### ISSUE TITLE
Text Letter Spacing is not applied correctly. Missing Space between "f" and "i"

### ISSUE THREAD

**Issue by SKnoedler** [flutter/flutter#110939] opened 2022-09-04 16:54 UTC
## Steps to Reproduce

1. Create a new flutter project
2. Paste the code sample below
3. run on Android

**Expected results:** 
Letter Spacing is applied between each letter

**Actual results:** 
Letter Spacing is missing between "f" and "i" (see screenshot)

![Bildschirmfoto 2022-09-04 um 18 50 15](https://user-images.githubusercontent.com/41230924/188324545-aa234037-8447-440e-b7a9-cd6f430d6ec6.png)

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(
        body: Center(
          child: Text(
            'Confirm',
            style: TextStyle(
              letterSpacing: 5.0,
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by aakansharamesh42** [comment] 2022-09-05 07:12
Hi, could you please assign this issue to me.

**Comment by danagbemava-nc** [comment] 2022-09-05 09:42
Issue is reproducible on `stable` and `master` using the code sample provided above.

In my testing, this only reproduced on `android` and `chrome-canvaskit`. All other platforms I tested worked just fine. 

<details>
<summary>screenshots</summary>

| macOS | canvaskit | HTML |
| -- | -- | -- |
| <img width="672" alt="Screenshot 2022-09-05 at 09 31 37" src="https://user-images.githubusercontent.com/88313112/188419072-47ace23a-6c80-4a89-ae19-47c6c618f7ee.png"> | <img width="657" alt="Screenshot 2022-09-05 at 09 33 03" src="https://user-images.githubusercontent.com/88313112/188419088-1954c73f-99c4-4468-b73e-1a8c1f06ae05.png"> | <img width="657" alt="Screenshot 2022-09-05 at 09 33 39" src="https://user-images.githubusercontent.com/88313112/188419095-395d40b4-3ff0-4654-b674-c1e556e52fe1.png"> |


| iOS | android |
| -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/188419099-1b7fbecd-c1f0-468c-8d51-0738a0c03baa.png" /> | <img src="https://user-images.githubusercontent.com/88313112/188419180-e34332e6-e89c-4c43-bf24-aeb8b0a7b3dd.png" /> |

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 13 Pro (mobile)      • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.72, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.72 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 202f5771f4 (9 hours ago), 2022-09-04 20:28:23 -0400
    • Engine revision b94120dfe9
    • Dart version 2.19.0 (build 2.19.0-168.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 13 Pro (mobile)      • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by GaryQian** [comment] 2022-09-06 17:15
This is likely a result of the layout engine treating the f and i together as a ligature, which is rendered as a single glyph. We should disable ligatures in cases like this to ensure the extra spacing is evenly applied.

@mdebbar

**Comment by GaryQian** [comment] 2022-09-06 17:17
@Rusino

**Comment by jason-simmons** [comment] 2022-09-08 00:27
You can work around this by disabling ligatures in the `TextStyle` using font features:
```
fontFeatures: <FontFeature>[FontFeature('liga', 0)],
```

The old Libtxt/MInikin text layout library will disable ligatures if letter spacing is enabled.
(see https://github.com/flutter/engine/blob/main/third_party/txt/src/minikin/Layout.cpp#L932)

Proposed a patch to add that to SkParagraph:
https://skia-review.googlesource.com/c/skia/+/578640

**Comment by gnprice** [comment] 2023-03-01 06:47
The above patch was merged in Skia. @SKnoedler Can you confirm whether the issue is fixed for you on the Flutter master channel?

**Closed** 2023-03-25 07:09 UTC
Labels: platform-android, waiting for customer response, engine, a: typography, platform-web, e: web_canvaskit, has reproducible steps, P4, found in release: 3.3, found in release: 3.4
