### ISSUE TITLE
Dynamic Size for a widget

### ISSUE THREAD

**Issue by ManmohanTalwar** [flutter/flutter#50261] opened 2020-02-06 08:18 UTC
Hello to the community!
I've been working with flutter, and it's very amazing how we can develop applications so quickly and for two platforms at the same time, everything is good.
But i think i've encountered a major issue in flutter, at least it's major to me, because every time you develop mobile application the size of our widget/view/container is not fixed. We can manage these by Flexible or Expanded widget but still we need to specify the size for the widget containing these widgets, which is ok in most of the cases, but for lets say one of the issue i'm facing is when, I'm trying to build a chat Screen for one of my projects and obviously we cannot figure out the height of the container showing the chat messages, one can send a one word message or multiple lines message, in this case the height property is becoming an issue to maintain. Tried using Wrap/Expanded/Flexible but nothings helps. Also tried using text.length property but it is also not accurate for maintaining the height of the container.
Maybe i'm looking in wrong direction but maybe it's a major issue which haven't been encountered yet.
Please help me guiding if i'm wrong.

```if (Prefs().id == http://entity.sender.id || entity.self) {
        return Container(
          height: entity.mText.length.toDouble() > 100
              ? (entity.mText.length.toDouble() > 200
                  ? entity.mText.length.toDouble()
                  : entity.mText.length.toDouble())
              : 80,
          child: Stack(
            overflow: Overflow.visible,
            fit: StackFit.loose,
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(4.0),
                child: Material(
                  borderRadius: BorderRadius.all(Radius.circular(36.0)),
                  color: white,
                  type: MaterialType.canvas,
                  child: Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.all(Radius.circular(36.0)),
                      color: white,
                    ),
                    child: Padding(
                      padding: EdgeInsets.only(
                          left: 36.0, right: 36.0, top: 4.0, bottom: 6.0),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Padding(
                            padding: EdgeInsets.only(top: 4.0, bottom: 6.0),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: <Widget>[
                                Text(
                                  Helper.stringForDatetime(entity.createdAt),
                                ),
                                Text(
                                  'You',
                                  style: TextStyle(
                                    color: black,
                                    fontSize: 16.0,
                                    fontWeight: FontWeight.w500,
                                  ),
                                )
                              ],
                            ),
                          ),
                          Expanded(
                            child: Text(
                              entity.mText,
                              style: TextStyle(
//                              fontFamily: 'Akrobat-SemiBold',
                                color: black.withOpacity(0.8),
                                fontSize: 15.0,
                              ),
                              maxLines: 30,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                top: 6.0,
                right: 0.0,
                width: 36.0,
                height: 36.0,
                child: Container(
                  decoration: BoxDecoration(
                    color: gamePink,
                    shape: http://BoxShape.circle,
                    border: Border.all(
                      color: white,
                      width: 1.5,
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      } else {
        return Container(
          height: entity.mText.length.toDouble() > 100
              ? (entity.mText.length.toDouble() > 200
                  ? 210
                  : entity.mText.length.toDouble())
              : 80,
          child: Stack(
            overflow: Overflow.visible,
            fit: StackFit.loose,
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(4.0),
                child: Material(
                  borderRadius: BorderRadius.all(Radius.circular(36.0)),
                  color: white,
                  type: MaterialType.canvas,
                  child: Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.all(Radius.circular(36.0)),
                      color: white,
                    ),
                    child: Padding(
                      padding: EdgeInsets.only(
                          left: 36.0, right: 36.0, top: 4.0, bottom: 6.0),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Padding(
                            padding: EdgeInsets.only(top: 4.0, bottom: 6.0),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: <Widget>[
                                Text(
                                  http://entity.sender.name,
                                  style: TextStyle(
//                                  fontFamily: 'Akrobat-SemiBold',
                                    color: black,
                                    fontSize: 16.0,
                                    fontWeight: FontWeight.w500,
                                  ),
                                ),
                                Text(
                                  Helper.stringForDatetime(entity.createdAt),
                                )
                              ],
                            ),
                          ),
                          Expanded(
                            child: Text(
                              entity.mText,
                              style: TextStyle(
//                              fontFamily: 'Akrobat-SemiBold',
                                color: black.withOpacity(0.8),
                                fontSize: 15.0,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                top: 6.0,
                left: 0.0,
                width: 36.0,
                height: 36.0,
                child: Container(
                  decoration: BoxDecoration(
                    color: gamePink,
                    shape: http://BoxShape.circle,
                    border: Border.all(
                      color: white,
                      width: 1.5,
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      }```


And if i don't specify any height or constraints it gives the following error:

RenderBox was not laid out: RenderDecoratedBox#13c4b relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'

Kindly help solving this issue!

**Comment by Zazo032** [comment] 2020-02-06 09:42
Not sure if it's what you're looking for, but you can get screen's `Size` using `MediaQuery.of(context).size` and then call `size.height` or `size.width`.

As there's missing code for reproducing the issue, if you're doing a chat messages screen, why don't you use a scrollable list for showing messages instead of a `Stack`?

**Comment by VladyslavBondarenko** [comment] 2020-02-28 11:07
@ManmohanTalwar 
I hope you've solved your problem
Closing since long time without an answer
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-02-28 11:07 UTC
Labels: waiting for customer response
