### ISSUE TITLE
[camera] Camera preview rotated by 90 degrees

### ISSUE THREAD

**Issue by hamdikahloun** [flutter/flutter#69113] opened 2020-10-27 15:50 UTC
## Steps to Reproduce

1. Download https://github.com/flutter/plugins/tree/master/packages/camera/example.
2. `flutter run`
3. Change the Android emulator orientation (Auto-rotate enabled)

**Actual results:** Camera preview rotated by 90 degrees

![image](https://user-images.githubusercontent.com/32666446/97325442-4867cd00-1873-11eb-9053-57b6712b0cbb.gif)

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[√] Flutter (Channel master, 1.24.0-4.0.pre.55, on Microsoft Windows [version 10.0.19041.572], locale fr-FR)
    • Flutter version 1.24.0-4.0.pre.55 at D:\fork\flutter
    • Framework revision e09688ad00 (2 days ago), 2020-10-25 03:12:02 -0400
    • Engine revision 95ec454993
    • Dart version 2.11.0 (build 2.11.0-256.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\hamdi\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\hamdi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30225.117
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\hamdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (2 available)
    • STK L21 (mobile)  • XMJ4C19B09007407 • android-arm64 • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64   • Microsoft Windows [version 10.0.19041.572]

• No issues found!
```

</details>

**Comment by hamdikahloun** [comment] 2020-10-27 16:05
cc @dnfield

**Comment by pedromassangocode** [comment] 2020-11-03 12:43
This is a duplicate of https://github.com/flutter/flutter/issues/39669 and there is https://github.com/flutter/flutter/issues/29500 that mention this same issue (and others) as well.

@hamdikahloun I'm closing this one in favor of the ones I mentioned above.
Please feel free to reopen if you think they are not the same.

**Closed by pedromassangocode** 2020-11-03 12:43 UTC
Labels: p: camera, p: first party, platform-android, plugin
