### ISSUE TITLE
video_player not smooth on lower end devices

### ISSUE THREAD

**Issue by pascal-reuse** [flutter/flutter#55198] opened 2020-04-20 12:32 UTC
I'm using the video_player in my flutter application on iOS to display and play a video from a local file, once it has loaded. I have followed the guide "[play and pause a video](https://flutter.dev/docs/cookbook/plugins/play-video)" from the flutter cookbook.

To play the video once after the load completed, I'm using the addPostFrameCallback from WidgetsBinding. The user can then replay the video by tapping on the video.

```dart
WidgetsBinding.instance.addPostFrameCallback((_) => afterBuild());
```

This works well most of the time but on older devices like the iPad air 1rst generation, occasionally, the video rendering is not smooth and drops some frames or a little bit of the audio while starting, creating like a choppy audio or video experience.

Note that I'm playing very short videos (~1 to ~3 seconds), I don't know if that can have an impact on the performance of the video_player (which might need a bit to launch the video and play it smoothly?)

Below is my current code.

It's been a while now I'm on that issue and don't know how to further troubleshoot. I already tried to delay a bit the first call to play the video (giving the player a bit more time), but this didn't fix the issue. Occasionally, the video will still not play smoothly.

Any idea what else to try?

Here is my code:

```dart
class MyVideoPlayer extends StatefulWidget {
  final File videoFile;

  MyVideoPlayer({Key key, this.videoFile}) : super(key: key);

  @override
  _MyVideoPlayerState createState() => _MyVideoPlayerState();
}

class _MyVideoPlayerState extends State<MyVideoPlayer> {
  VideoPlayerController _controller;
  Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    _controller = VideoPlayerController.file(widget.videoFile);

    WidgetsBinding.instance.addPostFrameCallback((_) => afterBuild());

    _controller.addListener(() async {
      if (_controller.value.duration != null &&
          _controller.value.position >= _controller.value.duration) {
        await _controller.seekTo(Duration(seconds: 0));
        await _controller.pause();
      }
    });

    _initializeVideoPlayerFuture = _controller.initialize();
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  _videoPressed() async {
    if (!_controller.value.isPlaying) {
     _controller.play();
    }
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _initializeVideoPlayerFuture,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: GestureDetector(
              onTap: () {
                _videoPressed();
              },
              child: VideoPlayer(_controller),
            ),
          );
        } else {
          return CircularProgressIndicator();
        }
      },
    );
  }

  void afterBuild() {
    _videoPressed();
  }
}
```

Here is the output of `flutter doctor -v`

```bash
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/MyUser/Documents/Dev/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/MyUser/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Device Name • device ID • ios • iOS 12.4.6
```

**Comment by darshankawar** [comment] 2021-03-03 11:38
@pascal-reuse 
Is this still a valid issue ? The `video_player` [plugin](https://pub.dev/packages/video_player/install) has gone through many updates since this issue was logged, so I'd recommend you to verify using latest plugin version with latest Flutter version (stable or master) and confirm if issue persists or not.

If yes, is there a way to provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to see the issue ?

**Comment by pedromassangocode** [comment] 2021-03-24 12:56
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-24 12:56 UTC
Labels: e: device-specific, p: video_player, platform-ios, plugin, waiting for customer response
