### ISSUE TITLE
NotifyIdle calls may overlap with rasterizer workloads.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#113796] opened 2022-10-20 21:07 UTC
Today, we try to interleave `NotifyIdle` calls between frame workloads on the UI thread. This is to ensure that the VM get as much information as possible on when to perform GCs. However, there isn't any consideration for workloads on the raster thread. When such calls overlap, the VM will attempt a GC when we are processing the raster thread workload for the frame. On lower end devices, this leads to core contention and dropped frame. This bug tracks reasoning about the accuracy of when we tell the VM that it is an appropriate time to perform a GC.
<img width="835" alt="Screen Shot 2022-10-19 at 2 17 17 PM" src="https://user-images.githubusercontent.com/44085/197058172-f0d4eb09-6a9a-480b-a7c0-5a152ed69f2c.png">

**Comment by chinmaygarde** [comment] 2022-10-20 21:08
cc @jonahwilliams @jason-simmons @zanderso. I tried to capture the talking points from yesterdays discussion. Not sure there is an action item just yet.

**Comment by jonahwilliams** [comment] 2022-10-20 21:25
I wonder if the expectation was that GC would not interfere with raster work, but we know that isn't really true now. I think a reasonable change would be to move the notify idle call to the end of the raster workload. Additionally, the delay seems a bit risky. I think we should be able to tell at the end of a frame if we'll have another frame scheduled. If not we can call it immediately?

**Comment by zanderso** [comment] 2022-10-20 21:35
cc @dnfield

**Comment by dnfield** [comment] 2022-10-21 04:02
NotifyIdle, as it's currently implemented, is kind of broken. But my understanding is that it wants to know about when it can do work on the UI thread, not when it's an optimal time to avoid thread contention.

It will frequently take only a small amount of time on the UI thread, but then spawn concurrent worker threads that greatly increase contention on low end devices.

If we wait until the end of rasterization, on a low end device we'll almost certainly be ready to start a new frame on the UI thread by that point.

IMHO, the bigger problem we have (even on higher end devices) is that I've observed a cheap/short frame that happens _right before animation starts_ with a long notify idle period that kicks of a GC which runs right as we start animating heavily.

I think the right thing to do here is to utilize the RAIL model more, but RAIL still could benefit from some hints about when the UI thread is free for animating. 

The time-delay current in place is meant to prevent us from accidentally notifying idle when we're actually trying to heavily animate, but I don't think it really works well and it has virtually zero test coverage.

**Comment by dnfield** [comment] 2022-10-21 04:03
@iskakaushik and @rmacnak-google have been looking at RAIL stuff more. @a-siva too.

**Comment by zanderso** [comment] 2022-10-21 16:05
I think my concern from looking at the timeline (the whole file is linked in chat), is that there are logic errors in the Engine code that calls NotifyIdle. It looks like NotifyIdle is being called in a way that goes against how we mean to use it. That is, it's being called in the middle of an animation, and it's being called ~immediately after a build method finishes. Both of those are wrong, AFAIU. It shouldn't be called in the middle of an animation, and there should be a delay between the last frame of an animation and the call to NotifyIdle (at least the comments in the code say there should be one...).

So this issue should be read as a suspicion that the current implementation is not working as intended, rather than an issue about the overall strategy or problems with trying to use it in the first place.

**Comment by jonahwilliams** [comment] 2022-10-21 21:33
If we're not calling NotifyIdle correctly, and its purely advisory, maybe we should disable it?

**Comment by rmacnak-google** [comment] 2022-10-21 21:51
NotifyIdle should be called during an animation with a short deadline, the remaining budget for the frame. This often allows scavenges to fit between frames, i.e., scavenges will happen after the UI thread has sent work to the GPU thread instead of before.

**Comment by dnfield** [comment] 2022-10-21 22:41
I think there are two concerns here.

1. NotifyIdle is getting called potentially every frame, without regard to whether we'll be trying to immediately pump a new frame again shortly. @iskakaushik was starting to look at whether we could signal whether we're in an animation intensive period for Flutter or not, but I'm not sure on the progress of that work. It's particularly sad in cases where we had a super cheap frame followed by a bunch of expensive ones.
2. NotifyIdle, per @rmacnak-google's comment, is meant to help schedule quick cheap GCs, but it often seems to trigger something cheap on the UI thread that then uses concurrency on other threads - IOW if the intention is to schedule quick scavenges we're often observing it schedule lengthy compactions.

**Comment by zanderso** [comment] 2022-10-24 18:36
Some more info:

<img width="1280" alt="Screen Shot 2022-10-24 at 11 33 04 AM" src="https://user-images.githubusercontent.com/6343103/197599855-5b394e41-92d6-4d47-a369-3cbacd541715.png">

The Engine is calling NotifyIdle with a deadline of ~2.5ms. The NotifyIdle call kicks off a concurrent mark. The UI thread is participating(?) in the concurrent mark in the form of a bunch of incremental marks, and it looks like the extra work leads to the frame coming in late.

**Comment by a-siva** [comment] 2022-11-01 19:15
This is the CL that enabled having the mutator thread participate in incremental marking during idle time https://dart-review.googlesource.com/c/sdk/+/229284, should we revisit this CL ?

**Comment by zanderso** [comment] 2022-11-01 21:38
I believe that @dnfield is planning to experiment with the `customer: chalk` app in a couple of different ways. Is there an easy way to experiment with turning it off locally?

**Comment by a-siva** [comment] 2022-11-01 22:21
The flag `mark_when_idle` would control that, but I see that the engine is not passing in this option, there is this code
in `runtime/dart_vm.cc`
```
    // 'mark_when_idle' appears to cause a regression, turning off for now.
    // "--mark_when_idle",
```
which seems to indicate somebody already noticed a regression and turned it off.

**Comment by dnfield** [comment] 2022-11-02 19:52
@a-siva - @rmacnak-google enabled that flag in https://github.com/flutter/engine/pull/31167 and you reverted it in https://github.com/flutter/engine/pull/31487.

IIRC, it had something to do with a benchmark on the low end Android device regressing, and we thought it had something to do with marking even small chunks taking a long time due to page faults.

I'm not sure if that's relevant to this issue or not though, because the trace that @zanderso was seeing was NotifyIdle calls where the GC was doing work far beyond the supplied budget.

**Comment by chinmaygarde** [comment] 2022-11-07 18:33
From Triage: @dnfield is going to have a chat with @rmacnak-google about this to figure out next steps.

**Comment by a-siva** [comment] 2022-11-14 17:32
CLs related to some of the items discussed in [doc](https://docs.google.com/document/d/1Gb8rtorpfrUMESGcTULht82VVB2JcM6ei_RV1FTCqCo/edit?resourcekey=0-zWq4UN4MCrAmKgUxlQsMVw#heading=h.3p4z6r9hvsaf)

https://dart-review.git.corp.google.com/c/sdk/+/269481
https://github.com/flutter/engine/pull/37539

**Comment by dnfield** [comment] 2022-11-14 18:52
https://github.com/flutter/engine/pull/37499 should help with this.

**Comment by dnfield** [comment] 2022-11-18 05:53
I think we could probably do better with something like what @mraleph had suggested here - https://github.com/flutter/flutter/issues/9594#issuecomment-322043099

If the VM gave the embedder tasks to run, we could choose to run them until we get a new frame scheduled, and continue to run them between frames rather than trying to hint the VM about how much time there is until we might be busy again.

**Comment by zanderso** [comment] 2022-11-18 16:14
We've also discussed inverting the relationship before in https://github.com/flutter/flutter/issues/89884 and https://github.com/flutter/flutter/issues/12567, but there have been some reservations as expressed in https://github.com/flutter/flutter/issues/89884#issuecomment-1032725245.

**Comment by dnfield** [comment] 2022-11-21 18:35
https://github.com/flutter/engine/pull/37737 should help a little with this - we will no longer call notify idle if the deadline is too short or in the past.

**Comment by chinmaygarde** [comment] 2022-11-28 18:33
Dan is OOO for a bit so removing his assignment. Lowering the priority now that the linked PRs have landed. We can close this after verification.

**Comment by dnfield** [comment] 2023-01-26 23:30
@zanderso do we have any recent traces from customer: chalk that are showing the undesirable behavior anymore? If not I think we should close this.

**Comment by zanderso** [comment] 2023-02-15 23:24
Took the `customer: chalk` app for a spin today, and did not see this issue. Closing.

**Closed by zanderso** 2023-02-15 23:24 UTC
Labels: engine, dependency: dart, P4, customer: chalk (g3)
