### ISSUE TITLE
Different Path needed when Loading Asset from DefaultAssetBundle

### ISSUE THREAD

**Issue by KeineKohleDev** [flutter/flutter#156475] opened 2024-10-09 14:24 UTC
### Steps to reproduce

Step one: Put a file in the Assets folder and add it to the pubpec.yml

Step two: try to load that file using the DefaultAssetBundle.of(context).loadAsString("filename");

Step three: Run the App on the Web. (No exceptions)

Step four: Run the App on Max (Exception: File not found)

Step five: add "assets/" before the file name and run it again on Mac. (No Exceptions). 

Step Six: Run the modified version on the Web. (No Exceptions).

### Expected results

I need to specify the path to a file for all platforms equally 

### Actual results

I need to specify the path to a file different depending on the platform i want to use.

### Code sample

<details open><summary>Code sample</summary>

```dart
String data = await DefaultAssetBundle.of(context).loadString("assets/map.json");
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "map.json".
The asset does not exist or has empty data.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.19.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/****/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/****/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.1)
    • IntelliJ at /Users/****/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.20629

[✓] Connected device (4 available)
    • iPhone von **** (mobile)        • 00008130-00167D842491401C • ios            • iOS 18.1 22B5054e
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.91
    ! Error: Browsing on the local area network for iPhone von ***. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by navaronbracke** [comment] 2024-10-09 14:44
Possibly a duplicate of https://github.com/flutter/flutter/issues/86833

**Comment by danagbemava-nc** [comment] 2024-10-10 06:50
This is indeed a duplicate of https://github.com/flutter/flutter/issues/86833. 

Kindly follow up in the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-10-10 06:50 UTC
Labels: in triage
