### ISSUE TITLE
TextField can no longer be focused after Navigator.pop

### ISSUE THREAD

**Issue by anaisbetts** [flutter/flutter#30929] opened 2019-04-11 19:04 UTC
After navigating, I can no longer use `requestFocus` to focus a TextField. This seems super related to #24436, #17098, and #27365, but unfortunately, this behavior is still broken as of the `1.4.15` tag, as well as the dev release `v1.4.7`

This bug is blocking me from releasing my app, any workaround or hack would definitely help me! 

## Steps to Reproduce

1. Clone https://github.com/paulcbetts/flutter-textfocus-repro
1. Click the text field at the top, type some text
1. Hit the Clear button - note that the TextField is still focused and typing still works
1. Hit the Push button, wait for 5 seconds for the page to pop back
1. Hit the Clear button again - now we are in this pseudo-focused state where typing just goes into the Ether

## Logs

```
[   +2 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:61760/
[   +1 ms] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+7487 ms] D/skia    ( 7780): Program linking failed.
[  +87 ms] D/skia    ( 7780): Program linking failed.
[+2099 ms] D/skia    ( 7780): Program linking failed.
[  +40 ms] W/IInputConnectionWrapper( 7780): getTextBeforeCursor on inactive InputConnection
[  +13 ms] W/IInputConnectionWrapper( 7780): getSelectedText on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper( 7780): getTextAfterCursor on inactive InputConnection
[  +33 ms] D/skia    ( 7780): Program linking failed.
[  +61 ms] D/skia    ( 7780): Program linking failed.
[+2544 ms] D/skia    ( 7780): Program linking failed.
[+6189 ms] D/skia    ( 7780): Program linking failed.
```

```
[√] Flutter (Channel dev, v1.4.7, on Microsoft Windows [Version 10.0.18362.30], locale en-US)
    • Flutter version 1.4.7 at C:\Users\ana\flutter
    • Framework revision 1bfa2f2311 (13 days ago), 2019-03-29 10:05:18 -0700
    • Engine revision c4d14a0071
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ana\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
```

**Comment by GaryQian** [comment] 2019-04-11 20:41
@justinmc

**Comment by justinmc** [comment] 2019-04-11 21:51
It does seem like this might be a bug.  Maybe someone with more knowledge of how our focus works can say what the expected behavior is.

Since you're open to workarounds though, you can probably await the `Navigator.push` and manually set focus again:

```dart
...
            RaisedButton(
                child: Text("Push"),
                onPressed: () async {
                  await Navigator.push(this.context,
                      MaterialPageRoute(builder: (_) => ModalDialogWidget()));
                  FocusScope.of(this.context).requestFocus(focusNode);
                }),
...
```

**Comment by paulcbetts** [comment] 2019-04-11 23:02
@justinmc that works for me!!!! Thanks so much for the suggestion!

**Comment by gspencergoog** [comment] 2019-05-07 18:03
Nowadays, you should also be able to just do `focusNode.requestFocus()`, but it sounds like you have something that works. Closing this.

**Closed by gspencergoog** 2019-05-07 18:03 UTC
Labels: a: text input, framework
