### ISSUE TITLE
W/HiTouch_PressGestureDetector(25375): Touch pointer move a lot. The moving distance of X is:3.0, limit is:60The moving distance of Y is:91.0, limit is:60

### ISSUE THREAD

**Issue by ImTTTT** [flutter/flutter#69004] opened 2020-10-26 04:55 UTC
I used `cached_network_image` and  scroll the page fast. 
This error only occurs on Android

the crash log
```
W/HiTouch_PressGestureDetector(25375): Touch pointer move a lot. The moving distance of X is:3.0, limit is:60The moving distance of Y is:91.0, limit is:60
E/flutter (24236): [ERROR:flutter/lib/ui/painting/image_descriptor.cc(181)] Failed to get pixels for image.
F/libc    (24236): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 24391 (lutter_bilibili), pid 24236 (lutter_bilibili)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/STK-L22/HWSTK-HF:10/HUAWEISTK-L22/10.0.0.270C636:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2020-10-26 11:49:38+0700
pid: 24236, tid: 24391, name: ssss_bilibili  >>> com.ssss.xxxx <<<
uid: 11158
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000000000000000  x3  0000007268d9b658
    x4  000000000000009b  x5  00000072dfc90410  x6  0000000000000000  x7  0000000000000000
    x8  0000007268d9b688  x9  0000000000000000  x10 0000000000000000  x11 0000000000000000
    x12 000000726fa05990  x13 0000000001000000  x14 0000000000000000  x15 0000000000000000
    x16 0000007364369938  x17 000000736435d970  x18 0000007263a18000  x19 0000007268d9b718
    x20 0000000000000000  x21 0000007268d9b678  x22 000000000000021a  x23 0000000000000320
    x24 000000726b84b9a6  x25 0000000000000000  x26 0000000000000001  x27 0000000000000055
    x28 0000000000000000  x29 0000000000000000
    sp  0000007268d9b670  lr  000000726c9d4a34  pc  000000726c9d4a34
backtrace:
      #00 pc 0000000001342a34  /data/app/com.opsdoc.flutter_bilibili-sWSJGQIHK2TX0Rgm9nszfg==/lib/arm64/libflutter.so (BuildId: 8d68c575944b2191a8d461c9d04ec82c003e099c)
      #01 pc 00000000000f780c  <anonymous:7268ca4000>
```

my environment:
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/mac/development/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone X Test (mobile) • 81fbc73666adb52318506fb12f08c6d9b28a0a85 • ios • iOS 14.0.1

```

**Comment by pedromassangocode** [comment] 2020-10-26 06:42
Hi @ImTTTT 
Can you provide a minimal reproducible code sample?

**Comment by pedromassangocode** [comment] 2020-10-26 06:49
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/69004#issue-729234064

**Comment by ImTTTT** [comment] 2020-10-26 08:09
I found that it was caused by loading an encrypted picture.

load Image code:
```
  Widget _buildImage() {
    return CachedNetworkImage(
        imageUrl: url,
        width: width,
        height: height,
        fit: fit,
        placeholder: (context, s) => placeholderWidget == null ?_buildPlaceholderWidget() : placeholderWidget,
        errorWidget: (context, s, e) {
          return errorWidget == null ? _buildErrorWidget() : errorWidget;
        });
  }
```
download and decode code:
```
class HttpDecodeFileService implements FileService {
  
  ...

  @override
  Future<FileServiceResponse> get(String url,
      {Map<String, String> headers = const {}}) async {
    final httpResponse = await _httpClient.get(url);
    return HttpDecodeGetResponse(httpResponse,url);
  }
}

class HttpDecodeGetResponse implements FileServiceResponse {
...

  @override
  // TODO: implement content
  Stream<List<int>> get content =>   Stream.fromFuture(FlutterAesEcbPkcs5.decryptOrigin(_response.bodyBytes, DefaultCacheManager.AES_KEY));
...
}

```

**Comment by mraleph** [comment] 2020-10-26 08:16
@ImTTTT none of the ARM64 engines at `75bef9f6c8` have build-id matching the one from the crash. Are you sure you provided correct version info?

**Comment by ImTTTT** [comment] 2020-10-26 08:47
@mraleph    
This is the environment when I crashed，
```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
    • Flutter version 1.22.2 at /Users/mac/development/flutter
    • Framework revision 84f3d28555 (10 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • ELS NX9 (mobile) • K5J0220310000234          • android-arm64 • Android 10 (API 29)
    • iPhone (mobile)  • 00008020-00044D4C0181002E • ios           • iOS 13.7

```

**Comment by mraleph** [comment] 2020-10-26 09:43
@flutter-symbolizer-bot engine#b8752bbfff

**Comment by chinmaygarde** [comment] 2020-10-26 18:09
This should be fixed by https://github.com/flutter/engine/pull/21891. Can you reproduce this on `master`?

**Comment by allansrc** [comment] 2020-10-26 20:33
@chinmaygarde I've this same Issue, how should I proceed to fix from this merged RP?

**Comment by pedromassango** [comment] 2020-10-26 21:24
@allansrc you can try the `master` branch. It should have the fix!

**Comment by allansrc** [comment] 2020-10-27 14:02
Still gettin ""[VERBOSE-2:image_descriptor.cc(181)] Failed to get pixels for image""

**Comment by pedromassango** [comment] 2020-10-27 21:23
Hi @allansrc 
According to the message the issue may be caused by an invalid image data. Can you verify that the image you are using is valid?

**Comment by allansrc** [comment] 2020-10-27 23:07
> Hi @allansrc 
> According to the message the issue may be caused by an invalid image data. Can you verify that the image you are using is valid?

Yah, its was working perfectly till i upgraded flutter stable

**Comment by davidmartos96** [comment] 2020-11-04 20:36
Hello, we are having the same issue and it is very critical for our app because it relies on thousands of images that come from third party APIs, which we don't have control of. 
Are there any plans to cherrypick the fix from @chinmaygarde into stable? The fix works correctly on master for us.
We did consider going back to Flutter 1.20.4, but since iOS 14 is out, we can't because of the other bugs fixed on 1.22. 
As said, it's quite critical for our app. We wouldn't mind the invalid images not showing, but those crashes are unacceptable because those invalid images are being cached between restarts.
If there are other workarounds we would be very happy to hear them.

**Comment by pedromassangocode** [comment] 2020-11-27 12:42
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-27 12:42 UTC
Labels: P4, a: images, engine, platform-android, severe: crash, waiting for customer response

**Comment by saged87** [comment] 2020-12-04 19:01
same Issue, any update on how to fix it ?

**Comment by saged87** [comment] 2020-12-04 19:15
`[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en)
    • Flutter version 1.22.2 at /Users/saged/Development/flutter
    • Framework revision 84f3d28555 (7 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/saged/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 921387f30ea1613645f6c89741c131c381015640 • ios • iOS 12.4.9

! Doctor found issues in 1 category.
`

**Comment by davidmartos96** [comment] 2020-12-05 14:44
@saged87 What we did is release our app with a locally compiled Flutter engine, cherripicking this commit https://github.com/flutter/engine/pull/21891
We haven't had crashes since we did that

**Comment by wengxianxun** [comment] 2021-01-27 07:42
Image.network(
              "http://tx-ec.static.yximgs.com/ufile/adsocial/37bd45fa-732d-4508-b82f-55db3223bddd.jpg",
              width: 300,
              height: 300,
            ),

这段代码会导致闪退，iOS和android都会
