### ISSUE TITLE
Make PrimaryScrollController attachment to a Scaffold be optional

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#105376] opened 2022-06-05 01:25 UTC
Many of us are still having ongoing problems with losing scroll to top functionality in iOS as part of a nested Scaffold structure when it is part of a bottom navigation bar.  

Usually there is a topmost Scaffold that contains the app content and the bottomnavigationbar.   Within the app content, there may be a series of sub-pages that each contain a Scaffold.  

When the status bar is tapped, the very top most Scaffold used to build the framework and navigation bar soaks up the tap, and it doesn't work on the actual content page a user is looking at

So far the only solution is to switch to a CupertinoPageScaffold, however it presents some problems with maintaining fluid cross platform support when the app is run on Android

There have so far been a few Issues made about this problem:
https://github.com/flutter/flutter/issues/85603
https://github.com/flutter/flutter/issues/95836
https://github.com/flutter/flutter/issues/74727
https://github.com/flutter/flutter/issues/96696
https://github.com/flutter/flutter/issues/92119

The question is, can we simply have an optional flag to choose if we want the PrimaryScrollController to be attached to a Scaffold when we create it?  That way we could very easily and in a straightforward way avoid this problem?

**Comment by darshankawar** [comment] 2022-06-06 07:24
Treating this as a proposal and labeling for further insights from the team.

Related: https://github.com/flutter/flutter/pull/102099

**Comment by darshankawar** [comment] 2022-06-06 07:31
Actually, I just found out that this is duplicate of https://github.com/flutter/flutter/issues/19732, so please follow-up in it for further updates.

**Comment by mark8044** [comment] 2022-06-06 13:44
> Actually, I just found out that this is duplicate of #19732, so please follow-up in it for further updates.

I don't know if this is a duplicate.  In #19732 they are discussing passing a primaryscrollcontroller to the Scaffold, whereas here the idea is a bool flag to have Scaffold simply not attach a primaryscrollcontroller and let us deal with things on our own

**Comment by darshankawar** [comment] 2022-06-07 05:33
Thanks for the feedback. I had gone through this issue https://github.com/flutter/flutter/issues/100264 which is specifically for desktop apps as mentioned, but your request seems to be for mobile platform. Based on your feedback, I am reopening this issue.

/cc @Piinks

**Comment by Piinks** [comment] 2022-06-07 14:58
> here the idea is a bool flag to have Scaffold simply not attach a primaryscrollcontroller and let us deal with things on our own.

I am not sure that this will resolve your issue, the Scaffold is not attached to a PrimaryScrollController. I may not be understanding your request, so can you share what you mean? How would you handle it yourself? What would you expect the API to look like that allows you to manage it?

> a nested Scaffold will have its own PrimaryScrollController

I am not sure this is true either. The Scaffold does not add a PrimaryScrollController to the tree. It only looks up the closest enclosing PSC to animate the scroll view.

I am not entirely sure what this issue is requesting, the referenced issues are all slightly different. Can you please provide a minimal sample of code that demonstrates your issue? It sounds like you have a nested Navigator like #85603.

A default PrimaryScrollController is provided in every route - so that may be where you are experiencing your issue, not in the Scaffold. More information will help us resolve this issue. Thanks!

**Comment by mark8044** [comment] 2022-06-08 02:41
> > here the idea is a bool flag to have Scaffold simply not attach a primaryscrollcontroller and let us deal with things on our own.
> 
> I am not sure that this will resolve your issue, the Scaffold is not attached to a PrimaryScrollController. I may not be understanding your request, so can you share what you mean? How would you handle it yourself? What would you expect the API to look like that allows you to manage it?
> 
> > a nested Scaffold will have its own PrimaryScrollController
> 
> I am not sure this is true either. The Scaffold does not add a PrimaryScrollController to the tree. It only looks up the closest enclosing PSC to animate the scroll view.
> 
> I am not entirely sure what this issue is requesting, the referenced issues are all slightly different. Can you please provide a minimal sample of code that demonstrates your issue? It sounds like you have a nested Navigator like #85603.
> 
> A default PrimaryScrollController is provided in every route - so that may be where you are experiencing your issue, not in the Scaffold. More information will help us resolve this issue. Thanks!

Ah ok, yes I'm likely misunderstanding the relationship between `Scaffold` and PSC.

The problem does at its core revolve around https://github.com/flutter/flutter/issues/85603 but over there, most of the solutions seem to have dead-ended on requesting a change to the core relationship between `Scaffold` and PSC. Here I was hoping for something a little different and more simple, but I may be misunderstanding.

So let me take a step back, this is quoted from what you wrote in this that thread:

```
Route
  - PrimaryScrollController // Connected to Tap 1, used by Scaffold below
    - Scaffold
      - ListView // Tap 1 - connected to the above controller
      - Route // From nested Navigator
        - PrimaryScrollController // Connected to Tap 2
          - ListView // Tap 2
```

I'll modify it to the way I'm using it and I think some people with multiple bottom navigation tabs are using it:

```
Scaffold / PSC-1
  |-> Content (switches based on what tab you have active)
       - Scaffold Tab 1 / PSC-2
              - Listview 1
        - Scaffold Tab 2 / PSC-3
               - Listview 2
        - Scaffold Tab 3 / PSC-4
               - Listview 3
  |-> BottomNavigationBar
 ```

The problem between the two examples is the same, when you tap on the top status bar, `Scaffold / PSC-1` is taking that tap and Listview 1/2/3 do not scroll up.

I *wrongly* thought Scaffold was generating PSC-1 and the two were tied together, so that maybe we could tell Scaffold not to generate PSC-1.

The reason I have this Idea is that if I simple change `Scaffold / PSC 1` to a `Stack` then everything works perfectly

Heres some code, where bottom navigation is present, but scroll to top **does not work**, in this example, each of the children in the IndexedStack is a Scaffold:
```
return 
    Scaffold(
        body: 
         IndexedStack(
                key: ...
                index: currentIndex,
                children:
                    pages.map((page) => page ?? SizedBox.shrink()).toList(),
              )
        bottomNavigationBar: widget.bottomNavigationBar()
      );
```

Simple changing this to a `Stack` corrects everything:
```
   return 
        Stack(
          children:[
            Expanded(
                child:Container(
                    child:
                     IndexedStack(
                  key: ValueKey<int>(widget.savePageState ? 0 : currentIndex),
                  index: currentIndex,
                  // If the page is not initialized, "not show" an invisible widget instead.
                  children:
                  pages.map((page) => page ?? SizedBox.shrink()).toList(),
                     )
                )),
            Align(alignment:Alignment.bottomCenter,child:widget.bottomNavigationBar()),
          ]
    );
```

Now yes the easiest answer is: hey then don't use a top level scaffold, use the Stack!  But it presents a whole lot of other problems with the bottom navigation bar overlapping content, especially the floating action button and things like snack bars getting misplaced

Another thing someone might say is, hey why not just remove the `Scaffold` from each subpage, OR pass the top level PSC down to each of those tabs.  The problem is that we then get very bad behavior with multiple list views attached to the same PSC, either with outright errors or all the list views on all tabs simultaneously scrolling up when the top bar is tapped.  Having multiple parallel `Scaffold` like this helps to keep everything isolated and tidy, except for this scroll to top issue.

So at the core of what I'm saying is that I *thought* that `Scaffold` was creating the PSC, but you are saying that is not true.  In the above layout, is there a way to simple not have that top level PSC so that each of the `Scaffold`'s own PSC can see the scroll to top, as it seems to be working in my second example where `Scaffold` is replaced by `Stack`?

**Comment by Piinks** [comment] 2022-06-08 22:02
> is there a way to simply not have that top level PSC so that each of the sub-Scaffold's own PSC can see the scroll to top

I do not think so, because the inner Scaffold does not receive the tap. Only the outer Scaffold contains the status bar. When the status bar is tapped (within a Scaffold) that Scaffold looks up the PSC and animates whatever scrollview is attached to it.

It looks like in your case you want the inner Scaffold to handle this, but that Scaffold does not contain the status bar.

Some runnable sample code would be very helpful in being able to help you further. Thanks!

**Closed** 2022-06-29 22:10 UTC
Labels: platform-ios, waiting for customer response, framework, f: material design, f: scrolling, proposal
