### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by Juthisarker** [flutter/flutter#33645] opened 2019-05-31 09:09 UTC
I'm developing my flutter app on macOS. But when I want to debug the app on my windows machine, it shows this error

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: ad97007bddb2687e)

This crash report written on log file. The log file is given below

## command

flutter run --machine -t lib\main.dart -d B3698Y11HA4122 --track-widget-creation --start-paused

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'D:\hcbmobile\.flutter-plugins' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:636:5)
#4      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:99:17)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:292:24)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:175:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:111:11)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:51:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#40     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.6.3, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
    [32m•[39m Flutter version 1.6.3 at D:\flutter
    [32m•[39m Framework revision bc7bc94083 (8 days ago), 2019-05-23 10:29:07 -0700
    [32m•[39m Engine revision 8dc3a4cde2
    [32m•[39m Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: D:\android\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at D:\android
    [32m•[39m Flutter plugin version 33.3.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m Connected device (1 available)
    [32m•[39m Symphony P7 PRO • B3698Y11HA4122 • android-arm64 • Android 6.0 (API 23)

[32m•[39m No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-10-08 13:16
Duplicate of #31135. @Juthisarker Please check the comment https://github.com/flutter/flutter/issues/31135#issuecomment-504404817 and reply if that work, or did you manage to solve it before.

**Closed by BondarenkoStas** 2019-10-08 13:16 UTC
