### ISSUE TITLE
[image_picker_modern] Android build failed

### ISSUE THREAD

**Issue by Losspost** [flutter/flutter#43081] opened 2019-10-20 10:46 UTC
## Steps to Reproduce

1. Added image_picker_modern: 0.4.12+3 to pubspec.yaml
2. Added to Screen : 
```dart
Future takePicture() async{
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);

    setState(() {
      _image = image.path;
    });
  }
```
3. Running the App

**Target Platform: Smartphone**
**Target OS version/browser: Android**
**Devices:**

## Logs

```
                    > Configure project :app
                    WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
                    WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

                    > Configure project :image_picker_modern
                    WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
                             *********************************************************
                    WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
                             See https://goo.gl/CP92wY for more information on the problem and how to fix it.
                             This warning prints for all Android build failures. The real root cause of the error may be unrelated.
                             *********************************************************
[   +7 ms] Resolving dependencies... (completed in 1.9s)
[   +4 ms] * Error running Gradle:
           ProcessException: Process "C:\Users\tobia\StudioProjects\shoplocalflutter\android\gradlew.bat" exited abnormally:
           
           > Configure project :app
           WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
           WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
           
           > Configure project :image_picker_modern
           WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
                    *********************************************************
           WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
                    See https://goo.gl/CP92wY for more information on the problem and how to fix it.
                    This warning prints for all Android build failures. The real root cause of the error may be unrelated.
                    *********************************************************
             Command: C:\Users\tobia\StudioProjects\shoplocalflutter\android\gradlew.bat app:properties
           
[   +9 ms] "flutter run" took 3,318ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:233:7)
<asynchronous suspension>
#2      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:164:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#29     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

```
Analyzing shoplocalflutter...

   info - Name non-constant identifiers using lowerCamelCase - lib\firebase\add_your_shop.dart:30:22 - non_constant_identifier_names
   info - Unused import: 'package:shop_local/firebase/find_item.dart' - lib\screens\item_screen.dart:3:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\screens\item_screen.dart:19:10 - non_constant_identifier_names
   info - Unused import: 'package:firebase_auth/firebase_auth.dart' - lib\screens\login_register_screen.dart:1:8 - unused_import
   info - Unused import: 'package:shop_local/firebase/firebase_auth.dart' - lib\screens\login_register_screen.dart:3:8 - unused_import
   info - The value of the field '_email' isn't used - lib\screens\login_register_screen.dart:26:10 - unused_field
   info - The value of the field '_password' isn't used - lib\screens\login_register_screen.dart:27:10 - unused_field
   info - The value of the field '_buisness' isn't used - lib\screens\login_register_screen.dart:29:8 - unused_field
   info - The value of the field '_keeploggedin' isn't used - lib\screens\login_register_screen.dart:30:8 - unused_field
   info - The value of the field '_formType' isn't used - lib\screens\login_register_screen.dart:32:12 - unused_field
warning - The parameter 'onPressed' is required - lib\screens\login_register_screen.dart:71:15 - missing_required_param
   info - Unused import: 'package:shop_local/screens/login_register_screen.dart' - lib\screens\login_screen.dart:3:8 - unused_import
   info - The value of the field '_buisness' isn't used - lib\screens\login_screen.dart:28:8 - unused_field
   info - Unused import: 'package:shop_local/screens/new_shop.dart' - lib\screens\profile_screen.dart:4:8 - unused_import
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: MainProfileScreen.context - lib\screens\profile_screen.dart:41:7 - must_be_immutable
   info - Unused import: 'dart:ffi' - lib\screens\shop_managment_item_add_screen.dart:1:8 - unused_import
   info - Unused import: 'package:shop_local/firebase/find_your_shops.dart' - lib\screens\shop_managment_item_screen.dart:3:8 - unused_import
   info - Unused import: 'package:flutter/material.dart' - lib\singletons\shop_data.dart:1:8 - unused_import

```

```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17763.805], locale en-GB)
    • Flutter version 1.9.1+hotfix.5 at E:\Produktivitaet\flutter
    • Framework revision 1aedbb1835 (3 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\tobia\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: E:\Produktivitaet\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at E:\Produktivitaet\Android\AndroidStudio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.38.1)
    • VS Code at C:\Users\tobia\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • MI 9 • fe1cd410 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```
I tried the solution of : https://github.com/flutter/flutter/issues/42910 but it didnt work.
Can anyone help me?

**Comment by akshay512** [comment] 2019-10-20 12:17
Try migrating to gradle to 3.5.1

**Comment by Losspost** [comment] 2019-10-20 13:16
I am already at 5.4.1

**Comment by akshay512** [comment] 2019-10-20 16:22
Did u try using image_picker: instead of which you are using for picking image.

**Comment by akshay512** [comment] 2019-10-20 16:27
It depends on your use case, if your use case doesn't require some features that are in image_picker_modern: you can try the previous plugin or May be the problem is with the image_picker_modern: version then try downgrading the version.

**Comment by Losspost** [comment] 2019-10-20 16:56
I tried image_picker which worked.

**Comment by akshay512** [comment] 2019-10-20 23:55
Then it's fine I guess.

**Comment by janmoppel** [comment] 2019-10-21 08:28
Hello @Losspost !

Thank you for posting an issue.
Have you tried to contact the developers of `image_picker_modern`? As you said, with `image_picker` plugin, build doesn't fail, it means that there is no problem with an official plugin.

**Comment by akshay512** [comment] 2019-10-21 12:47
If u want to use that plugin try downgrading version below "0.4.12+3".

**Comment by Losspost** [comment] 2019-10-21 14:57
@janmoppel No. I thougth image_picker_modern was the new/modern version of it.

**Comment by blasten** [comment] 2019-10-22 18:00
@truongsinh  would you mind taking a look at this issue?

**Comment by truongsinh** [comment] 2019-10-27 15:25
@Losspost  sorry for the inconvenience, this plugin was a fork of the 1st party plugin, which is now already at 0.6.x. I see that you have to problem using 1st party plugin. At that time, it seems (to me) that it is sensible to have the fork, but since then things have changed and it is recommended to use `image_picker` instead.

I will have a warning message on `image_picker_modern` to avoid other confusion. Meanwhile, if it there is no other problem with you, I think we can close this issue.

**Comment by jonahwilliams** [comment] 2020-01-09 17:40
Sounds like there was some confusion around image_picker_modern, and this is otherwise resolved

**Closed by jonahwilliams** 2020-01-09 17:40 UTC
Labels: severe: crash, t: gradle, tool, ▣ platform-android
