### ISSUE TITLE
Mac plugin_lint_mac failing: Couldn't determine repo type for URL: `https://cdn.cocoapods.org//`: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#112130] opened 2022-09-22 00:17 UTC
```
[plugin_lint_mac] [STDOUT] Flutter root at /opt/s/w/ir/x/w/recipe_cleanup/tmpba8j6fab/flutter sdk
[plugin_lint_mac] [STDOUT] Executing "pod lib lint /opt/s/w/ir/x/w/recipe_cleanup/tmpba8j6fab/flutter sdk/packages/integration_test/ios/integration_test.podspec --use-libraries --verbose" in "/opt/s/w/ir/x/t/flutter_plugin_test.2mLq07" with environment {BOT: true, LANG: en_US.UTF-8}
[plugin_lint_mac] [STDOUT] stdout: 
[plugin_lint_mac] [STDOUT] stdout: [!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org//`: SSL_connect returned=1 errno=0 peeraddr=172.67.74.167:443 state=error: certificate verify failed (unable to get local issuer certificate)
[plugin_lint_mac] [STDOUT] stdout:
```
https://ci.chromium.org/p/flutter/builders/prod/Mac%20plugin_lint_mac/8945

Tree closed.

**Comment by jmagman** [comment] 2022-09-22 00:23
Failures seem to be happening only on arm hosts, maybe related to https://github.com/flutter/flutter/pull/109889, though `plugin_lint_mac` did pass on an arm machine on that PR in presubmit.

https://status.cocoapods.org/ doesn't report any issues, not sure why there would be a cert failure.

**Comment by jmagman** [comment] 2022-09-22 00:33
More builders with the same issue:

https://ci.chromium.org/p/flutter/builders/prod/Mac%20build_ios_framework_module_test/8834
https://ci.chromium.org/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/7268

**Comment by jmagman** [comment] 2022-09-22 00:51
https://github.com/flutter/flutter/issues/112117 merged, that should reopen the tree, and then this priority can be lowered.

Still need to figure out what's up with the ssl certs on these machines.

**Comment by keyonghan** [comment] 2022-09-22 04:56
There are two issues with `Mac plugin_lint_mac`:
1) fails on arm64 bots (the certificate verify failure)
2) flake on x64 bots. Created https://github.com/flutter/flutter/issues/112146 to track

As for 1), the builder [succeeds](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/69b0e0eb2275d6565117422dcb4257a4c4773b66d84f934b88f53b3f031be8f9/+/build.proto) in `try` pool, but [fails](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/6df0b0b01415a377beac5dc9e5e09be9d1ac1f8dc14e5eaca102769cb4fef5d4/+/build.proto) in `prod` pool. Filed https://crbug.com/1366657 to see if any differences between these two pools.

**Comment by keyonghan** [comment] 2022-11-01 16:40
All try and prod bots are configured the same without any difference: https://crbug.com/1366657.

Will rerun LED builds to confirm the issue is still reproducible before asking to reinstall prod bots.
(LED runs on arm64 bots are currently blocked on https://github.com/flutter/flutter/issues/113231)

**Comment by godofredoc** [comment] 2022-12-14 00:37
@yusuf-goog FYI

**Comment by StillOnMyWay** [comment] 2022-12-26 19:57
Experiencing the same. 

arm based Mac Metal 2 (M1 chip) EC2 INSTANCE. Pod install output in the terminal producing `couldn't determine repo type for url: `https://cdn.cocoapods.org/`: ssl_connect returned=1 errno=0 peeraddr=172.67.74.167:443 state=error: certificate verify failed (unable to get local issuer certificate)`

**Comment by godofredoc** [comment] 2023-01-13 21:20
@StillOnMyWay this is caused by your version of ruby not being able to find the cacerts.pem. I'd recommend to uninstall/install your system's ruby and ensure that it takes precedence over the one bundle with xcode.

**Comment by godofredoc** [comment] 2023-01-13 21:20
Fixed with hermetic ruby bundles and https://flutter-review.googlesource.com/c/recipes/+/38088.

**Closed by godofredoc** 2023-01-13 21:20 UTC
Labels: team: infra, P3

**Comment by jmagman** [comment] 2023-01-13 21:45
Thank you!
