### ISSUE TITLE
[web]: <Web App Showing Old Version After Publish New Version>

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#61878] opened 2020-07-20 17:16 UTC
<script src="main.dart.js?version=2" type="application/javascript"></script>
1- each time i change the version for hosting web site butt browser showing old version until i clear my browser cache history or ( if i type url and press enter button page showing old stuff butt if i press reload button twice then browser show new changes.
2- first time loading take much time while mobile app load instantly .
3- web app stuff not searchable by google search engine SEO.

**Comment by TahaTesser** [comment] 2020-07-21 09:00
Hi @abdulrehmananwar 
1. Providing version is working as intended, it's just a workaround, there is a issue for it https://github.com/flutter/flutter/issues/57391
2. web app needs loading since it's literally in the browser, mobile apps don't need loading
3. There is already an open issue  https://github.com/flutter/flutter/issues/46789

Closing. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-21 09:00 UTC
