### ISSUE TITLE
[plugin][camera] Crash due to race condition in `_dispatchQueue`

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#95045] opened 2021-12-10 21:02 UTC
This crash is found when I was playing around with camera plugin

**Crash**
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureAudioDataOutput setSampleBufferDelegate:queue:] NULL queue passed'
terminating with uncaught exception of type NSException
```

**Reproduce**
(1) In sample app, start video recording then stop it. 
(2) Swipe home bar just a bit on iPhone X, so the app becomes inactive and immediately regain active. 
(3) Tap the video button again and observe this crash. 

**Root Cause**
`_dispatchQueue` is checked in main thread, but set to nil in background thread, which is open to race condition: 
```
  // main thread: 
  if (_dispatchQueue == nil) {
    _dispatchQueue = dispatch_queue_create("io.flutter.camera.dispatchqueue", NULL);
  } 

  // background thread 
 _dispatchQueue = nil
```

**Explain**
In the above reproduce step, (1) is to assign a new `_dispatchQueue`, (2) is to trigger "dispose" and "create" method calls consecutively, resulting in a race condition, and (3) will pass in the `_dispatchQueue` which has been nil'ed out asynchronously. 

**Solution**
(1) It looks like the camera plugin has pretty complicated threading logic and it's getting hard to maintain. There have been multiple related issues. If we get time I am interested in refactoring the threading model in the future. 
(2) For now an easy fix to this race condition is not to nil out this `_dispatchQueue`. DispatchQueues are quite lightweight as they are not actual threads. 
(3) Or we can dispatch to main thread again before setting nil, which should fix `_dispatchQueue` race for this particular case, but may still open for other unknown cases

**Comment by jmagman** [comment] 2021-12-10 21:46
This looks like a duplicate of https://github.com/flutter/flutter/issues/59124, but @hellohuanlin I see you commented in that one.  Do you have reason to believe this is a different issue?

**Comment by hellohuanlin** [comment] 2021-12-10 21:52
@jmagman the original issue does not have a repro step so it's hard for me to tell without more info.

**Comment by jmagman** [comment] 2021-12-10 22:09
Let's close this one in favor of that one.  You can add all the details and your repro steps there!

**Comment by hellohuanlin** [comment] 2021-12-10 22:10
@jmagman sounds good!

**Closed by jmagman** 2021-12-10 22:09 UTC
Labels: platform-ios, plugin, p: first party, p: camera, has reproducible steps
