### ISSUE TITLE
Unhandled Exception: PlatformException(java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Number, ClassCastException, Cause: null, Stacktrace: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Number

### ISSUE THREAD

**Issue by DanferMCH** [flutter/flutter#156599] opened 2024-10-11 16:41 UTC
### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock

  google_maps_flutter: ^2.9.0
```

</details>

### Steps to reproduce

Estoy usando la ultima versio de flutter  3.24.2  y he presentado un proble al moemnto de ejecutar mi codigo :
 LatLngBounds latLngBounds = LatLngBounds(
      southwest: LatLng(-13.416372, -76.139882), 
      northeast: LatLng(-13.417006, -76.132952), 
    );

    print(latLngBounds);

      setState(() {
        googleMapController
            .animateCamera(CameraUpdate.newLatLngBounds(latLngBounds, 70));
      });

### Expected results

Devolver una actualización de la cámara que transforma la cámara para que el cuadro delimitador geográfico especificado esté centrado en el mapa.

### Actual results

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Number, ClassCastException, Cause: null, Stacktrace: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Number
E/flutter ( 9786): 	at io.flutter.plugins.googlemaps.Convert.toDouble(Convert.java:377)
E/flutter ( 9786): 	at io.flutter.plugins.googlemaps.Convert.toLatLng(Convert.java:479)
E/flutter ( 9786): 	at io.flutter.plugins.googlemaps.Convert.toCameraUpdate(Convert.java:354)
E/flutter ( 9786): 	at io.flutter.plugins.googlemaps.GoogleMapController.animateCamera(GoogleMapController.java:945)
E/flutter ( 9786): 	at io.flutter.plugins.googlemaps.Messages$MapsApi$-CC.lambda$setUp$13(Messages.java:4796)
E/flutter ( 9786): 	at io.flutter.plugins.googlemaps.Messages$MapsApi$$ExternalSyntheticLambda16.onMessage(Unknown Source:2)
E/flutter ( 9786): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
E/flutter ( 9786): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 9786): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 9786): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 9786): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 9786): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 9786): 	at android.os.Looper.loop(Looper.java:223)
E/flutter ( 9786): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 9786): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9786): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 9786): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 9786): , null)
E/flutter ( 9786): #0      MapsApi.animateCamera (package:google_maps_flutter_android/src/messages.g.dart:1547:7)
E/flutter ( 9786): <asynchronous suspension>
E/flutter ( 9786): 

### Code sample

LatLngBounds latLngBounds = LatLngBounds(
      southwest: LatLng(-13.416372, -76.139882), 
      northeast: LatLng(-13.417006, -76.132952), 
    );

    print(latLngBounds);

      setState(() {
        googleMapController
            .animateCamera(CameraUpdate.newLatLngBounds(latLngBounds, 70));
      });

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

![image](https://github.com/user-attachments/assets/9cc035f9-5366-4203-905b-1b5a10ab559a)

### Flutter Doctor output

![image](https://github.com/user-attachments/assets/cdd3c4e4-05f6-4c01-8f08-34e921a9c813)

**Comment by stuartmorgan** [comment] 2024-10-11 17:38
Duplicate of https://github.com/flutter/flutter/issues/154930

**Closed by stuartmorgan** 2024-10-11 17:38 UTC
