### ISSUE TITLE
Localizations package is incompatible with firebase auth

### ISSUE THREAD

**Issue by Macacoazul01** [flutter/flutter#71801] opened 2020-12-06 14:15 UTC
I've tried to use flutter localizations package on my app to change the showdatepicker widget language, but when i add it to my pub there is a conflict with firebase auth:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.3
```

```
[assets_apps] flutter pub get
Running "flutter pub get" in assets_apps...                     
Because firebase_auth >=0.18.4 depends on firebase_auth_web ^0.3.2+2 which depends on intl ^0.16.1, firebase_auth >=0.18.4 requires intl ^0.16.1.

And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, firebase_auth >=0.18.4 is incompatible with flutter_localizations from sdk.

So, because assets_apps depends on both flutter_localizations any from sdk and firebase_auth ^0.18.4, version solving failed.
pub get failed (1; So, because assets_apps depends on both flutter_localizations any from sdk and firebase_auth ^0.18.4, version solving failed.)
exit code 1
```

My flutter doctor:

[√] Flutter (Channel master, 1.25.0-5.0.pre.57, on Microsoft Windows [versÃ£o 10.0.19042.662], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.51.1)      
[√] Connected device (2 available)

• No issues found!

Is there any way of changing the lang of the datepicker to pt-br that doesnt use the flutter_localizations?

**Comment by ekasetiawans** [comment] 2020-12-06 15:24
I'm on the dev channel and faced this problem too

**Comment by shatanikmahanty** [comment] 2020-12-07 06:32
Have you added - > intl: ^0.16.1 in pubspec.yaml because in official integration guide it's mentioned.
link : https://flutter.dev/docs/development/accessibility-and-localization/internationalization

**Comment by TahaTesser** [comment] 2020-12-07 09:15
Hi @Macacoazul01 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-07 09:15 UTC
