### ISSUE TITLE
After setting extendBody + bottomNavigationBar, a white block flashes back in the bottom navigation bar

### ISSUE THREAD

**Issue by maxfrees** [flutter/flutter#157269] opened 2024-10-21 15:29 UTC
### Steps to reproduce

https://github.com/user-attachments/assets/5e285786-70e7-43af-89f1-5b1097886ea0

### Expected results

After setting extendBody + bottomNavigationBar, a white block flashes back in the bottom navigation bar

### Actual results

After setting extendBody + bottomNavigationBar, a white block flashes back in the bottom navigation bar

### Code sample

```
Scaffold(
      appBar: const AppBar(),
      bottomNavigationBar: SafeArea(
      child: Container(
        decoration: BoxDecoration(
          color: Theme.of(context).colorScheme.surface,
          borderRadius: BorderRadius.circular(12),
        ),
        margin: EdgeInsets.only(left: 38, right: 38, bottom: 7),
        padding:EdgeInsets.symmetric(horizontal: AppTheme.padding, vertical: 4),
        child: child,
      ),
    );
      ),
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-10-22 06:42
@maxfrees 
It is not clear as what exactly is the issue / behavior are you reporting. Are you reporting about the `select all`, `install` selection bar that is appearing ? or is it something else ? I couldn't spot where does the white block flashes. Please point to it or elaborate properly.
Also, what flutter version are you on ? What platform (ios, android) is this occuring on ? Please provide complete details.

**Comment by maxfrees** [comment] 2024-10-22 06:44
@darshankawar  
![image](https://github.com/user-attachments/assets/5fc0374f-b271-4730-ad77-de67c3293f3f)

Probably because the video is too fast, there will be a very visible part of the white patch flashing on the screen

**Comment by maxfrees** [comment] 2024-10-22 06:52
ref https://github.com/flutter/flutter/issues/157316

**Comment by darshankawar** [comment] 2024-10-22 11:45
Closing this as a duplicate of linked issue.

**Closed by darshankawar** 2024-10-22 11:45 UTC
Labels: in triage
