### ISSUE TITLE
[go_router] callback function for go_router.

### ISSUE THREAD

**Issue by ravipatel0508** [flutter/flutter#107217] opened 2022-07-07 07:55 UTC
In Navigator, we can use `.then` to call the function when the user returns to that screen.

There is no callback function in `go_router`.

For eg:

` Navigator.push(context,MaterialPageRoute(builder: (context) => XyzScreen())).then((value) => _someFuncion());`

There is no simple way to implement the above code using `go_router`.

**Comment by exaby73** [comment] 2022-07-07 09:49
Duplicate of https://github.com/flutter/flutter/issues/99663

**Closed by exaby73** 2022-07-07 09:49 UTC
Labels: r: duplicate
