### ISSUE TITLE
visual studio

### ISSUE THREAD

**Issue by gomesglauce** [flutter/flutter#105590] opened 2022-06-08 13:05 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by gomesglauce** [comment] 2022-06-08 13:08
[Flutter bug.docx](https://github.com/flutter/flutter/files/8861744/Flutter.bug.docx)

Hi! I have a issue after installing Visual Code and neet to solve it. You can see details at the atatched file. 
Can you help me? Thanks!

**Comment by danagbemava-nc** [comment] 2022-06-08 13:14
Closing this as a duplicate of #102451. 

Kindly follow up in the linked issue for a workaround/updates. 

Thank you

**Closed by danagbemava-nc** 2022-06-08 13:14 UTC
Labels: in triage
