### ISSUE TITLE
Hot reload with integration_test 

### ISSUE THREAD

**Issue by hanskenis** [flutter/flutter#76985] opened 2021-03-01 13:44 UTC
Hi, 

we have written some integration tests with the [integration_test](https://pub.dev/packages/integration_test) package. Is it possible to run them agains a running application as described here: https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54?

**Comment by TahaTesser** [comment] 2021-03-01 14:11
Hi @hanskenis 
Interesting, I'm not sure, labelling this for documentation if it possible otherwise we can change to a proposal 
Thank you

**Comment by pascalw** [comment] 2021-03-08 07:02
What seems to work is running the integration test with `flutter run` instead of `flutter drive`, i.e. `flutter run integration_test/app_test.dart`. The tests will run when the app is started and the app will keep running. To re-run the tests you can trigger a hot **restart**, this will take into account any changes to both the app and the tests.

Hot _reload_ doesn't work. If I trigger a hot reload when running the integration tests like this the CLI prints "this is taking long" and never completes the hot reload. This is unfortunate as Android Studio triggers a hot reload on every save, so you have to run this from the command line instead of from the IDE.

**Comment by vini2001** [comment] 2021-04-09 02:31
> What seems to work is running the integration test with `flutter run` instead of `flutter drive`, i.e. `flutter run integration_test/app_test.dart`. The tests will run when the app is started and the app will keep running. To re-run the tests you can trigger a hot **restart**, this will take into account any changes to both the app and the tests.
> 
> Hot _reload_ doesn't work. If I trigger a hot reload when running the integration tests like this the CLI prints "this is taking long" and never completes the hot reload. This is unfortunate as Android Studio triggers a hot reload on every save, so you have to run this from the command line instead of from the IDE.

This was working until yesterday. Suddenly if I run it with flutter run the simulator gets stuck on the "Test Starting" screen

**Comment by vrnvorona** [comment] 2021-04-22 12:39
> What seems to work is running the integration test with `flutter run` instead of `flutter drive`, i.e. `flutter run integration_test/app_test.dart`. The tests will run when the app is started and the app will keep running. To re-run the tests you can trigger a hot **restart**, this will take into account any changes to both the app and the tests.
> 
> Hot _reload_ doesn't work. If I trigger a hot reload when running the integration tests like this the CLI prints "this is taking long" and never completes the hot reload. This is unfortunate as Android Studio triggers a hot reload on every save, so you have to run this from the command line instead of from the IDE.

It does run, but is it ok to run tests without integration_driver adapter? Behaviour seems to be different sometimes when running "properly".

**Comment by csells** [comment] 2021-04-29 17:08
cc @dnfield

**Comment by dnfield** [comment] 2021-04-29 17:10
Is there a sample project that this is broken on? Particularly if it worked at one point and doesn't now?

**Comment by pascalw** [comment] 2021-04-29 17:49
Hi @dnfield I guess this is more of a feature request than a bug report. What we are looking for is a way to write integration tests against a running app, without having to recompile and rerun the whole application for every small change to the tests. That would increase productivity by a lot.

Previously with `flutter_driver` this was possible, albeit with a workaround documented in [this](https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54) blog post.

What I noticed is that instead of using Flutter Driver to run the `integration_test` tests, it's also possible to run these tests using `flutter run` and then use hot _restart_ (not reload), to re-run the tests after the tests or the application has changed. In practise I haven't used this a lot yet, but @vrnvorona reported that behaviour seems different compared to running the tests using Flutter Driver.

**Comment by dnfield** [comment] 2021-04-29 17:51
Yes, I'm curious to see the example integration test you're trying this on :)

**Comment by pascalw** [comment] 2021-04-29 18:08
Ok sure, I'll try whip up an example tomorrow!

**Comment by pascalw** [comment] 2021-05-01 18:58
@dnfield I've uploaded an example here: https://github.com/pascalw/flutter_integration_test_example

This is basically `flutter create` + `integration_test` added with a test for the counter example. The following workflow works for me:

1. `flutter run integration_test/app_test.dart`
2. Change tests or implementation
3. Hot **restart**. Tests are restarted and new code is picked up.

This is OK, but could be improved in a few ways:

* Hot **reload** doesn't work currently. It just hangs indefinitely (today on `2.3.0-1.0.pre.182`, but also happened before on Flutter 1.x).
* There's no convenient way to run a single test this way.

IMO the ideal workflow would be something like this:

1. `flutter test integration_test/app_test.dart --server` - hypothetical `--server` argument, that runs the app and hot reloads changes to it.
2. `flutter test integration_test/app_test.dart:12` - Run the test at line 12, against the server/app that was started in step 1.

**Comment by TahaTesser** [comment] 2021-05-03 12:16
Hi @pascalw 
Thanks for the code sample, I just on the `master` channel,  `Hot Restart` doesn't hang for me on Android. 

If i changed the expected behavior, hot restart then i do see test fail without hang

<details> 
<summary>logs</summary> 

```console
[ +171 ms] Hot restart performed in 778ms.
[   +1 ms] Performing hot restart... (completed in 779ms)
[        ] Restarted application in 785ms.
[ +230 ms] I/flutter (21131): 00:00 +0: Counter increments smoke test
[+1069 ms] I/flutter (21131): 00:01 +1: (tearDownAll)
[  +12 ms] I/flutter (21131): 00:01 +2: All tests passed!
[+44879 ms] Skipping target: gen_localizations
[   +1 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Performing hot restart...
[  +35 ms] Scanned through 549 files in 35ms
[   +1 ms] Syncing files to device Android SDK built for x86 64...
[        ] <- reset
[        ] Compiling dart to kernel with 1 updated files
[        ] <- recompile
file:///C:/Users/Taha/AndroidStudioProjects/flutter_integration_test_example/integration_test/app_test.dart
0bf01c3f-644e-4566-9a3f-62d386882035
[        ] file:///C:/Users/Taha/AndroidStudioProjects/flutter_integration_test_example/integration_test/app_test.dart
[        ] <- 0bf01c3f-644e-4566-9a3f-62d386882035
[ +119 ms] Updating files.
[ +530 ms] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86 64... (completed in 653ms)
[        ] Synced 29.6MB.
[        ] <- accept
[ +164 ms] Hot restart performed in 856ms.
[   +1 ms] Performing hot restart... (completed in 857ms)
[        ] Restarted application in 863ms.
[ +226 ms] I/flutter (21131): 00:00 +0: Counter increments smoke test
[+1031 ms] I/flutter (21131): (The following exception is now available via WidgetTester.takeException:)
[  +64 ms] I/flutter (21131): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK
╞════════════════════════════════════════════════════
[   +2 ms] I/flutter (21131): The following TestFailure object was thrown running a test:
[        ] I/flutter (21131):   Expected: exactly one matching node in the widget tree
[        ] I/flutter (21131):   Actual: _TextFinder:<zero widgets with text "1" (ignoring offstage widgets)>
[   +1 ms] I/flutter (21131):    Which: means none were found but one was expected
[   +1 ms] I/flutter (21131):
[        ] I/flutter (21131): When the exception was thrown, this was the stack:
[        ] I/flutter (21131): #4      main.<anonymous closure>
(file:///C:/Users/Taha/AndroidStudioProjects/flutter_integration_test_example/integration_test/app_test.dart:15:5)
[   +1 ms] I/flutter (21131): <asynchronous suspension>
[        ] I/flutter (21131): <asynchronous suspension>
[        ] I/flutter (21131): (elided one frame from package:stack_trace)
[        ] I/flutter (21131): ...
[        ] I/flutter (21131):
[        ] I/flutter (21131): This was caught by the test expectation on the following line:
[        ] I/flutter (21131):
file:///C:/Users/Taha/AndroidStudioProjects/flutter_integration_test_example/integration_test/app_test.dart line 15
[        ] I/flutter (21131): The test description was:
[        ] I/flutter (21131):   Counter increments smoke test
[        ] I/flutter (21131):
════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] I/flutter (21131): (If WidgetTester.takeException is called, the above exception will be ignored. If it is
not, then the above exception will be dumped when another exception is caught by the framework or when the test ends,
whichever happens first, and then the test will fail due to having not caught or expected the exception.)
[   +1 ms] I/flutter (21131): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK
╞════════════════════════════════════════════════════
[        ] I/flutter (21131): The following TestFailure object was thrown running a test:
[        ] I/flutter (21131):   Expected: exactly one matching node in the widget tree
[        ] I/flutter (21131):   Actual: _TextFinder:<zero widgets with text "1" (ignoring offstage widgets)>
[        ] I/flutter (21131):    Which: means none were found but one was expected
[        ] I/flutter (21131):
[        ] I/flutter (21131): When the exception was thrown, this was the stack:
[        ] I/flutter (21131): #4      main.<anonymous closure>
(file:///C:/Users/Taha/AndroidStudioProjects/flutter_integration_test_example/integration_test/app_test.dart:15:5)
[        ] I/flutter (21131): <asynchronous suspension>
[        ] I/flutter (21131): <asynchronous suspension>
[        ] I/flutter (21131): (elided one frame from package:stack_trace)
[        ] I/flutter (21131): ...
[        ] I/flutter (21131):
[        ] I/flutter (21131): This was caught by the test expectation on the following line:
[   +2 ms] I/flutter (21131):
file:///C:/Users/Taha/AndroidStudioProjects/flutter_integration_test_example/integration_test/app_test.dart line 15
[        ] I/flutter (21131): The test description was:
[        ] I/flutter (21131):   Counter increments smoke test
[        ] I/flutter (21131):
════════════════════════════════════════════════════════════════════════════════════════════════════
[   +1 ms] I/flutter (21131): 00:01 +0: Counter increments smoke test [E]
[   +1 ms] I/flutter (21131):   Test failed. See exception logs above.
[        ] I/flutter (21131):   The test description was: Counter increments smoke test
[        ] I/flutter (21131):
[        ] I/flutter (21131): 00:01 +0 -1: (tearDownAll)
[  +23 ms]
```

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.205, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-1.0.pre.205 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96e4b47f5d (22 hours ago), 2021-05-02 07:24:01 -0700
    • Engine revision 3e578c6e0d
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19042.928]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 90.0.818.51

! Doctor found issues in 1 category.
```
		
</details>

**Comment by dnfield** [comment] 2021-05-04 05:05
So from what I can see with `flutter run`, by the time I get to a point where it'd even make sense to hot reload, the test has progressed to a finished state. Hot reload definitely gets stuck there, but even if it didn't what exactly would you expect the result of hot reload to be? Perhaps if there was some way to step through test expectations and hot reload at those points it could work - but even then, I imagine it'd get difficult to keep track of the state in the test that could be sensibly hot reloaded vs. things that really would require a hot restart to pick up.

Hot restart, on the other hand, does what I'd expect it do (restarts the entire isolate at the start of the test).

/cc @jiahaog for thoughts on how tooling might help here, since he's been working on that. I believe there's some expectation of `flutter test` or some similar command to work for integration tests, but I'm not clear on the progress on that.

**Comment by jiahaog** [comment] 2021-05-04 08:26
It seems like what you are asking for here is for a fast way to incrementally iterate on integration tests, and hot reloading / restart as mentioned is a possible solution to doing so, though this is not supported by the Flutter team today 🙂 

In the larger scope of things, I believe the larger effort to track this would be https://github.com/flutter/flutter/issues/4719, which is to support a watch mode for `flutter test`. Currently, with already some progress made on https://github.com/flutter/flutter/issues/66264, we are able to reuse most of the `flutter test` functionality to run Integration Tests on most platforms (except web). Depending on how #4719 is resolved, it should provide us with a structured way forward (or even for free!) to solve this for Integration Tests.

**Comment by esDotDev** [comment] 2021-06-05 02:53
> what exactly would you expect the result of hot reload to be? 

My expectation would be that it just runs the tests again, but without the app losing state. 

I could see this being useful if I had a bug somewhere deep in my smoke test, maybe I'm on step 5, and that's where the test is failing. I could quickly comment out all the tests preceding this step, run hot reload, and re-test the problematic view, when everything is working again, I remove comments and I have my fixed test.

The start at line 12 thing is neat too, but to me the "comment out this huge chunk of code" and hot reload, has more parallels to how we typically debug in Flutter anyways.

I'm not sure 'watch` solves this btw, as not everyone wants hot-reload on save. I don't because it tends to hot-reload prematurely and spams my error console with noise, I much prefer the manual keystroke to push a new build to device when working on a complex application.

**Comment by dnfield** [comment] 2021-06-05 03:19
Why not hot restart in that case?  I'm not sure what state you want to preserve for a failed test suite...

**Comment by pascalw** [comment] 2021-06-05 10:43
I agree that in principle hot restart is fine. I write my integration tests in such a way that every test can run completely independently, so always starting at the first screen in the app.

I guess my main issue with the current state of things is that the tooling does not support this use case very well. If I run `integration_test/app_test.dart` from Android Studio for example, tests are executed and the app remains running which is good. But when I make changes to the app or the test code, Android Studio will automatically trigger a `hot reload` which causes `flutter run` to hang and needs to be killed. So in order for this work, you have to `flutter run` from the command line and then manually go into the terminal and press `R` to trigger a hot restart, after every change.

**Comment by esDotDev** [comment] 2021-06-05 18:06
I also agree better tooling support for `restart` gets us most of the way there.

@dnfield The state of the application itself, imagine a smoke test that
1. Starts app
2. Runs tests on login view
3. Logs in
4. Changes navigation
5. Opens Settings
6. Runs tests on settings view (that require use to be logged in and preferences loaded)

Now imagine I have some issue on Step 6, and I just need to figure out why the test is failing. Hot reload in theory gives us a way to just keep the app on the failed view, and re-run test 6, without needing to traverse steps 1-5 over and over, or modify my test code to somehow skip to test 6.

**Comment by chientrm** [comment] 2022-03-11 17:24
Instead of hot-reload integration test, I suggestion orchestrated hot-restart integration test which is basically hot-restart integration test but if you have more than 1 device you can run multiple integration test apps at the same time on multiple devices.
I personally think hot-reload integration test is not a good idea because the total app is stateful while integration tests require an end-to-end session for each test. Thus, hot-reload should stay with unit test and widget tests or UI/UX design for now I guess.

**Comment by vrnvorona** [comment] 2022-03-12 11:35
> Android Studio will automatically trigger a hot reload which causes flutter run to hang and needs to be killed. So in order for this work, you have to flutter run from the command line and then manually go into the terminal and press R to trigger a hot restart, after every change.

Don't see a problem here, just disable automatic hot reload. Tests are not apps, they are end-to-end processes, there is nothing to hot reload here.

**Comment by nt4f04uNd** [comment] 2022-03-12 22:22
The hot reload being stuck was fixed in https://github.com/flutter/flutter/issues/79150

I noticed now that if we hot reload during the test running, this might (not always) affect the test state

<details>
<summary>Logs</summary>

```
I/flutter ( 8607): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter ( 8607): The following TestFailure was thrown running a test:
I/flutter ( 8607): Expected: exactly one matching node in the widget tree
I/flutter ( 8607):   Actual: _TextFinder:<zero widgets with text "0" (ignoring offstage widgets)>
I/flutter ( 8607):    Which: means none were found but one was expected
I/flutter ( 8607):
I/flutter ( 8607): When the exception was thrown, this was the stack:
I/flutter ( 8607): #4      main.<anonymous closure> (file:///C:/Users/danya/Desktop/flutter_integration_test_example/integration_test/app_test.dart:14:5)
I/flutter ( 8607): <asynchronous suspension>
I/flutter ( 8607): #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
I/flutter ( 8607): <asynchronous suspension>
I/flutter ( 8607): #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:830:5)
I/flutter ( 8607): <asynchronous suspension>
I/flutter ( 8607):
I/flutter ( 8607): This was caught by the test expectation on the following line:      
I/flutter ( 8607):   file:///C:/Users/danya/Desktop/flutter_integration_test_example/integration_test/app_test.dart line 14
I/flutter ( 8607): The test description was:
I/flutter ( 8607):   Counter increments smoke test
I/flutter ( 8607): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8607): 00:01 +0: Counter increments smoke test [E]
I/flutter ( 8607):   Test failed. See exception logs above.
I/flutter ( 8607):   The test description was: Counter increments smoke test
I/flutter ( 8607):
I/flutter ( 8607): 00:01 +0 -1: (tearDownAll)
```
</details>

I'd personally prefer that over runner being stuck, but it's not ideal, and as suggested above, perhaps it should also rerun the currently running test from the beginning, instead of just hot reloading while it's in progress.

**Comment by chientrm** [comment] 2022-03-13 06:17
I had just found out that hot reload can still work while running integration testing and it help me save time working on the UI.

**Comment by dnfield** [comment] 2022-03-13 06:45
Sounds like this is resolved.

**Closed by dnfield** 2022-03-13 06:45 UTC
Labels: a: tests, documentation, passed first triage, integration_test
