### ISSUE TITLE
iOS 14 从相册选择图片发生闪退

### ISSUE THREAD

**Issue by love-yukee** [flutter/flutter#69651] opened 2020-11-03 07:43 UTC
1. 第一次调用相册界面没有发生闪退, 
2. 当选择好图片后,  第二次进入相册界面时发生闪退

**Comment by pedromassangocode** [comment] 2020-11-03 08:39
嗨 @love-yukee 
您能否提供“ flutter doctor -v”，“ flutter run --verbose”以及最小的完整可复制代码示例？
我建议您用英语交流，因为这是我们在这里使用的交流方式。
谢谢

Hi @0000
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
I recommend you to communicate in English because it is what we use here to communicate.
Thank you

**Comment by pedromassangocode** [comment] 2020-11-24 10:13
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-24 10:13 UTC
Labels: in triage, waiting for customer response
