### ISSUE TITLE
Cupertino Icon Gallery is not available 👎🏻

### ISSUE THREAD

**Issue by henry2man** [flutter/flutter#89549] opened 2021-09-06 12:27 UTC
It looks that Cupertino Icon Gallery is down. It used to be live here: https://flutter.github.io/cupertino_icons

Also there is a link in the [CupertinoIcons](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html) class, which is also broken.

![Captura de pantalla 2021-09-06 a las 14 26 24](https://user-images.githubusercontent.com/4610108/132217320-84819720-866b-472d-a35f-afbd773c617a.png)

I've filled this issue into the "CI" category because I think this could be something CI related.

**Comment by TahaTesser** [comment] 2021-09-06 12:32
duplicate of https://github.com/flutter/flutter/issues/88754

**Closed by TahaTesser** 2021-09-06 12:32 UTC
Labels: team: infra, in triage

**Comment by henry2man** [comment] 2021-09-06 12:38
@TahaTesser Sorry for the duplicate, I didn't found the original one.
