### ISSUE TITLE
(mac-7) Test on iOS device in the staging pool getting cancelled repeatedly

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#128454] opened 2023-06-07 19:29 UTC
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20draw_points_perf_ios__timeline_summary

**Comment by zanderso** [comment] 2023-06-07 19:31
All failures are on `mac-7`

**Comment by drewroengoogle** [comment] 2023-06-07 19:55
For the short term, I will quarantine mac-7 to mitigate any failures, and then will investigate further

**Comment by kentnguyen99** [comment] 2023-06-08 21:39
I ran couples commands and didn't find any errors on machine mac-7.

**Comment by drewroengoogle** [comment] 2023-06-12 21:46
I will look into it a bit more tomorrow, and see if the issue is still occurring. Thanks for checking!

**Comment by kentnguyen99** [comment] 2023-06-15 16:51
@drewroengoogle Just checking... Have you had a chance to take a look of mac-7?

**Comment by drewroengoogle** [comment] 2023-06-15 17:27
Thank you for the reminder! I've removed mac-7 from quarantine after running some of the tests that had previously failed. Feel free to reopen if this starts occurring again.

**Comment by kentnguyen99** [comment] 2023-06-15 21:43
Hey @drewroengoogle,
Issue still existing..

<img width="1305" alt="Screenshot 2023-06-15 at 2 41 49 PM" src="https://github.com/flutter/flutter/assets/120754754/221e33fb-38ad-4e45-a36c-51c935108e53">

**Comment by drewroengoogle** [comment] 2023-06-15 21:53
Thanks. It seems that there is a difference between running these builds on led. Quarantining it again.

**Comment by drewroengoogle** [comment] 2023-06-15 22:02
@yusuf-goog I'm not super familiar with the specifics on these bots, but the build I'm mainly concerned about is this one: https://luci-milo.appspot.com/p/flutter/builders/staging/Mac_ios%20draw_points_perf_ios__timeline_summary/505?

I can run the test on mac-7 using led and it passes the `Run app to dismiss dialogs` step as expected. Is there any chance something on this bot isn't correctly set up?

The other failures seem to be failing across all bots, not just mac-7, so they probably are failing due to this bot.

**Comment by kentnguyen99** [comment] 2023-06-15 22:14
@keyonghan Can you take a look on Bot side on machine mac-7?  Thanks.

**Comment by keyonghan** [comment] 2023-06-16 22:43
There is leftover apps without being uninstalled after task failures:
```
ideviceinstaller -l
CFBundleIdentifier, CFBundleVersion, CFBundleDisplayName
dev.flutter.infra-dialogUITests.xctrunner, "1", "infra-dialogUITests-Runner"
```

Uninstalled the app, and restarted the device. LED run on an earlier failed build passed:
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/dfbc23c651a999d90bbc1446e3c6a7f63d05dc412055027cbf643573074d9168/+/build.proto

Let's monitor the status of the following builds to see if still any issues.

**Comment by keyonghan** [comment] 2023-06-20 16:44
https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Mac_ios%20draw_points_perf_ios__timeline_summary is passing consistently. 

@kentnguyen99 Just F.Y.I. it would be helpful to check the swarming_bot.log when the issue repros to see why the app was not uninstalled. Note we have the clean up logic for staging bots as well. Wondering if some transient LUCI issue.

Closing as the bot is in a good shape now.

**Closed by keyonghan** 2023-06-20 16:44 UTC
Labels: team: infra, device-lab

**Comment by kentnguyen99** [comment] 2023-06-20 18:14
@keyonghan Can you point me where the swarming_bot.log resides on machine? So, next time will check the logs file. Thanks

**Comment by keyonghan** [comment] 2023-06-20 18:18
It's under `/opt/s/logs`
