### ISSUE TITLE
FlutterJNI.loadLibrary
java.lang.UnsatisfiedLinkError - dlopen failed: library "libflutter.so" not found

### ISSUE THREAD

**Issue by hasanm08** [flutter/flutter#155243] opened 2024-09-16 10:51 UTC
#123458
Hi i encountered this error on flutter 3.24.1
Any updates?
'''
Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail. App is using cpu architecture: i686, and the native libraries directory (with path /data/app/edu.xaban.xaban-SbWOJOO43PyXRvO_-x2KXA==/lib/x86) contains the following files: null
'''
![IMG_20240916_142225_692.jpg](https://github.com/user-attachments/assets/3ca77bf0-59e8-452d-abbd-3163ffd5a64e)

**Comment by darshankawar** [comment] 2024-09-16 12:07
Closing as duplicate of https://github.com/flutter/flutter/issues/151638. Please follow-up in it for further updates.

**Closed by darshankawar** 2024-09-16 12:07 UTC
Labels: in triage
