### ISSUE TITLE
can't able to get focused on TextFormField sometime.

### ISSUE THREAD

**Issue by anandsubbu007** [flutter/flutter#77509] opened 2021-03-07 09:59 UTC
At some time TextField can't able to get focused. 
After restart, the app all works fine till this error occurs again.

Platform: windows

**No Error found in debug console.**

https://user-images.githubusercontent.com/55450843/110236028-a4e1a400-7f59-11eb-90ef-1ebe96cceb60.mp4

**Comment by darshankawar** [comment] 2021-03-08 11:12
@anandsubbu007 
Can you provide `flutter doctor -v` ? You see this issue when you try to tap on textformfield and it suddenly stops being in the focus ?

**Comment by anandsubbu007** [comment] 2021-03-08 15:32
Backspace & delete is also not working while typing in textfield
` You see this issue when you try to tap on textformfield and it suddenly stops being in the focus ?`
yes, cant able to type on field
```
PS C:\Users\anand\Desktop\GitHub\E-Billing_App\Billing_App> flutter doctor -v
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-IN)
    • Flutter version 2.0.1 at C:\Flutter Components\flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\anand\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\anand\AppData\Local\Android\Sdk
    • Java binary at: C:\Flutter Components\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Flutter Components\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\anand\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```

**Comment by darshankawar** [comment] 2021-03-09 07:33
@anandsubbu007 
Do you see this behavior consistently / everytime you try to type into the textformfield ?
Can you switch to latest master and see if you get same behavior ?

**Comment by anandsubbu007** [comment] 2021-03-09 07:39
I can't even able to get focused.
Whenever I tap or tried to get focus on textfield it is not responding itself unfocused like in image

**Comment by darshankawar** [comment] 2021-03-09 11:19
@anandsubbu007 
Can you provide reproducible code sample that we can directly use to verify this ?

**Comment by anandsubbu007** [comment] 2021-03-09 16:23
Following code works fine.
but this issue occurs anytime. 
I don't know how to share reproducible code sample

this occurs very few times.
```
class Test extends StatelessWidget {
  const Test({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Center(
        child: Container(
          width: 500,
          height: 75,
          child: TextField(
            decoration: InputDecoration(border: OutlineInputBorder()),
          ),
        ),
      ),
    ));
  }
}

```

**Comment by darshankawar** [comment] 2021-03-10 12:09
@anandsubbu007 
Tried the sample code on latest stable and saw no issues as you described. I was able to tap, use backspace and delete text from the `TextField` properly without any issues.


https://user-images.githubusercontent.com/67046386/110626679-09ee0180-81c7-11eb-8a71-7c3dbbaa0366.MOV

![IMG-0693](https://user-images.githubusercontent.com/67046386/110626993-6f41f280-81c7-11eb-8c8f-6f5a1b38eaaf.JPG)

**Comment by anandsubbu007** [comment] 2021-03-20 15:20
it occurs rarely.
most of the time it works fine.
i don't know why its happening.

**Comment by darshankawar** [comment] 2021-03-22 06:04
I am going ahead and closing this as not-reproducible and non-actionable, since per author it occurs `rarely` and there's no concrete steps to replicate this. Also, I wasn't able to replicate it when I tried.  Write in comments if you see this issue again but consistently and have proper steps to replicate.
Thanks.

**Closed by darshankawar** 2021-03-22 06:04 UTC
Labels: in triage
