### ISSUE TITLE
[impeller] MaskFilter and BlurStyle.inner leads to pixelated circle

### ISSUE THREAD

**Issue by xvrh** [flutter/flutter#128572] opened 2023-06-09 12:31 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the sample code on an iOS device using impeller
2. I can reproduce this on latest master and latest stable

### Expected results

Impeller and non-impeller should look the same

### Actual results

Impeller version is pixelated

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(_Example());

class _Example extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('MaskFilter'),
        ),
        body: ListView(
          children: [
            Center(
              child: CustomPaint(
                painter: _Painter(),
                size: const Size(200, 200),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _Painter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var paint = Paint()
      ..color = Colors.red
      ..maskFilter = const MaskFilter.blur(BlurStyle.inner, 10);

    canvas.drawCircle(size.center(Offset.zero), size.width / 2, paint);
  }

  @override
  bool shouldRepaint(covariant _Painter oldDelegate) {
    return true;
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

`--enable-impeller`

<img width="469" alt="Screenshot 2023-06-09 at 14 22 44" src="https://github.com/flutter/flutter/assets/5110923/32dd89d8-336b-4690-89c5-9aef139a890c">

`--no-enable-impeller`

<img width="468" alt="Screenshot 2023-06-09 at 14 25 54" src="https://github.com/flutter/flutter/assets/5110923/ce8944bd-b016-4773-bfb0-86c95922c988">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.12.0-3.0.pre.35, on macOS 13.2.1 22D68
    darwin-arm64, locale en-BE)
    • Flutter version 3.12.0-3.0.pre.35 on channel master at
      /Users/xavier/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 66cda5917d (62 minutes ago), 2023-06-09 04:28:18 -0700
    • Engine revision cb93477008
    • Dart version 3.1.0 (build 3.1.0-180.0.dev)
    • DevTools version 2.24.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/xavier/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/xavier/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841
      /Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/xavier/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/xavier/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/xavier/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/xavier/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/xavier/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • Pixel 6 (mobile)         • 19151FDF600CE7            • android-arm64  •
      Android 13 (API 33)
    • CPH2371 (mobile)         • EENBM78XA6857HMF          • android-arm64  •
      Android 13 (API 33)
    • Xavier’s iPhone (mobile) • 00008030-00012D9C0212802E • ios            •
      iOS 16.5 20F66
    • macOS (desktop)          • macos                     • darwin-arm64   •
      macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript •
      Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by chinmaygarde** [comment] 2023-06-12 17:58
Closing as a duplicate of https://github.com/flutter/flutter/issues/125947

**Closed by chinmaygarde** 2023-06-12 17:58 UTC
Labels: platform-ios, engine, has reproducible steps, impeller, found in release: 3.10, found in release: 3.12
