### ISSUE TITLE
Restore purchase returns multiple AppStorePurchaseDetails.

### ISSUE THREAD

**Issue by KuldeepAIP** [flutter/flutter#93369] opened 2021-11-10 06:31 UTC
When i try to restore the previous purchase by calling `await InAppPurchase.instance.restorePurchases();` i get multiple AppStorePurchaseDetails in below code.

```
@override
  void initState() {
    Stream purchaseUpdated = _connection.purchaseStream;

    _subscription = purchaseUpdated.listen((purchaseDetailsList) {
      _listenToPurchaseUpdated(purchaseDetailsList);
    }, onDone: () {
      _subscription.cancel();
    }, onError: (error) {
      // handle error here.
      print("error in purchase $error");
    });
    initStoreInfo();
    super.initState();
  }
```

Here is the list of `AppStorePurchaseDetails` that i get on restore purchase.
![Screenshot 2021-11-10 at 11 51 33 AM](https://user-images.githubusercontent.com/60171515/141061814-52651a53-3957-4b50-b75b-4a16d4b7c0b6.png)

Can anyone please let me know what i am missing and why it returns multiple records?
Thanks

**Comment by darshankawar** [comment] 2021-11-10 09:30
@KuldeepAIP 
I think you are hitting https://github.com/flutter/flutter/issues/85529. Check that and confirm if that's the case.

**Comment by aipxperts-developer** [comment] 2021-11-10 11:48
@darshankawar , yes, kind of same issue i am facing but not getting VERBOSE-2:ui_dart_state.cc(199)] error. i can see the issue is still open. is there any solution for that?

**Comment by KuldeepAIP** [comment] 2021-11-10 11:49
@darshankawar  yes, kind of same issue i am facing but not getting VERBOSE-2:ui_dart_state.cc(199)] error. i can see the issue is still open. is there any solution for that?

**Comment by darshankawar** [comment] 2021-11-11 06:25
@KuldeepAIP 
No, that issue is still open. You may share your findings in that issue for better tracking and keep an eye on that issue for further updates and reference. I will close this in favor of https://github.com/flutter/flutter/issues/85529. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-11-11 06:25 UTC
Labels: in triage
