### ISSUE TITLE
[MacOS] It is hard to trigger onSecondaryTap event when the widget is scrollable.

### ISSUE THREAD

**Issue by MegatronKing** [flutter/flutter#115065] opened 2022-11-10 08:14 UTC
## Steps to Reproduce

I have this issue on my MacBook Pro without mouse.

1. Execute `flutter run` on the code sample 
2. Tap trackpad with two fingers quickly and frequently, watch the console logs.
3. Remove `SingleChildScrollView` and try step2 again, it will be ok.

**Expected results:** Every tap should have a `onSecondaryTap` callback.

**Actual results:** Sometimes, nothing was happened.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: GestureDetector(
          onSecondaryTap: () {
            print('onSecondaryTap');
          },
          onTap: () {
            print('onTap');
          },
          child: Container(
            alignment: Alignment.center,
            child: const Text("Test SecondaryTap long long long long long long long long long long long long long long"),
          ),
        )
      )
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
Flutter (Channel stable, 3.3.7, on macOS 12.1 21C52 darwin-x64, locale
    en-CN)
    • Flutter version 3.3.7 on channel stable at
      /Users/megatronking/Github/flutter
    ! Upstream repository https://gitee.com/mirrors/Flutter.git is not a
      standard remote
    • Framework revision e99c9c7cd9 (8 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/megatronking/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/megatronking/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/megatronking/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87
```

</details>

https://user-images.githubusercontent.com/15059084/201036990-18c53b91-5b7e-452f-a614-493e74703ce2.mov

**Comment by exaby73** [comment] 2022-11-10 13:58
Hello @MegatronKing. This seems to be working as expected. If you try tapping with 2 fingers in a native application, you'll see that only the last tap is recognized rather than all of them. The same behavior, I can observe in Flutter. If you tap with 2 fingers and wait, it will successfully register consistently. This seems to reflect the native behavior therefore, I am closing this issue. If you disagree with my decision, please comment and I can reopen the issue. Thank you.

**Comment by MegatronKing** [comment] 2022-11-10 14:07
@exaby73 This design is reasonable: `only the last tap is recognized rather than all of them.` but this is not my issue. My issue is, If you not put the widget inside a ScrollView, the tap is sensitive. If you run my sample code with `SingleChildScrollView` and without `SingleChildScrollView`, you will find the difference.

**Comment by exaby73** [comment] 2022-11-10 14:13
@MegatronKing I cannot reproduce this. I observe the same behavior with both, with and without a scroll view. Tested on master

**Closed by exaby73** 2022-11-10 14:13 UTC
Labels: r: invalid
