### ISSUE TITLE
Stepper Type Horizontal results in Data Loss

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#19835] opened 2018-07-26 20:31 UTC
I am using Steppers, to display a list of widgets. My app worked well in Stepper Type Vertical, but I decided to switch to Horizontal type. I have Textfield widget as content of my step in Stepper, now as I traverse through my steps in stepper, whatever data I had previously entered in my TextField gets cleared.This results in Data Loss.

**Comment by Shantanu-Kotambkar** [comment] 2018-07-30 14:11
Here is a minimal sample code: 
`  class MyHome extends StatelessWidget {
  int current_step = 0;
  List<Step> my_steps = [
    new Step(
        title: new Text("Step 1"),
        content: new TextField(
          decoration: InputDecoration(
            hintText: 'Enter your name',
          ),
        ),
        isActive: true),
    new Step(
        title: new Text("Step 2"),
        content: new Text("Hello!"),
        state: StepState.indexed,
        isActive: true),
  ];



  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      // Appbar
      appBar: new AppBar(
        // Title
        title: new Text("Stepper Example"),
      ),
      // Body
      body: new Container(
          child: StreamBuilder(
        stream: blocStepper.stepperStream,
        builder: (context, snapshot) {
          current_step = snapshot.hasData ? snapshot.data : 0;
          return Stepper(
            currentStep: current_step,
            steps: my_steps,
            type: StepperType.horizontal,
            onStepTapped: blocStepper.changeStepper,
          );
        },
      )),
    );
  }
}`

**Comment by zoechi** [comment] 2018-07-30 16:44
Please add the output of `flutter doctor -v`.

**Comment by Hixie** [comment] 2018-07-30 22:04
You have to store the data for the text field when the user changes the data, because we try not to keep widgets around if they're not visible.

**Comment by Shantanu-Kotambkar** [comment] 2018-07-30 22:13
Well, it remains in vertical steppers. And shouldn't both the types work the same? If not, may be we should specify this in the documentation. There is a lack of documentation on Horizontal Stepper type. I have written a custom implementation of Horizontal Steppers, which are implemented the same way vertical one is, and thus I am not losing the data user entered. However, I am not sure if this affects flutters efficiency as I am keeping the widgets around when they are not visible.

**Comment by DarshanGowda0** [comment] 2018-07-31 21:33
@Shantanu-Kotambkar It's not specific to steppers. That's the functionality of the TextField/TextForField. The widgets are destroyed and rebuild if they are not visible on the screen in cases like ScrollView, ListView or Steppers. You basically have to use a TextEditingController to retain the values. [Here's](https://docs.flutter.io/flutter/material/TextField-class.html) the documentation on that or you can cmd+click on TextField / TextFormField (on IntelliJ) for brief documentations like this.

**Comment by zoechi** [comment] 2018-08-01 07:16
Hint: You are using a stateless widget with a state. (not sure yet this is related to your problem)

**Comment by Shantanu-Kotambkar** [comment] 2018-08-02 14:52
Yes thats right, I understand it is a basic behavior followed by widgets in flutter. But if I have multiple textfields, checkboxes, and several other form widgets. I am not sure which is a better approach,to store each one of them and then populate them again, whenever they are rebuilt or to keep them around.

**Comment by jagan999** [comment] 2019-12-30 09:07
Adding on to this thread. I see not much activity on this since early 2019. I have attached sample code in txt file format and see anomalies in it's working between Stepper type horizontal and vertical. I'm baffled how to get this to work. A brief explanation of the anomaly below:

When Stepper type is vertical, clicking Save details button validates data in all different steps and doesn't allow Save until all fields are validated properly **across steps**

When the Stepper type is horizontal, validation only happens on the currently visible step and any errors in other steps are ignored.

Please provide a solution. In my app, it's not a good user experience to have a vertical stepper.
[test_page_dart.txt](https://github.com/flutter/flutter/files/4009349/test_page_dart.txt)

**Comment by jagan999** [comment] 2019-12-30 09:48
@Shantanu-Kotambkar What did you do in your specific custom implementation of the horizontal stepper that allowed Stepper to preserve those steps that are not currently visible? Would you be able to share your code with me?

**Comment by ettaibi** [comment] 2020-04-04 22:23
Any idea about what is the best way to resolve this ? The problem is when having a lot of fields accross steps, is there any better solution than setting TextEditingController for each field to preserve the values ?

**Comment by Shantanu-Kotambkar** [comment] 2020-04-05 04:24
It's been a while since this issue was raised. As I recall, I resorted to using streams throughout my application to provide access. Streams had maps, which stored data/errors. However, using streams throughout an application has multiple overheads. So be cautious when using this approach.

**Comment by ettaibi** [comment] 2020-04-05 18:41
Thanks, Do you have an example on how you could use Streams inside Step component to keep data in TextFields while navigating accross steps ?

**Comment by ettaibi** [comment] 2020-06-11 10:48
For future readers, I finished by using `PageView` instead.

**Comment by Piinks** [comment] 2024-08-22 19:25
This appears to be fixed now, see this sample that shows the text content is maintained between steps:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHome(),
    );
  }
}

class MyHome extends StatefulWidget {
  @override
  State<MyHome> createState() => _MyHomeState();
}

class _MyHomeState extends State<MyHome> {
  int currentStep = 0;

  List<Step> mySteps = const [
    Step(
      title: Text("Step 1"),
      content: TextField(
        decoration: InputDecoration(
          hintText: 'Enter your name',
        ),
      ),
      isActive: true,
    ),
    Step(
      title: Text("Step 2"),
      content: Text("Hello!"),
      state: StepState.indexed,
      isActive: true,
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Stepper Example')),
      // Body
      body: Stepper(
        currentStep: currentStep,
        steps: mySteps,
        type: StepperType.horizontal,
        onStepTapped: (int step) {
          setState(
            () {
              currentStep = step;
            },
          );
        },
      ),
    );
  }
}
```

If this issue does still persist, please file a new one with sample code to reproduce. Thanks!

**Closed by Piinks** 2024-08-22 19:25 UTC
Labels: framework, f: material design, d: api docs, d: examples, team-design, triaged-design
