### ISSUE TITLE
BackdropFilter lugs in fadeIn animation

### ISSUE THREAD

**Issue by alectogeek** [flutter/flutter#43750] opened 2019-10-29 20:23 UTC
## Steps to Reproduce

I'm trying to use CachedNetwordImage package on iOS with placeholder and backdrop filter blur effect, but the backdrop filter lugs for a while during the transition from placeholder and image builder.

Screencast in slowed animations mode:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18165303/67805963-0dd22580-faa3-11e9-99b0-24e44e84374f.gif)

```
imageBuilder: (context, imageProvider) {
                      playSound();
                      return  Stack(
                        children: <Widget>[
                          Container(
                            decoration: BoxDecoration(
                              boxShadow: const <BoxShadow>[
                                BoxShadow(
                                    offset: Offset(0, 10),
                                    color: Color.fromRGBO(0, 0, 0, 0.7),
                                    blurRadius: 15,
                                    spreadRadius: -10),
                              ],
                              borderRadius: BorderRadius.circular(34),
                              image: DecorationImage(fit: BoxFit.cover, alignment: Alignment.center, image: imageProvider),
                            ),
                          ),
                          //
                          isChoiceMade
                              ? const SizedBox()
                              : ClipRRect(
                                borderRadius: BorderRadius.circular(34),
                                child: BackdropFilter(
                                  filter: ImageFilter.blur(sigmaX: 15, sigmaY: 15),
                                  child: Container(color: Colors.transparent),
                                ),
                              ),
                        ],
                      );
                    },
```

iOS 13.1.3
Release mode
iPhone 7

## Logs

```
[✓] Flutter (Channel master, v1.10.15-pre.272, on Mac OS X 10.14.6 18G103, locale en-RU)
    • Flutter version 1.10.15-pre.272 at /Users/alectogeek/Documents/Programs/flutter
    • Framework revision 5bc7fb6835 (2 days ago), 2019-10-27 21:25:13 -0700
    • Engine revision 3ebf006904
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 6354b0b97d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alectogeek/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Starlink • 2a1a85a3ec0891e413da9c4a9d5f311bd6a02abe • ios • iOS 13.1.3

• No issues found!


```

**Comment by alectogeek** [comment] 2019-10-30 16:08
@BondarenkoStas Also same behavior for Android

**Comment by alectogeek** [comment] 2019-11-04 09:31
Are there any news?

**Comment by chinmaygarde** [comment] 2019-11-04 20:02
Removing the Skia tag pending further investigation.

**Comment by liyuqian** [comment] 2019-11-04 20:27
From the gif, it's hard to tell if this is a rendering performance issue, or if the BackdropFilter is just incorrectly retained in the Widget tree (e.g., `isChoiceMade` is false while it should be true).

@alectogeek : can you please take another video screenshot with **profile mode** and [performance overlay turned on](https://flutter.dev/docs/perf/rendering/ui-performance#displaying-the-performance-overlay) so we'll know if this is a performance issue? Meanwhile, it would also be helpful if you can turn your snipped into a minimal `main.dart` file where we can copy paste it into a new `flutter create` project and reproduce your issue.

**Comment by alectogeek** [comment] 2019-11-04 21:11
@liyuqian  main.dart code:

```
import 'dart:ui';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: MediaQuery.of(context).size.width / 2,
      height: MediaQuery.of(context).size.width / 2,
      child: Center(
        child: Stack(
          children: <Widget>[
            CachedNetworkImage(
              fadeInDuration: Duration(seconds: 3),
              filterQuality: FilterQuality.medium,
              imageUrl: 'https://source.unsplash.com/random',
              fit: BoxFit.cover,
              alignment: Alignment.center,
              placeholder: (context, string) {
                return Container(
                  decoration: BoxDecoration(
                    border: Border.all(color: const Color.fromRGBO(255, 255, 255, 0.2)),
                    borderRadius: BorderRadius.circular(34),
                  ),
                  child: const Center(
                    child: CupertinoActivityIndicator(),
                  ),
                );
              },
              imageBuilder: (context, imageProvider) {
                return Stack(
                  children: <Widget>[
                    Container(
                      decoration: BoxDecoration(
                        boxShadow: const <BoxShadow>[
                          BoxShadow(
                              offset: Offset(0, 10),
                              color: Color.fromRGBO(0, 0, 0, 0.7),
                              blurRadius: 15,
                              spreadRadius: -10),
                        ],
                        borderRadius: BorderRadius.circular(34),
                        image: DecorationImage(fit: BoxFit.cover, alignment: Alignment.center, image: imageProvider),
                      ),
                    ),
                    Container(
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(34),
                        child: BackdropFilter(
                          filter: ImageFilter.blur(sigmaX: 15, sigmaY: 15),
                          child: Container(color: Colors.transparent),
                        ),
                      ),
                    ),
                  ],
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

```


the only thing you need to add to your pubspec file is:

```
cached_network_image: 2.0.0-rc
```

**Comment by liyuqian** [comment] 2019-11-11 22:33
From my testing, I didn't see any specific slow frame in either UI or GPU thread that could cause such a discontinuity in the blur animation as shown in the GIF above. I think it's a mismanagement of the animation states (maybe something is not in sync). It could be either:
1. An issue in the `CachedNetworkImage`
2. An issue in some other widgets
3. An issue in the combined usage of `CachedNetworkImage` and some other Flutter widgets.

@HansMuller : as our animation expert, can you please try the reproduction app above and give some suggestions?

**Comment by alectogeek** [comment] 2019-11-12 08:34
@liyuqian But I can reproduce it using the code above. I created a new project and there is nothing else besides the code above. Pay, please, attention to picture edges during fade-in animation.

**Comment by liyuqian** [comment] 2019-11-12 18:31
@alectogeek : yes, I can reproduce the lug too. The problem looks exactly the same as your GIF posted above. My comment above only said that I didn't see a very slow frame in any threads. So the lug may be caused by something else like a misaligned animation state.

**Comment by alectogeek** [comment] 2019-11-12 19:31
Oh, gotcha. But I didn't understand where exactly it could be misaligned, are talking about my code or framework? :)

**Comment by liyuqian** [comment] 2019-11-13 19:42
I'm a little more suspicious about our framework. That's why I think @HansMuller could provide more insights. Also CC @flar who is recently working on BackdropFilter issues.

**Comment by alectogeek** [comment] 2019-11-30 11:10
Is there any news?

**Comment by flar** [comment] 2019-12-02 19:07
I'm working to detect if we can cache the blurred background of a BackdropFilter, but that is a long term project and I have a number of PRs to finish (dependencies) before we can handle that. There is no short-term solution from these efforts.

With respect to diagnosis of what you are seeing, I have the same questions as @liyuqian with regards to what you are referring to by "lugs". Are the frames drawing slowly. Is it a high frame rate, but the progress between the two end states doesn't seem to move as linearly as you were expecting?

**Comment by LongCatIsLooong** [comment] 2019-12-02 19:49
If you are referring to the sudden change that happens near the end of the fade in animation, it's because flutter doesn't know the size of the image you're trying to load beforehand. If you specify the size of the image explicitly the transition should be smooth.

**Comment by alectogeek** [comment] 2019-12-28 14:38
@LongCatIsLooong I tried to specify image size in various vays, but it didn't help.

**Comment by pqsky7** [comment] 2020-01-14 11:08
I got the same problem, and it seems the blur effect (frosted glass effect) will temporarily disappear when the fade transition active and it will return after the fade transition done.

**Comment by flar** [comment] 2020-01-14 19:07
@pqsky7 If a BackdropFilter is a child of an Opacity widget then the BackdropFilter will not have access to the background when the Opacity has a value of anything but 1.0. BackdropFilter widgets currently cannot work inside an Opacity widget unfortunately.

See [this comment](https://github.com/flutter/flutter/issues/31706#issuecomment-522697161) for more information.

**Comment by alectogeek** [comment] 2020-02-03 10:51
@flar It worked! Thank you! Yeah, the problem was related with opacity, so I just have removed fadeInAnimation for image

**Comment by liyuqian** [comment] 2020-02-03 13:50
@alectogeek : thanks for the confirmation. Can we close this issue now?

**Comment by alectogeek** [comment] 2020-02-05 08:52
@liyuqian Sure, the workaround fits me for now. Thank you!

**Closed** 2020-02-05 08:52 UTC
Labels: engine, framework, severe: rendering
