### ISSUE TITLE
flutter firbase connection issu

### ISSUE THREAD

**Issue by SachinAnandSaini** [flutter/flutter#73232] opened 2021-01-03 07:37 UTC
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/firebase_core.dart:7:8: Error: Error when reading '../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_platform_interface-2.1.0/lib/firebase_core_platform_interface.dart': The system cannot find the path specified.

import 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart'

**Comment by Harmanjit14** [comment] 2021-01-03 14:17
add firebase_core plugin to pubspec.yaml and then try this
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
 WidgetsFlutterBinding.ensureInitialized();
 runApp(new MyApp());
}
```

**Comment by Harmanjit14** [comment] 2021-01-03 14:19
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/firebase_core.dart:7:8: Error: Error when reading '../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_platform_interface-2.1.0/lib/firebase_core_platform_interface.dart': The system cannot find the path specified.
> 
> import 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart'

add firebase_core plugin to pubspec.yaml and then try this
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
 WidgetsFlutterBinding.ensureInitialized();
 runApp(new MyApp());
}
```

**Comment by iapicca** [comment] 2021-01-03 14:21
@SachinAnandSaini
the issue seems to be cause by [firebase](https://firebase.flutter.dev/), which is a 3rd party plugin
please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by SachinAnandSaini** [comment] 2021-01-03 15:20
@Harmanjit14 

i am using these dependency in my  pubspec.yaml  but issue is same 
 

  firebase_auth: ^0.18.4+1
  firebase_database: ^4.4.0
  firebase_core: ^0.5.3

**Comment by SachinAnandSaini** [comment] 2021-01-03 15:21
Launching lib\main.dart on SM G610F in debug mode...
Running Gradle task 'assembleDebug'...
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/firebase_core.dart:7:8: Error: Error when reading '../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_platform_interface-2.1.0/lib/firebase_core_platform_interface.dart': The system cannot find the path specified.

import 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart'
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/firebase_core.dart:12:1: Error: Error when reading '../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_platform_interface-2.1.0/lib/firebase_core_platform_interface.dart': The system cannot find the path specified.

export 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart'
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase_app.dart:11:3: Error: Type 'FirebaseAppPlatform' not found.
  FirebaseAppPlatform _delegate;
  ^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase_app.dart:46:15: Error: Type 'FirebaseOptions' not found.
    @required FirebaseOptions options,
              ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase_app.dart:67:3: Error: Type 'FirebaseOptions' not found.
  FirebaseOptions get options => _delegate.options;
  ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:16:10: Error: Type 'FirebasePlatform' not found.
  static FirebasePlatform delegatePackingProperty;
         ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:18:10: Error: Type 'FirebasePlatform' not found.
  static FirebasePlatform get _delegate {
         ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:41:21: Error: Type 'FirebaseOptions' not found.
      {String name, FirebaseOptions options}) async {
                    ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase_app.dart:11:3: Error: 'FirebaseAppPlatform' isn't a type.
  FirebaseAppPlatform _delegate;
  ^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase_app.dart:19:5: Error: The getter 'FirebaseAppPlatform' isn't defined for the class 'FirebaseApp'.
 - 'FirebaseApp' is from 'package:firebase_core/firebase_core.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/firebase_core.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FirebaseAppPlatform'.
    FirebaseAppPlatform.verifyExtends(_delegate);
    ^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase_app.dart:46:15: Error: 'FirebaseOptions' isn't a type.
    @required FirebaseOptions options,
              ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase_app.dart:60:12: Error: Getter not found: 'defaultFirebaseAppName'.
    return defaultFirebaseAppName;
           ^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:16:10: Error: 'FirebasePlatform' isn't a type.
  static FirebasePlatform delegatePackingProperty;
         ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:20:33: Error: Getter not found: 'FirebasePlatform'.
      delegatePackingProperty = FirebasePlatform.instance;
                                ^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:41:21: Error: 'FirebaseOptions' isn't a type.
      {String name, FirebaseOptions options}) async {
                    ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:42:5: Error: 'FirebaseAppPlatform' isn't a type.
    FirebaseAppPlatform app =
    ^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:51:41: Error: Getter not found: 'defaultFirebaseAppName'.
  static FirebaseApp app([String name = defaultFirebaseAppName]) {
                                        ^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/lib/src/firebase.dart:52:5: Error: 'FirebaseAppPlatform' isn't a type.
    FirebaseAppPlatform app = _delegate.app(name);
    ^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'B:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'B:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 14s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pedromassangocode** [comment] 2021-01-04 09:22
Hi @SachinAnandSaini 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-04 09:22 UTC
