### ISSUE TITLE
Black screen after resume from background

### ISSUE THREAD

**Issue by kaisen199** [flutter/flutter#154525] opened 2024-09-03 03:29 UTC
### Steps to reproduce

1. Run the example app
2. Open a map page ( For example: Manage clustering)
3. Add a cluster
4. Put the app to background
5. Switch around to use other apps / Switch to other app and leave the device unused for sometime. Occasional but high frequency.
6. Resume app

Samsung Galaxy device

### Expected results

Map resume to existing state / App refreshed?

### Actual results

App black screen and stuck

### Code sample

Use example app

### Screenshots or Video

blackscreen

### Logs

<details open><summary>Logs</summary>

```console
I/ViewRootImpl@b0de174[FlutterActivity](12828): ViewPostIme pointer 0
I/ViewRootImpl@b0de174[FlutterActivity](12828): ViewPostIme pointer 1
D/MapsInitializer(12828): preferredRenderer: null
D/zzcc    (12828): preferredRenderer: null
I/Google Android Maps SDK(12828): Google Play services package version: 243333039
I/Google Android Maps SDK(12828): Google Play services maps renderer version(maps_core): 242625203
D/CompatibilityChangeReporter(12828): Compat change id reported: 210923482; UID 10434; state: DISABLED
D/CompatibilityChangeReporter(12828): Compat change id reported: 37756858; UID 10434; state: ENABLED
D/CompatibilityChangeReporter(12828): Compat change id reported: 171228096; UID 10434; state: ENABLED
W/Settings(12828): Setting device_provisioned has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
D/CompatibilityChangeReporter(12828): Compat change id reported: 247079863; UID 10434; state: DISABLED
W/JavaCronetEngine(12828): using the fallback Cronet Engine implementation. Performance will suffer and many HTTP client features, including caching, will not work.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
D/ConnectivityManager(12828): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4402)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4966)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4933)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4907)] [m.n$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:27)] [m.bac.b(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:53)] [m.aze.f(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:9)] [m.azb.a(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:1)] [m.amh.<init>(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:95)] [com.google.maps.api.android.lib6.phoenix.w.<init>(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:1)] [m.alk.a(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:3)] [m.azu.a(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:196)] [m.alm.c(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:12)] [m.cdt.b(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:15)] [m.iuk.b(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:16)] [m.iur.b(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:3)] [m.iuk.b(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:16)] [m.euk.run(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:50)] [java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)] [m.buo$a.run(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:19)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)] [m.bvd.run(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:40)] [java.lang.Thread.run(Thread.java:1012)]
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
I/PlatformViewsController(12828): Hosting view in view hierarchy for platform view: 0
I/PlatformViewsController(12828): PlatformView is using SurfaceProducer backend
W/WindowOnBackDispatcher(12828): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher(12828): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/CompatibilityChangeReporter(12828): Compat change id reported: 236825255; UID 10434; state: DISABLED
D/NativeCustomFrequencyManager(12828): [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
D/OpenGLRenderer(12828): CFMS:: SetUp Pid : 12828    Tid : 12873
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
I/GoogleMapController(12828): Installing custom TextureView driven invalidator.
E/GoogleMapController(12828): Cannot enable MyLocation layer as location permissions are not granted
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
D/TrafficStats(12828): tagSocket(184) with statsTag=0x99e6744e, statsUid=-1
D/TrafficStats(12828): tagSocket(183) with statsTag=0xffffffff, statsUid=-1
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
D/TrafficStats(12828): tagSocket(158) with statsTag=0xffffffff, statsUid=-1
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
D/TrafficStats(12828): tagSocket(172) with statsTag=0xffffffff, statsUid=-1
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
D/TrafficStats(12828): tagSocket(235) with statsTag=0xffffffff, statsUid=-1
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
W/ProxyAndroidLoggerBackend(12828): Too many Flogger logs received before configuration. Dropping old logs.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
I/oglemapsexample(12828): Compiler allocated 4956KB to compile void m.epv.n()
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
I/oglemapsexample(12828): Compiler allocated 5511KB to compile void m.eio.V(m.emq, m.fdj, android.content.res.Resources, m.eks, m.eve, boolean, m.dlh, java.util.Map, boolean, boolean, boolean)
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
I/ViewRootImpl@b0de174[FlutterActivity](12828): ViewPostIme pointer 0
I/ViewRootImpl@b0de174[FlutterActivity](12828): ViewPostIme pointer 1
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
I/oglemapsexample(12828): Compiler allocated 4376KB to compile void m.edm.b(m.dlw, m.ece, m.eeh, m.ele, boolean)
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
E/FrameEvents(12828): updateAcquireFence: Did not find frame.
I/ViewRootImpl@b0de174[FlutterActivity](12828): handleWindowFocusChanged: 0 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
I/ImeFocusController(12828): onPreWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
I/ImeFocusController(12828): onPostWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
D/InputTransport(12828): Input channel destroyed: 'ClientS', fd=157
I/ViewRootImpl@b0de174[FlutterActivity](12828): handleAppVisibility mAppVisible = true visible = false
I/SurfaceView@7a0add6(12828): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{7a0add6 V.E...... ........ 0,0-1080,2196} of ViewRootImpl@b0de174[FlutterActivity]
I/SurfaceView(12828): 127970774 Changes: creating=false format=false size=false visible=true alpha=false hint=false visible=true left=false top=false z=false attached=true lifecycleStrategy=false
I/SurfaceView@7a0add6(12828): 127970774 Cur surface: Surface(name=null)/@0x8c86ac3
I/SurfaceView(12828): 127970774 surfaceDestroyed
I/SurfaceView@7a0add6(12828): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{7a0add6 V.E...... ........ 0,0-1080,2196}
I/SurfaceView@7a0add6(12828): updateSurface: mVisible = false mSurface.isValid() = true
I/SurfaceView@7a0add6(12828): releaseSurfaces: viewRoot = ViewRootImpl@b0de174[FlutterActivity]
V/SurfaceView@7a0add6(12828): Layout: x=0 y=0 w=1080 h=2196, frame=Rect(0, 0 - 1080, 2196)
I/ViewRootImpl@b0de174[FlutterActivity](12828): destroyHardwareResources: Callers=android.view.ViewRootImpl.performTraversals:3932 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698 android.view.Choreographer.doCallbacks:1153 android.view.Choreographer.doFrame:1079 android.view.Choreographer$FrameDisplayEventReceiver.run:1646 android.os.Handler.handleCallback:958 android.os.Handler.dispatchMessage:99 
D/SurfaceView(12828): 15344977 windowPositionLost, frameNr = 0
I/ViewRootImpl@b0de174[FlutterActivity](12828): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) relayoutAsync=false req=(1080,2340)8 dur=7 res=0x402 s={false 0x0} ch=true seqId=0
I/SurfaceView@7a0add6(12828): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{7a0add6 V.E...... ........ 0,0-1080,2196} of ViewRootImpl@b0de174[FlutterActivity]
D/SurfaceView@7a0add6(12828): updateSurface: surface is not valid
I/SurfaceView@7a0add6(12828): releaseSurfaces: viewRoot = ViewRootImpl@b0de174[FlutterActivity]
D/SurfaceView@7a0add6(12828): updateSurface: surface is not valid
I/SurfaceView@7a0add6(12828): releaseSurfaces: viewRoot = ViewRootImpl@b0de174[FlutterActivity]
D/ConnectivityManager(12828): StackLog: [android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:5076)] [m.fdy.d(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:20)] [com.google.maps.api.android.lib6.impl.p.b(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:62)] [com.google.maps.api.android.lib6.impl.l.onTrimMemory(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:7)] [android.content.ComponentCallbacksController.lambda$dispatchTrimMemory$1(ComponentCallbacksController.java:109)] [android.content.ComponentCallbacksController$$ExternalSyntheticLambda1.accept(Unknown Source:4)] [android.content.ComponentCallbacksController.forAllComponentCallbacks(ComponentCallbacksController.java:124)] [android.content.ComponentCallbacksController.dispatchTrimMemory(ComponentCallbacksController.java:107)] [android.app.Application.onTrimMemory(Application.java:308)] [android.app.ActivityThread.handleTrimMemory(ActivityThread.java:7274)] [android.app.ActivityThread.-$$Nest$mhandleTrimMemory(Unknown Source:0)] [android.app.ActivityThread$ApplicationThread.$r8$lambda$jsQe3dM6MF6rTESBpFm4N1cH4V4(Unknown Source:0)] [android.app.ActivityThread$ApplicationThread$$ExternalSyntheticLambda2.accept(Unknown Source:8)] [com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)] [com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)] [com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:87)] [android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)] [android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)] [android.view.Choreographer.doCallbacks(Choreographer.java:1153)] [android.view.Choreographer.doFrame(Choreographer.java:1081)] [android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)]
D/OpenGLRenderer(12828): CacheManager::trimMemory(20)
I/ViewRootImpl@b0de174[FlutterActivity](12828): stopped(true) old = false
D/ViewRootImpl@b0de174[FlutterActivity](12828): WindowStopped on io.flutter.plugins.googlemapsexample/io.flutter.embedding.android.FlutterActivity set to true
D/SurfaceView@7a0add6(12828): updateSurface: surface is not valid
I/SurfaceView@7a0add6(12828): releaseSurfaces: viewRoot = ViewRootImpl@b0de174[FlutterActivity]
D/SurfaceView@7a0add6(12828): updateSurface: surface is not valid
I/SurfaceView@7a0add6(12828): releaseSurfaces: viewRoot = ViewRootImpl@b0de174[FlutterActivity]
D/Choreographer(12828): CoreRune.SYSPERF_ACTIVE_APP_BBA_ENABLE : stop animation in background states
D/OpenGLRenderer(12828): CacheManager::trimMemory(20)
D/OpenGLRenderer(12828): CacheManager::trimMemory(40)
D/OpenGLRenderer(12828): RenderThread::destroyRenderingContext()
Lost connection to device.
the Dart compiler exited unexpectedly.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale en-GB)
    • Flutter version 3.22.1 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 months ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

```
</details>

**Comment by darshankawar** [comment] 2024-09-03 08:51
I believe you are hitting https://github.com/flutter/flutter/issues/139630, so follow the underlying comments and  https://github.com/flutter/flutter/issues/139630#issuecomment-2007673827 for your further reference.
Closing as duplicate of it. 
If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2024-09-03 08:51 UTC
Labels: in triage
