### ISSUE TITLE
TextureRegistry.SurfaceProducer.Callback class Callback not found

### ISSUE THREAD

**Issue by divyamplutomoney** [flutter/flutter#155604] opened 2024-09-24 14:40 UTC
### Steps to reproduce

```console
/Users/divyamverma/.pub-cache/hosted/pub.dev/camera_android_camerax-0.6.8+2/android/src/main/java/io/flutter/plugins/camerax/PreviewHostApiImpl.java:84: error: cannot find symbol
            new TextureRegistry.SurfaceProducer.Callback() {
                                               ^
  symbol:   class Callback
  location: interface SurfaceProducer
/Users/divyamverma/.pub-cache/hosted/pub.dev/camera_android_camerax-0.6.8+2/android/src/main/java/io/flutter/plugins/camerax/PreviewHostApiImpl.java:85: error: method does not override or implement a method from a supertype
              @Override
              ^
/Users/divyamverma/.pub-cache/hosted/pub.dev/camera_android_camerax-0.6.8+2/android/src/main/java/io/flutter/plugins/camerax/PreviewHostApiImpl.java:91: error: method does not override or implement a method from a supertype
              @Override
              ^
3 errors

FAILURE: Build failed with an exception.
```

### Expected results

it should not give that issue

### Actual results

apk should  built

### Code sample

plugin has issue 

### Screenshots or Video

video not required

### Logs

```console
TextureRegistry.SurfaceProducer.Callback() {
                                               ^
  symbol:   class Callback
  location: interface SurfaceProducer
```
### Flutter Doctor output

```console
[!] Flutter (Channel [user-branch], 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    ! Flutter version 3.22.0 on channel [user-branch] at /Users/divyamverma/Documents/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 5dcb86f68f (5 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/divyamverma/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • SM E346B (mobile)               • RZCW80JP8FA           • android-arm64 • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64  • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin        • macOS 14.5 23F79 darwin-arm64
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

**Comment by huycozy** [comment] 2024-09-25 04:29
This is similar to https://github.com/flutter/flutter/issues/154332, https://github.com/flutter/flutter/issues/154054 and it is said that it is [fixed on 3.24.1](https://github.com/flutter/flutter/issues/154054#issuecomment-2308823071), please upgrade your Flutter SDK and retry. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/154332. If the issue still persists on the latest Flutter stable release, please write in comments and I will reopen this. Thanks!

**Closed by huycozy** 2024-09-25 04:29 UTC
Labels: in triage
