### ISSUE TITLE
[Android] External views are broken on master

### ISSUE THREAD

**Issue by XuanTung95** [flutter/flutter#133525] opened 2023-08-29 02:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

External views seem broken on master since https://github.com/flutter/flutter/commit/777192651705e8d64947c7d2f4be2b249e1af2b3

### Expected results

FloatingActionButton is visible above external views

### Actual results

FloatingActionButton is cut off

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class ScreenTest extends StatefulWidget {
  const ScreenTest({super.key});

  @override
  State<ScreenTest> createState() => _ScreenTestState();
}

class _ScreenTestState extends State<ScreenTest> {

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(onPressed: () {

      },),
      body: CustomScrollView(
        slivers: [SliverList(delegate: SliverChildBuilderDelegate(
            (context, index) {
              if (index == 8) {
                return SizedBox(
                  height: 100,
                  child: GoogleMap(
                      initialCameraPosition: _kGooglePlex,
                      onMapCreated: (GoogleMapController controller) {
                        print("onMapCreated mapId: ${controller.mapId}");
                      }
                  ),
                );
              }
              return SizedBox(
                  height: 100,
                  child: Placeholder());
            }
        ))],
      ),
    );
  }
}

```

```
  google_maps_flutter: 2.3.1
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media [here]]([url]([url](url)))
![z4645419735281_68e2e5482ecb334b2ad42a42a09b43fb](https://github.com/flutter/flutter/assets/26743089/f41b47cf-1c36-4cb2-8cd6-3f57a80c2a69)
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.14.0-12.0.pre.75, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-12.0.pre.75 on channel master at /Users/xuantung/Desktop/Develop/flutter/master/flutter
    ! Warning: `flutter` on your path resolves to /Users/xuantung/Desktop/Develop/flutter/3.3.10/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/xuantung/Desktop/Develop/flutter/master/flutter. Consider adding /Users/xuantung/Desktop/Develop/flutter/master/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/xuantung/Desktop/Develop/flutter/3.3.10/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/xuantung/Desktop/Develop/flutter/master/flutter. Consider adding /Users/xuantung/Desktop/Develop/flutter/master/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e6c7b84920 (62 minutes ago), 2023-08-28 21:29:15 -0400
    • Engine revision 1e821961e9
    • Dart version 3.2.0 (build 3.2.0-117.0.dev)
    • DevTools version 2.26.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/xuantung/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

</details>

**Comment by darshankawar** [comment] 2023-08-29 08:25
Thanks for the report @XuanTung95 
I tried the code sample using latest master (3.14.0-12.0.pre.78) on Pixel emulator and observed that the FAB gets cut off while scrolling up or down through the views as shown below:



https://github.com/flutter/flutter/assets/67046386/cadbb6aa-a68d-441e-902e-0bf2ba7ec484

While running the same scenario on latest stable seems to be working fine as FAB is rendered correctly.


https://github.com/flutter/flutter/assets/67046386/0bfee7ae-b4e5-45f9-9419-73e987fe18e4




<details>
<summary> master flutter doctor -v </summary>

```

[!] Flutter (Channel master, 3.14.0-12.0.pre.78, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.14.0-12.0.pre.78 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6dae269881 (36 minutes ago), 2023-08-29 00:22:24 -0400
    • Engine revision c7c61ff973
    • Dart version 3.2.0 (build 3.2.0-118.0.dev)
    • DevTools version 2.26.2
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by jonahwilliams** [comment] 2023-08-31 02:03
@darshankawar can you confirm that this is fixed after https://github.com/flutter/engine/pull/45085 landed in the framework? Anything at ToT after https://github.com/flutter/flutter/pull/133298 ?

**Comment by jonahwilliams** [comment] 2023-08-31 02:18
Actually I'll just try to repro it, the code is simple

**Comment by jonahwilliams** [comment] 2023-08-31 02:27
This still reproduces at ToT.

**Comment by dnfield** [comment] 2023-09-01 22:29
This was fixed by the revert, @flar tells me there's no intention of relanding that patch anytime soon.

**Closed by dnfield** 2023-09-01 22:29 UTC
Labels: c: regression, platform-android, engine, a: platform-views, has reproducible steps, P0, fyi-android, team-engine, found in release: 3.14
