### ISSUE TITLE
flutter test fails when run under checked mode

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4807] opened 2016-07-01 04:33 UTC
From https://github.com/flutter/flutter/issues/4803, `flutter test` fails with a 'Connection closed' error when the flutter tool is run in checked mode. Once this is fixed, we should consider turning on checked mode for all runs of the flutter tool (`-c`).

**Comment by abarth** [comment] 2016-07-01 04:37
I think the problem is with the stream sink/source type parameters.

**Comment by sethladd** [comment] 2016-09-14 17:38
We should totally run tests with checked mode! :)

**Comment by Hixie** [comment] 2017-01-31 06:10
This is fixed now. Moving to checked mode is https://github.com/flutter/flutter/pull/7655 and is blocked on unrelated stuff.

**Closed by Hixie** 2017-01-31 06:10 UTC
Labels: dev: tool, waiting for PR to land (fixed)
