### ISSUE TITLE
Scrollable is missing API docs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9655] opened 2017-04-27 21:16 UTC
Not sure if this means I shouldn't use it, or if we just haven't documented it yet :)

https://docs.flutter.io/flutter/widgets/Scrollable-class.html

**Comment by abarth** [comment] 2017-04-27 21:19
Duplicate of #1645

We've been waiting for nested scrolling to land, but that's out of hte way now,.

**Closed by abarth** 2017-04-27 21:19 UTC
Labels: dev: docs, dev: docs - api
