### ISSUE TITLE
[PLUGIN][webview_flutter] plugin not working on 'flutter run -d web-server'

### ISSUE THREAD

**Issue by ZurMaD** [flutter/flutter#82622] opened 2021-05-15 18:03 UTC
## Steps to Reproduce

This is a minimal app to reproduce the error

```
# Using dockerized environment
git clone https://github.com/DZGames/flutter_webview
# open visual code and load REMOTE-CONTAINER with folder cloned 
# env config already changes branch to develop in 
# open a new terminal in VSCode
cd octal_clock_app
flutter pub get
flutter run -d web-server # ERROR: Not loading
flutter build apk # works as expected
```

**Expected results:** 

The URL iframed in flutter web like in the apk builded, permissions and cleartext are already specified.

**Actual results:** 

I'm getting a screen with ERRORS, but on the apk everything works as expected

WEB:

![image](https://user-images.githubusercontent.com/28235457/118373700-ca081980-b57d-11eb-8155-b71562e588de.png)

APK on android:
![image](https://user-images.githubusercontent.com/28235457/118373790-32ef9180-b57e-11eb-8e3e-3684a7dba7b1.png)

<details>
  <summary>Logs</summary>

```
developer@190051f7a557:~/workspace/octal_clock_app$ flutter run -d web-server --verbose
[  +45 ms] executing: [/home/developer/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +19 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] executing: [/home/developer/flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[   +5 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +23 ms] executing: [/home/developer/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/developer/flutter/] git ls-remote --get-url origin
[   +1 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +20 ms] executing: [/home/developer/flutter/] git rev-parse --abbrev-ref HEAD
[   +1 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +33 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] executing: /home/developer/Android/Sdk/platform-tools/adb devices -l
[  +10 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +39 ms] executing: /home/developer/Android/Sdk/platform-tools/adb devices -l
[  +10 ms] Running "flutter pub get" in octal_clock_app...
[   +3 ms] executing: [/home/developer/workspace/octal_clock_app/] /home/developer/flutter/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +16 ms] List of devices attached
[   +1 ms] List of devices attached
[  +22 ms] FINE: Pub 2.12.3
[  +54 ms] MSG : Resolving dependencies...
[  +20 ms] SLVR: fact: octal_clock_app is 1.0.0+1
[   +3 ms] SLVR: derived: octal_clock_app
[  +13 ms] SLVR: fact: octal_clock_app depends on flutter any from sdk
[        ] SLVR: fact: octal_clock_app depends on cupertino_icons ^0.1.2
[        ] SLVR: fact: octal_clock_app depends on webview_flutter ^2.0.4
[        ] SLVR: fact: octal_clock_app depends on flutter_test any from sdk
[        ] SLVR:   selecting octal_clock_app
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: webview_flutter ^2.0.4
[        ] SLVR:   derived: cupertino_icons ^0.1.2
[        ] SLVR:   derived: flutter any from sdk
[   +7 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.19
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on path 1.8.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on fake_async 1.2.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on clock 1.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.10.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on vector_math 2.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on async 2.5.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on boolean_selector 2.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on characters 1.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on charcode 1.2.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on collection 1.15.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.10
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on meta 1.3.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on source_span 1.8.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.2.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on typed_data 1.3.0
[        ] SLVR:     selecting flutter_test 0.0.0 from sdk
[        ] SLVR:     derived: typed_data 1.3.0
[        ] SLVR:     derived: term_glyph 1.2.0
[        ] SLVR:     derived: string_scanner 1.1.0
[        ] SLVR:     derived: stream_channel 2.1.0
[        ] SLVR:     derived: source_span 1.8.0
[        ] SLVR:     derived: meta 1.3.0
[        ] SLVR:     derived: matcher 0.12.10
[        ] SLVR:     derived: collection 1.15.0
[        ] SLVR:     derived: charcode 1.2.0
[        ] SLVR:     derived: characters 1.1.0
[        ] SLVR:     derived: boolean_selector 2.1.0
[        ] SLVR:     derived: async 2.5.0
[        ] SLVR:     derived: vector_math 2.1.0
[        ] SLVR:     derived: stack_trace 1.10.0
[        ] SLVR:     derived: clock 1.1.0
[        ] SLVR:     derived: fake_async 1.2.0
[        ] SLVR:     derived: path 1.8.0
[        ] SLVR:     derived: test_api 0.2.19
[   +7 ms] SLVR:     fact: webview_flutter 2.0.4 depends on flutter any from sdk
[        ] SLVR:       selecting webview_flutter 2.0.4
[   +3 ms] SLVR:         selecting cupertino_icons 0.1.3
[   +3 ms] SLVR:         fact: flutter 0.0.0 from sdk depends on characters 1.1.0
[        ] SLVR:         fact: flutter 0.0.0 from sdk depends on collection 1.15.0
[        ] SLVR:         fact: flutter 0.0.0 from sdk depends on meta 1.3.0
[        ] SLVR:         fact: flutter 0.0.0 from sdk depends on typed_data 1.3.0
[        ] SLVR:         fact: flutter 0.0.0 from sdk depends on vector_math 2.1.0
[        ] SLVR:         fact: flutter 0.0.0 from sdk depends on sky_engine any from sdk
[        ] SLVR:           selecting flutter 0.0.0 from sdk
[        ] SLVR:           derived: sky_engine any from sdk
[   +2 ms] SLVR:           fact: typed_data 1.3.0 depends on collection ^1.15.0
[        ] SLVR:             selecting typed_data 1.3.0
[   +2 ms] SLVR:               selecting term_glyph 1.2.0
[   +2 ms] SLVR:               fact: string_scanner 1.1.0 depends on charcode ^1.2.0
[        ] SLVR:               fact: string_scanner 1.1.0 depends on source_span ^1.8.0
[        ] SLVR:                 selecting string_scanner 1.1.0
[   +1 ms] SLVR:                 fact: stream_channel 2.1.0 depends on async ^2.5.0
[        ] SLVR:                   selecting stream_channel 2.1.0
[   +1 ms] SLVR:                   fact: source_span 1.8.0 depends on charcode ^1.2.0
[        ] SLVR:                   fact: source_span 1.8.0 depends on collection ^1.15.0
[        ] SLVR:                   fact: source_span 1.8.0 depends on path ^1.8.0
[        ] SLVR:                   fact: source_span 1.8.0 depends on term_glyph ^1.2.0
[        ] SLVR:                     selecting source_span 1.8.0
[   +1 ms] SLVR:                       selecting meta 1.3.0
[   +1 ms] SLVR:                       fact: matcher 0.12.10 depends on stack_trace ^1.10.0
[        ] SLVR:                         selecting matcher 0.12.10
[   +1 ms] SLVR:                           selecting collection 1.15.0
[   +1 ms] SLVR:                             selecting charcode 1.2.0
[   +1 ms] SLVR:                               selecting characters 1.1.0
[   +1 ms] SLVR:                               fact: boolean_selector 2.1.0 depends on source_span ^1.8.0
[        ] SLVR:                               fact: boolean_selector 2.1.0 depends on string_scanner ^1.1.0
[        ] SLVR:                                 selecting boolean_selector 2.1.0
[   +1 ms] SLVR:                                 fact: async 2.5.0 depends on collection ^1.15.0
[        ] SLVR:                                   selecting async 2.5.0
[   +1 ms] SLVR:                                     selecting vector_math 2.1.0
[   +1 ms] SLVR:                                     fact: stack_trace 1.10.0 depends on path ^1.8.0
[        ] SLVR:                                       selecting stack_trace 1.10.0
[   +1 ms] SLVR:                                         selecting clock 1.1.0
[   +1 ms] SLVR:                                         fact: fake_async 1.2.0 depends on clock ^1.1.0
[        ] SLVR:                                         fact: fake_async 1.2.0 depends on collection ^1.15.0
[        ] SLVR:                                           selecting fake_async 1.2.0
[        ] SLVR:                                             selecting path 1.8.0
[   +2 ms] SLVR:                                             fact: test_api 0.2.19 depends on async ^2.5.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on boolean_selector ^2.1.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on collection ^1.15.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on meta ^1.3.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on path ^1.8.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on source_span ^1.8.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on stack_trace ^1.10.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on stream_channel ^2.1.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on string_scanner ^1.1.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on term_glyph ^1.2.0
[        ] SLVR:                                             fact: test_api 0.2.19 depends on matcher >=0.12.10 <0.12.11
[        ] SLVR:                                               selecting test_api 0.2.19
[        ] SLVR:                                                 selecting sky_engine 0.0.99 from sdk
[  +60 ms] SLVR: Version solving took 0:00:00.144348 seconds.
[        ]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (0.163s).
[  +43 ms] MSG :   async 2.5.0 (2.6.1 available)
[        ]     |   cupertino_icons 0.1.3 (1.0.3 available)
[        ]     |   source_span 1.8.0 (1.8.1 available)
[        ]     |   test_api 0.2.19 (0.4.0 available)
[  +26 ms] IO  : Writing 3646 characters to text file ./pubspec.lock.
[        ] FINE: Contents:
[        ]     | # Generated by pub
[        ]     | # See https://dart.dev/tools/pub/glossary#lockfile
[        ]     | packages:
[        ]     |   async:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: async
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.5.0"
[        ]     |   boolean_selector:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: boolean_selector
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.1.0"
[        ]     |   characters:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: characters
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0"
[        ]     |   charcode:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: charcode
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.2.0"
[        ]     |   clock:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: clock
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0"
[        ]     |   collection:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: collection
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.15.0"
[        ]     |   cupertino_icons:
[        ]     |     dependency: "direct main"
[        ]     |     description:
[        ]     |       name: cupertino_icons
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "0.1.3"
[        ]     |   fake_async:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: fake_async
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.2.0"
[        ]     |   flutter:
[        ]     |     dependency: "direct main"
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.0"
[        ]     |   flutter_test:
[        ]     |     dependency: "direct dev"
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.0"
[        ]     |   matcher:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: matcher
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "0.12.10"
[        ]     |   meta:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: meta
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.3.0"
[        ]     |   path:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: path
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.8.0"
[        ]     |   sky_engine:
[        ]     |     dependency: transitive
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.99"
[        ]     |   source_span:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: source_span
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.8.0"
[        ]     |   stack_trace:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: stack_trace
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.10.0"
[        ]     |   stream_channel:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: stream_channel
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.1.0"
[        ]     |   string_scanner:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: string_scanner
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0"
[        ]     |   term_glyph:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: term_glyph
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.2.0"
[        ]     |   test_api:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: test_api
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "0.2.19"
[        ]     |   typed_data:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: typed_data
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.3.0"
[        ]     |   vector_math:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: vector_math
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.1.0"
[        ]     |   webview_flutter:
[        ]     |     dependency: "direct main"
[        ]     |     description:
[        ]     |       name: webview_flutter
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.0.4"
[        ]     | sdks:
[        ]     |   dart: ">=2.12.0-259.9.beta <3.0.0"
[        ]     |   flutter: ">=1.22.0"
[        ] IO  : Writing 2262 characters to text file ./.packages.
[        ] FINE: Contents:
[        ]     | # This file is deprecated. Tools should instead consume 
[        ]     | # `.dart_tools/package_config.json`.
[        ]     | # 
[        ]     | # For more info see: https://dart.dev/go/dot-packages-deprecation
[        ]     | # 
[        ]     | # Generated by pub on 2021-05-15 23:01:58.351602.
[        ]     | async:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/async-2.5.0/lib/
[        ]     | boolean_selector:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0/lib/
[        ]     | characters:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0/lib/
[        ]     | charcode:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0/lib/
[        ]     | clock:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/clock-1.1.0/lib/
[        ]     | collection:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0/lib/
[        ]     | cupertino_icons:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-0.1.3/lib/
[        ]     | fake_async:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/fake_async-1.2.0/lib/
[        ]     | flutter:file:///home/developer/flutter/packages/flutter/lib/
[        ]     | flutter_test:file:///home/developer/flutter/packages/flutter_test/lib/
[        ]     | matcher:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.10/lib/
[        ]     | meta:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0/lib/
[        ]     | path:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/path-1.8.0/lib/
[        ]     | sky_engine:file:///home/developer/flutter/bin/cache/pkg/sky_engine/lib/
[        ]     | source_span:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.0/lib/
[        ]     | stack_trace:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.10.0/lib/
[        ]     | stream_channel:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.1.0/lib/
[        ]     | string_scanner:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0/lib/
[        ]     | term_glyph:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.2.0/lib/
[        ]     | test_api:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.19/lib/
[        ]     | typed_data:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/typed_data-1.3.0/lib/
[        ]     | vector_math:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.0/lib/
[        ]     | webview_flutter:file:///home/developer/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.4/lib/
[        ]     | octal_clock_app:lib/
[        ] MSG : Got dependencies!
[   +2 ms] IO  : Writing 4713 characters to text file ./.dart_tool/package_config.json.
[        ] FINE: Contents:
[        ]     | {
[        ]     |   "configVersion": 2,
[        ]     |   "packages": [
[        ]     |     {
[        ]     |       "name": "async",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/async-2.5.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "boolean_selector",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "characters",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "charcode",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "clock",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/clock-1.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "collection",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "cupertino_icons",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-0.1.3",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.0"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "fake_async",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/fake_async-1.2.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "flutter",
[        ]     |       "rootUri": "file:///home/developer/flutter/packages/flutter",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "flutter_test",
[        ]     |       "rootUri": "file:///home/developer/flutter/packages/flutter_test",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "matcher",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.10",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "meta",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "path",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/path-1.8.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "sky_engine",
[        ]     |       "rootUri": "file:///home/developer/flutter/bin/cache/pkg/sky_engine",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "source_span",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "stack_trace",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.10.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "stream_channel",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "string_scanner",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "term_glyph",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.2.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "test_api",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.19",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "typed_data",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/typed_data-1.3.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "vector_math",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "webview_flutter",
[        ]     |       "rootUri": "file:///home/developer/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.4",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "octal_clock_app",
[        ]     |       "rootUri": "../",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.7"
[        ]     |     }
[        ]     |   ],
[        ]     |   "generated": "2021-05-15T23:01:58.364988Z",
[        ]     |   "generator": "pub",
[        ]     |   "generatorVersion": "2.12.3"
[        ]     | }
[  +17 ms] Running "flutter pub get" in octal_clock_app... (completed in 385ms)
[  +39 ms] Found plugin webview_flutter at /home/developer/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.4/
[  +83 ms] Found plugin webview_flutter at /home/developer/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.4/
[  +19 ms] Generating /home/developer/workspace/octal_clock_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +85 ms] Launching lib/main.dart on Web Server in debug mode...
[  +67 ms] Updating assets
[  +49 ms] Waiting for connection from debug service on Web Server...
[  +11 ms] Found plugin webview_flutter at /home/developer/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.4/
[  +14 ms] Found plugin webview_flutter at /home/developer/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.4/
[  +56 ms] <- reset
[   +3 ms] /home/developer/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/developer/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/developer/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.GAOBCY/flutter_tool.JEUQHC/app.dill --libraries-spec file:///home/developer/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/developer/workspace/octal_clock_app/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root /tmp/flutter_tools.GAOBCY/flutter_tools.JDGSOD --filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///home/developer/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[   +4 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+9859 ms] Waiting for connection from debug service on Web Server... (completed in 9.9s)
[        ] Synced 29.2MB.
[        ] <- accept
[        ] Caching compiled dill
[ +497 ms] lib/main.dart is being served at http://localhost:35325
[        ] The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development
workflow.
[   +3 ms] 🔥  To hot restart changes while running, press "r" or "R".

```

```
developer@190051f7a557:~/workspace/octal_clock_app$ flutter analyze
Running "flutter pub get" in octal_clock_app...                    322ms
Analyzing octal_clock_app...                                            
No issues found! (ran in 21.2s)
```

```
developer@190051f7a557:~/workspace/octal_clock_app$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.6 at /home/developer/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/developer/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /home/developer/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

**Comment by ZurMaD** [comment] 2021-05-16 01:11
Related https://github.com/flutter/flutter/projects/166

**Comment by TahaTesser** [comment] 2021-05-17 10:06
Hi @ZurMaD 
This is not a bug as `webview_flutter` is not supported on the web
Closing as duplicate of https://github.com/flutter/flutter/issues/45295

**Closed by TahaTesser** 2021-05-17 10:06 UTC
Labels: in triage

**Comment by ZurMaD** [comment] 2021-05-18 00:35
Thanks
