### ISSUE TITLE
downloading dart sdk each time I run any flutter command  in dev channel

### ISSUE THREAD

**Issue by hussam132** [flutter/flutter#64418] opened 2020-08-23 15:07 UTC
I just download the latest version of flutter sdk and then change the channel to dev 
and then every time i run flutter command  it's gives this

```
C:\Users\husam>flutter
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 81027ab0cc0e7974beee760eb042827a44dd12f3...
```

and above the cmd I see this box

![image](https://user-images.githubusercontent.com/52833102/90981747-0cf30e80-e563-11ea-931a-9331b088c8ae.png)

by the way I'm already have dart sdk in my path

and this will be for long time ?? 
how I can fix this ?

**Comment by hussam132** [comment] 2020-08-23 17:39
first I remove the flutter bin from my path and then restart my pc and then since I have flutter folder that I downloaded before and then I get the same error when when I run flutter commands ?? I want to see that if I delete the flutter folder and then extract it again flutter command works but if I change to the dev channel I get this errors and this's only in the last version that I downloaded few days ago and didn't happened in the my old version

**Comment by hamdikahloun** [comment] 2020-08-23 17:48
@hussam132 
What happens after the Dart SDK download? Flutter command work again or It's downloading loop?

**Comment by mdmohsin7** [comment] 2020-08-24 04:29
> first I remove the flutter bin from my path and then restart my pc and then since I have flutter folder that I downloaded before and then I get the same error when when I run flutter commands ?? I want to see that if I delete the flutter folder and then extract it again flutter command works but if I change to the dev channel I get this errors and this's only in the last version that I downloaded few days ago and didn't happened in the my old version

Make sure you have added flutter\bin to path variable and then restart your pc. Now when you switch to the dev channel, it will start downloading the dart sdk, wait for the process to complete and then restart your pc.
Recently I faced this issue while switching to dev channel, the above process solved my issue.

**Comment by hussam132** [comment] 2020-08-24 09:11
New I can descript the complete issue I delete the flutter folder and extract it again then the flutter commands work fine 
but when I change to any other channel and then running any flutter command it's shows me this first
```
C:\Users\husam>flutter doctor                                                                                           
Checking Dart SDK version...                                                                                            
Downloading Dart SDK from Flutter engine 81027ab0cc0e7974beee760eb042827a44dd12f3...                                    
Unzipping Dart SDK...                                                                                                   
Building flutter tool...
Running pub upgrade...
Downloading package sky_engine...                                   4.5s
Downloading flutter_patched_sdk tools...                           36.4s
Downloading flutter_patched_sdk_product tools...                   32.3s
Downloading windows-x64 tools...                                         126.9s (!)
Downloading windows-x64/font-subset tools...                       10.6s
Downloading android-arm-profile/windows-x64 tools...                4.1s
Downloading android-arm-release/windows-x64 tools...               10.1s
Downloading android-arm64-profile/windows-x64 tools...             10.9s
Downloading android-arm64-release/windows-x64 tools...             13.5s
Downloading android-x64-profile/windows-x64 tools...               12.5s
Downloading android-x64-release/windows-x64 tools...               21.0s
```

and the will shows the command result also if I change the channel again it will check and  download the dart sdk 
I think flutter delete the dart sdk every time i move to other channel or there is issue in the flutter folder because as said its happened every time I change the channel

**Comment by markusaksli-nc** [comment] 2020-08-24 12:24
@hussam132 Do I understand correctly that it only does this once after you change channel and then doesn't do it if you try `flutter doctor` again?

**Comment by hussam132** [comment] 2020-08-24 14:41
@markusaksli-nc yes it's

**Comment by markusaksli-nc** [comment] 2020-08-24 14:50
Closing since this is the expected behavior here. Whenever you change your flutter version the tool will always download the associated Dart SDK version as mentioned by https://github.com/flutter/flutter/issues/64418#issuecomment-678792193. If this only happens once after changing your flutter version then there is no issue.

**Closed by markusaksli-nc** 2020-08-24 14:50 UTC
Labels: in triage
