### ISSUE TITLE
[Windows Desktop] Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

### ISSUE THREAD

**Issue by TerryLiu** [flutter/flutter#94688] opened 2021-12-05 09:01 UTC
The following assertion was thrown during a platform message callback:

```console
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#b2fd8(physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right"), logicalKey: LogicalKeyboardKey#00101(keyId: "0x200000101", keyLabel: "Control Right", debugName: "Control Right"), character: null, timeStamp: 6:51:09.854000, synthesized)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

=============
```
>flutter  doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2020.3)
[√] Connected device (2 available)

• No issues found!

**Comment by Ali-Fadaei** [comment] 2021-12-05 13:54
i have same issue since flutter 2.5 when change virtual desktops

**Comment by iqfareez** [comment] 2021-12-06 08:03
Same. Same issue when accessing clipboard history <kbd>Win</kbd>+<kbd>V</kbd>. Happens on Windows Desktop.

**Comment by maheshmnj** [comment] 2021-12-06 08:48
Hi @TerryLiu, Thanks for filing the issue. There have been several reports of this issue e.g #92538 and #92705 and, I believe this issue is fixed on the latest master. Everyone who is facing a similar issue I would advise you to please try switching to master using 

```
flutter channel master
flutter upgrade
```
and if the issue persists, please write back with the reproducible steps and the updated `flutter doctor -v`.

Thanks.

**Comment by bernaferrari** [comment] 2021-12-16 22:37
I had this:
```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs
flutter: in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure
flutter: that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the
flutter: event: KeyUpEvent#12916(physicalKey: PhysicalKeyboardKey#700e7(usbHidUsage: "0x000700e7", debugName:
flutter: "Meta Right"), logicalKey: LogicalKeyboardKey#00107(keyId: "0x200000107", keyLabel: "Meta Right",
flutter: debugName: "Meta Right"), character: null, timeStamp: 6:17:46.233717, synthesized)
flutter: 'package:flutter/src/services/hardware_keyboard.dart':
flutter: Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
flutter: #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
flutter: #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
flutter: #5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
flutter: #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
flutter: #7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
flutter: #8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:35)
flutter: #9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:374:46)
flutter: #10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
flutter: #14     _invoke2 (dart:ui/hooks.dart:189:10)
flutter: #15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
flutter: #16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
flutter: #17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
flutter: #18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
flutter: #19     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```
on 
```
➜ flutter doctor -v
[✓] Flutter (Channel master, 2.9.0-1.0.pre.116, on macOS 11.4 20F71 darwin-x64,
    locale en-BR)
    • Flutter version 2.9.0-1.0.pre.116 at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f5cc21be2 (3 hours ago), 2021-12-17 03:39:12 +0800
    • Engine revision 86bfc0a921
    • Dart version 2.16.0 (build 2.16.0-116.0.dev)
    • DevTools version 2.9.1
```

**Comment by maheshmnj** [comment] 2021-12-17 03:28
Thanks for reporting @bernaferrari. Are there any known reproducible steps or any specific keypress which reproduces this error?

**Comment by bernaferrari** [comment] 2021-12-17 03:44
Unfortunately, not. I guess it was command+something. I just saw the logs everywhere (more than 20 times) and searched here for the duplicated issue.

**Comment by rymesaint** [comment] 2022-01-01 04:25
sometimes i get this error on emulator ios too

**Comment by maheshmnj** [comment] 2022-01-05 07:33
> Same. Same issue when accessing clipboard history Win+V. Happens on Windows Desktop.

I am unable to reproduce this error when pressing `win + arrow` or `win +v` on windows 10  in a Desktop app on `stable 2.8.1`. If anyone has any further info on How to reproduce this issue I would be happy to check.

Thanks

**Comment by maheshmnj** [comment] 2022-01-18 08:20
I am unable to reproduce this issue, neither there are any reproducible steps However I will leave this issue open for  further tracking purposes specifically for Windows.

**Comment by maheshmnj** [comment] 2022-01-18 08:22
> sometimes i get this error on emulator ios too

@rymesaint, Please follow up on this issue https://github.com/flutter/flutter/issues/96277 (specific to IOS)

**Comment by luisfelipesantofimio** [comment] 2022-01-20 18:18
I faced the same error in Linux. Error: 

A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#485cf(physicalKey: PhysicalKeyboardKey#70014(usbHidUsage: "0x00070014", debugName: "Key Q"), logicalKey: LogicalKeyboardKey#00071(keyId: "0x00000071", keyLabel: "Q", debugName: "Key Q"), character: null, timeStamp: 3:38:55.706000) and the recorded logical key LogicalKeyboardKey#00040(keyId: "0x00000040", keyLabel: "@", debugName: "At")
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'

**What I did:**
I was filling a form built on top of the Form() widget and TextFormField widget. When I press shift for writing a special character, then I select the next field and then, select back the previous field, the entire form is locked, and I'm unable to write some input.

**Comment by gspencergoog** [comment] 2022-01-20 22:42
@luisfelipesantofimio Could you please file a separate issue for the Linux problem, with more details about your Flutter version, repro steps, etc.?

Since this issue doesn't have enough detail to be reproduced, we're going to close it.  Please feel free to reopen if you have specific reproduction steps and flutter version information for Windows. (Desktop Triage)

**Closed by gspencergoog** 2022-01-20 22:42 UTC
Labels: a: text input, framework, platform-windows, a: desktop
