### ISSUE TITLE
Presubmit builds may check out the wrong commit

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#149851] opened 2024-06-06 21:15 UTC
### Type of Request

bug

### Infrastructure Environment

LUCI, Github

### What is happening?

I've seen this happen several times now.

In a given PR, newly added unit tests will pass in presubmit. After the PR is approved and lands, some of those newly added unit tests fail, and the change is reverted.

I've seen this happen on: 
- https://github.com/flutter/flutter/pull/149245
  - https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_2/17525/overview
- https://github.com/flutter/flutter/pull/147171
  - This one in particular did not start to break the tree on its own unit tests until several commits **after** the PR landed
  - https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8745951578924749729/+/u/run_test.dart_for_framework_tests_shard_and_subshard_impeller/stdout
- https://github.com/flutter/flutter/pull/148470
  - https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_canvaskit_tests_7_last/14617/overview

It sounds like @christopherfujino has a lead on why this might be happening: https://github.com/flutter/flutter/pull/149245#issuecomment-2153384690

There were also some golden file failures in postsubmit earlier today that we weren't sure how they were getting in. If the golden file tests did not execute in presubmit, like is suspected above, then this is also the likely cause of the unexpected golden files at head.

### Steps to reproduce

See linked builds above

### Expected results

Tests run in both presubmit and postsubmit, reflecting the same result.

**Comment by Piinks** [comment] 2024-06-06 21:16
Working on getting the failing post submit builds for the others, they were not included in the revert

**Comment by Piinks** [comment] 2024-06-06 21:18
FYI @QuncCccccc and @TahaTesser

**Comment by QuncCccccc** [comment] 2024-06-07 19:25
Just to add another case, this issue happened again in this PR: https://github.com/flutter/flutter/pull/149739

**Comment by eyebrowsoffire** [comment] 2024-06-07 19:37
I filed a duplicate for https://github.com/flutter/flutter/pull/149739 and it has some specific info about the failure there that might be helpful: https://github.com/flutter/flutter/issues/149928

**Comment by eyebrowsoffire** [comment] 2024-06-07 19:41
Also, it appears that it checked out the wrong commit *only on the rerun*. The original presubmit run for that builder actually did check out the wrong commit and failed: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests_0/67329/infra

**Comment by christopherfujino** [comment] 2024-06-07 19:50
For the PR: https://github.com/flutter/flutter/pull/149245

We scheduled the try build (which started at June 6 01:15AM PDT): https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests_2/67064/infra

Which, in step 3.4 appeared to check out commit [4608a8913767116234e95cb7d73a410e9a7a2fc9](https://github.com/flutter/flutter/commit/4608a8913767116234e95cb7d73a410e9a7a2fc9), which was merged to master on June 5, 11:11PM PDT.

**Comment by christopherfujino** [comment] 2024-06-07 19:54
> For the PR: #149245
> 
> We scheduled the try build (which started at June 6 01:15AM PDT): https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests_2/67064/infra
> 
> Which, in step 3.4 appeared to check out commit [4608a8913767116234e95cb7d73a410e9a7a2fc9](https://github.com/flutter/flutter/commit/4608a8913767116234e95cb7d73a410e9a7a2fc9), which was merged to master on June 5, 11:11PM PDT.

I also see in the input properties: `"git_branch": "master"`: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests_2/67064/infra. I'm thinking maybe the bug is in the input properties Cocoon is scheduling these builds with?

**Comment by christopherfujino** [comment] 2024-06-07 19:56
Actually, comparing it with this failed try build: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests_2/67193/infra, it has a `"git_ref": "refs/pull/143249/head"` field, so I think the fact that our mistaken build is missing that field is why we checked out the wrong commit.

**Comment by christopherfujino** [comment] 2024-06-07 22:07
It looks like Cocoon populates this when generating its BuildBucket RPC request [here](https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/luci_build_service.dart#L763-L773)

**Comment by christopherfujino** [comment] 2024-06-07 22:48
> Also, it appears that it checked out the wrong commit _only on the rerun_. The original presubmit run for that builder actually did check out the correct commit and failed (as expected): https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests_0/67329/infra

Ahh, I wonder if re-runs go down a different codepath...

**Comment by christopherfujino** [comment] 2024-06-07 22:51
Although, it looks like when Cocoon receives the request from a GitHub check-run to retry a build, we call the same function (which should populate properties.git_ref): https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/luci_build_service.dart#L485

**Comment by christopherfujino** [comment] 2024-06-08 00:10
I see this in the cocoon logs:

```
> INFO 2024-06-06T08:14:56.219Z

Making bbv2 request with path: https://cr-buildbucket.appspot.com/prpc/buildbucket.v2.Builds/ScheduleBuild and body:

{
  "builder": {
    "project": "flutter",
    "bucket": "try",
    "builder": "Linux web_tests_2"
  },
  "properties": {},
  "tags": [
    {
      "key": "buildset",
      "value": "pr/git/149245"
    },
    {
      "key": "buildset",
      "value": "sha/git/49f9a3b3ce6fa06b7c7fd6f91de7533d132cacf1"
    },
    {
      "key": "cipd_version",
      "value": "refs/heads/main"
    },
    {
      "key": "github_checkrun",
      "value": "25879982459"
    },
    {
      "key": "github_link",
      "value": "https://github.com/flutter/flutter/pull/149245"
    },
    {
      "key": "user_agent",
      "value": "flutter-cocoon"
    },
    {
      "key": "current_attempt",
      "value": "2"
    }
  ],
  "notify": {
    "pubsubTopic": "projects/flutter-dashboard/topics/build-bucket-presubmit",
    "userData": "ZXlKaWRXbHNaR1Z5WDI1aGJXVWlPaUpNYVc1MWVDQjNaV0pmZEdWemRITmZNaUlzSW1Ob1pXTnJYM0oxYmw5cFpDSTZNalU0TnprNU9ESTBOVGtzSW1OdmJXMXBkRjl6YUdFaU9pSTBPV1k1WVROaU0yTmxObVpoTURaaU4yTTNabVEyWmpreFpHVTNOVE16WkRFek1tTmhZMll4SWl3aVkyOXRiV2wwWDJKeVlXNWphQ0k2SW0xaGMzUmxjaUlzSW5KbGNHOWZiM2R1WlhJaU9pSm1iSFYwZEdWeUlpd2ljbVZ3YjE5dVlXMWxJam9pWm14MWRIUmxjaUlzSW5WelpYSmZZV2RsYm5RaU9pSm1iSFYwZEdWeUxXTnZZMjl2YmlKOQ=="
  }
}

> INFO 2024-06-06T08:14:56.725Z bbv2 request returned response code 200
```

**Comment by christopherfujino** [comment] 2024-06-08 00:37
Meanwhile, from the LUCI milo [log](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests_2/67064/infra) of the actual scheduled build, these were the input properties:

```
{
  "$flutter/goma": {
    "server": "rbe-prod1.endpoints.fuchsia-infra-goma-prod.cloud.goog"
  },
  "$flutter/rbe": {
    "instance": "projects/flutter-rbe-prod/instances/default",
    "platform": "container-image=docker://gcr.io/cloud-marketplace/google/debian11@sha256:69e2789c9f3d28c6a0f13b25062c240ee7772be1f5e6d41bb4680b63eae6b304"
  },
  "$kitchen": {
    "emulate_gce": true
  },
  "$recipe_engine/isolated": {
    "server": "https://isolateserver.appspot.com"
  },
  "$recipe_engine/swarming": {
    "server": "https://chromium-swarm.appspot.com"
  },
  "bringup": false,
  "clobber": false,
  "cores": 8,
  "dependencies": [
    {
      "dependency": "android_sdk",
      "version": "version:34v3"
    },
    {
      "dependency": "chrome_and_driver",
      "version": "version:119.0.6045.9"
    },
    {
      "dependency": "goldctl",
      "version": "git_revision:720a542f6fe4f92922c3b8f0fdcc4d2ac6bb83cd"
    },
    {
      "dependency": "curl",
      "version": "version:7.64.0"
    }
  ],
  "device_type": "none",
  "git_branch": "master",
  "git_repo": "flutter",
  "gold_tryjob": true,
  "goma_jobs": "200",
  "mastername": "client.flutter",
  "os": "Ubuntu",
  "presubmit_max_attempts": 2,
  "rbe_jobs": "200",
  "recipe": "flutter/flutter_drone",
  "shard": "web_tests",
  "subshard": 2,
  "tags": [
    "framework",
    "hostonly",
    "shard",
    "linux"
  ],
  "upload_packages": false,
  "use_cas": true
}
```

**Comment by reidbaker** [comment] 2024-06-10 14:13
After you get the root cause fixed consider failing a run if "git_branch" is not set.

**Comment by christopherfujino** [comment] 2024-06-10 19:59
> After you get the root cause fixed consider failing a run if "git_branch" is not set.

I will consider it, although the constraints are quite complex

**Comment by christopherfujino** [comment] 2024-06-11 18:16
Jason merged https://github.com/flutter/cocoon/pull/3777 which we believe will fix this. However, it has not been deployed yet. Looking into making a manual deploy.

**Comment by christopherfujino** [comment] 2024-06-11 19:54
> Would this bug cause reverts merged into master to not appear on the build dashboard?

No, I don't believe so. I'm guessing you're observing that @yaakovschectman?

**Comment by yaakovschectman** [comment] 2024-06-11 19:57
@christopherfujino Yes. You can see on the commit history - https://github.com/flutter/flutter/commits/master/ - that a revert landed 4 hours before this comment, but the build dashboard does not go beyond https://github.com/flutter/flutter/commit/aad70e5cdb8e8cdba025cb10f496bc2f170131a3, which the most recent (as of now) commit reverted

**Comment by christopherfujino** [comment] 2024-06-11 19:59
> @christopherfujino Yes. You can see on the commit history - https://github.com/flutter/flutter/commits/master/ - that a revert landed 4 hours before this comment, but the build dashboard does not go beyond [aad70e5](https://github.com/flutter/flutter/commit/aad70e5cdb8e8cdba025cb10f496bc2f170131a3), which the most recent (as of now) commit reverted

Can you file a new issue for that?

**Comment by christopherfujino** [comment] 2024-06-11 20:35
Per my testing on https://github.com/flutter/flutter/pull/150061, I believe this is fixed. Please ping me ASAP if you observe a presubmit build running a commit from the master branch.

**Closed by christopherfujino** 2024-06-11 20:35 UTC
Labels: team-infra, P0, triaged-infra
