### ISSUE TITLE
[integration_test] `reverFlutterImage` does not exist

### ISSUE THREAD

**Issue by caseycrogers** [flutter/flutter#97921] opened 2022-02-06 23:31 UTC
The integration bindings tells you to call `reverFlutterImage`, but `reverFlutterImage` does not exist.

It should either be added or, if the documentation is absolute, the line telling you to call it should be removed.
See: https://github.com/flutter/flutter/blob/ba01ec8faae9a9be3cd90ee2b7357a803b7a7178/packages/integration_test/lib/integration_test.dart#L201

**Comment by darshankawar** [comment] 2022-02-07 10:55
Closing this as duplicate of https://github.com/flutter/flutter/issues/92381

**Closed by darshankawar** 2022-02-07 10:55 UTC
Labels: in triage
