### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5356 pos 14

### ISSUE THREAD

**Issue by thisistorsten** [flutter/flutter#103133] opened 2022-05-05 14:46 UTC
<details>
<summary> log </summary>

```

The relevant error-causing widget was: 
  ScreenUtilInit ScreenUtilInit:file:///Users/admin/Desktop/testapp/lib/main.dart:22:16
When the exception was thrown, this was the stack: 
#2      InheritedElement.notifyClients (package:flutter/src/widgets/framework.dart:5356:14)
#3      ProxyElement.updated (package:flutter/src/widgets/framework.dart:5118:5)
#4      InheritedElement.updated (package:flutter/src/widgets/framework.dart:5338:13)
#5      ProxyElement.update (package:flutter/src/widgets/framework.dart:5106:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#19     _invoke (dart:ui/hooks.dart:151:10)
#20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#21     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
Application finished.

```

</details>

Code:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: Size(460,790),
      builder: (context) => MultiProvider(
          providers: [
            ChangeNotifierProvider(create: (context) => TestApp()),
            ChangeNotifierProvider(create: (context) => PageControllerProvider()),
            ChangeNotifierProvider(create: (context) => RequestProvider()),
            ChangeNotifierProvider(create: (context) => HistoryProvider()),
            ChangeNotifierProvider(create: (context) => ThemeProvider()),
          ],
          child: App()
      ),
    );
  }
}
```

**Comment by thisistorsten** [comment] 2022-05-05 14:50
![hKWEF](https://user-images.githubusercontent.com/79338345/166950474-b7002243-f4d3-4631-ab93-a51d56d6deef.jpg)

**Comment by darshankawar** [comment] 2022-05-06 06:19
@thisistorsten 
From the code sample you shared, you seem to be using third party plugin code. In order to verify this issue properly, we'll need complete minimal reproducible code sample without third party plugin code.

Also, the red screen error you showed seems to be similar to https://github.com/flutter/flutter/issues/102803, so I suggest you to follow-up in that issue for further updates, or provide the code sample requested in that issue for better tracking.

Closing this as a duplicate.

**Closed by darshankawar** 2022-05-06 06:19 UTC
Labels: in triage

**Comment by pranavo72bex** [comment] 2022-05-07 12:51
I am also using screen utils packages. one of my team members getting the same error. may it is due to the screen utils package
