### ISSUE TITLE
webview_flutter package still lacks <input type="file"> selection menu feature

### ISSUE THREAD

**Issue by verisay** [flutter/flutter#48672] opened 2020-01-12 12:02 UTC
Yes there is another thread [https://github.com/flutter/flutter/issues/27924](url) about this.
& Yes nobody cares about this (it seems)

Why such a crucial feauture is missing?

Why is nobody eligible answering this? 

Current status:
When you tap on a "file upload" button in webview it gives this on android amulator Sdk29
`E/InputMethodManager( 7077): b/117267690: Failed to get fallback IMM with expected displayId=4 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{ef64f93 VFEDHVC.. .F...... 0,0-1080,1808}`

Tested on several different emulators and real devices some show different logs some show nothing.

**Comment by jonahwilliams** [comment] 2020-01-12 23:33
Please do not knowingly open duplicate issues .

Duplicate of https://github.com/flutter/flutter/issues/27924

**Closed by jonahwilliams** 2020-01-12 23:33 UTC
