### ISSUE TITLE
[snap] Stable channel installs Dart 3 version for arm64

### ISSUE THREAD

**Issue by ernesto-elsaesser** [flutter/flutter#117265] opened 2022-12-17 14:38 UTC
I just installed Flutter via snap on an ARM64 Linux machine:
>sudo snap install flutter --classic

This installed **Flutter 3.7.0-10.0.pre.34**, which seems to ship with **Dart 3.0.0-35.0.dev** - which from what I can tell is neither released, nor supported yet. At least some dependencies of my app don't build with Dart 3. Is this intended?

>snap info flutter

```
name:      flutter
summary:   Flutter SDK
publisher: Flutter Team✓
store-url: https://snapcraft.io/flutter
contact:   https://github.com/flutter/flutter/issues
license:   unset
description: |
  Flutter is Google’s UI toolkit for building beautiful, natively compiled
  applications for mobile, web, and desktop from a single codebase.
commands:
  - flutter.dart
  - flutter
  - flutter.openurl
snap-id:      YO0Adf4fqgxL7i3SaCn00oxEfd5CNQ63
tracking:     latest/stable
refresh-date: today at 12:54 UTC
channels:
  latest/stable:    0+git.6e68597 2022-05-20 (124) 175MB classic
  latest/candidate: ↑                                    
  latest/beta:      ↑                                    
  latest/edge:      0+git.6e68597 2022-05-13 (124) 175MB classic
installed:          0+git.6e68597            (124) 175MB classic
```

>flutter --version

```
Flutter 3.7.0-10.0.pre.34 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 7b850ef375 (2 hours ago) • 2022-12-17 07:05:35 -0500
Engine • revision f74dd53318
Tools • Dart 3.0.0 (build 3.0.0-35.0.dev) • DevTools 2.20.0
```
>dart --version

`Dart SDK version: 3.0.0-35.0.dev (dev) (Thu Dec 15 18:25:10 2022 -0800) on "linux_arm64"`

>uname -a

`Linux vm1 5.11.0-1022-oracle #23~20.04.1-Ubuntu SMP Fri Nov 12 15:45:47 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

(Note that I already solved this by directly cloning the git repo at tag 3.3.10, only wanted to report this issue. Also sorry for the messed up title, accidentally hit Enter while still typing.)

**Comment by darshankawar** [comment] 2022-12-19 06:29
Thanks for the report @ernesto-elsaesser 

> I just installed Flutter via snap on an ARM64 Linux machine:

`snap` is a third party package, so I think you will need to report this in snap's dedicated repo.



> Note that I already solved this by directly cloning the git repo at tag 3.3.10,

This indicates that the issue isn't when you directly clone the sdk without snap, so this issue doesn't seem to be flutter sdk's issue, but with snap.

Closing this based on above. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-12-19 06:29 UTC
Labels: in triage

**Comment by ernesto-elsaesser** [comment] 2022-12-19 08:27
Oh, I didn‘t realize there is a dedicated repo for the snap, sorry. I will report the issue on
https://github.com/canonical/flutter-snap

But while it‘s true that this isn‘t an issue with the SDK itself, snap still is the recommended installation method in the official docs, so dismissing it as a third party issue doesn‘t seem quite right … (https://docs.flutter.dev/get-started/install/linux#install-flutter-using-snapd)
