### ISSUE TITLE
Rich Editor for Flutter

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#119262] opened 2023-01-26 18:39 UTC
Hi all!
Now that Flutter supports desktop and web it is even more important that it incorporates a rich text editor with support for images, tables, text styles, colors, printing, saving to a special file, exporting to HTML, exporting to PDF, ....

The rich editors that exist for Flutter are not maintained, nor are they for all environments supported by Flutter, and they are very buggy.

If you want Flutter to really compete with other languages for desktop application development, it is essential that you have a widget with rich text support developed by the Flutter developer team.

Thanks!!

**Comment by stuartmorgan** [comment] 2023-01-26 20:14
Duplicate of https://github.com/flutter/flutter/issues/12675

**Closed by stuartmorgan** 2023-01-26 20:14 UTC
