### ISSUE TITLE
`flutter analyze` ends with exit code 1 on info (like TODO)

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#20855] opened 2018-08-21 06:19 UTC
This breaks my CI

```
   flutter analyze --no-pub
    Analyzing lookatmybaby_flutter...
  
       info • TODO(zoechi) implement uploadImage • lib/src/server_api_firebase/backoffice/image_reference_editor_dao.dart:236:8 • todo

       ...

       info • TODO(zoechi) ... • test/widgets/tabs/resources/title_image/title_image_test.dart:172:4 • todo
       info • TODO(zoechi) check the invitation was persisted and the mail was sent • test_driver/invitation.dart:51:8 • todo
       info • TODO(zoechi) see https://github.com/flutter/flutter/pull/14061/files#diff-8016791f5e3236521bb34819cbde9c1d for some additional inspiration • tool/grind.dart:33:4 • todo
  
    72 issues found. (ran in 17.8s)
  
  failed with exit code 1
```  

```
[✓] Flutter (Channel master, v0.6.1-pre.47, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.6.1-pre.47 at /Users/zoechi/flutter/flutter
    • Framework revision c123312c21 (2 hours ago), 2018-08-20 23:59:37 -0400
    • Engine revision 4e845be0b1
    • Dart version 2.1.0-dev.1.0.flutter-69fce633b7

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Pixel XL • HT69V0203649 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by zoechi** [comment] 2018-08-29 06:30
This seems to be fixed.

**Comment by zoechi** [comment] 2018-09-08 13:39
@dotdoom what Dart version?

**Comment by dotdoom** [comment] 2018-09-08 13:53
channel Beta:

```
[✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_US.UTF-8)
    • Flutter version 0.7.3 at /home/asheremet/pkg/flutter
    • Framework revision 3b309bda07 (11 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282
```

and channel Dev:

```
[✓] Flutter (Channel dev, v0.8.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.8.1 at /home/asheremet/pkg/flutter
    • Framework revision 0235ec59d1 (35 hours ago), 2018-09-06 20:23:13 -0700
    • Engine revision 9b297b3b51
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2
```

**Comment by zoechi** [comment] 2018-09-08 13:57
You think this is related to `exclude`? I had excludes in a while ago but removed it because it didn't work and replaced it by different workarounds.

**Comment by dotdoom** [comment] 2018-09-08 14:07
I actually created this file for excludes (`messages_$locale.dart` files autogenerated by `intl` were triggering `unnecessary_brace_in_string_interps`), so haven't tried without them.

But even with a completely empty `analysis_options.yaml` (0 bytes size), the outcome is the same.

**Comment by zoechi** [comment] 2018-09-08 16:04
Ok, I'll leave it open, but it's not happening for me anymore.

**Comment by tvolkert** [comment] 2018-09-10 18:37
@devoncarew sounds like it could be related to your recent work in the restructuring of `analysis_options.yaml`

**Comment by devoncarew** [comment] 2018-09-10 19:32
Possibly? It looks like for the `--watch` case we filter all `todo`s:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze_continuously.dart#L158

But I don't see any filtering logic for the single shot (`analyze_once.dart`) case.

**Comment by DagobertDokate** [comment] 2019-03-12 07:05
Is there a way that the build does not fail with an information?

**Comment by cubuspl42** [comment] 2019-04-19 14:24
It happens to me  too!
Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D42, locale en-PL)

**Comment by cubuspl42** [comment] 2019-04-19 15:03
Workaround:
https://gist.github.com/cubuspl42/ad277079f2cbc3c0bddb10f63ba1a3d2

**Comment by dotdoom** [comment] 2019-04-19 15:11
FWIW, I've added this to my `analysis_options.yaml`:

```yaml
analyzer:
  errors:
    # 'flutter analyze' exits with 1 even on 'info':
    # https://github.com/flutter/flutter/issues/20855
    todo: ignore

...
```

**Comment by doc-rj-celltrak** [comment] 2019-10-29 21:29
@dotdoom I guess that would ignore todo warnings, but not other "info" level warnings. This breaks my CI too, hope it's being worked.

**Comment by TahaTesser** [comment] 2020-05-28 07:35
Issue reproduces on latest `master`

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.173, on Mac OS X 10.15.5 19F96,
    locale en-GB)
    • Flutter version 1.19.0-2.0.pre.173 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 5663e02645 (9 hours ago), 2020-05-27 18:32:01 -0400
    • Engine revision 2663be8370
    • Dart version 2.9.0 (build 2.9.0-11.0.dev e007545c42)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F96
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.61

• No issues found!
``` 

</details>

**Comment by rafekun** [comment] 2021-02-26 11:25
any update?
I have same issue on Github Actions

**Comment by tbm98** [comment] 2021-02-26 14:31
I see some flag for disabling fatal if info/warning by `--fatal-infos` and `--fatal-warnings` on master branch

**Comment by tbm98** [comment] 2021-03-07 15:28
this issue should be close because flutter 2.0 is out :D

**Comment by rafekun** [comment] 2021-03-08 07:25
This feature seems not to have been landed on stable channel.

**Comment by gspencergoog** [comment] 2021-03-08 17:14
Actually, both `--no-fatal-infos` and `--no-fatal-warnings` exist in the stable channel. Closing.

**Closed by gspencergoog** 2021-03-08 17:14 UTC
Labels: P4, severe: new feature, tool
