### ISSUE TITLE
[Android] TextField & TextFormField External keyboard number pad enter key is not trigger onSubmitted & onFieldSubmitted

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#152181] opened 2024-07-23 18:30 UTC
### Steps to reproduce

1. Connect wireless keyboard with number pad
2. Focus TextField or TextFormField
3. Press Enter key in the Number pad

```
`class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(
                onSubmitted: (value) {
                  ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                      content: Text('TextField onSubmitted called')));
                },
              ),
              TextFormField(
                onFieldSubmitted: (value) {
                  ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                      content: Text('TextFormField onFieldSubmitted called')));
                },
              )
            ],
          ),
        ));
  }
}`

```
### Actual results

Did not show snackbar bcoz onSubmitted or onFieldSubmitted did not trigger

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by selvam920** [comment] 2024-07-23 18:34
i tested with google keep notes app, the number keypad enter key is working in the same mobile.

**Comment by selvam920** [comment] 2024-07-23 18:37
![image](https://github.com/user-attachments/assets/7fe2b539-0ddc-402f-b7cc-308961fbe3cd)

**Comment by selvam920** [comment] 2024-07-23 18:38
This issue only with number pad enter key, the backspace under enter key is working fine.

**Comment by darshankawar** [comment] 2024-07-24 08:58
@selvam920 
I tried using latest stable and running the code on pixel emulator, connected wireless keyboard and the snackbar is shown properly indicating the methods are being called as exepected.


https://github.com/user-attachments/assets/5468d9a6-26a4-4d73-ac07-4e63970a4337

You should try on latest beta / master or stable.

**Comment by selvam920** [comment] 2024-07-24 09:23
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources

checked with stable version, still issue exist.
please check with real phone & keyboard

**Comment by selvam920** [comment] 2024-07-24 09:36
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.24.0-1.0.pre.247, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources

In master branch also having same issue

**Comment by darshankawar** [comment] 2024-07-24 12:40
> please check with real phone & keyboard

I used real hardware keyboard (magic keyboard) running on mac. Also verified on Android Samsung S10+ device in which I get expected behavior as below:

 

https://github.com/user-attachments/assets/51af8046-420d-45d3-b1e9-c257b4d1f955

**Comment by selvam920** [comment] 2024-07-24 12:43
Can you check with Logitech wireless keyboard?

Is your magic keyboard has number keypad?

**Comment by darshankawar** [comment] 2024-07-25 06:44
> Is your magic keyboard has number keypad?

Yes.


> Can you check with Logitech wireless keyboard?

We don't have this keyboard, but checked with another generic keyboard with which it works as expected. Can you check if it only occurs on Android or on desktop and web as well ?

**Comment by selvam920** [comment] 2024-07-25 06:54
This issue only with android platform
I think you can check with any keyboard(wired or wireless) with number pad on right side

**Comment by selvam920** [comment] 2024-07-25 09:23
What is model of the dell wireless keyboard?

**Comment by selvam920** [comment] 2024-07-25 09:32
did you check Enter Key in the right side below plus button?

**Comment by bleroux** [comment] 2024-07-25 09:55
> did you check Enter Key in the right side below plus button?

Yes.
Can you check with another keyboard?

**Comment by selvam920** [comment] 2024-07-25 10:02
tested with 
1. Portronics POR 2207 Bluetooth Multi-device Keyboard 
2. logitech k270 wireless keyboard
It's not working

**Comment by darshankawar** [comment] 2024-07-25 12:06
Is there any short-cut key or any macro configured with these keyboards which could be conflicting with the `enter` key ?
Maybe it could be a fault with those keyboards itself ? See https://www.reddit.com/r/LogitechG/comments/ln3x2i/logitech_g910_enter_key_not_working_properly/

**Comment by selvam920** [comment] 2024-07-25 12:09
The same numpad enter key is working with other app.
Also when I press enter the focus lost from the textbox but did not the onSubmitted call

**Comment by darshankawar** [comment] 2024-07-25 12:22
Closing as duplicate of https://github.com/flutter/flutter/issues/147138.
Not sure why you closed that issue and filed this. I will reopen it, as it was already triaged and prioritized.

**Closed by darshankawar** 2024-07-25 12:22 UTC
Labels: in triage
