### ISSUE TITLE
Regression in average_frame_rasterizer_time_millis  mac_android_imagefiltered_transform_animation_perf__timeline_summary

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#79556] opened 2021-04-01 15:26 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1616720329&end=1617270843&keys=X16d58f4952fb3a99f57c42ade1611418&requestType=0&xbaroffset=23345

Starts at https://github.com/flutter/flutter/pull/79167 and does not drop to baseline, although previous benchmark runs had hit this peak. Maybe a device issue in the lab? I don't think the commit here would cause this.

/cc @flar, this week's engine sheriff.

The commit in question is one from @jonahwilliams if he wants to comment on my hypothesis that it's not actually that commit. Feel free to remove the `tool` label if I'm correct.

**Comment by kf6gpe** [comment] 2021-04-01 15:27
Also seen on other benchmarks at https://flutter-flutter-perf.skia.org/e/?begin=1616715843&end=1617270843&keys=X1ac9e25bb824cb5d3f915c8434fa33ad&requestType=0&xbaroffset=23342, which is another benchmark formerly bimodal.

**Comment by zanderso** [comment] 2021-04-01 15:31
Do these benchmarks use the gallery? There was a gallery roll in the commit before #79167 at https://github.com/flutter/flutter/commit/4d54b8966a0f2244a2d4416c0d728f903fc82f40

**Comment by jason-simmons** [comment] 2021-04-01 16:45
No - this benchmark is built from https://github.com/flutter/flutter/tree/master/dev/benchmarks/macrobenchmarks

**Comment by jonahwilliams** [comment] 2021-04-01 16:47
I don't see any reasonable way the tooling change could have triggered it (of course, there are always some unreasonable ways...)

Since this is an android test it would also be unrelated to the iOS version update

**Comment by jason-simmons** [comment] 2021-04-01 19:26
Bisected this to https://github.com/google/skia/commit/de3cb0b454e8ab79967bfd21d48443c2538d3c7d

@bsalomon

**Comment by bsalomon** [comment] 2021-04-01 20:45
This is not entirely unexpected. The change is an expansion of a driver bug workaround. It will only affect Adreno 4xx devices and very old/rare Tegra2/3 devices. It's possible we could claw this performance back in the future, but it will take some significant refactoring in our texture allocation to make that possible.

**Comment by chinmaygarde** [comment] 2021-04-05 17:37
@bsalomon Would it be possible to devise an issue in the Skia bug tracker that details the work needed to claw back this performance? The current regression makes the frame time get very close to the frame interval on this device. Earlier, this was well within budget.

**Comment by bsalomon** [comment] 2021-04-05 18:51
Sure thing. filed skbug.com/11833 for the longer term fix and skbug,com/11834 to see if we can narrow the set of affected devices in the shorter term.

**Comment by bsalomon** [comment] 2021-04-06 14:57
skbug.com/11834 is now fixed, which limits the workaround by driver version. If the test device has been upgraded from Marshmallow (shipped OS) to Nougat (latest available update) it should see the performance go back to the previous level.

**Comment by bsalomon** [comment] 2021-04-12 13:21
The bot must be running Android N because the performance has recovered.

**Comment by chinmaygarde** [comment] 2021-04-12 17:31
So it has
![Screen Shot 2021-04-12 at 10 31 04 AM](https://user-images.githubusercontent.com/44085/114436514-42904a80-9b7a-11eb-8d6e-fa0784a3dee1.png)

**Closed by chinmaygarde** 2021-04-12 17:31 UTC
Labels: P0, dependency: skia, engine, perf: speed, severe: performance, severe: regression, team: benchmark, team: bimodal benchmark
