### ISSUE TITLE
platform.PlatformViewsController.checkInputConnectionProxy  on a null object reference

### ISSUE THREAD

**Issue by yuchuan08** [flutter/flutter#36517] opened 2019-07-19 06:00 UTC
## Logs

07-19 10:32:30.457 30395 30395 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
--
407-19 10:32:30.457 30395 30395 E AndroidRuntime: at io.flutter.plugin.platform.PlatformViewsController.checkInputConnectionProxy(PlatformViewsController.java:336)
507-19 10:32:30.457 30395 30395 E AndroidRuntime: at io.flutter.view.FlutterView.checkInputConnectionProxy(FlutterView.java:402)
607-19 10:32:30.457 30395 30395 E AndroidRuntime: at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1300)
707-19 10:32:30.457 30395 30395 E AndroidRuntime: at android.view.inputmethod.InputMethodManager.onAmigoPostWindowFocus(InputMethodManager.java:1793)
807-19 10:32:30.457 30395 30395 E AndroidRuntime: at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3777)
907-19 10:32:30.457 30395 30395 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
1007-19 10:32:30.457 30395 30395 E AndroidRuntime: at android.os.Looper.loop(Looper.java:154)
1107-19 10:32:30.457 30395 30395 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6177)
1207-19 10:32:30.457 30395 30395 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
1307-19 10:32:30.457 30395 30395 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
1407-19 10:32:30.457 30395 30395 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.7.8, on Microsoft Windows [Version 10.0.17763.615], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
[√] Android Studio (version 3.4)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by loumzy** [comment] 2019-08-27 10:11
same problem

**Comment by loumzy** [comment] 2019-08-28 11:40
## this is bug in  io.flutter.plugin.platform.PlatformViewsController

```
    public boolean checkInputConnectionProxy(View view) {
        if (!this.contextToPlatformView.containsKey(view.getContext())) {
            return false;
        } else {
            View platformView = (View)this.contextToPlatformView.get(view.getContext());
            return platformView == view ? true : platformView.checkInputConnectionProxy(view);
        }
    }

```

**Comment by CoderNeilz** [comment] 2019-09-05 07:12
always happened in 金立 phone

**Comment by loumzy** [comment] 2019-09-12 02:35
@zanderso hope to review this problem

**Comment by RootKatherine** [comment] 2019-09-12 06:14
There are temporary solutions？

**Comment by loumzy** [comment] 2019-09-16 06:11
@RootKatherine 
you can use v1.5.4-hotfix.2 temporary

**Comment by MrLittleStrong** [comment] 2019-10-16 02:51
Same crash. Any progress now?

**Comment by 1242128273wangpeng** [comment] 2019-10-29 03:41
try this solution

//define custom flutterview
class MyFlutterView(context: Context?) : FlutterView(context) {
    override fun checkInputConnectionProxy(view: View?): Boolean {
        if(view == null){
            return false
        }
        return super.checkInputConnectionProxy(view)
    }
}

    override fun createFlutterView(context: Context?): FlutterView {
        flutterView = MyFlutterView(context)
        flutterView?.layoutParams = WindowManager.LayoutParams(-1, -1)
        setContentView(flutterView)
        addLaunchView()
        return flutterView!!
    }

    private fun addLaunchView() {
        if (launchView == null) {
            launchView = createLaunchView()
            addContentView(launchView, FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT))
            flutterView?.addFirstFrameListener(object : FlutterView.FirstFrameListener {
                override fun onFirstFrame() {
                    launchView?.animate()?.alpha(0.0f)?.setListener(object : AnimatorListenerAdapter() {
                        override fun onAnimationEnd(animation: Animator?) {
                            (launchView?.parent as? ViewGroup)?.removeView(launchView)
                        }
                    })
                    launchView = null
                    flutterView?.removeFirstFrameListener(this)
                }
            })
        }
    }

    private fun createLaunchView(): FrameLayout {
        val view = FrameLayout(this)
        val viewParams = FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT)
        val imageView = ImageView(this)
        imageView.setImageDrawable(resources.getDrawable(R.drawable.launch_background))
        view.addView(imageView, viewParams)
        view.setBackgroundColor(Color.WHITE)
        return view
    }

**Comment by trustedcoder** [comment] 2019-11-26 21:23
Am having the same problem while integrating with flutter_facebook_login

**Comment by trustedcoder** [comment] 2019-11-27 05:41
After so much battle, I downgraded the flutter SDK and the error was no more.
I think the latest SDK version caused this.

**Comment by Erenyang** [comment] 2019-12-19 07:33
Same crash. How to resolve it？

**Comment by trustedcoder** [comment] 2020-02-27 06:24
This error seems to occur in some android phones but not all. The latest flutter SDK was still not able to resolve this. My App keeps crashing. Please if someone has a temporary solution to this that will still involve me making use of the latest SDK, I will appreciate it if you can share.

Thanks

**Comment by qylshy** [comment] 2020-03-25 13:18
I met this problem also

**Comment by zhancheng** [comment] 2020-04-16 07:03
same issue!

**Comment by mayurdhurpate** [comment] 2020-04-30 08:56
Seems to be related to the reproducible #54710, faced on specific Gionee models (could be more). Faced especially during calling Method channels in Android for Intent, Payments triggering, Custom Sign In. 
@chiu14578 @TahaTesser @zoechi

**Comment by ikkyu0319** [comment] 2020-08-01 16:07
same issue!

**Comment by pengrad** [comment] 2020-08-18 07:28
same issue!
only happens on Gionee M7 Power phone

**Comment by pengrad** [comment] 2020-08-19 05:52
I've submitted PR with fix https://github.com/flutter/engine/pull/20622
@TahaTesser @chinmaygarde please help to review 🙏

**Comment by Aadiyaara** [comment] 2020-10-14 07:04
Can someone guide me on how to check with which flutter version is this functionality actually added?

**Comment by TahaTesser** [comment] 2020-10-14 11:52
Hi @yuchuan08  @pengrad 
Is this issue resolved with the PR  https://github.com/flutter/engine/pull/20622

If you're still experiencing this issue, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2020-11-04 12:46
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-04 12:46 UTC
Labels: P4, customer: crowd, engine, platform-android, severe: crash
