### ISSUE TITLE
PageView Cannot Scroll to Last Page

### ISSUE THREAD

**Issue by pennzht** [flutter/flutter#45339] opened 2019-11-21 11:58 UTC
## Steps to Reproduce

1. Start a new flutter app.
2. Use the following code as `lib/main.dart`.
3. Run the app.
4. You cannot scroll page 4 (the green page). It always bounces back to page 3 (the yellow page).

`git bisect` shows that this issue appeared after the commit `851d6996e7cedf767de7464e02a21e493a6f18e5` 'Revert "Implement PageView using SliverLayoutBuilder, Deprecate RenderSliverFillViewport (#37024)" (#44778)'

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  PageController _controller = PageController(
    initialPage: 0,
    viewportFraction: 0.5,
  );

  Widget build(BuildContext context) {
    return PageView(
      controller: _controller,
      children: [
        Container(
          color: Colors.blue,
          child: Text(
            '1',
            style: TextStyle(
              color: Colors.white,
              fontSize: 100,
            ),
          ),
        ),
        Container(
          color: Colors.red,
          child: Text(
            '2',
            style: TextStyle(
              color: Colors.white,
              fontSize: 100,
            ),
          ),
        ),
        Container(
          color: Colors.yellow,
          child: Text(
            '3',
            style: TextStyle(
              color: Colors.white,
              fontSize: 100,
            ),
          ),
        ),
        Container(
          color: Colors.green,
          child: Text(
            '4',
            style: TextStyle(
              color: Colors.white,
              fontSize: 100,
            ),
          ),
        ),
      ],
    );
  }
}
```

**Target Platform:** Web, Tablet, Mobile
**Target OS version/browser:** Chrome 78.0.3904.97, iOS 12.4
**Devices:** Both physical devices and simulator

## Logs

```
[  +31 ms] executing: [/Users/tianguang/Documents/f/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +39 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] <<<information removed>>>
[        ] executing: [/Users/tianguang/Documents/f/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +34 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.5-15-g43a8a1902
[  +10 ms] executing: [/Users/tianguang/Documents/f/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/tianguang/Documents/f/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:pennzht/flutter.git
[  +64 ms] executing: [/Users/tianguang/Documents/f/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +7 ms] executing: sw_vers -productName
[  +19 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +19 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G95
[  +34 ms] executing: /usr/bin/xcode-select --print-path
[  +13 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +126 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 10.3
           Build version 10G8
[  +70 ms] executing: /Users/tianguang/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /Users/tianguang/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +17 ms] executing: /Users/tianguang/Documents/f/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +56 ms] /usr/bin/xcrun simctl list --json devices
[ +277 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all
devices.
[  +82 ms] iPhone Xʀ             • <<<information removed>>> • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-12-4
           (simulator)
[   +4 ms] iPad (5th generation) • <<<information removed>>> • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-12-4
           (simulator)
[   +2 ms] macOS                 • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G95
[        ] Chrome                • chrome                               • web-javascript • Google Chrome 78.0.3904.108
[        ] Web Server            • web-server                           • web-javascript • Flutter Tools
[  +17 ms] "flutter run" took 788ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:575:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:500:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:490:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/tianguang/Documents/f/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


```

```
Running "flutter pub get" in carouselattempt...                     0.5s
Analyzing carouselattempt...                                            
No issues found! (ran in 8.2s)
```

```
Downloading android-arm-profile/darwin-x64 tools...                 0.7s
Downloading android-arm-release/darwin-x64 tools...                 0.4s
Downloading android-arm64-profile/darwin-x64 tools...               0.4s
Downloading android-arm64-release/darwin-x64 tools...               0.3s
Downloading android-x64-profile/darwin-x64 tools...                 0.4s
Downloading android-x64-release/darwin-x64 tools...                 0.3s
Downloading package sky_engine...                                   0.3s
Downloading common tools...                                         0.6s
Downloading common tools...                                         0.5s
Downloading darwin-x64 tools...                                     1.1s
[✓] Flutter (Channel master, v1.12.6-pre.15, on Mac OS X 10.14.6 18G95, locale en-DE)
    • Flutter version 1.12.6-pre.15 at /Users/tianguang/Documents/f/flutter
    • Framework revision 43a8a1902e (43 minutes ago), 2019-11-21 12:09:43 +0100
    • Engine revision 7a77e3625d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tianguang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (5 available)
    • iPhone Xʀ             • <<<information removed>>> • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)
    • iPad (5th generation) • <<<information removed>>> • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)
    • macOS                 • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G95
    • Chrome                • chrome                               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server            • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2019-11-21 12:40
@HansMuller 
I think it might be a duplicate of  https://github.com/flutter/flutter/issues/45096

**Comment by HansMuller** [comment] 2019-11-21 16:38
@iapicca 
I agree, this appears to be a duplicate. I'm going to close it.

**Closed by HansMuller** 2019-11-21 16:38 UTC
Labels: f: scrolling, framework, severe: regression
