### ISSUE TITLE
[web] Flutter app lags on scrolling in android devices

### ISSUE THREAD

**Issue by raviganwal** [flutter/flutter#46177] opened 2019-12-05 19:22 UTC
Hi, I am creating a flutter web app(https://raviganwal.github.io/#/). it works on pc browser just fine, but it lags too much while scrolling in the mobile device browser particularly google chrome-android. 
~~because in other mobile browsers such as Samsung Internet it does not open at all.~~
Strangely it was not loading on [Samsung Internet](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser) till now, but now it loads.
  
Furthermore, I have tested this issue in a few mobile browsers myself.
1. In  [Opera Mini](https://play.google.com/store/apps/details?id=com.opera.mini.native) URL Did not load at all.
2. In [Firefox Browser](https://play.google.com/store/apps/details?id=org.mozilla.firefox), [Samsung Internet](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser), [Microsoft Edge](https://play.google.com/store/apps/details?id=com.microsoft.emmx), [UC Browser](https://play.google.com/store/apps/details?id=com.UCMobile.intl) URL Loads But UI lags on scrolling

the output of `flutter doctor -v`:
```
[√] Flutter (Channel dev, v1.12.4, on Microsoft Windows [Version 10.0.18362.476], locale en-IN)
    • Flutter version 1.12.4 at C:\flutter
    • Framework revision 2461c75600 (3 weeks ago), 2019-11-18 12:26:51 -0500
    • Engine revision 5fb7eb753b
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Ravi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```
I am giving link of [My code](https://github.com/raviganwal/portfolio/blob/master/lib/Portfolio.dart). this is just a small project.

Although My project just contains
```
SingleChildScrollView(
  child: Column(
 children: <Widget>[
         Header Part,
         listView 1,
         listView 2,
         listView 3,
       ]
   )
)
```

**Comment by iapicca** [comment] 2019-12-06 09:22
Hi @raviganwal 
The scrolling issue you described might be already addressed in this open [issue](https://github.com/flutter/flutter/issues/42987).

Although you mentioned that is some cases it doesn't run at all;
could you please provide your   `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.

Could you please mention what devices are affected ?
Is it [this ](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en)the browser you mentioned? 

Thank you

**Comment by johnstef99** [comment] 2019-12-09 10:47
I have the same problem! Scrolling using opera or chrome beta works fine but on the main chrome version the scrolling is lagging. Scrolling also works in Safari iPhone! So I think it's an chrome browser problem

**Comment by raviganwal** [comment] 2019-12-09 11:17
@johnstef99 For me it's lagging on every browser I mentioned above!

**Comment by johnstef99** [comment] 2019-12-11 11:33
@raviganwal change to master channel!

**Comment by Piinks** [comment] 2020-02-27 18:05
Thanks for your contribution. This appears to be a duplicate of #42987. Please track that issue for updates. If you believe we've made an error, please reply here with more details that explain the difference and we'll re-open this issue.

**Closed by Piinks** 2020-02-27 18:05 UTC
Labels: customer: crowd, f: scrolling, framework, perf: speed, severe: performance, ☸ platform-web

**Comment by raviganwal** [comment] 2020-03-06 09:13
@Piinks But for me URL in not loading In Opera Mini also. Please check my question.

**Comment by chandrikaReddyBunga** [comment] 2020-05-21 14:30
My web app is very slow when scrolling on mobile phones
 , please tell me the solution.

**Comment by Baluds** [comment] 2020-09-19 10:29
I have the same problem but using listview.builder helped check it out once and if you find any alternatives let me know :)

**Comment by Baluds** [comment] 2020-09-19 10:33
> Thanks for your contribution. This appears to be a duplicate of #42987. Please track that issue for updates. If you believe we've made an error, please reply here with more details that explain the difference and we'll re-open this issue.

The thing is pr #42987 addresses the problem in general considering all the devices but the pr only fixes some scroll issues in pc but not on android.scroll on  Flutter web on android is very laggy and when animations are added to it , the lag can be witnessed for atleast 2 seconds

**Comment by Muraligopal09** [comment] 2020-09-24 10:19
use ListView  instead of SingleChildScrollView


ListView(
 children: <Widget>[
         Header Part,
         listView 1,
         listView 2,
         listView 3,
       ],
 ),
