### ISSUE TITLE
flutter ios platform support m3u8?

### ISSUE THREAD

**Issue by tonywong1996** [flutter/flutter#15678] opened 2018-03-19 07:09 UTC
Now. i can run the project in ios platform .
![381769910918220178](https://user-images.githubusercontent.com/32920112/37582296-48613d4a-2b87-11e8-99dd-050b91cf5b6e.jpg)

 when i change the url to m3u8   the player no thing to see......
![244668706005149902](https://user-images.githubusercontent.com/32920112/37582300-4b2c10ae-2b87-11e8-88da-55f6a7740943.jpg)
 
 

 In android platform. it can run m3u8 ....
![x5mh74c nyivp9 v43sxr2r](https://user-images.githubusercontent.com/32920112/37582308-551ff102-2b87-11e8-8de6-e8e515be94d6.jpg)

all platform are real devices. 
 
 

Thanks

**Comment by tonywong1996** [comment] 2018-03-19 07:09
![image](https://user-images.githubusercontent.com/32920112/37582357-8f14bd20-2b87-11e8-980b-8c6ce321e8e2.png)
 log....

**Comment by chinmaygarde** [comment] 2018-03-19 19:16
Flutter defers to the underlying platform for media playback. Flutter can display media formats natively supported by the platform. It is possible that the format you specified is not supported on iOS.

**Comment by zoechi** [comment] 2019-01-22 15:49
Duplicate of #18328

**Closed by zoechi** 2019-01-22 15:49 UTC
Labels: a: video, e: device-specific, engine, p: first party, p: video_player, plugin, ⌺‬ platform-ios
