### ISSUE TITLE
Can not decode letters like æøå

### ISSUE THREAD

**Issue by Itszipzon** [flutter/flutter#160818] opened 2024-12-24 11:54 UTC
### Steps to reproduce

String input = "Hva setter mange nordmenn på toppen av juletreet?";

utf8.decode(input.runes.toList());

### Expected results

It is just supposed to decode some signs like ´ or '  ` that caused error before, but now the æøå is giving error

Expected: Hva setter mange nordmenn på toppen av juletreet?

### Actual results

Hva setter mange nordmenn p� toppen av juletreet?

source bytes:
[102, 108, 117, 116, 116, 101, 114, 58, 32, 72, 118, 97,
32, 115, 101, 116, 116, 101, 114, 32, 109, 97, 110, 103,
101, 32, 110, 111, 114, 100, 109, 101, 110, 110, 32,
112, 239, 191, 189, 32, 116, 111, 112, 112, 101, 110,
32, 97, 118, 32, 106, 117, 108, 101, 116, 114, 101, 101,
116, 63]

### Code sample

<details open><summary>Code sample</summary>

```dart
  static String fixEncoding(String string) {
    return utf8.decode(string.runes.toList(), allowMalformed: true);
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found
while decoding string: flutter: Hva setter mange
nordmenn p� toppen av juletreet?. The Flutter team would
greatly appreciate if you could file a bug explaining
exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[102, 108, 117, 116, 116, 101, 114, 58, 32, 72, 118, 97,
32, 115, 101, 116, 116, 101, 114, 32, 109, 97, 110, 103,
101, 32, 110, 111, 114, 100, 109, 101, 110, 110, 32,
112, 239, 191, 189, 32, 116, 111, 112, 112, 101, 110,
32, 97, 118, 32, 106, 117, 108, 101, 116, 114, 101, 101,
116, 63]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.4.1
    23E224 darwin-arm64, locale nb-NO)
    • Flutter version 3.24.3 on channel stable at
      /Users/runemolander/Documents/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 months ago),
      2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing
      the Android SDK components.
      (or visit
      https://flutter.dev/to/macos-android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom
      location, please use
      `flutter config --android-sdk` to update to that
      location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed
      instructions).

[✓] VS Code (version 1.93.0)
    • VS Code at /Users/runemolander/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • Rune sin iPhone 12 Pro Max (mobile) • 00008101-000C799011A0001E            •
      ios            • iOS 18.2 22C152
    • iPhone 15 Pro Max (mobile)          • BEC7C32B-1EBF-44BE-BBC4-2AEE6DC8BB97 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                     • macos                                •
      darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                •
      darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                        • chrome                               •
      web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by sma** [comment] 2024-12-24 13:52
`input.runes` is not a valid input for `utf8.decode`. Runes are unicode code points. The `decode` method expects bytes. The code point of `å` is 229 (U+00e5). The UTF-8 encoding of that value is [195, 165].

**Comment by danagbemava-nc** [comment] 2024-12-31 06:38
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137025

PS: You may want to file this as a bug report on the dart-lang/sdk repo although this particular error is being tracked in the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-12-31 06:38 UTC
Labels: in triage
