### ISSUE TITLE
CircularProgressIndicator comes with a jank by default

### ISSUE THREAD

**Issue by aquadesk** [flutter/flutter#108168] opened 2022-07-22 14:42 UTC
## Details

1. created a new flutter project with flutter 3 (but I think it happens on older versions as well. but not confirmed)

```
flutter create jank_example
```

1. update code `main.dart` to render just an indicator

```
    return const Scaffold(
        body: Center(
      child: CircularProgressIndicator(),
    ));

```

1. run flutter profile mode 

device OnePlus 6

```
flutter run --profile
```

1. open performance tool and see the jank

![image](https://user-images.githubusercontent.com/19755104/180463215-52f3b6b0-73a8-421f-bd57-5bfd5af25842.png)

I've created the repo 
https://github.com/aquadesk/flutter-3-indicator-jank

### logs 

<details>
  <summary>
    
```
    flutter doctor -v
    [✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-US)
        • Flutter version 3.0.5 at /Users/youngjaeji/Documents/flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision f1875d570e (9 days ago), 2022-07-13 11:24:16 -0700
        • Engine revision e85ea0e79c
        • Dart version 2.17.6
        • DevTools version 2.12.2
    
    [!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
        • Android SDK at /Users/youngjaeji/Library/Android/sdk
        ✗ cmdline-tools component is missing
          Run `path/to/sdkmanager --install "cmdline-tools;latest"`
          See https://developer.android.com/studio/command-line for more details.
        ✗ Android license status unknown.
          Run `flutter doctor --android-licenses` to accept the SDK licenses.
          See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
    
    [!] Xcode - develop for iOS and macOS
        ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
          Download at: https://developer.apple.com/xcode/download/
          Or install Xcode via the App Store.
          Once installed, run:
            sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
            sudo xcodebuild -runFirstLaunch
        • CocoaPods version 1.11.3
    
    [✓] Chrome - develop for the web
        • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
    [✓] Android Studio (version 2021.2)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    
    [✓] VS Code (version 1.69.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.44.0
    
    [✓] Connected device (3 available)
        • ONEPLUS A6013 (mobile) • 23a4895f • android-arm64  • Android 11 (API 30)
        • macOS (desktop)        • macos    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
        • Chrome (web)           • chrome   • web-javascript • Google Chrome 103.0.5060.134
    
    [✓] HTTP Host Availability
        • All required HTTP hosts are available
    
    ! Doctor found issues in 2 categories.

```

  </summary>

</details>

[dart_devtools_2022_7_22-1658500935628000.json.zip](https://github.com/flutter/flutter/files/9168632/dart_devtools_2022_7_22-1658500935628000.json.zip)

attached the exported jank logs

**Comment by darshankawar** [comment] 2022-07-25 08:09
This looks similar / duplicate of https://github.com/flutter/flutter/issues/17793, so please follow-up in it for further updates and share your findings in it for better tracking.

Closing.

**Closed by darshankawar** 2022-07-25 08:09 UTC
Labels: in triage
