### ISSUE TITLE
VIVO I/flutter ( 8765): Observatory listening on ************************************

### ISSUE THREAD

**Issue by arman-juliansyah** [flutter/flutter#84907] opened 2021-06-19 11:49 UTC
flutter can't run hot reload on hp vivo V2025, Stack in 
I/flutter ( 8765): Observatory listening on ************************************

<img width="693" alt="Screen Shot 2021-06-19 at 18 45 59" src="https://user-images.githubusercontent.com/30833678/122641281-854c4100-d12e-11eb-9c0b-78d4cdc65f80.png">

<img width="693" alt="Screen Shot 2021-06-19 at 18 45 59" src="https://user-images.githubusercontent.com/30833678/122641297-99903e00-d12e-11eb-8dc4-bc06eafd9a6a.jpeg">

<img width="693" alt="Screen Shot 2021-06-19 at 18 48 47" src="https://user-images.githubusercontent.com/30833678/122641352-eaa03200-d12e-11eb-968c-6fe1bfecc7e6.png">

**Comment by rsbthebest** [comment] 2021-06-21 05:32
Am facing the same issue, can no longer develop on my Vivo device.

Please let me know if you need any details to move ahead with this issue.

**Comment by rsbthebest** [comment] 2021-06-21 05:33
Here is a link of StackOverflow showing more users facing the same issue with Vivo device:
https://stackoverflow.com/questions/67608470/flutter-app-stuck-on-the-observatory-listening-on-reload#

**Comment by TahaTesser** [comment] 2021-06-21 11:19
Hi @arman-juliansyah 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/82520
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-21 11:19 UTC
Labels: in triage
