### ISSUE TITLE
Container bottom border is get thickening while vertical scrolling

### ISSUE THREAD

**Issue by RenugaSadagoban98** [flutter/flutter#86558] opened 2021-07-16 14:28 UTC
Hi Team,
I have arranged the multiple Container widgets in the rows and columns-wise inside the nested Scrollview widget and I have set the left and bottom border to the container by using BoxDecoration.  While vertical scrolling, the container's bottom border seems thickened.

<details> 
<summary>code snippet</summary> 

```dart
class SimpleSample extends StatefulWidget {
  const SimpleSample({Key? key}) : super(key: key);

  @override
  _SimpleSampleState createState() => _SimpleSampleState();
}
class _SimpleSampleState extends State<SimpleSample> {
  ScrollController verticalController = ScrollController(),
      horizontalController = ScrollController();

  List<Row> buildRows() {
    return List.generate(
        50,
        (index) => Row(
                children: List.generate(
              20,
              (index) => Container(
                height: 100,
                width: 100,
                child: Center(child: Text('Row ${index}')),
                decoration: BoxDecoration(
                    border: Border(
                        left: BorderSide(color: Colors.grey),
                        bottom: BorderSide(color: Colors.grey))),
              ),
            )));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: SingleChildScrollView(
            controller: verticalController,
            scrollDirection: Axis.vertical,
            child: SingleChildScrollView(
              controller: horizontalController,
              scrollDirection: Axis.horizontal,
              child: Container(
                child: Column(
                  children: buildRows(),
                ),
              ),
            )));
  }
}
```

</details> 

**Expected results:** The container's bottom border should not thicken while scrolling vertically.

**Actual results:**  The Container's bottom border gets thickening while scrolling vertically

 **Issue image:**  
![image](https://user-images.githubusercontent.com/77044081/125966008-63319600-13f4-454e-a473-b4ec0764fcc8.png)

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel master, 2.4.0-5.0.pre.76, on Microsoft Windows [Version 10.0.19041.1083], locale en-US)
    • Flutter version 2.4.0-5.0.pre.76 at C:\Users\RenugadeviSadagoban\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8cf1de3e68 (8 hours ago), 2021-07-16 01:11:02 -0400
    • Engine revision c2ffafea35
    • Dart version 2.14.0 (build 2.14.0-321.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.4.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.4.29519.181
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.58.1)
    • VS Code at C:\Users\RenugadeviSadagoban\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1083]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment] 2021-07-19 11:27
Hi @RenugaSadagoban98 
This is an antialiasing artifact, easily reproducible in a grid layout 
Closing as duplicate of https://github.com/flutter/flutter/issues/14288

**Closed** 2021-07-19 11:27 UTC
Labels: r: duplicate
