### ISSUE TITLE
Flutter web giving the below issue mentioned inside StaggeredGridView.countBuilder block any solution on this would be helpful

### ISSUE THREAD

**Issue by Manjunath375** [flutter/flutter#67398] opened 2020-10-06 09:22 UTC
```
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.created
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49  throw_
lib/_engine/engine/html/surface.dart 175:3                                    debugAssertSurfaceState
lib/_engine/engine/html/scene_builder.dart 278:14                             addRetained
packages/flutter/src/rendering/layer.dart 439:14                              [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 2001:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1295:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1166:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 2001:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1166:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1166:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1611:5                              addToScene
packages/flutter/src/rendering/layer.dart 767:5                               buildScene
packages/flutter/src/rendering/view.dart 231:30                               compositeFrame
packages/flutter/src/rendering/binding.dart 440:18                            drawFrame
packages/flutter/src/widgets/binding.dart 914:13                              drawFrame
packages/flutter/src/rendering/binding.dart 302:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1117:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1055:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 971:5                             [_handleDrawFrame]
lib/_engine/engine/window.dart 758:13                                         _invoke
lib/_engine/engine/window.dart 358:5                                          invokeOnDrawFrame
lib/_engine/engine.dart 228:18                                                <fn>
dart-sdk/lib/async/zone.dart 1206:13                                          _rootRunUnary
dart-sdk/lib/async/zone.dart 1100:19                                          runUnary
dart-sdk/lib/async/zone.dart 1005:7                                           runUnaryGuarded
dart-sdk/lib/async/zone.dart 1042:26                                          <fn>

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following PersistedSurfaceException was thrown during a scheduler callback:
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.created

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49  throw_
lib/_engine/engine/html/surface.dart 175:3                                    debugAssertSurfaceState
lib/_engine/engine/html/scene_builder.dart 278:14                             addRetained
packages/flutter/src/rendering/layer.dart 439:14                              [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 2001:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1295:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1166:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 2001:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1166:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1166:5                              addToScene
packages/flutter/src/rendering/layer.dart 442:5                               [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1029:14                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1611:5                              addToScene
packages/flutter/src/rendering/layer.dart 767:5                               buildScene
packages/flutter/src/rendering/view.dart 231:30                               compositeFrame
packages/flutter/src/rendering/binding.dart 440:18                            drawFrame
packages/flutter/src/widgets/binding.dart 914:13                              drawFrame
packages/flutter/src/rendering/binding.dart 302:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1117:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1055:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 971:5                             [_handleDrawFrame]
lib/_engine/engine/window.dart 758:13                                         _invoke
lib/_engine/engine/window.dart 358:5                                          invokeOnDrawFrame
lib/_engine/engine.dart 228:18                                                <fn>
dart-sdk/lib/async/zone.dart 1206:13                                          _rootRunUnary
dart-sdk/lib/async/zone.dart 1100:19                                          runUnary
dart-sdk/lib/async/zone.dart 1005:7                                           runUnaryGuarded
dart-sdk/lib/async/zone.dart 1042:26                                          <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
FlutterError.onError

```

**Comment by darshankawar** [comment] 2020-10-06 13:27
@Manjunath375 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by Manjunath375** [comment] 2020-10-07 05:20
flutter doctor -v
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.0-12.1.pre at /Applications/source/flutter
    • Framework revision 8b3760638a (3 weeks ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/mantralabs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 2 categories.
 


code sample

 StaggeredGridView.countBuilder(
                  crossAxisCount: 2,
                  itemCount: itemsCount,
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  itemBuilder: (BuildContext context, int index) =>
                      buildChildItem(
                          index, isDataAvailable, homeChildModelList),
                  staggeredTileBuilder: (int index) {
                    if (!isDataAvailable) {
                      if (index == 0) {
                        return StaggeredTile.extent(2, itemHeight1x);
                      }
                      return StaggeredTile.extent(1, itemHeight1x);
                    } else {
                      if (homeChildModelList[index].isGrid != null &&
                          homeChildModelList[index].isGrid) {
                        return StaggeredTile.extent(1, itemHeight2x);
                      } else {
                        return StaggeredTile.extent(2, itemHeight1x);
                      }
                    }
                  },
                  mainAxisSpacing: 12.0,
                  crossAxisSpacing: 12.0,
                )

**Comment by darshankawar** [comment] 2020-10-07 06:50
@Manjunath375 
The code you provided seems to be incomplete. Please provide a complete minimal code sample that we can copy paste and run in IDE that shows the issue.
Thanks.

**Comment by Manjunath375** [comment] 2020-10-07 07:01
code is splitted into several block could not make a simple minimal code the above mentioned issue is getting repeated for several times

**Comment by darshankawar** [comment] 2020-10-07 13:58
@Manjunath375 Are you by any chance using `https://pub.dev/packages/flutter_staggered_grid_view/install` plugin in your code ?
If yes, please try to remove that plugin code and try again to see if it works. If issue doesn't occur, then the issue could be due to the pluign. Please verify accordingly.
Thanks.

**Comment by Manjunath375** [comment] 2020-10-09 10:10
I Checked it. It is not from the staggered plugin. It is from **InkResponse** This Constructor. Inside this i have added onTap and child Container is there any other alternative to use. Mention The Constructor That would be helpful

**Comment by darshankawar** [comment] 2020-10-09 11:41
@Manjunath375 
The code sample you provided is incomplete. I see lot of custom code in it whose implementation is not provided. Please provide a workable and complete reproducible code sample that we can simply copy paste and run in IDE to see the issue.

**Comment by Manjunath375** [comment] 2020-10-09 13:04
Check with Shimmer

**Below code will show the error**

import 'package:flutter/material.dart';
import 'package:shimmer/shimmer.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Shimmer.fromColors(
          baseColor: Colors.grey[300],
          highlightColor: Colors.grey[100],
           child: Container(
        decoration: BoxDecoration(
          color: Colors.grey[100],
          border: Border.all(color: Colors.grey.shade300),
        ),
      ),
        )
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by darshankawar** [comment] 2020-10-09 13:42
@Manjunath375 
`shimmer` is a 3rd party plugin. Anyways, I tried your code sample, but didn't see anything render on screen and got bunch of Exception logs:

`Another exception was thrown: UnimplementedError
Another exception was thrown: UnimplementedError`

Probably it has something to do with the plugin which may not be supporting web yet.

Please provide a video / gif of the issue you are facing without including 3rd party plugin code.

**Comment by pedromassangocode** [comment] 2020-10-30 11:36
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-30 11:36 UTC
