### ISSUE TITLE
Material Palette Icon size discrepancy

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#70691] opened 2020-11-17 13:42 UTC
Icon size btw `Icons.palette_outlined` and `Icons.palette` is different. Here is a short 

![ezgif-3-78215d73e25e](https://user-images.githubusercontent.com/25743901/99397273-bd5e7d80-28da-11eb-9f5b-44bbe3dff475.gif)

**Expected results:** 
Expected is both, the outline and the filled to be of the same size such as lightbulb or favorite icons are.

**Actual results:** 
filled icon is smaller than the outlined one even though both are set to be the same size: 32

<details><summary>Min repro code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(AmbeeApp());
}

class AmbeeApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ambee 2.0',
      home: TabBarScreen(),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class TabBarScreen extends StatefulWidget {
  @override
  _TabBarScreenState createState() => _TabBarScreenState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _TabBarScreenState extends State<TabBarScreen> {
  int _selectedIndex = 0;
  static const TextStyle optionStyle = TextStyle(fontSize: 30, fontWeight: FontWeight.bold);
  static const List<Widget> _widgetOptions = <Widget>[
    Text(
      'Index 0: Discover',
      style: optionStyle,
    ),
    Text(
      'Index 1: Favorites',
      style: optionStyle,
    ),
    Text(
      'Index 2: Lights',
      style: optionStyle,
    ),
  ];

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: _widgetOptions.elementAt(_selectedIndex),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.palette_outlined),
            activeIcon: Icon(Icons.palette),
            label: 'Discover',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.favorite_outline),
            activeIcon: Icon(Icons.favorite),
            label: 'Favorites',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.lightbulb_outline),
            activeIcon: Icon(Icons.lightbulb),
            label: 'Lights',
          ),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.amber[800],
        iconSize: 32,
        selectedFontSize: 12,
        unselectedFontSize: 12,
        onTap: _onItemTapped,
      ),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.251, on macOS 11.0.1 20B29 darwin-x64, locale es-ES)
    • Flutter version 1.24.0-8.0.pre.251 at /Users/tomas/code/flutter
    • Framework revision 836efaecf0 (3 days ago), 2020-11-13 21:51:04 -0800
    • Engine revision e06f106385
    • Dart version 2.12.0 (build 2.12.0-40.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • iPhone (mobile)            • 00008020-000415840E50003A            • ios • iOS 14.2
    • iPhone 12 Pro Max (mobile) • CF12B78D-3231-44DD-B217-A38E4A68588B • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 3 categories.



```

</details>

**Comment by pedromassangocode** [comment] 2020-11-17 13:52
The issue here is that the `Icons.palette` seems more smaller than `Icons.palette_outlined`.

![gif2](https://user-images.githubusercontent.com/67424416/99398155-4f1eb880-28e4-11eb-8fbe-d785d9775379.gif)


<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.267, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.267 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 22e576fa26 (11 hours ago), 2020-11-16 18:48:03 -0500
    • Engine revision f0e80100f7
    • Dart version 2.12.0 (build 2.12.0-49.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 86.0.4240.198

• No issues found!

```
</details>

**Comment by HansMuller** [comment] 2020-11-17 16:58
CC @willlarche

**Comment by willlarche** [comment] 2021-01-05 15:18
If you look on [material.io/icons](https://material.io/resources/icons/?search=palette&style=outline), you can see that the actual icon has different sizes. I'll put in a note to the icon team that someone has requested it be reconciled but we unfortunately will need to close this as working as intended for now.

**Comment by guidezpl** [comment] 2021-03-12 12:19
This will be fixed in the icon update after https://github.com/flutter/flutter/pull/76607 (no date yet)

**Closed** 2021-03-25 09:22 UTC
Labels: a: quality, f: material design, found in release: 1.24, framework, has reproducible steps
