### ISSUE TITLE
[camera] The camera library throws NullPointerException and crashes the app

### ISSUE THREAD

**Issue by bssughosh** [flutter/flutter#90173] opened 2021-09-16 07:45 UTC
## Steps to Reproduce

1. Initialize camera for video recording
2. Start video recording
3. Stop video recording after one chunk is recorded
4. Again start the recording till all the chunks are recorded
5. Faced this issue after some chunks are recorded and app crashes completely even if I have handled it properly 

**Expected results:** The chunking operations must be performed seamlessly and app must not crash 

**Actual results:** The app crashes completely

<details>
  <summary>Logs</summary>

```
[        ] E/AndroidRuntime(12443): FATAL EXCEPTION: LegacyCameraCallback
[        ] E/AndroidRuntime(12443): java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest
android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference
[        ] E/AndroidRuntime(12443):     at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:1792)
[        ] E/AndroidRuntime(12443):     at
android.hardware.camera2.legacy.CameraDeviceUserShim$CameraCallbackThread$CallbackHandler.handleMessage(CameraDeviceUserShim.java:316)
[        ] E/AndroidRuntime(12443):     at android.os.Handler.dispatchMessage(Handler.java:102)
[        ] E/AndroidRuntime(12443):     at android.os.Looper.loop(Looper.java:154)
[        ] E/AndroidRuntime(12443):     at android.os.HandlerThread.run(HandlerThread.java:61)
[  +56 ms] E/ActivityThread(12443): Activity com.***.***.MainActivity has leaked IntentReceiver
io.flutter.plugins.camera.features.sensororientation.DeviceOrientationManager$1@e5f1ff1 that was originally registered here. Are you missing a call to
unregisterReceiver()?
[        ] E/ActivityThread(12443): android.app.IntentReceiverLeaked: Activity com.***.***.MainActivity has leaked IntentReceiver
io.flutter.plugins.camera.features.sensororientation.DeviceOrientationManager$1@e5f1ff1 that was originally registered here. Are you missing a call to
unregisterReceiver()?
[        ] E/ActivityThread(12443):     at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1168)
[        ] E/ActivityThread(12443):     at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:955)
[        ] E/ActivityThread(12443):     at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
[        ] E/ActivityThread(12443):     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
[        ] E/ActivityThread(12443):     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
[        ] E/ActivityThread(12443):     at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.features.sensororientation.DeviceOrientationManager.start(DeviceOrientationManager.java:80)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.features.sensororientation.SensorOrientationFeature.<init>(SensorOrientationFeature.java:42)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.features.CameraFeatureFactoryImpl.createSensorOrientationFeature(CameraFeatureFactoryImpl.java:78)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.features.CameraFeatures.init(CameraFeatures.java:58)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.Camera.<init>(Camera.java:161)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:394)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$MethodCallHandlerImpl(MethodCallHandlerImpl.java:85)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.-$$Lambda$MethodCallHandlerImpl$OMU5dV7VCKXKBT37_ThIybqlHuo.onResult(lambda)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:53)
[        ] E/ActivityThread(12443):     at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:78)
[        ] E/ActivityThread(12443):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/ActivityThread(12443):     at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/ActivityThread(12443):     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[        ] E/ActivityThread(12443):     at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/ActivityThread(12443):     at android.os.MessageQueue.next(MessageQueue.java:323)
[        ] E/ActivityThread(12443):     at android.os.Looper.loop(Looper.java:136)
[        ] E/ActivityThread(12443):     at android.app.ActivityThread.main(ActivityThread.java:6165)
[        ] E/ActivityThread(12443):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/ActivityThread(12443):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
[        ] E/ActivityThread(12443):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```
                                   

```
No issues found! (ran in 3.6s)
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-IN)
    • Flutter version 2.2.3 at /Users/sughosh/development/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sughosh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2021-09-16 10:02
@bssughosh 
What camera plugin version are you using ?
Can you provide a complete minimal code sample that we can use to verify this issue ?
Thanks.

**Comment by bssughosh** [comment] 2021-09-16 10:14
@darshankawar 
The version we are using is `0.9.2+2` 

Will post the minimal sample code asap.
Thank you for looking into this

**Comment by bssughosh** [comment] 2021-09-16 10:58
@darshankawar 
Code:

```
import 'dart:async';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

List<CameraDescription>? cameras;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: CameraApp(title: 'Camera Test'),
    );
  }
}

class CameraApp extends StatefulWidget {
  CameraApp({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  CameraController? _cameraController;
  Timer? _timer;
  int _captureWindow = 120;
  bool _isTestInProgress = false;

  @override
  void initState() {
    super.initState();
    CameraDescription _cameraDescription = cameras!.firstWhere(
      (CameraDescription camera) =>
          camera.lensDirection == CameraLensDirection.front,
    );
    _cameraController = CameraController(
      _cameraDescription,
      ResolutionPreset.low,
      enableAudio: true,
    );

    _cameraController!.initialize().then((value) {
      if (!mounted) {
        return;
      }

      setState(() {});
    });
  }

  @override
  void dispose() {
    _cameraController!.dispose();
    super.dispose();
  }

  void _startTest() async {
    setState(() {
      _isTestInProgress = true;
    });
    await _cameraController!.startVideoRecording();
    print('Started Video Recording');
    _timer = new Timer.periodic(new Duration(seconds: 1), (timer) async {
      int duration = timer.tick;
      print('Duration:$duration');
      if (duration != 0 && duration % _captureWindow == 0) {
        try {
          XFile file = await _cameraController!.stopVideoRecording();
          print('Video Captured Successfully at path: ${file.path}');
        } catch (error) {
          // Camera Exception is thrown
          print('Error Encountered while stopping the camera:$error');
        }
        try {
          await _cameraController!.startVideoRecording();
        } catch (error) {
          // Camera Exception is not thrown here
          print('Error Encountered while starting the camera:$error');
        }
        print('Started Video Recording');
      }
    });
  }

  void _stopTest() async {
    setState(() {
      _isTestInProgress = false;
    });
    _timer!.cancel();
    try {
      XFile file = await _cameraController!.stopVideoRecording();
      print('Test Concluded');
      print('Video Captured Successfully at path: ${file.path}');
    } catch (error) {
      print('Error Encountered while stopping the camera:$error');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SafeArea(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              _cameraController!.value.isInitialized
                  ? Expanded(child: CameraPreview(_cameraController!))
                  : Container(),
              _isTestInProgress
                  ? TextButton(
                      onPressed: _stopTest,
                      child: Container(child: Text('STOP TEST')))
                  : TextButton(
                      onPressed: _startTest,
                      child: Container(
                        child: Text('START TEST'),
                      ))
            ],
          ),
        ),
      ),
    );
  }
}
```

Device: `Moto G Play`
Android: `7.1.1`

**Comment by darshankawar** [comment] 2021-09-17 06:09
@bssughosh 
Thanks for the code sample. I ran it and see the same behavior. However, there's a similar open issue describing your case, https://github.com/flutter/flutter/issues/79306. So I believe this is a duplicate of the linked issue. Please follow-up in the original one for further updates.
Closing this as a duplicate.

**Closed by darshankawar** 2021-09-17 06:09 UTC
Labels: in triage

**Comment by bssughosh** [comment] 2021-09-17 06:16
@darshankawar 
But that issue has been open since 30 Mar, and not have any updates on that. 
So could that issue be escalated as we have crashes in production

**Comment by darshankawar** [comment] 2021-09-17 06:25
I will certainly try to raise it with concerned team.
