### ISSUE TITLE
Crash in EmbedderTest.CanTerminateCleanly

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#86745] opened 2021-07-20 22:17 UTC
Here https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Unopt/781/overview on PR https://github.com/flutter/engine/pull/27327, but it doesn't look related.

```
[ RUN      ] EmbedderTest.CanTerminateCleanly
../../third_party/dart/runtime/bin/thread_linux.cc: 248: error: pthread error: 16 (Device or resource busy)
version=2.14.0-338.0.dev (dev) (Tue Jul 20 07:16:35 2021 -0700) on "linux_x64"
[ERROR:flutter/fml/backtrace.cc(116)] Caught signal SIGSEGV during program execution.
Frame 0: 0x39faaac dart::Assert::Fail()
Frame 1: 0x3858293 dart::bin::Monitor::~Monitor()
Frame 2: 0x383b74f dart::bin::Process::Cleanup()
Frame 3: 0x240ac0b flutter::DartVM::~DartVM()
Frame 4: 0x240cfeb std::__1::default_delete<>::operator()()
Frame 5: 0x240ce4a std::__1::__shared_ptr_pointer<>::__on_zero_shared()
Frame 6: 0x2a53791 std::__1::__shared_count::__release_shared()
Frame 7: 0x2a53809 std::__1::__shared_weak_count::__release_shared()
Frame 8: 0x2410c7c std::__1::shared_ptr<>::~shared_ptr()
Frame 9: 0x2410c43 std::__1::shared_ptr<>::reset()
Frame 10: 0x2410156 flutter::DartVMRef::~DartVMRef()
Frame 11: 0x346f1d8 flutter::Shell::~Shell()
Frame 12: 0x229003b std::__1::default_delete<>::operator()()
Frame 13: 0x228f5cc std::__1::unique_ptr<>::reset()
Frame 14: 0x228b754 flutter::EmbedderEngine::CollectShell()
Frame 15: 0x22469d5 FlutterEngineDeinitialize
Frame 16: 0x2246a05 FlutterEngineShutdown
Frame 17: 0x2130e4e flutter::testing::UniqueEngineTraits::Free()
Frame 18: 0x2130df9 fml::UniqueObject<>::FreeIfNecessary()
Frame 19: 0x212c3a5 fml::UniqueObject<>::~UniqueObject()
Frame 20: 0x214b8b9 flutter::testing::EmbedderTest_CanTerminateCleanly_Test::TestBody()
Frame 21: 0x3ee723b testing::internal::HandleSehExceptionsInMethodIfSupported<>()
Frame 22: 0x3ed7637 testing::internal::HandleExceptionsInMethodIfSupported<>()
Frame 23: 0x3ec7053 testing::Test::Run()
Frame 24: 0x3ec76f1 testing::TestInfo::Run()
Frame 25: 0x3ec7cb4 testing::TestSuite::Run()
Frame 26: 0x3ed131f testing::internal::UnitTestImpl::RunAllTests()
Frame 27: 0x3eea67b testing::internal::HandleSehExceptionsInMethodIfSupported<>()
Frame 28: 0x3ed9087 testing::internal::HandleExceptionsInMethodIfSupported<>()
Frame 29: 0x3ed0f2f testing::UnitTest::Run()
Frame 30: 0x2429871 RUN_ALL_TESTS()
Frame 31: 0x2429732 main
Frame 32: 0x7f637c9c32e1 __libc_start_main
Frame 33: 0x211a2aa _start
```

**Comment by chinmaygarde** [comment] 2021-07-20 22:28
It's either one of calling `pthread_mutex_destroy` or `pthread_cond_destroy` on a mutex or condition variable that has been locked elsewhere. The VM is being destroyed here via a `Process::Cleanup` invoked by [`dart::bin::CleanupDartIo ` here](https://github.com/flutter/engine/blob/a89a123cb2ce4ae8e613af308e7c484f182eb949/runtime/dart_vm.cc#L487). `Dart_Cleanup` has already occurred by this point (eventually called by `DartVMInitializer::Cleanup`). The frames are missing due to optimization but my guess is that this mutex is the  `signal_mutex` in `Process::Cleanup`. So the offending call is `pthread_mutex_destroy`.

I don't think there is much the engine can do differently here. I believe this needs to be fixed in the VM. @a-siva based on the additional context above, are you able to reason about how that mutex might be locked while we are terminating the VM?

**Comment by a-siva** [comment] 2021-07-20 22:54
@chinmaygarde the stacktrace shows dart::bin::Monitor::~Monitor() which means a monitor in use was being destroyed, so I am wondering if it is not the signal_mutex_ (would have expected Mutex::~Mutex() on the stack in that case).
I am suspecting it is ExitCodeHandler::monitor_ that is the being destroyed, it puzzles me as to who is holding on to this Monitor, In dart::bin::CleanupDartIO we call Process::TerminateExitCodeHandler(); which should have terminated the exit code handler thread.

**Comment by aam** [comment] 2021-07-20 23:23
The issue is with the fact that unit test runs vm twice.
The way how `static bool terminate_done_` is initialized https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_linux.cc#L251 leaves it set to `true` after first run around, so on the second run it doesn't stop TerminateExitCodeThread from waiting until ExitCodeHandlerEntry is done.

**Comment by a-siva** [comment] 2021-07-20 23:27
Yes, I realized that later that these tests are run twice and some of the static state we have is not reset again in the corresponding Init functions.

**Comment by aam** [comment] 2021-07-20 23:34
Awesome, https://dart-review.googlesource.com/c/sdk/+/207641 with proposed fix.

**Comment by a-siva** [comment] 2021-07-21 00:19
https://dart-review.googlesource.com/c/sdk/+/207642

**Comment by chinmaygarde** [comment] 2021-07-26 17:51
Thanks for the fixes everyone.

**Closed by chinmaygarde** 2021-07-26 17:51 UTC
Labels: a: tests, dependency: dart, engine, severe: fatal crash
