### ISSUE TITLE
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws

### ISSUE THREAD

**Issue by sahil311289** [flutter/flutter#19056] opened 2018-07-03 21:34 UTC
Have been stuck for days on this. iOS app crashes on launch.
```
Launching lib/main.dart on Sahil’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: Q48Y4UFKL8
Starting Xcode build...
Xcode build done.
Installing and launching...
5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws
```

Flutter doctor:
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by zoechi** [comment] 2018-07-04 09:08
Looks similar to #18973

**Comment by sahil311289** [comment] 2018-07-04 09:12
Yeah, it is the same issue. 
Nope, no proxy.

**Comment by zoechi** [comment] 2018-07-04 09:17
There is also #14991

I haven't figured out why @Hixie concluded that it is an emulator issue (see https://github.com/flutter/flutter/issues/12353#issuecomment-387577146)

If this is actually related you could try https://github.com/flutter/flutter/issues/13379#issuecomment-400966832

**Comment by DanTup** [comment] 2018-07-04 11:40
What happens after you get that line in the terminal? Does it quit, or stay hung?

If you take the `/ws` off the end of the url in the error (eg. `http://127.0.0.1:8100/`) and paste it into your browser, does anything load?

**Comment by zipzit** [comment] 2018-07-05 02:54
I'm having the exact same issue.   I'm working on https://github.com/nitishk72/flutter_image_picker .  I can test the software program successfully on Xcode ios simulator just fine in file picker mode. Obviously the emulator has no access to the camera.  Hence the use of a real iphone device.  I paid my subscription to Apple, I registered the device via Xcode, etc... 

While testing for this posting, I went back to basics.  I create a new hello_world (the count increment example).  Sample ran great... once.  Then I added a single character to the line `home: new MyHomePage(title: 'Flutter Demo2 Home Page'),`, something that I could see upon reload.  Continuous failure from that moment on.  

```
Launching lib/main.dart on iPhone in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: (my name) (X99999999999)"
Xcode build done.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:8110/ws
Exited (sigterm)
```

Note: the port numbers start at 8101 and vary depending on the run... I was never able to use the browser to verify anything at that IP address.  

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
(not sure what's up with the VS code error... I've installed, removed and reinstalled that thing multiple times. 

```
[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```
 ) Clearly the VS code is showing the flutter-dart module.  

OS: System Version:	macOS 10.13.5 (17F77)
iphone: 6S, ios = 11.3.1 (15E302)

I'm going to reboot the computer and try this all again.  I wanted to get this submitted before the reboot.

**Comment by zipzit** [comment] 2018-07-05 04:40
Still testing.   ios software emulator works great.  Real physical device iphone = erratic and just odd.  When I push code to the physical device, it seems to open up the app and I get a totally white screen.  Quick close the app (with home button push), re-open = same fail (all white screen) .   I still see the exact same error message in VS code during this push process.  

Remove the app 'thread" (with double home button push and then slide the white screen app up and off the phone), then re-click the icon on the physical device = success.   The simple increment app works, but its not clear what's going on here.  I haven't yet tested my simple camera app with the same test.  

Thanks to all for assistance.  One testing note:  I did look at the iphone console... holy cow but there are a whole of messages going by, even on a phone sitting at idle.  The physical device (an iphone 6S) console and device logs are available via Xcode --> Window --> Devices and Simulators --> choose Devices, then select either "view device logs" or "Open Console" button. With phone at idle on the desk, black screen on display,  I'm seeing nearly 1200 messages / minute.  Ugh.   Now I see where my battery juice is going....  

Is there any testing that I can do to bring more clarity on this issue?  Many thanks to all the folks supporting Flutter.

**Comment by DanTup** [comment] 2018-07-05 07:57
What happens if you run `python -c "import weakref"`? There's some info [here](https://github.com/MDAnalysis/mdanalysis/issues/1739#issuecomment-351392026) suggesting maybe something wrong with the Python install.

> (not sure what's up with the VS code error... I've installed, removed and reinstalled that thing multiple times. )

It's a bug; VS Code started lower-casing the extension folder names and our detection was accidentally case-sensitive. It's fixed in the master channel but hasn't made the beta channel yet.

**Comment by DanTup** [comment] 2018-07-05 15:03
The mis-reporting of the VS Code extension in `flutter doctor` is fixed in Flutter's master channel (it's flutter that reads the VS Code extensions). Probably it will be in the next beta release, but it's safe to ignore for now.

I'm not really sure about the Python issue - I hoped it would fail when you ran that so it was easier to debug, but it's strange that you can import it from a terminal like that but not when running flutter. Have you tried running flutter from the same terminal where Python worked, in case you've somehow got a different `PATH` there than when running from VS Code? (sometimes people have `PATH`s configured in shell scripts that only apply in the terminals, so VS Code often has different paths!).

**Comment by zipzit** [comment] 2018-07-05 15:07
Oh, I have no idea what I'm doing when it comes to python symlinks and multiple different paths. Not sure you saw my last edit.  I also didn't see how many open issues there are in this repo.  I now understand the urgency in getting stuff closed.  How can I help?  What can I do next?

**Comment by DanTup** [comment] 2018-07-05 16:28
I didn't see your edit, sorry. Sounds like you've traded one problem for another!

I would start by doing `echo $path` in your terminal and in the VS Code terminal and seeing where they're different - presumably the difference is why it works in one and not the other (I'd also restart both your terminal and VS Code first). 

> I'm getting the errors in VSCode console

What sort of errors?

**Comment by zipzit** [comment] 2018-07-05 20:16
This whole thing is just odd.  I get no response at all to $ `echo $path` no matter where I run it.  In a system bash window $ `python --version` results in `Python 2.7.15`,  $ `python2 --version` = `Python 2.7.15` and $ `python3 --version` = `Python 3.6.5`

In VS Code command line terminal the same tests gets slightly different results.  $ `python --version` results in `Python 2.7.10`,  $ `python2 --version` = `Python 2.7.15` and $ `python3 --version` = `Python 3.6.5`

When I push to physical device the error message within VS code debug console:

```
Launching lib/main.dart on iPhone in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: MyName (X99999999)"
Xcode build done.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Lost connection to device.
Exited (sigterm)
```

**Comment by zipzit** [comment] 2018-07-08 14:22
Update:   I went thru [this guide](https://medium.com/@waxzce/keeping-macos-clean-this-is-my-osx-brew-update-cli-command-6c8f12dc1731) to clean up my MacOS.  I did all the `brew` related steps in the referenced clean up guide but stopped at the Atom and the Clever Cloud stuff.  

I deleted quite a bit of content, most of it related to a manual installation of OpenCV and a little bit of Aubio audio stuff.  

After a couple of reboots, the flutter errors observed above are just gone.  I do see that $ `python --version` in both VS code command line terminal and system bash window now generate the exact same result, `Python 2.7.15` 

Perhaps the clean up macOS and reboot may work for others?

**Comment by DanTup** [comment] 2018-07-09 07:13
> I get no response at all to $ echo $path

It's case-sensitive, you need to use `echo $PATH`.

So what's the state of things now? You're getting the same Python version in all places, but it's still broken deploying to a real iPhone and works for the simulator?

Looking at your original error, it seems like Python 2.7.15 is the bad one - if that's the one on your PATH now, do you see the `_remove_dead_weakref` error when you run `python -c "import weakref"`? If so, getting your `PATH` to point back at 2.7.10 might help?

**Comment by zipzit** [comment] 2018-07-10 03:15
oops. $PATH.  I didn't know that. Thanks for sharing.  

[System Bash Window] $ echo $PATH

```
/development/flutter/bin:
/Users/myName/.nvm/versions/node/v8.9.3/bin:
/opt/local/bin:
/opt/local/sbin:
/usr/local/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin:
/opt/X11/bin:
/Library/Frameworks/Mono.framework/Versions/Current/Commands
```

[VS Code Terminal] $ echo $PATH

```
/development/flutter/bin:
/opt/local/bin:
/opt/local/sbin:
/usr/local/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin:
/opt/X11/bin:
/Library/Frameworks/Mono.framework/Versions/Current/Commands:
/development/flutter/bin:
/opt/local/bin:
/opt/local/sbin
```

From what I can see, there is no python version control dictated by either $PATH setup.  

I get absolutely no feedback with `python -c "import weakref"` in either System Bash Window or VS Code Terminal.  The system responds immediately to that command with a new empty line.  What response are you expecting?  

It sounds like I need to figure out the who, what, when where and why on different versions of python . This whole conversation is frustrating. I'm trying to use `pyenv` to load and control particular versions, but I'm having troubles.  I'm going to need to install a few things and reboot.  In the meantime I don't want to lose my notes in this entry.  

Can I ask some simple questions?

- What is `weakref`?  
- What essential service does it provide to the flutter platform?  

And apologies for hijacking this entire issue from a error message on `weakref` into my really poor understanding of version control of Python on macOS.  Dan, thanks for your patience here...

**Comment by DanTup** [comment] 2018-07-10 09:35
> From what I can see, there is no python version control dictated by either $PATH setup.

You can run `which python` in each to see which binary it's getting. Most likely there are links inside one (or more) of the folders on your `PATH`.

> I get absolutely no feedback with `python -c "import weakref"` in either System Bash Window or VS Code Terminal. The system responds immediately to that command with a new empty line. What response are you expecting?

An empty response is (usually) good, it means that no errors occurred importing the library. The error you're getting when deploying is what would happen if something was broken:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref <-- This is what it was trying to do
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

The question is, why does this happen when you deploy but it's fine from your terminals, and that's one I don't know the answer to. Based on comments in the code, it seems like this might be an `xcodebuild` dependency, but I find much info about this online.

> What is `weakref`?

I'm not familiar with this, but based on the links above  (and [this](https://docs.python.org/2/library/weakref.html)) it's a built-in Python module.

> What essential service does it provide to the flutter platform?

Based on the above, it seems essential for deploying to iPhone. The `copy` module is being used and that seems to import `weakref`. As far as I can tell, these are standard modules that all Python scripts should be able to assume exist.

Can you try running with the `--verbose` flag and attach the output?

**Comment by DanTup** [comment] 2018-07-10 09:40
Also; probably https://github.com/flutter/flutter/issues/17803 is a better place for this issue; I don't think it's related to the original issue here.

**Comment by zipzit** [comment] 2018-07-10 21:10
> Can you try running with the --verbose flag and attach the output?

Not sure how or where to do that.  The error message shows up on VS code Debug Console after you start the debugger.  Here is my launch.json file contents (from with folder .vscode) 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart"
        }
    ]
}
```

**Comment by DanTup** [comment] 2018-07-10 21:23
Adding `"args": ["--verbose"]` to the config should work, but you could also just run from a terminal window (`flutter run --verbose`).

**Comment by zipzit** [comment] 2018-07-10 22:21
File attached.  (You weren't kidding about verbose.  There are nearly 1100 lines of content...) I removed my id stuff and certificates.  
[flutter_verbose_test.txt](https://github.com/flutter/flutter/files/2182339/flutter_verbose_test.txt)

**Comment by DanTup** [comment] 2018-07-11 09:08
@zipzit Thanks! If I'm reading the log right, it seems like the command being run that fails is:

```
/usr/bin/env ios-deploy --id 5e48115b466e0b05a8fb6a934a06355074051403 --bundle build/ios/iphoneos/Runner.app --no-wifi --justlaunch --args --enable-dart-profiling --start-paused --enable-checked-mode
```

So I suspect if you try running this command directly it should fail in the same way? (You may need to try the normal build first to ensure the build folder is in the correct state).

If so, you could try adding `--verbose` to that command (https://github.com/ios-control/ios-deploy#usage) which may give more detailed output about what it's doing that might help identify why Python seems broken in there (but not from your shell normally).

**Comment by zipzit** [comment] 2018-07-11 17:12
@DanTup   Did the command line run.  

- Navigate to directory of interest.  
- carefully remove the app from the iphone before each deployment test.
 - Attempted to run $ `/usr/bin/env ios-deploy --id 5e48115b466e0b05a8fb6a934a06355074051403 --bundle build/ios/iphoneos/Runner.app --no-wifi --justlaunch --args --enable-dart-profiling --start-paused --enable-checked-mode --verbose` . That line is a fail, shell responds with:
`ios-deploy: unrecognized option '--start-paused' `   (Remove that option, run again)
`ios-deploy: unrecognized option '--enable-checked-mode' `(Remove that option, too...)
 - $ `/usr/bin/env ios-deploy --id 5e48115b466e0b05a8fb6a934a06355074051403 --bundle build/ios/iphoneos/Runner.app --no-wifi --justlaunch --args --enable-dart-profiling  --verbose `

[CLI_flutter_test.txt](https://github.com/flutter/flutter/files/2185493/CLI_flutter_test.txt)

Next test:

- $ `pyenv install 2.7.15`
- $` pyenv global 2.7.15`
- $ `/usr/bin/env ios-deploy --id 5e48115b466e0b05a8fb6a934a06355074051403 --bundle build/ios/iphoneos/Runner.app --no-wifi --justlaunch --args --enable-dart-profiling  --verbose `

[CLI_flutter_test2.txt](https://github.com/flutter/flutter/files/2185511/CLI_flutter_test2.txt)


The upload seems successful in both python versions.  Perhaps the issue generating the `weakref` errors are the two run arguments `--start-paused` and `--enable-checked-mode` ?? Is that line generated by Flutter or perhaps by VSCode?

**Comment by DanTup** [comment] 2018-07-12 07:03
Ah, there's a subtle difference you can't tell from the log. The string `--enable-dart-profiling --start-paused --enable-checked-mode --verbose` is all being passed as a single arg, but the display of it doesn't make this clear. So to run the command the same from the terminal you'd need to quote those args, something like:

    /usr/bin/env ios-deploy --id 5e48115b466e0b05a8fb6a934a06355074051403 --bundle build/ios/iphoneos/Runner.app --no-wifi --justlaunch --args '--enable-dart-profiling --start-paused --enable-checked-mode'

That will result in the args all being passed through to the app, rather than being interpreted by ios-deploy. That said, I don't think it's making any difference for what we were looking at here; I think you'll see the same results if you run that with them (though it's worth trying to eliminate them).

Unfortunately, that verbose logging doesn't look much better; I can't see any obvious difference in the working/broken one (besides the crash).

Btw, just to clarify, is this always broken when you run via Flutter, or only within VS Code?

**Comment by zipzit** [comment] 2018-07-12 15:05
As you thought, the test with the --arg and quotes in bash shell was fully functional, no real change to feedback.  There were no `ios-deploy: unrecognized option` errors or warnings.

> Btw, just to clarify, is this always broken when you run via Flutter, or only within VS Code?

`Broken`?  What does that word mean?  To me, `broken` means absolutely non-functional.  In this case when ever I push an app to physical ios device (iphone) I get an error message that looks like this.  

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:8100/ws
Exited (sigterm)
```

The app arrives on my phone, and works as intended.  I wouldn't call it `broken`.  It's fully functional.  The only issue I'm seeing is the mystery `weakref` error message.  I would not call what I'm seeing a "severe crash"; what I'm seeing is a minor inconvenience.  Note: I'm not the originator of this issue... merely a "me, too".  

And to answer your question, I'm only seeing the above error message within VS code push to device (debug console). There is no `weakref` error when running from the bash command line interpreter.  I'm curious.. If I downloaded the IntelliJ Android IDE and ran the same flutter program there would I see the same 'weakref' error?  (ouch. How long is it going to take me to learn the Android tooling?)

**Comment by DanTup** [comment] 2018-07-12 16:38
Oh, I see - I misunderstood and thought it didn't work when you saw that error message.

If you're only seeing the message when run from within VS Code, I'm sure it's PATH-related. Try running `which python`, `which ios-deploy`, `which xcodebuild` (and anything else that might be involved) both inside and outside VS Code to see if any of them are being run from different locations.

**Comment by DanTup** [comment] 2018-07-12 19:47
I'm not sure, but it's possible https://github.com/flutter/flutter/pull/19281 might affect this; it's going to change the PATH when `ios-deploy` is invoked. Maybe worth testing on the `master` channel.

**Comment by zipzit** [comment] 2018-07-12 20:55
Terminal inside VS Code:
```
$ which python
/Users/userName/.pyenv/shims/python
$ which ios-deploy
/usr/local/bin/ios-deploy
$ which xcodebuild
/usr/bin/xcodebuild
```

Systems Bash Terminal
```
$ which python
/Users/userName/.pyenv/shims/python
$ which ios-deploy
/usr/local/bin/ios-deploy
$ which xcodebuild
/usr/bin/xcodebuild

```
I'm seeing the same error message when I run via `code .`

**Comment by DanTup** [comment] 2018-07-16 09:11
So back on beta, your issue is solved? That's a bit strange, but I guess not a bad thing.

@sahil311289 this issue got somewhat side-tracked. Are you still having the original issue you reported here?

**Comment by barcellos** [comment] 2018-07-17 21:59
I'm not sure about this, but when I disabled the new option available on iOS 11.4.1 (This option is under Settings > Touch Id & Passcode > USB Accessories or Settings > Face Id & Passcode). After this, I can now get enabled Network option on Xcode (Devices & Simulators > Connect via network). Maybe this is the solution.

**Comment by DanTup** [comment] 2018-07-18 12:09
@barcellos What happens if you don't enable that setting? Based on https://github.com/flutter/flutter/issues/15072#issuecomment-394406976 I get the impression debugging over WiFi is disabled; but I would expect it to result in a reasonable failure, not just a network exception.

**Comment by DanTup** [comment] 2018-07-18 12:10
Also see: https://github.com/flutter/flutter/issues/10602

**Comment by DanTup** [comment] 2018-07-30 15:04
Is anyone here still having this issue that is not caused by WiFi debugging or a proxy?

**Comment by jianggaocheng** [comment] 2018-08-03 02:07
@DanTup ,
I have this issue even when I disabled WiFi debugging, and ensure localhost is in the NO_PROXY,
This is strange because sometimes it works, and sometimes it not work.
I need to exec ``` flutter run ``` many times when I want to start the app

**Comment by DanTup** [comment] 2018-08-13 16:01
@jiajiabingcheng There were a few issues mixed up here. Which are you seeing - the error in the issue title? If so, can you try this:

- If you take the `/ws` off the end of the url in the error (eg. `http://127.0.0.1:8100/`) and paste it into your browser, does anything load?

**Comment by jianggaocheng** [comment] 2018-08-14 01:16
@DanTup 
I find that when I see the ```HttpException```, I can just disconnect the connection of my iPhone and reconnect it. Then I can successfully connect in flutter.
Maybe something happened after I connect my iPhone

**Comment by DanTup** [comment] 2018-08-20 13:10
@jianggaocheng What happens if you opening in your browser right after getting the exception (see above about removing `/ws` off the url).

**Comment by js1972** [comment] 2018-09-10 02:44
Simply turning off wifi debugging for my phone fixed the issue for me... (on beta channel). The issue only seems to happen in apps using method channels for me.

**Comment by DanTup** [comment] 2018-09-12 01:40
@sahil311289 @jianggaocheng please let us know if you can still reproduce this (and on the current beta/dev/master).

**Comment by jianggaocheng** [comment] 2018-09-12 01:49
@DanTup The problem seems gone when I use the lastest version of dev channel

**Comment by Sonius94** [comment] 2018-09-12 12:04
@DanTup I am new to this issue but I have the problem for about 2 weeks now. Today I still have the problem on latest version of dev channel (0.8.2). Here a flutter doctor summary of my setup:

[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.6 17G65, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)

• No issues found!

**Comment by DanTup** [comment] 2018-09-12 17:05
@Sonius94 Do you have a proxy and/or WiFi debugging enabled? It seems like a lot of these issues are resolved by disabling WiFi debugging and/of adding localhost/127.0.0.1 to the `NO_PROXY` environment variable. Let me know if either of these work.

**Comment by Hypercruse** [comment] 2018-10-07 17:10
Got the same error over here, WiFi debugging is disabled and i do not use a proxy
`Starting Xcode build...
Xcode build done.
Installing and launching...
5.1.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.1.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1029/ws`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] Connected devices (2 available)

• No issues found!

**Closed** 2018-10-07 18:03 UTC
Labels: severe: crash, tool, waiting for customer response, ⌺‬ platform-ios

**Comment by DanTup** [comment] 2018-10-07 19:37
@Hypercruse Please try [opening in a browser as mentioned here](https://github.com/flutter/flutter/issues/19056) and post what you get.

**Comment by Hypercruse** [comment] 2018-10-08 12:01
@DanTup "website is unavailable. 127.0.0.1 has refused the connection. ERR_CONNECTION_REFUSED"

**Comment by DanTup** [comment] 2018-10-08 13:03
@Hypercruse If you create a simple Dart script, for ex.:

```dart
main() {
  print("test");
}
```

And then run it like:

```
dart --observe --pause_isolates_on_start test.dart
```

It should spit out a similar link - if you copy/paste that into your browser, does that one work?

**Comment by Hypercruse** [comment] 2018-10-09 09:31
@DanTup Yes that one leads me to the observatory > vm@ws://127.0.0.1:8181/ws

**Comment by javen123** [comment] 2018-10-10 16:13
I am having the same issue.  I can run the project from the terminal to my connected device (iOS) simply with flutter run.  So the issue, IMO, must be with the debugger connection from VS to device. When running from debug in the console it gives me the 'Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1040/ws'. Not sure how to resolve as I'm a newb with VSE.

**Comment by DanTup** [comment] 2018-10-10 16:18
@javen123 Do you have WiFi debugging enabled, or have a proxy? (see above for comments about these).

As a workaround while we figure this out, if you want to run from VS Code without the debugger, there's a `Start Without Debugging` option (you may also be able to add `noDebug: true` to `launch.json` to always run this way; though I haven't tested it).

**Comment by g-balas** [comment] 2018-10-18 14:28
Same here, android studio, everything up-to-date

**Comment by Sonius94** [comment] 2018-10-18 14:45
I was able to find out that I had an issue in my native code. In AppDelegates function didFinishLaunchingWithOptions I created a class that leaded to shut down my app. The error code I got in Android Studio was this HttpException. I do not know why. I found it out when I used os_log to see which parts of my native code I can reach without any problems.

**Comment by Sonius94** [comment] 2018-10-25 12:31
I was having the issue again today. I watched the logs with console.logs. The only log entry I got is:

HTHangEventCreate: HangTracing is disabled. Not creating a new event.

**Comment by recoilme** [comment] 2019-02-20 12:17
I think it's timeout error. When i start [websocket](https://github.com/gobwas/ws-examples) server with 10ms io timeout i see this error 90% of time. No error then 1000ms timeout.  Try starting without debugging - the same error. And from time to time I see broadcast messages not right after send, but in the next packet, after next send
Looks like Dart just very slow and buggy.

**Comment by JGTM2019** [comment] 2019-03-12 16:32
Trying reconnect the device sometimes fix the problem. Remember to set/check "NO_PROXY=127.0.0.1,localhost" always.

**Comment by tanpengsccd** [comment] 2019-03-14 03:41
> Trying reconnect the device sometimes fix the problem. Remember to set/check "NO_PROXY=127.0.0.1,localhost" always.

i tried  ``` export NO_PROXY=127.0.0.1,localhost```  in terminal ,it work ,thx

**Comment by keitoro** [comment] 2019-03-21 10:59
> > Trying reconnect the device sometimes fix the problem. Remember to set/check "NO_PROXY=127.0.0.1,localhost" always.
> 
> i tried ` export NO_PROXY=127.0.0.1,localhost` in terminal ,it work ,thx

seems to be working, thanks.

**Comment by Pardeep03315** [comment] 2019-04-10 13:01
> Trying reconnect the device sometimes fix the problem. Remember to set/check "NO_PROXY=127.0.0.1,localhost" always.


> Have been stuck for days on this. iOS app crashes on launch.
> 
> ```
> Launching lib/main.dart on Sahil’s iPhone in debug mode...
> Automatically signing iOS for device deployment using specified development team in Xcode project: Q48Y4UFKL8
> Starting Xcode build...
> Xcode build done.
> Installing and launching...
> 5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
> 5.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
> Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws
> ```
> Flutter doctor:
> 
> ```
> Running flutter doctor...
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-IN)
> [!] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
>     ✗ Android license status unknown.
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
> [✓] Android Studio (version 3.1)
> [✓] IntelliJ IDEA Community Edition (version 2018.1.5)
> [✓] VS Code (version 1.23.1)
> [✓] Connected devices (2 available)
> 
> ! Doctor found issues in 1 category.
> Process finished with exit code 0
> ```

getting same issue what will be solution

**Comment by DanTup** [comment] 2019-04-10 13:27
@Pardeep03315 since this issue is long closed, please open a new issue and include the full output of `flutter doctor -v` and `flutter run -v` with the error and @ mention me on the issue.

(if you haven't already though, please try `NO_PROXY` and disabling WiFi debugging as mentioned above if either apply)

**Comment by jerry-lllman** [comment] 2019-06-07 21:51
I'll just change the simulator，like **Nox**

**Comment by duckythegoose** [comment] 2019-06-12 19:11
in my case it helped to remove the app from the device (uninstall) and then try to execute `flutter run` again. Also make sure that, if you work on a real device and the deploy process takes a while, that the screen doesn't turn off.

**Comment by dustinrwh** [comment] 2019-06-14 23:33
Make sure to check the Android API version of your emulator. I have issues on Q, but everything works fine on an emulator with Android API 28.

**Comment by unrealnerd** [comment] 2019-06-15 07:38
``

> Make sure to check the Android API version of your emulator. I have issues on Q, but everything works fine on an emulator with Android API 28.

Indeed it works on API 28. Thanks @dustinrwh

**Comment by anhodev** [comment] 2019-06-15 10:22
That's is an API Level issue. You should switch to use API 28 instead of API 29 for you emulator.

**Comment by romdj** [comment] 2019-06-21 14:55
YES! thanks a lot!
Encountered the same issue with API 29, solved by going back to 28

**Comment by afucher** [comment] 2019-07-02 20:50
Have the same issue with API26

**Comment by Hixie** [comment] 2019-07-02 22:28
@afucher Closed bugs don't come up in our triage meetings. If you're seeing something wrong, please file a new bug starting at https://github.com/flutter/flutter/issues/new/choose and fill out all the information the template suggests. That's the best way to get an issue onto our radar.

**Comment by eXamadeus** [comment] 2019-07-23 01:39
I made a new Issue related to the problems with API 29 and having to downgrade to API 28.

#36723

**Comment by mdarifmustafa** [comment] 2019-10-21 01:02
yesterday night I faced this issue with flutter app because I tried to change the package name from main Manifest xml file, like com.example.appname to com.orgname.appname and later when I revert back, this issue gone.

**Comment by williamjnrkdd** [comment] 2020-02-19 20:47
I also had this issue when i was trying to add a splash screen to the android app through the launch_backgrgound.xml . the issue was the resolution. it was too high so the images memory footprint exploded and caused the app to crash hence the reason for this error. so just resize your image using a site called nativescript image builder so i got the ldpi,mdpi and all the rest and it worked fine for me.

**Comment by scullabyte** [comment] 2020-04-13 17:17
I get this just about every other time I build on VSCode. Running on iPhone directly.

Verbose logs include:
```
Application launched on the device. Waiting for observatory port.

Attempting to forward device port 54257 to host port 1025
flutter/bin/cache/artifacts/usbmuxd/iproxy
```
And finally:
```
[+1010 ms] Forwarded port ForwardedPort HOST:1029 to DEVICE:54257
[   +3 ms] Installing and launching... (completed in 61.4s)
[  +10 ms] Connecting to service protocol: http://127.0.0.1:1029/
[ +114 ms] Fail to connect to service protocol: http://127.0.0.1:1029/: HttpException: , uri = http://127.0.0.1:1029/ws
```

Still happens even after I do `flutter clean`, disconnect, restart VSCode and reconnect/build.


Here is my `flutter doctor -v`:

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en)
    • Flutter version 1.17.0 at /Users/admin/flutter
    • Framework revision d3ed9ec945 (7 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • Kevin’s iPhone    • 16e0be0d98a45594d66fce5bc03767078a0adaf9 • ios            • iOS 13.3.1
    • iPhone 11 Pro Max • 035D9994-BA87-4A94-AA51-94795CF44719     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome            • chrome                                   • web-javascript • Google Chrome 81.0.4044.92
    • Web Server        • web-server                               • web-javascript • Flutter Tools

• No issues found!
```



Only thing that works is a fresh build in XCode, but with firebase this takes at least 5 minutes, which means 10 minutes every time I want to start developing.

Any help would be greatly appreciated on this.
