### ISSUE TITLE
NoSuchMethodError: The method 'open' was called on null. getting during using razorpay

### ISSUE THREAD

**Issue by PanchaiNathan** [flutter/flutter#78510] opened 2021-03-18 05:37 UTC
payWithRazor(total_amt, qty) async {
    print("Razorpay");
    final prefs = await SharedPreferences.getInstance();
    Map<String, dynamic> options;
    options = {
      "description": 'Thanks for placing order!',
      "image": baseImage,
      "currency": "INR",
      "key": "rzp_live_vwdPSYlBoyrXul", // your Key Id from Razorpay dashboard
      "amount": total_amt,
      "name": 'Goodway',
      "prefill": {
        "email": '',
        "contact": prefs.getString("user_name"),
        "name": ''
      },
      //Color: '#F37254'
    };
    if (options != null) {
      print("hhhhhh");
      try {
        razorpay.open(options);

        print(options);
      } catch (e) {
        print(e.toString());
      }
    } 
  }

This is my razorpay coding.

**Comment by pedromassangocode** [comment] 2021-03-18 08:32
Hi @PanchaiNathan 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository.
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-18 08:32 UTC
Labels: in triage
