### ISSUE TITLE
Flutter Web throws an error when loading JPEG network images

### ISSUE THREAD

**Issue by LebenNNA** [flutter/flutter#144127] opened 2024-02-26 08:25 UTC
### Steps to reproduce

intel mac use Chrome
Loading JPEG images with Image.network results in an error

### Expected results

show the pic

### Actual results

screen white

### Code sample

<details open><summary>Code sample</summary>

```dart
Image.network(xxx.jpeg)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![img_v3_028e_16972175-3eab-40c1-8da7-50730b36159g](https://github.com/flutter/flutter/assets/15353971/cb731213-9db8-4dd9-afd4-ad63c9705c6a)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-02-26 10:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/140504

**Closed by danagbemava-nc** 2024-02-26 10:02 UTC
Labels: in triage

**Comment by oliverbytes** [comment] 2024-03-01 09:53
Indeed caused by network-based image
