### ISSUE TITLE
Now I have a requirement for Bluetooth communication

### ISSUE THREAD

**Issue by duoshine** [flutter/flutter#19401] opened 2018-07-16 09:43 UTC
Now I have a requirement for Bluetooth communication, so I should call the native api to complete the Bluetooth communication. I have to use the Android and IOS APIs to get the job done. But I am an Android developer

**Comment by zoechi** [comment] 2018-07-16 11:17
This is a duplicate of #430
There is the https://pub.dartlang.org/packages/flutter_blue package that provides Bluetooth communication for Flutter.

**Closed by zoechi** 2018-07-16 11:17 UTC
