### ISSUE TITLE
basic_material_app_ios__compile_debug_full_compile_millis regression...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49890] opened 2020-01-31 16:57 UTC
Looks like it's been creeping up. I don't think that https://github.com/flutter/flutter/pull/49835 is the culprit, because it drops after the roll. Maybe it needs to be rebaselined?

**Comment by Hixie** [comment] 2020-02-03 22:01
Dupe of https://github.com/flutter/flutter/issues/50014

**Closed by Hixie** 2020-02-03 22:01 UTC
Labels: engine, severe: performance, severe: regression, ⚠ TODAY
