### ISSUE TITLE
[flutter_tools] merge conflict during flutter upgrade

### ISSUE THREAD

**Issue by zenkog** [flutter/flutter#58564] opened 2020-06-03 05:04 UTC
## Steps to Reproduce
I really not sure is this the problem specific to me or with Flutter. Maybe I miss something. 
But I was on dev channel and all works fine. 
Then I need to develop web app, thus I switched to beta channel. 
So I run in terminal:
```
flutter channel beta
flutter upgrade
```

But then I got these results:

```
Downloading Dart SDK from Flutter engine c9506cb8e93e5e8879152ff5c948b175abb5b997...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  213M  100  213M    0     0  5975k      0  0:00:36  0:00:36 --:--:-- 4827k
Building flutter tool...
Upgrading Flutter from /Volumes/ZK-REGEN/Applications/flutter...
Auto-merging packages/flutter_tools/test/integration.shard/downgrade_upgrade_integration_test.dart
CONFLICT (content): Merge conflict in packages/flutter_tools/test/integration.shard/downgrade_upgrade_integration_test.dart
Auto-merging packages/flutter_tools/test/general.shard/version_test.dart
CONFLICT (content): Merge conflict in packages/flutter_tools/test/general.shard/version_test.dart
Auto-merging packages/flutter_tools/test/general.shard/runner/flutter_command_runner_test.dart
CONFLICT (content): Merge conflict in packages/flutter_tools/test/general.shard/runner/flutter_command_runner_test.dart
Removing packages/flutter_tools/test/general.shard/package_uri_mapper_test.dart
Removing packages/flutter_tools/test/general.shard/build_system/filecache_test.dart
Auto-merging packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart
CONFLICT (content): Merge conflict in packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart
Auto-merging packages/flutter_tools/test/commands.shard/hermetic/version_test.dart
CONFLICT (content): Merge conflict in packages/flutter_tools/test/commands.shard/hermetic/version_test.dart
Removing packages/flutter_tools/test/commands.shard/hermetic/unpack_test.dart
Removing packages/flutter_tools/templates/plugin/.idea/libraries/Flutter_for_Android.xml.tmpl
Removing packages/flutter_tools/templates/module/common/.idea/libraries/Flutter_for_Android.xml.tmpl
Removing packages/flutter_tools/templates/app/windows.tmpl/win32_window.cc
Removing packages/flutter_tools/templates/app/windows.tmpl/resources/app_icon.ico.img.tmpl
Removing packages/flutter_tools/templates/app/windows.tmpl/main.cpp
Removing packages/flutter_tools/templates/app/.idea/libraries/Flutter_for_Android.xml.tmpl
Auto-merging packages/flutter_tools/lib/src/version.dart
CONFLICT (content): Merge conflict in packages/flutter_tools/lib/src/version.dart
Auto-merging packages/flutter_tools/lib/src/commands/version.dart
CONFLICT (content): Merge conflict in packages/flutter_tools/lib/src/commands/version.dart
Auto-merging packages/flutter_tools/lib/src/commands/upgrade.dart
CONFLICT (content): Merge conflict in packages/flutter_tools/lib/src/commands/upgrade.dart
Removing packages/flutter_tools/lib/src/commands/unpack.dart
Removing packages/flutter/test/material/control_list_tile_test.dart
Removing dev/bots/debug_smoke_ftl.sh
Automatic merge failed; fix conflicts and then commit the result.
```

The point is the last line says: 

> Automatic merge failed; fix conflicts and then commit the result.

Then I did:
```
git clean -xfd`
git status
```

And I found there were some unmerged paths:

```
Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   packages/flutter_tools/lib/src/commands/upgrade.dart
	both modified:   packages/flutter_tools/lib/src/commands/version.dart
	both modified:   packages/flutter_tools/lib/src/version.dart
	both modified:   packages/flutter_tools/test/commands.shard/hermetic/version_test.dart
	both modified:   packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart
	both modified:   packages/flutter_tools/test/general.shard/runner/flutter_command_runner_test.dart
	both modified:   packages/flutter_tools/test/general.shard/version_test.dart
	both modified:   packages/flutter_tools/test/integration.shard/downgrade_upgrade_integration_test.dart
```

Hence, I tried to do `git add <paths>` then the unmerged messages were gone.
After that when I do `flutter upgrade`

This is the result:

> Downloading Dart SDK from Flutter engine ef9215ceb2884ddf520d321bcd822d1461330876...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  220M  100  220M    0     0  4394k      0  0:00:51  0:00:51 --:--:-- 6955k
Building flutter tool...
packages/flutter_tools/lib/src/commands/upgrade.dart:230:1: Error: The '===' operator is not supported.
=======
^
packages/flutter_tools/lib/src/commands/upgrade.dart:230:4: Error: The '===' operator is not supported.
=======
   ^
packages/flutter_tools/lib/src/commands/version.dart:91:1: Error: The '===' operator is not supported.
=======
^
packages/flutter_tools/lib/src/commands/version.dart:91:4: Error: The '===' operator is not supported.
=======
   ^
packages/flutter_tools/lib/src/version.dart:707:1: Error: The '===' operator is not supported.
=======
^
packages/flutter_tools/lib/src/version.dart:707:4: Error: The '===' operator is not supported.
=======
   ^
packages/flutter_tools/lib/src/version.dart:721:1: Error: The '===' operator is not supported.
=======
^
packages/flutter_tools/lib/src/version.dart:721:4: Error: The '===' operator is not supported.
=======
   ^
packages/flutter_tools/lib/src/version.dart:751:1: Error: The '===' operator is not supported.
=======
^
packages/flutter_tools/lib/src/version.dart:751:4: Error: The '===' operator is not supported.
=======
   ^

Then I'm stuck.

Below is my flutter doctor -v

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.17.0 at /Applications/flutter
    • Framework revision d3ed9ec945 (8 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Applications/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Applications/Android/sdk
    • Java binary at: /Applications/AndroidStudio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1-dev.5
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • iPho • b3ebbe92d78acd5xxxxxxxxefecf25da9ac75d28 • ios            • iOS 13.4.1
    • iPhone X   • 1A4XXXXXXX-E046-478E-BEFF3AB     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome     • chrome                                   • web-javascript • Google Chrome 83.0.4103.61
    • Web Server • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

Thank you

**Comment by iapicca** [comment] 2020-06-03 07:57
Hi @zenkog 
could you please provide your
`flutter upgrade --force --verbose`
If the logs are too long, you may attach them as txt file.
thank you

**Comment by zenkog** [comment] 2020-06-03 08:06
Here it is:

```
[  +17 ms] executing: [/Volumes/ZK-REGEN/Applications/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] d3ed9ec945f8869f0e136c357d0c2a6be2b60c98
[   +2 ms] executing: [/Volumes/ZK-REGEN/Applications/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +24 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.17.0-dev.3.1-0-gd3ed9ec945
[  +95 ms] executing: [/Volumes/ZK-REGEN/Applications/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +7 ms] executing: sw_vers -productName
[  +25 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +65 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +89 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[ +101 ms] executing: [/Volumes/ZK-REGEN/Applications/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +47 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.17.0-dev.3.1-0-gd3ed9ec945
[   +8 ms] executing: [/Volumes/ZK-REGEN/Applications/flutter/] git rev-parse @{u}
[  +79 ms] 2738a1148ba6c9a6114df62358109407c3ef2553
[        ] executing: [/Volumes/ZK-REGEN/Applications/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Volumes/ZK-REGEN/Applications/flutter/] git ls-remote --get-url origin
[  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +10 ms] Upgrading Flutter from /Volumes/ZK-REGEN/Applications/flutter...
[   +3 ms] executing: [/Volumes/ZK-REGEN/Applications/flutter/] git pull --ff
[  +43 ms] error: You have not concluded your merge (MERGE_HEAD exists).
[   +3 ms] hint: Please, commit your changes before merging.
[   +2 ms] fatal: Exiting because of unfinished merge.
[  +36 ms] "flutter upgrade" took 565ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      UpgradeCommandRunner.attemptFastForward (package:flutter_tools/src/commands/upgrade.dart:244:7)
<asynchronous suspension>
#2      UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:135:40)
<asynchronous suspension>
#3      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:85:13)
#4      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:60:27)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#6      _rootRunUnary (dart:async/zone.dart:1192:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#12     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#13     _rootRun (dart:async/zone.dart:1184:13)
#14     _CustomZone.run (dart:async/zone.dart:1077:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by kami-mehar38** [comment] 2020-06-04 16:27
As @zenkog stated the process of reproduction of this issue which is not in my case because i didn't try to switch channel instead i just tried to upgrade flutter version and this issue occurred as stated by @zenkog .
Currently if i try to run 'flutter upgrade', the process of upgrading resumes from Building flutter tool and then it prints the following error on console: error The '===' operator is not supported

**Comment by zenkog** [comment] 2020-06-04 22:47
> I was not able to reproduce this by going from dev -> beta

Did you try to do flutter upgrade?

**Comment by kami-mehar38** [comment] 2020-06-05 07:22
> I was not able to reproduce this by going from dev -> beta

Did you try to upgrade flutter?

**Comment by scugn1zz0** [comment] 2020-06-05 19:02
I am having the same issue right now, switched to beta and tried to upgrade with no success and now I cannot switch back to stable either, I'm stuck

**Comment by kami-mehar38** [comment] 2020-06-05 19:07
Try following steps:
Close the IDE
Delete the current flutter sdk
Download fresh copy of flutter sdk and paste it in the same previous
location of sdk
Now run the project again

Thanks
Regards,

Kamran Ramzan
Software Engineer
kamran@ingizly.com

**Comment by 1-2-ka-4-4-2-ka-1** [comment] 2020-06-07 06:44
I am facing the same issue!

**Comment by kami-mehar38** [comment] 2020-06-07 07:57
> Try following steps: 
Close the IDE
Delete the current flutter sdk 
Download fresh copy of flutter sdk and paste it in the same previous location of sdk 
Now run the project again 
Thanks Regards,
 Kamran Ramzan
 Software Engineer
 kamran@ingizly.com

@1-2-ka-4-4-2-ka-1 have your tried the above mentioned steps? After following the steps, run flutter clean

**Comment by magnatronus** [comment] 2020-06-07 10:17
I also had the same issue (I have had Flutter installed since it was first in beta)

Install OS: MAC Catalina
Install Dir ~/Library/flutter

First delete the ~/Library/flutter dir
Download the latest stable version of Flutter
Install into the same directory

This fixed the issue for me and I can now swap between the beta and stable channels.

**Comment by 1-2-ka-4-4-2-ka-1** [comment] 2020-06-11 06:30
> > Try following steps:
> > Close the IDE
> > Delete the current flutter sdk
> > Download fresh copy of flutter sdk and paste it in the same previous location of sdk
> > Now run the project again
> > Thanks Regards,
> > Kamran Ramzan
> > Software Engineer
> > [kamran@ingizly.com](mailto:kamran@ingizly.com)
> 
> @1-2-ka-4-4-2-ka-1 have your tried the above mentioned steps? After following the steps, run flutter clean

Thanks, but I was able to solve by changing the Gradle version in the wrapper, this issue has got nothing to do with flutter, but  sadly it appears when starting up with flutter.

**Comment by kami-mehar38** [comment] 2020-06-11 11:01
> Thanks, but I was able to solve by changing the Gradle version in the wrapper, this issue has got nothing to do with flutter, but sadly it appears when starting up with flutter.

@1-2-ka-4-4-2-ka-1 welcome, issue is resolved anyway

**Comment by christopherfujino** [comment] 2020-06-23 21:11
@zenkog do you by any chance know what version of dev you were on?

**Comment by christopherfujino** [comment] 2020-06-23 23:09
This was fixed by https://github.com/flutter/flutter/pull/54987. Unfortunately, for users already on flutter previous to the fix landing (`1.18.0-6.0.pre`) they will still be susceptible to this.

**Closed by christopherfujino** 2020-06-23 23:09 UTC
Labels: P4, severe: crash, tool

**Comment by MrCsabaToth** [comment] 2020-06-26 05:22
I'm with version 1.17.0 and can steadily reproduce this with my copy if anyone is interested before I'll do a clean install.
![Screenshot_2020-06-25_20-52-55](https://user-images.githubusercontent.com/744949/85823481-680aaf80-b732-11ea-8e85-4cf6351cbfe8.png)

**Comment by zenkog** [comment] 2020-06-26 07:10
> @zenkog do you by any chance know what version of dev you were on?

I'm pretty sure it was 1.19 pre. But now there is no way I can check which 1.19.x is it. Because I installed a fresh copy.

**Comment by christopherfujino** [comment] 2020-06-26 18:29
@MrCsabaToth Thanks for the offer! In this case we fixed the problem upstream, so you can do a clean install. And my apologies for this bad experience. I had assumed that `git pull` would exit with an error if it couldn't cleanly fast forward, but instead it would fall back to trying to merge.

**Comment by MrCsabaToth** [comment] 2020-06-26 19:18
@christopherfujino No worries. As a software engineer I feel you. I've had wrestling matches with `git` almost as good ones as with `CSS` for example. 
![unnamed](https://user-images.githubusercontent.com/744949/85893117-151f0f80-b7a7-11ea-9364-98ec6c117cb7.gif)

**Comment by banishangural** [comment] 2020-11-03 07:57
Deleting and downloading the fresh flutter SDK solved the issue
