### ISSUE TITLE
"Missing Push Notification Entitlement" email from Apple even though not using push

### ISSUE THREAD

**Issue by tobinharris** [flutter/flutter#14182] opened 2018-01-19 12:33 UTC
## Steps to Reproduce

- Create a Material scaffold flutter app that **does not** use push. 
- Make sure `aps-environment` is not set. 
- And that the App ID settings on the Developer portal do not have Push enabled. 
- Build for iOS
- Submit a build to Apple TestFlight. 
- You'll get an email warning you that you haven't set your `aps-environment` entitlement. 
- It's not going to get the app rejected, but it's annoying.

Is there a dependency in Flutter that is causing this? We can't find a trace of APNS usage in our app. Thanks!

Tobin

**Comment by mit-mit** [comment] 2018-01-19 13:31
cc @xster @cbracken

**Comment by tobinharris** [comment] 2018-01-19 14:44
Thanks @mit-mit, I'll monitor from here rather than on our email thread :)

**Comment by mit-mit** [comment] 2018-01-24 22:02
kind reminder @xster @cbracken

**Comment by xster** [comment] 2018-01-27 02:37
cc @mravn-google 

Implementing methods like 
didRegisterForRemoteNotificationsWithDeviceToken and didReceiveRemoteNotification etc in the app delegate in https://github.com/flutter/engine/pull/3645 might cause it

**Comment by mravn-google** [comment] 2018-02-05 13:56
That sounds right. The solution is tracked here: https://github.com/flutter/flutter/issues/9984.

**Comment by aubykhan** [comment] 2018-02-21 15:23
Facing the same issue. Fortunately, Apple doesn't stop you to submit the app for review even after warning about missing push notification entitlement.

**Comment by xster** [comment] 2018-10-24 02:00
Closing since it's a dupe of #9984

**Comment by emailsubjekt** [comment] 2019-07-22 22:16
Don't close this, I'm still getting this error and I'm not using push notifications at all in my app!!!!! !

ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

Best regards,

The App Store Team

**Comment by edwinludik** [comment] 2019-08-04 18:53
> Don't close this, I'm still getting this error and I'm not using push notifications at all in my app!!!!! !
> 
> ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
> 
> Best regards,
> 
> The App Store Team

dupe = duplicate, https://github.com/flutter/flutter/issues/9984 is still open. Follow this issue.

**Comment by bradyt** [comment] 2021-03-01 22:51
That issue is closed, with no response as to why it was closed, this issue is more specific, please reopen.

**Closed** 2021-03-01 23:29 UTC
Labels: p: framework, platform-ios, platform-mac, tool

**Comment by dpedrinha** [comment] 2021-03-18 04:37
I'm getting this warning too and I'm not using push.
I'm using firebase Core, Auth, dynamic links, firestore and analytics

**Comment by bjorge** [comment] 2021-03-19 16:32
I'm getting the warning too. I'm using  firebase_core and cloud_firestore.
