### ISSUE TITLE
Unable to call instatiateImageCodec from an isolate.

### ISSUE THREAD

**Issue by SByer** [flutter/flutter#27557] opened 2019-02-05 18:59 UTC
## Steps to Reproduce

Use the Flutter 1.0 SDK + Android Studio and the attached file to demonstrate the problem.

[main.dart.tar.gz](https://github.com/flutter/flutter/files/2833334/main.dart.tar.gz)

When getting the test image on the isolate, an exception 'Method not found' is thrown with the stack trace:

instantiateImageCodec.<anonymous closure>
_futurize
instantiateImageCodec
getTestImage (main.dart:26)
<asynchronous gap>
_isolateGetTestImage (main.dart:43)
<asynchronous gap>
_isolateGetTestImage (main.dart:1)
_Closure.call
_startIsolate.<anonymous closure>
_Closure.call
_RawReceivePortImpl._handleMessage

## Logs

```
```

```
```

 flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /usr/local/google/home/scottbyer/Development/flutter
    • Framework revision 5391447fae (10 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /usr/local/google/home/scottbyer/Android/Sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-prerelease, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/google/home/scottbyer/Android/Sdk/
    • Java binary at: /opt/android-studio-with-blaze-3.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio-with-blaze-3.3
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio-with-blaze-3.2
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iot msm8x53 som • HUA01TKR • android-arm • Android 8.1.0 (API 27)

• No issues found!

**Comment by jonahwilliams** [comment] 2019-02-05 19:02
Duplicate of https://github.com/flutter/flutter/issues/10647

**Closed by jonahwilliams** 2019-02-05 19:02 UTC
