### ISSUE TITLE
The back button appears for a few moments while I replace a route with Navigator 2.0.

### ISSUE THREAD

**Issue by johynpapin** [flutter/flutter#67277] opened 2020-10-04 20:48 UTC
Hello everyone!

I'm trying to use the new Navigator like this :

```dart
Navigator(
  pages: [
    if (showSignIn)
      MaterialPage(
        key: ValueKey('SignIn'),
        child: SignIn(
          switchToSignUp: () {
            setState(() => showSignIn = false);
          },
        ),
      )
    else
      MaterialPage(
        key: ValueKey('SignUp'),
        child: SignUp(
          switchToSignIn: () {
            setState(() => showSignIn = true);
          },
        ),
      )
  ],
  onPopPage: (route, result) => route.didPop(result),
)
```
When `showSignIn` changes value, I want to switch from one screen to another. It works, but the back button appears for a few moments in the AppBar. Is this normal?

I tried on the master channel, but I had the same problem.

I imagined several solutions to solve this issue, but they seem a little strange to me:

- Put the same key on both pages.
- Create a single page (Authentication), and change widget according to `showSignIn` inside.

Thank you in advance.

**Comment by darshankawar** [comment] 2020-10-05 13:35
@johynpapin 
Please provide `flutter doctor -v` and a complete minimal code sample that we can copy paste and run in IDE to see the issue.
Thanks.

**Comment by johynpapin** [comment] 2020-10-05 16:56
Thank you very much for your prompt response!

Here is the `flutter doctor -v`:

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.131, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.23.0-8.0.pre.131 at /opt/flutter
    • Framework revision 8485580bb9 (il y a 22 heures), 2020-10-04 14:47:02 -0400
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/johynpapin/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

And here is the complete minimal code sample:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool showSignIn = true;

  void toggleShowSignIn() {
    setState(() => showSignIn = !showSignIn);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Navigator(
        pages: [
          if (showSignIn)
            MaterialPage(
              key: ValueKey('SignIn'),
              child: SimplePage(
                toggleShowSignIn: toggleShowSignIn,
                signedIn: !showSignIn,
              ),
            )
          else
            MaterialPage(
              key: ValueKey('Home'),
              child: SimplePage(
                toggleShowSignIn: toggleShowSignIn,
                signedIn: !showSignIn,
              ),
            )
        ],
        onPopPage: (route, result) => route.didPop(result),
      ),
    );
  }
}

class SimplePage extends StatelessWidget {
  const SimplePage({
    Key key,
    this.toggleShowSignIn,
    this.signedIn,
  }) : super(key: key);

  final Function() toggleShowSignIn;
  final bool signedIn;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(signedIn ? 'Home' : 'Sign In'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(signedIn ? 'You are signed in' : 'You are not signed in'),
            ElevatedButton(
              child: Text('Toggle showSignIn'),
              onPressed: toggleShowSignIn,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment] 2020-10-06 07:05
@johynpapin The back button is a default setting. If you don't want it to show upon toggle, you may set `automaticallyImplyLeading: false,`, that'll not show the appbar back button.

```
appBar: AppBar(
        automaticallyImplyLeading: false,
        title: Text(signedIn ? 'Home' : 'Sign In'),
      ),
```

I am going ahead and closing it, as it's not an issue. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by jacobaraujo7** [comment] 2020-10-31 16:25
@darshankawar 
I believe that the problem has not been solved.
When there is a replace route, canPop() becomes 'true' causing the back button to appear for a few milliseconds.
![prover](https://user-images.githubusercontent.com/4047813/97784326-7ce1ce80-1b7c-11eb-8c82-0757f95ecfe1.gif)

**Comment by jacobaraujo7** [comment] 2020-11-03 19:00
cc @chunhtai

**Comment by darshankawar** [comment] 2020-11-04 05:58
<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (5 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

</details>

**Comment by jacobaraujo7** [comment] 2020-11-05 02:24
@chunhtai Why ```markForReplace``` not exist in RouteTransitionRecord?
I believe that this would solve this bug

**Comment by chunhtai** [comment] 2020-11-05 16:59
@jacobaraujo7 if you want to replace B with A you can use B.markForComplete and A.markForAdd to achieve the same result

**Comment by jacobaraujo7** [comment] 2020-11-06 02:11
> @jacobaraujo7 if you want to replace B with A you can use B.markForComplete and A.markForAdd to achieve the same result

But the A.markForAdd wouldn't show the input animation, right?

**Comment by chunhtai** [comment] 2020-11-06 02:20
@jacobaraujo7 yes, replace do not show animation too. or are you talking about pushAndReplace? in that case you can do A.markForPush

**Comment by jacobaraujo7** [comment] 2020-11-06 02:41
cool! I'm studying Translate Delegate and I really didn't see anything wrong with the standard Delegate logic. I believe that Navigator.canPop() is True during the transition because there are actually 2 entryOverlay in the history.

**Comment by jacobaraujo7** [comment] 2020-11-24 20:42
Hello @chunhtai 
Any news?

**Comment by chunhtai** [comment] 2020-11-25 17:31
@jacobaraujo7 Sorry for the late reply, I am currently overwhelmed by some high priority issues. I will get to this issue by the end of the next week

**Comment by chunhtai** [comment] 2020-12-08 19:20
Finished investigating, this is a bug in route.canpop that it check whether the route is the first or not, it return false when the route is completed but still on the route stack, this cause it to return true for route.canpop.

I will put up a fix

**Closed** 2021-01-06 18:59 UTC
Labels: f: routes, found in release: 1.22, framework, has reproducible steps, passed first triage

**Comment by antoinepemeja** [comment] 2021-03-24 09:33
Hello,

I'm facing with this issue.

https://user-images.githubusercontent.com/752689/112286601-c3e77200-8c8b-11eb-9b81-970ff6cec281.mov

Flutter doctor: 
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-arm, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)
```

My sample code to reproduce: 
```dart
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'dart:async';

// Custom Object -> PageConfiguration

const String SplashPath = '/splash';
const String LoginPath = '/login';
const String ListItemsPath = '/list';
const String DetailsPath = '/details';

enum Pages {
  Splash,
  Login,
  List,
  Details,
}

class PageConfiguration {
  final String key;
  final String path;
  final Pages uiPage;

  const PageConfiguration(
      {@required this.key, @required this.path, @required this.uiPage});
}

const PageConfiguration SplashPageConfig = PageConfiguration(key: 'Splash', path: SplashPath, uiPage: Pages.Splash);
const PageConfiguration LoginPageConfig = PageConfiguration(key: 'Login', path: LoginPath, uiPage: Pages.Login);
const PageConfiguration ListItemsPageConfig = PageConfiguration(key: 'List', path: ListItemsPath, uiPage: Pages.List);
const PageConfiguration DetailsPageConfig = PageConfiguration(key: 'Details', path: DetailsPath, uiPage: Pages.Details);

// Router Delegate

class MyRouterDelegate extends RouterDelegate<PageConfiguration> with ChangeNotifier, PopNavigatorRouterDelegateMixin<PageConfiguration> {

  final List<Page> _pages = [];

  @override
  PageConfiguration get currentConfiguration => _pages.last.arguments as PageConfiguration;

  @override
  Widget build(BuildContext context) {
    return Navigator(
      key: navigatorKey,
      onPopPage: _onPopPage,
      pages: List.of(_pages),
    );
  }

  @override
  GlobalKey<NavigatorState> get navigatorKey => GlobalObjectKey<NavigatorState>(this);

  @override
  Future<void> setNewRoutePath(PageConfiguration configuration) {
    _pages.clear();
    addPage(configuration);
    return Future.value(null);
  }

  bool _onPopPage(Route<dynamic> route, result) {

    final didPop = route.didPop(result);
    if (!didPop) {
      return false;
    }

    _pages.remove(route.settings);

    notifyListeners();

    return true;
  }

  @override
  Future<bool> popRoute() {
    if (_pages.length > 1) {
      _removePage(_pages.last);
      return Future.value(true);
    }
    return Future.value(false);
  }

  void _removePage(MaterialPage page) {
    if (page != null) {
      _pages.remove(page);
    }
    notifyListeners();
  }

  void addPage(PageConfiguration pageConfig) {

    final shouldAddPage = _pages.isEmpty ||
        (_pages.last.arguments as PageConfiguration).uiPage !=
            pageConfig.uiPage;

    if (shouldAddPage) {
      switch (pageConfig.uiPage) {
        case Pages.Splash:
          _addPageData(SplashPage(), SplashPageConfig);
          break;
        case Pages.Login:
          _addPageData(LoginPage(), LoginPageConfig);
          break;
        case Pages.List:
          _addPageData(ListPage(), ListItemsPageConfig);
          break;
        case Pages.Details:
          _addPageData(DetailsPage(), DetailsPageConfig);
          break;
        default:
          break;
      }

      notifyListeners();
    }
  }

  void _addPageData(Widget child, PageConfiguration pageConfig) {
    _pages.add(
      _createPage(child, pageConfig),
    );
  }

  MaterialPage _createPage(Widget child, PageConfiguration pageConfig) {
    return MaterialPage(
        child: child,
        key: Key(pageConfig.key),
        name: pageConfig.path,
        arguments: pageConfig
    );
  }

  void replace(PageConfiguration newRoute) {
    if (_pages.isNotEmpty) {
      _pages.removeLast();
    }
    addPage(newRoute);
  }

  void setPath(List<MaterialPage> path) {
    _pages.clear();
    _pages.addAll(path);
    notifyListeners();
  }

  void replaceAll(PageConfiguration newRoute) {
    setNewRoutePath(newRoute);
  }

  void push(PageConfiguration newRoute) {
    addPage(newRoute);
  }

  void pushWidget(Widget child, PageConfiguration newRoute) {
    _addPageData(child, newRoute);
    notifyListeners();
  }
}

// Route Information Parser

class MyParser extends RouteInformationParser<PageConfiguration> {

  @override
  Future<PageConfiguration> parseRouteInformation(RouteInformation routeInformation) {

    final uri = Uri.parse(routeInformation.location);

    if (uri.pathSegments.isEmpty) {
      return Future.value(SplashPageConfig);
    }

    final path = uri.pathSegments[0];

    switch (path) {
      case SplashPath:
        return Future.value(SplashPageConfig);
      case LoginPath:
        return Future.value(LoginPageConfig);
      case ListItemsPath:
        return Future.value(ListItemsPageConfig);
      case DetailsPath:
        return Future.value(DetailsPageConfig);
      default:
        return Future.value(SplashPageConfig);
    }
  }

  @override
  RouteInformation restoreRouteInformation(PageConfiguration configuration) {
    switch (configuration.uiPage) {
      case Pages.Splash:
        return const RouteInformation(location: SplashPath);
      case Pages.Login:
        return const RouteInformation(location: LoginPath);
      case Pages.List:
        return const RouteInformation(location: ListItemsPath);
      case Pages.Details:
        return const RouteInformation(location: DetailsPath);
      default:
        return const RouteInformation(location: SplashPath);
    }
  }
}

// Views

final delegate = MyRouterDelegate();
final parser = MyParser();

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  _MyAppState() {
    delegate.setNewRoutePath(SplashPageConfig);
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationParser: parser,
      routerDelegate: delegate,
    );
  }
}

class SplashPage extends StatefulWidget {
  @override
  _SplashPageState createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Center(
        child: CircularProgressIndicator(),
      ),
    );
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    Timer(const Duration(milliseconds: 2000), () {
      delegate.replace(LoginPageConfig);
    });
  }
}

class LoginPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Login Page"),
      ),
      body: Container(
        color: Colors.red,
        child: Center(
          child: ElevatedButton(
            child: Text("Login"),
            onPressed: () {
              delegate.replace(ListItemsPageConfig);
            },
          ),
        ),
      ),
    );
  }
}

class ListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("List Page"),
      ),
      body: Container(
        color: Colors.blue,
        child: Center(
          child: Column(
            children: [
              ElevatedButton(
                child: Text("Logout"),
                onPressed: () {
                  delegate.replace(LoginPageConfig);
                },
              ),
              ElevatedButton(
                child: Text("Show details"),
                onPressed: () {
                  delegate.push(DetailsPageConfig);
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class DetailsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Details Page"),
        ),
        body: Container(
            color: Colors.green,
            child: Center(
              child: ElevatedButton(
                child: Text("Back"),
                onPressed: () {
                  delegate.popRoute();
                },
              ),
            )
        )
    );
  }
}
```

Thank you for your help.
