### ISSUE TITLE
DraggableScrollableSheet reset to initialChildSize when setState() is called

### ISSUE THREAD

**Issue by vandir** [flutter/flutter#99508] opened 2022-03-03 20:12 UTC
The problem described below is caused by `setState()`. Is this a bug? This does not happen with `ScrollController` and `ListView`.

## Steps to Reproduce

Run the sample app [(dartpad)](https://dartpad.dev/?id=d6cd71fe750dea8bd6f41f5560492269) and click the floating button.

<details>
  <summary>Sample app (click to expand)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<Color> colors = [
    Colors.green.shade400,
    Colors.green.shade900,
  ];
  late DraggableScrollableController _controller;

  @override
  void initState() {
    _controller = DraggableScrollableController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: DraggableScrollableSheet(
        controller: _controller,
        initialChildSize: 1,
        minChildSize: 0,
        maxChildSize: 1,
        builder: (context, controller) {
          return Container(
            color: Colors.blueGrey.shade100,
            child: ListView.builder(
              controller: controller,
              itemCount: 30,
              itemBuilder: (context, index) {
                return Container(
                  margin: const EdgeInsets.fromLTRB(20, 10, 20, 0),
                  height: 30,
                  color: colors[index % colors.length],
                  child: Center(child: Text('$index')),
                );
              },
            ),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          await _controller.animateTo(
            _controller.size - 0.2,
            duration: const Duration(seconds: 3),
            curve: Curves.linear,
          );
          setState(() {});
        },
        child: const Icon(Icons.expand_more),
      ),
    );
  }
}
```
</details>

**Expected results:**
The `DraggableScrollableSheet` should not change its `size` after the animation ends.

**Actual results:**
The `DraggableScrollableSheet` reset its `size` to `initialChildSize` after the animation ends.

**Comment by maheshmnj** [comment] 2022-03-04 08:02
Hi @vandir, Thanks for filing the issue. This is working as intended. When the animation completes you are calling setState which basically rebuild the widget with its present values, where you have provided `initialChildSize:1` so it gets rebuilt to its original height.

If it is mandatory to call setState you could persist state by passing  the value to `initialChildSize`, Please see the updated code sample.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<Color> colors = [
    Colors.green.shade400,
    Colors.green.shade900,
  ];
  late DraggableScrollableController _controller;

  @override
  void initState() {
    _controller = DraggableScrollableController();
    super.initState();
  }

  double initialSize = 1.0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: DraggableScrollableSheet(
        controller: _controller,
        initialChildSize: initialSize,
        minChildSize: 0,
        maxChildSize: 1,
        builder: (context, controller) {
          return Container(
            color: Colors.blueGrey.shade100,
            child: ListView.builder(
              controller: controller,
              itemCount: 30,
              itemBuilder: (context, index) {
                return Container(
                  margin: const EdgeInsets.fromLTRB(20, 10, 20, 0),
                  height: 30,
                  color: colors[index % colors.length],
                  child: Center(child: Text('$index')),
                );
              },
            ),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          await _controller.animateTo(
            _controller.size - 0.2,
            duration: const Duration(seconds: 3),
            curve: Curves.linear,
          );
          setState(() {
            initialSize = _controller.size;
          });
        },
        child: const Icon(Icons.expand_more),
      ),
    );
  }
}

```
</details> 



Closing as this is working as intended. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-03-04 08:02 UTC
Labels: in triage

**Comment by vandir** [comment] 2022-03-09 17:57
Hi @maheshmnj, many thanks for your answer. Please consider adding a method like `isAttached` (I've seen the source code, it seems as simple as doing `_attachedController != null`) to `DraggableScrollableController` in order to know when the controller attaches to a `DraggableScrollableSheet` and solve the problem with the code below.

<details>
  <summary>Alternative solution (click to expand)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<Color> colors = [
    Colors.green.shade400,
    Colors.green.shade900,
  ];
  late DraggableScrollableController _controller;

  @override
  void initState() {
    _controller = DraggableScrollableController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: DraggableScrollableSheet(
        controller: _controller,
        initialChildSize: _controller.isAttached ? _controller.size : 0.25,
        minChildSize: 0,
        maxChildSize: 1,
        builder: (context, controller) {
          return Container(
            color: Colors.blueGrey.shade100,
            child: ListView.builder(
              controller: controller,
              itemCount: 30,
              itemBuilder: (context, index) {
                return Container(
                  margin: const EdgeInsets.fromLTRB(20, 10, 20, 0),
                  height: 30,
                  color: colors[index % colors.length],
                  child: Center(child: Text('$index')),
                );
              },
            ),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          await _controller.animateTo(
            _controller.size - 0.2,
            duration: const Duration(seconds: 3),
            curve: Curves.linear,
          );
          setState(() {});
        },
        child: const Icon(Icons.expand_more),
      ),
    );
  }
}
```
</details>

There are mainly two advantages over this solution:

1. Avoid an extra member field;
2. Avoid to set the member field every time I call `setState()` (which could be high)
