### ISSUE TITLE
[ImageCache] _liveImages only track widget tree for current page 

### ISSUE THREAD

**Issue by weiminghuaa** [flutter/flutter#95891] opened 2021-12-28 07:48 UTC
Why does the _liveImages in the ImageCache of the Flutter framework only work on the current page? 

For example: Push from page A to page B. Page B is a list. After sliding a lot of pictures, page B pops to page A,  The image on the page A will reload. Because _liveImages only works on the current page, after sliding too many pictures on page B, when clearing the image cache according to the LRU principle, the picture's memory on page A are killed. This is very different from native. The logic of iOS I know is that the image memory of page A, no matter how B does it, when clearing the image cache according to the LRU principle, the image memory referenced by page A will not be cleared.

为什么Flutter 框架的 ImageCache 里面的 _liveImages只作用于当前页面，比如：从A页面push到B页面，B页面是个列表，滑动超多图片之后，B页面pop到A页面，A页面的图片会重新加载。因为_liveImages只作用于当前页面，B页面滑动过多图片后，按照lru原则清除图片缓存时，把A页面的图片干掉了。这跟原生很不一样啊，我知道的iOS的逻辑是，A页面的图片内存，无论B怎么搞，按照lru原则清除图片缓存时，都不会把A页面引用的图片内存清掉。

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. open a list view
3. click item to detail view which is a image list 
4. scroll list in detail view
5. pop detail view, the image in list view will reload
 
**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
PaintingBinding.instance?.imageCache?.maximumSize = 10; // 10 entries
PaintingBinding.instance?.imageCache?.maximumSizeBytes = 10 << 20; // 10MiB

class SampleItem {
  const SampleItem(this.id, this.imgUrl);
  final String imgUrl;
  final int id;
}

class SampleItemListView extends StatelessWidget {
  const SampleItemListView({
    Key? key,
    this.items = const [
      SampleItem(1,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403301_list.webp"),
      SampleItem(2,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/16306743446371_list.webp"),
      SampleItem(3,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/16306743446372_list.webp")
    ],
  }) : super(key: key);

  static const routeName = '/';

  final List<SampleItem> items;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample Items'),
        actions: [
          IconButton(
            icon: const Icon(Icons.settings),
            onPressed: () {
              Navigator.restorablePushNamed(context, SettingsView.routeName);
            },
          ),
        ],
      ),
      body: ListView.builder(
        restorationId: 'sampleItemListView',
        itemCount: items.length,
        itemBuilder: (BuildContext context, int index) {
          final item = items[index];

          return ListTile(
              title: Text('SampleItem ${item.id}'),
              leading: Image.network(item.imgUrl),
              onTap: () {
                Navigator.restorablePushNamed(
                  context,
                  SampleItemDetailsView.routeName,
                );
              });
        },
      ),
    );
  }
}

class SampleItemDetailsView extends StatelessWidget {
  const SampleItemDetailsView({Key? key}) : super(key: key);

  static const routeName = '/sample_item';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Item Details'),
      ),
      body: Column(
        children: [
          Image.network(
            "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/1630674344637code.webp",
            height: 100,
            fit: BoxFit.fitHeight,
          ),
          Expanded(
            child: ListView.builder(
              itemBuilder: (context, index) {
                return Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Image.network(
                    imgUrls[index],
                    height: 100,
                    fit: BoxFit.fitHeight,
                  ),
                );
              },
              itemCount: imgUrls.length,
            ),
          ),
        ],
      ),
    );
  }
}

final imgUrls = [
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403301_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403302_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/1630674340330code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547921_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547922_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547923_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/1631091054792code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/73/1631603982361code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492001_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492002_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492003_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492004_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/1631091049200code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/2/16310910529721_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/2/1631091052972code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454121_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454122_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454123_list.webp"
];

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by mamuseferha** [comment] 2021-12-28 08:48
Hi @weiminghuaa, thank you for filing this issue. I tried to reproduce this on the latest stable and master channel using the sample code below and it is not reproducible.

The images on the first page does not reload when popped back and the cache does not seem to be cleared, I have also included a video output below. 

Can you please provide your `flutter doctor -v`? also confirm if issue is similar to this https://github.com/flutter/flutter/issues/68700

<details>
<summary>video output</summary>

https://user-images.githubusercontent.com/92717368/147547371-f7d90266-d696-4b50-8813-b8929c32760f.mp4


</details>

<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  PaintingBinding.instance?.imageCache?.maximumSize = 10; // 10 entries
  PaintingBinding.instance?.imageCache?.maximumSizeBytes = 10 << 20; // 10MiB
  runApp(const MyApp());
}

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        SampleItemDetailsView.routeName: (context) =>
            const SampleItemDetailsView(),
      },
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const SampleItemListView(),
      ),
    );
  }
}

class SampleItem {
  const SampleItem(this.id, this.imgUrl);
  final String imgUrl;
  final int id;
}

class SampleItemListView extends StatelessWidget {
  const SampleItemListView({
    Key? key,
    this.items = const [
      SampleItem(1,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403301_list.webp"),
      SampleItem(2,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/16306743446371_list.webp"),
      SampleItem(3,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/16306743446372_list.webp")
    ],
  }) : super(key: key);

  static const routeName = '/';

  final List<SampleItem> items;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample Items'),
        actions: [
          IconButton(
            icon: const Icon(Icons.settings),
            onPressed: () {},
          ),
        ],
      ),
      body: ListView.builder(
        restorationId: 'sampleItemListView',
        itemCount: items.length,
        itemBuilder: (BuildContext context, int index) {
          final item = items[index];

          return ListTile(
              title: Text('SampleItem ${item.id}'),
              leading: Image.network(item.imgUrl),
              onTap: () {
                Navigator.restorablePushNamed(
                  context,
                  SampleItemDetailsView.routeName,
                );
              });
        },
      ),
    );
  }
}

class SampleItemDetailsView extends StatelessWidget {
  const SampleItemDetailsView({Key? key}) : super(key: key);

  static const routeName = '/sample_item';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Item Details'),
      ),
      body: Column(
        children: [
          Image.network(
            "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/1630674344637code.webp",
            height: 100,
            fit: BoxFit.fitHeight,
          ),
          Expanded(
            child: ListView.builder(
              itemBuilder: (context, index) {
                return Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Image.network(
                    imgUrls[index],
                    height: 100,
                    fit: BoxFit.fitHeight,
                  ),
                );
              },
              itemCount: imgUrls.length,
            ),
          ),
        ],
      ),
    );
  }
}

final imgUrls = [
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403301_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403302_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/1630674340330code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547921_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547922_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547923_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/1631091054792code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/73/1631603982361code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492001_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492002_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492003_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492004_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/1631091049200code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/2/16310910529721_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/2/1631091052972code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454121_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454122_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454123_list.webp"
];

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (12 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.205, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.205 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ec059c994 (3 hours ago), 2021-12-28 00:29:08 -0500
    • Engine revision 31fcaf3ce4
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Comment by weiminghuaa** [comment] 2021-12-28 08:52
@mamuseferha Did you add this code before SampleItemListView init

`
PaintingBinding.instance?.imageCache?.maximumSize = 10; // 10 entries
PaintingBinding.instance?.imageCache?.maximumSizeBytes = 10 << 20; // 10MiB
`

**Comment by mamuseferha** [comment] 2021-12-29 07:18
Hi @weiminghuaa, I added the 
```
PaintingBinding.instance?.imageCache?.maximumSize = 10; // 10 entries
PaintingBinding.instance?.imageCache?.maximumSizeBytes = 10 << 20; // 10MiB
```
in the `main` method.

Can you run my sample code here https://github.com/flutter/flutter/issues/95891#issuecomment-1001944152 to see if issue still persists using the latest flutter stable channel `2.8.1`?

**Comment by weiminghuaa** [comment] 2021-12-29 08:02
@mamuseferha That code cannot add in main method, because PaintingBinding.instance?.imageCache? is null when call  before runApp function. You can try make MyApp convert to StatefulWidget, and add code in initState

<details>
<summary>Codes</summary>
```dart
/// This is the main application widget.
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();

    PaintingBinding.instance?.imageCache?.maximumSize = 10; // 10 entries
    PaintingBinding.instance?.imageCache?.maximumSizeBytes = 10 << 20; // 10MiB
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        SampleItemDetailsView.routeName: (context) =>
            const SampleItemDetailsView(),
      },
      title: MyApp._title,
      home: Scaffold(
        appBar: AppBar(title: const Text(MyApp._title)),
        body: const SampleItemListView(),
      ),
    );
  }
}
```
</details>

**Comment by mamuseferha** [comment] 2021-12-29 10:26
Hi @weiminghuaa, I verified this on the latest master and stable channel and it is reproducible. 

When `PaintingBinding.instance?.imageCache?.maximumSize` is set to a value in initState, the images reloads when you go back.

<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
 
  runApp(const MyApp());
}

/// This is the main application widget.
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();

    PaintingBinding.instance?.imageCache?.maximumSize = 10; // 10 entries
    PaintingBinding.instance?.imageCache?.maximumSizeBytes =
        10 << 20; // 10MiB
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        SampleItemDetailsView.routeName: (context) =>
            const SampleItemDetailsView(),
      },
      title: MyApp._title,
      home: Scaffold(
        appBar: AppBar(title: const Text(MyApp._title)),
        body: const SampleItemListView(),
      ),
    );
  }
}

class SampleItem {
  const SampleItem(this.id, this.imgUrl);
  final String imgUrl;
  final int id;
}

class SampleItemListView extends StatelessWidget {
  const SampleItemListView({
    Key? key,
    this.items = const [
      SampleItem(1,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403301_list.webp"),
      SampleItem(2,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/16306743446371_list.webp"),
      SampleItem(3,
          "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/16306743446372_list.webp")
    ],
  }) : super(key: key);

  static const routeName = '/';

  final List<SampleItem> items;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample Items'),
        actions: [
          IconButton(
            icon: const Icon(Icons.settings),
            onPressed: () {},
          ),
        ],
      ),
      body: ListView.builder(
        restorationId: 'sampleItemListView',
        itemCount: items.length,
        itemBuilder: (BuildContext context, int index) {
          final item = items[index];

          return ListTile(
              title: Text('SampleItem ${item.id}'),
              leading: Image.network(item.imgUrl),
              onTap: () {
                Navigator.restorablePushNamed(
                  context,
                  SampleItemDetailsView.routeName,
                );
              });
        },
      ),
    );
  }
}

class SampleItemDetailsView extends StatelessWidget {
  const SampleItemDetailsView({Key? key}) : super(key: key);

  static const routeName = '/sample_item';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Item Details'),
      ),
      body: Column(
        children: [
          Image.network(
            "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/11/1630674344637code.webp",
            height: 100,
            fit: BoxFit.fitHeight,
          ),
          Expanded(
            child: ListView.builder(
              itemBuilder: (context, index) {
                return Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Image.network(
                    imgUrls[index],
                    height: 100,
                    fit: BoxFit.fitHeight,
                  ),
                );
              },
              itemCount: imgUrls.length,
            ),
          ),
        ],
      ),
    );
  }
}

final imgUrls = [
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403301_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/16306743403302_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/3/1630674340330code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547921_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547922_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/16310910547923_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/5/1631091054792code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/73/1631603982361code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492001_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492002_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492003_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/16310910492004_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/1/1631091049200code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/2/16310910529721_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/2/1631091052972code.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454121_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454122_list.webp",
  "https://d2dpvm6hvxu74r.cloudfront.net/product/100780000002/4/16310910454123_list.webp"
];

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (5 available)
    • SM G975U (mobile)       • R58M95MA95E                          • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • E0F828CA-CF98-473C-8F5E-DAB4DE53A466 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.209, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.209 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6054eda86b (6 hours ago), 2021-12-28 18:19:16 -0800
    • Engine revision 01d19ceef4
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • E0F828CA-CF98-473C-8F5E-DAB4DE53A466 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
flo@flo-2 flutter_master % fvm flutter doctor -v
[✓] Flutter (Channel master, 2.9.0-1.0.pre.209, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.209 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6054eda86b (6 hours ago), 2021-12-28 18:19:16 -0800
    • Engine revision 01d19ceef4
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (5 available)
    • SM G975U (mobile)       • R58M95MA95E                          • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • E0F828CA-CF98-473C-8F5E-DAB4DE53A466 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Comment by weiminghuaa** [comment] 2021-12-29 10:38
Hi @mamuseferha Yes, I track source code, I found it cause by stopListeningToStream in _ImageState. I this maybe it's should do that in dispose?

```
  @override
  void didChangeDependencies() {
    _updateInvertColors();
    _resolveImage();

    if (TickerMode.of(context))
      _listenToStream();
    else
      _stopListeningToStream(keepStreamAlive: true);

    super.didChangeDependencies();
  }
```

**Comment by dnfield** [comment] 2022-01-10 23:55
The framework has no idea if `Page A` will ever come back again or not, but we do know that the widgets that are live on `Page B` might still need to be rendered soon. So we cache them.

If you want to cache the images on Page A because you _know_ you will be going back to it, you have to do that at the application level currently. I don't know if we have any easy way to do that, but using the `_liveImage` cache is not the right way.

Closing as WAI.

**Closed by dnfield** 2022-01-10 23:55 UTC
Labels: framework, a: images, has reproducible steps, found in release: 2.8, found in release: 2.9
