### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by 0RaMsY0** [flutter/flutter#109706] opened 2022-08-17 17:44 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2233:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:822:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:841:49)
#5      FlutterVmService.flutterDebugDumpRenderTree (package:flutter_tools/src/vmservice.dart:587:50)
#6      ResidentHandlers.debugDumpRenderTree (package:flutter_tools/src/resident_runner.dart:683:53)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1760:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.1.0-0.0.pre.2276, on Pop!_OS
    22.04 LTS 5.18.10-76051810-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.1.0-0.0.pre.2276 on channel master at
      /home/ramsy/snap/flutter/common/flutter
    [32m•[39m Upstream repository
      https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4aba1248c6 (2 days ago), 2022-08-15
      10:28:24 -0400
    [32m•[39m Engine revision f0c3829e90
    [32m•[39m Dart version 2.19.0 (build 2.19.0-96.0.dev)
    [32m•[39m DevTools version 2.16.0

[32m[✓][39m Android toolchain - develop for Android devices (Android
    SDK version 33.0.0)
    [32m•[39m Android SDK at /home/ramsy/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      11.0.16+8-post-Ubuntu-0ubuntu122.04)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m CHROME_EXECUTABLE = /snap/bin/chromium

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    [32m•[39m cmake version 3.10.2
    [32m•[39m ninja version 1.8.2
    [32m•[39m pkg-config version 0.29.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#andr
      oid-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.70.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.46.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Pop!_OS
      22.04 LTS 5.18.10-76051810-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Chromium
      104.0.5112.79 snap

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1

**Comment by darshankawar** [comment] 2022-08-18 10:36
Closing as duplicate of https://github.com/flutter/flutter/issues/101962

**Closed by darshankawar** 2022-08-18 10:36 UTC
Labels: in triage
