### ISSUE TITLE
Double tapping on a widget rebuilds it and throws gesture exception. Hot restarting the app then throws `LateInitialization` exception.

### ISSUE THREAD

**Issue by Hu1buerger** [flutter/flutter#92005] opened 2021-10-18 15:07 UTC
## Steps to Reproduce

See example [option selecting widget](https://gist.github.com/Hu1buerger/86350b1ae4a91d768de052e7a566bf49)

1. Use the widget
2. use `v1.dart`
3. supply it with options 
```dart
var options = List<Option<double>>.generate(5, (index) {
      return Option(
        value: index,
        selected: index == 0,
      );
    });
```
3. switch between options (aka click on some in some pattern)

**Expected results:** 

I expect that the option gets selected while deselecting all others and it shouldn't throw

**Actual results:** 
Actually it sometimes throws an LateInitError.

I would like to change two things (plus fix the bug):
1. don't rebuild the option widget when it gets selected or deselected, but I can't seem to get the state from the optionselector widget. 
```dart 
// with Option as StatefulWidget?
Option o = [...]; 
o.setSelected(true);

// instead of
var new = Option(
  value: o.value
  [...],
  selected: !o.selected
);
// and reinsert it into the OptionSelector
```
2. the onPressed callback in Option should be final. I cannot figure out why it gets "deinitialized" bcs I set the callback in initState. `v2.dart`dosnt seem to throw the LateInitError for some reason as the function gets set from the build function.

In regards to 1. i know of the GlobalKey but afaik I cannot create one while constructing the OptionWidget and call the super constructor.

Thanks a lot in advance
<details>
<summary>Code sample</summary>
 see above 
</details>

<details>
  <summary>Logs</summary>
```
======== Exception caught by gesture ===============================================================
The following LateError was thrown while handling a gesture:
LateInitializationError: Field 'onPressed' has not been initialized.

When the exception was thrown, this was the stack: 
#0      Option.onPressed (package:unexplainedevil/src/presentation/add_entrys/add_log_entry.dart)
#1      Option._onPressed (package:unexplainedevil/src/presentation/add_entrys/add_log_entry.dart:533:5)
#2      Option.build.<anonymous closure> (package:unexplainedevil/src/presentation/add_entrys/add_log_entry.dart:540:24)
#3      _RawChipState._handleTap (package:flutter/src/material/chip.dart:1768:23)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:558:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#25     _invoke1 (dart:ui/hooks.dart:185:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#a9fd3
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(192.0, 361.8)
  finalLocalPosition: Offset(18.0, 16.0)
  button: 1
  sent tap down
====================================================================================================
```

```
$flutter doctor -v

[✓] Flutter (Channel unknown, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-DE)
    • Flutter version 2.5.2 at /usr/local/Caskroom/flutter/2.5.1/flutter
    • Upstream repository unknown
    • Framework revision 3595343e20 (3 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-213.4293.20)
    • IntelliJ at /Applications/IntelliJ IDEA 2021.3 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.61.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 94.0.4606.81

! Doctor found issues in 1 category.

```

</details>

**Comment by Hu1buerger** [comment] 2021-10-19 10:32
Logger is from `logging: ^1.0.2`

```dart
void main() {
  var opts = List<Option<double>>.generate(5, (index) {
      return Option(
        value: index,
        selected: index == 0,
      );
    });

  runApp(MaterialApp(
    home: OptionSelecter(options: opts, onSelect: (o, i) => print(o.value.toString())}) ,
  ));
}
```

should work. @darshankawar

**Comment by Hu1buerger** [comment] 2021-10-20 14:16
This one compiles and runs but dosnt reproduce the original code / issue

```dart
import 'package:flutter/material.dart';
import 'package:logging/logging.dart';

void main() {
  var opts = List<Option>.generate(5, (index) {
    return Option(
      value: index.toDouble(),
      selected: index == 0,
      onPressed: (Option option) {},
    );
  });

  runApp(
    MaterialApp(
      home: Scaffold(
        body: Center(
          child: OptionSelecter(options: opts, onSelect: (o, i) => print(o.value.toString())),
        ),
      ),
    ),
  );
}

class OptionSelecter extends StatefulWidget {
  List<Option> options;
  void Function(Option selected, int index) onSelect;
  late int selectedIndex;

  OptionSelecter({Key? key, required this.options, required this.onSelect, int? selectedIndex}) : super(key: key) {
    if (options.isEmpty) ArgumentError.value(options, "options", "Options shall not be empty");

    if (selectedIndex != null && selectedIndex != -1) {
      if (0 <= selectedIndex && selectedIndex < options.length) {
        ArgumentError.value(selectedIndex, "selectedIndex", "isnt a valid index in options");
      }
      this.selectedIndex = selectedIndex;
    } else {
      selectedIndex = options.indexWhere((element) => element.selected == true);
    }

    if (selectedIndex == -1)
      this.selectedIndex = 0;
    else
      this.selectedIndex = selectedIndex;
  }

  @override
  State<StatefulWidget> createState() => _OptionSelectorState();
}

class _OptionSelectorState extends State<OptionSelecter> {
  Logger logger = Logger("OptionSelectorS");
  int selectedOption = 0;

  @override
  void initState() {
    super.initState();

    logger.fine("init state");

    selectedOption = widget.selectedIndex;

    for (int i = 0; i < widget.options.length; i++) {
      var old = widget.options[i];
      widget.options[i] = Option(
        key: UniqueKey(),
        value: old.value,
        selected: old.selected,
        onPressed: onPressOnOption,
      );

      logger.finest("setting onPressed for Option ${old.value.toString()}");
    }

    selectOption(selectedOption);
  }

  /// the option o has been pressed on and informs about it being selected
  void onPressOnOption(Option o) {
    assert(widget.options.contains(o));

    logger.finest("pressed on ${o.value.toString()}");

    int indexOfO = widget.options.indexOf(o);
    bool change = selectOption(indexOfO);

    if (change) {
      selectedOption = indexOfO;
      widget.onSelect(o, selectedOption);
      logger.finest("change, setting state");
      setState(() {});
      return;
    }

    assert(indexOfO == selectedOption);
  }

  bool selectOption(int i) {
    var o = widget.options[i];

    bool change = false;

    for (int i = 0; i < widget.options.length; i++) {
      var o1 = widget.options[i];

      // the option that has been pressed on should be selected
      bool shouldBeSelected = o1 == o;
      change |= _setOption(o1, shouldBeSelected);
    }

    return change;
  }

  bool _setOption(Option o, bool selected) {
    if (o.selected == selected) return false;

    int index = widget.options.indexOf(o);
    assert(0 <= index && index < widget.options.length);

    var onew = Option(
      key: UniqueKey(),
      value: o.value,
      selected: selected,
      onPressed: onPressOnOption,
    );
    logger.finest("updating option ${o.value.toString()} and setting onPressed to ${onew.onPressed}");

    widget.options[index] = onew;
    return true;
  }

  @override
  Widget build(BuildContext context) {
    logger.fine("building");
    void Function(Option o) callback = onPressOnOption;
    logger.finest(
        "idenity of closure onPressed ${identityHashCode(callback).toString()} and of this ${identityHashCode(this).toString()}");

    return Row(
      children: widget.options,
    );
  }
}

///TODO: let a option show a slider to select variable option
class Option<T> extends StatelessWidget {
  final bool selected;
  final T value;

  // callback to inform the OptionSelecter that this item has been pressed on
  late final void Function(Option option) onPressed;

  Option({Key? key, required this.value, this.selected = false, required this.onPressed}) : super(key: key);

  void _onPressed(BuildContext context) {
    var identity = identityHashCode(onPressed).toString();
    onPressed(this);
  }

  @override
  Widget build(BuildContext context) {
    InputChip chip = InputChip(
      label: Text(value.toString()),
      onPressed: () => _onPressed(context),
      selected: selected,
    );

    return chip;
  }
}
```

**Comment by darshankawar** [comment] 2021-10-21 06:25
Thanks for the updated code. I see a pattern to replicate the `LateInitialization` error, as below:

Initially, I played around the option selector UI which works well using single tap, but if I sequentially try to double tap on any one of them, then I get below error first:

<details>
<summary>console error log</summary>

```

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:ios_bug/main.dart': Failed assertion: line 93 pos 12: 'widget.options.contains(o)': is not true.

When the exception was thrown, this was the stack: 
#2      _OptionSelectorState.onPressOnOption (package:ios_bug/main.dart:93:12)
#3      Option._onPressed (package:ios_bug/main.dart:170:14)
#4      Option.build.<anonymous closure> (package:ios_bug/main.dart:177:24)
#5      _RawChipState._handleTap (package:flutter/src/material/chip.dart:1708:23)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:525:8)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#27     _invoke1 (dart:ui/hooks.dart:169:10)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#2e8dd
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(91.7, 464.0)
  finalLocalPosition: Offset(19.7, 16.0)
  button: 1
  sent tap down
====================================================================================================





```


</details>

Then for subsequent double tap, I get same error as above, but not `LateInitialization` error.  Now, if I hot restart the app and then directly tap on any of the chip, I see `LateInitialization`, as below:

<details>
<summary>console error log</summary>

```

Performing hot restart...
Syncing files to device iPhone 12 Pro Max...
Restarted application in 382ms.

======== Exception caught by gesture ===============================================================
The following LateError was thrown while handling a gesture:
LateInitializationError: Field 'onPressed' has not been initialized.

When the exception was thrown, this was the stack: 
#0      Option.onPressed (package:ios_bug/main.dart)
#1      Option._onPressed (package:ios_bug/main.dart:169:37)
#2      Option.build.<anonymous closure> (package:ios_bug/main.dart:177:24)
#3      _RawChipState._handleTap (package:flutter/src/material/chip.dart:1708:23)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:525:8)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#25     _invoke1 (dart:ui/hooks.dart:169:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#5eb80
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(93.7, 462.7)
  finalLocalPosition: Offset(21.7, 16.0)
  button: 1
  sent tap down
====================================================================================================






```


</details>

See if this pattern leads you to what can be fixed in your code implementation.

**Comment by christopherfujino** [comment] 2021-11-02 21:57
This looks like a hot reload issue, and we need help from the Dart team diagnosing the root cause.

**Comment by a-siva** [comment] 2021-11-10 00:32
//cc @rmacnak-google

**Comment by rmacnak-google** [comment] 2021-11-16 22:37
There's nothing specific to hot-reload here. Hot reload preserves late fields the same as regular fields.

The `LateInitializationError` occurs when the `Option` is constructed in `OptionSelectorUserState.build`, which unlike the other construction sites does not set `onPressed`. This construction site seems to only run during reassemble, but it's a framework question whether that is reasonable.

**Comment by goderbauer** [comment] 2021-11-18 00:04
Looking at the code given in https://github.com/flutter/flutter/issues/92005#issuecomment-947712117 this seems to be a bug in that code. In `OptionSelectorUserState.initState` (which assigns the `onPressed` only runs when the state is first initialized. During stateful (!) hot reload the state is not re-initialized (otherwise it wouldn't be stateful). Therefore, the `onPressed` handlers are never assigned to the newly created `Option` objects. `OptionSelectorUserState` is missing an implementation for `didUpdateWidget`. That one runs when the state is reconfigured with a new widget configuration. It needs to replicate some of the logic in `initState` and assign `onPressed` handlers to the options of the new configuration widget. See also https://master-api.flutter.dev/flutter/widgets/State/didUpdateWidget.html.

**Closed by goderbauer** 2021-11-18 00:04 UTC
Labels: severe: crash, tool, framework, t: hot reload, f: gestures, a: error message, has reproducible steps, P2, found in release: 2.5, found in release: 2.6

**Comment by Hu1buerger** [comment] 2021-11-18 19:17
@all thanks alot.  

@goderbauer why is onPressed not initialised.

**Comment by goderbauer** [comment] 2021-11-18 19:19
> why is onPressed not initialised.

Because you're not initializing it. You probably need to do that in `didUpdateWidget` when a new widget configuration is given.

**Comment by Hu1buerger** [comment] 2021-11-18 19:28
That for sure. Is it bcs the OptionWidget gets reinstantiated, while the StatefulWidget is not?
