### ISSUE TITLE
[webview_flutter] In release mode, the NavigationDelegate event is not called.

### ISSUE THREAD

**Issue by JosephNK** [flutter/flutter#118423] opened 2023-01-13 02:08 UTC
I am using webview_flutter 4.0.1 version.
The sample code below works fine in debug mode.
But in release mode the NavigaionDelegate event is not called.
I don't know why the problem only occurs in release mode.
I am wondering what could be causing this problem.

<details>
<summary>Code</summary>

```dart
late WebViewController _webViewController;

@override
void initState() {
  super.initState();

  ...

  final WebViewController controller =
        WebViewController.fromPlatformCreationParams(params);
  
  controller
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    ..setBackgroundColor(const Color(0x00000000))
    ..setNavigationDelegate(
      NavigationDelegate(
        onProgress: (int progress) { <-- not fire
          // Update loading bar.
        },
        onPageStarted: (String url) {}, <-- not fire
        onPageFinished: (String url) {}, <-- not fire
        onWebResourceError: (WebResourceError error) {}, <-- not fire
        onNavigationRequest: (NavigationRequest request) { <-- not fire
          if (request.url.startsWith('https://www.youtube.com/')) {
            return NavigationDecision.prevent;
          }
          return NavigationDecision.navigate;
        },
      ),
    );

  _webViewController = controller;

  WidgetsBinding.instance.addPostFrameCallback((_) async {
     _webViewController.loadRequest(Uri.parse('https://flutter.dev'));
  });
}
```
</details>

<details>
<summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 13.1 22C65 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
</details>

**Comment by danagbemava-nc** [comment] 2023-01-13 07:46
Hi @JosephNK, what platform(s) are you experiencing this issue on? 

Your code sample is not complete, please provide a complete minimal reproducible code sample so we can investigate this.

Thank you

**Comment by JosephNK** [comment] 2023-01-13 08:48
@danagbemava-nc  Only Android is currently being tested, iOS has not been confirmed.

As you can see in the screenshot below, the event is not called in release mode.

Sample Source
https://github.com/JosephNK/flutter_webview

Debug Mode
<img src="https://user-images.githubusercontent.com/1622085/212276445-f2080f05-6746-47e7-886a-a5c17cd1de04.png" width="200" />

Release Mode
<img src="https://user-images.githubusercontent.com/1622085/212277051-41c3c514-1392-47b9-88d7-29d859cd268c.png" width="200" />

**Comment by kubastick** [comment] 2023-01-13 09:25
I have same issue on android that occurs only with release mode.
I can confirm that NavigationDelegate works correctly in both debug and release mode on iOS.

**Comment by danagbemava-nc** [comment] 2023-01-13 09:51
Hi @JosephNK, you are missing the android permission in your `AndroidManifest.xml`. 

The debug manifest already includes the Internet permission because it is required for debugging but you have to manually add it in your main `AndroidManifest.xml`

**Comment by JosephNK** [comment] 2023-01-13 10:11
@danagbemava-nc Even if <uses-permission android:name="android.permission.INTERNET" /> value is entered in AndroidManifest.xml, the event does not work in release mode.
For reference, I added it to github and committed it.

**Comment by danagbemava-nc** [comment] 2023-01-13 13:32
Hi @JosephNK, the issue isn't actually with the `NavigationDelegate`, it looks like there was an issue in the initialization of the webview. I got the error below on the stable channel (I used the logcat in android studio to check the error). However, I cannot seem to reproduce the issue on the master channel. 

Can you switch to the master channel to see if you are still able to reproduce the error over there as well?
You can switch to the master channel by running the commands below

```
flutter channel master
flutter upgrade
```

If you still reproduce this on the master channel, kindly provide the `flutter doctor -v` output of the master channel. 

Thank you	

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference
                                                                                                    	at io.flutter.plugins.webviewflutter.k3.w(Unknown Source:12)
                                                                                                    	at io.flutter.plugins.webviewflutter.c2.U(:1)
                                                                                                    	at io.flutter.plugins.webviewflutter.c2.j(:1)
                                                                                                    	at io.flutter.plugins.webviewflutter.b2.a(Unknown Source:2)
                                                                                                    	at c2.a$b.a(Unknown Source:17)
                                                                                                    	at p1.c.j(Unknown Source:18)
                                                                                                    	at p1.c.k(Unknown Source:20)
                                                                                                    	at p1.c.g(Unknown Source:0)
                                                                                                    	at p1.b.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8319)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
                                                                                                    , null)
                                                                                                    #0      WebViewHostApi.loadUrl (package:webview_flutter_android/src/android_webview.pigeon.dart:377)
                                                                                                    <asynchronous suspension>
```

**Comment by MaksimZdanchuk** [comment] 2023-01-15 15:58
@JosephNK did u find the solution? have the same problem

**Comment by JosephNK** [comment] 2023-01-15 16:01
@MaksimZdanchuk I haven't found it yet 🧐

**Comment by MaksimZdanchuk** [comment] 2023-01-15 16:10
@JosephNK I ve just tried to downgrade the web_view library to 3.0.4 version and its worked for me)

**Comment by gitoramadhan** [comment] 2023-01-15 19:04
Same issue here..

**Comment by MaksimZdanchuk** [comment] 2023-01-15 19:05
@gitoramadhan downgrade the package as i said.

**Comment by JosephNK** [comment] 2023-01-16 00:58
@MaksimZdanchuk Downgrading doesn't seem like a good idea. The reason for solving this and using webview_flutter 4.0.1 is to apply the corrected code for the following problems.
[#116954](https://github.com/flutter/flutter/issues/116954)
[#104889](https://github.com/flutter/flutter/issues/104889)

**Comment by danagbemava-nc** [comment] 2023-01-16 06:20
Hi @JosephNK, can you move the `_webViewController.loadRequest(Uri.parse('https://flutter.dev'));` out of the `WidgetsBindings.instance.addPostFrameCallback` callback and try again to see if it works for you?

 It worked for me when I commented out `WidgetsBindings.instance.addPostFrameCallback`

**Comment by JosephNK** [comment] 2023-01-16 06:55
Hello @danagbemava-nc I need to use WidgetsBindings.instance.addPostFrameCallback because I need to use WidgetsBindings.instance.addPostFrameCallback to handle loadRequest in my current project.
Please note.

**Comment by gitoramadhan** [comment] 2023-01-16 07:31
> Hi @JosephNK, can you move the `_webViewController.loadRequest(Uri.parse('https://flutter.dev'));` out of the `WidgetsBindings.instance.addPostFrameCallback` callback and try again to see if it works for you?
> 
> It worked for me when I commented out `WidgetsBindings.instance.addPostFrameCallback`

Were you using stable channel? I still get the same issue

**Comment by gitoramadhan** [comment] 2023-01-16 12:30
> @MaksimZdanchuk Downgrading doesn't seem like a good idea. The reason for solving this and using webview_flutter 4.0.1 is to apply the corrected code for the following problems. [#116954](https://github.com/flutter/flutter/issues/116954), [#104889](https://github.com/flutter/flutter/issues/104889)

Until the issue has been resolved, I will have to downgrade.. until the is a suitable fix.

**Comment by gitoramadhan** [comment] 2023-01-16 15:11
@JosephNK @MaksimZdanchuk  Have you tried this: https://github.com/Earlybyte/aad_oauth/issues/196 ." initialize the NavigationDelegate as it's own variable before creating the WebViewController"

 I've applied this and it does work

**Comment by JosephNK** [comment] 2023-01-17 01:34
@danagbemava-nc @gitoramadhan @joshmossas I'm wondering what the difference is between release mode and debug mode for this issue.

**Comment by danagbemava-nc** [comment] 2023-01-17 06:06
> Were you using stable channel? I still get the same issue
@gitoramadhan, yes I was on the stable channel. I just tested again and it worked just fine.

> Hello @danagbemava-nc I need to use WidgetsBindings.instance.addPostFrameCallback because I need to use WidgetsBindings.instance.addPostFrameCallback to handle loadRequest in my current project.
Please note.

@JosephNK, I'm curious, why exactly do you need to use the WidgetsBindings to handle the `loadRequest`?

> I'm wondering what the difference is between release mode and debug mode for this issue.

It might be a race condition in the initialization of the controller

@JosephNK  Does the workaround in https://github.com/flutter/flutter/issues/108801#issuecomment-1367490174 work for you?

**Comment by JosephNK** [comment] 2023-01-17 06:13
Hello @danagbemava-nc Even if you don't use WidgetsBindings, shouldn't you be able to do a loadRequest on the button click event later? The reason loadRequest is being called in my project's WidgetsBindings is because initState needs to wait through loadRequest and fetch certain data.
I'm curious here. Does it matter if WidgetsBindings are used or not? 
I guess I'll have to find another reason to use WidgetsBindings or not.

**Comment by JosephNK** [comment] 2023-01-17 06:20
> Does the workaround in https://github.com/flutter/flutter/issues/108801#issuecomment-1367490174 work for you?
@danagbemava-nc I checked that part. I also confirmed that it works.
By the way, I wonder how the debug mode and release mode behave differently in the same code. For that code, if I set NavigationDelegate as a global variable, it works in release mode, otherwise it doesn't work. I wonder why this is.

**Comment by danagbemava-nc** [comment] 2023-01-18 06:43
> shouldn't you be able to do a loadRequest on the button click event later

Yes, you can do this later with a click event. 

> I'm curious here. Does it matter if WidgetsBindings are used or not?
I guess I'll have to find another reason to use WidgetsBindings or not.

I'm not sure I fully understand your use case so I can't say definitively whether or not it is necessary. 

>  I wonder how the debug mode and release mode behave differently in the same code

Debug and release use different compilation modes, so that could be a factor. Debug builds generally are not optimized, tree-shaking doesn't take place and symbols are not stripped, which happens in release mode.  

> if I set NavigationDelegate as a global variable, it works in release mode, otherwise it doesn't work. I wonder why this is.

I'm not entirely sure of the reason for this, it might have to do with how the modes are compiled but don't quote me on that.  

> Also, it doesn't work on the Stable channel but works on the Master channel.
What are the reasons for these parts?

There could have been some changes to how certain things are handled in the flutter engine or with dart itself. The master branch is usually several commits ahead of stable so it usually has a lot of improvements over the stable branch. 

Given that this has been fixed on the master channel (and workarounds exist for this issue on stable), per our triage policy, I'll be closing this issue. 

Thank you

**Closed by danagbemava-nc** 2023-01-18 06:43 UTC
Labels: in triage
