### ISSUE TITLE
Can't scroll a NestedScrollView with a not expandable pinned SliverAppBar

### ISSUE THREAD

**Issue by letsar** [flutter/flutter#99147] opened 2022-02-25 10:28 UTC
## Summary

If we don't set the `expandedHeight` of a `SliverAppBar` or if we set it to the same value than the `collapsedHeight`, then we can't scroll a list under a `NestedScrollView`.

If for example we change the `SliverAppBar` declaration (in the following code sample) by this instead, we can scroll: 
```dart
SliverAppBar(
  title: const Text('Books'),
  pinned: true,
  expandedHeight: kToolbarHeight + 0.005,
  forceElevated: innerBoxIsScrolled,
),
```

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Try to scroll

**Expected results:**
We should be able to scroll the list.

**Actual results:**
We can't scroll.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final List<String> _tabs = <String>['Tab 1', 'Tab 2'];
    return DefaultTabController(
      length: _tabs.length,
      child: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverOverlapAbsorber(
                handle:
                    NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  title: const Text('Books'),
                  pinned: true,
                  expandedHeight: kToolbarHeight,
                  forceElevated: innerBoxIsScrolled,
                ),
              ),
            ];
          },
          body: SafeArea(
            top: false,
            bottom: false,
            child: Builder(
              builder: (BuildContext context) {
                return CustomScrollView(
                  slivers: <Widget>[
                    SliverOverlapInjector(
                      handle: NestedScrollView.sliverOverlapAbsorberHandleFor(
                          context),
                    ),
                    SliverPadding(
                      padding: const EdgeInsets.all(8.0),
                      sliver: SliverFixedExtentList(
                        itemExtent: 48.0,
                        delegate: SliverChildBuilderDelegate(
                          (BuildContext context, int index) {
                            return ListTile(
                              title: Text('Item $index'),
                            );
                          },
                          childCount: 30,
                        ),
                      ),
                    ),
                  ],
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[   +4 ms] executing: /Users/letsar/Library/Android/sdk/platform-tools/adb -s 87950fce shell am force-stop com.example.issue_nested_scroll_view
[ +129 ms] Application finished.
[  +26 ms] "flutter run" took 52 532ms.
[  +69 ms] Service protocol connection closed.
[  +41 ms] ensureAnalyticsSent: 88ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing issue_nested_scroll_view...                           
No issues found! (ran in 8.8s)
```

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6 20G165 darwin-arm, locale fr-FR)
    • Flutter version 2.10.1 at /Users/letsar/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (2 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/letsar/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (5 available)
    • IN2023 (mobile)            • 87950fce                             • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)            • 00008030-000139323E86402E            • ios            • iOS 14.8.1 18H107
    • iPhone 13 Pro Max (mobile) • C50CF0C2-0B15-493F-B856-F594A4D3386F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by nt4f04uNd** [comment] 2022-02-26 21:32
Duplicate of https://github.com/flutter/flutter/issues/79077

**Closed by nt4f04uNd** 2022-02-26 21:32 UTC
