### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by RafaelZasas** [flutter/flutter#150654] opened 2024-06-22 06:56 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2584:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 15.0 24A5264n darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.23.0-0.1.pre on channel beta at /Users/rafaelzasas/dev/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2feea7a407 (2 weeks ago), 2024-06-06 10:19:10 +0700
    [32m•[39m Engine revision bb10c54666
    [32m•[39m Dart version 3.5.0 (build 3.5.0-180.3.beta)
    [32m•[39m DevTools version 2.36.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/rafaelzasas/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.0)
    [32m•[39m Xcode at /Applications/Xcode-beta.app/Contents/Developer
    [32m•[39m Build 16A5171c
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.87.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.84.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Rafs Iphone 15 (mobile)         • 00008130-001640DA0891401C • ios            • iOS 18.0 22A528

**Comment by huycozy** [comment] 2024-06-24 05:26
>Rafs Iphone 15 (mobile)         • 00008130-001640DA0891401C • ios            • iOS 18.0 22A528

This seems to be an OS version-specific issue on iOS 18 beta. Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131.

**Closed by huycozy** 2024-06-24 05:26 UTC
