### ISSUE TITLE
How to pin min window size in mac.

### ISSUE THREAD

**Issue by leaxoy** [flutter/flutter#47902] opened 2019-12-28 02:56 UTC
I write macos app with flutter, but the app window zoom without any limit, is there a way to pin the min window size, and can't zoom small with it

**Comment by stuartmorgan** [comment] 2019-12-28 04:26
Duplicate of https://github.com/google/flutter-desktop-embedding/issues/483

**Closed by stuartmorgan** 2019-12-28 04:26 UTC
Labels: created via support template
