### ISSUE TITLE
Flutter Gallery alpha: Data tables filter outside the table

### ISSUE THREAD

**Issue by SeraphimSerapis** [flutter/flutter#14595] opened 2018-02-09 16:50 UTC
## Steps to Reproduce

1. Install the Flutter Gallery alpha from the Play store
2. Open the app & navigate to Material Components: Data tables
3. Scroll to the bottom
4. The filter on the bottom left is outside the table

![screenshot_20180209-092832_2](https://user-images.githubusercontent.com/160543/36038930-5640dd00-0dc1-11e8-94ca-c0653da6ed05.png)

**Comment by Hixie** [comment] 2018-02-13 06:16
This is working as intended -- the row can be scrolled.

cc @willlarche who may have ideas for what we should do instead of making the row scrollable?

**Comment by Hixie** [comment] 2018-02-13 18:31
Moving to m4 since this doesn't match our m3 criteria.

**Comment by Hixie** [comment] 2018-06-11 20:11
@willlarche Let me know if we get any specific guidance on this, otherwise in the meantime I'm going to leave this as-is on the basis that it's working as intended.

**Comment by willlarche** [comment] 2018-06-25 13:40
Requesting guidance. Stand-by.

**Comment by willlarche** [comment] 2018-06-26 18:22
Here's a design. Is this sufficient?

<img width="864" alt="screen shot 2018-06-26 at 10 53 32 am" src="https://user-images.githubusercontent.com/1271525/41931519-51234c8a-794c-11e8-8ef7-b9098dfc56d6.png">

**Comment by Hixie** [comment] 2018-06-27 19:34
Thanks. Is there a formal spec for this? (e.g. saying what the minimum width should be before we just report overflow because of a poorly-written UI, what we should do in different languages for the word "items", what we should do when the table is wider, etc)

**Comment by willlarche** [comment] 2018-06-28 00:22
No there isn't. Whomever is assigned to the work will need to have a proper kick-off with the designer.

**Comment by alvesluc** [comment] 2020-01-02 13:20
Hey @willlarche, do you have the source code of the design that you posted?
If you could link the repository I would be so greatful, thanks!

**Comment by willlarche** [comment] 2020-01-04 00:52
These are designer mocks actually.

**Comment by markusaksli-nc** [comment] 2020-09-08 12:25
Closing since this seems to be fixed

**Closed by markusaksli-nc** 2020-09-08 12:25 UTC
Labels: P5, f: material design, framework, team: gallery
