### ISSUE TITLE
When the Android status bar is opaque (e.g. on Android ≤‬4.x), align the view with the bottom of the status bar and set the padding to zero

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8802] opened 2017-03-15 18:18 UTC
![screenshot_2017-03-15-11-14-48](https://cloud.githubusercontent.com/assets/1227763/23964213/fbca5374-0970-11e7-8508-e54d383cf357.png)

**Comment by eseidelGoogle** [comment] 2017-03-15 20:27
We need to make the slow-mode banner window.padding aware. :)

**Comment by eseidelGoogle** [comment] 2017-03-15 20:29
Android 4 doesn't support transparent status bars, so we have to change how we layout/paint.  I think that's window.padding, you can see code in:
https://github.com/flutter/engine/tree/master/shell/platform/android/io/flutter
where we handle this version quirk.  But we'd have to ask one of the framework engineers what the exact right parts to check are.  Probably:
https://docs.flutter.io/flutter/dart-ui/Window/padding.html

**Comment by zoechi** [comment] 2018-11-28 14:05
Can still reproduce

```
 $ flutter doctor -v
[✓] Flutter (Channel beta, v0.11.10, on Mac OS X 10.14.1 18B75, locale en-AT)
    • Flutter version 0.11.10 at /Users/zoechi/flutter/flutter
    • Framework revision c27c4a265e (2 days ago), 2018-11-26 17:07:24 -0500
    • Engine revision eebc6a5895
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • emulator-5554 • emulator-5554 • android-x86 • Android 4.1.2 (API 16) (emulator)
```

**Comment by TahaTesser** [comment] 2020-07-21 13:17
I can reproduce the issue on Android 4.4 emulator

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (6 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2024-04-03 11:36
As this issue is related to Android version 4 or less which is roughly api 14 I think, which seems to be not supported anymore per https://docs.flutter.dev/reference/supported-platforms, so I'll close this issue as obsolete.
If anyone disagrees, please write in comments and I'll reopen it.

**Closed by darshankawar** 2024-04-03 11:36 UTC
Labels: platform-android, framework, a: layout, has reproducible steps, P3, found in release: 1.21, team-android, triaged-android
