### ISSUE TITLE
flutter should catch crashes from dart tools (like `sky_snapshot`) and offer to report them

### ISSUE THREAD

**Issue by 1hitOVER** [flutter/flutter#7305] opened 2016-12-23 02:21 UTC
I have a problem and i dont know why. I created a flutter app with flutter create app, then cd app, but when i execute flutter run nothing happen just a error: **Error detected in application source code:** and nothing else. HELP ME!
![instantanea8](https://cloud.githubusercontent.com/assets/15723713/21445845/30c660c8-c884-11e6-9d3a-0ceca14d413f.png)

**Comment by zoechi** [comment] 2016-12-23 05:17
try running `flutter packages upgrade`
Just a guess, I'm new to Flutter myself.

**Comment by 1hitOVER** [comment] 2016-12-23 06:00
nothing...

**Comment by Hixie** [comment] 2016-12-23 07:31
Can you run `flutter analyze; flutter run -v` and paste the output here?

**Comment by 1hitOVER** [comment] 2016-12-24 03:04
**$ flutter analyze; flutter run -v**

Analyzing lib/main.dart...
No analyzer warnings! (ran in 17.9s)
[  +50 ms] /home/brian/Android/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /home/brian/Android/platform-tools/adb devices -l
[        ] List of devices attached
           T8IFSOVOK7P7W4FM       device usb:1-7 product:me1_global_com model:LG_K120 device:me1
[  +18 ms] /home/brian/Android/platform-tools/adb -s T8IFSOVOK7P7W4FM shell getprop
[ +156 ms] /home/brian/Lang/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/brian/Documents/IntelliJProjects/Flutter/myapp/.packages --print-deps /home/brian/Documents/IntelliJProjects/Flutter/myapp/lib/main.dart
[  +32 ms] Exit code -11 from: /home/brian/Lang/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/brian/Documents/IntelliJProjects/Flutter/myapp/.packages --print-deps /home/brian/Documents/IntelliJProjects/Flutter/myapp/lib/main.dart
[        ] Error detected in application source code:
[   +4 ms] 'flutter run' took 241ms.

package:flutter_tools/src/base/common.dart 31                     throwToolExit
package:flutter_tools/src/commands/run.dart 250                   RunCommand.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 161                            HotRunner._run.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/run.dart 252                   RunCommand.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/hot.dart 161                            HotRunner._run.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 66                        pubGet.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 159                   RunCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 197         FlutterCommand.findTargetDevice.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 72                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119         FlutterCommand.run
package:args/command_runner.dart 194                              CommandRunner.runCommand.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:args/command_runner.dart                                  CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 224  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 72                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 109                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 150  FlutterCommandRunner.run
package:flutter_tools/executable.dart 122                         main.<async>.<fn>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 121                         main.<async>.<fn>
package:flutter_tools/src/base/context.dart 76                    AppContext._run.<async>


[ +103 ms] exiting with code 1

**Comment by Hixie** [comment] 2016-12-24 05:57
Ok so it looks like there's two bugs here:
- [ ] sky_snapshot is segfaulting (it had a -11 exit code)
- [ ] the flutter tool doesn't handle that gracefully and just fails without any useful error message

cc @jason-simmons who may have better ideas for how to debug the sky_snapshot crash - I don't really know where to begin in figuring out the cause here.

**Comment by Hixie** [comment] 2017-11-29 00:27
This bug is unfortunately no longer really actionable in its current state. We're going to close it. We've made a number of changes to the tool since it was filed so the underlying issues are probably resolved at this point; however, if you still see anything like this please don't hesitate to file a new bug.

**Closed by Hixie** 2017-11-29 00:27 UTC
Labels: crash, dev: tool, prod: engine
