### ISSUE TITLE
Command Line CTRL+Z: Hot reload & restart not work

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#71115] opened 2020-11-24 00:00 UTC
if i pressed CTRL+Z by error  in the command line
if i try to press r to make Hot reload or hot restart it will not work and i should re run my app again ...

VS Code windows 10 flutter 1.22.4

**Comment by iapicca** [comment] 2020-11-24 08:17
@imeDevelopers 
tested on `linux` with a fairly recent master, **ctrl+Z** extits the program as expected

```console
[✓] Flutter (Channel master, 1.24.0-8.0.pre.344, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-8.0.pre.344 at
      /home/francesco/snap/flutter/common/flutter
    • Framework revision de56c6ad72 (2 days ago), 2020-11-23 05:28:06 +0900
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      87.0.4280.66

• No issues found!

```

**Comment by darshankawar** [comment] 2020-11-24 09:16
@imeDevelopers 
Is it only happening with VSCode or with Android Studio too ?

**Comment by imeDevelopers** [comment] 2020-11-24 13:39
@darshankawar 
i dont work with android studio , so i not sure ..

my channel is stable on this flutter version ..

also the analyser take too long time to analyze any code 


the reason why i use this version of flutter is because the latest version stops the hot reload or hot restart and gives me stopped message because of 0 isolates founded or something like this ..

i had opened an case for this problem but dont know latest results and fixed or not ..

i will try to mention the issue here for you ..

i need to use latest flutter version but it has problems..

**Comment by imeDevelopers** [comment] 2020-11-24 13:42
@darshankawar

here it is

https://github.com/flutter/flutter/issues/68990

**Comment by imeDevelopers** [comment] 2020-11-24 13:49
@iapicca 
it should not exit from the terminal or do anything because this is not a vommand for the command line ...

of course the app still running, i mean the debug session i should rerun it again

**Comment by darshankawar** [comment] 2020-11-25 06:23
@imeDevelopers 
I don't use VScode so I can't replicate this issue. The issue you referred above was opened exactly a month ago which had earlier version of Stable, that indicates the issue is not with latest stable version (1.22.4). Is it possible for you to downgrade to previous stable version (ex : 1.20) and see if you still see the issue ?
Or you may also switch to latest master and confirm if issue persists.
Thanks.

**Comment by pedromassangocode** [comment] 2020-12-16 09:32
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-16 09:32 UTC
Labels: in triage, waiting for customer response
