### ISSUE TITLE
Errors with firebase_database [androidx-migration]

### ISSUE THREAD

**Issue by leaf-ridesharing** [flutter/flutter#44354] opened 2019-11-07 16:34 UTC
Hello there,

I'm trying to build an app login with firebase and flutter. When trying to run the app I get the following error messages:

> 
> Running Gradle task 'assembleDebug'...
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:10: error: cannot find symbol
> import androidx.annotation.NonNull;
>                           ^
>   symbol:   class NonNull
>   location: package androidx.annotation
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:11: error: cannot find symbol
> import androidx.annotation.Nullable;
>                           ^
>   symbol:   class Nullable
>   location: package androidx.annotation
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:233: error: cannot find symbol
>   public void onMethodCall(final MethodCall call, @NonNull final Result result) {
>                                                    ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:185: error: cannot find symbol
>         String eventType, @NonNull DataSnapshot snapshot, String previousChildName) {
>                            ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin.EventObserver
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:199: error: cannot find symbol
>     public void onCancelled(@NonNull DatabaseError error) {
>                              ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin.EventObserver
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:207: error: cannot find symbol
>     public void onChildAdded(@NonNull DataSnapshot snapshot, String previousChildName) {
>                               ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin.EventObserver
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:212: error: cannot find symbol
>     public void onChildRemoved(@NonNull DataSnapshot snapshot) {
>                                 ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin.EventObserver
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:217: error: cannot find symbol
>     public void onChildChanged(@NonNull DataSnapshot snapshot, String previousChildName) {
>                                 ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin.EventObserver
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:222: error: cannot find symbol
>     public void onChildMoved(@NonNull DataSnapshot snapshot, String previousChildName) {
>                               ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin.EventObserver
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:227: error: cannot find symbol
>     public void onDataChange(@NonNull DataSnapshot snapshot) {
>                               ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin.EventObserver
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:166: error: cannot find symbol
>     public void onComplete(@Nullable DatabaseError error, @NonNull DatabaseReference ref) {
>                             ^
>   symbol:   class Nullable
>   location: class FirebaseDatabasePlugin.DefaultCompletionListener
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:166: error: cannot find symbol
>     public void onComplete(@Nullable DatabaseError error, @NonNull DatabaseReference ref) {
>                                                            ^
>   symbol:   class NonNull
>   location: class FirebaseDatabasePlugin.DefaultCompletionListener
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:333: error: cannot find symbol
>                 public Transaction.Result doTransaction(@NonNull MutableData mutableData) {
>                                                          ^
>   symbol: class NonNull
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.7\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java:331: error: cannot find symbol
>                 @NonNull
>                  ^
>   symbol: class NonNull
> 14 errors
> *******************************************************************************************
> The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> *******************************************************************************************
> Finished with error: Gradle task assembleDebug failed with exit code 1
> 

I don't know which files would be helpful for troubleshooting. If you need something please tell me.

Help would be greatly appreciated.

Thanks

**Comment by iapicca** [comment] 2019-11-11 07:52
Hi @leaf-ridesharing  
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-11 07:52 UTC
