### ISSUE TITLE
Failed to start up and run

### ISSUE THREAD

**Issue by keiing** [flutter/flutter#146970] opened 2024-04-18 06:47 UTC
### Steps to reproduce

1. Create and generate a picture-related resource file .png/.jpg in the project directory, and configure it in assets under pubspec.yaml
2. Run the project flutter run. After the build is successful, after build flutter_assets has generated the resource file, close the current program.
3. Restart the program and it will prompt Target debug_bundle_windows_assets failed: PathExistsException: Cannot copy file to
'C:\Users\xx\example\build\flutter_assets\images/app_logo.png', path =
'C:\Users\xx\example\images\xx.png' (OS Error: The file cannot be created when it already exists.?

Expected results

I hope that when the project is re-run, the project will automatically overwrite or skip updating the current resources and run the project successfully.

Actual results

In fact, after the current project resources have been generated, the file cannot be created. The startup fails and an error is reported, and the operation is automatically terminated.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
// 创建基础demo后配置 assets资源图片，运行多次即可复现
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [版本 10.0.22631.3447], locale zh-CN)
    • Flutter version 3.19.6 on channel stable at C:\Users\cc\onSDKS\flutterDir\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (11 hours ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\cc\AppData\Local\Android\Sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\cc\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at C:\Program Files (x86)\Chromebrowser\Chrome.exe)
    ! C:\Program Files (x86)\Chromebrowser\Chrome.exe is not executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.7)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34601.278
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.3
    • Flutter plugin version 77.1.3
    • Dart plugin version 232.10248

[√] VS Code (version 1.88.1)
    • VS Code at C:\Users\cc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.86.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3447]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.97

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-04-18 10:03
Closing this as a duplicate of https://github.com/flutter/flutter/issues/90028

**Closed by danagbemava-nc** 2024-04-18 10:03 UTC
Labels: in triage
