### ISSUE TITLE
[SelectableText] click word segmentation selection

### ISSUE THREAD

**Issue by jlcool** [flutter/flutter#47720] opened 2019-12-24 07:02 UTC
The text box of Chinese Android mobile phone supports click word segmentation selection. How to achieve this function in flutter.
like this https://youtu.be/LkcOuvhyXcA

**Comment by iapicca** [comment] 2019-12-24 15:24
Hi @jlcool  
can you please provide your `flutter doctor -v` 
and  a minimal code sample
or the steps to reproduce the problem?
Thank you

**Comment by jlcool** [comment] 2019-12-25 00:32
Hi @iapicca , I think it should be a function rather than a problem
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.6 at /Users/jiangliang/development/flutter
    • Framework revision 18cd7a3601 (13 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jiangliang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools
```
code sample
``` dart
TextField(controller: TextEditingController(text:"你好我是小明"),);
```
Long press "你好" in flutter, only one of the words can be selected
![textfield](https://github.com/jlcool/flutter_android_edittext/blob/master/example/lib/textfield.png?raw=true)

**Comment by KagurazakaHanabi** [comment] 2019-12-29 01:28
Maybe duplicate of #19584

**Comment by iapicca** [comment] 2020-01-10 09:11
Hi @jlcool 
sd @KagurazakaHanabi  pointed out (thank you)
there's an open [issue ](https://github.com/flutter/flutter/issues/19584)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you"

**Closed by iapicca** 2020-01-10 09:11 UTC
Labels: a: typography, f: material design, framework

**Comment by jlcool** [comment] 2020-01-11 10:08
Looking forward to solving the problem as soon as possible, thank you
