### ISSUE TITLE
[web] Multiline selection in TextField does not work properly

### ISSUE THREAD

**Issue by mordivgor** [flutter/flutter#51284] opened 2020-02-23 12:18 UTC
## Steps to Reproduce

    return TextField(
      enableInteractiveSelection: true,
      style: TextStyle(
        height: 2
      ),
      maxLines: null,
      keyboardType: TextInputType.multiline,
      decoration: const InputDecoration(
        border: InputBorder.none,
        hintText: 'Your article',
        labelText: 'Article'
      ),
      controller: _textController
    );

**Expected results:**

Selection of text shall work as normal - moving cursor above the next shall select text in area under the cursor.

**Actual results:**

If text in TextField occupies at least two lines, there is misleading behavior of text selection.
![text_field_bug_1](https://user-images.githubusercontent.com/54472480/75111899-e77e5a00-563e-11ea-8beb-8595eaad42a5.gif)

<details>
  <summary>Logs</summary>

[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.18362.657], locale pl-PL)
    • Flutter version 1.14.6 at G:\IOT\flutter\flutter
    • Framework revision fabeb2a16f (4 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Radek\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.116
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

</details>

**Comment by TahaTesser** [comment] 2020-02-24 09:21
Duplicate of [#50101](https://github.com/flutter/flutter/issues/50101)

**Closed by TahaTesser** 2020-02-24 09:21 UTC
