### ISSUE TITLE
Android runTransaction crash when doing multiple update, deletes

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#31668] opened 2019-04-26 12:37 UTC
It is really unfortunate that the firestore Transaction is really not usable at the moment. I was trying to do some simple things as below but it crashed with "Transaction has already completed". It just do not work as expected. 
```
  for (Item item in items) {
    final doc = Firestore.instance
        .collection(COLLECTION_CARTS)
        .document(item.id);
    await trans.delete(doc);
  }
```

After got stuck for a few days, I started to look into the android CloudFirestorePlugin.java and found this 
```
  private final SparseArray<Transaction> transactions = new SparseArray<>();

  private Transaction getTransaction(Map<String, Object> arguments) {
    return transactions.get((Integer) arguments.get("transactionId"));
  }

  @Override
  public void onMethodCall(MethodCall call, final Result result) {
    ...
    case "Transaction#delete":
            {
              final Map<String, Object> arguments = call.arguments();
              final Transaction transaction = getTransaction(arguments);
              new AsyncTask<Void, Void, Void>() {
                @Override
                protected Void doInBackground(Void... voids) {
                  transaction.delete(getDocumentReference(arguments));
                  result.success(null);
                  return null;
                }
              }.execute();
              break;
        }
        ...
   }
```
So above code means you will be using the same transaction instance to perform all operations. But the weird part is in the core/Transaction.java
```

public void delete(DocumentKey key) {
    this.write(Collections.singletonList(new DeleteMutation(key, this.precondition(key))));
    this.readVersions.put(key, SnapshotVersion.NONE);
}

private void write(List<Mutation> mutations) {
    if (this.committed) {
        throw new IllegalStateException("Transaction has already completed.");
    } else {
        this.mutations.addAll(mutations);
    }
}

public Task<Void> commit() {
    ...
    this.committed = true;
    ...
}
```
Somehow, when you finish one operation, this.committed becomes true which means you will get this error "Transaction has already completed." every time if you perform another action with the same transaction. 

I don't know why this is designed this way, but it makes transaction really not doing what it should be.  To be honest, WriteBatch and Transaction issues have been out there for quite long time, they really need someone to fix it or they should not be put out there. Really frustrating.

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment] 2019-10-16 14:25
@PandaGeek1024 how's it while using current cloud_firestore 0.12.9+5?

**Comment by iapicca** [comment] 2019-11-08 09:54
Hi @PandaGeek1024 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:54 UTC
Labels: waiting for customer response
