### ISSUE TITLE
The PR checks failed by accident, and the contributors can not retry.

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#64291] opened 2020-08-21 00:58 UTC
The PR checks failed by accident, and the contributors can not retry. https://ci.chromium.org/p/flutter/builders/try/Linux%20web_tests/728?
![image](https://user-images.githubusercontent.com/61075224/90840384-710faa00-e38c-11ea-96ff-7b7635258d37.png)

**Comment by godofredoc** [comment] 2020-08-21 01:57
This is working as intended, the correct way to retry the builds is from the github ui:


![image](https://user-images.githubusercontent.com/54371434/90843611-e0e34d80-e316-11ea-9fea-01f67a4ecbfa.png)

**Comment by xu-baolin** [comment] 2020-08-21 02:03
Why there is nothing here?
![image](https://user-images.githubusercontent.com/61075224/90843925-4aa23c80-e395-11ea-88da-be06fc652af2.png)

**Comment by digiter** [comment] 2020-08-27 22:25
Triage: @Hixie Would you mind taking a look at the permissions?

**Comment by Hixie** [comment] 2020-08-27 22:44
Which permissions specifically? I'm not aware of anything that controls who can retry; I assume it's always that only contributors (as in, people in the flutter-hackers group) can retry. (See https://github.com/flutter/flutter/wiki/Contributor-access for the process for getting contributor access.)

**Comment by Hixie** [comment] 2020-08-27 22:45
(in the meantime you can always force it by just pushing to the branch again)

**Comment by godofredoc** [comment] 2021-10-13 21:39
Closing as obsolete. Please reopen if this is still an issue.

**Closed by godofredoc** 2021-10-13 21:39 UTC
Labels: team, passed first triage, team: infra, passed secondary triage, P4
