### ISSUE TITLE
Dashboard commit hash link no longer links to the GitHub commit

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#132134] opened 2023-08-08 15:53 UTC
Maybe this is a problem with my browser, but for me clicking on the link in the screenshot below used to (yesterday) open the GitHub page for the commit in a new tab. Now it does nothing.

<img width="399" alt="Screenshot 2023-08-08 at 8 51 24 AM" src="https://github.com/flutter/flutter/assets/6343103/3846eb74-c50c-4cc8-a6de-adaa48781c69">

**Comment by keyonghan** [comment] 2023-08-08 16:04
Huh, no changes related to the dashboard these days, and I have no issue with the links. Could you try refreshing the page to give it a try, or reboot chrome?

**Comment by zanderso** [comment] 2023-08-08 16:10
Yeah, I've updated chrome, refreshed the page, and quit and restarted chrome. The links still don't work.

**Comment by keyonghan** [comment] 2023-08-11 16:05
I am still not able to reproduce this issue. @zanderso Do these links work for you by any chance?

**Comment by keyonghan** [comment] 2023-08-14 18:19
Moving out of ticket as this seems not a general blocker.

**Comment by CaseyHillers** [comment] 2023-08-17 19:07
If I click the copy button, it opens the github page. I assume we need to bisect between Aug 2 - 8 to find the Flutter commit that caused some changed in the tap boundaries.

**Comment by ricardoamador** [comment] 2023-08-23 22:07
Closing s this only affects 1 person.

**Comment by ricardoamador** [comment] 2023-08-23 22:08
Issue Casey has mentioned is tracked here: https://github.com/flutter/flutter/issues/132783

**Comment by CaseyHillers** [comment] 2023-08-23 22:08
> Closing s this only affects 1 person.

Can we not close valid issues only because it impacts 1 person? For reference, this impacts ~10 people

**Closed** 2023-08-23 22:08 UTC
Labels: team-infra

**Comment by ricardoamador** [comment] 2023-08-23 22:11
We could not reproduce this.

**Comment by CaseyHillers** [comment] 2023-08-23 22:19
Here's a video! https://github.com/flutter/flutter/assets/2148558/821b2295-f52b-4129-8933-a539977767be

The expected behavior is clicking the commit hash opens the github pages, and the copy button copies the sha.

If we're closing this due to missing reproduction, should we reopen?
