### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by dashu1999** [flutter/flutter#101517] opened 2022-04-07 14:55 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:53:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:486:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:93:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:156:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:214:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
    • Flutter version 2.1.0-12.2.pre at D:\Webdesign Year 3\flutter\flutter
    • Framework revision 5bedb7b1d5 (1 year, 1 month ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\darsh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Java\jdk-14.0.2\bin\java
    • Java version Java(TM) SE Runtime Environment (build 14.0.2+12-46)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.66.0)
    • VS Code at C:\Users\darsh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 99.0.1150.55

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 2738a1148ba6c9a6114df62358109407c3ef2553
### Plugins
flutter_facebook_login-3.0.0
flutter_plugin_android_lifecycle-1.0.11
flutter_secure_storage-3.3.5
image_picker-0.6.7+22
path_provider-2.0.4
path_provider_linux-2.1.0
path_provider_macos-2.0.2
path_provider_windows-2.0.3

**Comment by danagbemava-nc** [comment] 2022-04-08 06:56
Hi @dashu1999, this is a duplicate of #95916.

If you have any information on how to reproduce or what you were doing when you experienced this issue, kindly provide more details in #95916. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-04-08 06:56 UTC
Labels: in triage
