### ISSUE TITLE
The "Add Flutter to existing apps" wiki need to be updated

### ISSUE THREAD

**Issue by excitedhaha** [flutter/flutter#34312] opened 2019-06-12 05:59 UTC
The "Add Flutter to existing apps" wiki last updated November 26, 2018, a half year passed. Even stable channel includes this feature now, however, the master channel may lead to error like "Cannot change dependencies of configuration ':flutter:releaseApi' after it has been included in dependency resolution".

**Comment by pratikjain04** [comment] 2019-06-20 12:25
I am facing the same issue while integrating it with my existing Java Project, although it works fine with newly created Java Projects, but the "Gradle Sync" fails, saying: "Cannot change dependencies of configuration ':flutter:releaseApi' after it has been included in dependency resolution".

**Comment by excitedhaha** [comment] 2019-06-20 14:20
> I am facing the same issue while integrating it with my existing Java Android Project, although it works fine with newly created Java Android Projects, but the "Gradle Sync" fails, saying: "Cannot change dependencies of configuration ':flutter:releaseApi' after it has been included in dependency resolution" in the existing ones.

As I said, you can switch to the stable channel

**Comment by pratikjain04** [comment] 2019-06-20 14:23
I am already on the stable channel

**Comment by pratikjain04** [comment] 2019-06-21 07:18
So, I went to beta channel and then came back to stable channel, ran "flutter upgrade" and restarted my IDE, and this issue was resolved.
But the gradle sync fails, by saying: 
"ERROR: Resolving this BuildableArtifact can only done during task execution.
Affected Modules: flutter"

**Comment by LudySu** [comment] 2019-07-16 23:19
I came across the same issue, I think it's common when anyone integrates a flutter module into existing Android app after upgrading flutter to `v1.7.8+hotfix.3`.

I did a bit of the experiment around it:

1. Upgrade flutter to latest `v1.7.8+hotfix.3`
2. Do a gradle sync in my Android app (which was successfuly before upgrading flutter tool) -> It fails with message "Cannot change dependencies of configuration ':flutter:releaseApi' after it has been included in dependency resolution"
3. Check out only the file `packages/flutter_tools/gradle/flutter.gradle` to commit `3d09f939ba1b076a584e41a9c7d69cca1d1ceb49`
4. Do a gradle sync in my Android app -> It is successful
5. Check out only the file `packages/flutter_tools/gradle/flutter.gradle` to commit `90f38907d70481970046652c61565f896f40595b` -> It fails with the same error message

So I think it's a bug in flutter tool script `packages/flutter_tools/gradle/flutter.gradle` after adding 64-bit support in commit `90f38907d70481970046652c61565f896f40595b`. And it hasn't been fixed in the latest (17th July) commit `c50fa3d2bdc5abd8bdf2512f041240dfa4e73578`.

Flutter team please fix this issue.

**Comment by LudySu** [comment] 2019-07-23 03:47
Update to my last comment. I set up a minimal project [FlutterHybridExample](https://github.com/LudySu/FlutterHybridExample) following the "**Add Flutter to existing apps**" page, the very same  `v1.7.8+hotfix.3` flutter tool successfully builds the app bundle with 64-bit so library inside without the "_Cannot change dependencies of configuration ':flutter:releaseApi' after it has been included in dependency resolution_" error.

So I am guessing the current script `packages/flutter_tools/gradle/flutter.gradle` works for simple project settings, but not the complex ones. In my case, my app has multiple modules and some gradle script

**Comment by LudySu** [comment] 2019-07-31 00:17
Found a way to mitigate this build error. In my projects `gradle.properties` file, set `org.gradle.parallel=false` to disable parallel building. Then I was able to build an APK packed with 64-bit flutter binaries.

So the cause of this build error is the new changes from `v1.5.4` to `v1.7.8+hotfix.3` made the flutter sub-project a tightly coupled one, while parallel option should only be used with decoupled projects.

@shihaohong can you please update the ticket to reflect the true cause? I can see there are tons of issues in flutter project and this one doesn't look like a high priority one, it would be great if you could give any clue on how to fix the `packages/flutter_tools/gradle/flutter.gradle` script?

Cheers

**Comment by shihaohong** [comment] 2019-07-31 01:24
cc/ @xster, who I think is working add2app

**Comment by xster** [comment] 2019-07-31 01:33
It is indeed being updated shortly

@blasten @jmagman

**Comment by excitedhaha** [comment] 2019-08-02 03:01
Hi, all. The latest master channel fixed this problem, please give a try.

**Comment by jmagman** [comment] 2019-08-02 03:29
We've recently updated the wiki, and we're actively working on the feature. If you encounter specific errors or incorrect instructions in the wiki, please create new issues and include the output of `flutter doctor -v`. Make sure you are on the master channel, and have run `flutter upgrade`.

**Closed by jmagman** 2019-08-02 03:29 UTC
Labels: a: existing-apps, d: wiki
