### ISSUE TITLE
'TextPainter - forced line-wrapping with bidi' is failing on everything except web

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#13658] opened 2017-12-18 21:28 UTC
Many of the offsets in this test are incorrect on Windows. Here's an example:
```dart
// Actual
const Offset(7.0, 12.0);
// Expected
const Offset(10.0, 10.0);
```

According to @Hixie, this shouldn't be happening since the "Ahem" font should be the same across platforms. This test is disabled on Windows for now.

**Comment by markusaksli-nc** [comment] 2020-07-23 11:41
Reproducible on the latest master `1.21.0-2.0.pre.114` on Windows and Android when running all of [text_painter_rtl_test.dart](https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/test/painting/text_painter_rtl_test.dart). Does not fail on web or IOS.
<details>
 <summary>Windows logs</summary>

 ```
flutter: 00:00 +0: TextPainter - basic words
flutter: 00:00 +1: TextPainter - bidi overrides in LTR
flutter: 00:00 +1 ~1: TextPainter - bidi overrides in RTL
flutter: 00:00 +1 ~2: TextPainter - forced line-wrapping with bidi
flutter: 00:00 +1 ~2: TextPainter - forced line-wrapping with bidi [E]
flutter:   Expected: Offset:<Offset(0.0, 0.0)>
    Actual: Offset:<Offset(0.0, -0.3)>

flutter:   package:test_api/src/frontend/expect.dart 154:30               fail
  package:test_api/src/frontend/expect.dart 148:3                _expect
  package:test_api/src/frontend/expect.dart 60:3                 expect
  package:flutter_test/src/widget_tester.dart 370:3              expect
  package:windows/main.dart 281:5                                main.<fn>
  package:test_api/src/backend/declarer.dart 171:19              Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 226:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 381:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 368:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 413:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 367:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 100:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 366:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 152:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop

flutter: 00:00 +1 ~2 -1: TextPainter - line wrap mid-word
flutter: 00:00 +1 ~3 -1: TextPainter - line wrap mid-word, bidi - LTR base
flutter: 00:00 +1 ~4 -1: TextPainter - line wrap mid-word, bidi - RTL base
flutter: 00:00 +1 ~5 -1: TextPainter - multiple levels
flutter: 00:00 +1 ~6 -1: TextPainter - getPositionForOffset - RTL in LTR
flutter: 00:00 +1 ~7 -1: TextPainter - getPositionForOffset - LTR in RTL
flutter: 00:00 +1 ~8 -1: TextPainter - Spaces
flutter: 00:00 +1 ~9 -1: TextPainter - empty text baseline
flutter: 00:00 +1 ~10 -1: Some tests failed.
```
</details>
<details>
 <summary>Android logs</summary>

 ```
I/flutter (30621): 00:00 +0: TextPainter - basic words
I/flutter (30621): 00:00 +1: TextPainter - bidi overrides in LTR
I/flutter (30621): 00:00 +1 ~1: TextPainter - bidi overrides in RTL
I/flutter (30621): 00:00 +1 ~2: TextPainter - forced line-wrapping with bidi
I/flutter (30621): 00:00 +1 ~2: TextPainter - forced line-wrapping with bidi [E]
I/flutter (30621):   Expected: Offset:<Offset(0.0, 0.0)>
I/flutter (30621):     Actual: Offset:<Offset(0.0, 0.3)>
I/flutter (30621):   
I/flutter (30621):   package:test_api/src/frontend/expect.dart 154:30               fail
I/flutter (30621):   package:test_api/src/frontend/expect.dart 148:3                _expect
I/flutter (30621):   package:test_api/src/frontend/expect.dart 60:3                 expect
I/flutter (30621):   package:flutter_test/src/widget_tester.dart 370:3              expect
I/flutter (30621):   package:triage/main.dart 281:5                                 main.<fn>
I/flutter (30621):   package:test_api/src/backend/declarer.dart 171:19              Declarer.test.<fn>.<fn>
I/flutter (30621):   ===== asynchronous gap ===========================
I/flutter (30621):   dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
I/flutter (30621):   dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
I/flutter (30621):   package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
I/flutter (30621):   dart:async/zone.dart 1190:13                                   _rootRun
I/flutter (30621):   dart:async/zone.dart 1093:19                                   _CustomZone.run
I/flutter (30621):   dart:async/zone.dart 1630:10                                   _ru
I/flutter (30621): 00:00 +1 ~2 -1: TextPainter - line wrap mid-word
I/flutter (30621): 00:00 +1 ~3 -1: TextPainter - line wrap mid-word, bidi - LTR base
I/flutter (30621): 00:00 +1 ~4 -1: TextPainter - line wrap mid-word, bidi - RTL base
I/flutter (30621): 00:00 +1 ~5 -1: TextPainter - multiple levels
I/flutter (30621): 00:00 +1 ~6 -1: TextPainter - getPositionForOffset - RTL in LTR
I/flutter (30621): 00:00 +1 ~7 -1: TextPainter - getPositionForOffset - LTR in RTL
I/flutter (30621): 00:00 +1 ~8 -1: TextPainter - Spaces
I/flutter (30621): 00:00 +1 ~9 -1: TextPainter - empty text baseline
I/flutter (30621): 00:00 +1 ~10 -1: Some tests failed.
```
</details>
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-2.0.pre.114, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.21.0-2.0.pre.114 at C:\Development\flutter_master
    • Framework revision ddb8e6e3bf (7 hours ago), 2020-07-22 20:00:07 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.900]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment] 2020-09-18 08:18
Closing since https://github.com/flutter/flutter/issues/32238 is more relevant.

**Closed by markusaksli-nc** 2020-09-18 08:18 UTC
Labels: P4, a: internationalization, a: tests, a: typography, found in release: 1.21, framework, has reproducible steps, platform-android, platform-ios, platform-linux, platform-mac, platform-windows
