### ISSUE TITLE
Malformed BoxConstraints Error

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#35690] opened 2019-07-07 05:04 UTC
It's a valid error, but it's misformatted and says to report it. 

Basically, I used a `AnimatedCrossFade` to fade between two images. Previously, it was the whole `body` of the `Scaffold`, so I set their constraints to `double.infinity`. Placing this inside a `AnimatedCrossFade` made things weird. 

Code: 
```dart
Widget build (BuildContext) => Scaffold (
    body: CrossFadeTransition (
        firstChild: Image.asset ("some image", height: double.infinity, width: double.infinity, fit: BoxFit.fitWidth),
        secondChild: Image.asset ("some other image", height: double.infinity, width: double.infinity, fit: BoxFit.width),
    )
);
```

The error comes out like this: 
```dart
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
dart_sdk.js:18737 The following assertion was thrown during performLayout():
dart_sdk.js:18737 FlutterError contained multiple error summaries.
dart_sdk.js:18737 All FlutterError objects should have only a single short (one line) summary description of the
dart_sdk.js:18737 problem that was detected.
dart_sdk.js:18737 Malformed FlutterError:
dart_sdk.js:18737   RenderImage object was given an infinite size during layout.
dart_sdk.js:18737   This probably means that it is a render object that tries to be as big as possible, but it was put
dart_sdk.js:18737   inside another render object that allows its children to pick their own size.
dart_sdk.js:18737   RenderImage object was given an infinite size during layout.
dart_sdk.js:18737   This probably means that it is a render object that tries to be as big as possible, but it was put
dart_sdk.js:18737   inside another render object that allows its children to pick their own size.
dart_sdk.js:18737   The nearest ancestor providing an unbounded height constraint is: RenderStack#cf3c4 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
dart_sdk.js:18737     creator: Stack ← AnimatedSize ← ClipRect ← AnimatedCrossFade ← Center ← ImageCarousel ← MediaQuery ←
dart_sdk.js:18737       LayoutId-[Object <_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ←
dart_sdk.js:18737       DefaultTextStyle ← AnimatedDefaultTextStyle ← ⋯
dart_sdk.js:18737     parentData: offset=Offset(0.0, 0.0) (can use size)
dart_sdk.js:18737     constraints: BoxConstraints(0.0<=w<=1504.0, 0.0<=h<=734.0)
dart_sdk.js:18737     size: Size(1504.0, 734.0)
dart_sdk.js:18737     alignment: AlignmentDirectional.topStart
dart_sdk.js:18737     textDirection: ltr
dart_sdk.js:18737     fit: loose
dart_sdk.js:18737     overflow: visible
dart_sdk.js:18737   The constraints that applied to the RenderImage were:
dart_sdk.js:18737     BoxConstraints(w=1504.0, 0.0<=h<=Infinity)
dart_sdk.js:18737   The exact size it was given was:
dart_sdk.js:18737     Size(1504.0, Infinity)
dart_sdk.js:18737   See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.
dart_sdk.js:18737 
dart_sdk.js:18737 The malformed error has 2 summaries.
dart_sdk.js:18737 Summary 1: RenderImage object was given an infinite size during layout.
dart_sdk.js:18737 Summary 2: RenderImage object was given an infinite size during layout.
dart_sdk.js:18737 
dart_sdk.js:18737 This error should still help you solve your problem, however please also report this malformed error
dart_sdk.js:18737 in the framework by filing a bug on GitHub:
dart_sdk.js:18737   https://github.com/flutter/flutter/issues/new?template=BUG.md
dart_sdk.js:18737 
dart_sdk.js:18737 When the exception was thrown, this was the stack:
dart_sdk.js:18737 dart:sdk_internal 4556:11                                    throw
dart_sdk.js:18737 package:flutter_web/src/foundation/assertions.dart 549:9     <fn>
dart_sdk.js:18737 package:flutter_web/src/foundation/assertions.dart 551:14    fromParts
dart_sdk.js:18737 package:flutter_web/src/rendering/box.dart 2018:9            <fn>
dart_sdk.js:18737 package:flutter_web/src/rendering/box.dart 2093:14           debugAssertDoesMeetConstraints
dart_sdk.js:18737 package:flutter_web/src/rendering/box.dart 1780:7            <fn>
dart_sdk.js:18737 package:flutter_web/src/rendering/box.dart 1781:14           set size
dart_sdk.js:18737 package:flutter_web/src/rendering/image.dart 327:9           performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/stack.dart 570:14          performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/animated_size.dart 179:10  performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 1208:5      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/shifted_box.dart 409:12    performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/custom_layout.dart 140:10  layoutChild
dart_sdk.js:18737 package:flutter_web/src/material/scaffold.dart 360:7         performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/custom_layout.dart 206:7   [_callPerformLayout]
dart_sdk.js:18737 package:flutter_web/src/rendering/custom_layout.dart 348:32  performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 1208:5      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 3172:7      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/stack.dart 525:14          performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/proxy_box.dart 105:12      performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1821:7         layout
dart_sdk.js:18737 package:flutter_web/src/rendering/view.dart 158:29           performLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 1679:7         [_layoutWithoutResize]
dart_sdk.js:18737 package:flutter_web/src/rendering/object.dart 937:38         flushLayout
dart_sdk.js:18737 package:flutter_web/src/rendering/binding.dart 347:18        drawFrame
dart_sdk.js:18737 package:flutter_web/src/widgets/binding.dart 711:7           drawFrame
dart_sdk.js:18737 package:flutter_web/src/rendering/binding.dart 286:5         [_handlePersistentFrameCallback]
dart_sdk.js:18737 package:flutter_web/src/scheduler/binding.dart 1030:7        [_invokeFrameCallback]
dart_sdk.js:18737 package:flutter_web/src/scheduler/binding.dart 963:29        handleDrawFrame
dart_sdk.js:18737 package:flutter_web/src/scheduler/binding.dart 778:7         <fn>
dart_sdk.js:18737 dart:sdk_internal 15521:9                                    internalCallback
dart_sdk.js:18737 
dart_sdk.js:18737 The following RenderObject was being processed when the exception was fired: RenderImage#f6253 relayoutBoundary=up8 NEEDS-LAYOUT NEEDS-PAINT:
dart_sdk.js:18737   creator: RawImage ← Semantics ← Image ← FadeTransition ← ExcludeSemantics ←
dart_sdk.js:18737     TickerMode-[<CrossFadeState.showSecond>] ← Positioned-[<CrossFadeState.showSecond>] ← Stack ←
dart_sdk.js:18737     AnimatedSize ← ClipRect ← AnimatedCrossFade ← Center ← ⋯
dart_sdk.js:18737   parentData: <none> (can use size)
dart_sdk.js:18737   constraints: BoxConstraints(w=1504.0, 0.0<=h<=Infinity)
dart_sdk.js:18737   size: Size(1504.0, Infinity)
dart_sdk.js:18737   image: null
dart_sdk.js:18737   width: Infinity
dart_sdk.js:18737   height: Infinity
dart_sdk.js:18737   fit: fitHeight
dart_sdk.js:18737   alignment: center
dart_sdk.js:18737   invertColors: false
dart_sdk.js:18737   filterQuality: low
dart_sdk.js:18737 This This RenderObject has no descendants.
dart_sdk.js:18737 ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I believe the reason for this error having the same message twice is that the `AnimatedCrossFade` widget essentially is just a stack of both widgets, and since each `Image` has infinite constraints, the image propogates twice.

**Comment by matthew-carroll** [comment] 2020-05-31 01:33
I see that this bug is referring to the malformed error. That seems like an issue in its own right.

FYI, the underlying constraints issue that is reported here is, itself, reported as a bug, too: https://github.com/flutter/flutter/issues/57782

**Comment by markusaksli-nc** [comment] 2020-08-05 14:43
Hi @Levi-Lesches 
Can you confirm that this error is still malformed on the latest master? Not sure what crossfade setup you were exactly using but I can't reproduce this.
<details>
 <summary>Used sample code</summary>

 ```dart
import 'package:flutter/material.dart';

void main() => runApp(Directionality(
      textDirection: TextDirection.ltr,
      child: AnimatedCrossFade(
        crossFadeState: CrossFadeState.showFirst,
        duration: const Duration(milliseconds: 500),
        firstChild: Image.asset(
          "image.png",
          width: double.infinity,
          height: double.infinity,
          color: Colors.red,
        ),
        secondChild: Image.asset(
          "image.png",
          width: double.infinity,
          height: double.infinity,
          color: Colors.blue,
        ),
      ),
    ));
```
</details>
<details>
 <summary>Exceptions</summary>

 ```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderImage object was given an infinite size during layout.

This probably means that it is a render object that tries to be as big as possible, but it was put inside another render object that allows its children to pick their own size.
The nearest ancestor providing an unbounded height constraint is: RenderStack#6ee65 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0)
...  constraints: BoxConstraints(w=360.0, h=740.0)
...  size: Size(360.0, 740.0)
...  alignment: AlignmentDirectional.topStart
...  textDirection: ltr
...  fit: loose
...  clipBehavior: none
The constraints that applied to the RenderImage were: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
The exact size it was given was: Size(360.0, Infinity)

See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.

The relevant error-causing widget was: 
  Image file:///Users/markus/Desktop/triage/lib/main.dart:14:28
When the exception was thrown, this was the stack: 
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1988:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2056:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1774:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1776:6)
#4      RenderImage.performLayout (package:flutter/src/rendering/image.dart:370:5)
...
The following RenderObject was being processed when the exception was fired: RenderImage#fb55f relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
...  size: Size(360.0, Infinity)
...  image: null
...  width: Infinity
...  height: Infinity
...  color: MaterialColor(primary value: Color(0xff2196f3))
...  alignment: center
...  invertColors: false
...  filterQuality: low
RenderObject: RenderImage#fb55f relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
  size: Size(360.0, Infinity)
  image: null
  width: Infinity
  height: Infinity
  color: MaterialColor(primary value: Color(0xff2196f3))
  alignment: center
  invertColors: false
  filterQuality: low
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderSemanticsAnnotations object was given an infinite size during layout.
The relevant error-causing widget was: 
  Image file:///Users/markus/Desktop/triage/lib/main.dart:14:28
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#93fc6 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
  size: Size(360.0, Infinity)
  child: RenderImage#fb55f relayoutBoundary=up4 NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
    size: Size(360.0, Infinity)
    image: null
    width: Infinity
    height: Infinity
    color: MaterialColor(primary value: Color(0xff2196f3))
    alignment: center
    invertColors: false
    filterQuality: low
RenderObject: RenderSemanticsAnnotations#93fc6 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
  size: Size(360.0, Infinity)
  child: RenderImage#fb55f relayoutBoundary=up4 NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
    size: Size(360.0, Infinity)
    image: null
    width: Infinity
    height: Infinity
    color: MaterialColor(primary value: Color(0xff2196f3))
    alignment: center
    invertColors: false
    filterQuality: low
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderAnimatedOpacity object was given an infinite size during layout.
The relevant error-causing widget was: 
  AnimatedCrossFade file:///Users/markus/Desktop/triage/lib/main.dart:5:14
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderExcludeSemantics object was given an infinite size during layout.
The relevant error-causing widget was: 
  AnimatedCrossFade file:///Users/markus/Desktop/triage/lib/main.dart:5:14
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderImage object was given an infinite size during layout.

This probably means that it is a render object that tries to be as big as possible, but it was put inside another render object that allows its children to pick their own size.
The nearest ancestor providing an unbounded height constraint is: RenderStack#6ee65 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0)
...  constraints: BoxConstraints(w=360.0, h=740.0)
...  size: Size(360.0, 740.0)
...  alignment: AlignmentDirectional.topStart
...  textDirection: ltr
...  fit: loose
...  clipBehavior: none
The constraints that applied to the RenderImage were: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
The exact size it was given was: Size(360.0, Infinity)

See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.

The relevant error-causing widget was: 
  Image file:///Users/markus/Desktop/triage/lib/main.dart:14:28
When the exception was thrown, this was the stack: 
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1988:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2056:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1774:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1776:6)
#4      RenderImage.performLayout (package:flutter/src/rendering/image.dart:370:5)
...
The following RenderObject was being processed when the exception was fired: RenderImage#fb55f relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
...  size: Size(360.0, Infinity)
...  image: null
...  width: Infinity
...  height: Infinity
...  color: MaterialColor(primary value: Color(0xff2196f3))
...  alignment: center
...  invertColors: false
...  filterQuality: low
RenderObject: RenderImage#fb55f relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
  size: Size(360.0, Infinity)
  image: null
  width: Infinity
  height: Infinity
  color: MaterialColor(primary value: Color(0xff2196f3))
  alignment: center
  invertColors: false
  filterQuality: low
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderSemanticsAnnotations object was given an infinite size during layout.
The relevant error-causing widget was: 
  Image file:///Users/markus/Desktop/triage/lib/main.dart:14:28
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#93fc6 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
  size: Size(360.0, Infinity)
  child: RenderImage#fb55f relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
    size: Size(360.0, Infinity)
    image: null
    width: Infinity
    height: Infinity
    color: MaterialColor(primary value: Color(0xff2196f3))
    alignment: center
    invertColors: false
    filterQuality: low
RenderObject: RenderSemanticsAnnotations#93fc6 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
  size: Size(360.0, Infinity)
  child: RenderImage#fb55f relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
    size: Size(360.0, Infinity)
    image: null
    width: Infinity
    height: Infinity
    color: MaterialColor(primary value: Color(0xff2196f3))
    alignment: center
    invertColors: false
    filterQuality: low
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderAnimatedOpacity object was given an infinite size during layout.
The relevant error-causing widget was: 
  AnimatedCrossFade file:///Users/markus/Desktop/triage/lib/main.dart:5:14
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderExcludeSemantics object was given an infinite size during layout.
The relevant error-causing widget was: 
  AnimatedCrossFade file:///Users/markus/Desktop/triage/lib/main.dart:5:14
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>
<details>
 <summary>flutter doctor -v</summary>

 ```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.191, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.191 at /Users/markus/development/flutter_master
    • Framework revision f3b7788f77 (5 hours ago), 2020-08-05 00:11:03 -0400
    • Engine revision e1828008b9
    • Dart version 2.10.0 (build 2.10.0-3.0.dev 987c9e347c)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

**Comment by Levi-Lesches** [comment] 2020-08-10 04:29
After getting the error I immediately fixed the bug, so I don't exactly have the code on hand anymore. Not to mention, it's been a year so it's possible it's been fixed by now. If needed, I can try and reproduce the error (and now I'm wishing I'd posted my Flutter version as well).

**Comment by markusaksli-nc** [comment] 2020-08-10 07:29
If you could try to reproduce the issue that would be great. If you can't then we can just close the issue as probably fixed.

**Comment by darshankawar** [comment] 2020-09-02 09:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-02 09:45 UTC
Labels: framework, waiting for customer response
