### ISSUE TITLE
Xcode clean step hanging when running Flutter clean

### ISSUE THREAD

**Issue by agreaves** [flutter/flutter#56156] opened 2020-05-01 23:13 UTC
Occasionally, when running `flutter clean` the "Cleaning Xcode workspace..." step hangs, sometimes for hours. I know this isn't typical, but it would be useful to configure the command to add an option for ignoring Xcode workspace, or at the very least move it towards the end of the command so the rest of the clean occurs before hanging.

**Comment by agreaves** [comment] 2020-05-01 23:13
#jmagman:clean

**Comment by agreaves** [comment] 2020-05-01 23:14
#38992

**Comment by VladyslavBondarenko** [comment] 2020-05-04 14:31
Hi @agreaves 
could you provide your `flutter doctor -v`?

**Comment by agreaves** [comment] 2020-05-04 16:17
Sure!

[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.15.17 at /Users/alexgreaves/flutter
    • Framework revision 2294d75bfa (8 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alexgreaves/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by jmagman** [comment] 2020-05-05 20:25
Possibly a duplicate of https://github.com/flutter/flutter/issues/52268 but I don't know why cleaning the workspace would take so long.
It's just shelling out to `xcodebuild`
How long does this take?
```
$ cd ios
$ time xcrun xcodebuild -workspace Runner.xcworkspace -scheme Runner -quiet clean
```

https://github.com/flutter/flutter/pull/52860 is in v1.16.2, which is in the beta channel.  Would you mind running `flutter upgrade` and then giving us the output of `flutter clean -v` when it's reproducing?

**Comment by jilusubudhi** [comment] 2021-02-20 16:45
I am also facing the same issue. Is there any solution to fix this????

**Comment by jmagman** [comment] 2021-02-22 19:19
@jilusubudhi 

> How long does this take?
> 
> ```
> $ cd ios
> $ time xcrun xcodebuild -workspace Runner.xcworkspace -scheme Runner -quiet clean
> ```

What's the output of `flutter doctor -v`?  Can we get the output of `flutter clean -v` while it's reproducing?

**Comment by jmagman** [comment] 2021-04-20 01:47
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2021-04-20 01:47 UTC
Labels: P4, proposal, tool, waiting for customer response

**Comment by toshiaki-oy17** [comment] 2021-06-10 06:34
`Yosuas-MBP-2:frontend yosualeonardo$ flutter clean --verbose
[ +103 ms] executing: sysctl hw.optional.arm64
[  +25 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +16 ms] executing: [/Users/yosualeonardo/Desktop/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] executing: [/Users/yosualeonardo/Desktop/flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[ +171 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] 2.2.1
[   +7 ms] executing: [/Users/yosualeonardo/Desktop/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/yosualeonardo/Desktop/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +130 ms] executing: [/Users/yosualeonardo/Desktop/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +13 ms] executing: sw_vers -productName
[  +29 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +19 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.4
[        ] executing: sw_vers -buildVersion
[  +47 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20F71
[ +126 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +53 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +108 ms] executing: sysctl hw.optional.arm64
[   +8 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +971 ms] Exit code 0 from: xcrun xcodebuild -version
[   +1 ms] Xcode 12.5
           Build version 12E262
[   +7 ms] Cleaning Xcode workspace...
[   +3 ms] executing: [/Users/yosualeonardo/Documents/AndroidStudioProjects/frontend/ios/] xcrun xcodebuild -list
[+3325 ms] Command line invocation:
                        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

                    User defaults from command line:
                        IDEPackageSupportUseBuiltinSCM = YES

                    Information about project "Runner":
                        Targets:
                            Runner

                        Build Configurations:
                            Debug
                            Release
                            Profile

                        If no build configuration is specified and -scheme is not passed then "Profile" is used.

                        Schemes:
                            Runner
[   +4 ms] executing: [/Users/yosualeonardo/Documents/AndroidStudioProjects/frontend/] xcrun xcodebuild -workspace
/Users/yosualeonardo/Documents/AndroidStudioProjects/frontend/ios/Runner.xcworkspace -scheme Runner clean

`

I also face the same problem, here is the log.

I did `flutter doctor --verbose` and the code above is the result.

After `-scheme Runner clean`, it's hanging and I don't know it's still processing or not.
