### ISSUE TITLE
Create ProcessW  failed 193

### ISSUE THREAD

**Issue by EuvolaGG** [flutter/flutter#72934] opened 2020-12-24 17:16 UTC
I just created a flutter project and got this error on VSCODE.The error about Android studio does not apply since am using  VSCODE only.Flutter channel am using is stable.I dowwngraded from the latest version but still got the error.The error is not from my own code since I have not written anything.I have switched channel to master but still got the issue even after flutter clean
![flutter error](https://user-images.githubusercontent.com/68217917/103100342-28f6e180-4623-11eb-8825-72e68d32314a.jpg)

**Comment by iapicca** [comment] 2020-12-24 23:56
@EuvolaGG 
please follow the indication in the error message
run in the terminal
```console
flutter upgrade -f
cd <YOUR PROJECT FOLDER>
flutter create .
```
if the issue persists please provide your updated `flutter doctor -v` and your full `flutter run -v`
please avoid posting screenshots where a simple copy-paste is sufficient

**Comment by EuvolaGG** [comment] 2020-12-25 07:51
Thanks for the response @iapicca could you give me an example of how to use  the command
cd<YOUR PROJECT FOLDER>

**Comment by EuvolaGG** [comment] 2020-12-25 08:20
@iapicca 
I did as You said and its not working...That is why I asked how to use the cd command since the proposed solution has is invalid in this situation.
BELOW IS A COPY OF  flutter run -v and flutter doctor -v

PS C:\Users\NM\Desktop\Memo2\memo> flutter run -v
[  +98 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +138 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] d61d7758ed36a517daedbeeea7e170509936734c
[   +1 ms] executing: [C:\flutter/] git tag --points-at d61d7758ed36a517daedbeeea7e170509936734c
[ +182 ms] Exit code 0 from: git tag --points-at d61d7758ed36a517daedbeeea7e170509936734c
[   +2 ms] executing: [C:\flutter/] git describe --match *.*.* --long --tags d61d7758ed36a517daedbeeea7e170509936734c
[ +178 ms] Exit code 0 from: git describe --match *.*.* --long --tags d61d7758ed36a517daedbeeea7e170509936734c
[   +1 ms] 1.26.0-1.0.pre-134-gd61d7758ed
[  +76 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +86 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[ +101 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +184 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +151 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +27 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +134 ms] executing: C:\Users\NM\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +127 ms] List of devices attached
                    02673258C3000366       device product:PA05 model:TECNO_P904 device:TECNO-P904 transport_id:14
[  +11 ms] C:\Users\NM\AppData\Local\Android\sdk\platform-tools\adb.exe -s 02673258C3000366 shell getprop
[ +150 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +290 ms] Skipping pub get: version match.
[ +165 ms] Found plugin integration_test at C:\flutter\packages\integration_test\
[ +368 ms] Found plugin integration_test at C:\flutter\packages\integration_test\
[  +11 ms] Generating C:\Users\NM\Desktop\Memo2\memo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +115 ms] ro.hardware = mt6735
[   +1 ms] ro.build.characteristics = tablet
[ +113 ms] Initializing file store
[  +30 ms] Skipping target: gen_localizations
[   +8 ms] complete
[  +28 ms] Launching lib\main.dart on TECNO P904 in debug mode...
[  +14 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata --output-dill C:\Users\NM\AppData\Local\Temp\flutter_tools.c9a99612\flutter_tool.4f69c86e\app.dill --packages  
C:\Users\NM\Desktop\Memo2\memo\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\152a2ce78bff4a6f74a44ed554717a64.cache.dill.track.dill 
--flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[ +116 ms] executing: C:\Users\NM\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
C:\Users\NM\Desktop\Memo2\memo\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
CreateProcessW failed 193
[  +44 ms] Failed to extract manifest from APK: ProcessException: %1 is not a valid Win32 application.

             Command: C:\Users\NM\AppData\Local\Android\sdk\build-tools\29.0.2\aapt.EXE dump xmltree
             C:\Users\NM\Desktop\Memo2\memo\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
[ +194 ms] No application found for TargetPlatform.android_arm64.
                    Is your project missing an android\app\src\main\AndroidManifest.xml?
                    Consider running "flutter create ." to create one.
[ +248 ms] <- compile package:memo/main.dart
[+13667 ms] "flutter run" took 15,942ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)       
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:72:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:89:3)
           <asynchronous suspension>


[ +331 ms] ensureAnalyticsSent: 254ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +27 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
PS C:\Users\NM\Desktop\Memo2\memo> flutter doctor -v
[√] Flutter (Channel master, 1.26.0-2.0.pre.134, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.26.0-2.0.pre.134 at C:\flutter
    • Framework revision d61d7758ed (3 hours ago), 2020-12-24 21:42:25 -0800
    • Engine revision 1c975f1e7c
    • Dart version 2.12.0 (build 2.12.0-177.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\NM\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\NM\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (2 available)
    • TECNO P904 (mobile) • 02673258C3000366 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 86.0.4240.75

• No issues found!

**Comment by darshankawar** [comment] 2020-12-28 08:51
Closing this as duplicate of https://github.com/flutter/flutter/issues/72797

**Closed by darshankawar** 2020-12-28 08:51 UTC
