### ISSUE TITLE
[Windows][Desktop]: Trying to input Korean appends additional text

### ISSUE THREAD

**Issue by KyoungJoonKim** [flutter/flutter#94845] opened 2021-12-08 06:54 UTC
## Steps to Reproduce

Target Platform: Windows
Target OS version/browser: Windows 10
Devices: PC

1.  flutter run -d windows --release 
2. 
![image](https://user-images.githubusercontent.com/18536090/145160702-18403d9e-5f0d-4b68-9743-fef695c936de.png)
 
3. Type '김경준' into textfield  

**Expected results:** 
I want to display '김경준'

**Actual results:** 
But displayed '경준주ㅈㅈ경겨겨김'
![image](https://user-images.githubusercontent.com/18536090/145161158-dff1d664-735d-4493-b60a-43a1d4f8ea01.png)

<details>
<summary>Code sample</summary>
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              keyboardType: TextInputType.datetime,
              decoration: InputDecoration(
              labelText: '테스트',
            ),
            ),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```dart
```

</details>

<details>
  <summary>Logs</summary>

https://user-images.githubusercontent.com/18536090/145159429-d8431385-8f36-4b11-abc6-a32fb598b9c9.mp4

```
```

```
```

[√] Flutter (Channel master, 2.6.0-12.0.pre.936, on Microsoft Windows [Version 10.0.19042.1348], locale ko-KR)
    • Flutter version 2.6.0-12.0.pre.936 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 47a8f440c7 (25 hours ago), 2021-12-06 21:47:20 -0800
    • Engine revision 66a281107b
    • Dart version 2.16.0 (build 2.16.0-80.0.dev)
    • DevTools version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\kkchl\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\kkchl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1348]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!

</details>

**Comment by darshankawar** [comment] 2021-12-08 08:56
@KyoungJoonKim 
What keyboard type are you using for this behavior ?
Can you also check below issues and see if they resemble your case ?
https://github.com/flutter/flutter/issues/88645
https://github.com/flutter/flutter/issues/74819

**Comment by KyoungJoonKim** [comment] 2021-12-08 09:07
> @KyoungJoonKim What keyboard type are you using for this behavior ? Can you also check below issues and see if they resemble your case ? #88645 #74819

i did use normal keyboard. i think other issue. 

i did tested on macos, it is ok.

this issue is only windows system.

**Comment by HansMuller** [comment] 2021-12-08 18:25
CC @cbracken

**Comment by darshankawar** [comment] 2021-12-09 07:08
Verified this on Windows 10 machine using below sample code and running on latest stable and master and do see the same behavior, ie, while trying to input anything in Korean, it seems to be adding additional characters / text in it too, as shown below:

![korean_master](https://user-images.githubusercontent.com/67046386/145350065-0ecabee6-740d-403e-9048-4965a749d457.png)
![korean_stable](https://user-images.githubusercontent.com/67046386/145350069-ad0b695f-964e-4941-82a6-11a98f21d289.png)

<details>
<summary> flutter doctor -v </summary>

```
[√] Flutter (Channel master, 2.6.0-12.0.pre.975, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.6.0-12.0.pre.975 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9b1bbdbd16 (2 hours ago), 2021-12-09 00:04:07 -0500
    • Engine revision 30b0105c72
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1348]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!

[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.8.0 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.0)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1348]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!

```

</details>

**Comment by KyoungJoonKim** [comment] 2021-12-09 08:42
> Verified this on Windows 10 machine using below sample code and running on latest stable and master and do see the same behavior, ie, while trying to input anything in Korean, it seems to be adding additional characters / text in it too, as shown below:
> 
> ```
> body: Center(
>           child: TextField(
>             decoration: InputDecoration(
>               hintText: 'enter here'
>             )
>           )
>         )
> ```
> 
> ![korean_master](https://user-images.githubusercontent.com/67046386/145350065-0ecabee6-740d-403e-9048-4965a749d457.png) ![korean_stable](https://user-images.githubusercontent.com/67046386/145350069-ad0b695f-964e-4941-82a6-11a98f21d289.png)
> 
> flutter doctor -v


When will it be fixed?
We are currently developing a commercial product using Flutter.
If there was such a bug, I would not have chosen it.

**Comment by cbracken** [comment] 2021-12-16 23:29
This appears to be a regression; there have been some fundamental changes to text input in the June-Oct timeframe. I believe this is a duplicate of https://github.com/flutter/flutter/issues/88645; please follow that bug for progress.

**Closed by cbracken** 2021-12-16 23:29 UTC
Labels: a: text input, severe: regression, a: internationalization, platform-windows, a: desktop, has reproducible steps, P4, found in release: 2.6, found in release: 2.8

**Comment by KyoungJoonKim** [comment] 2021-12-17 08:27
> This appears to be a regression; there have been some fundamental changes to text input in the June-Oct timeframe. I believe this is a duplicate of #88645; please follow that bug for progress.

I tested the beta version. The result was the same.

run flutter doctor -v
[√] Flutter (Channel beta, 2.9.0-0.1.pre, on Microsoft Windows [Version 10.0.19042.1348], locale ko-KR)
    • Flutter version 2.9.0-0.1.pre at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (2 days ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\kkchl\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\kkchl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1348]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.53

• No issues found!

**Comment by gunami** [comment] 2021-12-25 15:47
same problem


>flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale ko-KR)
    • Flutter version 2.8.1 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (9 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\semoko\AppData\Local\Android\sdk
    • Platform android-31, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\semoko\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!
