### ISSUE TITLE
webview_flutter_platform_interface 1.5.0 issue

### ISSUE THREAD

**Issue by spaznuski** [flutter/flutter#93885] opened 2021-11-18 19:34 UTC
Latest update is causing a issue when trying to run an app, the latest commit  Add onUrlChanged callback to platform interface seems to be related.

`/C:/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.3.1/lib/src/webview.dart:432:7: Error: The non-abstract class '_PlatformCallbacksHandler' is missing implementations for these members:
 - WebViewPlatformCallbacksHandler.onUrlChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _PlatformCallbacksHandler implements WebViewPlatformCallbacksHandler {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_platform_interface-1.5.0/lib/src/platform_interface/webview_platform_callbacks_handler.dart:35:8: Context: 'WebViewPlatformCallbacksHandler.onUrlChanged' is defined here.
  void onUrlChanged(String url);`

Flutter doctor
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale en-JM)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:/Users/TechSyndicate/AppData/Local/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:/Users/TechSyndicate/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Redmi Note 5 (mobile) • 192.168.100.203:42860 • android-arm64  • Android 11 (API 30)
    • Chrome (web)          • chrome                • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)            • edge                  • web-javascript • Microsoft Edge 95.0.1020.30

• No issues found!

**Comment by davejlin** [comment] 2021-11-18 19:37
@spaznuski 
I had opened the same issue here right before you: https://github.com/flutter/flutter/issues/93884

**Comment by stuartmorgan** [comment] 2021-11-18 19:48
Closing as a duplicate of https://github.com/flutter/flutter/issues/93884

**Closed by stuartmorgan** 2021-11-18 19:48 UTC
