### ISSUE TITLE
Regression in frame build time in complex_layout_scroll_perf

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#130339] opened 2023-07-11 16:01 UTC
SkiaPerf is reporting that the 90%-ile and average frame build time regressed on `complex_layout_scroll_perf_bad_ios__timeline_summary` by about 30%:

https://flutter-flutter-perf.skia.org/e/?begin=1688490769&end=1689086966&keys=Xfce5bf9b2126b8e2e20d155f0f31b1d5&requestType=0&selected=commit%3D35614%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D90th_percentile_frame_build_time_millis%252Ctest%253Dcomplex_layout_scroll_perf_bad_ios__timeline_summary%252C&xbaroffset=35614

The report is on the commit here https://github.com/flutter/flutter/commit/3b8f6c4020a70a03267ab0ab9e25e83b26341082, containing a Skia roll with unrelated commits, and a manual Dart roll https://github.com/flutter/engine/pull/43472 with commits here:

https://dart.googlesource.com/sdk.git/+log/2d98d9e27dae..0b07debd5862

Unfortunately, it's a large Dart roll with many VM changes. Marking P0 only for help with identifying any culprits, if possible.

**Comment by lrhn** [comment] 2023-07-11 21:31
There are other mentions of the effect of this change on VM optimization.
See https://github.com/dart-lang/sdk/issues/48282 for discussion.

The existing code was wrong, as in the iterator giving completely wrong results in some cases, so it's not just something we can revert.

**Comment by rakudrama** [comment] 2023-07-11 23:40
For the benchmark to regress 30% on  https://dart.googlesource.com/sdk/+/d8fa6fe25522f45b7070278ad152abe4724cbdf2 it must be doing almost nothing except iterating the `.keys` or `.values` of an empty `Map`.
Our worst other regression was a micro-benchmark that did nothing other than iteration of singleton Map's `.keys` and was nearer 10%.

This seems a little unlikely, so can you validate the finding by profiling before and after to identify where the time is going?

**Comment by jason-simmons** [comment] 2023-07-12 03:23
I can reliably reproduce the effect of https://dart.googlesource.com/sdk/+/d8fa6fe25522f45b7070278ad152abe4724cbdf2 on the `complex_layout_scroll_perf_bad_ios__timeline_summary` frame build time metrics.

I tried capturing some profiles of the app used in the benchmark and noticed that it's spending significant time in `Layer._fireCompositionCallbacks`.
(https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/layer.dart#L175)

That function is iterating over a map that is apparently always empty in this app.  It consumes a lot of the time that is accounted as "frame build time" in the benchmark.

If I patch `Layer._fireCompositionCallbacks` to skip the iteration if the map is empty, then `average_frame_build_time_millis` is reduced by 25%.

@a-siva Adding the `@pragma('vm:prefer-inline')` annotation to the `_CompactIterable` iterator getter did not have a major effect.

**Comment by mraleph** [comment] 2023-07-12 08:53
Comment https://github.com/dart-lang/sdk/issues/48282#issuecomment-1625241307 describes the reason for the regression. tldr here is that `_CompactIterable.iterator` now has two additional virtual calls. This would only matter if you are iterating really small maps (~1 element) so the overhead of creating the iterator dominates the rest. I am going to look at fixing this, but in the interim I suggest just skipping the iteration altogether.

**Comment by lrhn** [comment] 2023-07-12 12:08
Maybe the Android version is JIT compiled. I believe Android supports both AoT and JIT, where iOS only supports AoT.

**Comment by mraleph** [comment] 2023-07-12 12:13
> Maybe the Android version is JIT compiled. I believe Android supports both AoT and JIT, where iOS only supports AoT.

I am pretty sure Flutter only runs benchmarks in profile mode (which corresponds to release AOT in Dart parlance).

**Comment by chinmaygarde** [comment] 2023-07-17 17:35
The regression is expected but a small amelioration has landed in https://github.com/flutter/flutter/pull/130438. Closing.

**Closed by chinmaygarde** 2023-07-17 17:35 UTC
Labels: c: regression, engine, c: performance, dependency: dart, perf: speed, P0, team-engine
