### ISSUE TITLE
Auth or Core issue? Cryptic: Can't run Firebase app ("taking longer than expected")

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#52020] opened 2020-03-05 16:32 UTC
![image](https://user-images.githubusercontent.com/54340176/76002625-a828f680-5ee5-11ea-89cc-cb4f7fdad859.png)

**Comment by andesappal** [comment] 2020-03-05 16:55
More info https://gist.github.com/andesappal/cae51b470b819c7378f8baa2bc0f2ea9

**Comment by andesappal** [comment] 2020-03-05 19:31
I can't identify which plugin is failing the build and how to fix it!

**Comment by andesappal** [comment] 2020-03-05 20:36
I believe all these plugin issues have to do with the new Xcode 11.3.1 which I recently downloaded?

**Comment by andesappal** [comment] 2020-03-05 20:43
![image](https://user-images.githubusercontent.com/54340176/76023861-ce13c280-5f08-11ea-9870-3cc0d188807c.png)

**Comment by iapicca** [comment] 2020-03-06 07:49
Hi @andesappal 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-03-06 07:49 UTC

**Comment by andesappal** [comment] 2020-03-06 15:15
@iapicca would you have any personal suggestions for when a plug-in stops the iOS build? Some others are also having the same issues as I: https://github.com/FirebaseExtended/flutterfire/issues?q=is%3Aissue+is%3Aopen+cloud_firestore
