### ISSUE TITLE
[tool_crash] SocketException: Write failed, OS Error: O pipe está sendo fechado., errno = 232

### ISSUE THREAD

**Issue by LucasDCoelho** [flutter/flutter#144037] opened 2024-02-23 18:32 UTC
## Command
```
flutter run --machine --start-paused -d 0080394598 --devtools-server-address http://127.0.0.1:9100/ --target C:\Users\Pc_Lucas_e_Nathalia\Desktop\Lucas\DiamondSolutions\curriculum_front\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Write failed, OS Error: O pipe está sendo fechado.
, errno = 232
```
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1246:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2004:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2479:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2214:28)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2168:11)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#10     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#12     _rootRun (dart:async/zone.dart:1391:47)
#13     _CustomZone.run (dart:async/zone.dart:1301:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#16     _rootRun (dart:async/zone.dart:1399:13)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```
[✓] Flutter (Channel stable, 3.19.1, on Microsoft Windows [versÆo 10.0.19045.4116], locale pt-BR)
    • Flutter version 3.19.1 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (3 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Android\Sdk
    • Java binary at: C:\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.5
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 233.13135.65

[✓] VS Code (version 1.86.2)
    • VS Code at C:\Users\Pc_Lucas_e_Nathalia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • motorola edge 30 neo (mobile) • 0080394598 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)             • windows    • windows-x64    • Microsoft Windows [versÆo 10.0.19045.4116]
    • Chrome (web)                  • chrome     • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)                    • edge       • web-javascript • Microsoft Edge 121.0.2277.128

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 41456452f29d64e8deb623a3c927524bcf9f111b
### Plugins
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2

**Comment by dam-ease** [comment] 2024-02-26 06:42
Hello @LucasDCoelho.
I see you opened multiple issues for the same issue.
Closing this as a duplicate of the previously opened issue.

**Closed by dam-ease** 2024-02-26 06:42 UTC
Labels: in triage
