### ISSUE TITLE
Flutter web view href to PDF file not opening in Android device only

### ISSUE THREAD

**Issue by cool0305** [flutter/flutter#110239] opened 2022-08-25 04:55 UTC
When I try to launch a URL with the pdf file, then Web view flutter fails to open the href URL in android device, but it works perfectly fine in IOS device.

**Comment by danagbemava-nc** [comment] 2022-08-25 09:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/48245. 

Kindly follow up in the linked issue for updates. 

Thank you

**Closed by danagbemava-nc** 2022-08-25 09:55 UTC
Labels: in triage
