### ISSUE TITLE
Avoid opening Xcode every time app runs on physical device.

### ISSUE THREAD

**Issue by quetool** [flutter/flutter#138106] opened 2023-11-08 19:54 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

This is not a bug nor a feature request but since there are no discussions available here I am.
The question is essentially this (unanswered) one: https://stackoverflow.com/questions/77152759/why-does-xcode-open-when-debugging-flutter-projects

- Why, since a few versions, Xcode is getting opened every time we run the app on physical device?
- Can we avoid it?
- Even more annoying is that, sometimes Xcode crashes with no reason making the debug session to be killed and having to restart the app again. It's quite annoying.

### Proposal

I don't have a proposal, just curios about the topic.

**Comment by stuartmorgan** [comment] 2023-11-08 20:35
Closing as a duplicate of https://github.com/flutter/flutter/issues/133465

**Closed by stuartmorgan** 2023-11-08 20:35 UTC
