### ISSUE TITLE
Flutter Impeller bug on iOS - Image.toByteData() null check failure

### ISSUE THREAD

**Issue by nezoat** [flutter/flutter#113854] opened 2022-10-21 21:05 UTC
## Steps to Reproduce

If Flutter Impeller is enabled in iOS, aka, FLTEnableImpeller is TRUE, then, Image.toByteData() throws a null check exception.  If Impeller is disabled, there is no problem.

//example code:
RenderRepaintBoundary rrb = currentContext!.findRenderObject() as RenderRepaintBoundary;
final img = rrb.toImage();
ByteData? data = await img.toByteData(format: ImageByteFormat.png);
// this last line fails

**Comment by jonahwilliams** [comment] 2022-10-21 21:08
Duplicate of https://github.com/flutter/flutter/issues/110829

**Closed by jonahwilliams** 2022-10-21 21:08 UTC
