### ISSUE TITLE
Possible regression in stock_layout_iteration notifyListener2_iteration microbenchmarks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#69583] opened 2020-11-02 16:45 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1603932125&end=1604318285&keys=Xf555aa9061b837985935b1cb021d49cf&requestType=0&xbaroffset=22298

Looks like it's no longer bimodal, and slightly over the peaks before.

Could be this engine roll, maybe? https://github.com/flutter/flutter/pull/69418

**Comment by zanderso** [comment] 2020-11-02 17:00
There was a big Dart roll in that engine roll https://github.com/flutter/engine/pull/22213, and a couple of commits later was the null-safety flag-flip, which should also be investigated.

**Comment by chinmaygarde** [comment] 2020-11-02 18:43
Per @jason-simmons, the purpose of this microbenchmark is hard to ascertain. It was bimodal before and not it is consistently settling at the higher value. On his local runs, it was still bimodal. We need the Dart VM teams help to understand this but we aren't even sure if this is measuring something useful.

**Comment by jason-simmons** [comment] 2020-11-03 23:29
I was able to reproduce the 7% increase in the `stock_layout_iteration` microbenchmark shown in the dashboard graph above.

The change started with https://github.com/dart-lang/sdk/commit/d5118d5fc83db077f23b8f7dd5d489634199ad1a.  That commit is calling `GetCurrentStackTrace` within `ReceivePort::New`.

This is expensive, and `ReceivePort::New` is invoked frequently in that benchmark as well as during use of apps like Gallery.  The calls to `GetCurrentStackTrace` are happening in release builds, not just debug/profile.

@bkonyi can this be made optional or limited to debug builds?

**Comment by bkonyi** [comment] 2020-11-03 23:35
We can probably limit it to Dart debug and release builds, but Flutter release / Dart product builds don't have any use for the collected stack.

**Comment by bkonyi** [comment] 2020-11-04 18:57
Fix up for review: https://dart-review.googlesource.com/c/sdk/+/170402

**Comment by jason-simmons** [comment] 2020-11-04 22:51
Note that Flutter engine profile builds do not define `PRODUCT` when building Dart.  So the benchmark results will stay the same after https://dart-review.googlesource.com/c/sdk/+/170402 lands.

**Comment by bkonyi** [comment] 2020-11-04 22:56
If that's the case I'm not sure how we can disable this. Why doesn't Flutter define `PRODUCT` when building for release?

**Comment by zanderso** [comment] 2020-11-04 23:52
@bkonyi Flutter profile builds contain the vmservice and e.g. the cpu profiler, so they cannot be `PRODUCT` builds.

**Comment by bkonyi** [comment] 2020-11-04 23:59
Right, but I thought this was an issue for Flutter release builds? This functionality needs to be available when the VM service is available.

**Comment by zanderso** [comment] 2020-11-05 00:12
@bkonyi I think we'd have to know a little more about what the functionality is to make the call about whether it needs to be in a Flutter profile build. If it is interfering with end-user profiling, as this benchmark might indicate, then I'd suggest that it should not go into profile builds.

**Comment by bkonyi** [comment] 2020-11-05 00:21
This functionality is used to debug open `ReceivePort` in order to give users a better idea where they were created and why they might still be open. I'm not aware of any other functionality in the VM service that behaves differently for profile builds, so I'm weary of special casing in this particular instance.

The other issue is that it's unclear to me how we'd disable this in the SDK. The VM doesn't know anything about Flutter build configurations as far as I know, so I'm not sure how we'd even check if we were running with a profile build in the first place. @rmacnak-google maybe you have more context on this?

**Comment by rmacnak-google** [comment] 2020-11-05 00:33
It's surprising that anything port related would be measurable in benchmarks that (IFAICT) don't involve IO or multiple isolates. Perhaps some work unrelated to the benchmark is running during the benchmark's timing window.

Indeed the VM does not (and should not) know anything about Flutter's build modes.

**Comment by zanderso** [comment] 2020-11-05 00:41
For example, Flutter debug mode has hot reload, the debugger etc., where profile mode does not. The VM does know about Flutter's build modes through combos of JIT vs. AOT and PRODUCT vs. non-PRODUCT. See also: https://github.com/dart-lang/sdk/blob/master/runtime/runtime_args.gni#L28.

@bkonyi Are you able to run the benchmark here or the Gallery? You can dogfood the new feature to track down the reason that these are being allocated more than expected ;-)

**Comment by jason-simmons** [comment] 2020-11-05 21:11
`ReceivePort::New` is called several thousand times while running the `stock_layout_iteration` benchmark.

Most of these calls happen because Dart timers create a receive port.  Timers are used throughout the Flutter framework, but they are created especially frequently in tests because `TestWidgetsFlutterBinding.idle` uses a timer.

**Comment by bkonyi** [comment] 2020-11-06 17:49
> For example, Flutter debug mode has hot reload, the debugger etc., where profile mode does not. The VM does know about Flutter's build modes through combos of JIT vs. AOT and PRODUCT vs. non-PRODUCT. See also: https://github.com/dart-lang/sdk/blob/master/runtime/runtime_args.gni#L28.
> 
> @bkonyi Are you able to run the benchmark here or the Gallery? You can dogfood the new feature to track down the reason that these are being allocated more than expected ;-)

@zanderso  ah, right, that's a fair point. Also I'd love to dogfood the feature, but I don't exactly have it hooked in anywhere yet... :-) 

Anyway, it looks like @jason-simmons found why so many ports are being allocated. Forgot timers relied on ports as well... hm... I'll see what our options are here. In the meantime, should I disable this stack collection?

**Comment by bkonyi** [comment] 2020-11-06 18:27
You know what, this can totally be solved with a VM flag that can be set by the engine. SDK Fix [here](https://dart-review.googlesource.com/c/sdk/+/170743).

**Comment by bkonyi** [comment] 2020-11-11 20:21
Discussed with the VM team and we came up with another solution. I've updated the timer implementation to no longer destroy its port when there's no active timers [here](https://dart-review.googlesource.com/c/sdk/+/171628). Instead, I've added functionality to the port map which allows for a port to be marked as inactive, effectively removing the port from the list of active ports in order to prevent the timer port from keeping an isolate alive when no other ports are open.

Here's the rough benchmark results from my Pixel 4 XL:

Before dart-lang/sdk@d5118d5:     `"notifyListener2_iteration": 545.0`
After dart-lang/sdk@d5118d5:     `"notifyListener2_iteration": 1639.0`
With fix:     `"notifyListener2_iteration": 629.0`

**Comment by bkonyi** [comment] 2020-11-12 00:06
Resolved in dart-lang/sdk@b729693cb9a8668e3a4abafa528a349610ec843a

**Closed by bkonyi** 2020-11-12 00:06 UTC
Labels: P2, dependency: dart, engine, passed first triage, perf: speed, severe: performance, severe: regression, team: benchmark
