### ISSUE TITLE
Improve layout of flutter cli help

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#27805] opened 2019-02-11 23:55 UTC
This may have to do with indentation, alignment, line width, etc. For example,

```
> flutter create
No option specified for the output directory.
Create a new Flutter project.

If run on a project that already exists, this will repair the project, recreating any files that
are missing.

Usage: flutter create <output directory>
-h, --help
Print this usage information.
    --[no-]pub
    Whether to run "flutter packages get" after the project has been created.
                                                                                                                  (defaults
                                                                                                                  to on)

    --[no-]offline
    When "flutter packages get" is run by the create command, this indicates whether to run it in
    offline mode or not. In offline mode, it will need to have all dependencies already available
    in the pub cache to succeed.
    --[no-]with-driver-test
    Also add a flutter_driver dependency and generate a sample 'flutter drive' test.
-t, --template=<type>
Specify the type of project to create.

          [app]
          (default) Generate a Flutter application.
          [package]
          Generate a shareable Flutter project containing modular Dart code.
          [plugin]
          Generate a shareable Flutter project containing an API in Dart code with a
          platform-specific implementation for Android, for iOS code, or for both.

-s, --sample=<the sample ID of the desired sample from the API documentation website
(http://docs.flutter.io)>    Specifies the Flutter code sample to use as the main.dart for an
application. Implies --template=app.
    --[no-]overwrite
    When performing operations, overwrite existing files.
    --description
    The description to use for your new Flutter project. This string ends up in the pubspec.yaml
    file.
                                                                                                                  (defaults
                                                                                                                  to "A new
                                                                                                                  Flutter
                                                                                                                  project.")

    --org
    The organization responsible for your new Flutter project, in reverse domain name notation.
    This string is used in Java package names and as prefix in the iOS bundle identifier.
                                                                                                                  (defaults
                                                                                                                  to
                                                                                                                  "com.examp
                                                                                                                  le")

    --project-name
    The project name for this new Flutter project. This must be a valid dart package name.
-i, --ios-language
[objc (default), swift]
-a, --android-language
[java (default), kotlin]

Run "flutter help" to see global options.
```

I find this hard to read.

There is a related issue, at https://github.com/flutter/flutter/issues/23074, but it seems limited to line width.

**Comment by zoechi** [comment] 2019-02-12 09:57
@bradyt what terminal are you seeing this? Is this the terminal window of an IDE or some other shell window? What shell?

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2019-02-12 10:01
This is what it looks for me in IntelliJ IDE terminal window with bash shell

wide window
```
No option specified for the output directory.
Create a new Flutter project.

If run on a project that already exists, this will repair the project, recreating any files that are missing.

Usage: flutter create <output directory>
-h, --help                                                                                                        Print this usage information.
    --[no-]pub                                                                                                    Whether to run "flutter packages get" after the project has been created.
                                                                                                                  (defaults to on)

    --[no-]offline                                                                                                When "flutter packages get" is run by the create command, this indicates whether to run it in offline mode or not. In offline mode, it will need to have all dependencies already available in the pub cache to succeed.
    --[no-]with-driver-test                                                                                       Also add a flutter_driver dependency and generate a sample 'flutter drive' test.
-t, --template=<type>                                                                                             Specify the type of project to create.

          [app]                                                                                                   (default) Generate a Flutter application.
          [package]                                                                                               Generate a shareable Flutter project containing modular Dart code.
          [plugin]                                                                                                Generate a shareable Flutter project containing an API in Dart code with a platform-specific implementation for Android, for iOS code, or for both.

-s, --sample=<the sample ID of the desired sample from the API documentation website (http://docs.flutter.io)>    Specifies the Flutter code sample to use as the main.dart for an application. Implies --template=app.
    --[no-]overwrite                                                                                              When performing operations, overwrite existing files.
    --description                                                                                                 The description to use for your new Flutter project. This string ends up in the pubspec.yaml file.
                                                                                                                  (defaults to "A new Flutter project.")

    --org                                                                                                         The organization responsible for your new Flutter project, in reverse domain name notation. This string is used in Java package names and as prefix in the iOS bundle identifier.
                                                                                                                  (defaults to "com.example")

    --project-name                                                                                                The project name for this new Flutter project. This must be a valid dart package name.
-i, --ios-language                                                                                                [objc (default), swift]
-a, --android-language                                                                                            [java (default), kotlin]

Run "flutter help" to see global options.
```

small window
```
No option specified for the output directory.
Create a new Flutter project.

If run on a project that already exists, this will repair the project, recreating any files that are missing.

Usage: flutter create <output directory>
-h, --help                                                                                                        Print this
usage information.
    --[no-]pub                                                                                                    Whether to run
    "flutter packages get" after the project has been created.
                                                                                                                  (defaults to
                                                                                                                  on)

    --[no-]offline                                                                                                When "flutter
    packages get" is run by the create command, this indicates whether to run it in offline mode or not. In offline mode, it will
    need to have all dependencies already available in the pub cache to succeed.
    --[no-]with-driver-test                                                                                       Also add a
    flutter_driver dependency and generate a sample 'flutter drive' test.
-t, --template=<type>                                                                                             Specify the
type of project to create.

          [app]                                                                                                   (default)
          Generate a Flutter application.
          [package]                                                                                               Generate a
          shareable Flutter project containing modular Dart code.
          [plugin]                                                                                                Generate a
          shareable Flutter project containing an API in Dart code with a platform-specific implementation for Android, for iOS
          code, or for both.

-s, --sample=<the sample ID of the desired sample from the API documentation website (http://docs.flutter.io)>    Specifies the
Flutter code sample to use as the main.dart for an application. Implies --template=app.
    --[no-]overwrite                                                                                              When performing
    operations, overwrite existing files.
    --description                                                                                                 The description
    to use for your new Flutter project. This string ends up in the pubspec.yaml file.
                                                                                                                  (defaults to "A
                                                                                                                  new Flutter
                                                                                                                  project.")

    --org                                                                                                         The
    organization responsible for your new Flutter project, in reverse domain name notation. This string is used in Java package
    names and as prefix in the iOS bundle identifier.
                                                                                                                  (defaults to
                                                                                                                  "com.example")

    --project-name                                                                                                The project
    name for this new Flutter project. This must be a valid dart package name.
-i, --ios-language                                                                                                [objc
(default), swift]
-a, --android-language                                                                                            [java
(default), kotlin]

Run "flutter help" to see global options.
```

```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by zoechi** [comment] 2019-02-18 17:19
Closing as duplicate of #23074

**Closed by zoechi** 2019-02-18 17:19 UTC
Labels: tool, waiting for customer response
