### ISSUE TITLE
Fix the footer and header of PaginatedDataTable

### ISSUE THREAD

**Issue by KalaliEhsan** [flutter/flutter#131151] opened 2023-07-23 08:52 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to fix the footer and header of the ```PaginatedDataTable``` widget. But it doesn't have this feature.
Please add this feature for ```PaginatedDataTable``` and ```DataTable``` widgets like this [package](https://pub.dev/packages/data_table_2).

### Proposal

The Flutter team should add this feature.

**Comment by danagbemava-nc** [comment] 2023-07-24 09:02
Hi @KalaliEhsan, I believe this is a duplicate of https://github.com/flutter/flutter/issues/80033. 

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-07-24 09:02 UTC
Labels: in triage

**Comment by KalaliEhsan** [comment] 2023-07-26 12:54
> Hi @KalaliEhsan, I believe this is a duplicate of #80033.
> 
> Kindly subscribe to the original issue for updates.
> 
> Closing from here as duplicate.
> 
> Thank you

Thanks @danagbemava-nc

**Comment by KalaliEhsan** [comment] 2023-07-26 12:54
Thanks @danagbemava-nc
