### ISSUE TITLE
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'

### ISSUE THREAD

**Issue by cooosuper** [flutter/flutter#41284] opened 2019-09-25 11:49 UTC
## Here is the Exception:
```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown while notifying listeners for AnimationController:
NoSuchMethodError: invalid member on null: 'findRenderObject'

When the exception was thrown, this was the stack:
package:flutter/src/widgets/editable_text.dart 1726:68            get renderEditable
package:flutter/src/widgets/editable_text.dart 1590:20            [_onCursorColorTick]
package:flutter/src/animation/listener_helpers.dart 124:19        notifyListeners
package:flutter/src/animation/animation_controller.dart 362:5     set value
package:flutter/src/widgets/editable_text.dart 1625:37            [_cursorTick]
package:build_web_compilers/src/dev_compiler/dart_sdk.js 28733:9  <fn>

The AnimationController notifying listeners was:
AnimationController#85179(⏮ 0.000; paused)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Here is my code, main.dart:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Hello Flutter'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  TabController _tabController;
  TextEditingController phoneController = new TextEditingController();
  TextEditingController passwordController = new TextEditingController();

  void _incrementCounter() {
    setState(() {});
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _tabController = new TabController(vsync: this, length: 1);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('登录'),
        actions: <Widget>[
        ],
        centerTitle: true,
      ),
      body: new TabBarView(
        controller: _tabController,
        children: <Widget>[
          new Column(
            children: <Widget>[
              new Container(
                margin: EdgeInsets.all(10.0),
                child: new TextField(
                  keyboardType: TextInputType.number,
                  controller: phoneController,
                  decoration: InputDecoration(
                    contentPadding: EdgeInsets.all(10.0),
                    icon: Icon(Icons.account_circle),
                    labelText: '请输入用户名',
                    helperText: '请输入您的用户名',
                  ),
                  onChanged: (String str) {},
                ),
              ),

              new Container(
                margin: EdgeInsets.all(10.0),
                child: new TextField(
                  controller: passwordController,
                  keyboardType: TextInputType.number,
                  decoration: InputDecoration(
                    contentPadding: EdgeInsets.all(10.0),
                    icon: Icon(Icons.lock),
                    labelText: '请输入密码',
                    helperText: '请输入您的密码',
                  ),
                ),
              ),

              new Container(
                child: new RaisedButton(
                  color: Theme
                      .of(context)
                      .primaryColor,
                  padding: EdgeInsets.all(10.0),
                  child: new Text('登录'),
                  textColor: Colors.white,
                  onPressed: () {},
                ),
                width: double.infinity,
                padding: EdgeInsets.all(10.0),
              ),

              new Container(
                child: new Text(
                  '登录遇到问题？',
                  style: new TextStyle(
                    fontSize: 16.0,
                    textBaseline: null,
                    decoration: TextDecoration.none,
                    color: Theme
                        .of(context)
                        .primaryColor,
                    fontStyle: FontStyle.normal,
                    fontWeight: FontWeight.normal,
                  ),
                ),
                padding: EdgeInsets.all(10.0),
              ),
            ],
          )
        ],
      ),
    );
  }
}
```

When I run my application first time, it's fine, but when I hot restart the application, the error occurs. Please help fix it. Thank you~

**Comment by escamoteur** [comment] 2019-09-25 12:37
You didn't dispose the two TextEditingControllers. not sure if this is the reason.

**Comment by cooosuper** [comment] 2019-09-25 12:49
Sorry, the error is just on flutter web.

**Comment by escamoteur** [comment] 2019-09-25 14:26
could you please switch to master and see if it is there solved?

**Comment by cooosuper** [comment] 2019-09-25 14:54
not solved

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.6-pre.62, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.10.6-pre.62 at /Users/cooosuper/Work/flutter
    • Framework revision 84a476a4db (30 minutes ago), 2019-09-25 10:17:04 -0400
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 69b5681546)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cooosuper/Work/ade/sdk2
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.0.beta.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[!] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.

**Comment by escamoteur** [comment] 2019-09-30 19:48
Just to be sure, you are both having the problem on flutter web, not on Android or iOS?

**Comment by deftsp** [comment] 2019-09-30 23:31
Sorry, after adding the `initialValue` to `TextFormField`, the problem not gone. It seems  occur in a random manner. It happended iOS too. 

```
Initializing hot reload...                                      
Reloaded 0 of 598 libraries in 74ms.

Performing hot reload...                                        version=2.6.0-dev.0.0.flutter-6ff8d2199d (Thu Sep 26 12:32:25 2019 +0000) on "ios_x64"
thread=43015, isolate=main(0x7f9d33016400)
pc 0x000000010d468174 fp 0x0000700005c366d0 dart::Profiler::DumpStackTrace(void*)
pc 0x000000010d3370b2 fp 0x0000700005c367b0 dart::Assert::Fail(char const*, ...)
pc 0x000000010d375c67 fp 0x0000700005c367e0 dart::Function::CheckedHandle(dart::Zone*, dart::RawObject*)
pc 0x000000010d4ac832 fp 0x0000700005c36890 dart::DRT_NoSuchMethodFromPrologue(dart::NativeArguments)
pc 0x0000000112641108 fp 0x0000700005c368d8 Unknown symbol
pc 0x0000000112643761 fp 0x0000700005c36920 Unknown symbol
pc 0x0000000124b906bc fp 0x0000700005c36978 Unknown symbol
pc 0x0000000113267d7a fp 0x0000700005c369b8 Unknown symbol
pc 0x000000011e77d864 fp 0x0000700005c369f8 Unknown symbol
pc 0x000000011e77d5b1 fp 0x0000700005c36a38 Unknown symbol
pc 0x000000011e77d402 fp 0x0000700005c36a98 Unknown symbol
pc 0x0000000113267d7a fp 0x0000700005c36ad8 Unknown symbol
pc 0x000000011e362ee4 fp 0x0000700005c36b18 Unknown symbol
pc 0x000000011e362dda fp 0x0000700005c36b58 Unknown symbol
pc 0x000000011e0bff2d fp 0x0000700005c36b98 Unknown symbol

```

**Comment by youmnay** [comment] 2019-10-20 11:23
I am having this issue too on web.

**Comment by DSenanayake** [comment] 2019-10-21 05:34
I have the same problem with flutter web.
Is there any update on this?

`Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'`



`Flutter 1.10.15-pre.186 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1c535de7e0 (2 days ago) • 2019-10-18 16:40:42 -0700
Engine • revision 8aefcd8575
Tools • Dart 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.186, on Mac OS X 10.14.6 18G95, locale en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    ! CocoaPods 1.5.3 out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.`

**Comment by youmnay** [comment] 2019-10-21 15:04
From my observations, it happens when I hot-reload a web project.

**Comment by mdebbar** [comment] 2019-10-21 20:48
Go home @no-response bot, you are drunk!

Re-opening the issue.

I'm looking into this. It seems to be related to timers and microtasks not being cleared when hot restart occurs. Once I confirm, I'll file an issue on https://github.com/dart-lang/sdk/ and link to it here.

**Comment by mdebbar** [comment] 2019-10-21 22:03
Filed issue: https://github.com/dart-lang/sdk/issues/39020

**Comment by khari998** [comment] 2019-10-22 23:54
Why is this being closed? I am getting the exact same issue. Appears to be related to using textfield in flutter web. If I type any text into the textfield rendered on the page and do a hot reload, I get this error nonstop until exiting and running the command flutter run -d chrome. It should be easily reproducible

**Comment by escamoteur** [comment] 2019-10-23 16:35
@khari998 see the issue mdebbar linked above the problem lies in the dart sdk

**Comment by mdebbar** [comment] 2019-10-23 19:53
The fix landed in [DartDevCompiler](https://github.com/dart-lang/sdk/commit/cccb9ffb2ab3268389a08d20261861115864156c), then rolled into [the engine](https://github.com/flutter/engine/commit/88734cc9ef531fdc0e5a85162fa72c0793bffd77), then rolled into [Flutter](https://github.com/flutter/flutter/commit/50112f3cdce6342926273575dedc2b03b21a7a33).

**Closed by mdebbar** 2019-10-23 19:53 UTC
Labels: a: text input, customer: webeap, dependency: dart, severe: crash, ☸ platform-web

**Comment by mdebbar** [comment] 2019-10-24 13:54
Yes.

**Comment by softmarshmallow** [comment] 2020-03-21 08:51
> I am having this issue too on web.

still having this
