### ISSUE TITLE
isolate message : (object is a StackTrace) 

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#71125] opened 2020-11-24 03:03 UTC
flutter: cant send error with too big stackTrace, error is : Invalid argument(s): Illegal argument in isolate message : (object is a StackTrace)

master branch

**Comment by pedromassangocode** [comment] 2020-11-24 07:30
Closing as duplicate of https://github.com/flutter/flutter/issues/71081. Please reply on the first issue instead of opening a new one.

**Closed by pedromassangocode** 2020-11-24 07:30 UTC
