### ISSUE TITLE
CryptoJs Encryption and Decryption and token generation 

### ISSUE THREAD

**Issue by eswarvarma-dev** [flutter/flutter#43489] opened 2019-10-25 07:38 UTC
```
import { Injectable } from "@angular/core";
import * as CryptoJS from 'crypto-js';

@Injectable()
export class EncryptionService {
    keySize: number;
    iterationCount: number;

    // keySize ==> 128, iterationCount ==> 10, (salt,IV) ==> f2e5c62df8c65d42a71747a3b878a3a5, passPhrase ==> qwer@hl3A!4
  
    initEncryptionValues(keySize: number, iterationCount: number) {
        this.keySize = keySize / 32;
        this.iterationCount = iterationCount;
    }
   

    generateKey(salt: string, passPhrase: string) {
        let key = CryptoJS.PBKDF2(passPhrase,CryptoJS.enc.Hex.parse(salt),{ keySize: this.keySize, iterations: this.iterationCount });
        return key;
    }


    encrypt(salt: string, iv: any, passPhrase: string, plainText: any) {
        let key = this.generateKey(salt, passPhrase);
        let encrypted = CryptoJS.AES.encrypt(
            plainText,
            key,
            { iv: CryptoJS.enc.Hex.parse(iv) });
        return (<any>encrypted.ciphertext).toString(CryptoJS.enc.Base64);
    }

    decrypt(salt: string, iv: any, passPhrase: string, cipherText: any) {
        let key = this.generateKey(salt, passPhrase);
        let cipherParams = (<any>CryptoJS.lib).CipherParams.create({
            ciphertext: CryptoJS.enc.Base64.parse(cipherText)
        });
        let decrypted = CryptoJS.AES.decrypt(
            cipherParams,
            key,
            { iv: CryptoJS.enc.Hex.parse(iv) });
        return decrypted.toString(CryptoJS.enc.Utf8);
    }
}

```

**Comment by MaherKSantina** [comment] 2019-10-25 08:31
Hey @eswarvarma-dev, I was just wondering what the issue is. Is this working in an unexpected way?

**Comment by BondarenkoStas** [comment] 2019-10-25 14:37
@eswarvarma-dev Please describe the issue you have, otherwise it gives no information.

**Comment by iapicca** [comment] 2019-11-15 15:46
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 15:46 UTC
Labels: waiting for customer response
