### ISSUE TITLE
[tool_crash] ArchiveException

### ISSUE THREAD

**Issue by rlogical-techsoft** [flutter/flutter#65156] opened 2020-09-03 08:04 UTC
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArchiveException
```
#0      new ZipFile (package:archive/src/zip/zip_file.dart:31:9)
#1      new ZipFileHeader (package:archive/src/zip/zip_file_header.dart:85:16)
#2      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:53:23)
#3      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:20:30)
#4      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:333:42)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:651:16)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#15     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#24     Net.fetchUrl (package:flutter_tools/src/base/net.dart)
```
```
[✓] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1016], locale en-IN)
    • Flutter version 1.20.3 at D:\SDK\FlutterSDK\flutter
    • Framework revision 216dee60c0 (2 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\SDK\android-sdk-windows
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = D:\SDK\android-sdk-windows
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.1)
    • VS Code at C:\Users\rlogical-dev-17\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Pixel 2 XL (mobile)                • 710KPFX0201123 • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554  • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment] 2020-09-03 09:01
Hi @rlogical-techsoft 
This seems to be fixed by https://github.com/flutter/flutter/issues/64950#issuecomment-684003453
Closing as duplicate of https://github.com/flutter/flutter/issues/64950
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-03 09:01 UTC
