### ISSUE TITLE
Support segmented controls in nav bars and double row nav bars

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10469] opened 2017-06-02 23:00 UTC
Extracting from #7508

Examples:
![screen shot 2017-06-02 at 3 59 59 pm](https://cloud.githubusercontent.com/assets/156888/26747722/99e979bc-47ac-11e7-865c-491fe0fd2e43.png)

![screen shot 2017-06-02 at 4 00 16 pm](https://cloud.githubusercontent.com/assets/156888/26747724/9cfba40e-47ac-11e7-94ef-884d757343d6.png)

**Comment by The-Redhat** [comment] 2018-05-19 10:17
When is this supposed to be ready to use?

**Comment by xster** [comment] 2018-05-21 22:36
It's in our plans for the next few months though it's hard to give an exact date at this point.

**Comment by allanwolski** [comment] 2018-10-31 17:36
@xster, do you have any predictions for this?

**Comment by konstantintuev** [comment] 2018-12-25 20:11
Not the most beautiful and very hacky but it works:
`// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

const Color _kKeyUmbraOpacity = Color(0x33000000); // alpha = 0.2
const Color _kKeyPenumbraOpacity = Color(0x24000000); // alpha = 0.14
const Color _kAmbientShadowOpacity = Color(0x1F000000); // alpha = 0.12

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new CupertinoApp(
      title: 'Where Are You - Client',
      debugShowCheckedModeBanner: false,
      localizationsDelegates: const <LocalizationsDelegate<dynamic>>[
        DefaultMaterialLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
      home: new CupertinoSegmentedControlDemo(),
    );
  }
}

class CupertinoSegmentedControlDemo extends StatefulWidget {
  static const String routeName = 'cupertino/segmented_control';

  @override
  _CupertinoSegmentedControlDemoState createState() => _CupertinoSegmentedControlDemoState();
}

class _CupertinoSegmentedControlDemoState extends State<CupertinoSegmentedControlDemo> {
  final Map<int, Widget> children = const <int, Widget>{
    0: Text('Midnight'),
    1: Text('Viridian'),
    2: Text('Cerulean'),
  };

  final Map<int, Widget> icons = const <int, Widget>{
    0: Center(
      child: FlutterLogo(
        colors: Colors.indigo,
        size: 200.0,
      ),
    ),
    1: Center(
      child: FlutterLogo(
        colors: Colors.teal,
        size: 200.0,
      ),
    ),
    2: Center(
      child: FlutterLogo(
        colors: Colors.cyan,
        size: 200.0,
      ),
    ),
  };

  int sharedValue = 0;



  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark.copyWith(
      statusBarColor: Colors.transparent, //or set color with: Color(0xFF0000FF)
    ));
    return DefaultTextStyle(
        style: const TextStyle(
        fontFamily: '.SF UI Text',
        inherit: false,
        fontSize: 17.0,
        color: CupertinoColors.black,
    ),

    child:  Scaffold(
      appBar: CupertinoNavigationBar(
        border: null,
        middle: const Text('Segmented Control', style: const TextStyle(
          inherit: true,
          fontWeight: FontWeight.bold,
        ),),
        previousPageTitle: 'Cupertino',
      ),
      body: Column(
        children: <Widget>[
          SizedBox(
            height: 31,
            child: CupertinoNavigationBar(
              border: null,
              middle: SizedBox(
                width: 500.0,
                child: CupertinoSegmentedControl<int>(
                  children: children,
                  onValueChanged: (int newValue) {
                    setState(() {
                      sharedValue = newValue;
                    });
                  },
                  groupValue: sharedValue,
                ),
              ),
            ),
          ),
          SizedBox(
            height: 10,
            child: CupertinoNavigationBar(),
          ),
          const Padding(
            padding: EdgeInsets.all(16.0),
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.symmetric(
                vertical: 32.0,
                horizontal: 16.0,
              ),
              child: Container(
                padding: const EdgeInsets.symmetric(
                  vertical: 64.0,
                  horizontal: 16.0,
                ),
                decoration: BoxDecoration(
                  color: CupertinoColors.white,
                  borderRadius: BorderRadius.circular(3.0),
                  boxShadow: const <BoxShadow>[
                    BoxShadow(
                      offset: Offset(0.0, 3.0),
                      blurRadius: 5.0,
                      spreadRadius: -1.0,
                      color: _kKeyUmbraOpacity,
                    ),
                    BoxShadow(
                      offset: Offset(0.0, 6.0),
                      blurRadius: 10.0,
                      spreadRadius: 0.0,
                      color: _kKeyPenumbraOpacity,
                    ),
                    BoxShadow(
                      offset: Offset(0.0, 1.0),
                      blurRadius: 18.0,
                      spreadRadius: 0.0,
                      color: _kAmbientShadowOpacity,
                    ),
                  ],
                ),
                child: icons[sharedValue],
              ),
            ),
          ),
        ],
      ),
    )
    );
  }
}`

**Comment by konstantintuev** [comment] 2018-12-25 20:18
Not the most beautiful and very hacky but it works.
Also merry christmas everyone!

```dart
// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

const Color _kKeyUmbraOpacity = Color(0x33000000); // alpha = 0.2
const Color _kKeyPenumbraOpacity = Color(0x24000000); // alpha = 0.14
const Color _kAmbientShadowOpacity = Color(0x1F000000); // alpha = 0.12

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new CupertinoApp(
      title: 'Where Are You - Client',
      debugShowCheckedModeBanner: false,
      localizationsDelegates: const <LocalizationsDelegate<dynamic>>[
        DefaultMaterialLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
      home: new CupertinoSegmentedControlDemo(),
    );
  }
}

class CupertinoSegmentedControlDemo extends StatefulWidget {
  static const String routeName = 'cupertino/segmented_control';

  @override
  _CupertinoSegmentedControlDemoState createState() => _CupertinoSegmentedControlDemoState();
}

class _CupertinoSegmentedControlDemoState extends State<CupertinoSegmentedControlDemo> {
  final Map<int, Widget> children = const <int, Widget>{
    0: Text('Midnight'),
    1: Text('Viridian'),
    2: Text('Cerulean'),
  };

  final Map<int, Widget> icons = const <int, Widget>{
    0: Center(
      child: FlutterLogo(
        colors: Colors.indigo,
        size: 200.0,
      ),
    ),
    1: Center(
      child: FlutterLogo(
        colors: Colors.teal,
        size: 200.0,
      ),
    ),
    2: Center(
      child: FlutterLogo(
        colors: Colors.cyan,
        size: 200.0,
      ),
    ),
  };

  int sharedValue = 0;



  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark.copyWith(
      statusBarColor: Colors.transparent, //or set color with: Color(0xFF0000FF)
    ));
    return DefaultTextStyle(
        style: const TextStyle(
        fontFamily: '.SF UI Text',
        inherit: false,
        fontSize: 17.0,
        color: CupertinoColors.black,
    ),

    child:  Scaffold(
      //our first CupertinoNavigationBar - just title
      appBar: CupertinoNavigationBar(
        border: null,
        middle: const Text('Segmented Control', style: const TextStyle(
          inherit: true,
          fontWeight: FontWeight.bold,
        ),),
        previousPageTitle: 'Cupertino',
      ),
      body: Column(
        children: <Widget>[
          /// our second CupertinoNavigationBar is
          /// in a SizedBox because the CupertinoSegmentedControl
          /// creates white highlights near itself which are not 
          /// very visible but not pleasant
          SizedBox(
            height: 31,
            child: CupertinoNavigationBar(
              border: null,
              middle: SizedBox(
                width: 500.0,
                child: CupertinoSegmentedControl<int>(
                  children: children,
                  onValueChanged: (int newValue) {
                    setState(() {
                      sharedValue = newValue;
                    });
                  },
                  groupValue: sharedValue,
                ),
              ),
            ),
          ),
          
          /// and our third CupertinoNavigationBar 
          /// Used just for the border and some padding
          SizedBox(
            height: 10,
            child: CupertinoNavigationBar(),
          ),
          const Padding(
            padding: EdgeInsets.all(16.0),
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.symmetric(
                vertical: 32.0,
                horizontal: 16.0,
              ),
              child: Container(
                padding: const EdgeInsets.symmetric(
                  vertical: 64.0,
                  horizontal: 16.0,
                ),
                decoration: BoxDecoration(
                  color: CupertinoColors.white,
                  borderRadius: BorderRadius.circular(3.0),
                  boxShadow: const <BoxShadow>[
                    BoxShadow(
                      offset: Offset(0.0, 3.0),
                      blurRadius: 5.0,
                      spreadRadius: -1.0,
                      color: _kKeyUmbraOpacity,
                    ),
                    BoxShadow(
                      offset: Offset(0.0, 6.0),
                      blurRadius: 10.0,
                      spreadRadius: 0.0,
                      color: _kKeyPenumbraOpacity,
                    ),
                    BoxShadow(
                      offset: Offset(0.0, 1.0),
                      blurRadius: 18.0,
                      spreadRadius: 0.0,
                      color: _kAmbientShadowOpacity,
                    ),
                  ],
                ),
                child: icons[sharedValue],
              ),
            ),
          ),
        ],
      ),
    )
    );
  }
}
```

**Comment by KagurazakaHanabi** [comment] 2019-07-30 12:35
Any updates?

**Comment by The-Redhat** [comment] 2020-03-05 19:27
Anything new on this issue? @xster nearly two years ago you said that the issue is in yout plans for the next few months.

**Comment by tobiaszuercher** [comment] 2020-05-20 13:34
we are also really interested in a proper solution for this. especially on iPad, it's an excellent way to provide a subnavigation inside a screen. tab navigation on the bottom shouldn't be replaced/changed. to provide a subnavi we think the best way is to not show the tab bar at the bottom and provide it on top with chips/whatever.

![image](https://user-images.githubusercontent.com/516373/82450155-9ef30300-9aac-11ea-95a0-f5a8e94c7087.png)

**Comment by BlueKanGoKilian** [comment] 2021-06-02 15:05
Same here. 
The X-platform mobile app my team and I are working on would really find this useful.
As I tried a little to do this kind of behavior today (and stumble upon this issue), I would like to know if this would be available "soon" or not (to know if I continue trying or just wait). I see this issue is tagged "passed first triage" but I don't see any PR linked, is there any problem ?

**Comment by victorsanni** [comment] 2024-09-27 21:35
The first part of this (segmented controls in nav bars) is already supported using the `middle` property of CupertinoNavigationBar and CupertinoSliverNavigationBar. 

The second part (segmented controls in double row nav bars might be fixed by https://github.com/flutter/flutter/pull/155841.

**Closed** 2024-10-16 19:36 UTC
Labels: c: new feature, framework, f: cupertino, c: proposal, P2, team-design, triaged-design
