### ISSUE TITLE
when run 'main.dart' on macOS(desktop), 

### ISSUE THREAD

**Issue by HongWonjong** [flutter/flutter#123487] opened 2023-03-26 03:55 UTC
hello, I'm using MacBook Air to writing flutter code. 

when i run simple code that contains only one text widget on MacOS, the screen goes weird. 

1. this is the code.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Center(
        child: Text("color problem")

      ),
    );
  }
}
```

2.  this is the screen I get when running the code above on MacOS. 

<img width="802" alt="스크린샷 2023-03-26 오후 12 53 29" src="https://user-images.githubusercontent.com/78672055/227754416-f256312f-177d-4b5d-9831-5a606f28041b.png">

how can is solve this problem?

**Comment by sinexy** [comment] 2023-03-26 04:36
Use the Scaffold widget to wrap your other widgets.
```
return MaterialApp(
    home: Scaffold(
        body:Center(
            child: Text("color problem")
            )
        ),
    );
```

**Comment by danagbemava-nc** [comment] 2023-03-27 07:24
Hi @HongWonjong, this is not a bug. The default background color for macOS desktop apps is black. 
The text you're seeing is also a result of the default text style. 

You can do https://github.com/flutter/flutter/issues/123487#issuecomment-1483992780 or use a material widget or provide your own text styles. 

Closing as this is not a bug. 

Thank you

**Closed by danagbemava-nc** 2023-03-27 07:24 UTC
Labels: in triage
