### ISSUE TITLE
[Impeller] Uneven letter spacing.

### ISSUE THREAD

**Issue by PiN73** [flutter/flutter#127815] opened 2023-05-30 00:30 UTC
Starting from Flutter 3.10, Impeller is used by default on iOS. Small text seems to have broken kerning

### Steps to reproduce

1. Create new app

2. Add small text (better noticeable on repeated letters)

```dart
Text('IIIIIIIII')
```

3. Run the app with Flutter 3.10.2 on iOS

### Expected results

The letters should render with even visual spacing (like it was in Skia)

<img alt=skia src=https://github.com/flutter/flutter/assets/18294052/de8102ec-d923-46a1-b09c-0373f75bd2ea height=160>

### Actual results

The letters renders with uneven visual spacing

<img alt=skia src=https://github.com/flutter/flutter/assets/18294052/95b34440-268e-4606-8ef9-07ed66cedbc2 height=160>

In real text it gives the impression of sloppy jumping letters

### Details

<details><summary>Full code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Material(
        color: Colors.white,
        child: Center(
          child: Text(
            'IIIIIIIII',
            style: TextStyle(
              color: Colors.black,
            ),
          ),
        ),
      ),
    );
  }
}
```

To reproduce old **Skia** behavior on Flutter 3.10
```console
flutter run --no-enable-impeller
```

To crop and scale screenshot (iPhone 14):
```console
convert screenshot.png -gravity center -crop 120x40+0+0 -scale 800% out.png
```

</details>

<details><summary>Tools versions</summary>

```console
Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E261 darwin-arm64, locale en-RU)
Xcode - develop for iOS and macOS (Xcode 14.3)
Android Studio (version 2022.2)

Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (6 days ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1
```

All the same on master:
```console
Flutter 3.11.0-14.0.pre.70 • channel master •
https://github.com/flutter/flutter.git
Framework • revision bd11ef06fd (8 hours ago) • 2023-05-29 11:50:25 -0400
Engine • revision f768be1078
Tools • Dart 3.1.0 (build 3.1.0-155.0.dev) • DevTools 2.23.1
```

</details>

May be related: #121887 #124310

**Comment by PiN73** [comment] 2023-05-30 01:06
The difference is more obvious with smaller text, e.g. `fontSize: 6`

<img alt=skia src=https://github.com/flutter/flutter/assets/18294052/bb53932b-7652-4c3e-8865-de5f05ac7dbb height=160>

<img alt=impeller src=https://github.com/flutter/flutter/assets/18294052/4cb7b7c0-6f94-46b4-9675-d24c2447cc1a height=160>

**Comment by huycozy** [comment] 2023-05-30 09:33
Thanks for your report. This issue is reproducible on the latest `stable` and `master` channels.

Issue is more visible with small fontSize (6.0) as mentioned above. I have placed the equal red rectangles so that we can clearly see the spacing difference between the letters.

This may be a regression since there was a similar issue that has been fixed: https://github.com/flutter/flutter/issues/124310

![Screenshot 2023-05-30 at 16 24 20](https://github.com/flutter/flutter/assets/104349824/963a6417-ab38-48e3-b05a-15a8efbfd836)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (22 hours ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-14.0.pre.73, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-14.0.pre.73 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 59128bd61e (49 minutes ago), 2023-05-29 22:35:15 -0400
    • Engine revision 93a8d41549
    • Dart version 3.1.0 (build 3.1.0-155.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by chinmaygarde** [comment] 2023-05-30 19:35
From Triage: This will be addressed by taking into account the subpixel hinting when rendering into the atlas.

**Comment by cuzyoucant** [comment] 2023-06-12 09:46
This also poses a problem when you have a vertically scrolling ListView. Depending on the text size and length, the text seems to jitters left and right.

On Android devices it works as expected but on all iPhones i have tested on (SE 2020, and 14 pro) the text jitters.
If Impeller is disabled, the text doesnt jitter anymore.

Small App sample to reproduce:
`
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: HorizontalTextScrollWidget(),
    );
  }
}

class HorizontalTextScrollWidget extends StatefulWidget {
  @override
  _HorizontalTextScrollWidgetState createState() =>
      _HorizontalTextScrollWidgetState();
}

class _HorizontalTextScrollWidgetState
    extends State<HorizontalTextScrollWidget> {
  final ScrollController _scrollController = ScrollController();
  final double _itemWidth = 200.0;
  final double _spacing = 10.0;
  final List<String> _textSamples = [
    'Text Sample 1. This is a long text sample.',
    'Text Sample 2. This is another long text sample.',
    'Text Sample 3. This is yet another long text sample.',
  ];
  int _currentIndex = 0;
  Timer? _timer;

  late List<Widget> _textWidgets;

  @override
  void initState() {
    super.initState();
    _textWidgets = _buildTextWidgets();
    WidgetsBinding.instance!.addPostFrameCallback((_) {
      _startAutoScroll();
    });
  }

  @override
  void dispose() {
    _scrollController.dispose();
    _timer?.cancel();
    super.dispose();
  }

  void _startAutoScroll() {
    _timer = Timer.periodic(const Duration(seconds: 7), (timer) {
      _currentIndex++;
      _scrollToIndex(_currentIndex);
    });
    _currentIndex++;
    _scrollToIndex(_currentIndex);
  }

  void _scrollToIndex(int index) {
    _scrollController.animateTo(
      index * (_itemWidth + _spacing),
      duration: const Duration(seconds: 7),
      curve: Curves.linear,
    );
  }

  List<Widget> _buildTextWidgets() {
    return _textSamples.map((text) {
      return _buildTextSample(text);
    }).toList();
  }

  Widget _buildTextSample(String text) {
    return Container(
      width: _itemWidth,
      margin: EdgeInsets.symmetric(horizontal: _spacing),
      padding: const EdgeInsets.all(10.0),
      color: Colors.grey,
      child: Center(
        child: Container(
          color: Colors.black,
          child: Text(
            text,
            textAlign: TextAlign.center,
            style: TextStyle(
                fontSize: 6, color: Colors.white, fontWeight: FontWeight.bold),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 200.0,
      child: ListView.builder(
        // prototypeItem: _textWidgets[0],
        itemExtent: _itemWidth + _spacing,
        scrollDirection: Axis.horizontal,
        controller: _scrollController,
        itemCount: null, // Set itemCount to null for endless scrolling
        itemBuilder: (context, index) {
          final adjustedIndex = index % _textWidgets.length;
          return _textWidgets[adjustedIndex];
        },
      ),
    );
  }
}
`

**Comment by bdero** [comment] 2024-05-01 20:53
We can mitigate this issue by making multiple variations of glyphs based on their subpixel positions.

**Closed** 2024-05-28 06:08 UTC
Labels: c: regression, platform-ios, engine, a: typography, has reproducible steps, P2, e: impeller, found in release: 3.10, found in release: 3.11, team-engine, triaged-engine, slimpeller
