### ISSUE TITLE
[Crash] WebView crashes when trying to open standart Select field in HTML

### ISSUE THREAD

**Issue by ProgrammingLife** [flutter/flutter#41771] opened 2019-10-02 10:38 UTC
Steps to reproduce:
```
        child: WebView(
          initialUrl: 'https://pixijs.io/bunny-mark/',
          javascriptMode: JavascriptMode.unrestricted,
        ),
```
When I try to select "Use Version" ("select a tag") I always get this crash:
```
E/AndroidRuntime( 6715): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListPopupWindow$DropDownListView.setSelection(int)' on a null object reference
E/AndroidRuntime( 6715): 	at android.widget.ListPopupWindow.show(ListPopupWindow.java:651)
E/AndroidRuntime( 6715): 	at SK.a(PG:23)
E/AndroidRuntime( 6715): 	at QK.onLayoutChange(PG:3)
E/AndroidRuntime( 6715): 	at android.view.View.layout(View.java:16772)
E/AndroidRuntime( 6715): 	at android.widget.AbsoluteLayout.onLayout(AbsoluteLayout.java:123)
E/AndroidRuntime( 6715): 	at android.view.View.layout(View.java:16763)
E/AndroidRuntime( 6715): 	at android.view.ViewGroup.layout(ViewGroup.java:5333)
E/AndroidRuntime( 6715): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime( 6715): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
E/AndroidRuntime( 6715): 	at android.view.View.layout(View.java:16763)
E/AndroidRuntime( 6715): 	at android.view.ViewGroup.layout(ViewGroup.java:5333)
E/AndroidRuntime( 6715): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
E/AndroidRuntime( 6715): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
```

Other elements seem work well.

```
» flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/denis/flutter
    • Framework revision 2d2a1ffec9 (4 недели назад), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/denis/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /home/denis/mylab/programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/denis/programs/android-studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • SM T531 • 50530ed7057f027b • android-arm • Android 5.0.2 (API 21)

• No issues found!
```

Android 5.0.2
Samsung Galaxy Tab4 SM-T531 10.1 inch
Flutter's doctor don't find any issues.

**Comment by escamoteur** [comment] 2019-10-02 11:58
Hi, thanks for reaching out. 

Could you please add the output of `flutter doctor .v` here?

Also a snippet of the HTML code that makes the problem would be helpfull

**Comment by escamoteur** [comment] 2019-10-02 12:08
Hi,
I just checked, there is a fix coming but we can't say when please see https://github.com/flutter/plugins/pull/1861

**Comment by ProgrammingLife** [comment] 2019-10-02 14:43
@escamoteur thanks for the answer. I've attached an output of the `flutter doctor -v` in the start message.

**Comment by mklim** [comment] 2020-01-07 18:32
Thanks for reporting this issue! Closing as a duplicate of flutter/flutter#25767.

**Closed by mklim** 2020-01-07 18:32 UTC
Labels: p: webview, severe: crash
