### ISSUE TITLE
firebase_admob warning message

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#22554] opened 2018-10-02 13:11 UTC
I just did copy and paste example code form `firebase_admob` plugin.
When I tapped `LOAD REWARDED VIDEO` console says this.

> <Google:HTML> You are currently using version 7.32.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from https://goo.gl/UoiJ8F. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.
<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
interstitial:didFailToReceiveAdWithError: No ad returned from any ad server. (MobileAd <FLTRewardedVideoAdWrapper: 0x6000013bb870> LOADING FLTRewardedVideoAdWrapper)

When I pressed `SHOW  REWARDED VIDEO`

> PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)

I literally didn't change anything. 

**Flutter doctor**

```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale ja-JP)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
exit code 0
```

**Comment by lianjianjie** [comment] 2018-11-29 08:33
it works on first load，but second not.

**Comment by collinjackson** [comment] 2019-04-18 18:21
Adding iOS because it looks like you are experiencing this on iOS. Are you seeing it on Android as well?

**Comment by kroikie** [comment] 2019-10-13 18:47
@ghost

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/631. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:35
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by zoeyfan** [comment] 2020-01-03 04:13
Unfortunately there isn't enough information on this bug to reproduce the issue. For example, which platform are you repro'ing this issue? 

Closing for now. If you are still experiencing this issue, you're welcome to reopen it. Please tell us exactly how to reproduce the problem you're running into. Attach a small sample that demonstrates the issue. 

Thank you for using Flutter!

**Closed by zoeyfan** 2020-01-03 04:13 UTC
Labels: p: firebase, p: firebase_admob, p: first party, plugin, severe: crash, transferred, ⌺‬ platform-ios
