### ISSUE TITLE
XIAOMI privacy compliance testing rejected

### ISSUE THREAD

**Issue by icc-tips** [flutter/flutter#153750] opened 2024-08-20 09:17 UTC
### Steps to reproduce

editable_text.dart

//
clipboardStatus.update();
//
It will trigger the behavior of actively obtaining the adhesive board, which will result in privacy compliance failure

### Expected results

I hope to trigger the behavior of actively obtaining the adhesive board,

### Actual results

It will trigger the behavior of actively obtaining the adhesive board, which will result in privacy compliance failure

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-21 07:31
Closing this as a duplicate of https://github.com/flutter/flutter/issues/101196

**Closed by danagbemava-nc** 2024-08-21 07:31 UTC
Labels: in triage
