### ISSUE TITLE
Building flutter tool error: The '===' operator is not supported.

### ISSUE THREAD

**Issue by kami-mehar38** [flutter/flutter#58683] opened 2020-06-04 15:56 UTC
Im trying to upgrade flutter but once it moves to Building flutter tool then it prints the following error on console:
../../Tools/flutter/packages/flutter_tools/lib/src/version.dart:751:1: Error: The '===' operator is not supported.

**Comment by jonahwilliams** [comment] 2020-06-04 16:01
duplicate of https://github.com/flutter/flutter/issues/58564

**Closed by jonahwilliams** 2020-06-04 16:01 UTC
