### ISSUE TITLE
✗ Flutter plugin not installed; this adds Flutter specific functionality.     ✗ Dart plugin not installed; this adds Dart specific functionality.

### ISSUE THREAD

**Issue by bholendraofficial** [flutter/flutter#68282] opened 2020-10-16 08:32 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by bholendraofficial** [comment] 2020-10-16 08:32
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

**Comment by sidrao2006** [comment] 2020-10-16 08:35
Duplicate of #68274

**Comment by darshankawar** [comment] 2020-10-16 09:17
Closing this as duplicate of [67986](https://github.com/flutter/flutter/issues/67986)

**Closed by darshankawar** 2020-10-16 09:17 UTC
