### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by sajib1066** [flutter/flutter#155882] opened 2024-09-28 16:17 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#2      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#3      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale en-BD)
    [32m•[39m Flutter version 3.24.3 on channel stable at /Users/sajib/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [3

**Comment by danagbemava-nc** [comment] 2024-09-30 06:57
Closing this as a duplicate of https://github.com/flutter/flutter/issues/154903, parent issue in https://github.com/flutter/flutter/issues/153471.

If you have a reliable way to let us reproduce this, kindly leave a comment in the parent issue.

Thank you

**Closed by danagbemava-nc** 2024-09-30 06:57 UTC
Labels: in triage
