### ISSUE TITLE
Could not authenticate download server

### ISSUE THREAD

**Issue by see311** [flutter/flutter#18262] opened 2018-06-07 07:40 UTC
## Steps to Reproduce

1. flutter upgrade 0.2 to 0.3
2. flutter doctor in my project folder
3. got things like below:
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading package sky_engine...(cached)
Downloading common tools...                                  7.0s
Downloading windows-x64 tools...                             9.9s
Downloading android-arm-profile/windows-x64 tools...
Could not authenticate download server. You may be experiencing a man-in-the-middle attack,
your network may be compromised, or you may have malware installed on your computer.
URL: https://storage.flutter-io.cn/flutter_infra/flutter/06afdfe54ebef9168a90ca00a6721c2d36e6aafa/android-arm-profile/windows-x64.zip
```

Each time I run flutter doctor, I got different logs. After several times, I got one log like below:
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading package sky_engine...(cached)
Downloading common tools...(cached)
Downloading windows-x64 tools...(cached)
Downloading android-arm-profile/windows-x64 tools...(cached)
Downloading android-arm-release/windows-x64 tools...(cached)
Downloading android-arm64-profile/windows-x64 tools...(cached)
Downloading android-arm64-release/windows-x64 tools...(cached)
Downloading android-x86 tools...                            116.9s
Downloading android-x64 tools...                            42.0s
Downloading android-arm tools...                            45.0s
Downloading android-arm-profile tools...
Could not authenticate download server. You may be experiencing a man-in-the-middle attack,
your network may be compromised, or you may have malware installed on your computer.
URL: https://storage.flutter-io.cn/flutter_infra/flutter/06afdfe54ebef9168a90ca00a6721c2d36e6aafa/android-arm-profile/artifacts.zip
```

After many many times, it become a normal flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.81], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected devices (1 available)

• No issues found!
```

I'm from China, and add the environment variable like wiki article said.

**Comment by chinmaygarde** [comment] 2018-06-09 01:12
cc @Hixie

**Comment by zoechi** [comment] 2019-02-22 10:05
Duplicate of #22502

**Closed by zoechi** 2019-02-22 10:05 UTC
Labels: a: china, a: first hour, severe: crash, tool
