### ISSUE TITLE
crashing issue for the package

### ISSUE THREAD

**Issue by vartikaantino** [flutter/flutter#118775] opened 2023-01-19 07:37 UTC
Hi ,

I have used this plugin to design custom camera and when it is released we are facing lot's of crash issue due to plugin. Can you please have a look into that .

I am attaching logs for the same as well.

```
android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError (CameraDeviceImpl.java:2228)
android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal (CameraDeviceImpl.java:658)
android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession (CameraDeviceImpl.java:644)
arrow_right
io.flutter.plugins.camera.Camera$DefaultCameraDeviceWrapper.createCaptureSession (Camera.java:175)
io.flutter.plugins.camera.Camera.createCaptureSessionWithSessionConfig (Camera.java:479)
io.flutter.plugins.camera.Camera.createCaptureSession (Camera.java:465)
io.flutter.plugins.camera.Camera.createCaptureSession (Camera.java:387)
io.flutter.plugins.camera.Camera.startPreview (Camera.java:1074)
io.flutter.plugins.camera.Camera$1.onOpened (Camera.java:322)
android.hardware.camera2.impl.CameraDeviceImpl$1.run (CameraDeviceImpl.java:151)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:223)
android.os.HandlerThread.run (HandlerThread.java:67)
```

Thanks
Vartika Mangal

**Comment by danagbemava-nc** [comment] 2023-01-19 11:14
Hi @vartikaantino,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the version of `camera` & `camera_android` that you're using as well as the device(s) you're experiencing the crash on. 

Thank you

**Comment by vartikaantino** [comment] 2023-01-20 04:38
HI, 

I am attaching sample code and camera version:

Camera version: 0.10.1

Please check this image as well
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/88431640/213618353-88f1e599-8114-4cb5-85f2-d22a50fa974c.png">


class CameraPreviewPage extends StatefulWidget {
  const CameraPreviewPage(
      {Key? key, required this.cameras, required this.lensDirection})
      : super(key: key);
  final CameraLensDirection lensDirection;
  final List<CameraDescription>? cameras;
  @override
  State<CameraPreviewPage> createState() => _CameraPreviewPageState();
}

class _CameraPreviewPageState extends State<CameraPreviewPage> {
  late CameraController _cameraController;
  bool _isRearCameraSelected = false;
  XFile picture = XFile("");
  @override
  void dispose() {
    _cameraController.dispose();
    picture = XFile("");
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    if (widget.lensDirection == CameraLensDirection.back) {
      _isRearCameraSelected = true;
    }
    final camera = widget.cameras!
        .firstWhere((element) => element.lensDirection == widget.lensDirection);
    initCamera(camera);
  }

  Future takePicture() async {
    if (!_cameraController.value.isInitialized) {
      return null;
    }
    if (_cameraController.value.isTakingPicture) {
      return null;
    }
    try {
      await _cameraController.setFlashMode(FlashMode.off);
      picture = await _cameraController.takePicture();
      setState(() {});
    } on CameraException catch (e) {
      debugPrint('Error occured while taking picture: $e');
      return null;
    }
  }

  Future initCamera(CameraDescription cameraDescription) async {
    _cameraController =
        CameraController(cameraDescription, ResolutionPreset.high);
    try {
      await _cameraController.initialize().then((_) {
        if (!mounted) return;
        setState(() {});
      });
    } on CameraException catch (e) {
      debugPrint("camera error $e");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
      child: Stack(children: [
        picture.path == ""
            ? (_cameraController.value.isInitialized)
                ? CameraPreview(_cameraController)
                : Container(
                    color: Colors.black,
                    child: const Center(child: CircularProgressIndicator()))
            : !_isRearCameraSelected
                ? Transform(
                    alignment: Alignment.center,
                    transform: Matrix4.rotationY(math.pi),
                    child: Image.file(File(picture.path), fit: BoxFit.cover))
                : Image.file(File(picture.path), fit: BoxFit.cover),
        Align(
            alignment: Alignment.bottomCenter,
            child: Container(
              height: MediaQuery.of(context).size.height * 0.20,
              decoration: const BoxDecoration(
                  borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
                  color: Colors.black),
              child: picture.path == ""
                  ? Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                          Expanded(
                            child: GestureDetector(
                              onTap: () {
                                if (_isRearCameraSelected) {
                                  final camera = widget.cameras!.firstWhere(
                                      (element) =>
                                          element.lensDirection ==
                                          CameraLensDirection.front);
                                  _isRearCameraSelected =
                                      !_isRearCameraSelected;
                                  initCamera(camera);
                                } else {
                                  final camera = widget.cameras!.firstWhere(
                                      (element) =>
                                          element.lensDirection ==
                                          CameraLensDirection.back);
                                  _isRearCameraSelected =
                                      !_isRearCameraSelected;
                                  initCamera(camera);
                                }
                                setState(() {});
                              },
                              child: Icon(
                                _isRearCameraSelected
                                    ? CupertinoIcons.switch_camera
                                    : CupertinoIcons.switch_camera_solid,
                                color: Colors.white,
                                size: 35 * SizeConfig.imageSizeMultiplier!,
                              ),
                            ),
                          ),
                          Expanded(
                            child: GestureDetector(
                              onTap: takePicture,
                              child: Icon(
                                Icons.circle,
                                color: Colors.white,
                                size: 60 * SizeConfig.imageSizeMultiplier!,
                              ),
                            ),
                          ),
                          Spacer()
                        ])
                  : Row(
                      children: [
                        Expanded(
                          child: GestureDetector(
                            onTap: () {
                              setState(() => picture = XFile(""));
                            },
                            child: Container(
                                decoration: BoxDecoration(
                                    color: grey217, shape: BoxShape.circle),
                                child: Icon(
                                  Icons.close,
                                  color: black50,
                                  size: 40 * SizeConfig.imageSizeMultiplier!,
                                )),
                          ),
                        ),
                        Expanded(
                            child: Container(
                          decoration: BoxDecoration(
                              color: grey217, shape: BoxShape.circle),
                          child: GestureDetector(
                            onTap: () {
                              Navigator.pop(context, picture.path);
                            },
                            child: Icon(
                              Icons.check_rounded,
                              color: black50,
                              size: 40 * SizeConfig.imageSizeMultiplier!,
                            ),
                          ),
                        )),
                      ],
                    ),
            )),
      ]),
    ));
  }
}

**Comment by danagbemava-nc** [comment] 2023-01-20 06:46
Hi @vartikaantino, it turns out that this is a duplicate of  https://github.com/flutter/flutter/issues/110378. 

Kindly follow up in the issue linked above for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-01-20 06:46 UTC
Labels: in triage
