### ISSUE TITLE
[go_router_builder] only override redirect on GoRouteData，use android back，will crash

### ISSUE THREAD

**Issue by jiechic** [flutter/flutter#150400] opened 2024-06-18 01:48 UTC
### Steps to reproduce
- > start root with “/”
- > goRouter redirect to "/login"
- > login module redirect to "/login/password"
- > when i use android key back 
### Expected results

close app

### Actual results

will crash with info “One of `build` or `buildPage` must be implemented.”

### Code sample

<details open><summary>Code sample</summary>

1. write a module "login" router with go_router_builder
```dart
@TypedGoRoute<LoginRoute>(
  path: '/login',
  routes: [
    TypedGoRoute<LoginPasswordRoute>(
      path: "password",
    ),
    TypedGoRoute<LoginSmsCodeRoute>(
      path: "smsCode",
    ),
    TypedGoRoute<LoginSecureRoute>(
      path: "secure",
    ),
  ],
)
class LoginRoute extends GoRouteData {
  String? returnUrl;

  LoginRoute({
    this.returnUrl,
  });

  @override
  FutureOr<String?> redirect(BuildContext context, GoRouterState state) {
    if (Uri.parse(location).path == state.uri.path) {
      return Uri(
              path: "/login/password",
              queryParameters: state.uri.queryParameters)
          .toString();
    }
    return null;
  }
}

class LoginPasswordRoute extends GoRouteData {
  String? returnUrl;

  LoginPasswordRoute({
    this.returnUrl,
  });

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return AuthorizationPage(returnUrl: returnUrl);
  }
}

class LoginSecureRoute extends GoRouteData {
  final String? account;
  final String? safeToken;
  final String? mobile;

  LoginSecureRoute({
    required this.account,
    required this.safeToken,
    required this.mobile,
  });

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return LoginSecurityPage(
      account: account,
      safeToken: safeToken,
      mobile: mobile,
    );
  }
}

class LoginSmsCodeRoute extends GoRouteData {
  String? returnUrl;

  LoginSmsCodeRoute({
    this.returnUrl,
  });
}
```
2. write root router with module "login"
```dart
GoRouter(
        routes: [
          GoRoute(
            path: "/",
            builder: (context, state) => const Text("root"),
            routes: [
              GoRoute(
                path: "me",
                builder: (context, state) => const Text("me"),
              ),
            ],
          ),
          $loginRoute,
        ],
        observers: navigatorObservers,
        redirect: (BuildContext context, GoRouterState state) async {
          ///if login path，no redirect
          if (state.matchedLocation.contains(($loginRoute as GoRoute).path) ==
              true) {
            return null;
          }

          ///if no auth，redirect to login path
          if (!await authData.isLogin()) {
            return Uri(
              path: "/login",
              queryParameters: {"return-url": state.uri.toString()},
            ).toString();
          }
          return null;
        },
      );
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-06-18 09:41
Hi @jiechic 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. It would be ideal if you could create a GitHub repository for the sample code. Thanks!

**Comment by jiechic** [comment] 2024-06-20 07:53
this is a sample code project in follow url
https://github.com/jiechic/go_router_builder_crash

reshow error by follow step

1. run app with android emulator
2. click android emulator return key

![image](https://github.com/flutter/flutter/assets/518977/8bbf0789-6199-4bdb-ab3f-1b5c8acc0c52)

**Comment by huycozy** [comment] 2024-06-21 05:14
I see, you are putting `password` as a sub-route of `login` (`login` route implemented `redirect` only). There is a similar case at https://github.com/flutter/flutter/issues/103368. It's explained that this is working as intended, see https://github.com/flutter/flutter/issues/103368#issuecomment-1589690425. Please also check the solution there.

Closing this as a duplicate of https://github.com/flutter/flutter/issues/103368.

**Closed by huycozy** 2024-06-21 05:14 UTC
Labels: in triage

**Comment by jiechic** [comment] 2024-06-24 01:27
Build goRouter using Goute instead of goRouterBuilder was success
new code update to branch [go_router](https://github.com/jiechic/go_router_builder_crash/tree/go_router)

new question：
The implementation of go_router_builder is inconsistent with the default goRouter ？

**Comment by jiechic** [comment] 2024-06-24 01:29
> Build goRouter using Goute instead of goRouterBuilder was success new code update to branch [go_router](https://github.com/jiechic/go_router_builder_crash/tree/go_router)
> 
> new question： The implementation of go_router_builder is inconsistent with the default goRouter ？

@huycozy 
The implementation of go_router_builder is inconsistent with the default goRouter

> I see, you are putting `password` as a sub-route of `login` (`login` route implemented `redirect` only). There is a similar case at #103368. It's explained that this is working as intended, see [#103368 (comment)](https://github.com/flutter/flutter/issues/103368#issuecomment-1589690425). Please also check the solution there.
> 
> Closing this as a duplicate of #103368.

@huycozy 

Build goRouter using Goute instead of goRouterBuilder was success
new code update to branch [go_router](https://github.com/jiechic/go_router_builder_crash/tree/go_router)

new question：
The implementation of go_router_builder is inconsistent with the default goRouter ？
