### ISSUE TITLE
`--tree-shake-icons` broken for web

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#102489] opened 2022-04-25 08:49 UTC
1. `flutter create my_app`
2. `flutter build web --tree-shake-icons`

```
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///Users/plg/development/flutter-dev/packages/flutter/lib/src/widgets/icon_data.dart:20:9
Target web_release_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with
--no-tree-shake-icons.
```

**Comment by jonahwilliams** [comment] 2022-04-26 03:45
Duplicate of https://github.com/flutter/flutter/issues/57181

**Closed by jonahwilliams** 2022-04-26 03:45 UTC
Labels: a: assets, platform-web, P3
