### ISSUE TITLE
Copying of code in codelab

### ISSUE THREAD

**Issue by Chisom-Collins** [flutter/flutter#118089] opened 2023-01-06 09:53 UTC
Hi 
When i copy the code on codelab unto my IDE , i get an error 
Below is the code , kindly assist

import 'package:english_words/english_words.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => MyAppState(),
      child: MaterialApp(
        title: 'Namer App',
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
        ),
        home: MyHomePage(),
      ),
    );
  }
}

class MyAppState extends ChangeNotifier {
  var current = WordPair.random();
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var appState = context.watch<MyAppState>();

    return Scaffold(
      body: Column(
        children: [
          Text('A random idea:'),
          Text(appState.current.asLowerCase),
        ],
      ),
    );
  }
}

**Comment by exaby73** [comment] 2023-01-06 10:19
Hello @Chisom-Collins. Could you provide a link to the codelab in question?

**Comment by Chisom-Collins** [comment] 2023-01-06 10:22
> Hello @Chisom-Collins. Could you provide a link to the codelab in question?

Hi @exaby73  the link is https://codelabs.developers.google.com/codelabs/flutter-codelab-first#2

it is the main.dart part

**Comment by exaby73** [comment] 2023-01-06 13:06
Can you provide the error that you get when trying to run this code?

**Comment by Chisom-Collins** [comment] 2023-01-06 14:21
![Screenshot (62)](https://user-images.githubusercontent.com/119885126/211030462-422ec50a-379b-43cd-9502-1b180b7554d1.png)

**Comment by exaby73** [comment] 2023-01-06 14:26
You need to install the `provider` and `english_words` packages. You can do this from the VsCode command pallete (ctrl + shift + p). Search for `Dart: Add dependency` and type in `provider,english_words`. This should install those packages. Read more about how to manage packages [here](https://dart.dev/guides/packages). This is working as expected. If you have issues, I suggest doing a search on Google or Stackoverflow or finding a resources at https://flutter.dev/community for these types of questions. But since this is not a bug or feature request, I am closing this issue. Thank you

**Closed by exaby73** 2023-01-06 14:27 UTC
Labels: in triage
