### ISSUE TITLE
Flutter web's canvaskit.wasm is too slow

### ISSUE THREAD

**Issue by steeling** [flutter/flutter#82757] opened 2021-05-17 22:16 UTC
Flutter web requires canvaskit.wasm to download prior to painting anything on the screen. This is hardcoded to https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.wasm, which is having issues.

I'm seeing 10+ second load times to downloading this file, which blocks the entire app. This should be moved to a new location that loads much faster, or we should have the flexibility to host it ourselves and point to it.

A couple ways to repeat this

curl -o /dev/null -s "https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.wasm" -w %{time_connect}:%{time_starttransfer}:%{time_total}

Open a tab in chrome and open the network tab in developer tools. Then click "disable cache", and browse to your app. You should see in the list of network requests the calls being made to download the wasm files.

I'd expect the file to load in < 500 ms. Can you please allow us to change the link at which this downloads, or put such a popular library on a CDN?

**Comment by TahaTesser** [comment] 2021-05-18 11:18
Hi @steeling 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/76009
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-18 11:18 UTC
Labels: in triage
