### ISSUE TITLE
Regression in iOS simulator performance during scale animation

### ISSUE THREAD

**Issue by fipooo** [flutter/flutter#41469] opened 2019-09-27 12:41 UTC
I update Xcode and after this I have problem with animation on simulator (iPhone 8 with iOS 13 and iPhone 11). On real device (only android I don't have device with iOS) and simulator (android) working fine.

Ios - video  https://streamable.com/tbe2g

Android video - https://streamable.com/qmi0n

```
@override
  initState() {
    animationController = AnimationController(duration: new Duration(milliseconds: 250), vsync: this);

animation = Tween<double>(begin: 15, end: 75).animate(animationController)..addListener((){
      setState(() {

      });
    });

  @override
  Widget build(BuildContext context) {
return new PlatformScaffold(
body: Stack(
        children: <Widget>[
                Positioned(
                  bottom: 15,
                  right: 15,
                  child: Transform.scale(
                    scale: animation.value-1,
                    child: FloatingActionButton(
                      heroTag: null,
                      shape: new RoundedRectangleBorder(borderRadius: new BorderRadius.circular(10.0)),
                      elevation: 10.0,
                      onPressed: (){
                        animationController.forward();
                      },
                      child: Icon(Icons.add, color: Colors.white),
                      backgroundColor: AppTheme().getMainColor(),
                    ),
                  ),
                ),

]
)
);
}
}
```

Before update (iPhone X) worked fine.

```
[✓] Flutter (Channel beta, v1.9.1+hotfix.3, on Mac OS X 10.14.6 18G95, locale pl-PL)
    • Flutter version 1.9.1+hotfix.3 at /Users/macbook/Developer/flutter
    • Framework revision a72edc2706 (2 days ago), 2019-09-25 15:41:01 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 5.1.1 (API 22) (emulator)
    • iPhone 8 Plus             • 5B944061-E9FA-4D20-9CC2-C77BD6A5A1B2 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by janmoppel** [comment] 2019-09-27 15:38
Hello @fipooo !

Thank you for posting an issue.
Unfortunately, your videos cannot be watched, because it requires authorization. Can you attach examples differently?

Also, it would be very helpful if you could create a self-contained repository or post code example here, so that your issue could be easily reproduced.

Thank you.

**Comment by fipooo** [comment] 2019-09-29 16:34
> Hello @fipooo !
> 
> Thank you for posting an issue.
> Unfortunately, your videos cannot be watched, because it requires authorization. Can you attach examples differently?
> 
> Also, it would be very helpful if you could create a self-contained repository or post code example here, so that your issue could be easily reproduced.
> 
> Thank you.

I uploaded videos to another hosting and I added a piece of code.

**Comment by liyuqian** [comment] 2019-12-02 23:25
Thank you @fipooo for the report! I'll test it on a real iPhone Xs device to see if the regression is simulator-only, or if it also affects real iPhone devices.

**Comment by liyuqian** [comment] 2019-12-05 01:19
@fipooo : sorry, the code you put in https://github.com/flutter/flutter/issues/41469#issue-499423063 doesn't reproduce the animation in the video (I put it in the `main.dart` file as https://gist.github.com/liyuqian/ebcb2e7a31f3a83959bbaac39f9490bd).

Anyway, I think it's expected to see worse performance in the iOS simulator, than in Android simulator or Android/iOS devices. In iOS simulators, we can't use hardware acceleration (GPU) so everything is rendered using software (CPU), because the iOS simulator itself is emulating OpenGL with CPU instead of using the real GPU of your laptops/desktops. In all other cases, Flutter uses GPU to accelerate the rendering.

**Comment by csells** [comment] 2020-01-10 23:29
closing this issue as expected behavior (no GPU in the iOS simulator)

**Closed by csells** 2020-01-10 23:29 UTC
Labels: a: animation, engine, severe: performance, severe: regression, waiting for customer response, ⌺‬ platform-ios
