### ISSUE TITLE
Using Admob AndroidView causes crash

### ISSUE THREAD

**Issue by hysheng** [flutter/flutter#45386] opened 2019-11-22 06:58 UTC
## Steps to Reproduce

I use Google Admob in my Flutter app, but since Admob doesn't provide a Flutter package, I can only use Admob's advertising service through native Android controls. In the Flutter code, build an AndroidView to generate Admob's advertising tools. However, there was a crash in some models.

**Target Platform:**Android
**Target OS version/browser:**6.0,7.0,8.0,9.0
**Devices:**Galaxy J2 Prime、Galaxy J2 Prime、Galaxy J1

## Logs
```bash
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference
       at org.chromium.ui.display.DisplayAndroid.updateFromDisplay(DisplayAndroid.java:133)
       at org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged(DisplayAndroidManager.java:169)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:467)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5628)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
```

**Comment by iapicca** [comment] 2019-11-22 10:58
Hi @hysheng 
could you please provide your updated  `flutter doctor -v`
and  a minimal code sample to reproduce the problem?
Also you may consider using [firebase_admob](https://pub.dev/packages/firebase_admob).
Thank you

**Comment by hysheng** [comment] 2019-11-25 03:56
Sorry, this bug has a low recurrence rate and may be easier to reproduce on those models.
I have used firebase_admob, but it has some limitations, does not support native ads, and does not meet our needs. So we will use the AndroidView method to call the custom Admob, on the Android platform, expand Admob. This is the native view of Android called on Flutter, just a normal call method.
Also, this is my Flutter related information:
_
C:\Users\walla>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
    • Flutter version 1.9.1+hotfix.6 at C:\SDK\flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\walla\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\DevTools\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\DevTools
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM J7108 • 330092543274b2df • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 1 category._

**Comment by iapicca** [comment] 2019-12-11 10:19
Hi @hysheng 
the issue need to be reproducible to be workable,
could you please provide a minimal code sample?
Thank you

**Comment by hysheng** [comment] 2020-01-02 07:55
@iapicca 
Sorry, in fact I can't reproduce it. The crash logs I receive are from the user and I cannot reproduce them. My project was developed using Flutter. Since Admob does not provide Flutter version support, I can only call Android's native Admob related advertising controls on Flutter. So, I don't know how to provide you with code snippets.

**Comment by VladyslavBondarenko** [comment] 2020-01-16 14:07
Possibly related to https://github.com/flutter/flutter/issues/12114

**Comment by iapicca** [comment] 2020-01-30 09:46
Hi @hysheng 
with the given information the issue is not workable
please consider providing a reproducible minimal code sample 
of your platform view implementation for admob 
to allow us to investigate the problem
Thank you

**Comment by iapicca** [comment] 2020-03-20 12:07
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-03-20 12:07 UTC
Labels: a: platform-views, dependency: android, framework, severe: crash, waiting for customer response, ▣ platform-android

**Comment by lds8988** [comment] 2020-08-14 12:22
@iapicca I have this problem.
here is the info:

Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)

webview_flutter: 0.3.22+1

java.lang.NullPointerException
Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference
1 org.chromium.ui.display.DisplayAndroid.updateFromDisplay(DisplayAndroid.java:280)
--
2 org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged(DisplayAndroidManager.java:176)
3 android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:462)
4 android.os.Handler.dispatchMessage(Handler.java:102)
5 android.os.Looper.loop(Looper.java:177)
6 android.app.ActivityThread.main(ActivityThread.java:6691)
7 java.lang.reflect.Method.invoke(Native Method)
8 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
9 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

phone list:
努比亚 NX563J | Android 7.1.1,level 25
OPPO R9S | Android 6.0.1,level 23
VIVO X9I | Android 7.1.2,level 25
VIVO X9 | Android 7.1.2,level 25
VIVO X9PLUS | Android 7.1.2,level 25
VIVO Y79A | Android 7.1.2,level 25
华为 CAZ AL10 | Android 7.0,level 24
OPPO A57T | Android 6.0.1,level 23

**Comment by Rickyballs** [comment] 2020-11-24 07:18
@iapicca I have this problem too.
here is the info:
Flutter 1.22.2
webview_flutter: 1.0.7

only crash on 

华为 CAZ AL10 | Android 7.0,level 24

**Comment by iapicca** [comment] 2020-11-24 07:49
@Rickyballs @lds8988 

please follow the info [above](https://github.com/flutter/flutter/issues/45386#issuecomment-601667356)

> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
> All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Rickyballs** [comment] 2020-11-24 08:16
https://github.com/flutter/flutter/issues/71142#issue-749480843
