### ISSUE TITLE
Material 3 `TabBar` does not take full width when `isScrollable: true`

### ISSUE THREAD

**Issue by m-haisham** [flutter/flutter#117722] opened 2022-12-28 09:18 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 

The bottom divider of the `TabBar` taking the full width available

**Actual results:** 

The `TabBar` taking minimum possible width.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> with SingleTickerProviderStateMixin {
  late TabController controller;

  final tabs = ['Tab 1', 'Tab 2', 'Tab 3'];

  @override
  void initState() {
    super.initState();
    controller = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    super.dispose();
    controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            controller: controller,
            tabs: tabs.map((name) => Tab(text: name)).toList(),
            isScrollable: true,
          ),
        ),
        body: TabBarView(
          controller: controller,
          children: tabs.map((name) => Center(child: Text(name))).toList(),
        ),
      ),
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

[logs.txt](https://github.com/flutter/flutter/files/10313296/logs.txt)

```
No issues found! (ran in 5.3s)
```

```
[✓] Flutter (Channel beta, 3.7.0-1.2.pre, on Microsoft Windows [Version 10.0.19043.2075], locale en-US)
    • Flutter version 3.7.0-1.2.pre on channel beta at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c29b09b878 (8 days ago), 2022-12-19 18:30:12 -0600
    • Engine revision 8c99b0feaf
    • Dart version 2.19.0 (build 2.19.0-444.2.beta)
    • DevTools version 2.20.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)  
    • Android SDK at C:\Users\mohamed.haisham\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java        
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) 
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)     
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community    
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) 

[✓] VS Code (version 1.74.2)
    • VS Code at C:\Users\mohamed.haisham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.2075]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

<img src="https://user-images.githubusercontent.com/47662901/209788500-bbefaffa-e635-4075-918f-e2721210ed21.png" width ="300">

**Comment by darshankawar** [comment] 2022-12-28 10:48
Thanks for the report.

1. With `material3: true`:

<img width="349" alt="Screenshot 2022-12-28 at 4 14 48 PM" src="https://user-images.githubusercontent.com/67046386/209800425-f5cda5c9-51b4-4873-983d-8c01331a4ceb.png">


2. Without `material3: true`:

<img width="347" alt="Screenshot 2022-12-28 at 4 15 18 PM" src="https://user-images.githubusercontent.com/67046386/209800485-5eba84d7-3f7b-45cf-9eaf-107d81a03802.png">

<details>
<summary> master flutter doctor -v </summary>

```

[!] Flutter (Channel master, 3.7.0-13.0.pre.51, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-13.0.pre.51 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6441a7dc62 (3 hours ago), 2022-12-22 20:38:18 -0500
    • Engine revision 12badb5459
    • Dart version 3.0.0 (build 3.0.0-60.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by maheshmnj** [comment] 2023-01-06 08:34
Also reproduces on stable 3.3

<img width="341" alt="image" src="https://user-images.githubusercontent.com/31410839/210962777-9f1dca6e-aa82-48a0-9cf3-f3b1d6131263.png">

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2023-01-06 08:59
> Also reproduces on stable 3.3
> 
> <img alt="image" width="341" src="https://user-images.githubusercontent.com/31410839/210962777-9f1dca6e-aa82-48a0-9cf3-f3b1d6131263.png">
> 
> flutter doctor -v (mac)

This is an unrelated issue to this (https://github.com/flutter/flutter/issues/103642) and It's been fixed, not available in stable yet.

**Comment by maheshmnj** [comment] 2023-01-06 15:13
The screenshot I have shared was pointing to this issue itself (It has multiple issues though), the tabbar is not of full width.

**Comment by TahaTesser** [comment] 2023-01-06 15:30
> The screenshot I have shared was pointing to this issue itself (It has multiple issues though), the tabbar is not of full width.

This is still using M2 TabBar, comparison in https://github.com/flutter/flutter/issues/117722#issuecomment-1366557610 and the full-width issue is expected for M3 which is not available in stable.

**Comment by Piinks** [comment] 2023-03-28 16:40
The change that closed this is being reverted. Reopening.

**Comment by TahaTesser** [comment] 2023-04-05 11:14
@Piinks 

>   test where the tabs were aligned to the left of the tab bar, and the change made then centered.

This is expected since the M3 TabBar with scrollable needs to take all the available width for the divider to stretch. 
Update tests cover this in https://github.com/flutter/flutter/pull/123127.

I can introduce `TabGravity`,   I can see this option in Android components. 
This way it would be possible to align the tab bar with `scrollable`  to the left. 

This doesn't exist in Flutter yet.

https://user-images.githubusercontent.com/48603081/230061965-df63d122-a345-42c0-8684-c05e4db335c3.mp4


Also filed an issue for this https://github.com/flutter/flutter/issues/124195 


#### Without my PR, the tab bar cannot take the whole width for the divider to be drawn all the way.

![Screenshot 2023-04-05 at 12 48 25](https://user-images.githubusercontent.com/48603081/230064172-98cdbe4f-5648-42a4-b8f4-3061255749e8.png)





#### https://github.com/flutter/flutter/pull/123127 fixed this 


![Screenshot 2023-04-05 at 12 48 46](https://user-images.githubusercontent.com/48603081/230064242-35ea0479-cfc0-4fe5-b6f1-75b57effc384.png)



### With` TabGravity` we can get center or start, while still taking the whole width.
![Screenshot 2023-04-05 at 14 13 40](https://user-images.githubusercontent.com/48603081/230064485-74c41290-2717-4548-adf6-3e024fa5ea11.png)

**Comment by Piinks** [comment] 2023-04-05 16:09
Thanks for investigating @TahaTesser! The customer will want to be able to maintain the UI they had, so adding the option to align the tabs is a great idea.
I don't think we use 'gravity' anywhere in the framework. I am really glad you found this concept already exists. To make it consistent and more abstract from Android development, WDYT of TabAlignment?

![image](https://user-images.githubusercontent.com/16964204/230139912-d00e64aa-7d97-4b58-8f58-b83f8b7eb386.png)

**Comment by TahaTesser** [comment] 2023-04-05 17:46
> To make it consistent and more abstract from Android development, WDYT of TabAlignment?

That definitely sounds more Flutterish, I like it. 


There will be only `start` and `center` properties tho.   


(Similar to fill and center here)
![image](https://user-images.githubusercontent.com/48603081/230161559-a3eec63f-0287-43ea-866f-43384645126b.png)

**Comment by Piinks** [comment] 2023-04-05 17:48
Oh! What about adding support for left to be thorough, with right & center? I wonder if the other *Alignment properties take into account the Directionality, especially when TextDirection is rtl. If so, we should follow conventions there too.

**Comment by TahaTesser** [comment] 2023-04-05 17:54
> Oh! What about adding support for left to be thorough, with right & center? I wonder if the other *Alignment properties take into account the Directionality, especially when TextDirection is rtl. If so, we should follow conventions there too.

RTL shouldn't be a problem, `start` supports  left on LTR and right in RTL.  I'll make sure this works as expected. 

`end` is the opposite` tho and you will need to reverse scroll direction.

**Comment by okerivy** [comment] 2023-05-11 14:23
How can I modify or remove the bottom divide color

**Comment by TahaTesser** [comment] 2023-05-11 14:26
> How can I modify or remove the bottom divide color

You can set a transparent color.
![Screenshot 2023-05-11 at 17 25 16](https://github.com/flutter/flutter/assets/48603081/41279d97-38a1-4516-825c-30b7abd74ca9)

(When the fix for this issue lands, you can also set `dividerHeight` to `0`)

**Comment by okerivy** [comment] 2023-05-12 01:26
> > How can I modify or remove the bottom divide color
> 
> You can set a transparent color. ![Screenshot 2023-05-11 at 17 25 16](https://user-images.githubusercontent.com/48603081/237718581-41279d97-38a1-4516-825c-30b7abd74ca9.png)
> 
> (When the fix for this issue lands, you can also modify divider height)

Amazing 
Thank you for your help 😎

**Comment by TahaTesser** [comment] 2023-07-25 11:49
This week looking going into the tab bar implementation closely and figure out the caused the fix to be reverted and reland this.

**Closed** 2023-08-02 00:48 UTC
Labels: framework, f: material design, has reproducible steps, P1, found in release: 3.7, team-design, triaged-design, multiteam-retriage-candidate
