### ISSUE TITLE
Flutter engine artifacts version mismatch

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#27574] opened 2019-02-06 01:17 UTC
The engine artifacts for version fde59006da24 is actually engine artifacts for version at least 2f18c3286

See https://github.com/flutter/flutter/issues/27558#issuecomment-460867005

**Comment by liyuqian** [comment] 2019-02-06 01:18
CC @chinmaygarde @jason-simmons @Hixie

**Comment by Hixie** [comment] 2019-02-06 23:50
cc @jonahwilliams @dnfield 
This seems pretty critical.

**Comment by jonahwilliams** [comment] 2019-02-06 23:51
I have no particular insight into why this might be happening

**Comment by jason-simmons** [comment] 2019-02-07 01:27
I looked at the build artifact archives in cloud storage and there does seem to be something that is off by one in the upload process.

I grabbed the `android-arm/artifacts.zip` archive for engine commit `fde5900` and extracted the `libflutter.so` binary out of `flutter.jar`.
Then I ran:
`strings lib/armeabi-v7a/libflutter.so | egrep '^[0-9a-f]{9}$'`

This should find the `FLUTTER_ENGINE_VERSION` stamp that was defined during build time.  For this `libflutter.so` the stamp was `2f18c3286` (the next commit after `fde5900`)

The same thing happened for the `2f18c3286` binary - it had a stamp for `174b73c21`.

I also tried this for `ce073991` (the most recent engine commit that has an android-arm binary uploaded).  Same results - `libflutter.so` had a stamp for `6585f334a`

Does anyone have some insight into how the buildbot script checks out the source tree?  Is it possible that we're building from head instead of the intended commit?

**Comment by dnfield** [comment] 2019-02-07 01:46
Looking at the same zip for the LUCI build looks like it's good.

I'm trying to verify whether any changes I've been making to prep for the LUCI migration could have caused this.

**Comment by dnfield** [comment] 2019-02-07 01:46
compare https://storage.googleapis.com/flutter_infra/experimental/flutter/fde59006da245dc90503919ea9091b9a56d74fb2/android-arm/artifacts.zip with https://storage.googleapis.com/flutter_infra/flutter/fde59006da245dc90503919ea9091b9a56d74fb2/android-arm/artifacts.zip

**Comment by dnfield** [comment] 2019-02-07 01:58
https://uberchromegw.corp.google.com/i/client.flutter/builders/Linux%20Engine/builds/4730/steps/bot_update/logs/stdio seems fishy.  It's fetching origin/master, which is not necessarily the commit it's supposed to be building.

I didn't change this, but I did do it differently for LUCI.  I suspect we may have had this issue before and just not realized it.

I'm going to open a CL on engine.py to try to address this.  I tried to get logs from before I started working on LUCI changes and unfortunately they seem to be unavailable.  But I suspect we've had this problem for some time.

**Comment by dnfield** [comment] 2019-02-07 02:04
I'm fairly sure this was introduced by https://chromium-review.googlesource.com/c/chromium/tools/build/+/1316508 - and it's very very likely that we have lots of builds that are like this (depending on how fast the bot was in getting to build this vs. how long it took to get things migrated to the googlesource git).

That CL updated us to use revision for our upload target, but didn't update the revision we actually pull down.  Since LUCI is now getting this right, I'm confident https://chromium-review.googlesource.com/c/chromium/tools/build/+/1457483  will fix this

**Comment by dnfield** [comment] 2019-02-07 03:41
CL has been merged, this should be fixed.

Do we want a test that runs on Cirrus presubmit to verify that the engine version is the same as the hash of the zip file? Or perhaps in the tooling where we download the assets?

**Comment by liyuqian** [comment] 2019-02-07 17:32
We should be able to once https://github.com/flutter/flutter/issues/27610 is fixed.

**Comment by dnfield** [comment] 2019-02-08 18:41
Assigning this to @jonahwilliams - changes have landed in engine to put full git hash into the binary, AFAIK Jonah will be looking at getting appropriate tests in the framework for this.

**Comment by dnfield** [comment] 2019-02-13 21:40
This is blocked on the resolution of discussion at https://github.com/flutter/engine/pull/7634

**Comment by Hixie** [comment] 2019-02-20 00:13
(Copied the milestone from the dependent bug; please update if it won't be done by then.)

**Comment by liyuqian** [comment] 2019-03-22 18:29
Ping as we just got another victim https://github.com/flutter/flutter/issues/29365

**Comment by jonahwilliams** [comment] 2019-03-22 18:40
We still need something like #26380 before we can make any progress here. Alternatively, the build process could upload some engine SHAs and we could check those in the tool?

**Comment by jonahwilliams** [comment] 2019-05-20 23:43
Re-assigning to @cbracken . This is blocked by engine work, and won't be complete until higher priority items are completed

**Comment by Hixie** [comment] 2019-08-21 00:00
@tvolkert is this something someone working on infra can look at?

**Comment by digiter** [comment] 2020-04-16 22:15
Triage: what's needed from infra side?

**Comment by zanderso** [comment] 2020-04-17 16:11
Maybe @Hixie's comment here is the action item? https://github.com/flutter/flutter/issues/26380#issuecomment-461955051. /cc @dnfield 

Or could this be written as a framework-level test without infra support? /cc @jonahwilliams

**Comment by dnfield** [comment] 2020-04-17 16:19
We need the git hash stamped into the engine binary to be able to verify it.  That work was done and reverted - @hixie does not want it publically exported.  It needs to be somewhere we can consistently read.

**Comment by jonahwilliams** [comment] 2020-04-17 17:11
I don't think we necessarily need the hash in the binary, but we do need some sort of checksum of the contents, and a way to map that checksum to an engine version

**Comment by dnfield** [comment] 2020-04-17 17:29
We need some way to make sure that the hash we think we uploaded is the hash the engine thinks it is.  Maybe we could just make it something specific to flutter_tester

**Comment by jonahwilliams** [comment] 2020-04-17 17:54
I just want CIPD (I know I said I didn't, but I was wrong and you were right)

**Comment by dnfield** [comment] 2020-04-17 18:29
Cipd could help with some things but it won't help if we tag a package with the wrong version.  The root cause of this bug was the recipe uploading builds with the wrong commit in the bucket name, either building some revision earlier than head and tagging it as head or vice versa.

**Comment by dnfield** [comment] 2020-04-17 18:31
I think if we just had something like `flutter_tester --git-revision` we could assert it matched the contents of engine.version

**Comment by dnfield** [comment] 2020-04-17 18:43
Actually, `flutter_tester --help` already prints this:

```
~/src/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --help   

  flutter_tester

Versions: 

Flutter Engine Version: f5127cc07a762de774b7e941fe6eb402c97aa1b3
Skia Version: 8afde5f395088351ea43045a380e2feb55bf88ea
Dart Version: fae35fca47c9fed7a2339cf2e9535d526146ddd2

.... ( a bunch of other help on switches).
```

**Closed** 2020-04-17 23:30 UTC
Labels: engine, passed secondary triage, team, team: infra, tool, waiting for PR to land (fixed)
