### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by abolfazlirani** [flutter/flutter#159026] opened 2024-11-16 13:07 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008130-001C41E43ED0001C --start-paused --flavor=gibical --dart-define=flutter.inspector.structuredErrors=true lib/main_gibical.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-x64, locale en-AF)
    • Flutter version 3.24.4 on channel stable at /Users/abo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
    • Android SDK at /Users/abo/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • iPhone (mobile)        • 00008130-001C41E43ED0001C            • ios            • iOS 18.2 22C5109p
    • iPhone 16 Pro (mobile) • 17216990-18FE-49A0-9BE0-C3DDE26C80A8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 15.0.1 24A348 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.2+12
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
app_links-3.5.1
audio_session-0.1.21
audio_waveforms-1.1.1
camera-0.10.6
camera_android-0.10.9+11
camera_avfoundation-0.9.17+4
camera_web-0.3.5
device_info_plus-9.1.2
ffmpeg_kit_flutter_min-5.1.0
file_picker-8.1.4
file_selector_linux-0.9.3
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
firebase_analytics-11.3.5
firebase_analytics_web-0.5.10+4
firebase_auth-5.3.3
firebase_auth_web-5.13.4
firebase_core-3.8.0
firebase_core_web-2.18.1
firebase_messaging-15.1.0
firebase_messaging_web-3.9.4
flu_wake_lock-0.0.2
flutter_local_notifications-17.2.4
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.22
google_sign_in-6.2.1
google_sign_in_android-6.1.31
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+2
gtk-2.1.0
image_picker-1.1.2
image_picker_android-0.8.12+12
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
just_audio-0.9.42
just_audio_web-0.4.13
keep_screen_on-3.0.0
package_info_plus-8.1.0
path_provider-2.1.5
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.13
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
rtmp_broadcaster-2.2.6
share_plus-10.1.2
sqflite-2.3.3+1
url_launcher-6.3.1
url_launcher_android-6.3.9
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
video_player-2.9.2
video_player_android-2.7.1
video_player_avfoundation-2.6.2
video_player_web-2.3.3
video_thumbnail-0.5.3
wakelock_plus-1.2.8

**Comment by danagbemava-nc** [comment] 2024-11-18 07:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

Please check if this is fixed after following the following instructions

System Settings -> Privacy & Security -> Local Network -> [Find your IDE] -> Toggle ON, then restart your phone.

**Closed by danagbemava-nc** 2024-11-18 07:58 UTC
Labels: in triage
