### ISSUE TITLE
The physical key is pressed on a different logical key assertion failure

### ISSUE THREAD

**Issue by gregwoodio** [flutter/flutter#134657] opened 2023-09-13 14:21 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- Run the code sample from Windows 11 for web.
- Copy some text and paste it into the `TextField` using Window's clipboard (WIN+V).

### Expected results

Text should be populated in the `TextField`.

### Actual results

An assertion is failed:

```
Error: Assertion failed: file:///C:/Source/flutter/3.0.1/packages/flutter/lib/src/services/hardware_keyboard.dart:474:16
_pressedKeys[event.physicalKey] == event.logicalKey
"A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#d94da(physicalKey: PhysicalKeyboardKey#8ed21(usbHidUsage: \"0x1700000000\", debugName: \"Key with ID 0x1700000000\"), logicalKey: LogicalKeyboardKey#00076(keyId: \"0x00000076\", keyLabel: \"V\", debugName: \"Key V\"), character: null, timeStamp: 0:01:12.215699, synthesized) and the recorded logical key LogicalKeyboardKey#b7bd2(keyId: \"0x200000100\", keyLabel: \"Control Left\", debugName: \"Control Left\")"
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
packages/flutter/src/services/hardware_keyboard.dart 474:56                       <fn>
packages/flutter/src/services/hardware_keyboard.dart 481:14                       [_assertEventIsRegular]
packages/flutter/src/services/hardware_keyboard.dart 601:5                        handleKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 948:29                       handleKeyData
lib/_engine/engine/platform_dispatcher.dart 332:33                                <fn>
lib/_engine/engine/platform_dispatcher.dart 1304:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 331:7                                 invokeOnKeyData
lib/_engine/engine/keyboard_binding.dart 161:39                                   [_onKeyData]
lib/_engine/engine/keyboard_binding.dart 579:36                                   <fn>
lib/_engine/engine/keyboard_binding.dart 457:11                                   [_handleEvent]
lib/_engine/engine/keyboard_binding.dart 582:7                                    handleEvent
lib/_engine/engine/keyboard_binding.dart 98:18                                    <fn>
lib/_engine/engine/keyboard_binding.dart 140:16                                   loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

This only seems to occur on web, building for Windows and repeating the test is fine.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'TextField paste bug',
      home: Scaffold(
        body: TextField(),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2283], locale en-CA)
    • Flutter version 3.13.1 on channel stable at C:\Source\flutter\3.0.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (3 weeks ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\<user>\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio 1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio 1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code, 64-bit edition (version 1.79.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.188
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.69

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment] 2023-09-14 08:55
Hi @gregwoodio 
There is a known issue with similar steps to reproduce and `HardwareKeyboard` error: https://github.com/flutter/flutter/issues/127073. It's marked as a duplicate of https://github.com/flutter/flutter/issues/100455, so please follow up on https://github.com/flutter/flutter/issues/100455 for updates. Thank you!

**Closed by huycozy** 2023-09-14 08:55 UTC
Labels: in triage
