### ISSUE TITLE
{WEB (CanvasKit)} CanvasKit renderer never starts application. 

### ISSUE THREAD

**Issue by RMotive** [flutter/flutter#149565] opened 2024-06-03 02:00 UTC
### Steps to reproduce

Create a new template application for web platform and use CanvasKit renderer

### Expected results

Expecting the application runs x.x

### Actual results

![image](https://github.com/flutter/flutter/assets/101542646/cdf2dfec-ced7-4f4c-b498-32abd6fc350a)
As shown in the SS there the app was stucked for 5 minutes. i tried 5 times and i got the same result.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-06-03 11:06
@RMotive 
I created new flutter project targeting web platform using latest stable version with which the app compiled and run properly without getting stuck, as shown below:

<img width="1316" alt="Screenshot 2024-06-03 at 4 31 21 PM" src="https://github.com/flutter/flutter/assets/67046386/2ff9e347-484f-4012-863a-c4c2d4f0e0e8">

What flutter version are you on and can you provide the command or steps taken to create flutter app ?
Also, if you run the command in verbose mode ( -v), does it show any meaningful log that shows app stuck ?

**Comment by RMotive** [comment] 2024-06-04 06:46
@darshankawar this happens when i set the renderer as canvaskit only i tried with HTML and it worked but when i use canvaskit it got stuck.

This is where i change the renderer:
![image](https://github.com/flutter/flutter/assets/101542646/0e5e2b76-b3eb-433b-8cdf-dba61e868c18)


Flutter doctor:
![image](https://github.com/flutter/flutter/assets/101542646/f2621896-86e2-4152-a33c-d880214604a7)

And this is the CML that i used to generate the example application:

flutter create -e --platforms web canvaskit_issues.

then i tried to run it using VSCode debugger (maybe it is relevant to the diagnosis).


PD: I tried again at the moment this reply was wrote and still happening.

**Comment by robert-virkus** [comment] 2024-06-04 11:50
I hope the following helps:
Running a Flutter web app with the new bootstrap.js integration will crash when the `--web-renderer canvaskit` Parameter is given in `flutter run`.

Steps to reproduce:

1. Create a new project, e.g. `flutter create --platforms web webrenderer`
2. `cd webrenderer`
3. `flutter run --web-renderer canvaskit`

Expected result:
App is starting

Actual result:
App is crashing with the following error message:

This app is linked to the debug service: ws://127.0.0.1:64447/frDF0VtIu9g=/ws
dom.dart:195 Rejecting promise with error: TypeError: Cannot read properties of undefined (reading 'registerPlugins')
DomConsoleExtension$124warn @ dom.dart:195
[...]
didCreateEngineInitializer @ flutter_bootstrap.js:1
[...]
Function_apply @ client.js:5963
_callDartFunctionFast @ client.js:8360
(anonymous) @ client.js:8351
localhost/:1 Uncaught (in promise) null

js_primitives.dart:28 A message on the flutter/lifecycle channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html


Workaround:
Call `flutter run` without the `--web-renderer` parameter.

**Comment by darshankawar** [comment] 2024-06-04 13:19
> And this is the CML that i used to generate the example application:
> 
> flutter create -e --platforms web canvaskit_issues.
> 
> then i tried to run it using VSCode debugger (maybe it is relevant to the diagnosis).

Thanks for the report. I'll keep the issue open for team's attention / tracking.

**Comment by cgzdevelopments** [comment] 2024-06-05 22:25
Hi, I'm having the same problem with Flutter V3.22.1,  using `flutter run -d web-server --web-renderer canvaskit`.

The app compiles so it shows the normal message "press R to hot reload", but it only shows a blank screen and throws some exceptions on browser's console when I try to open it (Safari and Edge on MacOS). It was working just fine with Flutter V3.19.4.

Sorry for my bad English..

**Comment by SpencerRiddering** [comment] 2024-06-23 19:14
I'm seeing this issue in Flutter v3.22.2 on Chrome (version 126 on Linux). 

Worked on Flutter v3.19.5.

Flutter v3.22.2 works if I set `--web-renderer html`, or if I use the deprecated `FlutterLoader.loadEntrypoint` and `serviceWorkerVersion` boot strapping in my index.html.

**Comment by Miiite** [comment] 2024-06-27 16:14
I also see this with flutter `3.22.2`.
But also, you cannot set the renderer to `canvaskit` via javascript because of https://github.com/flutter/flutter/issues/147610 (which is not included in `3.22.2`), so you're kind of stuck ?

**Comment by Miiite** [comment] 2024-06-28 07:16
> I also see this with flutter `3.22.2`. But also, you cannot set the renderer to `canvaskit` via javascript because of #147610 (which seems to be fixed but is not included in `3.22.2`), so you're kind of stuck ?

The weird thing is that it seems to only affect debug builds ?
I just published a release version of my project using `flutter build web --web-renderer=canvaskit` and I don't encounter the issues described above

**Comment by eyebrowsoffire** [comment] 2024-06-28 22:13
I am able to repro. It's not 100% consistent. From my investigation I suspect this is an issue from interactions between DDC's module loading system and the loading of the CanvasKit module. The new `load` API loads the CanvasKit module in parallel with the rest of the app, and the JS produced by emscripten attempts to register itself with requireJS, which is what DDC uses for its module loading system, and I suspect they are conflicting. This would explain why:

* This only happens in debug builds (DDC)
* This doesn't happen with the html renderer (no CanvasKit registration happening at all)
* This only happens when using the new `load` API (when using the old `loadEntrypoint` API, CanvasKit is not loaded until DDC is fully initialized)

I have a PR that changes CanvasKit over to be loaded as an ES6 module (which doesn't do anything with requireJS) which I suspect will resolve thie: https://github.com/flutter/engine/pull/52023

**Comment by eyebrowsoffire** [comment] 2024-07-01 21:42
The ES6 modules change landed in the engine, and I have been testing locally against it, and the issue is no longer reproducible now, so it appears to be fixed. The change should roll into the framework soon.

**Comment by eyebrowsoffire** [comment] 2024-07-02 16:14
The changed cause some other regressions and had to be reverted. I'm fixing those regressions and am looking at relanding the changes today.

**Comment by eyebrowsoffire** [comment] 2024-07-11 16:52
After some false starts landing the fix, we did finally get it in and this issue is fixed on the master channel.

**Closed by eyebrowsoffire** 2024-07-11 16:52 UTC
Labels: engine, platform-web, e: web_canvaskit, P1, e: wasm, e: web_skwasm, team-web, triaged-web
