### ISSUE TITLE
[web]: try to copy paste some text in Line Messenger Browser 

### ISSUE THREAD

**Issue by echomartha** [flutter/flutter#68087] opened 2020-10-14 07:37 UTC
![image](https://user-images.githubusercontent.com/71472725/95957836-d2a34080-0e32-11eb-85d5-f26b40024a05.png)

i can not paste text after copy text at my flutter web project

**Comment by pedromassangocode** [comment] 2020-10-14 10:10
Hi @echomartha 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by echomartha** [comment] 2020-10-15 02:22
hello @pedromassangocode  ths is my flutter doctor -v
![image](https://user-images.githubusercontent.com/71472725/96068903-a8ec2700-0ecf-11eb-8ad6-c9004d1dbab3.png)

and this is my code, lib i use  : https://pub.dev/packages/clipboard  
![image](https://user-images.githubusercontent.com/71472725/96068983-d507a800-0ecf-11eb-88a7-3feb6d001ca2.png)


already try with Clipboard Clipboard.setData(new ClipboardData(text: _copy)); but same result

**Comment by echomartha** [comment] 2020-10-15 04:52
@pedromassangocode , this the new  code i tryng to
`clipBoard(String url) async {
    await Clipboard.setData(ClipboardData(text: url))
        .then(
          (dynamic result) => Scaffold.of(context).showSnackBar(
            SnackBar(content: Text('Success')),
          ),
        )
        .catchError(
          (Object error) => Scaffold.of(context).showSnackBar(
            SnackBar(content: Text('Error $error')),
          ),
        );
  }`


the result
![image](https://user-images.githubusercontent.com/71472725/96078568-456cf400-0ee5-11eb-8289-143ad1af4f99.png)

**Comment by pedromassangocode** [comment] 2020-10-15 06:28
Hi @echomartha 
I need you to provide a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample by copy/paste it her in the comments and not as image so I can copy then and try to reproduce the issue you are having.

Please note that your code should not use a third-party plugin for this. 
If you keep using https://pub.dev/packages/clipboard then I suggest you to close this issue and create a new one in the repository of that plugin https://github.com/samuelezedi/flutter_clipboard.

**Comment by pedromassangocode** [comment] 2020-10-15 07:06
Can you please elaborate "when i try in Line messenger Browser it cant"?
Does it shows you an error in the console?

**Comment by echomartha** [comment] 2020-10-15 07:07
@pedromassangocode 

![image](https://user-images.githubusercontent.com/71472725/96088557-2e83cd00-0ef8-11eb-95d0-728a65ed883f.png)

**Comment by pedromassangocode** [comment] 2020-10-15 07:10
Please run your project with `flutter run -v` and try to reproduce the issue and then provide the output here.
If it is too long you can share it as a `.txt` file.

**Comment by echomartha** [comment] 2020-10-15 07:13
[Uploading result.txt…]()

**Comment by pedromassangocode** [comment] 2020-10-15 11:25
Hi @KernCheh 
Can you please share provide what I asked in https://github.com/flutter/flutter/issues/68087#issuecomment-708947441 as well?

Thanks

**Comment by echomartha** [comment] 2020-10-16 02:13
hi @pedromassangocode 
this is the issue i;ve got after deploy my project
![image](https://user-images.githubusercontent.com/71472725/96204759-aa812200-0f97-11eb-93e0-96c25ea24bda.png)



the expected result : 
![image](https://user-images.githubusercontent.com/71472725/96204917-09df3200-0f98-11eb-9ec8-f03a51acf273.png)

**Comment by echomartha** [comment] 2020-10-16 07:44
@pedromassangocode this my code

```
 clipBoard(String url) async {
    await Clipboard.setData(ClipboardData(text: url))
        .timeout(Duration(seconds: 2))
        .then(
          (dynamic result) => Scaffold.of(context).showSnackBar(
            SnackBar(content: Text('Success')),
          ),
        )
        .catchError(
          (Object error) => Scaffold.of(context).showSnackBar(
            SnackBar(content: Text('Error $error')),
          ),
        );
  }
```

**Comment by pedromassangocode** [comment] 2020-10-16 12:42
Hi @echomartha 
Sorry but I'm not understanding what is the real issue here.

You are saying that you cannot paste text into Line Messenger Browser but you are showing a UI with SnackBar build with Flutter.

I tried copy text from Flutter app and then pasting it into safari and it worked. I fear that Flutter does not have support for the Browser you are using. But since this is still not clear to me I'm not sure what the issue really is.

Does the code bellow reproduces the issue? 
If it does not reproduce then share a complete sample code that reproduces the issue.

Please share a clear steps by step in how to reproduce the issue. 
Unless you explain the issue right I will not be able to understand and reproduce it.

<details><summary>Code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FAB(),
    );
  }
}

class FAB extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FloatingActionButton.extended(
      label: Text('Copy \'FlutterX\' to Clipboard'),
      icon: Icon(Icons.add),
      onPressed: () async {
        await Clipboard.setData(ClipboardData(text: 'FlutterX'))
            .timeout(Duration(seconds: 2))
            .then(
              (dynamic result) =>
              Scaffold.of(context)?.showSnackBar(
                SnackBar(content: Text('Success')),
              ),
        )
            .catchError(
              (Object error) =>
              Scaffold.of(context)?.showSnackBar(
                SnackBar(content: Text('Error $error')),
              ),
        );
      },
    );
  }
}

```
</details>

**Comment by echomartha** [comment] 2020-10-16 12:50
helloo @pedromassangocode 

so my problem is when i try in local host it can copy paste like normaly but when i deploy my project, and i testing in mobile safari and line messeger browser it cant showing toast success

**Comment by pedromassangocode** [comment] 2020-10-16 14:14
Thanks for making it clear.
Can you confirm if the issue also happens when you try on Safari as well?

Noticed you are using an old version of Flutter. Can you please update Flutter and try again?
The latest stable is `1.22` and you can update by running:
`flutter channel stable`
`flutter upgrade --force`

If the issue persist please provide your `flutter doctor -v`.
Thank you

**Comment by echomartha** [comment] 2020-10-16 15:14
hello @pedromassangocode  sorry for my unclear question 
already ```flutter upgrade``` and ```No ussyes found!``` 

this is the new error 
![image](https://user-images.githubusercontent.com/71472725/96276235-4b59f680-1005-11eb-901e-43a5cc52cd83.png)

**Comment by pedromassangocode** [comment] 2020-10-19 06:46
Hi @echomartha 
Thanks for the update.
This is not an error, you defined a timeout for the seData method to last and since it is taking more than the expected it is showing you this message. You can simply await the future to complete without setting a timeout!


Given your latest message, I feel safe to close this issue. If you disagree, write in the comments bellow and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-10-19 06:46 UTC
Labels: in triage

**Comment by echomartha** [comment] 2020-10-19 07:10
@pedromassangocode oke thanks for your help
