### ISSUE TITLE
Text field cursor position in RTL goes to the penultimate character - still exists in flutter 3.7.0

### ISSUE THREAD

**Issue by easazade** [flutter/flutter#121164] opened 2023-02-21 19:55 UTC
When the user writes then taps at the end of a text field in RTL app the cursor position is set to the penultimate character instead of the last one. This issue occurs on both Android (tested on multiple devices from different vendors and emulator) and iOS.

Steps to Reproduce
Execute flutter run on the code sample
Write Arabic or any other RTL language in the text field.
Tap on any place to change the cursor position then tap again at the end of the text field, the cursor position will change to the penultimate character.
Expected results:
The cursor position should be after the last character.

Actual results:
The cursor position moves to the penultimate character.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      locale: const Locale("ar"),
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [Locale("ar")],
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: Padding(
          padding: EdgeInsets.all(16),
          child: TextField(),
        ),
      ),
    );
  }
}
```

<img src="https://user-images.githubusercontent.com/18516358/177010397-a05822f1-8989-4fc9-8f0c-d7541125d25c.gif" width="260">

here is the [link](https://github.com/flutter/flutter/issues/107006) to the original issue

**Comment by easazade** [comment] 2023-02-21 19:57
```
fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.2 22D49 darwin-arm64, locale en-IR)
    • Flutter version 3.7.0 on channel stable at /Users/alireza/fvm/versions/3.7.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 weeks ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/alireza/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 62.0.2
    • Dart plugin version 211.7798

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1
    ! NO_PROXY does not contain localhost
    • NO_PROXY contains 127.0.0.1
    ! NO_PROXY does not contain ::1

[✓] Connected device (3 available)
    • M2102J20SG (mobile) • d4fc1ae • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos   • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)        • chrome  • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment] 2023-02-22 08:49
@easazade 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/118566 and per [this](https://github.com/flutter/flutter/issues/118566#issuecomment-1412314895) comment, it seems to be fixed on latest master, so please run your scenario on latest master and see if the issue is fixed or not. Accordingly you can share your findings in the linked issue.

Closing this as a duplicate.

**Closed by darshankawar** 2023-02-22 08:49 UTC
Labels: in triage
