### ISSUE TITLE
[Web] add "dart:io" "Platform" support for web

### ISSUE THREAD

**Issue by ZhangDubhe** [flutter/flutter#47416] opened 2019-12-19 06:10 UTC
Platform is not supportable in beta branch when run in web
 (platform.dart)

such as `Normal error => message: Unsupported operation: Platform._operatingSystem`
and so on.

Flutter 1.12.13+hotfix.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 18cd7a3601 (8 days ago) • 2019-12-11 06:35:39 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by iapicca** [comment] 2019-12-19 14:28
Hi @ZhangDubhe 
can you please describe the issue more in details,
in what condition you are getting this error?

Can you please provide your `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by ZhangDubhe** [comment] 2019-12-20 07:38
![image](https://user-images.githubusercontent.com/15643994/71238334-ce0b1a00-233e-11ea-8895-55a17d4702cf.png)


**git** [Test demo here (click me)](https://github.com/ZhangDubhe/flutter_bug_demo)

`https://github.com/ZhangDubhe/flutter_bug_demo.git`

**Comment by ZhangDubhe** [comment] 2019-12-20 07:43
```bash
[  +27 ms] executing: [/Users/dubhe/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
[        ] executing: [/Users/dubhe/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +218 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +5 ms] v1.12.13+hotfix.6-0-g18cd7a3601
[  +11 ms] executing: [/Users/dubhe/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/dubhe/development/flutter/] git ls-remote --get-url origin
[  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +65 ms] executing: [/Users/dubhe/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +9 ms] executing: sw_vers -productName
[  +26 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +26 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.1
[        ] executing: sw_vers -buildVersion
[  +24 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19B88
[  +42 ms] executing: /usr/bin/xcode-select --print-path
[  +12 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +4 ms] executing: /usr/bin/xcodebuild -version
[+1228 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3
           Build version 11C29
[  +62 ms] executing: /Users/dubhe/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/dubhe/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +21 ms] executing: /Users/dubhe/development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +63 ms] /usr/bin/xcrun simctl list --json devices
[ +134 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all
devices.
[  +70 ms] Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +10 ms] "flutter run" took 1,760ms.
```



Here is log of `flutter run --verbose`  

@iapicca

**Comment by iapicca** [comment] 2019-12-20 11:24
Hi @ZhangDubhe 
my apologize, I've overlooked this information
https://flutter.dev/docs/development/platform-integration/web#does-platformis-work-on-the-web
I believe we can address the issue as a feature request
thank you

**Comment by ZhangDubhe** [comment] 2019-12-21 11:20
thx~

**Comment by ccastro11** [comment] 2019-12-23 06:59
> thx~

Bud, you can use this...
if (kIsWeb) {
}

KIsWeb is a method from fundation package

import 'package:flutter/foundation.dart';

it use "identical" a method for compare data. JavaScript only has one type of numbre data, double and int are the same but in dart doesn't the same.

JS: 0 == 0.0 // true
Dart 0 == 0.0 // false

**Comment by muhleder** [comment] 2019-12-31 09:16
This package can be used as a workaround in the meantime https://pub.dev/packages/universal_io

**Comment by yjbanov** [comment] 2020-01-03 22:23
This is a duplicate of https://github.com/flutter/flutter/issues/39998

**Closed by yjbanov** 2020-01-03 22:23 UTC
Labels: dependency: dart, proposal, severe: new feature, ☸ platform-web
