### ISSUE TITLE
Unexpected behavior of --release flag for flutter run

### ISSUE THREAD

**Issue by biocarl** [flutter/flutter#28142] opened 2019-02-19 13:53 UTC
## Steps to Reproduce

I use a `CustomPainter` to draw `Path` objects to a `Canvas` which works all fine with `flutter run --release` (**A**), but with `flutter build apk; flutter install` (**B**) the rendering doesn't behave as expected.

**Is that a desired behavior that both apk's behave differently? I thought the `--release` flag denotes the final apk which can be published to the store.**

- **A**. Run in `release` mode (on physical device)
```bash
flutter run --release
```

![alt](https://raw.githubusercontent.com/biocarl/img/master/debug/release_mode.gif)

- **B**. Build and install

When I build the apk and then install it on the same physical device I get the following output 

```bash
flutter build apk
flutter install
```

![alt](https://raw.githubusercontent.com/biocarl/img/master/debug/installed_apk.gif)

***What is happening here?**
Has the render difference to do with anti-aliasing or lost pointers or blend mode? 
I'm not very familiar with lower-level computer graphics.*

## Logs

For `flutter run --release` there are no additional log outputs when starting the animation. For `flutter build apk; flutter install` I used `adb logcat` to see if some exception is thrown but nothing there.
`flutter analyze` on both the example and the package doesn't find any issues.

 `flutter doctor -v`

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.2-pre.21 at /home/carl/lib/flutter
    • Framework revision 035e0765cc (3 days ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/carl/lib/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/carl/lib/Android/sdk
    • Java binary at: /opt/google/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/google/android-studio
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected device (1 available)
    • PRA LX1 • --------- • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```
## Source code
https://github.com/biocarl/drawing_animation/tree/master/example/example_03

**Comment by zoechi** [comment] 2019-02-19 14:34
So the main difference I saw was that in (**B**) the nose disappears at the end while in (**A**) it stays visible.

**Comment by zoechi** [comment] 2019-02-19 14:35
Can you reproduce this also with `stable` or `dev` channel or only with `master`?

**Comment by biocarl** [comment] 2019-02-19 15:15
Release mode [A]            |  Installed apk [B]
:-------------------------:|:-------------------------:
![release_mode](https://user-images.githubusercontent.com/12430709/53024396-b96ba600-343d-11e9-8c66-d2451e48982f.jpg) | ![installed_apk](https://user-images.githubusercontent.com/12430709/53024320-8b866180-343d-11e9-90ee-c78b4111d236.jpg)

Here a screenshot with higher resolution. In the lower bottom of [B] I can also see a repeating element from the "Fig. VI." .

@zoechi I ran [B] on both branches. On `stable` it is working as expected (as [A])! On `dev` occurs the same behavior as on `master`.

**Comment by jason-simmons** [comment] 2019-02-20 02:34
One potential difference between `flutter run` and `flutter build apk` is the target platform of the resulting APK.

`flutter run` will choose the target platform matching the attached device, whereas `flutter build apk` will default to 32-bit ARM.  The `flutter doctor` log above says that your device is an arm64 device, so `flutter run` would target arm64.

Try using `flutter build apk --target-platform=android-arm64` to build an arm64 APK.

You can also investigate differences between the APKs by unzipping the APK files output by each command.

**Comment by biocarl** [comment] 2019-02-20 13:32
@jason-simmons You are right, for `flutter build apk --target-platform=android-arm64` the rendering behaves as in [A].

I did as proposed (on `master` channel):
**`$diff --brief -r 32_bit.apk_FILES/ 64_bit.apk_FILES/`**
```
Files 32_bit.apk_FILES/assets/isolate_snapshot_data and 64_bit.apk_FILES/assets/isolate_snapshot_data differ
Files 32_bit.apk_FILES/assets/isolate_snapshot_instr and 64_bit.apk_FILES/assets/isolate_snapshot_instr differ
Files 32_bit.apk_FILES/assets/vm_snapshot_data and 64_bit.apk_FILES/assets/vm_snapshot_data differ
Files 32_bit.apk_FILES/assets/vm_snapshot_instr and 64_bit.apk_FILES/assets/vm_snapshot_instr differ
Only in 64_bit.apk_FILES/lib: arm64-v8a
Only in 32_bit.apk_FILES/lib: armeabi-v7a
Files 32_bit.apk_FILES/META-INF/CERT.RSA and 64_bit.apk_FILES/META-INF/CERT.RSA differ
Files 32_bit.apk_FILES/META-INF/CERT.SF and 64_bit.apk_FILES/META-INF/CERT.SF differ
Files 32_bit.apk_FILES/META-INF/MANIFEST.MF and 64_bit.apk_FILES/META-INF/MANIFEST.MF differ
```
Do you want some diffs from a specific file?

**Comment by jason-simmons** [comment] 2019-02-20 17:58
It looks like everything is working as expected.  The difference in behavior was due to 32-bit versus 64-bit builds.

**Comment by korgara** [comment] 2019-03-27 14:18
@jason-simmons thanks for your explanation
I was wondering if building to arm64 might caused some another errors or crashes on different devices?

**Comment by jonahwilliams** [comment] 2019-04-23 01:30
It sounds like this issue can be closed then? cc @jason-simmons

**Comment by cbracken** [comment] 2019-04-29 18:27
Closing for now. Please let us know if you're still seeing this on `master` branch and we'll re-open.

**Closed by cbracken** 2019-04-29 18:27 UTC
Labels: engine, severe: regression, tool
