### ISSUE TITLE
 camera/CameraPlugin.h' file not found

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#32910] opened 2019-05-17 18:15 UTC
Here is the thing:

* My Project runs **FINE** through X-Code, it means I got no errors while running the project from the Xcode's Run Project button. It compiles and runs fine on the device, but without the Hot Reload feature (obviously).
* When trying to run it on `Intellij`, I get this error:

```
=== BUILD TARGET Runner OF PROJECT Runner WITH THE DEFAULT CONFIGURATION (Debug) ===
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'camera/CameraPlugin.h' file not found
    #import <camera/CameraPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the precompiled application for the device.

Error launching application on iPhone de Gabriel.
```

The projects uses a lot of Plugins, some I wrote myself.
Again: It runs FINE through X-Code!!

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
[✓] Connected device (1 available)

```

EDIT: This issue is the same with flutter 1.7.8.

**Comment by Goolpe** [comment] 2019-05-18 06:30
Looks like a duplicate of
https://github.com/flutter/flutter/issues/15050
https://github.com/flutter/flutter/issues/9694

> Removing use_frameworks! from ios/Podfile. Then running a pod update, might resolve it

**Comment by meJevin** [comment] 2019-08-21 22:19
Anybody? This is still an issue

**Comment by shinayser** [comment] 2019-09-10 19:19
Updated to flutter 1.9 stable and still can't compile outside xcode.

The errors seem to changed a bit:

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/speech_recognition-0.3.0+1/ios/Classes/SpeechRecognitionPlugin.m:6:4: warning: 'SwiftSpeechRecognitionPlugin' is only available on iOS 10.0 or newer [-Wunguarded-availability]
      [SwiftSpeechRecognitionPlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/speech_recognition-0.3.0+1/ios/Classes/SpeechRecognitionPlugin.m:2:
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/build/ios/Release-iphoneos/speech_recognition/speech_recognition.framework/Headers/speech_recognition-Swift.h:194:12: note: 'SwiftSpeechRecognitionPlugin' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
    @interface SwiftSpeechRecognitionPlugin : NSObject <FlutterPlugin, SFSpeechRecognizerDelegate>
               ^
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/speech_recognition-0.3.0+1/ios/Classes/SpeechRecognitionPlugin.m:6:4: note: enclose 'SwiftSpeechRecognitionPlugin' in an @available check to silence this warning
      [SwiftSpeechRecognitionPlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:35:11: warning: variable 'originRect' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
          if (originX != nil && originY != nil && originWidth != nil && originHeight != nil) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:43:26: note: uninitialized use occurs here
                    atSource:originRect];
                             ^~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:35:7: note: remove the 'if' if its condition is always true
          if (originX != nil && originY != nil && originWidth != nil && originHeight != nil) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:35:11: warning: variable 'originRect' is used uninitialized whenever '&&' condition is false [-Wsometimes-uninitialized]
          if (originX != nil && originY != nil && originWidth != nil && originHeight != nil) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:43:26: note: uninitialized use occurs here
                    atSource:originRect];
                             ^~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:35:11: note: remove the '&&' if its condition is always true
          if (originX != nil && originY != nil && originWidth != nil && originHeight != nil) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:35:11: warning: variable 'originRect' is used uninitialized whenever '&&' condition is false [-Wsometimes-uninitialized]
          if (originX != nil && originY != nil && originWidth != nil && originHeight != nil) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:43:26: note: uninitialized use occurs here
                    atSource:originRect];
                             ^~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:35:11: note: remove the '&&' if its condition is always true
          if (originX != nil && originY != nil && originWidth != nil && originHeight != nil) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:35:11: warning: variable 'originRect' is used uninitialized whenever '&&' condition is false [-Wsometimes-uninitialized]
          if (originX != nil && originY != nil && originWidth != nil && originHeight != nil) {
              ^~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:43:26: note: uninitialized use occurs here
                    atSource:originRect];
                             ^~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:35:11: note: remove the '&&' if its condition is always true
          if (originX != nil && originY != nil && originWidth != nil && originHeight != nil) {
              ^~~~~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.2+1/ios/Classes/SharePlugin.m:34:7: note: variable 'originRect' is declared here
          CGRect originRect;
          ^
    4 warnings generated.
    In file included from /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/NSValueTransformer+MTLPredefinedTransformerAdditions.m:10:
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/MTLJSONAdapter.h:223:27: warning: '@endcode' command does not terminate a verbatim text block [-Wdocumentation]
    /// If `objCType` matches @encode(id), the value transformer returned by
                              ^~~~~~~
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/MTLJSONAdapter.h:226:65: warning: '@endcode' command does not terminate a verbatim text block [-Wdocumentation]
    /// The default implementation transforms properties that match @encode(BOOL)
                                                                    ^~~~~~~
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/MTLJSONAdapter.h:230:47: warning: '@endcode' command does not terminate a verbatim text block [-Wdocumentation]
    ///            as it would be returned by the @encode() directive.
                                                  ^~~~~~~
    3 warnings generated.
    In file included from /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/NSDictionary+MTLJSONKeyPath.m:11:
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/MTLJSONAdapter.h:223:27: warning: '@endcode' command does not terminate a verbatim text block [-Wdocumentation]
    /// If `objCType` matches @encode(id), the value transformer returned by
                              ^~~~~~~
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/MTLJSONAdapter.h:226:65: warning: '@endcode' command does not terminate a verbatim text block [-Wdocumentation]
    /// The default implementation transforms properties that match @encode(BOOL)
                                                                    ^~~~~~~
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/MTLJSONAdapter.h:230:47: warning: '@endcode' command does not terminate a verbatim text block [-Wdocumentation]
    ///            as it would be returned by the @encode() directive.
                                                  ^~~~~~~
    3 warnings generated.
    In file included from /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/MTLModel.m:12:
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/extobjc/EXTScope.h:91:35: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    typedef void (^mtl_cleanupBlock_t)();
                                      ^
                                       void
    1 warning generated.
    In file included from /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/MTLModel+NSCoding.m:11:
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/extobjc/EXTScope.h:91:35: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    typedef void (^mtl_cleanupBlock_t)();
                                      ^
                                       void
    1 warning generated.
    4 warnings generated.
    In file included from /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/extobjc/EXTScope.m:10:
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Pods/Mantle/Mantle/extobjc/EXTScope.h:91:35: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    typedef void (^mtl_cleanupBlock_t)();
                                      ^
                                       void
    1 warning generated.
    12 warnings generated.
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataTIFF.m:35:65: warning: 'kCGImagePropertyTIFFTileWidth' is only available on iOS 9.0 or newer [-Wunguarded-availability]
                 SYStringSel(tileWidth):                (NSString *)kCGImagePropertyTIFFTileWidth,
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'ImageIO' imported from /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataTIFF.m:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/ImageIO.framework/Headers/CGImageProperties.h:146:34: note: 'kCGImagePropertyTIFFTileWidth' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    IMAGEIO_EXTERN const CFStringRef kCGImagePropertyTIFFTileWidth  IMAGEIO_AVAILABLE_STARTING(10.11, 9.0);
                                     ^
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataTIFF.m:35:65: note: enclose 'kCGImagePropertyTIFFTileWidth' in an @available check to silence this warning
                 SYStringSel(tileWidth):                (NSString *)kCGImagePropertyTIFFTileWidth,
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataTIFF.m:36:65: warning: 'kCGImagePropertyTIFFTileLength' is only available on iOS 9.0 or newer [-Wunguarded-availability]
                 SYStringSel(tileLength):               (NSString *)kCGImagePropertyTIFFTileLength,
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'ImageIO' imported from /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataTIFF.m:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/ImageIO.framework/Headers/CGImageProperties.h:147:34: note: 'kCGImagePropertyTIFFTileLength' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    IMAGEIO_EXTERN const CFStringRef kCGImagePropertyTIFFTileLength  IMAGEIO_AVAILABLE_STARTING(10.11, 9.0);
                                     ^
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataTIFF.m:36:65: note: enclose 'kCGImagePropertyTIFFTileLength' in an @available check to silence this warning
                 SYStringSel(tileLength):               (NSString *)kCGImagePropertyTIFFTileLength,
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataPNG.m:32:61: warning: 'kCGImagePropertyPNGCompressionFilter' is only available on iOS 9.0 or newer [-Wunguarded-availability]
                 SYStringSel(compressionFilter):    (NSString *)kCGImagePropertyPNGCompressionFilter,
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'ImageIO' imported from /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataPNG.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/ImageIO.framework/Headers/CGImageProperties.h:743:34: note: 'kCGImagePropertyPNGCompressionFilter' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    IMAGEIO_EXTERN const CFStringRef kCGImagePropertyPNGCompressionFilter IMAGEIO_AVAILABLE_STARTING(10.11, 9.0);
                                     ^
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataPNG.m:32:61: note: enclose 'kCGImagePropertyPNGCompressionFilter' in an @available check to silence this warning
                 SYStringSel(compressionFilter):    (NSString *)kCGImagePropertyPNGCompressionFilter,
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/danieloliveira/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/ios/Classes/SYPictureMetadata/SYMetadataExif.m:9:9: warning: non-portable path to file '"SYMetadataExif.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
    #import "SYMetadataEXIF.h"
            ^~~~~~~~~~~~~~~~~~
            "SYMetadataExif.h"
    1 warning generated.
    /Users/danieloliveira/Documents/flutter_projects/mydenox_flutter/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'device_info/DeviceInfoPlugin.h' file not found
    #import <device_info/DeviceInfoPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description
```

**Comment by ollydixon** [comment] 2019-09-23 15:17
I'm getting tons of compiler issues across my projects with Flutter 1.9.1 :-|

**Comment by ollydixon** [comment] 2019-09-23 18:34
`camera: ^0.5.4+2` have the same error. Removing `use_frameworks!` gets further but just errors as well. Using Xcode 11.

Tried using a fresh project as well, same errors.

4 of our projects are now stuck. We've no idea what to do. Fairly critical that the camera package is not working for iOS release don't you think?

**Comment by GerGodfrey** [comment] 2019-09-26 20:25
i´ve the same problem 😫

**Comment by jaweii** [comment] 2019-10-12 11:35
same here

**Comment by blaqkrow** [comment] 2019-10-21 09:50
@ollydixon @jaweii @GerGodfrey have you solved the issue? are you running them on devices with iOS 13?

**Comment by ollydixon** [comment] 2019-10-21 09:54
@blaqkrow I had to update to MacOS 10.15.

**Comment by blaqkrow** [comment] 2019-10-21 13:34
> @blaqkrow I had to update to MacOS 10.15.

@ollydixon thanks for the fast reply! I am also on MacOS 10.15 and the problem still persists... I am using xcode v11.1 and i just updated my iphone to iOS 13.1.3. Was there any additional settings you tried?

**Comment by ollydixon** [comment] 2019-10-21 13:38
@blaqkrow no idea, it just seemed to resolve itself when updating to MacOS 15.10 and Flutter 1.9.1+hotfix.4

**Comment by blaqkrow** [comment] 2019-10-21 13:50
@ollydixon sorry one last thing, may i know your pubspec.yaml configurations for camera? mine is camer^0.5.6+1

**Comment by ollydixon** [comment] 2019-10-21 13:53
@blaqkrow `camera: ^0.5.4+2`

**Comment by blaqkrow** [comment] 2019-10-21 13:56
Thank you! Yes mine works now!

**Comment by ghunkins** [comment] 2019-10-30 00:14
I had this issue as well. Turns out my `Podfile` and `Podfile.lock` were somehow not generated correctly. I fixed by removing both and re-generating them using `flutter build ios`.

```
rm Podfile Podfile.lock
flutter build ios
```

After this, my build went through successfully.

**Comment by hagen00** [comment] 2019-11-05 07:06
Same problem here. I've tried every workaround mentioned here, as well as elsewhere.

**Comment by VNAPNIC** [comment] 2019-11-06 03:36
> If anyone is struggling with this, make sure you're opening the .xcworkspace file instead of the .xcodeproject one. I experienced this problem with the latter, not the former.

I sure opened the .xcworkspace file but it still error

**Comment by jmagman** [comment] 2019-11-14 22:53
I just created a new Objective-C Flutter project in IntelliJ on v1.7.8+hotfix.4 (with https://github.com/flutter/flutter/pull/41491 cherry-picked to get past the CocoaPods check since I'm running 1.8.4) and added `camera: ^0.5.6+1`.  I didn't see this import error.

If anyone is still seeing this, a reproducible project will probably be critical to make this actionable.

It also may be fixed on [Flutter v1.10.15 or later](https://github.com/flutter/flutter/pull/42204/files#diff-fb912d7008f6a340a5c4584a6ee1ae85R477) and [camera 0.5.5](https://github.com/flutter/plugins/pull/2115).

**Comment by Hixie** [comment] 2019-12-18 00:35
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by shinayser** [comment] 2019-12-18 14:30
It's been a year. And I still can't run my project on mac OS. Flutter 1.12 didin't fix any of this 😥

**Comment by jmagman** [comment] 2019-12-18 20:37
@shinayser 

> If anyone is still seeing this, a reproducible project will probably be critical to make this actionable.

**Comment by dnfield** [comment] 2020-01-16 00:46
I'm closing this since it's had no activity for > 21 days and has the waiting label.  I believe the bot is just backlogged and missing a bunch of these.  Please feel free to add more details if you want this re-opened.

**Closed by dnfield** 2020-01-16 00:46 UTC
Labels: p: camera, t: xcode, tool, waiting for customer response, ⌺‬ platform-ios

**Comment by ollydixon** [comment] 2020-02-09 03:47
This issue has resurfaced using Flutter ```v1.12.13+hotfix.7```

**Comment by dnfield** [comment] 2020-02-09 04:03
Can you provide a project that reproduces this?

**Comment by ollydixon** [comment] 2020-02-09 04:08
Standard Flutter project with the camera plugin, version ```camera: ^0.5.7+3```. It's only this dam plugin I keep having issues with, I have more than 50+ other plugins that have no issue at all.

I'm trying to debug on device. Seems to work on emulator.

Looks the same as this bug https://github.com/flutter/flutter/issues/43986

**Comment by ollydixon** [comment] 2020-02-09 04:16
@dnfield found a solution. 

Inside the Podfile I updated to ``platform :ios, '12.0'``
Upgraded both project and runner for Xcode project to 12.0
```Flutter clean```

**Comment by praveenbbhati** [comment] 2020-02-13 13:30
Xcode version : 11.3.1
Flutter: v1.12.13+hotfix.8
Target: 12.0
camera: ^0.5.7+3

@ollydixon  I'm still getting **module 'camera' not found.** any fix on this?

**Comment by ollydixon** [comment] 2020-02-13 14:30
@praveenbbhati sorry you're setting are the same as mine. You uncommented the Podfile right?

**Comment by praveenbbhati** [comment] 2020-02-14 12:06
@ollydixon this is my Podfile.
`# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  pod 'Firebase/Analytics'

end
`
is this correct?

**Comment by praveenbbhati** [comment] 2020-02-14 12:15
@ollydixon this is my Podfile.
![Screenshot 2020-02-14 at 5 45 01 PM](https://user-images.githubusercontent.com/10512037/74531096-bbcde680-4f51-11ea-9ec6-af68a2a4d1ed.png)

is this correct?

**Comment by 10it-lk** [comment] 2020-02-28 06:03
for me camera: ^0.5.4+2 worked with platform :ios, '10.0' only

**Comment by majirosstefan** [comment] 2021-02-14 13:41
still not fixed

**Comment by jmagman** [comment] 2021-02-16 20:23
@majirosstefan Can you file a new issue since you're not seeing it from the command line, only from Xcode?  Please include a full `flutter build --verbose` log where it's working, and an exported Xcode build logs where it's not working so we can see the linker flags.
<img width="1072" alt="Screen Shot 2021-02-16 at 11 17 03 AM" src="https://user-images.githubusercontent.com/682784/108110748-9124db00-7048-11eb-9a28-7c2cc4e8de2f.png">

> I am not sure, how I will build archive for Appstore Connect / Testflight without using Xcode

If you're able to upgrade to the dev or beta channel you can try the `flutter build ipa` command. https://flutter.dev/docs/deployment/ios#create-a-build-archive

**Comment by rchtgpt** [comment] 2021-02-17 13:28
still facing this issue.

**Comment by jmagman** [comment] 2021-02-17 18:33
@rchtgpt 

> If anyone is still seeing this, a reproducible project will probably be critical to make this actionable.

**Comment by kunanfo** [comment] 2021-02-27 16:35
Oh my god, after I comment the 'use_frameworks!' in Podfile, finally It works.

**Comment by ismdcf** [comment] 2021-04-14 17:08
Still experiencing this. Any Idea what should be done. in debug version it builds but when changing the release version it fails
