### ISSUE TITLE
Possible chance for system to kill the active app when in low memory

### ISSUE THREAD

**Issue by nsreenath** [flutter/flutter#15357] opened 2018-03-09 23:16 UTC
## Steps to Reproduce

Tested on Moto G4 Plus, Android 7.0
Turn on GPU profiling with on screen bars as shown below:

![screen2 custom](https://user-images.githubusercontent.com/3154529/37234335-276d8eb6-241d-11e8-8426-ea55b6965940.png)

Then open any app created using Flutter.
GPU usage is not detected, as shown in below video:
Note: The issue is there even if screen recording is off.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3154529/37234261-c0bae7cc-241c-11e8-8cd8-d89a6b71e3e0.gif)

## Problem
In this case, the system is unable to detect GPU usage of the app. So is it possible that the low memory killer will also be unable to detect that the app is rendering to screen and hence will kill the active app mistaking it to be in the background ?

**Comment by Hixie** [comment] 2018-06-08 20:02
cc @chinmaygarde

**Comment by chinmaygarde** [comment] 2018-06-08 21:01
I don't think the background status of an application is based solely on the use of the Android rendering machinery (instead of rendering directly via OpenGL like Flutter does). If that were true, Android would be treating all games as working in the background.

Are you finding specific instance of the system killing your application because it thought it was in the background? If so, logs and steps to reproduce would be great.

**Comment by nsreenath** [comment] 2018-06-18 15:18
@chinmaygarde I saw a `lowmemorykiller` process in the logs mentioned in this issue:
https://github.com/flutter/flutter/issues/15156
I don't know what the log says.

**Comment by kf6gpe** [comment] 2020-01-07 22:05
Closing due to lack of logs and reproducible steps. Feel free to reopen if someone can provide these.

**Closed by kf6gpe** 2020-01-07 22:05 UTC
Labels: engine
