### ISSUE TITLE
`No named parameter with the name 'window'` in package `printing`

### ISSUE THREAD

**Issue by gopiKrishnaPuligundla** [flutter/flutter#126749] opened 2023-05-13 17:23 UTC
macOS (desktop) • macos • darwin-x64 • macOS 13.3.1 22E261 darwin-x64

No wireless devices were found.

[1]: macOS (macos)
Please choose one (or "q" to quit): 1

Launching lib/main.dart on macOS in debug mode...
Running pod install...                                           1,153ms
2023-05-13 22:44:33.812 xcodebuild[11250:270231] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
/Users/gopikrishnap/.pub-cache/hosted/pub.dev/printing-5.10.3/macos/Classes/PrintJob.swift:233:23: warning: 'WebView' was deprecated in macOS 10.14: No longer supported; please adopt WKWebView.
        let webView = WebView()
                      ^
../../.pub-cache/hosted/pub.dev/printing-5.10.3/lib/src/widget_wrapper.dart:178:7: Error: No named parameter with the name 'window'.
      window: view,
      ^^^^^^
/users/gopikrishnap/flutter/packages/flutter/lib/src/rendering/view.dart:68:3: Context: Found this candidate, but the arguments don't match.
  RenderView({
  ^^^^^^^^^^
Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed

**Comment by gopiKrishnaPuligundla** [comment] 2023-05-13 17:23
bash-3.2$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-x64, locale en-IN)
    • Flutter version 3.10.0 on channel stable at /Users/gopikrishnap/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (4 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/gopikrishnap/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 13.3.1 22E261 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by gopiKrishnaPuligundla** [comment] 2023-05-13 17:24
could some one please check and address this issue

**Comment by stuartmorgan** [comment] 2023-05-13 20:24
The output you put in the issue title is just harmless informational output from Xcode; the error is this line that says it's error:

> ../../.pub-cache/hosted/pub.dev/printing-5.10.3/lib/src/widget_wrapper.dart:178:7: Error: No named parameter with the name 'window'.
> window: view,

This is coming from the `printing` package, so you'll need to report it to the authors of that package.

Closing as this is not a bug in Flutter.

**Closed by stuartmorgan** 2023-05-13 20:24 UTC

**Comment by gopiKrishnaPuligundla** [comment] 2023-05-14 02:49
but I am not able to run the application .. it says build failed , it doesn't seem to be error from my code , please help

/users/gopikrishnap/flutter/packages/flutter/lib/src/rendering/view.dart:68:3: Context: Found this candidate, but the arguments don't match.
RenderView({
^^^^^^^^^^
Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

Building macOS application...
Exception: Build process failed

**Comment by gopiKrishnaPuligundla** [comment] 2023-05-14 05:47
same issue seen even in ubuntu desktop app

Target kernel_snapshot failed: Exception
Exception: Build process failed

could you address it at the earliest ?

**Comment by stephcyrille** [comment] 2023-05-18 09:58
You just need to:
- Clean all your dependencies 
- Edit your <b>pubspec.yaml</b> from  `printing: ^5.10.3` to the latest release `printing: ^5.10.4` 

It's work for me.
