### ISSUE TITLE
I can't run or compile my first Flutter app under Android Studio

### ISSUE THREAD

**Issue by ChegMarcoADVANTECH** [flutter/flutter#68589] opened 2020-10-20 09:52 UTC
Hi all.

I just installed FLUTTER with a new Android simulator on the Android Studio IDE. BUT When I'm trying to run FLUTTER App (compile it) with android studio Simulator, I receive these following errors:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not resolve commons-io:commons-io:2.4.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > androidx.databinding:databinding-compiler-common:3.5.0
>       > Could not resolve commons-io:commons-io:2.4.
>          > Could not parse POM https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4.pom
>             > Could not resolve org.apache.commons:commons-parent:25.
>                > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.41.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.41
>       > Skipped due to earlier error
>    > Could not resolve net.sf.proguard:proguard-base:6.0.3.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > net.sf.proguard:proguard-gradle:6.0.3
>       > Skipped due to earlier error
>    > Could not resolve com.google.auto.value:auto-value:1.5.2.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:bundletool:0.9.0
>       > Skipped due to earlier error
>    > Could not resolve com.google.errorprone:error_prone_annotations:2.3.1.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:bundletool:0.9.0
>       > Skipped due to earlier error
>    > Could not resolve org.jdom:jdom2:2.0.6.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-script-runtime:1.3.50.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-daemon-embeddable:1.3.50.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.intellij.deps:trove4j:1.0.20181211.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-build-common:1.3.50.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-compiler-runner:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-daemon-client:1.3.50.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-compiler-runner:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-compiler-runner:1.3.50
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-scripting-common:1.3.50.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-scripting-jvm:1.3.50.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-stdlib:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains:annotations:13.0.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-stdlib:1.3.50
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0 > com.android.tools.layoutlib:layoutlib-api:26.5.0
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.kotlin:kotlin-util-io:1.3.50.
>      Required by:
>          project : > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > org.jetbrains.kotlin:kotlin-native-utils:1.3.50
>       > Skipped due to earlier error
>    > Could not resolve org.apache.commons:commons-compress:1.12.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0 > com.android.tools:repository:26.5.0
>       > Skipped due to earlier error
>    > Could not resolve org.jetbrains.trove4j:trove4j:20160824.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdk-common:26.5.0
>       > Skipped due to earlier error
>    > Could not resolve net.sf.kxml:kxml2:2.3.0.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.build:manifest-merger:26.5.0
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.ddms:ddmlib:26.5.0
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0 > com.android.tools.layoutlib:layoutlib-api:26.5.0
>       > Skipped due to earlier error
>    > Could not resolve com.google.code.findbugs:jsr305:3.0.2.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools.build:apkzlib:3.5.0
>       > Skipped due to earlier error
>    > Could not resolve com.google.guava:failureaccess:1.0.1.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > com.google.guava:guava:27.0.1-jre
>       > Skipped due to earlier error
>    > Could not resolve com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > com.google.guava:guava:27.0.1-jre
>       > Skipped due to earlier error
>    > Could not resolve com.google.code.findbugs:jsr305:3.0.2.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > com.google.guava:guava:27.0.1-jre
>       > Skipped due to earlier error
>    > Could not resolve org.checkerframework:checker-qual:2.5.2.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > com.google.guava:guava:27.0.1-jre
>       > Skipped due to earlier error
>    > Could not resolve com.google.errorprone:error_prone_annotations:2.3.1.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > com.google.guava:guava:27.0.1-jre
>       > Skipped due to earlier error
>    > Could not resolve com.google.j2objc:j2objc-annotations:1.1.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > com.google.guava:guava:27.0.1-jre
>       > Skipped due to earlier error
>    > Could not resolve org.codehaus.mojo:animal-sniffer-annotations:1.17.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > com.google.guava:guava:27.0.1-jre
>       > Skipped due to earlier error
>    > Could not resolve commons-logging:commons-logging:1.2.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > org.apache.httpcomponents:httpclient:4.5.6
>       > Skipped due to earlier error
>    > Could not resolve commons-codec:commons-codec:1.10.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.analytics-library:crash:26.5.0 > org.apache.httpcomponents:httpclient:4.5.6
>       > Skipped due to earlier error
>    > Could not resolve com.sun.activation:javax.activation:1.2.0.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0 > com.android.tools:repository:26.5.0
>       > Skipped due to earlier error
>    > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0 > com.android.tools:repository:26.5.0
>       > Skipped due to earlier error
>    > Could not resolve com.google.jimfs:jimfs:1.1.
>      Required by:
>          project : > com.android.tools.build:gradle:3.5.0 > com.android.tools.build:builder:3.5.0 > com.android.tools:sdklib:26.5.0 > com.android.tools:repository:26.5.0
>       > Skipped due to earlier error
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 18m 49s
> Exception: Gradle task assembleDebug failed with exit code 1

**PLEASE HELP ME TO RUN MY FIRST FLUTTER APP UNDER SIMULATOR ON ANDROID STUDIO.**

**Comment by pedromassangocode** [comment] 2020-10-20 12:10
Hi @ChegMarcoADVANTECH 
Looks like Android Studio is having trouble to download the required dependencies.

Is you machine connected to internet?
If yes then this might be caused by a firewall. You can try to use a different network.

**Comment by jayjah** [comment] 2020-10-20 12:16
Well, it looks like you are not connected to the internet, like @pedromassangocode mentioned or maybe you have an error in your gradle files. 
Could you provide your android/app/build.gradle file? Btw verify your gradle and repos options in android/build.gradle file. Should look similar to: 
```
    repositories {
        google()
        jcenter()
    }

classpath 'com.android.tools.build:gradle:4.0.1'
```

**Comment by ChegMarcoADVANTECH** [comment] 2020-10-20 12:17
Ok thank you

**Comment by pedromassangocode** [comment] 2020-10-21 06:48
Hi @ChegMarcoADVANTECH 

I'm closing this for now, let me know if the issue still happening with a stable internet connection.

**Closed by pedromassangocode** 2020-10-21 06:48 UTC
Labels: in triage
