### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

### ISSUE THREAD

**Issue by SpiciedCrab** [flutter/flutter#39470] opened 2019-08-29 07:34 UTC
When I archive the binary file for App Store today, the following issues occurs :

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

but it doesn't appear before since I'm using the same packages in pubspec.yaml, and no UIWebview in iOS plugins used.

So please check whether it exists in flutter...

Flutter doctor info:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.3 18D42, locale
    zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at
      /Users/harly/Library/Developer/Flutter/flutter
    • Framework revision 20e59316b8 (6 周前), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/harly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0
```

**Comment by fralways** [comment] 2019-08-29 09:15
Just a lucky guess, maybe https://github.com/flutter/plugins/tree/master/packages/url_launcher uses uiwebview and is causing this.

**Comment by SpiciedCrab** [comment] 2019-08-29 09:24
@fralways but it's not included in my app..

**Comment by mouse-lin** [comment] 2019-08-29 13:13
Is there any WKWebView in your project?

**Comment by formatCvt** [comment] 2019-08-29 13:29
@SpiciedCrab check your `pubspec.lock` file for `url_launcher` maybe one of your plugins depends on old version of url_launcher

**Comment by SheriefAlaa** [comment] 2019-08-29 13:33
> @SpiciedCrab check your `pubspec.lock` file for `url_launcher` maybe one of your plugins depends on old version of url_launcher

can confirm I have the same problem and there's no entry in my `pubspec.lock` with `url_launcher`. I am suspecting `https://pub.dev/packages/google_maps_flutter` because I enabled `io.flutter.embedded_views_preview` as prescribed in the library's doc.

**Comment by per-activote** [comment] 2019-08-29 13:49
Do you happen to have firebase_auth as a package? I'm running into the same problem and that's the only package that I've found that I'm including that seems to be using UIWebView based on a quick search through the package source code.

**Comment by alardizabal** [comment] 2019-08-29 14:03
> Do you happen to have firebase_auth as a package? I'm running into the same problem and that's the only package that I've found that I'm including that seems to be using UIWebView based on a quick search through the package source code.

I see the same issue during upload and I believe for me it's the plugins for Firebase Auth and Firebase Dynamic Links.

**Comment by eseidelGoogle** [comment] 2019-08-29 14:28
@amirh @collinjackson

**Comment by madfingo** [comment] 2019-08-29 17:04
This was just fixed by the firebase team. https://github.com/firebase/firebase-ios-sdk/pull/3723

**Comment by collinjackson** [comment] 2019-08-30 00:51
I talked to the Firebase team, and it sounds like firebase/firebase-ios-sdk#3723 will be released in the next update. Once it is available, the actionable work here is to update Flutterfire's CocoaPods dependency to point to the new implementation.

I've filed https://github.com/FirebaseExtended/flutterfire/issues/62 in the FirebaseExtended repo.

**Comment by dhanrajvermaRepo** [comment] 2019-08-31 11:26
i have used firebase dynamic links plugin in my flutter app. It was working fine but now when i rebuild my iOS app, it always takes me to app store. I have checked my setup several times and every time found it correct then why it is happening.
@collinjackson help me.

**Comment by dhanrajvermaRepo** [comment] 2019-08-31 12:02
> When I archive the binary file for App Store today, the following issues occurs :
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> but it doesn't appear before since I'm using the same packages in pubspec.yaml, and no UIWebview in iOS plugins used.
> 
> So please check whether it exists in flutter...
> 
> Flutter doctor info:
> 
> ```
> [✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.3 18D42, locale
>     zh-Hans-CN)
>     • Flutter version 1.7.8+hotfix.4 at
>       /Users/harly/Library/Developer/Flutter/flutter
>     • Framework revision 20e59316b8 (6 周前), 2019-07-18 20:04:33 -0700
>     • Engine revision fee001c93f
>     • Dart version 2.4.0
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/harly/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling
>       support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_152-release-1136-b06)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.3, Build version 10G8
>     • CocoaPods version 1.6.1
> 
> [✓] iOS tools - develop for iOS devices
>     • ios-deploy 1.9.4
> 
> [✓] Android Studio (version 3.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 31.3.1
>     • Dart plugin version 181.5656
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_152-release-1136-b06)
> 
> [✓] VS Code (version 1.32.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.25.0
> ```

@SpiciedCrab please check whether dynamic links in your iOS app is working or not. I am asking it because firebase_dynamic_links is not working (always takes me to app store) in ios now but last week it was working fine.

**Comment by bkayfitz-cara** [comment] 2019-09-04 20:55
It's not just Dynamic Links. There is also a `UIWebView` in Firebase Auth.  There's a small called `FIRAuthWebView` that looks like its just a simple wrapper around UIWebView.

**Comment by per-activote** [comment] 2019-09-04 21:41
The latest version of FirebaseAuth has fixed this. I updated, ran the pod update and everything worked without any errors /warnings from Apple.

**Comment by eaglesue** [comment] 2019-09-05 08:28
AFNetworking（3.2.1）这个库里面包含了UIWebView的相关API，如果你的flutter工程里面有这个库，肯定会报这个问题，没什么大碍。
The AFNetworking(v3.2.1) used APIs that included in UIWebView, which doesn't matter

**Comment by collinjackson** [comment] 2019-09-05 18:27
It looks like this fix is in Firebase 6.8.0, which hasn't yet been released to https://cocoapods.org/pods/Firebase. I'll leave this issue open until the CocoaPod is released (should be this week according to [Paul's comment](https://github.com/firebase/firebase-ios-sdk/pull/3723#issuecomment-527183143)), and then we'll update Flutterfire to require it.

**Comment by collinjackson** [comment] 2019-09-09 16:48
6.8.0 has been released, so we can now update Flutterfire to require it.

**Comment by Hixie** [comment] 2019-09-17 23:36
@collinjackson Can you give us an update on the status of this bug? Thanks.

**Comment by collinjackson** [comment] 2019-09-18 19:11
Per the code review feedback from @bparrishMines (https://github.com/FirebaseExtended/flutterfire/pull/141#issuecomment-532000581 and https://github.com/FirebaseExtended/flutterfire/pull/142#issuecomment-532000841), I don't think we need to make any changes to Flutterfire.

Running `(cd ios && pod update --repo-update)` should fix issue. If anyone is still encountering errors after doing so please let me know so we can reopen the issue.

**Comment by chenna-reddy** [comment] 2019-09-18 20:59
> 
> Running `(cd ios && pod update --repo-update)` should fix the issue. If anyone is still encountering errors after doing so please let me know so we can reopen and investigate further.

These steps have partially fixed the problem. `google_sign_in` still has the problem. If I upload without `google_sign_in` then the app is accepted by AppStore.

I see following version restriction in `google_sign_in` podspec:
```
  s.dependency 'Flutter'
  s.dependency 'GoogleSignIn', '~> 4.0'
```

GoogleSignIn version 4.x might still be using the deprecated UIWebView.

**Comment by sceee** [comment] 2019-09-19 05:11
I can agree with @chenna-reddy, with Google Sign in and Firebase Auth you still get this error from Apple.

**Comment by collinjackson** [comment] 2019-09-19 16:25
OK, it sounds like

**Comment by pravinarr** [comment] 2019-09-20 23:48
@collinjackson  It seems firebase_crashlytics is also using the UIWebview , can you check that too?.
Thanks in advance

**Comment by chenna-reddy** [comment] 2019-09-21 11:30
> @collinjackson It seems firebase_crashlytics is also using the UIWebview , can you check that too?.
> Thanks in advance

@pravinarr App store didn't complain with `firebase_crashlytics: ^0.1.0+3`. You need to update the pods as mentioned above.

**Comment by chenna-reddy** [comment] 2019-10-11 12:04
I couldn't make iOS release from last 40days becasuse of this bug (with `google_sign_in` specially). I guess it's same for all the Apps using `google_sign_in`. @collinjackson Could you please push this up??

**Comment by PerLycke** [comment] 2019-10-11 12:18
You can still release, the delivery will be successful, Apple will just notify you about that they will stop accept submissions going forward.

It could however affect review waiting time or something else, only Apple would know

**Comment by kroikie** [comment] 2019-10-13 19:38
@SpiciedCrab

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1082. Any further collaboration will be done there.

**Comment by collinjackson** [comment] 2019-10-14 18:57
Reopening since this is no longer a Flutterfire issue (it's about google_sign_in)

**Comment by cuijinfeng68** [comment] 2019-10-28 18:54
I have updated it to FireBase 6.11，but Deprecated Api Usage has not been solved.
please help me.
PODS:
  - FBSDKCoreKit (5.8.0):
    - FBSDKCoreKit/Basics (= 5.8.0)
    - FBSDKCoreKit/Core (= 5.8.0)
  - FBSDKCoreKit/Basics (5.8.0)
  - FBSDKCoreKit/Core (5.8.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (5.8.0):
    - FBSDKLoginKit/Login (= 5.8.0)
  - FBSDKLoginKit/Login (5.8.0):
    - FBSDKCoreKit (~> 5.0)
  - Firebase/Auth (6.11.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.3.1)
  - Firebase/Core (6.11.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.3)
  - Firebase/CoreOnly (6.11.0):
    - FirebaseCore (= 6.3.2)
  - Firebase/Messaging (6.11.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.1.7)
  - firebase_auth (0.0.1):
    - Firebase/Auth (~> 6.0)
    - Firebase/Core
    - Flutter
  - firebase_core (0.0.1):
    - Firebase/Core
    - Flutter
  - firebase_messaging (0.0.1):
    - Firebase/Core
    - Firebase/Messaging
    - Flutter
  - FirebaseAnalytics (6.1.3):
    - FirebaseCore (~> 6.3)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.1.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3.901)
  - FirebaseAnalyticsInterop (1.4.0)
  - FirebaseAuth (6.3.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.3.2):
    - FirebaseCoreDiagnostics (~> 1.0)
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnostics (1.1.1):
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.0.0)
  - FirebaseInstanceID (4.2.6):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebaseMessaging (4.1.7):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Reachability (~> 6.2)
    - GoogleUtilities/UserDefaults (~> 6.2)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - Flutter (1.0.0)
  - flutter_facebook_login (0.0.1):
    - FBSDKCoreKit (~> 5.5)
    - FBSDKLoginKit (~> 5.5)
    - Flutter
  - flutter_incall_manager (0.0.1):
    - Flutter
  - flutter_webrtc (0.1.6):
    - Flutter
    - GoogleWebRTC (= 1.1.27299)
    - libyuv-iOS
  - google_sign_in (0.0.1):
    - Flutter
    - GoogleSignIn (~> 4.0)
  - GoogleAppMeasurement (6.1.3):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3.901)
  - GoogleDataTransport (3.0.1)
  - GoogleDataTransportCCTSupport (1.2.1):
    - GoogleDataTransport (~> 3.0)
    - nanopb (~> 0.3.901)
  - GoogleSignIn (4.4.0):
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - "GoogleToolboxForMac/NSString+URLArguments (~> 2.1)"
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.2.2):
    - GoogleToolboxForMac/Defines (= 2.2.2)
  - GoogleToolboxForMac/Defines (2.2.2)
  - "GoogleToolboxForMac/NSDictionary+URLArguments (2.2.2)":
    - GoogleToolboxForMac/DebugUtils (= 2.2.2)
    - GoogleToolboxForMac/Defines (= 2.2.2)
    - "GoogleToolboxForMac/NSString+URLArguments (= 2.2.2)"
  - "GoogleToolboxForMac/NSString+URLArguments (2.2.2)"
  - GoogleUtilities/AppDelegateSwizzler (6.3.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.3.1)
  - GoogleUtilities/Logger (6.3.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.3.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.3.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.3.1)"
  - GoogleUtilities/Reachability (6.3.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.3.1):
    - GoogleUtilities/Logger
  - GoogleWebRTC (1.1.27299)
  - GTMSessionFetcher/Core (1.3.0)
  - image_picker (0.0.1):
    - Flutter
  - libyuv-iOS (1.0.2)
  - nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
  - nanopb/decode (0.3.9011)
  - nanopb/encode (0.3.9011)
  - package_info (0.0.1):
    - Flutter
  - Protobuf (3.10.0)
  - searchable_dropdown (0.0.1):
    - Flutter
  - share (0.5.2):
    - Flutter
  - shared_preferences (0.0.1):
    - Flutter
  - url_launcher (0.0.1):
    - Flutter
  - webview_flutter (0.0.1):
    - Flutter

DEPENDENCIES:
  - Firebase/Auth
  - Firebase/Messaging
  - firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`)
  - Flutter (from `.symlinks/flutter/ios-release`)
  - flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`)
  - flutter_incall_manager (from `.symlinks/plugins/flutter_incall_manager/ios`)
  - flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`)
  - google_sign_in (from `.symlinks/plugins/google_sign_in/ios`)
  - image_picker (from `.symlinks/plugins/image_picker/ios`)
  - package_info (from `.symlinks/plugins/package_info/ios`)
  - searchable_dropdown (from `.symlinks/plugins/searchable_dropdown/ios`)
  - share (from `.symlinks/plugins/share/ios`)
  - shared_preferences (from `.symlinks/plugins/shared_preferences/ios`)
  - url_launcher (from `.symlinks/plugins/url_launcher/ios`)
  - webview_flutter (from `.symlinks/plugins/webview_flutter/ios`)

SPEC REPOS:
  trunk:
    - FBSDKCoreKit
    - FBSDKLoginKit
    - Firebase
    - FirebaseAnalytics
    - FirebaseAnalyticsInterop
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCoreDiagnosticsInterop
    - FirebaseInstanceID
    - FirebaseMessaging
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleDataTransportCCTSupport
    - GoogleSignIn
    - GoogleToolboxForMac
    - GoogleUtilities
    - GoogleWebRTC
    - GTMSessionFetcher
    - libyuv-iOS
    - nanopb
    - Protobuf

EXTERNAL SOURCES:
  firebase_auth:
    :path: ".symlinks/plugins/firebase_auth/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  firebase_messaging:
    :path: ".symlinks/plugins/firebase_messaging/ios"
  Flutter:
    :path: ".symlinks/flutter/ios-release"
  flutter_facebook_login:
    :path: ".symlinks/plugins/flutter_facebook_login/ios"
  flutter_incall_manager:
    :path: ".symlinks/plugins/flutter_incall_manager/ios"
  flutter_webrtc:
    :path: ".symlinks/plugins/flutter_webrtc/ios"
  google_sign_in:
    :path: ".symlinks/plugins/google_sign_in/ios"
  image_picker:
    :path: ".symlinks/plugins/image_picker/ios"
  package_info:
    :path: ".symlinks/plugins/package_info/ios"
  searchable_dropdown:
    :path: ".symlinks/plugins/searchable_dropdown/ios"
  share:
    :path: ".symlinks/plugins/share/ios"
  shared_preferences:
    :path: ".symlinks/plugins/shared_preferences/ios"
  url_launcher:
    :path: ".symlinks/plugins/url_launcher/ios"
  webview_flutter:
    :path: ".symlinks/plugins/webview_flutter/ios"

SPEC CHECKSUMS:
  FBSDKCoreKit: e7dcac0aabcfb09d0166998edd95fe3b05a0ce5d
  FBSDKLoginKit: 1b0cf04df0370b37404213157b060d6666ede814
  Firebase: bc9cfc7a96c73268656d5aaab453ff1b4b530e0e
  firebase_auth: 1e3b7bdd37b9fbd4ef75ba1d985b00be09e02d3d
  firebase_core: ae55ea92448ec8675d325da4db22cf3b4d58a54d
  firebase_messaging: 0d5c04cc40f58bd4bf7f2992c91050f9bc01bec3
  FirebaseAnalytics: 0e3ecff2c5d86070f7d4325e21f1edabfbd558dc
  FirebaseAnalyticsInterop: d48b6ab67bcf016a05e55b71fc39c61c0cb6b7f3
  FirebaseAuth: b401a012cc33b04df3b52bb308b04e8766f2693e
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: beeff42c07c30ea94702471d99db2089b594fbbd
  FirebaseCoreDiagnostics: af29e43048607588c050889d19204f4d7b758c9f
  FirebaseCoreDiagnosticsInterop: 6829da2b8d1fc795ff1bd99df751d3788035d2cb
  FirebaseInstanceID: d0eafcd8bdbd3447cd694594734078c3e3e77d8b
  FirebaseMessaging: 5ab57080c83bc98c9961412e1dab379f4193d02a
  Flutter: 0e3d915762c693b495b44d77113d4970485de6ec
  flutter_facebook_login: cfb5659f686b1c575ef205c6b6fd20db9679d3c4
  flutter_incall_manager: 1a6aea8d37fb46d63aaa30ac7ea225e121704eab
  flutter_webrtc: b4d969a556b246378adb24262375b0204e1e89df
  google_sign_in: 27e70a98b529f0b076d4b19f231b81da28b1750b
  GoogleAppMeasurement: 434cc7be25e71dc04b8d0e3079125127b330e84a
  GoogleDataTransport: 166f9b9f82cbf60a204e8fe2daa9db3e3ec1fb15
  GoogleDataTransportCCTSupport: f6ab1962e9dc05ab1fb938b795e5b310209edeec
  GoogleSignIn: 7ff245e1a7b26d379099d3243a562f5747e23d39
  GoogleToolboxForMac: 800648f8b3127618c1b59c7f97684427630c5ea3
  GoogleUtilities: f895fde57977df4e0233edda0dbeac490e3703b6
  GoogleWebRTC: 893a5f2f3635437ec3b05ef240993d5713307804
  GTMSessionFetcher: 43b8b64263023d4f32caa0b40f4c8bfa3c5f36d8
  image_picker: 16e5fec1fbc87fd3b297c53e4048521eaf17cd06
  libyuv-iOS: 5a154ccc84ec754029886ecb607512731fe30640
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  package_info: 48b108e75b8802c2d5e126f208ef540561c98aef
  Protobuf: a4dc852ad69c027ca2166ed287b856697814375b
  searchable_dropdown: b3fd8c1d4c5704ff51b21f4c99a9f73b057269ee
  share: bae0a282aab4483288913fc4dc0b935d4b491f2e
  shared_preferences: 430726339841afefe5142b9c1f50cb6bd7793e01
  url_launcher: a1c0cc845906122c4784c542523d8cacbded5626
  webview_flutter: db3aba222b23e4dc432e0c5882834123dc50ff9f

PODFILE CHECKSUM: 6d9b06229b0843603ad7e5d0e61885da60e81481

COCOAPODS: 1.8.4

**Comment by PerLycke** [comment] 2019-10-28 19:06
@cuijinfeng68 using google_sign_in causes this, and there's a fix coming for that: https://github.com/flutter/plugins/pull/2127

**Comment by cuijinfeng68** [comment] 2019-10-29 02:20
> @cuijinfeng68 using google_sign_in causes this, and there's a fix coming for that: [flutter/plugins#2127](https://github.com/flutter/plugins/pull/2127)
I try to pod repo update, but it does not work.
how should I do to update it?

**Comment by cuijinfeng68** [comment] 2019-10-29 02:41
google_sign_in ^5.0.0 which doesn't match any versions, version solving failed.
pub get failed (1)

**Comment by PerLycke** [comment] 2019-10-29 06:35
@cuijinfeng68 It's not merged yet, you need to wait until it is or fork the repo and merge it yourself. Good luck

**Comment by venkatesh513** [comment] 2019-10-29 06:47
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

but it doesn't appear before since I'm using the same packages in pubspec.yaml, and no UIWebview in iOS plugins used.

So please check whether it exists in flutter...
Flutter doctor info:
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G87, locale
    en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] Connected device (1 available)

• No issues found!
**here is my pub file i am using** 
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intro_slider: 1.1.9
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.0.7
  shared_preferences: 0.5.1+2
  firebase_storage: ^3.0.6
  image_picker: ^0.6.0+17
  camera: 0.4.2
  image_cropper: 1.0.0
  flutter_datetime_picker: 1.1.4
  numberpicker: 1.0.0
  firebase_analytics: ^5.0.2
  image: 2.0.7
  flutter_slidable: 0.4.9
  timeago: 2.0.10
  url_launcher: ^5.2.5
  flutter_launcher_icons: 0.7.0
  firebase_messaging: ^5.1.6
  http: ^0.12.0+2
  dotted_border: ^0.1.1
  tree_view: ^0.0.5
  shimmer: ^1.0.0
  usage: ^3.4.1
  flutter_cupertino_date_picker: ^1.0.3
  datetime_picker_formfield: ^0.2.0
  timezone: ^0.5.4
  flutter_auth_buttons: ^0.5.0
  flutter_svg: ^0.13.1
  logger: ^0.7.0+2
  provider: ^3.0.0+1
  pin_code_text_field: ^1.2.1
  flutter_typeahead: ^1.6.1
  flutter_google_places: ^0.2.3
  logging: ^0.11.3+2
  rxdart: ^0.22.2
  geoflutterfire: 2.0.3+5
  location: ^2.3.5
  google_maps_flutter: ^0.5.21+8
  app_settings: ^1.0.6+2
  geolocator: ^5.1.4+1
  connectivity: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
**i have done pod update also u can check my pod file below**
Downloading dependencies
Installing BoringSSL-GRPC (0.0.3)
Installing Firebase (6.11.0)
Installing FirebaseAnalytics (6.1.3)
Installing FirebaseAnalyticsInterop (1.4.0)
Installing FirebaseAuth (6.3.1)
Installing FirebaseAuthInterop (1.0.0)
Installing FirebaseCore (6.3.2)
Installing FirebaseCoreDiagnostics (1.1.1)
Installing FirebaseCoreDiagnosticsInterop (1.0.0)
Installing FirebaseFirestore (1.6.1)
Installing FirebaseInstanceID (4.2.6)
Installing FirebaseMessaging (4.1.7)
Installing FirebaseStorage (3.4.1)
Installing Flutter (1.0.0)
Installing GTMSessionFetcher (1.3.0)
Installing GoogleAppMeasurement (6.1.3)
Installing GoogleDataTransport (3.0.1)
Installing GoogleDataTransportCCTSupport (1.2.1)
Installing GoogleMaps (3.6.0)
Installing GoogleSignIn (4.4.0)
Installing GoogleToolboxForMac (2.2.2)
Installing GoogleUtilities (6.3.1)
Installing Protobuf (3.10.0)
Installing Reachability (3.2)
Installing TOCropViewController (2.3.8)
Installing app_settings (1.0.6+2)
Installing camera (0.0.1)
Installing cloud_firestore (0.0.1)
Installing connectivity (0.0.1)
Installing firebase_analytics (0.0.1)
Installing firebase_auth (0.0.1)
Installing firebase_core (0.0.1)
Installing firebase_messaging (0.0.1)
Installing firebase_storage (0.0.1)
Installing gRPC-C++ (0.0.9)
Installing gRPC-Core (1.21.0)
Installing geoflutterfire (0.0.1)
Installing geolocator (5.1.4)
Installing google_api_availability (2.0.1)
Installing google_maps_flutter (0.0.1)

Installing google_sign_in (0.0.1)
Installing image_cropper (0.0.1)
Installing image_picker (0.0.1)
Installing intro_slider (0.0.1)
Installing keyboard_visibility (0.5.0)
Installing leveldb-library (1.22)
Installing location (0.0.1)
Installing location_permissions (2.0.3)
Installing nanopb (0.3.9011)
Installing shared_preferences (0.0.1)
Installing url_launcher (0.0.1)
**I have update every sdk but i dont know where i am doing wrong still i am getting same mail from apple**
Or shall we ignore this mail and push the build to app store?
Can anyone help us?

**Comment by PerLycke** [comment] 2019-10-29 06:52
@venkatesh513 you can still push the build to Apple as it's just a warning for the future. google_sign_in 4.4.0 causes this and the same answers I gave above still stands. Good luck

**Comment by venkatesh513** [comment] 2019-10-29 10:52
@gimox Thanks

**Closed** 2019-10-29 23:28 UTC
Labels: a: annoyance, customer: crowd, p: google_sign_in, plugin, severe: customer critical, waiting for PR to land (fixed), ⌺‬ platform-ios

**Comment by rennjeanpaul** [comment] 2019-11-19 01:05
Since this has become the “goto answer” on Google for this rejection message, I’ll add a React Native fix.

On React Native, considering that you’ve been a good developer and are not using UIWebView in your own code, use the following command to find out which of your dependencies still does use UIWebView:

grep -r UIWebView node_modules/*

Full Source Code With Example [Here](https://icetutor.com/question/flutter-how-to-fix-itms-90809-deprecated-api-usage-apple-will-stop-accepting-submissions-of-apps-that-use-uiwebview-apis/)

**Comment by crcaicedo** [comment] 2019-12-06 21:19
I updated pods using pod update, and firebase gets updated

But Apple keeps send me this warning about deprecated API usage

The error still exists

**Comment by bumasoft** [comment] 2020-02-18 11:50
I am getting the same error, I removed url_launcher from my project, thinking it was the culprit, but it's not. Here is my pubspec:

`name: x
description: xx

version: 1.16.0+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  shared_preferences: ^0.5.6
  device_id: ^0.2.0
  encrypt: ^3.3.1
  password: ^1.0.0
  passcode_screen: ^1.0.2
  provider: ^3.2.0
  camera: ^0.5.7+2
  path_provider: ^1.5.1
  after_init: ^0.1.2
  flutter_aws_s3_client: ^0.5.0
  sigv4: ^3.1.0
  aws_ai:
    path: extra_packages/aws-ai/
  qr_flutter: ^3.2.0
  qr_mobile_vision: ^0.3.1
  flutter_local_notifications: ^0.9.1+3
  firebase_messaging: ^6.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
`

**Comment by thenexus00** [comment] 2020-03-03 22:39
I had this as well today.
The latest version of url_launcher has still not changed over.

Updating Firebase..
firebase_storage
firebase_database
Mainly corrected the errors there so it has been addressed here.

@bumasoft  on the build it should have the path with regard to the error which identifies the package at fault.

**Comment by bumasoft** [comment] 2020-03-03 22:49
My error is actually coming from Google MobileVision, a package I use for scanning barcodes.

**Comment by nemoryoliver** [comment] 2020-03-06 02:11
I hope we get a concrete solution soon! April 2020 is almost here.

**Comment by KorbinianMossandl** [comment] 2020-03-06 18:20
@thenexus00 
i have no info about the depricated API in my build log, but still get the warning when submitting to apple. any other ideas how to identify the culprit?

**Comment by sajalgarg** [comment] 2020-03-06 18:26
Why is this issue closed? Isn't it being tracked anywhere?

**Comment by KorbinianMossandl** [comment] 2020-03-06 18:27
@collinjackson this issue is still happening and we only have a few weeks left before apple will stop allowing submissions

**Comment by LiNiVi21** [comment] 2020-03-16 15:18
It's still happening to me and I am using the latest Xamarin.Forms 4.5.0.356 which suppose to resolve that issue.

**Comment by nemoryoliver** [comment] 2020-03-16 23:27
Any official announcement/update, please?

**Comment by KorbinianMossandl** [comment] 2020-03-17 09:10
So after tinkering with this problem for some time let me share my findings:
i can confirm that the issue is not within flutter and also not within any plugins from the flutter team. if you are getting this you are importing a package that still uses the UIWebView API. BUT one thing that took me some time and maybe should be fixed: if you remove a package from the pubspec.yaml it does NOT automatically get removed from your podfile.lock. So even if you remove the package in question there, you still need to completely rebuild the podfile.lock to get rid of the imports.

For me the package in question was zendesk chat. the problem here is that zendesk has a precompiled package for iOS so finding the UIWebView by simple code search did not work. They also have no fix available yet, so we will see how things go starting april.

Hope this is to some help for others having this issue.

**Comment by sajalgarg** [comment] 2020-03-17 16:23
@KorbinianMossandl What do you mean by rebuilding podfile.lock. I deleted the file and run flutter build ios but got the same error message.

**Comment by KorbinianMossandl** [comment] 2020-03-17 16:36
@sajalgarg thats one way to rebuild it, yes. in that case you must be using a package that still uses UIWebView.
you can try to run ` grep -r "UIWebView" .` in your project folder to find the culprit.

**Comment by sajalgarg** [comment] 2020-03-18 18:31
@KorbinianMossandl Thanks a lot. The error got resolved
With grep command, I found the issue was in google_sign_in plugin. I updated the the plugin in podspec, deleted podfile.lock and rebuild the project.

**Comment by daniele777** [comment] 2020-03-20 19:55
Guys i have same issue using url_launcher how ti fix ? Or can use another plugin compatibile with iOS ?
