### ISSUE TITLE
Flutter provider not working in release apk, but working fine in debug mode

### ISSUE THREAD

**Issue by JgdshSeerm** [flutter/flutter#74290] opened 2021-01-20 02:51 UTC
We are using provider as Provider.of(context, listen: false), and using this inside a Consumer which is not working in release apk, whereas the same is working fine in debug builds.

**Comment by athul-ain** [comment] 2021-01-20 04:07
Use an old Gradle version, that worked for me.

classpath 'com.android.tools.build:gradle:3.5.0'
use this version on android/build.gradle

**Comment by JgdshSeerm** [comment] 2021-01-20 04:45
> Use an old Gradle version, that worked for me.
> 
> classpath 'com.android.tools.build:gradle:3.5.0'
> use this version on android/build.gradle

Thanks for the suggestion, but I'm using the same gradle version, and still its not working.

**Comment by pedromassangocode** [comment] 2021-01-20 07:04
Hi @JgdshSeerm 
From what I can see, the issue is related to a 3rd party package rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-20 07:04 UTC
