### ISSUE TITLE
Webview package does not compile on Android

### ISSUE THREAD

**Issue by YukiAttano** [flutter/flutter#156651] opened 2024-10-12 12:27 UTC
### Steps to reproduce

Using the [WebView Package](https://pub.dev/packages/webview_flutter) will cause a compilation error in Gradle

Start compiling the Android project.

EDIT: as with Android Studio Ladybug either or both Java and Gradle got an update, an Android project refactoring was necessary (to compile with the new versions).
The provided repository is therefor on the 'currently' latest state. 

### Expected results

Project compiles

### Actual results

Project does not compile

### Code sample

[Freshly created Repo](https://github.com/YukiAttano/flutter_webview_error)

### Logs

<details open><summary>Logs</summary>

```console
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webview_flutter_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':webview_flutter_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\2906a\AppData\Local\Android\Sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\2906a\.gradle\caches\transforms-3\4a46fc89ed5f9adfe3afebf74eb8bfeb\transformed\output\temp\jmod --add-modules java.base --output C:\Users\2906a\.gradle\caches\transforms-3\4a46fc89ed5f9adfe3afebf74eb8bfeb\transformed\output\jdkImage --disable-plugin system-modules}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4249], locale de-DE)
    • Flutter version 3.24.3 on channel stable at C:\Users\2906a\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at C:\Users\2906a\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • ANDROID_SDK_ROOT = C:\Users\2906a\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35312.102
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\2906a\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM N220U (mobile) • RF2R666PJZT • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22631.4249]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 127.0.2651.86

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by iapicca** [comment] 2024-10-12 13:34
@YukiAttano 
works as intended on my Samsung A55 (physical device) and your same flutter version

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(
      MaterialApp(
        home: Center(
          child: WebViewWidget(
            controller: WebViewController()
              ..loadRequest(Uri.parse('https://flutter.dev')),
          ),
        ),
      ),
    );
```

**Comment by YukiAttano** [comment] 2024-10-12 13:59
> @YukiAttano works as intended on my Samsung A55 (physical device) and your same flutter version
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:webview_flutter/webview_flutter.dart';
> 
> void main() => runApp(
>       MaterialApp(
>         home: Center(
>           child: WebViewWidget(
>             controller: WebViewController()
>               ..loadRequest(Uri.parse('https://flutter.dev')),
>           ),
>         ),
>       ),
>     );
> ```

Hmm, have you run my mentioned repository? 
I had to upgrade my Android project because of: Flutter plugin for AS got a new version -> required an Android Studio (AS) upgrade -> required an upgrade of the Android project because of Java/Gradle.

The provided repository is therefor freshly generated with the latest state of whatever happend in the background.

**Comment by iapicca** [comment] 2024-10-12 15:32
> EDIT: as with Android Studio Ladybug either or both Java and Gradle got an update, an Android project refactoring was necessary (to compile with the new versions).

> Hmm, have you run my mentioned repository?

yes
did you run the app via command line?

```console
gh repo clone YukiAttano/flutter_webview_error
Cloning into 'flutter_webview_error'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 98 (delta 6), reused 98 (delta 6), pack-reused 0 (from 0)
Receiving objects: 100% (98/98), 42.19 KiB | 459.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.

cd flutter_webview_error/

flutter run
Resolving dependencies...
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  flutter_lints 4.0.0 (5.0.0 available)
  leak_tracker 10.0.5 (10.0.7 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
  lints 4.0.0 (5.1.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  stack_trace 1.11.1 (1.12.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.2 (0.7.3 available)
  vm_service 14.2.5 (14.3.0 available)
Got dependencies!
11 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on SM A556B in debug mode...
Running Gradle task 'assembleDebug'...                             14.7s
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...           5.3s
Syncing files to device SM A556B...                                176ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on SM A556B is available at: http://127.0.0.1:59972/ZiN5BkzAlms=/
I/eads.google_ads( 1302): [HIDL_FETCH_IMapper] android.hardware.graphics.mapper@4.0: Loaded Mapper successfully.
The Flutter DevTools debugger and profiler on SM A556B is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:59972/ZiN5BkzAlms=/
I/BLASTBufferQueue_Java( 1302): update, w= 1080 h= 2340 mName = ViewRootImpl@774fbf[MainActivity] mNativeObject= 0xb4000074853a0000 sc.mNativeObject= 0xb400007485335c80 format= -3 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3031 android.view.ViewRootImpl.relayoutWindow:10153 android.view.ViewRootImpl.performTraversals:4126 android.view.ViewRootImpl.doTraversal:3302 android.view.ViewRootImpl$TraversalRunnable.run:11362 android.view.Choreographer$CallbackRecord.run:1689
I/ViewRootImpl@774fbf[MainActivity]( 1302): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) relayoutAsync=false req=(1080,2340)0 dur=5 res=0x401 s={true 0xb400007485587000} ch=false seqId=0
I/ViewRootImpl@774fbf[MainActivity]( 1302): updateBoundsLayer: t=android.view.SurfaceControl$Transaction@dac9131 sc=Surface(name=Bounds for - attano.yuki.googleads.google_ads/attano.yuki.googleads.google_ads.MainActivity@0)/@0x39cf016 frame=1
D/ViewRootImpl@774fbf[MainActivity]( 1302): reportNextDraw android.view.ViewRootImpl.performTraversals:4734 android.view.ViewRootImpl.doTraversal:3302 android.view.ViewRootImpl$TraversalRunnable.run:11362 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698
I/ViewRootImpl@774fbf[MainActivity]( 1302): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/BLASTBufferQueue( 1302): [SurfaceView[attano.yuki.googleads.google_ads/attano.yuki.googleads.google_ads.MainActivity]@0#1](f:0,a:0,s:0) onFrameAvailable the first frame is available
D/SurfaceView@21937a9( 1302): 35207081 setAlpha: alpha=1.0
I/SurfaceView( 1302): 35207081 Changes: creating=false format=false size=false visible=false alpha=true hint=false visible=false left=false top=false z=false attached=true lifecycleStrategy=false
I/SurfaceView@21937a9( 1302): 35207081 Cur surface: Surface(name=null)/@0xde7894a
I/SurfaceView@21937a9( 1302): updateSurface: mVisible = true mSurface.isValid() = true
I/SurfaceView@21937a9( 1302): updateSurface: mSurfaceCreated = true surfaceChanged = false visibleChanged = false
I/SurfaceView( 1302): 35207081 surfaceRedrawNeeded
I/SurfaceView( 1302): 35207081 finishedDrawing
V/SurfaceView@21937a9( 1302): Layout: x=0 y=0 w=1080 h=2298, frame=Rect(0, 0 - 1080, 2298)
I/ViewRootImpl@774fbf[MainActivity]( 1302): Setup new sync=wmsSync-ViewRootImpl@774fbf[MainActivity]#2
I/ViewRootImpl@774fbf[MainActivity]( 1302): Creating new active sync group ViewRootImpl@774fbf[MainActivity]#3
I/ViewRootImpl@774fbf[MainActivity]( 1302): registerCallbacksForSync syncBuffer=false
D/SurfaceView( 1302): 35207081 updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 1080, 2298] surfaceSize = 1080x2298
I/SurfaceView@21937a9( 1302): uSP: rtp = Rect(0, 0 - 1080, 2298) rtsw = 1080 rtsh = 2298
I/SurfaceView@21937a9( 1302): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@21937a9( 1302): aOrMT: ViewRootImpl@774fbf[MainActivity] t = android.view.SurfaceControl$Transaction@80f6d fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1660 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:369
I/ViewRootImpl@774fbf[MainActivity]( 1302): mWNT: t=0xb4000074942fb000 mBlastBufferQueue=0xb4000074853a0000 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.SurfaceView.applyOrMergeTransaction:1592 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1660
I/ViewRootImpl@774fbf[MainActivity]( 1302): Received frameDrawingCallback syncResult=0 frameNum=1.
I/ViewRootImpl@774fbf[MainActivity]( 1302): mWNT: t=0xb4000074942a9a80 mBlastBufferQueue=0xb4000074853a0000 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13859 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack>
I/ViewRootImpl@774fbf[MainActivity]( 1302): Setting up sync and frameCommitCallback
I/BLASTBufferQueue( 1302): [ViewRootImpl@774fbf[MainActivity]#0](f:0,a:0,s:0) onFrameAvailable the first frame is available
I/ViewRootImpl@774fbf[MainActivity]( 1302): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
D/OpenGLRenderer( 1302): CFMS:: SetUp Pid : 1302    Tid : 1397
I/ViewRootImpl@774fbf[MainActivity]( 1302): reportDrawFinished seqId=0
I/ViewRootImpl@774fbf[MainActivity]( 1302): handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
D/ViewRootImpl@774fbf[MainActivity]( 1302): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007485587000}
D/InputMethodManagerUtils( 1302): startInputInner - Id : 0
I/InputMethodManager( 1302): startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
D/InputMethodManagerUtils( 1302): startInputInner - Id : 0
I/InsetsController( 1302): onStateChanged: host=attano.yuki.googleads.google_ads/attano.yuki.googleads.google_ads.MainActivity, from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:7225, state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2340), mDisplayCutout=DisplayCutout{insets=Rect(0, 89 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(507, 0 - 573, 89), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2340 physicalDisplayWidth=1080 physicalDisplayHeight=2340 density={2.8125} cutoutSpec={M 0,0 M 0,8.177777777777778 a 11.73333333333333,11.73333333333333 0 1,0 0,23.46666666666667 a 11.73333333333333,11.73333333333333 0 1,0 0,-23.46666666666667 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=128, center=Point(128, 128)}, RoundedCorner{position=TopRight, radius=128, center=Point(952, 128)}, RoundedCorner{position=BottomRight, radius=128, center=Point(952, 2212)}, RoundedCorner{position=BottomLeft, radius=128, center=Point(128, 2212)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2340), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 89) rotation=0}, mDisplayShape=DisplayShape{ spec=-311912193 displayWidth=1080 displayHeight=2340 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {cff80000 mType=statusBars mFrame=[0,0][1080,89] mVisible=true mFlags=[]}, InsetsSource: {cff80005 mType=mandatorySystemGestures mFrame=[0,0][1080,123] mVisible=true mFlags=[]}, InsetsSource: {cff80006 mType=tappableElement mFrame=[0,0][1080,89] mVisible=true mFlags=[]}, InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {27 mType=displayCutout mFrame=[0,0][1080,89] mVisible=true mFlags=[]}, InsetsSource: {567d0001 mType=navigationBars mFrame=[0,2298][1080,2340] mVisible=true mFlags=[SUPPRESS_SCRIM]}, InsetsSource: {567d0004 mType=systemGestures mFrame=[0,0][84,2340] mVisible=true mFlags=[]}, InsetsSource: {567d0005 mType=mandatorySystemGestures mFrame=[0,2250][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {567d0006 mType=tappableElement mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {567d0024 mType=systemGestures mFrame=[996,0][1080,2340] mVisible=true mFlags=[]} }
I/InsetsSourceConsumer( 1302): applyRequestedVisibilityToControl: visible=false, type=ime, host=attano.yuki.googleads.google_ads/attano.yuki.googleads.google_ads.MainActivity
I/ViewRootImpl@774fbf[MainActivity]( 1302): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/ViewRootImpl@774fbf[MainActivity]( 1302): onDisplayChanged oldDisplayState=2 newDisplayState=2
D/ProfileInstaller( 1302): Installing profile for attano.yuki.googleads.google_ads
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 0
I/ViewRootImpl@774fbf[MainActivity]( 1302): ViewPostIme pointer 1
```

**Comment by huycozy** [comment] 2024-10-14 07:38
@YukiAttano Looks like you encounter the same issue with incompatible versions of Gradle, Java and AGP. Please try using versions as mentioned at https://github.com/flutter/flutter/issues/156304#issuecomment-2397707812 to see if it works.

**Comment by KarimX32** [comment] 2024-10-14 16:44
Encountering same issue.

**Comment by YukiAttano** [comment] 2024-10-17 08:52
> @YukiAttano Looks like you encounter the same issue with incompatible versions of Gradle, Java and AGP. Please try using versions as mentioned at [#156304 (comment)](https://github.com/flutter/flutter/issues/156304#issuecomment-2397707812) to see if it works.

Thank you very much. I had a project that died today and that linked configuration helped me.
I will try it today with my other Android projects and report back as soon as possible.

**Comment by stuartmorgan** [comment] 2024-10-17 14:30
Closing as a duplicate of https://github.com/flutter/flutter/issues/156304, where we are tracking this general issue.

**Closed by stuartmorgan** 2024-10-17 14:30 UTC
Labels: waiting for customer response, in triage
