### ISSUE TITLE
PointerUpEvent for mouse click does not report correct button being pressed.

### ISSUE THREAD

**Issue by NikolaTotev** [flutter/flutter#124548] opened 2023-04-10 21:51 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. PointerUpEvent.buttons only reports 0 as the mouse button pressed, regardless of the button that is  actually pressed.

**Expected results:** Some kind of differentiation between mouse buttons clicked.

**Actual results:** The same button is always reported.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
  runApp(const Demo());
}

class Demo extends StatelessWidget  {
  const Demo({Key? key}) : super(key: key);

  void onMouseClick(PointerUpEvent event) {
    //On desktop this always prints 0 regardless of the mouse button pressed.    
    debugPrint("Mouse button: ${event.buttons}");
    
    if (event.buttons == kPrimaryMouseButton) {      
      //As a result this if doenst work.
      debugPrint("Primary button pressed");
    }
    
  }
 
  @override
  Widget build(BuildContext context) {
    
        return Listener(
          onPointerUp: onMouseClick,
          child: 
             Container(height: 100, width: 100, color: Colors.red)          
        );       
  }
}

```

</details>
<details>
  <summary>Logs</summary>
flutter doctor -v
[✓] Flutter (Channel stable, 3.7.10, on Ubuntu 22.04.2 LTS 5.19.0-38-generic, locale en_US.UTF-8)
    • Flutter version 3.7.10 on channel stable at /home/nikola/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (7 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.77.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.2 LTS 5.19.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

</details>

**Comment by NikolaTotev** [comment] 2023-04-10 21:54
Similar issue can be found [here]( https://github.com/flutter/flutter/issues/81626).
I have made a new issue since this has been automatically close even though the issue still isn't resolved.

**Comment by danagbemava-nc** [comment] 2023-04-11 07:48
Hi @NikolaTotev, this is a duplicate of https://github.com/flutter/flutter/issues/110448. 

Kindly follow up in the issue linked above for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-04-11 07:48 UTC
Labels: in triage
