### ISSUE TITLE
[local_auth] `canCheckBiometrics` returning true when no biometrics available

### ISSUE THREAD

**Issue by diegogarciar** [flutter/flutter#91383] opened 2021-10-06 18:28 UTC
Hello,

I'm using an iOS simulator with no biometrics enabled and calling the function `canCheckBiometrics` which is defined as follows

```dart
  Future<bool> get canCheckBiometrics async =>  (await _channel.invokeListMethod<String>(
          'getAvailableBiometrics',
        ))).isNotEmpty;
```
the problem is that on the iOS code theres this:
``` objective-c
 else if (authError.code == LAErrorTouchIDNotEnrolled) {
    [biometrics addObject:@"undefined"];
  }
 ```
 so the array contains undefined making it not empty and thus returning true as if biometrics were available.

# proposal:
```dart
Future<bool> get canCheckBiometrics async =>
      (await getAvailableBiometrics()).isNotEmpty;
```
which automatically discards "undefined" from array

**Comment by coolswood** [comment] 2022-02-06 10:18
@stuartmorgan I've got the same error on android Honor 8, so I think need to add platform Android label too

**Comment by stuartmorgan** [comment] 2022-05-06 20:25
> the problem is that on the iOS code theres this:
> 
> ```objc
>  else if (authError.code == LAErrorTouchIDNotEnrolled) {
>     [biometrics addObject:@"undefined"];
>   }
> ```
> 
> so the array contains undefined making it not empty and thus returning true as if biometrics were available.

This is conflating device-level support for biometrics (which is what `canCheckBiometrics` checks) and enrollment. The code quoted above (it's changed now, but the behavior hasn't) was specifically designed to ensure that `canCheckBiometrics` would return true even if nothing was enrolled as long as the device reported that it has hardware biometrics support, because that's the documented behavior of the API.

Closing as this is not a bug. (I do have an update to the README that will be published soon that will clarify this though.)

**Closed by stuartmorgan** 2022-05-06 20:25 UTC
Labels: platform-ios, plugin, p: first party, p: local_auth, passed first triage, passed secondary triage, P4
