### ISSUE TITLE
FontWeight.w200 actually displays w100

### ISSUE THREAD

**Issue by PiN73** [flutter/flutter#89960] opened 2021-09-13 04:54 UTC
## Steps to Reproduce

1. Create new Flutter app
2. Display all text weights in a column:
```dart
for (final weight in FontWeight.values)
  Text(
    'Qwertyuiop',
    style: TextStyle(
      fontSize: 48,
      fontWeight: weight,
    ),
  ),
```
3. Optionally, use custom font

Full example: https://github.com/PiN73/test_font_weight

## Expected results
`FontWeight.w200` should display the text with "extra-light" weight which is visually between w100 and w300.

## Actual results
`FontWeight.w200` displays the text with "thin" weight, same as w100.

Default font:
![Roboto](https://user-images.githubusercontent.com/18294052/133025922-66af7918-b056-48b0-ad1f-4f482cc69278.png)

Custom font:
![Inter](https://user-images.githubusercontent.com/18294052/133025915-5a3c15e9-d5cd-4af9-9ce9-2039a10f6a3c.png)

First and second lines are the same.

Tested on:

<details>
<summary>stable, 2.5.0</summary>

```
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (5 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0
```
</details>

<details>
<summary>master, 2.5.0-7.0.pre.219</summary>

```
Flutter 2.6.0-1.0.pre.256 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0d0f7a4fb0 (25 minutes ago) • 2021-09-12 21:17:23 -0700
Engine • revision abb1980f65
Tools • Dart 2.15.0 (build 2.15.0-96.0.dev)
```
</details>

**Comment by PiN73** [comment] 2021-09-13 05:14
Here is expected result (for custom font) I achieved by adding separate family in pubspec.yaml:
```yaml
- family: Inter200
  fonts:
    - asset: fonts/Inter-ExtraLight.ttf
```

and hardcoding `fontFamily: 'Inter200'` for the second line

![Inter200](https://user-images.githubusercontent.com/18294052/133027223-bdf3ba10-f8c1-41e2-9b49-c430b86e21e9.png)

**Comment by danagbemava-nc** [comment] 2021-09-13 14:05
Issue is reproducible on latest `stable` and `master` with sample provided by OP. 

<details>
<summary>screenshot</summary>

![Simulator Screen Shot - iPhone 12 - 2021-09-13 at 14 02 47](https://user-images.githubusercontent.com/88313112/133098120-c1129e6e-0994-4f2d-b139-4185fa370cd7.png)
</details>


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.256, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.256 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0d0f7a4fb0 (7 hours ago), 2021-09-12 21:17:23 -0700
    • Engine revision abb1980f65
    • Dart version 2.15.0 (build 2.15.0-96.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by HansMuller** [comment] 2021-09-13 18:38
CC @rami-a

**Comment by guyluz11** [comment] 2023-03-11 00:15
@PiN73  I have a similar issue, maybe my workaround that I posted on the issue #122294 will work for you in the meantime.

**Comment by bleroux** [comment] 2023-03-31 08:56
This issue is no longer reproducible on Android using Flutter 3.9.0-20.0.pre.54:

<details>
<summary>Updated code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            for (final weight in FontWeight.values)
              Text(
                'Qwertyuiop',
                style: TextStyle(
                  fontSize: 48,
                  fontWeight: weight,
                ),
              ),
          ],
        ),
      ),
    );
  }
}


```
</details>

![Capture d’écran du 2023-03-31 10-03-27](https://user-images.githubusercontent.com/840911/229074360-26154cd9-7c73-436c-81a4-fd6fbdbdbcc6.png)



This code sample renders badly in Flutter Web + canvasKit but this is tracked in https://github.com/flutter/flutter/issues/75832

Closing this issue. If the problem is still reproducible on your side, feel free to comment and I will reopen the issue.

**Closed by bleroux** 2023-03-31 08:56 UTC
Labels: framework, f: material design, a: typography, has reproducible steps, found in release: 2.5, found in release: 2.6
