### ISSUE TITLE
Icons.nights_stay is not available

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#43814] opened 2019-10-30 15:17 UTC
https://material.io/resources/icons/?icon=nights_stay&style=baseline

Similar to https://github.com/flutter/flutter/issues/43747, this `Icon` is required for an app under development.

cc/ @HansMuller @willlarche

**Comment by TahaTesser** [comment] 2020-07-01 15:15
closing as duplicate of https://github.com/flutter/flutter/issues/27956

**Closed by TahaTesser** 2020-07-01 15:15 UTC
Labels: f: material design, framework
