### ISSUE TITLE
Oops; flutter has exited unexpectedly.  flutter.gradle' line: 450

### ISSUE THREAD

**Issue by gujingjing** [flutter/flutter#20609] opened 2018-08-15 02:32 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target /Users/jingjinggu/develope/longzhu/flutter/LongzhuFlutterAndroid/longzhuflutter/lib/main.dart --preview-dart-2 --target-platform android-arm64 --depfile /Users/jingjinggu/develope/longzhu/flutter/LongzhuFlutterAndroid/longzhuflutter/.android/Flutter/build/intermediates/flutter/debug/snapshot_blob.bin.d --asset-dir /Users/jingjinggu/develope/longzhu/flutter/LongzhuFlutterAndroid/longzhuflutter/.android/Flutter/build/intermediates/flutter/debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'build/app.dill' (OS Error: No such file or directory, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.5.9-pre.30, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.5.9-pre.30 at /Users/jingjinggu/develope/flutter/flutter
    • Framework revision 33c4cd0f39 (20 hours ago), 2018-08-13 23:43:49 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/jingjinggu/Library/Android/sdk
    • Android NDK at /Users/jingjinggu/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/jingjinggu/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] VS Code (version 1.26.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • HUAWEI NXT AL10 • 5LM0216122011219 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment] 2018-08-18 15:15
The title of your issue mentions a different error message than the one in the body of the issue.
Can you please clarify? Can you please post the full error output of the error this issue is about?

**Comment by zoechi** [comment] 2019-01-11 10:19
Duplicate of #20609

**Closed by zoechi** 2019-01-11 10:19 UTC
Labels: severe: crash, t: gradle, tool
