### ISSUE TITLE
[customer:money (g3)] [US] [<Platform: Android/iOS>] - Crash Signature: GrMtlGpu::insertFence-4e2ec500

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70877] opened 2020-11-19 21:36 UTC
https://b.corp.google.com/issues/173700659 for Google discussion. Conversation should occur there, please.

cc @zanderso.

**Comment by kf6gpe** [comment] 2020-11-30 16:38
There's now a screenshot on the upstream bug, but I'm not sure how useful it is.

**Comment by chinmaygarde** [comment] 2020-11-30 18:43
Will bring this up with Skia in the sync later today.

**Comment by chinmaygarde** [comment] 2020-12-02 18:44
Update: The Skia team is unable to reproduce this and looking for help with a reduced test case.

**Comment by chinmaygarde** [comment] 2020-12-07 19:01
This should be fixed by https://github.com/google/skia/commit/f557aef55f5df1666920677e0b84ce5fef425033 in Skia.

**Closed by chinmaygarde** 2020-12-07 19:01 UTC
Labels: P2, customer: money (g3), dependency: skia, engine, passed first triage, severe: fatal crash
