### ISSUE TITLE
Using whereIn operator in Flutter (Firestore)

### ISSUE THREAD

**Issue by Bryanmuloni** [flutter/flutter#59978] opened 2020-06-22 11:13 UTC
Is this the right way I am using whereIn operator for Firestore, it is not querying the data from Firestore but instead crashes with this error below.
**Help me look into it, here is my query.**

Stream<QuerySnapshot> getAnimalProductionSystemsOne(List<int> idList) {
    var reference = _fireStoreInstance
        .collection('ref-production-systems-one')
        .where("system_id", whereIn: idList == [] ? [0] : idList)
        .orderBy("system_en");
    return reference.snapshots();
  }

**This is the error I get:**
FirebaseError: [code=invalid-argument]: Invalid Query. A non-empty array is required for 'in' filters.

**Comment by iapicca** [comment] 2020-06-22 12:36
Hi @Bryanmuloni 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-22 12:36 UTC
