### ISSUE TITLE
New builds not showing up in build dashboard

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#120395] opened 2023-02-09 20:45 UTC
I'm seeing a lot of unscheduled and pending builds on the build dashboard:

![Screenshot from 2023-02-09 12-44-40](https://user-images.githubusercontent.com/7856010/217935146-1d0f73b7-316b-4905-b992-b24c3dea9c20.png)

However, looking at a particular bot, it looks like it has been consistently running and finished builds:

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-2

**Comment by drewroengoogle** [comment] 2023-02-09 21:26
It looks like there are a handful of "pending" tasks that haven't actually started yet (Possibly related to https://github.com/flutter/flutter/issues/116738). I looked at some of the tests that are "pending", and all of the bots in the associated pools are currently busy. With that being said, I'm not exactly sure why it got behind in the first place.

**Comment by godofredoc** [comment] 2023-02-09 22:10
Is this related to multiple PRs being tested for release candidate branches?

**Comment by christopherfujino** [comment] 2023-02-09 22:12
> Is this related to multiple PRs being tested for release candidate branches?

Ahh, yeah, probably!

**Comment by drewroengoogle** [comment] 2023-02-13 20:29
Lowering to P3 given the knowledge that it is related to the release candidate branch commits. The question left is how to make it clear that things not visible on the dashboard were the reason for the bot pools being so busy

**Comment by CaseyHillers** [comment] 2023-02-17 16:05
I filed https://github.com/flutter/flutter/issues/120395. Why would the release candidate branches fail to schedule any builds? This doesn't seem to be a bot busy issue

**Comment by CaseyHillers** [comment] 2023-02-23 03:35
@nehalvpatel can we promote this to P2? This is severely blocking releases and rolls. Consistently, the oncall needs to rerun 70+ builds which isn't a reasonable workaround.

**Comment by CaseyHillers** [comment] 2023-02-23 18:06
As FYI, I landed https://github.com/flutter/cocoon/pull/2471 as a mitigation for this a while back. This is still happening frequently, and is really only visible on the release branches now due to the vacuum only running against tip of tree.

**Comment by ricardoamador** [comment] 2023-02-23 23:50
@CaseyHillers can you/release team ping me when another release is opened and we hit this? Or is there another release branch in this state right now possibly that I can look at? The one I was using was a little old and I think the tasks were unstuck by the release team.

**Comment by ricardoamador** [comment] 2023-02-24 00:15
Yeah definitely not just a release branch issue. I found a currently commit with the same issue in flutter.

**Comment by ricardoamador** [comment] 2023-02-24 00:20
The top row shows the issue where builds are not being scheduled:
![image](https://user-images.githubusercontent.com/32242716/221060932-ced56813-1178-4983-8305-595871684a97.png)
Here is the amount of tasks that do not have build numbers in Datastore related to that commit:
![image](https://user-images.githubusercontent.com/32242716/221061047-e6535afa-595a-4c3d-88b4-ad3619fbb95c.png)
There are a significant number that have not been scheduled when there are idle machines that can take the build.
It appears that cocoon is not scheduling these tasks initially.

**Comment by nehalvpatel** [comment] 2023-02-24 22:12
> There are a significant number that have not been scheduled when there are idle machines that can take the build.
> It appears that cocoon is not scheduling these tasks initially.

I believe only one instance of a particular task is scheduled and run at a given time, even if there are multiple commits with that task waiting to be run. So in this case, some of the yellow tasks on the left likely finished their runs for the 3rd commit earlier, so they were able to get scheduled for the top two commits.

**Comment by ricardoamador** [comment] 2023-02-25 00:38
Some of the yellow tasks have not been run. I have found an instance where the tasks is showing as yellow but it is not in the tasks.

Here is the commit:
![image](https://user-images.githubusercontent.com/32242716/221325249-9851550c-708d-41c7-b92c-5d314e0b5071.png)

The related task:
![image](https://user-images.githubusercontent.com/32242716/221325314-0a9896d5-688c-4086-9aa8-2fbf04eae468.png)

The list of the tasks if you click the view logs:
![image](https://user-images.githubusercontent.com/32242716/221325375-cf490a49-c43e-4ab3-b4d1-e2b56c2ccd13.png)

And here is the newest log entry pertaining to that task:
![image](https://user-images.githubusercontent.com/32242716/221325423-03fc9b4e-8307-47ec-a9de-223af597b392.png)

And if you query Datastore you can see that there was no task created for the run:
![image](https://user-images.githubusercontent.com/32242716/221325554-6bda4f6a-2620-4917-92dd-ee5f69734926.png)

This is a secondary rate limit problem. We are simply generating far too much traffic. This is why cleaning up the commits works since the cleanup interval is 3 hours we have a better chance of creating the checkRun and associated build.

Eventually the builds get scheduled. The problem is github and the amount of requests we make. 

I did some research and it looks like [github.com](http://github.com/) has a hard cap for its rate limit per hour.
https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/rate-limits-for-github-apps

Which limits what you can do. It looks like since we have an Organization account that we are limited to 15,000 requests max per hour.

The other thing that is a problem is with the checkruns. You can only create a single check run at a time which is a single request. So for a post submit we make anywhere from 310 - 350 create check run requests for a single PR.

So depending on how many active requests are open we could easily hit the hard cap.

**Comment by ricardoamador** [comment] 2023-02-27 17:45
The best thing to do here is to actually read the headers and take action based on those. There are 4-5 header values that are returned that tell you what is happening when you are throttled when making a request.

**Comment by yusuf-goog** [comment] 2023-03-06 19:23
Potentially related to [#121989](https://github.com/flutter/flutter/issues/121989)

**Comment by keyonghan** [comment] 2023-03-07 18:40
Summarize a bit:
1) Original posted issue should be related to high queued number of tasks (related bug: https://github.com/flutter/flutter/issues/121989)
2) There are two issues related https://github.com/flutter/flutter/issues/120395#issuecomment-1444810718. Created corresponding bugs to track.
- Yellow boxes that are actually not scheduled: https://github.com/flutter/flutter/issues/122117
- Secondary rate limit issue from `batch-backfiller` api: https://github.com/flutter/flutter/issues/122116

With that, I am closing this one in favor of the above two.

**Closed by keyonghan** 2023-03-07 18:40 UTC
Labels: passed secondary triage, P2
