### ISSUE TITLE
Include Xcodeproj files in initial Flutter app template

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#390] opened 2015-11-16 21:31 UTC
When we generate a new Flutter app in our tools, we could also generate all the necessary Xcodeproj files. This could help our new Flutter devs get started on iOS easier/faster.

**Comment by sethladd** [comment] 2015-11-16 21:31
cc @chinmaygarde

**Comment by eseidelGoogle** [comment] 2015-11-16 21:54
We might have both filed the same bug? https://github.com/flutter/flutter/issues/391

**Comment by chinmaygarde** [comment] 2015-12-08 00:11
Dupe of #391. Closing.

**Closed by chinmaygarde** 2015-12-08 00:11 UTC
Labels: ⌺‬ platform-ios
