### ISSUE TITLE
[tool_crash] Bad state: StreamSink is closed

### ISSUE THREAD

**Issue by leo848** [flutter/flutter#55960] opened 2020-04-29 15:05 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: StreamSink is closed
```
#0      _StreamSinkImpl.add (dart:io/io_sink.dart:156:7)
#1      _Socket.add (dart:io-patch/socket_patch.dart:1868:38)
#2      _DetachedSocket.add (dart:_http/http_impl.dart:3070:13)
#3      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:60:11)
#4      ByteConversionSinkBase.addSlice (dart:convert/byte_conversion.dart:45:5)
#5      _Utf8EncoderSink.addSlice (dart:convert/utf.dart:267:13)
#6      StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#7      SseConnection._setUpListener (package:sse/src/server/sse_handler.dart:73:15)
<asynchronous suspension>
#8      new SseConnection (package:sse/src/server/sse_handler.dart:53:15)
#9      SseHandler._createSseConnection.<anonymous closure> (package:sse/src/server/sse_handler.dart:161:26)
#10     _fromHttpRequest.onHijack.<anonymous closure> (package:shelf/shelf_io.dart:146:35)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel beta, v1.17.0-3.3.pre, on Microsoft Windows [Version 10.0.18362.778], locale
    de-DE)
    • Flutter version 1.17.0-3.3.pre at C:\src\flutter
    • Framework revision 0da1ab0922 (21 hours ago), 2020-04-28 11:02:34 -0700
    • Engine revision 376ad6a64b
    • Dart version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Norman\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Norman\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Norman\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.44.2)
    • VS Code at C:\Users\Norman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 0da1ab09224f6c6d69fcff1195a3662fe7ad7534

**Comment by iapicca** [comment] 2020-04-30 07:25
Hi @leo848 
can you please provide your full `flutter run -d chrome --verbose`
(if it's lengthy you may attach it as txt file) 
and  a reproducible minimal code sample.
Thank you

**Comment by leo848** [comment] 2020-04-30 07:40
It all runs correctly, but then suddenly after a hot restart with bigger changes (e.g. add TextStyle to Text) Flutter crashes.

This is my flutter run -d chrome --verbose:
[flutter run -d chrome --verbose.txt](https://github.com/flutter/flutter/files/4556758/flutter.run.-d.chrome.--verbose.txt)

This is my code, very basic:
```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(home: First()),
    );

class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "To-Do-App",
          style: TextStyle(
              decoration: TextDecoration
                  .underline,
              fontFamily: "Consolas"),
        ),
      ),
      body: Text(
        "Body",
        style: TextStyle(
          fontSize: 24.0,
          decoration:
              TextDecoration.underline,
          fontFamily: "Consolas",
        ),
      ),
    );
  }
}

**Comment by leo848** [comment] 2020-04-30 07:42
And here is the log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d chrome --verbose

## exception

StateError: Bad state: StreamSink is closed

```
#0      _StreamSinkImpl.add (dart:io/io_sink.dart:156:7)
#1      _Socket.add (dart:io-patch/socket_patch.dart:1868:38)
#2      _DetachedSocket.add (dart:_http/http_impl.dart:3070:13)
#3      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:60:11)
#4      ByteConversionSinkBase.addSlice (dart:convert/byte_conversion.dart:45:5)
#5      _Utf8EncoderSink.addSlice (dart:convert/utf.dart:267:13)
#6      StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#7      SseConnection._setUpListener (package:sse/src/server/sse_handler.dart:73:15)
<asynchronous suspension>
#8      new SseConnection (package:sse/src/server/sse_handler.dart:53:15)
#9      SseHandler._createSseConnection.<anonymous closure> (package:sse/src/server/sse_handler.dart:161:26)
#10     _fromHttpRequest.onHijack.<anonymous closure> (package:shelf/shelf_io.dart:146:35)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.17.0-3.3.pre, on Microsoft Windows [Version
    10.0.18362.778], locale de-DE)
    • Flutter version 1.17.0-3.3.pre at C:\src\flutter
    • Framework revision 0da1ab0922 (2 days ago), 2020-04-28 11:02:34 -0700
    • Engine revision 376ad6a64b
    • Dart version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at C:\Users\Norman\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Norman\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Norman\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for
      detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.44.2)
    • VS Code at C:\Users\Norman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2020-04-30 11:01
related to https://github.com/flutter/flutter/issues/48014

**Comment by jonahwilliams** [comment] 2020-05-02 00:23
Duplicate of https://github.com/dart-lang/webdev/issues/943

**Closed by jonahwilliams** 2020-05-02 00:23 UTC
Labels: found in release: 1.17, has reproducible steps, platform-web, severe: crash, tool
