### ISSUE TITLE
AnimatedCrossFade does not resize as expected when state change triggered offscreen

### ISSUE THREAD

**Issue by zzzev** [flutter/flutter#19012] opened 2018-07-02 21:34 UTC
## Steps to Reproduce

1. Create an app that uses an `AnimatedCrossFade` widget to transition between two widgets with different sizes.
2. Trigger a change in `crossFadeState` while on a different screen
3. Return to screen with `AnimatedCrossFade`; the correct widget will be shown, but the size can be incorrect.

Here's a simplified Dart app that displays the problem; in this app there are two screens. The `HomeScreen` widget contains an `AnimatedCrossFade` that swaps between a large orange square and a small blue square, starting on orange, with the `crossFadeState` stored as state on `HomeScreenState`. The FAB toggles between the two, and works as expected on this screen (orange fades to blue, and tweens between sizes during animation). However, if you tap the `RaisedButton` to go to the second screen, and then tap the FAB (which invokes the same callback as on the first screen), then hit the **back button**, the `HomeScreen` displays the blue square, but with enough space to show the orange square (lots of whitespace, which doesn't show up if this is updated from the same screen).

Here's the code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      theme: new ThemeData(),
      home: new HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  HomeScreen({Key key}) : super(key: key);

  @override
  HomeScreenState createState() => new HomeScreenState();
}

class HomeScreenState extends State<HomeScreen> {
  CrossFadeState crossFadeState = CrossFadeState.showFirst;

  void _toggleShown() {
    setState(() {
      if (crossFadeState == CrossFadeState.showFirst) {
        crossFadeState = CrossFadeState.showSecond;
      } else {
        crossFadeState = CrossFadeState.showFirst;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Center(
          child: new Column(
        children: <Widget>[
          new AnimatedCrossFade(
              firstChild: new Container(
                color: Colors.orange,
                height: 200.0,
                width: 200.0,
              ),
              secondChild: new Container(
                color: Colors.blue,
                height: 10.0,
                width: 10.0,
              ),
              crossFadeState: crossFadeState,
              duration: const Duration(milliseconds: 100)),
          new RaisedButton(
            child: Text('Next page'),
            onPressed: () => Navigator.of(context).push(new MaterialPageRoute(
                builder: (context) => new SecondScreen(_toggleShown))),
          )
        ],
      )),
      floatingActionButton: new FloatingActionButton(
        onPressed: _toggleShown,
        tooltip: 'toggle',
        child: new Icon(Icons.swap_horiz),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  final VoidCallback _toggleShown;

  SecondScreen(this._toggleShown);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: _toggleShown,
        child: Icon(Icons.swap_horiz),
      ),
    );
  }
}
```

Please note that this is a contrived example to make it easy to repro; the actual scenario is a bit more complex, and precludes using e.g. the route's return value to update the state.

## Logs

This is an internal bug for project mulligan. No logging occurs during the repro steps.

**Comment by zoechi** [comment] 2018-07-03 07:00
Please add the output of `flutter doctor`.

**Comment by zoechi** [comment] 2019-01-24 12:06
Still reproduces
```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by filiph** [comment] 2020-02-19 05:41
Still reproduces on 

    Flutter 1.12.13+hotfix.8 • channel stable •

Since the size can be 0 in any of the dimensions (e.g. AnimatedCrossFade is used to "animate in" a message or a button), this leads to states of the app when an important part of the UI is completely missing (it's in the tree, but AnimatedCrossFade is hiding it). So this is not just a visual glitch.

**Comment by filiph** [comment] 2020-02-19 05:42
(A workaround is to use `AnimatedSwitcher`, for example.)

**Comment by markusaksli-nc** [comment] 2020-07-28 08:48
No longer reproduces on either latest stable `v1.17.5` or latest master `1.21.0-6.0.pre.41`.
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-6.0.pre.41, on Microsoft Windows [Version 10.0.18362.959], locale et-EE)
    • Flutter version 1.21.0-6.0.pre.41 at C:\Development\flutter_master
    • Framework revision 39fa00201d (5 hours ago), 2020-07-27 21:11:43 -0700
    • Engine revision f27729e97b
    • Dart version 2.10.0 (build 2.10.0-0.0.dev 24c7666def)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.959]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

Closing as probably fixed.

**Closed by markusaksli-nc** 2020-07-28 08:48 UTC
Labels: P4, a: animation, customer: mulligan (g3), framework
