### ISSUE TITLE
Flutter attach crash: NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null at package:flutter_tools/src/commands/attach.dart

### ISSUE THREAD

**Issue by gscool** [flutter/flutter#32471] opened 2019-05-10 07:36 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter attach

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null.
Receiver: null
Tried calling: port

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:219:78)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at /Users/guoshun/sdk/flutter
    [32m•[39m Framework revision 7a4c33425d (11 days ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/guoshun/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[33m[!][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [31m✗[39m Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.6.1

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 35.3.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin version 33.4.2
    [32m•[39m Dart plugin version 183.5912.23

[32m[✓][39m VS Code (version 1.33.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.0.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xʀ • AD7514E0-D696-44FC-9632-C35C3E3E7994 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[33m![39m Doctor found issues in 1 category.
```

=========================================

I try again and again by use "brew update;brew uninstall --ignore-dependencies libimobiledevice;brew uninstall --ignore-dependencies usbmuxd;brew install --HEAD usbmuxd;brew unlink usbmuxd;brew link usbmuxd;brew install --HEAD libimobiledevice;brew install ideviceinstaller",but "flutter doctor" command allways show me 
"Verify that all connected devices have been paired with this computer in Xcode".

I Use "flutter attach" command in order to debug.but show me "Checking for advertised Dart observatories...
Checking for available port on xxx._dartobservatory._tcp.local
Checking for authentication code for xxx._dartobservatory._tcp.local
This is taking longer than expected...".

I use "flutter attach --profile",the same as above.

**Comment by gaara87** [comment] 2019-05-10 20:39
Concating my logs:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color attach --machine --device-id=5D8EC0CF-CD9F-482D-AFF3-AF415C1224DC lib/main.dart

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null.
Receiver: null
Tried calling: port

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:219:78)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/ramaniar/workspace/flutter
    • Framework revision 7a4c33425d (11 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ramaniar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • iPhone Xʀ • 5D8EC0CF-CD9F-482D-AFF3-AF415C1224DC • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by gaara87** [comment] 2019-05-10 20:42
Related to #32189  and #31975

**Comment by PangYiMing** [comment] 2019-05-23 10:57
https://github.com/flutter/flutter/issues/31854

you can switch your branch to master:

flutter channel master
flutter upgrade

**Comment by StoneN** [comment] 2019-06-28 06:56
The same problem, Have you solved it?

**Comment by gscool** [comment] 2019-07-02 06:56
> The same problem, Have you solved it?

No

**Comment by jmagman** [comment] 2020-01-11 00:07
Duplicate of https://github.com/flutter/flutter/issues/40225.

**Closed by jmagman** 2020-01-11 00:07 UTC
Labels: tool
