### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by nazarpunk** [flutter/flutter#155319] opened 2024-09-17 19:44 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008101-001548423AB9001E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-x64, locale en-UA)
    • Flutter version 3.24.3 on channel stable at /Users/nazarpunk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nazarpunk/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nazarpunk/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Users/nazarpunk/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.1)
    • IntelliJ at /Users/nazarpunk/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.21829.3

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 00008101-001548423AB9001E • ios            • iOS 18.0 22A3354
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 15.0 24A335 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+378
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
app_links-6.3.2
app_links_linux-1.0.3
app_links_web-1.0.4
camera-0.11.0+2
camera_android_camerax-0.6.8+3
camera_avfoundation-0.9.17+3
camera_web-0.3.5
device_info_plus-10.1.2
facebook_auth_desktop-2.1.1
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_core-3.5.0
firebase_core_web-2.18.1
firebase_messaging-15.1.2
firebase_messaging_web-3.9.1
flutter_app_badge-2.0.2
flutter_facebook_auth-7.1.1
flutter_facebook_auth_web-6.1.2
flutter_native_splash-2.4.1
flutter_plugin_android_lifecycle-2.0.22
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
google_sign_in-6.2.1
google_sign_in_android-6.1.30
google_sign_in_ios-5.7.7
google_sign_in_web-0.12.4+2
gtk-2.1.0
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
local_auth-2.3.0
local_auth_android-1.0.44
local_auth_darwin-1.4.0
local_auth_windows-1.0.11
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sign_in_with_apple-6.1.2
sign_in_with_apple_web-2.1.0
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2

**Comment by danagbemava-nc** [comment] 2024-09-18 06:35
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131. If you have any additional information about how to consistently reproduce the issue, kindly leave a comment in the original issue. 

Thank you

**Closed by danagbemava-nc** 2024-09-18 06:35 UTC
Labels: in triage
