### ISSUE TITLE
[Impeller] Expose dashed path effect.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#112981] opened 2022-10-05 21:46 UTC
Impeller will be able to do path dashing much more quickly than the concerns we had with Skia.

This should be low priority, but the current methods of dashing a path in Flutter involve measuring the path and manually applying dashes. This is much slower than what Impeller would be able to do in its shader setup, because it's already creating a polyline and deals with things like this for handling moves.

Prior context is at https://github.com/flutter/flutter/issues/4858

/cc @hixie @chinmaygarde

**Comment by dnfield** [comment] 2022-10-05 21:46
(to be clear: there's no intention to work on this for at least the next quarter, but don't want to forget about it either).

**Comment by modulovalue** [comment] 2023-02-07 19:50
There are various fidelity related issues that can come up if users are forced to do the dashing themselves.
Consider the gif here: https://github.com/dnfield/flutter_path_drawing/issues/13 (easy to fix), and the example here: https://github.com/dnfield/flutter_path_drawing/issues/12 (not easy to fix)

**Comment by modulovalue** [comment] 2023-02-07 19:55
Certain use cases (such as drawing arrows) require path metrics. It is common to paint dashed arrows. I hope that duplicate work i.e. calculating the path metrics multiple times (once for the arrowhead, and once for its body), can be avoided in those cases. (https://github.com/dnfield/flutter_path_drawing/issues/16)

**Comment by chinmaygarde** [comment] 2023-02-07 23:53
@dnfield Closing this as a duplicate of https://github.com/flutter/flutter/issues/110723. I've cross referenced these and gone though the comments to ensure I didn't miss any context. That bug has some details related to performance of repeated draws so I'm favoring that. Feel free to re-open if you think these should be separate still.

**Closed by chinmaygarde** 2023-02-07 23:53 UTC
Labels: new feature, engine, P5, impeller
