### ISSUE TITLE
A Widget containing a Draggable can't be tapped.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1185] opened 2016-01-11 18:59 UTC
I'd like to have a Widget that can be tapped and/or dragged.  The Draggable steals the tap currently.

**Comment by Hixie** [comment] 2016-01-11 20:47
This is a dupe of https://github.com/flutter/flutter/issues/996 which has a discussion of possible solutions.

**Closed by Hixie** 2016-01-11 20:47 UTC
Labels: affects: framework, customer: pink
