### ISSUE TITLE
Exception: Release mode is not supported for iPhone 12 Pro Max

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#90736] opened 2021-09-26 01:10 UTC
Exception: Release mode is not supported for iPhone 12 Pro Max
See below:
![e92e64f954c08fbd7b8b1812fc88612](https://user-images.githubusercontent.com/91245043/134789712-1d3798f8-73f2-4dd2-9fa0-202d2f087101.jpg)

flutter doctor -v
![image](https://user-images.githubusercontent.com/91245043/134789746-58b98d04-a3ca-4674-9805-67bf46731745.png)

**Comment by maheshmnj** [comment] 2021-09-27 09:41
Hi @gionlime Thanks for filing the issue, It looks fishy here. Please note that you cannot build an ios app on windows and you need a mac to build for ios so I believe this is working as intended.

Thanks

**Comment by maheshmnj** [comment] 2021-09-27 09:51
If you are trying to run the app on the ios simulator on mac in release mode, it's not supported as well Here's the related issue https://github.com/flutter/flutter/issues/11754

Closing as working as intended if you disagree fee free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-27 09:51 UTC
Labels: in triage
