### ISSUE TITLE
A TextField wrapped inside a SelectionArea un focuses and focues on tap

### ISSUE THREAD

**Issue by EduardDumitrescu** [flutter/flutter#121198] opened 2023-02-22 08:43 UTC
On Flutter version 3.7.3, if we have a Textfield wrapped inside a SelectionArea, if the textfield is focused and we tap on it, it gets defocused and focused again.

## Steps to Reproduce

1. Create a simple flutter app with a textfield wrapped inside of a selection area
2. Tap on the textfield so it becomes focused
3. While it is focused tap on it again

**Expected results:** Nothing should happen

**Actual results:** The textfield gets unfocused and then focused.

<details>
<summary>Code sample</summary>

```import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final FocusNode focusNode = FocusNode();

  @override
  void initState() {
    super.initState();

    focusNode.addListener(
      () => print('Focus called: ${focusNode.hasFocus} '
          '${focusNode.hasPrimaryFocus}'),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SelectionArea(
        child: Center(
          child: TextField(focusNode: focusNode),
        ),
      ),
    );
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```No error/warning logs are present in the logs
```

```
```

```
```

</details>

**Comment by exaby73** [comment] 2023-02-22 10:39
## Triage report

I can reproduce this issue on `Master (3.8.0-14.0.pre.25)`.

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const SelectionArea(
        child: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Video demonstration</summary>

https://user-images.githubusercontent.com/50555895/220595953-1bb8144e-f790-4d76-9f02-f41caab1f898.mp4

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.8.0-14.0.pre.25, on Ubuntu 22.04.2 LTS 5.15.0-60-generic, locale en_US.UTF-8)
    • Flutter version 3.8.0-14.0.pre.25 on channel master at /home/exabyt3/fvm/versions/master
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/exabyt3/fvm/versions/master. Consider adding /home/exabyt3/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4c25587b71 (6 hours ago), 2023-02-21 16:10:25 -0800
    • Engine revision 3aa112c75c
    • Dart version 3.0.0 (build 3.0.0-261.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/exabyt3/Android/Sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /home/exabyt3/Android/Sdk
    • Java binary at: /home/exabyt3/programs/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/brave-browser

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/exabyt3/programs/android-studio
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.2 LTS 5.15.0-60-generic
    • Chrome (web)    • chrome • web-javascript • Brave Browser 110.1.48.164

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by exaby73** [comment] 2023-02-22 12:22
Closing as a duplicate of https://github.com/flutter/flutter/issues/107327

**Closed by exaby73** 2023-02-22 12:22 UTC
Labels: framework, has reproducible steps, f: selection, found in release: 3.7, found in release: 3.8
