### ISSUE TITLE
MissingPluginException for method authenticateWithBiometrics on channel plugins.flutter.io/local_auth for iOS

### ISSUE THREAD

**Issue by epf84** [flutter/flutter#80174] opened 2021-04-10 04:06 UTC
Hi, I'm getting an error when trying to use FaceId on the **iOS** emulator.

### Error message:

**[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method authenticateWithBiometrics on channel plugins.flutter.io/local_auth)**

## Steps to Reproduce

1. Run `flutter doctor -v`.

>  [✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-BR)
>     • Flutter version 1.22.6 at /Users/user/install/flutter
>     • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
>     • Engine revision 2f0af37152
>     • Dart version 2.10.5
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
>       You may also want to add it to your PATH environment variable.
> 
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.4)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.4, Build version 12D4e
>     • CocoaPods version 1.10.1
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
> 
> [✓] VS Code (version 1.55.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.21.0
> 
>  
> [!] Connected device                          
>     ! No devices available
> 
> ! Doctor found issues in 3  categories.
> 

2. Update the files as follows: 
**Info.plist**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>faceid_auth_test</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSFaceIDUsageDescription</key>
	<string>Authenticate by using face id</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

**pubspec.yaml**

```
name: faceid_auth_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  local_auth: ^0.6.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**XCode version: Version 12.4 (12D4e)**

**Emulator version: iPhone 11**

**Please, can anyone help me?**

**Thanks.**

**Comment by iapicca** [comment] 2021-04-10 15:21
> [✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-BR)

>   local_auth: ^0.6.3+4

@epf84 
your set up seems a bit outdated,
can you please run `flutter upgrade -f` and use the latest version of [local_auth](https://pub.dev/packages/local_auth): `^1.1.4`

if the issue persists
please provide your **_updated_** `flutter doctor -v`, your `flutter run -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by epf84** [comment] 2021-04-10 16:52
> > [✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-BR)
> 
> > local_auth: ^0.6.3+4
> 
> @epf84
> your set up seems a bit outdated,
> can you please run `flutter upgrade -f` and use the latest version of [local_auth](https://pub.dev/packages/local_auth): `^1.1.4`
> 
> if the issue persists
> please provide your **_updated_** `flutter doctor -v`, your `flutter run -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

@iapicca Exactly the same code (same local_auth version, same XCode version and same flutter version) works well in another Macbook Pro (Model 2018).

On Macbook Pro (Model 2012) doesn't works, simple like that. It generates the error message as mentioned.

Its kind weird in fact, I know but do you have any idea?

1  -  Macbook 2012, same code doesn't works.
2  - Macbook 2018, same code works well.

Im using device IOS for testing in both Macbooks. IPhone 11 (version 14).

Thanks in advance.

**Comment by iapicca** [comment] 2021-04-10 17:08
> Exactly the same code (same local_auth version, same XCode version and same flutter version) works well in another Macbook Pro (Model 2018).

@epf84 
please consider that 
- fixes may (or may not) be already shipped in the `latest version` of both flutter and [local_auth](https://pub.dev/packages/local_auth)
- for the issue to be workble need to be reproducible please provide the information mentioned [above](https://github.com/flutter/flutter/issues/80174#issuecomment-817152745), not a code snippet

> can you please run `flutter upgrade -f` and use the latest version of [local_auth](https://pub.dev/packages/local_auth): `^1.1.4`
> 
> if the issue persists
> please provide your **_updated_** `flutter doctor -v`, your `flutter run -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by epf84** [comment] 2021-04-11 23:30
> > Exactly the same code (same local_auth version, same XCode version and same flutter version) works well in another Macbook Pro (Model 2018).
> 
> @epf84
> please consider that
> 
> * fixes may (or may not) be already shipped in the `latest version` of both flutter and [local_auth](https://pub.dev/packages/local_auth)
> * for the issue to be workble need to be reproducible please provide the information mentioned [above](https://github.com/flutter/flutter/issues/80174#issuecomment-817152745), not a code snippet
> 
> > can you please run `flutter upgrade -f` and use the latest version of [local_auth](https://pub.dev/packages/local_auth): `^1.1.4`
> > if the issue persists
> > please provide your **_updated_** `flutter doctor -v`, your `flutter run -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

@iapicca I appreciate your answer but when I updated flutter to latest version appeared over than 700 error messages basically because null safety.

I run flutter doctor -v and I checked it that flutter and dart was updated correctly but the errors about null safety should take a lot of time to be solved.

Unfortunately I can't use iOS emulator from my Macbook and I'll still looking for a solution. If I get it to check the solution I'll let you guys know about it.

Thank you.

PS.: I'm try to use that another Macbook that allows the entire code works well with the same code. Perhaps with more time I try to use update approach again and try to solve that bunch of error about null safety.

**Comment by darshankawar** [comment] 2021-04-12 07:51
@epf84 
Can you try the official local_auth plugin [example](https://github.com/flutter/plugins/tree/master/packages/local_auth/example) on same setup and see if you get same issue ?

**Comment by epf84** [comment] 2021-04-14 00:35
> example
Hi @darshankawar I'll try that and let you know.

I'm using https://pub.dev/packages/local_auth with 0.6.3+4 version. Is this an official plugin?

Sorry but I'm confused now, please what link or version I supposed to use here? Your example link it is a github and I don't know what I need do to exactly.

Please could you give more details?

Thanks in advance.

**Comment by darshankawar** [comment] 2021-04-14 07:16
@epf84 
Per your earlier comment, it works on MBP 2018, but not in 2012, so we are not sure how to debug or address it, since 2012 is very old machine and may have become obsolete already, so if with current machine it's running properly, should this be still considered an issue ?

Regarding plugin version, latest version is https://pub.dev/packages/local_auth/install and you may simply copy paste the example code given here and check if you still get the same error or not. https://pub.dev/packages/local_auth/example

**Comment by pedromassangocode** [comment] 2021-05-07 11:07
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 11:07 UTC
Labels: in triage, waiting for customer response
