### ISSUE TITLE
Merge bot never landed a pull request

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#99965] opened 2022-03-11 10:16 UTC
It seems like the bot stuck in landing the https://github.com/flutter/flutter/pull/95757.

The https://github.com/flutter/flutter/labels/waiting%20for%20tree%20to%20go%20green label was applied 20 days ago, and since then, the bot didn't say anything, until there appeared a merge conflict, after which it said it couldn't land it.

cc @godofredoc

**Comment by godofredoc** [comment] 2022-03-11 18:53
This is a known issue where GraphQL is not scaling to our needs. We are working on a new version of the bot and it will be ready by mid April.

**Comment by godofredoc** [comment] 2022-03-11 18:53
\cc @keyonghan @CaseyHillers

**Comment by CaseyHillers** [comment] 2022-03-14 15:03
Duplicate of https://github.com/flutter/flutter/issues/96836#issuecomment-1029251155

**Closed by CaseyHillers** 2022-03-14 15:03 UTC
Labels: passed first triage, team: infra
