### ISSUE TITLE
SelectableText.rich on web double renders selection and in the wrong position

### ISSUE THREAD

**Issue by nateonguitar** [flutter/flutter#142410] opened 2024-01-28 17:13 UTC
### Steps to reproduce

Create a `SelectableText.rich()` widget with a large input string and highlight different sections of the text.

### Expected results

The selected text should be in the exact same position and have the exact same characters as the source text with only a single highlight, especially without the second, wrong highlight.

### Actual results

I've had complaints on my Flutter web project from users that selecting text produces a secondary blue highlight that's not even the correct highlight.

Here are 5 screenshots from the exact same `SelectableText.rich()` with a single child `TextSpan` with with about 2.5 paragraphs worth of text in it after deploying to firebase hosting. This is different portions of the same text body from the same user in the same session.

The only style applied to the `SelectableText.rich()` is:
```
TextStyle(
  fontSize: 16,
  color: Color(0xDCEBEBEB),
);
```

![image](https://github.com/flutter/flutter/assets/19334124/50abfc07-2386-4f36-a4f8-909fbdd2f1d1)
![image](https://github.com/flutter/flutter/assets/19334124/45f1050b-e34e-4d9b-af8b-5126623da0d8)
![image](https://github.com/flutter/flutter/assets/19334124/4a481df0-f7d1-4c8e-96a3-4ad8e4a6a807)
![image](https://github.com/flutter/flutter/assets/19334124/8a1a3a18-f8ae-4321-9be8-545061dcb58e)
![image](https://github.com/flutter/flutter/assets/19334124/c246065b-f1ea-4490-a79f-36096525437b)

As you can see, it produces an extra blue layer that gets progressively worse the farther into the text the user highlights.

Here is a screenshot of the exact same application in my local dev environment, as you can see, no issues, and it doesn't highlight blue (the green was what I was expecting).

![image](https://github.com/flutter/flutter/assets/19334124/7daef47d-dbe3-4cb7-b13e-a74e2fa6f33a)

All tests were done on Chrome using `--web-renderer canvaskit` both in production and local dev.

This is on the stable channel, tested both on `3.16.7` yesterday and today on `3.16.9` after running `flutter upgrade`.

I cannot seem to reproduce it outside of deploying the application.

### Code sample

Note that this code does not trigger the issue locally in development mode, I only see the issue on the production release.  Both production and local I used `--web-renderer canvaskit`

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Selectable Text',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Selectable Text'),
      ),
      body: const Center(
        child: SelectableText.rich(
          TextSpan(
            text: ''
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
                'Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Augue lacus viverra vitae congue eu. '
                'Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. '
                'Proin nibh nisl condimentum id venenatis a condimentum. Enim praesent elementum facilisis leo. '
                'Porttitor massa id neque aliquam vestibulum morbi blandit. Iaculis nunc sed augue lacus. '
                'Proin libero nunc consequat interdum. Nulla porttitor massa id neque aliquam vestibulum morbi blandit. '
                'Tellus at urna condimentum mattis pellentesque id. Arcu felis bibendum ut tristique et. '
                'Mi ipsum faucibus vitae aliquet nec. Lacus viverra vitae congue eu consequat ac. '
                'Sed arcu non odio euismod lacinia at quis risus sed. Vitae congue mauris rhoncus aenean vel elit scelerisque. '
                'Quis hendrerit dolor magna eget est. Massa id neque aliquam vestibulum morbi blandit cursus risus. '
                'Tellus pellentesque eu tincidunt tortor aliquam nulla.'
                '\n\n'
                'Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Aliquam sem et tortor consequat. '
                'Ullamcorper morbi tincidunt ornare massa eget. Rhoncus mattis rhoncus urna neque. '
                'Et sollicitudin ac orci phasellus egestas tellus. Sem fringilla ut morbi tincidunt augue interdum velit. '
                'Placerat orci nulla pellentesque dignissim enim sit. Nam libero justo laoreet sit amet cursus sit amet. '
                'Non arcu risus quis varius quam quisque id diam. Donec massa sapien faucibus et molestie ac feugiat sed. '
                'Nulla pellentesque dignissim enim sit amet venenatis urna. Malesuada fames ac turpis egestas sed tempus. '
                'Sit amet est placerat in egestas erat imperdiet. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. '
                'Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. In fermentum posuere urna nec tincidunt. '
                'Enim diam vulputate ut pharetra sit amet aliquam id diam.'
                '\n\n'
                'Non enim praesent elementum facilisis leo vel fringilla est. Dignissim convallis aenean et tortor at risus viverra. '
                'Morbi tristique senectus et netus et malesuada. Leo urna molestie at elementum eu facilisis sed odio. '
                'Nec sagittis aliquam malesuada bibendum arcu. Fermentum leo vel orci porta non pulvinar. '
                'Metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Diam maecenas ultricies mi eget mauris. '
                'Libero justo laoreet sit amet cursus sit. Aenean euismod elementum nisi quis. '
                'Vel quam elementum pulvinar etiam non quam lacus. Fringilla ut morbi tincidunt augue interdum velit euismod in. '
                'Viverra mauris in aliquam sem. Ultricies lacus sed turpis tincidunt. Nisl vel pretium lectus quam id leo. '
                'Ut aliquam purus sit amet luctus venenatis lectus magna. Netus et malesuada fames ac turpis. '
                'Consequat id porta nibh venenatis cras sed felis eget velit. '
                'Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. '
                'Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus.'
                '\n\n'
                'Risus feugiat in ante metus dictum at tempor. A erat nam at lectus urna duis. Sed viverra ipsum nunc aliquet bibendum. '
                'Sem integer vitae justo eget magna fermentum. Aliquam id diam maecenas ultricies mi. '
                'Ultricies integer quis auctor elit sed vulputate mi sit. Elementum tempus egestas sed sed risus pretium. '
                'Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. '
                'At tellus at urna condimentum mattis. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. '
                'Cum sociis natoque penatibus et. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. '
                'Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Orci ac auctor augue mauris augue neque gravida. '
                'Mattis rhoncus urna neque viverra justo nec ultrices. Id donec ultrices tincidunt arcu non sodales neque sodales ut. '
                'Lectus quam id leo in vitae. Adipiscing commodo elit at imperdiet dui accumsan sit amet. '
                'Habitasse platea dictumst quisque sagittis purus sit amet volutpat.',
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/19334124/50abfc07-2386-4f36-a4f8-909fbdd2f1d1)
![image](https://github.com/flutter/flutter/assets/19334124/45f1050b-e34e-4d9b-af8b-5126623da0d8)
![image](https://github.com/flutter/flutter/assets/19334124/4a481df0-f7d1-4c8e-96a3-4ad8e4a6a807)
![image](https://github.com/flutter/flutter/assets/19334124/8a1a3a18-f8ae-4321-9be8-545061dcb58e)
![image](https://github.com/flutter/flutter/assets/19334124/c246065b-f1ea-4490-a79f-36096525437b)

</details>

### Logs

There are no hints or errors, everything looks normal in the logs.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2024-01-29 10:45
Thanks for filing this @nateonguitar.
I tried reproducing this but can't reproduce it locally as well. I also tried deploying to a web server using `ngrok` but couldn't reproduce as well. I see from your comment that it occurs only in production, I'll be labelling this for more insights from the team.
Thank you!

<details><summary>flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.16.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (4 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile) • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 Pro (mobile)     • 79E44FCE-BEA4-4C4B-9C1C-EFBD9964E172 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by nateonguitar** [comment] 2024-01-29 18:10
Don't know how helpful it is, but this happens on my coworker's computer who is running Windows 10, it was also happening on my Windows 10 at home. My work machine, Linux Mint, is not showing the extra blue layer.

**Comment by nateonguitar** [comment] 2024-01-29 18:31
Another hint, I just tried it on an M1 Mac Studio, the blue layer shows. This was also using Chrome.

**Comment by htoor3** [comment] 2024-02-08 18:33
Thank you for the details here.  I wasn't able to reproduce the issue and I'm on Macbook Pro (Sonoma) on either Chrome, Firefox, or Safari, for either gametabs.net or a locally deployed app.  It looks like the underlying textarea content isn't being hidden correctly.

Thank you for the additional details @nateonguitar.  The issue doesn't seem to be browser or platform specific.  Is there a discrepancy in the Chrome version for those that were able to reproduce it and those that weren't?  Or is there some kind of accessibility setting that's forcing the underlying input to render its highlight for the coworkers that can repro the issue?

**Comment by nateonguitar** [comment] 2024-02-19 05:10
Hi there, I'm not in a position to re-run the gambit of tests again on a lot of different devices. I'll give it a try when I get the chance but it may be a few days, or a week.

This issue could have been resolved already, I'm not seeing it on my own computer (where I was able to trigger the issue). I will have access to the mac where I was able to reproduce the issue in a few days at the minimum.

I don't know how related to the chrome version it is though, as it also happened on FireFox on one device.

**Comment by htoor3** [comment] 2024-02-26 19:42
@nateonguitar thanks for the update.  It's possible the issue resolved on its own.  I'll close the issue for now, but if you're able to consistently reproduce it, feel free to open the issue back up and add those details so we can take a look.

**Closed** 2024-02-26 19:42 UTC
Labels: framework, a: typography, platform-web, team-web
