### ISSUE TITLE
ExcludeFocus can still allow focus

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#61700] opened 2020-07-17 06:25 UTC
## Steps to reproduce

1. Run the following app:

```dart
import 'dart:ui' show window;

import 'package:flutter/material.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatefulWidget {
  @override
  _BugReportState createState() => _BugReportState();
}

class _BugReportState extends State<BugReport> {
  bool blockFocus = false;

  _toggleBlockFocus() {
    setState(() {
      blockFocus = !blockFocus;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Actions(
      actions: WidgetsApp.defaultActions,
      child: Localizations(
        locale: Locale('en', 'US'),
        delegates: [
          DefaultWidgetsLocalizations.delegate,
          DefaultMaterialLocalizations.delegate,
        ],
        child: MediaQuery(
          data: MediaQueryData.fromWindow(window),
          child: Navigator(
            onGenerateRoute: (RouteSettings settings) {
              return MaterialPageRoute<void>(
                settings: settings,
                builder: (BuildContext context) {
                  return Material(
                    child: ExcludeFocus(
                      excluding: blockFocus,
                      child: Column(
                        children: [
                          TextField(),
                          TextField(),
                          OutlineButton(
                            onPressed: () => _toggleBlockFocus(),
                            child: Text(blockFocus ? 'Allow focus' : 'Block focus'),
                          ),
                        ],
                      ),
                    ),
                  );
                },
              );
            },
          ),
        ),
      ),
    );
  }
}
```

2. Focus the second text field.
3. Click the button to turn on excluding of focus

## Expected behavior

You expect focus to be lost completely, since all three UI elements are wrapped in a `ExcludeFocus` with `excluding` set to true.

## Actual behavior

The focus transfers from the second text field to the first one.

## Other info

This was spawned from https://github.com/flutter/flutter/issues/61659 and is observable on Android, iOS, and macOS, but it doesn't reproduce on web.  Here's what versions I'm synced to:

```
$ flutter doctor -v
[✓] Flutter (Channel master, 1.21.0-2.0.pre.51, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.21.0-2.0.pre.51 at /Users/tvolkert/project/flutter/flutter
    • Framework revision df542b6831 (5 hours ago), 2020-07-16 18:32:46 -0700
    • Engine revision d3b81f19fc
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06183779d7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tvolkert/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode_11.4.1.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by gspencergoog** [comment] 2020-07-17 17:12
I can reproduce this on Linux as well.  The exact reproduction is to click on the first text field, then the second, and then press the button to block focus.

I suspect this is because the unfocus mode that is being used is to focus the previously focused widget in the scope.

**Comment by goderbauer** [comment] 2020-07-22 22:14
@gspencergoog I assigned this to you since you have a PR out to fix it.

**Comment by TahaTesser** [comment] 2020-07-23 14:08
I can reproduce the issue based on https://github.com/flutter/flutter/issues/61700#issuecomment-660232316

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.95, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.95 at /Users/tahatesser/Code/flutter_master
    • Framework revision 50b87dc6c3 (19 hours ago), 2020-07-22 11:09:59 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Closed** 2020-07-23 15:27 UTC
Labels: P3, f: focus, found in release: 1.21, framework, has reproducible steps
