### ISSUE TITLE
* Error running Gradle:

### ISSUE THREAD

**Issue by hisan-web** [flutter/flutter#35437] opened 2019-07-02 01:30 UTC
the new project running on android for first time.

error 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.2.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > Connect to 127.0.0.1:1080 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > Connect to 127.0.0.1:1080 [/127.0.0.1] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Saifallak** [comment] 2019-07-02 11:07
It's network issue, make sure you have a stable connection and try again

**Comment by mikhail-tokarev** [comment] 2019-10-01 12:30
hi @hisan-web 
if the issue is still present with the latest version of Flutter, 
please provide the output of "flutter doctor -v"

**Comment by iapicca** [comment] 2019-11-08 15:34
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 15:34 UTC
Labels: waiting for customer response
