### ISSUE TITLE
Single item recall problem

### ISSUE THREAD

**Issue by SylvesterTube** [flutter/flutter#86610] opened 2021-07-17 17:56 UTC
Indeed, he can get here, but the application screen remains black without displaying anything

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:try22/config/toast_component.dart';

class UserInformation extends StatefulWidget {
  UserInformation(data);

  @override
  _UserInformationState createState() => _UserInformationState();
}

class _UserInformationState extends State<UserInformation> {
  final Stream<QuerySnapshot> _usersStream =
      FirebaseFirestore.instance.collection('productId').snapshots();
  ScrollController _mainScrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    print(['productTitle1']);
    return StreamBuilder<QuerySnapshot>(
      stream: _usersStream,
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        print(['productTitle2']);
        if (snapshot.hasError) {
          return Text(
            'Something went wrong',
            style: TextStyle(color: Colors.white),
          );
        }
        print(['productTitle3']);
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Text("Loading");
        }

        print(['productTitle4']);
        
        return new ListView(
          children: snapshot.data!.docs.map((DocumentSnapshot document) {
            Map<String, dynamic>? data =
                document.data() as Map<String, dynamic>?;

            return Scaffold(
              body: CustomScrollView(
                controller: _mainScrollController,
                physics: const BouncingScrollPhysics(
                    parent: AlwaysScrollableScrollPhysics()),
                slivers: [
                  SliverList(
                      delegate: SliverChildListDelegate([
                    Padding(
                        padding: const EdgeInsets.fromLTRB(
                          16.0,
                          8.0,
                          16.0,
                          0.0,
                        ),
                        child:  Text(
                        data!['productTitle'],
                         
                          style: TextStyle(
                              fontSize: 20,
                              color: MyTheme.font_grey,
                              fontWeight: FontWeight.bold),
                          maxLines: 2,
                        )
                        ),
                  ])),
                ],
              ),
            );
          }).toList(),
        );
      },
    );
  }
}

```

**Comment by iapicca** [comment] 2021-07-17 18:44
@SylvesterTube 
if it's an issue with [firebase](https://firebase.flutter.dev/) should be opened [here](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by TahaTesser** [comment] 2021-07-19 15:08
Hi @SylvesterTube 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-19 15:08 UTC
Labels: in triage
