### ISSUE TITLE
android app crash, error: [FATAL:flutter/shell/platform/android/image_external_texture_gl.cc(82)] Check failed: display != EGL_NO_DISPLAY.

### ISSUE THREAD

**Issue by lenzols** [flutter/flutter#155654] opened 2024-09-25 07:05 UTC
### Steps to reproduce

Flutter:  3.19.0 
Android: 13
Device: Mi 10
flutter_unity_widget: ^2022.2.1
  webview_flutter: 4.8.0
  webview_flutter_android: 3.16.1
  webview_flutter_wkwebview: ^3.14.0

1. Open the Unity page based on the flutter_unity_widget library package,
2. Open the webview_flutter-based WebView from the Unity page
3. Close the WebView page
4. Repeat the second and third steps about 8 times, and the program crashes

### Expected results

The program runs stably and does not crash

### Actual results

After repeatedly opening and closing the WebView page about 10 times while opening the Unity page, the program crashes

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

2024-09-25 14:54:00.014  3299-3299  AnimationHelper         com.android.systemui                 E  updateTime mToAod:false mHasNotification: false, mClockType: classic
2024-09-25 14:54:00.050  3299-3299  CollapsedS...arFragment com.android.systemui                 D  setIsHomePrivacyShowing mIsHomePrivacyShowing: true isHomePrivacyShowing: false isHomeToDottrue
2024-09-25 14:54:00.050  3299-3299  CollapsedS...arFragment com.android.systemui                 D  adjustDisableFlags: PanelExpansionState = 0 mHideIconsForBouncer = false mWereIconsJustHidden = false, mWakeUpCoordinator.getNotificationsFullyHidden = false, mIsExpanded = false, mBypassController.getBypassEnabled = false, mStatusBarStateController.getState() = 0, mKeyguardStateController.isKeyguardGoingAway() = false, mHeadsUpManager.hasPinnedHeadsUp = false, mIsLaunchAnimationRunning = false, mHideIconsDuringLaunchAnimation = true, isFullWidth()true, mShowIconsWhenExpanded = true, mControlPanelExpand = false
2024-09-25 14:54:00.138  1044-2276  libprotobuf-native      and...amera.provider@2.4-service_64  E  [libprotobuf ERROR external/protobuf/src/google/protobuf/message_lite.cc:123] Can't parse message of type "sns_flicker_event" because it is missing required fields: (cannot determine missing fields for lite message)
2024-09-25 14:54:00.138  1044-12883 libprotobuf-native      and...amera.provider@2.4-service_64  E  [libprotobuf ERROR external/protobuf/src/google/protobuf/message_lite.cc:123] Can't parse message of type "sns_flicker_event" because it is missing required fields: (cannot determine missing fields for lite message)
2024-09-25 14:54:00.189  2114-2605  MiuiNetworkPolicy       system_server                        D  updateLimit mLimitEnabled=false,enabled=true,mNetworkPriorityMode=1,mThermalForceMode=0
2024-09-25 14:54:00.196 10544-11315 AudioTrack              cn.daogoo.digitalworld               D  [audioTrackData][fine] 55s(f:55054 m:8191 s:0 k:0 cm:0 cs:0) : pid 10544 uid 11689 sessionId 2129 sr 48000 ch 2 fmt 5
2024-09-25 14:54:00.219  2114-2605  MiuiNetworkPolicy       system_server                        I  getEnableLimitTimeout when thermal mode is:0
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  Build fingerprint: 'Xiaomi/umi/umi:13/TKQ1.221114.001/V816.0.5.0.TJBCNXM:user/release-keys'
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  Revision: '0'
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  ABI: 'arm64'
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  Timestamp: 2024-09-25 14:53:59.464814467+0800
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  Process uptime: 119s
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  ZygotePid: 908
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  Cmdline: cn.daogoo.digitalworld
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  pid: 10544, tid: 10544, name: oo.digitalworld  >>> cn.daogoo.digitalworld <<<
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  uid: 11689
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  signal 6 (SIGABRT), code 0 (SI_USER), fault addr --------
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  Abort message: '[FATAL:flutter/shell/platform/android/image_external_texture_gl.cc(82)] Check failed: display != EGL_NO_DISPLAY. '
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      x0  0000000000000000  x1  0000000000002930  x2  0000000000000006  x3  0000007fd4eae190
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      x4  3333342f301f1f33  x5  3333342f301f1f33  x6  3333342f301f1f33  x7  7f7f7f7f7f7f7f7f
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      x8  00000000000000f0  x9  0000007d00672d30  x10 0000000000000001  x11 0000007d006e79c8
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      x12 0000007c61e01430  x13 000000000eae58c0  x14 000000000eae5840  x15 0000007d00676a02
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      x16 0000007d00752a80  x17 0000007d0072b650  x18 0000007d04700000  x19 0000000000002930
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      x20 0000000000002930  x21 00000000ffffffff  x22 b400007bc8a72fb8  x23 b400007bc8a72f88
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      x24 0000000000000000  x25 0000007fd4eaeb30  x26 0000007fd4eae9c0  x27 0000000000000004
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      x28 0000007fd4eaee00  x29 0000007fd4eae210
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A      lr  0000007d006d8948  sp  0000007fd4eae170  pc  0000007d006d8974  pst 0000000000001000
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A  backtrace:
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A        #00 pc 000000000008d974  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 8a2277585401a6103d671ea1f801ed52)
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A        #01 pc 0000000001c889d0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A        #02 pc 0000000001cb2960  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A        #03 pc 0000000001c90238  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A        #04 pc 0000000001c903d4  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A        #05 pc 0000000001c90544  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A        #06 pc 0000000001c8fd9c  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.221 12991-12991 DEBUG                   crash_dump64                         A        #07 pc 0000000001fcd4bc  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #08 pc 0000000001fc7dc0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #09 pc 0000000001fc6e2c  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #10 pc 0000000001fc7dc0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #11 pc 0000000001fcd7e0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #12 pc 0000000001fc7dc0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #13 pc 0000000001fcd7e0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #14 pc 0000000001fc7dc0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #15 pc 0000000001fcd7e0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #16 pc 0000000001fc7dc0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #17 pc 0000000001fcd7e0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #18 pc 0000000001fc7dc0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #19 pc 0000000001fcbebc  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #20 pc 00000000020efafc  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #21 pc 0000000001cb3508  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #22 pc 0000000001cb8fa0  /data/app/~~Y_m8Ej3HJvLKUzg3zL1H_Q==/cn.daogoo.digitalworld-lDCPEB3detiHtmnsqQHbNg==/lib/arm64/libflutter.so (BuildId: 3e3bace707d40d3b2b89bfadf71b5c8703947a35)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #23 pc 00000000000182e0  /system/lib64/libutils.so (android::Looper::pollInner(int)+1064) (BuildId: 21a5a3850d66add81295da6e6e78a956)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #24 pc 0000000000017e54  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116) (BuildId: 21a5a3850d66add81295da6e6e78a956)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #25 pc 000000000016cf0c  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48) (BuildId: bb4b4a6c550b76aaaebdcf90ae63ab5f)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #26 pc 00000000001b0094  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116) (BuildId: df622c091e95130688f598bc16995c70153b9355)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #27 pc 000000000201a5d4  /memfd:jit-cache (deleted) (android.os.MessageQueue.next+244)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #28 pc 0000000002017198  /memfd:jit-cache (deleted) (android.os.Looper.loopOnce+184)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #29 pc 0000000000209a9c  /apex/com.android.art/lib64/libart.so (nterp_helper+1948) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #30 pc 00000000001f0a50  /system/framework/framework.jar (android.os.Looper.loop+164)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #31 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #32 pc 00000000001cc8ae  /system/framework/framework.jar (android.app.ActivityThread.main+246)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #33 pc 0000000000210c00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #34 pc 000000000027b4ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+240) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #35 pc 000000000061a91c  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1400) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #36 pc 000000000059a420  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #37 pc 0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120) (BuildId: ab46a9f0d9016a2531f2e17cbdd13bc803503576)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #38 pc 000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #39 pc 0000000000508f0e  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #40 pc 00000000007349ac  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3228) (BuildId: df622c091e95130688f598bc16995c70153b9355)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #41 pc 0000000000210c00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #42 pc 000000000027b4ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+240) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #43 pc 000000000061b0a4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+452) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #44 pc 000000000061b590  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+96) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #45 pc 0000000000501fe8  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+600) (BuildId: 14fc77b24db0b351b919c97009dc86bf)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #46 pc 00000000000c4c04  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: bb4b4a6c550b76aaaebdcf90ae63ab5f)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #47 pc 00000000000d1c10  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924) (BuildId: bb4b4a6c550b76aaaebdcf90ae63ab5f)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #48 pc 0000000000002610  /system/bin/app_process64 (main+1464) (BuildId: 82486a24ab8170e1b0c9080a100ddae4)
2024-09-25 14:54:00.222 12991-12991 DEBUG                   crash_dump64                         A        #49 pc 0000000000085bd0  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100) (BuildId: 8a2277585401a6103d671ea1f801ed52)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.19.0, on Microsoft Windows [版本 10.0.22631.4169], locale zh-CN)
    ! Warning: `flutter` on your path resolves to D:\sdk\fvm\versions\3.19.0\bin\flutter, which is not inside your
      current Flutter SDK checkout at D:\sdk\fvm\default. Consider adding D:\sdk\fvm\default\bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to D:\sdk\Dart\dart-sdk\bin\dart.exe, which is not inside your current
      Flutter SDK checkout at D:\sdk\fvm\default. Consider adding D:\sdk\fvm\default\bin to the front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.2)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2024.1)
[√] Connected device (4 available)
[√] Network resources]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-25 09:30
This is a duplicate of https://github.com/flutter/flutter/issues/149396

Kindly share any additional information you can provide in the original issue. 

Please also upgrade to the latest version to see if you still experience this. 

Closing this in favor of the original issue. 

Thank you

**Closed by danagbemava-nc** 2024-09-25 09:30 UTC
Labels: in triage
