### ISSUE TITLE
Named SharedPreferences

### ISSUE THREAD

**Issue by ronshapiro** [flutter/flutter#27451] opened 2019-02-03 02:30 UTC
The `shared_preferences` package only allows for a single SharedPreferences file, but both [Android](https://developer.android.com/reference/android/content/Context#getSharedPreferences(java.lang.String,%20int)) and [iOS]https://developer.apple.com/documentation/foundation/nsuserdefaults/1409957-initwithsuitename?language=objc allow for multiple shared preferences/NSUserDefaults files.

It would be good to add this functionality to the Flutter package so that content can be properly sectioned by different packages/use cases. It would also allow use of the package without requiring a singleton instance, which is good for testability.

**Comment by kangwang1988** [comment] 2019-02-03 16:34
@cyanglaz 
Any comments on this suggestion?

**Comment by zoechi** [comment] 2019-02-07 11:07
Looks like a duplicate of #14337

**Closed** 2019-02-07 11:08 UTC
Labels: p: first party, p: shared_preferences, plugin, severe: new feature
