### ISSUE TITLE
Serious problem in flutter

### ISSUE THREAD

**Issue by amjadsh97** [flutter/flutter#42930] opened 2019-10-17 15:11 UTC
How can I solve this problem please?

Running "flutter pub get" in flutter_maps_location...               0.7s
Launching lib\main.dart on SM J610F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device SM J610F...
I/Adreno  (24083): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    (24083): Shader compilation error
D/skia    (24083): ------------------------
D/skia    (24083):    1	#version 310 es
D/skia    (24083):    2	
D/skia    (24083):    3	in highp vec4 sk_FragCoord_Workaround;
D/skia    (24083):    4	precision mediump float;
D/skia    (24083):    5	precision mediump sampler2D;
D/skia    (24083):    6	out mediump vec4 sk_FragColor;
D/skia    (24083):    7	in mediump vec4 vcolor_Stage0;
D/skia    (24083):    8	void main() {
D/skia    (24083):    9	    mediump vec4 outputColor_Stage0;
D/skia    (24083):   10	    {
D/skia    (24083):   11	        outputColor_Stage0 = vcolor_Stage0;
D/skia    (24083):   12	    }
D/skia    (24083):   13	    {
D/skia    (24083):   14	        sk_FragColor = outputColor_Stage0;
D/skia    (24083):   15	    }
D/skia    (24083):   16	}
D/skia    (24083):   17	
D/skia    (24083): Errors:
D/skia    (24083): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    (24083): 
I/Adreno  (24083): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    (24083): Shader compilation error

**Comment by timsneath** [comment] 2019-10-17 22:33
Looks like a duplicate of https://github.com/flutter/flutter/issues/36130.

**Closed by timsneath** 2019-10-17 22:33 UTC
