### ISSUE TITLE
Textfield automatically focused by back button but not by iOS swipe navigation

### ISSUE THREAD

**Issue by adem74** [flutter/flutter#153559] opened 2024-08-16 12:10 UTC
### Steps to reproduce

1. Open page
2. Click textfield
3. Click somewhere to navigate
4. Going back by clicking back button or swipe

### Expected results

I think both should produce the same things.

### Actual results

When user wants to going back, if click to back icon it focused to textfield. But if user used iOS swipe navigation, not focused.

### Code sample

<details open><summary>Code sample</summary>

```dart
// ignore_for_file: must_be_immutable, prefer_const_constructors

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

Future navigate({
  required BuildContext context,
  Widget? page,
}) async {
  if (page == null) {
    Navigator.pop(context);
    return;
  }
  final route =
      CupertinoPageRoute(builder: (context) => page, maintainState: true);
  await Navigator.push(context, route);
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(debugShowCheckedModeBanner: false, home: HomePage());
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: () {
          navigate(context: context, page: Page1());
        },
        child: Center(
          child: Text('Go Page1!'),
        ),
      ),
    );
  }
}

class Page1 extends StatelessWidget {
  Page1({super.key});
  var focusNode = FocusNode();
  final TextEditingController controller = TextEditingController();
  final ScrollController scrollController = ScrollController();
  var inited = false;
  @override
  Widget build(BuildContext context) {
    Future.delayed(Duration.zero, () {
      if (inited) return;
      if (controller.text.isEmpty) {
        controller.text = "basetext";
      } else {
        focusNode.requestFocus();
      }
      print("delayed page 1");
      inited = true;
    });
    return Scaffold(
      appBar: AppBar(
        scrolledUnderElevation: 0,
        leading: GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: () {
            navigate(context: context);
          },
          child: const Icon(
            Icons.arrow_back_ios_new,
            color: Colors.grey,
          ),
        ),
        title: Row(
          children: [
            searchInput(context),
          ],
        ),
      ),
      body: GestureDetector(
          onTap: () {
            FocusScope.of(context).unfocus();
          },
          child: _getView(context)),
    );
  }

  Widget _getView(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.all(16.0),
          child: Text("Just placeholder"),
        ),
        Expanded(
            child: ListView.separated(
                itemBuilder: (context, index) => ListTile(
                      onTap: () {
                        navigate(context: context, page: Page2());
                      },
                      title: Text("$index"),
                    ),
                separatorBuilder: (context, index) =>
                    Divider(color: Colors.black12),
                itemCount: 50)),
      ],
    );
  }

  Widget searchInput(BuildContext context) {
    return Expanded(
      child: SingleChildScrollView(
        child: TextFormField(
          style: TextStyle(fontWeight: FontWeight.bold),
          maxLength: 50,
          controller: controller,
          focusNode: focusNode,
          decoration: InputDecoration(
            labelText: "somethings",
            counterText: "",
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          scrolledUnderElevation: 0,
          leading: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: () {
              navigate(context: context);
            },
            child: const Icon(
              Icons.arrow_back_ios_new,
              color: Colors.grey,
            ),
          ),
          title: Text("Page2")),
      body: Center(child: Text("data")),
    );
  }
}

```

</details>

### Screenshots or Video

https://github.com/user-attachments/assets/9606a49c-fc18-4075-be4f-210a914f9374

### Logs

<details open><summary>Clicking back button</summary>

```console
I/ViewRootImpl@49561a7[MainActivity]( 9124): ViewPostIme pointer 0
I/ViewRootImpl@49561a7[MainActivity]( 9124): ViewPostIme pointer 1
D/InputMethodManager( 9124): startInputInner - Id : 0
I/InputMethodManager( 9124): startInputInner - mService.startInputOrWindowGainedFocus
I/IMM_LC  ( 9124): showSoftInput(View,I)
I/IMM_LC  ( 9124): ssi() - flag : 0 view : app.name reason = SHOW_SOFT_INPUT
I/IMM_LC  ( 9124): ssi() view is not EditText
I/IMM_LC  ( 9124): showSoftInput(View,I)
I/IMM_LC  ( 9124): ssi() - flag : 0 view : app.name reason = SHOW_SOFT_INPUT
I/IMM_LC  ( 9124): ssi() view is not EditText
D/InputConnectionAdaptor( 9124): The input method toggled cursor monitoring on
D/InsetsController( 9124): show(ime(), fromIme=true)
D/InsetsSourceConsumer( 9124): setRequestedVisible: visible=true, type=19, host=app.name/app.name.MainActivity, from=android.view.InsetsSourceConsumer.show:246 android.view.InsetsController.showDirectly:1489 android.view.InsetsController.controlAnimationUnchecked:1137 android.view.InsetsController.applyAnimation:1456 android.view.InsetsController.applyAnimation:1437 android.view.InsetsController.show:976 android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6483 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6408 android.os.Handler.dispatchMessage:106 android.os.Looper.loopOnce:226 
I/ViewRootImpl@49561a7[MainActivity]( 9124): mWNT: t = android.view.SurfaceControl$Transaction@2ec11f2 fN = 83 android.view.SyncRtSurfaceTransactionApplier.applyTransaction:94 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0$SyncRtSurfaceTransactionApplier:71 android.view.SyncRtSurfaceTransactionApplier$$ExternalSyntheticLambda0.onFrameDraw:4 
I/ViewRootImpl@49561a7[MainActivity]( 9124): mWNT: merge t to BBQ
// more prints same as above two
```

</details>
<details open><summary>Swipe navigation</summary>

```console
I/ViewRootImpl@49561a7[MainActivity]( 9124): ViewPostIme pointer 0
I/ViewRootImpl@49561a7[MainActivity]( 9124): ViewPostIme pointer 1
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale en-GB)
    • Flutter version 3.24.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\adam\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35122.118
    • Windows 10 SDK version 10.0.22621.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code, 64-bit edition (version 1.89.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • SM G975F (mobile) • 192.168.1.13:36529 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 127.0.2651.98

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-19 07:30
Hi @adem74, the code sample you have provided above is not complete and it contains a lot of third-party packages and custom widgets. 

Please provide a complete minimal reproducible code sample without any third-party packages or custom widgets (or provide the implementation for those widgets) so that we can properly investigate this issue. 

Thank you

**Comment by adem74** [comment] 2024-08-21 19:46
Hi @danagbemava-nc , Thanks for your interest. I have provided basic structure. If i do not click textfield, there is no problem. But if i do, the behaviour is different, you can see in video.

**Comment by danagbemava-nc** [comment] 2024-08-22 06:54
This is a duplicate of https://github.com/flutter/flutter/issues/48464. Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2024-08-22 06:54 UTC
Labels: in triage
