### ISSUE TITLE
_BoundSinkStream Error

### ISSUE THREAD

**Issue by dovahkiin98** [flutter/flutter#15110] opened 2018-03-03 19:05 UTC
I'm using Dart 2 and when I try to make an HTTP GET request, This error is shown

```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (21922): type '_BoundSinkStream<dynamic, List<int>>' is not a subtype of type '_HttpIncoming' where
E/flutter (21922):   _BoundSinkStream is from dart:async
E/flutter (21922):   List is from dart:core
E/flutter (21922):   int is from dart:core
E/flutter (21922):   List is from dart:core
E/flutter (21922):   int is from dart:core
E/flutter (21922):   _HttpIncoming is from dart:_http
E/flutter (21922):   List is from dart:core
E/flutter (21922):   int is from dart:core
```

this is my code

```dart
Future<Stream<Device>> getDevices() async {
  var httpClient = HttpClient();
  var uri = Uri.http('x.aba.ae', '/x.php');
  HttpClientRequest request = await httpClient.getUrl(uri);
  HttpClientResponse response = await request.close();

  return response 
      .transform(UTF8.decoder)
      .transform(JSON.decoder)
      .asyncMap((json) => Device.fromJson(json));
}
```

**Comment by mraleph** [comment] 2018-03-03 22:48
This should be fixed on master. Are you using beta?

**Comment by mraleph** [comment] 2018-03-03 22:48
Duplicate of #14819

**Closed by mraleph** 2018-03-03 22:48 UTC
