### ISSUE TITLE
Is there any way to get the photo gps info by using plugin camera?

### ISSUE THREAD

**Issue by caipeng-hrv** [flutter/flutter#42398] opened 2019-10-10 04:38 UTC

**Comment by janmoppel** [comment] 2019-10-10 10:12
Hello @caipeng-hrv !

Thank you for posting.
Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

**Comment by VladyslavBondarenko** [comment] 2020-02-19 16:36
Duplicate of https://github.com/flutter/flutter/issues/30769

**Closed by VladyslavBondarenko** 2020-02-19 16:36 UTC
Labels: d: stackoverflow, p: camera, p: first party, plugin
