### ISSUE TITLE
flutter install -d all does not work

### ISSUE THREAD

**Issue by safield** [flutter/flutter#50907] opened 2020-02-17 06:32 UTC
I am running multiple android emulator instances.

When I run **_flutter install_**, the output instructs me to use -d...

> more than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.

I then proceed to run **_flutter install -d all_**, and it still outputs and error...

> More than one device connected; please specify a device with the '-d <deviceId>' flag.

Providing a specific device as the -d argument properly installs, but -d all does not work.

My flutter doctor output...

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_CA.UTF-8)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [!] Android Studio (not installed)
> [✓] Connected device (2 available)
> 
> ! Doctor found issues in 1 category.

**Comment by Vanethos** [comment] 2020-02-17 06:34
Could you paste here the output of `flutter doctor` please?

**Comment by safield** [comment] 2020-02-17 06:37
> Could you paste here the output of `flutter doctor` please?

updated initial post.

**Comment by Vanethos** [comment] 2020-02-17 06:46
Duplicate of #16297

If you have more context for this error message, or want to leave a 👍 to indicate that it is still affecting you please comment on the meta issue #16297

**Closed by Vanethos** 2020-02-17 06:46 UTC
