### ISSUE TITLE
Ability to select a specific word in Text

### ISSUE THREAD

**Issue by ayush221b** [flutter/flutter#26581] opened 2019-01-15 10:06 UTC
I am displaying a String using the Text widget, and I want the user to be able to long press and select a specific word. But I can't find any way to do it. 

For instance, if the sentence is, "This is an example sentence." If the user long presses on the word "example" I want to be able to handle that, for instance pass it as a parameter to a function.

**Comment by zoechi** [comment] 2019-01-15 10:09
Duplicate of #5422

**Closed by zoechi** 2019-01-15 10:09 UTC
