### ISSUE TITLE
[Fonts][Icons] Material Icon Show incorrect (showing eagle for cart checkout icon)

### ISSUE THREAD

**Issue by barockok** [flutter/flutter#98457] opened 2022-02-15 00:51 UTC
Seems there is an issue with the font, I tried using `Icon.shopping_cart_checkout` for android, but it shows an eagle icon instead of a [cart with an arrow](https://api.flutter.dev/flutter/material/Icons/shopping_cart_checkout-constant.html).
I thought it was only on my local development but seems it also easily reproduce in [dart.pad](https://dartpad.dev/)

![Screen Shot 2022-02-15 at 07 50 25](https://user-images.githubusercontent.com/474500/153971681-752a5079-aa39-4969-a7c3-fbd5effec4ab.png)

sample code :
```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Row(children: [
      const Icon(Icons.shopping_cart_checkout),
      const SizedBox(width: 10),
      Text(
        'Hello, World!',
        style: Theme.of(context).textTheme.headline4,
      )
    ]);
  }
}

```

**Comment by danagbemava-nc** [comment] 2022-02-15 08:22
Duplicate of #97767

**Closed by danagbemava-nc** 2022-02-15 08:22 UTC
Labels: in triage
