### ISSUE TITLE
[web][HtmlElementView] Embedded videos don't retain state

### ISSUE THREAD

**Issue by thomas-stockx** [flutter/flutter#42431] opened 2019-10-10 13:32 UTC
## Steps to Reproduce

Embed a video (YouTube, Google Drive,...) in a page that also contains an AppBar with a back button. Hovering over the back button will cause the embedded iframe to refresh, and lose all state of the video player.

Unlike AndroidView and UiKitView (which are Stateful widgets), HtmlElementView is Stateless, could this be related?

Sample project:

```
import 'package:flutter/material.dart';
import 'package:stockxit_web/widgets/embedded_video.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Center(
        child: FlatButton(
          child: Text('Go to embedded video'),
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (BuildContext context) {
                  return EmbeddedVideo(
                    src: 'https://www.youtube.com/embed/8i-PyOT9WKk',
                  );
                },
              ),
            );
          },
        ),
      ),
    );
  }
}
```

and
```import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

class EmbeddedVideo extends StatefulWidget {
  const EmbeddedVideo({Key key, this.src, this.width, this.height})
      : super(key: key);

  final String width;
  final String height;
  final String src;

  @override
  _EmbeddedVideoState createState() => _EmbeddedVideoState();
}

class _EmbeddedVideoState extends State<EmbeddedVideo> {
  GlobalKey _key;

  @override
  void initState() {
    print('initstate of embedded video');
    super.initState();
    _key = new GlobalKey();
    ui.platformViewRegistry.registerViewFactory(widget.src, (int viewId) {
      final video = IFrameElement()
        ..width = widget.width
        ..height = widget.height
        ..src = widget.src
        ..style.border = 'none';
      return video;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: HtmlElementView(
        key: _key,
        viewType: widget.src,
      ),
    );
  }
}
```

**Target Platform:** MacOS
**Target OS version/browser:** Chrome Version 77.0.3865.90 (Official Build) (64-bit)

flutter doctor -v output:

```
[✓] Flutter (Channel master, v1.10.15-pre.51, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.10.15-pre.51 at /Users/thomass/dev/flutter
    • Framework revision 991153ada0 (4 hours ago), 2019-10-10 05:32:43 -0400
    • Engine revision 5a86054441
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 48e93d3d3b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thomass/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/thomass/Library/Android/sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (3 available)
    • macOS           • macOS           • darwin-x64     • Mac OS X 10.14.6 18G103
    • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

Thanks!

**Comment by yjbanov** [comment] 2019-10-17 22:13
This seems to be a duplicate of https://github.com/flutter/flutter/issues/39980

**Closed by yjbanov** 2019-10-17 22:13 UTC
Labels: ☸ platform-web

**Comment by thomas-stockx** [comment] 2019-10-18 07:06
Hi @yjbanov,

Sorry this is not a duplicate :(
Issue #39980 is about flickering of the VideoElement on Safari (not on Chrome)

This issue is about flickering of the HtmlElementView on all browsers (including Chrome).

**Comment by yjbanov** [comment] 2019-10-18 15:42
We think this is a duplicate because the underlying cause for both is the same, i.e. we put the HTML view inside the layer tree where it gets reparented across frames. At least that's the current hypothesis.
