### ISSUE TITLE
SelectionArea: Custom emoticons mixed with text during copy and paste selection, resulting in incomplete selection exception

### ISSUE THREAD

**Issue by men620** [flutter/flutter#157217] opened 2024-10-19 05:51 UTC
My complete code has been pasted out. Follow this example to reproduce it. It appears on Windows 10 PC;
Its effect is like this:
![无标题](https://github.com/user-attachments/assets/9aa251f4-fb70-4442-a32c-db27bf79b9f6)

Could you please help me review this issue?
```
import 'dart:ui';
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:extended_text/extended_text.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_svg/svg.dart';
import 'package:intl/intl.dart';
import 'generated/intl/messages_all.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      supportedLocales: S.delegate.supportedLocales,
      localizationsDelegates: const [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
      title: 'SelectionArea实现文本全选复制功能',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'SelectionArea实现文本全选复制功能'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final String content = "天气[aiyi][aiyi][aiyi]啊\nemm[baituo][baituo]唉";

  get _listView => ListView(
        padding:
            const EdgeInsets.only(left: 12, right: 12, top: 15, bottom: 15),
        children: [_textContent],
      );

  get _textContent => IBSelectionArea.wrap(ExtendedText(
        content,
        style: TextStyle(fontSize: 16),
        specialTextSpanBuilder: DefaultSpecialTextSpanBuilder(
          context: context,
          highlightStyle:
              TextStyle(fontSize: 16, fontWeight: FontWeight.w400, height: 1.5),
        ),
        maxLines: null,
        overflow: TextOverflow.fade,
        boxHeightStyle: BoxHeightStyle.max,
      ));

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: _listView,
    );
  }
}

class DefaultSpecialTextSpanBuilder extends SpecialTextSpanBuilder {
  DefaultSpecialTextSpanBuilder(
      {TextStyle? highlightStyle, this.emojiSize, this.context}) {
    _highlightStyle = highlightStyle;
  }

  late TextStyle? _highlightStyle;
  double? emojiSize;
  BuildContext? context;

  @override
  TextSpan build(String data,
      {TextStyle? textStyle, SpecialTextGestureTapCallback? onTap}) {
    if (data == '') {
      return const TextSpan(text: '');
    }
    List<InlineSpan> inlineList = <InlineSpan>[];
    inlineList = getSpans(data, context!, textStyle, onTap);
    return TextSpan(children: inlineList, style: textStyle);
  }

  List<InlineSpan> getSpans(String data, BuildContext context,
      TextStyle? textStyle, SpecialTextGestureTapCallback? onTap) {
    String originalData = revertBreakWord(data);
    var urls = UrlList().getUrls(originalData);
    List<InlineSpan> spans = [];
    int start = 0;
    int end;
    if (urls.isNotEmpty) {
      for (var element in urls) {
        end = originalData.toLowerCase().indexOf(element.toLowerCase(), start);
        String beforeUrl = originalData.substring(start, end);
        spans.addAll(buildString(beforeUrl, textStyle, onTap));
        spans.add(TextSpan(
            text:
                breakWord(originalData.substring(end, (end + element.length))),
            style: _highlightStyle));
        start = (end + element.length);
      }
    }
    String afterUrl = originalData.substring(start, originalData.length);
    spans.addAll(buildString(afterUrl, textStyle, onTap));
    return spans;
  }

  SpecialText? createSpecialText1(String flag, String data,
      {TextStyle? textStyle,
      SpecialTextGestureTapCallback? onTap,
      required int index}) {
    if (flag == '') {
      return null;
    }
    if (isStart(flag, '[')) {
      return Emoji(textStyle,
          start: index - ('['.length - 1), sizeRatio: emojiSize);
    } else if (isStart(flag, Highlight.flag)) {
      return Highlight(_highlightStyle,
          start: index - (Highlight.flag.length - 1));
    }
    return null;
  }

  List<InlineSpan> buildString(
      String data, TextStyle? textStyle, SpecialTextGestureTapCallback? onTap) {
    final List<InlineSpan> inlineList = <InlineSpan>[];
    if (data == '') {
      return inlineList;
    }
    if (data.isNotEmpty) {
      SpecialText? specialText;
      String textStack = '';

      //String text
      for (int i = 0; i < data.length; i++) {
        final String char = data[i];
        textStack += char;
        if (specialText != null) {
          // always append
          // and remove endflag in getContent method
          specialText.appendContent(char);
          if (specialText.isEnd(textStack)) {
            inlineList.add(specialText.finishText());
            specialText = null;
            textStack = '';
          }
        } else {
          specialText = createSpecialText1(textStack, data,
              textStyle: textStyle, onTap: onTap, index: i);
          if (specialText != null) {
            if (textStack.length - specialText.startFlag.length >= 0) {
              textStack = textStack.substring(
                  0, textStack.length - specialText.startFlag.length);
              if (textStack.isNotEmpty) {
                inlineList.add(TextSpan(text: textStack, style: textStyle));
              }
            }
            textStack = '';
          }
        }
      }

      if (specialText != null) {
        inlineList.add(TextSpan(
            text: specialText.startFlag + specialText.getContent(),
            style: textStyle));
      } else if (textStack.isNotEmpty) {
        if (textStack == '\u200B\u200B') {
          textStack = " $textStack";
          textStyle = textStyle?.copyWith(fontSize: 1);
        }
        inlineList.add(TextSpan(text: textStack, style: textStyle));
      }
    } else {
      inlineList.add(TextSpan(text: data, style: textStyle));
    }
    return inlineList;
  }

  @override
  SpecialText? createSpecialText(String flag,
      {TextStyle? textStyle,
      SpecialTextGestureTapCallback? onTap,
      required int index}) {
    return null;
  }
}

class Highlight extends SpecialText {
  Highlight(TextStyle? textStyle, {this.start}) : super(flag, flag, textStyle);

  static const String flag = '\$&※';
  final int? start;

  @override
  InlineSpan finishText() {
    final String text = getContent();

    return SpecialTextSpan(
        text: breakWord(text),
        actualText: toString(),
        start: start!,
        deleteAll: true,
        style: textStyle);
  }
}

///解决字符串中有- 空格等导致Text控件异常换行的问题.
String breakWord(String word) {
  if (word.isEmpty) {
    return word;
  }
  StringBuffer breakWord = StringBuffer();
  for (var element in word.trim().runes) {
    breakWord.write(String.fromCharCode(element));
    breakWord.write('\u200B');
  }
  return breakWord.toString();
}

String revertBreakWord(String word) {
  if (word.isEmpty) {
    return word;
  }
  StringBuffer breakWord = StringBuffer();
  for (var element in word.trim().runes) {
    if (element != 8203) {
      breakWord.write(String.fromCharCode(element));
    }
  }
  breakWord.write('\u200B\u200B');
  return breakWord.toString();
}

/// 表情文本
///
/// 例如：这里包含表情[jingli1]。其中“[jingli1]”将被尝试识别为表情，查找表示你好的表情并填充在它的位置。
class Emoji extends SpecialText {
  Emoji(TextStyle? textStyle, {this.start, this.sizeRatio})
      : super(Emoji.flag, ']', textStyle);
  static const String flag = '[';
  final int? start;
  final double? sizeRatio;

  @override
  InlineSpan finishText() {
    final String key = toString();
    if (EmojiUtil.instance.defaultCommonEmojiMap.containsKey(key)) {
      double size = 18;
      if (textStyle?.fontSize != null) {
        double ratio = 1.15;
        final tempRatio = sizeRatio;
        final height = textStyle!.height;
        if (tempRatio != null &&
            height != null &&
            tempRatio >= 1.0 &&
            tempRatio <= height) {
          ratio = tempRatio;
        } else if (height != null) {
          ratio = height;
        }
        size = textStyle!.fontSize! * ratio;
      }
      return ImageSpan(
          MyAssets.assetImage(
            EmojiUtil.instance.defaultCommonEmojiMap[key]!,
          ),
          actualText: key,
          imageWidth: size,
          imageHeight: size,
          start: start!,
          fit: BoxFit.contain,
          margin: const EdgeInsets.all(2));
    }
    return TextSpan(text: toString(), style: textStyle);
  }
}

class EmojiUtil {
  EmojiUtil._() {
    for (var name in _commonEmojiSet) {
      _defaultCommonEmojiMap['[$name]'] =
          '$_defaultCommonEmojiBasePath/$name.png';
    }
  }
  final String _defaultCommonEmojiBasePath = 'assets/commonEmoji';
  final Map<String, String> _defaultCommonEmojiMap = <String, String>{};
  /// 通用表情，表情名-表情文件名映射关系
  Map<String, String> get defaultCommonEmojiMap => _defaultCommonEmojiMap;
  final List<String> _commonEmojiSet = ["aiyi", "baituo"];
  /// 通用表情贴图，表情贴图名集合
  List<String> get defaultCommonEmojiSet => _commonEmojiSet;
  static EmojiUtil? _instance;
  static EmojiUtil get instance => _instance ??= EmojiUtil._();
}

class S {
  S();
  static S? _current;
  static S get current {
    assert(_current != null,
        'No instance of S was loaded. Try to initialize the S delegate before accessing S.current.');
    return _current!;
  }
  static const AppLocalizationDelegate delegate = AppLocalizationDelegate();

  static Future<S> load(Locale locale) {
    final name = (locale.countryCode?.isEmpty ?? false)
        ? locale.languageCode
        : locale.toString();
    final localeName = Intl.canonicalizedLocale(name);
    return initializeMessages(localeName).then((_) {
      Intl.defaultLocale = localeName;
      final instance = S();
      S._current = instance;

      return instance;
    });
  }

  static S of(BuildContext context) {
    final instance = S.maybeOf(context);
    assert(instance != null,
        'No instance of S present in the widget tree. Did you add S.delegate in localizationsDelegates?');
    return instance!;
  }

  static S? maybeOf(BuildContext context) {
    return Localizations.of<S>(context, S);
  }

  /// `Love`
  String get love {
    return Intl.message(
      'Love',
      name: 'love',
      desc: '',
      args: [],
    );
  }

  /// `Please`
  String get please {
    return Intl.message(
      'Please',
      name: 'please',
      desc: '',
      args: [],
    );
  }
}

class AppLocalizationDelegate extends LocalizationsDelegate<S> {
  const AppLocalizationDelegate();
  List<Locale> get supportedLocales {
    return const <Locale>[
      Locale.fromSubtags(languageCode: 'en'),
      Locale.fromSubtags(languageCode: 'zh'),
    ];
  }
  @override
  bool isSupported(Locale locale) => _isSupported(locale);
  @override
  Future<S> load(Locale locale) => S.load(locale);
  @override
  bool shouldReload(AppLocalizationDelegate old) => false;
  bool _isSupported(Locale locale) {
    for (var supportedLocale in supportedLocales) {
      if (supportedLocale.languageCode == locale.languageCode) {
        return true;
      }
    }
    return false;
  }
}

class MyAssets {
  static String? moduleName;
  static AssetImage assetImage(String assetName) {
    return AssetImage(assetName, package: moduleName);
  }
}

class UrlList {
  List<String> getUrls(String content) {
    List<String> urlList = [];
    RegExp exp = RegExp(
        "(https?|ftp|file)://[-A-Za-z0-9+&#/%?=~_|!:,.;]+[-A-Za-z0-9+&#/%=~_|]");
    var theURl = exp.allMatches(content);
    for (var element in theURl) {
      urlList.add(content.substring(element.start, element.end));
    }
    return urlList;
  }
}

///文本全选、复制
class IBSelectionArea {
  static Widget wrap(Text child, {bool selectAll = true, bool copy = true}) {
    //选择的文本
    var selectedText = '';
    return SelectionArea(
      child: child,
      onSelectionChanged: (SelectedContent? selectContent) =>
          selectedText = selectContent?.plainText ?? "",
      contextMenuBuilder:
          (BuildContext context, SelectableRegionState selectableRegionState) {
        bool selectAllEnable = false;
        //如果还有可选的内容则展示全选菜单
        if (selectedText.length < (child.data?.length ?? 0)) {
          selectAllEnable = true;
        }
        final List<ContextMenuButtonItem> buttonItems = [
          if (selectAll && selectAllEnable)
            ContextMenuButtonItem(
                label: '全选',
                onPressed: () {
                  selectableRegionState
                      .selectAll(SelectionChangedCause.toolbar);
                }),
          if (copy)
            ContextMenuButtonItem(
                label: '复制',
                onPressed: () {
                  selectableRegionState
                      .copySelection(SelectionChangedCause.toolbar);
                })
        ];
        return AdaptiveTextSelectionToolbar.buttonItems(
          buttonItems: buttonItems,
          anchors: selectableRegionState.contextMenuAnchors,
        );
      },
    );
  }
}

```

**Comment by danagbemava-nc** [comment] 2024-10-21 07:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/157157

Please do not file multiple issues to report the same bug in the future. 

Thank you

**Closed by danagbemava-nc** 2024-10-21 07:25 UTC
Labels: in triage
