### ISSUE TITLE
Build errors for Android when importing a custom flutter package that relies on a local android Library

### ISSUE THREAD

**Issue by Taco55** [flutter/flutter#65333] opened 2020-09-07 09:00 UTC
I have created a flutter package that relies on an android Library (AAR-file). Although the example that I included in this package builds fine for Android, when I import the package in another Flutter project I receive errors that the android library cannot be found:

```
Build file '/Users/user/.pub-cache/git/sample_flutter_plugin-958031b73ceb18e62439a4a05e1d9c2085b28992/android/build.gradle' line: 37

* What went wrong:
A problem occurred evaluating project ':sample_flutter_plugin'.
> Project with path ':localandroidlibrary' could not be found in project ':sample_flutter_plugin'.
```

The `build.gradle` of `sample_flutter_plugin` where the failure occurs: 

```
dependencies {
    implementation project(path: ':localandroidlibrary')
    implementation 'com.google.code.gson:gson:2.8.6'
}
```

And the `settings.gradle` file is:

```
rootProject.name = 'sample_flutter_plugin'
include ':localandroidlibrary'
project(":localandroidlibrary").projectDir = file("./localandroidlibrary")
```

The project structure of the package is:
```
sample_flutter_plugin
-> .idea
-v android
--> .gradle
--> .idea
--> .settings
--> gradle.wrapper
--v localandroidlibrary
---> .settings
---> build..transforms
---  .project
---  build.gradle
---  localandroidlibrary.aar
---  localandroidlibrary.iml
-> src.main
-  .classpath
-  .gitignore
-  .project
-  build.gradle
-  gradle.properties
-  local.properties
-  settings.gradle
-> example
...
```

I see a relationship with https://github.com/flutter/flutter/issues/17150, but in my case I have no problems with building an example app in the custom flutter package. 

Any ideas for a work-around to this problem?

**Comment by TahaTesser** [comment] 2020-09-07 10:29
Hi @Taco55 
Does this [solution](https://github.com/flutter/flutter/issues/17150#issuecomment-385644656) help your issue?

**Comment by Taco55** [comment] 2020-09-07 12:23
@TahaTesser Thanks for your answer. I already tried to add a `settings.gradle` to the root of the project, but unfortunately it doesn't solve the issue. The difference with #17150 is that in my case the example project builds correctly, but that the aar-project is not found when the package is imported in another Flutter project.

**Comment by TahaTesser** [comment] 2020-09-08 07:27
Hi @Taco55 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a complete reproducible minimal code plugin sample  in a repository 
Thank you

**Comment by angelschnider** [comment] 2020-09-17 06:22
Hello,

I have the exact same issue! I don't understand why. :-(

My Flutter plugin( Flugin ;-)) work fine when I launch the **"example"** project but when I try to use it in an another Flutter project I have the same error message than you :  >>**Project with path ':MyFlugin' could not be found in project ':MyFlugin'**<<
I also use a **".aar"** library in my Flugin. I tried to put **".aar"** in a libs folder and referencing it in "build.gradle", it works fine when I launch the **"example"** project but, when I try in an another Flutter project I have a message that tell I cannot use an ".aar" because it may be corrupt etc (I don't remember the exact error message sorry).
Then I try with the official way, **Menu>Projet>New Module>Import aar.**. It creates the "lib" folder with a gradle file inside and the "**.aar"** but I don't know why this folder is created inside **"MyFlugin/example/android"** and not in the **"MyFlugin/android"** folder? I presume it's for that reason I have the same issue than you....
Have you find a solution?

**Comment by Taco55** [comment] 2020-09-17 08:01
Hi @angelschnider 
Yes, this seems the same issue and might be a limitation of Gradle. 

A workaround that worked for me was to put the .aar-file in a `libs` map in the Android folder en to update `build.gradle` in the plugin with:

```
rootProject.allprojects {
    repositories {
        google()
        jcenter()
        flatDir {
            dirs project(': sample_flutter_plugin').file('libs')
        }
    }
}

dependencies {
    api(name: 'sample_flutter_plugin', ext: 'aar')
}
```

Note, that it is important to use `api` instead of `implementation` in `dependencies`. It took me quite some time to find out. 

With this implementation, the aar-file will also be found when the plugin is used in another project.

**Comment by angelschnider** [comment] 2020-09-17 08:13
Hi @Taco55 

I also tried this solution but I used "Implementation". I will try this solution. 
I give you a feedback if it works (or not).

Thank you!

**Comment by angelschnider** [comment] 2020-09-17 09:15
@Taco55 

That works! 

I lost 2 days to solve this. You save my 3rd day! 

Thank you!

**Comment by TahaTesser** [comment] 2020-09-18 07:56
Hi @Taco55 
Based on your https://github.com/flutter/flutter/issues/65333#issue-694885534, I tried to reproduce the issue but even example project files and I get a warning in Android the AAR file doesn't exist 


```
Warning:<i><b>root project 'sample_package': Unable to resolve additional project configuration.</b>
Details: org.apache.tools.ant.BuildException: Basedir C:\Users\Taha\AndroidStudioProjects\sample_package\android\vpnservice does not exist</i>
```

Tried to run the example app from the plugin
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Taha\AndroidStudioProjects\sample_package\android\build.gradle' line: 44

* What went wrong:
A problem occurred evaluating project ':sample_package'.
> Project with path ':vpnservice' could not be found in project ':sample_package'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

There are multiple ways to include aar files, https://github.com/flutter/flutter/issues/65333#issuecomment-694067206 works 
but the issue isn't reproducible based on your description, it clearly says it cannot file 

Directly locating aar also works
```
compile files('libs/file-name.aar')
```

Code Sample
[sample_package.zip](https://github.com/flutter/flutter/files/5244144/sample_package.zip)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.251, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.251 at C:\Code\flutter_master
    • Framework revision d26268bb9e (8 hours ago), 2020-09-18 09:06:26 +0900
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by Taco55** [comment] 2020-09-18 08:55
@TahaTesser I looked to your example and noticed in `settings.gradle` that your refer to `./vpnservice/` while the aar-file is located in a `libs` folder. 

What I omitted in my comment was that I previously had a `build.gradle` file in the same folder as the aar-file (with the same name of the aar-file) to add it as an artifact (although I don't think this should make a difference):

```
configurations.maybeCreate("default")
artifacts.add("default", file('localandroidlibrary.aar'))
```

I see that there were also other methods to solve the issue. That's good to know and thanks for the suggestion! 
For me, the issue can therefore be closed.

**Comment by TahaTesser** [comment] 2020-09-18 10:15
Hi @Taco55 
That's my bad, I tried lot of ways, forgot to revert to origin folder `./vpnservice/`,   tried this as well  https://github.com/flutter/flutter/issues/65333#issuecomment-694067206 hence libs folder 

Yes, I also found other ways we can integrate make it work with aar file 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-18 10:15 UTC
Labels: in triage

**Comment by ismanong** [comment] 2021-01-22 03:02
@Taco55 
Thank you for your research。
Is there a better way? In order not to destroy the architecture of Flutter
