### ISSUE TITLE
Text background color height is inconsistent when english/non-english characters are used together

### ISSUE THREAD

**Issue by edwardez** [flutter/flutter#58846] opened 2020-06-06 05:02 UTC
## Steps to Reproduce
This is reproducible in all places where a background color can be added to text(i.e. `style` within `Text` or `TextSpan`, or in my case, `SelectableText`)
```
class DemoText extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _DemoTextState();
  }
}

class _DemoTextState extends State<DemoText> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Builder(
        builder: (BuildContext buildContext) {
          return Scaffold(
            body: Center(child: SelectableText('test测试test', ))
          );
        },
      ),
    );
  }
}
```

**Expected results:** 
 Height for all background color should  be the same

**Actual results:** 

![demo](https://i.imgur.com/9QsaZGA.jpg)

Non-english characters is higher(here it is "测试"),which makes it looks weird
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, v1.17.3, locale en-US)
    • Flutter version 1.17.3
    • Framework revision b041144f83 (2 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
```

</details>

**Comment by TahaTesser** [comment] 2020-06-08 08:43
Issue is reproducible 

Closing as duplicate of https://github.com/flutter/flutter/issues/54935

**Closed by TahaTesser** 2020-06-08 08:43 UTC
