### ISSUE TITLE
Unable to build plugin frameworks: 2023-04-13 18:54:10.698 xcodebuild[69833:4519474] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled) ** BUILD FAILED **

### ISSUE THREAD

**Issue by hc2088** [flutter/flutter#124781] opened 2023-04-13 11:01 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter clean
rm -rf pubspec.lock
flutter pub get
flutter build ios-framework --no-profile --cocoapods --no-tree-shake-icons

### Actual results

Unable to build plugin frameworks: 2023-04-13 18:54:10.698 xcodebuild[69833:4519474] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

日志输出如下：
Cleaning Xcode workspace...                                      1,538ms
Deleting build...                                                   27ms
Deleting .dart_tool...                                               1ms
Deleting .packages...                                                0ms
Deleting .android...                                                 2ms
Deleting .ios...                                                    17ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in flutter_test_bbb...        13.6s

💪 Building with sound null safety 💪

Building frameworks for com.test.bbb in debug mode...
 ├─Creating Flutter.podspec...                                       4ms
 ├─Building App.xcframework...                                     64.8s
Running pod install...                                              3.0s
 ├─Building plugins...                                           1,941ms
Unable to build plugin frameworks: 2023-04-13 18:54:10.698 xcodebuild[69833:4519474] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
** BUILD FAILED **

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 13.3 22E252 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (1 available)

• No issues found!


```

</details>

**Comment by JherysVargas** [comment] 2023-04-13 15:47
I have the same problem, any solution?

**Comment by huycozy** [comment] 2023-04-14 04:23
Hi, what is your XCode version? Please provide the output of `flutter doctor -v`.

Also, you are using old Flutter version. Please retry on the latest stable (3.7.11) and master channels to see if the issue still occurs or not. 

May be a duplicate of https://github.com/flutter/flutter/issues/124340

**Comment by hc2088** [comment] 2023-04-14 08:03
> Hi, what is your XCode version? Please provide the output of `flutter doctor -v`.
> 
> Also, you are using old Flutter version. Please retry on the latest stable (3.7.11) and master channels to see if the issue still occurs or not.
> 
> May be a duplicate of #124340

Version 14.3 (14E222b)

**Comment by hc2088** [comment] 2023-04-14 08:04
> Hi, what is your XCode version? Please provide the output of `flutter doctor -v`.
> 
> Also, you are using old Flutter version. Please retry on the latest stable (3.7.11) and master channels to see if the issue still occurs or not.
> 
> May be a duplicate of #124340

[✓] Flutter (Channel stable, 2.5.3, on macOS 13.3 22E252 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Volumes/huc/myshared/opt/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (1 year, 6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/a58/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/a58/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 14.3, Build version 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 112.0.5615.49

• No issues found!

**Comment by hc2088** [comment] 2023-04-14 10:15
> It may be fixed in the recent release. Please retry on the latest stable (3.7.11) and master channels to see if the issue still occurs or not.

thanks

**Comment by huycozy** [comment] 2023-04-14 10:53
Given your last message, I feel safe to close this issue. If you experience this issue in the new Flutter versions, please write a comment or file a new issue. Thanks!

**Closed by huycozy** 2023-04-14 10:53 UTC
Labels: in triage

**Comment by DumbDev168** [comment] 2023-04-21 04:02
```
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.2 22D49 darwin-arm64, locale en-KH)
    • Flutter version 3.7.11 on channel stable at /Users/chantheatai/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (9 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/chantheatai/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0
```

**Comment by plumhly** [comment] 2023-04-24 09:47
recreate Scheme solve this problem。

1. remove Runner scheme
2. create Runner scheme

<img width="775" alt="image" src="https://user-images.githubusercontent.com/10388177/233961613-83a05ed1-8e7d-451b-a00c-f72577630562.png">

**Comment by Ashwin-Ani1** [comment] 2023-04-28 19:41
how do you recreate a runner scheme?

**Comment by 8eduardo8** [comment] 2023-04-30 19:05
in this video you can see how to do


https://blog.svenadolph.net/videos/flutter_flavors/schemes.mp4

**Comment by josenadin01** [comment] 2023-05-08 12:04
same problem here, any solutions?

**Comment by rivella50** [comment] 2023-05-08 12:11
There is a similar issue which is still open: https://github.com/flutter/flutter/issues/124835

**Comment by huycozy** [comment] 2023-05-09 09:56
@alefwd @josenadin01 
I try the `ios-framework` build command as mentioned at the original comment but it can build successfully without issue (on the latest stable `3.7.12`). 
Can you please provide the output of the build command with verbose (-v`) so that we may verify the issue?

**Comment by ljmatan** [comment] 2023-05-11 08:36
Problem is not occurring after running `sudo xcode-select -s` with Xcode version 14.2.

**Comment by rivella50** [comment] 2023-05-11 08:45
@ljmatan What CocoaPods version are you using?

**Comment by ljmatan** [comment] 2023-05-11 08:51
`pod --version`

1.12.1

**Comment by huycozy** [comment] 2023-05-12 03:53
>ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
           clang: error: linker command failed with exit code 1 (use -v to see invocation)

@ljmatan Your error is not the same as the original issue (`Unable to build plugin frameworks:`), but it's related to new issue at https://github.com/flutter/flutter/issues/126449. Please follow up on it for further update.

**Comment by ataknakbulut** [comment] 2023-05-12 12:16
I had same issue for 3 days. [This one solved my problem: ](https://stackoverflow.com/a/70923037/9921505)

**Comment by Muthukaliswaran** [comment] 2023-05-18 19:03
> I had same issue for 3 days. [This one solved my problem](https://stackoverflow.com/a/70923037/9921505)

**This solved my problem** good solution



Failed to build iOS app
Error output from Xcode build:
↳
    2023-05-19 00:17:18.228 xcodebuild[19428:107781] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
    ** BUILD FAILED **
