### ISSUE TITLE
[camera] iOS doesn't record audio when used intermittently with video_player

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#70851] opened 2020-11-19 17:59 UTC
## Example code

In a loop, this code records 3-second video clips and plays them back (see `mainloop`).

```dart
import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: CameraTest(),
        ),
      ),
    ),
  );
}

class CameraTest extends StatefulWidget {
  @override
  _CameraTestState createState() => _CameraTestState();
}

class _CameraTestState extends State<CameraTest> {
  @override
  Widget build(BuildContext context) {
    bool cameraInitialized =
        cameraControl != null && cameraControl.value.isInitialized;
    bool isRecording =
        cameraInitialized && cameraControl.value.isRecordingVideo;
    bool videoInitialized =
        videoControl != null && videoControl.value.initialized;
    bool isPlaying = videoInitialized && videoControl.value.isPlaying;

    return Column(
      children: [
        Text(
          "Status: ${isRecording ? "Recording" : isPlaying ? "Playing" : "Idle"}",
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text("camera"),
                ),
                if (cameraInitialized)
                  Column(
                    children: [
                      Container(
                        height: 200,
                        child: AspectRatio(
                          aspectRatio: cameraControl.value.aspectRatio,
                          child: CameraPreview(cameraControl),
                        ),
                      ),
                    ],
                  ),
              ],
            ),
            Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text("video_player"),
                ),
                if (videoInitialized)
                  Center(
                    child: Container(
                      height: 200,
                      child: AspectRatio(
                        aspectRatio: videoControl.value.aspectRatio,
                        child: VideoPlayer(videoControl),
                      ),
                    ),
                  ),
              ],
            ),
          ],
        ),
      ],
    );
  }

  CameraController cameraControl;
  VideoPlayerController videoControl;

  @override
  void initState() {
    super.initState();
    mainloop();
  }

  Future<void> mainloop() async {
    await initCamera();

    while (true) {
      String filePath = await start();
      await Future.delayed(Duration(seconds: 3));
      await stop();
      await playFile(filePath);
    }
  }

  Future<void> initCamera() async {
    List<CameraDescription> cameras = await availableCameras();
    cameraControl = CameraController(
      cameras[1],
      ResolutionPreset.medium,
      enableAudio: true,
    );
    cameraControl.addListener(cameraListener);
    await cameraControl.initialize();
    await cameraControl.prepareForVideoRecording();
  }

  Future<void> cameraListener() async {
    if (mounted) setState(() {});
    if (cameraControl == null) return;
    if (cameraControl.value.hasError) {
      throw cameraControl.value.errorDescription;
    }
  }

  Future<String> start() async {
    Directory folder = await getTemporaryDirectory();
    String filePath = "${folder.path}/${Uuid().v4()}.mp4";
    await cameraControl.startVideoRecording(filePath);
    return filePath;
  }

  Future<void> stop() async {
    await cameraControl.stopVideoRecording();
  }

  Future<void> playFile(String filePath) async {
    VideoPlayerController value = VideoPlayerController.file(File(filePath));
    value.addListener(videoListener);
    await value.initialize();

    setState(() {
      videoControl = value;
    });

    await value.play();

    // wait for completion
    Completer<void> done = Completer();
    value.addListener(() {
      if (value.value.isPlaying || done.isCompleted) return;
      done.complete();
    });
    await done.future;

    // cleanup
    setState(() {
      videoControl = null;
    });
    await WidgetsBinding.instance.endOfFrame;
    await value.dispose();
  }

  void videoListener() {
    if (mounted) setState(() {});
    if (videoControl == null) return;
    if (videoControl.value.hasError) {
      throw videoControl.value.errorDescription;
    }
  }
}
```

## Steps to Reproduce

Run the above example code

**Actual results:** 

- The 1st playback will contain audio
- 2nd and consequent playbacks will not contain audio. 
- Sometimes, the recordings will start with a black screen.

**Expected results:** 

- All recordings have audio
- No recordings start with a black screen.

## Notes 

Tested on a 5th gen iPad running iOS 14.1
Android doesn't seem to suffer from this issue

[See video](https://youtu.be/0rVq77yXM_8)

[See logs](https://gist.github.com/devxpy/84f83a234aff9fef659c5d71fa645df6)

## Version info

```
camera: 0.5.8+11
video_player: 1.0.1
```

```
$ flutter --version
Flutter 1.22.4 • channel unknown • unknown source
Framework • revision 1aafb3a8b9 (6 days ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4
```

<details>
  <summary>Flutter doctor</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, 1.22.4, on Mac OS X 10.14.6 18G4032 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/dev/Tools/flutter
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.6858069/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.1)
    • Android Studio at /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.6858069/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • iPad (mobile)    • 6e87c8716559fb803296cb4e2e39466320cad14a • ios            • iOS 14.1
    • macOS (desktop)  • macos                                    • darwin-x64     • Mac OS X 10.14.6 18G4032 darwin-x64
    • Web Server (web) • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 86.0.4240.198

! Doctor found issues in 1 category.
```

</details>

**Comment by devxpy** [comment] 2020-11-19 19:29
Current workaround - re-init camera before every record:


```dart
import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: CameraTest(),
        ),
      ),
    ),
  );
}

class CameraTest extends StatefulWidget {
  @override
  _CameraTestState createState() => _CameraTestState();
}

class _CameraTestState extends State<CameraTest> {
  @override
  Widget build(BuildContext context) {
    bool cameraInitialized =
        cameraControl != null && cameraControl.value.isInitialized;
    bool isRecording =
        cameraInitialized && cameraControl.value.isRecordingVideo;
    bool videoInitialized =
        videoControl != null && videoControl.value.initialized;
    bool isPlaying = videoInitialized && videoControl.value.isPlaying;

    return Column(
      children: [
        Text(
          "Status: ${isRecording ? "Recording" : isPlaying ? "Playing" : "Idle"}",
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text("camera"),
                ),
                if (cameraInitialized)
                  Column(
                    children: [
                      Container(
                        height: 200,
                        child: AspectRatio(
                          aspectRatio: cameraControl.value.aspectRatio,
                          child: CameraPreview(cameraControl),
                        ),
                      ),
                    ],
                  ),
              ],
            ),
            Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text("video_player"),
                ),
                if (videoInitialized)
                  Center(
                    child: Container(
                      height: 200,
                      child: AspectRatio(
                        aspectRatio: videoControl.value.aspectRatio,
                        child: VideoPlayer(videoControl),
                      ),
                    ),
                  ),
              ],
            ),
          ],
        ),
      ],
    );
  }

  CameraController cameraControl;
  VideoPlayerController videoControl;

  @override
  void initState() {
    super.initState();
    mainloop();
  }

  Future<void> mainloop() async {
    await initCamera();

    while (true) {
      String filePath = await start();
      await Future.delayed(Duration(seconds: 3));
      await stop();
      await playFile(filePath);
    }
  }

  Future<void> initCamera() async {
    if (cameraControl != null) {
      CameraController old = cameraControl;
      setState(() {
        cameraControl = null;
      });
      await WidgetsBinding.instance.endOfFrame;
      await old.dispose();
    }

    List<CameraDescription> cameras = await availableCameras();
    cameraControl = CameraController(
      cameras[1],
      ResolutionPreset.medium,
      enableAudio: true,
    );
    cameraControl.addListener(cameraListener);
    await cameraControl.initialize();
    await cameraControl.prepareForVideoRecording();
  }

  Future<void> cameraListener() async {
    if (mounted) setState(() {});
    if (cameraControl == null) return;
    if (cameraControl.value.hasError) {
      throw cameraControl.value.errorDescription;
    }
  }

  Future<String> start() async {
    if (Platform.isIOS) {
      await initCamera();
    }
    Directory folder = await getTemporaryDirectory();
    String filePath = "${folder.path}/${Uuid().v4()}.mp4";
    await cameraControl.startVideoRecording(filePath);
    return filePath;
  }

  Future<void> stop() async {
    await cameraControl.stopVideoRecording();
  }

  Future<void> playFile(String filePath) async {
    VideoPlayerController value = VideoPlayerController.file(File(filePath));
    value.addListener(videoListener);
    await value.initialize();

    setState(() {
      videoControl = value;
    });

    await value.play();

    // wait for completion
    Completer<void> done = Completer();
    value.addListener(() {
      if (value.value.isPlaying || done.isCompleted) return;
      done.complete();
    });
    await done.future;

    // cleanup
    setState(() {
      videoControl = null;
    });
    await WidgetsBinding.instance.endOfFrame;
    await value.dispose();
  }

  void videoListener() {
    if (mounted) setState(() {});
    if (videoControl == null) return;
    if (videoControl.value.hasError) {
      throw videoControl.value.errorDescription;
    }
  }
}

```

**Comment by TahaTesser** [comment] 2020-11-20 12:02
Hi @devxpy 
Thanks for filing the issue, I can reproduce it on iOS 14, and the workaround works as well, no issues on Android 

### Code Sample
https://github.com/flutter/flutter/issues/70851#issue-746805230

```yaml
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.8+11
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.24
  uuid: ^2.2.2
  video_player: ^1.0.1
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (7 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (1 available)            
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.2

! Doctor found issues in 1 category.
```

</details>

**Comment by aytunch** [comment] 2021-01-02 15:01
@TahaTesser do we know the root cause for this bug?
@devxpy thanks for the workaround but if it is the recommended usage for the camera package, it should be stated in the documentation. I would like to know if it is a solution or a workaround.

**Comment by danielroek** [comment] 2021-01-08 08:59
This issue is a duplicate of [#30689](https://github.com/flutter/flutter/issues/30689).

**Comment by TahaTesser** [comment] 2021-01-12 11:05
Closing as duplicate of https://github.com/flutter/flutter/issues/30689

**Closed by TahaTesser** 2021-01-12 11:05 UTC
Labels: found in release: 1.22, has reproducible steps, p: camera, p: first party, p: video_player, platform-ios, plugin
