### ISSUE TITLE
Support Android application lifecycle

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#3427] opened 2016-04-19 23:53 UTC
Android needs to be able to pause or kill a Flutter app based on memory pressure, then restore the app using a state bundle. Flutter apps needs to support this.

**Comment by abarth** [comment] 2016-04-21 15:29
What kind of support are you looking for?  You'd like to be able to save state to a bundle and then get that state back when restored?  We've been thinking about using the `PageStorage` mechanism for this use case.  If `PageStorage` persisted across Android killing and restoring the app, would that meet your needs?

**Comment by jimbeveridge** [comment] 2016-04-22 16:22
My particular interest is that Android be able to kill the Dart VM to relieve memory pressure. This appears to need the Dart app being able to participate in the lifecycle so it can manage resource, which in turn requires some form of persistence. The persistence mechanism itself should probably be a separate issue.

This bug is not an immediate need, more of a tracking bug as the project moves forward.

**Comment by abarth** [comment] 2016-04-22 17:25
Android is able to kill the Dart VM just by killing the process that contains the Dart VM.  There's nothing particular we need to do to enable that.

The part we're missing is persisting enough state so that when Android restarts the app it comes back in a reasonable state.

**Comment by Hixie** [comment] 2017-10-03 20:20
Closed as dupe of #6827. We do expose the lifecycle state now, we just don't automatically preserve state.

**Closed** 2017-10-03 20:39 UTC
Labels: new feature, ▣ platform-android
