### ISSUE TITLE
It is difficult to try to find the error even which file is throwing this error no hints as we can see other programming languages have it. It should  tell atleast the file error is coming.

### ISSUE THREAD

**Issue by basheir** [flutter/flutter#111805] opened 2022-09-17 10:39 UTC
```
#322    RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#323    RenderObject.layout
package:flutter/…/rendering/object.dart:1915
#324    RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#325    RenderObject.layout
package:flutter/…/rendering/object.dart:1915
#326    RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#327    RenderObject.layout
package:flutter/…/rendering/object.dart:1915
#328    RenderView.performLayout
package:flutter/…/rendering/view.dart:165
#329    RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1757
#330    PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:887
#331    RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:504
#332    WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:892
#333    RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:370
#334    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1146
#335    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1083
#336    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:864
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```
════════════════════════════════════════════════════════════════════════════════
![error flutter](https://user-images.githubusercontent.com/67736569/190852547-f07e4b25-973b-49e2-b419-96eb882936d1.PNG)
![flutter error](https://user-images.githubusercontent.com/67736569/190852650-cbc6b5a8-6f8d-4bcd-8036-f62367adce83.PNG)

**Comment by moffatman** [comment] 2022-09-18 03:20
The hint is the ownership chain. Need to look for `Padding(child: Expanded( ....` in your source code. Since each widget is not tagged with the source line, it can't be known when being processed in another source file.

**Comment by huycozy** [comment] 2022-09-19 08:53
Hi @basheir, please provide the crash log in text format instead of a screenshot for better investigation.
And it will be better if you can provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) based on the hint that **moffatman** commented above. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by huycozy** [comment] 2022-09-23 06:41
Hi @basheir, 
I see there's an open issue addressing the case you described #103264. That issue proposes adding widget information associated with the error in stack trace. You can leave there your comment about your case which will help to raise the issue. 

I will close this issue as a duplicate, so please follow up on it for further updates. If you disagree, please write in the comments and I will reopen it. 
Thank you!

**Closed by huycozy** 2022-09-23 06:41 UTC
Labels: waiting for customer response, in triage
