### ISSUE TITLE
_RenderRangeSelector does not meet its constraints.

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#74803] opened 2021-01-27 11:28 UTC
<details>
<summary>logs</summary>

```bash
When the exception was thrown, this was the stack: 
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2224:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2309:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:2001:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:2003:6)
#4      _RenderRangeSelector.performLayout (package:syncfusion_flutter_sliders/src/range_selector.dart:2911:5)
...
The following RenderObject was being processed when the exception was fired: _RenderRangeSelector#5f86f NEEDS-LAYOUT NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=892.0, h=50.0)
...  semantic boundary
...  size: Size(892.0, 49.0)
...  deferredUpdateDelay: "10000 ms"
...  thumbSize: "Size(20.0, 20.0)"
...  activeDivisorSize: "Size(2.0, 2.0)"
...  inactiveDivisorSize: "Size(2.0, 2.0)"
...  overlaySize: "Size(2.0, 2.0)"
...  tickSize: "Size(1.0, 8.0)"
...  minorTickSize: "Size(1.0, 5.0)"
RenderObject: _RenderRangeSelector#5f86f NEEDS-LAYOUT NEEDS-PAINT
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=892.0, h=50.0)
  semantic boundary
  size: Size(892.0, 49.0)
  deferredUpdateDelay: "10000 ms"
  thumbSize: "Size(20.0, 20.0)"
  activeDivisorSize: "Size(2.0, 2.0)"
  inactiveDivisorSize: "Size(2.0, 2.0)"
  overlaySize: "Size(2.0, 2.0)"
  tickSize: "Size(1.0, 8.0)"
  minorTickSize: "Size(1.0, 5.0)"
...  child: RenderLimitedBox#fe652
...    parentData: offset=Offset(10.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=872.0, h=37.0)
...    size: Size(872.0, 37.0)
...    maxWidth: 0.0
...    maxHeight: 0.0
...    child: RenderConstrainedBox#6dc8f
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=872.0, h=37.0)
...      size: Size(872.0, 37.0)
...      additionalConstraints: BoxConstraints(biggest)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
_RenderRangeSelector does not meet its constraints.
The relevant error-causing widget was: 
  _RangeSelectorRenderObjectWidget file:///Users/xff/android/android-drillclient/syncfusion_flutter_sliders/lib/src/range_selector.dart:1549:12
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by TahaTesser** [comment] 2021-01-27 15:16
hI @chongbo2013 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/syncfusion/flutter-widgets/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-27 15:16 UTC
