### ISSUE TITLE
[Documentation] Incorrect link in tutorial 

### ISSUE THREAD

**Issue by jonkiparsky** [flutter/flutter#132449] opened 2023-08-13 04:10 UTC
The link to "[this advanced version](https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8) of the same app"  on the last page of the "Your first app" tutorial (https://codelabs.developers.google.com/codelabs/flutter-codelab-first#8) takes the user to a "hello world" dart example.

**Comment by opxdelwin** [comment] 2023-08-13 04:47
Are these docs open-source? @Hixie

**Comment by Hixie** [comment] 2023-08-13 21:57
Of course! https://github.com/flutter/codelabs should contain all of them.

**Comment by danagbemava-nc** [comment] 2023-08-14 08:26
Closing this as a duplicate of https://github.com/flutter/flutter/issues/131300

Kindly use this link instead https://dartpad.dev/?id=e7076b40fb17a0fa899f9f7a154a02e8

**Closed by danagbemava-nc** 2023-08-14 08:26 UTC
Labels: in triage
