### ISSUE TITLE
Feature request: Provide a horizontal option for ListWheelScrollView

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#59146] opened 2020-06-10 08:58 UTC
Please provide a horizontal scrolling option for https://api.flutter.dev/flutter/widgets/ListWheelScrollView-class.html

**Comment by TahaTesser** [comment] 2020-06-10 09:43
duplicate of https://github.com/flutter/flutter/issues/25074

**Closed by TahaTesser** 2020-06-10 09:43 UTC

**Comment by giorgio79** [comment] 2020-06-10 10:23
Thanks! Also found this solution meanwhile https://pub.dev/packages/carousel_slider
