### ISSUE TITLE
Failed assertion during paint: 'optimized out' is not true

### ISSUE THREAD

**Issue by jasonta** [flutter/flutter#48284] opened 2020-01-07 07:04 UTC
## Steps to Reproduce

1. Call `canvas.drawImageRect(...)`

Observe the following assertion:

> I/flutter (19958): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (19958): The following assertion was thrown during paint():
I/flutter (19958): 'dart:ui/painting.dart': Failed assertion: line 3715: '\<optimized out\>': is not true.
I/flutter (21810): 
I/flutter (21810): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (21810): more information in this error message to help you determine and fix the underlying cause.
I/flutter (21810): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (21810):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (21810): 
I/flutter (21810): When the exception was thrown, this was the stack:
I/flutter (21810): #2      Canvas.drawImageRect (dart:ui/painting.dart:3715:12)

**Target Platform: Android**
**Target OS version/browser: Version 10**
**Devices: Pixel XL**

## Logs

```
I/flutter (19958): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (19958): The following assertion was thrown during paint():
I/flutter (19958): 'dart:ui/painting.dart': Failed assertion: line 3715: '\<optimized out\>': is not true.
I/flutter (21810): 
I/flutter (21810): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (21810): more information in this error message to help you determine and fix the underlying cause.
I/flutter (21810): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (21810):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (21810): 
I/flutter (21810): When the exception was thrown, this was the stack:
I/flutter (21810): #2      Canvas.drawImageRect (dart:ui/painting.dart:3715:12)
```

```
```

```
```

**Comment by VladyslavBondarenko** [comment] 2020-01-07 09:49
Hi @jasonta 
I see there's an issue addressing the case you described.
Please follow up on [that issue](https://github.com/flutter/flutter/issues/25396),
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-01-07 09:49 UTC

**Comment by jasonta** [comment] 2020-01-07 21:28
> Hi @jasonta
> I see there's an issue addressing the case you described.
> Please follow up on [that issue](https://github.com/flutter/flutter/issues/25396),
> I'm closing the current one as duplicate.
> If you disagree please write in the comments
> and I will reopen it.
> Thank you

@VladyslavBondarenko Thanks for the quick response. As indicated in a comment on that issue, it would be nice if the debug/assert message were made more helpful. I only discovered the specific source of this assert error by searching through the flutter source code. (`ui/painting.dart`) Is there a PR/issue for improving that?

**Comment by klaszlo8207** [comment] 2020-01-25 16:20
+1 for this, I got same messages and I don't know what is happening

**Comment by VladyslavBondarenko** [comment] 2020-01-27 09:41
Hi @jasonta , @klaszlo8207 
Yes, there was https://github.com/dart-lang/sdk/issues/35426 about these issues, which is closed as duplicate of open https://github.com/dart-lang/sdk/issues/34586
