### ISSUE TITLE
este es mi problema al cual no e encontrado ninguna solucion por internet

### ISSUE THREAD

**Issue by julian001-cmd** [flutter/flutter#53758] opened 2020-04-01 15:09 UTC
## Steps to Reproduce

1. ...Sending crash report to Google.
Crash report sent (report ID: 0ef2ca41e734c850)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\chama\AppData\Local\Temp\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
Exited (1)
2. ...
3. ...

## Logs

```
```

```
```

**Comment by VladyslavBondarenko** [comment] 2020-04-01 15:17
Hi @julian001-cmd 
attach please here the file `C:\Users\chama\AppData\Local\Temp\flutter_03.log`,
and if possible a complete minimal code sample to reproduce it
otherwise the issue is not actionable

**Comment by iapicca** [comment] 2020-04-22 10:46
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-04-22 10:46 UTC
Labels: in triage, waiting for customer response
