### ISSUE TITLE
How to pass custom arguments from command line in Flutter?

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#48707] opened 2020-01-13 08:15 UTC
## Use case

i want to use gradle plugins and cli to publish aab to google play，but flutter cli don't accept custom argument.

```shell
flutter build appbundle -t lib/main_${flavorName}.dart --flavor ${flavorName} --target-platform android-arm,android-arm64 --publish-to-play 
```

```groovy
                variant.assemble.doLast {
                    if (!target.hasProperty('publish-to-play')) {
                        return
                    }
                    publishToPlay(target, variant, mergePlay, false)
                }

                target.tasks.findByPath("bundle${variant.name.capitalize()}").doLast {
                    if (!target.hasProperty('publish-to-play')) {
                        return
                    }
                    publishToPlay(target, variant, mergePlay, true)
                }
```

**Comment by jonahwilliams** [comment] 2020-02-28 01:03
Duplicate of https://github.com/flutter/flutter/issues/33418

**Comment by preetjdp** [comment] 2020-03-06 15:56
Hi I would like to point out that this is not a duplicate of #33418 (This mentions how to pass args to gradle).

Would it be possible to have application specific args?
Possibly by modifying this : https://github.com/flutter/flutter/blob/ee476a7bd15732ba64f6783b9304fa855e98ac66/packages/flutter_tools/lib/src/commands/run.dart

**Comment by dheeraj2dj** [comment] 2020-03-20 13:27
I would love to see this feature in Flutter

**Comment by saahithyan** [comment] 2020-04-13 18:15
I have a use case where I want to send multiple arguments while building apk

`flutter build apk --env=<env> --country=<country_code> --location=<loc>`

- env: dev1, dev2, tbd1, tbd2, prd
- country_code: LK, UK
- loc: loc1, loc2

There is no way to achieve this

**Comment by saahithyan** [comment] 2020-04-13 20:46
Until I get a feature like that i'm going with [environment_config](https://pub.dev/packages/environment_config). 

- add dependency in `pubspec.yaml`
- add following line at end of `pubspec.yaml`
```
. environment_config:
  fields:
    env:
    country:
    location:
```
Now I have to split my commands
- `flutter pub get`
- `flutter pub run environment_config:generate --env=tbd2 --country=LK --location=loc1`
- `flutter run`

Second command will create a `environment_config.dart` file in your `lib` with a class name of `EnvironmentConfig` and all your fields as static constants.

Now we can access it like any other dart class file `EnvironmentConfig.env`. 

I'm adding this my `.gitignore` since this will change every time I run my project. And I will make sure to run in these commands in sequence.

**Comment by jonahwilliams** [comment] 2020-04-13 20:49
@saahithyan this bug is about passing arguments to gradle. If you want to pass arguments to dart use dart defines:

```
    --dart-define=<foo=bar>                       Additional key-value pairs that will be available as constants from the String.fromEnvironment, bool.fromEnvironment, int.fromEnvironment, and
                                                  double.fromEnvironment constructors.
                                                  Multiple defines can be passed by repeating --dart-define multiple times.
```

**Comment by fouques1u** [comment] 2020-04-16 15:09
@jonahwilliams I think dart-define is not possible to use right now due to the revert #52041.

**Comment by saahithyan** [comment] 2020-04-22 13:02
@jonahwilliams I get `bash: syntax error near unexpected token newline'` error when I run 

`flutter build apk --dart-define=<foo=bar>`

**Comment by fouques1u** [comment] 2020-04-22 14:57
@saahithyan hmm yeah you shouldn't use <foo=bar>, it's the '>' that causes your error here. it's supposed to work like that : flutter build apk --dart-define=variable="value", later in your code you acces it with String.fromEnvironnment("variable") (which would equal to value).

**Comment by TatsuUkraine** [comment] 2020-05-05 19:20
@fouques1u it seems --dart-define is scheduled to next stable release (at least I hope), it's currently working in beta channel

**Comment by phamnhuvu-dev** [comment] 2020-05-09 14:10
`--dart-define` is working in the stable channel version 1.17

**Comment by TatsuUkraine** [comment] 2020-05-09 15:11
@jonahwilliams I think this issue can be closed since Flutter 1.17 fixes it

@saahithyan you probably can stop using environment config package in favor of Dart Defines (btw, I already updated description in this package)

Also, if anyone curious, I wrote a small article that explains how Dart Defines can be used in Dart, iOS and Android code. Here is a [link](https://medium.com/@tatsu.ukraine/flutter-1-17-no-more-flavors-no-more-ios-schemas-command-argument-that-solves-everything-8b145ed4285d) with examples, how Dart Defines can be used

**Comment by v7lin** [comment] 2020-05-14 02:48
does '--dart-define' support '.env'?

**Comment by v7lin** [comment] 2020-05-14 02:57
flutter/android/ios flavors need more than 10 var

**Comment by TatsuUkraine** [comment] 2020-05-14 06:55
@v7lin it seems it's not( I created proposal issue to add some sort of config file OR .env support to flutter_tools. #56792

**Closed** 2021-05-20 23:19 UTC
Labels: P5, severe: new feature, t: gradle, tool
