### ISSUE TITLE
Flutter Web extremely laggy when scrolling with large number of image rows

### ISSUE THREAD

**Issue by ManishKiranagi** [flutter/flutter#71325] opened 2020-11-27 19:25 UTC
We  have a Flutter website built on channel beta that is used for uploading  images. 
When testing on Chrome, scrolling down when there are large number of image rows it is extremely laggy. We display a circular progress indicator on the images while uploading and this further makes the scrolling unusable, at times getting black frames.

The image elements have a Wrap layout within a Container. Below is  a minimal code that creates the UI for the Images List:
```
  Widget assetsList(BuildContext context, assets) {
    return Container(
      child: Stack(
        children: [
          Wrap(
            children: [
              Wrap(
                spacing: 10,
                runSpacing: 10,
                alignment: WrapAlignment.start,
                runAlignment: WrapAlignment.start,
                direction: Axis.horizontal,
                children: assets
                    .map((asset) => _assetUI(asset))
                    .toList(),
              ),
            ],
          ),
        ],
      ),
    );
  }


Widget _assetUI(asset) {
    return Container(
      width: 200,
      child: Wrap(
        children: [
          Stack(
            children: [
              Opacity(
                opacity: asset.status == UploadStatus.uploading ? 0.10 : 1,
                child: Container(
                  height: 150,
                  width: 200,
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.1),
                    border: Border.all(
                      color: Colors.transparent,
                      width: 3,
                    ),
                    borderRadius: BorderRadius.all(
                      Radius.circular(5),
                    ),
                  ),
                  child: asset.path != null
                      ? Image.network(asset.path)
                      : Text(asset.name),
                ),
              ),
              if (asset.status == UploadStatus.uploading)
                Container(
                  height: 150,
                  child: Align(
                    alignment: Alignment.center,
                    child: CircularProgressIndicator(),
                  ),
                ),
            ],
          ),
        ],
      ),
    );
  }
```

Below is a link to the site in profile mode:
https://focalagent-web-photographer-app-staging.azurewebsites.net/#/photos

Steps to reproduce the issue:
Click on 8 photos tab
Click on the browse button and select over 50 to 100 images to display over 10 rows
Try to scroll down to the upload button - it is extremely laggy
Click on the upload button. This will display the Circular progress indicator on the images, one after the other from the top row which seems to make it more laggy.

Is this standard behaviour when scrolling with large number of images?

**Comment by iapicca** [comment] 2020-11-27 20:47
@ManishKiranagi 
the problem may depend from your implementation and strategy for caching those images,
your code sample seems more a snippet from production code,
can you please provide a minimal **_reproducible_** code sample and your `flutter doctor -v`

**Comment by eyoeldefare** [comment] 2020-11-27 21:33
This highly depends on many factors such as how fast the images are being downloaded from the website you said you're getting these images which might make it look laggy to you. Assuming you're fetching these images for the first time, I suggest you use some sort of future building logic. This also should be moved to Stock overflow.

**Comment by ManishKiranagi** [comment] 2020-11-30 09:39
> This highly depends on many factors such as how fast the images are being downloaded from the website you said you're getting these images which might make it look laggy to you. Assuming you're fetching these images for the first time, I suggest you use some sort of future building logic. This also should be moved to Stock overflow.

@eyoeldefare the images are selected from the local machine. I have noticed that regardless of the size of the images the scrolling is laggy, if there are large number of them resulting in having to scroll. If there are only 1 or 2 rows then the scolling iss fine.

**Comment by ManishKiranagi** [comment] 2020-11-30 09:56
> @ManishKiranagi
> the problem may depend from your implementation and strategy for caching those images,
> your code sample seems more a snippet from production code,
> can you please provide a minimal **_reproducible_** code sample and your `flutter doctor -v`

@iapicca Below is Flutter doctor -v. I will send a minimal reproducible sample as soon as I can.

Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1198], locale en-GB)
    • Flutter version 1.24.0-10.2.pre at C:\src\flutter_windows_1.17.4-stable\flutter
    • Framework revision 022b333a08 (12 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\ManishKiranagi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\ManishKiranagi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!

**Comment by ManishKiranagi** [comment] 2020-11-30 16:02
@iapicca Please find minimal rep code: When there are large number of images are picked resulting in over 10 rows the scrolling becomes laggy. This becomes more pronounced with larger images up to 2MB

```
import 'package:flutter/material.dart';
import 'package:flutter_dropzone/flutter_dropzone.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  DropzoneViewController controller1;
  String message1 = 'Drop something here';
  bool highlighted1 = false;
  List assets = [];
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: const Text('Dropzone example'),
          ),
          body: ListView(
            children: [
              if (assets.length > 0)
                _showAssets(assets)
              else
                buildZone1(context),
              Padding(
                padding: const EdgeInsets.all(30),
                child: Container(
                  width: 100,
                  child: MaterialButton(
                    color: Colors.greenAccent,
                    child: Text('Browse files'),
                    onPressed: () async {
                      var files = await controller1.pickFiles(multiple: true);

                      //files
                      //controller1.pickFiles(multiple: true).then((files) {

                      files.forEach((file) async {
                        var url = await controller1.createFileUrl(file);
                        assets.add(url);
                        //controller1.createFileUrl(file).then((url) {

                        //});
                        //});
                      });
                      setState(() {
                        print('in set state');
                        //assets.add(url);
                      });
                    },
                  ),
                ),
              ),
              Container(height: 400, color: Colors.lightGreen),
              Container(height: 400, color: Colors.redAccent),
            ],
          ),
        ),
      );
  Widget _showAssets(List assets) {
    //print(assets);
    return Wrap(
      children: assets.map((asset) {
        return Container(
          height: 150,
          child: Image.network(asset),
        );
      }).toList(),
    );
  }

  Widget buildZone1(BuildContext context) => Builder(
        builder: (context) => Container(
          height: 200,
          child: DropzoneView(
            operation: DragOperation.copy,
            cursor: CursorType.grab,
            onCreated: (ctrl) => controller1 = ctrl,
            onLoaded: () => print('Zone 1 loaded'),
            onError: (ev) => print('Zone 1 error: $ev'),
            onHover: () {
              setState(() => highlighted1 = true);
              //print('Zone 1 hovered');
            },
            onLeave: () {
              setState(() => highlighted1 = false);
              //print('Zone 1 left');
            },
            onDrop: (ev) {
              print('Zone 1 drop: ${ev.name}');
              setState(() {
                print('in set state');
                message1 = '${ev.name} dropped';
                highlighted1 = false;
              });
            },
          ),
        ),
      );
}
```

pubspec.yaml
```
name: file_upload
description: A new Flutter project.


publish_to: 'none' 

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dropzone: ^1.0.9


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```

**Comment by iapicca** [comment] 2020-11-30 20:47
@ManishKiranagi 
[flutter_dropzone](https://pub.dev/packages/flutter_dropzone) is a 3rd party package, 
if you believe the issue is relate to this component please open an issue in the dedicated [github](https://github.com/deakjahn/flutter_dropzone/issues)
if instead you think it is a bug with flutter 
please provide a minimal reproducible code sample that does not rely on 3rd party packages

regardless the package in use, please consider following [Performance best practices](https://flutter.dev/docs/perf/rendering/best-practices)  and [image caching](https://flutter.dev/docs/cookbook/images/cached-images)

**Comment by darshankawar** [comment] 2020-12-04 07:22
@ManishKiranagi 
As suggested above, please provide a reproducible code sample without any 3rd party plugin code that still shows the issue.
Else, you may need to open this issue in plugin owner's repo.

**Comment by pedromassangocode** [comment] 2020-12-30 10:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 10:45 UTC
Labels: in triage, waiting for customer response
