### ISSUE TITLE
flutter/website uses a very old version of jekyll (2.4.0) which is incompatible with Ruby 2.4

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7317] opened 2016-12-29 16:10 UTC
See me fighting to get the website building on my Mac:
https://github.com/flutter/flutter/issues/7306#issuecomment-269646662

**Comment by mit-mit** [comment] 2016-12-30 14:32
As a datapoint, looks like GitHub Pages is on Jekyll 3.3.1:
https://pages.github.com/versions/

**Comment by mit-mit** [comment] 2016-12-30 14:37
Confirmed that changing the Gemfile from to `gem 'jekyll', '3.3.1'`, and running `bundler update` works on my Mac running Ruby ruby 2.3.1p112 (tested both `bundler exec jekyll build`, and `bundle exec htmlproofer`).

**Comment by mit-mit** [comment] 2016-12-30 15:30
Also worked on a VM running a clean MacOS Sierra image with Ruby 2.4.0p0.

I have submit a PR for this once I get https://github.com/flutter/website/pull/340 landed.

**Closed** 2017-01-06 09:11 UTC
Labels: affects: website
