### ISSUE TITLE
Using Navigator.pop() whilst the keyboard is visible but disappearing (due to pressing the 'done' button) results in cryptic error messages.

### ISSUE THREAD

**Issue by tomc1998** [flutter/flutter#12425] opened 2017-10-06 03:16 UTC
## Steps to Reproduce

Create a view with a text input, and a submit callback listener. In the submit listener, call something like `Navigator.popAndPushNamed()`. This will result in the following error message:

```
E/flutter (11330): 'package:flutter/src/widgets/routes.dart': Failed assertion: line 200 pos 12: '!_transitionCompleter.isCompleted': Cannot reuse a MaterialPageRoute after disposing it.
```

Probably not the best error message to read. 

Through a conversation on the flutter gitter I found that dismissing the keyboard using `Focus.clear(context);` before popping the view resolved the error. 

I propose the error message is changed to be more helpful towards this (seemingly quite common) error case - something like 'If you're popping and pushing a route with a text input, make sure you dismiss the keyboard using `Focus.clear(BuildContext)` before changing the route. Failing to do this results in the navigator trying to double-pop the keyboard.` or something along those lines!

I'd quite like to open a PR for this, I just want to check I haven't totally misunderstood what's going on underneath the hood!

Thanks,

Tom

**Comment by tomc1998** [comment] 2018-11-16 21:36
not sure, just google unfocus keyboard, it's probably been deprecated

**Comment by zoechi** [comment] 2019-02-21 10:09
Is this still an issue?
Can you please post a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by tomc1998** [comment] 2019-02-21 10:33
Fuck this is from ages ago, I don't even have flutter installed anymore, so probably won't get around to reproducing this. Not sure what you want to mark this issue.

**Comment by zoechi** [comment] 2019-02-21 10:40
Thanks for the update!

I'm going to close it as duplicate of #27334
(see also #23984)

If someone runs into this and thinks #27334 or #23984 don't matches, please create a new issue.

**Closed by zoechi** 2019-02-21 10:40 UTC
Labels: f: routes, framework
