### ISSUE TITLE
Render problem with gallery demo

### ISSUE THREAD

**Issue by Cfem** [flutter/flutter#18201] opened 2018-06-05 14:10 UTC
Some render (I think) issues occur while using the gallery demo app downloaded from Google Play (not complied by me)
Shrine demo doesn't show cards while scrolling. While using the Animation demo the text and logos in the app turns into weird characters. For a better understanding I have uploaded a video https://youtu.be/5yhP94L-AGo

**Comment by Cfem** [comment] 2018-06-05 14:32
It is Android 5.0.2 and the phone is Turkcell T 60 which is a mock up version of ZTE Blade S6

**Comment by HansMuller** [comment] 2018-06-05 17:58
Thanks for the update. We believe we have a fix that will be included in the next release of the app.

**Comment by zoechi** [comment] 2018-06-08 12:34
There is a triangle like in #17507, but at the end it also looks a bit like #17716.

**Comment by riterrani** [comment] 2018-06-11 13:42
@HansMuller I tested in my app and I can confirm that is fixed!

**Comment by HansMuller** [comment] 2018-06-11 19:53
@riterrani I am very pleased to hear that! I will pass your comment along to the Skia team.

**Comment by zoechi** [comment] 2018-12-11 15:09
Duplicate of #17507

**Closed by zoechi** 2018-12-11 15:09 UTC
Labels: a: typography, e: device-specific, team: gallery
