### ISSUE TITLE
RenderRepaintBoundary can not capture scenes like camera preview or AR views

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#52082] opened 2020-03-06 06:23 UTC
RenderRepaintBoundary can not capture scenes like camera preview or AR views, can fix it?

**Comment by TahaTesser** [comment] 2020-03-06 08:12
Duplicate of [#18989](https://github.com/flutter/flutter/issues/18989)

**Closed by TahaTesser** 2020-03-06 08:12 UTC

**Comment by qiuguian** [comment] 2020-03-06 08:38
no way to fix it?  just tell me the duplicate issue?

**Comment by TahaTesser** [comment] 2020-03-06 08:46
Hi @qiuguian 

Please follow up the mentioned issue 

Thank you
