### ISSUE TITLE
Gold flake: gold client not ready

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#50121] opened 2020-02-04 18:12 UTC
Originating from #49956 
This passed on a re-run.

https://cirrus-ci.com/task/6635508625309696

```
mp/flutter sdk/packages/flutter/test/cupertino/text_field_test.dart: Cupertino cursor golden (TargetPlatform.macOS)                                                         
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Unexpected Gold tryjobAdd failure.
Tryjob execution for golden file test cupertino.text_field_cursor_test.cupertino_macos.1.png failed
for
a reason unrelated to pixel comparison.
Debug information for Gold:
stdout:
stderr: ERROR: logging before flag.Parse: I0204 01:11:34.738559   64806 auth.go:364] auth.go:364
Read from file /private/tmp/flutter
sdk/bin/cache/pkg/skia_goldens4761/packages/flutter/test/cupertino/serviceAccount.json
Error running command: ''gold client not ready: Gold results fields invalid: Received nil pointer
for GoldResult. At jsonio.go:197 goldclient.go:468 goldclient.go:301 goldclient.go:291
cmd_imgtest.go:338 command.go:835 command.go:919 main.go:42 proc.go:203 asm_amd64.s:1357''
When the exception was thrown, this was the stack:
#0      SkiaGoldClient.tryjobAdd (package:flutter_goldens_client/skia_client.dart:371:9)
<asynchronous suspension>
#1      _AuthorizedFlutterPreSubmitComparator.compare (package:flutter_goldens/flutter_goldens.dart:374:23)
<asynchronous suspension>
#2      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:82:57)
<asynchronous suspension>
#3      AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:924:22)
#6      AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:922:26)
#7      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#9      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:52:28)
#10     _expect (package:test_api/src/frontend/expect.dart:116:26)
#11     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#12     expectLater (package:flutter_test/src/widget_tester.dart:385:10)
#13     main.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter/test/cupertino/text_field_test.dart:523:11)
#26     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1102:17)
#28     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1090:35)
(elided 31 frames from class _FakeAsync, dart:async, dart:async-patch, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Piinks** [comment] 2020-02-04 18:12
cc/ @dnfield @kjlubick

**Comment by kjlubick** [comment] 2020-02-04 19:35
Hmmm... That error reminds me of the time where we had multiple processes accidentally using the same directory. I see skia_goldens4761 in the URL, so I see there's some randomness there - is it possible the RNG is getting seeded poorly or the entropy in the directory names isn't enough to avoid collisions?

**Comment by Piinks** [comment] 2020-02-04 20:46
Could definitely be the case, I thought it looked a bit familiar. I'll monitor to see if it happens again.

**Comment by goderbauer** [comment] 2020-02-12 22:54
We've only seen this once and never since. Closing for now.

**Comment by Hixie** [comment] 2021-02-02 02:25
I just got this:

```
02:14 +4227 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/material/dropdown_test.dart: Having a focused element doesn't interrupt scroll when flung by touch                                        
02:14 +4227 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/material/bottom_app_bar_test.dart: custom shape                                                                                           
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Unexpected Gold tryjobAdd failure.
Tryjob execution for golden file test material.bottom_app_bar.custom_shape.1.png failed for
a reason unrelated to pixel comparison.

Debug information for Gold:
stdout:
stderr: Error running command: ''gold client not ready: Gold results fields invalid: Received nil
pointer for GoldResult. At jsonio.go:197 goldclient.go:586 goldclient.go:318 goldclient.go:308
cmd_imgtest.go:346 command.go:854 command.go:958 main.go:44 proc.go:204 asm_amd64.s:1374''

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.tryjobAdd (package:flutter_goldens_client/skia_client.dart:276:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Unexpected Gold tryjobAdd failure.
Tryjob execution for golden file test material.bottom_app_bar.custom_shape.2.png failed for
a reason unrelated to pixel comparison.

Debug information for Gold:
stdout:
stderr: Error running command: ''gold client not ready: Gold results fields invalid: Received nil
pointer for GoldResult. At jsonio.go:197 goldclient.go:586 goldclient.go:318 goldclient.go:308
cmd_imgtest.go:346 command.go:854 command.go:958 main.go:44 proc.go:204 asm_amd64.s:1374''

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.tryjobAdd (package:flutter_goldens_client/skia_client.dart:276:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════

02:14 +4227 ~14 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/material/bottom_app_bar_test.dart: custom shape [E]                                                                                    
  Test failed. See exception logs above.
  The test description was: custom shape
  

02:14 +4228 ~14 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/material/dropdown_test.dart: Having a focused element doesn't interrupt scroll when flung by touch                                     
02:14 +4229 ~14 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/material/dropdown_test.dart: Having a focused element doesn't interrupt scroll when flung by touch                                     
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8856456671737857760/+/steps/run_test.dart_for_framework_tests_shard_and_subshard_libraries/0/stdout

**Comment by tvolkert** [comment] 2021-04-28 19:05
I just hit this today.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848691986363597648/+/steps/run_test.dart_for_framework_tests_shard_and_subshard_libraries/0/logs/stdout/0?format=raw

**Comment by Piinks** [comment] 2021-05-03 20:59
@kjlubick, @Hixie has reported seeing this more often (sample log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848228147972053712/+/u/run_test.dart_for_framework_tests_shard_and_subshard_libraries/stdout) If we were able to detect this error and retry, would that cause ingestion issues with Gold?

**Comment by Hixie** [comment] 2021-05-03 21:25
I hit it two or three times last week in pre-submit tests.

**Comment by Piinks** [comment] 2021-05-03 21:39
I'm going to see if I can tweak the rng we use to generate the temporary directories for Gold in CI. I don't think this has been reported in post submit, where we have a rate limit on incoming PRs. In presubmit, with the volume of PRs we have open, it may be that we are getting collisions with the number of tests/shards we have running across all of the PRs.

**Comment by Hixie** [comment] 2021-05-03 21:46
Oh interesting, wow.

If you need a number that is guaranteed to not conflict with another PR, the PR number might be a good choice. You could also maybe use the commit hash.

**Comment by Hixie** [comment] 2021-05-03 21:50
Looking at the PR, I think I misunderstood where we're having conflicts. If the problem is needing a unique directory on the local machine, then Directory.createTempSync guarantees no conflicts.

**Comment by Piinks** [comment] 2021-05-03 21:57
I can't remember why we did not go that route before... then again it has been refactored a lot from the original version that ran on Cirrus, then Cirrus+Luci and now just Luci. There may be other opportunities to tighten things up now that we're on a stable CI, will investigate further and update the PR. Thanks! :)

**Comment by kjlubick** [comment] 2021-05-04 11:39
retrying should not cause ingestion issues.

**Closed** 2021-05-07 21:19 UTC
Labels: a: tests, framework, passed secondary triage, team, team: flakes, team: infra
