### ISSUE TITLE
The newly created project cannot be packaged aar

### ISSUE THREAD

**Issue by cowcomic** [flutter/flutter#94854] opened 2021-12-08 11:32 UTC
flutter create test
新创建一个工程
在pubspec.yaml中增加module相关配置
```
  module:
    androidX: true
    androidPackage: com.test.test

```

然后执行build aar进行安卓的打包
报错

### _translated using google translate_

flutter create test
Create a new project
Add module related configuration in pubspec.yaml

 ``` 
  module:
     androidX: true
     androidPackage: com.test.test
```

Then execute build aar to package Android
Report an error

```
flutter build aar
Running "flutter pub get" in test_android...                       653ms

💪 Building with sound null safety 💪

Running Gradle task 'assembleAarDebug'...                        1,149ms


FAILURE: Build failed with an exception.

* Where:
Initialization script '/Users/shimoxuan/tool/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 156

* What went wrong:
Failed to notify build listener.
> assert moduleProject != null
         |             |
         null          false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 764ms


Gradle task assembleAarDebug failed with exit code 1.

```

**Comment by maheshmnj** [comment] 2021-12-08 12:59
Hi @cowcomic, Thanks for filing the issue. to build aar files you need to create a module project 

```
flutter create -t module --org com.example my_flutter
```

and not a normal flutter project `flutter create hello`.

Please see the docs for more details https://docs.flutter.dev/development/add-to-app/android/project-setup

related to https://github.com/flutter/flutter/issues/42214

Closing as working as intended.

**Closed by maheshmnj** 2021-12-08 12:59 UTC
Labels: in triage

**Comment by cowcomic** [comment] 2021-12-09 01:14
> Hi @cowcomic, Thanks for filing the issue. to build aar files you need to create a module project
> 
> ```
> flutter create -t module --org com.example my_flutter
> ```
> 
> and not a normal flutter project `flutter create hello`.
> 
> Please see the docs for more details https://docs.flutter.dev/development/add-to-app/android/project-setup
> 
> related to #42214
> 
> Closing as working as intended.

in document "add to android" and "add to ios" use different command
```
for android
flutter create -t module --org com.example my_flutter

for ios
flutter create --template module my_flutter
```

our flutter project need to add both android and ios
how can i create one flutter project for adding to different platform

**Comment by maheshmnj** [comment] 2021-12-09 05:25
> our flutter project need to add both android and ios

@cowcomic  both commands are same first one specifies a bundle identifier and second one doesn't
