### ISSUE TITLE
Problem with 'flutter build apk' in Github Actions

### ISSUE THREAD

**Issue by jpgSouza** [flutter/flutter#67833] opened 2020-10-10 17:26 UTC
I'm getting this error when i try to run 'flutter build apk':

- **Execution failed for task ':share:compileReleaseJavaWithJavac'.**

- ### **My dependencies below:**
> dependencies:
  flutter:
    sdk: flutter    
  flutter_svg: ^0.19.0
  curved_navigation_bar: ^0.3.4
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.12.9
  firebase_auth: ^0.11.1+12
  firebase_core: ^0.4.0
  bloc_pattern: ^1.5.2
  rxdart: ^0.24.1
  mask_text_input_formatter: ^1.0.7
  image_picker: ^0.6.1
  image_cropper: ^1.0.2
  pdf: ^1.11.2
  firebase_storage: ^3.0.4
  **share: ^0.6.5+2**
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.4
  http: ^0.12.2

- When I remove the share plugin, it works fine. Can someone help me?

**Comment by hamdikahloun** [comment] 2020-10-10 19:01
Hi @jpgSouza 

Can you take a look please at this issue https://github.com/flutter/flutter/issues/66513

**Comment by jpgSouza** [comment] 2020-10-10 19:09
Oh, its the Java version

Thanks **@hamdikahloun**

**Comment by hamdikahloun** [comment] 2020-10-10 19:10
You are welcome

**Comment by TahaTesser** [comment] 2020-10-12 14:36
Hi @jpgSouza 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.  
duplicate of https://github.com/flutter/flutter/issues/66513
Thank you

**Closed by TahaTesser** 2020-10-12 14:36 UTC
