### ISSUE TITLE
[google_sign_in] I don't want to use Firebase in IOS

### ISSUE THREAD

**Issue by Funncy** [flutter/flutter#53394] opened 2020-03-27 06:28 UTC
When I set up google-sign-in, Android could be set up without a firebase. However, IOS had to sign up for Firebase to download GoogleServie-Info.plist. 

I want to set it up without signing up for Firebase.
So I am personally modifying the code and using it.
The question is whether "clientId" is used in "method_channel_google_sign_in.dart". 

I am currently using IOS "clientId" by assigning it to "clientId". 

```Dart
  @override
  Future<void> init(
      {@required String hostedDomain,
      List<String> scopes = const <String>[],
      SignInOption signInOption = SignInOption.standard,
      String clientId}) {
    return channel.invokeMethod<void>('init', <String, dynamic>{
      'signInOption': signInOption.toString(),
      'scopes': scopes,
      'hostedDomain': hostedDomain,
      'clientId': clientId, // I added.
    });
  }
```

**Comment by TahaTesser** [comment] 2020-03-27 08:16
Duplicate of [#36673](https://github.com/flutter/flutter/issues/36673)
please follow the issue there

**Closed by TahaTesser** 2020-03-27 08:16 UTC
