### ISSUE TITLE
TextFormField with textAlign right but Cursor is in the left

### ISSUE THREAD

**Issue by magnocastro** [flutter/flutter#18555] opened 2018-06-18 02:08 UTC
I have a TextFormField with attribute `textAlign: TextAlign.right`, but when i run the app, the cursor indicator is on the left only if contains 1 character, for more character the cursor go to right
![capturar](https://user-images.githubusercontent.com/14947820/41515107-dae159ba-7282-11e8-8c59-4fd8d778a5a2.PNG)

![capturar](https://user-images.githubusercontent.com/14947820/41515134-f5ae38d0-7282-11e8-9a65-2f46f1ab4b48.PNG)

**Comment by zoechi** [comment] 2018-06-18 09:05
somewhat similar to #17625
@Hixie

**Comment by zoechi** [comment] 2018-06-18 10:05
Probably a dup of #18483 which should be fixed in master after the next engine roll.

**Comment by magnocastro** [comment] 2018-06-23 18:28
ok

**Comment by jason-simmons** [comment] 2018-06-28 00:32
Duplicate of https://github.com/flutter/flutter/issues/18483

**Closed by jason-simmons** 2018-06-28 00:32 UTC
Labels: a: text input, framework
