### ISSUE TITLE
how to build x86 platform windows desk application 

### ISSUE THREAD

**Issue by wave314** [flutter/flutter#134803] opened 2023-09-15 05:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1

### Actual results

1

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>
1

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>
1

**Comment by stuartmorgan** [comment] 2023-09-15 10:29
Duplicate of https://github.com/flutter/flutter/issues/37777

> [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

In the future please follow that guide, rather than leaving everything blank.

**Closed by stuartmorgan** 2023-09-15 10:29 UTC
