### ISSUE TITLE
[go_router] ShellRoute builder Widget does not disappear, when go to route, which is not in this ShellRoute

### ISSUE THREAD

**Issue by teceP** [flutter/flutter#113460] opened 2022-10-14 21:09 UTC
Iam using go_router in version 5.0.5 and have an issue which appears when using ShellRoute.

When user is logged in, i get redirected to "/home" route, which is a subroute of a ShellRoute.
This ShellRoute has a builder, which wraps a navigation bar to the screen.

When i route to '/chats/:id' with "GoRouter.of(context).push('/chats/:id')", I expect, that the navigation bar disappears, since it is not inside of the ShellRoute, which delivers the navigation bar, but it doesnt disappear:

![image](https://user-images.githubusercontent.com/44495947/195944867-68387249-a41c-4e8a-9b4f-9e6a4c5be697.png)

Any suggestions how to fix this problem? 
Is it because I need another refreshListenable, which rebuilds the complete GoRouter when chaning the route?

`````
GoRouter(
      debugLogDiagnostics: true,
      refreshListenable:
          GoRouterRefreshStream(BlocProvider.of<AuthCubit>(context)),
      initialLocation: '/welcome',
      redirect: (context, state) {
        final loggedIn =
            BlocProvider.of<AuthCubit>(context).state is AuthStateAuthenticated;
        final isLoggingIn =
            ((state.location == '/welcome') || state.location == '/login') ||
                (state.location == '/register');

        // user should not see login or register screen if already signed in
        if (loggedIn && isLoggingIn) {
          return '/home';
        }

        // if not logged in and not at welcome/login/register screen: go to login - takes also action, when user logs out
        if (!loggedIn && !isLoggingIn) {
          return '/login';
        }

        return null;
      },
      routes: [
        ShellRoute(
          builder: (context, state, child) => Scaffold(
            body: SafeArea(child: child),
          ),
          routes: [
            GoRoute(
              path: '/welcome',
              builder: (context, state) => const WelcomeScreen(),
            ),
            GoRoute(
              path: '/login',
              builder: (context, state) => const LoginScreen(),
            ),
            GoRoute(
              path: '/register',
              builder: (context, state) => const RegisterScreen(),
            ),
          ],
        ),
        ShellRoute(
          builder: (context, state, child) => HireNavigationBar(child: child),
          routes: [
            GoRoute(
              path: '/home',
              builder: (context, state) => const HomeScreen(),
            ),
            GoRoute(
              path: '/overview',
              builder: (context, state) => const OverviewScreen(),
              routes: <GoRoute>[],
            ),
            GoRoute(
              path: '/search',
              builder: (context, state) => const ShopSearchScreen(),
            ),
            GoRoute(
              path: '/shops/:id',
              builder: (context, state) {
                final shopId = state.params['id']!;
                return ShopScreen(
                  shopId: shopId,
                );
              },
            ),
          ],
        ),
        GoRoute(
          path: '/chats',
          builder: (context, state) => const ChatsScreen(),
          routes: <GoRoute>[
            GoRoute(
              path: ':id',
              builder: (context, state) {
                final chatId = state.params['id']!;
                return ChatScreen(
                  chatId: chatId,
                );
              },
            ),
          ],
        ),
      ],
      errorBuilder: ((context, state) {
        return Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  '${state.error} Latest route ${state.location}',
                ),
                TextButton(
                  onPressed: () => context.go('/home'),
                  child: const Text('Go To Home'),
                ),
              ],
            ),
          ),
        );
      }),
    );
`````

**Comment by darshankawar** [comment] 2022-10-17 07:55
@teceP 
Can you provide `flutter doctor -v` ? The code sample you shared seems to have Bloc implementation. In order to properly analyaze the issue, can you provide a [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) without third party code that shows the current behavior you are reporting ? Also, provide what the expected result are you looking for upon running the updated code sample.

Thanks.

**Comment by teceP** [comment] 2022-10-19 06:58
@darshankawar 
Currently, I dont have time to work on other things besided my actual job.
What I expect: when i push to "/chats/:id", I expect that there is not a ShellRoute with a "HireNavigationBar" around it, since it is not defined in my GoRouter:

ShellRoute (HireNavigationBar)
    \\_GoRoute (Home)
   \\_GoRoute (Overview)
   \\_GoRoute (Search)
   \\_GoRoute (Shops)
GoRoute (Chats)

What I can do is to "go" to Chats, instead of "push" to chats. But then I do not have a back button to the previous screen.

````shell
flutter doctor -v
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19044.2130], locale de-DE)
    • Flutter version 3.3.4 on channel stable at C:\Users\mteklic\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mteklic\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\mteklic\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2130]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 106.0.1370.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`````

**Comment by darshankawar** [comment] 2022-10-19 13:19
Thanks for the feedback. Keeping this issue open for further insights from the team on expected behavior.

**Comment by johnpryan** [comment] 2022-10-20 21:40
This is because you are using push(), we will address this along with https://github.com/flutter/flutter/issues/100468

**Comment by stngcoding** [comment] 2022-10-21 04:22
What if I want to hide bottom navigation bar in some specific screen inside ShellRoute? how can I achieve that behavior with go_router

**Comment by johnpryan** [comment] 2022-10-21 18:38
@stngcoding have you tried using [`parentNavigatorKey`](https://pub.dev/documentation/go_router/latest/go_router/GoRoute/parentNavigatorKey.html)?

**Comment by stngcoding** [comment] 2022-10-25 02:22
> 

Sorry for the late reply, using parentNavigatorKey does work in my case, thank you so much

**Comment by leanhro2812** [comment] 2022-12-29 11:10
Same issue!

**Comment by claireliu14** [comment] 2023-08-11 03:34
Refer to this: [https://pub.dev/documentation/go_router/latest/go_router/ShellRoute-class.html](https://pub.dev/documentation/go_router/latest/go_router/ShellRoute-class.html)

It works.

**Comment by chunhtai** [comment] 2023-12-07 18:49
duplicate of https://github.com/flutter/flutter/issues/120665

**Comment by darshankawar** [comment] 2023-12-08 05:11
closing based on above comment as duplicate.

**Closed by darshankawar** 2023-12-08 05:11 UTC
Labels: package, P2, p: go_router, team-go_router, triaged-go_router, multiteam-retriage-candidate
