### ISSUE TITLE
Add the Dotted border  style feature in BoxDecoration 

### ISSUE THREAD

**Issue by parmarravi** [flutter/flutter#89019] opened 2021-08-27 03:24 UTC
The dotted border is sometimes a common feature for styling I believe box decoration should have this feature. Please add this feature

**Comment by chinmaygarde** [comment] 2021-08-30 18:27
Closing this is as a duplicate of https://github.com/flutter/flutter/issues/4858 which was closed as a Wont-Fix.

**Closed by chinmaygarde** 2021-08-30 18:27 UTC
Labels: severe: new feature, framework, engine, f: material design, proposal, passed first triage
