### ISSUE TITLE
Flutter web scroll lags on phone browsers

### ISSUE THREAD

**Issue by MahmoodBakhshayesh** [flutter/flutter#77602] opened 2021-03-08 15:20 UTC
## Details
I have a List of ExpansionTile in MyApp , it is working fine and  smooth on Android IOS and desktop browsers
but is too laggy on phone browsers (safari for Ios and chrome for Android )

i'm using Flutter 2.0.1 stable channel

 [Here is a main.dart file for building similar list](https://gist.github.com/MahmoodBakhshayesh/59b9171119881460e69e92ed1753802f)

**Target Platform:**
web
**Target OS version/browser:**
safari on IPhone and Chrome on Android
**Devices:**
Samsung S10, Iphone 7 

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2021-03-09 10:04
Duplicate of https://github.com/flutter/flutter/issues/59332 and https://github.com/flutter/flutter/issues/56257.

**Closed by pedromassangocode** 2021-03-09 10:04 UTC
Labels: created via performance template

**Comment by MahmoodBakhshayesh** [comment] 2021-04-22 10:50
> Duplicate of #59332 and #56257.

i was creating this issues since flutter 2.0 release and we is in stable branch now

**Comment by pedromassangocode** [comment] 2021-04-22 13:25
> i was creating this issues since flutter 2.0 release and we is in stable branch now

We do track same issues in a single place independently of the Flutter version, what we do is to update the labels of issues that are still present in the latest channel versions.
