### ISSUE TITLE
VM snapshot invalid and could not be inferred from settings. (Running release build gives a crashing app, but debug works fine)

### ISSUE THREAD

**Issue by JayadevHaddadi** [flutter/flutter#55940] opened 2020-04-29 06:20 UTC
I have seen many commentaries on this error but non of the solutions solves it for me.
Running flutter in debug mode is fine but release I get this error upon the app crashes immediately on opening:

```
#### Error
E/flutter (16772): [ERROR:flutter/runtime/dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
E/flutter (16772): [ERROR:flutter/runtime/dart_vm.cc(248)] Could not setup VM data to bootstrap the VM from.
E/flutter (16772): [ERROR:flutter/runtime/dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
F/flutter (16772): [FATAL:flutter/shell/common/shell.cc(268)] Check failed: vm. Must be able to initialize the VM.
```

#### What I have tried:
* Using different flutter versions:
1.12.13 hotfix 6
1.12.13 hotfix 9
1.16.3 dev
* I have tried clean and rebuilding.
* I have played around with the gradle file, specifially buildTypes for release.  Removed whatever is there and added ////            ndk {
////                abiFilters 'armeabi-v7a'//,'arm64-v8a','x86','x86_64'
////            }

**Gradle:** 

android {
    compileSdkVersion 29
    buildToolsVersion = "28.0.2"

    defaultConfig {
        applicationId "org.amritaelearning.ample"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.debug
            applicationIdSuffix ".dev"
        }
        release {
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

**Flutter doctor:** 

[√] Flutter (Channel dev, v1.16.3, on Microsoft Windows [Version 10.0.18363.815], locale en-US)
    • Flutter version 1.16.3 at C:\Users\mreza\Downloads\flutter 16.3 dev
    • Framework revision be3a4b37b3 (5 weeks ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\mreza\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • ASUS X01BDA    • JCAAGF06F945KBL • android-arm64 • Android 9 (API 28)
    • sdk gphone x86 • emulator-5554   • android-x86   • Android 10 (API 29) (emulator)

• No issues found!

<details>
  <summary>Logs running with --release --verbose</summary>

```
[  +30 ms] executing: [C:\Users\mreza\Downloads\flutter 16.3 dev/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +64 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] be3a4b37b3e9ab4e80d45b59bed53708b96d211f
[        ] executing: [C:\Users\mreza\Downloads\flutter 16.3 dev/] git describe --match v*.*.* --first-parent --long --tags
[  +61 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.16.3-0-gbe3a4b37b
[  +10 ms] executing: [C:\Users\mreza\Downloads\flutter 16.3 dev/] git rev-parse --abbrev-ref --symbolic @{u}
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\Users\mreza\Downloads\flutter 16.3 dev/] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +116 ms] executing: [C:\Users\mreza\Downloads\flutter 16.3 dev/] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +43 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +35 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +59 ms] List of devices attached
           JCAAGF06F945KBL        device product:WW_X01BD model:ASUS_X01BDA device:ASUS_X01BD_2 transport_id:2
           emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm transport_id:3
[   +8 ms] C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe -s JCAAGF06F945KBL shell getprop
[  +88 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +115 ms] Found plugin catcher at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\catcher-0.3.5\
[  +20 ms] Found plugin device_info at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\device_info-0.4.2+2\
[   +9 ms] Found plugin flutter_custom_tabs at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\flutter_custom_tabs-0.6.0\
[   +1 ms] Found plugin flutter_full_pdf_viewer at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\flutter_full_pdf_viewer-1.0.6\
[   +5 ms] Found plugin flutter_mailer at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\flutter_mailer-0.5.0-dev.7\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\
[   +8 ms] Found plugin fluttertoast at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\fluttertoast-4.0.1\
[  +23 ms] Found plugin package_info at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+17\
[   +4 ms] Found plugin path_provider at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.7\
[   +2 ms] Found plugin path_provider_macos at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+1\
[  +31 ms] Found plugin shared_preferences at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7\
[   +2 ms] Found plugin shared_preferences_macos at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+7\
[   +5 ms] Found plugin shared_preferences_web at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[  +15 ms] Found plugin url_launcher at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.5\
[   +2 ms] Found plugin url_launcher_macos at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+5\
[   +6 ms] Found plugin url_launcher_web at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[  +13 ms] Found plugin video_player at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.9\
[   +4 ms] Found plugin video_player_web at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.2+1\
[   +2 ms] Found plugin wakelock at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.4+1\
[   +2 ms] Found plugin webview_media at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\webview_media-0.1.2\
[  +69 ms] Found plugin catcher at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\catcher-0.3.5\
[  +12 ms] Found plugin device_info at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\device_info-0.4.2+2\
[   +3 ms] Found plugin flutter_custom_tabs at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\flutter_custom_tabs-0.6.0\
[   +1 ms] Found plugin flutter_full_pdf_viewer at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\flutter_full_pdf_viewer-1.0.6\
[   +3 ms] Found plugin flutter_mailer at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\flutter_mailer-0.5.0-dev.7\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\
[   +3 ms] Found plugin fluttertoast at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\fluttertoast-4.0.1\
[  +13 ms] Found plugin package_info at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+17\
[   +3 ms] Found plugin path_provider at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.7\
[   +1 ms] Found plugin path_provider_macos at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+1\
[   +8 ms] Found plugin shared_preferences at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7\
[   +1 ms] Found plugin shared_preferences_macos at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+7\
[   +1 ms] Found plugin shared_preferences_web at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[   +9 ms] Found plugin url_launcher at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.5\
[   +1 ms] Found plugin url_launcher_macos at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+5\
[   +2 ms] Found plugin url_launcher_web at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[   +4 ms] Found plugin video_player at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.9\
[   +4 ms] Found plugin video_player_web at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.2+1\
[   +1 ms] Found plugin wakelock at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.4+1\
[   +1 ms] Found plugin webview_media at C:\Users\mreza\Downloads\flutter 16.3 dev\.pub-cache\hosted\pub.dartlang.org\webview_media-0.1.2\
[  +94 ms] Generating C:\Android\AndroidStudioProjects\ample_student_app_flutter\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +37 ms] ro.hardware = qcom
[ +108 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree C:\Android\AndroidStudioProjects\ample_student_app_flutter\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +17 ms] Exit code 0 from: C:\Users\mreza\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree C:\Android\AndroidStudioProjects\ample_student_app_flutter\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x3
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="org.amritaelearning.ample.nsdc" (Raw: "org.amritaelearning.ample.nsdc")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x13
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=19)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=20)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
               E: uses-permission (line=21)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: application (line=23)
                 A: android:label(0x01010001)=@0x7f0a0000
                 A: android:icon(0x01010002)=@0x7f090000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:usesCleartextTraffic(0x010104ec)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=30)
                   A: android:theme(0x01010000)=@0x7f0b0000
                   A: android:name(0x01010003)="com.example.ample_flutter_student_app.MainActivity" (Raw: "com.example.ample_flutter_student_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=44)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=48)
                     E: action (line=49)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=51)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: provider (line=55)
                   A: android:name(0x01010003)="com.dataxad.flutter_mailer.FlutterMailerFileProvider" (Raw: "com.dataxad.flutter_mailer.FlutterMailerFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="org.amritaelearning.ample.nsdc.adv_provider" (Raw: "org.amritaelearning.ample.nsdc.adv_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=60)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw: "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f0d0000
                 E: activity (line=65)
                   A: android:theme(0x01010000)=@0x01030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw: "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[   +8 ms] Launching lib\main\main_nsdc.dart on ASUS X01BDA in release mode...
[   +4 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe -s JCAAGF06F945KBL shell -x logcat -v time -t 1
[  +98 ms] Exit code 0 from: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe -s JCAAGF06F945KBL shell -x logcat -v time -t 1
[        ] --------- beginning of main
           04-29 11:40:26.243 D/ThermalEngine( 1074): sensor_wait: msm_therm Wait start. 1000ms
[  +24 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +62 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +57 ms] Building APK
Running Gradle task 'assembleNsdcRelease'...
[  +47 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from C:\Android\AndroidStudioProjects\ample_student_app_flutter\android\gradlew.bat.
[   +1 ms] C:\Android\AndroidStudioProjects\ample_student_app_flutter\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +43 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +224 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +5 ms] executing: [C:\Android\AndroidStudioProjects\ample_student_app_flutter\android/] C:\Android\AndroidStudioProjects\ample_student_app_flutter\android\gradlew.bat -q -Ptarget-platform=android-arm64 -Ptarget=C:\Android\AndroidStudioProjects\ample_student_app_flutter\lib\main\main_nsdc.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleNsdcRelease
[+8071 ms] calculateSha: LocalDirectory: 'C:\Android\AndroidStudioProjects\ample_student_app_flutter\build\app\outputs\apk'/app.apk
[  +71 ms] calculateSha: reading file took 70us
[ +584 ms] calculateSha: computing sha took 583us
[   +5 ms] √ Built build\app\outputs\apk\nsdc\release\app-nsdc-release.apk (43.6MB).
[   +3 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree C:\Android\AndroidStudioProjects\ample_student_app_flutter\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +17 ms] Exit code 0 from: C:\Users\mreza\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree C:\Android\AndroidStudioProjects\ample_student_app_flutter\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x3
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="org.amritaelearning.ample.nsdc" (Raw: "org.amritaelearning.ample.nsdc")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x13
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=19)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=20)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
               E: uses-permission (line=21)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: application (line=23)
                 A: android:label(0x01010001)=@0x7f0a0000
                 A: android:icon(0x01010002)=@0x7f090000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:usesCleartextTraffic(0x010104ec)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=30)
                   A: android:theme(0x01010000)=@0x7f0b0000
                   A: android:name(0x01010003)="com.example.ample_flutter_student_app.MainActivity" (Raw: "com.example.ample_flutter_student_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=44)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=48)
                     E: action (line=49)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=51)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: provider (line=55)
                   A: android:name(0x01010003)="com.dataxad.flutter_mailer.FlutterMailerFileProvider" (Raw: "com.dataxad.flutter_mailer.FlutterMailerFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="org.amritaelearning.ample.nsdc.adv_provider" (Raw: "org.amritaelearning.ample.nsdc.adv_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=60)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw: "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f0d0000
                 E: activity (line=65)
                   A: android:theme(0x01010000)=@0x01030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw: "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[   +3 ms] Stopping app 'app.apk' on ASUS X01BDA.
[   +1 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe -s JCAAGF06F945KBL shell am force-stop org.amritaelearning.ample.nsdc
[ +120 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe -s JCAAGF06F945KBL shell pm list packages org.amritaelearning.ample.nsdc
[ +116 ms] package:org.amritaelearning.ample.nsdc
           package:org.amritaelearning.ample.nsdc.dev
[   +3 ms] executing: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe -s JCAAGF06F945KBL shell cat /data/local/tmp/sky.org.amritaelearning.ample.nsdc.sha1
[  +72 ms] 0e1f99e3f177b29f5eb49ea0d21d537a7d8f4a8b
[        ] Latest build already installed.
[        ] ASUS X01BDA startApp
[        ] executing: C:\Users\mreza\AppData\Local\Android\sdk\platform-tools\adb.exe -s JCAAGF06F945KBL shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true org.amritaelearning.ample.nsdc/com.example.ample_flutter_student_app.MainActivity
[ +144 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=org.amritaelearning.ample.nsdc/com.example.ample_flutter_student_app.MainActivity (has extras) }
[   +1 ms] Application running.
[ +460 ms] E/flutter (23464): [ERROR:flutter/runtime/dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
[        ] E/flutter (23464): [ERROR:flutter/runtime/dart_vm.cc(248)] Could not setup VM data to bootstrap the VM from.
[        ] E/flutter (23464): [ERROR:flutter/runtime/dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
[        ] F/flutter (23464): [FATAL:flutter/shell/common/shell.cc(268)] Check failed: vm. Must be able to initialize the VM.
```

</details>

**Comment by JayadevHaddadi** [comment] 2020-04-29 10:18
Randomly I changed 
        classpath 'com.android.tools.build:gradle:3.4.2'
to 3.5.2
and now it works again... I am very confused if this was the issue...

**Comment by jonahwilliams** [comment] 2020-04-29 15:32
Duplicate of https://github.com/flutter/flutter/issues/54126

**Closed by jonahwilliams** 2020-04-29 15:32 UTC
Labels: severe: crash
