### ISSUE TITLE
Status bar color changes when using `showLicensePage` and `primarySwatch`

### ISSUE THREAD

**Issue by KristofKekesi** [flutter/flutter#98065] opened 2022-02-08 22:04 UTC
## Steps to Reproduce

1.  Set `primarySwatch` a vibrant color (#E8672D in my case), where on top of that the text color would be white.
2. Click on a button that executes `showLicensePage(context: context);`
3. When closing the page, the white text on the status bar remains.

**Expected results:** 
Change the status bar color back to the old one.

**Actual results:** 
Keeps the new status bar color.

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.454, on macOS 12.1 21C52 darwin-arm, locale en-HU)
    • Flutter version 2.11.0-0.0.pre.454 at /Users/kristofkekesi/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 965397cfde (26 hours ago), 2022-02-07 11:05:14 -0800
    • Engine revision 0712096899
    • Dart version 2.17.0 (build 2.17.0-85.0.dev)
    • DevTools version 2.10.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kristofkekesi/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile)      • A57B83DD-3F7D-4617-B783-992AA196432C • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPhone 13 mini (mobile) • 5EEF38D4-F42C-4546-A4C2-E1E8E1D25C85 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 98.0.4758.80
    ! Error: Kristóf’s iPhone 11 is busy: Waiting to connect and unlock the device. Xcode will continue when Kristóf’s
      iPhone 11 is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

Before opening the license page (correct status bar color).
<img width="369" alt="Screenshot 2022-02-09 at 2 10 07 PM" src="https://user-images.githubusercontent.com/67046386/153157765-6018c64d-a870-480e-827b-22f66ca7c798.png">

Opening the license page sets the status bar's color white.
<img width="340" alt="Screenshot 2022-02-09 at 2 10 19 PM" src="https://user-images.githubusercontent.com/67046386/153157809-fb5002ff-3aa1-4fde-81df-4c231e86c1fb.png">

After opening the license page (incorrect color).
<img width="360" alt="Screenshot 2022-02-09 at 2 10 32 PM" src="https://user-images.githubusercontent.com/67046386/153157837-f2beeea3-3662-4c2b-a75f-8ac6d3ea3801.png">

**Comment by darshankawar** [comment] 2022-02-09 08:44
Based on the description, I came up with below code sample wherein, I set `primarySwatch: Colors.deepOrange`. Running the code on latest master and stable on an iOS device results in following:

<details>
<summary> complete code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    theme: ThemeData(
      primarySwatch: Colors.deepOrange
    ),
    home: SettingsPage(),
  ));
}

class SettingsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Center(
          child: ElevatedButton(
            onPressed: () {
              showLicensePage(
                context: context,
              );
            },
            child: Text('Show Licenses'),
          ),
        ),
      ),
    );
  }
}

```

</details>

1. When app launches, the status bar items text is in black:

<img width="347" alt="Screenshot 2022-02-09 at 2 00 22 PM" src="https://user-images.githubusercontent.com/67046386/153156708-0a20c84e-54b2-4930-8337-8dd5f373bd52.png">

2. Tapping on `Show Licenses` makes the status bar items text go white:

<img width="348" alt="Screenshot 2022-02-09 at 2 00 32 PM" src="https://user-images.githubusercontent.com/67046386/153156808-2b00ba1c-9d2b-44ec-893c-efe524d1be81.png">

3. Coming back to previous page still keeps the status bar items text in white:

<img width="349" alt="Screenshot 2022-02-09 at 2 00 41 PM" src="https://user-images.githubusercontent.com/67046386/153156886-d97a14fc-a5b2-4828-8965-87294c67329f.png">


<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel master, 2.11.0-0.0.pre.487, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.487 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3bdea6bb92 (4 hours ago), 2022-02-08 20:11:08 -0800
    • Engine revision 7bf74069a5
    • Dart version 2.17.0 (build 2.17.0-87.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.11.0-0.0.pre.487, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.487 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3bdea6bb92 (44 minutes ago), 2022-02-08 20:11:08 -0800
    • Engine revision 7bf74069a5
    • Dart version 2.17.0 (build 2.17.0-87.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment] 2022-02-09 10:27
Hi everyone
This is issue is not related licensePage but systemChrome and route, see https://github.com/flutter/flutter/issues/67871
New route is changing the status bar brightness due to Appbar (ex: License page has Appbar), when popping back to previous page, this brightness is not updated for some reason.

It can be reproduced using code sample
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    home: HomePage(),
  ));
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute<void>(
              builder: (BuildContext context) => Scaffold(
                appBar: AppBar(),
              ),
            ));
          },
          child: const Text('Show New Page'),
        ),
      ),
    );
  }
}
```
You could find a way using `RouteObserver` and change back the status bar brightness.

This is a duplicate of https://github.com/flutter/flutter/issues/67871 (i will look into that issue)

**Closed by TahaTesser** 2022-02-09 10:27 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 2.10, found in release: 2.11

**Comment by KristofKekesi** [comment] 2022-02-09 12:41
@TahaTesser Thanks for working on this issue. You're awesome 🥳.
