### ISSUE TITLE
[webview_flutter][android] Crash on console message.

### ISSUE THREAD

**Issue by kristoffer-zliide** [flutter/flutter#141572] opened 2024-01-15 13:53 UTC
### Steps to reproduce

Not actually sure, except just use the web view.

### Expected results

I expected my app to not crash.

### Actual results

The app crashed.

### Code sample

Sorry, don't have that.

### Logs

<details open><summary>Logs</summary>

```console
W/System.err(30979): 	at io.flutter.plugins.webviewflutter.WebChromeClientFlutterApiImpl.onConsoleMessage(WebChromeClientFlutterApiImpl.java:180)
W/System.err( 30979): 	at io.flutter.plugins.webviewflutter.WebChromeClientHostApiImpl$WebChromeClientImpl.onConsoleMessage(WebChromeClientHostApiImpl.java:114)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22631.3007], locale ...)
    • Flutter version 3.13.9 on channel stable at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at ...
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code (version 1.85.1)
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
...

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.```

</details>

**Comment by dam-ease** [comment] 2024-01-15 14:27
Thanks for filing this @kristoffer-zliide.
From the logs, this seems similar to https://github.com/flutter/flutter/issues/136797.
Kindly upvote, comment on your findings and follow up on that issue for updates.
Closing this as a duplicate of the already existing issue, if you disagree, please comment and I'll reopen this.
Thank you!

**Closed by dam-ease** 2024-01-15 14:27 UTC
Labels: in triage

**Comment by kristoffer-zliide** [comment] 2024-01-16 08:24
Yes it is, thanks. Sorry for not spotting that.
