### ISSUE TITLE
ContainerLayers with BlendMode look inconsistent

### ISSUE THREAD

**Issue by pskink** [flutter/flutter#93378] opened 2021-11-10 08:43 UTC
with the following `RenderObject` only in case of `ColorFilterLayer` the green rectangle is inside the red one since it is drawn with `BlendMode.srcIn`, is it by mistake and blend modes should not be honored in `ContainerLayer`'s painter code?

```
class FooWidget extends LeafRenderObjectWidget {
  @override
  RenderObject createRenderObject(BuildContext context) => _RenderFooWidget();
}

class _RenderFooWidget extends RenderProxyBox {
  @override
  void performLayout() {
    size = Size(constraints.maxWidth, 7 * 150.0);
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    context.pushLayer(OffsetLayer(offset: offset), _offsetPainter, offset);
  }

  double y = 0;
  TextPainter tp;
  _offsetPainter(PaintingContext context, Offset offset) {
    y = 0;
    final layers = [
      OffsetLayer(offset: Offset.zero),
      ClipRectLayer(clipRect: Offset.zero & size),
      ClipRRectLayer(clipRRect: RRect.fromRectAndRadius(Offset.zero & size, Radius.zero)),
      ClipPathLayer(clipPath: Path()..addRect(Offset.zero & size)),
      ColorFilterLayer(colorFilter: ColorFilter.mode(Colors.black, BlendMode.dst)),
      TransformLayer(transform: Matrix4.identity()),
      OpacityLayer(alpha: 255),
    ];
    layers.forEach((childLayer) {
      tp = TextPainter(
        text: TextSpan(text: childLayer.toString(), style: TextStyle(color: Colors.black)),
        textDirection: ui.TextDirection.ltr,
      );
      tp.layout();
      context.pushLayer(childLayer, _layerPainter, offset);
    });
  }

  _layerPainter(PaintingContext context, Offset offset) {
    context.canvas.drawRect(Rect.fromLTWH(100, y + 0, 100, 100), Paint()..color = Colors.red);
    context.canvas.drawRect(Rect.fromLTWH(150, y + 50, 100, 100), Paint()..color = Colors.green..blendMode = BlendMode.srcIn);
    tp.paint(context.canvas, Offset(0, y));
    y += 150;
  }
}

```

the following image shows `FooWidget` - all layers are drawn the same way except for `ColorFilterLayer` - only with that layer the green rectangle drawn with `Paint()..color = Colors.green..blendMode = BlendMode.srcIn` seems to be drawn correctly, so the question is if all other layers have bugs or `ColorFilterLayer` is buggy?

![blend](https://user-images.githubusercontent.com/5962376/141280068-c584dc55-e1e8-45fd-a83c-7253796d6200.png)

`flutter doctor` output:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, 2.7.0-3.0.pre, on LMDE 4 (debbie) 4.19.0-8-amd64, locale en_US.UTF-8)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
> [✓] Chrome - develop for the web
> [✓] Linux toolchain - develop for Linux desktop
> [✓] Android Studio (version 4.0)
> [✓] Android Studio (version 3.4)
> [✓] Android Studio (version 3.6)
> [✓] Android Studio (version 3.5)
> [✓] IntelliJ IDEA Community Edition (version 2017.1)
> [✓] VS Code (version 1.62.0)
> [✓] Connected device (2 available)
> 
> • No issues found!
>

**Comment by darshankawar** [comment] 2021-11-11 07:32
@pskink 
Thanks for the report. Can you please provide `flutter doctor -v` along with actual vs expected behavior ?

**Comment by pskink** [comment] 2021-11-11 10:14
added an image and "flutter doctor" output

**Comment by darshankawar** [comment] 2021-11-12 05:33
Thanks for the update. I see the same behavior on latest stable and master.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.6.0-12.0.pre.701, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.701 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 24b9346c9b (5 hours ago), 2021-11-11 16:45:40 -0800
    • Engine revision aaacb670af
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

> if all other layers have bugs or `ColorFilterLayer` is buggy?

Will leave it for team to comment on it.

**Comment by chinmaygarde** [comment] 2021-11-15 18:50
cc @flar

**Comment by flar** [comment] 2021-11-15 19:59
First, to understand SrcIn, it draws within the alpha of its background. If you have a large surface with an opaque white bg, and then you draw a red rectangle on top of it, it is still a large opaque surface, just some of the pixels have a different color (red). If you then draw a green rectangle anywhere on this surface with SrcIn, it will just be a green rectangle. SrcIn is no different than SrcOver in the case of rendering to a large surface full of opaque pixels. That is why most of the examples look like a green rectangle partially overlapping a red rectangle - they were all drawn on the background surface which was filled with opaque white.

The ColorFilterLayer is different because it involves a graphical `saveLayer` which isolates its children in order to apply the ColorFilter to them. It must first accumulate the output of its children and then filter them. This graphical layer starts out transparent. In that one case the rendering becomes an opaque red rectangle on a transparent surface and when the SrcIn green rectangle is drawn over it, it can only affect the opaque pixels that only exist in the bounds of the red rectangle.

I can see how the terminology used in the names of the classes can cause confusion here, though.

Most of the `...Layer` classes don't represent a separate graphical rendering layer as in a `saveLayer`, they represent a group of objects with some sort of modification applied to them.

Sometimes that modification requires a saveLayer to do its work (such as in ColorFilterLayer or ImageFilterLayer). I would have thought that the OpacityLayer - which operates via a `saveLayer` as well, would have also shown the "clipping" of the green rectangle as did the ColorFilterLayer, but the results for that layer were not shown in the image attached above.

In other cases the layers don't really require graphically capturing/separating the pixels of the children. OffsetLayer, for example, just offsets its children which it can do through a modification of the transform matrix. Clipping just requires the installation and removal of a clip. Though a clip layer that uses the `antialiasWithSaveLayer` behavior will also show the intersection of the green rectangle because it needs to isolate the child rendering before applying the clip mask.

This all stems from a confusion over the use of the term `Layer` in the framework classes and how that implies a connection with a `saveLayer` type of graphical operation.

**Comment by pskink** [comment] 2021-11-16 15:57
thanks a lot for explaining that it uses `saveLayer` under the hood- i thought that `ColorFilterLayer` do that in some other "magical" way

as for `OpacityLayer` - it renders as any other layer (that is big green rect on top of big green one) - are you sure `OpacityLayer` uses `saveLayer` as well? i learned from the docs that `saveLayer` is an expensive operation so how `RenderAnimatedOpacityMixin` can efficiently manage "opacity animation" if it uses `saveLayer` in `OpacityLayer` (https://github.com/flutter/flutter/blob/c19845a8c3/packages/flutter/lib/src/rendering/proxy_box.dart#L1008)?

**Comment by flar** [comment] 2021-11-16 18:08
Ah, I see. You are using an OpacityLayer with an alpha of 255 which omits the layer. If you change the alpha (even to 254) then it will use the saveLayer.

There is a bug about this behavior (https://github.com/flutter/flutter/issues/58425) of omitting the layer when alpha is 255. That issue describes a break in the raster caching performance, but you've just created a case that demonstrates how doing so also creates an inconsistency of its output.

**Comment by pskink** [comment] 2021-11-16 18:39
@flar yes indeed, i check it and when run with `alpha: 254` it forces `saveLayer` and "clipped" green rectangle

**Comment by jonahwilliams** [comment] 2024-09-08 23:59
I believe this is WAI and I'm closing the issue.

**Closed by jonahwilliams** 2024-09-08 23:59 UTC
Labels: engine, a: quality, c: rendering, has reproducible steps, P2, found in release: 2.5, found in release: 2.6, team-engine, triaged-engine
