### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by uniqlydev** [flutter/flutter#157789] opened 2024-10-29 14:29 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.0, on macOS 15.0.1 24A348 darwin-arm64, locale en-PH)
    [32m•[39m Flutter version 3.24.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.24.0/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 80c2e84975 (3 months ago), 2024-07-30 23:06:49 +0700
    [32m•[39m Engine revision b8800d88be
    [32m•[39m Dart version 3.5.0
    [32m•[39m DevTools version 2.37.2

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html

**Comment by danagbemava-nc** [comment] 2024-10-30 06:10
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-10-30 06:10 UTC
Labels: in triage
