### ISSUE TITLE
[IOS] Text Rendering issue on iPhone8/iPhone SE

### ISSUE THREAD

**Issue by kasperpeulen** [flutter/flutter#94237] opened 2021-11-26 10:19 UTC
I'm writing a little blog post about Flutter.
I wanted to talk a bit about using Flutter without any Context container such as MaterialApp.

So I started with this, which I thought is the most basic Hello World app, you can get get without using such a container:

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(
    Directionality(
      textDirection: TextDirection.ltr,
      child: Text('Hello World!'),
    ),
  );
}
```

What suprises me is that this looks different in every platform I tried it on:

Web:
![image](https://user-images.githubusercontent.com/1035299/143564419-5ffc36f0-a8bc-421e-a19d-bfa750784cc9.png)

MacOS:
![image](https://user-images.githubusercontent.com/1035299/143564563-a457d87c-67e9-4d91-b584-4169bf04dd4e.png)

iPhone 8/iPhone SE:
<img src="https://user-images.githubusercontent.com/1035299/143564613-addefd96-07e4-4773-9010-a6fb46fc495a.png" width ="300">

iPhone 11:
<img src="https://user-images.githubusercontent.com/1035299/143564833-9dc2481f-283b-40dc-a2a3-af4edb791de6.png" width ="300">

I'm not sure if this is a bug or a feature 😅 .
Black on white on web.
White on white on MacOS.
White on black on iPhone.
And weird font rendering on iPhone 8.

**Comment by maheshmnj** [comment] 2021-11-29 08:50
Hi @kasperpeulen, Thanks for filing the issue. I can reproduce the same behavior as you on `stable 2.5.3`, The different color issue is being tracked here https://github.com/flutter/flutter/issues/73968. Please follow up on the linked issue for further updates.

> And weird font rendering on iPhone 8.

This does seem like an issue. I can reproduce it on stable and the master channel.

<img src="https://user-images.githubusercontent.com/31410839/143832559-7ad366d7-75da-4312-8e80-2b7f142c03ea.png" width ="300">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.789, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.789 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ae721de3d (8 days ago), 2021-11-21 15:22:37 -0500
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • F6158AAA-3FA7-4B6E-BF29-7A8CB237E895 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • F6158AAA-3FA7-4B6E-BF29-7A8CB237E895 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
</details>

**Comment by chinmaygarde** [comment] 2021-11-29 19:27
The background depends on the embedder (along with stuff like whether dark mode is enabled). The engine won't use a default clear color on the on-screen renderbuffer before rendering. You would have to do that yourself.

Are you able to reproduce the iPhone 8 issue on an actual device? That is definitely not expected and I wonder if that is because the simulator is being scaled. I'll try to reproduce this myself to make sure.

> I'm not sure if this is a bug or a feature 😅 .

Besides the iPhone 8 issue that will have to dig deeper to explain, that is your call. Perhaps you are finding that "the most basic Hello World app" is indeed too basic to handle stuff like adding a default clear color, notches and rounded corners.

**Comment by chinmaygarde** [comment] 2023-09-19 01:54
Closing this as working as intended. There are widgets and utilities for handling stuff like clears, notches (via window metrics), etc.

**Closed by chinmaygarde** 2023-09-19 01:54 UTC
Labels: e: device-specific, platform-ios, engine, a: typography, c: rendering, has reproducible steps, P2, found in release: 2.5, found in release: 2.6, team-ios, triaged-ios, multiteam-retriage-candidate
