### ISSUE TITLE
Support for Horizontally Scrollable SliverList within a Vertically Scrollable CustomScrollView

### ISSUE THREAD

**Issue by ahmedghaly15** [flutter/flutter#158914] opened 2024-11-14 08:39 UTC
### Use case
**Description**
Currently, Flutter’s SliverList does not support horizontal scrolling, making it challenging to create layouts where a SliverList scrolls horizontally within a vertically scrollable CustomScrollView. This limitation requires workarounds, such as embedding a horizontal ListView inside a SliverToBoxAdapter, but these solutions can be less efficient and may not perform as well, especially when working with large or dynamic datasets.

A common design pattern in modern mobile apps is to have vertically scrolling screens that contain horizontally scrollable lists within specific sections. This layout is frequently seen in media, e-commerce, and social networking apps, where users can browse through multiple horizontal lists (e.g., featured items, popular categories) within a vertically scrolling screen.

Currently, implementing this pattern in Flutter requires the following workaround:

Embedding a horizontal ListView inside a SliverToBoxAdapter, which is placed within a CustomScrollView.
While functional, this approach can be suboptimal as it does not fully leverage the SliverList’s performance optimizations.

### Proposal

**Expected Behavior**
Provide a SliverList (or similar sliver widget) that can scroll horizontally within a CustomScrollView configured for vertical scrolling, allowing it to:

1. Integrate natively with the sliver architecture for better performance.
2. Avoid workarounds that require fixed height constraints and potentially less efficient layouts.

**Example**
```dart
CustomScrollView(
  slivers: [
    const SliverToBoxAdapter(
      child: Text('Vertical Content Before Horizontal List')
    ),
    SliverList.builder(
      scrollDirection: Axis.horizontal,
      itemBuilder: (context, index) => Container(
        width: 150,
        color: Colors.blueAccent,
        child: Center(child: Text('Item $index')),
      ),
      itemCount: 10,
    ),
    const SliverToBoxAdapter(
      child: Text('Vertical Content After Horizontal List')
    ),
  ],
);
```
**Current Workaround**
Using a `SliverToBoxAdapter` with a horizontally scrolling `ListView` inside:
```dart
SliverToBoxAdapter(
  child: SizedBox(
    height: 150,
    child: ListView.builder(
      scrollDirection: Axis.horizontal,
      itemCount: 10,
      itemBuilder: (context, index) => Container(
        width: 120,
        color: Colors.blueAccent,
        child: Center(child: Text('Item $index')),
      ),
    ),
  ),
)
```

**Justification**
This feature would enable developers to follow Flutter’s compositional philosophy more closely by creating layouts that are optimized for smooth, efficient scrolling without having to resort to complex workarounds. It would also help achieve a design pattern commonly used in mobile applications with a more declarative approach, consistent with Flutter’s SliverList and SliverGrid for vertical scrolling.

**Comment by Piinks** [comment] 2024-11-19 23:56
Hey @ahmedghaly15 thanks for reporting. I think this is a duplicate of https://github.com/flutter/flutter/issues/73786 so I am going to close this issue to refer there.

We likely would not reimplement SliverList to configure scroll direction, as SliverList does not currently handle that. The enclosing ScrollView does through the Scrollable widget and the viewport.

**Closed by Piinks** 2024-11-19 23:56 UTC
Labels: framework, f: scrolling, c: proposal, team-framework
