### ISSUE TITLE
Global key error using Slivers

### ISSUE THREAD

**Issue by fede-da** [flutter/flutter#78701] opened 2021-03-20 16:57 UTC
Compiler gave me this error, telling me to report it on GitHub  :

```
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
CustomScrollView

```
And later : 
```
Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.

```
Flutter doctor : 
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-IT)
    • Flutter version 2.0.3 at /Users/mac.fede/Desktop/flutter
    • Framework revision 4d7946a68d (2 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mac.fede/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/mac.fede/Library/Android/sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • 95BD2A9B-D974-4405-8A30-F90594F3796F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

! Doctor found issues in 1 category.

```
This is my code : 
```
return CustomScrollView(
      slivers: <Widget>[
        SliverList(
          delegate: SliverChildListDelegate(contentsList(artista)),
        ),
        index != 2
            ? SliverGrid.count(
                crossAxisCount: 2,
                mainAxisSpacing: 10,
                crossAxisSpacing: 10,
                children: tmpList,
              )
            : SliverList(
                delegate: SliverChildListDelegate(tmpList),
              ),
      ],
      //children: contentsList(artista),
    );
```
Hope this helps!

**Comment by iapicca** [comment] 2021-03-20 17:04
@fede-da 
can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by fede-da** [comment] 2021-03-20 17:08
> @fede-da
> can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Sure, by the way solved the issue after restarting application. I think it was something temporary.

**Comment by iapicca** [comment] 2021-03-20 20:28
> Sure, by the way solved the issue after restarting application

@fede-da 
if the issue is solved consider closing the issue

**Comment by darshankawar** [comment] 2021-03-22 11:42
> > @fede-da
> > can you provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> 
> Sure, by the way solved the issue after restarting application. I think it was something temporary. For the minimal reproducible example, what do you need? I think this is enough but I can provide more informations.

Closing this based on your comment. If you disagree or see similar issue again, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-03-22 11:42 UTC
Labels: in triage
