### ISSUE TITLE
[Flutter 3.3] Fatal crash with `java.lang.AssertionError` when selecting text in `TextField`

### ISSUE THREAD

**Issue by feimenggo** [flutter/flutter#110640] opened 2022-08-31 01:56 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Watch the demo video
3. The application is crashing

**Expected results:** 
Select all

**Actual results:** 
See a crash

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
2022-08-31 09:40:13.704 4255-4255/com.example.editor_demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.editor_demo, PID: 4255
    java.lang.AssertionError: Unexpected metaState 0 for key 0x200000102 during an ACTION_down event.
        at io.flutter.embedding.android.KeyEmbedderResponder.synchronizePressingKey(KeyEmbedderResponder.java:152)
        at io.flutter.embedding.android.KeyEmbedderResponder.handleEventImpl(KeyEmbedderResponder.java:264)
        at io.flutter.embedding.android.KeyEmbedderResponder.handleEvent(KeyEmbedderResponder.java:381)
        at io.flutter.embedding.android.KeyboardManager.handleEvent(KeyboardManager.java:224)
        at io.flutter.plugin.editing.InputConnectionAdaptor.sendKeyEvent(InputConnectionAdaptor.java:279)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:687)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:111)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

```



```

```
```

</details>

https://user-images.githubusercontent.com/12608693/187575596-2cdf295c-22e1-4c05-942e-305ea30725f0.mp4

**Comment by Altamimi-Dev** [comment] 2022-08-31 08:02
i got he same issue with my app using the bottom sheet makes the app crash, might be something with the constrains.
waiting for a fix

**Comment by AlexV525** [comment] 2022-08-31 09:12
@feimenggo @Altamimi-Dev Can you guys provide device info for the issue? Including:
- Model name
- System name
- system version

**Comment by feimenggo** [comment] 2022-08-31 09:24
> @feimenggo @Altamimi-Dev Can you guys provide device info for the issue? Including:
> 
> * Model name
> * System name
> * System version

![413A9CB4-CBE3-42DF-AEF5-82E776ACD49D](https://user-images.githubusercontent.com/12608693/187645668-f2733dc8-a109-4c47-ae27-2b8c10654b30.png)

**Comment by zmtzawqlp** [comment] 2022-08-31 09:26
https://user-images.githubusercontent.com/16477333/187646179-093af616-0628-4a3f-bba5-76bd5a879e25.mov

**Comment by justinmc** [comment] 2022-08-31 09:53
Can anyone confirm if this is a regression?

**Comment by AlexV525** [comment] 2022-08-31 10:07
We previously have the quite same issue https://github.com/flutter/flutter/issues/108124. cc @dkwingsmt

**Comment by AlexV525** [comment] 2022-08-31 10:23
Can everyone facing the issue verify if it's still reproducible on the master channel?

**Comment by Altamimi-Dev** [comment] 2022-08-31 13:26
> 

i keep getting this error on master:
`Launching lib/main.dart on iPhone 13 Pro in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        10.8s
Xcode build done.                                           34.2s
remote notifications are not supported in the simulator
[VERBOSE-2:dart_isolate.cc(143)] Could not prepare isolate.
[VERBOSE-2:runtime_controller.cc(386)] Could not create root isolate.
[VERBOSE-2:shell.cc(610)] Could not launch engine with configuration.`

am getting the issue here with flutter 3.3 stable:
`import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../../../constants/const.dart';

class BaseBottomSheet extends StatelessWidget {
  final List<Widget> children;
  final double bottomSheetsHeight;
  const BaseBottomSheet(
      {Key? key,
      required this.children,
      this.bottomSheetsHeight = bottomSheetHeight})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.white,
      elevation: 5,
      child: SizedBox(
        height: bottomSheetsHeight.h,
        width: bottomSheetWidth(context),
        child: SingleChildScrollView(
          child: Column(
            children: children,
          ),
        ),
      ),
    );
  }
}`
it keeps crashing when the BaseBottomSheet is active if i comment out the hight and width, once in the page if i add static values to the width and hight it works with hot reload. When restarting it , it crashes again.

**Comment by AlexV525** [comment] 2022-08-31 14:00
> i keep getting this error on master

@Altamimi-Dev This doesn't seem to be the same issue, please file a new one to track, we'll keep this issue focused on the specific behavior. Thanks.

**Comment by dkwingsmt** [comment] 2022-08-31 18:18
I'm creating a cherrypick.

**Comment by Renzo-Olivares** [comment] 2022-08-31 20:00
@dkwingsmt I can confirm this is fixed on master. Tried on Pixel 6 Pro running Android 13.

**Comment by dkwingsmt** [comment] 2022-08-31 20:24
Thank you!

**Comment by zmtzawqlp** [comment] 2022-09-01 06:45
Flutter 3.1.0-0.0.pre.2608 • channel master • https://github.com/flutter/flutter.git
Framework • revision 759d0e1b20 (37 minutes ago) • 2022-08-31 23:07:20 -0700
Engine • revision b149eea0a3
Tools • Dart 2.19.0 (build 2.19.0-154.0.dev) • DevTools 2.16.0

still crash

**Comment by zmtzawqlp** [comment] 2022-09-01 06:47
```
E/AndroidRuntime( 8096): Process: com.example.abc, PID: 8096
E/AndroidRuntime( 8096): java.lang.AssertionError: The key was empty
E/AndroidRuntime( 8096): 	at io.flutter.embedding.android.KeyEmbedderResponder.updatePressingState(KeyEmbedderResponder.java:112)
E/AndroidRuntime( 8096): 	at io.flutter.embedding.android.KeyEmbedderResponder.synthesizeEvent(KeyEmbedderResponder.java:359)
E/AndroidRuntime( 8096): 	at io.flutter.embedding.android.KeyEmbedderResponder.lambda$synchronizePressingKey$0$io-flutter-embedding-android-KeyEmbedderResponder(KeyEmbedderResponder.java:163)
E/AndroidRuntime( 8096): 	at io.flutter.embedding.android.KeyEmbedderResponder$$ExternalSyntheticLambda1.run(Unknown Source:6)
E/AndroidRuntime( 8096): 	at io.flutter.embedding.android.KeyEmbedderResponder.handleEventImpl(KeyEmbedderResponder.java:345)
E/AndroidRuntime( 8096): 	at io.flutter.embedding.android.KeyEmbedderResponder.handleEvent(KeyEmbedderResponder.java:396)
E/AndroidRuntime( 8096): 	at io.flutter.embedding.android.KeyboardManager.handleEvent(KeyboardManager.java:224)
E/AndroidRuntime( 8096): 	at io.flutter.plugin.editing.InputConnectionAdaptor.sendKeyEvent(InputConnectionAdaptor.java:279)
E/AndroidRuntime( 8096): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:438)
E/AndroidRuntime( 8096): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
E/AndroidRuntime( 8096): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8096): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 8096): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 8096): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8096): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 8096): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 8096): Sending signal. PID: 8096 SIG: 9
Lost connection to device.
```


```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2608, on macOS 12.5.1 21G83 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.1.0-0.0.pre.2608 on channel master at /Users/zmtzawqlp/Documents/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 759d0e1b20 (40 minutes ago), 2022-08-31 23:07:20 -0700
    • Engine revision b149eea0a3
    • Dart version 2.19.0 (build 2.19.0-154.0.dev)
    • DevTools version 2.16.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zmtzawqlp/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = /Users/zmtzawqlp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 Pro Max (mobile)  • D4462A35-FCBB-4827-964B-F54895926C98 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by bleroux** [comment] 2022-09-01 09:07
> Can anyone confirm if this is a regression?

@justinmc : I can confirm it is a regression.
@dkwingsmt @AlexV525 : this is not fixed on master

On my Android phone, with the code sample from https://github.com/flutter/flutter/issues/110640#issue-1356636183 :
- NO crash using Flutter 3.0.5
- Crash using Flutter 3.3.0
- Crash using master channel

<details>
<summary>flutter doctor -v (master) </summary>

```

[✓] Flutter (Channel master, 3.1.0-0.0.pre.2607, on Ubuntu 22.04.1 LTS 5.15.0-46-generic, locale fr_FR.UTF-8)
    • Flutter version 3.1.0-0.0.pre.2607 on channel master at /home/bruno/Bruno/Nevercode/flutter
    • Upstream repository git@github.com:NevercodeHQ/flutter.git
    • FLUTTER_GIT_URL = git@github.com:NevercodeHQ/flutter.git
    • Framework revision 92ab7625e8 (il y a 5 heures), 2022-09-01 00:04:25 -0400
    • Engine revision b149eea0a3
    • Dart version 2.19.0 (build 2.19.0-154.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/bruno/Android/Sdk
    • Platform android-31, build-tools 33.0.0
    • Java binary at: /home/bruno/Produits/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/bruno/Produits/android-studio
    • Flutter plugin version 68.1.3
    • Dart plugin version 213.7371
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.70.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • SNE LX1 (mobile) • HYF0219508003668 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)  • linux            • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-46-generic
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details>
<summary>Console log</summary>

```
Launching lib/main.dart on SNE LX1 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:41043/TxTg8ET_56g=/ws
W/Gralloc3(27897): mapper 3.x is not supported
E/        (27897): APS:IFLoad:importExternalFunctions, search function createNewHwApsUtils failed, dlsym err:undefined symbol: createNewHwApsUtils
D/        (27897): APS:importExternalFunctions OK
I/HwViewRootImpl(27897): removeInvalidNode jank list is null
D/AwareBitmapCacher(27897): handleInit switch not opened pid=27897
W/Settings(27897): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(27897): User setup is finished.
I/HwViewRootImpl(27897): removeInvalidNode all the node in jank list is out of time
I/AssistStructure(27897): Flattened final assist data: 464 bytes, containing 1 windows, 3 views
D/AndroidRuntime(27897): Shutting down VM
I/QarthLog(27897): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(27897): [PatchStore] create disable file for com.example.flutter_110640 uid is 10132
E/AndroidRuntime(27897): FATAL EXCEPTION: main
E/AndroidRuntime(27897): Process: com.example.flutter_110640, PID: 27897
E/AndroidRuntime(27897): java.lang.AssertionError: The key was empty
E/AndroidRuntime(27897): 	at io.flutter.embedding.android.KeyEmbedderResponder.updatePressingState(KeyEmbedderResponder.java:112)
E/AndroidRuntime(27897): 	at io.flutter.embedding.android.KeyEmbedderResponder.synthesizeEvent(KeyEmbedderResponder.java:359)
E/AndroidRuntime(27897): 	at io.flutter.embedding.android.KeyEmbedderResponder.lambda$synchronizePressingKey$0$io-flutter-embedding-android-KeyEmbedderResponder(KeyEmbedderResponder.java:163)
E/AndroidRuntime(27897): 	at io.flutter.embedding.android.KeyEmbedderResponder$$ExternalSyntheticLambda1.run(Unknown Source:6)
E/AndroidRuntime(27897): 	at io.flutter.embedding.android.KeyEmbedderResponder.handleEventImpl(KeyEmbedderResponder.java:345)
E/AndroidRuntime(27897): 	at io.flutter.embedding.android.KeyEmbedderResponder.handleEvent(KeyEmbedderResponder.java:396)
E/AndroidRuntime(27897): 	at io.flutter.embedding.android.KeyboardManager.handleEvent(KeyboardManager.java:224)
E/AndroidRuntime(27897): 	at io.flutter.plugin.editing.InputConnectionAdaptor.sendKeyEvent(InputConnectionAdaptor.java:279)
E/AndroidRuntime(27897): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:432)
E/AndroidRuntime(27897): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
E/AndroidRuntime(27897): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(27897): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(27897): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(27897): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27897): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(27897): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/Process (27897): Sending signal. PID: 27897 SIG: 9
Lost connection to device.
Exited (sigterm)

```
</details>

**Comment by bleroux** [comment] 2022-09-01 13:39
I did a 'git bisect'. The crash started with this engine roll: https://github.com/flutter/flutter/pull/105070

@dkwingsmt 
It seems to be related to this engine commit: https://github.com/flutter/engine/pull/33686

**Comment by WONDERJEWEL** [comment] 2022-09-13 14:37
I Have the same problem
device : Rwdmi 10c + All system apps are up to date 

C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22000.856], locale en-IL)
    • Flutter version 3.3.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (7 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\merid\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\merid\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (5 available)
    • 220333QAG (mobile)      • fd8dff64      • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 105.0.1343.33

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Closed** 2022-09-14 07:12 UTC
Labels: a: text input, severe: regression, severe: crash, engine, waiting for PR to land (fixed), P1, severe: fatal crash

**Comment by AlexV525** [comment] 2022-09-14 07:42
Cherry-pick:
- #111537
