### ISSUE TITLE
[image_picker] Image Picker Requests Double Permissions When Only Allowing Selected Photos on iOS

### ISSUE THREAD

**Issue by knnkrt** [flutter/flutter#132651] opened 2023-08-16 12:05 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Using sample image_picker codes.
2. Run on iOS 16.x.x

### Expected results

Asking only one time when requesting picking image on iOS.

### Actual results

Image Picker Requests Double Permissions When Only Allowing Selected Photos on iOS

### Code sample

<details><summary>Code sample</summary>

```dart
Future<void> pickImage() async {
    try {
      final pickedImage = await _imagePicker.pickImage(source: ImageSource.gallery);

      imageFile = pickedImage != null ? File(pickedImage.path) : null;

      if (GetPlatform.isAndroid) {
        if (pickedImage == null) {
          final LostDataResponse response = await _imagePicker.retrieveLostData();
          if (response.isEmpty) {
            return;
          }
          if (response.file != null) {
            imageFile = File(response.file!.path);
          } else {
            kToast(message: "general_error".tr);
            return;
          }
        }
      }

      if (imageFile != null) {
        cropImage(); // go to crop image activity
      }
    } catch (e) {
      kDialog(
        children: [
          Text(
            "warning".tr,
            style: Theme.of(Get.context!).textTheme.titleLarge,
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 15),
          Text(
            "allow_permission_photos".tr,
            style: Theme.of(Get.context!).textTheme.bodyMedium,
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 15),
          PrimaryButton(
            text: "settings".tr,
            onPressed: () {
              Get.back();
              openAppSettings();
            },
          ),
          const SizedBox(height: 10),
          PrimaryButton(
            text: "cancel".tr,
            isFillIn: false,
            onPressed: () => Get.back(),
          ),
        ],
      );
    }
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Ekran Resmi 2023-08-16 15 01 55](https://github.com/flutter/flutter/assets/32898380/0c6371b4-accd-4828-b5b3-a45f2447dfe8)

https://github.com/flutter/flutter/assets/32898380/4c41d608-1582-46bd-81c1-46c8ad95e236

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale
    tr-TR)
    • Flutter version 3.10.6 on channel stable at /Users/kenan/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/kenan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • S19 Max Pro (mobile) • A13P41283D3021801671 • android-arm64  • Android 11
      (API 30)
    • macOS (desktop)      • macos                • darwin-arm64   • macOS 13.5
      22G74 darwin-arm64
    • Chrome (web)         • chrome               • web-javascript • Google
      Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-08-16 12:39
Hi @knnkrt. This seems similar to https://github.com/flutter/flutter/issues/90373. Kindly upvote, comment and follow up on that issue for updates. Closing this as a duplicate of the already open issue, if you disagree, kindly comment and I'd reopen this. Thank you!

**Closed by dam-ease** 2023-08-16 12:39 UTC
Labels: in triage
