### ISSUE TITLE
[tool_crash] OSError: OS Error: Can't assign requested address, errno = 49

### ISSUE THREAD

**Issue by Joy-Q** [flutter/flutter#111719] opened 2022-09-16 03:06 UTC
## Command
```
flutter --no-color attach --machine --device-id=00008110-001A7C5C01E2801E lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Can't assign requested address, errno = 49
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1558:35)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1480:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2373:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:138:16)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:66:7)
<asynchronous suspension>
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:51)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:278:11)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:214:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/zhangqi151/flutter
    • Framework revision f4abaa0735 (1 year, 2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/zhangqi151/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/zhangqi151/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.4.1, Build version 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 00008110-001A7C5C01E2801E • ios            • iOS 15.5
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 105.0.5195.125

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
path_provider-1.6.0
permission_handler-5.1.0+2

**Comment by danagbemava-nc** [comment] 2022-09-16 08:26
Closing this as a duplicate of https://github.com/flutter/flutter/issues/97489. 

Kindly follow up in the issue linked above for updates. 

Please upvote the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2022-09-16 08:26 UTC
Labels: in triage
