### ISSUE TITLE
Rendering issues in IOS ONLY, On Android working perfectly

### ISSUE THREAD

**Issue by BRZErez** [flutter/flutter#69177] opened 2020-10-28 08:52 UTC
I'm working on a big Flutter app that is in production for the past few year.
Since Flutter **1.16** we are having issues with rendering for **IOS**. On Android it is perfectly fine!
Some images are not being rendered on some phones, It is very sporadically and not something that can be debug (Not always same images and elements)
In **1.17** it seems that the issue was solved. But then when updated to **1.20 (Also on 1.22)** the issues returned.
As this happens only on IOS and not consistent, it is so hard to debug and so annoying.
From what we managed to research the conclusion is that it happens mostly the the app is sent to the background for a long period of time (few hours) and only on certain devices.
I wonder if anyone encountered this issue and if there is a solution for it.

The way I will go from here is:

- Trying using SVG instead of PNG

- Trying to find a way to call setNeedsLayout() or something like that in flutter 

- Trying to find a ways to look at viewWillAppear and viewDidAppear for the flutter VC

Just throwing things over here as again in Android everything is working perfectly.

**Comment by darshankawar** [comment] 2020-10-28 10:16
@BRZErez 
Reading your issue description and the pattern, ie on iOS, app is sent to background for long time and then accessing it and this is not happening on Android, I tend to think this is similar to another [open](https://github.com/flutter/flutter/issues/64558) issue which talks about same thing. I'd suggest you to follow-up there for updates and any questions you might have since it has active discussion going on.
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-10-28 10:16 UTC

**Comment by BRZErez** [comment] 2020-10-28 10:19
This is a bit deferent as for us it is not only images... At list in Flutter 1.17 it was also text... 
We got text not rendered fully and things like that... 
It was rendering in general..
In 1.20 and 1.22 we see the images not rendering but I can't say it is only images not rendering...
So I do not know it is the same issue, But decently related 
10x

**Comment by darshankawar** [comment] 2020-10-28 12:05
@BRZErez 
Is it possible for you to provide a minimal complete reproducible code sample that can possibly help to replicate the issue in non-prod environment ?
