### ISSUE TITLE
Crash with nested StreamBuilders in CustomScrollView

### ISSUE THREAD

**Issue by tfinlay** [flutter/flutter#50137] opened 2020-02-04 21:02 UTC
## Steps to Reproduce

1. Run `flutter create bug_example`.
2. Update main.dart with the code below.
3. Run application.

<details>
    <summary>Code</summary>

```dart
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final StreamController<int> rootStreamController = StreamController();
  final StreamController<int> secondaryStreamController = StreamController();

  Stream<int> populateStream() async* {
    int nextValue = 1;
    while (true) {
      await Future.delayed(Duration(seconds: 1));
      yield nextValue;
      nextValue++;
      nextValue = nextValue % 3;
    }
  }

  @override
  void initState() {
    super.initState();

    rootStreamController.addStream(populateStream());
    secondaryStreamController.addStream(populateStream());
  }

  @override
  void dispose() {
    rootStreamController.close();
    secondaryStreamController.close();

    super.dispose();
  }

  Widget _buildSliver(BuildContext context) {
    return StreamBuilder<int>(
      initialData: 0,
      stream: rootStreamController.stream,
      builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
        if (snapshot.data == null || snapshot.data == 0) {
          return SliverToBoxAdapter(
            child: Container(
              child: Text("State 0")
            )
          );
        }
        else if (snapshot.data == 1) {
          return SliverToBoxAdapter(
              child: Container(
                  child: Text("State 1")
              )
          );
        }
        else {  // State 2
          return StreamBuilder<int>(
            initialData: 0,
            stream: secondaryStreamController.stream,
            builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
              return SliverList(
                delegate: SliverChildBuilderDelegate(
                  (BuildContext context, int index) {
                    return Container(
                      child: Text("child $index")
                    );
                  },
                  childCount: snapshot.data
                ),
              );
            },
          );
        }
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: <Widget>[_buildSliver(context)],
    );
  }
}
```
</details>

**Expected result:** Expected that once state 2 is reached, a list of 0, 1, or 2 numbers is shown.

**Actual results:** Shows 'State 0', 'State 1', then crashes (presumably when building State 2)

<details>
  <summary>Logs</summary>

```
[ +229 ms] <- compile package:bug_example/main.dart
[+2348 ms] I/flutter ( 9901): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[   +1 ms] I/flutter ( 9901): The following assertion was thrown during a scheduler callback:
[        ] I/flutter ( 9901): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1491 pos 12: 'center.parent ==
[   +1 ms] I/flutter ( 9901): this': is not true.
[        ] I/flutter ( 9901): 
[        ] I/flutter ( 9901): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 9901): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 9901): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 9901):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter ( 9901): 
[        ] I/flutter ( 9901): When the exception was thrown, this was the stack:
[        ] I/flutter ( 9901): #2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1491:12)
[   +1 ms] I/flutter ( 9901): #3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:794:17)
[        ] I/flutter ( 9901): #4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2946:20)
[        ] I/flutter ( 9901): #5      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1168:43)
[        ] I/flutter ( 9901): #6      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1294:39)
[        ] I/flutter ( 9901): #7      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:652:11)
[   +1 ms] I/flutter ( 9901): #8      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:741:14)
[   +1 ms] I/flutter ( 9901): #9      RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1270:18)
[   +4 ms] I/flutter ( 9901): #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1587:7)
[        ] I/flutter ( 9901): #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
[        ] I/flutter ( 9901): #12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
[        ] I/flutter ( 9901): #13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
[   +1 ms] I/flutter ( 9901): #14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
[   +1 ms] I/flutter ( 9901): #15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
[   +1 ms] I/flutter ( 9901): #16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
[        ] I/flutter ( 9901): #17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
[   +1 ms] I/flutter ( 9901): #21     _invoke (dart:ui/hooks.dart:259:10)
[        ] I/flutter ( 9901): #22     _drawFrame (dart:ui/hooks.dart:217:3)
[        ] I/flutter ( 9901): (elided 5 frames from class _AssertionError and package dart:async)
[        ] I/flutter ( 9901): ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +9 ms] I/flutter ( 9901): Another exception was thrown: Updated layout information required for RenderViewport#07888 NEEDS-LAYOUT to calculate semantics.
[ +813 ms] I/flutter ( 9901): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1247 pos 12: '_debugCanPerformMutations': is not true.
[  +18 ms] I/flutter ( 9901): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
[ +133 ms] I/flutter ( 9901): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2430 pos 16: '!_dirtyElements[index]._active ||
_dirtyElements[index]._debugIsInScope(context)': is not true.
[ +824 ms] I/flutter ( 9901): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3227 pos 12: 'child._parent == this': is not true.
[   +4 ms] I/flutter ( 9901): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
[+1186 ms] I/flutter ( 9901): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2430 pos 16: '!_dirtyElements[index]._active ||
_dirtyElements[index]._debugIsInScope(context)': is not true.
[ +767 ms] Updating files
[  +64 ms] I/flutter ( 9901): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3227 pos 12: 'child._parent == this': is not true.
[   +6 ms] I/flutter ( 9901): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
[ +103 ms] DevFS: Sync finished
[   +2 ms] Syncing files to device Pixel 3a XL... (completed in 6,560ms, longer than expected)
[   +1 ms] Synced 0.9MB.
[   +2 ms] Sending to VM service: _flutter.listViews({})
[   +6 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x73e26f7620, isolate: {type: @Isolate, fixedId: true, id: isolates/945811341266935, name: main.dart$main-945811341266935, number:
945811341266935}}]}
[   +1 ms] <- accept
[   +1 ms] Connected to _flutterView/0x73e26f7620.
[   +2 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on Pixel 3a XL is available at: http://127.0.0.1:52504/MeqvtkagceQ=/
[   +1 ms] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[ +880 ms] I/flutter ( 9901): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3227 pos 12: 'child._parent == this': is not true.
[   +5 ms] I/flutter ( 9901): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
[+1160 ms] I/flutter ( 9901): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2430 pos 16: '!_dirtyElements[index]._active ||
_dirtyElements[index]._debugIsInScope(context)': is not true.
[ +833 ms] I/flutter ( 9901): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3227 pos 12: 'child._parent == this': is not true.
[   +4 ms] I/flutter ( 9901): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
[ +868 ms] Application finished.
```

```
Analyzing bug_example...
No issues found! (ran in 8.5s)
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.592], locale en-NZ)
    • Flutter version 1.12.13+hotfix.7 at C:\sdk\flutter
    • Framework revision 9f5ff2306b (9 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Users\username\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\username\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\username\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.6015.39
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\username\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.0

[√] Connected device (1 available)
    • Pixel 3a XL • 92HAX012JY • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

**Comment by helinanever** [comment] 2020-02-05 10:27
Hi @tfinlay 
It seems like it can be solved by using SliverToBoxAdapter [#25861 Comment](https://github.com/flutter/flutter/issues/25861#issuecomment-580705104)  [#30253 Comment](https://github.com/flutter/flutter/issues/30253#issuecomment-478311459)

I'm closing the current one as duplicate of [#30253](https://github.com/flutter/flutter/issues/30253#issuecomment-478311459).
Thank you

**Closed by helinanever** 2020-02-05 10:27 UTC
