### ISSUE TITLE
Network image error in flutter 1.26.0-17.6.pre

### ISSUE THREAD

**Issue by savadodesigns** [flutter/flutter#76388] opened 2021-02-19 16:49 UTC
## Steps to Reproduce

```
$ flutter channel beta
$ flutter upgrade
$ flutter pub upgrade
$ flutter run
```

## Error
(I changed the img src address)

```
The following ImageCodecException was thrown resolving an image codec:
Failed to decode image data.
Image source:
https://something/something.svg

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
lib/_engine/engine/canvaskit/image.dart 102:7                                     createDefault
lib/_engine/engine/canvaskit/skia_object_cache.dart 141:41                        new
lib/_engine/engine/canvaskit/image.dart 92:3                                      decodeFromBytes
lib/_engine/engine/canvaskit/image.dart 75:53                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37283:58                              <fn>
dart-sdk/lib/async/zone.dart 1370:13                                              _rootRunUnary
dart-sdk/lib/async/zone.dart 1265:19                                              runUnary
dart-sdk/lib/async/zone.dart 1170:7                                               runUnaryGuarded
dart-sdk/lib/async/zone.dart 1207:26                                              <fn>

Image provider:
  NetworkImage("https://something/something.svg",
  scale: 1)
Image key:
  NetworkImage("https://something/something.svg",
  scale: 1)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Logs

```
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Mac OS X 10.14.6 18G103 darwin-x64, locale nl-NL)
    • Flutter version 1.26.0-17.6.pre at /Users/samvandoorn/Projecten/flutter
    • Framework revision a29104a69b (3 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/samvandoorn/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ! Xcode 11.1.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2021-02-19 22:08
@savadodesigns 
does it work with non-svg images?
https://github.com/flutter/flutter/issues/1831

**Comment by savadodesigns** [comment] 2021-02-20 09:20
Same error with non-SVG images (png for example). Also; the SVG worked before.

**Comment by iapicca** [comment] 2021-02-20 09:36
@savadodesigns 
I can reproduce the issue on `web` with the latest master
<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';

const _url = 'https://flutter.dev/assets/flutter-lockup-'
    '1caf6476beed76adec3c477586da54de6b552b2f42108ec5bc68dc63bae2df75.png';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
              child: Image(
            image: NetworkImage(_url),
          )),
        ),
      ),
    );

```

</details>
<details>
<summary>web logs</summary>

```bash
[ +237 ms] Launching lib/main.dart on Chrome in debug mode...
[ +103 ms] Updating assets
[  +74 ms] Waiting for connection from debug service on Chrome...
[   +6 ms] Found plugin flutter_plugin_android_lifecycle at /home/francesco/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.11/
[   +3 ms] Found plugin image_picker at /home/francesco/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+22/
[  +23 ms] Found plugin flutter_plugin_android_lifecycle at /home/francesco/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.11/
[   +5 ms] Found plugin image_picker at /home/francesco/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+22/
[  +63 ms] <- reset
[   +7 ms] /home/francesco/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.GQQPSF/flutter_tool.WBPREY/app.dill
--libraries-spec file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/francesco/projects/issue/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.GQQPSF/flutter_tools.XJCUWJ --filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +18 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+19961 ms] Waiting for connection from debug service on Chrome... (completed in 20.1s)
[        ] Synced 29.3MB.
[        ] <- accept
[        ] Caching compiled dill
[ +291 ms] Using Chromium 88.0.4324.182 snap

[ +278 ms] [CHROME]:
[        ] [CHROME]:(chrome:162907): Gtk-WARNING **: 11:31:24.623: Theme parsing error: gtk.css:1555:23: 'font-feature-settings' is not a valid property name
[   +3 ms] [CHROME]:
[        ] [CHROME]:(chrome:162907): Gtk-WARNING **: 11:31:24.628: Theme parsing error: gtk.css:3591:25: 'font-feature-settings' is not a valid property name
[   +1 ms] [CHROME]:
[        ] [CHROME]:(chrome:162907): Gtk-WARNING **: 11:31:24.629: Theme parsing error: gtk.css:4053:23: 'font-feature-settings' is not a valid property name
[ +128 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:38025/devtools/browser/49db6367-32a8-47fa-bc33-d4335a5ade81
[+1901 ms] DwdsInjector: Received request for entrypoint at http://localhost:33247/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[  +17 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[  +11 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:33247/main_module.bootstrap.js
[+2547 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: false
[ +570 ms] DevHandler: Debug service listening on ws://127.0.0.1:40011/hxGhIk0p0qA=/ws

[  +11 ms] Debug service listening on ws://127.0.0.1:40011/hxGhIk0p0qA=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +3 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+8707 ms] ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[   +2 ms] The following ImageCodecException was thrown resolving an image codec:
[        ] Failed to load network image.
[        ] Image URL:
[        ] https://flutter.dev/assets/flutter-lockup-1caf6476beed76adec3c477586da54de6b552b2f42108ec5bc68dc63bae2df75.png
[        ] Trying to load an image from another domain? Find answers at:
[        ] https://flutter.dev/docs/development/platform-integration/web-images
[   +1 ms] When the exception was thrown, this was the stack:
[        ] ...
[        ] Image provider:
[        ]   NetworkImage("https://flutter.dev/assets/flutter-lockup-1caf6476beed76adec3c477586da54de6b552b2f42108ec5bc68dc63bae2df75.png",
[        ]   scale: 1)
[        ] Image key:
[        ]   NetworkImage("https://flutter.dev/assets/flutter-lockup-1caf6476beed76adec3c477586da54de6b552b2f42108ec5bc68dc63bae2df75.png",
[        ]   scale: 1)
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════
[+11001 ms] DevHandler: Stopped debug service on ws://127.0.0.1:44679

[  +64 ms] Application finished.
[   +5 ms] "flutter run" took 46,532ms.
[ +257 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```

</details>
<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.27.0-5.0.pre.89, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-5.0.pre.89 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 1b871036f9 (82 minutes ago), 2021-02-20 01:56:02 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.182 snap

! Doctor found issues in 1 category.

```

</details>
<details>
<summary>web screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/108590988-09eca580-736f-11eb-8730-183aca1b974b.png)

</details>

no issues on android

<details>
<summary>android screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/108591131-ca728900-736f-11eb-8bd1-9a97c786621e.png)

</details>

**Comment by franarolas** [comment] 2021-02-20 13:46
> Same error with non-SVG images (png for example). Also; the SVG worked before.

SVGs are no longer supported without using [Flutter_SVG](https://pub.dev/packages/flutter_svg) package, also it is only supported in iOS, Android and Web with canvas renderer.

**Comment by savadodesigns** [comment] 2021-02-20 14:47
Same error for PNG images. Will that be fixed?

**Comment by savadodesigns** [comment] 2021-02-20 15:10
> SVGs are no longer supported without using [Flutter_SVG](https://pub.dev/packages/flutter_svg) package, also it is only supported in iOS, Android and Web with canvas renderer.

Why?

**Comment by iapicca** [comment] 2021-02-20 15:35
@savadodesigns 
testing [NetworkImage](https://api.flutter.dev/flutter/painting/NetworkImage-class.html) on the latest `master`
everything seems to work as intended

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

const _url = 'https://flutter.dev/assets/flutter-lockup-'
    '1caf6476beed76adec3c477586da54de6b552b2f42108ec5bc68dc63bae2df75.png';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
              child: Image(
            image: NetworkImage(_url),
          )),
        ),
      ),
    );

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.27.0-5.0.pre.89, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-5.0.pre.89 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 1b871036f9 (9 hours ago), 2021-02-20 01:56:02 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.182 snap

! Doctor found issues in 1 category.

```

</details>

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/108600700-4afdad80-73a1-11eb-8632-ea7e18297281.png)

</details>

if this code sample is not representative of the issue you are describing 
please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

> > SVGs are no longer supported without using [Flutter_SVG](https://pub.dev/packages/flutter_svg) package, also it is only supported in iOS, Android and Web with canvas renderer.
> 
> Why?

I believe the best places to ask questions are [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [stackoverflow](https://stackoverflow.com/questions/tagged/flutter), not flutter's main repo

**Comment by franarolas** [comment] 2021-02-20 16:39
> @franarolas
> 
> > SVGs are no longer supported without using [Flutter_SVG](https://pub.dev/packages/flutter_svg) package, also it is only supported in iOS, Android and Web with canvas renderer.
> 
> Why?

@savadodesigns  Flutter team is not planning to support SVG format for the moment, whatever they are planning to implement an alternative to it, it is discused in this post #1831 .

**Comment by savadodesigns** [comment] 2021-02-20 16:45
> > @franarolas
> > > SVGs are no longer supported without using [Flutter_SVG](https://pub.dev/packages/flutter_svg) package, also it is only supported in iOS, Android and Web with canvas renderer.
> > 
> > 
> > Why?
> 
> @savadodesigns Flutter team is not planning to support SVG format for the moment, whatever they are planning to implement an alternative to it, it is discused in this post #1831 .

I just don’t get why they removed the support that was in the previous version.

**Comment by savadodesigns** [comment] 2021-02-20 16:50
> @savadodesigns
> testing [NetworkImage](https://api.flutter.dev/flutter/painting/NetworkImage-class.html) on the latest `master`
> everything seems to work as intended
> 
> code sample
> doctor
> screenshot
> if this code sample is not representative of the issue you are describing
> please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> 
> > > SVGs are no longer supported without using [Flutter_SVG](https://pub.dev/packages/flutter_svg) package, also it is only supported in iOS, Android and Web with canvas renderer.
> > 
> > 
> > Why?
> 
> I believe the best places to ask questions are [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [stackoverflow](https://stackoverflow.com/questions/tagged/flutter), not flutter's main repo

Im sorry, but my issue is about `beta` channel and `web` environment. (Not `master` and `android`.)

**Comment by iapicca** [comment] 2021-02-20 17:19
@savadodesigns 
I didn't see `web` being mentioned in the steps you provided

> ```
> $ flutter channel beta
> $ flutter upgrade
> $ flutter pub upgrade
> $ flutter run
> ```

I fail to see the point of testing `beta` 
since if the issue is fixed in `master` will eventually land on a future  beta

testing on web
with the same doctor of my previous [answer](https://github.com/flutter/flutter/issues/76388#issuecomment-782699756)
and a the same code sample, but different `image url` because [CORS](https://flutter.dev/docs/development/platform-integration/web-images#cross-origin-resource-sharing-cors)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

const _url = 'https://miro.medium.com/max/1000/1*ilC2Aqp5sZd1wi0CopD1Hw.png';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
              child: Image(
            image: NetworkImage(_url),
          )),
        ),
      ),
    );

```


</details>

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/108603369-383ea500-73b0-11eb-840b-809f726a5dc6.png)

</details>

everything seems to work as intended
feel free to test the code in `beta` if you find it meaningful

**Comment by savadodesigns** [comment] 2021-02-20 18:19
> I fail to see the point of testing `beta` since if the issue is fixed in `master` will eventually land on a future beta

I read that `web` is not supported in `master`, can you confirm/dismiss?

I guess I will wait for the new beta. Thanks.

**Comment by franarolas** [comment] 2021-02-20 18:22
> > I fail to see the point of testing `beta` since if the issue is fixed in `master` will eventually land on a future beta
> 
> I read that `web` is not supported in `master`, can you confirm/dismiss?
> 
> I guess I will wait for the new beta. Thanks.

Web is supported in all channels but stable and png images from network work in the last beta, as I'm using them in some projects, you may be having a cors issue as @iapicca said.

**Comment by darshankawar** [comment] 2021-02-22 07:01
@savadodesigns 


> I guess I will wait for the new beta. Solved my problem for now by downgrading.

Based on your comment, I guess this issue can be closed. If you think your issue is related to CORS, then see [this](https://github.com/flutter/flutter/issues/74123#issuecomment-765000345) comment related to it.

If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-02-22 07:01 UTC
Labels: in triage
