### ISSUE TITLE
Google Maps place geotiff on map

### ISSUE THREAD

**Issue by joaquinperaza** [flutter/flutter#26019] opened 2019-01-03 18:07 UTC
I have native apps loading geotiff and other geotagged images to overlay the map, is that possible in flutter?

**Comment by joaquinperaza** [comment] 2021-03-20 13:12
https://github.com/flutter/plugins/pull/3420

**Comment by stuartmorgan** [comment] 2023-03-05 23:24
Closing as a duplicate of https://github.com/flutter/flutter/issues/26479

**Closed by stuartmorgan** 2023-03-05 23:24 UTC
Labels: new feature, plugin, p: maps, proposal, passed first triage, P4
