### ISSUE TITLE
Can move text in input field out beyond input field inside ScrollableView

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6010] opened 2016-09-22 22:20 UTC
Open Gallery, open Expansion Panels, open Trip Name, tap into Trip name text field.

Then, put finger at right side of text, and then move your finger to the left.

Notice how you can push the text off the left, beyond the boundaries of the text input field.

![screenshot_20160922-151357](https://cloud.githubusercontent.com/assets/5479/18768156/1fb9185a-80d8-11e6-9b6b-8ba814548692.png)

**Comment by sethladd** [comment] 2016-09-22 22:21
cc @mpcomplete @dragostis

**Comment by dragostis** [comment] 2016-09-22 22:23
I'm seeing similar behavior in the text input demo, only it's worse here.

**Comment by sethladd** [comment] 2016-09-22 22:24
Thanks for checking.

**Comment by dragostis** [comment] 2016-09-22 22:25
Update: Didn't check. Thought this was the old issue and someone had deleted my comment. 😆

**Comment by dragostis** [comment] 2016-09-22 22:28
Checked now. It's only happening in this particular demo.

**Comment by mpcomplete** [comment] 2016-09-26 20:55
I think this is a bug in expansion panels, or at least, layout of text inputs inside expansion panels. The Input's layout is not being performed until you edit the text (try typing before scrolling - it scrolls correctly). This means its Scrollable's scrollBehavior doesn't get its proper bounds. In particular, _handlePaintOffsetUpdateNeeded is not being called.

**Comment by dragostis** [comment] 2016-09-26 21:15
@mpcomplete The problem seems to be the fact that the input is inside a `ScrollableViewport`. I can reproduce it with this:

```
new ScrollableViewport(
        child: new Container(
          margin: const EdgeInsets.all(24.0),
          child: new Form(
            child: new Input(
              hintText: 'item.hint',
              labelText: 'item.name',
              value: new InputValue(text: 'item.value'),
              formField: new FormField<String>(
                setter: (String val) { }
              ),
            ),
          ),
        )
      )
```

**Comment by mpcomplete** [comment] 2016-09-26 22:35
One strange discovery: this only repros when the test case @dragostis provided above is run from within the Gallery app (replace the _ExpansionPanelsDemoState builder with the above code). Running it standalone (e.g. with a runApp(new ExpasionPanelsDemo()) call) does not repro the bug.

**Comment by mpcomplete** [comment] 2016-10-18 20:46
This is the same as https://github.com/flutter/flutter/issues/6329 . Fixed by https://github.com/flutter/flutter/pull/6328 .

**Closed by mpcomplete** 2016-10-18 20:46 UTC
Labels: affects: framework, affects: text input, customer: gallery, ⚠ bug
