### ISSUE TITLE
something wrong with TextStyle.TextDecoration params

### ISSUE THREAD

**Issue by dishcheng** [flutter/flutter#25607] opened 2018-12-20 07:33 UTC
I want a single underline but it shows double underline
![image](https://user-images.githubusercontent.com/26062252/50270418-76f11180-046c-11e9-8927-a22ebdc8f145.png)
![image](https://user-images.githubusercontent.com/26062252/50270435-83756a00-046c-11e9-8d7f-fbccac1a7f8b.png)

It shows on my HuaWei7x ,but My  friends doesn't show this

**Comment by dishcheng** [comment] 2018-12-20 07:49
if the text content without (") at the content head ,It shows single underline ,like this "长城环球通自由行信用卡美加澳线下消费返现",it is ok。Another，if the text is "环球精彩 一卡尽享境外消费满额最惠"，it shows double underline ,but if is "环球精彩一卡尽享境外消费满额最惠"(without Blank bewteen 彩 and 一),it show single

**Comment by zoechi** [comment] 2018-12-20 09:17
Please add the output of `flutter doctor -v`.

**Comment by dishcheng** [comment] 2018-12-20 09:20
![image](https://user-images.githubusercontent.com/26062252/50275911-888de580-047b-11e9-92d2-954d57e548ef.png)

**Comment by bonoogi** [comment] 2019-02-13 05:43
same issue happen to me. and not only `TextDecoration.underline`. also happened to `TextDecoration.overline`

### Screenshots
![simulator screen shot - iphone xs max - 2019-02-13 at 14 37 54](https://user-images.githubusercontent.com/6913297/52689291-07476080-2f9d-11e9-8c5f-a16d94b16507.png)
![simulator screen shot - iphone xs max - 2019-02-13 at 14 38 06](https://user-images.githubusercontent.com/6913297/52689293-07476080-2f9d-11e9-82a2-f6ab1e07c87e.png)

### Code
```
const roman = "ABCD";
  const korean = "가나다라";
  const chinese = "诶比西迪";
  const japanese = "あいうえ";
  const space = " ";
  final style = TextStyle(
    color: Colors.black,
    fontSize: 30.0,
    decoration: TextDecoration.underline, // or overline
  );
MaterialApp(
      home: Scaffold(
        body: ListView(
          children: <Widget>[
            Text("Only Korean",),
            Text(
              korean,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With whitespace",),
            Text(
              korean + space,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With Roman",),
            Text(
              roman + korean,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With Japanese",),
            Text(
              korean + japanese,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With Chinese",),
            Text(
              korean + chinese,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With All",),
            Text(
              roman + korean + chinese + japanese,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("Common TextStyle",),
            RichText(
              text: TextSpan(
                style: style,
                children: [
                  TextSpan(text: roman,),
                  TextSpan(text: korean,),
                  TextSpan(text: chinese,),
                  TextSpan(text: japanese,),
                ]
              )
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("Each TextStyle",),
            RichText(
              text: TextSpan(
                children: [
                  TextSpan(text: roman, style: style,),
                  TextSpan(text: korean, style: style,),
                  TextSpan(text: chinese, style: style,),
                  TextSpan(text: japanese, style: style,),
                ]
              )
            ),
          ],
        ),
      ),
    )
```

### flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by jason-simmons** [comment] 2019-03-29 20:02
Duplicate of https://github.com/flutter/flutter/issues/30041

**Closed by jason-simmons** 2019-03-29 20:02 UTC
Labels: a: typography, engine

**Comment by bonoogi** [comment] 2019-03-30 06:23
thank you @jason-simmons ! 
I have just test it. There's only one line exactly. But something is wrong to line's y position.
plz check screenshot below.

### Screenshot on LGM V30
![Screenshot_2019-03-30-14-55-23](https://user-images.githubusercontent.com/6913297/55272378-12611080-52ff-11e9-92c2-e756e9fb8e49.png)

### Screenshot on iOS(iPhone XS Max) Simulator
![Simulator Screen Shot - iPhone XS Max - 2019-03-30 at 14 52 11](https://user-images.githubusercontent.com/6913297/55272390-489e9000-52ff-11e9-9917-259ac0dcaa8c.png)

### code
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Main(),
    );
  }
}

const roman = "ABCD";
const korean = "가나다라";
const chinese = "诶比西迪";
const japanese = "あいうえ";
const space = " ";
final style = TextStyle(
  color: Colors.black,
  fontSize: 30.0,
  decoration: TextDecoration.underline, // or overline
);

class Main extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ListView(
          children: <Widget>[
            Text("Only Korean",),
            Text(
              korean,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With whitespace",),
            Text(
              korean + space,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With Roman",),
            Text(
              roman + korean,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With Japanese",),
            Text(
              korean + japanese,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With Chinese",),
            Text(
              korean + chinese,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("With All",),
            Text(
              roman + korean + chinese + japanese,
              style: style,
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("Common TextStyle",),
            RichText(
              text: TextSpan(
                style: style,
                children: [
                  TextSpan(text: roman,),
                  TextSpan(text: korean,),
                  TextSpan(text: chinese,),
                  TextSpan(text: japanese,),
                ]
              )
            ),
            Padding(padding: EdgeInsets.only(top: 24,)),
            Text("Each TextStyle",),
            RichText(
              text: TextSpan(
                children: [
                  TextSpan(text: roman, style: style,),
                  TextSpan(text: korean, style: style,),
                  TextSpan(text: chinese, style: style,),
                  TextSpan(text: japanese, style: style,),
                ]
              )
            ),
          ],
        ),
      );
  }
}
```

### flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.4.8-pre.18, on Mac OS X 10.14.4 18E226, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)
```
