### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by sikandernoori** [flutter/flutter#126591] opened 2023-05-11 20:11 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:129:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:428:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:427:12)
#5      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:916:19)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1518:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64,
    locale en-CA)
    [32m•[39m Flutter version 3.10.0 on channel stable at /Users/skandar/flutter
    [33m![39m Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside
      your current Flutter SDK checkout at /Users/skandar/flutter. Consider
      adding /Users/skandar/flutter/bin to the front of your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    [32m•[39m Engine revision d44b5a94c9
    [32m•[39m Dart version 3.0.0
    [32m•[39m DevTools version 2.23.1
    [32m•[39m If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    [32m•[39m Android SDK at /Users/skandar/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 32.1.0-rc1
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14C18
    [32m•[39m CocoaPods version 1.12.0

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.78.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.64.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone 14 Pro Max (mobile) • 63D662E7-3A3F-4088-B889-7E042BD8871F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    [32m•[39m macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    [32m•[39m Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 113.0.5672.92

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment] 2023-05-12 08:13
Closing as duplicate of https://github.com/flutter/flutter/issues/65242

**Closed by darshankawar** 2023-05-12 08:13 UTC
Labels: in triage
