### ISSUE TITLE
Package name  bug

### ISSUE THREAD

**Issue by charliezzo** [flutter/flutter#44560] opened 2019-11-11 08:56 UTC
## Steps to Reproduce

1. If my domain is abc.xyz.fun,
2. when i create a flutter project with android studio
3. MainActivity.kt will have a package name like package fun.xyz.abc
4. This cant build and run

## Logs

```
![image](https://user-images.githubusercontent.com/9925064/68573960-d18bc580-04a3-11ea-92a4-0c0b4be29ed1.png)


Package name must be a '.'-separated identifier list
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
Compilation error. See log for more details
```

```
![image](https://user-images.githubusercontent.com/9925064/68574110-23345000-04a4-11ea-9bac-f7860dc55318.png)

```

**Comment by charliezzo** [comment] 2019-11-11 08:57
youtrack.jetbrains.com tells me that is not bug of kotlin.
![image](https://user-images.githubusercontent.com/9925064/68574222-5e368380-04a4-11ea-8f78-5f7fb1bc021a.png)

**Comment by iapicca** [comment] 2019-11-11 11:44
Hi @charliezzo 
could you please provide your `flutter doctor -v` 
and your `flutter build --verbose` ?
Thank you

**Comment by charliezzo** [comment] 2019-11-12 08:04
**flutter doctor -v**
![image](https://user-images.githubusercontent.com/9925064/68653012-b3869980-0565-11ea-86b2-422fff259ef3.png)
**flutter build --verbose**
![image](https://user-images.githubusercontent.com/9925064/68653092-e6309200-0565-11ea-831e-6050812e65e8.png)

**Comment by charliezzo** [comment] 2019-11-12 08:06
@iapicca thank you , i upload my flutter doctor -v and flutter build --verbose yet

**Comment by iapicca** [comment] 2019-11-12 10:38
Hi @charliezzo 
thank you for the information you provided,
please refrain from posting pictures if not necessary.

**Comment by charliezzo** [comment] 2019-11-13 06:20
@iapicca sorry,I am not very skilled at using markdown,so i post pictures for you,
In order to communicate with you better, I am learning markdown,thank you.

**Comment by jonahwilliams** [comment] 2020-01-09 06:59
Duplicate of https://github.com/flutter/flutter/issues/16521

**Closed by jonahwilliams** 2020-01-09 06:59 UTC
Labels: severe: crash, tool
