### ISSUE TITLE
[camera] Camera Plugin not working on Android R API 30! android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error

### ISSUE THREAD

**Issue by mugikhan** [flutter/flutter#61544] opened 2020-07-15 14:21 UTC
## Steps to Reproduce

Taking picture on Android R API 30 emulator. Fails to take a picture with an error message.

**Expected results:** Take and save the picture. This works completely fine on all devices prior to Android R API 30. 

**Actual results:** The error below.

<details>
  <summary>Logs</summary>

```
W/.autopal.maide(15086): JNI critical lock held for 35.529ms on Thread[16,tid=15107,Runnable,Thread*=0xda4d3410,peer=0x13602650,"Binder:15086_3"]
E/CameraCaptureSession(15086): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(15086): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession(15086): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2163)
E/CameraCaptureSession(15086): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1253)
E/CameraCaptureSession(15086): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:578)
E/CameraCaptureSession(15086): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:480)
E/CameraCaptureSession(15086): 	at io.flutter.plugins.camera.Camera.close(Camera.java:486)
E/CameraCaptureSession(15086): 	at io.flutter.plugins.camera.Camera$2.onError(Camera.java:187)
E/CameraCaptureSession(15086): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1582)
E/CameraCaptureSession(15086): 	at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
E/CameraCaptureSession(15086): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)
E/CameraCaptureSession(15086): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
E/CameraCaptureSession(15086): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
E/CameraCaptureSession(15086): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession(15086): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(15086): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(15086): 	at android.os.Looper.loop(Looper.java:223)
E/CameraCaptureSession(15086): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/CameraCaptureSession(15086): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(15086): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/CameraCaptureSession(15086): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

```
Analyzing -app...
No issues found! (ran in 2.5s)
```

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-ZA)
    • Flutter version 1.17.5 at /Users/mugheeskhan/fvm/versions/stable
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mugheeskhan/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[!] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-15 16:20
Reproduced with current master `1.20.0-8.0.pre.102` as well (on emulator) with https://pub.dev/packages/camera/example
`camera 0.5.8+2`

**Comment by shadiossaili** [comment] 2020-09-02 21:08
any update about this issue ?

**Comment by alexcohn** [comment] 2020-09-07 14:30
For me, this works. My emulator has VirtualScene for the camera. How is your emulator configured?

**Comment by titusjoyson** [comment] 2020-09-12 14:14
I am facing the same issue, I have tried with VirtualScene  and webcam as well

**Comment by titusjoyson** [comment] 2020-09-12 14:21
I down graded to 29 and its working for me now

**Comment by kakaiba-talaga** [comment] 2020-09-14 05:06
Same here. As of now, the only solution is to downgrade to API 29.

**Comment by valconetti** [comment] 2020-09-17 09:28
It looks like it's a problem with having [(a) .NOMEDIA file(s) on your device](https://nerdschalk.com/gallery-not-showing-images-android-fix/). 

> In very rare cases, .nomedia file is generated by error inside every media directory on the device, restricting Gallery apps from indexing the media files inside those folders.

It seems to me like [phones running on Android 11](https://support.google.com/pixelphone/thread/70290821?hl=en) have generated this file, but this is just speculation on my part.

You can either delete these files by searching for them under DCIM and DCIM > Camera or you can do a factory reset. The latter worked for me. More solutions you can try are [here](https://android.stackexchange.com/questions/55967/pictures-and-videos-not-showing-in-the-gallery).

**Comment by amirh** [comment] 2020-09-30 17:39
We are not able to reproduce this issue.
@mugikhan / @valconetti - If you are able to reproduce this issue, please capture an Android bug report right after the crash by running `adb bugreport` and share with us. *Note that `adb bugreport` file includes the full logcat output, so make sure to review and remove any private information before sharing.*

**Comment by okarpov** [comment] 2020-10-08 10:07
W/Gralloc4( 5726): allocator 3.x is not supported
E/BufferQueueProducer( 5726): SurfaceTexture-0-5726-0 dequeueBuffer: attempting to exceed the max dequeued buffer count (3)
E/CameraCaptureSession( 5726): Session 0: Exception while stopping repeating:
E/CameraCaptureSession( 5726): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:459: Camera 0: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession( 5726): at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1009)
E/CameraCaptureSession( 5726): at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession( 5726): at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1251)
E/CameraCaptureSession( 5726): at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:578)
E/CameraCaptureSession( 5726): at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:789)
E/CameraCaptureSession( 5726): at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:245)
E/CameraCaptureSession( 5726): at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession( 5726): at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession( 5726): at android.os.Looper.loop(Looper.java:223)
E/CameraCaptureSession( 5726): at android.app.ActivityThread.main(ActivityThread.java:7656)
E/CameraCaptureSession( 5726): at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession( 5726): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/CameraCaptureSession( 5726): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/CameraCaptureSession( 5726): Caused by: android.os.ServiceSpecificException: cancelRequest:459: Camera 0: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession( 5726): at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
E/CameraCaptureSession( 5726): at android.os.Parcel.createException(Parcel.java:2357)
E/CameraCaptureSession( 5726): at android.os.Parcel.readException(Parcel.java:2340)
E/CameraCaptureSession( 5726): at android.os.Parcel.readException(Parcel.java:2282)
E/CameraCaptureSession( 5726): at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:732)
E/CameraCaptureSession( 5726): at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession( 5726): ... 11 more

**Comment by okarpov** [comment] 2020-10-08 10:09
so the issue mainly with the virtual scene camera for API 30 emulator
(also have one client with real device and the same issue)

**Comment by alexcohn** [comment] 2020-10-08 13:21
> the issue mainly with the virtual scene camera for API 30 emulator

This is not a flutter-specific problem, see https://stackoverflow.com/q/63351097/192373

**Comment by okarpov** [comment] 2020-10-08 13:28
> > the issue mainly with the virtual scene camera for API 30 emulator
> 
> This is not a flutter-specific problem, see https://stackoverflow.com/q/63351097/192373

they are talking about a CameraX plugin or something

but I'm talking about the https://pub.dev/packages/camera

**Comment by alexcohn** [comment] 2020-10-08 17:30
The point is, with CameraX library they hit the same root cause. CameraX, after all, is yet another wrapper around the camera2 platform API, and fultter camera is a wrapper around camera2 platform API. When there is a problem with a platform API on the Android 11 emulator, it hits everybody. 

It's important to understand that the error here is not a bug in the flutter plugin, but *below*. It may be possible to find a workaround, but hopefully the root cause will be fixed before Android 12 goes into production.

**Comment by gkoulomz** [comment] 2020-10-24 02:30
Does anyone know if/when Flutter camera plugin will support full manual exposure (ISO, f-stop, shutter speed, white-balance)??
As near as I can tell (being new to Flutter) it only supports fully automatic mode.
In general, camera2 is a very rich and powerful mechanism.  Hiding all that means Flutter can do only trivial camera apps.

**Comment by VladimirCourse** [comment] 2020-10-24 15:33
Having the same problem, version 0.5.8+9, device Xiaomi Mi A2 Lite, occurs when using `startImageStream`. Resolution of camera has no influence. Also, there are some strange artifacts in camera preview (blue vertical lines moving from left ro right and freezes every 1-2 seconds till crash). No problems found in older device Asus ze500cl

**Comment by alexcohn** [comment] 2020-10-25 17:22
@VladimirCourse are you sure you are running Android R (API 30) on that Xiaomi Mi A2 Lite?

**Comment by AnhPC03** [comment] 2020-12-31 03:05
Any solution for this issue please?

**Comment by PingShen** [comment] 2021-01-04 07:45
how to fix this?

**Comment by mvanbeusekom** [comment] 2021-01-13 16:31
@AnhPC03, @PingShen, is this still an issue? 

It indeed seems it is related to a bug in the emulator software, particular when using the VirtualScene mode. This would not really be something we can fix on the Flutter side.

Personally I cannot reproduce the error and am wondering if the error still occurs on a fully updated system (with the latest emulator software and updated image of Android 11)?

**Comment by SaloxiddinTursunaliev** [comment] 2021-02-03 13:23
Hi @mugikhan , @Trinity95 , @shadiossaili , @TahaTesser , @mvanbeusekom 
Sorry for disturbing!

Have you found a solution for this issue?
I am having this issue too, on Android 10 x86.
I have done almost everything to solve this, but...

Step 1:  when I run the app , it is running successfully.
step 2:  then I select one of the two cameras below.
step 3: When I take a photo it is giving these errors:

<details>
<summary>crash photo logs</summary>

```bash
W/Gralloc3( 3736): allocator 3.x is not supported
D/        ( 3736): HostConnection::get() New Host Connection established 0xe3d3e000, tid 3753
D/        ( 3736): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
D/        ( 3736): HostConnection::get() New Host Connection established 0xebf925b0, tid 3754
D/        ( 3736): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
D/        ( 3736): HostConnection::get() New Host Connection established 0xebed9670, tid 3755
D/        ( 3736): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
D/        ( 3736): HostConnection::get() New Host Connection established 0xebed96c0, tid 3785
D/        ( 3736): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
E/CameraCaptureSession( 3736): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession( 3736): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 3736):  at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2521)
E/CameraCaptureSession( 3736):  at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1128)
E/CameraCaptureSession( 3736):  at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)
E/CameraCaptureSession( 3736):  at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1147)
E/CameraCaptureSession( 3736):  at io.flutter.plugins.camera.Camera.close(Camera.java:1153)
E/CameraCaptureSession( 3736):  at io.flutter.plugins.camera.Camera$1.onError(Camera.java:247)
E/CameraCaptureSession( 3736):  at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.notifyError(CameraDeviceImpl.java:2010)
E/CameraCaptureSession( 3736):  at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.lambda$Sm85frAzwGZVMAK-NE_gwckYXVQ(Unknown Source:0)
E/CameraCaptureSession( 3736):  at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$CameraDeviceCallbacks$Sm85frAzwGZVMAK-NE_gwckYXVQ.accept(Unknown Source:8)
E/CameraCaptureSession( 3736):  at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:271)
E/CameraCaptureSession( 3736):  at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
E/CameraCaptureSession( 3736):  at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
E/CameraCaptureSession( 3736):  at android.os.Handler.handleCallback(Handler.java:883)
E/CameraCaptureSession( 3736):  at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraCaptureSession( 3736):  at android.os.Looper.loop(Looper.java:214)
E/CameraCaptureSession( 3736):  at android.app.ActivityThread.main(ActivityThread.java:7356)
E/CameraCaptureSession( 3736):  at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession( 3736):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/CameraCaptureSession( 3736):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter ( 3736): Error: captureTimeout
I/flutter ( 3736): Error Message: Picture capture request timed out
```
</details>

step 4: After this error I cant record a video, it is giving these errors:

<details>
<summary>crash video logs</summary>

```bash
E/MethodChannel#plugins.flutter.io/camera( 3736): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera( 3736): java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference
E/MethodChannel#plugins.flutter.io/camera( 3736):       at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:286)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at io.flutter.plugins.camera.Camera.startVideoRecording(Camera.java:624)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:115)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/camera( 3736):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter ( 3736): Error: error
I/flutter ( 3736): Error Message: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference
```
</details>

step 5: But if I record a video first after reinstalling the app, then the app records a video properly.
step 6: Then if I take a photo after recording a video it is giving the errors above again.

Thanks

**Closed** 2021-02-03 16:45 UTC
Labels: e: OS Version specific, found in release: 1.20, has reproducible steps, p: camera, platform-android, plugin, severe: crash, waiting for customer response

**Comment by alexcohn** [comment] 2021-02-04 14:14
@SaloxiddinTursunaliev, if you see this problem on emulator, it's not worth much. The problem is with the camera subsystem of the emulator, definitely not with the flutter camera plugin.

The question is whether it shows up on physical devices.

**Comment by hoaiha-zencode** [comment] 2021-07-30 04:46
Hi everyone, I also have the above issue when take picture from camera plugin. Any solution for this issue please?
