### ISSUE TITLE
onAttachedToActivity method of ActivityAware not called

### ISSUE THREAD

**Issue by lukluca** [flutter/flutter#122887] opened 2023-03-17 13:44 UTC
Good morning, 
I am currently developing a flutter plugin on Android and iOS platforms. The main problem is that all the callbacks of ActivityAware are never called. 

## Steps to Reproduce

1. Execute `flutter run` on the code sample (see "Code sample" section below)
2. Wait until the app is loaded inside Android simulator `Pixel_3a_API_33_arm64-v8a`

**Expected results:** 

 See log `onAttachedToActivity` on console.

**Actual results:** 

 The expected log `onAttachedToActivity` is never printed to console.

<details>
<summary>Code sample</summary>
Here you can find my git repository with all the code

[project](https://github.com/lukluca/spectogram_flutter_plugin)

</details>

<details>
  <summary>Logs</summary>

`flutter run --verbose`

[log.txt](https://github.com/flutter/flutter/files/11001814/log.txt)

`flutter analyze `

```
Analyzing example...                                                    
No issues found! (ran in 1.5s)
```

 `flutter doctor -v`

[doctor.txt](https://github.com/flutter/flutter/files/11001871/doctor.txt)

</details>

**Comment by huycozy** [comment] 2023-03-20 05:20
Thanks for filing the issue, @lukluca. I can reproduce this issue on the latest `stable` and `master` channels.

Minimal sample code (only contains ActivityAware's methods): https://github.com/huycozy/reproduce-plugin-template

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.7.7 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (10 hours ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.9.0-11.0.pre.6, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.9.0-11.0.pre.6 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0dd46a33e7 (6 hours ago), 2023-03-19 18:21:21 -0400
    • Engine revision dc6e389aea
    • Dart version 3.0.0 (build 3.0.0-339.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by stuartmorgan** [comment] 2023-03-21 19:50
@huycozy Does it reproduce with a Java plugin? We use `onAttachedToActivity` in many of the 1P plugins, and they are not all broken, so there must be something about these examples that is different from the existing, working plugins.

**Comment by huycozy** [comment] 2023-03-22 04:10
Yes. It actually works (on both Kotlin and Android). Thank @stuartmorgan for the hint.

@lukluca You should check the log from **Logcat**, for eg:

```
2023-03-22 10:59:58.471  3642-3642  ReproduceP...latePlugin com...oduce_plugin_template_example  V  onAttachedToActivity
```

I will close this issue because it is working as intended. If you disagree, please write in the comments and I will reopen it. Thanks!

**Closed by huycozy** 2023-03-22 04:10 UTC
Labels: platform-android, engine, has reproducible steps, P4, found in release: 3.7, a: plugins, found in release: 3.9

**Comment by lukluca** [comment] 2023-03-29 17:29
Hi @huycozy,

I found some defects on my git project, and I fixed them. I saw that the logs are displayed only if I run the example app as a standalone android project, but if I run the app as a flutter project, the logs are not displayed. So the onAttachedToActivity is called, but on console I am not able to see the logs. 

Thanks!
