### ISSUE TITLE
ios: Command line debug build fails (ld: symbol(s) not found for architecture armv7) while Xcode and VS Code builds are ok

### ISSUE THREAD

**Issue by johanlantz** [flutter/flutter#43710] opened 2019-10-29 09:35 UTC
## Steps to Reproduce
I have an flutter plugin using cocoapods which I am trying to build using:
```
flutter build ios --debug
```

But it keeps failing.  Do note that flutter run is ok and so is starting the app from VS Code and Xcode. It is only the command line build in debug mode that fails. It is possible I am using it wrong but I do have another project with the exact same setup and in that case the command line debug build works fine. 

The main difference is that this project linking with a prebuilt static library (c++ .a file) so perhaps that is what is causing the problem. However I am not able to understand why it works when launching using any of the options [flutter run, VS code, Xcode].

I understand this is a crappy problem description but if you spot anything that is worth investigating I am happy to do the work if there is a hint on what to look at.

The output from
flutter build ios --debug --verbose is here:
https://docs.google.com/document/d/1bzEpU_MODxZHh2t6cXiNJPbYiqQ-P7LVvxyZ5qm-XKQ/edit?usp=sharing

This looks like some sort of mixup with the architectures. The prebuilt static library does have all architectures. This is the lipo output:
```
Architectures in the fat file: libessentia.a are: armv7 arm64 x86_64
```

The rest of the code is defined in the .podfiles.

**Target Platform: iOS 
**Target OS version/browser: 13.1
**Devices:** iPhone 6S

## Logs (the flutter run is working fine)

https://pastebin.com/5y04A6m5

flutter analyze output
```
Analyzing audio_sentiment_flutter...                                    
No issues found! (ran in 2.2s)
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A603, locale en-GB)
    • Flutter version 1.9.1+hotfix.4 at /Users/yc00025/flutter
    • Framework revision cc949a8e8b (4 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yc00025/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/yc00025/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • QA-1 • b7f15a80e3e4e34c66c0455e2b3c316b3928d8e3 • ios • iOS 13.1
```

**Comment by BondarenkoStas** [comment] 2019-10-29 15:12
I don't know the cause and how to fix that, but seems the issue is hidden here (from error log)
```
/Users/yc00025/projects/wingman-audio-sentiment/testapps/audio_sentiment_flutter/build/ios/Debug-iphoneos/Pods_Runner.framework/Pods_Runner,
               building for iOS-armv7 but attempting to link with file built for iOS-arm64
               Undefined symbols for architecture armv7:
                 "_OBJC_CLASS_$_WingmanAudioSentimentPlugin", referenced from:
                     objc-class-ref in GeneratedPluginRegistrant.o
               ld: symbol(s) not found for architecture armv7
               clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jmagman** [comment] 2019-10-29 22:23
Thank you for including so much info!

Does `flutter run --debug` reproduce?  The command you pasted didn't include `--debug` so it defaulted to Release build configuration.

**Comment by jmagman** [comment] 2019-10-29 22:36
I wonder why ONLY_ACTIVE_ARCH=NO, I think it defaults to YES for Debug.
```
CONFIGURATION = Debug
...
ONLY_ACTIVE_ARCH = NO
```

**Comment by johanlantz** [comment] 2019-10-30 10:15
Hi @jmagman and @BondarenkoStas  and thanks for the fast replies.

So, all combinations of flutter run does work but both options for flutter build ios (with and without --debug) fails with different errors

I have uploaded my test project here:
https://drive.google.com/file/d/1c_XHcTHePln3i15F-m5g1xmeGJJV1i2D/view?usp=sharing

I hopefully allow you to reproduce the issue, most likely I am doing something wrong on my end.

Do note that my project setup is non-trivial. This is a flutter plugin, currently with code for iOS only. The common source files are in the src folder but this must be usable from a native app as well as a flutter or for instance ionic app. Due to this you also have a plugin folder where the flutter to swift bindings is located.

In the testapps folder you have a native iOS test app and a flutter test app. In order to reproduce the problem, you should hopefully only have to go to /testapps/audio-sentiment-flutter and do "flutter build ios.

Do also notice that the cocoapod structure is a bit complex since cocoapods does not allow to reference filesusing ../../. Due to this you will see that pubspec.yaml references the plugin folder which in turn needs the Framework declared in the .podspec in the root (that is referenced in the Podfile or testapps/flutter-audio-sentiment/ios/Podfile). It was the best solution I could come up with.

In my environment, doing flutter run works as does launching from Xcode or VS code. I can also do a build only from Xcode but only when building for the device since the precompiled libessentia.a does not work with the simulator (which also is strange since the fat lib includes the x86_64 architecture).

As I mentioned before, I have another plugin project setup the exact same way that builds fine using flutter build ios. The main difference is that the other project does not make use of any precompiled c++ library. I am not sure that is the issue but it could be a factor.

**Comment by jmagman** [comment] 2019-10-30 17:59
I don't really want to download that zip on my machine, but I'm guessing this is because ONLY_ACTIVE_ARCH = NO for Debug (did you change this?  It defaults to YES in the default Xcode and Flutter project template) and when you run on the simulator it maps armv7 to the i386 simulator.  You're targeting a x86_64 simulator, but ONLY_ACTIVE_ARCH = NO means it will try to build for both a (non-existent) 32- and 64-bit simulator.

Your static library (and Flutter.framework) doesn't include i386.  You can:
1. Change ONLY_ACTIVE_ARCH = YES for Debug.  [You still won't be able to build against a simulator in Release.](https://github.com/flutter/flutter/issues/11754)
2. Set your build setting `VALID_ARCHS[sdk=iphonesimulator*] = x86_64` so it doesn't even try to build i386 when the simulator is targeted.  I didn't test this exact case, but it might work?

I'm going to close this since I think this is an issue between your non-default Xcode project settings and your own static library.  If you think there is a Flutter bug to track down here, let me know and I'll reopen.  Thanks again for including so much detail in your report!

**Closed by jmagman** 2019-10-30 17:59 UTC
Labels: a: build, severe: crash, tool, ⌺‬ platform-ios
