### ISSUE TITLE
flutter web: assertion on mouse click

### ISSUE THREAD

**Issue by azol** [flutter/flutter#47440] opened 2019-12-19 09:58 UTC
flutter web assertion on doing nothing (clicking left/right mouse button on empty web page area) :) 

## Steps to Reproduce

Flutter (Channel dev, v1.13.2, on Mac OS X 10.15.1 19B88, locale en-GB)
1. `flutter create click`
2. `cd click`
3. `flutter run -d chrome`
4. open inspector (console) in chrome
5. right click on page (context menu appears)
6. left click somewhere do dismiss the menu  (menu disappears)
7. another right click and... crash

## Error
```
crash: errors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:271:18
!state.down
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:271)
    at _engine.PointerAdapter.new.[_convertEventToPointerData] (pointer_binding.dart:366)
    at pointer_binding.dart:317
    at HTMLElement.<anonymous> (pointer_binding.dart:183)
DartError @ errors.dart:147
throw_ @ errors.dart:196
assertFailed @ errors.dart:26
convert @ pointer_converter.dart:271
[_convertEventToPointerData] @ pointer_binding.dart:366
(anonymous) @ pointer_binding.dart:317
(anonymous) @ pointer_binding.dart:183
errors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:436:18
!_locationHasChanged(device, physicalX, physicalY)
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:436)
    at _engine.PointerAdapter.new.[_convertEventToPointerData] (pointer_binding.dart:366)
    at pointer_binding.dart:303
    at HTMLElement.<anonymous> (pointer_binding.dart:183)
DartError @ errors.dart:147
throw_ @ errors.dart:196
assertFailed @ errors.dart:26
convert @ pointer_converter.dart:436
[_convertEventToPointerData] @ pointer_binding.dart:366
(anonymous) @ pointer_binding.dart:303
(anonymous) @ pointer_binding.dart:183
errors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:271:18
!state.down
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:271)
    at _engine.PointerAdapter.new.[_convertEventToPointerData] (pointer_binding.dart:366)
    at pointer_binding.dart:317
    at HTMLElement.<anonymous> (pointer_binding.dart:183) 
```

## Logs

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.13.2, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.13.2 at /Users/az/opt/flutter
    • Framework revision 4944622b5d (7 days ago), 2019-12-12 18:43:58 +0000
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/az/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/az/Applications/Android Studio 4.0 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Users/az/Applications/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio
    • Android Studio at /Users/az/Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Users/az/Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7761

[✓] VS Code (version 1.41.0)
    • VS Code at /Users/az/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by ferhatb** [comment] 2019-12-19 17:21
https://github.com/flutter/engine/pull/14378 was committed to fix pointer binding issues. Please retry on master. /cc @dkwingsmt

**Comment by azol** [comment] 2019-12-19 17:28
still issue on  Flutter (Channel master, v1.13.3-pre.83, on Mac OS X 10.15.2 19C57, locale en-US) :(

**Comment by bernaferrari** [comment] 2019-12-26 01:11
Same here. I'm on v1.13.5

**Comment by sh0umik** [comment] 2019-12-26 01:27
I am on dev `Flutter (Channel dev, v1.13.5, on Mac OS X 10.14.6 18G103, locale en-BD)` and got the same problem while testing mouse drag and drop event.

**Comment by dkwingsmt** [comment] 2019-12-26 19:01
I found out that, when I switched to v1.13.2, then I run `flutter run -d chrome`, the engine code is outdated (i.e. before my PR). Do you know why? @ferhatb

**Comment by ferhatb** [comment] 2019-12-26 21:22
@dkwingsmt , if engine changes landed in flutter it should be the latests. You are using run with --local-engine when working on changes right?

**Comment by dkwingsmt** [comment] 2019-12-26 22:17
@ferhatb I was using `local-engine` during development (which had the updated code). Then I switched to framework v1.13.2 (released on Dec 12), ran without `local-engine`, and found that the code was outdated.

**Comment by dkwingsmt** [comment] 2019-12-27 08:47
I just realized this fix is only rolled into framework since 1.13.4. But someone reported it on 1.13.5. Will investigate tomorrow.

**Comment by bernaferrari** [comment] 2019-12-28 16:08
When I got it it was more like a random bug than something completely reproducible. I was playing with it, then.. bang! This error.

**Comment by mdebbar** [comment] 2020-01-02 18:02
While investigating this, I discovered multiple situations where a right click causes an error.

I'll send a fix shortly with the necessary tests to prevent regressions.

**Closed** 2020-01-03 17:21 UTC
Labels: severe: crash, ☸ platform-web
