### ISSUE TITLE
Build Archiving iOS for "Any iOS Device (arm64, armv7)" throws error for barcode_scan plugin

### ISSUE THREAD

**Issue by somdipdey** [flutter/flutter#74953] opened 2021-01-29 02:48 UTC
- Why this is happening for different target build on iOS Xcode?
- How to fix it so that I can build it for iOS for "Any iOS Device (arm64, armv7)" such that the built package could be uploaded to iTunes Connect (App Store Connect)? 

## Steps to Reproduce

1. Open Runner.xcodeproj in Xcode v 12.4 (12D4e)
2. Make sure Bundle Identifier is the correct App ID in Apple Developer Portal
3. Product->Archive Menu Option

The flutter app for Android works perfectly. On the iOS side when I try to build and run on my iPhone 11 then it runs without any issue. However, when I try to use the "Archive" option Product menu in Xcode where the target device is "Any iOS Device (arm64, armv7)" then I am getting the following error for barcode_scan plugin:

`Module "barcode_scan" not found`

Screenshot of Xcode running the app on my iPhone without issue --->
<img width="940" alt="Screen Shot 2021-01-29 at 2 35 28 AM" src="https://user-images.githubusercontent.com/8515608/106224764-d25d6400-61db-11eb-95fc-a783c11dcb6f.png">

Screenshot of Xcode running the app on "Any iOS Device (arm64, armv7)" where it throws the error for  "barcode_scan "--->
<img width="1006" alt="Screen Shot 2021-01-29 at 2 36 46 AM" src="https://user-images.githubusercontent.com/8515608/106224870-f7ea6d80-61db-11eb-894b-8659e1f2afed.png">

```
[✓] Flutter (Channel unknown, v1.16.3, on Mac OS X 10.15.6 19G2021, locale
    en-US)
    • Flutter version 1.16.3 at /Users/somdipdey/Downloads/flutter
    • Framework revision be3a4b37b3 (10 months ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc2)
    • Android SDK at /Users/somdipdey/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-30, build-tools 30.0.0-rc2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/somdipdey/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM N960F • 2aabc8a0393f7ece • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```
</details>

**Comment by TahaTesser** [comment] 2021-01-29 10:33
Hi @somdipdey 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/mintware-de/flutter_barcode_reader).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-29 10:33 UTC
