### ISSUE TITLE
can't create new project

### ISSUE THREAD

**Issue by amjadsh97** [flutter/flutter#44291] opened 2019-11-06 19:37 UTC
please any one help me
[flutter_03.log](https://github.com/flutter/flutter/files/3816381/flutter_03.log)

**Comment by stuartmorgan** [comment] 2019-11-06 19:44
Duplicate of #43734; see there for instructions to fix your checkout.

If you have any insight to add about how you ended up with an install in this state, please comment there, as the mechanism by which people are getting their Flutter trees into this state is still unclear.

**Closed by stuartmorgan** 2019-11-06 19:44 UTC
