### ISSUE TITLE
Embedding doesn't run on Windows 7 and crashes with an unclear missing DLL message.

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#40855] opened 2019-09-19 14:45 UTC
flutter.bat run
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Then:
Nothing more.
But,when i click the program what is compiled by flutter-desktop-embedding,the error occured:
"无法启动此程序，因为计算机中丢失api-ms-win-shcore-scaling-l1-1-1.dll。尝试重新安装该程序以解决此问题。"

**Comment by escamoteur** [comment] 2019-09-19 14:46
We don't support Windows 7 at this moment.

**Comment by stuartmorgan** [comment] 2019-09-19 15:27
We have other open bugs for potentially supporting platforms that we don't currently support, as a place to gather information about the level of interest (i.e., upvotes) as well as any special considerations.

Given that Windows 7 still has a large install base, I think it's worth having a tracking bug for that even though we don't currently have any specific plans to support it.

Also, while we aren't committing to supporting it, if someone is interested in making the embedding work on Windows 7 I'm happy to consider patches; we'd need to weigh any tradeoffs on a patch-by-patch basis.

**Comment by escamoteur** [comment] 2019-09-19 15:45
@stuartmorgan good idea, I was yesterday told by one of the Flutter team to close it because there is no plan to support it.

**Comment by biij5698** [comment] 2019-09-20 00:07
@escamoteur In china,about sixty percent people use windows 7 system

**Comment by biij5698** [comment] 2019-09-20 01:01
@stuartmorgan In china,about sixty percent people use windows 7 system

**Comment by biij5698** [comment] 2019-09-20 01:03
@stuartmorgan @escamoteur I want to build windows 7 program just now

**Comment by stuartmorgan** [comment] 2019-09-20 02:28
Please don't spam the issue with comments; it will not affect the resolution of the bug. You've expressed your interest, so further comments are not necessary unless you have new substantive information to add.

**Comment by escamoteur** [comment] 2019-09-20 07:46
And @biij5698 as already said. If you need it that urgent, figure out why the current version doesn't work and fix it then we can add it to Flutter. Flutter is open source so you can help making things better.

**Comment by biij5698** [comment] 2019-09-20 22:58
@escamoteur  I believe this problem can be solved

**Comment by stuartmorgan** [comment] 2019-09-21 02:18
> figure out why the current version doesn't work

It doesn't work because it uses APIs that aren't available in Windows 7. The work here wouldn't be figuring out why it doesn't work, but implementing a solution that allows running on Windows 7 without regressing the Windows 10 behavior.

**Comment by escamoteur** [comment] 2019-09-21 06:48
I actually implied finding a solution after finding the problem 😜

**Comment by 23Yc8z** [comment] 2019-10-25 18:21
If flutter-desktop-embedding doesn't support Win7, there should be a warning in the documentation. I have lost a lot of time until I have found this thread. Thank you

**Comment by stuartmorgan** [comment] 2019-10-25 21:53
Desktop support in Flutter is still experimental; there are many things that don't work. Documenting all of the limitations at this stage is a non-goal, as that would be a substantial amount of duplicate effort and would very likely not stay reliably updated.

**Comment by alevinetx** [comment] 2020-01-15 01:26
Found this while trying to run under win7, too.  I understand the burden in capturing every "won't run in this situation" for a product that's not supported, still in early dev.  With that said, would adding 1 sentence to the README be that horrible? 

```Right now supports only win10, likely to never support win7```

From what I read above, the issue is that APIs specific to 10 are being used, and that to make this viable under 7 would require a lot of overhaul at the risk of breaking w10 functionality.  Ergo, trying to find a patch/PR to contribute is actually a futile quest.     Is that a correct assessment?  

If that's not a correct assessment, can someone point to a general area in which to begin looking at making this work under 7?

 Thank you!

**Comment by stuartmorgan** [comment] 2020-01-15 06:29
> With that said, would adding 1 sentence to the README be that horrible?
> 
> `Right now supports only win10, likely to never support win7`

I would prefer not to create a self-fulfilling prophesy. As I said above I'm open to patches if people are interested in supporting Windows 7, which are unlikely to ever be written by the community if the documentation implies there's no point.

> From what I read above, the issue is that APIs specific to 10 are being used

Windows 8.1 for the part that's crashing here, I believe, but pretty much.

> and that to make this viable under 7 would require a lot of overhaul at the risk of breaking w10 functionality. Ergo, trying to find a patch/PR to contribute is actually a futile quest. Is that a correct assessment?

I have no reason at this point to believe that there's a lot of overhaul needed to fix the current issue, or that there any need to break Windows 10 support if written correctly. It's possible that there are other incompatibilities currently hidden behind this one, but the only way to know is to try.

> If that's not a correct assessment, can someone point to a general area in which to begin looking at making this work under 7?

The starting point would be to replace the DPI code [here](https://github.com/google/flutter-desktop-embedding/blob/master/example/windows/win32_window.cc#L36) with something along the lines of [this class](https://github.com/flutter/engine/blob/master/shell/platform/windows/win32_dpi_helper.cc#L15) with the dynamic loading and lookup, and remove the direct linking to `Shcore.dll` in the runner. Assuming that's the only issue of that nature, that should reduce the Windows 7 problem to [this bug](https://github.com/google/flutter-desktop-embedding/issues/572), which involves adding some kind of fallback that works in older versions (in this case, Windows 7); ideally that would be a different DPI lookup, but worst case it could fall back to a hard-coded 96 rather than the current behavior of returning 0 on failure.

Potentially that more robust lookup code could be consolidated into the engine and exposed via the embedding API since I would expect that it would end up being the same code in both cases, but the first step would be just getting to something that works.

**Closed** 2020-02-13 00:35 UTC
Labels: a: desktop, ❖ platform-windows

**Comment by rubgithub** [comment] 2020-02-19 20:04
I was able to run on win7 x64 (just download from internet missing files)
flutter desktop v1.15.3

**Comment by franciscojma86** [comment] 2020-02-19 23:49
Yeah this was fixed by 
https://github.com/flutter/engine/pull/16313
https://github.com/google/flutter-desktop-embedding/pull/658

What's the bug on windows size?

**Comment by rubgithub** [comment] 2020-02-20 00:10
> Yeah this was fixed by
> [flutter/engine#16313](https://github.com/flutter/engine/pull/16313)
> [google/flutter-desktop-embedding#658](https://github.com/google/flutter-desktop-embedding/pull/658)
> 
> What's the bug on windows size?

The main window starts like this:
![image](https://user-images.githubusercontent.com/3399476/74887862-8f034000-5352-11ea-8bea-2e4dcb4dc21c.png)
 
You can 'fix' it by creating a shortcut and setting to execute maximized.

The only chage that I've made was in `window_configuration.cpp` .

```
const unsigned int kFlutterWindowOriginX = 0;
const unsigned int kFlutterWindowOriginY = 0;
const unsigned int kFlutterWindowWidth = 1200;
const unsigned int kFlutterWindowHeight = 768;
```

**Comment by franciscojma86** [comment] 2020-02-20 00:18
@rubgithub Can you please file a bug with the `flutter doctor -v` output and any relevant logs please? I wasn't able to reproduce this on my windows 10 machine, but will try once I get to my windows 7 one.

**Comment by rubgithub** [comment] 2020-02-20 13:37
> @rubgithub Can you please file a bug with the `flutter doctor -v` output and any relevant logs please? I wasn't able to reproduce this on my windows 10 machine, but will try once I get to my windows 7 one.

Here you are
#51119 

By the way, is there plans to support win7 x32?

**Comment by franciscojma86** [comment] 2020-02-20 17:28
Thanks for the bug report!

There aren't any plans currently to support win7 x32.

**Comment by franciscojma86** [comment] 2020-02-20 18:11
@rubgithub Here's the tracking bug for win7 x32 https://github.com/flutter/flutter/issues/37777
