### ISSUE TITLE
minCompileSdk is 32 not 19 or 20,version webview_flutter: ^3.0.4

### ISSUE THREAD

**Issue by zhangzheng567** [flutter/flutter#116339] opened 2022-12-01 13:22 UTC
The minCompileSdk (32) specified in a
[2022-12-01 20:56:18]     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[2022-12-01 20:56:18]     is greater than this module's compileSdkVersion (android-31).
[2022-12-01 20:56:18]     Dependency: androidx.webkit:webkit:1.5.0.
[2022-12-01 20:56:18]     AAR metadata file: /root/.gradle/caches/transforms-3/2ddf6621a12dce3906273733bc5a665a/transformed/webkit-1.5.0/META-INF/com/android/build/gradle/aar-metadata.properties.

**Comment by exaby73** [comment] 2022-12-01 13:33
Hello @zhangzheng567. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by exaby73** [comment] 2022-12-07 07:27
Changing the `compileSdkVersion` in your `android/app/build.gradle` to 32 should fix this issue. Since this is not an issue with Flutter, I am closing it. If you disagree, please comment with your reasoning and I can reopen the issue.

PS: Thanks @RaphAlemoh for the help here :)

**Closed by exaby73** 2022-12-07 07:27 UTC
Labels: waiting for customer response, in triage
