### ISSUE TITLE
Input decoration vertical alignment is broken with `isDense: true`

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#86093] opened 2021-07-08 10:58 UTC
## Bug

Using a very simple `TextField` setup, the visuals are broken on web, i.e. the text is too high vertically / **not center aligned**.

This means there is a very easily provable **discrepancy** between Flutter web and Flutter for mobile.

### Screenshots

| Mobile (correct) | Web (broken) |
| :----------------: | :--------------: |
| ![image](https://user-images.githubusercontent.com/19204050/124910438-1f3f3500-dfdb-11eb-8d04-b7541f07e158.png) | ![image](https://user-images.githubusercontent.com/19204050/124910392-12224600-dfdb-11eb-9296-b8810c6d465c.png) |
| ![image](https://user-images.githubusercontent.com/19204050/124910464-25351600-dfdb-11eb-9107-66ab2e3a607e.png) | ![image](https://user-images.githubusercontent.com/19204050/124910478-27977000-dfdb-11eb-8200-fc7502569209.png) |

### Reproducible sample

This is the exact code I ran on **web** and on **mobile**:

<details><summary>Click to expand snippet</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const Bug());
}

class Bug extends StatelessWidget {
  const Bug({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(32),
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.onSurface.withAlpha(0x1a),
                borderRadius: BorderRadius.circular(8),
              ),
              child: SizedBox(
                height: 44,
                child: TextField(
                  cursorColor: Theme.of(context).accentColor,
                  textAlign: TextAlign.left,
                  textAlignVertical: TextAlignVertical.center,
                  style: Theme.of(context).textTheme.bodyText2,
                  decoration: InputDecoration(
                    border: InputBorder.none,
                    hintText: 'Hint :)',
                    isDense: true,
                    hintStyle: Theme.of(context).textTheme.subtitle2,
                    prefixIcon: const Icon(Icons.search),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

#### Versions

```dart
[✓] Flutter (Channel origin/stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale en-150)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (7 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.124
```

**Comment by TahaTesser** [comment] 2021-07-08 13:21
Hi @creativecreatorormaybenot 
Thanks for filing the issue, looks like `isDense: true,` is the culprit here, the issue reproduces on the web and desktop 

```console
      decoration: InputDecoration(
                    border: InputBorder.none,
                    hintText: 'Hint :)',
                    // isDense: true, // Comment this and run the app on desktop or web
                    hintStyle: Theme.of(context).textTheme.subtitle2,
                    prefixIcon: const Icon(Icons.search),
                  ),
```

| mobile w/ or wo/ `isDense: true`  | web/desktop w/ `isDense: true` | web/desktop wo/ `isDense: true` |
| --------------- | --------------- |  --------------- |
<img src="https://user-images.githubusercontent.com/48603081/124927592-7b1fb300-e007-11eb-8088-86330eb68e75.PNG"  /> | <img src="https://user-images.githubusercontent.com/48603081/124927600-7c50e000-e007-11eb-9cc2-c963152212bb.PNG"  /> | <img src="https://user-images.githubusercontent.com/48603081/124927602-7d820d00-e007-11eb-9852-20a1c4cb93c5.PNG" /> |


|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (7 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.51]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.114, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.4.0-1.0.pre.114 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc1b91c4b3 (5 hours ago), 2021-07-08 04:11:04 -0400
    • Engine revision c989ae17b7
    • Dart version 2.14.0 (build 2.14.0-289.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86     • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64     • Microsoft Windows [Version 10.0.22000.51]
    • Windows (UWP) (desktop) • winuwp        • windows-uwp-x64 •
    • Chrome (web)            • chrome        • web-javascript  • Google Chrome 91.0.4472.124
    • Edge (web)              • edge          • web-javascript  • Microsoft Edge 91.0.864.64

• No issues found!
```
		
</details>

✅ : No Issue ❌: Issue reproduced

**Comment by creativecreatorormaybenot** [comment] 2021-07-08 13:39
@TahaTesser I tested around with the `InputDecoration` parameters and text field configuration for a few hours and iirc, I also did encounter the same behavior with `isDense: false` when changing some other configuration (maybe content padding?).

Anyway, I believe this is a general issue with the text field and the sample I posted only tries to give the simplest possible example of the error occurring, but it also occurs in many other cases.

**Comment by HansMuller** [comment] 2021-07-08 15:35
This may be a consequence of applying the default visualDensity on desktop/web.

**Comment by TahaTesser** [comment] 2022-07-26 14:14
Looked into this, and for some reason, alignment is affected by the style of the border.

<details> 
<summary>Code Sample</summary> 

```dart
import 'package:flutter/material.dart';

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key, this.dark = true, this.useMaterial3 = true});

  final bool dark;
  final bool useMaterial3;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: dark ? ThemeMode.dark : ThemeMode.light,
      theme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      darkTheme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatefulWidget {
  const Example({super.key});

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  bool outlineBorder = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample'),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: const <Widget>[
                  Text('isDense: false'),
                  SizedBox(width: 20),
                  Text('isDense: true'),
                ],
              ),
              SizedBox(
                height: 100.0,
                child: Row(
                  children: <Widget>[
                    Expanded(
                      child: DecoratedBox(
                        decoration: BoxDecoration(
                          color:
                              Theme.of(context).colorScheme.secondaryContainer,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: TextField(
                          decoration: InputDecoration(
                            hintText: 'Hint',
                            prefixIcon: const Icon(Icons.calendar_today),
                            border: outlineBorder
                                ? const OutlineInputBorder()
                                : const UnderlineInputBorder(),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 20),
                    Expanded(
                      child: DecoratedBox(
                        decoration: BoxDecoration(
                          color:
                              Theme.of(context).colorScheme.secondaryContainer,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: TextField(
                          decoration: InputDecoration(
                            hintText: 'Hint',
                            isDense: true,
                            prefixIcon: const Icon(Icons.calendar_today),
                            border: outlineBorder
                                ? const OutlineInputBorder()
                                : const UnderlineInputBorder(),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              ElevatedButton(
                onPressed: () {
                  setState(() {
                    outlineBorder = !outlineBorder;
                  });
                },
                child:
                    Text('${outlineBorder ? 'Underline' : 'Outline'} border'),
              )
            ],
          ),
        ),
      ),
    );
  }
}

``` 
	
</details>


https://user-images.githubusercontent.com/48603081/181027237-c6e08b44-1c32-461c-a053-40a6fae575a5.mov

**Comment by TahaTesser** [comment] 2022-08-01 08:46
I can also see the alignment issue on mobile, its less noticeable


https://user-images.githubusercontent.com/48603081/182110221-0384e38f-f4e7-49ee-bda8-e1fee570983b.mov

**Comment by adrianostas** [comment] 2023-02-20 12:03
Any updates on this issue?

**Comment by huycozy** [comment] 2023-03-28 04:58
As https://github.com/flutter/flutter/issues/123532 is filed recently which has similar behavior to this, I leave my comment for further investigation.

- It seems the issue is caused by `hintText` (I also see above sample code contains `hintText` as well)
- Issue reproduction on platforms has been changed on the latest Flutter version (using sample code at https://github.com/flutter/flutter/issues/123532#issue-1641791773)

| Android | iOS | Web | MacOS |
| --------------- | --------------- | --------------- | --------------- |
❌ | ❌ | ✅ | ✅ |

✅: No Issue ❌: Issue reproduced


| Android | iOS |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/228131617-15840378-c640-43c6-92f4-af3b6e344e4b.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/228132046-32960e47-637a-4a60-8fa1-50e8b3c2f1ad.png">

 | Web | MacOS |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/228131637-75606c00-06be-4cba-9dd3-2b86af3db362.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/228131631-46e57eed-bf0d-473e-9c55-b9523a46524c.png">

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (34 hours ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.9.0-17.0.pre.27, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.9.0-17.0.pre.27 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4a1002e2e2 (6 hours ago), 2023-03-26 22:55:12 +0200
    • Engine revision 685fbc6f4d
    • Dart version 3.0.0 (build 3.0.0-366.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by ToniHeiss** [comment] 2023-04-24 11:04
Idk if it helps anybody: We currently add 4 points of padding to the top and bottom in our Flutter project, if we are in the web. (kIsWeb) It seems to fix it, as the textfield seems to layout past the boundaries by about 8 pixels in the web.

**Comment by Johannes5000** [comment] 2024-06-18 14:03
Is there any news on this bug, or is there a workaround to fix this issue?

I encountered this bug in my web application as well when using a combination of UnderlineInputBorder and a suffix icon (or widget). This causes the UI to look strange when using suffix icons.

![image](https://github.com/flutter/flutter/assets/61516197/84909f34-3d71-4a7c-9963-063b18346bb4)
(I added a color to the TextField in order to show the edges)

**Comment by bleroux** [comment] 2024-06-25 15:04
The main issue reported here was the icon and the input text not being aligned vertically on web and desktop.

![image](https://github.com/flutter/flutter/assets/840911/932f9b74-d04c-4408-bf66-106e964777da)

Since Flutter 3.7 this is no more reproducible:

![image](https://github.com/flutter/flutter/assets/840911/f7aed9cc-568c-4229-8841-5d74714fcc29)


<details><summary>Updated code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const Bug());
}

class Bug extends StatelessWidget {
  const Bug({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(32),
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.onSurface.withAlpha(0x1a),
                borderRadius: BorderRadius.circular(8),
              ),
              child: SizedBox(
                height: 44,
                child: TextField(
                  textAlign: TextAlign.left,
                  textAlignVertical: TextAlignVertical.center,
                  style: Theme.of(context).textTheme.bodyMedium,
                  decoration: InputDecoration(
                    border: InputBorder.none,
                    hintText: 'Hint :)',
                    isDense: true,
                    hintStyle: Theme.of(context).textTheme.titleSmall,
                    prefixIcon: const Icon(Icons.search),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
``` 

</details> 

Because the main issue is no more reproducible I will close this issue.
The InputDecorator rendering logic is complex and there are many edge cases that we try to tackle.

To everyone having similar issues, many thanks for filing new issues with a specific code sample (for instance, @Johannes5000 can you file an issue with the code sample for https://github.com/flutter/flutter/issues/86093#issuecomment-2176188243 ?).

**Closed by bleroux** 2024-06-25 15:04 UTC
Labels: a: text input, framework, f: material design, a: quality, has reproducible steps, found in release: 3.7, found in release: 3.9, team-design, triaged-design
