### ISSUE TITLE
Random Library

### ISSUE THREAD

**Issue by Tejaswgupta** [flutter/flutter#63385] opened 2020-08-10 13:38 UTC
### Use case

In Random library from 'dart:math' , `Random().nextInt` , takes only a single integer argument which is used as the upper limit.
This is a very basic feature that could be used in a variety of projects and is already used by a lot of people there
Flutter could build on that to take two arguments namely the upper limit and the lower limit , which is already present in languages like Swift.

## Proposal

This could be achieved in a very basic project with the following:
`int nextInt(int mix , int max) => min+Random.nextInt(max-min)` 

Not sure if changing this one line would implement this feature , it would be much harder to implement than it seems.
Looking forward to a positive response

**Comment by YazeedAlKhalaf** [comment] 2020-08-10 13:40
I think this is related to Dart itself not Flutter.

**Comment by pedromassangocode** [comment] 2020-08-10 14:24
Hi @Tejaswgupta 
From what I can see, the issue is related to a Dart language rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-10 14:24 UTC
