### ISSUE TITLE
Assert in animated_list.dart when inserting and sort is defined

### ISSUE THREAD

**Issue by ken-salterdiazsolutions** [flutter/flutter#115681] opened 2022-11-19 01:54 UTC
I have a FirebaseAnimatedList that is displaying data.  I have sort: defined to do string compares:

```
sort: (a, b) {
  return (a.key!.compareTo(b.key!));
}

```
Then the list is first populated, there are no issues.  As soon as I insert a new record, either programmatically or via the Firebase console, I get the following assert:

```
Exception has occurred.
_AssertionError ('package:flutter/src/widgets/animated_list.dart': Failed assertion: line 528 pos 12: 'index != null && index >= 0': is not true.)

```
The value of index in this case is -1.

if I change the sort: so that it always returns 0, it still asserts.

If I remove the sort: in the FirebaseAnimatedList completely, then the assertion goes away.

Has anyone encountered this before?  I have searched the internets and haven't found anything.

**Comment by darshankawar** [comment] 2022-11-21 06:04
@ken-salterdiazsolutions 
This is a duplicate of https://github.com/firebase/flutterfire/issues/7100 which has been fixed recently. So follow-up in it and upgrade your plugin version that should most probably fix the issue.
Closing from here. If that doesn't fix it, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-11-21 06:04 UTC
Labels: in triage
