### ISSUE TITLE
iOS crashes when device is rotated for a TextInput, except when obscureText is true

### ISSUE THREAD

**Issue by ROTGP** [flutter/flutter#16792] opened 2018-04-20 10:26 UTC
When a TextInput is present, and the keyboard is open, iOS will crash when the device is rotated. However, if the keyboard is dismissed, no crash occurs. Interesting, if the TextInput's `obscureText` property is true (aka, password), then the crash does not occur, even if the keyboard is open. I've also experienced similar crashes with simple ListViews (when no TextInput exists), perhaps this [bug](https://github.com/flutter/flutter/issues/15438) is related. Disabled rotation fixes this issue, but obviously that's not a long term solution.

## Steps to Reproduce

Run the following code...

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'ios rotation crash demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new TextField(
          obscureText: false,
        )
      ),
    );
  }
}
```

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D47, locale en-ES)
    • Flutter version 0.2.8 at /Users/dev/Sites/codebase/flutter
    • Framework revision b397406561 (3 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode9.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (2 available)
    • iPhone X • 043EA455-EDDF-4A03-B630-CCF5FA244554 • ios           • iOS 11.3 (simulator)

• No issues found!
```

**Comment by mAu888** [comment] 2018-06-06 19:07
Currently walking through Udacitys Flutter course and I'm facing the same issue. Unfortunately for me it is not consistently crashing on the first rotation to occur, but can take a few rotations until crashing. As mentioned, it does not crash when the text field is not focused.

**Comment by zoechi** [comment] 2018-08-26 12:02
Are you still seeing that?

**Comment by ROTGP** [comment] 2018-08-27 08:17
@zoechi against which branch/release should I verify this? Beta v0.5.1? I must confess I'm a bit confused. The CLI is always warning me to upgrade but then I upgrade and it tells me I'm up to date.

**Comment by zoechi** [comment] 2018-08-27 09:08
Ideally with `master` channel
```
flutter channel master
flutter doctor
```

**Comment by zoechi** [comment] 2018-08-27 09:09
If it still reproduces, can you please provide some error output?

**Comment by ROTGP** [comment] 2018-08-27 10:59
@zoechi yes, this is still an issue. Tested against master v0.7.1-pre.30. I should note though, I don't currently have access to an iOS device, only the emulator. Perhaps someone else can verify on an actual device. 

There's no error output - it just says
 ```
Lost connection to device. Exited (sigterm).
```  
I'm unable to reproduce this on an Android device. As noted in the original bug, this doesn't occur when obscureText == true

**Comment by zoechi** [comment] 2018-08-27 11:04
@ROTGP thanks a lot for the update.

**Comment by justinmc** [comment] 2020-03-06 18:23
I wasn't able to reproduce this using a physical iPhone 7 on iOS 13 or a simulator iPhone 11 on iOS 13.  I'm closing it since no one has reported the bug in awhile, but if anyone sees it, let me know and I'll reopen.

**Closed by justinmc** 2020-03-06 18:23 UTC
Labels: a: text input, framework, severe: crash, ⌺‬ platform-ios

**Comment by faldunate** [comment] 2020-07-30 17:27
I've been experiencing this same error since yesterday when I upgraded to the latest version.

Flutter 1.21.0-6.0.pre.103 • channel master
