### ISSUE TITLE
Try to set the wallpaper using the Flutter app. After successfully changing the wallpaper, the app will restart.

### ISSUE THREAD

**Issue by vvvirani** [flutter/flutter#137934] opened 2023-11-06 12:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Execute `flutter run` on the code sample
2. Try to change wallpaper from Url (using `MethodChannel` to call the `WallpaperManager` class).
3. After the wallpaper change is successful, the app will restart.

### Expected results

After successfully changing the wallpaper, The application should not restart.

### Actual results

After successfully changing the wallpaper, the app will restart.

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<void> _setWallpaper(String imageUrl) async {
    try {
      _updateLoading(true);

      await WallpaperManager.setWallpaperFromUrl(
        imageUrl: imageUrl,
        flag: WallPaperLocation.both,
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Wallpaper Changed'),
          ),
        );
      }
    } on PlatformException catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(e.message ?? 'Invalid Image Url')),
        );
      }
    } finally {
      _updateLoading(false);
    }
  }
```

```kotlin
@RequiresApi(Build.VERSION_CODES.N)
    private fun setNormalWallpaperFromUrl(imageUrl: String, location: String) {
        if (!wallpaperManager.isWallpaperSupported) {
            result.error("NOT_SUPPORTED", "Wallpaper change is not supported", null)
            return
        }

        Glide.with(context)
            .asBitmap()
            .load(imageUrl)
            .listener(object : RequestListener<Bitmap?> {
                override fun onLoadFailed(
                    e: GlideException?,
                    model: Any?,
                    target: Target<Bitmap?>,
                    isFirstResource: Boolean,
                ): Boolean {
                    e?.printStackTrace()
                    result.error("FAILED", e?.localizedMessage, e?.stackTrace)
                    return false

                }

                override fun onResourceReady(
                    resource: Bitmap,
                    model: Any,
                    target: Target<Bitmap?>?,
                    dataSource: DataSource,
                    isFirstResource: Boolean,
                ): Boolean {
                    try {
                        when (location) {
                            "lock" -> {
                                wallpaperManager.setBitmap(
                                    resource,
                                    null,
                                    true,
                                    WallpaperManager.FLAG_LOCK
                                )

                            }

                            "home" -> {
                                wallpaperManager.setBitmap(resource)

                            }

                            "both" -> {
                                wallpaperManager.setBitmap(
                                    resource,
                                    null,
                                    true,
                                    WallpaperManager.FLAG_LOCK or WallpaperManager.FLAG_SYSTEM
                                )
                            }
                        }
                        result.success(true)

                    } catch (e: IOException) {
                        e.printStackTrace()
                        result.error("FAILED", e.localizedMessage, e.stackTrace)

                    }
                    return false
                }
            }).submit()
    }```

</details>


### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/55572605/7b28e14c-3c56-4e0d-86a6-b9deac8e4172

</details>


### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale
    en-IN)
    • Flutter version 3.13.9 on channel stable at /Users/vishalvirani/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/vishalvirani/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Vish’s iPhone 12 (mobile) • 00008101-0015081E2200801E • ios            •
      iOS 17.0.3 21A360
    • macOS (desktop)           • macos                     • darwin-arm64   •
      macOS 14.1 23B74 darwin-arm64
    • Chrome (web)              • chrome                    • web-javascript •
      Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2023-11-06 12:35
Closing as a duplicate of https://github.com/flutter/flutter/issues/133722

**Closed by stuartmorgan** 2023-11-06 12:35 UTC
