### ISSUE TITLE
OS Error: La syntaxe du nom de fichier, de répertoire ou de  volume est incorrecte., errno = 123)

### ISSUE THREAD

**Issue by BlueSharkytb** [flutter/flutter#131506] opened 2023-07-28 20:26 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Install Android Studio + Android SDK 
run flutter config --android-studio-dir=<'D:\android_studio'>
run flutter doctor

### Expected results

Have a working Android Preview Interface

### Actual results

Here is the entire error :

Oops; flutter has exited unexpectedly: "FileSystemException: Exists failed, path =
'<D:/Android studio>' (OS Error: La syntaxe du nom de fichier, de répertoire ou de 
volume est incorrecte.
, errno = 123)".
A crash report has been written to
D:\NSI\apprentissage\dart\flutter_chat\flutter_chat\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Exists+failed%2C+path+%3D+%27%3CD%3A%2FAndroid+studio%3E%27+%28OS+Error%3A+La+syntaxe+du+nom+de+fichier%2C+de+r%C3%A9pertoire+ou+de+volume+est+incorrecte.%0D%0A%2C+errno+%3D+123%29

To report your crash to the Flutter team, first read the guide to filing a bug.    
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing theissue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Exists+failed%2C+OS+Error%3A+La+syntaxe+du+nom+de+fichier%2C+de+r%C3%A9pertoire+ou+de+volume+est+incorrecte.%0D%0A%2C+errno+%3D+123&body=%23%23+Command%0A%60%60%60%0Aflutter+doctor%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Exists+failed%2C+OS+Error%3A+La+syntaxe+du+nom+de+fichier%2C+de+r%C3%A9pertoire+ou+de+volume+est+incorrecte.%0D%0A%2C+errno+%3D+123%0A%60%60%60%0A%230++++++_Directory.existsSync+%28dart%3Aio%2Fdirectory_impl.dart%3A92%3A7%29%0A%231++++++ForwardingFileSystemEntity.existsSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file_system_entity.dart%3A43%3A33%29%0A%232++++++ErrorHandlingDirectory.existsSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A492%3A22%29%0A%233++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A590%3A14%29%0A%234++++++ErrorHandlingDirectory.existsSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A491%3A12%29%0A%235++++++AndroidStudio.latestValid+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_studio.dart%3A244%3A64%29%0A%236++++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%237++++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%238++++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%239++++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2310+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2311+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2312+++++androidStudio+%28package%3Aflutter_tools%2Fsrc%2Fglobals.dart%3A65%3A45%29%0A%2313+++++runInContext.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcontext_runner.dart%3A104%3A32%29%0A%2314+++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%2315+++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%2316+++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%2317+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2318+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2319+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2320+++++androidLicenseValidator+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_workflow.dart%3A30%3A65%29%0A%2321+++++DoctorCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fdoctor.dart%3A53%3A32%29%0A%2322+++++FlutterCommand.verifyThenRunCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1568%3A12%29%0A%3Casynchronous+suspension%3E%0A%2323+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1336%3A27%29%0A%60%60%60%0A%60%60%60%0Aencountered+exception%3A+FileSystemException%3A+Exists+failed%2C+path+%3D+%27%3CD%3A%2FAndroid+studio%3E%27+%28OS+Error%3A+La+syntaxe+du+nom+de+fichier%2C+de+r%C3%A9pertoire+ou+de+volume+est+incorrecte.%0D%0A%2C+errno+%3D+123%29%0A%0A%230++++++_Directory.existsSync+%28dart%3Aio%2Fdirectory_impl.dart%3A92%3A7%29%0A%231++++++ForwardingFileSystemEntity.existsSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file_system_entity.dart%3A43%3A33%29%0A%232++++++ErrorHandlingDirectory.existsSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A492%3A22%29%0A%233++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A590%3A14%29%0A%234++++++ErrorHandlingDirectory.existsSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A491%3A12%29%0A%235++++++AndroidStudio.latestValid+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_studio.dart%3A244%3A64%29%0A%236++++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%237++++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%238++++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%239++++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2310+++++androidStudio+%28package%3Aflutter_tools%2Fsrc%2Fglobals.dart%3A65%3A45%29%0A%2311+++++runInContext.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcontext_runner.dart%3A113%3A32%29%0A%2312+++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%2313+++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%2314+++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%2315+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2316+++++androidValidator+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_workflow.dart%3A29%3A51%29%0A%2317+++++_DefaultDoctorValidatorsProvider.validators+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A139%3A44%29%0A%2318+++++Doctor.validators+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A230%3A47%29%0A%2319+++++Doctor.startValidatorTasks+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A236%3A45%29%0A%2320+++++DoctorText._validatorTasks+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A734%3A60%29%0A%2321+++++DoctorText._validatorTasks+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%29%0A%2322+++++DoctorText._runDiagnosis+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A738%3A53%29%0A%2323+++++DoctorText.piiStrippedText+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A731%3A47%29%0A%2324+++++DoctorText.piiStrippedText+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%29%0A%2325+++++CrashReporter.informUser+%28package%3Aflutter_tools%2Fsrc%2Freporting%2Fcrash_reporting.dart%3A92%3A32%29%0A%2326+++++_handleToolError+%28package%3Aflutter_tools%2Frunner.dart%3A196%3A36%29%0A%3Casynchronous+suspension%3E%0A%2327+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2328+++++main+%28package%3Aflutter_tools%2Fexecutable.dart%3A91%3A3%29%0A%3Casynchronous+suspension%3E%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+f468f3366c26a5092eb964a230ce7892fda8f2f8%0A%0A&labels=tool%2Csevere%3A+crash

### Code sample

<details><summary>Code sample</summary>

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

Oops; flutter has exited unexpectedly: "FileSystemException: Exists failed, path =
'<D:/Android studio>' (OS Error: La syntaxe du nom de fichier, de répertoire ou de 
volume est incorrecte.
, errno = 123)".
A crash report has been written to
D:\NSI\apprentissage\dart\flutter_chat\flutter_chat\flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Exists+failed%2C+path+%3D+%27%3CD%3A%2FAndroid+studio%3E%27+%28OS+Error%3A+La+syntaxe+du+nom+de+fichier%2C+de+r%C3%A9pertoire+ou+de+volume+est+incorrecte.%0D%0A%2C+errno+%3D+123%29

To report your crash to the Flutter team, first read the guide to filing a bug.    
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing theissue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Exists+failed%2C+OS+Error%3A+La+syntaxe+du+nom+de+fichier%2C+de+r%C3%A9pertoire+ou+de+volume+est+incorrecte.%0D%0A%2C+errno+%3D+123&body=%23%23+Command%0A%60%60%60%0Aflutter+doctor%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Exists+failed%2C+OS+Error%3A+La+syntaxe+du+nom+de+fichier%2C+de+r%C3%A9pertoire+ou+de+volume+est+incorrecte.%0D%0A%2C+errno+%3D+123%0A%60%60%60%0A%230++++++_Directory.existsSync+%28dart%3Aio%2Fdirectory_impl.dart%3A92%3A7%29%0A%231++++++ForwardingFileSystemEntity.existsSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file_system_entity.dart%3A43%3A33%29%0A%232++++++ErrorHandlingDirectory.existsSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A492%3A22%29%0A%233++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A590%3A14%29%0A%234++++++ErrorHandlingDirectory.existsSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A491%3A12%29%0A%235++++++AndroidStudio.latestValid+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_studio.dart%3A244%3A64%29%0A%236++++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%237++++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%238++++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%239++++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2310+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2311+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2312+++++androidStudio+%28package%3Aflutter_tools%2Fsrc%2Fglobals.dart%3A65%3A45%29%0A%2313+++++runInContext.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcontext_runner.dart%3A104%3A32%29%0A%2314+++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%2315+++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%2316+++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%2317+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2318+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2319+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2320+++++androidLicenseValidator+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_workflow.dart%3A30%3A65%29%0A%2321+++++DoctorCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fdoctor.dart%3A53%3A32%29%0A%2322+++++FlutterCommand.verifyThenRunCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1568%3A12%29%0A%3Casynchronous+suspension%3E%0A%2323+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1336%3A27%29%0A%60%60%60%0A%60%60%60%0Aencountered+exception%3A+FileSystemException%3A+Exists+failed%2C+path+%3D+%27%3CD%3A%2FAndroid+studio%3E%27+%28OS+Error%3A+La+syntaxe+du+nom+de+fichier%2C+de+r%C3%A9pertoire+ou+de+volume+est+incorrecte.%0D%0A%2C+errno+%3D+123%29%0A%0A%230++++++_Directory.existsSync+%28dart%3Aio%2Fdirectory_impl.dart%3A92%3A7%29%0A%231++++++ForwardingFileSystemEntity.existsSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file_system_entity.dart%3A43%3A33%29%0A%232++++++ErrorHandlingDirectory.existsSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A492%3A22%29%0A%233++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A590%3A14%29%0A%234++++++ErrorHandlingDirectory.existsSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A491%3A12%29%0A%235++++++AndroidStudio.latestValid+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_studio.dart%3A244%3A64%29%0A%236++++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%237++++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%238++++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%239++++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2310+++++androidStudio+%28package%3Aflutter_tools%2Fsrc%2Fglobals.dart%3A65%3A45%29%0A%2311+++++runInContext.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcontext_runner.dart%3A113%3A32%29%0A%2312+++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%2313+++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%2314+++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%2315+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2316+++++androidValidator+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_workflow.dart%3A29%3A51%29%0A%2317+++++_DefaultDoctorValidatorsProvider.validators+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A139%3A44%29%0A%2318+++++Doctor.validators+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A230%3A47%29%0A%2319+++++Doctor.startValidatorTasks+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A236%3A45%29%0A%2320+++++DoctorText._validatorTasks+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A734%3A60%29%0A%2321+++++DoctorText._validatorTasks+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%29%0A%2322+++++DoctorText._runDiagnosis+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A738%3A53%29%0A%2323+++++DoctorText.piiStrippedText+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A731%3A47%29%0A%2324+++++DoctorText.piiStrippedText+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%29%0A%2325+++++CrashReporter.informUser+%28package%3Aflutter_tools%2Fsrc%2Freporting%2Fcrash_reporting.dart%3A92%3A32%29%0A%2326+++++_handleToolError+%28package%3Aflutter_tools%2Frunner.dart%3A196%3A36%29%0A%3Casynchronous+suspension%3E%0A%2327+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2328+++++main+%28package%3Aflutter_tools%2Fexecutable.dart%3A91%3A3%29%0A%3Casynchronous+suspension%3E%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+f468f3366c26a5092eb964a230ce7892fda8f2f8%0A%0A&labels=tool%2Csevere%3A+crash
</details>

**Comment by huycozy** [comment] 2023-07-31 04:53
I pasted your trace log here (from the url in the console above):

>FileSystemException: Exists failed, OS Error: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.
, errno = 123

"FileSystemException: Exists failed, OS Error: The file, directory, or volume name syntax is incorrect." (using google translate)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:244:64)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#12     androidStudio (package:flutter_tools/src/globals.dart:65:45)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:104:32)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#20     androidLicenseValidator (package:flutter_tools/src/android/android_workflow.dart:30:65)
#21     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:32)
#22     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1568:12)
<asynchronous suspension>
#23     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
```

This is a duplicate of https://github.com/flutter/flutter/issues/99954 but it seems this can be quick fixed by correct `--android-studio-dir`. Can you try below command instead to see if it works?

```bash
flutter config --android-studio-dir="D:\android_studio"
```

**Comment by huycozy** [comment] 2023-08-04 05:54
Closing as a duplicate of https://github.com/flutter/flutter/issues/99954. Please follow up on that issue for further updates.

**Closed by huycozy** 2023-08-04 05:54 UTC
Labels: waiting for customer response, in triage
