### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by randhirkc** [flutter/flutter#159687] opened 2024-12-02 20:07 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. I am running on Macbook M1, i.e. Arm64 proc 
2. Simply run 'flutter run'
3. After some 20 seconds or so, the tool crashes and connection to the Emulator is lost
4. Same is happening while debugging as well.

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#2      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#3      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.24.5 on channel stable at /opt/homebrew/Caskroom/flutter/3.24.5/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /Users/randhir/Library/Android/sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[32m[✓][39m VS Code (version 1.95.3)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 15 (API 35) (emulator)
    [32m•[39m macOS (desktop)             • macos         • darwin-arm64  • macOS 15.1.1 24B91 darwin-arm64

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 80c2e84975bbd28ecf5f8d4bd4ca5a2490bfc819
### Plugins
file_picker-8.1.4
file_selector_linux-0.9.3
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
flutter_plugin_android_lifecycle-2.0.23
fluttertoast-8.2.8
image_picker-1.1.2
image_picker_android-0.8.12+15
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.5
path_provider_android-2.2.14
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1

**Comment by danagbemava-nc** [comment] 2024-12-03 07:36
Closing this as a duplicate of https://github.com/flutter/flutter/issues/154903

**Closed by danagbemava-nc** 2024-12-03 07:36 UTC
Labels: in triage
