### ISSUE TITLE
App crashed if webview exceeds 9000px.

### ISSUE THREAD

**Issue by Airoyee** [flutter/flutter#47658] opened 2019-12-23 08:59 UTC
App crashed if webview exceeds 9000px.And desktop will reboot.

**Target Platform:** Android
**Target OS version/browser:** Android 9.0
**Devices:** Lenovo Z5 pro

## Logs
```
log：/PlatformViewsController( 1429): Creating a virtual display of size: [996, 8400] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2160].
```

```
[ +100 ms] W/PlatformViewsController( 8834): Creating a virtual display of size: [996, 8400] may result in
problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2160].
[ +119 ms] I/eats.blockbeat( 8834): The ClassLoaderContext is a special shared library.

 E/MethodChannel#flutter/platform_views( 8834): Failed to handle method call
[        ] E/MethodChannel#flutter/platform_views( 8834): DeadSystemException: The system died; earlier logs will point to the root
cause
[        ] Lost connection to device.

```

## Doctor

```
[✓] Flutter (Channel dev, v1.10.15, on Mac OS X 10.14.6 18G1012, locale zh-Hans-CN)
    • Flutter version 1.10.15 at /Users/zhengxiangchen/Downloads/flutter
    • Framework revision fbabb264e0 (7 weeks ago), 2019-11-02 01:36:07 +0300
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zhengxiangchen/Library/Android/sdk
    • Android NDK at /Users/zhengxiangchen/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.4445.29

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.4445.29

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • Lenovo L78011 • ce006a9b   • android-arm64  • Android 9 (API 28)
    • Chrome        • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server    • web-server • web-javascript • Flutter Tools

• No issues found!

```

**Comment by janmoppel** [comment] 2019-12-23 10:59
Hello @Airoyee !

Thank you for posting an issue.
Can you please also attach the minimal example, so that issue can be easily reproduced?

**Comment by Airoyee** [comment] 2019-12-24 03:59
> Thanks  @janmoppel  
Here's a simple example:
```dart
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: WebPage(),
    );
  }
}

class WebPage extends StatefulWidget {
  @override
  _WebPageState createState() => _WebPageState();
}

const String kNavigationExamplePage = '''
<!DOCTYPE html><html>
<head><title>Navigation Delegate Example</title></head>
<body>
<p>
The navigation delegate is set to block navigation to the youtube website.
</p>
<ul>
<ul><a href="https://www.youtube.com/">https://www.youtube.com/</a></ul>
<ul><a href="https://www.google.com/">https://www.google.com/</a></ul>
</ul>
''';

class _WebPageState extends State<WebPage> {
  WebViewController webViewController;

  double webViewHeight = 1;

  @override
  Widget build(BuildContext context) {
    final String contentBase64 = base64Encode(const Utf8Encoder().convert(kNavigationExamplePage));
    return ListView(
      children: <Widget>[
        Container(
          height: 20000,
          child: WebView(
            initialUrl: 'data:text/html;base64,$contentBase64',
            javascriptMode: JavascriptMode.unrestricted,
            navigationDelegate: (nav) {
              return NavigationDecision.prevent;
            },
          ),
        ),
      ],
    );
  }
}
```


**App will crash if the webview with larger height wrapped in ListView**

**Comment by TahaTesser** [comment] 2020-03-17 11:00
Duplicate of [#45243](https://github.com/flutter/flutter/issues/45243)

**Closed by TahaTesser** 2020-03-17 11:00 UTC
Labels: p: webview, plugin, severe: crash, ▣ platform-android
