### ISSUE TITLE
Add the flutter application to an existing windows app

### ISSUE THREAD

**Issue by riyulu** [flutter/flutter#110055] opened 2022-08-23 02:57 UTC
## Use case

Use flutter to do hybrid development in an existing windows project

## Proposal

like demo : https://github.com/yeyu1271/flutter_pc_demo

Flutter renders as a child window. there are some problems now, for example, when the parent window is minimized and reopened, it is not paint by default

Wondering if there is planned support, like Android and iOS

**Comment by exaby73** [comment] 2022-08-23 08:39
Hello @yeyu1271. Thank you for filing this request. Labelling for further insights from the team.

**Comment by darshankawar** [comment] 2022-09-21 12:37
Closing this as duplicate of https://github.com/flutter/flutter/issues/80339

**Closed by darshankawar** 2022-09-21 12:37 UTC
Labels: new feature, platform-windows, a: existing-apps, proposal
