### ISSUE TITLE
When the SDK faces multiple Dialogs, it cannot specify one of them to close, I need pop.. pop.. pop

### ISSUE THREAD

**Issue by rhymelph** [flutter/flutter#134192] opened 2023-09-07 04:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case
```dart
class LoginView extends StatefulWidget {
  const LoginView({super.key});

  @override
  State<LoginView> createState() => _LoginViewState();
}

class _LoginViewState extends State<LoginView> {
  TextEditingController controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Demo '),
      ),
      body: Column(
        children: [
          TextField(
            controller: controller,
          ),
          TextButton(
              onPressed: () {
                showDialog(
                  context: context,
                  builder: (_) => const AlertDialog(
                    title: Text('Loading'),
                  ),
                );
                await _handleLogic();
// The pop of this is actually a pop-up box that wants to cancel loading, but if you do some warning processing when _handleLogic, it will turn off the warning, not loading.
                Navigator.of(context).pop();
              },
              child: const Text('Check')),
        ],
      ),
    );
  }

 Future<void> _handleLogic() async{
    if (controller.text.isEmpty) {
      showDialog(
        context: context,
        builder: (_) => AlertDialog(
          title: const Text('Warning'),
          content: const Text('Please input somthing.'),
          actions: [
            TextButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: const Text('OK')),
          ],
        ),
      );
      return;
    }
    // do something...
  }
}
```

### Proposal

It is recommended to add an **id parameter** or **name parameter** to the `showDialog` method. 
```dart
                showDialog(
                  context: context,
                  name:"loading",
                  builder: (_) => const AlertDialog(
                    title: Text('Loading'),
                  ),
                );
```
When using `Navigator.of (context).pop ()`, it is best to have a method `Navigator.of (context).popDialog (name: "loading")`, so that I can close the corresponding popbox according to the id or name, instead of the current top-level popbox

**Comment by rhymelph** [comment] 2023-09-07 04:52
Also, sdk has provided us with `Navigator.of (context).pushNamed`, why not `Navigator.of (context).popNamed`.

**Comment by danagbemava-nc** [comment] 2023-09-07 11:29
Closing this as a duplicate of https://github.com/flutter/flutter/issues/62960.

**Closed by danagbemava-nc** 2023-09-07 11:29 UTC
Labels: in triage
