### ISSUE TITLE
firebase_admob 0.9.0 crashes Android

### ISSUE THREAD

**Issue by willvlad** [flutter/flutter#33692] opened 2019-06-01 00:04 UTC
verbose flutter run gives only the following cryptic error:

[ +145 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=xxx.xxx.app/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...

**Comment by BondarenkoStas** [comment] 2019-10-08 14:19
@willvlad what the device do you use to test? Please provide your flutter doctor. 
Did you manage to solve it? Does it happen on new projects as well?

**Comment by iapicca** [comment] 2019-11-08 12:27
Hi @willvlad 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 12:27 UTC
Labels: waiting for customer response
