### ISSUE TITLE
Failed assertion: 'tableWidth >= targetWidth': is not true

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#31407] opened 2019-04-22 06:22 UTC
## Steps to reproduce

```dart
void main() {
  runApp(
    Directionality(
      textDirection: TextDirection.ltr,
      child: Table(
        children: <TableRow>[
          TableRow(children: <Widget>[
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
            Text('a very very very very very long header column'),
          ])
        ],
      ),
    ),
  );
}
```

## Result

```
I/flutter ( 3395): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 3395): The following assertion was thrown during performLayout():
I/flutter ( 3395): 'package:flutter/src/rendering/table.dart': Failed assertion: line 882 pos 16: 'tableWidth >=
I/flutter ( 3395): targetWidth': is not true.
I/flutter ( 3395): 
I/flutter ( 3395): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3395): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3395): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3395):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 3395): 
I/flutter ( 3395): When the exception was thrown, this was the stack:
I/flutter ( 3395): #2      RenderTable._computeColumnWidths (package:flutter/src/rendering/table.dart:882:16)
I/flutter ( 3395): #3      RenderTable.performLayout (package:flutter/src/rendering/table.dart:1003:33)
I/flutter ( 3395): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 3395): #5      RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter ( 3395): #6      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter ( 3395): #7      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 3395): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:336:19)
I/flutter ( 3395): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 3395): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:275:5)
I/flutter ( 3395): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 3395): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 3395): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
I/flutter ( 3395): #22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 3395): #23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 3395): #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter ( 3395): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter ( 3395): 
I/flutter ( 3395): The following RenderObject was being processed when the exception was fired:
I/flutter ( 3395):   RenderTable#66c5f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   creator: Table ← Directionality ← [root]
I/flutter ( 3395):   parentData: <none>
I/flutter ( 3395):   constraints: BoxConstraints(w=411.4, h=683.4)
I/flutter ( 3395):   size: MISSING
I/flutter ( 3395):   default column width: FlexColumnWidth(1.0)
I/flutter ( 3395):   table size: 11×1
I/flutter ( 3395):   column offsets: unknown
I/flutter ( 3395):   row offsets: []
I/flutter ( 3395): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 3395):   RenderParagraph#99856 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#16efa NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#1af0b NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#a3054 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#ebb59 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#961c2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#77c7d NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#c08ed NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#27a05 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#66c75 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395):   RenderParagraph#3b5dc NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3395): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 3395): Another exception was thrown: 'package:flutter/src/rendering/table.dart': Failed assertion: line 1130 pos 12: '_rowTops.length == rows + 1': is not true.
```

**Comment by timsneath** [comment] 2019-05-04 00:53
I'm hitting this with an app that I'm writing in my leisure time, where displaying the soft keyboard causes this error to occur if I have more than eight keycaps in a row. https://github.com/timsneath/cambridge/blob/hummingbird/spectrum/lib/key.dart

**Comment by tvolkert** [comment] 2019-05-06 04:56
FYI, I was able to sidestep this bug by not using `Table` at all but rather by making a custom layout.

**Comment by chunhtai** [comment] 2019-05-30 17:30
I confirmed this is a duplicate of https://github.com/flutter/flutter/issues/23723
This is what i got before the assert tableWidth 411.4285714285714, targetWidth 411.42857142857144
It is a precision error

**Closed** 2019-05-30 18:59 UTC
Labels: customer: payouts, framework, severe: crash

**Comment by timsneath** [comment] 2019-05-31 18:43
I can confirm that this is now fixed for my scenario in master. Have [updated my code accordingly](https://github.com/timsneath/cambridge/blob/master/spectrum/lib/key.dart) and I can't reproduce the assert any longer. Thank you!
