### ISSUE TITLE
Exact duplicate Dart VM Services when running flutter attach

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#119535] opened 2023-01-30 18:00 UTC
Occasionally, there will be multiple results with the same application id and port when running `flutter attach`.

## Steps to Reproduce

1. Run flutter app wirelessly through Xcode
2. Run `flutter attach` in terminal
3. If you don't get the error, stop the attach and stop in Xcode and try steps 1-2 again

```
There are multiple Dart VM Services available.
Rerun this command with one of the following passed in as the app-id and device-vmservice-port:

  flutter attach --app-id "com.example.app_name" --device-vmservice-port xxxxxx
  flutter attach --app-id "com.example.app_name" --device-vmservice-port xxxxxx
```

**Comment by jmagman** [comment] 2023-01-30 18:53
@vashworth I've seen the duplication before with `flutter attach` on a usb-tethered device.

**Comment by vashworth** [comment] 2023-01-30 19:28
@jmagman You're right, it's not specific to wireless. USB will have issue too. As for having seen before, I believe this issue was introduced with wireless debugging. However, there's also a separate issue that's similar that I just added https://github.com/flutter/flutter/issues/119549. Maybe you've seen that one before?

**Comment by jmagman** [comment] 2023-01-30 19:45
Is this a duplicate of https://github.com/flutter/flutter/issues/119549 then?

**Comment by vashworth** [comment] 2023-01-30 19:55
No it's a slightly different issue. In that one, it's not an exact match. The name of the application id differs because there's a number attached to the end. In this one, the application id is exactly the same. 

Before wireless debugging, it would use a Set to filter out duplicates. 
https://github.com/flutter/flutter/blob/b06b8b2710955028a6b562f5aa6fe62941d6febf/packages/flutter_tools/lib/src/mdns_discovery.dart#L75-L77

**Comment by jmagman** [comment] 2023-01-30 20:19
> Before wireless debugging, this particular issue (not #119549) was handled by using a Set to filter out duplicates.

Ah, gotcha.

**Closed** 2023-01-31 17:48 UTC
Labels: platform-ios, tool
