### ISSUE TITLE
Cancelling Google Sign In on Android & iOS throws exception instead of returning null 

### ISSUE THREAD

**Issue by delasign** [flutter/flutter#59520] opened 2020-06-16 01:49 UTC
The code below throws a platform exception - even if I add a `on PlatformException catch(e)` when pressing cancel on the sign in that pops up

`Future<bool> signInWithGoogle() async {
  GoogleSignInAccount googleSignInAccount;
  try {
    await googleSignIn.signIn();
    return true;
  } catch (error, s) {
    print(error);
    print(s);
    return false;
  }
}`

**Comment by delasign** [comment] 2020-06-16 01:50
`[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.17.3 at /Users/oscardelaheragomez/Documents/Flutter/flutter
    • Framework revision b041144f83 (11 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/oscardelaheragomez/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone XS • ios • iOS 13.5.1`

**Comment by delasign** [comment] 2020-06-16 01:55
`PlatformException (PlatformException(sign_in_canceled, com.google.GIDSignIn, The user canceled the sign-in flow.))`

**Comment by delasign** [comment] 2020-06-16 02:04
Please note this only occurs when debugging, if I run `flutter run` it works really well

**Comment by TahaTesser** [comment] 2020-06-16 09:56
duplicate of https://github.com/flutter/flutter/issues/44431

**Closed by TahaTesser** 2020-06-16 09:56 UTC
