### ISSUE TITLE
Error when building APK with url_launcher package on Flutter 3.13.3 and Android Studio Giraffe 2022.3.1 Patch 1

### ISSUE THREAD

**Issue by jm-borges** [flutter/flutter#134383] opened 2023-09-10 14:28 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new Flutter project using the `flutter create` command.
2. Add the `url_launcher` package to your project's `pubspec.yaml` file with version `^6.1.14`.
3. Run the command `flutter build apk`.

### Expected results

The APK build should complete successfully without any errors.

### Actual results

The build process completes with the mentioned error messages related to Kotlin version compatibility, but the app installed with the APK crashes when launched.

### Code sample

<details><summary>No code sample to provide</summary>

```dart
//
```

</details>

### Logs

**Description**:

**Summary**:
When attempting to build an APK in a brand new Flutter app created with `flutter create`, the following error occurs:

```
e: C:/Users/Jo�o Manoel Borges/.gradle/caches/transforms-3/c4988ff80110f75080a936fc6f044848/transformed/core-1.10.1/jars/classes.jar!/META-INF/core_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Jo�o Manoel Borges/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation-jvm/1.6.0/a7257339a052df0f91433cf9651231bbb802b502/annotation-jvm-1.6.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Jo�o Manoel Borges/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Jo�o Manoel Borges/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Jo�o Manoel Borges/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Jo�o Manoel Borges/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.22/1a8e3601703ae14bb58757ea6b2d8e8e5935a586/kotlin-stdlib-common-1.8.22.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
Running Gradle task 'assembleRelease'...                          143,4s
√  Built build\app\outputs\flutter-apk\app-release.apk (17.4MB).
```

**Environment**:
- Flutter Version: 3.13.3
- Android Studio Version: Giraffe | 2022.3.1 Patch 1
- Kotlin Plugin Version in Android Studio: 223-1.9.0-release-358-AS8836.35.2231.10671973

**Additional Information**:
- The error seems to be related to Kotlin version compatibility in the Android Gradle build, but I have limited understanding of Android development.
- Without the package in pubspec.yaml, the APK is built normally and the app does not crash.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS C:\Users\Public\Development\Styles TH\teste> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [versÆo 10.0.19045.3324], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.82.0)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

Obs: I am aware that Visual Studio is not installed, as I currently do not develop apps for Windows.

</details>

**Comment by darshankawar** [comment] 2023-09-11 10:48
@jm-borges 
This seems to be duplicate of https://github.com/flutter/flutter/issues/134149
Please see https://github.com/flutter/flutter/issues/134149#issuecomment-1709839426 for solution.
Closing as such.

**Closed by darshankawar** 2023-09-11 10:48 UTC
Labels: in triage
