### ISSUE TITLE
Extra character while writing LTR and RTL languages in a text field

### ISSUE THREAD

**Issue by MetaiR** [flutter/flutter#68989] opened 2020-10-25 15:10 UTC
## Steps to Reproduce

1. create an empty application
2. add one text field to the application
3. (optional) you can make its obscure equals to true to see the problem better by seeing the count of dots
4. type something in English
5. change the language of your keyboard (we tested by Persian) and type another thing
6. use space
7. u must see another character is being written beside the space (we check the ASCII code and believe it is half space)

from several observation and tests, I believe this problem is happening when you are writing an LTR language inside an LTR field then you use an RTL language inside the same field (or vice-versa with the RTL field), and when it occurred if u even delete all the character and write again with only one language it still happening.

summary:
u have a LTR filed -> write LTR language (it's still ok) -> write RTL -> use space
or
u have an RTL field -> write RTL language (it's still ok) -> write LTR -> use space 

> note: because the half-space character is not visual and doesn't persist any spaces between characters you may want to use shift + right arrow and select the characters to feel it.

> note: this has been happening since flutter version 1.17 and because of that we have to use 1.12.13+hotfix6

it is a bit confusing when it comes to writing on a paper so u can see this video for a better understanding

![ezgif-6-fd79323b979e](https://user-images.githubusercontent.com/7807264/97110996-7e7d4380-16f1-11eb-8128-78174ce53bf2.gif)

**Comment by MetaiR** [comment] 2020-10-25 22:04
anybody?

**Comment by pedromassangocode** [comment] 2020-10-26 09:32
I was able to reproduce on latest master channel.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.57, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-4.0.pre.57 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision fdac8a9d1f (8 hours ago), 2020-10-25 19:47:02 -0400
    • Engine revision d4a3c9c471
    • Dart version 2.11.0 (build 2.11.0-256.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```
</details>

**Comment by MetaiR** [comment] 2020-11-05 19:34
so is there any patch for this problem yet?

**Comment by xJon** [comment] 2020-11-11 21:36
Probably a duplicate of https://github.com/flutter/flutter/issues/63042.

**Closed** 2021-03-25 00:54 UTC
Labels: P4, a: text input, engine, f: material design, found in release: 1.24, framework, has reproducible steps
