### ISSUE TITLE
Flaky over-release of FLValue* in FlEngineTest.SettingsPlugin test trips presubmits.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#73806] opened 2021-01-12 20:49 UTC
These instances were user-reported over the past week:

* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858736486722349488/+/steps/Host_Tests_for_host_debug_unopt/0/stdout
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858802668038323456/+/steps/Host_Tests_for_host_profile/0/stdout

The specific error is:
```
** (process:23103): CRITICAL **: void fl_value_unref(FlValue *): assertion 'self->ref_count > 0' failed
```

**Comment by stuartmorgan** [comment] 2021-01-13 03:01
Duplicate of https://github.com/flutter/flutter/issues/73517; should already be fixed.

**Closed by stuartmorgan** 2021-01-13 03:01 UTC
Labels: P2, a: desktop, engine, team: flakes
