### ISSUE TITLE
Rendering error when nesting GridView inside of a Stepper

### ISSUE THREAD

**Issue by KLee1248** [flutter/flutter#9663] opened 2017-04-28 07:43 UTC
## Steps to Reproduce

1. Create an app with a `ListView` or `GridView` inside of a `Stepper`:

```dart
class _BugTestState extends State<BugTest> {

  @override
  Widget build(BuildContext context) {
    List<Step> steps = [
      new Step(
        title: new Text('Test'),
        content: new GridView.extent(
            maxCrossAxisExtent: 200.0,
            padding: new EdgeInsets.all(6.0),
            children: [new Container(color: new Color(0xFF0000FF), child: new Text("HI"))]
    ))];

    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Stepper Page")
      ),
      body: new Stepper(
        steps: steps,
        type: StepperType.vertical
      ),
    );
  }
}

class BugTest extends StatefulWidget {
  @override
  _BugTestState createState() => new _BugTestState();
}
````

2. Attach to an app and run in debug mode.

I get the following error on the application: 
```
'package:flutter/src/rendering/object.dart': Failed assertion. line 1379 pos 12: '_debugCanPerformMutations': is not true.
```

## Logs

```
I/flutter (22374): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (22374): The following NoSuchMethodError was thrown during performLayout():
I/flutter (22374): The method 'toDouble' was called on null.
I/flutter (22374): Receiver: null
I/flutter (22374): Tried calling: toDouble()
I/flutter (22374): 
I/flutter (22374): When the exception was thrown, this was the stack:
I/flutter (22374): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
I/flutter (22374): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter (22374): #2      double.- (dart:core-patch/double.dart:21)
I/flutter (22374): #3      ViewportOffset&ScrollMetrics.extentBefore (package:flutter/src/widgets/scroll_metrics.dart:51:46)
I/flutter (22374): #4      ViewportOffset&ScrollMetrics.toString (package:flutter/src/widgets/scroll_metrics.dart:71:28)
I/flutter (22374): #5      _StringBase._interpolate (dart:core-patch/string_patch.dart:812)
I/flutter (22374): #6      RenderViewportBase.debugFillDescription (package:flutter/src/rendering/viewport.dart:408:38)
I/flutter (22374): #7      RenderViewport.debugFillDescription (package:flutter/src/rendering/viewport.dart:942:31)
I/flutter (22374): #8      RenderObject.toStringShallow (package:flutter/src/rendering/object.dart:2658:5)
I/flutter (22374): #9      RenderObject._debugReportException.<anonymous closure> (package:flutter/src/rendering/object.dart:1422:34)
I/flutter (22374): #10     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:296:17)
I/flutter (22374): #11     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:372:14)
I/flutter (22374): #12     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1414:18)
I/flutter (22374): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1854:9)
I/flutter (22374): #14     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #16     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #18     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #20     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #22     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #24     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #26     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:500:15)
I/flutter (22374): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #28     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:160:11)
I/flutter (22374): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #30     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #32     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:433:15)
I/flutter (22374): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #34     RenderAnimatedSize.performLayout (package:flutter/src/rendering/animated_size.dart:122:11)
I/flutter (22374): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #37     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:980:24)
I/flutter (22374): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #39     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:433:15)
I/flutter (22374): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #41     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:500:15)
I/flutter (22374): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #43     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #45     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:156:27)
I/flutter (22374): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #47     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:182:13)
I/flutter (22374): #48     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1057:12)
I/flutter (22374): #49     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1020:20)
I/flutter (22374): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #51     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #53     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #55     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #57     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #59     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #61     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #63     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
I/flutter (22374): #64     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:85:7)
I/flutter (22374): #65     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter (22374): #66     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter (22374): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #68     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #70     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #72     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #74     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #76     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #78     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #80     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2481:14)
I/flutter (22374): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #82     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (22374): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1866:7)
I/flutter (22374): #84     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:433:15)
I/flutter (22374): #85     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1743:7)
I/flutter (22374): #86     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1044:18)
I/flutter (22374): #87     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:225:19)
I/flutter (22374): #88     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:354:23)
I/flutter (22374): #89     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
I/flutter (22374): #90     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:645:15)
I/flutter (22374): #91     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:580:9)
I/flutter (22374): #92     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (22374): 
I/flutter (22374): The following RenderObject was being processed when the exception was fired:
I/flutter (22374):   RenderIgnorePointer#478505371 relayoutBoundary=up23 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22374):   creator: IgnorePointer-[GlobalKey#594132279] ← Listener ← _GestureSemantics ←
I/flutter (22374):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#723003073] ← RepaintBoundary ←
I/flutter (22374):   CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification> ←
I/flutter (22374):   GlowingOverscrollIndicator ← Scrollable ← GridView ← Column ← ⋯
I/flutter (22374):   parentData: <none> (can use size)
I/flutter (22374):   constraints: BoxConstraints(0.0<=w<=276.0, 0.0<=h<=Infinity)
I/flutter (22374):   size: MISSING
I/flutter (22374):   ignoring: false
I/flutter (22374):   ignoringSemantics: implicitly false
I/flutter (22374): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (22374):   RenderViewport#705082817 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22374):     RenderSliverPadding#719761743 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22374):       RenderSliverGrid#530368393 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22374): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/klee1/Code/flutter
    • Framework revision 2e194d5b44 (34 hours ago), 2017-04-26 14:30:20 -0700
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/klee1/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.0

[✓] Connected devices
    • SM G920V • 1015fabb89b91505 • android-arm • Android 7.0 (API 24) (emulator)
```

**Comment by eseidelGoogle** [comment] 2017-04-28 15:10
It looks like there was an error during error reporting. :/  @Hixie

**Comment by Shantanu-Kotambkar** [comment] 2018-09-28 17:05
Hi @eseidelGoogle @Hixie @KLee1248 , 

The 

> _debugCanPerformMutations': is not true 

exception pops up for me as well, when i am using a stepper. However, for me i have customized the original implementation of stepper, which makes it harder to give you relevant information. As of now, the exception is thrown only when i deal with certain widget states in my stepper. For example, if i have a checkbox and i check and then uncheck it,  and then switch to a next widget, i sometimes encounter this exception. Also, if i do not use a card widget for displaying widgets i encounter this exception occasionally. Now this may be completely irrelevant. Looking at the tag on the issue, i believe you already know the problem. Would you be able to explain to me what might be wrong here? it will help me fix my custom implementation

**Comment by iapicca** [comment] 2019-11-01 12:37
Hi @KLee1248 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by TahaTesser** [comment] 2020-02-26 11:49
Hi @KLee1248 
A lot has changed since you reported this issue and mentioned issue is also closed
Are you still experiencing this issue with the latest version of Flutter?
If yes, please a new issue and provide necessary details 
I feel free to close this issue for now
Thank you

**Closed by TahaTesser** 2020-02-26 11:49 UTC
Labels: f: material design, f: scrolling, framework, severe: crash
