### ISSUE TITLE
My app stuck when restart phone and need tp clear cache to work

### ISSUE THREAD

**Issue by AbanoubWagih94** [flutter/flutter#99633] opened 2022-03-06 14:34 UTC
My app work fine but i have a problem when user restart phone and try open app again it stuck on splash screen and when clear data and cache storage app work again.
this happened only on samsung phons .

here Android Manifest file
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools" package="com.myapp.myapp">
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>
  <uses-permission android:name="com.android.vending.BILLING" />
  <uses-permission android:name="android.permission.WAKE_LOCK"/>
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
  <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />

  <queries>
    
    <intent>
      <action android:name="android.intent.action.VIEW" />
      <data android:scheme="https" />
    </intent>
    
    <intent>
      <action android:name="android.intent.action.DIAL" />
      <data android:scheme="tel" />
    </intent>
    
    <intent>
      <action android:name="android.intent.action.SEND" />
      <data android:mimeType="*/*" />
    </intent>
    <package android:name="com.facebook.katana" />
  </queries>
  <application android:label="myapp" android:icon="@mipmap/launcher_icon" android:usesCleartextTraffic="true" android:allowBackup="false">
    <activity android:name="com.ryanheise.audioservice.AudioServiceActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize" android:exported="true">
      
      <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
      
      <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable"  android:resource="@drawable/launch_background" />
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="poc" android:host="deeplink.flutter.dev" />
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
    
    <meta-data android:name="flutterEmbedding" android:value="2" />
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
    

    <activity xmlns:tools="http://schemas.android.com/tools" android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="myapp" android:theme="@style/FullyTranslucent" tools:replace="android:theme"  />

    <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="@string/fb_login_protocol_scheme" />
      </intent-filter>
    </activity>

    
    <service android:name="com.ryanheise.audioservice.AudioService" android:exported="true" tools:ignore="Instantiatable">
      <intent-filter>
        <action android:name="android.media.browse.MediaBrowserService" />
      </intent-filter>
    </service>

    
    <receiver android:name="com.ryanheise.audioservice.MediaButtonReceiver" android:exported="true" tools:ignore="Instantiatable">
      <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
      </intent-filter>
    </receiver>

  </application>
</manifest>

`

here build.gradle file 
`         def localProperties = new Properties()
          def localPropertiesFile = rootProject.file('local.properties')
          if (localPropertiesFile.exists()) {
           localPropertiesFile.withReader('UTF-8') { reader ->
           localProperties.load(reader)
           }
           }

          def flutterRoot = localProperties.getProperty('flutter.sdk')
         if (flutterRoot == null) {
           throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
         }

       def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
       if (flutterVersionCode == null) {
        flutterVersionCode = '1'
        }

        def flutterVersionName = localProperties.getProperty('flutter.versionName')
        if (flutterVersionName == null) {
        flutterVersionName = '1.0'
          }

         def keystoreProperties = new Properties()
        def keystorePropertiesFile = rootProject.file('key.properties')
           if (keystorePropertiesFile.exists()) {
         keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
         }

         apply plugin: 'com.android.application'
        apply plugin: 'com.google.gms.google-services'
        apply plugin: 'kotlin-android'
       apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
       android.defaultConfig.ndk.debugSymbolLevel = 'FULL'
       android {
        compileSdkVersion 31
        sourceSets {
         main.java.srcDirs += 'src/main/kotlin'
     }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.myapp.myapp"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
        
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       release {
            zipAlignEnabled false
            shrinkResources false // Add this line.
            minifyEnabled false
            signingConfig signingConfigs.release
       }
   }
}

flutter {
    source '../..'
}

dependencies {
    def billing_version = "4.0.0"

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.android.billingclient:billing:$billing_version"
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation platform('com.google.firebase:firebase-bom:28.4.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.facebook.android:facebook-android-sdk:latest.release'
    implementation 'com.facebook.android:facebook-login:[8.9)'
    implementation 'androidx.work:work-runtime-ktx:2.7.0'

}`
here flutter doctor -v : 
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
    • Flutter version 2.8.0 at D:\programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (3 months ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 98.0.1108.62

• No issues found!

**Comment by darshankawar** [comment] 2022-03-07 09:54
@AbanoubWagih94 
Looking at the details you provided, we can't tell what exactly the issue is or if it's framework issue, so I would suggest you to ask this question on support channels like StackOverflow.
Closing from here as this looks more of a general question. If you disagree or think there's a genuine issue and error is due to framework, write in comments with details and I'll reopen it.
Thanks.

**Closed by darshankawar** 2022-03-07 09:54 UTC
Labels: in triage
