### ISSUE TITLE
Implement WinUI 3 To Flutter

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#124380] opened 2023-04-07 08:21 UTC
I have Suggestion Please Implement WinUI 3 To Flutter Framework.

**Comment by huycozy** [comment] 2023-04-07 08:44
Closing as a duplicate of https://github.com/flutter/flutter/issues/46481. Please follow up on it for further updates.

**Closed by huycozy** 2023-04-07 08:44 UTC
Labels: in triage
