### ISSUE TITLE
Flutter crash report.

### ISSUE THREAD

**Issue by hamid5434** [flutter/flutter#130679] opened 2023-07-16 13:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter build apk --target-platform android-arm --analyze-size

## exception

_TypeError: Null check operator used on a null value

```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:548:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

### Actual results

flutter build apk --target-platform android-arm --analyze-size


### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    [32m•[39m Flutter version 3.10.6 on channel stable at G:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (4 days ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at F:\SDKApp\Sdk
    [32m•[39m Platform android-34, build-tools 33.0.2
    [32m•[39m ANDROID_HOME = F:\SDKApp\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    [33m![39m Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.10.2)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    [32m•[39m Visual Studio Enterprise 2019 version 16.10.31410.357
    [31m✗[39m Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[32m[✓][39m VS Code, 64-bit edition (version 1.63.2)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 3.36.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m PM85 (mobile)     • 21309A0019 • android-arm64  • Android 9 (API 28)
    [32m•[39m Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.928]
    [32m•[39m Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.199
    [32m•[39m Edge (web)        • edge       • web-javascript • Microsoft Edge 114.0.1823.82

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

**Comment by danagbemava-nc** [comment] 2023-07-17 08:34
Closing this as a duplicate of https://github.com/flutter/flutter/issues/129706

**Closed by danagbemava-nc** 2023-07-17 08:34 UTC
Labels: in triage
