### ISSUE TITLE
It happend when Flutter Upgrading was running

### ISSUE THREAD

**Issue by amirucefi** [flutter/flutter#80882] opened 2021-04-21 18:12 UTC
It happened when Flutter Upgrading was running, How can I solve this?

```console
Downloading Dart SDK from Flutter engine b09f014e9658da6647361e7e416d1a159d34192d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   193  100   193    0     0    224      0 --:--:-- --:--:-- --:--:--   224
[/home/vahid/Android/flutter/bin/cache/dart-sdk-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/vahid/Android/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/vahid/Android/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/vahid/Android/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.
```

It appears that the downloaded file is corrupt; please try again.

**Comment by TahaTesser** [comment] 2021-04-22 08:03
Hi @amirucefi 
Thanks for filing the issue,

I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/66243
Meanwhile can you please reinstall 
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-22 08:03 UTC
Labels: in triage
