### ISSUE TITLE
Android build issue

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9121] opened 2017-03-31 11:25 UTC
## Steps to Reproduce

1. Create a build new app:
   ```
   flutter create repro
   cd repro
   flutter build apk
   ```
1. Start Android Studio, and File>Open `repro/android/`
1. Say to no gradle wrapper
1. Try to build

=>

```
Error:Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (24.2.0) and test app (25.0.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
```

## Flutter Doctor

```
mit-macbookpro2:repro2 mit$ flutter doctor
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/mit/dev/github/flutter
    • Framework revision 86e9fc1c68 (10 hours ago), 2017-03-30 18:46:32
    • Engine revision bf698a1fe5
    • Tools Dart version 1.23.0-dev.10.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/mit/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.0
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

```

**Comment by collinjackson** [comment] 2017-03-31 15:49
Possible dupe of #9120

**Comment by collinjackson** [comment] 2017-03-31 16:36
I rolled back what I believe is the problematic change, please reopen if you're still seeing issues.

**Closed by collinjackson** 2017-03-31 16:36 UTC
