### ISSUE TITLE
flutter analyze fails with web plugins generated_plugin_registrant.dart

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#45711] opened 2019-11-27 17:32 UTC
We are currently facing an analyze issue with the `generated_plugin _registrant.dart` file. The analyzer fails when this file is generated. Our current work around is to run analyze before running any tests or building the project in CI, but we would like to be able to do reruns with out doing a fresh install of our Flutter project.

## Steps to Reproduce

1. Add a Flutter web plugin to a project
2. Run the project in some way
3. Run `flutter analyze` to get this failure

## Logs

```
$ flutter analyze

Running "flutter pub get" in app_flutter...                         0.5s
Analyzing app_flutter...                                                

   info • Unused import: 'dart:ui' • lib/generated_plugin_registrant.dart:4:8 • unused_import
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.12.15-pre.20, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.15-pre.20 at /usr/local/google/home/chillers/flutter
    • Framework revision 831163f0d0 (19 hours ago), 2019-11-26 14:49:56 -0800
    • Engine revision e136d637a8
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/local/google/home/chillers/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 29.0.2
    • Java binary at: /opt/android-studio-with-blaze-3.5/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio-with-blaze-3.4
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio-with-blaze-3.5
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /opt/intellij-ue-2019.1
    • Flutter plugin version 39.0.2
    • Dart plugin version 191.8423

[✓] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by gi097** [comment] 2019-12-14 14:05
You can temporarily resolve this issue by creating a `analysis_options.yaml` in your project root and add the following:

```yaml
analyzer:
  exclude: [lib/generated_plugin_registrant.dart]
```

**Comment by tianhaoz95** [comment] 2019-12-21 06:42
Is there a more proper way to resolve this?

**Comment by hterkelsen** [comment] 2020-01-06 22:57
It looks like this was fixed in https://github.com/flutter/flutter/pull/47593

Please try again and re-open if the issue isn't fixed.

**Closed by hterkelsen** 2020-01-06 22:57 UTC
Labels: ☸ platform-web
