### ISSUE TITLE
%5Btool_crash%5D FileSystemException%3A Cannot retrieve length of file%2C OS Error%3A %D0%9D%D0%B5 %D1%83%D0%B4%D0%B0%D0%B5%D1%82%D1%81%D1%8F %D0%BD%D0%B0%D0%B9%D1%82%D0%B8 %D1%83%

### ISSUE THREAD

**Issue by sh1998t** [flutter/flutter#140951] opened 2024-01-04 07:25 UTC

**Comment by dam-ease** [comment] 2024-01-04 08:45
Hi @sh1998t  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2024-01-04 08:45 UTC
Labels: in triage
