### ISSUE TITLE
[webview_flutter][iOS] Fail to upload iOS App via XCode 

### ISSUE THREAD

**Issue by leochiu-work** [flutter/flutter#105471] opened 2022-06-06 22:02 UTC
I tried to upload my flutter iOS App via XCode, but following errors shown.
It used to be working before, I have no idea why.
Thank you.

<img width="734" alt="Screenshot 2022-06-06 at 22 57 16" src="https://user-images.githubusercontent.com/24238131/172256448-0affca4e-f551-4d6e-a238-a603cfdbb2da.png">

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 2.10.5 at /Users/leochiu/Documents/Sources/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (7 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/leochiu/Library/Android/sdk
    • Platform android-31, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • SM A515F (mobile) • R58N9318TRB • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by rainaakshay** [comment] 2022-06-06 22:13
I'm having the same exact problem. Restarted, cleaned, reinstalled, nothing helps

**Comment by Emperor-Koala** [comment] 2022-06-06 22:58
I am also having this issue. From looking around online today, many people across several cross-platform frameworks are having this exact issue, all starting a few hours ago. The issue seems to have arisen due to the WWDC that happened today, and probably the public betas/system maintenance that happened today.

**Comment by bill-smashing** [comment] 2022-06-06 23:20
This is happening to us also.

**Comment by stuartmorgan** [comment] 2022-06-06 23:24
Duplicate of https://github.com/flutter/flutter/issues/105472

**Closed by stuartmorgan** 2022-06-06 23:24 UTC

**Comment by paulocoutinhox** [comment] 2022-06-07 05:51
Hi,

Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."

Thanks.
