### ISSUE TITLE
[Web] TextField cursor in the wrong place when

### ISSUE THREAD

**Issue by mo-ah-dawood** [flutter/flutter#79885] opened 2021-04-06 19:16 UTC
when using arabic direction rtl and try to write english in textfield the cursor is in the wrong place

https://user-images.githubusercontent.com/31937782/113765298-60922100-971c-11eb-8cc3-17fe8488b708.mov

also i tried to set textAlign to end the cursor fixed partially but  its still wrong place

https://user-images.githubusercontent.com/31937782/113765784-02b20900-971d-11eb-8e2d-b6ba70d7bd8d.mov

steps 
 - create flutter app
 - use localization and make locale => Locale("ar)
 - Try TextField

Platform : Web

**Comment by TahaTesser** [comment] 2021-04-07 12:45
Hi @mo-ah-dawood 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/78550
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed** 2021-04-07 12:46 UTC
Labels: r: duplicate
