### ISSUE TITLE
build iOS apps on Linux

### ISSUE THREAD

**Issue by miklcct** [flutter/flutter#160175] opened 2024-12-12 16:14 UTC
### Use case

I want to build iOS apps, in addition to Android apps and web apps, on my Linux CI/CD server. Currently, all our iOS apps are built manually from an experienced iOS developer in our team, causing a delay in rolling out iOS updates compared to Android.

### Proposal

I would like a subcommand called `ios` be available in `flutter build`, i.e. we should be able to build an iOS app using `flutter build ios`, which can then be signed and published to the App Store, using a Linux machine.

**Comment by stuartmorgan** [comment] 2024-12-12 16:43
Closing as a duplicate of https://github.com/flutter/flutter/issues/22771

> we should be able to build an iOS app using `flutter build ios`, which can then be signed and published to the App Store, using a Linux machine.

iOS apps are built and signed using Xcode, so feedback about what platforms should be supported for that process would best be directed to Apple.

**Closed by stuartmorgan** 2024-12-12 16:43 UTC
