### ISSUE TITLE
`Mac_ios microbenchmarks_impeller_ios` failed on a codesigning error `errSecInternalComponent`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#110637] opened 2022-08-31 01:25 UTC
On `flutter-devicelab-mac-24`
```
[microbenchmarks_impeller_ios] [STDOUT] [STDOUT]                [   +7 ms] Target profile_unpack_ios failed: Exception: Failed to codesign /opt/s/w/ir/x/w/recipe_cleanup/tmpnfdabkco/flutter sdk/dev/benchmarks/microbenchmarks/build/ios/Profile-iphoneos/Flutter.framework/Flutter with identity AB7DFDD84BF4B572AA92CD5698B8C7648A810ECD.
[microbenchmarks_impeller_ios] [STDOUT] [STDOUT]                           /opt/s/w/ir/x/w/recipe_cleanup/tmpnfdabkco/flutter sdk/dev/benchmarks/microbenchmarks/build/ios/Profile-iphoneos/Flutter.framework/Flutter: errSecInternalComponent
[microbenchmarks_impeller_ios] [STDOUT] [STDOUT] 
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804363136466373841/+/u/run_microbenchmarks_impeller_ios/test_stdout

See similar https://github.com/flutter/flutter/issues/99490

**Comment by XilaiZhang** [comment] 2022-09-06 17:50
umm this looks like a unlock keychain issue, so I sshed into the machine and unlocked the keychain. if this doesn't fix the problem I am not sure which codesign script we are using for impeller ios, @christopherfujino would for sure know more

**Comment by christopherfujino** [comment] 2022-09-06 17:57
> umm this looks like a unlock keychain issue, so I sshed into the machine and unlocked the keychain. if this doesn't fix the problem I am not sure which codesign script we are using for impeller ios, @christopherfujino would for sure know more

I'm not sure if signed ios apps requires an unlocked keychain, but if so, then I think we need to make a SALT configuration update to do this globally; having @XilaiZhang ssh in to each bot and run a command manually will not scale well :)

**Comment by yusuf-goog** [comment] 2022-09-06 18:42
To determine:

* Is this happening on all machines?
* Are any other tests hitting this issue?

**Comment by yusuf-goog** [comment] 2022-09-06 19:39
@keyonghan had made a previous salt change to increase the relock timeout of the keychain. 

This was required if the tests took longer than 5 minutes (the original timeout). Once we figure out the if this is happening on all machines, and/or other tests, we should be able to figure out a way forward.

**Comment by keyonghan** [comment] 2022-09-08 22:27
After moved to staging, we hit 1 out of recent 100 builds, and the bot hit the failure is passing tests consistently. Lowering to P3.

**Comment by keyonghan** [comment] 2022-09-20 16:45
The issue is not repro in recent 200 builds. Moving to technical debt for further monitoring as this is not actionable now from ticket queue side.

**Comment by keyonghan** [comment] 2023-08-03 18:24
Not repro anymore. Please reopen if you see it again.

**Closed by keyonghan** 2023-08-03 18:24 UTC
Labels: team-infra, P1
