### ISSUE TITLE
The font rendered by canvaskit is a bit blurry, and I feel a bit dizzy after watching it for a lo

### ISSUE THREAD

**Issue by xyun52** [flutter/flutter#142434] opened 2024-01-29 09:19 UTC
### Steps to reproduce

create any app

### Expected results

![wind](https://github.com/flutter/flutter/assets/5417624/61f54fca-bd4c-49c0-9573-b06d244ff65c)

### Actual results

![web](https://github.com/flutter/flutter/assets/5417624/564b7f08-0126-4287-b9b0-60817481baf7)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [版本 10.0.22631.3085], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.85.2)

**Comment by dam-ease** [comment] 2024-01-29 12:13
Thanks for filing this @xyun52.

> Need to be on a low DPI computer

Can you please help with the device information?
Also, is this specific to only `canvaskit`? Can you test with the `html` renderer as well?

**Comment by xyun52** [comment] 2024-01-30 00:36
Samsung 24 inch 1080P monitor

![微信图片_20240130083334](https://github.com/flutter/flutter/assets/5417624/3ccd6252-95f2-418e-9416-1d67fd1054d9)

**Comment by dam-ease** [comment] 2024-01-30 06:43
Thanks for your response @xyun52.
Can you please confirm if this is specific to only `canvaskit`? Can you test with the `html` renderer as well?
Also, are you running on a Chromium-based browser?
I can see similar issues to yours:
https://github.com/flutter/flutter/issues/32274
https://github.com/flutter/flutter/issues/74986
Can you check them out as well if they are similar/related to the behaviour you are experiencing?

**Comment by xyun52** [comment] 2024-01-31 00:54
The client's computer is already not good, and if using HTML rendering, the performance will be even worse

**Comment by kevmoo** [comment] 2024-02-01 19:25
This has been fixed in beta/master. Will be in the next (new) stable release.

**Closed by kevmoo** 2024-02-01 19:25 UTC
Labels: e: device-specific, a: typography, platform-web, e: web_canvaskit, team-web

**Comment by eyebrowsoffire** [comment] 2024-02-01 19:29
Duplicate of https://github.com/flutter/flutter/issues/122541
