### ISSUE TITLE
Flutter Dev tools not Opening OR Working 

### ISSUE THREAD

**Issue by RR-Reddy** [flutter/flutter#83323] opened 2021-05-25 06:05 UTC
## Steps to Reproduce
1. Create new Flutter project ( counter app)
2. Hit run button in android studio
3. Click devtools button 

here is video for above steps :
[Video](https://drive.google.com/file/d/1kwNaXqMyo-ebVvZBbu6xZCvHAa50aBI8/view?usp=sharing)

**Expected results:**  Devtools should be opened in browser

**Actual results:** Devtools not opening at all

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 2.2.0 at /Users/rr-reddy/Documents/soft/flutter_soft/flutter
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rr-reddy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Redmi 8A (mobile) • 62b13eb90906 • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 90.0.4430.212

```

**Comment by TahaTesser** [comment] 2021-05-25 13:10
Hi @RR-Reddy 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-25 13:10 UTC
Labels: in triage

**Comment by RR-Reddy** [comment] 2021-05-26 03:32
Hi @TahaTesser  
Thanks for the information.
Dev tools are working  fine After updating Android studio flutter plugin.
