### ISSUE TITLE
The method 'forward' isn't defined for the type 'Animation'.

### ISSUE THREAD

**Issue by ravimandal06** [flutter/flutter#114331] opened 2022-10-31 05:56 UTC
when am implementing the animation widget and to start the animation i used-
animationController.forward(); after declaring the animationContoller in initState ,

This throws an error which is :   
-->
The method 'forward' isn't defined for the type 'Animation'.
Try correcting the name to the name of an existing method, or defining a method named 'forward'.dart[undefined_method](https://dart.dev/diagnostics/undefined_method)

**Comment by huycozy** [comment] 2022-10-31 11:50
@ravimandal06 Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by ravimandal06** [comment] 2022-11-04 04:45
Hello @huycozy sir,

I used the Animation flutter package version ^2.0.7 

Here is the code, Main.dart

`import 'package:flutter/material.dart';
import 'package:animations/animations.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late final Animation animation;
  late final Animation<double> animationController;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    animationController =
        AnimationController(duration: const Duration(seconds: 2), vsync: this)
          ..repeat();

    animation = Tween(begin: -1.0, end: 0.0).animate(CurvedAnimation(
        parent: animationController, curve: Curves.fastOutSlowIn));

     animationController.forward;
  }

  @override
  Widget build(BuildContext context) {
    final double width = MediaQuery.of(context).size.width;
    return AnimatedBuilder(
      animation: animationController,
      builder: (BuildContext context, Widget? child) {
        return Scaffold(
          body: Transform(
            transform:
                Matrix4.translationValues(animation.value * width, 0.0, 0.0),
            child: Center(
              child: Container(
                  child: const Text(
                'login',
                style: TextStyle(fontSize: 30.0, color: Colors.amber),
              )),
            ),
          ),
        );
      },
    );
  }
}
`

**Comment by darshankawar** [comment] 2022-11-04 05:27
@ravimandal06 
Looking at the code you provided, in order to use `forward()` method for `animationController` class, you will need to declare it as below:

`late final AnimationController animationController;`

instead of `late final Animation<double> animationController;`

Also, you don't need to use `animations` library, since the `animation` class provided out of box by the framework serves the purpose. Below is complete code sample.

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late final Animation animation;
  late final AnimationController animationController;

  @override
  void initState() {
// TODO: implement initState
    super.initState();
    animationController =
        AnimationController(duration: const Duration(seconds: 2), vsync: this)
          ..repeat();

    animation = Tween(begin: -1.0, end: 0.0).animate(CurvedAnimation(
        parent: animationController, curve: Curves.fastOutSlowIn));

    animationController.forward();
  }

  @override
  Widget build(BuildContext context) {
    final double width = MediaQuery.of(context).size.width;
    return AnimatedBuilder(
      animation: animationController,
      builder: (BuildContext context, Widget? child) {
        return Scaffold(
          body: Transform(
            transform:
                Matrix4.translationValues(animation.value * width, 0.0, 0.0),
            child: Center(
              child: Container(
                  child: const Text(
                'login',
                style: TextStyle(fontSize: 30.0, color: Colors.amber),
              )),
            ),
          ),
        );
      },
    );
  }
}

```

Closing as this is not an issue.

**Closed by darshankawar** 2022-11-04 05:27 UTC
Labels: in triage
