### ISSUE TITLE
SliverGridDelegateWithFixedCrossAxisCount fails creating children tiles sizes with unlucky aspect ratios

### ISSUE THREAD

**Issue by docet85** [flutter/flutter#11079] opened 2017-07-04 15:35 UTC
I got an unexpected exceptions "Explosion" when switching my android virtual device from 4.7 WXGA to Nexus 6 (nothing fancy, just default configs). The screen causing the crash had a Gridview widget with `gridDelegate SliverGridDelegateWithFixedCrossAxisCount`, built with the `.builder()` constructor, since I am building a calendar with markers inside and it comes more handy to have a function creating the children. 

From what I understood from the Exception Stacktrace it looks like a numeric issue when computing the children sizes:  440.8163265306122 is very, very, very close to 440.81632653061223, but yet bigger. 

```
I/flutter ( 5159): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5159): The following assertion was thrown during performLayout():
I/flutter ( 5159): SliverGeometry is not valid: The "maxPaintExtent" is less than the "paintExtent".
I/flutter ( 5159): The maxPaintExtent is 440.8163265306122, but the paintExtent is 440.81632653061223. Maybe you have
I/flutter ( 5159): fallen prey to floating point rounding errors, and should explicitly apply the min() or max()
I/flutter ( 5159): functions, or the clamp() method, to the paintExtent? By definition, a sliver can't paint more than
I/flutter ( 5159): the maximum that it can paint!
I/flutter ( 5159): The RenderSliver that returned the offending geometry was:
I/flutter ( 5159):   RenderSliverGrid#c2075 relayoutBoundary=up20 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5159):   creator: SliverGrid ← ShrinkWrappingViewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#45e4e]
I/flutter ( 5159):   ← Listener ← _GestureSemantics ←
I/flutter ( 5159):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#7ff23] ← RepaintBoundary ←
I/flutter ( 5159):   CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification> ←
I/flutter ( 5159):   GlowingOverscrollIndicator ← ⋯
I/flutter ( 5159):   parentData: layoutOffset=0.0 (can use size)
I/flutter ( 5159):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter ( 5159):   scrollOffset: 0.0, remainingPaintExtent: Infinity, crossAxisExtent: 411.4, viewportMainAxisExtent:
I/flutter ( 5159):   Infinity)
I/flutter ( 5159):   geometry: SliverGeometry(scrollExtent: 440.8, paintExtent: 440.8, maxPaintExtent: 440.8,
I/flutter ( 5159):   hasVisualOverflow: true, )
I/flutter ( 5159):   currently live children: 0 to 41
```

the code experiencing the bug looks like::
```dart
Widget build(BuildContext context) {
    return new Scaffold(
      body: new Scrollbar(
        child: new ListView(
          controller: _scrollController,
          shrinkWrap: true,
          children: <Widget>[
             ***
            new GridView.builder(
              shrinkWrap: true,
              controller: _scrollController,
              itemCount: countDays(firstDay),
              gridDelegate: new SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 7,
                childAspectRatio: 4 / 5,
              ),
              itemBuilder: calendarTileBuilder,
            ),

```

While changing childAspectRatio to 4.1/5 does not reproduce the bug.

**Comment by long1eu** [comment] 2018-01-24 11:34
any update on this?

**Comment by p30arena** [comment] 2019-04-13 07:52
I get this even if the AspectRatio is 1

**Comment by chunhtai** [comment] 2019-04-19 21:19
This is a duplicate of https://github.com/flutter/flutter/issues/16125. Let's track the bug there.

**Closed by chunhtai** 2019-04-19 21:19 UTC
Labels: f: scrolling, framework, severe: crash
