### ISSUE TITLE
iOS input keyboard sometime stuck in flutter app

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#32584] opened 2019-05-12 14:11 UTC
newest flutter on macOS, only on iOS the keyboard sometimes stuck, **only in Chinese or Janpanese keyboard, English keyboard is ok**, but android just works fine

**Comment by daniilguit** [comment] 2019-05-13 08:07
Yup, this is known problem tracked by https://github.com/flutter/flutter/issues/31138.
It only happens when you use native widgets integration, disable it if you can (e.g. you are not using google maps and webview plugins). It was introduced in 1.3 version.

**Comment by Stephan-Enoro** [comment] 2019-05-13 08:49
Google maps and webview are central features in my app. I do have keyboard hang with swedish keyboard. When I removed textCapitalization it seems to improve. I really hope that it was the case.

**Comment by jinfagang** [comment] 2019-05-13 08:59
@daniilguit  Exactly happend after I add an webview plugin (widget). Which is what I need to open a webpage in a scafffold. I need it so. Does there any way to make them coexistence? Or waiting flutter team fix on it?

**Comment by daniilguit** [comment] 2019-05-13 10:21
@jinfagang: If you can't open webview in separate in separate view (like url_launcher does) you'll have to wait for a fix from devs and therer is not esteimation yet :(, this bothers me alot also. 
Actually, there is big issue with webview (and all native widgets) on Android that it can not open keyboard by itself (i.e. user tapped text field on web form) on Android (on iOS keyboard does work) and fixing this is scheduled to October 😢 , so if you need your user to type anything in web page, you will have to not use webview_plugin until that date also.

**Comment by daniilguit** [comment] 2019-05-13 10:24
@amirh : Maybe this issue should be marked as duplicate of https://github.com/flutter/flutter/issues/31138?

**Comment by Stephan-Enoro** [comment] 2019-05-13 10:33
It seems that we have a set of different type of lag/hang and should be sorted in different issues.
TextField hang was without any WebView and Google Map on the page. It seems to be connected to textCapitalization. I hope hang issues will be address long before October.

**Comment by daniilguit** [comment] 2019-05-13 10:44
@Stephan-Enoro : this bug happens not when you have them on the page, but when you enabled native widgets integration overall (this changes some internal behaviour of the Flutter Engine regardless of whethe you really use those native widgets).

**Comment by Stephan-Enoro** [comment] 2019-05-13 10:47
Aha. I understand

**Comment by jinfagang** [comment] 2019-05-13 10:51
@daniilguit  It's like to the end of the world waiting for a fix. But really curious about why English keyboard only works fine and Android does not have this issue? Seems only related with the keyboard

**Comment by daniilguit** [comment] 2019-05-13 11:12
@jinfagang : I have this issue with both English and numeric keyboard. I'm not a Flutter developer so no clues here :) There is mention that it can be related to different threading usage when embedded views enabled and embedded views are very platform dependant by it's nature :)

**Comment by jinfagang** [comment] 2019-05-13 12:12
To correction myself:**it all stuck not only on English.** Tested it just now.

**Comment by BondarenkoStas** [comment] 2019-10-12 12:33
Closing it as a duplicate of #31138. The temporary fix landed to 1.6.7. Please follow that and #37665.

**Closed by BondarenkoStas** 2019-10-12 12:33 UTC

**Comment by renanyoy** [comment] 2020-09-24 10:12
I have same problem in debug, some freeze sometimes on a CupertinoTextField on top of a GoogleMap.
But for our users in release, it also crash sometimes.
I have managed to reproduce it one time

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-FR)
    • Flutter version 1.20.4 at /Users/renanyoy/code/sdk/flutter
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Pixel 3a (mobile)    • 9BCAY1J68Q                • android-arm64 • Android 10 (API 29)
    • Renaniphone (mobile) • 00008020-000640992209002E • ios           • iOS 13.7

• No issues found!

the console log 
https://pastebin.com/fqBdzyDt

**Comment by renanyoy** [comment] 2020-09-24 10:19
it's in french keyboard
