### ISSUE TITLE
Would like "next" form behavior in Keyboard

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11344] opened 2017-07-21 19:20 UTC
Normally when filling out a form on iOS or Android the "done" key turns into a "next" key and you don't have to dismiss the keyboard between text fields.

If you try our "Text fields" demo in the flutter_gallery it does not have this expected "next" behavior.

I ran into this initially in Posse's app in the sign-up screen.

**Comment by eseidelGoogle** [comment] 2017-07-21 19:20
https://github.com/flutter/flutter/issues/9363 is a related (but different) bug in our text input which is also obvious when attempting to build a sign-up screen.

**Comment by eseidelGoogle** [comment] 2017-07-27 21:29
@cbracken Posse would like to try and work this support into the next release of their app.  When you get back, would be interested in learning how hard this will be to do.

**Comment by cbracken** [comment] 2017-08-03 23:24
Related #10372 on iOS.

**Comment by cbracken** [comment] 2017-08-03 23:50
In terms of the work here, the main issue is that we don't currently define a navigation order over widgets. Assuming some reasonable default, this shouldn't be more than a couple days' work for iOS and I assume similar on Android.

My guestimate at the work involved:
1. Determine the minimal default widget traversal order. We could use what we use for accessibility today, which is a traversal of the render tree.
1. Implement support for a user-defined return-key type. Currently we only support 'done'.
1. Implement the focus traversal behaviour when 'next' is pressed.
1. Enable the iOS nav back/forward input accessory view.
1. Enable the Android equivalent (I haven't looked into this, but assume one exists).
1. Additional: Improve the default widget traversal order -- ideally, I assume top-to-bottom, left-to-right (for LTR locales).
1. Additional: Support a user-defined traversal order.

**Comment by Hixie** [comment] 2017-08-04 00:27
@abarth who may have ideas for how to do focus traversal

**Comment by abarth** [comment] 2017-08-04 02:14
I'd build the traversal using `FocusNode` rather than the render tree.  Currently, you only need to register your FocusNode with the FocusScopeNode when you requestFocus [1], you we should add another way of registering the FocusNode for traversal.

If you want to get fancy, you could register with a BuildContext and then traversal could use your global coordinates to guess a default traversal order.

[1] https://docs.flutter.io/flutter/widgets/FocusScopeNode/requestFocus.html

**Comment by eseidelGoogle** [comment] 2017-08-14 17:45
Posse is interested in knowing if this is something reasonable to do in the next two weeks before their next release.

**Comment by collinjackson** [comment] 2017-08-24 22:39
@cbracken is working on this. we are hoping to have something minimal next week, though not including custom focus order.

**Comment by xster** [comment] 2017-12-13 00:49
Minor update: the challenge is that we have no semantics yet that defines ordering of form fields' traversal

**Comment by Hixie** [comment] 2017-12-13 00:57
This doesn't fit our current priority list, so I'm moving it to a later milestone.

**Comment by Hixie** [comment] 2018-01-03 00:07
For the record, we are not planning on working on this in the near future. Please let us know if that is a problem. Thanks.

**Comment by nailgilaziev** [comment] 2018-01-19 11:29
Input data from keyboard to UI is a most important function in a mobile device on production.
So, topics related to working with native keyboards and ways of interaction with it, I consider very high priority.

**Comment by sbilstein** [comment] 2018-03-06 07:03
I'm running into this issue with an app I am building. Is there a suggested workaround?

**Comment by QoLTech** [comment] 2018-03-19 18:54
This is a feature that I would like as well.

Is there any workaround?

**Comment by Koseng** [comment] 2018-03-25 13:43
Really needed.

**Comment by franciscojunior** [comment] 2018-04-02 02:19
+1. I'm also running into this issue. Is there any workaround?

**Comment by FrantisekGazo** [comment] 2018-04-14 07:55
This is a really needed feature.

**Comment by FrantisekGazo** [comment] 2018-04-14 08:08
There is a workaround via `FocusScope`.

```
var focusNode = new FocusNode();
var TextField(focusNode: focusNode);

FocusScope.of(context).requestFocus(focusNode);
```
you can manually call this from the `TextField#onSubmit`.

But it would be great if this could be done automatically.

**Comment by wengelef** [comment] 2018-04-22 13:04
@FrantisekGazo 
nice, also works with `TextFormField#onFieldSubmitted`

**Comment by escamoteur** [comment] 2018-05-03 09:34
The current way to do this is especially problematic if you generate your TextFormFields dynamically.
My Proposal would be to let you assign an index to each TextFormField that will be used to determine the sequence within one Form.

**Comment by Hixie** [comment] 2018-06-20 21:19
@matthew-carroll assigned this to you based on our conversation yesterday

**Comment by sir-boformer** [comment] 2018-06-20 21:41
I would also like to see this feature. Not necessarily a fully automated solution. 

Combined with @FrantisekGazo's solution, all that would be needed is a way to [change the "action button" of the keyboard in iOS and Android to "Next"/"Go"/"Send"/...](https://github.com/flutter/flutter/issues/17525#issuecomment-397234102)

**Comment by escamoteur** [comment] 2018-06-21 06:57
@Hixie what is the proposed solution?

**Comment by matthew-carroll** [comment] 2018-06-21 19:53
@escamoteur I'll be working on this issue.  I'm currently assembling information about the support behaviors on Android and iOS regarding input focus navigation and IME options.  The keyboard actions are closely tied to those input details and I want to make sure we get the whole picture right for input.

If you'd like to chat about any specific, related issue, please let me know.  Otherwise, I'll try to update this ticket as I make progress with the investigation and API decisions.

**Comment by escamoteur** [comment] 2018-06-21 20:53
Hi @matthew-carroll thanks for your reply would love to stay updated.

**Comment by matthew-carroll** [comment] 2018-06-26 22:43
@escamoteur I have an engine PR and framework PR to add support for all keyboard action types.  This is the first step towards form focus navigation:

Engine:
https://github.com/flutter/engine/pull/5620

Framework:
https://github.com/flutter/flutter/pull/18855

API thoughts are welcome.

Even with this one change, manual focus navigation should be possible.  But of course I want to reach a systematic solution for that.

**Comment by escamoteur** [comment] 2018-06-27 07:47
@matthew-carroll I just reviewed it. looks great absolutely necessary for the next step and good to expose this separately. I really like the onSubmit handler because often you don't want to react to every key stroke.

Just curious why need you the conversion of string to textInputAction ? Also I would implement that with a static map, not a switch statement.

**Comment by matthew-carroll** [comment] 2018-06-27 22:15
I think I just extended what was already there with regard to the switch and string conversion.  However, we certainly don't want to pass strings around because that opens the door to typos and other hard-to-find mistakes.  So we definitely want an enum, I think.  If at some point there is an unbounded set of possible actions then we'd probably want to kill the enum, but for Android and iOS we definitely have small, bounded sets.

**Comment by adriancmurray** [comment] 2018-07-01 19:32
Glad I saw this, I was about to build my own solution to this problem. Looking forward to it being implemented. Thanks for all the work you're doing.

**Comment by estavex** [comment] 2018-07-22 23:40
Is this feature gonna be implemented soon? It's been over a year since this thread was posted

**Comment by jogboms** [comment] 2018-07-23 01:34
@estavex follow the thread, the complete milestone is only a few more commits away. For now, you can utilize a combination of `focusNode`, `textInputAction` and `onEditingComplete` on the `TextField`s to get the desired effect before this lands.

**Comment by escamoteur** [comment] 2018-07-23 06:32
@matthew-carroll how will it be implemented as API?

**Comment by slightfoot** [comment] 2018-07-23 15:53
@escamoteur It's already implemented in master.
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_field.dart#L105
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/text_input.dart#L240

**Comment by matthew-carroll** [comment] 2018-07-23 19:48
@estavex @escamoteur - As @slightfoot mentioned, the ability to change the action button on the keyboard is implemented.

Automatic focus change is a much larger and more intricate issue.  I'm not sure when that work will be completed.  It requires implementing a focus navigation tree that operates as a subset of the semantic accessibility tree.  In the meantime, as @jogboms pointed out, you can manually switch focus either in `onEditingComplete` or `onSubmitted`, depending on your use-case.

**Comment by Hixie** [comment] 2018-07-24 23:20
Current status is that this can be implemented manually in apps that want it. We intend to make this automatic eventually but do not currently have a plan for how to do that.

**Comment by escamoteur** [comment] 2018-07-31 08:38
Perhaps I'm just naive, but as far as I understand it all FormFields register at there surrounding Form or not? Why not allow any FormField to have an index value that defines the sequence of the focus like we did in good old MS mfc? Then onNext could just ask the surounding Form where to move the focus.

@timsneath I think this is an absolute critical feature before 1.0 for all business like Apps that have a lot of Form entries.

**Comment by matthew-carroll** [comment] 2018-07-31 20:36
We shouldn't solve focus for forms and nothing else.  Focus is a general UI behavior that needs to work in general.  All focusable widgets need to participate in focus navigation.  Moreover, that focus navigation needs to default to the same traversal as the semantics tree (but then can be customized by the developer).  And beyond that, the situation isn't as simple as next/previous.  There is also up/down/left/right which is necessary for d-pad devices.

I think creating an API just for forms and just for 1.0 is a mistake.

As has been mentioned, focus navigation can be implemented manually.  It might be a little more work for right now, but there is nothing preventing any form focus order traversal that you'd like.  You just need to utilize FocusNodes.

I think we need to treat this like any other yak shave and really dig to the core of the focus navigation issue and solve it in general.

CC @timsneath @Hixie @goderbauer

**Comment by matthew-carroll** [comment] 2018-07-31 20:49
Also, another thought, @escamoteur @slightfoot, you could throw together a community library that wraps form fields with this extended API.  If all you need is the index control you mentioned then I'm guessing it's not a lot of work.  Then that community library can hold people over until the framework catches up.  When the framework reaches general focus navigation, you can deprecate that library.  But we shouldn't do this with the framework because we'll never be able to get rid of the exposed API.

**Comment by Hixie** [comment] 2018-07-31 21:10
not every form field is registered with the form (e.g. if it's in a ListView but currently off screen,)

**Comment by Hixie** [comment] 2018-10-02 23:09
This is on our near-term radar.

**Comment by diegoveloper** [comment] 2018-12-06 22:47
While this is in development I created a new package that could be help some users that need move between textfields or add 'done' button for iOS number keyboard. 

![keyboard_actions](https://user-images.githubusercontent.com/4898256/49616438-d0dadd00-f97e-11e8-8cdd-915f0e97bc4e.gif)

https://pub.dartlang.org/packages/keyboard_actions

**Comment by escamoteur** [comment] 2018-12-07 09:09
@diegoveloper looks awesome! Does it also work with TextFormFields?

**Comment by diegoveloper** [comment] 2018-12-07 13:33
It should, because textformfield also receives focusNode.

**Comment by VictorCamargo** [comment] 2019-01-23 00:44
> It should, because textformfield also receives focusNode.

Awesome package, but unfortunately it didn't work on my app.. When I click on close button it only close the actionbar itself and don't dismiss the keyboard.

**Comment by diegoveloper** [comment] 2019-01-23 00:52
Could you add a minimum sample code to reproduce the issue?

**Comment by GeertJohan** [comment] 2019-02-11 11:55
@Hixie Its very useful if the implementation of this feature in Flutter allows the google/flutter-desktop-embedding project to implement "tabs" from a keyboard as well.
Please see google/flutter-desktop-embedding#94

**Comment by Hixie** [comment] 2019-02-11 16:58
@GeertJohan Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

**Comment by stuartmorgan** [comment] 2019-02-11 17:14
@GeertJohan Wiring up the tab key itself would be trivial, it's the automatic traversal chain that's the hard part; there's no way this could be solved that _wouldn't_ address the desktop need.

**Comment by gspencergoog** [comment] 2019-05-28 17:15
This issue is blocked by needing the shortcut key map implementation (issue #13264), and by adding a connection for a soft keyboard "next" button (when used in place of the Done button) to be wired to call nextFocus on the currently focused widget.

**Comment by gspencergoog** [comment] 2019-07-10 15:02
OK, the shortcut key map implementation is in, so this is just blocked now by not having the connection between the soft keyboard "next" button being pressed and the `nextFocus` call.

**Closed** 2019-07-11 14:56 UTC
Labels: a: desktop, a: text input, customer: posse (eap), f: material design, framework, severe: customer critical, severe: new feature

**Comment by escamoteur** [comment] 2019-09-13 12:28
Peeps, that is so awesome but why does nobody knows about this? OK its pretty new :-)
