### ISSUE TITLE
flutter vscode devcontainer hot-restart issue

### ISSUE THREAD

**Issue by knightswatch3** [flutter/flutter#111683] opened 2022-09-15 18:30 UTC
I have been trying to perform a hot-reload for my flutter-web [project](https://github.com/knightswatch3/flutter-setup).

Been struggling to get hot restart functionality enabled when running via viscose dev-containers. I tried:

Having the flutter run -d at the entry point.
Executing the debug via the vs-code debugger.
Neither of them solves the hot-restart issue on the browser on which the initial page is rendered after building from the inside container. Please help how to achieve what I am trying. TIA.

**Comment by huycozy** [comment] 2022-09-16 09:13
Hi @knightswatch3, thanks for filing the issue.
To determine the cause of the issue belongs to VSCode or Flutter, please provide the information indicated below:
- The detailed reproduction steps
- The output of `flutter doctor -v`
- VSCode version
- Error logs from the console if any 

Thank you!

**Comment by knightswatch3** [comment] 2022-09-21 22:28
@huycozy Here is the requested information:

```
[root@5cd7c82ba1de flutter-setup]# flutter --version

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Flutter 3.4.0-19.0.pre.296 • channel master •
https://github.com/flutter/flutter.git
Framework • revision bf5d608788 (6 days ago) • 2022-09-15 20:59:35 -0400
Engine • revision d12fe86ba2
Tools • Dart 2.19.0 (build 2.19.0-204.0.dev) • DevTools 2.17.0
[root@5cd7c82ba1de flutter-setup]# flutter doctor -v
[✓] Flutter (Channel master, 3.4.0-19.0.pre.296, on CentOS Linux 8
    5.10.124-linuxkit, locale en_US.UTF-8)
    • Flutter version 3.4.0-19.0.pre.296 on channel master at /flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bf5d608788 (6 days ago), 2022-09-15 20:59:35 -0400
    • Engine revision d12fe86ba2
    • Dart version 2.19.0 (build 2.19.0-204.0.dev)
    • DevTools version 2.17.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/firefox

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1 (Red Hat 12.0.1-4.module_el8.5.0+1025+93159d6c)
    • cmake version 3.20.2
    • ninja version 1.8.2
    • pkg-config version 1.4.2

[!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-arm64    • CentOS Linux 8
      5.10.124-linuxkit
    • Chrome (web)    • chrome • web-javascript • Running without a11y
      support!
      Mozilla Firefox 91.4.0esr

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.```

Here is my viscose version:

```
Version: 1.71.0 (Universal)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z (2 wks ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No```

**Comment by huycozy** [comment] 2022-09-22 05:18
Hi @knightswatch3, thanks for your response.
But I see there's an open issue addressing the case you described #89721 that proposes an official support Flutter Devcontainer for VSCode. Please also see https://github.com/microsoft/vscode-dev-containers/issues/162. That implies that it is not yet fully supported to handle other aspect issues.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2022-09-22 05:18 UTC
Labels: in triage
