### ISSUE TITLE
flutter packages get crashes if pubspec.yaml

### ISSUE THREAD

**Issue by pdivita** [flutter/flutter#32699] opened 2019-05-14 14:24 UTC
I've made a mistake (syntax error) when adding fonts:

   ```
fonts:
   - family: Pacifico
     fonts:
       -asset: font/pacifico.ttf
```

Note the dash in "-asset". It should be

   ```
fonts:
   - family: Pacifico
     fonts:
       - asset: font/pacifico.ttf
```

When I launch flutter packages get I, it crashes:

```
C:\dev\flutter\bin\flutter.bat --no-color packages get
Running "flutter packages get" in flutter_app...                    0,3s

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: b2e66ad01a10da6f)
Crash report written to C:\Users\p.divita\dev\altro\flutter\flutter_app\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1
```

## Steps to Reproduce

1. Copy and paste in pubspec.yaml
2. Create the fonts dir and place a ttf font named "pacifico.ttf"
3. Run flutter get

I guess the normal behaviour should be a syntax error reporting, instead of crash

## command

flutter --no-color packages get

## exception

_TypeError: type 'YamlMap' is not a subtype of type 'Iterable<dynamic>'

```
#0      _validateFonts (package:flutter_tools/src/flutter_manifest.dart:409:47)
#1      _validateFlutter (package:flutter_tools/src/flutter_manifest.dart:354:9)
#2      _validate (package:flutter_tools/src/flutter_manifest.dart:312:9)
<asynchronous suspension>
#3      FlutterManifest._createFromYaml (package:flutter_tools/src/flutter_manifest.dart:45:40)
<asynchronous suspension>
#4      FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:40:12)
<asynchronous suspension>
#5      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:34:12)
<asynchronous suspension>
#6      FlutterProject._readManifest (package:flutter_tools/src/project.dart:153:60)
<asynchronous suspension>
#7      FlutterProject.fromDirectory (package:flutter_tools/src/project.dart:44:44)
<asynchronous suspension>
#8      FlutterProject.fromPath (package:flutter_tools/src/project.dart:59:58)
#9      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:96:61)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#17     Future._complete (dart:async/future_impl.dart:473:7)
#18     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#19     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Versione 10.0.17763.475], locale it-IT)
    • Flutter version 1.5.4-hotfix.2 at C:\dev\flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\dev\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by jason-simmons** [comment] 2019-06-06 22:21
Duplicate of https://github.com/flutter/flutter/issues/31764

**Closed by jason-simmons** 2019-06-06 22:21 UTC
