### ISSUE TITLE
Compiler crashes on test

### ISSUE THREAD

**Issue by omontoya** [flutter/flutter#42150] opened 2019-10-07 20:46 UTC
```
00:03 +0: loading /Users/omontoya/omtreksoft/flutter_stores/test/main_test.dart                                                                                       Unhandled exception:
Crash when compiling file:///Users/omontoya/omtreksoft/flutter_stores/lib/web/image_picker.dart,
at character offset 590:
RangeError (offset): Invalid value: Not in range 0..2268, inclusive: 7359
#0      RangeError.checkValueInInterval (dart:core/errors.dart:281:7)
#1      Source.getLocation (package:kernel/ast.dart:6782:16)
#2      getLocation (package:front_end/src/fasta/messages.dart:16:52)
#3      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:201:47)
#4      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:224:29)
#5      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:70:13)
#6      Loader.addMessage (package:front_end/src/fasta/loader.dart:334:20)
#7      Loader.addProblem (package:front_end/src/fasta/loader.dart:285:12)
#8      LibraryBuilder.addProblem (package:front_end/src/fasta/builder/library_builder.dart:137:19)
#9      SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1208:47)
#10     BodyBuilder.addProblem (package:front_end/src/fasta/kernel/body_builder.dart:5238:20)
#11     BodyBuilder.addProblemErrorIfConst (package:front_end/src/fasta/kernel/body_builder.dart:5252:5)
#12     BodyBuilder.buildAbstractClassInstantiationError (package:front_end/src/fasta/kernel/body_builder.dart:4898:5)
#13     BodyBuilder.resolveRedirectingFactoryTargets (package:front_end/src/fasta/kernel/body_builder.dart:1021:13)
#14     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:935:5)
#15     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:864:14)
#16     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:897:7)
#17     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:627:5)
#18     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3438:20)
#19     Parser.parseClassOrMixinOrExtensionMemberImpl (package:front_end/src/fasta/parser/parser.dart:3206:15)
#20     Parser.parseClassOrMixinOrExtensionBody (package:front_end/src/fasta/parser/parser.dart:2941:15)
#21     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1802:13)
#22     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1761:14)
#23     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#24     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#25     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#26     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:299:14)
<asynchronous suspension>
#27     Loader.buildBodies (package:front_end/src/fasta/loader.dart:241:15)
<asynchronous suspension>
#28     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:305:20)
<asynchronous suspension>
#29     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#30     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:303:12)
<asynchronous suspension>
#31     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:344:28)
<asynchronous suspension>
#32     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#33     new Future.sync (dart:async/future.dart:224:31)
#34     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#40     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:139:20)
<asynchronous suspension>
#41     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:50:44)
<asynchronous suspension>
#42     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:374:60)
<asynchronous suspension>
#43     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#44     _rootRun (dart:async/zone.dart:1120:38)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#47     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#51     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#52     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#53     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:902:7)
#1      DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:627:5)
#2      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3438:20)
#3      Parser.parseClassOrMixinOrExtensionMemberImpl (package:front_end/src/fasta/parser/parser.dart:3206:15)
#4      Parser.parseClassOrMixinOrExtensionBody (package:front_end/src/fasta/parser/parser.dart:2941:15)
#5      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1802:13)
#6      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1761:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#8      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#9      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:299:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:241:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:305:20)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:303:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:344:28)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:139:20)
<asynchronous suspension>
#25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:50:44)
<asynchronous suspension>
#26     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:374:60)
<asynchronous suspension>
#27     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#28     _rootRun (dart:async/zone.dart:1120:38)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
00:03 +0 -1: loading /Users/omontoya/omtreksoft/flutter_stores/test/main_test.dart [E]                                                                                
  Exception: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 28:3               throwToolExit
  package:flutter_tools/src/compile.dart 605:13                 ResidentCompiler._compile.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/stream_impl.dart 389:13                            _BufferingStreamSubscription._sendDone.sendDone
  dart:async/stream_impl.dart 399:15                            _BufferingStreamSubscription._sendDone
  dart:async/stream_impl.dart 283:7                             _BufferingStreamSubscription._close
  dart:async/stream_transformers.dart 96:11                     _SinkTransformerStreamSubscription._close
  dart:async/stream_transformers.dart 23:11                     _EventSinkWrapper.close
  dart:convert/string_conversion.dart 249:11                    _StringAdapterSink.close
  dart:convert/line_splitter.dart 134:11                        _LineSplitterSink.close
  dart:async/stream_transformers.dart 141:24                    _SinkTransformerStreamSubscription._handleDone
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/stream_impl.dart 389:13                            _BufferingStreamSubscription._sendDone.sendDone
  dart:async/stream_impl.dart 399:15                            _BufferingStreamSubscription._sendDone
  dart:async/stream_impl.dart 283:7                             _BufferingStreamSubscription._close
  dart:async/stream_transformers.dart 96:11                     _SinkTransformerStreamSubscription._close
  dart:async/stream_transformers.dart 23:11                     _EventSinkWrapper.close
  dart:convert/string_conversion.dart 249:11                    _StringAdapterSink.close
  dart:convert/string_conversion.dart 300:20                    _Utf8ConversionSink.close
  dart:convert/chunked_conversion.dart 80:18                    _ConverterStreamEventSink.close
  dart:async/stream_transformers.dart 141:24                    _SinkTransformerStreamSubscription._handleDone
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/stream_impl.dart 389:13                            _BufferingStreamSubscription._sendDone.sendDone
  dart:async/stream_impl.dart 399:15                            _BufferingStreamSubscription._sendDone
  dart:async/stream_impl.dart 283:7                             _BufferingStreamSubscription._close
  dart:async/stream_controller.dart 772:19                      _SyncStreamControllerDispatch._sendDone
  dart:async/stream_controller.dart 629:7                       _StreamController._closeUnchecked
  dart:async/stream_controller.dart 622:5                       _StreamController.close
  dart:io-patch/socket_patch.dart 1836:21                       _Socket._onData
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1136:13                                  _rootRunUnary
  dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
  dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 764:19                      _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 640:7                       _StreamController._add
  dart:async/stream_controller.dart 586:5                       _StreamController.add
  dart:io-patch/socket_patch.dart 1384:35                       new _RawSocket.<fn>
  dart:io-patch/socket_patch.dart 890:18                        _NativeSocket.issueReadEvent.issue
  dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 116:13                  _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 173:5                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/stream_impl.dart 157:21                            _BufferingStreamSubscription.onDone
  dart:async/stream_impl.dart 114:10                            new _BufferingStreamSubscription
  dart:async/stream_transformers.dart 45:9                      new _SinkTransformerStreamSubscription
  dart:async/stream_transformers.dart 185:13                    _BoundSinkStream.listen
  package:flutter_tools/src/compile.dart 598:8                  ResidentCompiler._compile
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/compile.dart                        ResidentCompiler._compile
  package:flutter_tools/src/compile.dart 508:14                 ResidentCompiler._recompile
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/stream_impl.dart 139:21                            _BufferingStreamSubscription.onData
  dart:async/stream_impl.dart 112:10                            new _BufferingStreamSubscription
  dart:async/stream_controller.dart 838:9                       new _ControllerSubscription
  dart:async/stream_controller.dart 670:51                      _StreamController._subscribe
  dart:async/stream_controller.dart 818:19                      _ControllerStream._createSubscription
  dart:async/stream_impl.dart 472:9                             _StreamImpl.listen
  package:flutter_tools/src/compile.dart 480:26                 ResidentCompiler.recompile
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/test/test_compiler.dart             TestCompiler._onCompilationRequest
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                  _rootRunUnary
  dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
  dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 591:14                            _DelayedData.perform
  dart:async/stream_impl.dart 707:11                            _StreamImplEvents.handleNext
  dart:async/stream_impl.dart 667:7                             _PendingEvents.schedule.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 391:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/stream_impl.dart 139:21                            _BufferingStreamSubscription.onData
  dart:async/stream_impl.dart 112:10                            new _BufferingStreamSubscription
  dart:async/stream_controller.dart 838:9                       new _ControllerSubscription
  dart:async/stream_controller.dart 670:51                      _StreamController._subscribe
  dart:async/stream_controller.dart 818:19                      _ControllerStream._createSubscription
  dart:async/stream_impl.dart 472:9                             _StreamImpl.listen
  package:flutter_tools/src/test/test_compiler.dart 53:31       new TestCompiler
  package:flutter_tools/src/test/flutter_platform.dart 453:22   FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart          FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 363:36   FlutterPlatform.loadChannel
  package:flutter_tools/src/test/flutter_platform.dart 316:46   FlutterPlatform.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:test_core/src/runner/loader.dart                      Loader.loadFile.<fn>
  package:test_core/src/runner/load_suite.dart 98:31            new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>
  
00:03 +0 -1: Some tests failed.   
```
```                                                                                                                                    
omontoya@~/omtreksoft/flutter_stores:flutter doctor
Downloading android-arm-profile/darwin-x64 tools...                 0.8s
Downloading android-arm-release/darwin-x64 tools...                 0.6s
Downloading android-arm64-profile/darwin-x64 tools...               0.5s
Downloading android-arm64-release/darwin-x64 tools...               0.6s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.5, on Mac OS X 10.14.6 18G95, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] VS Code
[✓] Connected device (2 available)

• No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-10-07 21:08
@omontoya The error says `RangeError (offset): Invalid value: Not in range 0..2268, inclusive: 7359`. Can you provide a code example that reproduces the error?

**Comment by omontoya** [comment] 2019-10-07 23:43
I have a simple test case that it used to run but now it blows on build. it blows building a piece of code that relies on :
import 'package:universal_html/prefer_universal/html.dart' as html; The application seems to run.

import 'package:dart_stores_ws/shelf.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_stores/main.dart';

void main() {
  testWidgets('Load ShoppingAppWidget', (WidgetTester tester) async {
    await tester.pumpWidget(ShoppingAppWidget());
    expect(find.text('Register'), findsOneWidget);
    await tester.tap(find.text('Register'));
    await tester.pump().then((f){
      expect(find.text(create_account,skipOffstage: false), findsOneWidget);
    });
  });
}

**Comment by omontoya** [comment] 2019-10-31 02:57
The test compile and runs if I comment "html.FileReader();"

Excerpt:

import 'package:universal_html/prefer_universal/html.dart' as html;
...
final reader = null;     //html.FileReader();

Of course, it is not a viable solution :)

**Comment by emiliodallatorre** [comment] 2020-01-02 16:39
> The test compile and runs if I comment "html.FileReader();"
> 
> Excerpt:
> 
> import 'package:universal_html/prefer_universal/html.dart' as html;
> ...
> final reader = null; //html.FileReader();
> 
> Of course, it is not a viable solution :)

This seems to be a common error when trying to interoperate with Flutter apps between web and mobile. I think it is due to a not correct implementation of `FileReader` in `universal_html` plugin... I'm also looking for a solution of this problem.

**Comment by timsneath** [comment] 2020-01-02 20:11
Closing this for now, since it's not a reproducible problem in Flutter itself. Please open in https://github.com/dart-browser/universal_html/issues and if it turns out to be an issue in Flutter, then of course open a fresh issue with a small repro case. Thank you!

**Closed by timsneath** 2020-01-02 20:11 UTC
Labels: a: tests

**Comment by VKBobyr** [comment] 2020-05-31 03:21
I recently experienced the same error. Found out it was caused by a dependency cycle in global variables.
