### ISSUE TITLE
Completer test failed when call completeError

### ISSUE THREAD

**Issue by yanshouwang** [flutter/flutter#73032] opened 2020-12-28 11:06 UTC
## Steps to Reproduce

1. create a dart package.
2. Update the test file as follows:
``` dart
test('#1 Can catch future error', () async {
      final completer = Completer();
      final future = completer.future;
      final caller = (data) {
        final error = Exception('ABC');
        completer.completeError(error);
      };
      caller('data');
      try {
        await future;
      } catch (e) {
        expect('$e', 'Exception: ABC');
      }
    });

    test('#2 Can catch future error', () async {
      final completer = Completer();
      final future = completer.future;
      final caller = (data) {
        final error = Exception('ABC');
        completer.completeError(error);
      };
      caller('data');
      final duration = Duration(milliseconds: 500);
      await Future.delayed(duration);
      try {
        await future;
      } catch (e) {
        expect('$e', 'Exception: ABC');
      }
    });
```
3. run dart test, the first test passed, but the second test failed unexpected.

**Expected results: All tests should passed.

**Actual results:** The second test failed.

I've created a repo [here](https://github.com/yanshouwang/issues/blob/master/test/issues_test.dart)

<details>
  <summary>Logs</summary>

```
Output for #2 Can catch future error
Exception: ABC
dart:async                   _Completer.completeError
test\issues_test.dart 26:17  main.<fn>.<fn>
test\issues_test.dart 28:11  main.<fn>
```

</details>

**Comment by pedromassangocode** [comment] 2020-12-28 11:22
Hi @yanshouwang 
From what I can see, the issue is related to Dart language rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-28 11:22 UTC

**Comment by graphicbeacon** [comment] 2020-12-28 16:13
@yanshouwang It may be down to your implementation. Try this instead:

```dart
test('#1 Can catch future error', () async {
    Future caller(data) {
      final completer = Completer();
      final error = Exception('ABC');
      completer.completeError(error);
      return completer.future;
    }

    try {
      await caller('data');
    } catch (e) {
      expect('$e', 'Exception: ABC');
    }
  });

  test('#2 Can catch future error', () async {
    Future caller(data) {
      final completer = Completer();
      final error = Exception('ABC');
      completer.completeError(error);
      return completer.future;
    }

    const duration = Duration(milliseconds: 500);
    await Future.delayed(duration);

    try {
      await caller('data');
    } catch (e) {
      expect('$e', 'Exception: ABC');
    }
  });
```
