### ISSUE TITLE
Emoji not displaying on Linux

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#52343] opened 2020-03-10 18:51 UTC
Here's a simple heart char code that is not working on linux but already works in another devices.
`Text('Made with ${String.fromCharCode(0x2665)} by Flutter')`
->
![Screenshot from 2020-03-10 22-14-26](https://user-images.githubusercontent.com/20153831/76348372-52a57d00-631d-11ea-9ee0-65efbf05e1f8.png)
Here's my flutter doctor output:
```
[✓] Flutter (Channel master, v1.15.19, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] Connected device (3 available)
```

**Comment by stuartmorgan** [comment] 2020-03-10 19:08
That's a font issue, not a problem with creating the string. What font are you using?

**Comment by aliyazdi75** [comment] 2020-03-10 19:11
I've tested with default `Roboto` font and also `GoogleFonts.montserrat`.

**Comment by stuartmorgan** [comment] 2020-03-10 19:20
Roboto definitely doesn't have emoji.

Closing as a duplicate of #30700, which I've reopened for emoji specifically. See https://github.com/flutter/flutter/issues/30700#issuecomment-541269268 for a solution in the meantime.

**Closed by stuartmorgan** 2020-03-10 19:20 UTC
Labels: a: desktop, 🐧 platform-linux

**Comment by aliyazdi75** [comment] 2020-03-10 19:44
I don't know what emojis does this font have but it works with material icons in linux, if you want to know here's a simple code:
```
String.fromCharCode(Icons.description.icon.codePoint)
```
