### ISSUE TITLE
Hot reload not working in VSCode

### ISSUE THREAD

**Issue by ffb255** [flutter/flutter#60872] opened 2020-07-05 19:59 UTC
After saving the changes in VSCode (event changing a simple text), Debug Console returns `Reloaded 1 of 495 libraries in 149ms.`  But nothing changes in the emulator and I should use Hot Restart instead (`Ctrl + Shift + F5`)
in contrast to VSCode, Android Studio seems to be ok and changes are visible after saving with Hot Reload

## Steps to Reproduce

1. Create a simple project in VSCode
2. Start the emulator with `Ctrl + F5`
3. Apply some changes
4. Press `Ctrl + S` or hot reload button from the panel

## Logs

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.628], locale en-US)
    • Flutter version 1.17.5 at F:\flutter
    • Framework revision 8af6b2f038 (5 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Amir\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_SDK_ROOT = C:\Users\Amir\AppData\Local\Android\Sdk
    • Java binary at: F:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at F:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

- VSCode version: **v1.46.1**
- Dart extension version: **v3.12.1**
- Flutter extension version: **v3.12.1**

**Comment by iapicca** [comment] 2020-07-06 06:27
Hi @ffb255 
Are you experiencing the issue only with VS Code or with Android Studio and Terminal as well?
Thank you

**Comment by ffb255** [comment] 2020-07-06 17:26
It's only in VSCode and Android Studio works fine.

**Comment by TahaTesser** [comment] 2020-07-07 07:51
Hi @ffb255 
Seems like you it's just VS Code issue for you

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-07 07:51 UTC
Labels: in triage

**Comment by serhatzengin** [comment] 2020-11-21 18:24
Hello,

Click file (on the left) and enable autosave :) it is work for me :)

**Comment by ARY1257** [comment] 2021-02-03 05:07
Thanks a lot ☺☺
