### ISSUE TITLE
[web debugging]: Hot restart doesn't work with Canvaskit

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#69989] opened 2020-11-06 23:00 UTC
**Steps to Reproduce**
Create a new Flutter project in IntelliJ (increment counter app)
Select Chrome device
run app using canvaskit flag through terminal flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true
change title of app to "Hello world"
Hot reload the app through terminal using "R"
Observe terminal spinning for a while, quit app by closing chrome window

After quitting, terminal shows: 
Performing hot restart...                                         146.3s
hotRestart: (-32000) Service connection disposed

Logs:
flutter --version
Flutter 1.24.0-8.0.pre.129 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 9edfa1225d (3 hours ago) • 2020-11-06 15:24:02 -0500
Engine • revision cf376142ed
Tools • Dart 2.12.0 (build 2.12.0-27.0.dev)

**Comment by pedromassangocode** [comment] 2020-11-09 11:45
Closing as duplicate of https://github.com/flutter/flutter/issues/69263.

**Closed by pedromassangocode** 2020-11-09 11:45 UTC
Labels: debugging_web, e: web_canvaskit
