### ISSUE TITLE
ConnectivityBroadcastReceiver.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by jesseframework** [flutter/flutter#60197] opened 2020-06-24 11:42 UTC
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+6\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2020-06-24 12:14
Hi @jesseframework  
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`. 
Thank you

**Comment by jesseframework** [comment] 2020-06-24 12:17
$ flutter doctor -v
[√] Flutter (Channel master, 1.20.0-1.0.pre.81, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.20.0-1.0.pre.81 at C:\src\flutter
    • Framework revision e0ed12c73a (8 days ago), 2020-06-16 16:53:04 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\jgray\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29728.190
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\jgray\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (5 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows             • Windows       • windows-x64    • Microsoft Windows [Version 10.0.18363.900]
    • Web Server          • web-server    • web-javascript • Flutter Tools
    • Chrome              • chrome        • web-javascript • Google Chrome 83.0.4103.106
    • Edge                • edge          • web-javascript • Microsoft Edge 83.0.478.54

• No issues found!

**Comment by TahaTesser** [comment] 2020-06-25 11:13
duplicate of https://github.com/flutter/flutter/issues/44580

**Closed by TahaTesser** 2020-06-25 11:13 UTC
Labels: in triage
