### ISSUE TITLE
"Request to Dart VM Service timed out: _flutter.listViews({})" during hot reload

### ISSUE THREAD

**Issue by iampawan** [flutter/flutter#17434] opened 2018-05-09 17:43 UTC
Flutter version - 0.4.3-pre.16  & Dart Code - 2.12.2
@DanTup TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({})

[flutter_run.txt](https://github.com/flutter/flutter/files/1988861/flutter_run.txt)
[observatory.txt](https://github.com/flutter/flutter/files/1988862/observatory.txt)

**Comment by DanTup** [comment] 2018-05-10 07:50
Does hot reload always work the first time, and then fail on subsequent attempts?

In these logs, the first one works (which said "Initializing hot reload") but the next one failed (and it instead said "Performing hot reload..."). I'm not sure if there's a difference in what's performed the first time versus others.

```
[5:34:17 PM]: ==> [{"id":"7","method":"app.restart","params":{"appId":"cd36a340-0ea8-4cd4-80f8-158e72380363","fullRestart":false,"pause":true}}]
[5:34:17 PM]: <== [{"event":"app.progress","params":{"appId":"cd36a340-0ea8-4cd4-80f8-158e72380363","id":"5","progressId":"hot.reload","message":"Initializing hot reload..."}}]
[5:34:18 PM]: <== [{"event":"app.progress","params":{"appId":"cd36a340-0ea8-4cd4-80f8-158e72380363","id":"5","progressId":"hot.reload","finished":true}}]
[5:34:18 PM]: <== Reloaded 3 of 395 libraries in 1,239ms.
[5:34:18 PM]: <== [{"id":"7","result":{"code":0,"message":"Reloaded 3 of 395 libraries"}}]
[5:34:24 PM]: ==> [{"id":"8","method":"app.restart","params":{"appId":"cd36a340-0ea8-4cd4-80f8-158e72380363","fullRestart":false,"pause":true}}]
[5:34:24 PM]: <== [{"event":"app.progress","params":{"appId":"cd36a340-0ea8-4cd4-80f8-158e72380363","id":"6","progressId":"hot.reload","message":"Performing hot reload..."}}]
[5:35:25 PM]: <== [{"event":"app.progress","params":{"appId":"cd36a340-0ea8-4cd4-80f8-158e72380363","id":"6","progressId":"hot.reload","finished":true}}]
[5:35:25 PM]: <== [{"id":"8","error":"TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({})"}]
```

**Comment by iampawan** [comment] 2018-05-10 08:34
yes, it never gave exception at first attempt . It always give exception
after subsequent attempts stating ' Performing hot reload'

**Comment by darioielardi** [comment] 2018-05-10 11:10
same issue here

**Comment by DanTup** [comment] 2018-05-10 15:10
Looking at the logs again; we never got a response to the resume request on the second hot reload.. The log ends here:

```text
[5:34:25 PM]: ==> {"id":"414","method":"resume","params":{"isolateId":"isolates/61399362"}}
```

**Comment by devoncarew** [comment] 2018-05-10 15:15
@aam @rmacnak-google, we've had issues in the past re: `_flutter.listViews({})` and the VM being paused. There's some code in flutter_tools to avoid listing views if it thinks the VM is paused. That code is likely a bit racy however. We may want to consider moving to maintaining the list of views on the flutter_tools side, and adding and removing from the list based on `flutter view added` / `flutter view removed` events from the target device.

**Comment by zoechi** [comment] 2018-05-10 15:58
I had this consistently for some weeks but seems to be working now in `dev` channel.

**Comment by DanTup** [comment] 2018-05-10 16:03
@zoechi Was that in IntelliJ? We were just discussing whether it might be a timing issue and Dart Code doing something differently to IntelliJ; but maybe it happens there too. Do you normally run with or without the debugger?

**Comment by zoechi** [comment] 2018-05-10 16:03
Yes IntelliJ

**Comment by DanTup** [comment] 2018-05-10 16:06
@devoncarew I diff'd the good/bad restarts from the log above and the requests are all in the same order (obviously there may be timing variances), though the bad one never got a response to the resume.

<img width="1604" alt="screen shot 2018-05-10 at 5 02 00 pm" src="https://user-images.githubusercontent.com/1078012/39880016-58ffae82-5474-11e8-9a35-1c03a3447dc5.png">

I'm not sure how much we can do to change the timing (short of putting little delays in places).

Currently it looks like we wait for `PausePostRequest`, then we send requests to remove and re-add all breakpoints, then once they're all done, we send the resume.

**Comment by devoncarew** [comment] 2018-05-10 20:30
> Currently it looks like we wait for PausePostRequest, then we send requests to remove and re-add all breakpoints, then once they're all done, we send the resume.

OK, this matches what we're doing in IntelliJ; thanks for investigating.

**Comment by joon610** [comment] 2018-05-11 00:49
same issue~~....

**Comment by iampawan** [comment] 2018-05-13 14:16
Any update on this issue @DanTup ?

**Comment by DanTup** [comment] 2018-05-14 06:29
I'm afraid this one is currently a little outside of my knowledge so is going to need some input from someone else. As a temporary workaround you could run from the terminal (though this means no debugger) or disable hot-reload-on-save and use `Ctrl`+`F5` for full restarts (they're still pretty fast, but obviously lose state/position in app).

**Comment by knopp** [comment] 2018-05-14 15:46
Could this maybe get higher priority? Given how much hype hot reload gets, the feature in current state (at least with VSCode) is unreliable and very frustrating to use. Even in simulator hot reload only works couple of times before getting stuck, and even worse, after killing it and full restart the loaded code is old (few iterations before).

**Comment by iampawan** [comment] 2018-05-15 05:07
Agreed with @knopp

**Comment by AppleEducate** [comment] 2018-05-15 13:44
This started happening to be with the latest flutter beta 3 and vscode on high Sierra. I can build test and run my app but after about 2-5 hot reloads the app completely freezes. It doesn't matter it it is a physical device on iOS or android or emulator for iOS either. I even turned off auto save in vscode and sometimes just after 1 hot reload the app completely freezes. 

```
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.3.2 at /Users/rodydavis/Android/flutter/flutter
    • Framework revision 44b7e7d3f4 (4 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/rodydavis/Library/Android/sdk
    • Android NDK at /Users/rodydavis/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (3 available)
    • Rody’s 📱     • 68cab38f1e7de5b8aece2a1ebb7ca9a5d4761e19 • ios • iOS 11.3.1
    • Dev-iPhone-6s • a75015aff2fbecb29dcc8e459b14cba86c08f7fe • ios • iOS 11.3.1
    •               • 90288c0d9ae73afb8a84663c0475d208744fc569 • ios • iOS

• No issues found!
```

**Comment by aam** [comment] 2018-05-15 14:16
Does this hanging happen only when you hot reload while code is paused at a breakpoint?

**Comment by knopp** [comment] 2018-05-15 14:18
> Does this hanging happen only when you hot reload while code is paused at a breakpoint?

For me this happens regardless of whether the code is paused at a breakpoint.

**Comment by aam** [comment] 2018-05-15 14:33
Thanks @knopp. I am able to reproduce hanging when paused at a breakpoint(and looking into that), but not when the app is running. @DanTup have you been able to reproduce this?

**Comment by zoechi** [comment] 2018-05-15 15:17
I thought it's working for me, but it just happens less frequently.

**Comment by knopp** [comment] 2018-05-15 15:32
@aam, have you tried letting the app run for a while before attempting to reload? Timing might be a factor. Also it only happens when reloading from VScode (with debugging active, although not paused), reloading from command line works without any issue.

**Comment by DanTup** [comment] 2018-05-15 15:54
I tried again, but can't repro using Android emulator (which is what's in the OP's log) on my MacBook.

> reloading from command line works without any issue

I guess this is because it doesn't pause after the reload. The problem seems to be that the VM is remaining paused and not responding to the `resume` command. I wonder whether it's possible to connect to the Observatory web app while it's in this state?

@iampawan In your flutter_run log, you'll notice a line like this:

> [5:33:55 PM]: <== [{"event":"app.debugPort","params":{"appId":"cd36a340-0ea8-4cd4-80f8-158e72380363","port":8112,"wsUri":"ws://127.0.0.1:8112/ws","baseUri":"file:///data/user/0/com.google.unitconverter/cache/unit_converterEIBERS/unit_converter/"}}]

The `wsUri` part has the IP address that Observatory is bound to. If you take the IP/port part of that and put it into your browser (so in this case, `http://127.0.0.1:8112/`, but it can have a different port each time you run) it should load the Observatory web app. It'd be interesting to know what happens i you try this:

1. Enable flutter_run logs again
2. Launch the app
3. Look in the log file and get the IP/port
4. Open in your browser to see the observatory web app
5. Reproduce the issue in VS Code
6. Hit Refresh in your browser and see if it's still responding

If the web app is still responsive, maybe we can get more information from there?

**Comment by aam** [comment] 2018-05-15 16:01
@DanTup , hot restart follows different path than hot reload. I think here folks are reporting issue with hot reload.
In hot reload flow, first thing that happens is `listViews` request. Currently if UI thread is busy(if Dart VM is paused on a breakpoint for example), then that won't be processed (that is a problem).
In hot restart flow, `listViews` happens after the app is restarted and new isolate is created and started. All of this happens in `run_hot.dart` `restart`, `_restartFromSources` methods.
If you add `pause:true` parameter to any vm request, vm will be paused after it.
To continue isolate execution you can issue `resume` vm request.

I am not sure the steps that are done in IJ/VSCode plugins.

**Comment by aam** [comment] 2018-05-15 16:09
> I guess this is because it doesn't pause after the reload. The problem seems to be that the VM is remaining paused and not responding to the resume command. 

That matches the symptoms, but why are we pausing isolate on hot reload(rather than hot restart) request?

**Comment by DanTup** [comment] 2018-05-15 16:09
@aam Apologies, anytime I said restart I meant reload!

So in the original log, here's the reload request:

> [5:34:24 PM]: ==> [{"id":"8","method":"app.restart","params":{"appId":"cd36a340-0ea8-4cd4-80f8-158e72380363","fullRestart":false,"pause":true}}]

It's a reload (not restart) and we send `pause: true`. When we get `PausePostRequest` we re-send the breakpoints and then send a `resume`. In the log files at the top, we never get a response to that resume (the last thing logged was the outbound resume request and the app was then stalled for a minute).

That said, the comments on the `PausePostRequest` code mention `restart` not `reload` so now I'm wondering if we actually need to re-send breakpoints on a hot restart? If not, we could remove the pausing?

**Comment by AppleEducate** [comment] 2018-05-15 16:09
This seems to happen the most when the app is not doing anything. After I have finished testing on the device and I am going back to the code to update the view then go back to the device it completely freezes and I have to force quit the app and re deploy.

**Comment by aam** [comment] 2018-05-15 16:38
@DanTup, apologies, no, I don't believe so now. You do want to pause and resend breakpoints since the code might have moved as part of the hot reload. So yes, that is how you could end up in the same non-responsive engine state even if your code was not paused on the breakpoint when you did hot reload.
I'm working on a fix for this.

**Comment by DanTup** [comment] 2018-05-15 16:48
@aam Great; thanks!

**Comment by fmatosqg** [comment] 2018-05-15 23:38
after reading about breakpoints on this issue I started fiddling with them and got VERY different results. 

This is how I fiddled: 

![image](https://user-images.githubusercontent.com/5360753/40088788-e468c99c-58eb-11e8-9d3b-7344e573f38d.png)

The sequence I did was roughly the following:

1. disable 'break on exceptions'
2. Add characters one by one to `new Text(''),` with dart 2 enabled on AS.
3. hot reload
4. repeat sequence about 10 times
5. enable 'break on exceptions'
6. do steps 2 - 4. On 7th attempt it chocked and presented the usual problem
7. stop app, disable 'break on exceptions'
8. create a new `new Text(''),`  launch app again
9. repeat steps 2 - 4
10. do step 5 (enable exceptions again)
11. repeat steps 2 - 4

Now I can't make this project hang at all. Next time it does I'll fiddle again with breakpoints.

Note: I usually disable all breakpoints and have none intentionally added, until this hot reload solves itself. 

My logs and setup details are added in https://github.com/flutter/flutter/issues/17005#issuecomment-389035239. The only difference is that I downloaded and launched an emulator based on nexus 5X with Android P, but I could reproduce the problems very easily there yesterday after taking such logs.

**Comment by AppleEducate** [comment] 2018-05-16 00:04
Something changed on my setup too in VSCode, I installed the Offical flutter extension in addition to the dart on that was already installed. I would see if it has break on uncaught exceptions enabled by default...

**Comment by DanTup** [comment] 2018-05-16 06:46
> Something changed on my setup too in VSCode, I installed the Offical flutter extension in addition to the dart on that was already installed

This won't make any difference; at this point all of the debugging comes from the Dart extension (the Flutter extension has a dependency on the Dart one, so if you didn't already have it it would install it for you).

> I would see if it has break on uncaught exceptions enabled by default...

It's not on by default (it's a tickbox at the bottom left of the debug sidebar). I wouldn't expect this setting to affect the ability for us to resume, but I'm not familiar with what's happening in the VM-side.

That said, from the comment above, I think may @aam may have figured out the issue now :-)

**Comment by joon610** [comment] 2018-05-16 08:29
re install other version.. and then done~

**Comment by fmatosqg** [comment] 2018-05-17 00:50
I think I can find an effective workaround the problem.

- Today I opened pre-existing project
- 1st hot reload failed when editing string on text
- stopped, started app, changed string, 1st hot reload failed again. That happened 3x
- opened breakpoints menu, disabled all of them
- hot reload works like magic
- enable same breakpoints as before
- hot reload still working as expected. I can't figure out how to make it fail again.

These are the details:

- Different emulator since last time ( nexus 5x api 26, downloaded about 3 months ago )
- Updated flutter intellij plugin from 24 to 24.0.1 since last report
```
> flutter --version
Flutter 0.4.5-pre.6 • channel master • https://github.com/flutter/flutter.git
Framework • revision a25bbc7bfc (2 days ago) • 2018-05-14 15:51:12 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58
```

![image](https://user-images.githubusercontent.com/5360753/40150865-a3dd3c1c-59bf-11e8-9fbe-c5e1766d8087.png)

**Comment by aam** [comment] 2018-05-18 16:42
The intended fix for this landed in https://github.com/flutter/flutter/commit/89cb5d268d2fc939f180dcee29df7a729fd051ef . If folks could give it a try(get latest flutter from master channel/branch) and confirm, that would be awesome!

**Comment by ThinkDigitalRepair** [comment] 2018-05-20 02:00
@aam, So far so good.

**Comment by aam** [comment] 2018-05-21 15:04
Thank you for confirmation, @ThinkDigitalRepair !

**Closed by aam** 2018-05-21 15:04 UTC
