### ISSUE TITLE
How to catch MultipleGlobalKey exception

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#62442] opened 2020-07-28 21:00 UTC
I have difficulties to find out what causes "Multiple widgets used the same GlobalKey" exceptions. 
I have FlutterError.onError function for central exceptions handling but it does not give any context like what file, which place or which widget causes this error.

I saw on internet that is one of most painfull problem - multiple global keys...
Any advice how to figure out more details?

Thanks

**Comment by TahaTesser** [comment] 2020-07-29 08:48
Hi @vytautas-pranskunas- 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by vytautas-pranskunas-** [comment] 2020-07-29 10:25
I cannot  because i am facing android licenses issues:
![image](https://user-images.githubusercontent.com/3918999/88788740-0d7fcb80-d196-11ea-89da-3a7aaa5812d6.png)

I have followed up yours and other instructions from here:
https://github.com/flutter/flutter/issues/31116
https://github.com/flutter/flutter/issues/51712
https://github.com/flutter/flutter/issues/52719
https://github.com/flutter/flutter/issues/51712

nothing helps... i am getting this
![image](https://user-images.githubusercontent.com/3918999/88788874-3c963d00-d196-11ea-8c36-ebeb537c31f8.png)

I am sure i was not receiving upto month ago...
why there is so many problems with Java :( 
not sure what to do...
however fresh installation on my home pc works fine...

But comming back to this issue i cannot give you reproducable code because it is full application :) and my question was not - WHY i am receiving it - but - HOW to find which widget and code lines are causing it.

**Comment by TahaTesser** [comment] 2020-07-29 11:58
Hi @vytautas-pranskunas- 
I understand it wasn't why but to better address the issue code sample is helpful 
Can you try this possible [solution](https://stackoverflow.com/a/32627841) ?

Thank you

**Comment by vytautas-pranskunas-** [comment] 2020-07-29 12:01
But i am catching those errors in FlutterError.onError - but thay have no information about where it happened.... it just says that "Multiple widgets used the same GlobalKey". 
What try..catch blocks will give me? 
Should i wrap entire app or just one page?

Thank you :)

**Comment by TahaTesser** [comment] 2020-07-29 12:04
Hi @vytautas-pranskunas- 
Have you assigned keys as const? https://stackoverflow.com/a/50050097
please provide a complete reproducible minimal code sample to better address the issue 
Thank you

**Comment by vytautas-pranskunas-** [comment] 2020-07-29 12:10
My keys are not static, but i am sure i was trying to make them static also... I will try once again 
However that was not the root of my question.
my Question is - how to find which key causes an issue, which key is specified multiple times...!
It would be so much helpful to have key name or something else to have in that error message + widget where this issue is happening.

I cannot explain my self more clear :(

Thanks

**Comment by TahaTesser** [comment] 2020-07-30 07:34
Hi @vytautas-pranskunas- 
I believe you cannot this exception, you have to check your code and isolate the area where it might be causing this and fix the issue
Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by vytautas-pranskunas-** [comment] 2020-07-30 07:42
I understand but in .net there is stack trace, or you can see call history
- all call history/path until exception hapened. So you can judge.
But still I do not understand why it is so difficult to try to understand
what I am asking....
I solved my global key issue but my question remains:

In case of GlobalObjectKey('name') - why cannot you show label name in
error message so user knows what causes an error.
In case of GlobalKey - you can show what generic state causes problem and
in which place e.g. Route - home, line 150.

**Comment by goderbauer** [comment] 2020-08-05 22:02
Can you post the text of the full exception you're seeing? There should be more details with that exception:

https://github.com/flutter/flutter/blob/8ad4da4a4e38a9c1592936ceaec2d6c2671ec255/packages/flutter/lib/src/widgets/framework.dart#L219-L224

**Comment by vytautas-pranskunas-** [comment] 2020-08-05 22:42
Hi, i cannot because I just removed all Jay's outside to static class but exception text was standard - exactly what you have posted just without key names and no where they were used also

**Comment by vytautas-pranskunas-** [comment] 2020-08-05 22:44
Aš for me you can close this issue however this topic will not go away from here ant stackoverfliw untill there is no clear messages, stack calls, widgets, place in tree - which key causes this error. This widget tree sounds more mystical than helpful 😊

**Comment by markusaksli-nc** [comment] 2020-09-17 07:55
Closing since this issue is no longer really actionable. I would say the documentation and error message on this is pretty clear. I think this https://github.com/flutter/flutter/issues/34915#issuecomment-669158188 should still apply in regard to these issues.

**Closed by markusaksli-nc** 2020-09-17 07:55 UTC
Labels: d: api docs, documentation, framework, severe: crash
