### ISSUE TITLE
Flutter Windows ARM desktop build run throws exception: unable to generate build files

### ISSUE THREAD

**Issue by sunjianan9900** [flutter/flutter#91356] opened 2021-10-06 09:33 UTC
I'm using parallels on macbook to run windows 10 ARM
while i building a new project to run flutter on desktop, i got this error
 
![image](https://user-images.githubusercontent.com/10936316/136177792-491ad339-43b2-453e-958c-5364ecf05c34.png)

```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.21292.1000], locale zh-CN)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
[!] Android Studio (not installed)
[√] VS Code (version 1.60.2)
[√] Connected device (2 available)

```

</details>

**Comment by TahaTesser** [comment] 2021-10-06 10:11
Hi @sunjianan9900 
Currently, there is no support for ARM desktop as a target. 
Closing as duplicate of https://github.com/flutter/flutter/issues/53120 https://github.com/flutter/flutter/issues/62597

**Closed by TahaTesser** 2021-10-06 10:11 UTC
Labels: in triage
