### ISSUE TITLE
flutter run: Connection closed before full header was received

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12214] opened 2017-09-22 16:54 UTC
```
[ +461 ms] Observatory URL on device: http://127.0.0.1:40907/
[   +2 ms] D:\AndroidDev\AndroidSDK\platform-tools\adb -s emulator-5554 forward tcp:8100 tcp:40907
[  +32 ms] Forwarded host port 8100 to device port 40907 for Observatory
[  +54 ms] Connected to service protocol: http://127.0.0.1:8100/
[   +5 ms] getVM: {}
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:738)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:566)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:414)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:243)
#5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:88)
<asynchronous suspension>
#6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:584)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:106)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:209)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:348)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#11     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:232)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>                                                                                                                                                                                 6:52 PM
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:222)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#19     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     runZoned (dart:async/zone.dart:1467)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#28     main (file:///D:/AndroidDev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel master)
    • Flutter at D:\AndroidDev\flutter
    • Framework revision 63802b3dff (15 hours ago), 2017-09-21 18:29:16 -0700
    • Engine revision 0a6e415b60
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at D:\AndroidDev\AndroidSDK
    • Platform android-26, build-tools 26.0.1
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by YaminT** [comment] 2018-02-27 11:35
I solved it by using https instead of http.

**Comment by Hixie** [comment] 2018-05-30 23:01
Closing because we haven't been able to reproduce. Please let us know if you still see this.

**Closed by Hixie** 2018-05-30 23:01 UTC

**Comment by sahil311289** [comment] 2018-07-03 20:50
Launching lib/main.dart on iPhone X in debug mode...
Warning: Missing asset in fonts for BadScript
Warning: Missing asset in fonts for Roboto
Warning: Missing asset in fonts for Roboto
Starting Xcode build...
Xcode build done.
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws

**Comment by jjarral** [comment] 2018-07-21 13:59
How did you do that? @YaminT 
In which file did you changed http to https?

**Comment by nb7123** [comment] 2019-05-05 07:02
I got this issue too, when i load 40 images from network at once

**Comment by flutterq** [comment] 2021-02-17 02:38
[[Solved] How to fix HttpException: Connection closed before full header was received
](https://fluttercorner.com/httpexception-connection-closed-before-full-header-was-received/)

**Comment by CheaVanto** [comment] 2021-03-09 04:59
@flutterq You think it is the best solution for downgrade from Android Q to Pie? We develop for user. User can use any version. Thus we need to tell user downgrade from Q to Pie?
