### ISSUE TITLE
[FATAL:flutter/runtime/dart_vm.cc(380)] Error while initializing the Dart VM: Wrong full snapshot version, expected '9e1fa667daca1ecf538db8507091794e' found '8343f188ada07642f47c56e518f1307c'

### ISSUE THREAD

**Issue by phucgaoxam** [flutter/flutter#30904] opened 2019-04-11 10:14 UTC
I got this error after migrate my app to AndroidX. The app runs fine on iOS.
I have tried `git reset --hard` `git clean -xffd` `flutter doctor`, switch to channel master, delete flutter/bin/cache but neither of them work.

Flutter doctor: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.4.16-pre.18, on Mac OS X 10.14.3 18D109, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.3)
[✓] Connected device (2 available)
```

**Comment by justinmc** [comment] 2019-04-11 17:13
Duplicate of https://github.com/flutter/flutter/issues/16103, though maybe the migration to AndroidX is making this worse than usual.

**Comment by jonahwilliams** [comment] 2019-04-11 19:03
@phucgaoxam can you try, individually:

1. flutter clean
2. rm -rf `$FLUTTER_ROOT/bin/cache/`

**Comment by phucgaoxam** [comment] 2019-04-16 02:50
I left it for some days, now it's working normally.

**Comment by justinmc** [comment] 2019-04-16 16:02
Alright, I'll close this in favor of https://github.com/flutter/flutter/issues/16103 for now.

**Closed by justinmc** 2019-04-16 16:02 UTC
Labels: tool
