### ISSUE TITLE
[in_app_purchase] restorePurchases stuck when sign in is canceled

### ISSUE THREAD

**Issue by heilmela** [flutter/flutter#86104] opened 2021-07-08 15:25 UTC
I'm currently testing in app purchases on testflight with SandBox Accounts. 
My current purchase flow includes a `restorePurchases` before the user can actually perform any purchase to ensure that my backend does not miss on any past payments.
This flow works fine when the user signs in with his Apple Id successfully, however when i cancel the sign in, `restorePurchases` seems to never return, nor throw any Exception.

Furthermore, i think its problematic to delegate any status update to the `updateListener`, how am i supposed to show any loading screen on invoking `restorePurchases` when the invokation of the method does not provide any meaningful return value. If there are no purchases made im not able to stop loading since i dont get any update on the listener and the method silently returns.

Even when this process is successful its not very pleasent to use, showing a loading GUI only when the `updateListener` receives anything, causes the purchase GUI to appear for a short time and only when there are any purchases to restore the loading GUI is shown wihtout any further interaction which makes the flow rather disturbing.
There should be any way to get feedback if restore purchase was successful or not on method invocation.
## Steps to Reproduce
1. Sign Out of any SandBox Account under Settings - Appstore - "Sandbox"
2.  Invoke
```
    try {
      await InAppPurchase.instance.restorePurchases();
    } catch (e) {
      print(e);
    }
```

3.  Cancel the Sign In Dialog

**Expected results:** 

Any Breakpoint after the method invocation should be hit.

**Actual results:** 
Neither an exception is thrown or the returned `Future<void>` is completed.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/laurin/flutter
    • Framework revision d79295af24 (4 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/laurin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-07-09 11:21
Hi @heilmela 
it won't throw any exception as there is no return and setting breakpoint does stop at `await _inAppPurchase.restorePurchases();` as expected
Thanks for filing the issue, it looks like your concern matches with https://github.com/flutter/flutter/issues/85313, I reproduce no 
Closing as duplicate of https://github.com/flutter/flutter/issues/85313

**Closed by TahaTesser** 2021-07-09 11:21 UTC
Labels: in triage

**Comment by hiddenfloret** [comment] 2021-07-12 07:22
@heilmela you could do something like this:
```
await _iap.restorePurchases().then((value) {
   // Restore action has finished. User entered the correct credentials.
   // Purchase may have been restored OR not.
}, onError: (error) {
   // User cancelled the credentials dialog or entered the wrong credentials.
});
```
