### ISSUE TITLE
Assertion error "Trying to render a disposed EngineFlutterView" (on flutter web, master channel)

### ISSUE THREAD

**Issue by LeoRc01** [flutter/flutter#141253] opened 2024-01-10 09:50 UTC
### Steps to reproduce

1. Start a **WEB** application
2. Press "Hot restart" button (testing on Android Studio)

### Expected results

App restarts successfully

### Actual results

App doesn't restart and throws assertion error as shown in the logs below.

### Code sample

On every code base

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:91:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3        assertFailed
lib/_engine/engine/window.dart 91:13                                              render
packages/flutter/src/rendering/view.dart 309:7                                    compositeFrame
packages/flutter/src/rendering/binding.dart 582:19                                drawFrame
packages/flutter/src/widgets/binding.dart 991:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 443:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1386:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1311:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1169:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1346:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 260:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 185:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall
====================================================================================================

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.19.0-3.0.pre.25, on macOS 14.2.1 23C71 darwin-arm64, locale it-IT)
    • Flutter version 3.19.0-3.0.pre.25 on channel master at /Users/leonardo/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a103002496 (3 hours ago), 2024-01-10 02:02:12 -0500
    • Engine revision 7e6f3d847e
    • Dart version 3.4.0 (build 3.4.0-11.0.dev)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/leonardo/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPhone di Leonardo (mobile) • 00008120-000638C03AF3C01E • ios            • iOS 17.3 21D5026f
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-01-10 12:39
@LeoRc01 Thanks for the report. I am unable to replicate it after running a sample code on web from AS using latest master channel and then hot restarting it which works as expected. No errors were received.
Are there any specific steps or pattern that leads to the error. Does the error occur in canvaskit mode only or in html rendering as well ?

**Comment by danagbemava-nc** [comment] 2024-01-10 12:53
Hi @LeoRc01, do you only experience this issue only when you use android studio? Can you try with the cli or vscode to see if you still experience this issue? 

Does this reproduce with the counter app?

Did this start happening after you upgraded to the current version of the master channel you're on?

I just tested this but I can't seem to reproduce it.

**Comment by LeoRc01** [comment] 2024-01-10 13:05
@danagbemava-nc @darshankawar  thank you for your time and answers. 

- Testing on CLI and VSCode doesn't throw any error but the application won't change, as shown in the video below.

- Testing on AS it throws the error as mentioned in the issue. 

<details open><summary>Android Studio video</summary>

https://github.com/flutter/flutter/assets/45425606/aee58c30-ba1a-433c-9b65-680dfb4289b4

</details>

<details open><summary>VSCode video</summary>

https://github.com/flutter/flutter/assets/45425606/97a1a6a4-3715-4c24-af36-44206a50926d
</details>

**Comment by darshankawar** [comment] 2024-01-11 05:21
Thanks for the update. I think this is similar to https://github.com/flutter/flutter/issues/140684, so please follow-up in it for further updates. Closing this as a duplicate.

**Comment by pedromassango** [comment] 2024-03-08 15:47
Still happening

**Comment by gjlmotea** [comment] 2024-03-10 17:12
Encountered the same problem, it only occurs on the web.
Works fine on mobile platform.
(`flutter doctor -v` status is ok)

**Comment by huycozy** [comment] 2024-03-11 06:05
@pedromassango @gjlmotea What is Flutter version you see the issue?

The stack trace above is not similar to the stack trace at https://github.com/flutter/flutter/issues/140684#issue-2057949780. Instead, this issue is similar to https://github.com/flutter/flutter/issues/142030 which is fixed on the latest beta and master channels. 

For anyone facing this, please try upgrading/switching to beta/master channel. If the issue persists there, please write in comments.

**Comment by pedromassango** [comment] 2024-03-12 20:14
> @pedromassango @gjlmotea What is Flutter version you see the issue?

I'm on stable channel.

```
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:91:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3        assertFailed
lib/_engine/engine/window.dart 91:13                                              render
packages/flutter/src/rendering/view.dart 256:7                                    compositeFrame
packages/flutter/src/rendering/binding.dart 587:19                                drawFrame
packages/flutter/src/widgets/binding.dart 991:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 448:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1386:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1311:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1169:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1346:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 260:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 185:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall
====================================================================================================

```

**Comment by huycozy** [comment] 2024-03-14 07:30
>I'm on stable channel.

This should be fixed on the latest beta or master channels, you can try switching to these channels and re-check it.

**Comment by r-durao-pvotal** [comment] 2024-03-20 17:10
> > I'm on stable channel.
> 
> This should be fixed on the latest beta or master channels, you can try switching to these channels and re-check it.

Tried running the sample counter app. This issue specifically seems to not be happening anymore, but I'm seeing another error being logged this time around:

```
Error: TypeError: Instance of 'UniqueRef<JavaScriptObject>': type 'UniqueRef<JavaScriptObject>' is not a subtype of type 'JSObject'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1388:3                              _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1366:3                              _generalAsCheckImplementation
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 243:33  _argumentErrors
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 422:22  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
Error: TypeError: Instance of 'UniqueRef<JavaScriptObject>': type 'UniqueRef<JavaScriptObject>' is not a subtype of type 'JSObject'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1388:3                              _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1366:3                              _generalAsCheckImplementation
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 243:33  _argumentErrors
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 422:22  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
Error: TypeError: Instance of 'UniqueRef<JavaScriptObject>': type 'UniqueRef<JavaScriptObject>' is not a subtype of type 'JSObject'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1388:3                              _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1366:3                              _generalAsCheckImplementation
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 243:33  _argumentErrors
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 422:22  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
```

**Comment by mbecroft** [comment] 2024-03-20 23:23
Exactly the same errors here when running in Chrome in debug mode after switching to master channel.

As of the last week or so, I have not been able to hot reload or restart - making development work almost impossible.

I also tested with Linux native, and while I get no error messages, hot reload and hot restart do not work.

To be clear, hot reload and hot restart do have an effect (especially with hot restart, you can see the screen be redrawn). The issue is that code changes have no effect.

Given this problem arose since a flutter update from a couple of weeks ago, I am thinking of downgrading to see if that fixes it.

**Comment by huycozy** [comment] 2024-03-21 05:06
@r-durao-pvotal I also can reproduce that issue on master channel. Filed it here in dart repo: https://github.com/dart-lang/sdk/issues/55256

**Comment by r-durao-pvotal** [comment] 2024-03-21 09:51
@huycozy do you have an estimate on when this issue will be tackled? This severely hinders web app development using flutter. Having to re-run the app every time we want to test a change is extremely time consuming

**Comment by huycozy** [comment] 2024-03-21 10:10
@r-durao-pvotal I'm not sure, but usually issues like this will be noticed quickly (within a day)

**Comment by nialljawad96** [comment] 2024-03-22 17:22
This is a shambles. Disabling issues on both master and stable channels

**Comment by pedromassango** [comment] 2024-03-22 21:15
Closing as this isn't happening on master.

**Closed by pedromassango** 2024-03-22 21:15 UTC
Labels: waiting for customer response, in triage

**Comment by SeriousMonk** [comment] 2024-03-28 10:17
This is indeed still happening on master.

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22631.3296], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.87.2)
[√] Connected device (3 available)
[√] Network resources
```
