### ISSUE TITLE
[video_player] Aspect Ratio sometimes incorrect in iOS

### ISSUE THREAD

**Issue by leochiu-work** [flutter/flutter#66413] opened 2020-09-23 03:13 UTC
Hi, I found that the VideoPlayerController aspect ratio is sometimes incorrect, the width and height are interchanged.

Version is video_player: ^0.10.12+3
My testing device is iOS 14, not sure if it relates

```
VideoPlayerController videoPlayerController = VideoPlayerController.file(currentVideoFile);
await videoPlayerController.initialize();
developer.log(videoPlayerController.value.aspectRatio.toString());
```
The aspectRatio sometimes 1.777, sometimes 0.5625.

Here is my "flutter doctor -v"

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-HK)
    • Flutter version 1.20.4 at /Users/leochiu/Documents/Sources/flutter
    • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/leochiu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chi Ho’s iPhone (mobile) • 6e805e3b7ea518ced638b5b6eafddf06cf289318 • ios • iOS 14.0
```

**Comment by darshankawar** [comment] 2020-09-23 08:09
Hi @leochiu-work,
I tried the official `video_player` plugin [example](https://pub.dev/packages/video_player/example) on latest stable (1.20.4) on iPhone 6+ (OS 12.4.5) and observed consistent aspectRatio when video was playing.

```
TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
```

Although, not sure if iOS 14 will make any difference, but can you try the official example and see if you see deviation.
Thanks.

**Comment by leochiu-work** [comment] 2020-09-23 09:04
Hi @darshankawar , thanks for your advice. video_player plugin example works perfectly while playing a static asset.

There's maybe some misunderstanding, what I mean is different aspect ratio when I picked the same video repeatedly.

I was modified the example to pick the video from my phone library, with code as below. (Another library dependency: https://pub.dev/packages/image_picker)

```
ImagePicker imagePicker = ImagePicker();
PickedFile videoFile = await imagePicker.getVideo(source: ImageSource.gallery);

if (videoFile != null) {
    _controller = VideoPlayerController.file(File(videoFile.path));

     _controller.addListener(() {
        setState(() {});
    });
    await _controller.initialize();
    developer.log("_controller.value.aspectRatio = " + _controller.value.aspectRatio.toString());
}
```

It has exactly the same problem. Also, seems only portrait video has this issue, landscape video is totally fine.

Thanks.

**Comment by darshankawar** [comment] 2020-09-23 12:01
Thanks @leochiu-work for the details. I do see deviation in `aspectRatio` while playing different videos from gallery, but not sure if this is intended or a bug, because the video selected could be of different size, resolution. Keeping this issue open for further analysis.

```
flutter: _controller.value.aspectRatio = 0.5625                 
flutter: _controller.value.aspectRatio = 1.7777777777777777                                                                                               
flutter: _controller.value.aspectRatio = 0.5625  
```  

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.20.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

```

</details>

**Comment by leochiu-work** [comment] 2020-09-23 12:16
Thanks @darshankawar for the investigation.

I have different aspect ratio even if I selected same video. Sometimes 0.5625, sometimes 1.7777.

Due to the incorrect aspectRatio, my video is totally distort while playing.
Do you advise if there's any workaround at this moment?

**Comment by dvlj** [comment] 2020-09-24 09:01
having the same problem

flutter 1.20.4
ios 14

**Comment by snowb1shop** [comment] 2020-10-02 12:23
Same issue here

**Comment by khacnha** [comment] 2020-10-06 10:21
Me too

**Comment by RNCDev** [comment] 2020-10-07 20:13
I think we are seeing it in our app when a user records a video on Android and it is view on iOS. Is that possible? We're finding it a challenge to debug.

**Comment by cuililong** [comment] 2020-10-12 09:54
有同样的问题，请问有解决方案吗？

**Comment by danielwalczak** [comment] 2020-10-12 21:37
same here

**Comment by RNCDev** [comment] 2020-10-13 12:28
Crazy. We have a stupid work around:

? (PlatformService.deviceData['systemVersion'] != null &&
                              PlatformService.deviceData['systemVersion'] >=
                                  14.0)
                          ? CachedVideoPlayer(videoPlayerController)
                          : AspectRatio(
                              child: CachedVideoPlayer(videoPlayerController),
                              aspectRatio:
                                  videoPlayerController.value.aspectRatio,
                            )
                      : Container(
                          height: 500 * ScreenRatio.heightRatio,
                        ),

**Comment by OctMon** [comment] 2020-10-19 04:07
having the same problem

flutter 1.22.2
ios 14.0.1

**Comment by ObserverMoment** [comment] 2020-10-19 08:57
Also getting this issue after picking a file with "image_picker: ^0.6.7+4".

flutter: ^1.20.1
ios 14

Using "flutter_video_info: ^1.0.1" to try and get the correct info from the local file seems to show that any file that is picked will come back with a larger width dimension than height dimension (i.e. as if it is landscape).

So landscape videos are fine, they display correctly.

All portrait videos have their dimensions reversed. The longer side appears to be being auto set as the width.

The filetype is video/quicktime (.MOV) and the files are coming straight from the iOS photos library via image_picker.

Could image_picker be scrambling the meta data?

Or is there some issue with how both "video_player" and "flutter_video_info" are analysing these .MOV files?

**Comment by ObserverMoment** [comment] 2020-10-19 16:18
Some additional info: Just to confirm that the issue is not occurring on the android emulator. I don't have an android device here to test on. Can anyone point to the code in the library where video_player calculates the size of the video so that I can investigate? Assume it runs after this ```VideoPlayerController.file(File(widget.filePath))```.

**Comment by Ehesp** [comment] 2020-10-20 10:35
Is this happening on pre-iOS 14?

On Android, the width/height are flipped if the rotation of the video is detected to be portrait: https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java#L265

On iOS, this doesn't happen: https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L307

I'll do some more digging to see if `presentationSize` has changed behaviour recently.

**Comment by ObserverMoment** [comment] 2020-10-20 11:41
That looks like a promising lead, thanks for digging! I have always had issues with aspect ratio in the video_player package on iOS since starting to use flutter (around 6 months ago - so well before iOS14). The same issue has never been present on the Android emulator.

There is some action defined elsewhere in the file regarding rotation on iOS, but nothing which is called in the sendInitialized method.

getVideoCompositionWithTransform method: 

https://github.com/flutter/plugins/blob/9560b2ac8eaf23bc5568aafca229de2ef83dac5e/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L134

**Comment by Ehesp** [comment] 2020-10-20 11:43
Yeah I saw that too, was just trying to dig into why it's called in one location (and the reason) and not the other. Will keep having a look.

**Comment by paperview** [comment] 2020-10-22 14:51
I believe it does happen on iOS
`  if (rotationDegrees == 90 || rotationDegrees == 270) {
    width = videoTrack.naturalSize.height;
    height = videoTrack.naturalSize.width;
  }`

**Comment by Ehesp** [comment] 2020-10-22 15:22
@paperview Yep it does happen at one point, I'm just not sure whether that code is being handled during initialization (where this issue is happening).

**Comment by serp1412** [comment] 2020-10-22 15:54
@Ehesp It doesn't. It does use the current `width` and `height` if I change the `sendInitialized` [method](https://github.com/flutter/plugins/blob/08706281d34277c28296df7f3a272e5e13e2ff35/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L305) to this (rough patch):

```
- (void)sendInitialized {
  if (_eventSink && !_isInitialized) {
    CGSize size = [self.player currentItem].presentationSize;
    CGFloat width = size.width;
    CGFloat height = size.height;

    // The player has not yet initialized.
    if (height == CGSizeZero.height && width == CGSizeZero.width) {
      return;
    }
    // The player may be initialized but still needs to determine the duration.
    if ([self duration] == 0) {
      return;
    }
      
      // Fetching the natural size and applying the preferredTransform
      AVPlayerItemTrack *track = [self.player currentItem].tracks.firstObject;

      CGSize naturalSize = track.assetTrack.naturalSize;
      CGAffineTransform prefTrans = track.assetTrack.preferredTransform;
      CGSize realSize = CGSizeApplyAffineTransform(naturalSize, prefTrans);
      
    _isInitialized = true;
    _eventSink(@{
      @"event" : @"initialized",
      @"duration" : @([self duration]),
      @"width" : @(fabs(realSize.width) ? : width),
      @"height" : @(fabs(realSize.height) ? : height)
    });
  }
}
```

This fixes my current problem with playing network videos

**Comment by paperview** [comment] 2020-10-22 16:07
@Ehesp  good shout yes it seems the bug is that presentationSize is always landscape, so we want to read the actual renderSize given on this line
`videoComposition.renderSize = CGSizeMake(width, height);`
I fixed by setting a new property to hold this value

@serp1412 i might steal your solution, nice patch

**Comment by serp1412** [comment] 2020-10-22 17:11
@paperview take it if you have to :)

**Comment by danielwalczak** [comment] 2020-10-22 17:52
anyone can open PR ?

**Comment by Ehesp** [comment] 2020-10-23 13:01
@danielwalczak Yah will get it sorted.

**Comment by qbait** [comment] 2020-11-03 23:47
Any update on that one?

**Comment by snail-xx** [comment] 2020-11-06 10:47
@paperview your solution works for me，thanks a lot !

**Comment by iozozturk** [comment] 2020-12-06 13:36
I found the workaround as consuming the videos with pre-calculated aspect ratio and using that in video player.

**Comment by marcodecarolisidt** [comment] 2021-04-02 10:12
Is this fixed? It happens to me randomly as well, on iPhone SE

**Comment by TahaTesser** [comment] 2021-04-05 13:57
I can reproduce the issue on the simulator on iPhone SE and iPhone 11

<details> 
<summary>screenshots</summary> 

|  iPhone SE | iPhone 11 |
| --------------- | --------------- |
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-04-05 at 16 43 30](https://user-images.githubusercontent.com/48603081/113581003-2eef5c00-962f-11eb-8915-4378997b94b5.png) | ![Simulator Screen Shot - iPhone 11 - 2021-04-05 at 16 48 33](https://user-images.githubusercontent.com/48603081/113581021-37479700-962f-11eb-9e0e-ef8250c98048.png)



</details>

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(VideoPlayerApp());

class VideoPlayerApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Player Demo',
      home: VideoPlayerScreen(),
    );
  }
}

class VideoPlayerScreen extends StatefulWidget {
  VideoPlayerScreen({Key key}) : super(key: key);

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends State<VideoPlayerScreen> {
  VideoPlayerController _controller;
  Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    // Create and store the VideoPlayerController. The VideoPlayerController
    // offers several different constructors to play videos from assets, files,
    // or the internet.
    _controller = VideoPlayerController.network(
      'https://dev-cdn.hdmessaging.com/7/agvuxqkj9v1w.MOV',
    );

    // Initialize the controller and store the Future for later use.
    _initializeVideoPlayerFuture = _controller.initialize();

    // Use the controller to loop the video.
    _controller.setLooping(true);

    super.initState();
  }

  @override
  void dispose() {
    // Ensure disposing of the VideoPlayerController to free up resources.
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Butterfly Video'),
      ),
      // Use a FutureBuilder to display a loading spinner while waiting for the
      // VideoPlayerController to finish initializing.
      body: FutureBuilder(
        future: _initializeVideoPlayerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the VideoPlayerController has finished initialization, use
            // the data it provides to limit the aspect ratio of the video.
            return FittedBox(
              fit: BoxFit.fitHeight,
              child: SizedBox(
                width: _controller.value.size.width,
                height: _controller.value.size.height,
                child: VideoPlayer(_controller),
              ),
            );
          } else {
            // If the VideoPlayerController is still initializing, show a
            // loading spinner.
            return Center(child: CircularProgressIndicator());
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          // Wrap the play or pause in a call to `setState`. This ensures the
          // correct icon is shown.
          setState(() {
            // If the video is playing, pause it.
            if (_controller.value.isPlaying) {
              _controller.pause();
            } else {
              // If the video is paused, play it.
              _controller.play();
            }
          });
        },
        // Display the correct icon depending on the state of the player.
        child: Icon(
          _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale
    en-GB)
    • Flutter version 2.0.4 at /Users/nevercode/Code/flutter_stable
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios
      • iOS 10.3.3
    • macOS (desktop)        • macos                                    •
      darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.444, on macOS 11.2.3 20D91
    darwin-arm, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.444 at /Users/nevercode/Code/flutter_master
    • Framework revision 824b1ad3f8 (2 days ago), 2021-04-03 15:24:02 -0400
    • Engine revision e393800c63
    • Dart version 2.13.0 (build 2.13.0-196.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios
      • iOS 10.3.3
    • macOS (desktop)        • macos                                    •
      darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.
```
	
</details>

**Comment by danagbemava-nc** [comment] 2021-11-17 13:04
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-17 13:04 UTC
Labels: platform-ios, waiting for customer response, plugin, p: first party, p: video_player, has reproducible steps, P4, found in release: 1.20, found in release: 2.0, found in release: 2.1
