### ISSUE TITLE
The height of AppBar in iPhone 6s plus is incorrect after upgrade to flutter 1.17

### ISSUE THREAD

**Issue by cdhigh** [flutter/flutter#57457] opened 2020-05-18 02:02 UTC
## Steps to Reproduce
After upgrade to 1.17.0, The height of AppBar in iPhone 6s plus is very closer to statusbar as showed in picture, I tested in 1.17.1, the problem is the same.
![IMG-20200517-WA0001](https://user-images.githubusercontent.com/2580077/82166938-84444280-9890-11ea-9d6d-44962fe41e4d.jpg)
In 1.12.13 it was correct.
The code is very simple:
```
class SettingsPage extends StatefulWidget {
  @override
  _SettingsPageState createState() => _SettingsPageState();
}

class _SettingsPageState extends State<SettingsPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Settings'.i18n)),
      body: buildMainList(context),  // return a Container(child: ListView).
    );
  }
```

In Android, the height is correct.

**Comment by VladyslavBondarenko** [comment] 2020-05-18 14:02
Hi @cdhigh 
I don't have iPhone 6s to check.
Does it reproduce with this code sample?

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Settings')),
      body: Container(),
    );
  }
}
```

Could you provide a screenshot how does it look with `1.12.13`?

**Comment by cdhigh** [comment] 2020-05-18 16:54
Sorry for that, I compiled it with flutter 1.12.13, found the problem is the same: AppBar very closer to the StatusBar.
Because I was using android for debug, every some weeks send a version to a colleague.
he sent me the screenshot recently and I had upgraded to 1.17.
The space between AppBar and StatusBar is really smaller than other APP in iPhone 6s plus.
I created a new project with 'flutter create' and tested it too, but the problem is still.
It's a bug or I missed something?

**Comment by VladyslavBondarenko** [comment] 2020-05-19 08:35
@cdhigh 
on simulators with iOS 13.4 the AppBar doesn't overlap with status bar, what iOS version do you have on your device?

**Comment by cdhigh** [comment] 2020-05-19 09:39
13.4.1

**Comment by VladyslavBondarenko** [comment] 2020-05-19 09:56
@cdhigh 
Is status bar overlapped by AppBar when you run a default project (created via `flutter create`) on iPhone 6s?

**Comment by cdhigh** [comment] 2020-05-19 10:53
Yes, a default project without any modification.

**Comment by cdhigh** [comment] 2020-05-30 15:10
I put the statement `showToast(MediaQuery.of(context).padding.top.toString());` in a callback of a button, and the result is 0.0 on IOS, but is 24.0 on Android.

the same problem with #58150,
Which source file I can modify the variable 'MediaQuery.of(context).padding.top'?
I would to fix the variable to 24.0.

**Comment by cdhigh** [comment] 2020-05-30 16:34
I got it 'solved' as use following class to wrap the scaffold, and it will apply extra padding on plataform IOS.
I tested with the widget SafeArea, nothing happen.

```
class FixPadding extends StatelessWidget {
  final Widget scaffold;
  FixPadding(this.scaffold);
  @override
  Widget build(BuildContext context) {
    return Platform.isIOS 
      ? Container(padding: EdgeInsets.only(top: 20.0), color: Colors.blue, child: scaffold)
      : scaffold;
  }
}
```

for example:
```
@override
Widget build(BuildContext context) {
    super.build(context);
    return FixPadding(Scaffold(
      appBar: AppBar(title: Text('Title')),
      body: ...,
    ));
  }
```

**Comment by pedromassangocode** [comment] 2020-07-21 08:35
Hi @cdhigh,
I can't reproduce this on `dev` nor `stable` version with an iPhone 6s plus simulator (iOS 13.5).
Can you try to reproduce on the current `stable` channel?
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

 <details>
<summary> Complete sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
      leading: BackButton(),
      title: Text('Settings')),
      body: Container(),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (6 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome is not
      executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • iPhone 6s Plus (mobile) • EE37BCBA-E9E7-4411-9C09-7E8E85DB4ADF • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)         • macos                                •
      darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)        • web-server                           •
      web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
</details>

**Comment by cdhigh** [comment] 2020-07-23 11:42
I have reinstalled the mac os system and it is normal now. I don’t know if it’s a system problem or flutter problem.
This issue can be closed.

**Comment by pedromassangocode** [comment] 2020-07-24 12:01
Hi @cdhigh 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2020-07-24 12:01 UTC
Labels: e: device-specific, f: cupertino, f: material design, framework, platform-ios
