### ISSUE TITLE
While auto importing widgets the suggestion getting illegal characters error every time

### ISSUE THREAD

**Issue by iamkranthi** [flutter/flutter#106625] opened 2022-06-26 07:57 UTC
I recently shifted from windows to fedora 36 and I installed flutter and started a new project.
Flutter provides an auto-importing tool for widgets when I try to auto-import a widget with closed brackets ().
It is showing an illegal character error. example:-
If I try to import a text widget  it gives me Text(...) which decreases productivity and please help me to solve this error

![Screenshot from 2022-06-26 13-20-12](https://user-images.githubusercontent.com/75005151/175805039-2cf9e42d-2214-441f-a023-916365806d47.png)
![Screenshot from 2022-06-26 13-20-19 (1)](https://user-images.githubusercontent.com/75005151/175805050-32a4cf64-4976-443b-80c4-ea1f5be302cc.png)

**Comment by huycozy** [comment] 2022-06-27 09:38
Hi @iamkranthi 
It looks like you are working with VSCode. Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you!

**Closed by huycozy** 2022-06-27 09:38 UTC
Labels: in triage
