### ISSUE TITLE
Flutter not working on new Android LadyBug

### ISSUE THREAD

**Issue by williaanlopes** [flutter/flutter#158926] opened 2024-11-14 14:37 UTC
### Steps to reproduce

1. Install new Android Studio
2. Try run flutter app

### Actual results

[Gradle Build Fails with "Unsupported class file major version 65" After Updating to Java 17](https://stackoverflow.com/questions/79069781/gradle-build-fails-with-unsupported-class-file-major-version-65-after-updating)

### Logs

<details open>
<summary>Logs</summary>

```console

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\joao.nova\StudioProjects\ouze-mobile-v2\android\settings.gradle' (C:\Users\...\.gradle\caches\7.5\scripts\3d075fs9hjp81ny0sgym4v09w).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more

```

</details>

Error

![image (9)](https://github.com/user-attachments/assets/0b766e39-153d-4cab-aa4a-8e9e7fb3837d)

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [versÆo 10.0.19045.5131], locale pt-BR)
    • Flutter version 3.16.9 on channel stable at C:\flutter_3.16.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (10 months ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\willi\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\willi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-17\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Ferramentas de Build do Visual Studio 2022 17.5.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Ferramentas de Build do Visual Studio 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Community Edition (version 2024.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\willi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM A155M (mobile) • RQ8X900BTYW • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [versÆo 10.0.19045.5131]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 130.0.2849.80

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by EdsonMello-code** [comment] 2024-11-18 18:33
Can you show the full error please?

**Comment by BLumia** [comment] 2024-11-19 18:02
I'm also getting the same issue, while I already get it working, here are my detailed information when it doesn't work:

```
> flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [版本 10.0.22631.4460], locale zh-CN)
    • Flutter version 3.24.4 on channel stable at C:\Users\Gary\Programs\flutter-sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (4 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at E:\AndroidSDK
    • Platform android-35, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35431.28
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.95.3)
    • VS Code at C:\Users\Gary\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[√] Connected device (4 available)
    • MI 6X (mobile)    • 944bccec • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22631.4460]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 131.0.6778.69
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 131.0.2903.51

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```
> flutter config --list
All Settings:
  enable-web: (Not set)
  enable-linux-desktop: (Not set)
  enable-macos-desktop: (Not set)
  enable-windows-desktop: (Not set)
  enable-android: (Not set)
  enable-ios: (Not set)
  enable-fuchsia: (Not set) (Unavailable)
  enable-custom-devices: (Not set)
  cli-animations: (Not set)
  enable-native-assets: (Not set) (Unavailable)
  enable-flutter-preview: (Not set) (Unavailable)
  enable-swift-package-manager: (Not set) (Unavailable)
  android-sdk: E:\AndroidSDK
```

See the attached file for the output of `flutter run -v > run-v.log 2>&1`:

[run-v.log](https://github.com/user-attachments/files/17819392/run-v.log)

> Does the [answer](https://stackoverflow.com/a/79085420/5921933) on the SO link you shared help?

Yes, it works!

**Comment by EdsonMello-code** [comment] 2024-11-20 12:36
Good morning, this problem occurs when a dependency does not support Java 21, which Android Studio Ladybug brings by default as share_plus, which requires Java 17. Even if you do not use this package directly, it is very likely that some dependency uses it.

To solve the problem, you need to install Java 17 and indicate it to Flutter to use with this command:

flutter config --jdk-dir <path-to-java-sdk-17-home-directory>

I hope this solved your problem.

**Comment by techouse** [comment] 2024-11-26 09:04
Check my comment here https://github.com/flutter/flutter/issues/156111#issuecomment-2391603873

**Comment by tamilvanan07** [comment] 2024-11-28 06:00
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip
change in the gradle-wrapper.properties

**Comment by williaanlopes** [comment] 2024-12-05 14:29
@EdsonMello-code  error is

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\joao.nova\StudioProjects\ouze-mobile-v2\android\settings.gradle' (C:\Users\...\.gradle\caches\7.5\scripts\3d075fs9hjp81ny0sgym4v09w).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more
```

**Comment by williaanlopes** [comment] 2024-12-05 20:09
> Good morning, this problem occurs when a dependency does not support Java 21, which Android Studio Ladybug brings by default as share_plus, which requires Java 17. Even if you do not use this package directly, it is very likely that some dependency uses it.
> 
> To solve the problem, you need to install Java 17 and indicate it to Flutter to use with this command:
> 
> ```shell
> flutter config --jdk-dir <path-to-java-sdk-17-home-directory>
> ```
> 
> I hope this solved your problem.

This solved it for me, my question is whether Android Studio (and future versions) will not support Flutter?

**Comment by EdsonMello-code** [comment] 2024-12-05 20:38
> > Good morning, this problem occurs when a dependency does not support Java 21, which Android Studio Ladybug brings by default as share_plus, which requires Java 17. Even if you do not use this package directly, it is very likely that some dependency uses it.
> > To solve the problem, you need to install Java 17 and indicate it to Flutter to use with this command:
> > ```shell
> > flutter config --jdk-dir <path-to-java-sdk-17-home-directory>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this solved your problem.
> 
> This solved it for me, my question is whether Android Studio (and future versions) will not support Flutter?

Flutter supports Java version 21 and will probably support higher versions, the problem is in packages that do not yet support these versions such as share_plus or another package.

**Comment by danagbemava-nc** [comment] 2024-12-06 06:22
Closing this since it has been resolved. 

Thank you

**Closed by danagbemava-nc** 2024-12-06 06:22 UTC
Labels: in triage
