### ISSUE TITLE
Google sign-in Cancelling throws an error 

### ISSUE THREAD

**Issue by rjzg85** [flutter/flutter#60261] opened 2020-06-25 05:19 UTC
When I cancel the sign in it sends an error that I can't catch

    try{
     GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
    }catch(e){
      print('error');
    }
<img width="852" alt="Screen Shot 2020-06-25 at 12 18 54 AM" src="https://user-images.githubusercontent.com/42377283/85658966-92e4fd00-b679-11ea-9099-905fbbf342a0.png">

**Comment by TahaTesser** [comment] 2020-06-25 13:28
duplicate of https://github.com/flutter/flutter/issues/44431

**Closed by TahaTesser** 2020-06-25 13:28 UTC
