### ISSUE TITLE
Webview Plugin: is there any loadDataWithBaseURL alternative?

### ISSUE THREAD

**Issue by Praveena0989** [flutter/flutter#34920] opened 2019-06-22 12:12 UTC
In the android version of my app, I use `loadDataWithBaseURL` to load the local HTML file and I use it to play youtube videos using youtube JS SDK.
`loadDataWithBaseURL("https://www.youtube.com", htmlPageString, "text/html", "utf-8", null)`

In flutter, I am able to load the local HTML file but I am not able to play youtube video as Youtube throws video not available error and I used to get same error while using `loadData` api insead of `loadDataWithBaseURL` in android.

**Comment by Piinks** [comment] 2019-06-26 16:59
Hi @Praveena0989, Can you post a reproduction of the issue? We will need more information to help you resolve it.

**Comment by Praveena0989** [comment] 2019-06-28 09:04
This is my HTML file 
```
<!DOCTYPE html>
<html>
<style type="text/css">
    html,
    body {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
        background-color: #000000;
        overflow: hidden;
        position: fixed;
    }
</style>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <script src="https://www.youtube.com/iframe_api"></script>
</head>

<body>
    <div id="youTubePlayerDOM"></div>
</body>

<script type="text/javascript">
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('youTubePlayerDOM', {
            height: '100%',
            width: '100%',
            videoId:"Q-GOFPM01d0",
            playerVars: {
                controls: 1,
                fs:0,
                autoplay:1,
                playsinline:1,
                modestbranding:1
            }
        });
    }
</script>

</html>
```

And I am using it in my code like this 

```
void didChangeDependencies() {
    DefaultAssetBundle.of(context)
        .loadString('assets/youtube_player.html')
        .then((html) {
      setState(() {
        _html = html;
      });
    });
    super.didChangeDependencies();
  }

@override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: SafeArea(
          child: AspectRatio(
            aspectRatio: 16.0 / 9.0,
            child: _html == null
                ? CupertinoActivityIndicator()
                : WebView(
                      initialUrl:
                          new Uri.dataFromString(_html, mimeType: 'text/html')
                              .toString(),
                      javascriptMode: JavascriptMode.unrestricted)))
}
```

But youtube video won't play but shows video unavailable it's because youtube doesn't allow playing from local HTML which can be solved in android using `loadDataWithBaseURL("https://www.youtube.com", htmlPageString, "text/html", "utf-8", null)` but I don't see any alternative for this in flutter.

**Comment by AhmedNourJamalElDin** [comment] 2020-06-12 07:06
Any guidance to help in implementing this?
I'm not sure I can do it all or do it on my own because I have 0 knowledge in Swift and IDK if `loadDataWithBaseUrl` is available for iOS.

so if someone can help, I may help in implementing this.

**Comment by AhmedNourJamalElDin** [comment] 2020-06-14 10:03
@Piinks  any idea, please?

**Comment by uc-apa** [comment] 2020-08-07 07:56
I had opened pull request for this, in which the flutter webview has the support for baseUrl and localHtml support same as react native. I don't know why it is still not merged.

[https://github.com/flutter/plugins/pull/2830](https://github.com/flutter/plugins/pull/2830)
by adding simply two new attributes, html string with baseUrl(optional) can be loaded.

html: "<html><body>Sample</body></html>",
baseUrl: "file://" + HOME_PATH + '/',

also if required the html inside webview can be replaced with other other using webviewController.

webViewController.loadHtml(html);

---This needs to be added in pubspec.yaml---
webview_flutter:
    git:
      url: https://github.com/uc-apa/plugins.git
      path: packages/webview_flutter

**Comment by uc-dve** [comment] 2021-06-10 08:48
> I had opened pull request for this, in which the flutter webview has the support for baseUrl and localHtml support same as react native. I don't know why it is still not merged.
> 
> [flutter/plugins#2830](https://github.com/flutter/plugins/pull/2830)
> by adding simply two new attributes, html string with baseUrl(optional) can be loaded.
> 
> html: "Sample",
> baseUrl: "file://" + HOME_PATH + '/',
> 
> also if required the html inside webview can be replaced with other other using webviewController.
> 
> webViewController.loadHtml(html);
> 
> ---This needs to be added in pubspec.yaml---
> webview_flutter:
> git:
> url: https://github.com/uc-apa/plugins.git
> path: packages/webview_flutter

Hey! please let us know when it will be merged?
and is there any way to provide assets path in baseUrl

**Comment by stuartmorgan** [comment] 2023-03-18 17:48
Closing as resolved; the current API has `loadHtmlString`, which can take a base URL.

**Closed by stuartmorgan** 2023-03-18 17:48 UTC
Labels: new feature, plugin, p: webview, P4
