### ISSUE TITLE
[Share][Bug] Text not showing in share popup

### ISSUE THREAD

**Issue by jeremiahlukus** [flutter/flutter#79201] opened 2021-03-27 15:45 UTC
## Issue 
When using the share plugin i would expect the text to show in the share modal however i only see the app logo
Share only takes 3 args so i dont think i am missing something 

```
  static Future<void> share(
    String text, {
    String? subject,
    Rect? sharePositionOrigin,
  })
```

## How to reproduce 

```
 await Share.share("Hey im some text",
                            subject: "yoyo im a subject",
                            sharePositionOrigin:
                                box.localToGlobal(Offset.zero) & box.size);
```
<img width="654" alt="Screen Shot 2021-03-27 at 11 44 26 AM" src="https://user-images.githubusercontent.com/17206638/112726080-e37fd400-8ef1-11eb-9552-48717e07a2d4.png">

## Versions 

share: ^2.0.1

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.2, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
[✓] VS Code (version 1.53.2)
[✓] Connected device (3 available)
```

**Comment by darshankawar** [comment] 2021-03-29 09:41
Closing this as duplicate of https://github.com/flutter/flutter/issues/55061

**Closed by darshankawar** 2021-03-29 09:41 UTC
Labels: in triage
