### ISSUE TITLE
Widgets using another widget constructor tear-off in build crush during painting on the Web

### ISSUE THREAD

**Issue by mitryp** [flutter/flutter#128895] opened 2023-06-14 18:46 UTC
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a widget that takes a constructor of another widget in its constructor and uses it in its build method.
2. Create this widget and pass another widget constructor tear-off.
3. Run Flutter for Web in a release of profile mode and see the error in the browser console.

### Expected results

The error should not occur, the widget should be displayed correctly.

### Actual results

The widget created this way does not appear on the screen; 
<details><summary>The following error is printed in the browser console</summary>

```dart
NoSuchMethodError: method not found: 'index' on null
js_primitives.dart:42     at PaintingContext._clipAndPaint$4 (http://localhost:57723/main.dart.js:67619:28)
js_primitives.dart:42     at PaintingContext.clipPathAndPaint$4 (http://localhost:57723/main.dart.js:67639:12)
js_primitives.dart:42     at PaintingContext.pushClipPath$7$clipBehavior$oldLayer (http://localhost:57723/main.dart.js:71094:15)
js_primitives.dart:42     at RenderPhysicalShape.paint$2 (http://localhost:57723/main.dart.js:73841:31)
js_primitives.dart:42     at RenderPhysicalShape._paintWithContext$2 (http://localhost:57723/main.dart.js:71675:15)
js_primitives.dart:42     at PaintingContext.paintChild$2 (http://localhost:57723/main.dart.js:70968:17)
js_primitives.dart:42     at RenderConstrainedBox.paint$2 (http://localhost:57723/main.dart.js:73366:17)
js_primitives.dart:42     at RenderConstrainedBox._paintWithContext$2 (http://localhost:57723/main.dart.js:71675:15)
js_primitives.dart:42     at PaintingContext.paintChild$2 (http://localhost:57723/main.dart.js:70968:17)
js_primitives.dart:42     at _RenderInputPadding0.paint$2 (http://localhost:57723/main.dart.js:74614:17)
js_primitives.dart:42 Another exception was thrown: NoSuchMethodError: method not found: 'index' on null
```

</details>

I wasn't able to reproduce this problem on Android, it only appears on the Web.

This issue also occurs when specifying constructor tear-offs as default values for such fields.

The workaround that I have found is to replace the constructor tear-off with a lambda/function with the same signature calling the desired widget constructor.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: TestWidget(
          buttonConstructor: OutlinedButton.new,
        ),
      ),
    );
  }
}

typedef ButtonConstructor = Widget Function({
  required VoidCallback onPressed,
  required Widget child,
});

class TestWidget extends StatelessWidget {
  final ButtonConstructor buttonConstructor;

  const TestWidget({
    required this.buttonConstructor,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return buttonConstructor(
      onPressed: () {},
      child: const Text('test'),
    );
  }
}

```

</details>

### Logs

I only run the `flutter run web --profile` command.
<details><summary>Logs</summary>

```console
C:\Users\Dmytro\Desktop\flutter_constructors_issue>flutter run -d chrome --profile --verbose
[   +4 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +87 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f92f44110e87bad5ff168335c36da6f6053036e6
[        ] executing: [C:\tools\flutter/] git tag --points-at f92f44110e87bad5ff168335c36da6f6053036e6
[ +311 ms] Exit code 0 from: git tag --points-at f92f44110e87bad5ff168335c36da6f6053036e6
[   +1 ms] 3.10.3
[   +3 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +39 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +48 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +112 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +126 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +78 ms] Skipping pub get: version match.
[ +241 ms] Launching lib\main.dart on Chrome in profile mode...
[ +114 ms] generated_plugin_registrant.dart not found. Skipping.
[   +3 ms] Compiling lib\main.dart for the Web...
[   +5 ms] Initializing file store
[  +11 ms] Done initializing file store
[  +70 ms] Skipping target: web_entrypoint
[   +2 ms] Skipping target: gen_localizations
[   +6 ms] web_static_assets: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing:
C:\Users\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\flutter.js,C:\Users\Dmyt
ro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\canvaskit\canvaskit.js,C:\Users\Dmytr
o\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\canvaskit\canvaskit.wasm,C:\Users\Dmyt
ro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\canvaskit\chromium\canvaskit.js,C:\Us
ers\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\canvaskit\chromium\canvaskit.
wasm,C:\Users\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\canvaskit\skwasm.js
,C:\Users\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\canvaskit\skwasm.wasm,C
:\Users\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\canvaskit\skwasm.worker.j
s}
[ +410 ms] dart2js: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Users\Dmytro\Desktop\flutter_constructors_issue\lib\main.dart}
[   +4 ms] compiling dart code to kernel with command "C:\tools\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\tools\flutter\bin\cache\dart-sdk\bin\snapshots\dart2js.dart.snapshot
--platform-binaries=C:\tools\flutter\bin\cache\flutter_web_sdk\kernel --invoker=flutter_tool -Ddart.vm.profile=true
-DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d/
--native-null-assertions -o
C:\Users\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\app.dill
--packages=.dart_tool/package_config.json --cfe-only
C:\Users\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\main.dart"
[   +1 ms] web_static_assets: Complete
[+32237 ms] dart2js: Complete
[ +185 ms] web_release_bundle: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Users\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\main.dart.js,C:\Users\Dm
ytro\Desktop\flutter_constructors_issue\lib\main.dart,C:\Users\Dmytro\Desktop\flutter_constructors_issue\build\web\main.dart.js,build
\web\index.html, InvalidatedReasonKind.outputChanged: The following outputs have updated contents:
C:\Users\Dmytro\Desktop\flutter_constructors_issue\.dart_tool\flutter_build\d7352a28f8ba080d976388abe0d0b1f0\main.dart.js}
[ +149 ms] shaderc command: [C:\tools\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --sksl, --iplr, --json,
--sl=build\web\assets\shaders/ink_sparkle.frag, --spirv=build\web\assets\shaders/ink_sparkle.frag.spirv,
--input=C:\tools\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag,
--include=C:\tools\flutter\packages\flutter\lib\src\material\shaders,
--include=C:\tools\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]
[ +370 ms] web_release_bundle: Complete
[ +862 ms] web_service_worker: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
build\web\index.html,build\web\main.dart.js,build\web\main.dart.js.map}
[ +223 ms] web_service_worker: Complete
[   +4 ms] Persisting file store
[   +9 ms] Done persisting file store
[  +26 ms] Compiling lib\main.dart for the Web... (completed in 34,6s)
[ +811 ms] [CHROME]:
[   +8 ms] [CHROME]: DevTools listening on ws://127.0.0.1:58652/devtools/browser/19bcd7b4-35f0-461b-9d8a-90455c294a5d
[ +331 ms]   To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.3, on Microsoft Windows [Version 10.0.22621.1848], locale uk-UA)
    • Flutter version 3.10.3 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (13 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at D:\Android\sdk\
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: D:\Program Files\JetBrains\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at D:\Program Files\JetBrains\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\Dmytro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.43

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-06-15 06:11
Thanks for the report. I can reproduce this issue on the latest Flutter channels as well. 

It seems the issue only occurs in `profile` and `release` modes. In `debug` mode, widget (`OutlinedButton`) is rendered well and no error from browser console.

| debug | profile | release |
| --------------- | --------------- | --------------- | 
✅ | ❌ | ❌ | 


<details>
<summary>Workaround sample code (as mentioned above)</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: TestWidget(
          buttonConstructor: ({required child, required onPressed}) {
            return OutlinedButton(onPressed: onPressed, child: child);
          },
        ),
      ),
    );
  }
}

typedef ButtonConstructor = Widget Function({
required VoidCallback onPressed,
required Widget child,
});

class TestWidget extends StatelessWidget {
  final ButtonConstructor buttonConstructor;

  const TestWidget({
    required this.buttonConstructor,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return buttonConstructor(
      onPressed: () {},
      child: const Text('test'),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (29 hours ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (5 available)
    • Pixel 3a (mobile)      • 964AY0WL20                               • android-arm64  • Android 12 (API 32)
    • iPhone (mobile)        • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • iPhone 14 Pro (mobile) • 98082851-A0C4-4E39-A310-21C48B10A364     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-4.0.pre.84, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-4.0.pre.84 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3246808cd2 (3 hours ago), 2023-06-14 17:20:30 -0700
    • Engine revision 2d8d5ecfe4
    • Dart version 3.1.0 (build 3.1.0-206.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (5 available)
    • Pixel 3a (mobile)      • 964AY0WL20                               • android-arm64  • Android 12 (API 32)
    • iPhone (mobile)        • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • iPhone 14 Pro (mobile) • 98082851-A0C4-4E39-A310-21C48B10A364     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by ditman** [comment] 2023-06-15 18:47
If this does not happen in `debug`, but it does happen in `profile` and `release`, this may be a difference between `DDC` (debug) and `dart2js` (profile and release).

(Adding `dependency:dart` and paging maybe @elliette?)

**Comment by jason-simmons** [comment] 2023-06-19 22:52
This seems to be related to handling of super initializer syntax in `dart2js`.

The code sample works as intended if I replace the `OutlinedButton` constructor in https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/outlined_button.dart with a version that explicitly invokes the super constructor instead of using super initializers:

```
  const OutlinedButton({
    Key? key,
    required VoidCallback? onPressed,
    VoidCallback? onLongPress,
    ValueChanged<bool>? onHover,
    ValueChanged<bool>? onFocusChange,
    ButtonStyle? style,
    FocusNode? focusNode,
    bool autofocus = false,
    Clip clipBehavior = Clip.none,
    MaterialStatesController? statesController,
    required Widget child,
  }) : super(
    key: key,
    onPressed: onPressed,
    onLongPress: onLongPress,
    onHover: onHover,
    onFocusChange: onFocusChange,
    style: style,
    focusNode: focusNode,
    autofocus: autofocus,
    clipBehavior: clipBehavior,
    statesController: statesController,
    child: child,
  );
```

@sigmundch Can someone take a look at this?

**Comment by sigmundch** [comment] 2023-06-22 18:56
Thanks for the issue and the small reproduction. Thanks @jason-simmons for the clear culprit here!

I started isolating this further, it seems the error is specifically on the lowering for tearoffs of constructors that contain super initializers with a value. I managed to create an isolated repro and filed https://github.com/dart-lang/sdk/issues/52763 to track this.

Feel free to close this and use the other bug for primary tracking if you like.

**Comment by ditman** [comment] 2023-06-22 23:42
Thangs @sigmundch! I'll keep an eye on the dart-lang issue, and attempt to close this one when the dart fix flows through to flutter/flutter master channel!

**Comment by ditman** [comment] 2023-07-13 23:20
A fix for this has landed in the dart sdk:

* https://github.com/dart-lang/sdk/commit/6d56a75dca717b7db7197ce35ff2405aefe9a99b

**Comment by mitryp** [comment] 2023-07-14 13:23
Thanks, I couldn't reproduce the issue on the latest `master` branch version in DartPad

**Comment by ditman** [comment] 2023-07-14 18:25
Let's close this one as fixed then, thanks @mitryp for reporting!

**Closed by ditman** 2023-07-14 18:25 UTC
Labels: c: crash, framework, engine, dependency: dart, platform-web, has reproducible steps, P2, workaround available, found in release: 3.10, found in release: 3.12, team-web, triaged-web, multiteam-retriage-candidate
