### ISSUE TITLE
Impeller - Refresh indicator leaves dot mark if used on top of ImageFiltered (iOS)

### ISSUE THREAD

**Issue by Priyankkjain** [flutter/flutter#141959] opened 2024-01-22 10:44 UTC
### Steps to reproduce

Hi, I am facing an issue with the Impeller rendering engine in iOS. If a refresh indicator is used on top of **ImageFiltered**, it leaves a square or round black dot in place of the refresh indicator. The refresh indicator is visible and once it is gone the black dot appears in place of the refresh indicator. If the impeller is turned off and we run the same example. It does not leave the square or round black dot in place of the refresh indicator. I have attached a few videos regarding this.  The issue only appears if we have **ImageFiltered** widget below the refresh indicator. Without **ImageFiltered** in Impeller it works fine and as expected. 

### Expected results

The black square or round dot should not appear in place of the refresh indicator.

### Actual results

The black square or round dot appears in place of the refresh indicator.

### Code sample

<details open><summary>Code sample</summary>

```dart
RefreshIndicator.adaptive(
      onRefresh: store.updateUserData,
      child: SingleChildScrollView(
        physics: const AlwaysScrollableScrollPhysics(
          parent: ClampingScrollPhysics(),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ClipRRect(
              child: ImageFiltered(
                imageFilter: ImageFilter.blur(
                  sigmaX: 20,
                  sigmaY: 20,
                  //added Tile Mode for the flickering issue while scrolling
                  tileMode: TileMode.mirror,
                ),
                child: Image.network(
                  'https://picsum.photos/200/300',
                  height: 300,
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: AppConstants.commonHorizontalPadding,
              ),
              child: ListView.builder(
                shrinkWrap: true,
                padding: EdgeInsets.zero,
                physics: const NeverScrollableScrollPhysics(),
                itemBuilder: (_, index) => const SizedBox(
                  height: 70,
                  child: ColoredBox(color: AppColors.pinkBg),
                ),
                itemCount: 10,
              ),
            ),
            const SizedBox(
              height: 16,
            ),
          ],
        ),
      ),
    )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/20212314/782e9dd4-9112-4551-b179-b98411b657dd

https://github.com/flutter/flutter/assets/20212314/6a9fc457-d620-4dbc-9f34-8782f2c59fb2

https://github.com/flutter/flutter/assets/20212314/17700a5e-91ea-4643-bf78-f1f5f932222a
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.4.1 22F770820d darwin-arm64, locale en-IN)
    • Flutter version 3.13.9 on channel stable at /Users/priyank/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/priyank/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Users/priyank/Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/priyank/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/priyank/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Users/priyank/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9011.34/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Users/priyank/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/232.8660.185/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • SF-MOB-171 (mobile) • 00008110-001E45192684401E • ios            • iOS 16.2 20C65
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment] 2024-01-22 13:27
Hi @Priyankkjain, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.16.8) to see if you still experience this issue. 

If you do, please provide the updated output of `flutter doctor -v` along with a complete runnable minimal reproducible code sample so that we can investigate this issue. 

Thank you

**Comment by danagbemava-nc** [comment] 2024-01-24 07:21
Hi @Priyankkjain, I could not reproduce the "dot" when I tested on stable (although the pixelated square where the indicator was dragged was present). However, when I tested on master, the pixelated square is no longer there. Can you test on master to see if you still experience this issue over there?

**Comment by Priyankkjain** [comment] 2024-01-28 12:17
Hi @danagbemava-nc , I have checked it and it seems that the issue is not reproducing if I run it from the **master**. It is working correctly. If possible can you please tell me in which version this change is going to be included? Thank you for your help.

**Comment by danagbemava-nc** [comment] 2024-01-29 06:40
Hi @Priyankkjain, I just checked the `beta` channel as well and it seems like the fix is there, so with any luck, it should be in the next stable version. 

Per our triage policy, I'll be closing this since the issue has already been fixed on the master channel. 

Thank you

**Closed by danagbemava-nc** 2024-01-29 06:40 UTC
Labels: in triage
