### ISSUE TITLE
auto correct shows at left top at iPad

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#48262] opened 2020-01-06 20:30 UTC
## Steps to Reproduce
I checked in iPad(iOS) emulator.

1. change device lang to "japan"
2. select keyboard "日本語（かな）"
3. input "きょう"(in english "kyou") in textfield
4. auto correct show at left top possition

**Target Platform:**
iOS

**Target OS version/browser:**
iOS 13.3

**Devices:**
iPad Pro(12.9-inch)(3rd generation)

## Logs
I paste capture here 
![名称未設定](https://user-images.githubusercontent.com/7422251/71846809-c99c7a80-310e-11ea-89bb-b6bd15bb153f.png)

```
 flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale ja-JP)
  • Flutter version 1.12.13+hotfix.5 at /Users/user/Desktop/development/flutter
  • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
  • Engine revision 2994f7e1e6
  • Dart version 2.7.0
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
  • Android SDK at /Users/user/Library/Android/sdk
  • Android NDK location not configured (optional; useful for native profiling support)
  • Platform android-29, build-tools 29.0.2
  • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
  • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
  • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Xcode 11.3, Build version 11C29
  • CocoaPods version 1.8.4
[✓] Android Studio (version 3.5)
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin version 42.1.1
  • Dart plugin version 191.8593
  • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
[!] Connected device
  ! No devices available
```

**Comment by LongCatIsLooong** [comment] 2020-01-07 01:53
This is what it is supposed to look like: 

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-01-06 at 17 34 23](https://user-images.githubusercontent.com/31859944/71861856-a7721080-30ac-11ea-96a4-009baaed0cd4.png)

For the record I think it's part of the IME interface rather than autocorrection. It seems in this particular case we can't just return `CGRectZero`in `func firstRect(for range: UITextRange) -> CGRect
`.

**Comment by hatano0x06** [comment] 2020-04-04 13:25
Is there something update about this?

**Comment by LongCatIsLooong** [comment] 2020-04-17 17:42
Duplicate of #9344.

**Closed by LongCatIsLooong** 2020-04-17 17:42 UTC
Labels: a: internationalization, a: tablet, a: text input, f: cupertino, framework, platform-ios
