### ISSUE TITLE
Crash on LInux, seems related to PictureRecorder

### ISSUE THREAD

**Issue by zathras** [flutter/flutter#148364] opened 2024-05-14 23:50 UTC
### Steps to reproduce

Run the program at https://github.com/sgehrman/to_image_bug on Linux, and press either of the two buttons.  Tried on MacOS (with flutter 3.19.6 and with flutter 3.22.0), and it did not crash.

Note that the results do not vary when using a different SVG rendering library.

Originally reported to me at https://github.com/zathras/jovial_svg/issues/96

### Expected results

After warnings from loading the SVG asset, should print out encoded image size to stdout

### Actual results

After the SVG warnings a prrinted, no output --  program terminates abruptly.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:jovial_svg/jovial_svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<Uint8List> _useJovial() async {
    final si = await ScalableImage.fromSvgHttpUrl(
        Uri.parse('https://docs.gtk.org/gtk3/gtk-logo.svg'));

    await si.prepareImages();
    final vpSize = si.viewport;
    final recorder = PictureRecorder();
    final Canvas c = Canvas(recorder);

    si.paint(c);
    si.unprepareImages();

    final Picture pict = recorder.endRecording();
    final rendered =
        await pict.toImage(vpSize.width.round(), vpSize.height.round());

    final ByteData? bd = await rendered.toByteData(format: ImageByteFormat.png);
    final r = Uint8List.fromList(bd!.buffer.asUint8List());

    rendered.dispose();
    pict.dispose();

    print(r.length);

    return r;
  }

  Future<Uint8List> _useFlutterSvg() async {
    final PictureInfo pictureInfo = await vg.loadPicture(
      const SvgNetworkLoader('https://docs.gtk.org/gtk3/gtk-logo.svg'),
      null,
      onError: (error, stackTrace) {
        print(error);
        print(stackTrace);
      },
    );

    final recorder = PictureRecorder();
    final Canvas c = Canvas(recorder);

    c.drawPicture(pictureInfo.picture);
    pictureInfo.picture.dispose();

    final Picture pict = recorder.endRecording();
    final rendered = await pict.toImage(
        pictureInfo.size.width.toInt(), pictureInfo.size.height.toInt());

    final ByteData? bd = await rendered.toByteData(format: ImageByteFormat.png);
    final r = Uint8List.fromList(bd!.buffer.asUint8List());

    rendered.dispose();
    pict.dispose();

    print(r.length);

    return r;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Crashes on Flutter 3.22 Linux, but not Web.\nI did not test Windows or macOS',
              style: TextStyle(fontSize: 22),
            ),
            const SizedBox(height: 40),
            ElevatedButton(
                onPressed: _useJovial, child: const Text('Crash #1')),
            const SizedBox(height: 20),
            ElevatedButton(
                onPressed: _useFlutterSvg, child: const Text('Crash #2')),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Unable to produce logs -- "flutter logs" hangs
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
billf@Zathras:~/tmp/tmp/to_image_bug$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on Ubuntu 22.04.4 LTS 6.5.0-25-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by azkadev** [comment] 2024-05-15 01:19
i also experienced this bug

**Comment by azkadev** [comment] 2024-05-15 01:21
I tried screenshotting/exporting the widget into an image then the application closed itself

**Comment by danagbemava-nc** [comment] 2024-05-15 10:57
Hi @zathras, @azkadev I can't seem to reproduce the issue. See the recording below. Is there any other steps I need to take to reproduce the issue? 

[Screencast from 05-15-2024 10_52_10 AM.webm](https://github.com/flutter/flutter/assets/88313112/0dc8d27a-3cc0-4984-9374-74042613c793)

**Comment by azkadev** [comment] 2024-05-15 12:24
I have tested exporting the widget to image/png, but when I tried the image widget with a container it was successful but when I added borderRadius when the export became an image it immediately came out

```dart

        Padding(
          padding: const EdgeInsets.all(10),
          child: RepaintBoundary(
            key: globalKey,
            child: SizedBox(
              width: 720,
              child: Container(
                width: 50,
                height: 50,
                decoration: BoxDecoration(

                  borderRadius: BorderRadius.circular(15), // if this delete i can save this widget to image/png
                  image: DecorationImage(
                    image: Image.file(
                      File("/home/galaxeus/Documents/galaxeus/app/github_sponsor/package/github_sponsor_flutter/logo/_5c2f2b79-7f2f-4820-a32e-8c1882d8b52d.jpeg"),
                    ).image,
                  ),
                ),
                // clipBehavior: Clip.antiAlias,
              ),
            ),
          ),
        ),

```
## Operating system

```json
{
    "OS": "Ubuntu 24.04 LTS x86_64",
    "Host": "Modern 14 B5M REV:1.0",
    "Kernel": "6.8.0-31-generic",
    "Uptime": "1 hour, 15 mins",
    "Packages": "2017 (dpkg), 8 (snap)",
    "Shell": "zsh 5.9",
    "Resolution": "1920x1080",
    "DE": "GNOME 46.0",
    "WM": "Mutter",
    "WM Theme": "WhiteSur-Dark",
    "Theme": "WhiteSur-Dark [GTK2/3]",
    "Icons": "BigSur-Originals [GTK2/3]",
    "Terminal": "gnome-terminal",
    "CPU": "AMD Ryzen 5 5500U with Radeon Graphics (12) @ 4.056GHz",
    "GPU": "AMD ATI 03:00.0   Lucienne",
    "GPU": "AMD ATI 03:00.0 Lucienne",
    "Memory": "8161MiB / 15346MiB",
    "Version": "7.1.0"
}
```

## Flutter Version

```bash
Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (6 days ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3
```

**Comment by zathras** [comment] 2024-05-15 14:27
On the program I forwarded, no, no more steps.

The Linux machine I reproduced on was running the current stable Ubuntu linux, FWIW.

**Comment by danagbemava-nc** [comment] 2024-05-16 06:10
Hi @azkadev, can you please provide the full reproducible code sample?

**Comment by zathras** [comment] 2024-05-17 23:30
@danagbemava-nc, I have been told that this [also] reproduces the problem on Linux.  (Taken from https://github.com/sgehrman/linux_crash_322 ; cf. https://github.com/SachinGanesh/screenshot/issues/185)
```
import 'package:flutter/material.dart';
import 'package:screenshot/screenshot.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Screenshot Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  ScreenshotController screenshotController = ScreenshotController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Screenshot(
              controller: screenshotController,
              child: Container(
                clipBehavior: Clip.antiAlias,
                padding: const EdgeInsets.all(30.0),
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.blueAccent, width: 5.0),
                  color: Colors.amberAccent,
                  // =============================================
                  // NOTE: BorderRadius makes it crash on Linux, comment out and it won't crash
                  // Flutter 3.22 has serious crashing bugs on linux
                  borderRadius: BorderRadius.circular(15),
                  // =============================================
                ),
                child: Image.asset(
                  'assets/images/flutter.png',
                ),
              ),
            ),
            const SizedBox(
              height: 25,
            ),
            ElevatedButton(
              child: const Text(
                'Capture',
              ),
              onPressed: () {
                screenshotController
                    .capture(delay: const Duration(milliseconds: 10))
                    .then((capturedImage) async {
                  print(capturedImage?.length);
                }).catchError((onError) {
                  print(onError);
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by zathras** [comment] 2024-05-17 23:33
@danagbemava-nc BTW, what is your `flutter doctor` output?  Is your environment different than mine?  This seems like the sort of native memory corruption that's prone to being a Heisenbug...

**Comment by danagbemava-nc** [comment] 2024-05-20 06:17
Hi @zathras, I tested on ubuntu 22.04.4 with stable 3.22.0.  I also tested with the code sample in https://github.com/flutter/flutter/issues/148364#issuecomment-2118486693 but it does not crash for me. Were you able to reproduce with this code sample?

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.22.0, on Ubuntu 22.04.4 LTS 6.5.0-28-generic, locale en_US.UTF-8)
    • Flutter version 3.22.0 on channel stable at /home/daniel/fvm/versions/stable
    ! Warning: `dart` on your path resolves to /home/linuxbrew/.linuxbrew/Cellar/dart/3.2.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /home/daniel/fvm/versions/stable. Consider adding /home/daniel/fvm/versions/stable/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (11 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/daniel/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/daniel/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2
[✓] Android Studio (version 2023.1)
    • Android Studio at /home/daniel/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
[✓] VS Code (version 1.87.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.88.0
[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-28-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.91
[✓] Network resources
    • All expected network resources are available.
! Doctor found issues in 1 category.
```
</details>

**Comment by zathras** [comment] 2024-05-20 17:30
> Were you able to reproduce with this code sample?

OK, I turned on my Linux machine, and yes.  I don't see any obvious differences in platform from your `flutter doctor` output, either.

Oh, this is interesting:  Just to be sure, I let Ubuntu apply software updates, rebooted, and ran the program.  That time, it didn't crash until I pressed the button for the third time.  I tried running a couple more times, and each time it crashed on the first try.  Then, I rebooted again.  Same thing:  It took three tries to get the crash on the first run; crashes the first time on subsequent runs.

So, definitely heisenbug territory here.  Maybe try pressing the "capture" button multiple times?  And, if that doesn't work, maybe write a loop (after rewriting it as normal async code, of course) to call it 100,000 times or something?

My Linux laptop is about eight years old, and only has 8 GB of RAM; maybe some part of the stack is trying to be a little more frugal with memory than on your machine?  For example, maybe the memory is a little less likely to arrive zeroed-out on my machine?

Also, you're welcome to contact [https://github.com/sgehrman](https://github.com/sgehrman/linux_crash_322), who (mistakenly) submitted this issue to me against a library I maintain.  Apparently he's been banned from submitting bugs to Flutter?  He is, ah, rather prone to hyperbole, but in this case it does look like it's a real bug.

FWIW, I put a print  statement in the  code, just to be sure where the crash was happening.  I launch the program, press the "capture" button, and get the "Lost connection to device":

```
billf@Zathras:~/tmp/tmp/linux_crash_322$ flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
âœ“ Built build/linux/x64/debug/bundle/example
Syncing files to device Linux...                                   141ms

Flutter run key commands.
r Hot reload. ðŸ”¥ðŸ”¥ðŸ”¥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Linux is available at: http://127.0.0.1:41197/yGpT6v1NYos=/
The Flutter DevTools debugger and profiler on Linux is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:41197/yGpT6v1NYos=/
flutter: About to call screenshotController
Lost connection to device.
billf@Zathras:~/tmp/tmp/linux_crash_322$ git diff lib/main.dart
diff --git a/lib/main.dart b/lib/main.dart
index a27c61a..a1f7596 100644
--- a/lib/main.dart
+++ b/lib/main.dart
@@ -64,11 +64,14 @@ class _MyHomePageState extends State<MyHomePage> {
                 'Capture',
               ),
               onPressed: () {
+                print('About to call screenshotController');
                 screenshotController
                     .capture(delay: const Duration(milliseconds: 10))
                     .then((capturedImage) async {
+                  print('Called screenshotController');
                   print(capturedImage?.length);
                 }).catchError((onError) {
+                  print('Error from screenshotController');
                   print(onError);
                 });
               },
billf@Zathras:~/tmp/tmp/linux_crash_322$ 
```

**Comment by danagbemava-nc** [comment] 2024-05-21 08:44
Hi @zathras, can you check on the master channel to see if you're still able to reproduce the crash? One of my colleagues was able to repro on stable but not on the master channel.

**Comment by zathras** [comment] 2024-05-21 13:28
@danagbemava-nc  Maybe you could reach out to one of the original submitters, @askadev or [https://github.com/sgehrman](https://github.com/sgehrman/linux_crash_322).

**Comment by danagbemava-nc** [comment] 2024-05-21 13:33
@azkadev, can you check on the `master` channel to see if this reproduces there as well?

**Comment by otmi100** [comment] 2024-06-03 07:25
Came here because I ran into that problem as well. 

Can confirm the following on my machine:

**Crash** on:
[✓] Flutter (Channel stable, 3.22.1, on Arch Linux 6.9.2-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.22.1 on channel stable at /home/mitch/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (12 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3 

**Works** on:
[✓] Flutter (Channel master, 3.23.0-13.0.pre.69, on Arch Linux 6.9.2-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.23.0-13.0.pre.69 on channel master at /home/mitch/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 124aacbaef (2 days ago), 2024-05-31 22:32:25 -0400
    • Engine revision d81edf635a
    • Dart version 3.5.0 (build 3.5.0-214.0.dev)
    • DevTools version 2.36.0

Guess I'll skip 3.22 :)

**Comment by jason-simmons** [comment] 2024-06-06 00:05
This was fixed by https://github.com/flutter/engine/commit/bbe63afc7bb65211edfd16b0f65829c3da6413b9

**Comment by danagbemava-nc** [comment] 2024-06-12 07:44
Closing this based on https://github.com/flutter/flutter/issues/148364#issuecomment-2151147502

**Closed by danagbemava-nc** 2024-06-12 07:44 UTC
Labels: waiting for customer response, in triage
