### ISSUE TITLE
Unexpectedly transparent container in web.

### ISSUE THREAD

**Issue by stuz5000** [flutter/flutter#49723] opened 2020-01-29 19:42 UTC
The following code renders differently on web vs the mobile emulator. In particular, the Containers  who's background is set to a non-transparent color comes out transparent on the web, but not mobile.

**android emulator**: ![Screenshot from 2020-01-29 10-26-16](https://user-images.githubusercontent.com/7799980/73391012-0e3db080-428c-11ea-95c7-2eb05f6e646f.png)

**chrome**: ![Screenshot from 2020-01-29 10-25-38](https://user-images.githubusercontent.com/7799980/73391013-0e3db080-428c-11ea-951b-73ea59e1b3e2.png)

```
import 'package:flutter/material.dart';

// The background color of the badges.
const Color DEFAULT_BADGE_COLOR = Color.fromARGB(255, 109, 207, 214);

class DemoApp extends StatelessWidget {
  DemoApp();

  @override
  Widget build(BuildContext context) =>
      MaterialApp(title: 'Flutter Playground', home: Scaffold(body:content()));


  Text colorText(String text, Color color, {double size: 10}) => Text.rich(
    TextSpan(
        text: text,
        style: TextStyle(
          fontSize: size,
          fontFamily: "Poppins",
          color: color,
        )),
    overflow: TextOverflow.ellipsis,
    maxLines: 1,
    softWrap: false,
  );

  Widget badge(String text, {Color color: DEFAULT_BADGE_COLOR,
    Color textColor: Colors.white,
    double textSize: 30,
    hInpadding: 0.4,
    vInpadding: 0}) =>
      Container(
        child: colorText(text, textColor, size: textSize),
        padding: EdgeInsets.fromLTRB(
            textSize * hInpadding,
            textSize * vInpadding,
            textSize * hInpadding,
            textSize * vInpadding),
        decoration: new BoxDecoration(
            color: color,
            borderRadius:
            new BorderRadius.all(new Radius.circular(textSize * 10))),
      );

  Widget content() =>
      Center(child: SizedBox(width:200, height:200, child:Stack(children:[
        Positioned(top:0, left:0, child:badge("ABCDEFG")),
        Positioned(top:10, left:10, child:badge("ABCDEFG")),
        Positioned(top:20, left:20, child:badge("ABCDEFG")),
      ])));

}

main()=>runApp(DemoApp());
```

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.14.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.14.6 at /home/sir/development/flutter
    • Framework revision fabeb2a16f (27 hours ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/sir/Android/Sdk
    • Java binary at: /home/sir/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/sir/soft/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /snap/intellij-idea-ultimate/198
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome
      76.0.3809.132
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!

```

**Comment by stuz5000** [comment] 2020-01-29 19:45
Also, adding a Material around the container:
```
Widget badge(String text, {Color color: DEFAULT_BADGE_COLOR,
    Color textColor: Colors.white,
    double textSize: 30,
    hInpadding: 0.4,
    vInpadding: 0}) =>
      Material(child:Container(     /// <<<<< Added Material(child:
        child: colorText(text, textColor, size: textSize),
        padding: EdgeInsets.fromLTRB(
            textSize * hInpadding,
            textSize * vInpadding,
            textSize * hInpadding,
            textSize * vInpadding),
        decoration: new BoxDecoration(
            color: color,
            borderRadius:
            new BorderRadius.all(new Radius.circular(textSize * 10))),
      )      );
```
...gets non-transparent corners:

![image](https://user-images.githubusercontent.com/7799980/73391362-a63b9a00-428c-11ea-9dce-0e43346ea3bb.png)

**Comment by TahaTesser** [comment] 2020-11-10 15:30
Hi @stuz5000 
Can't reproduce this on the latest`master` on the web on desktop or mobile 

<img width="263" alt="Screenshot 2020-11-10 at 8 58 16 PM" src="https://user-images.githubusercontent.com/48603081/98694523-8e568200-2397-11eb-9530-41ef052b0f50.png">


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

// The background color of the badges.
const Color DEFAULT_BADGE_COLOR = Color.fromARGB(255, 109, 207, 214);

class DemoApp extends StatelessWidget {
  DemoApp();

  @override
  Widget build(BuildContext context) =>
      MaterialApp(title: 'Flutter Playground', home: Scaffold(body: content()));

  Text colorText(String text, Color color, {double size: 10}) => Text.rich(
        TextSpan(
            text: text,
            style: TextStyle(
              fontSize: size,
              fontFamily: "Poppins",
              color: color,
            )),
        overflow: TextOverflow.ellipsis,
        maxLines: 1,
        softWrap: false,
      );

  Widget badge(String text,
          {Color color: DEFAULT_BADGE_COLOR,
          Color textColor: Colors.white,
          double textSize: 30,
          hInpadding: 0.4,
          vInpadding: 0}) =>
      Container(
        child: colorText(text, textColor, size: textSize),
        padding: EdgeInsets.fromLTRB(
            textSize * hInpadding,
            textSize * vInpadding,
            textSize * hInpadding,
            textSize * vInpadding),
        decoration: new BoxDecoration(
            color: color,
            borderRadius:
                new BorderRadius.all(new Radius.circular(textSize * 10))),
      );

  Widget content() => Center(
      child: SizedBox(
          width: 200,
          height: 200,
          child: Stack(children: [
            Positioned(top: 0, left: 0, child: badge("ABCDEFG")),
            Positioned(top: 10, left: 10, child: badge("ABCDEFG")),
            Positioned(top: 20, left: 20, child: badge("ABCDEFG")),
          ])));
}

main() => runApp(DemoApp());

```

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.179, on Mac OS X 10.15.7 19H15
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.179 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision a90880a8c3 (2 hours ago), 2020-11-10 05:02:56 -0800
    • Engine revision e50ac2c552
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/SanDisk/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.2
    • macOS (desktop)      • macos                     • darwin-x64     • Mac OS
      X 10.15.7 19H15 darwin-x64
    • Web Server (web)     • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 86.0.4240.183

• No issues found!

```

</details>

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-10 15:30 UTC
Labels: P4, a: typography, engine, platform-web, severe: rendering

**Comment by stuz5000** [comment] 2020-11-10 17:31
> Hi @stuz5000
> Can't reproduce this on the latest`master` on the web on desktop or mobile

Is now also fixed for me. Thank you.
