### ISSUE TITLE
Hot Restart not updating changes on web

### ISSUE THREAD

**Issue by devfemibadmus** [flutter/flutter#142335] opened 2024-01-26 20:36 UTC
### Steps to reproduce

1. Create a new Flutter project 
2. Implement a web application within the project.
3. Make changes to the code.
4. Execute a hot restart using the command flutter run -d web.
5. Observe that the changes are not reflected on the web.

### Expected results

After performing a hot restart (`flutter run -d web`), the web application should update and reflect the recent changes made to the code.

### Actual results

The hot restart does not update the changes on the web, and the application continues to display the previous version of the code.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _currentIndex = 0;

  final List<Widget> _tabs = [
    TabOne(),
    TabTwo(),
    TabThree(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Bottom Tab Bar Example'),
      ),
      body: _tabs[_currentIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        onTap: (index) {
          setState(() {
            _currentIndex = index;
          });
        },
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Tab 1',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            label: 'Tab 2',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: 'Tab 3',
          ),
        ],
      ),
    );
  }
}

class TabOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Tab 1 Content'),
    );
  }
}

class TabTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Tab 2 Content'),
    );
  }
}

class TabThree extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Tab 3 Content'),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
Performing hot restart...                                          426ms
Restarted application in 431ms.

Performing hot restart...                                        1,450ms
Restarted application in 1,451ms.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel beta, 3.19.0-0.2.pre, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
  • Flutter version 3.19.0-0.2.pre on channel beta at C:\Users\devfe\Downloads\flutter_windows\flutter
  • Upstream repository https://github.com/flutter/flutter.git
  • Framework revision c1df7d07ac (9 days ago), 2024-01-17 15:42:07 -0800
  • Engine revision 4f18bb4dcb
  • Dart version 3.3.0 (build 3.3.0-279.0.dev)
  • DevTools version 2.31.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
  • Android SDK at C:\Users\devfe\AppData\Local\Android\sdk
  • Platform android-34, build-tools 33.0.0
  • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
  • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
  • All Android licenses accepted.

[√] Chrome - develop for the web
  • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.3.4)
  • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
  • Visual Studio Enterprise 2022 version 17.3.32901.215
  • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.2)
  • Android Studio at C:\Program Files\Android\Android Studio
  • Flutter plugin can be installed from:
    https://plugins.jetbrains.com/plugin/9212-flutter
  • Dart plugin can be installed from:
    https://plugins.jetbrains.com/plugin/6351-dart
  • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.85.2)
  • VS Code at C:\Program Files\Microsoft VS Code
  • Flutter extension version 3.80.0

[√] Connected device (3 available)
  • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
  • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.225
  • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.144

[√] Network resources
  • All expected network resources are available.
  • No issues found!

```

</details>

**Comment by devfemibadmus** [comment] 2024-01-26 20:41
Hot restart changes were updating/reflecting changes on web fine in my old flutter version

**Comment by dam-ease** [comment] 2024-01-29 07:09
Hello @devfemibadmus 
Thanks for filing this. I see you are on the beta channel and this is a known issue which has been fixed https://github.com/flutter/flutter/issues/141588.
Closing as a duplicate of that issue.

**Closed by dam-ease** 2024-01-29 07:09 UTC
Labels: in triage
