### ISSUE TITLE
Issue with Camera plugin in release build

### ISSUE THREAD

**Issue by RohithKilaparthi** [flutter/flutter#68788] opened 2020-10-22 15:27 UTC
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'camera'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin camera could not be built due to the issue above.

**Comment by TahaTesser** [comment] 2020-10-22 16:34
hi @RohithKilaparthi 
Can you please provide your `flutter doctor -v` your `flutter run --release  --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by GauteHaugen** [comment] 2020-10-23 09:02
We are also experiencing a similar issue with our project. This happened sometime after 13th of October (When we had our last successful deploy). One fix that we have noticed, is to set the version of all flutter plugins to a version before the October 14th release (where compileSdkVersion and targetSdkVersion got bumped from 28 to 29). IOS builds also work, so this is an Android issue. So in our case, we set the version of these plugins back to a version that we knew worked:

- path_provider: ^1.6.11 -> 1.6.11
- url_launcher: ^5.5.0 -> 5.5.0
- file_picker: ^2.0.1+2 -> 2.0.1+2
- image_picker: ^0.6.7+11 -> 0.6.7+11
- camera: ^0.5.8+7 -> 0.5.8+7
- device: ^0.4.2+8 -> 0.4.2+8

This solved our issue, but we would like to still use the latest version of the packages that we use.
We have also tried to use the latest version before the 14th of October update for all these packages, that also worked.
We have also tried to update compileSdkVersion and targetSdkVersion to 29 in the file android/app/build.gradle for our app, without luck

<details><summary>Error message</summary>
Launching lib\main.dart on SM G975F in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\gaute.haugen\Documents\GithubProjects\flutter_appframe\appframe_filter\example\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
√ `android\settings_aar.gradle` created successfully.
Building plugin camera...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'camera'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: The plugin camera could not be built due to the issue above.
Exited (sigterm)
</details>

<details><summary>flutter doctor -v</summary>
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.1 at C:\flutter
    • Framework revision f30b7f4db9 (2 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
    • Android SDK at C:\Users\gaute.haugen\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\gaute.haugen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • SM G975F (mobile) •  • android-arm64 • Android 10 (API 29)    

• No issues found!
</details>

<details><summary>build.gradle</summary>
<pre>
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()

def keystorePropertiesFile = rootProject.file('key.properties')

if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "SomeUniqueName"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
</pre>
</details>

**Comment by pedromassangocode** [comment] 2020-11-13 12:04
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-13 12:04 UTC
Labels: in triage
