### ISSUE TITLE
new file opening issue

### ISSUE THREAD

**Issue by arunachaleshwaran** [flutter/flutter#32407] opened 2019-05-09 13:16 UTC
when I open the flutter application file like `flutter-master` from the GitHub but it not working while opening. it shows the errors like the flutter is not connected to flutter SDK. like `runApp()` not defined.
> resolved by
I comment out every dependency in the `.yaml` file. then it didn't show any error. then one by one I remove the comments and run `futter package get` then it shows no error and runs perfectly.

**Comment by tvolkert** [comment] 2019-05-09 15:45
It's not clear from the description what the issue is or whether you've since resolved it, so I'm going to close this issue.  Please feel free to re-open and add more info if this is still an issue for you!

**Closed by tvolkert** 2019-05-09 15:45 UTC

**Comment by arunachaleshwaran** [comment] 2019-05-13 09:51
i fell that is like a bug i will reach out to you when i download new flutter files
