### ISSUE TITLE
Flutter bug in mobile web

### ISSUE THREAD

**Issue by steeling** [flutter/flutter#82734] opened 2021-05-17 20:03 UTC
Not sure where this is happening, but it's difficult to debug...

I have a flutter app that runs fine on android, ios, and web, **except** on mobile web (on an ios device). If I request the mobile site on chrome or on safari on my laptop it works fine, but specfically requesting the site (even desktop version) from an iPhone, it breaks with an "IndexSizeError: The index is not in the allowed range."

Even more difficult is that even with the unminified version it doesn't print the stack trace, instead the error is getting console.log'd, and the line just prints there.

It's then followed by 2 more errors "Another exception was thrown: Instance of 'ErrorSummary'"

I'm guessing it's an error specfic to webkit, possibly in one of my dependencies. It would be nice if I could deploy in debug mode from flutter to the simulator's Safari, to be able to debug this better, or if an error was thrown instead of just printed, or print the stack trace at least

**Comment by steeling** [comment] 2021-05-17 22:42
Best way to run this is on a mac:

1. Run the web app `flutter run -d chrome --web-port=8090 --debug`
2. Open the Safari on the iOS simulator, and visit `localhost:8090`
3. From Safari on your mac, enable the [develop menu](https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac)
4. On Safari on your mac, Develop > Simulator > localhost:8090
5. Refresh the page on your simulator's safari.
6. Visit the "console" tab on the Safari developer tools to see the error.

**Comment by TahaTesser** [comment] 2021-05-18 11:08
Hi @steeling 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by steeling** [comment] 2021-05-18 17:59
Can mark this as a duplicate of 82748

**Comment by TahaTesser** [comment] 2021-05-19 06:54
duplicate of https://github.com/flutter/flutter/issues/82748

**Closed by TahaTesser** 2021-05-19 06:54 UTC
Labels: in triage
