### ISSUE TITLE
[google_maps_flutter] Indoor navigation doesn't work on Android

### ISSUE THREAD

**Issue by mahmoudatef925** [flutter/flutter#57951] opened 2020-05-25 16:22 UTC
![Capture](https://user-images.githubusercontent.com/36286101/82829886-a4898800-9eb4-11ea-92d1-3aeaf967eba4.PNG)

i want to show this view in my application but i can't

**Comment by mahmoudatef925** [comment] 2020-05-25 16:25
view in my app 
![Screenshot_1590423776](https://user-images.githubusercontent.com/36286101/82829959-d00c7280-9eb4-11ea-86ac-a4ce9aacce98.png)
and my code
```GoogleMap(
                  mapType: MapType.normal,
                  scrollGesturesEnabled: true,
                  tiltGesturesEnabled: true,
                  trafficEnabled: false,
                  indoorViewEnabled: true,
                  compassEnabled: true,
                  rotateGesturesEnabled: true,
                  myLocationEnabled: true,
                  initialCameraPosition: _con.cameraPosition,
                  markers: Set.from(_con.allMarkers),
                  mapToolbarEnabled: true,
                  onMapCreated: (GoogleMapController controller) {
                    print("BEFORE COMPLETE");
                    _con.mapController.complete(controller);
                    print("AFTER COMPLETE");
                  },
                  onCameraMove: (CameraPosition cameraPosition) {
                    _con.cameraPosition = cameraPosition;
                  },
                ),

**Comment by VladyslavBondarenko** [comment] 2020-05-26 10:21
Reproduced with google_maps_flutter 0.5.28+1

<details>
 <summary>complete code sample with camera positioned on the building</summary>

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(40.750298, -73.993324),
    zoom: 17,
  );

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.normal,
        initialCameraPosition: _kGooglePlex,
        indoorViewEnabled: true,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
    );
  }
}
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
flutterd doctor -v
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • Redmi Note 7              • 6345c469      • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by mahmoudatef925** [comment] 2020-05-27 02:52
i tried your code but still same output, i'm on Channel beta, 1.18.0-11.1.pre 
could you show me screenshot from ur result ?

**Comment by mahmoudatef925** [comment] 2020-05-27 02:56
i tried your code but same output appear , i'm on Channel beta, 1.18.0-11.1.pre
could you show me screenshot from your output ?

**Comment by mahmoudatef925** [comment] 2020-05-27 02:59
> ![Capture](https://user-images.githubusercontent.com/36286101/82829886-a4898800-9eb4-11ea-92d1-3aeaf967eba4.PNG)
> 
> i want to show this view in my application but i can't

expected output

**Comment by VladyslavBondarenko** [comment] 2020-05-27 07:39
Yes, It's supported, but seems to be not for Android.

I can see the indoor navigation with iPhone 7 iOS 13.5.
But not with Redmi Note 7 Android 9 (API 28) or Android 10 (API 29) (emulator)

**Comment by jacek-marchwicki** [comment] 2021-02-08 15:54
I'm using a pretty old version of Google Maps Plugin (`google_maps_flutter: 0.5.33`) and with the version looks like the indoor maps are working only with the lite version on Android.

**Comment by jacek-marchwicki** [comment] 2021-02-08 17:44
I've tested my app with `google_maps_flutter: 1.2.0` and looks like the issue is fixed.

**Comment by TahaTesser** [comment] 2021-05-04 12:10
I can confirm the issue is fixed 

### Preview
| iOS | Android  |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/117001210-bb527480-acea-11eb-8d74-d74b77f624ac.png" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/117001218-bd1c3800-acea-11eb-9281-e8c5dc5af0e6.png" height="450" /> |


<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(40.750298, -73.993324),
    zoom: 17,
  );

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.normal,
        initialCameraPosition: _kGooglePlex,
        indoorViewEnabled: true,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
    );
  }
}
``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
```
		
</details>

Closing as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-04 12:10 UTC
Labels: found in release: 1.21, has reproducible steps, p: maps, platform-android, plugin
