### ISSUE TITLE
Fling-scrolling is slow unless you swipe precisely vertically

### ISSUE THREAD

**Issue by gnprice** [flutter/flutter#120345] opened 2023-02-09 07:49 UTC
When trying to scroll rapidly through a list, the fastest you can go is much slower if you swipe at an angle and not straight up or down: about 15%-30% less initial speed, and 20%-50% less total distance on a single fling, for a range of likely angles.

Swiping at an angle is the most natural motion for many ways of using a phone, especially when using the thumb to scroll. And Android native scrolling (*) does not share this behavior: swiping at an angle can reach the same top speeds as swiping precisely vertically. As a result, many users are accustomed to scrolling this way, and the way an app responds when they do is their primary experience of trying to scroll in the app.

((*) I mention Android because that's where I've tested. It's possible that iOS or other platforms share Flutter's behavior here, or Android's, or do something else.)

This is one of several issues that combine to produce user feedback that scrolling feels sluggish and unresponsive in the default scrolling behavior used on Android. The symptoms naturally blend together until you investigate closely, so here's the others I know of for cross-reference:
* Another 15% reduction in total fling distance, affecting many scrolling lists: #120338
* Another 7% reduction, affecting all kinds of scrollables: #119875
* A thread for the overall symptom of all three issues (and possibly others) combined: #16371

## Steps to Reproduce

1. Run the [`platform_tests/scroll_overlay`](https://github.com/flutter/platform_tests/tree/1d797b8699546f1178e3cf58de9c6cc64f825281/scroll_overlay) app on an Android device. (This may be the same on iOS and other platforms too, but I haven't yet tested that.)
2. In `lib/main.dart`, delete the line `itemCount: 1000,`, in order to avoid #120338. Reload.
3. Scroll with a fling gesture: swipe rapidly upward and release. Wait a couple of seconds for the scroll to come to a stop.
   * Swipe just once, and swipe as precisely straight upward as possible, just like with #119875.
4. Observe how far the scroll went, as shown by the numbered items in the Android- and Flutter-driven scrolling lists.

5. Scroll back to the top.
6. Repeat step 2, but this time swipe up at an angle. For example, swipe rapidly from about the lower-left corner of the screen to the upper-right corner.
   * You may find this a much more natural gesture than swiping straight upward, especially if you use your thumb. (At least it is for me, and others I've observed with this repro.)
7. Repeat step 3.

**Expected results:** 

Swiping at top speed should cause the list to scroll equally far whether you do it straight vertically up (which can be natural when using the index finger) or up at an angle (which is natural when using the thumb, and in many postures with the index finger.)

**Actual results:** 

The Flutter list scrolls much less far when swiping at an angle than it does when swiping straight up.

The Android list, on the other hand, scrolls the same distance in both cases, or nearly so. (If it doesn't, try again but swiping faster. There's a certain maximum fling distance no matter how hard you swipe, and it's the same whether straight up or at an angle. The total numbers may get slightly smaller at an angle, because they include the initial portion when your finger was still on the screen performing a drag, and that part is shorter when at an angle.)

Specifically:
* Swiping straight up, I see "Android 94" and "Flutter 90" at the top of the screen. (The remaining discrepancy in this case is #119875.)
* Swiping diagonally up at roughly a 30-degree angle from vertical (from about one corner to the opposite corner, on my phone in portrait mode), I see "Android 93" next to "Flutter 78".
* Swiping diagonally up at roughly a 45-degree angle, I see "Android 90" next to "Flutter 51".

This represents about a 19% reduction in the 30-degree case and a 56% reduction in the 45-degree case, compared to straight up. (By my calculations, using the fact that item N is 40+N logical pixels high.)

<details>
  <summary>Logs</summary>

```
$ flutter analyze
Analyzing scroll_overlay...                                             
No issues found! (ran in 0.8s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.8.0-8.0.pre.13, on Debian GNU/Linux 10 (buster) 4.19.0-23-amd64, locale en_US.UTF-8)
    • Flutter version 3.8.0-8.0.pre.13 on channel main at /home/greg/n/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2303f42250 (3 hours ago), 2023-02-08 14:24:12 -0500
    • Engine revision cc4ca6a06a
    • Dart version 3.0.0 (build 3.0.0-215.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/greg/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/greg/lib/android-studio-2020.3.1.24/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/greg/lib/android-studio-2020.3.1.24
    • Flutter plugin version 71.2.4
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 08171FDD40025F • android-arm64  • Android 13 (API 33)
    • Linux (desktop)  • linux          • linux-x64      • Debian GNU/Linux 10 (buster) 4.19.0-23-amd64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by gnprice** [comment] 2023-02-09 08:07
## Diagnosis

What's going on here is:
* Both Flutter and Android clamp the velocity to a certain maximum at the start of the fling.
  (And I haven't yet investigated what iOS does.)
* The total distance the fling travels is a function of its starting velocity. That function isn't quite the same between Flutter and Android (that discrepancy is #119875), but it scales at the same rate: Flutter's distance is a consistent 7.2% less than Android's.
* They both use the same number for that maximum velocity: 8000 logical pixels per second.
* But they apply the maximum velocity in different ways.
* As a result:
  * On Android, swiping rapidly straight up or rapidly up at an angle will both produce a velocity of 8000 logical pixels per second, and a fling that goes the maximum distance.
  * But on Flutter, only swiping exactly straight up will do that.
    * Swiping at a 30-degree angle produces a velocity of about 6930 px/sec (13% reduced) and a total distance about 22% shorter than maximum.
    * Swiping at a 45-degree angle produces a velocity of about 5660 px/sec (29% reduced) and a total distance about 45% shorter than maximum.

Those two different versions of clamping to a maximum velocity are:


### Android

Android takes the velocity in each axis, x and y, and clamps each of them independently. From RecyclerView.java:
```java
                velocityX = Math.max(-mMaxFlingVelocity, Math.min(velocityX, mMaxFlingVelocity));
                velocityY = Math.max(-mMaxFlingVelocity, Math.min(velocityY, mMaxFlingVelocity));
                mViewFlinger.fling(velocityX, velocityY);
```

A few lines before that, in fact, it looks at which axes the view can scroll in, and zeroes out the velocity in any axis that won't scroll:
```java
        if (!canScrollHorizontal || Math.abs(velocityX) < mMinFlingVelocity) {
            velocityX = 0;
        }
        if (!canScrollVertical || Math.abs(velocityY) < mMinFlingVelocity) {
            velocityY = 0;
        }
        if (velocityX == 0 && velocityY == 0) {
            return false;
        }
```

For the case of a view that scrolls in only one axis, this produces the desirable behavior seen above.


### Flutter

The current version of Flutter takes the velocity as a two-dimensional vector, and clamps that to a maximum length. From DragGestureRecognizer._checkEnd (if I've correctly traced this up the call graph):
```dart
    final VelocityEstimate? estimate = tracker.getVelocityEstimate();
    if (estimate != null && isFlingGesture(estimate, tracker.kind)) {
      final Velocity velocity = Velocity(pixelsPerSecond: estimate.pixelsPerSecond)
        .clampMagnitude(minFlingVelocity ?? kMinFlingVelocity, maxFlingVelocity ?? kMaxFlingVelocity);
      details = DragEndDetails(
        velocity: velocity,
        primaryVelocity: _getPrimaryValueFromOffset(velocity.pixelsPerSecond),
      );
```

Here `estimate.pixelsPerSecond` is an Offset, so a 2-d vector, and `Velocity.clampMagnitude` clamps that to a maximum Euclidean length, as computed using the Pythagorean theorem.

Then the call to `_getPrimaryValueFromOffset`, which is abstract on `DragGestureRecognizer` and implemented by its subclasses, picks out the component of the remaining velocity that goes in the relevant axis. That's the part that `ScrollDragController.end` pays attention to, and passes on to `goBallistic`.

In the case of something that can scroll in two dimensions, this logic makes more sense than the Android logic and probably produces more natural behavior — it means that the maximum speed is always the same 8000 px/sec, in every direction, whereas the Android logic would have it range from 8000 px/sec up to sqrt(2) times that, or about 11300 px/sec, when travelling at a 45-degree angle to the axes.

But when the view is only scrolling in one axis, the resulting behavior is not physically natural — it's as if you had a physical object mounted on a linear rail, but when you pushed it hard along the rail, it started resisting you much harder and moving more slowly if you also pushed it somewhat to the side. You *could* build a physical system like that, but it means one with a lot of friction, which is not the metaphor one wants for a good scrolling experience.

More concretely, this behavior produces the user perception of sluggishness described above. And it differs from Android's, which is a fidelity issue.

### Toward a solution

Instead, when we're in a `DragGestureRecognizer` subclass that's looking for drag gestures in a single axis (namely `VerticalDragGestureRecognizer` or `HorizontalDragGestureRecognizer`), we should allow the velocity in that axis to reach the maximum even when the input velocity has a component in the other axis too.

I haven't yet looked into what a good way to do that in the code would look like. It may require a change to the API implemented by `DragGestureRecognizer` subclasses.

**Comment by exaby73** [comment] 2023-02-09 13:56
Hello @gnprice. Apologies if I do not understand the issue completely, but could you highlight what this issue adds that isn't already in the issues you mentioned? There's a lot of information you provide - thanks :) - but I'm having a tough time sifting through it.

Also, the steps that you provided to reproduce this issue, I'm afraid that could be hindered by human error. Testing it, it looks like the scroll view sort of follows the finger. Flinging the scroll view, I am not sure if it's Flutter influencing the scroll speed or whether I was slower that time flinging it. I have also seen that sometimes, flinging at an angle scrolls further than flinging vertically, though not by much which is probably because of human error.

Is there a consistent way we can test this behavior? Can, for example, tests help us here to reproduce a consistent scrolling behavior? This would help verify the behavior and provide a definite way to check if the issue is fixed in the future.

**Comment by exaby73** [comment] 2023-02-10 06:26
Upon consulting with a colleague of mine, I've decided to label this issue. I've sat down and and reproduced this behavior over and over and I'd say around 80 - 90% of the time I can reproduce this behavior. The other 10 - 20% I'd consider error on my end. Hope to get further insights from the team on this issue :)

**Comment by gnprice** [comment] 2023-02-10 07:07
Thanks!


> but could you highlight what this issue adds that isn't already in the issues you mentioned? There's a lot of information you provide - thanks :) - but I'm having a tough time sifting through it.

Sure. The key part that's distinct about this issue, from a user-visible perspective, is that it specifically affects the scrolling when you do the swipe at an angle, and not when it's close to precisely vertical.

This issue makes swiping rapidly at an angle produce a slower fling-scroll, no matter how fast you swipe, than you get when swiping rapidly straight upward. The resulting fling-scroll also goes less far before stopping.

When you swipe straight up, this issue doesn't come into play. The scroll may still be slower than it should be, and slower than the native behavior, due to the other issues. When you swipe at an angle, the other issues are still present but this one slows the scroll down still more, and widens the gap from the native behavior.



> I'd say around 80 - 90% of the time I can reproduce this behavior. The other 10 - 20% I'd consider error on my end.

Cool. Yeah, I find that trying to swipe at a particular angle is fairly imprecise for me too. But a 80-90% reproduction rate is definitely reliable enough for investigating an issue and manually testing a fix.

And I definitely agree we'll want unit tests to accompany any fix. Fortunately those can be a lot more precise than a human finger on a screen, so they should be very reliable.

**Closed** 2023-03-17 20:52 UTC
Labels: framework, f: scrolling, has reproducible steps, P4, found in release: 3.7, found in release: 3.8
