### ISSUE TITLE
Provide ability for plugins to register to receive NSAppDelegate calls on macOS

### ISSUE THREAD

**Issue by MaikuB** [flutter/flutter#57944] opened 2020-05-25 12:27 UTC
## Use case

I maintain a plugin for displaying local notifications and was looking at an implementation for macOS. When running on macOS versions below 10.14, the [NSUserNotification APIs](https://developer.apple.com/documentation/foundation/nsusernotification) need to be used. When a user taps on a notification, the plugin needs to receive calls that the app launched to get details of the launch notification as per the docs [here](https://api.flutter.dev/objcdoc/Protocols/FlutterPluginRegistrar.html#/c:objc(pl)FlutterPluginRegistrar(im)addApplicationDelegate:). Plugins on iOS are able to receive `UIApplicationDelegate` calls as the plugin registrar exposes an [`addApplicationDelegate`](https://api.flutter.dev/objcdoc/Protocols/FlutterPluginRegistrar.html#/c:objc(pl)FlutterPluginRegistrar(im)addApplicationDelegate:) method for plugins to  use. However, this functionality is currently missing in the engine on macOS.

It's quite possible that other plugins would be interested in receiving these calls to respond to lifecycle changes in the application

## Proposal

The plugin registrar on macOS will provide a way for plugins to register to receive `NSAppDelegate` calls. This could be via method named `addApplicationDelegate` to be consistent with iOS

**Comment by stuartmorgan** [comment] 2020-05-25 15:07
Duplicate of https://github.com/flutter/flutter/issues/41471

**Closed by stuartmorgan** 2020-05-25 15:07 UTC
Labels: a: desktop, platform-mac, proposal, severe: new feature

**Comment by MaikuB** [comment] 2020-05-25 19:22
Ah missed that. Thanks
