### ISSUE TITLE
[iOS][add2app] can't compile the project via flutter build ios-framework with sqflite package

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#112459] opened 2022-09-27 10:10 UTC
**I've used to be able to compile the project with the specific constraints and with Flutter version 3.0.0**. Currently, I'm getting the below error output if using sqflite: "2.0.2+1" (or higher or lower versions)

The following steps are taken when compiling: 

1. Checkout to Flutter version 3.0.0
2. Run flutter pub cache repair 
3. Run flutter clean && flutter pub get && flutter build ios-framework

Minimal example (can't compile on latest master 3.4.0 as well): https://github.com/ljmatan/add2app_compile_issue

## Details

**Target Platform:** iOS
**Target OS version/browser:** -
**Devices:** -

## Logs

<details>
Building frameworks for ihre.apotheken.iaFlutter in debug mode...
 ├─Copying Flutter.xcframework...                                  441ms
 ├─Building App.xcframework...                                     14.9s
Running pod install...                                             738ms
 ├─Building plugins...                                              4.5s
Unable to build plugin frameworks: 2022-09-27 11:59:16.262 xcodebuild[33042:329393] Requested but did not find extension point with identifier
Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
com.apple.dt.IDEWatchSupportCore
2022-09-27 11:59:16.262 xcodebuild[33042:329393] Requested but did not find extension point with identifier
Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **

The following build commands failed:
        CompileC /Users/threeofthem/Projects/ADAC\ iOS/Flutter/Debug/iphoneos/Pods.build/Debug-iphoneos/FMDB.build/Objects-normal/arm64/FMDB-dummy.o
        /Users/threeofthem/Projects/temp/ia_flutter/.ios/Pods/Target\ Support\ Files/FMDB/FMDB-dummy.m normal arm64 objective-c
        com.apple.compilers.llvm.clang.1_0.compiler (in target 'FMDB' from project 'Pods')
(1 failure)
<summary>Logs</summary>

```
Analyzing ia_flutter...                                         
No issues found! (ran in 3.4s)

```

```
[✓] Flutter (Channel unknown, 3.0.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 3.0.0 at /Users/threeofthem/SDKs/flutter
    • Upstream repository unknown
    • Framework revision ee4e09cce0 (5 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/threeofthem/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] VS Code (version 1.72.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 06784F3B-852F-4A10-A66B-235E0BA9938A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125
    ! Device emulator-5554 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by ljmatan** [comment] 2022-09-27 10:34
Same issue happens when using an absolute path, referenced from https://github.com/flutter/flutter/issues/48859#issuecomment-588393937

**Comment by ljmatan** [comment] 2022-09-27 10:42
`flutter build ios-framework --cocoapods -v`

[verbose.txt](https://github.com/flutter/flutter/files/9654645/verbose.txt)

**Comment by huycozy** [comment] 2022-09-27 11:50
Hi @ljmatan 
From what I can see, the issue is related to a 3rd party plugin (sqflite) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/tekartik/sqflite/tree/master/sqflite).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Comment by ljmatan** [comment] 2022-09-27 11:54
Hey @huycozy 

I do disagree as previous builds had been succesful with the aforementioned constraints. All of the logs and the code you're requesting had been attached.

**Comment by huycozy** [comment] 2022-09-28 10:56
Hi @ljmatan, I reopen this issue for further discussion as you disagreed.

>I do disagree as previous builds had been succesful with the aforementioned constraints / with an earlier flutter version.

Which Flutter's old version did you build successfully? 

As this issue is related to 3rd plugin (sqflite), it will be better if you open an issue in its repository for better support there.

You're using `sqflite: ^2.0.2+1` in the project but I'm seeing the different version from your build output you attached above in https://github.com/flutter/flutter/issues/112459#issuecomment-1259307387:
>[  +11 ms] Found plugin sqflite at /Users/threeofthem/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+3/
[  +18 ms] Found plugin sqflite at /Users/threeofthem/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+3/

The latest plugin version is `sqflite: ^2.1.0`, you may try clearing pub cache and using the latest version to see if it can help.

Also, I tried pulling your repository [add2app_compile_issue](https://github.com/ljmatan/add2app_compile_issue) and follow your steps to reproduce, the issue does not happen from my end:

<details>
<summary>Logs</summary>

```bash
➜  add2app_compile_issue git:(master) ✗ flutter build ios-framework

💪 Building with sound null safety 💪

Building frameworks for ihre.apotheken.iaFlutter in debug mode...
 ├─Copying Flutter.xcframework...                                  320ms
 ├─Building App.xcframework...                                     23.3s
Running pod install...                                           1,556ms
 ├─Building plugins...                                             28.0s
 └─Moving to build/ios/framework/Debug                              94ms
Building frameworks for ihre.apotheken.iaFlutter in profile mode...
 ├─Copying Flutter.xcframework...                                  281ms
 ├─Building App.xcframework...                                     42.2s
 ├─Building plugins...                                             17.2s
 └─Moving to build/ios/framework/Profile                            66ms
Building frameworks for ihre.apotheken.iaFlutter in release mode...
 ├─Copying Flutter.xcframework...                                  652ms
 ├─Building App.xcframework...                                     45.4s
 ├─Building plugins...                                             18.8s
 └─Moving to build/ios/framework/Release                            88ms
Frameworks written to /Users/huynq/Desktop/add2app_compile_issue/build/ios/framework.
➜  add2app_compile_issue git:(master) ✗ 

```
</details>

You are using the old Flutter version `3.0.0`, the latest Flutter stable is `3.3.2` and the master is `3.4.0`. Please try upgrading them and retry to see if this issue still reproduces.

**Closed** 2022-10-19 11:10 UTC
Labels: waiting for customer response, in triage
