### ISSUE TITLE
[camerax]: Read External Storage defined in another plugin gets rejected from mergedManifest

### ISSUE THREAD

**Issue by rohansohonee1** [flutter/flutter#156198] opened 2024-10-04 06:47 UTC
### Steps to reproduce

1. Build the android app from the below code sample.
2. Inspect the manifest merger logs at build/outputs/logs/manifest-merger-debug-report.txt.

### Expected results

The permission should not get **REJECTED** because it is a required permission for the `file_picker` plugin.

### Actual results

The permission is **REJECTED**. 

```
ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:17:5-19:31
REJECTED from [:file_picker] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/file_picker/intermediates/merged_manifest/debug/AndroidManifest.xml:9:5-11:38
	tools:node
		ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:19:9-28
	android:name
		ADDED from [:camera_android_camerax] /Users/appleapple/StudioProjects/file_picker_api_30_issue/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:18:9-64
```

For reference https://github.com/flutter/packages/pull/4700#issuecomment-2391368602

### Code sample

<details open><summary>Code sample</summary>

```pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: 6.0.0
  shared_preferences: 2.2.3
  image_picker: 1.1.2
  image_cropper: 5.0.1
  flutter_cache_manager: 3.4.1
  device_info_plus: 10.1.2
  share_plus: 10.0.0
  connectivity_plus: 6.0.5
  flutter_udid: 3.0.0
  flutter_local_notifications: 17.2.2
  permission_handler: 11.3.1
  in_app_purchase: 3.2.0
  package_info_plus: 8.0.2
  mobile_scanner: 3.0.0-beta.1
  in_app_review: 2.0.9
  open_mail_app: 0.4.5
  webview_flutter: 4.8.0
  facebook_app_events: 0.19.3
  app_settings: 5.1.1
  camera: 0.11.0
  file_picker: 8.0.5

dependency_overrides:
  mobile_scanner:
    git:
      url: https://github.com/agendaboa/mobile_scanner
      ref: e6bc28f66f6d266177b80daf898acabae980283b
```

```dart
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() async {
    // pick the .p12 or .pfx extension file
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['p12', 'pfx'],
      withData: true,
    );
    print(result);
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

[manifest-merger-debug-report.txt](https://github.com/user-attachments/files/17254445/manifest-merger-debug-report.txt)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 12.7.6 21H1320 darwin-x64, locale en-US)
    • Flutter version 3.19.6 on channel stable at /Users/appleapple/fvm/versions/3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (6 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (3 available)            
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 12.7.6 21H1320 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 129.0.6668.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by rohansohonee1** [comment] 2024-10-04 06:49
1. Maybe the plugin should not perform the tools:node="remove".
2. Or the documentation must mention that Read external storage permission will be removed from the merged manifest.

**Comment by huycozy** [comment] 2024-10-04 09:57
I can reproduce this issue by following steps
1. Create new Flutter project
2. Add two plugins:

```yaml
camera_android_camerax: ^0.6.9+1
file_picker: ^8.1.2
```
3. Build apk: 
```console
flutter build apk
```
4. Check the `REJECTED` permission on `build/app/outputs/logs/manifest-merger-release-report.txt` as mentioned above

Reproduced this on Flutter stable `3.24.3` and master `3.26.0-1.0.pre.353`

**Comment by rohansohonee1** [comment] 2024-10-04 10:03
@huycozy 
Can you suggest a temporary/immediate solution for this issue?

**Comment by huycozy** [comment] 2024-10-04 10:23
I tried explicitly adding `READ_EXTERNAL_STORAGE` permission to project's AndroidManifest file with `tools:node="merge"` or `tools:node="replace"` but didn't work. 

Another idea that you can try is to fork [camera_android_camerax](https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax) and modify permission for your use temporarily (add it back?)

**Comment by rohansohonee1** [comment] 2024-10-04 10:38
I have tested by excluding this merge rules `tools:node="merge"` or `tools:node="replace"`.
I declared it in the project's AndroidManifest file in the same manner as it has been declared in `file_picker` plugin:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
```
It is working for me. 
@huycozy Can you test the same?

In the manifest merger logs it rejects the plugins as follows:
```
uses-permission#android.permission.READ_EXTERNAL_STORAGE
ADDED from /Users/appleapple/StudioProjects/agendaboaflutter/android/app/src/main/AndroidManifest.xml:17:5-19:38
REJECTED from [:camera_android_camerax] /Users/appleapple/StudioProjects/agendaboaflutter/build/camera_android_camerax/intermediates/merged_manifest/debug/AndroidManifest.xml:15:5-17:31
REJECTED from [:file_picker] /Users/appleapple/StudioProjects/agendaboaflutter/build/file_picker/intermediates/merged_manifest/debug/AndroidManifest.xml:7:5-9:38
	android:maxSdkVersion
		ADDED from /Users/appleapple/StudioProjects/agendaboaflutter/android/app/src/main/AndroidManifest.xml:19:9-35
	android:name
		ADDED from /Users/appleapple/StudioProjects/agendaboaflutter/android/app/src/main/AndroidManifest.xml:18:9-64
```

Is this a valid solution?

**Comment by rohansohonee1** [comment] 2024-10-04 10:48
For reference https://developer.android.com/build/manage-manifests#merge_priorities
![manifest-merger_2x](https://github.com/user-attachments/assets/76a7c31c-c2b9-42f7-8661-e1dc44bfc82b)

**Comment by huycozy** [comment] 2024-10-04 11:34
Yeah, app level should have higher priority than libraries. 

>I have tested by excluding this merge rules tools:node="merge" or tools:node="replace".
I declared it in the project's AndroidManifest file in the same manner as it has been declared in file_picker plugin:
It is working for me.

Adding permission like that or with `tools:node="merge"` or `tools:node="replace"`  indeed works. Perhaps I misread or the build is cached on my report at https://github.com/flutter/flutter/issues/156198#issuecomment-2393324770. 

You can confirm this by using Android Studio > Build > Analyze APK, selecting the output APK built from Flutter and checking the permission on the final AndroidManifest, it should be there.

**Comment by gmackall** [comment] 2024-10-04 18:45
From Android triage: Camille, talk to Reid

**Comment by camsim99** [comment] 2024-10-08 17:05
Ok I'm understanding that https://github.com/flutter/packages/blob/c6377679226b5ee00c46154f3f72f1b1a4c17c03/packages/camera/camera_android_camerax/android/src/main/AndroidManifest.xml#L10 was not quite the right fix for `READ_EXTERNAL_STORAGE` being unnecessarily added. And based on the comments, sounds like ideally we could have the manifest of any other plugin take precedent over CameraX's, but based on https://developer.android.com/build/manage-manifests#merge_priorities it doesn't sound like this is possible since they are all libraries?

Assuming it's not possible: FWIW, I'm not sure that needing to manually include `READ_EXTERNAL_STORAGE` in an app  that **does** need it is worse than having to remove it from an app that **does not** need it, but maybe the recent changes to scoped storage make the consequences less severe for the latter case.

@reidbaker I hear I should talk to you. Any insights?

**Comment by camsim99** [comment] 2024-10-08 21:26
Talked offline with @reidbaker and decided to revert https://github.com/flutter/packages/pull/4716 and add documentation on how to remove `READ_EXTERNAL_STORAGE` manually in your Flutter app.

The docs that explain why `WRITE_EXTERNAL_STORAGE` (which may bring in `READ_EXTERNAL_STORAGE` by default in the merged Android manifest) is needed in the plugin is already linked in the README that my PR edits.

**Closed** 2024-10-09 17:24 UTC
Labels: platform-android, p: camera, package, has reproducible steps, P1, a: plugins, team-android, triaged-android, fyi-ecosystem, found in release: 3.24, found in release: 3.26
