### ISSUE TITLE
Flutter can't run on Linux running on Surface Pro  (libEGL warning: DRI2: failed to create dri screen)

### ISSUE THREAD

**Issue by Firefnix** [flutter/flutter#72211] opened 2020-12-12 21:44 UTC
## Short description
On Linux, flutter can't run any project: the window is fixed with a screenshot of what was on my screen before the window popped up. The only log/error message are:
```
(bug:4750): Gtk-WARNING **: 21:59:25.921: Theme parsing error: gtk.css:5449:34: Invalid name of pseudo-class
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
```
I assume the first one is normal (or at least not very important), since I've seen it for weeks without any crash.
I'd like to add that there is no such bug when I run `flutter build linux` then `build/linux/release/bundle/bug`: the app runs normally (although the `Gtk-WARNING` stills here). And that's probably the strangest thing about this issue.

## Informations
I use Ubuntu (20.04.1 LTS), and a non-official kernel (`5.9.10-surface`, see [github](https://github.com/linux-surface/linux-surface/)).

## Steps to Reproduce
1. Run `flutter create bug`.
2. No need to update files. Just `cd bug` and `flutter run -d linux`

**Expected results:** A nice window pops up, resizeable, with a button counting how many times you tap on it.

**Actual results:** A window pops up, but it just shows a screenshot of what was on my screen before it popped up. No error messages. I can resize and close the window, but when I resize it, black strips appears at the borders of the window (Flutter fails to repaint). Also, hot restart and hot reload work.

<details>
  <summary>Logs</summary>

Output for `flutter run -d linux`:
```
[  +59 ms] executing: [~/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +29 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] a12e2a473a3214b4556ca589d2d9bd311ac7c6f1
[        ] executing: [~/snap/flutter/common/flutter/] git tag --points-at a12e2a473a3214b4556ca589d2d9bd311ac7c6f1
[  +11 ms] Exit code 0 from: git tag --points-at a12e2a473a3214b4556ca589d2d9bd311ac7c6f1
[        ] 1.25.0-8.0.pre
[  +33 ms] executing: [~/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [~/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +35 ms] executing: [~/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +50 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] executing: ~/Android/Sdk/platform-tools/adb devices -l
[  +24 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +73 ms] executing: ~/Android/Sdk/platform-tools/adb devices -l
[  +17 ms] Skipping pub get: version match.
[ +110 ms] Found plugin integration_test at ~/snap/flutter/common/flutter/packages/integration_test/
[ +133 ms] Found plugin integration_test at ~/snap/flutter/common/flutter/packages/integration_test/
[   +3 ms] Generating ~/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +64 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +4 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] ~/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev ~/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root ~/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.JEKOWH/flutter_tool.WREXYZ/app.dill --packages ~/bug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +12 ms] Building Linux application...
[  +23 ms] <- compile package:bug/main.dart
[   +4 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ~/bug/linux
[   +9 ms] List of devices attached
[   +2 ms] List of devices attached
[  +31 ms] -- Configuring done
[   +5 ms] -- Generating done
[        ] -- Build files have been written to: ~/bug/build/linux/debug
[   +8 ms] executing: ninja -C build/linux/debug install
[   +8 ms] ninja: Entering directory `build/linux/debug'
[+4513 ms] [1/5] Generating ~/bug/linux/flutter/ephemeral/libflutter_linux_gtk.so, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_engine.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_value.h, ~/bug/linux/flutter/ephemeral/flutter_linux/fl_view.h, ~/bug/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +20 ms] [  +76 ms] executing: [~/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] a12e2a473a3214b4556ca589d2d9bd311ac7c6f1
[        ] [        ] executing: [~/snap/flutter/common/flutter/] git tag --points-at a12e2a473a3214b4556ca589d2d9bd311ac7c6f1
[        ] [  +16 ms] Exit code 0 from: git tag --points-at a12e2a473a3214b4556ca589d2d9bd311ac7c6f1
[        ] [        ] 1.25.0-8.0.pre
[        ] [  +47 ms] executing: [~/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/dev
[        ] [        ] executing: [~/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +65 ms] executing: [~/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [  +71 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +84 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +83 ms] Initializing file store
[        ] [  +16 ms] Done initializing file store
[        ] [  +47 ms] Skipping target: gen_localizations
[        ] [+2388 ms] Skipping target: unpack_linux
[        ] [ +506 ms] Skipping target: kernel_snapshot
[        ] [ +354 ms] Skipping target: debug_bundle_linux_assets
[        ] [        ] Persisting file store
[        ] [  +10 ms] Done persisting file store
[        ] [   +7 ms] build succeeded.
[  +12 ms] [  +12 ms] "flutter assemble" took 3 541ms.
[   +1 ms] [   +6 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +4 ms] exiting with code 0
[ +503 ms] [2/5] Building CXX object CMakeFiles/bug.dir/flutter/generated_plugin_registrant.cc.o
[  +49 ms] [3/5] Building CXX object CMakeFiles/bug.dir/my_application.cc.o
[  +97 ms] [4/5] Linking CXX executable intermediates_do_not_run/bug
[        ] [4/5] Install the project...
[   +9 ms] -- Install configuration: "Debug"
[  +19 ms] -- Installing: ~/bug/build/linux/debug/bundle/bug
[        ] -- Set runtime path of "~/bug/build/linux/debug/bundle/bug" to "$ORIGIN/lib"
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/icudtl.dat
[        ] -- Installing: ~/bug/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[ +112 ms] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: ~/bug/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +43 ms] Building Linux application... (completed in 5,5s)
[  +48 ms] (bug:6675): Gtk-WARNING **: 22:29:47.611: Theme parsing error: gtk.css:5449:34: Invalid name of pseudo-class
[  +99 ms] libEGL warning: DRI2: failed to create dri screen
[   +5 ms] libEGL warning: DRI2: failed to create dri screen
[ +187 ms] Observatory URL on device: http://127.0.0.1:36851/NVvegRNujB4=/
[+2499 ms] Caching compiled dill
[  +84 ms] Connecting to service protocol: http://127.0.0.1:36851/NVvegRNujB4=/
[   +4 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:36851/NVvegRNujB4=/.
[ +179 ms] DDS is listening at http://127.0.0.1:45531/5kT2Et9CBwI=/.
[  +59 ms] Successfully connected to service protocol: http://127.0.0.1:36851/NVvegRNujB4=/
[  +10 ms] DevFS: Creating new filesystem on the device (null)
[  +12 ms] DevFS: Created new filesystem on the device (file:///tmp/bugPSEUPD/bug/)
[   +1 ms] Updating assets
[  +96 ms] Syncing files to device Linux...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:bug/main.dart 07d5ee1a-4a3b-4b38-aa57-446a63e35f24
[        ] <- 07d5ee1a-4a3b-4b38-aa57-446a63e35f24
[ +120 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 125ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +5 ms] Connected to _flutterView/0x19e13c0.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:45531/5kT2Et9CBwI=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+7121 ms] Gdk-Message: 22:29:58.105: bug: Fatal IO error 22 (Argument invalide) on X server :0.
[   +1 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///tmp/bugPSEUPD/bug/)
[ +257 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +5 ms] "flutter run" took 16 862ms.
[  +12 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +8 ms] Shutdown hooks complete
[        ] exiting with code 0
```

`flutter analyze` output:
```
Analyzing bug...                                                        
No issues found! (ran in 11.9s)
```

Output of running `flutter doctor -v`:
```
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.25.0-8.0.pre at /home/malo/snap/flutter/common/flutter
    • Framework revision a12e2a473a (il y a 4 jours), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/malo/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 3 categories.
```
Comments:
 -  Running `flutter doctor --android-licenses` throws a Java error, but that's another issue that seems unrelated to this one.
 - Chrome is not installed, but since I'm trying to run my app for `-d linux` (not `-d web-server`), I don't think that's a problem
 - Android Studio *is* installed (from `snap`).

</details>

**Comment by TahaTesser** [comment] 2020-12-14 12:35
Hi @Firefnix 
Are you running Ubuntu on VM?  or based on your kernel, you booting from surfacebook?
Please complete output of `neofetch`
Thank you

**Comment by Firefnix** [comment] 2020-12-18 20:20
Sorry for the late response.
I do not run Ubuntu on VM. I installed the official version of Ubuntu and then I installed another kernel than the mainstream kernel. My device is a Surface Pro 5 / 2017 (not a Surface Book). I'm booting from a UEFI entry named `Ubuntu` that was created when I installed this distro (before I installed the `surface` kernel).

<details>
<summary>Here's the complete output of `neofetch`.</summary>

```
            .-/+oossssoo+/-.               me@surface 
        `:+ssssssssssssssssss+:`           ------------ 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: Surface Pro D:0B:09F:5C:09P:38 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.9.10-surface 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 hours, 21 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2592 (dpkg), 14 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 2736x1824 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Yaru-Aqua-dark 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-Aqua-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Paper [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-7300U (4) @ 3.500GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel HD Graphics 620 
      -+sssssssssssssssssyyyssss+-         Memory: 4818MiB / 7886MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
```

</details>

**Comment by Firefnix** [comment] 2020-12-23 17:33
@TahaTesser I tried with an official kernel :
```
$ uname -a
Linux surface 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
(Here, `surface` is the device name, nothing to do with the kernel.)
However, the same crash still happens, so this issue does not seem related to that custom kernel. 
I also tried reinstalling `libegl1` (with `apt`). The only new thing I noticed was another warning after `libEGL warning: DRI2: failed to create dri screen` :
```
(bug:6511): Gtk-WARNING **: 18:31:05.493: Theme parsing error: gtk.css:5449:34: Invalid name of pseudo-class
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
WARNING: failed to attach a stencil buffer. Rendering will be skipped.
```

**Comment by TahaTesser** [comment] 2020-12-28 14:09
@Firefnix 
Thanks, updated title

**Comment by stuartmorgan** [comment] 2020-12-31 00:08
Does any OpenGL content work on that device? Searching for that error message (which is coming from something lower level than the Flutter engine) looks like its a machine configuration and/or driver issue.

**Comment by Firefnix** [comment] 2020-12-31 14:54
I compiled and ran the [chess](https://www.opengl.org/archives/resources/code/samples/glut_examples/demos/demos.html) OpenGL demo without any problem (I installed `freeglut3-dev` and compiled with GCC). Moreover, I never experienced any trouble with any other app, and a lot of them are based on OpenGL.
As a reminder, this crash does not occur when I `flutter build` the app, so it looks like a `flutter run`-specific issue.

**Comment by gspencergoog** [comment] 2021-01-14 19:16
(Desktop triage) We think this is a duplicate of flutter/flutter#72456
Please let us know if you still see this, and we'll reopen.

/cc @stuartmorgan

**Closed by gspencergoog** 2021-01-14 19:16 UTC
Labels: P5, a: desktop, e: device-specific, engine, passed first triage, platform-linux, severe: crash, severe: fatal crash

**Comment by Firefnix** [comment] 2021-01-16 12:57
I uninstalled the `flutter` snap and installed (with some trouble) Flutter from source (on the master branch).
`flutter run -d linux` doesn't fail anymore, so I consider this issue as solved.
Thank you all for helping me to solve my problem.

**Comment by Prashant4900** [comment] 2021-02-20 11:01
I also faced a similar problem but it's a little bit different whenever I tried to run flutter desktop in my ubuntu 20.04 by pressing the F5 key its will shows an error like this 

Launching lib/main.dart on Linux in debug mode...                                                                                      
lib/main.dart:1
(testapp:41237): Gtk-WARNING **: 16:10:35.942: Theme parsing error: gtk.css:7576:58: Failed to import: The resource at “/org/gnome/Mojave-theme/gtk.css” does not exist
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Linux.
Exited (sigterm)


or if I run using the terminal with the help of this command **fluttera run -d linux** then its work fine 

### **flutter doctor -v**
mindless@mindless-demo:~/Documents/code/flutter desktop/testapp$ fluttera doctor -v
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.27.0-4.0.pre at /home/mindless/Documents/flutter/flutter_dev
    • Framework revision f8cd24de95 (4 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/mindless/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-ultimate/269
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2021-02-23 09:43
@Prashant4900
 please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.

**Comment by Prashant4900** [comment] 2021-03-05 07:11
**Flutter doctor -v**

mindless@mindless-demo:~/Documents/code/demo_app$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.0, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.0 at /home/mindless/Documents/flutter
    • Framework revision 60bd88df91 (2 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-ultimate/269
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 2 categories.
mindless@mindless-demo:~/Documents/code/demo_app$ 


I recently migrate my flutter SDK 2.0but after the migration **app is not lunch by pressing the F5** 
but if I use a command like that flutter run -d linux, flutter run -d chrome then the app will run fine 

otherwise, if I run it's by F5 so for chrome app will run for 3 4 seconds a white screen will appear, and after it will go 
**Debug Console** = Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1

and for linex its shows the error = Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
(demo_app:66555): Gtk-WARNING **: 12:41:23.589: Theme parsing error: gtk.css:7576:58: Failed to import: The resource at “/org/gnome/Mojave-theme/gtk.css” does not exist
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Linux.
Exited (sigterm)
