### ISSUE TITLE
Crashlytics reported that flutter app crashed on start on Android: couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by windows7lake** [flutter/flutter#89147] opened 2021-08-30 04:00 UTC
I don't know why this issue [#32756](https://github.com/flutter/flutter/issues/32756) was closed without any solution. And I couldn't find a similar issue, so I create a new one.

![image](https://user-images.githubusercontent.com/10578898/131283455-394ed214-5826-4906-82ac-4dcbbecb5396.png)

**Comment by harshbarnwal** [comment] 2021-08-30 10:04
Flutter doesn't support 32 bit architecture that's libflutter.so is missing, you can analyze your apk in android studio and you will find that libflutter.so is missing in 32 bit folder.
Also GPay uses flutter so you can check that GPay isn't available for devices that support only 32 bit apps.

**Comment by TahaTesser** [comment] 2021-08-30 12:14
Hi @windows7lake 
duplicate of https://github.com/flutter/flutter/issues/32756, please read  https://github.com/flutter/flutter/issues/32756#issuecomment-798948280

**Closed by TahaTesser** 2021-08-30 12:14 UTC
Labels: in triage
