### ISSUE TITLE
frontend_server_dart: No such file 

### ISSUE THREAD

**Issue by geraldeersteling** [flutter/flutter#27835] opened 2019-02-12 10:51 UTC
## Steps to Reproduce

I followed the install directions in the docs but am unable to build and run the app to my iOS device using the `run` command.

The command fails because it can't find the file _frontend_server.dart.snapshot_, which is right because the location it's searching if...weird. Without the `file://` prefix the path would've been correct.

I don't know how to fix this one as I've updated my `$PATH` and Flutter itself _can_ be found.

## Logs

> The output of running `flutter run --verbose` is way too big.  
> I'm unable to post all of it here, but I'll post the non-verbose one

```
Launching lib/main.dart on TOO iPhone 7+ in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: TEAMID
Starting Xcode build...
 ├─Assembling Flutter resources...                    1.6s

Xcode build done.                                            3.3s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-02-12 11:48:10.087 xcodebuild[23121:3045622]  DTDeviceKit: deviceType from 4fe2906df031911d06bc8f15f9e7e435fca97e42 was NULL
    2019-02-12 11:48:10.087 xcodebuild[23121:3045622]  DTDeviceKit: deviceType from 4fe2906df031911d06bc8f15f9e7e435fca97e42 was NULL
    2019-02-12 11:48:10.090 xcodebuild[23121:3045622]  iPhoneSupport: 📱<DVTiOSDevice (0x7fa892b41c30), GeePhone X, iPhone, 12.1.4
    (16D57), 6eb37e68bb74fea7d733019283af5c65eedb686b> unable to mount DeveloperDiskImage (Error Domain=com.apple.dtdevicekit
    Code=601 "Could not find platform" UserInfo={NSLocalizedDescription=Could not find platform})
    2019-02-12 11:48:10.188 xcodebuild[23121:3045618] [MT] DTDeviceKit: deviceType from 4fe2906df031911d06bc8f15f9e7e435fca97e42 was
    NULL
    2019-02-12 11:48:10.197 xcodebuild[23121:3045618] [MT] DTDeviceKit: deviceType from 4fe2906df031911d06bc8f15f9e7e435fca97e42 was
    NULL
    2019-02-12 11:48:10.207 xcodebuild[23121:3045618] [MT] DTDeviceKit: deviceType from 4fe2906df031911d06bc8f15f9e7e435fca97e42 was
    NULL
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Error: Error when reading
    'file:///Users/owner/Documents/Flutter/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot':
    No such file or directory

    Compiler failed on /Users/owner/git/flutter-playground/lib/main.dart
    Failed to package /Users/owner/git/flutter-playground.

Could not build the precompiled application for the device.

Error launching application on TOO iPhone 7+.
 3.1s
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-NL)
    • Flutter version 1.0.0 at /Users/owner/Documents/Flutter/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/owner/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • TOO iPhone 7+ • DEVICEID • ios • iOS 10.3.3

• No issues found!
```

**Comment by zoechi** [comment] 2019-02-12 11:01
> Without the `file://` prefix the path would've been correct.

This is just a file URI which will then be converted to a file path. 

Duplicate of #22035

**Closed by zoechi** 2019-02-12 11:01 UTC

**Comment by geraldeersteling** [comment] 2019-02-12 11:09
😕 well after looking at the issue you mentioned as duplicate I changed the deployment target from 8.0 to 12.1, which removes the error from the build's output.  
However the second error—about not finding the file persists.

**Comment by zoechi** [comment] 2019-02-12 11:20
Please try deleting `/Users/owner/Documents/Flutter/flutter/bin/cache` and run `flutter doctor` then try again.

**Comment by geraldeersteling** [comment] 2019-02-12 11:31
This works, many thanks @zoechi! 🎉 
Maybe this is a tip for the docs (deleting the cache if this fails)?

**Comment by zoechi** [comment] 2019-02-12 11:34
@geraldeersteling haven't seen this issue before, but we will consider it if it is encountered more often.

**Comment by postmasters** [comment] 2019-08-19 16:04
I've just got hit by this `Could not find platform` error too. Removing `cache` directory did NOT solve it.

**Comment by fabclovinn** [comment] 2019-11-20 17:01
I have this issue everytime I try to run flutter. Like if I sepnd 10 minutes without working with flutter, when I try to run flutter again, I get this error so I have to appli what @zoechi said. But I have to do this like 10 times per day, it's very frustrating..
