### ISSUE TITLE
[camera] Unable to capture images when the flash is turned on

### ISSUE THREAD

**Issue by guilhermeagostinelli** [flutter/flutter#80895] opened 2021-04-21 20:54 UTC
Hello, I'm using the camera plugin version 0.8.1, testing on a Moto G4 (Android 6).

The flash feature is not working properly.

When using the `always` flash mode, at the moment the `takePicture` function is called, the flashlight stays forever on and the picture is not taken. A captureTimeout/"Picture capture request timed out" exception is being thrown and the following is written to the console:

```
I/RequestQueue(14354): Repeating capture request cancelled.
I/RequestQueue(14354): Repeating capture request set.
W/LegacyRequestMapper(14354): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
```

This seems to be very similar to https://github.com/flutter/flutter/issues/74645

I've tested with both `always` and `torch` flash modes and the result is the same: I'm unable to take any pictures. It's worth mentioning that it works perfectly fine - and the picture is taken almost instantly - when the flash is turned off.

This seems to be a device-specific problem since it is working on a Motorola One Hyper device (although the picture looks like it was taken with the flash turned off as reported in https://github.com/flutter/flutter/issues/80894).

Thanks in advance.

**Comment by pedromassangocode** [comment] 2021-04-22 08:27
Hi @guilhermeagostinelli 
I tested with the official [example](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example) code and I cannot reproduce this issue. Can you please provide the steps to reproduce, your `flutter run --verbose` (running on the same device where the issue happen) a minimal reproducible code sample?
Thank you

**Comment by Wian-TMC** [comment] 2021-04-26 06:54
Experiencing the exact same issue on a Xiaomi My A2 Lite.

**Comment by pedromassangocode** [comment] 2021-05-19 12:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-19 12:08 UTC
Labels: in triage, waiting for customer response
