### ISSUE TITLE
GoogleServices-Info.plist file not copied, prevents successful build

### ISSUE THREAD

**Issue by thosakwe** [flutter/flutter#13967] opened 2018-01-07 18:03 UTC
## Steps to Reproduce
Not sure why, but it seems like Flutter does not include the `GoogleServices-Info.plist` file from `ios/Runner` when building a Firebase-enabled application. This prevents the app from ever building, which led to an unhappy client for me 😃 

## Logs
The log is MASSIVE and very difficult to understand; I couldn't even paste it here, because it exceeds 65536 characters.

```
    Method:   -createCommandInvocationRecordFromInvocation:
    Thread:   <NSThread: 0x7feb17da87d0>{number = 18, name = (null)}
    Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CopyPlistFile /Users/thosakwe/Commercial/cric_central/build/ios/Debug-iphonesimulator/Runner.app/GoogleService-Info.plist /Users/Downloads/GoogleService-Info.plist
    (1 failure)
Xcode's output:
↳
    Build settings from command line:
        ARCHS = x86_64
        BUILD_DIR = /Users/thosakwe/Commercial/cric_central/build/ios
        ONLY_ACTIVE_ARCH = YES
        SDKROOT = iphonesimulator11.2
    
    === CLEAN TARGET GoogleToolboxForMac OF PROJECT Pods WITH CONFIGURATION Debug ===
    
    Check dependencies
```

**Comment by thosakwe** [comment] 2018-01-29 02:20
Anything I can do about this at all?

**Comment by branflake2267** [comment] 2018-01-29 02:38
From what it looks like the file is linked, and not copied to the Runner directory. I would try it again, and verify the file is copied into the Runner directory. Then select it, and verify on the right it's part of the target membership.

**Comment by Hixie** [comment] 2018-05-25 18:11
cc @collinjackson

**Comment by zoechi** [comment] 2019-01-21 16:21
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

The cause might have been that the file needs to be added using XCode.

**Comment by zoechi** [comment] 2019-02-18 07:54
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-18 07:54 UTC
Labels: p: firebase, plugin, waiting for customer response

**Comment by kroikie** [comment] 2019-10-13 19:20
@thosakwe

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/915. Any further collaboration will be done there.
