### ISSUE TITLE
MacOS: Pubspec data not available until after it is needed

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#135730] opened 2023-09-29 01:38 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Attempt to access a value defined in Pubspec.yaml in main before runApp.

### Expected results

Get the value

I need to get access to the version declared in pubspec.yaml.

The supplied code runs perfectly on Windows.

On MacOS I get the word salad error message.

### Actual results

Crash

The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized. Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding. In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding. If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.)

### Code sample

<details><summary>Code sample</summary>

```dart
clkass MyClass {
  static Future<String> getVersion() async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();
   return "Version: ${packageInfo.version}";
  }
}
:
: 
Future<void> main() async {
   var version = await MyClass.getVersion();
  runApp(const MyApp());

: 
: 
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.4 22F66 darwin-arm64, locale en-AU)
    • Flutter version 3.13.5 on channel stable at /Users/user/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (9 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPad (mobile)   • 00008103-000229CE1E31001E • ios            • iOS 16.6.1 20G81
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 117.0.5938.88

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by stuartmorgan** [comment] 2023-09-29 02:00
> The supplied code runs perfectly on Windows.

Because the plugin you are calling has completely different implementations on Windows and macOS; the latter uses platform channels, and the former does not.

> On MacOS I get the word salad error message.

I'm not sure what about the error message constitutes "word salad"; it explains exactly what the problem is:

> The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized. Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()"

You are trying to call a plugin that uses platform channels—and thus `ServicesBinding`—before `runApp() has been called. The solution is to call `WidgetsFlutterBinding.ensureInitialized()` first.

Closing as this is not a bug, and there is already a specific and actionable error message. If you have constructive feedback about how to improve the error message, please feel free to file an issue about that.

**Closed** 2023-09-29 02:01 UTC
Labels: r: invalid

**Comment by WorikQCI** [comment] 2023-09-29 02:35
>Because the plugin you are calling has completely different implementations on Windows and macOS; the latter uses platform channels, and the former does not.

This is a bug.

I do not care about plugins, I want to access data defined in a file that is allways there.

I have to jump through special hoops to do that.

It is brain dead.

It is wrong

It is a bug

**Comment by stuartmorgan** [comment] 2023-09-29 02:47
> > Because the plugin you are calling has completely different implementations on Windows and macOS; the latter uses platform channels, and the former does not.
> 
> This is a bug.

Feel free to report it as such to the developers of `package_info_plus`, which is a third-party package.

**Comment by WorikQCI** [comment] 2023-10-03 21:24
I have struck this again:  The `name:` field in pubspec.yaml is unavailable at compile time or runtime.

Third party packages, that do not work properly, are not a solution to this.

The issue, the bug, is that the environment that Flutter sets up, that is always present, is unavailable to the programme itself.

As a programmer using this system this is continual sand in the gears.
