### ISSUE TITLE
Relaunching app in release mode from home screen sometimes crashes after showing splash screen for 1 second

### ISSUE THREAD

**Issue by Siyaho** [flutter/flutter#140793] opened 2024-01-02 15:02 UTC
### Steps to reproduce

1. Launch app via Xcode (always succeeds) 
2. Close the app on springboard (screen) of iPhone / real device
3. Try to relaunch the app
4. Loads splashscreen for 1 second and then terminates _(happens sometimes)_

Note: if debug mode, it always fails to relaunch the app from the home screen. Guessing this has to do with this? https://github.com/flutter/flutter/issues/66422#issuecomment-697972897. If so, is this also written down in your documents?

### Extra info

- Using latest version of Xcode
- iOS version on real device is 17.2.1
- Can't reproduce the issue on the simulators

### Expected results

The app should relaunch successfully from the springboard in release mode.

### Actual results

Sometimes it fails and sometimes it works. I can not rely on this to actually roll out to production, as it is not clear whether this is a bug or not.

### Logs

<details open><summary>Logs</summary>

```console
**Jan  2 01:14:10 ReportCrash(MetricKitSource)[134] 
<Error>: Failed to create bundle record for bundleID <private> and error <private>**

domain: BSServiceConnectionErrorDomain; code: 3 ("OperationFailed"); "XPC error received on message reply handler">.

Jan  2 01:14:09 SpringBoard(FrontBoard)[33] <Error>: 
[app<com.example.myappnamehere(6DC11EF2-C3B9-459A-9210-004DA66051D2)>:2287] 
Termination failed with error: Error Domain=RBSRequestErrorDomain Code=3 "No such process found" UserInfo={NSLocalizedFailureReason=No such process found}

    NSUnderlyingError = <NSError: 0x2801a5e30; domain: 
BSServiceConnectionErrorDomain; code: 3 ("OperationFailed"); "XPC error received on message reply handler">;

Jan  2 01:15:56 SpringBoard(FrontBoard)[33] <Notice>: [(FBSceneManager):sceneID:com.example.myappnamehere-default][1] 
Scene invalidated with error: <NSError: 0x2801a2d30; domain: BSServiceConnectionErrorDomain; code: 3 ("OperationFailed"); "XPC error received on message reply handler">.
```

</details>

I highlighted the first one, because that one is always shown when a relaunch fails, it seems.

```
**Jan  2 01:14:10 ReportCrash(MetricKitSource)[134] 
<Error>: Failed to create bundle record for bundleID <private> and error <private>**
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.18.0-18.0.pre.47, on Microsoft Windows [Version 10.0.19045.3803], locale en-NL)
    • Flutter version 3.18.0-18.0.pre.47 on channel master at D:\Flutter\flutter                              
    • Upstream repository https://github.com/flutter/flutter.git                                              
    • Framework revision 3df4e735d5 (4 days ago), 2023-12-29 14:07:39 -0500                                   
    • Engine revision 9e03a57cde                                                                              
    • Dart version 3.3.0 (build 3.3.0-273.0.dev)                                                              
    • DevTools version 2.31.0-dev.0                                                                           

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\MY\AppData\Local\Android\sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.1)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\MY\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3803]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 120.0.6099.129
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by huycozy** [comment] 2024-01-03 05:44
Hi @Siyaho 
You are sharing the flutter doctor output on Windows but the reporting issue is for iOS app. Please share the output of `flutter doctor -v` on your MacOS machine which contains the correct Flutter and XCode versions.

And where did you get the crash log? Please share the entire stack trace if any. 

Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

**Comment by dinko7** [comment] 2024-01-19 00:07
Hi @huycozy.

I have the same issue except it happens every time on the real device (iOS 17.4.1.).
Running from a clean project using `flutter create` yields the same result.

The only hints I have are this crash log and a partial crashlytics stack trace from the real app.
Production app log:
[Runner-2024-01-18-170028.txt](https://github.com/flutter/flutter/files/13982688/Runner-2024-01-18-170028.txt)

Clean app log:
[Runner-2024-01-18-225137.txt](https://github.com/flutter/flutter/files/13982748/Runner-2024-01-18-225137.txt)

![Screenshot_2024-01-19_at_00 09 40](https://github.com/flutter/flutter/assets/1454449/fe5a3e99-ef8d-4e33-a1f3-3683c5b59d50)

flutter doctor -v:
```
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.0 23A344 darwin-arm64, locale en-HR)
    • Flutter version 3.16.8 on channel stable at /Users/dinkomarinac/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (2 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dinkomarinac/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/dinkomarinac/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Dinko’s iPhone (mobile) • 00008110-001004C93C05801E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

Let me know if you need any more info.

**Comment by huycozy** [comment] 2024-01-19 04:43
@dinko7 Thanks for the info but I don't see a similar trace log (from OP) on your given logs. Do you mean your app is also crashing in release mode and after showing splash screen for 1 second? Does the crash occur randomly or every time?

**Comment by itsJoKr** [comment] 2024-01-19 14:00
Here's some info we found out (me and @dinko7 on a separate occasions). This might be same issue, or maybe not.

- We have this issue but only in **debug** version. 
- This only happens on iOS 17, on iOS 16 this is expected: https://i.stack.imgur.com/0DgnF.png

@huycozy I would check if somehow you are not installing debug version. Also check XCode schemes, that you are sure that you are not building Debug version. And try it on iOS 16.

**Comment by huycozy** [comment] 2024-01-22 03:33
@itsJoKr Since you can reproduce the issue in debug mode, please share a minimal sample code and the entire output of `flutter run -v` that may contain information for investigating this. Your screenshot is not related to this issue, it is showing that you installed the app on the device in debug mode, disconnected and reopened it. It's only be available in profile/release mode as suggested.

**Comment by darshankawar** [comment] 2024-02-09 05:48
Closing this as resolved based on above comment.

**Closed by darshankawar** 2024-02-09 05:48 UTC
Labels: in triage
