### ISSUE TITLE
dashPath used with canvas drawPath not yet implemented in canvas.

### ISSUE THREAD

**Issue by terrylucas** [flutter/flutter#49882] opened 2020-01-31 14:12 UTC
Flutter Web crashes with unimplemented feature in canvas.

```
js_primitives.dart:32 ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
js_primitives.dart:32 The following UnimplementedError was thrown during paint():
js_primitives.dart:32 UnimplementedError
js_primitives.dart:32 
js_primitives.dart:32 The relevant error-causing widget was:
js_primitives.dart:32   CustomPaint org-dartlang-app:///packages/mp_chart/mp/chart/chart.dart:110:31
js_primitives.dart:32 
js_primitives.dart:32 When the exception was thrown, this was the stack:
js_primitives.dart:32 package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
js_primitives.dart:32 package:build_web_compilers/lib/_engine/engine/surface/path_metrics.dart 131:7        extractPath
js_primitives.dart:32 package:path_drawing/src/dash_path.dart 34:28                                         dashPath
js_primitives.dart:32 package:mp_chart/mp/core/adapter_android_mp.dart 22:12                                convert2DashPath
js_primitives.dart:32 package:mp_chart/mp/core/utils/canvas_utils.dart 21:22                                drawLines
js_primitives.dart:32 package:mp_chart/mp/core/render/line_chart_renderer.dart 438:23                       drawLinear
js_primitives.dart:32 package:mp_chart/mp/core/render/line_chart_renderer.dart 101:9                        drawDataSet
js_primitives.dart:32 package:mp_chart/mp/core/render/line_chart_renderer.dart 88:47                        drawData
js_primitives.dart:32 package:mp_chart/mp/painter/bar_line_chart_painter.dart 279:14                        onPaint
js_primitives.dart:32 package:mp_chart/mp/painter/painter.dart 242:5                                        paint
js_primitives.dart:32 package:flutter/src/rendering/custom_paint.dart 531:12                                [_paintWithPainter]
js_primitives.dart:32 package:flutter/src/rendering/custom_paint.dart 572:7                                 paint
js_primitives.dart:32 package:flutter/src/rendering/object.dart 2262:7                                      [_paintWithContext]
js_primitives.dart:32 package:flutter/src/rendering/object.dart 184:12                                      paintChild
js_primitives.dart:32 package:flutter/src/rendering/proxy_box.dart 128:14                                   paint
js_primitives.dart:32 package:flutter/src/rendering/object.dart 2262:7                                      [_paintWithContext]
js_primitives.dart:32 package:flutter/src/rendering/object.dart 184:12                                      paintChild
js_primitives.dart:32 package:flutter/src/rendering/proxy_box.dart 128:14                                   paint
js_primitives.dart:32 package:flutter/src/rendering/object.dart 2262:7                                      [_paintWithContext]
js_primitives.dart:32 package:flutter/src/rendering/object.dart 184:12                                      paintChild
js_primitives.dart:32 package:flutter/src/rendering/proxy_box.dart 128:14                                   paint
js_primitives.dart:32 package:flutter/src/rendering/object.dart 2262:7                                      [_paintWithContext]
js_primitives.dart:32 package:flutter/src/rendering/object.dart 184:12                                      paintChild
js_primitives.dart:32 package:flutter/src/rendering/box.dart 2515:14                                        defaultPaint
js_primitives.dart:32 package:flutter/src/rendering/stack.dart 601:5                                        paintStack
js_primitives.dart:32 package:flutter/src/rendering/stack.dart 609:7                                        paint
js_primitives.dart:32 package:flutter/src/rendering/object.dart 2262:7                                      [_paintWithContext]
js_primitives.dart:32 package:flutter/src/rendering/object.dart 184:12                                      paintChild
js_primitives.dart:32 package:flutter/src/rendering/proxy_box.dart 128:14                                   paint
js_primitives.dart:32 package:flutter/src/rendering/proxy_box.dart 2039:11                                  paint
js_primitives.dart:32 package:flutter/src/rendering/object.dart 2262:7                                      [_paintWithContext]
js_primitives.dart:32 package:flutter/src/rendering/object.dart 184:12                                      paintChild
js_primitives.dart:32 package:flutter/src/rendering/proxy_box.dart 128:14                                   paint
js_primitives.dart:32 package:flutter/src/rendering/object.dart 2262:7                                      [_paintWithContext]
js_primitives.dart:32 package:flutter/src/rendering/object.dart 135:10                                      _repaintCompositedChild
js_primitives.dart:32 package:flutter/src/rendering/object.dart 95:5                                        repaintCompositedChild
js_primitives.dart:32 package:flutter/src/rendering/object.dart 981:29                                      flushPaint
js_primitives.dart:32 package:flutter/src/rendering/binding.dart 403:19                                     drawFrame
js_primitives.dart:32 package:flutter/src/widgets/binding.dart 797:13                                       drawFrame
js_primitives.dart:32 package:flutter/src/rendering/binding.dart 283:5                                      [_handlePersistentFrameCallback]
js_primitives.dart:32 package:flutter/src/scheduler/binding.dart 1109:15                                    [_invokeFrameCallback]
js_primitives.dart:32 package:flutter/src/scheduler/binding.dart 1048:9                                     handleDrawFrame
js_primitives.dart:32 package:flutter/src/scheduler/binding.dart 964:5                                      [_handleDrawFrame]
js_primitives.dart:32 package:build_web_compilers/lib/_engine/engine.dart 190:21                            <fn>
js_primitives.dart:32 
js_primitives.dart:32 The following RenderObject was being processed when the exception was fired: RenderCustomPaint#b399f:
js_primitives.dart:32   creator: CustomPaint ← _PointerListener ← Listener ← _GestureSemantics ← RawGestureDetector ←
js_primitives.dart:32     GestureDetector ← ConstrainedBox ← Stack ← DecoratedBox ← Container ←
js_primitives.dart:32     RepaintBoundary-[GlobalKey#208a5] ← Screenshot<dynamic> ← ⋯
js_primitives.dart:32   parentData: <none> (can use size)
js_primitives.dart:32   constraints: BoxConstraints(w=2049.0, h=154.8)
js_primitives.dart:32   size: Size(2049.0, 154.8)
js_primitives.dart:32 This RenderObject has no descendants.
js_primitives.dart:32 ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Steps to Reproduce

Fails with latest DevTools running in Flutter Web.  I've currently worked around the problem by detecting (kIsWeb) and not using a dashPath when plotting a trace in our charting package.

I can build a version of DevTools that doesn't detect kIsWeb to show the crash or if you have PR that fixes the problem I can patch in the change to a local engine build.

Fails with tip of Flutter (Flutter 1.14.7-pre.24)

**Comment by hterkelsen** [comment] 2020-01-31 18:22
Duplicate of https://github.com/flutter/flutter/issues/48386

`extractPath` is not implemented yet

**Closed by hterkelsen** 2020-01-31 18:22 UTC
Labels: ☸ platform-web
