### ISSUE TITLE
Error while generating iOS archive. rsync error shown in the output logs of archive.

### ISSUE THREAD

**Issue by meet7-sagar23** [flutter/flutter#124592] opened 2023-04-11 14:52 UTC
## Steps to Reproduce

Error is faced after generating the iOS build via flutter. The main issue is faced while generating the build for iOS once the flutter build is generated.

```shell
[20:21:09] [~/Documents/flutter/meet7-flutter] git(chat_enhancement) ❱❱❱ fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-IN)
    • Flutter version 3.7.8 on channel stable at /Users/sagar.ghag23/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (3 weeks ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/sagar.ghag23/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64 (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
[20:21:24] [cost 9.955s] fvm flutter doctor -v    
```

Here is the issue that printed in console: -

```shell
mkdir -p /Users/sagar.ghag23/Library/Developer/Xcode/DerivedData/Runner-fnebknbvmcsbowghfhtaushudeyb/Build/Intermediates.noindex/ArchiveIntermediates/dev/BuildProductsPath/Release-dev-iphoneos/Runner.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/openssl_grpc.framework" "/Users/sagar.ghag23/Library/Developer/Xcode/DerivedData/Runner-fnebknbvmcsbowghfhtaushudeyb/Build/Intermediates.noindex/ArchiveIntermediates/dev/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks"
building file list ... rsync: link_stat "/Users/sagar.ghag23/Documents/flutter/meet7-flutter/ios/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/openssl_grpc.framework" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code

warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'abseil' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Libuv-gRPC' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'BoringSSL-GRPC' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-Core' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-C++' from project 'Pods')
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/sagar.ghag23/Library/Developer/Xcode/DerivedData/Runner-fnebknbvmcsbowghfhtaushudeyb/Build/Intermediates.noindex/ArchiveIntermediates/dev/IntermediateBuildFilesPath/Runner.build/Release-dev-iphoneos/Runner.build/Script-A2CE221546BD9333C4932EC4.sh (in target 'Runner' from project 'Runner')
(1 failure)
```

**Comment by darshankawar** [comment] 2023-04-12 06:20
@meet7-sagar23 
Can you upgrade your version to latest (3.7.10) or switch to latest master and run your scenario again to see if you still get same behavior or not ?

Looks like you are hitting https://github.com/flutter/flutter/issues/123890

**Comment by darshankawar** [comment] 2023-05-04 05:11
Good to know the issue is resolved. Closing based on above comment.

**Closed by darshankawar** 2023-05-04 05:11 UTC
Labels: in triage
