### ISSUE TITLE
[Add2App] [iOS] Supports build Flutter module as a Framework?

### ISSUE THREAD

**Issue by hnvn** [flutter/flutter#25323] opened 2018-12-13 11:04 UTC
I want to integrate my Flutter module into my existing app. I follow this [link](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) for a tutorial but it requires me to copy dart codes and assets into my existing project. That's not good. Is there any way to encapsulate my Flutter module as a Framework? and I can use that Framework without setting Flutter environment in my existing project.

**Comment by zoechi** [comment] 2018-12-13 11:07
Can you please elaborate on your project structure. 
Why do you think it requires you to copy Dart code?

**Comment by zoechi** [comment] 2018-12-13 13:49
Sounds like a duplicate of #24948
You even commented there. 
How is this issue different from #24948?

**Comment by hnvn** [comment] 2018-12-13 14:51
It's tricky and I still cannot get it working. It's good to have official support

**Comment by hnvn** [comment] 2018-12-14 11:06
I can get it working now. It takes two days to research. I think Flutter needs better document about this use case. I maybe write an article for it. But there's still a problem to be resolved, I still cannot build a universal framework.

**Closed** 2018-12-17 01:39 UTC
Labels: a: existing-apps, engine

**Comment by sdaduanbilei** [comment] 2018-12-25 09:18
Is there a demo, the idea is not to publish Flutter.framework and App.framework flutter_assets products through Pod, then the new project to get flutter business through pod install, can see your podspec file
@hnvn
