### ISSUE TITLE
gui was broken in lastest updates

### ISSUE THREAD

**Issue by nicksnz3k** [flutter/flutter#72725] opened 2020-12-21 16:59 UTC
i don't see text on my widgets after my app started. I see zero fps error in popup window. After screen refresh all is OK.
[https://ibb.co/7S15xSc](start broken screen)
it repeated on chrome, windows and android. Branch is master.
On Stable branch all is OK.

**Comment by timsneath** [comment] 2020-12-21 17:15
Duplicate of #72698

**Closed by timsneath** 2020-12-21 17:15 UTC
