### ISSUE TITLE
[iOS] Flutter.framework is too large when use flutter 1.12.13-hotfix5

### ISSUE THREAD

**Issue by GitTradWang** [flutter/flutter#47116] opened 2019-12-16 08:21 UTC
#### FLutter Doctor
```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
------------

### step 1 :
`flutter create demo_flutter `
### step 2 :
edit `pubspec.yaml` to add any dependencies   to auto create `Podfile`

such as:
```yaml
 shared_preferences: ^0.5.6
```

`flutter packages get `

### step 3 :
`flutter build ios --release`

and then you can find Flutter.framework in `build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/` like this: 

![image](https://user-images.githubusercontent.com/23413593/70890312-b4589280-201f-11ea-8952-aa4c49a8fa76.png)

**Comment by softronaut** [comment] 2019-12-16 08:33
Duplicate of https://github.com/flutter/flutter/issues/47114 and https://github.com/flutter/flutter/issues/47101.

**Comment by therealjohnsummer** [comment] 2019-12-16 10:56
If you can , rollback to 1.91 hotfix 6 which doesnt have this issue.

**Comment by iapicca** [comment] 2019-12-16 12:36
Hi @GitTradWang 
I see there's an open [issue](https://github.com/flutter/flutter/issues/47101) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2019-12-16 12:36 UTC

**Comment by GitTradWang** [comment] 2019-12-17 03:00
> 嗨@GitTradWang
> 我看到有一个开放的[问题，](https://github.com/flutter/flutter/issues/47101)解决你所描述的情况。
> 请继续解决该问题，
> 我将关闭当前问题，重复进行。
> 如果您不同意，请在评论中写下，
> 然后我将其重新打开。
> 谢谢

ok

**Comment by GitTradWang** [comment] 2019-12-17 03:07
@iapicca 
i used 1.12.13   to solve some PlatformView issues in Android 10 , so please fix this issue  
thanks!

**Comment by 305740166** [comment] 2019-12-27 04:16
> If you can , rollback to 1.91 hotfix 6 which doesnt have this issue.

how to rollback to 1.91 hotfix 6.
