### ISSUE TITLE
FlutterViews are overlap in a Fragment.

### ISSUE THREAD

**Issue by StephenZKCurry** [flutter/flutter#59121] opened 2020-06-10 02:12 UTC
I use bottomNavigationView to switch two fragments which both use flutterView to display flutter ui,I quit the app to background,when I return the app to the foreground,these two flutterViews are overlap in the fragment.This proplem also appears when the host activity changed from invisible to visible,for example,jump to a new activity and return.Has anyone met the same problem with me?

**MainActivity.java**
```java
public class MainActivity extends AppCompatActivity {

    private Fragment1 fragment1;
    private Fragment2 fragment2;
    
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        showFragment(0);

        BottomNavigationView bottomNavigationView = findViewById(R.id.bnv_bar);
        bottomNavigationView.setOnNavigationItemSelectedListener(item -> {
            switch (item.getItemId()) {
                case R.id.menu_item_home:
                    showFragment(0);
                    break;
                case R.id.menu_item_knowledgesystem:
                    showFragment(1);
                    break;
                default:
                    break;
            }
            return true;
        });
    }

    private void showFragment(int index) {
        FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
        hideFragment(ft);
        switch (index) {
            case 0:
                if (fragment1 == null) {
                    fragment1 = new Fragment1();
                    ft.add(R.id.fl_container, fragment1, Fragment1.class.getName());
                } else {
                    ft.show(fragment1);
                }
                break;
            case 1:
                if (fragment2 == null) {
                    fragment2 = new Fragment2();
                    ft.add(R.id.fl_container, fragment2, Fragment2.class.getName());
                } else {
                    ft.show(fragment2);
                }
                break;
            default:
                break;
        }
        ft.commit();
    }

    private void hideFragment(FragmentTransaction ft) {
        if (fragment1 != null) {
            ft.hide(fragment1);
        }
        if (fragment2 != null) {
            ft.hide(fragment2);
        }
    }
}
```

**activity_main.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <FrameLayout
        android:id="@+id/fl_container"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bnv_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:backgroundTint="#fff"
        app:labelVisibilityMode="labeled"
        app:menu="@menu/menu_bottom_navigation" />

</LinearLayout>
```

**Fragment1.java**
```java
public class Fragment1 extends Fragment {

    private FlutterView flutterView;
    private FlutterEngine flutterEngine;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_test, container, false);
        flutterView = view.findViewById(R.id.flutter_view);

        flutterEngine = new FlutterEngine(getActivity());
        flutterEngine.getNavigationChannel().setInitialRoute("route2");
        flutterEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );
        flutterView.attachToFlutterEngine(flutterEngine);

        return view;
    }

    @Override
    public void onResume() {
        super.onResume();
        flutterEngine.getLifecycleChannel().appIsResumed();
    }

    @Override
    public void onPause() {
        super.onPause();
        flutterEngine.getLifecycleChannel().appIsInactive();
    }

    @Override
    public void onStop() {
        super.onStop();
        flutterEngine.getLifecycleChannel().appIsPaused();
    }

    @Override
    public void onDestroy() {
        flutterView.detachFromFlutterEngine();
        super.onDestroy();
    }
}
```

**Fragment2.java**
```java
public class Fragment2 extends Fragment {

    private FlutterView flutterView;
    private FlutterEngine flutterEngine;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_test, container, false);
        flutterView = view.findViewById(R.id.flutter_view);

        flutterEngine = new FlutterEngine(getActivity());
        flutterEngine.getNavigationChannel().setInitialRoute("route2");
        flutterEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );
        flutterView.attachToFlutterEngine(flutterEngine);

        return view;
    }

    @Override
    public void onResume() {
        super.onResume();
        flutterEngine.getLifecycleChannel().appIsResumed();
    }

    @Override
    public void onPause() {
        super.onPause();
        flutterEngine.getLifecycleChannel().appIsInactive();
    }

    @Override
    public void onStop() {
        super.onStop();
        flutterEngine.getLifecycleChannel().appIsPaused();
    }

    @Override
    public void onDestroy() {
        flutterView.detachFromFlutterEngine();
        super.onDestroy();
    }
}
```

**Comment by TahaTesser** [comment] 2020-06-10 09:49
Hi @StephenZKCurry 
Can you please take a look at this?  https://github.com/flutter/flutter/issues/58848
Are you experiencing same issue?
Thank you

**Comment by weichongchong** [comment] 2020-06-22 07:39
I met same issue.

**Comment by weichongchong** [comment] 2020-06-22 07:47
Has someone solved it？

**Comment by weichongchong** [comment] 2020-06-22 07:52
appear on android version  OS10

**Comment by weichongchong** [comment] 2020-06-22 07:53
appear on android 10

**Comment by TahaTesser** [comment] 2020-07-02 10:17
Hi @StephenZKCurry  @weichongchong  
Tested on latest `master` channel and it fragments is hide and added new fragment 

<details> 
<summary>Activity</summary> 

``` 
import android.os.Bundle
import androidx.fragment.app.FragmentActivity
import androidx.fragment.app.FragmentManager
import com.google.android.material.bottomnavigation.BottomNavigationView
import io.flutter.embedding.android.FlutterFragment

class NewEngineActivity  : FragmentActivity() {
    companion object {
        private const val TAG_FLUTTER_FRAGMENT = "flutter_fragment"

    }

    private var flutterFragment: FlutterFragment? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.new_activity)

        val fragmentManager: FragmentManager = supportFragmentManager

        flutterFragment = fragmentManager
            .findFragmentByTag(TAG_FLUTTER_FRAGMENT) as FlutterFragment?

        if (flutterFragment == null) {
            var newFlutterFragment = FlutterFragment.withNewEngine()
                .initialRoute("/new_fragment")
                .build<FlutterFragment>()



            flutterFragment = newFlutterFragment
            fragmentManager
                .beginTransaction()
                .add(
                    R.id.fragment_container_new,
                    newFlutterFragment,
                    TAG_FLUTTER_FRAGMENT
                )
                .commit()

            fun showFragment(index: Int) {
                fragmentManager.beginTransaction().hide(newFlutterFragment).commit()

                when(index){
                    0 -> {
                        var newFlutterFragment = FlutterFragment.withNewEngine()
                            .initialRoute("/new_fragment")
                            .build<FlutterFragment>()
                        fragmentManager.beginTransaction().replace(     R.id.fragment_container_new,
                            newFlutterFragment,
                            TAG_FLUTTER_FRAGMENT).commit()

                    }

                    1 -> {
                        var defaultFlutterFragment = FlutterFragment.createDefault()
                        flutterFragment = newFlutterFragment
                        fragmentManager
                            .beginTransaction()
                            .replace(
                                R.id.fragment_container_new,
                                newFlutterFragment,
                                TAG_FLUTTER_FRAGMENT
                            )
                            .commit()
                        fragmentManager.beginTransaction().add(     R.id.fragment_container_new,
                            defaultFlutterFragment,
                            TAG_FLUTTER_FRAGMENT).commit()
                    }
                }
            }

            val bottomNavigationView = findViewById<BottomNavigationView>(R.id.bnv_bar)
        val mOnNavigationItemSelectedListener =    bottomNavigationView.setOnNavigationItemSelectedListener {
                when (it.itemId) {
                    R.id.menu_one -> showFragment(0)
                    R.id.menu_two -> showFragment(1)
                    else -> {
                    }
                }
                false

            }


        }
    }
}
``` 

</details> 


<details> 
<summary>layout</summary> 

``` 
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:gravity="center_horizontal"
    tools:context=".NewEngineActivity">

    <FrameLayout
        android:id="@+id/fragment_container_new"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bnv_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:backgroundTint="#fff"
        app:labelVisibilityMode="labeled"
        app:menu="@menu/menu_bottom_navigation" />

</LinearLayout>

``` 

</details> 

<details> 
<summary>menu_bottom_navigation</summary> 

``` 
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:id="@+id/menu_one"
        android:title="MMenu One" />
    <item android:id="@+id/menu_two"
        android:title="MMenu Two" />
</menu>
``` 

</details> 

![flutter_01](https://user-images.githubusercontent.com/48603081/86346920-3a19f380-bc7b-11ea-80f1-9ff3f7bd4fbf.png)

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.20.0-3.0.pre.124, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.20.0-3.0.pre.124 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision ec3368ae45 (4 hours ago), 2020-07-02 01:58:01 -0400
    • Engine revision 65ac8be350
    • Dart version 2.9.0 (build 2.9.0-20.0.dev f8ff12008e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.5 19F101
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!

``` 

</details> 

Make sure to commit hide fragment before adding new one
```
                fragmentManager.beginTransaction().hide(newFlutterFragment).commit()

```

**Comment by TahaTesser** [comment] 2020-07-02 10:19
@StephenZKCurry 
Since the issue is not reproducible and no response

Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by panda912** [comment] 2020-07-04 11:37
@TahaTesser Hi, I saw your sample code [above](https://github.com/flutter/flutter/issues/59121#issuecomment-652920617), you called `replace` after `hide` , I don't know what the point of calling `hide` , because `replace` is essentially the same as calling `remove` all fragments and `add` one.

**Comment by TahaTesser** [comment] 2020-07-06 09:14
@panda912 
I kept `hide` since i wanted to show author has missed adding `commit()`.

**Comment by weichongchong** [comment] 2020-07-17 03:31
> @panda912
> I kept `hide` since i wanted to show author has missed adding `commit()`.



> Hi @StephenZKCurry @weichongchong
> Tested on latest `master` channel, Android 10 and it fragments is hide and added new fragment
> 
> Activity
> ```
> import android.os.Bundle
> import androidx.fragment.app.FragmentActivity
> import androidx.fragment.app.FragmentManager
> import com.google.android.material.bottomnavigation.BottomNavigationView
> import io.flutter.embedding.android.FlutterFragment
> 
> class NewEngineActivity  : FragmentActivity() {
>     companion object {
>         private const val TAG_FLUTTER_FRAGMENT = "flutter_fragment"
> 
>     }
> 
>     private var flutterFragment: FlutterFragment? = null
> 
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         setContentView(R.layout.new_activity)
> 
>         val fragmentManager: FragmentManager = supportFragmentManager
> 
>         flutterFragment = fragmentManager
>             .findFragmentByTag(TAG_FLUTTER_FRAGMENT) as FlutterFragment?
> 
>         if (flutterFragment == null) {
>             var newFlutterFragment = FlutterFragment.withNewEngine()
>                 .initialRoute("/new_fragment")
>                 .build<FlutterFragment>()
> 
> 
> 
>             flutterFragment = newFlutterFragment
>             fragmentManager
>                 .beginTransaction()
>                 .add(
>                     R.id.fragment_container_new,
>                     newFlutterFragment,
>                     TAG_FLUTTER_FRAGMENT
>                 )
>                 .commit()
> 
>             fun showFragment(index: Int) {
>                 fragmentManager.beginTransaction().hide(newFlutterFragment).commit()
> 
>                 when(index){
>                     0 -> {
>                         var newFlutterFragment = FlutterFragment.withNewEngine()
>                             .initialRoute("/new_fragment")
>                             .build<FlutterFragment>()
>                         fragmentManager.beginTransaction().replace(     R.id.fragment_container_new,
>                             newFlutterFragment,
>                             TAG_FLUTTER_FRAGMENT).commit()
> 
>                     }
> 
>                     1 -> {
>                         var defaultFlutterFragment = FlutterFragment.createDefault()
>                         flutterFragment = newFlutterFragment
>                         fragmentManager
>                             .beginTransaction()
>                             .replace(
>                                 R.id.fragment_container_new,
>                                 newFlutterFragment,
>                                 TAG_FLUTTER_FRAGMENT
>                             )
>                             .commit()
>                         fragmentManager.beginTransaction().add(     R.id.fragment_container_new,
>                             defaultFlutterFragment,
>                             TAG_FLUTTER_FRAGMENT).commit()
>                     }
>                 }
>             }
> 
>             val bottomNavigationView = findViewById<BottomNavigationView>(R.id.bnv_bar)
>         val mOnNavigationItemSelectedListener =    bottomNavigationView.setOnNavigationItemSelectedListener {
>                 when (it.itemId) {
>                     R.id.menu_one -> showFragment(0)
>                     R.id.menu_two -> showFragment(1)
>                     else -> {
>                     }
>                 }
>                 false
> 
>             }
> 
> 
>         }
>     }
> }
> ```
> 
> layout
> menu_bottom_navigation
> ![flutter_01](https://user-images.githubusercontent.com/48603081/86346920-3a19f380-bc7b-11ea-80f1-9ff3f7bd4fbf.png)
> 
> flutter doctor -v
> Make sure to commit hide fragment before adding new one
> 
> ```
>                 fragmentManager.beginTransaction().hide(newFlutterFragment).commit()
> ```

replace will first remove fragment and add one, the fragment will rebuild every time. but we don't
want use this way.  we want use the author's code. "hide and show" -way  you can try the author's code

**Comment by panda912** [comment] 2020-07-22 10:05
My temporary solution,  only for reference:

Android kotlin code:

```kotlin
package com.ecovacs.scanbot.flutter

import io.flutter.embedding.android.FlutterFragment
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.FlutterEngineCache
import io.flutter.plugin.common.MethodChannel

/**
 * Created by panda on 2020/7/4 17:17.
 */
class MyFlutterFragment : FlutterFragment() {

    private var fragmentHiddenChangedChannel: MethodChannel? = null

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        fragmentHiddenChangedChannel = MethodChannel(
                flutterEngine.dartExecutor, "flutter.fragment/onHiddenChanged")
    }

    override fun onHiddenChanged(hidden: Boolean) {
        super.onHiddenChanged(hidden)
        fragmentHiddenChangedChannel?.invokeMethod("onHiddenChanged", hidden)
    }
}
```

flutter dart code:
```dart
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

const _fragmentHiddenChangedChannel =
    MethodChannel("flutter.fragment/onHiddenChanged");

abstract class BaseFragmentState<T extends StatefulWidget> extends State<T>
    with WidgetsBindingObserver {
  bool _hidden = false;

  @override
  void initState() {
    super.initState();
    _fragmentHiddenChangedChannel.setMethodCallHandler((call) async {
      if (call.method == "onHiddenChanged") {
        onHiddenChanged(call.arguments);
      }
    });
  }

  void onHiddenChanged(hidden) {
    setState(() {
      _hidden = hidden;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: !_hidden,
      child: buildWidget(context),
    );
  }

  Widget buildWidget(BuildContext context);

}

```

**Comment by TahaTesser** [comment] 2020-12-07 14:30
Hi @StephenZKCurry  @panda912  @weichongchong 
I tried to reproduce it again with the latest `master` using https://github.com/flutter/flutter/issues/59121#issue-635873142, I cannot see any overlap when switching between fragments 
Here is the complete code sample, done in java
[fragment_overlap_sample.zip](https://github.com/flutter/flutter/files/5653264/fragment_overlap_sample.zip)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.92, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.25.0-5.0.pre.92 at C:\Code\flutter_master
    • Framework revision 90f08769a3 (3 hours ago), 2020-12-07 12:33:03 +0100
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 87.0.664.52

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-12-30 11:01
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 11:01 UTC
Labels: a: existing-apps, engine, platform-android, waiting for customer response
