### ISSUE TITLE
flutter web initial load speed canvaskit.wasm

### ISSUE THREAD

**Issue by gururajahegde** [flutter/flutter#82810] opened 2021-05-18 13:53 UTC
download of canvaskit.wasm is taking 10-20 seconds, in India, tried from multiple internet providers, multiple locations. 
Initial flutter web page loading is taking time because of this.
 
step to reproduce:
curl -o /dev/null -s "https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.wasm" -w %{time_connect}:%{time_starttransfer}:%{time_total}

Tried downloading files of similar size from our server, which is faster.

Is there anyway in build, where we can specify flutter to download this file from our server(change url, or any other cdn).

using   "flutter web build"  to build package

**Comment by dariusstephen** [comment] 2021-05-22 09:03
I also encountered this running. It is causing the flutter web startup to be very slow (>5s).
Any workaround on this issue?

**Comment by TahaTesser** [comment] 2021-05-27 13:04
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/76009
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-27 13:04 UTC
Labels: in triage
