### ISSUE TITLE
Allow to resize image by fraction or percentage

### ISSUE THREAD

**Issue by Afsar-Pasha** [flutter/flutter#50419] opened 2020-02-08 19:55 UTC
Currently `ResizeImage` / `ui.instantiateImageCodec` only supports resizing image by pixels which requires us to know the dimension of the image prior to resize, also flutter doesn't provides a way to get image dimension without fully decoding, so it would be useful if we can resize them image relative to its original dimension by using fraction or by percentage.

**Comment by dnfield** [comment] 2020-02-11 06:51
Related: https://github.com/flutter/flutter/issues/50022

**Comment by dnfield** [comment] 2020-02-25 09:50
I'm a little skeptical about how useful this would be.

The purpose of resizing to pixels is to make sure the image won't use more memory than you expect. But a fraction of an image you don't know the dimensions of could still be enough to OOM your application, or it might make the image into a 1x1 pixel image.

If you could determine the size ahead of time, this would be somewhat more helpful, but then you could also pretty easily do a ratio or fractio nyourself.

Alternatively, you might want something where the cache width/height maintain the aspect ratio of the image, such that you could set the max dimension of the largest side of the image instead of needing to know the aspect ratio ahead of time.  Is that what you're looking for?  If so, then this bug is a duplicate of #48885

**Comment by Afsar-Pasha** [comment] 2020-02-25 17:01
@dnfield 
No, its not duplicate of #48885.

This can be used to resize image based on devicePixelRatio (eg, if `devicePixelRatio` is `x` and image is made for `devicePixelRatio` `y` then the image can be resized to a fraction of `x / y`).
Whereas `ResizeImage` or #48885 needs to know the size of widget therefore can't precache.

**Comment by dnfield** [comment] 2020-02-25 18:13
Ahh I see, so you might have an image where you know it's scale but you don't know its physical dimensions.  That makes sense.

**Comment by dnfield** [comment] 2020-03-03 18:59
I'm going to close this as a duplicate of #50022 - if we can get that resolved (let you determine the physical dimensions of an image before decoding it), this is really just a trivial extension, and probably something we wouldn't end up supporting directly in the framework anyway since it's kind of a niche use case.

**Closed by dnfield** 2020-03-03 18:59 UTC
Labels: a: images, framework, proposal, severe: new feature

**Comment by iamfel** [comment] 2021-04-25 18:44
Really need this!
