### ISSUE TITLE
DynamicLibrary.open('JavaScriptCore.framework/JavaScriptCore'); does not work any more since version 3.22.0

### ISSUE THREAD

**Issue by niklasvongarrel** [flutter/flutter#149407] opened 2024-05-31 12:48 UTC
### Steps to reproduce

1. Use "flutter upgrade" to upgrade to the latest stable version (3.22.1 at the time I created this issue)
2. Create a new Flutter project with "flutter create MyProject"
3. Go to widget_test.dart
4. Add the following line at the beginning of the file: import 'dart:ffi';
5. Add the following line at the beginning of testWidgets('Counter increments smoke test': DynamicLibrary.open('JavaScriptCore.framework/JavaScriptCore');
6. Execute the test

### Expected results

The library file can be loaded. 
When using "flutter downgrade" to downgrade to version 3.19.2, the library file can be loaded.

### Actual results

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following ArgumentError was thrown running a test:
Invalid argument(s): Failed to load dynamic library 'JavaScriptCore.framework/JavaScriptCore':
dlopen(JavaScriptCore.framework/JavaScriptCore, 0x0001): tried:
'JavaScriptCore.framework/JavaScriptCore' (no such file),
'/System/Volumes/Preboot/Cryptexes/OSJavaScriptCore.framework/JavaScriptCore' (no such file),
'/Users/niklas/flutter/bin/cache/artifacts/engine/darwin-x64/./JavaScriptCore.framework/JavaScriptCore'
(no such file), '/usr/local/lib/./JavaScriptCore.framework/JavaScriptCore' (no such file),
'/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/./JavaScriptCore.framework/JavaScriptCore' (no
such file),
'/Users/niklas/flutter/bin/cache/artifacts/engine/darwin-x64/../../../JavaScriptCore.framework/JavaScriptCore'
(no such file),
'/Users/niklas/flutter/bin/cache/artifacts/engine/darwin-x64/Frameworks/JavaScriptCore.framework/JavaScriptCore'
(no such file),
'/Users/niklas/flutter/bin/cache/artifacts/engine/darwin-x64/./JavaScriptCore.framework/JavaScriptCore'
(no such file), '/usr/local/lib/./JavaScriptCore.framework/JavaScriptCore' (no such file),
'/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/./JavaScriptCore.framework/JavaScriptCore' (no
such file),
'/Users/niklas/flutter/bin/cache/artifacts/engine/darwin-x64/../../../JavaScriptCore.framework/JavaScriptCore'
(no such file),
'/Users/niklas/flutter/bin/cache/artifacts/engine/darwin-x64/Frameworks/JavaScriptCore.framework/JavaScriptCore'
(no such file), '/usr/lib/JavaScriptCore.framework/JavaScriptCore' (no such file, not in dyld
cache), 'JavaScriptCore.framework/JavaScriptCore' (no such file)

When the exception was thrown, this was the stack:
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main.<anonymous closure> (file:///Users/niklas/AndroidStudioProjects/dynamiclib/test/widget_test.dart:17:20)
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:29)
<asynchronous suspension>
#4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Counter increments smoke test
```
### Code sample

<details open><summary>Code sample</summary>

```dart
DynamicLibrary.open('JavaScriptCore.framework/JavaScriptCore');
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-CH)
    • Flutter version 3.22.1 on channel stable at /Users/niklas/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (9 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /Users/niklas/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc2
    • Java binary at: /Applications/Android Studio Flamingo.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Flamingo.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • ZCH-IP-08 (mobile)              • 00008120-000641C03AF8A01E • ios            • iOS 17.1 21B80
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 125.0.6422.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dcharkes** [comment] 2024-05-31 13:11
Hi @niklasvongarrel! Nice to meet you!

Could you please elaborate on how `JavaScriptCore.framework/JavaScriptCore` is bundled with the app? Did you add it to the build yourself? Or were you expecting this framework to always be bundled with the app? What is your project setup, a `--template=plugin_ffi`? or the new experimental `--template=package_ffi`?

Is this MacOS or iOS?

Could you please provide a minimal reproduction project as a Github repo?

**Comment by niklasvongarrel** [comment] 2024-05-31 13:54
Hi @dcharkes.

The JavaScriptCore library is natively available on iPhones and Macs.
With DynamicLibrary.open('JavaScriptCore.framework/JavaScriptCore'); I am loading them at runtime.
However, since version 3.22.0, this does not work any more.

I literally just used "flutter create" to create a brand new project, without any extra configurations.

The issue if for both MacOS and iOS.

Here the minimal reproduction project: https://github.com/niklasvongarrel/dynamic-library-open-bug/blob/main/test/widget_test.dart
Just execute the test while having Flutter version 3.22.0 or 3.22.1.

**Comment by dcharkes** [comment] 2024-05-31 14:09
> ```dart
> DynamicLibrary.open('JavaScriptCore.framework/JavaScriptCore');
> ```

I believe nothing changed in `dart:ffi` with regards to `DynamicLibrary`.

@vashworth @jmagman Any chance we changed anything with the dynamic loading path (`DYLD_LIBRARY_PATH`, `@executable_path` and friends) on MacOS/iOS in a recent Flutter version? `DynamicLibrary.open` simply calls `dlopen` in C with the path being passed to it. So if this used to work and it no longer does it's probably the case that the native build slightly changed.

@niklasvongarrel Any chance you could try 3.21.x and 3.20.x for us to know when this behavior change was introduced?

@niklasvongarrel what command are you running? `flutter run`?

**Comment by hpelitebook745G2** [comment] 2024-05-31 19:36
I haven't downgraded yet and it's already Saturday here in Singapore but now that I realize, I recently upgraded my Flutter version from `3.19.2` to `3.22.0` and now I'm having exactly the same error in my TestFlight builds in iOS platform. It used to work when I had the former version.

I reported the same [issue](https://github.com/abner/flutter_js/issues/151) in `flutter_js` repo.

**Comment by jmagman** [comment] 2024-06-01 00:42
@niklasvongarrel thanks for the easy reproduction test.

@dcharkes I think I narrowed it down to c12d0068c5f0bd7383733151d65d99618985e292 (though I'd appreciate a double-check) which changed the version of Xcode the engine is built against from Xcode 14.3.1/iOS 16.4 to Xcode 15.0/iOS 17.  But I'm not sure why that would impact this since it's opening at runtime based on the target device's SDK etc?

**Comment by niklasvongarrel** [comment] 2024-06-03 04:58
@dcharkes With my minimal reproduction project: https://github.com/niklasvongarrel/dynamic-library-open-bug/blob/main/test/widget_test.dart, you simply have to run "flutter test" to reproduce the bug.

The bug was already introduced with https://github.com/flutter/flutter/releases/tag/3.22.0-12.0.pre
With the tag before (https://github.com/flutter/flutter/releases/tag/3.19.6) the library file could still be loaded.

**Comment by huycozy** [comment] 2024-06-03 05:20
I can reproduce the issue on the latest Flutter stable 3.22.1 and master `3.23.0-13.0.pre.69` with the [given sample project](https://github.com/niklasvongarrel/dynamic-library-open-bug/blob/main/test/widget_test.dart) whilst it doesn't occur on the previous release 3.19.6.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (11 hours ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.69, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.69 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 124aacbaef (2 days ago), 2024-05-31 22:32:25 -0400
    • Engine revision d81edf635a
    • Dart version 3.5.0 (build 3.5.0-214.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 125.0.6422.113

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jason-simmons** [comment] 2024-06-05 19:51
Confirmed that this started with https://github.com/flutter/engine/commit/d80fe1cb5854851761f94f5637db5db1ae716164

It looks like recent SDK/Xcode versions include some policy changes affecting the default paths used to search for dynamic libraries (see https://forums.developer.apple.com/forums/thread/737920)

Loading this library does work on current builds when using a fully qualified path:
`DynamicLibrary.open('/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore');`

**Comment by a-siva** [comment] 2024-06-05 20:50
@dcharkes are you investigating this?

**Comment by dcharkes** [comment] 2024-06-05 20:54
> @dcharkes are you investigating this?

I believe @jason-simmons comment above explains what's going on.

**Comment by a-siva** [comment] 2024-06-06 16:18
Does it mean this is working as intended and the issue can be closed ?

**Comment by niklasvongarrel** [comment] 2024-06-06 16:23
No, it does not work as intended.
Having to specify the full path is not an option as one cannot know it.
There are multiple paths under which the library can be located.
And they all have to be checked when calling DynamicLibrary.open.

**Comment by hpelitebook745G2** [comment] 2024-06-10 12:50
should we expect a patch version from Flutter @dcharkes ?

**Comment by dcharkes** [comment] 2024-06-10 13:03
If `/System/Library/Frameworks/` is the place where this library usually lives, then we could try to add that path to the `DYLD_FALLBACK_LIBRARY_PATH` in the Flutter build for all Flutter apps. This would kind of undo:

> It looks like recent SDK/Xcode versions include some policy changes affecting the default paths used to search for dynamic libraries (see https://forums.developer.apple.com/forums/thread/737920)

However, I am somewhat weary of trying to deviate from what Apple is doing by default. WDYT @jmagman @vashworth?
Maybe the better question to ask is, how does Apple intend standalone apps to reuse frameworks already installed on the host machine?

**Comment by jmagman** [comment] 2024-06-10 16:51
> However, I am somewhat weary of trying to deviate from what Apple is doing by default. WDYT @jmagman @vashworth? Maybe the better question to ask is, how does Apple intend standalone apps to reuse frameworks already installed on the host machine?

I agree.  I don't think ffi should radically deviate from how the native system expects loads.  If native apps require an absolute path, then I don't see why Flutter apps should do anything too differently, assuming Flutter's tooling and build systems allow it to be loaded in the same way.

**Comment by a-siva** [comment] 2024-06-10 19:23
If the consensus is to not deviate from how the native system works maybe we can close this issue .

**Comment by dcharkes** [comment] 2024-06-10 19:27
> Having to specify the fully qualified path is not an option as one cannot know it.

@niklasvongarrel What are alternative paths to `/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore` that this framework can be? If MacOS always installs it in the same location, an absolute path can be used. `/System/Library/Frameworks/JavaScriptCore.framework` exists on my machine.

**Comment by niklasvongarrel** [comment] 2024-06-11 05:48
@dcharkes It is not only about this specific library.
DynamicLibrary.open is for all kinds of libraries which are loaded at runtime.
From the logs in my issue description (refer to "Actual results") I can see that "DynamicLibrary.open" tried various locations.
So my conclusion is that it might not be that all libraries are always under "/System/Library/".
Maybe it is the case for newer iOS and MacOS versions but it might not be for older ones.
Just using the absolute path is too risky in my opinion.

This is why I solved the problem for my project by linking the library directly in my project and using "DynamicLibrary.process()" instead.
Steps to do so:

1. Open the Runner.xcworkspace file in the "ios" folder in Xcode
2. Runner -> Build Phases
3. Under "Link Binary With Libraries" I added "JavaScriptCore.framework"
4. Verify that the library is added in the "project.pbxproj" 

After calling "DynamicLibrary.process()" I can then call things like this:
`final JSContextGroupCreate = jsCoreLib
        .lookup<NativeFunction<Pointer Function()>>('JSContextGroupCreate')
        .asFunction<Pointer Function()>();`

Unfortunately, this only works for app builds.
When executing tests with "flutter test", loading the library like this does not work.
Therefore, I used a try catch to have both things working:

` 
try {
      return DynamicLibrary.open(
        '/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore',
      );
    } catch (e) {
      return DynamicLibrary.process();
    }
`
If possible, the absolute path is used.
This works fine on all current iOS and MacOS versions.
Just in case it does not work on older versions, I load the linked library.

**Comment by dcharkes** [comment] 2024-06-11 07:08
> From the logs in my issue description (refer to "Actual results") I can see that "DynamicLibrary.open" tried various locations.

This is exactly the list of locations Apple has changed. Therefore we're hesitant to add such location back.

> So my conclusion is that it might not be that all libraries are always under "/System/Library/".

Not all libraries, but it might be that a specific subset of libraries available on the MacOS systems will always be available on the same path. Again, the question is how Apple intends these libs to be used.

> I solved the problem for my project by linking the library directly in my project

Not relying on a library being available on a target device is always the safe option. 👍 

(Also if there are different versions of the library, you might find an older library on the system your app is deployed to. Bundling the library prevents such issues.)

> Therefore, I used a try catch to have both things working

It's probably slightly cleaner to use `Directory('/System/Library/Frameworks/JavaScriptCore.framework/').existsSync()` instead of having a try catch.

I'll close this issue.

Anyone who stumbles on the same issue can follow the steps mentioned above.

**Closed by dcharkes** 2024-06-11 07:08 UTC
Labels: c: regression, dependency: dart, has reproducible steps, P1, team-engine, triaged-engine, dependency:dart-triaged, found in release: 3.22, found in release: 3.23
