### ISSUE TITLE
tar: Error exit delayed from previous errors.

### ISSUE THREAD

**Issue by Mrwangmingchao** [flutter/flutter#61686] opened 2020-07-17 01:15 UTC
When I run 'flutter doctor' it show 
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
    • Flutter version 1.17.5 at /Library/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available`
```

But when I run 'flutter pub get' it show
```
__MACOSX/flutter_verification_box/._README.md: Truncated tar archive    
tar: Error exit delayed from previous errors.                           
Failed to extract .tar.gz stream to /Library/flutter/.pub-cache/_temp/dirsllhkl (exit code 1).
package:pub/src/io.dart 898:5                extractTarGz               
===== asynchronous gap ===========================                      
package:pub/src/source/hosted.dart 398:11    BoundHostedSource._download
===== asynchronous gap ===========================                      
package:pub/src/source/hosted.dart 264:13    BoundHostedSource.downloadToSystemCache
package:pub/src/entrypoint.dart 407:48       Entrypoint._get.<fn>       
dart:async                                   runZoned                   
package:pub/src/http.dart 279:10             withDependencyType         
package:pub/src/entrypoint.dart 403:12       Entrypoint._get            
dart:async                                   Future.wait                
package:pub/src/entrypoint.dart 252:18       Entrypoint.acquireDependencies
dart:async                                   _completeOnAsyncReturn     
package:pub/src/solver/version_solver.dart   VersionSolver.solve        
dart:async                                   _completeOnAsyncReturn     
package:pub/src/source/hosted.dart           BoundHostedSource.withPrefetching
dart:async                                   _completeOnAsyncReturn     
package:pub/src/rate_limited_scheduler.dart  RateLimitedScheduler.withPrescheduling
dart:async                                   _completeOnAsyncReturn     
package:pub/src/source/hosted.dart           BoundHostedSource.withPrefetching.<fn>
dart:async                                   _completeOnAsyncReturn     
package:pub/src/solver/version_solver.dart   VersionSolver.solve.<fn>   
dart:async                                   _completeOnAsyncReturn     
package:pub/src/solver/version_solver.dart   VersionSolver._result      
This is an unexpected error. Please run                                 
                                                                        
    pub --trace '--verbosity=warning' get --no-precompile               
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in express-customer-app...                    
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
```

This error show after I update Mac os
Who can help me, thank you

**Comment by TahaTesser** [comment] 2020-07-17 10:11
Hi @Mrwangmingchao 
Based on your error 
```
This is an unexpected error. Please run                                 
                                                                        
    pub --trace '--verbosity=warning' get --no-precompile               
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in express-customer-app...                    
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
```

From what I can see, the issue is related to `pub` rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-17 10:11 UTC
