### ISSUE TITLE
Error: NotSupportedError: Failed to load because no supported source was found.

### ISSUE THREAD

**Issue by Xzoky174** [flutter/flutter#86612] opened 2021-07-17 20:41 UTC
Getting this error when using the audioplayers package:
```
Error: NotSupportedError: Failed to load because no supported source was found.
    at Object.createErrorWithStack (http://localhost:51082/dart_sdk.js:5054:12)
    at Object._rethrow (http://localhost:51082/dart_sdk.js:37670:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51082/dart_sdk.js:37666:13)
    at Object._microtaskLoop (http://localhost:51082/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:51082/dart_sdk.js:37532:13)
    at http://localhost:51082/dart_sdk.js:33303:9
```

## Steps to Reproduce

1. Add the audioplayers package in the pubspec.yaml file below dependencies.
2. Get audio from the internet or just record some sample audio. 
3. Add the audio file under the assets in pubspec.yaml file. 
4. Anywhere in the main.dart file or any other file play audio using `AudioCache().play('audio/[any file].[file extension]');` (don't forget to import it first).
5. **Important: Run it on any web browser (chrome and edge are the only options currently)**.

**Expected results: I expected the audio file to play normally.**

**Actual results: I got the above error.**

<details>
  <summary>Logs</summary>
  
```
flutter run --verbose:
  [+88446 ms] Error: NotSupportedError: Failed to load because no supported source was found.
     at Object.createErrorWithStack (http://localhost:60696/dart_sdk.js:5054:12)
     at Object._rethrow (http://localhost:60696/dart_sdk.js:37670:16)
     at async._AsyncCallbackEntry.new.callback (http://localhost:60696/dart_sdk.js:37666:13)
     at Object._microtaskLoop (http://localhost:60696/dart_sdk.js:37526:13)
     at _startMicrotaskLoop (http://localhost:60696/dart_sdk.js:37532:13)
     at http://localhost:60696/dart_sdk.js:33303:9
```

</details>

**Comment by TahaTesser** [comment] 2021-07-19 14:06
Hi @Xzoky174 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/luanpotter/audioplayers/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-19 14:06 UTC
Labels: in triage
