### ISSUE TITLE
[camera] Supports wide-angle cameras

### ISSUE THREAD

**Issue by panzikeji** [flutter/flutter#133316] opened 2023-08-25 08:59 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

camera Supports wide-angle cameras

### Proposal

wide-angle

**Comment by dam-ease** [comment] 2023-08-25 11:51
Hi @panzikeji. There is a currently open issue proposing this in particular. Closing this as a duplicate of https://github.com/flutter/flutter/issues/91247.

**Closed by dam-ease** 2023-08-25 11:51 UTC
Labels: c: new feature, p: camera, package, c: proposal, in triage, team-ecosystem
