### ISSUE TITLE
Icons are rendered different in Desktop apps

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#82415] opened 2021-05-13 05:02 UTC
Icons on Windows and Mac OS apps are being rendered with a thicker line.

The image below shows an `IconButton`, rendered as a white icon with a thicker line, and a `CupertinoButton`, rendered as a blue icon, with normal thickness lines. 

Both look the same on Android and iOS though.

I am seeing a similar behavior for some texts as well.

![image001](https://user-images.githubusercontent.com/8120472/118079694-032e6700-b38f-11eb-8969-00f282190ae6.png)

**Comment by TahaTesser** [comment] 2021-05-13 10:34
Hi @feinstein 
Thanks for filing the issue!

I can notice difference different icon stroke width on `macOS` desktop only, other desktop platforms including Linux have regular width, also web on mac doesn't have this issue.

### Preview
| `windows` | `macos` | `linux` |
| --------------- | --------------- |  --------------- |
<img src="https://user-images.githubusercontent.com/48603081/118113726-50422580-b3ef-11eb-85fd-5aa458328b15.png" height="50" /> | <img src="https://user-images.githubusercontent.com/48603081/118113774-605a0500-b3ef-11eb-95f0-68b9123449d5.png" height="50" /> | <img src="https://user-images.githubusercontent.com/48603081/118113797-6a7c0380-b3ef-11eb-9226-2a770215df6a.png" height="50" /> |





Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(
                Icons.alarm,
              ),
              Icon(
                Icons.alarm_on,
              ),
              Icon(
                Icons.alarm_off,
              ),
              Icon(
                Icons.alarm_add,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
``` 

</details>

Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0
[✓] Connected device (3 available)
    • Taha's iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.5.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.3 20E232 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.212
    ! Error: Taha's iPhone is busy: Copying cache files from device. Xcode will
      continue when Taha's iPhone is finished. (code -10)
• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.163, on macOS 11.3 20E232 darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-2.0.pre.163 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 298f18b592 (7 hours ago), 2021-05-12 20:50:14 -0700
    • Engine revision a339374296
    • Dart version 2.14.0 (build 2.14.0-109.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233
[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0
[✓] Connected device (3 available)
    • Taha's iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.5.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.3 20E232 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.212
    ! Error: Taha's iPhone is busy: Copying cache files from device. Xcode will
      continue when Taha's iPhone is finished. (code -10)
• No issues found!
```
		
</details>


This is a known issue, closing as a duplicate of https://github.com/flutter/flutter/issues/67034

**Closed by TahaTesser** 2021-05-13 10:34 UTC
Labels: in triage

**Comment by feinstein** [comment] 2021-05-13 12:02
Thanks @TahaTesser
