### ISSUE TITLE
  Newest webview flutter has problem   On iOS 13.5.1

### ISSUE THREAD

**Issue by walkerwg** [flutter/flutter#61212] opened 2020-07-10 05:46 UTC
i have used the  flutter_echart   plugin that depends on webview flutter plugin (V0.3.22)to show Chart ,  and  i got problem that the chart will be stunk when scrolls on iOS 13.5.1, but Android and iOS lower version work well

please test it On iOS 13.5.1, thanks

**Comment by TahaTesser** [comment] 2020-07-10 12:41
Hi @walkerwg 
if you think this is a `webview_flutter` issue, can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample using just `webview_flutter`

If you can't reproduce the issue with only `webview_flutter` then probably the issue is related to a 3rd party plugin rather than with `webview_flutter` itself. Please open the issue in the dedicated [repository](https://github.com/entronad/flutter_echarts/issues).
		
Thank you

**Comment by walkerwg** [comment] 2020-07-16 09:41
macdeMacBook-Pro-2:~ wg$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/wg/Flutter/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/wg/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode_11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

####################

The following is my validating steps:
1 create one native iOS project
2 put  test.html and echarts.min.js  that used to show k-line chart in project
3 create one webview page to load local html

Result: h5 webview can zooms ok, cant stunk.

**Comment by TahaTesser** [comment] 2020-07-17 07:09
Hi @walkerwg 
To better address the issue, can you please provide a complete reproducible minimal code sample using just `webview_flutter`. Feel free to create to create repository for code sample and comment below 
Thank you

**Comment by walkerwg** [comment] 2020-07-17 10:56
it seems to  be well after i upgrade iOS to the lastest 13.6， i think it maybe a iOS bug on 13.5.1

thanks




            
            
                
                    
                            
                                
                            
                            
                                907029564
                            
                    
                        
                            
                                    邮箱：907029564@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 07/17/2020 15:10, Taha Tesser wrote: 
Hi @walkerwg
To better address the issue, can you please provide a complete reproducible minimal code sample using just webview_flutter. Feel free to create to create repository for code sample and comment below
Thank you

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/flutter/flutter/issues/61212#issuecomment-659911927",
"url": "https://github.com/flutter/flutter/issues/61212#issuecomment-659911927",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TahaTesser** [comment] 2020-07-20 07:26
Hi @walkerwg 
It might have been a native and i am also running iOS 13.6 so i'm unable to reproduce the issue with issue `webview_flutter`

given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-20 07:26 UTC
Labels: in triage
