### ISSUE TITLE
App Name doesn't support image insertion here.

### ISSUE THREAD

**Issue by gerry05** [flutter/flutter#37035] opened 2019-07-26 21:16 UTC
I try to select a GIF via keyboard and it says **App Name doesn't support image insertion here.**

**Comment by BondarenkoStas** [comment] 2019-09-21 14:54
@gerry05 Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Also provide your `flutter doctor -v` output.
Will just leave a [link](https://stackoverflow.com/questions/57257535/flutter-app-name-doesnt-support-image-insertion-here) here in case any solution will appear on SO.

**Comment by iapicca** [comment] 2019-11-11 16:09
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-11 16:09 UTC
Labels: waiting for customer response

**Comment by AxesandGrinds** [comment] 2020-04-15 23:34
You close this issue when you know that it's an issue that has existed since 2017. How can someone create a modern chat app without gifs and stickers. This is freaking crazy.

**Comment by iapicca** [comment] 2020-04-17 11:46
Hi @AxesandGrinds 
for the issue to be workable needs to contain the some information
such as `flutter doctor -v` , 
`flutter run --verbose` 
and a reproducible minimal code sample.

If you are experiencing a problem with flutter
please open an issue providing the information listed above
Thank you
