### ISSUE TITLE
[WEB] How to get the hot-reload status/signals (for refreshing the page) from web-server devices

### ISSUE THREAD

**Issue by tianna1121** [flutter/flutter#44974] opened 2019-11-15 08:16 UTC
## Use case

Get the hot-reload status from web-server device. The page in the chrome device can be refreshed automatically when user sent 'r' or 'R' command. However, we cannot get the similar signal from web-server device.

Flutter web servers are mostly build on web-server device. We want to provide auto-refresh feature when the flutter apps changed.

## Proposal

Provide some sort of signals when hot-reload finishes (for web-server devices).

**Comment by tianna1121** [comment] 2019-11-16 14:02
I have noticed that only ChromeDevice can get Page.reload command via wipConnection api call. How can I use wipConnection.sendCommand('Page.reload') to WebServerDevice?

**Comment by yjbanov** [comment] 2019-12-05 23:31
@jonahwilliams how easily can this be supported?

**Comment by jonahwilliams** [comment] 2019-12-05 23:35
Someone already filled an issue for this, maybe it got closed? Its a trivial change to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L1094 to conditionally register hot reload and hot restart hooks based on device supporting hotreload/restart instead of service protocol

**Comment by jonahwilliams** [comment] 2020-01-09 06:58
Duplicate of https://github.com/flutter/flutter/issues/44795

**Closed by jonahwilliams** 2020-01-09 06:58 UTC
Labels: proposal, severe: new feature, t: hot reload, tool, ☸ platform-web
