### ISSUE TITLE
image.toByteData does not work for web

### ISSUE THREAD

**Issue by egodefroy** [flutter/flutter#45467] opened 2019-11-23 16:27 UTC
## Steps to Reproduce

1. launch the attached flutter application for iOS in XCode
2. flutter build web
3. launch the web application
4. this statement is reached in iOS: print('getImage after toByteData');
5. this statement is NOT reached in web: print('getImage after toByteData');

flutter doctor

```
[✓] Flutter (Channel unknown, v1.12.1, on Mac OS X 10.15.1 19B88, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (4 available)

• No issues found!
```

## Logs

no error

### Source

```
import 'dart:typed_data';
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() async {

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Image',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final imageKey = GlobalKey();

  Future<ByteData> getImage(String path) async {
    Completer<ImageInfo> completer = Completer();
    var img = new NetworkImage(path);
    img
        .resolve(ImageConfiguration())
        .addListener(ImageStreamListener((ImageInfo info, bool _) {
      completer.complete(info);
    }));
    ImageInfo imageInfo = await completer.future;
    print('getImage before toByteData');
    var result =
        await imageInfo.image.toByteData(format: ui.ImageByteFormat.png);
    print('getImage after toByteData');
    return result;
  }

  @override
  Widget build(BuildContext context) {
    var data = getImage('https://picsum.photos/250?image=9');

    return Scaffold(
        appBar: AppBar(title: Text('Custom Fonts')),
        body: Center(
          child: Image.network('https://picsum.photos/250?image=9'),
        ));
  }
}
```

**Comment by jonahwilliams** [comment] 2019-11-23 19:19
duplicate of https://github.com/flutter/flutter/issues/44908

**Closed by jonahwilliams** 2019-11-23 19:19 UTC

**Comment by eebeeDEV** [comment] 2020-04-04 10:47
Hi egodefroy, I have the same issue. Did you find a solution?
Best,
Eric
