### ISSUE TITLE
Flutter firebase_ml_vision detects wrong text on IOS but the correct ones on Android

### ISSUE THREAD

**Issue by nellybaz** [flutter/flutter#45776] opened 2019-11-28 12:35 UTC
## Steps to Reproduce

1. Install firebase_ml_vision
2. Add pod 'Firebase/MLVisionTextModel'  to your PodFile on IOS
3. Follow the exact instructions on https://pub.dev/packages/firebase_mlkit_language to integrate firebase_ml_vision. Run the code on an iPhone not simulator.

**Target Platform:** IOS

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment] 2019-11-28 14:27
Hi @nellybaz 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-28 14:27 UTC
