### ISSUE TITLE
Flutter web can not run in flutter 3.24

### ISSUE THREAD

**Issue by Trung15010802** [flutter/flutter#153209] opened 2024-08-10 02:33 UTC
I have a similar issue. But it doesn't show any error. It stuck at loading screen.
![image](https://github.com/user-attachments/assets/973f589c-6364-4e31-8611-767ba1128254)

It has an error on console log

![image](https://github.com/user-attachments/assets/3df4baa2-fad1-4a2e-a105-fe407b3e6e24)

**Comment by jocubeit** [comment] 2024-08-10 04:21
Interestingly if you hit refresh in the browser, the app will load and work. It continues to work after a Shift-R hot reload in the terminal. It just doesn't run first time.

**Comment by Trung15010802** [comment] 2024-08-10 05:02
> Interestingly if you hit refresh in the browser, the app will load and work. It continues to work after a Shift-R hot reload in the terminal. It just doesn't run first time.
> 
> Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git Framework • revision [80c2e84](https://github.com/flutter/flutter/commit/80c2e84975bbd28ecf5f8d4bd4ca5a2490bfc819) (11 days ago) • 2024-07-30 23:06:49 +0700 Engine • revision b8800d88be Tools • Dart 3.5.0 • DevTools 2.37.2
> 
> Flutter doctor reports no issues found.

This way doesn't work for me

**Comment by mqhamdam** [comment] 2024-08-10 06:30
Did u get flutter_log file? I had similar issue, it generates flutter log file and ask to report a bug.

**Comment by jocubeit** [comment] 2024-08-10 06:48
> Did u get flutter_log file? I had similar issue, it generates flutter log file and ask to report a bug.

You console log, yes I got the same as you.

**Comment by mqhamdam** [comment] 2024-08-10 06:52
> You console log, yes I got the same as you.

i did open an issue #153137  but they close and marked it as duplicate of #153064

**Comment by Juliotati** [comment] 2024-08-10 15:18
@Trung15010802 
For it to run like before, at least for now you have to specify the renderer `--web-renderer html` or `--web-renderer auto`. Using `canvaskit` (now the default) will cause the app to get stuck (why? I don’t know).

Possibly connected to this too https://github.com/flutter/flutter/issues/152995

**Comment by spydon** [comment] 2024-08-10 18:55
Should be fixed by https://github.com/flutter/flutter/issues/152953
I tried with main and the issue is indeed solved there!

**Comment by darshankawar** [comment] 2024-08-12 07:40
Verified on latest master that it compiles and builds the web app properly. The issue seems to be only occuring in stable 3.24.0.
Please follow-up in the cp issue https://github.com/flutter/flutter/issues/152953 for further updates.
Closing this as fixed.

**Closed by darshankawar** 2024-08-12 07:40 UTC
Labels: in triage
