### ISSUE TITLE
PopupMenuButton icon splash radius is too large

### ISSUE THREAD

**Issue by MuhammadUmair786** [flutter/flutter#96206] opened 2022-01-06 05:28 UTC
## Use case
No way to modify the splash radius for PopupMenuButton and it is vey large by default. 

## Proposal
add splash radius property

**Comment by maheshmnj** [comment] 2022-01-06 09:17
Hi @MuhammadUmair786, Thanks for filing the issue. This looks like a valid proposal to me.

```dart
PopupMenuButton(
    splashRadius: 24, ///expose SplashRadius property
    color: !toggle ? Colors.red : Colors.green,
    key: _menuKey,
    itemBuilder: (_) => <PopupMenuItem<String>>[
        const PopupMenuItem<String>(
        child: Text('Doge'), value: 'Doge'),
        const PopupMenuItem<String>(
         child: Text('Lion'), value: 'Lion'),
         ToggleMenuItem<String>(
            child: Text('ChangeColor'),
            onTap: () => setState(() => toggle = !toggle))
        ],
        onSelected: (String x) {
        setState(() {
        selected = x;
     });
  }),
```

**Comment by dheerajv09** [comment] 2022-01-13 19:05
Hi, @maheshmnj , don't you think splashradius should also be passed as parameter to inkwell?? As  passing gild will not be having property to change splash radius.

**Comment by maheshmnj** [comment] 2022-01-14 04:24
@dheerajv09, Yes you are right, I have pushed the update. If you have any further thoughts please feel free to add it in the PR comments.

**Comment by maheshmnj** [comment] 2022-01-27 05:35
Closing as duplicate of https://github.com/flutter/flutter/issues/90898 (fixed)

**Closed by maheshmnj** 2022-01-27 05:35 UTC
Labels: severe: new feature, framework, f: material design, proposal, passed first triage
