### ISSUE TITLE
Flutter fails unexpectedly while creating template Flutter project

### ISSUE THREAD

**Issue by alvarofps** [flutter/flutter#69262] opened 2020-10-29 01:32 UTC
I get the following error, this occurs when I try to create a Flutter project in Android Studio

FileSystemException: FileSystemException: Exists failed, path = '/root/.pub-cache/hosted/pub.dartlang.org/flutter_template_images-1.0.1/lib/' (OS Error: Permission denied, errno = 13)
[flutter_01.log](https://github.com/flutter/flutter/files/5455620/flutter_01.log)

**Comment by sohilmemon** [comment] 2020-10-29 02:08
@alvarofps I think there might be issues with the permissions. Can you specify where you have copied or install actual flutter SDK directory?

**Comment by iapicca** [comment] 2020-10-29 08:13
possibly a duplicate of https://github.com/flutter/flutter/issues/50880
should be fixed on master https://github.com/flutter/flutter/pull/63540

**Comment by pedromassangocode** [comment] 2020-10-29 08:54
Hi @alvarofps 
Can you try Flutter master channel to see if the issue reproduces?
Thank you

**Comment by natnaelab** [comment] 2020-11-23 03:06
I'm facing the same issue

![Screenshot_20201123_060044](https://user-images.githubusercontent.com/45040910/99926189-e3a87100-2d51-11eb-95e5-9cf1357d7d95.png)

**Closed** 2020-11-23 03:56 UTC
Labels: in triage, waiting for customer response
