### ISSUE TITLE
Flutter 64 bit support

### ISSUE THREAD

**Issue by DrBeta** [flutter/flutter#30943] opened 2019-04-12 03:15 UTC
I am using MacOS 10.4.4 and when I ran `flutter create` my terminal popped up with this:
<img width="532" alt="Screen Shot 2019-04-11 at 6 51 48 PM" src="https://user-images.githubusercontent.com/45474221/56009915-2a457680-5ca7-11e9-91e6-82c31be0070a.png">

So I am contacting the developer for more information. Can anyone handle this?

**Comment by jonahwilliams** [comment] 2019-04-22 04:56
I believe this is related to gen_snapshot requiring XCode 9 on macOS from https://github.com/flutter/engine/pull/8643

**Comment by cbracken** [comment] 2019-05-29 17:51
The upstream issue is https://github.com/dart-lang/sdk/issues/36839, which evolved out of https://github.com/dart-lang/sdk/issues/31709.

**Comment by cbracken** [comment] 2019-05-29 17:52
Closing this as a dupe of #22598, which is the engine-side manifestation of this.

**Closed by cbracken** 2019-05-29 17:52 UTC
Labels: dependency: dart, engine
