### ISSUE TITLE
Issue in interactive viewer zooming,when zoom a image in a container some portions of image didn't accessible.

### ISSUE THREAD

**Issue by allwinvinosh** [flutter/flutter#65852] opened 2020-09-15 13:53 UTC
**I have wrapped the interactive viewer by container.I zoom one particular position in a view port.I dint zoom and scroll the image**

```
`class MyApp extends StatelessWidget {
static const String _title = 'Flutter Code Sample';

@override
Widget build(BuildContext context) {
return MaterialApp(
title: _title,
home: Scaffold(
appBar: AppBar(title: const Text(_title)),
body: Zoom(),
),
);
}
}
class Zoom extends StatefulWidget
{
@override
MyStatelessWidget createState()=> MyStatelessWidget();
}
/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends State {

@override
Widget build(BuildContext context) {
return Center(
child:Container(height: 300,
child: InteractiveViewer(
scaleEnabled: true,maxScale: 4.0,
child: Center(
child:Container( child:Image.asset('Assets/Java-001.jpg',fit: BoxFit.cover,alignment: Alignment.center,)),
 @),
)));
}
}`
```
**How can i solve this issue**

**Comment by Calamity210** [comment] 2020-09-15 23:40
@allwinvinosh It seems to be working as intended. The issue may be with your Image.asset, can you send your logs?

**Comment by Calamity210** [comment] 2020-09-15 23:41
```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: Zoom(),
      ),
    );
  }
}

class Zoom extends StatefulWidget {
  @override
  MyStatelessWidget createState() => MyStatelessWidget();
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends State<Zoom> {
  @override
  Widget build(BuildContext context) {
    return Center(
        child: Container(
            height: 300,
            color: Colors.greenAccent,
            child: InteractiveViewer(
              scaleEnabled: true,
              maxScale: 4.0,
              child: Center(
                child: Container(
                  color: Colors.red,
                ),
              ),
            )));
  }
}
```
Your code without the image, I can't reproduce.

**Comment by darshankawar** [comment] 2020-09-16 07:15
@allwinvinosh 
Can you elaborate more when you say the portion of image isn't accessible ? Can you provide video / gif of the issue ?
Thanks.

**Comment by allwinvinosh** [comment] 2020-09-16 12:15
after zoom a image top side image was not accessable,when image excced the container height(300 as mentioned in code)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/34914140/93335596-56720900-f844-11ea-8efa-ec1ea701f00f.png)

**Comment by darshankawar** [comment] 2020-09-16 13:08
Hi @allwinvinosh,
I tried to replicate the issue on latest stable (1.20.4) but was able to interact / rotate the image outside of the container height. Not sure if this is what the issue or am I missing anything.

[65852.mp4.zip](https://github.com/flutter/flutter/files/5232359/65852.mp4.zip)

**Comment by TahaTesser** [comment] 2020-10-14 15:13
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 15:13 UTC
Labels: in triage
