### ISSUE TITLE
iOS 18 TextField: whitespaces added when moving cursor

### ISSUE THREAD

**Issue by felixkrautschuk** [flutter/flutter#153098] opened 2024-08-08 15:24 UTC
### Steps to reproduce

1. Open a Flutter app with a TextField on iOS 18
2. Type something into the TextField
3. Move the cursor

### Expected results

Only the cursor position should be changed without any other side effects

### Actual results

When moving the cursor, some whitespaces are added to the TextField.

### Code sample

<details open><summary>Code sample</summary>

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Test"),
      ),
      body: const Center(
        child: Padding(
          padding: EdgeInsets.all(20),
          child: TextField(),
        )
      ),
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/7dce10c9-adf8-4f9e-873e-ecc886073344

</details>

### Logs

<details open><summary>Logs</summary>

```console
-- no logs --
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2024-08-09 08:16
Thank you for the report. I don't have such a version to test right now. But when I checked this on iOS 17.5, I didn't see the issue as described. I will mark this as an iOS version-specific issue for other input. 

In the mean time, can you please provide the output of `flutter doctor -v` that will contain the exact XCode/iOS build number  so that may be helpful for others to look into this later?

**Comment by justinmc** [comment] 2024-08-12 21:13
I'm not able to reproduce this on the iOS 18.0 simulator. Anything I could be missing?


https://github.com/user-attachments/assets/0362b4d6-ed76-4071-9fff-0dab8d773be6

**Comment by justinmc** [comment] 2024-08-12 22:09
@Renzo-Olivares also could not reproduce this on his physical device running iOS 18.1 beta 2.

I see @f-person also added a thumbs up, can you reproduce this, and if so how?

We noticed that the device language is German in the video, but changing to German didn't help reproduce it.

**Comment by f-person** [comment] 2024-08-14 08:50
Hey @justinmc! I didn't have this particular issue, but the iOS 18 beta led to some weird behaviors of the keyboard in our Flutter app (mainly, in non-standard text editing flows (e.g., several inputs sharing a single text controller)). The upvote was for drawing more attention to general input issues in iOS 18. 
One environment difference I noticed between your recording & the originally reported one is the latter using an iPhone 15 _Pro_ simulator, which wouldn't be expected to make a difference, but you never know for sure with these things ¯\\_(ツ)_/¯.

**Comment by jmagman** [comment] 2024-08-14 17:10
> iOS 18 beta led to some weird behaviors of the keyboard in our Flutter app (mainly, in non-standard text editing flows (e.g., several inputs sharing a single text controller)).

@f-person can you file new issues describing that, with reproduction steps?  I'm not aware of an existing open issue, so we're not investigating it.

**Comment by justinmc** [comment] 2024-08-15 17:46
I just tried on an iPhone 15 Pro simulator and got the same result, was not able to reproduce. Good idea to check though, @f-person .

**Comment by hellohuanlin** [comment] 2024-08-19 18:30
@felixkrautschuk which beta are you using? 
I just tried beta 5 and wasn't able to repro on simulator.

**Comment by jmagman** [comment] 2024-08-20 23:36
I wasn't able to reproduce on iOS 18 beta 5 on a physical device on Flutter 3.24 stable:

https://github.com/user-attachments/assets/282fb78b-c273-499c-9232-f652f2481bf6

I tried again in German in case that was somehow related, but it still didn't reproduce.

@felixkrautschuk can you confirm you are no longer seeing this on recent betas?

**Comment by felixkrautschuk** [comment] 2024-08-21 08:38
@jmagman @justinmc sorry for the late reply.

I am still seeing the issue on my side with beta 5. I always try to report issues as early as possible, but as I seem to be the only one with this problem, it's maybe no general issue with Flutter and iOS 18.
I will try beta 6 later this week report back.

**Comment by jmagman** [comment] 2024-08-21 17:33
> I am still seeing the issue on my side with beta 5. I always try to report issues as early as possible, but as I seem to be the only one with this problem, it's maybe no general issue with Flutter and iOS 18. I will try beta 6 later this week report back.

@felixkrautschuk Thanks for filing issues early!  
1. Can we get the output of `flutter doctor -v`, I don't think we have that from you.  
2. Are you sure there are no other extra steps you're taking to reproduce?  
3. Do you see the same result on a physical device?

**Comment by felixkrautschuk** [comment] 2024-08-22 10:42
@jmagman 

1. the output of flutter doctor -v on my machine is:

> [✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-x64, locale de-DE)
>     • Flutter version 3.24.0 on channel stable at /Users/felixkrautschuk/development/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
>     • Engine revision b8800d88be
>     • Dart version 3.5.0
>     • DevTools version 2.37.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at /Users/felixkrautschuk/Library/Android/sdk
>     • Platform android-35, build-tools 34.0.0
>     • ANDROID_HOME = /Users/felixkrautschuk/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 16.0)
>     • Xcode at /Applications/Xcode-beta.app/Contents/Developer
>     • Build 16A5230g
>     • CocoaPods version 1.15.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2024.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
> 
> [✓] Connected device (4 available)            
>     • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 14 (API 34) (emulator)
>     • iPhone 15 Pro (mobile)       • C99AA5C3-8661-4E5E-93E3-AF03C5F8C869 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
>     • macOS (desktop)              • macos                                • darwin-x64     • macOS 14.6.1 23G93 darwin-x64
>     • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 127.0.6533.120
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> • No issues found!


2. No additional steps needed, I just type something into the TextField and move the cursor

3. On our physical devices we only have installed iOS 17. For iOS 18 we only tested on Simulator so far

**Comment by huycozy** [comment] 2024-08-22 10:50
@felixkrautschuk Out of curiosity, I wonder if this issue occurs on iOS native app. Could you please check this on Simulator's default apps? 

One more test that would be helpful, can you please try on an iOS native project with a simple TextField?

**Comment by felixkrautschuk** [comment] 2024-08-22 16:22
@huycozy Indeed, when using a TextField in a native iOS app, the same strange effect occurs in the iOS 18 Simulator.

**Comment by jmagman** [comment] 2024-08-22 19:09
Good call checking on that @huycozy!
@felixkrautschuk given that it's reproducing in a native app and only on the simulator, there's nothing Flutter could do about this. I'm going to close this.

Thank you for testing Flutter on iOS betas, we want to make sure it's in good shape before iOS ships!

**Closed by jmagman** 2024-08-22 19:09 UTC
Labels: a: text input, platform-ios, e: OS-version specific, P2, fyi-ios, team-text-input, triaged-text-input
