### ISSUE TITLE
Differences between path_provider ^0.4.1 and ^1.5.1

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#47731] opened 2019-12-24 09:24 UTC
The **_getExternalStorageDirectory()_** function works differently in versions **^0.4.1** and **^1.5.1**. In the case of ^0.4.1, function really returns path to external memory, in the case of version ^1.5.1 path to the local application memory. In other words, accessing external memory in version ^1.5.1 isn't directly possible. Is this done on purpose, or is it a bug (or maybe this is a feature)? Below is the code and trace.

Code:
```
  Future<String> get _localPath async
  {
    final directory = await getExternalStorageDirectory();

    print ('rootExternal-> ${directory.path}');

    final appFolder = await getApplicationDocumentsDirectory();

    print ('appFolder-> ${appFolder.path}');

    Directory
      target = new Directory(directory.path + applicationPath);
    bool folderExist = false;
    if (target.existsSync())
    {
      print('${target.path} -- exists');
      _workPath = target.path;
      folderExist = true;
    }
    else
    {
      print('${target.path} -- is absent');
      try
      {
        target.createSync(recursive: true);
        print('${target.path} -- was created');
        folderExist = true;
      }
      catch(exception)
      {
        print('${target.path} -- failed to create -- ${exception.toString()}');
      }
    }
    return folderExist ? target.path : directory.path;
  }

```
Trace:

^0.4.1:
```
I/flutter (10277): rootExternal-> /storage/emulated/0
I/flutter (10277): appFolder-> /data/user/0/com.mk.hsm_e_editor/app_flutter
```
^1.5.1
```
I/flutter (10480): rootExternal-> /storage/emulated/0/Android/data/com.mk.hsm_e_editor/files
I/flutter (10480): appFolder-> /data/user/0/com.mk.hsm_e_editor/app_flutter
```
Flutter doctor:

```
/home/michael_k/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.6 at /home/michael_k/flutter
    • Framework revision 18cd7a3601 (13 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/michael_k/Tekoia/Dev-Tools/Android-Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/michael_k/Tekoia/Dev-Tools/Android-Sdk
    • Java binary at: /home/michael_k/Tekoia/Dev-Tools/Android-Studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.5)
    • Android Studio at /home/michael_k/Tekoia/Dev-Tools/Android-Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/michael_k/idea-IC-191.6707.61
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Mi A2 • 11354e2 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
PS. The same situation in the stable version.

**Comment by VladyslavBondarenko** [comment] 2020-03-20 12:00
Duplicate of https://github.com/flutter/flutter/issues/48208

**Closed by VladyslavBondarenko** 2020-03-20 12:00 UTC
Labels: p: first party, p: path_provider, plugin, severe: regression
