### ISSUE TITLE
Extension methods have the different hashCode for the same instance

### ISSUE THREAD

**Issue by MHShetty** [flutter/flutter#58855] opened 2020-06-06 09:34 UTC
```
class SomeType{}

extension Something on SomeType
{
void someFunction(){}
}

void main()
{
SomeType st = SomeType();
print(st.someFunction.hashCode); // Some value
print(st.someFunction.hashCode); // Some other value
}
```

Is there some way to ensure that the hashCode in both the cases remain same or can this be considered as a feature request?

**Comment by TahaTesser** [comment] 2020-06-08 09:22
It's like you have already filed the issue and got the answer https://github.com/dart-lang/sdk/issues/42208

As stated by [comment](https://github.com/dart-lang/sdk/issues/42208), This is working as intended

This is a Dart SDK thing, not Flutter

given your mentioned issue is resolved, I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-06-08 09:22 UTC
