### ISSUE TITLE
BackdropFilter breaks if put behind non-opaque widget

### ISSUE THREAD

**Issue by denis-evteev** [flutter/flutter#60966] opened 2020-07-07 08:34 UTC
The `BackdropFilter` widget behaves quite weirdly if it’s placed behind a non-opaque widget, such as `Opacity`. In some cases it hides the parent’s content, while in others it seems to render the content twice — with the filter effect and without it.

Here’s a sample code to reproduce the latter behaviour:
```
import 'dart:ui';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: (_, __) => Scaffold(
        body: Opacity(
          opacity: 1.0,
          child: Stack(
            children: <Widget>[
              Center(child: Text('Test', textScaleFactor: 4.0)),
              BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
                child: Container(color: Colors.black.withOpacity(0.0)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
With the `opacity` value being `1.0` everything seems to be just fine — the text is blurred.
<img width="135" alt="Screenshot 2020-07-07 at 11 27 30" src="https://user-images.githubusercontent.com/3929460/86748049-dad62d80-c044-11ea-89e3-ce58fe73fde2.png">

But changing the value to `0.9` leads to this:
<img width="135" alt="Screenshot 2020-07-07 at 11 28 22" src="https://user-images.githubusercontent.com/3929460/86748215-f8a39280-c044-11ea-8a94-ba6bbdaa270b.png">

This is not the result I expected to see.

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/denis/Projects/vendor/flutter
    • Framework revision 8af6b2f038 (7 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/denis/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 6FCA75B1-A34C-45EC-BF25-BA36CC5DA55D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-07-07 09:31
I can reproduce issue iOS and Android

<details> 
<summary>Code Sample</summary> 

``` 
import 'dart:ui';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: (_, __) => Scaffold(
        body: Opacity(
          opacity: 0.9,
          child: Stack(
            children: <Widget>[
              Center(child: Text('Test', textScaleFactor: 4.0)),
              BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
                child: Container(color: Colors.black.withOpacity(0.0)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (3 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (7 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • SM M305F      • 32003c30dc19668f                     • android-arm64 •
      Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E            • ios           • iOS
      13.5.1
    • iPhone 8      • 58538784-25E4-405B-B1FF-A0F4D150CA3D • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
``` 

</details>

**Comment by gaaclarke** [comment] 2020-07-08 20:55
cc @flar

**Comment by flar** [comment] 2020-07-09 20:54
Note that you can achieve the effect that you want by inserting an opaque backdrop behind the text, as in:
```
             children: <Widget>[
+              Center(child: Container(color: Colors.white, width: 400, height: 400)),
               Center(child: Text('Test', textScaleFactor: 4.0)),
               BackdropFilter(
                 filter: ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
                 child: Container(color: Colors.black.withOpacity(0.0)),
               ),
             ],
```
(adjust the size accordingly)

The next comment will describe why this happens and further work we can do to make this less surprising to developers.

**Comment by flar** [comment] 2020-07-09 21:10
This behavior has been there since BackdropFilter was created and is largely "working as would make sense" if someone understands how all of these mechanisms work, but has clearly caused confusion in the past and continues to do so, so we need to address it.

@liyuqian also noted this behavior in an earlier issue: https://github.com/flutter/flutter/issues/31706#issuecomment-522697161

That comment describes the issue in some depth, but basically if you don't have the Opacity (and when its value is 1.0 then it steps out of the way when building a rendering frame, so effectively you don't have it in that case), then the text would be rendered on the white background of the screen and then the BackdropFilter would blur the text's black pixels with the white screen background and paint that result back onto the background. The original text would be obscured by the many pixels that are combinations of opaque black and opaque white from the blur operation and none of the original text would show through.

When the Opacity widget is there and has a non-opaque value, then the text and the BackdropFilter is rendering to an offscreen Skia layer and it will see black Text on a transparent background. The blur will then blur those opaque black pixels with transparent pixels and get a semi-transparent fuzzy black blob. It then renders that semi-transparent blob back onto the background and it fails to obscure the original text.

The difference is that opaque pixels blurred with other opaque pixels produce a result that is also opaque. But burring opaque pixels with transparent pixels produces a semi-transparent result. This is the nature of the blur operation.

The transparency is introduced implicitly by the Opacity widget with a non-opaque value and is a necessary part of how that widget achieves its own effect.

Putting those two behaviors together, unfortunately, produces surprising results for developers.

We need to document this so that other developers don't keep running into the problem.

**Comment by flar** [comment] 2020-07-09 21:24
It looks like the example is attempting to blur a single widget, which is an operation that can be achieved much more efficiently using the `ImageFiltered` widget, as in:
```
        Opacity(
          opacity: 1.0,
          child: ImageFiltered(
            filter: ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
            child: Center(child: Text('Test', textScaleFactor: 4.0)),
          ),
        ),
```
This variation would not run into the issue seen with BackdropFilter that behaves differently when running under another widget that uses saveLayer. It should also be a bit faster.

**Comment by denis-evteev** [comment] 2020-07-10 08:52
Thanks for describing how the filter works and why it produces this unexpected result.

Unfortunately, though, the actual issue that I experience is a bit more complex than the one I used in the example, so your suggestion to use the `ImageFiltered` widget won’t resolve it.

The thing is that I have a `Stack` of widgets with the top-most widget in it being a `Text` widget. I want this text to appear on a semi-transparent background with a blur effect. So the actual widget tree that I have is this:
```
Container(
  padding: somePadding.copyWith(left: 10.0, top: 15.0),
  child: ClipRRect(
    borderRadius: BorderRadius.circular(5.0),
    child: BackdropFilter(
      filter: ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
      child: Container(
        padding: EdgeInsets.all(5.0),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(5.0),
          color: someColor.withOpacity(0.25),
        ),
        child: Text(
          title,
          textScaleFactor: 1.2,
          style: TextStyle(fontWeight: FontWeight.w700),
        ),
      ),
    ),
  ),
);
```

Now, the visibility of this top-most widget tree in the stack can be toggled on and off. But I don’t want that toggle effect to be instantaneous and therefore I wrap this widget tree in a `FadeTransition` widget that gradually changes opacity.

What I expect to see is the text gradually disappearing from the view or reappearing back into it. What I see in reality is that the text with its background disappears as soon as the opacity’s value becomes less than `1.0` and reappears only when it becomes exactly `1.0`.

Is there any way I can achieve the desired effect given that the `ImageFiltered` solution won’t work here and the `BackdropFilter` widget doesn’t do what I expect it to do?

**Comment by denis-evteev** [comment] 2020-07-10 09:40
Here’s another simplified example of my issue, but this time with the widget structure being much closer to the actual one I have in my app: https://dartpad.dev/518946f45d73080457202538e30dc858

Not entirely sure why in this example it’s only the blurred background that is not being animated (in my app the text on the background is also not animated), but at least it’s quite clear that the blurred effect is present only when the background layer is fully opaque.

**Comment by flar** [comment] 2020-07-10 19:15
I'm sorry, I edited your comment thinking it was mine. I'll try to restore it...

**Comment by flar** [comment] 2020-07-10 19:34
Inside an `Opacity` widget no child has any access to the content of the scene behind the `Opacity` widget. `BackdropFilter` cannot blur what it has no access to. You'd have to move the `BackdropFilter` outside of the fade transition in order for it to blur the text behind it.

With the `FadeTransition` the "scene" is an empty transparent box which cannot be blurred and a crisp piece of text on top of it. Nothing else is accessible. When the transition reaches its final value of 1.0, then the `Opacity` steps out of the way and suddenly the entire tree behind it is visible to the `BackdropFilter` and it can blur the text that was underneath the `FadeTransition`.

I don't think we can solve the issue of having the `BackdropFilter` filter pixels that are behind an intervening layer, but the sudden change in behavior when the fade reaches 1.0 could probably be eliminated by removing the optimization where the `Opacity` widget steps out of the way when it is fully opaque. In essence, that would give consistent behavior, but the behavior preserved would not be the one that achieves the effect you are going for.

If you want to achieve this effect, you would have to place the `BackdropFilter` outside of the fade transition and have it coordinate with the fading. Or insert an `ImageFiltered` and `Opacity` layer around the background coordinated with the fade on the foreground text.

**Comment by denis-evteev** [comment] 2020-07-10 21:10
Thanks again!

I followed your advice and was able to achieve the desired effect by placing the text wrapped in the `FadeTransition` widget on a separate layer in the stack and wrapping the `BackdropFilter` into an `AnimatedBuilder` to control the amount of blur and coordinate it with text fading.

Here’s an updated sample code in case anyone’s interested: https://dartpad.dev/b1158b255f12e6a5a5d9aa7df31795a1

**Comment by flar** [comment] 2020-09-30 19:25
Closing as the direction forward for BackdropFilters and opacity layers is being taken in a different direction as being tracked in https://github.com/flutter/flutter/issues/58425.

**Closed by flar** 2020-09-30 19:25 UTC
Labels: engine, found in release: 1.17, found in release: 1.20, framework, has reproducible steps

**Comment by flar** [comment] 2021-04-27 19:34
With the landing of https://github.com/flutter/engine/pull/19631 and https://github.com/flutter/flutter/pull/80129 developers can now specify a BlendMode.src operation in their BackdropFilter if it is nested inside an Opacity (or other widget that uses a save layer).

**Comment by flar** [comment] 2022-07-01 22:12
> I read through all the comments and tried "blendMode.src" but I don't think it works for my usecase. I'm attempting to implement #17617, and the current backing implementation of "magnifying" a part of the screen is using a BackdropFilter.matrix with a transform + scale.
> 
> All was going well up until I ran into this issue - the loupe needs an opacity to fade in. I've got an MVP boiled down to this: https://dartpad.dev/?id=f6dde469bc2d13f779988da3f610210b where if the opacity == 1, then the red square is shown (since it's a product of the translation) but if the opacity !== 1, then the red square is not shown.
> 
> If I'm reading this correctly, [Blendmode.src] should allow me to do what I want here, but it doesn't seem to be the fix here.

You are seeing another problem which is that BackdropFilter cannot "x-ray" through the layer created by the opacity widget to be able to filter and use the pixels of the primary scene layer. OpacityLayer kind of lifts your BackdropFilter out of the scene and has it working on its own little offscreen arena which is empty before blitting it back into the scene.

This was discussed a bit in this long-standing issue originally affecting iOS dialogs: https://github.com/flutter/flutter/issues/31706
