### ISSUE TITLE
[windows] lost connection to device

### ISSUE THREAD

**Issue by Ahmed-elshorbagy** [flutter/flutter#113474] opened 2022-10-15 01:01 UTC
my app for windows desktop is working correctly with no crash but when i tried to navigate to a third page and make any changes then the the debugger send this message "lost connection to device\n exit" but the app don't crash i tried changing the third page even to a container but it keeps doing the same

## Logs

<details>
<summary>Logs</summary>

```
```

```
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.3.4 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (10 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\zoro_\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\zoro_\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by Ahmed-elshorbagy** [comment] 2022-10-15 01:34
when i tried to switch the second and third page the problem disappeared the problem occurs after navigation from specific page2

**Comment by Ahmed-elshorbagy** [comment] 2022-10-15 02:07
i tried even to pop the second page before pushing the third but the same result

**Comment by Ahmed-elshorbagy** [comment] 2022-10-15 19:41
it really took my entire day to finally solve it or kind of making a work around
the problem is with vscode 
after switching to android studio 
flutter kept working with losing connecion to device

**Comment by huycozy** [comment] 2022-10-17 06:20
Hi @Ahmed-elshorbagy 

>it really took my entire day to finally solve it or kind of making a work around
the problem is with vscode

What's the workaround you implemented for this?

 >after switching to android studio
flutter kept working with losing connecion to device

As I see from your `flutter doctor -v` output, `Android toolchain` is still having issues there. So please try to solve them and retry running the app.

**Comment by Ahmed-elshorbagy** [comment] 2022-10-17 18:34
@huycozy 
i updated my comment the problem is with vscode
while working with android studio no problem occurs 
i fixed all the issues in flutter doctor and the proble still presist while using vscode

**Comment by huycozy** [comment] 2022-10-18 03:43
@Ahmed-elshorbagy 
What's VSCode version are you using? 

Does the issue happen with the Flutter default project (couter app)? If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by Ahmed-elshorbagy** [comment] 2022-10-19 03:54
@huycozy 
vscode version: 1.72.2
I was able to reproduce the problem in a new project and track it to a single line in `1stpage.dart` file
the line is 
`(await PlatformDeviceId.getDeviceId)`
it is from another library it works fine in android studio but not in vscode
these are the project files
[lib.zip](https://github.com/flutter/flutter/files/9816670/lib.zip)

**Comment by huycozy** [comment] 2022-10-19 04:53
Hi @Ahmed-elshorbagy 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. 
Looks like someone had a similar problem at https://github.com/BestBurning/platform_device_id/issues/21 and let's take a look at https://github.com/BestBurning/platform_device_id/issues/21#issuecomment-1133934641 as an alternative solution. 
If it's not the same as your case, try to open an issue in the [platform_device_id repository](https://github.com/BestBurning/platform_device_id) to have better support there.

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2022-10-19 04:53 UTC
Labels: in triage
