### ISSUE TITLE
App-crash when running CameraController.initialize();

### ISSUE THREAD

**Issue by SankaCoffee** [flutter/flutter#22427] opened 2018-09-28 14:23 UTC
## Steps to Reproduce

App crashes when trying to initialize camera with cameraController.initialize(); and gives error about 'Can request only one set of permissions at a time'

Yesterday the same code was working, i thought i was using Flutter version 9.4-pre32 then...

## Logs

```
[ +383 ms] D/        ( 1322): HostConnection::get() New Host Connection established 0xe6c924c0, tid 1344
[  +20 ms] D/EGL_emulation( 1322): eglMakeCurrent: 0xe8a61d00: ver 3 0 (tinfo 0xe6c83300)
[+1276 ms] Updating files
[ +571 ms] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86... (completed)
[        ] Synced 10.1MB.
[   +2 ms] _flutter.listViews: {isolateId: isolates/978519165}
[   +9 ms] Connected to _flutterView/0xeca3808c.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +3 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:64565/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+5516 ms] I/CameraManagerGlobal( 1322): Connecting to camera service
[+1027 ms] W/Activity( 1322): Can request only one set of permissions at a time
[   +4 ms] E/flutter ( 1322): [ERROR:flutter/shell/common/shell.cc(182)] Dart Error: Unhandled exception:
[        ] E/flutter ( 1322): CameraException(cameraPermission, Camera permission request ongoing)
[        ] E/flutter ( 1322): #0      CameraController.initialize (package:camera/camera.dart:215:7)
[        ] E/flutter ( 1322): <asynchronous suspension>
[        ] E/flutter ( 1322): #1      InvoiceTakePicturePage2State.loadCameras (package:/invoiceform.dart:90:30)
[        ] E/flutter ( 1322): <asynchronous suspension>
[        ] E/flutter ( 1322): #2      InvoiceTakePicturePage2State.initState (package:/invoiceform.dart:104:5)
[        ] E/flutter ( 1322): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3787:58)
[        ] E/flutter ( 1322): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
[   +1 ms] E/flutter ( 1322): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
[        ] E/flutter ( 1322): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
[        ] E/flutter ( 1322): #7      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4579:32)
[        ] E/flutter ( 1322): #8      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
[        ] E/flutter ( 1322): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #12     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
[        ] E/flutter ( 1322): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
[        ] E/flutter ( 1322): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #20     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
[        ] E/flutter ( 1322): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #24     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
[        ] E/flutter ( 1322): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #28     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
[        ] E/flutter ( 1322): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
[        ] E/flutter ( 1322): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
[        ] E/flutter ( 1322): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
[        ] E/flutter ( 1322): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
[        ] E/flutter ( 1322): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
[        ] E/flutter ( 1322): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
[        ] E/flutter ( 1322): #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
[        ] E/flutter ( 1322): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322): Failed to handle method call
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322): java.lang.IllegalStateException: Reply already submitted
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:207)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.plugins.camera.CameraPlugin$Camera$1.run(CameraPlugin.java:297)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.plugins.camera.CameraPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPlugin.java:230)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at android.app.Activity.requestPermissions(Activity.java:4477)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.plugins.camera.CameraPlugin$Camera.<init>(CameraPlugin.java:317)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:183)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:199)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at android.os.MessageQueue.next(MessageQueue.java:326)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at android.os.Looper.loop(Looper.java:160)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at android.app.ActivityThread.main(ActivityThread.java:6669)
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera( 1322):    at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/MethodChannel#plugins.flutter.io/camera( 1322):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[        ] E/FlutterNativeView( 1322): Uncaught exception in binary message listener
[        ] E/FlutterNativeView( 1322): java.lang.IllegalStateException: Reply already submitted
[   +1 ms] E/FlutterNativeView( 1322):  at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
[   +1 ms] E/FlutterNativeView( 1322):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:217)
[        ] E/FlutterNativeView( 1322):  at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
[        ] E/FlutterNativeView( 1322):  at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/FlutterNativeView( 1322):  at android.os.MessageQueue.next(MessageQueue.java:326)
[        ] E/FlutterNativeView( 1322):  at android.os.Looper.loop(Looper.java:160)
[        ] E/FlutterNativeView( 1322):  at android.app.ActivityThread.main(ActivityThread.java:6669)
[        ] E/FlutterNativeView( 1322):  at java.lang.reflect.Method.invoke(Native Method)
[        ] E/FlutterNativeView( 1322):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/FlutterNativeView( 1322):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[+15506 ms] D/AndroidRuntime( 1322): Shutting down VM
[   +5 ms] E/AndroidRuntime( 1322): FATAL EXCEPTION: main
[        ] E/AndroidRuntime( 1322): Process: com.example., PID: 1322
[        ] E/AndroidRuntime( 1322): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=513469796, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example./com.example..MainActivity}: java.lang.NullPointerException: Attempt
to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
[        ] E/AndroidRuntime( 1322):     at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
[        ] E/AndroidRuntime( 1322):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
[        ] E/AndroidRuntime( 1322):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
[   +1 ms] E/AndroidRuntime( 1322):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[        ] E/AndroidRuntime( 1322):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[        ] E/AndroidRuntime( 1322):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
[        ] E/AndroidRuntime( 1322):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime( 1322):     at android.os.Looper.loop(Looper.java:193)
[        ] E/AndroidRuntime( 1322):     at android.app.ActivityThread.main(ActivityThread.java:6669)
[        ] E/AndroidRuntime( 1322):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 1322):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/AndroidRuntime( 1322):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[        ] E/AndroidRuntime( 1322): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
[        ] E/AndroidRuntime( 1322):     at io.flutter.plugins.camera.CameraPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPlugin.java:230)
[        ] E/AndroidRuntime( 1322):     at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
[        ] E/AndroidRuntime( 1322):     at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
[        ] E/AndroidRuntime( 1322):     at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
[        ] E/AndroidRuntime( 1322):     at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
[        ] E/AndroidRuntime( 1322):     at android.app.Activity.dispatchActivityResult(Activity.java:7458)
[        ] E/AndroidRuntime( 1322):     at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
[        ] E/AndroidRuntime( 1322):     ... 11 more
[  +19 ms] I/Process ( 1322): Sending signal. PID: 1322 SIG: 9
[  +47 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device.
[   +7 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example./cache/-appKGRLIU/-app/)
[   +1 ms] _deleteDevFS: {fsName: -app}
[ +256 ms] TimeoutException after 0:00:00.250000: Future not completed
```

```
Analyzing -app...
No issues found! (ran in 1.2s)
```

```
[√] Flutter (Channel master, v0.9.5-pre.30, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.9.5-pre.30 at C:\Flutter\flutter
    • Framework revision 11ed8aa164 (10 hours ago), 2018-09-27 21:38:17 -0700
    • Engine revision 2a22019a8d
    • Dart version 2.1.0-dev.6.0.flutter-7f9a9feae1

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\Marijn\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.27.2)
    • VS Code at C:\Users\Marijn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by thosakwe** [comment] 2018-10-02 21:00
My app crashes when debugging on a physical iOS device (iPhone 6S, iOS 11.4.1). I don't see any permissions error (though that may be occurring). Using XCode 10 on MacOS Sierra.

**Comment by cyanglaz** [comment] 2019-04-05 21:05
@SankaCoffee Is the issue still happening for you? 

cc @bparrishMines @mklim as code owners.

**Comment by divyanshub024** [comment] 2019-10-23 04:25
I'm also facing this error.
```
E/flutter ( 5834): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: CameraException(cameraPermission, Camera permission request ongoing)
E/flutter ( 5834): #0      CameraController.initialize (package:camera/camera.dart:288:7)
E/flutter ( 5834): <asynchronous suspension>
E/flutter ( 5834): #1      _RecordVideoState._initCamera (package:highlevel_flutter/widgets/video_recording/record_video.dart:38:16)
E/flutter ( 5834): <asynchronous suspension>
E/flutter ( 5834): #2      _RecordVideoState.initState (package:highlevel_flutter/widgets/video_recording/record_video.dart:32:5)
E/flutter ( 5834): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter ( 5834): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 5834): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 5834): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 5834): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 5834): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 5834): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 5834): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 5834): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 5834): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 5834): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 5834): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 5834): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter ( 5834): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 5834): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 5834): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 5834): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 5834): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 5834): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 5834): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 5834): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5834): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5834): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 5834): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 5834): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 5834): #44     StatefulElement._firstBuild (package:flutter/src/widgets/fr
```

**Comment by bparrishMines** [comment] 2019-11-13 22:46
Hi @divyanshub024, 

Could you provide which version of the plugin you are using? Also, could you provide a small code sample or what steps cause this error?

**Comment by divyanshub024** [comment] 2019-11-14 06:45
@bparrishMines It happens with the latest version also. It happens only when you open the camera and it asks you for permission. Once you allow permission it throws this error. Next time you open the app and it won't happen. It happens only when camera asks for permission.

**Comment by bparrishMines** [comment] 2019-11-21 01:31
@SankaCoffee @divyanshub024 I was able to reproduce this error with the lines 
```dart
controller.initialize();
await controller.initialize();
```

According to https://stackoverflow.com/questions/42035244/getting-w-activity-can-request-only-one-set-of-permissions-at-a-time, you may see this error when you request permissions while another request is still on ongoing.

It's possible that another plugin is requesting permissions at the same time you call `CameraController.initialize()` or that you are calling to initialize the camera in two places.

Let me know if this helps.

**Comment by divyanshub024** [comment] 2019-11-26 10:40
Hey @bparrishMines !! I'm aware of this StackOverflow answer. The camera is only initialized at one place and no other permission is requested at that time. But camera plugin asks for two permissions 1. camera and 2. microphone. I wonder if that can cause the issue?

**Comment by mjaffa-figure** [comment] 2020-01-07 18:22
@timsneath This forked repo someone did fixes this issue. Can we get their change merged into the latest of this one so I can have all the latest addons from the official one.

https://pub.dev/packages/camera_fix_exception#-readme-tab-

**Comment by mjaffa-figure** [comment] 2020-01-07 18:23
asap, we are shipped with this apparently broken on Android. We do most our testing on iOS, won't make that mistake again.

**Comment by TahaTesser** [comment] 2020-03-16 16:28
Hi @mklim 
Is this issue still valid given the merged PR?
Thank you

**Comment by bparrishMines** [comment] 2020-03-16 17:41
@TahaTesser It looks like this is a dup of https://github.com/flutter/flutter/issues/26228, so I will go ahead and close this as well.

**Closed by bparrishMines** 2020-03-16 17:41 UTC
Labels: p: camera, p: first party, plugin, severe: crash
