### ISSUE TITLE
Impeller rendering issue on Android

### ISSUE THREAD

**Issue by AsjadSiddiqui** [flutter/flutter#152298] opened 2024-07-25 08:56 UTC
### Steps to reproduce

1. Install the app from http://play.google.com/store/apps/details?id=com.mineswap.app
2. It does not occur on every device, it is very specific, even I can't reproduce on my device, but I have screenshots from users

### Expected results

Actual results

![Simulator Screenshot - iPhone 15 Pro - 2024-07-25 at 13 52 44](https://github.com/user-attachments/assets/7c84ea47-d230-4464-9f57-85ad6d7597be)
![Simulator Screenshot - iPhone 15 Pro - 2024-07-25 at 13 52 54](https://github.com/user-attachments/assets/78d73a9f-c79a-4f31-aff5-bd52d21de85e)
![Simulator Screenshot - iPhone 15 Pro - 2024-07-25 at 13 53 04](https://github.com/user-attachments/assets/86fc9567-c123-4b68-9d5b-a930da08c80e)
![Simulator Screenshot - iPhone 15 Pro - 2024-07-25 at 13 53 14](https://github.com/user-attachments/assets/1cc6dfca-3daf-4891-bdaa-b4c7b62edc49)

### Actual results

Green overlay on some devices
Samsung z flip
Itel A70 (Android 13)
Tecno Pop 7 Pro (Android 12)

![GTUSeOTW0AA7FXh](https://github.com/user-attachments/assets/8ba3b4d2-29c5-4e44-aef2-3e7094e814d4)
![GTUSeK8XsAEz-Mm](https://github.com/user-attachments/assets/ae2d9fce-424f-4b41-a060-6cbcec082aea)
![GTUSeK5X0AAbn5L](https://github.com/user-attachments/assets/af32c2f7-e191-417b-b234-60ed9e1c73a9)
![GTUSeFeWsAAKY7U](https://github.com/user-attachments/assets/4b5f7fab-80c5-45f4-bcbd-d684741faeff)
![GTUTt5kXoAACBzU](https://github.com/user-attachments/assets/42ae3e30-6ba3-4c26-aff9-90dc63584fef)
![GTURgWaW4AMYG7K](https://github.com/user-attachments/assets/87f20d8e-2a0b-486d-91ac-9471d68f9127)

### Code sample

<details open><summary>Code sample</summary>

```dart
// No code, since it is overlaying green on basic widgets, I think it happens on all impeller apps on these devices
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale
    en-PK)
    • Flutter version 3.22.3 on channel stable at
      /Users/asjad/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (8 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/asjad/Library/Android/sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)
    • Asjad’s iPhone (mobile)         • 00008120-001471610258201E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79
      darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome
      119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

(I upgraded to 3.22.3 afterwards, but the app is using 3.22.2, I have not yet updated the app with 3.22.3)

**Comment by darshankawar** [comment] 2024-07-25 11:24
@AsjadSiddiqui 
According to https://docs.flutter.dev/perf/impeller#android,
Impeller on Android with Vulkan is supported. Do you know if the devices on which this behavior occurs support Vulkan ?
You can determine whether the affected device supports Vulkan at [checking for Vulkan support](https://docs.vulkan.org/guide/latest/checking_for_support.html#_android).



> 1. Install the app from http://play.google.com/store/apps/details?id=com.mineswap.app

Does it use `flutter_svg` package or any svg icons / images ?
A minimal code sample instead of the entire app, would be helpful to analyze further.

**Comment by AsjadSiddiqui** [comment] 2024-07-25 11:50
Hi,
Yes, the devices support Vulkan

Some of the impacted devices are:
Samsung z flip
Itel A70 (Android 13)
Tecno Pop 7 Pro (Android 12)

and Vulkan is a requirement for Android devices beginning with Android 10.0

and yes `flutter_svg` is used throughout the app

also, as you can see in the screenshots, apart from the svgs normal container and text widgets are also being shown with a green overlay

Regarding the code sample, I am unable to reproduce this locally as I mentioned, but it appears to be happening on simple flutter widgets as well

**Comment by AsjadSiddiqui** [comment] 2024-07-25 11:54
I haver updated the app and switched it to use Skia now
But I think a simple hello world app running Impeller would give the same output on these devices

I unfortunately don't have the devices to test, so I cannot confirm this

**Comment by jonahwilliams** [comment] 2024-07-26 01:57
I believe this is a duplicate of https://github.com/flutter/flutter/issues/143573 : all affected devices should be PowerVR devices which have a buggy Vulkan driver. The fix is not in 3.22, but will be in the next stable and is in the 3.23 beta.

**Comment by AsjadSiddiqui** [comment] 2024-07-26 02:01
@jonahwilliams 
Thanks for bringing that to my attention
I was not aware of #143573

I will test with 3.23 when it is stable

**Comment by darshankawar** [comment] 2024-07-26 05:13
Closing as duplicate.

**Closed by darshankawar** 2024-07-26 05:13 UTC
Labels: in triage
