### ISSUE TITLE
IOS 14.0.1 text cannot be displayed

### ISSUE THREAD

**Issue by junglehuang** [flutter/flutter#68846] opened 2020-10-23 02:46 UTC
![image](https://user-images.githubusercontent.com/16217730/96949768-44f2df80-151b-11eb-8b8c-f53234bf3048.png)

IOS 14.0.1 The text cannot be displayed, but the function can be clicked and used normally

Text widget  
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available
```

**Comment by TahaTesser** [comment] 2020-10-23 08:44
Hi @junglehuang 
Looks like you're an older `stable` channel

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Can you please provide your `flutter doctor -v` with **upgrade**, your `flutter run --verbose`, and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2020-11-13 12:05
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-13 12:05 UTC
Labels: in triage
