### ISSUE TITLE
cloud_firestore should have FieldValue support

### ISSUE THREAD

**Issue by Skylled** [flutter/flutter#13905] opened 2018-01-04 16:08 UTC
At present it is impossible to delete a field from a Document, or use the server's timestamp in a field.

These are minor issues and can be worked around by nullifying the field or using DateTime.now() respectively.

The Firestore APIs have `FieldValue.delete` and `FieldValue.serverTimestamp` for these tasks, and the Flutter API should probably support them at some point.

These are very easily implemented on iOS, as shown by @ananfang, however on the Java side, there's a blocking issue. Namely, trying to route `com.google.firebase.firestore.FieldValue` through the Message codec triggers the following error:
```
E/MethodChannel#plugins.flutter.io/cloud_firestore(29782): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(29782): java.lang.RuntimeException: No properties to serialize found on class com.google.firebase.firestore.FieldValue$zzb
```

Searching for this error turns up in [Google Cloud Java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/f2f910fd55d05902f1dd7fabec0024256f75034a/google-cloud-firestore/src/main/java/com/google/cloud/firestore/CustomClassMapper.java#L568) and seems to be due to the way [FieldValue is implemented](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/c281a3e4685e35f1e777ade6191dada83d36fd94/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldValue.java) in that it simply returns an `Object()`. This is assuming the Android implementation is the same as GCJ's, but I can't verify that as Firebase for Android does not seem to be open source.

I'm opening this issue in hopes that someone on the team will know who to cc about this.

**Comment by kabukky** [comment] 2018-01-11 14:19
Wouldn't using `DateTime.now() ` simply insert the current timestamp into the payload? That is not equal to `FieldValue.serverTimestamp` as the current timestamp would be evaluated on the server in that case.

I agree that we need access to `FieldValue.serverTimestamp`. Any news on this?

**Comment by Skylled** [comment] 2018-01-11 14:33
@kabukky That is correct. And especially important when Batch/Transaction support is added, as `DateTime.now()` is the call time, not the `commit()` time.

Additionally, nullifying the value is not the same as deleting the field. In RTDB they're one and the same, but in Firestore, the field remains, returning null.

**Comment by kabukky** [comment] 2018-01-11 15:39
BTW:
@pauldemarco implemented `FieldValue` here: https://github.com/pauldemarco/plugins
But only for Android and the changes didn't make it back into the flutter/plugins main branch.

**Comment by Skylled** [comment] 2018-01-11 15:42
His implementation is the one I used that triggered the above Java errors.

**Comment by mdanics** [comment] 2018-03-20 15:46
Any updates on this?

**Comment by Skylled** [comment] 2018-03-26 14:12
cc @collinjackson @mit-mit This issue can't really be resolved on the Flutter side, and needs to be brought to the attention of someone on the Android Firebase team.

**Comment by msaliminia** [comment] 2018-04-28 11:43
any update on this?

**Comment by harrisonturton** [comment] 2018-05-01 02:12
A workaround is to use the [Network Time Protocol](http://ntp.org/), seen in the [ntp package](https://pub.dartlang.org/packages/ntp#-readme-tab-) (Note: I haven't used it).

This doesn't solve all the problems (The timestamp is generated at call-time, not when it reaches the server), but when we only need consistent timestamps in relation to our clients, this solution works.

It's not a super clean way to do it, however. I hope there are updates.

**Comment by pinkfish** [comment] 2018-05-07 17:43
Is there a different work around here?  I was thinking about this from the flutter into the java direction.  How do you serialize a value so that you can say the field should be deleted?  From looking at the docs firebase only serializes things like maps and arrays, so this would not exactly work.  You could add an extra array to the set/update calls to pass in a delete set so we could delete those fields?  In the other direction seems like you could process the return results to pull out the servertimestamps and turn them into something flutter can understand?

**Comment by collinjackson** [comment] 2018-05-15 16:38
I'm investigating

**Comment by CyanBlob** [comment] 2018-05-18 01:36
@collinjackson Did you find anything? I just got to the point in my app where I need this.

**Comment by Buli1212** [comment] 2018-06-02 15:41
I have the blog app with user comments and I would rather use this than NTP. Any updates?

**Comment by dragosholban** [comment] 2018-06-10 15:02
Anything new? :(

**Comment by dragosholban** [comment] 2018-06-12 11:54
I tried to user NTP but if the device is offline is does not work. Without NTP, firestore works offline, so you lose this. I tried another workaround and seems to function pretty fine: use cloud functions to update the document when it's created or updated.

**Comment by varundroid** [comment] 2018-06-23 05:59
Okay, after six months, I am gonna ask the same question as others. 

**Any updates on this?** 

I am trying to avoid using MethodChannel to achieve this.

**Comment by shashikantdurge** [comment] 2018-08-06 04:54
Any updates on this?

**Comment by shashikantdurge** [comment] 2018-08-06 04:54
Any updates on this?

**Comment by creativecreatorormaybenot** [comment] 2018-08-10 17:41
If anyone has found a solution using MethodChannel, there is [an open bounty on StackOverflow](https://stackoverflow.com/questions/51456790/firestore-rules-verify-timestamp) expiring 15/10/2018.  
Would be really nice to have a working workaround in here anyway because of the problems @Skylled mentioned.

**Comment by rlee1990** [comment] 2018-08-22 03:06
So I'm guessing that there are still not any updates to this? This should be a high priority

**Comment by zoechi** [comment] 2018-08-22 06:10
Community contributions are welcome.

**Comment by Skylled** [comment] 2018-08-22 14:19
@zoechi I don't believe community contribution is possible for this issue, given that Firebase for Android is closed-source. This issue needs a response from someone on the Firebase team, which shouldn't be too terribly hard to get, given that Flutter and Firebase are both Google products.

**Comment by mit-mit** [comment] 2018-08-22 15:17
cc @kroikie for input

**Comment by shashikantdurge** [comment] 2018-08-31 11:26
I'm trapped!!

**Comment by iamjavademon** [comment] 2018-09-02 17:54
@shashikantdurge me too. Looking for a temporary workaround though and i think using cloud functions to save data in firestore so you can get server time and save it can be the wayout.

**Comment by creativecreatorormaybenot** [comment] 2018-09-02 21:33
@iamjavademon I feel like Cloud Functions is the only option right now. If that is the only purpose of the function, it will obviously add to the billing.

**Comment by pulyaevskiy** [comment] 2018-09-05 04:36
FYI: here's a PR which implements all available FieldValues for Firestore: https://github.com/flutter/plugins/pull/760

**Comment by rlee1990** [comment] 2018-09-05 16:59
@pulyaevskiy when will this be available?

**Comment by pulyaevskiy** [comment] 2018-09-05 18:00
Depends on the PR review speed. I recommend subscribing to it to get updates as soon as it's merged.

Pinging @kroikie is the assignee on this issue.

**Comment by gazialankus** [comment] 2018-09-05 21:45
@rlee1990 in the meantime, you should be able to set your pubspec.yaml to use this directly: https://github.com/pulyaevskiy/plugins/tree/firestore-arrays-and-persistence like this https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by kroikie** [comment] 2018-09-05 23:14
Thanks for the feedback and contributions, FieldValue is now available for use in the cloud_firestore plugin.

**Closed by kroikie** 2018-09-05 23:14 UTC
Labels: p: firebase, plugin

**Comment by johnson-yeap** [comment] 2018-09-16 13:17
I'm afraid FieldValue.arrayUnion([FieldValue.serverTimestamp()]) does not work properly.

`java.lang.IllegalArgumentException: Invalid data. Nested arrays are not supported`

**Comment by pulyaevskiy** [comment] 2018-09-16 15:44
@johnson-yeap I saw somewhere this is not supported by Firestore itself (or the sdk at least).

**Comment by johnson-yeap** [comment] 2018-09-17 01:30
@pulyaevskiy FieldValue has been released in v0.8.0
Do you mean the operation that I tried to perform is not supported?

**Comment by pulyaevskiy** [comment] 2018-09-17 01:46
@johnson-yeap Sorry, I meant serverTimestamps inside arrays in Firestore are not supported.

Here is relevant issue in the admin sdk: https://github.com/firebase/firebase-admin-node/issues/336#issuecomment-412614286

**Comment by jasonkaruza** [comment] 2018-12-11 21:30
I have the v.0.8.2+3 version of the plugin in my app, but when trying to do a batch write with a Map containing FieldValue.delete() I still get the serialization error.

Example:
batch.setdata(someDocumentReference, {someKey: FieldValue.delete()});

**Comment by adamkoch** [comment] 2018-12-11 22:21
@jasonkaruza did you try batch.updateData() instead of setData()?

**Comment by jasonkaruza** [comment] 2018-12-12 04:45
You're a rockstar @adamkoch +++ Thank you!

**Comment by gching** [comment] 2019-02-06 02:44
Given @adamkoch advice, `WriteBatch.updateData`works, but `WriteBatch.setData` still does not support `FieldValue`. Don't think this should be closed, or another issue should be open specifically for `WriteBatch.setData`

My current solution is calling `setData` then afterwards calling `updateData` with my `FieldValue`s.

**Comment by adamkoch** [comment] 2019-02-06 21:52
@gching I could be wrong, but I think this is how Firestore works and not an issue with the Flutter lib. Only updateData() supports FieldValue.delete():
https://firebase.google.com/docs/firestore/manage-data/delete-data#fields

**Comment by gching** [comment] 2019-02-10 10:05
@adamkoch interesting, is this also the case for `FieldValue.serverTimestamp()`? Sorry for not being clear!

**Comment by adamkoch** [comment] 2019-02-10 10:27
@gching I'm not too sure. I barely see any examples in the docs of it being used with `setData()`. But the [docs](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FieldValue.html#serverTimestamp()) do say it should work with both set and update so I think it should work (vs the [docs](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FieldValue.html#delete()) for `FieldValue.delete()`saying it only works with update).

**Comment by stephenhuey** [comment] 2019-03-02 21:20
I'm not sure what the expected behavior is, but if I use `FieldValue.serverTimestamp()` with a collection.add method, my listener fires twice, once with a null timestamp and then with a populated timestamp.  I'm filtering by only recent changes with 

```
where('createdAt', isGreaterThan: Timestamp.now())
```

and I tried both `querySnapshot.documentChanges` and `querySnapshot.documents` and in both cases it fires twice, and in both cases the timestamp is first null and then present.  The only thing helpful is that when using `documentChanges` it tells me the second time that the type is modified rather than added.  

Is this expected behavior in Firestore?  Always two events for a single addition?

**Comment by pulyaevskiy** [comment] 2019-03-02 22:28
@stephenhuey See this SO answer: https://stackoverflow.com/a/54449033/5280562

**Comment by kroikie** [comment] 2019-10-13 19:20
@Skylled

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/917. Any further collaboration will be done there.
