### ISSUE TITLE
 Long press home, after entering task management, the toolbar displays an exception.

### ISSUE THREAD

**Issue by yljjiava** [flutter/flutter#24649] opened 2018-11-22 08:28 UTC
![123](https://user-images.githubusercontent.com/10340521/48890348-939d2800-ee73-11e8-8286-cb6ca754ad60.png)

**Comment by zoechi** [comment] 2018-11-22 15:51
Please add the output of `flutter doctor -v`
and the console log that contains the exception details if possible.

Can you reproduce this with an unmodified app created with `flutter create foo` as well, or is this only with custom code?

**Comment by yljjiava** [comment] 2018-11-23 02:42
> Please add the output of `flutter doctor -v`
> and the console log that contains the exception details if possible.
> 
> Can you reproduce this with an unmodified app created with `flutter create foo` as well, or is this only with custom code?


I created a new project with androidstudio and didn't modify any code.this is my code：
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My App',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by zoechi** [comment] 2018-11-25 13:43
Please add the output of flutter doctor -v

I wasn't able to reproduce on Android 28 and Android 26.

**Comment by yljjiava** [comment] 2018-11-26 03:01
> 请添加flutter doctor -v的输出
> 
> 我无法在Android 28和Android 26上重现。
flutter doctor -v
[√] Flutter (Channel beta, v0.11.7, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 0.11.7 at E:\flutter\flutter_windows_v0.9.4-beta\flutter
    • Framework revision 7a005e1dcd (6 days ago), 2018-11-19 11:14:05 -0500
    • Engine revision 2e06da3df9
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Android\Android Studio3.1.3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.0)
    • Android Studio at D:\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 3.2)
    • Android Studio at D:\Android\Android Studio3.1.3
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • HHT6C • 0123456789ABCDEF • android-arm64 • Android 5.1 (API 22)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment] 2018-11-26 10:34
Can you reproduce on a different device or with an emulator?

**Comment by yljjiava** [comment] 2018-11-29 03:40
> Can you reproduce on a different device or with an emulator?

I have tested it on the following devices and simulators.

![6 0](https://user-images.githubusercontent.com/10340521/49197724-f722da80-f3ca-11e8-98f2-d2aab43765bd.png)
![7 0](https://user-images.githubusercontent.com/10340521/49197729-fa1dcb00-f3ca-11e8-84c3-b5cd65754002.png)

There is also a physical machine(HUAWEI MATE 20 pro,android 8.0), the picture is not uploaded, the result is the same as Figure 1.

**Comment by goderbauer** [comment] 2018-12-03 21:55
Wha is the exception you're seeing? I am not sure what the problem is that you're describing.

**Comment by wouterhardeman** [comment] 2018-12-04 16:20
Isn't it just the actual app bar?

Can you change ``primarySwatch: Colors.blue`` in the ThemeData to ``primarySwatch: Colors.red`` and post what it looks like?

**Comment by zoechi** [comment] 2018-12-18 16:05
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-12-18 16:05 UTC
Labels: framework, severe: crash, waiting for customer response, ▣ platform-android
