### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by muhammedfisek** [flutter/flutter#156320] opened 2024-10-07 13:52 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=00008130-0010385A3A08001C --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:636:22)
<asynchronous suspension>
#7      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:476:33)
<asynchronous suspension>
#8      HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart:432:14)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:463:34)
<asynchronous suspension>
#11     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:801:9)
<asynchronous suspension>
#12     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:799:5)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:709:15)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.19.5, on macOS 15.0 24A335 darwin-arm64, locale tr-TR)
    • Flutter version 3.19.5 on channel stable at /Users/developer/fluttersdk/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart-sdk/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/developer/fluttersdk/flutter. Consider adding /Users/developer/fluttersdk/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (6 months ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/developer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008130-0010385A3A08001C • ios            • iOS 18.0 22A3354
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 129.0.6668.90

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.0.0+25
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 300451adae589accbece3490f4396f10bdf15e6e
### Plugins
audio_session-0.1.21
better_open_file-3.6.5
camera-0.11.0+2
camera_android_camerax-0.6.5+2
camera_avfoundation-0.9.17+3
camera_filters-0.3.1
camera_web-0.3.5
connectivity_plus-6.0.5
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
flutter_localization-0.2.1
flutter_plugin_android_lifecycle-2.0.19
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
image_cropper-8.0.1
image_cropper_for_web-6.0.1
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
just_audio-0.9.40
just_audio_web-0.4.12
libphonenumber_plugin-0.3.3
libphonenumber_web-0.3.2
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.1
shared_preferences_windows-2.4.1
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.2
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_player-2.9.1
video_player_android-2.4.14
video_player_avfoundation-2.6.1
video_player_web-2.3.2
wakelock_plus-1.2.8
webview_flutter-4.8.0
webview_flutter_android-3.16.3
webview_flutter_wkwebview-3.14.0

**Comment by huycozy** [comment] 2024-10-08 06:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131.

**Closed by huycozy** 2024-10-08 06:00 UTC
Labels: in triage
