### ISSUE TITLE
【google_maps_flutter】The current location is not accurate in China

### ISSUE THREAD

**Issue by DuQuanzhong** [flutter/flutter#141558] opened 2024-01-15 10:00 UTC
### Steps to reproduce

The adopted coordinate system for latitude and longitude is different.

### Expected results

Accurate positioning in China.

### Actual results

The current location is not accurate in China

### Code sample

import 'package:flutter/material.dart';
import 'package:flutter_easy/components/export.dart';
import 'package:get/get.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import 'google_map_controller.dart';

class GoogleMapPage extends StatefulWidget {
  const GoogleMapPage({super.key});

  @override
  State<GoogleMapPage> createState() => _GoogleMapPageState();
}

class _GoogleMapPageState extends State<GoogleMapPage> {
  @override
  final googleGetController = Get.put<GoogleMapGetController>(GoogleMapGetController());
  @override
  Widget build(BuildContext context) {
    return GetBuilder<GoogleMapGetController>(builder: (_) {
      return BaseScaffold(
        appBar: BaseAppBar(
          title: Text('谷歌地图'),
        ),
        body: Obx(() => GoogleMap(
          mapType: MapType.normal,
          initialCameraPosition: const CameraPosition(
            target: LatLng(116.405285, 39.904989),
            zoom: 18,
          ),
          myLocationEnabled: true,
          markers: googleGetController.markers.value,

          onMapCreated: (GoogleMapController mapController) async {
            googleGetController.googleController = mapController;
            await googleGetController.fetchLocation();
            for (var element in googleGetController.markers.value) {
              mapController.showMarkerInfoWindow(element.markerId);
            }
          },
        )),
      );
    });

  }
}

class GoogleMapGetController extends GetxController {

  late GoogleMapController googleController;
  var markers = (<Marker>{}).obs;
  late BitmapDescriptor markerIcon1;
  late BitmapDescriptor markerIcon2;

  @override
  Future<void> onInit() async {
    super.onInit();
  }

  @override
  void onClose() {
    googleController.dispose();
  }
  ///  获取当前位置
  fetchLocation() async {
    if (await PermissionUtil.requestLocationPermission()) {
      markerIcon1 = await _getAssetIcon(Get.context!, 'assets/maps/map_marker.png');
      markerIcon2 = await _getAssetIcon(Get.context!, 'assets/maps/map_marker_2.png');
      Position position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
      logPrint(position.latitude);
      logPrint(position.longitude);
      ///  谷歌地图在国内用的坐标是国测局坐标
      var coordinate = MapUtil.gps84_To_Gcj02(position.latitude, position.longitude);

      // List<num> gpsResult = MapUtil.gcj02_To_Gps84(result[0], result[1]);

      //
      markers.value.clear();
      MarkerId markerId = const MarkerId('23123123123');
      Marker marker = Marker(
          markerId: markerId,
          position: LatLng(coordinate[0].toDouble(), coordinate[1].toDouble()),
          infoWindow: const InfoWindow(title: '哈哈哈哈哈', snippet: '*'),
          // onTap: _ontap,
          // onDragEnd: _onDragEnd,
          // onDrag: _onDrag,
          zIndex: 1,
        icon: markerIcon1,
      );
      markers.value.add(marker);

      // Future.delayed(const Duration(milliseconds: 100), () {
      //   googleController?.showMarkerInfoWindow(markers.toList()[0].markerId);
      // });
      var currentPosition = CameraPosition(
        target: LatLng(coordinate[0].toDouble(), coordinate[1].toDouble()),
        zoom: 18,
      );
      googleController.moveCamera(CameraUpdate.newCameraPosition(currentPosition));
    }
  }

  Future<BitmapDescriptor> _getAssetIcon(BuildContext context, String? icon) async {
    final Completer<BitmapDescriptor> bitmapIcon = Completer<BitmapDescriptor>();
    final ImageConfiguration config = createLocalImageConfiguration(context);

    AssetImage(icon ?? '').resolve(config).addListener(ImageStreamListener((ImageInfo image, bool sync) async {
      final ByteData? bytes =
      await image.image.toByteData(format: ImageByteFormat.png);
      if (bytes == null) {
        bitmapIcon.completeError(Exception('Unable to encode icon'));
        return;
      }
      final BitmapDescriptor bitmap =
      BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
      bitmapIcon.complete(bitmap);
    }));

    return bitmapIcon.future;
  }

}class GoogleMapGetController extends GetxController {

  late GoogleMapController googleController;
  var markers = (<Marker>{}).obs;
  late BitmapDescriptor markerIcon1;
  late BitmapDescriptor markerIcon2;

  @override
  Future<void> onInit() async {
    super.onInit();
  }

  @override
  void onClose() {
    googleController.dispose();
  }
  ///  获取当前位置
  fetchLocation() async {
    if (await PermissionUtil.requestLocationPermission()) {
      markerIcon1 = await _getAssetIcon(Get.context!, 'assets/maps/map_marker.png');
      markerIcon2 = await _getAssetIcon(Get.context!, 'assets/maps/map_marker_2.png');
      Position position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
      logPrint(position.latitude);
      logPrint(position.longitude);
      ///  谷歌地图在国内用的坐标是国测局坐标
      var coordinate = MapUtil.gps84_To_Gcj02(position.latitude, position.longitude);

      // List<num> gpsResult = MapUtil.gcj02_To_Gps84(result[0], result[1]);

      //
      markers.value.clear();
      MarkerId markerId = const MarkerId('23123123123');
      Marker marker = Marker(
          markerId: markerId,
          position: LatLng(coordinate[0].toDouble(), coordinate[1].toDouble()),
          infoWindow: const InfoWindow(title: '哈哈哈哈哈', snippet: '*'),
          // onTap: _ontap,
          // onDragEnd: _onDragEnd,
          // onDrag: _onDrag,
          zIndex: 1,
        icon: markerIcon1,
      );
      markers.value.add(marker);

      // Future.delayed(const Duration(milliseconds: 100), () {
      //   googleController?.showMarkerInfoWindow(markers.toList()[0].markerId);
      // });
      var currentPosition = CameraPosition(
        target: LatLng(coordinate[0].toDouble(), coordinate[1].toDouble()),
        zoom: 18,
      );
      googleController.moveCamera(CameraUpdate.newCameraPosition(currentPosition));
    }
  }

  Future<BitmapDescriptor> _getAssetIcon(BuildContext context, String? icon) async {
    final Completer<BitmapDescriptor> bitmapIcon = Completer<BitmapDescriptor>();
    final ImageConfiguration config = createLocalImageConfiguration(context);

    AssetImage(icon ?? '').resolve(config).addListener(ImageStreamListener((ImageInfo image, bool sync) async {
      final ByteData? bytes =
      await image.image.toByteData(format: ImageByteFormat.png);
      if (bytes == null) {
        bitmapIcon.completeError(Exception('Unable to encode icon'));
        return;
      }
      final BitmapDescriptor bitmap =
      BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
      bitmapIcon.complete(bitmap);
    }));

    return bitmapIcon.future;
  }

}

### Screenshots or Video

![IMG_4976](https://github.com/flutter/flutter/assets/5549754/4b3a8c64-f17d-4696-b577-3fc0bd3cd7c6)

### Logs

[DEBUG] 2024-01-15 17:58:48.280240 CLOSE TO ROUTE /googleMapPage
[DEBUG] 2024-01-15 17:58:48.609424 "GoogleMapGetController" onDelete() called
[DEBUG] 2024-01-15 17:58:48.609694 "GoogleMapGetController" deleted from memory
[DEBUG] 2024-01-15 17:58:49.262543 GOING TO ROUTE /googleMapPage
[DEBUG] 2024-01-15 17:58:49.281235 Instance "GoogleMapGetController" has been created
[DEBUG] 2024-01-15 17:58:49.281690 Instance "GoogleMapGetController" has been initialized
[] nw_path_necp_check_for_updates Failed to copy updated result (22)
[log] 39.892222883662676
[log] 116.47542076250697

### Flutter Doctor output

/Users/menumr/fvm/versions/3.10.2/bin/flutter doctor --verbose
[!] Flutter (Channel stable, 3.10.2, on macOS 14.1.2 23B92 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.2 on channel stable at /Users/menumr/fvm/versions/3.10.2
    ! Warning: `flutter` on your path resolves to /Users/menumr/fvm/versions/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/menumr/fvm/versions/3.10.2. Consider adding /Users/menumr/fvm/versions/3.10.2/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/menumr/fvm/versions/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/menumr/fvm/versions/3.10.2. Consider adding /Users/menumr/fvm/versions/3.10.2/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (8 months ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/menumr/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/menumr/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • 杜先生 (mobile)              • 00008101-000C49261A92001E • ios            • iOS 16.5.1 20F75
    • Quanzhong的iPhone (mobile) • 00008101-000915222EE0001E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)           • macos                     • darwin-x64     • macOS 14.1.2 23B92 darwin-x64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 120.0.6099.216

**Comment by stuartmorgan** [comment] 2024-01-15 11:32
Duplicate of https://github.com/flutter/flutter/issues/124576

**Closed by stuartmorgan** 2024-01-15 11:32 UTC
