### ISSUE TITLE
Flutter Flavor is not working on Web with Flutter 3.19.0

### ISSUE THREAD

**Issue by rohanjariwala03** [flutter/flutter#143582] opened 2024-02-16 15:34 UTC
### Steps to reproduce

1. Your flutter version should be 3.19.0
2. Add support for flutter flavor in your multi-platform application
3. Try to launch your app. It will throw following error
 
<img width="522" alt="image" src="https://github.com/flutter/flutter/assets/34390549/8b6a6360-2f9a-4244-acd6-68d352b81acb">

Moreover, When I do `flutter build web --flavor ....`. It's throwing this errors

<img width="1005" alt="image" src="https://github.com/flutter/flutter/assets/34390549/a95f879e-9bfd-45c5-ace3-5bbe99ac08f8">

### Expected results

The app should run perfectly without having any of the issue which it was in flutter version 3.16.9 or before.

### Actual results

Currently getting errors that flutter flavor is only supported on `Android, iOS and MacOs` and not on web.

**Error while running in Debug mode**

<img width="522" alt="image" src="https://github.com/flutter/flutter/assets/34390549/8b6a6360-2f9a-4244-acd6-68d352b81acb">

### Code sample

```
import 'package:flutter/material.dart';
import 'package:medium_build_flavor/app_config.dart';
import 'package:medium_build_flavor/home_page.dart';

void main() async {
  AppConfig.create(
    appName: "Prod Flavor Example",
    baseUrl: "https://dwirandyh.com",
    primaryColor: Colors.yellow,
    flavor: Flavor.prod,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo Production',
      theme: ThemeData(
        primarySwatch: AppConfig.shared.primaryColor,
      ),
      home: const HomePage(),
    );
  }
}

### Screenshots or Video

_No response_

### Logs

<details open><summary>Logs</summary>

```console
Compiling lib/main_dev.dart for the Web...                      
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/accelerometer.dart:52:45:
Error: The type 'JSObject' can't be used as supertype.
class AccelerometerReadingValues implements JSObject {
                                            ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/ambient_light.dart:22:44:
Error: The type 'JSObject' can't be used as supertype.
class AmbientLightReadingValues implements JSObject {
                                           ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/anchors.dart:11:27:
Error: The type 'JSObject' can't be used as supertype.
class XRAnchor implements JSObject {}
                          ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/anchors.dart:21:30:
Error: The type 'JSObject' can't be used as supertype.
class XRAnchorSet implements JSObject {}
                             ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/angle_instanced_arrays.dart:11:41:
Error: The type 'JSObject' can't be used as supertype.
class ANGLE_instanced_arrays implements JSObject {
                                        ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/attribution_reporting_api.dart:9:49:
Error: The type 'JSObject' can't be used as supertype.
class HTMLAttributionSrcElementUtils implements JSObject {}
                                                ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/attribution_reporting_api.dart:20:53:
Error: The type 'JSObject' can't be used as supertype.
class AttributionReportingRequestOptions implements JSObject {
                                                    ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/audio_output.dart:10:37:
Error: The type 'JSObject' can't be used as supertype.
class AudioOutputOptions implements JSObject {
                                    ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:17:41:
Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchManager implements JSObject {}
                                        ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:32:43:
Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchUIOptions implements JSObject {
                                          ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:86:40:
Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchRecord implements JSObject {}
                                       ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_sync.dart:11:30:
Error: The type 'JSObject' can't be used as supertype.
class SyncManager implements JSObject {}
                             ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/badging.dart:9:33:
Error: The type 'JSObject' can't be used as supertype.
class NavigatorBadge implements JSObject {}
                                ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/capture_handle_identity.dart:10:38:
Error: The type 'JSObject' can't be used as supertype.
class CaptureHandleConfig implements JSObject {
                                     ^
/opt/hostedtoolcache/flutter/stable-3.19.0-x64/.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/capture_handle_identity.dart:30:32:
Error: The type 'JSObject' can't be used as supertype.
class CaptureHandle implements JSObject {

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.0 23A344 darwin-arm64, locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 15.2)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.1)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by Reprevise** [comment] 2024-02-16 17:34
Hey @rohanjariwala03! Flavors are only supported on iOS, macOS, and Android as seen in the error message. I am also getting that error when running `flutter build web --flavor` on 3.16.9. There was an issue #59388 to support flavors on web, but it has since been closed. As an alternative, you can use `--dart-define KEY=VALUE`.

**Comment by rebindev** [comment] 2024-02-16 22:10
Same issue after upgrading to 3.19.0

**Comment by viniciusddrft** [comment] 2024-02-17 00:49
I had the same mistake.


My error:

Launching lib/main.dart on Chrome in debug mode...
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/accelerometer.dart:52:45: Error: The type 'JSObject' can't be used as supertype.
class AccelerometerReadingValues implements JSObject {
                                            ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/ambient_light.dart:22:44: Error: The type 'JSObject' can't be used as supertype.
class AmbientLightReadingValues implements JSObject {
                                           ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/anchors.dart:11:27: Error: The type 'JSObject' can't be used as supertype.
class XRAnchor implements JSObject {}
                          ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/anchors.dart:21:30: Error: The type 'JSObject' can't be used as supertype.
class XRAnchorSet implements JSObject {}
                             ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/angle_instanced_arrays.dart:11:41: Error: The type 'JSObject' can't be used as supertype.
class ANGLE_instanced_arrays implements JSObject {
                                        ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/attribution_reporting_api.dart:9:49: Error: The type 'JSObject' can't be used as supertype.
class HTMLAttributionSrcElementUtils implements JSObject {}
                                                ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/attribution_reporting_api.dart:20:53: Error: The type 'JSObject' can't be used as supertype.
class AttributionReportingRequestOptions implements JSObject {
                                                    ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/audio_output.dart:10:37: Error: The type 'JSObject' can't be used as supertype.
class AudioOutputOptions implements JSObject {
                                    ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:17:41: Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchManager implements JSObject {}
                                        ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:32:43: Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchUIOptions implements JSObject {
                                          ^
../../../../.pub-cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:86:40: Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchRecord implements JSObject {}


My flutter doctor: 

❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.19.0, on Arch Linux 6.7.4-arch1-1, locale pt_BR.UTF-8)
    ! Warning: `dart` on your path resolves to /opt/dart-sdk/bin/dart, which is not inside your current Flutter SDK checkout at
      /home/viniciusddrft/Downloads/flutter. Consider adding /home/viniciusddrft/Downloads/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by aumb** [comment] 2024-02-17 15:39
inspired by https://github.com/flutter/flutter/issues/143574#issuecomment-1948284087 this works for me

```json
  {
      "name": "Web Development",
      "request": "launch",
      "type": "dart",
      "flutterMode": "debug",
      "args": [
        "--web-port",
        "5000",
        "--dart-define",
        "flavor=development"
      ],
      "program": "lib/main_development.dart"
   }
  ```

**Comment by rohanjariwala03** [comment] 2024-02-18 13:47
@aumb That's not the case for me. Every time my pull request merge it's running workflow and that work flow building app for Web. So, I don't know how can I add this to my workflow file.

**Comment by amrgetment** [comment] 2024-02-18 14:15
@aumb My full implementation for web flavors and mobile, I have flavors for firebase-messaging-sw.js if you want too

```
Flavor getEnvironmentFlavor() {
  // Flutter has the flavor you passed by cli '--flavor dev'
  // for mobile and desktop only
  // https://api.flutter.dev/flutter/services/appFlavor-constant.html
  const String defaultFlutterFlavor =
      String.fromEnvironment('FLUTTER_APP_FLAVOR') != ''
          ? String.fromEnvironment('FLUTTER_APP_FLAVOR')
          : '';

  if (defaultFlutterFlavor.isNotEmpty) {
    return Flavor.byName(defaultFlutterFlavor);
  }

  const String flavorEnv =
      bool.hasEnvironment('flavor') ? String.fromEnvironment('flavor') : '';
  return Flavor.byName(flavorEnv);
}
```

**Comment by RomjanHossain** [comment] 2024-02-18 16:35
Anyone who's having problem with Launching flavor in Linux.

```
    {
      "name": "Linux Development",
      "request": "launch",
      "type": "dart",
      "flutterMode": "debug",
      "args": [
          "--dart-define",
          "flavor=development"
      ],
      "program": "lib/main_development.dart",
  },
```

**Comment by huycozy** [comment] 2024-02-19 05:10
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143574. Please follow up on it for updates.

**Closed by huycozy** 2024-02-19 05:10 UTC
Labels: in triage
