### ISSUE TITLE
TextField textInputAction.next cannot allow TextField with obscureText=true to correctly obtain focus.

### ISSUE THREAD

**Issue by azhon** [flutter/flutter#140721] opened 2023-12-29 03:29 UTC
### Steps to reproduce

When TextField sets textInputAction to next and the next TextField's obscureText is true, when you click the next button on the keyboard, TextField will gain focus and then immediately lose focus.

### Expected results

TextField gets focus normally

### Actual results

TextField gets focus normally

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TextField',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('TextField'),
      ),
      body: const Padding(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('TextField'),
            TextField(
              textInputAction: TextInputAction.next,
            ),
            TextField(
              obscureText: true,
            ),

            ///
            Padding(
              padding: EdgeInsets.only(top: 16.0),
              child: Text('CupertinoTextField'),
            ),
            Padding(
              padding: EdgeInsets.symmetric(vertical: 16.0),
              child: CupertinoTextField(
                textInputAction: TextInputAction.next,
                placeholder: 'text field',
              ),
            ),
            CupertinoTextField(
              obscureText: true,
              placeholder: 'obscureText field',
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

It can be seen from the video that TextField first gained focus, displayed the keyboard, and then immediately lost focus but the keyboard was not hidden.

https://github.com/flutter/flutter/assets/20559556/09b1530c-0d88-438d-84bb-6d3572a3a6c3

</details>

### Logs

<details open><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 12.5 21G72 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.5)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by khushiarora001** [comment] 2023-12-30 13:08
I Looked at this yesterday but couldn't identify the root cause @azhon  can you tell your keyboard setting I mean which language  you add on in your keyboard

**Comment by sharabiddin** [comment] 2024-01-01 11:15
Could not reproduce, need more details

**Comment by azhon** [comment] 2024-01-02 01:30
<img width="376" alt="image" src="https://github.com/flutter/flutter/assets/20559556/d06b7fcc-c918-4e16-83ca-46929cd84b9e">
I found out that the problem is with the security keyboard switch. Will the above problem occur when it is turned on?

- More console logs

```
Performing hot restart...
Syncing files to device LIO AL00...
Restarted application in 1,061ms.
I/DecorView(27755): updateColorViewInt type:1 size: 122 color:fffcfcfc appColor:fffcfcfc
D/HwDragEnhancementImpl(27755): handleTimerDrag: false
D/HwDragEnhancementImpl(27755): handleTimerDrag: false
D/WebViewDragEnhancement(27755): dragReset.
D/WebViewDragEnhancement(27755): dragReset cacheSize = 0
I/InputMethodManager(27755): Starting input: reason=APP_CALLED_RESTART_INPUT_API
W/HwRemoteInputMethodManager(27755): isCasting false because IHwDistributedWindowManager is invalid.
I/InputMethodManager(27755): Starting input: Bind resultString=SUCCESS_WITH_IME_SESSION
I/InputMethodManager(27755): showSoftInput, displayId=-1,callers=android.view.inputmethod.InputMethodManager.showSoftInput:1785 android.view.inputmethod.InputMethodManager.showSoftInput:1723 io.flutter.plugin.editing.TextInputPlugin.showTextInput:397 io.flutter.plugin.editing.TextInputPlugin$2.show:102 
D/InputMethodManager(27755): showSoftInput() view=io.flutter.embedding.android.FlutterView{91e6592 VFE...... .F...... 0,0-1176,2278 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/AssistStructure(27755): Flattened final assist data: 388 bytes, containing 1 windows, 3 views
D/InsetsSourceConsumer(27755): ViewUI_insets setControl -> ITYPE_IME on com.azhon.todo_flutter/com.azhon.todo_flutter.MainActivity
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1176,99], mVisible=true}
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2278][1176,2400], mVisible=true}
D/InsetsSourceConsumer(27755): ViewUI_insets setControl -> ITYPE_IME on com.azhon.todo_flutter/com.azhon.todo_flutter.MainActivity
D/InsetsController(27755): ViewUI_insets show(ime(), fromIme=true)
I/InsetsController(27755): ViewUI_insets applyAnimation types:8,show:true, this:android.view.InsetsController@33948de
I/InsetsController(27755): ViewUI_insets controlAnimation types: 8
D/InsetsController(27755): ViewUI_insets controlAnimation after canel existing types: 8
I/DecorView(27755): updateColorViewInt type:1 size: 122 color:fffcfcfc appColor:fffcfcfc
D/SceneHelper(27755): notifyState ltpo1.0 push currentPackageName=com.azhon.todo_flutter ltpo10SceneState=3009 scene=IME
I/HwViewRootImpl(27755): Add sceneId 96 topId: 10
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1176,99], mVisible=true}
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2278][1176,2400], mVisible=true}
I/InsetsSourceConsumer(27755): ViewUI_insets mSourceControl is null notifyControlRevoked type: 1
I/InsetsAnimationCtrlImpl(27755): Ime in switching, skipping updateSurfacePosition.
D/SceneHelper(27755): notifyState ltpo1.0 push currentPackageName=com.azhon.todo_flutter ltpo10SceneState=3010 scene=IME
I/HwViewRootImpl(27755): remove sceneId 96 topId: 10
I/InputMethodManager(27755): Starting input: reason=APP_CALLED_RESTART_INPUT_API
W/HwRemoteInputMethodManager(27755): isCasting false because IHwDistributedWindowManager is invalid.
I/InputMethodManager(27755): Starting input: Bind resultString=SUCCESS_WITH_IME_SESSION
I/InputMethodManager(27755): showSoftInput, displayId=-1,callers=android.view.inputmethod.InputMethodManager.showSoftInput:1785 android.view.inputmethod.InputMethodManager.showSoftInput:1723 io.flutter.plugin.editing.TextInputPlugin.showTextInput:397 io.flutter.plugin.editing.TextInputPlugin$2.show:102 
D/InputMethodManager(27755): showSoftInput() view=io.flutter.embedding.android.FlutterView{91e6592 VFE...... .F...... 0,0-1176,2278 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/InputMethodManager(27755): showSoftInput, displayId=-1,callers=android.view.inputmethod.InputMethodManager.showSoftInput:1785 android.view.inputmethod.InputMethodManager.showSoftInput:1723 io.flutter.plugin.editing.TextInputPlugin.showTextInput:397 io.flutter.plugin.editing.TextInputPlugin$2.show:102 
D/InputMethodManager(27755): showSoftInput() view=io.flutter.embedding.android.FlutterView{91e6592 VFE...... .F...... 0,0-1176,2278 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/InsetsController(27755): ViewUI_insets applyAnimation types:8,show:false, this:android.view.InsetsController@33948de
I/InsetsController(27755): ViewUI_insets controlAnimation types: 8
D/InsetsController(27755): ViewUI_insets controlAnimation after canel existing types: 8
I/AssistStructure(27755): Flattened final assist data: 388 bytes, containing 1 windows, 3 views
I/DecorView(27755): updateColorViewInt type:1 size: 122 color:fffcfcfc appColor:fffcfcfc
D/SceneHelper(27755): notifyState ltpo1.0 push currentPackageName=com.azhon.todo_flutter ltpo10SceneState=3009 scene=IME
I/HwViewRootImpl(27755): Add sceneId 96 topId: 10
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1176,99], mVisible=true}
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2278][1176,2400], mVisible=true}
D/InsetsSourceConsumer(27755): ViewUI_insets setControl -> ITYPE_NAVIGATION_BAR on com.azhon.todo_flutter/com.azhon.todo_flutter.MainActivity
D/InsetsSourceConsumer(27755): ViewUI_insets setControl mType:1, requestedVisible:true, getLeash:Surface(name=Surface(name=7192840 NavigationBar0)/@0x2bfeeed - animation-leash of insets_animation)/@0xa5f195a, needAnimation:false, mIsAnimationPending:false, getRootViewTitle:com.azhon.todo_flutter/com.azhon.todo_flutter.MainActivity
I/InsetsAnimationCtrlImpl(27755): Ime in switching, skipping updateSurfacePosition.
D/SceneHelper(27755): notifyState ltpo1.0 push currentPackageName=com.azhon.todo_flutter ltpo10SceneState=3010 scene=IME
I/HwViewRootImpl(27755): remove sceneId 96 topId: 10
D/InsetsSourceConsumer(27755): ViewUI_insets setControl -> ITYPE_IME on com.azhon.todo_flutter/com.azhon.todo_flutter.MainActivity
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1176,99], mVisible=true}
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2278][1176,2400], mVisible=true}
D/InsetsSourceConsumer(27755): ViewUI_insets setControl -> ITYPE_IME on com.azhon.todo_flutter/com.azhon.todo_flutter.MainActivity
D/InsetsController(27755): ViewUI_insets show(ime(), fromIme=true)
I/InsetsController(27755): ViewUI_insets applyAnimation types:8,show:true, this:android.view.InsetsController@33948de
I/InsetsController(27755): ViewUI_insets controlAnimation types: 8
D/InsetsController(27755): ViewUI_insets controlAnimation after canel existing types: 8
I/DecorView(27755): updateColorViewInt type:1 size: 122 color:fffcfcfc appColor:fffcfcfc
D/SceneHelper(27755): notifyState ltpo1.0 push currentPackageName=com.azhon.todo_flutter ltpo10SceneState=3009 scene=IME
I/HwViewRootImpl(27755): Add sceneId 96 topId: 10
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1176,99], mVisible=true}
I/InsetsController(27755): ViewUI_insets updateState new source: InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2278][1176,2400], mVisible=true}
I/InsetsSourceConsumer(27755): ViewUI_insets mSourceControl is null notifyControlRevoked type: 1
I/InsetsAnimationCtrlImpl(27755): Ime in switching, skipping updateSurfacePosition.
D/SceneHelper(27755): notifyState ltpo1.0 push currentPackageName=com.azhon.todo_flutter ltpo10SceneState=3010 scene=IME
I/HwViewRootImpl(27755): remove sceneId 96 topId: 10

```

**Comment by huycozy** [comment] 2024-01-02 05:24
Hi @azhon 
This seems to be a device-specific issue since I can't reproduce it on my device `Realme 6, Android 11`. And I see there is a known issue https://github.com/flutter/flutter/issues/140580. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/140580. Please share your device information there (OS, model) and you can also react an upvote to the original comment will help to raise the issue. Thanks!

**Closed by huycozy** 2024-01-02 05:24 UTC
Labels: in triage
