### ISSUE TITLE
[video_player][Android] Looping network video downloads data repeatedly

### ISSUE THREAD

**Issue by juri180** [flutter/flutter#99417] opened 2022-03-02 16:45 UTC
I'm experiencing an issue with the video_player package on Android. I couldn't reproduce it on iOS. 

## Steps to Reproduce

1. Create a flutter app with the video_player package `2.2.19`.
2. Integrate the custom widget `LoopingVideo` of the code sample in the app.
3. Run the app on an Android device or emulator.
4. Navigate to the code sample widget and keep it visible on the screen.
5. Inspect the data consumption.

**Expected results:** The player downloads the video one time and loops over it. It's even possible to cut the network connection of the device once the video is fully downloaded and it repeats the video forever.

**Actual results:** The player downloads the video over and over again, probably once for every loop replay. If you cut the network connection of the device, the loop iterates a couple of times and then stops.

<details>
<summary>Code sample</summary>

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

class LoopingVideo extends StatefulWidget {
  final _LoopingVideoState _state;

  LoopingVideo({required String url}) : _state = _LoopingVideoState(url);

  @override
  _LoopingVideoState createState() => _state;
}

class _LoopingVideoState extends State<LoopingVideo> {
  VideoPlayerController? _controller;
  final String _url;

  _LoopingVideoState(this._url);

  @override
  void initState() {
    super.initState();
    final playerOptions = VideoPlayerOptions(mixWithOthers: true);

    _controller = VideoPlayerController.network(
      _url,
      videoPlayerOptions: playerOptions,
    );

    _controller?.initialize().then((_) {
      setState(() {
        _controller?.setVolume(0.0);
        _controller?.play();
        _controller?.setLooping(true);
      });
    });
  }

  @override
  void dispose() {
    _controller?.pause();
    _controller?.dispose();
    _controller = null;
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_controller?.value.isInitialized ?? false) {
      return AspectRatio(
        aspectRatio: _controller!.value.aspectRatio,
        child: VideoPlayer(_controller!),
      );
    } else {
      return Container();
    }
  }
}
```

</details>

<details>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.3.1 20E241 darwin-arm, locale de-DE)
    • Flutter version 2.8.1 at /Users/juria/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/juria/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0
```

</details>

**Comment by maheshmnj** [comment] 2022-03-03 06:53
Hi @juri180, Thanks for filing the issue. This issue looks the same as  https://github.com/flutter/flutter/issues/99417  where the video is redownloaded when seek To beginning or when video plays on loop. Could you please check and confirm if this is the same issue?

**Comment by juri180** [comment] 2022-03-03 09:23
Hi @maheshmnj, thanks for your response. I guess you've posted the wrong link? The link is this issue itself.

**Comment by maheshmnj** [comment] 2022-03-03 09:35
Oops! I am so sorry, Please take a look at this https://github.com/flutter/flutter/issues/98482

**Comment by juri180** [comment] 2022-03-03 10:37
Thanks! [#98482](https://github.com/flutter/flutter/issues/98482) is a very similar issue, if not the same. I didn't realize a delay, but I've used videos with very small sizes (~3 seconds, ~100KB). Those videos are used like GIFs in my use case. They loop infinitely which causes a lot of data consumption on Android.

I've also tested to use `seekTo(Duration.zero)` as soon as the video ends, but this caused the same issue. Only one difference: Using `seekTo` caused less data consumption than `setLooping(true)`.

In my example with the ~3 seconds/~100KB video, the data consumption was as follows:

- `setLooping(true)`: up to 10MB/minute
- `seekTo`: 2-3MB per minute.

No idea why there is a difference. Both looked identically on the UI.

**Comment by maheshmnj** [comment] 2022-03-03 13:41
Thanks for the update, 

> In my example with the ~3 seconds/~100KB video, the data consumption was as follows:

>setLooping(true): up to 10MB/minute
seekTo: 2-3MB per minute.


May I know how you are measuring the data consumption? Does this happen with any video source or a specific video?

**Comment by maheshmnj** [comment] 2022-03-04 06:33
> I could observe the "Usage" tab in the Firebase console to measure the data consumption.

Thanks for the update, I am not sure if that is the right measure to understand the data consumption, Could you please try the below code sample by adding the video source to firebase and see if you see the same behavior with this video too?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: VideoApp(),
    );
  }
}

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: Stack(
              alignment: Alignment.bottomCenter,
              children: <Widget>[
                _controller.value.isInitialized
                    ? VideoPlayer(_controller)
                    : const CircularProgressIndicator(),
                VideoProgressIndicator(_controller, allowScrubbing: true),
              ],
            ),
          ),
        ),
        floatingActionButton: Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            FloatingActionButton(
              onPressed: () {
                setState(() {
                  _controller.seekTo(Duration.zero);
                });
              },
              child: const Icon(
                Icons.replay,
              ),
            ),
            const SizedBox(
              width: 10,
            ),
            FloatingActionButton(
              onPressed: () {
                setState(() {
                  _controller.value.isPlaying
                      ? _controller.pause()
                      : _controller.play();
                });
              },
              child: Icon(
                _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
              ),
            ),
            const SizedBox(
              width: 10,
            ),
            FloatingActionButton(
              onPressed: () {
                if (_controller.value.position <
                    _controller.value.duration - (const Duration(seconds: 5))) {
                  setState(() {
                    _controller.seekTo(_controller.value.position +
                        const Duration(seconds: 5));
                  });
                }
              },
              child: Icon(
                Icons.skip_next,
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```
</details>

**Comment by juri180** [comment] 2022-03-04 13:45
First I tried your unchanged code sample on an Android device and observed, that when the video is almost done playing and I cut the network connection and press the replay button, the video doesn't start again. Thus, the video has to be downloaded on every replay, indeed. That's not the case on iOS. On iOS you can press replay without an available network connection.

Then, I uploaded the video to my Firebase Storage and set looping to `true`. I observed the "usage" tab in the Firebase console and the result is similar to my own videos I described earlier. While the video loops, it downloads ~10MB per minute.

**Comment by maheshmnj** [comment] 2022-03-07 06:13
Thanks for the update @juri180, This issue looks the same as this  https://github.com/flutter/flutter/issues/98482 as pointed out earlier. I am closing this issue as a duplicate of the linked issue.
In case you disagree feel free to write in the comments and we will reopen it.

**Closed by maheshmnj** 2022-03-07 06:13 UTC
Labels: in triage
