### ISSUE TITLE
Cannot find executable for <project>\android\gradlew.bat

### ISSUE THREAD

**Issue by Jatin-Goyal5** [flutter/flutter#53790] opened 2020-04-01 22:47 UTC
[flutter_01.log](https://github.com/flutter/flutter/files/4417998/flutter_01.log)

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -v

## exception

ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\win10\Documents\calculator_f\android\gradlew.bat.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:413:27)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:431:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:364:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:522:28)
<asynchronous suspension>
#7      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#17     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#27     AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720],
    locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    [32m•[39m Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Users\win10\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.6)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio1
    [32m•[39m Flutter plugin version 44.0.2
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[32m[✓][39m VS Code (version 1.43.2)
    [32m•[39m VS Code at C:\Users\win10\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.8.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

[32m•[39m No issues found!
```

**Comment by Jatin-Goyal5** [comment] 2020-04-03 16:47
Hey @VladyslavBondarenko were u able to solve the problem

**Comment by jmagman** [comment] 2020-04-07 19:02
Was https://github.com/flutter/flutter/pull/39145 (in v1.9.7) supposed to fix this?  See https://github.com/flutter/flutter/issues/39341.

**Comment by jmagman** [comment] 2020-04-07 19:02
\cc @blasten

**Comment by blasten** [comment] 2020-04-07 19:15
This one seems like a slightly different issue. @Jatin-Goyal5 if you run `flutter create -t app`, there should be a `android\gradle.bat` file. If that is the case, something running on your system might have deleted that file in your app.

**Comment by Jatin-Goyal5** [comment] 2020-04-07 19:19
Gradle. bat file is present but system is unable to read at time of run

**Comment by blasten** [comment] 2020-04-07 19:37
does `gradlew.bat` have exec permission? If not, try adding it. See this article for an example: https://www.online-tech-tips.com/computer-tips/set-file-folder-permissions-windows/

**Comment by Vellutia** [comment] 2020-04-08 13:10
> This one seems like a slightly different issue. @Jatin-Goyal5 if you run `flutter create -t app`, there should be a `android\gradle.bat` file. If that is the case, something running on your system might have deleted that file in your app.

First of all, I'm not sure if this `gradlew.bat` file exists in all my projects from the very beginning but this morning I don't know why, suddenly I can't do `flutter run` on all my projects with this output `Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for
...\android\gradlew.bat.".`. 

And on top of that, my normal `flutter create` command doesn't generate `gradlew.bat` file, is there something wrong with it?

As for my projects, after run `flutter create -t app` and copy the `gradlew.bat`, it works just fine.

**Comment by Jatin-Goyal5** [comment] 2020-04-08 13:25
How to copy gradle. bat

**Comment by Vellutia** [comment] 2020-04-08 13:31
I just run `flutter create -t app`, then go to `project-app\android`. There's `gradlew.bat` file, just copy it.

**Comment by Jatin-Goyal5** [comment] 2020-04-09 20:37
Now sdk manager is not found is showing

**Comment by jmagman** [comment] 2020-04-09 20:49
@Jatin-Goyal5 That's probably https://github.com/flutter/flutter/pull/54133.

**Comment by Jatin-Goyal5** [comment] 2020-04-11 10:25
Sdkmangager is automatically deleted again and again

**Comment by jmagman** [comment] 2020-04-13 17:28
> Sdkmangager is automatically deleted again and again

@Jatin-Goyal5 Can you explain what you mean?  The SDK manager isn't distributed by Flutter, it's Android Studio or however else you downloaded your Android SDK.  Flutter tooling just tries to figure out its path.
https://github.com/flutter/flutter/pull/54133 is in 1.18.0-dev.3.0, which is currently in [master, dev, and beta](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) channels.

But that looks unrelated to the original issue you filed.  I'm not sure why `gradlew.bat` was missing, you shouldn't need to generate a new project and copy it over.

**Comment by Jatin-Goyal5** [comment] 2020-04-13 17:36
The above issue is not solved so i tried to reinstall everything but wgen i run flutter doctor sdkmangager is automatically deleted and license are not acceptable

**Comment by jmagman** [comment] 2020-05-12 17:51
Can you explain what "sdkmangager is automatically deleted" means?

**Comment by Jatin-Goyal5** [comment] 2020-05-12 17:57
Now, it's fixed because of some virus this problem has occurred

**Comment by jmagman** [comment] 2020-05-12 18:30
Are you saying your antivirus app deletes `sdkmangager` from inside the Android SDK, and `gradlew.bat` from inside your Flutter app?

**Comment by Jatin-Goyal5** [comment] 2020-05-13 10:08
Maybe something like that after i format my laptop it's running fine

**Comment by jmagman** [comment] 2020-05-13 17:37
Okay we can use https://github.com/flutter/flutter/issues/56975 to track this issue.  Thanks!

**Comment by VladyslavBondarenko** [comment] 2020-05-25 08:01
> Okay we can use #56975 to track this issue. Thanks!

Then closing current one as duplicate. Feel free to reopen if the issue is needed

**Closed by VladyslavBondarenko** 2020-05-25 08:01 UTC
Labels: platform-android, platform-windows, severe: crash, t: gradle, tool

**Comment by SadSack963** [comment] 2020-06-21 13:02
> 
> 
> Are you saying your antivirus app deletes `sdkmangager` from inside the Android SDK, and `gradlew.bat` from inside your Flutter app?

I spent two days chasing this on another user's system. In his case it was definitely AVG that was deleting / hiding sdkmanager.bat. Uninstalling AVG has removed that issue. However, today, his gradlew.bat in the project/android folder is doing the same. Even when copying it in Windows Explorer it simply disappears. I'm still trying to track down what is casing that.

**Comment by Anag-coder** [comment] 2020-07-07 12:23
> > This one seems like a slightly different issue. @Jatin-Goyal5 if you run `flutter create -t app`, there should be a `android\gradle.bat` file. If that is the case, something running on your system might have deleted that file in your app.
> 
> First of all, I'm not sure if this `gradlew.bat` file exists in all my projects from the very beginning but this morning I don't know why, suddenly I can't do `flutter run` on all my projects with this output `Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for ...\android\gradlew.bat.".`.
> 
> And on top of that, my normal `flutter create` command doesn't generate `gradlew.bat` file, is there something wrong with it?
> 
> As for my projects, after run `flutter create -t app` and copy the `gradlew.bat`, it works just fine.
> 
> EDIT: As I wrote before, there is no `gradlew.bat` file in all my existing projects and when I run `flutter run` it returns `Exception: Gradle task assembledebug failed with exit code -1 flutter`, but after a single success `flutter run` (after I copied `gradlew.bat` to one of my projects), then suddenly all my projects are working fine even tho I haven't copied the `gradlew.bat` to the rest of the projects.

Pls give a exact solution

**Comment by kartikBhanderi** [comment] 2020-12-29 05:46
> Sdkmangager is automatically deleted again and again

Hey @Jatin-Goyal5 , I am facing same problems and trying to resolve since FOUR days ):
Please help me what should I do ??

In my case : 
         
> Gradlew.bat files are missing, and if I run old projects having that file then,
>          Exception: Gradle task assembledebug failed with exit code -1 flutter

I tried to accept all licenses but as in your case, sdkmanager.bat file is deleting again and again.

Please help me.
Thanks in advance.

**Comment by kartikBhanderi** [comment] 2020-12-29 05:51
> > Are you saying your antivirus app deletes `sdkmangager` from inside the Android SDK, and `gradlew.bat` from inside your Flutter app?
> 
> I spent two days chasing this on another user's system. In his case it was definitely AVG that was deleting / hiding sdkmanager.bat. Uninstalling AVG has removed that issue. However, today, his gradlew.bat in the project/android folder is doing the same. Even when copying it in Windows Explorer it simply disappears. I'm still trying to track down what is causing that.
> 
> It appears that Windows Defender may be the cause, and of course we can't turn that off in Home edition. So it's a case of reinstalling AVG and adding exceptions in Menu -> Settings -> General -> Exceptions for the relevant folders, typically:
> C:\Users\[username]\AppData\Local\Android\* and
> C:\Users\[username]\AndroidStudioProjects\*
> 
> Finally! That seems to have done the trick. I also got him to turn off Resident Shield just in case. We then copied known good versions of gradlew and gradlew.bat from "C:\Program Files\Android\Android Studio\plugins\android\lib\templates\gradle\wrapper" into the project\android folder, and I uploaded my sdkmanager.bat so that he could put it in C:\Users\[username]\AppData\Local\Android\Sdk\tools\bin. It all works now, and he built his first project!
> 
> HTH

Hey @SadSack963 , I am facing same problems and trying to resolve since FOUR days ):
Please help me what should I do ??

In my case : 
         
> Gradlew.bat files are missing, and if I run old projects having that file then,
>          Exception: Gradle task assembledebug failed with exit code -1 flutter

I tried to accept all licenses but as in your case, sdkmanager.bat file is deleting again and again.

Please help me.
Thanks in advance.

**Comment by SadSack963** [comment] 2020-12-29 10:16
Well, (and I'm not being facetious here) if you have the time and inclination you should consider Linux as a free alternative operating system for your programming needs. I'm not kidding - I have never seen a post from a Linux (or Mac) user saying that this or that file has suddenly been deleted. This is specifically a Windows problem simply because it is so insecure.

Anyway, my point is that files don't just disappear for no reason. If a file is being deleted, then **_something_** is deleting it. You need to find that **_something_** - and there are so many candidates on Windows that no-one can offer specific help for you.

I can only suggest that you begin by installing IOBit Uninstaller. Have a look through the list of programs installed, check out any suspicious programs in your search engine, and remove anything you don't like the sound of. Specifically, you are looking for some kind of antivirus - usually something a bit obscure. 

Such FREE(!) PUPs (potentially unwanted programs) are usually installed silently alongside some other quite legitimate program that you have downloaded from the internet. As an aside, I would recommend that if you do install something you download, then always use the Custom Install option, so that you can see if such things are packaged along with it.

If that still doesn't work, then open Task Manager (right click on the task bar) and search through the apps and background processes. Ignore Microsoft processes - you will not have a problem with those. Again, look up anything you don't recognise and that looks suspicious on the internet before deleting it. Also check if there are any specific procedures for removing the program, since some may have self-preservation locks which prevent you from removing them easily. If you right-click on the item and select Open file location, you could try renaming the offending file (or parent folder) if you're concerned about just deleting or uninstalling it.

I'm afraid there's not much more I can offer. Persevere and you will find the culprit. Good luck!

**Comment by Jatin-Goyal5** [comment] 2020-12-29 15:05
Try to install android sdk in local d or another directory

**Comment by kartikBhanderi** [comment] 2020-12-29 16:08
> Well, (and I'm not being facetious here) if you have the time and inclination you should consider Linux as a free alternative operating system for your programming needs. I'm not kidding - I have never seen a post from a Linux (or Mac) user saying that this or that file has suddenly been deleted. This is specifically a Windows problem simply because it is so insecure.
> 
> Anyway, my point is that files don't just disappear for no reason. If a file is being deleted, then **_something_** is deleting it. You need to find that **_something_** - and there are so many candidates on Windows that no-one can offer specific help for you.
> 
> I can only suggest that you begin by installing IOBit Uninstaller. Have a look through the list of programs installed, check out any suspicious programs in your search engine, and remove anything you don't like the sound of. Specifically, you are looking for some kind of antivirus - usually something a bit obscure.
> 
> Such FREE(!) PUPs (potentially unwanted programs) are usually installed silently alongside some other quite legitimate program that you have downloaded from the internet. As an aside, I would recommend that if you do install something you download, then always use the Custom Install option, so that you can see if such things are packaged along with it.
> 
> If that still doesn't work, then open Task Manager (right click on the task bar) and search through the apps and background processes. (Also check the Services tab.) Ignore Microsoft processes - you will not have a problem with those. Again, look up anything you don't recognise and that looks suspicious on the internet before deleting it. Also check if there are any specific procedures for removing the program, since some may have self-preservation locks which prevent you from removing them easily. If you right-click on the item and select Open file location, you could try renaming the offending file (or parent folder) if you're concerned about just deleting or uninstalling it.
> 
> I'm afraid there's not much more I can offer. Persevere and you will find the culprit. Good luck!

Thanks for your time buddy, I will try it :)

**Comment by kartikBhanderi** [comment] 2020-12-29 16:08
> Try to install android sdk in local d or another directory

I will try it :)
