### ISSUE TITLE
Flutter can't run for iOS but flutter build ios works fine

### ISSUE THREAD

**Issue by kasonde** [flutter/flutter#29834] opened 2019-03-23 08:31 UTC
## Steps to Reproduce

I have flutter installation. And I created a new app. There's nothing really special apart from the fact that I have shared_prefs, flutter_graphql, http, carousel_slider and flutter_html installed. 

## Logs

```
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.                                            1.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/richard/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.1/ios/Classes/PathProviderPlugin.m:5:
    /Users/richard/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.1/ios/Classes/PathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/richard/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.1+2/ios/Classes/SharedPreferencesPlugin.m:5:
    /Users/richard/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.1+2/ios/Classes/SharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone X.
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale en-ZM)
    • Flutter version 1.0.0 at /Users/Richard/flutter
    • Framework revision 5391447fae (4 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/richard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/richard/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone X • 5B95DD67-FC62-4390-B62A-7269B4015CFB • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by danydev** [comment] 2020-02-04 14:09
I was normally working with my project, it was just compiling normally, and suddenly after a trivial code change I had the same error. I tried each workaround I found googling:
- Upgrading Podfile template with the newest
- Upgrading \ Downgrading cocoapods
- Switching flutter to beta\stable channel, then upgrade, then clean & run
- Added Swift's specific [workaround](https://github.com/mravn-google/flutter/blob/e0c73220a6f69d341ce436244212277d83bc189b/packages/flutter_tools/templates/cocoapods/Podfile-swift#L71) on Podfile.
- Deintegrate pod , pod install, then clean and run
- Played with `Framework Search Path' and `Header Search Path`

Nothing really worked, until I just deleted the `ios\Flutter` folder and recreated the flutter project with a `flutter create .` (remember to specify java\objective-c if you are using them). Then magically the issue disappeared. I assume, somehow the Flutter framework (that is git ignored) has been corrupted.

Leaving here this solution since  it cost me at least couple hours :)

**Comment by jmagman** [comment] 2020-03-06 02:55
I believe @kasonde's issue was fixed by https://github.com/flutter/flutter/pull/42029.  I recommend you upgrade to latest Flutter if you haven't already--1.0.0 is pretty old at this point.

@danydev I'm not quite sure what you were seeing since you tried it on beta and I assume had updated your Podfile based on the error from https://github.com/flutter/flutter/pull/42029.  If you are still able to reproduce, please file a new issue and we'll take a look!

**Closed by jmagman** 2020-03-06 02:55 UTC
Labels: t: xcode, tool
