### ISSUE TITLE
[local_auth] add iOS UserFallback

### ISSUE THREAD

**Issue by furaiev** [flutter/flutter#59458] opened 2020-06-15 09:26 UTC
## Use case

When the 1st attempt of device unlocking is failed usually iOS users have an additional optional button (e.g. Enter Passcode).

![image](https://user-images.githubusercontent.com/33546696/84640729-c0f07180-af02-11ea-9d44-c3e265874f8e.png)

In the current version, the UserFallback button is hardcoded `context.localizedFallbackTitle = @"";`

## Proposal

- Extend the `IOSAuthMessages` with optional `localizedFallbackTitle`.
- Extend errors with new `LAErrorUserFallback`
- For iOS assign `context.localizedFallbackTitle` equal to `localizedFallbackTitle`

**Comment by TahaTesser** [comment] 2020-06-15 12:03
duplicate of https://github.com/flutter/flutter/issues/34638

**Closed by TahaTesser** 2020-06-15 12:03 UTC
