### ISSUE TITLE
salt-call command failed when sync with Salt master.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#142627] opened 2024-01-31 18:34 UTC
### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

Hi Yusuf,

Will you take a look of linux-20, I'm getting following errors when run command salt-call state.apply when sync with Salt master.
Thanks,
Kent

ID: /etc/pki/flutter-devicelab-linux-20.mtv.corp.google.com.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2423, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509.py", line 709, in certificate_managed
                  contents = __salt__["x509.create_certificate"](text=True, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 1451, in create_certificate
                  get_public_key(
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 720, in get_public_key
                  if isinstance(key, M2Crypto.X509.X509):
              AttributeError: module 'M2Crypto' has no attribute 'X509'
     Started: 10:26:49.923634
    Duration: 0.586 ms
     Changes:

----------
          ID: /opt/luci/machine_tokend/run.sh
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-linux-20.mtv.corp.google.com.crt
     Started: 10:26:50.303678
    Duration: 0.005 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh >/dev/null 2>&1
    Function: cron.present
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-linux-20.mtv.corp.google.com.crt
     Started: 10:26:50.304273
    Duration: 0.004 ms
     Changes:
----------
          ID: /opt/s/bot_code.py
    Function: cmd.script
      Result: False
     Comment: Command '/opt/s/bot_code.py' run
     Started: 10:26:50.813475
    Duration: 554.205 ms
     Changes:   
              ----------
              pid:
                  30915
              retcode:
                  1
              stderr:
                  Traceback (most recent call last):
                    File "/opt/s/__salt.tmp.gc7yvo_y.py", line 9, in <module>
                      with open(r'/var/lib/luci_machine_tokend/token.json', 'r') as fd:
                  FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/luci_machine_tokend/token.json'
              stdout:
----------
          ID: /etc/systemd/system/swarming-start-bot.service
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: luci/swarming./opt/s/bot_code.py
     Started: 10:26:51.368211
    Duration: 0.003 ms
     Changes:   
----------
          ID: swarming-start-bot
    Function: service.running
      Result: False
     Comment: One or more requisite failed: luci/swarming./opt/s/bot_code.py, luci/swarming./etc/systemd/system/swarming-start-bot.service
     Started: 10:26:51.368717
    Duration: 0.001 ms
     Changes:   

Summary for local
-------------
Succeeded: 33 (changed=4)
Failed:     6

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment] 2024-01-31 18:51
Salt scripts didn't copy some files are missing when install Ubuntu 20.04 directly.

Example: 
* No crontab
* Files are missing under folder /opt/s

**Comment by yusuf-goog** [comment] 2024-01-31 20:42
The failure is being caused by an issue with deprecated version of M2Crypto:

`x509.py:98: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.`

It looks like the minion version on linux-20 is:

```
$ salt-call --version
salt-call 3006.5 (Sulfur)
```

and on a different machine (linux-19) which is currently not experiencing the issue, the minion is at:

```
$ salt-call --version
salt-call 3006.1
```

**Comment by yusuf-goog** [comment] 2024-01-31 21:21
Changed the `cocoon/dev/provision_salt.sh` script which now installs minion version 3005.x. 

Opened issue to track updates to our code to move to the new X509 v2 modules: https://github.com/flutter/flutter/issues/142645

linux-20 is back up.

**Comment by yusuf-goog** [comment] 2024-01-31 22:29
closing this. there is another tracking issue to handle the deprecation/update needed.

**Comment by keyonghan** [comment] 2024-02-01 19:38
@yusuf-goog I guess you meant to close this bug. I am closing here.

**Closed by keyonghan** 2024-02-01 19:38 UTC
Labels: team-infra, infra: device lab
