### ISSUE TITLE
SocketException: Failed host lookup

### ISSUE THREAD

**Issue by coder-xb** [flutter/flutter#72498] opened 2020-12-17 07:57 UTC
## Error message:
```SocketException: Failed host lookup: 'xxx.com' (OS Error: nodename nor servname provided, or not known, errno = 8)```

## Steps to Reproduce

1. Run `flutter run` on macOs and run my application with IOS simulator or real-IPhone(IOS 14.2)
2. Quickly click to enter different pages in my application to request the API address on mine server
3. This problem will appear after repeating step 2 for a certain period of time

The Http request plugin I use is Dio (v3.0.10).
The development tool is Android Studio (v4.1.1) and Xcode(v12.3)

This is my `Flutter doctor` running results:
```dart
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.1, on macOS 11.1 20C69, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1) 
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

/// Note: After Android Studio 4.x, the results of my Flutter doctor running show that
/// the Flutter and Dart plugins are not installed. 
/// In fact, I have installed them and can develop my applications normally.
```
In addition, I have reported this issue to dio github, but because no more people reported the issue, my issue has been closed.

I am sure that my application has been configured in 
Android>app>main>src>AndroidManifesto.xml file: 
```<uses-permission android:name="android.permission.INTERNET" /> ```
and IOS >Runner>info.plist file: 
```
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key>
<true/>
</dict>
```
And the server configuration is normal!

**Comment by pedromassangocode** [comment] 2020-12-17 08:51
Hi @coder-xb 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/flutterchina/dio).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-17 08:51 UTC
