### ISSUE TITLE
2 second lagspikes onZebra/Symbol MC18 handheld device

### ISSUE THREAD

**Issue by mark-revision** [flutter/flutter#71315] opened 2020-11-27 14:31 UTC
Hi!

We're developing selfscanning applications for the retail market. On one of the devices our customers are using Zebra/Symbol MC18 our Flutter app is unresponsive and lagging like crazy. After investigating the issue, we come to the conclusion, that it's not an issue in our app. Our native apps do not suffer from this issue and are running without any hiccups.

Luckily we were able to easily reproduce this issue in the default counter-project and were able to spot a very strange pattern. Through flutter driver the button is clicked for 1000 times and after each tap the time it took was printed.  

Repo: https://github.com/mark-revision/flutter_MC18N0_issue
Start test: flutter drive --target=test_driver/app.dart

On all other devices the time between taps is between 220 - 320ms depending on the device during these 1000 taps.

On the MC18N0 we're seeing a different pattern
The **first 11 taps** are always slow and sluggish and every tap takes **2000 ms** or sometimes 4000 ms
Then **after 11 taps**, **every 10th tap** takes around **2000 ms** and the **taps in between 250-300 ms**
Then **after 200 taps**, **every** tap takes between 250-300 ms. This is after 2 minutes.

Resulting in the response graph below:
<img width="1124" alt="Screenshot" src="https://user-images.githubusercontent.com/75087802/100459093-23aa8380-30c5-11eb-862b-930f4065b06f.png">

The behaviour makes even the simple counter app unusable. On our own app, the lag spikes stay after 2 minutes. Googling around it seems to be a bug related to the PowerVR SGX 540 GPU that is used in this device.CPU is OMAP4430 ARM-v7A 32-bit.

Related tickets with similar PowerVR SGX 540 issues:
[31746](https://github.com/flutter/flutter/issues/31746)
[14036](https://github.com/flutter/flutter/issues/14036)
[11794](https://github.com/flutter/flutter/issues/11794)

Issue is present both in debug and in release builds.

Our customers have thousands of these devices that run native Android and Xamarin apps perfectly, so this bug seems to be related to Flutter. Maybe it's possible to workaround this problem? Any help is appreciated.

Best regards,

Mark

[edit]
When replacing the floating action button press with a gesture recognizer updating the state (to eliminate the Inkwell-animation), you'll see that the lag spikes are there too, the taps are registered, but the screen is not being updated when the state has changed.
[in this video](https://devapps.re-vision.nl:8443/mark/device-2021-03-04-171849_MC18.mp4)

**Comment by pedromassangocode** [comment] 2020-11-30 11:08
I don't have that specific device to I'm unable to reproduce this issue.

**Comment by mark-revision** [comment] 2020-11-30 13:02
Hi @pedromassango . Here's my flutter doctor -v. It's complaining about the Flutter and Dart plugin, but all projects build fine and is unrelated to the issue.

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-NL)
    • Flutter version 1.22.4 at /Library/Developer/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc3)
    • Android SDK at /Users/mark/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • MC18N0 (mobile)     • 16011523020722                           • android-arm   • Android 5.1.1 (API 22)
    • GM1913 (mobile)     • 10.0.0.147:8888                          • android-arm64 • Android 10 (API 29)
    • iPhone8 MT (mobile) • a12097c965bac46c4d3c2f512bbdd372d002723c • ios           • iOS 13.5.1

**Comment by mark-revision** [comment] 2020-11-30 13:03
Additionally, here's a list of devices that use the same GPU. Based on the other tickets, it seems to be GPU-related. 

Acer Iconia A1-830
--
Alcatel One Touch Idol X+
Asus Memo Pad HD7 16 GB
Asus ZenFone 4
Asus ZenFone 5
Asus ZenFone 6
BLU Life Pure
Blu Life Pure Mini
BLU Vivo 4.8 HD
BLUE Dash 4.5
Celkon S1
Faiphone 1
Gionee Elife E6
Gionee GPAD G3
Gionee GPAD G4
Huawei Ascend G610
Huawei Ascend G700
Intex Aqua HD
Intex Aqua Wonder Quad Core
Karbonn Titanium S7
Karbonn Titanium S9
Lava Iris Pro
Lava Iris Pro 20
Lava Iris Pro 30+
Lemon Aspire HD
Lenovo IdeaPhone A820
Lenovo K900
Lenovo P780
Lenovo S820
Lenovo S920
Lenovo S930
Lenovo Vibe X
Lenovo Y oga 10
Lenovo Yoga 8
Micromax A116 Canvas HD
Micromax Canvas Doodle 2 A240
Micromax Canvas HD A116i
Micromax Canvas Magnus A117
Micromax Canvas Tab P650
Micromax Canvas Turbo A250
Micromax Canvas XL2 A109
Oppo R819
Panasonic P51
Redmi 1
Samsun Galaxy Premier I9260
Samsung Galaxy S4
Sony Experia C
Spice Pinnacle FHD Mi-525
Xolo Q1000
XOLO Q1000s Plus
Xolo Q3000
Xolo Q700
Xolo Q800 X-Edition
Xolo Q8000
Xolo Q900T
XOLO Q900T
ZTE Geek
ZTE Grand X2 Ln

**Comment by mark-revision** [comment] 2020-12-04 11:44
Here are two video's showing the problem: first one is just the standard flutter counter demo where the lag spikes are visible when pressing the button and waiting for the counter to be updated. Second movie is the Flutter Drive test, where the spikes are visible in the beginning, then until 189th tap, the spikes of 2 seconds every 10th tap and from tap 190 and later, all seems normal again.

Manual test: https://mdcinternational-my.sharepoint.com/:v:/g/personal/m_toten_re-vision_nl/EeLoaQxhml9IlG5-TIchckwB2Q-w5YqpZswnBSVPkMRHkw?e=hwXfpR

Driver test: https://mdcinternational-my.sharepoint.com/:v:/g/personal/m_toten_re-vision_nl/EZdCdGgGN5JCoX49A7MrpucBq1FFcQhrCMKwGyrVE6kJ-A?e=kLSKx4

**Comment by mark-revision** [comment] 2020-12-21 11:45
We have received some additional feedback from the device-manufacturer (Zebra) regarding this issue, which confirms that this is a Flutter issue:

_We have checked touch event processing from Kernel side(GPU/CPU driver)  and found that touch response is quite fast at kernel level(Kernel space ) but it is getting delayed on user space ( processing touch event from kernel to framework(Flutter receiving and processing)). Below is  logs snippet . Hence as of now Flutter have to handle and make it fast.
 
[<6>[ 2248.704467]     <input1>: T[1] C[330] V[1]
<6>[ 2248.803771] omap-iommu omap-iommu.1: ipu: version 2.1
<6>[ 2248.858123]     <input1>: T[1] C[330] V[0]
<6>[ 2255.578186] omap-iommu omap-iommu.1: ipu: version 2.1 <6>[ 2270.856445] duty_cycle_apply_cooling: not throttling <4>[ 2284.553039] healthd: battery l=79 v=3993 t=28.0 h=2 st=3 c=-255 chg= <6>[ 2284.638610] omap-iommu omap-iommu.1: ipu: version 2.1 <6>[ 2299.936492] duty_cycle_apply_cooling: not throttling <4>[ 2300.423034] healthd: battery l=79 v=3993 t=27.0 h=2 st=3 c=-245 chg= <6>[ 2300.513488] omap-iommu omap-iommu.1: ipu: version 2.1 <6>[ 2315.596832] omap-iommu omap-iommu.1: ipu: version 2.1
<6>[ 2318.968688]     <input1>: T[1] C[330] V[1]
<6>[ 2319.216094]     <input1>: T[1] C[330] V[0]
<6>[ 2322.635131]     <input1>: T[1] C[330] V[1]
<6>[ 2322.852783]     <input1>: T[1] C[330] V[0]
<6>[ 2326.140441]     <input1>: T[1] C[330] V[1]
<6>[ 2326.375610]     <input1>: T[1] C[330] V[0]
<6>[ 2346.851135]     <input1>: T[1] C[330] V[1]
<6>[ 2347.061126] omap-iommu omap-iommu.1: ipu: version 2.1
<6>[ 2347.082519]     <input1>: T[1] C[330] V[0]
<6>[ 2349.946563]     <input1>: T[1] C[330] V[1]
<6>[ 2350.111083]     <input1>: T[1] C[330] V[0]
<6>[ 2354.796203]     <input1>: T[1] C[330] V[1]
<6>[ 2354.988037]     <input1>: T[1] C[330] V[0]
<6>[ 2375.601257] omap-iommu omap-iommu.1: ipu: version 2.1_

**Comment by mesb1** [comment] 2021-01-30 15:42
@mark-revision did you find some workaround for that problem?

**Comment by kf6gpe** [comment] 2021-02-01 22:48
@liyuqian If we want to work more on this, I could see about procuring one of the devices listed above with the same GPU. I don't think we presently have any.

**Comment by Tekneurt** [comment] 2021-02-01 23:30
@mesb1 unfortunately not. Have been trying precompiled shaders but to no effect.

@kf6gpe Let me know. I could try to arrange something with the manufacturer

**Comment by mark-revision** [comment] 2021-02-25 15:25
@kf6gpe @liyuqian If 

> @liyuqian If we want to work more on this, I could see about procuring one of the devices listed above with the same GPU. I don't think we presently have any.

I can send you a device if you want to work on this issue, pm me.

**Comment by kf6gpe** [comment] 2021-03-01 16:25
Thanks, @mark-revision! Following up by email. /cc @zanderso who may be able to help us identify who can help once we arrange getting the hardware, and @csells who may want to chat with you in general about your use cases.

I'll try to get some answers back for you by the end of the week.

**Comment by mark-revision** [comment] 2021-03-11 22:45
Hereby the traceAction-logs from the test.

First the logs from the Flutter Driver test from https://github.com/mark-revision/flutter_MC18N0_issue from the master branch. This test will click the counter-app’s button continuously, but apparently Flutter Driver will wait until the screen is refreshed before pressing the button again. This test will show all 250 presses and every time, the first 20 clicks take 2 seconds each and then until 200 clicks every 10th click takes 2 seconds. After 200 clicks the performance is no longer suffering from the issue.
Summary: https://devapps.re-vision.nl:8443/mark/71315/mc18_test_summary.timeline_summary.json 
Timeline: https://devapps.re-vision.nl:8443/mark/71315/mc18_test_timeline.timeline.json  

Second the logs from the Flutter Driver test from https://github.com/mark-revision/flutter_MC18N0_issue from the gesture branch where the FloatingActionButton was replaced with a GestureDetector. This test will click the counter-app’s button continiously and now Flutter Driver will not wait until the screen is refreshed before pressing the button again. Since in the previous test it takes about 200-300ms for the device to refresh the screen and the button presses 15-30ms, a lot of frames will be missed, which is ok. I have added this test as it might show additional details when the device is stressed.
Summary: https://devapps.re-vision.nl:8443/mark/71315/gesture_mc18_test_summary.timeline_summary.json 
Timeline: https://devapps.re-vision.nl:8443/mark/71315/gesture_mc18_test_summary.timeline_summary.json 
 
Additionally I have added a log from the Flutter DevTools CPU-profiling where I have pressed the button manually after the UI is updated. Here again, the first 20 clicks  have the 2 second lagspikes, then every 10th click suffers from the lagspike and after 200 clicks, all is fine again.
Log: https://devapps.re-vision.nl:8443/mark/71315/dart_devtools_2021_3_11-1615494852111000_Click_after_ui_update.json 

And the same test was exectuted manually, but instead of waiting for the UI to be updated, I pressed the button continuously around 3 times per second, which should be enough for the device to update the UI, but during the lagspikes, the counter-value is updated but the UI is not updated. Again after exactly 200 presses, performance is like it should be.
Log: https://devapps.re-vision.nl:8443/mark/71315/dart_devtools_2021_3_11-1615494508551000_fast_clicking.json

**Comment by jason-simmons** [comment] 2021-03-12 00:55
Typo fix: the link to the timeline for the gesture_mc18_test run is:
https://devapps.re-vision.nl:8443/mark/71315/gesture_mc18_test_timeline.timeline.json

That timeline shows calls to SkCanvas::Flush that are taking 2 seconds

**Comment by zanderso** [comment] 2021-03-12 17:46
@jason-simmons Is there enough information here to ask Skia folks for help, or will we need to get our hands on the device first to report a good issue to them?

**Comment by jason-simmons** [comment] 2021-03-12 18:22
We could try asking Skia if they know of any issues like this.  But I suspect that we will need the device in order to understand what is happening.

**Comment by jason-simmons** [comment] 2021-04-08 23:48
Looked at Flutter's performance on this device and found that the hangs during `SkCanvas::flush` occurred during calls to `glTexSubImage2D` using the `GL_RED` texture format.

Skia has landed a patch that disables use of that format on this device's GPU:
    https://skia-review.googlesource.com/c/skia/+/394159/

**Comment by mesb1** [comment] 2021-04-27 20:25
Do we have some kind of milestone for flutter to be updated with that skia fix?
I was unable to understand when it is expected.
Couple of days ago we have moved our app to 2.0.5, but issue still remains for that gpu type.

**Comment by zanderso** [comment] 2021-04-27 21:22
The fix rolled into the engine here https://github.com/flutter/engine/pull/25507 and flutter/flutter master here https://github.com/flutter/flutter/pull/80135 at https://github.com/flutter/flutter/commit/ff970cb18110ec57f62789b9bf0bc2994add07be. That change has made it to the dev branch, but it missed the cut for the beta. The next beta cut will be early next month.

**Comment by mark-revision** [comment] 2021-04-28 08:15
Like @zanderso  mentioned, the change is already merged to master. On Mac where the SDK is build based on your local repository, you can cherry pick that commit [ff970cb](https://github.com/flutter/flutter/commit/ff970cb18110ec57f62789b9bf0bc2994add07be) on the latest stable and build the SDK again and compile latest stable with this fix. This way you can run latest stable with this fix until it has reached beta and stable. We have been testing it extensively two weeks ago and did not come across any (other) issues, @mesb1

**Comment by MrBirb** [comment] 2021-07-06 11:41
@mark-revision So I assume this issue can be closed?

**Comment by zanderso** [comment] 2021-07-07 15:21
Yes this can be closed.

**Closed by zanderso** 2021-07-07 15:21 UTC
Labels: P4, e: device-specific, e: gpu driver bug, engine, passed first triage, perf: speed, platform-android, severe: performance

**Comment by behzodfaiziev** [comment] 2021-07-27 21:05
@mark-revision 
I found another bug because of this GPU (Samsung Galaxy S4) after update of flutter from 2.0.6 to 2.2.0. More details on #86794

If I am not wrong this  https://github.com/flutter/flutter/commit/ff970cb18110ec57f62789b9bf0bc2994add07be merge caused this issue, because the date when it was merged( 9 Apr 2021) and the update of 2.2.0 (stable) (18.05.2021) are very close dates.

**Comment by mesb1** [comment] 2021-07-28 07:43
@behzodfaiziev 
But isn't this fix was merged into dev branch with this date?
As far as i get it you can have it starting from 2.3.0 24 pre.

**Comment by behzodfaiziev** [comment] 2021-07-28 08:11
@mesb1  
It seems I was wrong.
