### ISSUE TITLE
Make GridView child's height wrap by its content

### ISSUE THREAD

**Issue by SixSheeppp** [flutter/flutter#29035] opened 2019-03-08 07:42 UTC
`return Container(
        height: 100,
        child: GridView.count(
          primary: false,
          crossAxisCount: defaultItemCount,
          mainAxisSpacing: 0,
          childAspectRatio: _childAspectRatio,
          physics: NeverScrollableScrollPhysics(),
          children: _createChildItemList(data.gridItem),
        ));`

Its the usual way to create a gridview.
 But what makes me confused is the child item's height of the gridview is not determined by the child height.Its measured by the childAspectRatio. Is there any way to make child's height wrap by its content?

**Comment by cirediew** [comment] 2019-05-07 12:04
I agree.

I solved this for now by doing the following in `Widget build(BuildContext context)`:
```
var maxWidth = 500.0;
var width = MediaQuery.of(context).size.width;
var columns = (width ~/ maxWidth) + 1;
var columnWidth = width / columns;
//136 is the height of one grid item
var aspectRatio = columnWidth / 136;

SliverGrid(
   gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
      maxCrossAxisExtent: maxWidth, childAspectRatio: aspectRatio),
   delegate: (...)
```

**Comment by Liuzhiyang94** [comment] 2019-05-08 04:04
> I agree.
> 
> I solved this for now by doing the following in `Widget build(BuildContext context)`:
> 
> ```
> var maxWidth = 500.0;
> var width = MediaQuery.of(context).size.width;
> var columns = (width ~/ maxWidth) + 1;
> var columnWidth = width / columns;
> //136 is the height of one grid item
> var aspectRatio = columnWidth / 136;
> 
> SliverGrid(
>    gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
>       maxCrossAxisExtent: maxWidth, childAspectRatio: aspectRatio),
>    delegate: (...)
> ```

Yes.I handle this just like u.

**Comment by kutear** [comment] 2021-03-23 03:41
> I agree.
> 
> I solved this for now by doing the following in `Widget build(BuildContext context)`:
> 
> ```
> var maxWidth = 500.0;
> var width = MediaQuery.of(context).size.width;
> var columns = (width ~/ maxWidth) + 1;
> var columnWidth = width / columns;
> //136 is the height of one grid item
> var aspectRatio = columnWidth / 136;
> 
> SliverGrid(
>    gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
>       maxCrossAxisExtent: maxWidth, childAspectRatio: aspectRatio),
>    delegate: (...)
> ```

but sometime we can't measure the height of grit item [cry]

**Comment by Pourqavam** [comment] 2021-11-29 16:19
Same issue.

**Comment by Piinks** [comment] 2022-07-11 20:38
Closing as a duplicate of https://github.com/flutter/flutter/issues/97544. Please follow progress in that issue.

**Closed by Piinks** 2022-07-11 20:38 UTC
Labels: new feature, framework, P5
