### ISSUE TITLE
The page suddenly flashed and couldn't stop, on iOS

### ISSUE THREAD

**Issue by willphonez** [flutter/flutter#103204] opened 2022-05-06 14:27 UTC
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3.1 21E258 darwin-x64, locale
    zh-Hans-CN)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)

https://user-images.githubusercontent.com/20037837/167152645-0d28f060-a7ec-4802-a08e-e1e69f0f75e3.mov

**Comment by danagbemava-nc** [comment] 2022-05-06 14:34
Hi @willphonez, this is a duplicate of https://github.com/flutter/flutter/issues/100522.

If you have any steps to reproduce, kindly provide them in the linked issue. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-05-06 14:34 UTC
Labels: in triage
