### ISSUE TITLE
When using devtools features, "Tried to paint a RenderObject reentrantly" is thrown since Flutter 3. May be linked to MaterialType.transparency

### ISSUE THREAD

**Issue by jeff-odopass** [flutter/flutter#106022] opened 2022-06-15 14:05 UTC
## Steps to Reproduce

1. Create a new app using Flutter latest version (reproductible on master, beta and stable channels)
2. Use the provided main.dart which demonstrate the problem
3. Run the app
4. Once app is fully loaded, open devtools. I personally open devtools on web from Android Studio, however the problem also happen with Visual Studio.
5. Click "Show Guidelines" from devtools, or "Show Baselines" etc.

**Expected results:**
No error is thrown.

**Actual results:**
The following error happen:
```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
Tried to paint a RenderObject reentrantly.

The following RenderObject was already being painted when it was painted again: RenderClipPath#e80ca NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, h=812.0)
...  size: Size(375.0, 812.0)
Since this typically indicates an infinite recursion, it is disallowed.
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/jean-francois/.../Apps/sample_app/lib/main.dart:12:12
When the exception was thrown, this was the stack: 
#0      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2612:9)
#1      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2625:6)
#2      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:240:13)
#3      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2715:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:240:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2715:7)
#8      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:156:11)
#9      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:99:5)
#10     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1117:31)
#11     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:515:19)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#17     _invoke (dart:ui/hooks.dart:148:13)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#19     _drawFrame (dart:ui/hooks.dart:115:31)
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#c6fee
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, h=812.0)
...  size: Size(375.0, 812.0)
RenderObject: RenderSemanticsAnnotations#c6fee
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, h=812.0)
  size: Size(375.0, 812.0)
...  child: RenderClipPath#e80ca NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=375.0, h=812.0)
...    size: Size(375.0, 812.0)
...    child: RenderCustomPaint#128cb NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=375.0, h=812.0)
...      size: Size(375.0, 812.0)
...      painter: null
...      foregroundPainter: _ShapeBorderPainter#afec2()
...      child: _RenderInkFeatures#3dc55 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=375.0, h=812.0)
...        size: Size(375.0, 812.0)
...        child: RenderPositionedBox#e06c7 NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=375.0, h=812.0)
...          size: Size(375.0, 812.0)
...          alignment: Alignment.center
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
====================================================================================================
```

<details>
<summary>Code sample</summary>
main.dart:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Sample App',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        // home: const MyHomePageWithError());
        // home: const MaterialWidgetWithoutError());
        home: const MaterialWidgetWithError());
  }
}

class MyHomePageWithError extends StatelessWidget {
  const MyHomePageWithError({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return NestedScrollView(
      floatHeaderSlivers: true,
      headerSliverBuilder: (BuildContext context, _) => [
        SliverAppBar(
          expandedHeight: 63,
          elevation: 0,
          flexibleSpace: FlexibleSpaceBar(
            background: Align(
              alignment: Alignment.topCenter,
              child: AppBar(
                title: const Text("Flexible space bar"),
              ),
            ),
            collapseMode: CollapseMode.pin,
          ),
        ),
      ],
      body: const Scaffold(
        body: Center(
          child: Text('Blablabla'),
        ),
      ),
    );
  }
}

class MaterialWidgetWithError extends StatelessWidget {
  const MaterialWidgetWithError({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Material(
      type: MaterialType.transparency,
      child: Center(child: Text("Blablabla", style: TextStyle(color: Colors.white))),
    );
  }
}

class MaterialWidgetWithoutError extends StatelessWidget {
  const MaterialWidgetWithoutError({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Material(
      child: Center(child: Text("Blablabla", style: TextStyle(color: Colors.black))),
    );
  }
}
```

I provided 3 widgets to test with, 2 having the described problem and 1 which just works fine.
The problem seems to related to `type: MaterialType.transparency,` however I'm not sure why and how to solve it.

</details>

<details>
  <summary>Logs</summary>

Run `flutter analyze` and attach any output of that command below:
```
╰─ flutter analyze
Analyzing sample_app...                                                 
No issues found! (ran in 2.7s)
```

Paste the output of running `flutter doctor -v`:

```
╰─ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.0.2 at /Users/jean-francois/Documents/workspace/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (7 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jean-francois/Library/Android/sdk
    • Platform android-32, build-tools 30.0.2
    • ANDROID_HOME = /Users/jean-francois/Library/Android/sdk
    • Java binary at: /Users/jean-francois/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/jean-francois/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/jean-francois/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Users/jean-francois/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • iPhone de Jean-François (mobile) • 00008030-0019711C3E28802E • ios            • iOS 15.5 19F77
    • macOS (desktop)                  • macos                     • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)                     • chrome                    • web-javascript • Google Chrome 102.0.5005.115
    ! Error: iPhone de Jean-François is busy: Fetching debug symbols for iPhone de Jean-François. Xcode will continue when iPhone de Jean-François is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
I don't know why Android Studio part is displayed twice now.

</details>

The error is quite critical because I cannot use devtools anymore, after the error has been triggered screen is weird and not repainted. Moreover, my company's app freeze when the error pop because it is a larger project.
I'm available to provide more feedback if needed asap.

**Comment by huycozy** [comment] 2022-06-16 04:58
Hi @jeff-odopass, thanks for filing the issue. 

This issue is reproducible on the latest `stable` and `master` channels. 
As far as I can see, the log is similar to #105969's log if you do click on `Show Guidelines` first then click on `Show Baselines` after that.

The issue is happening to both VSCode and Android Studio.

<details>
<summary>Demo</summary>

- Android Studio:

https://user-images.githubusercontent.com/104349824/173994130-a1477c4f-bb18-4aab-862e-e4c499f14296.mp4

- VSCode:

https://user-images.githubusercontent.com/104349824/173994137-6f5051dd-562c-4b3c-ba11-0d6f60ddbf9f.mp4



</details>

<details>
<summary>Logs</summary>

```bash
======== Exception caught by rendering library =====================================================
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/reproduce_issues/lib/devtools_106022.dart:12:12
When the exception was thrown, this was the stack: 
#0      RenderClipPath.debugPaintSize.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1854:38)
#1      RenderClipPath.debugPaintSize (package:flutter/src/rendering/proxy_box.dart:1858:6)
#2      RenderBox.debugPaint.<anonymous closure> (package:flutter/src/rendering/box.dart:2725:9)
#3      RenderBox.debugPaint (package:flutter/src/rendering/box.dart:2734:6)
#4      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2722:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2726:6)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:240:13)
#7      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2715:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:240:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2715:7)
#12     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:156:11)
#13     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:99:5)
#14     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1117:31)
#15     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:515:19)
#16     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#20     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#21     _invoke (dart:ui/hooks.dart:148:13)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#23     _drawFrame (dart:ui/hooks.dart:115:31)
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#286a7
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=600.9, h=958.5)
...  size: Size(600.9, 958.5)
RenderObject: RenderSemanticsAnnotations#286a7
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=600.9, h=958.5)
  size: Size(600.9, 958.5)
...  child: RenderClipPath#e07bc
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=600.9, h=958.5)
...    size: Size(600.9, 958.5)
...    child: RenderCustomPaint#9bdc3
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=600.9, h=958.5)
...      size: Size(600.9, 958.5)
...      painter: null
...      foregroundPainter: _ShapeBorderPainter#c8da8()
...      child: _RenderInkFeatures#03895
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=600.9, h=958.5)
...        size: Size(600.9, 958.5)
...        child: RenderPositionedBox#a0b1a
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=600.9, h=958.5)
...          size: Size(600.9, 958.5)
...          alignment: Alignment.center
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
Tried to paint a RenderObject reentrantly.

The following RenderObject was already being painted when it was painted again: RenderClipPath#e07bc NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=600.9, h=958.5)
...  size: Size(600.9, 958.5)
Since this typically indicates an infinite recursion, it is disallowed.
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/reproduce_issues/lib/devtools_106022.dart:12:12
When the exception was thrown, this was the stack: 
#0      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2612:9)
#1      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2625:6)
#2      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:240:13)
#3      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2715:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:240:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:146:15)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2715:7)
#8      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:156:11)
#9      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:99:5)
#10     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1117:31)
#11     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:515:19)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#17     _invoke (dart:ui/hooks.dart:148:13)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#19     _drawFrame (dart:ui/hooks.dart:115:31)
The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#286a7
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=600.9, h=958.5)
...  size: Size(600.9, 958.5)
RenderObject: RenderSemanticsAnnotations#286a7
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=600.9, h=958.5)
  size: Size(600.9, 958.5)
...  child: RenderClipPath#e07bc NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=600.9, h=958.5)
...    size: Size(600.9, 958.5)
...    child: RenderCustomPaint#9bdc3 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=600.9, h=958.5)
...      size: Size(600.9, 958.5)
...      painter: null
...      foregroundPainter: _ShapeBorderPainter#c8da8()
...      child: _RenderInkFeatures#03895 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=600.9, h=958.5)
...        size: Size(600.9, 958.5)
...        child: RenderPositionedBox#a0b1a NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=600.9, h=958.5)
...          size: Size(600.9, 958.5)
...          alignment: Alignment.center
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
====================================================================================================

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.2 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1265, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1265 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6671503789 (2 hours ago), 2022-06-15 18:36:08 -0700
    • Engine revision f8c0dc87bc
    • Dart version 2.18.0 (build 2.18.0-189.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

To prevent the issue from being fragmented, I will close this issue as a duplicate, and we should stay tuned in #105969 for further updates. And please drop comments in #105969 for anything you found.
If you disagree about this, please drop a comment and I will reopen it. Thanks!

**Closed by huycozy** 2022-06-16 04:58 UTC
Labels: in triage
