### ISSUE TITLE
[futter_tools] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#137163] opened 2023-10-24 17:16 UTC
Version: `stable/3.13.8`
Command: `debug_adapter`

```
StateError: Bad state: Future already completed
at _Completer.completeError(future_impl.dart:18)
at ThreadInfo.resolveUrisToPathsBatch.<anonymous closure>(isolate_manager.dart:1023)
at _LinkedHashMapMixin.forEach(compact_hash.dart:625)
at ThreadInfo.resolveUrisToPathsBatch(isolate_manager.dart:1023)
at <asynchronous gap>(async)
at ThreadInfo.resolveUrisToPackageLibPathsBatch(isolate_manager.dart:976)
at <asynchronous gap>(async)
at IsolateManager._sendLibraryDebuggables(isolate_manager.dart:812)
at <asynchronous gap>(async)
at Future.wait.<anonymous closure>(future.dart:525)
at <asynchronous gap>(async)
at IsolateManager._configureIsolate(isolate_manager.dart:392)
at <asynchronous gap>(async)
at IsolateManager.registerIsolate(isolate_manager.dart:221)
at <asynchronous gap>(async)
at DartDebugAdapter._configureExistingIsolates.<anonymous closure>(dart.dart:749)
at <asynchronous gap>(async)
at Future.wait.<anonymous closure>(future.dart:525)
at <asynchronous gap>(async)
at DartDebugAdapter._configureExistingIsolates(dart.dart:742)
at <asynchronous gap>(async)
at DartDebugAdapter._withErrorHandling(dart.dart:2424)
at <asynchronous gap>(async)
at DartDebugAdapter.connectDebugger(dart.dart:690)
at <asynchronous gap>(async)
at FlutterDebugAdapter._connectDebugger(flutter_adapter.dart:383)
at <asynchronous gap>(async)
at FlutterDebugAdapter._handleDebugPort(flutter_adapter.dart:464)
at <asynchronous gap>(async)
```

**Comment by stoppiNeobiz** [comment] 2023-12-11 19:58
any solution, i riceve the error:
Error: Bad state: Future already completed

**Comment by eliasyishak** [comment] 2023-12-11 20:07
Hi @stoppiNeobiz, are you able to provide some reproducible steps for us to replicate, that would help us find a solution if it has not already been fixed

**Comment by stoppiNeobiz** [comment] 2023-12-11 20:10
hi @eliasyishak  the complete errore is this, i work on web:
```
Error: Bad state: Future already completed
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
dart-sdk/lib/async/future_impl.dart 43:31                                    complete
packages/google_sign_in_web/google_sign_in_web.dart 170:5                    initWithParams
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7 
```

this is the code:
```
final GoogleSignIn _googleSignIn = GoogleSignIn(
        clientId: "xxxxxxxxxx.apps.googleusercontent.com",
        scopes: scopes,
      );
```

this code cause the error .

**Comment by stoppiNeobiz** [comment] 2023-12-11 21:34
hi @eliasyishak the problem compares when I use bloc, if I remove the bloc consumers then it doesn't give an error and everything works. This, however, is a problem

**Comment by stoppiNeobiz** [comment] 2023-12-11 22:02
hi @eliasyishak , i confirm that is bloc, this is my very simple app:
main:

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'bloc/login_cubit/login_cubit.dart';
import 'firebase_options.dart';
import 'home.dart';
import 'repositories/authentication_repository.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.web);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider<AuthenticationRepository>(
          create: (context) => AuthenticationRepository(
            firebaseAuth: FirebaseAuth.instance,
          ),
        ),
      ],
      child: MultiBlocProvider(
        providers: [
          BlocProvider<LoginCubit>(
            create: (context) => LoginCubit(
              authenticationRepository: context.read<AuthenticationRepository>(),
            ),
          ),
        ],
        child: MaterialApp(
          title: 'amdigitallife',
          theme: ThemeData(
            useMaterial3: true,
          ),
          home: HomePage(),
        ),
      ),
    );
  }
}

```

this is the home:
```

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';
import 'package:google_sign_in_web/google_sign_in_web.dart' as web1;
import 'bloc/login_cubit/login_cubit.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  void initState() {
    super.initState();
    _init();
  }

  _init() {
    const List<String> scopes = <String>[
      'email',
    ];
    final GoogleSignIn googleSignIn = GoogleSignIn(
      clientId: "472109982413-ivqi0bulgrqlkoaktrq6e2rjjc9ainm2.apps.googleusercontent.com",
      scopes: scopes,
    );
    googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount? account) async {
      if (kIsWeb && account != null) {
        final authentication = await account.authentication;
        final idToken = authentication.idToken;
        final credential = GoogleAuthProvider.credential(
          accessToken: "",
          idToken: idToken,
        );
        await FirebaseAuth.instance.signInWithCredential(credential);
      }
      googleSignIn.signInSilently();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          (GoogleSignInPlatform.instance as web1.GoogleSignInPlugin).renderButton(configuration: web1.GSIButtonConfiguration()),
          BlocConsumer<LoginCubit, LoginState>(
              listener: (context, state) {},
              builder: (context, state) {
                return Text("Test");
              })
        ],
      ),
    );
  }
}

```

The login cubit is simple cubit empty, if you try with blocConsumer in page, not work, if you delete the bloc works correctly.

**Comment by stoppiNeobiz** [comment] 2023-12-11 22:11
hi @eliasyishak sorry if I write to you again but I have reduced the problem further, the problem is this line:
authenticationRepository: context.read<AuthenticationRepository>() passed to the cubit. if i delete this line work correctly otherwise i riceve the error

**Comment by sina8013** [comment] 2023-12-18 18:12
Hey guys, I've solved it! This bug is from the latest versions of Flutter and Dart extensions for VS Code. Just downgrade their versions a few releases, and it should be fixed.

**Comment by christopherfujino** [comment] 2023-12-19 20:10
> Hey guys, I've solved it! This bug is from the latest versions of Flutter and Dart extensions for VS Code. Just downgrade their versions a few releases, and it should be fixed.

^ FYI @DanTup. This is one of the top crashers on stable/3.16.4

**Comment by DanTup** [comment] 2023-12-19 20:35
Thanks, I'll take a look.

> I'm assuming this downgrade opted them out of using DAP. This is one of the top crashers on stable/3.16.4

Yeah, if you go back a few versions you'll likely end up on the legacy DAPs. You could also force that by setting `"dart.previewSdkDaps": false` in settings instead of downgrading.

How often is this occurring? Are there specific actions that cause it? Before the last update ~50% of people were on the new debug adapters and in the latest release it became 100%, it's odd that it didn't come up before (although it's always possible the behaviour changed slightly in the latest Flutter release).

**Comment by christopherfujino** [comment] 2023-12-19 20:36
> it's odd that it didn't come up before (although it's always possible the behaviour changed slightly in the latest Flutter release).

Well this was filed back in October for 3.13

**Comment by DanTup** [comment] 2023-12-20 11:10
> Well this was filed back in October for 3.13

Ah sorry, missed that.

I think this issue could be the same as https://github.com/dart-lang/sdk/issues/52632, although I don't know if there are other ways to trigger it. If I create a Flutter app where a filename has a comma, then the debug session terminates and I get a `flutter_01.log` written that contains this:

```
StateError: Bad state: Future already completed

#0      _Completer.completeError (dart:async/future_impl.dart:19:31)
#1      ThreadInfo.resolveUrisToPathsBatch.<anonymous closure> (package:dds/src/dap/isolate_manager.dart:1136:58)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#3      ThreadInfo.resolveUrisToPathsBatch (package:dds/src/dap/isolate_manager.dart:1136:20)
<asynchronous suspension>
#4      ThreadInfo.resolveUrisToPackageLibPathsBatch (package:dds/src/dap/isolate_manager.dart:1089:21)
<asynchronous suspension>
#5      IsolateManager._sendLibraryDebuggables (package:dds/src/dap/isolate_manager.dart:913:5)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
```

I will fix the issue causing us to try to complete the completer twice (I have an idea what that is), however we might still be left with an error (although one with a better message) if the cause is that the VM is returning invalid responses to that request.

**Comment by DanTup** [comment] 2023-12-20 12:34
I've opened https://dart-review.googlesource.com/c/sdk/+/342800 which will improve the error message here to make it clearer what the issue is and adds a failing test for https://github.com/dart-lang/sdk/issues/52632.

However, I don't have a good way to work around the bug because when the response length doesn't match the request length, we can't tell which items are valid/invalid (and if we treat them all as invalid many things won't work correctly). We'll need the underlying issue to be resolved to properly address this.

For anyone hitting this bug - I would check whether any of your files may have commas in the filenames. If so, renaming the files to not include commas may avoid the issue until there's a fix for https://github.com/dart-lang/sdk/issues/52632. If you have a repro and believe you don't believe you do, please try:

- Run the **Dart: Capture Debugging Logs** command from the command palette before starting your application
- Start your application and trigger the issues
- Click **Cancel** on the logging notification to stop logging and open the log file
- Search for a line that contains `"method":"lookupResolvedPackageUris"` (probably near the end of the log just before the session terminated)
- Format that line as JSON and it will include a list of paths - one of which may contain a comma or other character that's triggering https://github.com/dart-lang/sdk/issues/52632

![image](https://github.com/flutter/flutter/assets/1078012/abaa641e-cb11-4651-adfd-23a9fff93f42)

**Comment by DanTup** [comment] 2023-12-20 13:16
It turns out, my change does actually improve things here. Without the fix, the exception is thrown synchronously because we tried to complete a completed future. However with my change, we're no longer throwing, we're just completing those futures with errors which is picked up by some other error handling.

It doesn't solve the whole problem (there are still errors), but in my testing with the fix on Flutter master, it's _not_ terminating the debugging session.

**Comment by christopherfujino** [comment] 2023-12-20 18:52
> It turns out, my change does actually improve things here. Without the fix, the exception is thrown synchronously because we tried to complete a completed future. However with my change, we're no longer throwing, we're just completing those futures with errors which is picked up by some other error handling.
> 
> It doesn't solve the whole problem (there are still errors), but in my testing with the fix on Flutter master, it's _not_ terminating the debugging session.

ahh, ok, so we *suspect* that the underlying error being hit is https://github.com/dart-lang/sdk/issues/52632, which is currently being investigated. And then [this](https://dart-review.googlesource.com/c/sdk/+/342800) DDS CL will prevent this error from crashing the tool but be handled by existing error handling code. Do I have that right?

**Comment by DanTup** [comment] 2023-12-21 10:17
> ahh, ok, so we suspect that the underlying error being hit is https://github.com/dart-lang/sdk/issues/52632, which is currently being investigated. And then [this](https://dart-review.googlesource.com/c/sdk/+/342800) DDS CL will prevent this error from crashing the tool but be handled by existing error handling code. Do I have that right?

Yes, that is correct - although this is based on the assumption that the trigger here is having commas in filenames (or something else that fails in the same way). Without repros from those hitting this I can't be certain there aren't other conditions (which may or may not behave differently).

I'm not certain there aren't other ways in which existing error handling wouldn't cover this, but in my testing (with the change) I could not produce any crashes and debugging worked. There remains a risk that some things won't work correctly until https://github.com/dart-lang/sdk/issues/52632 is resolved though.

Once that change lands, we should push an updated DDS and make sure it gets into Flutter (cc @bkonyi!)

**Closed** 2024-01-04 19:43 UTC
Labels: P2, team-tool, triaged-tool
