### ISSUE TITLE
[Add to App] shared_preferences Package doesn't work in the multiple_flutters_android in release mode.

### ISSUE THREAD

**Issue by yinanwang1** [flutter/flutter#95662] opened 2021-12-22 07:44 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. The sample of multiple_flutters_android in the add_to_app in the https://github.com/flutter/samples.
3. Added the shared_preferences in the dependencies in the pubspec.yaml file. 
4. Using the SharedPreferences class in the main.dart file. 
5. It works well in the debug model. 
6. I build a release version of the multiple_flutters_android app.
7. It doesn't appear the correct view when jump to DoubleFlutterActivity.

Expected results             |  Actual results
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/6257935/147052973-f1bc9c16-bfe9-432c-af96-3804d1c271b1.jpeg)  |  ![](https://user-images.githubusercontent.com/6257935/147053121-c146a348-ae88-4f9f-b0f2-e480a92be173.jpeg)

<details>
<summary>Code sample</summary>

```
// Copyright 2021 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart' as launcher;

void main() => runApp(const MyApp(color: Colors.blue));

@pragma('vm:entry-point')
void topMain() => runApp(const MyApp(color: Colors.green));

@pragma('vm:entry-point')
void bottomMain() => runApp(const MyApp(color: Colors.purple));

class MyApp extends StatelessWidget {
  const MyApp({Key? key, required this.color}) : super(key: key);

  final MaterialColor color;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: color,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int? _counter = 0;
  late MethodChannel _channel;

  @override
  void initState() {
    super.initState();

    initialCounter();

    _channel = const MethodChannel('multiple-flutters');
    _channel.setMethodCallHandler((call) async {
      if (call.method == "setCount") {
        // A notification that the host platform's data model has been updated.
        setState(() {
          _counter = call.arguments as int?;

          saveCounter(_counter);
        });
      } else {
        throw Exception('not implemented ${call.method}');
      }
    });
  }

  Future<void>  initialCounter() async {
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    _counter = sharedPreferences.getInt("counter") ?? 0;

    debugPrint("wyn 222 $_counter");
  }

  Future<void> saveCounter(int? counter) async {
    debugPrint("wyn 111 $counter");
    if (null != counter) {
      SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
      sharedPreferences.setInt("counter", counter);
    }
  }

  void _incrementCounter() {
    // Mutations to the data model are forwarded to the host platform.
    _channel.invokeMethod<void>("incrementCount", _counter);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            TextButton(
              onPressed: _incrementCounter,
              child: const Text('Add'),
            ),
            TextButton(
              onPressed: () {
                _channel.invokeMethod<void>("next", _counter);
              },
              child: const Text('Next'),
            ),
            ElevatedButton(
              onPressed: () async {
                // Use the url_launcher plugin to open the Flutter docs in
                // a browser.
                const url = 'https://flutter.dev/docs';
                if (await launcher.canLaunch(url)) {
                  launcher.launch(url);
                }
              },
              child: const Text('Open Flutter Docs'),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
2021-12-22 15:13:20.989 5551-5551/? D/ForceDarkHelper: updateByCheckExcludeList: pkg: dev.flutter.multipleflutters activity: dev.flutter.multipleflutters.DoubleFlutterActivity@8021c18
2021-12-22 15:13:20.994 5551-5711/? E/flutter: [ERROR:flutter/shell/common/shell.cc(94)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'topMain' declared.
    Receiver: top-level
    Tried calling: topMain, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:218)
2021-12-22 15:13:20.994 5551-5711/? E/flutter: [ERROR:flutter/runtime/dart_isolate.cc(718)] Could not resolve main entrypoint function.
2021-12-22 15:13:20.994 5551-5711/? E/flutter: [ERROR:flutter/runtime/dart_isolate.cc(202)] Could not run the run main Dart entrypoint.
2021-12-22 15:13:20.994 5551-5711/? E/flutter: [ERROR:flutter/runtime/runtime_controller.cc(384)] Could not create root isolate.
2021-12-22 15:13:20.994 5551-5711/? E/flutter: [ERROR:flutter/shell/common/shell.cc(574)] Could not launch engine with configuration.
2021-12-22 15:13:20.995 5551-5551/? D/ForceDarkHelper: updateByCheckExcludeList: pkg: dev.flutter.multipleflutters activity: dev.flutter.multipleflutters.DoubleFlutterActivity@8021c18
2021-12-22 15:13:21.000 5551-5711/? E/flutter: [ERROR:flutter/shell/common/shell.cc(94)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'bottomMain' declared.
    Receiver: top-level
    Tried calling: bottomMain, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:218)
2021-12-22 15:13:21.000 5551-5711/? E/flutter: [ERROR:flutter/runtime/dart_isolate.cc(718)] Could not resolve main entrypoint function.
2021-12-22 15:13:21.000 5551-5711/? E/flutter: [ERROR:flutter/runtime/dart_isolate.cc(202)] Could not run the run main Dart entrypoint.
2021-12-22 15:13:21.000 5551-5711/? E/flutter: [ERROR:flutter/runtime/runtime_controller.cc(384)] Could not create root isolate.
2021-12-22 15:13:21.000 5551-5711/? E/flutter: [ERROR:flutter/shell/common/shell.cc(574)] Could not launch engine with configuration.
```

```
Analyzing multiple_flutters_module...                                   
No issues found! (ran in 2.2s)
```

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale en-CN)
    • Flutter version 2.8.0 at /Users/arthurwang/Public/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (13 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/arthurwang/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/arthurwang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • MI 8 Lite (mobile) • 4e3ac1b2 • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

</details>

https://user-images.githubusercontent.com/6257935/147053891-10eab754-36ca-4ff6-967e-bba0384b4095.mp4

**Comment by maheshmnj** [comment] 2021-12-22 12:51
Hi @yinanwang1, Thanks for filing the issue. I ran your code sample but could not reproduce the issue. 
Can you please share your output of `flutter doctor -v`?

https://user-images.githubusercontent.com/31410839/147095458-54741601-4edf-4fe8-8b96-c0bc47a1a803.mov



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by yinanwang1** [comment] 2021-12-23 01:52
Thanks for your reply. 
Of Course, here is my flutter doctor -v.
<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale en-CN)
    • Flutter version 2.8.0 at /Users/arthurwang/Public/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/arthurwang/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/arthurwang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • MI 8 Lite (mobile) • 4e3ac1b2 • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 96.0.4664.55
</details>

********
PLEASE make sure two points:
1. Add the shared_preferences in the dependencies in the pubspec.yaml file.
2. Build a release version of the multiple_flutters_android app then install & run the APP. (It works in the beta version)

**Comment by maheshmnj** [comment] 2021-12-23 05:47
Thanks for the info @yinanwang1, I was able to reproduce the issue, This issue occurs only in release mode and works fine in debug mode. Also note that this looks like a regression, since it works fine on stable 2.5.3 in release mode


stable 2.8.1 ❌ | stable 2.5.3 ✅
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/147193047-a92c3827-6b34-422c-8f5d-7b11c3b2c407.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/147193916-57d41a7f-2dff-4a6f-b856-14bf1812a9e2.mov' width=180/>

✅ : No Issue ❌: Issue reproduced


I couldn't verify it on the master channel the build failed due to incompatible versions of kotlin and some dependency.


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (10 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.7:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by stuartmorgan** [comment] 2022-01-01 17:37
Duplicate of https://github.com/flutter/flutter/issues/91841

**Closed by stuartmorgan** 2022-01-01 17:37 UTC
Labels: severe: regression, platform-android, plugin, p: first party, a: existing-apps, p: shared_preferences, has reproducible steps, found in release: 2.8
