### ISSUE TITLE
I can't add the c++ file to flutter ios plugin

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#61284] opened 2020-07-11 07:04 UTC
![image](https://user-images.githubusercontent.com/7962840/87218659-4a228900-c387-11ea-8983-982c9a4f2f24.png)
<img width="680" alt="截屏2020-07-11 15 02 19" src="https://user-images.githubusercontent.com/7962840/87218689-8a820700-c387-11ea-8db6-31f15e3feb25.png">

when I pod install finish,  then run flutter run, it got a error: cant find #include <string>

**Comment by TahaTesser** [comment] 2020-07-13 10:53
Hi @qiuguian 
Please follow https://flutter.dev/docs/development/platform-integration/c-interop
Can you please provide your `flutter doctor -v`
Thank you

**Comment by qiuguian** [comment] 2020-07-15 02:36
@TahaTesser  Hello, you can try to run my plugin example on ios platform and you will get the problem;
plugin git:https://github.com/qiuguian/flutter_openctm.git

**Comment by qiuguian** [comment] 2020-07-15 02:44
@TahaTesser   plugin  use .podspec  s.source_files = 'OpenCtm/**/*'  to import source_files   the problem will get.    If drag it in by hand, it  run fine.

**Comment by TahaTesser** [comment] 2020-07-15 07:00
I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by qiuguian** [comment] 2020-07-15 07:16
@TahaTesser  What's version of your flutter? My version is Flutter 1.17.0 • channel stable

**Comment by qiuguian** [comment] 2020-07-15 07:17
@TahaTesser  <img width="612" alt="截屏2020-07-15 15 17 11" src="https://user-images.githubusercontent.com/7962840/87515354-4e63e480-c6ae-11ea-9429-e6b93be25e1a.png">

**Comment by Hixie** [comment] 2020-07-28 23:32
@qiuguian You will need to provide very clear steps to reproduce, along these lines:

1. Run `flutter create b61284`
2. Edit this file... and that file... like this... and like that...
3. Next step...

...and then explain what effect you're seeing and what you expect.

Otherwise we don't really know what you are running into.

**Comment by Hixie** [comment] 2020-08-25 23:04
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by Hixie** 2020-08-25 23:04 UTC
Labels: p: framework, platform-ios, waiting for customer response, will need additional triage
