### ISSUE TITLE
Build infra failure in Mac_android smoke_catalina_start_up

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#78461] opened 2021-03-17 20:42 UTC
Failure:
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20smoke_catalina_start_up/360/overview

This could be a recipe timeout similar to https://github.com/flutter/flutter/issues/78243 but I don't know how to confirm that. And the failure message doesn't say "Recipe timeout", so I'm creating a new issue for it, in case it's different.

**Comment by mdebbar** [comment] 2021-03-17 22:31
Same with this one: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20microbenchmarks_ios/232/overview

**Comment by godofredoc** [comment] 2021-03-18 22:19
Add duplicate bug and close

**Comment by godofredoc** [comment] 2021-07-29 19:51
Duplicate of https://github.com/flutter/flutter/issues/82972

**Closed by godofredoc** 2021-07-29 19:51 UTC
Labels: passed first triage, passed secondary triage, team: infra
