### ISSUE TITLE
Bot tried to merge WIP PR

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#65039] opened 2020-09-01 18:40 UTC
The github bot that auto-merges PRs appears to be considering those with the `work in progress` label.
It should only be considering those with the `waiting for tree to go green` label, not sure what happened.

Here is the PR where it was triggered by the WIP label, and actually removed the WIP label.
https://github.com/flutter/flutter/pull/64982

![Screen Shot 2020-09-01 at 11 33 28 AM](https://user-images.githubusercontent.com/16964204/91892476-9384ab80-ec47-11ea-82aa-925599af33fa.png)

This could accidentally merge PRs that aren't ready yet, for example if it's been approved, but not ready to land..

**Comment by christopherfujino** [comment] 2020-09-01 20:37
Another instance https://github.com/flutter/flutter/pull/62586#issuecomment-685054809

**Comment by Piinks** [comment] 2020-09-01 21:01
Here too: https://github.com/flutter/flutter/pull/64170#issuecomment-685054949

**Comment by keyonghan** [comment] 2020-09-02 00:00
Looked through the codes, but "waiting for tree to go green" is the only label Cocoon is considering. The graphql query works as expected to return PRs only with "waiting for tree to go green" labeled. The next step `remove label` uses exactly the same `labelID`. Do not see where 

@dnfield Do you have any input?

**Comment by dnfield** [comment] 2020-09-02 00:36
It would probably be good to try running the GraphQL queries that the bot is running and see if we're getting back unexpected results.

It looks like the query has changed sinc eI last worked on it. It could be a bug in our query, or it could be a bug in GitHub (maybe GitHub is returning the wrong labels sometimes?).

**Comment by keyonghan** [comment] 2020-09-02 16:45
> It would probably be good to try running the GraphQL queries that the bot is running and see if we're getting back unexpected results.

Confirmed GraphQL queries return correct results (all PRs with label `waiting for tree to go green`)

> It looks like the query has changed sinc eI last worked on it. It could be a bug in our query, or it could be a bug in GitHub (maybe GitHub is returning the wrong labels sometimes?).

I will add some logs to dig further. Thanks @dnfield

**Comment by christopherfujino** [comment] 2020-09-02 16:48
@keyonghan do we keep some record of webhooks in datastore? that would be valuable in diagnosing situations where either GitHub never sent us hooks we expected, or if we got malformed webhooks.

**Comment by keyonghan** [comment] 2020-09-02 16:57
Unfortunately, we don't seem to save any data about webhook.

**Comment by christopherfujino** [comment] 2020-09-02 17:03
> Unfortunately, we don't seem to save any data about webhook.

Ok, filed https://github.com/flutter/flutter/issues/65104 to track, if I ever get some free time I might try to implement.

**Comment by keyonghan** [comment] 2020-09-02 18:43
Walked through affected PRs, all seem to happen yesterday. Existing WIP PRs don't hit this issue. Additionally I created a test PR with WIP label, and still no issue.

This seems to be a one-time GitHub glitch, but I will keep monitoring (more logs added).

Since this is not a blocker, marking it as P3 for now.

**Comment by keyonghan** [comment] 2020-09-25 22:24
Bot removed `waiting for customer response` in https://github.com/flutter/engine/pull/19355#issuecomment-698995657.

**Comment by godofredoc** [comment] 2022-05-13 03:11
@keyonghan any updates on this bug?

**Comment by keyonghan** [comment] 2022-05-13 16:16
Closing as obsolete. Please reopen if you see the issue again.

**Closed by keyonghan** 2022-05-13 16:16 UTC
Labels: passed first triage, team: infra, passed secondary triage, P3
