### ISSUE TITLE
It happens unconditionally when using automatic rotation on Android devices.

### ISSUE THREAD

**Issue by kimriri** [flutter/flutter#104807] opened 2022-05-27 06:58 UTC
HI ! 
It happens unconditionally when using automatic rotation on Android devices.

E/flutter: [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
at io.flutter.plugin.platform.PlatformViewsController.u(SourceFile:13)
at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(SourceFile:2)
at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(SourceFile:3)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:335)
at android.os.Looper.loopOnce(Looper.java:186)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2022-05-27 13:55:22.846 21430-21430/? A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env).
Thank you!

**Comment by darshankawar** [comment] 2022-05-27 08:07
Please don't open multiple issues for same reason. Closing this as duplicate of https://github.com/flutter/flutter/issues/104797

**Closed by darshankawar** 2022-05-27 08:07 UTC
Labels: in triage
