### ISSUE TITLE
Webview with Hybrid Composition leave tab/webview open in memory, reopening webview Create new one

### ISSUE THREAD

**Issue by ycv005** [flutter/flutter#67863] opened 2020-10-11 12:23 UTC
Flutter version- 1.22.0
Fluter webview plugin- ([official webview plugin](https://pub.dev/packages/webview_flutter) && [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)) 
Android Version- 10
Device- Realme 3 Pro

## Problem Facing

- When I am opening a website (URL is mentioned in the code snippet) to view the video & after playing the video, later on if I exit webview and then reopen the webview to play the same video, video player of website shows as I am using two tabs to access the content but actually I have closed last webview and reopen new one but still earlier tab(which seems to closed) is sending/retrieving some kind of request or stay open in background/memory somewhere.

Here exit the webview mean, calling `Navigator.of(context).pop()`

## Video of Problem (To make you easily understand)-
 
1 - [Using Official Plugin](https://photos.app.goo.gl/FzcHGgoe7d4qAe9Y9)

2 - [Using flutter_inappwebview](https://photos.app.goo.gl/caYPKgq2bhcnM2eK6)

3 - [Using Android Chrome Browser](https://photos.app.goo.gl/GHvgS4b6653VjgSM7) (Watching this you could understand easily, that THE REASON IS accessing same video from 2 tab)

**So, Video player shows such Error when I am opening video in Chrome & accessing it from 2 Tabs whereas I am not opening new tabs in flutter app using any webview plugin.** Even, reloading is not working.

## Cross Checking with other plugin that uses Hybrid Composition

I am also facing same issue when using- [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview ) (download latest version from github's master branch) as it is also using Hybrid Composition.

THUS, PROBLEM SEEMS TO BE UNRELATED TO PLUGIN, & IT IS RELATED TO FLUTTER'S HYBRID COMPOSITION.

## Behavior with old version of plugin (official & flutter_inappwebview)

I am not facing the issue with OLDER VERSION of plugin([official webview plugin](https://pub.dev/packages/webview_flutter) && [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)) 

Dependencies
```
dependencies:
  flutter:
    sdk: flutter
  # uncomment below to get hybrid compositon version plugin

  # flutter_inappwebview:
  #     git:
  #       url: https://github.com/pichillilorenzo/flutter_inappwebview.git
  #       ref: master

  flutter_inappwebview: ^4.0.0+4
  webview_flutter: ^1.0.1
```

## Steps to produce

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:test_browser/offical_webview.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static const mainUrl =
      "https://www.hotstar.com/in/sports/cricket/indian-premier-league/sunrisers-hyderabad-vs-kings-xi-punjab-m701672/match-clips/highlights-srh-reign-over-kxip/1540002246";

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Test Browser',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: OpenWeb(),
    );
  }
}

class OpenWeb extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Testing HybridComp in Webview"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(
                builder: (context) => WebviewOfficial(), // InAppWebview(), // uncomment to use it
                ));
          },
          child: const Text("Open"),
        ),
      ),
    );
  }
}


class InAppWebview extends StatefulWidget {
  @override
  _InAppWebviewState createState() => _InAppWebviewState();
}

class _InAppWebviewState extends State<InAppWebview> {
  InAppWebViewController controller;
  String url = MyApp.mainUrl;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Test Browser"),
      ),
      body: Column(children: [
        Expanded(
          child: InAppWebView(
            initialUrl: url,
            onWebViewCreated: (InAppWebViewController webViewController) {
              controller = webViewController;
            },
            initialOptions: InAppWebViewGroupOptions(
              android: AndroidInAppWebViewOptions(
                disableDefaultErrorPage: true,
                useHybridComposition: true,
              ),
              crossPlatform: InAppWebViewOptions(
                mediaPlaybackRequiresUserGesture: false,
                horizontalScrollBarEnabled: false,
                verticalScrollBarEnabled: false,
              ),
            ),
            androidOnPermissionRequest: (InAppWebViewController controller,
                String origin, List<String> resources) async {
              return PermissionRequestResponse(
                  resources: resources,
                  action: PermissionRequestResponseAction.GRANT);
            },
          ),
        ),
        Container(
          color: Colors.white,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              MaterialButton(
                materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                padding: EdgeInsets.zero,
                child: Icon(Icons.refresh),
                onPressed: () {
                  if (controller != null) {
                    controller.reload();
                  }
                },
              ),
              MaterialButton(
                materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                padding: EdgeInsets.zero,
                child: Icon(Icons.share),
                onPressed: () async {},
              ),
              MaterialButton(
                materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                padding: EdgeInsets.zero,
                child: Icon(Icons.arrow_back),
                onPressed: () => null,
              ),
              MaterialButton(
                materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                padding: EdgeInsets.zero,
                child: Icon(Icons.arrow_forward),
                onPressed: () {
                  if (controller != null) {
                    controller.goForward();
                  }
                },
              ),
            ],
          ),
        ),
      ]),
    );
  }
}

```
```

import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:test_browser/main.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebviewOfficial extends StatefulWidget {
  @override
  _WebviewOfficialState createState() => _WebviewOfficialState();
}

class _WebviewOfficialState extends State<WebviewOfficial> {
  String url = MyApp.mainUrl;
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();
  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        top: true,
        child: WebView(
          initialUrl: url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment] 2020-10-12 15:30
I can reproduce the issue on physical Android 10 device

<details> 
<summary>complete code sample</summary> 

```dart
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static const mainUrl =
      "https://www.hotstar.com/in/sports/cricket/indian-premier-league/sunrisers-hyderabad-vs-kings-xi-punjab-m701672/match-clips/highlights-srh-reign-over-kxip/1540002246";

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Test Browser',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: OpenWeb(),
    );
  }
}

class OpenWeb extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Testing HybridComp in Webview"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(
              builder: (context) =>
                  WebviewOfficial(), // InAppWebview(), // uncomment to use it
            ));
          },
          child: const Text("Open"),
        ),
      ),
    );
  }
}

class WebviewOfficial extends StatefulWidget {
  @override
  _WebviewOfficialState createState() => _WebviewOfficialState();
}

class _WebviewOfficialState extends State<WebviewOfficial> {
  String url = MyApp.mainUrl;
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();
  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        top: true,
        child: WebView(
          initialUrl: url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0 at C:\Code\flutter_stable
    • Framework revision d408d302e2 (13 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.286, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-8.0.pre.286 at C:\Code\flutter_master
    • Framework revision 8211aaa2ae (6 hours ago), 2020-10-12 17:25:38 +0800
    • Engine revision 11d756a62e
    • Dart version 2.11.0 (build 2.11.0-207.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by chinmaygarde** [comment] 2020-10-12 17:49
We believe this may be a duplicate of https://github.com/flutter/flutter/issues/66764. I am marking this as a P4 with the AI that we convince ourselves that this is indeed a duplicate. The linked bug is handled at a higher priority.

**Comment by jason-simmons** [comment] 2020-10-14 19:18
Duplicate of https://github.com/flutter/flutter/issues/66764

**Closed by jason-simmons** 2020-10-14 19:18 UTC
Labels: P4, a: platform-views, engine, found in release: 1.22, found in release: 1.23, has reproducible steps, p: first party, p: webview, platform-android, plugin, severe: regression

**Comment by ycv005** [comment] 2020-10-16 07:10
Reopening as Hybrid Compositon is causing AlertDialog to disappear and reappears when touches the screen & after few time later app crash.

I am raising issue here, as it is flutter's issues instead of the plugin. Video - https://photos.app.goo.gl/UjMA5AYGsH2iXnJm7

Here is the link to issue- [Link](https://github.com/pichillilorenzo/flutter_inappwebview/issues/553#issuecomment-709814284).
