### ISSUE TITLE
[Impeller] Support handling texture while app is backgrounded.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#118195] opened 2023-01-09 19:06 UTC
While reading through the code for a design doc it looks like Impeller is not handling app states correctly which could lead to subtle rendering bugs when backgrounding and foregrounding the app on iOS

https://github.com/flutter/engine/blob/5df0072a0e63310abdd6ef3a187f54bbe15718c5/lib/ui/painting/multi_frame_codec.cc#L144

I'd expect there to be a branch of code that is executed when the gpu enabled switch is false.  Since the calls are using Metal, it's potentially safe to just ignore the sync switch and do the same calls in background or foreground.

**Comment by chinmaygarde** [comment] 2023-03-20 18:52
Closing this as duplicate of https://github.com/flutter/flutter/issues/123027. That other issue has an xref to the internal issue.

**Closed by chinmaygarde** 2023-03-20 18:52 UTC
Labels: engine, P4, impeller
