### ISSUE TITLE
Polygon & Circle onTap both not working

### ISSUE THREAD

**Issue by andywuwork** [flutter/flutter#62480] opened 2020-07-29 09:13 UTC
Hi,

I'm using google map, but when I onTap on Polygon or Circle, both are not working

thank you

**Comment by tony981** [comment] 2020-07-29 09:17
Idk

**Comment by pedromassangocode** [comment] 2020-07-29 11:05
Hi @andywuwork 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal [complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by andywuwork** [comment] 2020-07-30 01:37
[doctor-v.txt](https://github.com/flutter/flutter/files/4998280/doctor-v.txt)
[run--verbose.txt](https://github.com/flutter/flutter/files/4998281/run--verbose.txt)
[test-code.txt](https://github.com/flutter/flutter/files/4998282/test-code.txt)

thank you for your help

**Comment by pedromassangocode** [comment] 2020-07-30 08:42
Hi @andywuwork 
Looks like you have not enabled your Circle, Polygon to consume tap events.

```dart
        Circle(
            circleId: CircleId(circleIdVal),
            center: point,
            radius: radius,
            consumeTapEvents: true, // This need to be true, to allow this circle to be clickable.
            fillColor: Colors.redAccent.withOpacity(0.5),
            strokeWidth: 3,
            strokeColor: Colors.redAccent,
            onTap: () {
              print('Circle click');
            }
        )
```

Use the `consumeTapEvents` of your `Circle` and `Polygon` to enable them to handle the onTap event.

Closing this as invalid Flutter issue. If you disagree please write a comment bellow and I will reopen it.

**Closed by pedromassangocode** 2020-07-30 08:42 UTC
Labels: in triage

**Comment by andywuwork** [comment] 2020-07-31 06:13
Hi,
 It's working, thank you.
Could I ask why use flag to controll onTap event?

**Comment by pedromassangocode** [comment] 2020-07-31 08:28
Hi @andywuwork 
I have no idea, but I. know that this just follow the implementation of the original Android Google Maps API. You can follow the link below to read more about it.
https://developers.google.com/android/reference/com/google/android/gms/maps/model/Circle#setClickable(boolean)

**Comment by andywuwork** [comment] 2020-07-31 08:31
Hi, 
 thank you very much
