### ISSUE TITLE
Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch

### ISSUE THREAD

**Issue by theSonGoku1991** [flutter/flutter#114838] opened 2022-11-07 19:31 UTC
Hello guys,

I just re-started to work on my flutter project but am not able to run my project on the android studio emulator I use in VS Code.

Everytime I try to run the app, I get the following error message:

```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
lib\main.dart:1
Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:123)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1396)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:985)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3514)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3507)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:62)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch
	at java.base/com.sun.crypto.provider.ChaCha20Cipher$EngineAEADDec.doFinal(ChaCha20Cipher.java:1392)
	at java.base/com.sun.crypto.provider.ChaCha20Cipher.engineDoFinal(ChaCha20Cipher.java:726)
	at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
	at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
	at java.base/sun.security.ssl.SSLCipher$T12CC20P1305ReadCipherGenerator$CC20P1305ReadCipher.decrypt(SSLCipher.java:2204)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:260)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	... 17 more
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```
My flutter doctor looks like this:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.19044.2130], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.73.0)
[√] Connected device (2 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

I do not know why flutter does not find my VS Code even though it is installed and I am using it, but several posts I red said that is does not really matter.

Restarting VS Code / my pc did not help. Flutter clean and flutter pub get did not help.

distributionUrl is https\://services.gradle.org/distributions/gradle-6.7-all.zip

I am looking forward to your help!

Regards
Thomas

**Comment by huycozy** [comment] 2022-11-08 04:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/63193

**Closed by huycozy** 2022-11-08 04:02 UTC
Labels: in triage
