### ISSUE TITLE
Video_player plugin Android loop = false, the value of controller.value.postion can be played beyond the value of controller.value.duration will not automatically stop the playe

### ISSUE THREAD

**Issue by LebenNNA** [flutter/flutter#28833] opened 2019-03-04 12:38 UTC
## Steps to Reproduce

Video_player plugin Android loop = false, the value of controller.value.postion can be played beyond the value of controller.value.duration will not automatically stop the playe

## Codes

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    ChewieDemo(),
  );
}

class ChewieDemo extends StatefulWidget {
  ChewieDemo({this.title = 'Demo'});

  final String title;

  @override
  State<StatefulWidget> createState() {
    return _ChewieDemoState();
  }
}

class _ChewieDemoState extends State<ChewieDemo> {
  VideoPlayerController _videoPlayerController1;

  @override
  void initState() {
    super.initState();
    _videoPlayerController1 = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4');
    _videoPlayerController1.initialize();
  }

  @override
  void dispose() {
    _videoPlayerController1.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: widget.title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: VideoPlayer(_videoPlayerController1),
      ),
    );
  }
}
```

## Logs

```
bogon:example h3d-nna$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/h3d-nna/Documents/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/h3d-nna/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • dongxiaoiPhone • e90da41de945b9d8d5320facfb087b4027d0d7a2 • ios • iOS 10.3.3
    • iPhone 8 Plus  • 7F484401-C0C2-4A08-93D5-0F737E0758F2     • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-03-18 13:47
Duplicate of [#33187](https://github.com/flutter/flutter/issues/33187)

**Closed by TahaTesser** 2020-03-18 13:47 UTC
Labels: a: video, p: first party, p: video_player, plugin
