### ISSUE TITLE
image_picker

### ISSUE THREAD

**Issue by talalsammour01** [flutter/flutter#88527] opened 2021-08-19 13:12 UTC
I cannot read image from camera on iOS only
I need image to read data from it or upload it as multipart image or base64image but I cannot do that on iOS real device camera.
image from gallery on both android or iOS are working.
image form camera on android working fine.
But on iOS I cannot read any thing from it.
I checked from permissions and info.plist the problem is that I cannot make any process on the picked file.

**Comment by bernaferrari** [comment] 2021-08-21 01:55
Do you have a reproducible source code? And what is the `flutter doctor`?

**Comment by darshankawar** [comment] 2021-08-23 06:49
@talalsammour01 
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with `flutter doctor -v` to properly address this issue.
Thanks.

**Comment by talalsammour01** [comment] 2021-08-23 12:21
`class PhotoAnalysisViewModel extends ChangeNotifier {
  List<String> _data = [];
  bool isBusy = false;
  TextDetector textDetector = GoogleMlKit.vision.textDetector();

  List<String> get data => _data;

  Future processPickedFile(XFile pickedFile) async {
    _data = [];
    final inputImage = InputImage.fromFilePath(pickedFile.path);
    if (isBusy) return;
    isBusy = true;
    final recognisedText = await textDetector.processImage(inputImage);
    for (TextBlock block in recognisedText.blocks) _data.add(block.text);
    isBusy = false;
    notifyListeners();
  }
}

  _getImage(XFile? pickedFile) {
    if (pickedFile != null) {
      imageFile = File(pickedFile.path);
      photoAnalysisViewModel.processPickedFile(pickedFile);
    }
    widget.onImageUploaded(imageFile, photoAnalysisViewModel.data);
    setState(() {});
  }

  _imageFromCamera() async {
    setState(() => isLoading = true);
    XFile? pickedFile = await ImagePicker().pickImage(source: ImageSource.camera, imageQuality: 100, preferredCameraDevice: CameraDevice.rear);
    _getImage(pickedFile);
    setState(() => isLoading = false);
  }
`

**Comment by talalsammour01** [comment] 2021-08-23 12:41
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en)
    • Flutter version 2.2.3 at /Users/talalsammour/Developer/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/talalsammour/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (4 available)
    • SM A217F (mobile)                              • RZ8R227E54J
      • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile)                        • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPad Pro (12.9-inch) (5th generation) (mobile) •
      DC2909B1-117C-452C-A12A-A1DCDA59A0AA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

**Comment by darshankawar** [comment] 2021-08-24 05:49
@talalsammour01 
The code you shared here, https://github.com/flutter/flutter/issues/88527#issuecomment-903715534 seems to be 3rd party plugin code, so we can't use it directly. Please provide a complete minimal code sample without any 3rd party plugin code that we can directly copy paste and run to verify the issue.
Thanks.

**Comment by darshankawar** [comment] 2021-09-17 12:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-09-17 12:52 UTC
Labels: waiting for customer response, in triage
