### ISSUE TITLE
Bug in Flutter Gallery. Phone number in the Text Field page is hard coded to only the US.

### ISSUE THREAD

**Issue by gedw99** [flutter/flutter#16737] opened 2018-04-19 08:41 UTC
Choose Text Fields page from the side menu

But the phone number field has the +1 in the text field and you can't delete it.

**Comment by gedw99** [comment] 2018-04-19 08:43
Also the salary is US only.

Would be nice if the demo incorporated the i18n and i10n aspects.

I guess the Intl package is not fully baked yet ?

**Comment by HansMuller** [comment] 2018-04-19 15:31
Although the intl package is fully baked the Flutter gallery has not been localized, at least not yet.  However it really should be!

I've opened up an issue for this; will close your issue as a duplicate of that. Thanks for this report.

https://github.com/flutter/flutter/issues/16747

**Closed by HansMuller** 2018-04-19 15:31 UTC
