### ISSUE TITLE
Infinite loop in Mac text field

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#77855] opened 2021-03-10 23:12 UTC
1. Run an app on Mac with any sort of text field, such as the example code below.
2. Click to focus the input.
3. Quickly hammer down on some keys like "asdf".

The text will oscillate back and forth in the field and the following error will be logged over and over again in the console:

```
2021-03-10 15:06:45.620 sandbox[35149:395097] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
```

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}

```

Not sure if I or someone else broke this recently or if it's been around awhile.  CC @gspencergoog @dkwingsmt

**Comment by gspencergoog** [comment] 2021-03-11 20:08
@justinmc I'm unable to repro this. Can you give me some more info about what you're synced to, OS, etc. (Probably just `flutter doctor -v` would be good enough).

And how easy is it to repro for you?

**Comment by justinmc** [comment] 2021-03-11 20:40
It's 100% on the first try for me.  I'm on a MacBook running Big Sur at v11.2.1 and I just pulled master.

https://user-images.githubusercontent.com/389558/110851894-808e0c00-8266-11eb-969d-277606a73abe.mov

<details>

<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.212, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    • Flutter version 2.1.0-11.0.pre.212 at /Users/jmccandless/Projects/flutter
    • Framework revision c6dbb6f2b5 (74 minutes ago), 2021-03-11 11:25:02 -0800
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/jmccandless/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.5, Build version 12E5220o
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
➜  sandbox
```
</details>

**Comment by lukepighetti** [comment] 2021-03-17 17:02
Saw this yesterday on `dev` channel

**Comment by chunhtai** [comment] 2021-03-17 18:31
Hi @justinmc @lukepighetti 
I can't seem to reproduce the infinite loop in regular textfield in macos. I tried to type multiple character at once, and it works as expected. I am testing on master branch

I can reproduce the MaskedTextController one though

**Comment by chunhtai** [comment] 2021-03-17 18:35
https://user-images.githubusercontent.com/47866232/111519938-d3f3d480-8714-11eb-82ba-3c32291c75b2.mov

**Comment by lukepighetti** [comment] 2021-03-17 18:35
```
% flutter devices
4 connected devices:

SM S102DL (mobile)     • RF8N737S2CR                              • android-arm    • Android 10 (API 29)
Luke's iPhone (mobile) • 0bc0c4864d8e08aac4456893cded68bf0b6767d5 • ios            • iOS 14.4
macOS (desktop)        • macos                                    • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
Chrome (web)           • chrome                                   • web-javascript • Google Chrome 89.0.4389.90
```

**Comment by lukepighetti** [comment] 2021-03-17 18:38
You gotta really go for it. Smash them keys!

https://user-images.githubusercontent.com/666539/111520335-60f75780-872e-11eb-86c5-5904e29a1303.mov

**Comment by chunhtai** [comment] 2021-03-17 18:46
Talked to @justinmc offline, none of us can reproduce it on latest master. Not sure what may have fixed it. @lukepighetti Can you check if you are on the latest master?

**Comment by gspencergoog** [comment] 2021-03-17 18:50
@dkwingsmt recently landed engine changes for macOS key event handling (https://github.com/flutter/engine/pull/23469), so that may have fixed it.

**Comment by lukepighetti** [comment] 2021-03-17 18:59
```
% flutter doctor                           
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.1.0-13.0.pre.138, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (4 available)

• No issues found!
```



https://user-images.githubusercontent.com/666539/111523144-4ffc1580-8731-11eb-8968-68b08f43544c.mov

**Comment by chunhtai** [comment] 2021-03-17 19:02
I would like to close this issue as not reproducible. The commit is likely a breaking change for the flutter_masked_text, but is overlooked because our current breaking change policy only consider breaking change if it fails customer tests in https://github.com/flutter/tests

**Closed by chunhtai** 2021-03-17 19:02 UTC
Labels: P3, a: desktop, a: text input, platform-mac

**Comment by lukepighetti** [comment] 2021-03-17 20:46
That's fair, thanks!
