### ISSUE TITLE
Platform Exception

### ISSUE THREAD

**Issue by sandeepinigithub** [flutter/flutter#43514] opened 2019-10-25 18:00 UTC
I/flutter (15360): Error signing in: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)

**Comment by sandeepinigithub** [comment] 2019-10-25 18:04
![PlatformException](https://user-images.githubusercontent.com/46392691/67593498-e36d2900-f77f-11e9-841c-9114baed7405.JPG)

**Comment by BondarenkoStas** [comment] 2019-10-28 18:14
Duplicate of #36041

**Closed by BondarenkoStas** 2019-10-28 18:14 UTC
