### ISSUE TITLE
[Firebase messaging] iOS gets 2 times the payload of the message while Android gets it only once

### ISSUE THREAD

**Issue by ZatacaSystems** [flutter/flutter#30906] opened 2019-04-11 10:59 UTC
I have noticed that iOS is receiving twice the payload of the message while android is getting the payload only once. iOS shows 2 notifications while android only get's one.

**Comment by ZatacaSystems** [comment] 2019-04-11 13:32
I also have noticed that it happens in some devices, for me, 2 iphones (8 plus and 7) behave on differente ways. The 8 plus recive 2 notifications while the 7 only 1.

**Comment by escamoteur** [comment] 2019-10-01 13:20
If the problems still isn't solved, please ask at the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks!

**Comment by iapicca** [comment] 2019-11-07 14:42
Hi @ZatacaSystems 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-07 14:42 UTC
Labels: waiting for customer response
