### ISSUE TITLE
[Desktop] Handle mouse navigation buttons by default

### ISSUE THREAD

**Issue by ZhulanovAA** [flutter/flutter#131338] opened 2023-07-26 16:08 UTC
### Use case

Duplicate of #56919, but I can't reopen the original issue though I have more examples to back up that request.

Many mice have extra buttons on their side and in most desktop apps they are used as back/forward buttons by default. Original issue was closed as not a standard behavior which should be handled per app and not on the framework level as not much counterarguments were provided. I've decided to reopen it with much more examples to show that this behavior is the de facto standard on desktop. Examples include:

- Chromium based browsers
- Electron apps (Discord and Slack have been mentioned in the original issue)
- Non chromium browsers (Firefox)
- Standard Gnome apps (Nautilus, File Roller, Settings...)
- At least some other gtk apps (Pop!_shop, Komikku)
- At least some QT apps (Clementine)
- Android studio (in the settings) and so probably all the other IntelijIDEA based IDEs
- Steam
- Blender
- Microsoft seems to at least recognize it as the standard expected behavior, but requires some [code](https://learn.microsoft.com/en-us/windows/apps/design/basics/navigation-history-and-backwards-navigation#handle-mouse-navigation-buttons) to implement it. And I belive at least their file manager uses it by default as well.

I haven't managed to find a single app on my desktop not supporting this behavior (though to be fair, many desktop apps just don't have any back/forward functionality in the fisrt place), except my app I'm currently developing with flutter. But I remember rarely encountering an app without this behavior and every time it immediately felt non-native.

### Proposal

Mouse back and forward buttons should be handled by default in desktop apps to feel native.

**Comment by stuartmorgan** [comment] 2023-07-26 17:58
> Original issue was closed as not a standard behavior which should be handled per app and not on the framework level as not much counterarguments were provided.

I think you may have misunderstood [my comment](https://github.com/flutter/flutter/issues/56919#issuecomment-626901595); I wasn't saying that it's non-standard in the sense of being an uncommon behavior for apps to decide to implement, but that since those buttons do not have a *defined* (as opposed to just being relatively common) meaning, applications are the layer that needs to make the decision about what they should do.

> I've decided to reopen it with much more examples to show that this behavior is the de facto standard on desktop. Examples include:

More examples of apps choosing to implement a behavior doesn't change the above. It may well be a good argument for individual developers to choose to map to that behavior in their own apps, but they already can.

> * Microsoft seems to at least recognize it as the standard expected behavior, but requires some [code](https://learn.microsoft.com/en-us/windows/apps/design/basics/navigation-history-and-backwards-navigation#handle-mouse-navigation-buttons) to implement it.

The fact that Microsoft's UI framework shows how an application developer could handle it, rather than building it into the framework, is strong evidence in favor of the argument I provided when closing the original.

**Comment by stuartmorgan** [comment] 2023-07-26 18:00
(Labelling for desktop triage, but FWIW my recommendation would be to close this as a duplicate.)

**Comment by ZhulanovAA** [comment] 2023-07-26 19:41
> I wasn't saying that it's non-standard in the sense of being an uncommon behavior

Oh, I haven't thought of this comment meaning "it's uncommon behavior", but rather as "it doesn't seem to be common enough to be qulified as a standard", so I provided more and wider examples of desktop apps following it. 

> those buttons do not have a defined (as opposed to just being relatively common) meaning

ctrl + c  also doesn't technically have a defined meaning in a sense that OS doesn't send some sort of `copyShortcutPressed` signal. Yet it's still hardcoded in flutter as something expected from a desktop app.

Most desktop apps that users interact with (browser and file manager are already enough, I would say) have this behavior, while I'm also not aware of any other usages of these buttons in any application, maybe except for games (though now when I'm thinking about it, even Dota 2 for example aslo handles these buttons the same way in the menus, while still allowing to use them for other things in the gameplay).

In the end, I still think it's common enough behavior to have it out of the box instead of rely on each developer for each app to be aware of this behavior expected by many users, to not forget about it (especially if they are testing primary web version, which has this behavior by default through the browser) and then figuring out how to implement it properly. And of course I'm still open to hear the possible flaws and pitfalls of having it by default.

**Comment by gspencergoog** [comment] 2023-07-27 18:43
Closing this as a duplicate of #56919

**Closed by gspencergoog** 2023-07-27 18:43 UTC
Labels: c: new feature, framework, a: desktop, team-desktop
