### ISSUE TITLE
Overlay entry is hiding appbar

### ISSUE THREAD

**Issue by divyeshDev** [flutter/flutter#102641] opened 2022-04-27 12:04 UTC
I have faced this problem. Appbar is hiding when I was scrolling Overlay entry.

![Screenshot 2022-04-27 at 5 29 58 PM](https://user-images.githubusercontent.com/104503242/165513737-df8a87c6-eb4f-4a5b-ad5a-8f2757630123.png)

sample code :- 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(brightness: Brightness.light),
      home: Scaffold(
        appBar: AppBar(title: const Text('test')),
        body: SingleChildScrollView(
          child: OverlayButton(),
        ),
      ),
    );
  }
}

class OverlayButton extends StatefulWidget {
  @override
  _OverlayButtonState createState() => _OverlayButtonState();
}

class _OverlayButtonState extends State<OverlayButton> {
  late OverlayEntry _overlayEntry;
  final LayerLink _layerLink = LayerLink();
  bool _overlayIsShown = false;

  @override
  void dispose() {
    super.dispose();
    if (_overlayIsShown) {
      _hideOverlay();
    }
  }

  void _showOverlay() {
    if (_overlayIsShown) return;
    _overlayEntry = _createOverlayEntry();
    Overlay.of(context)!.insert(_overlayEntry);
    _overlayIsShown = true;
  }

  void _hideOverlay() {
    _overlayIsShown = false;
    _overlayEntry.remove();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        CompositedTransformTarget(
          link: _layerLink,
          child: RaisedButton(
              child: const Text('Open Overlay'), onPressed: _showOverlay),
        ),
        CompositedTransformTarget(
          link: _layerLink,
          child: RaisedButton(
              child: const Text('Open Overlay'), onPressed: _showOverlay),
        ),
      ],
    );
  }

  OverlayEntry _createOverlayEntry() {
    RenderBox renderBox = context.findRenderObject() as RenderBox;
    var anchorSize = renderBox.size;
    return OverlayEntry(builder: (context) {
      // TODO: dynamically use the correct child width / height for
      var childWidth = 200.0;
      var childHeight = 40.0;
      var childOffset =
          Offset(-(childWidth - anchorSize.width) / 2, -(childHeight));
      return Row(
        children: <Widget>[
          CompositedTransformFollower(
            link: _layerLink,
            offset: childOffset,
            child: RaisedButton(
              child: const Text('close'),
              onPressed: _hideOverlay,
            ),
          ),
        ],
      );
    });
  }
}

```

**Comment by maheshmnj** [comment] 2022-04-27 13:07
Hi @divyeshDev, OverlayEntry is basically a widget in a stack layout so it is expected that the overlay hides the AppBar, You could use Positioned widget inside the overlay to offset the widget in OverlayEntry.
Closing as this is working as intended. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-04-27 13:07 UTC
Labels: in triage

**Comment by maheshmnj** [comment] 2022-11-29 03:41
Duplicate of  https://github.com/flutter/flutter/issues/90101
