### ISSUE TITLE
Image heroes up over the shadow and fab, shadow and fab "pop" into place (in public Flutter app)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#8659] opened 2017-03-08 22:11 UTC
Took a movie here: https://youtu.be/5sjrjRTFLRs

From this public app: https://play.google.com/store/apps/details?id=com.starheightmedia.intallinn

Notice the top shadow, and the middle FAB, _pop_ into place after the image completes its hero. This is a noticeable visual effect.

Ideally, the image heroes under the shadow and FAB, so they don't pop back to the front.

**Comment by eseidelGoogle** [comment] 2017-03-08 22:54
This may be https://github.com/flutter/flutter/issues/5231 ?

**Comment by eseidelGoogle** [comment] 2017-03-08 22:54
Source: https://github.com/ilikerobots/intallinn_flutter

**Comment by Hixie** [comment] 2017-03-08 23:02
Unrelated to #5231 but there's definitely another bug which covers this already.

Fundamentally the problem is that we do heroes by lifting them to the Overlay as their own layer, so they go over the shadow and FAB and so forth. I'm not sure what the right fix is. They clearly need to go over their original route, since that one is going to be covered up...

**Comment by eseidelGoogle** [comment] 2017-04-11 22:35
@Hixie suggests this is a difficult fix which we will not have time for in the M2 timeframe.  Punting to M4.

**Comment by sethladd** [comment] 2017-04-19 16:25
The currently deployed Gallery does not have this issue in Pesto. Pesto's recipe transition, with the FAB moving up, does the right thing in the currently published Gallery.

So either:

A) something regressed in the framework (?)

B) the public app did something different than Pesto here


Before we close this, I'm curious if we regressed something.

**Comment by Hixie** [comment] 2017-04-19 18:05
We stopped making the toolbar into a hero when we landed the scrolling refactor, which would have changed our behaviour here.

**Comment by zoechi** [comment] 2018-11-28 14:19
I assume this is stale.

**Closed by zoechi** 2018-11-28 14:19 UTC
Labels: a: fidelity, customer: public-app, f: material design, framework
