### ISSUE TITLE
Image sorting not correct

### ISSUE THREAD

**Issue by ting28418** [flutter/flutter#121865] opened 2023-03-03 09:10 UTC
Pick images  a.png , b.png ,c.png 

And then selected image show at android real device >>>>   a.png, c.png, b.png

https://user-images.githubusercontent.com/110028664/222679472-cf3887f5-ba07-4ff3-b716-7e5e69dbb7fe.mp4

image_picker: [0.8.6+4]([url](url))
flutter version 3.7.1

**Comment by stuartmorgan** [comment] 2023-03-03 11:48
Duplicate of https://github.com/flutter/flutter/issues/117192

**Closed by stuartmorgan** 2023-03-03 11:48 UTC
