### ISSUE TITLE
debug_full_compile_millis regressed about 10% across the board (dart2)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19432] opened 2018-07-16 22:50 UTC
Starting with this engine roll: https://github.com/flutter/flutter/pull/19322

**Comment by devoncarew** [comment] 2018-07-16 22:58
It looks like this uses the `package:analyzer` API directly. The fix for this will be independent of the fix for https://github.com/flutter/flutter/issues/19431.

**Comment by aam** [comment] 2018-07-17 00:30
There is https://github.com/flutter/flutter/issues/12745 that tracks the work of removing dependency on analyzer altogether.

**Comment by aam** [comment] 2018-07-17 06:36
Actually I don't think analyzer is invoked in build step and compile metric.
Regression might be coming from pub that is invoked as part of gradle build.

**Comment by aam** [comment] 2018-07-17 16:24
With dart2 becoming default for dart sdk(and `pub`)  `pub ` launch on z840 linux workstation regresses from 0.10s to 0.20s:

before enabling dart2 to be default(https://github.com/dart-lang/sdk/commit/cdd2553a128e1fcaea2176fe411051ac260469b7)
```
╭─aam@aams.mtv.corp.google.com ~/p/d/dart-sdk/sdk  ‹cdd2553a12*› 
╰─➤  time out/ReleaseX64/dart-sdk/bin/pub | grep total               1 ↵
out/ReleaseX64/dart-sdk/bin/pub  0.10s user 0.03s system 141% cpu 0.090 total
grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} total  0.00s user 0.00s system 0% cpu 0.086 total
```

after(https://github.com/dart-lang/sdk/commit/bc7220a4fd72b6c348f8a1c605b3af4a22daf669 )
```
╭─ ~/p/d/dart-sdk/sdk  ‹bc7220a4fd*› 
╰─➤  time out/ReleaseX64/dart-sdk/bin/pub | grep total                    1 ↵
out/ReleaseX64/dart-sdk/bin/pub  0.20s user 0.10s system 151% cpu 0.196 total
grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} total  0.00s user 0.00s system 0% cpu 0.185 total
```

cc @a-siva

**Comment by aam** [comment] 2018-07-17 21:52
At this point hypothesis is that the culprit for this is frontend compiler now running in dart2 mode, same as for https://github.com/flutter/flutter/issues/19437#issuecomment-405684252

**Comment by Hixie** [comment] 2018-07-17 22:33
Update: This is caused by the Dart 2 VM being slower than the Dart 1 VM. This is considered a P0 bug by the Dart team.

**Comment by keertip** [comment] 2018-09-19 23:14
@mraleph, this looks like a slowdown that should have benefited from your changes to speed up the dart tools?

**Comment by mraleph** [comment] 2018-09-19 23:40
I think it has benefitted but it is still not on par. (also recently we had to disable one of the optimizations we implemented temporarily)

**Comment by cbracken** [comment] 2019-02-04 18:56
Closing as the compile performance improved substantially late last year, and I don't believe there's any specific action items remaining here.

**Closed by cbracken** 2019-02-04 18:56 UTC
Labels: dependency: dart, engine, severe: performance, severe: regression
