### ISSUE TITLE
[google_sign_in] web implemented uses deprecated APIs

### ISSUE THREAD

**Issue by jeff9315** [flutter/flutter#118948] opened 2023-01-21 13:47 UTC
This still seems to be an issue with google_sign_in https://github.com/flutter/flutter/issues/101004. Is there an ETA on it or should I be using a different solution?

Hello Google Developer,

You are receiving this message as a reminder that one or more of your web applications uses the legacy Google Sign-In web solution. Our announced plan stated that support for the Google Sign-In JavaScript platform library will be deprecated after March 31, 2023.

After March 31, 2023, migration to the new Google Identity Services is recommended to sign in customers using their Google Account to your platform. The SDK will use the new Sign in with Google client library.

**Comment by stuartmorgan** [comment] 2023-01-21 15:36
Closing as a duplicate of https://github.com/flutter/flutter/issues/88084

**Closed by stuartmorgan** 2023-01-21 15:36 UTC
