### ISSUE TITLE
In Container and Canvas documentation, explain why adjacent color blocks that aren't aligned on physical pixel boundaries show a seam

### ISSUE THREAD

**Issue by afedorychak** [flutter/flutter#17084] opened 2018-04-29 04:47 UTC
When I run this on Pixel 2:

```dart
    return Scaffold(
      body: Column(
        children: <Widget>[
          Container(height: 100.0, color: Colors.indigo),
          Container(height: 100.0, color: Colors.indigo),
        ],
      ),
    );
```

I get the background color bleeding through the line where two boxes touch each other. 
![not-pixel-perfect](https://user-images.githubusercontent.com/2334887/39403292-30528e2a-4b35-11e8-8d06-66570610fb27.png )

If I make the height of the top box a multiple of 8 then no gap is visible. 

Another example:
```dart
Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Container(width: 1.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 2.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 3.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 4.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 5.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 6.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 7.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 8.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 9.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 10.0, height: 2.0, color: Color(0xffff0000)),
          Container(width: 11.0, height: 2.0, color: Color(0xffff0000)),
        ],
      )
```
The result (eight times magnified):
![screen shot 2018-04-29 at 5 16 29 pm](https://user-images.githubusercontent.com/2334887/39411979-91df3016-4bd1-11e8-9630-d4808b96c2a8.png)

First question: is this by design?
Second question: is there anything I can do to make it render without that gap?

**Comment by jonahwilliams** [comment] 2018-04-29 05:30
Possibly related to https://github.com/flutter/flutter/issues/16262, where a device with a non-power of two device pixel ratio causes unintuitive rounding.

**Comment by itsJoKr** [comment] 2018-05-01 15:15
This is by design, based on the answer by @Hixie  here: https://github.com/flutter/flutter/issues/15035

Possible solution:

> The second is to wrap all those widgets with a RepaintBoundary, which will cause them to all be painted as one graphic which is then anti-aliased once with the parent. That might not solve the issue, depending on exactly what the alignment ends up being, but it should be better.

**Comment by Hixie** [comment] 2018-05-01 16:37
It's possible to avoid these antialiasing effects by specifying sizes that align to the physical pixel boundaries. If you ask for a rectangle that's 3.5 physical pixels high, and then another that's 3.5 pixels physical high, then we have to figure out how to render the physical pixels that have half of the top rectangle and half of the bottom rectangle both blended on top of the background.

We definitely need to document this better though. Maybe in the Canvas and Container documentation?

**Comment by SteveAlexander** [comment] 2018-09-04 17:19
Found this helpful after I thought I was seeing a fencepost error.

Ended up writing this:
```
  double divideQuantizedToPixelRatio(pixels, divideBy, pixelRatio) =>
      (pixels * pixelRatio ~/ divideBy) / pixelRatio;
```

**Comment by Hixie** [comment] 2018-09-17 22:53
See also https://github.com/flutter/flutter/issues/15035

**Comment by goderbauer** [comment] 2018-12-28 22:53
Closing this as another dupe of https://github.com/flutter/flutter/issues/14288.

**Closed by goderbauer** 2018-12-28 22:53 UTC
Labels: d: api docs, engine, framework
