### ISSUE TITLE
[Android Studio BumbleBee 2021.1.1]: flutter doctor shows `CocoaPods not installed. Skipping pod install`

### ISSUE THREAD

**Issue by NathanMDT** [flutter/flutter#97251] opened 2022-01-25 22:05 UTC
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Debug flutter project 

Flutter doctor run from command 
Says CocoaPods not installed.

And YES, I have tried uninstalling and reinstalling cocoacpods dozens of times. 
IT IS INSTALLED. 
But Android Studio doesn't know that. 

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
 Very interesting that the output of the flutter doctor from the command line is different from that of Tools-> Flutter >Flutter Doctor

First, from running flutter doctor -v 
no issues are found. 
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/Nathan.mellor/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nathan.mellor/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/nathan.mellor/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • Pixel 3 (mobile)   • 8A9X0NAVC                            • android-arm64  • Android 12 (API 31)
    • iPhone 13 (mobile) • 0B466EB6-F0CB-4477-9745-A1B550143BC3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

But if using the menu option:
```
/Users/nathan.mellor/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/nathan.mellor/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nathan.mellor/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • Pixel 3 (mobile)   • 8A9X0NAVC                            • android-arm64  • Android 12 (API 31)
    • iPhone 13 (mobile) • 0B466EB6-F0CB-4477-9745-A1B550143BC3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.
Process finished with exit code 0

```

**Comment by stuartmorgan** [comment] 2022-01-26 01:34
Where is Cocoapods installed? The most likely explanation for the difference is that it's in a location that's in your path in a terminal, but not for UI applications.

**Comment by darshankawar** [comment] 2022-01-26 08:55
@NathanMDT 
Check above comment and confirm the location in your path is correct.

**Comment by kolotum** [comment] 2022-01-26 09:55
This happened after I upgraded to Android Studio Bumblebee (2021.1.1) on Mac (Apple Silicon).

No issues with the previous Android Studio version before.

**Comment by alod2019** [comment] 2022-01-26 14:46
The same issue with AS Bumblebee on a Mac with Intel CPU

**Comment by alod2019** [comment] 2022-01-26 15:30
verbose logging shows these two lines one right after another

> [  +14 ms] executing: which pod
> [   +8 ms] Warning: CocoaPods not installed. Skipping pod install.

"which pod" works Ok outside AS and in AS terminal window but something goes wrong when building or running Flutter doctor from the menu.

**Comment by NathanMDT** [comment] 2022-01-26 16:39
Is this I check where my cocoapods are installed? 
% gem which cocoapods
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods.rb
How do I check whether that is in Android Studio's path? 

I have tried installing it through brew as well. 

It is also on AS Bumblebee on a Mac. The Mac recently had an update to 12.1.
Xcode at /Applications/Xcode.app/Contents/Developer

**Comment by alod2019** [comment] 2022-01-26 16:55
That's what "Flutter doctor" menu option prints (with verbose logging  enabled) 

[  +14 ms] executing: which pod
[   +8 ms] Warning: CocoaPods not installed. Skipping pod install.
             CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
             Without CocoaPods, plugins will not work on iOS or macOS.
             For more info, see https://flutter.dev/platform-plugins
           To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[   +3 ms] CocoaPods not installed or not in valid state.
[        ] Error launching application on iPhone 13 Pro Max.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:576:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

**Comment by alod2019** [comment] 2022-01-26 17:27
Just in case that's what "Flutter doctor" menu command prints if verbose logging is enabled
```
[  +14 ms] executing: which pod
[   +8 ms] Warning: CocoaPods not installed. Skipping pod install.
             CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
             Without CocoaPods, plugins will not work on iOS or macOS.
             For more info, see https://flutter.dev/platform-plugins
           To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[   +3 ms] CocoaPods not installed or not in valid state.
[        ] Error launching application on iPhone 13 Pro Max.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:576:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```

**Comment by darshankawar** [comment] 2022-01-27 05:27
Please check below links and see if they help:

https://github.com/flutter/flutter/issues/97072#issuecomment-1020072523
https://github.com/flutter/flutter/issues/93475#issuecomment-966851919

**Comment by liorboyango** [comment] 2022-01-27 06:46
While the debug & run buttons on Android Studio fail due to the above, 'flutter run' works

**Comment by alod2019** [comment] 2022-01-27 06:50
To clarify - the problem happens only when a flutter command (Doctor or build) is triggered from AS Bumblebee menu.
There are no problems with AS Arctic Fox and VS Code.

**Comment by alod2019** [comment] 2022-01-27 07:45
[A workaround from Stackoverflow](https://stackoverflow.com/a/70870858) is to start Android studio from terminal:
```
open /Applications/Android\ Studio.app 
```

**Comment by exitist** [comment] 2022-01-27 09:25
I've also tested workarounds in #97072 (comment) #93475 (comment) and bunch of command line workarounds, but nothing works. All conditions are same as above comments.

I'm doing my job with `flutter run --debug` from AS terminal. Clicking r/R is doing hot reload/restart, so it is not that critic. I guess it may be a AS flutter-dart plugin issue..

**Comment by MarkBurvs** [comment] 2022-01-27 11:32
Getting this issue on my M1 Macbook after updating to Bumblebee. Normal terminal and terminal in Android Studio both find pod okay, and flutter doctor reports no problems. Running flutter from the command line works fine (in AS too), but pressing the run or debug buttons on the AS toolbar give the error.
As suggested above, launching AS from the command line makes everything work.
I've tried adding the path to pod to my .zshrc file, but that doesn't help. For some reason, AS just can't find it.

**Comment by IonVillarreal** [comment] 2022-01-27 11:54
For now, download the previous preview version: Android Studio Chipmunk (2021.2.1) Canary 6

https://developer.android.com/studio/archive

**Comment by blue492** [comment] 2022-01-27 13:52
I have same issue and this problem appear when I upgraded to the new Android version, only in Mac when I try to do: Build -> Flutter -> Build iOS it shows this warning:


``Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
CocoaPods not installed or not in valid state.
Process finished with exit code 1 ``

But I did already this
`gem install cocoapods
Successfully installed cocoapods-1.11.2
Parsing documentation for cocoapods-1.11.2
Done installing documentation for cocoapods after 1 seconds
1 gem installed`

and I did pod install also, but it still shows same warning.

How to fix it? 
Regards

**Comment by mariopepe** [comment] 2022-01-27 20:05
Craxy that this goes to production to millions of users... spent hours now.... boring and lame

**Comment by mark8044** [comment] 2022-01-28 03:35
This is nuts.  Been at a standstill now, thinking its a widespread bug and would be surely addressed quickly.
Not only can you not launch any iOS simulator apps but the android device manager also doesn't work after the bumblebee upgrade.

So do we wait more or will this take weeks/months to address?

**Comment by darshankawar** [comment] 2022-01-28 05:23
Thanks for your patience. I understand that this behavior is occuring using the latest version of Android Studio, ie, https://developer.android.com/studio/releases#bumblebee and based on above reports, it occurs on Intel as well as on M1.
Based on above reports, I am going ahead and labeling it.

/cc @christopherfujino

**Comment by MarkBurvs** [comment] 2022-01-28 09:57
> 

@mark8044 You can double-press shift to do a global search search and type "Virtual Device Manager" to open the device manager and that works. Just not from the button on the top bar or the menu.

**Comment by alod2019** [comment] 2022-01-28 15:24
Issue in AS bugtracker
https://issuetracker.google.com/issues/216663013

**Comment by stevemessick** [comment] 2022-01-28 16:54
If `open /Applications/Android\ Studio.app` makes everything work, then this may be an issue with environment variables getting out of sync. If that's the case, logging out and logging back in (to reset the global shell and reload its envars) might fix the underlying problem.

Could someone who's experiencing the problem try that and report back here?

**Comment by MarkBurvs** [comment] 2022-01-28 16:57
> If `open /Applications/Android\ Studio.app` makes everything work, then this may be an issue with environment variables getting out of sync. If that's the case, logging out and logging back in (to reset the global shell and reload its envars) might fix the underlying problem.
> 
> Could someone who's experiencing the problem try that and report back here?

@stevemessick Logging out / logging in doesn't fix anything for me.

**Comment by Paul-Todd** [comment] 2022-01-28 21:40
@stevemessick Logging out/logging in had no effect for me. using open did however worked as a workaround

**Comment by TatsuUkraine** [comment] 2022-01-28 22:43
Can confirm that this issue appeared after android studio update. Happening on Intel and m1 macs. Workarounds so far that worked for me:
- run build form the terminal
- launch AS from the terminal, it that case app builds from both terminal and AS buttons

**Comment by stevemessick** [comment] 2022-01-28 23:07
Thanks for the reply, everyone. What's odd to me is that re-logging did clear up the problem for me. Or maybe I never properly reproduced it in the first place. On my macOS 12.1 computer, still using bash (not zsh), everything works as it should.

One source of confusion is modifying `PATH` in the wrong script file. One of them is only run when logging in and that's the shell used by the IDE. I have no idea why upgrading to Bumblebee would cause a problem, so it might be something totally different. But, as I said, I can launch a Flutter app on the iOS simulator and my iPad. I suggest checking the docs for your shell, and making sure your `PATH` mods and other environment variables are set in the login script.

One more thing: the problem with the device manager is related to a bug in the Flutter plugin. The device manager only launches if the project has an Android module. If you add an Android module to your Flutter project then the device manager works. https://github.com/flutter/flutter-intellij/issues/5464#issuecomment-836857485 has more info. I'm working on a fix for the problem but I'm not sure when it will be ready.

**Comment by TatsuUkraine** [comment] 2022-01-28 23:42
@stevemessick I definitely can confirm that actions like Flutter doctor or Run, Debug buttons from the IDE UI were working fine until I update AS and plugins for Flutter and Dart. Commands like `flutter run` and `flutter doctor` were working and remain working just fine. No matter if I type them in the regular terminal window or terminal within the IDE.

Launching IDE from the terminal fixes the issue. It looks to me that problem is actually inside the Flutter plugin rather than in IDE.

**Comment by stevemessick** [comment] 2022-01-29 00:13
@TatsuUkraine since launching from the terminal fixes the issue, it really sounds like the path is defined in a script that gets run when you create a new shell after having logged in. For the IDE to see it, the path must be defined when running the login script. And, as I mentioned, everything works for me, which strongly suggests there is no problem in the plugin.

**Comment by TatsuUkraine** [comment] 2022-01-29 00:21
I was rebooting and relogin yesterday and today. I didn't change any env variables. Only one difference between now and then - ide and plugin versions. And it was the same on both MacBooks Intel and m1 based

**Comment by mark8044** [comment] 2022-01-29 04:33
> @mark8044 You can double-press shift to do a global search search and type "Virtual Device Manager" to open the device manager and that works. Just not from the button on the top bar or the menu.

Can confirm this works.  Thank you very much for this tip!
But hopefully this is all sorted out quickly because for now I have to do your trick, in addition to launching studio from command line and doing a `pod update` for every dependency upgrade.  Its getting old real quick  :)

Thanks again

**Comment by mark8044** [comment] 2022-01-29 04:39
> 
> One more thing: the problem with the device manager is related to a bug in the Flutter plugin. The device manager only launches if the project has an Android module. If you add an Android module to your Flutter project then the device manager works. [flutter/flutter-intellij#5464 (comment)](https://github.com/flutter/flutter-intellij/issues/5464#issuecomment-836857485) has more info. I'm working on a fix for the problem but I'm not sure when it will be ready.

Im probably not understanding what you mean about an Android module to flutter project, but my app is primarily used on Android, and flutter doctor -v shows I successfully have android SDK installed, but this bug is occurring for me

For now what I'm doing to get things to work as pre-bumblebee are
1. Launch Android studio from terminal with: `open /Applications/Android\ Studio.app`
2. Open Device manager by: `press shift twice` and then type `Virtual Device Manager`
3. When trying to run on iOS simulator, from terminal have to `cd ios` then type `pod update` to get cocoa pods parts updated

This has become my daily routine to get things going, hopefully this helps others and hopefully things get back on track

Thanks

**Comment by sanuser121** [comment] 2022-01-29 05:41
> If `open /Applications/Android\ Studio.app` makes everything work, then this may be an issue with environment variables getting out of sync. If that's the case, logging out and logging back in (to reset the global shell and reload its envars) might fix the underlying problem.
> 
> Could someone who's experiencing the problem try that and report back here?

it doesn't fix anything for me either

**Comment by sanuser121** [comment] 2022-01-29 05:57
> 1. open /Applications/Android\ Studio.app

thanks a lot it does work for me . Almost wasted a day to find something meaningful .
Thank you

**Comment by jperezr21** [comment] 2022-01-29 20:58
One solution if using zsh is to do
```
echo "source ~/.zshrc" > ~/.profile
```
then log out and log back in. Now when I open Android Studio from the dock I can launch Flutter apps in the iOS simulator.

**Comment by TatsuUkraine** [comment] 2022-01-30 00:07
@jperezr21 doesn't work for me

what flutter doctor says when you launch it from package.yaml actions (top right corner)? If we talking about launching the app on the simulator, the fact that it started to work for you may not mean that you fixed the issue. It may simply mean that pod install wasn't invoked during app build. SInce Pod installation doesn't invoke each time you build the app, I think it invokes only when iOS deps are changing to you building the app after `flutter clean`

**Comment by jperezr21** [comment] 2022-01-30 00:19
@TatsuUkraine you're right, when running flutter doctor from `pubspec.yaml` I get
```
✗ CocoaPods not installed.
```
so ignore my comment above.

**Comment by aruizcanton** [comment] 2022-01-31 07:58
> [A workaround from Stackoverflow](https://stackoverflow.com/a/70870858) is to start Android studio from the terminal:
> 
> ```
> open /Applications/Android\ Studio.app 
> ```

Thanks a lot for the solution.
I spent a whole day looking for a solution.

**Comment by TatsuUkraine** [comment] 2022-01-31 12:38
so I just installed Android Studio Arctic Fox | 2020.3.1 Patch 4, and I can say that all works fine there

**Comment by stevemessick** [comment] 2022-01-31 19:39
[I meant to post this Sunday but forgot to click Comment. I did post it in Flutter plugin issues.]

It turns out, I did not do a proper test (as I claimed in a previous comment). It is broken for me, too.

For some reason Android Studio Bumblebee is not getting the PATH from the login shell. I found this:

<img width="523" alt="Screen Shot 2022-01-30 at 10 30 46 AM" src="https://user-images.githubusercontent.com/8518285/151860821-e494f336-00c1-402d-9dde-231660f44b36.png">

That's the default value of PATH before any shell script runs. Not very useful for us. (In case anyone needs to know how to find that, I used the Flutter plugin to create a Java project in Android Studio -- something you should not be able to do. Then I added a run config for an Application and used the environment variable tool to display the values.)

If I look at the same dialog using Chipmunk (canary) it shows a proper PATH value.

I don't know how to fix it yet, but I'm going to talk with my team about possibilities.

**Comment by stevemessick** [comment] 2022-01-31 19:52
Update: We planned to release a new version of the plugin on Feb 1 but have decided to hold that until we have a fix for this problem. We have a couple possible solutions, with the simplest (from our point of view) being an update to Bumblebee that fixes the `PATH` value. Alternatively, perhaps wrapping all our process-forking code in a shell would work. Neither is likely to happen overnight.

So, for now, the work-arounds are to go back to Arctic Fox or launch from a terminal via:
`open /Applications/Android\ Studio.app`

If you installed Android Studio from the JetBrains Toolbox the path will be different, something like:
`open ~/Library/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628/AndroidStudio.app`
(I'm guessing the path. There may be a space in Android Studio, ch-0 might be something else, and the version number may be different. But, that seems to be the pattern.)

**Comment by stevemessick** [comment] 2022-01-31 21:35
Update: The Android Studio team is already aware of the problem. I don't know when it will get fixed but I expect a patch soon-ish.

There is another work-around, that you only have to do once.

> The workaround is to add missing flag: chmod +x /Applications/Android\ Studio.app/Contents/bin/printenv
> 
> If you are using JetBrains Toolbox, then printenv file location would be different. Check installation path in (kebab menu) / Setting / Configuration for Android Studio tool, and adjust command above accordingly.

**Comment by harnit-bakshi** [comment] 2022-02-01 05:41
Pretty poor user experience :(

**Comment by TatsuUkraine** [comment] 2022-02-01 08:08
> The workaround is to add missing flag: chmod +x /Applications/Android\ Studio.app/Contents/bin/printenv
>
> If you are using JetBrains Toolbox, then printenv file location would be different. Check installation path in (kebab menu) / Setting / Configuration for Android Studio tool, and adjust command above accordingly.

this worked! thank you)

**Comment by christopherfujino** [comment] 2022-02-02 00:50
@harnit-bakshi I hid your comment as off-topic. I would also advise you to review Flutter's code of conduct https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md#code-of-conduct before making future comments in our community. Thanks!

**Comment by stevemessick** [comment] 2022-02-04 17:22
There is a new version of Bumblebee available that fixes this issue.

**Comment by stevemessick** [comment] 2022-02-04 21:26
If the menu item `Check for Updates` does not prompt you to update you can download it directly from https://developer.android.com/studio/archive

**Comment by mark8044** [comment] 2022-02-05 03:23
> There is a new version of Bumblebee available that fixes this issue.

I think it successfully fixes the CocoaPods issue, at least I'm not getting that anymore as far as I can tell.  

However the device manager still doesn't work?

**Comment by TatsuUkraine** [comment] 2022-02-05 08:17
@mark8044 I don't know if it's related to bumblebee update or not, I was able to solve it by adding Android to the project structure in the settings

**Comment by mark8044** [comment] 2022-02-05 22:41
> @mark8044 I don't know if it's related to bumblebee update or not, I was able to solve it by adding Android to the project structure in the settings

For me it broke with the first Bumblebee upgrade

With that said, when you say `project structure` where do you find that?  

thanks!

**Comment by TatsuUkraine** [comment] 2022-02-05 23:40
@mark8044 

<img width="245" alt="Снимок экрана 2022-02-06 в 01 30 46" src="https://user-images.githubusercontent.com/621542/152662492-219b0c40-bee5-4a4f-af3a-7c75c0a64d64.png">

then click on the project name and Add button

<img width="232" alt="Снимок экрана 2022-02-06 в 01 37 29" src="https://user-images.githubusercontent.com/621542/152662602-20b7d2a5-7d5f-4762-9d04-c482b00c73ca.png">

And select the Android option there

<img width="218" alt="Снимок экрана 2022-02-06 в 01 31 52" src="https://user-images.githubusercontent.com/621542/152662526-7ac9d37e-ac3a-433e-94ac-f7d500abe48f.png">

I personally didn't change any input values and saved it as it is

**Closed** 2022-02-07 16:41 UTC
Labels: tool, platform-mac, t: flutter doctor, customer: crowd
