### ISSUE TITLE
RefreshProgressIndicator animates when offstage

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#18054] opened 2018-05-31 03:42 UTC
I was playing around with the profiling overlay, and I noticed that the overlay continues to move as if frames are animating when we have a `RefreshProgressIndicator` that's offstage. I'm assuming this is unintentional per #5469 ?

**Comment by alanrussian** [comment] 2018-05-31 16:55
My evidence is that the performance overlay continues to move instead of stopping. I assumed that meant it was generating frames? I've attached a video of the following code. Note that this is before #17923 was fixed, so it stops at 6.66 seconds.

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Test app'),
        ),
        body: _body),
    showPerformanceOverlay: true,
  ));
}

Widget get _body {
  return new Offstage(offstage: true, child: new RefreshProgressIndicator());
}
```
[demo.mp4.zip](https://github.com/flutter/flutter/files/2059211/demo.mp4.zip)



I also notice that if I try to pumpAndSettle in a widget test, the pumpAndSettle times out.

```
  testWidgets('Size transition', (WidgetTester tester) async {
    await tester.pumpWidget(new Offstage(
      offstage: true,
      child: new RefreshProgressIndicator(),
    ));
    await tester.pumpAndSettle(const Duration(milliseconds: 100),
        EnginePhase.sendSemanticsUpdate, const Duration(seconds: 2));
  });
```

That happens for `CircularProgressIndicator` too. I think this only means that microtasks are still scheduled, not that frames are still being produced. However, why are microtasks scheduled if no animations are occurring?

**Comment by goderbauer** [comment] 2018-05-31 21:45
After talking to @Hixie I believe it is intentional that the animations keep running while something is off-stage. Off-stage is defined to layout a widget exactly like it would happen on screen except that nothing is painted. This means that animations also continue running. Offstage is mainly meant to measure the size of a widget without having it on screen.

#5469 is supposed to only stop animations for routes that are currently not on screen. That's probably also why @HansMuller wasn't able to reproduce this with the "Pull to refresh" demo as he was most likely backing out of a route.

I am closing this as working as intended for now. Feel free to re-open with more information if you have further concerns.

**Closed** 2018-05-31 21:45 UTC
Labels: customer: mulligan (g3), severe: customer critical

**Comment by alanrussian** [comment] 2018-05-31 21:50
Got it. Thanks for the explanation. 

Is it worth adding a quick comment in the `Offstage` widget DartDoc?

**Comment by goderbauer** [comment] 2018-05-31 21:53
Will do!

**Comment by goderbauer** [comment] 2018-06-01 00:39
Just FYI and maybe related: If you do want to stop animations in a sub-tree you can use the TickerMode widget: https://docs.flutter.io/flutter/widgets/TickerMode-class.html

**Comment by alanrussian** [comment] 2018-07-24 19:51
What's the schedule for updating the Flutter Dart Docs like? I was looking for the updated information at  https://docs.flutter.io/flutter/widgets/Offstage-class.html today but didn't see it.
