### ISSUE TITLE
Test coverage shows only some asserts coveraged

### ISSUE THREAD

**Issue by apaatsio** [flutter/flutter#22508] opened 2018-10-01 10:24 UTC
## Bug description
I have multiple asserts in my code and I run tests with `flutter test --coverage`.

Actual result: Only some asserts are marked covered in the lcov report.

Expected result: All asserts are marked covered in the lcov report.

![asserts-partial-coverage](https://user-images.githubusercontent.com/195210/46283367-7f743300-c574-11e8-9943-f18a0b52efa6.png)
(Screenshot from VSCode with Coverage Gutters extension. Green marks covered lines, red marks uncovered.)

## Steps to Reproduce & logs

The code, lcov report, and verbose output can be found here: https://gist.github.com/apaatsio/eed9ada2c0a17a614190b04938312faf

**Comment by zoechi** [comment] 2019-02-14 17:40
I think there was some coverage-related fix not too long ago. 
Can you please check if you can still reproduce with Flutter from latest `master` channel?

**Comment by 100cm** [comment] 2019-02-15 09:43
![image](https://user-images.githubusercontent.com/12691638/52848118-e91e6380-3148-11e9-9092-22577c7e956e.png)
@zoechi 

yes, i can reproduce, and here is my test file:

![image](https://user-images.githubusercontent.com/12691638/52848167-04896e80-3149-11e9-9a35-fd4611ff2ec6.png)


and here are my project's files;

![image](https://user-images.githubusercontent.com/12691638/52848184-0b17e600-3149-11e9-880e-41ad34ac1b55.png)

**Comment by zoechi** [comment] 2019-02-15 09:56
I use a Grinder task 
```dart
/// Generate a single Dart file that executes all tests.
/// Dart code coverage reporting still requires that.
@Task('generate test/all.dart')
Future<void> prepareCoverage() async {
  final testDir = Directory('test');
  final context = path.Context(style: path.Style.posix);
  final testFiles = testDir
      .listSync(recursive: true, followLinks: false)
      .where((e) =>
          FileSystemEntity.isFileSync(e.path) && e.path.endsWith('_test.dart'))
      .map(
          (tf) => context.normalize(path.relative(tf.path, from: testDir.path)))
      .toList()
        ..sort();
  final content = StringBuffer('''
// ignore_for_file: await_only_futures

import 'dart:async';

''');
  final executions = StringBuffer();
  for (var i = 0; i < testFiles.length; i++) {
    final testFile = testFiles[i];
    content.writeln("import '$testFile' as i$i;");
    executions.writeln('  i$i.main();');
  }
  content
    ..writeln('Future<void> main() async {')
    ..writeln()
    ..writeln(executions)
    ..writeln('}');
  File('test/all.dart').writeAsStringSync(content.toString());
  PubApp.global('dart_style')
      .run(['-w', '--fix']..add('test/all.dart'), script: 'format');
}
```
to generate a `test/all.dart` like

```dart
// ignore_for_file: await_only_futures

import 'dart:async';

import 'client/controller/app_controller_test.dart' as i0;
import 'client/controller/authentication_controller_test.dart' as i1;
import 'client/controller/backoffice/backoffice_controller_test.dart' as i2;
import 'client/controller/backoffice/image_reference_controller_test.dart'
    as i3;
...

Future<void> main() async {
  i0.main();
  i1.main();
  i2.main();
...
}
```
When I run this with coverage from IntelliJ the project window shows coverage info.

**Comment by 100cm** [comment] 2019-02-15 10:04
i  got  this , but i need time to learn it (i need to do this in gitlab CI). 
and an other question: There's no any other way to generate the report directly that  includes both tested and untested files ?

**Comment by zoechi** [comment] 2019-02-15 10:16
I don't know gitlab but `flutter run test --coverage`  and then uploading the resulting output to codecov.io (according to their instructions) provided a web interface to see what files and lines are covered by tests.

**Comment by 100cm** [comment] 2019-02-15 10:20
@zoechi Yes, but the question now is if i write test cases for File [A] ,and none test cases for File [B]

and i run 

`flutter  run test --coverage`

the report will show 100% coverage , Not what i expected (50%) ,it only collect the files that you have test cases for it.

**Comment by zoechi** [comment] 2019-02-15 10:32
> the report will show

which report? What tool are you using to display the result?

**Comment by 100cm** [comment] 2019-02-15 10:43
@zoechi  see my picture above .

the test.sh execute the commands:

```genhtml coverage/lcov.info -o ./coverage```
```lcov-summary coverage/lcov.info```

**Comment by zoechi** [comment] 2019-02-15 10:50
This discussion is unrelated to the issue and I think it would be better to create a StackOverflow question. 
The problem seems to be a limitation or wrong usage of `genhtml`.
If it actually turns out to be a Flutter problem, please create a new issue for that specific problem.

**Comment by 100cm** [comment] 2019-02-15 10:51
@zoechi  thanks a lot.

**Comment by zoechi** [comment] 2019-02-15 11:29
@100cm I just posted an answer to https://stackoverflow.com/questions/54708107/flutter-inline-test-coverage-in-android-studio/54708361#54708361 about coverage information in IntelliJ. I had to dig a bit because it's a while I worked on that project.

**Comment by 100cm** [comment] 2019-02-15 11:55
@zoechi  i know how to test all "test cases" and how to generate GUI report , i just confused about  why the  `lcov.info` results only includes tested files. but not all files.

**Comment by apaatsio** [comment] 2019-02-15 12:28
@zoechi I'm still seeing the exact same issue even when using the latest master.

```
[✓] Flutter (Channel master, v1.2.2-pre.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.2-pre.3 at /home/antti/tools/flutter
    • Framework revision 67cf21577f (5 hours ago), 2019-02-14 23:17:16 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by zoechi** [comment] 2019-02-15 14:15
@apaatsio thanks for checking!

**Comment by markusaksli-nc** [comment] 2020-07-28 12:14
Hi @apaatsio 
Can you confirm that the issue still persists on the latest master?
Thank you

**Comment by apaatsio** [comment] 2020-08-02 18:00
Yes, the problem still persists.

Tested on:
```
Flutter 1.21.0-6.0.pre.141 • channel master • https://github.com/flutter/flutter.git
Framework • revision c748f1a7aa (2 days ago) • 2020-07-31 17:45:18 -0700
Engine • revision 280bbfc763
Tools • Dart 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)
```

**Comment by markusaksli-nc** [comment] 2020-08-03 13:02
It would be very helpful if you could provide a minimal reproducible project to demonstrate this issue, marking it as passed triage since there seems to be enough information here.

**Comment by apaatsio** [comment] 2020-08-04 07:38
Added a minimal reproducible project: https://github.com/apaatsio/flutter_assert_test_coverage

```
git clone git@github.com:apaatsio/flutter_assert_test_coverage.git
cd flutter_assert_test_coverage
flutter test --coverage
cat ./coverage/lcov.info
```

**Comment by markusaksli-nc** [comment] 2020-08-04 08:04
Thank you. Confirming as Reproducible on the latest master `1.21.0-6.0.pre.160`.
<details>
 <summary>flutter doctor -v</summary>

 ```
 [✓] Flutter (Channel master, 1.21.0-6.0.pre.160, on Mac OS X 10.15.6 19G73, locale en-GB)
     • Flutter version 1.21.0-6.0.pre.160 at /Users/markus/development/flutter_master
     • Framework revision 31ee51a302 (8 hours ago), 2020-08-03 17:27:21 -0700
     • Engine revision fa16c3d0ba
     • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)

  
 [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
     • Android SDK at /Users/markus/Library/Android/sdk
     • Platform android-30, build-tools 30.0.1
     • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
     • All Android licenses accepted.

 [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
     • Xcode at /Applications/Xcode.app/Contents/Developer
     • Xcode 11.6, Build version 11E708
     • CocoaPods version 1.9.3

 [✓] Chrome - develop for the web
     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

 [✓] Android Studio (version 4.0)
     • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
       Studio.app/Contents
     • Flutter plugin version 48.0.2
     • Dart plugin version 193.7361
     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 [✓] Connected device (4 available)
     • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
     • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
     • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
     • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

 • No issues found!
```
</details>
<details>
 <summary>lcov.info</summary>

 ```
SF:lib/assert.dart
DA:1,1
DA:2,0
LF:2
LH:1
end_of_record
```
</details>

**Comment by darshankawar** [comment] 2022-10-20 10:37
Verified this using latest stable version and by cloning the repo given by OP and it gives the expected result as below:

```
dhs@Dhss-MacBook-Pro flutter_assert_test_coverage % cat ./coverage/lcov.info
SF:lib/assert.dart
DA:1,1
DA:2,1
LF:2
LH:2
end_of_record

```

Closing as fixed.

**Closed by darshankawar** 2022-10-20 10:37 UTC
Labels: a: tests, framework, dependency: dart, passed first triage, has reproducible steps, P4, found in release: 1.21
