### ISSUE TITLE
Android App Closed unexpectedly. App Crashes

### ISSUE THREAD

**Issue by SandyAra** [flutter/flutter#32903] opened 2019-05-17 16:48 UTC
Please kindly help me asap.
My App ready to launch on play store.. but getting delay due to this crash.

Kindly help me asap
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.vgts.lmes, PID: 4228
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/auth/internal/InternalAuthProvider;
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-common@@17.0.0:78)
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-common@@17.0.0:71)
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@17.0.0:468)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:354)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:321)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:305)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.0.0:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.0.0:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: com.google.firebase.auth.internal.InternalAuthProvider
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-common@@17.0.0:78) 
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-common@@17.0.0:71) 
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@17.0.0:468) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:354) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:321) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:305) 
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.0.0:53) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1917) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1892) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.0.0:47) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/internal/InternalTokenProvider;
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-common@@17.0.0:78) 
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-common@@17.0.0:71) 
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@17.0.0:468) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:354) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:321) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:305) 
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.0.0:53) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1917) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1892) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.0.0:47) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.internal.InternalTokenProvider" on path: DexPathList[[zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/base.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_dependencies_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_resources_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_0_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_1_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_2_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_3_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_4_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_5_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_6_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_7_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_8_apk.apk", zip file "/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/base.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_resources_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 24 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/tech.vgts.lmes-9XcSMRSTvmB6BN8MkBPS_A==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
        at android.app.LoadedApk.getResources(LoadedApk.java:954)
```

**Comment by kenwen** [comment] 2019-06-27 10:57
I've just started experiencing the same, I'm trying to isolate and think issue caused by some changes made to gradle files right before

**Comment by BondarenkoStas** [comment] 2019-10-09 13:42
Found the same error I think #32716.
@SandyAra did it get resolved? how's it with current flutter stable? if not, please provide your gradle.build content

**Comment by iapicca** [comment] 2019-11-08 10:42
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 10:42 UTC
Labels: waiting for customer response
