### ISSUE TITLE
Module 'cloud_firestore' not found impossible to publish APP on Apple App Store

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#47394] opened 2019-12-19 00:17 UTC
I can't build archive and upload it to App Store Connect because of this error.
My app runs perfectly on my iphone 6s ios 13.1.2, I can tweak and flutter run without any problems, I can tweak and tweet Xcode without any problems. The problem only occurs when I try product -> archive

```swift
//
//  Generated file. Do not edit.
//

#import "GeneratedPluginRegistrant.h"

#if __has_include(<cloud_firestore/FLTCloudFirestorePlugin.h>)
#import <cloud_firestore/FLTCloudFirestorePlugin.h>
#else
@import cloud_firestore;
#endif

#if __has_include(<connectivity/FLTConnectivityPlugin.h>)
#import <connectivity/FLTConnectivityPlugin.h>
#else
@import connectivity;
#endif

#if __has_include(<firebase_analytics/FLTFirebaseAnalyticsPlugin.h>)
#import <firebase_analytics/FLTFirebaseAnalyticsPlugin.h>
#else
@import firebase_analytics;
#endif

#if __has_include(<firebase_auth/FLTFirebaseAuthPlugin.h>)
#import <firebase_auth/FLTFirebaseAuthPlugin.h>
#else
@import firebase_auth;
#endif

#if __has_include(<firebase_core/FLTFirebaseCorePlugin.h>)
#import <firebase_core/FLTFirebaseCorePlugin.h>
#else
@import firebase_core;
#endif

#if __has_include(<firebase_database/FLTFirebaseDatabasePlugin.h>)
#import <firebase_database/FLTFirebaseDatabasePlugin.h>
#else
@import firebase_database;
#endif

#if __has_include(<google_sign_in/FLTGoogleSignInPlugin.h>)
#import <google_sign_in/FLTGoogleSignInPlugin.h>
#else
@import google_sign_in;
#endif

#if __has_include(<map_launcher/MapLauncherPlugin.h>)
#import <map_launcher/MapLauncherPlugin.h>
#else
@import map_launcher;
#endif

#if __has_include(<path_provider/FLTPathProviderPlugin.h>)
#import <path_provider/FLTPathProviderPlugin.h>
#else
@import path_provider;
#endif

#if __has_include(<share/FLTSharePlugin.h>)
#import <share/FLTSharePlugin.h>
#else
@import share;
#endif

#if __has_include(<shared_preferences/FLTSharedPreferencesPlugin.h>)
#import <shared_preferences/FLTSharedPreferencesPlugin.h>
#else
@import shared_preferences;
#endif

#if __has_include(<sqflite/SqflitePlugin.h>)
#import <sqflite/SqflitePlugin.h>
#else
@import sqflite;
#endif

#if __has_include(<url_launcher/FLTURLLauncherPlugin.h>)
#import <url_launcher/FLTURLLauncherPlugin.h>
#else
@import url_launcher;
#endif

#if __has_include(<webview_flutter/FLTWebViewFlutterPlugin.h>)
#import <webview_flutter/FLTWebViewFlutterPlugin.h>
#else
@import webview_flutter;
#endif

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [FLTCloudFirestorePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTCloudFirestorePlugin"]];
  [FLTConnectivityPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTConnectivityPlugin"]];
  [FLTFirebaseAnalyticsPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseAnalyticsPlugin"]];
  [FLTFirebaseAuthPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseAuthPlugin"]];
  [FLTFirebaseCorePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseCorePlugin"]];
  [FLTFirebaseDatabasePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseDatabasePlugin"]];
  [FLTGoogleSignInPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTGoogleSignInPlugin"]];
  [MapLauncherPlugin registerWithRegistrar:[registry registrarForPlugin:@"MapLauncherPlugin"]];
  [FLTPathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTPathProviderPlugin"]];
  [FLTSharePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTSharePlugin"]];
  [FLTSharedPreferencesPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTSharedPreferencesPlugin"]];
  [SqflitePlugin registerWithRegistrar:[registry registrarForPlugin:@"SqflitePlugin"]];
  [FLTURLLauncherPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTURLLauncherPlugin"]];
  [FLTWebViewFlutterPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTWebViewFlutterPlugin"]];
}

@end
```

![WhatsApp Image 2019-12-18 at 21 06 57](https://user-images.githubusercontent.com/12227024/71133915-0abe0080-21db-11ea-99ae-08bbfc9bb78f.jpeg)

```console
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(_dir_, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

```yaml
name: appsescverao
description: Aplicativo do Sesc Verão Rio das Ostras

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+2
  path_provider: ^1.5.1
  flutter_advanced_networkimage: ^0.6.2
  sqflite: ^1.2.0
  connectivity: ^0.4.6+1
  url_launcher: ^5.4.1
  cloud_firestore: ^0.12.10
  firebase_auth: ^0.14.0+8
  google_sign_in: ^4.0.11
  firebase_database: ^3.0.9
  rxdart: ^0.23.1
  webview_flutter: ^0.3.18+1
  auto_size_text: ^2.1.0
  flutter_map: ^0.8.0
  latlong: ^0.6.1
  queries: ^0.1.12
  firebase_analytics: ^5.0.6
  shared_preferences: ^0.5.6
  share: ^0.6.3+5
  map_launcher: ^0.3.2
  #audioplayers: ^0.13.5
  #audio_streams: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.7

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.png
    - assets/background2.png
    - assets/background3.png
    - assets/user-avatar.png
    - assets/logo-pmro-cinza.png
    - assets/logo-pmro-branco.png
    - assets/wave-bottom.png
    - assets/wave-top.png
    - assets/logo2.png
    - assets/logo-branca.png

  fonts:
    - family: Big Noodle Titling
      fonts:
        - asset: fonts/big_noodle_titling.ttf
    - family: GlosaDisplayW01-Bold
      fonts:
        - asset: fonts/glosa_display_w01_bold.ttf
    - family: BakerieSmoothCondensedMedium
      fonts:
        - asset: fonts/BakerieSmoothCondensed-Medium.otf
    - family: BakerieSmoothBold
      fonts:
        - asset: fonts/BakerieSmooth-Bold.otf
    - family: iconsmind
      fonts:
        - asset: fonts/iconsmind.ttf
```

```dart
import 'package:appsescverao/pages/agendas_page.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'routes.dart';

//pages
import 'pages/atracoes_page.dart';
import 'pages/home_page.dart';
import 'pages/login_page.dart';
import 'pages/cadastro_page.dart';
import 'util/connection_check.dart';
import 'util/database_helper.dart';
import 'app_settings.dart';
import 'package:flutter/services.dart';

import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_analytics/observer.dart';


import 'package:flutter/services.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp() {
    //isInternet();
    //getToken();
  }

  /*Future isInternet() async {
    var r = await ConnectionCheck.isInternet();
    ConnectionCheck.asInternet = r;
  }

  void getToken() async {
    try {
      AppSettings.signIntoFirebase();
      var db = new DatabaseHelper();
      var user = await db.getFistUser();
      if (user != null) {
        AppSettings.token = user;
        AppSettings.tokenString = user.accessToken;
        debugPrint("main | carregou o token local ");
      } else {
        debugPrint("main | Erro ao obter token do sqlite");
      }
    } catch (e) {
      debugPrint("main | Erro ao obter token do sqlite e: " + e.toString());
    }
  }*/

  @override
  Widget build(BuildContext context) {
    // Fixing App Orientation.
    /*SystemChrome.setPreferredOrientations(
        [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);*/

    //SystemChrome.setEnabledSystemUIOverlays ([SystemUiOverlay.top]);
    //SystemChrome.setEnabledSystemUIOverlays ([]);
    //SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle())

    //FirebaseAnalytics analytics = FirebaseAnalytics();

    return MaterialApp(
      /*navigatorObservers: [
        FirebaseAnalyticsObserver(analytics: analytics),
      ],*/
      debugShowCheckedModeBanner: false,
      debugShowMaterialGrid: false,
      title: 'Sesc Verão',
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('pt', 'BR'),
        const Locale('es', 'ES'),
        const Locale('en', 'US'),
      ],
      theme: ThemeData(
        fontFamily: 'Roboto',
        brightness: Brightness.light,
        primaryColor: Colors.blue,
        // accentColor: Colors.lightBlue,
      ),
      home: //MinhaAgendaPage(),
      HomePage(),
      routes: routes,
    );
  }
}
```

**Comment by jmagman** [comment] 2019-12-19 02:12
Does it work if you remove `use_modular_headers!` from your Podfile?

**Comment by insinfo** [comment] 2019-12-19 15:04
@jmagman I did what you suggested, commented line 37 in the "use_module headers!" Podfile, but the problem remains.
Strange that I didn't put this line in Podfile, this Podfile was generated by Android Studio when I created the Flutter project.
My attempts were:
removed podfile.lock
rm -R .flutter-plugins
flutter clean

I can compile with "flutter build ios" and "flutter run"

**Comment by insinfo** [comment] 2019-12-19 15:06
Any suggestions are welcome as I need to publish this App as soon as possible as the Apple App Store will go down on December 27th. I have been able to publish to Google Play Store without problem so far, but at Apple I have this problem.

**Comment by MiguelAlcaino** [comment] 2019-12-19 19:50
I also have the same problem with connectivity and flutter_webview_plugin . I have read couple of issues related to the same problem and I still haven't found any solution :/

**Comment by jmagman** [comment] 2019-12-19 20:59
@insinfo With your pubspec and Podfile I was able to archive a Flutter app following the instructions at https://flutter.dev/docs/deployment/ios#create-a-build-archive.

As @MiguelAlcaino said, did you open Runner.xcworkspace and not Runner.xcodeproj?  See https://github.com/flutter/flutter/issues/10770

**Comment by insinfo** [comment] 2019-12-22 15:01
@MiguelAlcaino  dude you saved my day, i was 3 days breaking my head with this. Really the flutter needs to improve this part because I opened the project in xcode using the left mouse button floating menu inside vs code above the ios folder. Ideally, there is a button in visual studio code and Android Studio called open xcode that opens the correct project and a command called flutter opn xcode. The weirdest thing about it is that in xcode, when i clicked on the "run" icon inside xcode the project was successfully compiled and executed without any problem. And also when I executed the option "analyze App" xcode also gave no error, only when I clicked on "archive" that gave problem. Had to have better error message.

**Comment by rfitz123** [comment] 2020-01-19 21:40
@MiguelAlcaino This made my build take longer, but I still got the same error.

**Comment by jmagman** [comment] 2020-01-22 22:46
> because I opened the project in xcode using the left mouse button floating menu inside vs code above the ios folder

That was fixed with https://github.com/Dart-Code/Dart-Code/issues/2179.

Closing as duplicate of https://github.com/flutter/flutter/issues/10770.

**Closed by jmagman** 2020-01-22 22:46 UTC
Labels: t: xcode, tool, ⌺‬ platform-ios

**Comment by anraiki** [comment] 2020-03-12 23:11
For anyone who is facing the problem when "Archiving" or trying to publish to the Apple Store:

- Make sure to have all projects closed in Xcode
- Open "**Runner.xcworkspace**" not runner.xcodeproj

You have to make sure that runner.xcodeproj is not open at the same time with workspace.

This is also assuming that you have run and built successfully prior to making an archive.

**Comment by lexyfeito** [comment] 2020-03-28 22:29
Also, make sure select Generic IOS device. Otherwise Archive will not be enable. Thank you @MiguelAlcaino !!!
