### ISSUE TITLE
Please change this !!!

### ISSUE THREAD

**Issue by M001T** [flutter/flutter#58100] opened 2020-05-27 15:15 UTC
I would like to suggest an idea to improve the usability of the CLI flutter by 90%

Change the Print Widget Key, keep it away from the "R" key please, many developers accidentally click on the "T" key because it is next to each other

Another thing: Iapicca, I know you like to go on everyone's comment to say (Please share your flutter doctor) in that case stay away from my issue please

**Comment by TahaTesser** [comment] 2020-05-27 15:22
duplicate of https://github.com/flutter/flutter/issues/58101

**Closed by TahaTesser** 2020-05-27 15:22 UTC
