### ISSUE TITLE
0.2.2-pre.57 and Dart 2.0.0-dev.37.0.flutter-7328726088 on master looking for 'new' and 'const'

### ISSUE THREAD

**Issue by tensor-programming** [flutter/flutter#15593] opened 2018-03-15 23:12 UTC
After upgrading my flutter SDK to the current master channel I am unable to run my dart-2-preview applications without adding `new` or `const` keywords for certain widgets and classes. Compiler seems to assume these classes are functions without the `const` or `new` keywords. 

## Steps to Reproduce
Load up any dart 2 preview code that worked prior to the upgrade and upgrade your flutter tool to the master channel for `0.2.2-pre.57` and `Dart 2.0.0-dev.37.0.flutter-7328726088`.  Then launch one of these applications.

## Logs

```
 error - The function 'MaterialApp' isn't defined at lib\main.dart:7:10 - undefined_function
  error - The function 'StarWarsData' isn't defined at lib\main.dart:8:11 - undefined_function
  error - 'StarWarsState' isn't a function at lib\main.dart:14:34 - invocation_of_non_function
  error - 'Scaffold' isn't a function at lib\main.dart:35:12 - invocation_of_non_function
  error - 'AppBar' isn't a function at lib\main.dart:36:15 - invocation_of_non_function
  error - 'Text' isn't a function at lib\main.dart:37:16 - invocation_of_non_function  error - The method 'builder' isn't defined for the class 'ListView', but a constructor with that name is defined at lib\main.dart:40:22 - undefined_method_with_constructor
  error - 'Center' isn't a function at lib\main.dart:44:20 - invocation_of_non_function
  error - 'Column' isn't a function at lib\main.dart:45:22 - invocation_of_non_function
  error - 'Card' isn't a function at lib\main.dart:48:19 - invocation_of_non_function  error - 'Container' isn't a function at lib\main.dart:49:28 - invocation_of_non_function
  error - The method 'all' isn't defined for the class 'EdgeInsets', but a constructor with that name is defined at lib\main.dart:50:45 - undefined_method_with_constructor
  error - 'Row' isn't a function at lib\main.dart:51:32 - invocation_of_non_function
  error - 'Text' isn't a function at lib\main.dart:53:29 - invocation_of_non_function  error - 'Text' isn't a function at lib\main.dart:54:29 - invocation_of_non_function  error - 'TextStyle' isn't a function at lib\main.dart:55:40 - invocation_of_non_function
  error - 'Card' isn't a function at lib\main.dart:60:19 - invocation_of_non_function  error - 'Container' isn't a function at lib\main.dart:61:28 - invocation_of_non_function
  error - The method 'all' isn't defined for the class 'EdgeInsets', but a constructor with that name is defined at lib\main.dart:62:45 - undefined_method_with_constructor
  error - 'Row' isn't a function at lib\main.dart:63:32 - invocation_of_non_function
  error - 'Text' isn't a function at lib\main.dart:65:29 - invocation_of_non_function  error - 'Text' isn't a function at lib\main.dart:66:29 - invocation_of_non_function  error - 'TextStyle' isn't a function at lib\main.dart:67:40 - invocation_of_non_function
  error - 'Card' isn't a function at lib\main.dart:72:19 - invocation_of_non_function  error - 'Container' isn't a function at lib\main.dart:73:28 - invocation_of_non_function
  error - The method 'all' isn't defined for the class 'EdgeInsets', but a constructor with that name is defined at lib\main.dart:74:45 - undefined_method_with_constructor
  error - 'Row' isn't a function at lib\main.dart:75:32 - invocation_of_non_function
  error - 'Text' isn't a function at lib\main.dart:77:29 - invocation_of_non_function  error - 'Text' isn't a function at lib\main.dart:78:29 - invocation_of_non_function  error - 'TextStyle' isn't a function at lib\main.dart:79:40 - invocation_of_non_function
```

## Flutter Doctor
```
[√] Flutter (Channel master, v0.2.2-pre.57, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.2.2-pre.57 at C:\flutter
    • Framework revision 600739d195 (4 hours ago), 2018-03-15 12:06:37 -0700
    • Engine revision 520529dbba
    • Dart version 2.0.0-dev.37.0.flutter-7328726088
```

Edit:  Changing the channel to either dev or beta seems to fix this issue.

**Comment by mraleph** [comment] 2018-03-16 07:03
@devoncarew seems like regression in the analyzer?

**Comment by szotp** [comment] 2018-03-16 07:05
Just pulled master(c599662903d7ad8af2143fc0644a82bdebadb1ae) and have a lot of these:
`The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here`

**Comment by mraleph** [comment] 2018-03-16 13:30
@szotp these errror is due to #15590 - the feature was not implemented correctly so we temporary made it report an error in places where it would instead silently incorrectly insert `new`.

**Comment by devoncarew** [comment] 2018-03-16 14:03
@tensor-programming, just to confirm, you're seeing this issues from flutter analyze, and you're running it as `flutter analyze --preview-dart-2`?

**Comment by tensor-programming** [comment] 2018-03-18 13:43
Yeah i was using the --preview-dart-2 flag and also using the vs code dart 2 preview variable.  In both instances I was getting errors like this on the master branch.

**Comment by devoncarew** [comment] 2018-03-21 05:26
@tensor-programming, I'm unable to repro your issue. I'm:

- updating to the latest master
- `flutter create repro`
- from that project, remove a few `new` keywords
- run `flutter analyze`; I see no issues.

When I explicitly disable preview dart 2, I do see issues (which is expected):

```
[~/temp/repro] flutter analyze --no-preview-dart-2
Analyzing /Users/devoncarew/temp/repro...
  error • 'MaterialApp' isn't a function at lib/main.dart:9:12 • invocation_of_non_function
  error • 'ThemeData' isn't a function at lib/main.dart:11:14 • invocation_of_non_function
  error • 'Scaffold' isn't a function at lib/main.dart:67:12 • invocation_of_non_function
3 issues found.
```

As of a few hours ago, you should also see preview-dart-2 default to on for IDEs.

**Comment by devoncarew** [comment] 2018-03-21 05:26
Can you re-verify your steps and re-confirm the issue? Thanks!

**Comment by maryx** [comment] 2018-03-21 23:50
I'm able to repro this with this project: https://github.com/flutter/udacity-course

1. Check out master on Flutter
2. Run `flutter upgrade`
3. Run `flutter run --preview-dart-2`

```
I/FlutterActivityDelegate( 6487): onResume setting current activity to this
I/flutter ( 6487): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6487): The following _CompileTimeError was thrown building UnitConverterApp(dirty):
I/flutter ( 6487): 'file:///Users/maryxia/github-forks/udacity-course/unit_converter/unit_converter/lib/main.dart':
I/flutter ( 6487): error: line 33 pos 13: lib/main.dart:33:13: Error: The keyword 'const' or 'new' is required here.
I/flutter ( 6487): Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
I/flutter ( 6487):       home: CategoryRoute(),
I/flutter ( 6487):             ^
I/flutter ( 6487):       home: CategoryRoute(),
I/flutter ( 6487):             ^
I/flutter ( 6487): 
I/flutter ( 6487): When the exception was thrown, this was the stack:
I/flutter ( 6487): #0      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
I/flutter ( 6487): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter ( 6487): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6487): #3      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 6487): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 6487): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 6487): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 6487): #7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
I/flutter ( 6487): #8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
I/flutter ( 6487): #9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
I/flutter ( 6487): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
I/flutter ( 6487): #11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
I/flutter ( 6487): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
I/flutter ( 6487): #13     runApp (package:flutter/src/widgets/binding.dart:699:7)
I/flutter ( 6487): #14     main (file:///Users/maryxia/github-forks/udacity-course/unit_converter/unit_converter/lib/main.dart:11:3)
I/flutter ( 6487): #15     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter ( 6487): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 6487): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Android SDK built for x86...         2.6s
```

If instead of the master branch, I use commit `e1c38aa02` for Flutter, I don't have this issue.

**Comment by devoncarew** [comment] 2018-03-22 00:00
Yup - @maryx I think you're hitting https://github.com/flutter/flutter/issues/15590.

**Comment by tensor-programming** [comment] 2018-03-23 19:31
I am not sure if the problem is persisting on `Master` (because I changed channel to `Dev` after this issue first happened), but I am now seeing the problem on the `dev` channel.  I am running the project through VS code's Dart code extension with the `dart.previewDart2` variable set to true.  

Also, when I run the code in the terminal with `flutter run --preview-dart-2` I get the same errors.  

```The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.``` followed by the error I mentioned above is the error message that I generally see in these cases and its for basically every single widget in the program.  

I am using the latest windows version of flutter's dev channel: `Flutter 0.2.4 • channel dev • https://github.com/flutter/flutter.git`  with `Dart 2.0.0-dev.39.0.flutter-06949dc985`.

**Comment by devoncarew** [comment] 2018-03-23 22:59
@tensor-programming, thanks for all the investigation!

I believe this is a dupe of #15590 (and will close in favor of that issue). You'll hit this on master and dev, but won't see it on beta yet. I'm not sure of the eta for a fix, but best follow #15590 for that. Thanks!

**Closed by devoncarew** 2018-03-23 22:59 UTC
Labels: dart2, waiting for customer response

**Comment by tensor-programming** [comment] 2018-03-23 23:04
Is there anyway to roll back the SDK to the last `Dev` branch merge?  The beta is too far behind and it has bugs that make it impossible to hot reload using VS code's extension and the current `dev` and `master` have the issue mentioned above.

**Comment by devoncarew** [comment] 2018-03-23 23:08
Yup, the flutter sdk is just a git repo. From the command line, you can 'git checkout' any revision, and then run 'flutter doctor' or similar to get the right dart sdk and flutter engine artifacts for that revision.

**Comment by devoncarew** [comment] 2018-03-23 23:08
And you can find the git revisions for the releases here: https://github.com/flutter/flutter/releases

**Comment by tensor-programming** [comment] 2018-03-23 23:10
I know it is a git repo, just wasn't sure where I could find the release info.  Thank you for pointing me in the right direction.
