### ISSUE TITLE
All TextFields stops working after swipe back on page pushed by CupertinoPageRoute from inside CupertinoTabScaffold

### ISSUE THREAD

**Issue by edisonlsm** [flutter/flutter#44441] opened 2019-11-08 13:38 UTC
After pushing a page using CupertinoPageRoute from inside a CupertinoTabView/CupertinoTabScaffold and returning to the previous page with the swipe gesture all TextViews of the entire application stop working, you tap on them and the keyboard does not show.

- This happens on both Android and iOS, both with CupertinoApp and MaterialApp;
- If I push the page with CupertinoPageRoute from outside the CupertinoTabScaffold the error **DOES NOT** happen;
- The error happens **only** if I push to the root navigator. A push inside the tab works as expected;
- All TextViews stops working, even on pages created after the swipe;

I was able to reproduce the issue with the following basic app:
https://gist.github.com/edisonlsm/08819d18c58df3b0f818d2ef9de11356

## Steps to Reproduce

1. Run the app from the gist posted above.
2. Select the TextField and confirm it is working
3. Tap on "Push Page Two" button
4. Swipe back with the gesture from the left edge of the screen
5. Tap on the TextField again. The paste menu will open, but the keyboard will not show and you won't be able to insert text on the TextField.

## Logs

```
flutter analyze
Analyzing swipe_test...                                                 
No issues found! (ran in 2.7s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A602, locale pt-BR)
    • Flutter version 1.10.7 at /Users/edisonlsm/Library/flutter
    • Framework revision e70236e36c (5 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/edisonlsm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by spfannemueller** [comment] 2019-11-11 12:54
I'm having the same error #44298 .

**Comment by coreysprague** [comment] 2020-01-09 22:36
We just ran into this while upgrading too 1.12.13. @spfannemueller, have you had any luck in finding a workaround? We've just started digging in to try to find one.

**Comment by spfannemueller** [comment] 2020-01-24 11:44
@coreysprague it seems to be fixed in the current dev branch. Although I still don't know what caused this and how it was fixed.

**Comment by TahaTesser** [comment] 2020-03-26 15:45
Hi @edisonlsm 
Just tested your code sample on and couldn't reproduce on XR real device on IOS 13.4 

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.16.2 at /Users/taha/Code/flutter_dev
    • Framework revision 58cad787d8 (3 days ago), 2020-03-23 08:33:41 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • iPhone 11  • 41EB2A85-7EB4-4FD2-8978-FBBE2A681D74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.4 19E266
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 80.0.3987.149
    • Web Server • web-server                           • web-javascript •
      Flutter Tools

• No issues found!
```

Could everyone still facing this issue with latest version of Flutter
 can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Closed** 2020-03-26 15:51 UTC
Labels: a: text input, f: cupertino, f: material design, f: routes, framework, has reproducible steps
