### ISSUE TITLE
[Android] Check failed: entry.encountered_this_frame

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#121678] opened 2023-03-01 09:44 UTC
An assertion error occurred when running the platform view demo in `Hybrid Composition` mode using the Flutter engine compiled with the `--unopt` option.

```
F/flutter ( 9363): [FATAL:flutter/flow/raster_cache.cc(173)] Check failed: entry.encountered_this_frame. 
F/libc    ( 9363): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9363 (iew_performance), pid 9363 (iew_performance)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/GLK-AL00/HWGLK:10/HUAWEIGLK-AL00/102.0.0.291C00:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2023-03-01 11:29:40+0800
pid: 9363, tid: 9363, name: iew_performance  >>> com.example.platform_view_performance <<<
uid: 10000
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/flow/raster_cache.cc(173)] Check failed: entry.encountered_this_frame. 
'
    r0  00000000  r1  00002493  r2  00000006  r3  ff88aad8
    r4  ff88aaec  r5  ff88aad0  r6  00002493  r7  0000016b
    r8  ff88aae8  r9  ff88aad8  r10 ff88ab08  r11 ff88aaf8
    ip  00002493  sp  ff88aaa8  lr  eec5e58f  pc  eec5e5a2
backtrace:
      #00 pc 000545a2  /apex/com.android.runtime/lib/bionic/libc.so (abort+166) (BuildId: b3a547af3eb880c5dfd66f61a8c8b4ca)
      #01 pc 0190d39f  /data/app/com.example.platform_view_performance-vFJOpTBSorDKwQ77wkvCGA==/lib/arm/libflutter.so (BuildId: 783146b3cd0b3bfbbd44766127f943f5a8ec518a)
Lost connection to device.
```

## Steps to Reproduce

<img width="300" alt="screenshot" src="https://user-images.githubusercontent.com/26625149/222101473-ab7266a0-415a-4035-8f98-0c609ac82807.png">

1. Compile the Flutter engine using the `--unopt` option.
2. Get test code: `git clone git@github.com:0xZOne/platform_view_performance.git`
3. Execute `flutter run --local-engine-src-path=/Users/zero/Dev/GitHub/engine/src --local-engine=android_debug_unopt` 
4. Enable `Hybrid Composition` mode as shown in the picture.
5. Tap on `List View` or `Matrix Transform` and see a crash

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel main, 3.8.0-18.0.pre.4, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.8.0-18.0.pre.4 on channel main at /Users/zero/fvm/versions/main
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 87679ff1c3 (19 hours ago), 2023-02-28 10:31:51 +0200
    • Engine revision b78ac04129
    • Dart version 3.0.0 (build 3.0.0-277.0.dev)
    • DevTools version 2.22.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/zero/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/zero/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/zero/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • GLK AL00 (mobile) • PWHUT20514014877 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 110.0.5481.177

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jason-simmons** [comment] 2023-03-02 02:48
This is another issue involving the raster thread merger.

`CompositorContext::ScopedFrame::Raster` calls the external view embedder's `PostPrerollAction`.  When the issue happens, `AndroidExternalViewEmbedder::PostPrerollAction` invokes the thread merger and returns `kSkipAndRetryFrame`.

With the threads merged, a queued rasterizer task calls `Rasterizer::Draw` again on the platform thread.  This time, `ScopedFrame::Raster` gets a `kResubmit` response from the external view embedder.  `ScopedFrame::Raster` then exits without calling `LayerTree::Paint` (which would call `RasterCache::EvictUnusedCacheEntries`)

The rasterizer later calls `RasterCache::EndFrame`, which updates the cache metrics and checks the assertion verifying that all remaining cache entries have the `encountered_this_frame` flag set.  But in this case, there was no call to `EvictUnusedCacheEntries`, so there are still entries in the cache where that flag is clear.

`Rasterizer::DrawToSurfaceUnsafe` will exit and avoid the call to `EndFrame` if `ScopedFrame::Raster` returns `kFailed` or `kSkipAndRetry`.

I suspect that the rasterizer should do the same for `kResubmit`.  I tried patching the rasterizer to do that and confirmed that this application works as expected.

@iskakaushik @chinmaygarde

**Comment by reidbaker** [comment] 2023-03-02 19:24
Assigned to Jason and labeled p4 since Jason already has a pull request up for it.

**Closed** 2023-03-03 01:12 UTC
Labels: platform-android, engine, a: platform-views, P4, hc-only
