### ISSUE TITLE
[Android] App crashes after moving the app to background

### ISSUE THREAD

**Issue by atrope** [flutter/flutter#96875] opened 2022-01-19 20:30 UTC
Hello, we have a major regression with latest Flutter 2.8+ and HybridViews in Android < 10.

using  `await PlatformViewsService.synchronizeToNativeViewHierarchy(false);` every action that makes the app go to background (for example clicking the ad, or sharing some content) makes the app crash.

Removing the line or Downgrading flutter seems to fix the issue but i consider this a major regression considering it was introduced by Flutter 2.8+ and it is now the recommended way of having inline ads on older devices..

Here is the example app, just run it on Old Android and click the button or the Example banner.

https://github.com/atrope/my_app

<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchWindowVisibilityChanged(int)' on a null object reference
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1660)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1348)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6865)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
       at android.view.Choreographer.doCallbacks(Choreographer.java:699)
       at android.view.Choreographer.doFrame(Choreographer.java:634)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6351)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
```
</details>

**Comment by maheshmnj** [comment] 2022-01-20 08:32
Hi @atrope, Thanks for filing the issue. I was able to reproduce the app crash on Xiaomi k20 pro (Android 11) after moving the app to the background. The issue is reproducible on both stable and the master channel and I couldn't verify the app on `stable 2.5.3` the app fails to build with AAR dependency conflicts

<details>
<summary>logs</summary>

```console
mahesh@Maheshs-MacBook-Air-M1 my_app % flutter run                
Could not load custom device from config index 0: Expected enabled to be a boolean.
Running "flutter pub get" in my_app...                              3.9s
Launching lib/main.dart on Redmi K20 Pro in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Running Gradle task 'assembleDebug'...                            146.6s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                24.2s
W/ConnectionStatusConfig(11395): Dynamic lookup for intent failed for action: com.google.android.gms.leibniz.events.service.START
W/GmsClient(11395): unable to connect to service: com.google.android.gms.leibniz.events.service.START on com.google.android.gms
I/WebViewFactory(11395): Loading com.google.android.webview version 97.0.4692.98 (code 469209833)
W/.example.my_ap(11395): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/.example.my_ap(11395): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/.example.my_ap(11395): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/.example.my_ap(11395): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/.example.my_ap(11395): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(11395): Loaded version=97.0.4692.98 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(11395): Successfully loaded native library
I/cr_CachingUmaRecorder(11395): Flushed 8 samples from 8 histograms.
E/libc    (11395): Access denied finding property "ro.vendor.df.effect.conflict"
E/libc    (11395): Access denied finding property "ro.vendor.knock.type"
W/AdWorker(Defaul(11395): type=1400 audit(0.0:1028964): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=28867 scontext=u:r:untrusted_app:s0:c225,c259,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.android.providers.calendar
I/AudioManager(11395): In isSpeakerphoneOn(), calling application: com.example.my_app
W/.example.my_ap(11395): ClassLoaderContext classpath element mismatch. expected=/data/app/~~a8RHQ8rG6xtPsljVry1lHg==/com.example.my_app-zASVyGliL6oqG5O4P0repg==/base.apk, found=/data/app/~~1Vx9X217Q1OGpgPsqr5qzg==/com.example.my_app-dUdrF-_-6_V51FDfXtGR_w==/base.apk (PCL[];PCL[/data/app/~~a8RHQ8rG6xtPsljVry1lHg==/com.example.my_app-zASVyGliL6oqG5O4P0repg==/base.apk*1297728736] | PCL[];PCL[/data/app/~~1Vx9X217Q1OGpgPsqr5qzg==/com.example.my_app-dUdrF-_-6_V51FDfXtGR_w==/base.apk*747580480])
W/.example.my_ap(11395): ClassLoaderContext classpath element mismatch. expected=/data/app/~~a8RHQ8rG6xtPsljVry1lHg==/com.example.my_app-zASVyGliL6oqG5O4P0repg==/base.apk, found=/data/app/~~1Vx9X217Q1OGpgPsqr5qzg==/com.example.my_app-dUdrF-_-6_V51FDfXtGR_w==/base.apk (PCL[];PCL[/data/app/~~a8RHQ8rG6xtPsljVry1lHg==/com.example.my_app-zASVyGliL6oqG5O4P0repg==/base.apk*1297728736] | PCL[];PCL[])
I/.example.my_ap(11395): ProcessProfilingInfo new_methods=1872 is saved saved_to_disk=1 resolve_classes_delay=8000
W/AdWorker(Defaul(11395): type=1400 audit(0.0:1028965): avc: granted { execute } for path="/data/data/com.example.my_app/app_pccache/5/20434A7F4C8550FFAA683956EA0AF945095CF79B/pcam.jar" dev="sda31" ino=3957547 scontext=u:r:untrusted_app:s0:c225,c259,c512,c768 tcontext=u:object_r:app_data_file:s0:c225,c259,c512,c768 tclass=file app=com.android.providers.calendar
W/Ads     (11395): Update ad debug logging enablement as false
D/EgretLoader(11395): EgretLoader(Context context)
D/EgretLoader(11395): The context is not activity
W/.example.my_ap(11395): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
E/chromium(11395): [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/com.example.my_app/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
E/chromium(11395): [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
W/cr_media(11395): Requires BLUETOOTH permission
Syncing files to device Redmi K20 Pro...                           461ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Redmi K20 Pro is available at:
http://127.0.0.1:51856/xU1lBiA29QM=/
The Flutter DevTools debugger and profiler on Redmi K20 Pro is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:51856/xU1lBiA29QM=/
D/EgretLoader(11395): EgretLoader(Context context)
D/EgretLoader(11395): The context is not activity
D/EgretLoader(11395): EgretLoader(Context context)
D/EgretLoader(11395): The context is not activity
I/flutter (11395): loaded.
W/ContentCatcher(11395): Failed to notify a WebView
D/MIUIInput(11395): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=568569861, downTime=568569861 } moveCount:0
W/MirrorManager(11395): this model don't Support
D/MIUIInput(11395): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=568569943, downTime=568569861 } moveCount:0
I/Timeline(11395): Timeline: Activity_launch_request time:568569983
D/AndroidRuntime(11395): Shutting down VM
E/AndroidRuntime(11395): FATAL EXCEPTION: main
E/AndroidRuntime(11395): Process: com.example.my_app, PID: 11395
E/AndroidRuntime(11395): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchWindowVisibilityChanged(int)' on a null object reference
E/AndroidRuntime(11395):        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1641)
E/AndroidRuntime(11395):        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1641)
E/AndroidRuntime(11395):        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1641)
E/AndroidRuntime(11395):        at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1641)
E/AndroidRuntime(11395):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2547)
E/AndroidRuntime(11395):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2065)
E/AndroidRuntime(11395):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8495)
E/AndroidRuntime(11395):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
E/AndroidRuntime(11395):        at android.view.Choreographer.doCallbacks(Choreographer.java:897)
E/AndroidRuntime(11395):        at android.view.Choreographer.doFrame(Choreographer.java:826)
E/AndroidRuntime(11395):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
E/AndroidRuntime(11395):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(11395):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11395):        at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(11395):        at android.app.ActivityThread.main(ActivityThread.java:8061)
E/AndroidRuntime(11395):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11395):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(11395):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
I/Process (11395): Sending signal. PID: 11395 SIG: 9
Lost connection to device.
mahesh@Maheshs-MacBook-Air-M1 my_app % 
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.398, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.398 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8017883a5d (28 hours ago), 2022-01-18 23:04:01 -0500
    • Engine revision 7a33b4b3fb
    • Dart version 2.17.0 (build 2.17.0-27.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

> NPE Regression with Flutter 2.8+ Old Androids and HybridViews

ps: Sorry if I am missing any context, What exactly is "NPE" ?

**Comment by maheshmnj** [comment] 2022-01-20 08:49
cc: @blasten

**Comment by atrope** [comment] 2022-01-20 09:54
@maheshmnj NPE = NullPointerException :)

**Comment by kolbasan** [comment] 2022-01-28 13:12
This is a major issue to us as well. 
Had to halt production rollout and we can't push further updates without downgrading flutter.
We were forced to use `await PlatformViewsService.synchronizeToNativeViewHierarchy(false)` since we had multiple user complaints on performance issues and this was the only way to fix it (https://github.com/googleads/googleads-mobile-flutter/issues/297)

**Comment by blasten** [comment] 2022-01-28 16:47
I’m working on a general solution to the performance issue, and the removal of this flag. Stayed tune.

**Comment by doctek235** [comment] 2022-02-09 10:10
>We were forced to use await PlatformViewsService.synchronizeToNativeViewHierarchy(false) since we had multiple user complaints on performance issues and this was the only way to fix it (https://github.com/googleads/googleads-mobile-flutter/issues/297)

Hello @kolbasan! Could you please let me know is this workaround applicable to Flutter 2.10 or you didn't update your app to last version yet?

>I’m working on a general solution

@blasten we'll be thankful even for temporar workaround. We're stuck with 2.5.3 😁

**Comment by Naografix** [comment] 2022-02-11 17:32
Put a little flag here, I got the same issue:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchWindowVisibilityChanged(int)' on a null object reference
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1614)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1614)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1614)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1614)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1614)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2451)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8190)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
       at android.view.Choreographer.doCallbacks(Choreographer.java:796)
       at android.view.Choreographer.doFrame(Choreographer.java:731)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Lot of users says they have the problem:
_The crashes seem to be caused by the app not being able to stay in background memory, when switching between different apps. Like the device is low on memory. For example if I open another app and switch between yours and another one, 30% of the time when I open MYAPP again it will completely refresh the app and sometimes I'll get a notification stating "MYAPP keeps closing". _

Thank you

**Comment by Naografix** [comment] 2022-02-13 14:37
Any news about this fatal bug? Thank you

**Comment by ozzy1873** [comment] 2022-02-13 14:54
Are you still seeing this in Flutter 2.10.1 ?

**Comment by Naografix** [comment] 2022-02-16 12:42
@ozzy1873 , hey!II have not tried with version 2.10.1. I looked at the changelog and I didn't see any improvement regarding this crash.

**Comment by xiejinpeng007** [comment] 2022-02-17 02:31
I have the same problem in version 2.10.0

**Comment by doctek235** [comment] 2022-02-17 07:56
I can confirm that the problem still exists in 2.10.1. We use cirrusci/flutter image in CI/CD pipelines but it should be the same in usual enviroments.
I have to mention that you're able to repeat it only in release-build but not in debug.

And as long as we have the function to "hide ads" I am not able to repeat the problem when google mobile ads package "disabled".
It could be possible workaround if you can afford to leave without ads until this issue will be resolved.

I hope @blasten didn't forget about us 😁

**Comment by Naografix** [comment] 2022-02-21 20:35
Any fix?

**Comment by Naografix** [comment] 2022-02-21 20:38
@blasten Any updates?

**Comment by TheJulianJES** [comment] 2022-02-22 23:39
Issue also present in 2.11.0-0.1.pre.
I'm only using the standard WebView (which now uses Hybrid Composition instead of Virtual Displays) and I've seen crashes where a user opened a WebView, closed the WebView with the app only crashing after it was minimized.
I'm **not** using ``await PlatformViewsService.synchronizeToNativeViewHierarchy(false);`` anywhere.

Crashes seem to happen on many Android versions: Galaxy J4+ with Android 9, Galaxy A51 with Android 10, Galaxy A50 with Android 11, Galaxy S21 5G with Android 12, Redmi Note 8 Pro with Android 11.

**Comment by BajieSaveMe** [comment] 2022-03-06 02:45
Any updates in version 2.10.3? Thank you

**Comment by EArminjon** [comment] 2022-03-06 18:34
I've deployed my app with flutter 2.10.3 and got this on crashlytics, issue persist : 

```
main (native): tid=1 systid=21769
#00 pc 0x86b8c libc.so 
#01 pc 0x1b092c libart.so 
#02 pc 0x3a8290 libart.so 
#03 pc 0x4040 libnativehelper.so 
#04 pc 0xedbe4 libandroid_runtime.so 
#05 pc 0x92500 libgui.so 
#06 pc 0x19da8 libutils.so 
#07 pc 0x199ac libutils.so 
#08 pc 0x118450 libandroid_runtime.so 
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:206)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Naografix** [comment] 2022-03-07 11:35
@blasten :) hey!

**Comment by jason-simmons** [comment] 2022-03-10 02:56
Verified that the app in https://github.com/flutter/flutter/issues/96875#issue-1108526962 is working as expected with an engine build containing https://github.com/flutter/engine/commit/4dd7eb7cfa210332f48e5ac1a220f114f2902a38 and https://github.com/flutter/engine/commit/7b5edec4cd13fd948fa12c0cacdf5d1852b0149f

These fixes are available in 2.10.3 and on the master branch.

**Comment by EArminjon** [comment] 2022-03-10 07:53
> Any updates in version 2.10.3? Thank you

I can confirm, this issue has been fixed, I deploy my app last week and today the issue did not reappear.

**Comment by doctek235** [comment] 2022-03-10 15:53
I can confirm that 2.10.3 is fixing the issue (circleci image). We're experiencing some performance downgrade (some flickering when changing screens) but it could be unrelated to this issue. 

No crashes and this is what we need.
Thanks a lot!

**Comment by maheshmnj** [comment] 2022-03-11 05:30
> We're experiencing some performance downgrade (some flickering when changing screens) but it could be unrelated to this issue.

The issue you are referring to could be related to https://github.com/flutter/flutter/issues/95343

**Comment by ozzy1873** [comment] 2022-04-02 12:18
@Naografix Are you still seeing this issue?

**Comment by Naografix** [comment] 2022-04-02 14:43
> @Naografix Are you still seeing this issue?

In version 2.10.3 I don't feel like I have the problem anymore

**Comment by blasten** [comment] 2022-04-28 23:12
This issue is fixed in the master channel.
`synchronizeToNativeViewHierarchy` is no longer necessary.

**Closed by blasten** 2022-04-28 23:13 UTC
Labels: severe: crash, platform-android, engine, a: platform-views, p: third party, has reproducible steps, P4, found in release: 2.8, found in release: 2.9
