### ISSUE TITLE
[web]: Mouse Hover (without mouse down) is a MUST for Flutter Web

### ISSUE THREAD

**Issue by boeledi** [flutter/flutter#34126] opened 2019-06-09 09:38 UTC
Mouse Events such as (e.g. onMouseEnter, onMouseExit, onMouseHover) should be supported by Flutter Web **without** the "mouse is down" condition.

This is an important feature for all devices with mouse support if we want Flutter Web to fully be adopted by the Web Developers Community.

I admit that this represents some changes/refactoring (among others **PointerEventConverter**, **PointerAdapter** ...) and a potential impact on performance, however, I do believe that something should be done at that level.

Many thanks in advance,

**Comment by stuartmorgan** [comment] 2019-06-09 13:09
Closing as a duplicate of #33707

**Closed by stuartmorgan** 2019-06-09 13:09 UTC

**Comment by boeledi** [comment] 2019-06-09 14:09
This is not a duplicate... this ticket refers to the need to handle mouse events WITHOUT having to hold the mouse button down...

**Comment by kenthinson** [comment] 2019-06-20 03:36
@boeledi please read #33707. You will see it is a duplicate. We are talking about the same thing. It's a bug that Listener() doesn't work correctly (without mouse held down). Listener() is the correct Widget to use for what you want but it doesn't work it's bugged.
