### ISSUE TITLE
PlatformException (PlatformException(sign_in_canceled, com.google.android.gms.common.api.ApiException: 12501: , null))

### ISSUE THREAD

**Issue by TMaxedCode** [flutter/flutter#54945] opened 2020-04-16 09:54 UTC
## Steps to Reproduce
Use google_sign_in package to sign in with google. 

**Expected results:** 
Canceling Google Sign In button makes you go back to the login page.
**Actual results:** 
Canceling Google Sign In button throws an exception.

I saw @ffpetrovic's solution in #48879 and he said that his solution works for this problem. Can you check it out? 

> Regarding issue no. 4, I had to copy the `google_sign_in.dart` file from the library, and make it a local widget. Then I edited the `_callMethod` method to this, (just added a try/catch block)
> 
> ```
>   Future<GoogleSignInAccount> _callMethod(String method) async {
>     try {
>       await _ensureInitialized();
> 
>       final Map<dynamic, dynamic> response = await channel.invokeMethod(method);
>       return _setCurrentUser(response != null && response.isNotEmpty
>           ? GoogleSignInAccount._(this, response)
>           : null);
>     } catch (e) {
>       return null;
>     }
>   }
> ```
> 
> ^^^ This should be handled better, but I see this having lower priority because the root issue should be solved first by the authors, because right now the library makes the app crash (unless you hack it like shown above), on a very expected user scenario.

**Comment by TahaTesser** [comment] 2020-04-16 10:15
Hi @TMaxedCode 
if the proposed solution doesn't work, issue is already open
Duplicate of [#48879](https://github.com/flutter/flutter/issues/48879)

**Closed by TahaTesser** 2020-04-16 10:15 UTC

**Comment by TMaxedCode** [comment] 2020-04-16 10:37
@TahaTesser How do I implement his solution? I can't change the code of the package since I don't own it.

**Comment by ffpetrovic** [comment] 2020-04-19 01:15
@TMaxedCode It says in the snippet you quoted what you have to do, although it's a terrible, terrible solution. If it makes you feel better, this just... stopped happening to me, and also, this only happens in **debug** mode, and **not in production mode.** I agree it can be a huge inconvenience, but the chances are you probably won't need to test this case (where the user cancels the login flow).

**Comment by TMaxedCode** [comment] 2020-04-19 03:43
@ffpetrovic Ok, thank you. I think I don't have to try to fix it anymore.

**Comment by paulkastel** [comment] 2020-04-20 08:13
@TahaTesser This ticket relates to #44431, valid for version of plugin 4.3.0 (and probably newer)
