### ISSUE TITLE
Issue with NestedScrollView + TabBarView in Flutter web

### ISSUE THREAD

**Issue by jcblancomartinez** [flutter/flutter#101320] opened 2022-04-04 22:00 UTC
## Steps to Reproduce

1. Execute `flutter run` for web.
2. Scroll down in Sliver Tab 1 using the scroll bar.
4. Change to Sliver Tab 2.
5. Try to scroll down in Sliver Tab 2 using the scroll bar.

**Expected results:** 
I would expect to be able to scroll down in Sliver Tab 2 using the scroll bar.

**Actual results:** 

No scroll bar in Sliver Tab 2 is present and exceptions are thrown (see Logs below).

https://user-images.githubusercontent.com/1192455/161638524-69e97965-7790-4b5a-8c35-b9675f8f9656.mp4

In [NestedScrollView's documentation](https://github.com/flutter/flutter/blob/ab89ce285f76a3fd3a9328ec863f5623cc5ac8bc/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L251-L261), it is suggested not to pass any controller to the ListViews, however, for web, that is causing issues with their corresponding ScrollBars.

```
  /// The widget to show inside the [NestedScrollView].
  ///
  /// Typically this will be [TabBarView].
  ///
  /// The [body] is built in a context that provides a [PrimaryScrollController]
  /// that interacts with the [NestedScrollView]'s scroll controller. Any
  /// [ListView] or other [Scrollable]-based widget inside the [body] that is
  /// intended to scroll with the [NestedScrollView] should therefore not be
  /// given an explicit [ScrollController], instead allowing it to default to
  /// the [PrimaryScrollController] provided by the [NestedScrollView].
  final Widget body;
```

**Proposal:**

NestedScrollView should support X number of controllers and X number of scrollbars, one per each TabBar. 

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: 2,
        child: Scaffold(
            body: NestedScrollView(
                headerSliverBuilder:
                    (BuildContext context, bool innerBoxIsScrolled) {
                  return [
                    SliverToBoxAdapter(
                      child: Container(
                        height: 200,
                        color: Colors.black12,
                        child: const Center(child: Text('Sliver 1')),
                      ),
                    ),
                    const SliverToBoxAdapter(
                        child: Center(
                      child: TabBar(
                        labelColor: Colors.black,
                        tabs: [
                          Tab(text: 'Sliver Tab 1'),
                          Tab(text: 'Sliver Tab 2'),
                        ],
                      ),
                    )),
                  ];
                },
                body: TabBarView(
                  children: [
                    ListView.builder(
                        // controller: ScrollController(),
                        itemCount: 1000,
                        itemBuilder: (context, index) => Container(
                              height: 50,
                              color: index.isEven ? Colors.red : Colors.white,
                              child: AliveKeeper(index: index),
                            )),
                    ListView.builder(
                        // controller: ScrollController(),
                        itemCount: 1000,
                        itemBuilder: (context, index) => Container(
                              height: 50,
                              color: index.isEven ? Colors.blue : Colors.white,
                              child: AliveKeeper(index: index),
                            ))
                  ],
                ))));
  }
}

class AliveKeeper extends StatefulWidget {
  int index;

  AliveKeeper({
    required this.index,
    GlobalKey? key,
  }) : super(key: key);

  @override
  AliveKeeperState createState() => AliveKeeperState();
}

class AliveKeeperState extends State<AliveKeeper>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Text('Item ${widget.index}');
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Launching lib/main3.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:34933/UVXaMNTWrJY=/ws
Debug service listening on ws://127.0.0.1:34933/UVXaMNTWrJY=/ws

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:34933/UVXaMNTWrJY=/ws
WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/widgets/scrollbar.dart 1333:9                            <fn>
packages/flutter/src/widgets/scrollbar.dart 1356:14                           [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1272:14                           [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                   notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 815:7                [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 749:5                [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 612:12               [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 494:12               reverse
packages/flutter/src/widgets/scrollbar.dart 1451:37                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback
The AnimationController notifying status listeners was: AnimationController#9810e(◀ 1.000)
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
packages/flutter/src/widgets/scrollbar.dart 1333:9                                <fn>
packages/flutter/src/widgets/scrollbar.dart 1356:14                               [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1272:14                               [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                       notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 815:7                    [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 749:5                    [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 612:12                   [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 461:12                   forward
packages/flutter/src/widgets/scrollbar.dart 1642:46                               [_handleScrollNotification]
packages/flutter/src/widgets/notification_listener.dart 151:27                    [_dispatch]
packages/flutter/src/widgets/notification_listener.dart 67:19                     visitAncestor
packages/flutter/src/widgets/scroll_notification.dart 31:18                       visitAncestor
packages/flutter/src/widgets/framework.dart 4254:39                               visitAncestorElements
packages/flutter/src/widgets/notification_listener.dart 83:13                     dispatch
packages/flutter/src/widgets/scroll_activity.dart 94:90                           dispatchScrollUpdateNotification
packages/flutter/src/widgets/scroll_position.dart 900:5                           didUpdateScrollPositionBy
packages/flutter/src/widgets/nested_scroll_view.dart 1289:5                       applyClampedPointerSignalUpdate
packages/flutter/src/widgets/nested_scroll_view.dart 930:21                       pointerScroll
packages/flutter/src/widgets/nested_scroll_view.dart 1384:24                      pointerScroll
packages/flutter/src/widgets/scrollable.dart 717:16                               [_handlePointerScroll]
packages/flutter/src/gestures/pointer_signal_resolver.dart 88:7                   resolve
packages/flutter/src/gestures/binding.dart 445:29                                 handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 322:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                 [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1026:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 184:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 295:14                                    [_handleWheelEvent]
lib/_engine/engine/pointer_binding.dart 559:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 284:84                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
The AnimationController notifying status listeners was: AnimationController#9810e(▶ 0.000)
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
packages/flutter/src/widgets/scrollbar.dart 1333:9                                <fn>
packages/flutter/src/widgets/scrollbar.dart 1356:14                               [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1272:14                               [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                       notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 815:7                    [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 749:5                    [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 612:12                   [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 461:12                   forward
packages/flutter/src/widgets/scrollbar.dart 1642:46                               [_handleScrollNotification]
packages/flutter/src/widgets/notification_listener.dart 151:27                    [_dispatch]
packages/flutter/src/widgets/notification_listener.dart 67:19                     visitAncestor
packages/flutter/src/widgets/scroll_notification.dart 31:18                       visitAncestor
packages/flutter/src/widgets/framework.dart 4254:39                               visitAncestorElements
packages/flutter/src/widgets/notification_listener.dart 83:13                     dispatch
packages/flutter/src/widgets/scroll_activity.dart 94:90                           dispatchScrollUpdateNotification
packages/flutter/src/widgets/scroll_position.dart 900:5                           didUpdateScrollPositionBy
packages/flutter/src/widgets/nested_scroll_view.dart 1289:5                       applyClampedPointerSignalUpdate
packages/flutter/src/widgets/nested_scroll_view.dart 930:21                       pointerScroll
packages/flutter/src/widgets/nested_scroll_view.dart 1384:24                      pointerScroll
packages/flutter/src/widgets/scrollable.dart 717:16                               [_handlePointerScroll]
packages/flutter/src/gestures/pointer_signal_resolver.dart 88:7                   resolve
packages/flutter/src/gestures/binding.dart 445:29                                 handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 322:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                 [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1026:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 184:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 295:14                                    [_handleWheelEvent]
lib/_engine/engine/pointer_binding.dart 559:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 284:84                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
The AnimationController notifying status listeners was: AnimationController#b52a3(▶ 0.000)
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/widgets/scrollbar.dart 1333:9                            <fn>
packages/flutter/src/widgets/scrollbar.dart 1356:14                           [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1272:14                           [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                   notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 815:7                [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 831:5                [_tick]
packages/flutter/src/scheduler/ticker.dart 238:12                             [_tick]
packages/flutter/src/scheduler/binding.dart 1144:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1057:106                          <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/scheduler/binding.dart 1055:16                           handleBeginFrame
packages/flutter/src/scheduler/binding.dart 974:5                             [_handleBeginFrame]
lib/_engine/engine/platform_dispatcher.dart 1026:13                           invoke1
lib/_engine/engine/platform_dispatcher.dart 138:5                             invokeOnBeginFrame
lib/_engine/engine/initialization.dart 119:45                                 <fn>
The AnimationController notifying status listeners was: AnimationController#9810e(⏭ 1.000; paused)
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/widgets/scrollbar.dart 1333:9                            <fn>
packages/flutter/src/widgets/scrollbar.dart 1356:14                           [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1272:14                           [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                   notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 815:7                [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 831:5                [_tick]
packages/flutter/src/scheduler/ticker.dart 238:12                             [_tick]
packages/flutter/src/scheduler/binding.dart 1144:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1057:106                          <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/scheduler/binding.dart 1055:16                           handleBeginFrame
packages/flutter/src/scheduler/binding.dart 974:5                             [_handleBeginFrame]
lib/_engine/engine/platform_dispatcher.dart 1026:13                           invoke1
lib/_engine/engine/platform_dispatcher.dart 138:5                             invokeOnBeginFrame
lib/_engine/engine/initialization.dart 119:45                                 <fn>
The AnimationController notifying status listeners was: AnimationController#b52a3(⏭ 1.000; paused)
====================================================================================================

```

```
```

```
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.3 LTS 5.13.0-37-generic, locale en_US.UTF-8)
    • Flutter version 2.10.4 at /home/juancarlos/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /home/juancarlos/Android/Sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • Java binary at: /home/juancarlos/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/juancarlos/android-studio
    • Flutter plugin version 61.2.3
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by jcblancomartinez** [comment] 2022-04-05 07:38
I've found this [comment](https://github.com/flutter/flutter/issues/89864#issuecomment-925179768) from @Piinks where she suggests to instantiate a different controller for each ListView, however, when doing so the behavior changes. When scrolling down from the List View, the sliver remains visible.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: 2,
        child: Scaffold(
            body: NestedScrollView(
                headerSliverBuilder:
                    (BuildContext context, bool innerBoxIsScrolled) {
                  return [
                    SliverToBoxAdapter(
                      child: Container(
                        height: 200,
                        color: Colors.black12,
                        child: const Center(child: Text('Sliver 1')),
                      ),
                    ),
                    const SliverToBoxAdapter(
                        child: Center(
                      child: TabBar(
                        labelColor: Colors.black,
                        tabs: [
                          Tab(text: 'Sliver Tab 1'),
                          Tab(text: 'Sliver Tab 2'),
                        ],
                      ),
                    )),
                  ];
                },
                body: TabBarView(
                  children: [
                    ListView.builder(
                        controller: ScrollController(),
                        itemCount: 1000,
                        itemBuilder: (context, index) => Container(
                              height: 50,
                              color: index.isEven ? Colors.red : Colors.white,
                              child: AliveKeeper(index: index),
                            )),
                    ListView.builder(
                        controller: ScrollController(),
                        itemCount: 1000,
                        itemBuilder: (context, index) => Container(
                              height: 50,
                              color: index.isEven ? Colors.blue : Colors.white,
                              child: AliveKeeper(index: index),
                            ))
                  ],
                ))));
  }
}

class AliveKeeper extends StatefulWidget {
  int index;

  AliveKeeper({
    required this.index,
    GlobalKey? key,
  }) : super(key: key);

  @override
  AliveKeeperState createState() => AliveKeeperState();
}

class AliveKeeperState extends State<AliveKeeper>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Text('Item ${widget.index}');
  }
}
```

</details>

https://user-images.githubusercontent.com/1192455/161702604-8c813f12-2274-4c93-8bc6-ff22449f970d.mp4

@Piinks Is there any way to achieve the same behavior as in the video [here](https://github.com/flutter/flutter/issues/101320#issue-1192358337) but making scroll bars work in web for both ListViews?.

Thanks.

**Comment by darshankawar** [comment] 2022-04-05 08:39
@jcblancomartinez 
Adding `controller: ScrollController(),` seems to resolve the exception. 
See [this](https://github.com/flutter/flutter/issues/88428) original issue for your reference and [this](https://github.com/flutter/flutter/issues/88428#issuecomment-901490859) comment from it and check if it helps.

**Comment by jcblancomartinez** [comment] 2022-04-05 08:45
@darshankawar

Thanks for looking into this.

As mentioned [here](https://github.com/flutter/flutter/issues/101320#issuecomment-1088365656) I understand how to fix the error but the proposed fix also changes the behaviour of the scrolling. "When scrolling down from the List View, the sliver remains visible."

Can you please suggest al alternative to get the same behaviour but without the exceptions?

Thanks.

**Comment by jcblancomartinez** [comment] 2022-04-05 09:56
The following is the closest that I've got to the expected behavior but it is not yet there.

- Scrollbar can't be use to scroll within the ListViews.
- When down in the ListView (i.e. Item 100) and click on the scrollbar, we automatically get to the Item 0. Expected is that we should remain where we are.


https://user-images.githubusercontent.com/1192455/161729122-922e3a7f-abce-4110-8cd7-c248146bd06e.mp4



<details>
<summary>Code sample</summary>


```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: 2,
        child: Scaffold(
            body: NestedScrollView(
                scrollBehavior:
                    ScrollConfiguration.of(context).copyWith(scrollbars: true),
                headerSliverBuilder:
                    (BuildContext context, bool innerBoxIsScrolled) {
                  return [
                    SliverToBoxAdapter(
                      child: Container(
                        height: 200,
                        color: Colors.black12,
                        child: const Center(child: Text('Sliver 1')),
                      ),
                    ),
                    const SliverToBoxAdapter(
                        child: Center(
                      child: TabBar(
                        labelColor: Colors.black,
                        tabs: [
                          Tab(text: 'Sliver Tab 1'),
                          Tab(text: 'Sliver Tab 2'),
                        ],
                      ),
                    )),
                  ];
                },
                body: TabBarView(
                  children: [
                    ScrollConfiguration(
                        behavior: ScrollConfiguration.of(context)
                            .copyWith(scrollbars: false),
                        child: ListView.builder(
                            itemCount: 1000,
                            itemBuilder: (context, index) => Container(
                                  height: 50,
                                  color:
                                      index.isEven ? Colors.red : Colors.white,
                                  child: AliveKeeper(index: index),
                                ))),
                    ScrollConfiguration(
                        behavior: ScrollConfiguration.of(context)
                            .copyWith(scrollbars: false),
                        child: ListView.builder(
                            itemCount: 1000,
                            itemBuilder: (context, index) => Container(
                                  height: 50,
                                  color:
                                      index.isEven ? Colors.blue : Colors.white,
                                  child: AliveKeeper(index: index),
                                )))
                  ],
                ))));
  }
}

class AliveKeeper extends StatefulWidget {
  final int index;

  const AliveKeeper({
    required this.index,
    GlobalKey? key,
  }) : super(key: key);

  @override
  AliveKeeperState createState() => AliveKeeperState();
}

class AliveKeeperState extends State<AliveKeeper>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Text('Item ${widget.index}');
  }
}
```

</details>

**Comment by darshankawar** [comment] 2022-04-05 13:17
Thanks for the update and further details. I am labeling it for further insights from the team on the intended behavior with a potential solution / fix.

**Comment by Piinks** [comment] 2022-04-05 18:58
@jcblancomartinez based on your [last code sample ](https://github.com/flutter/flutter/issues/101320#issuecomment-1088503935), you have configured the NestedScrollView to only apply to the header (outer scroll view) of the NestedScrollView, and not to the body (inner scroll view) of the NestedScrollView. 

```dart
...
            body: NestedScrollView(
                scrollBehavior:
                    // This only wraps scrollbars around the header <---
                    ScrollConfiguration.of(context).copyWith(scrollbars: true),
                headerSliverBuilder:
                    (BuildContext context, bool innerBoxIsScrolled) {
                  return [
                    SliverToBoxAdapter(
                      ...
                  ];
                },
                body: TabBarView(
                  children: [
                    ScrollConfiguration(
                        behavior: ScrollConfiguration.of(context)
                            // This removes scrollbars from the inner scroll view <----
                            .copyWith(scrollbars: false),
                        child: ListView.builder(
                            ...
```

I think the PrimaryScrollController may be at fault here. By default, the PrimaryScrollController (PSC) automatically attaches to vertical scroll positions. The NestedScrollView creates a PSC that it relies on to attach to the inner scroll view so that both scroll views can be controlled to keep them in sync, appearing as one scroll view. Since you are using keep alive, when you change tabs, the PSC is still attached to the scroll position on the first page, and is also attached to the position on the second page. The scrollbar can only base itself on one scroll position, so it creates the exception when it looks up the PSC and find more than one position. 

Since the header is outside of the tab view, the exception does not appear since there is only one outer scroll position.

I've been looking into PSC issues like these, similar to https://github.com/flutter/flutter/issues/100264

**Comment by jcblancomartinez** [comment] 2022-04-05 19:03
Thanks for looking into this.

@Piinks Is there any way to achieve the same behavior as in the video [here](https://github.com/flutter/flutter/issues/101320#issue-1192358337) (with different code) but making scroll bars work in web for both ListViews with keep alive?.

Thanks.

**Comment by Piinks** [comment] 2022-04-05 19:06
> Is there any way to achieve the same behavior as in the video [here](https://github.com/flutter/flutter/issues/101320#issue-1192358337) (with different code) but making scroll bars work in web for both ListViews with keep alive?

This sounds like a great question for stackoverflow or one of our [community channels](https://flutter.dev/community). I have seen UIs like this done in Flutter, but cannot work on recreating it as I am focused on fixing and resolving bugs like this one! :)

**Comment by jcblancomartinez** [comment] 2022-04-05 19:23
For future reference, I've posted a [question](https://stackoverflow.com/questions/71757325/page-level-scrollbar-per-tabbarview-with-widgets-on-top) in StackOverflow.

**Comment by jcblancomartinez** [comment] 2022-04-05 19:28
@Piinks Could you please clarify what specifically you are going to be looking into here?

> The scrollbar can only base itself on one scroll position, so it creates the exception when it looks up the PSC and find more than one position.

Should I create a separate GitHub issue as feature request to discuss about "NestedScrollView should support X number of controllers and X number of scrollbars, one per each TabBar."?

Thanks.

**Comment by jcblancomartinez** [comment] 2022-04-26 10:30
@Piinks Can you please label this issue as feature request so it can be taken into consideration to support wanted UX experiences.

Thanks.

**Comment by yjbanov** [comment] 2022-05-05 20:20
Since this particular issue has been resolved via StackOverflow, let's close it and track follow-up nested scrolling issues as part of https://github.com/flutter/flutter/issues/102003.

**Closed by yjbanov** 2022-05-05 20:20 UTC
Labels: framework, f: material design, f: scrolling, a: quality, platform-web
