### ISSUE TITLE
[Icons] Missing Material Icons

### ISSUE THREAD

**Issue by kgass** [flutter/flutter#97889] opened 2022-02-05 23:58 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 
The Material Icons for `Icons.sports_martial_arts` and `Icons.handshake` should be shown.

**Actual results:** 
Empty or wrong Icons
![flutter_01](https://user-images.githubusercontent.com/37659158/152662963-278e3d32-75d8-40b1-9c9a-4293b7793efd.png)

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Missing Icons Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Missing Icons Demo"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const [
            Icon(Icons.sports_martial_arts),
            Icon(Icons.handshake),  
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

With `flutter run --verbose` nothing is logged

With `flutter analyze` nothing is logged

Output for `flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-arm, locale de-DE)
    • Flutter version 2.10.0 at /Users/xyz/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (vor 4 Tagen), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kg/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Pixel 5 (mobile) • XYZ • android-arm64  • Android 12 (API 31)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by TowaYamashita** [comment] 2022-02-06 11:07
The same problem was reproduced in my environment.

Output for `flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-arm, locale ja)
    • Flutter version 2.8.1 at /opt/homebrew/Caskroom/flutter/2.5.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/yamashita/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Pixel 3a (mobile) • 93GAY0BAJD • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

**Comment by TowaYamashita** [comment] 2022-02-06 12:53
This problem is similar https://github.com/flutter/flutter/issues/97767

**Comment by danagbemava-nc** [comment] 2022-02-07 09:03
Closing as duplicate of #97767.

The issue has been fixed on master, and there's a cherry-pick request for it to be hotfixed into 2.10 in #97767. Kindly follow up there for more information. 

Thank you

**Closed by danagbemava-nc** 2022-02-07 09:03 UTC
Labels: in triage
