### ISSUE TITLE
TextField onChanged fires on focus

### ISSUE THREAD

**Issue by Lomski** [flutter/flutter#83647] opened 2021-05-31 04:18 UTC
onChanged method in TextField widget fires on focus TextField if it already have some text. Found this in flutter 2.0.6. Same behavour in flutter 2.2.1 (latest stable channel version for now) and in 2.3.0-16.0.pre (latest dev channel version). In 1.22.6 it was fine.

## Code
`TextField(
              onChanged: (text) {
                print(text);
              },
            )`

## Steps to Reproduce

1. Click on TextField
2. Type something
3. Submit (TextField lose focus)
4. Click on TextField

**Expected results:** 
onChanged method of TextField shouldnt fires on second click (without changing text).
**Actual results:** 
onChanged method of TextField fires on second click.

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale ru_RU.UTF-8)
    • Flutter version 2.2.1 at /home/user/Programs/flutter
    • Framework revision 02c026b03c (3 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /home/user/Android/Sdk
    • Java binary at: /home/user/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/user/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-01 08:42
HI @Lomski 
Thanks for filing the issue, however, I cannot reproduce the issue on the API 30 or API 28(same as you). I focused on the `TextFIeld`, type `flutter, unfocus with submit button, click on `TextFIeld` again, nothing is printed 


Here you can after I click `TextFIeld`, other logs are printed but `onChanged`
### Logs`
```console
I/flutter ( 5424): flu
I/flutter ( 5424): flut
I/flutter ( 5424): flutt
I/flutter ( 5424): flutte
I/flutter ( 5424): flutter
W/TextInputPlugin( 5424): Changing the content within the the composing region may cause the input method to behave strangely, and is therefore discouraged. See https://github.com/flutter/flutter/issues/78827 for more details
W/IInputConnectionWrapper( 5424): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 5424): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 5424): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 5424): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 5424): endBatchEdit on inactive InputConnection
```

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
 
void main() => runApp(MyApp());
 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField( onChanged: (text) { print(text); }, )


        ),
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.1 at /home/taha/Code/flutter_stable
    • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Linux
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 91.0.4472.77

• No issues found!

```

</details>

**Comment by Lomski** [comment] 2021-06-02 06:46
<details>
<summary>Code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'onChanged fires this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8.0),
              child: TextField(
                onChanged: (text) {
                  print(text);
                  setState(() {
                    _counter++;
                  });
                }
              ),
            )
          ],
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>Demonstration</summary>

![untitled1](https://user-images.githubusercontent.com/8664572/120435504-257d3880-c3c1-11eb-8bb3-367793bcedb4.gif)

</details>

Same behaviour on emulators API 30 and API 28. But on a real device ONEPLUS A6010 (mobile) • android-arm64 • Android 10 (API 29) onChanged fires only when i change the text.

**Comment by TahaTesser** [comment] 2021-06-02 09:22
Hi @Lomski 
I just tried emulator on Linux (same as you) and also tried Oneplus 8 device, `onChanged` isn't fired on focus.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'onChanged fires this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8.0),
              child: TextField(
                onChanged: (text) {
                  print(text);
                  setState(() {
                    _counter++;
                  });
                }
              ),
            )
          ],
        ),
      ),
    );
  }
}


``` 

</details>


| emulator  | Oneplus 8 |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/120454940-0076ce80-c39d-11eb-8a56-0fa287f733ff.gif" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/120455023-11bfdb00-c39d-11eb-8d68-25bdd4d90d36.gif" height="450" /> |




<details> 
<summary>flutter doctor -v</summary> 


	
```console
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.1 at /home/taha/Code/flutter_stable
    • Framework revision 02c026b03c (6 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
⣻Error 1 retrieving device properties for ro.product.cpu.abi:
adb: insufficient permissions for device: user taha is not in the plugdev group
See [http://developer.android.com/tools/device.html] for more information
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0
[✓] Connected device (4 available)
    • c9d8ee0c (mobile)            • c9d8ee0c      • android-arm    • Android
      null (API null)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Linux
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 91.0.4472.77
• No issues found!
```

</details>


Let me know If I am missing something
Thank you

**Comment by darshankawar** [comment] 2021-07-09 12:04
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-07-09 12:04 UTC
Labels: in triage, waiting for customer response
