### ISSUE TITLE
How to get all the images from mobile?

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#19368] opened 2018-07-14 04:41 UTC
I tried to get all the images from mobile using image_picker package.
But it makes user pick only one image at a time. How to get all the images from mobile automatically?
What package or library use to achieve these kinid of things?

**Comment by ThinkDigitalRepair** [comment] 2018-07-15 02:31
@baeharam For help, you want to ask on StackOverflow. This area is for errors in the Flutter SDK.

**Comment by zoechi** [comment] 2018-07-16 11:21
https://pub.dartlang.org/packages/flutter_multiple_image_picker might do what you want.
If not you can extend on the source of that package and customize it to your needs.

**Comment by zoechi** [comment] 2018-07-17 08:59
See also flutter/plugins#660

**Comment by baeharam** [comment] 2018-07-23 09:15
@zoechi Thx for helping. But what I want is to bring all the images from user's device by one button click. Can't be possible?

**Comment by zoechi** [comment] 2018-12-06 11:59
Perhaps https://pub.dartlang.org/packages/multi_image_picker

**Comment by zoechi** [comment] 2019-01-08 15:48
Duplicate of #14098

**Closed by zoechi** 2019-01-08 15:48 UTC
Labels: p: first party, p: image_picker, plugin, severe: new feature, waiting for customer response
