### ISSUE TITLE
Plugin pubspec supports android/iOS plugins without java and objc `pluginClass`

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#63545] opened 2020-08-12 02:58 UTC
## Use case

Currently, mobile(ios, andorid) plugins assumes a native(objc, swift, java, kotlin) `pluginClass`. Plugins that doesn't require a `pluginClass` is a legit use case (For example, FFI plugins like https://pub.dev/packages/objectbox). We should have a way to officially support it. 

## Proposal

There are many options and I plan to list all of them in a separate document. 

RELATED: https://github.com/flutter/flutter/issues/57497 https://github.com/flutter/flutter/issues/62853

CC @csells

**Comment by jmagman** [comment] 2021-02-18 00:37
Is this a duplicate of https://github.com/flutter/flutter/issues/52267?

**Comment by blasten** [comment] 2021-02-18 00:46
yes. It seems this issue is mostly focused on iOS/Android whereas https://github.com/flutter/flutter/issues/52267 has focused primarily on desktop support.

**Comment by stuartmorgan** [comment] 2021-06-13 15:47
That issue was intended to cover all platforms, do closing as a duplicate.

**Closed by stuartmorgan** 2021-06-13 15:47 UTC
Labels: P4, passed first triage, plugin, severe: new feature, tool
