### ISSUE TITLE
Saving image from ImageProvider error [Seems a Bug]

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#19407] opened 2018-07-16 14:11 UTC
error got when parse a image bytes from a ImageProvider:

```dart
widget.imageProvider
        .resolve(new ImageConfiguration())
        .addListener((imgInfo, _) {

          print('imgInfo: $imgInfo');
      imgInfo.image.toByteData().then((data) {
        print('data.buffer.asUint8List(): ${data.buffer.asUint8List()}');
        _toSaveImgFile.writeAsBytes(data.buffer.asUint8List());
      });
    });
```

Error:

```
[ERROR:flutter/lib/ui/painting/image_encoding.cc(71)] Pixel copy failed.
E/flutter ( 2340): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 2340): Exception: operation failed
E/flutter ( 2340): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
E/flutter ( 2340): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 2340): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

flutter doctor -v main info:

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.14 18A314h, locale en-CN)
    • Flutter version 0.5.1 at /Users/jintian/development/flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760
```

I can confirm that this code should not have problem, but every time I do this it can not save correctly. (I also posted a stackoverflow question but noone reponse), if anyone could gentally test it or just have a glance at my code, specific out my problem, so many thanks!

**Comment by jinfagang** [comment] 2018-07-16 14:20
More detail error:

```
 _toSaveImgFile: File: 'Directory: '/data/user/0/com.example.flutteruranus/app_flutter'2018-07-16T22:19:06.512685.jpg'
I/flutter ( 8335): imgInfo: [1440×2560] @ 1.0x
I/flutter ( 8335): [1440×2560]
E/flutter ( 8335): [ERROR:flutter/lib/ui/painting/image_encoding.cc(71)] Pixel copy failed.
E/flutter ( 8335): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 8335): Exception: operation failed
E/flutter ( 8335): #0      _ImagePreviewPageState._saveImageToLocal.<anonymous closure> (file:///Volumes/xs/awesome/uranus/clients/flutter/crystal/lib/components/image_preview.dart:36:31)
E/flutter ( 8335): <asynchronous suspension>
E/flutter ( 8335): #1      ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:203:17)
E/flutter ( 8335): #2      MultiFrameImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:431:11)
E/flutter ( 8335): #3      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:132:25)
E/flutter ( 8335): #4      _ImagePreviewPageState._saveImageToLocal (file:///Volumes/xs/awesome/uranus/clients/flutter/crystal/lib/components/image_preview.dart:33:10)
E/flutter ( 8335): <asynchronous suspension>
E/flutter ( 8335): #5      _ImagePreviewPageState._showModalBottomSheet.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Volumes/xs/awesome/uranus/clients/flutter/crystal/lib/components/image_preview.dart:74:27)
E/flutter ( 8335): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
E/flutter ( 8335): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
E/flutter ( 8335): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 8335): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter ( 8335): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter ( 8335): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 8335): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter ( 8335): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter ( 8335): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 8335): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter ( 8335): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter ( 8335): #17     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter ( 8335): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

```

Any information about this would be very helpful, this feature is much important in my project, thanks!

**Comment by zoechi** [comment] 2018-07-16 14:34
Similar to the closed issue #18323

**Comment by Galahand** [comment] 2018-08-24 19:05
i'm having the same issue, any news with this?

**Comment by jinfagang** [comment] 2018-08-26 04:15
@zoechi You called me open another issue, and you link this to the previous issue. It's this a recursive??

**Comment by zoechi** [comment] 2018-08-26 11:43
No, but it might be helpful when investigating that something similar was reported before already.

**Comment by jinfagang** [comment] 2018-08-26 12:49
@zoechi I still got no clue for twenty years.

**Comment by DavBfr** [comment] 2018-10-20 14:37
Can be linked to #17687

**Comment by zoechi** [comment] 2018-12-11 07:04
@jinfagang are you still seeing this?

**Comment by jinfagang** [comment] 2018-12-11 14:52
@zoechi Yeah..... but still don't know how to save a Image widget to local album, it's lack some official api or instructions to do this with current apis

**Comment by zoechi** [comment] 2018-12-11 15:38
@jinfagang I think to remember that there is a community to access the album in pub.dartlang.org

**Comment by jinfagang** [comment] 2018-12-12 01:44
@zoechi which one? did u remember some keywords? I'll search it out

**Comment by TahaTesser** [comment] 2020-10-13 14:51
Hi  @jinfagang
Your code incomplete/outdateed, unable to reproduce the issue
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2020-11-04 12:42
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-04 12:42 UTC
Labels: P4, dependency: skia, engine, severe: crash
