### ISSUE TITLE
How would you use GestureDetector to implement a directional zoom function？

### ISSUE THREAD

**Issue by c1s1x1** [flutter/flutter#135430] opened 2023-09-25 14:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Pardon my English, but I wanted to achieve an effect similar to the GIF I posted, and I found that onScaleUpdate provides a ScaleUpdateDetails property, I also see horizontalScale and verticalScale with two different axes.
I thought I could easily use either horizontalScale or verticalScale to achieve my goal, but as I used it, the value of horizontalScale changed even if I just scaled vertically.
So I don't know how to do that, only one direction is going to scale.
By the way, is localFocalPoint the midpoint of the line between the two touchpoints? If so, how can I get the coordinates of any of the touch points

Thanks for answering my questions.

### Proposal

![106751958-33e16080-662a-11eb-99fc-994f0b41de93](https://github.com/flutter/flutter/assets/13296895/2b59056d-2976-4903-b418-b66762ca4715)

**Comment by asadalpha** [comment] 2023-09-25 19:59
Hey I tried to create a similar feature,. I assigned Singlechild scroll view to avoid the pixel error,

Code


`import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  double _containerWidth = 200.0;
  double _containerHeight = 200.0;
  double _baseWidth = 100.0;
  double _baseHeight = 100.0;

  void _updateContainerSize(double horizontalScale, double verticalScale) {
    setState(() {
      // Update width based on horizontal scale (pinch inward)
      _containerWidth = _baseWidth * horizontalScale;

      // Update height based on vertical scale (pinch outward)
      _containerHeight = _baseHeight * verticalScale;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Pinch to Shrink Container'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            const SizedBox(
              height: 100,
            ),
            GestureDetector(
              // onScaleUpdate: (ScaleUpdateDetails details) {
              //   _updateContainerSize(
              //     details.horizontalScale,
              //     details.verticalScale,
              //   );
              // },
              // onScaleStart: (ScaleStartDetails details) {
              //   _baseWidth = _containerWidth;
              //   _baseHeight = _containerHeight;
              // },
              child: Center(
                child: Container(
                  width: _containerWidth,
                  height: _containerHeight,
                  color: Colors.blue,
                ),
              ),
            ),
            GestureDetector(
              onScaleUpdate: (ScaleUpdateDetails details) {
                _updateContainerSize(
                  details.horizontalScale,
                  details.verticalScale,
                );
              },
              onScaleStart: (ScaleStartDetails details) {
                _baseWidth = _containerWidth;
                _baseHeight = _containerHeight;
              },
              child: Container(
                margin: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                    color: const Color.fromARGB(255, 220, 218, 218),
                    borderRadius: BorderRadius.circular(12)),
                height: 200,
                width: double.infinity,
              ),
            )
          ],
        ),
      ),
    );
  }
}
`

**Comment by asadalpha** [comment] 2023-09-25 20:02
I tried to replicate the scenario , also added the Singlechildscrollview for avoiding pixel errors.

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  double _containerWidth = 200.0;
  double _containerHeight = 200.0;
  double _baseWidth = 100.0;
  double _baseHeight = 100.0;

  void _updateContainerSize(double horizontalScale, double verticalScale) {
    setState(() {
      _containerWidth = _baseWidth * horizontalScale;

      _containerHeight = _baseHeight * verticalScale;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Pinch to Shrink Container'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            const SizedBox(
              height: 100,
            ),
            Center(
              child: Container(
                width: _containerWidth,
                height: _containerHeight,
                color: Colors.blue,
              ),
            ),
            GestureDetector(
              onScaleUpdate: (ScaleUpdateDetails details) {
                _updateContainerSize(
                  details.horizontalScale,
                  details.verticalScale,
                );
              },
              onScaleStart: (ScaleStartDetails details) {
                _baseWidth = _containerWidth;
                _baseHeight = _containerHeight;
              },
              child: Container(
                margin: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                    color: const Color.fromARGB(255, 220, 218, 218),
                    borderRadius: BorderRadius.circular(12)),
                height: 200,
                width: double.infinity,
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

**Comment by asadalpha** [comment] 2023-09-25 20:03
I tried to replicate the scenario and also added the Singlechildscrollview to avoid pixel errors.

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  double _containerWidth = 200.0;
  double _containerHeight = 200.0;
  double _baseWidth = 100.0;
  double _baseHeight = 100.0;

  void _updateContainerSize(double horizontalScale, double verticalScale) {
    setState(() {
      _containerWidth = _baseWidth * horizontalScale;

      _containerHeight = _baseHeight * verticalScale;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Pinch to Shrink Container'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            const SizedBox(
              height: 100,
            ),
            Center(
              child: Container(
                width: _containerWidth,
                height: _containerHeight,
                color: Colors.blue,
              ),
            ),
            GestureDetector(
              onScaleUpdate: (ScaleUpdateDetails details) {
                _updateContainerSize(
                  details.horizontalScale,
                  details.verticalScale,
                );
              },
              onScaleStart: (ScaleStartDetails details) {
                _baseWidth = _containerWidth;
                _baseHeight = _containerHeight;
              },
              child: Container(
                margin: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                    color: const Color.fromARGB(255, 220, 218, 218),
                    borderRadius: BorderRadius.circular(12)),
                height: 200,
                width: double.infinity,
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by c1s1x1** [comment] 2023-09-26 01:22
> 我尝试复制该场景，并添加了 Singlechildscrollview 以避免像素错误。
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return const MaterialApp(
>       debugShowCheckedModeBanner: false,
>       home: Home(),
>     );
>   }
> }
> 
> class Home extends StatefulWidget {
>   const Home({super.key});
> 
>   @override
>   State<Home> createState() => _HomeState();
> }
> 
> class _HomeState extends State<Home> {
>   double _containerWidth = 200.0;
  >   double _containerHeight = 200.0;
>   double _baseWidth = 100.0;
>   double _baseHeight = 100.0;
> 
>   void _updateContainerSize(double horizontalScale, double verticalScale) {
>     setState(() {
>       _containerWidth = _baseWidth * horizontalScale;
> 
>       _containerHeight = _baseHeight * verticalScale;
>     });
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Pinch to Shrink Container'),
>       ),
>       body: SingleChildScrollView(
>         child: Column(
>           children: [
>             const SizedBox(
>               height: 100,
>             ),
>             Center(
>               child: Container(
>                 width: _containerWidth,
>                 height: _containerHeight,
>                 color: Colors.blue,
>               ),
>             ),
>             GestureDetector(
>               onScaleUpdate: (ScaleUpdateDetails details) {
>                 _updateContainerSize(
>                   details.horizontalScale,
>                   details.verticalScale,
>                 );
>               },
>               onScaleStart: (ScaleStartDetails details) {
>                 _baseWidth = _containerWidth;
>                 _baseHeight = _containerHeight;
>               },
>               child: Container(
>                 margin: const EdgeInsets.all(16),
>                 decoration: BoxDecoration(
>                     color: const Color.fromARGB(255, 220, 218, 218),
>                     borderRadius: BorderRadius.circular(12)),
>                 height: 200,
>                 width: double.infinity,
>               ),
>             )
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

Did you try to slide only horizontally? I tested your demo and found that horizontal sliding causes vertical height to change.
That's not what I want, I want to slide horizontally so that only _containerWidth changes, slide vertically so that only _containerHeight changes, and if I slide diagonally so that _containerWidth and _containerHeight scale together
![iShot_2023-09-26_09 18 51](https://github.com/flutter/flutter/assets/13296895/fdee7e25-c4c5-473f-ad2d-b4189f660dcc)

**Comment by darshankawar** [comment] 2023-09-26 07:18
@c1s1x1 
Your issue / question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a `how to` question / support question and not a bug report or feature request.

**Closed by darshankawar** 2023-09-26 07:18 UTC
Labels: in triage

**Comment by c1s1x1** [comment] 2023-09-26 08:31
> @c1s1x1 Your issue / question is better suited for support channels like StackOverflow, so please ask the same there. Closing from here, as this is more of a `how to` question / support question and not a bug report or feature request.

But if this can't be solved, it represents a lack of functionality, and I think that in the monitoring of user gestures, the touch coordinates of each finger should be provided, so that developers are not limited to the external interface data you provide
