### ISSUE TITLE
Shared preferences ^0.5.12+4 is giving an exception in the headless background process

### ISSUE THREAD

**Issue by markjoseultra** [flutter/flutter#79774] opened 2021-04-05 12:50 UTC
## Steps to Reproduce

1. Create a new flutter application
2. pub get background_fetch: '0.7.1' and shared_preferences: ^0.5.12+4
3. create a headless method that uses shared preferences to get a local data
4. run the app on a physical device
5. exit the app and then trigger the background fetch using this command
adb shell cmd jobscheduler run -f com.example.app 999
6. You will not see the logs since you exit the app, so you need to run a different flutter project on the physical device before you run the command above and there you will see the error logs from a headless background fetch

7. I tried removing shared_sharedpreferences and the method works fine.

**Expected results:** 
It should get the data from shared preferences

**Actual results:** 
I/flutter (29628): [BackgroundFetch] Headless event received in Sparkle Merchant.
I/flutter (29628): Executing local notification
E/flutter (29628): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

<details>
I/flutter (29628): [BackgroundFetch] Headless event received in Sparkle Merchant.
I/flutter (29628): Executing local notification
E/flutter (29628): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

```
I/flutter (29628): [BackgroundFetch] Headless event received in Sparkle Merchant.
I/flutter (29628): Executing local notification
E/flutter (29628): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

```
Analyzing sparkles-seller...                                            
No issues found! (ran in 8.8s)
```

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-PH)
    • Flutter version 1.22.4 at /Users/sparkle-star/Developer/flutter
    • Framework revision 1aafb3a8b9 (5 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sparkle-star/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```

</details>

**Comment by pedromassangocode** [comment] 2021-04-06 08:01
Hi @markjoseultra 
This seems to be a duplicate of https://github.com/flutter/flutter/issues/66833 which is a deduplicate of https://github.com/flutter/flutter/issues/78625 which was closed recently. Can you please try what was suggested in https://github.com/flutter/flutter/issues/78625#issuecomment-809915540 and see if it works for you?

If the issue persists, please provide a minimal code sample that does not use any third-party plugin/package and your `flutter doctor -v`.
Thank you

**Comment by markjoseultra** [comment] 2021-04-06 08:58
Hi @pedromassangocode 

Thank you for the response, I have already tried these #78625 #66833 articles, but I am still getting the same issue and same exception logs.
transistorsoft have a sample project using shared_preferences in the background process but it is generated from older flutter version and using older plugin version.

this issue only shows up when shared preferences is used in the background while app is terminated.

**Comment by pedromassangocode** [comment] 2021-04-07 06:51
Can you please use the latest version of SharedPreferences? The latest version is: `shared_preferences: ^2.0.5`

If the issue persists, please provide a minimal code sample that does not use any third-party plugin/package and your `flutter doctor -v`.
Thank you

**Comment by markjoseultra** [comment] 2021-04-07 07:19
Thank you @pedromassangocode I upgraded to flutter 2 its working now

**Closed** 2021-04-07 08:02 UTC
Labels: r: solved
