### ISSUE TITLE
Android Firebase Test Lab run is flaky because PlatformException(error, Neither user 10218 nor current process has android.permission.WAKE_LOCK., null)

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#42349] opened 2019-10-09 19:01 UTC
This seems to be extremely flaky and numerous runs have run into the same. An example is the [engine roll](https://cirrus-ci.com/build/flutter/flutter/85cc31319a5c445a5714a3031413567826c56f7e)  which failed on the [release_smoke_tests](https://cirrus-ci.com/task/5683028134723584) because of a [test lab run whose dashboard is here](https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.1b29258e8f97b976/matrices/7537779313191336608).

**Comment by dnfield** [comment] 2019-10-09 19:12
Posted this to the slack channel for Firebase test lab in case they have insight: https://firebase-community.slack.com/archives/C1MTSQ5QT/p1570644251004600

**Comment by dnfield** [comment] 2019-10-09 20:20
/cc @mklim - this is probably better place to discuss.

The stack trace seems to indicate that something in resizing a platform view on Android is triggering some API call that wants WAKE_LOCK permissions, which isn't expected.

AFAICT, google maps does not require this permission on Android by default.

**Comment by mklim** [comment] 2019-10-09 20:30
Investigating this now. In general when we resize a platform view on Android we create and destroy a virtual display and re-attach the view to the new display. AFAIK that doesn't need any kind of `WAKE_LOCK` permission. But there may be a weird chain of calls here, checking now.

**Comment by dnfield** [comment] 2019-10-09 21:01
One possibility:

> Thank you for the example run, it was really helpful in establishing the context of your question.
This issue might be intermittent because Robo crawls are non-deterministic, while permissions are checked/requested dynamically on the later Android versions, so some crawls might hit the scenario leading to the check of WAKE_LOCK permission, while others might not trigger this check.
Also, it looks like this problem happened for a Q-beta-3 crawl. So, it could be a result of some negative synergy between your app's behavior and Q-beta-3 or some bug/feature in Q-beta-3. You can confirm this by excluding Q-beta-3 from your runs. Thanks!

**Comment by mklim** [comment] 2019-10-09 21:56
Is it at all possible that the test harness itself is expecting this permission itself in order to try and keep the device under test awake?

I've looked through our APIs and will keep looking, but so far I haven't found anything that looks like it should need this permission. AFAICT this is only related to literally acquiring `WakeLock`s, generally via `PowerManager`, which we never use. There is some transitive nesting in the various virtual display API calls but none of them seem to have anything to do with PowerManager or WakeLocks.

There's also the chance that there's something in the Google Maps SDK that calls an API needing this when it detects that the map has been resized, but I can't find any documentation about the SDK expecting this permission. Do we know if this flake is just `google_maps_flutter` specifically or all platform views?

**Comment by dnfield** [comment] 2019-10-09 22:04
I think the biggest clue is that it's happening on Q-beta-3.  Perhaps it's a bug in Q?

**Comment by mklim** [comment] 2019-10-09 22:33
@dnfield maybe. It could also be some combination. For example, the Google Maps library could hypothetically have a Q-only code path that calls an Android API that needs the permission.

I couldn't find anything for sure, but there is some suspicious things. There's a wearable version of maps that allows for an "ambient mode" that requires WAKE_LOCK. I'm also seeing a [`GeoFenceHadrwareImpl`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/location/GeofenceHardwareImpl.java) class in AOSP that also requires a wake lock, but I don't know if that itself is referenced anywhere with Maps. I don't think our plugin should be using either of those, but we are deferring to the SDK so it's hard to really tell.

I'm going to step back and run the test myself and see if I can reproduce it locally, and then see if it reproduces if Maps is swapped out for another platform view. Basically I'd like to try to narrow this down from to the CI environment, the platform views api, or the plugin.

**Comment by mklim** [comment] 2019-10-09 23:22
This test is also flakily actually executing its logic. It relies on the keyboard opening, for which we have some Kotlin code that's supposed to automatically open it at app start. However it looks like that code has never functioned, and the demo app happens to have a random text field... so some of of the time the test is really executed because Robo happens to tap the text field, and other times it doesn't really run. The Kotlin code not opening the keyboard may be device specific, but the text field should probably never be there for Robo to accidentally tap on.

**Comment by dnfield** [comment] 2019-10-09 23:41
A cornicopia of bugs!

**Comment by mklim** [comment] 2019-10-10 01:08
This also reproduces flakily locally. I can see this stack trace about 2% of the time just from running `adb shell am start && sleep 5 && adb shell pm clear` on a loop inside of my terminal. That's including the partial fixes from  #42379.

**Comment by mklim** [comment] 2019-10-10 17:51
I replaced this test with a `webview` and ran it a few hundred times and didn't see it repro. I think whatever issue this is is specific to Google maps. I filed #42451 for the plugin and I'm going to close this out by changing the platform view we rely on for the test.

**Comment by Hixie** [comment] 2019-10-11 04:47
I just got this on one of my PRs (https://cirrus-ci.com/task/4865379809099776?command=test):
```
./dev/bots/firebase_testlab.sh
Activated service account credentials for: [cirrus-firebase-testlab@flutter-infra.iam.gserviceaccount.com]
Updated property [core/project].
/tmp/flutter sdk/dev/integration_tests/release_smoke_test /tmp/flutter sdk
Initializing gradle...                                              7.8s
Resolving dependencies...                                          60.9s
Running Gradle task 'bundleRelease'...                          
Note: /root/.pub-cache/hosted/pub.dartlang.org/instrumentation_adapter-0.1.3/android/src/main/java/dev/flutter/instrumentationadapter/FlutterRunner.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Removed unused resources: Binary resource data reduced from 36KB to 23KB: Removed 36%
Running Gradle task 'bundleRelease'...                             73.2s
Built build/app/outputs/bundle/release/app-release.aab (8.6MB).
Have questions, feedback, or issues? Get support by visiting:
  https://firebase.google.com/support/
Uploading [build/app/outputs/bundle/release/app-release.aab] to Firebase Test Lab...
Raw results will be stored in your GCS bucket at [https://console.developers.google.com/storage/browser/flutter_firebase_testlab/dev/integration_tests/release_smoke_test/6b8dca271a0eed140a41686a2b8283f94c7e585f/5012710709788672/]
Test [matrix-2x6a37czg3son] has been created in the Google Cloud.
Firebase Test Lab will execute your robo test on 3 device(s).
Creating individual test executions...
.................................................................................................................................................................................................................................................................................................done.
Test results will be streamed to [https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.27c33c672e9b01f2/matrices/8706522675758801659].
04:25:47 Test matrix status: Pending:3 
04:25:59 Test matrix status: Running:3 
04:26:11 Test matrix status: Running:3 
04:26:23 Test matrix status: Running:3 
04:26:35 Test matrix status: Running:3 
04:26:47 Test matrix status: Running:3 
04:26:59 Test matrix status: Running:3 
04:27:11 Test matrix status: Running:3 
04:27:23 Test matrix status: Running:3 
04:27:35 Test matrix status: Running:3 
04:27:47 Test matrix status: Running:3 
04:27:59 Test matrix status: Running:3 
04:28:11 Test matrix status: Running:3 
04:28:24 Test matrix status: Running:3 
04:28:36 Test matrix status: Running:3 
04:28:48 Test matrix status: Finished:1 Running:2 
04:29:00 Test matrix status: Finished:1 Running:2 
04:29:12 Test matrix status: Finished:1 Running:2 
04:29:24 Test matrix status: Finished:1 Running:2 
04:29:36 Test matrix status: Finished:1 Running:2 
04:29:48 Test matrix status: Finished:2 Running:1 
04:30:00 Test matrix status: Finished:3           
Robo testing complete.
More details are available at [https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.27c33c672e9b01f2/matrices/8706522675758801659].
+---------+-------------------------------+--------------+
| OUTCOME |        TEST_AXIS_VALUE        | TEST_DETAILS |
+---------+-------------------------------+--------------+
| Passed  | blueline-28-en-portrait       | --           |
| Passed  | blueline-Q-beta-3-en-portrait | --           |
| Passed  | griffin-24-en-portrait        | --           |
+---------+-------------------------------+--------------+
10-10 21:27:17.029: I/flutter(20799): Instance of 'DiagnosticableTreeNode'
10-10 21:26:38.066: I/flutter(28202): Instance of 'DiagnosticableTreeNode'
10-10 21:27:09.917: I/flutter(12164): Instance of 'DiagnosticableTreeNode'
/tmp/flutter sdk
/tmp/flutter sdk/dev/integration_tests/abstract_method_smoke_test /tmp/flutter sdk
Initializing gradle...                                              0.5s
Resolving dependencies...                                          15.4s
Running Gradle task 'bundleRelease'...                          
Checking the license for package Android SDK Platform 29 in /opt/android_sdk/licenses
License for package Android SDK Platform 29 accepted.
Preparing "Install Android SDK Platform 29 (revision: 3)".
"Install Android SDK Platform 29 (revision: 3)" ready.
Installing Android SDK Platform 29 in /opt/android_sdk/platforms/android-29
"Install Android SDK Platform 29 (revision: 3)" complete.
"Install Android SDK Platform 29 (revision: 3)" finished.
Removed unused resources: Binary resource data reduced from 23KB to 16KB: Removed 29%
Running Gradle task 'bundleRelease'...                             84.3s
Built build/app/outputs/bundle/release/app-release.aab (10.0MB).
Have questions, feedback, or issues? Get support by visiting:
  https://firebase.google.com/support/
Uploading [build/app/outputs/bundle/release/app-release.aab] to Firebase Test Lab...
Raw results will be stored in your GCS bucket at [https://console.developers.google.com/storage/browser/flutter_firebase_testlab/dev/integration_tests/abstract_method_smoke_test/6b8dca271a0eed140a41686a2b8283f94c7e585f/5012710709788672/]
Test [matrix-2ur2ocevv6w2k] has been created in the Google Cloud.
Firebase Test Lab will execute your robo test on 3 device(s).
Creating individual test executions...
.....................................................................................................................................................................................................................done.
Test results will be streamed to [https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.1b29258e8f97b976/matrices/5774866626729123864].
04:32:28 Test matrix status: Pending:3 
04:32:41 Test matrix status: Pending:1 Running:2 
04:32:53 Test matrix status: Running:3           
04:33:05 Test matrix status: Running:3           
04:33:17 Test matrix status: Running:3           
04:33:29 Test matrix status: Running:3           
04:33:41 Test matrix status: Running:3           
04:33:53 Test matrix status: Running:3           
04:34:05 Test matrix status: Running:3           
04:34:17 Test matrix status: Running:3           
04:34:29 Test matrix status: Running:3           
04:34:41 Test matrix status: Running:3           
04:34:53 Test matrix status: Running:3           
04:35:05 Test matrix status: Running:3           
04:35:17 Test matrix status: Running:3           
04:35:29 Test matrix status: Running:3           
04:35:41 Test matrix status: Finished:1 Running:2 
04:35:54 Test matrix status: Finished:1 Running:2 
04:36:06 Test matrix status: Finished:1 Running:2 
04:36:18 Test matrix status: Finished:2 Running:1 
04:36:30 Test matrix status: Finished:2 Running:1 
04:36:42 Test matrix status: Finished:2 Running:1 
04:36:54 Test matrix status: Finished:3           
Robo testing complete.
More details are available at [https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.1b29258e8f97b976/matrices/5774866626729123864].
+---------+-------------------------------+--------------+
| OUTCOME |        TEST_AXIS_VALUE        | TEST_DETAILS |
+---------+-------------------------------+--------------+
| Passed  | blueline-28-en-portrait       | --           |
| Passed  | blueline-Q-beta-3-en-portrait | --           |
| Passed  | griffin-24-en-portrait        | --           |
+---------+-------------------------------+--------------+
10-10 21:33:59.942: E/flutter(19737): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Neither user 10218 nor current process has android.permission.WAKE_LOCK., null)
10-10 21:33:59.942: E/flutter(19737): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
10-10 21:33:59.942: E/flutter(19737): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
10-10 21:33:59.942: E/flutter(19737): <asynchronous suspension>
10-10 21:33:59.942: E/flutter(19737): #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:559)
10-10 21:33:59.942: E/flutter(19737): <asynchronous suspension>
10-10 21:33:59.942: E/flutter(19737): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174)
10-10 21:33:59.942: E/flutter(19737): <asynchronous suspension>
10-10 21:33:59.942: E/flutter(19737): #4      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155)
10-10 21:33:59.942: E/flutter(19737): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1695)
10-10 21:33:59.942: E/flutter(19737): #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
10-10 21:33:59.942: E/flutter(19737): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1716)
10-10 21:33:59.942: E/flutter(19737): #8      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806)
10-10 21:33:59.942: E/flutter(19737): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1716)
10-10 21:33:59.942: E/flutter(19737): #10     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:161)
10-10 21:33:59.942: E/flutter(19737): #11     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477)
10-10 21:33:59.942: E/flutter(19737): #12     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:231)
10-10 21:33:59.942: E/flutter(19737): #13     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:392)
10-10 21:33:59.942: E/flutter(19737): #14     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584)
10-10 21:33:59.942: E/flutter(19737): #15     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844)
10-10 21:33:59.942: E/flutter(19737): #16     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344)
10-10 21:33:59.942: E/flutter(19737): #17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:777)
10-10 21:33:59.942: E/flutter(19737): #18     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283)
10-10 21:33:59.942: E/flutter(19737): #19     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1043)
10-10 21:33:59.942: E/flutter(19737): #20     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:982)
10-10 21:33:59.942: E/flutter(19737): #21     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:898)
10-10 21:33:59.942: E/flutter(19737): #22     _rootRun (dart:async/zone.dart:1124)
10-10 21:33:59.942: E/flutter(19737): #23     _CustomZone.run (dart:async/zone.dart:1021)
10-10 21:33:59.942: E/flutter(19737): #24     _CustomZone.runGuarded (dart:async/zone.dart:923)
10-10 21:33:59.942: E/flutter(19737): #25     _invoke (dart:ui/hooks.dart:259)
10-10 21:33:59.942: E/flutter(19737): #26     _drawFrame (dart:ui/hooks.dart:217)
```

**Comment by dnfield** [comment] 2019-10-11 04:56
Can you merge up to head and try again?  You were likely testing against an older branch that contained this issue.

**Comment by dnfield** [comment] 2019-10-11 05:03
Looks like your commit contained the fix for this... we should probably add WAKE_LOCK back to the androidmanifest.

**Comment by Hixie** [comment] 2019-10-11 06:57
(FWIW, my script to push a branch to GitHub first merges to tip of tree, so any commit I push to GitHub is always pretty recent.)

**Comment by dnfield** [comment] 2019-10-11 15:06
I was vainly hoping you had opened your PR before this fix landed, and then landed it after but still had presubmits going against the earlier commit :)

**Comment by dnfield** [comment] 2019-10-11 15:27
Added the WAKE_LOCK permission back to that app.  @mklim it seems like this might not be google_maps specific?

**Comment by mklim** [comment] 2019-10-11 16:48
I guess not, thanks for fixing it @dnfield. I ran it around a few hundred times without maps and didn't see it repro again locally, vs 2% of the time with maps. But it must be just flaky enough that that was a fluke.

**Comment by mklim** [comment] 2019-10-11 17:29
Yeah, I still can't reproduce this locally anymore after a few hundred more runs. I'm already testing on the same exact device as CI and general SDK version, though not sure if I'm on the exact same release of Q. @dnfield do you know how to tell exactly what release the test device is on? I'm looking a number like "QP1A.191005.007.A1."

**Comment by mklim** [comment] 2019-10-11 17:55
There's a much better stack trace from the Java side in the Firebase logs themselves, I don't think I need repro anymore:

```
Failed to handle method call
java.lang.SecurityException: Neither user 10218 nor current process has android.permission.WAKE_LOCK.
	at android.os.Parcel.createException(Parcel.java:2069)
	at android.os.Parcel.readException(Parcel.java:2037)
	at android.os.Parcel.readException(Parcel.java:1986)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1153)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:895)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
	at android.app.Dialog.show(Dialog.java:342)
	at android.app.Presentation.show(Presentation.java:250)
	at io.flutter.plugin.platform.k.a(Unknown Source:104)
	at io.flutter.plugin.platform.j$a.a(Unknown Source:52)
	at io.flutter.embedding.engine.d.g$a.e(Unknown Source:59)
	at io.flutter.embedding.engine.d.g$a.a(Unknown Source:141)
	at a.a.c.a.j$a.a(Unknown Source:17)
	at io.flutter.embedding.engine.b.b.a(Unknown Source:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:1896)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1924)
	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4268)
	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2174)
	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2140)
_state.cc(148)] Unhandled Exception: PlatformException(error, Neither user 10218 nor current process has android.permission.WAKE_LOCK., null)
```

This points to us calling Presentation#show, which we do in the engine via `SingleViewPresentation#show` on resize. Then that goes through a bunch of AOSP calls and something in there triggers the permissions error. Going to keep searching to try and find which API actually causes the error. I expect that it may be a bug in Q beta 3, since nothing in [Presentation#show](https://developer.android.com/reference/android/app/Presentation#show()) says it should require this permission. The problem line looks likely to be `android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1153)`.

**Comment by godofredoc** [comment] 2019-11-14 23:06
Any updates on this bug?

**Comment by daniele777** [comment] 2020-01-20 10:27
I have same but solve  android studio i  do this ..

1 Add line on android manifest debug 
 <uses-permission android:name="android.permission.WAKE_LOCK" />

2  Close all service and instance in task bar about develop
3 Backup of project
4 Delete Gradle directory on C\user\.....\.gradle
5 Open project > click on build.gradle and click to Open for Editing in adroid studio 
6 Sync with gradle
7 After download package of gradle and sync ok ...exit close all instance in task bar 
8 Delete directory of prooject and restore backup
9 After load ... click FIle>invalidate chache and restart 

Done !!!! Hope than help!

**Comment by blasten** [comment] 2020-04-10 03:23
I haven't seen this issue in recent runs. If it comes back, feel free to re-open this bug. Also, `release_smoke_tests ` were  renamed  as `firebase_test_lab_tests-linux`.

**Closed by blasten** 2020-04-10 03:23 UTC
Labels: passed secondary triage, team: flakes, team: infra

**Comment by hawkinsjb1** [comment] 2020-05-17 08:07
This is still happening very consistently for me
