### ISSUE TITLE
Automatically retry when Gradle fails with "Could not GET ... failed to respond"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#42878] opened 2019-10-16 23:58 UTC
This should not be fatal (and should not cause tests to fail), we should automatically retry after a short pause:
```
[gradle_plugin_bundle_test] [STDOUT] Execution failed for task ':app:checkReleaseDuplicateClasses'.
[gradle_plugin_bundle_test] [STDOUT] > Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
[gradle_plugin_bundle_test] [STDOUT]    > Could not download kotlin-stdlib-jdk7.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50)
[gradle_plugin_bundle_test] [STDOUT]       > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.3.50/kotlin-stdlib-jdk7-1.3.50.jar'.
[gradle_plugin_bundle_test] [STDOUT]          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.3.50/kotlin-stdlib-jdk7-1.3.50.jar'.
[gradle_plugin_bundle_test] [STDOUT]             > jcenter.bintray.com:443 failed to respond
```

**Comment by jmagman** [comment] 2019-12-03 22:49
This looks like a duplicate of https://github.com/flutter/flutter/issues/19235.  Were you trying to track something different here?

**Comment by blasten** [comment] 2019-12-03 22:55
Discussed offline. We have integration tests that call Gradle directly. These test should have a re-try logic similar to the one in the tool.

**Comment by VladyslavBondarenko** [comment] 2020-01-10 09:17
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by VladyslavBondarenko** 2020-01-10 09:17 UTC
Labels: a: build, team: flakes, tool, waiting for customer response
