### ISSUE TITLE
CupertinoListSection examples not working

### ISSUE THREAD

**Issue by alvesluc** [flutter/flutter#118820] opened 2023-01-19 18:57 UTC
Also, CupertinoListTile ain't working.
https://api.flutter.dev/flutter/cupertino/CupertinoListSection-class.html

Tried with Safari and Chrome.

**Comment by TahaTesser** [comment] 2023-01-19 20:28
duplicate of https://github.com/flutter/flutter/issues/118161

**Closed by TahaTesser** 2023-01-19 20:28 UTC
