### ISSUE TITLE
[web][regression] App doesn't render in debug mode (shows blank page in canvaskit only)  & throws Expected a value of type 'Future<_RegisteredFont>', but got one of type            '_Future<_RegisteredFont?>'

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#69570] opened 2020-11-02 12:19 UTC
## Steps to Reproduce
1. Create a new project `flutter create master_flutter` on the latest `master` channel 
3. Execute `flutter run --debug --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome -v`

(No issue with `flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome -v` or `flutter run -d chrome`)

| Expected Results | Actual Results |
| --------------- | --------------- |
<img width="559" alt="Screenshot 2020-11-02 at 5 47 39 PM" src="https://user-images.githubusercontent.com/48603081/97867272-8b261b00-1d33-11eb-9221-f66dbb9e2bc0.png">  | <img width="689" alt="Screenshot 2020-11-02 at 5 37 16 PM" src="https://user-images.githubusercontent.com/48603081/97867258-86616700-1d33-11eb-8bff-c334e6eb4976.png">

### Additional context:
1. The app renders fine in release mode 
2. Doesn't reproduce on the `dev` channel
3. Reproduce on the web on mac and windows too, haven't tested on Linux 

<details> 
<summary>logs</summary> 

```bash
[  +29 ms] Running "flutter pub get" in master_flutter... (completed in 577ms)
[ +168 ms] Generating
/Users/tahatesser/AndroidStudioProjects/master_flutter/android/app/src/main/java
/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +140 ms] Launching lib/main.dart on Chrome in debug mode...
[ +139 ms] Updating assets
[ +134 ms] Syncing files to device Chrome...
[  +91 ms] <- reset
[  +10 ms] /Users/tahatesser/Code/flutter_master/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/Users/tahatesser/Code/flutter_master/bin/cache/artifacts/engine/darwin-x64/fron
tend_server.dart.snapshot --sdk-root
/Users/tahatesser/Code/flutter_master/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true -DFLUTTER_WEB_USE_SKIA=true
--output-dill
/var/folders/6w/rnw9ch3d2cv277x3nzm9t9ph0000gn/T/flutter_tools.svAXbQ/flutter_to
ol.L0zH3w/app.dill --libraries-spec
file:///Users/tahatesser/Code/flutter_master/bin/cache/flutter_web_sdk/libraries
.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-root
/var/folders/6w/rnw9ch3d2cv277x3nzm9t9ph0000gn/T/flutter_tools.svAXbQ/flutter_to
ols.rLaHSd --filesystem-scheme org-dartlang-app --initialize-from-dill
build/3b22c16eb48c043f81099103590514a0.cache.dill.track.dill --platform
file:///Users/tahatesser/Code/flutter_master/bin/cache/flutter_web_sdk/kernel/fl
utter_ddc_sdk.dill --no-sound-null-safety
[   +8 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+2417 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad7,12",
                        "identifier" : "01A7720C-88FE-4491-AB2E-100CFD7775EE",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-7-wwan-1",
                        "modelName" : "iPad (7th generation)",
                        "name" : "iPad (7th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone13,2",
                        "identifier" : "572593A3-647B-413C-9188-B91DD07DEAF0",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-12-1",
                        "modelName" : "iPhone 12",
                        "name" : "iPhone 12"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "14.1 (18A8395)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.iphoneos",
                        "modelCode" : "iPad11,6",
                        "identifier" : "00008020-000255113EE8402E",
                        "architecture" : "arm64e",
                        "modelUTI" : "com.apple.ipad-8-wifi-1",
                        "modelName" : "iPad (8th generation)",
                        "name" : "Taha’s iPad"
                      }
                    ]
[   +3 ms] [
             {
               "simulator" : true,
               "operatingSystemVersion" : "14.1 (18A8394)",
               "available" : true,
               "platform" : "com.apple.platform.iphonesimulator",
               "modelCode" : "iPad7,12",
               "identifier" : "01A7720C-88FE-4491-AB2E-100CFD7775EE",
               "architecture" : "x86_64",
               "modelUTI" : "com.apple.ipad-7-wwan-1",
               "modelName" : "iPad (7th generation)",
               "name" : "iPad (7th generation)"
             },
             {
               "simulator" : true,
               "operatingSystemVersion" : "14.1 (18A8394)",
               "available" : true,
               "platform" : "com.apple.platform.iphonesimulator",
               "modelCode" : "iPhone13,2",
               "identifier" : "572593A3-647B-413C-9188-B91DD07DEAF0",
               "architecture" : "x86_64",
               "modelUTI" : "com.apple.iphone-12-1",
               "modelName" : "iPhone 12",
               "name" : "iPhone 12"
             },
             {
               "simulator" : false,
               "operatingSystemVersion" : "14.1 (18A8395)",
               "interface" : "usb",
               "available" : true,
               "platform" : "com.apple.platform.iphoneos",
               "modelCode" : "iPad11,6",
               "identifier" : "00008020-000255113EE8402E",
               "architecture" : "arm64e",
               "modelUTI" : "com.apple.ipad-8-wifi-1",
               "modelName" : "iPad (8th generation)",
               "name" : "Taha’s iPad"
             }
           ]
[+12839 ms] Syncing files to device Chrome... (completed in 15.4s)
[        ] Synced 28.4MB.
[        ] <- accept
[        ] Caching compiled dill
[ +224 ms] Using Google Chrome 86.0.4240.111 

[ +538 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:63218/devtools/browser/0f35a395-0670-420b-8e3e-e2d7aa3395cb
[ +957 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata
[+2191 ms] DevHandler: Debug service listening on
ws://127.0.0.1:63238/JI_JbYllbCY=/ws

[   +4 ms] Debug service listening on ws://127.0.0.1:63238/JI_JbYllbCY=/ws
[   +1 ms] Warning: Flutter's support for web development is not stable yet and
hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
[+1213 ms] Failed to load font MaterialIcons at assets/fonts/MaterialIcons-Regular.otf
[        ] null
[   +3 ms] Error: Expected a value of type 'Future<_RegisteredFont>', but got one of type
           '_Future<_RegisteredFont?>'
               at Object.throw_ [as throw] (http://localhost:63204/dart_sdk.js:4193:11)
               at Object.castError (http://localhost:63204/dart_sdk.js:4166:15)
               at Object.cast [as as] (http://localhost:63204/dart_sdk.js:4475:17)
               at Function.as_C [as as] (http://localhost:63204/dart_sdk.js:4122:19)
               at Array.[dartx.add] (http://localhost:63204/dart_sdk.js:14333:11)
               at _engine.SkiaFontCollection.new.registerFonts
               (http://localhost:63204/dart_sdk.js:130488:39)
               at registerFonts.next (<anonymous>)
               at http://localhost:63204/dart_sdk.js:36140:33
               at _RootZone.runUnary (http://localhost:63204/dart_sdk.js:36008:59)
               at _FutureListener.thenAwait.handleValue
(http://localhost:63204/dart_sdk.js:31237:29)
               at handleValueCallback (http://localhost:63204/dart_sdk.js:31752:49)
               at Function._propagateToListeners
(http://localhost:63204/dart_sdk.js:31790:17)
               at _Future.new.[_completeWithValue]
(http://localhost:63204/dart_sdk.js:31638:23)
               at async._AsyncCallbackEntry.new.callback
               (http://localhost:63204/dart_sdk.js:31659:35)
               at Object._microtaskLoop (http://localhost:63204/dart_sdk.js:36245:13)
               at _startMicrotaskLoop (http://localhost:63204/dart_sdk.js:36251:13)
               at http://localhost:63204/dart_sdk.js:31999:9

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-7.0.pre.51, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-7.0.pre.51 at /Users/tahatesser/Code/flutter_master
    • Framework revision 734d2a22fe (2 hours ago), 2020-11-02 15:23:02 +0530
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.1
    • macOS (desktop)      • macos                     • darwin-x64     • Mac OS
      X 10.15.7 19H2 darwin-x64
    • Web Server (web)     • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 86.0.4240.111

• No issues found!

```

</details>

**Comment by pedromassangocode** [comment] 2020-11-02 13:10
Reproducible. This seems to be caused by null-safety implementation.

```
[        ] Error: Expected a value of type 'Future<_RegisteredFont>', but got one of type '_Future<_RegisteredFont?>'
               at Object.throw_ [as throw] (http://localhost:51270/dart_sdk.js:4193:11)
               at Object.castError (http://localhost:51270/dart_sdk.js:4166:15)
               at Object.cast [as as] (http://localhost:51270/dart_sdk.js:4475:17)
               at Function.as_C [as as] (http://localhost:51270/dart_sdk.js:4122:19)
               at Array.[dartx.add] (http://localhost:51270/dart_sdk.js:14333:11)
               at _engine.SkiaFontCollection.new.registerFonts (http://localhost:51270/dart_sdk.js:130488:39)
               at registerFonts.next (<anonymous>)
               at http://localhost:51270/dart_sdk.js:36140:33
               at _RootZone.runUnary (http://localhost:51270/dart_sdk.js:36008:59)
               at _FutureListener.thenAwait.handleValue (http://localhost:51270/dart_sdk.js:31237:29)
               at handleValueCallback (http://localhost:51270/dart_sdk.js:31752:49)
               at Function._propagateToListeners (http://localhost:51270/dart_sdk.js:31790:17)
               at _Future.new.[_completeWithValue] (http://localhost:51270/dart_sdk.js:31638:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:51270/dart_sdk.js:31659:35)
               at Object._microtaskLoop (http://localhost:51270/dart_sdk.js:36245:13)
               at _startMicrotaskLoop (http://localhost:51270/dart_sdk.js:36251:13)
               at http://localhost:51270/dart_sdk.js:31999:9
```

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-7.0.pre.51, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-7.0.pre.51 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 734d2a22fe (3 hours ago), 2020-11-02 15:23:02 +0530
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by ferhatb** [comment] 2020-11-02 17:39
See https://github.com/flutter/engine/pull/22248

**Comment by pcsosinski** [comment] 2020-11-02 20:53
@ferhatb will 22248 address https://github.com/flutter/flutter/issues/69571 as well?

**Comment by ferhatb** [comment] 2020-11-02 22:27
No a separate fix landed.

**Comment by ferhatb** [comment] 2020-11-03 00:47
Should land in flutter master shortly. Closing.

**Closed by ferhatb** 2020-11-03 00:47 UTC
Labels: a: null-safety, e: web_canvaskit, engine, found in release: 1.24, has reproducible steps, platform-web, severe: crash, severe: regression, waiting for PR to land (fixed)
