### ISSUE TITLE
Devicelab task runner does not run all tasks with -a flag

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#74660] opened 2021-01-25 17:57 UTC
`cd dev/devicelab && dart bin/run.dart -a` does not run all devicelab tests as documented in the README https://github.com/flutter/flutter/tree/2007186d2ed7a9754480cb9b8e2562604b2d17ef/dev/devicelab#running-all-tests

@godofredoc says https://github.com/flutter/flutter/pull/74459#issuecomment-765637492
> -a is trying to use stages, individual tests should still run. If we want to keep that functionality we need to update the runner to read prod_config.json instead of manifest.yaml

`dart bin/run.dart -t <test>` still works.
Either update the README doc or get this working (I personally have never used `-a` to run all tests, but @xster used it).

**Comment by xster** [comment] 2021-01-26 07:26
Useful when you make a risky change and want to make sure everything will go ok without waiting for post-submit.

**Comment by godofredoc** [comment] 2021-01-26 18:52
\cc @CaseyHillers as this affects your design for splitting builds and tests

**Comment by CaseyHillers** [comment] 2021-01-26 19:34
The issue is that `--all` loads all the tasks from the devicelab manifest. With infra moving the devicelab manifest to be contained in the luci configs, the test runner is not finding tests to run.

**Comment by godofredoc** [comment] 2023-06-13 18:53
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.

**Closed by godofredoc** 2023-06-13 18:53 UTC
Labels: team, passed first triage, team: infra, good first contribution, passed secondary triage
