### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123

### ISSUE THREAD

**Issue by darmakusumaa** [flutter/flutter#126335] opened 2023-05-09 15:12 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:498:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:497:12)
#5      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1024:43)
#6      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:857:37)
#7      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:744:9)
#8      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:250:54)
<asynchronous suspension>
#9      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:469:26)
<asynchronous suspension>
#10     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:284:41)
<asynchronous suspension>
#11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.22621.1555], locale en-ID)
    [32m•[39m Flutter version 3.7.7 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2ad6cd72c0 (9 weeks ago), 2023-03-08 09:41:59 -0800
    [32m•[39m Engine revision 1837b5be5f
    [32m•[39m Dart version 2.19.4
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    [32m•[39m Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    [32m•[39m Platform android-33-ext5, build-tools 34.0.0-rc2
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.5.33502.453
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[32m[✓][39m VS Code (version 1.78.0)
    [32m•[39m VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.62.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.35

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: eb6d86ee27deecba4a83536aa20f366a6044895c
### Plugins
path_provider-2.0.14
path_provider_android-2.0.27
path_provider_foundation-2.2.2
path_provider_linux-2.1.10
path_provider_windows-2.1.6

**Comment by tomg2012** [comment] 2023-05-09 15:45
Hi, can you provide sample code that generates this error? Also, what is your target device? Is it an Android device, web, or Windows?

**Comment by huycozy** [comment] 2023-05-10 06:11
Closing as duplicate of https://github.com/flutter/flutter/issues/99954.

**Closed by huycozy** 2023-05-10 06:11 UTC
Labels: in triage
