### ISSUE TITLE
Issue with mapbox street map 

### ISSUE THREAD

**Issue by hamzaehsansatti** [flutter/flutter#65385] opened 2020-09-08 13:34 UTC
i am trying to add mapbox street view map in my flutter project but it is not working

Here is the error. I have integrated necessary things. url,accesstoken,id but still is not working

I/flutter ( 1743): The following assertion was thrown building LayoutBuilder:
I/flutter ( 1743): Can't find correct layer for null. Perhaps when you create your FlutterMap you need something like
I/flutter ( 1743): this:
I/flutter ( 1743): 
I/flutter ( 1743):     options: new MapOptions(plugins: [MyFlutterMapPlugin()])
I/flutter ( 1743): 'package:flutter_map/src/map/flutter_map_state.dart':
I/flutter ( 1743): Failed assertion: line 191 pos 12: 'false'
I/flutter ( 1743): 
I/flutter ( 1743): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 1743): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 1743): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 1743):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 1743): 
I/flutter ( 1743): The relevant error-causing widget was:
I/flutter ( 1743):   LayoutBuilder
I/flutter ( 1743):   file:///C:/Program%20Files/Android/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.10.1+1/lib/src/map/flutter_map_state.dart:77:12
I/flutter ( 1743): 
I/flutter ( 1743): When the exception was thrown, this was the stack:
I/flutter ( 1743): #2      FlutterMapState._createLayer (package:flutter_map/src/map/flutter_map_state.dart:191:12)
I/flutter ( 1743): #3      FlutterMapState.build.<anonymous closure>.<anonymous closure> (package:flutter_map/src/map/flutter_map_state.dart:106:30)
I/flutter ( 1743): #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
I/flutter ( 1743): #5      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
I/flutter ( 1743): #6      FlutterMapState.build.<anonymous closure> (package:flutter_map/src/map/flutter_map_state.dart)
I/flutter ( 1743): #7      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart)
I/flutter ( 1743): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter ( 1743): #9      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:95:11)
I/flutter ( 1743): #10     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1823:58)
I/flutter ( 1743): #11     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
I/flutter ( 1743): #12     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1823:13)
I/flutter ( 1743): #13     RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:173:5)
I/flutter ( 1743): #14     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:240:5)
I/flutter ( 1743): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #16     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 1743): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #18     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter ( 1743): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #20     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
I/flutter ( 1743): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #22     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:497:13)
I/flutter ( 1743): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #42     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
I/flutter ( 1743): #43     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
I/flutter ( 1743): #44     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
I/flutter ( 1743): #45     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
I/flutter ( 1743): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #50     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
I/flutter ( 1743): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #67     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
I/flutter ( 1743): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #69     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter ( 1743): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 1743): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 1743): #83     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
I/flutter ( 1743): #84     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
I/flutter ( 1743): #85     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
I/flutter ( 1743): #86     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
I/flutter ( 1743): #87     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
I/flutter ( 1743): #88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter ( 1743): #89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter ( 1743): #90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter ( 1743): #91     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
I/flutter ( 1743): #100    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter ( 1743): #101    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter ( 1743): #102    _RawReceivePortImpl._handleMessage

**Comment by pedromassangocode** [comment] 2020-09-08 14:23
Hi @hamzaehsansatti 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [flutter_map repository](https://github.com/fleaflet/flutter_map).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-08 14:23 UTC

**Comment by hamzaehsansatti** [comment] 2020-09-09 10:19
yeah it was not issue with flutter it was issue with the url that is was using from mapbox.com website
