### ISSUE TITLE
App Bar with bottom widget seems to have a bottom border when elevation = 0

### ISSUE THREAD

**Issue by alexwhiteside1** [flutter/flutter#16262] opened 2018-04-05 03:32 UTC
Create a standard scaffold with AppBar and bottom element. Make the elevation 0. The primary body child does not matter, as long as it is also a dark color. You should see a full width line below the bottom widget. Removing the bottom widget removes the line completely. The line also does not seem to show on the emulator, but appears on real devices (Pixel and Galaxy) in both debug and release modes. 

See code below and attached screenshot. 

```dart
return new Scaffold(
        backgroundColor: BirchColors.gray.shade300,
        appBar: new AppBar(
          elevation: 0.0,
          title: new Text(widget.transaction.merchantDetails,
              style: BirchText.appBarTitle),
          bottom: new PreferredSize(
              child: new Container(
                  color: BirchColors.primary,
                  padding: const EdgeInsets.all(5.0),
                  child: new Text(
                    new DateFormat.yMMMMd("en_US")
                        .format(widget.transaction.date),
                    style: BirchText.appBarTitleAction,
                  )),
              preferredSize: const Size.fromHeight(20.0)),
        ),
        body: new Container(
          child: new SingleChildScrollView(
```

## Flutter Doctor

```terminal
[✓] Flutter (Channel dev, v0.2.4, on Mac OS X 10.13 17A405, locale en-US)
    • Flutter version 0.2.4 at /Users/alexwhiteside/Development/Flutter/flutter
    • Framework revision 3352a3fb48 (2 weeks ago), 2018-03-20 19:30:06 +0100
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/alexwhiteside/Library/Android/sdk
    • Android NDK at /Users/alexwhiteside/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424.63

[✓] Connected devices (2 available)
    • Pixel                     • FA6CE0303326  • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by alexwhiteside1** [comment] 2018-04-05 03:32
![screenshot_20180404-195524](https://user-images.githubusercontent.com/5420059/38346030-59cfe24e-3847-11e8-9f95-d647e64acc36.png)

**Comment by alexwhiteside1** [comment] 2018-04-05 03:38
Removing the bottom bar, everything works fine. 

![screenshot_20180404-203717](https://user-images.githubusercontent.com/5420059/38346143-0e929960-3848-11e8-8f91-a05637404e13.png)

**Comment by eseidelGoogle** [comment] 2018-04-05 19:43
So presumably this is a pixel rounding issue?  @HansMuller

**Comment by HansMuller** [comment] 2018-04-05 19:44
I think what you're seeing is the effect of antialiasing the top edge of the appbar's bottom widget with the appbar's background color. Does making the the AppBar's backgroundColor BirchColors.primary fix the problem?

**Comment by HansMuller** [comment] 2018-04-05 19:46
This issue has come up before, see for example https://github.com/flutter/flutter/issues/15035

**Comment by alexwhiteside1** [comment] 2018-04-05 20:02
Setting the AppBar's background color didn't change anything. The app bar inherits the theme category by default I believe (which is Birch.primary)

**Comment by alexwhiteside1** [comment] 2018-04-05 20:04
I also just tried removing the backgroundColor from the container in PreferredSize Widget, which also didn't change anything.

**Comment by alexwhiteside1** [comment] 2018-04-05 20:25
See attached complete widget:

```
import 'package:flutter/material.dart';

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(backgroundColor: Colors.red,
      appBar: new AppBar(
        backgroundColor: Colors.blue,
        elevation: 0.0,
        title: new Text("App Bar"), bottom: new PreferredSize(
          child: new Container(
            padding: const EdgeInsets.all(5.0),
            child: new Text(
                "Bottom Bar"),
          ),
          preferredSize: const Size.fromHeight(20.0)),
      ),
      body: new Container(color: Colors.blue,
        child: new Center(child: new Text("body")),
        constraints: new BoxConstraints.expand(height: 25.0),),);
  }


}
```

**Comment by HansMuller** [comment] 2018-04-05 20:30
Thanks for the sample; I'll give it a try

**Comment by alexwhiteside1** [comment] 2018-04-05 20:30
My only concern about making the scaffold backgroundColor the same color as the appBar is that I would need to make sure the body is ALWAYS the remainder of the height so I could control the rest of the background color. Though I imagine this same issue would occur on the bottom boundary with the nav.

**Comment by HansMuller** [comment] 2018-04-05 20:35
I haven't been able to reproduce the problem with a Nexus5 or a Motorola G4. Will try with a Pixel

**Comment by HansMuller** [comment] 2018-04-05 20:37
I can reproduce the problem on a Pixel.  Good.

**Comment by HansMuller** [comment] 2018-04-05 20:48
If you enclose the Scaffold's body in a `SizedBox.expand` widget, the body will always fill the remaining space. Then, as you pointed out, specifying the Scaffold's backgroundColor, hides the problem.

**Comment by alexwhiteside1** [comment] 2018-04-05 21:09
Gotcha, it's not going to be fun with the stack view in the middle, since I'll have to make those overlaps line up for varying sized widgets. But it'll work as a work around. 

Thanks.

**Comment by HansMuller** [comment] 2018-04-05 21:13
Still looking into this. The problem is sensitive to the device (Pixel) and the height of the bottom widget (>= 32.0 seems to mask the problem).  The widget's renderer appears to have sensible whole number values for its Y coordinate and height.

**Comment by Hixie** [comment] 2018-04-10 23:05
are they still whole numbers when you multiply by the device pixel ratio?

**Comment by Hixie** [comment] 2018-04-10 23:08
Is the problem that there are two boxes with the same colour both over a different background color?
We really should document that as a problem to be careful about.
Fundamentally the problem is devices with weird (not power-of-2) dprs...

**Comment by Hixie** [comment] 2018-04-17 23:25
I'm going to remove the customer:blocker label since it sounds like you are no longer blocked, but don't hesitate to reach out if this is still a blocker.

If the problem is indeed what we think it is, then it's more or less working as intended, and we will treat this as a documentation issue. It's not really clear what else we can do.

**Comment by alexwhiteside1** [comment] 2018-04-17 23:45
It's no longer a blocker. I changed some heights and its not noticeable. Thanks for the help though!

**Comment by goderbauer** [comment] 2018-12-28 22:03
Improving the docs for this is already tracked at https://github.com/flutter/flutter/issues/14288. So, I am closing this for now.

**Closed by goderbauer** 2018-12-28 22:03 UTC
Labels: customer: paper, d: api docs, dependency: skia, framework

**Comment by shanthakumarf22** [comment] 2020-01-19 12:02
I did a temporary fix by giving `extendBodyBehindAppBar: true,` to `Scaffold()` and adding a margin to scaffold body.

**Comment by 5hanth** [comment] 2020-01-19 12:02
I did a temporary fix by giving extendBodyBehindAppBar: true, to Scaffold() and adding a margin to scaffold body.

**Comment by fabioselau077** [comment] 2020-04-02 07:23
Hello, it has nothing to do with the problem but how did you create this buttombar?
