### ISSUE TITLE
please support short sound effects in flutter

### ISSUE THREAD

**Issue by mfa95** [flutter/flutter#122301] opened 2023-03-09 16:00 UTC
I'm new to flutter but I've been researching for 1 week to use short sound effects in my application. and I was disappointed. very difficult and very problematic

this is a big miss. it uses short sound effects like at least in all applications (button sounds, page refresh sounds, notification sounds, etc.). Not everyone needs an advanced music player, but short sound effects are essential for everyone.

Trying to create short sound effects with these music player packs is cumbersome. They weren't made for this. It has a lot of features but it causes delay in sound. and often skips sounds. (try making clicking sound in counter app and click very fast)

There are a few packs for short sound effects (soundpool etc) but these packs were last updated 12 months, 24 months or 3 years ago. they also don't have effects like pitch. very limited. (most features not available in android's soundpool system)

anyway please find a solution to this. Installing a sound system into an application constitutes the longest and most laborious development process.

At least in the kernel an interface should be created and provided (a standard) for 3rd party packages. In this way, all packages can provide the same features using different methods. This results in a quality race. it would be good.

support short sound effects in flutter. thanks.

(sorry i used google translate. i hope it translated well)

**Comment by stuartmorgan** [comment] 2023-03-09 16:35
Closing as a duplicate of https://github.com/flutter/flutter/issues/47105

**Closed by stuartmorgan** 2023-03-09 16:35 UTC
