### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Flutter36** [flutter/flutter#139474] opened 2023-12-04 12:43 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We have a flutter app which is trying to connect to a server side API having Self signed certificate by an internal CA. The app is able to connect to the server API correctly through IOS device but not on android device. Getting below errors.

```
11-30 11:44:46.824  3469  3521 I flutter : Exception: HandshakeException: Handshake error in client (OS Error: 
11-30 11:44:46.824  3469  3521 I flutter : 	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:393))
```

Note: These certificates are installed through Airwatch on the device under user folder. Have tried adding the network security config to trust all certificates trusted under user but still it fails with above error. Would be helpful to get more help on debugging this further more.

Network security config details
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            
            <certificates src="system"/>
            
            <certificates src="user"/>
        </trust-anchors>
    </base-config>
</network-security-config>

<application
    android:networkSecurityConfig="@xml/network_security_config"
    ...>
    ...
</application>

### Expected results

HTTP request should go through and the self signed certificate should be accepted.

### Actual results

HTTP request is not going through and the self signed certificate verification fails.

### Code sample

    var response = await http.get(
        Uri.parse("$serverUrl/api/v1/XXXXX"),
        headers: <String, String>{
          'Content-Type': 'application/json'
        }).catchError((error, stackTrace) {
      loggingService.error(
          '<log error>');
      throw Exception(error);
    });

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

11-30 11:44:46.824  3469  3521 I flutter : Exception: HandshakeException: Handshake error in client (OS Error: 
11-30 11:44:46.824  3469  3521 I flutter : 	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:393))

### Flutter Doctor output

/opt/hostedtoolcache/Flutter/3.10.2/linux/flutter/bin/flutter doctor -v
[✓] Flutter (Channel stable, 3.10.2, on Ubuntu 22.04.3 LTS 6.2.0-1016-azure, locale C.UTF-8)
    • Flutter version 3.10.2 on channel stable at /opt/hostedtoolcache/Flutter/3.10.2/linux/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (6 months ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /usr/local/lib/android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /usr/local/lib/android/sdk
    • ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
    • Java binary at: /usr/lib/jvm/temurin-11-jdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.27.8
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-1016-azure
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

**Comment by darshankawar** [comment] 2023-12-05 07:26
@Flutter36 
I think this is duplicate of https://github.com/flutter/flutter/issues/56607, so please follow-up in it for further updates.
Closing this from here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-12-05 07:26 UTC
Labels: in triage

**Comment by Flutter36** [comment] 2023-12-12 01:42
@darshankawar., My issue is on a httpclient call inside the app to a server and not during a Flutter pub get. I think both are different issues and I would request to reopen the bug to relook at this.

Also, just to mention, below is the network security config which I am using currently.

<network-security-config>
    <base-config>
        <trust-anchors>
            
            <certificates src="system"/>
            
            <certificates src="user"/>
        </trust-anchors>
    </base-config>
</network-security-config>

**Comment by darshankawar** [comment] 2023-12-12 05:41
Please check https://github.com/flutter/flutter/issues/50699 and underlying comments to see if they help in your case or not.
