### ISSUE TITLE
[ maps / platform-views ] google_maps_flutter - application crashes & exits when GoogleMap() is created 

### ISSUE THREAD

**Issue by genjm** [flutter/flutter#27185] opened 2019-01-28 15:53 UTC
Initially version `0.0.3` of the plugin was working well for me but now whenever I try to run my application, it crashes as soon as I navigate to the screen with the Map on it.

The output is as follows:
```
*** First throw call stack:
(
0   CoreFoundation                      0x000000010d1341bb __exceptionPreprocess + 331
1   libobjc.A.dylib                     0x000000010c6da735 objc_exception_throw + 48
2   CoreFoundation                      0x000000010d134015 +[NSException raise:format:] + 197
3   Runner                              0x00000001074eab63 +[GMSServices checkServicePreconditions] + 182
4   Runner                              0x00000001074e79a2 +[GMSServices sharedServicesSync] + 110
5   Runner                              0x00000001074d73f9 -[GMSMapView sharedInitWithServices:camera:forPlaces:] + 156
6   Runner                              0x00000001074d6861 -[GMSMapView initWithFrame:camera:] + 123
7   Runner                              0x00000001074d6685 +[GMSMapView mapWithFrame:camera:] + 104
8   Runner <…>
Lost connection to device.
Exited (sigterm)
```
I am using the latest version of flutter & the latest version of the plugin ( 0.2.0 at the time of posting this ).

The behaviour is exactly the same if I use the example code ( although that doesn't work out of the box due to not supplying the `GoogleMaps()` with an initial camera position ) but once you add an `initialCameraPosition`, it crashes with the same stack trace as I posted above.

I am developing on OSX, using Visual Studio Code & the behaviour can be replicated on either the iOS Simulator or a physical iOS device.

If I can provide any other information which may be helpful please let me know, this is the first time I've logged an issue on GIT so hopefully the above is sufficient.

Thanks.

**Comment by wouterhardeman** [comment] 2019-01-28 16:49
You likely forgot to add the API key. Take a look at this issue: https://github.com/flutter/flutter/issues/17894

**Comment by zoechi** [comment] 2019-01-28 16:55
Duplicate of #17894

**Closed by zoechi** 2019-01-28 16:55 UTC
Labels: p: first party, p: maps, plugin, severe: crash
