### ISSUE TITLE
This requires the 'non-nullable' experiment to be enabled.

### ISSUE THREAD

**Issue by MohammadEhsanMirzaaee** [flutter/flutter#51846] opened 2020-03-03 13:29 UTC
Hi, I created a file with this name "analysis_options.yaml"  in root of my project and add these lines "analyzer:
  enable-experiment:
    - non-nullable" 
to it, but when I use "flutter run" command I receive below error for two places that I use this: "?"

Error: This requires the 'non-nullable' experiment to be enabled.
Try enabling this experiment by adding it to the command line when compiling and running.

**Comment by TahaTesser** [comment] 2020-03-03 13:37
Hi @MohammadEhsanMirzaaee 

"Unfortunately I don't think it's possible to get --enable-experiment:non-nullable working "
Please take a look at this [coment](https://github.com/flutter/flutter/issues/40490#issuecomment-552656395)

Duplicate of [40490rl](https://github.com/flutter/flutter/issues/40490rl)
Please follow up there 
Thank you

**Closed by TahaTesser** 2020-03-03 13:37 UTC

**Comment by mpfaff** [comment] 2020-06-02 15:39
#40490 was locked by the stale bot, so can we continue the discussion here? The issue is by no means fixed, so closing and locking conversations is just insulting to the community.

**Comment by nickroeker** [comment] 2020-06-19 01:07
I echo the above, this discussion needs to continue now more than ever before.

It's still pretty fresh (following link is dated June 10th), but non-nullable/NNBD is available on the `beta` channel now: https://medium.com/dartlang/announcing-sound-null-safety-defd2216a6f3

I'm specifically trying with `sdk: ">=2.9.0-14.1.beta <3.0.0"` right now. I won't state things on behalf of the Dart team, but it seems that non-nullable types are indeed coming soon to a stable release.

With a very short exercise in converting code to use NNBD, I actually found a few bugs. One seems to be just from general improvements to the analyzer as a result, but a couple are definitely regarding null safety. And these were found in my Flutter-specific code as well as some "backend" utilities of the app. As disheartening as this was (I assure you I was _trying_ to be safe with this project), it really highlights the benefit of bringing NNBD to Flutter apps.

For now I'll have to sigh and convert my code back to the land of unknown nulls (plus a few fixes!), but I now yearn for the NNDB future.

Rather than just "this can't happen", can we start a discussion on "what do we need to get this to work?"? (Truthfully I hope there's already a plan, but we can start here if not).

I'd hate to see Flutter die because Dart outgrew it and confused the community. That would be awkward.

**Comment by TahaTesser** [comment] 2020-07-06 14:21
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by dimitar-nikovski** [comment] 2020-12-10 13:50
Additionally to the packages migration and the enable-experiment in `analysis_options`, I also needed to explicitly run the `build_runner build` with the flag `--enable-experiment non-nullable` and it worked

**Comment by exeptionerror** [comment] 2021-06-21 12:19
All Working Possible Solution [[Solved] Error: This requires the ‘non-nullable’ experiment to be enabled](https://fluttercorner.com/error-this-requires-the-non-nullable-experiment-to-be-enabled/)
