### ISSUE TITLE
Error sharing with Share plugin

### ISSUE THREAD

**Issue by carlinho11** [flutter/flutter#76524] opened 2021-02-22 12:59 UTC
Good Morning!

When using the Share plugin to share on facebook and instagram, do not send the "text", only the image. Is there any way to solve it?

I thank the attention!

**Comment by carlinho11** [comment] 2021-02-22 13:00
I use:  share: ^0.6.5+4

**Comment by TahaTesser** [comment] 2021-02-22 14:32
Hi @carlinho11 
I can reproduce the using latest `share: ^0.6.5+4`, this seems to be a duplicate of https://github.com/flutter/flutter/issues/36438
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-22 14:32 UTC
Labels: in triage
