### ISSUE TITLE
Flutter version command replaces the first v character

### ISSUE THREAD

**Issue by sososdk** [flutter/flutter#55659] opened 2020-04-26 03:01 UTC
## Steps to Reproduce
![image](https://user-images.githubusercontent.com/46806014/80296316-6f522300-87ac-11ea-9e3a-f4cc7c0f22d0.png)

## flutter doctor -v
```
    • Flutter version 1.18.0-9.0.pre.13 at /Users/xxx/fvm/versions/master
    • Framework revision d72eea539e (6 hours ago), 2020-04-25 14:27:55 -0700
    • Engine revision 2b94311a77
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 94178e920e)
```

**Comment by VladyslavBondarenko** [comment] 2020-04-27 09:22
Duplicate of https://github.com/flutter/flutter/issues/55421

**Closed by VladyslavBondarenko** 2020-04-27 09:22 UTC
