### ISSUE TITLE
Crash in unhandled exception reporting in the flutter runner.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#32780] opened 2019-05-15 21:49 UTC
Placeholder to surface https://fuchsia.atlassian.net/browse/FL-256 to triage team. When that issue is closed, please close this issue.

**Comment by Hixie** [comment] 2019-06-11 16:54
Removing from critical list per @kf6gpe

**Comment by Hixie** [comment] 2019-06-12 19:48
Duplicate of https://github.com/flutter/flutter/issues/34343

**Closed by Hixie** 2019-06-12 19:48 UTC
Labels: customer: fuchsia, engine, severe: crash
