### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Acesso negado., errno = 5

### ISSUE THREAD

**Issue by DeividAlmeida** [flutter/flutter#99552] opened 2022-03-04 14:26 UTC
%23%23 Command
```
flutter run -d Chrome
```

%23%23 Steps to Reproduce
1. ...
2. ...
3. ...

%23%23 Logs
FileSystemException: Directory listing failed, OS Error: Acesso negado.
, errno = 5
```
%230      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
%231      _Directory.listSync (dart:io/directory_impl.dart:243:5)
%232      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
%233      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
%234      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:953:78)
%235      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:792:37)
%236      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:697:9)
%237      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
%238      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:496:26)
<asynchronous suspension>
%239      ResidentWebRunner.restart (package:flutter_tools/src/isolated/resident_web_runner.dart:359:37)
<asynchronous suspension>
%2310     TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1627:40)
<asynchronous suspension>
%2311     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.2, on Microsoft Windows [versÃ£o 10.0.19044.1526], locale pt-BR)
    • Flutter version 2.10.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deivid\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed

**Comment by iapicca** [comment] 2022-03-04 18:18
duplicate? https://github.com/flutter/flutter/issues/96568

**Comment by darshankawar** [comment] 2022-03-07 06:10
Closing this as duplicate of https://github.com/flutter/flutter/issues/92695

**Closed by darshankawar** 2022-03-07 06:10 UTC
Labels: in triage
