### ISSUE TITLE
No signature of method: build_920bd04w3g7a2thu3a2loeauc.android() is applicable for argument types:

### ISSUE THREAD

**Issue by Titos23** [flutter/flutter#107428] opened 2022-07-11 21:33 UTC
I was running  `flutter build apk --split-per-abi` on my code in order to build the release apk. I modified some fields as showed down. Then this error occured.Is there any solution to solve the problem ?  
     
     FAILURE: Build failed with an exception.
    
    * Where:
    Build file 'D:\Flutter Workspace\myubuntu\android\app\build.gradle' line: 35
    
    * What went wrong:
    A problem occurred evaluating project ':app'.
    > No signature of method: build_920bd04w3g7a2thu3a2loeauc.android() is applicable for argument types: (build_920bd04w3g7a2thu3a2loeauc$_run_closure2) values: [build_920bd04w3g7a2thu3a2loeauc$_run_closure2@48f16130]
    
    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 3m 31s

<details>
<summary>
build.gradle(app)

      def localProperties = new Properties()
      def localPropertiesFile = rootProject.file('local.properties')
      if (localPropertiesFile.exists()) {
          localPropertiesFile.withReader('UTF-8') { reader ->
              localProperties.load(reader)
          }
      }
    
    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }
    
    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        flutterVersionCode = '1'
    }
    
    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        flutterVersionName = '1.0'
    }
    
    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
    apply plugin: 'com.google.gms.google-services'
    
    def keystoreProperties = new Properties()
    def keystorePropertiesFile = rootProject.file('key.properties')
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    }
    
    android {
        compileSdkVersion 29
        ndkVersion flutter.ndkVersion
    
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    
        kotlinOptions {
            jvmTarget = '1.8'
        }
    
        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }
    
        defaultConfig {
            // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
            applicationId "com.titos.myubuntu"
            // You can update the following values to match your application needs.
            // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
            minSdkVersion 21
            targetSdkVersion 29
            versionCode 1
            versionName 1.0.0
        }
    
       signingConfigs {
           release {
               keyAlias keystoreProperties['keyAlias']
               keyPassword keystoreProperties['keyPassword']
               storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
               storePassword keystoreProperties['storePassword']
           }
       }
       buildTypes {
           release {
               signingConfig signingConfigs.release
           }
       }
    
    }
    
    flutter {
        source '../..'
    }
    
    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
        implementation platform('com.google.firebase:firebase-bom:30.2.0')
    }
  gradle wrapper

    distributionBase=GRADLE_USER_HOME
    distributionPath=wrapper/dists
    zipStoreBase=GRADLE_USER_HOME
    zipStorePath=wrapper/dists
    distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
</summary>

```dart
```

</details>

**Comment by maheshmnj** [comment] 2022-07-12 08:19
Hi @Titos23, Thanks for filing the issue. Can you please share the complete output of `flutter run -v` in a textfile? Also please check if this [StackOverflow thread](https://stackoverflow.com/questions/61807520/how-to-fix-error-no-signature-of-method-build-ap86oam3dut3pxce3x49rdtma-androi) helps fix the issue

**Comment by Titos23** [comment] 2022-07-12 16:58
@maheshmnj 
This is the output of `flutter run -v`. Unfortunately, the thread didn't help me.
[logs.txt](https://github.com/flutter/flutter/files/9095062/logs.txt)

**Comment by IsmailAlamKhan** [comment] 2022-07-13 09:18
I have the same error but it doesn't happen when I try to run `flutter build apk --split-per-abi lib/main_release_prof.dart --no-tree-shake-icons` locally on my PC, this error happens when I try to run this command using GH actions
 ```
 * What went wrong:
A problem occurred evaluating project ':record'.
> No signature of method: build_rgwhtxfe7wytj5wwooj9592.android() is applicable for argument types: (build_rgwhtxfe7wytj5wwooj9592$_run_closure2) values: [build_rgwhtxfe7wytj5wwooj9592$_run_closure2@62ae33c0]
```
Everything was working before 3.0.4.

**Comment by IsmailAlamKhan** [comment] 2022-07-13 09:29
![image](https://user-images.githubusercontent.com/67656229/178700560-3341f0ee-fd2c-4105-a425-090bf1a9c16a.png)
hmm same thing with Flutter 3.0.3. Let me try last time with Flutter 3.

**Comment by IsmailAlamKhan** [comment] 2022-07-13 18:34
> I don't really know what was the problem but I just reverted the build files to the old versions and modified them again. And after that everything was fine.

You mean to say run flutter clean?

**Comment by Titos23** [comment] 2022-07-13 18:39
Not at all. I returned to the debug release configurations build file  and I modified it carefully to get the release configurations. Fortunately the error was fixed.

**Comment by IsmailAlamKhan** [comment] 2022-07-13 18:41
> Not at all. I returned to the debug release configurations build file  and I modified it carefully to get the release configurations. Fortunately the error was fixed.

Ah ok

**Comment by maheshmnj** [comment] 2022-07-14 09:08
>Not at all. I returned to the debug release configurations build file and I modified it carefully to get the release configurations. Fortunately the error was fixed.

provided that this issue no longer reproduces, I am going to close this issue. Incase you encounter this issue again feel free to file a new issue.
ps: If you found the root cause, please consider sharing it in the comments as it might help someone who stumbles on this issue.

**Closed by maheshmnj** 2022-07-14 09:08 UTC
Labels: in triage
