### ISSUE TITLE
Analyzer errors in flutter/lib code with 1.25.0-dev.8.0

### ISSUE THREAD

**Issue by keertip** [flutter/flutter#11415] opened 2017-07-26 19:41 UTC
See the following errors in the flutter package, running analyzer from 1.25.0-dev.8.0 version of the Dart SDK.  This was run as part of the integration into google3. The line numbers are a bit off wrt to the github code, as they point to the flutter package in google3 third_party/dart.

Can use the Dart SDK at http://gsdview.appspot.com/dart-archive/channels/dev/raw/1.25.0-dev.8.0/sdk/ for the analysis.

ERROR: third_party/dart/flutter/lib/src/rendering/sliver.dart:1430
  Mixin introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_mixin

ERROR: third_party/dart/flutter/lib/src/rendering/sliver.dart:1513
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_fill.dart:29
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_fill.dart:110
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_fixed_extent_list.dart:37
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_fixed_extent_list.dart:241
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_grid.dart:451
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_list.dart:36
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart:151
  Mixin introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_mixin

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_persistent_header.dart:35
  Mixin introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_mixin

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_persistent_header.dart:227
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_persistent_header.dart:265
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_persistent_header.dart:330
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/rendering/sliver_persistent_header.dart:482
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:253
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:291
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:294
  Mixin introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_mixin

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:309
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:311
  Mixin introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_mixin

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:334
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:336
  Mixin introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_mixin

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:359
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_persistent_header.dart:361
  Mixin introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_mixin

ERROR: third_party/dart/flutter/lib/src/widgets/sliver_prototype_extent_list.dart:128
  Base class introduces an invalid override. The type of 'RenderObject.constraints' ('() → Constraints') isn't a subtype of 'RenderSliver.constraints' ('() → SliverConstraints'). #strong_mode_invalid_method_override_from_base

**Comment by keertip** [comment] 2017-07-26 19:41
@Hixie

**Comment by keertip** [comment] 2017-07-26 19:50
@goderbauer

**Comment by Hixie** [comment] 2017-07-26 20:09
@leafpetersen Any idea if these are valid?

**Comment by keertip** [comment] 2017-07-26 20:12
@jmesserly

**Comment by Hixie** [comment] 2017-07-26 20:12
These errors aren't on line numbers that make sense in the version I'm looking at (e.g. the first points in the middle of a comment), and the messages aren't very clear about what the problem is (e.g. they don't mention what is being overridden), but presumably we're just missing a single `covariant` somewhere on some method declaration on some base class...

**Comment by keertip** [comment] 2017-07-26 20:15
The line numbers are for the third_party/dart/flutter package in google3.

**Comment by leafpetersen** [comment] 2017-07-26 21:33
How bleeding edge is this?  @jmesserly landed a fix a couple of days ago for our override checking to catch some bad cases related to mixins that we weren't catching before, but that also rejected a few valid things.  She sent a second CL a day or so ago that fixed the bad errors.  

First CL is here:
https://codereview.chromium.org/2981183003/ .

Second CL is here:
https://codereview.chromium.org/2988673003/

If this is current bleeding edge (i.e. with the second fix) then we should verify that they are actual problems, but they may indeed be places that require covariant that we were missing.

**Comment by keertip** [comment] 2017-07-26 21:50
Dev 8.0 does not contain the second cl.

But, I am still seeing the same errors with today's bleeding edge integration, which is commit 1d44f52, and that does contain the second cl. Verified that my client does have the changes from the cl.

**Comment by leafpetersen** [comment] 2017-07-26 21:58
Wow is that code a maze of twisty mixins, all alike.

We're sort of in uncharted territory here, because I'm not sure that super mixins have a well specified override semantics, at least for Dart 2.0, and probably not for Dart 1.0.

I chased through the code a bit, and it sort of looks to me as if all of the mixin compositions end up with classes in a consistent state, even though they go through some slightly strange intermediate states.  I'll try to pare this down to a manageable example.

**Comment by leafpetersen** [comment] 2017-07-26 22:31
Ok, here's a reproduction of the first level of errors:

```dart
abstract class A {}

abstract class B extends A {}

abstract class ProvidesConcreteAGetter {
  A get constraints => null;
}

abstract class ProvidesConcreteBGetter extends ProvidesConcreteAGetter {
  @override
  B get constraints => super.constraints;
}

abstract class ProvidesAbstractBGetter implements ProvidesConcreteBGetter {}

abstract class HasConcreteAGetterButDeclaresAbstractBGetter extends ProvidesConcreteBGetter
    with ProvidesConcreteAGetter, ProvidesAbstractBGetter {}
```

@ianh is this code working as intended?  Notice that the `HasConcreteAGetterButDeclaresAbstractBGetter` class is in a super weird state.  It has a concrete implementation of an `A` getter associated with it, but it declares itself as providing a `B` getter.  Since it is abstract, that's kind of ok?  I guess so long as you only mix it into something that provides a concrete `B` getter to override the abstract `A` getter which is hiding the other concrete `B` getter you'll be ok, but otherwise you'll have to get an error at the use site.

In actual fact, I think the code in question is broken.  Here is the actual hierarchy abstracted:
```dart
abstract class Constraints {}

abstract class SliverConstraints extends Constraints {}

abstract class RenderObject {
  Constraints get constraints => _constraints;
  Constraints _constraints;
}

abstract class RenderSliver extends RenderObject {
  // layout input
  @override
  SliverConstraints get constraints => super.constraints;
}

abstract class RenderSliverHelpers implements RenderSliver {}

// Abstract SilverConstraints, concrete Constraints
abstract class RenderSliverPersistentHeader extends RenderSliver
    with RenderObject, RenderSliverHelpers {}

// Ditto
abstract class RenderSliverPinnedPersistentHeader
    extends RenderSliverPersistentHeader {}

// Ditto
abstract class _RenderSliverPinnedPersistentHeader
    extends RenderSliverPinnedPersistentHeader {}

// Ditto
abstract class _RenderSliverPersistentHeaderForWidgetsMixin
    extends RenderSliverPersistentHeader {}

// Ditto, and this is not abstract, so this has to be an error.
class _RenderSliverPinnedPersistentHeaderForWidgets
    extends _RenderSliverPinnedPersistentHeader
    with _RenderSliverPersistentHeaderForWidgetsMixin {}
```

Unless I've messed something up while abstracting, this is broken:  you have a non-abstract class where the "most recent" concrete implementation of constraints returns `Constraints`, but the last mixed in class declares it as returning `SilverConstraints`.  Even if we suppress the errors on all of the abstract classes, I think we would have to emit an error here.

cc @floitschG @lrhn @eernstG @munificent @sigmundch

**Comment by leafpetersen** [comment] 2017-07-26 22:48
An interesting question is whether adding a concrete implementation of the `SilverConstraints` getter should fix this.  It's still slightly odd since one of the intermediate classes produced by the override is invalid (`RenderSliver with RenderObject`) but it's immediately followed by another mixin which restores it (`RenderSliver with RenderObject, RenderSliverHelpers`).  I believe the intent of @jmesserly's second CL was to allow more of these patterns so perhaps we should consider it?

I'd really like to hear from some of the folks involved in the super mixins proposal though - maybe @lrhn?

**Comment by leafpetersen** [comment] 2017-07-26 22:50
Missed a key phrase in the previous comment, edited to be "concrete implementation of the `SilverConstraints` getter to `RenderSliverHelpers`.

**Comment by Hixie** [comment] 2017-07-26 23:01
The `with RenderObject` part seems bogus. Where is that in the actual code?

**Comment by leafpetersen** [comment] 2017-07-26 23:52
> The with RenderObject part seems bogus. Where is that in the actual code?

Sorry, that was me trying to make things slightly simpler.  In the actual hierarchy, it's

```dart
abstract class RenderSliverPersistentHeader extends RenderSliver with RenderObjectWithChildMixin<RenderBox>, RenderSliverHelpers {
 ```

from line 35 of sliver_persistent_header.dart.

But for the purposes of this analysis RenderObjectWithChildMixin is essentially just RenderObject.

**Comment by Hixie** [comment] 2017-07-26 23:58
Ah no, there's a big difference there as I understand it. `with` only imports the concrete members from the class, everything _it_ inherited is made abstract. So it's more like `implements RenderObject`. No?

**Comment by Hixie** [comment] 2017-07-27 00:00
I base that assertion on the fact that the analyzer says that C in the example below is missing a concrete `A.foo`, even though no class has an abstract `A.foo`:

```dart
abstract class A { final int foo; }
class B extends A { final int bar; }
class C extends Object with B { }
```

**Comment by Hixie** [comment] 2017-07-27 00:02
Which is to say that the class you describe as "Abstract SilverConstraints, concrete Constraints" IMHO is actually "concrete SliverConstraints, abstract Constraints" and the "abstract Constraints" part (which comes in via several paths) is satisfied by the "concrete SliverConstraints" part.

**Comment by leafpetersen** [comment] 2017-07-27 00:24
Possible, that kind of rings a bell.  I'm really not very familiar with the super mixins proposal - I wasn't on the language team when it was proposed.  Assuming so, then yes I believe that makes that code ok, since the only concrete method that gets mixed in satisfies the contract.

**Comment by munificent** [comment] 2017-07-27 01:35
Yeah, when you mixin a class with a superclass, you don't actually get anything from the superclass, just the class's own members (which is super confusing and was the main criticism of the proposal).

**Comment by Hixie** [comment] 2017-07-27 01:56
FWIW, that behaviour is very much in line with what we've found we need in Flutter land. We haven't found a need for diamond inheritance or multiple inheritance. The only reason we want super mixins is so that the mixin can say "I must be mixed into a hierarchy that has these classes and interfaces". For that it works really well.

**Comment by leafpetersen** [comment] 2017-07-27 15:53
I'll try to get a fix in for the override checking today.

**Comment by leafpetersen** [comment] 2017-07-27 18:20
FYI: any support for super mixins in strong mode is probably mostly accidental.  So you're not getting full strong mode style checking for super mixins right now.

https://github.com/dart-lang/sdk/issues/30283

**Comment by leafpetersen** [comment] 2017-07-27 20:46
https://codereview.chromium.org/2986063002/

**Comment by leafpetersen** [comment] 2017-07-27 21:40
Fix for the issue identified above landed here:  https://github.com/dart-lang/sdk/commit/bbb0ed27ad34d6f35d90415feb68e55cdded4d73

**Comment by Hixie** [comment] 2018-05-08 23:40
I'm closing this on the assumption it's long obsolete.

**Closed by Hixie** 2018-05-08 23:40 UTC
