### ISSUE TITLE
Handle pen pressure from wacom tablets

### ISSUE THREAD

**Issue by fodil-a** [flutter/flutter#73267] opened 2021-01-04 13:22 UTC
## Use case
I want to detect pen pressure from pencil table like Wacom Intuos

## Proposal
Today, you can use GestureDetector which handles pressure from screens.

I think this is do-able through a package which handles pressure on web and native.

Here is a current possible code, but does not work on Linux:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: Container(
            child: GestureDetector(
      onForcePressPeak: (details) => print(details.pressure),
      onForcePressStart: (details) => print(details.pressure),
      onForcePressUpdate: (details) => print(details.pressure),
    )));
  }
}
```

Here is the flutter doctor:
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.167, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.26.0-2.0.pre.167 at /home/fodil/dev/flutter
    • Framework revision d3a2259541 (il y a 4 jours), 2020-12-31 15:14:03 -0500
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/fodil/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /home/fodil/Téléchargements/idea-IC-201.7223.91
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.7846.93

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment] 2021-01-04 14:32
possible duplicate of

https://github.com/flutter/flutter/issues/63209
https://github.com/flutter/flutter/issues/65248
https://github.com/flutter/flutter/issues/42846

@TahaTesser 
for what is worth I think those issue are divided even too granularity
I'd consider consolidating the aforementioned issues (plus [apple pencil's](https://github.com/flutter/flutter/issues/38135)) 
under a new platform / vendor agnostic issue
just my 2 cents

**Comment by TahaTesser** [comment] 2021-01-04 14:57
Hi @fodil-a 
I agree with @iapicca, these issues are too granular, trying to achieve pretty same results but something like Apple Pencil might come with more features, it also added a text-input label which makes sense since Apple Pencil has some specific text input features.

Since you're trying to achieve on Linux, this is a duplicate of https://github.com/flutter/flutter/issues/63209
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-04 14:57 UTC
