### ISSUE TITLE
Failed to load test with flutter_test

### ISSUE THREAD

**Issue by jja08111** [flutter/flutter#88677] opened 2021-08-23 03:41 UTC
## Steps to Reproduce

1. Run flutter test on the IDE(VSCode, Android studio)
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('simple test', () async {
    expect(4, 4);
  });
}
```

**Expected results:** 

Pass the test.

**Actual results:** 

Failed to load test.

<details>
  <summary>Logs</summary>

```console
Failed to load "D:\Android_Project\p_lyric\test\worker\worker_test.dart": Connection closed before test suite loaded.
package:test_core/src/runner/plugin/platform_helpers.dart 110:19  deserializeSuite.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 394:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 404:15                                _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 741:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 596:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 589:5                           _StreamController.close
new GuaranteeChannel.<fn>.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 394:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 404:15                                _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 741:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 596:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 589:5                           _StreamController.close
dart:async/stream_controller.dart 833:29                          _StreamSinkWrapper.close
_GuaranteeSink.close
_MultiChannel._closeInnerChannel
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 394:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 404:15                                _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 741:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 596:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 589:5                           _StreamController.close
new GuaranteeChannel.<fn>.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 394:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 404:15                                _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 610:14                                _DelayedDone.perform
dart:async/stream_impl.dart 706:11                                _StreamImplEvents.handleNext
dart:async/stream_impl.dart 663:7                                 _PendingEvents.schedule.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/zone.dart 1202:23                                      _CustomZone.bindCallbackGuarded.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1354:13                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/zone.dart 1202:23                                      _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 40:21                          _microtaskLoop
dart:async/schedule_microtask.dart 49:5                           _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 120:13                      _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 185:5                       _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/future_impl.dart 25:44                                 _Completer.completeError
package:test_core/src/runner/plugin/platform_helpers.dart 108:19  deserializeSuite.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 394:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 404:15                                _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 741:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 596:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 589:5                           _StreamController.close
new GuaranteeChannel.<fn>.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 394:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 404:15                                _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 741:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 596:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 589:5                           _StreamController.close
dart:async/stream_controller.dart 833:29                          _StreamSinkWrapper.close
_GuaranteeSink.close
_MultiChannel._closeInnerChannel
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 394:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 404:15                                _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 741:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 596:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 589:5                           _StreamController.close
new GuaranteeChannel.<fn>.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 394:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 404:15                                _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 610:14                                _DelayedDone.perform
dart:async/stream_impl.dart 706:11                                _StreamImplEvents.handleNext
dart:async/stream_impl.dart 663:7                                 _PendingEvents.schedule.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/zone.dart 1202:23                                      _CustomZone.bindCallbackGuarded.<fn>
StackZoneSpecification._run
StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1354:13                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/zone.dart 1202:23                                      _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 40:21                          _microtaskLoop
dart:async/schedule_microtask.dart 49:5                           _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 120:13                      _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 185:5                       _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 1279:19                                      _CustomZone.registerCallback
dart:async/stream_impl.dart 161:17                                _BufferingStreamSubscription._registerDoneHandler
dart:async/stream_impl.dart 110:19                                new _BufferingStreamSubscription.zoned
dart:async/stream_impl.dart 103:14                                new _BufferingStreamSubscription
dart:async/stream_controller.dart 806:9                           new _ControllerSubscription
dart:async/stream_controller.dart 637:47                          _StreamController._subscribe
dart:async/stream_controller.dart 786:19                          _ControllerStream._createSubscription
dart:async/stream_impl.dart 473:9                                 _StreamImpl.listen
dart:_internal/async_cast.dart 17:17                              CastStream.listen
package:test_core/src/runner/plugin/platform_helpers.dart 80:52   deserializeSuite
package:flutter_tools/src/test/flutter_platform.dart 343:46       FlutterPlatform.load
package:test_core/src/runner/loader.dart 224:38                   Loader.loadFile.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1286:19                                      _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 45:22                           _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart                          Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 97:31                new LoadSuite.<fn>.<fn>
package:test_core/src/runner/load_suite.dart 96:17                new LoadSuite.<fn>.<fn>
package:test_core/src/runner/load_suite.dart 107:8                new LoadSuite.<fn>
Invoker.waitForOutstandingCallbacks.<fn>
Invoker.waitForOutstandingCallbacks.<fn>
dart:async/zone.dart 1354:13                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1789:10                                      _runZoned
dart:async/zone.dart 1711:10                                      runZoned
Invoker.waitForOutstandingCallbacks
Invoker._onRun.<fn>.<fn>.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1286:19                                      _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 45:22                           _asyncThenWrapperHelper
package:test_api/src/backend/invoker.dart                         Invoker._onRun.<fn>.<fn>.<fn>
dart:async/zone.dart 1354:13                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1789:10                                      _runZoned
dart:async/zone.dart 1711:10                                      runZoned
Invoker._onRun.<fn>.<fn>
dart:async/zone.dart 1354:13                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1789:10                                      _runZoned
dart:async/zone.dart 1711:10                                      runZoned
Invoker.guard
Invoker._guardIfGuarded
Invoker._onRun.<fn>
Chain.capture.<fn>
dart:async/zone.dart 1354:13                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1789:10                                      _runZoned
dart:async/zone.dart 1711:10                                      runZoned
Chain.capture
Invoker._onRun
LiveTestController.run
dart:async/future.dart 198:37                                     new Future.microtask.<fn>
dart:async/zone.dart 1346:47                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/zone.dart 1202:23                                      _CustomZone.bindCallbackGuarded.<fn>
dart:async/zone.dart 1354:13                                      _rootRun
dart:async/zone.dart 1258:19                                      _CustomZone.run
dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
dart:async/zone.dart 1202:23                                      _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 40:21                          _microtaskLoop
dart:async/schedule_microtask.dart 49:5                           _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 120:13                      _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 185:5                       _RawReceivePortImpl._handleMessage

✖ loading D:\Android_Project\p_lyric\test\worker\worker_test.dart
Exited (1)

```

```console
PS D:\Android_Project\p_lyric> flutter analyze
Analyzing p_lyric...                                                    
No issues found! (ran in 5.6s)
```

```console
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale ko-KR)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • ANDROID_SDK_ROOT = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\민성\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • SM G950N (mobile) • ce081718ca85ee2802 • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2021-08-23 06:35
Hi @jja08111 thanks for filing the issue. 

Can you confirm if you experience this issue with a new project? 

I created a new project to see if I could replicate this issue, however all my tests passed.
See attached image below

<img width="826" alt="Screenshot 2021-08-23 at 06 33 21" src="https://user-images.githubusercontent.com/88313112/130401357-1a5cf1a2-7ef6-4eb8-b7dc-806cd2b415f4.png">

Thank you

**Comment by jja08111** [comment] 2021-08-23 06:43
Hi @danagbemava-nc, thanks for response my issue.

I created the new project there is the same issue. I think my Flutter environment has some problems but I don't know how to fix them.
![image](https://user-images.githubusercontent.com/57604817/130402387-1cfb9443-2ab7-4fa0-ab7d-c777358705b3.png)

**Comment by danagbemava-nc** [comment] 2021-08-23 06:50
@jja08111 do you get the same issue when you use the `flutter test` command?

**Comment by jja08111** [comment] 2021-08-23 06:53
@danagbemava-nc Yes, but when I used `test` package not `flutter_test` and using `dart test test/main_test.dart` command from the terminal works.

**Comment by danagbemava-nc** [comment] 2021-08-23 08:56
@jja08111 Are you able to run the default flutter app using vscode?

**Comment by jja08111** [comment] 2021-08-23 08:58
@danagbemava-nc Yes, the only flutter_test didn't work.

**Comment by danagbemava-nc** [comment] 2021-08-23 09:27
@jja08111 are you behind a proxy network? 

Also, can you check if you experience it with another network? 

Lastly, kindly take a look at #30892 and #16398 to see if there might be a fix for you over there

**Comment by jja08111** [comment] 2021-08-23 09:41
@danagbemava-nc No, I don't use a proxy network.

Would you explain the "experience it with another network"? I don't understand what you mean.

And I looked around the #30892, #16398 and #60512, but I couldn't solve this problem.

**Comment by danagbemava-nc** [comment] 2021-08-23 10:15
> Would you explain the "experience it with another network"? I don't understand what you mean.

The `Connection closed before test suite` might suggest a network issue, so I wanted to know if switching to a different network might solve the issue for you

> And I looked around the #30892, #16398 and #60512, but I couldn't solve this problem.

Would it be possible for you to try reinstalling flutter to see if anything changes?

**Comment by jja08111** [comment] 2021-08-23 11:52
@danagbemava-nc Thanks for more info.

I've reinstalled the Flutter, but there is the same issue.

### flutter doctor -v
```console
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale ko-KR)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • ANDROID_SDK_ROOT = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\민성\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!

```

**Comment by danagbemava-nc** [comment] 2021-08-23 12:11
@jja08111 Can you check if you have this `flutter/packages/flutter_test` in your latest installation?

**Comment by jja08111** [comment] 2021-08-23 12:17
Yes, I have that files.
![image](https://user-images.githubusercontent.com/57604817/130445499-26bd8ec6-5fbf-430e-af25-09526b5b4a87.png)

**Comment by danagbemava-nc** [comment] 2021-08-23 13:10
@jja08111 kindly run `flutter test` from the `command line` and paste the output for me

**Comment by jja08111** [comment] 2021-08-23 13:12
@danagbemava-nc Here is a output.
```console
PS D:\Android_Project\test_issue> flutter test
00:06 +0 -1: loading D:\Android_Project\test_issue\test\simple_test.dart [E]
  Failed to load "D:\Android_Project\test_issue\test\simple_test.dart": Connection closed before test suite loaded.
00:06 +0 -2: loading D:\Android_Project\test_issue\test\widget_test.dart [E]
  Failed to load "D:\Android_Project\test_issue\test\widget_test.dart": Connection closed before test suite loaded.
00:06 +0 -2: Some tests failed.
PS D:\Android_Project\test_issue> 

```

**Comment by jja08111** [comment] 2021-09-21 15:53
I think this was caused by a network issue, but I don't know what I used it. 
@danagbemava-nc Can you show something like a checklist to check the network setting for this issue please?

**Comment by zhangyu528** [comment] 2021-09-25 08:48
same problem .
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS D:\工作\项目\flutter_demo\demo> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.60.2)
[√] Connected device (2 available)

• No issues found!
PS D:\工作\项目\flutter_demo\demo> flutter test
00:00 +0: loading D:\工作\项目\flutter_demo\demo\test\widget_test.dart
00:01 +0: loading D:\工作\项目\flutter_demo\demo\test\widget_test.dart
00:01 +0 -1: loading D:\工作\项目\flutter_demo\demo\test\widget_test.dart [E]
   
  Failed to load "D:\工作\项目\flutter_demo\demo\test\widget_test.dart": Connection closed before test suite loaded.
00:01 +0 -1: Some tests failed.

**Comment by zhangyu528** [comment] 2021-09-25 09:43
PS D:\工作\项目\flutter_demo\demo> netsh winhttp show proxy
no proxy
当前的 WinHTTP 代理服务器设置:

    直接访问(没有代理服务器)。

**Comment by zhangyu528** [comment] 2021-09-25 09:45
name: flutter_test

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".

  flutter:
    sdk: flutter

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: 0.4.2

  # Used by golden file comparator
  path: 1.8.0

  # Testing utilities for dealing with async calls and time.
  fake_async: 1.2.0
  clock: 1.1.0

**Comment by zhangyu528** [comment] 2021-09-25 14:31
But ，flutter pub test is OK .Flutter test is not OK.

**Comment by CCXXXI** [comment] 2021-10-02 07:22
Same issue.

Found a solution:
```
flutter channel master
flutter upgrade
```

**Comment by jja08111** [comment] 2021-10-02 07:49
@CCXXXI thanks for your comment, but it is not working.

**Comment by CCXXXI** [comment] 2021-10-02 08:24
Weird... I got another issue after `flutter channel stable` `flutter upgrade` `flutter test`:
```
dart_tool/flutter_build/generated_main.dart:8:8: Error: Error when reading '../../../AppData/Local/Temp/flutter_tools.cf468f26/flutter_test_listener.761451b/listener.dart'
```
`flutter clean` resovled this new issue. Now I cannot reproduce the original issue.

**Comment by perqin** [comment] 2021-11-04 17:13
I've encountered the same issue, and `flutter clean` works.

**Comment by darshankawar** [comment] 2022-10-13 11:24
I am unable to replicate this issue on latest stable version of the framework. The given test code passes properly:

<img width="997" alt="Screenshot 2022-10-13 at 4 52 51 PM" src="https://user-images.githubusercontent.com/67046386/195583816-b867b742-2e5f-4888-8b54-e64438fe0cd7.png">

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] VS Code (version 1.62.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

With this finding, I am going ahead and closing as not an issue. If anybody disagrees or still facing same issue, please open new issue with relevant details.

**Closed by darshankawar** 2022-10-13 11:24 UTC
Labels: a: tests, severe: crash, tool, passed first triage
