### ISSUE TITLE
The Android send intent does not open my Flutter App properly.  

### ISSUE THREAD

**Issue by akbulutdora** [flutter/flutter#112335] opened 2022-09-24 21:26 UTC
## Steps to Reproduce

1. Create a new Flutter project.
2. Modify the main activity in `android/app/src/main/AndroidManifest.xml` as follows by adding the SEND intent filter (Note: using different android:launchMode values does not change the result. I have tried `"standard"`, `"singleTop"`, `"singleTask`", `"singleInstance"`, and `"singleInstancePerTask"`):
```xml
<activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleInstance"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>


            <!--Add the following-->
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/plain" />
            </intent-filter>
        </activity>
```
3. Execute `flutter run` on the code sample 
4. Open google chrome, and go to any URL.
5. Share the URL, and choose the Flutter app among the apps in the list.

**Expected results:** 
Google chrome is now sent to background, the Flutter app is displayed on the screen. Just as anyone would expect. 

**Actual results:** 
Somehow, the app is opened **inside** the chrome app. When I click the overview button of Android (it is the square one that shows apps running in the background), I can see both the Flutter app with its own icon, and again, the Flutter app but with the Chrome icon.

```dart
```
Creating the beginner Flutter app is enough for reproducing the problem. The AndroidManifest file requires explained change.

</details>

The following log output contains the `flutter run --verbose` output after the app runs, and I perform the steps to reproduce.
<details>
  <summary>Logs</summary>

```
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 
[        ] R Hot restart.
[   +1 ms] h List all available interactive commands.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety 
[   +1 ms] An Observatory debugger and profiler on sdk gphone x86 64 is available at: http://127.0.0.1:53049/YZBF19Hwbow=/
[ +739 ms] The Flutter DevTools debugger and profiler on sdk gphone x86 64 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:53049/YZBF19Hwbow=/
[+14219 ms] D/EGL_emulation( 1743): eglCreateContext: 0x789c8ec3c850: maj 2 min 0 rcv 2
[  +11 ms] D/EGL_emulation( 1743): eglCreateContext: 0x789c8ec3aee0: maj 2 min 0 rcv 2
[  +12 ms] D/HostConnection( 1743): HostConnection::get() New Host Connection established 0x789c9ebc6550, tid 1881
[   +4 ms] D/HostConnection( 1743): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4
ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands
ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles
ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit
ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing
ANDROID_EMU_gles_max_version_2
[  +29 ms] D/EGL_emulation( 1743): eglMakeCurrent: 0x789c8ec3aee0: ver 2 0 (tinfo 0x789c2ec2a400) (first time)
[ +108 ms] D/HostConnection( 1743): HostConnection::get() New Host Connection established 0x789c9ebc6190, tid 1879
[  +10 ms] D/HostConnection( 1743): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4
ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands
ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles
ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit
ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing
ANDROID_EMU_gles_max_version_2
[  +59 ms] D/EGL_emulation( 1743): eglMakeCurrent: 0x789c8ec3c850: ver 2 0 (tinfo 0x789c2ec2c080) (first time)
[   +1 ms] D/EGL_emulation( 1743): eglCreateContext: 0x789c8ec3e690: maj 2 min 0 rcv 2
```

```
PS D:\Github_Repos\test_app> flutter analyze
Analyzing test_app...                                                   
No issues found! (ran in 3.3s)
```

```
PS D:\Github_Repos\test_app> flutter doctor -v
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.2006], locale tr-TR)
    • Flutter version 3.0.5 at C:\Users\doraa\Documents\flutter                                  
    • Upstream repository https://github.com/flutter/flutter.git                                 
    • Framework revision f1875d570e (2 months ago), 2022-07-13 11:24:16 -0700                    
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\doraa\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Derleme Araçları 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Derleme Araçları 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at D:\IntelliJ IDEA 2021.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\doraa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (2 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)
    • Windows (desktop)          • windows       • windows-x64 • Microsoft Windows [Version 10.0.19044.2006]

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

In the screenshot, it can be seen that two instances of the app are running, one under the Flutter icon, and one with the Chrome icon.
![app_test](https://user-images.githubusercontent.com/60580158/192118809-a72f6705-27e3-4384-a918-b0d8a4351644.png)

**Comment by danagbemava-nc** [comment] 2022-09-26 10:48
Hi @akbulutdora, can you upgrade to the latest version of flutter stable to see if you still experience this issue? I ran a sample project with the latest stable and it seems to be working just fine for me. 

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/192257933-780e33d4-98af-4560-a921-c1a2bf95f916.mp4

</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19043.1889], locale en-GH)
    • Flutter version 3.3.2 on channel stable at c:\src\sdks\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (5 available)
    • M2007J20CG (mobile)          • 5dd3be00      • android-arm64  • Android 12 (API 31)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1889]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 105.0.1343.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by akbulutdora** [comment] 2022-09-26 11:28
Hello @danagbemava-nc, I upgraded Flutter to  3.3.2 and the issue persists (Also, the example I ran before was actually already on Flutter version 3.3.2).
Can you please click the overview button of android again to see the running apps? I could not see the part where I am having trouble with in the video you've sent. Do you have two instances of your app (one with the Flutter icon and one with the Chrome icon) or only one (the one with the Flutter icon)?

Here is the flutter doctor of the test application I used for this issue.

```
PS D:\Github_Repos\test_app> flutter doctor -v
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.1904
    • Flutter version 3.3.2 on channel stable at C:\Users\doraa\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\doraa\AppData\Local\Android\sdk                       
    • Platform android-33, build-tools 32.1.0-rc1                                   
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Derleme Araçları 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Derleme Araçları 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at D:\IntelliJ IDEA 2021.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\doraa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (2 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)
    • Windows (desktop)          • windows       • windows-x64 • Microsoft Windows [Version 10.0.19044.2006]

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Please pay extra attention to the last 10 seconds of the video. I wonder if you have the same issue.
[bad_behavior.webm](https://user-images.githubusercontent.com/60580158/192265309-fd5b8af2-8102-42e8-a0ea-1ba239915351.webm)

**Comment by danagbemava-nc** [comment] 2022-09-27 06:53
Hi @akbulutdora, I'm curious, does this reproduce for you if you test on a simulator with a different version of android, say android 12?

I can reproduce your issue on android 11 but I can't reproduce it on android 12. I wonder if this is an issue with OS versions. 


| android 11 | android 12 |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/192454200-bf336440-7ca6-4f14-a1d7-82c143ea45f0.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/192454218-9061c1f5-0f41-4f38-b0cf-8320a339a075.mp4" /> |

**Comment by akbulutdora** [comment] 2022-09-27 14:04
Yes, I have also reproduced the same behavior you got in Android 11 & 12 respectively. In this case, should I open the issue somewhere else?

**Comment by danagbemava-nc** [comment] 2022-09-28 07:06
Hi @akbulutdora, it looks like this may not be a flutter issue after all. 

I tested a native android app with just "hello world" and the bug reproduces there. Do you have a physical android 11 device that you can test this on? I'm wondering whether this is just an issue with android 11 or the android 11 emulator. 

My physical device is android 12 and it doesn't reproduce there.

<details>
<summary>native android test</summary>

https://user-images.githubusercontent.com/88313112/192711090-26f99979-dacc-45a2-8bd0-a12d014b4755.mp4

</details>

**Comment by AEAydog** [comment] 2022-09-28 11:03
Hello thread. I'm working on the same dev team with @akbulutdora and wanted to add that I've tried to reproduce the bug on my Android 10 physical device and it seems to work just fine - no bug.

**Comment by akbulutdora** [comment] 2022-09-28 20:45
Unfortunately, I don't have access to a physical Android 11.

**Comment by danagbemava-nc** [comment] 2022-09-29 07:15
Given that this issue occurs in a native android project as well, I'm more inclined to believe that this is not an issue with flutter. Also, considering that this occurs with certain versions of android and not others, it seems like either an OS issue or 
an issue with the emulator. 

Nonetheless, this doesn't seem like an issue with flutter. 

As such, I'll be closing this issue. 

Thank you

**Closed by danagbemava-nc** 2022-09-29 07:15 UTC
Labels: in triage

**Comment by akbulutdora** [comment] 2022-09-30 11:41
@danagbemava-nc
I had decided to use the Android 12 emulator, but there is another problem with that about the VIEW intents. Android 12 emulator doesn't seem to open VIEW intents. Can you add the following intent to a beginning app and try to open the app through App Links (not send/share intent)? For me, it just opens chrome without any options for my own test app. 

```
<intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                 <category android:name="android.intent.category.BROWSABLE" />
                <!-- Accepts URIs that begin with https://upcarta-staging.onrender.com -->
                <data
                    android:host="yourhost.com"
                    android:scheme="https" />
</intent-filter>
```

Results:
Android 11 (Expected behavior):
[android_11_view_intent.webm](https://user-images.githubusercontent.com/60580158/193261761-1bf3f554-f524-451d-bb14-83635ad82808.webm)

Android 12 (Bad behavior):
[android_12_view_intent.webm](https://user-images.githubusercontent.com/60580158/193262037-0c69c5e6-c134-4bc6-a721-2aee9473adf5.webm)


Can you reproduce this on native android apps to see if it is a Flutter issue please?

**Comment by akbulutdora** [comment] 2022-10-01 13:33
Okay thanks, it seems that my assetlinks file had a small typo.
