### ISSUE TITLE
[Impeller] `Command::viewport` and `Command::scissor` are only used in tests.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#132781] opened 2023-08-17 18:25 UTC
These objects are only ever set for the ImGui backend used in playgrounds:

https://github.com/flutter/engine/blob/9fae689d10a9fc7615b9b185172b1bed5c8d40a1/impeller/playground/imgui/imgui_impl_impeller.cc#L245-L246

They contribute `sizeof(Rect) * 2` to the size of command objects. We should remove them if they're really only useful for ImGui, or use them if they'd be useful elsewhere.

@bdero WDYT?

@gaaclarke fyi

**Comment by gaaclarke** [comment] 2023-08-17 19:30
I raised this the other day and Jonah made the point that these are going to be surfaced in Dart GPU at some point?

**Comment by dnfield** [comment] 2023-08-17 20:10
That makes it sound like we should be using them in the actual implementations then because they're somehow useful.

I guess a third possibility is that they're only useful in some cases, and right now we only cover those cases in tests, but I'd like to better understand that if it's the case.

**Comment by bdero** [comment] 2023-08-18 20:44
Both are ubiquitous features in graphics standards/HALs. The scissor test can be used for free rectangle clipping by many renderers (no stencil traffic!), and adjusting the viewport can absorb transform churn in some situations.

In multi-camera scenarios (like split screen multiplayer, VR, overhead maps, drone cameras, etc.) you can avoid burdening all of your vertex shaders with having to somehow apply the on-screen positioning transform -- which may or may not be a big ask, depending on the renderer! Stuff like baking static HUD geometry into NDC space becomes harder to wrangle without having control over the viewport.

It's unfortunately hard to pull value from these in Impeller's 2D renderer, though, since I don't think scissors can be used for subpixel clipping on multisample intermediates (which is a shame). There might still be places where we could leverage scissors or viewports in Impeller, but I haven't put much thought into it TBH.

**Comment by bdero** [comment] 2023-08-23 19:12
> If I'm understanding correctly, it sounds like it would be a mistake for developers to try to use them in the API currently and they wouldn't realize that until rendering looked wrong

No, the problem is that the scissor test takes integers, not that they'll behave in a surprising way or not work when binding multisample textures. We just can't use them as a full replacement of our rectangle clips because all of our clips need to be antialiased -- although it might still be useful for bounds hint scenarios...

I would prefer we don't remove them since Flutter GPU renderers will benefit from having these expected options available.

One example of a command encoding optimization that will survive with time would be to make command encoding more granular and reflect how the backends need to track state anyhow. The viewport and scissor don't have to be part of every command. Nor do bindings, etc. Our current command encoding setup isn't just wasteful in terms of memory: We also need to optimize graphics API traffic, and so we need to check every field of every command for changes and encode those changes accordingly.

For packing these smaller commands in a buffer, I would recommend reworking the RenderPass API to take simpler commands (like `BindTexture`, `DrawIndices`, `SetViewport`, etc.) and have these commands encode a discriminated union chunk into the internal encoding buffer. The discriminated union's enum can be used by the backend as an index into a per-backend dispatch table (ordered list of functions) that knows how to handle encoding each of the subcommands.

Added a bug to discuss this possible solution here: https://github.com/flutter/flutter/issues/133179

**Comment by chinmaygarde** [comment] 2023-09-08 19:15
Closing this as working as intended per the discussion. https://github.com/flutter/flutter/issues/133179 seems like the followup discussing making the commands slimmer.

**Closed by chinmaygarde** 2023-09-08 19:15 UTC
Labels: a: tests, engine, P3, e: impeller, team-engine, triaged-engine
