### ISSUE TITLE
Dart formatter Keeps running endlessly && freezes later on.

### ISSUE THREAD

**Issue by temitopeog** [flutter/flutter#95324] opened 2021-12-15 10:21 UTC
I am also facing the same issue. I have done everything suggested in your previous tickets @DanTup but VS code still hangs / freezes

## Steps to Reproduce
Versions below:

Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (6 days ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0

What i've noticed is,
<img width="1225" alt="Screenshot 2021-12-15 at 09 54 40" src="https://user-images.githubusercontent.com/49304398/146165221-45cb7c4b-e964-4710-ba31-1b7208c7641e.png">
<img width="889" alt="Screenshot 2021-12-15 at 09 57 23" src="https://user-images.githubusercontent.com/49304398/146165231-250583bd-2ec4-4c80-a195-a45de4b8b7c6.png">
 as the file gets slightly larger, the crash behaviour occurs. this doesn't happen with very small project.

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
[bug.zip](https://github.com/flutter/flutter/files/7718397/bug.zip)
<img width="1234" alt="Screenshot 2021-12-15 at 10 12 44" src="https://user-images.githubusercontent.com/49304398/146168678-27574515-b2e4-47bd-9978-93633a5b4f3a.png">
<img width="887" alt="Screenshot 2021-12-15 at 10 13 43" src="https://user-images.githubusercontent.com/49304398/146168694-e7b46a9f-6835-4a63-b838-4ced396d5cb3.png">

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
 info • Unused import: 'package:magicbox/pages/welcome_page.dart' • lib/main.dart:3:8 • unused_import
   info • Prefer const with constant constructors • lib/main.dart:21:13 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/misc/colors.dart:4:35 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/misc/colors.dart:5:35 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/misc/colors.dart:6:37 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/misc/colors.dart:7:34 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/misc/colors.dart:8:34 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/misc/colors.dart:9:38 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/misc/colors.dart:10:41 • prefer_const_constructors
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements
          are also provided by the import of 'package:flutter/material.dart' •
          lib/pages/authpages/login_page.dart:1:8 • unnecessary_import
   info • Unused import: 'package:magicbox/misc/colors.dart' • lib/pages/authpages/login_page.dart:3:8 •
          unused_import
   info • Unused import: 'package:magicbox/widgets/app_large_text.dart' •
          lib/pages/authpages/login_page.dart:4:8 • unused_import
   info • Unused import: 'package:magicbox/widgets/app_text.dart' • lib/pages/authpages/login_page.dart:5:8
          • unused_import
   info • Unused import: 'package:magicbox/model/login_model.dart' •
          lib/pages/authpages/login_page.dart:6:8 • unused_import
   info • The value of the field '_emailRegExp' isn't used • lib/pages/authpages/login_page.dart:17:9 •
          unused_field
   info • The value of the field '_formKey' isn't used • lib/pages/authpages/login_page.dart:21:9 •
          unused_field
   info • The value of the local variable 'height' isn't used • lib/pages/authpages/login_page.dart:28:18 •
          unused_local_variable
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements
          are also provided by the import of 'package:flutter/material.dart' •
          lib/pages/welcome_page.dart:1:8 • unnecessary_import
   info • Unnecessary new keyword • lib/pages/welcome_page.dart:18:31 • unnecessary_new
   info • SizedBox for whitespace • lib/pages/welcome_page.dart:49:26 • sized_box_for_whitespace
   info • SizedBox for whitespace • lib/pages/welcome_page.dart:69:26 • sized_box_for_whitespace
   info • Prefer typing uninitialized variables and fields • lib/pages/welcome_page.dart:94:7 •
          prefer_typing_uninitialized_variables
   info • Private field could be final • lib/pages/welcome_page.dart:94:7 • prefer_final_fields
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more
          of its instance fields aren't final: AppButtons.text, AppButtons.icon, AppButtons.width,
          AppButtons.isIcon, AppButtons.height • lib/widgets/app_buttons.dart:6:7 • must_be_immutable
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements
          are also provided by the import of 'package:flutter/material.dart' •
          lib/widgets/app_large_text.dart:1:8 • unnecessary_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more
          of its instance fields aren't final: AppLargeText.size • lib/widgets/app_large_text.dart:4:7 •
          must_be_immutable
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements
          are also provided by the import of 'package:flutter/material.dart' •
          lib/widgets/app_text.dart:1:8 • unnecessary_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more
          of its instance fields aren't final: AppText.size • lib/widgets/app_text.dart:4:7 •
          must_be_immutable
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements
          are also provided by the import of 'package:flutter/material.dart' •
          lib/widgets/my_form_text_field.dart:1:8 • unnecessary_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more
          of its instance fields aren't final: MyFormTextField.onSaved, MyFormTextField.decoration,
          MyFormTextField.validator • lib/widgets/my_form_text_field.dart:4:7 • must_be_immutable
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements
          are also provided by the import of 'package:flutter/material.dart' •
          lib/widgets/responsive_button.dart:1:8 • unnecessary_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more
          of its instance fields aren't final: ResponsiveButton.isResponsive, ResponsiveButton.width •
          lib/widgets/responsive_button.dart:6:7 • must_be_immutable
```

```
Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.8.0 at /Users/i508752/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (7 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/i508752/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] VS Code (version 1.34.0)
    • VS Code at /Users/i508752/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
    ! Error: Temitope’s iPhone is not connected. Xcode will continue when Temitope’s iPhone is connected. (code
      -13)

```

</details>

**Comment by mamuseferha** [comment] 2021-12-15 10:36
Hi @temitopeog 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-12-15 10:36 UTC
Labels: in triage

**Comment by DanTup** [comment] 2021-12-15 11:20
This is likely an issue in the LSP server - we can troubleshoot in the issue raised at https://github.com/dart-lang/sdk/issues/47934. Thanks!
