### ISSUE TITLE
when i connected the physic devices, the vscode print the response, and vscode lost connect to devices!!

### ISSUE THREAD

**Issue by wangxingxing123654** [flutter/flutter#71139] opened 2020-11-24 07:41 UTC
here is flutter doctor -v
`[✓] Flutter (Channel stable, 1.22.2, on macOS 11.0.1 20B50, locale zh-Hans-CN)
    • Flutter version 1.22.2 at /Users/chicv/Downloads/flutter
    • Framework revision 84f3d28555 (6 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/chicv/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)`

**Comment by sidrao2006** [comment] 2020-11-24 07:53
Hey @wangxingxing123654 ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with a 3rd party package, please close this issue and open it in the dedicated  [repository](https://github.com/dart-code/dart-code/issues) instead.

Thanks

**Comment by wangxingxing123654** [comment] 2020-11-24 07:56
yes,because i updated the vscode ,which included the dart devtool,and when i connected to iphone12,it will lost the connection the devices;

**Comment by pedromassangocode** [comment] 2020-11-24 09:00
Hi @wangxingxing123654 
Can you please elaborate what the issue is? It is not clear to me what you are trying to report.

**Comment by wangxingxing123654** [comment] 2020-11-25 06:30
![image](https://user-images.githubusercontent.com/28847126/100191221-b8c54500-2f2a-11eb-81d3-7fdeeccc3477.png)

**Comment by wangxingxing123654** [comment] 2020-11-25 06:30
> Hi @wangxingxing123654
> Can you please elaborate what the issue is? It is not clear to me what you are trying to report.

please look the picture below

**Comment by wangxingxing123654** [comment] 2020-11-25 06:31
> Hi @wangxingxing123654
> Can you please elaborate what the issue is? It is not clear to me what you are trying to report.
please look the picture below

**Comment by pedromassangocode** [comment] 2020-11-25 08:34
Hi @wangxingxing123654 
Can you please provide the steps to reproduce the issue?
Thanks

**Comment by wangxingxing123654** [comment] 2020-11-26 13:01
> Hi @wangxingxing123654
> Can you please provide the steps to reproduce the issue?
> Thanks

my mac os is mac big sur, xcode 12. it must be repeat the `lost connect to device` result. you can upgrade to mac big sur

**Comment by jonahwilliams** [comment] 2020-11-29 20:59
@pedromassango it is still unclear what the issue is here

**Comment by pedromassangocode** [comment] 2020-11-30 07:20
Hi @wangxingxing123654 
Please provide the steps to reproduce the issue?
Thanks

**Comment by wangxingxing123654** [comment] 2020-12-04 07:11
> Hi @wangxingxing123654
> Please provide the steps to reproduce the issue?
> Thanks

just upgrade to mac big sur, and newest vscode, and connect to the iphone12, when i need print the long text, it's must lost the connect to the device, but simulator wont lose the connection.

**Comment by pedromassangocode** [comment] 2020-12-04 08:06
Hi @wangxingxing123654 
Can you please provide the steps to reproduce the issue and the actual vs expected results? It is still unclear what the issue is, please list the steps to reproduce the issue so that anyone can test and verify it.
Thanks

**Comment by pedromassangocode** [comment] 2020-12-30 10:46
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 10:46 UTC
Labels: in triage, waiting for customer response
