### ISSUE TITLE
TextCapitalization.characters is not working

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#71153] opened 2020-11-24 12:55 UTC
`textCapitalization: TextCapitalization.characters` on `TextField` is not working on iOS. It works on Android Emulator when I combine it with `keyboardType: TextInputType.text` (without setting this `keyboardType` value it does not work on Android Emulator either).

I expect to tap on the `TextField` and see all characters on keyboard uppercase but they all lowercase.

Sample app:
```
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TextField(
      keyboardType: TextInputType.text,
      textCapitalization: TextCapitalization.characters,
      onChanged: (text) {},
    );
  }
}
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.22.4 at C:\dev\flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\dev\android
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\dev\android
    • Java binary at: C:\Users\Tudor (Work)\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Tudor (Work)\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Tudor (Work)\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    ! Device emulator-5562 is offline.

! Doctor found issues in 1 category.
```

**Comment by pedromassangocode** [comment] 2020-11-24 13:40
Hi @tudor07 
This is working as expected here.

![gif](https://user-images.githubusercontent.com/67424416/100101703-e2b33480-2e62-11eb-8a70-a5deb0ab1000.gif)

Can you please provide information about the device you are testing on?

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by tudor07** [comment] 2020-11-24 14:53
Ok so I've done more testing on:
- iPhone 12 Mini with iOS 14.2
- iPhone 7 with iOS 14.1
- iPhone 5s with iOS 12.4.9
- Samsung S8 with Android 8
- Lenovo P2 with Android 7
 
It does not work on any of these devices... so it's not an iOS only issue

Places where it works:
- iPhone 6 with iOS 12.3
- Android Emulator with Android 10

**Comment by pedromassangocode** [comment] 2020-11-25 07:03
Thanks.
I can't reproduce on emulators and I don't have those devices for tests. If anyone can reproduce on those devices that would be great.

**Comment by chinmaygarde** [comment] 2020-12-07 19:32
@pedromassangocode So is the hypothesis that this can only be reproduced on iOS devices and not the simulator (or Android)?

**Comment by tudor07** [comment] 2020-12-08 07:57
@chinmaygarde there was one iOS device where it worked, so it seems pretty random where it works and where it doesn't.

**Comment by pedromassangocode** [comment] 2020-12-08 09:38
> @pedromassangocode So is the hypothesis that this can only be reproduced on iOS devices and not the simulator (or Android)?

@chinmaygarde according to https://github.com/flutter/flutter/issues/71153#issuecomment-733024947 yes. It is possible to reproduce on some physical devices only be it iOS or Android.

**Comment by TahaTesser** [comment] 2020-12-08 11:06
Doesn't reproduce on physical XR and iPad (8th gen) running iOS 14.2 and iPad OS 14.2
| XR | iPad |
| --------------- | --------------- |
![IMG_0935](https://user-images.githubusercontent.com/48603081/101476197-66951280-3973-11eb-87b0-8d8b334eb530.PNG) | ![IMG_0185](https://user-images.githubusercontent.com/48603081/101476205-6a289980-3973-11eb-863d-1dd026dac5e5.PNG)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS
      14.2
    • iPhone 12 (mobile)   • C303B5A5-D598-4CAC-8ACC-09BF07A191DC • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by jawadrns** [comment] 2021-02-18 05:43
Any solution?

**Comment by jaysignorello** [comment] 2021-06-22 19:15
I thought I was running into this bug as well until I discovered my test device (iPhone X, 14.6) had Auto-Capitalization disable in the keyboard settings. You might want to check that as well.

**Comment by dupiesdupreez** [comment] 2023-08-28 09:26
Incase any one is still having this issue on your Emulator, 

Just remember, when you input text into your text input **do not use your physical computer keyboard** you should use the keyboard in the emulator itself. 

Using your computer keyboard will give you the false perception of it not working, because auto capitalization works by **capitalizing the Keyboard of the device**

**Comment by deepss1** [comment] 2023-12-13 12:37
Not sure if I should be opening another issue

I am able to reproduce this on a `MacOS` app
Flutter version : 3.16.3

**Comment by BawenderY** [comment] 2024-03-02 17:11
> Incase any one is still having this issue on your Emulator,
> 
> Just remember, when you input text into your text input **do not use your physical computer keyboard** you should use the keyboard in the emulator itself.
> 
> Using your computer keyboard will give you the false perception of it not working, because auto capitalization works by **capitalizing the Keyboard of the device**

But how about the web where the we use the physical computer keyboard? I see that this is not working on the web as well.

**Comment by deverlex** [comment] 2024-05-10 08:06
Any update or fix???

**Comment by dupiesdupreez** [comment] 2024-05-10 09:20
It was never broken - Don't use your pc keyboard, use the emulator keyboard.

**Comment by JetA2** [comment] 2024-07-05 15:14
I have this issue on Android and discovered that if you set `enableSuggestions: false` no text captialization settings work.
This did not use to be the case. Not sure if it's a bug or expected behaviour on Android.

**Comment by fchamone** [comment] 2024-08-08 22:25
> I have this issue on Android and discovered that if you set `enableSuggestions: false` no text captialization settings work. This did not use to be the case. Not sure if it's a bug or expected behaviour on Android.

Exactly what happened here as well, on Android emulator.

**Comment by tudor07** [comment] 2024-09-25 14:07
@darshankawar it's been 4 years, I don't even work with Flutter anymore

**Comment by darshankawar** [comment] 2024-09-26 04:54
Closing this out as not replicable and also considering below comments that suggest the solution works:

https://github.com/flutter/flutter/issues/71153#issuecomment-2211050957
https://github.com/flutter/flutter/issues/71153#issuecomment-866262668

If anybody still sees this as an issue using latest stable version, please file a new issue with relevant details.

**Closed by darshankawar** 2024-09-26 04:54 UTC
Labels: a: text input, e: device-specific, engine, P2, team-engine, triaged-engine
