### ISSUE TITLE
Slider within a TabBarView  onChangeEnd function fires at drag start. 

### ISSUE THREAD

**Issue by zero-is-one** [flutter/flutter#21069] opened 2018-08-27 16:47 UTC
## Steps to Reproduce

If you drag the slider the `onChangeEnd` event will fire at start of dragging and other random times. 

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new MyHomePage(title: 'Flutter Test Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _myValue = 60;

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: 3,
        child: new Scaffold(
          appBar: new AppBar(
            title: new Text(widget.title),
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
          ),
          body: new TabBarView(children: <Widget>[
            new Center(
              child: new Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  new Slider(
                    value: _myValue.toDouble(),
                    min: 1.0,
                    max: 100.0,
                    divisions: 10,
                    label: '$_myValue',
                    onChanged: (double newValue) {
                      setState(() {
                        _myValue = newValue.round();
                      });
                    },
                    onChangeEnd: (double newValue) {
                      print('Ended change on $newValue');
                    },
                  ),
                ],
              ),
            ),
            new Icon(Icons.directions_transit),
            new Icon(Icons.directions_bike),
          ]),
          // This trailing comma makes auto-formatting nicer for build methods.
        ));
  }
}
```

```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.5.1 at C:\src\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\victorsigma\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (2 available)
    • Pixel XL                  • HT6AB0202794  • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

```

**Comment by zoechi** [comment] 2018-08-31 18:49
I can confirm.
Seems to be a conflict with guestures with the TabBarView.
```
          body: new TabBarView(
              physics: NeverScrollableScrollPhysics(),
```
fixed it for me.

**Comment by TahaTesser** [comment] 2020-04-08 10:16
Issue still exist,  `onChangeEnd` event will fire at start of dragging 

`flutter doctor -v`
```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 8f7327f83a (31 hours ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

**Comment by zenkog** [comment] 2020-10-20 06:24
Got the same problem. Anyone has solution on this?

**Comment by darshankawar** [comment] 2020-12-30 13:39
Issue replicable on latest master. `onChangeEnd` is triggered on drag start as well as after drag stop.

```
I/flutter (23635): Ended change on 1.0
I/flutter (23635): Ended change on 40.6
I/flutter (23635): Ended change on 40.6
I/flutter (23635): Ended change on 50.5
I/flutter (23635): Ended change on 50.5
I/flutter (23635): Ended change on 60.4
I/flutter (23635): Ended change on 60.4
I/flutter (23635): Ended change on 70.3

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.137 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8f5d0371af (4 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.



```

</details>

**Comment by enricobenedos** [comment] 2021-03-08 18:00
Can someone tell us if there is any workaround for this issue? It is from more than two year that this issue exists and it is very frustrating that a basic component like `Slider` has this bug. 

If in a project you need to fire something at the `onChangedEnd` for example asking data from the API it results in a API overload. 

A similar problem exist with the `ListView()`, in this case the `onChangedEnd` fire when you start dragging and when you end (two times per user action).

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: DefaultTabController(
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            title: new Text('Slider Bug'),
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
          ),
          body: Builder(
            builder: (context) => TabBarView(children: <Widget>[
              Center(
                  child: RaisedButton(
                child: Text('Open Slider page'),
                onPressed: () => Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => MyStatefulWidget(),
                  ),
                ),
              )),
              new Icon(Icons.directions_transit),
            ]),
          ),
        ),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  double _currentSliderValue = 20;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView(
          children: [
            Slider(
              value: _currentSliderValue,
              min: 0,
              max: 100,
              divisions: 5,
              label: _currentSliderValue.round().toString(),
              onChanged: (double value) {
                setState(() {
                  _currentSliderValue = value;
                });
              },
              onChangeEnd: (double value) {
                print('onChangedEnd: $value');
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by nt4f04uNd** [comment] 2021-12-14 02:09
@TahaTesser I believe this was fixed, see https://github.com/flutter/flutter/issues/28115

**Comment by TahaTesser** [comment] 2021-12-14 08:03
Closing per the last comment, please follow up there. Thanks!

**Closed by TahaTesser** 2021-12-14 08:03 UTC
Labels: framework, f: material design, a: quality, has reproducible steps, P4, found in release: 1.22, found in release: 1.26
