### ISSUE TITLE
Would like an easy way to create a test

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4098] opened 2016-05-22 16:00 UTC
A separately 'new_test' template perhaps?  Maybe the easier way to solve this is to just put a test into the default create template? Maybe Dart already has solutions for this? @devoncarew

**Comment by Hixie** [comment] 2016-05-28 20:29
We should just have a test included with the flutter create template.

**Comment by Hixie** [comment] 2017-01-30 03:02
dupe of https://github.com/flutter/flutter/issues/4080

**Closed by Hixie** 2017-01-30 03:02 UTC
Labels: dev: tool, new feature
