### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by dancan-sandys** [flutter/flutter#121967] opened 2023-03-05 13:00 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile C:\Users\danca\Desktop\iso\intelligentIsoFrontend-3a54c614b252d98ba0bf89df6bbb3ca3fa2f389d\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Users\danca\Desktop\iso\intelligentIsoFrontend-3a54c614b252d98ba0bf89df6bbb3ca3fa2f389d\build\app\intermediates\flutter\debug -dTargetFile=C:\Users\danca\Desktop\iso\intelligentIsoFrontend-3a54c614b252d98ba0bf89df6bbb3ca3fa2f389d\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. Update flutter version to 3.7.6 from 3.3.0

## Logs
FileSystemException: Cannot delete file, OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File._deleteSync (dart:io/file_impl.dart:312:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#6      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:750:33)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:638:5)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:32)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19044.2604], locale en-US)
    • Flutter version 3.7.6 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (4 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\danca\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at C:\Users\danca\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM S134DL (mobile) • R9WT60DL6PV • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.2604]
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 110.0.1587.57

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d7946a68d26794349189cf21b3f68cc6fe61dcb
### Plugins
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
desktop_window-0.4.0
device_info_plus-4.0.0
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
flutter_local_notifications-12.0.4
fluttertoast-8.2.1
geolocator-9.0.2
geolocator_android-4.1.7
geolocator_apple-2.2.5
geolocator_web-2.1.6
geolocator_windows-0.1.1
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-1.0.5
path_provider-2.0.13
path_provider_android-2.0.23
path_provider_foundation-2.1.2
path_provider_linux-2.1.9
path_provider_windows-2.0.7
shared_preferences-2.0.18
shared_preferences_android-2.0.16
shared_preferences_foundation-2.1.4
shared_preferences_linux-2.1.4
shared_preferences_web-2.0.5
shared_preferences_windows-2.1.4
sqflite-2.2.4+1
url_launcher-6.1.5
url_launcher_android-6.0.24
url_launcher_ios-6.1.1
url_launcher_linux-3.0.3
url_launcher_macos-3.0.3
url_launcher_web-2.0.15
url_launcher_windows-3.0.4

**Comment by danagbemava-nc** [comment] 2023-03-06 08:38
Closing this as a duplicate of https://github.com/flutter/flutter/issues/88830.

**Closed by danagbemava-nc** 2023-03-06 08:38 UTC
Labels: in triage
