### ISSUE TITLE
App crashing having nested listviews with cachedNetwork images

### ISSUE THREAD

**Issue by Sjosh-cronJ** [flutter/flutter#41465] opened 2019-09-27 11:15 UTC
I am developing a flutter app which has 2 listViews(Items of listview is image box with infinite scrolling)  in page one is horizontal another is verticle, having images fetched using cached network image.On tabbing another page opens have

Issue 1> Cached network is throwing ERror 404 not found sometimes.
2. App crashes imminently while scrolling and clicking the item of listview navigating to a different screen and coming back. I disposed of everything correctly.

Code

```


  initState() {
...
  }

  final TextEditingController searchController =
      new TextEditingController(text: "");

  eventScrollListener() {
    try {
      if (_eventScrollController.position.maxScrollExtent ==
              _eventScrollController.offset &&
          !this._isEventLoading) {
        this.getMoreEvents();
      }
    } catch (error) {
      print(error);
    }
  }

  _flikScrollListener() {
    try {
      if (_flikScrollController.position.maxScrollExtent ==
              _flikScrollController.offset &&
          !this._fetchingMoreFliks) {
        this._getPublicFliks(false);
      }
    } catch (error) {
      print(error);
    }
  }

  void didChangeAppLifecycleState(AppLifecycleState state) {
    print(state);
    if (state.toString() == 'suspending') {
      this.dispose();
      this.initState();
    }
  }

  @override
  dispose() {
    try {
      SystemChannels.platform.invokeMethod<void>('SystemNavigator.pop');
      _eventScrollController.dispose();
      _flikScrollController.dispose();
      searchController.dispose();
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
      ]);
       if(Platform.isIOS){
         try {
        _rotationChannel.invokeMethod('setPortrait');
      } catch (error) {}
       }
      super.dispose();
    } catch (error) {
      print(error);
    }
  }

 
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () {
        exit(0);
      },
      child: this.searchClicked 
          ? Scaffold(
              body: Column(
                children: <Widget>[_getSearchBar()],
              ),
            )
          : Scaffold(
            floatingActionButton: SpeedDial(
               marginRight: 18,
               marginBottom: 20,
               child: this.changeIcon ? Icon(Icons.close) : Icon(Icons.add),
              closeManually: false,
               curve: Curves.bounceIn,
               overlayColor: Colors.black,
               overlayOpacity: 0.5,
               backgroundColor: Color.fromRGBO(124, 77, 255, 1),
               foregroundColor: Colors.white,
               elevation: 8.0,
               shape: CircleBorder(),
               onClose: (){
                 setState(() {
                   this.changeIcon = false;
                 });
               },
               onOpen: (){
                 setState(() {
                   this.changeIcon = true;
                 });
               },
               children: [
                 SpeedDialChild(
                   child: Icon(Icons.event),
                   backgroundColor: Colors.red,
                   label: 'Create an Event',
                   labelStyle: TextStyle(fontSize: 16.0),
                   onTap: () => this.userId != null
                       ? Navigator.push(
                           context,
                           MaterialPageRoute(
                             builder: (context) => CreateEvent(
                               eventFormType: EventFormType.CREATE,
                               eventId: null,
                               eventData: null,
                               tags: null,
                               routePage: 'HOMEI',
                             ),
                           ),
                         )
                       : Navigator.pushNamed(context, '/login'),
                 ),
                 SpeedDialChild(
                   child: Icon(Icons.video_library),
                   backgroundColor: Colors.blue,
                   label: 'Share a Video',
                   labelStyle: TextStyle(fontSize: 16.0),
                   onTap: () => this.userId != null
                       ? Navigator.push(
                           context,
                           MaterialPageRoute(
                             builder: (context) => ExploreEvents(
                               fromSpeedDial: true
                             ),
                           ),
                         )
                       : Navigator.pushNamed(context, '/login'),
                 ),
               ],
             ),
              body: Stack(
                children: [
                  Column(
                    children: [
                      _getAppBar(),
                      Divider(
                        height: 1.0,
                        color: Colors.black12,
                      ),
                      Expanded(
                        child: Container(
                          color: Colors.white,
                          child: MediaQuery.removePadding(
                            context: context,
                            removeTop: true,
                            child: RefreshIndicator(
                              onRefresh: this._onRefresh,
                              child: ListView.builder(
                                physics: new ClampingScrollPhysics(),
                                cacheExtent: 300,
                                addAutomaticKeepAlives: true,
                                controller: _flikScrollController,
                                itemCount: _publicFliksList.length + 4,
                                itemBuilder: (context, int index) {
                                  if (index == 0)
                                    return _getTitleBar(
                                        'Events', ExploreTitle.EVENTS);
                                  else if (index == 1)
                                    return _showEvents();
                                  else if (index == 2) {
                                    return Divider(
                                      height: 1.0,
                                      color: Colors.black38,
                                    );
                                  } else if (index == 3) {
                                    return Column(
                                      children: <Widget>[
                                        _getTitleBar(
                                            'Fliks', ExploreTitle.FLIKS),
                                      ],
                                    );
                                  } else if (index > 3)
                                    return _getFlikTile(
                                        index, this._publicFliksList.length);
                                },
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                  this._featchingFliks && !this.isPullToRefresh
                      ? Container(
                          margin: EdgeInsets.only(top: 400.0),
                          child: Center(
                            child: SpinKitWave(
                              size: 40.0,
                              itemBuilder: (_, int index) {
                                return DecoratedBox(
                                  decoration: BoxDecoration(
                                      color: Color.fromRGBO(124, 77, 255, 1)),
                                );
                              },
                            ),
                          ))
                      : Container()
                ],
              ),
            ),
    );
  }




  _showEvents() {
    return Container(
      width: double.infinity,
      height: 234.0,
      margin: EdgeInsets.only(
        right: 16.0,
      ),
      color: Colors.white,
      child: Stack(
        children: [
          ListView.builder(
            physics: new ClampingScrollPhysics(),
            cacheExtent: 300,
            addAutomaticKeepAlives: true,
            scrollDirection: Axis.horizontal,
            controller: _eventScrollController,
            shrinkWrap: true,
            itemCount: this._eventList.length,
            itemBuilder: (context, int index) {
              return GestureDetector(
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => EventInfo(
                        pageType: EventPageType.INFO,
                        eventId: this._eventList[index].id,
                        routePage: 'HOMEI',
                      ),
                    ),
                  );
                },
                child: EventWidget(
                  coverImage: this._eventList[index].coverImage,
                  eventEndTime: _eventList[index].eventEndTime,
                  eventStartTime: _eventList[index].eventStartTime,
                  eventName: _eventList[index].name,
                  creatorName: _eventList[index].creatorName,
                  eventWidgetType: EventWidgetType.CUSTOM_WIDTH,
                  isPrivate: _eventList[index].isPrivate,
                ),
              );
            },
          ),
          this._isEventLoading && !this.isPullToRefresh
              ? Center(
                  child: SpinKitWave(
                    size: 40.0,
                    itemBuilder: (_, int index) {
                      return DecoratedBox(
                        decoration: BoxDecoration(
                            color: Color.fromRGBO(124, 77, 255, 1)),
                      );
                    },
                  ),
                )
              : Container(),
        ],
      ),
    );
  }

  _getFlikTile(int index, int flikListLength) {
    return Column(
      children: [
        GestureDetector(
          child: FlikWidget(
            thumbnailUrl: this._publicFliksList[index - 4].thumbnailUrl,
            flikTitle: _publicFliksList[index - 4].flikTitle,
            creatorUserName: _publicFliksList[index - 4].creatorUserName,
            isEditable: false,
            editWidget: Container(),
            flikModel: _publicFliksList[index - 4],
            flikCreatedAt: _publicFliksList[index - 4].createdAt,
            totalViews: _publicFliksList[index - 4].totalViews.toString(),
            routeCallback: 'HOME',
            eventId: null,
            routePage: null,
            pageType: null,
          ),
          onTap: () {},
        ),
        Divider(
          height: 2,
        ),
        flikListLength == index - 3 && this._fetchingMoreFliks
            ? Container(
                padding: EdgeInsets.only(top: 10.0),
                height: 60.0,
                width: double.infinity,
                color: Colors.white,
                child: Column(
                  children: <Widget>[
                    Text(
                      'Hold On, Loading more fliks',
                      style: TextStyle(
                        fontFamily: 'Anvir',
                        letterSpacing: 0.50,
                      ),
                    ),
                    SpinKitWave(
                      size: 30.0,
                      itemBuilder: (_, int index) {
                        return DecoratedBox(
                          decoration: BoxDecoration(
                              color: Color.fromRGBO(124, 77, 255, 1)),
                        );
                      },
                    ),
                  ],
                ),
              )
            : Container()
      ],
    );
  }
}
  
```

**Comment by escamoteur** [comment] 2019-09-27 12:53
Please add the output of flutter doctor here.
Does this happen on iOS and Android?

**Comment by Sjosh-cronJ** [comment] 2019-09-27 13:26
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[!] Connected device
    ! No devices available
```


Both android and ios

**Comment by escamoteur** [comment] 2019-09-27 13:42
Just checked, cached NetworkImage

**Comment by Sjosh-cronJ** [comment] 2019-09-27 13:43
CachedNetwork image keeps giving error 404

**Comment by Sjosh-cronJ** [comment] 2019-09-27 13:45
> Just checked, cached NetworkImage is not a Flutter widget that we don't support.
> Does this happen too if you use Flutter Images?
Only cached network image gives me the ability to put error widger if the request fails with some error.I have to put placeholder if the image is not present in that URL or any other error occurs.

**Comment by escamoteur** [comment] 2019-09-27 13:50
I know that you want to use it but please try if you still get the error

**Comment by Sjosh-cronJ** [comment] 2019-09-27 13:51
ok

**Comment by Sjosh-cronJ** [comment] 2019-09-27 14:24
> Just checked, cached NetworkImage is not a Flutter widget that we don't support.
> Does this happen too if you use Flutter Images?

Flutter images means Image.network()

**Comment by escamoteur** [comment] 2019-09-27 15:02
Yes!

**Comment by bhanuka96** [comment] 2020-03-30 03:11
I removed `cacheExtent` and now working

**Comment by VladyslavBondarenko** [comment] 2020-05-05 15:11
Hi @Sjosh-cronJ 
Is it still an issue?
if yes, could you provide a **minimal complete** code sample to reproduce it without using a 3rd party plugin?

**Comment by VladyslavBondarenko** [comment] 2020-05-27 08:33
Closing since initial issue was reported about a 3rd party plugin.
If you disagree and it's an issue with flutter, please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-05-27 08:33 UTC
Labels: f: scrolling, framework, waiting for customer response
