### ISSUE TITLE
Date Picker fidelity

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#985] opened 2015-12-17 23:15 UTC
OEM widget:

![screenshot_20151217-150821](https://cloud.githubusercontent.com/assets/5479/11884756/e60f455e-a4d0-11e5-8e6f-ae6a69da3730.png)

Flutter widget:

![screenshot_20151217-150831](https://cloud.githubusercontent.com/assets/5479/11884759/efa32b9e-a4d0-11e5-9f06-4bc219817223.png)

Couple of things I noticed:

- [ ] dates are a darker color in OEM version
- [ ] left and right arrows in OEM version
- [ ] month name has more top padding in OEM version
- [ ] the day abbreviations are lighter, and thinner, in OEM version
- [ ] "cancel" seems closer to "ok" in the OEM version
- [ ] the year is in a different place

(also, the assumption is that the OEM widget follows the material design spec. Not sure if that's true? https://www.google.com/design/spec/components/pickers.html#pickers-usage looks more like the OEM version at a quick glance)

**Comment by abarth** [comment] 2015-12-18 04:46
We should aim to match the spec, not the OEM widget.  In either case, there's room for improvement.  :)

**Comment by sethladd** [comment] 2016-01-06 22:58
Good point re: the spec.

Looks like in this case the OEM widget is closer to the spec, if the spec is actually https://www.google.com/design/spec/components/pickers.html#


![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HVWZOVkdRQlJEdDg/components_pickers_date1.png)

**Comment by eseidelGoogle** [comment] 2016-01-06 23:19
Looks like the spec changed:
https://web.archive.org/web/20150325091005/http://www.google.com/design/spec/components/pickers.html
We likely wrote from an old version.
@appsforartists

**Comment by abarth** [comment] 2016-05-18 22:32
Duplicate of #3558

**Closed by abarth** 2016-05-18 22:32 UTC
Labels: affects: date picker, affects: framework, affects: material design, customer: demos, ⚠ bug
