### ISSUE TITLE
TextField is out the border on Mac App

### ISSUE THREAD

**Issue by MegatronKing** [flutter/flutter#98916] opened 2022-02-22 12:42 UTC
## Steps to Reproduce
<img width="800" alt="image" src="https://user-images.githubusercontent.com/15059084/155134277-2a80cdce-869f-4027-b019-1a39aa999117.png">

```dart
  @override
  Widget build(BuildContext context) {
    return TextField(
      maxLines: null,
      style: TextStyle(
        color: textColor,
        fontFamily: fontFamily,
        fontSize: textSize
      ),
      keyboardType: TextInputType.multiline,
      decoration: InputDecoration(
        border: InputBorder.none,
        fillColor: backgroundColor,
        isCollapsed: true,
        isDense: true
      ),
      scrollController: controller,
      showCursor: false,
      onChanged: onChanged,
      scrollPadding: const EdgeInsets.all(0)
    );
  }
```

Flutter version:
```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (10 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

**Comment by MegatronKing** [comment] 2022-02-22 12:56
Profiled widget:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/15059084/155136755-e1c0b035-0417-4379-8aec-a3d1cf2432b2.png">

**Comment by MegatronKing** [comment] 2022-02-23 06:13
Disabled the decoration, it is ok! Is this a bug?
```dart
TextField(
      maxLines: null,
      style: TextStyle(
        color: textColor,
        fontFamily: fontFamily,
        fontSize: textSize
      ),
      keyboardType: TextInputType.multiline,
      decoration: null,
      scrollController: controller,
      onChanged: onChanged
    );
```

**Comment by maheshmnj** [comment] 2022-02-23 08:18
Hi  @MegatronKing, Thanks for filing the issue. I am quite not sure from your screenshot what do you mean by textfield is out of border? Can you please clarify this?

 I see the text inside the Textfield border. 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/31410839/155282178-7b676511-6f58-4edf-9202-729cffcbb1d5.png">


<details>
<summary>flutter doctor -v</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Material(
        child: Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [MyStatefulWidget()],
    ));
  }
}

class MyStatefulWidget extends StatelessWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return TextField(
        maxLines: null,
        style: TextStyle(color: Colors.blue, fontSize: 16),
        keyboardType: TextInputType.multiline,
        decoration: InputDecoration(
            border: InputBorder.none,
            fillColor: Colors.blue.shade100,
            isCollapsed: true,
            isDense: true),
        showCursor: false,
        scrollPadding: const EdgeInsets.all(0));
  }
}

```
</details>

**Comment by MegatronKing** [comment] 2022-02-23 08:38
<img width="800" alt="image" src="https://user-images.githubusercontent.com/15059084/155285225-f52b0dcf-1028-42dd-aafa-ef8cb1081b9a.png">
This screenshot is set decoration to null, see the difference?

**Comment by maheshmnj** [comment] 2022-02-23 11:58
@MegatronKing, I compared both your screenshots side by side, Are your referring to the text highlight overflow on top in the first screenshot?

with decoration             |  without decoration
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/15059084/155136755-e1c0b035-0417-4379-8aec-a3d1cf2432b2.png)  |  ![](https://user-images.githubusercontent.com/15059084/155285225-f52b0dcf-1028-42dd-aafa-ef8cb1081b9a.png)

**Comment by MegatronKing** [comment] 2022-02-24 01:17
@maheshmnj Yes, that is what I mean.

**Comment by maheshmnj** [comment] 2022-02-25 05:02
@MegatronKing I think this is working as intended because the text is still within the bounds and the highlight could bypass the boundary,  the constraints of the highlight depends on different fonts and the Style of the Text. Closing as this is working as intended. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-02-25 05:02 UTC
Labels: in triage

**Comment by MegatronKing** [comment] 2022-02-25 06:08
@maheshmnj I don't think this is working as intended, I set a filled color and input more text to make it scrollable. When I scroll the content, both top and bottom is overflow, this is weird.
<img width="785" alt="image" src="https://user-images.githubusercontent.com/15059084/155663255-ae55fe2f-acb0-49be-b86f-f48f264e28b8.png">

**Comment by MegatronKing** [comment] 2022-02-25 06:10
My test code:
```
decoration: InputDecoration(
          border: InputBorder.none,
          filled: true,
          fillColor: Colors.blue,
          isCollapsed: true,
          isDense: true,
        ),
```

**Comment by maheshmnj** [comment] 2022-02-25 09:12
Please share a minimal and complete code sample to investigate further.
