### ISSUE TITLE
Maven Repository Flutter artifacts possibly outdated

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#88471] opened 2021-08-18 20:59 UTC
Looking at https://mvnrepository.com/artifact/io.flutter, it seems like all the artifacts were last uploaded on May 19, 2021. In addition, the version tags have the hash `b09f014e9658da6647361e7e416d1a159d34192d`, which is https://github.com/flutter/engine/commit/b09f014e9658da6647361e7e416d1a159d34192d. However, this release went out on April 15.

**Comment by christopherfujino** [comment] 2021-08-18 20:59
cc @blasten

**Comment by blasten** [comment] 2021-08-18 21:59
We don't depend on the Maven repository to distribute the Flutter artifacts.

@christopherfujino Do you know if this is an add-to-app user? It would help to get more context about why they aren't using our own repository in build.gradle.

**Comment by Cedricoh** [comment] 2021-08-19 17:53
Hey, I'm the guy who reported this.
I came across the issue while trying the know which version of Flutter corresponds with which artifact on the repo.

I need this information because I am building an app with an AAR Flutter module. The problem I ran into is this one (taken from the android logcat) :
`19/08 09:06:57:599	4413	F	DEBUG   	Abort message: '[FATAL:flutter/runtime/dart_vm_initializer.cc(22)] Error while initializing the Dart VM: Wrong full snapshot version, expected '2845111295952b75abc6dae3c101021b' found 'e4a09dbf2bb120fe4674e0576617a0dc'`

This using the artifact 1.0.0-033363c139ef4ad9c5d792e509700cb28a5fc46f and Flutter 2.2.3.

It seems that there is a discrepancy between the expected Dart Engine and the provided one. My guess is that I'm building the AAR with one version of Flutter, and getting another one (the wrong one) from the repo.
Thus, I want to know which version from the repo corresponds to the Flutter stable release 2.2.3. That's how I ended up on the Maven repo https://mvnrepository.com/artifact/io.flutter while searching for my answer.

Of course, I could be totally wrong when I assume that a discrepancy in Dart Engines is the cause of this particular error, but it seems to be the most obvious thing, so I wanted to make sure to have the correct version before reporting this as a bug.

There have been other instances of that error talked about on the internet, with most of the solutions involving switching branches/upgrading/downgrading. I think that point to my guess being the correct one.


I hope I've made myself clear enough :)

PS : Of course even if this problem gets solved, there still is this issue of the Maven repo being out there and sowing confusion. Doing something about that might prevent a lot of problems in the future, even if it's just marking it as deprecated.

**Comment by blasten** [comment] 2021-08-19 18:05
did you set the repository in build.gradle as suggested by `flutter build aar`?

**Comment by Cedricoh** [comment] 2021-08-19 18:14
Yep,
maven {
	url "https://storage.googleapis.com/download.flutter.io"
}

**Comment by blasten** [comment] 2021-08-19 18:18
do you have more than one aar?

**Comment by Cedricoh** [comment] 2021-08-19 18:19
Yes I do, should test without the additional aar ?

**Comment by blasten** [comment] 2021-08-19 18:41
All Flutter module AARs must be built with the exact same Flutter version, so if you have more than one, make sure they are built with the same version.

**Comment by Cedricoh** [comment] 2021-08-19 18:44
Damn, that MUST be it. I'm not at work rn, I'll come back to confirm that tomorrow morning. Thanks a lot for the info !

**Comment by blasten** [comment] 2021-08-19 19:38
sounds good. Feel free to reopen the issue if necessary.

**Closed by blasten** 2021-08-19 19:38 UTC
Labels: dependency: android, team: infra

**Comment by Cedricoh** [comment] 2021-08-20 06:12
Still not going. I've build the module with the last master :
```
Flutter 2.5.0-7.0.pre.160 • channel master • https://github.com/flutter/flutter.git
Framework • revision c37fe7c4fa (7 hours ago) • 2021-08-19 19:02:41 -0400
Engine • revision b20c1a3774
Tools • Dart 2.15.0 (build 2.15.0-33.0.dev)
```

Here's the logcat :

```
20/08 08:06:14:955	1186	F	DEBUG   	Abort message: '[FATAL:flutter/runtime/dart_vm_initializer.cc(22)] Error while initializing the Dart VM: Wrong full snapshot version, expected '2845111295952b75abc6dae3c101021b' found '6a884b4c15a6e3e2d318ce329af723cb'
20/08 08:06:14:955	1186	F	DEBUG   	    x0  0000000000000000  x1  000000000000526a  x2  0000000000000006  x3  0000007fd189a280
20/08 08:06:14:955	1186	F	DEBUG   	    x4  fd4463b6606ff709  x5  fd4463b6606ff709  x6  fd4463b6606ff709  x7  ff7f7fff7f7fff7f
20/08 08:06:14:955	1186	F	DEBUG   	    x8  00000000000000f0  x9  fe4564b76170f80a  x10 0000000000000001  x11 0000000000000000
20/08 08:06:14:955	1186	F	DEBUG   	    x12 fffffff0fffffbdf  x13 000000000a3f7378  x14 0000000000000000  x15 ffffffffffffffff
20/08 08:06:14:955	1186	F	DEBUG   	    x16 00000070294f78c0  x17 00000070294d4920  x18 000000702e27a000  x19 000000000000526a
20/08 08:06:14:955	1186	F	DEBUG   	    x20 000000000000526a  x21 00000000ffffffff  x22 0000006fa2f7b600  x23 0000006f916da3e0
20/08 08:06:14:955	1186	F	DEBUG   	    x24 0000000000000004  x25 0000000000000011  x26 0000006f9b68c1f8  x27 0000006f97593d53
20/08 08:06:14:955	1186	F	DEBUG   	    x28 0000006f97593d60  x29 0000007fd189a320
20/08 08:06:14:955	1186	F	DEBUG   	    sp  0000007fd189a260  lr  0000007029489108  pc  0000007029489134
20/08 08:06:14:956	1186	F	DEBUG   	
20/08 08:06:14:956	1186	F	DEBUG   	backtrace:
20/08 08:06:14:956	1186	F	DEBUG   	      #00 pc 0000000000083134  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: ecce0f8f6d05a6808531d834fd5e2b07)
20/08 08:06:14:956	1186	F	DEBUG   	      #01 pc 00000000002d2f54  /data/app/com.masociete.fluttertest-UpUkQW1JvIsN7xMjQpAHIg==/lib/arm64/libflutter.so (BuildId: c673a8d8a503abb556afdf5a8646ef3ab1516794)
```

To note, the found engine hash has changed. Unfortunately, I can't find which version of the Dart Engine that corresponds to (if it's even a version hash).
I built the app with version 1.0.0-033363c139ef4ad9c5d792e509700cb28a5fc46f from https://storage.googleapis.com/download.flutter.io as dependencies.
