### ISSUE TITLE
Pigeon : [FlutterApi] Support for asynchronous methods/Functions

### ISSUE THREAD

**Issue by xsahil03x** [flutter/flutter#64810] opened 2020-08-28 18:06 UTC
@gaaclarke 

`Issue:` Currently there is no way to define async methods in `(FlutterApi)` while generating code using Pigeon.

```dart
@FlutterApi()
abstract class TestFlutterApi {
  UserResult getUser(); // I want this to be async
}
```

This code here generates 
```java
abstract class TestFlutterApi {
  UserResult getUser();
  static void setup(TestFlutterApi api) {
    {
      const BasicMessageChannel<dynamic> channel =
          BasicMessageChannel<dynamic>('dev.flutter.pigeon.TestFlutterApi.getUser', StandardMessageCodec());
      channel.setMessageHandler((dynamic message) async {
        final UserResult output = api.getUser();
        return output._toMap();
      });
    }
  }
}
```
`Solution:` The solution is pretty simple, we just need to somehow tell the generator that this function is an async one. We can do this easily using an annotation to mark it such and just add an `await` keyword in front of the function execution while code generation.

```dart
@FlutterApi()
abstract class TestFlutterApi {
  @async
  UserResult getUser();
}
```
This will somehow generate

```java
abstract class TestFlutterApi {
  Future<UserResult> getUser();
  static void setup(TestFlutterApi api) {
    {
      const BasicMessageChannel<dynamic> channel =
          BasicMessageChannel<dynamic>('dev.flutter.pigeon.TestFlutterApi.getUser', StandardMessageCodec());
      channel.setMessageHandler((dynamic message) async {
        final UserResult output = await api.getUser();
        return output._toMap();
      });
    }
  }
}
```

**Comment by gaaclarke** [comment] 2020-08-28 22:48
Duplicate of https://github.com/flutter/flutter/issues/60399

Check out that issue for a workaround and to see what we were planning on implementing for this in the future.  Thanks!

**Closed by gaaclarke** 2020-08-28 22:48 UTC
