### ISSUE TITLE
Unable to upload image in flutter

### ISSUE THREAD

**Issue by MHBhura** [flutter/flutter#153481] opened 2024-08-15 01:57 UTC
### What package does this bug report belong to?

animations

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

```
dependencies:
  flutter:
    sdk: flutter
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  string_scanner: 1.2.0
  test_api: 0.7.2
  collection: 1.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
```

### Steps to reproduce

Need the solution

### Expected results

To be able to upload image

### Actual results

```
Resolving dependencies... (1.0s)
See https://dart.dev/go/sdk-version-pinning for details.


Because erp_next depends on flutter_test from sdk which depends on string_scanner 1.2.0, string_scanner 1.2.0 is required.
So, because erp_next depends on string_scanner ^1.3.0, version solving failed.
PS C:\Flutter\erp_next> flutter pub upgrade
Resolving dependencies... (1.3s)


Because erp_next depends on flutter_test from sdk which depends on string_scanner 1.2.0, string_scanner 1.2.0 is required.
So, because erp_next depends on string_scanner ^1.3.0, version solving failed.
PS C:\Flutter\erp_next>
PS C:\Flutter\erp_next> flutter pub get
Resolving dependencies... 
Downloading packages...
  collection 1.18.0 (1.19.0 available)
! cupertino_icons 1.0.8 (overridden)
  material_color_utilities 0.11.1 (0.12.0 available)
! test_api 0.7.2 (overridden) (0.7.3 available)
  web 0.5.1 (1.0.0 available)
Got dependencies!
5 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
PS C:\Flutter\erp_next> flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name              Current              Upgradable           Resolvable           Latest

direct dependencies:
cupertino_icons           *1.0.8 (overridden)  *1.0.8 (overridden)  *1.0.8 (overridden)  1.0.8

dev_dependencies: all up-to-date.

transitive dependencies:
collection                *1.18.0              *1.18.0              *1.18.0              1.19.0
material_color_utilities  *0.11.1              *0.11.1              *0.11.1              0.12.0
web                       *0.5.1               *0.5.1               *0.5.1               1.0.0
string_scanner            *1.2.0 (overridden)  *1.2.0 (overridden)  *1.2.0 (overridden)  1.3.0 (overridden)
test_api                  *0.7.2 (overridden)  *0.7.2 (overridden)  *0.7.2 (overridden)  0.7.3 (overridden)
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
PS C:\Flutter\erp_next>
Tools • Dart 3.5.0 • DevTools 2.37.2
```

### Code sample

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: LoginPage(),
```

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

**Comment by danagbemava-nc** [comment] 2024-08-15 08:40
There appears to be multiple issues here so the course of action required from us isn't clear. I'll be closing this due to the lack of clarity in this issue. Please file a new issue and provide a clear and concise description of what the issue is along with the relevant steps required to reproduce so that it can be properly addressed. 

Thank you

**Closed by danagbemava-nc** 2024-08-15 08:40 UTC
Labels: in triage
