### ISSUE TITLE
Crash when compiling package:vm_service/vm_service.dart when building flutter tool.

### ISSUE THREAD

**Issue by JustinWeru12** [flutter/flutter#55252] opened 2020-04-20 23:42 UTC
i tried to run flutter upgrade and it as been stuck in the following loop for over 8 hours. no other flutter command is running not even flutter doctor works anymore
`Building flutter tool...
Running pub upgrade...
Crash when compiling package:vm_service/vm_service.dart,
at character offset null:
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      scannerRecovery (package:_fe_analyzer_shared/src/scanner/recover.dart:29:17)
#2      _tokenizeAndRecover (package:_fe_analyzer_shared/src/scanner/scanner.dart:102:14)
#3      scan (package:_fe_analyzer_shared/src/scanner/scanner.dart:81:10)
#4      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:220:28)
<asynchronous suspension>
#5      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:294:26)
#6      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:255:13)
<asynchronous suspension>
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:257:20)
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:255:12)
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:129:28)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#12     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#13     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:224:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#25     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#26     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:359:17)
#27     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:163:45)
#28     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#29     _rootRun (dart:async/zone.dart:1122:38)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      scannerRecovery (package:_fe_analyzer_shared/src/scanner/recover.dart:29:17)
#2      _tokenizeAndRecover (package:_fe_analyzer_shared/src/scanner/scanner.dart:102:14)
#3      scan (package:_fe_analyzer_shared/src/scanner/scanner.dart:81:10)
#4      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:220:28)
<asynchronous suspension>
#5      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:294:26)
#6      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:255:13)
<asynchronous suspension>
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:257:20)
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:255:12)
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:129:28)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#12     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#13     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:224:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#25     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#26     SingleShotCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:359:17)
#27     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:163:45)
#28     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#29     _rootRun (dart:async/zone.dart:1122:38)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Error: Unable to create dart snapshot for flutter tool.
Building flutter tool...
Running pub upgrade...`

**Comment by TahaTesser** [comment] 2020-04-21 09:03
Hi @JustinWeru12 
can you please provide your `flutter doctor -v` or any copy/paste whatever message you getting when you try to execute `flutter doctor -v`? 
Thank you

**Comment by Lloyd0577** [comment] 2020-05-03 04:55
same problem in flutter channel beta

**Comment by jonahwilliams** [comment] 2020-05-03 05:00
Can you provide more information on the operating system you are using?

**Comment by jonahwilliams** [comment] 2020-05-03 05:02
Could you also run `git rev-parse HEAD` in the flutter checkout? This will contain a hash we can use to lookup the flutter version you are on?

**Comment by Lloyd0577** [comment] 2020-05-03 05:48
what my problem is that terminal stuck with 'Building flutter tool... ' after run any flutter command, my os is mac catalina,is it caused by network? i am in china , but i had opened vpn.

**Comment by jonahwilliams** [comment] 2020-05-03 08:35
@Lloyd0577  if you're not crashing then the issue is different, possible during the `pub upgrade` stage. I would recommend following https://flutter.dev/community/china

**Comment by Lloyd0577** [comment] 2020-05-03 09:02
@jonahwilliams  thanks for your reply , my problem was solved, I switched to china mirror finally

**Comment by JustinWeru12** [comment] 2020-05-03 12:49
I found that the only solution is removing flutter then installing a new version..

**Comment by JustinWeru12** [comment] 2020-05-03 12:52
No flutter command can run at this stage.... Flutter upgrade tries to install dart and fails... After this it keeps retrying and it does this 10times before failing and starting attempt one again.... This repeats infinitely. As far as I know.

**Comment by iapicca** [comment] 2020-07-01 13:29
Hi @JustinWeru12 
could you please provide 
your `flutter doctor -v `
and the information listed above [[1](https://github.com/flutter/flutter/issues/55252#issuecomment-623054376), [2](https://github.com/flutter/flutter/issues/55252#issuecomment-623054530)]
Thank you

**Comment by TahaTesser** [comment] 2020-07-24 14:15
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-24 14:15 UTC
Labels: in triage
