### ISSUE TITLE
Flutter Web : Videos Not playing from the files I picked from my device.

### ISSUE THREAD

**Issue by abdulrehman192** [flutter/flutter#139444] opened 2023-12-03 11:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am picking up a video file from the device drive using file picker and image picker. and load the controller as network. but the video players is not initialized. There should be a option to run the video from byte array.

### Expected results

Video should be run from memory. There must be a memory constructor.

### Actual results

Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, DEMUXER_ERROR_NO_SUPPORTED_STREAMS: FFmpegDemuxer: no supported streams, The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

### Code sample

<details><summary>Code sample</summary>

```dart
pickMediaFile() async{
    final ImagePicker picker = ImagePicker();
    final XFile? media = await picker.pickMedia();
    if(media != null){
      if(kIsWeb){
        videoPlayerController = VideoPlayerController.networkUrl(Uri.parse(media.path));
        await videoPlayerController.initialize();
        update();
      }
      else
      {

      }

    }
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
C:\Users\mrabd>flutter doctor -v
[√] Flutter (Channel stable, 3.13.7, on Microsoft Windows [Version 10.0.19045.3693], locale en-PK)
    • Flutter version 3.13.7 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (8 weeks ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\mrabd\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Java\jdk-11.0.14\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.31)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34114.132
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.3
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\mrabd\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • AC2003 (mobile)   • adb-42b69244-d0zCdr._adb-tls-connect._tcp • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows                                   • windows-x64    • Microsoft Windows [Version
      10.0.19045.3693]
    • Chrome (web)      • chrome                                    • web-javascript • Google Chrome 119.0.6045.124
    • Edge (web)        • edge                                      • web-javascript • Microsoft Edge 119.0.2151.93

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by stuartmorgan** [comment] 2023-12-03 19:27
> There must be a memory constructor.

Closing as a duplicate of https://github.com/flutter/flutter/issues/53017

**Closed by stuartmorgan** 2023-12-03 19:27 UTC
