### ISSUE TITLE
[tool_crash] _TypeError: (#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24))

### ISSUE THREAD

**Issue by Abubakr50** [flutter/flutter#146149] opened 2024-04-02 19:12 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24))
```
#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:178:24)
#1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:746:57)
<asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.5, on macOS 14.3.1 23D60 darwin-x64, locale ar-SA)
    [32m•[39m Flutter version 3.19.5 on channel stable at /Users/imac/Downloads/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 300451adae (in the future), 2024-03-27 21:54:07 -0500
    [32m•[39m Engine revision e76c956498
    [32m•[39m Dart version 3.3.3
    [32m•[39m DevTools version 2.31.1

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/imac/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
    [31m✗[39m Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.3)
    [32m•[39m Xcode at /Users/imac/Downloads/Xcode.app/Contents/Developer
    [32m•[39m Build 15E5202a
    [32m•[39m CocoaPods version 1.14.0

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.83.1)
    [32m•[39m VS Code at /Users/imac/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.84.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 14.3.1 23D60 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.129
    [33m![39m Error: Browsing on the local area network for Zak. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: d3d8effc686d73e0114d71abdcccef63fa1f25d2
### Plugins
app_tracking_transparency-2.0.4
connectivity_plus-5.0.2
flutter_localization-0.2.0
fluttertoast-8.2.4
mobile_device_identifier-0.0.2
path_provider-2.1.1
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
singular_flutter_sdk-1.3.3
sqflite-2.3.0
url_launcher-6.2.4
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.0
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.0
webview_flutter-4.4.4
webview_flutter_android-3.13.1
webview_flutter_wkwebview-3.10.0

**Comment by danagbemava-nc** [comment] 2024-04-03 06:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/145740

**Closed by danagbemava-nc** 2024-04-03 06:41 UTC
Labels: in triage
