### ISSUE TITLE
Flutter widgets in Unity 3D 

### ISSUE THREAD

**Issue by rohitdesaidev** [flutter/flutter#73287] opened 2021-01-05 02:32 UTC
## Use case
Render Flutter UI inside Unity 3D applications.

## Proposal

I am looking for support which can render the flutter widgets inside unity 3d engine. 
This will be helpful to utilize our current flutter application and building 3D applications. 
I am new to flutter it will be helpful if anyone can suggest me how I can achieve this with flutter API or Flutter Engine.

**Comment by sidrao2006** [comment] 2021-01-05 07:28
Rendering flutter widgets in unity may not be possible but the other way around is .

Check out [`flutter_unity_widget`](https://pub.dev/packages/flutter_unity_widget) which allows you to embed Unity game scenes in flutter.

And this Medium article might be helpful - [Unity 3D in Flutter](https://medium.com/@weird_beird/unity-3d-in-flutter-e842b982d0f)

Since this is not a core functionality, this could make a good plugin if the above doesn't fit your needs

**Comment by iapicca** [comment] 2021-01-05 08:04
duplicate of https://github.com/flutter/flutter/issues/18509

**Comment by TahaTesser** [comment] 2021-01-05 08:11
Hi @rohitdesaidev 
Indeed a duplicate of https://github.com/flutter/flutter/issues/18509
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-05 08:11 UTC

**Comment by rohitdesaidev** [comment] 2021-01-05 17:21
Thanks for responding on my request so quickly.
Hi @TahaTesser ,
I agree it is duplicate of what was asked for. But the answer their I found was integrating unity inside flutter, not vise versa(which was a request), So I reopened new request where I wanted to see if this is possible with unity 3d (using flutter engine in unity and so on). As my I am trying to load flutter widgets inside unity app. Please guide me if this is possible and from where can I start as I am beginner in flutter. 

Thank you.
