### ISSUE TITLE
[state restoration] restorablePush called with List<String?> argument type, but routeBuilder called with List<Object?> argument type

### ISSUE THREAD

**Issue by azizarc88** [flutter/flutter#132021] opened 2023-08-07 03:18 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create screen to be opened using restorablePush
2. Pass List<String?> type of variable on restorablePush argument
3. Simulate open restorablePush screen
4. Simulate don't keep activities
5. When we reopen the apps, the error occurred, said type 'List<Object?>' is not a subtype of type 'List<String?>' in type cast

### Expected results

The argument type of routeBuilder should be the same as argument type when we push screen using restorablePush, since List<String?> is can be serializable using StandardMessageCodec

### Actual results

routeBuilder is called with argument type List<Object?> instead of List<String?>

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

final navigatorKey = GlobalKey<NavigatorState>();

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      restorationScopeId: "app",
      navigatorKey: navigatorKey,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const SplashScreen(),
      builder: _builder,
    );
  }

  Widget _builder(BuildContext context, Widget? child) {
    return child ?? const Scaffold();
  }
}

class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            const TypeScreen(
              type: TypeEnum.test1,
              title: "TEST1",
            ).openRestorable();
          },
          child: const Text("TEST"),
        ),
      ),
    );
  }
}

enum TypeEnum { test1, test2 }

T? stringToEnum<T>(Iterable<T> values, String? value) {
  for (var type in values) {
    if ((type as Enum).name == value) return type;
  }
  return null;
}

class TypeScreen extends StatefulWidget {
  final String? title;
  final TypeEnum type;

  const TypeScreen({
    super.key,
    required this.type,
    this.title,
  });

  @override
  State<TypeScreen> createState() => _TypeScreenState();

  @pragma('vm:entry-point')
  static Route<void> _routeBuilder(BuildContext context, Object? rawArguments) {
    final argument = rawArguments as List<String?>;
    final screen = TypeScreen(
      type: stringToEnum<TypeEnum>(
        TypeEnum.values,
        argument[0],
      )!,
      title: argument[1],
    );
    return MaterialPageRoute<void>(
      builder: (context) => screen,
    );
  }

  String? openRestorable({bool replace = false, dynamic result}) {
    final argument = <String?>[type.name, title];
    if (replace) {
      return navigatorKey.currentState?.restorablePushReplacement(
        _routeBuilder,
        arguments: argument,
        result: result,
      );
    } else {
      return navigatorKey.currentState?.restorablePush(
        _routeBuilder,
        arguments: argument,
      );
    }
  }
}

class _TypeScreenState extends State<TypeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title ?? "unknown"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Type Screen: ${widget.type.name}',
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/19973012/76fe3009-5cf1-4454-add1-d91e1ec51a10

</details>

### Logs

<details><summary>Logs</summary>

```console
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building _FocusMarker:
type 'List<Object?>' is not a subtype of type 'List<String?>' in type cast

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/aziz/StudioProjects/restoration_test/lib/main.dart:14:12
When the exception was thrown, this was the stack: 
#0      TypeScreen._routeBuilder (package:restoration_test/main.dart:81:35)
#1      _AnonymousRestorationInformation.createRoute (package:flutter/src/widgets/navigator.dart:5422:47)
#2      _RestorationInformation.toRouteEntry (package:flutter/src/widgets/navigator.dart:5331:34)
#3      _HistoryProperty.restoreEntriesForPage (package:flutter/src/widgets/navigator.dart:5552:69)
#4      NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3334:42)
#5      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:917:5)
#6      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:903:7)
#7      NavigatorState.didChangeDependencies (package:flutter/src/widgets/navigator.dart:3405:11)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5119:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (338 frames)
#347    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#348    Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)
#349    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#350    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#351    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#352    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#353    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#354    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#355    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#356    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#357    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
#361    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.2, on macOS 14.0 23A5301h darwin-arm64, locale id-ID)
    • Flutter version 3.7.2 on channel stable at /Users/aziz/Library/Flutter/main
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32fb2f948e (6 months ago), 2023-02-08 07:30:10 -0800
    • Engine revision f40b73f8a4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
    • Android SDK at /Users/aziz/Library/Android/sdk
    • Platform android-33, build-tools 34.0.0-rc4
    • ANDROID_HOME = /Users/aziz/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5195m
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.0 23A5301h darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2023-08-07 11:21
Hi @azizarc88. Thanks for filing this issue. I'm unable to reproduce this issue on the latest versions of flutter (Tested on Android and iOS). I see you are on an old version, can you upgrade to the latest versions of flutter to confirm this issue no longer persists?

https://github.com/flutter/flutter/assets/53122008/f421059b-ea98-4d1b-b3cc-78c5782b4bf5

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!

``` 

</p>
</details>

**Comment by azizarc88** [comment] 2023-08-08 02:49
have you enable don't keep activities from developer option ?

**Comment by dam-ease** [comment] 2023-08-08 08:16
Hi @azizarc88. Thanks for explaining further, I am able to reproduce this issue on Android with the steps you explained on the latest `master` and `stable` channels. Not too sure but this might be the expected behavior. Can you try this if it works in your use-case:

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

final navigatorKey = GlobalKey<NavigatorState>();

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      restorationScopeId: "app",
      navigatorKey: navigatorKey,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const SplashScreen(),
      builder: _builder,
    );
  }

  Widget _builder(BuildContext context, Widget? child) {
    return child ?? const Scaffold();
  }
}

class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            const TypeScreen(
              type: TypeEnum.test1,
              title: "TEST1",
            ).openRestorable();
          },
          child: const Text("TEST"),
        ),
      ),
    );
  }
}

enum TypeEnum { test1, test2 }

T? stringToEnum<T>(Iterable<T> values, String? value) {
  for (var type in values) {
    if ((type as Enum).name == value) return type;
  }
  return null;
}

class TypeScreen extends StatefulWidget {
  final String? title;
  final TypeEnum type;

  const TypeScreen({
    super.key,
    required this.type,
    this.title,
  });

  @override
  State<TypeScreen> createState() => _TypeScreenState();

  @pragma('vm:entry-point')
  static Route<void> _routeBuilder(BuildContext context, Object? rawArguments) {
    final argument = rawArguments as List;
    final screen = TypeScreen(
      type: stringToEnum<TypeEnum>(
        TypeEnum.values,
        argument[0],
      )!,
      title: argument[1],
    );
    return MaterialPageRoute<void>(
      builder: (context) => screen,
    );
  }

  String? openRestorable({bool replace = false, dynamic result}) {
    final argument = <Object?>[type.name, title];
    if (replace) {
      return navigatorKey.currentState?.restorablePushReplacement(
        _routeBuilder,
        arguments: argument,
        result: result,
      );
    } else {
      return navigatorKey.currentState?.restorablePush(
        _routeBuilder,
        arguments: argument,
      );
    }
  }
}

class _TypeScreenState extends State<TypeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title ?? "unknown"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Type Screen: ${widget.type.name}',
            ),
          ],
        ),
      ),
    );
  }
}
``` 

</p>
</details>

**Comment by dam-ease** [comment] 2023-08-08 09:23
Thanks for your response @azizarc88. Yes, it seems to be supported but also from the doc:

> Decoded values will use List<Object?> and Map<Object?, Object?> irrespective of content.

**Comment by azizarc88** [comment] 2023-08-08 10:03
yes, but why List<Object?> cannot directly cast to List<String?> and throwing an error 🤔

**Comment by dam-ease** [comment] 2023-08-09 07:34
Hi @azizarc88. Thanks for responding. To cast a List<Object?> to List<String?>:

```dart
List<Object?> objectList = ["1", 'two', "3.0", null, 'five'];

  List<String?> stringList = objectList.cast<String?>();
``` 

or 

```dart
List<Object?> originalList = [1, 'two', 3.0, null, 'five'];

List<String?> stringList = originalList.map((item) {
  if (item is String) {
    return item;
  } else if (item != null) {
    return item.toString();
  } else {
    return null;
  }
}).toList();
```  

Closing this as this seems to have been resolved, if you disagree, kindly comment and I'd reopen this.
Thank you!

**Closed by dam-ease** 2023-08-09 07:34 UTC
Labels: in triage
