### ISSUE TITLE
Animation performance problem when used with platform view

### ISSUE THREAD

**Issue by EugenePisotsky** [flutter/flutter#49241] opened 2020-01-21 21:06 UTC
Hello,

I noticed that animated views in stack sometimes are janky when I drag or especially zoom map. It happens periodically, sometimes it works smooth, but at some point performance is getting down. Here's the video (iPhone XS Max):
https://youtu.be/XS2Iynr4Abg

And here's how it looks on IDE timeline:
https://youtu.be/0t7U322vnAo

I was able to reproduce it with Google Maps and Mapbox.

Tested also on Android (very average phone), frames also dropped to 30fps, but flutter animation doesn't look janky.

## Steps to Reproduce

Git repo with example:
https://github.com/EugenePisotsky/flutter_reproduce_bug

<details>
  <summary>Logs</summary>

```
% flutter analyze
Analyzing bug...                                                        
No issues found! (ran in 3.1s)
```

```
% flutter doctor -v
Downloading android-arm-profile/darwin-x64 tools...                 0.5s
Downloading android-arm-release/darwin-x64 tools...                 0.4s
Downloading android-arm64-profile/darwin-x64 tools...               0.4s
Downloading android-arm64-release/darwin-x64 tools...               0.3s
Downloading android-x64-profile/darwin-x64 tools...                 0.4s
Downloading android-x64-release/darwin-x64 tools...                 0.3s
[✓] Flutter (Channel master, v1.14.2-pre.59, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.14.2-pre.59 at /Users/eugenepisotsky/Development/flutter
    • Framework revision 8086dd601f (2 hours ago), 2020-01-21 13:11:38 -0500
    • Engine revision 975c9c8607
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 ef0c7f16e6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/eugenepisotsky/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] Connected device (3 available)
    • iPhone (Eugene) • 00008020-001A5D121123002E • ios            • iOS 13.2.3
    • Chrome          • chrome                    • web-javascript • Google Chrome 78.0.3904.97
    • Web Server      • web-server                • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by liyuqian** [comment] 2020-11-09 23:00
The frame times in https://youtu.be/XS2Iynr4Abg and those in https://youtu.be/0t7U322vnAo don't seem to agree with each other. In the former, GPU thread (now raster thread) and UI thread have a sum of max frame time less than 16ms. In the latter, the frame time constantly goes above 16ms. I wonder if this difference is due to iOS vs Android?

I also noticed that
> Here's the video (iPhone XS Max)

and

> Tested also on Android (very average phone), frames also dropped to 30fps, but flutter animation doesn't look janky.

which seems to suggest that the videos are recorded on iPhone XS Max while the actual performance issue is only reproduced on average Android phones. @EugenePisotsky , can you please confirm if that's the case?

**Comment by EugenePisotsky** [comment] 2020-11-10 04:04
@liyuqian 

> which seems to suggest that the videos are recorded on iPhone XS Max while the actual performance issue is only reproduced on average Android phones. @EugenePisotsky , can you please confirm if that's the case?

Android is not a problem, I mentioned it because even on average android phone flutter animation visually looks fine, but not on XS.

I'm not sure if you can notice it, but if you look at that green box when I start zooming the map, you can see that it stops being smooth after a while.

> The frame times in https://youtu.be/XS2Iynr4Abg and those in https://youtu.be/0t7U322vnAo don't seem to agree with each other. In the former, GPU thread (now raster thread) and UI thread have a sum of max frame time less than 16ms. In the latter, the frame time constantly goes above 16ms. I wonder if this difference is due to iOS vs Android?

<details>
 <summary>Both are iOS. I was not sure why it was different on IDE so I recorded both. I'm on master channel and have just tried again. Here are screenshots how it looks now (the same app on XS). Animation still feels janky</summary>
<img width="485" alt="Screenshot 2020-11-10 at 05 53 52" src="https://user-images.githubusercontent.com/5047628/98625925-4abd3300-2319-11eb-879a-483a7716b780.png">
<img width="485" alt="Screenshot 2020-11-10 at 05 53 52" src="https://user-images.githubusercontent.com/5047628/98626142-b56e6e80-2319-11eb-940c-ec184a169ed6.jpeg">
</details>

**Comment by liyuqian** [comment] 2020-11-10 04:30
I see. Then this looks like a iOS platform view thread scheduling issue to me. In the performance overlay, raster and UI threads are both fast, but the final animation may look janky if not many frames are actually scheduled. This seems to be captured by the IDE plugin. @kenzieschmoll : do you know how the IDE plugin currently measures the frame time?

@cyanglaz @iskakaushik , are you familiar with the thread scheduling issue here? I vaguely remember that if there are platform views, sometimes Flutter has to merge raster and UI threads and that may affect performance. The fact that iOS is much more janky than Android seems to suggest that our thread handling on iOS platform views might be a little inferior than the Android approach.

**Comment by cyanglaz** [comment] 2020-11-10 17:10
On iOS, the platform thread and raster thread are merged when there are platform views. The performance will be dropped when there are platform views since both rasterizer and platform views are running on a single thread.
However, I would imagine, on iOS,  only the platform thread should have a load burden,  both raster thread and UI thread should be OK. (Which is inline with the first video recorded on iOS)

@EugenePisotsky  Is it possible we can see the platform thread measurement in the same sequence in your video?

On Android, there is no thread merging, so the performance drop is not related to thread merging. Which also explains that the flutter widgets' performance were ok, since they were still drawn on the raster thread.

**Comment by kenzieschmoll** [comment] 2020-11-10 17:18
IIRC, the flutter intellij plugin measures frame time from the `flutter.frame` events sent by the framework. This only encompasses the work on the UI thread, though. For a more accurate calculation of both the frame time for the UI and Raster threads, I would use the DevTools timeline.

**Comment by TahaTesser** [comment] 2021-04-27 13:43
Hi @EugenePisotsky 
I cannot see the spikes in Android Studio when running your project with the latest `google_maps_flutter: ^2.0.3` 

<img width="467" alt="Screenshot 2021-04-27 at 4 37 35 PM" src="https://user-images.githubusercontent.com/48603081/116251017-ee3eba80-a776-11eb-8b48-82c58782c24c.png">

### Preview of the testing

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/116251723-9c4a6480-a777-11eb-84db-885c0819d101.gif)

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.93

• No issues found!
```
		
</details>

Can you please upgrade to the latest  `stable` &. `google_maps_flutter`  and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by pedromassangocode** [comment] 2021-05-19 12:15
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

- [ ]

**Closed by pedromassangocode** 2021-05-19 12:15 UTC
Labels: P4, a: platform-views, p: first party, p: maps, platform-ios, plugin, severe: performance, waiting for customer response
