### ISSUE TITLE
build_runner is throwing an exception after the 2.2 upgrade when used with hive_generator

### ISSUE THREAD

**Issue by flutterfromscratch** [flutter/flutter#83404] opened 2021-05-26 11:03 UTC
I am experiencing an issue with `build_runner` in Flutter 2.2. This used to work fine with previous versions of Flutter. Specifically, I experience an issue when I attempt to use Hive with my app.

## Steps to Reproduce

1. flutter create new testapp
2. add all depenencies for Hive to the app
```
dependencies:
  hive: ^2.0.4
  hive_flutter: ^1.0.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
```

3. at the command line, run `flutter packages pub run build_runner build`
4. watch it asplode

I am logging this issue here, and not at the Hive repository, because this used to work fine in Flutter before 2.2. In a brand new project I noticed it failing. Weirdly, the `hive_generator` package depends on `analyzer` 1.0.0, but as I can see in the error, it seems to be trying to use analyzer 1.6.0.

I googled my heart out and searched StackOverflow, and also reproduced the same issue on my M1 Macbook, so it's not just a local computer thing.

## Logs

<details>
<summary>Logs</summary>

```
C:\code\baptest>flutter packages pub run build_runner build
Failed to precompile build_runner:build_runner:
/e:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:1600:40: Error: Getter not found: 'topLevelVariable'.
      return kinds.contains(TargetKind.topLevelVariable);
                                       ^^^^^^^^^^^^^^^^
/e:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Getter not found: 'topLevelVariable'.
      case TargetKind.topLevelVariable:
                      ^^^^^^^^^^^^^^^^
/e:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Type 'dynamic' of the case expression is not a subtype of type 'TargetKind' of this switch expression.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('/e:/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0/lib/meta_meta.dart').
      case TargetKind.topLevelVariable:
                      ^
/e:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2001:13: Context: The switch expression is here.
    switch (this) {
            ^
pub finished with exit code 1
```

```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.985], locale en-AU)
    • Flutter version 2.2.0 at e:\flutter
    • Framework revision b22742018b (11 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\lewci\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3
    • Flutter plugin version 55.1.4
    • Dart plugin version 203.8173

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\lewci\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.66

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-05-26 11:05
Hi @flutterfromscratch 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/build/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-26 11:05 UTC
Labels: in triage

**Comment by flutterfromscratch** [comment] 2021-05-26 14:22
It's not technically an issue with Flutter, but anyone trying to use `build_runner` right now (which forms part of many Flutter tutorials or even Google's own documentation) won't be able to. Surely that's worth a mention somewhere here?

The original dart-lang issue tracking this issue is here: https://github.com/dart-lang/sdk/issues/46142
