### ISSUE TITLE
Weird IntelliJ IDE "error message": Invalid constant value.

### ISSUE THREAD

**Issue by hundeva** [flutter/flutter#9837] opened 2017-05-05 11:10 UTC
When creating a `FractionalOffset` with `const`, IntelliJ will highlight the first import as an [error](http://i.imgur.com/q7eioB0.png). For example, both `import 'package:flutter/foundation.dart';` and `import 'package:flutter/material.dart';` import can be reported as an error, depending on if you use for example `@required` annotation in your dart file.

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

class Test {
  FractionalOffset offset = const FractionalOffset(0.0, 0.02);
}
```

The app is still going to compile, and function correctly regardless. Replacing `const` with `new` "solves" the issue, and the error message dissappears:

```dart
import 'package:flutter/material.dart';

class Test {
  FractionalOffset offset = new FractionalOffset(0.0, 0.02);
}
```

This is a very minor issue, as nothing breaks, it is however annoying to see all of your folders underlined with the red error indicator up until the project root.

For reference, the dart-lang github has this exact [issue](https://github.com/dart-lang/sdk/issues/29358), which was closed 7 days ago. I suppose a future dart upgrade should solve the problem.

**Comment by eseidelGoogle** [comment] 2017-05-05 14:38
I believe this is a dupe of https://github.com/flutter/flutter/issues/9438

**Comment by hundeva** [comment] 2017-05-05 15:33
Yeah, they seem to be the same.

**Comment by mit-mit** [comment] 2017-06-09 12:16
Closing. @hundeva the expected dupe #9438 has been resolved, so if you are still seeing this after updating please reopen, or open a new bug.

**Closed by mit-mit** 2017-06-09 12:16 UTC

**Comment by glenfordwilliams** [comment] 2019-01-27 17:59
currently  experiencing this issue 

```
Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (8 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.3)
[✓] Connected device (1 available)

• No issues found!
```
![screenshot from 2019-01-27 12-57-57](https://user-images.githubusercontent.com/1114368/51804808-3fc40c00-2233-11e9-819f-9d2aa0cc7009.png)

**Comment by zoechi** [comment] 2019-01-27 18:16
@glenfordwilliams I doubt `widget.title` is a valid constant value.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
