### ISSUE TITLE
[Firebase Storage] getReferenceFromUrl returns wrong storage reference path

### ISSUE THREAD

**Issue by ugurcany** [flutter/flutter#56661] opened 2020-05-08 10:35 UTC
I have a file which resides in the following path in Firebase storage: **/users/{userid}/avatar.jpg**

I'm putting this file in storage, then retrieve its download URL via `getDownloadURL` method. Afterwards, I'm saving this download URL in Firestore.

Whenever I want to delete this file from storage, I'm using this download URL already saved in Firestore to retrieve the storage reference of this file. So, I'm using this method:

```
StorageReference avatarRef =
        await _firebaseStorage.getReferenceFromUrl(user.avatarUrl);
```

When I debug this `avatarRef` object, I see that its `path` field has the value: **/users/{userid}/{userid}/avatar.jpg**

As you can see the path involves duplicate `{userid}`s. Therefore `avatarRef.delete()` operation fails due to this wrong reference path.

I tested this on an Android device. And here is my `flutter doctor` output:
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-05-08 11:53
Hi @ugurcany 
for what I can see the issue is related to a FlutterFire plugin, please open the issue in the dedicated [GitHub](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by TahaTesser** 2020-05-08 11:53 UTC
