### ISSUE TITLE
[cupertino] Text is rendered black (so not visible) by default in dark mode 

### ISSUE THREAD

**Issue by andreacimino** [flutter/flutter#48438] opened 2020-01-08 20:45 UTC
## Steps to Reproduce

[main.dart.zip](https://github.com/flutter/flutter/files/4037104/main.dart.zip)

Text is incorrectly rendered as black in dark mode, while it should be white.
While the app, when run in bright mode (selected by the ios settings), is rendered correctly,
when dark mode is enabled, text is invisible.
In order to reproduce the problem, in the simulator enable the dark mode from the developer settings of the simulator (iOS 13.3 tested).

**Target Platform: iOS**
**Target OS version/browser: iOS 13.3 **
**Devices: iPhone 11Max (Simulator), Dark mode enabled **

## Logs

```
```

```
$flutter analyze
Analyzing testapp...
No issues found! (ran in 2.2s)

```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale it)
    • Flutter version 1.12.13+hotfix.5 at /Users/andrea/Downloads/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andrea/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/andrea/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.3

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • iPhone di Andrea  • b2d46b5c5c0fc643cee1d68900c98493c96c1fea • ios • iOS 13.3
    • iPhone 11 Pro Max • 09A9F5B2-3BA2-4B84-AAF1-902ABF57466E     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
```

**Comment by eopeter** [comment] 2020-01-23 04:02
any update on this?

**Comment by LongCatIsLooong** [comment] 2020-03-20 18:34
Code to reproduce:
```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(CupertinoStoreApp());

class CupertinoStoreApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: CupertinoStoreHomePage(),
    );
  }
}

class CupertinoStoreHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: const Text('Cupertino Store'),
      ),
      child:  SafeArea(child: Text("Here text is expected to be white")),
    );
  }
}

```

**Comment by alexbhandari** [comment] 2020-04-10 02:16
looks like this is in the pipeline to be looked at. In the meantime, however, are there any workarounds? Is there a property I can override in the dark mode theme to get colors to render correctly?

**Comment by TooMuchRAM** [comment] 2020-04-29 14:52
Setting the TextStyle on each Text widget like this seems to be working:
`Text("[text]", style: CupertinoTheme.of(context).textTheme.textStyle)`
This is however far from an ideal solution, as it has to be set on every Text object.

**Comment by being-yash-t** [comment] 2020-06-08 09:39
It looks like setting the app theme manually to dark does  fix the problem but the app will always stay is darkmode
```      theme: CupertinoThemeData(brightness: Brightness.dark),```

**Comment by cpboyd** [comment] 2020-07-19 23:52
You can force the color to the appropriate value by `CupertinoDynamicColor.resolve(CupertinoColors.label, context)`, but it seems like text styles like `CupertinoTheme.of(context).textTheme.navTitleTextStyle` may not automatically adapt their colors... Which leads to `CupertinoNavigationBar` and such displaying black text in dark mode.

**Comment by VladyslavBondarenko** [comment] 2020-07-30 11:56
Persists with current master `1.21.0-6.0.pre.117`

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.117 at /Users/nevercode/dev/flutter
    • Framework revision 7ec2d360bc (2 hours ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by cielo** [comment] 2020-11-11 06:40
This problem is still present today, as of flutter 1.22.3.

```
flutter --version          
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (12 days ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3
```

**Comment by guidezpl** [comment] 2020-11-20 12:21
@LongCatIsLooong I'd like to fix this (my case is for navigation bar titles). Should we do this for Cupertino widgets individually in the style of https://github.com/flutter/flutter/blame/1aafb3a8b9b0c36241c5f5b34ee914770f015818/packages/flutter/lib/src/cupertino/nav_bar.dart#L1331? Or is there a way to more broadly apply text style light/dark defaults in the way Material currently does it?

**Comment by LongCatIsLooong** [comment] 2020-11-20 19:52
@guidezpl If I remember correctly this happens because `CupertinoApp` doesn't have a `MediaQuery` so it can't resolve the text color? What I had in mind was to let `WidgetsApp.textStyle` take a lazy builder (of type `TextStyle Function(BuildContext) `), and defer the color resolution to `WidgetsApp.build`, but that's a breaking change so I was a bit reluctant.

**Comment by guidezpl** [comment] 2020-11-23 15:18
I'm using a `MaterialApp` rather than a `CupertinoApp` to support both platforms.  I don't know if that's an anti-pattern. I'm relying on the implicitly generated `CupertinoTextThemeData`, which seems incorrect. I'll file a separate issue about that.

**Comment by h65wang** [comment] 2021-01-13 22:59
Wrapping another MaterialApp widget on top of CupertinoApp would appear to solve this problem for now:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: CupertinoApp(
        home: MyHomePage(),
      ),
    );
  }
}
```

This way, all default Text will render correctly in both light mode and dark mode.

However, there is a side-effect for putting MaterialApp as the root widget: it will make CupertinoAlertDialog always render in light mode.

**Comment by h65wang** [comment] 2021-01-13 23:31
Placing a `DefaultTextStyle` widget somewhere near the top of the widget tree is also a good workaround. Just remember it needs to be one level lower than the CupertinoApp, or else it cannot find the inherited theme using its build context.

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: Builder(
        builder: (BuildContext context) {
          return DefaultTextStyle(
            style: CupertinoTheme.of(context).textTheme.textStyle,
            child: MyHomePage(),
          );
        },
      ),
    );
  }
}
```

**Comment by SimonHausdorf** [comment] 2021-01-31 17:55
> Aren't navigation bar components already wrapped in a `DefaultTextStyle` widget and should have the correct text color?

Yes, navigation bar works.
However, the problem still exists with `Flutter 1.25.0-8.3.pre • channel beta`

**Comment by SirusCodes** [comment] 2021-03-12 07:07
Does this problem still exists??

**Comment by henry2man** [comment] 2021-03-12 13:27
> Does this problem still exists??

Yes, I can confirm this problem still exists with Flutter 2 stable and iOS 14.4 (I had to apply the workaround)

**Comment by mleonhard** [comment] 2021-04-21 02:45
This bug is still happening in the latest stable Flutter, version 2.0.5.

I wasted time debugging this issue.  And now my project's code is more complicated because of the additional unnecessary `Builder`.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] VS Code (version 1.49.2)
[✓] Connected device (2 available)

• No issues found!
```

Bug demo:
```dart
import 'package:flutter/cupertino.dart'
    show
        Center,
        CupertinoPageScaffold,
        CupertinoApp,
        CupertinoPage,
        CupertinoThemeData,
        Text;
import 'package:flutter/widgets.dart' show runApp, Navigator;

void main() {
  runApp(
    CupertinoApp(
      theme: CupertinoThemeData(),
      title: 'App1',
      home: Navigator(
        pages: [
          CupertinoPage(
              title: 'Home',
              child: CupertinoPageScaffold(child: Center(child: Text('Home'))))
        ],
        onPopPage: (route, result) => true,
      ),
    ),
  );
}
```
![Screenshot_1618971156](https://user-images.githubusercontent.com/520739/115486903-6f90cd00-a20c-11eb-8899-7861e4b43757.png)
![Screenshot_1618971115](https://user-images.githubusercontent.com/520739/115486906-71f32700-a20c-11eb-9c39-4884b7d453c6.png)

**Comment by savadodesigns** [comment] 2021-04-21 19:43
Same problem here, flutter 2.12

**Comment by TahaTesser** [comment] 2021-10-04 09:39
<details> 
<summary>flutter doctor -v</summary> 
	
```console
<details> 
[✓] Flutter (Channel master, 2.6.0-12.0.pre.185, on macOS 12.0 21A5534d darwin-x64, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.185 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 91dd3276fd (2 days ago), 2021-10-02 10:18:03 -0700
    • Engine revision 6f4143e800
    • Dart version 2.15.0 (build 2.15.0-172.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 15.0 19A346
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 12.0 21A5534d darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 94.0.4606.61
    ! Error: Taha’s iPhone is busy: Making the device ready for development. Xcode will continue when Taha’s iPhone is finished. (code -10)

• No issues found!
```
	 
</details>

**Comment by gamelaster** [comment] 2021-12-12 07:17
It's almost 2 years after bringing up this issue, and it's still not working correctly on `Flutter 2.8.0-3.2.pre`.

**Comment by gamelaster** [comment] 2021-12-12 11:09
I probably found where is the issue. The _effectiveColor is wrong, because "brightness" setting, which is get from Theme or MediaQuery, returns light, because Theme is null, and at that time when defaultTextStyle is initialized in CupertinoApp, the MediaQuery is not existing, thus it returns by default `light`. Sadly, I couldn't figure out, why is MediaQuery not initialized, and I couldn't find out how MaterialApp handles this, and since this is my first time digging into the internals of Flutter, I have no idea how to fix this ☹️

**Comment by cpboyd** [comment] 2021-12-12 20:13
@gamelaster After looking into all the Cupertino widgets in detail, the real issue is that many simply don't properly resolve `CupertinoDynamicColor` (and thus, if passed a `CupertinoDynamicColor` don't display the correct version in dark mode)

I feel like a real solution would be to go through and fix all of these one-off resolution issue, but that's kind of a nightmarish headache from the standpoint of updating all the tests... which is why I haven't worked on a PR.

**Comment by gamelaster** [comment] 2021-12-13 05:53
@cpboyd Hi and thank you for your fast reply 😊 
Interesting thing is, that I didn't found any other widgets, which had issues with brightness settings. Also, the Text is not Cupertino widget, so how we would fix color resolving here?

I tested passing CupertinoColors, without using CupertinoDynamicColors.resolve, as you said, it always returns a default color.
But this same behavior is also in Material, isn't?

Thanks

**Comment by gamelaster** [comment] 2021-12-15 05:33
Hi @mleonhard did you tried my workaround? Does it solve some issues, or it still happens?

Anyway, it still seems like Flutter team doesn't maintain the Cupertino (almost) at all, also the documentation for Cupertino is very weak ☹️

**Comment by Princewil** [comment] 2022-01-29 05:00
For now what I did was to write a code that checks if my app is on dark mode. If it is, it changes the text color to white, else it uses the default text color. I did this by using a custom font from Google font package, then  imputing "the check" on the color parameters of the font and then finally inputted it on my materialApp textTheme parameter. (Of course I used riverpod for the state management)


I can show a sample if you want.

**Comment by samruncoach** [comment] 2022-02-23 06:14
> I found proper workaround, which should fix all the problems (since this might happen also in other color configurations):
> 
> ```dart
> return MediaQuery.fromWindow(
>   child: CupertinoApp(
>     useInheritedMediaQuery: true,
>     home: // ...
>   )
> );
> ```
> 
> Why this workaround works? I find out, that in time, when `defaultTextStyle` in CupertinoApp is initialized, MediaQuery is not initialized, thus it will return (by default) Light Mode. I would like to create PR, although, this is my first time digging into the internals and I doubt my solution will be the correct. Anyway, this workaround is quite elegant, so I will use it until this will be fixed.

This is a better solution than any other specified above. Please do raise a PR to know more about this change from the flutter devs.

**Comment by ivirtex** [comment] 2022-03-05 18:25
Any progress on this?

**Comment by gamelaster** [comment] 2022-03-05 19:51
@ivirtex as far as I know, no ☹️

**Comment by justinmc** [comment] 2022-12-21 18:59
Usually I handle this sort of problem by manually setting the brightness on the CupertinoThemeData using WidgetsBindingObserver.  Then built-in widgets seem to pick up the correct light/dark mode stylings, and I can also query the theme for the brightness myself like `CupertinoTheme.of(context).brightness`.  Example below.

Does that fix everyone's main visual problem here, or am I missing more details?

I definitely understand that needing to set that up manually is not ideal, and the fact that it is different from Material is a mistake in the API design.  Any real solution to this issue should make Cupertino behave exactly like Material in this regard, and my workaround here would be redundant.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(const CupertinoHomePage());

class CupertinoHomePage extends StatefulWidget {
  const CupertinoHomePage({
    super.key,
  });

  @override
  State<CupertinoHomePage> createState() => _CupertinoHomePageState();
}

class _CupertinoHomePageState extends State<CupertinoHomePage> with WidgetsBindingObserver {
  Brightness _brightness = Brightness.light;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _brightness = WidgetsBinding.instance.window.platformBrightness;
  }

  @override
  void didChangePlatformBrightness() {
    if (mounted) {
      setState(() {
        _brightness = WidgetsBinding.instance.window.platformBrightness;
      });
    }

    super.didChangePlatformBrightness();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: CupertinoThemeData(
        brightness: _brightness,
      ),
      home: const CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(
          middle: Text('Cupertino App'),
        ),
        child: SafeArea(
          child: Text('Here text is expected to be white in dark mode, black in light mode.'),
        ),
      ),
    );
  }
}
```

</details>

**Closed** 2023-02-27 18:36 UTC
Labels: framework, f: cupertino, has reproducible steps, found in release: 1.21, found in release: 2.6
