### ISSUE TITLE
image_picker bug stretching the image

### ISSUE THREAD

**Issue by jrmarkham** [flutter/flutter#39415] opened 2019-08-28 16:44 UTC
Between image_picker versions 0.5.4+3 and 0.6.1+3, a frequent bug has caused images pulled from the gallery to be stretched. It appears that the aspect ratio is inverted. When I switched back to 0.5.4+3 the problem went away and it is fine on the modern version. This appears to be happened on iOS only but I didn't text this exhaustively.

I'd also like to add that this plugin is very helpful -- Thanks.

**Comment by BondarenkoStas** [comment] 2019-09-04 14:39
Duplicate of #38882

**Comment by BondarenkoStas** [comment] 2019-09-04 14:41
@jrmarkham I think it's safe to close the issue as the same problem was mentioned in the issue above. Please comment if you disagree.

**Closed by BondarenkoStas** 2019-09-04 14:41 UTC
Labels: p: image_picker

**Comment by jrmarkham** [comment] 2019-09-04 17:25
Yes, it is a duplicate; sorry, I did look for it prior to posting. I must have missed it. Thanks for all your Flutter work; I absolutely love this framework.
