### ISSUE TITLE
`text_input.dart': Failed assertion: line 710 pos 12: 'attached': is not true` when changing InputDecoration of a previously active Textfield

### ISSUE THREAD

**Issue by hardik9996** [flutter/flutter#40755] opened 2019-09-18 13:17 UTC
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building InputDecorator(decoration: InputDecoration(labelText: "عنوان بريد الكتروني", helperText: "", hintMaxLines: "1", errorStyle: "TextStyle(inherit: true, color: MaterialColor(primary value: Color(0xfff44336)), family: AdobeArabicBold, height: 1.0x)", prefixIcon: Icon(IconData(U+0E853), color: Color(0xffffffff)), focusedBorder: UnderlineInputBorder(), enabledBorder: UnderlineInputBorder(), alignLabelWithHint: false), isFocused: false, isEmpty: false, dependencies: [_LocalizationsScope-[GlobalKey#2faa2], _InheritedTheme, Directionality, MediaQuery], state: _InputDecoratorState#ffa1a(tickers: tracking 2 tickers)):
'package:flutter/src/services/text_input.dart': Failed assertion: line 703 pos 12: 'attached': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  TextFormField file:///D:/AndroidWorkspace/ComoRestuarantApp/como_restaurant/lib/login/login_ui.dart:97:25
When the exception was thrown, this was the stack: 
#2      TextInputConnection.setStyle (package:flutter/src/services/text_input.dart:703:12)
#3      EditableTextState.didUpdateWidget (package:flutter/src/widgets/editable_text.dart:1100:29)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4096:58)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:2886:15)
#6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5136:14)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by hardik9996** [comment] 2019-09-18 13:18
My Code For Form
```
Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      body: Stack(
        fit: StackFit.expand,
        children: <Widget>[
          Image(
            image: AssetImage(StringConstant.LoginPageBGPath),
            fit: BoxFit.cover,
            color: Colors.black54,
            colorBlendMode: BlendMode.darken,
          ),
          ListView(
            shrinkWrap: true,
            children: <Widget>[
              Directionality(
                child: Container(
                  padding: EdgeInsets.only(top: 30),
                  child: _buildLanguageWidget(_index),
                  alignment: Alignment.topCenter,
                ),
                textDirection: TextDirection.ltr,
              ),
              SizedBox(height: 60.0),
              Center(
                child: Text(AppLocalizations.of(context).lbSignIn,
                    style: TextStyle(
                        color: Colors.white,
                        fontFamily: _index == 0
                            ? "MyriadProSemibold"
                            : "AdobeArabicBold",
                        fontSize: 35.0),
                    strutStyle: StrutStyle(
                      forceStrutHeight: true,
                    )),
              ),
              Form(
                key: _loginFormKey,
                child: Theme(
                  data: ThemeData(
                      brightness: Brightness.dark,
                      primarySwatch: Colors.orange,
                      inputDecorationTheme: InputDecorationTheme(
                          labelStyle: TextStyle(
                        color: Colors.white,
                      ))),
                  child: Container(
                    margin: EdgeInsets.only(top: 30.0, right: 30.0, left: 30.0),
                    child: Column(
                      children: <Widget>[
                        TextFormField(
                          focusNode: _emailNode,
                          controller: emailController,
                          cursorColor: Colors.white,
                          decoration: InputDecoration(
                            prefixIcon: Icon(
                              Icons.account_circle,
                              color: Colors.white,
                            ),
                            labelText:
                                AppLocalizations.of(context).emailAddress,
                            helperText: "",
                            labelStyle: TextStyle(
                              color: Colors.white,
                              height: 1,
                              fontFamily: _index == 0
                                  ? "MyriadProSemibold"
                                  : "AdobeArabicBold",
                            ),
                            errorStyle: TextStyle(
                              color: Colors.red,
                              height: 1,
                              fontFamily: _index == 0
                                  ? "MyriadProSemibold"
                                  : "AdobeArabicBold",
                            ),
                            hintStyle: TextStyle(
                              color: Colors.white,
                              height: 1,
                              fontFamily: _index == 0
                                  ? "MyriadProSemibold"
                                  : "AdobeArabicBold",
                            ),
                            helperStyle: TextStyle(
                              color: Colors.white,
                              height: 1,
                              fontFamily: _index == 0
                                  ? "MyriadProSemibold"
                                  : "AdobeArabicBold",
                            ),
                            enabledBorder: UnderlineInputBorder(
                                borderSide: BorderSide(color: Colors.white)),
                            focusedBorder: UnderlineInputBorder(
                              borderSide: BorderSide(color: Colors.orange),
                            ),
                          ),
                          // ignore: missing_return
                          validator: (value) {
                            if (value.isEmpty) {
                              return AppLocalizations.of(context)
                                  .errorEnterMail;
                            } else if (!value.contains("@")) {
                              return AppLocalizations.of(context)
                                  .errorInvalidMail;
                            } else
                              return "";
                          },

                          keyboardType: TextInputType.emailAddress,
                          textInputAction: TextInputAction.next,
                          onFieldSubmitted: (value) {
                            _fieldFocusChange(
                                context, _emailNode, _passwordNode);
                          },
                        ),
                        TextFormField(
                          focusNode: _passwordNode,
                          controller: pwdController,
                          cursorColor: Colors.orange,
                          decoration: InputDecoration(
                              helperText: "",
                              prefixIcon: Icon(
                                Icons.lock_open,
                                color: Colors.white,
                              ),
                              suffixIcon: Icon(
                                Icons.remove_red_eye,
                                color: Colors.white,
                              ),
                              labelText: AppLocalizations.of(context).password,
                              labelStyle: TextStyle(
                                color: Colors.white,
                                height: 1,
                                fontFamily: _index == 0
                                    ? "MyriadProSemibold"
                                    : "AdobeArabicBold",
                              ),
                              errorStyle: TextStyle(
                                color: Colors.red,
                                height: 1,
                                fontFamily: _index == 0
                                    ? "MyriadProSemibold"
                                    : "AdobeArabicBold",
                              ),
                              hintStyle: TextStyle(
                                color: Colors.white,
                                height: 1,
                                fontFamily: _index == 0
                                    ? "MyriadProSemibold"
                                    : "AdobeArabicBold",
                              ),
                              helperStyle: TextStyle(
                                color: Colors.white,
                                height: 1,
                                fontFamily: _index == 0
                                    ? "MyriadProSemibold"
                                    : "AdobeArabicBold",
                              ),
                              enabledBorder: UnderlineInputBorder(
                                  borderSide: BorderSide(color: Colors.white)),
                              focusedBorder: UnderlineInputBorder(
                                borderSide: BorderSide(color: Colors.orange),
                              )),
                          // ignore: missing_return
                          validator: (value) {
                            if (value.isEmpty) {
                              return AppLocalizations.of(context).errorEnterPwd;
                            } else
                              return "";
                          },

                          keyboardType: TextInputType.text,
                          obscureText: true,
                        ),
                        Padding(
                          padding: const EdgeInsets.all(20.0),
                        ),
                        Builder(
                          builder: (context) => Center(
                            child: SizedBox(
                              width: double.maxFinite,
                              child: RaisedButton(
                                color: Colors.orange,
                                textColor: Colors.white,
                                child: Text(
                                  AppLocalizations.of(context).login,
                                  style: TextStyle(
                                    fontSize: 17,
                                  ),
                                  strutStyle: StrutStyle(
                                    forceStrutHeight: true,
                                  ),
                                ),
                                onPressed: () {
                                  if (_loginFormKey.currentState.validate()) {
                                    showSnakeBar(context);
                                    Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                MyHomePage()));
                                  }
                                },
                                padding: EdgeInsets.all(10.0),
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(5.0)),
                              ),
                            ),
                          ),
                        ),
                        Padding(
                          padding: EdgeInsets.only(top: 22.0),
                        ),
                        Text(
                          AppLocalizations.of(context).forgotPassword,
                          style: TextStyle(color: Colors.white, fontSize: 16.0),
                        ),
                        Padding(
                          padding: EdgeInsets.only(top: 22.0),
                        ),
                        FlatButton(
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: <Widget>[
                                Text(AppLocalizations.of(context).lbSignUpStr,
                                    style: TextStyle(
                                        color: Colors.white, fontSize: 16.0),
                                    strutStyle: StrutStyle(
                                      forceStrutHeight: true,
                                    )),
                                Text(AppLocalizations.of(context).signUp,
                                    style: TextStyle(
                                        color: Colors.orange, fontSize: 16.0),
                                    strutStyle: StrutStyle(
                                      forceStrutHeight: true,
                                    )),
                              ],
                            ),
                            onPressed: () => Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => SignUpPage())))
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
```

**Comment by escamoteur** [comment] 2019-09-18 13:24
Could you please add your output of flutter doctor?

**Comment by hardik9996** [comment] 2019-09-18 13:30
E:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel master, v1.10.3-pre.46, on Microsoft Windows [Version 10.0.18362.295], locale en-IN)
    • Flutter version 1.10.3-pre.46 at E:\flutter
    • Framework revision 3331c37804 (2 days ago), 2019-09-16 05:02:41 -0400
    • Engine revision 79ecdbf220
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d0052c1b31)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi Note 6 Pro • ff4cd888 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
Process finished with exit code 0
@escamoteur ``

**Comment by benjlin** [comment] 2019-09-27 23:09
I have made an example project to show off the error, its not confined to changing the local on the text edit. 

when a SetState is modifying the values of the non active TextField when more than one text field has previously been activated. 

In the below demo, if you toggle the switch without inserting any values both TextField are fine, if you put a value in one TextField then switch it is also fine, tap into the second field and the error will occur.

in text_input.dart we have: 
`/// Whether this connection is currently interacting with the text input control.
  bool get attached => _clientHandler._currentConnection == this;`

which naturally resolves to false since we are indeed not interacting with the current text input controller. so when the widget tree invokes the SetState the assert naturally fails. 

I don't understand what the assert is trying to achieve here, since you may want to set the state on any instance of a text_input not just the currently active one. updating the state on multiple inputs did perviously work so is this some kind of regression? 

` /// Send text styling information.
  ///
  /// This information is used by the Flutter Web Engine to change the style
  /// of the hidden native input's content. Hence, the content size will match
  /// to the size of the editable widget's content.
  void setStyle({
    @required String fontFamily,
    @required double fontSize,
    @required FontWeight fontWeight,
    @required TextDirection textDirection,
    @required TextAlign textAlign,
  }) {
    assert(attached);

    SystemChannels.textInput.invokeMethod<void>(
      'TextInput.setStyle',
      <String, dynamic>{
        'fontFamily': fontFamily,
        'fontSize': fontSize,
        'fontWeightIndex': fontWeight?.index,
        'textAlignIndex': textAlign.index,
        'textDirectionIndex': textDirection.index,
      },
    );
  }`



`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Color textCol = Colors.grey;

  bool theam = false;

  void _switchTheam(state) {
    setState(() {
      theam = state;
      if (!state) {
        textCol = Colors.grey;
      } else {
        textCol = Colors.red;
      }
    });
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Builder(
        builder: (context) => Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new TextField(
              decoration: InputDecoration(
                border: InputBorder.none,
                hintText: '',
                hintStyle: TextStyle(
                  color: textCol,
                ),
                labelText: 'Input 1',
                labelStyle: TextStyle(
                  color: textCol,
                ),
              ),
              textAlign: TextAlign.center,
              style: TextStyle(
                color: textCol,
              ),
            ),

            new TextField(
              decoration: InputDecoration(
                border: InputBorder.none,
                hintText: '',
                hintStyle: TextStyle(
                  color: textCol,
                ),
                labelText: 'Input 2',
                labelStyle: TextStyle(
                  color: textCol,
                ),
              ),
              textAlign: TextAlign.center,
              style: TextStyle(
                color: textCol,
              ),
            ),
            new Switch(
              value: theam,
              onChanged: (state) => _switchTheam(state),
            ),
          ],
        ),
      ),
    );
  }
}
`

**Comment by escamoteur** [comment] 2019-09-30 21:29
@benjlin did you test on web or on Android/iOS? 
I was a bit confused because in you code snipped above in the comment they talk about flutter web

**Comment by escamoteur** [comment] 2019-09-30 21:35
Ok, forget that latest, I could reproduce on Android on latest master `Channel master, v1.10.7-pre.95, on Microsoft Windows `

**Comment by benjlin** [comment] 2019-10-01 04:28
yeah sorry for the lack of clarity there, i was testing with Android on the latest master on macOS, i was trying to point out that it looks like web code changes might have caused this

**Comment by BasedMusa** [comment] 2019-10-03 08:48
Any workarounds for this? I'm on `1`. Should I downgrade? I have to release my app within this week, and this is the last bug. I've already created a custom widget from the TextField widget.

**Comment by escamoteur** [comment] 2019-10-03 09:28
Would the older version give you other problems? If you release for iOS you will have problems with iOS 13.

**Comment by BasedMusa** [comment] 2019-10-03 11:01
I am downloading iOS 11 Simulator runtime for testing, but this issue is also on Android (Tested on physical device, Xiaomi Redmi 6).

**Comment by BasedMusa** [comment] 2019-10-05 21:03
Tested and confirmed that this also an issue on iOS 11.1. Please how soon can we expect a fix for this?

**Comment by BasedMusa** [comment] 2019-10-17 13:30
@escamoteur @Hixie Any update?

**Comment by gdomingues** [comment] 2019-10-22 19:41
In order to temporarily circumvent this bug I commented [this line](https://github.com/flutter/flutter/blob/f6d3dbd62002b85d5c43a71f6e79be121076d46c/packages/flutter/lib/src/services/text_input.dart#L710) and generated a local version of Flutter.

**Comment by CiceroTecchio** [comment] 2019-10-23 12:28
> In order to temporarily circumvent this bug I commented [this line](https://github.com/flutter/flutter/blob/f6d3dbd62002b85d5c43a71f6e79be121076d46c/packages/flutter/lib/src/services/text_input.dart#L710) and generated a local version of Flutter.

That's works. Thanks!

**Comment by BasedMusa** [comment] 2019-10-23 14:05
> In order to temporarily circumvent this bug I commented [this line](https://github.com/flutter/flutter/blob/f6d3dbd62002b85d5c43a71f6e79be121076d46c/packages/flutter/lib/src/services/text_input.dart#L710) and generated a local version of Flutter.

This could be a potential solution.

**Comment by BasedMusa** [comment] 2019-10-29 13:22
@gdomingues How do I generate a local version of Flutter?

**Comment by escamoteur** [comment] 2019-10-30 17:47
@BasedMusa best to fork the flutter repo and clone it to your computer.

**Comment by yasinarik** [comment] 2019-11-05 20:17
> In order to temporarily circumvent this bug I commented [this line](https://github.com/flutter/flutter/blob/f6d3dbd62002b85d5c43a71f6e79be121076d46c/packages/flutter/lib/src/services/text_input.dart#L710) and generated a local version of Flutter.

Yes. Commenting out that line worked for me too!

**Comment by votruk** [comment] 2019-11-08 13:35
I have the same problem. Any information when a fix would be ready?

**Comment by huextrat** [comment] 2019-12-12 09:39
Getting exactly the same error on my side with the latest stable version ` 1.12.13+hotfix.5` any news ?

**Comment by GyuriMajercsik** [comment] 2019-12-13 14:40
Same issue here on 1.12.13+hotfix.5 • channel stable •

**Comment by gdomingues** [comment] 2019-12-13 15:36
Please **upvote the first comment**, else this issue won't be prioritized accordingly.

The number of comments saying "same issue" and similars probably aren't considered in the prioritization.

**Comment by SunLongbri** [comment] 2019-12-19 08:22
Same issue on : 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.3-pre.78, on Mac OS X 10.15.1 19B88, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

**Comment by SunLongbri** [comment] 2019-12-19 08:24
我的MaterialApp的local属性是这样设置的     locale:dataProvider.isLocal,但是在切换的时候，语言切换过来了，但是报了这个错误:TextInput 'attached':is not true.下次再切换语言，就直接红屏报错，错误原因:framework： 'child == _child': is not true. 我该咋办呀！

**Comment by enzobonggio** [comment] 2019-12-26 01:14
Hi the problem pop ups when I change the style while the element is not selected, is there any other way to make this work without commenting the line? 

Maybe the approach that I'm going is wrong

**Comment by chunhtai** [comment] 2019-12-28 02:34
setStyle is setting the style of 'current active' one. the assert is there to make sure the current active one is the one of this editabletext. Comment out the line will create potential issue. for example if you have two textfields: textfield1 and textfield2.
textfield2 is active, and textfield1 change its style while textfield2 stays the same.
The textfield1 will try to setstyle for the 'current active' textinput which is the text input of textfield2. This will currently throw an exception because of the assert.

I am working on a fix, stay tune.

**Closed** 2020-01-03 00:19 UTC
Labels: a: error message, a: text input, f: material design, framework, severe: crash, severe: regression

**Comment by miguelpruivo** [comment] 2020-01-06 19:17
@chunhtai your fix on latest master doesn't seem to fix this, however, removing the mentioned `assert` definitely fixes it and everything is smooth as it should. 

Spent all afternoon around this as I have an animation lerping the font size in a list of multiple form fields and with this, it seems impossible to achieve. However, using a local fix on my repo isn't a solution either for me.

This should be reopened.

**Comment by enzobonggio** [comment] 2020-01-06 22:44
@chunhtai It's not happening anymore on master at least for me.

I made a simple example from where I used to have the error

https://gist.github.com/enzobonggio/3c79ba62d3ad02e585a5bbc4ec9f9581

Thanks a lot.

**Comment by chunhtai** [comment] 2020-01-07 00:17
@miguelpruivo 
Can you share your reproducible example? The assert is there to make sure things work correctly. Removing it is risky.

**Comment by koyadovic** [comment] 2020-01-07 11:33
In my case, was that sometimes TextFields were added to widget tree and in some cases not. When dependent variable changed causing that some TextFields come and others gone is when this error was raised. My solution was using the widget Visibility so all this widgets always, being visible or not, are added to the widget tree so the error is gone.

Replacing:
```
if(visible)
TextField(
  controller: passwordController1,
  obscureText: true,
  autofocus: true,
  decoration: InputDecoration(
      contentPadding: EdgeInsets.fromLTRB(20.0, 15.0, 20.0, 15.0),
      hintText: AppTranslations.of(context).text('login_password1'),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(5.0))
  ),
)
```
by:
```
Visible(
  visible: visible,
  child: TextField( ...
)
```

(Sorry for my english ...)

**Comment by miguelpruivo** [comment] 2020-01-07 12:20
@chunhtai my bad, I can confirm that indeed it's working on `master` HEAD. Thank you.

**Comment by KLD** [comment] 2020-01-19 07:50
This might work for some. I had a `TextEditingController` for my `TextFormField`. Setting a text value in `TextEditingController` prevented this assert for failing. 

But this create another problem of not having empty fields.

**Comment by devibrahimkarahan** [comment] 2020-01-20 14:12
> @chunhtai It's not happening anymore on master at least for me.
> 
> I made a simple example from where I used to have the error
> 
> https://gist.github.com/enzobonggio/3c79ba62d3ad02e585a5bbc4ec9f9581
> 
> Thanks a lot.

This example throws an error when u follow these steps:

1- Click first textfield
2- Click second textfield
3- Click the button
(No problem when we remove style parameters)
Console >

> The following assertion was thrown building InputDecorator(decoration: InputDecoration(hintMaxLines: "1", alignLabelWithHint: false), baseStyle: TextStyle(inherit: true, color: Color(0xff000000)), isFocused: false, isEmpty: true, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#69b00], Directionality, _InheritedTheme], state: _InputDecoratorState#22e11(tickers: tracking 2 tickers)):
> 'package:flutter/src/services/text_input.dart': Failed assertion: line 745 pos 12: 'attached': is not true.
> 
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=BUG.md
> 
> The relevant error-causing widget was: 
>   TextFormField file:///C:/Users/Karahan/Desktop/workspace/testttt/lib/main.dart:39:11
> When the exception was thrown, this was the stack: 
> #2      TextInputConnection.setStyle (package:flutter/src/services/text_input.dart:745:12)
> #3      EditableTextState.didUpdateWidget (package:flutter/src/widgets/editable_text.dart:1162:29)
> #4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
> #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
> #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
> ...
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> 
> ════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
> A RenderFlex overflowed by 99753 pixels on the bottom.
> The relevant error-causing widget was: 
>   Column file:///C:/Users/Karahan/Desktop/workspace/testttt/lib/main.dart:37:13
> ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by eslam-elswesy** [comment] 2020-01-26 23:01
i have the same error

**Comment by teejayhh** [comment] 2020-01-28 03:35
I have exactly the same issue, on the current and up to date master branch.

**Comment by soteras** [comment] 2020-01-28 16:40
I have the same error. I tried version v1.12.13+hotfix.7 but it isn't fixed yet, what version this fix https://github.com/flutter/flutter/pull/47904 will released?

**Comment by chunhtai** [comment] 2020-01-28 17:36
v1.13.6 it is not release to stable yet

**Comment by cesarnorena** [comment] 2020-01-31 21:32
@chunhtai your fix worked for me, for now I just added the extra condition while we get the new Flutter's version, thanks!

**Comment by Ahmedmedhat187** [comment] 2020-02-06 20:32
@chunhtai  Thanks a lot, your solution solved my problem

**Comment by zigszigsdk** [comment] 2020-02-17 12:17
To make it perfectly clear for anyone else who's having this problem as I also did:
What you need to do is to use the source code installation -not the prepackaged bundle-, and check out v1.13.6 or later - not the stable branch. (find a wysiwyg/gui git tool if you're not too comfortable with git) Check out the latest numbered release (currently 1.15.3)

The fix will of course be released to stable at some later point.

**Comment by ajeethhacki** [comment] 2020-03-16 13:10
@chunhtai Thanks a lot for your fix, But please release the strable flutter v1.13.6 as soon as possible

**Comment by fredytellor** [comment] 2020-03-17 15:28
i had the same issue but then i runned the app on release mode and didnt happen
