### ISSUE TITLE
Flutter web - mouse pointer appears as unavailable when hovering PopupMenuButton

### ISSUE THREAD

**Issue by topex-psy** [flutter/flutter#97938] opened 2022-02-07 08:02 UTC
## Steps to Reproduce

1. Hover mouse pointer above `PopupMenuButton`
2. When clicked, functions as expected, but the pointer icon appears wrong
3. I've tried using `MouseRegion` widget but no avail

![IMG_20220207_145727](https://user-images.githubusercontent.com/14989865/152747886-dd9b0638-e3fc-4b97-95f7-95eb2d53d72c.jpg)

**Expected results:** 
Appear as pointer (hand)

**Actual results:** 
Appear as unavailable

<details>
<summary>Code sample</summary>

```dart
Material(
  color: isActive ? APP_UI_COLOR_LIGHT : Colors.transparent,
  borderRadius: BorderRadius.circular(8),
  child: InkWell(
    borderRadius: BorderRadius.circular(8),
    onTap: onTap,
    onLongPress: onLongTap,
    child: Padding(
      padding: const EdgeInsets.all(8.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            flex: flexCard,
            child: Stack(
              alignment: Alignment.topRight,
              children: [
                card ?? SizedBox(width: cardSize, height: cardSize, child: Card(
                  elevation: 10,
                  shadowColor: Colors.grey[200],
                  shape: cardShape ?? RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  clipBehavior: Clip.antiAlias,
                  child: Image(image: a.imageProvider(item.photo), fit: BoxFit.cover,),
                )),
                item.total == null ? Container() : MyNumberBadge(item.total, offsetX: 10, offsetY: -10,),
              ],
            ),
          ),
          SizedBox(width: rowGap,),
          Expanded(
            flex: flexText,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(item.title, style: TextStyle(fontSize: titleSize, fontWeight: FontWeight.w700),),
                item.note == null ? SizedBox(height: textGap,) : Padding(padding: EdgeInsets.symmetric(vertical: textGap), child: Text(item.note!, style: TextStyle(fontSize: subtitleSize),),),
                Text(item.description ?? "", style: TextStyle(fontSize: captionSize, color: APP_UI_COLOR_ACCENT),),
              ],
            ),
          ),
          actions == null ? const SizedBox() : Padding(
            padding: EdgeInsets.only(left: rowGap),
            child: actions!,
          ),
          !showCaret ? const SizedBox() : MouseRegion(
            cursor: SystemMouseCursors.click,
            child: caretMenus.isEmpty ? Padding(
              padding: EdgeInsets.only(left: rowGap),
              child: Icon(caretIcon, color: caretColor, size: caretSize,),
            ) : PopupMenuButton( // here's the PopupMenuButton
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(APP_UI_CARD_RADIUS)),
              child: IconButton(icon: Icon(caretIcon), color: caretColor, iconSize: caretSize, onPressed: null,),
              tooltip: "Class menu",
              itemBuilder: (context) => caretMenus.map<PopupMenuItem>((menu) {
                return PopupMenuItem<MenuModel>(
                  child: Text(menu.label, style: const TextStyle(color: APP_UI_TEXT_DEFAULT, fontWeight: FontWeight.w600, fontSize: 14),),
                  value: menu,
                );
              }).toList(),
              onSelected: (val) {
                final menu = val as MenuModel?;
                menu?.onPressed?.call();
              },
            ),
          ),
        ],
      ),
    ),
  ),
)
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-ID)
    • Flutter version 2.8.1 at F:\Android\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: F:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at F:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.64.0)
    • VS Code at C:\Users\topex\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.69

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2022-02-07 13:39
Hi @topex-psy, Thanks for filing the issue. This is working as intended since your `IconButton.onPressed` is null
 
>  child: IconButton(icon: Icon(caretIcon), color: caretColor, iconSize: caretSize, onPressed: null,),

Closing as this is working as intended, If you disagree fee free to write in the comments and We will reopen it.

Thank you.

**Closed by maheshmnj** 2022-02-07 13:39 UTC
Labels: in triage
