### ISSUE TITLE
flutter needs a print_crash command

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#150] opened 2015-11-09 21:22 UTC
<a href="https://github.com/ppiet"><img src="https://avatars.githubusercontent.com/u/1824302?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ppiet](https://github.com/ppiet)**
_Thursday Aug 27, 2015 at 16:23 GMT_
_Originally opened as https://github.com/flutter/engine/issues/886_

----

_From @eseidelGoogle on June 8, 2015 17:44_

We can just directly crib the one from mojodb.

(Or some other way to help users get symbolicated stack traces out of android!)

@collinjackson @abarth @iansf 

_Copied from original issue: domokit/mojo#205_

**Comment by Hixie** [comment] 2015-12-11 23:18
Maybe flutter logs should automatically notice there was a crash and format it appropriately?

**Comment by sethladd** [comment] 2016-09-14 17:09
Closing for now. Please reopen if we need to.

**Comment by Hixie** [comment] 2016-09-14 17:18
We really should automatically symbolize crashes.

**Comment by Hixie** [comment] 2016-09-14 17:18
...but we can close this as a dupe of https://github.com/flutter/flutter/issues/1016 instead.

**Closed by Hixie** 2016-09-14 17:18 UTC
Labels: affects: dev experience, affects: tools, ⚠ brand new feature
