### ISSUE TITLE
Customize TextSelectionControls

### ISSUE THREAD

**Issue by winterDroid** [flutter/flutter#51598] opened 2020-02-27 22:58 UTC
## Use case

We'd like to modify the `TextSelectionControls` which are shown on text selection in a `TextField` to support custom operations that might be not even text related.

## Proposal

I thought about enhancing `ToolbarOptions` to take a list of `ToolbarOption`s that can be used to
1. build the widget to be shown in the menu
2. have a callback that gets invoked on tap of the widget

There could be a `ToolbarOptions` factory method to support the current default options (paste, cut, copy, selectAll).

**Comment by winterDroid** [comment] 2020-02-27 22:58
Related to PR #49391

**Comment by justinmc** [comment] 2020-03-23 15:54
Closing as a duplicate of https://github.com/flutter/flutter/issues/31412.

Now that we've merged https://github.com/flutter/flutter/pull/49391, I think the codebase is in a much better position to support this feature.  I'm working on the equivalent in iOS right now so it can be supported there as well.  Then hopefully it can be added.

**Closed by justinmc** 2020-03-23 15:54 UTC
Labels: a: text input, framework
