### ISSUE TITLE
Selection handles and actions don't follow scroll (text input)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9222] opened 2017-04-05 18:09 UTC
Open Gallery, open Text Input. Type into "life story" (make it compelling, grab the reader).

Then, highlight some of the text.

Then, scroll up.

Expected: the selection handles and actions should follow the text as it scrolls up.

Actual: the handles and the actions should follow the text, I presume.

![screenshot_20170405-110716 1](https://cloud.githubusercontent.com/assets/5479/24719927/502144de-19f0-11e7-94d0-54fa602c27f9.png)

**Comment by sethladd** [comment] 2017-04-05 18:09
cc @abarth

**Comment by eseidelGoogle** [comment] 2017-04-06 19:29
Seth believes this should block an updated release of the gallery.  The next build is slated to being release verification next week, so we'd need to fix this by then.

**Comment by Hixie** [comment] 2017-04-06 19:38
This is a dupe of https://github.com/flutter/flutter/issues/3861.

**Closed by Hixie** 2017-04-06 19:38 UTC
Labels: customer: gallery, prod: text input
