### ISSUE TITLE
resizeToAvoidBottomInset: false blocks scrolling

### ISSUE THREAD

**Issue by ansolantz** [flutter/flutter#52480] opened 2020-03-12 17:24 UTC
## Steps to Reproduce
When setting resizeToAvoidBottomInset to false and clicking on a textfield, the scrolling does not work. The TextField ends up behind the keyboard and you can not access it.

The following minimal example reproduces it on the latest stable version.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

@override
void initState() {
  SystemChrome.setEnabledSystemUIOverlays([]);
  super.initState();
}  
  void _incrementCounter() {
    setState(() {
    
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ListView(children: [
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.display1,
              ),
               Text(
                'Hello',
              ),
              Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
              Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
              Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
              Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
              Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
                Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
                Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
                Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
                Text(
                'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
              ),
              TextField(),
            ],
          ),
        ]),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by GaspardMerten** [comment] 2020-03-12 20:59
Well that's how it is supposed to work if you look at the documentation, it says that for the resizeToAvoidBottomInset:

  /// If true the [body] and the scaffold's floating widgets should size
  /// themselves to avoid the onscreen keyboard whose height is defined by the
  /// ambient [MediaQuery]'s [MediaQueryData.viewInsets] `bottom` property.
  ///
  /// For example, if there is an onscreen keyboard displayed above the
  /// scaffold, the body can be resized to avoid overlapping the keyboard, which
  /// prevents widgets inside the body from being obscured by the keyboard.
  ///
  /// Defaults to true.

**Comment by GaspardMerten** [comment] 2020-03-12 21:18
If I may propose something that you could play with:

`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  void initState() {
    super.initState();
  }
  void _incrementCounter() {
    setState(() {

      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    SystemChrome.setEnabledSystemUIOverlays([]);
    return  Material(
      child: Container(
        color: Colors.white,
        child: Scaffold(
            body: ListView(
                children: [
                  Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      Text(
                        'You have pushed the button this many times:',
                      ),
                      Text(
                        '$_counter',
                        style: Theme.of(context).textTheme.display1,
                      ),
                      Text(
                        'Hello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      Text(
                        'HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello',
                      ),
                      TextField(),
                    ],
                  ),
                ])
        ),
      ),
    );
  }
}
`

Does it help?

**Comment by ansolantz** [comment] 2020-03-12 22:27
Thanks @GaspardMerten for the quick reply. The default value of true works fine but it seems to reserve some space at the bottom for the Android native navigation bar.

The problem is that we have a fixed hight application and when I set  resizeToAvoidBottomInset to true, it seems to reserve some space at the bottom. That is what I am trying to avoid.

This is what it looks like when I set it to false in our app. I can use the full height but when I click the textfield, the keyboard shows and the TextField is hidden.
![false_value](https://user-images.githubusercontent.com/48385990/76571765-997baa00-64b8-11ea-9a28-f5f03ccab474.png)

On the other hand, if I use the default setting, when the keyboard shows, it scrolls the TextField to the correct place so that works as expected. However, I am not able to use the full height of the Scaffold, not the darker brown border below the Confirm / Cancel buttons.
![false_value](https://user-images.githubusercontent.com/48385990/76571885-e790ad80-64b8-11ea-969b-957405b6151f.png)

**Comment by GaspardMerten** [comment] 2020-03-12 22:52
Then I think that this should do it :D

`MediaQuery(
      data: MediaQueryData(),
      child: <Your scaffold widget with the listview here without setting the parameter it to false>`

**Comment by GaspardMerten** [comment] 2020-03-12 23:05
I was a little upset about not finding the answer so ... I found it after a little while... :D 

`  @override
  Widget build(BuildContext context) {
    double bottomPadding = 0;

    if (MediaQuery.of(context).viewInsets.bottom > 100) {
      // keyboard is open
      bottomPadding = MediaQuery.of(context).viewInsets.bottom;
    }


    return MediaQuery(
      data: MediaQueryData.fromWindow(window).copyWith(viewInsets: EdgeInsets.only(bottom: bottomPadding)),
      child: Builder(
          builder: (context) {
            return `

**Comment by ansolantz** [comment] 2020-03-12 23:26
Thats a nice solution, thanks for taking the time to investigate it, so appreciated.

The side effect I see is that after opening and dismissing the keyboard, the black native navigation bar stays visible on top of the buttons. This is the same problem as I posted in a separate issue.
![Screenshot 2020-03-13 at 00 24 42](https://user-images.githubusercontent.com/48385990/76575983-1448c300-64c1-11ea-8f3b-bf2637dd9847.png)

I can get around this by adding an else to your code above:
```
 if (MediaQuery.of(context).viewInsets.bottom > 100) {
      // keyboard is open
      bottomPadding = MediaQuery.of(context).viewInsets.bottom;
    } else {
      SystemChrome.setEnabledSystemUIOverlays([]);
    }
```

There is a quick flash but this effectively removes the bottom black navigation bar when the keyboard is dismissed. It seems kind of a hack but it does this job.

**Comment by iapicca** [comment] 2020-03-13 08:03
HI @ansolantz 
I'd glad that the issue is solved
thank you @GaspardMerten for stepping in

I feel confident to close the issue,
if you disagree please comment below and I will reopen it
Thank you

**Closed by iapicca** 2020-03-13 08:03 UTC
