### ISSUE TITLE
TapGestureRecognizer in TextSpan is not work, TextSpan next to WidgetSpan.

### ISSUE THREAD

**Issue by CPstudy** [flutter/flutter#55105] opened 2020-04-18 14:15 UTC
![flutter_widgetspan](https://user-images.githubusercontent.com/3941131/79639827-06c1df80-81c9-11ea-82fb-a9427d749625.gif)

```
bool _isChecked = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RichText(
              text: TextSpan(
                children: [
                  WidgetSpan(
                    child: Container(
                      height: 24,
                      color: Colors.transparent,
                      child: Stack(
                        children: <Widget>[
                          Text(
                            'first',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              fontSize: 24,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  TextSpan(
                    text: 'Doughnut',
                    recognizer: TapGestureRecognizer()..onTap = _showDialog,
                    style: TextStyle(
                      fontSize: 36,
                    ),
                  )
                ]
              ),
            ),
            RichText(
              text: TextSpan(
                children: [
                  WidgetSpan(
                    child: Container(
                      width: 50,
                      height: 50,
                      color: Colors.grey,
                      child: Checkbox(
                        value: _isChecked,
                        onChanged: (value){
                          setState(() {
                            _isChecked = value;
                          });
                        },
                      ),
                    ),
                  ),
                  TextSpan(
                    text: 'Ice Cream',
                    recognizer: TapGestureRecognizer()..onTap = _showDialog,
                    style: TextStyle(
                      fontSize: 36,
                    ),
                  )
                ]
              ),
            ),
          ],
        ),
      )
    );
  }

void _showDialog() {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        // return object of type Dialog
        return AlertDialog(
          title: new Text("Click Here"),
          content: new Text("Clicked"),
          actions: <Widget>[
            new FlatButton(
              child: new Text("Close"),
              onPressed: () {
                Navigator.pop(context);
              },
            ),
          ],
        );
      },
    );
  }
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale ko-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.44.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

I can't tap the first letter that TextSpan is next to the WidgetSpan.

Is there any solution?

**Comment by VladyslavBondarenko** [comment] 2020-04-20 11:16
Hi @CPstudy 
I can reproduce it with current stable `v1.12.13+hotfix.9`, but can't with current beta `v1.17.0` or current dev `v1.18.0-dev.5.0`.
Consider to switch to another channel until it's not in stable yet.
Closing since seems to be fixed,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-04-20 11:16 UTC
