### ISSUE TITLE
Allow static file versioning for flutter build web

### ISSUE THREAD

**Issue by jamesgaddum** [flutter/flutter#65785] opened 2020-09-14 19:39 UTC
## Use case

Allow web assets output by `flutter build web` to be versioned in order to facilitate caching of static assets by distribution networks and browsers.

## Proposal

Maybe add a flag to the `flutter build web` cli command (`--build-version`?) so that in our CI/CD pipeline we can specify the build hash. That value would then be inserted into the static file path `href`s in the generated index.html so that when users receive the new index.html from the server their browser and any distribution network infra in between them and the server automatically request the latest version of the static assets.

**Comment by PixelToast** [comment] 2020-09-14 22:43
This seems to be a duplicate of #63500, let me know if that isn't the case and this can be re-opened.

**Closed by PixelToast** 2020-09-14 22:43 UTC
