### ISSUE TITLE
Paragraph/TextPainter.getPositionForOffset reports incorrect multiline positions for web

### ISSUE THREAD

**Issue by stuz5000** [flutter/flutter#44121] opened 2019-11-04 18:47 UTC
## Steps to Reproduce

1. Run the code below app as a flutter web app. 
2. Tap the text. Text character positions are reported correctly for the first line, and incorrectly for the second or later lines of wrapped text.
3. Works incorrectly on web, but correctly on mobile.

```
import 'package:flutter/material.dart';

final loremIpsum =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Container(
            width: 350,
            color: Color.fromARGB(100, 0, 0, 0),
            child: SelectText(),
          ),
        ),
      ),
    );
  }
}

class SelectText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //    return redbox();
    // Set width to max allowed by parent
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      final textPainter = TextPainter(
        text: TextSpan(text: loremIpsum),
        textDirection: TextDirection.ltr,
      );

      final width = constraints.maxWidth;
      textPainter.layout(
        minWidth: 20,
        maxWidth: width,
      );
      final height = textPainter.height;
      GlobalKey key = GlobalKey();

      return Container(
          key: key,
          width: width,
          height: height,
          color: Colors.yellow,
          child: GestureDetector(
            onTapDown: (details) {
              print(
                  "Selection: ${textPainter.getPositionForOffset(details.localPosition)}");
            },
            child: CustomPaint(
              size: Size(width, height), // Parent width, text height
              painter: TextCustomPainter(textPainter),
            ),
          ));
    });
  }
}

class TextCustomPainter extends CustomPainter {
  TextPainter textPainter;

  TextCustomPainter(this.textPainter, {Listenable repaint})
      : super(repaint: repaint);

  @override
  void paint(Canvas canvas, Size size) {
    textPainter.paint(canvas, Offset(0, 0));
  }

  @override
  bool shouldRepaint(CustomPainter old) {
    return false;
  }
}
```

**Target Platform:** Web
**Target OS version/browser:** Ubuntu 18 LTS
**Devices:** ChromeOS

## Logs

```
Performing hot restart...
Reloaded application in 1,381ms.
# Tapping the first line of text 
Selection: TextPosition(offset: 1, affinity: TextAffinity.downstream)
Selection: TextPosition(offset: 3, affinity: TextAffinity.downstream)
Selection: TextPosition(offset: 9, affinity: TextAffinity.upstream)
Selection: TextPosition(offset: 37, affinity: TextAffinity.downstream)
Selection: TextPosition(offset: 43, affinity: TextAffinity.downstream)

# Tapping line 2,3,4... values should be higher than the first line. 
Selection: TextPosition(offset: 1, affinity: TextAffinity.downstream)
Selection: TextPosition(offset: 2, affinity: TextAffinity.upstream)
Selection: TextPosition(offset: 2, affinity: TextAffinity.upstream)```
```

## Flutter doctor output:
```
[✓] Flutter (Channel master, v1.10.15-pre.305, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.15-pre.305 at /home/sir/development/flutter
    • Framework revision 01dc19b93f (7 days ago), 2019-10-28 19:58:06 -0700
    • Engine revision 49971e2140
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 5e39817ec7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/sir/Android/Sdk
    • Java binary at: /home/sir/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/sir/soft/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /snap/intellij-idea-ultimate/181
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[✓] Connected device (3 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Chrome                       • chrome        • web-javascript • Google Chrome 76.0.3809.132
    • Web Server                   • web-server    • web-javascript • Flutter Tools

• No issues found!

```

**Comment by stuz5000** [comment] 2019-11-04 20:26
Paragraph builder has the same issue. Updating title to reflect the cause.
```
import 'package:flutter/material.dart';
import 'dart:ui';
import 'dart:ui' as ui;

final loremIpsum =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Container(
            width: 350,
            color: Color.fromARGB(100, 0, 0, 0),
            child: SelectText(),
          ),
        ),
      ),
    );
  }
}

class SelectText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final TextStyle style = TextStyle(
      color: Colors.black,
    );

    // Set width to max allowed by parent
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      final ui.ParagraphBuilder paragraphBuilder = ui.ParagraphBuilder(
          ui.ParagraphStyle(
        fontSize: style.fontSize,
        // There unfortunelly are some things to be copied from your common TextStyle to ParagraphStyle :C
        fontFamily: style.fontFamily,
        // IDK why it is like this, this is somewhat weird especially when there is `pushStyle` which can use the TextStyle...
        fontStyle: style.fontStyle,
        fontWeight: style.fontWeight,
        textAlign: TextAlign.justify,
        //maxLines: 25,
      ))
        ..pushStyle(style
            .getTextStyle()) // To use multiple styles, you must make use of the builder and `pushStyle` and then `addText` (or optionally `pop`).
        ..addText(loremIpsum);

      final width = constraints.maxWidth;
      final ui.Paragraph paragraph = paragraphBuilder.build()
        ..layout(ui.ParagraphConstraints(width: width));

      paragraph.layout(ParagraphConstraints(
        width: width,
      ));
      final height = paragraph.height;

      return Container(
          width: width,
          height: height,
          color: Colors.yellow,
          child: GestureDetector(
            onTapDown: (details) {
              // BUG. On web- position is only correct for first line.
              print(
                  "Selection: ${paragraph.getPositionForOffset(details.localPosition)}");
            },
            child: CustomPaint(
              size: Size(width, height), // Parent width, text height
              painter: TextCustomPainter(paragraph),
            ),
          ));
    });
  }
}

class TextCustomPainter extends CustomPainter {
  Paragraph paragraph;

  TextCustomPainter(this.paragraph, {Listenable repaint})
      : super(repaint: repaint);

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawParagraph(paragraph, const Offset(0, 0));
  }

  @override
  bool shouldRepaint(CustomPainter old) {
    return false;
  }
}
```

**Comment by stuz5000** [comment] 2019-11-16 02:32
Possibly related to https://github.com/flutter/flutter/issues/45020

**Comment by mdebbar** [comment] 2019-12-11 22:12
Duplicate of https://github.com/flutter/flutter/issues/39826

**Closed by mdebbar** 2019-12-11 22:12 UTC
Labels: a: typography, f: gestures, ☸ platform-web
