### ISSUE TITLE
I have been going through all the issue threads related to this. Everywhere people mention quitting/disabling the AdGuard or anti-virus software. I do not have AdGuard installed and uninstalling or disabling anti-virus software doesn't seem like an option to me due to my company policies. Now, how do I get this working?

### ISSUE THREAD

**Issue by rahulrvp** [flutter/flutter#78690] opened 2021-03-20 13:59 UTC
I have been going through all the issue threads related to this. Everywhere people mention quitting/disabling the AdGuard or anti-virus software. I do not have AdGuard installed and uninstalling or disabling anti-virus software doesn't seem like an option to me due to my company policies. Now, how do I get this working?

The `flutter config --no-analytics` command only helps me to get the `flutter doctor` command to work. Once you start a project, the `flutter pub get` command is not working due to the very same error!

Totally stuck now!! Seeing this issue still occurring in March 2021 even though this was reported in q4 of 2020, I think this is a bit of a negligible towards the @flutter community.

```
Running "flutter pub get" in my_app...                

Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub get failed (255; #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12))
Process finished with exit code 255
```

_Originally posted by @rahulrvp in https://github.com/flutter/flutter/issues/71483#issuecomment-803340992_

**Comment by iapicca** [comment] 2021-03-20 15:31
@rahulrvp 
> Totally stuck now!! Seeing this issue still occurring in March 2021 even though this was reported in q4 of 2020, 

the referenced [issue](https://github.com/flutter/flutter/issues/71483#issuecomment-737096037) was **_closed_**  in q4 2020, it's not actively worked on

> I think this is a bit of a negligible towards the @flutter community.

I'm sorry you feel that way, but consider that the purpose of this repo is to improve flutter
with bug reports and feature requests, **_not_** to give assistance to developers

> [...] uninstalling or disabling anti-virus software doesn't seem like an option to me due to my company policies. Now, how do I get this working?

the problem doesn't seem to be an issue with flutter, but with the set up of the antivirus of on your machine
if you need help with your set up you may ask assistance on [stackoverflow](https://stackoverflow.com/tags/flutter), [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) or [slack](https://fluttercommunity.dev/joinslack)

**Comment by rahulrvp** [comment] 2021-03-22 06:06
@iapicca Thanks for the time to review my issue and providing a clean response.

I was saying if the operations flutter do under the hood for getting libraries and executing certain commands seems an issue to all the antivirus software, there has to be some resolution made from the flutter team to support this right? That was my intention to raise a ticket here.

I have been searching all the above forums to find a solution and seems like there is none that does not require the antivirus software uninstallation/disabling. :(

**Comment by iapicca** [comment] 2021-03-22 08:43
duplicate of https://github.com/flutter/flutter/issues/46696

**Comment by darshankawar** [comment] 2021-03-22 10:42
> the problem doesn't seem to be an issue with flutter, but with the set up of the antivirus of on your machine
> if you need help with your set up you may ask assistance on [stackoverflow](https://stackoverflow.com/tags/flutter), [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) or [slack](https://fluttercommunity.dev/joinslack)

You may get more help from the links mentioned here. 




> I have been searching all the above forums to find a solution and seems like there is none that does not require the antivirus software uninstallation/disabling.

Please follow-up in https://github.com/flutter/flutter/issues/46696 for updates.

You may also try to whitelist the Flutter SDK if you haven't tried that already. See also [this](https://github.com/flutter/flutter/issues/61997) open issue for further reference.

Closing from here.

**Closed by darshankawar** 2021-03-22 10:42 UTC
Labels: in triage
