### ISSUE TITLE
[image_picker] ignores maxHeight

### ISSUE THREAD

**Issue by WasaLordy** [flutter/flutter#131963] opened 2023-08-04 22:17 UTC
# Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

Edit: I found this old issue: https://github.com/flutter/flutter/issues/88901 which is still open

### Steps to reproduce

I have a problem with the scaling of the image.
If only maxHeight is used everything works fine but setting maxHeight and maxWidth in [pickImage] results in a scaling in only one dimension which could be wrong.

E.g. maxWidth: 1440, maxHeight: 1800,
Original Image: 4000 * 6080, 1,4 MB
=>
After pickImage: 1440 * 2188, 89 KB

### Expected results

I expect that the width is max 1440 and the height is max 1800, which is not the case here.
Width should be 1184 and height 1800, which is the case when I only pass maxHeight.

### Actual results

Images are only scaled in one dimension: After pickImage: 1440 * 2188, 89 KB

Edit: See also this old issue: https://github.com/flutter/flutter/issues/88901 which is still open

### Code sample
image_picker: ^1.0.1
image_size_getter: ^2.1.2
```
import 'package:image_size_getter/image_size_getter.dart' as isg;

XFile? file = await ImagePicker().pickImage(
    source: ImageSource.gallery,
    maxWidth: 1440,
    maxHeight: 1800,
    imageQuality: 50,
    requestFullMetadata: false,
);

final f = await files.first.readAsBytes();
final size = const isg.JpegDecoder().getSize(isg.MemoryInput(f));
logger.w('$size file: ${f.length/1024} KB');
```

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3208], locale de-DE)
    • Flutter version 3.10.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at C:\Users\Paul\AppData\Local\Android\sdk
    • Platform android-33, build-tools 34.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Paul\AppData\Local\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3208]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by stuartmorgan** [comment] 2023-08-05 15:39
Closing as a duplicate of https://github.com/flutter/flutter/issues/88901

**Closed by stuartmorgan** 2023-08-05 15:39 UTC
