### ISSUE TITLE
Windows build support self-contained build (single exe file)

### ISSUE THREAD

**Issue by cnmade** [flutter/flutter#105655] opened 2022-06-09 00:13 UTC
Feature request: 
flutter build for windows can build output a single exe file.
build all dll, into one big single exe file, let we can easy to redeploy our programm, copy then run.

much more like Mac .app file, copy, then we can run anywhere.

**Comment by stuartmorgan** [comment] 2022-06-09 00:18
Duplicate of https://github.com/flutter/flutter/issues/75200

**Closed by stuartmorgan** 2022-06-09 00:18 UTC

**Comment by cnmade** [comment] 2022-06-09 00:39
I am said some thing like dotnet self contained file. It's more like a box to map to real  executable file and it's dlls
