### ISSUE TITLE
TextField onchange does not return empty if text got selected and change the text

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#123955] opened 2023-04-02 02:04 UTC
![image](https://user-images.githubusercontent.com/20491308/229327040-a2839614-ef14-40e6-858a-cb386c19a93c.png)

when i press any key in keyboard the onchange event does not return value as empty.

forexample, the text selected in the textbox and i press the 'K' key the onchange event written log for 'K'
but i expected first time log should be null or empty and then 'K'

Flutter version 3.7.9 on channel stable

class _TextFieldIssueState extends State<TextFieldIssue> {
  final ctrlText = TextEditingController();

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    Future.delayed(Duration(milliseconds: 60), () {
      ctrlText.text = 'text';
      ctrlText.selection =
          TextSelection(baseOffset: 0, extentOffset: ctrlText.text.length);
    });

    ctrlText.addListener(() {
      print('listen value: ' + ctrlText.text);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TextFormField(
        autofocus: true,
        controller: ctrlText,
        onChanged: (value) {
          print('onchange value: ' + value);
        },
        decoration: const InputDecoration(
          labelText: 'Email',
        ),
        textInputAction: TextInputAction.next,
      ),
    );
  }
}

output:
flutter: onchange value: K

**Comment by huycozy** [comment] 2023-04-03 11:51
Hi @selvam920 
This is intended behavior. You should handle it by yourself to have your expected result. Closing as it's not a Flutter issue.

**Closed by huycozy** 2023-04-03 11:51 UTC
Labels: in triage
