### ISSUE TITLE
Problem nesting horizontal scrolling widget in ExpansionTile

### ISSUE THREAD

**Issue by ericricky** [flutter/flutter#26984] opened 2019-01-23 21:00 UTC
## Steps to Reproduce
I am trying to create an `ExpansionTile` in which the child is a horizontal scrolling widget such as `ListView`. I've tried variations of the following program with different error messages. If it's relevant, I am trying to fix the expansion tile to a certain portion of the screen so that opening/closing it does not affect some lower elements on screen. 

Example program: 

```dart
import 'package:flutter/material.dart';

void main() => runApp(
  MaterialApp(
    home: Scaffold(
      appBar: AppBar(title: Text("Title")),
      body: Column(
        children: <Widget>[
          Expanded(
            flex: 5,
            child: ExpansionTile(
              children: <Widget>[
                ListView(
                  shrinkWrap: true,
                  scrollDirection: Axis.horizontal,
                  children: <Widget>[
                    Text("Hello"),
                    Text("World"),
                  ],
                ),
              ],
            ),
          ),
          Expanded(
            flex: 5,
            child: Container(
              color: Colors.red,
            ),
          ),
        ],
      ),
    )
  )
);
```

## Logs
Here is the start of the relevant part of the logs.

```
[  +97 ms] I/flutter (14616): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +21 ms] I/flutter (14616): The following assertion was thrown building AnimatedBuilder(animation: AnimationController#39d6c(⏮
[        ] I/flutter (14616): 0.000; paused), dirty, state: _AnimatedState#d4694):
[        ] I/flutter (14616): 'package:flutter/src/widgets/text.dart': Failed assertion: line 40 pos 15: 'child != null': is not
[        ] I/flutter (14616): true.
[   +8 ms] I/flutter (14616): 
[        ] I/flutter (14616): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (14616): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (14616): In either case, please report this assertion by fi
ling a bug on GitHub:
[  +52 ms] I/flutter (14616):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (14616): 
[        ] I/flutter (14616): When the exception was thrown, this was the stack:
[        ] I/flutter (14616): #2      new DefaultTextStyle (package:flutter/src/widgets/text.dart:40:15)
[        ] I/flutter (14616): #3      _ExpansionTileState._buildChildren (package:flutter/src/material/expansion_tile.dart:163:22)
[        ] I/flutter (14616): #4      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:840:12)
[        ] I/flutter (14616): #5      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:96:48)
[        ] I/flutter (14616): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
[        ] I/flutter (14616): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
[        ] I/flutter (14616): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
[        ] I/flutter (14616): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
[        ] I/flutter (14616): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)

```

**Comment by zoechi** [comment] 2019-01-24 09:14
I can not reproduce the issue.
I get a warning that `title` is required for `ExpansionTile` and when I collapse I get
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,854ms.
I/flutter ( 4359): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4359): The following assertion was thrown during performLayout():
I/flutter ( 4359): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1598 pos 16:
I/flutter ( 4359): 'constraints.hasBoundedHeight': is not true.
I/flutter ( 4359): 
```

**Comment by zoechi** [comment] 2019-01-24 09:14
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment] 2019-02-18 08:06
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-18 08:06 UTC
Labels: waiting for customer response

**Comment by mirmahfuz99** [comment] 2020-04-30 10:20
Keep your ExpansionTile inside a ListView And Inner ListView should be present inside a Container .Here is an example code:

`return new Scaffold(
      body: new ListView.builder(
        itemCount: vehicles.length,
        itemBuilder: (context, i) {
          return new ExpansionTile(
            leading:  new Icon(vehicles[i].icon),
            title: new Text(vehicles[i].title, style: new TextStyle(fontSize: 20.0, fontWeight: FontWeight.bold, fontStyle: FontStyle.italic),),
            children: <Widget>[
              Container(
                height : 300,
                child: ListView.builder(
                    shrinkWrap: true,
                    scrollDirection: Axis.horizontal,
                    itemCount: vehicles[i].contents.length,
                    itemBuilder: (BuildContext ctxt, int Index) {
                      return Text(vehicles[i].contents[Index]);
                    }),
              )
            ],
          );
        },
      ),
    )`

**Comment by egprojects** [comment] 2020-05-04 16:51
The problem is real. If you remove `scrollDirection: Axis.horizontal,` from the code above you'll see that it's working pretty OK. But when you try to change scroll direction to horizontal it'll not show you anything. Surprisingly, if you'll use Row instead of ListView it will show the items.
