### ISSUE TITLE
[IDE Integration] Android Studio only shows first few lines of stack trace

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#84535] opened 2021-06-13 21:10 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
 - add `int value = (null)!;` just before `_counter++`, to cause an exception.
3. Run the app, click the plus button

Note: related to #43331

**Expected results:** 
To see full stacktrace in the console

**Actual results:**
You can only see the first few lines of it, such as:
```
======== Exception caught by gesture library =======================================================
The following _TypeError was thrown while dispatching a pointer event:
type 'Null' is not a subtype of type 'String' of 'function result'

When the exception was thrown, this was the stack: 
#0      _Location.file (package:flutter/src/widgets/widget_inspector.dart)
#1      _Location.toJsonMap (package:flutter/src/widgets/widget_inspector.dart:2844:15)
#2      _Location.toJsonMap.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:2853:42)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
...
Event: PointerUpEvent#d7bb4(position: Offset(368.6, 765.1))
  position: Offset(368.6, 765.1)
Target: <WidgetsFlutterBinding>
====================================================================================================
```

<details>
  <summary>Logs</summary>

Not adding the `flutter run` logs since they are working when running `flutter run`. The problem is with the IDE integration.

`flutter analyze` logs:
```
Analyzing tmp...
   info - The value of the local variable 'value' isn't used - bug\lib\main.dart:58:11 - unused_local_variable
   info - This null-check will always throw an exception because the expression will always evaluate to 'null' - bug\lib\main.dart:58:19 - null_check_always_fails
   info - Dead code - bug\lib\main.dart:59:7 - dead_code

3 issues found. (ran in 3.1s)
```
That's expected though, since the line is written to cause an exception.

`flutter doctor -v` logs:
```
$ flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at D:\Flutter
    • Framework revision d79295af24 (2 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • ANDROID_SDK_ROOT = D:\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)                       • edge          • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-14 14:48
Hi @matanshukry 

<details> 
<summary>logs</summary> 
	
```console
Launching lib\main.dart on IN2011 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:53760/zrkmihGf2ss=/ws
Syncing files to device IN2011...
W/DisplayEventDispatcher( 6644): dispatcher 0xb4000073b94f8530 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher( 6644): dispatcher 0xb4000073694df6b0 ~ ignoring unknown event type 0x6d746f6e
D/OpScreenModeManager( 6644): setRefreshRate parent io.flutter.embedding.android.FlutterView{8e80b2c VFED..... ......ID 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager( 6644): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{1ebc339 V.E...... ......ID 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/OpScreenModeManager( 6644): setRefreshRate parent io.flutter.embedding.android.FlutterView{8e80b2c VFED..... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager( 6644): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{1ebc339 V.E...... ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/DecorView( 6644): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d1172df[MainActivity]
D/ViewRootImpl[MainActivity]( 6644): windowFocusChanged hasFocus=true inTouchMode=true
W/DisplayEventDispatcher( 6644): dispatcher 0xb4000073b94f8530 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher( 6644): dispatcher 0xb4000073694df6b0 ~ ignoring unknown event type 0x6d746f6e

======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _MyHomePageState._incrementCounter.<anonymous closure> (package:bug/main.dart:58:25)
#1      State.setState (package:flutter/src/widgets/framework.dart:1088:30)
#2      _MyHomePageState._incrementCounter (package:bug/main.dart:52:5)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#b774a
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(341.3, 787.9)
  finalLocalPosition: Offset(29.3, 22.6)
  button: 1
  sent tap down
====================================================================================================

```

</details>

Is your output complete, in my  case, I do see tap down 


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1055], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Taha\Code\flutter_stable
    • Framework revision d79295af24 (3 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31402.337
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1055]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 91.0.864.48

! Doctor found issues in 1 category.
PS C:\Users\Taha\StudioProjects\bug> f^C
PS C:\Users\Taha\StudioProjects\bug> ^C
PS C:\Users\Taha\StudioProjects\bug> fsd
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1055], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Taha\Code\flutter_stable
    • Framework revision d79295af24 (3 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31402.337
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1055]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 91.0.864.48

! Doctor found issues in 1 category.
```

</details>


![image](https://user-images.githubusercontent.com/48603081/121909615-c4495380-cd36-11eb-82c6-3f3af6866ce7.png)



Can make sure you're using the same plugin?


Related https://github.com/flutter/flutter/issues/84539?

**Comment by matanshukry** [comment] 2021-06-15 06:27
Hey @TahaTesser,

> Is your output complete, in my case, I do see tap down

It is complete. You can see the end of it by the line with the `====`.

> Can make sure you're using the same plugin?

It is, with exactly the same versions as well.

> Related #84539?

Dont' think so, but it's possible both are caused by the same issue. Since we don't know what the actual cause it, we don't really know.


I'm not familiar with flutter/intellij integration, but if it's possible I'm willing to debug it further, code included.

**Comment by TahaTesser** [comment] 2021-06-15 07:28
Hi @matanshukry 
Unfortunately, both issues don't reproduce for me on Windows using the same code and plugin

As you mentioned in the title, it's Android Studi only, Is it possible for you to try in VS Code and Terminal and confirm, there is no issue on both?

Thank you

**Comment by matanshukry** [comment] 2021-06-15 14:31
@TahaTesser checked with VS code, it seems to work fine. Checked with terminal previously and it works fine as well.

so yes, this is an android studio issue only.

> both issues don't reproduce for me on Windows using the same code and plugin
Do you mean with Android Sutdio or with other IDEs?

**Comment by TahaTesser** [comment] 2021-06-16 07:18
Hi @matanshukry 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-16 07:18 UTC
Labels: in triage

**Comment by matanshukry** [comment] 2021-06-16 08:03
didn't know there was specific repo for that. Looked in there and found out there was an issue to it and a fix, made around 2m ago.

So for anyone else who encounters it, the pr is this:
https://github.com/flutter/flutter-intellij/pull/5443/files#

and comparing the code to what I have in IntelliJ, I don't believe it's out yet.
