### ISSUE TITLE
Undefined symbols for architecture x86_64 and ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by ArdelAlegre1** [flutter/flutter#55176] opened 2020-04-20 00:10 UTC
Hello I am very new to flutter and app development in general. When I was cleaning out my computer I think I may have accidentally deleted something important? I have tried deleting my podfile podfile.lock and runner.xcworkspace and letting it recreate itself, but that doesn't seem to work.

## Steps to Reproduce

1. Run `flutter run`.

**Actual results:** 
<details>
  <summary>Logs</summary>

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                            8.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in GoogleApiAvailabilityPlugin.o
      "_FlutterMethodNotImplemented", referenced from:
          -[GoogleApiAvailabilityPlugin handleMethodCall:result:] in GoogleApiAvailabilityPlugin.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

```
Analyzing christin...                                                   

   info • Unused import: 'dart:async' • lib/Home.dart:1:8 • unused_import
   info • 'await' applied to 'void', which is not a 'Future' • lib/Home.dart:52:5 •
          await_only_futures
   info • Unused import: 'package:christin/globals.dart' • lib/Welcome.dart:1:8 •
          unused_import
   info • Name types using UpperCamelCase • lib/editPhotos.dart:8:7 •
          camel_case_types
   info • Name types using UpperCamelCase • lib/editPhotos.dart:18:7 •
          camel_case_types
   info • Don't explicitly initialize variables to null • lib/globals.dart:6:21 •
          avoid_init_to_null
   info • Unused import: 'package:firebase_auth/firebase_auth.dart' •
          lib/login_signup_page.dart:3:8 • unused_import
   info • Unused import: 'login_signup_page.dart' • lib/main.dart:4:8 • unused_import
   info • Name types using UpperCamelCase • lib/map.dart:5:7 • camel_case_types
   info • This class (or a class which this class inherits from) is marked as
          '@immutable', but one or more of its instance fields are not final:
          map.currentLocation • lib/map.dart:5:7 • must_be_immutable
   info • Name types using UpperCamelCase • lib/map.dart:13:7 • camel_case_types
   info • Name types using UpperCamelCase • lib/photoSelect.dart:11:7 •
          camel_case_types
   info • Name types using UpperCamelCase • lib/photoSelect.dart:21:7 •
          camel_case_types
   info • The declaration '_clear' isn't referenced • lib/photoSelect.dart:54:8 •
          unused_element

14 issues found. (ran in 12.3s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale
    en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/ardelalegre/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ardelalegre/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 446850C7-C775-4440-B89D-2C47A6D8CA1B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>

**Comment by sohampandya00** [comment] 2020-04-20 04:38
Same issue.

**Comment by TahaTesser** [comment] 2020-04-20 09:19
Duplicate of [#51395](https://github.com/flutter/flutter/issues/51395)

**Closed by TahaTesser** 2020-04-20 09:19 UTC
