### ISSUE TITLE
upgrade integration_test to null safety

### ISSUE THREAD

**Issue by Mister-Hope** [flutter/flutter#77459] opened 2021-03-06 10:45 UTC
```
Because every version of integration_test depends on flutter_driver any from sdk which depends on archive 2.0.13, every version of integration_test requires archive 2.0.13.

So, because innenu depends on both archive ^3.1.2 and integration_test any, version solving failed.
pub get failed (1; So, because innenu depends on both archive ^3.1.2 and integration_test any, version solving failed.)
exit code 1
```

**Comment by darshankawar** [comment] 2021-03-08 09:02
@Mister-Hope 
Check [this](https://github.com/flutter/flutter/issues/71379#issuecomment-772055489) comment and see if it helps to resolve the issue.

**Comment by Mister-Hope** [comment] 2021-03-08 11:12
Nope. I have already changed to :

```

dev_dependencies:

  integration_test:
    sdk: flutter
```

https://github.com/brendan-duncan/archive/blob/master/CHANGELOG.md

archieve says it support null safety in v3.

```
[innenu] flutter pub get
Running "flutter pub get" in innenu...                          
Because every version of integration_test from sdk depends on archive 2.0.13 and innenu depends on archive ^3.1.2, integration_test from sdk is forbidden.

So, because innenu depends on integration_test any from sdk, version solving failed.
pub get failed (1; So, because innenu depends on integration_test any from sdk, version solving failed.)
exit code 1
```

**Comment by Mister-Hope** [comment] 2021-03-08 11:18
I read though the comments again, so it's now availble on dev channel?

IMO, packages like this should be bundled with major release, otherwise I would not agree that the relase should be put into stable.

**Comment by darshankawar** [comment] 2021-03-09 06:05
> I read though the comments again, so it's now availble on dev channel?

@Mister-Hope Yes, it should now be available on dev.


> IMO, packages like this should be bundled with major release, otherwise I would not agree that the release should be put into stable. I think there is a lot of people like me would regard it as core packages of flutter.

Cc: @dnfield

**Comment by stuartmorgan** [comment] 2021-03-13 12:04
Closing as a duplicate of 71379

**Closed by stuartmorgan** 2021-03-13 12:04 UTC
Labels: in triage, waiting for customer response
