### ISSUE TITLE
TextField with obscureText=true craches with EXC_BAD_ACCESS on iOS

### ISSUE THREAD

**Issue by espresso3389** [flutter/flutter#62650] opened 2020-07-31 08:12 UTC
## Steps to Reproduce

`TextField(obscureText: true)` craches with EXC_BAD_ACCESS on iOS.
The simplest repro code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TextField issue',
      home: Scaffold(
        appBar: AppBar(
          title: Text('TextField issue'),
        ),
        body: TextField(obscureText: true)
      )
    );
  }
}
```

If you remove `obscureText: true`, it does not crash.

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.129, on Mac OS X 10.15.6 19G73, locale ja-JP)
    • Flutter version 1.21.0-6.0.pre.129 at /Users/kawasaki/flutter
    • Framework revision 30aef0a3b9 (11 hours ago), 2020-07-30 14:20:21 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kawasaki/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • 川崎高志のiPhone (mobile) • 3628db90114429a646c3295c78b92ebe92536748 • ios • iOS 13.6
    ! Error: Cuminas iPad Pro 10.5 is not connected. Xcode will continue when Cuminas iPad Pro 10.5 is connected. (code -13)
    ! Error: クミナス開発のiPad mini is not connected. Xcode will continue when クミナス開発のiPad mini is connected. (code -13)
```

**Comment by pedromassangocode** [comment] 2020-07-31 09:11
Hi @espresso3389 
Can you please provide your full `flutter run --verbose`. If the logs are too long, you may attach them as txt file.
Thank you

**Comment by espresso3389** [comment] 2020-07-31 10:04
[flutter--verbose.txt](https://github.com/flutter/flutter/files/5006373/flutter--verbose.txt)

I didn't explain the things accurately; the crash occurs either on tapping on the textfield or typing a character on it.

<img width="1440" alt="error-xcode" src="https://user-images.githubusercontent.com/1311400/89024780-9e0a0780-d360-11ea-9657-0ee1f56de613.png">

**Comment by LongCatIsLooong** [comment] 2020-07-31 11:04
Seems to be a duplicate of https://github.com/flutter/flutter/issues/62501, should be fixed when the next engine roll lands.

**Closed by LongCatIsLooong** 2020-07-31 11:04 UTC
Labels: in triage
