### ISSUE TITLE
ThemeData.fontFamily not applied to appBarTheme/textButtonTheme or any other xxxTheme with TextStyle

### ISSUE THREAD

**Issue by wliu6v** [flutter/flutter#99665] opened 2022-03-07 08:30 UTC
## Steps to Reproduce

1. Create ThemeData with a custom fontFamily, it should be work for all widget. like below

![image](https://user-images.githubusercontent.com/5987831/156993771-5781288c-f913-4c71-88e9-537c299ada24.png)

2. Create a AppBarTheme with custom TextStyle. If the fontFamily property is not explicitly set, it should use the ThemeData's fontFamily, but in fact it does not.

![image](https://user-images.githubusercontent.com/5987831/156994165-5feaedff-6b99-46cb-98ea-bf7c885c01fb.png)

3. TextButtonTheme / OutlinedButtonTheme or any other xxxTheme has same problem. So we had to declare fontFamily property over and over again for everything with TextStyle defined in ThemeData.

![image](https://user-images.githubusercontent.com/5987831/156994666-b30665cd-d0bc-4cff-9bee-43c6347d2eec.png)

<summary>Code sample</summary>

full code : https://github.com/wliu6v/flutter-font-theme-demo/blob/master/lib/main.dart

<details>

```dart
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        fontFamily: 'test',
        // define appbar textstyle makes global fontfamily not work.
        appBarTheme: AppBarTheme(
          titleTextStyle: TextStyle(
            fontSize: 18,
            // font family must define again! otherwise appbar missing its style
            // fontFamily: 'test',
          ),
        ),

        textButtonTheme: TextButtonThemeData(
          style: TextButton.styleFrom(
            textStyle: TextStyle(
              fontSize: 18,
              // font family must define again! otherwise textButton missing its style
              fontFamily: 'test',
            ),
          ),
        ),
      ),
      home: const MyHomePage(title: 'app bar font family is wrong!'),
    );

```

</details>

<details>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/username/fvm/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = ~/Library/Android/sdk
    • Java binary at: /Users/username/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/username/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/username/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
```

</details>

**Comment by maheshmnj** [comment] 2022-03-07 11:47
Hi @wliu6v, Thanks for filing the issue. I ran the below code sample and used [this font](https://www.dafont.com/homeday-2.font) and I could see adding a fontFamily to ThemeData applies to appBar too.

Also, it looks like you are not using the latest version of flutter, Please try upgrading flutter and see if this helps resolve the issue. You may upgrade using `flutter upgrade`.

<img src="https://user-images.githubusercontent.com/31410839/157028660-88c25165-f926-4229-a539-7e6ea9d39bed.png" width ="300"> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue, fontFamily: 'Homeday'),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Icon(Icons.tiktok),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```
</details>

**Comment by HansMuller** [comment] 2022-03-07 19:10
CC @darrenaustin @guidezpl

**Comment by TahaTesser** [comment] 2022-04-22 11:54
Hi everyone
This is working as designed 

```dart
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
        appBarTheme: const AppBarTheme(
          backwardsCompatibility: false,
          // `textTheme` is deprecated, this property is only inherited only
          // when `backwardsCompatibility` is true.
          // This won't inherit font from  `ThemeData.fontFamily`, provide your font fammily below.
          // Source:
          // ```
          // TextStyle? titleTextStyle = backwardsCompatibility
          //   ? widget.textTheme?.headline6
          //     ?? appBarTheme.textTheme?.headline6
          //     ?? theme.primaryTextTheme.headline6
          //   : widget.titleTextStyle
          //     ?? appBarTheme.titleTextStyle
          //     ?? theme.textTheme.headline6?.copyWith(color: foregroundColor);
          // ```
          textTheme: TextTheme(
            headline6: TextStyle(
              fontFamily: 'Whisper',
              color: Colors.red,
            ),
          ),
          // Use `titleTextStyle` instead, provide font family here.
          // `ThemeData.fontFamily` will be deprecated in https://github.com/flutter/flutter/issues/91772
          // This won't inherit font from `ThemeData.fontFamily`, provide your font fammily below.
          // Source:
          // ```
          // TextStyle? titleTextStyle = backwardsCompatibility
          //   ? widget.textTheme?.headline6
          //     ?? appBarTheme.textTheme?.headline6
          //     ?? theme.primaryTextTheme.headline6
          //   : widget.titleTextStyle
          //     ?? appBarTheme.titleTextStyle
          //     ?? theme.textTheme.headline6?.copyWith(color: foregroundColor);
          // ```theme.primaryTextTheme.bodyText2
          // ```
          titleTextStyle: TextStyle(
            fontFamily: 'Whisper',
            backgroundColor: Colors.green,
          ),
        ),
```


`AppBarTheme.textTheme(deprecated)` is not inherited as suggested in https://github.com/flutter/flutter/issues/99665#issuecomment-1060602775, it is actually `ThemeData.fontFamily`

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key, this.dark = false});

  final bool dark;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: dark ? ThemeMode.dark : ThemeMode.light,
      theme: ThemeData(
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
        appBarTheme: const AppBarTheme(
          backwardsCompatibility: false,
          // `textTheme` is deprecated, this property is only inherited only
          // when `backwardsCompatibility` is true.
          // This won't inherit font from  `ThemeData.fontFamily`, provide your font fammily below.
          // Source:
          // ```
          // TextStyle? titleTextStyle = backwardsCompatibility
          //   ? widget.textTheme?.headline6
          //     ?? appBarTheme.textTheme?.headline6
          //     ?? theme.primaryTextTheme.headline6
          //   : widget.titleTextStyle
          //     ?? appBarTheme.titleTextStyle
          //     ?? theme.textTheme.headline6?.copyWith(color: foregroundColor);
          // ```
          textTheme: TextTheme(
            headline6: TextStyle(
              fontFamily: 'Whisper',
              color: Colors.red,
            ),
          ),
          // Use `titleTextStyle` instead, provide font family here.
          // `ThemeData.fontFamily` will be deprecated in https://github.com/flutter/flutter/issues/91772
          // This won't inherit font from `ThemeData.fontFamily`, provide your font fammily below.
          // Source:
          // ```
          // TextStyle? titleTextStyle = backwardsCompatibility
          //   ? widget.textTheme?.headline6
          //     ?? appBarTheme.textTheme?.headline6
          //     ?? theme.primaryTextTheme.headline6
          //   : widget.titleTextStyle
          //     ?? appBarTheme.titleTextStyle
          //     ?? theme.textTheme.headline6?.copyWith(color: foregroundColor);
          // ```theme.primaryTextTheme.bodyText2
          // ```
          titleTextStyle: TextStyle(
            fontFamily: 'Whisper',
            backgroundColor: Colors.green,
          ),
        ),
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
        appBarTheme: const AppBarTheme(
          backwardsCompatibility: false,
          // `textTheme` is deprecated, this property is only inherited only
          // when `backwardsCompatibility` is true.
          // This won't inherit font from  `ThemeData.fontFamily`, provide your font fammily below.
          // Source:
          // ```
          // TextStyle? titleTextStyle = backwardsCompatibility
          //   ? widget.textTheme?.headline6
          //     ?? appBarTheme.textTheme?.headline6
          //     ?? theme.primaryTextTheme.headline6
          //   : widget.titleTextStyle
          //     ?? appBarTheme.titleTextStyle
          //     ?? theme.textTheme.headline6?.copyWith(color: foregroundColor);
          // ```
          textTheme: TextTheme(
            headline6: TextStyle(
              fontFamily: 'Whisper',
              color: Colors.red,
            ),
          ),
          // Use `titleTextStyle` instead, provide font family here.
          // `ThemeData.fontFamily` will be deprecated in https://github.com/flutter/flutter/issues/91772
          // This won't inherit font from `ThemeData.fontFamily`, provide your font fammily below.
          // Source:
          // ```
          // TextStyle? titleTextStyle = backwardsCompatibility
          //   ? widget.textTheme?.headline6
          //     ?? appBarTheme.textTheme?.headline6
          //     ?? theme.primaryTextTheme.headline6
          //   : widget.titleTextStyle
          //     ?? appBarTheme.titleTextStyle
          //     ?? theme.textTheme.headline6?.copyWith(color: foregroundColor);
          // ```theme.primaryTextTheme.bodyText2
          // ```
          titleTextStyle: TextStyle(
            fontFamily: 'Whisper',
            backgroundColor: Colors.green,
          ),
        ),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App bar'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}

``` 
	
</details>

Closing as this is working as designed.

**Closed by TahaTesser** 2022-04-22 11:54 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 2.10, found in release: 2.11
