### ISSUE TITLE
[android] systemNavigationBarIconBrightness resets back to default after phone screen is turned off and on again

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#57848] opened 2020-05-23 11:58 UTC
## Steps to Reproduce
I have only tested it on Samsung S8
1. `SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark.copyWith(systemNavigationBarIconBrightness: Brightness.dark))`.
2. Turn off the screen by pressing the power button, and then turn it on again

**Expected results:** 
The navigation bar icon brightness should remain as set

**Actual results:**
The navigation bar icon brightness resets to its system default (other properties except icon brightness do retain)

**Flutter Doctor:**
```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.18.0-11.1.pre at C:\flutter
    • Framework revision 2738a1148b (10 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • SM G950F   • ce01182183406c760c • android-arm64  • Android 9 (API 28)
    • Web Server • web-server         • web-javascript • Flutter Tools
    • Chrome     • chrome             • web-javascript • Google Chrome 81.0.4044.138
```

**Comment by iapicca** [comment] 2020-05-25 10:04
Hi @MohiuddinM 
Can you please provide a minimal complete reproducible code sample.
Thank you

**Comment by MohiuddinM** [comment] 2020-05-29 11:49
Change the theme to light and notice the bottom bar color, now switch the screen on an off, and notice the icon color have reset.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _dark = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: RaisedButton(
            child: Text('Current theme: ${_dark ? 'dark' : 'light'}'),
            onPressed: () {
              setState(() {
                _dark = !_dark;

                if (_dark) {
                  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);
                } else {
                  SystemChrome.setSystemUIOverlayStyle(
                      SystemUiOverlayStyle.dark.copyWith(systemNavigationBarColor: Colors.black26, systemNavigationBarIconBrightness: Brightness.dark));
                }
              });
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by VladyslavBondarenko** [comment] 2020-05-29 15:27
@MohiuddinM with the same `beta 1.18.0-11.1.pre` I couldn't reproduce it on Redmi Note 7 Android 9 (API 28).
Does it happen with current master version as well?

**Comment by TahaTesser** [comment] 2020-09-16 12:49
Hi @MohiuddinM 

Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with the latest `stable` and `flutter run --verbose` 
Thank you

**Comment by markusaksli-nc** [comment] 2020-10-07 09:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by markusaksli-nc** 2020-10-07 09:08 UTC
Labels: a: layout, e: device-specific, framework, platform-android, waiting for customer response
