### ISSUE TITLE
[video_player] Unhandled Exception: PlatformException(VideoError, Failed to load video: 未能完成该操作，(kCFErrorDomainCFNetwork错误-12281 - custom url not redirect), null) 

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#54534] opened 2020-04-11 12:40 UTC
Hello,

 I got this error sometime when playing video. 

  I can't find any code with  `PlatformException(VideoError` in Video_player plugin, do you know how can I find the root caused code.

**Comment by TahaTesser** [comment] 2020-04-13 10:14
Hi @jerryzhoujw 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jerryzhoujw** [comment] 2020-04-15 03:40
Hi @TahaTesser 

   It seems because I try to include extra feature from @recastrodiaz's work. 
   And this error is related to the cache feature added by @recastrodiaz.
   revert it make this error disppear.

```dart
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:  
  video_player: #^0.10.8 # for video player
    git:
      source: git
      url: "https://github.com/jerryzhoujw/plugins/"
      path: "packages/video_player/video_player"
      ref: "dev/avoid_dim_screen_when_playing_video_with_speed_adjust"
      version: "0.12.3"

dependency_overrides:
  video_player_platform_interface:
    git:
      source: git
      url: "https://github.com/recastrodiaz/plugins"
      path: "packages/video_player/video_player_platform_interface"
      ref: "develop2"
      version: ^1.1.0
```

**Comment by TahaTesser** [comment] 2020-04-15 07:22
Hi @jerryzhoujw 
Looks like it's not a issue with `video_player` itself
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-04-15 07:22 UTC
Labels: in triage
