### ISSUE TITLE
ListViews get scrambled in version 1.19.0-1.0.pre on web

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#57105] opened 2020-05-13 12:01 UTC
There seems to be a bug introduced in version **1.19.0-1.0.pre** on the web.

Elements (images/text) of ListViews get hidden or swapped between ListViews.

This issue was not present in version **1.19.0-0.0.pre** (**dev** channel).

To overcome the issue I've switched back to the working version with the `flutter version 1.19.0-0.0.pre`. I guess it should work also with `flutter downgrade`

**Comment by slavap** [comment] 2020-05-13 12:10
The same problem for me, reverted back to 1.18.0-13.0.pre

**Comment by TahaTesser** [comment] 2020-05-14 10:07
Hi @Constans 
can you please provide your `flutter doctor -v` and `flutter run -d Chrome --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by slavap** [comment] 2020-05-14 10:18
@TahaTesser this new bug is total stopper, flutter web is completely broken in 1.19.0-1.0.pre

**Comment by Constans** [comment] 2020-05-14 10:47
> Hi @Constans
> can you please provide your `flutter doctor -v` and `flutter run -d Chrome --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

Please see the mentioned issue above.

I'll see if I have time to write a minimal code sample. Right now I have my hands quite full, hence the short bug report.

Please find bellow my **flutter doctor -v**:
```
[✓] Flutter (Channel unknown, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale en-NL)
    • Flutter version 1.19.0-0.0.pre at /Users/constans/development/flutter
    • Framework revision a849daf283 (6 days ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/constans/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4694.29

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

If there is still a need of further info from my side, please let me know.

**Comment by 10686142** [comment] 2020-05-14 11:59
Same here, I am experiencing this both on the master and dev channel on my Safari iOS browser and my macbook's Chrome browser:

#### Iphone Safari browser:
![](https://media.giphy.com/media/VD43MU7EHr7xLq02Mk/giphy.gif)


#### Mac Chrome browser:
![](https://media.giphy.com/media/f7Yag47WeF8A8Lzd64/giphy.gif)


#### Logs
<details>
 <summary>Flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.34, on Mac OS X 10.15.4 19E287, locale en-NL)
    • Flutter version 1.19.0-2.0.pre.34 at /Users/vascowerk/Development/flutter
    • Framework revision 610dc170d9 (19 hours ago), 2020-05-14 00:37:02 +0800
    • Engine revision b59e3e9c39
    • Dart version 2.9.0 (build 2.9.0-8.0.dev 2bf3259005)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vascowerk/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • iPhone 11  • 983437CA-22B4-4A37-AB90-E55B565739DA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by jason-simmons** [comment] 2020-05-14 21:31
I can reproduce image tiles disappearing using the current master by running Gallery on web and scrolling around in the Pesto demo.

This is associated with https://github.com/flutter/engine/commit/68bf137634b5628d2f1fa94605d3d7bacbc0f966

@yjbanov

**Comment by yjbanov** [comment] 2020-05-14 21:39
That looks like a bad regression. I'll be looking into it shortly.

**Comment by slavap** [comment] 2020-05-14 21:44
@jason-simmons @yjbanov Pardon my question, but how could it be that such major breakage is not caught by automatic tests? I was under impression that dev channel gets more or less tested versions.

**Comment by yjbanov** [comment] 2020-05-14 22:16
@slavap One issue we are experiencing with screenshot testing on the web is that `--headless` Chrome is behaving differently from non-headless Chrome. In particular there is a difference in paint order, where some things get obscured when running without `--headless`. We will be moving to new test infra that will allow us to run all tests without `--headless`. This issue also affects Safari.

**Closed** 2020-05-15 01:25 UTC
Labels: customer: crowd, f: scrolling, found in release: 1.19, framework, platform-web, severe: regression, ⚠ TODAY

**Comment by emran92** [comment] 2020-05-17 10:42
TextFormField is flickering in  `1.19.0-2.0.pre.83`

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.83, on Mac OS X 10.15.4 19E287, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)
```

![May-17-2020 16-41-33](https://user-images.githubusercontent.com/21041969/82142327-58f43000-985d-11ea-8cb8-da4c6c730b42.gif)

**Comment by Constans** [comment] 2020-05-18 14:40
> TextFormField is flickering in `1.19.0-2.0.pre.83`
> 
> ```
> [✓] Flutter (Channel master, 1.19.0-2.0.pre.83, on Mac OS X 10.15.4 19E287, locale en-BD)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [✓] VS Code (version 1.45.1)
> [✓] Connected device (3 available)
> ```
> 
> ![May-17-2020 16-41-33](https://user-images.githubusercontent.com/21041969/82142327-58f43000-985d-11ea-8cb8-da4c6c730b42.gif)

@emran92 , I think you have to open a new issue to be noticed.

**Comment by slavap** [comment] 2020-05-19 01:27
@emran92 @Constans @yjbanov Looks like related issue to me, not sure new issue should be opened.

**Comment by Constans** [comment] 2020-05-19 09:47
The context and elements involved are a bit different. 

Anyway, the main issue is that this ticket is closed, so the attention will not fall here anymore.

When opening the new ticket you can also mention this one if you think they are related.
