### ISSUE TITLE
Admob wrong size smartBanner when ad have long text

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#34985] opened 2019-06-24 11:29 UTC
Hello! When specifying the size: AdSize.smartBanner for an advertising banner, the size on the iphone xr is not correctly determined

<img width="597" alt="Снимок экрана 2019-06-24 в 13 24 43" src="https://user-images.githubusercontent.com/44409006/60011914-763b7100-9683-11e9-8f8c-c84bc9dbc7c2.png">

**Comment by Piinks** [comment] 2019-06-26 17:14
Hi @1AlexFix1, Can you post a minimal sample of code that reproduces the issue? We will need more information to help you resolve it.

**Comment by 1AlexFix1** [comment] 2019-06-26 21:12
```
 myBanner = BannerAd(
      adUnitId: ADS.bannerId,
      size: AdSize.smartBanner,
      targetingInfo: ADS.targetingInfo,
      listener: (MobileAdEvent event) {
        if (MobileAdEvent.loaded == event) {
          setState(() {
            myBanner.show(anchorType: AnchorType.bottom);
          });
        }
      },
    );
    myBanner.load();
```

I also found some regularity; I changed the SmartBanner to AdSize.banner. And if the advertisement has the text, it goes beyond the screen, although the width of the banner is 
_width:_ 320,
height: 50,
This is how the advertisement with this code was displayed.

```
 myBanner = BannerAd(
      adUnitId: ADS.bannerId,
      size: AdSize.banner,
      targetingInfo: ADS.targetingInfo,
      listener: (MobileAdEvent event) _{_
        if (MobileAdEvent.loaded == event) {
          setState(() {
            myBanner.show(anchorType: AnchorType.bottom);
          });
        }
      },
    );
    myBanner.load();
```


> Hi @1AlexFix1, Can you post a minimal sample of code that reproduces the issue? We will need more information to help you resolve it.

**Comment by 1AlexFix1** [comment] 2019-06-26 21:25
That's how ads on smartSize are displayed on iphone 6
<img width="754" alt="Снимок экрана 2019-06-27 в 0 18 42" src="https://user-images.githubusercontent.com/44409006/60215840-3e921c00-9871-11e9-822a-091892683447.png">

**Comment by kroikie** [comment] 2019-10-13 19:48
@1AlexFix1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1176. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:47
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by stuartmorgan** [comment] 2021-05-25 19:20
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).

**Closed by stuartmorgan** 2021-05-25 19:20 UTC
Labels: p: firebase_admob, plugin, transferred
