### ISSUE TITLE
Issue in webview_flutter plugin

### ISSUE THREAD

**Issue by gayatri2610** [flutter/flutter#69393] opened 2020-10-30 11:55 UTC
Hello ,
I can't intercept http request with help of webview_flutter plugin.

**Comment by gayatri2610** [comment] 2020-10-30 11:55
I am newly in Flutter. I want to use webview in my flutter application. I refer

https://pub.dev/packages/webview_flutter
https://pub.dev/packages/iwebview_flutter
For intercepting css, js, json request from web view. This is nicely working with Android . But in IOS , can’t intercept all request. Problem in NSURLProtocol using with WKWebview.

When I use NSURLProtocol then I can not be login with my website. And if commented this code from file(mention in below) then everything nicely work but I can’t get intercept request.

When you open GitHub from both url you can find this file under project directory

WebViewFlutterPlugin.m

Path - Projectfolder/ios/Classes/WebViewFlutterPlugin.m

[NSURLProtocol registerClass:[FlutterNSURLProtocol class]];
[NSURLProtocol wk_registerScheme:@"http"];
[NSURLProtocol wk_registerScheme:@"https"];
When I adding Those line in WebViewFlutterPlugin.m then navigation or authenticate url not working in web view. When I remove those line from WebViewFlutterPlugin.m then shouldInterceptRequest not working. What can I do ?

It’s happen only for IOS.

**Comment by TahaTesser** [comment] 2020-10-30 15:03
Hi @gayatri2610 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by gayatri2610** [comment] 2020-10-31 07:51
> flutter doctor -v

macbook@MACBOOKs-MacBook-Pro webview_flutter-master 2 % flutter doctor -v          
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.22.2 at /Users/macbook/flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to
      that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[!] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 47DC8894-6431-42CF-B30B-3479E63E0CB4 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 3 categories.

**Comment by gayatri2610** [comment] 2020-10-31 07:52
name: webview_flutter_example
description: Demonstrates how to use the webview_flutter plugin.

version: 1.0.3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
    - assets/css/jianshu.css
    - assets/google.png
    - assets/baidu.png

**Comment by gayatri2610** [comment] 2020-10-31 08:10
Even i can't Signin with Google.
when open google from there 

https://pub.dev/packages/webview_flutter

**Comment by TahaTesser** [comment] 2020-11-02 08:57
Hi @gayatri2610
So what I understand so far 
You wanted to intercept HTTP requests but you couldn't so you modified source code and then you can't log in anywhere including GitHub and Google, Is this right? 
Please don't modify the source code for the issue, it doesn' look like this is supported in the plugin yet 

Duplicate of https://github.com/flutter/flutter/issues/27896

**Comment by gayatri2610** [comment] 2020-11-02 12:23
Ok . But how can i achieve intercept HTTP requests in flutter ios .
Plugin working no doubt but what we have option.

**Comment by TahaTesser** [comment] 2020-11-02 14:45
Hi @gayatri2610 
This would be fixed by https://github.com/flutter/flutter/issues/27896
Closing as duplicate of https://github.com/flutter/flutter/issues/27896

**Closed by TahaTesser** 2020-11-02 14:45 UTC
Labels: in triage
