### ISSUE TITLE
[Impeller] font-icons rendering issue

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#118615] opened 2023-01-17 12:45 UTC
I have found out an issue with rendering font-icons.
Tested it on master 3.7.0-15.0.pre.16, ios 16.1, iphone 13 pro.

## Steps to Reproduce

Sample repo available here, required resources are inside assets folder.
https://github.com/delfme/impeller-font-icons

**Main.dart**

```
import 'package:flutter/material.dart';
import 'package:impeller_issues/app_icons.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        fontFamily: 'Poppins',
      ),
      home: const MyHomePage(title: 'Font-icons rendering issue'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [

                const Padding(
                  padding: EdgeInsets.all(8.0),
                  child: Icon(
                    AppIcons.navbar_stories_sel,
                    size: 35.0,
                  ),
                ),
                const Padding(
                  padding: EdgeInsets.all(8.0),
                  child: Icon(
                    AppIcons.navbar_instant_sel,
                    size: 35.0,
                  ),
                ),
                const Padding(
                  padding: EdgeInsets.all(8.0),
                  child: Icon(
                    AppIcons.search,
                    size: 35.0,
                  ),
                ),
                const Padding(
                  padding: EdgeInsets.all(8.0),
                  child: Icon(
                    AppIcons.activity,
                    size: 35.0,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

**Expected results:**
This is the correct rendering of sample font-icons, there is no issue if Impeller is not enabled.
![IMG_good](https://user-images.githubusercontent.com/53510751/212901134-8e21e860-c753-4781-8f66-b87828d1260a.PNG)

**Actual results:**
Font-icons are rendered wrongly when Impeller is enabled, they look ticker and not sharp.
![IMG_bad](https://user-images.githubusercontent.com/53510751/212901258-f3e393bc-0a1e-4003-8e9c-58766ef784b8.PNG)

**Flutter doctor:**
 [✓] Flutter (Channel master, 3.7.0-15.0.pre.16, on macOS 12.2 21D49 darwin-arm64, locale en-IT) [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0) ✗ cmdline-tools component is missing Run path/to/sdkmanager --install "cmdline-tools;latest" See https://developer.android.com/studio/command-line for more details. ✗ Android license status unknown. Run flutter doctor --android-licenses to accept the SDK licenses. See https://flutter.dev/docs/get-started/install/macos#android-setup for more details. [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.2) [✓] Connected device (3 available) [✓] HTTP Host Availability

**Comment by delfme** [comment] 2023-01-17 12:46
I might be wrong, but maybe this issue is somehow related to https://github.com/flutter/flutter/issues/118614

**Comment by darshankawar** [comment] 2023-01-18 06:23
1. With impeller:

<img width="265" alt="Screenshot 2023-01-18 at 11 50 06 AM" src="https://user-images.githubusercontent.com/67046386/213099383-9c0ee5f4-d66f-4d49-8c51-3f49a9be210c.png">

2. Without impeller:

<img width="239" alt="Screenshot 2023-01-18 at 11 51 31 AM" src="https://user-images.githubusercontent.com/67046386/213099386-b4d165ff-59e7-4934-a22c-81f35e610468.png">

I don't see much of a difference @delfme 
I tried on iOS simulator (iPhone 13, OS 15.2)

**Comment by delfme** [comment] 2023-01-18 06:58
Hi @darshankawar it seems issue occurs only on real device. I tested on ios 15.2 simulator and it doesnt occur there also for me

**Comment by darshankawar** [comment] 2023-01-18 13:08
I see, yes, noticeable difference as reported running on iPhone 6s.

<details>
<summary> master flutter doctor -v </summary>

```

[!] Flutter (Channel master, 3.7.0-22.0.pre.9, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.7.0-22.0.pre.9 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 780563ce05 (4 hours ago), 2023-01-18 09:55:33 +0900
    • Engine revision f790304409
    • Dart version 3.0.0 (build 3.0.0-122.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by jonahwilliams** [comment] 2023-01-18 21:06
Thanks for the report, we're tracking this issue in the following bug. (Font-icons use the same codepath as regular fonts)

Duplicate of https://github.com/flutter/flutter/issues/117428

**Closed by jonahwilliams** 2023-01-18 21:06 UTC
Labels: platform-ios, engine, has reproducible steps, impeller, found in release: 3.7

**Comment by jonahwilliams** [comment] 2023-01-18 22:42
Sorry, should probably be https://github.com/flutter/flutter/issues/118613 . These are the same issue
