### ISSUE TITLE
Text input "copy", "paste" window is overflowing

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#36005] opened 2019-07-11 19:57 UTC
An image says more than words:

![device-2019-07-11-165008](https://user-images.githubusercontent.com/1146982/61080764-2804cc80-a3fc-11e9-843d-6e545da283f1.png)

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [versÃ£o 10.0.17763.615], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

```

**Comment by justinmc** [comment] 2019-07-19 15:27
I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/35826.  Thanks for posting this though, you're right this is a bug, and it's good to know that Portuguese locales are seeing this too.

**Closed by justinmc** 2019-07-19 15:27 UTC
Labels: f: material design, framework
