### ISSUE TITLE
ParagraphTest.InlinePlaceholderLongestLine flaky on engine LUCI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#64256] opened 2020-08-20 15:54 UTC
This test has flaked 2-3 days in a row, closing the engine tree.

```
[ RUN      ] ParagraphTest.InlinePlaceholderLongestLine
../../flutter/third_party/txt/tests/paragraph_unittests.cc:1483: Failure
Value of: paragraph->longest_line_ >= 50
  Actual: false
Expected: true
```

Marking P1 since this is closing the tree and affecting rolls. Provisionally assigning @jason-simmons to investigate, but feel free to reach out to others as needed.

**Comment by LongCatIsLooong** [comment] 2020-08-20 18:21
Revert https://github.com/flutter/engine/pull/20370/files?

**Comment by jason-simmons** [comment] 2020-08-20 20:43
I'm unable to reproduce the `ParagraphTest.InlinePlaceholderLongestLine` failure.

The test works as expected in local Linux and Mac environments.  I also tried copying a locally built binary to a LUCI bot and running it over ssh.  But the test also consistently succeeds when run in that setup.

**Comment by zanderso** [comment] 2020-08-20 20:56
The change is reverted. The tree should hopefully be opening back up soon. I'm going to drop the priority of this and assign @LongCatIsLooong to investigate this before relanding.

**Comment by LongCatIsLooong** [comment] 2020-08-20 23:44
@jason-simmons pointed out `is_ghost_` was not initialized in the constructor. Opened a test PR and will try rerunning it for 10 times to see if it's still flaky. Will request review if it passes all 10 times.

**Comment by zanderso** [comment] 2020-08-21 01:16
> @jason-simmons pointed out `is_ghost_` was not initialized in the constructor..

@gaaclarke Can the linter catch things like this? Does/Should the linter run on `third_party/txt` since we own it?

**Comment by chinmaygarde** [comment] 2020-08-24 18:09
The merged PR has landed.

**Closed by chinmaygarde** 2020-08-24 18:09 UTC
Labels: P3, customer: product, engine, team, team: flakes
