### ISSUE TITLE
Pigeon: add support for generics

### ISSUE THREAD

**Issue by matejdro** [flutter/flutter#66445] opened 2020-09-23 12:33 UTC
## Use case

Being able to use generics inside pigeons would further the whole "type-safe" aspect of pigeons

## Proposal

Attempting to process following class widh pigeon:

```dart
class MyClass {
  String someProperty;
}

class ClassWithList {
  List<MyClass> listOfMyClasses;
}

@HostApi()
abstract class TestApi {
  void provideList(ClassWithList list);
}
```

Will result in MyClass being ommited as unused and generated `ClassWithList` will only contain List instance without type data:

```dart
class ClassWithList {
  List listOfMyClasses;
  // ignore: unused_element
  Map<dynamic, dynamic> _toMap() {
    final Map<dynamic, dynamic> pigeonMap = <dynamic, dynamic>{};
    pigeonMap['listOfMyClasses'] = listOfMyClasses;
    return pigeonMap;
  }
  // ignore: unused_element
  static ClassWithList _fromMap(Map<dynamic, dynamic> pigeonMap) {
    if (pigeonMap == null){
      return null;
    }
    final ClassWithList result = ClassWithList();
    result.listOfMyClasses = pigeonMap['listOfMyClasses'];
    return result;
  }
}
```

@gaaclarke

**Comment by gaaclarke** [comment] 2020-09-23 13:15
duplicate of https://github.com/flutter/flutter/issues/63468

**Closed by gaaclarke** 2020-09-23 13:15 UTC
Labels: pigeon, proposal, severe: new feature, tool
