### ISSUE TITLE
testDismissedFlutterViewControllerNotRespondingToApplicationLifecycle is flaky

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#40817] opened 2019-09-19 04:36 UTC
/cc @xster 

test in question: [AppLifecycleTests.m#L43](https://github.com/flutter/engine/blob/d03582d183b1e4ab7fb82607366471f46a97f2e0/testing/scenario_app/ios/Scenarios/ScenariosTests/AppLifecycleTests.m#L43)

logs:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8901930194060398832/+/steps/Scenario_App_Unit_Tests/0/stdout

and 

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8901925738100649952/+/steps/Scenario_App_Unit_Tests/0/stdout

Both of these happened on changes completely unrelated to ios, and passed on subsequent changes also unrelated to ios.

**Comment by xster** [comment] 2019-09-19 04:40
lol, the output just straight up says test crashed. I haven't seen this one before. Skipping SG

**Comment by goderbauer** [comment] 2020-02-19 00:35
The test is still marked as skipped.

/cc @xster @gaaclarke Any chance you can take a look at this flake?

**Comment by zanderso** [comment] 2021-04-28 20:05
From triage: @dnfield were you able to find out anything more about this test? I see it is still skipped.

**Comment by dnfield** [comment] 2021-04-28 20:26
I'm not very familiar with this test.

**Comment by gaaclarke** [comment] 2021-04-28 20:29
I did find a problem in the tests that was causing some tests to flake.  I fixed it here: https://github.com/flutter/engine/commit/27bf114b861e3bf7a95aef5b90e14e0206d78146

After that landed there are potentially things that are marked as flakey that shouldn't be flakey anymore.  TLDR a test was leaking an object because of OCMock weirdness that was responding to notifications still.

**Comment by zanderso** [comment] 2021-04-28 20:46
@gaaclarke Could you take a quick pass over the skipped tests that are related to the fix, and re-enable them, or file issues to re-enable them?

**Comment by gaaclarke** [comment] 2021-04-28 20:53
There is no quick pass probably since there is no clear way to know if that leak was causing the flake that caused a given test to be disabled.  Someone would have to disable them one by one and run the tests ~1000 times to make sure it doesn't flake anymore.  I'm willing to do it but I'll have to find some time in my schedule for probably a half day of mind numbing tedium... unless we find a way to automate it, hmm that isn't a bad idea.  It would even be cool if it ran automatically as part of CI and issued an error if a test is marked skip but it passes and isn't flakey.

**Comment by dnfield** [comment] 2021-04-28 21:24
If we think it's fixed, can we just re-enable it and re-skip it if it starts flaking again?

**Comment by gaaclarke** [comment] 2021-04-28 21:31
The problem is I don't think it's fixed, I think it's possible that it's fixed because the thing I changed had wild unintended consequences that leaked into other tests and since the test order is randomized its impossible to say without testing it out wether it is fixed or not.

**Comment by gaaclarke** [comment] 2021-04-28 21:31
Testing this one test isn't a problem, it just becomes a problem if we want to ferret out all the potential issues that got fixed from that one change.

**Comment by zanderso** [comment] 2021-04-28 23:02
Is this problem just limited to the Scenario tests, or could other tests have been affected as well?

**Comment by gaaclarke** [comment] 2021-04-28 23:32
Ugh, I didn't realize this was a scenario app test.  Ignore everything I said, my fix was for the unit tests.  They look similar, sorry.

**Comment by zanderso** [comment] 2021-04-29 15:58
@gaaclarke To clarify, you're saying the fix you landed in https://github.com/flutter/engine/commit/27bf114b861e3bf7a95aef5b90e14e0206d78146 probably doesn't affect the disabled test that this issue is about?

**Comment by gaaclarke** [comment] 2021-04-29 16:31
@zanderso That's correct.

**Comment by chinmaygarde** [comment] 2021-07-28 21:57
Closing as duplicate of https://github.com/flutter/flutter/issues/69438

**Closed by chinmaygarde** 2021-07-28 21:57 UTC
Labels: P4, a: tests, engine, passed first triage, platform-ios, severe: disabled test, team: flakes
