### ISSUE TITLE
[ios] text disappear when the app is switched to the foreground in the background for a long time

### ISSUE THREAD

**Issue by Mauiie** [flutter/flutter#70079] opened 2020-11-09 08:33 UTC
## All the text on the iOS device disappeared, when the app is switched to the foreground in the background for a long time.

My application is a complete Flutter application. Recently, some customers reported that when the application is switched from the background to the foreground, the text on the entire page disappears, but you can still click to use it. 
It is difficult for me to reproduce it, but my colleagues will inadvertently have such a situation.
In addition, there is no such problem on Android devices.

I hope you can try or extrapolate it.
Thanks.

Here is an abnormal screenshot and a normal screenshot for reference:
(Ignore the background picture at the top bar, I didn't set the test environment)
<img src="https://user-images.githubusercontent.com/11786490/98514734-ebbdd680-22a4-11eb-84e8-326529b637c3.jpeg" width = "200" height = "400"  align=center />
<img src="https://user-images.githubusercontent.com/11786490/98515066-730b4a00-22a5-11eb-80d3-9c4d62b3c8f9.png" width = "200" height = "400" alt="" align=center />

## Steps to Reproduce
It is difficult for me to reproduce. The approximate steps to reproduce are:

1. The application is used normally for a period of time,
2. Put the application in the background and leave it alone for a long time (such as one night or longer)
3. Then open the app from the background.

**Expected results:** 

**Actual results:** 

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.22.3 at /Users/wangxin/Library/flutter/flutter
    • Framework revision 8874f21e79 (10 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wangxin/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • 853F59FD-C617-4A56-A3B3-11022F1CBFED • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)


```

</details>

**Comment by pedromassangocode** [comment] 2020-11-09 10:44
Hi @Mauiie 
Thanks for filling this issue. It would help if you could provide any minimal reproducible code.

@dnfield this seems similar to https://github.com/flutter/flutter/issues/64558
Cc @csells

**Comment by dnfield** [comment] 2020-11-09 16:46
This is almost certainly a duplicate of https://github.com/flutter/flutter/issues/64558, closing as duplicate.

/cc @chinmaygarde who is going to be looking at that some more.

**Closed by dnfield** 2020-11-09 16:46 UTC
Labels: a: production, a: typography, engine, framework, platform-ios
