### ISSUE TITLE
Flutter web can't  load gif?

### ISSUE THREAD

**Issue by chkkassd** [flutter/flutter#39053] opened 2019-08-22 13:14 UTC
I meet a problem, I'm a newer in flutter web, I find the code below works well in flutter, but it dosen't work in flutter web. Somebody can help me?
```dart
class testGif extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Image.asset('drink_beer.gif'),
      ),
    );
  }
}
```

**Comment by jld3103** [comment] 2019-08-22 13:24
A lot of things don't simply work on web. Like [svg](https://github.com/flutter/flutter/issues/37749).
Maybe that's another thing that doesn't work on web out of the box.

**Comment by ferhatb** [comment] 2019-08-22 17:07
Note: TODO-> Code needs to switch to DomCanvas to enable gif. Current code draws Image asset into bitmap canvas.

**Comment by ferhatb** [comment] 2019-08-23 16:53
Duplicate of https://github.com/flutter/flutter/issues/33618

**Closed by ferhatb** 2019-08-23 16:53 UTC
Labels: ☸ platform-web
