### ISSUE TITLE
Web view on flutter 3.0.1 with stretched out height and hybrid composition crashes on Android

### ISSUE THREAD

**Issue by boriszv** [flutter/flutter#104986] opened 2022-05-30 20:14 UTC
I'm having an issue trying to render a web view to it's full content height on Android using flutter 3.0.1. I am submitting this issue on the flutter repository because this seems to be an issue with the PlatformView implementation on Android on flutter >=3, because this code sample works fine on flutter 2.10.5 with hybrid composition. Also I tried both the `webview_flutter` and `flutter_inappwebview` packages and I am getting the same results.

## Steps to Reproduce

1. Execute `flutter run` on the code sample on Android 
2. The app will open, render a Web View for a second, stretch the content out and throw the exception below

**Expected results:** Rendered web view with the given height of the content

**Actual results:** App crashing

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(body: TestWebView()),
    );
  }
}

class TestWebView extends StatefulWidget {
  const TestWebView({
    Key? key,
    this.pushThankYouPage,
  }) : super(key: key);

  final Function()? pushThankYouPage;
  @override
  State<TestWebView> createState() => TestWebViewState();
}

class TestWebViewState extends State<TestWebView> {
  int? contentHeight;

  @override
  Widget build(BuildContext context) {
    const url = 'https://www.smashingmagazine.com/2017/05/long-scrolling/';

    final height = contentHeight?.toDouble() ?? 1000;

    return ListView(
      children: [
        SizedBox(
          height: height,
          child: InAppWebView(
            initialUrlRequest: URLRequest(url: Uri.parse(url)),
            initialOptions: InAppWebViewGroupOptions(
              crossPlatform: InAppWebViewOptions(
                disableHorizontalScroll: true,
                horizontalScrollBarEnabled: false,
                useShouldOverrideUrlLoading: true,
                useOnLoadResource: true,
              ),
              android: AndroidInAppWebViewOptions(
                useHybridComposition: true,
              ),
            ),
            onLoadStop: _onLoadStop,
          ),
        ),
        // Below content to show.
        const Text('Text below'),
      ],
    );
  }

  Future<void> _onLoadStop(InAppWebViewController controller, Uri? uri) async {
    await Future<dynamic>.delayed(const Duration(milliseconds: 500));
    final height = await controller.getContentHeight();
    debugPrint('TestWebView height: $height');
    setState(() {
      contentHeight = height;
    });
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```[   +4 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 
[   +1 ms] R Hot restart.
[  +13 ms] h List all available interactive commands.
[   +6 ms] d Detach (terminate "flutter run" but leave application running).
[   +2 ms] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[   +1 ms]  Running with sound null safety 
[   +3 ms] An Observatory debugger and profiler on RMX2155 is available at: http://127.0.0.1:56866/0KfwVygK4kM=/
[ +304 ms] W/ample.wv_test_( 5976): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
[   +1 ms] W/ample.wv_test_( 5976): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
[  +14 ms] W/ample.wv_test_( 5976): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
[   +4 ms] I/System.out( 5976): recordForce value 3
[   +2 ms] W/ample.wv_test_( 5976): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
[   +1 ms] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[   +1 ms] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[        ] I/GED     ( 5976): [GT]_get_procNameprocess pid(5976)
[        ] I/GED     ( 5976): [GT]_getprocess name(com.example.wv_test_3)
[        ] I/ample.wv_test_( 5976): [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
[   +1 ms] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[   +1 ms] I/chatty  ( 5976): uid=10668(com.example.wv_test_3) Chrome_InProcGp identical 2 lines
[   +1 ms] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[   +1 ms] I/BufferQueueConsumer( 5976): [](id:175800000000,api:0,p:-1,c:5976) connect(): controlledByApp=true
[   +1 ms] D/Surface ( 5976): lockHardwareCanvas
[   +5 ms] I/BufferQueueProducer( 5976): [SurfaceTexture-0-5976-0](id:175800000000,api:1,p:5976,c:5976) connect(): api=1 producerControlledByApp=true
[   +4 ms] E/ion     ( 5976): ioctl c0044901 failed with code -1: Invalid argument
[   +2 ms] W/cr_media( 5976): Requires BLUETOOTH permission
[   +1 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[   +9 ms] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[   +2 ms] I/GED     ( 5976): [GT]_get_procNameprocess pid(5976)
[        ] I/GED     ( 5976): [GT]_getprocess name(com.example.wv_test_3)
[   +2 ms] I/ample.wv_test_( 5976): [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
[        ] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[  +16 ms] I/chatty  ( 5976): uid=10668(com.example.wv_test_3) Chrome_InProcGp identical 2 lines
[   +1 ms] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[  +10 ms] E/Parcel  ( 5976): Reading a NULL string not supported here.
[ +132 ms] The Flutter DevTools debugger and profiler on RMX2155 is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:56866/0KfwVygK4kM=/
[        ] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[ +165 ms] I/ample.wv_test_( 5976): ProcessProfilingInfo new_methods=1674 is saved saved_to_disk=1 resolve_classes_delay=5000
[   +6 ms] D/Surface ( 5976): lockHardwareCanvas
[  +11 ms] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[  +31 ms] I/chatty  ( 5976): uid=10668(com.example.wv_test_3) RenderThread identical 8 lines
[   +4 ms] E/libEGL  ( 5976): Invalid file path for libcolorx-loader.so
[   +1 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[  +19 ms] D/Surface ( 5976): lockHardwareCanvas
[  +16 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[+1349 ms] D/Surface ( 5976): lockHardwareCanvas
[ +495 ms] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[  +26 ms] I/chatty  ( 5976): uid=10668(com.example.wv_test_3) RenderThread identical 5 lines
[   +3 ms] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[   +2 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[   +5 ms] I/Choreographer( 5976): Skipped 31 frames!  The application may be doing too much work on its main thread.
[  +15 ms] D/Surface ( 5976): lockHardwareCanvas
[   +2 ms] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[   +1 ms] I/chatty  ( 5976): uid=10668(com.example.wv_test_3) RenderThread identical 2 lines
[   +9 ms] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[        ] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[  +23 ms] D/Surface ( 5976): lockHardwareCanvas
[   +7 ms] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[   +3 ms] I/chatty  ( 5976): uid=10668(com.example.wv_test_3) RenderThread identical 6 lines
[        ] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[        ] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[   +2 ms] D/Surface ( 5976): lockHardwareCanvas
[   +1 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[ +213 ms] D/Surface ( 5976): lockHardwareCanvas
[   +2 ms] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[   +2 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[ +279 ms] I/flutter ( 5976): TestWebView height: 19949
[  +99 ms] D/Surface ( 5976): lockHardwareCanvas
[   +2 ms] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[  +18 ms] I/chatty  ( 5976): uid=10668(com.example.wv_test_3) RenderThread identical 5 lines
[   +1 ms] E/GPUAUX  ( 5976): [AUX]GuiExtAuxCheckAuxPath:589: Null anb
[   +1 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[   +3 ms] D/Surface ( 5976): lockHardwareCanvas
[  +65 ms] E/chromium( 5976): [ERROR:skia_output_surface_impl.cc(979)] 
[        ] E/chromium( 5976):   surface_size=1080x59847
[        ] E/chromium( 5976):   format=7
[        ] E/chromium( 5976):   color_type=4
[        ] E/chromium( 5976):   backend_format.isValid()=1
[        ] E/chromium( 5976):   backend_format.backend()=0
[        ] E/chromium( 5976):   backend_format.asGLFormat()=1
[   +1 ms] E/chromium( 5976):   backend_format.asVkFormat()=0
[        ] E/chromium( 5976):   backend_format.asVkFormat() vk_format=0
[        ] E/chromium( 5976):   surface_origin=1
[        ] E/chromium( 5976):   willGlFBO0=1
[        ] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[  +16 ms] D/Surface ( 5976): lockHardwareCanvas
[  +84 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[  +28 ms] E/ample.wv_test_( 5976): [SurfaceTexture-0-5976-0] bindTextureImage: error binding external image: 0x501
[   +2 ms] E/flutter ( 5976): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
[        ] E/flutter ( 5976):   at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
[        ] E/flutter ( 5976):   at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
[        ] E/flutter ( 5976):   at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
[        ] E/flutter ( 5976): 
[        ] F/flutter ( 5976): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1322)] Check failed: fml::jni::CheckException(env). 
[  +80 ms] D/Surface ( 5976): lockHardwareCanvas
[   +2 ms] E/FrameEvents( 5976): updateAcquireFence: Did not find frame.
[        ] D/Surface ( 5976): lockHardwareCanvas
[ +330 ms] F/libc    ( 5976): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6022 (1.raster), pid 5976 (ample.wv_test_3)
[ +164 ms] Process name is com.example.wv_test_3, not key_process
[   +2 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[   +1 ms] Build fingerprint: 'realme/RMX2155EEA/RMX2155L1:11/RP1A.200720.011/1649169972136:user/release-keys'
[   +1 ms] Revision: '0'
[   +1 ms] ABI: 'arm64'
[   +4 ms] Timestamp: 2022-05-30 22:11:48+0200
[   +1 ms] pid: 5976, tid: 6022, name: 1.raster  >>> com.example.wv_test_3 <<<
[   +1 ms] uid: 10668
[        ] signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
[   +2 ms] Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1322)] Check failed: fml::jni::CheckException(env). 
[   +1 ms] '
[   +2 ms]     x0  0000000000000000  x1  0000000000001786  x2  0000000000000006  x3  0000007c568c1f30
[   +9 ms]     x4  0000007d54ea0000  x5  0000007d54ea0000  x6  0000007d54ea0000  x7  0000000009be451a
[   +2 ms]     x8  00000000000000f0  x9  0000007d51b698d8  x10 ffffff80fffffbdf  x11 0000000000000001
[   +1 ms]     x12 0000007c568c0d40  x13 000000000000007e  x14 0000007c568c0df0  x15 00005367dcec641f
[        ]     x16 0000007d51c2a7e0  x17 0000007d51c09950  x18 0000007c55330000  x19 00000000000000ac
[        ]     x20 0000000000001758  x21 00000000000000b2  x22 0000000000001786  x23 00000000ffffffff
[        ]     x24 b400007cbd651780  x25 0000000000000000  x26 0000000000000001  x27 0000000000000055
[        ]     x28 0000000000000001  x29 0000007c568c1fb0
[        ]     lr  0000007d51bbc944  sp  0000007c568c1f10  pc  0000007d51bbc974  pst 0000000000001000
[   +4 ms] backtrace:
[   +1 ms]       #00 pc 0000000000078974  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180) (BuildId: 554cb674fad07588ff08040bb89924c9)
[   +1 ms]       #01 pc 000000000156f94c  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +2 ms]       #02 pc 0000000001594534  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #03 pc 000000000157b3d0  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #04 pc 00000000015710dc  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #05 pc 0000000001570f2c  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #06 pc 00000000018a5188  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #07 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #08 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #09 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #10 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #11 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +9 ms]       #12 pc 00000000018a0274  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +3 ms]       #13 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #14 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #15 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #16 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #17 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +3 ms]       #18 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #19 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #20 pc 00000000018a4188  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #21 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #22 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #23 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #24 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #25 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #26 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #27 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #28 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #29 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #30 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #31 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #32 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #33 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #34 pc 00000000018a54e4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #35 pc 00000000018a0f90  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[  +13 ms]       #36 pc 00000000018a2f74  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #37 pc 000000000189d810  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #38 pc 00000000018bd2b4  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #39 pc 00000000018bbfd8  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +3 ms]       #40 pc 00000000018bbf18  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #41 pc 00000000018c8964  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #42 pc 0000000001595230  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #43 pc 000000000159aad8  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #44 pc 000000000001a064  /system/lib64/libutils.so (android::Looper::pollInner(int)+916) (BuildId: b37fec3a059fd02e261d56e0be089e47)
[        ]       #45 pc 0000000000019c68  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: b37fec3a059fd02e261d56e0be089e47)
[        ]       #46 pc 0000000000012d3c  /system/lib64/libandroid.so (ALooper_pollOnce+100) (BuildId: f9886c0110f84b5b69dbaf366a7169ab)
[   +1 ms]       #47 pc 000000000159aa60  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #48 pc 0000000001595178  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[        ]       #49 pc 0000000001599070  /data/app/~~ila24n0E8YIqZ_2aI4MQMw==/com.example.wv_test_3-tv07lBGPkn3bddjjYmGmWg==/lib/arm64/libflutter.so (BuildId: 1a0a352c6b73760081fffa780cfe1e18e75259c2)
[   +1 ms]       #50 pc 00000000000db188  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 554cb674fad07588ff08040bb89924c9)
[   +1 ms]       #51 pc 000000000007a9d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 554cb674fad07588ff08040bb89924c9)
[ +502 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device.
[   +4 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.wv_test_3/code_cache/wv_test_3BOVSPY/wv_test_3/)
[ +272 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +6 ms] "flutter run" took 53.335ms.
[ +124 ms] ensureAnalyticsSent: 119ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1706], locale sr-Latn-RS)
    • Flutter version 3.0.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (11 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\boris\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.3)
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.67.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • RMX2155 (mobile)  • GADIU8HEI7KFSOT8 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-05-31 07:21
Hello @boriszv. This issue seems to be a duplicate of #104889. I'm closing this issue as a duplicate. You can follow up on the issue mentioned. If you disagree, please comment and we can reopen it.

**Closed by exaby73** 2022-05-31 07:21 UTC
Labels: in triage
