### ISSUE TITLE
app stuck on splash screen for android  in release mode but good in debug mode

### ISSUE THREAD

**Issue by jinjilynn** [flutter/flutter#99206] opened 2022-02-26 14:33 UTC
```dart
SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [])
```
when i remove the code above, the problem  is gone

**Comment by jinjilynn** [comment] 2022-02-26 14:35
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6 20G165 darwin-x64, locale
    en-CN)
[!] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc2)
    ✗ Android SDK file not found:
      /Users/jinjilin/Library/Android/sdk/platforms/android-32/android.jar.
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)

**Comment by danagbemava-nc** [comment] 2022-02-28 08:29
Duplicate of #98973

**Closed by danagbemava-nc** 2022-02-28 08:29 UTC
Labels: in triage
