### ISSUE TITLE
bug : selection icon and popup menu is over on appbar

### ISSUE THREAD

**Issue by DJafari** [flutter/flutter#55555] opened 2020-04-24 13:44 UTC
![Screenshot_1587736411](https://user-images.githubusercontent.com/1963047/80220198-bcbd7b80-8658-11ea-87d1-7b7c4260fe11.png)

after scroll down :

![Screenshot_1587736416](https://user-images.githubusercontent.com/1963047/80220223-c2b35c80-8658-11ea-9cc1-9aa3ab82fe48.png)

p.s : wow what a round issue number 😁 #55555

**Comment by DJafari** [comment] 2020-04-24 13:52
@iapicca 

```
[✓] Flutter (Channel master, v1.18.0-8.0.pre.4, on Mac OS X 10.15.4 19E287,
    locale en-US)
    • Flutter version 1.18.0-8.0.pre.4 at /Volumes/My/SDK/Flutter
    • Framework revision f582246af6 (17 hours ago), 2020-04-23 22:29:02 +0200
    • Engine revision 8fff8da38d
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Volumes/My/SDK/Android
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Volumes/My/SDK/Android
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9
      (API 28) (emulator)
    • macOS                        • macOS         • darwin-x64  • Mac OS X
      10.15.4 19E287

• No issues found!
```

and reproducible code :

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    theme: ThemeData(
      primarySwatch: Colors.blue,
    ),
    home: Scaffold(
      appBar: AppBar(),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              TextFormField(
                initialValue: "TEST",
              ),
              SizedBox(
                height: 1000,
              ),
            ],
          ),
        ),
      ),
    ),
  ));
}
```
just select the text and scroll down

**Comment by DJafari** [comment] 2020-04-24 14:01
i think it's related to #55547

**Comment by TahaTesser** [comment] 2020-04-27 09:22
duplicate of [#55547](https://github.com/flutter/flutter/issues/55547)

**Closed by TahaTesser** 2020-04-27 09:22 UTC
Labels: in triage
