### ISSUE TITLE
Crash in impeller::Tessellator::TessellateConvex(impeller::Path const&, float) on iOS

### ISSUE THREAD

**Issue by ydotmalik** [flutter/flutter#150967] opened 2024-06-27 23:20 UTC
### Steps to reproduce

Have not been able to produce minimal code to reproduce issue. App makes heavy use of Canvas.

### Expected results

iOS does not crash

### Actual results

Crash on iOS 17.5 on both simulator and real device. This is the error at the instruction where the app crashes:
```
io.flutter.1.raster (11): EXC_BAD_ACCESS (code=1, address=0x10274fff8)
```

Crash happens on iPhone 12 device running iOS 17.5.1 and on iPhone 15 simulator running iOS 17.5.

App does not crash on Android, either simulator or real device.

In order to workaround this issue, I set this in Info.plist:
```
	<key>FLTEnableImpeller</key>
	<false />
```

### Code sample

<details open><summary>Code sample</summary>
Have not been able to produce minimal code to reproduce issue. App makes heavy use of Canvas.

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Stack trace in XCode:
<img width="1315" alt="image" src="https://github.com/flutter/flutter/assets/29930828/446904cf-ae2d-4d18-a416-2dddac908f04">

</details>

### Logs

<details open><summary>Logs</summary>

I am debugging using VS Code. No extra commands were executed.

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)            
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by jonahwilliams** [comment] 2024-06-28 03:20
Duplicate of https://github.com/flutter/flutter/issues/149309

**Closed by jonahwilliams** 2024-06-28 03:20 UTC
