### ISSUE TITLE
Text is rendering incorrectly on web for some Android devices (CanvasKit)

### ISSUE THREAD

**Issue by doppio** [flutter/flutter#84530] opened 2021-06-13 17:49 UTC
Two users of my web app have reported an issue on Android where text is partially cut off or not displayed at all.

**Expected results:**
This is how the app's homepage should look. This is what the vast majority (thousands) of Android users see.

<img src="https://user-images.githubusercontent.com/1127641/121817021-bd85e800-cc33-11eb-9682-959af455cbe2.png" width="350px"/>

**Actual results:**
This is what the two users who have reported the issue see.

<img src="https://user-images.githubusercontent.com/1127641/121817030-cecef480-cc33-11eb-9095-96bc9359cbee.png" width="350px"/>

Unfortunately, I can't reproduce the issue myself, and I'm posting here in case anyone else has seen a similar issue or knows what might be going on here.

**Additional details:**
Both users who reported the issue were using Chrome on Android. One device is a Samsung Galaxy S8 and the other is an Asus ZenFone 5. I'm using the CanvasKit renderer, and these are simple Text widgets using the "Inter" font TTF, downloaded from Google Fonts.

The app was built using the Flutter Dev channel:
```
> flutter --version
Flutter 2.3.0-16.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision fa5883b78e (3 weeks ago) • 2021-05-21 13:04:03 -0700
Engine • revision 2f067fc4c5
Tools • Dart 2.14.0 (build 2.14.0-136.0.dev)
```

**Comment by TahaTesser** [comment] 2021-06-14 12:28
Hi @doppio 
Thanks for filing the issue.
Is the app explicitly built for `canvaskit`? Can you please share the command you used for the web? 
Auto uses HTML on mobile browsers, see https://flutter.dev/docs/development/tools/web-renderers

**Comment by doppio** [comment] 2021-06-14 17:27
Hey @TahaTesser, yes, the app is explicitly built for CanvasKit due to several open issues with the HTML renderer that are major problems for my project:

`flutter build web --web-renderer canvaskit`

**Comment by TahaTesser** [comment] 2021-06-15 07:59
Hi @doppio 
This looks like a duplicate of https://github.com/flutter/flutter/issues/74990
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/74990
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-15 07:59 UTC
Labels: in triage
