### ISSUE TITLE
[webview_flutter] [Android] Not getting prompted for camera and microphone permissions on Android

### ISSUE THREAD

**Issue by iamongit** [flutter/flutter#125245] opened 2023-04-20 20:31 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce
Using webview_flutter: 4.1.0

I am accessing a secure url that hosts a video calling service using a javascript library. On iOS I get the prompt requesting access to Microphone and Camera and everything works as expected.

However, on my Pixel 6 I do not get any prompt and the page does not initialize as expected due to no availability of camera and microphone.Pixel is running Android 13. 

Using the url directly in chrome or flutter_custom_tabs also works as expected and I am being prompted for camera and microphone permissions.

I also tried to grant all permissions using permission handler but the actual permission needs to be for the url I'm accessing.

### Expected results

Secure url requesting access to microphone and camera.

### Actual results

No prompt for any permissions, page does not initialize as expected.

### Code sample

<details><summary>Code sample</summary>

```dart
Using the same code as available in example for the webview plugin.
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
E/AudioManager(16217): updatePortConfig port not found for handle: 14
I/AAudio  (16217): AAudioStreamBuilder_openStream() called ----------------------------------------
I/AudioStreamBuilder(16217): rate   =  48000, channels  = 2, channelMask = 0x80000003, format   = 5, sharing = SH, dir = OUTPUT
I/AudioStreamBuilder(16217): device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 128
I/AudioStreamBuilder(16217): usage  =      1, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
I/AudioStreamBuilder(16217): privacy sensitive = false, opPackageName = (null), attributionTag = (null)
I/chromium(16217): [INFO:CONSOLE(44646)] "%c2023-04-20 20:10:19.776 -05:00: INFO: VidyoClient: Execute Main Thread: VidyoClient.js:12049: VidyoCore._handleAudioContextStateChange: AudioContext state changed: running color: black", source: https://static.platform.vidyo.io/vidyoclient/webrtc/22.5.0/VidyoClient.js (44646)
D/AudioStreamInternal_Client(16217): configureDataInformation() original HW burst = 96, minMicros = 2000 => SW burst = 96
D/AAudioStream(16217): setState(s#1) from 0 to 2
I/AAudioFlowGraph(16217): configure() source format = 0x00000005, channels = 2, sink format = 0x00000005, channels = 2, useMonoBlend = 0, audioBalance = 0.000000, isExclusive 0
I/AAudio  (16217): AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#1 ----------------
D/AAudio  (16217): AAudioStream_requestStart(s#1) called --------------
D/AAudioStream(16217): setState(s#1) from 2 to 3
D/AAudio  (16217): AAudioStream_requestStart(s#1) returned 0 ---------
D/AudioStreamInternalPlay_Client(16217): callbackLoop() entering >>>>>>>>>>>>>>>
D/AudioStreamInternal_Client(16217): onEventFromServer - got AAUDIO_SERVICE_EVENT_STARTED
D/AAudioStream(16217): setState(s#1) from 3 to 4
E/AudioManager(16217): updatePortConfig port not found for handle: 14
I/AAudio  (16217): AAudioStreamBuilder_openStream() called ----------------------------------------
I/AudioStreamBuilder(16217): rate   =  48000, channels  = 2, channelMask = 0x80000003, format   = 5, sharing = SH, dir = OUTPUT
I/AudioStreamBuilder(16217): device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 128
I/AudioStreamBuilder(16217): usage  =      1, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
I/AudioStreamBuilder(16217): privacy sensitive = false, opPackageName = (null), attributionTag = (null)
I/chromium(16217): [INFO:CONSOLE(44646)] "%c2023-04-20 20:10:41.865 -05:00: INFO: VidyoClient: Execute Main Thread: VidyoClient.js:12049: VidyoCore._handleAudioContextStateChange: AudioContext state changed: running color: black", source: https://static.platform.vidyo.io/vidyoclient/webrtc/22.5.0/VidyoClient.js (44646)
D/AudioStreamInternal_Client(16217): configureDataInformation() original HW burst = 96, minMicros = 2000 => SW burst = 96
D/AAudioStream(16217): setState(s#2) from 0 to 2
I/AAudioFlowGraph(16217): configure() source format = 0x00000005, channels = 2, sink format = 0x00000005, channels = 2, useMonoBlend = 0, audioBalance = 0.000000, isExclusive 0
I/AAudio  (16217): AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#2 ----------------
D/AAudio  (16217): AAudioStream_requestStart(s#2) called --------------
D/AAudioStream(16217): setState(s#2) from 2 to 3
D/AAudio  (16217): AAudioStream_requestStart(s#2) returned 0 ---------
D/AudioStreamInternalPlay_Client(16217): callbackLoop() entering >>>>>>>>>>>>>>>
D/AudioStreamInternal_Client(16217): onEventFromServer - got AAUDIO_SERVICE_EVENT_STARTED
D/AAudioStream(16217): setState(s#2) from 3 to 4
D/AAudio  (16217): AAudioStream_requestStop(s#1) called
D/AudioStreamInternalPlay_Client(16217): callbackLoop() exiting, result = 128, isActive() = 1 <<<<<<<<<<<<<<
D/AAudioStream(16217): joinThread_l() pthread_join succeeded
D/AAudioStream(16217): setState(s#1) from 4 to 9
D/AudioStreamInternal_Client(16217): onEventFromServer - got AAUDIO_SERVICE_EVENT_STOPPED
D/AAudioStream(16217): setState(s#1) from 9 to 10
D/AAudio  (16217): AAudioStream_close(s#1) called ---------------
D/AudioStreamInternal_Client(16217): release_l(): mServiceStreamHandle = 0x0000002B
D/AAudioStream(16217): setState(s#1) from 10 to 11
D/AAudioStream(16217): setState(s#1) from 11 to 11
D/AAudioStream(16217): setState(s#1) from 11 to 12
D/AudioStreamInternal_Client(16217): ~AudioStreamInternal() 0xb4000078026a04a0 called
D/AAudioStream(16217): ~AudioStream(s#1) mPlayerBase strongCount = 2
D/AAudio  (16217): AAudioStream_close(s#1) returned 0 ---------
D/AAudio  (16217): AAudioStream_requestStop(s#2) called
D/AudioStreamInternalPlay_Client(16217): callbackLoop() exiting, result = 128, isActive() = 1 <<<<<<<<<<<<<<
D/AAudioStream(16217): joinThread_l() pthread_join succeeded
D/AAudioStream(16217): setState(s#2) from 4 to 9
D/AudioStreamInternal_Client(16217): onEventFromServer - got AAUDIO_SERVICE_EVENT_STOPPED
D/AAudioStream(16217): setState(s#2) from 9 to 10
D/AAudio  (16217): AAudioStream_close(s#2) called ---------------
D/AudioStreamInternal_Client(16217): release_l(): mServiceStreamHandle = 0x0000002C
D/AAudioStream(16217): setState(s#2) from 10 to 11
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.7.6, on macOS 13.0.1 22A400 darwin-arm64, locale en-US)
    • Flutter version 3.7.6 on channel stable at /Users/**/fvm/versions/3.7.6
    ! Warning: `flutter` on your path resolves to /Users/**/fvm/versions/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/**/fvm/versions/3.7.6. Consider adding /Users/**/fvm/versions/3.7.6/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/**/fvm/versions/stable/bin/dart, which is not inside your current Flutter SDK checkout at /Users/**/fvm/versions/3.7.6. Consider adding /Users/**/fvm/versions/3.7.6/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (7 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/**/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
    • Pixel 6 (mobile)       • 26061FDF6002DT                           • android-arm64  • Android 13 (API 33)
    • iPad mini 4 (mobile)   • 1e744661cb39ac4c909354c6c02f99a29f2bd0be • ios            • iOS 15.7.3 19H307
    • iPhone 14 Pro (mobile) • 73ACFE00-7487-4C1C-AE5C-FD88A997AB21     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by stuartmorgan** [comment] 2023-04-20 20:44
Duplicate of https://github.com/flutter/flutter/issues/78147

**Closed by stuartmorgan** 2023-04-20 20:44 UTC
