### ISSUE TITLE
Expose AssetBundle available keys

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#28464] opened 2019-02-25 15:56 UTC
When working with Asset you can declare

```
flutter:
  assets:
    - assets/
```

Would it be possible to expose keys of available resources under this asset ?

`AssetBundle.entries(String assetdir) -> Iterable<String> keys`

Thank you

**Comment by zoechi** [comment] 2019-02-25 16:21
Similar to #11477, #18898
I'm going to close as Duplicate of #18898

**Closed by zoechi** 2019-02-25 16:21 UTC
