### ISSUE TITLE
Unknown error in executing flutter command

### ISSUE THREAD

**Issue by zarub2k** [flutter/flutter#13822] opened 2018-01-01 19:33 UTC
## Steps to Reproduce

I am getting the following error whenever i execute flutter command in my terminal

## Logs
[: !=: unary operator expected

/Users/tham/softwares/flutter/bin/flutter: line 43: [: !=: unary operator expected
Downloading Material fonts...                             

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: f17d2f489794bb56)
Crash report written to /Users/tham/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment] 2018-01-01 20:38
What OS?
What shell?

**Comment by zarub2k** [comment] 2018-01-02 04:30
OS - Mac OS (Sierra)
Shell - Terminal

**Comment by arzacj** [comment] 2018-01-03 18:55
<h2>Steps to Reproduce</h2>
Same message here. Every time I run any flutter command in the terminal (iTerm2).

OS - Mac OS (Sierra 10.12.6)
Shell - -bash

<h2>Logs</h2>

$ flutter packages get<br>/Applications/flutter/bin/flutter: line 43: [: !=: unary operator expected<br>Running "flutter packages get" in some_flutter_app...  0.6s.


<p>
Get the same message in IntelliJ IDEA, for example when I run my app:
</p>
/Applications/flutter/bin/flutter: line 43: [: !=: unary operator expected
<br>Launching lib/main.dart on iPhone X in debug mode...
<br>Running pod install...
<br>Running Xcode build...
<br>    CADisplay.name = LCD;
<br>    CADisplay.deviceName = PurpleMain;
<br>    CADisplay.seed = 1;
 <br>   tags = 0;
<br>    currentMode = <FBSDisplayMode: 0x60c000091800; 375x812@3x (1125x2436/3) 60Hz p3 SDR>;
<br>    safeOverscanRatio = {0.89999997615814209, 0.89999997615814209};
<br>    nativeCenter = {562.5, 1218};
<br>    pixelSize = {1125, 2436};
 <br>   bounds = {{0, 0}, {375, 812}};
 <br>   CADisplay = <CADisplay:LCD PurpleMain>;
<br>}
<br>Syncing files to device iPhone X...

<h2>Flutter Doctor</h2>
flutter doctor
<br>
/Applications/flutter/bin/flutter: line 43: [: !=: unary operator expected
<br>
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale en-US, channel alpha)
    • Flutter at /Applications/flutter
    • Framework revision fd7853faad (4 weeks ago), 2017-12-05 16:12:55 -0800
    • Engine revision b57fca02b5
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d4cfecb1065d322d3670df7e9ec9a0cc2d4b90f0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/arzacjj/Library/Android/sdk
    • Android NDK location not configured (this optional configuration is useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
<br>

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone X                  • 78AC7581-7D4F-45D4-A142-EDD590165245 • ios         • iOS 11.2 (simulator)

**Comment by zarub2k** [comment] 2018-01-04 08:28
For the time being, I completely removed the flutter project and checked out the code again. This problem seems to be gone now. But I have no clue why I got this problem earlier :(

**Comment by jamesdlow** [comment] 2018-03-03 01:43
I still get this issue and I just installed flutter on 3rd March 2018

**Comment by Hixie** [comment] 2018-05-31 18:06
This was fixed by https://github.com/flutter/flutter/pull/15087. It was caused by some bad coding we had which would get triggered when a particular internal sentinel file got corrupted in a way that we don't really understand.

**Closed by Hixie** 2018-05-31 18:06 UTC
