### ISSUE TITLE
[shared_preferences] Allow suiteName settings for NSUserDefaults

### ISSUE THREAD

**Issue by TheManuz** [flutter/flutter#110062] opened 2022-08-23 07:26 UTC
## Use case

There are 2 issues right now that prevent me from migrating from an iOS native app:
- It's not possible to set the prefix
    - Discussed in #52544
- It's not possible to set the [suiteName](https://developer.apple.com/documentation/foundation/nsuserdefaults/1409957-initwithsuitename) for NSUserDefaults
    - Discussed here 

My native app uses different **suiteNames**, based on flavors, and I cannot read the values stored in **NSUserDefaults** because of this.

## Proposal

`SharedPreferences.getInstance();` don't let you configure **prefix** (all platforms) nor **suiteName** (iOS only).

It would be nice to be able to call
```dart
SharedPreferences(
  prefix: 'myPrefix',
  suiteName: 'mySuiteName',
);
```
(a constructor, not a static method).

I think the singleton logic should be dropped when calling the constructor, because different instances with different prefixes/suiteNames configurations might be needed.

`SharedPreferences.getInstance` should be maintained with the current configuration for retrocompatibility.

**Comment by stuartmorgan** [comment] 2022-08-25 20:25
Sorry, I forgot that we already had this filed when I asked you to file a new issue for this. Closing as a duplicate of https://github.com/flutter/flutter/issues/64739.

**Closed by stuartmorgan** 2022-08-25 20:25 UTC
Labels: new feature, platform-ios, plugin, p: first party, p: shared_preferences, proposal

**Comment by TheManuz** [comment] 2022-08-26 07:18
No problem, I should've searched before asking.

Anyway, the important thing is that the feature request has its own issue and it's tracked.
