### ISSUE TITLE
Flutter users will need a way to generate symbols for AOT Dart code

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7918] opened 2017-02-07 03:49 UTC
In order to support understanding (rare, but possible) SEGFAULT, OOM, etc, in AOT Dart code we will likely to want to support symbol generation for gen_snapshot, etc.

I don't know what the contract is for AOT dart code (is it supposed to be able to crash this way?) but it seems like this may be useful?

@a-siva may already have a bug on file for this, but I didn't find it in a quick search so here is one.

**Comment by a-siva** [comment] 2017-03-22 20:09
Is this is a duplicate of https://github.com/flutter/flutter/issues/7108 and has been addressed by the CLs that landed for https://github.com/dart-lang/sdk/issues/28785 ? Can it be closed.

**Comment by Hixie** [comment] 2017-06-08 17:24
Are we currently outputting the symbols anywhere during release builds?

**Comment by rmacnak-google** [comment] 2017-06-08 22:10
When AOT buildS as assembly instead of blobs (currently iOS and Fuchsia but not Android), we include symbols on each Dart function and DWARF debug information. The program would still work if these symbols are stripped, so you can safely do so and save them somewhere for offline symbolization.  (Cf. Issue #4287)

**Comment by a-siva** [comment] 2017-08-14 16:57
rmacnak@ can this issue be closed or are you keeping this open to track migration of android AOT builds to use assembly?

**Comment by rmacnak-google** [comment] 2017-08-14 17:52
The VM side changes are done, but there's work needed in the flutter tool.

**Comment by jonahwilliams** [comment] 2020-02-08 20:03
Superseded by work on dwarf-stack-traces/debug info and tracked in https://github.com/flutter/flutter/issues/50206

**Closed by jonahwilliams** 2020-02-08 20:03 UTC
Labels: tool
