### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by vicky-prog** [flutter/flutter#76470] opened 2021-02-21 03:22 UTC
## Command
```
flutter --quiet assemble --depfile /Users/vicky/Ecommerce/online_organic_store/build/app/intermediates/flutter/debug/flutter_build.d --output /Users/vicky/Ecommerce/online_organic_store/build/app/intermediates/flutter/debug -dTargetFile=/Users/vicky/Ecommerce/online_organic_store/lib/main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=flutter.inspector.structuredErrors%3Dtrue debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:186:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_file_system.dart:351:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:185:5)
#8      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:667:23)
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:584:5)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _runZoned (dart:async/zone.dart:1630:10)
#18     runZoned (dart:async/zone.dart:1550:10)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
```
```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.0 at /Users/Developer/flutter
    • Framework revision 840c9205b3 (7 months ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nina/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/nina/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 840c9205b344a59e48a5926ee2d791cc5640924c
### Plugins
cloud_firestore-0.16.0+1
cloud_firestore_web-0.3.0+2
firebase_auth-0.20.1
firebase_auth_web-0.3.3
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_crashlytics-0.4.0+1
firebase_messaging-6.0.16
hexcolor-1.0.6
razorpay_flutter-1.2.4

**Comment by iapicca** [comment] 2021-02-21 10:19
@vicky-prog 
your flutter version is obsolete can you run `flutter upgrade -f`

**Comment by pedromassangocode** [comment] 2021-02-22 08:12
Please upgrade Flutter and try again.
Thank you

**Comment by vicky-prog** [comment] 2021-03-04 07:45
> Please upgrade Flutter and try again.
> Thank you

Thank you

**Comment by vicky-prog** [comment] 2021-03-04 07:45
> Please upgrade Flutter and try again.
> Thank you

Thank you

**Comment by iapicca** [comment] 2021-03-14 12:28
duplicate of https://github.com/flutter/flutter/issues/68958

**Closed** 2021-03-15 08:20 UTC
Labels: in triage, waiting for customer response
