### ISSUE TITLE
VoiceOver on Flutter WebView not working correctly for exploration by touch gesture on iOS

### ISSUE THREAD

**Issue by DuaaMahya** [flutter/flutter#129108] opened 2023-06-19 09:53 UTC
### Is there an existing issue for this?

- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)

### Steps to reproduce

When using the Flutter Web View package on iOS devices, the screen reader, VoiceOver, is not responding correctly when a user tries to drag between elements on a web page.

1. Open the Flutter app on an iOS device.
2. Navigate to a URL using the Flutter WebView package.
3. Turn on the iOS screen reader, VoiceOver.
4. Try to navigate the page using exploration by touch (dragging a single finger across the screen to interact with the elements).

### Expected results

VoiceOver should detect and announce the elements as the user drags their finger across the page. The user should be able to navigate between the elements using the exploration by touch feature of VoiceOver.

### Actual results

VoiceOver does not announce or highlight elements when dragging a finger across the page. Instead, navigation between elements can only be achieved by swiping left or right. This restricts the accessibility and navigation options for users with visual impairments.

### Code sample

<details><summary>Code sample</summary>

```dart
class TestWebViewScreen extends StatefulWidget {
  const TestWebViewScreen({Key? key}) : super(key: key);

  @override
  State<TestWebViewScreen> createState() => _TestWebViewScreenState();
}

class _TestWebViewScreenState extends State<TestWebViewScreen> {
  late WebViewController? _webView;

  @override
  void initState() {
    super.initState();
    late final PlatformWebViewControllerCreationParams params;
    if (WebViewPlatform.instance is WebKitWebViewPlatform) {
      params = WebKitWebViewControllerCreationParams(
        // allowsInlineMediaPlayback: true,
        limitsNavigationsToAppBoundDomains: true,
        mediaTypesRequiringUserAction: const <PlaybackMediaTypes>{},
      );
    } else {
      params = const PlatformWebViewControllerCreationParams();
    }

    final WebViewController controller =
        WebViewController.fromPlatformCreationParams(params);

    controller
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.navigate;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(
        Uri.parse('https://google.com'),
        method: LoadRequestMethod.get,
      );

    _webView = controller;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter Simple Example')),
      body: Semantics(
        explicitChildNodes: true,
        tagForChildren: const SemanticsTag("webviewTag"),
        child: WebViewWidget(controller: _webView!),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _webView = null;
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

***-to understand the issue more please unmute the video***

https://github.com/flutter/flutter/assets/61805266/c30c16ba-d74c-40c7-8e63-a807d53c9b52

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-x64, locale en-SA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.59.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-06-19 14:15
Hi @DuaaMahya. This seems to be similar to https://github.com/flutter/flutter/issues/87031. Can you confirm it is?

**Comment by DuaaMahya** [comment] 2023-06-20 05:05
Hi @dam-ease While the issue described in #87031 relates to the 'go back' gesture used with VoiceOver (scrubbing two fingers back and forth on the screen), this issue focuses on the inability to navigate inside the WebView using touch exploration.

##Further Clarification:

There are two primary navigation methods for touch device screen reader users:

1. Quick left and right swipes with one finger, which allow sequential navigation between elements from the beginning to the end of the screen.
2. Dragging one finger across the screen, which activates exploration mode. In this mode, the screen reader vocalizes the element beneath the user's finger. To activate the element, the user lifts their finger and quickly double taps.
While swiping functions correctly, touch exploration does not work in the latest Flutter version. Consequently, screen readers lose focus when interacting with elements in a WebView, rendering the UI challenging to navigate.

## Further Investigation:

This issue surfaced after upgrading from Flutter 3.10.5 to 3.7.12, and it's exclusive to iOS (Android's Talkback does not yield a similar outcome). Downgrading to 3.7.12 rectifies the problem. However, downgrading is not an option for us due to security considerations.
Accessibility is a requirement imposed by our stakeholders. As such, I'm wondering if there's any other possible solution for fixing this issue that doesn't involve downgrading. 

note: this issue was tested on iOS 16.5

**Comment by dam-ease** [comment] 2023-06-20 08:31
Hi @DuaaMahya. Thanks for the detailed explanation. I can confirm that this issue occurs on the latest `stable` and `master` channels and that the touch gesture worked fine in WebView in Flutter `3.7.12`.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:webview_flutter_wkwebview/webview_flutter_wkwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: TestWebViewScreen());
  }
}

class TestWebViewScreen extends StatefulWidget {
  const TestWebViewScreen({Key? key}) : super(key: key);

  @override
  State<TestWebViewScreen> createState() => _TestWebViewScreenState();
}

class _TestWebViewScreenState extends State<TestWebViewScreen> {
  late WebViewController? _webView;

  @override
  void initState() {
    super.initState();
    late final PlatformWebViewControllerCreationParams params;
    if (WebViewPlatform.instance is WebKitWebViewPlatform) {
      params = WebKitWebViewControllerCreationParams(
        limitsNavigationsToAppBoundDomains: true,
      );
    } else {
      params = const PlatformWebViewControllerCreationParams();
    }

    final WebViewController controller =
        WebViewController.fromPlatformCreationParams(params);

    controller
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.navigate;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(
        Uri.parse('https://google.com'),
        method: LoadRequestMethod.get,
      );

    _webView = controller;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter Simple Example')),
      body: Semantics(
        explicitChildNodes: true,
        child: WebViewWidget(controller: _webView!),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _webView = null;
  }
}

``` 

</p>
</details> 

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.5 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (6 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                            •
      android-arm64  • Android 11 (API 30) (emulator)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e •
      ios            • iOS 16.5 20F66
    • iPhone 14 (mobile)         • 5FE8DE93-0F4C-45BA-8BED-BC9CD69B35D1     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile)     • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.12.0-4.0.pre.121, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.12.0-4.0.pre.121 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5182697c0d (7 hours ago), 2023-06-19 21:37:33 -0400
    • Engine revision a91bb3f566
    • Dart version 3.1.0 (build 3.1.0-230.0.dev)
    • DevTools version 2.24.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (6 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                            • android-arm64  • Android 11 (API 30) (emulator)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e • ios            • iOS 16.5 20F66
    • iPhone 14 (mobile)         • 5FE8DE93-0F4C-45BA-8BED-BC9CD69B35D1     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile)     • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!

``` 

```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.7.12 on channel stable at /Users/dammya/fvm/versions/3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (9 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (6 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                            • android-arm64  • Android 11 (API 30) (emulator)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e • ios            • iOS 16.5 20F66
    • iPhone 14 (mobile)         • 5FE8DE93-0F4C-45BA-8BED-BC9CD69B35D1     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile)     • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 114.0.5735.133

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

``` 

</p>
</details>

**Comment by jeremie-movify** [comment] 2023-06-22 12:47
Hi there,
We're facing the same issue. I've spent a little bit of time testing different versions of the Flutter SDK (running on iOS 16.5), here are my findings:

- Issue is **not** reproducible on _3.7.12_ (as stated by @DuaaMahya & @dam-ease)
- Issue is also **not** reproducible on _3.8.0-7.0.pre_ (I can still navigate/explore via touch gesture, VoiceOver on)
- Issue **is** reproducible on _3.8.0-8.0.pre_ (same issue as described by @DuaaMahya).

So a change happened between those two versions, breaking the 'touch gesture exploration' functionality.

Hope this helps! Cheers

**Comment by cyanglaz** [comment] 2023-07-25 17:04
This is a duplicate of https://github.com/flutter/flutter/issues/30804. Closing this one.

**Closed by cyanglaz** 2023-07-25 17:04 UTC
Labels: c: regression, platform-ios, framework, a: accessibility, f: gestures, p: webview, package, has reproducible steps, P2, found in release: 3.10, found in release: 3.12, team-ios, triaged-ios, multiteam-retriage-candidate
