### ISSUE TITLE
FAILURE: Build failed with an exception. <gnu/stubs-32.h>

### ISSUE THREAD

**Issue by ErnestoAbram** [flutter/flutter#72415] opened 2020-12-16 07:00 UTC
In Ubuntu 20 when I compile for Android get this error:
```bash
* What went wrong:
Execution failed for task ':bitmap:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/ernesto/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/ernesto/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.0.6/android/.cxx/cmake/debug/armeabi-v7a --target bitmap} ....

/snap/flutter/current/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
  # include <gnu/stubs-32.h>
            ^~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.
```
```bash
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/ernesto/snap/flutter/common/flutter
    • Framework revision 022b333a08 (hace 4 semanas), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ernesto/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-1)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Web Server (web)                 • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 87.0.4280.88
```
I try to install libc-32 and other thinks, but it don work anywhere.

Flutter is working for me in other projects in Android and web.

```yaml
this is my puscpec:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  firebase_ml_vision: ^0.9.10
  bitmap: ^0.0.6
  #light: ^1.0.0 
  


  edge_detection: ^1.0.5

  intl: ^0.16.1

  provider: ^4.1.3


  fluttertoast: ^4.0.1

  slider_button: ^0.5.0

  url_launcher: ^5.7.8
  geolocator: ^5.1.3
  font_awesome_flutter: ^8.10.0

  pdf: ^1.9.0
  flutter_signature_pad: ^2.0.2

  torch_compat: ^1.0.2

  camera: ^0.5.8+11

  google_fonts: ^1.1.1

  #flutter_webview_plugin: ^0.3.11

  #jitsi_meet: ^0.4.2

  flutter_secure_storage: ^3.3.5

  path_provider:
  path:


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/eqalogo.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**Comment by TahaTesser** [comment] 2020-12-16 09:27
Hi @ErnestoAbram 
Can you please provide your complete  `flutter run --verbose` logs and a complete reproducible minimal code sample without using third-party packages 
Thank you

**Comment by pedromassangocode** [comment] 2021-01-06 12:36
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by rigeltrue** [comment] 2021-02-22 02:58
I encounter the same issue in Ubuntu 16.04 when building Android app.
stubs-32.h is in my /usr/include/x86_64-linux-gnu/gnu folder but not in the /snap/flutter/current/usr/include/x86_64-linux-gnu/gnu/ folder.

I just follow this https://flutter.dev/docs/development/platform-integration/c-interop and don't add anything else.
Could anyone help?
Thanks

The output of `flutter doctor -v` is:
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-4.0.pre at /home/rigel/snap/flutter/common/flutter
    • Framework revision f8cd24de95 (5 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/rigel/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /opt/android-studio/
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome
      87.0.4280.88

**Comment by TahaTesser** [comment] 2021-02-23 09:51
@rigeltrue 
Ubuntu 16.04 is not supported, please upgrade to at least 18.04

**Comment by rigeltrue** [comment] 2021-02-24 11:52
I install Ubuntu 20.04, but this issue still happen

  /snap/flutter/current/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
  include <gnu/stubs-32.h>

  1 error generated.
  ninja: build stopped: subcommand failed.

[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-4.0.pre at /home/rigel/snap/flutter/common/flutter
    • Framework revision f8cd24de95 (8 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/rigel/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /opt/android-studio/
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome
      88.0.4324.182

• No issues found!

**Comment by TahaTesser** [comment] 2021-03-01 11:48
@rigeltrue 
Can you please provide `flutter run -d linux --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by inetic** [comment] 2021-03-02 08:56
Hi, I'm not OP, but I have the same problem on Ubuntu 18.04. Attached is a quite minimal example with which this happens. The log is from running the command `flutter build apk -d linux --verbose`.

[example.tar.gz](https://github.com/flutter/flutter/files/6067336/example.tar.gz)
[build.log](https://github.com/flutter/flutter/files/6067339/build.log)

**Comment by GuyWithCookies** [comment] 2021-03-02 20:11
I also had this issue. This happens because you are missing the 32-libc-dev package as mentioned [here](https://stackoverflow.com/questions/7412548/error-gnu-stubs-32-h-no-such-file-or-directory-while-compiling-nachos-source
). 
If you didn't install flutter via snap then simply running 
` sudo apt-get install libc6-dev-i386` (Ubuntu)
should fix the issue.

However this does NOT work for flutter installed via snap.
First remove flutter with
`sudo snap remove flutter`
and reinstall flutter manually as described [here](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually).

**Comment by TahaTesser** [comment] 2021-03-03 09:12
Hi everyone!
it seems to be related to flutter snap, please file an issue on their dedicated GitHub [repository](https://github.com/canonical/flutter-snap/issues).
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-03-03 09:12 UTC
Labels: in triage, waiting for customer response

**Comment by asafeca** [comment] 2021-04-15 06:05
@TahaTesser  You're right. snap version is the big problem. I was going through the same problem and changing for the manual installation solved the problem. Thanks

**Comment by atsansone** [comment] 2023-09-21 22:37
Snap appears to have fixed this issue with https://github.com/canonical/flutter-snap/pull/78.
