### ISSUE TITLE
[web]: TextField cursor jump to the first character when typing Thai vowel above and below the alphabet

### ISSUE THREAD

**Issue by draoinaja** [flutter/flutter#85897] opened 2021-07-05 10:59 UTC
[https://github.com/flutter/flutter/issues/21745](https://github.com/flutter/flutter/issues/21745)

I have same issue (link above) at flutter web (stable 2.2.3) in Thai Language.
but I'm tried at flutter web (stable 1.22.6) it's working fine

![image](https://user-images.githubusercontent.com/86959946/124460992-4bc83680-ddba-11eb-952d-c603135359a5.png)
![image](https://user-images.githubusercontent.com/86959946/124461175-803bf280-ddba-11eb-9bd4-9788fae3b853.png)

**Comment by darshankawar** [comment] 2021-07-06 07:32
Verified this on latest master (2.4.0-1.0.pre.84) and stable (2.2.3) and seems to be occuring with canvaskit.


https://user-images.githubusercontent.com/67046386/124560150-1f63f700-de5a-11eb-88ee-27f8b73e88dc.mov


Works well using html renderer, ie, the cursor persists at current position and doesn't reset to the start.

<img width="448" alt="Screenshot 2021-07-06 at 12 54 16 PM" src="https://user-images.githubusercontent.com/67046386/124560200-2db21300-de5a-11eb-8ce7-b848446fb2fe.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

```
return Scaffold(
      body: Center(
        child: TextField(
          decoration: InputDecoration(
            hintText: 'enter here'
          ),
        ),
      )
    );
```

**Comment by asashour** [comment] 2021-07-08 14:04
In case someone would take this further:

The issue is in here, the return type is empty for the vowels, and this goes inside `sky_engine`

https://github.com/flutter/flutter/blob/5d18c9d38e1c4cbd28d3ccb5a9ef036f3179c14f/packages/flutter/lib/src/painting/text_painter.dart#L701


I tried to build the `engine`, but there are errors.

**Comment by asashour** [comment] 2021-07-16 21:37
This issue is related to diacritics, and is affecting all languages which use it.

In case someone would take this issue forward, further to the discussion [here](https://bugs.chromium.org/p/skia/issues/detail?id=12208), skia would take time to implement the requested features.

In the mean time, I guess Flutter can from its side evaluate the current skia results and calculate the cursor accordingly (to do what Google driver does with text editing, not what Microsoft Word or Notepad++ do), see the discussion for details.

**Comment by asashour** [comment] 2021-07-18 23:40
This can be fixed in framework. Specifically removing this line fixes the issue

https://github.com/flutter/flutter/blob/e084e9d9466d598cb541c51740a30384c8a90c2f/packages/flutter/lib/src/painting/text_painter.dart#L707

I tried to make a test case in `text_painter_test.dart`, but it succeeds, hinting a difference from real scenario.

```dart
  test('Diacritic', () {
    final TextPainter painter = TextPainter()
      ..textDirection = TextDirection.ltr;

    // two letters followed by a diacritic
    const String text = 'ฟห้';
    painter.text = const TextSpan(text: text);
    painter.layout();

    final ui.Offset caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: text.length), ui.Rect.zero);
    expect(caretOffset.dx, painter.width);
  });
```

**Comment by hterkelsen** [comment] 2021-07-20 22:34
Thanks for looking into this @asashour .

I think we can also fix this in the framework by changing this line to account for diacritics:

https://github.com/flutter/flutter/blob/e084e9d9466d598cb541c51740a30384c8a90c2f/packages/flutter/lib/src/painting/text_painter.dart#L694

**Comment by asashour** [comment] 2021-07-21 09:26
Thanks @hterkelsen for your feedback.

Indeed, that would be a better solution, however I don't know how to detect diacritics (I am gradually diving into the issue and feeling myself in `discovery channel` :) ).

Another concern is also the test case, which I couldn't make as hinted in my previous comment.

**Comment by hterkelsen** [comment] 2021-07-22 21:32
I added that test and am able to get it to fail using `flutter test --platform=chrome --web-renderer=canvaskit test/painting/text_painter_test.dart`

**Comment by hterkelsen** [comment] 2021-07-26 16:25
Fixed by https://github.com/flutter/flutter/pull/86960

**Closed by hterkelsen** 2021-07-26 16:25 UTC
Labels: P3, a: internationalization, a: text input, a: typography, dependency: skia, e: web_canvaskit, engine, found in release: 2.2, found in release: 2.4, has reproducible steps, platform-web
