### ISSUE TITLE
Backspace doesn't work in Flutter for obscured password entry when Capslock is on

### ISSUE THREAD

**Issue by johnfelton** [flutter/flutter#78667] opened 2021-03-19 23:55 UTC
@chunhtai 
internal b/179195930

This appears to be a bug in the keyboard that flutter uses when entering an obscured password. It only happens when CAPS lock is enabled (not when shifting a letter at a time but when the keyboard is locked in all caps mode by double touching the shift key). The keyboard used for entering a password shows numbers across the top of the keyboard instead of suggestions. Changing the "Show Password" setting prior to touching the input field brings up the normal text entry keyboard. This keyboard does not have the CAPS lock issue. Turning the "Show Password" setting off again will obscure the password but continue to use the normal text entry keyboard. This is not a workaround but helps to clarify the situation. One could potentially force the text entry keyboard for password entry but showing suggestions when entering passwords is undesirable. The simplest workaround is to turn off the CAPS lock key when deleting characters. Unfortunately this might not be obvious to a user.

**Comment by chunhtai** [comment] 2021-03-20 00:04
Hi @johnfelton can you provide a minimum reproducible code, which i can copy paste into my main.dart and run?

Also may i know which platform are you running on?

**Comment by chunhtai** [comment] 2021-03-20 00:06
cc @gspencergoog and @justinmc

**Comment by johnfelton** [comment] 2021-03-20 15:54
Hi @chunhtai 

I am running on Android

Here is a minimal test case:

`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Password Test',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter Password Test'),
        ),
        body: TextFormField(
                obscureText: true,
                decoration: const InputDecoration(
                  labelText: 'Password',
          ),
        ),
      ),
    );
  }
}
`

**Comment by LongCatIsLooong** [comment] 2021-03-20 23:29
This looks like a duplicate of https://github.com/flutter/flutter/issues/64761.

**Comment by justinmc** [comment] 2021-04-05 17:17
Also reminds me of https://github.com/flutter/flutter/issues/79374.

I think there is some root problem with how capslock is being handled right now.

**Comment by TahaTesser** [comment] 2022-08-23 11:57
Hi everyone

I cannot reproduce it on device or emulator. 
Given the lack of activity, I feel safe to close the issue. 


<details> 
<summary>flutter doctor -v</summary> 

```console
[!] Flutter (Channel master, 3.1.0-0.0.pre.2428, on macOS 13.0 22A5321d darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2428 on channel master at /Users/tahatesser/Code/flutter
    ! Upstream repository git@github.com:NevercodeHQ/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:NevercodeHQ/flutter.git to dismiss this error.
    • Framework revision 328545e5af (9 hours ago), 2022-08-22 22:31:06 -0400
    • Engine revision ca48808d06
    • Dart version 2.19.0 (build 2.19.0-124.0.dev)
    • DevTools version 2.16.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 14A5294e
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)        • macos    • darwin-arm64   • macOS 13.0 22A5321d darwin-arm
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
``` 
	
</details>

**Closed by TahaTesser** 2022-08-23 11:57 UTC
Labels: a: text input, framework, f: material design, passed first triage, P3
