### ISSUE TITLE
modal bottom sheet doesn't work anymore

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1301] opened 2016-01-19 18:54 UTC
modal bottom sheet doesn't work anymore

Just shows the overlay, not the sheet.
https://youtu.be/osem8PnkcD4

@HansMuller

**Comment by abarth** [comment] 2016-01-19 18:55
This might be fixed.  /me tries.

**Comment by abarth** [comment] 2016-01-19 18:56
Fixed at HEAD.

**Comment by HansMuller** [comment] 2016-01-19 18:56
This is a duplicate of https://github.com/flutter/flutter/issues/1250

**Closed by abarth** 2016-01-19 18:56 UTC
