### ISSUE TITLE
Strange interaction between popup and keyboard and scrolling

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8279] opened 2017-02-18 05:53 UTC
This may only end up applying on Android, since iOS doesn't really have dropdown pickers:
https://developer.apple.com/ios/human-interface-guidelines/ui-controls/pickers/

![picker_keyboard mov](https://cloud.githubusercontent.com/assets/11857803/23090795/730d01ea-f55b-11e6-8852-2dc4a21d8c90.gif)

**Comment by abarth** [comment] 2017-02-18 06:09
Interesting.  We should figure out if we're supposed to leave the contents overscrolled (to keep the dropdown button under the menu) or if we're supposed to reposition the menu to track the button as the content springs back from being overscrolled.

**Comment by ds84182** [comment] 2017-02-18 18:08
On Android most popups reposition themselves. This can be tested in the YouTube app if you manage to tap the menu button on a video while trying to scroll in the same frame.

**Comment by markusaksli-nc** [comment] 2020-07-16 10:44
Closing this as a duplicate of #60773, since the mentioned issue has reproducing steps please follow up on it.

**Closed by markusaksli-nc** 2020-07-16 10:44 UTC
Labels: P4, a: fidelity, f: material design, framework
