### ISSUE TITLE
[web]: <Gif not getting animated flutter web>

### ISSUE THREAD

**Issue by liuzhengcai** [flutter/flutter#39320] opened 2019-08-27 09:48 UTC
Gif not getting animated flutter web

```
import 'package:flutter_web/material.dart';
//import 'dragable.dart';
import 'image/showimage.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'gif image',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      //home: MainImagePage(),
      home:Image.asset("images/jlt/jlt.gif"),
      );
  }
}
```

**Comment by andrijasinski** [comment] 2019-08-28 12:55
Please add the output of `flutter doctor -v`.
Also, attach images and minimal runnable reproduction as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by liuzhengcai** [comment] 2019-09-06 00:48
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale zh-CN)
    • Flutter version 1.7.8+hotfix.4 at D:\WebAPP\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\WebAPP\androidsdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\WebAPP\androidsdk
    • Java binary at: D:\WebAPP\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\WebAPP\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at D:\WebAPP\IntelliJ\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[!] Connected device
    ! No devices available

**Comment by liuzhengcai** [comment] 2019-09-06 00:49
import 'package:flutter_web/material.dart';
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'gif image',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home:Image.asset("jlt.gif"),
      );
  }
}

**Comment by liuzhengcai** [comment] 2019-09-06 00:50
http://www.liuzhengcai.top/images/jlt.gif

**Comment by ditman** [comment] 2019-09-10 21:44
This issue is duplicate, but thanks for the minimal repro code; it'll come in handy!

> @ferhatb : Note: TODO-> Code needs to switch to DomCanvas to enable gif. Current code draws Image asset into bitmap canvas.

**Comment by ditman** [comment] 2019-09-10 21:45
Duplicate of #33618

**Closed by ditman** 2019-09-10 21:45 UTC
Labels: ☸ platform-web
