### ISSUE TITLE
Webview download alert

### ISSUE THREAD

**Issue by varunkumarmedam** [flutter/flutter#70831] opened 2020-11-19 12:03 UTC
When I tried to download a picture using [webview_flutter](https://pub.dev/packages/webview_flutter) it can't able to show an alert box like what chrome is doing. 

![flutter_webview](https://user-images.githubusercontent.com/30391861/99663821-356ca500-2a8d-11eb-8852-9a6afd396344.jpeg)

**Comment by TahaTesser** [comment] 2020-11-19 15:13
Hi @varunkumarmedam 
Current;y `webview_flutter` doesn't support downloads so I am not sure alert download would appear without this ability
Closing as duplicate of https://github.com/flutter/flutter/issues/39321
Thank you

**Closed by TahaTesser** 2020-11-19 15:13 UTC
