### ISSUE TITLE
Sizedbox can not restrain Text Widget

### ISSUE THREAD

**Issue by skyshenfu** [flutter/flutter#27150] opened 2019-01-27 09:28 UTC
```dart
          SizedBox(
            width: 100.0,
            height: 100.0,
            child: Container(
              child: Text("You have pushed the button this many times" * 3),
              decoration: BoxDecoration(
                color: Colors.green,
              ),
            ),
          )
```

I see that text content overflow the `Sizebox`, The parent Widget of `Sizebox` is `Column`
![login](https://i.loli.net/2019/01/27/5c4d7912abbc8.png)

**Comment by zoechi** [comment] 2019-01-27 16:15
Probably a duplicate of #25025 #26006 #16450

**Comment by Kartik1607** [comment] 2019-01-28 07:54
Related : https://github.com/flutter/flutter/issues/26173

**Closed** 2020-06-19 07:56 UTC
Labels: P4, a: typography, framework
