### ISSUE TITLE
cupertino navigation bar leading width seems limited

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#36691] opened 2019-07-22 15:17 UTC
The cupertino navigation bar leading width seems limited:

![image](https://user-images.githubusercontent.com/21303438/61643872-51fc9f80-acd6-11e9-8510-365aca47a2e3.png)

I can not make my widget such as a Row with text and image in side ...... What should I do?

**Comment by shihaohong** [comment] 2019-07-22 16:28
Closing as duplicate of https://github.com/flutter/flutter/issues/36689

**Closed by shihaohong** 2019-07-22 16:28 UTC
