### ISSUE TITLE
error in flutter install

### ISSUE THREAD

**Issue by al7re4** [flutter/flutter#75538] opened 2021-02-05 21:28 UTC
$ flutter doctor
```
Downloading Dart SDK from Flutter engine 2f0af3715217a0c2ada72c717d4ed9178d68f6ed...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    388      0 --:--:-- --:--:-- --:--:--   387
[/home/kali/Downloads/mobiledev/flutter/bin/cache/dart-sdk-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/kali/Downloads/mobiledev/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/kali/Downloads/mobiledev/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/kali/Downloads/mobiledev/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

```

**Comment by iapicca** [comment] 2021-02-06 14:48
duplicate of https://github.com/flutter/flutter/issues/66243

**Comment by darshankawar** [comment] 2021-02-08 07:44
Closing this as duplicate of https://github.com/flutter/flutter/issues/66243

**Closed by darshankawar** 2021-02-08 07:44 UTC
