### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by emakei** [flutter/flutter#80272] opened 2021-04-12 12:50 UTC
## Steps to Reproduce

1. do `flutter upgrade`
2. wait until error after upgrading

### command

flutter --no-color --no-version-check precache

### exception

FileSystemException: FileSystemException: Deletion failed, path = 'C:\flutter\bin\cache\flutter_web_sdk' (OS Error: Папка не пуста.
, errno = 145)
<details>
<summary>Logs</summary>

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:459:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:458:12)
#6      FlutterWebSdk.updateInner (package:flutter_tools/src/cache.dart:838:16)
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:692:11)
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:562:24)
<asynchronous suspension>
#9      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:167:7)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#19     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#20     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#23     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

```
Downloading package sky_engine...                                  859ms
Downloading flutter_patched_sdk tools...                         1 947ms
Downloading flutter_patched_sdk_product tools...                 1 848ms
Downloading windows-x64 tools...                                    4,8s
Downloading windows-x64/font-subset tools...                       485ms
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.17763.1817], locale ru-RU)
    • Flutter version 2.0.4 at C:\flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\emakey\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\emakey\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment] 2021-04-12 13:18
Closing as duplicate of https://github.com/flutter/flutter/issues/64410. Please subscribe on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-04-12 13:18 UTC
Labels: in triage

**Comment by emakei** [comment] 2021-04-12 16:48
> Closing as duplicate of #64410. Please subscribe on that issue for updates.
> Thank you

It's true. But maybe important to see 'PATH'? Maybe this issue happens only with Web SDK?
