### ISSUE TITLE
[web] Uncaught SyntaxError: Unexpected token '|'

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#63546] opened 2020-08-12 03:06 UTC
flutter doctor -v
[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101,
locale zh-Hans-CN)
• Flutter version 1.20.0-1.0.pre.132 at /Users/liuyanfeng/Library/flutter
• Framework revision 5995661777 (), 2020-06-19 16:15:58 -0700
• Engine revision 676cd566f7
• Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9a)
• Pub download mirror https://pub.flutter-io.cn
• Flutter download mirror https://storage.flutter-io.cn

![image](https://user-images.githubusercontent.com/2295872/89970533-9c5b1080-dc8b-11ea-9ca9-7977cee81be8.png)

**Comment by darshankawar** [comment] 2020-08-12 08:10
Hi @lyf571321556,
Please elaborate on the issue. Are you getting this issue when you imported the code, a plugin or is it your own code ?
Also provide a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by lyf571321556** [comment] 2020-08-12 10:46
plugin:
  sembast: ^2.4.7+6
  sembast_web: ^1.2.0
when i call some code  jusk like below:
await _store.delete(dbClinet);
or 
await _store.update(dbClinet);

tow of them produced same error.

**Comment by darshankawar** [comment] 2020-08-12 11:56
@lyf571321556,
This seems to be an issue with the third party plugins you are using `sembast` and `sembast_web`. Please consider opening this issue there.
Closing, as this doesn't seem to be an issue with Flutter. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-08-12 11:56 UTC
Labels: in triage
