### ISSUE TITLE
Cannot enter data into TextFormField on iOS device due to SelectionArea

### ISSUE THREAD

**Issue by Nosfert** [flutter/flutter#128660] opened 2023-06-11 13:26 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

See DartGist : https://dartpad.dev/?id=882fe81f1eecf09ae7ffe10480a0ec8f

1. Create a Web app
2. In the MaterialApp wrap the Child in SelectionArea()
3. Create a TextFormField  
4. Start the instance, 
5. Navigate to the webpage via the simulator or a real iOS device
6. See that you cannot enter data into the TextFormField

I have also tried to submit (to see if the text is just not visible) the data and nothing is present. 
Wanted to wrap the whole web in SelectionArea so that one can select any and all text etc on the webpage. 

### Expected results

Expected that iOS units also should have the ability to enter text into the fields

### Actual results

The iOS unit cannot enter text into the text fields

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: SelectionArea(
        child : Scaffold(
        body: Center(
          child: MyWidget(),
        ),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children : [Text(
      'Hello, World!',
      style: Theme.of(context).textTheme.headlineMedium,
        ),
        TextFormField(
                      enabled: true,
                      decoration: const InputDecoration(
                        labelText: 'Email',
                        border:  OutlineInputBorder(),
                      )
          ),
    ]
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>
Tried running this on the simulator. 
Cannot enter tex.t 

</summary>
![image](https://github.com/flutter/flutter/assets/1873652/a7151427-d961-404e-826f-ac1f00273a3a)
</details>

### Logs

<details><summary>Logs</summary>

```console
No Logs
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-arm64, locale en-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2023-06-12 09:42
Thanks for filing the issue. There's an open issue (https://github.com/flutter/flutter/issues/107327) that could be similar. But it still can be entered text if clicking more than one tap on TextField. Can you retry and confirm this?

**Comment by Nosfert** [comment] 2023-07-04 11:50
@huycozy sorry for late reply, went on vacation (building physical stuff) and missed this notification. 
Tried what you asked and no matter how many times I click I cannot enter data into the text field. 

I solved it by removing the SelectionArea that wrapped my whole app. 
But I feel reluctant to wrap "all" individual components that are not a input field to make this work.

**Comment by huycozy** [comment] 2023-07-05 04:33
Thanks for your response. I checked this issue again and tried it on iOS device but I still can enter text to TextField.

<details>
<summary>Demo Web on iOS</summary>

https://github.com/flutter/flutter/assets/104349824/e38c7c35-0742-4686-bf7d-190902c53684

</details>

Can you please share a demo video showing you can not enter text? 

Might still be the same issue at https://github.com/flutter/flutter/issues/107327 as it also loses focus on the web (see [my comment](https://github.com/flutter/flutter/issues/107327#issuecomment-1576254447)). This issue is more specific to mobile web browsers.

**Comment by agordeev** [comment] 2023-07-08 18:52
I'm having the same issue. Input starts working after a few taps on the field. Reproducible on iOS 16.5.1 (Chrome, Mozilla, Safari).

Here's code example:


```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const Center(
        child: SelectionArea(
          child: TextField(
            decoration: InputDecoration(
              border: OutlineInputBorder(),
              labelText: 'Test input',
            ),
          ),
        ),
      ),
    );
  }
}

```

<details><summary>Doctor output</summary>

```console

❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-RU)
    • Flutter version 3.10.5 on channel stable at /Users/andrey/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] VS Code (version 1.80.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.67.20230601

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  •
      Android 13 (API 33) (emulator)
    • iPhone 14 Pro Max (mobile)  • A6365F46-0726-41B3-BE19-780471F7F7F8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   •
      macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript •
      Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>



https://github.com/flutter/flutter/assets/2883524/7c94cc60-d5a6-4c4e-ad18-735cacaa0be7

**Comment by Nosfert** [comment] 2023-07-08 23:06
@huycozy will try it out a bit more at a later date, give me a week or two before im back on my laptop

**Comment by huycozy** [comment] 2023-07-10 04:55
@agordeev The behavior you described is similar to https://github.com/flutter/flutter/issues/128116 and that issue is marked as a duplicate of https://github.com/flutter/flutter/issues/107327. So please follow up on that issue for further updates. In this issue, the OP can not focus on TextField even tapping on it many times which could be an edge case. 

@Nosfert just FYI, I now can see the behavior as @agordeev described above with a physical device (need more one tap to be able to focus TextField.

**Comment by agordeev** [comment] 2023-07-10 07:51
@huycozy in my example, I can focus on the TextField. Please see the video. The cursor is there and keyboard too.

**Comment by huycozy** [comment] 2023-07-10 08:12
Ah yes, sorry, I typed it wrong. I was meaning to "enter" (please also see https://github.com/flutter/flutter/issues/128660#issuecomment-1620101087).

**Comment by agordeev** [comment] 2023-07-31 08:29
@huycozy I don't think this issue should be closed, as it's not resolved yet. What do you think?

**Comment by huycozy** [comment] 2023-08-01 08:59
@agordeev The issue is automatically closed by the bot. I reopen for discussion further. 

I just checked this issue and can reproduce it on stable channel 3.10.6 (it's quite weird since it didn't appear on my last test at https://github.com/flutter/flutter/issues/128660#issuecomment-1621006866). But this seems to be fixed on the latest master channel. Can you please check this and confirm?

```
flutter channel master
flutter upgrade
```

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5195m
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.13.0-15.0.pre.13, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.0-15.0.pre.13 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at
      /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c851efaa3a (5 hours ago), 2023-07-31 22:40:26 -0400
    • Engine revision 791f505c8c
    • Dart version 3.2.0 (build 3.2.0-16.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5195m
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Closed** 2023-08-11 16:08 UTC
Labels: waiting for customer response, in triage

**Comment by agordeev** [comment] 2023-08-11 18:29
Hi @huycozy ! The issue is closed again.

**Comment by huycozy** [comment] 2023-08-14 03:22
@agordeev Can you please check and confirm this on the latest master channel as I mentioned above? If the issue still appears, please help to create a new issue for this since OP doesn't seem to respond to this issue (the bot will automatically close the issue if OP doesn't response).
