### ISSUE TITLE
[AddToApp] NullPointerException thrown while FlutterActivityAndFragmentDelegate try attaching the engine to FlutterView 

### ISSUE THREAD

**Issue by yrom** [flutter/flutter#48061] opened 2020-01-02 07:43 UTC
Flutter version: 1.12.13+hotfix.5
Target platform: Android

In `FlutterActivityAndFragmentDelegate` [onStart()](https://github.com/flutter/engine/blob/v1.12.13-hotfixes/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L281-L299) the `flutterView` will `attachToFlutterEngine()` in next loop via Handler callback.

But at some strange times, [`release()`](https://github.com/flutter/engine/blob/v1.12.13-hotfixes/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L113-L118) may have been called before it, see following logs.

## Logs
```
java.lang.NullPointerException
Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterView.attachToFlutterEngine(io.flutter.embedding.engine.FlutterEngine)' on a null object reference

1 io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2.run(FlutterActivityAndFragmentDelegate.java:2)
2 android.os.Handler.handleCallback(Handler.java:836)
3 android.os.Handler.dispatchMessage(Handler.java:103)
4 android.os.Looper.loop(Looper.java:203)
5 android.app.ActivityThread.main(ActivityThread.java:6406)
6 java.lang.reflect.Method.invoke(Native Method)
7 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
8 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
```

## Solution

Surrounding with `if (flutterView != null)`:
```java
new Handler().post(new Runnable() {
    @Override
    public void run() {
       if (flutterView != null) {
          Log.v(TAG, "Attaching FlutterEngine to FlutterView.");
          flutterView.attachToFlutterEngine(flutterEngine);

          doInitialFlutterViewRun();
       }
    }
  });
}
```

**Comment by iapicca** [comment] 2020-01-02 10:20
Hi @yrom  
can you please provide your `flutter doctor -v` 
and your full `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by jmagman** [comment] 2020-01-02 20:36
Duplicate of https://github.com/flutter/flutter/issues/45347.

**Closed by jmagman** 2020-01-02 20:36 UTC
Labels: a: existing-apps, dependency: android, waiting for customer response, ▣ platform-android
