### ISSUE TITLE
Faster slide animation speed for PageView and TabView

### ISSUE THREAD

**Issue by sofasurfa** [flutter/flutter#55103] opened 2020-04-18 13:57 UTC
Hi, I was wondering if there's a way to change the sliding animation speed for PageView and TabView. In my opinion, the sliding animation (when you swipe in one direction and let go with enough velocity) is a bit too slow for my app.

I dug around the source code for PageView and TabView but couldn't find anything to do with animation speed. Is there constant value in constants.dart that controls the speed?
Any help is appreciated.

**Feature**: It would be nice to control the animation speed for these widgets using a parameter like `animationSpeed: 200.0` (where `200.0` is milliseconds). I feel like apps have different feel to them, and control of the animation speed is vital to achieve a particular user experience.

Thanks :)

**Comment by VladyslavBondarenko** [comment] 2020-04-20 10:42
Hi @sofasurfa 
Have you tried https://api.flutter.dev/flutter/scheduler/timeDilation.html?

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    timeDilation = 0.1;
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Icon(Icons.directions_car),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

Do you still feel need in animationSpeed parameter for PageView and TabView?

**Comment by sofasurfa** [comment] 2020-04-21 18:32
@VladyslavBondarenko Thank you, this does the trick. However this is more of a hack and requires extra logic to switch on and off (since timeDilation is global and changes the animation speed for the whole app). 

So yes, I still feel the need for `animationSpeed` parameter for PageView and TabView, and maybe other widgets that have similar requirements.

This is what I have to turn on/off `timeDilation`, so it only happens on specific widgets (TabView in this case). The timer makes sure the animation fully completes at the right speed.

```
Listener(
                  onPointerDown: (PointerDownEvent event) {
                     timeDilation = 0.6;
                  },
                  onPointerUp: (PointerUpEvent event) {
                    Timer(Duration(milliseconds: 1000), () {
                      timeDilation = 1.0;
                    });
                  },
                   child: TabBarView(
```

**Comment by lazylazyllama** [comment] 2020-04-22 22:46
I think that the animation speed of the TabView should be faster in general by default... Its much faster on android anyways...

**Comment by luckysmg** [comment] 2020-06-13 06:42
emm ,I think such code is intrusive and not elegant....

**Comment by luckysmg** [comment] 2020-08-05 05:49
hope that there is a property to control it..

**Comment by xingfudeshi** [comment] 2020-09-06 09:40
> timeDilation
Where is timeDilation used?

**Comment by JMooreo** [comment] 2020-12-16 19:16
@sofasurfa 
Here is a better solution to the animation speed that is MUCH more elegant than using timeDilation. It has fewer side effects and I think this is the intended way to change the animation speed.

1. Create a PageController in StatefulWidget.
```
final _controller = PageController();
```
2. Attach to the onPageChanged hook on the PageView constructor and pass in the desired duration and curve.
```
@override
Widget build(BuildContext context) {
  return PageView(
    controller: _controller,
    onPageChanged: (pageIdx) => _controller.animateToPage(pageIdx,
        duration: const Duration(milliseconds: 200),
        curve: Curves.linearToEaseOut),
    children: [...],
  );
}
```

**Comment by ilkercankaya** [comment] 2020-12-16 19:31
You can modify the source of PageView as a last resort to achieve this. Currently PageView uses Physics to achieve the auto scrolling rather than a simple Animation with curves. For faster animations, make a spring with lower mass:

```
static final SpringDescription customSpring =
      SpringDescription.withDampingRatio(
    mass: 0.1,
    stiffness: 100.0,
    ratio: 1.1,
  );

```

Insert it inside the function below:
```
@override
  Simulation createBallisticSimulation(
      ScrollMetrics position, double velocity)
```
replace this line with your custom spring:
```
if (target != position.pixels)
      return ScrollSpringSimulation(
          customSpring, position.pixels, target, velocity,
          tolerance: tolerance);
```

I think this is what you mean by the `animation speed`. 

[For more info here is a stackoverflow question, read the comments.](https://stackoverflow.com/questions/65325496/flutter-pageview-detect-when-page-is-about-to-change-not-on-changed?noredirect=1#comment115494537_65325496)

**Comment by JMooreo** [comment] 2020-12-16 21:44
@ilkercankaya I like your solution better! Feels much more native. Here is a custom Scroll Physics class that I wrote.
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/physics.dart';

class CustomPageViewScrollPhysics extends ScrollPhysics {
  const CustomPageViewScrollPhysics({ScrollPhysics parent})
      : super(parent: parent);

  @override
  CustomPageViewScrollPhysics applyTo(ScrollPhysics ancestor) {
    return CustomPageViewScrollPhysics(parent: buildParent(ancestor));
  }

  @override
  SpringDescription get spring => const SpringDescription(
        mass: 80,
        stiffness: 100,
        damping: 1,
      );
}
```
It can be used in the PageView constructor like this:
```
PageView(... physics: const CustomPageViewScrollPhysics(),)
```

**Comment by ilkercankaya** [comment] 2020-12-16 21:59
@JMooreo Your code is easier to use and overall better. I think that is how it should be done rather than copying the source code. Thank you for sharing! 👍

**Comment by Tom1380** [comment] 2021-01-04 02:11
> @ilkercankaya I like your solution better! Feels much more native. Here is a custom Scroll Physics class that I wrote.
> 
> ```
> import 'package:flutter/cupertino.dart';
> import 'package:flutter/physics.dart';
> 
> class CustomPageViewScrollPhysics extends ScrollPhysics {
>   const CustomPageViewScrollPhysics({ScrollPhysics parent})
>       : super(parent: parent);
> 
>   @override
>   CustomPageViewScrollPhysics applyTo(ScrollPhysics ancestor) {
>     return CustomPageViewScrollPhysics(parent: buildParent(ancestor));
>   }
> 
>   @override
>   SpringDescription get spring => const SpringDescription(
>         mass: 80,
>         stiffness: 100,
>         damping: 1,
>       );
> }
> ```
> 
> It can be used in the PageView constructor like this:
> 
> ```
> PageView(... physics: const CustomPageViewScrollPhysics(),)
> ```

Damn, amazing! Thank you so much.

**Comment by WangPe1n** [comment] 2021-09-15 08:23
还就那个牛逼  👍

**Comment by markusaksli-nc** [comment] 2021-11-10 16:23
FYI https://github.com/flutter/flutter/pull/91987 added this for TabBarView

**Comment by Sunbreak** [comment] 2022-03-15 12:25
We'd better close it in favor of https://github.com/flutter/flutter/issues/38357

**Comment by Katanabiz** [comment] 2022-05-23 15:29
Alxamdullilax

**Comment by rzrobert** [comment] 2022-12-20 10:58
> 还就那个牛逼 👍

还是你的评论通俗易懂！

**Comment by Piinks** [comment] 2023-02-21 20:31
Based on the comments above, I am going to close this as a dupe of https://github.com/flutter/flutter/issues/38357. 
Please follow that issue for updates. If we missed something here, let us know and we can take another look. Thank you!

**Closed by Piinks** 2023-02-21 20:31 UTC
Labels: framework, f: material design, a: fidelity, f: scrolling, proposal
