### ISSUE TITLE
Should enable ExpansionTile to be programmatically expanded/collapsed

### ISSUE THREAD

**Issue by csells** [flutter/flutter#63723] opened 2020-08-13 23:48 UTC
## Use case
The ExpansionTile has no way to enable it to be expanded/collapsed programmatically. For example, if you wanted to ensure that an ExpansionTile is open because you've changed the collapsed content, there's no efficient way to do so. The "recommended" solution to this problem currently is to [change the key value to force the ExpansionTile to be recreated](https://dartpad.dev/44d1ba5de3cd9e25af749c1a42c62209), using the initiallyExpanded value to force an expansion state, which can be very inefficient.

![expansion_list_forced_expansion](https://user-images.githubusercontent.com/2568253/90197816-b0cf0400-dd84-11ea-9d02-deab6450994e.gif)

## Proposal
The ExpansionTile should include a controller that allows it to be programmatically expanded/collapsed following the standard pattern in Flutter.

## References
- https://github.com/flutter/flutter/pull/56210
- https://github.com/flutter/flutter/issues/7024

**Comment by csells** [comment] 2020-08-13 23:48
cc @goderbauer

**Comment by Nuytemans-Dieter** [comment] 2020-08-14 17:07
Closely related to #60387

**Comment by goderbauer** [comment] 2020-08-14 17:49
Duplicate of https://github.com/flutter/flutter/issues/60387.

**Closed by goderbauer** 2020-08-14 17:49 UTC
Labels: f: material design, framework, proposal, severe: new feature
