### ISSUE TITLE
webview_flutter package not woking file pick

### ISSUE THREAD

**Issue by hpodong** [flutter/flutter#124186] opened 2023-04-05 06:40 UTC
I making hybrid app from webview_flutter
but i can"t file pick in only android
i set up permissions but not work help me plz

**Comment by danagbemava-nc** [comment] 2023-04-05 07:59
Please do not file multiple issues for the same bug.
Closing this as a duplicate of https://github.com/flutter/flutter/issues/124185

**Closed by danagbemava-nc** 2023-04-05 07:59 UTC
Labels: in triage
