### ISSUE TITLE
Can't render anything useful

### ISSUE THREAD

**Issue by steeling** [flutter/flutter#73393] opened 2021-01-06 05:07 UTC
I'm new to flutter, but the learning curve seems steep... How am I supposed to know what Widget needs to reside under which widget? I am constantly getting 'constraints.hasBoundedWidth': is not true.

errors, or overflow bottom errors. What I'm trying to do is relatively simple, but results in a large amount of nested widgets.

Anyways, the bug I'm running into says the error description should be more detailed, and asks to file a github issue, so here I am.. 

What I'd like to have 2 columns within a scrollable view that can grow from a single textfield input, with said  text field statically placed at the bottom.

The code I have is

```
  Widget build(BuildContext context) {
    // TODO: let's create a form, that allows this to be modular.
    List<List<Widget>> columns = [[], []];
    // opts.localPlayers.map((player) => playerCard(player)).toList();

    int i = 0;
    for (Player p in opts.localPlayers) {
      columns[i++ % 2].add(playerCard(p));
    }
    return Align( // this is needed to center the thing..
        alignment: Alignment.center,
        child: Column( // using a column to encapsulate both the lists and text field below
          children: [ 
          SingleChildScrollView( // attempting to place the lists in here so i can scroll
              child: ConstrainedBox( // I think this is required when using a scrollview?
                  constraints: BoxConstraints(), // copied from stackoverflow
                  child: Row(children: [ // is a row the right thing here? my issue is when one list grows larger than the other, it expands the row, and the second list shifts down
                    Align(. // attempting to solve that shifting issue by throwing it within an alignment to topCenter.
                        alignment: Alignment.topCenter,
                        child: Expanded( // not sure why i need this, was getting errors at a previous stage without
                            child: ListView( // now i'm finally at my list.
                          shrinkWrap: true,
                          children: columns[0], // this is a list of ListTile, it may be empty
                        ))),
                    Align(
                        alignment: Alignment.topCenter,
                        child: Expanded(
                            child: ListView(
                          shrinkWrap: true,
                          children: columns[1],
                        ))),
                  ]))),
          Expanded(
              child: Form(
                  key: _formKey,
                  child: Column(children: [
                    Visibility(
                        visible: false,
                        child: TextFormField(validator: (value) {
                          if (opts.localPlayers.length < 2) {
                            return "need at least 2 players to play";
                          }
                          return null;
                        })),
                    Container(
                      width: 400.0,
                      child: TextField(
                        textAlign: TextAlign.center,
                        decoration: InputDecoration(
                            border: InputBorder.none, hintText: 'Add a player'),
                        focusNode: _focusNode,
                        autofocus: true,
                        controller: _controller,
                        onSubmitted: (val) {
                          setState(() {
                            opts.localPlayers.add(Player(val));
                            _controller.clear();
                            _focusNode.requestFocus();
                          });
                        },
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.all(16.0),
                      child: RaisedButton(
                        onPressed: () async {
                          if (_formKey.currentState.validate()) {
                            return;
                          }
                          GameClient cli = LocalGameClient();
                          String id = await cli.createGame(opts);

                          Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => Provider(
                                      create: (_) => cli,
                                      child: GamePage(id))));
                        },
                        child: Text("Create Game"),
                      ),
                    ),
                    // add button for create
                  ])))
        ]));
  }
```

**Comment by steeling** [comment] 2021-01-06 05:10
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1857 pos 16: 'constraints.hasBoundedWidth': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
ListView
lib/create_or_join.dart:98
When the exception was thrown, this was the stack
#2      RenderShrinkWrappingViewport.performLayout
package:flutter/…/rendering/viewport.dart:1857
#3      RenderObject.layout
package:flutter/…/rendering/object.dart:1777
#4      RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:120
#5      RenderObject.layout
package:flutter/…/rendering/object.dart:1777
#6      RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:120
...
The following RenderObject was being processed when the exception was fired: RenderShrinkWrappingViewport#97c39 relayoutBoundary=up19 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderShrinkWrappingViewport#97c39 relayoutBoundary=up19 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(unconstrained)
    size: MISSING
    axisDirection: down
    crossAxisDirection: right
    offset: ScrollPositionWithSingleContext#1ec59(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#a9c7e, ScrollDirection.idle)
    child 0: RenderSliverPadding#b95b4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: layoutOffset=None
        constraints: MISSING
        geometry: null
        padding: EdgeInsets(0.0, 0.0, 0.0, 21.0)
        textDirection: ltr
        child: RenderSliverList#f99ce NEEDS-LAYOUT NEEDS-PAINT
            parentData: paintOffset=Offset(0.0, 0.0)
            constraints: MISSING
            geometry: null
            no children current live

**Comment by steeling** [comment] 2021-01-06 05:17
I also get a lot of these errors:

The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Align widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  Column ← Expanded ← Align ← AddPlayerWidget ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← ⋯
When the exception was thrown, this was the stack
#0      RenderObjectElement._updateParentData.<anonymous closure>
package:flutter/…/widgets/framework.dart:5826
#1      RenderObjectElement._updateParentData
package:flutter/…/widgets/framework.dart:5842
#2      RenderObjectElement.attachRenderObject
package:flutter/…/widgets/framework.dart:5864
#3      RenderObjectElement.mount
package:flutter/…/widgets/framework.dart:5557
#4      MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6288
...



when playing around with moving expanded/alignment/etc.

I have to say overall that this is a pretty terrible debugging experience :/

**Comment by darshankawar** [comment] 2021-01-06 11:35
@steeling 
From the error log and description you shared, I see three below exceptions:

```
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.
```

```
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1857 pos 16: 'constraints.hasBoundedWidth': is not true.
2
```

`errors, or overflow bottom errors.`

All above exceptions indicates code implementation errors and are very common when you start learning Flutter. 
I'd suggest you to ask this question on StackOver flow, as these exceptions are not a bug in Flutter framework, but an issue with code implementation.

Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by darshankawar** 2021-01-06 11:35 UTC
