### ISSUE TITLE
Flutter crash when exiting message recording

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46161] opened 2019-12-05 16:29 UTC
https://buganizer.corp.google.com/issues/145678675.

**Comment by kf6gpe** [comment] 2019-12-05 16:30
cc @jason-simmons , who was looking at it last.

**Comment by jason-simmons** [comment] 2019-12-05 18:44
Is this a duplicate of https://github.com/flutter/flutter/issues/46111?

**Comment by gaaclarke** [comment] 2019-12-06 18:41
> Is this a duplicate of #46111?

Looks like it, they both reference the same buganizer issue: https://buganizer.corp.google.com/issues/145678675

**Closed by gaaclarke** 2019-12-06 18:41 UTC
Labels: customer: dream (g3), engine, severe: customer critical
