### ISSUE TITLE
flutter web failed to launch browser

### ISSUE THREAD

**Issue by simon-zhangmuye** [flutter/flutter#80424] opened 2021-04-14 11:29 UTC
Need help, I try to run flutter web from vscode console. but This is the warning I got. How can I solve this problem?
This is flutter --version and flutter doctor. No error.
```
PS C:\flutterProject\webapptest> flutter --version
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (12 days ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
PS C:\flutterProject\webapptest> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.959], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code, 32-bit edition (version 1.39.2)
[√] VS Code, 64-bit edition (version 1.55.1)
[√] Connected device (1 available)
```
This is the error when I run flutter run -d chrome -v

```
PS C:\flutterProject\webapp> flutter run -d chrome -v
[  +99 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +256 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] b1395592de68cc8ac4522094ae59956dd21a91db
[        ] executing: [C:\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[ +267 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +45 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +212 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[ +180 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +259 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +187 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +139 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +98 ms] executing: C:\Users\muyez\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +837 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +181 ms] executing: C:\Users\muyez\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +31 ms] Skipping pub get: version match.
[ +170 ms] Generating C:\flutterProject\webapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +544 ms] Launching lib\main.dart on Chrome in debug mode...
[ +148 ms] Updating assets
[ +109 ms] Waiting for connection from debug service on Chrome...
[ +158 ms] <- reset
[  +14 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\muyez\AppData\Local\Temp\flutter_tools.d9db2177\flutter_tool.c24e2039\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages        
C:\flutterProject\webapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\muyez\AppData\Local\Temp\flutter_tools.d9db2177\flutter_tools.4261b7d3 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[ +519 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[ +433 ms] List of devices attached


                    * daemon not running; starting now at tcp:5037
                    * daemon started successfully
[ +231 ms] List of devices attached
[+18785 ms] Waiting for connection from debug service on Chrome... (completed in 20.1s)
[   +1 ms] Synced 29.1MB.
[        ] <- accept
[   +1 ms] Caching compiled dill
[+30551 ms] Using 
[ +269 ms] [CHROME]:[0414/211445.870:ERROR:icu_util.cc(165)] Invalid file descriptor to ICU data received.
[+30180 ms] Failed to launch browser. Command used to launch it: C:\Users\muyez\AppData\Local\Google\Chrome\Application\chrome.exe
--user-data-dir=C:\Users\muyez\AppData\Local\Temp\flutter_tools.d9db2177\flutter_tools_chrome_device.71d6f2f --remote-debugging-port=5886 --disable-background-timer-throttling
--disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:5744
[   +5 ms] "flutter run" took 83,324ms.
[   +6 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at
           https://github.com/flutter/flutter/issues.
[   +2 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:278:11)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1325:9)
           #3      _rootRun (dart:async/zone.dart:1346:47)
           #4      _CustomZone.run (dart:async/zone.dart:1258:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
           #11     _rootRun (dart:async/zone.dart:1346:47)
           #12     _CustomZone.run (dart:async/zone.dart:1258:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #21     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #22     _rootRun (dart:async/zone.dart:1346:47)
           #23     _CustomZone.run (dart:async/zone.dart:1258:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #34     _rootRun (dart:async/zone.dart:1346:47)
           #35     _CustomZone.run (dart:async/zone.dart:1258:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:741:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:589:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2151:21)
           #44     _rootRunUnary (dart:async/zone.dart:1370:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:607:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:554:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1687:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1185:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[ +264 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +17 ms] Shutdown hooks complete
[        ] exiting with code 1
PS C:\flutterProject\webapp> flutter run -d web-service -v
[  +75 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +215 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [C:\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[ +228 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +45 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +172 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[ +154 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +246 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +168 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +143 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +101 ms] executing: C:\Users\muyez\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +397 ms] List of devices attached
[   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +62 ms] No devices found with name or id matching 'web-service'
[  +13 ms] "flutter run" took 622ms.
[  +28 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:442:7)
           <asynchronous suspension>
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +262 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

My chrome is the lastest version.
I tried many solutions from google, like using chrome 86, flutter clean,  reinstall flutter sdk and etc, but they all do not work. Please help.

**Comment by TahaTesser** [comment] 2021-04-14 13:01
Based on logs, this looks the same as https://github.com/flutter/flutter/issues/79225#issuecomment-809273737
Closing as duplicate of https://github.com/flutter/flutter/issues/79225

**Closed by TahaTesser** 2021-04-14 13:01 UTC
Labels: in triage

**Comment by simon-zhangmuye** [comment] 2021-04-14 18:34
> Based on logs, this looks the same as [#79225 (comment)](https://github.com/flutter/flutter/issues/79225#issuecomment-809273737)
> Closing as duplicate of #79225

No，it is not the same.

**Comment by TahaTesser** [comment] 2021-04-15 09:21
@simon-zhangmuye 
Please check the logs in https://github.com/flutter/flutter/issues/79225#issuecomment-809273737
make sure your Chrome browser is launched using https://github.com/flutter/flutter/issues/79225#issuecomment-810584914
