### ISSUE TITLE
Text weight in v3.16 different on previous version. In my theme config weight has not be changed.

### ISSUE THREAD

**Issue by ziqq** [flutter/flutter#139134] opened 2023-11-28 13:01 UTC
### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
<br />

<img width="685" alt="image" src="https://github.com/flutter/flutter/assets/20646071/ff785b1d-ceee-4241-9a14-0c740ca3b7d4">

<br />

<img width="355" src="https://github.com/flutter/flutter/assets/20646071/79f2c363-3d0e-4c9a-b2cf-45eedead8e37" /> <img width="355" src="https://github.com/flutter/flutter/assets/20646071/19a321be-2ffa-447d-9ac5-233068869f21" />

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (5 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment] 2023-11-29 08:02
Hi @ziqq 
What is your previous Flutter version? (Maybe related: https://github.com/flutter/flutter/issues/138386) 

Do you use default font family or any others? Could you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by ziqq** [comment] 2023-11-30 08:30
Hi @huycozy,

I use default font family.

Previous version one of the versions 3.13...

<details>
  <summary>TextTheme</summary>

  ```dart
  textTheme: TextTheme(
    displayLarge: TextStyle(
      letterSpacing: Platform.isIOS ? -0.3 : 0,
      fontWeight: FontWeight.bold,
      fontSize: _fontSizes.displayLarge,
      color: _lightScheme.labelsColors.primary,
    ),
    displayMedium: TextStyle(
      letterSpacing: Platform.isIOS ? -0.3 : 0,
      fontWeight: FontWeight.bold,
      fontSize: _fontSizes.displayMedium,
      color: _lightScheme.labelsColors.primary,
    ),
    displaySmall: TextStyle(
      letterSpacing: Platform.isIOS ? -0.3 : 0,
      fontWeight: FontWeight.w600,
      fontSize: _fontSizes.displaySmall,
      color: _lightScheme.labelsColors.primary,
    ),
    headlineMedium: TextStyle(
      letterSpacing: Platform.isIOS ? -0.3 : 0,
      height: 1.1,
      fontWeight: FontWeight.w500,
      fontSize: _fontSizes.headlineMedium,
      color: _lightScheme.labelsColors.primary,
    ),
    headlineSmall: TextStyle(
      letterSpacing: Platform.isIOS ? -0.3 : 0,
      fontWeight: FontWeight.w500,
      fontSize: _fontSizes.headlineSmall,
      color: _lightScheme.labelsColors.primary,
    ),
    bodyLarge: TextStyle(
      height: 1.45,
      letterSpacing: Platform.isIOS ? -0.41 : 0,
      fontWeight: FontWeight.w400,
      fontSize: _fontSizes.bodyLarge,
      color: _lightScheme.labelsColors.primary,
    ),
    bodyMedium: TextStyle(
      height: 1.35,
      letterSpacing: Platform.isIOS ? -0.24 : 0,
      fontWeight: FontWeight.w400,
      fontSize: _fontSizes.bodyMedium,
      color: _lightScheme.labelsColors.primary,
    ),
    bodySmall: TextStyle(
      height: 1.25,
      letterSpacing: Platform.isIOS ? -0.08 : 0,
      fontWeight: FontWeight.w400,
      fontSize: _fontSizes.bodySmall,
      color: _lightScheme.labelsColors.secondary,
    ),
    labelSmall: TextStyle(
      height: 1.15,
      fontWeight: FontWeight.w300,
      fontSize: _fontSizes.labelSmall,
      letterSpacing: Platform.isIOS ? -0.08 : 0,
      color: _lightScheme.labelsColors.secondary,
    ),
    ),
  ```
</details>

**Comment by ziqq** [comment] 2023-12-01 12:41
Hi @huycozy,

The problem persists in version `3.16.2`.

<details>
  <summary>flutter doctor</summary>

  ```console

  [✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.1 23B81 darwin-arm64, locale ru-RU)
  [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
  [✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
  [✓] Chrome - develop for the web
  [✓] Android Studio (version 2022.3)
  [✓] VS Code (version 1.84.2)
  [✓] Connected device (6 available)
  [✓] Network resources
  ```
</details>

<details>
  <summary>Screenshots (3.16.2 / Old )</summary>

  <img src="https://github.com/flutter/flutter/assets/20646071/5aa8c604-4f84-403e-bb8a-1db5f703cb64" width="355" />
  <img src="https://github.com/flutter/flutter/assets/20646071/9f8fab7d-35d7-4a11-ab2d-c0563e258aca" width="355" />
</details />

**Comment by huycozy** [comment] 2023-12-04 05:05
Is the text thicker on 3.16.2? As I checked above, it looks thinner on the master channel. Could you switch to master and confirm this?

```
flutter channel master
flutter upgrade
```

**Comment by ziqq** [comment] 2023-12-04 06:17
> Is the text thicker on 3.16.2? As I checked above, it looks thinner on the master channel. Could you switch to master and confirm this?

Sorry in current time i can't switch to master.

**Comment by huycozy** [comment] 2023-12-05 03:41
Per our [triage](https://github.com/flutter/flutter/wiki/Triage) policy, if the issue is fixed on the latest Flutter channel, it should be closed. So please try checking this on master to see if it's fixed or not. Thanks!

**Comment by ziqq** [comment] 2023-12-06 13:20
Hi @huycozy,

The problem persists in version `3.18.0-2.0.pre.1`

<details>
  <summary>Screenshots</summary>

  | Old | 3.16.2 | 3.18.0-2.0.pre.1 |
  | ----------- | ----------- | ----------- |
  |<img src="https://github.com/flutter/flutter/assets/20646071/9f8fab7d-35d7-4a11-ab2d-c0563e258aca" width="355" />|<img src="https://github.com/flutter/flutter/assets/20646071/5aa8c604-4f84-403e-bb8a-1db5f703cb64" width="355" />|<img src="https://github.com/flutter/flutter/assets/20646071/ad15015b-f21f-424d-8852-171caeeb9dad" width="355" />|

</details />


<details>
  <summary>New problem in 3.18.0-2.0.pre.1</summary>

  | Old | 3.18.0-2.0.pre.1 |
  | ----------- | ----------- |
  |<img src="https://github.com/flutter/flutter/assets/20646071/ae7fc8c5-6b59-4f29-80b6-2590c9c0c5e3" width="355" />|<img src="https://github.com/flutter/flutter/assets/20646071/ad018c5d-46f6-4567-bb6f-b19bbcaf14cf" width="355" />|
</details />

**Comment by huycozy** [comment] 2023-12-07 04:52
I also checked this on beta channel (`3.18.0-0.1.pre`) but it's similar to master. Text is thinner on beta/main channel compared to stable 3.16.2. This is contrary to your results.

<details>
<summary>Demo on beta channel - iPhone 14 Pro, iOS 16.4</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/a5f14e2c-c836-4cab-928d-367721d417cd">

</details>

I'm not sure which channel you are being on (can't find `3.18.0-2.0.pre.1` on the repository). Could you share `flutter doctor -v`?

Also, which device are you checking on? Please also try [my sample code above](https://github.com/flutter/flutter/issues/139134#issuecomment-1835434549) to make sure we are examining the same example.

**Comment by ziqq** [comment] 2023-12-07 06:46
I use real device `iPhone XS` with iOS version `16.7.2`.

<details>
  <summary>Flutter doctor</summary>

  ```console
  flutter git:(master) flutter doctor

  [✓] Flutter (Channel master, 3.18.0-2.0.pre.1, on macOS 14.1.1 23B81 darwin-arm64, locale ru-RU)
  [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
  [✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
  [✓] Chrome - develop for the web
  [✓] Android Studio (version 2022.3)
  [✓] VS Code (version 1.84.2)
  [✓] Connected device (5 available)
  [✓] Network resources
  ```
</details>

<details>
  <summary>Demo on master channel - iPhone 14 iOS 17.0 | Flutter 3.18.0-2.0.pre.1</summary>
  
  <img width="350" src="https://github.com/flutter/flutter/assets/20646071/c43365aa-1260-4b99-8139-76ada433c1af">
</details>

<details>
  <summary>Demo on master channel - iPhone 12 iOS 17.0 | Flutter 3.18.0-2.0.pre.1</summary>

  <img width="350" src="https://github.com/flutter/flutter/assets/20646071/0890b6f4-75a5-4081-9bb4-8dc363328e8e">
  <img width="350" src="https://github.com/flutter/flutter/assets/20646071/4a8f1453-03ae-48b8-93f7-c5bd71ee3993">
</details>



<details>
  <summary>Flutter doctor</summary>

  ```console
  flutter git:(stable) flutter doctor

  [✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.1 23B81 darwin-arm64, locale ru-RU)
  [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
  [✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
  [✓] Chrome - develop for the web
  [✓] Android Studio (version 2022.3)
  [✓] VS Code (version 1.84.2)
  [✓] Connected device (6 available)
  [✓] Network resources
  ```
</details>

<details>
  <summary>Demo on stable channel - iPhone 14 iOS 17.0 | Flutter 3.16.2</summary>
  
  <img width="350" src="https://github.com/flutter/flutter/assets/20646071/63fef505-b2b9-4aaa-bd9c-7ef3c19e3869">
</details>

<details>
  <summary>Demo on stable channel - iPhone 12 iOS 17.0 | Flutter 3.16.2</summary>

  <img width="350" src="https://github.com/flutter/flutter/assets/20646071/395ef2da-2191-476a-849f-862938de9be0">
  <img width="350" src="https://github.com/flutter/flutter/assets/20646071/5c8e4941-3efe-4f88-9615-62d8dac6510f">
</details>

<details>
  <summary>My extended sample</summary>

  ```dart
  import 'dart:io';
  
  import 'package:flutter/material.dart';
  
  const _fontSizes = UiKitFontSizes(
    displayLarge: 24.0,
    displayMedium: 22.0,
    displaySmall: 20.0,
    headlineLarge: 20.0,
    headlineMedium: 18.0,
    headlineSmall: 17.0,
    bodyLarge: 17.0,
    bodyMedium: 15.0,
    bodySmall: 14.0,
    labelSmall: 13.0,
  );
  
  void main() async {
    runApp(
      MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          platform: TargetPlatform.iOS,
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
          textTheme: TextTheme(
            displayLarge: TextStyle(
              letterSpacing: Platform.isIOS ? -0.3 : 0,
              fontWeight: FontWeight.bold,
              fontSize: _fontSizes.displayLarge,
            ),
            displayMedium: TextStyle(
              letterSpacing: Platform.isIOS ? -0.3 : 0,
              fontWeight: FontWeight.bold,
              fontSize: _fontSizes.displayMedium,
            ),
            displaySmall: TextStyle(
              letterSpacing: Platform.isIOS ? -0.3 : 0,
              fontWeight: FontWeight.w600,
              fontSize: _fontSizes.displaySmall,
            ),
            headlineLarge: TextStyle(
              letterSpacing: Platform.isIOS ? -0.3 : 0,
              height: 1.1,
              fontWeight: FontWeight.w600,
              fontSize: _fontSizes.headlineMedium,
            ),
            headlineMedium: TextStyle(
              letterSpacing: Platform.isIOS ? -0.3 : 0,
              height: 1.1,
              fontWeight: FontWeight.w500,
              fontSize: _fontSizes.headlineMedium,
            ),
            headlineSmall: TextStyle(
              letterSpacing: Platform.isIOS ? -0.3 : 0,
              fontWeight: FontWeight.w500,
              fontSize: _fontSizes.headlineSmall,
            ),
            bodyLarge: TextStyle(
              height: 1.45,
              letterSpacing: Platform.isIOS ? -0.41 : 0,
              fontWeight: FontWeight.w400,
              fontSize: _fontSizes.bodyLarge,
            ),
            bodyMedium: TextStyle(
              height: 1.35,
              letterSpacing: Platform.isIOS ? -0.24 : 0,
              fontWeight: FontWeight.w400,
              fontSize: _fontSizes.bodyMedium,
            ),
            bodySmall: TextStyle(
              height: 1.25,
              letterSpacing: Platform.isIOS ? -0.08 : 0,
              fontWeight: FontWeight.w400,
              fontSize: _fontSizes.bodySmall,
            ),
            labelSmall: TextStyle(
              height: 1.15,
              fontWeight: FontWeight.w300,
              fontSize: _fontSizes.labelSmall,
              letterSpacing: Platform.isIOS ? -0.08 : 0,
            ),
          ),
        ),
        home: const MyApp(),
      ),
    );
  }
  
  class MyApp extends StatefulWidget {
    const MyApp({
      super.key,
    });
  
    @override
    State<MyApp> createState() => _MyAppState();
  }
  
  class _MyAppState extends State<MyApp> {
    @override
    Widget build(BuildContext context) {
      return Scaffold(
        body: SafeArea(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Flexible(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text(
                      'Hello World',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 30,
                      ),
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Display Large',
                      style: Theme.of(context).textTheme.displayLarge,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Display Medium',
                      style: Theme.of(context).textTheme.displayMedium,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Display Small',
                      style: Theme.of(context).textTheme.displaySmall,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Headline Large',
                      style: Theme.of(context).textTheme.headlineLarge,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Hello World',
                      style: Theme.of(context).textTheme.headlineMedium,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Headline Medium',
                      style: Theme.of(context).textTheme.headlineSmall,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Body Large',
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Body Medium',
                      style: Theme.of(context).textTheme.bodyMedium,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Body Small',
                      style: Theme.of(context).textTheme.bodySmall,
                    ),
                  ],
                ),
              ),
              Flexible(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text(
                      'Привет Мир',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 30,
                      ),
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Большой',
                      style: Theme.of(context).textTheme.displayLarge,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Средний',
                      style: Theme.of(context).textTheme.displayMedium,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Маленький',
                      style: Theme.of(context).textTheme.displaySmall,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Заголовок большой',
                      style: Theme.of(context).textTheme.headlineLarge,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Заголовок средний',
                      style: Theme.of(context).textTheme.headlineMedium,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Заголовок маленький',
                      style: Theme.of(context).textTheme.headlineSmall,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Тело большое',
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Тело Среднее',
                      style: Theme.of(context).textTheme.bodyMedium,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Тело маленькое',
                      style: Theme.of(context).textTheme.bodySmall,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      );
    }
  }
  
  @immutable
  class UiKitFontSizes {
    final double displayLarge;
    final double displayMedium;
    final double displaySmall;
    final double headlineLarge;
    final double headlineMedium;
    final double headlineSmall;
    final double bodyLarge;
    final double bodyMedium;
    final double bodySmall;
    final double labelSmall;
  
    const UiKitFontSizes({
      required this.displayLarge,
      required this.displayMedium,
      required this.displaySmall,
      required this.headlineLarge,
      required this.headlineMedium,
      required this.headlineSmall,
      required this.bodyLarge,
      required this.bodyMedium,
      required this.bodySmall,
      required this.labelSmall,
    });
  
    UiKitFontSizes copyWith({
      double? displayLarge,
      double? displayMedium,
      double? displaySmall,
      double? headlineLarge,
      double? headlineMedium,
      double? headlineSmall,
      double? bodyLarge,
      double? bodyMedium,
      double? bodySmall,
      double? labelSmall,
    }) {
      return UiKitFontSizes(
        displayLarge: displayLarge ?? this.displayLarge,
        displayMedium: displayMedium ?? this.displayMedium,
        displaySmall: displaySmall ?? this.displaySmall,
        headlineLarge: headlineLarge ?? this.headlineLarge,
        headlineMedium: headlineMedium ?? this.headlineMedium,
        headlineSmall: headlineSmall ?? this.headlineSmall,
        bodyLarge: bodyLarge ?? this.bodyLarge,
        bodyMedium: bodyMedium ?? this.bodyMedium,
        bodySmall: bodySmall ?? this.bodySmall,
        labelSmall: labelSmall ?? this.labelSmall,
      );
    }
  }
  ```
</details>

**Comment by huycozy** [comment] 2023-12-07 07:50
It's similar to my results above between stable and master channels. On master channel, the text is thinner than on stable channel. This might be related to a refactor recently: https://github.com/flutter/flutter/commit/e84f1296ac4b9f4d04dff5750ff737eec16867e4 (Refactor to use Apple system fonts)

I'm not quite sure if this is an intentional change or a bug. Will label this for other's insights. Thanks for your patience.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (23 hours ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.18.0-7.0.pre.14, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.18.0-7.0.pre.14 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c22c19b6e2 (4 hours ago), 2023-12-06 15:13:17 -0800
    • Engine revision 347f506a34
    • Dart version 3.3.0 (build 3.3.0-198.0.dev)
    • DevTools version 2.30.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by MitchellGoodwin** [comment] 2023-12-07 08:39
> It's similar to my results above between stable and master channels. On master channel, the text is thinner than on stable channel. This might be related to a refactor recently: [e84f129](https://github.com/flutter/flutter/commit/e84f1296ac4b9f4d04dff5750ff737eec16867e4) (Refactor to use Apple system fonts)

That commit did two things that are affecting things here on master.
1. It made it so that larger texts in the theme were more compacted in, in order to match iOS typography. In the Material theme, this affected `displayLarge`, `displayMedium`, `displaySmall`, `headlineLarge`, `headlineMedium`, `headlineSmall`, and `titleLarge`. This was intended.
2. It broke most font weights for iOS system fonts. So the default fonts on iOS at all sizes. See here #139689. The fix for that is on the way.

To use the behavior before that, set the `fontFamily` to '.SF Pro Text' in your themes.

However, this only explains some things on master. I have no idea what could be affecting fonts pre 3.18

**Comment by MitchellGoodwin** [comment] 2023-12-07 17:30
Can the issue be reproduced on master with the font family set to ".SF Pro Text"? And maybe with an image and explanation of which text is rendering incorrectly and what the requested font weight is for that text?

**Comment by MitchellGoodwin** [comment] 2024-01-22 21:03
The other font weight issue has been resolved on master. Is this issue still persisting?

**Comment by hellohuanlin** [comment] 2024-01-22 21:35
@MitchellGoodwin can you suggest a priority label to this issue?

**Comment by MitchellGoodwin** [comment] 2024-01-23 17:29
I'm not sure if exactly what the issue is, or if it is still there. @ziqq @hellohuanlin there was a recent change to default iOS font weights, does this still persist on master?

**Closed** 2024-02-06 10:08 UTC
Labels: platform-ios, waiting for customer response, framework, engine, a: typography, has reproducible steps, team-ios, found in release: 3.18
