### ISSUE TITLE
In the isolate, SharedPreferences data cannot be synchronized in real time

### ISSUE THREAD

**Issue by dabpop139** [flutter/flutter#61529] opened 2020-07-15 10:11 UTC
```Dart
cronStock() async {
    _stockCode = _stockCodeController.value.text;
    _growRate = _growRateController.value.text;
    _reduceRate = _reduceRateController.value.text;

    ……

    saveData();
    refreshStock(true);

    await AndroidAlarmManager.periodic(const Duration(seconds: 30), periodicAlarmID, refreshStock, wakeup: true);
}

saveData() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.reload();
    try {
        print('0001 saveData: '+DateTime.now().toString());
        prefs.setString('stock_prefix', stockPrefix);
        prefs.setString('stock_code', _stockCodeController.value.text);
        prefs.setDouble('grow_rate', double.parse(_growRateController.value.text));
        prefs.setDouble('reduce_rate', double.parse(_reduceRateController.value.text));
    } on FormatException catch(e) {

    } catch (e) {
        // No specified type, handles all
    }
}

……

refreshStock([bool isManual = false]) {
    print('0002 refreshStock afterTimer: '+DateTime.now().toString());

    Future<List> stockShared = getShared();
    stockShared.then((List shared) {

        print('isManual: $isManual');
        print('shareData: $shared');

    });
}

Future<List> getShared() async {
    print('getShared');
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.reload();
    return [
        prefs.getString('stock_prefix'),
        prefs.getString('stock_name'),
        prefs.getString('stock_code'),
        prefs.getDouble('grow_rate'),
        prefs.getDouble('reduce_rate'),

        // 当前值
        prefs.getString('stock_price'),
        prefs.getDouble('stock_rate'),
        prefs.getInt('rate_color'),
    ];
}
```

**Comment by TahaTesser** [comment] 2020-07-15 10:59
Hi @dabpop139 
This is currently not possible as far as i know,  `shared_preference` uses method channel to communicate to native platform and you cannot call it using another isolate

Closing as duplicate of https://github.com/flutter/flutter/issues/13937  If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-15 10:59 UTC

**Comment by kirill-21** [comment] 2021-06-27 17:27
> Hi @dabpop139
> This is currently not possible as far as i know, `shared_preference` uses method channel to communicate to native platform and you cannot call it using another isolate [Reference](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences_platform_interface/lib/method_channel_shared_preferences.dart)
> 
> Closing as duplicate of #13937 If you disagree, please write in the comments and I will reopen it.
> Thank you

So what is the workaround?
