### ISSUE TITLE
When running with web-server device, the initial empty white page should contain a hint about using the Dart debug extension

### ISSUE THREAD

**Issue by mfgabriel92** [flutter/flutter#48803] opened 2020-01-14 13:02 UTC
## Steps to Reproduce

1. Create a Flutter project with web enabled
2. Open it on Visual Studio Code
3. Select **Web Server (web-javascript)** as the device
3. Select the **Debug and Run** tab
4. Press **Run with Dart & Flutter** button

**Expected results:**
The project to run normally and see the elements on the screen.

**Actual results:**
It opens a tab on Chrome, but VSCode is stuck at **Attempting to connect to browser instance..**. It will work if run `flutter run -d web-server`, but it will always require me to press 'r' on the Terminal. It also works on Android Studio.

<details>
  <summary>Logs</summary>

It's a newly created project, but
```
❯ flutter analyze
No issues found! (ran in 1.2s)
```

```
❯ flutter doctor -v
[✓] Flutter (Channel master, v1.13.9-pre.79, on Linux, locale en_US.UTF-8)
    • Flutter version 1.13.9-pre.79 at /home/gabriel/.flutter-sdk
    • Framework revision 9eb9ea0ffa (7 hours ago), 2020-01-13 21:30:42 -0800
    • Engine revision 0235a50843
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 28c335d5a2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/gabriel/.android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```
</details>

Maybe it's a VSCode extension issue?

**Comment by DanTup** [comment] 2020-01-14 21:32
Can you try:

- Run the **Dart: Capture Logs** command from the VS Code command palette
- Leaving everything ticked *except Analysis Server*
- Reproduce the issue
- Leave the "Attempting to connect..." for at least 60 seconds
- Click the **Cancel** button on the logging prompt
- Review the log for anything sensitive
- Attach log here (or paste into a gist, and paste the link here)

Thanks!

**Comment by DanTup** [comment] 2020-01-14 21:35
Sorry, I mis-read the issue. When using the **Web Server** device, you would need to use the [Dart Debug Chrome Extension](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm). Unless you have reason to use this (it's designed to support remote environments like VS Remoting/VS Online/GitPod - though it is not complete) you should instead use the **Chrome** device.

**Comment by mfgabriel92** [comment] 2020-01-15 01:45
Hi @DanTup. Thanks for the response, but how do I use it? I installed the extension but things remain the same. 

I am contenting myself with Chrome device, but I dislike it opening a new window without my account logged in.

**Comment by DanTup** [comment] 2020-01-15 08:01
When the "white page" loads, you need to click the Dart button that was added to the top of the browser by the extension. (Note: that work in VS Code is not complete and might not all work correctly).

I think the reason Chrome launches in a clean profile is to enable the debug protocol (using the dev extension provides another way to achieve the same thing, but is less seamless).

Let me know if you hit any issues using this so I can check if they're known/incomplete or something I need to fix. Thanks!

**Comment by mfgabriel92** [comment] 2020-01-15 18:25
Is there a way not to open a new profile on Chrome?

**Comment by DanTup** [comment] 2020-01-15 19:15
Based on the comments here:

https://github.com/flutter/flutter/blob/ee7a37f1d3f12ca815d755a557f16765942897a4/packages/flutter_tools/lib/src/web/chrome.dart#L124-L127

it seems like a clean profile may be required to force a new instance, which is required to run with the debug port (I presume otherwise it will re-use any existing Chrome instance that may not have been launched with the debug port). @jonahwilliams may know more though.

**Comment by yjbanov** [comment] 2020-01-16 23:25
Is there anything we can fix in Flutter or VSCode to make this smoother?

**Comment by mdebbar** [comment] 2020-01-16 23:30
> Is there a way not to open a new profile on Chrome?

You could try using the `--no-web-browser-launch` flag. That would prevent the flutter tool from launching a Chrome instance. So you could use your own Chrome instance and connect to the server using the [Dart Debug Extension](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm).

/cc @jonahwilliams

**Comment by DanTup** [comment] 2020-01-17 09:47
The `--no-web-browser-launch` flag was removed in #44263 as part of the web-server work (it's the best way to run without Flutter spawning Chrome).

It's a bit confusing that the page just renders white and the user needs to know about the Dart Debug Extension. It'd be nice if we could show a message in place of that white screen with a link to the Dart Debug Extension and instructions to click the button (though I don't know if this is possible - @jonahwilliams may be more familiar with it - if it's possible we could use this issue as a request for that).

@mfgabriel92 if you install the Dart Debug Extension and click its button when you get the white page, does everything otherwise work for you?

**Comment by jonahwilliams** [comment] 2020-01-19 22:20
We might be able to inject some html into the served client containing debug extension instructions.

**Comment by mdebbar** [comment] 2020-01-21 20:55
FYI, here's a related issue that I filed some time ago: https://github.com/flutter/flutter/issues/42662. @jonahwilliams feel free to merge it with this one if you think it's a duplicate.

**Comment by DanTup** [comment] 2020-02-24 16:01
I updated the title of this issue to better reflect what this issue is now about, but I think @mdebbar is correct - this just seems to be a dupe of #42662 now. They're in different milestones though - I'm not sure which is correct.

**Comment by andrew-tpz** [comment] 2020-12-04 07:50
[ChromiumLauncher](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/chrome.dart) starts Chrome with "--disable-extensions" argument, so there is no "Dart debug extension" button in new Chrome instance.

**Comment by DanTup** [comment] 2020-12-07 17:08
@andrew-tpz you shouldn't need the Dart Debug extension when having Flutter launch Chrome (using the chrome device), it's only for when using the web-server device (where Flutter can't otherwise get a connection to the debugger because it didn't launch the browser).

**Comment by jonahwilliams** [comment] 2021-04-23 16:27
Going to follow up this issue in https://github.com/flutter/flutter/issues/80987 with the proposed solution noted

**Closed by jonahwilliams** 2021-04-23 16:27 UTC
Labels: P4, platform-web, tool
