### ISSUE TITLE
Complicated project setup in windows

### ISSUE THREAD

**Issue by ahmedtamseer** [flutter/flutter#55197] opened 2020-04-20 12:14 UTC
I gave up flutter, after failed to setup my first startup project to run for two days. I have wasted my time and many GB of internet just to make it run. No proper error message in terminal.

First it was gradle error, then kotlin, then it hung up in gradle assm.... .

I was inspired to use flutter, but now I am frustrated. 

There should be some document to tell which gradle, kotlin, and Android sdk version should be used to a particular flutter sdk.

**Comment by TahaTesser** [comment] 2020-04-20 12:27
Hi @ahmedtamseer 
You can follow this [Flutter install on Windows](https://flutter.dev/docs/get-started/install/windows).
It has all the steps you need
When you done the setup, can you please provide your `flutter doctor -v` and `flutter run --verbose` from root of your project? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
Thank you

**Comment by ahmedtamseer** [comment] 2020-04-29 14:37
I followed your instructions

Below are the result

**1) First command**
$ flutter doctor -v                                                                                                                                                                                                                                                                                                                                                                               [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.16299.431], locale en-US)                                                                                         • Flutter version 1.12.13+hotfix.9 at C:\src\flutter                                                                                                                                             • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700                                                                                                                         • Engine revision af51afceb8                                                                                                                                                                     • Dart version 2.7.2                                                                                                                                                                                                                                                                                                                                                                          [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)                                                                                                                     • Android SDK at D:\Users\Ahamed\AppData\Local\Android\sdk                                                                                                                                       • Android NDK location not configured (optional; useful for native profiling support)                                                                                                            • Platform android-29, build-tools 29.0.3                                                                                                                                                        • ANDROID_HOME = D:\Users\Ahamed\AppData\Local\Android\sdk                                                                                                                                       • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java                                                                                                                           • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)                                                                                                                    • All Android licenses accepted.                                                                                                                                                                                                                                                                                                                                                              [√] Android Studio (version 3.6)                                                                                                                                                                     • Android Studio at C:\Program Files\Android\Android Studio                                                                                                                                      • Flutter plugin version 45.1.1                                                                                                                                                                  • Dart plugin version 192.7761                                                                                                                                                                   • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)                                                                                                                                                                                                                                                                                                                 [√] VS Code, 32-bit edition (version 1.44.2)                                                                                                                                                         • VS Code at C:\Program Files (x86)\Microsoft VS Code                                                                                                                                            • Flutter extension version 3.9.1                                                                                                                                                                                                                                                                                                                                                             [√] Connected device (1 available)                                                                                                                                                                   • Redmi Note 7 • 4cecc4f5 • android-arm64 • Android 9 (API 28)                                                                                                                                                                                                                                                                                                                                • No issues found!
--


**2) Second Command**


$ flutter run --verbose                                                                                                                                                                          [ +104 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H                                                                                               [ +238 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H                                                                                                          [        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3                                                                                                                                              [        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags                                                                                                 [ +118 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags                                                                                                            [        ] v1.12.13+hotfix.9-0-gf139b1100                                                                                                                                                        [  +22 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}                                                                                                               [ +118 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}                                                                                                                          [        ] origin/stable                                                                                                                                                                         [        ] executing: [C:\src\flutter\] git ls-remote --get-url origin                                                                                                                           [  +99 ms] Exit code 0 from: git ls-remote --get-url origin                                                                                                                                      [        ] https://github.com/flutter/flutter.git                                                                                                                                                [ +262 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD                                                                                                                          [ +107 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD                                                                                                                                     [        ] stable                                                                                                                                                                                [ +450 ms] executing: D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l                                                                                                [ +114 ms] Exit code 0 from: D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l                                                                                         [        ] List of devices attached                                                                                                                                                                         4cecc4f5               device product:lavender model:Redmi_Note_7 device:lavender transport_id:1                                                                                      [  +57 ms] D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4cecc4f5 shell getprop                                                                                            [ +313 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.                                                                                                        [  +13 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.                                                                                                [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.                                                                                                           [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.                                                                                                                [  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.                                                                                                       [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.                                                                                                         [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.                                                                                                         [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.                                                                                                     [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.                                                                                                     [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.                                                                                                    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.                                                                                                    [ +584 ms] Generating D:\practice\flutter\flutter_test\flutter_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java                                                   [ +102 ms] ro.hardware = qcom                                                                                                                                                                    [ +274 ms] Launching lib\main.dart on Redmi Note 7 in debug mode...                                                                                                                              [  +44 ms] executing: D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4cecc4f5 shell -x logcat -v time -t 1                                                                  [ +397 ms] Exit code 0 from: D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4cecc4f5 shell -x logcat -v time -t 1                                                           [        ] --------- beginning of main                                                                                                                                                                      04-29 20:04:22.157 I/DPMJ    ( 2840): \|REQ:RCVR\| DPM creating socket                                                                                                                  [  +26 ms] executing: D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe version                                                                                                   [   +4 ms] executing: D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4cecc4f5 logcat -v time -T 04-29 20:04:22.157                                                          [ +286 ms] Android Debug Bridge version 1.0.41                                                                                                                                                              Version 30.0.0-6374843                                                                                                                                                                           Installed as D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe                                                                                                         [  +11 ms] executing: D:\Users\Ahamed\AppData\Local\Android\sdk\platform-tools\adb.exe start-server                                                                                              [ +444 ms] Building APK                                                                                                                                                                          [  +57 ms] [!] Your app isn't using AndroidX.                                                                                                                                                    [   +4 ms]     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.                                                              [  +62 ms] Running Gradle task 'assembleDebug'...                                                                                                                                                [   +6 ms] gradle.properties already sets `android.enableR8`                                                                                                                                     [  +21 ms] Using gradle from D:\practice\flutter\flutter_test\flutter_app\android\gradlew.bat.                                                                                                   [  +73 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version                                                                                                              [ +564 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version                                                                                                       [        ] openjdk version "1.8.0_212-release"                                                                                                                                                              OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)                                                                                                                                   OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)                                                                                                                               [   +7 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version                                                                                                              [ +360 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version                                                                                                       [        ] openjdk version "1.8.0_212-release"                                                                                                                                                              OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)                                                                                                                                   OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)                                                                                                                               [   +8 ms] executing: [D:\practice\flutter\flutter_test\flutter_app\android\] D:\practice\flutter\flutter_test\flutter_app\android\gradlew.bat -Pverbose=true -Ptarget=D:\practice\flutter\flutt er_test\flutter_app\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug                                               [ +848 ms] Unzipping C:\Users\Ahamed\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip to C:\Users\Ahamed\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h1 6so49nn74lgtbb                                                                                                                                                                                   [   +5 ms] Exception in thread "main" java.util.zip.ZipException: error in opening zip file                                                                                                      [   +4 ms]      at java.util.zip.ZipFile.open(Native Method)                                                                                                                                     [        ]      at java.util.zip.ZipFile.(ZipFile.java:225)                                                                                                                                [        ]      at java.util.zip.ZipFile.(ZipFile.java:155)                                                                                                                                [        ]      at java.util.zip.ZipFile.(ZipFile.java:169)                                                                                                                                [        ]      at org.gradle.wrapper.Install.unzip(Install.java:214)                                                                                                                            [        ]      at org.gradle.wrapper.Install.access$600(Install.java:27)                                                                                                                        [        ]      at org.gradle.wrapper.Install$1.call(Install.java:74)                                                                                                                            [        ]      at org.gradle.wrapper.Install$1.call(Install.java:48)                                                                                                                            [        ]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)                                                                                      [        ]      at org.gradle.wrapper.Install.createDist(Install.java:48)                                                                                                                        [        ]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)                                                                                                          [        ]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)                                                                                                          [  +55 ms] Running Gradle task 'assembleDebug'... (completed in 1.9s)                                                                                                                            [   +5 ms] [!] Gradle threw an error while trying to update itself. Retrying the update...                                                                                                       [   +8 ms] [!] Your app isn't using AndroidX.                                                                                                                                                    [        ]     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.                                                              [   +2 ms] Running Gradle task 'assembleDebug'...                                                                                                                                                [   +1 ms] gradle.properties already sets `android.enableR8`                                                                                                                                     [   +7 ms] Using gradle from D:\practice\flutter\flutter_test\flutter_app\android\gradlew.bat.                                                                                                   [   +1 ms] executing: [D:\practice\flutter\flutter_test\flutter_app\android\] D:\practice\flutter\flutter_test\flutter_app\android\gradlew.bat -Pverbose=true -Ptarget=D:\practice\flutter\flutt er_test\flutter_app\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug                                               [ +654 ms] Unzipping C:\Users\Ahamed\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip to C:\Users\Ahamed\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h1 6so49nn74lgtbb                                                                                                                                                                                   [  +12 ms] Exception in thread "main" java.util.zip.ZipException: error in opening zip file                                                                                                      [        ]      at java.util.zip.ZipFile.open(Native Method)                                                                                                                                     [        ]      at java.util.zip.ZipFile.(ZipFile.java:225)                                                                                                                                [        ]      at java.util.zip.ZipFile.(ZipFile.java:155)                                                                                                                                [        ]      at java.util.zip.ZipFile.(ZipFile.java:169)                                                                                                                                [        ]      at org.gradle.wrapper.Install.unzip(Install.java:214)                                                                                                                            [        ]      at org.gradle.wrapper.Install.access$600(Install.java:27)                                                                                                                        [        ]      at org.gradle.wrapper.Install$1.call(Install.java:74)                                                                                                                            [        ]      at org.gradle.wrapper.Install$1.call(Install.java:48)                                                                                                                            [        ]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)                                                                                      [        ]      at org.gradle.wrapper.Install.createDist(Install.java:48)                                                                                                                        [        ]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)                                                                                                          [        ]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)                                                                                                          [  +57 ms] Running Gradle task 'assembleDebug'... (completed in 0.7s)                                                                                                                            [        ] [!] Gradle threw an error while trying to update itself. Retrying the update...                                                                                                       [  +26 ms] "flutter run" took 6,146ms.                                                                                                                                                           Gradle task assembleDebug failed with exit code 1                                                                                                                                                                                                                                                                                                                                                 #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)                                                                                                                          #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:431:7)                                                                                                                     #2      _asyncThenWrapperHelper. (dart:async-patch/async_patch.dart:73:64)                                                                                                    #3      _rootRunUnary (dart:async/zone.dart:1134:38)                                                                                                                                             #4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)                                                                                                                                      #5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)                                                                                                                         #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)                                                                                                    #7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)                                                                                                                        #8      Future._completeWithValue (dart:async/future_impl.dart:524:5)                                                                                                                            #9      Future._asyncComplete. (dart:async/future_impl.dart:554:7)                                                                                                            #10     _rootRun (dart:async/zone.dart:1126:13)                                                                                                                                                  #11     _CustomZone.run (dart:async/zone.dart:1023:19)                                                                                                                                           #12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)                                                                                                                                      #13     _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:965:23)                                                                                                        #14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)                                                                                                                                #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)                                                                                                                            #16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)                                                                                                              #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
--

**Comment by TahaTesser** [comment] 2020-04-30 07:01
Hi @ahmedtamseer 
Based on your logs, looks like your gradle isn't downloaded properly
Please check this [comment](https://github.com/flutter/flutter/issues/54712#issuecomment-614337346) for solution

You need to properly download gradle again so delete your `gradle-5.6.2-all` in `C:\Users\Ahamed\.gradle\wrapper\dists\g`  and run the app again until it proper downloads and launch the appp

```
C:\Users\Ahamed\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h1 6so49nn74lgtbb                                                                                                                                                                                   [   +5 ms] Exception in thread "main" java.util.zip.ZipException: error in opening zip file                                                                                                      [   +4 ms]      at java.util.zip.ZipFile.open(Native Method)                                                                                                                                     [        ]      at java.util.zip.ZipFile.(ZipFile.java:225)                                                                                                                                [        ]      at java.util.zip.ZipFile.(ZipFile.java:155)                                                                                                                                [        ]      at java.util.zip.ZipFile.(ZipFile.java:169)                                                                                                                                [        ]      at org.gradle.wrapper.Install.unzip(Install.java:214)                                                                                                                            [        ]      at org.gradle.wrapper.Install.access$600(Install.java:27)                                                                                                                        [        ]      at org.gradle.wrapper.Install$1.call(Install.java:74)                                                                                                                            [        ]      at org.gradle.wrapper.Install$1.call(Install.java:48)      
```

Thank you

**Comment by TahaTesser** [comment] 2020-05-22 12:48
Hi @ahmedtamseer 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution

**Closed by TahaTesser** 2020-05-22 12:48 UTC
Labels: in triage, waiting for customer response
