### ISSUE TITLE
List scrolling is not smooth

### ISSUE THREAD

**Issue by zsunkun** [flutter/flutter#43083] opened 2019-10-20 12:08 UTC
There is a list page in our application. I found that didn't scroll smoothly when I finished the page.So I tried to analyze it by using Timeline(device:HUAWEI P10).Then I found two problems:

Q1:UI Thread cost much time to build remain list items when the list scrolls for the first time. 
This is Timeline:
[dart-timeline-2019-9-20_first_scroll.json.zip](https://github.com/flutter/flutter/files/3747824/dart-timeline-2019-9-20_first_scroll.json.zip)
Deep levels, traversal takes much time：
![image](https://user-images.githubusercontent.com/5997059/67159226-85ea6e00-f374-11e9-887a-a310c6e19d3b.png)
Although I can avoid it by preload list items, but I don't think this is a good idea. I think my page requirement is not very complicated.But when I implemented this requirement, I found that the Widget has such a deep level and cost time.Is my usage incorrect? If not, when I have a more complicated requirement later, what should I do? I can't rely on preload.

Q2:GPU Thread's problem.After all the items are cached, we can ignore the time spent by the UI thread, UI Thread only cost 2~3ms average,GPU Thread cost 11ms average. It still not scroll smoothly in feel.But Timeline shows list performs well without dropping frames,Timeline like this:
[dart-timeline-2019-9-20_cached.json.zip](https://github.com/flutter/flutter/files/3747825/dart-timeline-2019-9-20_cached.json.zip)
![image](https://user-images.githubusercontent.com/5997059/67159241-ad413b00-f374-11e9-9ceb-a79e5859d315.png)

I used suspected that there are some problems in PointeEvent processing or animation simulation. But I found that if I replace the list item with a simpler layout, it gets smoother. Because of the item cache, they spend almost the same time on the UI thread.The only difference is the GPU Thread.So I think the page will become smooth if I can reduce the time spent on GPU thread.But I didn't find a place to optimize.Any suggestions appreciated！

I simplified the page code into a demo, hope it is useful.SourceCode:
[list_demo.zip](https://github.com/flutter/flutter/files/3747826/list_demo.zip)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel bd_1.5.4, v1.5.4-hotfix.3-pre.75, on Mac OS X 10.13.6 17G2208, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 3.0)
[✓] Connected device (1 available)

**Comment by kunit1** [comment] 2019-10-20 15:37
List scrolling performance should be fixed on a more recent version of flutter. Your current version 1.5.4 does not have this fix. Please try switching to the latest dev branch and report back if the issue is resolved.

**Comment by zsunkun** [comment] 2019-10-21 06:32
> List scrolling performance should be fixed on a more recent version of flutter. Your current version 1.5.4 does not have this fix. Please try switching to the latest dev branch and report back if the issue is resolved.

Which commit fixes the list scrolling performance?

When I switching to the latest dev branch, the problem is even more serious.The original UI Thread took 2~3ms after the item cache, and now it becomes 8~10ms.The GPU Thread has not changed.

**Comment by liyuqian** [comment] 2019-10-29 22:04
Regarding the UI thread, it seems a lot of time is spent on `LayoutRichText`. Some questions for our text expert @GaryQian :
1. Have you recently modified the rich text behaviors?
2. Are there metrics in https://flutter-dashboard.appspot.com/benchmarks.html that track rich text's build performance? If so, what's the trend recently?
3. Can you reproduce the janky scroll locally with the attached [list_demo](https://github.com/flutter/flutter/files/3747826/list_demo.zip)? If so, do you have any guesses of what's happening from the local testing?

Regarding the GPU thread, I believe that HUAWEI P10 has a 60Hz screen and having 11ms/frame should be as smooth as you can get. @kunit1 : can you please turn on the performance overlay, and shoot a slow-mo video of the scrolling (e.g., using an iPhone) so we can have a better understanding of what feels not smooth?

**Comment by zsunkun** [comment] 2019-10-30 13:48
> Regarding the UI thread, it seems a lot of time is spent on `LayoutRichText`. Some questions for our text expert @GaryQian :
> 
> 1. Have you recently modified the rich text behaviors?
> 2. Are there metrics in https://flutter-dashboard.appspot.com/benchmarks.html that track rich text's build performance? If so, what's the trend recently?
> 3. Can you reproduce the janky scroll locally with the attached [list_demo](https://github.com/flutter/flutter/files/3747826/list_demo.zip)? If so, do you have any guesses of what's happening from the local testing?
> 
> Regarding the GPU thread, I believe that HUAWEI P10 has a 60Hz screen and having 11ms/frame should be as smooth as you can get. @kunit1 : can you please turn on the performance overlay, and shoot a slow-mo video of the scrolling (e.g., using an iPhone) so we can have a better understanding of what feels not smooth?

Thanks for your reply.
About LayoutRichText, my colleague has fixed it, there is the pull request :https://github.com/flutter/engine/pull/13257. 
I think it's the reason why the UI Thread performance deteriorates when I switch to the latest dev branch. I have this fix on my branch. Even so, I think that it takes too much time to build an item when scrolling for the first time. Any suggestions for this situation?

About GPU Thread, I know why I feel that the scrolling is not smooth, I changed the FlutterView from SurfaceView to TextureView before. It feels better when I switch back to SurfaceView, even though they have the same Timeline data. It's my mistake, I didn't expect such a big difference.
But I still want to know what can be optimized for GPU Thread?
Is it reasonable to spend 11ms on this level of complexity? It takes nearly 16ms when I make the item's data(ranking.json) a bit more complicated.I am afraid that GPU Thread cannot cope with more complicated situations.

[list_demo_first_scrolls.json.zip](https://github.com/flutter/flutter/files/3789175/list_demo_first_scrolls.json.zip)

This is the Timeline when list_demo first scrolls.There are several frames in it that exceed 16ms on GPU Thread.

**Comment by liyuqian** [comment] 2019-11-06 07:49
@zsunkun : thanks for fixing the UI thread issue!

I have a good news on the GPU thread too. Your demo revealed a picture raster cache throttling bug https://github.com/flutter/flutter/issues/44252. By fixing it (https://github.com/flutter/engine/pull/13710), we'll have a ~25% speedup (4.3ms/frame to 3.3ms/frame on Moto G4). Please see the traces of your demo app before and after the fix: [list_demo_traces.zip](https://github.com/flutter/flutter/files/3813077/list_demo_traces.zip).

Previously we never noticed that bug because:
1. For simple and small list items, raster caching or not doesn't affect the performance much. Our tiles_scroll_perf test is such an example.
2. For complex and big list items, there are only about 3-4 items per screen if there's just a single list so our throttling bug isn't revealed. Our complex_layout_scroll_perf test is such an example.

Your demo app includes complex items on multiple lists that. The items would fill up the vertical space with 3-4 items, but they're scrolling horizontally with multiple lists so we're seeing an additional 3-4 items that are not cached.

I'll adapt your demo into our performance benchmark test, and then land https://github.com/flutter/engine/pull/13710 to confirm the fix. Thank you again for the fantastic demo!

**Comment by cbracken** [comment] 2019-11-25 18:36
@liyuqian can you provide an update on this issue? Is this still actively being worked on?

**Comment by liyuqian** [comment] 2019-11-25 21:57
This fix is https://github.com/flutter/engine/commit/9e6d360177580f68f1321b56da7fbffc300d9d3f landed , and we've observed the expected improvements in our newly test https://github.com/flutter/flutter/commit/a32fc986f3c636e64f9e34acac1ead7612340d97 . Closing this bug.

**Closed by liyuqian** 2019-11-25 21:57 UTC
Labels: a: typography, customer: headline, engine, f: scrolling, severe: customer blocker, severe: performance

**Comment by neobie** [comment] 2020-04-29 10:57
I am using latest version of flutter (1.12.13) as of today. Running on flutter.dev basic tutorial, the UI is not smooth at all. This includes, ListView, and push view, or any animations.
Downloading sample app (Flutter Catalog) from App Store also having same problem.

**Comment by liyuqian** [comment] 2020-04-29 19:08
@neobie : that's probably a different issue than the one that we fixed here. We'd encourage you to open a new issue using our [performance issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=created+via+performance+template&template=performance.md&title=).
