### ISSUE TITLE
Hot reload seems to be slower on windows machines

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#32204] opened 2019-05-07 15:00 UTC
Section 3 of [document](https://docs.google.com/document/d/1ComztlbIKQ6y0sJ0kMSCjG6w1jeDGrv4sfG4f0uI3SI/edit?ts=5cd0e6fa#) seems to indicate that hot reload on windows machine is slower than on linux or macOS.

**Comment by jonahwilliams** [comment] 2019-05-07 15:25
This is due to the performance of the windows filesystem during stat calls required for reload updates. The impact of this could be decreased by updating the flutter tool to use filesystem watchers instead of scanning directories, but this leaves the possibility for race conditions

**Comment by ZichangG** [comment] 2019-05-31 21:13
Did some tests with --verbose flag for flutter_gallery in /example/. 

Scanning 593 files takes around 75ms on Windows, 12 ms on Linux. The overall time spent has 80 to 150 ms difference. The other noticeable contributor is compiling dart to kernel. On Windows it takes 30 ms(with only 1 updated file), compared to 10ms on Linux.

But I am not able to reproduce the 400ms difference showed in the report. I suspect it may have a greater amount of files.

@jayoung-lee Hi, I tried to run your query but it cannot find the dataset. Do you have more info or some examples I can test with? Thanks.

**Comment by jayoung-lee** [comment] 2019-06-05 00:02
@ZichangG I can give you access to the BigQuery dataset. Could you send your ldap to me over the Chat or email?

**Comment by ZichangG** [comment] 2019-06-05 20:23
Correct a mistake in previous post. The compilation isn't slower on Windows. 
Scanning on windows simply takes much more time.

**Comment by zichangg** [comment] 2020-09-01 03:51
There is no actionable item. I'll remove myself.

**Comment by jonahwilliams** [comment] 2020-09-01 03:54
I'm going to close this as windows-specific improvements are infeasible

**Closed by jonahwilliams** 2020-09-01 03:54 UTC
Labels: P4, platform-windows, severe: performance, tool
