### ISSUE TITLE
Several questions about CupertinoWidget

### ISSUE THREAD

**Issue by isMeiying** [flutter/flutter#37371] opened 2019-08-01 07:09 UTC
### problem

> **1.Cannot call out the copy and paste menu bar when the `CupertinoTextField` is empty. I updated it #https://github.com/flutter/flutter/pull/37042, but the problem is still not solved. This situation can only be temporarily resolved when I type in the text and then call out the menu bar once.**

> **2.When the background is white, the horizontal lines in the dialog box are obviously invisible, and they can only be seen when the background is colored.**
> _`like this, it is faintly visible in the colored background, but on a white background it will disappear:`_ 
>
> ![49A896CBA83F042BA6797FDCC53CD631](https://user-images.githubusercontent.com/13428030/62270875-b273a580-b469-11e9-9ce1-27fc7547515d.jpg)

> **3.In the case of Chinese, part of the text in the `CupertinoTextField` menu bar is obviously cropped.**
> _`like this:`_
>
> ![B8C8B5280F4D7F1574964AB609675C59](https://user-images.githubusercontent.com/13428030/62271274-c8359a80-b46a-11e9-9398-7ed13a9ff716.jpg)

> **4.In case the `CupertinoTextField` has only hint and is Chinese, the cursor only shows a part, but input text will be fully displayed.**
> _`in before input:`_
>
> ![99A7299FBDE26BFD4DB9A2676602D951](https://user-images.githubusercontent.com/13428030/62271738-ef409c00-b46b-11e9-8517-54fed58c4dc9.jpg)
>
> _`in after input:`_
>
> ![988683232B9659C2BBECA51262BBE013](https://user-images.githubusercontent.com/13428030/62271754-fa93c780-b46b-11e9-9b8a-26272e0ea929.jpg)

> **5.In China, people prefer to use third-party keyboard programs. But unfortunately, in `Flutter CupertinoTextField`, the following shortcuts don't respond, but it's clear that the native `EditText` doesn't have this problem.** #https://github.com/flutter/flutter/issues/27880
> _`these shortcuts are copy, paste, select all, cut, ltrb select, delete text, etc...`_
>
> ![ACF4A9B87AD5B623F4D4E684D434D275](https://user-images.githubusercontent.com/13428030/62272215-29f70400-b46d-11e9-93c8-720d65719b63.jpg)

I hope that it can be solved as soon as possible, let flutter be perfect

**Comment by HansMuller** [comment] 2019-08-01 16:13
Thanks for the detailed report!

It would be best to break this into 5 separate issues.

**Comment by isMeiying** [comment] 2019-08-01 16:23
@HansMuller Thank you for your reply, I will standardize the question next time.

**Comment by justinmc** [comment] 2019-08-06 23:15
For number 1, can you try again on the master [channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)?  Here is a gif of how it works for me on master.  I tap to open the keyboard, then long-press the field, and the paste button shows up.

![long_press_empty](https://user-images.githubusercontent.com/389558/62583501-55ab2d00-b865-11e9-8ad7-9affc5772012.gif)

**Comment by jlcool** [comment] 2019-11-01 04:37
@justinmc This is a very obvious and urgent problem. It makes my application experience very bad ，This problem is the function of Android Chinese third-party input method, such as iFLYTEK input method and Sogou input method

**Comment by justinmc** [comment] 2019-11-01 20:59
@jlcool I think that problem (part no. 5 of this issue) may be related to https://github.com/flutter/flutter/issues/9419, which is about special IME keys that Flutter currently doesn't support.

I think we would need to add support for other key codes like this in the engine similar to [here](https://github.com/flutter/engine/blob/a5243c024c5241a297b2afed6473a187112388b7/shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java#L156) and the other conditions of the if statement.

**Comment by jlcool** [comment] 2019-11-03 06:29
@justinmc Thank you for your reply. I have been troubled by this problem for a long time. How long can I solve this problem

**Comment by justinmc** [comment] 2019-11-04 18:25
Me or someone else should get to this at some point.  In the meantime if you or anyone else wants to try fixing this and opening a PR, please feel free!

I think the first thing to do would be to log the `event.getKeyCode()` that is being sent when you press the buttons that aren't working.  Then, add support in the `if` statement [here](https://github.com/flutter/engine/blob/a5243c024c5241a297b2afed6473a187112388b7/shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java#L156) for each of the key codes that you want support for.

This takes place in the Flutter engine, so you would need to [compile the engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine) and run Flutter with `--local-engine=...` to be able to do this.

**Comment by jlcool** [comment] 2019-12-11 03:00
@justinmc It's a little difficult for me. I'll try, or I hope you can solve this problem. Thank you

**Comment by justinmc** [comment] 2020-01-13 19:00
I installed the Sogou keyboard and played around with it while watching what key events are sent to the engine.  I think that a generic fix for https://github.com/flutter/flutter/issues/9419 will likely solve a lot of the problems here, though there seemed to be a ton of features in that keyboard, so there could be some follow up needed.

**Comment by edman** [comment] 2020-02-28 19:27
We've just pushed a change adding support for many of the text editing controls mentioned at the 5th point of this issue.

Up/down don't behave well on texts with soft wrapping, but it does _something_.

**Comment by justinmc** [comment] 2020-03-18 23:30
I confirmed that the keyboard support added in https://github.com/flutter/engine/pull/15560 works for the Chinese Sogou keyboard too.

I'm going to close this issue, since it really should be several separate issues.  If anyone is still seeing any specific problems listed above, please open a new issue for each and link this issue.

**Closed by justinmc** 2020-03-18 23:30 UTC
Labels: a: fidelity, a: text input, f: cupertino, framework
