### ISSUE TITLE
[tool_crash] ProcessException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. Command: C:\Android\android-sdk\emulator\emulator.exe, OS error code: 225

### ISSUE THREAD

**Issue by Bristotle** [flutter/flutter#97218] opened 2022-01-25 16:53 UTC
## Command
```
flutter emulators
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
 Command: C:\Android\android-sdk\emulator\emulator.exe, OS error code: 225
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:565:18)
#3      Process.run (dart:io-patch/process_patch.dart:47:12)
#4      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:74:22)
#5      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:669:24)
#6      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#7      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:668:12)
#8      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:267:59)
#9      AndroidEmulators._getEmulatorAvds (package:flutter_tools/src/android/android_emulator.dart:65:56)
#10     AndroidEmulators.emulators (package:flutter_tools/src/android/android_emulator.dart:56:43)
#11     EmulatorManager.getAllAvailableEmulators.<anonymous closure> (package:flutter_tools/src/emulator.dart:82:41)
#12     EmulatorManager.getAllAvailableEmulators.<anonymous closure> (package:flutter_tools/src/emulator.dart:81:67)
#13     Future.forEach.<anonymous closure> (dart:async/future.dart:495:26)
#14     Future.doWhile.<anonymous closure> (dart:async/future.dart:535:26)
#15     _rootRunUnary (dart:async/zone.dart:1436:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#18     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
#19     Future.doWhile (dart:async/future.dart:551:18)
#20     Future.forEach (dart:async/future.dart:493:12)
#21     EmulatorManager.getAllAvailableEmulators (package:flutter_tools/src/emulator.dart:81:18)
#22     EmulatorsCommand._listEmulators (package:flutter_tools/src/commands/emulators.dart:93:33)
#23     EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:56:13)
#24     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19044.1466], locale en-GB)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Android\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\Bristotle\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      C:\Android\android-sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:78:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:413:54)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart)
      <asynchronous suspension>
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:170:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:515:34)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>


! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by christopherfujino** [comment] 2022-01-25 19:20
I am closing this as a duplicate of https://github.com/flutter/flutter/issues/61997. The Flutter SDK cannot do anything if you are using a virus scanner that is flagging the Android SDK emulator. I can say that this is a legitimate part of the Android SDK, and you should allow-list it, per the linked issue.

**Closed by christopherfujino** 2022-01-25 19:20 UTC
