### ISSUE TITLE
OOM crashes in GC

### ISSUE THREAD

**Issue by AKZHW** [flutter/flutter#108723] opened 2022-08-01 09:28 UTC
![image](https://user-images.githubusercontent.com/9245326/182118110-7c75e6d2-3c87-4eb1-ade0-1f8a29964e4a.png)
![image](https://user-images.githubusercontent.com/9245326/182118251-c87230ef-051d-4303-9a8e-70c3f6a95fb3.png)
![image](https://user-images.githubusercontent.com/9245326/182118341-ce008587-e1dc-441c-ae90-b219a25696cd.png)

 I have some crash

**Comment by AKZHW** [comment] 2022-08-01 09:44
flutter 2.10.4

**Comment by mraleph** [comment] 2022-08-01 10:52
All of these are OOM crashes. It might be that your application is leaking memory or it can be that the phone itself is low on resources. Either way - this is unactionable without detailed reproductions.

**Comment by huycozy** [comment] 2022-08-01 12:32
Hi @AKZHW 
Please provide the crash log in text format instead of a screenshot for better investigation.
As @mraleph mentioned above, this issue may be caused by low memory devices, please also provide affected devices' information.
And as far as I can see, you are using the old Flutter version `2.10.4`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please try upgrading them and retry to see if this issue still reproduces.

**Comment by AKZHW** [comment] 2022-08-01 12:34
> Hi @AKZHW
> Please provide the crash log in text format instead of a screenshot for better investigation.
> As @mraleph mentioned above, this issue may be caused by low memory devices, please also provide affected devices' information.
> And as far as I can see, you are using the old Flutter version `2.10.4`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please try upgrading them and retry to see if this issue still reproduces.



libsystem_kernel.dylib | __pthread_kill | - | -
-- | -- | -- | --
1 | libsystem_pthread.dylib | pthread_kill$VARIANT$mp | - | -
2 | libsystem_c.dylib | abort | - | -
3 | Flutter | dart::SimpleHashMap::Lookup(void*, unsigned int, bool) | hashmap.cc | 22
4 | Flutter | dart::ThreadPool::RunImpl(std::__1::unique_ptr<dart::ThreadPool::Task, std::__1::default_delete<dart::ThreadPool::Task> >) | thread_pool.cc | 92
5 | Flutter | dart::PageSpace::CollectGarbageHelper(bool, bool, long long, long long) | pages.cc | 1194
6 | Flutter | dart::PageSpace::CollectGarbage(bool, bool) | pages.cc | 1140
7 | Flutter | dart::Heap::StartConcurrentMarking(dart::Thread*, dart::GCReason) | heap.cc | 630
8 | Flutter | dart::Heap::NotifyIdle(long long) | heap.cc | 0
9 | Flutter | flutter::RuntimeController::NotifyIdle(long long) | runtime_controller.cc | 217
10 | Flutter | flutter::Shell::OnAnimatorNotifyIdle(long long) | shell.cc | 1100
11 | Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) | message_loop_impl.cc | 132
12 | Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) | message_loop_darwin.mm | 81
13 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ | - | -
14 | CoreFoundation | __CFRunLoopDoTimer | - | -
15 | CoreFoundation | __CFRunLoopDoTimers | - | -
16 | CoreFoundation | __CFRunLoopRun | - | -
17 | CoreFoundation | CFRunLoopRunSpecific | - | -
18 | Flutter | fml::MessageLoopDarwin::Run() | message_loop_darwin.mm | 52
19 | Flutter | void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) | thread | 291
20 | libsystem_pthread.dylib | _pthread_body | - | -
21 | libsystem_pthread.dylib | _pthread_start

**Comment by AKZHW** [comment] 2022-08-01 12:35
> Hi @AKZHW
> Please provide the crash log in text format instead of a screenshot for better investigation.
> As @mraleph mentioned above, this issue may be caused by low memory devices, please also provide affected devices' information.
> And as far as I can see, you are using the old Flutter version `2.10.4`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please try upgrading them and retry to see if this issue still reproduces.



0 | libsystem_kernel.dylib | __pthread_kill | - | -
-- | -- | -- | -- | --
1 | libsystem_pthread.dylib | pthread_kill$VARIANT$mp | - | -
2 | libsystem_c.dylib | abort | - | -
3 | Flutter | dart::SimpleHashMap::Lookup(void*, unsigned int, bool) | hashmap.cc | 22
4 | Flutter | dart::ThreadPool::RunImpl(std::__1::unique_ptr<dart::ThreadPool::Task, std::__1::default_delete<dart::ThreadPool::Task> >) | thread_pool.cc | 92
5 | Flutter | dart::Scavenger::Scavenge(dart::GCReason) | scavenger.cc | 1642
6 | Flutter | dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::GCReason) | heap.cc | 474
7 | Flutter | dart::Heap::NotifyIdle(long long) | heap.cc | 381
8 | Flutter | flutter::RuntimeController::NotifyIdle(long long) | runtime_controller.cc | 217
9 | Flutter | flutter::Shell::OnAnimatorNotifyIdle(long long) | shell.cc | 1100
10 | Flutter | std::__1::__function::__func<flutter::Animator::RequestFrame(bool)::$_2, std::__1::allocator<flutter::Animator::RequestFrame(bool)::$_2>, void ()>::operator()() | animator.cc | 0
11 | Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) | message_loop_impl.cc | 132
12 | Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) | message_loop_darwin.mm | 81
13 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ | - | -
14 | CoreFoundation | __CFRunLoopDoTimer | - | -
15 | CoreFoundation | __CFRunLoopDoTimers | - | -
16 | CoreFoundation | __CFRunLoopRun | - | -
17 | CoreFoundation | CFRunLoopRunSpecific | - | -
18 | Flutter | fml::MessageLoopDarwin::Run() | message_loop_darwin.mm | 52
19 | Flutter | void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) | thread | 291
20 | libsystem_pthread.dylib | _pthread_body | - | -
21 | libsystem_pthread.dylib | _pthread_start

**Comment by AKZHW** [comment] 2022-08-01 12:46
> Hi @AKZHW
> Please provide the crash log in text format instead of a screenshot for better investigation.
> As @mraleph mentioned above, this issue may be caused by low memory devices, please also provide affected devices' information.
> And as far as I can see, you are using the old Flutter version `2.10.4`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please try upgrading them and retry to see if this issue still reproduces.



iPad Mini 2   arm64  12.5.5(16H62)
![image](https://user-images.githubusercontent.com/9245326/182150927-dd7a9991-1924-49c3-89a7-1746bd309215.png)

**Comment by huycozy** [comment] 2022-08-02 04:56
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/108723#issuecomment-1201142936 force flutter#v2.10.4 ios release arm64

**Comment by huycozy** [comment] 2022-08-02 04:58
@AKZHW please provide full of crash log so that we can verify the issue properly. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by impeiwei** [comment] 2022-08-02 05:25
> @AKZHW please provide full of crash log so that we can verify the issue properly. Also, please provide the output of `flutter doctor -v` as well. Thank you!

Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c1df2c24e0 (7 weeks ago) • 2022-06-16 15:48:05 +0800
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2


we also merge [#98013](https://github.com/flutter/flutter/issues/98013)  to our engine artifact

**Comment by mraleph** [comment] 2022-08-02 07:03
@huycozy there is nothing to symbolize here. stacks are already readable and clearly point towards OOM. without reproduction this is unactionable, there might be variety of reasons (leaks in the app, leaks in Flutter engine, etc).

**Comment by huycozy** [comment] 2022-08-02 07:29
Hi @AKZHW 
Without reproduction, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us (reproduction steps and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) then we will reopen it right away!
Thanks for your contribution.

**Closed by huycozy** 2022-08-02 07:29 UTC
Labels: waiting for customer response, in triage

**Comment by AKZHW** [comment] 2022-08-03 02:26
> @huycozy there is nothing to symbolize here. stacks are already readable and clearly point towards OOM. without reproduction this is unactionable, there might be variety of reasons (leaks in the app, leaks in Flutter engine, etc).

OK
