### ISSUE TITLE
After starting debugging, "Path must be a string. Received null" is displayed.

### ISSUE THREAD

**Issue by ganessaa** [flutter/flutter#24961] opened 2018-12-05 01:36 UTC
We used the flutter for the first time in a few months.

However, when we press F5, the following error is displayed in the lower right corner of the Visual Code and it cannot be debugged.

```
Path must be a string. Received null
```

Are we mistaken for something?

We have upgraded with the following command.

```
flutter channel dev
flutter upgrade
flutter clean
```

We switched to master and tried it again.

```
flutter channel master
flutter upgrade
flutter clean
```

But the problem was not improved.

We tried it on Mac and Windows, but both were the same.

Mac
```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.0.0, on Mac OS X 10.13.6 17G3025, locale ja)
    • Flutter version 1.0.0 at /Applications/flutter
    • Framework revision 5391447fae (5 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/xxxxxxxx/src/android-sdks
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/xxxxxxxx/src/android-sdks
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • ASUS Z017DA • XXXXXXXXXXXXXXX • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

Windows
```
>flutter doctor -v
[√] Flutter (Channel dev, v1.0.0, on Microsoft Windows [Version 10.0.17763.134], locale ja-JP)
    • Flutter version 1.0.0 at C:\Users\xxxxxxxx\Documents\flutter
    • Framework revision 5391447fae (5 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\xxxxxxxx\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.29.1)
    • VS Code at C:\Users\xxxxxxxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.0

[√] Connected device (1 available)
    • ASUS Z017DA • XXXXXXXXXXXXXXX • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by miguelpruivo** [comment] 2018-12-05 02:31
Do you have the issue when you run without extensions `--disable-extensions`? Also check the logs in the developer tools console Help>Toggle Developer Tools.

**Comment by ganessaa** [comment] 2018-12-05 02:58
@miguelpruivo
Thank you for your reply.

What do we add it to?
We tried it but it did not work properly.
```
$ flutter run --disable-extensions
Could not find an option named "disable-extensions".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

We usually only press F5, but if we tried the following command, it worked normally.
```
$ flutter run
```

This problem seems to occur when we select `Debug> Start Debugging` or `Debug> Start Without Debugging` or use shortcut keys.

We checked the log of Toggle Developer Tools.
```
notificationsAlerts.ts:38 Error: Path must be a string. Received null
	at assertPath (path.js:28:11)
	at Object.relative (path.js:1267:5)
	at Object.isWithinPath (/Users/xxxxxxxx/.vscode/extensions/dart-code.dart-code-2.21.0/out/src/debug/utils.js:112:27)
	at DebugConfigProvider.<anonymous> (/Users/xxxxxxxx/.vscode/extensions/dart-code.dart-code-2.21.0/out/src/providers/debug_config_provider.js:124:74)
	at Generator.next (<anonymous>)
	at /Users/xxxxxxxx/.vscode/extensions/dart-code.dart-code-2.21.0/out/src/providers/debug_config_provider.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/xxxxxxxx/.vscode/extensions/dart-code.dart-code-2.21.0/out/src/providers/debug_config_provider.js:3:12)
	at DebugConfigProvider.resolveDebugConfiguration (/Users/xxxxxxxx/.vscode/extensions/dart-code.dart-code-2.21.0/out/src/providers/debug_config_provider.js:53:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:476:297
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:114:65
	at new Promise (<anonymous>)
	at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:114:33)
	at e.$resolveDebugConfiguration (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:476:266)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:609:757)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:609:423)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:608:15)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:606:957)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:604:773
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:103:886
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:105:344)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:156:881)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:157:95)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by zoechi** [comment] 2018-12-05 07:34
Might be https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated
Can you please try recreating `ios/` and `android/` as explained?

**Comment by zoechi** [comment] 2018-12-05 09:11
I didn't recognize at first that this is a VSCode issue, not a Flutter issue.
/cc @DanTup

**Comment by ganessaa** [comment] 2018-12-05 09:39
We mentioned VSCode, but we deleted it.
We apologized for confusing you.

Did we make a mistake in the place to ask questions?
Where should we ask this question?

**Comment by DanTup** [comment] 2018-12-05 14:37
@ganessaa Could you please open an issue at https://github.com/Dart-Code/Dart-Code/issues/new

Please run the `Dart: Capture Log` command and select the `Flutter Run` and then reproduce the issue and supply the log file, and also include a copy of your `.vscode/launch.json` file if you have one.

Thanks!

**Comment by DanTup** [comment] 2018-12-05 14:40
Actually, I can already repro this - working on a fix...

I've opened https://github.com/Dart-Code/Dart-Code/issues/1327 about it, so I'll close this one.

**Closed by DanTup** 2018-12-05 14:40 UTC

**Comment by DanTup** [comment] 2018-12-05 14:42
(I think it only occurs when there's no open file, so having a `.dart` file open may prevent the issue until a fix is released)

**Comment by DanTup** [comment] 2018-12-05 15:53
@ganessaa Please updated the Dart extension in VS Code to v2.21.1 (just published) and let me know here or on https://github.com/Dart-Code/Dart-Code/issues/1327 whether the issue is resolved for you. Thanks!

**Comment by ganessaa** [comment] 2018-12-06 00:11
@DanTup We sincerely thank you for your prompt response. :)

We updated the Dart extension.
The following message is no longer displayed.
```
Path must be a string. Received null
```
The issue is resolved.

**Comment by DanTup** [comment] 2018-12-06 07:40
@ganessaa Great! Thanks for the report and the confirmation!
