### ISSUE TITLE
Android 12 Overscroll effect

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#83355] opened 2021-05-25 16:23 UTC
## Native Android

With Android 12, this is how the **[overscroll effect](https://developer.android.com/about/versions/12/overscroll)** looks like **in native Android 12**:

| Pull stretch | Fling stretch |
| :-: | :-: |
| ![pull-stretch-overscroll](https://user-images.githubusercontent.com/19204050/119530567-a65d8400-bd72-11eb-9785-7d8f840b7b8f.gif) | ![fling-stretch-overscroll](https://user-images.githubusercontent.com/19204050/119530578-abbace80-bd72-11eb-9ce1-c4caf191e54f.gif) |

## Flutter

This is what the overscroll effects looks like in Flutter running on Android 12:

https://user-images.githubusercontent.com/19204050/119533495-6b108480-bd75-11eb-9218-c298001134f7.mp4

### Resource

You can find the **overscroll effect** article on Android Developers: https://developer.android.com/about/versions/12/overscroll

**Comment by TahaTesser** [comment] 2021-05-26 07:49
Hi @creativecreatorormaybenot 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/82906
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-26 07:49 UTC
Labels: in triage

**Comment by creativecreatorormaybenot** [comment] 2021-05-26 08:23
@TahaTesser I agree, thanks. I really tried to find an existing issue, but I did not find anything :/
