### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by rechy** [flutter/flutter#128369] opened 2023-06-07 00:22 UTC
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#5      AndroidProject._computeSupportedVersion (package:flutter_tools/src/project.dart:497:41)
#6      AndroidProject.isSupportedVersion (package:flutter_tools/src/project.dart:476:40)
#7      AndroidProject.isSupportedVersion (package:flutter_tools/src/project.dart)
#8      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:260:26)
#9      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:11)
#10     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:27)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.3, on Microsoft Windows [版本 10.0.19045.2006], locale zh-CN)
    [32m•[39m Flutter version 3.10.3 on channel stable at D:\flutter\flutter_windows_3.3.3-stable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f92f44110e (5 days ago), 2023-06-01 18:17:33 -0500
    [32m•[39m Engine revision 2a3401c9bb
    [32m•[39m Dart version 3.0.3
    [32m•[39m DevTools version 2.23.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\rechy\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.5.33627.172
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at N:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at C:\Users\rechy\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.66.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.2006]
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.37

[33m[!][39m Network resources
    [31m✗[39m An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.6+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 52b3dc25f6471c27b2144594abb11c741cb88f57
### Plugins
flutter_libwcgo
install_apk
package_info_plus-4.0.2
path_provider-2.0.15
path_provider_android-2.0.24
path_provider_foundation-2.2.1
path_provider_linux-2.1.10
path_provider_windows-2.1.6
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.8
permission_handler_windows-0.1.2
screen_retriever-0.1.6
shared_preferences-2.1.1
shared_preferences_android-2.1.0
shared_preferences_foundation-2.2.0
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
0.5.15
tobias-2.4.1+1
window_manager-0.3.4

**Comment by darshankawar** [comment] 2023-06-07 07:27
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021.

**Closed by darshankawar** 2023-06-07 07:27 UTC
Labels: in triage
