### ISSUE TITLE
Linux Desktop App Build Failure Generating libflutter_linux_gtk.so

### ISSUE THREAD

**Issue by cedarbob** [flutter/flutter#77382] opened 2021-03-05 16:41 UTC
After moving to the latest stable channel on my development machine, I can no longer build a simple test desktop app in my project.  I'm running Ubuntu 18.03.  Below is my build output:
```
Building Linux application...
[  +37 ms] <- compile file:///home/rhr/IdeaProjects/basic_behavior_trees/bin/graphview_example.dart
[   +1 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/rhr/IdeaProjects/basic_behavior_trees/linux
[   +7 ms] List of devices attached
[   +2 ms] List of devices attached
[ +101 ms] -- Configuring done
[   +7 ms] -- Generating done
[        ] -- Build files have been written to: /home/rhr/IdeaProjects/basic_behavior_trees/build/linux/debug
[   +4 ms] executing: ninja -C build/linux/debug install
[   +6 ms] ninja: Entering directory `build/linux/debug'
[ +250 ms] [1/5] Generating /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +12 ms] FAILED: /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/libflutter_linux_gtk.so /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_engine.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_method_call.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_method_response.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_value.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/fl_view.h /home/rhr/IdeaProjects/basic_behavior_trees/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_ 
[   +1 ms] cd /home/rhr/IdeaProjects/basic_behavior_trees/build/linux/debug/flutter && /usr/bin/cmake -E env FLUTTER_ROOT=/home/rhr/Tools/flutter PROJECT_DIR=/home/rhr/IdeaProjects/basic_behavior_trees DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue DART_OBFUSCATION=false EXTRA_FRONT_END_OPTIONS=--no-sound-null-safety TRACK_WIDGET_CREATION=true TREE_SHAKE_ICONS=false PACKAGE_CONFIG=/home/rhr/IdeaProjects/basic_behavior_trees/.dart_tool/package_config.json FLUTTER_TARGET=/home/rhr/IdeaProjects/basic_behavior_trees/bin/graphview_example.dart /home/rhr/Tools/flutter/packages/flutter_tools/bin/tool_backend.sh Debug
[        ] Unhandled exception:
[        ] RangeError (index): Invalid value: Only valid value is 0: 1
[        ] #0      List.[] (dart:core-patch/array.dart:110:52)
[        ] #1      main (file:///home/rhr/Tools/flutter/packages/flutter_tools/bin/tool_backend.dart:14:37)
[        ] #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
[        ] #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[        ] ninja: build stopped: subcommand failed.
[+5386 ms] Exception: Build process failed
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:550:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +10 ms] "flutter run" took 6,262ms.
[  +88 ms] ensureAnalyticsSent: 87ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +10 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
My flutter doctor output follows:
```
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.1 at /home/rhr/Tools/flutter
    • Framework revision c5a4b4029c (23 hours ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/rhr/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/rhr/Tools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/rhr/Tools/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/rhr/Tools/idea-IC-193.6494.35
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.72

```

**Comment by stuartmorgan** [comment] 2021-03-05 17:42
Duplicate of https://github.com/flutter/flutter/issues/77241

**Closed by stuartmorgan** 2021-03-05 17:42 UTC
