### ISSUE TITLE
OnTap of GestureDetector is not working for containers in stack.

### ISSUE THREAD

**Issue by himanshu096** [flutter/flutter#23454] opened 2018-10-24 07:21 UTC
I have two containers in a stack and both containers have GestureDetector.The OnTap for the first container is working fine but it's not working with another container.
The first container is the image and the second one is the green background aligned partially over the first container.

```dart
  new Stack(
                alignment: Alignment(0.0, 1.44),
                children: <Widget>[
                  GestureDetector(
                    onTap: () => _openImage(context),
                    child: Container(
                      width: 340.0,
                      foregroundDecoration: new BoxDecoration(
                          color: Color.fromRGBO(155, 85, 250, 0.55)),
                      height: 240.0,
                      child: FadeInImage.assetNetwork(
                        placeholder: 'assets/dimlight.png',
                        image: post.imageUrl,
                        fit: BoxFit.cover,
                      ),
                    ),
                  ),
                  new GestureDetector(
                    child: new Container(
                      color: Colors.green,
                      child: Row(
                        mainAxisSize: MainAxisSize.max,
                        children: <Widget>[
                          SizedBox(width: 7.0),
                          CircleAvatar(
                            backgroundImage: 
                               new AssetImage("assets/boy.png")
                            radius: 30.0,
                          ),
                          SizedBox(
                            width: 7.0,
                          ),
                          Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: <Widget>[
                              new SizedBox(
                                height: 20.0,
                              ),
                              Text(
                                post.user.name,
                                style: TextStyle(fontWeight: FontWeight.bold),
                              ),
                              Text(
                                getTimeString(post.timestamp.toString()),
                                style: TextStyle(
                                    color: Colors.grey, fontSize: 10.0),
                              ),
                            ],
                          ),
                          SizedBox(
                            width: 20.0,
                          ),
                        ],
                      ),
                    ),
                    onTap: () => _navigateToDetails(context),
                  )
                ],
              )
```

**Comment by himanshu096** [comment] 2018-10-26 06:07
@zoechi I asked this question on StackOverflow and here's the link https://stackoverflow.com/questions/52965799/flutter-gesturedetector-not-working-with-containers-in-stack

and here's the code to reproduce the issue https://gist.github.com/himanshu096/b9f8d4506a024c3322c9291027491815

**Comment by goderbauer** [comment] 2019-01-04 01:06
@himanshu096 Can you post a complete code sample that I can copy & paste and run to investigate the issue? The code you posted doesn't run on its own as is.

**Comment by himanshu096** [comment] 2019-01-04 06:31
@goderbauer here is the complete code thttps://gist.github.com/himanshu096/b9f8d4506a024c3322c9291027491815

**Comment by baoolong** [comment] 2019-04-02 03:35
@himanshu096 Have you solved this problem?

**Comment by AkramChauhan** [comment] 2019-05-02 04:59
Facing same issue.
Anyone get any luck on this issue?

**Comment by biocarl** [comment] 2019-05-03 15:24
Setting the `behavior` property of the `GestureDetector` to `HitTestBehavior.translucent` resolved it for me. Just wanted add that this issue occurred after updating the stable channel. Last time it worked without that flag and I checked was 3 months ago also on the stable channel

**Comment by patelkrunal78** [comment] 2019-10-05 17:13
wrapping the container inside an Inkwell() Widget could solve the problem or even GestureDetector() as

  InkWell(                        
        child: Container(...),                        
        onTap: () {                          
        print("tapped on container");
        },                      
     );
Using the Gesture Detector

GestureDetector(
  onTap: () { print("Container was tapped"); },
  child: Container(...),
)

Find Your Solution At [Here](https://stackoverflow.com/questions/44317188/flutter-ontap-method-for-containers)

**Comment by SahajRana** [comment] 2019-11-02 13:02
facing the same problem, not solved by `GestureDetector` to `HitTestBehavior.translucent`

**Comment by mehmetyilmaz001** [comment] 2019-11-13 19:37
Facing the same problem, too.

**Comment by SahajRana** [comment] 2019-11-14 05:49
@mehmetyilmaz001, I have solved this problem for Containers with GestureDetector in Stack that I was facing. In my case, I had a Container inside Container containing GestureDectector, like
```
Stack
    Container (1)
         Align
             Gesture
                 Container (2)
    Container (3)
         Align
             Gesture
                 Container (4)
```
So in short, making the `color of Container(1&3) null` solved the problem for me (Problem: Gesture only detected by Container(4)).

**Comment by mehmetyilmaz001** [comment] 2019-11-14 09:56
@SahajRana  Thanks for sharing your case.

In my case there is a flat button at the end of widget tree. So It had prevented Gesture onTap event.

**Comment by 229106948** [comment] 2020-01-03 01:49
Facing the same problem, too.I need cover completely a transparent widget.but the listview can't get the onTap event

MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Stack(
          children: <Widget>[
            ListView.builder(itemBuilder: (context, index) {
              return GestureDetector(
                onTap: (){
                  print("item点击");
                },
                child: Padding(
                  padding: EdgeInsets.only(left: 10,right: 10,bottom: 10),
                  child: Container(
                    height: 50,
                    color: Colors.red,
                    child: Center(
                      child: Text("测试item"),
                    ),
                  ),
                ),
              );
            }),
            Container(
              width: MediaQueryData.fromWindow(window).size.width,
              height:  MediaQueryData.fromWindow(window).size.height,
              child: Text("测试",style: TextStyle(backgroundColor: Color(0xff00ff00)),),
            )
          ],
        ),
      ),
    );

**Comment by superdiazzz** [comment] 2020-03-05 10:17
I have this problem and already posted in SO. Still failed https://stackoverflow.com/questions/60538165/gesture-detector-cant-trigger-inside-stackview/60539620?noredirect=1#comment107102954_60539620

**Comment by cah4a** [comment] 2020-03-22 14:44
I've got the same issue without any Stack.

Here is a minimal example:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      home: Scaffold(
        body: Center(
          child: Container(
            width: 200,
            height: 200,
            color: Colors.black,
            child: OverflowBox(
              maxWidth: 400,
              child: GestureDetector(
                onTap: () => print(1),
                child: Container(
                  color: Colors.blue.withOpacity(.3),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

I guess that's something with OverflowBox by itself.

**Comment by PhyoeKo** [comment] 2020-04-10 12:02
I also getting like that.

**Comment by ameeee** [comment] 2020-04-11 18:45
Same problem ! nothing is working, im having a Swiper inside the container

**Comment by iapicca** [comment] 2020-04-22 12:25
Hi all 
you may want to consider this [approach](https://dartpad.dev/e4ddf85b03943733454c1e62d89c3c50)

I'm closing the issue  as duplicate of 
https://github.com/flutter/flutter/issues/19974
https://github.com/flutter/flutter/issues/20798

If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-04-22 12:25 UTC
Labels: f: gestures, framework

**Comment by gdrtrts** [comment] 2020-05-02 12:42
For me the following approach worked.
```
SizedBox.expand(
child: <your child> 
);
```

**Comment by tgbaozkn** [comment] 2020-06-17 17:31
Hello i have same issue. I want to shadow widget with animated container to whole screen. I did this stack but i have two buttons on the page and they don't work  i tried GestureDetector and  behavior: HitTestBehavior.translucent, but it doesn't work ,buttons can't see my click, how can i fix?

**Comment by glennmichaelmejias** [comment] 2020-06-18 10:16
Just make sure that your gesturedetector is not overlapped with other widgets that is not transparent. 
sample stack widget here
`
stack[
       gesturedetector,
       container,
       widgets...
]
`

make sure that the container has no color because even transparent color can overlap the inputs.

**Comment by erayhamurlu** [comment] 2020-11-07 18:00
**GestureDetector is not working when write code inside its block
**It will be doesn't work****

    GestureDetector(
                      onTap: () {
                        setState(() {
                          _color = Colors.red;
                        });
                      },),

**You will write like that it will work**

    GestureDetector(
                      onTap: () {
                        changed();
                      },),

**method**

    void changed() {
    setState(() {
      _color = Colors.red;
    });}

**Comment by iapicca** [comment] 2020-11-07 18:25
@erayhamurlu 
your snippets are not representative since often, if not always
the issue is with size of the parent or the child of the gesture detector,
I recommend you to look at this [comment](https://github.com/flutter/flutter/issues/23454#issuecomment-617747489) 
and if doesn't solve the issue, please provide a minimal reproducible code sample

**Comment by zzterrozz** [comment] 2020-11-17 22:19
After hours of search, it was in my case a `Positioned.fill` in the `Stack` that was creating the issue (GestureDetector not recognized).
Deleting this `Positioned.fill` solved the problem.
Hope it can help some people.

**Comment by arexhuang** [comment] 2021-01-04 07:03
I ever try with Xiaomi Mix2S with Android 10 and Xiaomi 4 android8 , the same code,mix2s is fine. another is NG.
and I also find some android box(android 4.x) , it can't work too.

So it seems that this is platform issue??

**Comment by iapicca** [comment] 2021-01-04 09:08
@arexhuang 
this issue is closed from more than 8 months and is currently not worked on,
I posted above a [working code sample](https://github.com/flutter/flutter/issues/23454#issuecomment-617747489)
if this code sample is not representative of the behavior you are experiencing 
please provide a complete minimal reproducible code sample

tagging @TahaTesser for visibility

**Comment by dsaket** [comment] 2021-05-04 09:08
Turns out, only this workaround worked. We need to wrap the widget inside Padding so that it won't cause overflow.

```
Stack(
        clipBehavior: Clip.none, children: [
        Padding(
            padding: EdgeInsets.only(right: 12, top: 12), // padding amount exactly equal to the overflow amount
            child: ClipRRect(
              borderRadius: BorderRadius.circular(10),
              child: Container(width: 100, height: 50),
            )),
        Positioned(
            top: 0, // should be >=0 to work
            right: 0, // should be >=0 to work
            child: GestureDetector(
                behavior: HitTestBehavior.translucent,
                onTap: () {
                  print("tapped");
                },
                child: Container(
                  color: Colors.black,
                  width: 24,
                  height: 24,
                )
                ))
      ])
```

**Comment by AliYar-Khan** [comment] 2021-06-07 16:01
Same is the case with me . I have a positioned widge inside stack and it detects gesture on corner of the container border only:
```

Positioned(
                            bottom: -67,
                            child: GestureDetector(
                              onTap: () {
                                print('Tap');
                              },
                              child: Container(
                                width: 70,
                                height: 70,
                                padding: EdgeInsets.all(4),
                                decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.white,
                                    width: 5,
                                  ),
                                  boxShadow: [
                                    BoxShadow(
                                      color:
                                          Color(0xFF000000).withAlpha(11),
                                      blurRadius: 16,
                                      offset: Offset(0, 3),
                                    ),
                                  ],
                                  shape: BoxShape.circle,
                                  color: Colors.white,
                                ),
                                child: CircleAvatar(
                                  radius: 24,
                                  backgroundColor: Colors.green,
                                  child: Icon(
                                    Icons.arrow_forward,
                                    color: Colors.white,
                                  ),
                                ),
                              ),
                            ),
                          ),
```
                          
It is detecting the tap but outside the white border of circle avatar. I want the whole White border and circle avatar to be clickable. Removing the positioned makes the whole container clickable but now how i want to position that element in the stack !!!
