### ISSUE TITLE
complex_layout_scroll_perf__memory end_total_kb regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13626] opened 2017-12-16 02:31 UTC
The amount of memory that complex_layout uses after scrolling has increased dramatically:
![memory_regression](https://user-images.githubusercontent.com/551196/34066614-1b3ed940-e1c6-11e7-999d-ef9870ed5594.png)

It hasn't affected other memory benchmarks, as visible above.

**Comment by mraleph** [comment] 2017-12-18 11:36
Bisected to 5a44162c97. Looking into this.

**Comment by mraleph** [comment] 2017-12-18 15:35
The memory increase is due to `vmservice` itself taking more space, not because of the application memory increase. 

The fix is here https://dart-review.googlesource.com/c/sdk/+/30280, waiting review by @rmacnak-google

**Comment by mraleph** [comment] 2017-12-18 19:07
Fixed by dart-lang/sdk@b2eab8b96eba28eca711810bb9b008ec6fc8909b

**Closed by mraleph** 2017-12-18 19:07 UTC
Labels: performance, regression, ⚠ TODAY

**Comment by Hixie** [comment] 2017-12-18 20:01
Thanks!!

**Comment by Hixie** [comment] 2017-12-22 01:06
Looks like the fix didn't actually bring us all the way back, FWIW.

**Comment by mraleph** [comment] 2017-12-22 08:37
Looked like complete fix locally. I will check it out when I am back from vacation (after new Year)

**Comment by mraleph** [comment] 2018-01-02 13:35
I tried running the test against local engine build against TOT Dart, here is what I get (on my Nexus 5X):

```console
$ FLUTTER_ENGINE=$HOME/src/flutter-clean/engine/src dart bin/run.dart -t complex_layout_scroll_perf__memory
...
{
  "success": true,
  "data": {
    "start_total_kb": 115614,
    "end_total_kb": 139976,
    "diff_total_kb": 24362
  },
  "benchmarkScoreKeys": [
    "start_total_kb",
    "end_total_kb",
    "diff_total_kb"
  ]
}
```

This matches what I saw locally when I tested against old version of Dart (that was updated by the roll):

```console
{
  "success": true,
  "data": {
    "start_total_kb": 118177,
    "end_total_kb": 142417,
    "diff_total_kb": 24240
  },
  "benchmarkScoreKeys": [
    "start_total_kb",
    "end_total_kb",
    "diff_total_kb"
  ]
}
```

prior to fixing it I saw numbers like this:

```
{                                                                   
  "success": true,                                                  
  "data": {                                                         
    "start_total_kb": 118692,                                       
    "end_total_kb": 165580,                                         
    "diff_total_kb": 46888                                          
  },                                                                
  "benchmarkScoreKeys": [                                           
    "start_total_kb",                                               
    "end_total_kb",                                                 
    "diff_total_kb"                                                 
  ]                                                                 
}
```

So regression is most certainly fixed. 

What I don't understand is why my local numbers don't match don't exactly match what dashboard shows.

/cc @yjbanov any ideas? What kind of hardware dashboard uses to run `complex_layout_scroll_perf__memory`?

**Comment by yjbanov** [comment] 2018-01-02 18:26
We run tests on Moto G4.
