### ISSUE TITLE
multiline TextField's blinking cursor always on start (just on ios)

### ISSUE THREAD

**Issue by YaoShuwei** [flutter/flutter#25530] opened 2018-12-19 01:39 UTC
```
[✓] Flutter (Channel master, v1.1.3-pre.39, on Mac OS X 10.13.6 17G3025, locale
    zh-Hans-CN)
    • Flutter version 1.1.3-pre.39 at /Users/yaoshuwei/flutter
    • Framework revision 8b34a12d45 (3 hours ago), 2018-12-18 14:46:45 -0800
    • Engine revision 08465e8000
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/yaoshuwei/Library/Android/sdk
    • Android NDK at /Users/yaoshuwei/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • MI 8       • 96c89e18                                 • android-arm64 •
      Android 9 (API 28)
    • iPhone (2) • 9170a974b32c4b641a950c2eb12d721497444ca0 • ios           •
      iOS 12.1
```

**Comment by zoechi** [comment] 2018-12-19 07:04
Is this the same on all devices and emulators? Did this start after a Flutter update?

This seems to work for others. Except #21745.

Is this also with a simple app that consists only of a TextField with no additional behavior?

**Comment by YaoShuwei** [comment] 2018-12-19 07:21
Both ios devices and simulator. Android is normal.
`Is this also with a simple app that consists only of a TextField with no additional behavior?`
Yes, it is.

**Comment by zoechi** [comment] 2018-12-19 07:35
Sorry, I missed the `multiline`.

**Comment by goderbauer** [comment] 2019-01-04 22:36
I cannot reproduce this. If you still see this, can you provide a runnable code sample that shows the issue?

**Comment by zoechi** [comment] 2019-02-07 18:38
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-07 18:38 UTC
Labels: a: text input, framework, waiting for customer response, ⌺‬ platform-ios
