### ISSUE TITLE
Waiting for obsevatory port to be available... on Vivo S1 only

### ISSUE THREAD

**Issue by aneebhiba614** [flutter/flutter#88302] opened 2021-08-16 18:25 UTC
## Steps to Reproduce

1. Run `flutter run -v` on Vivo S1.

**Expected results:**  Able to run and debug my app on my mobile

**Actual results:** Waiting for observatory port to be available...

<details>
##Result of `flutter run --verbose`:

```
[ +402 ms] executing: [C:\Users\Aneeb\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +413 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +4 ms] executing: [C:\Users\Aneeb\flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[ +217 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +2 ms] 2.2.3
[  +43 ms] executing: [C:\Users\Aneeb\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +182 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[   +2 ms] executing: [C:\Users\Aneeb\flutter/] git ls-remote --get-url origin
[ +157 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +632 ms] executing: [C:\Users\Aneeb\flutter/] git rev-parse --abbrev-ref HEAD
[ +201 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[ +628 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +23 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +415 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +310 ms] List of devices attached
                    AEDI7DEQXCGUJJAQ       device product:1907 model:vivo_1907_19 device:1907 transport_id:1
[  +77 ms] C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe -s AEDI7DEQXCGUJJAQ shell getprop
[ +205 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +409 ms] Skipping pub get: version match.
[ +516 ms] Generating C:\Flutter\MyApps\shop_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +347 ms] ro.hardware = mt6768
[   +4 ms] ro.build.characteristics = default
[ +216 ms] Initializing file store
[  +40 ms] Skipping target: gen_localizations
[  +41 ms] complete
[  +29 ms] Launching lib\main.dart on vivo 1907 19 in debug mode...
[  +33 ms] C:\Users\Aneeb\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\Aneeb\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\Aneeb\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\Aneeb\AppData\Local\Temp\flutter_tools.b6fbe319\flutter_tool.1e3c130a\app.dill --packages
C:\Flutter\MyApps\shop_app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root       
--initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +60 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree C:\Flutter\MyApps\shop_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +42 ms] Exit code 0 from: C:\Users\Aneeb\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree C:\Flutter\MyApps\shop_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.shop_app" (Raw: "com.example.shop_app")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="shop_app" (Raw: "shop_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.shop_app.MainActivity" (Raw: "com.example.shop_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +35 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe -s AEDI7DEQXCGUJJAQ shell -x logcat -v time -t 1
[  +35 ms] <- compile package:shop_app_course/main.dart
[ +174 ms] --------- beginning of main
[  +35 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +269 ms] Android Debug Bridge version 1.0.41
                    Version 31.0.3-7562133
                    Installed as C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +6 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +65 ms] Building APK
[  +88 ms] Running Gradle task 'assembleDebug'...
[  +37 ms] Using gradle from C:\Flutter\MyApps\shop_app\android\gradlew.bat.
[  +29 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +506 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +4 ms] executing: [C:\Flutter\MyApps\shop_app\android/] C:\Flutter\MyApps\shop_app\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Flutter\MyApps\shop_app\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false       
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+6194 ms] Starting a Gradle Daemon, 34 busy and 2 incompatible and 1 stopped Daemons could not be reused, use --status for details
[+24025 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[ +379 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[  +19 ms] > Task :app:preBuild UP-TO-DATE
[   +6 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +3 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[ +484 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +17 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[   +9 ms] > Task :app:cleanMergeDebugAssets
[  +39 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[  +12 ms] > Task :app:compileDebugShaders NO-SOURCE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +8 ms] > Task :app:mergeDebugAssets
[ +792 ms] > Task :app:copyFlutterAssetsDebug
[ +161 ms] > Task :app:generateDebugResValues UP-TO-DATE
[ +102 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +522 ms] > Task :app:mergeDebugResources UP-TO-DATE
[ +371 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[ +327 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[ +105 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[ +139 ms] > Task :app:processDebugManifest UP-TO-DATE
[ +289 ms] > Task :app:processDebugManifestForPackage UP-TO-DATE
[   +3 ms] > Task :app:processDebugResources UP-TO-DATE
[+1749 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +7 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +103 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +6 ms] > Task :app:compileDebugSources UP-TO-DATE
[  +11 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[ +214 ms] > Task :app:compressDebugAssets UP-TO-DATE
[ +149 ms] > Task :app:processDebugJavaRes NO-SOURCE
[  +28 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[ +155 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[ +240 ms] > Task :app:dexBuilderDebug UP-TO-DATE
[  +74 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +48 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +2 ms] > Task :app:mergeDexDebug UP-TO-DATE
[ +101 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[ +109 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +3 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +2 ms] > Task :app:validateSigningDebug UP-TO-DATE
[  +46 ms] > Task :app:packageDebug UP-TO-DATE
[ +593 ms] > Task :app:assembleDebug
[  +75 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[  +24 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[  +14 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] BUILD SUCCESSFUL in 37s
[   +1 ms] 32 actionable tasks: 4 executed, 28 up-to-date
[ +715 ms] Running Gradle task 'assembleDebug'... (completed in 39.0s)
[ +235 ms] calculateSha: LocalDirectory: 'C:\Flutter\MyApps\shop_app\build\app\outputs\flutter-apk'/app.apk
[+3519 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[  +21 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree C:\Flutter\MyApps\shop_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +46 ms] Exit code 0 from: C:\Users\Aneeb\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree C:\Flutter\MyApps\shop_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.shop_app" (Raw: "com.example.shop_app")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="shop_app" (Raw: "shop_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.shop_app.MainActivity" (Raw: "com.example.shop_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +38 ms] Stopping app 'app.apk' on vivo 1907 19.
[   +4 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe -s AEDI7DEQXCGUJJAQ shell am force-stop com.example.shop_app
[ +275 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe -s AEDI7DEQXCGUJJAQ shell pm list packages com.example.shop_app
[ +236 ms] package:com.example.shop_app
[  +14 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe -s AEDI7DEQXCGUJJAQ shell cat /data/local/tmp/sky.com.example.shop_app.sha1
[ +154 ms] 35dcbebaa22cf5be877104618bbe827d0203d646
[   +6 ms] Latest build already installed.
[   +3 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe -s AEDI7DEQXCGUJJAQ shell -x logcat -v time -t 1
[ +185 ms] --------- beginning of main
                    08-16 21:48:23.270 I/cmd     (27493): oneway function results will be dropped but finished with status OK and parcel size 4
[  +34 ms] executing: C:\Users\Aneeb\AppData\Local\Android\sdk\platform-tools\adb.exe -s AEDI7DEQXCGUJJAQ shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.shop_app/com.example.shop_app.MainActivity
[ +209 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.shop_app/.MainActivity (has extras) }
[  +12 ms] Waiting for observatory port to be available...
```

**Flutter Analyze result:** 

```
Analyzing shop_app...                                                   
No issues found! (ran in 6.8s)
```

##Result of `flutter doctor -v`: 

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.928], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Aneeb\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Aneeb\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\Aneeb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • vivo 1907 19 (mobile) • AEDI7DEQXCGUJJAQ • android-arm64  • Android 11 (API 30)
    • Edge (web)            • edge             • web-javascript • Microsoft Edge 92.0.902.73
```

</details>

**Comment by TahaTesser** [comment] 2021-08-17 07:41
closing as a duplicate of https://github.com/flutter/flutter/issues/82520

**Closed by TahaTesser** 2021-08-17 07:41 UTC
Labels: in triage
