### ISSUE TITLE
Not clear which is selected in large dropdown

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8266] opened 2017-02-18 05:14 UTC
See gif, this is in the Buttons > Dropdown demo.
![dropdowns mov](https://cloud.githubusercontent.com/assets/11857803/23090584/0ab24844-f556-11e6-958c-bf53ef4e9c48.gif)

**Comment by eseidelGoogle** [comment] 2017-02-18 05:14
The selected one doesn't even show up on screen. :)

**Comment by abarth** [comment] 2017-02-18 05:16
The physics aren't correct in the dropdown.  It needs the special behavior where it will stay overscrolled until you start scrolling it back in range.  Once you overscroll it less, it shouldn't let you overscroll more.

**Comment by abarth** [comment] 2017-02-21 22:21
The old code has a one-frame delay hack to make this work.  The new scrolling system is more resistant to hacking, so we might need to fix this for real without the one frame delay.

**Comment by abarth** [comment] 2017-03-03 04:21
The fix for this needs a change in https://github.com/flutter/flutter/pull/8547

**Comment by eseidelGoogle** [comment] 2017-04-11 22:34
Speculatively punting to M3.

**Comment by eseidelGoogle** [comment] 2017-04-26 03:23
A flavor of this was seen in Material Design review:

"Dropdown spinner animate-scrolls when it opens. Shrine > Tap the first item > Tap Quantity dropdown > Choose 5 > Tap the dropdown again : observe dropdown popup content animates/scrolls"

Which I believe is the same underlying bug.  If not, I'm happy to split out a new one @abarth

**Comment by Hixie** [comment] 2017-12-12 23:47
We should fix this as part of our Material work in the coming months.

**Comment by allanwolski** [comment] 2018-07-20 19:33
Any updates on this problem?

**Comment by markusaksli-nc** [comment] 2020-07-16 09:57
Reproducible on the latest master `1.20.0-8.0.pre.125`.
<details>
 <summary>Minimal reproducible sample</summary>

 ```
// Flutter code sample for DropdownButton

// This sample shows a `DropdownButton` with a large arrow icon,
// purple text style, and bold purple underline, whose value is one of "One",
// "Two", "Free", or "Four".
//
// ![](https://flutter.github.io/assets-for-api-docs/assets/material/dropdown_button.png)

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

/// This Widget is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  String dropdownValue = '30';

  @override
  Widget build(BuildContext context) {
    return DropdownButton<String>(
      value: dropdownValue,
      icon: Icon(Icons.arrow_downward),
      iconSize: 24,
      elevation: 16,
      style: TextStyle(color: Colors.deepPurple),
      underline: Container(
        height: 2,
        color: Colors.deepPurpleAccent,
      ),
      onChanged: (String newValue) {
        setState(() {
          dropdownValue = newValue;
        });
      },
      items: <String>['1' ,'2' ,'3' ,'4' ,'5' ,'6' ,'7' ,'8' ,'9' ,'10' ,'11' ,'12' ,'13' ,'14' ,'15' ,'16' ,'17' ,'18' ,'19' ,'20' ,'21' ,'22' ,'23' ,'24' ,'25' ,'26' ,'27' ,'28' ,'29' ,'30']
          .map<DropdownMenuItem<String>>((String value) {
        return DropdownMenuItem<String>(
          value: value,
          child: Text(value),
        );
      }).toList(),
    );
  }
}

```
</details>

<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.20.0-8.0.pre.125, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.20.0-8.0.pre.125 at C:\Development\flutter_master
    • Framework revision 9c4a5ef1ed (13 hours ago), 2020-07-15 21:41:27 +0100
    • Engine revision 774ae0313d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 89fe12b12a)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```
</details>

**Comment by YeungKC** [comment] 2020-11-21 23:08
https://github.com/flutter/flutter/issues/8266#issuecomment-280822889

At last master it is possible to show selected one correctly.

**Comment by YeungKC** [comment] 2020-11-21 23:09
> The selected one doesn't even show up on screen. :)

At last master it is possible to show selected one correctly.

**Comment by markusaksli-nc** [comment] 2020-11-23 11:12
This is still reproducible on the latest master `1.24.0-8.0.pre.344` with the sample above.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.344, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.344 at C:\Development\flutter_master
    • Framework revision de56c6ad72 (15 hours ago), 2020-11-23 05:28:06 +0900
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 86.0.622.68

• No issues found!
```
</details>
<img src="https://user-images.githubusercontent.com/68219924/99955691-774b6300-2d8d-11eb-9f61-266eedeefec1.gif" height="600" />

**Comment by YeungKC** [comment] 2020-11-23 14:02
But it clearly shows the selected item?
It will be displayed even if you select 15.

**Comment by markusaksli-nc** [comment] 2020-11-23 14:09
The selected item (30) isn't centered. That's also why the issue is about large dropdowns

See https://github.com/flutter/flutter/issues/8266#issuecomment-280822976

**Comment by YeungKC** [comment] 2021-01-09 18:19
https://user-images.githubusercontent.com/11473691/104105562-008d0980-52ea-11eb-832e-7a27f88acd9c.mp4
Is this behavior as expected?

cc @markusaksli-nc @abarth @eseidelGoogle

**Comment by markusaksli-nc** [comment] 2021-01-15 11:38
This is certainly a possible fix but whether it's an acceptable solution or not isn't up to me. There should probably be some more discussion about this on your PR.

**Closed** 2021-01-25 18:49 UTC
Labels: P4, f: material design, found in release: 1.20, found in release: 1.24, framework, from: study, has reproducible steps
