### ISSUE TITLE
Text Shadows are not working after upgrading to flutter 3

### ISSUE THREAD

**Issue by rafiqueud** [flutter/flutter#105546] opened 2022-06-07 19:46 UTC
## Steps to Reproduce

1. Create an Text widget in a Flexible/Expanded Widget with a text that will break-line.
2. Add shadow to the TextStyle.
3. Look that the shadows are only painted in the last line.

The situation happens in iOS and Android.

**Expected results:**
Shadow in all text words of all lines.

**Actual results:**
Shadow only in last line.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    const shadows = [
      Shadow(
        offset: Offset(1, 1),
        blurRadius: 4.0,
        color: Color.fromARGB(100, 0, 0, 0),
      ),
      Shadow(
        offset: Offset(2, 2),
        blurRadius: 12.0,
        color: Color.fromARGB(125, 0, 0, 3),
      ),
    ];

    const textStyle = TextStyle(
      fontSize: 14,
      height: 1.8,
      letterSpacing: 0.2,
      wordSpacing: 1,
      fontWeight: FontWeight.w400,
      shadows: shadows,
      fontFamily: 'roboto-regular',
    );
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const [
            Expanded(
              child: Text(
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae congue tellus. Morbi orci augue, lacinia eu dui a, luctus maximus velit. Duis ex odio, posuere quis odio a, auctor iaculis massa. Sed eget turpis eget leo consequat venenatis. Duis risus elit, luctus non purus non, faucibus fermentum metus. In hac habitasse platea dictumst. Nullam et pretium magna, porttitor tincidunt nisl. Fusce interdum augue sed ante aliquet, id semper velit interdum. Ut urna orci, luctus ac enim vel, pulvinar condimentum sem. Integer a ante ac quam rutrum sagittis. Curabitur quis finibus diam. Maecenas at arcu lobortis, molestie lectus eu, imperdiet ligula. Sed eu tortor at nunc vulputate sagittis. Curabitur ac ex suscipit, gravida ex nec, pulvinar ipsum. Suspendisse facilisis lorem nibh, id consectetur augue pellentesque interdum.",
                style: textStyle,
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
$ flutter analyze
Analyzing bug...                                                        
No issues found! (ran in 1.2s)

```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale pt-BR)
    • Flutter version 3.0.1 at /Users/rafique/Workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/rafique/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA 2022.1 EAP.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] Connected device (3 available)
    • iPhone 12 mini (mobile) • C8BB8B55-086B-43EE-82AD-0C446B94195A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

<img width="458" alt="Captura de Tela 2022-06-07 às 16 26 02" src="https://user-images.githubusercontent.com/8432657/172465624-0ce5ef3f-e7f7-4404-853d-9993ed014600.png">

**Comment by maheshmnj** [comment] 2022-06-08 06:55
Hi @rafiqueud, Thanks for filing the issue. I am able to reproduce the issue  on stable and the master channel, White it works fine on the old version `stable 2.10.0` 

stable/master flutter 3 ❌ | stable 2.10.0  ✅   
:-------------------------:|:-------------------------:
![Screenshot_1654670995](https://user-images.githubusercontent.com/31410839/172551459-dd25a0dc-b18a-4294-b17c-b7c34a34d682.png) | ![Screenshot_1654671088](https://user-images.githubusercontent.com/31410839/172551444-ea04e10d-ded0-4b96-b356-060672d9edb5.png)


✅ : No Issue
❌: Issue reproduced 

Since this works fine in the older version, I am labeling this issue as a regression.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    const shadows = [
      Shadow(
        offset: Offset(1, 1),
        blurRadius: 4.0,
        color: Color.fromARGB(100, 0, 0, 0),
      ),
      Shadow(
        offset: Offset(2, 2),
        blurRadius: 12.0,
        color: Color.fromARGB(125, 0, 0, 3),
      ),
    ];

    const textStyle = TextStyle(
      fontSize: 14,
      height: 1.8,
      letterSpacing: 0.2,
      wordSpacing: 1,
      fontWeight: FontWeight.w400,
      shadows: shadows,
      fontFamily: 'roboto-regular',
    );
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Expanded(
              child: const Text(
                "Lorem ipsum dolor sit amet, asdadasdaasdad adad afsasd  sfsfs fs fsfsfsfsfs fsdada as adad adasd ad adipisdfsfsfscing elit. Nunc vitae congue tellus. Morbi orci augue, lacinia eu dui a, luctus maximus velit. Duis ex odio, posuere quis odio a, auctor iaculis massa. Sed eget turpis eget leo consequat venenatis. Duis risus elit, luctus non purus non, faucibus fermentum metus. In hac habitasse platea dictumst. Nullam et pretium magna, porttitor tincidunt nisl. Fusce interdum augue sed ante aliquet, id semper velit interdum. Ut urna orci, luctus ac enim vel, pulvinar condimentum sem. Integer a ante ac quam rutrum sagittis. Curabitur quis finibus diam. Maecenas at arcu lobortis, molestie lectus eu, imperdiet ligula. Sed eu tortor at nunc vulputate sagittis. Curabitur ac ex suscipit, gravida ex nec, pulvinar ipsum. Suspendisse facilisis lorem nibh, id consectetur augue pellentesque interdum.",
                style: textStyle,
              ),
            )
          ],
        ),
      ),
    );
  }
}
```
</details> 

<details>
<summary>flutter doctor -v(stable 2.10.0)</summary>

```
[✓] Flutter (Channel unknown, 2.10.0, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 2.10.0 at /Users/mahesh/Documents/flutter_dev
    • Upstream repository unknown
    • Framework revision 5f105a6ca7 (4 months ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1138, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1138 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9be807192 (26 hours ago), 2022-06-06 21:16:49 -0700
    • Engine revision 48864fc837
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 6AE1D692-DB57-4C3E-ADCA-66842182426B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-06-08 06:57
cc: @jason-simmons

**Comment by jason-simmons** [comment] 2022-06-08 21:22
Proposed fix: https://skia-review.googlesource.com/c/skia/+/548358

**Comment by rafiqueud** [comment] 2022-07-05 15:17
Do you know if this fix will be released soon?

**Comment by chinmaygarde** [comment] 2023-09-19 01:55
The fix has been merged and rolled in. Cleaning up the tracking issue.

**Closed by chinmaygarde** 2023-09-19 01:55 UTC
Labels: c: regression, engine, a: typography, has reproducible steps, P2, found in release: 3.0, found in release: 3.1, team-engine, triaged-engine
