### ISSUE TITLE
Android: EGL_BAD_ACCESS while app switch

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#23738] opened 2018-10-30 15:58 UTC
With the newest version of flutter, I'm not able to do an Android app switch anymore (iOS works just fine).

Setup:
* two apps (com.whatever.**one** & com.whatever.**two**)
* **one**: use [url_launcher](https://pub.dartlang.org/packages/url_launcher) to launch url (eg. "testapplicationtwo://test?value=test")
* **two**: react to app call from **one** with intent > invoke method to call Flutter

Log-statements in the intent implementation are logged. But because of the missing/wrong context (see error), the invokeMethod is never triggered (or not recognized in Flutter).

In MainActivity onCreate method of app **two**:
```dart
Intent intent = getIntent();
if (Intent.ACTION_VIEW.equals(intent.getAction())) {
  Uri uri = intent.getData();
  if("test".equals(uri.getHost())) {
    String value = uri.getQueryParameter("value");
    if(value != null) {
      methodChannel.invokeMethod("testmethod", value);
    }
  }
}
```

In AndroidManifest.xml of app **two**:
```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <data android:scheme="testapplicationtwo" />
</intent-filter>
```

Error in app **two**:
```dart
E/EGL_emulation: eglMakeCurrent: error: EGL_BAD_ACCESS: context 0xe8ac3a60 current to another thread!
E/EGL_emulation: tid 12193: eglMakeCurrent(1663): error 0x3002 (EGL_BAD_ACCESS)
E/libEGL: eglMakeCurrent:1091 error 3002 (EGL_BAD_ACCESS)
E/flutter: [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)] Could not make the context current
E/flutter: [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_ACCESS (12290)
```

I also tried to call it directly via intents - same result.

**Comment by zoechi** [comment] 2018-10-30 16:04
Please add the output of `flutter doctor -v`.

**Comment by YAPPDEF** [comment] 2018-10-30 16:29
```dart
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale de-CH)
    • Flutter version 0.9.4 at /Users/xx/Development/Tools/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Android NDK at /Users/xx/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (2 available)
    • Usage: ideviceinfo [OPTIONS]
      Show information about a connected device.
      
        -d, --debug		enable communication debugging
        -s, --simple		use a simple connection to avoid auto-pairing with the device
        -u, --udid UDID	target specific device by its 40-digit device UDID
        -q, --domain NAME	set domain of query to NAME. Default: None
        -k, --key NAME	only query key specified by NAME. Default: All keys.
        -x, --xml		output information as xml plist instead of key/value pairs
        -h, --help		prints usage information
      
        Known domains are:
      
        com.apple.disk_usage
        com.apple.disk_usage.factory
        com.apple.mobile.battery
        com.apple.iqagent
        com.apple.purplebuddy
        com.apple.PurpleBuddy
        com.apple.mobile.chaperone
        com.apple.mobile.third_party_termination
        com.apple.mobile.lockdownd
        com.apple.mobile.lockdown_cache
        com.apple.xcode.developerdomain
        com.apple.international
        com.apple.mobile.data_sync
        com.apple.mobile.tethered_sync
        com.apple.mobile.mobile_application_usage
        com.apple.mobile.backup
        com.apple.mobile.nikita
        com.apple.mobile.restriction
        com.apple.mobile.user_preferences
        com.apple.mobile.sync_data_class
        com.apple.mobile.software_behavior
        com.apple.mobile.iTunes.SQLMusicLibraryPostProcessCommands
        com.apple.mobile.iTunes.accessories
        com.apple.mobile.internal
        com.apple.mobile.wireless_lockdown
        com.apple.fairplay
        com.apple.iTunes
        com.apple.mobile.iTunes.store
        com.apple.mobile.iTunes
      
      Homepage: <http://libimobiledevice.org> • 00008020-001E543601F0002E            • ios • iOS Usage: ideviceinfo [OPTIONS]
      Show information about a connected device.
      
        -d, --debug		enable communication debugging
        -s, --simple		use a simple connection to avoid auto-pairing with the device
        -u, --udid UDID	target specific device by its 40-digit device UDID
        -q, --domain NAME	set domain of query to NAME. Default: None
        -k, --key NAME	only query key specified by NAME. Default: All keys.
        -x, --xml		output information as xml plist instead of key/value pairs
        -h, --help		prints usage information
      
        Known domains are:
      
        com.apple.disk_usage
        com.apple.disk_usage.factory
        com.apple.mobile.battery
        com.apple.iqagent
        com.apple.purplebuddy
        com.apple.PurpleBuddy
        com.apple.mobile.chaperone
        com.apple.mobile.third_party_termination
        com.apple.mobile.lockdownd
        com.apple.mobile.lockdown_cache
        com.apple.xcode.developerdomain
        com.apple.international
        com.apple.mobile.data_sync
        com.apple.mobile.tethered_sync
        com.apple.mobile.mobile_application_usage
        com.apple.mobile.backup
        com.apple.mobile.nikita
        com.apple.mobile.restriction
        com.apple.mobile.user_preferences
        com.apple.mobile.sync_data_class
        com.apple.mobile.software_behavior
        com.apple.mobile.iTunes.SQLMusicLibraryPostProcessCommands
        com.apple.mobile.iTunes.accessories
        com.apple.mobile.internal
        com.apple.mobile.wireless_lockdown
        com.apple.fairplay
        com.apple.iTunes
        com.apple.mobile.iTunes.store
        com.apple.mobile.iTunes
      
      Homepage: <http://libimobiledevice.org>
    • iPhone XS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            • D00311BE-A085-48DC-BA71-58C39E72C735 • ios • iOS 12.0 (simulator)

• No issues found!

```

**Comment by YAPPDEF** [comment] 2018-11-12 08:46
@zoechi is there any update? We're relying on this feature and currently we're not able to solve this on Android

**Comment by eseidelGoogle** [comment] 2018-11-21 14:59
@chinmaygarde or @liyuqian might have theories.

**Comment by dnfield** [comment] 2018-11-21 19:13
I can reproduce the error, but it doesn't acutally seem to hurt anything.  It seems like the app still runs fine.  What are you seeing after this error?

**Comment by YAPPDEF** [comment] 2018-11-21 19:54
@dnfield we're trying to switch between our apps (both built with Flutter). After the error occures, the context is lost and it seems as app-1 is "displayed" in app-2. So the content of app-1 is within the container of app-2. If I display the opened applications, I can see the same content in both apps and I cannot react to the intent.

What I'm trying to do: app-1 is our business app / app-2 is our security app
Trigger the security app to authorise an action from the business app. This functionality is very important for our project but cannot be achieved on Android - context is lost.

**Comment by dnfield** [comment] 2018-11-21 20:53
Ahh ok, I think I see now.  

So the EGL_CONTEXT error you're seeing actually has nothing to do with that.  That's more about how the Android intent system is working.  

What version of Flutter did this last work?

**Comment by dnfield** [comment] 2018-11-21 21:13
And to be clear, here's what I'm seeing in my own demo:

1. App 1 uses url_launcher to send an intent that launches the activity from App 2
1. App 2's activity loads in App 1's container
1. App 2 spits out the GL context error (bug in the engine), but recovers
1. App 2 responds to the intent with a log message

**Comment by dnfield** [comment] 2018-11-21 22:11
Unfortunately it's quite possible updates in Android in that time have caused this behavior too.

It may be worthwhile to get the behavior you're expecting working in a native app, and then compare how the intents/activities are working together.  I suspect that what you want to do requires some additional flags on the Intent that `url_launcher` isn't setting (or perhaps requires removing one that it is setting).  If you can get an example of how you'd expect this to work in a native app, it should be pretty trivial to identify exactly where the problem is occurring - whether it's a change in the Android runtime, a change in url_launcher, or a change in the Flutter embedding.

**Comment by YAPPDEF** [comment] 2018-11-22 09:11
I built two native apps:

**App1 (MainActivity.java)**:
```java
Uri uri = Uri.parse("app2://test?value=12345");
Intent intent = new Intent(Intent.ACTION_VIEW, uri);
startActivity(intent);
```

**App2 (MainActivity.java)**:
```java
Intent intent = getIntent();
if (Intent.ACTION_VIEW.equals(intent.getAction())) {
    Uri uri = intent.getData();
    if("test".equals(uri.getHost())) {
        String value = uri.getQueryParameter("value");
        if(value != null) {
            Log.d("APP2", "Value is " + value);
        }
    }
}
```
**App2 (AndroidManifest.xml)**:
```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <data android:scheme="app2" />
</intent-filter>
```

This works just fine (log: `D/APP2: Value is 12345`)

______________________________________________________

Now what's the real problem in my flutter apps:

**App1 (test.dart)**:
```dart
url_launcher.launch('app2://test?value=12345')
```

**App2 (MainActivity.java)**:
```java
Intent intent = getIntent();
if (Intent.ACTION_VIEW.equals(intent.getAction())) {
  Uri uri = intent.getData();
  if("test".equals(uri.getHost())) {
    String value = uri.getQueryParameter("value");
    if(value != null) {
      Log.d("APP2", "Value is " + value);
      methodHandler.invokeMethod("testaction", value);
    }
  }
}
```
**App2 (AndroidManifest.xml)**:
```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <data android:scheme="app2" />
</intent-filter>
```
**App1 logs**:
```dart
2018-11-22 09:53:55.020 15721-15751/com.test.app1 D/EGL_emulation: eglMakeCurrent: 0xe8a404a0: ver 3 0 (tinfo 0xe1231690)
2018-11-22 09:54:01.298 15721-15721/com.test.app1 W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@89a3c29
2018-11-22 09:54:01.358 15721-16008/com.test.app1 E/EGL_emulation: eglMakeCurrent: error: EGL_BAD_ACCESS: context 0xe8a3fae0 current to another thread!
2018-11-22 09:54:01.358 15721-16008/com.test.app1 E/EGL_emulation: tid 16008: eglMakeCurrent(1663): error 0x3002 (EGL_BAD_ACCESS)
2018-11-22 09:54:01.358 15721-16008/com.test.app1 E/libEGL: eglMakeCurrent:1091 error 3002 (EGL_BAD_ACCESS)
2018-11-22 09:54:01.358 15721-16008/com.test.app1 E/flutter: [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)] Could not make the context current
2018-11-22 09:54:01.358 15721-16008/com.test.app1 E/flutter: [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_ACCESS (12290)
```

**App 2 logs**:
```dart
2018-11-22 09:53:53.837 15594-15594/com.test.app2 W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b2cdbf0
2018-11-22 09:53:53.870 15594-15594/com.test.app2 V/FA: onActivityCreated
2018-11-22 09:53:53.893 15594-15977/com.test.app2 E/EGL_emulation: eglMakeCurrent: error: EGL_BAD_ACCESS: context 0xe8a405c0 current to another thread!
2018-11-22 09:53:53.893 15594-15977/com.test.app2 E/EGL_emulation: tid 15977: eglMakeCurrent(1663): error 0x3002 (EGL_BAD_ACCESS)
2018-11-22 09:53:53.894 15594-15977/com.test.app2 E/libEGL: eglMakeCurrent:1091 error 3002 (EGL_BAD_ACCESS)
2018-11-22 09:53:53.894 15594-15977/com.test.app2 E/flutter: [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)] Could not make the context current
2018-11-22 09:53:53.894 15594-15977/com.test.app2 E/flutter: [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_ACCESS (12290)
2018-11-22 09:53:53.902 15594-15615/com.test.app2 I/test.app: Waiting for a blocking GC ProfileSaver
2018-11-22 09:53:54.057 15594-15594/com.test.app2 D/APP2: Value is 12345
```

**Conclusion**:
The log works as well (log: `D/APP2: Value is 12345`)
But the methodHandler is never called (or received by flutter).

**Comment by YAPPDEF** [comment] 2018-11-22 20:06
Finally I was able to fix it:

LaunchMode on activity to **singleInstance** in both AndroidManifest.xml (App1 & App2)
`<activity android:launchMode="singleInstance" `

I didn't use url_launcher anymore and replaced all calls in native. On the Intent I additionally set those two flags:
`intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_SINGLE_TOP);`

I'm currently checking if every case is working - but seems to be ok.

**Comment by dnfield** [comment] 2018-11-22 20:08
Do you think it would be worth patching url_launcher to support this use case?

**Comment by YAPPDEF** [comment] 2018-11-22 20:10
I think the main difference was the launchMode of the apps (otherwise, the appSwitch would replace the app's container with the other app's content).
But if the two flags are helping why not. I'll let you know

**Comment by dnfield** [comment] 2018-12-17 22:48
Would you be interested in submitting a patch for that?  It seems like you probably have something pretty close to ready for it!

**Comment by YAPPDEF** [comment] 2018-12-18 09:01
The question is, if I should add it generally to the non web view call or add an additional parameter. For that I'm probably not expert enough for Android development..

But adding the following flags to the Intent solved my problem:
`intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_SINGLE_TOP);`

**Comment by yinzhiqun** [comment] 2019-01-14 03:07
I had the same problem when start the second FlutterActivity. It seems to appear when there are two FlutterView.

**Comment by maryx** [comment] 2019-02-08 01:21
I'm also encountering this issue - a patch would be great! What's happening for me is I have a FlutterView inside of an Android app. I open the FlutterView, then I swipe back to the Android view, and then I swipe to the FlutterView again, and then I see the error:
```
02-07 16:46:17.697  1128  1748 E flutter : [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)] Could not make the context current
02-07 16:46:17.697  1128  1748 E flutter : [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_ACCESS (12290)
```
in the logs. I'm not using url_launcher though, I think. I think the Android app is just launching the FlutterView via something like https://github.com/flutter/flutter/tree/master/examples/flutter_view

**Comment by collinjackson** [comment] 2019-04-11 18:26
It seems like there's an acceptable workaround for the original issue (possibly it should do this by default in the flutter create template) but that this issue still tends to come up in add-to-app scenarios.  I don't think this really specific to plugins but is rather a general Flutter Android issue, so I'm removing the plugin-related labels. It would be helpful to get a reduced test case that doesn't rely on plugins.

**Comment by maryx** [comment] 2019-04-11 19:51
For the add-to-app scenario I described above, it seems I never called flutterView.destroy(). That, along with https://github.com/flutter/engine/pull/8330, resolved the issue for my case.

**Comment by dnfield** [comment] 2019-04-11 21:13
Is there any action left to take on this bug then?  Maybe just add a note to the error log saying something like `Did you forget to call flutterView.destroy()?`

**Comment by Hixie** [comment] 2020-01-10 01:52
I couldn't figure out if what was needed here was a patch to url_launcher, a change to the logging when we detect a particular condition (what?), or nothing. Can someone clarify what the actionable next steps are for this bug?

**Comment by dnfield** [comment] 2020-01-10 04:01
I'm going to close this.  It sounds like the plugins team has decided that the proposed changes to url_launcher (the real reason this bug was originally opened) aren't suitable for the plugin - the other issue (the confusing log) seems like it hasn't been an issue for some time and has likely significantly changed in the new embedding anyway.

**Closed by dnfield** 2020-01-10 04:01 UTC
Labels: a: existing-apps, engine, severe: regression, ▣ platform-android
