### ISSUE TITLE
Unable to run Android app on stable  2.10 if it uses a plugin with an android folder but no Android support

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#97729] opened 2022-02-03 19:19 UTC
## Steps to Reproduce

The app can't be built on Android if a plugin is only iOS targetting. 
It's the case with [apple_map_flutter](https://pub.dev/packages/apple_maps_flutter). 

I can't run my app under Android with the new release ```Flutter: 2.10``` because the tool expect all plugins to support both Android and iOS or something like this (i have another project that builds find without `apple_map_flutter`)

1. Create a new project under flutter: 2.10
2. Add [apple_maps_flutter](https://pub.dev/packages/apple_maps_flutter) dependency using `flutter pub add apple_maps_flutter`
3. Build your app on Android device on flutter 2.10 stable/master

**Expected results:** 

The app should be built on Android (and on iOS) even if a plugin is missing for one of the platform, as it was done before ```flutter: 2.10```.

**Actual results:** 

```
Launching lib/main.dart on moto g 8 power in debug mode...
Running Gradle task 'assembleDebug'...
Plugin project :apple_maps_flutter not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/foxtom/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 421

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Cannot invoke method afterEvaluate() on null object
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-x64, locale fr-FR)
    • Flutter version 2.10.0 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (2 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • moto g 8 power (mobile) • ZY22BNDW2C • android-arm64  • Android 11 (API 30)
    • macOS (desktop)         • macos      • darwin-x64     • macOS 12.2 21D49 darwin-x64
    • Chrome (web)            • chrome     • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2022-02-04 07:36
Hi @Tom3652, Thanks for filing the issue. I  was able to reproduce the same behavior the app failed to build when using a plugin not supported for Android. This was reproducible on the latest stable/master and even on `stable 2.8.1`. This looks like a duplicate of https://github.com/flutter/flutter/issues/46304 (closed). Not sure if this is intended, But I was able to fix this by modifying the `settings.gradle`

<details>
<summary>settings.gradle (after modification)</summary>

```gradle
include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

// Fixed by adding the lines below

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
```
</details>


<details>
<summary>flutter run stable(2.10)</summary>

```
Launching lib[/main.dart]() on Redmi K20 Pro in debug mode...
lib/main.dart:1
Plugin project :apple_maps_flutter not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

* Where:
Script '[/Users/mahesh/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle]()' line: 421

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Cannot invoke method afterEvaluate() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 21s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```
</details>

<details>
<summary>flutter run (stable 2.8.1)</summary>

```console
mahesh@Maheshs-MacBook-Air-M1 sample % flutter run     
Launching lib/main.dart on Redmi K20 Pro in debug mode...
Plugin project :apple_maps_flutter not found. Please update settings.gradle.
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
e: /Users/mahesh/Desktop/sample/android/app/src/main/kotlin/com/example/sample/MainActivity.kt: (3, 19): Unresolved reference: embedding
e: /Users/mahesh/Desktop/sample/android/app/src/main/kotlin/com/example/sample/MainActivity.kt: (5, 21): Unresolved reference: FlutterActivity

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Running Gradle task 'assembleDebug'...                             37.2s
Exception: Gradle task assembleDebug failed with exit code 1
```
</details>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (2 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.371, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.371 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1285eef1b (2 days ago), 2022-02-02 00:50:20 -0500
    • Engine revision 5bbdb7a6f7
    • Dart version 2.17.0 (build 2.17.0-74.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

 cc: @blasten

**Comment by Tom3652** [comment] 2022-02-04 12:57
Thank you @maheshmnj it's indeed working with your ```settings.gradle``` file ! :)

**Comment by stuartmorgan** [comment] 2022-02-04 15:55
I'm very confused here.

> ```groovy-gradle
> // Fixed by adding the lines below
> ```

The lines you've added below that should *cause* this issue, not fix it. It unconditionally adds every plugin, unlike `app_plugin_loader.gradle` which filters by supported platform.

**Comment by stuartmorgan** [comment] 2022-02-04 15:56
@Tom3652 Could you provide the `.flutter-plugins-dependencies` file for a project that reproduces this?

**Comment by Tom3652** [comment] 2022-02-04 16:02
Yes sure @stuartmorgan : 

```
{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"apple_maps_flutter","path":"/Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/apple_maps_flutter-1.0.1/","dependencies":[]}],"android":[],"macos":[],"linux":[],"windows":[],"web":[]},"dependencyGraph":[{"name":"apple_maps_flutter","dependencies":[]}],"date_created":"2022-02-04 17:01:44.328220","version":"2.10.0"}%  
```

I have simply created a new project, added the ```apple_map_flutter``` and build on my android device.

**Comment by stuartmorgan** [comment] 2022-02-04 16:20
Oh, I see. This is the new code to check min SDK versions. It's still using `.flutter-plugins`, which is wrong; it should be using `.flutter-plugins-dependencies`.

In most cases it will still work because `flutter_tools/gradle/flutter.gradle` does its own filtering based on the presence of a gradle file in the right place in the plugin, but that is being defeated by the fact that `apple_maps_flutter` has an android/ folder even though it doesn't support Android.

We should definitely fix this on our side by updating `flutter_tools/gradle/flutter.gradle` to use `.flutter-plugins-dependencies`, but it can also be fixed by the plugin author. I'll file an issue there.

**Comment by stuartmorgan** [comment] 2022-02-08 16:32
> Any solution to this?

If you want a solution that can be applied immediately, before the Flutter-side fix reaches the stable channel, plugin authors can trivially fix this by removing the `android/` directory from their plugin if it doesn't declare Android support in `pubspec.yaml`.

**Comment by topex-psy** [comment] 2022-02-09 13:59
This has not been solved even on the master channel. Please reopen this.

**Comment by stuartmorgan** [comment] 2022-02-09 16:40
The fix had to be reverted (https://github.com/flutter/flutter/pull/98050)

**Comment by stuartmorgan** [comment] 2022-02-10 12:19
This is not currently fixed on any channel.

What plugin are you having this issue with? Have you contacted that plugin's developer?

**Comment by YDA93** [comment] 2022-02-10 13:05
```
Plugin project :soundpool_web not found. Please update settings.gradle.
Plugin project :soundpool_macos not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

* Where:
Script '[/Users/yousefalmutairi/flutter/packages/flutter_tools/gradle/flutter.gradle]()' line: 421

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Cannot invoke method afterEvaluate() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 1s
```

**Comment by YDA93** [comment] 2022-02-10 13:14
> > Any solution to this?
> 
> If you want a solution that can be applied immediately, before the Flutter-side fix reaches the stable channel, plugin authors can trivially fix this by removing the `android/` directory from their plugin if it doesn't declare Android support in `pubspec.yaml`.

Would this cause breaking change to plugin users under flutter 2.10?

**Comment by stuartmorgan** [comment] 2022-02-10 13:18
> Would this cause breaking change to plugin users under flutter 2.10?

Android stubs haven't been required since at least 1.17.

**Comment by andesappal** [comment] 2022-02-15 15:10
Hi, my issue https://github.com/flutter/flutter/issues/98223 might be related to the cause of this one

**Comment by mdrideout** [comment] 2022-05-23 22:28
> > Any solution to this?
> 
> If you want a solution that can be applied immediately, before the Flutter-side fix reaches the stable channel, plugin authors can trivially fix this by removing the `android/` directory from their plugin if it doesn't declare Android support in `pubspec.yaml`.

I was having this issue developing a federated plugin. If you are building a federated plugin, you need to delete (or just rename to android.bak) the android folder from the main plugin package.

Example: if using the [url_launcher](https://github.com/flutter/plugins/tree/main/packages/url_launcher) architecture. 

- your_plugin_package    <-- Delete android folder from this one
  - your_plugin_package_platform_interface
  - your_plugin_package_ios
  - your_plugin_package_web
  - your_plugin_package_android

**Comment by stuartmorgan** [comment] 2022-05-31 15:51
> If you are building a federated plugin, you need to delete (or just rename to android.bak) the android folder from the main plugin package.

If you are building a fully federated plugin you should be doing that regardless of this bug, and for all platforms, because in the structure you are describing having platform implementation directories in the app-facing package is dead code that you are shipping to all clients of your plugin.

**Comment by stuartmorgan** [comment] 2022-11-02 14:48
No, it's still a bug. It's trivial for plugin developers to avoid by deleting dead/dummy `android/` directories, but we shouldn't fail to build if they don't.

**Closed** 2023-12-21 16:55 UTC
Labels: c: regression, platform-android, tool, a: build, has reproducible steps, P2, found in release: 2.10, team-android, triaged-android, multiteam-retriage-candidate
