### ISSUE TITLE
Failed to send request: {"jsonrpc":"2.0"..... flutter_windows_v1.7.8+hotfix.3-stable

### ISSUE THREAD

**Issue by denizhoxha** [flutter/flutter#36100] opened 2019-07-12 21:11 UTC
I am getting plenty of the below exception 
Failed to send request: {"jsonrpc":"2.0","id":"593","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"594","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"595","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"596","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"597","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"598","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"599","method":"getVM","params":{}}
Failed to send request: {"jsonrpc":"2.0","id":"600","method":"getVM","params":{}}

Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

When i switched to master branch I got **Lost connection to device.**.

Syncing files to device SM G965F...
E/DartVM  (30216): vm-service: Error: Unhandled exception:
E/DartVM  (30216): Unrecognized response: null
E/DartVM  (30216): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
E/DartVM  (30216): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
E/DartVM  (30216): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
E/DartVM  (30216): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/DartVM  (30216): 
E/flutter (30216): [ERROR:flutter/runtime/dart_isolate.cc(814)] Unhandled exception:
E/flutter (30216): Unrecognized response: null
E/flutter (30216): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
E/flutter (30216): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
E/flutter (30216): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
E/flutter (30216): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Lost connection to device.

Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.8.2-pre.61, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (3 available)

**Comment by rahulmanthena** [comment] 2019-07-13 03:10
I am having the same issue on macOS. Using 'flutter run' in terminal doesn't have this issue. I am on master branch.

**Comment by gerryhigh** [comment] 2019-07-13 04:13
Am seeing this on Windows in Android Studio. Like @rahulmanthena using flutter run in a command prompt doesn't have this issue.

**Comment by PreritO** [comment] 2019-07-13 06:37
> I am having the same issue on macOS. Using 'flutter run' in terminal doesn't have this issue. I am on master branch.

Same problem here

**Comment by denizhoxha** [comment] 2019-07-13 09:12
Thank you @rahulmanthena tried to run via command line and is working correctly.

**Comment by calvinmuller** [comment] 2019-07-13 12:13
also same issue on MacOSX

**Comment by xinoxapps** [comment] 2019-07-13 14:12
Same issue

> vm-service: Error: Unhandled exception:
Unrecognized response: null
#0      new Response.from (dart:_vmservice/message_router.dart:70:7)
#1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
#2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[VERBOSE-2:dart_isolate.cc(814)] Unhandled exception:
Unrecognized response: null
#0      new Response.from (dart:_vmservice/message_router.dart:70:7)
#1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
#2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"7","method":"getVM","params":{}}

[✓] Flutter (Channel master, v1.8.2-pre.30, on Mac OS X 10.14.5 18F132, locale nl-NL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2018.2.7)
[✓] Connected device (3 available)

**Comment by momsenmeister** [comment] 2019-07-13 17:59
Same here, but on channel stable.

[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale de-DE)
    • Flutter version 1.7.8+hotfix.3
    • Framework revision b712a172f9 (4 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7830

[√] Connected device (1 available)
    • android-arm64 • Android 9 (API 28)

**Comment by senitiki** [comment] 2019-07-14 06:16
Facing the same problem on Android Studio (Windows 10). **flutter run** via the console, however, is working.

[√] Flutter (Channel master, v1.8.2-pre.29, on Microsoft Windows [Version 10.0.18362.239], locale en-FJ)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.6)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (2 available)

**Comment by rockingdice** [comment] 2019-07-14 07:27
Same issue with Idea IDE.

**Comment by panmin** [comment] 2019-07-14 11:10
the same problem in master and stable

**Comment by EricPreventa** [comment] 2019-07-15 19:13
wow shocked to see so many people also having this problem. Running Mojave, with Intellij Ultimate, with the latest iPad running the latest version.

**Comment by collinjackson** [comment] 2019-07-15 21:10
This might be the same as https://github.com/flutter/flutter/issues/36150

**Comment by gspencergoog** [comment] 2019-07-15 22:19
Assuming this is a duplicate of https://github.com/flutter/flutter/issues/36150. Closing.

**Closed by gspencergoog** 2019-07-15 22:19 UTC

**Comment by collinjackson** [comment] 2019-07-15 22:33
Follow this issue for the fix, which will likely involve updating IntelliJ plugin: https://github.com/flutter/flutter-intellij/issues/3670

**Comment by prasant10050** [comment] 2019-07-16 06:56
I am also facing this issue on flutter master channel in MacOs

**Comment by collinjackson** [comment] 2019-07-16 17:53
This has been fixed in flutter/flutter-intelli#3669. Updating to the latest IntelliJ/Android Studio plugin should address the issue.

**Comment by herrmartell** [comment] 2020-07-20 18:17
I'm seeing this issue as well. Have Flutter plugin v47.1.2 and Dart v193.9361. Android Studio v4.0.1.

**Comment by Jamminroot** [comment] 2021-05-27 17:48
```
Android Studio 4.2
Dart Plugin 202.8488
Flutter Plugin 56.0.2

Dart version 2.13.0
Flutter version 2.2.0
```
