### ISSUE TITLE
flutter doctor error on IntelliJ IDEA: FormatException: Unexpected extension byte (at offset 5)

### ISSUE THREAD

**Issue by Dargoz** [flutter/flutter#95604] opened 2021-12-21 02:32 UTC
## Steps to Reproduce

1. run ``flutter doctor``
2. got issues  

## Logs

<details>
<summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1083], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code, 64-bit edition (version 1.63.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

```
```

</details>

**Comment by danagbemava-nc** [comment] 2021-12-21 08:32
Duplicate of #94060

**Closed by danagbemava-nc** 2021-12-21 08:32 UTC
Labels: in triage
