### ISSUE TITLE
When debug flutter App with Xcode, It will be in white screen it will take a moment to render

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#67188] opened 2020-10-03 03:11 UTC
When I m using Xcode to bug my flutter App,It will be in white screen..And it will be a long moment to render out.But it will be ok when i use idea to debug it

```
[✓] Flutter (Channel stable, 1.22.0, on macOS 11.0 20A5384c, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (2 available)
    ! Error: 文景睿的iPhone is busy: Copying cache files from device. Xcode will
      continue when 文景睿的iPhone is finished. (code -10)

```

**Comment by Andy-Python-Programmer** [comment] 2020-10-03 03:40
Duplicate 22338

**Comment by luckysmg** [comment] 2020-10-03 14:13
emm i still don't know how to solve this proble,........

**Comment by TahaTesser** [comment] 2020-10-05 12:26
This looks like the opposite/duplicate of https://github.com/flutter/flutter/issues/63800
Where that issue was when you launch from IDE, it shows a white screen longer compared to when launched from code but here looking closely, code has a long white screen when launched from Xcode than IDE, this is reproducible on the `master` channel as well

| VSC | Xcode |
| --------------- | --------------- |
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/95078889-77d36000-0733-11eb-9654-1660eec20686.gif) | ![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/95078947-8caff380-0733-11eb-8b3a-4a0fa5a07e40.gif)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • AFF9AE1D-D6C7-46C4-9288-A98DB74D942B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.0 at /Users/tahatesser/Code/flutter_beta
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (3 available)            
    • iPhone 11 (mobile) • AFF9AE1D-D6C7-46C4-9288-A98DB74D942B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.121

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.132, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.132 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 5e97eed895 (5 hours ago), 2020-10-05 00:42:50 -0700
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • iPhone 11 (mobile) • AFF9AE1D-D6C7-46C4-9288-A98DB74D942B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.121

• No issues found!
```

</details> 


CC @jmagman 
Please close if this is already addressed

**Comment by kf6gpe** [comment] 2020-10-05 15:46
@luckysmg Can you let us know what version of iOS your iPhone under test is, please? Thanks!

**Comment by luckysmg** [comment] 2020-10-05 15:50
OK，my iOS version is 14.0 iphoneX







发自我的iPhone


------------------ Original ------------------

**Comment by TahaTesser** [comment] 2020-10-05 16:00
The white screen issue I mentioned in my https://github.com/flutter/flutter/issues/67188#issuecomment-703598263 was reproducible on iOS 13 hence I didn't add  `OS Version specific` label. Unless it's Xcode 12 related issue, this should reproduce on iOS 13 as well

**Comment by gaaclarke** [comment] 2020-10-05 17:50
Since the screen is stuck on white for 10 seconds it seems to be the same problem that was mentioned in https://github.com/flutter/flutter/issues/63800, synchronizing the files times out after 10 seconds, retries and succeeds the second time.

There is a bug in the Dart devfs server where it sometimes doesn't return a status code for a PUT command and we timeout waiting for it.  I had to choose 10 seconds to accommodate slow server farms but found that a 0.5 second timeout worked perfectly fine locally.

As a workaround until those dart issues are fixed (https://github.com/dart-lang/sdk/issues/43525) you can edit that timeout like so:
```diff
--- a/packages/flutter_tools/lib/src/devfs.dart
+++ b/packages/flutter_tools/lib/src/devfs.dart
@@ -302,7 +302,7 @@ class _DevFSHttpWriter implements DevFSWriter {
         // tests in "Google Tests".
         try {
           final HttpClientResponse response = await request.close().timeout(
-            const Duration(milliseconds: 10000));
+            const Duration(milliseconds: 500));
           response.listen((_) {},
             onError: (dynamic error) {
               _logger.printTrace('error: $error');
```

**Comment by jmagman** [comment] 2020-11-30 19:24
https://github.com/flutter/flutter/issues/68215#issuecomment-734843052 @SCaptainCAP 
> Open xCode, click Window -> Devices and Simulators. My IPhone was there with the notice: `IPhone is busy: Copying cache files from device`. I just waited around 2~3 minutes till that text went away, then the flutter error was also fixed. So, it's just some apple's dark magic.
> 
> My Iphone: IOS 14.2, My Flutter: channel beta, 1.24.0-10.2.pre

https://github.com/flutter/flutter/issues/68215#issuecomment-734844242 @sanekyy
> I fixed this issue via [this](https://developer.apple.com/forums/thread/651012).
> 
> It looks like Xcode problem.

**Comment by jmagman** [comment] 2020-12-16 01:18
I was never able to reproduce this.  @luckysmg are you seeing this on Xcode 12.3?

**Comment by luckysmg** [comment] 2020-12-16 11:20
Xcode 12.3 works fine @jmagman

**Comment by jmagman** [comment] 2020-12-16 17:46
@TahaTesser I know you reproduced as well, can you confirm you no longer see this in newer versions of Xcode?

**Comment by TahaTesser** [comment] 2020-12-17 10:16
Hi @jmagman 
I can reproduce it on Xcode 12.3 on iOS 14.3 simulator, it sometimes runs slower, sometimes faster (deleted existing app on each run)

### Steps to reproduce

1. Run from Xcode, in either from `xcodeproject` or `xcworkspace`, same results 
2. uninstall the existing app for each run. You may see a slow run or fast run, if you repeating this, you would see both results multiple times. (I saw slow run two times in my testing) 

| When launching from Xcode taking longer than 10s |
| --------------- | 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/102473680-c0858e80-407d-11eb-86ea-d5cc84d0f087.gif) |

| When launching from Xcode is faster |
| --------------- | 
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/102474250-6cc77500-407e-11eb-85bf-5adffa905e80.gif) |

| When launching from VSCode is fast too |
| --------------- | 
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/48603081/102474573-d051a280-407e-11eb-9fb8-3e94d42573cd.gif) |

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.64, on macOS 11.1 20C69 darwin-x64,
    locale en-GB)
    • Flutter version 1.26.0-2.0.pre.64 at /Users/tahatesser/Code/flutter_master
    • Framework revision 9ff4326e1f (4 hours ago), 2020-12-17 06:19:05 +0000
    • Engine revision 6edb402ee4
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 01685E98-F396-4EB9-9C58-8B92677E24D5 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.1 20C69 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

**Closed** 2021-05-10 04:36 UTC
Labels: a: debugging, a: quality, found in release: 1.22, found in release: 1.23, has reproducible steps, platform-ios, t: xcode, tool
