### ISSUE TITLE
[LineageOS] Screen rendering uncomplete in landscape mode

### ISSUE THREAD

**Issue by Ifilehk** [flutter/flutter#123545] opened 2023-03-27 16:15 UTC
I am experiencing a rendering problem when running my app on a Samsung S4 GT I9505 with Lineage OS 19. The problem is the same in debug or release mode. Sometime also the screen in flickering strangely.

Flutter tells this:
```
aunching lib/main.dart on GT I9505 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:42625/oBF6DfsWiVc=/ws
Syncing files to device GT I9505...
D/CompatibilityChangeReporter( 2900): Compat change id reported: 78294732; UID 10201; state: ENABLED
I/flutter ( 2900): QR: Finding Match for / under root
I/flutter ( 2900): QR: adding Route: Key: [0](root), Full Path: / to the navigator with Key: [-1](Root)
I/flutter ( 2900): Observer: Navigating to /
I/flutter ( 2900): QR: Root observer: Push: root
I/Gralloc4( 2900): mapper 4.x is not supported
W/Gralloc3( 2900): mapper 3.x is not supported
W/Gralloc4( 2900): allocator 4.x is not supported
W/Gralloc3( 2900): allocator 3.x is not supported
I/Gralloc2( 2900): Adding additional valid usage bits: 0x2202400
I/flutter ( 2900): service.invoke('INITIALIZED');
I/flutter ( 2900): QR: Finding Match for / under root
I/flutter ( 2900): Observer: popping out from /
I/flutter ( 2900): QR: Finding Match for /main under root
I/flutter ( 2900): QR: adding Route: Key: [1](main), Full Path: /main to the navigator with Key: [-1](Root)
I/flutter ( 2900): Observer: Navigating to /main
I/flutter ( 2900): QR: Root observer: Push: main
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 2900): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
```
And the doc this:

[✓] Flutter (Channel master, 3.9.0-17.0.pre.21, on Ubuntu 22.04.2 LTS 5.15.0-67-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

https://user-images.githubusercontent.com/108150565/227784832-5a366d57-f7f4-4c08-b024-7f0828791a18.mp4

**Comment by huycozy** [comment] 2023-03-28 06:37
Hi @Ifilehk 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the complete output of `flutter run -v` as well (If the log is too long, please save it into a file and attach it here). Thank you!

**Comment by huycozy** [comment] 2023-03-28 09:52
Can you please check if the issue also happens on Android native project or not? (Sample code: [Android-Native-Sample](https://github.com/huycozy/Android-Native-Sample))

**Comment by Ifilehk** [comment] 2023-03-28 10:42
In native android no problem !!!

https://user-images.githubusercontent.com/108150565/228211485-eb7c21cc-3a2d-4def-a790-b9a04d00d30d.mp4

**Comment by reidbaker** [comment] 2023-03-30 18:07
Note from Android team triage: We think the engine team should set the priority here.

**Comment by reidbaker** [comment] 2023-03-30 19:16
Thank you for taking the time to file this issue. This appears to be a duplicate of #123353. Please track that issue for updates. If you believe I've made an error, please reply here with more details that explain the difference and we'll re-open this issue.

**Closed by reidbaker** 2023-03-30 19:16 UTC
Labels: e: device-specific, platform-android, engine, severe: rendering, e: OS Version specific

**Comment by Ifilehk** [comment] 2023-04-05 17:20
Fantastic!!! Problem is solved for me with the last update:

Flutter 3.9.0-22.0.pre.32 • channel master • https://github.com/flutter/flutter.git
Framework • revision daaa32bc06 (17 minutes ago) • 2023-04-05 09:30:36 -0700
Engine • revision db23c3fbe0
Tools • Dart 3.0.0 (build 3.0.0-409.0.dev) • DevTools 2.23.0
