### ISSUE TITLE
Incomplete implementation of EngineParagraphBuilder prevents flutter_html from working in chrome and fuchsia (linux)

### ISSUE THREAD

**Issue by tobiww** [flutter/flutter#51306] opened 2020-02-24 02:21 UTC
The flutter_html plugin works with android and ios, but fails on linux in both web/chrome and go-desktop. The first problem I ran into was an exception in `widget_span.dart` line 108:

```
  assert(builder.placeholderCount < dimensions.length);
```

The crash was not assertion failure, it was that builder (an implementation of `EngineParagraphBuilder`) does not initialize `_placeholderCount`, so it returns null.
(When this executes for Android, at this line of code, 'builder' is an instance of ParagraphBuilder, and the exception does not occur, as ParagraphBuilder correctly initializes _placeholderCount in its constructor).

If you work around this bug by replacing "builder.placeholderCount" with "builder.placeholderCount ?? 0" in the two occurrences in widget_span.dart, the next problem you run into is UnimplementedError inside addPlaceholder (engine/text/paragraph.dart):

```
@override
  void addPlaceholder(
    double width,
    double height,
    ui.PlaceholderAlignment alignment, {
    double scale,
    double baselineOffset,
    ui.TextBaseline baseline,
  }) {
    // TODO(garyq): Implement stub_ui version of this.
    throw UnimplementedError();
  }
```

Working around that seemed beyond my current dart/flutter skills, so here's the bug report.

By the way, the widget tree from fluter_html is about as trivial as possible:

```
  Html( data: """<p>Hello world</p>""" )
```

```
This is what the widget hierarchy looks like with the web device (it's not 
the same on Android), one stack frame up from the crashing code, when
`this` is a TextSpan widget. It's the call to child.build that triggers the crash inside
widget_span.dart.

TextSpan
 children:[
   WidgetSpan:
     child: 
       ContainerSpan:
         children: [
           TextSpan: 
              text: "Hello world"
         ]
 ]
```

## Impact

This problem blocks the flutter_html plugin from working in web view/chrome, and also in go-desktop.

## Larger impact

I've run into separate blocking bugs trying flutter_widget_from_html, webview_flutter, and flutter_webview_plugin, and so I'm really struggling to find a way to make a cross-platform flutter app (mobile & desktop) that can display even limited html.

## System info:

- Tried both Flutter beta (1.14.6) and Fluter dev (1.15.3)
- Platform: Arch Linux. I had been using the 5.5 kernel, then rolled it back to 5.4 because of the epoll-related hang on 5.5 kernels: [dart-lang/40589](https://github.com/dart-lang/sdk/issues/40589), [dart-lang/49185](https://github.com/flutter/flutter/issues/49185)

**Comment by tobiww** [comment] 2020-02-24 02:37
[edit]  The title is presumptive: I don't really know if there are additional issues that block flutter_html from working with web and go-flutter on linux, but it appears that this is at least one of them. If you fix this, I'll be happy to find and report on whether there are other blockers!
-- Thanks

**Comment by mdebbar** [comment] 2020-02-28 05:07
@tobiww you are right, this is the same issue as https://github.com/flutter/flutter/issues/42086 so I'll mark it as duplicate. I'll close this one and keep the other one since it's older and has more thumbs-ups.

Duplicate of https://github.com/flutter/flutter/issues/42086

**Closed by mdebbar** 2020-02-28 05:07 UTC
Labels: engine, severe: new feature, ☸ platform-web

**Comment by kiaxseventh** [comment] 2020-03-05 16:00
i see lot of issue about this problem but every one closed !
do not have any solution from this problem ?!
