### ISSUE TITLE
Engine builds failing 'gcloud pubsub' step

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#120096] opened 2023-02-06 16:43 UTC
See: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/20197/overview

**Comment by drewroengoogle** [comment] 2023-02-06 17:30
@yusuf-goog I noticed you assigned this to yourself, do you have more context on what the issue is? I wasn't able to find anything, as it seems like the CIPD package referenced is available [here](https://chrome-infra-packages.appspot.com/p/infra/3pp/tools/gcloud/linux-amd64/+/BF0Ycb5t2-Ol3pdqmG62DBabDVgGdCd5nSjkFQPaVtoC)

**Comment by yusuf-goog** [comment] 2023-02-06 17:35
Just got this this morning. I think it might have something to do with a goma change that was made. Checking with @godofredoc about that.

Also looking into if there was some issue with the gcloud cipd package version/path, that might have caused this to not be found.

**Comment by whesse** [comment] 2023-02-06 18:03
I checked the gcloud cipd package that is being downloaded, it does have the gcloud executable at the correct place.

Is the problem just that the successful try builds are running gcloud on windows by running python.exe lib\gcloud.py and the failing ones are trying to run bin\gcloud , both from the CIPD checkout?

**Comment by whesse** [comment] 2023-02-06 18:12
The code that runs gcloud, either with python or not, is coming from the fuchsia gcloud recipe module.  Perhaps that rolled in the recipes bundle.

**Comment by godofredoc** [comment] 2023-02-06 18:16
The python part is already fixed with a roll to the latest versions of fuchsia recipes and other deps. The remaining part is a problem with the gcloud binary not found in windows.

**Comment by yusuf-goog** [comment] 2023-02-06 18:39
Setting up a CL to disable this step to unblock the builds till we can root cause.

**Comment by yusuf-goog** [comment] 2023-02-06 18:53
https://flutter-review.git.corp.google.com/c/recipes/+/38600

**Closed** 2023-02-06 22:58 UTC
Labels: team: infra, P0
