### ISSUE TITLE
Keyboard shortcuts stop working when caps lock is down.

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#79374] opened 2021-03-30 14:33 UTC
### Steps to reproduce 
1. Creat a project on any of the latest channels
2. Add a `TextField()` 
or try the code sample below

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>

### Actual Results 
Be able to enter only capital text and delete the text with backspace/delete

### Expected Results
Not able to delete text with backspace/delete when text is in caps in the end

Note:
1. If you enter lower caps text right after all caps text, you will be able to delete text backspace/delete
2. If you enter only lower caps, there is no issue
3. It reproduces all channels (check multiple doctor -v below) on the macOS Desktop app
 

| When there is only capital text | 
| --------------- | 
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/48603081/113006272-e3940400-917d-11eb-9d05-140322bc204e.gif) |

| Backspace/delete only working where there non-captial text at the end  | 
| --------------- | 
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/48603081/113006072-b2b3cf00-917d-11eb-9390-3dcad15f8534.gif) | 

![Screenshot 2021-03-30 at 5 21 58 PM](https://user-images.githubusercontent.com/48603081/113004714-7c298480-917c-11eb-86a9-f3797f25dcf3.png)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (12 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

```bash
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-x64,
    locale en-GB)
    • Flutter version 2.1.0-12.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5bedb7b1d5 (13 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

```bash
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on macOS 11.2.3 20D91 darwin-x64,
    locale en-GB)
    • Flutter version 2.1.0-12.1.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 8264cb3e8a (3 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.323, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.323 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 2cdd51900c (6 hours ago), 2021-03-30 10:16:05 +0200
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```
	
</details>

**Comment by justinmc** [comment] 2021-03-30 16:05
I can't reproduce this on the latest master using the same version of Big Sur with the code above.  I start the app, type "FFFFFF", and press delete, and it deletes like normal.  Am I following the steps correctly?

Strange bug though, I'm not sure what would cause this.

**Comment by TahaTesser** [comment] 2021-03-30 16:20
@justinmc 
Just tried again on-screen keyboard to demonstrate my key-stroke pattern, with it even lower case text isn't being not deleted. While the text in Chrome deletes fine 

https://user-images.githubusercontent.com/48603081/113021910-bbf86800-918c-11eb-856d-09f02ef2aa0a.mov

**Comment by darshankawar** [comment] 2021-03-31 09:54
This issue has a pattern involving onscreen keyboard with which it can be replicated, as below:

1.  When TextField is focussed and we use physical keyboard to enter lower case and upper case letters, the letters are deleted, as expected:


https://user-images.githubusercontent.com/67046386/113124573-45627580-9233-11eb-874f-02570d9f8be9.mov

2. If we open onscreen keyboard that has a default input source (ex: ABC or ABC extended) and type in lower case letters, then those letters are deleted as expected, but as soon as we turn ON caps lock and type in a letter, then those are not getting deleted. Moreover, if we turn OFF caps lock and now enter lower case letters, now these are also not getting deleted:


https://user-images.githubusercontent.com/67046386/113124851-983c2d00-9233-11eb-8bb9-e0d5958dedca.mov

3. Now if we switch to physical keyboard and try to enter any lower case or upper case letter, none is deleted:


https://user-images.githubusercontent.com/67046386/113125324-1bf61980-9234-11eb-83bc-7579ae1c15c9.mov

Looking at step 2 above, if we are coming back from onscreen keyboard to physical keyboard, then regular letters in small caps or upper case letters are not getting deleted, so this issue isn't limited to not deleting last upper case letter, but if the last letter is small caps, the same issue persists.


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.346, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.346 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8158b478d7 (2 hours ago), 2021-03-31 13:29:03 +0800
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment] 2021-03-31 10:04
Originally issue reproduced without using the on-screen keyboard  https://github.com/flutter/flutter/issues/79374#issue-844653134

Here is a demonstration of the issue without ever opening on-screen keyboard  [1 min complete preview]

https://user-images.githubusercontent.com/48603081/113127443-6de17400-9221-11eb-8c47-3f60d76a7e9d.mov

**Comment by gspencergoog** [comment] 2021-04-01 18:28
This is a known issue caused by not tracking the caps lock state separately from the caps lock key press state. This should be fixed by https://github.com/flutter/flutter/issues/44918

**Comment by edwardaux** [comment] 2021-08-09 19:56
Hi all, I originally raised another ticket when I encountered this problem on the mac, but subsequently discovered that this one had already been raised. In my case it was specifically that backspace, delete and cursor arrows just mysteriously stop working when caps-lock is on.

I see that #44918 has been earmarked as the ticket that will fix it, however that ticket has been open for almost 2 years now with no visibility as to when it will be released (which is totally fine... it is a large ticket with a lot of implications so I get that it takes time).

However, the question is what to do about this problem right now. Where we are at the moment is that the app can easily get into a state where important keystrokes are just ignored and there's no clue to the user about why that is happening. I mean, I'm a developer and it took me ages to track down a repeatable case... what hope do my users have of figuring out why the app has suddenly stopped responding?

Is there any chance of a tactical fix or a suggested workaround while we're waiting for 44918 (and/or a bump in the priority)? I get that caps-lock isn't massively used on mobile, but on desktop/web, it is *very* common. This feels, to me, like a pretty bad bug and to be honest, I'm reluctant to ship a mac app where my app becomes non-responsive just because the user has their caps-lock key on.

**Comment by edwardaux** [comment] 2021-08-11 22:41
Actually, there's definitely another underlying problem with the cursor/backspace keys. I've lost count of the number of times I've just suddenly lost the ability to backspace even without caps lock on (it also affects the cursor arrow keys, delete, and the tab key). Normal text entry continues to work fine. 

I'm yet to find a reliable way to reproduce, but it happens approx 10 times a day for me (note that this is on macOS... not sure if it happens on mobile too).

Not that I expect anyone from the Flutter team to be able to do anything without a repeatable test case, but I just thought I'd mention it here as a datapoint.

**Comment by cbracken** [comment] 2021-09-28 22:18
Assigning to @dkwingsmt to ensure this is on his radar.

**Comment by cbracken** [comment] 2021-10-18 17:54
Tested just now on Win32 and wasn't able to reproduce in the following situations:
* physical keyboard only
* on-screen keyboard, using caps-lock and control key combinations on on-screen keyboard
* physical keyboard with on-screen keyboard up

I'm going to label this as macOS-specific for the moment since it seems like all reports above have been for macOS. I have not yet tested on macOS.

**Comment by dkwingsmt** [comment] 2022-03-04 05:47
This issue should have been fixed by https://github.com/flutter/flutter/pull/80756 (merged on Apr 26, 2021).

@edwardaux I'm sorry to hear about the random hiccups. We have improved a lot since your comment. Let us know if you're experiencing any issues lately.

**Closed by dkwingsmt** 2022-03-04 05:47 UTC
Labels: a: text input, framework, f: material design, platform-mac, a: desktop, has reproducible steps, P4, found in release: 2.1
