### ISSUE TITLE
Using var with String.fromEnvironment returns empty string.

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#59110] opened 2020-06-09 23:12 UTC
I've just modified my launcher to use a --dart-define however I was getting an empty String back from the call to String.fromEnvironment.

```
flutter run --dart-define=APP_ENV=staging
```
The dart code I used to read the environment variable was;
```dart
var env = String.fromEnvironment("APP_ENV");
  print('env=$env'));
```
This printed out:
```
env=
```
After a lot of experiments I found the problem was in my use of 'var'.

If I changed the code to:
```dart
const env = String.fromEnvironment("APP_ENV");
  print('env=$env'));
```
Note the use of const instead of var.

The code then correctly printed out the value of APP_ENV.

So when I run:

```dart

void main() async {
  const constEnv = String.fromEnvironment("APP_ENV");
  print('constEnv=$constEnv');

  var varEnv = String.fromEnvironment("APP_ENV");
  print('varEnv=$varEnv');

  String stringEnv = String.fromEnvironment("APP_ENV");
  print('stringEnv=$stringEnv');
```

The output is:
```
I/flutter (16722): constEnv=staging
I/flutter (16722): varEnv=
I/flutter (16722): stringEnv=
```
I would expect all three lines to output 'staging'

Flutter doctor:

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.17.3 at /home/bsutton/apps/flutter
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/bsutton/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/bsutton/Android/Sdk
    • ANDROID_SDK_ROOT = /home/bsutton/Android/Sdk
    • Java binary at: /home/bsutton/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/bsutton/apps/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by jonahwilliams** [comment] 2020-06-09 23:15
Duplicate of https://github.com/flutter/flutter/issues/55870

**Closed by jonahwilliams** 2020-06-09 23:15 UTC
