### ISSUE TITLE
Firebase Admob - banner ad overlaps the drawer menu

### ISSUE THREAD

**Issue by riftninja** [flutter/flutter#17075] opened 2018-04-28 12:20 UTC
Drawer Opened             |  Drawer Closed
:-------------------------:|:-------------------------:
![screenshot_20180428-131121](https://user-images.githubusercontent.com/23476626/39396451-556da036-4ae6-11e8-9b89-ad63b6b1e2a0.png)  |  ![screenshot_20180428-131113](https://user-images.githubusercontent.com/23476626/39396455-5da5965a-4ae6-11e8-9e3d-2bc7e6f8e6ca.png)

**Comment by zoechi** [comment] 2018-07-27 07:07
Similar to #14222

**Comment by mulderpf** [comment] 2018-12-02 07:59
This didn't seem to be a major issue when the banner is placed at the bottom, but to accommodate the iPhone X, I have been experimenting with putting the banner at the top of the page.  When I then open the drawer, the banner is in the way.  I'm fairly sure this is not acceptable according to policy.

![image](https://user-images.githubusercontent.com/13488242/49337237-270af180-f608-11e8-8cb7-cddd36f89a35.png)

**Comment by zoechi** [comment] 2018-12-11 09:09
Duplicate of #14222

**Closed by zoechi** 2018-12-11 09:09 UTC
Labels: p: firebase, p: first party, plugin

**Comment by kroikie** [comment] 2019-10-13 19:12
@riftninja

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/842. Any further collaboration will be done there.

**Comment by Dabhipb** [comment] 2020-10-23 11:18
Any updates?
