### ISSUE TITLE
Pull to refresh in official example is not work

### ISSUE THREAD

**Issue by onewkl** [flutter/flutter#32614] opened 2019-05-13 10:13 UTC
My flutter sdk version is 1.5.4-hotfix.2. When I view flutter_gallery example,I found that the pull to refresh is not work on my android device, but it works well on ios simulator.Is it a bug?
![image](https://user-images.githubusercontent.com/39547225/57613956-ba2e5700-75aa-11e9-8630-00315b3db3e5.png)

**Comment by KirolousNashaat** [comment] 2019-05-13 13:04
it doesnt work unless u enable cupertino platform mechanics
duplicate of https://github.com/flutter/flutter/issues/31709

**Comment by shihaohong** [comment] 2019-05-13 22:07
This seems to have been fixed on the `master` branch with https://github.com/flutter/flutter/pull/30129/, with an explanation as to why this used to not work with Android. I will close this out, but feel free to re-open if there is an alternate issue!

**Closed by shihaohong** 2019-05-13 22:07 UTC
Labels: f: material design, framework, team: gallery
