### ISSUE TITLE
Can't wrap widget list with new widget assist by Alt+Enter

### ISSUE THREAD

**Issue by covid202** [flutter/flutter#62708] opened 2020-08-01 01:05 UTC
<img width="875" alt="AE20FED2-9201-46AE-8635-BB796C3D3543" src="https://user-images.githubusercontent.com/69062755/89090381-3f1db000-d3ab-11ea-8d6d-0731fc76fd7a.png">

Hello 
I am facing a issue on my android studio 
I can’t see the bulb unless i press right click and click on context action and my main problem than there is only 1 option available, same as in the picture 

I uninstalled everything from android studio to dart then install the latest dev sdk
Even i tried this 

The solution is go to android studio tab->preferences->intention->check quick assits powered by dart....(same as the attachment)

Still facing the same prob I can’t see the wrap options , please HELP !

**Comment by TahaTesser** [comment] 2020-08-03 09:15
Hi @covid202 
I cannot reproduce this issue on Flutter `48.0.2` plugin in Android Studio 

<img width="434" alt="Screenshot 2020-08-03 at 2 43 48 PM 1" src="https://user-images.githubusercontent.com/48603081/89166549-d7788800-d597-11ea-87e2-7c0fc1d03205.png">

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

 
[✓] Connected device (4 available)            
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6
      19G73
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.105

• No issues found!

```

</details> 

Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-03 09:15 UTC
