### ISSUE TITLE
[tool_crash] FileSystemException:  Directory listing failed, OS Error: Access is denied. errno = 5

### ISSUE THREAD

**Issue by usama-devloper** [flutter/flutter#120778] opened 2023-02-15 10:19 UTC
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

FileSystemException: FileSystemException: Directory listing failed, path = 'C:\Documents and Settings\*' (OS Error: Access is denied.
, errno = 5)

```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:953:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:792:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:697:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#8      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:502:26)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:287:41)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19045.2546], locale en-IN)
    • Flutter version 3.0.5 at C:\UMA_learning\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\3DBPI\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.1
    • Java binary at: C:\Program Files\Java\jdk-19\bin\java
    • Java version Java(TM) SE Runtime Environment (build 19.0.1+10-21)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32516.85
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.1)
    • VS Code at C:\Users\3DBPI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2546]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.78

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment] 2023-02-15 11:09
Hi @usama-devloper, kindly provide the file in `C:\UMA_learning\Projects\SharingInfo\sinfo_data\flutter_02.log`

Please also provide the output of `flutter doctor -v`

Thank you

**Comment by usama-devloper** [comment] 2023-02-16 05:51
> 

[flutter_02.log](https://github.com/flutter/flutter/files/10752591/flutter_02.log)

**Comment by usama-devloper** [comment] 2023-02-16 05:51
> Hi @usama-devloper, kindly provide the contents of the file in `C:\UMA_learning\Projects\SharingInfo\sinfo_data\flutter_02.log`
> 
> Please also provide the output of `flutter doctor -v`
> 
> Thank you

[flutter_02.log](https://github.com/flutter/flutter/files/10752593/flutter_02.log)

**Comment by danagbemava-nc** [comment] 2023-02-16 06:24
Closing this as a duplicate of https://github.com/flutter/flutter/issues/115642. 

Kindly subscribe to the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2023-02-16 06:24 UTC
Labels: in triage
