### ISSUE TITLE
[Conductor] version not being calculated correctly on start

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#111558] opened 2022-09-14 14:55 UTC
When releasing flutter 3.3.2, version was miscalculated as 3.3.0.  

Investigate why version is being calculated incorrectly.

**Comment by itsjustkevin** [comment] 2022-09-14 15:00
`release_type` key is set to `STABLE_INITIAL`

Logs: 
```
{
  "releaseChannel": "stable",
  "releaseVersion": "3.3.0",
  "engine": {
    "candidateBranch": "flutter-3.2-candidate.5",
    "startingGitHead": "2edab2e42b6b4460890859858c16a6cfb8d21d52",
    "currentGitHead": "2edab2e42b6b4460890859858c16a6cfb8d21d52",
    "checkoutPath": "/Users/kevinjchisholm/release/flutter_conductor_checkouts/engine",
    "upstream": {
      "name": "upstream",
      "url": "git@github.com:flutter/engine.git"
    },
    "mirror": {
      "name": "mirror",
      "url": "git@github.com:itsjustkevin/engine.git"
    },
    "dartRevision": "c42a304ce78f37b717cc055abc503023871a7013",
    "workingBranch": "cherrypicks-flutter-3.2-candidate.5"
  },
  "framework": {
    "candidateBranch": "flutter-3.2-candidate.5",
    "startingGitHead": "e331e3da38a626474ed3d56117c58ae640984eb1",
    "currentGitHead": "e331e3da38a626474ed3d56117c58ae640984eb1",
    "checkoutPath": "/Users/kevinjchisholm/release/flutter_conductor_checkouts/framework",
    "upstream": {
      "name": "upstream",
      "url": "git@github.com:flutter/flutter.git"
    },
    "mirror": {
      "name": "mirror",
      "url": "git@github.com:itsjustkevin/flutter.git"
    },
    "workingBranch": "cherrypicks-flutter-3.2-candidate.5"
  },
  "createdDate": "1663114099318",
  "lastUpdatedDate": "1663114099318",
  "logs": [
    "[trace] Deleting engine from /Users/kevinjchisholm/release/flutter_conductor_checkouts/engine...",
    "[trace] Cloning engine from git@github.com:flutter/engine.git to /Users/kevinjchisholm/release/flutter_conductor_checkouts/engine...",
    "[trace] Repository engine is checked out at revision \"769c84579ac0a13f97c7eeb28b3a62e616544ed6\".",
    "[trace] Deleting framework from /Users/kevinjchisholm/release/flutter_conductor_checkouts/framework...",
    "[trace] Cloning framework from git@github.com:flutter/flutter.git to /Users/kevinjchisholm/release/flutter_conductor_checkouts/framework...",
    "[trace] Repository framework is checked out at revision \"e331e3da38a626474ed3d56117c58ae640984eb1\".",
    "[error] Parsed version 3.3.1-null.null.pre.2 has a different y value than candidate branch flutter-3.2-candidate.5",
    "[error] Tried to tag the branch point, however the target version is 3.3.0, which does not have n == 0!",
    "[trace] Writing state to file /Users/kevinjchisholm/.flutter_conductor_state.json...",
    "[status] All engine cherrypicks have been auto-applied by the conductor.\n",
    "[write] Are you ready to push your engine branch to the repository git@github.com:itsjustkevin/engine.git? (y/n) ",
    "[status] Executed command: `git push mirror HEAD:refs/heads/cherrypicks-flutter-3.2-candidate.5`",
    "[status] \nUpdating phase from APPLY_ENGINE_CHERRYPICKS to CODESIGN_ENGINE_BINARIES...\n",
    "[status] Your working branch cherrypicks-flutter-3.2-candidate.5 was pushed to your mirror.\nYou must now open a pull request at https://github.com/flutter/engine/compare/flutter-3.2-candidate.5...itsjustkevin:cherrypicks-flutter-3.2-candidate.5?expand=1&title=%5Bflutter_releases%5D+Flutter+stable+3.3.0+Engine+Cherrypicks&body=%23+Flutter+stable+3.3.0+Engine%0A%0A%23%23+Scheduled+Cherrypicks%0A%0A-+Roll+dart+revision%3A+dart-lang%2Fsdk%40c42a304ce%0A, verify pre-submit CI\nbuilds on your engine pull request are successful, merge your pull request,\nvalidate post-submit CI, and then codesign the binaries on the merge commit.",
    "[status] You must validate pre-submit CI for your engine PR, merge it, and codesign\nbinaries before proceeding.\n",
    "[write] Has CI passed for the engine PR and binaries been codesigned? (y/n) ",
    "[status] \nUpdating phase from CODESIGN_ENGINE_BINARIES to APPLY_FRAMEWORK_CHERRYPICKS...\n",
    "[status] Either all cherrypicks have been auto-applied or there were none."
  ],
  "currentPhase": "APPLY_FRAMEWORK_CHERRYPICKS",
  "conductorVersion": "",
  "releaseType": "STABLE_INITIAL"
}%
```

**Comment by itsjustkevin** [comment] 2022-09-19 17:51
cc: @godofredoc @CaseyHillers

**Comment by CaseyHillers** [comment] 2022-09-29 13:28
I believe the issue is that https://github.com/flutter/flutter/releases/tag/3.3.0-0.0.pre isn't on the branch point at https://github.com/flutter/flutter/commit/08457a3d7ef81cec0662bce6f6ed6db37b6d9b8c. This is something that was fixed on the roll scripts recently.

We could manually tag `3.3.0-5.0.pre` to https://github.com/flutter/flutter/commit/08457a3d7ef81cec0662bce6f6ed6db37b6d9b8c to get conductor to correctly calculate the version

**Comment by CaseyHillers** [comment] 2022-09-29 13:28
I believe the issue is that https://github.com/flutter/flutter/releases/tag/3.3.0-0.0.pre isn't on the branch point at https://github.com/flutter/flutter/commit/08457a3d7ef81cec0662bce6f6ed6db37b6d9b8c. This is something that was fixed on the roll scripts recently.

We could manually tag `3.3.0-5.0.pre` to https://github.com/flutter/flutter/commit/08457a3d7ef81cec0662bce6f6ed6db37b6d9b8c to get conductor to correctly calculate the version

**Comment by CaseyHillers** [comment] 2023-01-03 14:41
Marking as fixed as the roll script fix should work for us. Once we get to the next Y rev on stable, we won't see this issue anymore.

**Closed by CaseyHillers** 2023-01-03 14:41 UTC
Labels: d: conductor, team: release
