### ISSUE TITLE
local auth problem with face id in xiaomi poco F3

### ISSUE THREAD

**Issue by zohreh-jamali** [flutter/flutter#102032] opened 2022-04-17 06:18 UTC
I got faced to "PlatformException(NotEnrolled, No biometrics enrolled on this device., null, null)"  error . only the face id is enable on device setting and the list of available biometrics is only contain BiometricType.fingerprint .
P.S. : No fingerprint defined at all.

**Comment by darshankawar** [comment] 2022-04-18 08:41
Closing this as duplicate of https://github.com/flutter/flutter/issues/45497

**Closed by darshankawar** 2022-04-18 08:41 UTC
Labels: in triage
