### ISSUE TITLE
Firebase storage : downloadURL with ascii characters

### ISSUE THREAD

**Issue by shriharip** [flutter/flutter#43263] opened 2019-10-22 12:33 UTC
Flutter doctor 
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

  **firebase_storage: ^3.0.6**

StorageRules is open 
```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write;
    }
  }
}

```
Problem: 
I am saving the URL internally by setting the https://firebasestorage.googleapis.com/v0/b/ + app name + metadata.path 

which results in 
 https://firebasestorage.googleapis.com/v0/b/app-v2.appspot.com/o/images/Nz92o9x9ys3p2YvRo5Px/0.png?alt=media&token=ad1894f3-9f12-49ce-8261-cd303456aca3

However, the getDownloadurl returns me 

https://firebasestorage.googleapis.com/v0/b/minlandsby-v2.appspot.com/o/images%2FNz92o9x9ys3p2YvRo5Px%2F0.png?alt=media&token=ad1894f3-9f12-49ce-8261-cd303456aca3

_After 'images' I use a forward slash but the getdownloadurl returns hex character._

This causes a  NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 400,

If I directly paste the URLs in the browser it is the same behavior.
the one returned from the getdownloadURL loads fine but the one I am generating is not.

Having a slash is creating a problem!!

Also, StorageMetaData.path returns with a slash and not hex characters

Thanks

**Comment by iapicca** [comment] 2019-10-23 09:41
Hi @shriharip 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2019-10-23 09:41 UTC

**Comment by shriharip** [comment] 2019-10-23 10:44
> Hi @shriharip
> for what I can see the issue is related to a FlutterFire plugin,
> please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
> Closing, as this isn't an issue with Flutter itself,
> if you disagree please write in the comments and I will reopen it
> Thank you

I agree, but from the github link on flutterfire, I was directed here :). But now I have raised this issue on that repo.
