### ISSUE TITLE
iOS Device - Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1024/7El8EVb7r60=/ws

### ISSUE THREAD

**Issue by c0h1b4** [flutter/flutter#32651] opened 2019-05-13 21:38 UTC
## Steps to Reproduce

1. Create a new flutter project with the command "flutter create myproject
2. Enter myproject directory "cd myproject"
3. Run VS Code "code ."
4. Start debugging on my iPhone device, pressing F5
5. White screen on iPhone, and this error on the debug console:

Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1024/kzLI1UZIOJQ=/ws

I read all the issues here (duplicates and non duplicates) and all the solutions are worthless for my case.

What I have tried:

1. Disconnect/Reconnect the device (iPhone) - no difference, still issue
2. Export "export no_proxy=localhost,127.0.0.0/8,::1" and all the other variances - no difference, still issue
3. iTunes "Sync with this iPhone over Wi-Fi" UNSET - no difference, still issue
4. XCode Devices - "Connect via network"UNSET - no difference, still issue
5. Turn Wifi to OFF on device - no difference, still issue
6. Turn Tether to OFF on device - no difference, still issue
7. Tested on different USB ports - no difference, still issue
8. Reboot computer/device - no difference, still issue
9. Replaced the device (got an iPad) - no difference, still issue
10. Switched channel DEV to MASTER - no difference, still issue
11. Switched channel MASTER to STABLE - no difference, still issue
12. Switched channel STABLE to BETA - no difference, still issue

So, I am running out of ideas. I need to have iOS device access on development because I am developing an app that uses camera to take photos and qr-code reader. It is very frustrating to have this kind of issues on a such great tool. From what I saw in the web, this is a MAJOR BREAKING issue that happens on some people but not to others. I hope the Flutter team fixes this on the next version.

On IOS Simulator, it works perfectly.
On Android Simulator, it works perfectly.
On Android Device, it works perfectly.

## Logs

debug console:

Launching lib/main.dart on iPhone Mauro in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: ..."
Xcode build done.                                            3.5s
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1024/kzLI1UZIOJQ=/ws
Exited (sigterm) 

```
```

flutter doctor -v
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-BR)
    • Flutter version 1.5.8 at /Users/mauro/development/flutter
    • Framework revision 0ba67226ee (3 weeks ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mauro/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mauro/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mauro/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0.beta.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • iPhone Mauro • e1216cebac409d83bc8d37bde15f8af53564c933 • ios • iOS 12.3

• No issues found!

```
```

**Comment by c0h1b4** [comment] 2019-05-14 10:05
Just to note: This issue wasn't happening a few months ago, then it started to happen randomly and now it is a constant, making it impossible to debug on an iOS device.

**Comment by c0h1b4** [comment] 2019-05-14 10:47
Some more info:

When I run from command line "flutter run", I get this error:

Error connecting to the service protocol: HttpException: , uri =
http://127.0.0.1:1024/DnwOPTSB0MQ=/ws

And the app is running on the device - I can see the main screen.

When I run from VS Code - F5 or ctrl-F5, I get a white screen with the same error: 

Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/bLcFaTaqJBQ=/ws

Before, when I didn't had this error permanently, just randomly, I saw that the port number was auto-incrementing (1023, 1024, 1025, ...) to find a port that wasn't blocked or being used. I believe that this can be solved changing the port number, but I don't have any idea or skills to reprogram a port change on flutter.

**Comment by c0h1b4** [comment] 2019-05-14 10:51
On android studio, the app launches but I have this on the Console:

Launching lib/main.dart on iPhone Mauro in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3F9J2TRCP3
Running Xcode build...
Xcode build done.                                            7.0s
Installing and launching...
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/vac7B3cmyMo=/ws

**Comment by c0h1b4** [comment] 2019-05-14 17:05
Finally got it to work.

Steps I made:

1. Get in terminal
2. Command: "lsof -nP -i4TCP:1024"
This command will return:
`COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mobiledev 18230 mauro    7u  IPv4 0xbea54bcdd5cea723      0t0  TCP 127.0.0.1:1024 (LISTEN)`
3. Kill the mobiledev with the ommand "kill 18230" (the number PID from the process)
4. Hit the F5/Ctrl-F5 or Start Debugging/Start Without Debuggin on VS Code or Android Studio
5. You have it working with hot reload and DevTools working perfectly.

The real issue is that I have to find the PID and kill it everytime I stop the app.

**Comment by c0h1b4** [comment] 2019-05-14 17:27
Here is a short command that finds the PID and kills the process using the port 1024:

`lsof -n -i4TCP:1024 | grep LISTEN | awk '{ print $2 }' | xargs kill`

**Comment by pjo336** [comment] 2019-05-15 15:16
I had this running Q. Changing to Pie helped

**Comment by c0h1b4** [comment] 2019-05-15 15:53
I am using iPhone.

**Comment by c0h1b4** [comment] 2019-05-25 10:39
I was opened 12 days ago and no review from the Flutter team. 

What is the strategy here, wait and let it die by itself?

**Comment by knissophiliac** [comment] 2019-05-31 22:48
I'm getting the same error. I'm completely not sure, but can it be related with CocoaPods version? Mine is also 1.7.0

**Comment by Rehan164** [comment] 2019-06-05 06:05
The same problem but how do you use your iPhone. Because my android sim is not working.

**Comment by c0h1b4** [comment] 2019-06-05 10:05
@knissophiliac Usually, killing the process that is using the 1024 port with the line from my previous comment, it works. If not I disconnect/reconnect the iPhone and keep killing the port (if it is being used) and then it works.
I also found out that if I have another device (android) connected to the dev machine, it will not work until I disconnect the other device.

**Comment by knissophiliac** [comment] 2019-06-09 20:23
@c0h1b4 I change my CocaPods version to 1.5.0. I'm getting this error rarely. If I get it, I unplug my device and replug it. That's a temporary solution but it works for me :)

**Comment by c0h1b4** [comment] 2019-06-18 10:56
Not working for me :( And no help from Flutter team.

**Comment by c0h1b4** [comment] 2019-06-25 10:11
Still waiting for some help of the Flutter team.

**Comment by DanTup** [comment] 2019-06-25 11:46
@c0h1b4 am I understanding this correctly?

- The first time you run everything is fine
- After you stop the debug session, it leaves a process (`mobiledev`) hanging around
- Subsequent runs will fail with the error above
- Terminating the `mobiledev` process fixes things (back to the start, where you can run once, but then you see the issue again)?

If so, does this repro from the command line (with WiFi debugging disabled)? If so, could you capture a full verbose log (using `flutter run -v`) for the sample flutter app (created with `flutter create`) and paste it into a Gist and paste the link here?

If it doesn't happen at the terminal (only VS Code) and you have IntelliJ or Android Studio available, could you see if the issue reproduces there?

**Comment by c0h1b4** [comment] 2019-06-25 12:52
> @c0h1b4 am I understanding this correctly?
> 
> * The first time you run everything is fine
> * After you stop the debug session, it leaves a process (`mobiledev`) hanging around
> * Subsequent runs will fail with the error above
> * Terminating the `mobiledev` process fixes things (back to the start, where you can run once, but then you see the issue again)?
> 
> If so, does this repro from the command line (with WiFi debugging disabled)? If so, could you capture a full verbose log (using `flutter run -v`) for the sample flutter app (created with `flutter create`) and paste it into a Gist and paste the link here?
> 
> If it doesn't happen at the terminal (only VS Code) and you have IntelliJ or Android Studio available, could you see if the issue reproduces there?

Let me clear the questions:

1. No, the first time I run the app on iOS, it launches the app and halts on the splash screen, after waiting a little, the HttpException appears. Then I need to unplug the device/kill the mobiledev process;
If I check the 1024 port before running the app, I can see that no process is using it, with a clean answer from lsof -n -i4TCP:1024. After running, I see the following:

lsof -n -i4TCP:1024
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
dart      39063 mauro    8u  IPv4 0x4099351af82f3a65      0t0  TCP 127.0.0.1:61924->127.0.0.1:1024 (ESTABLISHED)
dart      39063 mauro   24u  IPv4 0x4099351afe10a465      0t0  TCP 127.0.0.1:61930->127.0.0.1:1024 (ESTABLISHED)
mobiledev 39817 mauro    7u  IPv4 0x4099351aff101465      0t0  TCP 127.0.0.1:1024 (LISTEN)
mobiledev 39817 mauro    8u  IPv4 0x4099351b13c52de5      0t0  TCP 127.0.0.1:1024->127.0.0.1:61924 (ESTABLISHED)
mobiledev 39817 mauro   17u  IPv4 0x4099351b026d6a65      0t0  TCP 127.0.0.1:1024->127.0.0.1:61930 (ESTABLISHED)
 and the app is halted on the splash screen and VS Code is stuck on "Syncing files to device iPhone ..."
Then I press the STOP button on VS Code that stops the process that is waiting, but if I run lsof to check the ports I can see that a single process is still stuck.

lsof -n -i4TCP:1024
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mobiledev 39817 mauro    7u  IPv4 0x4099351aff101465      0t0  TCP 127.0.0.1:1024 (LISTEN)

Now, I need to stop the app on the iOS device (iPhone) to exit the splash screen, and kill the process that is blocking 1024 port, unplug/plug de iOS device and run again (F5). Now everything works, hot reload, devTools, restart (shift-cmd-F5). BUT, if I stop the app (shift-F5 or stop button), after the app stops on the device and shows on the VS Code that it is stopped I see that mobiledev is still holding the port:
lsof -n -i4TCP:1024
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mobiledev 47765 mauro    7u  IPv4 0x4099351b00bbfde5      0t0  TCP 127.0.0.1:1024 (LISTEN)

If I try run again, I get the "Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1024/is-7bqXvKkI=/ws" error with the splash screen frozen.
Fix, I need to kill the process that is stucking the port/unplug&plug the device and press F5 again.

The only way to run without unplugging/plugging the device is to kill the process before running the app.

Also, if there is any other device (Android) connected to the computer, it will never work, al

2. Yes, exactly, So if I need to start a new debug session I need to kill the mobiledev 
3. Yes, if I don't kil the mobiledev, I get the error.
4. Yes, it fixes IF I don't try to run the app with the process using the 1024 port. If I run with the process running, I need to kill the process and unplug/plug the device.

WiFi debug is disabled.

Gist with the port 1024 being used by mobiledev: https://gist.github.com/c0h1b4/684a678e411a56ae20208f80a4a26930
that shows the error

Gist with the mobiledev process killed before running:
https://gist.github.com/c0h1b4/ea8faf74c5a844a3380d294d4348a640
with no error and everything works ok!

On Android Studio I was having the same issues, but today to check your questions, I just saw that I don't have this issue after I stop the app. So it looks like the issue is only with the VS Code.

I will do a test after rebooting the computer to see if the issue appears on Android Studio on the first run and post here in a few minutes.

Also, here is my flutter doctor -v:

[✓] Flutter (Channel dev, v1.7.9, on Mac OS X 10.14.5 18F132, locale en-BR)
    • Flutter version 1.7.9 at /Users/mauro/development/flutter
    • Framework revision 8dbfc82bc7 (26 hours ago), 2019-06-24 11:41:02 +0100
    • Engine revision 4444c9cb6c
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mauro/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mauro/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mauro/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (3 available)
    • iPhone Mauro • e1216cebac409d83bc8d37bde15f8af53564c933 • ios            • iOS 12.3.2
    • macOS        • macOS                                    • darwin-x64     • Mac OS X 10.14.5 18F132
    • web          • web                                      • web-javascript • Google Chrome 75.0.3770.100


• No issues found!

**Comment by c0h1b4** [comment] 2019-06-25 12:57
Just checked on Android Studio after reboot and with 2 Android devices connected and the issue is gone on Android Studio. It seems to be isolated to VS Code and terminal 'flutter run' only, by now.

**Comment by c0h1b4** [comment] 2019-06-25 13:00
Just stopped the app on Android Studio, quit Android Studio, checked the 1024 port (it is clean), started VS Code and run the app:

Stuck on splash screen.

Launching lib/main.dart on iPhone Mauro in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3F9J2TRCP3
Xcode build done.                                            5.9s
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/pg7WezLBzlc=/ws
Exited (sigterm)

lsof -n -i4TCP:1024

COMMAND    PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mobiledev 2974 mauro    7u  IPv4 0x759c0207e61031bb      0t0  TCP 127.0.0.1:1024 (LISTEN)

**Comment by DanTup** [comment] 2019-06-25 13:02
Thanks for the info - I was thinking that VS Code might be terminating Flutter in a way that it's not cleaning up properly, but that doesn't explain why it wouldn't work the very first time or why it happens from the terminal.

I don't have an iPhone unfortunately to test here (and if I understand correctly, it only happens with a physical iOS device?). I'm curious about the mobiledev process - do you know where that's from? Is it part of our one Flutter's dependencies or part of the iOS toolchain (I can't find anything online)?

**Comment by DanTup** [comment] 2019-06-25 13:04
Can you get a tree of process that includes `mobiledev`? (For ex. does it show in the tree when running `code --status`). Also, when you open VS Code does the `mobiledev` process show up before you press F5 to run, or only once you try running?

**Comment by c0h1b4** [comment] 2019-06-25 14:18
Ok, I got your advice and followed the white rabbit on "mobiledev".
This is where it comes from:
https://github.com/imkira/mobiledevice

It looks like it is installed by homebrew on the Mac.

I will try uninstalling it and check if Flutter still works.

And the mobiledev process does not show up before F5.

**Comment by c0h1b4** [comment] 2019-06-25 15:19
Ok, after uninstalling mobiledevice, flutter stopped to work. So it is an essential part of it. 
I reinstalled and it got back to the same issues.
So after checking again on Android Studio and VS Code, I confirmed that on Android Studio, all the mobiledev processes are killed and on VS Code, one is left:

before stop (vs code):
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Code\x20H  6991 mauro   61u  IPv4 0xf443635abe1ddffd      0t0  TCP 127.0.0.1:50279->127.0.0.1:1024 (ESTABLISHED)
dart      10072 mauro    8u  IPv4 0xf443635aa804367d      0t0  TCP 127.0.0.1:50272->127.0.0.1:1024 (ESTABLISHED)
dart      10072 mauro   11u  IPv4 0xf443635aacff4ffd      0t0  TCP 127.0.0.1:50304->127.0.0.1:1024 (ESTABLISHED)
mobiledev 10528 mauro    7u  IPv4 0xf443635aab6199fd      0t0  TCP 127.0.0.1:1024 (LISTEN)
mobiledev 10528 mauro    8u  IPv4 0xf443635abdb8037d      0t0  TCP 127.0.0.1:1024->127.0.0.1:50272 (ESTABLISHED)
mobiledev 10528 mauro   11u  IPv4 0xf443635abdeadffd      0t0  TCP 127.0.0.1:1024->127.0.0.1:50304 (ESTABLISHED)
mobiledev 10528 mauro   23u  IPv4 0xf443635aa5aad37d      0t0  TCP 127.0.0.1:1024->127.0.0.1:50279 (ESTABLISHED)

after stop (vs code):

COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mobiledev 10528 mauro    7u  IPv4 0xf443635aab6199fd      0t0  TCP 127.0.0.1:1024 (LISTEN)

So I believe that the cleanup after stopping on VS Code must be missing something.

**Comment by DanTup** [comment] 2019-06-26 08:15
@c0h1b4 thanks, this helps! Could you capture a verbose log from VS Code?

- Run the **Dart: Capture Logs** command
- Tick just the Debugger/Observartory and Flutter Run categories
- Run your project (with F5)
- Click Stop
- Wait until the debug toolbar has disappeared, then a further few seconds
- Click **Stop Logging** on the logging notification (which has probably collapsed into the bell icon in the status bar by now)
- Paste the log into a Gist

When logs are being captured, it'll run Flutter in verbose mode (same as `-v` from the terminal), and the Observatory logging will include the termination signals VS Code is sending when trying to shut down (and whether it aggressively terminated the process for not responding correctly).

If you can repro this from the terminal, the same log running `flutter run -v` will be useful too (since then it might be easily debuggable by someone else - who has an iOS device available!).

**Comment by c0h1b4** [comment] 2019-06-26 14:55
@DanTup 
Here are the log gists:

Running the project with F5:
https://gist.github.com/c0h1b4/44ebd97c1d031a7cfb470467ffdbd7d0

Running the project from terminal:
https://gist.github.com/c0h1b4/c0759274aa895999c97e438a2422f4df

On both actions, I get the mobiledev process stuck on port 1024 after stopping the app.
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mobiledev 88414 mauro    9u  IPv4 0xd8824c81cb8e5ca7      0t0  TCP 127.0.0.1:1024 (LISTEN)

PS: I killed the 1024 port process before running.

**Comment by DanTup** [comment] 2019-07-10 08:10
@c0h1b4 thanks! There's something a little weird in those logs - looks like we tell the app to stop twice, and the first one doesn't get a response. I don't know if that's contributing to the issue, but it feels wrong. I can repro that locally so I'll have a go at fixing and then you can test if it makes any difference.

**Comment by DanTup** [comment] 2019-07-10 09:24
@c0h1b4 could you see if this build makes any difference?

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.3.0-alpha.2

Download the `.vsix` file somewhere, then run **Extensions: Install from VSIX** from the VS Code command palette and browse to that file, then click the Reload button.

We were previously sending `app.stop` multiple times and then also assuming that when the Observatory connection closed, Flutter had quit (but it hasn't, which resulted in us then also sending a `SIGINT` too). Now we should only send one, and we'll wait for the app to quit (up to 3 seconds) before sending any `SIGINT`s.

Be aware that clicking the Stop button a second time during shutdown will perform a `SIGTERM` which could definitely leave processes around, that's somewhat unavoidable (VS Code only gives us two chances to stop.. one cleanly, one aggressively).

**Comment by antoninobajeli** [comment] 2019-07-13 16:07
I'm facing the same problem.

This is my flutter doctor

/Users/antoninobajeli/Documents/FlutterSDK/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale it-IT)
    • Flutter version 1.5.4-hotfix.2 at /Users/antoninobajeli/Documents/FlutterSDK/flutter
    • Framework revision 7a4c33425d (3 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/antoninobajeli/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/antoninobajeli/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.1 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.0.2
    • Dart plugin version 172.4343.25

[✓] Connected device (2 available)
    • TA 1021                   • PLEGAR17A1802749                         • android-arm64 • Android 9 (API 28)
    • iPhone di Antonino Bajeli • 1dc32573e1ee148d13ae7c8cee583152725b9185 • ios           • iOS 12.3.1

• No issues found!

**Comment by DanTup** [comment] 2019-07-22 17:25
@antoninobajeli I posted a build of the VS Code extension above with some tweaks but haven't had any feedback. There's a newer version at https://github.com/Dart-Code/Dart-Code/releases/tag/v3.3.0-beta.2 now. I'm still interested to hear if it improves things for anyone (or even if it makes things worse).

**Comment by c0h1b4** [comment] 2019-07-23 00:17
Hello. On the latest version the issue is solved!
I have no issues about it now.

**Comment by DanTup** [comment] 2019-07-23 07:18
@c0h1b4 excellent! Thanks for confirming. I'll close this, but if anyone comes here with similar issues - please try the latest v3.3 build from https://github.com/Dart-Code/Dart-Code/releases and if you still see issues, open a new issue with a log attached.

**Closed by DanTup** 2019-07-23 07:18 UTC

**Comment by ride4sun** [comment] 2020-03-19 00:39
@DanTup I see the problem in the beta channel. How can I switch just Dart to version 3.3?
