### ISSUE TITLE
Allow NavigationBar's backgroundColor to extend behind system navigation

### ISSUE THREAD

**Issue by martinpichler** [flutter/flutter#121883] opened 2023-03-03 17:18 UTC
The Material 3 NavigationBar uses SafeArea which leads to issues with background colors. 

Tested with sample app from Flutter documentation (unchanged)
flutter create --sample=material.NavigationBar.1 mysample

As you can see in the screenshot the area below the NavigationBar is not the same color as the NavigationBar itself and there is no way to change it. 

Screenshot was taken on real device, problem also persist on emulator.

![Screenshot_20230303_181345](https://user-images.githubusercontent.com/21956176/222785417-e3e311f0-1814-41c6-95bc-8e77397e07ac.jpg)

**Comment by exaby73** [comment] 2023-03-06 08:25
`BottomNavigationBar` does not use `SafeArea`, but rather `MediaQueryData.viewPaddingOf(context).bottom` and sets a padding. This looks like it's intended, but this may be a proposal to consider. 

cc: @TahaTesser for more insights

**Comment by TahaTesser** [comment] 2023-03-06 08:45
Hey @martinpichler 
This can be observed without a navigation bar. Duplicate of https://github.com/flutter/flutter/issues/119465

**Closed by TahaTesser** 2023-03-06 08:45 UTC
Labels: new feature, framework, f: material design, proposal

**Comment by TahaTesser** [comment] 2023-03-06 09:35
Try this code sample with a transparent status bar from https://github.com/flutter/flutter/issues/119465

| Preview | 
| --------------- | 
| <img src="https://user-images.githubusercontent.com/48603081/223072002-332ec2ef-a35d-44fb-8bcc-5ad3154cc621.png" height="450" />	|



<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const NavigationBarApp());

class NavigationBarApp extends StatelessWidget {
  const NavigationBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: NavigationExample());
  }
}

class NavigationExample extends StatefulWidget {
  const NavigationExample({super.key});

  @override
  State<NavigationExample> createState() => _NavigationExampleState();
}

class _NavigationExampleState extends State<NavigationExample> {
  int currentPageIndex = 0;

  @override
  Widget build(BuildContext context) {
// SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
// SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
//   statusBarBrightness: Brightness.light,
//   statusBarIconBrightness: Brightness.dark,
//   statusBarColor: Colors.transparent,
//   systemNavigationBarColor: Colors.transparent,
// ));

    return Scaffold(
      bottomNavigationBar: NavigationBar(
        onDestinationSelected: (int index) {
          setState(() {
            currentPageIndex = index;
          });
        },
        selectedIndex: currentPageIndex,
        destinations: const <Widget>[
          NavigationDestination(
            icon: Icon(Icons.explore),
            label: 'Explore',
          ),
          NavigationDestination(
            icon: Icon(Icons.commute),
            label: 'Commute',
          ),
          NavigationDestination(
            selectedIcon: Icon(Icons.bookmark),
            icon: Icon(Icons.bookmark_border),
            label: 'Saved',
          ),
        ],
      ),
      body: <Widget>[
        Container(
          color: Colors.red,
          alignment: Alignment.center,
          child: const Text('Page 1'),
        ),
        Container(
          color: Colors.green,
          alignment: Alignment.center,
          child: const Text('Page 2'),
        ),
        Container(
          color: Colors.blue,
          alignment: Alignment.center,
          child: const Text('Page 3'),
        ),
      ][currentPageIndex],
    );
  }
}

``` 
	
</details>
