### ISSUE TITLE
Feature request: implement retrying all builds for a commit in build dashboard

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#75709] opened 2021-02-09 16:25 UTC
Every column is purple. Is there a trick to re-run every column?

https://ci.chromium.org/p/flutter/g/engine/console

/cc @liyuqian

**Comment by zanderso** [comment] 2021-02-09 17:32
Looks like @iskakaushik landed a PR to kick the tree, but I'll leave this open in case there is any infra issue to investigate. It would still probably be good to get builds on the commit where this happened if they can be easily triggered en masse.

**Comment by godofredoc** [comment] 2021-02-09 17:32
We may want to start discussing if we want to use the flutter-dashboard for all the flutter repositories. Implementing this functionality there will allow us to reuse and also will remove the restriction of having a small group of people with permissions to retry the builds.

I see that there is a new commit and the builds are passing, moving this bug to P1 while I investigate what happen in the purple row.

**Comment by godofredoc** [comment] 2021-02-09 17:40
All the failures happened on 02/08/2021 at ~3:50PM. There was a LUCI buildbucket outage between 2:54PM and 4:07PM caused by a roll of a new version of buildbucket and was fixed by rolling back at 4:07PM. 


```
[I 2021-02-08 23:57:06] using kitchen properties:
{
  "git_auth": true,
  "devshell": false,
  "emulate_gce": true,
  "docker_auth": true,
  "firebase_auth": false
}
panic: Impossible unmarshaling error

goroutine 1 [running]:
main.(*cookRun).syncResultDBInfo(0xc00000c1e0, 0xe350a0, 0xc000041480, 0x0, 0x0)
	/tmp/_chrome_infra_build/infra/go/src/infra/tools/kitchen/cook.go:981 +0xa0d
main.(*cookRun).run(0xc00000c1e0, 0xe350a0, 0xc000041480, 0xc000122dd0, 0x0, 0x3, 0xc0003022d0, 0x0, 0x0)
	/tmp/_chrome_infra_build/infra/go/src/infra/tools/kitchen/cook.go:428 +0x9ff
main.(*cookRun).Run(0xc00000c1e0, 0xe38f40, 0x1375c60, 0xc000122dd0, 0x0, 0x3, 0xc0004adbc0, 0xc000036b30)
	/tmp/_chrome_infra_build/infra/go/src/infra/tools/kitchen/cook.go:344 +0x1ba
github.com/maruel/subcommands.Run(0xe38f40, 0x1375c60, 0xc000122a90, 0x34, 0x37, 0x0)
	/tmp/_chrome_infra_build/infra/go/.vendor/src/github.com/maruel/subcommands/subcommands.go:373 +0x4d4
main.main()
	/tmp/_chrome_infra_build/infra/go/src/infra/tools/kitchen/kitchen.go:53 +0x145
 ```

**Comment by godofredoc** [comment] 2021-02-09 17:41
Keeping this bug open for the feature request of adding functionality to retry an entire commit.

**Comment by godofredoc** [comment] 2021-02-18 23:10
This functionality should retry all the failed builds only to not waste resources.

**Comment by godofredoc** [comment] 2022-11-16 19:57
\cc @nehalvpatel this one requires both changes in the backend and frontend of cocoon

**Comment by godofredoc** [comment] 2023-05-30 22:54
@XilaiZhang I believe you implemented this functionality am I correct?

**Comment by XilaiZhang** [comment] 2023-05-30 23:07
Casey completed this recently. yeah the command is documented in [the infra playbook](https://g3doc.corp.google.com/company/teams/flutter/infrastructure/playbook.md?cl=head#rerun-all-failed-tasks-for-a-commit)

**Closed by XilaiZhang** 2023-05-30 23:07 UTC
Labels: team, passed first triage, team: infra, passed secondary triage, P3
