### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Accès refusé., errno = 5

### ISSUE THREAD

**Issue by froug** [flutter/flutter#88868] opened 2021-08-25 10:47 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile E:\firstaapp\loginapp\flutter_firstapp\build\app\intermediates\flutter\debug/flutter_build.d --output E:\firstaapp\loginapp\flutter_firstapp\build\app\intermediates\flutter\debug -dTargetFile=E:\firstaapp\loginapp\flutter_firstapp\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Accès refusé.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#6      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:731:33)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:619:5)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [version 10.0.19043.1165], locale fr-TN)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (3 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\gouad\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: E:\androidstudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at E:\androidstudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\gouad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • SM A715F (mobile) • RZ8NA1BSC3E • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 92.0.902.67

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 02c026b03cd31dd3f867e5faeb7e104cce174c5f
### Plugins
sqflite-2.0.0+3

**Comment by darshankawar** [comment] 2021-08-25 11:03
Closing this as duplicate of https://github.com/flutter/flutter/issues/69116

**Closed by darshankawar** 2021-08-25 11:03 UTC
Labels: in triage
