### ISSUE TITLE
[Impeller] Failure on image load in a background worker thread

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123027] opened 2023-03-20 16:53 UTC
See failures on b/274227975

Error message is:
```
[VERBOSE-3:image_decoder_impeller.cc(329)] Check failed: context. No valid impeller context
```

Backtrace is:
```
Thread 17 Crashed:: io.worker.2
0   libsystem_kernel.dylib        	    0x7fff6bf9f00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7fff6bff61ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7fff2010771e __abort + 139
3   libsystem_c.dylib             	    0x7fff20107693 abort + 138
4   Flutter                       	       0x10db1ca95 fml::KillProcess() + 9
5   Flutter                       	       0x10db1ca8c fml::LogMessage::~LogMessage() + 274
6   Flutter                       	       0x10dd0e88d std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<flutter::DlImage>)> const&)::$_1, std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<flutter::DlImage>)> const&)::$_1>, void ()>::operator()() + 111
7   Flutter                       	       0x10db1ad86 fml::ConcurrentMessageLoop::WorkerMain() + 450
8   Flutter                       	       0x10db1b477 void* std::_LIBCPP_ABI_NAMESPACE::__thread_proxy[abi:v15000]<std::_LIBCPP_ABI_NAMESPACE::tuple<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<std::_LIBCPP_ABI_NAMESPACE::__thread_struct, std::_LIBCPP_ABI_NAMESPACE::default_delete<std::_LIBCPP_ABI_NAMESPACE::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) + 191
9   libsystem_pthread.dylib       	    0x7fff6bff64e1 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7fff6bff1f6b thread_start + 15
```

**Comment by jonahwilliams** [comment] 2023-03-20 17:17
From reading the code, we probably need to handle the case in image decoding when there is no GPU. either by erroring out or creating an image implementation that deferrs uploading of texture data until the GPU is available again.

That said, we may also start hitting issues where the lack of software rendering starts to be a problem

**Comment by chinmaygarde** [comment] 2023-03-20 18:50
The crash is definitely a bug. Looking at the Skia implemnetation, it looks like we create a raster image and Skia performs the upload once the graphics context is re-acquired. We can do the same. I though we just failed to decompress the image though. We could do that in the interim to avoid the crash.

**Comment by chinmaygarde** [comment] 2023-03-20 18:51
Duplicate of https://github.com/flutter/flutter/issues/118195. But, I'm closing that earlier bug instead of since this has an xref to the internal bug.

**Closed** 2023-04-03 19:49 UTC
Labels: engine, waiting for PR to land (fixed), P2, impeller
