### ISSUE TITLE
[go_router] URL doesn't refresh when pushing/popping to different route

### ISSUE THREAD

**Issue by zigapovhe** [flutter/flutter#129893] opened 2023-07-02 21:18 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use any go_router version which is 8.0.0 or higher
3. Copy code sample from below
4. Run web app
5. Check initial url (should be '/test1')
6. Click on "Go to TestScreen2" button
7. Check url (should be '/test2' but is still '/test1')

Works as expected on GoRouter v7.1.1 or below

### Expected results

URL should change when pushing to new route

### Actual results

URL does not change

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final _router = GoRouter(
    initialLocation: "/test1",
    routes: [
      GoRoute(
        name: "TestScreen1",
        path: "/test1",
        builder: (context, state) => const TestScreen1(),
      ),
      GoRoute(
        name: "TestScreen2",
        path: "/test2",
        builder: (context, state) => const TestScreen2(), 
      ),
    ],
  );

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Test',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routerConfig: _router,
    );
  }
}

class TestScreen1 extends StatelessWidget {
  const TestScreen1({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: ElevatedButton(
              onPressed: () {
                GoRouter.of(context).push("/test2");
              },
              child: const Text("Go to TestScreen2"))),
    );
  }
}

class TestScreen2 extends StatelessWidget {
  const TestScreen2({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: ElevatedButton(
              onPressed: () {
                GoRouter.of(context).pop();
              },
              child: const Text("Back to TestScreen1"))),
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
<img width="1333" alt="Screenshot 2023-07-02 at 23 08 57" src="https://github.com/flutter/flutter/assets/21365070/7495e754-2877-4419-9d9b-e91bdb2b3837">
<img width="1338" alt="Screenshot 2023-07-02 at 23 09 03" src="https://github.com/flutter/flutter/assets/21365070/6f98907f-3803-448e-b00d-6f9bd2dcfc37">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-SI)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-07-03 09:56
Hi @zigapovhe 
There is a breaking change since [v8.0.0](https://pub.dev/packages/go_router/changelog#800):

>Imperatively pushed GoRoute no longer change URL.
Browser backward and forward button respects imperative route operations

You can check the migration guide at [Migrating to 8.0.0](https://flutter.dev/go/go-router-v8-breaking-changes). In short, you should use `GoRouter.optionURLReflectsImperativeAPIs = true;`.

Closing this issue since it's changed as intended.

**Closed by huycozy** 2023-07-03 09:56 UTC
Labels: in triage
