### ISSUE TITLE
Flutter Hot Reload is broken on Android Studio 3.1 and above

### ISSUE THREAD

**Issue by wilburt** [flutter/flutter#16881] opened 2018-04-23 11:52 UTC
I updated to Android Studio 3.1.1 recently and since then I started minor issues with Flutter **Hot Reload** but restarting Android Studio appears to fix it temporarily. However, about a couple of days ago, **Hot Reload** stopped working entirely. For example, this is my terminal output: 

    gap@xop:~/Flutter/Projects/fibo$ flutter run
    Launching lib/main.dart on HTC 10 in debug mode...
    Initializing gradle...                                       1.0s
    Resolving dependencies...                                   11.0s
    Running 'gradlew assembleDebug'...                           2.8s
    Built build/app/outputs/apk/debug/app-debug.apk (31.9MB).
    Installing build/app/outputs/apk/app.apk...                  7.8s

It just ends there, the usual information about using `r` or `R` for hot reload or full rebuild is no longer there. Also, I don't see the logs for the app in Logcat but I can see all logs if I select **No Filters**.

**What I have done:**

 1. Upgraded to Android Studio 3.2 Canary 11
 2. Switched Flutter to master and subsequently ran `git pull`, `flutter upgrade` and `flutter doctor`
 3. Restarted Android Studio
 4. Did full system restart.

**Android Studio Info:**

    Android Studio 3.2 Canary 11
    Build #AI-181.3007.14.32.4720098, built on April 13, 2018
    JRE: 1.8.0_152-release-1136-b01 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Linux 4.13.0-38-generic

**Flutter info:**

    Flutter 0.3.3-pre.13 • channel master • https://github.com/flutter/flutter.git
    Framework • revision fd7222eea8 (11 hours ago) • 2018-04-23 02:03:46 +0100
    Engine • revision cb3376c5de
    Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

**System Info:**

Ubuntu 17.04

Please, is there any fix for this?

**Comment by GauravSharma531** [comment] 2018-05-06 08:05
I am also facing this issue on my mac book pro.

System Information 
System Version:	macOS 10.13.4 (17E202)
  Kernel Version:	Darwin 17.5.0
  Boot Volume:	Macintosh HD

Android Studio Information
Android Studio 3.1.2
Build #AI-173.4720617, built on April 14, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4

Flutter Information 
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E202, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.22.2)
[✓] Connected devices (2 available)

Is it android studio issue or flutter plugin please fix it.

**Comment by dai875939260** [comment] 2018-05-12 21:52
I am also facing this issue on my mac book pro.

hot load button is always disabled in android studio or idea, vs code will get error like this when click hot load button
> NoSuchMethodError: The getter 'isClosed' was called on null.
Receiver: null
Tried calling: isClosed

Flutter Information
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] VS Code (version 1.23.1)

**Comment by jftrujillo** [comment] 2018-06-07 20:34
Same issue here. I'm working on windows and hot reload is not working. Hot restart is always necessary.

**Comment by jftrujillo** [comment] 2018-06-14 21:21
I resolve the problem reinstalling the flutter complement. Now It's working without any problem.

**Comment by zoechi** [comment] 2018-06-15 08:58
Is this still an issue with recent Flutter versions?

**Comment by Nikki1993** [comment] 2018-06-28 09:06
Flutter 0.5.1 beta fresh install on Arch, Hot Reload is grayed out in Android Studio.

**Comment by zoechi** [comment] 2018-06-28 09:08
@Nikki1993 
Please add the output of `flutter doctor`

**Comment by Nikki1993** [comment] 2018-06-28 19:55
@zoechi 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] Android Studio (version 3.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by ariaenggar** [comment] 2018-07-03 05:54
@zoechi 

I tried running new flutter app to my device LG K350 (LG K8 2016, Android Marshmallow), the hot reload didn't working, the hot reload button at Android studio disabled.

I tried running the app to my friend's device, Xiaomi Redmi S3 (Android Marshmallow), the hot reload worked, at the console showed text "Syncing files to device Redmi 3S..." (didn't showed up on my LG)

Here's the result of flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
[√] Connected devices (1 available)

Hope that helps,
Best Regards.

**Comment by zoechi** [comment] 2018-07-03 06:10
@devoncarew any idea what can cause the hot-reload button being disabled?

**Comment by Nikki1993** [comment] 2018-07-06 14:55
I got hot reload to work on VSCode after the recent update to flutter, however Android Studio Hot Reload option remains grayed out.

**Comment by rodzun** [comment] 2018-07-20 03:22
I had the same issue. Resolved just unistalling the flutter plugin, restarting Android Studio, and then reinstalling the plugin and restarting Android Studio again. Hope it helps.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.137], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!
```

**Comment by jt100xu** [comment] 2018-07-25 07:51
Just run on an emulator -> it works fine -> and then try to run on an Android/iOS devices -> cheers 👯‍♂️

**Comment by faraz-ahmad** [comment] 2018-08-03 05:30
I am facing the following issue while installing build on Android device. 

"Error waiting for a debug connection: ProcessException: adb did not report forwarded port"

Although build is installed but not able to do hot reload.

**Comment by XQDD** [comment] 2018-08-13 07:49
Try to update adb version
https://developer.android.com/studio/releases/platform-tools

**Comment by eduardobcastro** [comment] 2018-09-06 03:51
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.7.6-pre.57, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

• No issues found!

$ flutter --version

Flutter 0.7.6-pre.57 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2c1d12d4f7 (3 hours ago) • 2018-09-05 18:03:43 -0700
Engine • revision de4c7a53f2
Tools • Dart 2.1.0-dev.3.0.flutter-760a9690c2
```

- Android Studio hot reload disabled
- Device shows blank screen when debugging in VScode (F5)
- Nothing happens when pressing **r** key when running with `flutter run`

**Comment by zoechi** [comment] 2018-09-06 06:04
@eduardobcastro are you seeing this since a Flutter update?

**Comment by eduardobcastro** [comment] 2018-09-06 15:51
@zoechi No. This is a fresh installation.

**Comment by vamsiaila** [comment] 2018-09-17 19:15
i am facing same issue i am using vs code editor and my android device it is building up the app and opening in my device but it automatically quits unable to hot reload i am using ubuntu 16.04

**Comment by zoechi** [comment] 2018-09-19 15:06
@eduardobcastro do you still see this with Flutter master channel?
@vamsiaila please post the output of `flutter doctor -v`

**Comment by eduardobcastro** [comment] 2018-09-19 15:17
In my case it was an issue with adb. 
https://github.com/flutter/flutter/issues/18757

**Comment by hairypalm** [comment] 2018-09-26 16:19
I face the same issue on Ubuntu 18.04.  I am evaluating Flutter, followed instructions at https://flutter.io/setup-linux/ and found that the first Test Drive app (https://flutter.io/get-started/test-drive/) did not allow hot-reload.  Hot reload is greyed out.  Otherwise, everything worked as described in the tutorial.  Project is compiled and runs on attached device fine, just no hot reload.

Completely fresh install of Flutter and Android Studio.

**Comment by miyoyo** [comment] 2018-09-26 16:30
I wonder if it's device specific, I think it's a frequent problem in LG devices, could any future posters post their devices/brand as well?

**Comment by hairypalm** [comment] 2018-09-26 17:08
> I wonder if it's device specific, I think it's a frequent problem in LG devices, could any future posters post their devices/brand as well?

It turns out that I am using an LG G5.  Just trying under Windows, and seems to be the same outcome.  No hot reload.

**Comment by agierus** [comment] 2018-09-26 17:43
I just confirmed that on both Windows and Ubuntu, my LG G5 under Android Studio has flutter hot reload greyed out and inoperable.  However, under both OSs, the emulator allows flutter hot reload and this works as expected.

**Comment by hairypalm** [comment] 2018-09-26 17:47
I just confirmed that on both Windows and Ubuntu, my LG G5 under Android Studio has flutter hot reload greyed out and inoperable. However, under both OSs, the emulator allows flutter hot reload and this works as expected.

**Comment by MarcinusX** [comment] 2018-10-09 04:29
Having the same issue with my LG G6 and OSX. Didn't have it before on Ubuntu 18.04.

**Comment by goderbauer** [comment] 2018-10-16 14:59
What versions of Flutter are you all running (output of `flutter doctor -v`)? Do you still see the issue on the latest beta or on master?

The issue may have been fixed with https://github.com/flutter/flutter/pull/21977.

**Comment by MarcinusX** [comment] 2018-10-17 03:46
New version fixed it for me. Hot reload works like it should. :)
```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale pl-PL)
    • Flutter version 0.9.4 at /Users/mszalek/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/mszalek/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Users/mszalek/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 29.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (2 available)
    • LG H870       • LGH870b78bb781                       • android-arm64 • Android 8.0.0 (API 26)
    • iPhone 8 Plus • 7A25BD92-3B70-46F1-A652-B8FAE4E6BDC5 • ios           • iOS 12.0 (simulator)
```

**Comment by goderbauer** [comment] 2018-10-17 07:41
With the report that this seems to be working again I am closing the issue. Feel free to re-open it with more information if you continue to have problems on the latest Flutter version.

**Closed by goderbauer** 2018-10-17 07:41 UTC
Labels: t: hot reload, tool, waiting for customer response

**Comment by BarbaricGamester** [comment] 2018-12-01 11:15
I'm getting the same problem on a fresh installation of Ubuntu 18.10 (Android Studio), worked fine on Windows 10. The outputs stops at `Built build/app/outputs/apk/debug/app-debug.apk`. Error is also on IntelliJ Idea. This is the 5th or 6th time, this has happened but previously it used to happen on Windows 10, but it would automatically start working after a few commands like `flutter clean`, `flutter upgrade` and also reinstalling the plugin. This is starting to get annoying.

**Comment by zoechi** [comment] 2018-12-01 13:33
@BarbaricGamester if you use a proxy https://github.com/flutter/flutter/issues/16875#issuecomment-384758566 might help.

**Comment by BarbaricGamester** [comment] 2018-12-01 18:52
@zoechi I tried but it didn't work, I don't recall installing or using any sort of proxy didn't work.

**Comment by zoechi** [comment] 2018-12-03 06:03
Please add the output of `flutter doctor -v`.

**Comment by BarbaricGamester** [comment] 2018-12-04 18:49
I fixed it by installing an Android Studio emulator and running the app in
it, and then restarting the app in my mobile device.

**Comment by lichao2018** [comment] 2018-12-11 06:06
it crashed in Android 4.4 .but reload is enabled in my device Android 5.0.1.

**Comment by zoechi** [comment] 2018-12-11 06:16
This issue is closed since a while. If you are still seeing this, please create a new issue with a properly filled issue template.

**Comment by nderituKelvin** [comment] 2019-02-06 18:20
For anyone else who may be looking for the right answer, Check the `/test/widget_test.dart` file, you may have edited you file in the `lib/main.dart` and changed `MyApp()` to something else

**Comment by shashanthk** [comment] 2019-08-16 06:04
If you're opening Android Studio (flutter project) for the first time after installing Flutter and Dart plugins, just restart the Android Studio by clicking on **File - > Invalidate Cache and Restart -> Just Restart**

This should work even after creating fresh Flutter project with Android Studio.

Tested with Android Studio 3.4.2, Flutter SDK v1.7.8+hotfix.4, Flutter plugin v38.2.1

**Comment by aseem-hegshetye** [comment] 2019-10-20 16:29
Above mentioned **Invalidate Cache and Restart** did not work for my on ubuntu 18 LTS , Andoid studio 3.5.1 , Android emulator. 
The app reloads successfully when I run (shift+f10)  it again though.

**Comment by afei1991** [comment] 2020-05-06 08:35
In my case ,I upgrade the sdk platform-tools to lastest.And it works.
