### ISSUE TITLE
Flutter web laggy in Iphone Pro models

### ISSUE THREAD

**Issue by Himanshu700296** [flutter/flutter#159709] opened 2024-12-03 04:38 UTC
### Steps to reproduce

You can use the link https://resturentmenu-f3fbd.web.app/ in web, android, or any iphone 14,15 and the scrolling behaviour is smooth, but in the pro models specifically iphone 15 pro, the list of items are getting lagging on scroll, one more thing is if i use two fingers to scroll in pro model then there is no issue in scrolling

### Expected results

The scrolling when done in pro model will be laggy with one finger but will be smooth with two

### Actual results

the scrolling should be smooth same as android and other iphone

### Code sample

<details open><summary>Code sample</summary>

```

import 'package:animated_text_kit/animated_text_kit.dart';
import 'package:flutter/material.dart';
import 'package:resturent_menu/Utils/listOfProducts.dart';
import 'package:web_smooth_scroll/web_smooth_scroll.dart';

Map<String, List<Map<String, String>>> orginalList = {};
List filterList = [];

class MenuPage extends StatefulWidget {
  @override
  _MenuPageState createState() => _MenuPageState();
}

class _MenuPageState extends State<MenuPage> {
  final ScrollController _scrollController = ScrollController();
  final TextEditingController _searchController = TextEditingController();
  FocusNode focusNode = FocusNode();
  bool isSearch = false;
  String currentSelected = "";
  String currentFilter = "";

  Map<String, List<Map<String, String>>> categories = Map.from(orginalList);

  // Sample categories and items

  // To store the GlobalKeys for categories
  final Map<String, GlobalKey> _categoryKeys = {};

  late Map<String, List<Map<String, String>>> filteredCategories;

  @override
  void initState() {
    super.initState();
    // Initialize filtered categories to include all categories
    listCreation();
  }

  void listCreation() {
    filteredCategories = Map.from(categories);

    // Initialize GlobalKeys for each category
    categories.keys.forEach((category) {
      _categoryKeys[category] = GlobalKey();
    });

    // Add listener to update filtered categories on search
    _searchController.addListener(() {
      final query = _searchController.text.toLowerCase();
      setState(() {
        if (query.isEmpty) {
          filteredCategories = Map.from(categories);
        } else {
          filteredCategories = {
            for (var entry in categories.entries)
              entry.key: entry.value
                  .where((item) => item["name"]!.toLowerCase().contains(query))
                  .toList()
          }..removeWhere((key, value) => value.isEmpty);
        }
      });
    });
  }

  void _showMenuDialog(List<String> categories) {
    showDialog(
      context: context,
      builder: (context) {
        return Dialog(
          child: ListView(
            shrinkWrap: true,
            children: categories.map((category) {
              return ListTile(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(25),
                ),
                title: Column(
                  children: [
                    Padding(
                      padding: const EdgeInsets.only(top: 0, bottom: 0),
                      child: Text(
                        category,
                        style: TextStyle(
                            color: currentSelected == category
                                ? Colors.blue
                                : Colors.black,
                            fontWeight: currentSelected == category
                                ? FontWeight.w600
                                : FontWeight.w400),
                      ),
                    ),
                  ],
                ),
                onTap: () {
                  _scrollToCategory(category);
                  setState(() {
                    currentSelected = category;
                  });
                  Navigator.pop(context);
                },
              );
            }).toList(),
          ),
        );
      },
    );
  }

  void _scrollToCategory(String category) async {
    final keyContext = _categoryKeys[category]?.currentContext;
    if (keyContext != null) {
      // Add a small delay before scrolling to allow layout processing
      await Future.delayed(Duration(milliseconds: 50));
      Scrollable.ensureVisible(
        keyContext,
        duration: Duration(milliseconds: 500),
        curve: Curves.easeInOut,
      );
    }
  }

  void filterAccordingToFilter(String filter) {
    // If the filter is empty, reset categories to originalList
    if (filter.isEmpty) {
      setState(() {
        categories = Map.from(orginalList);
      });
      listCreation();
      return;
    }

    // Perform filtering if the filter is not empty
    Map<String, List<Map<String, String>>> newMap = {};
    for (var item in categories.keys) {
      for (var v in categories[item]!) {
        if (v.containsKey(filter)) {
          if (newMap[item] == null) {
            newMap[item] = [v];
          } else {
            newMap[item]!.add(v);
          }
        }
      }
    }

    setState(() {
      categories = newMap;
    });

    listCreation();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Color(0xFFfef7ff),
        surfaceTintColor: Color(0xFFfef7ff),
        toolbarHeight: 60,
        title: Align(
          alignment: Alignment.centerLeft, // Align the title to the left
          child: Column(
            crossAxisAlignment: CrossAxisAlignment
                .start, // Align text to the left inside the column
            children: [
              Text("Cafe Ko Meret"),
              Text(
                "Food that feels like heaven",
                style: TextStyle(fontSize: 12),
              ),
            ],
          ),
        ),
      ),
      body: Stack(
        alignment: Alignment.bottomRight,
        children: [
          Column(
            children: [
              // Search bar
              Padding(
                padding: const EdgeInsets.only(
                    left: 15, top: 8, bottom: 8, right: 15),
                child: GestureDetector(
                  onTap: () {
                    setState(() {
                      isSearch = true;
                      focusNode.requestFocus();
                    });
                  },
                  child: Container(
                    height: 50,
                    width: MediaQuery.sizeOf(context).width,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(width: 1),
                    ),
                    child: Row(
                      children: [
                        Container(
                          width: 50,
                          child: Icon(Icons.search),
                        ),
                        isSearch == false
                            ? Padding(
                                padding: const EdgeInsets.only(top: 0, left: 0),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: <Widget>[
                                    const Text(
                                      'Search for',
                                      style: TextStyle(fontSize: 14.0),
                                    ),
                                    const SizedBox(width: 5.0, height: 100.0),
                                    DefaultTextStyle(
                                      style: const TextStyle(
                                        fontSize: 14.0,
                                        fontFamily: 'Horizon',
                                      ),
                                      child: AnimatedTextKit(
                                        repeatForever: true,
                                        totalRepeatCount: 200,
                                        animatedTexts: [
                                          RotateAnimatedText('Burger'),
                                          RotateAnimatedText('Pizza'),
                                          RotateAnimatedText('Pasta'),
                                        ],
                                        onTap: () {
                                          setState(() {
                                            isSearch = true;
                                            focusNode.requestFocus();
                                          });
                                        },
                                      ),
                                    ),
                                  ],
                                ),
                              )
                            : Container(
                                width: MediaQuery.of(context).size.width * 0.78,
                                child: TextField(
                                  maxLines: 1,
                                  focusNode: focusNode,
                                  controller: _searchController,
                                  decoration: InputDecoration(
                                    border: InputBorder.none,
                                    hintText: "Search",
                                    hintMaxLines: 1,
                                    contentPadding: EdgeInsets.symmetric(
                                        vertical: 12.0,
                                        horizontal:
                                            0.0), // Adjust vertical padding
                                    suffixIcon:
                                        _searchController.text.isNotEmpty
                                            ? IconButton(
                                                icon: Icon(Icons.clear),
                                                onPressed: () {
                                                  _searchController.clear();
                                                },
                                              )
                                            : null,
                                  ),
                                ),
                              ),
                      ],
                    ),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(left: 10, bottom: 10),
                child: Container(
                  height: 45,
                  child: ListView.builder(
                    scrollDirection: Axis.horizontal,
                    itemCount: filterList.length, // Number of containers
                    itemBuilder: (context, index) {
                      return Padding(
                        padding: const EdgeInsets.only(
                            left: 6, right: 6, top: 6, bottom: 6),
                        child: GestureDetector(
                          onTap: () {
                            setState(() {
                              categories = Map.from(orginalList);
                              if (currentFilter ==
                                  filterList.elementAt(index)["key"]) {
                                currentFilter = ""; // Reset filter
                              } else {
                                currentFilter =
                                    filterList.elementAt(index)["key"];
                              }
                              filterAccordingToFilter(currentFilter);
                            });
                          },
                          child: Container(
                            padding: EdgeInsets.only(left: 15, right: 15),
                            decoration: BoxDecoration(
                              border: Border.all(
                                color: filterList.elementAt(index)["key"] ==
                                        currentFilter
                                    ? Colors.blue
                                    : Colors.white,
                              ),
                              boxShadow: [
                                BoxShadow(
                                  color: Colors.black.withOpacity(0.1),
                                  offset: Offset(0, 0),
                                  blurRadius: 10,
                                  spreadRadius: 2,
                                ),
                              ],
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: Center(
                              child: Row(
                                children: [
                                  Text(
                                    filterList.elementAt(index)["name"],
                                    style: TextStyle(
                                        color: Colors.black, fontSize: 14),
                                  ),
                                  SizedBox(
                                    width: 5,
                                  ),
                                  Container(
                                    height: 20,
                                    child: Image.asset(
                                      filterList.elementAt(index)["icon"],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      );
                    },
                  ),
                ),
              ),
              // ListView with categories
              Expanded(
                child: SingleChildScrollView(
                  controller: _scrollController,
                  child: Column(
                    children: [
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: filteredCategories.entries.map((entry) {
                          final category = entry.key;
                          final items = entry.value;

                          return KeyedSubtree(
                            key: _categoryKeys[
                                category]!, // Using GlobalKey for each category
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                // Category heading
                                Padding(
                                  padding:
                                      const EdgeInsets.only(left: 8, top: 8),
                                  child: Text(
                                    category,
                                    style: const TextStyle(
                                      fontSize: 20,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                                // Category items
                                ...items.map(
                                  (item) => MenuItem(item),
                                ),
                              ],
                            ),
                          );
                        }).toList(),
                      ),
                      SizedBox(
                        height: 100,
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
          GestureDetector(
            onTap: () {
              _showMenuDialog(categories.keys.toList());
            },
            child: Padding(
              padding: const EdgeInsets.only(bottom: 20, right: 10),
              child: Container(
                width: 120,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.menu,
                      color: Colors.white,
                    ),
                    SizedBox(width: 5),
                    Text(
                      "Menu",
                      style: TextStyle(color: Colors.white),
                    ),
                  ],
                ),
                height: 45,
                padding: const EdgeInsets.symmetric(horizontal: 15),
                decoration: BoxDecoration(
                  color: Colors.blue,
                  borderRadius: BorderRadius.circular(10),
                ),
              ),
            ),
          )
        ],
      ),
    );
  }

  @override
  void dispose() {
    _scrollController.dispose();
    _searchController.dispose();
    super.dispose();
  }
}

class MenuItem extends StatefulWidget {
  Map item;

  MenuItem(this.item);

  @override
  State<MenuItem> createState() => _MenuItemState();
}

class _MenuItemState extends State<MenuItem> {
  bool isExpanded = false; // To track if the full text is shown
  @override
  Widget build(BuildContext context) {
    String description = widget.item['description']!;
    String truncatedDescription =
        description.length > 100 ? description.substring(0, 100) : description;
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10),
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.1),
              offset: Offset(0, 0),
              blurRadius: 10,
              spreadRadius: 2,
            ),
          ],
        ),
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Row(
            children: [
              Container(
                height: 140,
                width: 140,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(
                      10), // Clip the child to match the container's border radius
                  child: InkWell(
                    borderRadius: BorderRadius.circular(
                        10), // Ensure the InkWell also respects the border radius
                    onTap: () {
                      // Handle tap
                    },
                    child: Image.network(
                      "https://static.vecteezy.com/system/resources/previews/023/809/530/non_2x/a-flying-burger-with-all-the-layers-ai-generative-free-photo.jpg",
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              SizedBox(
                width: 10,
              ),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        SizedBox(
                          height: 5,
                        ),
                        widget.item['bestSeller'] == null
                            ? SizedBox()
                            : Row(
                                children: [
                                  Container(
                                    height: 20,
                                    child: Image.asset("assets/bestSeller.png"),
                                  ),
                                  SizedBox(
                                    width: 5,
                                  ),
                                  Text(
                                    widget.item['bestSeller'] == null
                                        ? ""
                                        : "Best seller",
                                    style: TextStyle(
                                      fontSize: 13,
                                      color: Color(0xffFF7830),
                                    ),
                                  ),
                                ],
                              ),
                        SizedBox(
                          height: 5,
                        ),
                        Container(
                          child: Text(
                            widget.item['name']!,
                            style: TextStyle(
                                fontSize: 18, fontWeight: FontWeight.w600),
                          ),
                        ),
                        SizedBox(
                          height: 5,
                        ),
                        GestureDetector(
                          onTap: () {
                            setState(() {
                              isExpanded = !isExpanded; // Toggle text expansion
                            });
                          },
                          child: RichText(
                            text: TextSpan(
                              text: isExpanded
                                  ? description
                                  : truncatedDescription,
                              style: TextStyle(
                                fontSize: 12,
                                color: Colors.grey.shade700,
                              ),
                              children: [
                                if (description.length > 30)
                                  TextSpan(
                                    text: isExpanded
                                        ? " Read Less"
                                        : " Read More",
                                    style: TextStyle(
                                      fontSize: 12,
                                      color: Colors.blue,
                                    ),
                                  ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                    SizedBox(
                      height: 30,
                    ),
                    Align(
                      alignment: Alignment.bottomRight,
                      child: Text(
                        "Rs. ${widget.item['price']}",
                        style: TextStyle(
                            fontSize: 20, fontWeight: FontWeight.w700),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
[ScreenRecording_12-03-2024 10-04-12_1 (1).mp4.zip](https://github.com/user-attachments/files/17987407/ScreenRecording_12-03-2024.10-04-12_1.1.mp4.zip)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```

[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    ! iOS 18.0 Simulator not installed; this may be necessary for iOS and macOS development.
      To download and install the platform, open Xcode, select Xcode > Settings > Platforms,
      and click the GET button for the required platform.

      For more information, please visit:
        https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by darshankawar** [comment] 2024-12-03 12:31
@Himanshu700296 
In order to properly address the issue, please provide only minimal but complete reproducible code sample that shows the reported behavior. 

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by darshankawar** [comment] 2024-12-04 05:56
@Himanshu700296 
Looks like it is closely related / similar to https://github.com/flutter/flutter/issues/117714 that you can check along with underlying comments to see if it helps in your case or not.

**Comment by Himanshu700296** [comment] 2024-12-04 06:17
i have seen the solution there and tried but nothing changed, i know the problem is similar

i am using a iphone 15 pro with iOS 18.2 Beta 2 and i have turned of the.....“prefer page rendering updates near 60fps” feature flag.

but then also there is the same lagging in my device, it is working fine in any iphone without the pro version and even android

**Comment by darshankawar** [comment] 2024-12-04 06:39
I think it is a known issue for now, so I suggest you to follow-up in it for further reference. The linked issue is still open. You may share your findings in it for better tracking.
Closing this in favor of it.

**Closed by darshankawar** 2024-12-04 06:39 UTC
Labels: in triage

**Comment by Himanshu700296** [comment] 2024-12-04 06:40
sure....thanks for your response
