### ISSUE TITLE
HtmlElementView crash on resizing a Flutter Web app

### ISSUE THREAD

**Issue by URIBM016** [flutter/flutter#158546] opened 2024-11-13 01:24 UTC
### Steps to reproduce

**Pre-requisites**: 
[Web package](https://pub.dev/packages/web/versions) >=0.5.1 
Flutter SDK >=3.19.6 
environment:
  sdk: ^3.2.0

1. Ensure semantics on the semantics binding instance in the main function:

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  SemanticsBinding.instance.ensureSemantics();

  runApp(const MainApp());
}
```

2. Add a long paragraph inside a text widget, wrapped in a big padding. Short texts or small padding won't reproduce the crash. We have consistently reproduced this crash with a paragraph of two phrases from Loren Ipsum and a padding of 80px:

```dart
Padding(
  padding: EdgeInsets.all(80),
  child: Text(
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam volutpat venenatis orci, a rhoncus enim egestas sit amet.',
  ),
),
```

3. Add an `HtmlElementView` inside a `SizedBox` below the text (we have used a `ListView` to have both elements in a scrollable list), the `viewType` of the `HtmlElementView` can be anything; for this example we are using an `HTMLIFrameElement` with no content:

```dart
platformViewRegistry.registerViewFactory(
  _viewTypeId,
  (int viewId) => HTMLIFrameElement(),
);

// …

SizedBox(
  height: 200,
  child: HtmlElementView(viewType: _viewTypeId),
),
```

4. To reproduce the crash, compile the app to Chrome, and reduce the width of the window to a small width until the browser crashes. As stated before, when screens are more complex, the crash will be reproduced more easily, by resizing the window just a little, or just landing into a very complex screen containing at least all the 3 steps before. Please see included video for reference.

### Expected results

The app should resize without crashing

### Actual results

The app crashes if we resize the screen to a certain point. In our more complex projects, this happens quicker than with the simple app mentioned above.
The console prints the message

> Debugger: Target crashed!

NOTE: We were not able to reproduce the crash when using web: ^0.3.0 and Flutter SDK 3.16.9. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:ui_web';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';
import 'package:web/web.dart' hide Text;

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  if (kIsWeb) {
    SemanticsBinding.instance.ensureSemantics();
  }

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) => const MaterialApp(
        home: WebCrashPage(),
      );
}

class WebCrashPage extends StatelessWidget {
  const WebCrashPage({super.key});

  static const String _viewTypeId = 'some_view_type';

  @override
  Widget build(BuildContext context) {
    platformViewRegistry.registerViewFactory(
      _viewTypeId,
      (int viewId) => HTMLIFrameElement(),
    );

    return Scaffold(
      body: ListView(
        children: const <Widget>[
          Padding(
            padding: EdgeInsets.all(80),
            child: Text(
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam volutpat venenatis orci, a rhoncus enim egestas sit amet.',
            ),
          ),
          SizedBox(
            height: 200,
            child: HtmlElementView(viewType: _viewTypeId),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/b303bbe4-81de-4ecd-97c8-040ddb685a62

</details>

### Logs

<details open><summary>Logs</summary>

```console

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Resolving dependencies... 
  async 2.11.0 (2.12.0 available)
  boolean_selector 2.1.1 (2.1.2 available)
  characters 1.3.0 (1.3.1 available)
  clock 1.1.1 (1.1.2 available)
  collection 1.18.0 (1.19.1 available)
  fake_async 1.3.1 (1.3.2 available)
  flutter_lints 2.0.3 (5.0.0 available)
+ leak_tracker 10.0.0 (10.0.8 available)
+ leak_tracker_flutter_testing 2.0.1 (3.0.9 available)
+ leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (5.1.0 available)
> matcher 0.12.16+1 (was 0.12.16) (0.12.17 available)
> material_color_utilities 0.8.0 (was 0.5.0) (0.12.0 available)
> meta 1.11.0 (was 1.10.0) (1.16.0 available)
> path 1.9.0 (was 1.8.3) (1.9.1 available)
  stack_trace 1.11.1 (1.12.0 available)
  string_scanner 1.2.0 (1.4.0 available)
  test_api 0.6.1 (0.7.3 available)
+ vm_service 13.0.0 (14.3.1 available)
> web 0.5.1 (was 0.3.0) (1.1.0 available)
Changed 9 dependencies!
20 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             12.7s
This app is linked to the debug service: ws://127.0.0.1:62604/TZw8q1fpvHg=/ws
Debug service listening on ws://127.0.0.1:62604/TZw8q1fpvHg=/ws

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

A Dart VM Service on Chrome is available at: http://127.0.0.1:62604/TZw8q1fpvHg=
Height of Platform View type: [some_view_type] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [some_view_type] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9103?uri=http://127.0.0.1:62604/TZw8q1fpvHg=
Height of Platform View type: [some_view_type] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [some_view_type] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
Height of Platform View type: [some_view_type] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [some_view_type] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
Debugger: Target crashed!
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.19.6 on channel stable at /.../fvm/versions/3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (7 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /.../Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode_15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.16.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by ditman** [comment] 2024-11-13 02:38
https://github.com/pixijs/pixijs/discussions/7544 <- suspicious (?)

**Comment by kevmoo** [comment] 2024-12-06 21:34
The linked issues bottom out at https://g-issues.chromium.org/issues/335553723 – which was fixed in Chrome 125+

But we're saying this in Chrome 131 (and not Safari and Firefox). So this seems related, but a separate issue with chrome.

**Comment by kevmoo** [comment] 2024-12-10 23:41
Filed THIS issue to track the root cause in Chrome: https://g-issues.chromium.org/issues/383392741

**Comment by kevmoo** [comment] 2024-12-11 17:38
FYI: it seems this has been fixed in Chrome. I cannot replicate it in Chrome Canary v133.0.6889.0

**Closed by kevmoo** 2024-12-11 17:38 UTC
Labels: a: platform-views, platform-web, P2, blocked, c: fatal crash, browser: chrome-desktop, customer: castaway, team-web, triaged-web
