### ISSUE TITLE
[i10n] Make parameters named instead of positional

### ISSUE THREAD

**Issue by MatrixDev** [flutter/flutter#131773] opened 2023-08-02 14:25 UTC
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Consider following arb file:
```json
{
    "matchInfo_about": "{homeTeam} vs {awayTeam} started on {date} at {time} in {stadium} as part of {event}."
}
```
It generates this code in dart:
```dart
abstract class AppLocalizations {
    String matchInfo_about1(Object awayTeam, Object date, Object event, Object homeTeam, Object stadium, Object time);
}
```
There are few problems here. The first one is that there are many untyped arguments, easy to missplace them.

Secondly, order is different from what was provided in arb file. This is fine because order might be different in different languages but it makes reading it very unnatural:
```dart
AppLocalizations.of(context).matchInfo_about(
    "Chicago Fire", // order doesn't make sense, easy to missplace
    "2023/08/01",
    "Leagues Cup",
    "Puebla",
    "Soldier Field",
    "00:00:00",
);
```

### Proposal

Add additional property to `i10n.yaml` file:
```yaml
named-string-getters = true
```

It will change all arguments to be named:
```dart
abstract class AppLocalizations {
    String matchInfo_about1({Object awayTeam, Object date, Object event, Object homeTeam, Object stadium, Object time});
}
```
```dart
AppLocalizations.of(context).matchInfo_about(
    event = "Leagues Cup", // now order is logical and it is hard to missplace things
    homeTeam = "Puebla",
    awayTeam = "Chicago Fire",
    stadium = "Soldier Field",
    date = "2023/08/01",
    time = "00:00:00",
);
```

There can be multiple solution when for some reason named arguments have different name in different languages:
1. fallback to positional arguments for affected strings
2. throw an error during generation

**Comment by Piinks** [comment] 2023-10-26 16:38
Looking through internationalization issues this morning I came across this and found it is a duplicate of https://github.com/flutter/flutter/issues/116308
I am going to close this to refer back to that issue.

**Closed by Piinks** 2023-10-26 16:38 UTC
Labels: c: new feature, framework, a: internationalization, a: quality, c: proposal, P3, team-framework, triaged-framework
