### ISSUE TITLE
Custom refactor menu in VSCode

### ISSUE THREAD

**Issue by amreniouinnovent** [flutter/flutter#36803] opened 2019-07-24 05:07 UTC
## Use case
The refactor menu in VSCode has basic widgets.
I want to be able to wrap my widget in a BlocBuilder widget directly or any other widget other than the default widgets

## Proposal

I think there should a JSON format or similar way for adding more widgets to the refactor menu and asks for an **array** of parameters like bloc state class, bloc event class, etc.

![image](https://user-images.githubusercontent.com/52191652/61766607-777ecb80-adf2-11e9-9206-98149e0f320a.png)

**Comment by DanTup** [comment] 2019-07-24 07:37
Closing this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/1890, since it makes sense to discuss there since it's pretty VS Code specific.

**Closed by DanTup** 2019-07-24 07:37 UTC
