### ISSUE TITLE
Flutter build web version change problem.

### ISSUE THREAD

**Issue by CetinIpnordic** [flutter/flutter#98617] opened 2022-02-16 21:14 UTC
When I run this command:
**flutter build web --build-name=1.0.2 --build-number=2 --no-sound-null-safety**
I get this error :
Could not find an option named "build-name".
I also want to change the **version.json** file during the build.
Any ideas on how to do it?

**Comment by darshankawar** [comment] 2022-02-17 08:45
Closing this as a duplicate of https://github.com/flutter/flutter/issues/75909

**Closed by darshankawar** 2022-02-17 08:45 UTC
Labels: in triage
