### ISSUE TITLE
Not getting stacktrace from exceptions

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter#71172] opened 2020-11-24 20:29 UTC
I always get a full stacktrace when I get an exception which helps figure out where the error is coming from. But lately for some reason I stopped getting them. 

I'm currently getting this screen: 
![Screen Shot 2020-11-24 at 3 27 46 PM](https://user-images.githubusercontent.com/3067603/100147613-9c150880-2e69-11eb-9550-08bd9b5cc801.png)

With only this in the console output:
![Screen Shot 2020-11-24 at 3 27 30 PM](https://user-images.githubusercontent.com/3067603/100147586-93243700-2e69-11eb-9120-239c9f320315.png)

Which is not helpful at all. What's worse, if I search for 'isNotEmpty' on my code base, i can't find any, which is leading me to believe it's happening inside the flutter framework. Because of some mistake on my part I'm sure, but without the stacktrace I don't know where to look.

Any idea why this might be happening?

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.24.0-7.0.pre at /Users/jan/flutter
    • Framework revision a0860f6e87 (4 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jan/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)             • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 86.0.4240.198
    ! Error: iPhone de Jan Lubeck is not connected. Xcode will continue when iPhone de Jan Lubeck is connected. (code -13)

• No issues found!
```

</details>

**Comment by nt4f04uNd** [comment] 2020-11-24 22:00
Try enabling "pause on exception" feature in the debugger of your IDE

**Comment by jlubeck** [comment] 2020-11-24 22:12
@nt4f04uNd  Do you know where that is on Android Studio? Can't seem to find it...

**Comment by nt4f04uNd** [comment] 2020-11-24 22:14
@jlubeck https://stackoverflow.com/questions/24718958/android-studio-ide-break-on-exception

**Comment by jlubeck** [comment] 2020-11-24 22:21
Looks like I already had everything checked:

![Screen Shot 2020-11-24 at 5 21 22 PM](https://user-images.githubusercontent.com/3067603/100157981-7abc1880-2e79-11eb-89b2-f397ed3acaa2.png)

**Comment by nt4f04uNd** [comment] 2020-11-24 22:21
Switch to "Break on all exceptions"

**Comment by jlubeck** [comment] 2020-11-24 22:22
Aha!! Thanks!

**Comment by nt4f04uNd** [comment] 2020-11-24 22:25
Though it's still unclear, why the stacktrace didn't print

**Comment by jlubeck** [comment] 2020-11-24 22:28
Well, thanks to the break on all exceptions, it stopped here in one of my external dependencies:

```dart
    try {
      _doc = await widget.build(pageFormat);
    } catch (e) {
      error = e;
      return;
    }
```

So it was a caught exception. Should it be printing the stacktrace there? If it should, I'll reopen the issue

**Comment by nt4f04uNd** [comment] 2020-11-24 22:37
From the code you shown it's not obvious to me why the flutter would show an exception. AFAIK stack traces should be always printed, but I'm not sure, so better to reopen it for someone else to look at.

**Comment by Abhishek01039** [comment] 2020-11-25 05:24
Hello @jlubeck 
can you please try without a `try-catch` bloc to see the stack trace?
One variable is null by the way that's why this error is occur.
Thanks

**Comment by jlubeck** [comment] 2020-11-25 05:35
The problem is that part is not part of my code, it’s on an external dependency

**Comment by pedromassangocode** [comment] 2020-11-25 10:19
Hi @jlubeck 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by pedromassangocode** [comment] 2020-12-16 09:33
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-16 09:33 UTC
Labels: in triage, waiting for customer response
