### ISSUE TITLE
A problem occurred evaluating project ':app'. > ASCII

### ISSUE THREAD

**Issue by hrwndr** [flutter/flutter#42921] opened 2019-10-17 11:11 UTC
I am having this error after i tried to connect the project with firebase.

```
* Error running Gradle:
ProcessException: Process "D:\flutter\destinyapp\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\flutter\destinyapp\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
  Command: D:\flutter\destinyapp\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)
```

My App Level Gradle File:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.destinyapp"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-analytics:17.2.0'
}

apply plugin: 'com.google.gms.google-services'

```
Any help would be highly appreciated.

**Comment by BondarenkoStas** [comment] 2019-10-17 12:09
Duplicate of #41492. Please try https://github.com/flutter/flutter/issues/41492#issuecomment-536112970

**Closed by BondarenkoStas** 2019-10-17 12:09 UTC

**Comment by flutterq2** [comment] 2021-06-22 04:17
All possible working solution added [[Solved] Gradle failure A problem occurred evaluating project ‘:app’](https://fluttercorner.com/gradle-failure-a-problem-occurred-evaluating-project-app/)
