### ISSUE TITLE
use thirdparty softKeyboard height are wrong in ios

### ISSUE THREAD

**Issue by cryuhy** [flutter/flutter#141559] opened 2024-01-15 10:10 UTC
### Steps to reproduce

https://github.com/flutter/flutter/assets/10368258/f5efc425-4dd4-46a0-b679-41af7e3d589a

im use thirdPaty softKeyboard in web textfeild  softKeyboard Height was wrong,but system keyboard are correct

### Expected results

keyboard height should be correct

### Actual results

keyboard height is wrong

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.7, on macOS 14.0 23A344 darwin-arm64,
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.79.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for 李白的iPad. Ensure the
      device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly.
      (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly.
      (code -27)
[✓] Network resources

• No issues found!

**Comment by darshankawar** [comment] 2024-01-15 12:41
@cryuhy 
Are you seeing this on mobile browser running on iOS ?
If it is happening using third party soft keyboard, then you might need to file this issue in dedicated repo. Can you provide details of the keyboard you are using ?
Also, are you reporting the issue of the keyboard opening glitch ?

**Comment by darshankawar** [comment] 2024-01-16 05:34
@cryuhy 
Since the issue is occuring only using third party keyboard (iFlytek) and not using system or default virtual keyboard, I think the issue lies with the third party keyboard itself because not all third party packages or tools maybe compatible with Flutter's latest versions, so I suggest you to follow-up in third party keyboard's repo itself for further resolution.

Also, inappwebview is also third party package. Flutter's first party webview package is `webview_flutter`. If using it, you get same behavior, write in comments and I'll reopen it. Closing for now.

**Closed by darshankawar** 2024-01-16 05:34 UTC
Labels: in triage

**Comment by cryuhy** [comment] 2024-01-16 06:44
ok thanks
