### ISSUE TITLE
In flutter HTTP Client, an option is required to set the IPv4 or IPv6 for DNS resolution for the developer

### ISSUE THREAD

**Issue by SijuKJ** [flutter/flutter#116537] opened 2022-12-05 19:12 UTC
## Details

**Target Platform:** Android 
**Target OS version/browser:** Android 12+
**Devices:** 

Many Flutter-based Android and iOS apps are very slow during HTTP service calls in the Wifi networks due to failed IPv6 DNS resolution.
As I am requesting this feature as a solution for the three important issues reported by Flutter developers.

1. https://github.com/flutter/flutter/issues/116477
2. https://github.com/flutter/flutter/issues/112285
3. https://github.com/dart-lang/sdk/issues/41451

In essence, we are facing slowness in the API call execution while using Wifi networks due to failed IPv6 DNS resolution, thereafter it fallback to IPv4 DNS resolution. Hence each API call execution is getting delayed a minimum of 10+ seconds. 

It would be great If there would be a feature for manually specifying IPv4 or IPv6 versions during HTTP client initialization.

So I request your kind attention on this important issue, as we are developing business-critical applications using Flutter, for iOS/ Android, and Windows.

**Comment by SijuKJ** [comment] 2022-12-06 19:42
@exaby73 Thank you.  I will share the sample code and logs from the application.


## Steps to Reproduce



1. Use Android 12+ device
2. Use a WiFi connection having IPv6 & IPv4 enabled router
3. Execute `flutter run` on the code sample


<details>
<summary>Code sample</summary>


Dart code
```
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';

import 'package:http/http.dart' as http;


void main() async {
  runApp(const HttpSampleApp());
}

class HttpSampleApp extends StatelessWidget {
  const HttpSampleApp({super.key});

    @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'HttpSample App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MainUI(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class MainUI extends StatefulWidget {
  const MainUI({super.key});

  @override
  State<MainUI> createState() => _MainUIState();
}

class _MainUIState extends State<MainUI> {
  final String _serverURL = "https://smartcampus.co/api/Account/Authenticate";
  void _authenticate() async {
    Map<String, dynamic> userCredentails = new Map();

    userCredentails["UsernameOrEmailAddress"] = "demo";
    userCredentails["Password"] = "demo123";
    userCredentails["TenancyName"] = "test";

    _login(body: userCredentails);
  }

  Future<Map?> _login({required Map<String, dynamic> body}) async {
    debugPrint("Sevice call via Dart.io HttpClient >> ");

    HttpClient httpClient = HttpClient();
    final stopwatch = Stopwatch()..start();
    try {
      HttpClientRequest request = await httpClient.openUrl("POST", Uri.parse(_serverURL));
      request.headers.set(HttpHeaders.contentTypeHeader, "application/json; charset=UTF-8");

      request.write(json.encode(body));
      debugPrint(' Data access time => ${stopwatch.elapsed}');

      HttpClientResponse response = await request.close();
      final stringData = await response.transform(utf8.decoder).join();
      debugPrint(stringData);
    } on SocketException catch (e) {
      debugPrint("Socket Error $e");
    } on TimeoutException catch (e) {
      debugPrint("Timeout Exception Error $e");
    } on Error catch (e) {
      debugPrint('Error: $e');
    } finally {
      debugPrint("Http Client connection closed");
      httpClient.close();
    }

    debugPrint("Sevice call via Http Plugin >> ");
    try {
      final stopwatch1 = Stopwatch()..start();

      http.Response response = await http.post(Uri.parse(_serverURL),
          headers: {
            "Content-Type": "application/json", //"keep-alive": "true"
          },
          body: json.encode(body));

      debugPrint('Login time access => ${stopwatch1.elapsed}');

      debugPrint(response.body);

      final int statusCode = response.statusCode;

      if (statusCode < 200 || statusCode > 400 || json == null) {
        return null;
      }

      return json.decode(response.body);
      //});

    } on SocketException catch (e) {
      debugPrint("Socket Error $e");
    } on TimeoutException catch (e) {
      debugPrint("Timeout Exception Error $e");
    } on Error catch (e) {
      debugPrint('Error: $e');
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Http Client Sample"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              ElevatedButton(
                onPressed: () async {
                  _authenticate();
                },
                style: ElevatedButton.styleFrom(elevation: 12.0, textStyle: const TextStyle(color: Colors.white)),
                child: const Text('Authenticate'),
              ),
            ],
          ),
        ));
  }
}

```
Pubspec.yml

```
name: samplehttp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  

```

</details>

<details>
  <summary>Logs</summary>

  Logs from Android 11 with Wifi - Tooks only less than a second for the API call. I have used both `dart.io` based HttpClient and 
`http: ^0.13.5` plugin.


```
I/flutter (20245): Sevice call via Dart.io HttpClient >>
I/flutter (20245):  Data access time => 0:00:00.405276
I/flutter (20245): {"result":null,"targetUrl":null,"success":false,"error":{"code":0,"message":"Login failed!","details":"There is no tenant defined with name test","validationErrors":null},"unAuthorizedRequest":false,"__abp":true}
I/flutter (20245): Http Client connection closed
I/flutter (20245): Sevice call via Http Plugin >>
I/flutter (20245): Login time access => 0:00:00.468740
I/flutter (20245): {"result":null,"targetUrl":null,"success":false,"error":{"code":0,"message":"Login failed!","details":"There is no tenant defined with name test","validationErrors":null},"unAuthorizedRequest":false,"__abp":true}
```

Logs from Android 12 with Wifi - Took 10+ seconds for the API call.

```
I/flutter (26735): Sevice call via Dart.io HttpClient >>
I/flutter (26735):  Data access time => 0:00:10.314715
I/flutter (26735): {"result":null,"targetUrl":null,"success":false,"error":{"code":0,"message":"Login failed!","details":"There is no tenant defined with name test","validationErrors":null},"unAuthorizedRequest":false,"__abp":true}
I/flutter (26735): Http Client connection closed
I/flutter (26735): Sevice call via Http Plugin >>
I/flutter (26735): Login time access => 0:00:10.349536
I/flutter (26735): {"result":null,"targetUrl":null,"success":false,"error":{"code":0,"message":"Login failed!","details":"There is no tenant defined with name test","validationErrors":null},"unAuthorizedRequest":false,"__abp":true}

```

The output  of `Flutter doctor -v`

```
PS C:\Workspace\flutter\Flutter\samplehttp> flutter doctor -v
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.22000.1219], locale en-US)
    • Flutter version 3.3.6 on channel stable at C:\Applns\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (6 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • 2201116SI (mobile) • b75ac32a6d34 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows      • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
    • Chrome (web)       • chrome       • web-javascript • Google Chrome 108.0.5359.73
    • Edge (web)         • edge         • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

```
</details>

**Comment by exaby73** [comment] 2022-12-07 08:42
I cannot reproduce this issue with my device. Though, I see this proposal as a valid one, so I'll label the issue for insights from the team

**Comment by Hixie** [comment] 2022-12-14 00:12
This is a Dart API issue, if I'm not mistaken. I recommend closing this issue and instead filing it at https://github.com/dart-lang/sdk/issues/new. Thanks!

**Comment by exaby73** [comment] 2022-12-14 08:35
Based on https://github.com/flutter/flutter/issues/116537#issuecomment-1350134115, I am closing this issue. Please follow the instructions and raise an issue in the Dart SDK repo instead. Thank you

**Closed by exaby73** 2022-12-14 08:35 UTC
Labels: new feature, will need additional triage, proposal
