### ISSUE TITLE
Does not run on linux - libGL error: failed to load driver: virtio_gpu

### ISSUE THREAD

**Issue by 1056824847** [flutter/flutter#113733] opened 2022-10-20 03:34 UTC
![image](https://user-images.githubusercontent.com/44287872/196850061-a9250272-c6e1-4a2e-a543-44f6d79075cc.png)
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.5.0-4.0.pre, on UnionTech OS Desktop 20 Pro 4.19.0-arm64-desktop, locale zh_CN.UTF-8)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Flutter IDE Support (No supported IDEs installed)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

**Comment by huycozy** [comment] 2022-10-20 07:50
Hi @1056824847 
Does this issue happen on the Flutter default sample project (counter app)? Also, please provide the error log in text format instead of a screenshot for better readability.

**Comment by 1056824847** [comment] 2022-10-21 06:50
> Hi @1056824847 Does this issue happen on the Flutter default sample project (counter app)? Also, please provide the error log in text format instead of a screenshot for better readability.

# My system information
## Linux zise 4.19.0-arm64-desktop #5210 SMP Wed Jul 27 16:46:15 CST 2022 aarch64 GNU/Linux

**Comment by huycozy** [comment] 2022-10-21 12:39
@1056824847 Thanks! Keeping this open for further insights from the team.

**Comment by 1056824847** [comment] 2022-10-21 18:42
> @1056824847 Thanks! Keeping this open for further insights from the team.
# This is the download address for my linux system
https://cdimage-download.chinauos.com/uniontechos-desktop-20-professional-1050-update2-arm64.iso?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjUzOTQ1ODcsImZpbGVfbmFtZSI6InVuaW9udGVjaG9zLWRlc2t0b3AtMjAtcHJvZmVzc2lvbmFsLTEwNTAtdXBkYXRlMi1hcm02NC5pc28ifQ.wtG_n4VsA_kxYWKnOHQ6hmR7FJoN5voqLGhWSlbqk-I

**Comment by gspencergoog** [comment] 2022-10-27 18:11
Perhaps we need a software driver fallback for Linux?

@1056824847 Can you confirm that you running on an emulator (qemu perhaps)?

**Comment by gspencergoog** [comment] 2022-10-27 18:11
cc @cbracken @robert-ancell

**Comment by 1056824847** [comment] 2022-10-28 02:25
> Perhaps we need a software driver fallback for Linux?
> 
> @1056824847 Can you confirm that you running on an emulator (qemu perhaps)?

The linux I am running now runs using a virtual machine (Parallels Desktop 17)

**Comment by gspencergoog** [comment] 2022-11-17 19:23
You may need to enable accelerated graphics in Parallels.

**Comment by gspencergoog** [comment] 2022-11-17 19:24
Since we can't really reproduce this, we're going to close it for now. (Desktop Triage)

**Closed by gspencergoog** 2022-11-17 19:24 UTC
Labels: severe: crash, engine, platform-linux, a: desktop, P4
