### ISSUE TITLE
Failed LUCI try builds not updating with link in GitHub checks UI

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#93827] opened 2021-11-17 23:15 UTC
For example: https://github.com/flutter/flutter/pull/93580/checks?check_run_id=4244320801

Previous failing checks on this same PR (but a previous commit) DID have links to the LUCI build.

**Comment by godofredoc** [comment] 2021-11-17 23:18
From logs it seems like some status are not being updated:

```

2021-11-17 15:14:39.415 PST
Setting status: {build: Instance of 'Build', hostname: cr-buildbucket.appspot.com, user_data: {"repo_owner":"flutter","repo_name":"engine","user_agent":"flutter-cocoon","check_run_id":4244911208}} for Linux Arm Host Engine
2021-11-17 15:14:39.415 PST
neat_cache: reading cache entry for "configgithubapp_installations"
2021-11-17 15:14:39.416 PST
neat_cache: reading cache entry for "configgithubapp_private_pem"
2021-11-17 15:14:39.416 PST
neat_cache: reading cache entry for "configgithubapp_public_pem"
2021-11-17 15:14:39.417 PST
neat_cache: reading cache entry for "configgithubapp_id"
2021-11-17 15:14:40.076 PST
Updating check run with output: [null]
```

**Comment by keyonghan** [comment] 2021-12-08 19:03
Per our last touch, assigning to @CaseyHillers for potential triage/fix, and moving out of ticket queue.

**Comment by CaseyHillers** [comment] 2021-12-08 19:08
I believe this is a dupe of https://github.com/flutter/flutter/issues/94635. I'll keep it assigned to me while I work on the underlying issue with generating the GitHub tokens

**Comment by CaseyHillers** [comment] 2022-02-18 23:10
I haven't seen this since fixing https://github.com/flutter/flutter/issues/94635. We recently refactored some of the logic to simplify any possible race conditions that would have caused this.

Please reopen if you're still seeing this issue.

**Closed by CaseyHillers** 2022-02-18 23:10 UTC
Labels: passed first triage, team: infra, passed secondary triage, P2
