### ISSUE TITLE
Observatory doesn't start on my Android device due to an error

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#6619] opened 2016-11-01 12:52 UTC
## Steps to Reproduce

* Upgrade to the latest version of Flutter.
* Run any app using `flutter run`.

The bug didn't happen until I upgraded my copy of flutter. I don't recall what revision it was on then, but it was fairly recent (within the last week).

## Logs

Output of `flutter run`:

```
[ +137 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb devices -l
[  +25 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           T06280AJUJ             device usb:5-1 product:ghost_verizon model:XT1060 device:ghost
[  +22 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ shell getprop
[ +228 ms] Running build command.
[  +18 ms] Running 'gradlew build'...
[   +3 ms] [android/] /home/dwayne/flutter_player/android/gradlew build
[+7941 ms] :buildSrc:compileJava UP-TO-DATE
[ +227 ms] :buildSrc:compileGroovy UP-TO-DATE
[  +16 ms] :buildSrc:processResources UP-TO-DATE
[   +3 ms] :buildSrc:classes UP-TO-DATE
[  +34 ms] :buildSrc:jar UP-TO-DATE
[   +3 ms] :buildSrc:assemble UP-TO-DATE
[  +10 ms] :buildSrc:compileTestJava UP-TO-DATE
[   +1 ms] :buildSrc:compileTestGroovy UP-TO-DATE
[        ] :buildSrc:processTestResources UP-TO-DATE
[        ] :buildSrc:testClasses UP-TO-DATE
[   +3 ms] :buildSrc:test UP-TO-DATE
[   +3 ms] :buildSrc:check UP-TO-DATE
[   +4 ms] :buildSrc:build UP-TO-DATE
[+7586 ms] Incremental java compilation is an incubating feature.
[+1368 ms] :app:preBuild UP-TO-DATE
[  +42 ms] :app:preDebugBuild UP-TO-DATE
[   +8 ms] :app:checkDebugManifest
[   +2 ms] :app:preReleaseBuild UP-TO-DATE
[  +33 ms] :app:prepareComGoogleAndroidAgeraAgera120Beta2Library UP-TO-DATE
[   +2 ms] :app:prepareDebugDependencies
[  +18 ms] :app:compileDebugAidl UP-TO-DATE
[  +19 ms] :app:compileDebugRenderscript UP-TO-DATE
[  +20 ms] :app:generateDebugBuildConfig UP-TO-DATE
[+3101 ms] :app:flutterBuild
[        ] Built /home/dwayne/flutter_player/android/app/build/intermediates/flutter/app.flx.
[ +430 ms] :app:mergeDebugShaders UP-TO-DATE
[  +19 ms] :app:compileDebugShaders UP-TO-DATE
[   +2 ms] :app:generateDebugAssets UP-TO-DATE
[  +11 ms] :app:mergeDebugAssets UP-TO-DATE
[  +82 ms] :app:copyFlutterAssetsDebug
[   +6 ms] :app:generateDebugResValues UP-TO-DATE
[   +1 ms] :app:generateDebugResources UP-TO-DATE
[  +16 ms] :app:mergeDebugResources UP-TO-DATE
[  +11 ms] :app:processDebugManifest UP-TO-DATE
[  +35 ms] :app:processDebugResources UP-TO-DATE
[   +1 ms] :app:generateDebugSources UP-TO-DATE
[  +14 ms] :app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
[  +28 ms] :app:compileDebugKotlin UP-TO-DATE
[  +46 ms] :app:compileDebugJavaWithJavac UP-TO-DATE
[  +85 ms] :app:copyDebugKotlinClasses UP-TO-DATE
[   +2 ms] :app:compileDebugNdk UP-TO-DATE
[   +2 ms] :app:compileDebugSources UP-TO-DATE
[ +142 ms] :app:transformClassesWithDexForDebug UP-TO-DATE
[  +18 ms] :app:mergeDebugJniLibFolders UP-TO-DATE
[  +42 ms] :app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
[  +15 ms] :app:transformNative_libsWithStripDebugSymbolForDebug UP-TO-DATE
[        ] :app:processDebugJavaRes UP-TO-DATE
[  +28 ms] :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[   +7 ms] :app:validateSigningDebug
[+2330 ms] :app:packageDebug
[        ] :app:assembleDebug
[   +1 ms] :app:checkReleaseManifest
[   +1 ms] :app:prepareReleaseDependencies
[   +4 ms] :app:compileReleaseAidl UP-TO-DATE
[   +6 ms] :app:compileReleaseRenderscript UP-TO-DATE
[   +5 ms] :app:generateReleaseBuildConfig UP-TO-DATE
[   +4 ms] :app:mergeReleaseShaders UP-TO-DATE
[   +3 ms] :app:compileReleaseShaders UP-TO-DATE
[        ] :app:generateReleaseAssets UP-TO-DATE
[   +6 ms] :app:mergeReleaseAssets UP-TO-DATE
[  +44 ms] :app:copyFlutterAssetsRelease
[   +3 ms] :app:generateReleaseResValues UP-TO-DATE
[        ] :app:generateReleaseResources UP-TO-DATE
[  +10 ms] :app:mergeReleaseResources UP-TO-DATE
[   +8 ms] :app:processReleaseManifest UP-TO-DATE
[  +13 ms] :app:processReleaseResources UP-TO-DATE
[   +2 ms] :app:generateReleaseSources UP-TO-DATE
[   +7 ms] :app:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
[  +17 ms] :app:compileReleaseKotlin UP-TO-DATE
[  +22 ms] :app:compileReleaseJavaWithJavac UP-TO-DATE
[  +49 ms] :app:copyReleaseKotlinClasses UP-TO-DATE
[   +3 ms] :app:compileReleaseNdk UP-TO-DATE
[   +3 ms] :app:compileReleaseSources UP-TO-DATE
[+3052 ms] :app:lintVitalRelease
[  +23 ms] :app:transformClassesWithDexForRelease UP-TO-DATE
[   +9 ms] :app:mergeReleaseJniLibFolders UP-TO-DATE
[  +10 ms] :app:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
[   +8 ms] :app:transformNative_libsWithStripDebugSymbolForRelease UP-TO-DATE
[   +3 ms] :app:processReleaseJavaRes UP-TO-DATE
[  +12 ms] :app:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
[ +866 ms] :app:packageRelease
[        ] :app:assembleRelease
[        ] :app:assemble
[+4252 ms] :app:lint
[        ] Ran lint on variant release: 7 issues found
[   +1 ms] Ran lint on variant debug: 7 issues found
[  +48 ms] Wrote HTML report to file:///home/dwayne/flutter_player/android/app/build/outputs/lint-results-debug.html
[   +8 ms] Wrote XML report to file:///home/dwayne/flutter_player/android/app/build/outputs/lint-results-debug.xml
[   +6 ms] :app:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
[   +3 ms] :app:preDebugUnitTestBuild UP-TO-DATE
[   +5 ms] :app:prepareDebugUnitTestDependencies
[  +13 ms] :app:compileDebugUnitTestKotlin UP-TO-DATE
[  +12 ms] :app:compileDebugUnitTestJavaWithJavac UP-TO-DATE
[   +2 ms] :app:processDebugUnitTestJavaRes UP-TO-DATE
[   +2 ms] :app:compileDebugUnitTestSources UP-TO-DATE
[   +4 ms] :app:mockableAndroidJar UP-TO-DATE
[   +3 ms] :app:assembleDebugUnitTest UP-TO-DATE
[   +5 ms] :app:copyDebugUnitTestKotlinClasses UP-TO-DATE
[  +11 ms] :app:testDebugUnitTest UP-TO-DATE
[   +4 ms] :app:incrementalReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
[   +2 ms] :app:preReleaseUnitTestBuild UP-TO-DATE
[   +3 ms] :app:prepareReleaseUnitTestDependencies
[   +3 ms] :app:compileReleaseUnitTestKotlin UP-TO-DATE
[  +11 ms] :app:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
[   +6 ms] :app:processReleaseUnitTestJavaRes UP-TO-DATE
[   +5 ms] :app:compileReleaseUnitTestSources UP-TO-DATE
[   +7 ms] :app:assembleReleaseUnitTest UP-TO-DATE
[  +11 ms] :app:copyReleaseUnitTestKotlinClasses UP-TO-DATE
[   +4 ms] :app:testReleaseUnitTest UP-TO-DATE
[   +5 ms] :app:test UP-TO-DATE
[   +1 ms] :app:check
[   +2 ms] :app:build
[   +6 ms] BUILD SUCCESSFUL
[  +11 ms] Total time: 32.403 secs
[ +247 ms] This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
[ +368 ms] Built android/app/build/outputs/apk/app-debug.apk (12.6MB).
[        ] Stopping app 'app-debug.apk' on XT1060.
[   +1 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ shell am force-stop com.example.flutter
[   +1 ms] Running install command.
[   +1 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb version
[  +13 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb version
[        ] Android Debug Bridge version 1.0.36
           Revision 84e3321d5db3-android
[   +3 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb start-server
[  +14 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb start-server
[        ] Installing android/app/build/outputs/apk/app-debug.apk...
[        ] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ install -r android/app/build/outputs/apk/app-debug.apk
[+7735 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ install -r android/app/build/outputs/apk/app-debug.apk
[        ] [  0%] /data/local/tmp/app-debug.apk
           [...] lines removed
           [100%] /data/local/tmp/app-debug.apk
           	pkg: /data/local/tmp/app-debug.apk
           Success
[   +4 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ shell echo -n  > /data/local/tmp/sky.com.example.flutter.sha1
[  +23 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ shell echo -n  > /data/local/tmp/sky.com.example.flutter.sha1
[   +6 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ logcat -v time -t 1
[  +44 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ logcat -v time -t 1
[        ] --------- beginning of system
           11-01 08:45:14.193 I/ActivityManager( 1087): Start proc 7205:com.android.keychain/1000 for broadcast com.android.keychain/.KeyChainBroadcastReceiver
[   +2 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ logcat -g -T 11-01 08:45:14.193
[  +29 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ logcat -g -T 11-01 08:45:14.193
[        ] main: ring buffer is 256Kb (242Kb consumed), max entry is 5120b, max payload is 4076b
           system: ring buffer is 256Kb (239Kb consumed), max entry is 5120b, max payload is 4076b
           crash: ring buffer is 256Kb (174b consumed), max entry is 5120b, max payload is 4076b
[        ] Launching loader on XT1060...
[   +4 ms] /home/dwayne/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/dwayne/flutter_player/.packages --print-deps /home/dwayne/flutter_player/lib/main.dart
[ +433 ms] Exit code 0 from: /home/dwayne/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/dwayne/flutter_player/.packages --print-deps /home/dwayne/flutter_player/lib/main.dart
[  +27 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ logcat -v tag -T 11-01 08:45:14.193
[   +2 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb version
[  +14 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb version
[        ] Android Debug Bridge version 1.0.36
           Revision 84e3321d5db3-android
[        ] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb start-server
[  +11 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb start-server
[   +6 ms] /home/dwayne/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/dwayne/flutter_player/.packages --snapshot=build/snapshot_blob.bin --depfile=build/snapshot_blob.bin.d --build-output=build/snapshot_blob.bin /home/dwayne/flutter/packages/flutter/bin/loader/loader_app.dart
[  +82 ms] --------- beginning of system
[ +346 ms] W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=6260, uid=10193 that is not exported from uid 10099
[ +291 ms] Building build/app.flx
[ +251 ms] which zip
[  +11 ms] Encoding zip file to build/app.flx
[  +37 ms] [build/flx/] zip -q /home/dwayne/flutter_player/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE snapshot_blob.bin
[ +259 ms] Exit code 0 from: zip -q /home/dwayne/flutter_player/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE snapshot_blob.bin
[   +1 ms] [build/flx/] zip -q -0 /home/dwayne/flutter_player/build/app.flx assets/default_album_art.png
[  +17 ms] Exit code 0 from: zip -q -0 /home/dwayne/flutter_player/build/app.flx assets/default_album_art.png
[        ] Built build/app.flx.
[        ] Starting bundle for XT1060.
[   +5 ms] XT1060 startBundle
[        ] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ push build/app.flx /data/local/tmp/dev.flx
[ +134 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ push build/app.flx /data/local/tmp/dev.flx
[        ] [  9%] /data/local/tmp/dev.flx
           [ 18%] /data/local/tmp/dev.flx
           [ 27%] /data/local/tmp/dev.flx
           [ 36%] /data/local/tmp/dev.flx
           [ 45%] /data/local/tmp/dev.flx
           [ 54%] /data/local/tmp/dev.flx
           [ 63%] /data/local/tmp/dev.flx
           [ 72%] /data/local/tmp/dev.flx
           [ 81%] /data/local/tmp/dev.flx
           [ 90%] /data/local/tmp/dev.flx
           [ 99%] /data/local/tmp/dev.flx
           [100%] /data/local/tmp/dev.flx
[   +1 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ shell am start -a android.intent.action.RUN -d /data/local/tmp/dev.flx -f 0x20000000 --ez enable-background-compilation true --ez enable-checked-mode true com.example.flutter/.ExampleActivity
[ +734 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ shell am start -a android.intent.action.RUN -d /data/local/tmp/dev.flx -f 0x20000000 --ez enable-background-compilation true --ez enable-checked-mode true com.example.flutter/.ExampleActivity
[        ] Starting: Intent { act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x20000000 cmp=com.example.flutter/.ExampleActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +903 ms] W/ActivityManager: Unable to start service Intent { cmp=com.oasisfeng.greenify/.notification.gadget.NotificationService (has extras) } U=0: not found
[   +7 ms] W/flutter : [WARNING:jni_string.cc(28)] ConvertJavaStringToUTF8 called with null string.
[ +564 ms] observatory port = 50369
[  +15 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ forward tcp:8110 tcp:50369
[  +12 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ forward tcp:8110 tcp:50369
[        ] Observatory listening on http://127.0.0.1:8110
[        ] diagnostic port = 46995
[   +9 ms] /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ forward tcp:8111 tcp:46995
[  +12 ms] Exit code 0 from: /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk/platform-tools/adb -s T06280AJUJ forward tcp:8111 tcp:46995
[        ] Diagnostic server listening on http://127.0.0.1:8111
[ +538 ms] Connected to service protocol on port 8110
[+3917 ms] E/DartVM  : vm-service: Error: Unhandled exception:
[        ] E/DartVM  : FileSystemException: Creation of temporary directory failed, path = '/data/local/tmp' (OS Error: Permission denied, errno = 13)
[        ] E/DartVM  : #0      _Directory.createTemp.<anonymous closure> (directory_impl.dart:128)
[        ] E/DartVM  : #1      _RootZone.runUnary (dart:async/zone.dart:1404)
[        ] E/DartVM  : #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
[        ] E/DartVM  : #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
[        ] E/DartVM  : #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
[        ] E/DartVM  : #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
[        ] E/DartVM  : #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
[        ] E/DartVM  : #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] E/DartVM  : #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] E/DartVM  : #9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[        ] E/DartVM  : #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[        ] E/DartVM  : 
[        ] E/flutter : [ERROR:../../flutter/runtime/dart_init.cc(137)] Isolate vm-service exited with an error
[        ] E/flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter : FileSystemException: Creation of temporary directory failed, path = '/data/local/tmp' (OS Error: Permission denied, errno = 13)
[        ] E/flutter : #0      _Directory.createTemp.<anonymous closure> (directory_impl.dart:128)
[        ] E/flutter : #1      _RootZone.runUnary (dart:async/zone.dart:1404)
[        ] E/flutter : #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
[        ] E/flutter : #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
[        ] E/flutter : #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
[        ] E/flutter : #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
[        ] E/flutter : #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
[        ] E/flutter : #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] E/flutter : #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] E/flutter : #9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[        ] E/flutter : #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Output from `flutter analyze`:

```
Analyzing 7 files...
[hint] This method overrides a method annotated as @mustCall super in 'State', but does invoke the overriden method. (lib/src/widgets/album_list.dart, line 43, col 8)
[hint] Unused import. (lib/main.dart, line 11, col 8)
[hint] Unused import. (lib/main.dart, line 5, col 8)
[hint] Unused import. (lib/main.dart, line 8, col 8)
(Ran in 18.1s)
```

## Flutter Doctor

Output from `flutter doctor`:

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/dwayne/flutter
    • Framework revision 4b037fd65f (13 hours ago), 2016-10-31 16:46:54
    • Engine revision 63e71803de
    • Tools Dart version 1.21.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /home/dwayne/adt-bundle-linux-x86_64-20140702/sdk
    • Platform android-24, build-tools 24.0.3
    • OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.40

[✓] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • XT1060 • T06280AJUJ • android-arm • Android 5.1 (API 22)
```

**Comment by eseidelGoogle** [comment] 2016-11-01 13:42
@johnmccutchan is probably the best person for triage.  Looks like there was a write permission error, but the service isolate may also have failed to start before we even got there.

Looks like this might be a MOTO X XT1060?  I'm not sure we have one of those around the office, but certainly can get one if needed.

**Comment by ds84182** [comment] 2016-11-01 13:49
Ok, so I just managed to fix it. Some old Flutter APKs were floating around my build environment. Removing the build folders and running again fixes the issue.

**Comment by ds84182** [comment] 2016-11-01 14:33
I managed to reproduce the bug with the hello_services example. If you run in release then run in debug debug mode breaks, probably because it continues to use the release mode APK. For the other examples I can't reproduce it at all.

**Comment by eseidelGoogle** [comment] 2016-11-17 19:07
Based on the last comment sounds like this is a dependency-tracking issue with the hello_service example.

**Comment by Hixie** [comment] 2017-12-20 00:33
We've had two reports of this so far.

**Comment by nikki93** [comment] 2018-01-11 21:00
I faced this too, also having made a release then a debug build of my app. After seeing the comment at https://github.com/flutter/flutter/issues/6619#issuecomment-257581560 I decided to delete my build/ directory and try an Android build again and it worked!

**Comment by mklim** [comment] 2018-09-26 19:35
Is this crash reproducing for anyone still? Started looking into fixing this, but the example @ds84182 originally was able to reproduce the bug with was removed in flutter/flutter#8995. I couldn't get the crash to happen in the other example apps I spot checked.

**Comment by mklim** [comment] 2018-09-26 22:42
Thanks for the info. I'm going to close this, please file a new issue if this happens again.

**Closed by mklim** 2018-09-26 22:42 UTC
Labels: engine, severe: crash, ▣ platform-android
