### ISSUE TITLE
[web] large Radius.circular causes rendering issue

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#38857] opened 2019-08-19 23:40 UTC
## Steps to Reproduce

1. Use a BoxDecoration with a circularBorderRadius that is too large e.g. `(BorderRadius.all(Radius.circular(64)` for a small container)
2. observe rendering artifact

on iOS:
![Screen Shot 2019-08-19 at 4 40 01 PM](https://user-images.githubusercontent.com/1145719/63306583-02db6780-c2a0-11e9-8144-dbb4b1632c89.png)

in Chrome:
![Screen Shot 2019-08-19 at 4 40 06 PM](https://user-images.githubusercontent.com/1145719/63306587-0969df00-c2a0-11e9-931c-164817a1e778.png)

**Comment by ferhatb** [comment] 2019-08-21 20:33
duplicate of https://github.com/flutter/flutter/issues/38549

**Closed by ferhatb** 2019-08-21 20:33 UTC
Labels: waiting for PR to land (fixed), ☸ platform-web
