### ISSUE TITLE
[tool_crash] UnknownException

### ISSUE THREAD

**Issue by vousmeevoyez** [flutter/flutter#131725] opened 2023-08-02 00:17 UTC
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/sign_in_page_test.dart -d chrome
```

## Steps to Reproduce
1. Running standalone crhome `docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest`
2. Running flutter drive

## Logs
UnknownException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:102:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:103:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:309:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.7.9, on macOS 13.4 22F66 darwin-arm64, locale en-ID)
    • Flutter version 3.7.9 on channel stable at /Users/kelvin/fvm/versions/3.7.9
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/kelvin/fvm/versions/3.7.9. Consider adding /Users/kelvin/fvm/versions/3.7.9/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (4 months ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.4.7+511
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
amplitude_flutter-3.15.0
audioplayers-3.0.1
audioplayers_android-2.0.0
audioplayers_darwin-3.0.1
audioplayers_linux-1.0.4
audioplayers_web-2.2.0
audioplayers_windows-1.1.3
connectivity_plus-3.0.3
flutter_image_compress-2.0.3
flutter_image_compress_common-1.0.1
flutter_image_compress_web-0.1.3
flutter_plugin_android_lifecycle-2.0.8
flutter_secure_storage-8.0.0
flutter_secure_storage_linux-1.1.3
flutter_secure_storage_macos-3.0.0
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-2.0.0
image_picker-0.8.6+3
image_picker_android-0.8.5+7
image_picker_for_web-2.1.11
image_picker_ios-0.8.6+9
integration_test
mobile_scanner-3.3.0
network_info_plus-3.0.2
package_info_plus-3.0.3
path_provider-2.0.15
path_provider_android-2.0.22
path_provider_foundation-2.1.1
path_provider_linux-2.1.8
path_provider_windows-2.1.7
sentry_flutter-7.9.0
share_plus-7.0.2
sqflite-2.2.4+1
ua_client_hints-1.1.3
url_launcher-6.1.9
url_launcher_android-6.0.23
url_launcher_ios-6.1.0
url_launcher_linux-3.0.5
url_launcher_macos-3.0.2
url_launcher_web-2.0.18
url_launcher_windows-3.0.7

**Comment by vousmeevoyez** [comment] 2023-08-02 00:18
Launching integration_test/sign_in_page_test.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             25.9s
This app is linked to the debug service: ws://127.0.0.1:58232/738Zkkt_1A4=/ws
Debug service listening on ws://127.0.0.1:58232/738Zkkt_1A4=/ws

💪 Running with sound null safety 💪
00:00 +0: (setUpAll)
00:00 +1: Scenario 1: When the app is loaded for the first time the user should be able to login / sign up

Oops; flutter has exited unexpectedly: "UnknownException (500): Illegal key values seen in w3c capabilities: [chromeOptions]".
A crash report has been written to /Users/kelvin/apps/kabloom/mindhive_yeah_nah/flutter_05.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+UnknownException+%28500%29%3A+Illegal+key+values+seen+in+w3c+capabilities%3A+%5BchromeOptions%5D

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!

**Comment by danagbemava-nc** [comment] 2023-08-02 06:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/123602

**Closed by danagbemava-nc** 2023-08-02 06:48 UTC
Labels: in triage
