### ISSUE TITLE
SnackBar not shown while bottomSheet is used

### ISSUE THREAD

**Issue by fayaz07** [flutter/flutter#58615] opened 2020-06-03 17:31 UTC
## Steps to Reproduce

1. Create a basic screen with Scaffold widget
2. Add a child to `bottomSheet` property of Scaffold
3. Create a `GlobalKey<ScaffoldState>`, attach it to Scaffold's key
4. Try to show a snackbar

**Expected results:** 

Should popup a Snackbar.

**Actual results:**

SnackBar not shown, neither it threw any error. 

**Problem**

As there is a child for `bottomSheet` property, the Snackbar didn't show up. When I tried to remove `bottomSheet` and replaced with `bottomNavigationBar` it did popup and works fine.

**Comment by TahaTesser** [comment] 2020-06-04 09:32
Snackbar is show but it's hidden behind bottom, you can see it if you  set container's height to be 50 in `BottomSheet`

![Simulator Screen Shot - iPhone 11 - 2020-06-04 at 14 59 03](https://user-images.githubusercontent.com/48603081/83740200-224b5180-a674-11ea-9cb7-a0dcea97e024.png)

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final GlobalKey<ScaffoldState> key = GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: key,
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Stack(
        alignment: Alignment.center,
        children: [
          Positioned(
            bottom: 0,
            child: Text('Hello World'),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          key.currentState.showSnackBar(SnackBar(
              content: Text('Yay! A SnackBar!'),
              action: SnackBarAction(
                label: 'Undo',
                onPressed: () {},
              )));
        },
      ),
      bottomSheet: BottomSheet(
          backgroundColor: Colors.transparent,
          onClosing: () {},
          builder: (_) {
            return Container(height: 50, color: Colors.transparent);
          }),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (2 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details> 

Closing as duplicate of https://github.com/flutter/flutter/issues/19547

**Closed by TahaTesser** 2020-06-04 09:32 UTC

**Comment by fayaz07** [comment] 2020-06-04 10:51
sorry, actually it didn't show me suggestion while raising the issue. Thanks @TahaTesser  for considering this issue and solving it in v1.19
