### ISSUE TITLE
firebase_core compilation issue that started in xcode 13 beta

### ISSUE THREAD

**Issue by assaf000** [flutter/flutter#84974] opened 2021-06-21 11:10 UTC
## Steps to Reproduce

1. Compile [firebase_core](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core) using xcode 13 beta.

## Logs
You the compile error for [FLTFirebaseCorePlugin.h](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.h)
`'TARGET_OS_OSX' is not defined, evaluates to 0`
<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-06-21 11:22
Hi @assaf000 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-21 11:22 UTC
Labels: in triage

**Comment by assaf000** [comment] 2021-06-21 11:31
ok, thanks!

**Comment by aDrIaNo34500** [comment] 2021-06-21 11:46
FR
