### ISSUE TITLE
Project Creation

### ISSUE THREAD

**Issue by saisashreek5thdt** [flutter/flutter#48111] opened 2020-01-03 06:11 UTC
Initially, when i downloaded flutter files and setup. It worked fine then later it stopped working and cant create new projects. I setup flutter in AndroidStudio, which has the latest version.

When I started using flutter I could do some small changes in code and also could see it in output.
Only error I get now while creating new project is flutter_01. If I open the file its in .txt mode.
[flutter_01.log](https://github.com/flutter/flutter/files/4018244/flutter_01.log).

Can anyone help me out with this issue.

**Comment by iapicca** [comment] 2020-01-03 09:04
Hi @saisashreek5thdt 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by VladyslavBondarenko** [comment] 2020-01-03 09:12
Hi @saisashreek5thdt 
I see there are issues addressing the case you described.
Please take a look on [this issue](https://github.com/flutter/flutter/issues/43734), or [this one](https://github.com/flutter/flutter/issues/43431)
The problem was already discussed.
Thank you

**Comment by stuartmorgan** [comment] 2020-01-03 20:11
Closing as a duplicate of #43734

**Closed by stuartmorgan** 2020-01-03 20:11 UTC
Labels: waiting for customer response
