### ISSUE TITLE
skia_object_cache.dart:248:12 !browserSupportsFinalizationRegistry

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#95635] opened 2021-12-21 15:32 UTC
```
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart:248:12
!browserSupportsFinalizationRegistry
is not true

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
lib/_engine/engine/canvaskit/skia_object_cache.dart 248:13                    [_doResurrect]
lib/_engine/engine/canvaskit/skia_object_cache.dart 245:40                    get skiaObject
lib/_engine/engine/canvaskit/canvas.dart 210:33                               drawPicture
lib/_engine/engine/canvaskit/layer.dart 467:17                                paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 337:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 257:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 537:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 537:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 154:5                                 paint
lib/_engine/engine/canvaskit/layer_tree.dart 56:17                            paint
lib/_engine/engine/canvaskit/layer_tree.dart 99:16                            <fn>
lib/_engine/engine/profiler.dart 37:18                                        timeAction
lib/_engine/engine/canvaskit/layer_tree.dart 98:5                             raster
lib/_engine/engine/canvaskit/rasterizer.dart 33:22                            draw
lib/_engine/engine/platform_dispatcher.dart 579:7                             render
lib/ui/src/ui/window.dart 93:50                                               render
packages/flutter/src/rendering/view.dart 229:15                               compositeFrame
packages/flutter/src/rendering/binding.dart 501:18                            drawFrame
packages/flutter/src/widgets/binding.dart 883:13                              drawFrame
packages/flutter/src/rendering/binding.dart 363:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1145:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1082:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1005:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 159:5                             invokeOnDrawFrame
lib/_engine/engine.dart 455:45                                                <fn>
```

Caused with 

```dart
LayoutBuilder(
                builder: (context, constraints) {
                  final widgetHeight = constraints.maxHeight;
                  return SizedBox(
                    height: widgetHeight,
                    child: Image.memory(
                      bytes!,
                      fit: BoxFit.cover,
                    ),
                  );
                },
              )
```

doctor
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.8.1 at /Users/danielmills/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/danielmills/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Users/danielmills/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • IN2017 (mobile)            • 2e01d742                  • android-arm64  • Android 11 (API 30)
    • cyberpwn’s iPhone (mobile) • 00008101-001818940228001E • ios            • iOS 14.7.1 18G82
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 96.0.4664.110
```

**Comment by darshankawar** [comment] 2021-12-22 07:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/94906

**Closed by darshankawar** 2021-12-22 07:16 UTC
Labels: in triage
