### ISSUE TITLE
Flutter web spellcheck (Firefox grammar check)

### ISSUE THREAD

**Issue by ihorkozar** [flutter/flutter#103342] opened 2022-05-09 13:54 UTC
The Firefox grammar check somehow fits into the text field and highlights the wrong input (which is correct in my particular case). Setting autocorrect: false, enableSuggestions: false doesn't help.

As far as I understand flutter web spellcheck doesn't work at all - https://github.com/flutter/flutter/issues/40682

I would appreciate a hint on how to solve this problem.

**Comment by darshankawar** [comment] 2022-05-10 06:26
@ihorkozar 
Can you elaborate on the issue by providing `flutter doctor -v`, a minimal code sample along with actual vs expected behavior you are looking for and what exactly is the behavior you are reporting ?

**Comment by ihorkozar** [comment] 2022-05-10 08:52
@darshankawar Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6.1 20G224 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by ihorkozar** [comment] 2022-05-10 08:56
@darshankawar I am using a standard textfield, If I add the attribute spellcheck = 
false in the inspector to the textarea, then everything starts working correctly. But I don't see any way to pass this attribute from flutter.
![Screenshot 2022-05-10 at 11 51 06](https://user-images.githubusercontent.com/45120893/167590153-ef1e7d04-fffc-4aad-8652-2dbdd2032715.png)

**Comment by darshankawar** [comment] 2022-05-10 11:49
Thanks for the update. I am trying to understand what's the difference between your use case and the linked issue : https://github.com/flutter/flutter/issues/40682 which seems to be open at the moment. Are you hitting same issue as discussed in it ?

**Comment by ihorkozar** [comment] 2022-05-10 17:33
@darshankawar I would say that my problem is mirrored. The issue https://github.com/flutter/flutter/issues/40682 discusses the possibility of turning on the spellcheck, but on the contrary, I'm interested in the possibility of turning it off. And I think, in principle, a rather interesting case that in one of the browsers (Firefox) the spellcheck works.

**Comment by darshankawar** [comment] 2022-05-11 05:44
Thanks for the update. Per this PR linked in original issue, it seems to have been merged already long time back https://github.com/flutter/engine/pull/12192, so I am not sure if due to it, you are able to see some stuff working.

`enableSuggestions` only works on mobile platform per https://api.flutter.dev/flutter/material/TextField/enableSuggestions.html, so it won't work in web.

Can you try with `keyboardType: TextInputType.visiblePassword` and see if it helps ?

**Closed** 2022-06-01 06:12 UTC
Labels: waiting for customer response, in triage
