### ISSUE TITLE
Engine -> Framework autoroller PRs failing due to queued tasks not running

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#80376] opened 2021-04-13 16:15 UTC
See: https://github.com/flutter/flutter/pull/80183

**Comment by godofredoc** [comment] 2021-04-13 16:28
Retried manually.

**Comment by keyonghan** [comment] 2021-04-13 16:32
> Retried manually.

The retry fails (This should be retried agains flutter/flutter, rather than flutter/engine)

```
2021-04-13 09:24:06.880 PDT
Attempt to download /flutter/engine/98f974cfff3e85f752def4e30042341aa83a3a44/ci/dev/try_builders.json failed (HTTP 404)
2021-04-13 09:24:08.921 PDT
Attempt to download /flutter/engine/98f974cfff3e85f752def4e30042341aa83a3a44/ci/dev/try_builders.json failed (HTTP 404)
2021-04-13 09:24:12.964 PDT
Attempt to download /flutter/engine/98f974cfff3e85f752def4e30042341aa83a3a44/ci/dev/try_builders.json failed (HTTP 404)
2021-04-13 09:24:18.965 PDT
GitHub not responding; giving up
```

**Comment by godofredoc** [comment] 2021-04-13 16:47
yeah, I didn't change some repo in the first retries but the last one was successful.

**Comment by godofredoc** [comment] 2021-04-13 17:12
I can't find anything wrong in the logs. We may be hiding errors either scheduling the builds in LUCI side or failing to process the pubsub status updates.

**Comment by godofredoc** [comment] 2021-04-13 23:55
Moving as P3 to investigate why sometimes tasks are stuck in a queue state.

**Comment by godofredoc** [comment] 2021-04-19 18:21
Next time this happens we'll need to use the buildbucket rpc explorer to check if tasks were actually created.

**Comment by godofredoc** [comment] 2021-04-21 04:32
Took a look at this issue and the problem is that luci builds are failing to be scheduled:

Using the following query at go/buildbucket-rpc-explorer for commit https://github.com/flutter/flutter/commit/8d3022ec40b3b0e3f442d783246bad17cd426624  gives an empty result

```
{
    "predicate": {
        "builder": {
            "project": "flutter",
            "bucket": "try"
        },
        "tags": [
            {
                "key": "buildset",
                "value": "pr/git/80003"
            },
            {
                "key": "buildset",
                "value": "sha/git/8d3022ec40b3b0e3f442d783246bad17cd426624"
            }
        ]
    },
    "fields": "*"
}
```

The theory is we are failing to trigger LUCI builds silently not printing any logs.

**Comment by godofredoc** [comment] 2021-04-21 04:35
This is what I see in the checks page:

![image](https://user-images.githubusercontent.com/54371434/115497361-5c87f800-a220-11eb-8531-a0a5dd2535a7.png)

**Comment by godofredoc** [comment] 2023-06-13 18:49
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.

**Closed by godofredoc** 2023-06-13 18:49 UTC
Labels: team, passed first triage, team: infra, passed secondary triage, P3
