### ISSUE TITLE
[web]: Cannot use kill - SIGUSR1 PIDFILE to issue hot-reload

### ISSUE THREAD

**Issue by tianna1121** [flutter/flutter#44795] opened 2019-11-13 04:42 UTC
The "kill -SIGUSR1 PIDFILE" works well for both iOS & Android devices. However, when I issue the same command to web-server, it really "KILL"ed the process. When I press "r" or "R" in the terminal, it works fine. I know the flutter-web is still under tech-preview stage. But, could you please add this feature in the up-coming release? Thanks.

Command: 
```
flutter run -d web-server --web-port=41943 --web-hostname=localhost --profile --pid-file pid
kill -SIGUSR1 $(cat pid)
/Users/yang/ws/flutter/flutter/bin/flutter: line 192: 82221 User defined signal 1: 30 "$DART" --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
```

Fluter_web version: Flutter 1.10.15 • channel dev
Browser version: MacOS Chrome 78.0.3904.97

**Comment by jonahwilliams** [comment] 2019-11-13 05:04
The existing logic checks if the resident runner supports the "service protocol" (vmservice) before registering SIGUSR1 and SIGUSR2

https://github.com/flutter/flutter/blob/e7073f9a1f5c40398f589ae45956b489b1f3ab10/packages/flutter_tools/lib/src/resident_runner.dart#L1052

On the web-server device, this will be false since we do not support the vmservice proxy in that mode. It seems like this check is unnecessary and could be replaced with a check for hot reload and hot restart allowed

**Comment by tianna1121** [comment] 2019-11-13 05:46
thanks for your quick response. I am trying to rebuild the flutter local engine now.

**Comment by jonahwilliams** [comment] 2019-11-15 07:14
I re-opening the issue because web should be able to use this feature but it isn't implemented

**Comment by clearloop** [comment] 2021-01-16 16:46
Any updates or some workaround advice?

**Comment by exaby73** [comment] 2022-07-26 13:13
Hello @tianna1121. Upon trying to reproduce this issue, I have reached a sort of blocker. When running a flutter app as a web server (`flutter run -d web-server --pid-file pid`), the pid file does not get generated. Though, when doing the same with chrome (`flutter run -d chrome --pid-file pid`), it does.

When testing with chrome, the behavior you described does in fact exist, pointing to this issue being fixed. But due to the pid file not being generated, and your original post specifying web server, I cannot proceed to close the issue.

Can you provide some feedback on this? Are you able to reproduce it still?

**Closed** 2022-08-16 13:17 UTC
Labels: easy fix, waiting for customer response, tool, r: timeout
