### ISSUE TITLE
[MacOS] SingleChildScrollView twitching when mouse cursor is on TextField

### ISSUE THREAD

**Issue by bytes7bytes7** [flutter/flutter#149723] opened 2024-06-05 08:20 UTC
### Steps to reproduce

1. Install Flutter 3.22.1 (stable)
2. Create new Flutter project
3. Add screen with SingleChildScrollView, Column, TextField
4. Run MacOS app
5. Point mouse cursor on TextField
6. Make scroll from up to down (make overscroll)

### Expected results

Smooth scroll

### Actual results

Twitching scroll

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            TextField(
              decoration: InputDecoration(
                labelText: 'Hint',
              ),
            ),
            TextField(
              decoration: InputDecoration(
                hintText: 'Hint',
              ),
            ),
            TextField(
              decoration: InputDecoration(
                hintText: 'Hint',
              ),
            ),
            TextField(
              decoration: InputDecoration(
                hintText: 'Hint',
              ),
            ),
            TextField(
              decoration: InputDecoration(
                hintText: 'Hint',
              ),
            ),
            TextField(
              decoration: InputDecoration(
                hintText: 'Hint',
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/74134786/f48361eb-5d8b-4c9d-a69a-195c11355833

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.22.1, on macOS 14.2.1 23C71 darwin-arm64, locale ru-RU)
    • Flutter version 3.22.1 on channel stable at /Users/anatoli/fvm/versions/3.22.1
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/anatoli/fvm/versions/3.22.1. Consider adding /Users/anatoli/fvm/versions/3.22.1/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (2 недели назад), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/anatoli/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2024-06-05 11:31
I can't reproduce this on my end on Mac Intel chip. I see you are using a Mac Apple chip, I'm unsure if this is related. 

<details>
<summary>Demo (issue is not reproduced)</summary>

https://github.com/flutter/flutter/assets/104349824/681f20f7-dea0-43f8-a926-a1a8282e4c6f

</details>


Could you retry on the latest Flutter master channel? 

Also, does the issue also occur with trackpad?

**Comment by huycozy** [comment] 2024-06-06 04:40
Thanks for checking that. Since this issue has been fixed on master, I will close it. For the `scroll is inverted` issue, please help to a separate issue for it.

**Closed by huycozy** 2024-06-06 04:40 UTC
Labels: in triage
