### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by suresh161229** [flutter/flutter#80696] opened 2021-04-19 06:30 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2021-04-19 08:17
self duplicate of https://github.com/flutter/flutter/issues/80695

**Comment by pedromassangocode** [comment] 2021-04-19 08:19
Closing as duplicate of https://github.com/flutter/flutter/issues/80695.

**Closed by pedromassangocode** 2021-04-19 08:19 UTC
Labels: in triage
