### ISSUE TITLE
Dialog/BottomSheet background color breaks on Impeller

### ISSUE THREAD

**Issue by AhmedLSayed9** [flutter/flutter#138571] opened 2023-11-16 21:30 UTC
### Is there an existing issue for this?

This might be related to https://github.com/flutter/flutter/issues/135659 but it's closed now.

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the project using [Impeller rendering engine](https://docs.flutter.dev/perf/impeller)
2. Press `Show Dialog` or `showModalBottomSheet` button.

### Expected results

I except the background color to be white.

### Actual results

The background color is not white.

**Alternative workaround:**
Setting elevation to 0 should fix this.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextButton(
              onPressed: () => showDialog<String>(
                context: context,
                builder: (BuildContext context) => AlertDialog(
                  backgroundColor: Colors.white,
                  title: const Text('AlertDialog Title'),
                  content: const Text('AlertDialog description'),
                  actions: <Widget>[
                    TextButton(
                      onPressed: () => Navigator.pop(context, 'Cancel'),
                      child: const Text('Cancel'),
                    ),
                    TextButton(
                      onPressed: () => Navigator.pop(context, 'OK'),
                      child: const Text('OK'),
                    ),
                  ],
                ),
              ),
              child: const Text('Show Dialog'),
            ),
            TextButton(
              child: const Text('showModalBottomSheet'),
              onPressed: () {
                showModalBottomSheet<void>(
                  context: context,
                  backgroundColor: Colors.white,
                  builder: (BuildContext context) {
                    return SizedBox(
                      height: 200,
                      child: Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[
                            const Text('Modal BottomSheet'),
                            ElevatedButton(
                              child: const Text('Close BottomSheet'),
                              onPressed: () => Navigator.pop(context),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="350" alt="Screenshot 2023-11-16 at 11 23 07 PM" src="https://github.com/flutter/flutter/assets/70890146/be17c061-886e-4b52-ad76-b6764191ff9c">
<img width="334" alt="Screenshot 2023-11-16 at 11 23 39 PM" src="https://github.com/flutter/flutter/assets/70890146/14c582e9-5c51-440b-ab42-6fbb475e4ff0">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64 (Rosetta), locale en-EG)
    • Flutter version 3.13.6 on channel stable at /Users/bx777/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (7 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/bx777/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 8F0DE058-66D7-4970-8C9D-DD01B3953F4B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS
      13.5.2 22G91 darwin-arm64 (Rosetta)
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-11-17 09:30
Thanks for filing this. 
This doesn't seem to be an issue with flutter itself but the expected behaviour of the colour of Dialogs with Material 3, you can see https://m3.material.io/components/dialogs/overview#4ed577f5-fb0b-4e9f-9e41-cb0dbd4e9265 for more details.
Setting `useMaterial3: false` would also give a white colour.
Closing this as this seems to be the expected behaviour, if you disagree or if I misunderstood your issue, please comment and I'll reopen this.
Thank you!

**Closed by dam-ease** 2023-11-17 09:30 UTC
Labels: in triage

**Comment by AhmedLSayed9** [comment] 2023-11-17 15:43
You're right. The change in the background color comes from `surfaceTintColor`, setting it to Colors.transparent fixes it.

Thanks!
