### ISSUE TITLE
TextField intrinsic width doesn't take into account label or errorText

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15401] opened 2018-03-11 08:25 UTC
cc @HansMuller

**Comment by zoechi** [comment] 2019-01-15 16:53
Not sure what the expected behavior is

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: IntrinsicWidth(
            child: Column(
              children: <Widget>[
                Expanded(
                    child: Container(
                  child: Center(child: Text('foo')),
                  color: Colors.amberAccent,
                )),
                TextField(
                  decoration: InputDecoration(
                      labelText: 'label1 label2 label3 label4',
                      errorText: 'error1 error2 error3 error4'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

results in label and error text to be truncated 

![image](https://user-images.githubusercontent.com/405837/51195972-6fe3e480-18ee-11e9-8a55-0c8d4d4d328d.png)

**Comment by TahaTesser** [comment] 2020-04-24 11:24
Issue still exist

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (3 days ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.122
    • Web Server                • web-server    • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by YeungKC** [comment] 2020-11-03 20:12
![image](https://user-images.githubusercontent.com/11473691/98035718-e9e2b600-1e53-11eb-876e-393e33b0a92a.png)


Could not reproduce in master branch, now fixed, please close.

cc @TahaTesser @justinmc

**Comment by justinmc** [comment] 2020-11-04 01:22
I think I agree that this should be closed by looking at that screenshot, but I'll leave it to @TahaTesser in case I'm misunderstanding.

**Comment by TahaTesser** [comment] 2020-11-04 13:37
I can confirm the issue is fixed 
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-7.0.pre.88, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-7.0.pre.88 at /Users/tahatesser/Code/flutter_master
    • Framework revision bf94fa072d (16 hours ago), 2020-11-03 16:23:27 -0500
    • Engine revision 59b01e0e5a
    • Dart version 2.12.0 (build 2.12.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (6 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.1
    • iPhone 12 (mobile)   • 572593A3-647B-413C-9188-B91DD07DEAF0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)     • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 86.0.4240.183

• No issues found!

```

</details>

Closing as fixed

**Closed by TahaTesser** 2020-11-04 13:37 UTC
Labels: P4, a: text input, f: material design, found in release: 1.18, framework, has reproducible steps
