### ISSUE TITLE
`gen_l10n/app_localizations.dart` is not recognized

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#120561] opened 2023-02-12 16:12 UTC
I am following https://docs.flutter.dev/development/accessibility-and-localization/internationalization#introduction-to-localizations-in-flutter

I got app_localizations.dart generated, but import of `gen_l10n/app_localizations.dart` is not recognized.

My pubspec:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
```

<img width="890" alt="Screenshot 2023-02-12 at 8 09 43 AM" src="https://user-images.githubusercontent.com/12115586/218322643-1b14e2ed-506f-4930-b80f-66648e3654d9.png">

<img width="958" alt="Screenshot 2023-02-12 at 8 10 47 AM" src="https://user-images.githubusercontent.com/12115586/218322650-49ce084a-9415-43dc-b309-93f9044918f4.png">

**Comment by polina-c** [comment] 2023-02-12 16:25
```
flutter --version
Flutter 3.8.0-7.0.pre • channel flutter-3.8-candidate.7 • https://github.com/flutter/flutter.git
Framework • revision 1e6e6d41e3 (5 days ago) • 2023-02-07 20:18:32 -0800
Engine • revision f310ffd146
Tools • Dart 3.0.0 (build 3.0.0-204.0.dev) • DevTools 2.21.1
```

**Comment by huycozy** [comment] 2023-02-13 10:40
Hi @polina-c 
Does it show any suggestions when clicking on `Quick Fix`? 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

**Comment by polina-c** [comment] 2023-02-13 19:39
Added you as contributor to https://github.com/polina-c/flutter-chat

Issues are:

1. What I follow [adding-your-own-localized-messages](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages) step 2 to add `generate: true` to pubspec.,yaml, pub get is unhappy:

![Screenshot 2023-02-13 at 11 33 07 AM](https://user-images.githubusercontent.com/12115586/218556129-8e121b5a-5c44-4d30-beea-f3595b7c3dd0.png)

2. For step 6, it says to remove l10n.yaml, that i created in step 3
```
polinach-macbookpro3:flutter-chat polinach$ flutter gen-l10n
Because l10n.yaml exists, the options defined there will be used instead.
To use the command line arguments, delete the l10n.yaml file in the Flutter project.


Attempted to generate localizations code without having the flutter: generate flag turned on.
Check pubspec.yaml and ensure that flutter: generate: true has been added and rebuild the project. Otherwise, the
localizations source code will not be importable.
```

3. If i delete the file, generation succeeds, but then I get issue with import described begore


Does it help?

**Comment by polina-c** [comment] 2023-02-13 23:06
And no meaningful suggestions with Quick Fix

**Comment by huycozy** [comment] 2023-02-14 08:57
@polina-c 

>What I follow [adding-your-own-localized-messages](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages) step 2 to add generate: true to pubspec.yaml, pub get is unhappy:

You should add `generate: true` to the end `flutter` as the document mentioned (_and usually comes later in the pubspec file._), not in `flutter`'s `dependencies`; for eg:

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  intl: ^0.18.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

```

>If i delete the file, generation succeeds, but then I get issue with import described begore

The correct import should be: 
```
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
```

Please try the above changes and confirm if they work.

**Comment by huycozy** [comment] 2023-02-15 04:06
Honestly, I think this isn't an issue to fix since you can see instructions from step 2 and step 7 respectively.


>2. Then in the pubspec.yaml file, enable the generate flag. This is added to the section of the pubspec that is specific to Flutter, and usually comes later in the pubspec file.

>7. Add the import statement on app_localizations.dart and AppLocalizations.delegate in your call to the constructor for MaterialApp.

**Comment by huycozy** [comment] 2023-02-15 04:07
I will be closing this issue as solved. If you disagree, please write in the comments and I will reopen it. Thanks!

**Closed by huycozy** 2023-02-15 04:07 UTC
Labels: in triage

**Comment by polina-c** [comment] 2023-08-23 18:34
Sorry to be late here. I still think instructions in generated file should not be misleading.
If they are hard to maintain up-to-date, there should not be instructions at all.

**Comment by huycozy** [comment] 2023-08-25 04:27
I checked the documentation again, looks like the 2nd step has been updated since it's different than the content I posted at https://github.com/flutter/flutter/issues/120561#issuecomment-1430726314.

Currently, the 2nd step stated:
```
Open the pubspec.yaml file and enable the generate flag. This flag is found in the flutter section in the pubspec file.

# The following section is specific to Flutter.
flutter:
  generate: true # Add this line

```

I agree it should be more detailed. But I think it's best suited on [Website repository](https://github.com/flutter/website/issues) than here. I would suggest you open an issue there for this request.
