### ISSUE TITLE
error in keyboard event

### ISSUE THREAD

**Issue by Ahmedzafar7600** [flutter/flutter#111390] opened 2022-09-12 12:55 UTC
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#19a62(physicalKey: PhysicalKeyboardKey#7001d(usbHidUsage: "0x0007001d", debugName: "Key Z"), logicalKey: LogicalKeyboardKey#0007a(keyId: "0x0000007a", keyLabel: "Z", debugName: "Key Z"), character: null, timeStamp: 9:07:01.547846)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by ggirotto** [comment] 2022-09-12 13:55
Duplicate of https://github.com/flutter/flutter/issues/110950 ?

**Comment by danagbemava-nc** [comment] 2022-09-12 14:20
Hi @Ahmedzafar7600, please provide the output of `flutter doctor -v` along with a minimal reproducible code sample and steps to reproduce this issue. 

Thank you

**Closed** 2022-10-03 14:22 UTC
Labels: waiting for customer response, in triage
