### ISSUE TITLE
verify_binaries_codesigned  failing cloning repo: Host key verification failed. fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#111772] opened 2022-09-16 20:48 UTC
Cherry-pick https://github.com/flutter/flutter/pull/111759 `verify_binaries_codesigned` is failing
```
13:31:21.219299 git.c:460               trace: built-in: git clone --origin upstream -- git@github.com:flutter/flutter.git /opt/s/w/ir/x/w/flutter_conductor_checkouts/framework
Cloning into '/opt/s/w/ir/x/w/flutter_conductor_checkouts/framework'...
13:31:21.234344 run-command.c:654       trace: run_command: unset GIT_DIR; GIT_PROTOCOL=version=2 ssh -o SendEnv=GIT_PROTOCOL git@github.com 'git-upload-pack '\''flutter/flutter.git'\'''
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8802834422048794577/+/u/Verify_binaries_codesigned/verify_binaries_codesigned/test_stderr

**Comment by christopherfujino** [comment] 2022-09-16 20:57
Related https://github.com/flutter/flutter/issues/95297

**Comment by keyonghan** [comment] 2022-09-20 16:40
> cc @XilaiZhang I think you should fix this when fixing https://github.com/flutter/flutter/issues/95297

Based on this, marking as duplicate of https://github.com/flutter/flutter/issues/95297.

**Closed by keyonghan** 2022-09-20 16:40 UTC
Labels: team: infra, P2
