### ISSUE TITLE
Flutter driver appears to be broken on web

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#67560] opened 2020-10-07 20:52 UTC
This is causing tree closures on engine and plugins

/cc @jonahwilliams (because I think it might be related to your nullsafety PR)

@jason-simmons is bisecting right now AFAIK.

/cc @zanderso @liyuqian @yjbanov

**Comment by dnfield** [comment] 2020-10-07 20:53
If we do not currently have a `flutter driver` based web test in the framework we should add one, and if we do we need to add one that fails the way the engine/plugins repo is seeing.

**Comment by dnfield** [comment] 2020-10-07 20:58
Re-opening and reducing priority to p1 per @jonahwilliams' comment in linked PR (we need to get test coverage for this failure in the framework repo)

**Comment by Piinks** [comment] 2020-10-07 20:58
This is blocking https://github.com/flutter/flutter/pull/67468 too. (I was just about to file an issue 😅 )

**Comment by yjbanov** [comment] 2020-10-07 21:02
I am adding a driver test in https://github.com/flutter/flutter/pull/67324, but I thought we already had one.

/cc @nturgut @angjieli

**Comment by jonahwilliams** [comment] 2020-10-07 21:04
Assigned @yjbanov for this one. please let me know when it is landed so I can re-land the driver migration

**Comment by yjbanov** [comment] 2020-10-07 21:17
We already have a test for Flutter Driver for web: https://github.com/flutter/flutter/tree/master/examples/hello_world/test_driver. I'm not sure how my additional test (which I'm writing with a totally different motivation) can help.

**Comment by jonahwilliams** [comment] 2020-10-07 21:20
We reverted the driver migration because it apparently broke flutter web driver tests, though nothing in the framework failed.

**Comment by jonahwilliams** [comment] 2020-10-07 21:20
So we either need a framework test that exercises the driver in the same way to trigger a failure, or all web driver tests need to be deleted. @dnfield can you share the error logs from the test that failed?

**Comment by Piinks** [comment] 2020-10-07 21:21
These are the error logs from #67468 https://cirrus-ci.com/task/5921209307103232

**Comment by yjbanov** [comment] 2020-10-07 21:28
Perhaps the problem is that we're not running this test on engine PRs?

**Comment by jonahwilliams** [comment] 2020-10-07 21:30
Nothing in the framework repo failed on postsubmit for that migration PR

**Comment by angjieli** [comment] 2020-10-07 21:33
Based on the error log provided by @Piinks, the test is failing because we do not have a ChromeDriver running. 
Do we have more logs?

**Comment by yjbanov** [comment] 2020-10-07 21:35
From the logs, it seems we fail to fetch the chromedriver, but then keep on trucking:

```
lib/web_driver_installer.dart: Warning: Interpreting this as package URI, 'package:web_driver_installer/web_driver_installer.dart'.
INFO: chrome version in use Google Chrome 86.0.4240.75 
downloading file from https://chromedriver.storage.googleapis.com/null/chromedriver_linux64.zip
Exception during install Exception: Failed to unzip the downloaded Chrome driver chromedriver/chromedriver_linux64.zip.
With the driver path chromedriver
The unzip process exited with code 9.
```

At this point the test should have stopped. But it kept going:

```
chromedriver/chromedriver --port=4444 &
sleep 5
/tmp/scripts5526a41a9504680b4e7c8b763a1b1d49.sh: line 11: chromedriver/chromedriver: No such file or directory
cd ../../../examples/hello_world/
flutter drive --target=test_driver/smoke_web_engine.dart -d web-server --profile --browser-name=chrome
Downloading Web SDK...                                              2.3s
```

**Comment by angjieli** [comment] 2020-10-07 21:38
Ran out of resource and couldn't extract the chromedriver?

**Comment by yjbanov** [comment] 2020-10-07 21:40
https://github.com/flutter/flutter/pull/67564 should make such failures clearer (but does not fix this issue)

**Comment by yjbanov** [comment] 2020-10-07 21:42
> Ran out of resource and couldn't extract the chromedriver?

Doesn't look like it. It simply tries to download from an invalid URL: https://chromedriver.storage.googleapis.com/null/chromedriver_linux64.zip (note the "null" in the URL)

**Comment by yjbanov** [comment] 2020-10-07 21:48
I know what happened. I think we rebuilt the Docker image and picked up Chrome 86, for which we don't have a chromedriver yet. https://github.com/flutter/web_installers/blob/master/packages/web_drivers/driver_version.yaml

**Comment by yjbanov** [comment] 2020-10-07 21:56
https://github.com/flutter/web_installers/pull/21 should temporarily fix the driver issue. However, this is not sustainable. I will file an issue to improve it.

**Comment by yjbanov** [comment] 2020-10-07 22:10
Filed https://github.com/flutter/flutter/issues/67569

**Comment by yjbanov** [comment] 2020-10-07 23:07
web_smoke_test is passing in https://github.com/flutter/flutter/pull/67468 now. Closing.

**Comment by dnfield** [comment] 2020-10-07 23:16
Re-opening to track failures related to `felt test --browser=firefox`.

@jonahwilliams - if you re-land the NNBD changes, we need to make sure they don't break firefox.

**Comment by jonahwilliams** [comment] 2020-10-07 23:18
@yjbanov can you find an owner for the FF investigation?

**Comment by jason-simmons** [comment] 2020-10-07 23:22
The Firefox issue happens when running `dev/felt.dart test --browser firefox` using a framework tree containing https://github.com/flutter/flutter/commit/d411242468773a800945f0d8c6cfcf40c7ea8e44

Example log:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867140806173595232/+/steps/felt_test_firefox/0/stdout

The test starts showing a stream of errors like:
```
1602033985667	webdriver::server	DEBUG	-> POST /session/784010f5-2515-4406-ab3b-319f3e2547ad/execute/sync {"script":"return $flutterDriverResult","args":[]}
1602033985668	Marionette	DEBUG	0 -> [0,8,"WebDriver:ExecuteScript",{"args":[],"script":"return $flutterDriverResult"}]
1602033985688	Marionette	DEBUG	0 <- [1,8,{"error":"javascript error","message":"ReferenceError: $flutterDriverResult is not defined","stacktrace":"@http://localhost:46303/:2:7\n@http://localhost:46303/:3:8\n"},null]
1602033985689	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"javascript error","message":"ReferenceError: $flutterDriverResult is not defined","stacktrace":"@http://localhost:46303/:2:7\n@http://localhost:46303/:3:8\n"}}
JavaScript warning: http://localhost:46303/main.dart.js, line 3: unreachable code after return statement
```

**Comment by ditman** [comment] 2020-10-08 16:34
Comparing a [good](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866995548825643104/+/steps/felt_test_firefox/0/stdout) vs a [bad](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867140806173595232/+/steps/felt_test_firefox/0/stdout) execution, it seems they start to differ here:

Bad: 

```
1602034405337	Marionette	DEBUG	0 -> [0,7,"WebDriver:ExecuteScript",{"args":[],"script":"window.$flutterDriver('{\"command\":\"request_data\",\"timeout\":\"60000\",\"message\":\"null\"}')"}]
JavaScript error: http://localhost:39851/main.dart.js, line 5148: : Bad state: This type of status does not exist: null
1602034405354	Marionette	DEBUG	0 <- [1,7,null,{"value":null}]
```

Good:

```
1602172895837	Marionette	DEBUG	0 -> [0,7,"WebDriver:ExecuteScript",{"args":[],"script":"window.$flutterDriver('{\"command\":\"request_data\",\"timeout\":\"60000\",\"message\":null}')"}]
1602172895850	Marionette	DEBUG	0 <- [1,7,null,{"value":null}]
```

Investigating:

**JavaScript error: http://localhost:39851/main.dart.js, line 5148: : Bad state: This type of status does not exist: null**

**Comment by nturgut** [comment] 2020-10-08 16:49
I think the NNBD issue 

> I am adding a driver test in #67324, but I thought we already had one.
> 
> /cc @nturgut @angjieli

We had a driver tests. The issue is the way we are using flutter driver with e2e. Since it is unique to engine integration tests we haven't had any test on the flutter/flutter repo. It was obviously a mistake though. I'll copy one of the engine integration tests to the flutter flutter repo to guard against the future changes.

**Comment by nturgut** [comment] 2020-10-08 16:55
More observations

1) even though this issue is discussed as firefox, the problem would have occurred in chrome as well. On LUCI recipe we run firefox step earlier than the chrome step therefore the error was on firefox.
2) all PRs that are synced to head should be good to now. 
3) I'll add a test to flutter/flutter to make sure we can resubmit https://github.com/flutter/flutter/pull/67441 without any breakages. 

I'm dropping the priority.

**Comment by ditman** [comment] 2020-10-08 20:13
The State Error is being thrown from here:

https://github.com/flutter/plugins/blob/master/packages/integration_test/lib/common.dart#L206

_(I'm still not sure how we're getting to the point that we get a null DriverTestMessage)_

**Comment by ditman** [comment] 2020-10-08 21:50
OK, I've added a bunch of string operations (toUpperCase, length, and runtimeType) to the `status` variable, and it seems we're indeed receiving a `'null'` String (and not proper `null`):

`Bad state: This type of status does not exist: NULL (String, 4 characters)`

**Comment by nturgut** [comment] 2020-10-08 21:56
We are registering the web service extension here: https://github.com/flutter/plugins/blob/master/packages/integration_test/lib/_extension_web.dart#L21

Looks like we should reconsider [this line](https://github.com/flutter/flutter/pull/67441/files#diff-3424eff76cbb29c64dd79c768fea488cR29) if we want a correct javascript added to the browser

**Comment by nturgut** [comment] 2020-10-08 21:58
Another solution, we can also check for 'null' in the integration_test package? wdyt?

**Comment by jonahwilliams** [comment] 2020-10-08 22:00
Good find! Looks like the fix would be to avoid inserting the message if it is null, instead of converting to a string.

Is there a test running in the repo currently that exercises this?

**Comment by ditman** [comment] 2020-10-08 22:05
(I double-checked the calls above, and the difference between `\"null\"` and `null` is now very painfully obvious 🤦‍♂️

**Comment by nturgut** [comment] 2020-10-08 22:26
> Good find! Looks like the fix would be to avoid inserting the message if it is null, instead of converting to a string.
> 
> Is there a test running in the repo currently that exercises this?

Nope, I'm adding one but these are the changes I need to make so it might take some time:

-> add a new validation to the recipes
-> add this as a new builder to flutter/infra
-> add this change to try builds under flutter/flutter

**Comment by ditman** [comment] 2020-10-08 22:27
Just ran @jonahwilliams' fix, and this is the log now:

```
   "script": "window.$flutterDriver('{\"command\":\"request_data\",\"timeout\":\"60000\"}')"
```

No `null` or `\"null\"`, but accessing a non existing key from a map returns null, so we're good!

**Closed** 2020-10-09 00:42 UTC
Labels: P2, a: null-safety, a: tests, engine, framework, passed first triage, platform-web, plugin, t: flutter driver

**Comment by nturgut** [comment] 2020-10-09 00:47
I'm adding tests to make sure this won't happen again. I will be referencing this issue. Please feel free to add comments on the PRs!

**Comment by nturgut** [comment] 2020-10-09 23:08
The tests are up and running https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_e2e_test/2
