### ISSUE TITLE
[tool_crash] SocketException: The remote computer refused the network connection., OS Error: The remote computer refused the network connection., errno = 1225

### ISSUE THREAD

**Issue by Mahmouddsameer** [flutter/flutter#153330] opened 2024-08-13 02:14 UTC
## Command
```sh
flutter run --machine --start-paused -d edge --devtools-server-address http://127.0.0.1:9103/ --target C:\Users\DELL\StudioProjects\Myegstay_mangment\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: The remote computer refused the network connection.
, OS Error: The remote computer refused the network connection.
, errno = 1225
```console
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22)
#4      Socket.startConnect (dart:io/socket.dart:825:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2632:48)
#10     ChromeConnection.getUrl (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:108:33)
#11     ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:53:26)
#12     ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:90:31)
#13     Chromium.close (package:flutter_tools/src/web/chrome.dart:510:53)
#14     ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:164:20)
#15     ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:203:27)
<asynchronous suspension>
#16     ResidentWebRunner.cleanupAtFinish (package:flutter_tools/src/isolated/resident_web_runner.dart:191:5)
<asynchronous suspension>
#17     ResidentRunner.waitForAppToFinish (package:flutter_tools/src/resident_runner.dart:1482:5)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:788:26)
<asynchronous suspension>
#19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
    • Flutter version 3.24.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (13 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code (version 1.92.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.95.20240801

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.100
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 127.0.2651.98

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
cloud_firestore-5.1.0
cloud_firestore_web-4.0.3
firebase_auth-5.1.2
firebase_auth_web-5.12.4
firebase_core-3.3.0
firebase_core_web-2.17.4
firebase_messaging-15.0.4
firebase_messaging_web-3.8.12
path_provider-2.1.3
path_provider_android-2.2.7
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
pointer_interceptor-0.10.1+1
pointer_interceptor_ios-0.10.1
pointer_interceptor_web-0.10.2
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.8
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
webview_flutter-4.8.0
webview_flutter_android-3.16.4
webview_flutter_wkwebview-3.14.0

**Comment by huycozy** [comment] 2024-08-13 05:37
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153064.

**Closed by huycozy** 2024-08-13 05:37 UTC
Labels: in triage
