### ISSUE TITLE
Runner/GeneratedPluginRegistrant.m:10:9: Module 'apple_sign_in' not found  showing this error in xcode

### ISSUE THREAD

**Issue by umairali4433** [flutter/flutter#61520] opened 2020-07-15 07:31 UTC

**Comment by TahaTesser** [comment] 2020-07-15 09:48
Hi @umairali4433 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/tomgilder/flutter_apple_sign_in/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-15 09:48 UTC
