### ISSUE TITLE
build_benchmark_second_debug_build regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#37175] opened 2019-07-29 15:43 UTC
Time's nearly doubled since https://github.com/flutter/flutter/commit/51d2d3511c11f6b101f97ff28864d204313b4e4b.

**Comment by jonahwilliams** [comment] 2019-07-29 16:36
I've re re re disabled the kernel finger print due to https://github.com/flutter/flutter/issues/16604. This will be addressed via flutter assemble, but ultimately is not resolvable until that is landed

**Comment by franciscojma86** [comment] 2019-08-03 00:04
Regression re-introduced by https://github.com/flutter/flutter/commit/99fe0d078b7698e8f6f0f51344fe6c67c29ae6c9. 
@jason-simmons

**Comment by franciscojma86** [comment] 2019-08-03 00:06
after_config_change_build_debug_millis is also affected.

**Comment by jonahwilliams** [comment] 2019-08-05 15:34
I'm removing this from benchmark, as it is due to a bug fix from above. It is not a today issue

**Comment by liyuqian** [comment] 2019-09-30 22:50
Shall we close this as the benchmark is removed?

**Comment by liyuqian** [comment] 2019-11-21 00:44
Closing this issue as the benchmark is removed and there's no objection of closing.

**Closed by liyuqian** 2019-11-21 00:44 UTC
Labels: severe: performance, severe: regression
