### ISSUE TITLE
Horizontal ListView item with particular size takes parent size unless wrapped with Center widget

### ISSUE THREAD

**Issue by phanirithvij** [flutter/flutter#56028] opened 2020-04-30 09:53 UTC
The cookbook contains this sample https://flutter.dev/docs/cookbook/lists/horizontal-list .
```dart
        body: Container(
          margin: EdgeInsets.symmetric(vertical: 20.0),
          height: 200.0,
          child: ListView(
            scrollDirection: Axis.horizontal,
            children: <Widget>[
              Container(
                width: 160.0,
                color: Colors.red,
              ),
              ...
```
This makes the children height `200` but not the intended `160`.
 I think this is a bug. A StackOverflow [question on this](https://stackoverflow.com/q/50155738/8608146) with no answers.

**Comment by TahaTesser** [comment] 2020-04-30 10:49
Hi @phanirithvij 
Container with `height: 200.0,` for `ListView` horizontal, you cannot have `ListView` without a defined size  snd `width: 160.0` is listitem size 

Container
![flutter_01](https://user-images.githubusercontent.com/48603081/80702160-3db7bf80-8afe-11ea-9475-719efc803d52.png)

Item
![flutter_02](https://user-images.githubusercontent.com/48603081/80702162-3ee8ec80-8afe-11ea-85e0-9f3aa5d1bcc8.png)

This isn't a big, Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by phanirithvij** [comment] 2020-04-30 11:09
@TahaTesser thanks for your response but something like this gives the children 200 height but not 100 height

```dart
                      Container(
                        height: 200,
                        color: Colors.teal,
                        child: ListView(
                          padding: EdgeInsets.zero,
                          scrollDirection: Axis.horizontal,
                          children: <Widget>[
                            Container(
                                width: 100, height: 100, color: Colors.black),
                            Container(
                                width: 100, height: 100, color: Colors.blue),
                            Container(
                                width: 100, height: 100, color: Colors.black),
                            Container(
                                width: 100, height: 100, color: Colors.blue),
                          ],
                        ),
                      ),
```

![Screenshot_2020_04_30_16_36_42_22_0219d4c5888c6c39c266fd3e6f4e57e12](https://user-images.githubusercontent.com/29627898/80703782-0e568200-8b01-11ea-9887-6846b3610d34.jpg)
![Screenshot_2020-04-30-16-36-59-85](https://user-images.githubusercontent.com/29627898/80703775-0ac2fb00-8b01-11ea-9adf-ac46713e05cf.jpg)

**Comment by goderbauer** [comment] 2020-05-06 22:22
This is working as intended, the ListView always fills all available space, hence it is 200px tall and it forces it's children to always fill out the cross-direction, see the documentation: https://master-api.flutter.dev/flutter/widgets/ListView-class.html

>  In the cross axis, the children are required to fill the ListView.

If you don't want this, you can wrap the children in an Align widget (or Center widget).

**Closed by goderbauer** 2020-05-06 22:22 UTC
Labels: d: api docs, d: cookbook, documentation, f: scrolling, found in release: 1.18, framework, has reproducible steps
