### ISSUE TITLE
Apple is now blocking apps that use webview_flutter_wkwebview because of non-public API usage

### ISSUE THREAD

**Issue by PedroBatista** [flutter/flutter#105515] opened 2022-06-07 11:16 UTC
Hi,

All of sudden after WWDC's presentation Apple has begun to reject apps that use Webview:

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/webview_flutter_wkwebview.framework/webview_flutter_wkwebview: estimatedProgress, initWithFrame:configuration:, isMainFrame, setNavigationDelegate:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

I'm using the latest version: webview_flutter: ^3.0.4

Is there any know way to get around this until it's fixed?

**Comment by stuartmorgan** [comment] 2022-06-07 11:37
Duplicate of https://github.com/flutter/flutter/issues/105472

**Closed by stuartmorgan** 2022-06-07 11:37 UTC
