### ISSUE TITLE
Can't get MediaQuery.of(context).viewInsets.bottom anymore

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#24685] opened 2018-11-23 18:50 UTC
Sometime ago (version 0.8.something) I used to be able to get `MediaQuery.of(context).viewInsets.bottom`.

That would be `0.0` when the keyboard was closed, and some other value when the keyboard was open. Now I always get `0.0`, no matter if the keyboard is open or not.

I'm using the Android Emulator.

Flutter Doctor:
```
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] Connected device (1 available)
```

**Comment by marcglasberg** [comment] 2018-11-23 18:59
Seems related to https://github.com/flutter/flutter/issues/23421

**Comment by zoechi** [comment] 2018-11-26 08:17
With 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _focusNode = FocusNode();

  @override
  void initState() {
    super.initState();
    _focusNode.addListener(() {
      final mq = MediaQuery.of(context);
      print(mq.viewInsets.bottom);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            MaterialButton(
                onPressed: () {
                  final mq = MediaQuery.of(context);
                  print(mq.viewInsets.bottom);
                },
                child: Text('Press me')),
            TextField(focusNode: _focusNode)
          ],
        ),
      ),
    );
  }
}
```
I get `viewInsets.bottom = 249.0` in `onPressed` when the keyboard is shown but `0.0` in the listener added in `initState()` because at this point the keyboard hasn't animated in yet.

What devices did you try? (ios, Android, emulator, real device)

**Comment by marcglasberg** [comment] 2018-11-26 16:16
I just tested with your code and, yes, I only get 0.0.

I'm using the Android emulator, with "Android 8.1 (Google Api)". In more detail:

    5.1 1440x2690 xxxhdpi
    Android 8.1 x86 
    Portrait
    Graphics: Hardware - GLES 2.0
    RAM 1536
    VM heap: 512
    Internal Storage: 800
    SD card: Studio-managed 256 Mb
    Keyboard: Enable keyboard input

**Comment by marcglasberg** [comment] 2018-11-26 16:21
Now, I have tested with a Galaxy S7 - SM-G030F. Android 8.0.0 (9.0 Samsung Experience)

And I get the same behavior.

**Comment by marcglasberg** [comment] 2018-12-06 17:23
@zoechi A question: Are you able to reproduce this? You labeled this as device-specific.

**Comment by zoechi** [comment] 2018-12-06 17:43
@marcglasberg I can't reproduce and my guess was that this is because it behaves differently on different devices.

**Comment by marcglasberg** [comment] 2018-12-06 21:13
Ok, we found the problem: https://github.com/flutter/flutter/issues/25050

**Comment by zoechi** [comment] 2018-12-07 06:18
Can we close this issue then?

**Comment by marcglasberg** [comment] 2018-12-13 16:43
Yes, please.

**Closed** 2018-12-13 18:03 UTC
Labels: e: device-specific, engine, framework, severe: regression
