### ISSUE TITLE
Horizontal and vertical scrollbars are shown only when it reaches the max scroll extend in nested scrolling.

### ISSUE THREAD

**Issue by RenugaSadagoban98** [flutter/flutter#86428] opened 2021-07-14 15:53 UTC
Hi Team,
I have used nested scrollbar and enable isAlwaysShown property as true in both scrollbars. When I scrolling vertically and horizontally, the horizontal scroll bar is not visible. When I scrolling the vertical scrollbar to max extend then the horizontal scrollbar getting into visible.

Please run the below code snippet,

<details> 
<summary>code snippet</summary> 

```dart
class NestedScrolling extends StatefulWidget {
  const NestedScrolling({Key? key}) : super(key: key);
  @override
  _NestedScrollingState createState() => _NestedScrollingState();
}
class _NestedScrollingState extends State<NestedScrolling> {
  ScrollController verticalController = ScrollController(),
      horizontalController = ScrollController();
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Scrollbar(
        isAlwaysShown: true,
        controller: verticalController,
        child: SingleChildScrollView(
          controller: verticalController,
          scrollDirection: Axis.vertical,
          child: Scrollbar(
            isAlwaysShown: true,
            controller: horizontalController,
            child: SingleChildScrollView(
              controller: horizontalController,
              scrollDirection: Axis.horizontal,
              child: Container(
                child: Column(
                  children: List.generate(
                      50,
                      (index) => Row(
                          children: List.generate(
                              20,
                              (index) => Container(
                                  width: 100,
                                  height: 100,
                                  alignment: Alignment.center,
                                  decoration: BoxDecoration(
                                      border: Border.all(
                                          color: Colors.grey.withOpacity(0.45),
                                          width: 1.0)),
                                  child: Text('Cell ${index}'))))),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
``` 

</details>

**Expected results:** 

Horizontal scrollbar should be shown even if the vertical scrolling doesn't reach the max scroll extend.

**Actual results:** 
Horizontal scrollbar shows only if the vertical scrolling reaches the max scroll extend.

**Demo video**

https://user-images.githubusercontent.com/77044081/125658006-bbb074d3-79e3-4b9c-922d-f92102367733.mp4

**Comment by maheshmnj** [comment] 2021-07-15 07:19
Hi @RenugaSadagoban98,
Thanks for filing the issue, could you please share the output of ```flutter doctor -v```.

**Comment by maheshmnj** [comment] 2021-07-15 07:24
Reproducible on the latest stable and the master channel, The horizontal scrollbar remains hidden until the list reaches vertically at the bottom. The horizontal scrollbar should be visible when the list scrolls horizontally.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```
[✓] Flutter (Channel master, 2.4.0-1.0.pre.149, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.4.0-1.0.pre.149 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d71c0eb1d8 (6 days ago), 2021-07-09 06:01:04 -0400
    • Engine revision 024cc455fe
    • Dart version 2.14.0 (build 2.14.0-293.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2021-07-15 09:42
There is already a similar issue addressing this case, Closing this issue as duplicate of https://github.com/flutter/flutter/issues/86399. You may follow up there fore further updates.
Feel free to comment if you disagree, And I will reopen it. 

Thank you.

**Closed by maheshmnj** 2021-07-15 09:42 UTC
Labels: f: material design, f: scrolling, found in release: 2.2, found in release: 2.4, framework, has reproducible steps

**Comment by Abhijit-Revamp** [comment] 2021-07-15 09:48
@maheshmnj
the referenced one is a feature request. However, this is a defect and severe one of you are on DESKTOP WEB without trackpad.

Scrolling is impossible

**Comment by maheshmnj** [comment] 2021-07-15 09:55
@Abhijit-Revamp both issues seem to address the exact same thing for the web, So I don't see a point to have two different issues for the same case. And regarding the proposal/issue it will be modified before the issue is prioritized to work on.

**Comment by Abhijit-Revamp** [comment] 2021-07-15 09:57
Perfectly agree if the understanding is similar and other will carry appropriate priority (not to be deferred infinitely)
