### ISSUE TITLE
ListView jank when app resumed from background

### ISSUE THREAD

**Issue by m-j-g** [flutter/flutter#98886] opened 2022-02-21 22:08 UTC
This is something I noticed a while back and applies to any screen on any app, so it isn't specific to the version of flutter that was just released today.

I've provided a code sample below, but any screen with a ListView will work.  

1.) Install a release version of the app on **iOS (not sure about Android)**
2.) Run app, and then send the app to the background
3.) Click the app icon to bring the app back up from the background and immediately swipe up or down.
4.) You will see jank on the scroll.

Additional notes:
1.) After resuming the app, if you pause for half a second before swiping then you will not see jank.
2.) You will continue to get jank until you stop scrolling for half a second.  Meaning if you click the app icon to resume the already running app, and you swipe immediately, and keep swiping then you will keep getting jank for many seconds.
3.) This is the weirdest one: If you are doing a screen record IT DOES NOT JANK.  I figured this out when trying to create a screen recording of the issue.  
3.b.) I'm not sure what starting a screen recording does that resolves this issue, but Native iOS apps don't have this issue either way.
4.) It may seem like a minor issue, but in practice, users regularly start scrolling as soon as they resume apps with lists of data, which hurts the perceived quality of the app.  

Here is a minimum code sample that you can plug into a new flutter project:
```
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemCount: 200,
        itemBuilder: (BuildContext context, int index) {
          return Container(
            height: 100,
            color: index.isEven ? Colors.grey.shade600 : Colors.grey.shade800,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      index.toString() + ' line of text',
                      style: const TextStyle(color: Colors.white),
                    ),
                    const SizedBox(height: 32),
                    Text(
                      index.toString() + ' line of text',
                      style: const TextStyle(color: Colors.white),
                    ),
                  ],
                ),
                const SizedBox(
                  width: 32,
                ),
                Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      index.toString() + ' line of text',
                      style: const TextStyle(color: Colors.white),
                    ),
                    const SizedBox(height: 32),
                    Text(
                      index.toString() + ' line of text',
                      style: const TextStyle(color: Colors.white),
                    ),
                  ],
                )
              ],
            ),
          );
        },
      ),
    );
  }
}
```

Flutter doctor --verbose
```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
    • Flutter version 2.10.2 at /Users//flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users//Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
```

**Comment by darshankawar** [comment] 2022-02-22 07:27
@m-j-g 
I tried to replicate on iOS device in release mode using latest stable and master, but was unable to replicate the jank behavior you reported.


https://user-images.githubusercontent.com/67046386/155082982-b98e06fa-6e78-4d2e-9655-3f2e1413ce92.MP4


`Channel stable, 2.10.2`
`Channel master, 2.11.0-0.0.pre.634`

However, I see a similar / related issue describing same case as yours, https://github.com/flutter/flutter/issues/96381. Please check that because the author of that issue does mention that they see a jank on scroll behavior after coming back from background. https://github.com/flutter/flutter/issues/96381#issuecomment-1009645653

Also this is similar, but including add2app behavior: https://github.com/flutter/flutter/issues/80367

**Comment by m-j-g** [comment] 2022-02-22 12:33
Ahh yes. It does seem to be the same issue as https://github.com/flutter/flutter/issues/96381 

I’m using an iPhone 11 Pro which falls in line with their discovery that it happens on iphoneX and later.

**Comment by darshankawar** [comment] 2022-02-22 12:54
Closing this as a duplicate of https://github.com/flutter/flutter/issues/96381

**Closed by darshankawar** 2022-02-22 12:54 UTC
Labels: in triage
