### ISSUE TITLE
Fatal deprecation warnings after upgrading to gradle plugin 3.0.0

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10629] opened 2017-06-12 19:11 UTC
I'm using Android Studio 3.0 preview 3. I've updated my top-level gradle to use v3.0.0-alpha3 for the Android gradle plugin. I receive the following deprecation warnings that prevent me from building an apk.

```
'Running 'gradle assembleRelease'...                       
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
Configuration 'profileCompile' in project ':app' is deprecated. Use 'profileImplementation' instead.
Configuration 'releaseCompile' in project ':app' is deprecated. Use 'releaseImplementation' instead.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Configuration 'compile' in project ':firebase_analytics' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':firebase_analytics' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':firebase_analytics' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'compile' in project ':firebase_database' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':firebase_database' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':firebase_database' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'debugProvided' in project ':path_provider' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':path_provider' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'compile' in project ':permit' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':permit' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':permit' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'debugProvided' in project ':url_launcher' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':url_launcher' is deprecated. Use 'releaseCompileOnly' instead.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all dependencies for configuration ':app:profileCompileClasspath'.
   > Unable to find a matching configuration of project :firebase_analytics:
       - Configuration 'debugApiElements':
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'AndroidTypeAttr{name=Aar}' and found compatible value 'AndroidTypeAttr{name=Aar}'.
           - Required com.android.build.gradle.internal.dependency.BuildTypeAttr 'BuildTypeAttr{name=profile}' and found incompatible value 'BuildTypeAttr{name=debug}'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'VariantAttr{name=debug}' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'for compile' and found compatible value 'for compile'.
       - Configuration 'debugRuntimeElements':
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'AndroidTypeAttr{name=Aar}' and found compatible value 'AndroidTypeAttr{name=Aar}'.
           - Required com.android.build.gradle.internal.dependency.BuildTypeAttr 'BuildTypeAttr{name=profile}' and found incompatible value 'BuildTypeAttr{name=debug}'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'VariantAttr{name=debug}' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'for compile' and found incompatible value 'for runtime'.
       - Configuration 'releaseApiElements':
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'AndroidTypeAttr{name=Aar}' and found compatible value 'AndroidTypeAttr{name=Aar}'.
           - Required com.android.build.gradle.internal.dependency.BuildTypeAttr 'BuildTypeAttr{name=profile}' and found incompatible value 'BuildTypeAttr{name=release}'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'VariantAttr{name=release}' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'for compile' and found compatible value 'for compile'.
       - Configuration 'releaseRuntimeElements':
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'AndroidTypeAttr{name=Aar}' and found compatible value 'AndroidTypeAttr{name=Aar}'.
           - Required com.android.build.gradle.internal.dependency.BuildTypeAttr 'BuildTypeAttr{name=profile}' and found incompatible value 'BuildTypeAttr{name=release}'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'VariantAttr{name=release}' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'for compile' and found incompatible value 'for runtime'.
```

==========

Flutter doctor:
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision 0f277fcc8a (6 days ago), 2017-06-06 17:19:27 +0200
    • Engine revision 8686a45810
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29
```

**Comment by eseidelGoogle** [comment] 2017-06-13 06:37
FYI @jason-simmons @mit-mit

**Comment by mit-mit** [comment] 2017-06-13 13:04
We are working on resolving this; for now can you see if this workaround resolves the issue for you for now: https://github.com/flutter/flutter/issues/10236#issuecomment-303029027

**Comment by alardizabal** [comment] 2017-06-13 15:12
@mit-mit I updated flutter config to point to an earlier version of Gradle (3.3 - previously 3.5).

```
Settings:
  gradle-dir: /usr/local/Cellar/gradle/3.3
```

I still get the below after flutter build apk.

```
☆ flutter build apk
Running 'gradle assembleRelease'...                       
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
Configuration 'profileCompile' in project ':app' is deprecated. Use 'profileImplementation' instead.
Configuration 'releaseCompile' in project ':app' is deprecated. Use 'releaseImplementation' instead.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Configuration 'compile' in project ':firebase_analytics' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':firebase_analytics' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':firebase_analytics' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'compile' in project ':firebase_database' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':firebase_database' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':firebase_database' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'debugProvided' in project ':path_provider' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':path_provider' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'compile' in project ':permit' is deprecated. Use 'implementation' instead.
Configuration 'debugProvided' in project ':permit' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':permit' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'debugProvided' in project ':url_launcher' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':url_launcher' is deprecated. Use 'releaseCompileOnly' instead.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all dependencies for configuration ':app:profileCompileClasspath'.
   > Unable to find a matching configuration in project :firebase_analytics:
       - Configuration 'debugApiElements':
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'AndroidTypeAttr{name=Aar}' and found compatible value 'AndroidTypeAttr{name=Aar}'.
           - Required com.android.build.gradle.internal.dependency.BuildTypeAttr 'BuildTypeAttr{name=profile}' and found incompatible value 'BuildTypeAttr{name=debug}'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'VariantAttr{name=debug}' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'for compile' and found compatible value 'for compile'.
       - Configuration 'debugRuntimeElements':
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'AndroidTypeAttr{name=Aar}' and found compatible value 'AndroidTypeAttr{name=Aar}'.
           - Required com.android.build.gradle.internal.dependency.BuildTypeAttr 'BuildTypeAttr{name=profile}' and found incompatible value 'BuildTypeAttr{name=debug}'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'VariantAttr{name=debug}' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'for compile' and found incompatible value 'for runtime'.
       - Configuration 'releaseApiElements':
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'AndroidTypeAttr{name=Aar}' and found compatible value 'AndroidTypeAttr{name=Aar}'.
           - Required com.android.build.gradle.internal.dependency.BuildTypeAttr 'BuildTypeAttr{name=profile}' and found incompatible value 'BuildTypeAttr{name=release}'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'VariantAttr{name=release}' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'for compile' and found compatible value 'for compile'.
       - Configuration 'releaseRuntimeElements':
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'AndroidTypeAttr{name=Aar}' and found compatible value 'AndroidTypeAttr{name=Aar}'.
           - Required com.android.build.gradle.internal.dependency.BuildTypeAttr 'BuildTypeAttr{name=profile}' and found incompatible value 'BuildTypeAttr{name=release}'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'VariantAttr{name=release}' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'for compile' and found incompatible value 'for runtime'.
```

**Comment by mit-mit** [comment] 2017-06-13 15:18
Hmm, note sure what is going on. cc @jason-simmons @jakobr-google

**Comment by jakobr-google** [comment] 2017-06-13 15:39
I think the problem is the upgraded version of the Android Gradle plugin, not the version of Gradle used to build.

The deprecation notices *should* just be warnings (that we'll need to address eventually), so it looks like the real error is that it can't find a configuration of :firebase_analytics that matches our requirements (usage=compile, buildType=profile). 

Plugin libraries currently only have debug and release variants, which worked fine with the old Android plugin, but apparently something's changed there in the newer Android plugin.

We should investigate either adding a profile variant to plugins, or having the profile variant of the app depend on the release variant of the plugin.

**Comment by lukef** [comment] 2017-06-13 18:48
Should we log a separate issue for the deprecations or is that included in the fix? I can confirm that downgrading gradle resolved the impasse, but we'd obviously like the broader issue fixed :)

**Comment by Hixie** [comment] 2017-06-13 21:00
Yes please do file a separate bug for that issue. Is the issue in this bug resolved to your satisfaction?

**Comment by eseidelGoogle** [comment] 2017-06-15 23:46
@lukef my understanding is your team has moved back to gradle plugin 2.3 and this is no longer an immediate blocker?  Is that correct?

**Comment by lukef** [comment] 2017-06-15 23:59
Correct. We still would like it to be fixed but we can move forward without it.

**Comment by mit-mit** [comment] 2017-06-29 11:05
We are tracking the official support for Android Studio 3.0 (and the final gradle versions it ends up shipping with) in https://github.com/flutter/flutter/issues/10992. Closing this bug.

**Closed by mit-mit** 2017-06-29 11:05 UTC
Labels: customer: posse (eap), dev: tool - gradle, ▣ platform-android

**Comment by asaarnak** [comment] 2017-08-04 10:44
Linking a migration guide to Android Studio 3.0.
https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html
Since `com.android.tools.build:gradle:3.0.0-alpha5` atleast Gradle 4.1 is required.

Just some ideas:
What do you think about creating dedicated Flutter channel, would it be good for testing this issue earlier and ease the migration later?
And maybe even set Flutter minimum Gradle version 4.1 to sync with Android Stuido 3.0 as Flutter itself is also in alpha version? This hopefully helps migrations in future.
When Android Studio is in stable, people already expect it to work.
