### ISSUE TITLE
Text capitalisation doesn't work correctly 

### ISSUE THREAD

**Issue by perfoWorks** [flutter/flutter#59869] opened 2020-06-19 17:41 UTC
I have made simple reproducible code

```dart
Column(
        children: <Widget>[
          TextFormField(textCapitalization: TextCapitalization.words),
          TextFormField(textCapitalization: TextCapitalization.none),
          TextFormField(textCapitalization: TextCapitalization.none)
        ],
      ),
```

**Problem:** When you click on first text field the shift key on keyboard is activated and it stay activated in all three text fields if you don't write anything. If you press done button (deactivate keyboard) and press on second textfield then shift keyboard is off on all three text fields

**doctor** 

```console
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.4 at /Users/peter/development/tools/flutter
    • Framework revision 1ad9baa8b9 (2 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/peter/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • F933AAC4-9E3C-4026-B525-E2D39F4704A8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

**Comment by iapicca** [comment] 2020-06-22 09:02
Hi @perfoWorks 
I cannot reproduce the issue you are experiencing with the code below
<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MyApp(),
    );

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);
  static const MyHomePage _home = MyHomePage();
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: _home,
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => SafeArea(
        child: Material(
          child: Column(
            children: <Widget>[
              Column(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: <Widget>[
                  TextFormField(textCapitalization: TextCapitalization.words),
                  TextFormField(textCapitalization: TextCapitalization.none),
                  TextFormField(textCapitalization: TextCapitalization.none)
                ],
              ),
            ],
          ),
        ),
      );
}

```

</details>

[video](https://photos.app.goo.gl/srur6VRrwR7cTHaP9)

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.132 at /Users/nevercode/development/flutter_master
    • Framework revision 5995661777 (2 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Pixel 3a      • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

</details>

if you are experiencing the issue **only** with ios please follow up in the issue below
https://github.com/flutter/flutter/issues/59374

if it occurs with android as well could you please provide a complete reproducible code sample
thank you

**Comment by perfoWorks** [comment] 2020-06-22 09:09
@iapicca You could not reproduce it because you have typed text into it.. To reproduce it please do not type anything into the text field.. If you're changing focus on text field by pressing soft keyboard 'next' on your keyboard and don't type anything then it will not work. For simplicity of this issue please don't type anything and just change focus manually by taping on the text field without typing anything

**Comment by iapicca** [comment] 2020-06-24 14:31
Hi @perfoWorks 
using the same repro code as above on the latest master
with this [result](https://photos.app.goo.gl/5CFk4YLZ1aXa6bgM8)
I'm don't see any unintended behavior,
are you experiencing the issue with the latest master?
thank you

**Comment by perfoWorks** [comment] 2020-06-24 14:38
@iapicca I have only tried that on stable channel 

> Chanel Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-GB)

**Comment by TahaTesser** [comment] 2020-06-25 08:55
hI @perfoWorks 
i can reproduce this issue on iOS
Closing as duplicate of https://github.com/flutter/flutter/issues/59374

**Closed by TahaTesser** 2020-06-25 08:55 UTC
Labels: in triage
