### ISSUE TITLE
Flutter Custom font and Font Weight wont show

### ISSUE THREAD

**Issue by KingRegera** [flutter/flutter#51383] opened 2020-02-25 02:32 UTC
I was trying to change the font of some text on my app and noticed it made no change the font even though I did everything right. I then tried changing the font-weight and that did not work either (on my ios-sim). The weird thing about this is that it fonts don't show up on my android phone and ios-sim but font-weight works fine on my android device. Some things I have tried -

- I tried reinstalling the app
- I tried flutter clean
- I tried creating a new project
- I tried deleting VSC
- I tried deleting Xcode

**Comment by dnfield** [comment] 2020-02-25 06:55
Duplicate of #49492

**Closed by dnfield** 2020-02-25 06:55 UTC
