### ISSUE TITLE
Paste from clipboard issue on iOS 16

### ISSUE THREAD

**Issue by limenote135** [flutter/flutter#112515] opened 2022-09-28 03:07 UTC
The dialog to request permission is shown every time when a text is pasted from another app into TextField widget.

## Steps to Reproduce

1. Run form_app: https://github.com/flutter/samples/tree/main/form_app
2. Copy a text on another app.
3. Paste the text into TextField.
4. Tap 'Allow paste'.
5. Copy again on another app.
6. Paste again

**Expected results:**

Don't show the dialog or only one time on the first time in the app.

**Actual results:** 

Showed the dialog every time.

**Comment by danagbemava-nc** [comment] 2022-09-28 07:26
Hi @limenote135, what version of iOS 16 are you on? 

If you are not on iOS 16.0.2 I would advise you to upgrade. This was a bug in iOS 16 that has since been fixed in iOS 16.0.2 

See the release notes for iOS 16.0.2 https://support.apple.com/en-gb/HT213407

**Comment by limenote135** [comment] 2022-09-28 09:01
@danagbemava-nc I'm using iOS 16.0.2. iOS 16.0.0 has a bug that shows this dialog every time even if allows paste. After upgrading iOS 16.0.2, the dialog is not shown if the text is not changed but it is shown after copying some text again on another app.
It seems this happens only on flutter app.

**Comment by danagbemava-nc** [comment] 2022-09-29 08:42
Hi @limenote135,

What are some of the apps that you tested and what were their behaviors? From what I see on my end, most of the apple apps do not request permission when I attempt to copy text into the textfields.

I can reproduce this in an app that is not a flutter app. Outline VPN Client.  

From what I see on their repo, it appears to be a cordova app. See repo here https://github.com/Jigsaw-Code/outline-client
https://getoutline.org/en-GB/get-started/#step-3

Can you check if you can repro with Outline as well?

Perhaps this bug was not completely fixed in iOS 16.0.2

**Comment by limenote135** [comment] 2022-09-29 11:33
@danagbemava-nc Thanks for your investigation. I can repro this in Outline VPN Client, too. And an app made by ReactNative seems not to cause this issue. (I don't know why.)

I'm worried about this is not an iOS issue because the paste notification had been shown on iOS 15. I think this means the app read clipboard unintendedly from the point of view of iOS.

**Comment by danagbemava-nc** [comment] 2022-09-29 14:13
Hi @limenote135, it looks like this wasn't fixed by iOS 16.0.2 after all. I tested a small SwiftUI app where I request the clipboard data every time a TextField is tapped and the same behavior reproduces there. 

Can you try the sample below to see if your experience same?

<details>
<summary>sample</summary>

```swift
import SwiftUI

struct ContentView: View {
    
    @State var textValue = ""
    
    var body: some View {
        
        VStack {
            
            TextField(text: $textValue, label: {
                Text("Some text")
            }).onTapGesture {
                let pasteboard = UIPasteboard.general
                if let string = pasteboard.string {
                    print(string)
                }
            }
            
        }
        .padding()
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```
</details>

**Comment by limenote135** [comment] 2022-09-29 14:39
@danagbemava-nc year, I tried and it behaved the same.
Of cause, this code just reads the clipboard so I can paste a text into TextField even if I select 'Don't Allow Paste'.

**Comment by danagbemava-nc** [comment] 2022-09-30 08:53
> Of course, this code just reads the clipboard so I can paste a text into TextField even if I select 'Don't Allow Paste'.

Hi @limenote135, from what I gather TextField in iOS doesn't rely on the clipboard for copy-pasting text, so that's likely why it's working regardless. 

The flutter Textfield on the hand appears to rely on the clipboard data to enable copy-paste. The reason denying the permission for flutter doesn't paste any text is that there's no data returned when you disable the permission. However, since the prompt for permission comes from the system I don't know if flutter can do anything about that. 

See below the native call flutter uses to read the clipboard data. As you can see, the method call looks similar to what I used in the swiftui example above. 

https://github.com/flutter/engine/blob/db054e228b3f9bb8e3e4ba21e22bcfc8a79551b7/shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm#L260-L268

Since the prompt comes from the operating system, this issue will have to be fixed by the operating system. 

As such, I'll be closing this issue since this is a bug in iOS 16 that needs to be fixed by apple. 

If you disagree, leave a comment below stating why you disagree and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-09-30 08:53 UTC
Labels: in triage

**Comment by limenote135** [comment] 2022-09-30 09:50
@danagbemava-nc iOS 16 rolls out automatically to all iOS users in the near future and after that, some apps like the memo app made by flutter will be significantly inconvenient.
Don't the flutter team think this is critical? Does anyone urge Apple to fix this?

**Comment by limenote135** [comment] 2022-10-04 03:30
@danagbemava-nc hi, what do you think about that?
