### ISSUE TITLE
Compiler doesn‘t recognize generic of returning function

### ISSUE THREAD

**Issue by PAException** [flutter/flutter#89745] opened 2021-09-09 11:08 UTC
## Steps to Reproduce

create function
```
foo<T>(T Function(Map<String,dynamic>) parse, Widget Function(T) foo2); 
```
Now when calling 

```
foo(parseFoo(), (t) => returnSomething());
```
t isn't recognize as T rather as `Object?`

**Comment by maheshmnj** [comment] 2021-09-09 11:30
Hi @PAException Please share the output of `flutter doctor -v`

**Comment by PAException** [comment] 2021-09-09 14:29
```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale de-DE)
    • Flutter version 2.5.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (32 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
```

**Comment by nikitadol** [comment] 2021-09-10 07:21
> ```dart 
> foo(parseFoo(), (t) => returnSomething());
> ```
> t isn't recognize as T rather as Object?

You must explicitly specify the generic type

https://github.com/dart-lang/sdk/issues/42766

**Comment by maheshmnj** [comment] 2021-09-10 08:02
Hi @PAException Thanks for the info, @nikitadol is right it is working as intended you need to explicitly specify the type

```dart
void main() {
  foo<T>(T Function(Map<String, dynamic>) parse, Widget Function(T) foo2) {}

  String Function(Map<String, dynamic> p1) parseFoo() {
    return (z) {
      return z['test'];
    };
  }

  Widget returnSomething() {
    return Container();
  }

  foo(parseFoo(), (t) => returnSomething()); /// t is Object?

  foo<String>(parseFoo(), (t) => returnSomething());  /// t is String
}
```

Closing this issue as working as intended if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-10 08:02 UTC
Labels: in triage

**Comment by PAException** [comment] 2021-09-10 08:08
Thanks for the fast support. After you explained it I just understood! Makes totally sense... Sorry to bother you!
