### ISSUE TITLE
\t is not displayed correctly in a Text widget with Flutter 3.0.1

### ISSUE THREAD

**Issue by figengungor** [flutter/flutter#104415] opened 2022-05-23 14:57 UTC
## Steps to Reproduce

1. Run this dartpad example: https://dartpad.dev/?id=441204f9be10f98cf43fcc27c75726aa

**Expected results:** 
/t should leave a tab space

**Actual results:** 
It shows a corrupt display

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.0.1, on Mac OS X 10.15.7 19H1419 darwin-x64, locale en-TR)
    • Flutter version 3.0.1 at /Users/figengungor/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/figengungor/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM G980F (mobile) • RF8N72BXR7R • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-x64     • Mac OS X 10.15.7 19H1419 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by justinmc** [comment] 2022-05-23 17:11
I can only reproduce this on Windows and web (Chrome on Mac and Linux).  I also tried it on MacOS, Linux, Windows, Android (emulator) and iOS (emulator) and it looked fine.

I also don't believe this is a regression.  I tried a bunch of old versions back to July of 2021 and I still saw the bug.

**Comment by figengungor** [comment] 2022-05-23 19:35
It also happens on Android device.

**Comment by maheshmnj** [comment] 2022-05-24 13:36
looks similar to https://github.com/flutter/flutter/issues/79153

**Comment by maheshmnj** [comment] 2022-05-25 05:31
Closing as duplicate of #79153. Please follow up on that issue for further updates.

**Closed by maheshmnj** 2022-05-25 05:31 UTC
Labels: engine, platform-windows, a: typography, platform-web, has reproducible steps, found in release: 3.0, found in release: 3.1
