### ISSUE TITLE
flutter doctor found an issue after installing Visual Studio 2022 on Windows 10

### ISSUE THREAD

**Issue by 1feng128** [flutter/flutter#105216] opened 2022-06-02 11:53 UTC
Hi,

"flutter doctor" found an issue after installing Visual Studio 2022 on Windows 10 (Simplified Chinese edition):

 Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    **X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER)** found while decoding string: [
        {
          "instanceId": "c9388fb3",
          "installDate": "2022-06-02T08:12:34Z",
          "installationName": "VisualStudio/17.2.3+32526.322",
          "installationPath": "D:\\dev\\VStudio",
          "installationVersion": "17.2.32526.322",
          "productId": "Microsoft.VisualStudio.Product.Community",
          "productPath": "D:\\dev\\VStudio\\Common7\\IDE\\devenv.exe",
          "state": 4294967295,
          "isComplete": true,
          "isLaunchable": true,
          "isPrerelease": false,
          "isRebootRequired": false,
          "displayName": "Visual Studio Community 2022",
          "description": "����ǿ��� IDE����ѧ��������Դ��������ߺ͸������ʹ��",
          "channelId": "VisualStudio.17.Release",
          "channelUri": "https://aka.ms/vs/17/release/channel",
          "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
          "installedChannelUri": "https://aka.ms/vs/17/release/channel",
          "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.2#17.2.3",
          "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
          "updateDate": "2022-06-02T08:12:34.7949533Z",
          "catalog": {
            "buildBranch": "d17.2",
            "buildVersion": "17.2.32526.322",
            "id": "VisualStudio/17.2.3+32526.322",
            "localBuild": "build-lab",
            "manifestName": "VisualStudio",
            "manifestType": "installer",
            "productDisplayVersion": "17.2.3",
            "productLine": "Dev17",
            "productLineVersion": "2022",
            "productMilestone": "RTW",
            "productMilestoneIsPreRelease": "False",
            "productName": "Visual Studio",
            "productPatchVersion": "3",
            "productPreReleaseMilestoneSuffix": "1.0",
            "productSemanticVersion": "17.2.3+32526.322",
            "requiredEngineVersion": "3.2.2148.26540"
          },
          "properties": {
            "campaignId": "2030",
            "channelManifestId": "VisualStudio.17.Release/17.2.3+32526.322",
            "nickname": "",
            "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
          }
        }
      ]

**Comment by danagbemava-nc** [comment] 2022-06-02 12:20
Closing this as a duplicate of #102451. 

Kindly follow up in the linked issue for updates.

Thank you

**Closed by danagbemava-nc** 2022-06-02 12:20 UTC
Labels: in triage
