### ISSUE TITLE
[iOS Simulator] Hardware keyboard input is broken

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#96638] opened 2022-01-14 01:47 UTC
## Steps to Reproduce

1. Run the app using code below on an iOS simulator (iPhone 8 running iOS 14.5) and try typing in the form fields.

**Expected results:**
Typing in the text field should work

**Actual results:**
Typing doesn't work at all. Using Command-K doesn't bring up the software keyboard either. The only way to get the software keyboard to come up as a workaround is to disable **"Connect Hardware Keyboard"** 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            TextField(),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

**This bug is the EXACT same bug as #92796 which was closed, but it still occurs with the stable channel 2.8.1, beta channel 2.10.0-0.1.pre and the master channel.**

**Flutter doctor:**

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.362, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.362 at /Users/danny.valente/Library/flutter/9.9.99-master
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 72df4801c8 (24 minutes ago), 2022-01-13 17:08:35 -0800
    • Engine revision f121c1fe68
    • Dart version 2.17.0 (build 2.17.0-11.0.dev)
    • DevTools version 2.9.2
```

I assume all the keyboard input refactoring that happened in Flutter 2.5 and 2.8 broke this.

**Comment by maheshmnj** [comment] 2022-01-14 10:24
Hi @dannyvalentesonos, I verified this issue on `stable 2.8.1` and the latest `master, 2.9.0-1.0.pre.328`, But I am not seeing any exception or error. Is this reproducible by pressing any specific keys or are there any known reproducible steps?


**output from master, 2.9.0-1.0.pre.328**

https://user-images.githubusercontent.com/31410839/149500068-66d63b28-13be-4df1-b0be-665cbe438c01.mov




<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.328, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.328 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d290763941 (2 days ago), 2022-01-11 18:20:14 -0800
    • Engine revision 643b2787f4
    • Dart version 2.16.0 (build 2.16.0-159.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by dannyvalentesonos** [comment] 2022-01-14 14:17
@maheshmnj thanks for looking. I've built a simple app with the code above, and launched it on a simulator running ios 14.5 and typing using the hw keyboard doesn't work. No special keys needed. It just never works.

I'm on MacOS Big Sur, and running XCode 12.5.1 with command line tools version 13.2. I can install xcode 13 and give that a try, if you think that will make a difference?

**Comment by dannyvalentesonos** [comment] 2022-01-14 15:03
Actually, I still had the "Connect Hardware Keyboard" toggled off from my previous runs. When I built a simple Flutter app and ran it with the toggle on, it works (though I found another bug... The backspace button when held doesn't keep deleting characters).

In my case, our app is an "Add To Existing" module, so I've created a simple Add2App example that reproduces the problem. I'm attaching it here.

Steps to build:

1. Update flutter_module/build.sh and put your path to flutter
2. run build.sh like so: `./build.sh`
3. Open the ios project (ios/Add2AppTest.xcodeproj)
4. Build and run

The app will launch with a single button called "Launch Flutter". Tapping that will bring up the flutter view, with a TextField and you can repro the problem there.

I used the 2.8.1 stable release for this test.

Please let me know if you have any issues building the sample project.
Thank you.

[Add2AppTest (2.8.1 broken keyboard).zip](https://github.com/flutter/flutter/files/7871221/Add2AppTest.2.8.1.broken.keyboard.zip)

**Comment by maheshmnj** [comment] 2022-01-17 05:43
Thanks for the code sample @dannyvalentesonos, Is this issue reproducible in a normal flutter app or only in add to app? If the latter this seems like a duplicate of https://github.com/flutter/flutter/issues/92997

**Comment by maheshmnj** [comment] 2022-01-19 05:06
Thanks for the update closing as duplicate of #92997

**Closed by maheshmnj** 2022-01-19 05:06 UTC
Labels: in triage
