### ISSUE TITLE
[plugins] Android AAR builds are broken (Android property not found)

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#57846] opened 2020-05-23 11:22 UTC
## Description

It seems like https://github.com/flutter/flutter/issues/46304 is still an issue for Android AARs and since recently all no-op `android` directories have been removed in `flutter/plugins`, this breaks any `flutter build aar` using any of those Flutter plugins.

## Steps to Reproduce

1. Add `url_launcher` as a dependency:

```yaml
url_launcher: 5.4.10
```
2. Run `flutter build aar`.
3. Experience the following build failure: https://stackoverflow.com/questions/59942331/android-property-not-found-error-while-building-flutter-aar

This happens because `assembleAarDebug` cannot be found for the `url_launcher_web` plugin that is automatically included when using `flutter build aar`.

This specific problem (for `url_launcher`) was caused by this PR from @cg021: https://github.com/flutter/plugins/pull/2776

```
FAILURE: Build failed with an exception.
* Where:
Initialization script '/opt/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 15
* What went wrong:
Android property not found.
```

**Comment by TahaTesser** [comment] 2020-05-25 09:45
duplicate of https://github.com/flutter/flutter/issues/57795

**Closed by TahaTesser** 2020-05-25 09:45 UTC
