### ISSUE TITLE
Cannot detect iOS simulator under 10.xx macOS system and flutter 2.2

### ISSUE THREAD

**Issue by victorykong** [flutter/flutter#83203] opened 2021-05-23 07:55 UTC
![image](https://user-images.githubusercontent.com/50655436/119252479-1935f600-bbdf-11eb-96e8-3a9507582995.png)
![image](https://user-images.githubusercontent.com/50655436/119252484-1f2bd700-bbdf-11eb-8108-9cd1cf706fb0.png)
![image](https://user-images.githubusercontent.com/50655436/119252487-2357f480-bbdf-11eb-98ac-f2ba103aed0b.png)

**Comment by victorykong** [comment] 2021-05-23 08:20
flutter doctor -v why didn't you find my simulator?

**Comment by TahaTesser** [comment] 2021-05-24 12:02
Hi @victorykong 
`Failed to launch iOS simulator` is a known issue https://github.com/flutter/flutter/issues/80291
Quit the simulator completely and run the app again. 

Regarding `flutter doctor -v` not finding the simulator seems to be related ti outdated Xcode

**Comment by TahaTesser** [comment] 2021-05-27 10:00
https://github.com/flutter/flutter/issues/83463 confirms this to be a regression on 2.2

**Comment by TahaTesser** [comment] 2021-05-27 10:02
cc: @jmagman

**Comment by jmagman** [comment] 2021-05-27 18:02
I wasn't able to reproduce this on 2.2.0, but I'm on Xcode 12.5.
@victorykong Can we get the output of `flutter devices -v`?

**Comment by darshankawar** [comment] 2021-06-18 12:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-06-18 12:59 UTC
Labels: e: OS Version specific, passed first triage, platform-ios, t: flutter doctor, t: xcode, tool, waiting for customer response
