### ISSUE TITLE
gradient.dart:369:27: Error: Optional parameter 'colors' should have a default value because its type 'List<Color>' doesn't allow null.

### ISSUE THREAD

**Issue by steelx** [flutter/flutter#70383] opened 2020-11-12 15:12 UTC
My project used to work, but recently I switched to different machine.
And when I try to run the project I get following error

```
Container(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Color.fromRGBO(
                    215,
                    117,
                    255,
                    1,
                  ).withOpacity(0.5),
                  Color.fromRGBO(
                    255,
                    188,
                    117,
                    1,
                  ).withOpacity(0.9),
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                stops: [0, 1],
              ),
            ),
          ),
```

I even did `flutter clean` restart machine as well.

```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
/opt/flutter/packages/flutter/lib/src/painting/gradient.dart:369:27: Error: Optional parameter 'colors' should have a default value because its type 'List<Color>' doesn't allow null.
 - 'List' is from 'dart:core'.
 - 'Color' is from 'dart:ui'.
    @required List<Color> colors,
                          ^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1

```

Below is the code from flutters **gradient.dart** file which is causing the issue.

```
class LinearGradient extends Gradient {
  /// Creates a linear gradient.
  ///
  /// The [colors] argument must not be null. If [stops] is non-null, it must
  /// have the same length as [colors].
  const LinearGradient({
    this.begin = Alignment.centerLeft,
    this.end = Alignment.centerRight,
    @required List<Color> colors,
    List<double>? stops,
    this.tileMode = TileMode.clamp,
    GradientTransform? transform,
  }) : assert(begin != null),
       assert(end != null),
       assert(tileMode != null),
       super(colors: colors, stops: stops, transform: transform);
```

**flutter doctor -v**    

```
> flutter doctor -v                
[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_IN)
    • Flutter version 1.22.3 at /opt/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/ajinkya/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

Plugins installed
![image](https://user-images.githubusercontent.com/3184210/98957631-6433ca00-2527-11eb-813d-f65dd6be7acf.png)

**pubspec.yml**

```
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.9.4
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  rxdart: ^0.24.1
  http: ^0.12.2
  search_map_place: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  network_image_mock: ^1.0.0
  #test: 1.15.0
```

**flutter run -v**
[https://pastebin.run/CjbQtNJWxT](https://pastebin.run/CjbQtNJWxT)

**Comment by sidrao2006** [comment] 2020-11-12 15:17
Hello @steelx ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by sidrao2006** [comment] 2020-11-12 15:18
Cc @jonahwilliams ,
Weren't android studio's plugin issues resolved?

**Comment by steelx** [comment] 2020-11-12 15:21
> Hello @steelx ,
> Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
> Thank you!

updated now

**Comment by Calamity210** [comment] 2020-11-12 23:19
@steelx Have you modified gradient.dart? Flutter has migrated to nnbd, required is now a keyword,

The following change should resolve that
```diff
- @required List<Color> colors,
+ required List<Color> colors,
```

**Comment by steelx** [comment] 2020-11-13 02:12
> @steelx Have you modified gradient.dart? Flutter has migrated to nnbd which brings required as a keyword,
> 
> The following change should resolve that
> ```diff
> - @required List<Color> colors,
> + required List<Color> colors,
> ```

Yes I added '@' I will update and let you know

**Comment by TahaTesser** [comment] 2020-11-13 08:49
Hi @steelx 
I just tried on `stable`, `beta`, `master`
There are no errors thrown without source class. 



<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: [
                Color.fromRGBO(
                  215,
                  117,
                  255,
                  1,
                ).withOpacity(0.5),
                Color.fromRGBO(
                  255,
                  188,
                  117,
                  1,
                ).withOpacity(0.9),
              ],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              stops: [0, 1],
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.22.3 at C:\Code\flutter_stable
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\Code\flutter_beta
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!
```

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.229, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.24.0-8.0.pre.229 at C:\Code\flutter_master
    • Framework revision 7cda6866b0 (5 hours ago), 2020-11-12 22:39:02 -0500
    • Engine revision dddb532b5c
    • Dart version 2.12.0 (build 2.12.0-37.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.610]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!
```

</details>

Closing as this seems to be a local chang & isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-13 08:49 UTC
