### ISSUE TITLE
Not able to hide the home bar on iPhone X+

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#20965] opened 2018-08-23 20:43 UTC
```dart
SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top])
```
This does not hide the bottom navigation bar of the iPhone X, reference: https://stackoverflow.com/questions/51993256/how-to-hide-the-navigation-bar-on-the-iphone-x-in-flutter

**Comment by TheKeenProgrammer** [comment] 2018-08-23 20:47
Thanks for posting it for me. I am the one having issues with it in the original post, if you need more information, feel free to ask me.

**Comment by TheKeenProgrammer** [comment] 2018-08-26 10:42
So there is no way for me to do it now then? I’m developing an app right now which the design will be broken if I have this line. May need to move to Swift and Java otherwise.

**Comment by xster** [comment] 2018-08-30 18:37
For now, you can use https://flutter.io/platform-channels/ to make this connection or send us a PR :)

**Comment by TheKeenProgrammer** [comment] 2018-08-31 13:29
Where would I find the FlutterViewController? Can't seem to find it.

**Comment by TheKeenProgrammer** [comment] 2018-10-02 18:44
@creativecreatorormaybenot Is this fixed now then in the latest Flutter?

**Comment by AndreaMiotto** [comment] 2019-06-21 11:09
any news on this fix?

**Comment by creativecreatorormaybenot** [comment] 2019-06-21 12:32
@AndreaMiotto You should give the original issue a thumbs up if you think that it should be prioritized as this will make the issue appear earlier when [sorting by thumbs up](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), which is the most common way of sorting.

**Comment by nohli** [comment] 2019-07-09 06:31
> For now, you can use https://flutter.io/platform-channels/ to make this connection or send us a PR :)

Anyone successful in hiding the home indicator through platform channels?

**Comment by lynn** [comment] 2019-10-24 12:15
I just made and released [a package to do this](https://pub.dev/packages/home_indicator). Add `home_indicator` to your pubspec.yaml, then

```dart
import 'package:home_indicator/home_indicator.dart';

await HomeIndicator.hide();
await HomeIndicator.show();
```

**Comment by nohli** [comment] 2019-10-24 22:36
> I just made and released [a package to do this](https://pub.dev/packages/home_indicator). Add `home_indicator` to your pubspec.yaml, then
> 
> ```dart
> import 'package:home_indicator/home_indicator.dart';
> 
> await HomeIndicator.hide();
> await HomeIndicator.show();
> ```
> 
> (cc @nohli)

@lynn one line of code and the home indicator is gone - it's gold for my meditation app. thanks a lot!!!

**Comment by TahaTesser** [comment] 2020-09-08 14:17
Hi @creativecreatorormaybenot 
Are you still experiencing this issue X Plus?  I can't reproduce on physical XR 
I wanna make sure if it is  device-specific 

![IMG_0161](https://user-images.githubusercontent.com/48603081/92488317-0247a300-f20c-11ea-9ccd-8e838d73d53d.PNG)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top]);

    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
✓] Flutter (Channel master, 1.22.0-10.0.pre.88, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.88 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision e10bdbbd9d (18 hours ago), 2020-09-07 11:40:03 -0700
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (4 available)            
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 73130414-6DF8-4E37-B9AF-F81FA0F9068B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.83

• No issues found!

```

</details>

**Comment by creativecreatorormaybenot** [comment] 2020-09-08 14:22
@TahaTesser I do not have access to that device right now - can someone else reproduce?

**Comment by TahaTesser** [comment] 2020-09-08 15:00
I am adding the `wait` label until somebody else confirms the issue, otherwise, I will close the issue after 21 days. Sounds good?

**Comment by darshankawar** [comment] 2020-09-30 11:09
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-30 11:09 UTC
Labels: P4, a: layout, customer: crowd, engine, framework, platform-ios, waiting for customer response

**Comment by WwwdMR** [comment] 2021-01-26 23:22
I have the same issue . It appears when there is a bottomNavigationBar
