### ISSUE TITLE
How can I ask Gradle to ignore namespace issues ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#129074] opened 2023-06-18 08:21 UTC
I've just started to process to upgrade to 3.10, and have multiple packages that haven't update to gradle 8.
How can I go past that ? Because if it's not possible, I'll have to stay on 3.7 indefinitely. It makes no sense to cut myself off from all the packages that haven't upgraded and doing all the upgrading and testing myself is too big of a task.

**Comment by dam-ease** [comment] 2023-06-19 10:04
Hi @TheCarpetMerchant. What packages are affected??

**Comment by TheCarpetMerchant** [comment] 2023-06-19 10:09
Downgrading to Gradle 7.4.2 seems to work well, don't know why Flutter (or something else) asked me to upgrade.

**Comment by dam-ease** [comment] 2023-06-19 15:20
Okay, can you share the error message or logs you are getting??

**Comment by TheCarpetMerchant** [comment] 2023-06-20 20:05
Well, I didn't keep the whole error but here's some of it copy-pasted from a discord message :
```
A problem occurred configuring project ':flutter_archive'.
Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.
```

**Comment by dam-ease** [comment] 2023-06-21 08:58
Hi @TheCarpetMerchant. Per this https://github.com/flutter/flutter/issues/126403#issuecomment-1588072282, this seems to have been fixed on the latest master channel. Can you confirm this by switching to the latest `master`?

**Comment by jbankz** [comment] 2023-06-24 22:15
> 7.4.2



> Hi @TheCarpetMerchant. Per this [#126403 (comment)](https://github.com/flutter/flutter/issues/126403#issuecomment-1588072282), this seems to have been fixed on the latest master channel. Can you confirm this by switching to the latest `master`?

I am not sure it has been fixed on master branch because the issue is still there.

**Comment by dam-ease** [comment] 2023-06-26 07:47
Hi @jbankz. Were you able to still reproduce the issue after following this https://github.com/flutter/flutter/issues/126403#issuecomment-1591486226

**Comment by jbankz** [comment] 2023-06-26 09:59
> Hi @jbankz. Were you able to still reproduce the issue after following this [#126403 (comment)](https://github.com/flutter/flutter/issues/126403#issuecomment-1591486226)

Yes I was able to reproduce and fix it.

**Comment by dam-ease** [comment] 2023-06-26 15:34
Hi @jbankz. Thanks for confirming this. Per your comment, I guess this is fine right? Also, can you drop an example of the fix that seemed to solve the issue before I close this?

**Comment by jbankz** [comment] 2023-06-26 17:49
> Hi @jbankz. Thanks for confirming this. Per your comment, I guess this is fine right? Also, can you drop an example of the fix that seemed to solve the issue before I close this?

`android {
  .....

    if (project.android.hasProperty('namespace')) {
        namespace 'your package name here'
    }
}
`

**Comment by dam-ease** [comment] 2023-06-27 07:36
Thanks @jbankz.

**Closed by dam-ease** 2023-06-27 07:36 UTC
Labels: in triage
