### ISSUE TITLE
FlutterDriver's requestData() does not respect timeout.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#23614] opened 2018-10-27 04:17 UTC
`requestData()` on `FlutterDriver` doesn't respect the timeout parameter.  If I don't pass anything then I get a 30 second timeout.  If I pass a value larger than 30 seconds, I get a 30 second timeout.

I'm running my flutter_driver test on an iPhone 7 simulator.

Repro code:
main_test.dart
```dart
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  FlutterDriver driver;

  setUpAll(() async {
    // Connects to the app
    driver = await FlutterDriver.connect();
  });

  tearDownAll(() async {
    if (driver != null) {
      // Closes the connection
      driver.close();
    }
  });

  test('FlutterDriver requestData() does not respect timeout', () async {
    print('Running test');

    final FlutterDriver driver = await FlutterDriver.connect();
    await driver.requestData('completion_notice', timeout: const Duration(seconds: 60));

    print('Test is done');
  });
}
```

main.dart
```dart
import 'dart:async';
import 'package:flutter_driver/driver_extension.dart';

void main() {
  print('Running main');
  enableFlutterDriverExtension(handler: (String message) {
    // Never return.
    return Completer<String>().future;
  });

  print('Delaying');
  Future.delayed(const Duration(seconds: 45));

  print('Delay over. Completing app.');
}
```
```
Flutter Doctor:
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.4 at [redacted]
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at [redacted]
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1012-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • iPhone 7 • [redacted] • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by jonahwilliams** [comment] 2019-04-22 05:03
I believe this is caused by package:test's timeout. Configuring it via https://pub.dartlang.org/documentation/test_api/latest/test_api/Timeout-class.html should allow longer timeouts for driver processes.

**Comment by matthew-carroll** [comment] 2019-04-22 14:32
I don't have the test code in front of me right now to verify that, but assuming it works, we still have an issue here, right? Regardless of workaround, the call doesn't respect its own `timeout` parameter...

**Comment by jonahwilliams** [comment] 2019-04-22 17:55
The call respects the timeout parameter, but `test`/`tearDownAll`/`setupApp` have their own timeout parameters

**Comment by matthew-carroll** [comment] 2019-04-22 18:00
I'm open to solution options, I'm just saying that this is a problem. 

Whether it's a documentation problem, naming problem, discoverability problem, etc. I'm not sure. All I can say for certain is that when I was writing this I wanted the given call to have a timeout, the call offered a timeout, I set it, it appeared to be ignored, and I was confused and frustrated. 

It would be good if other developers don't experience that.

**Comment by nerder** [comment] 2020-04-04 19:34
The workaround we find was to setup the `timeout` in this way `driver.requestData().timeout(Duration(seconds:1))`

**Comment by markusaksli-nc** [comment] 2020-07-28 13:45
This behavior and the ways to change it are very clearly documented in the [timeout article](https://pub.dev/packages/test#timeouts) that is referenced in the 30sec timeout exception message. 

`TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts`

For shorter manually specified timeouts the behavior is as expected: the specified shorter timeout is honored. Closing as this is no longer an issue in the documentation or behavior of timeouts. If you feel the documentation for Timeouts needs to be made even clearer, please comment with your suggestion and I'll reopen.

**Closed by markusaksli-nc** 2020-07-28 13:45 UTC
Labels: P4, a: tests, framework, t: flutter driver
