### ISSUE TITLE
Carried velocity is incorrectly applied on iOS

### ISSUE THREAD

**Issue by trymnilsen** [flutter/flutter#79277] opened 2021-03-29 15:26 UTC
On iOS with `BouncingScrollPhysics` the carried velocity that is applied at the end of a scroll activity seems to be incorrectly applied. It will always apply the velocity even if the last fling's velocity was substantially less than previous flings. This will cause the visible effect of the scrollview _accelerating_ after a slower fling. 

## Steps to Reproduce

These steps assumes the usage of the [scroll_overlay](https://github.com/flutter/platform_tests/tree/master/scroll_overlay) platform test

For the unxperienced finger this is a bit challenging to _intentionally_ trigger.  Therefor I have included two ways to trigger it and a video at the end (as it was difficult to show how to reproduce with just a screen-capture). 

1. Build momentum by flinging 3-4 times a bit fast
2. Then while continuing to fling slow down the velocity of the flings
3. Make one final fling that is slowing that the flings you made 3-4 times
4. Observe that the scrollview's velocity is a lot more than the native scroll view and in some cases will even have a larger velocity than what you finger had while in contact with the screen.

https://user-images.githubusercontent.com/1550685/112858768-79faf380-90b2-11eb-8133-3d07029d486d.mp4

**Expected results:** 

Somewhat similar velocity to the native iOS scrollview when lifting the finger for the last time

**Actual results:**

The scrollview simply added the previously carried momentum to the velocity of the current fling. Causing the effect of making the scrollview speed up and scroll for much longer than the native view. This is especially jarring when you barely have any velocity while lifting the finger with carried momentum, like trying to stop a scroll by swiping just a little bit. 

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/trymnilsen/development/flutter
    • Framework revision 5d36f2e7f5 (2 months ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/trymnilsen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio 4.1 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • iPhone (mobile) • <id redacted> • ios • iOS 14.4.2

• No issues found!
```

**Comment by nt4f04uNd** [comment] 2021-03-29 16:54
potentially a duplicate of https://github.com/flutter/flutter/issues/77043

**Comment by TahaTesser** [comment] 2021-03-30 12:11
Hi @trymnilsen 
This indeed looks like a duplicate of https://github.com/flutter/flutter/issues/77043
I can reproduce the issue when following your reproducible as well as using the code sample from  https://github.com/flutter/flutter/issues/77043#issuecomment-788884763 
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-30 12:11 UTC
Labels: f: scrolling, framework, in triage, platform-ios

**Comment by trymnilsen** [comment] 2021-03-30 15:39
@TahaTesser Fine by my. Created an suggestion for a fix at https://github.com/flutter/flutter/pull/79382
