### ISSUE TITLE
The following assertion was thrown while finalizing the widget tree

### ISSUE THREAD

**Issue by lancard-aikawa** [flutter/flutter#150678] opened 2024-06-24 04:31 UTC
```console
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3878 pos 12: '!_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      NavigatorState.dispose (package:flutter/src/widgets/navigator.dart:3878:12)
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5696:11)
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2077:13)
#5      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5539:14)
#16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#17     ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#18     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2086:25)
#19     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2765:15)
#20     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3175:7)
#21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1143:19)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#25     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#26     _invoke (dart:ui/hooks.dart:312:13)
#27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#28     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
```

**Comment by huycozy** [comment] 2024-06-24 08:47
This seems to be an issue with your implementation on navigator usage, please check [this](https://stackoverflow.com/questions/55618717/error-thrown-on-navigator-pop-until-debuglocked-is-not-true/) and underlying answers to see if one of them is your case or not. 

Closing the issue. If answers are not helpful, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Also, please provide the output of `flutter doctor -v` and I will reopen this issue. Thanks!

**Closed by huycozy** 2024-06-24 08:47 UTC
Labels: in triage
