### ISSUE TITLE
Error faced in Firebase Auth signInWithCredential method

### ISSUE THREAD

**Issue by DCodez804** [flutter/flutter#80515] opened 2021-04-15 15:28 UTC
![Screenshot (1)](https://user-images.githubusercontent.com/52531507/114895248-f9b3ec80-9e2c-11eb-8fde-16d9915c1d49.png)
Google user is getting created successfully but when using the auth credential from GoogleAuthProvider in the method signInWithCredential , the following error is thrown.

**Comment by iapicca** [comment] 2021-04-15 16:00
@DCodez804 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by TahaTesser** [comment] 2021-04-16 07:30
Hi @iapicca 
The issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-16 07:30 UTC
Labels: in triage
