### ISSUE TITLE
When building and publishing as a web application, use the webviewx plug-in to ask questions

### ISSUE THREAD

**Issue by yudanh** [flutter/flutter#107227] opened 2022-07-07 11:49 UTC
1. The current page uses sliverpersistentheader to hover and WebView together. Click the component on the hover interface, and it will get stuck

2. Using stack, add WebView and (flutter native components with click events, such as draggable and gesturedetector), and click events will be transmitted to WebView
![image](https://user-images.githubusercontent.com/18692389/177766343-26564de5-a301-4d83-83a4-278492ee2422.png)

**Comment by maheshmnj** [comment] 2022-07-07 12:51
Hi @yudanh,  WebviewX is not a first part plugin (developed by flutter team) issues related to that must be filed with the maintainer closing as this is not a bug in flutter

**Closed by maheshmnj** 2022-07-07 12:51 UTC
Labels: in triage
