### ISSUE TITLE
There is no "surface container" color in material 3

### ISSUE THREAD

**Issue by mrbeardad** [flutter/flutter#129755] opened 2023-06-29 07:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

```dart
ColorScheme.fromSeed({
// ...
Color? background,    // In m3 color system, there is no background color
Color? surface,  // Instead, use surface as background color
Color? surfaceVariant,// And use surface container color as the color for a contained area against the surface color
})
```

### Proposal

<https://m3.material.io/styles/color/the-color-system/color-roles>
![image](https://github.com/flutter/flutter/assets/54128430/9ec82574-debb-440f-9450-8c681b12ee0e)

**Comment by TahaTesser** [comment] 2023-06-29 08:37
duplicate of https://github.com/flutter/flutter/issues/115912

**Closed by TahaTesser** 2023-06-29 08:37 UTC
Labels: in triage
