### ISSUE TITLE
[MacOS Desktop]Ram increase after lid is close

### ISSUE THREAD

**Issue by letungcntt** [flutter/flutter#94090] opened 2021-11-23 09:02 UTC
source code: https://github.com/letungcntt/my_app

```console
Flutter 2.8.0-3.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2901cd7208 (5 days ago) • 2021-11-18 11:15:09 -0800
Engine • revision bcc2b7f12c
Tools • Dart 2.15.0 (build 2.15.0-268.18.beta)
```

<img width="982" alt="Screen Shot 2021-11-23 at 3 49 29 PM" src="https://user-images.githubusercontent.com/46608407/142996347-f4df85f4-b63b-4585-b2e1-a9e022a5a2b5.png">

<img width="982" alt="Screen Shot 2021-11-23 at 3 54 00 PM" src="https://user-images.githubusercontent.com/46608407/142995536-25e300a4-5729-49ad-9f5d-0ac138d5b2a7.png">

**Comment by maheshmnj** [comment] 2021-11-24 14:49
Hi @letungcntt, Thanks for filing the issue. How long is the lid of the laptop kept closed and  In which mode(debug/profile/release) is the app running?

I ran your sample code in debug mode and closed the lid for five minutes and reopened the app was running with same memory usage.

Before  |  After
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/143259951-c8d51920-f08c-4b46-8fac-5350e6e66cab.png)  |  ![](https://user-images.githubusercontent.com/31410839/143260142-2f1db59c-127c-48f1-b9ac-7a95d7c0e332.png)

**Comment by letungcntt** [comment] 2021-11-24 15:10
@maheshmnj i test it with debug and release. But i ran code and closed the lid under ten seconds.

**Comment by maheshmnj** [comment] 2021-11-25 12:54
@letungcntt How long have you kept the lid closed? Can you try switching to master channel and see if you can reproduce it there? You can switch to master by running

```
flutter channel master 
flutter upgrade
```

**Comment by letungcntt** [comment] 2021-11-25 14:39
@maheshmnj i kept the lid closed at 5s to 10s. i will try again with branch master

**Comment by letungcntt** [comment] 2021-11-26 02:06
The problem hasn't fixed at master

**Comment by maheshmnj** [comment] 2021-11-26 06:54
@letungcntt  Can you please verify if this happens with other apps too? Because your app is loading a lot of network images and that seems to be contributing to the memory. Even if you don't close the lid and browse the app you will see an increase in memory consumption.

**Comment by letungcntt** [comment] 2021-11-28 13:49
@maheshmnj Keeping this issue open for further investigation.

**Comment by maheshmnj** [comment] 2021-11-29 05:25
> @maheshmnj Keeping this issue open for further investigation.

@letungcntt Without enough details, we won't be able to investigate further. I can see that memory increases when you scroll the list regardless of the lid is closed. If I close and open the lid the memory usage is approximately the same.
Can you please confirm if you are seeing this behavior?

**Comment by letungcntt** [comment] 2021-12-02 07:09
@maheshmnj oh. sorry, i has checked and the problem is loading a lot of network images

**Comment by maheshmnj** [comment] 2021-12-02 07:48
> @maheshmnj oh. sorry, i has checked and it is loading a lot of network images

Provided your last message I feel its safe to close the issue, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-12-02 07:48 UTC
Labels: in triage
