### ISSUE TITLE
I keep getting the 'The Flutter Daemon has terminated.' message every time I try to connect to my emulator.

### ISSUE THREAD

**Issue by khadija-hotreload** [flutter/flutter#76555] opened 2021-02-22 19:34 UTC
Here is the error log:

[log-b46b.txt](https://github.com/flutter/flutter/files/6024698/log-b46b.txt)

**Comment by khadija-hotreload** [comment] 2021-02-22 19:34
@DanTup

**Comment by DanTup** [comment] 2021-02-22 20:14
It looks like the process is failing to start:

```
[12:18:25 AM] [FlutterDaemon] [Info] Spawning /Users/mc/Documents/flutter/bin/flutter with args ["daemon"]
[12:18:25 AM] [FlutterDaemon] [Info] ..  in /Users/mc/Documents/flutter
[12:18:25 AM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[12:18:25 AM] [FlutterDaemon] [Info]     PID: 47912
[12:18:25 AM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"emulator.getEmulators"}]
[12:18:25 AM] [FlutterDaemon] [Error] env: bash: No such file or directory
```

Further up the log when searching for the SDK, it has:

```
[12:18:25 AM] [General] [Info]         /Users/mc/Desktop/Flutter Projects/newprojecttest/$PATH
[12:18:25 AM] [General] [Info]         /Users/mc/Desktop/Flutter Projects/newprojecttest/$PATH/bin
[12:18:25 AM] [General] [Info]         /Users/mc/Documents/flutter/bin
```

The presence of `$PATH` in there looks broken. My guess is that the way you've set your `PATH` variable is incorrect, and you've ended up with the literal string `$PATH` in the search path rather than the previous contents of the variable `$PATH`. This means `bash` is not found (but is required, since Dart-Code spawns all processes using shell-execute).

So I would review how/where you've updated your PATH environment variable, it seems like something might be incorrect.

**Comment by darshankawar** [comment] 2021-02-23 07:33
@khadija-hotreload 
Seems to be an issue how you have setup $PATH. 
Please check above comment and possible solution and see if it helps to resolve your issue.

**Comment by khadija-hotreload** [comment] 2021-02-25 20:22
![Screenshot 2021-02-26 at 1 19 21 AM](https://user-images.githubusercontent.com/61636156/109211871-a92af600-77d0-11eb-9942-8a1cd3a4b33a.png)

This is how I've set the PATH. The issue appears to be something else since my flutter application is running through the terminal. It's just that flutter daemon that terminates and doesn't connect my IDE (vscode) to the emulator (if that makes any sense).

**Comment by darshankawar** [comment] 2021-02-26 06:32
@khadija-hotreload 
It seems the issue is related to your setup and not an issue within the framework. Please see https://flutter.dev/community for resources and may ask this in StackOverflow to get help on it.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-02-26 06:32 UTC
Labels: in triage

**Comment by DanTup** [comment] 2021-02-26 16:58
@khadija-hotreload VS Code spawns the process a little differently to how it'll run in your terminal. It has to spawn a shell to execute the process and by default that's `bash`, but because the `PATH` is not correct `bash` can't be found.

The log file you posted shows that your `PATH` contains the literal string `$PATH` which means all the usual system paths have been removed.

If you type `echo $PATH` in your terminal, you may find that it includes the string `$PATH` but it should not. I'm not sure what's causing it, perhaps it's the quotes `"` around it - they don't look like standard quotes so maybe they're preventing the variable from being interpolated (this happens with single quotes, for example.. you should use standard double quotes `"`).

After fixing this, you may need to reboot to get the original `PATH` back, as it's been overwritten for the session with that string. You should be able to tell when it's fixed as `echo $PATH` in your terminal should print something that does not include the string `$PATH` but many system paths (for example `/usr/local/bin`, `/usr/bin` etc).
