### ISSUE TITLE
When use ReorderableListView dragging item from up to down, "newIndex" is incorrect.

### ISSUE THREAD

**Issue by Nomeleel** [flutter/flutter#56821] opened 2020-05-10 08:58 UTC
## Steps to Reproduce

# 1. Below is my code.

```
class ReorderableListDemoView extends StatefulWidget {
  @override
  _ReorderableListDemoViewState createState() => _ReorderableListDemoViewState();
}

class _ReorderableListDemoViewState extends State<ReorderableListDemoView> {

  List<Widget> _widgetList;

  defText(String text) {
    return Text(
      text,
      style: TextStyle(
        fontSize: 15,
        color: Colors.black,
        decoration: TextDecoration.none,
      ),
    );
  }

  @override
  void initState() {
    
    _widgetList = List.generate(8, (index) => 
      Container(
        key: ValueKey('$index'),
        height: 55,
        color: Color(Random().nextInt(0xFFFFFFFF)),
        alignment: Alignment.center,
        child: defText('$index'),
      )
    );

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Container(
        color: Colors.white,
        child: Column(
          children: <Widget>[
            Container(
              height: 100,
              alignment: Alignment.center,
              child: defText('Can try to drag.'),
            ),
            Expanded(
              child: ReorderableListView(
                  children: _widgetList,
                  onReorder: onReorder,
                ),
            ),
          ],
        ),
      ),
    );
  }

  onReorder(int oldIndex, int newIndex) {
    print('oldIndex: $oldIndex newIndex: $newIndex');

    int direction = oldIndex < newIndex ? 1 : -1;
    var temp = _widgetList[oldIndex];
    var check = (index) => (newIndex - index).abs() + (oldIndex - index).abs() == (newIndex - oldIndex).abs(); 
    for (int i = oldIndex; check(i); i += direction) {
      _widgetList[i] = _widgetList[i + direction];
    }
    _widgetList[newIndex] = temp; 
  }

}

```

# 2. Try to drag item: 1 -> 3, 7 -> 5

There will be movement animation during the dragging process, but in fact it will not change the order of the items in the list.
In onReorder callback, change the order of list items.

```
onReorder(int oldIndex, int newIndex) {
  print('oldIndex: $oldIndex newIndex: $newIndex');

  int direction = oldIndex < newIndex ? 1 : -1;
  var temp = _widgetList[oldIndex];
  var check = (index) => (newIndex - index).abs() + (oldIndex - index).abs() == (newIndex - oldIndex).abs(); 
  for (int i = oldIndex; check(i); i += direction) {
    _widgetList[i] = _widgetList[i + direction];
  }
  _widgetList[newIndex] = temp; 
}

```
Try to drag item: 1 -> 3, 7 -> 5

**Actual results:** 

```
I/flutter ( 8948): oldIndex: 1 newIndex: 4
I/flutter ( 8948): oldIndex: 7 newIndex: 5
```
![ReorderableView_result_wrong](https://user-images.githubusercontent.com/25820430/81494921-06f05f00-92df-11ea-8f0e-2da1ff10902a.PNG)

I found when dragging item from up to down, ***"newIndex" is 1 increase*** from the actual result.

# 3. Special logic processing

In onReorder callback "newIndex" proactively subtract 1.

```
onReorder(int oldIndex, int newIndex) {
  print('oldIndex: $oldIndex newIndex: $newIndex');

  if (newIndex > oldIndex) {
    newIndex--;
    print('reset index: oldIndex: $oldIndex newIndex: $newIndex');
  }

  int direction = oldIndex < newIndex ? 1 : -1;
  var temp = _widgetList[oldIndex];
  var check = (index) => (newIndex - index).abs() + (oldIndex - index).abs() == (newIndex - oldIndex).abs(); 
  for (int i = oldIndex; check(i); i += direction) {
    _widgetList[i] = _widgetList[i + direction];
  }
  _widgetList[newIndex] = temp; 
}

```

**Expected results:** 

```
I/flutter ( 9602): oldIndex: 1 newIndex: 4
I/flutter ( 9602): reset index: oldIndex: 1 newIndex: 3
I/flutter ( 9602): oldIndex: 7 newIndex: 5
```

![ReorderableView_result_right](https://user-images.githubusercontent.com/25820430/81494933-1bccf280-92df-11ea-8a66-06141457f04b.PNG)

# 4. View the source code of ReorderableView

View source code: [ReorderableListView](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/reorderable_list.dart) found the following comments.

```
Line 23 ~ 26
/// If [oldIndex] is before [newIndex], removing the item at [oldIndex] from the
/// list will reduce the list's length by one. Implementations used by
/// [ReorderableListView] will need to account for this when inserting before
/// [newIndex].
```

And some special instructions.

```
Line 405 ~ 410
void moveToStart() => reorder(index, 0);
void moveToEnd() => reorder(index, widget.children.length);
void moveBefore() => reorder(index, index - 1);
// To move after, we go to index+2 because we are moving it to the space
// before index+2, which is after the space at index+1.
void moveAfter() => reorder(index, index + 2);
```

# 5. In conclusion

This index is concerned with the position of the item during the dragging process to trigger the moved animation. It describes the index corresponding to the moved animation.

And what we focus on when we use it is from where to where drag, where the demand is relatively simple.

The former will do special treatment for subscripts, so I do n’t think that the processed subscripts should be passed directly to the user, and then the user must do a reverse process when using it.

<details>
  <summary>Logs</summary>

run `flutter doctor -v`

```
PS P:\Flutter> flutter doctor -v
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18362.778], locale zh-CN)
    • Flutter version 1.17.0 at C:\Software\Flutter\flutter
    • Framework revision e6b34c2b5c (8 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at P:\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = P:\Android\Sdk
    • Java binary at: C:\Software\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Software\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.44.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by niuxinghua** [comment] 2020-05-11 11:21
same issue

**Comment by TahaTesser** [comment] 2020-05-11 12:04
Duplicate of [#24786](https://github.com/flutter/flutter/issues/24786)

**Closed by TahaTesser** 2020-05-11 12:04 UTC
