### ISSUE TITLE
I'm not getting color suggestion box while adding colors

### ISSUE THREAD

**Issue by Shivansh001** [flutter/flutter#59132] opened 2020-06-10 04:56 UTC
When I use to e=write the code

color: Colors.teal, 

Then I can't see the dialog box of other shades which I can use in flutter

**Comment by TahaTesser** [comment] 2020-06-11 08:27
Hi @Shivansh001 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by SadSack963** [comment] 2020-06-14 21:13
It looks like that feature has been removed (accidentally?) the latest Flutter Plugin (or is it Android Studio 4?) 

I just installed an old version of Android Studio on my Linux VM with Flutter Plugin 39.0.1, and the pop-up worked just fine (Ctrl+Q).

However, after upgrading Android Studio, (and Flutter/Dart) it no longer works. I should make that clearer: the Quick Docs pop-up still works (Ctrl+Q) but the palette is no longer shown on the pop-up.

The differences between a working pop-up and a non-working pop-up are the upgrades:
Android Studio: 3.4.2    -> 4.0
Flutter Plugin: 39.0.1   -> 46.0.2
Dart Plugin:    183.6270 -> 193.7361
Both tests used Flutter version 1.17.3. 

flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.17.3 at /home/john/Programs/flutter
    • Framework revision b041144f83 (10 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/john/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /home/john/Programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/john/Programs/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

HTH :)

![Screenshot from 2020-06-14 20-47-39](https://user-images.githubusercontent.com/60894773/84604191-25bcb500-ae8c-11ea-9ed1-a6a140e7e256.png)
![Flutter and Dart Update](https://user-images.githubusercontent.com/60894773/84604194-2d7c5980-ae8c-11ea-9313-4827c41f5768.png)
![Studio Update](https://user-images.githubusercontent.com/60894773/84604195-2ead8680-ae8c-11ea-94b4-b43a2a8daad1.png)
![Color pop-up Linux](https://user-images.githubusercontent.com/60894773/84604198-2fdeb380-ae8c-11ea-91b2-a14640eb89c9.png)

**Comment by SadSack963** [comment] 2020-06-28 00:00
I have just discovered that the palette does work in Visual Studio Code, but still not in Android Studio:
![image](https://user-images.githubusercontent.com/60894773/85934464-b3f85880-b8da-11ea-9d35-b9675c19d7fd.png)

**Comment by TahaTesser** [comment] 2020-07-01 09:24
Looks like plugin issue, not an issue with Flutter itself 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-01 09:24 UTC
Labels: in triage

**Comment by SadSack963** [comment] 2020-07-01 10:18
Thanks for the link Taha. I'll open this issue there.
