### ISSUE TITLE
CupertinoNavigationBar middle and trailing will wrap during routes transition

### ISSUE THREAD

**Issue by YaoShuwei** [flutter/flutter#24560] opened 2018-11-20 07:03 UTC
See the flutter_grally demo:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/cupertino/cupertino_navigation_demo.dart

```
[✓] Flutter (Channel master, v0.11.8-pre.11, on Mac OS X 10.13.6 17G3025, locale
    zh-Hans-CN)
    • Flutter version 0.11.8-pre.11 at /Users/yaoshuwei/flutter
    • Framework revision 9e0ce09f64 (5 hours ago), 2018-11-19 20:40:05 -0500
    • Engine revision a4afd19a97
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/yaoshuwei/Library/Android/sdk
    • Android NDK at /Users/yaoshuwei/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • MI 8       • 96c89e18                                 • android-arm64 •
      Android 9 (API 28)
    • iPhone (2) • 9170a974b32c4b641a950c2eb12d721497444ca0 • ios           •
      iOS 12.0.1

• No issues found!
```

**Comment by xster** [comment] 2018-11-21 02:56
Which device did you run it on? What's the language and/or accessibility font size on the phone?

**Comment by YaoShuwei** [comment] 2018-11-21 10:44
> Which device did you run it on? What's the language and/or accessibility font size on the phone?

I run it on Mi 8(Android Pie).The system language is Chinese,both Englist and Chinese will wrap on the middle text.The font size is all default.

**Comment by xster** [comment] 2018-12-03 19:58
Unfortunately I don't have that phone in the rack. Is it reproducible on an emulator?

**Comment by xster** [comment] 2020-03-11 17:30
I'm going to tentatively close this since we made a few tweaks to the font size tweening since 2018. Feel free to re-open a new issue if the problem is still present.

**Closed by xster** 2020-03-11 17:30 UTC
Labels: f: cupertino, f: routes, framework, team: gallery
