### ISSUE TITLE
[Engine Crash] Flutter can't decode this image and Crashes

### ISSUE THREAD

**Issue by nancyyihao** [flutter/flutter#116756] opened 2022-12-09 02:32 UTC
https://img.kwcdn.com/product/1dab9add96/804826ef-5a66-4d10-932a-050581ccc231_1200x1200.jpeg

I put the above image in a new Image.network() and flutter always return error:

```
[, , 0]:3997_FlutterError.onError dumpErrorToConsole exception=Exception: Codec failed to produce an image, possibly due to invalid image data.
```

Error occurs in Android and iOS，it's ok in chrome broswer.

Flutter Version: 3.3.6

iOS crash stack:

```
flutter::SingleFrameCodec::getNextFrame(_Dart_Handle*)	single_frame_codec.cc:36
flutter::SingleFrameCodec::getNextFrame(_Dart_Handle*)	single_frame_codec.cc:31
flutter::Codec_getNextFrame(_Dart_NativeArguments*)	codec.cc:27
dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))	native_entry.cc:217
App#Stub_CallAutoScopeNative
App#Codec._getNextFrame_16946
App#Codec.getNextFrame_16945
App#MultiImageStreamCompleter._decodeNextFrameAndSchedule_16924
App#MultiImageStreamCompleter._handleCodecReady_16933
App#new_MultiImageStreamCompleter.anonymous_closure_118036

dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)	dart_entry.cc:145
dart::DartEntry::InvokeCallable(dart::Thread*, dart::Function const&, dart::Array const&, dart::Array const&)	dart_entry.cc:294
Dart_InvokeClosure	dart_api_impl.cc:4713
std::__1::__function::__func<flutter::SingleFrameCodec::getNextFrame(_Dart_Handle*)::$_0, std::__1::allocator<flutter::SingleFrameCodec::getNextFrame(_Dart_Handle*)::$_0>, void (sk_sp<flutter::DlImage>)>::operator()(sk_sp<flutter::DlImage>&&)	functional:1727
std::__1::__function::__func<fml::internal::CopyableLambda<flutter::ImageDecoderSkia::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::__1::function<void (sk_sp<flutter::DlImage>)> const&)::$_0::operator()(flutter::SkiaGPUObject<SkImage>, fml::tracing::TraceFlow) const::{lambda()#1}>, std::__1::allocator<fml::internal::CopyableLambda<flutter::ImageDecoderSkia::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::__1::function<void (sk_sp<flutter::DlImage>)> const&)::$_0::operator()(flutter::SkiaGPUObject<SkImage>, fml::tracing::TraceFlow) const::{lambda()#1}> >, void ()>::operator()()	functional:1727
fml::MessageLoopImpl::FlushTasks(fml::FlushType)	message_loop_impl.cc:126
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)	message_loop_darwin.mm:80
___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
___CFRunLoopDoTimer
___CFRunLoopDoTimers
___CFRunLoopRun
_CFRunLoopRunSpecific
fml::MessageLoopDarwin::Run()	message_loop_darwin.mm:51
std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0> >(void*)	thread:291
__pthread_start
```

Android crash stack, no more stack frame.
```
flutter::SingleFrameCodec::getNextFrame(_Dart_Handle*)	../../flutter/lib/ui/painting/single_frame_codec.cc:36
#01 pc 005b430c  /data/app/~~Qfphk0PEBJKOhCIRAOmqTQ==/com.dingdang.gogo-C7hA5Ke8D8rVXK3l6l6AHw==/lib/arm/libflutter.so
******* Java stack for JNI crash *******
(no managed stack frames)
```

**Comment by nancyyihao** [comment] 2022-12-09 10:10
> Hi @nancyyihao, does the crash happen in release mode only or it occurs in debug mode as well? What device(s) are experiencing the crash?
> 
> I've tested this locally, but the only issue I get is the image decoding exception below.
> 
> Can you also upgrade to `stable 3.3.9` to see if you experience the crash?
> 
> sample used
> ```
> ════════ Exception caught by image resource service ════════════════════════════
> The following _Exception was thrown resolving an image frame:
> Exception: Codec failed to produce an image, possibly due to invalid image data.
> 
> When the exception was thrown, this was the stack
> Image provider: NetworkImage("https://img.kwcdn.com/product/1dab9add96/804826ef-5a66-4d10-932a-050581ccc231_1200x1200.jpeg", scale: 1.0)
> Image key: NetworkImage("https://img.kwcdn.com/product/1dab9add96/804826ef-5a66-4d10-932a-050581ccc231_1200x1200.jpeg", scale: 1.0)
> ════════════════════════════════════════════════════════════════════════════════
> ```

@danagbemava-nc as you can see, it crash in Release mode,  not Debug mode. I got the same message in Debug mode.

crash Device Info:
device: M2007J17C
arch: armeabi-v7a
android version: 11 (API 30).

And I want to know Why codec failed in Flutter, but OK In Chrome browser.

**Comment by danagbemava-nc** [comment] 2022-12-09 13:15
Hi @nancyyihao, when I run in release mode with `flutter run --release`, all I see is a blank screen with the sample in https://github.com/flutter/flutter/issues/116756#issuecomment-1343972814. Can you share a sample that reproduces the engine crash?

**Comment by nancyyihao** [comment] 2022-12-09 14:36
@danagbemava-nc sorry, I don't have the crash device in hand, any idea why the picture decode failed in Flutter? It seems OK on my Mac and google Chrome browser.

**Comment by danagbemava-nc** [comment] 2022-12-12 04:11
> any idea why the picture decode failed in Flutter?

Unfortunately, I do not. 

Is the trace for iOS in https://github.com/flutter/flutter/issues/116756#issue-1485835532 the complete stack trace? 

Can we also get a full list of affected devices so that we can know the severity of the issue? 

Thank you

**Comment by nancyyihao** [comment] 2022-12-12 13:26
@danagbemava-nc Hi, lots of crash and in different devices and variant system version. some crash devices are listed below, there are so many that I can't list them all, it all seems crash in armabi-v7a Android devices, hope it can help.

- iOS

|  Model   | Arch  | System Version |
|  ----  | ----  | ---- |
| iPhone10,3(iPhone X)  | arm64 |16.0
| iPhone9,2(iPhone 7 Plus) | arm64 | 15.7.1
| iPhone10,2(iPhone 8 Plus) | arm64 | 15.4.1
| iPhone11,8(iPhone XR) | arm64e | 16.1.2
| iPhone12,8 | arm64e | 15.7.1


- Android

|  Model   | Arch  | Android Version |
|  ----  | ----  | ---- |
| M2007J17C  | armeabi-v7a | 12
| vivo V3Max A | armeabi-v7a | 5.1.1
| V2055A | armeabi-v7a | 11
| NAM-AL00 | armeabi-v7a | 11
| M2006C3LC | armeabi-v7a | 10
| MI 9| armeabi-v7a | 10
| TRT-TL10 | armeabi-v7a | 7.0
| Redmi 6| armeabi-v7a | 9

**Comment by danagbemava-nc** [comment] 2022-12-13 06:41
Thanks for the info. 

Labeling for further investigation from the team. 

#### Extra information

Using the sample in https://github.com/flutter/flutter/issues/116756#issuecomment-1343972814 the image fails to render on all platforms I tested with the error in the same comment aside the the `WEB_HTML` renderer, where this worked just fine. Running with the `--release ` flag, the app just showed a blank screen (since debug errors are not shown in release mode). There may be something else that triggers the crash but the iOS crash logs in https://github.com/flutter/flutter/issues/116756#issue-1485835532 show some logs related to loading images so it may as well be the image.
Some affected devices are listed in https://github.com/flutter/flutter/issues/116756#issuecomment-1346497418

**Comment by chinmaygarde** [comment] 2023-01-09 19:18
From Triage: We think this issue was fixed in https://github.com/flutter/engine/commit/577337792ccda532903dbd384e0ec364c3fefa4f. Does this still happen in ToT?

**Closed** 2023-01-30 21:09 UTC
Labels: severe: crash, waiting for customer response, engine, a: images, a: production, P4
