### ISSUE TITLE
url starting with "www" are not launched anymore

### ISSUE THREAD

**Issue by deacon78** [flutter/flutter#51299] opened 2020-02-23 21:58 UTC
Hello

I have notice that urls must start with "http" otherwise they are not launched.
This is the case with "www.google.fr" or "www.youtube.com" for example.

Thanks for update

**Comment by stuartmorgan** [comment] 2020-02-24 02:58
What function/class/plugin is this in reference to? Could you provide some sample code to clarify what this is about specifically?

>

**Comment by deacon78** [comment] 2020-02-24 05:21
Hello stuartmorgan
I know but if you put those host names in google chrome, the navigator can reach the url of the web site.
For a non web expert, that can be surprising.
I print an alert message saying the url is invalid and must begin with http.

Here is the function which throw the error : 

` Future _launchURL(String url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }`

**Comment by stuartmorgan** [comment] 2020-02-24 06:43
> I know but if you put those host names in google chrome, the navigator can reach the url of the web site.

Because a browser is intended for browsing the web, so it can guess that the scheme is http(s) and be right essentially every time. `url_launcher` isn't a browser, it's a way of launching arbitrary URLs, registered by arbitrary applications--as the documentation for the plugin says, "The supported URL schemes depend on the underlying platform and installed apps."

> I print an alert message saying the url is invalid and must begin with http.

If, in your specific use case, you believe that http is the scheme the user intends, then you can feel free to add it yourself before calling the plugin.

Closing as this is working as intended. You need to provide it a valid URL.

**Closed by stuartmorgan** 2020-02-24 06:43 UTC
Labels: p: url_launcher, plugin
