### ISSUE TITLE
Firebase phone auth is not working on IOS

### ISSUE THREAD

**Issue by Abosrie** [flutter/flutter#50441] opened 2020-02-09 14:39 UTC
I'm having an issue with firebase_auth verifyPhoneNumber on iOS. I followed all the requirements on documentation. APN works fine (FCM can be received) & URL Scheme. But whenever verifyPhoneNumber called, the SMS is coming but the auto verification is not working.

Note: the reCAPTCHA is working fine on the simulator. Also, Android is working fine

```
Future<Null> handleSignInMobile(String mobileNumber) async {
    var otpValidateScreen = OtpValidateScreen();

    final PhoneCodeSent smsOTPSent = (String verId, [int forceCodeResend]) {
      setState(() {
        isLoading = false;
      });

      this.verificationId = verId;

     var user = User(userName, userMobile, countryName, countryCode,
          loginOrSignUp, verificationId, forceCodeResend, mobileNumber);
      otpValidateScreen.updateUserDetails(user);
      var route = new MaterialPageRoute(
        builder: (BuildContext context) => otpValidateScreen,
      );
      Navigator.of(context).push(route); 


    };

    print("smsOTPSent: + $smsOTPSent");

    final PhoneVerificationCompleted verificationCompleted =
        (FirebaseUser user) {
      otpValidateScreen.phoneVCEvent(user);
    };

     print("verificationCompleted: + $verificationCompleted");

    final PhoneVerificationFailed verificationFailed =
        (AuthException exception) {
      print("${exception.message}");

    };

    print("verificationFailed: + $verificationFailed");

    final PhoneCodeAutoRetrievalTimeout retrievalTimeout =
        (String verificationId) {
      this.verificationId = verificationId;

    };

    print("retrievalTimeout: + $retrievalTimeout");

    try {
      await auth.verifyPhoneNumber(
          phoneNumber: mobileNumber,
          timeout: const Duration(seconds: 30),
          verificationCompleted: verificationCompleted,
          verificationFailed: verificationFailed,
          codeSent: smsOTPSent,
          codeAutoRetrievalTimeout: retrievalTimeout);
    } catch (onError) {
      setState(() {
        isLoading = false;
      });

      print("${onError.message}");
    }
  }
```

some output:

> flutter: smsOTPSent: + Closure: (String, [int]) => Null
> flutter: verificationCompleted: + Closure: (FirebaseUser) => Null
> flutter: verificationFailed: + Closure: (AuthException) => Null
> flutter: retrievalTimeout: + Closure: (String) => Null
> flutter: verId: + AM5PThCS_XDvaao6cXeZyhIVx7VxSS5-xxxxx....

**Comment by TahaTesser** [comment] 2020-02-10 10:39
Hi @Abosrie 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by TahaTesser** 2020-02-10 10:39 UTC

**Comment by amitkabra59** [comment] 2020-06-30 13:50
> I'm having an issue with firebase_auth verifyPhoneNumber on iOS. I followed all the requirements on documentation. APN works fine (FCM can be received) & URL Scheme. But whenever verifyPhoneNumber called, the SMS is coming but the auto verification is not working.
> 
> Note: the reCAPTCHA is working fine on the simulator. Also, Android is working fine
> 
> ```
> Future<Null> handleSignInMobile(String mobileNumber) async {
>     var otpValidateScreen = OtpValidateScreen();
> 
>     final PhoneCodeSent smsOTPSent = (String verId, [int forceCodeResend]) {
>       setState(() {
>         isLoading = false;
>       });
> 
>       this.verificationId = verId;
> 
>      var user = User(userName, userMobile, countryName, countryCode,
>           loginOrSignUp, verificationId, forceCodeResend, mobileNumber);
>       otpValidateScreen.updateUserDetails(user);
>       var route = new MaterialPageRoute(
>         builder: (BuildContext context) => otpValidateScreen,
>       );
>       Navigator.of(context).push(route); 
> 
> 
>     };
> 
>     print("smsOTPSent: + $smsOTPSent");
> 
>     final PhoneVerificationCompleted verificationCompleted =
>         (FirebaseUser user) {
>       otpValidateScreen.phoneVCEvent(user);
>     };
> 
>      print("verificationCompleted: + $verificationCompleted");
> 
>     final PhoneVerificationFailed verificationFailed =
>         (AuthException exception) {
>       print("${exception.message}");
> 
>     };
> 
>     print("verificationFailed: + $verificationFailed");
> 
>     final PhoneCodeAutoRetrievalTimeout retrievalTimeout =
>         (String verificationId) {
>       this.verificationId = verificationId;
> 
>     };
> 
>     print("retrievalTimeout: + $retrievalTimeout");
> 
>     try {
>       await auth.verifyPhoneNumber(
>           phoneNumber: mobileNumber,
>           timeout: const Duration(seconds: 30),
>           verificationCompleted: verificationCompleted,
>           verificationFailed: verificationFailed,
>           codeSent: smsOTPSent,
>           codeAutoRetrievalTimeout: retrievalTimeout);
>     } catch (onError) {
>       setState(() {
>         isLoading = false;
>       });
> 
>       print("${onError.message}");
>     }
>   }
> ```
> 
> some output:
> 
> > flutter: smsOTPSent: + Closure: (String, [int]) => Null
> > flutter: verificationCompleted: + Closure: (FirebaseUser) => Null
> > flutter: verificationFailed: + Closure: (AuthException) => Null
> > flutter: retrievalTimeout: + Closure: (String) => Null
> > flutter: verId: + AM5PThCS_XDvaao6cXeZyhIVx7VxSS5-xxxxx....

Hi @Abosrie 
Did you manage to solve the issue? I am facing the exact same issue with similar situation

**Comment by dave-k** [comment] 2020-07-11 04:08
@amitkabra59 @Abosrie 
Did either of you solve this issue? I am also facing the same situation. The SMS code is sent but verificationCompleted(), the instant verification callback, is not called.
