### ISSUE TITLE
Issue from website page Get Started: Install on macOS

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#16968] opened 2018-04-25 20:15 UTC
From URL: https://flutter.io/setup-macos/
Devon says this is a bug. Shams says this should be fixed before I/O.

I followed the instructions to set up the Android emulator, but I cannot start the emulator from IntelliJ. I get "PANIC: Missing emulator engine program for 'x86' CPU."

If I start Android Studio and open Tools>AVD Manager, I can start the emulator from there. If I do that, then that emulator shows up in IntelliJ and I can target it.

**Comment by mit-mit** [comment] 2018-04-26 12:59
I don't understand what the issue is. The current steps do create the AVD via AVD Manager. @wmleler @devoncarew can you elaborate?

**Comment by DanTup** [comment] 2018-04-26 15:47
There's also additional wonkiness if you don't run `emulator` from its own folder:

```
dantup-macbookpro:Dart-Code dantup$ emulator -list-avds
Danny_Nexus
Nexus_5X_API_27_x86

dantup-macbookpro:Dart-Code dantup$ emulator -avd Nexus_5X_API_27_x86
PANIC: Missing emulator engine program for 'x86' CPU.

dantup-macbookpro:Dart-Code dantup$ emulator -avd Danny_Nexus
[140735575937856]:ERROR:android/android-emu/android/qt/qt_setup.cpp:28:Qt library not found at ../emulator/lib64/qt/lib
Could not launch '/Users/dantup/Dev/Dart-Code/../emulator/qemu/darwin-x86_64/qemu-system-i386': No such file or directory

dantup-macbookpro:Dart-Code dantup$ pushd ~/Library/Android/sdk/emulator; emulator -avd Danny_Nexus; popd
~/Library/Android/sdk/emulator ~/Dev/Dart-Code
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"
```

I'll see if I can track down how Android Studio launches them

**Comment by devoncarew** [comment] 2018-04-26 15:54
Ah, the cwd is important? I'll check what we're doing in IntelliJ.

**Comment by devoncarew** [comment] 2018-04-26 15:56
(we're currently running it from the android sdk home dir - one level up from the emulator tool)

**Comment by DanTup** [comment] 2018-04-26 16:25
Not sure if I have all the source code here though; there are methods like `isAvdRunning` that don't seem to be reference anywhere. I'm looking at the `base-studio-master-dev` branch of the Android repo I cloned. I wonder whether it's not all in here.

**Comment by zoechi** [comment] 2018-12-04 12:19
Is this still an issue?

**Comment by BondarenkoStas** [comment] 2019-10-24 11:49
Is this still an issue?

**Comment by DanTup** [comment] 2019-10-24 13:13
I think this is a dupe of https://github.com/flutter/flutter-intellij/issues/2351 and is fixed by https://github.com/flutter/flutter-intellij/pull/2383. The Android SDK has two `emulator` binaries and one of them is less-good than the other one. I believe Flutter, IntelliJ and VS Code all prefer the good one now, so this shouldn't be an issue anymore.

**Closed by DanTup** 2019-10-24 13:13 UTC
Labels: d: website - content, tool
