### ISSUE TITLE
Flutter web: swipe back action does not work

### ISSUE THREAD

**Issue by steebchen** [flutter/flutter#91161] opened 2021-10-02 17:41 UTC
The swipe back action for flutter web is not really working for me. You can see that it's quite buggy in general, e.g. https://gallery.flutter.dev/#/.

In my own app, it's even worse, as the swipe action goes out of the whole flutter web app.

## Steps to Reproduce

1. Navigate to another route, then swipe right to navigate back.

For the second case:

1. Host any non-flutter html code at /
2. Host a flutter web app at /app/ and set `<base href="/app/"/>`
3. Navigate to /, then /app, then some link inside of the flutter app, then swipe back
4. The animation is super buggy and the back swipe will go back to the non-flutter web app at / instead of just going back inside of the flutter navigator

**Expected results:** 

No issue.

**Actual results:** 

1

on https://gallery.flutter.dev/#/.

https://user-images.githubusercontent.com/5013932/135726792-eee21ec1-7ec2-4877-a17a-0609216e540a.MP4

2

on https://polarwealth.com

https://user-images.githubusercontent.com/5013932/135726796-ca24a54b-53c5-4224-a4ee-e8bf639bdaba.MP4

<details>
  <summary>Logs</summary>

```
```

```
```

```
❯ flutter doctor -v         
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.6 20G165 darwin-x64, locale en-DE)
    • Flutter version 2.5.0 at /usr/local/Caskroom/flutter/2.2.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/luca/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 59.0.3
    • Dart plugin version 211.7727

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Users/luca/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Users/luca/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.4746.92/IntelliJ IDEA.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.4746.57

[✓] Connected device (3 available)
    • M2006C3LG (mobile) • FQCU59BUIZ79FIRW • android-arm    • Android 10 (API 29)
    • macOS (desktop)    • macos            • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 94.0.4606.61

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2021-10-04 09:59
Hi @steebchen 
This seems to work fine on macOS safari, the issue exists on iOS, a duplicate of https://github.com/flutter/flutter/issues/55913

**Closed by TahaTesser** 2021-10-04 09:59 UTC
Labels: in triage
