### ISSUE TITLE
TextField invisible characters

### ISSUE THREAD

**Issue by iwbas** [flutter/flutter#67386] opened 2020-10-06 07:40 UTC
## Steps to Reproduce

1. Enter some numbers
2. Enter any characters, but number
3. Delete the number

**Expected results:** the last number should be deleted

**Actual results:** to delete the last number you need to delete all entered characters at step 2.

```dart
/// Flutter code sample for TextField

// This sample shows how to get a value from a TextField via the [onSubmitted]
// callback.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  TextEditingController _controller;

  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          inputFormatters: [ FilteringTextInputFormatter.digitsOnly,],
          controller: _controller,
          onSubmitted: (String value) async {
            await showDialog<void>(
              context: context,
              builder: (BuildContext context) {
                return AlertDialog(
                  title: const Text('Thanks!'),
                  content: Text('You typed "$value".'),
                  actions: <Widget>[
                    FlatButton(
                      onPressed: () {
                        Navigator.pop(context);
                      },
                      child: const Text('OK'),
                    ),
                  ],
                );
              },
            );
          },
        ),
      ),
    );
  }
}
```

codepen source: https://codepen.io/iwbas/pen/PozYQrB

**Comment by sidrao2006** [comment] 2020-10-06 08:17
Hello @iwbas , there is an open issue addressing this problem here ( #67236 )
Please close this issue

**Comment by xclud** [comment] 2020-10-06 08:21
#67391

**Comment by darshankawar** [comment] 2020-10-06 10:25
Closing this as duplicate of [67236](https://github.com/flutter/flutter/issues/67236)

**Closed by darshankawar** 2020-10-06 10:25 UTC
