### ISSUE TITLE
TextInputFormatter always keeps an unformatted value

### ISSUE THREAD

**Issue by tvqphong001** [flutter/flutter#69166] opened 2020-10-28 04:11 UTC
My formatter 
```
class EditFullNameFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    if(checkSpecialString(newValue.text)){
      print("oldValue ${oldValue.text}");
      print("newValue ${newValue.text}");
      return TextEditingValue(
        text: '${oldValue.text}',
        selection: TextSelection.collapsed(offset: oldValue.selection.baseOffset),
      );
    }
    return newValue;
  }
}
```
This is normal function check special String
```
bool checkSpecialString(String string, {bool space = true}) {
    for (int i = 0; i < string.length; i++) {
      if (!((space ? string.codeUnitAt(i) == 32 : false) || // space
          (string.codeUnitAt(i) >= 48 && string.codeUnitAt(i) <= 57) || // 0 -9
          (string.codeUnitAt(i) >= 65 && string.codeUnitAt(i) <= 90) || // A-Z
          (string.codeUnitAt(i) >= 97 && string.codeUnitAt(i) <= 122))) // a-z
      {
        return false;
      }
    }
    return true;
  }
```

Flutter doctor: 
```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

Though `return TextEditingValue` but newValue always have `@` , I don't know why newValue keep any thing I type and my TextField always show `hello`, it will run in ` if(checkSpecialString(newValue.text)){...}`
```

2020-10-28 11:03:25.613 27363-27529/vn.wee.facepayapp I/flutter: oldValue hello
2020-10-28 11:03:25.613 27363-27529/vn.wee.facepayapp I/flutter: newValue hello@
2020-10-28 11:03:26.790 27363-27529/vn.wee.facepayapp I/flutter: oldValue hello
2020-10-28 11:03:26.790 27363-27529/vn.wee.facepayapp I/flutter: newValue hello@j
2020-10-28 11:03:31.927 27363-27529/vn.wee.facepayapp I/flutter: oldValue hello
2020-10-28 11:03:31.927 27363-27529/vn.wee.facepayapp I/flutter: newValue hello@js
2020-10-28 11:03:37.786 27363-27529/vn.wee.facepayapp I/flutter: oldValue hello
2020-10-28 11:03:37.787 27363-27529/vn.wee.facepayapp I/flutter: newValue hello@jsd
```

**Comment by pedromassangocode** [comment] 2020-10-28 10:11
Hi @tvqphong001 
Can you please provide your `flutter doctor -v` a minimal complete reproducible code sample?
I need a code that anyone can just copy/paste to reproduce the issue.
 
Thank you

**Comment by tvqphong001** [comment] 2020-11-04 03:10
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),

            TextField(
              inputFormatters: [
                EditUsernameFormatter()
              ],
            )
          ],
        ),
      ),
    );
  }
}

class EditUsernameFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    if(!checkSpecialString(newValue.text,space: false)){
      return TextEditingValue(
        text: oldValue.text,
        selection:TextSelection.collapsed(offset: oldValue.selection.baseOffset),
      );
    }
    return newValue;
  }

}

bool checkSpecialString(String string, {bool space = true}) {
  for (int i = 0; i < string.length; i++) {
    if (!((space ? string.codeUnitAt(i) == 32 : false) || // space
        (string.codeUnitAt(i) >= 48 && string.codeUnitAt(i) <= 57) || // 0 -9
        (string.codeUnitAt(i) >= 65 && string.codeUnitAt(i) <= 90) || // A-Z
        (string.codeUnitAt(i) >= 97 && string.codeUnitAt(i) <= 122))) // a-z
        {
      return false;
    }
  }
  return true;
}

```

**Comment by tvqphong001** [comment] 2020-11-04 03:11
@pedromassangocode you can copy it and run

**Comment by pedromassangocode** [comment] 2020-11-04 08:08
Hi @tvqphong001 
I cannot reproduce the issue on latest `master` channel.

This is the logs while I tried to type: `hello@world`. Notice that the @ was removed right after I typed it.

```
I/flutter ( 5024): oldValue: 
I/flutter ( 5024): newValue: h
I/flutter ( 5024): oldValue: h
I/flutter ( 5024): newValue: he
I/flutter ( 5024): oldValue: he
I/flutter ( 5024): newValue: hel
I/flutter ( 5024): oldValue: hel
I/flutter ( 5024): newValue: hell
I/flutter ( 5024): oldValue: hell
I/flutter ( 5024): newValue: hello
I/flutter ( 5024): oldValue: hello
I/flutter ( 5024): newValue: hello@
I/flutter ( 5024): oldValue: hello
I/flutter ( 5024): newValue: hello
I/flutter ( 5024): oldValue: hello
I/flutter ( 5024): newValue: hellow
I/flutter ( 5024): oldValue: hellow
I/flutter ( 5024): newValue: hellowo
I/flutter ( 5024): oldValue: hellowo
I/flutter ( 5024): newValue: hellowor
I/flutter ( 5024): oldValue: hellowor
I/flutter ( 5024): newValue: helloworl
I/flutter ( 5024): oldValue: helloworl
I/flutter ( 5024): newValue: helloworld
```

The logs from stable channel are slightly different but does not seems to reproduce the issue as well. Am I missing something?
<details><summary>Logs (stable channel)</summary>

```
I/flutter ( 5690): oldValue: 
I/flutter ( 5690): newValue: h
I/flutter ( 5690): oldValue: h
I/flutter ( 5690): newValue: he
I/flutter ( 5690): oldValue: he
I/flutter ( 5690): newValue: hel
I/flutter ( 5690): oldValue: hel
I/flutter ( 5690): newValue: hell
I/flutter ( 5690): oldValue: hell
I/flutter ( 5690): newValue: hello
I/flutter ( 5690): oldValue: hello
I/flutter ( 5690): newValue: hello@
I/flutter ( 5690): oldValue: hello
I/flutter ( 5690): newValue: hello@
I/flutter ( 5690): oldValue: hello
I/flutter ( 5690): newValue: hellow
I/flutter ( 5690): oldValue: hellow
I/flutter ( 5690): newValue: hellowo
I/flutter ( 5690): oldValue: hellowo
I/flutter ( 5690): newValue: hellowor
I/flutter ( 5690): oldValue: hellowor
I/flutter ( 5690): newValue: helloworl
I/flutter ( 5690): oldValue: helloworl
I/flutter ( 5690): newValue: helloworld
```
</details>

<details><summary>sample code (with logs-printing)</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),

            TextField(
              inputFormatters: [
                EditUsernameFormatter()
              ],
            )
          ],
        ),
      ),
    );
  }
}

class EditUsernameFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    print('oldValue: ${oldValue.text}');
    print('newValue: ${newValue.text}\n');

    if(!checkSpecialString(newValue.text,space: false)){
      return TextEditingValue(
        text: oldValue.text,
        selection:TextSelection.collapsed(offset: oldValue.selection.baseOffset),
      );
    }
    return newValue;
  }

}

bool checkSpecialString(String string, {bool space = true}) {
  for (int i = 0; i < string.length; i++) {
    if (!((space ? string.codeUnitAt(i) == 32 : false) || // space
        (string.codeUnitAt(i) >= 48 && string.codeUnitAt(i) <= 57) || // 0 -9
        (string.codeUnitAt(i) >= 65 && string.codeUnitAt(i) <= 90) || // A-Z
        (string.codeUnitAt(i) >= 97 && string.codeUnitAt(i) <= 122))) // a-z
        {
      return false;
    }
  }
  return true;
}
```
</details>

**Comment by liuyasss** [comment] 2020-11-05 10:00
I alse have this problem!!!!!!!!!!!!!!!

**Comment by liuyasss** [comment] 2020-11-05 10:01
I also have this problem!!!!!!!!!!!!!!!

How can i fix it

**Comment by liuyasss** [comment] 2020-11-05 10:07
> Hi @tvqphong001
> I cannot reproduce the issue on latest `master` channel.
> 
> This is the logs while I tried to type: `hello@world`. Notice that the @ was removed right after I typed it.
> 
> ```
> I/flutter ( 5024): oldValue: 
> I/flutter ( 5024): newValue: h
> I/flutter ( 5024): oldValue: h
> I/flutter ( 5024): newValue: he
> I/flutter ( 5024): oldValue: he
> I/flutter ( 5024): newValue: hel
> I/flutter ( 5024): oldValue: hel
> I/flutter ( 5024): newValue: hell
> I/flutter ( 5024): oldValue: hell
> I/flutter ( 5024): newValue: hello
> I/flutter ( 5024): oldValue: hello
> I/flutter ( 5024): newValue: hello@
> I/flutter ( 5024): oldValue: hello
> I/flutter ( 5024): newValue: hello
> I/flutter ( 5024): oldValue: hello
> I/flutter ( 5024): newValue: hellow
> I/flutter ( 5024): oldValue: hellow
> I/flutter ( 5024): newValue: hellowo
> I/flutter ( 5024): oldValue: hellowo
> I/flutter ( 5024): newValue: hellowor
> I/flutter ( 5024): oldValue: hellowor
> I/flutter ( 5024): newValue: helloworl
> I/flutter ( 5024): oldValue: helloworl
> I/flutter ( 5024): newValue: helloworld
> ```
> 
> The logs from stable channel are slightly different but does not seems to reproduce the issue as well. Am I missing something?
> 
> Logs (stable channel)
> sample code (with logs-printing)

you need do 'delete' action  , can find the problem

**Comment by liuyasss** [comment] 2020-11-05 10:14
this is  a bug,  We can pull the last branch stable, it has fix.

**Comment by tvqphong001** [comment] 2020-11-14 04:35
@pedromassangocode @liuyasss You need press more  **special string**, in case press one  **special string** it still no problem

```
I/flutter (27650): newValue: hello
I/flutter (27650): oldValue: hello
I/flutter (27650): newValue: hello%
I/flutter (27650): oldValue: hello
I/flutter (27650): newValue: hello4
I/flutter (27650): oldValue: hello4
I/flutter (27650): newValue: hello4$
I/flutter (27650): oldValue: hello4
I/flutter (27650): newValue: hello4$
I/flutter (27650): oldValue: hello4
I/flutter (27650): newValue: hello4$$
I/flutter (27650): oldValue: hello4
I/flutter (27650): newValue: hello4$$$
I/flutter (27650): oldValue: hello4
I/flutter (27650): newValue: hello4$$$3
I/flutter (27650): oldValue: hello4
I/flutter (27650): newValue: hello4$$$33
I/flutter (27650): oldValue: hello4
I/flutter (27650): newValue: hello4$$$332
```
![Screen Shot 2020-11-14 at 11 35 07](https://user-images.githubusercontent.com/34592697/99139660-73bd2b00-266d-11eb-8fe8-ca22bb0e8889.png)

**Comment by pedromassangocode** [comment] 2020-11-16 06:23
Hi @tvqphong001 
I cannot reproduce this issue on the latest `stable` channel.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by pedromassangocode** [comment] 2020-12-09 09:25
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-09 09:25 UTC
Labels: a: text input, f: material design, framework, in triage, waiting for customer response
