### ISSUE TITLE
Google SignIn throwing error

### ISSUE THREAD

**Issue by RaghavAggiwal** [flutter/flutter#62844] opened 2020-08-04 08:02 UTC
## Steps to Reproduce

I am taking idToken from Google SignIn and authenticating with my backend server. I have a website running and now I am implementing the same functionality in app using same auth api as used by the website. In the developers console, I have generated credentials for an app and filled SHA1 there. I have also created a google-services.json file and have put it into the required folder. Still, I am getting this error.

``` 
Code:
 if (event is GoogleSignInButtonPressed) {
      yield LoginInProgress();

      try {
        GoogleSignIn _googleSignIn = GoogleSignIn(scopes:['email']);
        GoogleSignInAccount user = await _googleSignIn.signIn();
        //this is not printed, the error comes at this line
        logger.i("user: $user");
        GoogleSignInAuthentication googleSignInAuthentication = await user.authentication;

        String idToken = googleSignInAuthentication.idToken;
        logger.i("idToken: $idToken");
        final token = await userRepository.authenticateWithGoogleSignIn(idToken: idToken);

        authenticationBloc.add(AuthenticationLoggedIn(token: token));
        yield LoginInitial();
      } catch (error) {
        yield LoginFailure(error: error.toString());
      }
    }

-- User repository code:
 Future<String> authenticateWithGoogleSignIn({@required String idToken}) async {
    //authenticate using google sign in
    String _apiEndPoint = Config.configApiBaseUrl + "/login";

    //headers
    Map<String, String> headers = {
      'Content-Type': 'application/json; charset=UTF-8',
    };

    //body
    Map<String, dynamic> body = {
      "provider": 3,
      "token": idToken
    };

    final response = await _provider.post(apiEndPoint: _apiEndPoint, headers: headers, body: jsonEncode(body));
    return response["token"].toString();
  }
```

**Expected results:**  Successful sign in.

**Actual results:** Error: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)

<details>
  <summary>Logs</summary>

```
No analysis issues found.
```

```
Flutter doctor output: 

[√] Flutter (Channel master, 1.19.0-2.0.pre, on Microsoft Windows [Version 10.0.17763.678], locale en-IN)
    • Flutter version 1.19.0-2.0.pre at C:\src\flutter
    • Framework revision 9d58a87066 (2 months ago), 2020-05-22 22:37:01 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\raghav.aggiwal\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\raghav.aggiwal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.0

[√] Connected device (1 available)
    • SM A105F • RZ8M5004SKZ • android-arm • Android 10 (API 29)

• No issues found!

```

**Comment by pedromassangocode** [comment] 2020-08-04 11:06
Hi @RaghavAggiwal 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-04 11:06 UTC
