### ISSUE TITLE
flutter-devicelab-linux-18 tests failed `Task failed: DeviceException: No Android devices detected`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#109001] opened 2022-08-04 22:35 UTC
https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_samsung_a02%20openpay_benchmarks__scroll_perf/307/overview
```
Task result:
{
  "success": false,
  "reason": "Task failed: DeviceException: No Android devices detected"
}
```

**Comment by keyonghan** [comment] 2022-08-04 23:00
Both linux-18 and linux-27 failed complaining `No Android devices detected` for `Linux_samsung_a02%20openpay_benchmarks__scroll_perf` only, but succeed on any other tests. This sounds a test related issue.
Marking dup of https://github.com/flutter/flutter/issues/108391 to track there.

**Comment by jmagman** [comment] 2022-08-04 23:03
Hm, are you sure? It's not timing out, `adb devices -l` seems to be empty.

**Comment by keyonghan** [comment] 2022-08-04 23:15
This is what I get on linux18:
```
adb devices -l
List of devices attached
R9HR50FHKCK            device usb:1-3 product:a02qsq model:SM_A025V device:a02q transport_id:2
```

The swarming bot page also shows the device is okay: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-18

Together with the bots are running through for all other tests, I am assuming the issue is caused when running `openpay_benchmarks__scroll_perf`.

We can keep this bug open until @iskakaushik confirms.

**Comment by iskakaushik** [comment] 2022-08-05 17:50
@keyonghan the test succeeded for several runs and started failing consistently:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/1006071/183132739-47976b4f-113e-470f-91d8-7e429e26fd32.png">

I will attempt to run this locally to see if anything has changed, but i'm curious why the devices were reported as zero, it should be using the same exact code to check for devices as any other test.

cc: @jonahwilliams, @dnfield  for any ideas as to what might be going on.

**Comment by dnfield** [comment] 2022-08-05 18:25
Maybe the cable on those machines needs to be jiggled?

Might be easier to try just rebooting the devices though.

**Comment by keyonghan** [comment] 2022-08-05 18:35
> Maybe the cable on those machines needs to be jiggled?
> 
> Might be easier to try just rebooting the devices though.

I am in the lab, and can confirm the cables are stable (they are new original ones coming with the phone).

**Comment by yusuf-goog** [comment] 2022-08-10 19:39
I gave @iskakaushik an a02s device to test at his desk.

The device on linux-18 one seems to be connected and running as far as we can tell.

**Comment by yusuf-goog** [comment] 2022-08-11 21:09
@iskakaushik can you please note the asset number of the device I gave you here.

**Comment by keyonghan** [comment] 2022-09-20 16:23
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-18 has been running tests successfully, and the task `openpay_benchmarks__scroll_perf` has been removed from CI.
Closing here in favor of https://github.com/flutter/flutter/issues/108391

**Closed by keyonghan** 2022-09-20 16:23 UTC
Labels: team: infra
