### ISSUE TITLE
[web] Wrong Icons displayed / Icons font cached after framework update

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#86391] opened 2021-07-14 00:18 UTC
## Bug

There is a bug with the **Material icons**. It happens through the following sequence of events:
1. Users uses **web** app
2. [Icons class](https://api.flutter.dev/flutter/material/Icons-class.html) is updated with new code points in https://github.com/flutter/flutter
3. Web app is updated → **new** Flutter version is deployed
4. User opens web app again
5. Flutter web service worker pulls new app version (with new `Icons` code points)
6. **Old** icons font is pulled → results in completely wrong icons

### Impact

The impact of this bug can be **critical**. See the following screenshots of the proper icons vs. the incorrect cached icons.  
One of the icons in this Flutter web app (ignore the language, focus on the icons) is replaced by 💸, which might seem funny, but is also unacceptable from a product standpoint.

| Cached / wrong version | Proper version |
| :------------------: | :-----------------: |
| ![image](https://user-images.githubusercontent.com/19204050/125540546-8e9783cf-bf69-4bc8-b5fa-922115106bc0.png) | ![image](https://user-images.githubusercontent.com/19204050/125540515-8d5fa316-60a8-485b-9473-6290a7674302.png) |
| ![image](https://user-images.githubusercontent.com/19204050/125540560-205d2796-0699-4883-9105-6147a9b8979f.png) | ![image](https://user-images.githubusercontent.com/19204050/125540525-c8ceb25c-3bfa-4992-8c3f-72b2ed63ff1f.png) |
| ![image](https://user-images.githubusercontent.com/19204050/125540568-0783699a-0389-405b-9281-08fbd202dd18.png) | ![image](https://user-images.githubusercontent.com/19204050/125540534-1cd62cf8-f3ac-4015-9bd0-d8c5de262063.png) |

## Steps to Reproduce

This is an e2e issue, i.e. I cannot provide a minimal sample. What needs to happen for this is for Chrome to cache an old version of the Material icons font but pull a new version of the app.

This happens to us frequently in the mentioned production app, which is why I want to open this issue. Here is the Flutter doctor anyway:

<details><summary>Click to expand versions</summary>

```
[✓] Flutter (Channel stable, 2.2.3, locale en-US)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (12 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Chrome - develop for the web
    • Chrome

[✓] Connected device (3 available)
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.124
```

</details>

## Potentially related

I found the following two references, which I think might be related but both do not duplicate this issue:
* [Question on SO](https://stackoverflow.com/questions/63760883/flutter-material-icons-rendering-random-icons-on-web), which might be the same issue but has no actual answer
* https://github.com/flutter/flutter/issues/75288, which might also be the same cause but was closed

## Potential fix

You might argue that we should change the caching strategy of our web app, however, here are two reasons for why this should be fixed by Flutter:
* We have no way of knowing the Flutter version the app the user receives is running
* On top of that, the icons fonts is not loaded by us but by Flutter, so we cannot control the caching

I think the **service worker** used in Flutter web should fix this issue.  
The icons fonts should be **versioned** with the hash of the `Icons` class (source file?) and then at runtime, Flutter web should only pull the **cached** icon font when the code points have not changed.

I tried to provide as many details as possible - have been seeing the issue for quite a while with varying extent but was reluctant to open an issue so far due to the lack of a minimal sample, however, I think if a web expert takes a look at this issue, they should be able to identify exactly why this happens and how to fix it (hopefully) 🙏

**Comment by bernaferrari** [comment] 2021-07-14 02:37
Probably duplicate of https://github.com/flutter/flutter/issues/85296 or https://github.com/flutter/flutter/issues/83703 ?

**Comment by creativecreatorormaybenot** [comment] 2021-07-14 06:32
@bernaferrari it should be a dupe of https://github.com/flutter/flutter/issues/83703. However, I was not able to find it.

Maybe the additional information here is use for @guidezpl or @yjbanov.

**Comment by maheshmnj** [comment] 2021-07-14 08:50
Hi @creativecreatorormaybenot,
Thanks for filing the issue, closing as this is a duplicate of #83703 please follow up there for further updates. If you disagree feel free to comment and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-07-14 08:50 UTC
Labels: in triage

**Comment by creativecreatorormaybenot** [comment] 2021-07-14 13:42
@maheshmnj I think the issue can be improved. #83703 is missing details in the description as well as the tile. This makes it difficult to find and also difficult to follow-up on it.

**Comment by maheshmnj** [comment] 2021-07-15 05:15
@creativecreatorormaybenot, I agree your fings are detailed and valuable, But I am not sure if it would be right to update the other issue with your findings, but you could always add your findings in the comments of that issue so that the details don't get missed. 
Thank you.
