### ISSUE TITLE
ScrollController.jumpTo() can't be called from within didUpdateWidget

### ISSUE THREAD

**Issue by cvolzke4** [flutter/flutter#30528] opened 2019-04-04 22:29 UTC
I/flutter (30806): Unexpected call to replaceSemanticsActions() method of RawGestureDetectorState.
I/flutter (30806): The replaceSemanticsActions() method can only be called outside of the build phase.
I/flutter (30806): #0      RawGestureDetectorState.replaceSemanticsActions.<anonymous closure> (package:flutter/src/widgets/gesture_detector.dart:737:9)
I/flutter (30806): #1      RawGestureDetectorState.replaceSemanticsActions (package:flutter/src/widgets/gesture_detector.dart:743:6)
I/flutter (30806): #2      ScrollableState.setSemanticsActions (package:flutter/src/widgets/scrollable.dart:380:40)
I/flutter (30806): #3      ScrollPosition._updateSemanticActions (package:flutter/src/widgets/scroll_position.dart:445:13)
I/flutter (30806): #4      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:695:5)
I/flutter (30806): #5      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:318:5)
I/flutter (30806): #6      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:201:7)
I/flutter (30806): #7      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:172:16)
I/flutter (30806): #8      _PostListState.didUpdateWidget (package:blogger.mobile.app/ui/posts/post_list.dart:47:25)
I/flutter (30806): #9      StatefulElement.update (package:flutter/src/widgets/framework.da

**Comment by valerybodak** [comment] 2019-04-26 12:33
I have the same issue when I call:
`Scrollable.ensureVisible(dataKey.currentContext);`

**Comment by bgyhnddr** [comment] 2019-07-26 08:58
I have the same issue

> @override
  void didUpdateWidget(Widget oldWidget) {
    super.didUpdateWidget(oldWidget);
    controller.animateToItem(
      widget.index,
      curve: Curves.ease,
      duration: Duration(milliseconds: 300),
    );
  }

**Comment by escamoteur** [comment] 2019-09-25 11:36
Hi, just want to check if this is still a problem for you.

**Comment by DennisMuchiri** [comment] 2019-10-03 04:02
@escamoteur  yes

**Comment by escamoteur** [comment] 2019-10-04 18:59
@DennisMuchiri could you post the output of `flutter doctor -v` here please?

**Comment by iapicca** [comment] 2019-11-07 14:26
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by vannevar-morgan** [comment] 2019-11-10 19:54
I am also getting this error.
"The following assertion was thrown building FutureBuilder<List<RssItem>>(dirty, state: _FutureBuilderState<List<RssItem>>#39f11):
Unexpected call to replaceSemanticsActions() method of RawGestureDetectorState."

I'm returning a widget with this hierarchy:
FutureBuilder
>>RefreshIndicator
>>>>ScrollablePositionedList

onRefresh:

  Future<Null> _handleRefresh() async {
    await new Future.delayed(new Duration(milliseconds: _refresh_duration_ms));

I'm trying to overdrag down to refresh an rss feed.  If I only drag down, everything works fine, no error is thrown.  If I drag down, then, while showing the refresh indicator I drag any amount in the ScrollablePositionedList I will get this error.  Always happens, easily reproducible.

ScrollablePositionedList is based on ListView but not officially supported.  I'm not sure if this error also occurs with ListView.  I suspect but haven't tested that FutureBuilder isn't necessary to reproduce.  I'll try to put together a minimal code sample to reproduce.

**Comment by vannevar-morgan** [comment] 2019-11-11 08:07
Tested further on this.
Can't reproduce without making a call to ScrollController.jumpTo() while building.

I think my previous post doesn't present anything new.
I moved that call outside of build to a callback which avoids the error.

e.g.,
WidgetsBinding.instance.addPostFrameCallback
or
WidgetsBinding.instance.addPersistentFrameCallback

**Comment by AngusPei** [comment] 2019-11-25 13:01
ScrollController.jumpTo() form didUpdateWidget 

erro:
Unexpected call to replaceSemanticsActions() method of RawGestureDetectorState.

**Comment by escamoteur** [comment] 2019-12-03 12:31
For all having still this problem, please add the output of your `flutter doctor -v`

**Comment by VladyslavBondarenko** [comment] 2020-01-10 09:35
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by VladyslavBondarenko** 2020-01-10 09:35 UTC
Labels: waiting for customer response
