### ISSUE TITLE
Windows gets blue screen after running an app on emulator android studio

### ISSUE THREAD

**Issue by adham-ashraf77** [flutter/flutter#160161] opened 2024-12-12 11:55 UTC
### Steps to reproduce

run the app on the Android emulator Flutter version 3.27.0 to get blue-screen windows
I tried to fix it by add-in  AndroidManifest.xml 

            make EnableImpeller false if it is true and it's by default true in the new update gets the blue screen added down
            
            
              <meta-data
            android:name="io.flutter.embedding.android.EnableImpeller"
            android:value="false" />

### Expected results

app run correctly

### Actual results

get windows 11 blue screen

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![WhatsApp Image 2024-12-12 at 09 39 44_a61c1985](https://github.com/user-attachments/assets/e8c901d9-d550-4744-9d23-d489cad88002)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jonahwilliams** [comment] 2024-12-12 16:47
You will need to report this bug to Android (https://source.android.com/docs/setup/contribute/report-bugs) and/or windows, as there is little we can do with this information

**Comment by darshankawar** [comment] 2024-12-13 07:07
Closing this based on above comment. If anything, write in comments and I'll reopen.

**Closed by darshankawar** 2024-12-13 07:07 UTC
Labels: in triage

**Comment by mmabas77** [comment] 2024-12-19 20:34
Any updates on the problem ?

**Comment by Peppebalzanoo** [comment] 2024-12-21 14:43
Hello,  
I’m experiencing the same issue described above, with the identical *Stop_Code* error. I was trying to create my first project using Flutter, following all the required configuration steps. However, when I attempted to run the `main.dart` file, Windows 11 displayed a blue screen error (BSOD) similar to the one shown earlier.  

The project I launched is the default one automatically generated by Android Studio, so no modifications or customizations have been made. Unfortunately, I’m unable to provide any additional information about the error.  

**System details**:  
- **Processor**: Intel i7-10700  
- **RAM**: 32 GB  
- **Operating System**: Windows 11 Pro, version 24H2, build 26100.2605  
- **IDE**: Android Studio Ladybug | 2024.2.1 Patch 3  

I don’t believe the issue is related to my hardware performance, as while my setup is not brand new, it’s still capable of handling Flutter development.  

For now, I’m forced to postpone my first experience with Flutter, which is quite disappointing. I hope you can help me identify the cause of this issue and find a solution.  

Thank you in advance for your assistance!

**Comment by maksatgw** [comment] 2024-12-22 19:34
Hello,
I’m also experiencing the same issue described above

No modifications are made in the project. Even when trying to run counter app, I also got exact same Stop Code error. I can get builds on api 33 without having problem. 

System details:

- Processor: Intel i7-10750H
- RAM: 16GB
- GPU: GTX1650TI
- Operating System: Windows 10 Home, version 10.0.19045 build 19045
- Android Studio Iguana | 2023.2.1 Patch 1
- VSCode

**Comment by ozcanbayram** [comment] 2024-12-22 22:38
### **The reason for this error may be that your video card driver is not up to date. (e.g. NVIDIA, Intel)**

_**I am using NVIDIA and I updated as follows:**_

- Go to NVIDIA Driver Download Page: [https://www.nvidia.com/en-us/drivers/](url)

- Choose your product type and model (For example):
Product Type: GeForce
Product Series: The series of your card (for example GeForce RTX 30 Series).
Product: Your card model (for example RTX 3060).
Operating System: The operating system you are using (Windows 10, 11, etc.).

- Download the resulting driver and run the file.

- Install Driver

- After the installation is complete, restart your computer.




### **! If you are using intel**

- Go to Intel's Driver Download Page

- Learn Your Processor Model:
(Click Start > Run > type dxdiag and press Enter.)
In the window that opens, go to the "System Information" tab and check the model of your processor 

- On the driver download page, select the "Graphics" category.

- Find the graphics driver for your processor model and select the version compatible with your operating system.

- Download the relevant driver and start the installation process by running the file.

- After the installation is complete, restart your computer.

**_! If this solution solves your error, I would be happy to give you feedback._**

**Comment by BerkSartik** [comment] 2024-12-23 08:15
- Open the `C:\Users\user\.android` folder.
- Create an `advancedFeatures.ini` file.
- Add the commands below to it.
```
Vulkan=off
GLDirectMem=on
```
- Do `flutter clean` `flutter run`

This is what removed the computer freezing issue in API 34. Apart from this, the emulator was closing itself in API 33, and it was completely resolved.

**Comment by adham-ashraf77** [comment] 2024-12-24 08:54
> * Open the `C:\Users\user\.android` folder.
> * Create an `advancedFeatures.ini` file.
> * Add the commands below to this file.
> 
> ```
> Vulkan=off
> GLDirectMem=on
> ```
> 
> * Do `flutter clean` `flutter run`
> 
> This is what removed the computer freezing issue in API 34. Apart from this, the emulator was closing itself in API 33, and it was completely resolved.

Is this a temporary solution and, what else will this solution affect on something else?
