### ISSUE TITLE
Use initWithEngine:nibName:bundle: method to create FlutterViewController, and then setInitialRoute not working

### ISSUE THREAD

**Issue by X-Liang** [flutter/flutter#27216] opened 2019-01-29 04:36 UTC
When I use `initWithEngine:nibName:bundle:` to create `FlutterViewController`, and then `setInitialRoute:` ;I find it doesn't work; When I use `window.defaultRouteName` in `main.dart` I get `'/'`
This is the code:
```objective-c
// Appdelegate

    FlutterEngine *engine = [[FlutterEngine alloc] initWithName:@"io.flutter" project:nil allowHeadlessExecution:YES];
    self.engine = engine;
    [self.engine runWithEntrypoint:nil];

// ViewController

    FlutterEngine *flutterEngine = [(AppDelegate *)[[UIApplication sharedApplication] delegate] engine];

    FlutterViewController* flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];

    [flutterViewController setInitialRoute:@"myApp"];
```
```dart
// main.dart

    void main() => runApp(_widgetForRoute(window.defaultRouteName));

    Widget _widgetForRoute(String route) {
      switch (route) {
        case 'myApp':
          return new MyApp();
        case 'home':
          return new HomePage();
        default:
          return Center(
            child: Text('Unknown route: $route', textDirection: TextDirection.ltr),
          );
      }
    }
```
I always get a Text and content is ''Unknown route: /'

**Comment by kangwang1988** [comment] 2019-01-29 07:30
@X-Liang 
`flutter doctor -v` and a minimal demo project which can reproduce this issue would be helpful.

**Comment by X-Liang** [comment] 2019-01-29 07:37
https://github.com/X-Liang/NativeWithFlutter This is Demo link

**Comment by kangwang1988** [comment] 2019-01-29 15:48
Duple of: https://github.com/flutter/flutter/issues/23736
I've verified this issue is resolved in latest master.

**Comment by chengge0921** [comment] 2019-02-11 02:51
> When I use `initWithEngine:nibName:bundle:` to create `FlutterViewController`, and then `setInitialRoute:` ;I find it doesn't work; When I use `window.defaultRouteName` in `main.dart` I get `'/'`
> This is the code:
> 
> ```objc
> // Appdelegate
> 
>     FlutterEngine *engine = [[FlutterEngine alloc] initWithName:@"io.flutter" project:nil allowHeadlessExecution:YES];
>     self.engine = engine;
>     [self.engine runWithEntrypoint:nil];
> 
> // ViewController
> 
>     FlutterEngine *flutterEngine = [(AppDelegate *)[[UIApplication sharedApplication] delegate] engine];
> 
>     FlutterViewController* flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
> 
>     [flutterViewController setInitialRoute:@"myApp"];
> ```
> 
> ```dart
> // main.dart
> 
>     void main() => runApp(_widgetForRoute(window.defaultRouteName));
> 
>     Widget _widgetForRoute(String route) {
>       switch (route) {
>         case 'myApp':
>           return new MyApp();
>         case 'home':
>           return new HomePage();
>         default:
>           return Center(
>             child: Text('Unknown route: $route', textDirection: TextDirection.ltr),
>           );
>       }
>     }
> ```
> 
> I always get a Text and content is ''Unknown route: /'

你好，你的这个问题解决了吗？

**Comment by lupeihong** [comment] 2019-02-13 13:52
I have the same problem

//AppDelegate
self.flutterEngine = [[FlutterEngine alloc] initWithName:@"io.flutter" project:nil];
[self.flutterEngine runWithEntrypoint:nil];
[GeneratedPluginRegistrant registerWithRegistry:self.flutterEngine];

//ViewController
FlutterViewController *flutterViewController = [FlutterViewController new];
 [flutterViewController setInitialRoute:@"myApp"];


//main.dart
window.defaultRouteName  Is always ‘/’

**Comment by zoechi** [comment] 2019-02-13 16:11
@lupeihong if it's the same problem, why did you create another issue? #27882

**Comment by yehot** [comment] 2019-02-14 10:00
Same problem.

But weird, use `FlutterViewController *flutterViewController = [FlutterViewController new];`  to init the `FlutterViewController`  ,  the `setInitialRoute`  work fine. 

So what's different between  `[FlutterViewController new]` and ` [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil]` ?

**Comment by ungacy** [comment] 2019-02-19 10:11
+1

**Comment by zoechi** [comment] 2019-02-19 10:21
@ungacy 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by DavidSonNguyen** [comment] 2019-02-22 04:19
I use Swift, and i found problem is `self.flutterEngine?.run(withEntrypoint: nil)` in document [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url). If you do like that, `FlutterEngine` will run before you create `FlutterViewController` so you cannot `setInitialRoute`.
To solve, you must init `FlutterViewController` without `FlutterEngine` `let flutterViewController = FlutterViewController(nibName: nil, bundle: nil)`, and `setInitialRoute`, final call `flutterEngine?.run(withEntrypoint: nil)`.

**Comment by YoungJam** [comment] 2019-02-26 08:33
+1

**Comment by zoechi** [comment] 2019-02-26 08:34
@YoungJam 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by kidzss** [comment] 2019-03-06 02:13
I solved the problem.
//=======================

@interface XXFlutterViewController : FlutterViewController

@EnD

(void)viewDidLoad {
[super viewDidLoad];
// Do any additional setup after loading the view.
FlutterEngine *flutterEngine = self.engine;

[GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
//custom futter plugin
[XXXFlutterBridge registerWithRegistry:flutterEngine];
}

//open flutter vc
XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
[flutterViewController setInitialRoute:@"xxxxx/xxxx"];

**Comment by kidzss** [comment] 2019-03-06 02:19
I solved the problem.
//=======================

@interface XXFlutterViewController : FlutterViewController

@EnD

(void)viewDidLoad {
[super viewDidLoad];
// Do any additional setup after loading the view.
FlutterEngine *flutterEngine = self.engine;

[GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
//custom futter plugin
[XXXFlutterBridge registerWithRegistry:flutterEngine];
}

//open flutter vc
XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
[flutterViewController setInitialRoute:@"xxxxx/xxxx"];

**Comment by lihui2333** [comment] 2019-03-06 02:26
it works on me @kidzss

**Comment by michealstrong** [comment] 2019-03-14 14:01
> I solved the problem.
> //=======================
> 
> @interface XXFlutterViewController : FlutterViewController
> 
> @EnD
> 
> (void)viewDidLoad {
> [super viewDidLoad];
> // Do any additional setup after loading the view.
> FlutterEngine *flutterEngine = self.engine;
> 
> [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
> //custom futter plugin
> [XXXFlutterBridge registerWithRegistry:flutterEngine];
> }
> 
> //open flutter vc
> XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> [flutterViewController setInitialRoute:@"xxxxx/xxxx"];

Didn't U find the flutterVC dont release in this way?

**Comment by michael-chiu** [comment] 2019-03-15 11:30
I am still experiencing this issue on iOS platform, with the Flutter version shown below :

// --------- flutter doctor summary --------- //

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.10, on Mac OS X 10.14 18A391, locale en-HK)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.3)
[✓] Connected device (3 available)

// --------- flutter doctor summary --------- //

I am following the official guide on [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url).

SetInitialRoute() is working when using FlutterViewController(project: nil, nibName: nil, bundle: nil), however, this seems make the Flutter plugins not found with the FlutterViewController, when I try to access methods in Flutter plugins, it throws MissingPluginException. It seems that because of those Plugins are register with FlutterEngine, the FlutterViewController will not find them if not connected with the FlutterEngine.

Using FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil), makes the plugins work, but SetInitialRoute() is not working.

Is there any way or alternative to solve this issue, making both setInitialRoute and plugins work in the same FlutterViewController? Thanks!

**Comment by Lolingew** [comment] 2019-04-25 12:00
> > I solved the problem.
> > //=======================
> > @interface XXFlutterViewController : FlutterViewController
> > @EnD
> > (void)viewDidLoad {
> > [super viewDidLoad];
> > // Do any additional setup after loading the view.
> > FlutterEngine *flutterEngine = self.engine;
> > [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
> > //custom futter plugin
> > [XXXFlutterBridge registerWithRegistry:flutterEngine];
> > }
> > //open flutter vc
> > XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> > [flutterViewController setInitialRoute:@"xxxxx/xxxx"];
> 
> Didn't U find the flutterVC dont release in this way?

I meet the problem... almost nothing released...

**Comment by yxwandroid** [comment] 2019-05-10 16:10
> When I use `initWithEngine:nibName:bundle:` to create `FlutterViewController`, and then `setInitialRoute:` ;I find it doesn't work; When I use `window.defaultRouteName` in `main.dart` I get `'/'`
> This is the code:
> 
> ```objc
> // Appdelegate
> 
>     FlutterEngine *engine = [[FlutterEngine alloc] initWithName:@"io.flutter" project:nil allowHeadlessExecution:YES];
>     self.engine = engine;
>     [self.engine runWithEntrypoint:nil];
> 
> // ViewController
> 
>     FlutterEngine *flutterEngine = [(AppDelegate *)[[UIApplication sharedApplication] delegate] engine];
> 
>     FlutterViewController* flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
> 
>     [flutterViewController setInitialRoute:@"myApp"];
> ```
> 
> ```dart
> // main.dart
> 
>     void main() => runApp(_widgetForRoute(window.defaultRouteName));
> 
>     Widget _widgetForRoute(String route) {
>       switch (route) {
>         case 'myApp':
>           return new MyApp();
>         case 'home':
>           return new HomePage();
>         default:
>           return Center(
>             child: Text('Unknown route: $route', textDirection: TextDirection.ltr),
>           );
>       }
>     }
> ```
> 
> I always get a Text and content is ''Unknown route: /'
我遇到同样的问题 请问你解决了吗

**Comment by kidzss** [comment] 2019-05-13 09:33
> > > I solved the problem.
> > > //=======================
> > > @interface XXFlutterViewController : FlutterViewController
> > > @EnD
> > > (void)viewDidLoad {
> > > [super viewDidLoad];
> > > // Do any additional setup after loading the view.
> > > FlutterEngine *flutterEngine = self.engine;
> > > [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
> > > //custom futter plugin
> > > [XXXFlutterBridge registerWithRegistry:flutterEngine];
> > > }
> > > //open flutter vc
> > > XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> > > [flutterViewController setInitialRoute:@"xxxxx/xxxx"];
> > 
> > 
> > Didn't U find the flutterVC dont release in this way?
> 
> I meet the problem... almost nothing released...
我使用flutter 1.2.1 在dealloc断点是有的

**Comment by lihui2333** [comment] 2019-05-13 09:42
> > > > I solved the problem.
> > > > //=======================
> > > > @interface XXFlutterViewController : FlutterViewController
> > > > @EnD
> > > > (void)viewDidLoad {
> > > > [super viewDidLoad];
> > > > // Do any additional setup after loading the view.
> > > > FlutterEngine *flutterEngine = self.engine;
> > > > [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
> > > > //custom futter plugin
> > > > [XXXFlutterBridge registerWithRegistry:flutterEngine];
> > > > }
> > > > //open flutter vc
> > > > XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> > > > [flutterViewController setInitialRoute:@"xxxxx/xxxx"];
> > > 
> > > 
> > > Didn't U find the flutterVC dont release in this way?
> > 
> > 
> > I meet the problem... almost nothing released...
> > 我使用flutter 1.2.1 在dealloc断点是有的

i use the same solution and it fixed.But official should also give a solution.

**Comment by Lolingew** [comment] 2019-05-14 02:25
> > > > I solved the problem.
> > > > //=======================
> > > > @interface XXFlutterViewController : FlutterViewController
> > > > @EnD
> > > > (void)viewDidLoad {
> > > > [super viewDidLoad];
> > > > // Do any additional setup after loading the view.
> > > > FlutterEngine *flutterEngine = self.engine;
> > > > [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
> > > > //custom futter plugin
> > > > [XXXFlutterBridge registerWithRegistry:flutterEngine];
> > > > }
> > > > //open flutter vc
> > > > XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> > > > [flutterViewController setInitialRoute:@"xxxxx/xxxx"];
> > > 
> > > 
> > > Didn't U find the flutterVC dont release in this way?
> > 
> > 
> > I meet the problem... almost nothing released...
> > 我使用flutter 1.2.1 在dealloc断点是有的

I update 1.2.1 last week. Do you mean, at 1.2.1 version, this solution will release memory normally? I used this before and found memory increased linearly. I'll try 1.2.1 and test it.

**Comment by zhangyihui-whalevii** [comment] 2019-05-15 03:20
WVFlutterViewController *controller = [[WVFlutterViewController alloc] init];
[GeneratedPluginRegistrant registerWithRegistry:controller]; 
[controller setInitialRoute:route];


使用这种方式可以成功传递route，并且不会影响插件的注册

**Comment by ly05010419** [comment] 2019-06-27 15:12
the same Problem!

**Comment by hucong730** [comment] 2019-07-17 11:15
> WVFlutterViewController *controller = [[WVFlutterViewController alloc] init];
> [GeneratedPluginRegistrant registerWithRegistry:controller];
> [controller setInitialRoute:route];
> 
> 使用这种方式可以成功传递route，并且不会影响插件的注册

这个方式有效果，感谢。

**Comment by zzjjob** [comment] 2019-09-11 09:53
1. create FlutterEngine
2. [_engine.get() createShell:nil libraryURI:nil];
    [_engine.navigationChannel invokeMethod:@"setInitialRoute" arguments:route];
3. self.flutterVc = [[FlutterViewController alloc] initWithEngine:engine nibName:nil bundle:nil];
    [engine launchEngine:nil libraryURI:nil];
    [engine setViewController:self.flutterVc];

**Comment by binjiayou66** [comment] 2019-09-23 09:55
> > > > > I solved the problem.
> > > > > //=======================
> > > > > @interface XXFlutterViewController : FlutterViewController
> > > > > @EnD
> > > > > (void)viewDidLoad {
> > > > > [super viewDidLoad];
> > > > > // Do any additional setup after loading the view.
> > > > > FlutterEngine *flutterEngine = self.engine;
> > > > > [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
> > > > > //custom futter plugin
> > > > > [XXXFlutterBridge registerWithRegistry:flutterEngine];
> > > > > }
> > > > > //open flutter vc
> > > > > XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> > > > > [flutterViewController setInitialRoute:@"xxxxx/xxxx"];
> > > > 
> > > > 
> > > > Didn't U find the flutterVC dont release in this way?
> > > 
> > > 
> > > I meet the problem... almost nothing released...
> > > 我使用flutter 1.2.1 在dealloc断点是有的
> 
> i use the same solution and it fixed.But official should also give a solution.

Creating a new FlutterViewController in the new or alloc init way does deliver routeName, but this way creates multiple flutter.io/gpu/ui threads over and over again.

**Comment by Aronlong1001** [comment] 2019-09-25 10:10
> I am still experiencing this issue on iOS platform, with the Flutter version shown below :
> 
> // --------- flutter doctor summary --------- //
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v1.3.10, on Mac OS X 10.14 18A391, locale en-HK)
> [!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
> [!] iOS toolchain - develop for iOS devices (Xcode 10.1)
> ✗ Verify that all connected devices have been paired with this computer in Xcode.
> If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
> To update with Brew, run:
> brew update
> brew uninstall --ignore-dependencies libimobiledevice
> brew uninstall --ignore-dependencies usbmuxd
> brew install --HEAD usbmuxd
> brew unlink usbmuxd
> brew link usbmuxd
> brew install --HEAD libimobiledevice
> brew install ideviceinstaller
> [✓] Android Studio (version 3.3)
> [✓] Connected device (3 available)
> 
> // --------- flutter doctor summary --------- //
> 
> I am following the official guide on [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url).
> 
> SetInitialRoute() is working when using FlutterViewController(project: nil, nibName: nil, bundle: nil), however, this seems make the Flutter plugins not found with the FlutterViewController, when I try to access methods in Flutter plugins, it throws MissingPluginException. It seems that because of those Plugins are register with FlutterEngine, the FlutterViewController will not find them if not connected with the FlutterEngine.
> 
> Using FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil), makes the plugins work, but SetInitialRoute() is not working.
> 
> Is there any way or alternative to solve this issue, making both setInitialRoute and plugins work in the same FlutterViewController? Thanks!

i have the same question, have you solved it, please?

**Comment by lyc2345** [comment] 2019-10-16 08:05
> > I am still experiencing this issue on iOS platform, with the Flutter version shown below :
> > // --------- flutter doctor summary --------- //
> > Doctor summary (to see all details, run flutter doctor -v):
> > [✓] Flutter (Channel dev, v1.3.10, on Mac OS X 10.14 18A391, locale en-HK)
> > [!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> > ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
> > [!] iOS toolchain - develop for iOS devices (Xcode 10.1)
> > ✗ Verify that all connected devices have been paired with this computer in Xcode.
> > If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
> > To update with Brew, run:
> > brew update
> > brew uninstall --ignore-dependencies libimobiledevice
> > brew uninstall --ignore-dependencies usbmuxd
> > brew install --HEAD usbmuxd
> > brew unlink usbmuxd
> > brew link usbmuxd
> > brew install --HEAD libimobiledevice
> > brew install ideviceinstaller
> > [✓] Android Studio (version 3.3)
> > [✓] Connected device (3 available)
> > // --------- flutter doctor summary --------- //
> > I am following the official guide on [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url).
> > SetInitialRoute() is working when using FlutterViewController(project: nil, nibName: nil, bundle: nil), however, this seems make the Flutter plugins not found with the FlutterViewController, when I try to access methods in Flutter plugins, it throws MissingPluginException. It seems that because of those Plugins are register with FlutterEngine, the FlutterViewController will not find them if not connected with the FlutterEngine.
> > Using FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil), makes the plugins work, but SetInitialRoute() is not working.
> > Is there any way or alternative to solve this issue, making both setInitialRoute and plugins work in the same FlutterViewController? Thanks!
> 
> i have the same question, have you solved it, please?

**When you create a FlutterViewController don't use FlutterEngine**

``` swift
let flutterViewController = FlutterViewController(nibName: nil, bundle: nil)
flutterVC.setInitialRoute("RouteName")
```
Use this way is working!

**Comment by xx-li** [comment] 2019-10-31 10:24
I use `[FlutterViewController new]` replace `[[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil]`， `setInitialRoute ` is working， but when native push this FlutterViewController firsh show `splashScreen`。 Anyone encounter the same problem，how to avoid show splashScreen？

my env is :
```
Xcode11.2 / iOS13 
Flutter 1.10.14 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 1946fc4da0 (3 weeks ago) • 2019-10-07 15:23:31 -0700
Engine • revision 1d62160fdb
Tools • Dart 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)
```

**Comment by ungacy** [comment] 2019-11-01 05:47
> I use `[FlutterViewController new]` replace `[[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil]`， `setInitialRoute ` is working， but when native push this FlutterViewController firsh show `splashScreen`。 Anyone encounter the same problem，how to avoid show splashScreen？
> 
> my env is :
> 
> ```
> Xcode11.2 / iOS13 
> Flutter 1.10.14 • channel dev • https://github.com/flutter/flutter.git
> Framework • revision 1946fc4da0 (3 weeks ago) • 2019-10-07 15:23:31 -0700
> Engine • revision 1d62160fdb
> Tools • Dart 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)
> ```

try to set a view to property`splashScreenView` to the instance of `FlutterViewController`

**Comment by xx-li** [comment] 2019-11-01 06:06
> > I use `[FlutterViewController new]` replace `[[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil]`， `setInitialRoute ` is working， but when native push this FlutterViewController firsh show `splashScreen`。 Anyone encounter the same problem，how to avoid show splashScreen？
> > my env is :
> > ```
> > Xcode11.2 / iOS13 
> > Flutter 1.10.14 • channel dev • https://github.com/flutter/flutter.git
> > Framework • revision 1946fc4da0 (3 weeks ago) • 2019-10-07 15:23:31 -0700
> > Engine • revision 1d62160fdb
> > Tools • Dart 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)
> > ```
> 
> try to set a view to property`splashScreenView` to the instance of `FlutterViewController`

tks，I am so tried，push animation is not normal

**Comment by ungacy** [comment] 2019-11-01 06:15
```
    FlutterViewController *some = [FlutterViewController new];
    UIView *view = [[UIView alloc] initWithFrame:UIApplication.sharedApplication.keyWindow.bounds];
    view.backgroundColor = [UIColor whiteColor];
    some.splashScreenView = view;
```

**Comment by xx-li** [comment] 2019-11-01 06:20
> ```
>     FlutterViewController *some = [FlutterViewController new];
>     UIView *view = [[UIView alloc] initWithFrame:UIApplication.sharedApplication.keyWindow.bounds];
>     view.backgroundColor = [UIColor whiteColor];
>     some.splashScreenView = view;
> ```

tks, I am also try so, push animation firsh show white splashScreenView， I need to avoid show splashScreen.

**Comment by zyg1982527** [comment] 2019-11-01 08:55
我搞定了，经过测试既能够传入routeName,又可以flutter和原生交互正常。少一行代码都不行。如下
let flutterViewController = FlutterProjectListViewController.init(project: nil  , nibName: nil, bundle: nil)!;
        flutterViewController.splashScreenView =  FlutterSplashViewController().view
        GeneratedPluginRegistrant.register(with: flutterViewController)
        flutterViewController.setModel(model: FLUTTER_PROJECT_LIST);
        flutterViewController.view.frame = UIScreen.main.bounds;
        self.navigationController?.pushViewController(flutterViewController, animated: true)
                 
        self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
        self.flutterEngine?.run(withEntrypoint: nil)
        GeneratedPluginRegistrant.register(with: self.flutterEngine)

**Comment by zyg1982527** [comment] 2019-11-01 09:12
我搞定了，可以传入routeName，又能保证交互好用。it work well

let flutterViewController = FlutterViewController.init(project: nil  , nibName: nil, bundle: nil)!;
       flutterViewController.splashScreenView =  FlutterSplashViewController().view
       GeneratedPluginRegistrant.register(with: flutterViewController)
       flutterViewController.setInitialRoute("test1");
       flutterViewController.view.frame = UIScreen.main.bounds;
       self.navigationController?.pushViewController(flutterViewController, animated: true)
       self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
       self.flutterEngine?.run(withEntrypoint: nil)
       GeneratedPluginRegistrant.register(with: self.flutterEngine)

**Comment by xx-li** [comment] 2019-11-04 03:28
Use [FlutterViewController new] replace [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil]  cause other problems。 I have two problems  encountered now.
1.  Can't avoid show splashScreenView
2. Case [package_info](https://pub.dev/packages/package_info) not normal work。 （Suspected that the native and Flutter could not communicate properly）

**Comment by zyg1982527** [comment] 2019-11-04 03:36
yes ,splashScreenView cannot be  ignored.  Use my code flutter plugin can work normal. Do you try other plugin?for example flutter share_preference




| |
自己
|
|
邮箱：zyg1982527@126.com
|

签名由 网易邮箱大师 定制

On 11/04/2019 11:31, Stellar wrote:

Use [FlutterViewController new] replace [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil] cause other problems。 I have two problems encountered now.

Can't avoid show splashScreenView
Case package_info not normal work。 （Suspected that the native and Flutter could not communicate properly）

**Comment by xx-li** [comment] 2019-11-04 03:43
@zyg1982527  Should be caused by plugin registration issues，  use `[GeneratedPluginRegistrant registerWithRegistry:flutterViewController];` after `FlutterViewController` init can resolve  it。 A little worried about whether other problems will be introduced later。

**Comment by freedom-shen** [comment] 2019-11-14 06:13
仔细研究了下Flutter/Engine里面的源码，`setInitialRoute`要在`launchEngine:libraryURI:`之前，
使用了`initWithEngine`方法，要求自定义的FlutterEngine初始化完毕，并且运行`runWithEntrypoint:libraryURI:`（内部还是会调用launchEngine:libraryURI:）。
所以使用`initWithEngine`初始化，`setInitialRoute`是无效的。
所以只能使用`initWithProject`（init,new都会调用该方法），但是带来了新问题会加载Launch图。

贴一个简单的思路，新建一个FlutterViewController的子类CSFlutterController，去除和launch有关的部分。

```
@interface CSFlutterViewController () <FlutterBinaryMessenger, FlutterStreamHandler> {
    BOOL _enigneNeedsLaunch;
}
@end

@implementation CSFlutterViewController

#pragma mark - Rewrite

- (BOOL)loadDefaultSplashScreenView {
    return NO;
}

- (void)installSplashScreenViewIfNecessary {
}

- (void)removeSplashScreenView:(dispatch_block_t _Nullable)onComplete {
    onComplete();
}

#pragma mark - Init Rewrite

- (instancetype)initWithProject:(FlutterDartProject *)project nibName:(NSString *)nibName bundle:(NSBundle *)nibBundle {
    self = [super initWithProject:project nibName:nibName bundle:nibBundle];
    if (self) {
        _enigneNeedsLaunch = NO;
        [self setInitialRoute:@"/userCenter"];
        [self.engine performSelector:@selector(launchEngine:libraryURI:) withObject:nil withObject:nil];
        [self.engine runWithEntrypoint:nil libraryURI:nil];
        [self.engine setViewController:self];
    }
    return self;
}

@end

```

**Comment by amazingrace** [comment] 2019-11-19 11:28
> WVFlutterViewController *controller = [[WVFlutterViewController alloc] init];
> [GeneratedPluginRegistrant registerWithRegistry:controller];
> [controller setInitialRoute:route];
> 
> 使用这种方式可以成功传递route，并且不会影响插件的注册

Yes, it woks for me. You saved my 2 days time, thanks a lot.

亲们，这个法子真的可以啊，[GeneratedPluginRegistrant registerWithRegistry:controller]; 而不是[GeneratedPluginRegistrant registerWithRegistry:self.engine]; 
官网害死人啦。
---------来自被这个问题搞疯了两天的程序媛。。

**Comment by zyg1982527** [comment] 2019-11-19 11:32
哈哈，能帮到大家我很开心




| |
自己
|
|
邮箱：zyg1982527@126.com
|

签名由 网易邮箱大师 定制

On 11/19/2019 19:30, amazingrace wrote:

WVFlutterViewController *controller = [[WVFlutterViewController alloc] init];
[GeneratedPluginRegistrant registerWithRegistry:controller];
[controller setInitialRoute:route];

使用这种方式可以成功传递route，并且不会影响插件的注册

Yes, it woks for me. You saved my 2 days time, thanks a lot.

亲们，这个法子真的可以啊，[GeneratedPluginRegistrant registerWithRegistry:controller]; 而不是[GeneratedPluginRegistrant registerWithRegistry:self.engine];
官网害死人啦。
---------来自被这个问题搞疯了两天的程序媛。。

**Comment by xster** [comment] 2019-12-11 23:57
This is somewhat the same as https://github.com/flutter/flutter/issues/31185 and now covered under https://github.com/flutter/flutter/issues/31185. Also adding some clarifications in https://github.com/flutter/engine/pull/14367. 

To be fair, this API is indeed unclear and confusing. I think we want to gradually discourage its use but don't have a great alternative yet. 

In general, we should make all custom interop easier https://github.com/flutter/flutter/issues/32930 so you can pass any initialization data you'd like at startup, not only route. 

Also, if we were to make built-in concepts like route easier, we should do it on top of the upcoming navigator APIs rather than adding more to the current imperative navigator APIs. https://github.com/flutter/flutter/issues/45938

**Closed** 2019-12-12 00:43 UTC
Labels: a: existing-apps, engine, f: routes

**Comment by WinJayQ** [comment] 2020-01-07 11:06
> I use Swift, and i found problem is `self.flutterEngine?.run(withEntrypoint: nil)` in document [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url). If you do like that, `FlutterEngine` will run before you create `FlutterViewController` so you cannot `setInitialRoute`.
> To solve, you must remove that line in `AppDelegate`, init `FlutterViewController` without `FlutterEngine` `let flutterViewController = FlutterViewController(nibName: nil, bundle: nil)`, and `setInitialRoute`, final call `flutterEngine?.run(withEntrypoint: nil)`.

Yes, it woks for me.

**Comment by jitesh-sharma** [comment] 2020-01-14 07:33
> > I use Swift, and i found problem is `self.flutterEngine?.run(withEntrypoint: nil)` in document [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url). If you do like that, `FlutterEngine` will run before you create `FlutterViewController` so you cannot `setInitialRoute`.
> > To solve, you must remove that line in `AppDelegate`, init `FlutterViewController` without `FlutterEngine` `let flutterViewController = FlutterViewController(nibName: nil, bundle: nil)`, and `setInitialRoute`, final call `flutterEngine?.run(withEntrypoint: nil)`.
> 
> Yes, it woks for me.

its working, but showing splash screen before pushing to flutterViewController and when we are trying to pop from flutterViewController its pop to black screen instead of our native iOS ViewController.
