### ISSUE TITLE
Is there any way to make the native part of one plugin depend on the native part of another plugin?

### ISSUE THREAD

**Issue by talisk** [flutter/flutter#48554] opened 2020-01-10 04:07 UTC
## Use case

As we all know, we can make a plugin depend on another plugin by pub. How to make the native part of one plugin depend on the native part of another plugin?

For example, there're two plugin called A and B, the native part of A called AN,  the native part of B called BN. B depend on A, so we declare the dependency in the pubspec.yaml of B. I want to call some functions of AN in BN, but I can't do it.

**Comment by dnfield** [comment] 2020-01-10 04:19
It's platform dependent. For example, on Android, you'd add dependencies in your build.gradle.  On iOS, you'd add dependencies to your podspec, etc.

This is a question that would be better suited for stackoverflow, as it is not a bug in the framework or a feature request.  I'm going to close this - please let me know if there's something I'm missing here though.  /cc @blasten and @jmagman who might have more thoughts.

**Comment by blasten** [comment] 2020-01-10 04:46
Yep. This is already possible on Android. I remember @jmagman was going to look into it as well. The tool already generates .flutter-plugins-dependencies which is relevant for iOS as well.

**Comment by mklim** [comment] 2020-01-10 17:44
@blasten, looks like the re-opening was probably unintentional so I'm closing this again. Feel free to re-open if that was intentional and you think this should stay open.

**Closed by mklim** 2020-01-10 17:44 UTC
Labels: d: stackoverflow, plugin

**Comment by blasten** [comment] 2020-01-10 17:46
@blasten we probably need an issue for the iOS part then?
