### ISSUE TITLE
The lack of the component "tree" prevents me from quickly implementing this feature

### ISSUE THREAD

**Issue by mingyouzhu** [flutter/flutter#78850] opened 2021-03-23 09:22 UTC
Needs like this on the web:
<img width="879" alt="Screen Shot 2021-03-23 at 5 15 05 PM" src="https://user-images.githubusercontent.com/37821420/112123498-47f21900-8bfc-11eb-8828-fede111d2793.png">

**Comment by pedromassangocode** [comment] 2021-03-23 09:35
Duplicate of https://github.com/flutter/flutter/issues/42332.

**Closed by pedromassangocode** 2021-03-23 09:35 UTC
Labels: in triage
