### ISSUE TITLE
Breakpoints are not working on web for external packages

### ISSUE THREAD

**Issue by jkydevelopment** [flutter/flutter#106727] opened 2022-06-28 08:20 UTC
## Steps to Reproduce

I wrote an application which runs successfully on Android and iOS (in fact they are on production since some time ago).
The app is organized by packages (following clean architecture pattern), so I enabled the `debugExternalPackageLibraries` flag in my `settings.json` file to be able to debug all my code. 
When I started configuring the environment to deploy web version I realized that the breakpoints which are outside the main package are not working (meanwhile **they are working on Android and iOS platforms**). 

I mean, I am able to add a breakpoint at any file inside the main `lib/` path, but if I try to add it on a package outside of this package, the Visual Studio marks it as a `Unverified Breakpoint`. 

my_project
|
|__ lib
|      |__any_file.dart (can add breakpoint)  ✅ 
|
|__account_domain (any other package)
     |_ any_file.dart (can't add breakpoint)  ❌ 

I tried different combinations of the `settings.json` file using these flags:
```
    "debug.allowBreakpointsEverywhere": true,
    "dart.debugSdkLibraries": true,
    "dart.debugExternalPackageLibraries": true,
```

I also tried to debug the project using `Dev Tools` in web browser, but in this case the tool doesn't allow to add breakpoints in external packages (the small white dot which shows that the line code admits a breakpoint does not appear at any line of any file outside the `lib/` folder). 

Also tried to downgrade Chrome version following [this issue](https://github.com/flutter/flutter/issues/101403) but still not working. 

This is my `launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Project Dev",
            "request": "launch",
            "program": "lib/main_dev.dart",
            "type": "dart",
            "flutterMode": "debug",
            "args": [
                "--flavor",
                "dev",
                "-t",
                "lib/main_dev.dart" 
            ]
        },
        {
            "name": "Project Prod",
            "request": "launch",
            "program": "lib/main_prod.dart",
            "type": "dart",
            "args": [
                "--flavor",
                "prod",
                "-t",
                "lib/main_prod.dart" 
            ]
        },
        {
            "name": "Project (profile mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile"
        }
    ]
}
```

<details>
<summary>Code sample</summary>

Flutter analyze:

```
0 issues found. (ran in 10.6s)
```

Flutter doctor:

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.1 21C52 darwin-arm (Rosetta), locale es-ES)
    • Flutter version 3.0.3 at /Users/jugarcs/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (hace 6 días), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jugarcs/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-06-28 08:45
Hi @jkydevelopment. Thanks for filing this issue. Could you please provide a [minimal, reproducible example][1] so that we can verify and investigate it?

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by exaby73** [comment] 2022-06-29 12:44
Are you able to reproduce it using local packages? Maybe you could create a repo reproducing it that way

**Comment by jkydevelopment** [comment] 2022-06-29 15:27
Yes, I'm able to reproduce it locally. I tried to copy the project and remove a lot of code just to reproduce the same situation but I'm not able to "break" the debugging as it's happening in my project. Could we make some live session or something like that to show it to you?

**Comment by exaby73** [comment] 2022-06-30 06:07
Maybe you could put in into a repository and share it here so that others on the team could also look at it

**Comment by jkydevelopment** [comment] 2022-06-30 06:45
No I can't, my company doesn't allow to me to share it. Don't worry, I hope I can find the problem. If I do it, I will let you know about it.

**Comment by exaby73** [comment] 2022-06-30 07:08
I am not asking you to share proprietary code, but rather create a new project with sample code in a new repo. Let me know of you can do that instead :)

**Comment by jkydevelopment** [comment] 2022-06-30 07:55
The problem is that I am not able to reproduce this issue in a new project, even I have tried to copy the same structure and removing a lot of unnecessary files. It's a bit annoying...

**Comment by exaby73** [comment] 2022-06-30 08:18
Unfortunately, if the issue is not reproducible, we cannot take action on it. If you are able to produce a sample that may reproduce this issue, please post it here. Until then, I am closing this issue. Thank you for filing it :)

**Comment by jkydevelopment** [comment] 2022-07-13 12:18
Hi @exaby73 I found again the problem and I created a repository with the bug and the instructions to reproduce it. 
[REPO](https://github.com/jkydevelopment/flutter_web_bug)
I you have any question about it please ask for them. 
Thanks in advance!

**Comment by exaby73** [comment] 2022-07-14 06:48
Hey @jkydevelopment. I am able to reproduce this on stable but due to a package you included not supporting the master channel, I am unable to test this on master as well. Can you modify the sample to work on master as well?

#### Logs

```
Launching lib/main_dev.dart on Chrome in debug mode...
lib/main_dev.dart:1
: Error: The non-abstract class 'FwfhTextStyle' is missing implementations for these members:
../…/lib/fwfh_text_style.dart:11
 - TextStyle.fontVariations
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
 ```

**Comment by jkydevelopment** [comment] 2022-07-14 14:48
Hi @exaby73, thanks for your answer.

Currently I am on stable channel. How did you get that log? I have tried it capturing a whole session and I am not able to find anything related to that `FwfhTextStyle` class you mentioned. 

About the channel, do you refer any lib I'm using is not supporting the master channel? How could I find it?

**Comment by exaby73** [comment] 2022-07-15 06:25
Thank you @jkydevelopment. I can reproduce this issue on stable and master. Though by the looks of it, it looks like a Dart issue rather than a Flutter issue. There is a similar issue on the [dart-lang/sdk](https://github.com/dart-lang/sdk) repo (https://github.com/dart-lang/sdk/issues/43197).

@DanTup is this issue the result of https://github.com/dart-lang/sdk/issues/43197?

**Comment by DanTup** [comment] 2022-07-15 10:18
I can reproduce this too. I don't think it's related to https://github.com/dart-lang/sdk/issues/43197 as that seems testing (and not-web) specific.

I captured a log while reproducing, and found that the web proxy is rejecting the breakpoint like this:

```
==> [VM
] {
	"jsonrpc": "2.0",
	"id": "1694",
	"method": "addBreakpointWithScriptUri",
	"params": {
		"isolateId": "1",
		"scriptUri": "file:///Users/danny/Dev/TestStuff/flutter_web_bug/account_presentation/lib/controllers/sign_in_controller.dart",
		"line": 21
	}
}
<== [VM
] {
	"jsonrpc": "2.0",
	"error": {
		"code": 102,
		"message": "The VM is unable to add a breakpoint at the specified line or function",
		"data": {
			"request": {
				"jsonrpc": "2.0",
				"id": "1694",
				"method": "addBreakpointWithScriptUri",
				"params": {
					"isolateId": "1",
					"scriptUri": "file:///Users/danny/Dev/TestStuff/flutter_web_bug/account_presentation/lib/controllers/sign_in_controller.dart",
					"line": 21
				}
			}
		}
	},
	"id": "1694"
}
```

I think this could be the same issue as https://github.com/dart-lang/webdev/issues/874. Interestingly, I note that you say this doesn't happen if you remove the import of `package:router/router.dart` and that import seems to introduce a cycle (`controllers/sign_in_controller.dart` -> `package:router/router.dart` -> `package:account_presentation/account_presentation_library.dart` -> `controllers/sign_in_controller.dart`) although I'm not sure if that's what's triggering it.

@annagrin @elliette do you think this is the same as https://github.com/dart-lang/webdev/issues/874, or should this be moved to a new dwds issue?

**Comment by elliette** [comment] 2022-07-18 17:44
I think this is a separate issue. I've opened a new bug in DWDS for this (https://github.com/dart-lang/webdev/issues/1692). Closing this in favor of the new DWDS issue. Thank you!

**Closed by elliette** 2022-07-18 17:44 UTC
Labels: in triage
