### ISSUE TITLE
Debugging often crashes

### ISSUE THREAD

**Issue by qq3144225600** [flutter/flutter#42900] opened 2019-10-17 06:17 UTC
Console crash log：
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```
Build fingerprint: 'xiaomi/cactus/cactus:9/PPR1.180610.011/V10.4.4.0.PCBCNXM:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 23101, tid: 23126, name: com.app.yongjiu  >>> com.app.yongjiu <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    r0  89ebeea8  r1  89ebeefc  r2  5aa45dca  r3  00000008
    r4  ca2a7ee2  r5  da7a445a  r6  d34fb356  r7  ca2b8202
    r8  d34facd6  r9  d34fadfa  r10 ca2b966e  r11 d34fadc6
    ip  00000000  sp  d34fb12a  lr  906d2adb  pc  a8aeaa40
backtrace:
    #00 pc 00019a40  /system/lib/libc.so (sigsetjmp+112)
    #01 pc 00f0cad7  /data/app/com.app.yongjiu-c83lHRelAp7IJWbjpMZzZA==/lib/arm/libflutter.so (offset 0xafe000)
Lost connection to device.
```
flutter doctor
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G7024,
    locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
Kris:~ kris$ 
```

**Comment by BondarenkoStas** [comment] 2019-10-17 10:36
@qq3144225600 can you provide a full log you receive?
Also please add the info about your device, I only can see that it's xiaomi, but no model and no android version.

**Comment by qq3144225600** [comment] 2019-10-17 10:44
Phone model Redmi6A android version Android9

**Comment by mraleph** [comment] 2020-03-23 20:23
Duplicate of #27077

**Closed by mraleph** 2020-03-23 20:23 UTC
Labels: severe: crash, tool, ▣ platform-android
