### ISSUE TITLE
Web flutter can not work RTL 

### ISSUE THREAD

**Issue by amanc1361** [flutter/flutter#71143] opened 2020-11-24 08:34 UTC
Writing right-to-left text in the WEB FLUTTER platform does not work properly
In TEXT and TEXTFORMFIELD widgets

**Comment by pedromassangocode** [comment] 2020-11-24 08:57
Hi @amanc1101 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by amanc1101** [comment] 2020-11-24 09:01
PS D:\accountting\accounting> flutter doctor -v
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale fa-IR)
    • Flutter version 1.24.0-10.2.pre at c:\src\flutter
    • Framework revision 022b333a08 (6 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at H:\Android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = H:\Android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (4 available)
    • SM A520F (mobile) • 520001bef0909403 • android-arm64  • Android 8.0.0 (API 26)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.47

**Comment by amanc1101** [comment] 2020-11-24 09:03
Directionality(
                 textDirection: TextDirection.rtl,
                                child: TextFormField(
                  cursorColor: primarylightcolor,
                  cursorWidth: 1,
                  onChanged: (value) => {callback(value)},
                  decoration: InputDecoration(
                    border: InputBorder.none,
                    focusedBorder: InputBorder.none,
                    enabledBorder: InputBorder.none,
                    hintText: "جستجو",
                  ),
              ),
               ),

**Comment by pedromassangocode** [comment] 2020-11-24 11:10
Hi @amanc1101 
Please provide a complete minimal code sample that I can just copy/paste and run it.
Thanks

**Comment by iapicca** [comment] 2020-11-24 14:53
possible duplicate of 
https://github.com/flutter/flutter/issues/47745
https://github.com/flutter/flutter/issues/69396
also related to https://github.com/flutter/flutter/issues/70049

**Comment by xclud** [comment] 2020-11-25 16:43
I made a PR for hint text-direction on the form-fields. I hope it will be merged.

https://github.com/flutter/flutter/pull/69534

**Comment by amanc1101** [comment] 2020-11-26 07:19
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Directionality(
          textDirection: TextDirection.rtl,
          child: MyHomePage(title: 'RTL NOT WORK IN WEB FLUTTER')),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: <Widget>[
            TextFormField(
              textDirection: TextDirection.rtl,
              decoration: InputDecoration(
                border: OutlineInputBorder(),
                labelText: 'جستجو',
                hintText: 'عبارت مورد جستجو.....',
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by amanc1101** [comment] 2020-11-26 07:25
> I made a PR for hint text-direction on the form-fields. I hope it will be merged.
> 
> #69534

Thank you
I hope it gives good results

**Comment by pedromassangocode** [comment] 2020-11-26 08:16
Hi @amanc1101 
Can you describe what do you mean by "not working"?

I think this may be a duplicate of one of the issues mentioned in https://github.com/flutter/flutter/issues/71143#issuecomment-733025013.

**Comment by pedromassangocode** [comment] 2020-12-18 10:47
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-18 10:47 UTC
Labels: in triage, waiting for customer response
