### ISSUE TITLE
[iOS] Carsh on GPUSurfaceMetalImpeller::AcquireFrameFromCAMetalLayer

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#153845] opened 2024-08-21 14:36 UTC
Duplicate of https://github.com/flutter/flutter/issues/149646

_Originally posted by @darshankawar in https://github.com/flutter/flutter/issues/149893#issuecomment-2154732678_

**Comment by cj3479** [comment] 2024-08-21 14:39
Why  https://github.com/flutter/flutter/issues/149646 AND  https://github.com/flutter/flutter/issues/149893 is duplicate？
Their crash stack is different

**Comment by danagbemava-nc** [comment] 2024-08-22 08:04
They were supposedly fixed by the same commit, which is why one was closed as a duplicate of the other. If you are running into this issue on the latest version of flutter stable (3.24.1), kindly file a new issue and provide detailed information. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-08-22 08:04 UTC
Labels: in triage
