### ISSUE TITLE
[Impeller] Glitch when Lottie stacked on top of custom paint with blur

### ISSUE THREAD

**Issue by junaid1460** [flutter/flutter#133249] opened 2023-08-24 11:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. clone https://github.com/junaid1460/flutter_impeller_reported_bugs
2. switch to lottie tab
3. the animation with run it would gritch with custom pain't blur background within stack
4. Run it with flutter en --no-enable-impeller flag to verify actual result

### Expected results

https://github.com/xvrh/lottie-flutter/assets/3303745/28be468b-56f2-4c94-8d51-547593d64328

### Actual results

https://github.com/xvrh/lottie-flutter/assets/3303745/77803c8b-5b12-4eeb-82a0-c3df28cdcc34

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

import 'assets.dart';

class LottieIssue1WithBackground extends StatelessWidget {
  const LottieIssue1WithBackground({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      clipBehavior: Clip.none,
      children: [
        Positioned(
          left: -60,
          top: -10,
          child: CustomPaint(
            painter:
                OvalBlurPainter(blurSigma: 100, color: const Color(0xFF347B6F)),
            child: const SizedBox(
              width: 462,
              height: 463,
            ),
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(
              horizontal: MediaQuery.of(context).size.width / 4),
          child: AspectRatio(aspectRatio: 720 / 626, child: Container()),
        ),
        Positioned.fill(
          top: -100,
          child: LottieBuilder.asset(
            Assets.milestoneLandingLottie,
            repeat: false,
          ),
        ),
      ],
    );
  }
}

class OvalBlurPainter extends CustomPainter {
  final double blurSigma;
  final Color color;
  OvalBlurPainter({
    required this.blurSigma,
    required this.color,
  });

  @override
  void paint(Canvas canvas, Size size) {
    Paint line = Paint()
      ..color = color
      ..strokeCap = StrokeCap.round
      ..style = PaintingStyle.fill
      ..maskFilter = MaskFilter.blur(BlurStyle.normal, blurSigma);
    canvas.drawOval(Rect.fromLTWH(0, 0, size.width, size.height), line);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
flutter run
flutter run --no-enable-impeller
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
➜  ___ git:(master) flutter doctor -v
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale en-IN)
    • Flutter version 3.13.0 on channel stable at ~/.asdf/installs/flutter/3.13.0-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (6 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mj/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: ~/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at ~/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] VS Code (version 1.80.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 3F33BF82-DF19-4D65-BA2F-A28AC6CFD455 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4
      (simulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by junaid1460** [comment] 2023-08-24 11:40
xref: https://github.com/xvrh/lottie-flutter/issues/294

https://github.com/flutter/flutter/issues/132972#issuecomment-1687674726

**Comment by dam-ease** [comment] 2023-08-24 13:24
Hi @junaid1460. Thanks for filing this! I can reproduce this on the latest flutter versions with impeller. Without impeller, it works fine! I also tested on a previous version `3.10.6` and I can see it works fine both with and without impeller.

| With Impeller | Without Impeller |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/53122008/80f4ed9a-4751-4d7b-b091-0c9881b2c736"> | <video src="https://github.com/flutter/flutter/assets/53122008/ff541428-345f-4ba1-9de2-21f2e0031d20"> | 

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

void main() {
  runApp(MaterialApp(
    title: 'Flutter Demo',
    theme: ThemeData(
      colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      useMaterial3: true,
    ),
    home: const Material(child: SafeArea(child: MyApp())),
  ));
}

enum Issue { gradientTransform, maskBlur, lottie1 }

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return const Column(children: [
      Expanded(
        child: AnimatedSwitcher(
          duration: Duration(milliseconds: 300),
          child: LottieIssue1WithBackground(
            key: ValueKey(#lottie_issue_1_with_background),
          ),
        ),
      ),
    ]);
  }
}

class LottieIssue1WithBackground extends StatelessWidget {
  const LottieIssue1WithBackground({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      clipBehavior: Clip.none,
      children: [
        Positioned(
          left: -60,
          top: -10,
          child: CustomPaint(
            painter:
                OvalBlurPainter(blurSigma: 100, color: const Color(0xFF347B6F)),
            child: const SizedBox(
              width: 462,
              height: 463,
            ),
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(
              horizontal: MediaQuery.of(context).size.width / 4),
          child: AspectRatio(aspectRatio: 720 / 626, child: Container()),
        ),
        Positioned.fill(
          top: -100,
          child: LottieBuilder.asset(
            "assets/milestone_landing.lottie.json",
            repeat: false,
          ),
        ),
      ],
    );
  }
}

class OvalBlurPainter extends CustomPainter {
  final double blurSigma;
  final Color color;
  OvalBlurPainter({
    required this.blurSigma,
    required this.color,
  });

  @override
  void paint(Canvas canvas, Size size) {
    Paint line = Paint()
      ..color = color
      ..strokeCap = StrokeCap.round
      ..style = PaintingStyle.fill
      ..maskFilter = MaskFilter.blur(BlurStyle.normal, blurSigma);
    canvas.drawOval(Rect.fromLTWH(0, 0, size.width, size.height), line);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
``` 

</p>
</details> 

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.1 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (27 hours ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • iPhone 8 (mobile)  • 218697C0-911E-4F4E-9568-C387ACB184ED • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile) • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64
      • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.14.0-9.0.pre.70, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.14.0-9.0.pre.70 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bede50cba2 (7 hours ago), 2023-08-24 00:49:29 -0400
    • Engine revision 3b92bb6eda
    • Dart version 3.2.0 (build 3.2.0-97.0.dev)
    • DevTools version 2.26.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 8 (mobile)           • 218697C0-911E-4F4E-9568-C387ACB184ED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)          • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by chinmaygarde** [comment] 2023-08-28 17:34
cc @bdero. Could this be the [same as your coverage hint fix](https://github.com/flutter/engine/pull/45079)?

**Comment by bdero** [comment] 2023-08-28 17:48
Yeah this looks like the same issue as https://github.com/flutter/flutter/issues/132936

**Comment by chinmaygarde** [comment] 2023-08-28 19:36
Sounds good. The fix has landed and it seems to be in the process of being cherry-picked. Closing.

**Closed by chinmaygarde** 2023-08-28 19:36 UTC
Labels: c: regression, platform-ios, engine, a: animation, has reproducible steps, P1, e: impeller, team-engine, triaged-engine, found in release: 3.13, found in release: 3.14

**Comment by bdero** [comment] 2023-08-28 19:56
@junaid1460 Is this solved on the master channel for you?

**Comment by junaid1460** [comment] 2023-08-29 04:55
Let me verify, I will get back in sometime

**Comment by junaid1460** [comment] 2023-08-29 05:43
Glitch is solved, but there's difference in blur results and some color projection

xref
https://github.com/flutter/flutter/issues/127770#issuecomment-1696800383
