### ISSUE TITLE
Flutter build web command still only builds older version

### ISSUE THREAD

**Issue by psygo** [flutter/flutter#101511] opened 2022-04-07 13:51 UTC
`flutter build web` is building the last (and first) time I used it, ignoring the many changes I've made over the last few weeks.

This issue has already been described here:

- #55008
- #75762
- #78912

My Flutter version is the latest, 2.10.4. And you can reproduce this issue by pulling [this project](https://github.com/FanaroEngineering/dogemp), from [this commit (`72600d7`)](https://github.com/FanaroEngineering/dogemp/commit/72600d776f3178b976278a7337dcb7b9ede9fc07).

I was able to solve the problem, even though it was far from ideal. Basically, I used the recommendations in [this comment](https://github.com/flutter/flutter/issues/75762#issuecomment-777323687), creating a new Flutter repo and then copying everything I currently have on top of it.

**Comment by maheshmnj** [comment] 2022-04-08 09:08
Hi @psygo, Thanks for filing the issue. I was able to reproduce the issue on the latest stable channel. I tried running the app in debug and release mode and I could see different output.


### Debug vs Release
https://user-images.githubusercontent.com/31410839/162403020-3d4bc44a-0d97-44c0-a24f-368fcaf32a4b.mov


I looked at the [web folder](https://github.com/FanaroEngineering/dogemp/tree/master/web) and it looks like there are some files that shouldn't have been there e.g (main.dart.js), which are basically generated on building the web app. 
so I deleted the web directory and recreated it using `flutter create . --platforms web` and then I see the same output in debug and release.
 
https://user-images.githubusercontent.com/31410839/162403682-56ea4791-d82d-4fa0-8751-3b3f9c855a2f.mov


Provided that this works fine with a newly created web app, I believe this is not really and issue and we can close it. Incase you disagree feel free to write in the comments and we will reopen it.

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>  

Thank you.

**Closed by maheshmnj** 2022-04-08 09:08 UTC
Labels: in triage

**Comment by psygo** [comment] 2022-04-08 13:33
I disagree with the closing of this issue.

> Provided that this works fine with a newly created web app

The user is not going to use `flutter build web` only upon the project's creation.

> I looked at the [web folder](https://github.com/FanaroEngineering/dogemp/tree/master/web) and it looks like there are some files that shouldn't have been there e.g (main.dart.js), which are basically generated on building the web app.

How many people are going to be aware of that? I'm not a Flutter beginner and I didn't have the foresight to do it. And, if this repeats itself every time, why not automate it? Why not include these steps inside `flutter build web`?

**Comment by maheshmnj** [comment] 2022-04-11 05:59
> The user is not going to use flutter build web only upon the project's creation.

@psygo, Sorry if I was not clear what I meant was files in your `web` directory contains some unwanted build files and those are not added by flutter on running `flutter build web`. The flutter build command generated files are always under the `build/` folder.  

> How many people are going to be aware of that? I'm not a Flutter beginner and I didn't have the foresight to do it. And, if this repeats itself every time, why not automate it? Why not include these steps inside flutter build web?

 I do not mean that you have to run `flutter create . --platforms web` everytime on project creation. The issue with your sample project was that the build files seem to be mistakenly added to the web folder, Hence the issue.
So I don't see any reason for this issue to be repeated.
