### ISSUE TITLE
[Video Player] Getting error when playing AWS cloudfront URL in Flutter web

### ISSUE THREAD

**Issue by rahulvyas** [flutter/flutter#107372] opened 2022-07-10 11:53 UTC
## Steps to Reproduce

Try to run AWS Cloudfront URL in the video player in web and Android Simulator.

1. Add video Player plugin and chewie plugins 
   video_player: ^2.4.5
   chewie: ^1.3.3

2. Just run the code and error will appear when we try to run app in the web and android simulator. Android device and iOS simulator tested working fine.

**Expected results:** 
It should play the video

**Actual results:** 
It's giving exception

<details>
<summary>Code sample</summary>
     
```
import 'package:appinio_video_player/appinio_video_player.dart';
import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(const VideoPlayerIssueApp());
}

class VideoPlayerIssueApp extends StatefulWidget {
  const VideoPlayerIssueApp({Key? key}) : super(key: key);

  @override
  State<VideoPlayerIssueApp> createState() => _VideoPlayerIssueAppState();
}

class _VideoPlayerIssueAppState extends State<VideoPlayerIssueApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
            child: VideoWidget(
                play: true,
                url:
                    "https://d2ybzxcqdye1lu.cloudfront.net/user/30361/output/post/video/e4e2a070-2d2e-4f8c-8d22-5fc8095346cb/hls-master-playlist.m3u8?Expires=1658037597&Signature=Sk-osneyk~Ao1TxgRrCEpeHcCyCOL~EJjTqk0WmC-z3BoxaLTlqg2XeetpNY40F3IFQ3SNMhn3wH7pIloc9Eh6huzC3LpNk0MxY2JJHdTGpkq7dIo17HrLi8nGPvyz3Ox-LEh7FgDdFu3i31pbh7GVrCue9l4LCOGdZ8SNDhhWesAVBDj2UvWd4DFS9VNeKRv8rI7W0BL9yPBaV26EXBWj9gOzln6JgNv0pu9gQpW8zSI69VmVs5BA1qfEQ9~EfoOPzzs3094TatWUSpSLqgep3VPRFl5XlZZF7VeTo5aT4T6INfCZj~cXU7BtpW8958D2CsAKBK36nVwLmXLOmT9g__&Key-Pair-Id=APKAIZSM57UC53QJB6MQ",
                aspectRatio: 3 / 2)),
      ),
    );
  }
}

class VideoWidget extends StatefulWidget {
  final bool play;
  final String url;
  final double aspectRatio;

  const VideoWidget({
    Key? key,
    required this.play,
    required this.url,
    required this.aspectRatio,
  }) : super(key: key);

  @override
  _VideoWidgetState createState() => _VideoWidgetState();
}

class _VideoWidgetState extends State<VideoWidget> {
  late VideoPlayerController videoPlayerController;
  late Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    super.initState();
    videoPlayerController = VideoPlayerController.network(widget.url);

    _initializeVideoPlayerFuture = videoPlayerController.initialize().then((_) {
      //       Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
      setState(() {});
    });
  } // This closing tag was missing

  @override
  void dispose() {
    videoPlayerController.dispose();
    //    widget.videoPlayerController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _initializeVideoPlayerFuture,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          print(videoPlayerController.value.aspectRatio);
          return Center(
            child: Chewie(
              key: PageStorageKey(widget.url),
              controller: ChewieController(
                videoPlayerController: videoPlayerController,
                //aspectRatio: widget
                // .aspectRatio, //videoPlayerController.value.aspectRatio ??

                // Prepare the video to be played and display the first frame
                autoInitialize: true,
                looping: false,
                autoPlay: false,
                // Errors can occur for example when trying to play a video
                // from a non-existent URL
                errorBuilder: (context, errorMessage) {
                  return Center(
                    child: Text(
                      errorMessage,
                      style: const TextStyle(color: Colors.white),
                    ),
                  );
                },
              ),
            ),
          );
        } else {
          return const Center(
            child: CircularProgressIndicator(),
          );
        }
      },
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

```
Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)
    at Object.createErrorWithStack (http://localhost:50688/dart_sdk.js:5419:12)
    at Error._throw (http://localhost:50688/dart_sdk.js:21341:18)
    at Error.throwWithStackTrace (http://localhost:50688/dart_sdk.js:21335:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50688/dart_sdk.js:43396:18)
    at Object._microtaskLoop (http://localhost:50688/dart_sdk.js:43223:13)
    at _startMicrotaskLoop (http://localhost:50688/dart_sdk.js:43229:13)
    at http://localhost:50688/dart_sdk.js:38359:9
Application finished.
```
</details>

<details>
  <summary>Flutter Doctor Output</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/sysquare/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sysquare/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = /Users/sysquare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment] 2022-07-11 08:33
Hi @rahulvyas, I think the issue is from the browser. 
When I open the URL in chrome/firefox, both chrome and firefox do not attempt to play the video but rather download it.

Safari on the other hand plays the video in the browser.  

This translates to the behavior I see when running a flutter app with the URL. 

In chrome/firefox I get the exception that you are reporting, however in Safari, the video plays as expected. 

Can you confirm if you experience the same?

**Comment by danagbemava-nc** [comment] 2022-07-12 06:30
Hi @rahulvyas, I'm not certain that there's anything you can do about it. From what I am seen online the m3u8 uses a format that is proprietary to Apple so the other browsers do not yet have support for it. 

What you can do is try to ensure that the format of the videos uploaded use a format that is supported by all the browsers. 

In the meantime, I'll be closing this issue as this is currently a browser limitation and not an issue with the plugin. 

Thank you

**Closed by danagbemava-nc** 2022-07-12 06:30 UTC
Labels: in triage
