### ISSUE TITLE
Possible bug related to isolates as all plugins get registered in each isolate

### ISSUE THREAD

**Issue by atrope** [flutter/flutter#97840] opened 2022-02-04 21:41 UTC
Hey Guys, 
I am digging further into an issue that maybe affecting the performance(and functionality) from all apps. 
When we create a new isolate in flutter (for example when we are using firebase messaging) our plugins are all registered and allocated in different memory spaces so for example, 
when we are using N plugins and we are using Firebase Messaging(that uses a new isolate)  in reality we are registering(onAttachedToEngine is running for)  N*(isolates+1) plugins?  
If so we should be able to Enable/disable plugins per isolate no? We don't need all plugins registered in each isolate as this affect performance.

I Have an issue that in my plugin onAttachedToEngine was checking if channel == null and was registering and saving to a variable but then when we started the Push notification isolate before the app(that means receiving a push and clicking on it), i was not able to use my plugin because the channel was registered to the Push Isolate. 

I Managed to fix by checking if we have already attached to activity but this is a workaround and IMHO we should be able to register/unregister plugin on isolates and/or recognizes on the onAttachedToEngine the "id" from the isolate and then we can do the logic in our app.

**Comment by atrope** [comment] 2022-02-07 16:54
Hi, can someone take a look at this issue?

**Comment by darshankawar** [comment] 2022-02-08 13:36
@atrope 
Sorry for picking this issue a bit late. Can you provide your `flutter doctor -v`, a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that possibly shows the issue along with expected and actual result ?
That way, it'll help to address this issue properly.

**Comment by atrope** [comment] 2022-02-14 18:07
@darshankawar 

Just run the firebase_messaging example adding any plugin in pubspec, for example this one:
```
  social_share:
    git:
      url: https://github.com/SuaMusica/social_share.git
      ref: feature/nullSafety
```
I Just added Logs when `onAttachedToEngine` is run.

Here is the forked example with only this change: 
https://github.com/atrope/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example



We can see that whenever the isolate is run we see onAttachedToEngine printed in Logcat(This is example is run twice, one for main app and another one after the isolate is created).

 We should be able to "blacklist" all plugins from registering if we do not need them in said isolate for example because this can cause trouble by a plugin being registered N Times and being requested things more than once in a channel.

Log:
```

2022-02-14 15:06:05.282 19691-19691/? I/ssaging.exampl: Late-enabling -Xcheck:jni
2022-02-14 15:06:05.304 19691-19691/? E/USNET: USNET: appName: io.flutter.plugins.firebase.messaging.example
2022-02-14 15:06:05.306 19691-19691/? D/ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-02-14 15:06:05.308 19691-19691/? D/ActivityThread: setConscryptValidator
2022-02-14 15:06:05.308 19691-19691/? D/ActivityThread: setConscryptValidator - put
2022-02-14 15:06:05.277 19691-19691/? I/libc: SetHeapTaggingLevel: tag level set to 0
2022-02-14 15:06:05.282 19691-19691/? I/ssaging.exampl: Late-enabling -Xcheck:jni
2022-02-14 15:06:05.304 19691-19691/? E/USNET: USNET: appName: io.flutter.plugins.firebase.messaging.example
2022-02-14 15:06:05.306 19691-19691/? D/ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-02-14 15:06:05.308 19691-19691/? D/ActivityThread: setConscryptValidator
2022-02-14 15:06:05.308 19691-19691/? D/ActivityThread: setConscryptValidator - put
2022-02-14 15:06:05.277 19691-19691/? I/libc: SetHeapTaggingLevel: tag level set to 0
2022-02-14 15:06:05.282 19691-19691/? I/ssaging.exampl: Late-enabling -Xcheck:jni
2022-02-14 15:06:05.336 19691-19691/io.flutter.plugins.firebase.messaging.example D/ActivityThread: handleBindApplication()++ app=io.flutter.plugins.firebase.messaging.example
2022-02-14 15:06:05.304 19691-19691/? E/USNET: USNET: appName: io.flutter.plugins.firebase.messaging.example
2022-02-14 15:06:05.306 19691-19691/? D/ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-02-14 15:06:05.308 19691-19691/? D/ActivityThread: setConscryptValidator
2022-02-14 15:06:05.308 19691-19691/? D/ActivityThread: setConscryptValidator - put
2022-02-14 15:06:05.336 19691-19691/io.flutter.plugins.firebase.messaging.example D/ActivityThread: handleBindApplication()++ app=io.flutter.plugins.firebase.messaging.example
2022-02-14 15:06:05.336 19691-19691/io.flutter.plugins.firebase.messaging.example D/ActivityThread: handleBindApplication()++ app=io.flutter.plugins.firebase.messaging.example
2022-02-14 15:06:05.337 19691-19691/io.flutter.plugins.firebase.messaging.example D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10661; state: DISABLED
2022-02-14 15:06:05.351 19691-19691/io.flutter.plugins.firebase.messaging.example D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2022-02-14 15:06:05.444 19691-19691/io.flutter.plugins.firebase.messaging.example V/GraphicsEnvironment: ANGLE Developer option for 'io.flutter.plugins.firebase.messaging.example' set to: 'default'
2022-02-14 15:06:05.444 19691-19691/io.flutter.plugins.firebase.messaging.example V/GraphicsEnvironment: App is not on the allowlist for updatable production driver.
2022-02-14 15:06:05.445 19691-19691/io.flutter.plugins.firebase.messaging.example D/LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=io.flutter.plugins.firebase.messaging.example appContext.mBasePackageName=io.flutter.plugins.firebase.messaging.example
2022-02-14 15:06:05.445 19691-19691/io.flutter.plugins.firebase.messaging.example D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-02-14 15:06:05.458 19691-19691/io.flutter.plugins.firebase.messaging.example D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-02-14 15:06:05.461 19691-19691/io.flutter.plugins.firebase.messaging.example W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
2022-02-14 15:06:05.461 19691-19691/io.flutter.plugins.firebase.messaging.example I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
2022-02-14 15:06:05.462 19691-19691/io.flutter.plugins.firebase.messaging.example D/FLTFireContextHolder: received application context.
2022-02-14 15:06:05.463 19691-19691/io.flutter.plugins.firebase.messaging.example D/ActivityThread: handleBindApplication() --
2022-02-14 15:06:05.611 19691-19736/io.flutter.plugins.firebase.messaging.example I/ResourceExtractor: Found extracted resources res_timestamp-1-1644861732355
2022-02-14 15:06:05.656 19691-19691/io.flutter.plugins.firebase.messaging.example D/PathProviderPlugin: Use TaskQueues.
2022-02-14 15:06:05.657 19691-19691/io.flutter.plugins.firebase.messaging.example D/SocialShare: onAttachedToEngine
2022-02-14 15:06:05.672 19691-19691/io.flutter.plugins.firebase.messaging.example W/ssaging.exampl: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (unsupported,test-api, reflection, allowed)
2022-02-14 15:06:05.672 19691-19691/io.flutter.plugins.firebase.messaging.example W/ssaging.exampl: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (unsupported, reflection, allowed)
2022-02-14 15:06:05.672 19691-19691/io.flutter.plugins.firebase.messaging.example W/ssaging.exampl: Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (unsupported, reflection, allowed)
2022-02-14 15:06:05.672 19691-19691/io.flutter.plugins.firebase.messaging.example W/ssaging.exampl: Accessing hidden method Landroid/util/LongArray;->get(I)J (unsupported, reflection, allowed)
2022-02-14 15:06:05.677 19691-19691/io.flutter.plugins.firebase.messaging.example W/FlutterActivityAndFragmentDelegate: A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
2022-02-14 15:06:05.681 19691-19691/io.flutter.plugins.firebase.messaging.example I/DecorView: [INFO] isPopOver=false, config=true
2022-02-14 15:06:05.681 19691-19691/io.flutter.plugins.firebase.messaging.example I/DecorView: updateCaptionType >> DecorView@2014069[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
2022-02-14 15:06:05.681 19691-19691/io.flutter.plugins.firebase.messaging.example D/DecorView: setCaptionType = 0, this = DecorView@2014069[]
2022-02-14 15:06:05.690 19691-19691/io.flutter.plugins.firebase.messaging.example I/MSHandlerLifeCycle: isMultiSplitHandlerRequested: ignored. pkg=io.flutter.plugins.firebase.messaging.example parent=null callers=com.android.internal.policy.DecorView.setVisibility:4216 android.app.ActivityThread.handleResumeActivity:5285 android.app.servertransaction.ResumeActivityItem.execute:54 android.app.servertransaction.ActivityTransactionItem.execute:45 android.app.servertransaction.TransactionExecutor.executeLifecycleState:176 
2022-02-14 15:06:05.690 19691-19691/io.flutter.plugins.firebase.messaging.example I/MSHandlerLifeCycle: removeMultiSplitHandler: no exist. decor=DecorView@2014069[]
2022-02-14 15:06:05.704 19691-19691/io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: setView = com.android.internal.policy.DecorView@2014069 TM=true
2022-02-14 15:06:05.705 19691-19691/io.flutter.plugins.firebase.messaging.example I/MSHandlerLifeCycle: isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@2014069[FlutterActivity]
2022-02-14 15:06:05.705 19691-19691/io.flutter.plugins.firebase.messaging.example I/MSHandlerLifeCycle: removeMultiSplitHandler: no exist. decor=DecorView@2014069[FlutterActivity]
2022-02-14 15:06:05.735 19691-19691/io.flutter.plugins.firebase.messaging.example I/SurfaceView: onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{5b32749 V.E...... ......I. 0,0-0,0} of ViewRootImpl@77671ab[FlutterActivity]
2022-02-14 15:06:05.745 19691-19754/io.flutter.plugins.firebase.messaging.example I/flutter: Observatory listening on http://127.0.0.1:35291/dhJh00f26e4=/
2022-02-14 15:06:05.752 19691-19691/io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=13 res=0x7 s={true 491984411872} ch=true fn=-1
2022-02-14 15:06:05.753 19691-19725/io.flutter.plugins.firebase.messaging.example D/hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-02-14 15:06:05.753 19691-19691/io.flutter.plugins.firebase.messaging.example I/SurfaceView: windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{5b32749 V.E...... ......ID 0,0-1080,2361} of ViewRootImpl@77671ab[FlutterActivity]
2022-02-14 15:06:05.753 19691-19691/io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11233 android.view.ViewRootImpl.performTraversals:4075 android.view.ViewRootImpl.doTraversal:2819 
2022-02-14 15:06:05.756 19691-19691/io.flutter.plugins.firebase.messaging.example I/SurfaceView: updateSurface: mVisible = true mSurface.isValid() = true
2022-02-14 15:06:05.757 19691-19691/io.flutter.plugins.firebase.messaging.example I/SurfaceView: updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
2022-02-14 15:06:05.757 19691-19691/io.flutter.plugins.firebase.messaging.example I/SurfaceView: surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{5b32749 V.E...... ......ID 0,0-1080,2361}
2022-02-14 15:06:05.764 19691-19691/io.flutter.plugins.firebase.messaging.example I/SurfaceView: surfaceChanged (1080,2361) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{5b32749 V.E...... ......ID 0,0-1080,2361}
2022-02-14 15:06:05.764 19691-19691/io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] dp(2) 1 android.view.SurfaceView.updateSurface:1369 android.view.SurfaceView.lambda$new$1$SurfaceView:253 android.view.SurfaceView$$ExternalSyntheticLambda2.onPreDraw:2 
2022-02-14 15:06:05.764 19691-19691/io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] pdf(1) 1 android.view.SurfaceView.notifyDrawFinished:607 android.view.SurfaceView.performDrawFinished:594 android.view.SurfaceView.$r8$lambda$st27mCkd9jfJkTrN_P3qIGKX6NY:0 
2022-02-14 15:06:05.764 19691-19691/io.flutter.plugins.firebase.messaging.example D/ViewRootImpl@77671ab[FlutterActivity]: Creating frameCompleteCallback mNextDrawUseBlastSync=false mReportNextDraw=true commitCallbacks size=0
2022-02-14 15:06:05.787 19691-19725/io.flutter.plugins.firebase.messaging.example D/ViewRootImpl@77671ab[FlutterActivity]: Received frameCompleteCallback frameNum=1
2022-02-14 15:06:05.793 19691-19691/io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$createFrameCompleteCallback$3$ViewRootImpl:4833 android.view.ViewRootImpl$$ExternalSyntheticLambda15.run:6 android.os.Handler.handleCallback:938 
2022-02-14 15:06:05.793 19691-19691/io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] rdf()
2022-02-14 15:06:05.807 19691-19691/io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2022-02-14 15:06:05.809 19691-19691/io.flutter.plugins.firebase.messaging.example D/InputMethodManager: startInputInner - Id : 0
2022-02-14 15:06:05.809 19691-19691/io.flutter.plugins.firebase.messaging.example I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2022-02-14 15:06:05.814 19691-19691/io.flutter.plugins.firebase.messaging.example D/InputMethodManager: startInputInner - Id : 0
2022-02-14 15:06:06.000 19691-19766/io.flutter.plugins.firebase.messaging.example I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2022-02-14 15:06:06.029 19691-19737/io.flutter.plugins.firebase.messaging.example W/FlutterJNI: FlutterJNI.loadLibrary called more than once
2022-02-14 15:06:06.029 19691-19736/io.flutter.plugins.firebase.messaging.example I/ResourceExtractor: Found extracted resources res_timestamp-1-1644861732355
2022-02-14 15:06:06.029 19691-19778/io.flutter.plugins.firebase.messaging.example W/FlutterJNI: FlutterJNI.prefetchDefaultFontManager called more than once
2022-02-14 15:06:06.031 19691-19691/io.flutter.plugins.firebase.messaging.example W/FlutterJNI: FlutterJNI.init called more than once
2022-02-14 15:06:06.033 19691-19691/io.flutter.plugins.firebase.messaging.example I/FLTFireBGExecutor: Creating background FlutterEngine instance, with args: []
2022-02-14 15:06:06.044 19691-19691/io.flutter.plugins.firebase.messaging.example D/PathProviderPlugin: Use TaskQueues.
2022-02-14 15:06:06.044 19691-19691/io.flutter.plugins.firebase.messaging.example D/SocialShare: onAttachedToEngine
2022-02-14 15:06:06.267 19691-19691/io.flutter.plugins.firebase.messaging.example I/FLTFireMsgService: FlutterFirebaseMessagingBackgroundService started!
2022-02-14 15:06:06.700 19691-19738/io.flutter.plugins.firebase.messaging.example I/flutter: FCM Token: dQzJbBioQCGsRy62RJiGhn:APA91bFXbOxR0z6biwVbFYJbVrUHd4HvccnFfjsamDYT-i4avb5iQpi2K9OV9J_DST4dHX_grUciBU9V2y2sotnZg4l6wexELlOmYhGlVTJ2cB2AzPEE1GE7aNKnPMuQV0s7DqhcJdTi

```


You can even see that PathProviderPlugin is also started twice by the `D/PathProviderPlugin: Use TaskQueues.` debug message.

**Comment by darshankawar** [comment] 2022-02-15 05:04
@atrope 
Thanks for the update. Does this behavior occur only when you run `firebase_messaging` example ? or with other plugins too ?

**Comment by atrope** [comment] 2022-02-15 05:16
@darshankawar this is related to any isolate.
I've put the messaging example because it was easier to setup and show

**Comment by darshankawar** [comment] 2022-02-15 13:10
@atrope 
Can you check if you are doing any activity inside `MainActivity()` ? Like below:

```
public class MainActivity extends FlutterActivity {
  // You can keep this empty class or remove it. Plugins on the new embedding
  // now automatically registers plugins.
}
```

**Comment by atrope** [comment] 2022-02-15 13:41
@darshankawar  as you can see in the example i sent it doesn't even have  a MainActivity class.

**Comment by darshankawar** [comment] 2022-02-16 06:17
@atrope 
Is this happening in debug or in release mode ? Also, are you using `--obfuscate` ?
If so, if you don't use that flag, is the behavior expected ?

**Comment by atrope** [comment] 2022-02-16 12:09
Happening in both, not using obfuscate.

**Comment by darshankawar** [comment] 2022-02-17 05:36
@atrope 
Please check [this](https://github.com/flutter/flutter/issues/98591) issue and see if it's related to your case.

**Comment by atrope** [comment] 2022-02-17 18:33
hey @darshankawar it is not related.It is exactly the opposite.

**Comment by darshankawar** [comment] 2022-02-18 06:30
Thanks for these details. Using the code sample and steps to replicate and running on Android, I do see the same log as reported and specially `onAttachedEngine` entries:

```
io.flutter.plugins.firebase.messaging.example D/ActivityThread: handleBindApplication()++ app=io.flutter.plugins.firebase.messaging.example
io.flutter.plugins.firebase.messaging.example D/ActivityThread: handleBindApplication()++ app=io.flutter.plugins.firebase.messaging.example
io.flutter.plugins.firebase.messaging.example D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10661; state: DISABLED
io.flutter.plugins.firebase.messaging.example D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
io.flutter.plugins.firebase.messaging.example V/GraphicsEnvironment: ANGLE Developer option for 'io.flutter.plugins.firebase.messaging.example' set to: 'default'
io.flutter.plugins.firebase.messaging.example V/GraphicsEnvironment: App is not on the allowlist for updatable production driver.
io.flutter.plugins.firebase.messaging.example D/LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=io.flutter.plugins.firebase.messaging.example appContext.mBasePackageName=io.flutter.plugins.firebase.messaging.example
io.flutter.plugins.firebase.messaging.example D/NetworkSecurityConfig: No Network Security Config specified, using platform default
io.flutter.plugins.firebase.messaging.example D/NetworkSecurityConfig: No Network Security Config specified, using platform default
io.flutter.plugins.firebase.messaging.example W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
io.flutter.plugins.firebase.messaging.example I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
io.flutter.plugins.firebase.messaging.example D/FLTFireContextHolder: received application context.
io.flutter.plugins.firebase.messaging.example D/ActivityThread: handleBindApplication() --
io.flutter.plugins.firebase.messaging.example I/ResourceExtractor: Found extracted resources res_timestamp-1-1644861732355
io.flutter.plugins.firebase.messaging.example D/PathProviderPlugin: Use TaskQueues.
io.flutter.plugins.firebase.messaging.example D/SocialShare: onAttachedToEngine
io.flutter.plugins.firebase.messaging.example I/SurfaceView: surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{5b32749 V.E...... ......ID 0,0-1080,2361}
io.flutter.plugins.firebase.messaging.example I/SurfaceView: surfaceChanged (1080,2361) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{5b32749 V.E...... ......ID 0,0-1080,2361}
io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] dp(2) 1 android.view.SurfaceView.updateSurface:1369 android.view.SurfaceView.lambda$new$1$SurfaceView:253 android.view.SurfaceView$$ExternalSyntheticLambda2.onPreDraw:2 
io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] pdf(1) 1 android.view.SurfaceView.notifyDrawFinished:607 android.view.SurfaceView.performDrawFinished:594 android.view.SurfaceView.$r8$lambda$st27mCkd9jfJkTrN_P3qIGKX6NY:0 
io.flutter.plugins.firebase.messaging.example D/ViewRootImpl@77671ab[FlutterActivity]: Creating frameCompleteCallback mNextDrawUseBlastSync=false mReportNextDraw=true commitCallbacks size=0
io.flutter.plugins.firebase.messaging.example D/ViewRootImpl@77671ab[FlutterActivity]: Received frameCompleteCallback frameNum=1
io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$createFrameCompleteCallback$3$ViewRootImpl:4833 android.view.ViewRootImpl$$ExternalSyntheticLambda15.run:6 android.os.Handler.handleCallback:938 
io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: [DP] rdf()
io.flutter.plugins.firebase.messaging.example I/ViewRootImpl@77671ab[FlutterActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
io.flutter.plugins.firebase.messaging.example D/InputMethodManager: startInputInner - Id : 0
io.flutter.plugins.firebase.messaging.example I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
io.flutter.plugins.firebase.messaging.example D/InputMethodManager: startInputInner - Id : 0
io.flutter.plugins.firebase.messaging.example I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
io.flutter.plugins.firebase.messaging.example W/FlutterJNI: FlutterJNI.loadLibrary called more than once
io.flutter.plugins.firebase.messaging.example I/ResourceExtractor: Found extracted resources res_timestamp-1-1644861732355
io.flutter.plugins.firebase.messaging.example W/FlutterJNI: FlutterJNI.prefetchDefaultFontManager called more than once
io.flutter.plugins.firebase.messaging.example W/FlutterJNI: FlutterJNI.init called more than once
io.flutter.plugins.firebase.messaging.example I/FLTFireBGExecutor: Creating background FlutterEngine instance, with args: []
io.flutter.plugins.firebase.messaging.example D/PathProviderPlugin: Use TaskQueues.
io.flutter.plugins.firebase.messaging.example D/SocialShare: onAttachedToEngine
io.flutter.plugins.firebase.messaging.example I/FLTFireMsgService: FlutterFirebaseMessagingBackgroundService started!
```

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.612, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.612 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c50b02f2c3 (60 minutes ago), 2022-02-17 22:44:23 -0500
    • Engine revision 605454e201
    • Dart version 2.17.0 (build 2.17.0-118.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by chinmaygarde** [comment] 2022-02-22 22:41
cc @gaaclarke who may have the most background on plugin initialization.

**Comment by gaaclarke** [comment] 2022-02-22 23:01
Isolates spawned in Dart actually don't register plugins.  That is why a developer created `flutter_isolates` https://pub.dev/packages/flutter_isolate.  I suspect `firebase_messaging` may be doing a similar trick.  That means your problem with registering plugins multiple times isn't a Flutter issue, but a `firebase_messaging` issue.  Said differently, I don't think you could reproduce the issue without `firebase_messaging`.

I'd see if you can reproduce it without `firebase_messaging`.  If so, add the reproduction here.  If not, I'd file an issue against that package.

**Comment by atrope** [comment] 2022-02-22 23:41
@gaaclarke I see that.. @darshankawar is it possible to move this issue to flutterfire repo? Or should i create the same issue linking to this one?

**Comment by darshankawar** [comment] 2022-02-23 05:01
@atrope 
Since flutterfire repo is outside of flutter, you'll need to file this separately here: https://github.com/FirebaseExtended/flutterfire/issues
I'll close this so you can create a new one and link it.

**Closed by darshankawar** 2022-02-23 05:01 UTC
Labels: engine, severe: performance, dependency: dart, p: framework, has reproducible steps, P4, found in release: 2.10, found in release: 2.11
