### ISSUE TITLE
[tool_crash] StateError: Bad state: No element

### ISSUE THREAD

**Issue by desainimit** [flutter/flutter#73158] opened 2020-12-31 05:42 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=21b97383 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No element
```
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:63:32)
<asynchronous suspension>
#2      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:249:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-IN)
    • Flutter version 1.26.0-1.0.pre at C:\flutter
    • Framework revision 63062a6443 (3 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/Desai Nimit/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/Desai Nimit/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Desai Nimit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • vivo 1917 (mobile) • 21b97383 • android-arm64 • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 63062a64432cce03315d6b5196fda7912866eb37
### Plugins
integration_test

**Comment by darshankawar** [comment] 2020-12-31 07:44
@desainimit 
Try [this](https://github.com/flutter/flutter/issues/47040#issuecomment-579185623) solution and see if it helps.
If issue persists, please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by bkonyi** [comment] 2021-01-05 23:58
This is a duplicate of https://github.com/flutter/flutter/issues/72385.

**Closed by bkonyi** 2021-01-05 23:58 UTC
Labels: in triage, waiting for customer response

**Comment by bkonyi** [comment] 2021-01-06 00:19
@desainimit, we've been having a hard time reproducing this issue and would really appreciate your assistance. Is this something you've been able to reproduce consistently on your end? If so, would you mind sharing details of your environment (IDE, operating system, target device type, general circumstance in which you see the issue, etc) in #72385? If you have a reproduction case, that would be even more helpful!

**Comment by aliasgarlabs** [comment] 2021-06-07 13:52
You need to implement `orElse` for the `firstWhere` function.

Eg. 

```
list.firstWhere(
                  (element) => element.isDeleted,
                  orElse: () => null);


```

**Comment by ribinshad** [comment] 2021-07-06 08:51
> You need to implement `orElse` for the `firstWhere` function.
> 
> Eg.
> 
> ```
> list.firstWhere(
>                   (element) => element.isDeleted,
>                   orElse: () => null);
> ```

now error shows on null

**Comment by aliasgarlabs** [comment] 2021-07-06 14:10
> > You need to implement `orElse` for the `firstWhere` function.
> > Eg.
> > ```
> > list.firstWhere(
> >                   (element) => element.isDeleted,
> >                   orElse: () => null);
> > ```
> 
> now error shows on null

orElse function returns `null` if the filter in `firstWhere` couldn't find any matches. If you are getting `null` because your condition didn't find any matches.

**Comment by aliasgarlabs** [comment] 2021-07-06 14:13
For what it's worth, `orElse` should be a required argument.

**Comment by RakaAlrian** [comment] 2021-07-28 11:01
> > > You need to implement `orElse` for the `firstWhere` function.
> > > Eg.
> > > ```
> > > list.firstWhere(
> > >                   (element) => element.isDeleted,
> > >                   orElse: () => null);
> > > ```
> > 
> > 
> > now error shows on null
> 
> orElse function returns `null` if the filter in `firstWhere` couldn't find any matches. If you are getting `null` because your condition didn't find any matches.

I getting error at `orElse: () => null` after upgrading to null safety, any suggestion please?

**Comment by aliasgarlabs** [comment] 2021-07-28 12:14
You can mark your var as nullable and then do a null check after the `firstWhere` query. 

https://dart.dev/codelabs/dart-cheatsheet#nullable-variables
