### ISSUE TITLE
Error: The getter 'toolbarIsVisible' was called on null

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#64471] opened 2020-08-24 16:54 UTC
This error was cropping up in the logs of a production app running v1.17.1.  Looking at the stack trace, I don't see any new code changes that definitely would have fixed this, but if we don't hear any reports of it from later versions in awhile, this issue should be closed.

Reported in https://github.com/flutter/flutter/issues/34571#issuecomment-678558456.

<details>

<summary>Stack Trace</summary>

```
Error:
NoSuchMethodError: The getter 'toolbarIsVisible' was called on null.
Receiver: null
Tried calling: toolbarIsVisible
Stack trace:
#0 EditableTextState.toggleToolbar (package:flutter/src/widgets/editable_text.dart:1879)
#1 _TextFieldState._handleSelectionHandleTapped (package:flutter/src/material/text_field.dart:937)
#2 _TextSelectionHandleOverlayState._handleTap (package:flutter/src/widgets/text_selection.dart:702)
#3 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
#4 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504)
#5 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:297)
#6 BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254)
#7 GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156)
#8 (:222)
#9 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
#10 GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
#11 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
#12 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
#13 _rootRunUnary (dart:async/zone.dart:1196)
#14 _CustomZone.runUnary (dart:async/zone.dart:1085)
#15 _CustomZone.runUnaryGuarded (dart:async/zone.dart:987)
#16 _invoke1 (dart:ui/hooks.dart:275)
#17 _dispatchPointerDataPacket (dart:ui/hooks.dart:184)
```

</details>

## Steps to Reproduce

Unknown, but it seems to come from tapping on a selection handle in certain cases.  The stack trace leads to this line:

https://github.com/flutter/flutter/blob/f7a6a7906be96d2288f5d63a5a54c515a6e987fe/packages/flutter/lib/src/widgets/text_selection.dart#L702

If anyone has any clues about how to reproduce this, please post a comment!

**Comment by pedromassangocode** [comment] 2020-08-25 07:02
Hi @justinmc 
Can I close this as a duplicate of https://github.com/flutter/flutter/issues/64368 or we should track this here?

**Comment by justinmc** [comment] 2020-08-25 16:06
@pedromassango Thanks, I missed that issue.  Looks like that one has been closed and we're using this one to track the bug, which sounds good to me.

**Comment by justinmc** [comment] 2020-09-25 21:00
Since this issue has failed to attract anyone else corroborating the bug, I'm going to close it.  If anyone has this problem in the future though, please comment!

**Comment by CaleyD** [comment] 2020-10-27 00:20
We are seeing this error in our production application. 

Here is the stack reported from Crashlytics:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: NoSuchMethodError: The getter 'toolbarIsVisible' was called on null.
Receiver: null
Tried calling: toolbarIsVisible. Error thrown Instance of 'ErrorDescription'.
       at [APP]-[flutter]--[unhandled_flutter]--editable_text.NoSuchMethodError_The_getter_'toolbarIsVisible'_was_called_on_nullR:_([APP]-[flutter]--[unhandled_flutter]--editable_text.java:2351)
       at EditableTextState.toggleToolbar(EditableTextState.java:2351)
       at _SelectableTextState._handleSelectionHandleTapped(_SelectableTextState.java:515)
       at _TextSelectionHandleOverlayState._handleTap(_TextSelectionHandleOverlayState.java:725)
       at GestureRecognizer.invokeCallback(GestureRecognizer.java:183)
       at TapGestureRecognizer.handleTapUp(TapGestureRecognizer.java:598)
       at BaseTapGestureRecognizer._checkUp(BaseTapGestureRecognizer.java:304)
       at BaseTapGestureRecognizer.acceptGesture(BaseTapGestureRecognizer.java:259)
       at GestureArenaManager.sweep(GestureArenaManager.java:157)
       at GestureBinding.handleEvent(GestureBinding.java:362)
       at GestureBinding.dispatchEvent(GestureBinding.java:338)
       at RendererBinding.dispatchEvent(RendererBinding.java:267)
       at GestureBinding._handlePointerEvent(GestureBinding.java:295)
       at GestureBinding._flushPointerEventQueue(GestureBinding.java:240)
       at GestureBinding._handlePointerDataPacket(GestureBinding.java:213)
```

**Comment by justinmc** [comment] 2020-10-27 16:21
@CaleyD Thanks for reporting!  What version of Flutter is that coming from?  And do you have any idea how to reproduce the problem?

**Comment by CaleyD** [comment] 2020-11-02 20:52
> @CaleyD Thanks for reporting! What version of Flutter is that coming from? And do you have any idea how to reproduce the problem?

This is coming from 1.22.0 and I have no idea how to reproduce but I can confirm it happens regularly to our users from the evidence in our Crashlytics logs.

**Comment by justinmc** [comment] 2020-11-03 15:49
Thanks, I suppose I'll reopen and keep trying to gather information.  If anyone can reproduce or sees this locally, let us know.

**Comment by darshankawar** [comment] 2022-09-21 12:17
@justinmc Hi, we have a newest issue with very similar stack trace : https://github.com/flutter/flutter/issues/111660 with a likely root-cause and a potential fix. Is it ok to close this in favor of the new one ?

**Comment by gnprice** [comment] 2023-02-18 20:42
I believe this was fixed by #111995. The code now looks like this:
```dart
  void toggleToolbar([bool hideHandles = true]) {
    final TextSelectionOverlay selectionOverlay = _selectionOverlay ??= _createSelectionOverlay();
    if (selectionOverlay.toolbarIsVisible) {
```

which will not call that getter on null.

**Comment by exaby73** [comment] 2023-02-20 09:36
@justinmc Could you confirm on [the](https://github.com/flutter/flutter/issues/64471#issuecomment-1435765223). If this issue is indeed fixed, we can close this issue. Looks like https://github.com/flutter/flutter/issues/111660 is indeed closed as fixed

**Comment by gnprice** [comment] 2023-03-04 04:57
Closing for the reasons above, as having been duplicated by #111660 and fixed.

**Closed by gnprice** 2023-03-04 04:57 UTC
Labels: a: text input, framework, passed first triage, P4

**Comment by justinmc** [comment] 2023-03-06 22:00
Sorry for the absence here, I agree with this being closed.
