### ISSUE TITLE
cloud_firestore runTransaction future completes before transaction finished

### ISSUE THREAD

**Issue by illia-romanenko** [flutter/flutter#32037] opened 2019-05-03 16:36 UTC
## Steps to Reproduce

0. Use cloud_firestore 0.9.7 - more recent versions not working for me due to some compilation issues on iOS.
1. Run Transaction concurrently (from multiple devices) using something like the following code
 ```
Firestore.instance.runTransaction((Transaction transaction) async {
      print("start");
      DocumentSnapshot packageSnapshot = await transaction.get(packageReference);
      if (packageSnapshot.exists) {
      print(packageSnapshot.data['deliveryUserId']);
        if (packageSnapshot.data['deliveryUserId'] == null) {
          await transaction
              .update(packageReference, <String, dynamic>{'deliveryUserId': 'test', 'deliveryUserName': 'test'});
        } else {
          print("not null");
        }
      }
    }).then((val) {
      print("result");
    }).catchError((v) {
      print("error");
    });

```

### So on first device, it outputs
start
null
result

### On the second device (android), it outputs
start
null
result <--- So as you see result returned before all retries complete
start
test
not null

###  If iOS start transaction second -  it outputs:
start
null
start
test
not null
start
test
not null
start
test
not null
start
test
not null
error

## Logs

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E227, locale en-UA)
    • Flutter version 1.2.1 at /Users/illia/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/illia/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 9.0.4+11)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).


```

**Comment by BondarenkoStas** [comment] 2019-10-15 11:12
@illia-romanenko did you manage to resolve it?

**Comment by iapicca** [comment] 2019-11-08 10:01
Hi @illia-romanenko 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 10:01 UTC
Labels: waiting for customer response
