### ISSUE TITLE
Difficulties to run tests with Firestore extenstions

### ISSUE THREAD

**Issue by degloff** [flutter/flutter#48800] opened 2020-01-14 12:39 UTC
I constantly get 

MissingPluginException(No implementation found for method FirebaseApp#appNamed on channel plugins.flutter.io/firebase_core)

A presume it has to do with a missing plugin installation. I tried this setup calling MethodChannel as I discovered in the tests but without success. What do I overlook?

```
import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/services.dart';
import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final Completer<String> completer = Completer<String>();
  enableFlutterDriverExtension(handler: (_) => completer.future);
  tearDownAll(() => completer.complete(null));

  group('$Firestore', () {
    Firestore firestore;
    Firestore firestoreWithSettings;
    const MethodChannel firebaseCoreChannel = MethodChannel('plugins.flutter.io/firebase_core');

    setUp(() async {
      final FirebaseOptions firebaseOptions = const FirebaseOptions(
        googleAppID: ....
        gcmSenderID: '....',
        apiKey: '.....',
        projectID: '....',
      );
      final FirebaseApp app = await FirebaseApp.configure(
        name: 'test',
        options: firebaseOptions,
      );
      final FirebaseApp app2 = await FirebaseApp.configure(
        name: 'test2',
        options: firebaseOptions,
      );
      firestore = Firestore(app: app);
      firestoreWithSettings = Firestore(app: app2);
      await firestoreWithSettings.settings(
        persistenceEnabled: true,
        host: null,
        sslEnabled: true,
        cacheSizeBytes: 1048576,
      );
    });

    test('getDocumentsWithFirestoreSettings', () async {
      final Query query = firestoreWithSettings.collection('wallets').limit(1);
      final QuerySnapshot querySnapshot = await query.getDocuments();
      expect(querySnapshot.documents.length, 1);
    });

```

**Comment by degloff** [comment] 2020-01-14 12:40
I can use Firestore DB properly in my mobile app though.

**Comment by iapicca** [comment] 2020-01-15 08:31
Hi @degloff 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-15 08:31 UTC
