### ISSUE TITLE
Scrolling a multiline TextField within an InteractiveViewer scrolls both the text field and the viewer

### ISSUE THREAD

**Issue by UnicornaasTech** [flutter/flutter#153497] opened 2024-08-15 14:35 UTC
### Steps to reproduce

Create a multi-line TextField within an InteractiveViewer.
Enter more rows of text in the TextField than maxLines can show.
Scroll the TextField.

### Expected results

Expecting that only TextField's content is scrolled.

### Actual results

Both TextField scrolls, and also InteractiveViewer's viewport moves (either scales or pans, depending on your settings). This really disturbs the user.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'issue demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
      ),
      home: const MyHomePage(title: 'Demo text field scrolling issue within intearctive viewer'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: InteractiveViewer(
      child: InteractiveViewerWithTextField()
      )
    );
  }
}


class InteractiveViewerWithTextField extends StatefulWidget {
  @override
  _InteractiveViewerWithTextFieldState createState() =>
      _InteractiveViewerWithTextFieldState();
}

class _InteractiveViewerWithTextFieldState
    extends State<InteractiveViewerWithTextField> {
  final TransformationController _transformationController =
      TransformationController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Interactive Viewer with TextField"),
      ),
      body: Center(
        child: InteractiveViewer(
          transformationController: _transformationController,
          boundaryMargin: EdgeInsets.all(double.infinity),
          child: Stack(
            children: [
              // Background Image (replace with your image)
              Container(
                decoration: BoxDecoration(
                  color: Colors.amber,
                  ),
                ),
              
              Positioned(
                top: 100,
                left: 50,
                child: SizedBox(
                  width: 200,
                  child: TextField(
                    keyboardType: TextInputType.multiline,
                    minLines: 4,
                    maxLines: 4,
                    decoration: InputDecoration(
                      filled: true,
                      fillColor: Colors.white70,
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/cb6801b3-4ffa-4691-a715-6907336a0529

</details>

### Logs

<details open><summary>Logs</summary>

```console
N/A
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale fi-FI)
    • Flutter version 3.24.0 on channel stable at /Users/panuhallfors/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/panuhallfors/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.65.2)
    • VS Code at /Users/panuhallfors/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.101

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by UnicornaasTech** [comment] 2024-08-15 14:37
Just noticed that in the example code, there are two nested InteractiveViewer's. That's an error in the example.
The issue also happens when you don't have nested InteractiveViewers, but only one.

**Comment by moffatman** [comment] 2024-08-15 18:30
I guess you are scrolling with a mouse?

If so, there is some known improvement needed to `InteractiveViewer` here

https://github.com/flutter/flutter/issues/135132#issuecomment-1728164343

**Comment by UnicornaasTech** [comment] 2024-08-15 18:42
Yes, scrolling with mouse (MacBook touchpad more specifically).
Thanks for reference, it seems that #135132 is the same problem but another way around in the example: there InteractiveViewer is within another widget, whereas in this item, it's the wrapping one.

**Comment by moffatman** [comment] 2024-08-15 19:28
MacBook touchpad is not mouse. I was thinking of like a PC mouse with mouse wheel.
It's not clear from your video. are you running on Web or on Desktop (macOS native)?
If it's web, then it still is the bug I showed above, because on Web trackpad and mosue wheel are treated pretty similarly.
I didn't see this bug when running your example on macOS Desktop. But I do see it on Web.

**Comment by UnicornaasTech** [comment] 2024-08-16 05:51
Yup, it's web. Sorry for missing this out in the original report.

**Comment by danagbemava-nc** [comment] 2024-08-16 06:51
Closing this as a duplicate of https://github.com/flutter/flutter/issues/135132 based on https://github.com/flutter/flutter/issues/153497#issuecomment-2292044846


Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-08-16 06:51 UTC
Labels: in triage
