### ISSUE TITLE
Flutter has exited unexpectedly on linux

### ISSUE THREAD

**Issue by basha97** [flutter/flutter#52872] opened 2020-03-19 05:29 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --target lib/main.dart -d RZ8M903MPFK --track-widget-creation --start-paused

## exception

FileSystemException: FileSystemException: Failed to set file modification time, path = '/home/adilbasha/development/flutter_project/transezy_flutter/.packages' (OS Error: Operation not permitted, errno = 1)

```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:211:19)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:599:17)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1465:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
#40     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.8 at /home/adilbasha/development/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/adilbasha/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/84/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/84/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • SM M307F • RZ8M903MPFK • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-03-19 07:32
Duplicate to [#49948](https://github.com/flutter/flutter/issues/49948)

Duplicate of [#50880](https://github.com/flutter/flutter/issues/50880)

**Closed by TahaTesser** 2020-03-19 07:32 UTC
