### ISSUE TITLE
CupertinoDatePicker in time mode gets confused around 12am/pm

### ISSUE THREAD

**Issue by Kretin1** [flutter/flutter#27755] opened 2019-02-11 02:49 UTC
## Steps to Reproduce

Cupertino DateTime picker is getting confused around AM and PM if use24hFormat is false.

1. When 12:XX PM is initial time, moving to 11:XX swaps to AM correctly and reports correct time, but moving to 1:XX swaps to AM. Just moving the minute value displays PM but reports as 0:XX instead of 12:XX.
2. When 1:XX PM is initial time, moving to back to 12:XX or forward to 2:XX swaps to AM instead of staying at PM.
3. When 0:XX is initial time, moving back to 11:XX swaps to PM, but moving back to 10:XX incorrectly swaps back to AM. Moving forward to 1:XX stays at AM, but moving forward to 2:XX incorrectly swaps to PM

The Flutter Gallery Pickers demo for Time and "Date and Time" display same behavior.

Also on iOS AM is displayed as "am", and PM as "pm"

Code:
```dart
TimeOfDay startTime = TimeOfDay.now();
await showCupertinoModalPopup(
        context: context,
        builder: (BuildContext context) {
          return _buildBottomPicker(
            CupertinoDatePicker(
              mode: CupertinoDatePickerMode.time,
              initialDateTime: new DateTime(date.year, date.month, date.day, startTime.hour, startTime.minute),
              onDateTimeChanged: (DateTime newDateTime) {
                //setState(() => time = newDateTime);
                time = new TimeOfDay(hour: newDateTime.hour, minute: newDateTime.minute);
              },
            ),
          );
        },
      );
```

## Logs

```
D:\VSProjects\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.2.0 at D:\VSProjects\flutter
    • Framework revision 06b979c4d5 (2 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Jonny\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

[!] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • HTC 0PJA10 • FA632YJ02378 • android-arm64 • Android 7.0 (API 24)
```

**Comment by timtraversy** [comment] 2019-02-11 05:00
Weird! I can't recreate any of this behavior locally. I uploaded screen recordings for each of your test cases [here](https://drive.google.com/open?id=1d8zgtIYrxSWykM7PzHwM7e5R7A0Iqhvr). Could you share what yours looks like?

Your framework version is two weeks old so it is possible this has been fixed. If so, you can try running 
```
flutter channel master
flutter upgrade
```

**Comment by Kretin1** [comment] 2019-02-11 06:57
Thanks Tim,

I upgraded Flutter just before posting. [Here is a video](https://drive.google.com/file/d/1MLu652lDL_Bpp60EYqdO87lyimgndOKJ/view?usp=sharing) of my previous results.

I followed your advice which switched to 'master' branch from 'origin' and upgraded to 1.2.1. 
The AM PM display now seems to be behaving correctly as in your videos, but when initialTime is set to 12PM, it still returns 12AM.

**Comment by zoechi** [comment] 2019-02-11 08:30
@Kretin1 thanks for reporting.
Could you please post a minimal but complete runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by Kretin1** [comment] 2019-02-11 11:56
Thanks @zoechi 

Here I am setting the initial time to 12:12(pm). If you only change the minutes it returns 0:XX instead of 12:XX
```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Cupertino Time Picker',
      home: new MyHomePage(title: 'Cupertino Time Picker'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TimeOfDay time;

  void _openTimePicker() async
  {
    DateTime date = DateTime.now();
    await showCupertinoModalPopup(
      context: context,
      builder: (BuildContext context) {
        return _buildBottomPicker(
          CupertinoDatePicker(
            mode: CupertinoDatePickerMode.time,
            initialDateTime: new DateTime(date.year, date.month, date.day, 12, 12),
            onDateTimeChanged: (DateTime newDateTime) {
              //setState(() => time = newDateTime);
              print(newDateTime.toString());
              date = newDateTime;
              //time = new TimeOfDay(hour: newDateTime.hour, minute: newDateTime.minute);
            },
          ),
        );
      },
    );
    print(date.toString());
    _setTime(date);
  }
  void _setTime(DateTime newDateTime) {
    setState(() {
      time = new TimeOfDay(hour: newDateTime.hour, minute: newDateTime.minute);
    });
  }
  @override
  initState()
  {
    time = TimeOfDay.now();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              time.hour.toString() + ':' + time.minute.toString(),
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _openTimePicker,
        tooltip: 'Set Time',
        child: new Icon(Icons.timer),
      ),
    );
  }

  Widget _buildBottomPicker(Widget picker) {
    return Container(
      height: 216.0,
      padding: const EdgeInsets.only(top: 6.0),
      color: CupertinoColors.white,
      child: DefaultTextStyle(
        style: const TextStyle(
          color: CupertinoColors.black,
          fontSize: 22.0,
        ),
        child: GestureDetector(
          // Blocks taps from propagating to the modal sheet and popping.
          onTap: () {},
          child: SafeArea(
            top: false,
            child: picker,
          ),
        ),
      ),
    );
  }
}

```

**Comment by timtraversy** [comment] 2019-02-11 14:34
Ok I found it: https://github.com/flutter/flutter/blob/b8a035a3d416a19756c60c4fcf2394b4af06740f/packages/flutter/lib/src/cupertino/date_picker.dart#L426-L432.
The `AmPm` variable is set to 1 if the time is in PM, so if it is 10 PM it will add 12 to make it 22. However if the time is 12PM, it will add 12 and make it 24, which overflows back to 0.
This is fixed with:
```
    return DateTime(
      date.year,
      date.month,
      date.day,
      selectedHour % 12 + selectedAmPm * 12,
      selectedMinute,
    );
```
I'll open PR.

**Comment by Kretin1** [comment] 2019-02-12 22:05
Thanks so much.

I was looking at that, but was the end of a busy day so my brain wasn't processing it well enough to fix.

**Comment by Kretin1** [comment] 2019-02-12 22:09
While you're there please consider adding this:
```
Widget _buildAmPmPicker(double offAxisFraction, TransitionBuilder itemPositioningBuilder) {
...
          Text(
            index == 0
              ? localizations.anteMeridiemAbbreviation.toLowerCase()
              : localizations.postMeridiemAbbreviation.toLowerCase()
...
```

**Comment by timtraversy** [comment] 2019-02-12 22:13
Why lowercase? I think iOS style is uppercase.
https://www.google.com/search?q=ios+time+picker&safe=off&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjz3f-7m7fgAhXOTN8KHd5pCDcQ_AUIDigB&biw=997&bih=814&dpr=2#imgrc=jX0kgUaoWBy2SM:

**Comment by Kretin1** [comment] 2019-02-13 02:32
Maybe it's my location (Australia) but iPod and iPad (iOS 12 and iOS10) both show lower case when setting the alarm time, however I'm struggling to find images that [show what I'm seeing](https://drive.google.com/file/d/1fwvt6_gwu-Bn_aey8NvTlu_W6_yBbTno/view?usp=sharing)

**Closed** 2019-02-13 21:03 UTC
Labels: f: cupertino, f: date/time picker, framework
