### ISSUE TITLE
MediaQuery.of(context) makes cursor in TextField move to start

### ISSUE THREAD

**Issue by PashaTurok** [flutter/flutter#108526] opened 2022-07-28 09:24 UTC
This is screen code:

```
import 'package:flutter/material.dart';

class Model {
  String? text;

  Model(this.text);
}

class TempDialog extends StatefulWidget {

  TempDialog({Key? key}) : super(key: key);

  @override
  State<TempDialog> createState() => _TempDialogState();
}

class _TempDialogState extends State<TempDialog> {

  final model = Model("This is test text");

  @override
  Widget build(BuildContext context) {
    var textController = TextEditingController(text: model.text);
    return AlertDialog(
      content: Container(
        width: MediaQuery
            .of(context)
            .size
            .width - 50,
        height: MediaQuery
            .of(context)
            .size
            .height - 300,
        child: Column(
          children: [
            TextField(
              textAlign: TextAlign.left,
              decoration: InputDecoration(
                contentPadding: EdgeInsets.all(10.0),
              ),
              keyboardType: TextInputType.multiline,
              maxLines: null,
              minLines: 4,
              controller: textController,
            )
          ],
        ),
      ),
    );
  }
}

class TempScreen extends StatefulWidget {

  TempScreen({Key? key}) : super(key: key);

  @override
  State<TempScreen> createState() => _TempScreenState();
}

class _TempScreenState extends State<TempScreen> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Temp screen"),
      ),
      body: Column(
        children: [
          TextButton(
              onPressed: (){
                showDialog(
                    context: context,
                    builder: (BuildContext context) {
                      return TempDialog();
                    }
                );
              },
              child: Text("Tap me"))
        ],
      ),
    );
  }
}
```

And this is the result:

![Untitled](https://user-images.githubusercontent.com/10261361/181470686-c085c9b9-8421-4d57-94d9-5b307afbd019.gif)

As you see although a user taps somewhere in the middle of the text, after keyboard appears cursor moves to start (home). The problem is in these lines:
```
        width: MediaQuery
            .of(context)
            .size
            .width - 50,
        height: MediaQuery
            .of(context)
            .size
            .height - 300,
```
If we replace them with these :

```
        width: 200,
        height: 200,
```
everything works as expected

**Comment by maheshmnj** [comment] 2022-07-28 12:47
Hi @PashaTurok, Thanks for filing the issue. This is working as intended. Notice that you are initializing textController under the build method

```
 var textController = TextEditingController(text: model.text);
```
And build method is getting called whenever the MediaQuery changes (Opening/ closing the keyboard). So the cursor position gets set to zero.

To prevent this issue you can initialize the controller out of the build method to persist state. See the below code sample where I am initializing textController in initState which will solve the issue.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

class Model {
  String? text;

  Model(this.text);
}

class TempDialog extends StatefulWidget {
  TempDialog({Key? key}) : super(key: key);

  @override
  State<TempDialog> createState() => _TempDialogState();
}

class _TempDialogState extends State<TempDialog> {
  final model = Model("This is test text");

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    textController = TextEditingController(text: model.text);
  }

  late TextEditingController textController;
  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      content: Container(
        width: MediaQuery.of(context).size.width - 50,
        height: MediaQuery.of(context).size.height - 300,
        child: Column(
          children: [
            TextField(
              textAlign: TextAlign.left,
              decoration: InputDecoration(
                contentPadding: EdgeInsets.all(10.0),
              ),
              keyboardType: TextInputType.multiline,
              maxLines: null,
              minLines: 4,
              controller: textController,
            )
          ],
        ),
      ),
    );
  }
}

class TempScreen extends StatefulWidget {
  TempScreen({Key? key}) : super(key: key);

  @override
  State<TempScreen> createState() => _TempScreenState();
}

class _TempScreenState extends State<TempScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Temp screen"),
      ),
      body: Column(
        children: [
          TextButton(
              onPressed: () {
                showDialog(
                    context: context,
                    builder: (BuildContext context) {
                      return TempDialog();
                    });
              },
              child: Text("Tap me"))
        ],
      ),
    );
  }
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TempScreen(),
    );
  }
}

```
</details> 


 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Closed by maheshmnj** 2022-07-28 12:47 UTC
Labels: in triage
