### ISSUE TITLE
[Impeller] ImageFilter.blur Edge sampling issue

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119289] opened 2023-01-26 22:27 UTC
In the app at https://github.com/HayesGordon/flutter-rive-design-code-demo

On the screen here https://github.com/HayesGordon/flutter-rive-design-code-demo/blob/main/lib/rive_app/on_boarding/onboarding_view.dart#L60.

The blur ImageFilter flickers at the right apparently due to an edge sampling issue. See attached video:

cc @bdero 

https://user-images.githubusercontent.com/6343103/214964801-d376d199-2f52-4115-aa1f-9fd330e9a820.mp4

**Comment by bdero** [comment] 2023-02-02 10:50
The surface-level cause of this flicker is that the subpass coverage is slightly misaligned with a clip being applied to the blurred savelayer:

Left is the color attachment, right is the stencil attachment:
![image](https://user-images.githubusercontent.com/919017/216218318-a2fb3127-8727-4bee-a139-ea06e6cca57e.png)

Because the rive animation in the source app is being rendered into a savelayer which is filtered with clamp sampling, changes to edge colors result in a dramatic change reflected across many pixels. Similar to Skia, we create minimally sized textures for the coverage of the contents. This combination of behavior reveals coverage artifacts in a way that's not entirely trivial to deal with. Note that this also happens in Skia (and I believe this is intended behavior -- more below), but a little less dramatically (see the bottom edge):

https://user-images.githubusercontent.com/919017/216300821-729b3ee5-70df-403f-97db-2f44bb43a03c.mov

With https://github.com/flutter/engine/pull/39336, we easily eliminate the right side flicker entirely in Impeller (aside from the "snapping" action, of course. However, the bottom is still leaky because it's unbounded by the screen size:

https://user-images.githubusercontent.com/919017/216302147-8ed024ce-9d9b-4410-a7af-2f18e5607641.mov

This flicker isn't really something that can be fully solved within Impeller itself (or Skia) without more information about the user's intent. The best way to control the layer in this situation would be to either use a different sampling mode, or specify the "bounds" hint when the savelayer to expand the bottom of the layer a bit.

**Comment by chinmaygarde** [comment] 2023-02-02 17:29
The linked patch looks good to go. I'm treating this as a bug tracking differences between Impeller and the current renderer. If we close this, we might lost context on the flicker at the bottom. Perhaps we can just lift what you said in a different bug and track that separately?

**Comment by bdero** [comment] 2023-02-02 19:02
The example app is using `ImageFiltered` to create the layer. Not sure if there's a way to tickle rive into making the bottom layer always expand.
```dart
        ImageFiltered(
          imageFilter: ImageFilter.blur(sigmaX: 30, sigmaY: 30),
          child: const RiveAnimation.asset(app_assets.shapesRiv),
        ),
```

Adding `fit: BoxFit.fill`, the bottom flicker looks much less dramatic, but it doesn't go away entirely.

**Comment by bdero** [comment] 2023-02-03 01:08
Closing, made a follow-up for the non-impeller specific problem here: https://github.com/flutter/flutter/issues/119873

**Closed by bdero** 2023-02-03 01:08 UTC
Labels: engine, impeller
