### ISSUE TITLE
After the iOS textfield returns to the page in flutter 3.22.1, reclicking cannot invoke the keyboard.

### ISSUE THREAD

**Issue by wahkim** [flutter/flutter#149393] opened 2024-05-31 07:40 UTC
### Steps to reproduce

1. Enter any text in the textfield and click to jump to another page
2. Then gesture right swipe back (note that you must gesture right swipe back here)
3. After returning, click textfield again to refocus, but no keyboard pops up

### Expected results

The input box refocuses

### Actual results

The input field cannot be refocused

### Code sample

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_textfield/test_2.dart';

class TestField extends StatefulWidget {
  const TestField({super.key});

  @override
  State<TestField> createState() => _TestFieldState();
}

class _TestFieldState extends State<TestField> {
  FocusNode focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          TextButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute<void>(
                    builder: (BuildContext context) => Test2(),
                  ),
                );
              },
              child: Text('跳转'))
        ],
      ),
      body: Container(
        child: Center(
          child: TextField(
            focusNode: focusNode,
          ),
        ),
      ),
    );
  }
}



class Test2 extends StatefulWidget {
  const Test2({super.key});

  @override
  State<Test2> createState() => _Test2State();
}

class _Test2State extends State<Test2> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        child: Center(
          child: Text('2'),
        ),
      ),
    );
  }
}

```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

https://github.com/flutter/flutter/assets/33590201/191382e2-bcba-4c91-b7c4-a7095809d869

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.1, on macOS 13.6.1 22G313 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by huycozy** [comment] 2024-05-31 09:52
Hi @wahkim, this is a known issue at https://github.com/flutter/flutter/issues/148867 and it should be fixed on Flutter master channel, you can try switching to master channel and check the issue:

```
flutter channel master
flutter upgrade
```

I will close this as a duplicate of https://github.com/flutter/flutter/issues/148867. There is also a cherry pick request that you can follow up on it.

**Closed by huycozy** 2024-05-31 09:52 UTC
Labels: in triage

**Comment by FelixMittermeier** [comment] 2024-05-31 20:51
@huycozy Can this please be cherry picked into the stable branch? IMO this is an issue with a serious user impact if the keyboard does not open at all in some cases. Also having trouble with this bug in my app with the latest flutter version.

Would be much appreciated if a cherry pick could be considered, thanks.

**Comment by ebwood** [comment] 2024-06-01 14:53
> Hi @wahkim, this is a known issue at #148867 and it should be fixed on Flutter master channel, you can try switching to master channel and check the issue:
> 
> ```
> flutter channel master
> flutter upgrade
> ```
> 
> I will close this as a duplicate of #148867. There is also a cherry pick request that you can follow up on it.

I doubt the company projects would use master channel which is beta as their development sdk version. Doesn't such a big problem deserve a hotfix?

**Comment by DennisKragekjaer** [comment] 2024-06-02 10:21
I think this is very urgent, having exact same issue. It works fine when going back to the page where the textfield is, but when swiping back there is no way to gain focus on a textfield.

**Comment by wahkim** [comment] 2024-06-03 02:05
> 嗨@wahkim，这是一个已知问题，在#148867，它应该在Flutter主频道上修复，您可以尝试切换到主频道并检查问题：>> ````> 颤动通道主> 颤动升级> ````>> 我将把作为#148867的副本来关闭。还有一个樱桃采摘请求，你可以跟进。

最新版本与插件冲突，如何指定更新到3.22.0-0.19.0.pre版本

**Comment by huycozy** [comment] 2024-06-03 03:17
This is the cherry-pick request, please follow up on it: https://github.com/flutter/flutter/issues/149178

**Comment by DennisKragekjaer** [comment] 2024-06-03 06:34
Solved it temporarily by cherry picking routes.dart

**Comment by lukemmtt** [comment] 2024-06-06 22:50
A hotfix release (Flutter 3.22.2) was released today that resolves this issue:
https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md#3222-june-06-2024
