### ISSUE TITLE
didChangeDependencies is not called

### ISSUE THREAD

**Issue by kevinengel** [flutter/flutter#27994] opened 2019-02-15 08:58 UTC
Recently upgraded flutter and some of my Widgets which explicitly call `context.inheritFromWidgetOfExactType(MediaQuery)` no longer have `didChangeDependencies` fire when the keyboard appears/disappears.

Example code (Ugh's `didChangeDependencies` works, its child Meh's `didChangeDependencies` does not):

```dart
import 'package:flutter/material.dart';

void main() => runApp(Main());

class Main extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'didChangeDependencies bug',
      home: Ugh(),
    );
  }
}

class Ugh extends StatefulWidget {
  @override
  UghState createState() => UghState();
}

class UghState extends State<Ugh> {

  @override void didChangeDependencies() {
    context.inheritFromWidgetOfExactType(MediaQuery);
    print('Ugh');
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Why U No Work?'),
      ),
      body: Meh(),
    );
  }
}

class Meh extends StatefulWidget {
  @override
  MehState createState() => MehState();
}

class MehState extends State<Meh> {

  @override void didChangeDependencies() {
    context.inheritFromWidgetOfExactType(MediaQuery);
    print('Meh');
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: TextField(),
    );
  }
}
```

`flutter doctor -v`:

```
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.2.0 at C:\Users\Admin\Desktop\flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Pixel 3 • 8CCX1MHY7 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by zoechi** [comment] 2019-02-15 09:04
What version did you upgrade from?

**Comment by kevinengel** [comment] 2019-02-15 17:21
From the git commit log, I'm guessing the previous version was v1.1.9  (Unless they just list all the versions as they update past them ...?)  Is there a better way to check?  The previous upgrade was sometime in early January on the dev branch.

**Comment by zoechi** [comment] 2019-02-15 17:59
That's ok. Could also have been 0.7.0 or 1.0.0 or similar. 
So it was a very recent version and the change was introduce not long ago.

**Comment by kevinengel** [comment] 2019-02-15 19:33
While we're here I'll also note that even prior to this recent upgrade I had run across a case where didChangeDependencies didn't work as expected.

Similar to the example presented above, but instead of a child Widget, the parent called showDialog with a custom Widget.  Again in this case only the parent's didChangeDependencies was called when the keyboard appeared/disappeared, not the dialog's Widget.

Not sure what branch I was working on at that point, it may have been the stable branch.

**Comment by zoechi** [comment] 2019-02-17 13:12
Not sure about your latest example. A dialog is not show as a descendant of the widget that calls `showDialog`. This would require a minimal reproduction to diagnose as well.

**Comment by kevinengel** [comment] 2019-02-20 04:41
Here's the dialog example:

```
import 'package:flutter/material.dart';

void main() => runApp(Main());

class Main extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'didChangeDependencies bug',
      home: Ugh(),
    );
  }
}

class Ugh extends StatefulWidget {
  @override
  UghState createState() => UghState();
}

class UghState extends State<Ugh> {

  @override void didChangeDependencies() {
    context.inheritFromWidgetOfExactType(MediaQuery);
    print('Ugh');
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Why U No Work?'),
      ),
      body: Center(
        child: FlatButton(
          child: Text('PRESS ME'),
          onPressed: () {
            showDialog(
              context: context,
              builder: (context) {
                return Dialog(child: Meh());
              },
            );
          },
        ),
      ),
    );
  }
}

class Meh extends StatefulWidget {
  @override
  MehState createState() => MehState();
}

class MehState extends State<Meh> {

  @override
  void didChangeDependencies() {
    context.inheritFromWidgetOfExactType(MediaQuery);
    print('Meh');
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: TextField(),
    );
  }
}
```

`flutter doctor -v`

```
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.1.8 at C:\Users\Admin\Desktop\flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Pixel 3 • 8CCX1MHY7 • android-arm64 • Android 9 (API 28)
```

Note that the initial non-dialog example works properly for this beta v1.1.8 channel (i.e. both 'Ugh' and 'Meh' are printed each time the keyboard appears/disappears) but this version with the dialog does not.

**Comment by dnfield** [comment] 2019-05-15 21:51
Can you check if showing the Keyboard fires the window's onMetricsChanged callback?

**Comment by MustansirZia** [comment] 2019-06-19 17:26
I had a very similar behavior but only in case of Android. The `didChangeDependencies ` callback wasn't getting called in some child widgets when the keyboard was toggling. What I did was, made my widget a `WidgetsBindingObserver`, subscribed and implemented my own `didChangeMetrics` callback. That did it and this was getting called on both iOS and Android when the keyboard was toggled. 
So I moved what I had to do inside `didChangeDependencies` and placed it inside `didChangeMetrics`. 
This does indeed have something to with dialogs/overlays as my widget was kind of an overlay.

**Comment by chunhtai** [comment] 2019-07-17 21:30
I investigated it a little bit it turns out that Ugh and Meh are subscribe to different mediaQuery
here is the tree structure
MaterialApp
  MediaQuery1
    Ugh(dependencies: [MediaQuery1])
      Scaffold
        MediaQuery2
          Meh(dependencies: [MediaQuery2])

and it turns out the keyboard event only trigger the notification of MediaQuery1.
I am still investigate what the right fix is

**Comment by chunhtai** [comment] 2019-07-19 21:21
This is a changes introduce in https://github.com/flutter/flutter/pull/26259
I think the change is intended @HansMuller The MediaQuery inside scaffold will no longer trigger by keyboard padding

@kevinengel Let me know if this is a concern for you

**Comment by kevinengel** [comment] 2019-07-22 19:51
How do you recommend I detect the keyboard appear/disappear in these child widgets then?

**Comment by chunhtai** [comment] 2019-07-22 20:19
One example could be https://github.com/adee42/flutter_keyboard_visibility

**Comment by chunhtai** [comment] 2019-07-26 17:11
I will close this issue for now as this is intended change. Feel free to reopen if you have other concern

**Closed by chunhtai** 2019-07-26 17:11 UTC
Labels: framework, severe: regression
