### ISSUE TITLE
flutter android sdkmanager error !!!

### ISSUE THREAD

**Issue by eminyazann** [flutter/flutter#52101] opened 2020-03-06 10:56 UTC
AndroidStudio is updated everything is updated ı think error come from here
 C:\Users\lanet\AppData\Local\Android\sdk\tools\bin\sdkmanager
 because this folder couldnt created when ı looked to there ım waiting for advices . thank you

C:\Users\lanet>flutter doctor -v 
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.592], locale tr-TR)

• Flutter version 1.12.13+hotfix.8 at C:\src\flutter
• Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
• Engine revision e1e6ced81d
• Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)

• Android SDK at C:\Users\lanet\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
X Android license status unknown.
  Try re-installing or updating your Android SDK Manager.
  See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.6)

• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 44.0.2
• Dart plugin version 192.7761
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.42.1)

• VS Code at C:\Users\lanet\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.8.1

[!] Connected device

! No devices available

! Doctor found issues in 2 categories.

C:\Users\lanet>flutter doctor --android-licenses

Android sdkmanager tool not found (C:\Users\lanet\AppData\Local\Android\sdk\tools\bin\sdkmanager).

Try re-installing or updating your Android SDK,

visit https://flutter.dev/setup/#android-setup for detailed instructions.

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by TahaTesser** [comment] 2020-03-06 10:58
Duplicate of [#51712](https://github.com/flutter/flutter/issues/51712#issuecomment-595487979)

Please follow up there

**Closed by TahaTesser** 2020-03-06 10:58 UTC

**Comment by eminyazann** [comment] 2020-03-06 11:23
thank you @TahaTesser
