### ISSUE TITLE
`SystemChrome.setSystemUIOverlayStyle` doesn't change colors

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#88431] opened 2021-08-18 13:19 UTC
## Steps to Reproduce

Run the code sample and enable different sections of it to see the effect and click the button

**Expected results:** when change color without brightness, it should change

**Actual results:** nothing happens, no assertions, warnings, and this behavior is not documented as far as I can tell.
Verified on Android 9 and Android 11

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

Future<void> main() async {
  runApp(App());
}

class App extends StatefulWidget {
  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  bool red = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Center(
              child: ElevatedButton(
                onPressed: () {
                  final color = red ? Color(0xffff0000) : Color(0xff00ff00);
                  red = !red;

                  // divider color is changing, other colors are not

                  SystemChrome.setSystemUIOverlayStyle(
                    SystemUiOverlayStyle(
                      systemNavigationBarColor: color,
                      statusBarColor: color,
                      systemNavigationBarDividerColor: color,
                      // statusBarBrightness: Brightness.light,
                      // statusBarIconBrightness: Brightness.light,
                      // systemNavigationBarIconBrightness: Brightness.light,

                      // These parameters do not affect the situation, whether they are true or false
                      //
                      //
                      // systemStatusBarContrastEnforced: false,
                      // systemNavigationBarContrastEnforced: false,
                    ),
                  );

                  // status bar now changes color (no matter what brightenss is set)

                  // SystemChrome.setSystemUIOverlayStyle(
                  //   SystemUiOverlayStyle(
                  //     systemNavigationBarColor: color,
                  //     statusBarColor: color,
                  //     systemNavigationBarDividerColor: color,
                  //     statusBarBrightness: Brightness.light,
                  //     statusBarIconBrightness: Brightness.light,
                  //     // systemNavigationBarIconBrightness: Brightness.light,
                  //   ),
                  // );

                  // nav bar now changes color (no matter what brightenss is set)

                  // SystemChrome.setSystemUIOverlayStyle(
                  //   SystemUiOverlayStyle(
                  //     systemNavigationBarColor: color,
                  //     statusBarColor: color,
                  //     systemNavigationBarDividerColor: color,
                  //     // statusBarBrightness: Brightness.light,
                  //     // statusBarIconBrightness: Brightness.light,
                  //     systemNavigationBarIconBrightness: Brightness.light,
                  //   ),
                  // );

                  // all colors are changing (no matter what brightenss is set)
                  
                  // SystemChrome.setSystemUIOverlayStyle(
                  //   SystemUiOverlayStyle(
                  //     systemNavigationBarColor: color,
                  //     statusBarColor: color,
                  //     systemNavigationBarDividerColor: color,
                  //     statusBarBrightness: Brightness.light,
                  //     statusBarIconBrightness: Brightness.light,
                  //     systemNavigationBarIconBrightness: Brightness.light,
                  //   ),
                  // );
                },
                child: Text('click'),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.83, on Microsoft Windows [Version 10.0.19041.1110], locale ru-RU)
    • Flutter version 2.5.0-7.0.pre.83 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 06be7e5392 (4 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1110]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-08-19 16:23
HI @nt4f04uNd 
Thanks for filing the issue

This seems like a regression, I can't reproduce it `stable, 2.2.3`, it reproduces from `beta` to `master`. Tested on multiple Android devices 11




|  `stable`  |  `beta`  | `dev` | `master` |
| :---: | :---: | :---: |:---: |
|  ✅  |   ❌  |  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/taha/Code/flutter_stable
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • Linux (desktop)  • linux            • linux-x64      • Linux
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel beta, 2.5.0-5.1.pre, on Pop!_OS 21.04 5.11.0-7620-generic,
    locale en_US.UTF-8)
    • Flutter version 2.5.0-5.1.pre at /home/taha/Code/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 65cf7de5f4 (8 days ago), 2021-08-11 15:48:01 -0700
    • Engine revision fbeb7e22bd
    • Dart version 2.14.0 (build 2.14.0-377.4.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • Linux (desktop)  • linux            • linux-x64      • Pop!_OS 21.04
      5.11.0-7620-generic
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel dev, 2.5.0-6.0.pre, on Pop!_OS 21.04 5.11.0-7620-generic,
    locale en_US.UTF-8)
    • Flutter version 2.5.0-6.0.pre at /home/taha/Code/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 225a43d941 (2 weeks ago), 2021-08-05 11:32:48 -0700
    • Engine revision 07ec4b82c7
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • Linux (desktop)  • linux            • linux-x64      • Pop!_OS 21.04
      5.11.0-7620-generic
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      92.0.4515.131

• No issues found
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.155, on Pop!_OS 21.04
    5.11.0-7620-generic, locale en_US.UTF-8)
    • Flutter version 2.5.0-7.0.pre.155 at /home/taha/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff547a9234 (11 hours ago), 2021-08-19 01:17:04 -0400
    • Engine revision 9a54e9e05c
    • Dart version 2.15.0 (build 2.15.0-29.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • Linux (desktop)  • linux            • linux-x64      • Pop!_OS 21.04
      5.11.0-7620-generic
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced

Thank you

**Comment by TahaTesser** [comment] 2021-08-19 16:25
cc: @stuartmorgan

**Comment by blasten** [comment] 2021-08-19 17:27
@Piinks I think this is related to changes in https://github.com/flutter/engine/pull/27018/files#diff-8dfd4b72efbe5f5b494de945a284feba1d7e63a71e56a567235e6748717801caR372

**Comment by Piinks** [comment] 2021-08-19 18:41
Thanks for reporting! I am looking into this now.

**Comment by Piinks** [comment] 2021-08-19 20:41
Fix is in https://github.com/flutter/engine/pull/28206, will request cherry pick.

Thew refactoring in https://github.com/flutter/engine/pull/27018 caused this for both the status and navigation bar color.

**Closed** 2021-08-20 03:42 UTC
Labels: severe: regression, platform-android, framework, waiting for PR to land (fixed), a: layout, has reproducible steps, cp: 2.5, found in release: 2.5
