### ISSUE TITLE
UpdateEditingValue of TextInputClient called twice on Android

### ISSUE THREAD

**Issue by keepfocusontechnology** [flutter/flutter#70835] opened 2020-11-19 13:29 UTC
I think maybe I have the same problem with #46680  When I click  the textField content.the TextEditingController listener sometimes call twice. And when my language is The Arab. The  TextEditingController`s selection may give me different value.
- this my log:
![image](https://user-images.githubusercontent.com/8263580/99671024-67d9ca80-2aac-11eb-9034-5f141157899a.png)

- this my Phone Screen capture,I just click the content once:

![image](https://user-images.githubusercontent.com/8263580/99671172-a1123a80-2aac-11eb-832e-056e0e2447a3.png)

- My code :

<details><summary>Code</summary>

```
import 'package:flutter/material.dart';

import 'custom_rich_text.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BugTest',
      home: ExampleWidget(),
    );
  }
}


class ExampleWidget extends StatefulWidget {
  ExampleWidget({Key key}) : super(key: key);

  @override
  _ExampleWidgetState createState() => new _ExampleWidgetState();
}





/// State for [ExampleWidget] widgets.
class _ExampleWidgetState extends State<ExampleWidget> {
  final TextEditingController _controller = new TextEditingController();
  
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller.addListener((_printLatestValue));
  }


  _printLatestValue() {
    print("_controller.value: ${_controller.selection}");
  }
  
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Padding(
            padding: EdgeInsets.only(left: 100,right: 100),
              child: new TextField(
                autofocus: true,
                onChanged: (String value) {
                  print("onChanged run ... $value");
                },
                maxLines: 10,
                minLines: 5,
                controller: _controller,
                decoration: new InputDecoration(
                  contentPadding: EdgeInsets.symmetric(horizontal: 10,vertical: 5),
                  hintText: 'Type something',
                  border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(5),
                      borderSide: BorderSide.none),
                  filled: true,
                  fillColor: Color(0xffaaaaaa),
                ),
              ),
            ),
          new RaisedButton(
            onPressed: () {
              showDialog(
                context: context,
                child: new AlertDialog(
                  title: new Text('What you typed'),
                  content: new Text(_controller.text),
                ),
              );
            },
            child: new Text('DONE'),
          ),
        ],
      ),
    );
  }
}
```
</details>

- flutter verson:
![image](https://user-images.githubusercontent.com/8263580/99671806-87252780-2aad-11eb-84bc-a1fd8dd11fd3.png)

**Comment by pedromassangocode** [comment] 2020-11-19 13:56
I confirm that this issue is reproducible on current stable and beta but **NOT** reproducible on current master channel.

Cc @pcsosinski 

<details><summary>flutter doctor -v (master)</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.304, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.304 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision c6290500f8 (12 hours ago), 2020-11-18 17:29:28 -0800
    • Engine revision 35a0b9fe68
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile) • 0258ff700005 • android-arm64  • Android 8.1.0 (API
      27)
    • macOS (desktop)       • macos        • darwin-x64     • Mac OS X 10.15.7
      19H2 darwin-x64
    • Web Server (web)      • web-server   • web-javascript • Flutter Tools
    • Chrome (web)          • chrome       • web-javascript • Google Chrome
      86.0.4240.198

• No issues found!
```
</details>

<details><summary>flutter doctor -v (beta)</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en)
    • Flutter version 1.23.0-18.1.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 198df796aa (5 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Redmi 5 Plus (mobile) • 0258ff700005 • android-arm64  • Android 8.1.0 (API 27)
    • Web Server (web)      • web-server   • web-javascript • Flutter Tools
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 86.0.4240.198

• No issues found!

```
</details>

<details><summary>flutter doctor -v (stable)</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Redmi 5 Plus (mobile) • 0258ff700005 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

```
</details>

**Comment by keepfocusontechnology** [comment] 2020-11-25 07:53
any updates?  the master also find this issue @pedromassangocode

**Comment by pedromassangocode** [comment] 2020-11-25 09:07
Nope, you can use master or beta channel or wait until the changes are merged into stable!

**Comment by keepfocusontechnology** [comment] 2020-12-03 04:02
Hi @pedromassangocode, I confirm that this issue is reproducible on master channel

**Comment by pedromassangocode** [comment] 2020-12-03 09:11
Just tested now and it does not seems to reproduce the issue on latest master.
Please provide your `flutter doctor -v`.

**Comment by keepfocusontechnology** [comment] 2020-12-07 06:38
Hi ~@pedromassangocode  ,this is my flutter version.  u can try the Arab language environment.

[✓] Flutter (Channel master, 1.24.0-8.0.pre.321, on macOS 11.0.1 20B50 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.24.0-8.0.pre.321 at /Users/mr_qual1ty/softwore/flutter
    • Framework revision 05dadb0120 (2 weeks ago), 2020-11-20 07:33:05 +0530
    • Engine revision a0da844845
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mr_qual1ty/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • ELE L29 (mobile) • XPH0219725002545 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by keepfocusontechnology** [comment] 2020-12-07 06:46
![IMG_0050](https://user-images.githubusercontent.com/8263580/101318074-ad630980-389a-11eb-8b41-ac1788bb9f09.GIF)
I also found a problem that in the Arabic language environment, the cursor position of IOS is not reliable. For example, in my gif, there is a big gap between the cursor position when adding a character or backtracking a character.

**Comment by pedromassangocode** [comment] 2020-12-07 12:21
@keepfocusontechnology 
I would suggest you to upgrade to the latest master version (`1.25`)!

**Comment by keepfocusontechnology** [comment] 2020-12-10 07:45
I tried, but there were still problems . I fount same issue[#34610](https://github.com/flutter/flutter/issues/34610)

**Comment by keepfocusontechnology** [comment] 2020-12-10 07:56
@GaryQian  Hi~GrayQian, ~~~ I have seen your reply under other issues. I hope you can also read this problem and give me a solution. ~~~thank you!

**Comment by maheshmnj** [comment] 2022-12-02 05:40
Hi @keepfocusontechnology, I verified this issue on the latest stable and the master channel and I cannot reproduce it. This issue is very likely fixed.

<details>
<summary>logs</summary>

```console
Restarted application in 414ms.
flutter: _controller.value: TextSelection.collapsed(offset: 0, affinity: TextAffinity.downstream, isDirectional: false)
flutter: _controller.value: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... a
flutter: _controller.value: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... as
flutter: _controller.value: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asd
flutter: _controller.value: TextSelection.collapsed(offset: 4, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdf
flutter: _controller.value: TextSelection.collapsed(offset: 5, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfg
flutter: _controller.value: TextSelection.collapsed(offset: 6, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfgh
flutter: _controller.value: TextSelection.collapsed(offset: 7, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfghj
flutter: _controller.value: TextSelection.collapsed(offset: 8, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfghjk
flutter: _controller.value: TextSelection.collapsed(offset: 9, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfghjka
flutter: _controller.value: TextSelection.collapsed(offset: 10, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfghjkas
flutter: _controller.value: TextSelection.collapsed(offset: 11, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfghjkasd
flutter: _controller.value: TextSelection.collapsed(offset: 12, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfghjkasdf
flutter: _controller.value: TextSelection.collapsed(offset: 13, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfghjkasdfg
flutter: _controller.value: TextSelection.collapsed(offset: 14, affinity: TextAffinity.downstream, isDirectional: false)
flutter: onChanged run ... asdfghjkasdfgh

```
</details> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing, since this is no longer reproducible. Incase you still encounter the issue. Please feel free to comment on this issue and we will reopen it.

**Closed by maheshmnj** 2022-12-02 05:40 UTC
Labels: a: text input, framework, f: material design, has reproducible steps, found in release: 1.22, found in release: 1.23
