### ISSUE TITLE
Text renders blur on mac

### ISSUE THREAD

**Issue by yahu1031** [flutter/flutter#111351] opened 2022-09-10 18:59 UTC
When I click a button to show this dialog, It renders blur initially. If there is any mouse movement, then it fixes the rendering issue automatically.

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. And click the button

**Expected results:** 
![image](https://user-images.githubusercontent.com/35523357/189496185-b32dc62b-7626-4439-9238-98de51ca85b3.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/35523357/189496170-e9c868af-2d44-4cdf-8e61-90eeb9cb7abf.png)

<details>
<summary>Code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:math' as math;

void main(List<String> args) {
  runApp(
    const MyApp(),
  );
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
          body: Center(
        child: TextButton(
          child: const Text('Hello World'),
          onPressed: () {
            showDialog<AlertDialog>(
              context: context,
              builder: (BuildContext context) {
                return const SystemRequirements();
              },
            );
          },
        ),
      )),
    );
  }
}


class SystemRequirements extends StatefulWidget {
  const SystemRequirements({
    Key? key,
  }) : super(key: key);

  @override
  State<SystemRequirements> createState() => _SystemRequirementsState();
}

class _SystemRequirementsState extends State<SystemRequirements> {
  bool isChecking = false;
  String? logDir;
  Future<void> init() async {
    logDir = (await getApplicationSupportDirectory()).path;
    setState(() {});
  }

  @override
  void initState() {
    init();
    super.initState();
  }

  @override
  void setState(VoidCallback fn) {
    if (mounted) {
      super.setState(fn);
    }
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      width: 500,
      child: AlertDialog(
        backgroundColor: Colors.white,
        title: const Text(
          'System Requirements',
          style: TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 20,
          ),
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            const Text(
              'Please make sure you have the following requirements before installing the app:',
              style: TextStyle(
                fontSize: 14,
              ),
            ),
            if (!Platform.isLinux)
              BulletPoint(
                isChecking: isChecking,
                content:
                    '${Platform.operatingSystem} version must be ${Platform.isWindows ? '7 SP!' : '10.7'} or later.',
                bulletColor:
                    Colors.red,
              ),
            BulletPoint(
              isChecking: isChecking,
              content:
                  '${Platform.operatingSystemVersion.split('" ')[0].replaceAll('"', '')} Architecture must be x64 (x86-64)',
              bulletColor: Colors.red,
            ),
            BulletPoint(
              isChecking: isChecking,
              content: 'Disk space of at least 2GB',
              bulletColor: Colors.red,
            ),
            BulletPoint(
              isChecking: isChecking,
              content:
                  'Other tools like ${Platform.isWindows ? 'Windows Powershell 5.0(or new), Git for windows' : Platform.isMacOS ? 'xCode, git' : 'bash, curl, file, git, mkdir, rm, unzip, which,\n xz-utils, zip, libglu1-mesa/mesa-libGLU'}, Java(11 recommended).',
              bulletColor: Colors.red,
            ),
            isChecking
                ? const SizedBox(height: 69)
                : Padding(
                    padding: const EdgeInsets.symmetric(vertical: 18.0),
                    child: TextButton(
                      style: ButtonStyle(
                        backgroundColor: MaterialStateProperty.all<Color>(
                          Colors.red,
                        ),
                      ),
                      onPressed: () async {
                        setState(() {
                          isChecking = true;
                        });
                        setState(() {
                          isChecking = false;
                        });
                      },
                      child: const Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Text(
                          'Check',
                          style: TextStyle(
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ),
            if (kDebugMode)
              Center(
                child: logDir == null
                    ? AdaptiveLoading(
                        size: Platform.isMacOS ? 5 : 10,
                      )
                    : Text(
                        'Your logs files are stored here\n$logDir',
                        textAlign: TextAlign.center,
                        style: const TextStyle(
                          fontSize: 10,
                        ),
                      ),
              ),
          ],
        ),
      ),
    );
  }
}

class BulletPoint extends StatelessWidget {
  final String? content;
  final TextStyle? contentStyle;
  final Color? bulletColor;
  final bool isChecking;
  const BulletPoint({
    Key? key,
    required this.content,
    required this.isChecking,
    this.contentStyle,
    this.bulletColor,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10.0, horizontal: 17.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 3.5),
            child: isChecking
                ? AdaptiveLoading(
                    size: Platform.isMacOS ? 5 : 10,
                    strokeWidth: 1.5,
                  )
                : CustomPaint(
                    size: const Size(10, 10),
                    painter: CircleBullet(
                      bulletColor ??
                               Colors.black
                    ),
                  ),
          ),
          Text(
            content!,
            style: contentStyle ??
                const TextStyle(
                  fontSize: 12,
                ),
          ),
        ],
      ),
    );
  }
}

class CircleBullet extends CustomPainter {
  CircleBullet(this.color);
  final Color color;
  @override
  void paint(Canvas canvas, Size size) {
    Paint paint0Fill = Paint()..style = PaintingStyle.fill;
    paint0Fill.color = color.withOpacity(1.0);
    canvas.drawCircle(Offset(size.width * 0.5, size.height * 0.5),
        size.width * 0.5, paint0Fill);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}

class AdaptiveLoading extends StatefulWidget {
  const AdaptiveLoading({
    Key? key,
    this.strokeWidth = 3,
    this.semanticLabel,
    this.backgroundColor,
    this.activeColor,
    this.size,
    this.backwards = false,
  }) : super(key: key);

  final double strokeWidth;
  final String? semanticLabel;
  final Color? backgroundColor;
  final Color? activeColor;
  final bool backwards;
  final double? size;

  @override
  AdaptiveLoadingState createState() => AdaptiveLoadingState();

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('strokeWidth', strokeWidth));
  }
}

class AdaptiveLoadingState extends State<AdaptiveLoading>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  double d1 = 0, d2 = 0, lowSpeed = 8, highSpeed = 12;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      duration: const Duration(seconds: 3),
      vsync: this,
    );
    _controller.repeat();
  }

  @override
  void didUpdateWidget(AdaptiveLoading oldWidget) {
    super.didUpdateWidget(oldWidget);
    _controller.repeat();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ColorScheme style = Theme.of(context).colorScheme;
    return Container(
      constraints: BoxConstraints(
        minWidth: widget.size ?? 36,
        minHeight: widget.size ?? 36,
      ),
      child: Semantics(
        label: widget.semanticLabel,
        child: AnimatedBuilder(
          animation: _controller,
          builder: (BuildContext context, Widget? value) => Platform.isMacOS
              ? CupertinoActivityIndicator(
                  radius: widget.size ?? 20,
                  animating: true,
                )
              : CustomPaint(
                  painter: WinLoading(
                    backgroundColor:
                        widget.backgroundColor ?? Colors.transparent,
                    color: widget.activeColor ?? style.secondary,
                    strokeWidth: widget.strokeWidth,
                    d1: d1,
                    d2: d2,
                    lowSpeed: lowSpeed,
                    highSpeed: highSpeed,
                    onUpdate: (dynamic v) {
                      d1 = v[0]!;
                      d2 = v[1]!;
                      lowSpeed = v[2]!;
                      highSpeed = v[3]!;
                    },
                    backwards: widget.backwards,
                  ),
                ),
        ),
      ),
    );
  }
}

class WinLoading extends CustomPainter {
  final Color color;
  final Color backgroundColor;
  final double strokeWidth;
  final double d1, d2, lowSpeed, highSpeed;
  final ValueChanged onUpdate;
  final bool backwards;

  const WinLoading({
    required this.color,
    required this.backgroundColor,
    required this.strokeWidth,
    required this.d1,
    required this.d2,
    required this.lowSpeed,
    required this.highSpeed,
    required this.onUpdate,
    required this.backwards,
  });

  static const double _startAngle = -math.pi / 2.0;
  static const double _deg2Rad = (2 * math.pi) / 360;

  @override
  void paint(Canvas canvas, Size size) {
    // Background line
    canvas.drawArc(
      Offset.zero & size,
      _startAngle,
      100,
      false,
      Paint()
        ..color = backgroundColor
        ..style = PaintingStyle.stroke
        ..strokeWidth = strokeWidth,
    );
    Paint paint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.round
      ..style = PaintingStyle.stroke;
    double d1 = this.d1, d2 = this.d2, speed1 = lowSpeed, speed2 = highSpeed;

    void drawArc() {
      canvas.drawArc(
        Offset.zero & size,
        (backwards ? (90 - d2) : (90 + d2)) * _deg2Rad,
        ((d2 - d1) * _deg2Rad),
        false,
        paint,
      );
    }

    void update() {
      d1 += speed1;
      d2 += speed2;
      if (d1 > 360 && d2 > 360) {
        d1 -= 360;
        d2 -= 360;
      }
      if ((d1 - d2).abs() >= 180) {
        double s1 = speed1;
        speed1 = speed2;
        speed2 = s1;
      }
      // update the values changed above
      onUpdate(<dynamic>[d1, d2, speed1, speed2]);
    }

    update();
    if (d1 == d2 && d1 % 360 == 0) return;
    drawArc();
  }

  @override
  bool shouldRepaint(WinLoading oldDelegate) => true;

  @override
  bool shouldRebuildSemantics(WinLoading oldDelegate) => false;
}
```

</details>

<details>
  <summary>Logs</summary>

`flutter run` [Logs](https://gist.githubusercontent.com/yahu1031/eea413c8d042095672eaac17258431b6/raw/d6395cb6ea3f76ae5f560b7ce6c83a8fb52547af/flutter_logs.log)

```
minnu@MrMinnus-MacBook-Air ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-arm, locale
    en-IN)
    • Flutter version 3.3.1 on channel stable at
      /Users/minnu/Development/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 4f9d92fbbd (4 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/minnu/Development/android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/minnu/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526
      /Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/minnu/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 12.5.1 21G83 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2022-09-12 10:51
Hi @yahu1031, thanks for filing the issue. But I can not reproduce the issue on the latest `stable` and `master` channels.
When clicking on `Hello World` button, the mouse didn't move and the dialog displayed normally without blur.

_Note: I've updated your sample code here in this comment due to a context error when running the app (fixed by wrapping `TextButton` by a `Builder`)_

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/189626718-106d7134-d472-4f3e-80e6-1aa5b114072d.mov

</details>

<details>
<summary>Sample code</summary>

```dart
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:math' as math;

void main() {
  runApp(
    const MyApp(),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(body: Center(
        child: Builder(builder: (context) {
          return TextButton(
            child: const Text('Hello World'),
            onPressed: () {
              showDialog<AlertDialog>(
                context: context,
                builder: (BuildContext context) {
                  return const SystemRequirements();
                },
              );
            },
          );
        }),
      )),
    );
  }
}

class SystemRequirements extends StatefulWidget {
  const SystemRequirements({
    Key? key,
  }) : super(key: key);

  @override
  State<SystemRequirements> createState() => _SystemRequirementsState();
}

class _SystemRequirementsState extends State<SystemRequirements> {
  bool isChecking = false;
  String? logDir;

  Future<void> init() async {
    logDir = (await getApplicationSupportDirectory()).path;
    setState(() {});
  }

  @override
  void initState() {
    init();
    super.initState();
  }

  @override
  void setState(VoidCallback fn) {
    if (mounted) {
      super.setState(fn);
    }
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      width: 500,
      child: AlertDialog(
        backgroundColor: Colors.white,
        title: const Text(
          'System Requirements',
          style: TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 20,
          ),
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            const Text(
              'Please make sure you have the following requirements before installing the app:',
              style: TextStyle(
                fontSize: 14,
              ),
            ),
            if (!Platform.isLinux)
              BulletPoint(
                isChecking: isChecking,
                content:
                    '${Platform.operatingSystem} version must be ${Platform.isWindows ? '7 SP!' : '10.7'} or later.',
                bulletColor: Colors.red,
              ),
            BulletPoint(
              isChecking: isChecking,
              content:
                  '${Platform.operatingSystemVersion.split('" ')[0].replaceAll('"', '')} Architecture must be x64 (x86-64)',
              bulletColor: Colors.red,
            ),
            BulletPoint(
              isChecking: isChecking,
              content: 'Disk space of at least 2GB',
              bulletColor: Colors.red,
            ),
            BulletPoint(
              isChecking: isChecking,
              content:
                  'Other tools like ${Platform.isWindows ? 'Windows Powershell 5.0(or new), Git for windows' : Platform.isMacOS ? 'xCode, git' : 'bash, curl, file, git, mkdir, rm, unzip, which,\n xz-utils, zip, libglu1-mesa/mesa-libGLU'}, Java(11 recommended).',
              bulletColor: Colors.red,
            ),
            isChecking
                ? const SizedBox(height: 69)
                : Padding(
                    padding: const EdgeInsets.symmetric(vertical: 18.0),
                    child: TextButton(
                      style: ButtonStyle(
                        backgroundColor: MaterialStateProperty.all<Color>(
                          Colors.red,
                        ),
                      ),
                      onPressed: () async {
                        setState(() {
                          isChecking = true;
                        });
                        setState(() {
                          isChecking = false;
                        });
                      },
                      child: const Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Text(
                          'Check',
                          style: TextStyle(
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ),
            if (kDebugMode)
              Center(
                child: logDir == null
                    ? AdaptiveLoading(
                        size: Platform.isMacOS ? 5 : 10,
                      )
                    : Text(
                        'Your logs files are stored here\n$logDir',
                        textAlign: TextAlign.center,
                        style: const TextStyle(
                          fontSize: 10,
                        ),
                      ),
              ),
          ],
        ),
      ),
    );
  }
}

class BulletPoint extends StatelessWidget {
  final String? content;
  final TextStyle? contentStyle;
  final Color? bulletColor;
  final bool isChecking;

  const BulletPoint({
    Key? key,
    required this.content,
    required this.isChecking,
    this.contentStyle,
    this.bulletColor,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10.0, horizontal: 17.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 3.5),
            child: isChecking
                ? AdaptiveLoading(
                    size: Platform.isMacOS ? 5 : 10,
                    strokeWidth: 1.5,
                  )
                : CustomPaint(
                    size: const Size(10, 10),
                    painter: CircleBullet(bulletColor ?? Colors.black),
                  ),
          ),
          Text(
            content!,
            style: contentStyle ??
                const TextStyle(
                  fontSize: 12,
                ),
          ),
        ],
      ),
    );
  }
}

class CircleBullet extends CustomPainter {
  CircleBullet(this.color);

  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    Paint paint0Fill = Paint()..style = PaintingStyle.fill;
    paint0Fill.color = color.withOpacity(1.0);
    canvas.drawCircle(Offset(size.width * 0.5, size.height * 0.5),
        size.width * 0.5, paint0Fill);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}

class AdaptiveLoading extends StatefulWidget {
  const AdaptiveLoading({
    Key? key,
    this.strokeWidth = 3,
    this.semanticLabel,
    this.backgroundColor,
    this.activeColor,
    this.size,
    this.backwards = false,
  }) : super(key: key);

  final double strokeWidth;
  final String? semanticLabel;
  final Color? backgroundColor;
  final Color? activeColor;
  final bool backwards;
  final double? size;

  @override
  AdaptiveLoadingState createState() => AdaptiveLoadingState();

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('strokeWidth', strokeWidth));
  }
}

class AdaptiveLoadingState extends State<AdaptiveLoading>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  double d1 = 0, d2 = 0, lowSpeed = 8, highSpeed = 12;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      duration: const Duration(seconds: 3),
      vsync: this,
    );
    _controller.repeat();
  }

  @override
  void didUpdateWidget(AdaptiveLoading oldWidget) {
    super.didUpdateWidget(oldWidget);
    _controller.repeat();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ColorScheme style = Theme.of(context).colorScheme;
    return Container(
      constraints: BoxConstraints(
        minWidth: widget.size ?? 36,
        minHeight: widget.size ?? 36,
      ),
      child: Semantics(
        label: widget.semanticLabel,
        child: AnimatedBuilder(
          animation: _controller,
          builder: (BuildContext context, Widget? value) => Platform.isMacOS
              ? CupertinoActivityIndicator(
                  radius: widget.size ?? 20,
                  animating: true,
                )
              : CustomPaint(
                  painter: WinLoading(
                    backgroundColor:
                        widget.backgroundColor ?? Colors.transparent,
                    color: widget.activeColor ?? style.secondary,
                    strokeWidth: widget.strokeWidth,
                    d1: d1,
                    d2: d2,
                    lowSpeed: lowSpeed,
                    highSpeed: highSpeed,
                    onUpdate: (dynamic v) {
                      d1 = v[0]!;
                      d2 = v[1]!;
                      lowSpeed = v[2]!;
                      highSpeed = v[3]!;
                    },
                    backwards: widget.backwards,
                  ),
                ),
        ),
      ),
    );
  }
}

class WinLoading extends CustomPainter {
  final Color color;
  final Color backgroundColor;
  final double strokeWidth;
  final double d1, d2, lowSpeed, highSpeed;
  final ValueChanged onUpdate;
  final bool backwards;

  const WinLoading({
    required this.color,
    required this.backgroundColor,
    required this.strokeWidth,
    required this.d1,
    required this.d2,
    required this.lowSpeed,
    required this.highSpeed,
    required this.onUpdate,
    required this.backwards,
  });

  static const double _startAngle = -math.pi / 2.0;
  static const double _deg2Rad = (2 * math.pi) / 360;

  @override
  void paint(Canvas canvas, Size size) {
    // Background line
    canvas.drawArc(
      Offset.zero & size,
      _startAngle,
      100,
      false,
      Paint()
        ..color = backgroundColor
        ..style = PaintingStyle.stroke
        ..strokeWidth = strokeWidth,
    );
    Paint paint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.round
      ..style = PaintingStyle.stroke;
    double d1 = this.d1, d2 = this.d2, speed1 = lowSpeed, speed2 = highSpeed;

    void drawArc() {
      canvas.drawArc(
        Offset.zero & size,
        (backwards ? (90 - d2) : (90 + d2)) * _deg2Rad,
        ((d2 - d1) * _deg2Rad),
        false,
        paint,
      );
    }

    void update() {
      d1 += speed1;
      d2 += speed2;
      if (d1 > 360 && d2 > 360) {
        d1 -= 360;
        d2 -= 360;
      }
      if ((d1 - d2).abs() >= 180) {
        double s1 = speed1;
        speed1 = speed2;
        speed2 = s1;
      }
      // update the values changed above
      onUpdate(<dynamic>[d1, d2, speed1, speed2]);
    }

    update();
    if (d1 == d2 && d1 % 360 == 0) return;
    drawArc();
  }

  @override
  bool shouldRepaint(WinLoading oldDelegate) => true;

  @override
  bool shouldRebuildSemantics(WinLoading oldDelegate) => false;
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (31 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.192, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.192 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4930444f4a (2 days ago), 2022-09-09 21:58:23 -0400
    • Engine revision f72107f457
    • Dart version 2.19.0 (build 2.19.0-183.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

This issue could be related to #110738 by someone could reproduce it in case using `AlertDialog`.
And look at https://github.com/flutter/flutter/issues/110738#issuecomment-1241714590, it seems to have been fixed on master channel. So, please try running app again on the latest master channel and confirm if this issue is fixed. Thanks!

**Closed** 2022-09-12 11:02 UTC
Labels: waiting for customer response, in triage
