### ISSUE TITLE
[`DataTable`]  Unable to center the label of a DataColumn without side effects

### ISSUE THREAD

**Issue by wer-mathurin** [flutter/flutter#143340] opened 2024-02-12 22:56 UTC
### Steps to reproduce

Use the provided code to see the outcome.
As you will see, the label of the first column is not center.

After inspecting the source code this is cause by:
 
```
 label = Row(   <==============
      textDirection: numeric ? TextDirection.rtl : null,
      children: <Widget>[
        label, 
        if (onSort != null)
          ...<Widget>[
            _SortArrow(
              visible: sorted,
              up: sorted ? ascending : null,
              duration: _sortArrowAnimationDuration,
            ),
            const SizedBox(width: _sortArrowPadding),
          ],
      ],
    );
```

The label place inside a row, so the Center or Align have no effect.
But the simple solution like wrapping the label in a Flexible and a side effect of moving the sort arrow to the end of the cell...

So there is not easy solution(from my perspective) by not breaking the API of DataColumn.
One possible solution can be:

```
 label = Row(
      textDirection: numeric ? TextDirection.rtl : null,
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Flexible(child: label),
        if (onSort != null) ...<Widget>[
          customArrows ??
              _SortArrow(
                visible: sorted,
                up: sorted ? ascending : null,
                duration: sortArrowAnimationDuration,
                sortArrowIcon: sortArrowIcon,
              ),
          const SizedBox(width: _sortArrowPadding)
        ]
      ],
    );

    label = isCentered
        ? Row(
            textDirection: numeric ? TextDirection.rtl : null,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (onSort != null) ...<Widget>[
                const SizedBox(width: _sortArrowPadding),
                const SizedBox(width: _SortArrowState._arrowIconSize),
              ],
              Flexible(child: label),
            ],
          )
        : label;
```

But probably passing an Alignment can do the trick as well and be more generic.  This is not perfect, but at least there will be a way to center the heading cell, and this is better than now :-)

### Expected results

When using a Center or Align(center) widget in the heading cell, have the cell...center :-)
Or another mechanism to make it happen.

### Actual results

The widget is not center in the heading cell.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final source = _Source(items: Data.data);

  @override
  Widget build(BuildContext context) {
    final themeData = Theme.of(context).copyWith(
        dataTableTheme: const DataTableThemeData(
      columnSpacing: 0,
      horizontalMargin: 0,
      dividerThickness: 0,
      checkboxHorizontalMargin: 0,
    ));

    return Theme(
      data: themeData,
      child: PaginatedDataTable(
        columns: [
          DataColumn(
            label: const Center(
              child: Text(
                'Centered',
                textAlign: TextAlign.center,
              ),
            ),
            // numeric: true,
            onSort: (columnIndex, ascending) => setState(() {
              source.sort(ascending);
            }),
          ),
          const DataColumn(
            label: Text(
              'Second',
              textAlign: TextAlign.center,
            ),
          ),
        ],
        sortColumnIndex: 0,
        sortAscending: source.ascending,
        source: source,
      ),
    );
  }
}

class Data {
  static List<String> get data => List.generate(100, (index) => '$index');
}

class _Source extends DataTableSource {
  _Source({
    required this.items,
  });

  final List<String> items;
  bool ascending = false;

  @override
  DataRow? getRow(int index) {
    return DataRow.byIndex(index: index, cells: [
      DataCell(Center(child: Text(items[index]))),
      DataCell(Text(items[index])),
    ]);
  }

  void sort(bool ascending) {
    this.ascending = ascending;

    items.sort((a, b) => ascending ? a.compareTo(b) : b.compareTo(a));
    notifyListeners();
  }

  @override
  bool get isRowCountApproximate => false;

  @override
  int get rowCount => items.length;

  @override
  int get selectedRowCount => 0;
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.1)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by dam-ease** [comment] 2024-02-13 08:41
Thanks for filing this @wer-mathurin.
I can reproduce this on the latest `master` and `stable` channels.
This is similar to https://github.com/flutter/flutter/issues/40526 which was closed as fixed by https://github.com/flutter/flutter/pull/51667 by OP.

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.16.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 Pro (mobile)      • 79E44FCE-BEA4-4C4B-9C1C-EFBD9964E172 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.20.0-4.0.pre.62, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.20.0-4.0.pre.62 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 950e0025c4 (4 hours ago), 2024-02-09 00:38:30 -0500
    • Engine revision f6dddb257a
    • Dart version 3.4.0 (build 3.4.0-116.0.dev)
    • DevTools version 2.32.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)      • 00008110-001964480AE1801E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by TahaTesser** [comment] 2024-02-22 16:06
Looked into the issue now, it looks like this is working as intended and is documented in [DataColumn label](https://main-api.flutter.dev/flutter/material/DataColumn/label.html). This is also covered by a framework test. 


As the documentation suggest use `Flexible` to control the label's content flexes.  


### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Material(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: DataTable(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(16),
              border: Border.all(
                color: Theme.of(context).colorScheme.primary,
                width: 2,
              ),
            ),
            onSelectAll: (value) {},
            columns: <DataColumn>[
              DataColumn(
                onSort: (columnIndex, ascending) {},
                label: const Flexible(child: Center(child: Text('Column A'))),
              ),
              DataColumn(
                onSort: (columnIndex, ascending) {},
                label: const Flexible(child: Center(child: Text('Column B'))),
              ),
            ],
            rows: const <DataRow>[],
          ),
        ),
      ),
    );
  }
}
```

</details>


### Before

![Screenshot 2024-02-22 at 18 04 20](https://github.com/flutter/flutter/assets/48603081/73eec9e3-26e8-47aa-b219-66a792b8e458)


### After
![Screenshot 2024-02-22 at 18 03 53](https://github.com/flutter/flutter/assets/48603081/76906538-3f2a-4d73-8473-82c92c8c4064)

**Comment by wer-mathurin** [comment] 2024-02-22 17:22
@TahaTesser : I forgot to mention, without side effects !
When using the Flexible widget this cause the sorting arrow to be position at the end of the header, and this is not compliant to the material specification and this can be very confusing as well when there is not border and if the next header is not center!

<img width="563" alt="image" src="https://github.com/flutter/flutter/assets/39314023/a7273408-53e3-4dab-9612-fe915f5ccab9">

So I think we **can't** close this ticket cause of the side effect using the Flexible.  We can change the title indeed :-)

**Closed** 2024-04-01 09:42 UTC
Labels: framework, f: material design, has reproducible steps, P2, team-design, triaged-design, found in release: 3.16, found in release: 3.20
