### ISSUE TITLE
When I type something in the textfield, sometimes it get the following error

### ISSUE THREAD

**Issue by lrthorhammer007** [flutter/flutter#66562] opened 2020-09-24 15:25 UTC
```
════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 78 pos 16: 'keys.isNotEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      new KeySet.fromSet 
package:flutter/…/widgets/shortcuts.dart:78
#3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
#4      new LogicalKeySet.fromSet 
package:flutter/…/widgets/shortcuts.dart:187
#5      ShortcutManager.handleKeypress 
package:flutter/…/widgets/shortcuts.dart:321
#6      _ShortcutsState._handleOnKey 
package:flutter/…/widgets/shortcuts.dart:490
...
════════════════════════════════════════════════════════════════════════════════
```

**Comment by TahaTesser** [comment] 2020-09-24 15:27
Hi @lrthorhammer007 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by lrthorhammer007** [comment] 2020-09-24 16:06
> Hi @lrthorhammer007
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you

I have put the code in the attachment. It will show how the problem occurs.
[DEMO.zip](https://github.com/flutter/flutter/files/5277499/DEMO.zip)

**Comment by TahaTesser** [comment] 2020-09-25 06:58
Hi @lrthorhammer007 
Can you please try Android Emulator or physical to reproduce this issue?  Looks like you're running on gaming emulator which is not supported by Flutter. Also please upgrade to the latest `stable 1.20.4` 


Running your project on API 29 Android Studio emulator, no issues


<details> 
<summary>logs</summary> 

```bash
Launching lib\main.dart on Android SDK built for x86 in debug mode...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Connecting to VM Service at ws://127.0.0.1:53471/yMffXII7jZI=/ws
D/EGL_emulation(15759): eglMakeCurrent: 0xd795f0c0: ver 2 0 (tinfo 0xd797f4b0)
D/eglCodecCommon(15759): setVertexArrayObject: set vao to 0 (0) 1 0
W/IInputConnectionWrapper(15759): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15759): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15759): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(15759): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15759): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15759): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15759): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15759): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(15759): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15759): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15759): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15759): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15759): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15759): getTextAfterCursor on inactive InputConnection

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.4 at C:\Code\flutter_stable
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

</details>

**Comment by lrthorhammer007** [comment] 2020-09-25 07:03
> Hi @lrthorhammer007
> Can you please try Android Emulator or physical to reproduce this issue? Looks like you're running on gaming emulator which is not supported by Flutter. Also please upgrade to the latest `stable 1.20.4`
> 
> Running your project on API 29 Android Studio emulator, no issues
> 
> logs
> flutter doctor -v

Okay, I'm going to run it on the real machine

**Comment by pedromassangocode** [comment] 2020-10-23 11:12
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-23 11:12 UTC
Labels: a: text input, f: material design, framework, in triage
