### ISSUE TITLE
TextField always beeps when pressing alt+any key in Windows

### ISSUE THREAD

**Issue by cjng96** [flutter/flutter#111554] opened 2022-09-14 13:11 UTC
My program is using the Alt+S key as a shortcut while typing TextField. Every time presses the Alt+any key(including S), it beeps.

I can find related issue at https://github.com/flutter/flutter/issues/74287.

However, the beep does not disappear when wrapped with a Focus widget. :(

All I want is,
1. Prevents beep sound when pressing Alt+S(including other key) key
2. The TextField inside the Focus widget works well.

The sample code below does not prevent beeping when pressing the alt+S key.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Flutter Demo', theme: ThemeData(primarySwatch: Colors.blue), home: const MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController inputCon = TextEditingController();
  FocusNode focus = FocusNode();

  @override
  Widget build(BuildContext context) {
    Widget input = TextField(controller: inputCon, autofocus: true, focusNode: focus);

    // https://github.com/flutter/flutter/issues/74287
    input = Focus(
      child: input,
      onKeyEvent: (node, event) {
        if (event.logicalKey == LogicalKeyboardKey.keyS) {
          return KeyEventResult.handled;
        }
        return KeyEventResult.ignored;
      },
    );

    Widget body = Scaffold(
      appBar: AppBar(title: Text('demo')),
      body: Center(child: input),
    );

    return body;
  }
}
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1889], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] VS Code (version 1.71.1)
[✓] VS Code (version 1.67.0-insider)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment] 2022-09-15 04:03
Hi @cjng96, thanks for filing the issue. I can reproduce this issue on the latest `stable` and `master` channels.
But it always dings a beep sound when pressing `Alt` with other keys such as `a`, `b`, `c` (not only `s` key). Can you confirm this and update description corresponding to this if you have the same behavior?

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/190310834-72f5f767-38d0-4a7f-afa5-63c586c89c6e.mp4

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19043.1889], locale en-US)
    • Flutter version 3.3.2 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (14 hours ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[√] Flutter (Channel master, 3.4.0-19.0.pre.270, on Microsoft Windows [Version 10.0.19043.1889], locale en-US)
    • Flutter version 3.4.0-19.0.pre.270 on channel master at C:\WIP\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c4c1b0b0b7 (2 hours ago), 2022-09-14 21:22:29 -0400
    • Engine revision 3a49977f8b
    • Dart version 2.19.0 (build 2.19.0-199.0.dev)
    • DevTools version 2.17.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by cjng96** [comment] 2022-09-15 04:18
Thank you for the reply. 

Correct, event if I wrap the focus widget and return the KeyEventResult.handled value, the beep always occurs on other keys. :{

**Comment by huycozy** [comment] 2022-09-15 07:16
@cjng96 Thanks for the update. But I forgot to mention the remaining part about `TextField can't receive the S key`.
I think it worked as intended when you had this code:
```
if (event.logicalKey == LogicalKeyboardKey.keyS) {
  return KeyEventResult.handled;
}
```
https://github.com/flutter/flutter/blob/2262892e3b7c439a9dcf0f9ca600ae9d305ef29d/packages/flutter/lib/src/widgets/focus_manager.dart#L40-L48

**Comment by cjng96** [comment] 2022-09-15 08:05
Thank you. I didn't know that TextField don't receive the key although the Focus widget was the parent of the TextField widget. 

If so, wrapping it with the Focus widget mentioned on https://github.com/flutter/flutter/issues/74287 is unfortunately not a solution to prevent a beep when using the text input widget.

It is difficult and unnatural to filter the Alt Key combination because there is no Alt Key press flag in the Key Event of the Focus widget. 

Is there any other formal solution other than the Focus widget that is currently not working to prevent beeps?  (T_T)

**Comment by huycozy** [comment] 2022-09-15 08:53
Hi @cjng96, what I mean at https://github.com/flutter/flutter/issues/111554#issuecomment-1247680782 is only about your code implemented for `TextField can't receive the S key`, while the sound issue still persists as the comments above. 
Labeling the issue to get more insights from the team. Thank you!

**Comment by gspencergoog** [comment] 2022-09-15 18:08
You should probably look at the `Shortcuts` widget, or perhaps `CallbackShortcuts` in order to implement things like this.  The `onKeyEvent` API is a lower-level API that is actually getting in your way here.

Things you might want to read about:
[Shortcuts](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html)
[ShortcutActivator](https://api.flutter.dev/flutter/widgets/ShortcutActivator-class.html)
[CallbackShortcuts](https://api.flutter.dev/flutter/widgets/CallbackShortcuts-class.html)

**Comment by cjng96** [comment] 2022-09-16 02:11
@gspencergoog Oh.. Thank you. I didn't know about CallbackShortcuts widget.

**Comment by justinmc** [comment] 2022-09-16 16:57
Seems like there is nothing to fix here, so I'll go ahead and close this issue.  @cjng96 let me know if that's not right or your problem isn't solved with CallbackShortcuts etc.

**Closed by justinmc** 2022-09-16 16:57 UTC
Labels: a: text input, framework, platform-windows, a: desktop, f: focus, has reproducible steps, P4, found in release: 3.3, found in release: 3.4

**Comment by cjng96** [comment] 2022-09-17 02:20
The issue is not resolved because it is related to a beep that occurs whenever the alt+any key is pressed.

I was hooking the key using the RawKeyListener, and it beeps.

I found on https://github.com/flutter/flutter/issues/74287 that a Focus widget with a a KeyEventResult.handled value can prevent beeping. but it doesn't work now.

Also, the CallbackShortcuts widget that doesn't have a return value cannot prevent a beep.
