### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by meciks** [flutter/flutter#97104] opened 2022-01-23 20:31 UTC
It would be nice to use dart and flutter on OpenBSD.
Can someone add obsd support?

**Comment by stuartmorgan** [comment] 2022-01-24 03:17
This is a duplicate of https://github.com/dart-lang/sdk/issues/10260, since Flutter cannot support an OS that Dart doesn't support.

**Closed by stuartmorgan** 2022-01-24 03:17 UTC
