### ISSUE TITLE
docs are incorrect on how to install rosetta on mac

### ISSUE THREAD

**Issue by dwilbur-sutrobio** [flutter/flutter#108834] opened 2022-08-02 20:45 UTC
$ sudo softwareupdate --install-rosetta --agree-to-license

has errors and then says in installed... leaving one thinking it failed. you can see verification on this at:
https://discussions.apple.com/thread/252516380?page=1
NOTE: the solved is not correct as you can see in later posts

either the docs need to state that the error is ok... which i don't think it is because the rosetta updater fails at this point.

or maybe suggest the following:

the "correct" way to install it is to have an intel app try to run. which will cause rosetta to be installed...
https://support.apple.com/en-gb/HT211861

imo, apple should have, better way to install this via say xcode... maybe it does i just don't use it...

**Comment by exaby73** [comment] 2022-08-04 06:57
Hello. Thank you for filing this issue. Labelling it for further insights from the team

**Comment by darshankawar** [comment] 2022-09-21 13:09
Closing this as a duplicate of https://github.com/flutter/flutter/issues/88012

**Closed by darshankawar** 2022-09-21 13:09 UTC
Labels: platform-mac, a: first hour, documentation, arch: m1
