### ISSUE TITLE
google_maps_flutter PlatformException(create_failed, can't create a view on a headless engine, null)

### ISSUE THREAD

**Issue by xNoEndx** [flutter/flutter#36310] opened 2019-07-16 21:49 UTC
Hi everyone, this issue appeared with no changes in code. I was able to use google maps normally, however I started to get below error. Google map will stay white. However, when I run the app again it works fine. Only The first run that has this error.

Thanks

```
GoogleMap(
              mapType: MapType.hybrid,
              initialCameraPosition: _initial_pos,
              myLocationEnabled: true,
              myLocationButtonEnabled: false,
              scrollGesturesEnabled: true,
              zoomGesturesEnabled: true,
              markers: markers,
              onCameraMove: (CameraPosition pos) {
                setState(() {
                  _current_location = pos.target;
                });
              }, // _createMarker(),
              onMapCreated: (GoogleMapController controller) {
                _controller = controller;
              },
            ),
```

```
VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(create_failed, can't create a view on a headless engine, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:167:41)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:499:71)
<asynchronous suspension>
```
```
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G7024, locale en-BH)
 
Checking Android licenses is taking an unexpectedly long time...⣟^C
Ahmeds-iMac:take_it ahmedbuchery$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G7024, locale en-BH)
    • Flutter version 1.7.8+hotfix.3 at /Applications/flutter
    • Framework revision b712a172f9 (7 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ahmedbuchery/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (3 available)
    • ONEPLUS A5000   • fda25b09                             • android-arm64 • Android 9 (API 28)
    • Ahmed’s iPhoneX • 00008020-000C70C23A90003A            • ios           • iOS 13.0
    • iPhone XR       • 2106863E-206C-47F6-9193-F1FD2FA936AE • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-1 (simulator)

• No issues found!

```

**Comment by xNoEndx** [comment] 2019-07-17 16:49
Weird Solution is the a had the zoom as zero before, changed it to 1 then 2, however still same issue. Then tried zoom level 3 and it is fine now?!

Thanks

**Comment by Jumpbotron** [comment] 2019-09-12 05:23
Hi, can you please explain better how you solved it?? Having the same issue for days

**Comment by xNoEndx** [comment] 2019-09-12 05:30
Hi Jumpbotron,

As mentioned above, I have just changed the initial camera zoom level from level to level 3. Apparently it will crash when the map is smaller than the screen.

**Comment by abumoallim** [comment] 2019-11-02 13:24
Any updates on this? I am still getting the same error. Any workaround for now ? My zoom is already 12 by default.

**Comment by Jumpbotron** [comment] 2019-11-03 16:25
> Any updates on this? I am still getting the same error. Any workaround for now ? My zoom is already 12 by default.

Hi, did you checked your google maps key and on which container are you putting it?

**Comment by salehahmedZ** [comment] 2019-11-09 06:34
I was facing the same issue and managed to solve it. 
It turns out that I was trying to show the map while asking user for Notification permission or Location permission. 

The solution is to hide the map or show a loader spinner until the user answers the permission dialogs.

**Comment by nuzelac** [comment] 2019-11-09 10:01
I'm wondering if it's some kind of race condition regardless of permissions, so waiting for permissions buys some time before map is rendered.

**Comment by Navil** [comment] 2020-03-04 13:29
> I was facing the same issue and managed to solve it.
> It turns out that I was trying to show the map while asking user for Notification permission or Location permission.
> 
> The solution is to hide the map or show a loader spinner until the user answers the permission dialogs.

Could you elaborate on how you achieved this? DId you put the logic for checking the permission into the same Widget which renders the map?

**Comment by nuzelac** [comment] 2020-03-06 17:39
I have a FutureBuilder that waits for permission dialog result before rendering map, but this did not manage to fix the issue. Does anyone else have any other solutions?

**Comment by theochampion** [comment] 2020-04-03 19:37
Any updates on this ? I'm getting the same error on the last version of the plugin

**Comment by ricnaaru** [comment] 2020-04-08 08:26
this happens when the app is requesting for any permission in ios, and the flutter NativeView try to render itself. so as long as the permission dialog hanging there, i think it's considered to be "headless". what you can do to fix this is basically wait until the permission request is finished, and then try to render / call the build NativeView (whatever it is, could be WebView or GoogleMap)

although this case is relatively hard to reproduce, and considered to be rare occasion (need to have ios permission request script [calling the GPS location / Notification received thus will prompt notification permission request / start motion activity update], and render the NativeView at the same time)

**Comment by nuzelac** [comment] 2020-04-08 09:46
@ricnaaru sorry but this is not a rare occasion and not at all hard to reproduce. I even await permission confirmation before rendering (I could very easily reproduce before adding this) and it still keeps happening.
<img width="1151" alt="Issues - poop-map - Sentry 2020-04-08 11-42-33" src="https://user-images.githubusercontent.com/195299/78769796-14d45c80-798e-11ea-9b77-a53e262034f3.png">

**Comment by yukitaka13-1110** [comment] 2020-04-20 01:19
Any updates on this? I am still getting the same error at the issue @LichKing-2234 referenced.

**Comment by jl-gogovapps** [comment] 2020-05-16 22:20
I'm facing a similar issue, and have a couple things to add. 
I've added a AppLifecycleState hook, so i can tell when the app is looking for permissions to be accepted, because the app becomes inactive.  I've used `xcrun privacy`, available in version 50, and this resolves my issue on my laptop, with a headed simulator. 

However, we have an OSX CI/CD machine where I'm trying to run our tests, and I'm still facing issues where the `onMapCreated` call is never invoked.  I've gotten past the permission issues, i think, but still, not sure whats going on in this headless environment.  I suspect it's related to this problem.

This is being experienced in the context of flutter driver, as demonstrated below:

```
flutter build ios --debug --no-codesign --target=test_driver/app.dart
xcrun simctl install $UDID ./build/ios/iphoneos/Runner.app
xcrun simctl privacy $UDID grant location-always com.xxx.yyyy
flutter driver --target=test_driver/app.dart --driver=test_driver/some_test.dart --no-build
```

I'm building and installing the app, then setting the permissions for Location, then running the tests.  If i run the privacy command before installing the app, or don't run it at all, I'm able to observe my app ask for permissions based on the AppLifecycleState hooks

**Comment by seeuli** [comment] 2020-07-08 04:01
I also encountered this problem.

Delaying the creation of UIKitView a few seconds when initializing the Widget, and then frequently switching between the front and background can be reproduced steadily. You will encounter this.

demo：https://github.com/seeuli/my_app/tree/feature/platform_exception
steps：
1. click button "PlatformView"
2. Frequent switching between front and background

flutter doctor -v
```
[✓] Flutter (Channel unknown, v1.17.1, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/liyf/.flutter_sdk
    • Framework revision f7a6a7906b (8 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/liyf/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/liyf/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    ! CocoaPods 1.6.2 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)

```

**Comment by seeuli** [comment] 2020-07-08 05:39
This exception usually occurs when the PlatformView is created for the second time and later.

**Comment by seeuli** [comment] 2020-07-28 12:29
> This exception usually occurs when the PlatformView is created for the second time and later.

@jason-simmons @jmagman @gspencergoog

**Comment by chinmaygarde** [comment] 2020-08-03 18:21
Triage: This looks like a race in the plugin lifecycle when the engine thinks that the app is still in the background by the time the plugin needs to be setup.

**Comment by chinmaygarde** [comment] 2020-08-31 18:05
cc @cyanglaz for triage.

**Comment by cyanglaz** [comment] 2020-09-09 17:19
This should be fixed by https://github.com/flutter/engine/commit/3d104f43649d333492dfa792968c8a09af93a84c#diff-77cd0412ef34958c72d156d4b818b7d7 and https://github.com/flutter/engine/commit/1c13abaab120d8d2d4c07e5b5fc75100f56a89e2#diff-77cd0412ef34958c72d156d4b818b7d7

I will tentatively close the issue. If anyone finds it not fixed, please ping me here and I will re-open the issue and further investigate.

**Closed by cyanglaz** 2020-09-09 17:19 UTC
Labels: P3, customer: crowd, engine, p: first party, p: maps, plugin, severe: crash
