### ISSUE TITLE
[Impeller] Text widget is rendered pixelated on iPhone XR when wrapped with Opacity widget.

### ISSUE THREAD

**Issue by talp-flytrex** [flutter/flutter#127386] opened 2023-05-23 12:38 UTC
### Steps to reproduce

`Text` widget is rendered pixelated on iPhone XR when using SF Pro text font with -0.5 `letterSpacing` and `Opacity` widget.
See code sample below.

### Expected results

`Text` widget should be rendered normally when wrapped with `Opacity` widget.

### Actual results

`Text` widget is rendered pixelated when wrapped with `Opacity` widget.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) => const MaterialApp(home: HomePage());
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  static const _textStyle = TextStyle(
    fontFamily: "SFProText", // <<<<<<<< custom font
    fontSize: 24,
    fontWeight: FontWeight.w400,
    letterSpacing: -0.5, // <<<<<<<< custom letter spacing
  );

  @override
  Widget build(BuildContext context) => const Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Opacity(
                opacity: 0.5,
                child: Text("Pixelated text", style: _textStyle),
              ),
              Text("Normal text", style: _textStyle),
            ],
          ),
        ),
      );
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots</summary>

![52833](https://github.com/flutter/flutter/assets/93519223/ceff2f62-af0d-409d-b83d-6b077288596b)
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-x64, locale en-IL)
    • Flutter version 3.10.0 on channel stable at /Users/xxx/fvm/versions/3.10.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone XR (mobile) • 00008020-000931213CFA002E • ios            • iOS 15.7.1 19H117
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by talp-flytrex** [comment] 2023-05-23 12:40
![52833](https://github.com/flutter/flutter/assets/93519223/ceff2f62-af0d-409d-b83d-6b077288596b)

**Comment by danagbemava-nc** [comment] 2023-05-23 13:05
Hi @talp-flytrex, please share the font file that you used in your reproduction. 

Thank you

**Comment by danagbemava-nc** [comment] 2023-05-24 06:58
Hi @talp-flytrex, can you try running the app with the command below to see if it reproduces for you? Before that, can you try to upgrade to stable 3.10.1 to see if it reproduces? If it does, can you try running the command below?

`flutter run --no-enable-impeller`. 


On flutter 3.10+, the default renderer for iOS is impeller. I tested this on my iPhone XS but I could not reproduce the bug and I do not have an iPhone XR so I cannot test on that device as well.

**Comment by talp-flytrex** [comment] 2023-05-24 07:43
@danagbemava-nc 
Issue still happens with `3.10.1`
Issue does **NOT** happen when running `flutter run --no-enable-impeller`.
I also tested on several iOS devices and it happens only on iPhone XR.

**Comment by danagbemava-nc** [comment] 2023-05-25 06:49
Hi @talp-flytrex, thanks for the updates. One final thing, can you check on the `master` channel to see if you still experience the issue over there? 

You can switch to the master channel by running 

```
flutter channel master
flutter upgrade
```

If it still reproduces on the `master` channel, please provide the output of `flutter doctor -v` for the master channel and if possible some side-by-side screenshots of skia vs impeller. 

Thank you

**Comment by talp-flytrex** [comment] 2023-05-28 09:40
@danagbemava-nc 
The issue still happens on `master` channel (version: `3.11.0-14.0.pre.61`)

**Comment by danagbemava-nc** [comment] 2023-05-29 06:40
Thanks for the info @talp-flytrex. 

Labeling for further investigation as this seems to reproduce only on specific devices as reported in https://github.com/flutter/flutter/issues/127386#issuecomment-1560611674. 

This seems to be an impeller only issue as well.

**Comment by kaankoken** [comment] 2023-06-05 06:37
I have the same issue using flutter 3.10.3 & several iphone devices. (iphone 14 pro max, iphone 11)

**Comment by nelsoncamposCW** [comment] 2023-07-21 17:09
I had this issue too, I will use Skia until this issue is solved

**Comment by FelixMittermeier** [comment] 2023-08-03 10:58
The screenshots provided (of the text) also happens for me on the iPhoneXR. I like Impeller way more in general but the text rendering is still way better with Skia unfortunately

**Comment by aytunch** [comment] 2023-09-06 15:41
Hi, coming from https://github.com/dnfield/flutter_svg/issues/975
Not to rush or anything but, since impeller is being used by default in the latest Flutter, this rendering problem causes a lot of bad feedback for our app (when using svg icons)
I personally did not see any weird text rendering tbh.
Respectfully, is there any ETA on this?

**Comment by gaaclarke** [comment] 2023-10-16 20:15
Is this supposed to reproduce on the iPhone XR simulator?  It looks fine there at HEAD:

## doctor
```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.16.0-11.0.pre.82, on macOS 13.6 22G120 darwin-arm64, locale en)
    • Flutter version 3.16.0-11.0.pre.82 on channel main at /Users/aaclarke/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 06c1b1ecf4 (2 hours ago), 2023-10-16 14:29:19 -0400
    • Engine revision 64734a2666
    • Dart version 3.3.0 (build 3.3.0-27.0.dev)
    • DevTools version 2.28.1
```

## screenshot

<img width="496" alt="Screenshot 2023-10-16 at 1 14 25 PM" src="https://github.com/flutter/flutter/assets/30870216/ee80e2a0-d273-4628-9b37-0ad3c2587576">

**Comment by gaaclarke** [comment] 2023-10-16 20:46
I just checked out framework version `84a1e904f4` (3.10), and this definitely reproduces there on the simulator.  I'm marking this as closed since it doesn't reproduce at HEAD anymore.

<img width="205" alt="Screenshot 2023-10-16 at 1 43 53 PM" src="https://github.com/flutter/flutter/assets/30870216/6336c608-dfcb-4853-9e3a-9f374e97e43d">

(Screenshot at `84a1e904f4` with iPhone XR simulator)

**Closed by gaaclarke** 2023-10-16 20:46 UTC
Labels: e: device-specific, platform-ios, engine, a: typography, c: rendering, P2, e: impeller, team-engine, triaged-engine, multiteam-retriage-candidate
