### ISSUE TITLE
android license issue on ubuntu

### ISSUE THREAD

**Issue by MoRmdn** [flutter/flutter#73220] opened 2021-01-02 19:05 UTC
dark@Dark-Blade:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    

- [x] **✗ Android license status unknown.**

      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.
[!] Android Studio
   

- [x]  **_**✗ Flutter plugin not installed; this adds Flutter specific functionality.
- [x]     ✗ Dart plugin not installed; this adds Dart specific functionality.**_**

    ✗ android-studio-dir = /usr/local/android-studio
    ✗ Android Studio not found at /usr/local/android-studio
 
[!] Connected device                          
    ! No devices available

! Doctor found issues in 3 categories.

- [x] when i run 
### 
**flutter doctor --android-licenses to solve first problem this what i get** 

dark@Dark-Blade:~$ flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

**Comment by jdf-id-au** [comment] 2021-01-03 00:29
I got the same stack trace with both the snap and the tar installations.

```
% java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

**Comment by MoRmdn** [comment] 2021-01-03 09:48
> I got the same stack trace with both the snap and the tar installations.
> 
> ```
> % java --version
> openjdk 11.0.9.1 2020-11-04
> OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
> OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
> ```

I had solved it by install the command line SDK tool in android studio 
and running flutter doctor --android-licenses

**Comment by iapicca** [comment] 2021-01-03 14:12
> I had solved it by install the command line SDK tool in android studio
> and running flutter doctor --android-licenses

is the issue is solved please close it
the correct procedure for installation on linux is described [here](https://flutter.dev/docs/get-started/install/linux#android-setup)

**Comment by TahaTesser** [comment] 2021-01-04 11:04
Hi @MoRmdn 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-01-04 11:04 UTC
