### ISSUE TITLE
Flutter beta channel broken for fragment shaders (windows 11)

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#141838] opened 2024-01-19 04:31 UTC
### Steps to reproduce

Clone a project like https://github.com/renancaraujo/turi
`flutter run -d windows`

### Expected results

Turi running.
Web shaders working.

### Actual results

Turi runs, but the screen gets corrupted with some black frames.

Also:
Using shaders on **flutter web** stopped working with a runtime error loading the shader.
`flutter run -d chrome --web-renderer canvaskit`

With Flutter 3.13.0: see screenshot
With Flutter 3.19.0-0.2.pre: exception (see logs)

3.19.0-0.2.pre compiled for web throws in some stack trace checking if the shader is a `typeof string` when its an `object`.

### Code sample

none

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/1924313/8517619d-bfc6-4e87-8c4b-fdc26bd741f1)

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following FormatException was thrown:
Invalid Shader Data

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
lib/_engine/engine/shader_data.dart 24:7                                     fromBytes
lib/_engine/engine/canvaskit/painting.dart 305:46                            fromBytes
lib/_engine/engine/canvaskit/renderer.dart 464:32                            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.19.0-0.2.pre, on Microsoft Windows [Version 10.0.22631.3007], locale en-US)
    • Flutter version 3.19.0-0.2.pre on channel beta at C:\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c1df7d07ac (29 hours ago), 2024-01-17 15:42:07 -0800
    • Engine revision 4f18bb4dcb
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Development\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Development\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code, 64-bit edition (version 1.85.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.218
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

**Comment by huycozy** [comment] 2024-01-19 11:01
Hi @jtmcdole 
I ran the project on my Windows 10 (Windows desktop app) but can't see the screenshot you shared. The splash and gameplay scenes are showing on my end like this:

<details>
<summary>Demo (splash+game play)</summary>

![image](https://github.com/flutter/flutter/assets/104349824/3aa62ed1-c7d9-4936-b185-1fc206ff4baa)

![image](https://github.com/flutter/flutter/assets/104349824/6573246a-35c1-4308-b9a7-8b869492feb4)

</details>

Could you share how to produce the issue like in the screenshot you share? 

When running on Web, the app is a black screen only and there is an exception from the output console. On Flutter stable `3.16.8`, the exception has only the message `Got object store box in database hydrated_box` but on beta channel `3.19.0-0.2.pre`, it also has the message `FormatException: Invalid Shader Data` like you shared above. The master channel has the same error as beta channel.

<details>
<summary>Exception on stable 3.16.8 - Web</summary>

```console
Launching lib\main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:52440/gwPuHYsLAV8=/ws
Debug service listening on ws://127.0.0.1:52440/gwPuHYsLAV8=/ws
Connecting to VM Service at ws://127.0.0.1:52440/gwPuHYsLAV8=/ws
Got object store box in database hydrated_box.
[log] RangeError (index): Index out of range: index should be less than 5: 19
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 610:7            _set]
lib/_engine/engine/shader_data.dart 56:15                                    fromBytes
lib/_engine/engine/canvaskit/painting.dart 305:46                            fromBytes
lib/_engine/engine/canvaskit/renderer.dart 397:32                            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
```
</details>

**Comment by jtmcdole** [comment] 2024-01-19 14:44
> I ran the project on my Windows 10 (Windows desktop app) but can't see the screenshot you shared. The splash and gameplay scenes are showing on my end like this:

The screen shot is from a private repo. It's only Flutter with a single fragment shader- and that's the "good case" (i.e. Flutter Stable). The bad case is the logs.


> gameplay scenes are showing on my end like this:

Yes, so when I run Turi, it runs for the first part, but when I get to the jumping phase; the graphics get corrupted.

I probably should not have mixed windows + web in the same bug report.  The gits of it is:

- Turi runs but gets corrupted on Windows with Flutter Beta
- Personal planet shader does not run on Windows or Web with Flutter Beat - does on Stable.

**Comment by jtmcdole** [comment] 2024-01-19 15:16
3.19.0-0.1.pre -  planet shader works on windows, not on web.
 3.19.0-0.2.pre -  planet shader works on windows, not on web.

**Comment by parlough** [comment] 2024-01-19 17:32
\cc @jonahwilliams

**Comment by huycozy** [comment] 2024-01-22 04:46
>Turi runs but gets corrupted on Windows with Flutter Beta

@jtmcdole Do you mean these spots in these red circles? If they are not, could you please share a demo for the issue?

<details>
<summary>Demo screenshot</summary>

![image](https://github.com/flutter/flutter/assets/104349824/593b6bd8-3f40-49f8-ab34-e49735321f87)

</details>

Please split this into separate issues for tracking them better. Thank you!

**Comment by jtmcdole** [comment] 2024-01-22 21:19
> @jtmcdole Do you mean these spots in these red circles? If they are not, could you please share a demo for the issue?

No; though I do see those.  What I see is a black splotch that covers the middle of the screen.

**Comment by jtmcdole** [comment] 2024-01-25 02:26
I re-upgraded to the beta channel and the only glitches I'm getting now are the green dots mentioned before.

**Comment by jtmcdole** [comment] 2024-01-25 02:29
I do still get shader errors when running a single fragment shader in chrome:


```
This app is linked to the debug service: ws://127.0.0.1:54308/iOQc166Qknk=/ws
js_primitives.dart:30 ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
js_primitives.dart:30 The following FormatException was thrown:
js_primitives.dart:30 Invalid Shader Data
js_primitives.dart:30 
js_primitives.dart:30 When the exception was thrown, this was the stack:
js_primitives.dart:30 dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
js_primitives.dart:30 lib/_engine/engine/shader_data.dart 24:7                                     fromBytes
js_primitives.dart:30 lib/_engine/engine/canvaskit/painting.dart 305:46                            fromBytes
js_primitives.dart:30 lib/_engine/engine/canvaskit/renderer.dart 464:32                            <fn>
js_primitives.dart:30 dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
js_primitives.dart:30 dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
js_primitives.dart:30 dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
js_primitives.dart:30 dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
js_primitives.dart:30 dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
js_primitives.dart:30 dart-sdk/lib/async/future_impl.dart 713:7                                    callback
js_primitives.dart:30 dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
js_primitives.dart:30 dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
js_primitives.dart:30 dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
js_primitives.dart:30 ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by huycozy** [comment] 2024-01-25 06:17
>I re-upgraded to the beta channel and the only glitches I'm getting now are the green dots mentioned before.

I'm not sure if this is an issue as it's a complex project that needs to dig dive. It would be better if there is a minimal sample code to reproduce it. 

I will label this issue for the error on Web platform: `Invalid Shader Data`. If you also agree this issue should only centralize on issue on Web, please update the corresponding title. Thanks!

<details>
<summary>flutter doctor -v (stable, beta and master)</summary>

```bash
[!] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.16.8 on channel stable at C:\WORKING\SDK\flutter
    ! Warning: `flutter` on your path resolves to C:\Aliases\flutter.bat, which is not inside your current Flutter SDK checkout at C:\WORKING\SDK\flutter. Consider adding
      C:\WORKING\SDK\flutter\bin to the front of your path.
    ! The dart binary is not on your path. Consider adding C:\WORKING\SDK\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (5 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\huynq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

```bash
[!] Flutter (Channel master, 3.19.0-9.0.pre.50, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.19.0-9.0.pre.50 on channel master at C:\WORKING\SDK\flutter_master
    ! Warning: `flutter` on your path resolves to C:\Aliases\flutter.bat, which is not inside your current Flutter SDK checkout at C:\WORKING\SDK\flutter_master. Consider
      adding C:\WORKING\SDK\flutter_master\bin to the front of your path.
    ! The dart binary is not on your path. Consider adding C:\WORKING\SDK\flutter_master\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dea6b994e (13 hours ago), 2024-01-21 12:01:23 -0500
    • Engine revision a7b207d5a1
    • Dart version 3.4.0 (build 3.4.0-52.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\huynq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```


```bash
[!] Flutter (Channel beta, 3.19.0-0.2.pre, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.19.0-0.2.pre on channel beta at C:\WORKING\SDK\flutter
    ! Warning: `flutter` on your path resolves to C:\Aliases\flutter.bat, which is not inside your current Flutter SDK checkout at C:\WORKING\SDK\flutter. Consider adding
      C:\WORKING\SDK\flutter\bin to the front of your path.
    ! The dart binary is not on your path. Consider adding C:\WORKING\SDK\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c1df7d07ac (4 days ago), 2024-01-17 15:42:07 -0800
    • Engine revision 4f18bb4dcb
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\huynq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```
</details>

**Comment by bleroux** [comment] 2024-02-28 14:34
Closing as fixed because https://github.com/flutter/engine/pull/49754 has landed

**Closed by bleroux** 2024-02-28 14:34 UTC
Labels: c: crash, engine, platform-web, has reproducible steps, P2, team-web, triaged-web, found in release: 3.19

**Comment by renancaraujo** [comment] 2024-02-29 12:14
Hello there, 
Will this cherrypicked into the stable channel? 
As of right now, **no fragment shaders work on the web on the stable channe**l.
