### ISSUE TITLE
 onPanUpdate is tricked when you touch the screen

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#61454] opened 2020-07-14 14:55 UTC
```
var gestureDetector = GestureDetector(
      child: Container(
        width: 300,
        height: 300,
        color: Colors.blue,
        //  child: small,
      ),
      onTap: () => print("clicked in outer"),
      onPanUpdate: (detail) {
        print("on pan update");
      },
    );
```

if onTap is comments, then onPanUpdate is tricked when you touch the screen,
but when onTap is there , then onPanUpdate will be tricked only when you really move some distance;

so it reacts differenctly;

**Comment by PixelToast** [comment] 2020-07-14 15:06
This is intentional because tap gestures often have a bit of slip, you wouldn't want to accidentally trigger pan events.

**Comment by wanjm** [comment] 2020-07-14 22:46
but this makes pan acts different.

**Comment by TahaTesser** [comment] 2020-07-15 10:23
Hi @wanjm 
Can you explain how  " pan acts different"? Provide an example an Can you please provide your `flutter doctor -v`
Thank you

**Comment by wanjm** [comment] 2020-07-17 15:02
```
var gestureDetector = GestureDetector(
      child: Container(
        width: 300,
        height: 300,
        color: Colors.blue,
        //  child: small,
      ),
      //onTap: () => print("clicked in outer"),
      onPanUpdate: (detail) {
        print("on pan update");
      },
    );
```
with the above code, I do the same action, just touch the screen and don't move; onPanUpdate is called;
but when the onTap is uncommented in the above , and I just touch screen and don't move , onPanUpdate will not be called until I move  some pixes; 

so with same action "just touch the screen and don't move", onPanUpdate acts differently depends on whether there is onTap;

any way I think it is designed now, as it gives more flexibility to developers;

**Comment by TahaTesser** [comment] 2020-07-20 06:50
Hi @wanjm 
Yes, as mentioned earlier https://github.com/flutter/flutter/issues/61454#issuecomment-658234581, it's by design 

given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-20 06:50 UTC
Labels: in triage
