### ISSUE TITLE
a bug with text fields demo in  flutter_gallery 

### ISSUE THREAD

**Issue by welldone217** [flutter/flutter#9326] opened 2017-04-11 03:30 UTC
## text fields on focus bug show me
```
Performing hot reload...                             569ms
Reload done: 0 of 480 libraries needed reloading.
E/SpannableStringBuilder( 4025): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4025): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
W/IInputConnectionWrapper( 4025): getCursorCapsMode on inactive InputConnection
E/SpannableStringBuilder( 4025): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
```

## Flutter Doctor
```
D:\aflutter>cd flutter_gallery

D:\aflutter\flutter_gallery>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], channel master)
    • Flutter at D:\huanjing\dart\flutter
    • Framework revision a5593b1678 (6 hours ago), 2017-04-10 14:20:47 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6

[√] Host Executable Compatibility
    • Downloaded executables execute on host

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at D:\huanjing\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: D:\huanjing\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at D:\huanjing\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4006
    • Flutter plugin version 12.1

[√] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).
```

**Comment by eseidelGoogle** [comment] 2017-04-11 21:58
I'm not sure I understand.  Could you give a bit more context of what you were attempting to do vs. what you saw?

FYI @abarth

**Comment by eseidelGoogle** [comment] 2017-04-12 02:36
https://github.com/flutter/flutter/issues/9282 also uses the words "text field" and "focus" but I'm not sure if that's what you're seeing.

**Comment by welldone217** [comment] 2017-04-12 02:41
this is my opteration。

http://img0.ph.126.net/8n2rd39olFmRobcx6etu9A==/6632177172934202055.png
http://img0.ph.126.net/9VFdCZSp_2MVXxRUo8H_kw==/6632444354257079742.png 



in myself program  The effect is this #9282。

**Comment by eseidelGoogle** [comment] 2017-04-12 03:28
You definitely don't want to be creating a new editing controller every build. :)  You want to hold onto the Controller in your state.

We clearly need to update the docs to make that more clear: https://docs.flutter.io/flutter/widgets/TextEditingController-class.html  FYI @abarth

**Comment by welldone217** [comment] 2017-04-12 06:13
controller:new TextEditingController(text:customer['uname']),

in this code just want a initalvalue,the doc just say ok.but in Text_Form_Field.dart has no.

I make a gif ,

<img src='http://img1.ph.126.net/lR9tX9zoqMbStQWk3_cQug==/6632373985512905797.gif'>
 and the code is same  from  text fileds demo in flutter_gallery.

**Comment by welldone217** [comment] 2017-04-12 06:27
maybe android monitors log you want 


04-12 06:26:06.493 6625-6625/com.yourcompany.customers E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-12 06:26:06.493 6625-6625/com.yourcompany.customers E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-12 06:26:06.851 6625-6625/com.yourcompany.customers E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-12 06:26:06.851 6625-6625/com.yourcompany.customers E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-12 06:26:08.487 6625-6625/com.yourcompany.customers E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-12 06:26:08.487 6625-6625/com.yourcompany.customers E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
04-12 06:26:08.585 6625-6641/com.yourcompany.customers I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
04-12 06:26:08.593 6625-6641/com.yourcompany.customers I/flutter: The following assertion was thrown building _AnimatedLabel(duration: 200ms; inherit: true; color:
04-12 06:26:08.593 6625-6641/com.yourcompany.customers I/flutter: Color(0xffff80ab); size: 14.0; dirty; state: _AnimatedLabelState#790657948(ticker active)):
04-12 06:26:08.593 6625-6641/com.yourcompany.customers I/flutter: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 195 pos 12: 'begin.inherit ==
04-12 06:26:08.593 6625-6641/com.yourcompany.customers I/flutter: end.inherit': is not true.
04-12 06:26:08.606 6625-6641/com.yourcompany.customers I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
04-12 06:26:08.606 6625-6641/com.yourcompany.customers I/flutter: more information in this error message to help you determine and fix the underlying cause.
04-12 06:26:08.606 6625-6641/com.yourcompany.customers I/flutter: In either case, please report this assertion by filing a bug on GitHub:
04-12 06:26:08.606 6625-6641/com.yourcompany.customers I/flutter:   https://github.com/flutter/flutter/issues/new
04-12 06:26:08.606 6625-6641/com.yourcompany.customers I/flutter: When the exception was thrown, this was the stack:
04-12 06:26:08.613 6625-6641/com.yourcompany.customers I/flutter: #2      TextStyle.lerp (package:flutter/src/painting/text_style.dart:195:12)
04-12 06:26:08.613 6625-6641/com.yourcompany.customers I/flutter: #3      TextStyleTween.lerp (package:flutter/src/widgets/implicit_animations.dart:77:41)
04-12 06:26:08.613 6625-6641/com.yourcompany.customers I/flutter: #4      Tween.evaluate (package:flutter/src/animation/tween.dart:126:12)
04-12 06:26:08.615 6625-6641/com.yourcompany.customers I/flutter: #5      _AnimatedLabelState.build (package:flutter/src/material/input_decorator.dart:499:30)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3193:27)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3103:15)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3004:5)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1879:33)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #10     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:353:20)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #11     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #12     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:645:15)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #13     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:580:9)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: #14     _beginFrame (file:///ssd2/chrome_infra/build/slave/fake_slave/build/src/flutter/lib/ui/hooks.dart:83)
04-12 06:26:08.616 6625-6641/com.yourcompany.customers I/flutter: (elided 2 frames from class _AssertionError)
04-12 06:26:08.617 6625-6641/com.yourcompany.customers I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
04-12 06:26:08.672 6625-6641/com.yourcompany.customers I/flutter: Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 195 pos 12: 'begin.inherit == end.inherit': is not true.

**Comment by goderbauer** [comment] 2018-12-27 22:05
With the current information on this bug I am unable to reproduce this issue. Could you maybe post a minimal code example that shows the issue and explain what interactions you did to produce the crash?

**Comment by zoechi** [comment] 2019-01-21 09:36
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-21 09:36 UTC
Labels: framework, severe: crash, waiting for customer response
