### ISSUE TITLE
[webview_flutter] Clicking text with WebView widget on Android 10 will cause crash.

### ISSUE THREAD

**Issue by kevin-X-lee** [flutter/flutter#56990] opened 2020-05-12 10:27 UTC
## Steps to Reproduce

example:
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: WebView(
          initialUrl: 'https://flutter.dev',
          javascriptMode: JavascriptMode.unrestricted,
        ),
      ),
    );
  }
}
```

1. Run `flutter create example`.
2. Run example and open drawer widget.
3. Call the keyboard.
4. paused application  and resumed application.
5. repeat call the keyboard.
6. After a few repeated paused and resumed will be problems.

**Expected results:** 
Web view can be used normally.
[Video](https://github.com/kevin-X-lee/demo.git)
**Actual results:** 
Web view lock click unresponsive.

<details>
  <summary>Logs</summary>

```
E/flutter (27457): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Neither user 10674 nor current process has android.permission.WAKE_LOCK., null)
E/flutter (27457): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (27457): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (27457): <asynchronous suspension>
E/flutter (27457): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (27457): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:552:41)
E/flutter (27457): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
E/flutter (27457): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
E/flutter (27457): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
E/flutter (27457): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (27457): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (27457): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
E/flutter (27457): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (27457): #11     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:394:13)
E/flutter (27457): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (27457): #13     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
E/flutter (27457): #14     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:480:7)
E/flutter (27457): #15     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
E/flutter (27457): #16     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
E/flutter (27457): #17     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
E/flutter (27457): #18     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
E/flutter (27457): #19     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
E/flutter (27457): #20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
E/flutter (27457): #21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
E/flutter (27457): #22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
E/flutter (27457): #23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1013:9)
E/flutter (27457): #24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:929:5)
E/flutter (27457): #25     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (27457): #26     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (27457): #27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (27457): #28     _invoke (dart:ui/hooks.dart:277:10)
E/flutter (27457): #29     _drawFrame (dart:ui/hooks.dart:235:3)
E/flutter (27457): 
```

```
[✓] Flutter (Channel master, 1.19.0-1.0.pre.26, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
    • Flutter version 1.19.0-1.0.pre.26 at /Users/ming/flutter
    • Framework revision 793e6a48a1 (2 days ago), 2020-05-10 12:14:01 +0800
    • Engine revision 9b905d3f03
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 617bc54b71)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ming/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ming/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • SM N9700   • R58M84RVP3D • android-arm64  • Android 10 (API 29)
    • Web Server • web-server  • web-javascript • Flutter Tools
    • Chrome     • chrome      • web-javascript • Google Chrome 81.0.4044.138
```

</details>

**Comment by TahaTesser** [comment] 2020-05-12 15:18
```
E/flutter (20147): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Neither user 10541 nor current process has android.permission.WAKE_LOCK., null)
```

duplicate of [#49912](https://github.com/flutter/flutter/issues/49912)

**Closed by TahaTesser** 2020-05-12 15:18 UTC
