### ISSUE TITLE
analysis feedback changes if you include sky_engine in your project

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6769] opened 2016-11-08 22:19 UTC
Repro case and instructions here: https://gist.github.com/sethladd/79b6d1cdcc9d3b29b5e3acc27581944a

We'd expect there to be _no warnings_ for the code in `lib/main.dart`, however the inclusion of sky_engine package into `.packages` is enough to trigger the warning.

The warning we get:

```
[warning] Unsound implicit cast from 'List<dynamic>' to 'List<Bar>'. (/Users/sethladd/tmp/repocase/lib/main.dart, line 8, col 23)
```

Which, we're told, is something we shouldn't be getting. The code should be valid (we're told).

Tested with:

```
~/tmp/repocase $ dartanalyzer --version
dartanalyzer version 1.21.0-dev.4.0
```

**Comment by sethladd** [comment] 2016-11-08 22:20
cc @danrubel

**Comment by sethladd** [comment] 2016-11-08 22:22
cc @yyoon

**Comment by sethladd** [comment] 2016-11-08 22:26
cc @leafp to confirm our code is correct?

**Comment by leafpetersen** [comment] 2016-11-08 23:32
That code should be strong mode clean, and I see no errors if I run the regular strong mode analyzer on it (I didn't try to reproduce the sky_engine issue).

I believe that flutter uses their own version of the SDK, so perhaps that has something to do with it?  That error is what I would expect to see if List.map was not properly annotated as a generic method.

**Comment by sethladd** [comment] 2016-11-09 00:47
> I believe that flutter uses their own version of the SDK

I'm analyzing with "dartanalyzer", from homebrew, version 1.21.0-dev.4.0.

The variable here isn't "dartanalyzer" or "flutter analyze", it's "is sky_engine in my .packages".

**Comment by leafpetersen** [comment] 2016-11-09 01:19
> The variable here isn't "dartanalyzer" or "flutter analyze", it's "is sky_engine in my .packages".

I don't know where the external version of sky_engine lives (the pub.dartlang version looks way out of date, and 404s on the link to the source code), but looking at the internal version I see a copy of the dart sdk.  This makes me.... suspicious... :)  I don't know why it's there if it's not being used, and if it's being used, then it seems relevant to this problem.

It's possible that this is a general analyzer bug - there was a caching issue that @stereotype441 just fixed that caused some strange inference problems, but this looks pretty unlikely to be related to me.

I know very little about how flutter works, but I know there's some voodoo going on with the "dart:flutter" etc URIs.  That seems like the most likely problem to me: that importing sky_engine is causing a different SDK to be used because of some of this voodoo.

**Comment by sethladd** [comment] 2016-11-09 01:21
> I don't know where the external version of sky_engine lives 

Oh, sorry. It comes from the Flutter SDK, which you clone from github.

We can try to track this down with Dan R. Meanwhile, thanks for confirming that the code should be strong mode clean. That helps eliminate a variable.

**Comment by leafpetersen** [comment] 2016-11-09 01:22
Here's something you can try: make the following change to the code:

```dart
  List<Bar> barList = fooList.map/*<Bar>*/((Foo f) => new Bar(f)).toList();
```
and see what happens.

If you get an error about number of type parameters, then it is an issue with the definition of `Iterable.map` that you are picking up.

If that makes the error go away, then you have a correct definition of `Iterable.map`, but something is causing the inference of the generic type parameter to fail.

**Comment by sethladd** [comment] 2016-11-09 01:28
sky_engine's version of iterable.dart has `  Iterable/*<T>*/ map/*<T>*/(/*=T*/ f(E e)) =>       new MappedIterable<E, dynamic/*=T*/>(this, f);` 

which I guess is correct/up-to-date?

**Comment by leafpetersen** [comment] 2016-11-09 01:33
Looks right to me.

**Comment by leafpetersen** [comment] 2016-11-09 01:35
But there are failure modes that the test that I suggested above might suss out, so I would try it.

For example, something may be causing the sky_engine sdk to be analyzed in a non-strong mode, resulting in an analyzer context which is non-strong, which is then used to analyze lib/main.dart in strong mode.  Hijinks ensue.

**Comment by yyoon** [comment] 2016-11-09 01:39
I tried adding the `/*<Bar>*/` comment as suggested, and here's the result:

```
youngseokyoon temp$ dartanalyzer .
Analyzing [.]...
[error] The type '((Foo) → dynamic) → Iterable<dynamic>' is declared with 0 type parameters, but 1 type arguments were given. (/usr/local/google/home/youngseokyoon/Programming/temp/lib/foo.dart, line 12, col 31)
[warning] Unsound implicit cast from 'List<dynamic>' to 'List<Bar>'. (/usr/local/google/home/youngseokyoon/Programming/temp/lib/foo.dart, line 12, col 23)
[lint] Document all public members (/usr/local/google/home/youngseokyoon/Programming/temp/lib/foo.dart, line 1, col 7)
1 error, 1 warning and 1 lint found.
```

**Comment by eseidelGoogle** [comment] 2016-11-09 02:01
sky_engine is a package built from the flutter/engine repository by our
buildbots, hosted on Google Cloud Storage and then pulled down by the
`flutter` tool into bin/cache/pkgs/sky_engine corresponding to the
flutter/engine version set in bin/internal/engine.version.

Here are the build rules which produce sky_engine:
https://github.com/flutter/engine/tree/master/sky/packages/sky_engine

As seth says, it's easiest to look at the package by using your local
flutter/flutter checkout and running the `flutter` tool once to have it
populate bin/cache.

**Comment by leafpetersen** [comment] 2016-11-09 05:45
> I tried adding the /*<Bar>*/ comment as suggested, and here's the result:

Ok, so that error means that the analyzer context that is being used to analyze your code was run over the SDK in non-strong mode (and so it picked up a non-generic version of Iterable.map).  I don't know anything about how the flutter modified SDKs work. @pq or @danrubel are probably the best people to talk to here.

**Comment by sethladd** [comment] 2016-11-09 15:46
Thanks for the analysis! Feels like we're getting closer.

**Comment by danrubel** [comment] 2016-11-09 18:33
The sky_engine contains an [_embedder.yaml file](https://github.com/flutter/engine/blob/master/sky/packages/sky_engine/lib/_embedder.yaml) which  affects analysis. By including the sky_engine package, you are causing `dartanalyzer` to analyze against a different set of `dart:*` libraries when analyzing `lib/main.dart`.

**Comment by sethladd** [comment] 2016-11-09 18:35
Looking at the _embedder.yaml, it points to dart libraries that have the generic methods syntax. It also turns on super-mixins.

What else can toggle "turn off strong mode" ?

**Comment by yyoon** [comment] 2016-11-20 00:10
Any updates on this?

**Comment by danrubel** [comment] 2016-11-20 03:09
I'm working towards making the analysis options more explicit via [an analysis options "include" directive](https://github.com/dart-lang/sdk/issues/27817). Once that is in place, we can remove the modifications that the `_embedder.yaml` makes to how files are analyzed.

**Comment by yyoon** [comment] 2016-11-20 22:42
Sounds good. Thanks!

**Comment by bwilkerson** [comment] 2016-11-23 21:32
I believe that I have found the problem and have sent out a CL for review with a fix (https://codereview.chromium.org/2523313002/). We were not correctly preserving the options in the SDK when using an SDK described by an _embedder.yaml file.

**Comment by sethladd** [comment] 2016-11-25 16:43
Thanks for taking a look!

**Comment by sethladd** [comment] 2016-11-28 17:10
@pq Do you know how to tell when this is ready for us to test? How can we connect the next Dart SDK roll back to this issue?

**Comment by pq** [comment] 2016-11-29 18:57
This pull should have the fix:  https://github.com/flutter/flutter/pull/7065.  Just waiting on a review.

> How can we connect the next Dart SDK roll back to this issue?

A quick thought would be to create (weekly?) issues to track dev SDK rolls so we can do just this kind of thing.  Don't want to add extra issues if it wouldn't be generally valued though.

**Comment by sethladd** [comment] 2016-11-29 20:20
If the rule is "you'll get the PR on the next roll of the SDK", that's something we can mentally track. I didn't know if Dart SDK rolls come from a branch or master.

**Comment by pq** [comment] 2016-11-29 20:50
> If the rule is "you'll get the PR on the next roll of the SDK", that's something we can mentally track.

👍 

We generally track the latest dev push.  If there's a blocker, I try and file a ticket.

**Comment by yyoon** [comment] 2016-12-20 23:08
BTW, I can confirm that this has been fixed. Thanks!
We've enabled strong-mode back and not seeing any issues for a couple of weeks.

@sethladd Feel free to close the issue.

**Comment by sethladd** [comment] 2016-12-20 23:22
Great to hear.

**Closed** 2016-12-20 23:22 UTC
Labels: affects: dev experience, affects: tools, customer: pink
