### ISSUE TITLE
The GameRenderBox class does not implement "computeDryLayout".

### ISSUE THREAD

**Issue by hanserl** [flutter/flutter#74122] opened 2021-01-16 16:11 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2021-01-16 22:04
@hanserl 
`GameRenderBox` doesn't seem like a flutter class 
if you are experiencing a problem with a 3rd party package I recommend to open an issue in the dedicated github
if you believe the issue is caused by flutter 
please provide your `flutter doctor -v` and  a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by TahaTesser** [comment] 2021-01-18 09:04
Hi @zmunk 
This is already filed in https://github.com/flame-engine/flame/issues/629
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. 
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
Closing as duplicate of https://github.com/flutter/flutter/issues/74036
Thank you

**Closed by TahaTesser** 2021-01-18 09:04 UTC
