### ISSUE TITLE
Add Visual Studio 2022 support

### ISSUE THREAD

**Issue by LeftTwixWand** [flutter/flutter#85922] opened 2021-07-05 20:29 UTC
Hi, I'm using Visual Studio 2022 preview, and I can't run flutter on Windows.
I got the error:

![image](https://user-images.githubusercontent.com/50652041/124515472-336f1080-dde8-11eb-869d-ae0166e72248.png)

On the same computer with installed Visual Studio 2019 everything was working fine.
All the required components for flutter are installed.
The latest Visual Studio version info:

![image](https://user-images.githubusercontent.com/50652041/124515639-952f7a80-dde8-11eb-92ac-90b114e17738.png)

**Comment by stuartmorgan** [comment] 2021-07-05 23:08
This will require an update here at least: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/windows/build_windows.dart#L25-L28

**Comment by LeftTwixWand** [comment] 2021-07-06 06:33
> This will require an update here at least: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/windows/build_windows.dart#L25-L28

Thanks, I will try to fix it today)

**Comment by LeftTwixWand** [comment] 2021-07-06 19:53
How can I debug the flutter project?
I mean the build method, where is the cmake path is checking

**Comment by stuartmorgan** [comment] 2021-07-07 14:43
See https://github.com/flutter/flutter/wiki/The-flutter-tool#making-changes-to-the-flutter-tool

**Comment by spnda** [comment] 2021-09-04 13:50
I'd like to see an update on this.
However, it seems that Flutter uses the CMake binary shipped with VS. Sadly, VS 17 ships with an outdated CMake version (3.20.21032501-MSVC_2) that does not have `'Visual Studio 17 2022'` as a valid generator option (It was added in [3.21](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html#generator:Visual%20Studio%2017%202022)). So, we'll just have to wait for them to update to 3.21....

**Comment by LeftTwixWand** [comment] 2021-10-10 00:20
> Visual Studio 2022 Preview 4 ships with CMake 3.21, please fix this @spnda @LeftTwixWand

@Baneeishaque, thank you for reply! I will check it today)

**Comment by cbracken** [comment] 2021-11-09 22:57
@timsneath can we confirm this would be a blocker for a stable release? Obviously, we'll want to support it ASAP, but this will involve infra/buildbot upgrades to ensure we're testing all supported configurations in CI.

**Comment by cbracken** [comment] 2021-11-10 01:45
@godofredoc @keyonghan my recollection is we currently source our VS 2019 install from the Chromium CIPD bundle. Do you know if a Chromium bundle exists for VS 2022, and if not, when we might expect one?

**Comment by cbracken** [comment] 2021-11-10 01:59
Answer from @godofredoc is that on the devicelab/framework test side we bundle the VS install ourselves. Instructions for creating a new bundle are at [go/flutter-infra-vs](http://go/flutter-infra-vs) (Google internal).

**Comment by cbracken** [comment] 2021-11-10 17:55
There are a couple infra changes remaining to land; in particular https://github.com/flutter/cocoon/pull/1446. Once that's in the remaining work will be:
* [ ] Create a VS 2022 bundle following the instructions at [go/flutter-infra-vs](http://go/flutter-infra-vs) (Google internal)
* [ ] Make the changes necessary to support VS 2022
* [ ] Ensure we have enough Windows bots to cover the load of running our Windows tests against a new VS install
* [ ] Add a test suite similar to the tests we already execute in framework CI, but using VS 2022

**Comment by cbracken** [comment] 2021-11-10 17:56
One remaining item would be to determine the impact on plugin repo testing.

/cc @stuartmorgan for comment.

**Comment by stuartmorgan** [comment] 2021-11-10 17:59
The only impact I can think of would be to make sure that https://github.com/flutter/plugins/blob/master/.ci.yaml#L28 is installing whatever version we want to use there (or to update that line to a pinned version).

**Comment by godofredoc** [comment] 2021-11-11 23:24
\cc @CaseyHillers

**Comment by timsneath** [comment] 2021-11-15 00:54
With @stuartmorgan's patch, this looks fixed (at least on my machine). I uninstalled Visual Studio 2019 and now just have VS2022;  `flutter run -d windows` works on a VS2022-only machine running the latest `master` channel build at the time of writing. 

I think this might be good to close when another issue exists for any testing work.

**Comment by cbracken** [comment] 2021-11-15 19:26
@stuartmorgan's fix allows developers on VS2022 to build and run Flutter apps, but this is still untested and pending infra. As with all Flutter bugs, we'll close this once we have tests in place that prevent a regression.

**Comment by cbracken** [comment] 2021-11-15 20:32
If filed https://github.com/flutter/flutter/issues/93680 with some non-blocking followup work to avoid users being hit by a caching bug on future Visual Studio upgrades.

**Comment by cbracken** [comment] 2021-11-15 23:17
FWIW - while I don't think we should close this, since it includes prior discussion and the list of remaining tasks, I do think it's fair to remove this from the blockers list, since at this point, the remaining work is to eliminate the testing tech debt we've accrued here. There are unit tests, but no integration test.

**Comment by abdurrahman-adel** [comment] 2021-11-17 15:08
so, which flutter channel that support vs2022? or it is not supported yet?

**Comment by stuartmorgan** [comment] 2021-11-17 15:10
> so, which flutter channel that support vs2022? 

`master`

**Comment by LeftTwixWand** [comment] 2021-11-18 10:50
It works for me!
Thank you guys so much🚀🚀

Should I close the issue, or it's better to wait, when all the remaining task will be completed?

**Comment by cbracken** [comment] 2021-11-18 21:29
Good to hear! Please leave the issue open; we'll close it once we've upgraded our infrastructure to test with VS 2022; that way we avoid any regressions.

**Comment by Agondev** [comment] 2021-11-25 21:22
Is there an ETA for when VS22 support will trickle down to the lower branches?

**Comment by stuartmorgan** [comment] 2021-11-25 21:53
See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for general information about release schedules.

Support landed after the current beta (2.8) branched, so it will be whenever a version of 2.9 or higher reaches each channel.

**Comment by JoeGilkey** [comment] 2021-12-02 23:54
Could this be added as a hotfix? Waiting for 2.9 would rule out my ability to use Flutter on a major project we are in the planning stages on. We just upgraded all the developers to 2022 :(

**Comment by stuartmorgan** [comment] 2021-12-03 03:47
This is not a P0 or P1 issue, so is extremely unlikely to be cherry-picked to 2.8.

> Waiting for 2.9 would rule out my ability to use Flutter on a major project we are in the planning stages on.

Keep in mind that the desktop support that is on the stable channel is described as a "beta snapshot". If you are developing for desktop right now you will in general be better off using `beta` (in which case you only have to wait for the next beta branch, which happens monthly) or even `master`.

Alternately, my PR is small; you could easily patch it in locally for your own use.

**Comment by wudiplk** [comment] 2021-12-07 08:46
flutter channel master and update flutter sdk

**Comment by kj3115526** [comment] 2021-12-07 08:48
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在因外出有事，无法亲自回复您的邮件。我会在事情处理好后的第一时间回复您。如有急事，可以通过手机或短信的方式联系我。如果给你的工作或生活带来不便，请您原谅。

**Comment by mdaffailhami** [comment] 2021-12-13 06:22
> This is not a P0 or P1 issue, so is extremely unlikely to be cherry-picked to 2.8.
> 
> > Waiting for 2.9 would rule out my ability to use Flutter on a major project we are in the planning stages on.
> 
> Keep in mind that the desktop support that is on the stable channel is described as a "beta snapshot". If you are developing for desktop right now you will in general be better off using `beta` (in which case you only have to wait for the next beta branch, which happens monthly) or even `master`.
> 
> Alternately, my PR is small; you could easily patch it in locally for your own use.
___
Does the beta channel also support Visual Studio 2022?

**Comment by stephenwade** [comment] 2021-12-13 14:54
Not yet. It should support VS 2022 when they release the next beta later this month.

**Comment by tsinis** [comment] 2021-12-15 07:28
For those, who asked about the beta channel. 2.9.0-0.1.pre just have been landed there, so you are free to test it out :)

**Comment by ShahriyarB** [comment] 2021-12-18 15:09
> For those, who asked about the beta channel. 2.9.0-0.1.pre just has been landed there, so you are free to test it out :)

I confirm this worked

Updated to beta channel and it correctly detects Visual Studio 2022

**Comment by domesticmouse** [comment] 2021-12-30 10:33
@cbracken do you want to close this bug now and raise a new one for infrastructure, or do you want to update the title to reflect the outstanding work? It's a lil misleading at the moment.

**Comment by cbracken** [comment] 2022-01-04 21:03
@domesticmouse makes sense; I've opened https://github.com/flutter/flutter/issues/96138 for the infra side.

**Closed by cbracken** 2022-01-04 21:03 UTC
Labels: tool, platform-windows, a: desktop, a: build, passed first triage, team: infra, passed secondary triage, P4

**Comment by Ben0505** [comment] 2022-01-14 16:28
None works for me.
I have vs2022 in windows 11, what should I do?

**Comment by stephenwade** [comment] 2022-01-14 16:31
Switch to the [beta channel](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels). If that doesn't work, open a new issue and describe your problem there.

**Comment by davidfraser** [comment] 2022-01-19 10:18
There are instructions to patch Flutter 2.8 to work with VS2022 [here](https://stackoverflow.com/a/69951396/120398) - I haven't done anything extensive but it compiles and runs a basic app

**Comment by domesticmouse** [comment] 2022-01-19 10:32
@davidfraser I suspect you could get away with just using the latest flutter beta to regenerate the Windows runner. I can't see anything in the delta between the Flutter 2.8 generated Windows runner and the Flutter 2.10 beta generated Windows runner that would cause backwards incompatibilities.

**Comment by stuartmorgan** [comment] 2022-01-19 15:01
@domesticmouse The change was to the build command in `flutter`, not to the template, so regenerating with a newer version won't make 2.8 work.

**Comment by domesticmouse** [comment] 2022-01-19 22:14
Ahh, I stand corrected. My bad.
