### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "D:\SDK\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: D:\SDK\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0

### ISSUE THREAD

**Issue by maulikhichadiya** [flutter/flutter#156669] opened 2024-10-13 12:28 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=4984aba9 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
``

**Comment by danagbemava-nc** [comment] 2024-10-14 07:17
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143391

**Closed by danagbemava-nc** 2024-10-14 07:17 UTC
Labels: in triage
