### ISSUE TITLE
[web] Random images in grid of PhysicalModels are not displayed when scrolling

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#60460] opened 2020-06-28 08:47 UTC
![](https://user-images.githubusercontent.com/814785/85942845-49700880-b92c-11ea-9dc9-395498c42b28.gif)

Using `Image.network` instead of `ImageCard` works as expected.

Maybe related to https://github.com/flutter/flutter/issues/47328?

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ImageGrid(),
    );
  }
}

class ImageGrid extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: (MediaQuery.of(context).size.width / 180).floor(),
        childAspectRatio: 2.4,
      ),
      itemCount: 1000,
      itemBuilder: (BuildContext context, int index) {
        return ImageCard('https://picsum.photos/seed/$index/300/200');
      },
    );
  }
}

class ImageCard extends StatelessWidget {
  const ImageCard(this.url);

  final String url;

  @override
  Widget build(BuildContext context) {
    return PhysicalModel(
      color: Colors.red,
      child: Image.network(url, fit: BoxFit.cover),
    );
  }
}
```

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.78, on Mac OS X 10.15.5 19F101, locale en-CH)
    • Flutter version 1.20.0-3.0.pre.78 at /Users/ben/flutter
    • Framework revision 2962912d68 (25 hours ago), 2020-06-27 00:59:50 -0700
    • Engine revision fc0e27210c
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 63cf56d925)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ben/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • macOS desktop • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by iapicca** [comment] 2020-06-29 13:25
Hi @cbenhagen 
the fact that the issue does not occur using simply Image.network,
leads me to think that the problem are the widget being rebuilt,

<details><summary>sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ImageGrid(),
    );
  }
}

class ImageGrid extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: (MediaQuery.of(context).size.width / 180).floor(),
        childAspectRatio: 2.4,
      ),
      itemCount: 1000,
      itemBuilder: (BuildContext context, int index) {
        return ImageCard(url: 'https://picsum.photos/seed/$index/300/200', key: ValueKey(index));
      },
    );
  }
}

class ImageCard extends StatelessWidget {
  const ImageCard({this.url, Key key}) : super(key: key);
  final String url;

  @override
  Widget build(BuildContext context) {
    return Card(
      color: Colors.red,
      child: Image.network(url, fit: BoxFit.cover),
    );
  }
}
```

</details>

as expected using a `key` this behaviour does not occur;
does this fix the issue for you?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-06-29 13:34
Hi @cbenhagen 
I'm experiencing this when running with current master `1.20.0-3.0.pre.78` and dev `1.20.0-2.0.pre`, but not with beta `1.19.0-4.2.pre`. Does beta work as expected for you?

**Comment by cbenhagen** [comment] 2020-06-29 17:24
@iapicca the workaround you suggested does not work here.

@VladyslavBondarenko Yes this bug is not present in the beta.

**Comment by VladyslavBondarenko** [comment] 2020-06-30 08:33
I tried also with iOS and Android, it seems to work as expected there.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.100, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.100 at /Users/nevercode/dev/flutter
    • Framework revision f2f48df3af (3 hours ago), 2020-06-29 22:19:55 -0700
    • Engine revision a974b78117
    • Dart version 2.9.0 (build 2.9.0-19.0.dev f91547d6dd)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (5 available)
    • Redmi Note 7       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.5
    • macOS desktop      • macos                                    • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server         • web-server                               • web-javascript • Flutter Tools
    • Chrome             • chrome                                   • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by cbenhagen** [comment] 2020-06-30 11:16
Actually this is also reproducible in the beta.

**Comment by ferhatb** [comment] 2020-08-28 05:20
@goderbauer, @yjbanov  have you run across anything similar to this on native mobile?
Basically while the images inside the cards are still waiting for network request to complete, if you scroll the view up and down really fast, it looks like it reuses the card element somehow but picture is not repainted (the picture itself is there but instead of loading new image into it and repainting it just stays blank).

Only reproducable if you scroll really fast (with half the image still loading) and then scroll the opposite direction.

**Comment by goderbauer** [comment] 2020-08-28 16:14
I've not seen this on native mobile and also couldn't reproduce it there just now.

/cc @dnfield

**Comment by dnfield** [comment] 2020-08-28 16:19
It's possible that `ScrollAwareImageProvider` is getting messed up on web, but given that this works with a plain `Image.network`, that wouldn't be the first place I'd check.

**Comment by cbenhagen** [comment] 2020-09-09 08:00
This also happens when using `PhysicalModel` directly instead of the whole `Card` widget. I changed the title and the example accordingly.

**Comment by ferhatb** [comment] 2020-10-26 17:38
Landed in master.

**Comment by ferhatb** [comment] 2020-11-06 02:53
Still not completely fixed. Recycled canvas is used multiple times.

**Closed** 2020-11-06 08:52 UTC
Labels: P3, a: images, f: material design, found in release: 1.20, framework, has reproducible steps, platform-web, severe: regression, waiting for PR to land (fixed)
