### ISSUE TITLE
GestureDetector hitTesting not working when used with Transform.translate

### ISSUE THREAD

**Issue by RollyPeres** [flutter/flutter#39656] opened 2019-09-01 20:47 UTC
Hit testing does't seem to work for widgets like `InkWell`/`GestureDetector` when used in conjunction with `Transform.translate`.

Bug reproduction: https://gist.github.com/RollyPeres/82c079711a59940bcc535b834f48d550

`flutter doctor -v` ouput:

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.175], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\src\flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at C:\Users\roland.peres\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.37.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • SM A105FN • RF8M738WDVT • android-arm • Android 9 (API 28)
```

**Comment by Piinks** [comment] 2019-09-30 21:46
Hi @RollyPeres,
Thanks for reporting this. I've played with your reproduction a bit. It seems that the transformation is causing the cards to overlap. The detection of gestures appears to be deferring to the element above in the overlap areas. Do you expect a different behavior when tapping the overlapping areas?

I have also noticed that the further you go down the list, the further the hit area seems to migrate down. Notice in this gif that I can tap directly on the text in earlier cards, but not further down. I suspect the hit area is not being transformed up like the visual elements (i.e. the inkwell honors the correct area bounded by the borders).


![gestures](https://user-images.githubusercontent.com/16964204/65919414-0e3aac00-e391-11e9-9c22-c94c141f1790.gif)


 I have trimmed down your reproduction to better isolate the issue.
``` dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Demo')),
        body: ListView.builder(
          itemCount: 4,
          itemBuilder: (BuildContext context, int index) {
            return Transform.translate(
              offset: Offset(0.0, -20.0 * index),
              child: InkWell(
                splashColor: Colors.amber,
                onTap: () {},
                child: Container(
                  height: 100.0,
                  decoration: BoxDecoration(border: Border.all(
                    color: index % 2 == 0 ? Colors.blue : Colors.red,
                    width: 5.0,
                  )),
                  child: Align(
                    alignment: Alignment.topLeft,
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Text('Tap'),
                    ),
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

Let me know if you expect different behavior in the overlapping case and I will continue to work on the hit area. :)

**Comment by Piinks** [comment] 2019-09-30 22:04
Debug paint shows the boundary of the hit area growing smaller and smaller (notated by the light blue line)

![Screen Shot 2019-09-30 at 3 04 02 PM](https://user-images.githubusercontent.com/16964204/65920354-a33ea480-e393-11e9-83ef-039301fcfaf0.png)

**Comment by Piinks** [comment] 2019-10-01 19:37
@RollyPeres, would you be able to tell me more about your use case? This seems to be working as intended based on the composition of your widgets.

**Comment by RollyPeres** [comment] 2019-10-01 20:14
Hey @Piinks . Thanks for looking into this issue. Tbh, I would expect the hit testing area to be translated together with the list item. i.e. the `InkWell` tap/splash should respect the translated boundaries, or else there's limited usage of such feature.

As a workaround, I've implemented my own custom `Align` widget which uses a raw height instead of percent based `heightFactor` and works perfectly.

**Comment by RollyPeres** [comment] 2019-10-01 20:23
To have a better understanding of my scenario, I needed to translate those list items since I applied some custom clipping to them, so I had to get rid of the empty space left between them, while also respecting the new boundaries when the tap/splash is being applied to the item.

**Comment by Piinks** [comment] 2019-10-04 16:49
Thank you for explaining your use case further! Would you be willing to share a minimal code snippet of your workaround?
I think there is another way to achieve your layout. I noticed that transforming the list items within the list builder method like you have shown earlier not only results in misaligned hitTesting, but also, if you look at how the list items are built and disposed of as you scroll, they disappear early as you start to scroll them off of the screen. This is because the original bounds of the list item would have scrolled out of view by that point.

**Comment by RollyPeres** [comment] 2019-10-04 18:28
There you go @Piinks 

 ```
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Demo')),
        body: ListView.builder(
          itemCount: 4,
          itemBuilder: (BuildContext context, int index) {
            return FixedAlign(
              height: -20.0,
              child: InkWell(
                splashColor: Colors.amber,
                onTap: () {},
                child: Container(
                  height: 100.0,
                  decoration: BoxDecoration(
                      border: Border.all(
                    color: index % 2 == 0 ? Colors.blue : Colors.red,
                    width: 5.0,
                  )),
                  child: Align(
                    alignment: Alignment.topLeft,
                    child: const Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Text('Tap'),
                    ),
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

class FixedAlign extends SingleChildRenderObjectWidget {
  const FixedAlign({
    Key key,
    this.alignment = Alignment.center,
    this.width,
    this.height,
    Widget child,
  })  : assert(alignment != null),
        super(key: key, child: child);

  final double width;
  final double height;
  final AlignmentGeometry alignment;

  @override
  RenderObject createRenderObject(BuildContext context) {
    return RenderFixPositionedBox(
      alignment: alignment,
      width: width,
      height: height,
      textDirection: Directionality.of(context),
    );
  }

  @override
  void updateRenderObject(
      BuildContext context, RenderFixPositionedBox renderObject) {
    renderObject
      ..alignment = alignment
      ..width = width
      ..height = height
      ..textDirection = Directionality.of(context);
  }
}

class RenderFixPositionedBox extends RenderAligningShiftedBox {
  /// Creates a render object that positions its child.
  RenderFixPositionedBox({
    RenderBox child,
    double width,
    double height,
    AlignmentGeometry alignment = Alignment.center,
    TextDirection textDirection,
  })  : _width = width,
        _height = height,
        super(child: child, alignment: alignment, textDirection: textDirection);

  /// If non-null, sets its width to the child's width plus this value.
  ///
  /// Can have any value.
  double get width => _width;
  double _width;
  set width(double value) {
    if (_width == value) {
      return;
    }
    _width = value;
    markNeedsLayout();
  }

  /// If non-null, sets its height to the child's height plus this value.
  ///
  /// Can have any value.
  double get height => _height;
  double _height;
  set height(double value) {
    if (_height == value) {
      return;
    }
    _height = value;
    markNeedsLayout();
  }

  @override
  void performLayout() {
    final bool shrinkWrapWidth =
        _width != null || constraints.maxWidth == double.infinity;
    final bool shrinkWrapHeight =
        _height != null || constraints.maxHeight == double.infinity;

    if (child != null) {
      child.layout(constraints.loosen(), parentUsesSize: true);
      size = constraints.constrain(Size(
          shrinkWrapWidth ? child.size.width + _width : double.infinity,
          shrinkWrapHeight ? child.size.height + _height : double.infinity));
      alignChild();
    } else {
      size = constraints.constrain(Size(shrinkWrapWidth ? 0.0 : double.infinity,
          shrinkWrapHeight ? 0.0 : double.infinity));
    }
  }

  @override
  void debugPaintSize(PaintingContext context, Offset offset) {
    super.debugPaintSize(context, offset);
    assert(() {
      Paint paint;
      if (child != null && !child.size.isEmpty) {
        Path path;
        paint = Paint()
          ..style = PaintingStyle.stroke
          ..strokeWidth = 1.0
          ..color = const Color(0xFFFFFF00);
        path = Path();
        final BoxParentData childParentData = child.parentData;
        if (childParentData.offset.dy > 0.0) {
          // vertical alignment arrows
          final double headSize =
              math.min(childParentData.offset.dy * 0.2, 10.0);
          path
            ..moveTo(offset.dx + size.width / 2.0, offset.dy)
            ..relativeLineTo(0.0, childParentData.offset.dy - headSize)
            ..relativeLineTo(headSize, 0.0)
            ..relativeLineTo(-headSize, headSize)
            ..relativeLineTo(-headSize, -headSize)
            ..relativeLineTo(headSize, 0.0)
            ..moveTo(offset.dx + size.width / 2.0, offset.dy + size.height)
            ..relativeLineTo(0.0, -childParentData.offset.dy + headSize)
            ..relativeLineTo(headSize, 0.0)
            ..relativeLineTo(-headSize, -headSize)
            ..relativeLineTo(-headSize, headSize)
            ..relativeLineTo(headSize, 0.0);
          context.canvas.drawPath(path, paint);
        }
        if (childParentData.offset.dx > 0.0) {
          // horizontal alignment arrows
          final double headSize =
              math.min(childParentData.offset.dx * 0.2, 10.0);
          path
            ..moveTo(offset.dx, offset.dy + size.height / 2.0)
            ..relativeLineTo(childParentData.offset.dx - headSize, 0.0)
            ..relativeLineTo(0.0, headSize)
            ..relativeLineTo(headSize, -headSize)
            ..relativeLineTo(-headSize, -headSize)
            ..relativeLineTo(0.0, headSize)
            ..moveTo(offset.dx + size.width, offset.dy + size.height / 2.0)
            ..relativeLineTo(-childParentData.offset.dx + headSize, 0.0)
            ..relativeLineTo(0.0, headSize)
            ..relativeLineTo(-headSize, -headSize)
            ..relativeLineTo(headSize, -headSize)
            ..relativeLineTo(0.0, headSize);
          context.canvas.drawPath(path, paint);
        }
      } else {
        paint = Paint()..color = const Color(0x90909090);
        context.canvas.drawRect(offset & size, paint);
      }
      return true;
    }());
  }

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DoubleProperty('widthFactor', _width, ifNull: 'expand'));
    properties.add(DoubleProperty('heightFactor', _height, ifNull: 'expand'));
  }
}
```

My workaround is quite simple tbh. I just followed `Align`'s implementation and modified it so it would use a raw value instead of a percent based `heightFactor` like the one that comes with the `Align` widget.

Hope that helps :)

**Comment by Piinks** [comment] 2019-10-25 18:13
I'm not currently working on this so I'm removing my assignment in case someone else would like to take a look.
After chatting with @goderbauer offline, he suggested the reported behavior is appropriate for the composition of the widgets in the sample snippet. This may be an opportunity to better document how to achieve the desired effect.

**Comment by MohammedYAmmar** [comment] 2020-01-04 19:34
@RollyPeres Think you so much it's work perfectly

**Comment by iapicca** [comment] 2020-04-29 14:08
Hi @RollyPeres 
running the code from your initial post on [dartpad](https://dartpad.dev/82c079711a59940bcc535b834f48d550)
seems to work as intended,
is the issue solved for you?
Thank you

**Comment by iapicca** [comment] 2020-04-29 14:16
Hi @RollyPeres 
I see there's an open [issue](https://github.com/flutter/flutter/issues/27587) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-04-29 14:16 UTC
Labels: a: quality, f: gestures, f: scrolling, framework, in triage, waiting for customer response

**Comment by PearlByte** [comment] 2020-07-02 18:01
This behavior (which in my opinion is an issue) has been a real pain... we are always forced to re-organize or re-write our UI components to make this work and be able to use GestureDetector(). This is especially problematic when we get UI screen designs from Adobe XD or other tools. If you can look into fixing this or adding a global GestureDetector widget that is not affected by transformations that would be ideal.

**Comment by iapicca** [comment] 2020-07-03 08:24
Hi @PearlByte 
you may want to take a look at the new [InteractiveViewer](https://github.com/flutter/flutter/pull/56409)
Thank you

**Comment by YudingZhou** [comment] 2020-07-09 17:26
> This behavior (which in my opinion is an issue) has been a real pain... we are always forced to re-organize or re-write our UI components to make this work and be able to use GestureDetector(). This is especially problematic when we get UI screen designs from Adobe XD or other tools. If you can look into fixing this or adding a global GestureDetector widget that is not affected by transformations that would be ideal.

that is exactly what I am facing. that Adobe Xd uses transform.translate to align the children causes gesture detector not working.  

Do you found any solution here.

**Comment by PearlByte** [comment] 2020-07-09 23:01
Yeah, Adobe XD uses transform.translate for all the controls and that was a problem... I end up just removing the transforms and isolating the control so the GestureDetector works. Another option is to use the Tap callback from Adobe XD for the specific component that you need to wrap with GestureDetector. Someone also suggested InteractiveViewer but I didn't try that yet... I think it's in Beta so I couldn't find that widget in my latest stable Flutter sdk.
