### ISSUE TITLE
In Service，I create a flutterView which i will add it to FrameLayout and display ui with windowmanager，when i attach FlutterEngine to flutterview， it do not work

### ISSUE THREAD

**Issue by tingyouwu** [flutter/flutter#76773] opened 2021-02-25 09:30 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2021-02-25 09:44
Hi @tingyouwu 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by tingyouwu** [comment] 2021-02-25 09:47
> Hi @tingyouwu
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> Thank you

[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.804], locale zh-CN)
    • Flutter version 1.22.3 at C:\src\flutter\flutter_windows_1.22.3-stable\flutter
    • Framework revision 8874f21e79 (4 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by tingyouwu** [comment] 2021-02-25 09:48
> Hi @tingyouwu
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> Thank you

package com.quwan.core.plugin.ttchat_flowball.service;

import android.annotation.SuppressLint;
import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.graphics.PixelFormat;
import android.os.Build;
import android.os.IBinder;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.view.WindowManager;
import android.widget.FrameLayout;

import androidx.annotation.Nullable;
import androidx.core.app.NotificationCompat;

import com.quwan.core.plugin.ttchat_flowball.TtchatFlowballPlugin;
import com.quwan.core.plugin.ttchat_flowball.utils.Commons;
import com.quwan.core.plugin.ttchat_flowball.utils.NumberUtils;
import com.quwan.tt.core.log.Log;

import java.util.HashMap;

import io.flutter.embedding.android.FlutterView;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.FlutterEngineCache;
import io.flutter.embedding.engine.dart.DartExecutor;

import static com.quwan.core.plugin.ttchat_flowball.utils.Constants.INTENT_EXTRA_PARAMS_MAP;
import static com.quwan.core.plugin.ttchat_flowball.utils.Constants.KEY_HEIGHT;
import static com.quwan.core.plugin.ttchat_flowball.utils.Constants.KEY_WIDTH;

public class FlowBallService extends Service implements View.OnTouchListener {

    private static final String TAG = FlowBallService.class.getSimpleName();
    public static final String CHANNEL_ID = "ForegroundServiceChannel";
    private final static int NOTIFICATION_ID = 1;
    public static final String INTENT_EXTRA_IS_UPDATE_WINDOW = "IsUpdateWindow";
    public static final String INTENT_EXTRA_IS_CLOSE_WINDOW = "IsCloseWindow";

    private WindowManager wm;

    private int windowWidth;
    private int windowHeight;

    private FrameLayout windowView;
    // 承接Flutter容器
    private FlutterView flutterView;

    private float offsetX;
    private float offsetY;
    private int originalXPos;
    private int originalYPos;
    private boolean moving;

    private Context mContext;

    @Override
    public void onCreate() {
        createNotificationChannel();
        Intent notificationIntent = new Intent(this, TtchatFlowballPlugin.class);
        PendingIntent pendingIntent = PendingIntent.getActivity(this,
                0, notificationIntent, 0);
        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle("TTChat FlowBall is running")
//                .setSmallIcon(R.drawable.ic_desktop_windows_black_24dp)
                .setContentIntent(pendingIntent)
                .build();
        startForeground(NOTIFICATION_ID, notification);
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        //Toast.makeText(this, "service starting", Toast.LENGTH_SHORT).show();
        if (null != intent && intent.getExtras() != null) {
            @SuppressWarnings("unchecked")
            HashMap<String, Object> paramsMap = (HashMap<String, Object>) intent.getSerializableExtra(INTENT_EXTRA_PARAMS_MAP);
            mContext = this;
            boolean isCloseWindow = intent.getBooleanExtra(INTENT_EXTRA_IS_CLOSE_WINDOW, false);
            if (!isCloseWindow) {
                assert paramsMap != null;
                boolean isUpdateWindow = intent.getBooleanExtra(INTENT_EXTRA_IS_UPDATE_WINDOW, false);
                if (isUpdateWindow && windowView != null) {
                    updateWindow(paramsMap);
                } else {
                    createWindow(paramsMap);
                }
            } else {
                closeWindow(true);
            }
        }
        return START_STICKY;
    }

    private void createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel serviceChannel = new NotificationChannel(
                    CHANNEL_ID,
                    "Foreground Service Channel",
                    NotificationManager.IMPORTANCE_DEFAULT
            );
            NotificationManager manager = getSystemService(NotificationManager.class);
            assert manager != null;
            manager.createNotificationChannel(serviceChannel);
        }
    }

    private void setWindowManager() {
        if (wm == null) {
            wm = (WindowManager) getSystemService(Context.WINDOW_SERVICE);
        }
    }

    private void setWindowLayoutFromMap(HashMap<String, Object> paramsMap) {
        windowWidth = NumberUtils.getInt(paramsMap.get(KEY_WIDTH));
        windowHeight = NumberUtils.getInt(paramsMap.get(KEY_HEIGHT));

        FlutterEngine flutterEngine = FlutterEngineCache.getInstance().get("tt_engine_id");
        if (flutterEngine == null) {
            Log.INSTANCE.e(TAG, "Can not find Cache Flutter Engine while engineId = tt_engine_id");
        } else {
            if(flutterView == null) {
                flutterView = new FlutterView(this);
                Log.INSTANCE.i(TAG, "Attaching FlutterEngine to FlutterView.");
                flutterView.attachToFlutterEngine(flutterEngine);
            }
        }
    }

    private WindowManager.LayoutParams getLayoutParams() {
        final WindowManager.LayoutParams params;
        params = new WindowManager.LayoutParams();
        params.width = WindowManager.LayoutParams.MATCH_PARENT;
        params.height = 400;
        params.format = PixelFormat.TRANSLUCENT;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            params.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
            params.flags = WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL | WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED | WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE;
        } else {
            params.type = WindowManager.LayoutParams.TYPE_SYSTEM_ALERT | WindowManager.LayoutParams.TYPE_SYSTEM_OVERLAY;
            params.flags = WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL | WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE;
        }
        params.gravity = Gravity.TOP;
        params.x = 0;
        params.y = 0;
        return params;
    }

    @SuppressLint("ClickableViewAccessibility")
    private void setWindowView(WindowManager.LayoutParams params, boolean isCreate) {
        boolean isEnableDraggable = true;//params.width == WindowManager.LayoutParams.MATCH_PARENT;
        if (isCreate) {
            windowView = new FrameLayout(mContext);
        }
//        windowView.setBackgroundColor(Color.WHITE);
        windowView.setLayoutParams(params);
        windowView.removeAllViews();
        if (flutterView != null)
            flutterView.setLayoutParams(new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, 500));
            windowView.addView(flutterView);
        if (isEnableDraggable)
            windowView.setOnTouchListener(this);
    }

    private void createWindow(HashMap<String, Object> paramsMap) {
        closeWindow(false);
        setWindowManager();
        setWindowLayoutFromMap(paramsMap);
        WindowManager.LayoutParams params = getLayoutParams();
        setWindowView(params, true);
        wm.addView(windowView, params);
    }

    private void updateWindow(HashMap<String, Object> paramsMap) {
        setWindowLayoutFromMap(paramsMap);
        WindowManager.LayoutParams params = (WindowManager.LayoutParams) windowView.getLayoutParams();
        params.width = (windowWidth == 0) ? WindowManager.LayoutParams.MATCH_PARENT : Commons.getPixelsFromDp(mContext, windowWidth);
        params.height = (windowHeight == 0) ? WindowManager.LayoutParams.WRAP_CONTENT : Commons.getPixelsFromDp(mContext, windowHeight);
        setWindowView(params, false);
        wm.updateViewLayout(windowView, params);
    }

    private void closeWindow(boolean isEverythingDone) {
        Log.INSTANCE.i(TAG, "Closing the overlay window");
        try {
            if (wm != null) {
                if (windowView != null) {
                    wm.removeView(windowView);
                    windowView = null;
                }
            }
            wm = null;
        } catch (IllegalArgumentException e) {
            Log.INSTANCE.e(TAG, "view not found");
        }
        if(isEverythingDone){
            stopSelf();
        }
    }

    @SuppressLint("ClickableViewAccessibility")
    @Override
    public boolean onTouch(View v, MotionEvent event) {
        if (null != wm) {
            if (event.getAction() == MotionEvent.ACTION_DOWN) {
                float x = event.getRawX();
                float y = event.getRawY();
                moving = false;
                int[] location = new int[2];
                windowView.getLocationOnScreen(location);
                originalXPos = location[0];
                originalYPos = location[1];
                offsetX = originalXPos - x;
                offsetY = originalYPos - y;
            } else if (event.getAction() == MotionEvent.ACTION_MOVE) {
                float x = event.getRawX();
                float y = event.getRawY();
                WindowManager.LayoutParams params = (WindowManager.LayoutParams) windowView.getLayoutParams();
                int newX = (int) (offsetX + x);
                int newY = (int) (offsetY + y);
                if (Math.abs(newX - originalXPos) < 1 && Math.abs(newY - originalYPos) < 1 && !moving) {
                    return false;
                }
                params.x = newX;
                params.y = newY;
                wm.updateViewLayout(windowView, params);
                moving = true;
            } else if (event.getAction() == MotionEvent.ACTION_UP) {
                return moving;
            }
        }
        return false;
    }

    @Override
    public void onDestroy() {
        //Toast.makeText(this, "service done", Toast.LENGTH_SHORT).show();
        Log.INSTANCE.i(TAG, "Destroying the overlay window service");
        NotificationManager notificationManager = (NotificationManager) getApplicationContext().getSystemService(Context.NOTIFICATION_SERVICE);
        assert notificationManager != null;
        notificationManager.cancel(NOTIFICATION_ID);
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}

**Comment by pedromassangocode** [comment] 2021-02-25 12:02
Hi @tingyouwu 
Your Flutter version is four months old, please upgrade and try again.
If you still facing this issue, please provide your `flutter doctor -v`.

Note: if your issue is related to android code, it is easy to just provide a complete sample project that reproduce the issue.

Thank you

**Comment by tingyouwu** [comment] 2021-02-25 12:17
> Hi @tingyouwu
> Your Flutter version is four months old, please upgrade and try again.
> If you still facing this issue, please provide your `flutter doctor -v`.
> 
> Note: if your issue is related to android code, it is easy to just provide a complete sample project that reproduce the issue.
> 
> Thank you

Hello, the sample project is in this url  https://github.com/tingyouwu/flowball
please help to check it, thank you

> Hi @tingyouwu
> Your Flutter version is four months old, please upgrade and try again.
> If you still facing this issue, please provide your `flutter doctor -v`.
> 
> Note: if your issue is related to android code, it is easy to just provide a complete sample project that reproduce the issue.
> 
> Thank you

Hello, the sample project is in this url  https://github.com/tingyouwu/flowball
please help to check it, thank you

**Comment by tingyouwu** [comment] 2021-02-25 13:29
> Hi @tingyouwu
> Your Flutter version is four months old, please upgrade and try again.
> If you still facing this issue, please provide your `flutter doctor -v`.
> 
> Note: if your issue is related to android code, it is easy to just provide a complete sample project that reproduce the issue.
> 
> Thank you

I have update flutter sdk to 1.22.6 and check this issue ，but it still do not work，sadly。。

**Comment by tingyouwu** [comment] 2021-02-25 13:33
> Hi @tingyouwu
> Your Flutter version is four months old, please upgrade and try again.
> If you still facing this issue, please provide your `flutter doctor -v`.
> 
> Note: if your issue is related to android code, it is easy to just provide a complete sample project that reproduce the issue.
> 
> Thank you

when I check it，I find this log：

2021-02-25 21:32:32.961 28637-28678/com.quwan.core.plugin.ttchat_flowball_example I/flutter: [INFO:persistent_cache.cc(205)] No sksl asset found.
2021-02-25 21:32:32.961 28637-28678/com.quwan.core.plugin.ttchat_flowball_example I/flutter: [INFO:gpu_surface_gl.cc(90)] Found 0 SkSL shaders; precompiled 0

but I do not what means

**Comment by pedromassangocode** [comment] 2021-02-26 08:42
Hi @tingyouwu 
Can you please provide the steps to reproduce the issue and what is the actual vs expected results?

I was not able to run your project, it looks like your dependency is in a private repository.

```console
Git error. Command: `git clone --mirror git@gitlab.ttyuyin.com:azeroth/app/logger_plugin.git /Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/logger_plugin-73823b01a41ea800de19eb01a8c18948eed9a2f1`
stdout: 
stderr: Cloning into bare repository '/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/logger_plugin-73823b01a41ea800de19eb01a8c18948eed9a2f1'...
ssh: connect to host gitlab.ttyuyin.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

Thank you

**Comment by tingyouwu** [comment] 2021-02-26 08:47
> Hi @tingyouwu
> Can you please provide the steps to reproduce the issue and what is the actual vs expected results?
> 
> I was not able to run your project, it looks like your dependency is in a private repository.
> 
> ```
> Git error. Command: `git clone --mirror git@gitlab.ttyuyin.com:azeroth/app/logger_plugin.git /Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/logger_plugin-73823b01a41ea800de19eb01a8c18948eed9a2f1`
> stdout: 
> stderr: Cloning into bare repository '/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/logger_plugin-73823b01a41ea800de19eb01a8c18948eed9a2f1'...
> ssh: connect to host gitlab.ttyuyin.com port 22: Operation timed out
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> exit code: 128
> ```
> 
> Thank you

Please check it again， I have remove logger_plugin

**Comment by tingyouwu** [comment] 2021-02-26 10:23
> Hi @tingyouwu
> Can you please provide the steps to reproduce the issue and what is the actual vs expected results?
> 
> I was not able to run your project, it looks like your dependency is in a private repository.
> 
> ```
> Git error. Command: `git clone --mirror git@gitlab.ttyuyin.com:azeroth/app/logger_plugin.git /Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/logger_plugin-73823b01a41ea800de19eb01a8c18948eed9a2f1`
> stdout: 
> stderr: Cloning into bare repository '/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/logger_plugin-73823b01a41ea800de19eb01a8c18948eed9a2f1'...
> ssh: connect to host gitlab.ttyuyin.com port 22: Operation timed out
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> exit code: 128
> ```
> 
> Thank you

Thank You Very Much，I have know this reason and fix it in java code。

// Always schedule a frame when the app does become active as per API
  // recommendation
  // https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622956-applicationdidbecomeactive?language=objc
  if (state == "AppLifecycleState.resumed" && have_surface_) {
    ScheduleFrame();
  }

it must call flutterEngine.getLifecycleChannel().appIsResumed() to notify flutter engine to render UI

**Comment by pedromassangocode** [comment] 2021-02-26 12:41
Hi @tingyouwu 
Is this issue solved?

**Comment by tingyouwu** [comment] 2021-02-26 12:43
> Hi @tingyouwu
> Is this issue solved?

yes fix it. it related with AppLifeCycle

**Comment by pedromassangocode** [comment] 2021-02-26 12:52
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2021-02-26 12:52 UTC
Labels: in triage
