### ISSUE TITLE
CanvasKit crashes on app startup for some users

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#62043] opened 2020-07-22 16:24 UTC
Some users are seeing CanvasKit crashes at startup due to problems with CanvasKit creating a WebGl contexts. Interestingly non-flutter WebGL applications run alright on these machines. Disabling hardware acceleration in Chrome works around the problem for at least some users so it may be an Emscripten + WebGL issue.

To repro:
OS: Windows 7
Machine: Lenovo T430 series
https://github.com/flutter/devtools/issues/2125
Open Dart DevTools and no UI renders but about 80 errors are logged to the console related to failing to create WebGL contexts.

Fyi: @hterkelsen

**Comment by yjbanov** [comment] 2020-08-11 00:40
https://github.com/flutter/flutter/pull/63153 has landed. Can you please verify if this is still an issue?

**Comment by yjbanov** [comment] 2020-08-11 00:42
The reason I think https://github.com/flutter/flutter/pull/63153 may fix the issue is because it contains https://github.com/flutter/engine/pull/20306. My hypothesis is that the Windows 7 issue is the same as the Moto E5 issue where we're incorrectly determining that WebGL is not supported.

**Comment by yjbanov** [comment] 2020-08-30 18:31
Considering this issue as fixed based on feedback from https://github.com/flutter/devtools/issues/2125#issuecomment-676513914

**Closed by yjbanov** 2020-08-30 18:31 UTC
Labels: P3, customer: ddt, customer: web10, e: web_canvaskit, passed first triage, platform-web
