### ISSUE TITLE
I can't run flutter_gallery

### ISSUE THREAD

**Issue by chenchongyu** [flutter/flutter#35965] opened 2019-07-11 07:57 UTC
## Steps to Reproduce
I can't run the flutter_gallery demo.
this is the steps I done.
1. checkout from https://github.com/flutter/flutter.git
2. cd flutter/examples/flutter_gallery
3. flutter run

## Logs

```
error infomation:
Because flutter_gallery depends on flutter_goldens any from sdk which depends on test_api 0.2.6, test_api 0.2.6 is required.
So, because flutter_gallery depends on test_api 0.2.5, version solving failed.
```

```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.12.6 16G1618, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/didi/Documents/flutter
    • Framework revision 7a4c33425d (2 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/didi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2017.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • EDI AL10 • 8DF6R17316001370 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 4 categories.

```

**Comment by dnfield** [comment] 2019-07-11 08:06
I'm not able to reproduce this.  Can you verify that your local checkout matches https://github.com/flutter/flutter/blob/master/packages/flutter_goldens/pubspec.yaml#L32 ?

**Comment by chenchongyu** [comment] 2019-07-11 08:13
> I'm not able to reproduce this. Can you verify that your local checkout matches https://github.com/flutter/flutter/blob/master/packages/flutter_goldens/pubspec.yaml#L32 ?

mine is test_api: 0.2.5 too

**Comment by dnfield** [comment] 2019-07-11 19:33
Can you see if this happening on the latest stable version?  You're on the previous one.

**Comment by chenchongyu** [comment] 2019-07-12 02:57
> Can you see if this happening on the latest stable version? You're on the previous one.

Can you send me the link of the latest stable version ?
It's not the https://github.com/flutter/flutter.git?

**Comment by dnfield** [comment] 2019-07-12 03:03
```
flutter channel stable
flutter upgrade
``` 
should do it

**Comment by chenchongyu** [comment] 2019-07-12 03:09
> ```
> flutter channel stable
> flutter upgrade
> ```
> 
> should do it

Thanks so much,I will try it.

**Comment by chenchongyu** [comment] 2019-07-12 03:21
> ```
> flutter channel stable
> flutter upgrade
> ```
> 
> should do it

after I do this and run flutter run,I get this:
```
Because every version of flutter_goldens from sdk depends on pedantic 1.7.0 and flutter_gallery depends on pedantic 1.8.0+1, flutter_goldens from sdk is forbidden.
So, because flutter_gallery depends on flutter_goldens any from sdk, version solving failed.

```

**Comment by dnfield** [comment] 2019-07-12 03:27
@jonahwilliams do you know what's going on here?

**Comment by chenchongyu** [comment] 2019-07-12 03:29
But I open flutter_goldens/pubspec.yaml ,the Dependence is pedantic: 1.8.0+1 too。Is there any cache I need to clear ?

**Comment by jonahwilliams** [comment] 2019-07-12 03:36
Since both `flutter_goldens` and  `flutter_gallery` depend on `pedantic` 1.8.0+1 in the latest stable, I'm going to guess there were some local modifications made to the flutter checkout, or else the upstream used is not correct

**Comment by chenchongyu** [comment] 2019-07-12 03:41
> Since both `flutter_goldens` and `flutter_gallery` depend on `pedantic` 1.8.0+1 in the latest stable, I'm going to guess there were some local modifications made to the flutter checkout, or else the upstream used is not correct

Thanks for reply.

I think there are no modifications to my local flutter.
Here is my local flutter status.
```
~/Documents/flutter$ git status
On branch stable
Your branch is up-to-date with 'origin/stable'.

nothing to commit, working tree clean
```

**Comment by jonahwilliams** [comment] 2019-07-12 03:46
Is `flutter` coming from your checkout of flutter at `~/Documents/flutter/bin/flutter` ?

**Comment by chenchongyu** [comment] 2019-07-12 03:58
> Is `flutter` coming from your checkout of flutter at `~/Documents/flutter/bin/flutter` ?

Ah，I get! I run the `~/Documents/flutter/bin/flutter`  demo is OK，I‘m so sorry to trouble u with the low-grade question. Amazing for ur quick reply. Thanks again.@jonahwilliams @dnfield

**Comment by jonahwilliams** [comment] 2019-07-12 04:04
It's okay! I wonder what we could do to better catch this error

**Comment by dnfield** [comment] 2019-07-12 04:08
Check the cwd, if it's a flutter checkout that isn't this checkout print a warning?

**Comment by jonahwilliams** [comment] 2019-07-12 04:10
We have a check that looks if the current flutter root is the same as the flutter root in the app's pubspec file. I'll look into why that wasn't working here

**Comment by reedom** [comment] 2019-07-17 02:54
I'm stuck with the same issue.
> > Is flutter coming from your checkout of flutter at ~/Documents/flutter/bin/flutter ?

> Ah，I get! I run the ~/Documents/flutter/bin/flutter demo is OK，

I didn't get the point what was the cause.
What should I do?

```
$ pwd
~/Documents/src/projects/flutter/flutter/examples/flutter_gallery

$ which flutter
~/Documents/src/flutter/bin/flutter

$ ~/Documents/src/flutter/bin/flutter pub get
Because every version of flutter_goldens from sdk depends on pedantic 1.7.0 and flutter_gallery depends on pedantic 1.8.0+1, flutter_goldens from sdk is forbidden.
So, because flutter_gallery depends on flutter_goldens any from sdk, version solving failed.
Running "flutter pub get" in flutter_gallery...                         
pub get failed (1)

$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-JP)
    • Flutter version 1.7.8+hotfix.3 at /Users/tohru/Documents/src/flutter
    • Framework revision b712a172f9 (7 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tohru/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[!] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • somewhere • e50bff22d30e2ab4718fa50df2df3683084977d4 • ios • iOS 12.3.1
```

**Comment by obiwan007** [comment] 2019-07-21 08:16
I had the same error. Just checkout the right branch solved it for me.
If you just clone the flutter git repo, it is on master. As you installed the stable flutter binaries this will not work together.
git checkout stable helped in my case...

**Comment by steptan** [comment] 2019-07-24 14:32
In my case, none of these solutions worked. 

[BAD:] for convenience I had symlinked flutter_gallery:
```flutter_gallery -> flutter/examples/flutter_gallery```

trying to ```flutter run``` from there somehow borked everything and caused the above error. Being new to flutter, I had no idea how to track this down.

Then, someone recommended running flutter_gallery from their flutter install. In my case, a simple
```
cd ~/flutter/examples/flutter_gallery
flutter run
```

fixed it

**Comment by dvirgiln** [comment] 2020-03-03 12:40
Is there any way to run this flutter project? I am facing the same problem. This issue has been opened since middle 2019.

**Comment by pedromassangocode** [comment] 2020-09-09 14:02
Hi @chenchongyu 
Are you still have this issue?

**Comment by darshankawar** [comment] 2020-09-30 11:00
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-30 11:00 UTC
Labels: f: material design, framework, team: gallery, waiting for customer response
