### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by Nishit-Chauhan** [flutter/flutter#25331] opened 2018-12-13 16:43 UTC
## Logs

```
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip
                     ...................................................................

                     ...................................................................
                     .................

                     Exception in thread "main" javax.net.ssl.SSLException: Connection
                     has been shutdown: javax.net.ssl.SSLException:
                     java.net.SocketException: Connection reset
                     	at
                     	sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1551)
                     	at
                     	sun.security.ssl.AppInputStream.available(AppInputStream.java:60)
                     	at
                     	java.io.BufferedInputStream.available(BufferedInputStream.java:410
                     	)
                     	at sun.net.www.MeteredStream.available(MeteredStream.java:170)
                     	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:85)
                     	at java.io.FilterInputStream.close(FilterInputStream.java:181)
                     	at
                     	sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(
                     	HttpURLConnection.java:3448)
                     	at org.gradle.wrapper.Download.downloadInternal(Download.java:77)
                     	at org.gradle.wrapper.Download.download(Download.java:44)
                     	at org.gradle.wrapper.Install$1.call(Install.java:61)
                     	at org.gradle.wrapper.Install$1.call(Install.java:48)
                     	at
                     	org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFile
                     	AccessManager.java:65)
                     	at org.gradle.wrapper.Install.createDist(Install.java:48)
                     	at
                     	org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:12
                     	8)
                     	at
                     	org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:6
                     	1)
                     Caused by: javax.net.ssl.SSLException: java.net.SocketException:
                     Connection reset
                     	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
                     	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
                     	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
                     	at
                     	sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:
                     	1880)
                     	at
                     	sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:
                     	1825)
                     	at sun.security.ssl.AppInputStream.read(AppInputStream.java:116)
                     	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
                     	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
                     	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
                     	at java.io.FilterInputStream.read(FilterInputStream.java:133)
                     	at
                     	sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(H
                     	ttpURLConnection.java:3375)
                     	at
                     	sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(H
                     	ttpURLConnection.java:3368)
                     	at org.gradle.wrapper.Download.downloadInternal(Download.java:62)
                     	... 7 more
                     Caused by: java.net.SocketException: Connection reset
                     	at java.net.SocketInputStream.read(SocketInputStream.java:210)
                     	at java.net.SocketInputStream.read(SocketInputStream.java:141)
                     	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
                     	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
                     	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
                     	at
                     	sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
                     	at
                     	sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:9
                     	40)
                     	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
                     	... 14 more
[  +14 ms] "flutter run" took 59,106ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-GB)
    • Flutter version 1.0.0 at /Users/nishit/Developement/flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/nishit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/nishit/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
[flutter_01.log](https://github.com/flutter/flutter/files/2676878/flutter_01.log)

**Comment by RyanDsilva** [comment] 2018-12-13 18:46
Having the same issue!

**Comment by zoechi** [comment] 2018-12-14 13:56
Duplicate of #25117

**Closed by zoechi** 2018-12-14 13:56 UTC
