### ISSUE TITLE
Windows Exe Detected as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by anggoran** [flutter/flutter#118430] opened 2023-01-13 03:43 UTC
![WhatsApp Image 2023-01-13 at 10 33 52](https://user-images.githubusercontent.com/66579441/212232394-15c11bb7-eaea-4f68-9c56-e727be17e273.jpeg)
![WhatsApp Image 2023-01-13 at 10 33 37](https://user-images.githubusercontent.com/66579441/212232402-89c66e72-1769-4139-b0f7-2cfacbe4cd53.jpeg)

### Steps to reproduce
- Compile Flutter App to .Exe with Inno Setup via Github Actions.
- Download the .Exe file from Github Release to your Windows machine that has Windows Security Defender.
- Cannot download the file to the computer because it is detected as `Trojan:Win32/Wacatac.B!ml`.

I'm pretty sure it is a false positive, because if I tried setting it up on my local, it wasn't detected as Trojan. So, it is quite annoying when Windows Consumer see this...

**Comment by exaby73** [comment] 2023-01-13 08:55
Hello @anggoran. Could you provide the Github workflow you're using to compile the windows app?

**Comment by anggoran** [comment] 2023-01-13 11:45
Suree, it's https://gist.github.com/anggoran/3bbe36e18c58657f475d92e744b57f84

**Comment by stuartmorgan** [comment] 2023-01-13 12:10
Duplicate of https://github.com/flutter/flutter/issues/95167

You should contact the developer of the scanning software to report the false positive.

**Closed by stuartmorgan** 2023-01-13 12:10 UTC
Labels: in triage

**Comment by anggoran** [comment] 2023-01-13 12:24
@stuartmorgan I mean this is a built-in software created by Microsoft on Windows 11 machine (especially Microsoft Surface), while the thread that you pointed out is web-based and optional. As person from middle of nowehere, I don't have a meaningful influence to tell them, compared to Flutter backed by known Google.

**Comment by anggoran** [comment] 2023-01-13 12:32
![Screenshot_2023-01-13-19-31-53-62_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/66579441/212321171-216633e3-64e0-4f6d-a35a-fb5656deeef4.jpg)
![IMG_20230113_193129](https://user-images.githubusercontent.com/66579441/212321215-8821e78d-3277-4534-bcc6-0b8be8d17d08.jpg)

**Comment by anggoran** [comment] 2023-01-13 12:35
Please don't close this issue too fast, the scanning software is on many Windows machine 🙏 @stuartmorgan . Though maybe it is on their side, but at least this issue can be tracked

**Comment by anggoran** [comment] 2023-01-13 13:00
https://github.com/flutter/flutter/issues/78463

**Comment by stuartmorgan** [comment] 2023-01-13 14:26
> Though maybe it is on their side, but at least this issue can be tracked

We track things here that are actionable by the Flutter team; the Flutter team can't change the scanning heuristics of software we don't control. You'll need to report this to Microsoft.
