### ISSUE TITLE
【webview_flutter】There is no way to inject JS before the page loads

### ISSUE THREAD

**Issue by coooliang** [flutter/flutter#105202] opened 2022-06-02 08:00 UTC
Dart: （WebView --> onPageFinished:）

```
//exec runJavascript at onPageFinished method
onPageFinished: (String url) {
    _controller.future.then((webViewController) async{
       var js = "window.plugins={}";
       webViewController.runJavascript(js);
    });
},
```

HTML : cannot get objects before the page loads ：

```
$(function(){
   // window.plugins is undefined
})
```

IOS : But in IOS WKWebview can use  WKPreferences injection javascript before the page loads
```
WKUserScript *nativeScript = [[WKUserScript alloc]initWithSource:[NativeJS js] 
injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO];
[userContentController addUserScript:nativeScript];

WKWebViewConfiguration *configuration = [[WKWebViewConfiguration alloc] init];
configuration.userContentController = userContentController;

WKPreferences *preferences = [WKPreferences new];
configuration.preferences = preferences;
configuration.allowsInlineMediaPlayback = YES;

[[WKWebView alloc] initWithFrame:CGRectMake(0, 0, WIDTH, HEIGHT) configuration:configuration];
```

PS: I ended up having to put the JS injection into the onProgress method, but that would have been run multiple times
```
onProgress: (int progress) {
  injectionJS();
  print('WebView is loading (progress : $progress%)');
},
```

**Comment by exaby73** [comment] 2022-06-02 08:32
Hello @coooliang. Does [`onPageStarted`](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebView/onPageStarted.html) serve your purpose?

**Comment by coooliang** [comment] 2022-06-09 08:42
Hello @exaby73 ，I've tried that before，plugins is undefined

```
$(function(){
   // window.plugins is undefined
})
```

**Comment by exaby73** [comment] 2022-06-09 13:34
Could you provide a [minimal, reproducible example][1] demonstrating this error so that we can investigate?

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by coooliang** [comment] 2022-06-24 09:23
@exaby73 ok,this is demo

https://github.com/coooliang/flutter_webview_injection_js_test_demo

**Comment by exaby73** [comment] 2022-06-27 06:50
Hello @coooliang. I was able to get it working by doing the following:

Modify the `assets/html/index.html`, adding `update()`:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width,initial-scale=1.0,user-scalable=0"
        />
        <title>Title</title>
        <script>
            function pageload() {
                var text = "pageload = " + window.myMessage;
                document.getElementById("msg").innerText = text;
            }

            function pageshow() {
                var text = "pageshow = " + window.myMessage;
                document.getElementById("msg2").innerText = text;
            }

            function pagefinish() {
                var text = "pagefinish = " + window.myMessage;
                document.getElementById("msg3").innerText = text;
            }

            // Add this function
            function update() {
                const text = "update = " + window.myMessage;
                document.getElementById("msg4").innerText = text;
            }
        </script>
    </head>
    <body onload="pageload()" onpageshow="pageshow()">
        hello world <br />
        <span id="msg"></span><br />
        <span id="msg2"></span><br />
        <span id="msg3"></span><br />
        <span id="msg4"></span><br />
    </body>
</html>

<script>
    pagefinish();
</script>
```

Then modify `_injectionJS()` to call the update method:

```dart
  _injectionJS() {
    var js = "if(!window.myMessage) window.myMessage='321';update();";
    _webViewController.runJavascript(js);
  }
```

I believe that js in `_injectionJS()` is being called after `onload` and `onpageshow` which is why you get `undefined`.

Since this is not a bug, I am closing this issue.

**Closed by exaby73** 2022-06-27 06:50 UTC
Labels: in triage

**Comment by Nkwachi-N** [comment] 2022-06-28 07:22
Is there a solution for when you don't have access to the html?

**Comment by exaby73** [comment] 2022-06-28 08:21
@Nkwachi-N I don't believe so. Since you are running JS "remotely", you'd expect that you can edit the HTML on where you are running it. I'm not sure how you'd approach this if you do not have access to the HTML.

**Comment by coooliang** [comment] 2022-06-29 02:25
> exaby73

Hello , How can I get injected code before onload, because ios native use WKUserScriptInjectionTimeAtDocumentStar can be implemented

```
WKUserScript *nativeScript = [[WKUserScript alloc]initWithSource:[NativeJS js] 
injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO];
[userContentController addUserScript:nativeScript];

WKWebViewConfiguration *configuration = [[WKWebViewConfiguration alloc] init];
configuration.userContentController = userContentController;

WKPreferences *preferences = [WKPreferences new];
configuration.preferences = preferences;
configuration.allowsInlineMediaPlayback = YES;

[[WKWebView alloc] initWithFrame:CGRectMake(0, 0, WIDTH, HEIGHT) configuration:configuration];

```

Because in complex business, we need to use JS to communicate with native

```
$(function(){
   // window.plugins is undefined
})
```

**Comment by coooliang** [comment] 2022-06-29 02:26
> exaby73

Hello , How can I get injected code before onload, because ios native use WKUserScriptInjectionTimeAtDocumentStar can be implemented

```
WKUserScript *nativeScript = [[WKUserScript alloc]initWithSource:[NativeJS js] 
injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO];
[userContentController addUserScript:nativeScript];

WKWebViewConfiguration *configuration = [[WKWebViewConfiguration alloc] init];
configuration.userContentController = userContentController;

WKPreferences *preferences = [WKPreferences new];
configuration.preferences = preferences;
configuration.allowsInlineMediaPlayback = YES;

[[WKWebView alloc] initWithFrame:CGRectMake(0, 0, WIDTH, HEIGHT) configuration:configuration];

```

Because in complex business, we need to use JS to communicate with native

```
$(function(){
   // window.plugins is undefined
})
```

**Comment by exaby73** [comment] 2022-06-29 07:05
@coooliang You can refer code from https://github.com/flutter/flutter/issues/101195 if it helps
