### ISSUE TITLE
Mouse hover is not working in flutter web.

### ISSUE THREAD

**Issue by Yuvaraj-Gajaraj** [flutter/flutter#62947] opened 2020-08-05 06:16 UTC
## Steps to Reproduce

1. Run the project by run command `flutter run -d chrome`.
2. [Uploading mouse_interaction.zip…]()   Here is a sample.
3. Step to reproduce : 
- After running the project just tap on the screen then it shows the tap position.

- Then move the mouse pointer over the screen it doesn't show any position.

    
**Note:** I have included the `MouseRegion` widget before the `Listener` if I include `MouseRegion` after the `Listener` mouse hover is working. But I want both MouseRegion and Listener working. I have checked this with the flutter version 1.19.0-4.3.pre, both Mouse and listener is working fine. But in the latest flutter beta, both are not working only the last widget gets work.

**Expected results:** 

- Want to get both mouse and listener position.

**Actual results:** 

- But, I get a listener position only.

<details>
  <summary>Logs</summary>

```
PS D:\Dart\mouse_interaction> flutter analyze
Analyzing mouse_interaction...
No issues found! (ran in 2.6s)
```

```
PS D:\Dart\mouse_interaction> flutter doctor -v
[√] Flutter (Channel beta, 1.20.0-7.4.pre, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.20.0-7.4.pre at C:\src\flutter
    • Framework revision 916c3ac648 (4 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\AdminUser\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.47.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.1

[√] Connected device (3 available)
    • Redmi Note 6 Pro (mobile) • 53a1093e   • android-arm64  • Android 9 (API 28)
    • Web Server (web)          • web-server • web-javascript • Flutter Tools
    • Chrome (web)              • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-08-05 11:24
Hi @Yuvaraj-Gajaraj 
The link you provided does not contains a reproducible code of the issue, please provide that code to help you.
thank you.

**Comment by Yuvaraj-Gajaraj** [comment] 2020-08-05 11:28
Hi, @pedromassangocode  Thanks for your reply,

Here is the code snippet 
```
import 'package:flutter/material.dart';

import 'package:flutter/widgets.dart';

void main() => runApp(MyApp());

/// This Widget is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  
  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  double x = 0.0;
  double y = 0.0;
  String eventType = 'No event';

  @override
  Widget build(BuildContext context) {
    return Container(
            child: Stack(
              children: <Widget>[
                Text('$eventType : ($x,$y)',style: const TextStyle(fontSize: 28,fontWeight: FontWeight.bold),),
                MouseRegion(
                  child: Container(
                    height: MediaQuery.of(context).size.height,
                    width: MediaQuery.of(context).size.width,
                    decoration: const BoxDecoration(color: Colors.transparent)
                  ),
                    onHover: (PointerEvent event) {
                      setState(() {
                        x = event.position.dx.roundToDouble();
                        y = event.position.dy.roundToDouble();
                        eventType = 'Mouse';
                      });
                    },
                ),
                Listener(
                  child: Container(
                  height: MediaQuery.of(context).size.height,
                  width: MediaQuery.of(context).size.width,
                  decoration: const BoxDecoration(color: Colors.transparent)),
                  onPointerDown: (PointerDownEvent event) {
                    setState(() {
                      x = event.position.dx.roundToDouble();
                      y = event.position.dy.roundToDouble();
                      eventType = 'Listener';
                    });
                  },
                ),
              ],
            ),
          );
  }
}
```

**Comment by himanshusharma89** [comment] 2020-08-06 05:29
I guess because you are using Stack, the Listener widget containing the Container is on top of the Stack Tree. That is why the MouseRegion is not working.

**Comment by pedromassangocode** [comment] 2020-08-06 08:28
Hi @Yuvaraj-Gajaraj 
Does the code bellow helps you?

```dart
import 'package:flutter/material.dart';

import 'package:flutter/widgets.dart';

void main() => runApp(MyApp());

/// This Widget is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  double x = 0.0;
  double y = 0.0;
  String eventType = 'No event';

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onHover: (PointerEvent event) {
        setState(() {
          x = event.position.dx.roundToDouble();
          y = event.position.dy.roundToDouble();
          eventType = 'Mouse';
        });
      },
      child: Container(
        child: Stack(
          children: <Widget>[
            Text('$eventType : ($x,$y)',style: const TextStyle(fontSize: 28,fontWeight: FontWeight.bold),),
            Container(
                height: MediaQuery.of(context).size.height,
                width: MediaQuery.of(context).size.width,
                decoration: const BoxDecoration(color: Colors.transparent)
            ),
            Listener(
              child: Container(
                  height: MediaQuery.of(context).size.height,
                  width: MediaQuery.of(context).size.width,
                  decoration: const BoxDecoration(color: Colors.transparent)),
              onPointerDown: (PointerDownEvent event) {
                setState(() {
                  x = event.position.dx.roundToDouble();
                  y = event.position.dy.roundToDouble();
                  eventType = 'Listener';
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment] 2020-09-02 10:11
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-02 10:11 UTC
Labels: in triage, waiting for customer response
