### ISSUE TITLE
[IOS] App runs fine in Xcode in all Modes, But apple verification team says that my app failed to progress past the launch screen

### ISSUE THREAD

**Issue by Badis14** [flutter/flutter#100617] opened 2022-03-23 13:37 UTC
Ps :it is validated  by google it's on google play but i didn't figure out a solution with apple
![1](https://user-images.githubusercontent.com/73723266/159712295-8252ad47-07bb-47db-9a9c-95b47a8dc792.png)
![3](https://user-images.githubusercontent.com/73723266/159712346-0087df62-d975-4299-bef0-26cc21f3b9fe.png)
![4](https://user-images.githubusercontent.com/73723266/159712363-57018f80-4f20-4213-92d2-ea3b59923687.png)

**Comment by maheshmnj** [comment] 2022-03-24 06:08
Hi @Badis14, Thanks for filing the issue. Does your app run fine on the reproducible device/simulator (Ipad IOS 15.4)? 
Please also share the output of `flutter doctor -v` of the device where the app was compiled.

**Comment by maheshmnj** [comment] 2022-03-29 10:27
Thanks for the update @Badis14, Does the app work fine locally on the simulator or physical device on ios 15.3 / 15.4? if the issue reproduces for you locally Please try upgrading to the latest stable version of flutter `2.10.4`?

**Comment by Badis14** [comment] 2022-03-29 11:11
@maheshmnj  thank you for your reply .
First i can't upgrade the version of flutter 2.10.4 because it is an old project and use some packages that cannot work on 2.10.4,
the app work fine and smooth on both mode release and debug on i.o.s  15.3 for the physical and simulator devices and i uploaded a recording vid to the apple team .
now i noticed that in build settings of Pods file there is no 'interface builder storyboard'
I'm not sure but it may be the problem because the app failed progressing the launch screen

**Comment by maheshmnj** [comment] 2022-03-29 13:47
> the app work fine and smooth on both mode release and debug on i.o.s 15.3 for the physical and simulator devices and i uploaded a recording vid to the apple team .

@Badis14 I am quite not sure where the conflict is since you are able to run the app while the apple team cannot.

> now i noticed that in build settings of Pods file there is no 'interface builder storyboard'

Can you please attach your podfile?

**Comment by Badis14** [comment] 2022-03-29 14:18
@maheshmnj
Podfile
[Podfile.txt](https://github.com/flutter/flutter/files/8372285/Podfile.txt)
Podflie.lock
[Podfile.lock.txt](https://github.com/flutter/flutter/files/8372287/Podfile.lock.txt)

**Comment by maheshmnj** [comment] 2022-03-30 05:36
Thanks for the info @Badis14, Since you are not able to reproduce the issue, I think that this issue is unrelated to flutter meaning changing anything in the flutter sdk or in the documentation won't help fix this issue. Probably the bug is somewhere else in your code.
This issue is not actionable further from our side, So I am going to close this issue for now, if you have any further info or logs that points an issue in flutter feel free to comment on this issue and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-03-30 05:36 UTC
Labels: in triage
