### ISSUE TITLE
[tool_crash] String: <44 characters>

### ISSUE THREAD

**Issue by jagsme** [flutter/flutter#127750] opened 2023-05-27 15:59 UTC
## Command
```
flutter run --host-vmservice-port=8888 --target=auto_qa.dart --profile -d  xxxx --disable-service-auth-codes  --no-build
```

## Steps to Reproduce
1. app already build in profile mode
2. flutter run with specific observatory url
3. app crashed and failed to connect to observatory url

## Logs
String: <44 characters>
```
#0      DartDevelopmentServiceImpl._startDDSServer (package:dds/src/dds_impl.dart:189:7)
<asynchronous suspension>
#1      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:117:7)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#3      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:55:22)
<asynchronous suspension>
#4      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:296:11)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-AE)
    [32m•[39m Flutter version 3.10.0 on channel stable at /Users/sjag5095/Documents/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 84a1e904f4 (3 weeks ago), 2023-05-09 07:41:44 -0700
    [32m•[39m Engine revision d44b5a94c9
    [32m•[39m Dart version 3.0.0
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /Users/sjag5095/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m ANDROID_HOME = /Users/sjag5095/Library/Android/sdk
    [32m•[39m ANDROID_SDK_ROOT = /Users/sjag5095/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E222b
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.76.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.64.0

[32m[✓][39m Proxy Configuration
    [32m•[39m HTTP_PROXY is set

**Comment by danagbemava-nc** [comment] 2023-05-29 06:52
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812.

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-05-29 06:52 UTC
Labels: in triage
