### ISSUE TITLE
[image_picker] ImageResizer.resizeImageIfNeeded (ImageResizer.java:42)

### ISSUE THREAD

**Issue by snoopdoggy322** [flutter/flutter#134125] opened 2023-09-06 09:38 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

image_picker: ^1.0.2

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Steps to reproduce

This problem occurs on some Android devices.
I get this stacktrace from Crashlytics.

### Expected results

Device/Androd-version:

OS version: android10
Model:Huawei Nova 5T

OS version: android13
Model:Galaxy A54 5G

OS version: android6.0
Model:Y5 2017

OS version: android10
Model:Honor 10 Lite

OS version: android8.1.0
Model:Honor 8C

### Actual results
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
       at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:42)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.getResizedImagePath(ImagePickerDelegate.java:18)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:14)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:18)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.lambda$onActivityResult$0(ImagePickerDelegate.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)`

**Comment by dam-ease** [comment] 2023-09-06 13:43
Hi @snoopdoggy322. Thanks for filing this. Can you help with more information on this? More specifically, are you attempting to select Images from Google Photos? Also, can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code and the output of your `flutter doctor -v`?

**Comment by snoopdoggy322** [comment] 2023-09-06 14:30
@dam-ease  
Hello, the fact is that I cannot reproduce this error on any of my devices, I get it in a crash report via Firebase Crashlytics.
I found a similar problem but it's already been solved
https://github.com/flutter/flutter/issues/38775

flutter doctor -v
<details>
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F770820d darwin-arm64, locale ru-RU)
    • Flutter version 3.10.5 on channel stable at /Users/vlad/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/vlad/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • F1415A2B-C884-4C45-80DC-BFB036E7B4D4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</details>

**Comment by dam-ease** [comment] 2023-09-07 07:28
Thanks for your response. Yes, looking through that issue, it seems similar and has been solved, kindly upgrade to the latest versions of Flutter and the image_picker package. Closing this as it seems this has been fixed in the latest versions, If you observe the same issue after the upgrade, kindly comment with any information on what steps might be helpful in reproducing it on our end, so I'll reopen this.
Thank you!

**Closed by dam-ease** 2023-09-07 07:28 UTC
Labels: in triage

**Comment by snoopdoggy322** [comment] 2023-09-07 07:57
@dam-ease 
Judging by this pr(https://github.com/flutter/plugins/pull/2293), this was fixed back in version 0.6.2+1 of the image_picker plugin, in my prod application the image_picker version is used: ^1.0.2 and flutter version 3.10.5.
I assume that updating versions in this situation will not help solve this problem.
Unfortunately, I can't add stable reproducible steps as this issue is not reproducible on my devices, but only on real users in production.

**Comment by dam-ease** [comment] 2023-09-07 09:06
Hi @snoopdoggy322. Can you try to provide more info on actions you are taking with the `image_picker` package or any reproduction steps that might be helpful. For an issue to be workable, we'd need a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and reproduction steps.
Also, you could run `flutter build release -v` to see if we could get helpful info

**Comment by DjordjeMancic97** [comment] 2023-09-18 09:54
Experiencing same issue here, latest flutter and plugin. We are unable to reproduce it ourselves yet

**Comment by stepanov-standy** [comment] 2023-10-01 20:57
The same problem was found from my side also. I still can't reproduce it, but it was fine on Flutter image_picker: ^0.8.7+4. Crashlytics app crashes are reported after switch to 1.0.1 both on iOS and Android. I tries to rollback to ^0.8.7+4, but still see the same crash on it. Can it be due to updated flutter version or another related dependency?

Currently I use flutter 3.10.6
