### ISSUE TITLE
LicenseRegistry.licenses doesn't complete during Driver tests

### ISSUE THREAD

**Issue by chris-rutkowski** [flutter/flutter#57630] opened 2020-05-20 03:20 UTC
The following code:

```
void _start() async {
    var contents = <LicenseItem>[];

    await for (final LicenseEntry license in LicenseRegistry.licenses) {
      final paragraphs = license.paragraphs.map((p) => p.text).toList();
      contents.add(LicenseItem(
        title: license.packages.join(', '),
        body: paragraphs.join('\n\n'),
      ));
    }

    if (disposed) return;
    _itemsController.add(contents);
  }
```

works fine when running the app (debug/release). 

**However during Flutter Driver tests, it never completes.** It should complete in a matter of seconds, but it never completes.

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-TH)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!
```

</details>

**Comment by iapicca** [comment] 2020-05-20 09:09
Hi @chris-rutkowski 
could you please run `flutter upgrade --force`
if the issue persists
please provide a "**runnable**" minimal code sample
Thank you

**Comment by chris-rutkowski** [comment] 2020-05-21 02:53
I've just upgraded the Flutter with force flag, however I experience this issue for long time already on multiple stables and beta channels.

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale en-TH)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

@iapicca here is the demo project
https://github.com/chris-rutkowski/flutter-license-driver-failure

If you run the project on Android Emulator, this is the result:

<img width="505" alt="Screen Shot 2563-05-21 at 09 49 54" src="https://user-images.githubusercontent.com/58718695/82518013-92bc8380-9b48-11ea-993b-5f74008801d2.png">

also check the console log:

```
I/flutter ( 7334): started
I/flutter ( 7334): next item
I/chatty  ( 7334): uid=10133(com.example.licenses) Thread-2 identical 442 lines
I/flutter ( 7334): next item
I/flutter ( 7334): completed
I/flutter ( 7334): Snapshot data length: 444
```

If you run driver tests `flutter drive --target=test_driver/app.dart`

This is the result:

<img width="505" alt="Screen Shot 2563-05-21 at 09 50 45" src="https://user-images.githubusercontent.com/58718695/82518029-9c45eb80-9b48-11ea-8374-29068cbb4a1c.png">

and the console log:

```
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:51600/OnqxMZ5AiIc=/
VMServiceFlutterDriver: Isolate found with number: 2760223258967499
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Waiting for service extension
I/flutter ( 7695): started
VMServiceFlutterDriver: Connected to Flutter application.
00:01 +0: licenses

VMServiceFlutterDriver: waitFor message is taking a long time to complete...
```

**Comment by jonahwilliams** [comment] 2020-05-26 21:08
Duplicate of https://github.com/flutter/flutter/issues/24703

**Closed by jonahwilliams** 2020-05-26 21:08 UTC
Labels: found in release: 1.12, found in release: 1.18, framework, has reproducible steps, t: flutter driver, tool
