### ISSUE TITLE
Rive artifacts after update to 1.17.1

### ISSUE THREAD

**Issue by AtixD** [flutter/flutter#57959] opened 2020-05-25 19:07 UTC
![image](https://user-images.githubusercontent.com/17594120/82837909-3a341000-9ed3-11ea-943b-2b9f8957330e.png)

I have updated from 1.12 to 1.17, but I see artifact on a flare object, this can be seen in the screenshot. This problem only the real device, not simulator. 

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale ru-RU)
    • Flutter version 1.17.1 at /Users/_/development/flutter
    • Framework revision f7a6a7906b (13 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/_/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/_/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.3

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone • ios • iOS 13.4.1

! Doctor found issues in 2 categories.

flare_flutter: ^2.0.1

```
Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.end,
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Row(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            Stack(
              overflow: Overflow.visible,
              alignment: Alignment.center,
              children: <Widget>[
                Positioned(
                  bottom: 80,
                  child: _LockContainer(
                      streamControllerLockedUI: _streamControllerLockedUI, animationController: _animationController),
                ),
                RecorderWrapper(
                  onCancel: onCancel,
                  onStart: onStart,
                  onStop: onStop,
                  onChange: onChange,
                  onLock: onLock,
                  isLock: _isLock,
                  isStart: _isStart,
                  offset: _maxOffset,
                  child: Container(
                    height: 50,
                    width: 50,
                    margin: EdgeInsets.only(left: 20, right: 20, top: 20, bottom: 20),
                    child: Stack(
                      overflow: Overflow.visible,
                      children: <Widget>[
                        Positioned(
                          left: -20,
                          right: -20,
                          top: -20,
                          bottom: -20,
                          child: FlareActor(
                                  "assets/flare/Recorder.flr",
                                  animation: 'idle',
                                ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ],
    );
```

**Comment by TahaTesser** [comment] 2020-05-26 10:22
Hi @AtixD 
For issue related to the 3rd party plugin [flare_flutter](https://pub.dev/packages/flare_flutter) you may want to open an issue in the dedicated [GitHub](https://github.com/2d-inc/Flare-Flutter/issues).

Looks like you already did, please all details on the issue you opened on their GitHub
Closing, as this isn't an issue with Flutter itself, if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-26 10:22 UTC

**Comment by umberto-sonnino** [comment] 2020-07-02 10:02
I've looked into this, and I've been able to reproduce the problem on a physical device (iPad Mini 4 running iOS 13.5.1) running Flutter Stable. Here's two screenshots: [Flutter Stable](https://i.imgur.com/B7SXIPw.png), [Flutter Dev](https://i.imgur.com/A6BUtPf.png).

The iPad was running the following snippet with a `CustomPainter`:

```dart
void main() => runApp(MyPaint());

class MyPaint extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              Expanded(
                child: CustomPaint(
                  foregroundPainter: MyPainter(),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class MyPainter extends CustomPainter {
  Paint _paint = Paint();

  @override
  bool shouldRepaint(CustomPainter oldPainter) => false;

  @override
  void paint(Canvas canvas, Size size) {
    var radius = size.height / 2;
    var center = Offset(size.width / 2, size.height / 2);
    canvas.drawCircle(center, radius, _paint..color = Colors.blue[50]);

    canvas.save();
    canvas.translate(center.dx, center.dy);
    const double padding = 20;
    const arcConstant = 0.55;
    double h = radius - padding;
    double w = h;
    double aw = w * arcConstant;
    double ah = h * arcConstant;
    Path _path = Path()
      ..moveTo(0, h)
      ..cubicTo(aw, h, w, ah, w, 0)
      ..cubicTo(w, -ah, aw, -h, 0, -h)
      ..cubicTo(-aw, -h, -w, -ah, -w, 0)
      ..cubicTo(-w, ah, -aw, h, 0, h)
      ..close();
    canvas.drawPath(_path, _paint..color = Colors.red);
    canvas.restore();
  }
}
```

**Comment by TahaTesser** [comment] 2020-07-02 10:53
@umberto-sonnino 
if it isn't related to Rive, please file a new issue with all the details
Thank you
