### ISSUE TITLE
Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: C:\Users\Pulsara\AppData\Local\Android\Sdk\platform-tools\adb.exe

### ISSUE THREAD

**Issue by PulsaraSandeepa** [flutter/flutter#94300] opened 2021-11-28 05:30 UTC
When I start the project popup shows "Flutter daemon terminate" and when starting the flutter application it shows the "No Connected Devices Found" dialog box. Then I run `flutter doctor -v`  doctor found issues in:

```
Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: C:\Users\Pulsara\AppData\Local\Android\Sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:78:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:413:54)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart)
      <asynchronous suspension>
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:170:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:515:34)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>
```
I already set up the SDK path as `ANDROID_SDK_TOOLS`  in user variables and `tools`, and `platform-tools` in Path. And reinstalled the `platform-tools` as well but did not solve the issue. I cannot figure the solution if anyone can give me a solution it will be really helpful to me.

**Comment by innos123** [comment] 2021-11-28 05:57
> When I start the project popup shows "Flutter daemon terminate" and when starting the flutter application it shows the "No Connected Devices Found" dialog box. Then I run `flutter doctor -v` doctor found issues in:
> 
> ```
> Connected device (the doctor check crashed)
>     X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
>     X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: C:\Users\Pulsara\AppData\Local\Android\Sdk\platform-tools\adb.exe
>     • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>       #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:78:7)
>       <asynchronous suspension>
>       #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:413:54)
>       <asynchronous suspension>
>       #3      Future.wait.<anonymous closure> (dart:async/future.dart)
>       <asynchronous suspension>
>       #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:170:40)
>       <asynchronous suspension>
>       #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:515:34)
>       <asynchronous suspension>
>       #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
>       <asynchronous suspension>
> ```
> 
> I already set up the SDK path as `ANDROID_SDK_TOOLS` in user variables and `tools`, and `platform-tools` in Path. And reinstalled the `platform-tools` as well but did not solve the issue. I cannot figure the solution if anyone can give me a solution it will be really helpful to me.

**Comment by innos123** [comment] 2021-11-28 06:11
> When I start the project popup shows "Flutter daemon terminate" and when starting the flutter application it shows the "No Connected Devices Found" dialog box. Then I run `flutter doctor -v` doctor found issues in:
> 
> ```
> Connected device (the doctor check crashed)
>     X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
>     X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: C:\Users\Pulsara\AppData\Local\Android\Sdk\platform-tools\adb.exe
>     • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>       #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:78:7)
>       <asynchronous suspension>
>       #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:413:54)
>       <asynchronous suspension>
>       #3      Future.wait.<anonymous closure> (dart:async/future.dart)
>       <asynchronous suspension>
>       #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:170:40)
>       <asynchronous suspension>
>       #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:515:34)
>       <asynchronous suspension>
>       #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
>       <asynchronous suspension>
> ```
> 
> I already set up the SDK path as `ANDROID_SDK_TOOLS` in user variables and `tools`, and `platform-tools` in Path. And reinstalled the `platform-tools` as well but did not solve the issue. I cannot figure the solution if anyone can give me a solution it will be really helpful to me.

**Comment by darshankawar** [comment] 2021-11-29 10:37
Closing this as a duplicate of https://github.com/flutter/flutter/issues/72101

**Closed by darshankawar** 2021-11-29 10:37 UTC
Labels: in triage
