### ISSUE TITLE
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride

### ISSUE THREAD

**Issue by asamprabin** [flutter/flutter#82177] opened 2021-05-10 13:08 UTC
Running "flutter pub get" in bookingMobile...
Launching lib/main.dart on iPhone 12 Pro in debug mode...
lib/main.dart:1
Xcode build done.                                           18.0s
Connecting to VM Service at ws://127.0.0.1:49724/TnM3_LReeQs=/ws
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
Lost connection to device.
Exited (sigterm)

Flutter app not working

Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by darshankawar** [comment] 2021-05-10 13:24
@asamprabin 
When do you get this error ? Can you provide `pubspec.yaml` and a complete minimal reproducible code sample that shows this issue ?

**Comment by asamprabin** [comment] 2021-05-10 13:31
@darshankawar I updated my Xcode today. After that I am getting this error. I am using mac book pro m1.

pubspec.yml

name: name
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  numeric_keyboard: ^1.0.0
  url_launcher: ^6.0.0-nullsafety
  youtube_player_flutter: ^7.0.0+7
  carousel_slider: ^3.0.0
  http: ^0.13.1
  shared_preferences: ^2.0.5
  contacts_service: ^0.6.0
  modal_bottom_sheet: ^2.0.0
  country_code_picker: ^2.0.1
  image_picker: ^0.7.4
  permission_handler: ^7.1.0
  flutter_icons: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: SF-Pro-Text-Regular
      fonts:
        - asset: assets/SF-Pro-Text-Regular.otf

    - family: SF-Pro-Text-Bold
      fonts:
        - asset: assets/SF-Pro-Text-Bold.otf

    - family: Calibre-Semibold
      fonts:
        - asset: assets/Calibre Semibold.otf

    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons.ttf

**Comment by cpboyd** [comment] 2021-05-10 17:55
Possible duplicate of #82166 
I'm also seeing these errors when **restarting** but not during a hot reload on iOS Simulators.

**Comment by cpboyd** [comment] 2021-05-12 02:55
@darshankawar After running `flutter upgrade` to the latest `dev` release, the crash doesn't happen anymore.

**Comment by asamprabin** [comment] 2021-05-12 04:23
@darshankawar I created a new project and tried, it worked fine. Even in the old project it was working fine with the iphone. So the problem could be some 3rd party plugins not being supported. Thank you for the support.

@cpboyd dev release may have more bugs. Please be careful

**Comment by darshankawar** [comment] 2021-05-12 05:51
Thanks for confirming @cpboyd and @asamprabin.
Closing this as resolved based on above comment.

**Closed by darshankawar** 2021-05-12 05:51 UTC
Labels: in triage
