### ISSUE TITLE
type `(List<Wrapper<Child>>) => Future<void>` is not a subtype of type `((List<Wrapper<Parent>>) => Future<void>)?`

### ISSUE THREAD

**Issue by albertms10** [flutter/flutter#80939] opened 2021-04-22 11:11 UTC
## Steps to Reproduce

1. Clone [albertms10/cabin_booking](https://github.com/albertms10/cabin_booking/tree/null-safety) (`null-safety` branch)
2. `flutter run` (any device)
3. Go to _Cabins_ page (third item in `NavigationRail`)
4. Add a cabin via the FAB and tap the _add_ button
5. Select the created cabin in the table and edit via the upper action bar

**Expected results:** 
A dialog shows the cabin info ready to be edited.

**Actual results:** 
Nothing happens, as Flutter throws a `_TypeError` exception in the background—for more details, check albertms10/cabin_booking#10.

By the way, it _does_ work as expected by following the same steps in the [`main`](https://github.com/albertms10/cabin_booking/tree/086b28db25c086f7e43c71572fb71db1c95b8223) branch, with Dart SDK `v2.10` and Flutter `v1.22`, so it seems to be related to the new Dart SDK `v2.12` or Flutter `v2.0`.

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type '(List<ItemsTableRow<Cabin>>) => Future<void>' is not a subtype of type
'((List<ItemsTableRow<Item>>) => Future<void>)?'

When the exception was thrown, this was the stack:
#0      _ItemsTableState.build.<anonymous closure> (package:cabin_booking/widgets/item/items_table.dart:267:28)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#5      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#7      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:385:20)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
#9      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#10     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
#11     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
#17     _invoke1 (dart:ui/hooks.dart:180:10)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 3 frames from dart:async)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#5949e
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
No issues found! (ran in 3.6s)
```

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    ca-ES)
    • Flutter version 2.0.5 at /Users/albert/Developer/flutter
    • Framework revision adc687823a (fa 6 dies), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/albert/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment] 2021-04-22 13:01
@albertms10 
Looking at the error you are getting:

`The following _TypeError was thrown while handling a gesture:
type '(List<ItemsTableRow<Cabin>>) => Future<void>' is not a subtype of type
'((List<ItemsTableRow<Item>>) => Future<void>)?'`

The `typeError` gives the information as to why / what could be wrong in the code.  Can you try by adding explicit types to your local variable here to see what types are at each step ?

**Comment by mraleph** [comment] 2021-04-24 05:54
The error is absolutely correct. A function that expects more a concrete subtype is not a subtype of a function type that expects a super type. Think about the following: if you have a function that expects a Dog you can’t use that function in contexts which pass an arbitrary Animal - because Animal is not necessarily a Dog. The other way works though - if you have a function that accepts Animals then you can use it in places which only pass Dogs, because all dogs are animals.

**Comment by albertms10** [comment] 2021-04-24 19:08
Thanks for your explanation, @mraleph, I understand what you mean. Indeed, the `ItemsTable` definition expects an arbitrary `Item` (an abstract class), and the implementation in code uses a child of that class (a `Cabin`).

Here you have some code references to look at.

### Model class definition

```dart
abstract class Item implements Comparable<Item> {
  // ...
}

class Cabin extends Item {
  int number;
  // ...
}
```

### Widget definition

```dart
class ItemsTable<T extends Item> extends StatefulWidget {
  final String Function(ItemsTableRow<T>) itemTitle;
  final List<ItemsTableRow<T>> rows;
  final Future<void> Function(List<ItemsTableRow<T>>)? onEditPressed;
  // ...
}
```

### Usage

```dart
ItemsTable<Cabin>(
  itemTitle: (ItemsTableRow<Cabin> row) => '${row.item.number}',
  // ...
  onEditPressed: (List<ItemsTableRow<Cabin>> selectedRows) async {
    // ...
  },
);

```

**Comment by darshankawar** [comment] 2021-04-26 06:36
Keeping this open for further insights / investigation.

**Comment by mraleph** [comment] 2021-04-26 09:18
I looked at the reproduction, the exception you are getting is being thrown from the following line: 

```dart
widget.onEditPressed?.call(widget._selectedRows)
```

The root cause for getting this exception is due to you not passing `T` down to you state in `createState`:

```dart
  _ItemsTableState createState() => _ItemsTableState();
```

If you change this to 

```dart
  _ItemsTableState createState() => _ItemsTableState<T>();
```

Then things will start working. 

Now let me try to explain on a simple code example why you get this exception. 

```dart
class A<T> {
  final void Function(T) handle;
  A({required this.handle});

  B createB() => B(); // Note: forgot <T> here.
}

class B<T> {
  late A<T> a;
  void delegate(T obj) {
    a.handle(obj);  // (*)
  }
}

void main() {
  final a = A<int>(handle: (i) { print(i); });
  final b = a.createB();
  b.a = a;
  b.delegate(1);
}
```

This code will type check but throw a runtime error: 

```console
╭─~
╰─» dart issue80939.dart
Unhandled exception:
type '(int) => void' is not a subtype of type '(dynamic) => void'
#0      B.delegate (file:///Users/vegorov/issue80939.dart:11:7)
#1      main (file:///Users/vegorov/issue80939.dart:19:5)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

This happens due to a relatively unknown corner case around generics and function types occurring in return types of methods or getters. For non-dynamic invocations of closures Dart's type system guarantees that static types of arguments match static types of the parameters. However this guarantee can't be ensured statically due to covariance of Dart's generics. 

Let's look at the expression: `a.handle(obj);`. All types match _statically_ here. However due to covariance it can be that `T=Object` while `A<T> a` actually contains `A<int>`. In this case a closure invocation arises which does not adhere to types, e.g. `obj` can be any object (even a string `"whatever"`), but `a.handle` is actually a function that expects `int` (because `a` is `A<int>`). 

During design of Dart 2 type system it was decided this this corner case is solved by introducing an implicit check that verifies that `a.handle` runtime type is a subtype of its static type, meaning that `a.handle(...)` actually gets compiled as `(a.handle as void Function(T))(...)` - hence if `T` in `B<T>` is `dynamic` and `T` in `A<T>` is `int` you get a check: `(a.handle as void Function(dynamic))` which throws the exception above. 

The solution is to ensure that `T` matches between `A` and `B`. 

The reason why this worked before is that you did not pass `T=Cabin` to `ItemsTable` before, which meant that both your widget and your state had `T=Item`, but then you changed constructor sites to pass `T=Cabin` to `ItemsTable` but did not change `createState` to pass it further down - which created the discrepancy and got caught by the implicit check. 

Hope this helps. 

I am going to close the issues given that explanation above is exhaustive. But don't hesitate to ask further questions.

**Closed by mraleph** 2021-04-26 09:18 UTC
Labels: a: error message, a: null-safety, dependency: dart, passed first triage

**Comment by albertms10** [comment] 2021-04-26 09:42
Thank you so much, again! I appreciate your time for looking at the code and explaining with such detail that concrete scenario. 😄
