### ISSUE TITLE
Material 3: IconButton default color

### ISSUE THREAD

**Issue by Vorkytaka** [flutter/flutter#118943] opened 2023-01-21 10:50 UTC
Right now, when we set `useMaterial3` as `true`, then `IconButton` starts to set default color for icon.
By default it's `themeData.colorScheme.onSurfaceVariant`.

The problem is we can't use `IconTheme` around `IconButton` for color anymore.
The theme below won't have any effect with `useMaterial3: true`.
```dart
IconTheme(
  data: IconThemeData(
    color: Colors.red,
  ),
  child: IconButton(
    icon: const Icon(Icons.add),
    onPressed: () {},
  ),
)
```

But with old icon button that works fine.
Not sure about Material You specification, but that's look like pretty strange limitation.

**Comment by Vorkytaka** [comment] 2023-01-22 11:49
If that's exactly behavior that Material You said us to do, then, maybe, we can create some `IconButtonTheme` widget, that will have priority over inner default colors inside `_IconButtonM3` and `__IconButtonDefaultsM3`?

**Comment by exaby73** [comment] 2023-01-23 08:18
Hello @Vorkytaka. I can reproduce this issue in stable but looks like this is fixed in the beta and master channels. Since this is fixed, I am closing this issue. Thank you

**Closed by exaby73** 2023-01-23 08:18 UTC
Labels: in triage
