### ISSUE TITLE
Unexpected behavior CustomScrollView with a short list, list jumps up and down with material 3

### ISSUE THREAD

**Issue by JoanSchi** [flutter/flutter#118145] opened 2023-01-07 19:03 UTC
Hi,

I found a unexpected behavior with CustomScrollView and material 3 when the list is very short (shorter than the viewport). If the view is overscrolled, the list starts to stretch as expected with M3. However if the direction is changed the opposite way even slightly, the view jumps back. This feels strange and unnatural, especially in combination with NestedScrollView. 

**Steps to Reproduce**
1. Scroll down and up  (fling up and down), do not end the scroll.
2. The list starts to jump up and down

**Expected results:** 
I expect the same behavior with a list longer than the viewport. If the direction of the overscroll (short list) is the opposite of the initial overscroll then the stretch should be gradually disappear and not jump.

**Actual results:** 
The list starts to jump up and down.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(const AppBarApp());

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const AppBarExample(),
    );
  }
}

class AppBarExample extends StatelessWidget {
  const AppBarExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
            top: false,
            bottom: false,
            child: CustomScrollView(
              slivers: <Widget>[
                SliverPadding(
                  padding: const EdgeInsets.all(8.0),
                  sliver: SliverFixedExtentList(
                    itemExtent: 48.0,
                    delegate: SliverChildBuilderDelegate(
                      (BuildContext context, int index) {
                        return ListTile(
                          title: Text('Item $index'),
                        );
                      },
                      childCount: 2,
                    ),
                  ),
                ),
              ],
            )));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on openSUSE Tumbleweed 6.1.2-1-default, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

[example jump up and down 2.webm](https://user-images.githubusercontent.com/32017307/211412456-e4c0d7be-7a89-4e48-b9ae-4bdd681aa847.webm)

**Comment by huycozy** [comment] 2023-01-09 08:56
@JoanSchi Can you provide a visual for this issue? (a recorded video would be great)
I tested with a list with 2 items and 20 items but couldn't see the wrong behavior:

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/211269597-4f27c338-2095-4463-9f4e-1e2118e13756.mov
</details>

**Comment by JoanSchi** [comment] 2023-01-09 18:44
@huycozy Thank you, I uploaded the demo video in the original message. 

That is strange, in my video the problem is clearly visible, do you use also Channel stable, 3.3.10? I also see it with earlier versions of flutter and on my phone.

**Comment by huycozy** [comment] 2023-01-10 05:31
@JoanSchi I can see the issue now when following your steps ("_keep the mouse down and then move up and down_"). 

And it seems to be only reproducible on Android whilst it works normally on iOS.

Labeling the issue for further investigation from the team. The issue is reproducible on the latest stable and master channels.

<details>
<summary>Demo (Android and iOS)</summary>

| Android | iOS |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/211469246-303599e8-18fe-4c5e-aed9-bb058eb7cd0d.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/211469221-91f21975-edbf-4e16-b610-d891493b0748.mov"/>

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-16.0.pre.11, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-16.0.pre.11 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4205357554 (45 minutes ago), 2023-01-09 18:08:34 -0800
    • Engine revision 9c0b187a11
    • Dart version 3.0.0 (build 3.0.0-103.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by JoanSchi** [comment] 2023-01-10 07:38
Maybe this issue is a trigger for issue #104798 and maybe it is also only android related.

(I do not have iOS, but maybe it is interesting to test issue #104798 also on iOS to show if it is only android problem.)

**Comment by kinex** [comment] 2023-01-27 18:31
I noticed this issue in my app immediately after upgrading to Flutter 3.7 and Material 3. It seems all my widgets using `ListView` have this issue. It looks so bad I wouldn't like to publish my app before this gets fixed. Workaround seems to be switching to `SingleChildScrollView`, but that's not possible in all cases.

**Comment by Piinks** [comment] 2023-02-21 22:18
This was fixed by https://github.com/flutter/flutter/pull/116548 🎉

**Closed by Piinks** 2023-02-21 22:18 UTC
Labels: platform-android, framework, f: material design, f: scrolling, has reproducible steps, found in release: 3.3, found in release: 3.7
