### ISSUE TITLE
Oops bug

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#92797] opened 2021-10-31 19:50 UTC
<img width="919" alt="Снимок экрана 2021-10-31 в 22 48 14" src="https://user-images.githubusercontent.com/353832/139599186-d3173333-8044-4911-a67f-5665c31491d0.png">

When this will be fixed ?

**Comment by behzodfaiziev** [comment] 2021-10-31 21:44
@alex9153 
Не могли бы вы предоставить более подробную информацию об этой ошибке?

**Comment by behzodfaiziev** [comment] 2021-10-31 21:49
@alex9153 
Не могли бы вы предоставить более подробную информацию об этой ошибке? 
И добавьте отчет из flutter doctor -v

**Comment by danagbemava-nc** [comment] 2021-11-01 09:13
@alex9153, can you please provide steps to reproduce and the output of `flutter doctor -v`? 

Thank you

**Comment by maheshmnj** [comment] 2021-12-03 12:56
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by maheshmnj** 2021-12-03 12:56 UTC

**Comment by maheshmnj** [comment] 2021-12-03 12:57
Possible duplicate of https://github.com/flutter/flutter/issues/90844
