### ISSUE TITLE
IntelliJ text doesn't look great on Linux by default

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7711] opened 2017-01-27 22:34 UTC
This is the default appearance of IJ on Linux. It looks like the typewriter ribbon is wearing out :-)

![ig](https://cloud.githubusercontent.com/assets/1377460/22389945/2d8211ca-e49d-11e6-9a9a-97cec95e114b.png)

The other themes (GTK and Darcula) don't seem to be much better vis rendering text.  This is the same code rendered by emacs using the default text settings:

![emacs](https://cloud.githubusercontent.com/assets/1377460/22389962/493d3246-e49d-11e6-8967-a2e9835655f8.png)

And Chrome:

![chrome](https://cloud.githubusercontent.com/assets/1377460/22389964/4f67ea08-e49d-11e6-99f6-9af725c699d6.png)

**Comment by eseidelGoogle** [comment] 2017-01-28 01:13
@devoncarew or @pq might know.

**Comment by pq** [comment] 2017-01-29 00:45
Hmmmm....  @alexander-doroshko ?

**Comment by alexander-doroshko** [comment] 2017-01-29 07:47
@HansMuller What Linux version and monitor resolution? Please paste contents of IntelliJ's Help | About.

**Comment by HansMuller** [comment] 2017-01-30 17:51
I have a HP 30" display, 2560x1600 (16:10).

IntelliJ IDEA 2016.3.1
Build #IC-163.9166.29, built on December 9, 2016
JRE: 1.8.0_112-google-v7-144883550-143772575 amd64
JVM: OpenJDK 64-Bit Server VM by Google Inc.

**Comment by alexander-doroshko** [comment] 2017-01-30 18:41
@HansMuller Thanks! 
I guess the problem is with the JRE that the IDE starts under. Standard IntelliJ IDEA installer includes JRE developed by JetBrains. It is based on OpenJDK and includes a ton of our own fixes exactly about font rendering, antialiasing, HiDPI support, etc. So I recommend to [switch back to the bundled JDK](https://www.jetbrains.com/help/idea/2016.3/switching-boot-jdk.html).

**Comment by eseidelGoogle** [comment] 2017-01-31 04:00
If that fixes your font rendering troubles @HansMuller we should we add that to our list of IntelliJ setup instructions @devoncarew?

**Comment by alexander-doroshko** [comment] 2017-01-31 07:53
> should we add that to our list of IntelliJ setup instructions

In my understanding, correct JRE is used by default and to get problems that Hans has got additional manual actions required. If so, then probably instructions like "do not shoot yourself in the foot" are not necessary :). I may be wrong, I didn't test on Linux.

**Comment by pq** [comment] 2017-05-20 02:49
@HansMuller : this one is fixed?

**Comment by pq** [comment] 2017-11-21 18:56
@HansMuller : safe to close this one?

**Comment by Hixie** [comment] 2018-04-23 21:12
Closing per the last year's worth of comments. :-)

**Closed by Hixie** 2018-04-23 21:12 UTC
Labels: dev: ide - jetbrains
