### ISSUE TITLE
Note: C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by abhiditi** [flutter/flutter#57346] opened 2020-05-15 21:55 UTC
Note: C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Why it is showing this warning?

**Comment by mariamalbarghouti** [comment] 2020-05-15 23:45
what was the solution ?

**Comment by mariamalbarghouti** [comment] 2020-05-15 23:45
i'm facing the same error

**Comment by abhiditi** [comment] 2020-05-16 15:19
It is just a warning when firebase cloudstore package is upgraded to  cloud_firestore: ^0.13.5
You can ignore it, the app still runs.
The warning removed in my case in the following way:
Open build.gradle in android app level build
add this
 defaultConfig 
{
multiDexEnabled true
}
and add this dependency-   
  implementation 'androidx.multidex:multidex:2.0.1'

then save-> invalidate and restart->flutter clean->flutter Pub upgrade->flutter Pub get
then Run.

**Comment by TahaTesser** [comment] 2020-05-18 09:25
Hi @abhiditi, for what I can see the issue is related to a FlutterFire plugin. 
 
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1926

**Closed by TahaTesser** 2020-05-18 09:25 UTC
