### ISSUE TITLE
compileSdkVersion flutter.compileSdkVersion Doesn't work in Flutter 3.16.9

### ISSUE THREAD

**Issue by famasf1** [flutter/flutter#142519] opened 2024-01-30 11:05 UTC
### Steps to reproduce

I'm trying to run & debug my app. However i ran into issues on building steps. The app simply won't run on my emulator.

While I already found a workaround by changing ``` compileSdkVersion flutter.compileSdkVersion ``` to ``` compileSdkVersion 34 ``` , I still would like to avoid it as per Official Documentations. I already tried to updated Android Studio SDK tools but still not working.

I did not try to run it on my physical device. Only emulator, I'm using Pixel 3A (extension_level_7_API_34) and Pixel 7 Pro (API 33)

Steps to reproduce

1. Run and Debug on VSCode
2. That's it

### Expected results

I should be able to build and debug my app normally.

### Actual results

Build Error.

### Code sample

<details open><summary>Code sample</summary>

```dart
android {
    namespace "com.example.myapp"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.pos_mobile_platform"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 2 issues were found when checking AAR metadata:

       1.  Dependency 'androidx.webkit:webkit:1.8.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.3.0 is 33.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

       2.  Dependency 'androidx.browser:browser:1.6.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.3.0 is 33.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1


Exited (1).

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version
    10.0.22621.3007], locale th-TH)
    • Flutter version 3.16.9 on channel stable at
      D:\flutter\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git       
    • Framework revision 41456452f2 (5 days ago), 2024-01-25 10:06:23  
      -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or     
    higher)

[√] Android toolchain - develop for Android devices (Android SDK
    version 34.0.0)
    • Android SDK at C:\Users\User3\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android
      Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe  

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 
    17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual
      Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio        
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\User3\AppData\Local\Programs\Microsoft VS    
      Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    •  
      Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    •  
      Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)                 • chrome        • web-javascript •  
      Google Chrome 120.0.6099.217
    • Edge (web)                   • edge          • web-javascript •  
      Microsoft Edge 121.0.2277.83

[√] Network resources
    • All expected network resources are available.
```
</details>

**Comment by supratim1609** [comment] 2024-01-30 11:50
just check if the compileSdkversion and is same as that of the specification of the emulator

**Comment by dam-ease** [comment] 2024-01-30 11:57
Hello @famasf1 
Does this occur with the default Flutter counter, app, if yes, please check with https://github.com/flutter/flutter/issues/142519#issuecomment-1916675533?
Also, kindly check out this SO thread for more insights into this https://stackoverflow.com/questions/77271961/dependency-androidx-activityactivity1-8-0-requires-libraries-or-apps-that-de to see if it helps.

**Comment by stuartmorgan** [comment] 2024-01-30 14:54
> I still would like to avoid it as per Official Documentations.

It's not clear to me what official documentation this is referring to; you are welcome to adjust the `compileSdkVersion` yourself to meet your application's needs.

The `flutter.compileSdkVersion` has [already been updated to 34](https://github.com/flutter/flutter/pull/137967) on master, so closing as a duplicate of https://github.com/flutter/flutter/issues/134220.

**Closed by stuartmorgan** 2024-01-30 14:54 UTC
Labels: waiting for customer response, in triage
