### ISSUE TITLE
Flutter 2.2 iconData: wrong icon rendering on real iOS mobile devices

### ISSUE THREAD

**Issue by acx70** [flutter/flutter#83208] opened 2021-05-23 09:19 UTC
Since when I upgraded to Flutter 2.2, when I use IconData to create an Icon widget, I get different icons on real mobile devices.

You can find below a sample code where I used the constant 62465 which should correspond with [supervised_user_circle_outlined](https://api.flutter.dev/flutter/material/Icons/supervised_user_circle_outlined-constant.html).

![icon data 62465](https://user-images.githubusercontent.com/25884815/119254668-7ade6c00-bbaf-11eb-9321-b596c2ba996b.png)

Icon(
         IconData(
          62465,
          fontFamily: 'MaterialIcons')
)

On iOS simulators I can see the correct icon.

![right icon on ios simulator](https://user-images.githubusercontent.com/25884815/119254730-f2140000-bbaf-11eb-826b-0f292f7a2887.png)

When I deploy my app on a real iOS device, I see a completely different icon as you can see in the image below.

![wrong on iphone 8](https://user-images.githubusercontent.com/25884815/119254477-706fa280-bbae-11eb-9f36-76f3ad1ef41e.jpg)

My Flutter's version is:

Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (8 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

I tested the anomaly on iPhone 8 with OS version 14.5.1

**Comment by rajrushilmakkar** [comment] 2021-05-23 14:10
I am seeing the same issue on flutter web as well.
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (9 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
Issue gets resolved when user clears browser cache and reload

**Comment by acx70** [comment] 2021-05-24 06:46
Unfortunately, as far as I know, there is no way to clear the cache on mobile phone.

**Comment by rajrushilmakkar** [comment] 2021-05-24 06:54
> Unfortunately, as far as I know, there is no way to clear the cache on mobile phone.

Yes, this issue needs to be fixed. I was just sharing my experience with this issue on flutter web as well. It's definitely not a solution if users have to clear cache

**Comment by darshankawar** [comment] 2021-05-24 12:14
@acx70 
Verified this using latest stable on iphone 6s (14.4.1) and ios simulator (14.3) on which I see same icons:

1. Simulator:

<img width="195" alt="Screenshot 2021-05-24 at 5 38 17 PM" src="https://user-images.githubusercontent.com/67046386/119346182-83ba6500-bcb7-11eb-932d-3a7c3e23bd8f.png">


2. iPhone:

<img width="276" alt="Screenshot 2021-05-24 at 5 42 11 PM" src="https://user-images.githubusercontent.com/67046386/119346202-8917af80-bcb7-11eb-91ef-a21a15fa7ce6.png">

<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ncflutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!



```

</details>

**Comment by acx70** [comment] 2021-05-24 16:36
@darshankawar
the only difference I see from my test is the iOS version (14.5.1) , and the iphone version (iphone 8).
Did you test your app with your iphone connected to your mac in debug mode or you deployed your app on the store?
because I think it makes the difference.

**Comment by darshankawar** [comment] 2021-05-25 05:51
@acx70 
I don't have the said device and OS to verify on. 

> Did you test your app with your iphone connected to your mac in debug mode or you deployed your app on the store?

I verified on iphone connected to mac in debug mode.

Are you saying it happens in release mode / published apps ?

**Comment by acx70** [comment] 2021-05-25 07:12
@darshankawar 
Yes, it happens when I download the app from the the apple store. It does not happen with google store.

**Comment by i3games** [comment] 2021-05-25 10:37
We are seeing Icons replaced in certain environments in **Flutter Web** since upgrading to Flutter 2.2 

Screenshots below on Chrome 90.0.4430.212 It also happens on mobile devices.

<img width="1103" alt="Screenshot 2021-05-25 at 12 19 11" src="https://user-images.githubusercontent.com/830492/119482359-10b2fc00-bd54-11eb-81b9-6524a2c8b415.png">

left top: Local Development Machine 
left bottom: Staging
right: Live / CDN

same codebase using Material Icons from `package:flutter/material.dart`.

```
bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Start',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.map),
            label: 'Karte',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.list),
            label: 'Stücke',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.emoji_objects),
            label: 'Lösung',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.help),
            label: 'Hilfe',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.info),
            label: 'Impressum',
          ),
        ],
```

I'll add more info if possible.

```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
```

**Comment by acx70** [comment] 2021-05-25 16:00
@i3games 
my fault, I changed the title replacing 2.0 to 2.2

**Comment by bernaferrari** [comment] 2021-05-25 21:48
Duplicate of https://github.com/flutter/flutter/issues/79020 https://github.com/flutter/flutter/issues/75633

See this:
https://github.com/flutter/flutter/issues/75633#issuecomment-775487364

**Comment by i3games** [comment] 2021-05-25 22:23
> Duplicate of #79020 #75633
> 
> From what I heard, deleting Flutter's local cache solves this issue (i.e., try reinstalling Flutter).
> 
> See this:
> [#75633 (comment)](https://github.com/flutter/flutter/issues/75633#issuecomment-775487364)

I am not using Codepoints and the bug reported here was introduced with Flutter 2.2, a few days ago. Might be related but the bug was **not** preset in Flutter 2.0, so not sure how it relates to a bug closed in February.

**Comment by bernaferrari** [comment] 2021-05-25 22:25
Flutter 2.2 is the first stable version since the icon change which happened a few weeks ago.

**Comment by bernaferrari** [comment] 2021-05-25 22:32
The IconData is periodically updated. Check https://github.com/flutter/flutter/pull/79058 and the corresponding issues.

**Comment by i3games** [comment] 2021-05-25 23:08
> The IconData is periodically updated. Check #79058 and the corresponding issues.

I am aware of that but the issues reported there do not match in any way with what I wrote above. Check the details I posted here: https://github.com/flutter/flutter/issues/83208#issuecomment-847756904 .

I did tried `pub cache repair` as suggested somewhere in those issues and redeployed without any change to the situation.

**Comment by brunodmn** [comment] 2021-05-25 23:08
I have similar issue on Android real device, opened #83370. It is released with different icons, not only on debug device.

**Comment by darshankawar** [comment] 2021-05-26 05:28
@acx70 
Is there an easy way to replicate this on iOS mobile device, without having to deploy on appstore and check ? because it may need extra steps to deploy app on appstore and then verify.

@i3games Are you using canvaskit or html rendering to deploy your app that shows this behavior ?

**Comment by cosentino-smeup** [comment] 2021-05-26 06:20
@rajrushilmakkar 
No, unfortunately I did not find another way to replicate it.

**Comment by guidezpl** [comment] 2021-05-26 08:18
There are a few issues being conflated here so let's try to disambiguate.

First off, do not use `IconData` with MaterialFonts directly as the codepoints (e.g. 51234) can change as often as every stable release. Instead, use `Icon.<name>`. Note, I'm working with the Dartdoc team to de-emphasize or remove the `IconData` code snippets from the API docs. 

Now, if you're using Icons.<name> and seing different icons, the issue is likely with cache.
* Locally: 
  * `flutter/bin/internal/material_fonts.version` defines the current fonts version. As of stable 2.2 it is `bd151aa3c2f7231344411a01dba4ef61b3cd56b2`
  * `flutter/bin/cache/material_fonts.stamp` stores the currently cached version. This should be the same as `material_fonts.version`. The tool uses this file to determine if the cached version is up to date.
* To anyone facing this issue, please let me know if these files have different contents and try deleting `flutter/bin/cache/material_fonts.stamp` and then doing a `flutter run` or `flutter precache`

* Web 
  * Can you check if your browser or server cache is serving an older version of the MaterialIcons .tff? The workaround would be to use a shorter TTL. We may also want to look at asset cache-busting in web builds.

* mobile devices
  * Builds copy the cached asset I mentionned earlier, so that would be the source of the problem.

**Comment by i3games** [comment] 2021-05-26 10:18
> There are a few issues being conflated here so let's try to disambiguate.
> 
> First off, do not use `IconData` with MaterialFonts directly as the codepoints (e.g. 51234) can change as often as every stable release. Instead, use `Icon.<name>`. Note, I'm working with the Dartdoc team to de-emphasize or remove the `IconData` code snippets from the API docs.
> 
> Now, if you're using `Icons.<name>` and seing different icons, the issue is likely with cache.
> 
>     * Locally:
>       
>       * `flutter/bin/internal/material_fonts.version` defines the current fonts version. As of stable 2.2 it is `bd151aa3c2f7231344411a01dba4ef61b3cd56b2`
>       * `flutter/bin/cache/material_fonts.stamp` stores the currently cached version. This should be the same as `material_fonts.version`. The tool uses this file to determine if the cached version is up to date.
> 
>     * To anyone facing this issue, please let me know if these files have different contents and try deleting `flutter/bin/cache/material_fonts.stamp` and then doing a `flutter run` or `flutter precache`
> 
>     * Web
>       
>       * Can you check if your browser or server cache is serving an older version of the MaterialIcons .tff? The workaround would be to use a shorter TTL. We may also want to look at asset cache-busting in web builds.
> 
>     * mobile devices
>       
>       * Builds copy the cached asset I mentionned earlier, so that would be the source of the problem.

Thanks for the clear explanation. Here is what i did.

I did a complete re-install of Futter 2.2.0 as suggested above and deployed the project again including the file `MaterialIcons-Regular.otf`. I had to overwrite it on the server manually. As a result that the problem for me is solved and the 'old' correct icons show up again. 

I looks like that file was reverted to a previous version without updating the time stamp and therefore caches / deployment pipelines do not overwrite the existing file with a newer timestamp. 

On Firefox for example, even after the server served the correct file again, a Shift Reload did fetch the correct version, a subsequent reload however displayed the wrong version again. It seems like Firefox kept the previous version cached and did not overwrite it, I assume because of the timestamp issue. So did my server.

In the future it would be fabulous if the framework update process would take care of that situation. e.g. updating timestamps accordingly.

**Comment by brunodmn** [comment] 2021-05-26 12:39
> Icons.<name>

Hello,
 I am using `Icons.<name>`. 
 The local files material_fonts version/stamp are the same you mentioned.
 I've deleted `flutter/bin/cache/material_fonts.stamp` manually and did a `flutter run`, which indeed solved the problem in my case.
 Thank you!

**Comment by cosentino-smeup** [comment] 2021-05-26 15:45
IconData is very convenient to provide icons with an external configuration.
Lose IconData means lose flexibility.

By the way, I fixed the problem :
- I checked that both the versions of the fonts (current fonts version and stores the currently cached version) were the same 
- I run "flutter pub cache repair" 

Now everything works fine.

Thank you everyone!!

**Closed** 2021-05-26 16:15 UTC
Labels: in triage, waiting for customer response

**Comment by DirkSimons** [comment] 2021-07-01 11:59
I'm using IconData to store the icon the user has chosen in a database...  so I do need th IconData integer, or do you guys have another idea to achieve this?

**Comment by guidezpl** [comment] 2021-07-01 13:06
I'm talking to the fonts team to see if we can get stable codepoints, but for now, assume all existing codepoints change when the icons are updated. Hopefully it'll be fixed before the next update
