### ISSUE TITLE
No file or variants found for asset: packages/html_editor_enhanced/summernote.html.

### ISSUE THREAD

**Issue by gireeshkottayam** [flutter/flutter#120544] opened 2023-02-12 02:17 UTC
i have tried to build apk , but unfortunately the result ends with the following error 

_No file or variants found for asset: packages/html_editor_enhanced/summernote.html._

**### pubspec.yaml** 

name: admin_eshop
description: A new Flutter project.
publish_to: 'none'
version: 4.0.0+1 #3.0.6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http: ^0.13.4
  shared_preferences: ^2.0.8
  connectivity: ^3.0.6
  shimmer: ^2.0.0
  jaguar_jwt: ^3.0.0
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.0.12
  sms_autofill: ^2.2.0
  firebase_auth: ^3.1.3
  country_code_picker: ^2.0.2
  fl_chart: ^0.51.0
  flutter_local_notifications: ^9.0.0
  firebase_messaging: ^11.4.1
  path_provider: ^2.0.5
  file_picker: ^4.1.4
  flutter_downloader: ^1.6.1
  open_file: ^3.2.1
  permission_handler: ^9.2.0
  flutter_html_to_pdf: ^0.7.0
  sticky_headers: ^0.3.0+2
  mime: ^1.0.1
  html_editor_enhanced: 2.4.0+1
  firebase_core_platform_interface: 4.5.1
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
    modal_bottom_sheet:
      git:
        url: https://github.com/danReynolds/modal_bottom_sheet.git
        path: modal_bottom_sheet

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/maintenance.json
    - lib/Language/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf

**Comment by iapicca** [comment] 2023-02-12 16:17
@gireeshkottayam 
this issue seems to be caused by [html_editor_enhanced](https://pub.dev/packages/html_editor_enhanced) and probably should be open [here](https://github.com/tneotia/html-editor-enhanced/issues)

**Comment by danagbemava-nc** [comment] 2023-02-13 07:39
Hi @gireeshkottayam, as @iapicca pointed out above this is an issue with `html_editor_enhanced` and as such should be reported on their repo. It already seems like other users have reported this issue over there. See https://github.com/tneotia/html-editor-enhanced/issues/382. 

Closing from here as this is not a flutter issue. 

Thank you

**Closed by danagbemava-nc** 2023-02-13 07:39 UTC
Labels: in triage
