### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by mustikachairani** [flutter/flutter#134202] opened 2023-09-07 09:15 UTC
## Command
```
flutter run -t lib/main_ios.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3324], locale en-ID)
    [32m•[39m Flutter version 3.10.6 on channel stable at D:\flutter\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (8 weeks ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\PC JK\AppData\Local\Android\Sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = C:\Users\PC JK\AppData\Local\Android\Sdk
    [32m•[39m Java bin231)
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[32m[✓][39m VS Code (version 1.81.1)
    [32m•[39m VS Code at C:\Users\PC JK\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.72.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.142
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.69

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f468f3366c26a5092eb964a230ce7892fda8f2f8

**Comment by danagbemava-nc** [comment] 2023-09-07 09:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/79748

**Closed by danagbemava-nc** 2023-09-07 09:48 UTC
Labels: in triage
