### ISSUE TITLE
Flutter tests complain about: "Shell: Do not know weight for: TeXGyreSchola (BoldItalic) "

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7224] opened 2016-12-09 22:27 UTC
Run flutter test packages/flutter

@chinmaygarde

**Comment by chinmaygarde** [comment] 2016-12-09 22:30
This happens because the test shell tries to read fonts on the host when it cant resolve a font specified in the framework (Roboto or San Francisco). Sometimes, fonts on the host are buggy and Skia or FontConfig may complain about the same.

Once https://github.com/flutter/engine/pull/3301 lands, we will never attempt to read fonts on the host from the test shell. So this error should go away too.

**Comment by chinmaygarde** [comment] 2016-12-13 20:18
Fix has landed.

**Comment by jcollins-g** [comment] 2018-01-17 22:23
I seem only able to reproduce this on my workstation at the moment (Linux).

```
~/dart/flutter/dev/automated_tests
$ ../../bin/flutter test flutter_test/exception_handling_test.dart 2>&1 | head
00:00 +0: - Exception handling in test harness - string
Shell: Do not know weight for: TeXGyreSchola (BoldItalic) 
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown running a test:
Who lives, who dies, who tells your story?

When the exception was thrown, this was the stack:
#0      main.<anonymous closure> (///usr/local/google/home/jcollins/dart/flutter/dev/automated_tests/flutter_test/exception_handling_test.dart:10:5)
<asynchronous suspension>
#1      testWidgets.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:61:25)
```

**Comment by jason-simmons** [comment] 2018-03-03 00:19
This is coming from Skia's SkScalerContext_FreeType

I just started seeing this after upgrading to a new Linux setup.  I worked around it by uninstalling the tex-gyre package.

**Comment by HansMuller** [comment] 2018-03-21 16:01
I'm seeing the same problem. Running `flutter test` produces a blizzard of these warnings.

**Comment by Hixie** [comment] 2019-12-09 19:00
This hasn't happen in a while as far as I'm aware.

**Closed by Hixie** 2019-12-09 19:00 UTC
Labels: dependency: skia, engine, team
