### ISSUE TITLE
FlatButton material widget incorrect sizing

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#19410] opened 2018-07-16 15:29 UTC
I am not sure if this is a new bug, but this does not appear to be normal...

The button SHOULD and used to expand in an older version of flutter to fill the entire screen but it does not anymore.

The hitbox does expand, but the button styling does not reflect that change, as you can see in the GIF the hitbox is massive but the button is not massive. The button size does not match the hitbox size.

![2018-07-16_11-28-49](https://user-images.githubusercontent.com/7272343/42767611-6bfde7be-88eb-11e8-91b4-2baf4c4dd76e.gif)

## Reproducing:

    return
      Scaffold(
        resizeToAvoidBottomPadding: false,
        backgroundColor: Colors.white,
        body: 
         Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Expanded(
              flex: 1,
              child:
                  FlatButton(
                    color: CoreTheme.MainColor,
                    child: Text('Sign Up', style: TextStyle(fontWeight: FontWeight.w400, color: Colors.white, fontSize: 18.0)),
                    onPressed: () => {},
                  )
            ),
          ]
        )
      );

**Comment by jonahwilliams** [comment] 2018-07-16 15:43
closing as a dupe of https://github.com/flutter/flutter/issues/19399, I will find a more usable fix, but for now see the solution in the issue

**Closed by jonahwilliams** 2018-07-16 15:43 UTC
