### ISSUE TITLE
 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by eududalim** [flutter/flutter#69884] opened 2020-11-05 15:10 UTC
```
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#31f95](dirty, dependencies: [HeroControllerScope], state: NavigatorState#a0b1e(tickers: tracking 3 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.

The relevant error-causing widget was
MaterialApp
lib/main.dart:15
When the exception was thrown, this was the stack
#2      NavigatorState.build
package:flutter/…/widgets/navigator.dart:4041
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#4      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#5      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
#6      Element.rebuild
package:flutter/…/widgets/framework.dart:4343
...

```

**Comment by RivaanRanawat** [comment] 2020-11-06 07:30
It is hard to tell what the problem is by seeing the error only and not the code but I think there is a problem with the lifecycle of a widget in Flutter. Will be more helpful if you can share the code.

**Comment by darshankawar** [comment] 2020-11-06 07:39
@eududalim 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by RivaanRanawat** [comment] 2020-11-17 06:44
Since there is no response from the user, I am closing this issue.

**Comment by eududalim** [comment] 2020-12-01 13:03
Thank you so much for the help. I managed to solve the problem :)

**Comment by darshankawar** [comment] 2020-12-01 13:59
@eududalim 
Good to know your issue is resolved. Closing this based on your comment above.

**Closed by darshankawar** 2020-12-01 13:59 UTC
Labels: in triage

**Comment by RubaHashash** [comment] 2020-12-08 12:22
I have the same problem. Can you please tell me what was it?

**Comment by eududalim** [comment] 2020-12-08 13:14
Yea! I insert was the widget **Navigator** in to **WidgetsBinding.instance.addPostFrameCallback**
I believe that be a solution temporary, but are working well. :)
My code stayed like this:

` WidgetsBinding.instance.addPostFrameCallback((_) {
                Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(
                      builder: (context) => LoginScreen(),
                    ));
              });`

**Comment by adigujjar** [comment] 2020-12-21 13:51
i also facing this issue when i want to move to another screen

**Comment by adigujjar** [comment] 2020-12-21 13:51
`======= Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4506 pos 12: '<optimized out>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      NavigatorState._pushReplacementEntry (package:flutter/src/widgets/navigator.dart:4506:12)
#3      NavigatorState.pushReplacement (package:flutter/src/widgets/navigator.dart:4448:5)
#4      Navigator.pushReplacement (package:flutter/src/widgets/navigator.dart:2198:35)
#5      _PlayerDashboard.build.<anonymous closure>.<anonymous closure> (package:magic_game/pages/home/PlayerHome.dart:124:33)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...`

**Comment by sovan-7** [comment] 2021-02-15 13:37
Unhandled Exception: 'package:flutter/src/foundation/binding.dart': Failed assertion: line 56 pos 12: '!_debugInitialized': is not true.
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
//import 'package:lifeo/splashscreen/flash1.dart';
import 'package:lifeo/splashscreen/home.dart';
import 'package:shared_preferences/shared_preferences.dart';

int initScreen;
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SharedPreferences preferences = await SharedPreferences.getInstance();
  initScreen = await preferences.getInt('initScreen');
  await preferences.setInt('initScreen', 1);
  WidgetsFlutterBinding();
  SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitDown, DeviceOrientation.portraitUp]);
  runApp(MyApp());
  //home: MyApp(),
  //debugShowCheckedModeBanner: false,
  //));
}

int bgcolorone;

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'LIFE-O',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
          backgroundColor:
              bgcolorone == null ? Color(0xFF30CFD0) : Color(bgcolorone),
          primaryColor: Colors.blue[900],
          fontFamily: "Lato",
          appBarTheme: AppBarTheme(
            color: Colors.blue[900],
          ),
          textTheme: TextTheme(
            headline1: TextStyle(
              color: Colors.white,
              fontFamily: "Lato",
              fontSize: 20,
              fontWeight: FontWeight.w300,
              letterSpacing: 1,
            ),
            headline5: TextStyle(
              color: Colors.black,
              fontSize: 17,
              fontWeight: FontWeight.w300,
              letterSpacing: 0,
            ),
          )),
      initialRoute: initScreen == 0 || initScreen == null ? 'onboard' : 'home',
      routes: {
        'home': (context) => HomeScreen(),
        'onboard': (context) => HomeScreen(),
      },
    );
  }
}

**Comment by EricSantosteixeira** [comment] 2021-03-31 01:25
> Sim! **Inseri** foi o widget **Navigator** em **WidgetsBinding.instance.addPostFrameCallback**
> acredito que seja uma solução temporária, mas está funcionando bem. :)
> Meu código ficou assim:
> 
> ` WidgetsBinding.instance.addPostFrameCallback((_) { Navigator.pushReplacement( context, MaterialPageRoute( builder: (context) => LoginScreen(), )); });`

Funcionou pra mim obrigado!

**Comment by mohadel92** [comment] 2021-06-26 23:36
> WidgetsBinding.instance.addPostFrameCallback((_) { Navigator.pushReplacement( context, MaterialPageRoute( builder: (context) => LoginScreen(), )); });

can you please explain this solution
