### ISSUE TITLE
PlatformException related to Connectivity package version 0.4.9+5 occurs after disposing a screen

### ISSUE THREAD

**Issue by nekoto-kun** [flutter/flutter#68265] opened 2020-10-16 03:02 UTC
Hi there,
I got PlatformException that caught for the first time in my app after upgrading the ```connectivity``` package to ```0.4.9+5```. The flow that produces the exception generally goes like below:
1. User logins
2. Dashboard screen shows up, containing connectivity handling which exactly the same as the example from its documentation. Below is the state class of Dashboard screen I'm having.
```
class _StateDashboardScreen extends State<DashboardScreen>
    with TickerProviderStateMixin {
final Connectivity _connectivity = Connectivity();
  StreamSubscription<ConnectivityResult> _connectivitySubscription;

@override
  void initState() {
    super.initState();
    ... initalizes any controllers
    initConnectivity();
    _connectivitySubscription =
        _connectivity.onConnectivityChanged.listen(_updateConnectionStatus);
  }

  @override
  void dispose() {
    ... disposes any controllers
    _connectivitySubscription.cancel();
    super.dispose();
  }

// Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initConnectivity() async {
    ConnectivityResult result;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      result = await _connectivity.checkConnectivity();
    } on PlatformException catch (e) {
      print(e.toString());
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) {
      return Future.value(null);
    }

    return _updateConnectionStatus(result);
  }

Future<void> _updateConnectionStatus(ConnectivityResult result) async { ... }
...
}
```
3. Dashboard screen containing PageView with some screens. One screen has a Logout button.
4. User hits the Logout button. A logout confirmation dialog shown.
5. User confirms logout. Below is the method that invoke logout process and it supposed to clear all storage and variables then redirect user back to login screen using ```notifyListeners()``` (from ```Provider``` package).
```
Future<void> logOut() async {
    ... clears storage
    ... clears variables
    ... clears anything
    notifyListeners();
  }
```
This one is supposed to dispose the Dashboard screen as well and calls the overridden dispose method in Dashboard screen above.
6. The logout process entirely safe and sound, the login screen shown successfully. However, in the process of disposing Dashboard screen, the exception occurs like in the logs provided below. I suppose that something went wrong when executing this ```_connectivitySubscription.cancel();``` method. Or did I missing something that needs to be handled in recent version?

<details>
  <summary>Logs</summary>

```
[+1969 ms] E/EventChannel#plugins.flutter.io/connectivity_status(21009): Failed to close event stream
[   +1 ms] E/EventChannel#plugins.flutter.io/connectivity_status(21009): java.lang.IllegalArgumentException:
NetworkCallback was not registered
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
[  +13 ms] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3528)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
io.flutter.plugins.connectivity.ConnectivityBroadcastReceiver.onCancel(ConnectivityBroadcastReceiver.java:53)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onCancel(EventChannel.java:201)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:169)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
android.os.MessageQueue.next(MessageQueue.java:326)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at android.os.Looper.loop(Looper.java:165)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
android.app.ActivityThread.main(ActivityThread.java:6864)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at java.lang.reflect.Method.invoke(Native
Method)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
[        ] E/EventChannel#plugins.flutter.io/connectivity_status(21009):        at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
[  +62 ms] I/flutter (21009): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY
╞══════════════════════════════════════════════════════════
[   +1 ms] I/flutter (21009): The following PlatformException was thrown while de-activating platform stream on channel
[        ] I/flutter (21009): plugins.flutter.io/connectivity_status:
[        ] I/flutter (21009): PlatformException(error, NetworkCallback was not registered, null, null)
[        ] I/flutter (21009):
[        ] I/flutter (21009): When the exception was thrown, this was the stack:
[        ] I/flutter (21009): #0      StandardMethodCodec.decodeEnvelope
(package:flutter/src/services/message_codecs.dart:582:7)
[        ] I/flutter (21009): #1      MethodChannel._invokeMethod
(package:flutter/src/services/platform_channel.dart:159:18)
[        ] I/flutter (21009): <asynchronous suspension>
[        ] I/flutter (21009): #2      MethodChannel.invokeMethod
(package:flutter/src/services/platform_channel.dart:332:12)
[   +1 ms] I/flutter (21009): #3      EventChannel.receiveBroadcastStream.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:552:29)
[        ] I/flutter (21009): #4      EventChannel.receiveBroadcastStream.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:549:18)
[        ] I/flutter (21009): #17     _StateDashboardScreen.dispose
(▮▮▮/screens/dashboard_screen.dart:62:31) <-- this is my primary screen which contains another screen inside that is invoking a logOut() and dispose the screen entirely. Later, the app switch back to a login screen.
[        ] I/flutter (21009): #18     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
[        ] I/flutter (21009): #19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1998:13)
[        ] I/flutter (21009): #20     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
[        ] I/flutter (21009): #21     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2007:25)
[        ] I/flutter (21009): #22     BuildOwner.finalizeTree.<anonymous closure>
(package:flutter/src/widgets/framework.dart:2821:27)
[        ] I/flutter (21009): #23     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2621:15)
[        ] I/flutter (21009): #24     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2820:7)
[        ] I/flutter (21009): #25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:915:18)
[        ] I/flutter (21009): #26     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:302:5)
[        ] I/flutter (21009): #27     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1117:15)
[        ] I/flutter (21009): #28     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1055:9)
[        ] I/flutter (21009): #29     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:971:5)
[        ] I/flutter (21009): #33     _invoke (dart:ui/hooks.dart:251:10)
[        ] I/flutter (21009): #34     _drawFrame (dart:ui/hooks.dart:209:3)
[        ] I/flutter (21009): (elided 15 frames from dart:async)
[        ] I/flutter (21009):
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1082], locale id-ID)
    • Flutter version 1.22.1 at C:\flutter
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Redmi Note 8 (mobile) • 152aa503 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```
</details>

**Comment by darshankawar** [comment] 2020-10-16 09:30
@nekoto-kun 
Please provide a complete minimal reproducible code sample that we can copy paste and run that shows the issue.
Thanks.

**Comment by funwithflutter** [comment] 2020-10-16 11:53
Experiencing the same error @darshankawar .

To reproduce you can use the example app in the repo. After running it do a restart (not Hot Reload) and it will throw a `Failed to close existing event stream` error.

**Comment by nekoto-kun** [comment] 2020-10-17 02:13
This example code is just containing two screen, one without connectivity initializations. Each screen containing a button to do simple go and back navigation.

<details>
<summary>Reproducible example app code</summary>

```
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'dart:io';

import 'package:connectivity/connectivity.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// Sets a platform override for desktop to avoid exceptions. See
// https://flutter.dev/desktop#target-platform-override for more info.
void _enablePlatformOverrideForDesktop() {
  if (!kIsWeb && (Platform.isWindows || Platform.isLinux)) {
    debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
  }
}

void main() {
  _enablePlatformOverrideForDesktop();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: NoConnectivityScreen(), //MyHomePage(),
    );
  }
}

class NoConnectivityScreen extends StatefulWidget {
  @override
  _NoConnectivityScreenState createState() => _NoConnectivityScreenState();
}

class _NoConnectivityScreenState extends State<NoConnectivityScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Screen w/o Connectivity'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text('This screen is without connectivity initializations'),
            SizedBox(height: 8),
            RaisedButton(
              child: Text('Go to Connectivity Screen'),
              onPressed: () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) => MyHomePage(),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _connectionStatus = 'Unknown';
  final Connectivity _connectivity = Connectivity();
  StreamSubscription<ConnectivityResult> _connectivitySubscription;

  @override
  void initState() {
    super.initState();
    initConnectivity();
    _connectivitySubscription =
        _connectivity.onConnectivityChanged.listen(_updateConnectionStatus);
  }

  @override
  void dispose() {
    _connectivitySubscription.cancel();
    super.dispose();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initConnectivity() async {
    ConnectivityResult result;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      result = await _connectivity.checkConnectivity();
    } on PlatformException catch (e) {
      print(e.toString());
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) {
      return Future.value(null);
    }

    return _updateConnectionStatus(result);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Connectivity example app'),
      ),
      body: Center(
          child: Column(
        children: [
          Text('Connection Status: $_connectionStatus'),
          SizedBox(height: 8),
          RaisedButton(
            child: Text('Go Back'),
            onPressed: () => Navigator.pop(context),
          )
        ],
      )),
    );
  }

  Future<void> _updateConnectionStatus(ConnectivityResult result) async {
    switch (result) {
      case ConnectivityResult.wifi:
        String wifiName, wifiBSSID, wifiIP;

        try {
          if (!kIsWeb && Platform.isIOS) {
            LocationAuthorizationStatus status =
                await _connectivity.getLocationServiceAuthorization();
            if (status == LocationAuthorizationStatus.notDetermined) {
              status =
                  await _connectivity.requestLocationServiceAuthorization();
            }
            if (status == LocationAuthorizationStatus.authorizedAlways ||
                status == LocationAuthorizationStatus.authorizedWhenInUse) {
              wifiName = await _connectivity.getWifiName();
            } else {
              wifiName = await _connectivity.getWifiName();
            }
          } else {
            wifiName = await _connectivity.getWifiName();
          }
        } on PlatformException catch (e) {
          print(e.toString());
          wifiName = "Failed to get Wifi Name";
        }

        try {
          if (!kIsWeb && Platform.isIOS) {
            LocationAuthorizationStatus status =
                await _connectivity.getLocationServiceAuthorization();
            if (status == LocationAuthorizationStatus.notDetermined) {
              status =
                  await _connectivity.requestLocationServiceAuthorization();
            }
            if (status == LocationAuthorizationStatus.authorizedAlways ||
                status == LocationAuthorizationStatus.authorizedWhenInUse) {
              wifiBSSID = await _connectivity.getWifiBSSID();
            } else {
              wifiBSSID = await _connectivity.getWifiBSSID();
            }
          } else {
            wifiBSSID = await _connectivity.getWifiBSSID();
          }
        } on PlatformException catch (e) {
          print(e.toString());
          wifiBSSID = "Failed to get Wifi BSSID";
        }

        try {
          wifiIP = await _connectivity.getWifiIP();
        } on PlatformException catch (e) {
          print(e.toString());
          wifiIP = "Failed to get Wifi IP";
        }

        setState(() {
          _connectionStatus = '$result\n'
              'Wifi Name: $wifiName\n'
              'Wifi BSSID: $wifiBSSID\n'
              'Wifi IP: $wifiIP\n';
        });
        break;
      case ConnectivityResult.mobile:
      case ConnectivityResult.none:
        setState(() => _connectionStatus = result.toString());
        break;
      default:
        setState(() => _connectionStatus = 'Failed to get connectivity.');
        break;
    }
  }
}
```

</details>

**Comment by darshankawar** [comment] 2020-10-19 06:11
<details>
<summary>log</summary>

```
D/ConnectivityManager(13756): requestNetwork; CallingUid : 10227, CallingPid : 13756
D/ConnectivityManager(13756): unregisterNetworkCallback; CallingUid : 10227, CallingPid : 13756
E/EventChannel#plugins.flutter.io/connectivity_status(13756): Failed to close event stream
E/EventChannel#plugins.flutter.io/connectivity_status(13756): java.lang.IllegalArgumentException: NetworkCallback was not registered
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3862)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at io.flutter.plugins.connectivity.ConnectivityBroadcastReceiver.onCancel(ConnectivityBroadcastReceiver.java:53)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onCancel(EventChannel.java:201)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:169)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at android.os.Looper.loop(Looper.java:142)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at android.app.ActivityThread.main(ActivityThread.java:6543)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E/EventChannel#plugins.flutter.io/connectivity_status(13756): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following PlatformException was thrown while de-activating platform stream on channel plugins.flutter.io/connectivity_status:
PlatformException(error, NetworkCallback was not registered, null, null)

When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:552:29)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
W/libEGL  (13756): EGLNativeWindowType 0xc7271808 disconnect failed
W/libEGL  (13756): EGLNativeWindowType 0xc7f14808 disconnect failed

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (11 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

</details>

**Comment by rhuarc0** [comment] 2020-11-03 01:36
This exception hasn't been fixed in version 2.0.0 yet. You've been asking for the code to reproduce but it's unnecessary. 
The problem appears because of the incorrect code in `ConnectivityBroadcastReceiver.java`, method `void onCancel(Object arguments)`


```
  @Override
  public void onCancel(Object arguments) {
    if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
      connectivity.getConnectivityManager().unregisterNetworkCallback(getNetworkCallback());
    } else {
      context.unregisterReceiver(this);
    }
  }
```


```
  @RequiresApi(api = Build.VERSION_CODES.N)
  ConnectivityManager.NetworkCallback getNetworkCallback() {
    return new ConnectivityManager.NetworkCallback() {
      @Override
      public void onAvailable(Network network) {
        sendEvent();
      }

      @Override
      public void onLost(Network network) {
        sendEvent();
      }
    };
  }
```

Here you can see unregistering of some **new** callback, not the one which was registered before.

**Comment by xylim666** [comment] 2020-11-16 02:31
how do you guys get around this issue? My app black screen whenever this happens

**Comment by hamdikahloun** [comment] 2020-11-17 19:27
Hi @rhuarc0 @nekoto-kun 

connectivity 2.0.2 published.

```
2.0.2 :
Android: Fix IllegalArgumentException.
Android: Update Example project.
```

Thank you

**Closed by hamdikahloun** 2020-11-17 19:27 UTC
Labels: found in release: 1.22, has reproducible steps, p: connectivity, p: first party, plugin
