### ISSUE TITLE
Flutter [Web] TextField - Unable to move to nextline in multiline input, cursor doesn't move to next line.

### ISSUE THREAD

**Issue by the-airbender** [flutter/flutter#44057] opened 2019-11-03 09:40 UTC
## Steps to Reproduce

1.  We are able to type only in a single line in TextField, hitting enter doesn't move to next line.
2.  TextFeild Multiline doesn't work on Web.. Same works perfectly on iOS/Android.
3.  I have set "maxLines:null" still didn't work.  
`
 TextFormField(
                    controller: _messageController,
                    maxLines: null,
                    enableInteractiveSelection: true,
                    keyboardType: TextInputType.multiline,
                    decoration: new InputDecoration(
                        labelStyle: TextStyle(color: Colors.grey),
                        labelText: "Message",
                        errorText: _validateMessage ? 'Value Can\'t Be Empty' : null,
                        enabledBorder: const OutlineInputBorder(
                          borderSide:
                              const BorderSide(color: Colors.grey, width: 0.5),
                        )),
                  ),
`

**Target Platform: Browser**
**Target OS version/browser: Chrome**
**Devices: MacBook Air**

## Logs

```
```

```
```

```
[✓] Flutter (Channel master, v1.10.15-pre.384, on Mac OS X 10.15 19A583, locale en-IN)
    • Flutter version 1.10.15-pre.384 at /Users/airbender/flutter
    • Framework revision ee032f67c7 (16 hours ago), 2019-11-02 09:46:25 -0700
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/airbender/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 77.0.3865.75
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

**Comment by yjbanov** [comment] 2019-11-07 23:35
This should be fixed now.

/cc @mdebbar, please close with a link to the PR

**Comment by mdebbar** [comment] 2019-11-07 23:38
Duplicate of https://github.com/flutter/flutter/issues/43935 which was fixed two days ago. Please re-file the issue if you are still seeing the bug.

**Closed by mdebbar** 2019-11-07 23:38 UTC
Labels: a: text input, framework, ☸ platform-web
