### ISSUE TITLE
[Flutter 2.8.1] Scrollbar jumps around erratically when item in ListView is smoothly increasing in height

### ISSUE THREAD

**Issue by chipweinberger** [flutter/flutter#97354] opened 2022-01-27 07:17 UTC
40 boxes in a ListView. The first box made to expand 1 point in height every 30 millisconds. The scroll bar becomes jumpier and jumpier as the first box gets taller.

**Expectation:**  The scroll bar should remain fluid and usable when dragged. 

**Result:**  The scroll bar jumps around when dragged. See Video.

**Flutter:** 2.8.1
**iOS:** 15.2 (iPhone 12 Mini)
**Dev:** MacOS 12.1 / Visual Code

https://user-images.githubusercontent.com/1863934/151309968-603938a9-bbe2-43d9-8104-e212af33bf5f.mov

<details>
<summary>code sample</summary>

```dart
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    Widget widget = const FunkyList();

    return MaterialApp(
      title: 'Jumpy Scrollbar',
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Jumpy Scrollbar'),
        ),
        body: widget
      ),
    );

  }
}


class FunkyList extends StatefulWidget {
  const FunkyList({Key? key}) : super(key: key);
  @override
  createState() => _FunkyListState();
}

class _FunkyListState extends State<FunkyList> {
  late Timer _everyMillis;

  double _expandingHeight = 0;

  @override
  void initState() {
    super.initState();

    _everyMillis = Timer.periodic(const Duration(milliseconds: 30), (Timer t) {
      if (mounted) {
        setState(() {
          // increate the height of the first item in the ListView every 30ms
          _expandingHeight += 1.0;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
      isAlwaysShown: true,
      child: ListView.builder(
          itemCount: 40,
          itemBuilder: (context, index) {
            return Padding(
              padding: const EdgeInsets.all(16.0),
              child: SizedBox(
                // increate the height of the first item in the ListView every 30ms, otherwise 200
                height: index == 0 ? _expandingHeight : 200.0,
                width: 30,
                child: const DecoratedBox(
                  decoration: const BoxDecoration(color: Colors.red),
                ),
              ),
            );
          }),
    );
  }
}
```
</details>

**Comment by chipweinberger** [comment] 2022-01-27 07:20
Are there any workarounds to prevent this behavior?

**Comment by chipweinberger** [comment] 2022-01-27 09:14
I've hacked up a pretty good workaround by
- 1. setting ListView.reverse: true
- 2. expanding the *last* item (now really the first item) list. 

From the example above:


```
const int itemCount = 40; // CHANGED 

ListView.builder(
          reverse: true, // CHANGED
          itemCount: itemCount, // CHANGED
          itemBuilder: (context, index) {
            return Padding(
              padding: const EdgeInsets.all(16.0),
              child: SizedBox(
                // increate the height of the first item in the ListView every 30ms, otherwise 200
                height: index == (itemCount - 1) ? _expandingHeight : 200.0,  // CHANGED
                width: 30,
                child: const DecoratedBox(
                  decoration: const BoxDecoration(color: Colors.red),
                ),
              ),
            );
          }),
    );
```

**Comment by chipweinberger** [comment] 2022-01-27 09:55
Yup, It can be repro'd with this even simpler case. Just List Items of different sizes (8000 vs 200)

```
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    return MaterialApp(
        title: 'Jumpy Scrollbar',
        home: Scaffold(
          appBar: AppBar(title: const Text('Jumpy Scrollbar')),
          body: Scrollbar(
            isAlwaysShown: true,
            child: ListView.builder(
                itemCount: 40,
                itemBuilder: (context, index) {
                  return Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      children: [
                        Text("test ${index}"),
                        SizedBox(
                          // increate the height of the first item in the ListView every 30ms, otherwise 200
                          height: index == 0 ? 8000 : 200.0,
                          width: 30,
                          child: const DecoratedBox(
                            decoration: const BoxDecoration(color: Colors.red),
                          ),
                        ),
                      ],
                    ),
                  );
                }),
          ),
        ));
  }
}
```

**Comment by chipweinberger** [comment] 2022-01-27 10:06
It also reproduces with just a ListView, no ListView.builder needed. 

```
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  Widget box(double height) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        children: [
          Text("test $height"),
          SizedBox(
            height: height,
            width: 30,
            child: const DecoratedBox(
              decoration: const BoxDecoration(color: Colors.red),
            ),
          ),
        ],
      ),
    );
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Jumpy Scrollbar',
        home: Scaffold(
          appBar: AppBar(title: const Text('Jumpy Scrollbar')),
          body: Scrollbar(
            isAlwaysShown: true,
            child: ListView(
                children: [
                  box(8000),
                  box(200),
                  box(200),
                  box(200),
                ]),
          ),
        ));
  }
}

```

**Comment by maheshmnj** [comment] 2022-01-27 11:10
Hi @chipweinberger, Thanks for filing the issue. I can reproduce the same behavior the scrollbar is jumpy and does not smoothly scroll, But I believe this is intended since the list item is dynamically changing its height which changes the List maxExtent too.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.307, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.307 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b7424c619c (7 hours ago), 2022-01-26 17:25:45 -0800
    • Engine revision c248c6e38e
    • Dart version 2.17.0 (build 2.17.0-63.0.dev)
    • DevTools version 2.10.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by chipweinberger** [comment] 2022-01-27 11:14
Look at my last example, it reproduces even with statically sized box. Everything is Stateless.

**Comment by maheshmnj** [comment] 2022-01-27 11:45
Thanks for the code sample @chipweinberger, I can reproduce the issue on both stable and the master channel. However I see there is an issue already filed for this case https://github.com/flutter/flutter/issues/25652 Please follow up on this issue for further updates. Closing this issue as a duplicate.

**Closed by maheshmnj** 2022-01-27 11:45 UTC
Labels: in triage

**Comment by Piinks** [comment] 2022-01-27 21:00
Thanks @chipweinberger. I think this is expected behavior, you are changing the size of the scrollview dynamically every 30ms. Because of this, the scrollbar is going to update its position based on the change.

**Comment by Piinks** [comment] 2022-01-27 21:02
> How can the scroll bar for static items be broken?

What do you mean by static? In your code sample they are changing in size as a function of time.

The example where you have a fixed size of 8000 followed by 200, 200 200 is explained further in #25652

**Comment by chipweinberger** [comment] 2022-01-27 21:20
> I think this is expected behavior, you are changing the size of the scrollview dynamically every 30ms

Yes It makes sense that it jumps on the initial change. But, if I alter the first example (with the 30ms timer) to stop the timer after a few seconds, the scroll bar remains jumpy even after the timer stops (just like the first video).

That seems like unexpected (or at least not good) behavior. 

> What do you mean by static? In your code sample they are changing in size as a function of time.

Yes I was referring to my 2nd code example, with 8000 followed by 200, 200, 200. 

I will try the itemExtent you mentioned. Hopefully that will get me most of the way there. I will also need to figure out a solution for this requirement:
- The content on the screen does not shift downward if extend the items above it.

Apologies for tone in the other thread. No offense intended. I understand this stuff can be tricky to get right.

**Comment by Piinks** [comment] 2022-01-27 21:50
I played with it a bit, and found that if you increase the cacheExtent, you will get the behavior you desire:

<details>

  <summary> static size </summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);
  final ScrollController controller = ScrollController();

  Widget box(double height) {
    print('box($height)');
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        children: [
          Text("test $height"),
          SizedBox(
            height: height,
            width: 30,
            child: const DecoratedBox(
              decoration: BoxDecoration(color: Colors.red),
            ),
          ),
        ],
      ),
    );
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(scrollbarTheme: ScrollbarThemeData(
        thumbVisibility: MaterialStateProperty.all(true))),
        title: 'Jumpy Scrollbar',
        home: Scaffold(
          floatingActionButton: FloatingActionButton(
            onPressed: () => print(controller.position),
          ),
          appBar: AppBar(title: const Text('Jumpy Scrollbar')),
          body: ListView(
            controller: controller,
            cacheExtent: 8500,
            children: [
              box(8000),
              box(200),
              box(200),
              box(200),
            ]
          ),
        ));
  }
}
```

</details>


<details>

  <summary> changing size </summary>

On this one, the size is only updated for you first widget by that time function if it is still in range of being built. This is why you only see the scrollbar update when that item is in range, because of lazy loading. So if the first item is out of range, but continues getting larger and larger, the scroll metrics will not reflect that until it is built at its new size. If you want all of the list view items to stay alive, we have a KeepAlive option.

```dart
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    Widget widget = const FunkyList();

    return MaterialApp(
      title: 'Jumpy Scrollbar',
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Jumpy Scrollbar'),
        ),
        body: widget
      ),
    );

  }
}


class FunkyList extends StatefulWidget {
  const FunkyList({Key? key}) : super(key: key);
  @override
  createState() => _FunkyListState();
}

class _FunkyListState extends State<FunkyList> {
  late Timer _everyMillis;

  double _expandingHeight = 0;

  @override
  void initState() {
    super.initState();

    _everyMillis = Timer.periodic(const Duration(milliseconds: 30), (Timer t) {
      if (mounted) {
        setState(() {
          // increate the height of the first item in the ListView every 30ms
          _expandingHeight += 1.0;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
      isAlwaysShown: true,
      child: ListView.builder(
          itemCount: 40,
          cacheExtent: _expandingHeight + 200,
          itemBuilder: (context, index) {
            return Padding(
              padding: const EdgeInsets.all(16.0),
              child: SizedBox(
                // increate the height of the first item in the ListView every 30ms, otherwise 200
                height: index == 0 ? _expandingHeight : 200.0,
                width: 30,
                child: const DecoratedBox(
                  decoration: BoxDecoration(color: Colors.red),
                ),
              ),
            );
          }),
    );
  }
}
```

```dart
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    Widget widget = const FunkyList();

    return MaterialApp(
      title: 'Jumpy Scrollbar',
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Jumpy Scrollbar'),
        ),
        body: widget
      ),
    );

  }
}


class FunkyList extends StatefulWidget {
  const FunkyList({Key? key}) : super(key: key);
  @override
  createState() => _FunkyListState();
}

class _FunkyListState extends State<FunkyList> {
  late Timer _everyMillis;

  double _expandingHeight = 0;

  @override
  void initState() {
    super.initState();

    _everyMillis = Timer.periodic(const Duration(milliseconds: 30), (Timer t) {
      if (mounted) {
        setState(() {
          // increate the height of the first item in the ListView every 30ms
          _expandingHeight += 1.0;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
      isAlwaysShown: true,
      child: ListView.builder(
          itemCount: 40,
          // cacheExtent: _expandingHeight + 200,
          itemBuilder: (context, index) {
            return Padding(
              padding: const EdgeInsets.all(16.0),
              child: MyBox(size: index == 0 ? _expandingHeight : 200.0),
            );
          }),
    );
  }
}

class MyBox extends StatefulWidget {
  const MyBox({ Key? key, required this.size }) : super(key: key);

  final double size;

  @override
  MyBoxState createState() => MyBoxState();

}

class MyBoxState extends State<MyBox> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return SizedBox(
      // increate the height of the first item in the ListView every 30ms, otherwise 200
      height: widget.size,
      width: 30,
      child: const DecoratedBox(
        decoration: BoxDecoration(color: Colors.red),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;

}
```



</details>

I hope you will continue to explore Flutter. There are many different scrolling widgets and many different ways to use them. If you find in your learning that our documentation is lacking anywhere, please file an issue so we can improve it. :)

**Comment by Piinks** [comment] 2022-01-27 22:06
ListView.shrinkwrap is another option you might want in the case of your static example.

**Comment by chipweinberger** [comment] 2022-01-27 22:21
Appreciate all the suggestions and the welcome to the community, Kate.

I tried your last code sample (copied below for clarity) with and without cacheExtent but I still see the scroll bar to jump (after about 15 seconds of expansion):

```
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    Widget widget = const FunkyList();

    return MaterialApp(
      title: 'Jumpy Scrollbar',
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Jumpy Scrollbar'),
        ),
        body: widget
      ),
    );

  }
}


class FunkyList extends StatefulWidget {
  const FunkyList({Key? key}) : super(key: key);
  @override
  createState() => _FunkyListState();
}

class _FunkyListState extends State<FunkyList> {
  late Timer _everyMillis;

  double _expandingHeight = 0;

  @override
  void initState() {
    super.initState();

    _everyMillis = Timer.periodic(const Duration(milliseconds: 30), (Timer t) {
      if (mounted) {
        setState(() {
          // increate the height of the first item in the ListView every 30ms
          _expandingHeight += 1.0;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
      isAlwaysShown: true,
      child: ListView.builder(
          itemCount: 40,
          cacheExtent: _expandingHeight + 200,
          itemBuilder: (context, index) {
            return Padding(
              padding: const EdgeInsets.all(16.0),
              child: MyBox(size: index == 0 ? _expandingHeight : 200.0),
            );
          }),
    );
  }
}

class MyBox extends StatefulWidget {
  const MyBox({ Key? key, required this.size }) : super(key: key);

  final double size;

  @override
  MyBoxState createState() => MyBoxState();

}

class MyBoxState extends State<MyBox> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return SizedBox(
      // increate the height of the first item in the ListView every 30ms, otherwise 200
      height: widget.size,
      width: 30,
      child: const DecoratedBox(
        decoration: BoxDecoration(color: Colors.red),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;

}
```

The dynamic example of the first item expanding is the one my App really needs to get working right =)

I'm also considering implementing my own custom scroll bar entirely. I'd just need access to get / set the view coordinates of the scroll view. Does that seem like a good and doable solution to you? It would hopefully be more performant than using cache extent too.

**Comment by Piinks** [comment] 2022-01-27 23:55
Last one, unfortunately the github issue tracker is not meant for technical support, it is meant for issues with Flutter itself. I think your desired behavior can be achieved to different effects, and otherwise is covered by the other linked issue. This issue really peaked my curiosity today though. :)

> I tried your last code sample (copied below for clarity) with and without cacheExtent but I still see the scroll bar to jump (after about 15 seconds of expansion)

I see. In your video, you scroll far away from that top widget, so it is not updating with the expanded height. Since it is out of view and beyond the cache extent, the lazy loading list does not rebuild it, it doesn't need to because we can't see it. But in the meantime, your timer based _expandedHeight is still growing. When you scroll back up towards the top widget, it updates the _expandedHeight all at once so you see the jump. Do you mean to always have it growing? If so, see the solution below. If not, you may want to stop incrementing the height when the top widget is not visible.

I think I have your solution, but if not, I would definitely recommend checking out the community page of the website. We have a really great community you can ask questions or swap code with, from slack to discord, reddit and stackoverflow, there are links to all of these places here: https://flutter.dev/community

---

Here is what I came up with, using a CustomScrollView is probably most appropriate for your use case, separating your growing leading item from the rest. That way the rest of the list is built lazily, and the size of the expanding widget will continue smoothly.

Of course, since the top widget continues to grow, the scroll view will also be moving since it is continually expanding. 

If you do not want this behavior, then the earlier solutions should suit, but I would recommend not incrementing the size while the top widget is not visible, otherwise it will continue to 'grow' but update all at once later when the widget comes back into view, causing the undesired jump.

```dart
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    Widget widget = const FunkyList();

    return MaterialApp(
      title: 'Jumpy Scrollbar',
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Jumpy Scrollbar'),
        ),
        body: widget
      ),
    );

  }
}


class FunkyList extends StatefulWidget {
  const FunkyList({Key? key}) : super(key: key);
  @override
  createState() => _FunkyListState();
}

class _FunkyListState extends State<FunkyList> {
  late Timer _everyMillis;

  double _expandingHeight = 0;

  @override
  void initState() {
    super.initState();

    _everyMillis = Timer.periodic(const Duration(milliseconds: 30), (Timer t) {
      if (mounted) {
        setState(() {
          // increate the height of the first item in the ListView every 30ms
          _expandingHeight += 1.0;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
      isAlwaysShown: true,
      child: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: SizedBox(
                // increate the height of the first item in the ListView every 30ms, otherwise 200
                height: _expandingHeight,
                width: 30,
                child: const DecoratedBox(
                  decoration: BoxDecoration(color: Colors.red),
                ),
              ),
            )
          ),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (context, index) {
                return const Padding(
                  padding: EdgeInsets.all(16.0),
                  child: SizedBox(
                    height: 200.0,
                    width: 30,
                    child: DecoratedBox(
                      decoration: BoxDecoration(color: Colors.red),
                    ),
                  ),
                );
              },
              childCount: 39,
            ),
          ),
        ],
      ),
    );
  }
}
```

I hope you enjoy the community, we are very welcoming. Thanks for sharing your use case. 😄

**Comment by chipweinberger** [comment] 2022-01-28 00:48
> really peaked my curiosity today though. :)

Yes, I've been having a fun time trying to get this to work too. Thanks for helping on it!

Just tried your solution and it seems so good! Apart from the always scrolling down issue. Also, I wonder if it will still hit #25652 with real data the 39 lower boxes are all different (but static) sizes. 

> your timer based _expandedHeight is still growing. When you scroll back up towards the top widget, it updates the _expandedHeight all at once so you see the jump. Do you mean to always have it growing?

Yes. The list is expands when Bluetooth LE messages arrive with new time series data. So in effect it is always able to expand, even when not visible or in the active region of the ListView.

> Of course, since the top widget continues to grow, the scroll view will also be moving since it is continually expanding.

I have a work around for this. Super hacky, but:
1. I instead of append to the top, append to the bottom of the list. 
2. wrap the scroll view in a 180 transform, so that bottom becomes top
3. flip each List item 180 degrees as well.  

**My Solution:** 
This is the closest I've gotten, using your keepAlive & cacheExtent trick, & my double mirror trick. But it still becomes jumpy when each lower item it not the same size (and the scroll bar is now on the wrong side, but thats more minor IMO hah)

**Next Steps:**
Trying ListView.itemExtent to handle different sized (static) boxes. I really hope the Flutter team has time to improve scroll bars for more advanced use cases in the upcoming releases =) I feel like there is a lot of fertile ground here for improvement. 

```
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    Widget widget = const FunkyList();

    return MaterialApp(
      title: 'Jumpy Scrollbar',
      theme: ThemeData(
        primarySwatch: Colors.red,
      ),
      home: widget,
    );
  }
}

class FunkyList extends StatefulWidget {
  const FunkyList({Key? key}) : super(key: key);
  @override
  createState() => _FunkyListState();
}

class _FunkyListState extends State<FunkyList> {
  late Timer _everyMillis;
  double _expandingHeight = 0;

  @override
  void initState() {
    super.initState();

    _everyMillis = Timer.periodic(const Duration(milliseconds: 30), (Timer t) {
      if (mounted) {
        setState(() {
          // increate the height of the first item in the ListView every 30ms
          _expandingHeight += 1.0;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Jumpy Scrollbar'),
        ),
        body: Transform(
            alignment: FractionalOffset.center, // set transform origin
            transform: Matrix4.rotationZ(180 / 57.2958), // rotate -10 deg
            child: Scrollbar(
              isAlwaysShown: true,
              child: ListView.builder(
                  itemCount: 40,
                  cacheExtent: _expandingHeight + 200,
                  itemBuilder: (context, index) {
                    return Transform(
                      alignment: FractionalOffset.center, // set transform origin
                      transform:
                          Matrix4.rotationZ(180 / 57.2958), // rotate -10 deg
                      child: Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Column(
                          children: [
                            Text('$index'),
                            MyBox(size: index == 39 ? _expandingHeight : 200.0),
                            // closer to real data: each lower item can be a unique static size
                            // MyBox(size: index == 39 ? _expandingHeight : (index * 50.0)),
                          ],
                        ),
                      ),
                    );
                  }),
            )));
  }
}

class MyBox extends StatefulWidget {
  const MyBox({Key? key, required this.size}) : super(key: key);
  final double size;
  @override
  MyBoxState createState() => MyBoxState();
}

class MyBoxState extends State<MyBox> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return SizedBox(
      // increate the height of the first item in the ListView every 30ms, otherwise 200
      height: widget.size,
      width: 30,
      child: const DecoratedBox(
        decoration: BoxDecoration(color: Colors.red),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}
```
