### ISSUE TITLE
MessageChannel hits ByteData.getFloat64 alignment crash on ARM

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10701] opened 2017-06-14 19:21 UTC
I've been experiencing mid-session crashes that started yesterday. There's little detail in the output when the crash occurs. I don't seem to be experiencing the same type of crash on iOS.

IntelliJ
```
F/libc    (14696): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc4983159 in tid 14726 (ui_thread)
Lost connection to device.
```

Android Studio Logcat
```
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc4983159 in tid 14726 (ui_thread)
                                                        
[ 06-14 14:48:47.689   569:  569 W/         ]
debuggerd: handling request: pid=14696 uid=10419 gid=10419 tid=14726
```

```
☆ flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision ede575a92e (3 hours ago), 2017-06-14 09:05:53 -0700
    • Engine revision 4f5d6fab11
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 9.0, Build version 9M136h
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Pixel        • FA71A0302167                             • android-arm • Android 7.1.2 (API 25)
    • Posse iPhone • ac24c3de3cbe39efed542095769ce83fc89630f7 • ios         • iOS 10.3.1 (14E304)
    •              • c0e109b7e55a826627aa0f3e79af8931534f3554 • ios         • iOS  ()
```

**Comment by eseidelGoogle** [comment] 2017-06-14 19:41
Presumably a regression from the last engine roll?

**Comment by eseidelGoogle** [comment] 2017-06-14 19:42
https://github.com/flutter/flutter/commit/b4ba972bf394a2269824e1eadaa1627bbc872d4b was the last engine roll.  FYI @tvolkert 

It's also possible this a plugin crashing?

We'll need to get a stack trace to diagnose I suspect.

**Comment by eseidelGoogle** [comment] 2017-06-14 19:43
https://github.com/flutter/flutter/issues/10674 was another crash report we saw come in last night, but is likely unrelated.

**Comment by tvolkert** [comment] 2017-06-14 19:47
Doesn't look like a plugin crash, but logcat output would be helpful.  `adb bugreport > bugreport.txt` would be comprehensive.

**Comment by alardizabal** [comment] 2017-06-14 20:15
Here you go.
[bugreport-NHG47L-2017-06-14-15-55-31.zip](https://github.com/flutter/flutter/files/1075809/bugreport-NHG47L-2017-06-14-15-55-31.zip)

**Comment by eseidelGoogle** [comment] 2017-06-14 20:24
@tvolkert  we should be able to symbolicate the crashes with https://github.com/flutter/engine/wiki/Symbolicating-production-crash-stacks

**Comment by eseidelGoogle** [comment] 2017-06-14 21:18
@tvolkert is looking now.

**Comment by tvolkert** [comment] 2017-06-14 21:19
Actually it's @jason-simmons :-)

**Comment by tvolkert** [comment] 2017-06-15 01:43
@alardizabal can you see if you can reproduce this against the latest alpha or master?  We [reverted](https://github.com/flutter/flutter/pull/10711) a change that was identified as the culprit in a few regressions, and I have a suspicion that reverting it may have fixed this too.

**Comment by alardizabal** [comment] 2017-06-15 13:59
@tvolkert I just pulled the latest master and I'm still experiencing the same crash.

**Comment by jason-simmons** [comment] 2017-06-15 20:17
Took a look at the tombstones.  It looks like this is an unaligned memory access that occurs while trying to deserialize a 64-bit float in a message send by a plugin.

The plugin message seen in the crash is a map containing two fields.  If you change the field values from doubles to strings on the Java side and then convert the data back into floats on the Dart side, then does the crash still happen?

The message codec uses the Dart ByteData API to decode primitive types.  My understanding is that ByteData.getFloat64 may be optimized to do a simple read regardless of alignment, and that the read may be unsafe in ARM cores seen on some devices.

Looks like this is a known issue in Dart, e.g. https://github.com/dart-lang/sdk/issues/23953

One option would be changing the Flutter message codec to insert padding to align all values.  This would probably also improve performance.

**Comment by jason-simmons** [comment] 2017-06-16 17:05
This should be fixed now

**Closed by jason-simmons** 2017-06-16 17:05 UTC
Labels: crash, customer: posse (eap), regression
