### ISSUE TITLE
Transform widget is broken in master

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#19062] opened 2018-07-04 03:37 UTC
The current master branch of Flutter seems to have a bug in the Transform widget that breaks rendering. See issue 18376 for more information (this new issue is not redundant, issue 18376 is for a separate bug but in trying to fix it this new bug was uncovered).

This new bug breaks the app developed in the article https://medium.com/flutter-io/perspective-on-flutter-6f832f4d912e

Switching to flutter channel beta fixes the bug.

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.7-pre.50, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] Connected devices (1 available)

• No issues found!

**Comment by jonahwilliams** [comment] 2018-07-04 05:46
I can reproduce this in both a physical android device and on an iOS simulator.

**Comment by wmleler** [comment] 2018-07-04 14:01
Same here. Tested on physical Pixel 2 XL and iOS simulator. Both fail.
You can see this easier if you run the following gist (also from the article linked above) -- https://gist.github.com/wmleler/cfc18137ce7db77d7e599e179dee4619#file-main2-dart
The app is initially rendered correctly. Do a drag gesture on the screen and the app will rotate in 3D, but the app itself will stop rendering. If you double-tap on the screen, then the rotation is reset and the app will again be rendered correctly.

**Comment by jonahwilliams** [comment] 2018-07-05 05:13
This was introduced by me in f5f055113ad92836985f36d4adabddb6a22e2c5c.  Removing the insertion of an AnnotatedRegionLayer into the layer tree fixes the issue.  Still investigating what the cause is.

**Comment by jonahwilliams** [comment] 2018-07-05 05:37
I've narrowed down the issue to a problem in the `RenderAnnotatedRegion`:

Removing the addition of the annotated region layer does not fix the transform issue.
```
  @override
  void paint(PaintingContext context, Offset offset) {
    if (child != null) {
      final AnnotatedRegionLayer<T> layer = new AnnotatedRegionLayer<T>(value, size: sized ? size : null);
      //context.pushLayer(layer, super.paint, offset);
      super.paint(context, offset);
    }
  }
```

Only if `alwaysNeedsCompositing` is also set to false does the transform being working again.  Setting `alwaysNeedsCompositing` to true when the layer is still added cause exceptions to be thrown, but only breaks the transform for the appBar.

**Comment by jonahwilliams** [comment] 2018-07-05 05:43
The error message is:
```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following message was thrown during paint():
flutter: Object has been disposed.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Canvas.restore (dart:ui/painting.dart:2879:41)
flutter: #1      RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1645:16)
flutter: #2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2024:7)
flutter: #3      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:127:15)
flutter: #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2024:7)
flutter: #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
```

**Comment by jonahwilliams** [comment] 2018-07-05 20:48
This error can be reproduced by placing the following render object into an application.  If `alwaysNeedsCompositing` is `true`, then the screen goes blank when a rotation is applied.  If `false`, then the transform does not update the children.

```dart

class RenderAncestor extends RenderProxyBox {
  @override
  bool get alwaysNeedsCompositing => true; 

  @override
  void paint(PaintingContext context, Offset offset) {
    context.pushLayer(new OffsetLayer(), super.paint, offset);
    //super.paint(context, offset);
  }
```

**Comment by jonahwilliams** [comment] 2018-07-06 01:12
I checked against some commits in early jun and may and I can still reproduce the error with the above snippet

**Comment by jonahwilliams** [comment] 2018-07-06 02:52
This is also doesn't happen if the perspective line is removed

```dart
Matrix4.identity()
        //..setEntry(3, 2, 0.001) // perspective - removed
        ..rotateX(0.01 * _offset.dy) // changed
        ..rotateY(-0.01 * _offset.dx), 
```

**Comment by jonahwilliams** [comment] 2018-07-06 02:53
... it also doesn't happen if you set that entry after the rotations... I'm thinking this might not be a bug

**Comment by wmleler** [comment] 2018-07-06 15:57
Matrix multiplication is not commutative. Moving the setEntry method call
after the rotations is not a workaround because the perspective doesn't
happen if you do that.

This code, with the perspective line first, has worked for at least 8
months. It still works just fine in the current beta version. I know of at
least two articles that have been published using this code. So this
definitely looks like a bug.

**Comment by jonahwilliams** [comment] 2018-07-06 16:06
@wmleler Right, moving the perspective produces an entirely different matrix - But that matrix renders correctly.  So for some reason the particular matrix being generated by the example does not work in general, but only with certain render objects as children.  So you're right, it's a bug somewhere, but it wasn't introduced recently.

**Comment by jonahwilliams** [comment] 2018-07-06 16:45
A more minimal reproduction:

```dart

class Example extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final matrix = Matrix4.identity();
    matrix.setEntry(3, 0, 0.0003);
    return Transform(  // Transform widget
      transform: matrix, // changed
      alignment: FractionalOffset.center,
      child: new Ancestor( // remove and it renders correctly
        child: new Material(
          child: new Container(
            color: Colors.red,
            width: 200.0,
            height: 200.0,
          ),
        ),
      ),
    );
  }
}


class Ancestor extends SingleChildRenderObjectWidget {
  const Ancestor({Widget child, Key key}): super(child: child, key: key);
  
  @override
  RenderObject createRenderObject(BuildContext context) {
    return new RenderAncestor();
  }
}

class RenderAncestor extends RenderProxyBox {
  @override
  bool get alwaysNeedsCompositing => true; 

  @override
  void paint(PaintingContext context, Offset offset) {
    context.pushLayer(new OffsetLayer(), super.paint, offset);
  }
}

```

**Comment by wmleler** [comment] 2018-07-06 17:01
If it wasn't introduced recently, why did it work just fine for at least 8
months and then suddenly stop working recently? I've been using this
program as a demo for a long time.

**Comment by jonahwilliams** [comment] 2018-07-06 17:15
Because I can checkout a commit from two months ago and reproduce the issue with the reduced sample above.  A few weeks ago I changed the app bar which results in the addition of a new layer, that is what caused your code to stop working.  But removing that won't fix the underlying issue, which is what I am trying to do.

**Comment by wmleler** [comment] 2018-07-06 17:28
That's fine. I was just concerned because when you said maybe this isn't a
bug, it sounded like you didn't think it needed to be fixed.

I look forward to having my code work again soon!

Thanks.

**Comment by jonahwilliams** [comment] 2018-07-06 17:31
Ahh sorry about that, just the ramblings of someone who spent too long debugging.  Though it is obviously not ideal, removing the appBar from the demo will make it work again for now

**Comment by wmleler** [comment] 2018-07-06 18:36
Updating the code in published articles probably isn't a good option. I
hope you figure this out and fix it soon. Thanks again.

**Comment by jonahwilliams** [comment] 2018-07-06 21:03
The difference in removing/adding the `AncestorWidget` is in whether the `TransformLayer` uses `pushLayer` or `canvas.transform`.  If it is the former, because a child needs to be recompositied, then it uses the transform matrix and the current painting context to estimate the paint bounds for the layer.

According to the engine timeline, when the view isn't painted it is because all of the child paint bounds are empty.  The problem might lie in how these bounds are computed or shared between flutter and the engine.  For reference, a normal frame (top) and a frame with a perspective (bottom). After the preroll which computes bounds, none of the layers are painted

<img width="1123" alt="screen shot 2018-07-06 at 1 58 36 pm" src="https://user-images.githubusercontent.com/8975114/42400122-39f6706a-8125-11e8-94df-a78ea181be5f.png">
<img width="1009" alt="screen shot 2018-07-06 at 1 59 15 pm" src="https://user-images.githubusercontent.com/8975114/42400124-3bf39e4c-8125-11e8-8167-17234019977c.png">

**Comment by jonahwilliams** [comment] 2018-07-08 03:36
While I assumed the Flutter runners layer tree dump was accurate, what is actually happening is that the DefaultLayerBuilder is not adding the child picture layer when its picture doesn't intersect with the current cullRect.

https://github.com/flutter/engine/blob/f52955c2558a8bc2539192f88d84fe7d339f5d4b/flow/layers/default_layer_builder.cc#L146-L150

The transformLayer updates the cullRect by inverting its transformation and applying this to the current cullRect to produce a new cullRect. (The cullRect beings with the `kGiantRect`)

https://github.com/flutter/engine/blob/f52955c2558a8bc2539192f88d84fe7d339f5d4b/flow/layers/default_layer_builder.cc#L38-L44

When there is no perspective transform applied, the cullRect produced might look something like `Rect.LTRB{-3.33333e+08, -4.71228e+09, 3.33333e+08, 4.71227e+09}`, whereas with a perspective we end up will a cullRect like `Rect.LTRB{-793.003, -13768.9, -792.997, 14504.9}`.  Since the picture doesn't intersect, it isn't drawn. If the TransformLayer doesn't have another child layer, then none of this happens, since it uses the canvas.transform instead.  

A reasonable approach might be to detect perspective transforms  just default to the either the kGiantRect or the previous element of the cull rect stack.  (Another possibility is that there is some math is subtly wrong here )

https://github.com/google/skia/blob/dd962a95c5f21cba18a8ef90f2a6f974e2968142/include/core/SkMatrix.h#L1443

**Comment by wmleler** [comment] 2018-07-08 17:21
Flutter does have a function makePerspectiveMatrix that creates a new
OpenGL perspective matrix. I wonder if using this instead would cause the
same problem? If not, then its implementation might yield some helpful
insights.

I don't use that function because I'm not dealing with a scene with a field
of view or near and far planes. The transformation I'm using is pretty
standard (I've done a lot of 3D graphics, and even wrote a book on it).

I'm looking at the implementation of makePerspectiveMatrix and it just
calls setPerspectiveMatrix, which does the real work. That code sets the
scaling -- entries (0,0), (1,1), (2,2) -- which are safe to ignore. It then
sets (3,2) to a constant –1.0 (that's the entry I set to 0.001), and then
sets (2,3) to an expression.

I'd play around with this, but I'm leaving on a trip tomorrow morning to
give some talks and don't have time.

**Closed** 2018-07-09 19:52 UTC
Labels: engine, severe: regression
