### ISSUE TITLE
Real onPause() method for flutter?

### ISSUE THREAD

**Issue by shaheenzahedi** [flutter/flutter#20075] opened 2018-08-01 11:48 UTC
I'm already familiar with `WidgetsBindingObserver` but you cannot do anything before pause method's going to execute, For example I wanted to save a state before pausing the app(Like below), it will execute just first lines of `saveLocalStorage()` method.

```dart
class _GameBoard extends State<GameBoard> with WidgetsBindingObserver {

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state.index == AppLifecycleState.paused.index) {
      saveLocalStorage();
    }
    super.didChangeAppLifecycleState(state);
  }
....
}
```
I don't know what exactly is happening here but when I call `saveLocalStorage()` from anywhere else it works just fine.

**Comment by zoechi** [comment] 2018-08-01 11:53
That's probably because you are not `await`ing `Future`s.

**Comment by shaheenzahedi** [comment] 2018-08-01 11:59
@zoechi  here  is the implementation of `saveLocalStorage()` 
```
 Future<void> saveLocalStorage() async {
    final storage = new FlutterSecureStorage();
    await storage.write(key: 'steps', value: GameRedux.steps.toString());
    
    String encode = JSON.encode(GameRedux.getBoardState().toJson());
    GameRedux.setSt(encode, null);
    await storage.write(key: 'tiles', value: encode);
  }
```

**Comment by shaheenzahedi** [comment] 2018-08-01 12:49
@zoechi now here's the implementation
```
@override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    if (state.index == AppLifecycleState.paused.index) {
      await saveLocalStorage();
    }
    super.didChangeAppLifecycleState(state);
  }
```
but nothing has changed, I have no idea.
although I tried calling this method on a `onPressed()` of a button, it worked like a charm(without await and async calling).

**Comment by zoechi** [comment] 2018-08-01 14:55
Sorry, out of ideas. Perhaps someone else.

**Comment by jonahwilliams** [comment] 2018-08-01 17:30
It's not possible to prevent a lifecycle transition from occurring, on either native iOS or Android - hence why this continues after the await.  Furthermore, neither platform guarantees that any lifecycle notifications will be received - since your app may be killed at any time.

If you have important data you would like to persist - you should do so when it is created. This is the best way to guard against data loss in a real environment.

**Comment by shaheenzahedi** [comment] 2018-08-01 17:39
@j9brown thanks for the advice, TBH I thought of that already, but there is a paradox here:
The data I am trying to persist is really critical, AND I have time problems bcz the app itself is slow enough, and amount of changes I am making is too much so the app needs to go for saving the changed data which is another expensive thing to do. I came up with a situation like using `onPause()` method, what will you suggest for this scenario?

**Comment by jonahwilliams** [comment] 2018-08-02 00:14
You know your app better than I do - so the only advice I can really give is save the important data when it is created.  Another approach might be to figure out what data _isn't_ important and avoid saving that. There is nothing actionable here for us though, because we cannot change how iOS or Android behave in this regard.

**Comment by zoechi** [comment] 2019-01-29 12:58
Closing as working as intended.

See also #22328 #6827 for similar issues.

**Closed by zoechi** 2019-01-29 12:58 UTC
Labels: framework
