### ISSUE TITLE
TextInputFormatter is given wrong data

### ISSUE THREAD

**Issue by rafalbednarczuk** [flutter/flutter#42806] opened 2019-10-15 23:37 UTC
[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.4)
Device: Nexus 5, Android 6.0.1

code:
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            body: Center(
      child: TextField(
        keyboardType: TextInputType.number,
        inputFormatters: [AddTextFormatter()],
      ),
    )));
  }
}

class AddTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
    final newText =
        newValue.text + (DateTime.now().millisecond % 10).toString();
    print("${oldValue.text}:${newValue.text}:$newText:${newText.length}:");

    return newValue.copyWith(text: newText);
  }
}
```
output after typing **one** sign in keyboard: 

```
I/flutter (11682): :5:55:2:
I/flutter (11682): 55:5:58:2:
I/flutter (11682): 58:55:550:3:
I/flutter (11682): 550:58:585:3:
W/IInputConnectionWrapper(11682): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(11682): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(11682): getTextAfterCursor on inactive InputConnection
I/flutter (11682): 585:550:5501:4:
I/flutter (11682): 5501:585:5856:4:
I/flutter (11682): 5856:5501:55012:5:
I/flutter (11682): 55012:5856:58564:5:
I/flutter (11682): 58564:55012:550121:6:
W/IInputConnectionWrapper(11682): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(11682): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(11682): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(11682): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(11682): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(11682): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(11682): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(11682): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(11682): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(11682): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(11682): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(11682): getTextAfterCursor on inactive InputConnection

```

There should be only one flutter print after one sign typed in keyboard.
There is always same scenario with this bug:
User type _x_ sign. _TextInputFormatter_ gets empty string as old value and _x_ as new value. Then _TextInputFormatter_ returns _TextEditingValue_ with longer text. It works as it should be. But then _TextInputFormatter_ gets longer text as old value and _x_ sign as new value. And this is the bug.

**Comment by HansMuller** [comment] 2019-10-16 17:29
I'm closing this as a duplicate of #41005, see  https://github.com/flutter/flutter/issues/41005#issuecomment-542466751

We are actively working on this problem.

**Closed by HansMuller** 2019-10-16 17:29 UTC
Labels: a: text input, f: material design, framework
