### ISSUE TITLE
in flutter web platform, the ui  scroll slowly!

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#47075] opened 2019-12-15 10:23 UTC
device: iphone 8 pl
browser: safari
image widget: Image.network

if flutter can provide a network  image widget than can cache network image ?, if so,  I thank it will make better.

**Comment by tjerkw** [comment] 2019-12-17 08:33
I think this is a duplicate of https://github.com/flutter/flutter/issues/42987

**Comment by qiuguian** [comment] 2019-12-18 00:07
When the page is complex and there are many components, many canvas s will be generated. When a certain amount of memory is reached, the maximum value of canvas will be exceeded in phone's safari


![image](https://user-images.githubusercontent.com/7962840/71044516-c6941700-216c-11ea-9c96-0eeb3f1eff0d.png)

**Comment by iapicca** [comment] 2019-12-18 13:03
Hi @qiuguian 
as @tjerkw  pointed out (thanks) 
there's an open issue addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2019-12-18 13:03 UTC
Labels: d: stackoverflow
