### ISSUE TITLE
SystemChrome.setPreferredOrientations not working on iPad

### ISSUE THREAD

**Issue by yakuraku** [flutter/flutter#66533] opened 2020-09-24 07:02 UTC
When I try to set the orientation of my app with `SystemChrome.setPreferredOrientations([DeviceOrientation.landscapeLeft, DeviceOrientation.landscapeRight])` it works on my Android Phone and iPhone, but not on the iPad. On the iPad the device stays in landscape mode.

**Comment by darshankawar** [comment] 2020-09-24 08:36
Hi @yakuraku,
Please see [this](https://github.com/flutter/flutter/issues/27235) issue and [this](https://github.com/flutter/flutter/issues/27235#issuecomment-530726236) comment on it. The behavior you are seeing is not a bug and same has been [documented](https://api.flutter.dev/flutter/services/SystemChrome/setPreferredOrientations.html).

I am closing this as not an issue. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-24 08:36 UTC
