### ISSUE TITLE
iphone 13 SDK missing from LUCI mac bots

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68144] opened 2020-10-14 22:02 UTC
For example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866428577751065856/+/steps/run_build_ios_framework_module_test/0/stdout

```
[build_ios_framework_module_test] [STDOUT] stdout: 
[build_ios_framework_module_test] [STDOUT] stdout: Xcode's output:
[build_ios_framework_module_test] [STDOUT] stdout: ↳
[build_ios_framework_module_test] [STDOUT] stdout:     note: Using new build systemnote: Planning buildnote: Constructing build descriptionerror: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'package_info' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'package_info' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'device_info' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'device_info' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'Pods-Runner' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'Pods-Runner' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'Flutter' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'Flutter' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'Runner' from project 'Runner')error: unable to find sdk 'iphoneos13.0' (in target 'Runner' from project 'Runner')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'FlutterPluginRegistrant' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'FlutterPluginRegistrant' from project 'Pods')
[build_ios_framework_module_test] [STDOUT] stdout: 
[build_ios_framework_module_test] [STDOUT] stderr: 
```

**Comment by keyonghan** [comment] 2020-10-14 22:17
Checked recent pre-submit runs of this builder, finding both successful and failed build on a same bot:
https://ci.chromium.org/p/flutter/builders/try/Mac%20build_ios_framework_module_test/567
https://ci.chromium.org/p/flutter/builders/try/Mac%20build_ios_framework_module_test/554
@godofredoc Where do you see any flaky part?

**Comment by godofredoc** [comment] 2020-10-14 23:56
Do these flakes started on 10/12 at ~1:00 PM?

**Comment by keyonghan** [comment] 2020-10-15 00:06
> Do these flakes started on 10/12 at ~1:00 PM?

The first failure with this error happened around 10/13 8:10pm. Then also failed three times today.
https://ci.chromium.org/p/flutter/builders/try/Mac%20build_ios_framework_module_test?limit=200

**Comment by jonahwilliams** [comment] 2020-10-15 21:35
here is another instance happening today: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866339011711441488/+/steps/run_module_test_ios/0/stdout

**Comment by godofredoc** [comment] 2020-10-15 22:13
@godofredoc  to share the changes that may causing this.

**Comment by godofredoc** [comment] 2020-10-19 16:31
Moving this bug as a P0 as it is a major source of flakiness in the sdk.

**Comment by godofredoc** [comment] 2020-10-19 16:44
This is happening just after an engine ios build fail. Using as example:

 https://chromium-swarm.appspot.com/bot?id=build818-m9

It first failed an ios engine task:

https://chromium-swarm.appspot.com/task?id=4f4c984f02863d10

And after that it failed with the ios not found error:
 
https://ci.chromium.org/p/flutter/builders/prod/Mac%20SDK%20Drone/4097?

There are several things we need to fix:

* Ios engine build is installing xcode twice.
* When xcode fails the contexts are not cleaning up e.g in https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/7338 I would expect steps deleting the symlinks.

**Comment by godofredoc** [comment] 2020-10-19 16:45
\cc @LongCatIsLooong @keyonghan

**Comment by LongCatIsLooong** [comment] 2020-10-19 16:57
https://flutter-review.googlesource.com/c/recipes/+/6960/15/recipe_modules/flutter_osx_sdk/api.py I thought the last line should do it? Or do I need to embed that in a "try ... finally" statement?

**Comment by LongCatIsLooong** [comment] 2020-10-19 17:54
@godofredoc thanks for the diagnosis! The fix CL is up for review.  But I didn't address the double Xcode installation step (as it doesn't seem critical at the moment?).

**Comment by godofredoc** [comment] 2020-10-19 20:40
Thanks @LongCatIsLooong for the fix. Here is the link to the CL:

https://flutter-review.googlesource.com/c/recipes/+/7780

**Comment by godofredoc** [comment] 2020-10-20 01:04
Moving to P1 as the fix has landed.

**Comment by jmagman** [comment] 2020-10-22 21:25
I saw this again today https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865709664161227520/+/steps/run_test.dart_for_build_tests_shard_and_subshard_1_last/0/stdout

**Comment by godofredoc** [comment] 2020-10-24 02:19
Caches from the following machines were cleaned up manually:

Try:
build856-m9
build830-m9
build837-m9
build842-m9
build829-m9

Prod:
build797-m9
build815-m9
build809-m9
build825-m9
build806-m9
build810-m9
build813-m9

**Comment by jonahwilliams** [comment] 2020-10-26 20:37
Just happened again in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865346074475118656/+/steps/run_module_test_ios/0/stdout

**Comment by godofredoc** [comment] 2020-10-28 04:35
Cleaned the cache of build820-m9

**Comment by godofredoc** [comment] 2020-10-28 04:35
Please reopen if you find another machine with this problem.

**Comment by jonahwilliams** [comment] 2020-10-29 16:46
This happened today on https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865089364464722736/+/steps/run_build_ios_framework_module_test/0/stdout

**Comment by godofredoc** [comment] 2020-10-29 17:39
Manually cleaned the cache of build816-m9, please reopen for new ones.

**Comment by jonahwilliams** [comment] 2020-10-29 23:40
Happened again on https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865062961740942240/+/steps/run_module_test_ios/0/stdout

**Comment by godofredoc** [comment] 2020-11-03 03:15
Bot build796-m9.golo was cleaned up.

**Comment by jmagman** [comment] 2020-11-03 18:25
This happened again on build390-m9 https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8864629808132264784/+/steps/run_plugin_lint_mac/0/stdout

**Comment by jonahwilliams** [comment] 2020-11-03 18:31
I do not think this problem is solved. Cleaning the bots every time this breaks is not a scalable solution either.

Can we rethink what we are doing with Xcode? Do we need to isolate the engine and framework bots?

**Comment by godofredoc** [comment] 2020-11-03 20:03
Adding some context here:

We added a hack to the xcode installations to support ios sdk 14 with xcode 11 version(flutter desktop requirement in the engine). This hack is creating a symbolic link to a temporary folder and the new logic in case of builder failures didn't delete the symbolic link. That problem was already fixed but many machines were left with that symbolic link in place, the first few days we manually deleted the symbolic link from the machines that were failing and the failure rate decreased to once every other day.

The reason we have been documenting in this bug the machines we have been cleaning is to ensure the problem does not exist anymore and we are only getting errors from machines that were left on that state a few weeks ago. The right thing to do is to clean all the machines but that is kind of expensive in resources: ~5 mins per machine x 120.

Please let me know if we believe this is happening frequently enough to spend that time on cleaning up all the machines and we'll start the process.

Meanwhile I cleaned build390-m9 machine.

**Comment by jmagman** [comment] 2020-11-03 20:46
Hit on build293-m9
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8864629807184864240/+/steps/run_build_ios_framework_module_test/0/stdout

**Comment by godofredoc** [comment] 2020-11-03 22:05
Cleaned build293-m9.golo. I just remembered we are reprovisioning all the machines to 10.15.7 which will delete all the previous data.

**Comment by jmagman** [comment] 2020-11-04 18:10
build387-m9 https://ci.chromium.org/p/flutter/builders/prod/Mac%20module_test_ios/629

**Comment by keyonghan** [comment] 2020-11-04 18:14
Just requested bots upgrading for all remaining 10.15.6. https://github.com/flutter/flutter/issues/69730

**Comment by godofredoc** [comment] 2020-11-06 23:12
All the prod mac bots were reprovisioned to 10.15.7 and this issue should not happen anymore in prod.

**Comment by godofredoc** [comment] 2020-11-06 23:13
\cc @keyonghan what is the plan for try machines?

**Comment by keyonghan** [comment] 2020-11-06 23:26
All try bots have been with 10.15.7 as well: https://github.com/flutter/flutter/issues/69730

**Comment by godofredoc** [comment] 2020-11-06 23:28
Thanks, then closing this bug as it should not happen anymore.

**Comment by christopherfujino** [comment] 2020-11-13 19:18
Re-occurred during a stable build:

```
[        ] Xcode's output:
           ↳
[        ]     Command line invocation:
                   /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/usr/bin/xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/opt/s/w/ir/k/flutter/examples/platform_channel/build/ios -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO "CODE_SIGNING_IDENTITY=\"\"" FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO

               Build settings from command line:
                   BUILD_DIR = /opt/s/w/ir/k/flutter/examples/platform_channel/build/ios
                   CODE_SIGNING_ALLOWED = NO
                   CODE_SIGNING_IDENTITY = ""
                   CODE_SIGNING_REQUIRED = NO
                   COMPILER_INDEX_STORE_ENABLE = NO
                   FLUTTER_SUPPRESS_ANALYTICS = true
                   SDKROOT = iphoneos13.6
                   VERBOSE_SCRIPT_LOGGING = YES

               note: Using new build system
               note: Building targets in parallel
               note: Planning build
               note: Constructing build description
               error: unable to resolve run destination SDK: 'iphoneos13.6' (in target 'Runner' from project 'Runner')
               error: unable to find sdk 'iphoneos13.6' (in target 'Runner' from project 'Runner')
```

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20SDK%20Drone/6961/overview

**Comment by keyonghan** [comment] 2020-11-13 19:36
Cleared the cache on build394-m9

**Comment by LongCatIsLooong** [comment] 2020-11-13 19:38
Could there be an issue with the recipe? The relevant code can be found [here](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/flutter_osx_sdk/api.py). The `_additional_ios_sdk` step is where the additional sdk gets symlinked to xcode. I guess the error happens when the symlink somehow leaks into the next job, but not sure how exactly this can happen since the cleanup is done in a `finally` clause.

**Comment by pcsosinski** [comment] 2020-11-14 05:03
happening on the beta builders (1.24) now as well: https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_lint_mac/1285?

**Comment by dnfield** [comment] 2020-11-18 05:49
Another one https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863328391455486464/+/steps/run_test.dart_for_build_tests_shard_and_subshard_0/0/stdout#L23291_0

**Comment by dnfield** [comment] 2020-11-18 06:20
https://ci.chromium.org/p/flutter/builders/prod/Mac%20build_gallery/521 on post submit, making the tree red.

**Comment by godofredoc** [comment] 2020-11-18 22:13
Closing this bug as the problem is different and creating a new one to track the issue https://github.com/flutter/flutter/issues/70793

**Closed by godofredoc** 2020-11-18 22:13 UTC
Labels: P1, passed first triage, passed secondary triage, team: infra
