### ISSUE TITLE
TextField in ReorderableListView cannot be focused

### ISSUE THREAD

**Issue by LehemYang** [flutter/flutter#25867] opened 2018-12-29 07:02 UTC
## Description
I had refer issues #20699, #25836, #25839 before, but could not get any useful information.

## Steps to Reproduce

1. create a Widget before target Widget
2. navigate to target Widget which contains ReorderableListView
3. click TextField in ReorderableListView

![reproduction](https://user-images.githubusercontent.com/14569638/50534145-8ca0be00-0b73-11e9-9cb9-7f26db4ae64f.gif)

#  Minimal Runnable Reproduction
/lib/main.dart
```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TapClass(),
    ));

class TapClass extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: FlatButton(
        child: Text('click me'),
        onPressed: () {
          Navigator.of(context)
              .push(MaterialPageRoute(builder: (context) => MyHomePage()));
        },
      ),
    ));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('title here'),
        ),
        body: ReorderableListView(
          children: <Widget>[
            Row(
              key: ValueKey('key'),
              children: <Widget>[
                Expanded(
                  child: TextField(
                    decoration: InputDecoration(hintText: 'type in'),
                  ),
                )
              ],
            )
          ],
          onReorder: (int oldIndex, int newIndex) {},
        ));
  }
}
```

## Doctor
```
[✓] Flutter (Channel master, v1.0.1-pre.1, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.0.1-pre.1 at /Users/Lehem/Documents/Flutter/flutter-github
    • Framework revision a226c0f0d9 (4 weeks ago), 2018-11-30 16:18:18 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/Lehem/Library/Android/sdk
    • Android NDK at /Users/Lehem/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/Lehem/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Users/Lehem/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone XS Max • 21CA7CEA-6A75-4218-AB96-373135FF339A • ios • iOS 12.1 (simulator)
```

**Comment by zoechi** [comment] 2018-12-30 16:35
I think you need to pass a `TextEditingController` that you keep outside of `build()` so that it isn't recreated every time `build()` is run.

**Comment by zsirfs** [comment] 2019-01-02 12:36
The changed `build()`.
```dart
body: Container(
                            child: ReorderableListView(
                              children: <Widget>[
                                Row(
                                  key: ValueKey('key'),
                                  children: <Widget>[
                                    Expanded(
                                      child: TextField(
                                        controller: _controller,
                                        decoration: InputDecoration(hintText: 'type in'),
                                      ),
                                    )
                                  ],
                                )
                              ],
                              onReorder: (int oldIndex, int newIndex) {},
                            ),
                          ),

```
initState()
```dart
  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: 'sss');
  }
```


The suggestion is invliad

**Comment by zsirfs** [comment] 2019-01-02 12:38
The complete example file:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TapClass(),
    ));

class TapClass extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: FlatButton(
        child: Text('click me'),
        onPressed: () {
          Navigator.of(context)
              .push(MaterialPageRoute(builder: (context) => MyHomePage()));
        },
      ),
    ));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
TextEditingController _controller;
  initState() {
    super.initState()
   _controller = TextEditingController(text: 'sss');
  }
  @override 
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('title here'),
        ),
        body: ReorderableListView(
          children: <Widget>[
            Row(
              key: ValueKey('key'),
              children: <Widget>[
                Expanded(
                  child: TextField(
                    controller: _controller,
                    decoration: InputDecoration(hintText: 'type in'),
                  ),
                )
              ],
            )
          ],
          onReorder: (int oldIndex, int newIndex) {},
        ));
  }
}

**Comment by zoechi** [comment] 2019-01-02 18:53
I can't reproduce on Android. Focusing and writing in the text field works just fine.
I can't currently build for iOS.

**Comment by goderbauer** [comment] 2019-01-04 22:52
This does indeed reproduce on iOS.

**Comment by zsirfs** [comment] 2019-01-08 01:18
In the ios and you can reproduce. @zoechi

**Comment by leonr2080** [comment] 2019-04-09 06:11
I can reproduce on Android with flutter 1.2.1 using zsirfs complete example file.
to reproduce: tap on text field
result: keyboard opens and immediately closes

**Comment by lohanidamodar** [comment] 2019-07-18 05:13
Still having problem with flutter 1.7.8. Has anybody got the solution yet?

**Comment by deepss1** [comment] 2019-08-28 14:36
Do we have any update on this issue ? I am still facing this issue with latest build in master channel.

And the TextField cannot be focused in Dismissible widget as well.

Can anyone give any solution or workaround ?

**Comment by iontaroberto** [comment] 2019-12-09 10:08
Workaround : it works by changing the setting "android:windowSoftInputMode" on android manifest with the values "adjustUnspecified" or "adjustPan", but this is only a workaround.

**Comment by TahaTesser** [comment] 2020-05-05 15:55
Hi @LehemYang 
Not able reproduce on latest `dev` channel 

![Simulator Screen Shot - iPhone 11 - 2020-05-05 at 21 24 53](https://user-images.githubusercontent.com/48603081/81087088-e909af80-8f16-11ea-9860-4ceb9629151a.png)

Are you using still experience this issue?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-05-27 08:30
Can't reproduce with iOS as well. Closing as fixed.
If you disagree, please write in the comments and I will reopen it

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (6 available)
    • Redmi Note 7              • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.5
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server                • web-server                               • web-javascript • Flutter Tools
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by LehemYang** [comment] 2020-05-27 15:54
Sorry for the late reply, it works very well, thank you for your efforts. 🎉

**Closed** 2020-05-27 15:55 UTC
Labels: a: text input, f: material design, framework, platform-ios

**Comment by SupremNandalDev** [comment] 2020-06-22 11:43
Hey there...
I'm still facing this issue on Android even after upgrade..

### Flutter is already up to date on channel dev
Flutter 1.20.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f73f498da1 (4 days ago) • 2020-06-18 08:23:22 -0700
Engine • revision c0d52b98d1
Tools • Dart 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

**### [✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)**

**Comment by VladyslavBondarenko** [comment] 2020-06-22 15:09
@SupremNandalDev 
with `dev 1.20.0-1.0.pre` and code sample from https://github.com/flutter/flutter/issues/25867#issuecomment-450853566 I can't reproduce it on Redmi Note 7 Android 9 (API 28). Consider to file a new issue with filling out template
