### ISSUE TITLE
gen_l10n fail for decimalPattern, percentPattern and scientificPattern

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#74524] opened 2021-01-22 21:46 UTC
Given this `app_en.arb`:

```json
{
    "shopping_lists_item_elements": "{count, plural, =1 {1 element} other {{count} elements}}",
    "@shopping_lists_item_elements": {
        "placeholders": {
            "count": {
                "type": "int",
                "format": "percentPattern"
            }
        }
    }
}
```

And having the `generate: true` in `pubspec.yaml` and the corresponding config in `l10n.yaml` I'm getting these errors:

```
.dart_tool/flutter_gen/gen_l10n/app_localizations_de.dart:15:7: Error: No named parameter with the name 'locale'.
      locale: localeName,
      ^^^^^^
/C:/Users/walbe/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/intl-0.16.1/lib/src/intl/number_format.dart:185:3: Context: Found this candidate, but the arguments don't match.
  NumberFormat.percentPattern([String locale])
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
.dart_tool/flutter_gen/gen_l10n/app_localizations_en.dart:15:7: Error: No named parameter with the name 'locale'.

      locale: localeName,
      ^^^^^^
```

The same error happens for `decimalPattern` and `scientificPattern`.

My guess is that the error persists because those three methods of the `NumberFormat` take `locale` as an optional positional parameter, not named one like the other methods.

```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (6 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Comment by Albert221** [comment] 2021-01-22 21:49
A fix for that would be to not specify a `type` and let the `int` be `toString()`ed, but we sometimes want thousands and decimal separators and this bug keeps us from having it.

```json
{
    "shopping_lists_item_elements": "{count, plural, =1 {1 element} other {{count} elements}}",
    "@shopping_lists_item_elements": {
        "placeholders": {
            "count": {}
        }
    },
}
```

**Comment by pedromassangocode** [comment] 2021-01-25 14:10
I can reproduce the issue on latest stable channel.


<details>
<summary>logs</summary>

```bash
To see a detailed report, use the --untranslated-messages-file 
option in the tool to generate a JSON format file containing 
all messages that need to be translated.
To see a detailed report, use the --untranslated-messages-file 
option in the tool to generate a JSON format file containing 
all messages that need to be translated.
Launching lib/main.dart on sdk gphone x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
To see a detailed report, use the --untranslated-messages-file 
option in the tool to generate a JSON format file containing 
all messages that need to be translated.
.dart_tool/flutter_gen/gen_l10n/app_localizations_en.dart:15:7: Error: No named parameter with the name 'locale'.
      locale: localeName,
      ^^^^^^
../../../Code/flutter_stable/.pub-cache/hosted/pub.dartlang.org/intl-0.16.1/lib/src/intl/number_format.dart:185:3: Context: Found this candidate, but the arguments don't match.
  NumberFormat.percentPattern([String locale])
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
.dart_tool/flutter_gen/gen_l10n/app_localizations_pt.dart:15:7: Error: No named parameter with the name 'locale'.
      locale: localeName,
      ^^^^^^
../../../Code/flutter_stable/.pub-cache/hosted/pub.dartlang.org/intl-0.16.1/lib/src/intl/number_format.dart:185:3: Context: Found this candidate, but the arguments don't match.
  NumberFormat.percentPattern([String locale])
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/pedromassango/Code/flutter_stable/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/pedromassango/Code/flutter_stable/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Comment by HansMuller** [comment] 2021-01-27 20:27
CC @shihaohong

**Comment by drekka** [comment] 2021-01-29 08:00
Have this here. See comments on https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwijjI2H0cDuAhXyQ3wKHXvnBLwQFjABegQIAxAC&url=https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter%2Fissues%2F67217&usg=AOvVaw0tjuy_zxGSljxcAGD0ssF2

**Comment by shihaohong** [comment] 2021-02-01 09:36
Duplicate of https://github.com/flutter/flutter/issues/67217

**Closed by shihaohong** 2021-02-01 09:36 UTC
Labels: a: internationalization, found in release: 1.22, found in release: 1.26, has reproducible steps, severe: crash, tool
