### ISSUE TITLE
Web - VSCode launches on localhost:8080 by default, refused to connect

### ISSUE THREAD

**Issue by awfin** [flutter/flutter#69185] opened 2020-10-28 10:48 UTC
## Steps to Reproduce

1. Install VSCode and Flutter according to https://flutter.dev/docs/get-started/install/macos#web-setup
2. Create a new Flutter app in VSCode
3. Click Run > Run Without Debugging
4. Chrome window opens with localhost:8080, page shows refused to connect error
5. If I launch by terminal, or replace the default "pwa-chrome" config in launch.json by the following
```
        {
            "name": "Flutter for web",
            "type": "dart",
            "request": "launch",
            "program": "lib/main.dart",
            "args": [
              "-d",
              "chrome"
            ]
        }
```
then it launches as desired

It is concerning that the default Flutter app created in VSCode has a configuration that prevents a workable launch, following the official doc instructions. There is also no official documentation (and limited online community) coverage on this issue.

## Logs

```
```

```
```

**Comment by TahaTesser** [comment] 2020-10-28 11:04
Hi @awfin 
Are you able to run from command with `flutter run -d chrome?` 
Can you please provide your `flutter doctor -v`

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Thank you

**Comment by awfin** [comment] 2020-10-28 16:26
@TahaTesser  Thank you, I've moved the ticket to https://github.com/Dart-Code/Dart-Code/issues/2911

**Comment by TahaTesser** [comment] 2020-10-29 07:22
Hi @awfin 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-10-29 07:22 UTC
Labels: in triage
