### ISSUE TITLE
Dedicated thread to handle the animation execution

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#110063] opened 2022-08-23 07:43 UTC
Now, we will use **impeller** to solve some Jank problems caused by the Shader compilation, which will somewhat alleviate the Jank problem of page jumping. But I think this is limited.

Since the computation logic of Animation is currently in the UI thread, imagine a scenario where we jump from page A to page B. Still, page B is very complex, which means that Widget building and Layout will take a long time, and they will block the UI thread, leading to the jank of the transition animation.

If we use a dedicated thread to handle the animation execution like Android `RenderThread`, this may solve the animation stuttering problem

**Comment by linxuebin1990** [comment] 2022-08-23 08:37
**Page A** trans to **Page B**

**Comment by linxuebin1990** [comment] 2022-08-23 09:02
https://user-images.githubusercontent.com/3382181/186117897-e466380a-4e71-443a-9e2b-90dca975c5f6.mov

**Comment by exaby73** [comment] 2022-08-23 09:37
Hello @JsouLiang. Thank you for filing this request. Labelling for further insights from the team.

**Comment by jonahwilliams** [comment] 2022-08-23 22:09
Splitting the UI thread work into multiple theads is infeasible for several reasons. 

By design, a single thread means that newspace allocations don't need any locking, making widget allocation fast compared to a language like Java. Furthermore, all Dart code that has _ever_ been written, was written under the assumption that it can only be interrupted at yield points (`await`). Finally, the widget tree/layout/painting itself all has references to objects that would need to be shared across threads, making that sort of change deeply intrusive.

here are some methods we have addressed page transition speed and some ideas we have for transition animations:

1. Animate a raster/snapshot instead of the widget tree itself. This can be computed on the first animation frame (making any lag imperctible, since the animation has not visually started). Once the page transition completes, we swap back to the regular widget tree.  See: https://github.com/pulls?q=is%3Apr+author%3Ajonahwilliams+archived%3Afalse+is%3Aclosed+zoom

2. (Idea) allow delaying the start of a page transition until the work from 1, or some other layout steps have completed removing the observable stutter from impacting frame time.

I'm sure there are more possible approaches.

**Comment by jonahwilliams** [comment] 2022-08-23 22:12
Of course impeller also potentially unlocks some new optimizations, since toImage/toImageSync must run on the dedicated raster thread today, but would have no such restriction with impeller

**Comment by jonahwilliams** [comment] 2022-08-23 22:22
Somethign else to consider:

Usually when I investigate slow frames like the one you've posted, I've found they are usually doing much more work than necessary - perhaps due to a large list of text that is not implemented using Slivers. And rather than make intrusive changes to the layout system, its much simple to only build what will be onscreen using the primitives we provide.

The cannonical example of this might be replacing a Column in a SingleChildScrollView with a ListView.

**Comment by xanahopper** [comment] 2022-08-30 15:46
Most of these lag page transitions is already using the primitives which Flutter SDK provided such as ListView.

But there is one thing I cannot agree more is that some offcial widgets' performance is terrible, like NestedScrollView. FPS of A scene before use it has at least 55+ becomes less than 50.
So I don't think things will be better if a page we are going to route using some framework widget.

For more, many cases are complicated, we have to improve the transition and animation. Animation's calculation is all running in Dart's main thread and which is not necessary. Meanwhile Android even has animators runs in RenderThread ([ViewPropertyAnimator](https://developer.android.com/reference/android/view/ViewPropertyAnimator))

User interface is a complicated topic, but single thread is definitely not the best way (even not a better way) in modern GUI framework, especially with mobile platforms.

**Comment by xanahopper** [comment] 2022-08-30 15:53
If you tell developers in no matter which way that: Pages in transition should maintain single, I think developers will choose a framework allow they do that, even in a dramatic way.

I think you know some solutions like [Litho](https://fblitho.com/), which measure and layout in a different thread.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/2241197/187483233-e5b1016b-5b75-422e-96c5-9859c69de00f.png">

and Android's [PrecomputedText](https://developer.android.com/reference/android/text/PrecomputedText).

You don't have a request that one line and two lines with different layout and elements?

**Comment by jonahwilliams** [comment] 2022-08-30 16:17
Its very possible to use the widgets provided by the Flutter SDK in such a way that page transitions are laggy. For example, if you nest scroll views and end up shrinkwrapping the child, your scene will contain all of that lists children which requires a tremendous amount of text layout. While we should make those better, and identify scenarios where they perform worse than expected, I don't really see what that has the to do with this bug - which is a request for a feature that is clearly infeasible. 

If you have a reproducible sample application I'd love to take a look at it.

**Comment by zanderso** [comment] 2022-11-10 23:31
@JsouLiang As for tracking this in the issue tracker, it's probably more helpful to start off from the perspective of the problem rather than a potential solution. I'm going to close this, but I'd encourage filing a new issue about the problem that includes the code for a repro case that we all can study. Thanks!

**Closed by zanderso** 2022-11-10 23:31 UTC
Labels: new feature, engine, a: animation, proposal, perf: speed, P5
