### ISSUE TITLE
firebase_auth Android crash when using the Twitter AuthProvider

### ISSUE THREAD

**Issue by ajaynonstopio** [flutter/flutter#37954] opened 2019-08-09 19:48 UTC
When signing in with TwitterAuthProvider credentials with Firebase Auth, the app crashes on Android (stack trace below)

```
D/AndroidRuntime(17848): Shutting down VM
E/AndroidRuntime(17848): FATAL EXCEPTION: main
E/AndroidRuntime(17848): Process: **PackageName**, PID: 17848
E/AndroidRuntime(17848): java.lang.IllegalArgumentException: Unsupported value: null
E/AndroidRuntime(17848): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/AndroidRuntime(17848): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(17848): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(17848): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(17848): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(17848): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
E/AndroidRuntime(17848): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(17848): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:691)
E/AndroidRuntime(17848): 	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
E/AndroidRuntime(17848): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(17848): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(17848): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(17848): 	at android.app.ActivityThread.main(ActivityThread.java:6898)
E/AndroidRuntime(17848): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17848): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(17848): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/CrashlyticsCore(17848): Cannot send reports. Settings are unavailable.
D/OSTracker(17848): OS Event: crash
I/Process (17848): Sending signal. PID: 17848 SIG: 9
```

**Implementation**

```
    var twitterLogin = new TwitterLogin(
      consumerKey: TwitterSettings.consumerKey,
      consumerSecret: TwitterSettings.consumerSecret,
    );

    final TwitterLoginResult result = await twitterLogin.authorize();

    final AuthCredential credential =
        TwitterAuthProvider.getCredential(authToken: result.session.token, authTokenSecret: result.session.secret);

    final FirebaseUser firebaseUser = (await _auth.signInWithCredential(credential))?.user;
```

**pubspec.yaml > dependencies**

```
  firebase_analytics: ^4.0.2
  firestore_ui: ^1.6.0
  firebase_storage: ^3.0.5
  firebase_auth: ^0.14.0+1
  firebase_database: ^3.0.5
  google_sign_in: ^4.0.6
  flutter_twitter: ^1.1.3
```

Similar issue[ #37681](https://github.com/flutter/flutter/issues/37681)

**Comment by jmagman** [comment] 2019-08-09 22:39
Duplicate of https://github.com/flutter/flutter/issues/37681 (as you pointed out).

**Closed by jmagman** 2019-08-09 22:39 UTC
Labels: severe: performance
