### ISSUE TITLE
Text widget maxLines attribute in flutter web causes horizontal scrollbar to appear 

### ISSUE THREAD

**Issue by morhaviv** [flutter/flutter#91103] opened 2021-10-01 17:37 UTC
Hi,

I'm having a weird bug with the Text widget in flutter, which causes a horizontal scrollbar appear for no reason when adding the maxLines attribute to a text widget, on specific screen resolutions. The bug occurres only on Flutter Web, and I encountered it on multiple mobile devices and chrome for desktop.

** Example of the issue: **
Demo version:
https://user-images.githubusercontent.com/61060270/135662197-94de117c-af9d-465e-8497-17c647f882b5.mp4
My app version:
![image](https://user-images.githubusercontent.com/61060270/135663092-ebf72b22-5e24-4a20-acc7-7446f0daf813.png)

** Few things I noticed: **
- The issue depends on a combination of screen resolution & text length. If you edit the text, you'll need to play with the screen resolution a little bit and then it will occur again.
- If you remove the maxLines attribute, the issue dissapears.
- The issue occurres even if your text doesn't exceed the maxLines amount
- Sometimes the issue happens even without the InkWell animation and just as soon as you go to the page you see the scrollbar appearing. (You can see an example for such case on the "My app version" screenshot above)
- Sometimes the scrollbar disappears within a few seconds without touching anything, sometimes it just stays

** Things I tried: **
- I tried to add a scrollconfiguration and disable the scrollbars but it didn't work
- I tried to change the physics of the ListView to NeverScrollable, but also the scrollbar appeared

** System info: **
Windows 10
Chrome  94.0.4606.61
Flutter 2.5.2

## Steps to Reproduce
My project is really complicated, so I created a sample project and I was able to reproduce the issue.
1. Create an example flutter project
2. Edit the main.dart file to this:
```

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primaryColor: Colors.red,
        primarySwatch: Colors.red,
        appBarTheme: const AppBarTheme(
          color: Colors.red,
        ),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<AnimatedListState> listKey = GlobalKey<AnimatedListState>();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        padding: EdgeInsets.all(15.0),
        child: AnimatedList(
          key: listKey,
          initialItemCount: 115,
          itemBuilder: (context, index, animation) {
            return Material(
              color: Colors.white,
              child: InkWell(
                onTap: () {
                  print("Tapped");
                },
                child: Container(
                  child: Row(
                    children: [
                      Container(
                        width: 70,
                      ),
                      Flexible(
                          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: <Widget>[
                        Container(
                          //width: 260,
                          child: const Text(
                            "Gavim, Sapie College, Sderot, Mefalsim, Nir Am Shooting Range",
                            maxLines: 3,
                            style: TextStyle(overflow: TextOverflow.fade, fontSize: 15, color: Color.fromARGB(255, 48, 48, 54)),
                          ),
                        ),
                        const Text(
                          "Test",
                          maxLines: 3,
                          style: TextStyle(fontSize: 15, color: Colors.black),
                        ),
                      ])),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

```
3. Run with Chrome, and open devtools
4. Click on "Toggle device toolbar"
5. Set the device's resolution to 362x650 (The height doesn't really matter, only the width)

**Expected results:** 
There shouldn't have been a scrollbar

**Actual results:** 
A horizontal scrollbar appeared below the text.

**Comment by TahaTesser** [comment] 2021-10-04 08:16
Hi @morhaviv 
I just tried the latest Flutter`stable` channel, only the vertical expected scrollbar is visible changing the width, I couldn't find any horizontal scrollbar even after tapping the items

### command

`flutter run -d chrome`

### Preview


https://user-images.githubusercontent.com/48603081/135816649-b9bfe40d-748b-49ca-808d-c1c35da4bd6f.mov




<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.0 21A5534d darwin-x64, locale en-GB)
    • Flutter version 2.5.2 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.0 21A5534d darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
	 
</details>

Can you please provide your `flutter doctor -v`?
Thank you

**Comment by morhaviv** [comment] 2021-10-04 09:13
> Hi @morhaviv I just tried the latest Flutter`stable` channel, only the vertical expected scrollbar is visible changing the width, I couldn't find any horizontal scrollbar even after tapping the items
> 
> ### command
> `flutter run -d chrome`
> 
> ### Preview
>  Screen.Recording.2021-10-04.at.11.12.17.mov 
> flutter doctor -v
> Can you please provide your `flutter doctor -v`? Thank you


Hi, here is my doctor result:

```
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1237], locale en-IL)
    • Flutter version 2.5.2 at D:\Softwares\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Softwares\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\Softwares\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at D:\Softwares\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Softwares\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1237]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 94.0.4606.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!
```

Thank you!

**Comment by morhaviv** [comment] 2021-10-04 21:12
> Hi @morhaviv I just tried the latest Flutter`stable` channel, only the vertical expected scrollbar is visible changing the width, I couldn't find any horizontal scrollbar even after tapping the items
> 
> ### command
> `flutter run -d chrome`
> 
> ### Preview
>  Screen.Recording.2021-10-04.at.11.12.17.mov 
> flutter doctor -v
> Can you please provide your `flutter doctor -v`? Thank you

Ok so after further investigation, my original app has an image in the container next to the text. In the sample I removed the image because I thought it wasn't necessary, but after playing with the code a little bit I found out that it makes the problem significantly worse, as you can see in the attached video. Also I've added some more random text.

This time the scrollbar appears even without clicking the items, and it happens to many of the items. Sometimes the scrollbar appears within a few seconds, then returns when I scroll back again. sometimes it just stays.

Example video (At the beggining of the video I refresh the page, then just scroll): 

https://user-images.githubusercontent.com/61060270/135925062-f7a4caba-e239-409a-990d-86dcd27bc18a.mp4


Here is the new code (With the image next to the text):
```

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primaryColor: Colors.red,
        primarySwatch: Colors.red,
        appBarTheme: const AppBarTheme(
          color: Colors.red,
        ),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<AnimatedListState> listKey = GlobalKey<AnimatedListState>();

  List<String> list = ["Ashkelon Northern Industrial Zone, Ashkelon, Ashkelon Southern Industrial Zone, Beit Shikma, Bat Hadar, Ge'a, Mavki'im, Nitzan","Ashkelon Southern Industrial Zone, Zikim, Karmia, Netiv HaAssara","Ashkelon, Ashkelon Southern Industrial Zone, Mavki'im, Ashkelon Northern Industrial Zone","Avshalom, Yevul, Shlomit","Be'eri, Nachal Oz, Alumim, Zimrat, Shuva, Kfar Azza, Sa'ad, Shokeda","Be'eri, Zimrat, Shuva, Nachal Oz, Sa'ad, Alumim, Shokeda, Netivot, Kfar Maimon and Tushia, Yoshivia, Tkuma, Ad Halom Industrial Zone, Ashdod, Nitzan, Beit Ezra, Be'er Ganim, Nitzanim, Ashkelon Southern Industrial Zone","Dekel, Yated, Sdeh Avraham, Avshalom, Ashdod, Nitzan, Bnei Darom, Gan HaDarom, Kfar Aviv, Kerem BeYavne, Bnei Darom Compound, Kvutzat Yavne, Nir Galim, Ad Halom Industrial Zone, Beit Ezra, Gan Yavne, Sdeh Uziahu, Shtulim, Mishmar HaNegev, Rahat, Tirabin, Gavim, Sapir College, Yakhini, Mefalsim","Ein HaShlosha, Kissufim, Nirim","Ein Quiniyye, Neveh Ativ, Snir","Erez, Yad Mordechai, Netiv HaAssara","Gavim, Sapir College, Sderot, Mefalsim, Nir Am Shooting Range","Gavim, Sapir College, ניר עם, Sderot, Erez, Nir Am Shooting Range","Holit, Kerem Shalom, Sufa, Avshalom, Yevul, Yated, Sdeh Avraham, Dekel","Karmia, Ashkelon Southern Industrial Zone, Zikim, Beit Ezra, Ashkelon, Be'er Ganim, Nitzan, Nitzanim, Nir Israel, Ashdod","Kerem Shalom","Kerem Shalom, Avshalom, Yevul, Yated, Naveh","Kerem Shalom, Zikim, Netiv HaAssara","Kfar Azza","Kfar Azza, Nachal Oz, Sa'ad, Ashkelon Southern Industrial Zone, Zikim, Karmia, Netiv HaAssara, Gavim, Sapir College, ניר עם, Sderot, Erez, Nir Am Shooting Range","Kfar Giladi, Kiryat Shmona, Tel Hai","Kissufim, Ein HaShlosha","Kissufim, Mivtahim, Ami'oz, Yesha, Zohar, Ohad","Kissufim, Nirim, Ein HaShlosha","Magen, Nir Oz, Nirim, Holit, Kerem Shalom, Yated, Sufa, Sdeh Avraham, Yevul, Talmei Yossef, Gvulot, Talmei Eliyahu, Zohar, Ohad","Mavki'im, Erez, Yad Mordechai, Karmia, Netiv HaAssara, Beit Shikma, Ge'a, Mishan, Gvaram, Ashkelon Southern Industrial Zone, Talmei Yaffe","Mefalsim, Nir Am Shooting Range","Mivtahim, Ami'oz, Yesha, Zohar, Ohad, Shlomit","Nachal Oz","Nachal Oz, Kfar Azza","Netiv HaAssara","Netiv HaAssara, Erez, Yad Mordechai","Netivot, Zimrat, Shuva, Kfar Maimon and Tushia, Tkuma and Havat Izra'am, Sa'ad, Shokeda, Yoshivia, Tkuma, Alumim","Nir Am Shooting Range, Mefalsim","Nir Itzhak, Mivtahim, Ami'oz, Yesha, Zohar, Ohad, Sdeh Nitzan, Nachal Oz, Talmei Eliyahu","Nir Oz","Nir Oz, Nirim","Nirim, Ein HaShlosha","Rosh HaNikra, Netiv HaShayara, Sheikh Danun, Hanita, Ya'ara, Cabri, Metzuba, Avdon, Idmit, Shlomi","Sderot, Erez, Nir Am Shooting Range","Sderot, Gavim, Sapir College, Nir Am Shooting Range","Sufa, Pri Gan","Yad Mordechai, Netiv HaAssara","ניר עם, Kfar Azza, Mefalsim, Nir Am Shooting Range","ניר עם, Mefalsim, Nir Am Shooting Range, Sderot","ניר עם, Sderot, Mefalsim, Nir Am Shooting Range, Zru'a, Yakhini, Kfar Azza, Sa'ad, Tkuma, Gavim, Sapir College, Erez, Netivot, Be'eri, Zimrat, Shuva, Kfar Maimon and Tushia, Alumim, Shokeda, Havat Shikmim, Ashkelon Southern Industrial Zone, Zikim, Nitzan, Nitzanim, Ashkelon Northern Industrial Zone, Ashkelon, Be'er Ganim, Ashdod","ניר עם, Sderot, Nir Am Shooting Range, Gavim, Sapir College"];

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        padding: EdgeInsets.all(15.0),
        child: AnimatedList(
          key: listKey,
          initialItemCount: list.length,
          itemBuilder: (context, index, animation) {
            return Material(
              color: Colors.white,
              child: InkWell(
                onTap: () {
                  print("Tapped");
                },
                child: Container(
                  child: Row(
                    children: [
                      Container(
                        width: 70,
                        child: Image.asset("assets/ic_launcher_round.png"),
                      ),
                      Flexible(
                          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: <Widget>[
                        Container(
                          //width: 260,
                          child: Text(
                            list[index],
                            maxLines: 3,
                            style: TextStyle(overflow: TextOverflow.fade, fontSize: 15, color: Color.fromARGB(255, 48, 48, 54)),
                          ),
                        ),
                        const Text(
                          "Test",
                          maxLines: 3,
                          style: TextStyle(fontSize: 15, color: Colors.black),
                        ),
                      ])),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

```

And also attached the icon file:
![ic_launcher_round](https://user-images.githubusercontent.com/61060270/135925475-55f70b4a-7bcd-427c-8b19-c46f42073770.png)

Thank you!

**Comment by TahaTesser** [comment] 2021-10-05 08:10
Hi @morhaviv 
I can reproduce the issue, it is only reproducible in HTML render and a duplicate of https://github.com/flutter/flutter/issues/82176

**Closed by TahaTesser** 2021-10-05 08:10 UTC
Labels: in triage
