### ISSUE TITLE
Attempt to execute code removed by Dart AOT compiler (TFA)

### ISSUE THREAD

**Issue by rsetkus** [flutter/flutter#137297] opened 2023-10-25 22:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Android logcat output when launching release application.

### Stacktrace
```
I  Attempt to execute code removed by Dart AOT compiler (TFA)
I  #0      AddonsObjectBoxStorageProvider.create (package:addons_benefits/core/data/object_box/addons_object_box_storage_provider.dart)
I  <asynchronous suspension>
I  #1      AddonsBenefitsInjectionModule._registerProviders (package:addons_benefits/core/addons_benefits_injection_module.dart:144)
I  <asynchronous suspension>
I  #2      AddonsBenefitsInjectionModule.registerDependencies (package:addons_benefits/core/addons_benefits_injection_module.dart:88)
I  <asynchronous suspension>
I  #3      _initFeatures (package:my_app/src/application/di/injection_container.dart:193)
I  <asynchronous suspension>
I  #4      init (package:my_app/src/application/di/injection_container.dart:180)
I  <asynchronous suspension>
I  #5      _registerDependencies (package:my_app/main.dart:257)
I  <asynchronous suspension>
I  #6      main.<anonymous closure> (package:my_app/main.dart:36)
I  <asynchronous suspension>
I  #7      main (package:my_app/main.dart:32)
I  <asynchronous suspension>
```

### Expected results

Android release application interacts with a user.

### Actual results

Android release build gets stuck when launching an application. It doesn't crash but just freezes and stops performing. The debug build works as expected. iOS release and debug builds are working fine.

### Code sample

<details><summary>Code sample</summary>

The first instance of code where it possibly fails
```dart
static Future<AddonsObjectBoxStorageProvider> create({
    required AddonReminderDomainModelMapper mapper,
  }) async {
    Directory directory = await getApplicationDocumentsDirectory();
    String appPath = directory.path;
    String directoryPath = '$appPath/addons';
    Store store;
    if (Store.isOpen(directoryPath)) {
      store = Store.attach(getObjectBoxModel(), directoryPath);
    } else {
      store = await openStore(directory: directoryPath);
    }
    return AddonsObjectBoxStorageProvider._create(store, mapper);
  }
```

</details>

### Logs

<details><summary>Logs</summary>

```console
I  Attempt to execute code removed by Dart AOT compiler (TFA)
I  #0      AddonsObjectBoxStorageProvider.create (package:addons_benefits/core/data/object_box/addons_object_box_storage_provider.dart)
I  <asynchronous suspension>
I  #1      AddonsBenefitsInjectionModule._registerProviders (package:addons_benefits/core/addons_benefits_injection_module.dart:144)
I  <asynchronous suspension>
I  #2      AddonsBenefitsInjectionModule.registerDependencies (package:addons_benefits/core/addons_benefits_injection_module.dart:88)
I  <asynchronous suspension>
I  #3      _initFeatures (package:my_app/src/application/di/injection_container.dart:193)
I  <asynchronous suspension>
I  #4      init (package:my_app/src/application/di/injection_container.dart:180)
I  <asynchronous suspension>
I  #5      _registerDependencies (package:my_app/main.dart:257)
I  <asynchronous suspension>
I  #6      main.<anonymous closure> (package:my_app/main.dart:36)
I  <asynchronous suspension>
I  #7      main (package:my_app/main.dart:32)
I  <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.6, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    ! Flutter version 3.10.6 on channel unknown at /Users/rsetkus/opt/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision f468f3366c (4 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rsetkus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment] 2023-10-26 07:54
Thanks for the report @rsetkus 
Can you provide us complete runnable reproducible code sample that throws the error ?


> ```
> AddonsObjectBoxStorageProvider.create (package:addons_benefits/core/data/object_box/addons_object_box_storage_provider.dart)
> I  <asynchronous suspension>
> I  #1      AddonsBenefitsInjectionModule._registerProviders (package:addons_benefits/core/addons_benefits_injection_module.dart:144)
> I  <asynchronous suspension>
> I  #2      AddonsBenefitsInjectionModule.registerDependencies (package:addons_benefits/core/addons_benefits_injection_module.dart:88)
> I  <asynchronous suspension>
> ```

These seems to be coming from third party implementation.

**Comment by mraleph** [comment] 2023-10-26 08:34
cc @alexmarkov

**Comment by rsetkus** [comment] 2023-10-26 09:17
> Thanks for the report @rsetkus Can you provide us complete runnable reproducible code sample that throws the error ?
> 
> > ```
> > AddonsObjectBoxStorageProvider.create (package:addons_benefits/core/data/object_box/addons_object_box_storage_provider.dart)
> > I  <asynchronous suspension>
> > I  #1      AddonsBenefitsInjectionModule._registerProviders (package:addons_benefits/core/addons_benefits_injection_module.dart:144)
> > I  <asynchronous suspension>
> > I  #2      AddonsBenefitsInjectionModule.registerDependencies (package:addons_benefits/core/addons_benefits_injection_module.dart:88)
> > I  <asynchronous suspension>
> > ```
> 
> These seems to be coming from third party implementation.

I can try a minimal reproducible application. Is there anything else that would be helpful for you to detect the area of problem?

**Comment by mraleph** [comment] 2023-10-26 09:30
Repro would be the best. It might be duplicate of https://github.com/dart-lang/sdk/issues/52874

Try checking if making `store` variable nullable fixes it.

**Comment by rsetkus** [comment] 2023-10-30 16:47
> Repro would be the best. It might be duplicate of [dart-lang/sdk#52874](https://github.com/dart-lang/sdk/issues/52874)
> 
> Try checking if making `store` variable nullable fixes it.

Trying to apply the changes @mraleph suggested but after the change, it takes hours to make a build (roughly 5 hours). Build gets stuck at step

```plain
[+919448 ms] [+919301 ms] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/rsetkus/projects/my-app/features/addons_benefits/lib/core/data/object_box/addons_object_box_storage_provider.dart}
[  +57 ms] [ +246 ms] /Users/rsetkus/opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/rsetkus/opt/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/Users/rsetkus/opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -DBUILD_TYPE=enterprise
-DSHA1_CERTIFICATE=... -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages
/Users/rsetkus/projects/my-app/.dart_tool/package_config.json --output-dill
/Users/rsetkus/projects/my-app/.dart_tool/flutter_build/d66a517e4f75945a72904f6846bea346/app.dill --depfile
/Users/rsetkus/projects/my-app/.dart_tool/flutter_build/d66a517e4f75945a72904f6846bea346/kernel_snapshot.d --source
file:///Users/rsetkus/projects/my-app/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///Users/rsetkus/projects/my-app/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error package:my_app/main.dart
```
Not sure if that is related Dart AOT. Any ideas about what might it cause?

**Comment by alexmarkov** [comment] 2023-10-30 18:22
@rsetkus Could you create a minimal reproduction? Also, could you try building your app with the latest Flutter version on the `main` channel? The `main` channel can be selected using `flutter channel main` and then `flutter upgrade`.

**Comment by rsetkus** [comment] 2023-11-08 09:25
Hi. Just heads up, I am working on creating a minimal reproduction. The error appears on a large scale project, so it might take some time to create it.

**Comment by rsetkus** [comment] 2023-11-14 22:40
Hi. Here is the minimal reproducible project https://github.com/rsetkus/flutter-mre. I have managed to recreate the same error as we get on actual project.

**Comment by mraleph** [comment] 2023-11-15 11:45
@rsetkus thank you! could you please license the code in the repo under some open source license (e.g. MIT, Apache, BSD, GPL - all work, not AGPL preferrably). We can't look at the code which does not have a clear license.

**Comment by rsetkus** [comment] 2023-11-15 11:56
> @rsetkus thank you! could you please license the code in the repo under some open source license (e.g. MIT, Apache, BSD, GPL - all work, not AGPL preferrably). We can't look at the code which does not have a clear license.

Done

**Comment by rsetkus** [comment] 2023-11-15 17:45
> I can reproduce the problem on Flutter 3.10.6, but not on the current tip of the tree. As far as I can see, this is indeed a duplicate of [dart-lang/sdk#52596](https://github.com/dart-lang/sdk/issues/52596).
> 
> After changing code in AddonsObjectBoxStorageProvider.create() to `Store? store;` the problem disappears. Also, it builds rather quickly: frontend_server step took ~20s on my machine.
> 
> @rsetkus Could you post the full build log (with `-v) of the slow build, so we would see all timings? Can you reproduce the slow build on your minimal repro project?
> 
> Consider upgrading to the latest `beta` or wait for the next stable release which should happen soon.

You are right. Indeed, changing `Store? store;` does the trick. I got confused myself and changed class scope `Store` variable instead of the function scope.

Would you consider it as Flutter bug? If so, do you need any log reports? Happy to provide if you need.

**Comment by alexmarkov** [comment] 2023-11-15 21:17
It's worth investigating sudden increase in compilation time if it can be reproduced on the latest version. If that's the case, could you provide a minimal repro and logs?

**Closed** 2023-12-07 08:09 UTC
Labels: waiting for customer response, in triage
