### ISSUE TITLE
Xcode 11.3.1 No such module 'Firebase'

### ISSUE THREAD

**Issue by Daibaku9999** [flutter/flutter#51101] opened 2020-02-20 06:06 UTC
After `Xcode` updated, app can't be run both iOS simulator and real device with the message `No such module 'Firebase'`
I tried pod reinstall and pod update, but no luck.
How can I fix this?

**Comment by iapicca** [comment] 2020-02-20 08:23
Hi @Daibaku9999 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-02-20 08:23 UTC
