### ISSUE TITLE
FR: Column & Row widget: add `spacing` (similar to Wrap one)

### ISSUE THREAD

**Issue by henry2man** [flutter/flutter#101107] opened 2022-03-31 10:37 UTC
## Use case

I would like the `Column` and `Row` widgets to have a `spacing` parameter that would work exactly the same as in `Wrap`, so that information could be easily displayed by adding a certain space between each child node of the widget.

## Proposal

Simply add a new attribute `spacing` to `Column` and `Row` that defaults to `0` to preserve current default behaviour.

**Comment by danagbemava-nc** [comment] 2022-03-31 10:45
Duplicate of #55378

**Closed by danagbemava-nc** 2022-03-31 10:45 UTC
Labels: in triage

**Comment by henry2man** [comment] 2022-03-31 10:50
@danagbemava-nc Thanks, I didn't found #55378. 
For anyone interested, here it is a nice workaround https://github.com/flutter/flutter/issues/16957#issuecomment-558878770
