### ISSUE TITLE
How to change TargetPlatform.ios?

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#13829] opened 2018-01-02 08:14 UTC
My iOS project is named `Uber.xcodeproj` and `Uber.xcworkspace`, I placed my files into the ios folder, but it seems Flutter project can not find the iOS project .

**Comment by realcarlos** [comment] 2018-01-02 08:36
Running "flutter packages get" in platform_view...
Launching lib/main.dart on iPhone 8 in debug mode...
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.

**Comment by mit-mit** [comment] 2018-01-02 13:37
Sorry to hear. Did you create your project with `flutter create`, of by cloning an existing project?

**Comment by Hixie** [comment] 2018-05-23 16:33
@realcarlos any luck? Did running `flutter create .` help?

**Comment by Jasonthefirst** [comment] 2018-06-27 14:24
I have the same problem. A flutter create . says it added two files but trying to run the program I get the same error.

**Comment by ThinkDigitalRepair** [comment] 2018-07-01 23:36
I'm having that issue after editing the info.plist manually. Even after running `flutter create .`, it gave the same error. I was able to resolve it by deleting the Info.plist and running `flutter create .` again, but now I don't have my edits...

**Comment by xiahawaii** [comment] 2018-07-10 09:58
may be you can run "flutter doctor" in Terminal
make sure "iOS toolchain" is OK

**Comment by lichentao** [comment] 2018-07-15 03:10
otao-macbookpro:dmcompileflutter botao$ flutter run
Launching lib/main.dart on iPhone X in debug mode...
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.

**Comment by mofuntech** [comment] 2018-08-23 01:07
I presented a similar problem and the way to solve it was eliminated all the key (for example: <key> UIRequiredDeviceCapabilities </ key>) manually added in "Info.plist" from the IDE (IntelliJ IDEA) and proceeded to enter these " key "directly from Xcode in Info.plist.

Then I proceeded to install the following libraries that I still lacked:

brew install --HEAD libimobiledevice
brew install ideviceinstaller
brew install ios-deploy
brew install cocoapods
pod setup
sudo easy_install six

Additional also install: Flutter plugin in my IDE.

then install everything always from the directory that contains the project in which all the previous installations "flutter run" were made.

This was the procedure that worked for me.

**Comment by jmagman** [comment] 2020-01-23 01:26
I think this is a duplicate of https://github.com/flutter/flutter/issues/9767.

**Closed by jmagman** 2020-01-23 01:26 UTC
Labels: tool, ⌺‬ platform-ios

**Comment by Ahmedxjs2** [comment] 2020-09-28 11:49
The easy way: create a dummy project and run it and make sure it run perfectly. Copy all files from the old project(the one can't be run) and paste them in the dummy project.

Open the dummy project again and now it's your old project and will run.
