### ISSUE TITLE
[BUG] DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true

### ISSUE THREAD

**Issue by franferri** [flutter/flutter#60486] opened 2020-06-29 00:12 UTC
I have installed today in Android Studio the plugins Flutter and Dart. Last versions.

I was working for hours doing tests in my project and after the update suddenly I can't run the Flutter tests anymore, it keeps saying:

```
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.
```

I'm using macOS last version with Flutter stable channel:

```
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (11 days ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
I have tried to add the DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true to the environment, export in a console and then start Android Studio with open -a... nothing works.
```

Either Flutter is rewriting the var or the build-in dart-sdk not picking it.

Since setting the variable as global don't work, nor in the terminal session before running Android Studio, nor Android Studio let you change anything in the dart plugin panel... I'm out of options

if anybody knows how to fix this please help.

Posted in stackoverflow too in a desperate attempt to get help: https://stackoverflow.com/questions/62629506/dart-vm-options-dsilent-observatory-true

**Comment by rackberg** [comment] 2020-06-29 05:14
I've updated the Flutter and Dart plugins of my Android Studio to the last available versions:
Flutter Plugin (47.0.2)
Dart Plugin (193.7361)

I can confirm that now I am unable to run any tests and it shows the same annoying warning message.

Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5

Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (4 weeks ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

Please help!

**Comment by rackberg** [comment] 2020-06-29 05:44
I think I have found a "workaround" solution for the moment.

I've completely removed the plugins dart and flutter from Android Studio and replaced them with older versions (found at https://plugins.jetbrains.com/plugin/9212-flutter/versions and https://plugins.jetbrains.com/plugin/6351-dart/versions)

The following plugin combination works for me when running flutter test in Android Studio (without warnning message) like a charm:
Dart Plugin (193.6911.31)
Flutter Plugin (46.0.2)

To manually install a plugin from disk go to "Preferences" -> "Plugins" -> Click the little cog icon near the "Installed" tab -> Choose "Install Plugin from Disk..."

@franferri Did this helped you?

Best,

Rackberg

**Comment by harishreddy-m** [comment] 2020-06-29 07:31
> I think I have found a "workaround" solution for the moment.
> 
> I've completely removed the plugins dart and flutter from Android Studio and replaced them with older versions (found at https://plugins.jetbrains.com/plugin/9212-flutter/versions and https://plugins.jetbrains.com/plugin/6351-dart/versions)
> 
> The following plugin combination works for me when running flutter test in Android Studio (without warnning message) like a charm:
> Dart Plugin (193.6911.31)
> Flutter Plugin (46.0.2)
> 
> To manually install a plugin from disk go to "Preferences" -> "Plugins" -> Click the little cog icon near the "Installed" tab -> Choose "Install Plugin from Disk..."
> 
> @franferri Did this helped you?
> 
> Best,
> 
> Rackberg

Android Studio did not even start. 
Displayed some Java Cast Exception.

**Comment by franferri** [comment] 2020-06-29 08:35
> I think I have found a "workaround" solution for the moment.
> 
> I've completely removed the plugins dart and flutter from Android Studio and replaced them with older versions (found at https://plugins.jetbrains.com/plugin/9212-flutter/versions and https://plugins.jetbrains.com/plugin/6351-dart/versions)
> 
> The following plugin combination works for me when running flutter test in Android Studio (without warnning message) like a charm:
> Dart Plugin (193.6911.31)
> Flutter Plugin (46.0.2)
> 
> To manually install a plugin from disk go to "Preferences" -> "Plugins" -> Click the little cog icon near the "Installed" tab -> Choose "Install Plugin from Disk..."
> 
> @franferri Did this helped you?
> 
> Best,
> 
> Rackberg

Thanks for the workaround, so far I tried all I knew and I was stuck in the dust, I will try it in a few hours, after work, and report back, installing previous versions will do the trick for sure. I didn't found the option myself the first time I have looked, nor the sources.

**Comment by rackberg** [comment] 2020-06-29 11:23
> Android Studio did not even start.
> Displayed some Java Cast Exception.

After I've removed the plugins I restarted Android Studio. Then I installed the dart plugin first, restarted Android Studio and then installed the flutter plugin and restarted Android Studio again.

No ClassCastException occurred during this process.

Which version of Android Studio are you using?
Maybe you have plugins installed that depend on the dart or flutter plugins?

Did you managed in the meantime to let your Android Studio start again?

**Comment by iapicca** [comment] 2020-06-29 11:58
Hi @franferri 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by franferri** [comment] 2020-06-29 12:56
iapicca please dont close the issue before you read it and understand it, **Flutter is broken to run the test in Android Studio**.

**No one is commenting anything about VS**, this is about Android Studio with Flutter not being able to run the tests.

Android Studio Flutter and Dart plugins were the cause.

**Comment by franferri** [comment] 2020-06-29 13:02
Reposted, @iapicca please don't close tickets without reading them and understanding them: https://github.com/flutter/flutter/issues/60517

**Comment by iapicca** [comment] 2020-06-29 13:09
Hi @franferri 
Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code and from terminal as well?
Thank you

**Comment by franferri** [comment] 2020-06-29 13:19
> Hi @franferri
> Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code and from terminal as well?
> Thank you

First sentence ever written here: "I have installed today in Android Studio the plugins Flutter and Dart. Last versions."
I have no tested or ever used VS Code, and I'm not using flutter in the terminal beyond "flutter doctor".

Is a bug in the last version of Flutter/Dart plugins for AndroidStudio introduced in the last update.

Steps to reproduce:

macos, download android studio, install flutter plugin, new flutter project, run the test with right click, run test (you may have edit the runtest configuration to mark it as flutter test instead of dart test).

I hope with this details, we can add whatever missing parameter is for the Flutter plugin (owned by flutter.dev not Jetbrains) when calling dart to run the tests.

**Comment by franferri** [comment] 2020-06-29 13:24
@iapicca thanks for looking into it.

**Comment by franferri** [comment] 2020-06-29 17:15
> I think I have found a "workaround" solution for the moment.
> 
> I've completely removed the plugins dart and flutter from Android Studio and replaced them with older versions (found at https://plugins.jetbrains.com/plugin/9212-flutter/versions and https://plugins.jetbrains.com/plugin/6351-dart/versions)
> 
> The following plugin combination works for me when running flutter test in Android Studio (without warnning message) like a charm:
> Dart Plugin (193.6911.31)
> Flutter Plugin (46.0.2)
> 
> To manually install a plugin from disk go to "Preferences" -> "Plugins" -> Click the little cog icon near the "Installed" tab -> Choose "Install Plugin from Disk..."
> 
> @franferri Did this helped you?
> 
> Best,
> 
> Rackberg

Worked, and I owe you a beer my friend, you put me back on track.
Thanks!

**Comment by franferri** [comment] 2020-06-29 17:17
I have updated the intellij flutter plugin topic: https://github.com/flutter/flutter-intellij/pull/4622

**Comment by franferri** [comment] 2020-06-29 17:17
This is not resolved but can be closed @iapicca

**Comment by TahaTesser** [comment] 2020-06-30 08:23
Hi @franferri 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-06-30 08:23 UTC
Labels: in triage
