### ISSUE TITLE
CacheImageNetwork for flutter web

### ISSUE THREAD

**Issue by RanABI** [flutter/flutter#42582] opened 2019-10-12 14:55 UTC
Hi,
I am migrating my project to flutter web, all is working fine but the cached images.
On mobile devices, I receive and view the image with no problem.
On web, it gets stuck on Circular progress indicator .
Since there is no debugging support for web, I do not know where the problem is, unless flutter web just doesn't support CachedNetworkImage.
If it doesn't - is there an alternative?

Here is my code:
 ```
 CachedNetworkImage getCachedImage(index, url, headers) {
    var cachedImage = new CachedNetworkImage(
      imageUrl: url,
      httpHeaders: headers,
      placeholder: (context, url) => new CircularProgressIndicator(),
      errorWidget: (context, url, error) => new Icon(Icons.error),
      imageBuilder: (context, imageProvider) => Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            image: imageProvider,
            fit: BoxFit.cover,
          ),
        ),
      ),
    );
    return cachedImage;
  }
```

This is the call:
```
 var cachedImage = getCachedImage(i, getUrl(i), headers);
        return GestureDetector(
          child: Hero(
              tag: 'imageHero',
              child: Container(
                padding: EdgeInsets.only(left: 10,right: 10),
                height: deviceSize.height * 0.3,
                width: deviceSize.width * 0.4,
                child: Center(
                  child: cachedImage,
                ),
              )
```

**Target Platform: Chrome**
**Target OS version/browser: Windows10 , Chrome**

Flutter analyze 

```
Analyzing rejects_web...                                                

   info - Unused import: './widgets/splash_screen.dart' - lib\main.dart:20:8 - unused_import
   info - Unused import: './widgets/http_override.dart' - lib\main.dart:33:8 - unused_import
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\providers\checklist_item_list.dart:15:13 - sdk_version_ui_as_code     
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\providers\constructs.dart:18:13 - sdk_version_ui_as_code
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\providers\contractors.dart:54:13 - sdk_version_ui_as_code
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\providers\contractors.dart:58:13 - sdk_version_ui_as_code
   info - The value of the local variable 'bodyContent' isn't used - lib\providers\contractors.dart:100:13 - unused_local_variable
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\providers\rejects.dart:15:13 - sdk_version_ui_as_code
   info - Unused import: '../utils/constants.dart' - lib\providers\sites.dart:8:8 - unused_import
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\providers\sites.dart:17:13 - sdk_version_ui_as_code
   info - This function has a return type of 'Future<void>', but doesn't end with a return statement - lib\providers\sites.dart:56:3 - missing_return
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\providers\subconstructs.dart:18:13 - sdk_version_ui_as_code
   info - The value of the field '_isLoading' isn't used - lib\screens\add_building_item.dart:32:7 - unused_field
   info - The value of the field '_isInit' isn't used - lib\screens\add_task_screen.dart:75:7 - unused_field
   info - The value of the local variable 'errorMessage' isn't used - lib\screens\auth_screen.dart:154:11 - unused_local_variable
   info - This function has a return type of 'String', but doesn't end with a return statement - lib\screens\auth_screen.dart:301:38 - missing_return
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\screens\auth_screen.dart:328:23 - sdk_version_ui_as_code
   info - This function has a return type of 'String', but doesn't end with a return statement - lib\screens\auth_screen.dart:335:35 - missing_return
   info - The for, if, and spread elements weren't supported until version 2.2.2, but this code is required to be able to run on earlier versions - lib\screens\auth_screen.dart:346:23 - sdk_version_ui_as_code
   info - The value of the field '_isLoading' isn't used - lib\screens\checklist_item_screen.dart:24:7 - unused_field
   info - Unused import: '../widgets/item_widget.dart' - lib\screens\constructs_list_screen.dart:14:8 - unused_import
   info - Unused import: '../widgets/bottom_nav_bar.dart' - lib\screens\reject_overview_screen.dart:12:8 - unused_import
   info - Unused import: '../Enums/screen_enum.dart' - lib\screens\reject_overview_screen.dart:15:8 - unused_import
   info - The value of the field '_isLoading' isn't used - lib\screens\reject_overview_screen.dart:24:7 - unused_field
   info - The value of the field '_rejectImages' isn't used - lib\screens\reject_overview_screen.dart:27:14 - unused_field
   info - The value of the field '_initValues' isn't used - lib\screens\reject_overview_screen.dart:28:7 - unused_field
   info - The value of the field '_isIOS' isn't used - lib\screens\sites_list_screen.dart:33:7 - unused_field
   info - The value of the local variable 'deviceSize' isn't used - lib\screens\sites_list_screen.dart:96:11 - unused_local_variable
   info - Unused import: '../widgets/item_widget.dart' - lib\screens\subconstructs_list_screen.dart:13:8 - unused_import
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AppCheckBox.status - lib\widgets\check_box.dart:4:7 - must_be_immutable     
   info - This function has a return type of 'Color', but doesn't end with a return statement - lib\widgets\checklist_item_widget.dart:72:3 - missing_return
   info - The declaration '_activeColor' isn't referenced - lib\widgets\checklist_item_widget.dart:72:9 - unused_element
   info - This function has a return type of 'bool', but doesn't end with a return statement - lib\widgets\checklist_item_widget.dart:88:3 - missing_return
   info - The declaration '_isActiveCheckbox' isn't referenced - lib\widgets\checklist_item_widget.dart:88:8 - unused_element
   info - Unused import: 'package:rejects_manager/widgets/long_pressed_popup.dart' - lib\widgets\collapsing_list.dart:2:8 - unused_import
   info - Unused import: 'item_widget.dart' - lib\widgets\collapsing_list.dart:22:8 - unused_import
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: CollapsingList.appBar, CollapsingList.searchWidget,
          CollapsingList.widgetList, CollapsingList.filter, CollapsingList.itemHeader, CollapsingList.userRole - lib\widgets\collapsing_list.dart:55:7 - must_be_immutable
   info - Field doesn't override an inherited getter or setter - lib\widgets\image_handler.dart:21:28 - override_on_non_overriding_field
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: ItemDetail.isLongPressed, ItemDetail.pageContext,
          ItemDetail.longPressedCounter - lib\widgets\item_widget.dart:19:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: SearchTextField._controller - lib\widgets\search_textfield_widget.dart:10:7 
          - must_be_immutable

40 issues found. (ran in 12.3s)
```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.15-pre.23, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2017.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.39.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by cbenhagen** [comment] 2019-10-13 09:07
Duplicate of https://github.com/flutter/flutter/issues/38781

Quote:
>We plan to rely on browser's built-in caching capabilities. There's no explicit API. The browser is expected to respect the cache headers sent by the server.

PS: You should try to fix all those (unrelated) analyzer issues.

**Comment by yjbanov** [comment] 2019-10-17 22:17
Closing as duplicate.

**Closed by yjbanov** 2019-10-17 22:17 UTC
Labels: ☸ platform-web
