### ISSUE TITLE
Support iPhone’s ProMotion (120hz)

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#90733] opened 2021-09-26 00:41 UTC
Now that iPhone Pro lineup supports [variable refresh rates](https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro) I’m wondering if it can be achieved with Flutter? How does the plist property impacts the performance overall?

**Comment by TahaTesser** [comment] 2021-09-27 10:01
Hi @miguelpruivo 
There is an open issue with lots of activity,  closing as duplicate of https://github.com/flutter/flutter/issues/90675

**Closed by TahaTesser** 2021-09-27 10:01 UTC
Labels: in triage
