### ISSUE TITLE
rtl Text is displayed incorrectly in Web on mobile (or using the device toolbar in Chrome)

### ISSUE THREAD

**Issue by ronytesler** [flutter/flutter#80623] opened 2021-04-17 02:46 UTC
Expected result (happens when using desktop web):
![image](https://user-images.githubusercontent.com/9344207/115099369-13912480-9f3e-11eb-97d6-e7ba3cc0ef56.png)

Actual result, when using mobile or chrome device toolbar:
![image](https://user-images.githubusercontent.com/9344207/115099398-36bbd400-9f3e-11eb-9003-e6cb5f46932c.png)

With a larger app, there are two things that fix the text in runtime:
1. Playing around with the dimensions of the screen (using the device toolbar)
2. Removing 'helperText' from TextFields I have.
2. Clicking on a dropdown in the screen:
Before clicking:
![image](https://user-images.githubusercontent.com/9344207/115098852-13435a00-9f3b-11eb-9f2f-eff4a547bc6c.png)
After clicking:
![image](https://user-images.githubusercontent.com/9344207/115098866-26562a00-9f3b-11eb-82dd-f17317ae9a6d.png)

```
flutter analyze
Analyzing bug...
No issues found! (ran in 1.6s)

```

```

flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.0.3 at c:\flutter\flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Rony\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Rony\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!
```

my code:

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
        localizationsDelegates: [
          GlobalCupertinoLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
      supportedLocales: [
        Locale('en', ''),
        Locale('he', 'IL'),
      ],
      locale: Locale('he', 'IL'),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text("טקסט לבדיקה.", style: TextStyle(fontSize: 20),),
          ],
        ),
      ), 
    );
  }
}
```

**Comment by TahaTesser** [comment] 2021-04-19 08:40
Hi @ronytesler 
The issue isn't clear, can you please what exactly is incorrect?

it's not related to Mobile but `html` renderer (which is the default for mobile when not explicitly providing `--web-renderer`), So we can also reproduce it on desktop using `html` renderer


Here I can see the difference when using both renderers  (left `canvaskit` & right `html`) 
Looks like a duplicate of https://github.com/flutter/flutter/issues/80094

<img width="1440" alt="Screenshot 2021-04-19 at 11 36 13 AM" src="https://user-images.githubusercontent.com/48603081/115206970-d4143500-a103-11eb-934d-45c6eee0221c.png">


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
// import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      supportedLocales: [
        Locale('en', ''),
        Locale('he', 'IL'),
      ],
      locale: Locale('he', 'IL'),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Directionality(
        textDirection: TextDirection.rtl,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                "טקסט לבדיקה.",
                style: TextStyle(fontSize: 20),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.161, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.161 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ce18d702e9 (3 hours ago), 2021-04-19 01:44:02 -0400
    • Engine revision 60f12daf85
    • Dart version 2.14.0 (build 2.14.0-8.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!

```
	
</details>

**Comment by ronytesler** [comment] 2021-04-19 11:37
@TahaTesser Right, I forgot about the rendering difference.
Not sure what exactly is not clear if you reproduced it yourself, can you please let me know what additional information I should add? The second example I gave shows that the text is incorrect but becomes correct if I click the dropdown.

Yes, it looks like [#80094](https://github.com/flutter/flutter/issues/80094)
So I should just use `flutter build web --web-renderer canvaskit` until it's fixed?

This is VERY important for our company - any idea what about [#78550](https://github.com/flutter/flutter/issues/78550)? It's really a deal breaker for projects that use rtl languages. I don't know why it's only P3, that means it's not reasonable to use Flutter Web for our project for the next year or two. Any way to make it at least P2? Any workaround?
Thanks!

**Comment by TahaTesser** [comment] 2021-04-20 06:32
@ronytesler 
Closing as duplicate of https://github.com/flutter/flutter/issues/80094

> So I should just use flutter build web --web-renderer canvaskit until it's fixed?

It is up to you, test your web app on mobile in canvaskit, make sure you've nothing broken. 

Please add `thumbs up` reaction to the issue, it helps the team to prioritize the issue https://github.com/flutter/flutter/issues/78550#issue-835036475

**Closed by TahaTesser** 2021-04-20 06:32 UTC
Labels: in triage
