### ISSUE TITLE
`Mac_ios` tasks failed due to `flutter doctor` failure

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#115386] opened 2022-11-15 19:59 UTC
Two instances:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flutter_view_ios__start_up/6956/overview
```
Doctor summary (to see all details, run flutter doctor -v):
```

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20color_filter_and_fade_perf_ios__e2e_summary/1353/overview
```
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xab
version=2.19.0-401.0.dev (dev) (Mon Nov 14 23:59:52 2022 -0800) on "macos_x64"
pid=96372, thread=10755, isolate_group=kernel-service(0x7f7b3d818000), isolate=kernel-service(0x7f7b3d824000)
os=macos, arch=x64, comp=no, sim=no
isolate_instructions=10976d000, vm_instructions=102ba23e0
```

/cc @christopherfujino

**Comment by zanderso** [comment] 2022-11-15 20:22
This is probably https://github.com/dart-lang/sdk/issues/48668. Closing as a duplicate of https://github.com/flutter/flutter/issues/114980.

**Closed by zanderso** 2022-11-15 20:22 UTC
Labels: tool
