### ISSUE TITLE
[Impeller] Artifacting in the new backdrop filter blur with high sigma values

### ISSUE THREAD

**Issue by ArAmM7** [flutter/flutter#143947] opened 2024-02-22 17:20 UTC
### Steps to reproduce

1. use sigma values 40 or higher in ImageFilter.blur
2. add scrolling under the backdrop filter

### Expected results

Colors shouldn't "jiggle" when under a blur.

### Actual results

The blur hase weird artifacts when there is a scrollable widgets under it. Blur is fullscreen so the results are easier to notice.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(title: 'blur artifacts with high sigma in 3.20'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    super.key,
    required this.title,
  });

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: ListView.separated(
        itemCount: 1000,
        itemBuilder: (_, i) => Container(
          clipBehavior: Clip.antiAlias,
          margin: const EdgeInsets.symmetric(horizontal: 16),
          decoration: BoxDecoration(
            color: Colors.amberAccent,
            borderRadius: BorderRadius.circular(16),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const SizedBox(height: 4),
              for (int x = 0; x < 2; x++)
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    for (int x = 0; x < 10; x++) ...[
                      const FlutterLogo(),
                      Text('$x'),
                    ],
                  ],
                ),
              Image.network(
                'https://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
                height: 200,
                fit: BoxFit.cover,
              ),
              const SizedBox(height: 4),
              Text('Some  text for $i'),
              const SizedBox(height: 4),
            ],
          ),
        ),
        separatorBuilder: (_, __) => const SizedBox(height: 8),
      ),
      bottomNavigationBar: Material(
        color: Colors.transparent,
        child: BottomAppBar(
          color: const Color(0x22131313),
          shape: const CircularNotchedRectangle(),
          shadowColor: Colors.transparent,
          surfaceTintColor: Colors.transparent,
          elevation: 0,
          notchMargin: 0,
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaY: 40, sigmaX: 40),
            child: const ColoredBox(
              color: Colors.transparent,
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/29163975/10d4c383-4edd-447a-ac1a-35652d4aa870

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[flutter] flutter doctor -v
[!] Flutter (Channel master, 3.20.0-11.0.pre.84, on macOS 14.3.1 23D60 darwin-arm64, locale en-AM)
    • Flutter version 3.20.0-11.0.pre.84 on channel master at /Users/aram/fvm/versions/master
    ! Warning: `flutter` on your path resolves to /Users/aram/fvm/versions/3.16.9/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/aram/fvm/versions/master. Consider adding /Users/aram/fvm/versions/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/aram/fvm/versions/3.16.9/bin/dart, which is not inside your current Flutter SDK checkout at /Users/aram/fvm/versions/master. Consider adding /Users/aram/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b48ae31487 (2 hours ago), 2024-02-22 10:47:07 -0500
    • Engine revision 9250bfdb38
    • Dart version 3.4.0 (build 3.4.0-163.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/aram/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • Aram’s iPhone (mobile)          • 00008120-001249D00C32201E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 122.0.6261.57

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
exit code 0

```

</details>

**Comment by ArAmM7** [comment] 2024-02-22 17:20
@gaaclarke

**Comment by gaaclarke** [comment] 2024-02-22 17:25
We just need to tweak `GaussianBlurFilterContents::CalculateScale` to be a little less aggressive in this sigma band.  Now that we've landed the lerp hack hopefully that's bought us more headroom to downsample less.

**Comment by ArAmM7** [comment] 2024-02-22 17:37
I stumbled upon this because we're using a higher size blur in one of our apps.
`CupertinoNavigationBar` uses lower size blur; I think that's why neither performance nor the artifacting were that noticeable in most cases.

**Comment by ArAmM7** [comment] 2024-02-23 07:46
I was trying it on iPhone 15

**Comment by ArAmM7** [comment] 2024-02-23 07:48
@gaaclarke you can try scrolling slowly like in my video, it is much more noticeable that way.

**Comment by danagbemava-nc** [comment] 2024-02-23 07:55
I also couldn't reproduce it on my iPhone XS on `Flutter 3.20.0-11.0.pre.107 • channel master `


https://github.com/flutter/flutter/assets/88313112/95bdac84-aa59-41bf-8f38-73f34b2a2d06

**Comment by ArAmM7** [comment] 2024-02-23 08:12
I see it on both iPhone X and iPhone 15, the later being more noticeable, the recordings don't show it at full probably due to compression. at master fcd154bd24 ie 3.20.0-11.0.pre.107

https://github.com/flutter/flutter/assets/29163975/db56fd74-f4f6-490c-b16a-4eabf65df6b6

https://github.com/flutter/flutter/assets/29163975/071d77f6-36bc-4d3d-b754-76caa029f036

**Comment by ArAmM7** [comment] 2024-02-23 08:21
It's also easier to notice if you look at the edges of the scrollable

**Comment by danagbemava-nc** [comment] 2024-02-26 07:00
Thanks for the hint, I now notice that it happens before the list item has fully come into view. 

Labeling for further investigation. 

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.19.1 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (5 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 121.0.6167.184
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.20.0-13.0.pre.31, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.20.0-13.0.pre.31 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d8503febb1 (2 hours ago), 2024-02-25 23:42:25 -0500
    • Engine revision fd3136782a
    • Dart version 3.4.0 (build 3.4.0-175.0.dev)
    • DevTools version 2.33.0-dev.11

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)                • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 121.0.6167.184
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by jonahwilliams** [comment] 2024-02-26 18:40
Potentially this could be "fixed" on the customer side by specifying decal sampling?

@gaaclarke do we need to keep this issue open? I'm not sure how this compares to Skia's implementaiton. If its comparable then I don't think there is anything to do here.

**Comment by ArAmM7** [comment] 2024-02-27 07:41
The thing is I see some of the "jiggle" in the center of the scrollable too, it's very similar to the one on the edges, but I see it only when I scroll very slowly like in the screen recordings I shared.

**Comment by gaaclarke** [comment] 2024-03-26 00:06
> @gaaclarke do we need to keep this issue open?

Skia demonstrates the same rendering at the bottom when scrolling, so while we could address that it isn't a regression.  Here is a skia recording:

https://github.com/flutter/flutter/assets/30870216/5f7135b3-f390-4c8b-8bc3-52bf6f621def

It's also not the issue originally described.

As for the jittering displayed in the issue description, we can't reproduce it on `main`.  I went back and looked at the new impeller blur versus skia and I've didn't see any issue to the extent of what the videos are showing.  I think there is a little bit of artifacting when scrolling very slowly.  If you go back and look at the skia implementation it demonstrates that same characteristic and can be seen a bit in the video above.   To my eye skia's is worse.  I also double checked release builds and it didn't seem to make a difference.

So, here's what what I propose:
1) We close this issue since what it originally states and shows is not reproducible and thus inactionable.
1) If you think the behavior at the bottom of the screen is incorrect, file an issue against it.  Note that skia and impeller behave the same.
1) Consider filing an issue for the artifacting that happens with the slow scroll including a video capture using Impeller in at the tip of `main`.  Note that skia demonstrates the artifacting too.
1) If you still think the original issue is reproducible on `main`, please reopen if you can find a reliable reproduction.

I think that's the best course of action considering 2 major assertions in this description are contrary to the empirical evidence:
1) There is massive flickering when scrolling (in reality there is a small bit of flickering when scrolling slowly)
1) This bug is unique to impeller.

**Closed by gaaclarke** 2024-03-26 00:06 UTC
Labels: engine, c: rendering, has reproducible steps, P2, e: impeller, team-engine, triaged-engine, found in release: 3.19, found in release: 3.20
