### ISSUE TITLE
I might have found an issue with 'initialValue' in '(Text)FormField()'

### ISSUE THREAD

**Issue by kuyaC** [flutter/flutter#55171] opened 2020-04-19 22:18 UTC
**(Edit: I have spent over an hour writing this and trying to post on stackoverflow, but there is an issue with the code formatting that won't go away, so my only option was to post it here)**

The following code is from a document of my application that deals with an SQLite database, just to give you some context (SQLite is not relevant in this question).

This is a screen/route that helps you create a table in the database.  
Each column that you want to add to the table gets its own little Widget-tree with things to modify (I will add screenshots).  
Each of these widget-trees contain an `Iconbutton`, that deletes the widget-tree, in other words: it removes the column.

The deletion works flawlessly according to:  

 - a    `Text()`-widget I added for testing purposes  
   (compare the content
   of the     `Text()` and     `TextFormField()` widgets in the screenshots)
 - some print statements confirm this as well

The issue seems to be in the     `TextFormField()`, which only has the property '    `initialValue`' set.  
Even though     `setState()` gets called and new     `TextFormField()`-widgets are being created, it appears as if only the last     `TextFormField()` gets deleted, instead the one at the selected index.

I added some Chinese comments to help you find the critical sections more easily.

```import 'package:flutter/material.dart';

class EditTableScreen extends StatefulWidget {
  final String tableName;

  EditTableScreen({this.tableName});

  @override
  _EditTableScreenState createState() => _EditTableScreenState(tableName: tableName);
}

class _EditTableScreenState extends State<EditTableScreen> {
  String tableName;

  _EditTableScreenState({this.tableName});

  //List<String> columnNames = ['']; //init the list with one 'blank' column
  List<String> columnNames = ['t0', 't1', 't2', 't3', 't4'];  //for testing purposes
  List<Widget> columnDescriptions;

  @override
  Widget build(BuildContext context) {
    buildColumnsListView(); //initializes columnDescriptions

    return Scaffold(
      appBar: AppBar(title: Text(tableName)),
      body: Column(
        children: <Widget>[
          TextFormField(initialValue: 'ENTER TABLE NAME HERE'),
          Expanded(
            child: ListView(children: columnDescriptions),
          ),
          RaisedButton(
            child: Text('done'),
            onPressed: () {
              //todo create new table in Database
              // and go back to main screen
              Navigator.pop(context);
            },
          ),
        ],
      ),
    );
  }

  //i used a for loop instead of .map(f) to make it easier to delete items (via index)
  void buildColumnsListView() {
    columnDescriptions = [];
    for (int index = 0; index < columnNames.length; index++) {
      Column column = Column(
        children: <Widget>[
          Row(
            children: <Widget>[
              Text(columnNames[index]),                                   //这里没有错误
              SizedBox(width: 30),
              Expanded(                                                   //这里有错误
                  child: TextFormField(initialValue: columnNames[index]), //WEIRD BEHAVIOR HERE
              ),
              Expanded(child: Text('Datatype')),
              IconButton(
                icon: Icon(Icons.delete),
                onPressed: () {
                  setState(() {
                    //everything seems to work fine
                    print('columnNames: $columnNames');         //都是好的
                    print('remove column at index: \t $index'); //the list changes as expected
                    print('columnNames: $columnNames');         //error is in TextFormField above^^
                  });
                },
              ),
            ],
          ),
          TextFormField(initialValue: 'Constraints'),
        ],
      );
      columnDescriptions.add(column);
    }

    columnDescriptions.add(IconButton(
      icon: Icon(Icons.add_circle_outline),
      onPressed: () {
        setState(() {
          columnNames.add('');
        });
      },
    ));
  }
}



```

Screenshots:  
[before][1]  
[after][2]  
[console][3]

This question: https://stackoverflow.com/questions/58702162/textformfield-initialvalue-gets-the-value-of-the-next-field-when-i-remove-the-fi seems to be very similar, but sorry, I didn't understand both the question and the answer, as I'm new to Flutter.

Thank you very much for reading, any help is appreciated.

  [1]: https://i.stack.imgur.com/CpQ6o.jpg
  [2]: https://i.stack.imgur.com/Q6yX5.jpg
  [3]: https://i.stack.imgur.com/ghouY.png

**Comment by alexZaicev** [comment] 2020-04-19 23:01
I've just investigated your issue and it seems that all the `TextFormField` widgets are the same without specifying unique key. Basically, flutter refer to them as the same object (sorry for my explanation, I don't understand it fully...). So if you add a `UniqueKey()` to your `TextFormField` you will remove the bug. 

```
for (int index = 0; index < columnNames.length; index++) {
      Column column = Column(
        children: <Widget>[
          Row(
            children: <Widget>[
              Text(columnNames[index]),                                   //这里没有错误
              SizedBox(width: 30),
              Expanded(                                                   //这里有错误
                  child: TextFormField(key: UniqueKey(), initialValue: columnNames[index]), //WEIRD BEHAVIOR HERE
              ),
              Expanded(child: Text('Datatype')),
              IconButton(
                icon: Icon(Icons.delete),
                onPressed: () {
                  setState(() {
                    //everything seems to work fine
                    print('columnNames: $columnNames');         //都是好的
                    print('remove column at index: \t $index'); //the list changes as expected
                    print('columnNames: $columnNames');         //error is in TextFormField above^^
                  });
                },
              ),
            ],
          ),
          TextFormField(initialValue: 'Constraints'),
        ],
      );
      columnDescriptions.add(column);
    }
```

For more details about keys you can watch [this link](https://www.youtube.com/watch?v=kn0EOS-ZiIc)

**Comment by kuyaC** [comment] 2020-04-19 23:27
Oh I've seen that vid a few days ago. I don't fully understand it yet, but I see now where my problem may have come from.
Thank your very much for the fast reply Alex 😀

**Comment by alexZaicev** [comment] 2020-04-20 00:53
@kuyaC Great! Can you close the issue is that fixed your problem 🥳

**Closed** 2020-04-20 07:46 UTC
Labels: created via support template
