### ISSUE TITLE
api.flutter.dev : SliverAppBar page has a broken example.

### ISSUE THREAD

**Issue by vanillabeach** [flutter/flutter#86297] opened 2021-07-12 16:14 UTC
https://api.flutter.dev/flutter/material/SliverAppBar-class.html

Interactive example seems to break (cannot compile to JavaScript). I think it's a Content Security Policy (CSP) thing.

**Comment by vanillabeach** [comment] 2021-07-12 16:17
**update**
after pasting it into dartpad.dev, it seems that the culprit is located in the *OverflowBar* widget. 
removing the following code ```alignment: MainAxisAlignment.spaceEvenly,``` makes it work.

**Comment by HansMuller** [comment] 2021-07-12 18:55
The problem appears to be that the OverflowBar's alignment feature, introduced in https://github.com/flutter/flutter/pull/85260, is newer than DartPad's version of Flutter. Sorry about that.

**Comment by HansMuller** [comment] 2021-07-12 18:56
CC @RedBrogdon, @gspencergoog - I guess we're missing some API doc sample testing here

**Comment by gspencergoog** [comment] 2021-07-12 20:38
It's not really the testing: the problem is that there isn't yet a frontend Dartpad option to select the branch to run on. Once we have that, then the stable API site will request the stable branch, and these things won't break the samples.  We do have backend services for dev and beta rolled out in addition to stable, but no frontend options yet.  That's coming, although I'm not sure when it'll be available.

Even when that comes out, there will be some lag between when something lands on master and when it gets to dev, but that should only affect the master API docs site.

**Comment by RedBrogdon** [comment] 2021-07-14 23:53
What version of the SDK is represented by that URL? I was (perhaps wrongly!) under the impression that api.flutter.dev was built off the most recent stable channel release, and master-api.flutter.dev is built with latest master.

FWIW, DartPad's currently running v2.2.3 when the null safety param is set to true.

**Comment by gspencergoog** [comment] 2021-07-15 01:14
You're correct: api.flutter.dev is supposed to be from stable, and master-api.flutter.dev is from master, updated with each commit.

However, I noticed something that might shed some light.

That page is built from stable, but the DartPad running the example doesn't appear to be getting its example code from the stable branch. If you compare the code in the DartPad with the code in the other tab (the one that just shows the source without the template boilerplate), you'll see that the usage of `OverflowBar` is different. In the stable branch source, the example doesn't have an `OverflowBar` at all, and uses a `ButtonBar` instead.

I think it stems from this URL in the stable API doc page:
https://dartpad.dev/embed-flutter.html?split=60&run=true&null_safety=true&sample_id=material.SliverAppBar.2&sample_channel=master

See that `master` at the end?  If I change that to `stable`, it works (and downloads the right sample).

So, since DartPad is running Flutter 2.2.3, but getting its sample code from the master channel, bad things happen.

I wonder if we changed how we're deploying the docs site, and we're moving the master over to stable when publishing or something. I know that in the docs generation, we emit the right URL when building docs in the stable channel (I just tried it).

@christopherfujino do you know if this could be a deployment problem with the docs?

**Comment by RedBrogdon** [comment] 2021-07-15 18:33
That's interesting.

IIRC, we put that `sample_channel` parameter in so that the master-api.flutter.dev docs could have embeds that at least loaded the correct code (even if DartPad wasn't yet able to run it):

https://github.com/dart-lang/dart-pad/blob/master/lib/sharing/gists.dart#L236

Setting it to `master` instructs DartPad to load the snippet from `master-api.flutter.dev/snippets`. Leaving it out entirely or setting it to `stable` directs DartPad to load the code from `api.flutter.dev/snippets`.

**Comment by christopherfujino** [comment] 2021-07-15 18:45
> You're correct: api.flutter.dev is supposed to be from stable, and master-api.flutter.dev is from master, updated with each commit.
> 
> However, I noticed something that might shed some light.
> 
> That page is built from stable, but the DartPad running the example doesn't appear to be getting its example code from the stable branch. If you compare the code in the DartPad with the code in the other tab (the one that just shows the source without the template boilerplate), you'll see that the usage of `OverflowBar` is different. In the stable branch source, the example doesn't have an `OverflowBar` at all, and uses a `ButtonBar` instead.
> 
> I think it stems from this URL in the stable API doc page:
> https://dartpad.dev/embed-flutter.html?split=60&run=true&null_safety=true&sample_id=material.SliverAppBar.2&sample_channel=master
> 
> See that `master` at the end? If I change that to `stable`, it works (and downloads the right sample).

That appears to be generated from: https://github.com/flutter/flutter/blob/stable/dev/snippets/config/skeletons/dartpad-sample.html#L26

```
        <iframe class="snippet-dartpad" src="https://dartpad.dev/embed-flutter.html?split=60&run=true&null_safety=true&sample_id={{id}}&sample_channel={{channel}}"></iframe>
```

I'm not sure what is setting that variable, however. I wonder if this is related to https://github.com/flutter/flutter/issues/77178

**Comment by christopherfujino** [comment] 2021-07-15 18:50
Found it, and it appears to indeed be the same issue: https://github.com/flutter/flutter/blob/stable/dev/snippets/lib/main.dart#L24

**Comment by christopherfujino** [comment] 2021-07-15 18:58
I'm de-duplicating this issue with #77178 and raising the priority.

**Comment by christopherfujino** [comment] 2021-07-17 00:08
Re-opening this issue as, although the root cause has been fixed by https://github.com/flutter/flutter/pull/86501, the API docs will not be fixed until the next stable deploy.

**Comment by christopherfujino** [comment] 2021-07-20 21:59
ok, for stable api docs to be fixed, [this pr](https://github.com/flutter/flutter/pull/86723) needs to land, and then a new docs_publish build to be manually scheduled.

**Comment by nt4f04uNd** [comment] 2021-08-15 21:47
This issue can be closed

**Closed** 2021-08-16 16:11 UTC
Labels: framework, f: material design, d: api docs, d: examples, documentation, passed first triage
