### ISSUE TITLE
[Camera Plugin] How to keep device orientation and camera orientation in sync 

### ISSUE THREAD

**Issue by jzillmann** [flutter/flutter#16587] opened 2018-04-14 10:37 UTC
I'm trying the camera plugin v0.1.2 with the usage code from its example: https://github.com/flutter/plugins/blob/master/packages/camera/example/lib/main.dart

Now the problem i'm having.. If i change the device orientation, the camera preview doesn't follow so the shown picture are rotated to the left/right.

I can improve on this behaviour by disabling device orientation change through setting `SystemChrome.setPreferredOrientations`
Now i always see the picture in correct orientation, but things like the app menu bar don't change and also the picture looking stretched in portrait mode.

So is there a way or is it planned to control camera rotation/orientation !?

**Comment by chinmaygarde** [comment] 2018-04-15 03:13
If possible, can you attach a reduced test case?

**Comment by jzillmann** [comment] 2018-04-22 16:16
Oh, i must confess i not yet dived into the mysteries of flutter testing... but in one or two weeks latest i guess i will have my app ready to do some reality check and compare the results of the app camera withe the results of the standard camera app! Will let you know!

**Comment by jzillmann** [comment] 2018-05-23 06:49
Ok, i did some more testing (manuel).
I'am now at Flutter 0.3.2 and plugin 0.2. I'am using a Galaxy Tab A (2016) device, SM-T280.

I took pictures:
- With the standard Android camera app in vertical and horizontal (rotated left) mode 
- With my app while setting `SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);`
- With my app without the fixed orientation

Here is the comparative result:
<img width="1613" alt="picturecompare" src="https://user-images.githubusercontent.com/148472/40407467-e1c9a55c-5e64-11e8-96b5-54438a0a929d.png">

I noticed:
- Different resolutions between camera and app and also between app1 and app2 (fixed orientation on/off)
- Pictures from the app are rotated wrongly in at least on case (horizontal/vertical)
- File sizes do differ (not sure if thats based on a different resolution, exposure time or quality or something else)

What i basically want is to mimic the camera behaviour as close as possible, means:
- Preview should be full screen
- Can use vertical or horizontal orientation and the resulting pictures/video have the correct orientation and resolution

Looking at the camera's flutter plugin code is see no controls to tweak the behaviour...
Any help or insights appreciated!

**Comment by dev-mush** [comment] 2018-06-13 08:50
I'm facing the same problem, I was thinking that a workaround for me would be to take the picture and then rotate it somehow depending on the device orientation, I can do this because I don't need to preview the image, but I imagine that since you need a preview it would be harder on your side, did you manage to find an alternative and better solution?

**Comment by jzillmann** [comment] 2018-06-21 12:56
Not yet. I was expecting that this was something so core that the google dev's care about...
For me, the picture thing was also intermediate - while i was waiting for video support - so i'm focussing more on the video behaviour now...

Btw, think there are a couple of more people facing that, see e.g. https://github.com/flutter/flutter/issues/18094

**Comment by AlexBacich** [comment] 2018-08-04 11:07
I have similar problem with camera plugin. 

It happens even without rotating the phone. App is started (and locked) in portrait, photo taken in portrait. Bu the photo is saved 90 CCW.

I'm seeing this on Sony F5321(Android 8.0), but not other devices.

**Comment by sebastiancadena** [comment] 2018-09-05 18:38
Any news on this matter?

**Comment by chandeepadissanayake** [comment] 2018-09-07 14:57
Is this issue been addressed by any of the developers of flutter?

**Comment by lance-blo** [comment] 2018-09-28 16:11
Having the same issue. Is this device related? As the same code currently produces the issue on iOS iPhone SE but not on Android OnePlus 3.

**Comment by analogic** [comment] 2018-10-16 08:39
The CameraPreview rotation issue can be workarounded with help of https://pub.dartlang.org/packages/native_device_orientation like this:
```dart
NativeDeviceOrientationReader(
  builder: (context) {
    NativeDeviceOrientation orientation = NativeDeviceOrientationReader.orientation(context);

    int turns;
    switch (orientation) {
      case NativeDeviceOrientation.landscapeLeft: turns = -1; break;
      case NativeDeviceOrientation.landscapeRight: turns = 1; break;
      case NativeDeviceOrientation.portraitDown: turns = 2; break;
      default: turns = 0; break;
    }

    return RotatedBox(
      quarterTurns: turns,
      child: _cameraPreviewWidget()
    );
  }
)
```

**Comment by zinwalin** [comment] 2018-11-13 22:36
No fix yet.

**Comment by erikmonsonisperez** [comment] 2018-11-28 11:33
> I have similar problem with camera plugin.
> 
> It happens even without rotating the phone. App is started (and locked) in portrait, photo taken in portrait. Bu the photo is saved 90 CCW.
> 
> I'm seeing this on Sony F5321(Android 8.0), but it's fine with other devices.

I've the same problem. Any news on this issue?

**Comment by magnocasmor** [comment] 2018-11-30 19:47
They releases the version 0.2.6 of camera plugin yesterday that fix in Android. Any news to IPhone?

**Comment by zinwalin** [comment] 2018-12-06 23:52
> They releases the version 0.2.6 of camera plugin yesterday that fix in Android. Any news to IPhone?

Camera 0.2.6 fixed issue on Android, still not for iOS.

**Comment by mklim** [comment] 2019-01-04 20:16
I've been looking into this on iOS. From what I can tell the [(deprecated) callback](https://developer.apple.com/documentation/avfoundation/avcapturephotocapturedelegate/1778647-captureoutput?language=objc) we're registering [here](https://github.com/flutter/plugins/blob/efe4c1b/packages/camera/ios/Classes/CameraPlugin.m#L57-L62) doesn't get any EXIF metadata or orientation from the camera, it just gets raw pixels from the capture. There's a [newer callback](https://developer.apple.com/documentation/avfoundation/avcapturephotocapturedelegate/2873949-captureoutput?language=objc) that contains metadata, but it's iOS 11.0+ only and the camera plugin supports 10.0+. I think unfortunately the solution here for at least 10.x is going to be to poll the accelerometer and save that like the plugin is already doing on the Android side. There's another [iOS API that does get device orientation on demand](https://developer.apple.com/documentation/uikit/uidevice/1620053-orientation?language=objc), but similar to the Android equivalent it doesn't return the true device orientation when the UI is locked.

**Closed** 2019-01-07 23:17 UTC
Labels: p: camera, p: first party, plugin

**Comment by RussellZornes** [comment] 2019-06-06 20:35
There is not a single behavior that is correct in all situations.

Sometimes I want the camera to follow rotation, sometimes I don't.
It should be an option in the API.

For example if I am writing a photo taking app I might want to rotate my device to take a landscape photo so I want the camera to follow the rotation (camera locked to device orientation).

Another example is I am writing a kiosk and I want the camera to always be a certain orientation no matter how the device is oriented. (camera on a swivel always pointing up).

**Comment by iNima** [comment] 2019-08-19 03:11
Hi @mklim ,
This is exactly what I need now and thanks for clarifying the root cause of the issue.
In Android, I receive all Exif data for the captured photo via both `Camera` plugin (0.5.3+1) and `Image_Picker` plugin (0.6.0+17) but on iOS I receive full Exif data only from `Image_Picker` plugin, not the `Camera` plugin.
Based on what you mentioned above, I know that the reason why we still receive the orientation data is related to your fix PR which has already merged.
What I really need is the full Exif data not only the orientation. Fortunately, my app's deploy target is iOS 11+ so I'm happy to use the new callback you mentioned above.
Is there any sample code related to that in Objective-C to be able to replace it with the current approach in the Camera plugin?
Is there any roadmap for fixing the issue to have full Exit data on iOS as well?

**Comment by mklim** [comment] 2019-08-22 18:00
@RussellZornes sorry about the delay. Filed a feature request for controlling the camera orientation in #39071.

@iNima I filed a feature request for it at #39070. I don't think we have any sample code for this yet, but the general idea if you're patching this yourself would be to fork what the plugin is currently doing, then replace the current limited callback with the newer one. I think it would be straightforward, but I can't say for 100% sure since I haven't dug into it in detail myself yet.
