### ISSUE TITLE
More details platform-level crash details

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#50838] opened 2020-02-14 22:25 UTC
## Use case
When debugging an application that crashes, we only get surface information that usually, (in my case) doesn't give enough detail to properly diagnose, so I have to either run in Xcode or check the logcat.
My current crash is:
**Flutter**:
```*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
	3   Runner                              0x000000010bf1d678 -[GIDSignIn signInWithOptions:] + 242
	4   Runner                              0x000000010bf19c6d -[GIDSignIn signIn] + 64
	5   Runner                              0x000000010bf4ed9a -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2234
	6   Flutter                             0x000000010e17adb5 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	7   Flutter                             0x000000010e10eba0 _ZNK7flut<…>
```
**When run with Xcode:**
```
2020-02-14 14:17:30.015123-0800 Runner[917:2661009] Google Maps SDK for iOS version: 2.7.30514.0
2020-02-14 14:17:30.015363-0800 Runner[917:2661009] New version of Google Maps SDK for iOS available: 3.7.0.0
2020-02-14 14:17:33.917465-0800 Runner[917:2661654] 6.16.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
>>Valuable line>>>> 2020-02-14 14:18:32.246350-0800 Runner[917:2661009] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Your app is missing support for the following URL schemes: com.googleusercontent.apps.530969775686-p5l7hnnctusl48pcdvj144134ti6lu82'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
	3   Runner                              0x0000000102cda548 -[GIDSignIn signInWithOptions:] + 242
	4   Runner                              0x0000000102cd6b3d -[GIDSignIn signIn] + 64
	5   Runner                              0x0000000102d0bc6a -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2234
	6   Flutter                             0x00000001051a7db5 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	7   Flutter                             0x000000010513bba0 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	8   Flutter                             0x000000010513f64e _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	9   Flutter                             0x00000001051a1969 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_32NS_9allocatorIS8_EEFvvEEclEv + 57
	10  Flutter                             0x000000010514eb73 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 117
	11  Flutter                             0x00000001051538b8 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	12  CoreFoundation                      0x00007fff23bd4b94 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	13  CoreFoundation                      0x00007fff23bd4882 __CFRunLoopDoTimer + 1026
	14  CoreFoundation                      0x00007fff23bd3eda __CFRunLoopDoTimers + 266
	15  CoreFoundation                      0x00007fff23bcec4e __CFRunLoopRun + 2238
	16  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	17  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	18  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	19  Runner                              0x000000010236a588 main + 72
	20  libdyld.dylib                       0x00007fff5227ec25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by jmagman** [comment] 2020-02-18 19:36
Duplicate of https://github.com/flutter/flutter/issues/22536.

**Closed by jmagman** 2020-02-18 19:36 UTC
Labels: a: error message, tool
