### ISSUE TITLE
[Web] The flutter web page will not be responsive web design while printing.

### ISSUE THREAD

**Issue by derjohng** [flutter/flutter#95678] opened 2021-12-22 13:57 UTC
## Steps to Reproduce

1. Open flutter web page with chrome. For example, https://gallery.flutter.dev/#/
2. Open Menu File > Print
![1222_001](https://user-images.githubusercontent.com/1803036/147101351-25cd7fcd-3d44-49a2-8c84-bd9cd101e18b.png)

**Expected results:** 
The print preview should be responsive web of whole page, not just a part of web page.

**Actual results:** 
The print preview will not rendered according to the width, and just clip of whole web page. This kind of behavior is not like other responsive web design (such as, https://getbootstrap.com/). Try to print  getbootstrap.com website, you will see the layout will be rendered while printing. 
![1222_002](https://user-images.githubusercontent.com/1803036/147102060-e7b9e1d0-9068-412d-bc15-98a02101c716.png)

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2021-12-23 05:55
Verified this using a counter app and running on both renderers and observed below, ie, the print preview seems to be mis-aligned as compared to non-Flutter web apps:

<img width="1223" alt="Screenshot 2021-12-23 at 11 16 29 AM" src="https://user-images.githubusercontent.com/67046386/147194914-0d89b155-0d71-41db-82d2-a4896e5c6cee.png">
<img width="1099" alt="Screenshot 2021-12-23 at 11 20 51 AM" src="https://user-images.githubusercontent.com/67046386/147194929-156f15c7-3d27-45d8-a1a7-758f2f112d4a.png">
<img width="1096" alt="Screenshot 2021-12-23 at 11 21 44 AM" src="https://user-images.githubusercontent.com/67046386/147194931-4106b7a6-fbc4-4d28-92a4-7d119e57e291.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.9.0-1.0.pre.173, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.173 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 60de93f297 (2 hours ago), 2021-12-22 22:09:12 -0500
    • Engine revision 2235abc0aa
    • Dart version 2.16.0 (build 2.16.0-128.0.dev)
    • DevTools version 2.9.2
    
[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

**Comment by maheshmnj** [comment] 2021-12-23 06:24
Duplicate of https://github.com/flutter/flutter/issues/32249 and https://github.com/flutter/flutter/issues/91671 (closed)

**Comment by maheshmnj** [comment] 2021-12-23 06:25
Closing as a duplicate of #32249.

**Closed by maheshmnj** 2021-12-23 06:25 UTC
Labels: platform-web, a: layout, has reproducible steps, found in release: 2.8, found in release: 2.9
