### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by Kijacode** [flutter/flutter#145080] opened 2024-03-13 12:17 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SentinelException
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2499:21)
#2      VmService.reloadSources (package:vm_service/src/vm_service.dart:2354:7)
#3      _reloadDeviceSources (package:flutter_tools/src/run_hot.dart:1275:33)
<asynchronous suspension>
#4      defaultReloadSourcesHelper (package:flutter_tools/src/run_hot.dart:1208:65)
<asynchronous suspension>
#5      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:958:38)
<asynchronous suspension>
#6      HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:868:16)
<asynchronous suspension>
#7      HotRunner.restart (package:flutter_tools/src/run_hot.dart:765:36)
<asynchronous suspension>
#8      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1777:40)
<asynchronous suspension>
#9      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1830:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.9, on macOS 14.3 23D56 darwin-arm64, locale en-TZ)
    [32m•[39m Flutter version 3.16.9 on channel stable at /Users/../development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 41456452f2 (7 weeks ago), 2024-01-25 10:06:23 -0800
    [32m•[39m Engine revision f40e976bed
    [32m•[39m Dart version 3.2.6
    [32m•[39m DevTools version 2.28.5

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/../Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 33.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15C500b
    [32m•[39m CocoaPods version 1.14.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.87.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.84.0

[32m[✓][39m VS Code (version 1.70.2)
    [32m•[39m VS Code at /Users/ab02488/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.84.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m SM A336B (mobile) • RFCT50SDE0R • android-arm64  • Android 14 (API 34)
    [32m•[39m macOS (desktop)   • macos       • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    [32m•[39m Chrome (web)      • chrome      • web-javascript • Google Chrome 122.0.6261.112
    [33m![39m Error: Browsing on the local area network for Sarah’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.11+68
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1

**Comment by darshankawar** [comment] 2024-03-13 12:38
Closing as duplicate of https://github.com/flutter/flutter/issues/78214

**Closed by darshankawar** 2024-03-13 12:38 UTC
Labels: in triage
