### ISSUE TITLE
Flutter Firebase Phone Authentication not receiving OTP on IPHONE 11 Max

### ISSUE THREAD

**Issue by randeepbagga** [flutter/flutter#90834] opened 2021-09-27 21:20 UTC
## Steps to Reproduce

1. Use Firebase_auth plugin for Phone Autentication with firebase.
2. All Iphone except IPHONE 11 pRO mAX IS NOT RECEIVING otp CODE FROM FIREBASE. Flutter firebase phone authentication doesn't work on IPHONE 11 AND 12 Pro max. It works fine on all other iphones.
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by psenakv** [comment] 2021-09-28 00:01
Can you post your `flutter doctor -v`? Which version of firebase_auth plugin are you using?

**Comment by randeepbagga** [comment] 2021-09-28 00:08
using firebase_auth: 0.15.3
I didn't release my app since march. Flutter is 1.22.5
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H1419 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/sam/flutter
    • Framework revision 7891006299 (10 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sam/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.11.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 5D0722BE-D053-41F8-A0C1-9EF17BBE2E9A • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!

**Comment by psenakv** [comment] 2021-09-28 00:11
firebase_auth current version is `3.1.1`. Try using the latest and see if the problem persist.

**Comment by randeepbagga** [comment] 2021-09-28 00:17
App is in production and  works fine on other iphones. However just not on 11 and 12 max. Also if I click on Settings inside Iphone 11 max and then click on my app, it doesn't show Camera and Notifications as options. Just shows  "siri & search" and "background app refresh toggled off" Not sure why iphone max doesn't even show camera and notifications. Both are enabled in Info.plist

**Comment by randeepbagga** [comment] 2021-09-28 00:19
Here is what i get when i change to 3.1.1 
Because tickme depends on firebase_auth >=0.21.0-1.0.nullsafety.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed. 
Not sure how to resolve this

**Comment by randeepbagga** [comment] 2021-09-28 00:23
I cliked on Iphone 11 max Settings-> Notifications  ( my app doesn't show up here). App is appearing in notifications for other iphones. Looks like config issue.

**Comment by psenakv** [comment] 2021-09-28 00:29
You are using almost 2 years old version of this plugin and old version of Flutter, so it's hard to tell where the problem is. Try upgrading your app to latest possible versions of plugins, because it will probably get solved by just upgrading to latest. However, you will probably run to few troubles, because at least some of your plugins would have breaking changes by now. Try solving these and see if the problem persist after you upgrade your plugins.

Also, are you testing on real device or simulator?

**Comment by randeepbagga** [comment] 2021-09-28 00:32
I will test on real device tomorrow for iphone 11 max. Its working fine on iphone 8 plus( my current phone)
I had some customers calling me that app is not sending OTP on 11 pro max. So they can't login. Thats how i came to know about this issue. OTP is fine on iphone 11 just not max.

**Comment by randeepbagga** [comment] 2021-09-28 00:33
But Settins->Notifications in 11 pro max doesn't shows our app. Thats very strange. May e some config issue. Probably inof.plis

**Comment by randeepbagga** [comment] 2021-09-28 00:34
Any ways I really appreciate your help here.  Thank you so much.

**Comment by darshankawar** [comment] 2021-09-28 07:27
@randeepbagga 
Firebase related issues need to be opened in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues
Closing from here.

**Closed by darshankawar** 2021-09-28 07:27 UTC
Labels: in triage

**Comment by randeepbagga** [comment] 2021-09-28 12:22
Hi- This is flutter issues. I am struggling to find answers here. Please keep it open for more feedbacks.
Thanks
