### ISSUE TITLE
App crashes after firebase authentication.

### ISSUE THREAD

**Issue by valv008** [flutter/flutter#44341] opened 2019-11-07 11:29 UTC
I migrated to Android x. Everything works fine till authentication and I am able to see the registered users but after that the app quits.

This is supposed to happen but the app quits.
``` dart
onPressed: () async {
                   try{ final newuser =  await _auth.createUserWithEmailAndPassword(email: email,password: password);
                    Navigator.pushNamed(context, ChatScreen.id);
                     if(newuser !=null ){ 
                      
                     }
                   }
                   catch(e){
                     print(e);
                   }
```

**Comment by janmoppel** [comment] 2019-11-07 11:45
Hello @valv008 !

Thank you for posting an issue.
Can you please also provide the `flutter doctor -v` command output?
Also, does app provide any logs?

**Comment by iapicca** [comment] 2019-11-15 16:16
Hi @valv008 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-15 16:16 UTC
Labels: p: firebase_auth, plugin, waiting for customer response, ▣ platform-android
