### ISSUE TITLE
URL resolution of main.dart.js is broken after migrating to 3.24

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#153077] opened 2024-08-08 08:46 UTC
### Steps to reproduce

Set base href in document to "/"
Make a web app that uses url path strategy
Try to refresh app from "/someURL"

### Expected results

main.dart.js is loaded from /main.dart.js

### Actual results

/ is stripped from base url during URL resolution and main.dart.js is loaded relative to document instead of root

This regression is caused by recent changes here:

https://github.com/flutter/engine/blob/main/lib/web_ui/flutter_js/src/utils.js
https://github.com/flutter/engine/blob/main/lib/web_ui/flutter_js/src/entrypoint_loader.js

In 3.22 the / is not stripped, but in 3.24 it is stripped.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by markusrubey** [comment] 2024-08-08 08:53
possible duplicate of https://github.com/flutter/flutter/issues/152995 - which seems to be fixed on master.

**Comment by jezell** [comment] 2024-08-08 09:01
@markusrubey sounds like a similar issue, though this has nothing to do with go_router as implied by the other issue. It's a problem with the bootstrapping logic of flutter iteself.

**Comment by jezell** [comment] 2024-08-08 09:05
<img width="607" alt="Screenshot 2024-08-08 at 2 02 20 AM" src="https://github.com/user-attachments/assets/5cece99e-7c8f-4d49-851d-42e153e841b5">

Error I see in console is a little different than the MIME type error, but I'd suspect you are correct that might be the same root cause. Different logic on the server side where the pages are being served could result in these two different errors from serving HTML when the js file is not found.

**Comment by jezell** [comment] 2024-08-08 15:30
@huycozy I believe the difference is just the way the server implementation is coded. I'm fairly certain they are the same issue in the boostrapping of the app scripts.

**Comment by Cobolt77** [comment] 2024-08-08 18:06
We are having the same exact issues on all our projects using Flutter 3.24 on the Stable channel.

**Comment by jezell** [comment] 2024-08-08 20:06
@huycozy maybe addressed by: https://github.com/flutter/engine/pull/54446

**Comment by huycozy** [comment] 2024-08-09 04:42
@jezell I think so. Let's track it for updates. Once a new stable hotfix is released, please check again. Closing this to concentrate on https://github.com/flutter/flutter/issues/152995 since it has the same steps to reproduce issue.

**Closed by huycozy** 2024-08-09 04:42 UTC
Labels: in triage
