### ISSUE TITLE
Android license status unknown.

### ISSUE THREAD

**Issue by Wdam** [flutter/flutter#87092] opened 2021-07-27 07:30 UTC
`flutter doctor`
![image](https://user-images.githubusercontent.com/42366809/127113565-85f46158-e02e-4d94-b344-42f4879c43d1.png)
`flutter doctor --android-licenses`
![image](https://user-images.githubusercontent.com/42366809/127113669-95337535-59e7-4824-835a-cb2d952713ad.png)
`doctor -v`
![image](https://user-images.githubusercontent.com/42366809/127114012-6bde8664-606f-4b9e-8729-e124f7666fc4.png)
android studio
![image](https://user-images.githubusercontent.com/42366809/127113865-4e082f77-4a66-43f0-94be-8e197059a6a8.png)

**Comment by hndrbrm** [comment] 2021-07-27 07:45
Same with [#86236](https://github.com/flutter/flutter/issues/86236)
Solution on [SO](https://stackoverflow.com/a/58652345/4218210)

**Comment by Wdam** [comment] 2021-07-27 08:03
> Same with [#86236](https://github.com/flutter/flutter/issues/86236)
> Solution on [SO](https://stackoverflow.com/a/58652345/4218210)
> 
> Basically update the `cmdline-tools`.
> The included `cmdline-tools` is not compatible with Java 11.
> Android Studio update its java sdk from 8 -> 11.
> Only the updated `cmdline-tools` comply with java 11, as far as i know.
> 
> I personally have tried update the latest cmdline-tools from inside AndroidStudio by checking it.
> But it still failed.
> I solved it by manually download from [here](https://developer.android.com/studio#command-tools)
> And put it into `${androidSdk}/cmdline-tools/latest`
> The `.../latest` directory is important, without that it won't work.

**Comment by Wdam** [comment] 2021-07-27 08:03
Your solution is similar to this86594
<https://github.com/flutter/flutter/issues/86594>，I have tried it and it
didn't work

hndrbrm ***@***.***> 于2021年7月27日周二 下午3:45写道：

**Comment by hndrbrm** [comment] 2021-07-27 08:09
If it is possible could you give the full log of `flutter doctor --android-licenses -vv`

**Comment by Wdam** [comment] 2021-07-27 08:14
>
> PS D:\flutter sdk\flutter-2.2.3> flutter doctor --android-licenses -vv
> [  +54 ms] executing: [D:\flutter sdk\flutter-2.2.3/] git -c
> log.showSignature=false log -n 1 --pretty=format:%H
> [  +55 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
> --pretty=format:%H
> [   +1 ms] 360044e7bf47331fe1258188d5c6cfbf80d14d10
> [        ] executing: [D:\flutter sdk\flutter-2.2.3/] git tag --points-at
> 360044e7bf47331fe1258188d5c6cfbf80d14d10
> [ +232 ms] Exit code 0 from: git tag --points-at
> 360044e7bf47331fe1258188d5c6cfbf80d14d10
> [   +2 ms] executing: [D:\flutter sdk\flutter-2.2.3/] git describe --match
> *.*.* --long --tags
> 360044e7bf47331fe1258188d5c6cfbf80d14d10
> [  +58 ms] Exit code 128 from: git describe --match *.*.* --long --tags
> 360044e7bf47331fe1258188d5c6cfbf80d14d10
> [        ] fatal: No tags can describe
> '360044e7bf47331fe1258188d5c6cfbf80d14d10'.
>            Try --always, or create some tags.
> [   +2 ms] Could not interpret results of "git describe":
> [   +1 ms] executing: [D:\flutter sdk\flutter-2.2.3/] git rev-parse
> --abbrev-ref --symbolic @{u}
> [  +27 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] fatal: no upstream configured for branch 'master'
> [  +43 ms] executing: [D:\flutter sdk\flutter-2.2.3/] git rev-parse
> --abbrev-ref HEAD
> [  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] master
> [  +41 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
> update.
> [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
> required, skipping update.
> [  +35 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
> update.
> [        ] Artifact Instance of 'GradleWrapper' is not required, skipping
> update.
> [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
> update.
> [        ] Artifact Instance of 'FlutterSdk' is not required, skipping
> update.
> [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
> required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
> required, skipping update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'FontSubsetArtifacts' is not required,
> skipping update.
> [        ] Artifact Instance of 'PubDependencies' is not required,
> skipping update.
> [  +12 ms] executing: [D:\flutter sdk\flutter-2.2.3/] git rev-parse
> --abbrev-ref HEAD
> [  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [   +1 ms] master
> [   +3 ms] executing: [D:\flutter sdk\flutter-2.2.3/] git fetch
> https://github.com/flutter/flutter.git --tags -f
> [+19644 ms] Exit code 128 from: git fetch
> https://github.com/flutter/flutter.git --tags -f
> [        ] fatal: unable to access '
> https://github.com/flutter/flutter.git/': OpenSSL SSL_read: Connection
> was reset,
> errno 10054
> [        ] executing: [D:\flutter sdk\flutter-2.2.3/] git tag --points-at
> HEAD
> [  +59 ms] Exit code 0 from: git tag --points-at HEAD
> [        ] executing: [D:\flutter sdk\flutter-2.2.3/] git describe --match
> *.*.* --long --tags HEAD
> [  +53 ms] Exit code 128 from: git describe --match *.*.* --long --tags
> HEAD
> [        ] fatal: No tags can describe
> '360044e7bf47331fe1258188d5c6cfbf80d14d10'.
>            Try --always, or create some tags.
> [        ] Could not interpret results of "git describe":
> [   +2 ms] executing: D:\Android\jre\bin\java -version
> [ +118 ms] Exit code 0 from: D:\Android\jre\bin\java -version
> [        ] openjdk version "11.0.8" 2020-07-14
>            OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
>            OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed
> mode)
> : Ҳ޷ sdk\cmdline-tools\latest\bin\\..
> ԭ: java.lang.ClassNotFoundException: sdk\cmdline-tools\latest\bin\\//
> [ +245 ms] "flutter doctor" took 20,229ms.
> [ +149 ms] ensureAnalyticsSent: 145ms
> [   +1 ms] Running shutdown hooks
> [        ] Shutdown hooks complete
> [        ] exiting with code 0

*The magic is that I can actually run Android apps on vscode and android
studio *

hndrbrm ***@***.***> 于2021年7月27日周二 下午4:10写道：

**Comment by hndrbrm** [comment] 2021-07-27 08:22
From the error: I think your flutter sdk is corrupted.
Can you try to check it. Go to your flutter sdk directory, and type `git status`. What does it shows?

**Comment by Wdam** [comment] 2021-07-27 08:25
[image: image.png]

hndrbrm ***@***.***> 于2021年7月27日周二 下午4:22写道：

**Comment by Wdam** [comment] 2021-07-27 08:35
@h
![image](https://user-images.githubusercontent.com/42366809/127123300-81ab552d-8957-4973-a601-f6a4fef3356e.png)

**Comment by hndrbrm** [comment] 2021-07-27 08:39
Yes it confirmed my guess, your flutter sdk is broken.

The simplest way is to redownload your flutter sdk.

**Comment by Wdam** [comment] 2021-07-27 08:51
@hndrbrm 
Unfortunately the problem still exists
But it doesn’t seem to affect my development, thank you for your help
![image](https://user-images.githubusercontent.com/42366809/127124937-a9a550a4-f56b-49fe-bd97-9eaaec642dd8.png)
![image](https://user-images.githubusercontent.com/42366809/127125203-b261d95b-82bb-4038-a705-f8e3ecb4d944.png)

**Comment by Wdam** [comment] 2021-07-27 08:53
@hndrbrm 
I have two flutter files, one branch is master and the other is stable. I don’t know if this has any effect.
![image](https://user-images.githubusercontent.com/42366809/127125579-0aaff83f-a138-454f-aec4-f5d281ab9758.png)

**Comment by darshankawar** [comment] 2021-07-27 09:04
@Wdam 
First of all, please refrain from posting screenshots as comments, which makes it difficult to read. Post your error messages in properly formatted text so that we can use them to verify the issue.

Ideally, installing command line tools should resolve the issue as mentioned in above similar links and solutions. If you are using multiple flutter versions, you need to check your path and java home variables to properly link to your corresponding flutter version.
Also, since your original issue is related to not accepting android licenses for which the solution is to install cmd tools. Your sub-issue could be related to your setup for which support channels like StackOverflow is a correct platform to discuss and share your findings. You can also check for similar fixed / solved issues in this repo which has solutions to this issue.

I am going ahead and closing this from here. If you disagree, or think this is a unique issue in the flutter doctor, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-07-27 09:04 UTC
Labels: in triage

**Comment by Wdam** [comment] 2021-07-27 09:09
@darshankawar  ok
