### ISSUE TITLE
Nested StatefulWidgets of same types crash when updating with same subtype on non-web platforms

### ISSUE THREAD

**Issue by SaadArdati** [flutter/flutter#142532] opened 2024-01-30 17:05 UTC
### Steps to reproduce

1. Run sample app.
2. Wait 20-40 seconds as the ticker ticks.
3. Crash.

I am unsure why this crash happens, but from what I can tell, the Flutter Framework or underlying Dart VM is confusing types somehow between two widgets of the same type but with two different values.

Notable points:
- The issue has something to do with equality operations. There are multiple ways to prevent the crash from happening. The most notable is that didUpdateWidget MUST be run by at least _one_ of the two widgets in the sample.
- The equality and hashcode overrides in Effect allow for proper comparison of the types in didUpdateWidget, however, that's all they do, they will trigger didUpdateWidget's if statement ONCE and that's enough to produce the crash. If you remove the, the equality operations, the if statement in didUpdateWidget will always pass as the types may not be the same reference and the `effect` field will update to a "corrected" state. Corrected is a strong word because the behaviour should never happen.
- The ticker is necessary to keep refreshing the build function. The build function will keep rebuilding until it spontaneously crashes with mixed types. It thinks TranslateEffect is ScaleEffect and vice versa.
- The one-frame delay is important to trigger didUpdateWidget to change at least once for at least one of the two EffectWidgets.
- You can also get this to crash in didUpdateWidget by using the `effect`'s functions directly in the didUpdateWidget function. There is a complex but familiar example in hyper_effects: https://github.com/hyper-designed/hyper_effects/blob/main/lib/src/effect_widget.dart#L69 This line crashes in the exact same way. But the sample provided is a minimal reproducible sample. This is just to highlight that this issue is not only about the build function's cycle.

### Expected results

No crash.

### Actual results

Crash:

```
flutter: build: TranslateEffect vs TranslateEffect | true
flutter: build: ScaleEffect vs ScaleEffect | true
flutter: tick: 8
flutter: build: TranslateEffect vs TranslateEffect | true
flutter: build: ScaleEffect vs ScaleEffect | true
flutter: tick: 8
flutter: build: TranslateEffect vs TranslateEffect | true
flutter: build: ScaleEffect vs ScaleEffect | true
flutter: tick: 8
flutter: build: TranslateEffect vs TranslateEffect | true
flutter: build: ScaleEffect vs ScaleEffect | true
flutter: tick: 8
flutter: build: ScaleEffect vs TranslateEffect | false              <--------------------------------------------

======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building EffectWidget(state: _EffectWidgetState#e8691):
Class 'TranslateEffect' has no instance getter 'scale'.
Receiver: Instance of 'TranslateEffect'
Tried calling: scale

The relevant error-causing widget was: 
  EffectWidget EffectWidget:file:///Users/saadardati/IdeaProjects/covariant_bug/lib/main.dart:102:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      ScaleEffect.apply (package:covariant_bug/main.dart:41:30)
#2      _EffectWidgetState.build (package:covariant_bug/main.dart:151:19)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#12     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#20     _invoke (dart:ui/hooks.dart:312:13)
#21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#22     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  runApp(const App());
}

abstract class Effect {
  const Effect();

  Widget apply(BuildContext context, Widget child);
}

class TranslateEffect extends Effect {
  final Offset offset;

  TranslateEffect(this.offset);

  @override
  Widget apply(BuildContext context, Widget child) =>
      Transform.translate(offset: offset, child: child);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslateEffect &&
          runtimeType == other.runtimeType &&
          offset == other.offset;

  @override
  int get hashCode => runtimeType.hashCode ^ offset.hashCode;
}

class ScaleEffect extends Effect {
  final double scale;

  ScaleEffect(this.scale);

  @override
  Widget apply(BuildContext context, Widget child) =>
      Transform.scale(scale: scale, child: child);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScaleEffect &&
          runtimeType == other.runtimeType &&
          scale == other.scale;

  @override
  int get hashCode => runtimeType.hashCode ^ scale.hashCode;
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TickingTimeBomb(),
    );
  }
}

class TickingTimeBomb extends StatefulWidget {
  const TickingTimeBomb({super.key});

  @override
  State<TickingTimeBomb> createState() => _TickingTimeBombState();
}

class _TickingTimeBombState extends State<TickingTimeBomb>
    with SingleTickerProviderStateMixin {
  late final Ticker ticker;

  double scale = 1;

  @override
  void initState() {
    super.initState();

    ticker = createTicker((Duration elapsed) {
      debugPrint('tick: ${elapsed.inSeconds}');
      setState(() {});
    })
      ..start();

    SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
      update();
    });
  }

  void update() {
    if (!mounted) return;
    scale = 2;
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: EffectWidget(
        effect: TranslateEffect(const Offset(100, 100)),
        child: EffectWidget(
          effect: ScaleEffect(scale),
          child: Container(
            width: 150,
            height: 150,
            color: Colors.blue,
          ),
        ),
      ),
    );
  }
}

class EffectWidget extends StatefulWidget {
  final Effect effect;
  final Widget child;

  const EffectWidget({
    super.key,
    required this.effect,
    required this.child,
  });

  @override
  State<EffectWidget> createState() => _EffectWidgetState();
}

class _EffectWidgetState extends State<EffectWidget> {
  late Effect effect = widget.effect;

  @override
  void didUpdateWidget(covariant EffectWidget oldWidget) {
    super.didUpdateWidget(oldWidget);

    // This equality will fail and update effect exactly once.
    if (oldWidget.effect != widget.effect) {
      debugPrint(
          'didUpdateWidget: ${effect.runtimeType} vs ${widget.effect.runtimeType}');

      effect = widget.effect;
    }
  }

  @override
  Widget build(BuildContext context) {
    debugPrint(
        'build: ${effect.runtimeType} vs ${widget.effect.runtimeType} | ${effect.runtimeType == widget.effect.runtimeType}');
    return effect.apply(context, widget.child);
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1727" alt="image" src="https://github.com/flutter/flutter/assets/7407478/8967ef58-7d68-4591-9fed-df4e8a9aa57d">

</details>

### Logs

<details open><summary>Logs</summary>

Github Gist URL:

https://gist.githubusercontent.com/SaadArdati/5b01a613e0a900ea59c4813eb994ce61/raw/608c43ae34804a9bf02c1080c9119e31d5a3bb15/log.txt

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-LB)
    • Flutter version 3.16.9 on channel stable at /Users/saadardati/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (5 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/saadardati/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/saadardati/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/saadardati/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Users/saadardati/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13763.5

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] VS Code (version 1.81.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 13 (API 33) (emulator)
    • Saad’s iPhone (mobile)      • 00008110-000555941151801E • ios            • iOS 17.3 21D50
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-01-31 08:01
Reproducible using the code sample provided above. 

This reproduced on all platforms I tested except the web

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3 23D56 darwin-arm64, locale en-GB)
    • Flutter version 3.16.9 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (6 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.3 21D50
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.3 21D50
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.19.0-14.0.pre.26, on macOS 14.3 23D56 darwin-arm64, locale en-GB)
    • Flutter version 3.19.0-14.0.pre.26 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 16e014e884 (2 hours ago), 2024-01-30 22:12:20 -0800
    • Engine revision 2d2d88068a
    • Dart version 3.4.0 (build 3.4.0-92.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.3 21D50
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.3 21D50
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by goderbauer** [comment] 2024-02-07 18:30
I wonder if this is a Dart bug? The stack trace is strange:

```
The following NoSuchMethodError was thrown building EffectWidget(state: _EffectWidgetState#e8691):
Class 'TranslateEffect' has no instance getter 'scale'.
Receiver: Instance of 'TranslateEffect'
Tried calling: scale

The relevant error-causing widget was: 
  EffectWidget EffectWidget:file:///Users/saadardati/IdeaProjects/covariant_bug/lib/main.dart:102:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      ScaleEffect.apply (package:covariant_bug/main.dart:41:30)
```

According to frame 1 there we are inside `ScaleEffect.apply` and are calling `scale` on an implicit `this`, which should be the `ScaleEffect` instance, but according to the error message the receiver was a `TranslateEffect` instance? How can that be?

I added a `print('inside ScaleEffect.apply: $runtimeType');` to `ScaleEffect.apply` and just before the crash it prints:

```
inside ScaleEffect.apply: TranslateEffect
```

From the code it seems impossible that inside of `ScaleEffect.apply` `this` could ever have a runtimeType of `TranslateEffect`?

Interestingly enough, the crash goes away when only slightly refactoring the code by replacing `late Effect effect = widget.effect;` with the equivalent

```dart
  late Effect effect;

  @override
  void initState() {
    super.initState();
    effect = widget.effect;
  }
```

Maybe someone from the dart team knows what could be happening here?

**Comment by mraleph** [comment] 2024-02-07 20:11
This is caused by `InitLateInstanceField` stub not updating guarded state of the field, so JIT compiler gets confused about the field contents later. The field contains `TranslateEffect`, but compiler thinks this field can only contain instances of `ScaleEffect`. Simple reproduction of this issue looks like this:

```dart
abstract class C {
  String str();
}

class A extends C {
  String str() => 'A!';
}

class B extends C {
  String str() => 'B!';
}

class N {
  final C x;
  late C v = x;

  N(this.x);

  @pragma('vm:never-inline')
  void foo() {
    if (v.str() != x.str()) {
      throw 'WAT: ${v} ${x}';
    }
  }
}

void main() {
  final ns = [N(A()), N(B())];

  // Init fields through late field initializer. This does not update guarded cid
  for (var n in ns) n.v;  

  // Update field normally. This will set guarded cid to be monomorphic (A)
  ns[0].v = ns[0].x;

  for (var i = 0; i < 10000; i++) {
    try {
      for (var n in ns) n.foo();
    } catch (_) {
      print('broken on iteration $i');
      rethrow;
    }
  }
}
```

I have asked @alexmarkov to look at fixing this.

**Comment by goderbauer** [comment] 2024-02-07 20:25
Thanks you for taking a look, @mraleph and @alexmarkov.

**Comment by mraleph** [comment] 2024-02-12 13:05
This has been fixed by https://github.com/dart-lang/sdk/commit/97164b3a017122a111151417b1184b2f31fb89f6 by @alexmarkov and has been rolled into Flutter.

**Closed by mraleph** 2024-02-12 13:05 UTC
Labels: framework, dependency: dart, a: error message, has reproducible steps, P2, team-framework, triaged-framework, found in release: 3.16, found in release: 3.19, dart-triaged
