### ISSUE TITLE
I updated the camera package to latest version i.e., 0.10.3. Now i  getting null object error.

### ISSUE THREAD

**Issue by faisalmushtaq007** [flutter/flutter#119813] opened 2023-02-02 12:15 UTC
I/flutter ( 4643): CameraException(error, Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference).
A small snippet of camera controller:

  Future startService(CameraDescription cameraDescription) async {
    _cameraDescription = cameraDescription;
    _cameraController = CameraController(
        _cameraDescription, ResolutionPreset.high,
        enableAudio: false);

    // sets the rotation of the image
    _cameraRotation = rotationIntToImageRotation(
      _cameraDescription.sensorOrientation,
    );

    // Next, initialize the controller. This returns a Future.
    return _cameraController.initialize(); // GETTING ERROR HERE!!!!
  }

**Comment by danagbemava-nc** [comment] 2023-02-02 13:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/109769.

**Closed by danagbemava-nc** 2023-02-02 13:28 UTC
Labels: in triage
