### ISSUE TITLE
[flutter web] debugger does not seem to stop/break at the breakpoint location but at some arbitrary location

### ISSUE THREAD

**Issue by vaibhav891** [flutter/flutter#101318] opened 2022-03-31 17:51 UTC
## Steps to Reproduce

- create a basic flutter app
- place a breakpoint anywhere in the _MyHomePageState's build method.
- run the application in chrome in debug mode
- notice the IDE (both android studio & VSCode) debugger stops at some other location

## additional notes
The debugger works fine when run on Android.

<img width="1440" alt="Screenshot 2022-03-31 at 11 17 53 PM" src="https://user-images.githubusercontent.com/62712068/161118215-a8038a26-46cf-49de-a2ca-2a96ff8379b7.png">

## Version info

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.8.1 at /Users/vaibhavsultania/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/vaibhavsultania/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Users/vaibhavsultania/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 100.0.4896.60

• No issues found!

**Comment by annagrin** [comment] 2022-04-05 01:25
@vaibhav891 I cannot repro this on the latest flutter master - Looks like it might be related to a Chrome update: https://github.com/flutter/flutter/issues/101139. Investigating...

**Comment by darshankawar** [comment] 2022-04-05 07:20
Tried the scenario using Android Studio on latest master, but unable to replicate as well.
Labeling for tracking.

**Comment by annagrin** [comment] 2022-04-05 22:55
duplicate of https://github.com/flutter/flutter/issues/101224

**Comment by darshankawar** [comment] 2022-04-06 04:50
Closing this as duplicate per above comment. Please follow-up in linked issue.

**Closed by darshankawar** 2022-04-06 04:50 UTC
Labels: dependency: dart, a: debugging, platform-web
