### ISSUE TITLE
My team members cannot run in debug mode when cloning my project

### ISSUE THREAD

**Issue by NanobyteRuata** [flutter/flutter#68798] opened 2020-10-22 16:53 UTC
I created a new flutter web project and uploaded it to gitlab.

When my friends cloned the project and tried to run using `flutter run -d chrome` 
or `flutter run` and choose another browsers, they get error like this
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/25664687/96903033-4d1b3280-14bb-11eb-8601-621054a4dc0f.png)

We tried using `flutter run -d chrome --release` and it runs the code but when there is error, it does not show in any of the terminal, developer tools console and even on the rendered UI. So, it's not ideal way to develop something. Also, it takes a lot more time to run in release mode than debug mode. So, it's also pretty unproductive.

We also tried `flutter run` then choosing Web Server. We paste the localhost url shown in our browser. 
It's a little better than release mode above but error messages are only shown in browser's developer tools console and they are not as reliable and understandable as error messages shown in terminal.

We also tried `flutter upgrade`. Few of my teammates solved the problem but after running a couple of times, it happens again to them.

Notice: Most of our laptops do not have good performance. Maybe I can run in debug mode because my laptop is better in performance than them. But anyway, I think we all should be able to run in debug mode.

**Comment by darshankawar** [comment] 2020-10-23 06:50
Closing this as duplicate of [49482](https://github.com/flutter/flutter/issues/49482)

**Closed by darshankawar** 2020-10-23 06:50 UTC
