### ISSUE TITLE
I'm Having a problem with getting Firebase to work on Android please help

### ISSUE THREAD

**Issue by TakeAchance365** [flutter/flutter#74376] opened 2021-01-21 04:14 UTC
Launching lib/main.dart on MAGNUS01111116048791 in debug mode...
 lib/main.dart
E/AndroidRuntime(22657): FATAL EXCEPTION: main
E/AndroidRuntime(22657): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(22657): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4673)
E/AndroidRuntime(22657): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4300)
E/AndroidRuntime(22657): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4242)
E/AndroidRuntime(22657): 	at android.app.ActivityThread.access$1300(ActivityThread.java:133)
E/AndroidRuntime(22657): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
E/AndroidRuntime(22657): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22657): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(22657): 	at android.app.ActivityThread.main(ActivityThread.java:4855)
E/AndroidRuntime(22657): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(22657): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(22657): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(22657): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(22657): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(22657): Caused by: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(22657): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
E/AndroidRuntime(22657): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(22657): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(22657): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4658)
E/AndroidRuntime(22657): 	... 12 more
E/AndroidRuntime(22924): FATAL EXCEPTION: main
E/AndroidRuntime(22924): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(22924): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4673)
E/AndroidRuntime(22924): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4300)
E/AndroidRuntime(22924): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4242)
E/AndroidRuntime(22924): 	at android.app.ActivityThread.access$1300(ActivityThread.java:133)
E/AndroidRuntime(22924): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
E/AndroidRuntime(22924): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22924): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(22924): 	at android.app.ActivityThread.main(ActivityThread.java:4855)
E/AndroidRuntime(22924): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(22924): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(22924): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(22924): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(22924): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(22924): Caused by: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(22924): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
E/AndroidRuntime(22924): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(22924): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(22924): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4658)
E/AndroidRuntime(22924): 	... 12 more
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(23134): FATAL EXCEPTION: main
E/AndroidRuntime(23134): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(23134): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4673)
E/AndroidRuntime(23134): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4300)
E/AndroidRuntime(23134): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4242)
E/AndroidRuntime(23134): 	at android.app.ActivityThread.access$1300(ActivityThread.java:133)
E/AndroidRuntime(23134): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
E/AndroidRuntime(23134): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23134): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(23134): 	at android.app.ActivityThread.main(ActivityThread.java:4855)
E/AndroidRuntime(23134): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23134): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(23134): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(23134): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(23134): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(23134): Caused by: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(23134): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
E/AndroidRuntime(23134): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(23134): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(23134): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4658)
E/AndroidRuntime(23134): 	... 12 more

**Comment by TakeAchance365** [comment] 2021-01-21 04:17
here is my pub spec.yaml file 
name: haleyvillehigh
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  webview_flutter: ^1.0.7
  font_awesome_flutter:
  webfeed:
  url_launcher: 
  http:
  cached_network_image:
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  app_info: ^0.0.1
  firebase_crashlytics: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/hhslogotransparent.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by TakeAchance365** [comment] 2021-01-21 04:20
I'm using all of these plugins

cupertino_icons: ^1.0.0
  webview_flutter: ^1.0.7
  font_awesome_flutter:
  webfeed:
  url_launcher: 
  http:
  cached_network_image:
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  app_info: ^0.0.1
  firebase_crashlytics: ^0.4.0+1

**Comment by TakeAchance365** [comment] 2021-01-21 04:22
and I also have been using a physical device that runs  Android version 4.1.2 

I hope this info helps

**Comment by pedromassangocode** [comment] 2021-01-21 07:22
Hi @TakeAchance365 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-21 07:22 UTC

**Comment by TakeAchance365** [comment] 2021-01-21 16:18
Ok thank you
