### ISSUE TITLE
App does not close on Android with back button

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#8334] opened 2017-02-22 19:00 UTC
Easily reproducible with a simple app:

```Dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(home: new Scaffold(body: new Text('App!'))));
}
```
Pressing back button once closes the main page but does not quit the app. We see a blank page. Pressing back a second time produces the following exception:

```
E/flutter ( 3151): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3151): Bad state: Future already completed
E/flutter ( 3151): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:40)
E/flutter ( 3151): #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:128)
E/flutter ( 3151): #2      Route.didPop (package:flutter/src/widgets/navigator.dart:92)
E/flutter ( 3151): #3      OverlayRoute.didPop (package:flutter/src/widgets/routes.dart:52)
E/flutter ( 3151): #4      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:184)
E/flutter ( 3151): #5      TransitionRoute&&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:329)
E/flutter ( 3151): #6      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:996)
E/flutter ( 3151): #7      NavigatorState.maybePop.<maybePop_async_body> (package:flutter/src/widgets/navigator.dart:970)
E/flutter ( 3151): <asynchronous suspension>
E/flutter ( 3151): #8      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart)
E/flutter ( 3151): #9      _WidgetsAppState.didPopRoute.<didPopRoute_async_body> (package:flutter/src/widgets/app.dart:158)
E/flutter ( 3151): <asynchronous suspension>
E/flutter ( 3151): #10     _WidgetsAppState.didPopRoute (package:flutter/src/widgets/app.dart)
E/flutter ( 3151): #11     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.handlePopRoute.<handlePopRoute_async_body> (package:flutter/src/widgets/binding.dart:182)
E/flutter ( 3151): <asynchronous suspension>
E/flutter ( 3151): #12     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.handlePopRoute (package:flutter/src/widgets/binding.dart)
E/flutter ( 3151): #13     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._handleNavigationMessage.<_handleNavigationMessage_async_body> (package:flutter/src/widgets/binding.dart:191)
E/flutter ( 3151): <asynchronous suspension>
E/flutter ( 3151): #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._handleNavigationMessage (package:flutter/src/widgets/binding.dart)
E/flutter ( 3151): #15     PlatformMessages.setJSONMessageHandler.<anonymous closure>.<<anonymous closure>_async_body> (package:flutter/src/services/platform_messages.dart:174)
E/flutter ( 3151): <asynchronous suspension>
E/flutter ( 3151): #16     PlatformMessages.setJSONMessageHandler.<anonymous closure> (package:flutter/src/services/platform_messages.dart)
E/flutter ( 3151): #17     PlatformMessages.setStringMessageHandler.<anonymous closure>.<<anonymous closure>_async_body> (package:flutter/src/services/platform_messages.dart:160)
E/flutter ( 3151): <asynchronous suspension>
E/flutter ( 3151): #18     PlatformMessages.setStringMessageHandler.<anonymous closure> (package:flutter/src/services/platform_messages.dart)
E/flutter ( 3151): #19     PlatformMessages.handlePlatformMessage.<handlePlatformMessage_async_body> (package:flutter/src/services/platform_messages.dart:77)
E/flutter ( 3151): <asynchronous suspension>
E/flutter ( 3151): #20     PlatformMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart)
E/flutter ( 3151): #21     _dispatchPlatformMessage (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:63)
```

**Comment by eseidelGoogle** [comment] 2017-02-22 19:10
This may have been fixed by https://github.com/flutter/flutter/commit/6d4333410bed25ad5d0280a62a1e6ec20631a8ec which likely hasn't been released internally yet.  FYI @tvolkert

**Comment by abarth** [comment] 2017-02-22 20:37
I believe this is a duplicate of #8307

**Closed by abarth** 2017-02-22 20:37 UTC
Labels: customer: leafy, regression

**Comment by ramtinq** [comment] 2020-04-06 10:57
This still persists!
