### ISSUE TITLE
[web][RTL] Text reverse on hover mouse

### ISSUE THREAD

**Issue by xOldeVx** [flutter/flutter#73258] opened 2021-01-04 08:34 UTC
The text is reverse on hover the mouse on FlatButton or on the Table body in case of PaginatedDataTable, DataTable etc..

https://user-images.githubusercontent.com/24361103/103515766-fe552600-4e77-11eb-9d90-03856fc30c62.mp4

<details>
  <summary>code</summary>

```
  dialog(BuildContext context, body) {
    return showDialog(
      context: context,
      builder: (context) => Directionality(
        textDirection: TextDirection.rtl,
        child: AlertDialog(
          title: Text('שגיאה!),
          content: Text(body),
          actions: <Widget>[
            FlatButton(
                child: Text("אישור"),
                onPressed: () {
                  Navigator.pop(context);
                }),
          ],
        ),
      ),
    );
  }
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.18363.1256], locale he-IL)
    • Flutter version 1.25.0-8.1.pre at C:\src\flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\myUser\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\myUser\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment] 2021-01-04 09:19
Hi @xOldeVx 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by xOldeVx** [comment] 2021-01-04 11:03
https://user-images.githubusercontent.com/24361103/103528749-28651300-4e8d-11eb-95c9-ce7d142dc1ba.mp4

<details>
  <summary>Here's a full code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'RTL 


bug',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final List<Person> persons = [
    Person(1, "Moshe", "levi"),
    Person(2, "Haim", "Cohen"),
    Person(3, "Liz", "Zilbershtein"),
  ];

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.rtl,
      child: Column(children: [
        RaisedButton(
            child: Text('dialog'),
            onPressed: () {
              dialog(context, "הכתב של הכתורת מתהפך");
            }),
        DataTable(
          columns: [
            DataColumn(label: Expanded(child: Text("id"))),
            DataColumn(label: Expanded(child: Text("שם"))),
            DataColumn(label: Expanded(child: Text("משפחה"))),
          ],
          rows: persons.map(
            (person) {
              return DataRow(
                cells: [
                  DataCell(Text(person.id.toString())),
                  DataCell(Text(person.firstName)),
                  DataCell(Text(person.lastName)),
                ],
              );
            },
          ).toList(),
        ),
      ]),
    );
  }

  dialog(BuildContext context, body) {
    return showDialog(
      context: context,
      builder: (context) => Directionality(
        textDirection: TextDirection.rtl,
        child: AlertDialog(
          title: Text('שגיאה!'),
          content: Text(body),
          actions: <Widget>[
            FlatButton(
                child: Text("אישור"),
                onPressed: () {
                  Navigator.pop(context);
                }),
          ],
        ),
      ),
    );
  }
}

class Person {
  int id;
  String firstName, lastName;
  Person(this.id, this.firstName, this.lastName);
}

```
</details>

**Comment by pedromassangocode** [comment] 2021-01-04 13:14
I was able to reproduce this on latest master and beta channel on Flutter Web app only.

![giff](https://user-images.githubusercontent.com/67424416/103538767-24d68980-4e97-11eb-8b03-926b9c8e8843.gif)


<details><summary>multiple flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.168, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.168 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 299e017e41 (23 hours ago), 2021-01-03 06:29:01 -0500
    • Engine revision 121b67fb85
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-8.1.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by xOldeVx** [comment] 2021-01-05 08:41
Please take care of this bug, especially since it did not exist until the new version

**Comment by pedromassangocode** [comment] 2021-01-05 10:36
Hi @xOldeVx 
In which Flutter version this issue was not happening?

**Comment by xOldeVx** [comment] 2021-01-05 11:01
In 1.20.2 it's work fine

**Comment by pedromassangocode** [comment] 2021-01-05 12:30
Can you please provide the `flutter doctor -v` of that same version?

**Comment by xOldeVx** [comment] 2021-01-05 13:44
I tried to downgrade to 1.20.2, but it did not work because a lot of last versions of dependencies in my project :|

**Comment by xOldeVx** [comment] 2021-01-06 08:42
It's really a big problem, can't publish my website because that

**Comment by mdebbar** [comment] 2021-04-22 21:51
Duplicate of https://github.com/flutter/flutter/issues/69396

**Closed by mdebbar** 2021-04-22 21:51 UTC
Labels: P4, a: internationalization, a: typography, engine, f: material design, found in release: 1.25, found in release: 1.26, framework, has reproducible steps, platform-web
