### ISSUE TITLE
Scaffold body not extended to bottom of screen on SystemChrome.setEnabledSystemUIOverlays([]);

### ISSUE THREAD

**Issue by premingiet** [flutter/flutter#51219] opened 2020-02-21 18:49 UTC
When making the app __full screen__ without any __systemUIoverlays__, when __extendBody: true__ option is set, still body only expands upto the bottom portion till the margin, where previously there was bottom system Ui overlay existed  before making the app full screen.

Here is the sample flutter code
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([]);
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.indigo,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      backgroundColor: Colors.red,
      extendBody: true,

      body: Container(
        color: Colors.amber,
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.display1,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

__Here is output of    ``` flutter doctor -v ```__
```dart
C:\Users\premi\Desktop\foxtailmega_pro>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (10 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\premi\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\premi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • E • G350RT058157000F • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

#### Here is the sample app screenshot when full screen without any bottom system overlay
![Screenshot_20200222-001359](https://user-images.githubusercontent.com/22827434/75062239-6fae1380-5508-11ea-9fc3-08ed2db53b3d.png)

#### Here is the sample app screenshot when full screen but i swipe bottom to show bottom system overlay
![Screenshot_20200222-001404](https://user-images.githubusercontent.com/22827434/75062287-87859780-5508-11ea-87b9-6b1515882060.png)

**Comment by TahaTesser** [comment] 2020-02-24 11:28
Duplicate of [#50511](https://github.com/flutter/flutter/issues/50511)

**Closed by TahaTesser** 2020-02-24 11:28 UTC

**Comment by cetozdemir** [comment] 2020-04-30 12:04
2 lines code can resolve this problem.

` return Scaffold(
      resizeToAvoidBottomPadding: false, //remove bottom padding
      resizeToAvoidBottomInset: true, // enable keyboard resizing
   );`
