### ISSUE TITLE
IconButton's InkWell effect covered by Container's decoration

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#31541] opened 2019-04-24 08:22 UTC
I have looked at  [issues/3782](https://github.com/flutter/flutter/issues/3782)

# Flutter version
```shell
flutter --version
Flutter 1.4.9-hotfix.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 88fa7ea403 (12 days ago) • 2019-04-11 14:01:46 -0700
Engine • revision 4737fc5cd8
Tools • Dart 2.2.1 (build 2.2.1-dev.4.0 None)
```
# Problem: Part of InkWell(of wheelchairs') been covered

![InkWellCoverdByDecoration](https://user-images.githubusercontent.com/6405390/56643460-41736380-66ac-11e9-8a12-7af1cf48a277.gif)

# Source code
```dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(MaterialApp(
    title: "Hello Title",
    theme: ThemeData(primarySwatch: Colors.blue),
    home: _createHomeWidget(),
  ));
}

Widget _createHomeWidget() {
  return Scaffold(
    backgroundColor: Colors.yellow,
    appBar: AppBar(
      title: Text('data'),
    ),
    body: ListView(
      children: <Widget>[
        IconButton(
          splashColor: Colors.blue,
          icon: Icon(Icons.access_alarm),
          onPressed: () {},
        ),
        Container(
          height: 150,
          color: Colors.red,
        ),
        Stack(
          children: <Widget>[
            IconButton(
              splashColor: Colors.blue,
              icon: Icon(Icons.ac_unit),
              onPressed: () {},
            ),
          ],
        ),

        _topicHorizontalListWidget(),
      ],
    ),
  );
}

Widget _topicHorizontalListWidget() {
  var itemCount = 5;
  return Container(
    height: 150,
    child: ListView.builder(
      scrollDirection: Axis.horizontal,
      itemCount: itemCount + 2,
      // itemExtent: 160,
      itemBuilder: (BuildContext context, int index) {
        if (index == 0 || index == itemCount + 1) {
          return Container(
            color: Colors.red,
            width: 20,
          );
        }
        return Container(
          margin: index == 1 ? null : EdgeInsets.only(left: 10),
          width: 150,
          decoration: index % 2 == 0 ? null : BoxDecoration(   // <-- this one
            borderRadius: BorderRadius.all(Radius.circular(10)),
            color: Colors.blue[100],
          ),
          child: Stack(
            children: <Widget>[
              Positioned(
                right: 5,
                bottom: 5,
                child: Container(
                  child: IconButton(
                    splashColor: Colors.red,    // <-- this one
                    icon: Icon(Icons.accessible),
                    onPressed: () {},
                  ),
                ),
              ),
            ],
          ),
        );
      },
    ),
  );
}
```

**Comment by jerryzhoujw** [comment] 2019-04-24 12:29
I have temporary fixed this by inner transparency Material as mentioned in the above issue discussing.


```dart
Widget _topicHorizontalListWidget() {
  var itemCount = 5;
  return Container(
    height: 150,
    child: ListView.builder(
      scrollDirection: Axis.horizontal,
      itemCount: itemCount + 2,
      // itemExtent: 160,
      itemBuilder: (BuildContext context, int index) {
        if (index == 0 || index == itemCount + 1) {
          return Container(
            color: Colors.red,
            width: 20,
          );
        }
        return Container(
          margin: index == 1 ? null : EdgeInsets.only(left: 10),
          width: 150,
          decoration: index % 2 == 0
              ? null
              : BoxDecoration(
                  borderRadius: BorderRadius.all(Radius.circular(10)),
                  color: Colors.blue[100],
                ),
          child: Material(
            type: MaterialType.transparency,   <----   this is the one
            child: Stack(
              children: <Widget>[
                Positioned(
                  right: 5,
                  bottom: 5,
                  child: Container(
                    child: IconButton(
                      splashColor: Colors.red,
                      icon: Icon(Icons.accessible),
                      onPressed: () {},
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    ),
  );
}
```

**Comment by shihaohong** [comment] 2019-04-24 22:45
Since ink splashes paint on top of Material widgets, you would have to create a Material widget that is larger than your current blue/transparent Containers, or like you said, positioning your icons away from the corners.

**Comment by jerryzhoujw** [comment] 2019-04-25 02:24
@shihaohong  I'm not sure how to do it with larger Material widget in this case. The case of if Inkwell effect may reach out to next list item.

**Comment by kwintAl** [comment] 2019-05-21 09:58
there is also an discussion on [StackOverflow](https://stackoverflow.com/questions/56231322/why-flutter-iconbutton-animation-shows-under-the-row)

A possible workaround is to set backgroundBlendMode to multiply.

here an example:
```
Container(
          decoration: BoxDecoration(
              color: Colors.green,
              backgroundBlendMode: BlendMode.multiply),
          child: ListTile(
            leading: IconButton(icon: Icon(Icons.play_arrow), onPressed: () {}),
            title: Text("issue title"),
            subtitle: Text("issue title"),
          ),
        ),
```

**Comment by TahaTesser** [comment] 2020-04-29 14:22
This issue still exist

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision e0c63cd35e (5 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.129
• No issues found!
```

</details>

**Comment by lxwcfz** [comment] 2020-05-20 10:23
I got this issue too, I don't even know how to create a effect like InkWell. upset day!

**Comment by lxwcfz** [comment] 2020-05-20 10:26
I got this issue too, I don't even know how to create an effect like InkWell. damn! for doubt, flutter???

**Comment by markusaksli-nc** [comment] 2020-07-14 08:52
#29040 needs to be closed once this is fixed.

**Comment by mrRedSun** [comment] 2021-01-07 16:59
The issue is more than a year old. Does anyone have a workaround for this? Blend mode doesn't help.

**Comment by TahaTesser** [comment] 2021-01-13 11:37
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(MaterialApp(
    title: "Hello Title",
    theme: ThemeData(primarySwatch: Colors.blue),
    home: _createHomeWidget(),
  ));
}

Widget _createHomeWidget() {
  return Scaffold(
    backgroundColor: Colors.yellow,
    appBar: AppBar(
      title: Text('data'),
    ),
    body: ListView(
      children: <Widget>[
        IconButton(
          splashColor: Colors.blue,
          icon: Icon(Icons.access_alarm),
          onPressed: () {},
        ),
        Container(
          height: 150,
          color: Colors.red,
        ),
        Stack(
          children: <Widget>[
            IconButton(
              splashColor: Colors.blue,
              icon: Icon(Icons.ac_unit),
              onPressed: () {},
            ),
          ],
        ),
        _topicHorizontalListWidget(),
      ],
    ),
  );
}

Widget _topicHorizontalListWidget() {
  var itemCount = 5;
  return Container(
    height: 150,
    child: ListView.builder(
      scrollDirection: Axis.horizontal,
      itemCount: itemCount + 2,
      // itemExtent: 160,
      itemBuilder: (BuildContext context, int index) {
        if (index == 0 || index == itemCount + 1) {
          return Container(
            color: Colors.red,
            width: 20,
          );
        }
        return Container(
          margin: index == 1 ? null : EdgeInsets.only(left: 10),
          width: 150,
          decoration: index % 2 == 0
              ? null
              : BoxDecoration(
                  // <-- this one
                  borderRadius: BorderRadius.all(Radius.circular(10)),
                  color: Colors.blue[100],
                ),
          child: Stack(
            children: <Widget>[
              Positioned(
                right: 5,
                bottom: 5,
                child: Container(
                  child: IconButton(
                    splashColor: Colors.red, // <-- this one
                    icon: Icon(Icons.accessible),
                    onPressed: () {},
                  ),
                ),
              ),
            ],
          ),
        );
      },
    ),
  );
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.313, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.313 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1cb0a24a46 (6 hours ago), 2021-01-12 21:39:27 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)                    • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by steeling** [comment] 2021-05-09 01:53
any update on this?

**Comment by banderberg** [comment] 2021-11-27 23:09
Bueller.. ?

**Comment by maheshmnj** [comment] 2022-12-22 01:44
Hi @jerryzhoujw, This is working as intended. [InkWell](https://api.flutter.dev/flutter/material/InkWell-class.html) draws a splash  on the nearest material widget
> The [InkWell](https://api.flutter.dev/flutter/material/InkWell-class.html) widget must have a [Material](https://api.flutter.dev/flutter/material/Material-class.html) widget as an ancestor. The [Material](https://api.flutter.dev/flutter/material/Material-class.html) widget is where the ink reactions are actually painted. This matches the [Material](https://api.flutter.dev/flutter/material/Material-class.html) Design premise wherein the Material is what is actually reacting to touches by spreading ink.

You will need to wrap the IconButton with Material widgets e.g Material

```dart
 Positioned(
   right: 5,
   bottom: 5,
   child: Material( // wrapped with material
     color: Colors.transparent,
     shape: const CircleBorder(),
     clipBehavior: Clip.hardEdge,
      child: IconButton(
       splashColor: Colors.red,
       icon: const Icon(Icons.accessible),
       onPressed: () {},
     ),
   ),
 ),
```

https://user-images.githubusercontent.com/31410839/209036120-d4971c9e-b432-4a88-be04-a55a8c94c50c.mov

Here's the complete code sample for the above output

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(MaterialApp(
    title: "Hello Title",
    theme: ThemeData(primarySwatch: Colors.blue),
    home: _createHomeWidget(),
  ));
}

Widget _createHomeWidget() {
  return Scaffold(
    backgroundColor: Colors.yellow,
    appBar: AppBar(
      title: const Text('data'),
    ),
    body: ListView(
      children: <Widget>[
        IconButton(
          splashColor: Colors.blue,
          icon: const Icon(Icons.access_alarm),
          onPressed: () {},
        ),
        Container(
          height: 150,
          color: Colors.red,
        ),
        Stack(
          children: <Widget>[
            IconButton(
              splashColor: Colors.blue,
              icon: const Icon(Icons.ac_unit),
              onPressed: () {},
            ),
          ],
        ),
        _topicHorizontalListWidget(),
      ],
    ),
  );
}

Widget _topicHorizontalListWidget() {
  var itemCount = 5;
  return SizedBox(
    height: 150,
    child: ListView.builder(
      scrollDirection: Axis.horizontal,
      itemCount: itemCount + 2,
      // itemExtent: 160,
      itemBuilder: (BuildContext context, int index) {
        if (index == 0 || index == itemCount + 1) {
          return Container(
            color: Colors.red,
            width: 20,
          );
        }
        return Container(
          margin: index == 1 ? null : const EdgeInsets.only(left: 10),
          width: 150,
          decoration: index % 2 == 0
              ? null
              : BoxDecoration(
                  // <-- this one
                  borderRadius: const BorderRadius.all(Radius.circular(10)),
                  color: Colors.blue[100],
                ),
          child: Stack(
            children: <Widget>[
              Positioned(
                right: 5,
                bottom: 5,
                child: Material(
                               color: Colors.transparent,
                shape: const CircleBorder(),
                clipBehavior: Clip.hardEdge,
                  child: IconButton(
                    splashColor: Colors.red, // <-- this one
                    icon: const Icon(Icons.accessible),
                    onPressed: () {},
                  ),
                ),
              ),
            ],
          ),
        );
      },
    ),
  );
}
```
</details> 

Closing as this is working as intended. Incase anyone disagrees feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-22 01:44 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 1.22, found in release: 1.26
