### ISSUE TITLE
[tools] coverage:ignore-line doesn't always work

### ISSUE THREAD

**Issue by longtimedeveloper** [flutter/flutter#95791] opened 2021-12-24 23:05 UTC
# UPDATED REPO 12/27/2021

## Steps to Reproduce

1. Create a default Flutter app
2. Add a `coverage.dart` file next to `main.dart`
3. Add the following code to `coverage.dart`
4. Under the `\test` folder add a `coverage_test.dart` file.
5. Add the test code to the `coverage_test.dart` file. 
6. In the Visual Studio Code terminal window execute this command:
  `flutter test --coverage`
7. Open the `\coverage\lcov.info` file.

## Working Sample

```dart
class Coverage {
  bool test(Test test) {
    switch (test) {
      case Test.fail:
        return false;
      case Test.pass:
        return true;
      default:
        throw Exception('boom');  // coverage:ignore-line
    }
  }
}

enum Test {
  fail,
  pass,
  extra,
}
```

`coverage_test.dart`

```dart
void main() {
  group('Code Coverage Test', () {
    test('description', () {
      // arrange
      final sut = Coverage();

      // act

      // assert
      expect(sut.test(Test.fail), false);
      expect(sut.test(Test.pass), true);
    });
  });
}

```

## Failing sample 

```dart
class Coverage {
  String validate(String value, RegularExpressionPatternType regularExpressionPatternType) {
    String pattern;
    String brokenRuleMessage;

    switch (regularExpressionPatternType) {
      case RegularExpressionPatternType.custom:
        pattern = 'customRegularExpressionPattern';
        brokenRuleMessage = 'regularExpressionDidNotMatchTheRequiredPatternFormat';
        break;
      case RegularExpressionPatternType.email:
        pattern = 'RegExPatternConstants.email';
        brokenRuleMessage = 'regularExpressionDidNotMatchTheRequiredEmailPatternFormat';
        break;
      case RegularExpressionPatternType.ipAddress:
        pattern = 'RegExPatternConstants.ipAddress';
        brokenRuleMessage = 'regularExpressionDidNotMatchTheRequiredIPAddressPatternFormat';
        break;
      case RegularExpressionPatternType.ssn:
        pattern = 'RegExPatternConstants.ssn';
        brokenRuleMessage = 'regularExpressionDidNotMatchTheRequiredSSNPatternFormat';
        break;
      case RegularExpressionPatternType.urlHttpHttpsFtp:
        pattern = 'RegExPatternConstants.urlHttpHttpsFtp';
        brokenRuleMessage = 'regularExpressionDidNotMatchTheRequiredURLPatternFormat';
        break;
      case RegularExpressionPatternType.usPhoneNumber:
        pattern = 'RegExPatternConstants.usPhoneNumber';
        brokenRuleMessage = 'regularExpressionDidNotMatchTheRequiredUSPhoneNumberPatternFormat';
        break;
      case RegularExpressionPatternType.usZipCode:
        pattern = 'RegExPatternConstants.usZipCode';
        brokenRuleMessage = 'regularExpressionDidNotMatchTheRequiredZipCodePatternFormat';
        break;
      default:
        throw Exception('enumValueNotProgrammedFormat'); // coverage:ignore-line
    }

    return pattern + brokenRuleMessage;
  }
}

enum RegularExpressionPatternType {
  custom,
  email,
  ipAddress,
  ssn,
  urlHttpHttpsFtp,
  usPhoneNumber,
  usZipCode,
}

```

`coverage_test.dart`

```dart
import 'package:flutter_test/flutter_test.dart';
//TODO import the coverage.dart file

void main() {
  group('Code Coverage Test', () {
    test('description', () {
      // arrange
      final sut = Coverage();

      // act
      var result = sut.validate('', RegularExpressionPatternType.custom);
      result = sut.validate('', RegularExpressionPatternType.email);
      result = sut.validate('', RegularExpressionPatternType.ipAddress);
      result = sut.validate('', RegularExpressionPatternType.ssn);
      result = sut.validate('', RegularExpressionPatternType.urlHttpHttpsFtp);
      result = sut.validate('', RegularExpressionPatternType.usPhoneNumber);
      result = sut.validate('', RegularExpressionPatternType.usZipCode);

      // assert
      expect(result.isNotEmpty, true);
    });
  });
}

```

**Expected results:** 
Line 10 in `lcov.info`  shows that the DA:36 line would be 1, indicating the line passes code coverage, honoring `// coverage:ignore-line`

**Actual results:**
Line 10 in `lcov.info`  shows that DA:36 was 0, indicating the line does not have code coverage.

Notice line 36 in the `coverage.dart` file has the required: `// coverage:ignore-line`

`coverage:ignore-line` is being ignored by the `flutter test --coverage` command.

![2021-12-27_7-47-59](https://user-images.githubusercontent.com/79998776/147473207-825a0a10-767e-4e4a-bb8d-d10a292023f1.jpg)

**Thank you for looking into this, greatly appreciate it.**

<details>
<summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1415], locale en-US)
    • Flutter version 2.8.1 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at C:\Users\kdawg\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\kdawg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2021-12-27 09:13
Hi @longtimedeveloper, can you check if this comment in this post works for you? https://github.com/dart-lang/coverage/issues/330#issuecomment-796551849

**Comment by longtimedeveloper** [comment] 2021-12-27 11:58
@danagbemava-nc thank you very much!

Can they update the Flutter Test docs to indicate this correct usage?  [Flutter Testing Docs](https://docs.flutter.dev/testing)

For those coming here with the same issue, the `// coverage:ignore-line` **must** be placed at the end of the line to be ignored by the code coverage too.

**Correct Usage**
  `throw Exception('boom'); // coverage:ignore-line`

**Incorrect Usage**
```
  // coverage:ignore-line
  throw Exception('boom');
```
Thank you again, 

Karl

**Comment by longtimedeveloper** [comment] 2021-12-27 12:44
@danagbemava-nc 

Your recommendation to place the `// coverage:ignore-line` at the end of the line of code worked in my original sample repo.

However, use cases in my real app, still showed incorrect code coverage results.

I've updated the original code with code the code coverage tool misses.

Can you please investigate?

Thank you!!

Karl

**Comment by longtimedeveloper** [comment] 2021-12-27 13:40
@danagbemava-nc 

In my real-world application, I was able to work around this issue by removing the `default` option in my switch blocks.  Then rely on the compiler to show an error at edit-time if the enum has a value added to it.

I also had an `if/if else/else` block of code that `// coverage:ignore-line` didn't work for.  To correct the issue, I converted the `if/if else/else` to use `switch` instead and not include a default use case.

**What both of these use cases had in common was an `enum` value being tested.**

I hope this helps,

Karl

**Comment by danagbemava-nc** [comment] 2021-12-27 13:47
Related to https://github.com/flutter/flutter/issues/83425.

Reproducible using samples in original post.

On my end, the line of code with the `// coverage:ignore-line` is `line 44` for the failing sample whereas for the working sample it is `line 9`.

Notice that for the `lcov_working.txt` file, `line 9` is missing from the file. but for the failing sample, `line 44` is visible. 

[lcov_failing.txt](https://github.com/flutter/flutter/files/7780387/lcov_failing.txt)
[lcov_working.txt](https://github.com/flutter/flutter/files/7780389/lcov_working.txt)

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (11 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.199, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.199 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a014515c1 (11 hours ago), 2021-12-26 22:09:16 -0500
    • Engine revision 8816e59dd4
    • Dart version 2.16.0 (build 2.16.0-135.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by longtimedeveloper** [comment] 2021-12-27 13:58
@danagbemava-nc the discrepancy with line numbers may be that I removed the original repo from my code.  

I'm glad you were able to find another use case that has similar results.

Thank you for correcting the title, and showing a passing and failing example.  I'll be sure for any future issues to write them up this way.

Thank you!

**Comment by longtimedeveloper** [comment] 2021-12-30 21:23
@danagbemava-nc can you have a look at this related issue please https://github.com/dart-lang/dart_style/issues/1088

I don't know if this team can handle that use case, or is in the formatter team's hands.

Thank you!

**Comment by liamappelbe** [comment] 2022-01-11 22:48
Thanks for the detailed repro steps. I followed the updated steps, and I can't repro this using either Flutter's test coverage or vanilla package:coverage. Maybe something important was removed when the repro steps were simplified?

My coverage.dart looks like:
```Dart
class Coverage {
  bool test(Test test) {
    switch (test) {
      case Test.fail:
        return false;
      case Test.pass:
        return true;
      default:
        throw Exception('boom');  // coverage:ignore-line
    }
  }
}

enum Test {
  fail,
  pass,
  extra,
}
```

When I run this with `flutter test --coverage`, the throw line (line 9) is ignored. The relevent part of the lcov.info file is:
```
SF:lib/coverage.dart
DA:2,1
DA:4,1
DA:6,1
DA:14,1
LF:4
LH:4
end_of_record
```

When I remove the ignore comment, I get a `DA:9,0` line:
```
SF:lib/coverage.dart
DA:2,1
DA:4,1
DA:6,1
DA:9,0
DA:14,1
LF:5
LH:4
end_of_record
```

**Comment by longtimedeveloper** [comment] 2022-01-12 02:59
@liamappelbe yes, you copied the above **Working Sample**, we know this works.  See the above **Failing Sample.**

**Comment by liamappelbe** [comment] 2022-01-12 22:48
Oh, yep, my mistake. I can repro now.

A quick workaround I found is that ignore-start/end still work in this case, which at least saves you from restructuring your code:
```Dart
      default:
        // coverage:ignore-start
        throw Exception('enumValueNotProgrammedFormat');
        // coverage:ignore-end
```

**Comment by longtimedeveloper** [comment] 2022-01-12 22:57
@liamappelbe that is what I'm doing for now.  Hoping this can get corrected so developers can use the single-line syntax.  This issue may also bring other edge cases to light for correction.

**Comment by liamappelbe** [comment] 2022-01-12 23:48
Found the problem. It's related to a bug that was already fixed: https://github.com/dart-lang/coverage/pull/347

The fix is in coverage version 1.1.0, which isn't published yet.

**Closed by liamappelbe** 2022-01-12 23:48 UTC
Labels: a: tests, dependency: dart, has reproducible steps, found in release: 2.8, found in release: 2.9

**Comment by longtimedeveloper** [comment] 2022-01-13 00:02
@liamappelbe did you verify the above **Failing sample** now works with coverage 1.1.0 before closing this?

**Comment by liamappelbe** [comment] 2022-01-13 00:13
Yep, it works with 1.1.0

**Comment by longtimedeveloper** [comment] 2022-01-13 01:23
@liamappelbe forgot to ask, I'm when do you think this fix will be in the stable branch?  Thank you again for the research and for resolving this issue.

**Comment by liamappelbe** [comment] 2022-01-13 18:36
Not sure. I don't know of any blockers to publishing it, but the other main contributor to the package is on vacation this week. I'll talk to him about it next week.

**Comment by longtimedeveloper** [comment] 2022-01-13 20:14
@liamappelbe thank you, enjoy your weekend!

**Comment by liamappelbe** [comment] 2022-01-18 21:09
1.1.0 is published, so if you update to this version the bug should be fixed: https://pub.dev/packages/coverage/versions/1.1.0
