### ISSUE TITLE
The primary color of the ThemeData is not equal to that of the color scheme value when using Brightness.dark and Material 3

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#124319] opened 2023-04-06 14:59 UTC
In dark mode, the `primaryColor` of the theme is not equal to that of the color scheme.

## Steps to Reproduce

1. Run the code sample
2. Compare the color values in the output
3. The values are different for the dark mode case

**Expected results:** The colors are the same for both light and dark mode

**Actual results:** The colors are different when in dark mode

```
light theme: theme.primaryColor: Color(0xff0061a4) colorScheme.primary Color(0xff0061a4)
dark theme: theme.primaryColor: Color(0xff1a1c1e) colorScheme.primary Color(0xff9ecaff)
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  final lightTheme = getTheme(brightness: Brightness.light);
  final darkTheme = getTheme(brightness: Brightness.dark);
  
  print('light theme: theme.primaryColor: ${lightTheme.primaryColor} colorScheme.primary ${lightTheme.colorScheme.primary}');
  print('dark theme: theme.primaryColor: ${darkTheme.primaryColor} colorScheme.primary ${darkTheme.colorScheme.primary}');
}

ThemeData getTheme({required Brightness brightness}) {
  final ColorScheme colorScheme =
      ColorScheme.fromSeed(seedColor: Colors.blue, brightness: brightness);
  
  return ThemeData(
    useMaterial3: true,
    colorScheme: colorScheme,
  );
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-x64, locale
    en-BE)
    • Flutter version 3.7.10 on channel stable at
      /Users/navaronbracke/Documents/flutter
    • Upstream repository git@github.com:navaronbracke/flutter.git
    • FLUTTER_GIT_URL = git@github.com:navaronbracke/flutter.git
    • Framework revision 4b12645012 (3 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • ANDROID_SDK_ROOT = 
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-04-07 08:37
Thanks for filing the issue, @navaronbracke 

This issue is reproducible on the latest `stable` and `master` channels. May be related or affect to https://github.com/flutter/flutter/issues/118146. 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (2 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.9.0-22.0.pre.84, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.9.0-22.0.pre.84 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aa6a0a9dea (2 hours ago), 2023-04-07 06:52:30 +0200
    • Engine revision d1dad6acbe
    • Dart version 3.0.0 (build 3.0.0-417.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 111.0.5563.146

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment] 2023-04-12 07:15
Hi @navaronbracke 

This seems to be intentional as `ThemeData.primary` isn't part of the `ColorScheme`.

 `ThemeData.primary`  is actually using `ColorScheme.surface` for the dark theme.

https://github.com/flutter/flutter/blob/0a140c68f88b7cb3c83d721cfa0f64466fa10923/packages/flutter/lib/src/material/theme_data.dart#L471-L476

You can confirm this by printing `ColorScheme.surface`. 
```dart
  print('light theme: theme.primaryColor: ${lightTheme.primaryColor} colorScheme.surface ${lightTheme.colorScheme.surface} colorScheme.primary ${lightTheme.colorScheme.primary}');
  print('dark theme: theme.primaryColor: ${darkTheme.primaryColor} colorScheme.surface ${darkTheme.colorScheme.surface} colorScheme.primary ${darkTheme.colorScheme.primary}');
```

```console
flutter: light theme: theme.primaryColor: Color(0xff343dff) colorScheme.surface Color(0xfffffbff) colorScheme.primary Color(0xff343dff)
flutter: dark theme: theme.primaryColor: Color(0xff1b1b1f) colorScheme.surface Color(0xff1b1b1f) colorScheme.primary Color(0xffbec2ff)
```



This was added in https://github.com/flutter/flutter/pull/93463 and you can find a reason for this [here](https://github.com/flutter/flutter/pull/93463#discussion_r755466861). 

Given `ThemeData.primary` is supposed to be deprecated under https://github.com/flutter/flutter/issues/91772 and the behavior is intentional, I feel safe to close this issue.

**Closed by TahaTesser** 2023-04-12 07:15 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.7, found in release: 3.9
