### ISSUE TITLE
Linux flutter_gallery__image_cache_memory is 1.41% flaky

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#86685] opened 2021-07-19 23:35 UTC
The post-submit test builder `Linux flutter_gallery__image_cache_memory` had a flaky ratio 1.41% for the past 15 days, which is the flakiest test below 2% threshold.

One recent flaky example for a commit:
Commit: 72ae6e236ea192a686b1c015f2a6b242682888cd
Failed build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_gallery__image_cache_memory/2033/overview
Succeeded build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_gallery__image_cache_memory/2034/overview

Please follow https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness). 

(Creating this issue as part of the gardener rotation.)

**Comment by zanderso** [comment] 2021-07-20 04:09
Duplicate of https://github.com/flutter/flutter/issues/86643

**Closed by zanderso** 2021-07-20 04:09 UTC
Labels: P2, engine, severe: flake, team: flakes
