### ISSUE TITLE
Linux web_tool_tests flakes on `Unexpected character`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97330] opened 2022-01-26 22:57 UTC
part of [#97036](https://github.com/flutter/flutter/issues/97036))
These data is based on Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

2 flakes on `Linux web_tool_tests`: 
[4463](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/4463/overview) (happened on 12/21/2021)
[4272](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/4272/overview) (happened on 12/01/2021)

```
05:09 +10 ~1 -1: test/web.shard/web_run_test.dart: flutter run works on web devices with a unary main function [E]                                                                                     
  Exception: Exception: Received app.stop event while waiting for app.started event
  
  [+1750 ms] FormatException: Unexpected character (at character 1)
             <html>
             ^
  
             #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
             #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
             #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
             #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
             #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
             #5      JsonCodec.decode (dart:convert/json.dart:216:41)
             #6      jsonDecode (dart:convert/json.dart:155:10)
             #7      ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:44:10)
             <asynchronous suspension>
             #8      ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:57:25)
             <asynchronous suspension>
             #9      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:401:9)
             <asynchronous suspension>
             #10     ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
             <asynchronous suspension>
             #11     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
             <asynchronous suspension>
             #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
             <asynchronous suspension>
  
  Unable to connect to Chrome debug port: 37021
   FormatException: Unexpected character (at character 1)
  <html>
  ^
  
  
  #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
  #1      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:406:9)
  <asynchronous suspension>
  #2      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
  <asynchronous suspension>
  #3      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
  <asynchronous suspension>
  #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
  <asynchronous suspension>
```

**Comment by keyonghan** [comment] 2022-01-26 23:10
@zanderso Here is another one for Linux web_tool_tests. Please help take a look and feel free to close if the issue has been addressed or is no longer feasible to fix. Thanks!

**Comment by zanderso** [comment] 2022-01-31 05:29
This is a duplicate of https://github.com/flutter/flutter/issues/94886

**Closed by zanderso** 2022-01-31 05:29 UTC
Labels: tool, team: flakes
