### ISSUE TITLE
when i use camera in ios phone, i take video and turn phone to left, but return a 90° file

### ISSUE THREAD

**Issue by cizhaoyang** [flutter/flutter#62374] opened 2020-07-28 03:15 UTC
When I use the camera to shoot video, the camera shoots horizontally, and the returned data is still 90 degrees in ios, how can i get a 180° data

**Comment by pedromassangocode** [comment] 2020-07-28 10:30
Hi @cizhaoyang  
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by cizhaoyang** [comment] 2020-07-30 06:21
import 'dart:math';
import 'dart:io';
import 'dart:ui';
import 'dart:async';
import 'package:permission_handler/permission_handler.dart';
import 'package:path_provider/path_provider.dart';
import 'package:photo_manager/photo_manager.dart';
import 'package:tglpl_proj/data/publish/photo_data.dart';
import 'package:video_player/video_player.dart';
import 'package:camera/camera.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'package:tglpl_proj/utils/ui_header.dart';
import 'package:tglpl_proj/components/alert_dialog.dart';

class CustomCamera extends StatefulWidget {
  CustomCamera({
    Key key,
    this.onSure
  }):super(key: key);

  final ValueSetter<PhotoData> onSure;

  @override
  _CustomCameraState createState() => _CustomCameraState();
}

class _CustomCameraState extends State<CustomCamera> with TickerProviderStateMixin  {
  final _screen = ScreenUtil.getInstance();
  double percentage = 0.0;
  AnimationController percentageAnimationController;
  CameraController controller;
  File imageFile;
  File videoFile;
  String videoPath;
  List<CameraDescription> cameras;
  VideoPlayerController videoController;
  VoidCallback videoPlayerListener;
  bool isHide = false;
  Timer timer;
  double buttonWidth = 0;

  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();

  _camera() async{
    cameras = await availableCameras();
    if(cameras != null){
      controller = CameraController(cameras[0], ResolutionPreset.high);
      controller.initialize().then((_) {
        if (!mounted) {
          return;
        }
        setState(() {});
      });
    }
  }

  Future<void> requestPermission(Permission permission, BuildContext context) async {
    final status = await permission.request();
    if (status.isPermanentlyDenied) {
      //禁止后不再提示
      alertView(context);
    } else if (status.isDenied) {
      //禁止
      if (Platform.isIOS) {
        alertView(context);
      }
    } else if (status.isGranted) {
      //允许
    } else if (status.isRestricted) {
      alertView(context);
    }
  }

  alertView(BuildContext context) {
    LplAlertDialog(context).show(
        sTitle: '请在设置中允许"Odyssey"访问您的麦克风',
        sLeftText: '取消',
        sRightText: '前往设置',
        onRightPress: () {
          Navigator.pop(context);
          openAppSettings();
        },
        onLeftPress: () {
          Navigator.pop(context);
        });
  }

  @override
  void initState() {
    super.initState();
    requestPermission(Permission.microphone, this.context);
    _camera();
    percentageAnimationController = new AnimationController(
        vsync: this, duration: new Duration(milliseconds: 30000))
      ..addListener(() {
        setState(() {
          percentage =  percentageAnimationController.value * pi * 2;
        });
      });
    timer = Timer.periodic(Duration(seconds: 4), (time) {
      setState(() {
        isHide = true;
      });
      timer?.cancel();
    });
    buttonWidth =  _screen.getAdapterSize(200);
  }

  @override
  void dispose() {
    super.dispose();
    percentageAnimationController.dispose();
    videoController?.dispose();
    controller.dispose();
    timer ?.cancel();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: imageFile != null || videoController != null ? showContainWidget() : Container(
        child: Stack(
          children: <Widget>[
            cameraPreviewWidget(),
            Positioned(
              top: _screen.statusBarHeight +10,
              left: 15,
              child: IconButton(
                icon: Icon(Icons.close),
                color: Colors.white,
                iconSize: 30,
                onPressed: () => Navigator.pop(context),
              ),
            ),
            Positioned(
                bottom: _screen.getAdapterSize(450),
                child: isHide ? Container() : Container(
                  width: _screen.screenWidth,
                  alignment: Alignment.center,
                  child: Text('轻触拍照，按住摄像', style: TextStyle(color: Colors.white),),
                )
            ),
            Positioned(
              bottom: _screen.getAdapterSize(180),
              left: (_screen.screenWidth - buttonWidth) / 2,
              child: cameraButton(),
            )
          ],
        ),
      ),
    );
  }

  Widget showContainWidget() {
    return Stack(
      children: <Widget>[
        Container(
          width: double.infinity,
          height: double.infinity,
          child: videoController == null && imageFile == null
              ? Container
              : videoController == null
              ? Image.file(imageFile,fit: BoxFit.cover,) : videoPlayerWidget(),
        ),
        Positioned(
          bottom: 20,
          left: 0,
          right: 0,
          height: 40,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: <Widget>[
              buttonView('取消', () {
                setState(() {
                  imageFile = null;
                  videoFile = null;
                  videoController = null;
                });
              }),
              buttonView('完成', () async{
                PhotoData data = PhotoData();
                if (imageFile != null){
                  data.type = AssetType.image;
                  data.file = imageFile;
                  data.originBytes = imageFile.readAsBytesSync();
                  data.width = _screen.screenWidth;
                  data.height = _screen.screenHeight;
                  widget.onSure(data);
                  ImageGallerySaver.saveFile(imageFile.path);
                  Navigator.of(context).pop();
                } else if (videoFile != null) {
                  data.type = AssetType.video;
                  data.file = videoFile;
                  data.width = _screen.screenWidth;
                  data.height = _screen.screenHeight;
                  data.originBytes = videoFile.readAsBytesSync();
                  widget.onSure(data);
                  ImageGallerySaver.saveFile(videoFile.path);
                  Navigator.of(context).pop();
                }
              }),
            ],
          ),
        )
      ],
    );
  }

  Widget buttonView(String title, GestureTapCallback onTap) {
    return InkWell(
      onTap: onTap,
      child: Container(
        alignment: Alignment.center,
        width: _screen.getAdapterSize(180),
        height: _screen.getAdapterSize(76),
        decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(5),
            color: Colors.green
        ),
        child: Text(title, style: TextStyle(fontSize: 14, color: Colors.white),),
      ),
    );
  }

  Widget videoPlayerWidget() {
    return Container(
      child: Center(
        child: AspectRatio(
            aspectRatio:
            videoController.value.size != null
                ? videoController.value.aspectRatio
                : 1.0,
            child: VideoPlayer(videoController)),
      ),
    );
  }

  Widget cameraPreviewWidget() {
    if (controller == null || !controller.value.isInitialized) {
      return Container();
    }

    final size = MediaQuery.of(context).size;
    final deviceRatio = size.width / size.height;
    return Transform.scale(
      scale: controller.value.aspectRatio / deviceRatio,
      child: Center(
        child: CameraPreview(controller),
      ),
    );
  }

  Widget cameraButton() {
    return Container(
        height: buttonWidth,
        width: buttonWidth,
        child: AnimatedBuilder(animation: percentageAnimationController, builder: (context, child) {
          return new CustomPaint(
            foregroundPainter: new MyPainter(
                lineColor: Colors.white,
                completeColor: Colors.greenAccent,
                startPercent: percentage,
                width: 4.0),
            child: new Padding(
              padding: const EdgeInsets.all(8.0),
              child: GestureDetector(
                onLongPressStart: (data) {
                  percentageAnimationController.forward(from: 0);
                  //开始录制视频
                  _onStartRecord();
                },
                onLongPressEnd: (data) {
                  percentageAnimationController.stop();
                  _onStopRecord();
                },
                onTap: () {
                  onTakePicture();
                },
                child: Container(
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(192/2),
                    color: Colors.white,
                  ),
                ),
              ),
            ),
          );
        })
    );
  }

  _onStartRecord() async{
    startVideoRecording().then((file) {
      if (mounted) setState(() {});
    });
  }

  _onStopRecord() {
    stopVideoRecording().then((_) async{
      if (mounted) {
        setState(() {
          videoFile = File(videoPath);
          percentage = 0;
        });
      }
    });
  }

  Future<void> _startVideoPlayer() async {
    final VideoPlayerController vcontroller = VideoPlayerController.file(File(videoPath));
    videoPlayerListener = () {
      if (videoController != null && videoController.value.size != null) {
        if (mounted) setState(() {});
        videoController.removeListener(videoPlayerListener);
      }
    };
    vcontroller.addListener(videoPlayerListener);
    await vcontroller.setLooping(true);
    await vcontroller.initialize();
    await videoController?.dispose();
    if (mounted) {
      setState(() {
        videoController = vcontroller;
      });
    }
    await vcontroller.play();
  }

  onTakePicture() {
    takePicture().then((File file) {
      setState(() {
        imageFile = file;
      });
    });
  }

  //拍照片
  Future<File> takePicture() async {
    if (!controller.value.isInitialized) {
      return null;
    }
    final Directory extDir = await getApplicationDocumentsDirectory();
    final String dirPath = '${extDir.path}/pictures/flutter_lpl';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/${timestamp()}.jpg';
    File file = File(filePath);
    if (controller.value.isTakingPicture) {
      // A capture is already pending, do nothing.
      return null;
    }
    try {
      await controller.takePicture(filePath);
    } on CameraException catch (_) {
      return null;
    }
    return file;
  }

  //开始录制视频
  Future<File> startVideoRecording() async {
    if (!controller.value.isInitialized) {
      return null;
    }
    final Directory extDir = await getApplicationDocumentsDirectory();
    final String dirPath = '${extDir.path}/Movies/flutter_lpl';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/${timestamp()}.mp4';
    File file;
    if (controller.value.isRecordingVideo) {
      // A recording is already started, do nothing.
      return null;
    }

    try {
      videoPath = filePath;
      file = File(filePath);
      controller.startVideoRecording(filePath);
    } on CameraException catch (_) {
      return null;
    }
    return file;
  }
  //结束录制
  Future<void> stopVideoRecording() async {
    if (!controller.value.isRecordingVideo) {
      return null;
    }
    try {
      await controller.stopVideoRecording();
    } on CameraException catch (_) {
      return null;
    }
    await _startVideoPlayer();
  }
}

//自定义拍摄按钮
class MyPainter extends CustomPainter {
  Color lineColor;
  Color completeColor;
  double startPercent; //圆弧转动时 开始的位置
  double width;

  MyPainter({this.lineColor,
    this.completeColor,
    this.startPercent,
    this.width,
  });

  @override
  void paint(Canvas canvas, Size size) {
    Paint line = Paint()
      ..color = lineColor
      ..strokeCap = StrokeCap.round
      ..style = PaintingStyle.stroke
      ..strokeWidth = width;

    Paint complete = Paint()
      ..color = completeColor
      ..strokeCap = StrokeCap.round
      ..style = PaintingStyle.stroke
      ..strokeWidth = width;

    Offset center = Offset(size.width / 2, size.height / 2); //  坐标中心
    double radius = min(size.width / 2, size.height / 2); //  半径
    canvas.drawCircle(
      //  画圆方法
        center,
        radius,
        line);

    double arcAngle = startPercent;

    //画转动的圆弧
    canvas.drawArc(Rect.fromCircle(center: center, radius: radius),
        -pi/2, arcAngle, false, complete);
  }

  @override
  bool shouldRepaint(MyPainter oldDelegate) {
    return startPercent != oldDelegate.startPercent;
  }
}

**Comment by cizhaoyang** [comment] 2020-07-30 06:29
Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.959], locale zh-CN)
    • Flutter version 1.17.4 at C:\flutter_sdk\flutter
    • Framework revision 1ad9baa8b9 (6 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


this is my flutter doctor

**Comment by pedromassangocode** [comment] 2020-07-30 09:17
Hi @cizhaoyang  
I need a minimal code that reproduces the issue. Your code as so many personal code and I'm unable to reproduce the issue with it. Please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample. 
Thank you

**Comment by TahaTesser** [comment] 2020-08-25 13:25
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-25 13:25 UTC
Labels: in triage
