### ISSUE TITLE
Flutter 3.10.0 behavior has changed for a maximally large RenderView

### ISSUE THREAD

**Issue by xxzj990** [flutter/flutter#126976] opened 2023-05-17 01:09 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run sample code 

| Expected results | Actual results |
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/5134154/c46f4d24-09c7-48bd-914e-059911d26ef6" alt="3.7.12" width="300" /> | <img src="https://github.com/flutter/flutter/assets/5134154/5676c62d-3b85-4719-a945-9f1820fc9e6b" alt="3.10.0" width="300" /> |

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter 3.10.0'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static Future<ByteData?> widgetToImage(BuildContext context, Widget widget,
      {Alignment alignment = Alignment.center,
      Size size = const Size(double.maxFinite, double.maxFinite),
      double devicePixelRatio = 1.0,
      double pixelRatio = 1.0}) async {
    RenderRepaintBoundary repaintBoundary = RenderRepaintBoundary();

    RenderView renderView = RenderView(
      child: RenderPositionedBox(alignment: alignment, child: repaintBoundary),
      configuration: ViewConfiguration(
        size: size,
        devicePixelRatio: devicePixelRatio,
      ),
      view: View.of(context),
      // window: ui.window,
    );

    PipelineOwner pipelineOwner = PipelineOwner();
    pipelineOwner.rootNode = renderView;
    renderView.prepareInitialFrame();

    BuildOwner buildOwner = BuildOwner(focusManager: FocusManager());
    RenderObjectToWidgetElement rootElement = RenderObjectToWidgetAdapter(
      container: repaintBoundary,
      child: widget,
    ).attachToRenderTree(buildOwner);
    buildOwner.buildScope(rootElement);
    buildOwner.finalizeTree();

    pipelineOwner.flushLayout();
    pipelineOwner.flushCompositingBits();
    pipelineOwner.flushPaint();

    ui.Image image = await repaintBoundary.toImage(pixelRatio: pixelRatio);
    ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);

    return byteData;
  }

  ByteData? image;

  void _showImage() {
    widgetToImage(
        context,
        Container(
          width: 80,
          height: 80,
          color: Colors.red,
          alignment: Alignment.center,
          child: const Directionality(
            textDirection: TextDirection.ltr,
            child: Text(
              'Hello',
              style: TextStyle(color: Colors.white),
            ),
          ),
        )).then((value) {
      setState(() {
        image = value;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: image != null
            ? Image.memory(image!.buffer.asUint8List())
            : Container(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showImage,
        tooltip: 'Show',
        child: const Icon(Icons.play_arrow),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Flutter 3.10.0 result</summary>
![3 10 0](https://github.com/flutter/flutter/assets/5134154/b4ea00b7-83da-48a9-956f-c8823996651f)
</details>

<details>
<summary>Flutter 3.7.12 result</summary>
![3 7 12](https://github.com/flutter/flutter/assets/5134154/9ac2e353-7fe1-439e-9856-3753d4c6a029)
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.10.0 on channel stable at /Users/lei/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (7 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/lei/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • D6069F1D-FFA1-4ECA-B497-44D80E278E70 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-05-17 08:43
Hi @xxzj990, I ran the code sample provided but when I tap on the `FAB` nothing happens. 
Is there something I'm missing? There are no errors in the console either.

**Comment by xxzj990** [comment] 2023-05-17 11:38
> Hi @xxzj990, I ran the code sample provided but when I tap on the `FAB` nothing happens. Is there something I'm missing? There are no errors in the console either.

Thank you for your reply, I tested it on the real machine again, and indeed I don't get any display, I get a 80x80 purple square on the emulator.

It seems that the effect on the real machine and the emulator is different, but it is not normal.

In addition, I use the Flutter 3.7.12 version of the SDK to test on the real machine and get the expected results, which are the same as the emulator.

If you need to run the test code on 3.7.12, you need to make the following modifications:

```
...
view: View.of(context),
// window: ui. window,
...
```
to
```
...
//view: View.of(context),
window: ui. window,
...
```

**Comment by danagbemava-nc** [comment] 2023-05-17 13:28
Hi, @xxzj990, thanks for the details. 

I can reproduce the issue on the iOS simulator using the code sample provided above on master & stable. On my physical device(iPhone XS), when I clicked the FAB, nothing is rendered on the screen. 
On flutter 3.7.12, it works as expected on both my physical device and the emulator. This does not seem to be specific to impeller as when I tested on the master channel with skia, nothing is rendered on the screen. 
This also reproduced on android and macOS. 

Labeling for further investigation

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel unknown, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
    ! Flutter version 3.7.12 on channel unknown at /Users/nexus/dev/sdks/flutter_rc/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter_rc/flutter. Consider adding /Users/nexus/dev/sdks/flutter_rc/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter_rc/flutter. Consider adding /Users/nexus/dev/sdks/flutter_rc/flutter/bin to the front of your path.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 4d9e56e694 (4 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.8770.15

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)       • 28291FDH2001SA                       • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 16.4.1 20E252
    • iPhone 14 Pro (mobile) • 4B6F7F35-7AFA-400C-B4A0-DAFA1B377178 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
    • Flutter version 3.10.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (8 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.8770.15

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)       • 28291FDH2001SA                       • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 16.4.1 20E252
    • iPhone 14 Pro (mobile) • 4B6F7F35-7AFA-400C-B4A0-DAFA1B377178 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.11.0-6.0.pre.112, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
    • Flutter version 3.11.0-6.0.pre.112 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 45e3039a45 (9 hours ago), 2023-05-17 00:56:25 -0400
    • Engine revision 4b7c37532e
    • Dart version 3.1.0 (build 3.1.0-117.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.8770.15

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)       • 28291FDH2001SA                       • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 16.4.1 20E252
    • iPhone 14 Pro (mobile) • 4B6F7F35-7AFA-400C-B4A0-DAFA1B377178 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by bleroux** [comment] 2023-05-22 06:23
I bisected this to https://github.com/flutter/flutter/pull/123433 which is an engine roll containing 1 commit:
https://github.com/flutter/engine/pull/40098.

Pinging @dnfield for insights about https://github.com/flutter/engine/pull/40098 impact on this issue.

**Comment by dnfield** [comment] 2023-05-22 16:23
I see, I can reproduce this on any platform. 

The problem is that the `offset` is some absurdly huge value that doesn't fit into a float. We used to just ignore this and make it identity, now we try to clamp it to FLT_MAX.

**Comment by dnfield** [comment] 2023-05-22 16:41
Ok, here's the problem:

- You're creating a render view that claims to have a size of `double.maxFinite` in both dimensions.
- You then try to position a child in the center of that view.
- This means the engine gets a transform layer with a value that is larger than the max what it considers to be a scalar value.
  - Before #123433, the engine would see this transform as having non-finite values (the too-large values got truncated to +inf), and it would replace the matrix with an identity matrix, and everything appeared to work for this case, because your widget was not getting transformed at all (but, in fact, this was not working, because _you were asking to draw your widget in the center of a very very very large space_).
  - After that commit, the engine now gets a transform with the max value of a float32 in there. You're getting a space that's about half as large as you were asking for and are now actually drawing the widget in the center of it, but that means the widget is getting drawn _very far outside of where you are actually drawing it_.

To fix this:

- You should probably not default to `double.maxFinite` for your size dimensions.
- You should definitely not default to `Alignment.center`. You really want `Alignment.topLeft` because that's where you're going to be taking from in the `toImage` call later.

I think this is all WAI, but we still have work to do in terms of how we deal with scalar values in the framework/ engine.

**Comment by dnfield** [comment] 2023-05-22 16:50
I'm going to close this as intended behavior. This was a breaking change for which no one had submitted tests, so it never got caught as a break we'd have to announce or migrate for. I'm sorry it's causing disruption for your particular implementation, but I hope you can see what I'm getting at: when you asked to draw a small thing in the center of a very large surface, we used to incorrectly draw the thing in the top left. Now we actually try to draw it at the center.

**Closed by dnfield** 2023-05-22 16:50 UTC
Labels: severe: regression, framework, severe: rendering, has reproducible steps, found in release: 3.10, found in release: 3.11

**Comment by xxzj990** [comment] 2023-05-23 01:28
> Ok, here's the problem:
> 
> * You're creating a render view that claims to have a size of `double.maxFinite` in both dimensions.
> * You then try to position a child in the center of that view.
> * This means the engine gets a transform layer with a value that is larger than the max what it considers to be a scalar value.
>   
>   * Before [Roll Flutter Engine from 608d5b214faa to 6c2dafed5077 (1 revision) #123433](https://github.com/flutter/flutter/pull/123433), the engine would see this transform as having non-finite values (the too-large values got truncated to +inf), and it would replace the matrix with an identity matrix, and everything appeared to work for this case, because your widget was not getting transformed at all (but, in fact, this was not working, because _you were asking to draw your widget in the center of a very very very large space_).
>   * After that commit, the engine now gets a transform with the max value of a float32 in there. You're getting a space that's about half as large as you were asking for and are now actually drawing the widget in the center of it, but that means the widget is getting drawn _very far outside of where you are later pulling the image data from_.
> 
> To fix this:
> 
> * You should probably not default to `double.maxFinite` for your size dimensions.
> * You should definitely not default to `Alignment.center`. You really want `Alignment.topLeft` because that's where you're going to be taking from in the `toImage` call later.
> 
> I think this is all WAI, but we still have work to do in terms of how we deal with scalar values in the framework/ engine.

@dnfield Thanks, It works!

### Code sample

<details><summary>Code sample</summary>

``` dart
import 'dart:developer';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter 3.10.0'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static Future<ByteData?> widgetToImage(BuildContext context, Widget widget,
      {required Size size,
      double devicePixelRatio = 1.0,
      double pixelRatio = 1.0}) async {
    RenderRepaintBoundary repaintBoundary = RenderRepaintBoundary();

    RenderView renderView = RenderView(
      child: RenderPositionedBox(
          alignment: Alignment.topLeft, child: repaintBoundary),
      configuration: ViewConfiguration(
        size: size,
        devicePixelRatio: devicePixelRatio,
      ),
      view: View.of(context),
      // window: ui.window,
    );

    PipelineOwner pipelineOwner = PipelineOwner();
    pipelineOwner.rootNode = renderView;
    renderView.prepareInitialFrame();

    BuildOwner buildOwner = BuildOwner(focusManager: FocusManager());
    RenderObjectToWidgetElement rootElement = RenderObjectToWidgetAdapter(
      container: repaintBoundary,
      child: widget,
    ).attachToRenderTree(buildOwner);
    buildOwner.buildScope(rootElement);
    buildOwner.finalizeTree();

    pipelineOwner.flushLayout();
    pipelineOwner.flushCompositingBits();
    pipelineOwner.flushPaint();

    ui.Image image = await repaintBoundary.toImage(pixelRatio: pixelRatio);
    ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);

    return byteData;
  }

  ByteData? image;

  void _showImage() {
    widgetToImage(
            context,
            Container(
              width: 80,
              height: 80,
              color: Colors.red,
              alignment: Alignment.center,
              child: const Directionality(
                textDirection: TextDirection.ltr,
                child: Text(
                  'Hello',
                  style: TextStyle(color: Colors.white),
                ),
              ),
            ),
            size: const Size(80, 80))
        .then((value) {
      log('value:$value');
      setState(() {
        image = value;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: image != null
            ? Image.memory(image!.buffer.asUint8List())
            : Container(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showImage,
        tooltip: 'Show',
        child: const Icon(Icons.play_arrow),
      ),
    );
  }
}
```
</details>
