### ISSUE TITLE
The following assertion was thrown building Container(padding: EdgeInsets(20.0, 0.0, 30.0, 0.0), bg: I/flutter ( 9092):   BoxDecoration(color: Color(0xffffffff), borderRadius: BorderRadius.circular(14.0), boxShadow: I/flutter ( 9092):   [BoxShadow(Color(0x1f000000), Offset(0.0, 0.0), 10.0, 0.0)] I/flutter ( 9092):   ), constraints: BoxConstraints(w=300.0, h=60.0)): I/flutter ( 9092): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 676 pos 12: 'widget.value == I/flutter ( 9092): null || I/flutter ( 9092):       widget.items.where((DropdownMenuItem<T> item) => item.value == widget.value).length == 1': is I/flutter ( 9092):       not true.

### ISSUE THREAD

**Issue by mouhssineelazhadi** [flutter/flutter#30338] opened 2019-04-01 21:35 UTC
```
child : DropdownButton<String>(
                                  /*
                                  _currencies.map((String dropDownItem){
                                          return DropdownMenuItem<String>(
                                              value : dropDownItem,
                                              child : Text(dropDownItem),
                                          );
                                  */

                                  items: cities.map((item) {
                                    return new DropdownMenuItem(
                                      child: new Text(item['name']),
                                      value: item['id'].toString(),
                                    );
                                  }).toList(),
                                    hint: new Text("Choisir votre ville"),
                                 onChanged: (String newVal){
                                    setState(() {
                                      selectedItem = newVal;
                                    });
                                 },
                                  value: selectedItem,
                                  style: TextStyle(
                                      fontSize: 15.0,
                                      fontFamily: 'Sans',
                                      letterSpacing: 0.3,
                                      color: Colors.black38,
                                      fontWeight: FontWeight.w600)
                                ),
```
```
final String url = Consts.Consts.ipAddress+":"+Consts.Consts.port+"/Cities";

  List cities = List(); //edited line

  Future<String> getCities() async {
    print(Consts.Consts.token);
    var res = await http
        .get(Uri.encodeFull(url), headers: {"Accept": "application/json"});
    var resBody = json.decode(res.body);
  print(resBody.runtimeType);
    setState(() {
      cities = resBody;
    });
    print(resBody);
    return "Sucess";
  }
```

```
 ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9092): The following assertion was thrown building Container(padding: EdgeInsets(20.0, 0.0, 30.0, 0.0), bg:
I/flutter ( 9092):   BoxDecoration(color: Color(0xffffffff), borderRadius: BorderRadius.circular(14.0), boxShadow:
I/flutter ( 9092):   [BoxShadow(Color(0x1f000000), Offset(0.0, 0.0), 10.0, 0.0)]
I/flutter ( 9092):   ), constraints: BoxConstraints(w=300.0, h=60.0)):
I/flutter ( 9092): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 676 pos 12: 'widget.value ==
I/flutter ( 9092): null ||
I/flutter ( 9092):       widget.items.where((DropdownMenuItem<T> item) => item.value == widget.value).length == 1': is
I/flutter ( 9092):       not true.
I/flutter ( 9092): 
I/flutter ( 9092): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9092): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9092): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9092):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9092): 
I/flutter ( 9092): When the exception was thrown, this was the stack:
I/flutter ( 9092): #2      _DropdownButtonState._updateSelectedIndex (package:flutter/src/material/dropdown.dart:676:12)
I/flutter ( 9092): #3      _DropdownButtonState.didUpdateWidget (package:flutter/src/material/dropdown.dart:668:5)
I/flutter ( 9092): #4      StatefulElement.update (package:flutter/src/widgets/framework.dart:3879:58)
I/flutter ( 9092): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9092): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9092): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9092): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #23     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9092): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #25     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9092): #26     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9092): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #28     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9092): #29     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9092): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9092): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9092): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #47     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1030:36)
I/flutter ( 9092): #48     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:980:34)
I/flutter ( 9092): #49     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter ( 9092): #50     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:991:36)
I/flutter ( 9092): #51     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:957:7)
I/flutter ( 9092): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #55     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9092): #56     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9092): #57     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 9092): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #73     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9092): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9092): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #89     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #93     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #97     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9092): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #101    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9092): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #103    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #107    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9092): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #113    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9092): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #115    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9092): #116    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9092): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #120    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9092): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #124    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9092): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #126    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9092): #127    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9092): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #131    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #135    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9092): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #139    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #141    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #144    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #145    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9092): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #147    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9092): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #151    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #155    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #159    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9092): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #163    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9092): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #167    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9092): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9092): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9092): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9092): #171    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter ( 9092): #172    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 9092): #173    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 9092): #174    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 9092): #175    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 9092): #176    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter ( 9092): #180    _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 9092): #181    _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 9092): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 9092): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by natanfudge** [comment] 2019-05-13 14:10
The assertion should be split into multiple different assertions so the user knows exactly what condition was not satisfied. 
In my experience this part part causes the error happens most often: `widget.items.where((DropdownMenuItem<T> item) => item.value == widget.value).length == 1`. If it's not true it means that either the `DropdownButton` has a value that none of the `DropdownMenuItem` have, or there are 2 `DropdownMenuItem`s with that value. These two cases should also be separate.

**Comment by natanfudge** [comment] 2019-05-13 19:26
I would like to contribute the changes I mentioned as well as add text to the assets. Would that be acceptable?

**Comment by VladyslavBondarenko** [comment] 2020-02-18 14:43
Duplicate of https://github.com/flutter/flutter/issues/17903

**Closed by VladyslavBondarenko** 2020-02-18 14:43 UTC
Labels: d: stackoverflow, f: material design, framework
