### ISSUE TITLE
[webview_flutter] Android Platform Views do not work on devices without VirtualDisplay support

### ISSUE THREAD

**Issue by KinsomyJS** [flutter/flutter#24974] opened 2018-12-05 07:17 UTC
in Oppo R15，Android view represents a black card,but my oneplus 5 is correct。

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2017.3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.29.1)
[✓] Connected device (2 available)
```

```dart
class TextViewExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Flutter TextView example')),
        body: Column(children: [
          Center(
              child: Container(
                  padding: EdgeInsets.symmetric(vertical: 30.0),
                  width: 130.0,
                  height: 100.0,
                  color: Colors.blue[100],
                  child: TextView(
                    onTextViewCreated: _onTextViewCreated,
                  ))),
          Expanded(
              flex: 3,
              child: Container(
                  color: Colors.blue[100],
                  child: Center(child: Text("Hello from Flutter!"))))
        ]));
  }

  void _onTextViewCreated(TextViewController controller) {
    controller.setText('Hello from Android!');
  }
}
```
```dart
class _TextViewState extends State<TextView> {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    if (defaultTargetPlatform == TargetPlatform.android) {
      return AndroidView(
          viewType: 'plugins.kinsomy/textview',
          onPlatformViewCreated: _onPlatformViewCreated);
    }
    return Text('$defaultTargetPlatform is not support yet');
  }

  void _onPlatformViewCreated(int id) {
    if (widget.onTextViewCreated == null) {
      return;
    }
    widget.onTextViewCreated(new TextViewController._(id));
  }
}
```

**Comment by amirh** [comment] 2018-12-06 23:47
Can you try the [webview example app](https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example) so we can run the same code.

Also can you please include a screenshot and all logs you get when you start the webview example app.

Thanks.

**Comment by luodongseu** [comment] 2019-02-16 02:00
@amirh  I use flutter_webview plugin, but when i run code on oppo phone, it show black screen and console print logs like "D/BufferQueueProducer(15418): [SurfaceTexture-0-15418-1](this:0x7ed08c3800,id:1,api:1,p:414,c:-1) cancelBuffer: slot 0", and the log print continue when i not close that page.

**Comment by amirh** [comment] 2019-02-16 02:04
Can you include the output for ‘flutter doctor -v’ and more of the logcat log?

**Comment by huuang** [comment] 2019-03-12 10:26
I am pacing the same problem, any suggestions will be appreciated.

`[✓] Flutter (Channel dev, v1.3.2, on Mac OS X 10.14.3 18D109, locale en-CN)
    • Flutter version 1.3.2 at /Users/huangjihua/Development/flutter
    • Framework revision 046f960ae2 (11 days ago), 2019-02-28 23:05:45 -0800
    • Engine revision 99f3f7a9c2
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/huangjihua/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • PACM00 • LR9LRGO7SOSC7D85 • android-arm64 • Android 8.1.0 (API 27)`

**Comment by huuang** [comment] 2019-03-12 10:33
log:

`-platform android-arm
Launching lib/main.dart on PACM00 in debug mode...
Initializing gradle...                                              1.1s
Resolving dependencies...                                           2.0s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         2.0s
Built build/app/outputs/apk/debug/app-debug.apk.
D/libEGL  (22211): ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0xcdb77e00)     
I/BufferQueue(22211): [unnamed-22211-0](this:0xcb406000,id:0,api:0,p:-1,c:-1) BufferQueue core=(22211:com.example.test_android_view)
W/GuiExt  (22211): Cannot find GuiExtService                            
E/GED     (22211): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, 7        
I/GLConsumer(22211): [SurfaceTexture-0-22211-0] detachFromContext       
I/Presentation(22211): Presentation is being dismissed because the display metrics have changed since it was created.
D/WindowClient(22211): Add to mViews: DecorView@dec1649[], this = android.view.WindowManagerGlobal@4e69e9e
I/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) connect(P): api=1 producer=(415:???) producerControlledByApp=false
D/ViewRootImpl[MainActivity](22211): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
I/InputTransport(22211): Create ARC handle: 0xcccd5110                  
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/View    (22211): [Warning] assignParent to null: this = DecorView@dec1649[]
I/InputTransport(22211): Destroy ARC handle: 0xcccd5110                 
D/WindowClient(22211): Remove from mViews: DecorView@dec1649[], this = android.view.WindowManagerGlobal@4e69e9e
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
I/GLConsumer(22211): [SurfaceTexture-0-22211-0] attachToContext         
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/HWUIExtension(22211): MTKProgramCache.generateProgram: 562984313159681
D/HWUIExtension(22211): createProgram 0x0002000800000001, binary 0xeea22cac, length 5080, format 36705 within 282ns
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0`

**Comment by huuang** [comment] 2019-03-12 10:51
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.

Please reopen this issue.

**Comment by amirh** [comment] 2019-03-12 18:49
@huuang can you confirm that you get this when running the webview sample app?
Which phone are you seeing this on?

**Comment by huuang** [comment] 2019-03-13 02:34
> @huuang can you confirm that you get this when running the webview sample app?
> Which phone are you seeing this on?

This issue happens on OPPO and vivo brand phones.

**Comment by huuang** [comment] 2019-03-13 02:50
> @huuang can you confirm that you get this when running the webview sample app?
> Which phone are you seeing this on?

I tried it again, and I am sure the webview sample app has the same problem on OPPO and vivo brand phones while no problem on others.

**Comment by huuang** [comment] 2019-03-14 03:05
> @huuang can you confirm that you get this when running the webview sample app?
> Which phone are you seeing this on?

Please reopen this issue, thank you very much.

**Comment by huuang** [comment] 2019-03-14 08:40
I create a new issue https://github.com/flutter/flutter/issues/29346

**Comment by huuang** [comment] 2019-03-17 16:22
OPPO and vivo brand phones occupy half of the Android mobile phone market in China.

This issue blocks my application publishing. I wish this issue would be fixed soon, Thank you very much.

**Comment by amirh** [comment] 2019-03-17 20:28
@huuang can you check if video playback is working on this phone? you can try the video page in the [Flutter Gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) app 
 (under Media).

**Comment by huuang** [comment] 2019-03-18 03:11
> @huuang can you check if video playback is working on this phone? you can try the video page in the [Flutter Gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) app
> (under Media).

I have tested it, video playback works well in Flutter Gallery app.

**Comment by amirh** [comment] 2019-03-18 03:19
Interesting that means external textures are working e2e in Flutter.
Can you try running the following Android app (not Flutter) to check whether virtual displays are working on the device: https://gist.github.com/amirh/33e2765206d6107bd52beeaca8b634cc

If you can post a screenshot of that activity running on the device it will be helpful.

**Comment by amirh** [comment] 2019-03-18 03:20
Just to make sure: did you run Flutter Gallery from the same Flutter framework commit you're seeing the issue with?

**Comment by huuang** [comment] 2019-03-18 03:38
> Interesting that means external textures are working e2e in Flutter.
> Can you try running the following Android app (not Flutter) to check whether virtual displays are working on the device: https://gist.github.com/amirh/33e2765206d6107bd52beeaca8b634cc
> 
> If you can post a screenshot of that activity running on the device it will be helpful.

![WechatIMG102](https://user-images.githubusercontent.com/14324434/54505328-543e9e00-4972-11e9-9da0-d61eb25ae4ba.png)

**Comment by huuang** [comment] 2019-03-18 03:40
> Interesting that means external textures are working e2e in Flutter.
> Can you try running the following Android app (not Flutter) to check whether virtual displays are working on the device: https://gist.github.com/amirh/33e2765206d6107bd52beeaca8b634cc
> 
> If you can post a screenshot of that activity running on the device it will be helpful.

Error log:
<img width="1358" alt=" 2019-03-18 at 11 39 47 AM" src="https://user-images.githubusercontent.com/14324434/54505399-97007600-4972-11e9-9a8d-8608e501da8b.png">

**Comment by huuang** [comment] 2019-03-18 03:44
> Just to make sure: did you run Flutter Gallery from the same Flutter framework commit you're seeing the issue with?

I am sure they are running from the same Flutter framework commit.

**Comment by amirh** [comment] 2019-03-18 04:21
Wow looks like virtual displays are not working on that device, there isn't much Flutter can do about it(that Android app you ran should present a red rectangle in the center that is rendered through a virtual display).

I'd guess the best chance is to follow up with the vendor. I'll also try to get ahold of one of these devices to make sure I'm seeing the same.

**Comment by amirh** [comment] 2019-03-26 16:01
Hi, I just got an Oppo R15, we tried the webview example and it works.

The device is running Android 8.1.0

Can you post the Android version for your Oppo R15 phone that does not work?

**Comment by huuang** [comment] 2019-03-27 03:35
> Hi, I just got an Oppo R15, we tried the webview example and it works.
> 
> The device is running Android 8.1.0
> 
> Can you post the Android version for your Oppo R15 phone that does not work?

Same as mine

![WechatIMG105](https://user-images.githubusercontent.com/14324434/55048771-644a3200-5084-11e9-8768-f16bf6da7b41.jpeg)

**Comment by huuang** [comment] 2019-03-27 03:55
@amirh 

Thank you for your help.

I have confirmed with the manufacturer, they said only some ROM versions have this problem.

**Comment by amirh** [comment] 2019-03-27 05:17
Thanks for the update! Did they say if this is something they are planning to fix for the ROMs that has the issue?

**Comment by amirh** [comment] 2019-03-27 16:47
For reference the device I have that's working has a different model: PACT00, other than that the versions seems to be the same.

**Comment by huuang** [comment] 2019-03-29 02:31
> Thanks for the update! Did they say if this is something they are planning to fix for the ROMs that has the issue?

Yes, they did. But they did not give the deadline to fix it.

**Comment by MoiSaco** [comment] 2019-04-02 09:55
> Wow looks like virtual displays are not working on that device, there isn't much Flutter can do about it(that Android app you ran should present a red rectangle in the center that is rendered through a virtual display).
> 
> I'd guess the best chance is to follow up with the vendor. I'll also try to get ahold of one of these devices to make sure I'm seeing the same.

is there a way for us to disable virtual display in order to adapt more phones?

**Comment by xiaojia21190** [comment] 2019-04-03 06:05
> > 感谢更新！他们是否说过他们是否打算为有问题的ROM修复这个问题？
> 
> 是的，他们确实。但他们没有给出修复它的截止日期。

你们之后是怎么解决的

**Comment by huuang** [comment] 2019-04-03 06:13
> > > 感谢更新！他们是否说过他们是否打算为有问题的ROM修复这个问题？
> > 
> > 
> > 是的，他们确实。但他们没有给出修复它的截止日期。
> 
> 你们之后是怎么解决的

Ignore this issue.

**Comment by amirh** [comment] 2019-05-15 18:04
I just heard back from Oppo, the virtual display issue is fixed in their latest OTA.
@freejihua  / @KinsomyJS can you confirm that the issue is fixed after installing the latest system update?

**Comment by freejihua** [comment] 2019-05-16 03:44
@amirh Yes, it is fixed.

**Closed** 2019-06-05 18:56 UTC
Labels: a: platform-views, engine, waiting for customer response

**Comment by ikkyu0319** [comment] 2020-06-19 07:53
@DylanXing @huuang @xiaojia21190 你们怎么解决了呢？

**Comment by huuang** [comment] 2020-06-19 11:43
> @DylanXing @huuang @xiaojia21190 你们怎么解决了呢？

部分版本操作系统的问题，OPPO 那边说后续版本会修复，所以忽略这个问题。

**Comment by suhail-zartek** [comment] 2020-09-11 11:54
Same situation in Color OS7 while using exoplayer.The audio plays well.But the video is on the black screen. Please reopen this issue

**Comment by prashantspandey** [comment] 2020-10-06 17:46
> Same situation in Color OS7 while using exoplayer.The audio plays well.But the video is on the black screen. Please reopen this issue

Facing the same problem in Oppo reno 2f Color os 7 and 8. AUdio works but blank video. Any solutions?

**Comment by fauzy6493** [comment] 2020-11-09 14:33
> I just heard back from Oppo, the virtual display issue is fixed in their latest OTA.
> @freejihua / @KinsomyJS can you confirm that the issue is fixed after installing the latest system update?

May i know what is VirtualDisplay?
And how to test the phone is support VirtualDisplay or not?
