### ISSUE TITLE
other characters will not be entered when I type quickly on the TextField

### ISSUE THREAD

**Issue by isabadguy** [flutter/flutter#43889] opened 2019-10-31 07:04 UTC
## Steps to Reproduce

1. source code
```
import 'package:flutter/material.dart';

void main() => runApp(AppScene());

class AppScene extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('title'),
        ),
        body: Center(
          child: TextField(
            obscureText: true,
          ),
        ),
      ),
    );
  }

}
```
2.  screen capture
![d81cr-9zgpb](https://user-images.githubusercontent.com/20485798/67924944-e4bdac00-fbec-11e9-95c9-33cf8521b961.gif)

Like the image, other characters will not be entered when I type quickly on the TextField.
I'm not sure if this is a bug.
Is there a way I can fix it?
Thx.

**Target Platform: Android
**Target OS version/browser:  Android 8.0
**Devices: honor 8

## Logs

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.9.1+hotfix.4 at E:\tools\Android\flutter
    • Framework revision cc949a8e8b (5 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\tools\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\tools\Android\Sdk
    • Java binary at: E:\tools\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at E:\tools\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at E:\tools\IntelliJ IDEA 2017.3.5
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[√] Connected device (1 available)
    • FRD AL00 • WTK7N16C13001996 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

```

**Comment by SyaKaku** [comment] 2019-10-31 08:08
I has the same problem and can not find the solution how to fix it.

My OS version is Android 8.0
My device is samsung Galaxy S8

**Comment by sevensun1213** [comment] 2019-10-31 08:22
how to deal with it?!  
It's normal on the device of IPhone 8+，but it's unuseful on the device of Anfroid .
It is ok with full keyboard input the words on the password TextField.But it is not work well with nine palace keyboard.

**Comment by TahaTesser** [comment] 2020-04-16 14:06
Hi @isabadguy 
Not able to reproduce with issue when typed quickly
Are you still experiencing the issue with latest stable?
if yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by espresso3389** [comment] 2020-04-21 14:30
Same issue on Sony Xperia XZ1 Compact (SO-02K). No other devices around me does not reproduce the issue (even on same generation Xperia devices).

**Comment by yamakoshi-jig** [comment] 2020-04-24 03:10
I think this is caused by the POBox Plus IME that is installed in Xperia.
Workaround from https://github.com/flutter/flutter/issues/22828#issuecomment-509092147 :

```
TextField(
  keyboardType: TextInputType.emailAddress,
  ...
);
```

However, this is not so good as it will open the keyboard for email.

**Comment by macoshita** [comment] 2020-04-24 03:11
I think this is caused by the POBox Plus IME that is installed in Xperia.
Workaround from https://github.com/flutter/flutter/issues/22828#issuecomment-509092147 :

```
TextField(
  keyboardType: TextInputType.emailAddress,
  ...
);
```

However, this is not so good as it will open the keyboard for email.

**Comment by iapicca** [comment] 2020-06-05 13:09
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-06-05 13:09 UTC
Labels: a: text input, e: device-specific, f: material design, framework, platform-android, waiting for customer response
