### ISSUE TITLE
Improve performance of building DlColorSource objects

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101518] opened 2022-04-07 14:59 UTC
b/226484927

This is currently copying some information, which is slow on low-end devices. That information could instead be passed by reference.

**Comment by zanderso** [comment] 2022-04-09 01:14
The initial results of the benchmark on a Moto G4 don't seem to demonstrate any significant difference before and after https://github.com/flutter/engine/pull/31981. I think we will need to do the same experiment on a lower-end device. I believe @dnfield will be taking a look at that next week.

**Comment by dnfield** [comment] 2022-04-11 22:31
Dynamic:

A:

```
  "average_frame_build_time_millis": 5.728,
  "90th_percentile_frame_build_time_millis": 6.382,
  "99th_percentile_frame_build_time_millis": 8.313,
  "worst_frame_build_time_millis": 11.868,
  "missed_frame_build_budget_count": 0,
  "average_frame_rasterizer_time_millis": 11.362,
  "90th_percentile_frame_rasterizer_time_millis": 12.309,
  "99th_percentile_frame_rasterizer_time_millis": 17.049,
  "worst_frame_rasterizer_time_millis": 21.825,
  "average_layer_cache_count": 0.0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0.0,
  "90th_percentile_layer_cache_memory": 0.0,
  "99th_percentile_layer_cache_memory": 0.0,
  "worst_layer_cache_memory": 0.0,
  "average_picture_cache_count": 0.0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0.0,
  "90th_percentile_picture_cache_memory": 0.0,
  "99th_percentile_picture_cache_memory": 0.0,
  "worst_picture_cache_memory": 0.0,
  "missed_frame_rasterizer_budget_count": 12,
  "frame_count": 607,
  "new_gen_gc_count": 82,
  "old_gen_gc_count": 2
```

B:

```
  "average_frame_build_time_millis": 4.978,
  "90th_percentile_frame_build_time_millis": 5.52,
  "99th_percentile_frame_build_time_millis": 7.243,
  "worst_frame_build_time_millis": 10.067,
  "missed_frame_build_budget_count": 0,
  "average_frame_rasterizer_time_millis": 11.178,
  "90th_percentile_frame_rasterizer_time_millis": 12.142,
  "99th_percentile_frame_rasterizer_time_millis": 15.642,
  "worst_frame_rasterizer_time_millis": 21.424,
  "average_layer_cache_count": 0.0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0.0,
  "90th_percentile_layer_cache_memory": 0.0,
  "99th_percentile_layer_cache_memory": 0.0,
  "worst_layer_cache_memory": 0.0,
  "average_picture_cache_count": 0.0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0.0,
  "90th_percentile_picture_cache_memory": 0.0,
  "99th_percentile_picture_cache_memory": 0.0,
  "worst_picture_cache_memory": 0.0,
  "missed_frame_rasterizer_budget_count": 5,
  "frame_count": 605,
  "new_gen_gc_count": 54,
  "old_gen_gc_count": 0
```

static: 

a:

```
  "average_frame_build_time_millis": 2.151,
  "90th_percentile_frame_build_time_millis": 2.514,
  "99th_percentile_frame_build_time_millis": 3.213,
  "worst_frame_build_time_millis": 4.497,
  "missed_frame_build_budget_count": 0,
  "average_frame_rasterizer_time_millis": 11.325,
  "90th_percentile_frame_rasterizer_time_millis": 12.232,
  "99th_percentile_frame_rasterizer_time_millis": 15.26,
  "worst_frame_rasterizer_time_millis": 19.869,
  "average_layer_cache_count": 0.0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0.0,
  "90th_percentile_layer_cache_memory": 0.0,
  "99th_percentile_layer_cache_memory": 0.0,
  "worst_layer_cache_memory": 0.0,
  "average_picture_cache_count": 0.0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0.0,
  "90th_percentile_picture_cache_memory": 0.0,
  "99th_percentile_picture_cache_memory": 0.0,
  "worst_picture_cache_memory": 0.0,
  "missed_frame_rasterizer_budget_count": 4,
  "frame_count": 605,
  "new_gen_gc_count": 6,
  "old_gen_gc_count": 2
```
b:
```
  "average_frame_build_time_millis": 3.279,
  "90th_percentile_frame_build_time_millis": 3.961,
  "99th_percentile_frame_build_time_millis": 5.175,
  "worst_frame_build_time_millis": 10.187,
  "missed_frame_build_budget_count": 0,
  "average_frame_rasterizer_time_millis": 11.429,
  "90th_percentile_frame_rasterizer_time_millis": 12.384,
  "99th_percentile_frame_rasterizer_time_millis": 14.823,
  "worst_frame_rasterizer_time_millis": 18.292,
  "average_layer_cache_count": 0.0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0.0,
  "90th_percentile_layer_cache_memory": 0.0,
  "99th_percentile_layer_cache_memory": 0.0,
  "worst_layer_cache_memory": 0.0,
  "average_picture_cache_count": 0.0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0.0,
  "90th_percentile_picture_cache_memory": 0.0,
  "99th_percentile_picture_cache_memory": 0.0,
  "worst_picture_cache_memory": 0.0,
  "missed_frame_rasterizer_budget_count": 4,
  "frame_count": 606,
  "new_gen_gc_count": 6,
  "old_gen_gc_count": 0
```

consistent:

a:
```
  "average_frame_build_time_millis": 4.976,
  "90th_percentile_frame_build_time_millis": 5.415,
  "99th_percentile_frame_build_time_millis": 7.579,
  "worst_frame_build_time_millis": 15.213,
  "missed_frame_build_budget_count": 0,
  "average_frame_rasterizer_time_millis": 11.14,
  "90th_percentile_frame_rasterizer_time_millis": 12.046,
  "99th_percentile_frame_rasterizer_time_millis": 15.393,
  "worst_frame_rasterizer_time_millis": 16.319,
  "average_layer_cache_count": 0.0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0.0,
  "90th_percentile_layer_cache_memory": 0.0,
  "99th_percentile_layer_cache_memory": 0.0,
  "worst_layer_cache_memory": 0.0,
  "average_picture_cache_count": 0.0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0.0,
  "90th_percentile_picture_cache_memory": 0.0,
  "99th_percentile_picture_cache_memory": 0.0,
  "worst_picture_cache_memory": 0.0,
  "missed_frame_rasterizer_budget_count": 3,
  "frame_count": 603,
  "new_gen_gc_count": 56,
  "old_gen_gc_count": 0
```

b:
```
  "average_frame_build_time_millis": 5.698,
  "90th_percentile_frame_build_time_millis": 6.356,
  "99th_percentile_frame_build_time_millis": 8.396,
  "worst_frame_build_time_millis": 18.375,
  "missed_frame_build_budget_count": 1,
  "average_frame_rasterizer_time_millis": 11.424,
  "90th_percentile_frame_rasterizer_time_millis": 12.423,
  "99th_percentile_frame_rasterizer_time_millis": 16.572,
  "worst_frame_rasterizer_time_millis": 26.198,
  "average_layer_cache_count": 0.0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0.0,
  "90th_percentile_layer_cache_memory": 0.0,
  "99th_percentile_layer_cache_memory": 0.0,
  "worst_layer_cache_memory": 0.0,
  "average_picture_cache_count": 0.0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0.0,
  "90th_percentile_picture_cache_memory": 0.0,
  "99th_percentile_picture_cache_memory": 0.0,
  "worst_picture_cache_memory": 0.0,
  "missed_frame_rasterizer_budget_count": 8,
  "frame_count": 596,
  "new_gen_gc_count": 80,
  "old_gen_gc_count": 2
```

**Comment by dnfield** [comment] 2022-04-11 22:33
It's hard to tell if this is noise or not... is there a particular one I should try to run for more iterations?

**Comment by flar** [comment] 2022-04-11 22:43
The benchmarks looked pretty stable to me when they were running under Performance Overlay, so I think it is more how much 200 iterations of this one rendering technique might impact an overall frame rate for the given act.

About the only other measurement I thought might be helpful is how much the static compares to the dynamic which gives us a good idea of whether recreating the SkShaders every time we render them might be costing us due to GPU program cache misses.

**Comment by flar** [comment] 2022-04-11 22:45
Obviously the static case improves a lot for the build times. This slow device takes a long time to create and transfer the arrays to native. But they don't seem to impact raster times much.

**Comment by flar** [comment] 2022-04-11 22:55
There does seem to be some inconsistency when the consistent version has longer build times than the dynamic. The only difference between these two is that they both recreate the gradients on every frame, but the consistent version uses the same values on every frame and the dynamic one computes new values every frame. I did that to see if Skia might be caching based on value or not. There shouldn't really be any reason that consistent is faster than dynamic to build, they should only maybe see a difference in raster time.

The AB mechanism for running benchmarks works well for checking consistency. It runs the benchmark 4 times each on the default framework repo's engine and again with the local engine, interspersing the runs for added consistency checking. It them reports the averages over 4 runs and their variance.

**Comment by flar** [comment] 2022-04-11 23:47
Results of an A/B test similar to what Dan did on his low end device - these were run on a Moto G 4:

Here are the results of doing an A/B run on these benchmarks against a pre-DlColorSource engine. For each of these results, the default, or A engine is using the DlColorSource and the local, or B engine is using SkGradient. The "Speed-up" column is how much faster Sk is against Dl (or slower if the factor is less than 1.0).

Results for the "static" version of the benchmark:

```
═══════════╡ ••• Formatted summary for "ABresults.static.json" ••• ╞════════════

                   Score                     Average A (noise)  Average B (noise)   Speed-up
average_frame_build_time_millis                   5.35 (0.59%)       4.45 (0.92%)    1.20x  
worst_frame_build_time_millis                     7.79 (0.64%)       7.25 (11.94%)   1.07x  
90th_percentile_frame_build_time_millis           5.80 (0.86%)       4.90 (0.27%)    1.18x  
99th_percentile_frame_build_time_millis           6.36 (6.13%)       5.52 (3.56%)    1.15x  
average_frame_rasterizer_time_millis             15.15 (0.41%)      16.01 (0.91%)    0.95x  
worst_frame_rasterizer_time_millis               18.85 (2.28%)      20.16 (7.17%)    0.94x  
90th_percentile_frame_rasterizer_time_millis     15.43 (0.61%)      16.28 (1.25%)    0.95x  
99th_percentile_frame_rasterizer_time_millis     16.04 (1.37%)      17.55 (2.76%)    0.91x  
average_layer_cache_count                         0.00 (0.00%)       0.00 (0.00%)     NaNx  
90th_percentile_layer_cache_count                 0.00 (0.00%)       0.00 (0.00%)     NaNx  
99th_percentile_layer_cache_count                 0.00 (0.00%)       0.00 (0.00%)     NaNx  
worst_layer_cache_count                           0.00 (0.00%)       0.00 (0.00%)     NaNx  
average_layer_cache_memory                        0.00 (0.00%)       0.00 (0.00%)     NaNx  
90th_percentile_layer_cache_memory                0.00 (0.00%)       0.00 (0.00%)     NaNx  
99th_percentile_layer_cache_memory                0.00 (0.00%)       0.00 (0.00%)     NaNx  
worst_layer_cache_memory                          0.00 (0.00%)       0.00 (0.00%)     NaNx  
average_picture_cache_count                       0.00 (0.00%)       0.00 (0.00%)     NaNx  
90th_percentile_picture_cache_count               0.00 (0.00%)       0.00 (0.00%)     NaNx  
99th_percentile_picture_cache_count               0.00 (0.00%)       0.00 (0.00%)     NaNx  
worst_picture_cache_count                         0.00 (0.00%)       0.00 (0.00%)     NaNx  
average_picture_cache_memory                      0.00 (0.00%)       0.00 (0.00%)     NaNx  
90th_percentile_picture_cache_memory              0.00 (0.00%)       0.00 (0.00%)     NaNx  
99th_percentile_picture_cache_memory              0.00 (0.00%)       0.00 (0.00%)     NaNx  
worst_picture_cache_memory                        0.00 (0.00%)       0.00 (0.00%)     NaNx  
new_gen_gc_count                                  5.50 (15.75%)      5.00 (20.00%)   1.10x  
old_gen_gc_count                                  0.00 (0.00%)       1.00 (100.00%)  0.00x  
```

And the results for the "consistent" version of the benchmark:

```
═════════╡ ••• Formatted summary for "ABresults.consistent.json" ••• ╞══════════

                   Score                     Average A (noise)  Average B (noise)   Speed-up
average_frame_build_time_millis                  10.42 (1.20%)      10.46 (1.11%)    1.00x  
worst_frame_build_time_millis                    74.88 (1.36%)      62.10 (3.12%)    1.21x  
90th_percentile_frame_build_time_millis          10.86 (0.57%)      11.08 (0.42%)    0.98x  
99th_percentile_frame_build_time_millis          24.14 (89.89%)     11.99 (1.11%)    2.01x  
average_frame_rasterizer_time_millis             16.03 (0.45%)      16.60 (0.33%)    0.97x  
worst_frame_rasterizer_time_millis               27.83 (11.09%)     24.06 (3.36%)    1.16x  
90th_percentile_frame_rasterizer_time_millis     16.57 (0.42%)      17.03 (1.30%)    0.97x  
99th_percentile_frame_rasterizer_time_millis     20.68 (5.65%)      21.17 (1.55%)    0.98x  
average_layer_cache_count                         0.00 (0.00%)       0.00 (0.00%)     NaNx  
90th_percentile_layer_cache_count                 0.00 (0.00%)       0.00 (0.00%)     NaNx  
99th_percentile_layer_cache_count                 0.00 (0.00%)       0.00 (0.00%)     NaNx  
worst_layer_cache_count                           0.00 (0.00%)       0.00 (0.00%)     NaNx  
average_layer_cache_memory                        0.00 (0.00%)       0.00 (0.00%)     NaNx  
90th_percentile_layer_cache_memory                0.00 (0.00%)       0.00 (0.00%)     NaNx  
99th_percentile_layer_cache_memory                0.00 (0.00%)       0.00 (0.00%)     NaNx  
worst_layer_cache_memory                          0.00 (0.00%)       0.00 (0.00%)     NaNx  
average_picture_cache_count                       0.00 (0.00%)       0.00 (0.00%)     NaNx  
90th_percentile_picture_cache_count               0.00 (0.00%)       0.00 (0.00%)     NaNx  
99th_percentile_picture_cache_count               0.00 (0.00%)       0.00 (0.00%)     NaNx  
worst_picture_cache_count                         0.00 (0.00%)       0.00 (0.00%)     NaNx  
average_picture_cache_memory                      0.00 (0.00%)       0.00 (0.00%)     NaNx  
90th_percentile_picture_cache_memory              0.00 (0.00%)       0.00 (0.00%)     NaNx  
99th_percentile_picture_cache_memory              0.00 (0.00%)       0.00 (0.00%)     NaNx  
worst_picture_cache_memory                        0.00 (0.00%)       0.00 (0.00%)     NaNx  
new_gen_gc_count                                 28.00 (0.00%)      16.00 (12.50%)   1.75x  
old_gen_gc_count                                  0.00 (0.00%)       0.50 (173.21%)  0.00x  
```

And results for the "dynamic" version of the benchmark:

```
═══════════╡ ••• Formatted summary for "ABresults.dynamic.json" ••• ╞═══════════

                   Score                     Average A (noise)  Average B (noise)  Speed-up
average_frame_build_time_millis                  10.36 (0.91%)      10.36 (0.95%)   1.00x  
worst_frame_build_time_millis                    75.79 (2.26%)      59.28 (3.59%)   1.28x  
90th_percentile_frame_build_time_millis          10.88 (0.62%)      11.10 (0.13%)   0.98x  
99th_percentile_frame_build_time_millis          12.15 (3.12%)      20.73 (72.73%)  0.59x  
average_frame_rasterizer_time_millis             16.07 (0.43%)      16.55 (0.34%)   0.97x  
worst_frame_rasterizer_time_millis               25.29 (13.25%)     25.49 (4.35%)   0.99x  
90th_percentile_frame_rasterizer_time_millis     16.65 (0.70%)      16.92 (0.39%)   0.98x  
99th_percentile_frame_rasterizer_time_millis     20.61 (4.29%)      21.40 (2.24%)   0.96x  
average_layer_cache_count                         0.00 (0.00%)       0.00 (0.00%)    NaNx  
90th_percentile_layer_cache_count                 0.00 (0.00%)       0.00 (0.00%)    NaNx  
99th_percentile_layer_cache_count                 0.00 (0.00%)       0.00 (0.00%)    NaNx  
worst_layer_cache_count                           0.00 (0.00%)       0.00 (0.00%)    NaNx  
average_layer_cache_memory                        0.00 (0.00%)       0.00 (0.00%)    NaNx  
90th_percentile_layer_cache_memory                0.00 (0.00%)       0.00 (0.00%)    NaNx  
99th_percentile_layer_cache_memory                0.00 (0.00%)       0.00 (0.00%)    NaNx  
worst_layer_cache_memory                          0.00 (0.00%)       0.00 (0.00%)    NaNx  
average_picture_cache_count                       0.00 (0.00%)       0.00 (0.00%)    NaNx  
90th_percentile_picture_cache_count               0.00 (0.00%)       0.00 (0.00%)    NaNx  
99th_percentile_picture_cache_count               0.00 (0.00%)       0.00 (0.00%)    NaNx  
worst_picture_cache_count                         0.00 (0.00%)       0.00 (0.00%)    NaNx  
average_picture_cache_memory                      0.00 (0.00%)       0.00 (0.00%)    NaNx  
90th_percentile_picture_cache_memory              0.00 (0.00%)       0.00 (0.00%)    NaNx  
99th_percentile_picture_cache_memory              0.00 (0.00%)       0.00 (0.00%)    NaNx  
worst_picture_cache_memory                        0.00 (0.00%)       0.00 (0.00%)    NaNx  
new_gen_gc_count                                 30.50 (14.94%)     15.50 (10.70%)  1.97x  
old_gen_gc_count                                  0.00 (0.00%)       0.00 (0.00%)    NaNx  
```

**Comment by zanderso** [comment] 2022-04-12 18:17
Would a good summary of these numbers be that we are struggling to reproduce the regression?

**Comment by flar** [comment] 2022-04-12 19:11
We're definitely seeing the difficulty in reproducing perf regressions using manual techniques. If only these benchmarks had been in position before the commit was landed we would have a better view via the statistical analysis of skia perf.

**Comment by chinmaygarde** [comment] 2022-04-18 17:34
@dnfield Per my reading of the comment threads, we are still having trouble reproducing this reliably. Is that right? A speculative fix forward could be to pass the gradient information by reference but I hesitate to commit to that approach before getting more reliable numbers.

I am not sure this is a P2 (Zach is OOO this week) based on the internal priorities. Keeping it put till I get better information.

**Comment by chinmaygarde** [comment] 2022-04-25 17:44
We can't reproduce this and the internal priorities are fairly low. We can investigate passing color source argument information by reference as a matter of course. But lowering the priority of this issue.

**Comment by jonahwilliams** [comment] 2024-08-13 03:55
Closing as obsolete

**Closed by jonahwilliams** 2024-08-13 03:55 UTC
Labels: engine, c: performance, customer: money (g3), perf: speed, P2, team-engine, triaged-engine
