### ISSUE TITLE
we should be building x86 artifacts for android, not x64 ones 

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2898] opened 2016-03-25 17:37 UTC
Related to https://github.com/flutter/flutter/issues/2642, I think we need to build our android emulator artifacts for x86, not x86-64 (x64). Running `adb shell getprop ro.product.cpu.abi` against the android emulator, genymotion, and xamarin all return `x86`, and when trying to run on an emulator, I see the error message:

```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.example.flutter_sunflower-1/lib/x86/libsky_shell.so" is 64-bit instead of 32-bit
```

**Comment by devoncarew** [comment] 2016-03-25 17:42
We're currently building for (and uploading to) android-x64 (https://chromium.googlesource.com/chromium/tools/build/+/master/scripts/slave/recipes/flutter/engine.py#93).

**Comment by jason-simmons** [comment] 2016-04-07 19:31
The Android emulator can support 32-bit or 64-bit x86 system images.  I think we should continue building for x86-64.

**Comment by sethladd** [comment] 2016-04-07 19:34
> The Android emulator can support 32-bit or 64-bit x86 system images.

Confirmed this yesterday.

However, it's not clear to me if GenyMotion (a very popular android emulator) is x86 only (or not).

**Comment by spierce7** [comment] 2016-04-08 02:21
I just pulled the latest from alpha branch, and I'm trying to run one of the sample apps on genymotion. Here's my output:

```
spierce7:myapp spierce7$ flutter run
Downloading Dart SDK 1.16.0-dev.3.0...
######################################################################## 100.0%
Building flutter tool...
Downloading engine package sky_engine...      2.5s
Downloading engine package sky_services...    1.0s
Downloading engine artifacts android-arm...   5.8s
Downloading engine artifacts android-x64...   9.6s
Downloading engine artifacts ios...           7.9s
Downloading engine artifacts darwin-x64...    3.6s
Installing app.apk on device.
Running lib/main.dart on Google Nexus 5, 5 1 0, API 22, 1080x1920...
error: Unable to find Dart library 'package:mojo_services/mojo/ui/view_containers.mojom.dart'.
Failed to run the Flutter compiler. Exit code: 1

Oops; flutter has exited unexpectedly.
Crash report written to flutter_03.log; please let us know at https://github.com/flutter/flutter/issues.
spierce7:myapp spierce7$ flutter run
Installing app.apk on device.
Running lib/main.dart on Google Nexus 5, 5 1 0, API 22, 1080x1920...
error: Unable to find Dart library 'package:mojo_services/mojo/ui/view_containers.mojom.dart'.
Failed to run the Flutter compiler. Exit code: 1

Oops; flutter has exited unexpectedly.
Crash report written to flutter_04.log; please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by abarth** [comment] 2016-04-08 03:17
You might need to run `pub get` to update your dependent packages.  The tool is supposed to do that for you if you run `flutter upgrade`.  We should find a way to check the state of the current directory and suggest this fix.

@devoncarew I would have expected `flutter run` to run pub get automatically.  Maybe it should consider the modified time on the flutter tools stamp file to decide whether to run pub get?

**Comment by abarth** [comment] 2016-04-08 03:32
https://github.com/flutter/flutter/pull/3206 <--- Teaches the tool to run `pub get` automatically in this situation.

**Comment by spierce7** [comment] 2016-04-08 04:13
Ran `pub get`, and then tried again. Slightly different output, but same result:

```
spierce7:myapp spierce7$ flutter run
Building APK...
Warning: signing the APK using the debug keystore.
Generated APK to build/app.apk.
Installing app.apk on device.
Running lib/main.dart on Google Nexus 5, 5 1 0, API 22, 1080x1920...
Starting: Intent { act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x20000000 cmp=com.yourcompany.myapp/org.domokit.sky.shell.SkyActivity (has extras) }
Error type 3
Error: Activity class {com.yourcompany.myapp/org.domokit.sky.shell.SkyActivity} does not exist.
Error running application on Google Nexus 5, 5 1 0, API 22, 1080x1920.
```

**Comment by eseidelGoogle** [comment] 2016-04-08 19:26
@spierce7 This looks expected to me.  There are still a few things missing.

- [ ] flutter run does not know how to detect the right abi of the device and switch between prebuilt engines (FYI @devoncarew) `adb shell getprop ro.product.cpu.abilist` or `adb shell getprop ro.product.cpu.abi` will do so, we just need to teach the `flutter` tool to call that and use that info.
- [ ] We're only uploading x86-64 artifacts, not x86-32, @jason-simmons and I spoke about this yesterday, there are probably some minor fixes to make to our BUILD.gn files or sky/tools/gn wrapper to make building Android x86-32 easy, once that's done I can teach the bots how to do so.

**Comment by eseidelGoogle** [comment] 2016-05-02 22:26
@jason-simmons and I spoke about this today, I believe he's willing to push this over the finish line, so that 32-bit emulators work correctly.

**Comment by eseidelGoogle** [comment] 2017-01-19 17:19
Looking at our infra bots, it looks like we're building and uploading both x86 and x86-64 for Android:
https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py#96

**Comment by eseidelGoogle** [comment] 2017-01-19 17:23
I see x86 artifacts, debug only: https://storage.googleapis.com/flutter_infra/flutter/2efc78cc24eac9439a5315ed9333fa8599aab3a1/android-x86/artifacts.zip

**Comment by jakobr-google** [comment] 2017-01-20 09:50
Yep, we have both x86 and x64 debug artifacts for android. We'll need to add profile and release artifacts, too, for the gradle work.

@jason-simmons do you want to own this, or should I take it?

**Comment by eseidelGoogle** [comment] 2017-01-20 15:25
We've intentionally not added --release artifacts for non-shipping configurations (e.g. desktops, emulators).  One could argue that there are x86 Android shipping configurations (devices), but last time I checked the usage numbers on those were very low, maybe that's changed?

Looks like it's 1.5%: http://hwstats.unity3d.com/mobile/cpu.html  Many of them support arm emulation too last I knew.

**Comment by Hixie** [comment] 2017-01-22 04:48
1.7% for Android based on that page. As of 2015, there were apparently 1.4 billion Android devices, so that's over 23 million potential users right there.

**Comment by mit-mit** [comment] 2017-02-28 15:01
@jason-simmons are you working on this one?

**Comment by jason-simmons** [comment] 2017-02-28 17:41
I'm not currently involved in this - feel free to assign it elsewhere

**Comment by eseidelGoogle** [comment] 2017-04-11 22:18
I believe this can be replaced by #9253 which is more clear on the topic.  We should provide both x86 and x64 build products.

**Closed by eseidelGoogle** 2017-04-11 22:18 UTC
Labels: dev: tool, new feature, temp: revisit, ▣ platform-android
