### ISSUE TITLE
[web] flutter website doesn't resize  properly when zoomed in/out and resizing window on desktop 

### ISSUE THREAD

**Issue by tanharpatel** [flutter/flutter#77084] opened 2021-03-02 19:30 UTC
I have deployed flutter website, its working fine but when I try to zoom the screen it doesn't work as expected.

I come across some cocoon site which is also behaving as my website is. 

| **How the actual site looks like** | **The site after zoom in** |
| ------------------------------------------------------------------- | ------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/47564751/109703250-4021f480-7bbb-11eb-9d8b-8fa9f14c2c27.png) | ![image](https://user-images.githubusercontent.com/47564751/109703167-2c768e00-7bbb-11eb-9fa4-5863ef916c3e.png) |

Is their any way to resolve it???

Thanks in advance.

**Comment by nilsreichardt** [comment] 2021-03-02 23:25
Which flutter version do you use and can you provide a reproducible code sample?

**Comment by tanharpatel** [comment] 2021-03-03 05:07
@nilsreichardt I am using ```flutter version 1.27``` and the minimal reproducible code sample is: 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    ),
 );
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      color: const Color(0xFF1a1a1a),
      child: Scaffold(
        backgroundColor: Colors.blue,
        body: Stack(
          children: [
            Positioned(
              left: MediaQuery.of(context).size.height * 0.2,
              right: MediaQuery.of(context).size.height * 0.1,
              top: MediaQuery.of(context).size.height * 0.15,
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.5,
                    child: Text("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", style: TextStyle(color:Colors.white)),
                  ),
                  SizedBox(width: MediaQuery.of(context).size.width * 0.02),
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.2,
                    child: Center(
                      child: Text("Hello\nGood Morning", style: TextStyle(color:Colors.white)),
                  ),
                ),
               ],
              ),
            ),
          ],
        ),
       ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2021-03-03 08:12
Hi @tanharpatel 
Thanks for filing the issue, I'm unable to reproduce it on macOS or Windows


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    ),
  );
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      color: const Color(0xFF1a1a1a),
      child: Scaffold(
        backgroundColor: Colors.blue,
        body: Stack(
          children: [
            Positioned(
              left: MediaQuery.of(context).size.height * 0.2,
              right: MediaQuery.of(context).size.height * 0.1,
              top: MediaQuery.of(context).size.height * 0.15,
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.5,
                    child: Text(
                        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
                        style: TextStyle(color: Colors.white)),
                  ),
                  SizedBox(width: MediaQuery.of(context).size.width * 0.02),
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.2,
                    child: Center(
                      child: Text("Hello\nGood Morning",
                          style: TextStyle(color: Colors.white)),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.175, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-9.0.pre.175 at /Users/tahatesser/Code/flutter_master
    • Framework revision 97295dc9a8 (3 hours ago), 2021-03-03 00:19:03 -0500
    • Engine revision cd0e54348b
    • Dart version 2.13.0 (build 2.13.0-93.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.4
    • iPhone 12 (mobile)   • 948EC106-78EE-4A69-8D31-83C00E6419DE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 11.2.2 20D80
      darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome
      88.0.4324.192

• No issues found!
```

</details>

Can you please provide your `flutter doctor -v` and which browser you're using? 
Thank you

**Comment by tanharpatel** [comment] 2021-03-03 08:40
Hello @TahaTesser 
Thank you for your valuable response.

I am using Chrome on Windows. And the problem persists in release mode.

<details>
<summary> flutter doctor -v </summary>

```bash

[√] Flutter (Channel master, 1.27.0-2.0.pre.103, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.27.0-2.0.pre.103 at C:\flutter
    • Framework revision f49956598b (2 weeks ago), 2021-02-16 00:56:06 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Tanha Patel\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Tanha Patel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Tanha Patel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.56

• No issues found!

```

**Comment by TahaTesser** [comment] 2021-03-03 09:39
Hi @nilsreichardt 
You seem to be on 2 weeks `master`, for `master` channel it's quite old
I cannot reproduce this issue on the latest `master` channel.
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`
Thank you

**Comment by tanharpatel** [comment] 2021-03-03 13:37
Hey @TahaTesser 

I am on latest master channel. But still I am facing issue when I zoom.

<details>
<summary> flutter doctor -v </summary>

```dart

[√] Flutter (Channel master, 1.27.0-9.0.pre.176, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.27.0-9.0.pre.176 at C:\flutter
    • Framework revision dff42b8ee1 (5 hours ago), 2021-03-03 03:14:02 -0500
    • Engine revision cd0e54348b
    • Dart version 2.13.0 (build 2.13.0-93.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Tanha Patel\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Tanha Patel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Tanha Patel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.56

• No issues found!
```
</details>

Thanks!

**Comment by TahaTesser** [comment] 2021-03-04 08:09
Hi @nilsreichardt 
There is a precise zoom out to reproduce, if zoomed out quickly it corrects itself, then zoom a bit more, and then issues show up
Here I managed to zoom out exactly to reproduce. Only reproduces in Canvaskit render 


### Preview
| Canvaskit | HTML | 
| --------------- | --------------- |
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/109931191-8af05900-7cee-11eb-8293-56a75423bcd8.gif) | ![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/109931177-875cd200-7cee-11eb-9a45-0e5a8e5e96b2.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    ),
  );
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      color: const Color(0xFF1a1a1a),
      child: Scaffold(
        backgroundColor: Colors.blue,
        body: Stack(
          children: [
            Positioned(
              left: MediaQuery.of(context).size.height * 0.2,
              right: MediaQuery.of(context).size.height * 0.1,
              top: MediaQuery.of(context).size.height * 0.15,
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.5,
                    child: Text(
                        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
                        style: TextStyle(color: Colors.white)),
                  ),
                  SizedBox(width: MediaQuery.of(context).size.width * 0.02),
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.2,
                    child: Center(
                      child: Text("Hello\nGood Morning",
                          style: TextStyle(color: Colors.white)),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.0.0 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 60bd88df91 (15 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.97, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.1.0-11.0.pre.97 at C:\Users\Taha\Code\flutter_master
    • Framework revision c14c8d8177 (2 hours ago), 2021-03-03 21:40:34 -0800
    • Engine revision 72bbc5d92c
    • Dart version 2.13.0 (build 2.13.0-93.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```

</details>


Thank you

**Comment by nilsreichardt** [comment] 2021-03-04 08:16
Hi @TahaTesser, I am not effected and not the author of this issue 😅 I just wanted to help you to get more information 👍

**Comment by tanharpatel** [comment] 2021-03-04 08:24
Hi @TahaTesser is there any way to fix it? Other than defining web renderer explicitly??

**Comment by tanharpatel** [comment] 2021-03-04 08:24
Hi @TahaTesser is there any way to fix it? Other than defining web renderer explicitly??

Thank you.

**Comment by ConcenTech** [comment] 2021-03-06 18:55
@TahaTesser 

This also happens with html render

![Screenshot 2021-03-06 185250](https://user-images.githubusercontent.com/70274454/110217677-4828af80-7ead-11eb-9493-7b2ea6d4e1e6.png)

<Details>
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.844], locale en-GB)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (2 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\kgcar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\kgcar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
</Details>

**Comment by vigneshksaithal** [comment] 2021-03-09 04:40
I am also experiencing same issue with "html" render

**Comment by jlubeck** [comment] 2021-03-23 22:40
I'm not sure it's the same issue (it sounds like it though) but sometimes when my computer goes to sleep, and then it resumes, the site would should up either scaled 2x or scaled down 2x. Very hard to reproduce since it doesn't happen all the time...

**Comment by vigneshksaithal** [comment] 2021-06-04 09:22
Any updates?

**Comment by elliotsayes** [comment] 2021-08-04 03:36
Is there some indication of the circumstances under which this bug appears? Or how long it typically takes for a P3 to be resolved?

Are there any work-arounds? The HTML renderer has inconsistent layout with the CanvasKit renderer so I don't want to switch over to that.

So far the only other option I can find is to disable the zoom hotkeys. However this is only a partial solution as the user is unable to increase zoom, or may still use the broken zoom in the browser menu.

`web/index.html`
```
<script>
  document.addEventListener('wheel', function(e) {
    e.ctrlKey && e.preventDefault();
  }, {
    passive: false,
  });
  window.addEventListener('keydown', function(e) {
    if (event.metaKey || event.ctrlKey) {
      switch (event.key) {
        case '=':
        case '-':
          event.preventDefault();
          break;
      }
    }
  });
</script>
```
Any assistance would be appreciated, as I am wanting to deliver a workable product to my client... it seems flutter web might be a dead end if even the sample project is broken on such a basic feature.

**Comment by Hixie** [comment] 2021-08-07 01:21
Easiest way to repro this is to look at Cocoon (dashboard.flutter.dev) and hit Ctrl+ a few times then Ctrl- a few times. Ctrl+ should make the text bigger (right now it makes it bigger briefly then goes back to normal). Ctrl- should make it smaller (right now it briefly makes it smaller then grows again). In both cases doing it a lot eventually leaves the page in a limbo state where it's grown or shrunk but not properly fit to the screen any more.

**Comment by angelhdz** [comment] 2021-11-05 05:54
I solved this with the command `flutter build web --web-renderer html` to build app or `flutter run web --web-renderer html` to run/debug app.
But it loses quality in **html**. I hope its get fixed for **canvaskit** soon.

**Comment by orestesgaolin** [comment] 2021-12-01 12:28
Do you know if there's a way to disable zoom/scaling with CTRL/CMD and +/- with canvaskit entirely?

**Comment by leossmith** [comment] 2021-12-02 09:41
> Do you know if there's a way to disable zoom/scaling with CTRL/CMD and +/- with canvaskit entirely?

I guess you can do it directly with js by handling keydown for ctrl +/- . This is an old solution i used in old projects and might not still work, but it might help you.

```
$(document).keydown(function(event) {
if (event.ctrlKey==true && (event.which == '61' || event.which == '107' || event.which == '173' || event.which == '109'  || event.which == '187'  || event.which == '189'  ) ) {
        event.preventDefault();
     }
    // 107 Num Key  +
    // 109 Num Key  -
    // 173 Min Key  hyphen/underscore key
    // 61 Plus key  +/= key
});

$(window).bind('mousewheel DOMMouseScroll', function (event) {
       if (event.ctrlKey == true) {
       event.preventDefault();
       }
});
```

**Comment by huvi8161** [comment] 2021-12-06 08:56
@TahaTesser is there any progress with this, we have the same issue with our app?

**Comment by archie-sh** [comment] 2022-02-08 14:37
Hi, 

we use flutter web in production and our users are experiencing this issue? Any plans from the flutter team to tackle it?

**Comment by jpeiffer** [comment] 2022-02-23 15:54
This can also happen if you move the browser window from screen with a high pixel ratio (`window.devicePixelRatio == 2`) to a screen with a standard pixel ratio (`window.devicePixelRatio == 1`) or back.

**Comment by MHatemAbdelhamid** [comment] 2022-03-02 07:49
We are using flutter web for production and we have the same issue with zoom and moving the browser between screens that have different pixel ratio, any plans to resolve it in the near future?

**Comment by regullus** [comment] 2022-03-02 15:28
Hello, we are also using flutter web, already in version: 2.10.2 • channel stable and
the problem persists.

**Comment by Terranic** [comment] 2022-03-03 18:17
Confirming this issue-- Browser zooming completely breaks the layout. Using Flutter 2.10.3

**Comment by phillbrady** [comment] 2022-03-04 17:46
I also have this issue on the latest. Reloading the page at the desired zoom level renders it correctly

**Comment by BrunoGalv** [comment] 2022-03-07 05:35
Any updates?

**Comment by fatduckling** [comment] 2022-03-07 10:16
I too am looking for a possible fix for this please, thank you.

**Comment by yeyomuri** [comment] 2022-03-08 03:46
I have the same problem.

**Comment by Sasha-Andrukhov** [comment] 2022-03-08 11:41
I have the same problem.

**Comment by Ayush-gupta-josh** [comment] 2022-03-09 09:41
I have the same problem

**Comment by regullus** [comment] 2022-03-30 19:16
Thanks DenisovAV, we found a palliative solution after your post.
 
 We included the script below in the index.html to verify if the Zoom was activated, if yes, we performed a reload page.
 
 Unfortunately the entire application is restarted. Which isn't ideal, but it's better than it was getting.
 
 We will appreciate the flutter team's make a definitive fix it.
 
 Add this to your index.html:
 
 <script>
    //for zoom detection
    px_ratio = window.devicePixelRatio || window.screen.availWidth / document.documentElement.clientWidth;
    function isZooming(){
        var newPx_ratio = window.devicePixelRatio || window.screen.availWidth / document.documentElement.clientWidth;
        if(newPx_ratio != px_ratio){
            px_ratio = newPx_ratio;
            console.log("zooming");
            return true;
        }else{
            console.log("just resizing");
            return false;
        }
    }
    window.addEventListener("resize", event => {
      if(isZooming()){
        window.location.reload();
      }
    });
  </script>

**Comment by regullus** [comment] 2022-03-30 20:20
Thanks @DenisovAV, we found a palliative solution after your post.

We included the script below in the index.html to verify if the Zoom was activated, if yes, we performed a reload page.

Unfortunately the entire application is restarted. Which isn't ideal, but it's better than it was getting.

We will appreciate the flutter team's make a definitive fix it.

Add this into your index.html:

```
<script>
  //for zoom detection
  px_ratio = window.devicePixelRatio || window.screen.availWidth / document.documentElement.clientWidth;
  function isZooming(){
      var newPx_ratio = window.devicePixelRatio || window.screen.availWidth / document.documentElement.clientWidth;
      if(newPx_ratio != px_ratio){
          px_ratio = newPx_ratio;
          console.log("zooming");
          return true;
      }else{
          console.log("just resizing");
          return false;
      }
  }
  window.addEventListener("resize", event => {
    if(isZooming()){
      window.location.reload();
    }
  });
</script>
```

**Comment by gururaja-kambala** [comment] 2022-04-21 08:51
I have the same problem.

**Comment by Jonas-Sander** [comment] 2022-04-26 11:25
Shouldn't this also fall under Accessibility as people with poor sight might try to use the zoom functionality to make stuff bigger?

**Comment by linxuebin1990** [comment] 2022-05-07 07:07
I can also reproduce this problem with a simple demo：

https://user-images.githubusercontent.com/3382181/167242310-725f5495-4f8a-4c79-b05f-b76946b782fe.mov

Adding relevant log information to [createOrUpdateSurface in surface.dart ](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/canvaskit/surface.dart#L157), we get the following output：

```dart
if (previousSurfaceSize != null) {
      print("[lxblog] createOrUpdateSurface is call\n"
          "previousSurfaceSize.width = ${previousSurfaceSize!.width} and size.width = ${size.width} \n"
          "previousSurfaceSize.height = ${previousSurfaceSize!.height} and size.height = ${size.height}\n"
          "preDevicePixelRatio = ${_currentDevicePixelRatio} and currentDevicePixelRatio = ${window.devicePixelRatio}");
    }
```

https://user-images.githubusercontent.com/3382181/167242398-b96acbc5-2d27-48b1-96a8-173758a72c67.mov

From the video above, we can see the following line of key logs:
```
[lxblog] createOrUpdateSurface is call
previousSurfaceSize.width = 2284 and size.width = 2283.9999883227865 
previousSurfaceSize.height = 1862 and size.height = 1861.999975087907
preDevicePixelRatio = 2 and currentDevicePixelRatio = 1.7999999523162842
```
Due to the problem of precision, size.width is not equal to previousSurfaceSize.width, but smaller than previousSurfaceSize.width. height has the same problem.
At the same time, the value of DevicePixelRatio has changed.

``` dart
CkSurface createOrUpdateSurface(ui.Size size) {
    // ...

    // Step 1, reuse Surface
    final ui.Size? previousSurfaceSize = _currentSurfaceSize;
    if (!_forceNewContext &&
        previousSurfaceSize != null &&
        size.width == previousSurfaceSize.width &&
        size.height == previousSurfaceSize.height) {
      // The existing surface is still reusable.
      if (window.devicePixelRatio != _currentDevicePixelRatio) {
        _updateLogicalHtmlCanvasSize();
      }
      return _surface!;
    }

    _currentDevicePixelRatio = window.devicePixelRatio;

    // Step 2, recreate Canvas
    final ui.Size? previousCanvasSize = _currentCanvasPhysicalSize;
    if (_forceNewContext ||
        previousCanvasSize == null ||
        size.width > previousCanvasSize.width ||
        size.height > previousCanvasSize.height) {
      final ui.Size newSize = previousCanvasSize == null ? size : size * 1.4;

      // ...
      _createNewCanvas(newSize);
      _currentCanvasPhysicalSize = newSize;
    }

    _currentSurfaceSize = size;
    _translateCanvas();
    return _surface = _createNewSurface(size);
  }

```
As can be seen from the above simplified code combined with the log, step 1 and step 2 are not executed, so `_updateLogicalHtmlCanvasSize` is not called to deal with the change of DevicePixelRatio.

**Comment by xu-baolin** [comment] 2022-05-07 07:12
> e value of DevicePixelRatio has changed

Would you like to post a PR to fix this?

**Comment by linxuebin1990** [comment] 2022-05-07 07:14
> > e value of DevicePixelRatio has changed
> 
> Would you like to post a PR to fix this?

Yes, pr is being prepared.

**Comment by xu-baolin** [comment] 2022-05-07 07:17
> > > e value of DevicePixelRatio has changed
> > 
> > 
> > Would you like to post a PR to fix this?
> 
> Yes, pr is being prepared.

Nice, assign to you.

**Comment by HeinrichJanzing** [comment] 2022-05-23 19:39
I just tested this on master and it seems the merged fix is only a partial one. In case the surface size is still valid (i.e. no window size change, only device pixel ratio change), there's an early exit happening here in lib\src\engine\canvaskit\surface.dart, `Surface.createOrUpdateSurface`:

```dart
    // Check if the window is the same size as before, and if so, don't allocate
    // a new canvas as the previous canvas is big enough to fit everything.
    final ui.Size? previousSurfaceSize = _currentSurfaceSize;
    if (!_forceNewContext &&
        previousSurfaceSize != null &&
        size.width == previousSurfaceSize.width &&
        size.height == previousSurfaceSize.height) {
      // The existing surface is still reusable.
      if (window.devicePixelRatio != _currentDevicePixelRatio) {
        _updateLogicalHtmlCanvasSize(); // <-- should also call `_translateCanvas()` here!
      }
      return _surface!;
    }
```
Interestingly, as @linxuebin1990 noticed, `size.width` and `size.height` often suffer from precision issues, making them subtly different, causing this path to not be taken as often as expected. When it _is_ taken, the `devicePixelRatio` change is detected, the logical size of the canvas is updated to match, but the canvas' translation, intended to compensate for the canvas being oversized, isn't updated. This translation is expressed in logical pixels and thus should also be updated. 

If this doesn't happen, it causes the Flutter UI to appear shifted vertically in the browser's viewport. This can be reproduced in any Flutter web app by using Ctrl+mousewheel to change the zoom level. Sooner or later it pops up. Luckily, changing the zoom level again or resizing the window does trigger the call to `_translateCanvas()` and fixes things.

So, there should be a call to `_translateCanvas()` next to `_updateLogicalHtmlCanvasSize()`.

I would contribute a patch but it seems to take a while to get my CLA in order.

**Comment by linhdoan24** [comment] 2022-05-24 14:46
i still have this problem when zoom out + zoom in.
Flutter 3.0.1

**Comment by fatduckling** [comment] 2022-05-25 03:13
Hi @HeinrichJanzing 
I've created https://github.com/flutter/flutter/issues/104573 for the fix and added a pull request (as this issue is closed). 
Thanks

**Comment by fatduckling** [comment] 2022-05-30 08:18
Hi team,
I have created a pull request https://github.com/flutter/engine/pull/33695 to call `_translateCanvas()` after `_updateLogicalHtmlCanvasSize()`. Please check, thanks

**Comment by PongsiriTK** [comment] 2022-06-17 10:27
Any updates?

**Comment by lucas-goldner** [comment] 2022-07-10 09:06
Also waiting for this to be fixed...

**Comment by lextotan** [comment] 2022-07-13 11:05
first solutions: run on terminal : flutter run -d chrome --web-renderer html
seconds solutions: if u use android studio , click main.dart(top left run button) Edit configurations. You will see Additional run args: --web-renderer html   
apply > ok > run

**Comment by andrelrf1** [comment] 2022-07-23 16:52
> first solutions: run on terminal : flutter run -d chrome --web-renderer html seconds solutions: if u use android studio , click main.dart(top left run button) Edit configurations. You will see Additional run args: --web-renderer html apply > ok > run

That didn't work one hundred percent, because when I zoom in with the touchpad the problem still happens unfortunately.

**Comment by lextotan** [comment] 2022-07-23 17:11
> 

Bro, can u try on new flutter project. Channel stable

**Comment by andrelrf1** [comment] 2022-07-23 17:28
> Bro, can u try on new flutter project. Channel stable

That's what I did. I'm using the latest stable version of Flutter. So when I zoom with ctrl + mouse scroll or using the browser's zoom option the page works as expected, but when I use the touchpad/trackpad gesture to zoom the problem still happens.

**Closed** 2022-08-05 21:43 UTC
Labels: severe: regression, engine, customer: crowd, platform-web, severe: rendering, e: web_canvaskit, has reproducible steps, P3, found in release: 2.0, found in release: 2.1, customer: samehere
