### ISSUE TITLE
[tool_crash] NoSuchMethodError: The method 'toFilePath' was called on null.Receiver: nullTried calling: toFilePath()

### ISSUE THREAD

**Issue by reob-info** [flutter/flutter#53810] opened 2020-04-02 06:24 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:28:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:85:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#15     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, v1.15.17, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.15.17 at /home/fernando/opt/flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.162
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by reob-info** [comment] 2020-04-02 06:28
I am trying to run the test created by the command **flutter create teste**.
I want to use flutter to make a web app only, then I have not installed anything to develop to mobile.
Thanks.

**Comment by TahaTesser** [comment] 2020-04-02 07:57
Duplicate of [#52914](https://github.com/flutter/flutter/issues/52914)
This is fixed [comment](https://github.com/flutter/flutter/issues/52914#issuecomment-601822368)

**Comment by yecanlin** [comment] 2020-04-02 07:58
upgrade to flutter stable version, and run :flutter doctor.
then switch back to flutter beta versin , and run: flutter doctor , also run: flutter config --enable-web.
I solved this problem ty this way.
you can try it by this way.

**Closed by TahaTesser** 2020-04-02 07:57 UTC

**Comment by reob-info** [comment] 2020-04-02 17:18
I will try It. Thanks.

Em qui, 2 de abr de 2020 04:58, yecanlin <notifications@github.com>
escreveu:
