### ISSUE TITLE
%5Btool_crash%5D RPCError

### ISSUE THREAD

**Issue by Njibamum** [flutter/flutter#153315] opened 2024-08-12 20:45 UTC
%23%23 Command%0A%60%60%60sh%0Aflutter run%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0ARPCError%0A%60%60%60console%0A%0A%60%60%60%0A%60%60%60console%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Flutter %28Channel stable%2C 3.24.0%2C on macOS 15.1 24B5009l darwin-arm64%2C locale en-US%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Flutter version 3.24.0 on channel stable at %2FUsers%2Fm2%2Fdevelopment%2Fflutter%0A    %1B%5B32m%E2%80%A2%1B%5B39m Upstream repository https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A    %1B%5B32m%E2%80%A2%1B%5B39m Framework revision 80c2e84975 %2813 days ago%29%2C 2024-07-30 23%3A06%3A49 %2B0700%0A    %1B%5B32m%E2%80%A2%1B%5B39m Engine revision b8800d88be%0A    %1B%5B32m%E2%80%A2%1B%5B39m Dart version 3.5.0%0A    %1B%5B32m%E2%80%A2%1B%5B39m DevTools version 2.37.2%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Android toolchain - develop for Android devices %28Android SDK version 35.0.0%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Android SDK at %2FUsers%2Fm2%2FLibrary%2FAndroid%2Fsdk%0A    %1B%5B32m%E2%80%A2%1B%5B39m Platform android-35%2C build-tools 35.0.0%0A    %1B%5B32m%E2%80%A2%1B%5B39m ANDROID_HOME %3D %2FUsers%2Fm2%2FLibrary%2FAndroid%2Fsdk%0A    %1B%5B32m%E2%80%A2%1B%5B39m ANDROID_SDK_ROOT %3D %2FUsers%2Fm2%2FLibrary%2FAndroid%2Fsdk%0A    %1B%5B32m%E2%80%A2%1B%5B39m Java binary at%3A %2FApplications%2FAndroid Studio.app%2FContents%2Fjbr%2FContents%2FHome%2Fbin%2Fjava%0A    %1B%5B32m%E2%80%A2%1B%5B39m Java version OpenJDK Runtime Environment %28build 17.0.11%2B0-17.0.11b1207.24-11852314%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m All Android licenses accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Xcode - develop for iOS and macOS %28Xcode 15.4%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Xcode at %2FApplications%2FXcode.app%2FContents%2FDeveloper%0A    %1B%5B32m%E2%80%A2%1B%5B39m Build 15F31d%0

**Comment by huycozy** [comment] 2024-08-13 05:36
Decoded content above:

## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console

```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.0, on macOS 15.1 24B5009l darwin-arm64, locale en-US)
 [32m•[39m Flutter version 3.24.0 on channel stable at /Users/m2/development/flutter
 [32m•[39m Upstream repository https://github.com/flutter/flutter.git
 [32m•[39m Framework revision 80c2e84 (13 days ago), 2024-07-30 23:06:49 +0700
 [32m•[39m Engine revision b8800d88be
 [32m•[39m Dart version 3.5.0
 [32m•[39m DevTools version 2.37.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
 [32m•[39m Android SDK at /Users/m2/Library/Android/sdk
 [32m•[39m Platform android-35, build-tools 35.0.0
 [32m•[39m ANDROID_HOME = /Users/m2/Library/Android/sdk
 [32m•[39m ANDROID_SDK_ROOT = /Users/m2/Library/Android/sdk
 [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
 [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
 [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
 [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
 [32m•[39m Build 15F31d%0

**Comment by huycozy** [comment] 2024-08-13 05:36
Closing this as a duplicate of https://github.com/flutter/flutter/issues/117988

**Closed by huycozy** 2024-08-13 05:36 UTC
Labels: in triage
