### ISSUE TITLE
Exception Caught By widgets library

### ISSUE THREAD

**Issue by 97loser** [flutter/flutter#41893] opened 2019-10-03 06:59 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment] 2019-10-03 09:46
Hello @97loser !

Thank you for posting. 
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-10-03 09:46 UTC
