### ISSUE TITLE
Feature request: Google Maps Shapes

### ISSUE THREAD

**Issue by ViniciusSossela** [flutter/flutter#26008] opened 2019-01-03 11:29 UTC
The plugin should support shapes.

Like this: 
https://developers.google.com/maps/documentation/android-sdk/shapes
https://developers.google.com/maps/documentation/ios-sdk/shapes

**Comment by zoechi** [comment] 2019-01-04 11:49
Is this a duplicate of #17832 ?

**Comment by ViniciusSossela** [comment] 2019-01-08 12:14
> Is this a duplicate of #17832 ?

Looks like it is! Should we close this?

**Comment by csells** [comment] 2020-01-13 20:56
Closed as duplication of #17832

**Comment by darshankawar** [comment] 2021-05-04 10:25
The shapes mentioned in the original issue description are `polyline`, `polygon` and `circle`, which seem to be part of the plugin now:

<img width="485" alt="Screenshot 2021-05-04 at 3 54 00 PM" src="https://user-images.githubusercontent.com/67046386/116990702-1b4c1980-acf1-11eb-83c6-24d7a3dd04a8.png">
<img width="492" alt="Screenshot 2021-05-04 at 3 54 09 PM" src="https://user-images.githubusercontent.com/67046386/116990712-1dae7380-acf1-11eb-9ba9-efe1b3b3e496.png">
<img width="495" alt="Screenshot 2021-05-04 at 3 54 19 PM" src="https://user-images.githubusercontent.com/67046386/116990714-1e470a00-acf1-11eb-90b5-e57f42cd8ac3.png">

Closing this as fixed. If anyone disagrees, write in comments and I'll reopen.

Thanks.

**Closed by darshankawar** 2021-05-04 10:25 UTC
Labels: P4, p: first party, p: maps, plugin, severe: new feature
