### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by Srikanth-Digitalraiz** [flutter/flutter#141273] opened 2024-01-10 14:31 UTC
## Command
```
flutter run --machine --start-paused -d 6LDALZT4UCOZQ4FU --devtools-server-address http://127.0.0.1:9100/ --target /Users/suman/StudioProjects/kaanav_neel/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[!] Flutter (Channel [user-branch], 3.13.9, on macOS 13.6.1 22G313 darwin-x64, locale en-GB)
    ! Flutter version 3.13.9 on channel [user-branch] at /Users/suman/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision d211f42860 (3 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/suman/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.6.1 22G313 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f92f44110e87bad5ff168335c36da6f6053036e6
### Plugins
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_analytics-10.7.4
firebase_analytics_web-0.5.5+11
firebase_auth-4.15.3
firebase_auth_web-5.8.12
firebase_core-2.24.2
firebase_core_web-2.10.0
firebase_crashlytics-3.4.8
firebase_messaging-14.7.9
firebase_messaging_web-3.5.18
flutter_blue-0.8.0
flutter_blue_plus-1.30.5
flutter_local_notifications-16.2.0
flutter_plugin_android_lifecycle-2.0.17
flutter_reactive_ble-5.2.0
image_picker-1.0.5
image_picker_android-0.8.9+1
image_picker_for_web-3.0.1
image_picker_ios-0.8.9
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.0.1
permission_handler_android-11.1.0
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
reactive_ble_mobile-5.2.0
rive_common-0.2.7
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
url_launcher-6.2.2
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.1

**Comment by dam-ease** [comment] 2024-01-10 16:30
Closing this as a duplicate of https://github.com/flutter/flutter/issues/79748

**Closed by dam-ease** 2024-01-10 16:30 UTC
Labels: in triage
