### ISSUE TITLE
My app stuck on splash screen (IOS 13 device) after updating to xcode 11 

### ISSUE THREAD

**Issue by Amr1440** [flutter/flutter#41765] opened 2019-10-02 09:01 UTC
My app stuck on splash screen (IOS 13 device) after updating to xcode 11 without showing any error in logs !!.
Im using flutter 1.9.1+hotfix.4

**Comment by genert** [comment] 2019-10-02 09:20
This seems to happen here as well.

**Comment by ConnorMcGill** [comment] 2019-10-02 09:25
I've been getting a similar error which seems to be connected to a number of exceptions I'm getting while running in verbose mode. These are displayed as followed `Exception attempting to connect to Observatory: WebSocketException: Connection to 'http://127.0.0.1:1029/9JVtRmQcnjk=/ws#' was not upgraded to websocket`

**Comment by genert** [comment] 2019-10-02 12:05
It came out that 2 plugins caused a forever loop in "registerWithRegistrar" function for some reason. Either removing them or adding Swift code library import fixed the issue.

Note, that I am on master channel, for stable channel everything is fine.

```
✓] Flutter (Channel master, v1.10.7-pre.109, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.10.7-pre.109 at /Users/genertorg/flutter
    • Framework revision 056f7244ef (14 hours ago), 2019-10-01 18:09:24 -0400
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/genertorg/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone X • 6D7AD1A4-5621-4A9C-AA4F-1DE5D7B8FFB4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.```

**Comment by escamoteur** [comment] 2019-10-02 13:05
@genert could you please tell us which plugins that were that made the problem?

**Comment by genert** [comment] 2019-10-02 16:59
@escamoteur - This https://github.com/benjamindean/flutter_vibration and our created library - https://github.com/ninjasolutions/flutter_opentok

For some reason, when library missed this line https://github.com/ninjasolutions/flutter_opentok/blob/master/ios/Classes/FlutterOpentokPlugin.m#L2 an endless loop was created...

**Comment by jmagman** [comment] 2019-10-02 18:00
I was just able to run the example app https://github.com/benjamindean/flutter_vibration/tree/master/example with Xcode 11 and iOS 13 and it didn't stick on the splash screen.
Is there some other way to reproduce the issue?

**Comment by genert** [comment] 2019-10-08 10:36
Seems to be resolved. Could not reproduce anymore.

**Comment by escamoteur** [comment] 2019-10-08 11:23
Cool, then I close the issue.

**Closed by escamoteur** 2019-10-08 11:23 UTC
Labels: a: debugging, e: OS Version specific, severe: crash, t: xcode, tool, waiting for customer response, ⌺‬ platform-ios
