### ISSUE TITLE
https://stackoverflow.com/questions/54554053/how-to-fix-platform-exception-error-auth-in-progress-for-flutter-local-authent

### ISSUE THREAD

**Issue by galves93** [flutter/flutter#60699] opened 2020-07-01 15:29 UTC
https://stackoverflow.com/questions/54554053/how-to-fix-platform-exception-error-auth-in-progress-for-flutter-local-authent

--- BEGIN QUOTE ---

This happens on Android. You have to modify your MainActivity to implement FlutterFragmentActivity to use local_auth plugin. Change your code from this (Kotlin on my example):

```
import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

To this:

```
import android.os.Bundle

import io.flutter.app.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

Also you need to add this two lines to your gradle.properties file.

android.useAndroidX=true
android.enableJetifier=true

This error is hard to find since version 0.5.1, because the plugin doesn't throw the right exception, and the documentation doesn't tell you to implement this base class.

--- END OF QUOTE ---

_Originally posted by @crcaicedo in https://github.com/flutter/flutter/issues/27584#issuecomment-508799168_

**Comment by VladyslavBondarenko** [comment] 2020-07-02 06:54
Hi @galves93 
closing as duplicate of https://github.com/flutter/flutter/issues/41119,
and it's said at https://pub.dev/packages/local_auth#android-integration

>Note that local_auth plugin requires the use of a FragmentActivity as opposed to Activity. This can be easily done by switching to use FlutterFragmentActivity as opposed to FlutterActivity in your manifest (or your own Activity class if you are extending the base class).

**Closed by VladyslavBondarenko** 2020-07-02 06:54 UTC

**Comment by galves93** [comment] 2020-07-02 11:09
hi Vladyslav i opened accidentaly, so sorry about this
