### ISSUE TITLE
[video_player]

### ISSUE THREAD

**Issue by ff-frida** [flutter/flutter#112373] opened 2022-09-26 09:27 UTC
ver:2.4.7
iOS16 video has no picture, only sound

iPhone 13pm
iOS 16.0.2

**Comment by danagbemava-nc** [comment] 2022-09-26 13:05
Hi @ff-frida, I believe this is a duplicate of https://github.com/flutter/flutter/issues/111457. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-09-26 13:05 UTC
Labels: in triage
