### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by HardikJain02** [flutter/flutter#102210] opened 2022-04-20 11:22 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2216:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:797:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:816:49)
#5      FlutterVmService.flutterDebugDumpRenderTree (package:flutter_tools/src/vmservice.dart:575:50)
#6      ResidentHandlers.debugDumpRenderTree (package:flutter_tools/src/resident_runner.dart:668:52)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1724:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.628, on Microsoft Windows [Version 10.0.19043.1526], locale en-IN)
    • Flutter version 2.13.0-0.0.pre.628 at C:\Users\jainh\Downloads\flutter_windows_2.10.4-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 88eca6c1ce (15 hours ago), 2022-04-19 13:29:06 -0700
    • Engine revision dbae488f8a
    • Dart version 2.18.0 (build 2.18.0-34.0.dev)
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed

**Comment by danagbemava-nc** [comment] 2022-04-20 12:26
Closing this as duplicate of #98237

**Closed by danagbemava-nc** 2022-04-20 12:26 UTC
Labels: in triage
