### ISSUE TITLE
Text distorted in presence of two platform views 

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46911] opened 2019-12-12 20:47 UTC
https://buganizer.corp.google.com/issues/146142979. cc @chinmaygarde and @cbracken.

**Comment by cbracken** [comment] 2019-12-12 23:21
This looks somewhat similar to previous multitexturing font issues we'd seen on iOS devices (and still do in some cases on iPhone 4S and 5).
See: https://github.com/flutter/flutter/issues/17364

Similar previous issues for ref:
https://github.com/flutter/flutter/issues/13817
https://github.com/flutter/flutter/issues/13087
https://github.com/flutter/flutter/issues/12934

cc'ed @brianosman on the internal issue.

**Comment by Hixie** [comment] 2019-12-18 00:12
This currently seems to be an upstream Skia issue so we do not expect to be directly working on it ourselves. Leaving open for tracking purposes so that we can check on it occasionally to see if progress is being made.

**Comment by cbracken** [comment] 2020-01-08 00:26
We believe this is an upstream Skia issue related to multi-texturing. This is back on our plate to verify whether disabling multi-texturing eliminates the issue and to get back to the Skia team with the answer.

**Comment by chinmaygarde** [comment] 2020-01-13 19:43
Just got back from vacation and working through a backlog. The root cause has **not** been identified yet and the multitexturing hypothesis needs to be verified first by setting the `options.fAllowMultipleGlyphCacheTextures` option to `Enable:kNo` in the [GL surface creation component](https://github.com/flutter/engine/blob/5ef2c7968c7215acaffddd008a8ccabeb7cb6706/shell/gpu/gpu_surface_gl.cc#L48) and checking to see if the issue goes away.

**Comment by kf6gpe** [comment] 2020-01-14 19:13
Workaround on internal thread does not work for all cases; this is blocking our customer. I raised the priority.

**Comment by Hixie** [comment] 2020-01-22 00:03
As of today, Jim on the Skia team is working on this.

**Comment by chinmaygarde** [comment] 2020-01-23 19:51
The cause has been identified as GL context isolation. Across all the bug trackers I was pinged on, this seems to have highest priority. Working on mitigation for this now.

**Comment by chinmaygarde** [comment] 2020-01-23 22:05
Fixed after reverting texture bindings in the embedder. cl/291239009

**Comment by chinmaygarde** [comment] 2020-02-07 20:11
Reopened internally. The current course of action is described in my comment in the internal tracker that I am pasting here in its entirety.

> Instead of playing whack-a-mole with issues of this class, I am going to update the engine to make it so that it never relies on the embedder to maintain OpenGL state. While doing this aggressively would be detrimental to performance, I am going to make it so that this only happens at the transition of control from the embedder to the engine on the render thread. If I move around stuff around a bit, I believe I can ensure that this only happens once per frame. This should not impact performance in any observable way and definitively solve all issues of this class.

**Comment by chinmaygarde** [comment] 2020-02-10 20:13
We believe this is the embedder stomping on the Skia GL context. Removing the skia label for triage.

**Comment by chinmaygarde** [comment] 2020-02-17 23:15
After https://github.com/flutter/engine/pull/16653, the embedder should no longer need to restore OpenGL state before transferring control back to the engine.

**Comment by chinmaygarde** [comment] 2020-02-17 23:21
Will close this issue once the patch lands. There are no pending Flutter deliverables on this front.

**Closed** 2020-02-18 20:51 UTC
Labels: customer: dream (g3), engine, severe: customer blocker
