### ISSUE TITLE
Add ability to make Scrollbar/CupertinoScrollbar draggable without long press

### ISSUE THREAD

**Issue by tablesturn** [flutter/flutter#68799] opened 2020-10-22 16:59 UTC
## Use case

Hello, I am using an infinite (auto-growing) ListView inside a Scrollbar (or CupertinoScrollbar) on Android.
The native-looking scrollbar should be directly draggable for quick scrolling inside the list.

## Problem

Currently, Scrollbar is  not draggable at all. CupertinoScrollbar requires long pressing or dragging to the inside for "grabbing" it.

For a draggable scrollbar (like in a lot of apps), I need to re-implement ScrollBar or use something like [this](https://pub.dev/packages/draggable_scrollbar) which is not (or hard to implement manually) native-looking.

## Proposal

- Add the ability to configure CupertinoScrollBar in a way that no LongPress is needed.
- Add a similar interactivity to ScrollBar.

**Comment by darshankawar** [comment] 2020-10-23 07:00
There's a similar [open](https://github.com/flutter/flutter/issues/31753) feature request, but for desktop. Adding this for mobile.

**Comment by HansMuller** [comment] 2020-10-23 16:11
CC @Piinks

**Comment by Piinks** [comment] 2020-10-23 16:57
Hi @tablesturn I think the CupertinoScrollBar uses a long press gesture to match the native performance of an iOS scrollbar. I believe @justinmc worked on this, is this the expected native behavior?

**Comment by justinmc** [comment] 2020-10-26 20:54
Yes, as far as I'm aware, native iOS scrollbars cannot be draggable without the longpress, so Flutter behaves the same way.  I think this should be closed as "working as intended", but let me know if I'm wrong and I'll reopen.

Desktop will definitely have to support this, but that's being tracked in https://github.com/flutter/flutter/issues/31753 as mentioned.

@tablesturn If you need this on mobile right now, you could probably copy the CupertinoScrollbar [code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/scrollbar.dart) into your project and modify it, since it's not super long.  Obviously not a perfect solution, though.

**Closed by justinmc** 2020-10-26 20:54 UTC
Labels: f: cupertino, f: material design, f: scrolling, framework, passed first triage, proposal, severe: new feature
