### ISSUE TITLE
Camera is not working for Android 13 OS, (Target SDK: 33)

### ISSUE THREAD

**Issue by tejaswinidev24** [flutter/flutter#117259] opened 2022-12-17 08:07 UTC
camera: ^0.10.0+5

Flutter version 3.0.5
Dart version 2.17.6
Platform android-33, build-tools 33.0.0

Error Log:
======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building CapturePhotoCamera(dirty, dependencies: [MediaQuery], state: _CapturePhotoCameraState#e8c2c):
The getter 'value' was called on null.
Receiver: null
Tried calling: value

**Comment by exaby73** [comment] 2022-12-19 07:27
Hello @tejaswinidev24. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by tejaswinidev24** [comment] 2022-12-19 11:10
Hi @exaby73 

Thank you for addressing this issue,

<details><summary>Sample Code</summary>
<p>

```
import 'dart:async';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:sample/ResourceConstants/color_constants.dart';
import 'package:sample/ResourceConstants/image_constants.dart';
import 'package:sample/Utils/app_language_util.dart';
import 'package:sample/Utils/loading_util.dart';
import 'package:sample/Utils/print_util.dart';
import 'package:sample/Utils/toast_util.dart';
import 'package:sizer/sizer.dart';
import 'dart:math' as math;

class CapturePhotoCamera extends StatefulWidget {
  const CapturePhotoCamera({
    Key? key,
  }) : super(key: key);

  @override
  _CapturePhotoCameraState createState() => _CapturePhotoCameraState();
}

/// Returns a suitable camera icon for [direction].
IconData getCameraLensIcon(CameraLensDirection direction) {
  switch (direction) {
    case CameraLensDirection.back:
      return Icons.camera_rear;
    case CameraLensDirection.front:
      return Icons.camera_front;
    case CameraLensDirection.external:
      return Icons.camera;
    default:
      throw ArgumentError('Unknown lens direction');
  }
}

void logError(String code, String? message) {
  if (message != null) {
    PrintUtil().printMsg('Error: $code\nError Message: $message');
  } else {
    PrintUtil().printMsg('Error: $code');
  }
}

class _CapturePhotoCameraState extends State<CapturePhotoCamera>
    with WidgetsBindingObserver, TickerProviderStateMixin {
  CameraController? controller;
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  List<CameraDescription> cameras = [];
  CameraDescription? selectedCamera;

  String txtSelectCamera = "Select a camera first!";
  String? somethingWentWrongText = "Something went wrong!!";

  ValueNotifier<bool> hideAppBar = ValueNotifier(false);

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    getAvaiableCamera();
  }

  getAvaiableCamera() async {
    cameras = await availableCameras();
    if (cameras.isNotEmpty) {
      if (cameras.isNotEmpty) {
        selectedCamera = cameras[1];
        onNewCameraSelected(selectedCamera!);
      } else {
        selectedCamera = cameras[0];
        onNewCameraSelected(selectedCamera!);
      }
    }

    setState(() {});
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    controller?.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    final CameraController cameraController = controller!;

    // App state changed before we got the chance to initialize.
    if (!cameraController.value.isInitialized) {
      return;
    }

    if (state == AppLifecycleState.inactive) {
      cameraController.dispose();
    } else if (state == AppLifecycleState.resumed) {
      onNewCameraSelected(cameraController.description);
    }
  }

  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();

  void showInSnackBar(String message) {
    ToastUtil().showSnackBar(context: context, message: message, isError: true);
  }

  void _showCameraException(CameraException e) {
    logError(e.code, e.description!);
  }

  void onNewCameraSelected(CameraDescription cameraDescription) async {
    await controller?.dispose();
    final CameraController cameraController = CameraController(
      cameraDescription,
      ResolutionPreset.medium,
    );
    controller = cameraController;
    // If the controller is updated then update the UI.
    cameraController.addListener(() {
      if (mounted) setState(() {});
      if (cameraController.value.hasError) {}
    });

    try {
      await cameraController.initialize();
    } on CameraException catch (e) {
      _showCameraException(e);
    }

    if (mounted) {
      setState(() {});
    }
  }

  backHandle() async {
    controller?.dispose();
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () => backHandle(),
      child: SafeArea(
        child: Scaffold(
          resizeToAvoidBottomInset: false,
          key: _scaffoldKey,
          body: Stack(
            children: [
              Positioned(
                child: Container(
                  alignment: Alignment.center,
                  child: cameraScreen(),
                ),
              ),
              Positioned(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    ValueListenableBuilder<bool>(
                      valueListenable: hideAppBar,
                      builder: (context, snapshot, child) {
                        return (hideAppBar.value == false)
                            ? AppBar(
                                backgroundColor: Colors.black.withOpacity(0.10),
                                automaticallyImplyLeading: false,
                                elevation: 0.0,
                                centerTitle: true,
                                leading: InkWell(
                                  onTap: () async {
                                    backHandle();
                                  },
                                  child: Padding(
                                    padding: EdgeInsets.all(8.sp),
                                    child: Icon(
                                      Icons.arrow_back_ios,
                                      size: 16.0.sp,
                                      color: Colors.white,
                                    ),
                                  ),
                                ),
                                actions: [cameraSwitch()],
                              )
                            : const SizedBox(
                                width: 0.0,
                                height: 0.0,
                              );
                      },
                    ),
                  ],
                ),
              ),
              Positioned(
                bottom: 0.0,
                child: SingleChildScrollView(
                  child: Container(
                    width: SizerUtil.width,
                    padding: EdgeInsets.symmetric(
                      vertical: 12.sp,
                    ),
                    alignment: Alignment.bottomCenter,
                    child: cameraCapture(),
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }

  Widget cameraScreen() {
    final CameraController cameraController = controller!;
    if (!cameraController.value.isInitialized) {
      return Container(
        width: SizerUtil.width,
        height: SizerUtil.height,
        color: Colors.black,
        child: Center(
          child: Text('Loading'),
        ),
      );
    } else {
      return cameraWidgetOldVersion(context, cameraController);
    }
  }

  /* Camera package version v0.7.0 and above */
  Widget cameraWidgetNewVersion(context, cameraController) {
    var camera = cameraController.value;
    // fetch screen size
    final size = MediaQuery.of(context).size;

    // calculate scale depending on screen and camera ratios
    // this is actually size.aspectRatio / (1 / camera.aspectRatio)
    // because camera preview size is received as landscape
    // but we're calculating for portrait orientation
    var scale = size.aspectRatio * camera.aspectRatio;

    // to prevent scaling down, invert the value
    if (scale < 1) scale = 1 / scale;

    return Transform.scale(
      scale: scale,
      child: Center(
        child: CameraPreview(cameraController),
      ),
    );
  }

  /* Older versions - v0.6.6 and below */
  Widget cameraWidgetOldVersion(context, cameraController) {
    // get screen size
    final size = MediaQuery.of(context).size;

    // calculate scale for aspect ratio widget
    var scale = cameraController.value.aspectRatio / size.aspectRatio;

    // check if adjustments are needed...
    if (cameraController.value.aspectRatio < size.aspectRatio) {
      scale = 1 / scale;
    }

    double defaultRatio = MediaQuery.of(context).size.aspectRatio;

    return Transform.scale(
      scale: 1.0,
      child: AspectRatio(
        aspectRatio: defaultRatio,
        child: OverflowBox(
          alignment: Alignment.center,
          child: FittedBox(
            fit: size.aspectRatio >= defaultRatio
                ? BoxFit.fitHeight
                : BoxFit.fitWidth,
            child: SizedBox(
              width:
                  size.aspectRatio >= defaultRatio ? size.height : size.width,
              height: size.aspectRatio >= defaultRatio
                  ? size.height * cameraController.value.aspectRatio
                  : size.width * cameraController.value.aspectRatio,
              child: Stack(
                children: <Widget>[
                  CameraPreview(cameraController),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget cameraSwitch() {
    final CameraController cameraController = controller!;
    return InkWell(
      onTap: () {
        if (cameraController.value.isInitialized &&
            !cameraController.value.isRecordingVideo) {
          if (cameras.isNotEmpty) {
            if (selectedCamera == cameras[0]) {
              selectedCamera = cameras[1];
              onNewCameraSelected(selectedCamera!);
            } else {
              selectedCamera = cameras[0];
              onNewCameraSelected(selectedCamera!);
            }
          }
        }
        setState(() {});
      },
      child: Padding(
        padding: EdgeInsets.only(right: 16.0.sp),
        child: Image.asset(
          ImageConstants.switchCamera,
          width: 22.sp,
          height: 22.sp,
        ),
      ),
    );
  }

  Future<void> onCaptureButtonPressed() async {
    hideAppBar.value = true;
    await takePicture();
    if (mounted) setState(() {});
  }

  Future<void> takePicture() async {
    final CameraController cameraController = controller!;

    if (!cameraController.value.isInitialized) {
      showInSnackBar(txtSelectCamera);
      return;
    }

    try {
      XFile? imageXFile = await cameraController.takePicture();

      hideAppBar.value = true;

      Navigator.of(context).pop(
        imageXFile.path.toString(),
      );
    } on CameraException catch (e) {
      _showCameraException(e);
      return;
    }
  }

  Future<XFile?> stopVideoRecording() async {
    final CameraController cameraController = controller!;
    if (!cameraController.value.isRecordingVideo) {
      return null;
    }
    try {
      return await cameraController.stopVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
  }

  Widget cameraCapture() {
    final CameraController cameraController = controller!;
    return InkWell(
      onTap: () {
        if (cameraController.value.isInitialized) {
          onCaptureButtonPressed();
        } else {
          showInSnackBar(somethingWentWrongText ?? "");
        }
      },
      child: Container(
          padding: EdgeInsets.all(
            4.5.sp,
          ),
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            border: Border.all(
              color: Colors.transparent,
              width: 3.5.sp,
            ),
          ),
          child: CircleAvatar(
            radius: 18.sp,
            backgroundColor: ColorConstants.whiteColor,
          ),
        ),
    );
  }
}

```
</p>
</details>


<details> <summary>Output of flutter run -v </summary>
<p>

Error Log:

```
======= Exception caught by widgets library =======================================================
The following _CastError was thrown building CapturePhotoCamera(dirty, state: _CapturePhotoCameraState#8e5e4):
Null check operator used on a null value

The relevant error-causing widget was: 
  CapturePhotoCamera CapturePhotoCamera:file:///Users/Desktop/FlutterProject/Projects/sample/lib/Routers/routing.dart:111:35
When the exception was thrown, this was the stack: 
#0      _CapturePhotoCameraState.cameraScreen (package:sample/Utils/capture_photo_camera_util.dart:234:57)
#1      _CapturePhotoCameraState.build (package:sample/Utils/capture_photo_camera_util.dart:173:26)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4968:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
...     Normal element mounting (275 frames)
#283    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#284    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#285    Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#286    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5883:32)
#287    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#288    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#289    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#290    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#291    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#292    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#293    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#294    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#295    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#296    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#297    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#298    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#299    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#300    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#301    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:108:11)
#302    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#303    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#304    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#305    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#306    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#307    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#308    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#309    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#310    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#311    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#312    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#313    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#314    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#315    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#316    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#317    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#318    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#319    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#320    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#321    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#322    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#323    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#324    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#325    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#326    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#330    _invoke (dart:ui/hooks.dart:151:10)
#331    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#332    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
E/MethodChannel#plugins.flutter.io/camera_android(16521): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_android(16521): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.features.resolution.ResolutionFeature.configureResolution(ResolutionFeature.java:244)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.features.resolution.ResolutionFeature.<init>(ResolutionFeature.java:50)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.features.CameraFeatureFactoryImpl.createResolutionFeature(CameraFeatureFactoryImpl.java:58)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.features.CameraFeatures.init(CameraFeatures.java:71)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.Camera.<init>(Camera.java:215)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:389)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$io-flutter-plugins-camera-MethodCallHandlerImpl(MethodCallHandlerImpl.java:82)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.MethodCallHandlerImpl$$ExternalSyntheticLambda0.onResult(Unknown Source:6)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:69)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:75)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at android.app.ActivityThread.main(ActivityThread.java:7892)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#plugins.flutter.io/camera_android(16521):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/flutter (16521): Error: error
I/flutter (16521): Error Message: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference
```
</p>
</details>


<details> <summary>Output of flutter doctor -v </summary>
<p>

```

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-arm (Rosetta), locale en-IN)
    • Flutter version 3.0.5 at /Users/Desktop/FlutterProject/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</p>
</details>

**Comment by exaby73** [comment] 2022-12-19 11:36
You sample code is too complex. Can you try to simplify it, removing all code that is not necessary to reproduce the issue? It should be complete but minimal

**Comment by tejaswinidev24** [comment] 2022-12-19 13:26
Can you please check this code

<details>
<summary> Sample Code </Summary>
<p>
```
import 'dart:async';
import 'dart:math' as math;

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:sample/ResourceConstants/color_constants.dart';
import 'package:sample/ResourceConstants/image_constants.dart';
import 'package:sample/Utils/app_language_util.dart';
import 'package:sample/Utils/loading_util.dart';
import 'package:sample/Utils/print_util.dart';
import 'package:sample/Utils/toast_util.dart';
import 'package:sizer/sizer.dart';

class CapturePhotoCamera extends StatefulWidget {
  const CapturePhotoCamera({
    Key? key,
  }) : super(key: key);

  @override
  _CapturePhotoCameraState createState() => _CapturePhotoCameraState();
}

class _CapturePhotoCameraState extends State<CapturePhotoCamera>
    with WidgetsBindingObserver, TickerProviderStateMixin {
  CameraController? controller;
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  List<CameraDescription> cameras = [];
  CameraDescription? selectedCamera;
  String txtSelectCamera = "Select a camera first!";
  String? somethingWentWrongText = "Something went wrong!!";

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    getLang();
    getAvaiableCamera();
  }

  getAvaiableCamera() async {
    cameras = await availableCameras();
    if (cameras.isNotEmpty) {
      if (cameras.isNotEmpty) {
        selectedCamera = cameras[1];
        onNewCameraSelected(selectedCamera!);
      } else {
        selectedCamera = cameras[0];
        onNewCameraSelected(selectedCamera!);
      }
    }
    setState(() {});
  }
 
  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();

  void onNewCameraSelected(CameraDescription cameraDescription) async {
    await controller?.dispose();
    final CameraController cameraController = CameraController(
      cameraDescription,
      ResolutionPreset.medium,
    );
    controller = cameraController;
    
    cameraController.addListener(() {
      if (mounted) setState(() {});
      if (cameraController.value.hasError) {}
    });

    try {
      await cameraController.initialize();
    } on CameraException catch (e) {
    }
    if (mounted) {
      setState(() {});
    }
  }

  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
          resizeToAvoidBottomInset: false,
          key: _scaffoldKey,
          body: Stack(
            children: [
              Positioned(
                child: Container(
                  alignment: Alignment.center,
                  child: cameraScreen(),
                ),
              ),
              Positioned(
                bottom: 0.0,
                child: SingleChildScrollView(
                  child: Container(
                    width: SizerUtil.width,
                    padding: EdgeInsets.symmetric(
                      vertical: 12.sp,
                    ),
                    alignment: Alignment.bottomCenter,
                    child: cameraCapture(),
                  ),
                ),
              )
            ],
          ),
        );
  }

  Widget cameraScreen() {
    final CameraController cameraController = controller!;
    if (!cameraController.value.isInitialized) {
      return Container(
        width: SizerUtil.width,
        height: SizerUtil.height,
        color: Colors.black,
        child: Center(
          child: LoadingUtil.ballRotate(context),
        ),
      );
    } else {
      return cameraWidgetOldVersion(context, cameraController);
    }
  }

  /* Camera package version v0.7.0 and above */
  Widget cameraWidgetNewVersion(context, cameraController) {
    var camera = cameraController.value;
   
    final size = MediaQuery.of(context).size;

    var scale = size.aspectRatio * camera.aspectRatio;

    if (scale < 1) scale = 1 / scale;

    return Transform.scale(
      scale: scale,
      child: Center(
        child: CameraPreview(cameraController),
      ),
    );
  }

  /* Older versions - v0.6.6 and below */
  Widget cameraWidgetOldVersion(context, cameraController) {
    
    final size = MediaQuery.of(context).size;

    var scale = cameraController.value.aspectRatio / size.aspectRatio;

    if (cameraController.value.aspectRatio < size.aspectRatio) {
      scale = 1 / scale;
    }

    double defaultRatio = MediaQuery.of(context).size.aspectRatio;

    return Transform.scale(
      scale: 1.0,
      child: AspectRatio(
        aspectRatio: defaultRatio,
        child: OverflowBox(
          alignment: Alignment.center,
          child: FittedBox(
            fit: size.aspectRatio >= defaultRatio
                ? BoxFit.fitHeight
                : BoxFit.fitWidth,
            child: SizedBox(
              width:
                  size.aspectRatio >= defaultRatio ? size.height : size.width,
              height: size.aspectRatio >= defaultRatio
                  ? size.height * cameraController.value.aspectRatio
                  : size.width * cameraController.value.aspectRatio,
              child: Stack(
                children: <Widget>[
                  CameraPreview(cameraController),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget cameraSwitch() {
    final CameraController cameraController = controller!;
    return InkWell(
      onTap: () {
        if (cameraController.value.isInitialized &&
            !cameraController.value.isRecordingVideo) {
          if (cameras.isNotEmpty) {
            if (selectedCamera == cameras[0]) {
              selectedCamera = cameras[1];
              onNewCameraSelected(selectedCamera!);
            } else {
              selectedCamera = cameras[0];
              onNewCameraSelected(selectedCamera!);
            }
          }
        }
        setState(() {});
      },
      child: Padding(
        padding: EdgeInsets.only(right: 16.0.sp),
        child: Image.asset(
          ImageConstants.switchCamera,
          width: 22.sp,
          height: 22.sp,
        ),
      ),
    );
  }

  Future<void> onCaptureButtonPressed() async {
    await takePicture();
    if (mounted) setState(() {});
  }

  Future<void> takePicture() async {
    final CameraController cameraController = controller!;
    if (!cameraController.value.isInitialized) {
      return;
    }

    try {
      XFile? imageXFile = await cameraController.takePicture();
      Navigator.of(context).pop(
        imageXFile.path.toString(),
      );
    } on CameraException catch (e) {
      return;
    }
  }

  Future<XFile?> stopVideoRecording() async {
    final CameraController cameraController = controller!;
    if (!cameraController.value.isRecordingVideo) {
      return null;
    }
    try {
      return await cameraController.stopVideoRecording();
    } on CameraException catch (e) {
      return null;
    }
  }

  Widget cameraCapture() {
    final CameraController cameraController = controller!;
    return InkWell(
      onTap: () {
        if (cameraController.value.isInitialized) {
          onCaptureButtonPressed();
        } 
      },
      child: Container(
          padding: EdgeInsets.all(
            4.5.sp,
          ),
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            border: Border.all(
              color: Colors.transparent,
              width: 3.5.sp,
            ),
          ),
          child: CircleAvatar(
            radius: 18.sp,
            backgroundColor: ColorConstants.whiteColor,
          ),
        ),
    );
  }
}



```
</p>
</details>

**Comment by exaby73** [comment] 2022-12-19 13:34
Try to exclude the use of any 3rd party libraries and those language and color utils. Ideally, the only imports that should exist are Flutter ones and the `camera` one.

Alternatively, could you try [the official example](https://pub.dev/packages/camera/example) and see if you reproduce it?

Also, there is a similar issue already open (https://github.com/flutter/flutter/issues/109769). Is this what you're experiencing?

**Comment by tejaswinidev24** [comment] 2022-12-19 15:58
Yes @exaby73 I am facing similar issues. I have tried the official example as well. Same issue

**Comment by exaby73** [comment] 2022-12-20 07:42
Since this is the same issue, you can follow up on the original issue. I am closing this one as a duplicate. Thank you

**Closed by exaby73** 2022-12-20 07:42 UTC
Labels: in triage
