### ISSUE TITLE
Android Studio flutter and Dart plugins are not install error(Stable branch)

### ISSUE THREAD

**Issue by Alabhya268** [flutter/flutter#75570] opened 2021-02-06 21:47 UTC
Despite flutter and Dart plugins being installed when running "flutter doctor -v" in terminal its showing Android Studio flutter and Dart plugins are not install error when switching to stable branch from master.

[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_IN)
    • Flutter version 1.22.6 at /home/alabhya/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alabhya/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • GM1911 (mobile) • d0cefaf5 • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
</details>

**Comment by Alabhya268** [comment] 2021-02-07 07:47
@shihaohong help me with this issue please.

**Comment by iapicca** [comment] 2021-02-07 14:38
@Alabhya268 
I was 100% sure that the problem was flutter snap installation,
but I see that you have AS installed by snap, but not flutter...
interesting

**Comment by Alabhya268** [comment] 2021-02-07 14:39
> @Alabhya268 
> I was 100% sure that the problem was flutter snap installation,
> but I see that you have AS installed by snap, but not flutter...
> interesting

@iapicca , I tried it in windows too...on stable branch it shows same issue.

**Comment by TahaTesser** [comment] 2021-02-08 08:19
Hi @Alabhya268 
Missing plugins in `doctor -v` don't affect Flutter functionality https://github.com/flutter/flutter/issues/67986#issuecomment-715452201. You can still use Flutter in IntelliJ or Android Studio.
This would be resolved once the fixe reaches `stable`
Closing this as a duplicate of https://github.com/flutter/flutter/issues/67986#issuecomment-715452201
Thank you

**Closed by TahaTesser** 2021-02-08 08:19 UTC
