### ISSUE TITLE
Double tap a word in a TextField to select it

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#11279] opened 2017-07-18 20:58 UTC
On Android you can double tap a word in a text field to select it, but in a flutter TextField this doesn't seem to work. You need to long press to select it.

## Steps to Reproduce

- Add a new TextField
- Write some words
- Double tap a word

**Comment by joelfaul** [comment] 2018-07-11 19:38
This seems to be a duplicate of [#9288](https://github.com/flutter/flutter/issues/9288) which contains a full discussion of the topic.

**Comment by zoechi** [comment] 2018-07-11 19:49
@joelfaul thanks. Closing as dup.

**Closed by zoechi** 2018-07-11 19:49 UTC
Labels: a: text input, ▣ platform-android
