### ISSUE TITLE
"Restore Down" takes long time 

### ISSUE THREAD

**Issue by TheCGDF** [flutter/flutter#55169] opened 2020-04-19 21:26 UTC
## Steps to Reproduce

1. Write some code and run it on Windows
2. Click "Maxmize".
![fluttertest_uMqoFtahwp](https://user-images.githubusercontent.com/17256673/79700215-20e5e580-82cf-11ea-947a-abe879b1584e.jpg)
3. Click "Restore Down"
![fluttertest_8bpkvvXYdu](https://user-images.githubusercontent.com/17256673/79700235-44a92b80-82cf-11ea-9abc-11400b6ec795.jpg)

**Expected results:** Restore down quickly.

**Actual results:**
![fluttertest_H9Jeeomlrc](https://user-images.githubusercontent.com/17256673/79700254-64d8ea80-82cf-11ea-850a-39857a3cf481.jpg)

It took seconds to display.

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, v1.18.0-6.0.pre.82, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.18.0-6.0.pre.82 at D:\Software\flutter
    • Framework revision f35b673f2b (24 hours ago), 2020-04-19 02:45:01 +0530
    • Engine revision a5e0b2f2f2
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 5b19445d9c)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Software\AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Software\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.5.0)
    • Visual Studio at D:\Software\VS2019
    • Visual Studio Enterprise 2019 version 16.5.29911.84

[√] Android Studio (version 3.6)
    • Android Studio at D:\Software\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.17763.1039]
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
</details>

**Comment by stuartmorgan** [comment] 2020-04-19 22:25
Duplicate of https://github.com/flutter/flutter/issues/40068.

It's actually not that it's slow per se, it's that we're somehow missing a redraw event, so it doesn't redraw until the next time a redraw would happen for some other reason. If you have an animation running in the window, for instance, you won't see it.

**Closed by stuartmorgan** 2020-04-19 22:25 UTC
