### ISSUE TITLE
Some fonts not rendering correctly on Windows Desktop

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#53871] opened 2020-04-02 21:27 UTC
On Windows the font Quicksand-Bold just never seems to render. Here's Web on top, and Windows on the bottom:
![image](https://user-images.githubusercontent.com/736973/78294578-d7805280-74e7-11ea-94e4-b722800380ac.png)
```
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
```
https://fonts.google.com/specimen/Quicksand

**Comment by pedromassangocode** [comment] 2020-11-26 10:45
Hi @esDotDev 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by esDotDev** [comment] 2020-11-26 18:32
When I logged this bug we were on the latest master, but I'm on another project now and can't easily test.

The minimal reproduction case should be just use the font as I specified, and then:
```
Text("Foo", style: TextStyle(fontWeight: FontWeight.Bold)
```
And compare on Windows vs everywhere else. If they are the same I guess this is closed :)

**Comment by TahaTesser** [comment] 2020-11-30 07:38
Hi @esDotDev 
Looks like this  is fixed on newer flutter channels

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        body: Center(
          child: Container(
            child: Text(
              "Foo",
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
        ),
      ),
    );
  }
}

``` 

</details>

[Font](https://fonts.google.com/specimen/Quicksand?query=quick)

| Web| Windows |
| --------------- | --------------- |
![Screenshot 2020-11-30 125853](https://user-images.githubusercontent.com/48603081/100580980-e9cbbe00-330c-11eb-8d45-52c745afad1c.png) | ![Screenshot 2020-11-30 125957](https://user-images.githubusercontent.com/48603081/100581026-fd772480-330c-11eb-911b-ffb0d3966995.png)


<details> 
<summary>dev & master flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-10.2.pre at C:\Code\flutter_dev
    • Framework revision 022b333a08 (12 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin version 50.0
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-8.0.pre.374 at C:\Code\flutter_master
    • Framework revision 183f0e797a (4 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin version 50.0
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```

</details>

Looks like outputs are identical between web and desktop, when comparing 


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-30 07:38 UTC
Labels: P5, a: desktop, a: typography, engine, in triage, platform-windows
