### ISSUE TITLE
99th_percentile_frame_rasterizer_time_millis flutter_gallery_sksl_warmup__transition_perf regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#69205] opened 2020-10-28 16:18 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1603526223&end=1603867624&keys=X7728d6094a7f0aebd80375845eda2829&requestType=0&xbaroffset=22225

https://github.com/flutter/engine/pull/22118 seems to be the culprit.

It looks bimodal, though.

**Comment by zanderso** [comment] 2020-11-02 16:24
This appears to be due to https://github.com/flutter/flutter/pull/69126 not https://github.com/flutter/engine/pull/22118. https://github.com/flutter/flutter/pull/69237 did not appear to help. /cc @jonahwilliams

**Comment by dnfield** [comment] 2020-11-02 17:03
I'm a bit confused about how a client side change to the driver implementation could cause a perf regression.

**Comment by zanderso** [comment] 2020-11-02 17:07
@liyuqian might have a good understanding of how this could happen.

**Comment by liyuqian** [comment] 2020-11-02 18:16
It's likely that the driver change caused different frames to be measured. For example, previously we've seen similar changes when e2e (integration_test) replaces the old driver perf test: e2e is faster, and the test ended up measuring more frames which changes the frame time distribution.

It might also be a bug in the tool similar to https://github.com/flutter/flutter/issues/69206. But I think this is less likely for this case.

To figure out what exactly happened, I recommend plot the frame times (e.g., https://github.com/flutter/flutter/issues/68620#issuecomment-713071284) since the 99th percentile doesn't give enough information on the full distribution.

**Comment by dnfield** [comment] 2020-11-02 18:20
That sounds like we can reduce the priority on this and sort out a more consistent way to measure this benchmark. Is that fair?

**Comment by dnfield** [comment] 2020-11-02 18:49
@liyuqian do we have a bug open tracking using a more stable way of measuring frame times, or should we use this one?

**Comment by dnfield** [comment] 2020-11-02 18:50
And if we use this bug, is there a more appropriate title we can use?

**Comment by liyuqian** [comment] 2020-11-02 18:56
AFAIK, there isn't an issue that tracks the inconsistency of measuring frame times when the tool is changed. If we use this issue for that, I think we should first figure out what caused this regression/inconsistency, and then maybe we can change the title to be something like "Fix XXX inconsistency and guard future problems like this".

**Comment by dnfield** [comment] 2020-11-02 19:03
In that case let's close this - if we see that there is continued inconsistency with the new changes, we can open a more focused bug to investigate.

**Closed by dnfield** 2020-11-02 19:03 UTC
Labels: P3, a: tests, engine, passed first triage, perf: speed, severe: performance, severe: regression, team: benchmark, team: bimodal benchmark, team: flakes
