### ISSUE TITLE
Tool crashes when using setLastModifiedSync on .packages

### ISSUE THREAD

**Issue by sirredbeard** [flutter/flutter#49948] opened 2020-02-01 17:47 UTC
When running flutter for Linux in WSL2 on a project stored on the automatically mounted Windows file system (at /mnt/c) flutter crashes with the following error:

```
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to set file modification time, path =               '/mnt/c/Users/Hayden/OneDrive/Documents/GitHub/flutter_stuff/flutter-desktop-embedding/example/.packages' (OS Error:    Operation not permitted, errno = 1)". 
```

![Annotation 2020-02-01 122530](https://user-images.githubusercontent.com/33820650/73596259-b94da480-44ee-11ea-94cb-afee06188468.png)

This is probably a weird permissions issue as a result of the Windows<->Linux boundary but it would be nice if it could work around that or at least fail with a more informative message.

chowning the files doesn't work, tried that.

The current workaround is to move the project to the WSL file system:
```
cd ~
mv /mnt/c/folder/flutter_project .
chown -R $(id -u -n) flutter_project/
cd flutter_project/
flutter build
```

Here are logs I collected:

[flutter_01.log](https://github.com/flutter/flutter/files/4142890/flutter_01.log)
[flutter_02.log](https://github.com/flutter/flutter/files/4142891/flutter_02.log)
[flutter_03.log](https://github.com/flutter/flutter/files/4142892/flutter_03.log)

**Comment by jonahwilliams** [comment] 2020-02-01 20:45
The code that is failing is here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/pub.dart#L210

It should probably catch exceptions and only warn - though if you lack permission to modify files in the project, this would probably only move the exception elsewhere

**Comment by danielroek** [comment] 2020-02-02 21:48
What helped for me was deleting all generated files because there is no permission to override those the run method fails... 

That should be the following files:
.packages
pubspec.lock (not sure about this one, I think this will fail when you run packages upgrade)
.flutter-plugins
.flutter-plugins-dependencies
.dart_tool
and the build folder

**Comment by jonahwilliams** [comment] 2020-02-15 22:01
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-15 22:01 UTC
Labels: severe: crash, tool
