### ISSUE TITLE
Text ellipsis

### ISSUE THREAD

**Issue by cooler-king** [flutter/flutter#3721] opened 2016-05-04 03:25 UTC
Feature request:  I would like an option to tell Text that it should never overflow its container (in either direction) or edge of the screen.  If it does detect such an overflow, I would like it to replace as many characters as necessary with an ellipsis so that there is no overflow.

**Comment by abarth** [comment] 2016-05-04 03:56
Duplicate of #417

This is a common feature request.  We'll implement it soon.

**Closed by abarth** 2016-05-04 03:56 UTC
