### ISSUE TITLE
firebasemessaging Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-4.0.0+1/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#30376] opened 2019-04-02 12:03 UTC
Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-4.0.0+1/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

**Comment by worldofsites** [comment] 2019-04-08 06:55
Same issue on `flutter build apk` command.
```
Note: D:\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+1\android\src\main\java\io\flutter\plugins\firebasemessaging\FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by iapicca** [comment] 2019-11-07 14:20
Hi @kw2019ltd 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-07 14:20 UTC
Labels: waiting for customer response
