### ISSUE TITLE
[Web][Safari] TextFormField requires two taps to start typing

### ISSUE THREAD

**Issue by jpiabrantes** [flutter/flutter#131245] opened 2023-07-25 08:43 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I can reproduce this bug using DartPad.

Open this [link](https://dartpad.dev/c7ed9e38d003f26b2ca6788cf0c94492) on a Safari browser (it also doesn't work on desktop). Tap the button, then tap the TextField once and start typing. Nothing will be typed in. Tap again, and now you can write..

### Expected results

Should be able to write with only one tap.

### Actual results

Needs two taps.

### Code sample

Code is here: https://dartpad.dev/c7ed9e38d003f26b2ca6788cf0c94492

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.2 22D49 darwin-arm64, locale en-GB)
    • Flutter version 3.10.6 on channel stable at /Users/joaoabrantis/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (12 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/joaoabrantis/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 71.2.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.248

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment] 2023-07-25 09:56
Hi @jpiabrantes. Thanks for filing this issue. The code in the dartpad link provided seems to have been modified. Kindly copy and paste the code here as indicated in the template so we can work on this issue properly. Thank you!

**Comment by dam-ease** [comment] 2023-07-25 12:13
Hi @jpiabrantes. Thanks for your response. I am able to reproduce this issue on the latest `master` and `stable` channels.

| Safari | Chrome |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/53122008/308493ae-93fe-4129-9d10-72de07243492"> | <video src="https://github.com/flutter/flutter/assets/53122008/499b5dc0-48fc-4430-9771-7240dae6b1c9"> | 

This seems to be caused by the `SelectionArea` widget used to wrap the whole app. If you remove the `SelectionArea` widget it works very fine. As for the issue with `SelectionArea`, this seems to be similar/related to https://github.com/flutter/flutter/issues/107327 although I seem to be able to reproduce this issue only on Safari. Can you confirm that this works fine on your end removing the `SelectionArea` widget and that the already open issue describes your issue?

**Comment by dam-ease** [comment] 2023-07-26 08:54
Yes, I see the same behaviour on my end as well. I presume it's the same issue, another issue was filed similar to this https://github.com/flutter/flutter/issues/128116 which was closed in favour of the already existing issue. Kindly comment, upvote and follow up on the currently open issue for updates. Closing this as a duplicate, if you disagree, kindly comment and I'd reopen.
Thank you!

**Closed by dam-ease** 2023-07-26 08:54 UTC
Labels: in triage
