### ISSUE TITLE
Ellipsis overflow option doesn't work for title of SliverAppBar

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#11337] opened 2017-07-21 16:10 UTC
If you add a `Text` widget to a `SliverAppBar` and set `overflow: TextOverflow.ellipsis,` then it will use clipped. `TextOverflow.fade` works.

**Comment by Hixie** [comment] 2018-05-08 23:37
cc @jason-simmons

**Comment by helinanever** [comment] 2020-05-27 13:39
I reproduced the issue here's my **flutter doctor -v**

`[✓] Flutter (Channel master, v1.18.1-pre.9, on Mac OS X 10.15.1 19B88, locale en-BD)
    • Flutter version 1.18.1-pre.9 at /Users/mamun/Developer/flutter
    • Framework revision 17079f26b5 (7 weeks ago), 2020-04-06 01:21:01 -0400
    • Engine revision 9b8dcc7ecf
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 05103dfe5a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mamun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • P9         • P9170526000200                       • android-arm64  • Android 7.0 (API 24)
    • ios 13.3   • 55CEFA0C-C25A-4064-A491-0C77292D7F39 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 83.0.4103.61
    • Web Server • web-server                           • web-javascript • Flutter Tools

• No issues found!
`

**Comment by VladyslavBondarenko** [comment] 2020-05-27 14:42
I can't reproduce the issue with `dev 1.19.0-1.0.pre` and this code sample:

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverAppBar(
              expandedHeight: 150.0,
              flexibleSpace: const FlexibleSpaceBar(
                title: Text(
                  'text text text text text text text text text text text text text text text',
                  overflow: TextOverflow.ellipsis,
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```
Closing as fixed. 
If you disagree, please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-05-27 14:42 UTC
Labels: a: typography, engine, framework, has reproducible steps
