### ISSUE TITLE
[go_router] 5.2.0 can't enter same path again

### ISSUE THREAD

**Issue by a1573595** [flutter/flutter#116082] opened 2022-11-28 02:13 UTC
## Steps to Reproduce
1. Execute `flutter run` on the code sample.
2. Click 「Second」to next page.
3. Click the back button back to the home page.
4. Click 「Second」to next page.

**Expected results:** 
Enter the second page again.

**Actual results:** 
Nothing on 5.2.0, but 5.1.10 is ok.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

final rootRouter = GoRouter(routes: [
  GoRoute(path: '/', builder: (context, state) => HomePage(), routes: [
    GoRoute(
        path: 'second',
        builder: (context, state) => const SecondPage(),
        routes: []),
  ]),
]);

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: rootRouter,
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: Center(
        child: ElevatedButton(
            onPressed: () {
              GoRouter.of(context).go('/second');
            },
            child: const Text('Second')),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second'),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[   +1 ms] Stopping app 'app.apk' on sdk gphone64 arm64.
[        ] executing: /Users/chien/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.example.untitled1
[ +128 ms] executing: /Users/chien/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.untitled1
[  +61 ms] package:com.example.untitled1
[        ] executing: /Users/chien/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.untitled1.sha1
[  +65 ms] 8fd64c614e9de4bc8ad9cf28e08ef158ed70371a
[        ] Installing APK.
[        ] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /Users/chien/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r /Users/chien/Flutter/untitled1/build/app/outputs/flutter-apk/app.apk
[ +701 ms] Performing Streamed Install
                    Success
[   +1 ms] Installing build/app/outputs/flutter-apk/app.apk... (completed in 701ms)
[        ] executing: /Users/chien/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo -n 01f111074c7c30e57dd726fcf2f8d7645b3eb8dd >
/data/local/tmp/sky.com.example.untitled1.sha1
[  +23 ms] executing: /Users/chien/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[ +115 ms] --------- beginning of main
                    11-28 10:03:08.873 W/RanchuHwc(  382): presentDisplay display has no layers to compose, flushing client target buffer.
[   +6 ms] executing: /Users/chien/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f
0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.untitled1/com.example.untitled1.MainActivity
[  +64 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=com.example.untitled1/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +478 ms] Observatory URL on device: http://127.0.0.1:34427/m9-Ysn9CJeA=/
[        ] executing: /Users/chien/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:34427
[  +11 ms] 62769
[        ] Forwarded host port 62769 to device port 34427 for Observatory
[   +2 ms] Caching compiled dill
[  +36 ms] Connecting to service protocol: http://127.0.0.1:62769/m9-Ysn9CJeA=/
[  +85 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:62769/m9-Ysn9CJeA=/.
[  +76 ms] DDS is listening at http://127.0.0.1:62772/IVlI3bcSQ6s=/.
[  +25 ms] Successfully connected to service protocol: http://127.0.0.1:62769/m9-Ysn9CJeA=/
[  +37 ms] DevFS: Creating new filesystem on the device (null)
[  +16 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.untitled1/code_cache/untitled1QSSIEC/untitled1/)
[        ] Updating assets
[  +37 ms] Syncing files to device sdk gphone64 arm64...
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:untitled1/main.dart 8459ace9-5f90-40ec-896e-98ee9b209b48
[        ] <- 8459ace9-5f90-40ec-896e-98ee9b209b48
[   +2 ms] Bundle processing done.
[  +78 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device sdk gphone64 arm64... (completed in 81ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] Connected to _flutterView/0xb400007bdbcfad70.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:62772/IVlI3bcSQ6s=/
[ +148 ms] The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:62772/IVlI3bcSQ6s=/
[  +63 ms] E/SurfaceSyncer( 8190): Failed to find sync for id=0
[  +24 ms] W/Parcel  ( 8190): Expecting binder but got null!
[+6992 ms] D/EGL_emulation( 8190): app_time_stats: avg=3510.85ms min=104.22ms max=6917.48ms count=2
[+1075 ms] D/EGL_emulation( 8190): app_time_stats: avg=66.54ms min=1.46ms max=842.26ms count=14
[+2423 ms] D/EGL_emulation( 8190): app_time_stats: avg=121.18ms min=10.77ms max=2110.19ms count=20
[+1208 ms] D/EGL_emulation( 8190): app_time_stats: avg=31.04ms min=1.36ms max=774.41ms count=27
```

```
Analyzing untitled1...                                                  

   info • Prefer const with constant constructors • lib/main.dart:9:51 • prefer_const_constructors
   info • Prefer const literals as parameters of constructors on @immutable classes • lib/main.dart:13:17 • prefer_const_literals_to_create_immutables
   info • Prefer const with constant constructors • lib/main.dart:35:16 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:55:16 • prefer_const_constructors

4 issues found. (ran in 1.4s)
```

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale zh-Hant-TW)
    • Flutter version 3.3.9 on channel stable at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (5 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/chien/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/chien/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • ASUS Z01RD (mobile)         • J9AZB760H2767RP • android-arm64  • Android 10 (API 29)
    • sdk gphone64 arm64 (mobile) • emulator-5554   • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos           • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                • chrome          • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-11-28 07:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/115832

**Closed by danagbemava-nc** 2022-11-28 07:44 UTC
Labels: in triage
