### ISSUE TITLE
Flutter tool red text difficult to read in PowerShell on Windows

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#101926] opened 2022-04-14 18:51 UTC
It's difficult to read red text printed by the `flutter` command in Powershell:

![powershell](https://user-images.githubusercontent.com/1145719/163454561-bab09e3e-93e7-4c75-8363-e3d9941ee670.png)

Powershell is ANSI, but it seems like the convention is to use a black background for error messages:

<img width="879" alt="Screen Shot 2022-04-14 at 11 49 16 AM" src="https://user-images.githubusercontent.com/1145719/163457144-91379682-806d-40c6-a1ae-3680fbed1530.png">

cc: @domesticmouse

**Comment by johnpryan** [comment] 2022-04-14 18:55
I'm not sure this is something we can control. My workaround was to just change the background color:
<img width="400" alt="Screen Shot 2022-04-14 at 11 55 02 AM" src="https://user-images.githubusercontent.com/1145719/163457888-4af9bf4b-7406-4ab1-a3e5-78dc9f2c9576.png">

**Comment by cbracken** [comment] 2022-04-20 05:36
Closing as duplicate of https://github.com/flutter/flutter/issues/78400

**Closed by cbracken** 2022-04-20 05:36 UTC
Labels: tool, platform-windows
