### ISSUE TITLE
I have problem when route to new page in android 5.0.2  (lollipop)  

### ISSUE THREAD

**Issue by arashkey** [flutter/flutter#106393] opened 2022-06-22 05:00 UTC
Hi
Unfortunately in Android 5.0.2 I had trouble using this package. When WebView is displayed on one page, and I move to the next page with the help of a button, the previous WebView is still displayed on the screen.
How can I solve this problem?
![photo](https://user-images.githubusercontent.com/7925542/174948597-a48b4265-fcaf-45d4-aa07-d8f9c5226d9d.jpg)

[test_flutter.zip](https://github.com/flutter/flutter/files/8954514/test_flutter.zip)
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22610.1], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.2.4)
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.68.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
`

**Comment by exaby73** [comment] 2022-06-22 09:21
Duplicate of #103630

**Closed** 2022-06-22 09:21 UTC
Labels: in triage, r: duplicate
