### ISSUE TITLE
Check the device in integration testing

### ISSUE THREAD

**Issue by BassamxMednini** [flutter/flutter#56243] opened 2020-05-03 15:29 UTC
It is currently not possible, to detect if the integration test runs on a smartphone or tablet. I've some functions there are just for smartphones and some functions there are just for tablets. But without detecting which device currently is connected, the test runs everything and, of course, print some errors. Generally, creating an app for tablets is in flutter not as easy as it might sound.

**Comment by jonahwilliams** [comment] 2020-05-04 02:57
Duplicate of https://github.com/flutter/flutter/issues/10584

**Closed by jonahwilliams** 2020-05-04 02:57 UTC

**Comment by BassamxMednini** [comment] 2020-05-07 16:25
@jonahwilliams Is there a temporary solution? This feature is very important for me.
