### ISSUE TITLE
[tool_crash] _CastError: (%230      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49))

### ISSUE THREAD

**Issue by DGHub-Dimitry** [flutter/flutter#102038] opened 2022-04-17 14:21 UTC
%23%23 Command
```
flutter run -d windows
```

%23%23 Steps to Reproduce
1. ...
2. ...
3. ...

%23%23 Logs
_CastError: (%230      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49))
```
%230      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49)
%231      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1137:34)
%232      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1238:46)
%233      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1313:47)
%234      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
%235      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
%236      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
%237      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
%238      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
%239      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1296:7)
<asynchronous suspension>
%2310     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
%2311     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2312     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
%2313     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
%2314     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2315     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```
```
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
    • Flutter version 2.10.4 at D:\DevTools\SDK\flutter_windows_1.22.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\msi\AppData\Local\Android\sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: D:\Programs\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\Programs\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\Programs\IntelliJ IDEA 2021.2.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at C:\Users\msi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.39

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

%23%23 Flutter Application Metadata
**Type**: app
**Version**: 1.0.0 1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 097d3313d8e2c7f901932d63e537c1acefb87800
%23%23%23 Plugins
bitsdojo_window-0.1.1 1
bitsdojo_window_linux-0.1.1
bitsdojo_window_macos-0.1.0
bitsdojo_window_windows-0.1.0
google_sign_in-5.3.0
google_sign_in_android-5.2.5
google_sign_in_ios-5.2.5
google_sign_in_web-0.10.1
path_provider_linux-2.1.5
path_provider_windows-2.0.5
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
window_manager-0.2.1

**Comment by danagbemava-nc** [comment] 2022-04-18 08:36
Closing this as duplicate of #87851

**Closed** 2022-04-18 09:13 UTC
Labels: r: duplicate
