### ISSUE TITLE
The children setting key of listview.builder does not work

### ISSUE THREAD

**Issue by lalLAL95828** [flutter/flutter#93443] opened 2021-11-11 00:25 UTC
Listview and listview.builder, when the children of both are set with key. When using the floatingactionbutton to delete and build the list of their children, the children color of listview will not change, but listview.builder will. Why? If I hope that the color of children in listview.builder will not change with its list, what can I do?
```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main()=>runApp(MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final List<String> name1 = ["a:The color will change","b:The color will change","c:The color will change"];
  final List<String> name2 = ["a2:The color will not change","b2:The color will not change","c2:The color will not change"];


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "lal Test",
      home:Scaffold(
        body: Container(
          child: Column(
            children: [
              ListView.builder(
                  shrinkWrap:true,
                  itemCount:name1.length,
                  itemBuilder:(ctx,index){
                    return TestKey(name1[index],key: ValueKey(name1[index]),);
                  },

              ),

              SizedBox(height: 50,),

              ListView(
                  shrinkWrap:true,
                  children: name2.map((e){
                return TestKey(e,key: ValueKey(e),);
              }).toList())
            ],
          ),
        ),
        appBar: AppBar(
          title: Text("home"),
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.delete),
          onPressed: (){
            name1.removeAt(0);
            name2.removeAt(0);
            setState((){});
          },
        ),
      )
    );
  }
}


class TestKey extends StatefulWidget {
  final String item;
  TestKey(this.item,{Key? key}) : super(key: key);

  @override
  _TestKeyState createState() => _TestKeyState();
}

class _TestKeyState extends State<TestKey> {
  Color _c = Color.fromARGB(255, Random().nextInt(256), Random().nextInt(256), Random().nextInt(256));

  @override
  Widget build(BuildContext context) {
    print("即使key一样，还是会重新build");
    return Container(
      height: 50,
      color:_c,
      child: Text(widget.item,style: TextStyle(color: Colors.white),),
    );
  }
}

```

**Comment by maheshmnj** [comment] 2021-11-12 09:09
Hi @lalLAL95828, Thanks for filing the issue. This is by design  I would recommend you to please go through this to understand when flutter redraws widgets https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d

Closing as this isn't an issue with flutter if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-11-12 09:09 UTC
Labels: in triage
