### ISSUE TITLE
[flutter_tools] SocketException: OS Error: Success

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#90921] opened 2021-09-29 02:32 UTC
No stacktrace, on `stable/2.5.1`:

```
Thread 0 main threadSocketException: SocketException: OS Error: Success, errno = 0, port = 0
```

**Comment by christopherfujino** [comment] 2021-12-14 22:46
This is in the top 10 most frequent crashers for Flutter stable 2.8.0.

**Comment by a-siva** [comment] 2021-12-20 23:04
Is there a possibility of getting a stack trace when this exception happens ?

**Comment by christopherfujino** [comment] 2021-12-28 22:59
I believe this is `dependency: dart` because the exception is being thrown from the sdk cc @zanderso

**Comment by zanderso** [comment] 2021-12-28 23:16
@a-siva Unfortunately, what we're seeing in crash logging is that there is no stack trace. In the past when we've seen similar crashes, it means that it is an asynchronous exception from a call to something like `Future.error()`, or `StreamController.addError()` without the optional `StackTrace` argument.

My guess is that this one is coming from here: https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/vm/bin/socket_patch.dart#L1408. That could happen if there's an error on the socket that gets clobbered somehow before the error bits can be read off of it, for example maybe if it gets closed immediately.

In theory we could work around it by putting an error handler callback on the `listen()` call for that stream, but the listener for that stream is probably in the `HttpClient` implementation, and even if it's not, we don't have the stack trace to track it down.

**Comment by christopherfujino** [comment] 2022-01-18 22:41
@a-siva has anyone had a chance to take a look at this?

**Comment by a-siva** [comment] 2022-01-24 16:16
Started looking at this last week, hope to make some progress soon.

**Comment by a-siva** [comment] 2022-03-02 00:07
Still having trouble creating a scenario that would reproduce the problem.
If anybody has seem this error in crash reports with a stack trace please post it here.

**Comment by zanderso** [comment] 2022-03-07 16:28
> Still having trouble creating a scenario that would reproduce the problem. If anybody has seem this error in crash reports with a stack trace please post it here.

@a-siva We're not getting a stack trace in crash logging, probably because the error is being injected into a stream from somewhere like [here](https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/vm/bin/socket_patch.dart#L1408) where the stack is passed as `null`. There might not actually be a meaningful stack to pass there, though since the `multiplex` method is the callback for messages received from the event handler thread.

**Comment by Hixie** [comment] 2022-03-15 23:16
Is there some instrumentation / logging we can add somewhere to make it easier to determine what's going on? Is there a future we should be listening to to catch errors, that we're not listening to?

**Comment by a-siva** [comment] 2022-03-21 15:31
you mean instrumentation/logging in the release builds?
Yes that is possible, not sure how noisy it is going to be.

**Comment by a-siva** [comment] 2022-03-21 17:35
@rmacnak-google had a good idea this morning, add code to dump stack trace and crash when an exception object is created with 'OS Error: Success'. This is something we can add to release builds and see if we run into this.

**Comment by a-siva** [comment] 2022-03-30 21:08
https://dart-review.googlesource.com/c/sdk/+/239541 adds a Fatal for OS Error with error code 0.

**Comment by a-siva** [comment] 2022-04-04 20:49
The CL to assert on OSError code being 0 revealed some issues

- On windows there were some cases when error code was 0 for some file operations, these have been fixed by @aam in [sdk#239861](https://dart-review.googlesource.com/c/sdk/+/239861) [sdk#239725](https://dart-review.googlesource.com/c/sdk/+/239725)
- The SSL code was not picking up the right error code for failures in that path, this is being fixed by [sdk#239863](https://dart-review.googlesource.com/c/sdk/+/239863)
- The socket exception assertion when error code is 0 is being landed in here [sdk#239846](https://dart-review.googlesource.com/c/sdk/+/239846)

**Comment by a-siva** [comment] 2022-04-11 15:27
The socket exception assertion when error code is 0 has rolled into Flutter engine, please watch for these assertion in the Flutter logs and post them here whenever we see any such assertions.

**Comment by christopherfujino** [comment] 2022-04-19 21:41
I believe this GitHub search query should pick up if users report the assertion: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+%22Fatal+error+in+dart%3Aio+%28socket%29%3A+%22

**Comment by Hixie** [comment] 2022-04-19 23:07
We may want to close this on the basis that it's not further actionable until we get people filing issues with the stack traces.

**Comment by zanderso** [comment] 2023-07-10 15:35
@christopherfujino Are we still seeing this in crash logging?

**Comment by a-siva** [comment] 2023-11-27 21:08
closing this issue as we have not encountered this recently.

**Closed by a-siva** 2023-11-27 21:08 UTC
Labels: tool, dependency: dart, P2, team-tool, :hourglass_flowing_sand:
