### ISSUE TITLE
Photos are coming up rotated with the camera: ^0.2.6 package on Samsung Devices

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#25232] opened 2018-12-11 19:44 UTC
_Originally posted by @goderbauer in https://github.com/flutter/flutter/issues/10895#issuecomment-445050911_

Although this is a dupe of #10895, it was requested that a new issue is opened if the issue still exists. I'm testing on a Samsung Galaxy S9+ and images are still being saved as rotated 270° even when the device is locked into the vertical orientation. This is on latest (as of now) camera: ^0.2.6.
I also noticed that an Image taken with the front-facing camera is rotated 90°.

**Update: This seems to be an issue only on Samsung devices.** I'm not able to reproduce this on the Android Emulator (8.1.0) nor the Google Pixel. (9.0)

Steps to reproduce:
1. Clone the flutter/ plugins repo and run the example camera app on a **Samsung** device.
2. Notice that images are saved rotated. You can see this in the bottom right corner of the screenshot below.

![whatsapp image 2018-12-11 at 11 42 41 am](https://user-images.githubusercontent.com/23037821/49825824-30980600-fd3a-11e8-91dc-f10e5136e739.jpeg)

**Comment by mklim** [comment] 2018-12-19 21:50
@ThinkDigitalRepair thanks for the bug report! I'm still working on getting an S9 to test this with, but so far I haven't been able to reproduce this on the other Samsung devices that I've tried it on unfortunately. Have you seen this happen on other Samsung devices besides an S9?

I also have a clarifying question.

> images are still being saved as rotated 270° even when the device is locked into the vertical orientation

When you say "locked" here do you mean when the UI is locked to portrait mode, or when the device is physically being held vertically? I'm asking because previously photo orientation was set to match the UI on Android, so photos taken while the device was locked to portrait mode would always be vertical. But flutter/plugins#942 deliberately changed this behavior so that all photos match how the device is physically orientated instead, ignoring the UI rotation.

**Comment by ThinkDigitalRepair** [comment] 2018-12-19 22:12
> Have you seen this happen on other Samsung devices besides an S9?
Yes, with an S7 edge

> When you say "locked" here do you mean when the UI is locked to portrait mode, or when the device is physically being held vertically? 

The device rotation mode would be set to portrait and the ui as well.

**Comment by matte5031** [comment] 2018-12-29 02:21
Same issue here, any updates?

**Comment by BoHellgren** [comment] 2019-01-25 12:57
I made a minimal camera app to illustrate the problem. Using camera 0.2.9+1.

![image](https://user-images.githubusercontent.com/18601125/51747183-fe9ff080-20a8-11e9-9822-23594f2bb0ff.png)


On my Samsung Galaxy, this works as expected when the mobile is  in a vertical  (portrait) position,  but not when horizontal (landscape).

This bug stops me from using Flutter for my app. Can we hope for a solution anytime soon?

**Comment by BoHellgren** [comment] 2019-01-25 13:16
(The built-in camera app does not behave like this. Then a person standing up remains vertical no matter how I turn the phone. But with the app listed above, something happens when I turn the phone past 45 degrees.)

**Comment by BoHellgren** [comment] 2019-01-27 20:09
Found this on
https://developer.android.com/reference/android/hardware/Camera#setDisplayOrientation(int)

_setDisplayOrientation
added in API level 8
public final void setDisplayOrientation (int degrees)
Set the clockwise rotation of preview display in degrees. This affects the preview frames and the picture displayed after snapshot. This method is useful for portrait mode applications. Note that preview display of front-facing cameras is flipped horizontally before the rotation, that is, the image is reflected along the central vertical axis of the camera sensor. So the users can see themselves as looking into a mirror.

This does not affect the order of byte array passed in Camera.PreviewCallback.onPreviewFrame(byte[], Camera), JPEG pictures, or recorded videos. This method is not allowed to be called during preview.

If you want to make the camera image show in the same orientation as the display, you can use the following code.

(code omitted, see link above)
 
Starting from API level 14, this method can be called when preview is active.

Note: Before API level 24, the default value for orientation is 0. Starting in API level 24, the default orientation will be such that applications in forced-landscape mode will have correct preview orientation, which may be either a default of 0 or 180. Applications that operate in portrait mode or allow for changing orientation must still call this method after each orientation change to ensure correct preview display in all cases._

**The camera plugin needs to include this code, I think.**

**Comment by AlexVegner** [comment] 2019-05-19 16:33
We have same issues with device: Samsung Note 8, Android 9

**Comment by gianlucainnocente** [comment] 2019-12-03 17:32
Same problem with Galaxy S6/7

**Comment by TahaTesser** [comment] 2020-03-17 09:40
Hi @ThinkDigitalSoftware  @gianlucainnocente 
Are you still experiencing with latest stable?
Thank you

**Comment by ThinkDigitalSoftware** [comment] 2020-03-17 15:49
Hi, I'm not on a project that uses it currently

On Mar 17, 2020 2:40 AM, Taha Tesser <notifications@github.com> wrote:

Hi @ThinkDigitalSoftware<https://github.com/ThinkDigitalSoftware> @gianlucainnocente<https://github.com/gianlucainnocente>
Are you still experiencing with latest stable?
Thank you

**Comment by BoHellgren** [comment] 2020-03-17 17:45
I tried again with camera: 0.5.7+4 and Flutter 1.12.13+hotfix.8 • channel stable •.

Test program below. 

With a Samsung Galaxy S10e the problem is the same. Portrait mode is OK, in Landscape mode the image is rotated 90 degrees clockwise. Changing ResolutionPreset makes no difference. Front facing camera makes no difference.

With a Samsung Galaxy S4 I now get this error message:

E/CameraDevice-0-LE(19471): Surface with size (w=720, h=480) and format 0x21 is not valid, size not in valid set: [4128x3096, 4128x2322, 3264x2448, 3264x1836, 2560x1920, 2048x1536, 2048x1152, 1920x1080, 1280x960, 1280x720, 640x480]

```
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Minimal Camera App'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  CameraController controller;

  @override
  void initState() {
    super.initState();
    initCamera();
  }

  void initCamera() async {
    List<CameraDescription> cameras = await availableCameras();
    controller = CameraController(cameras[0], ResolutionPreset.medium);
    await controller.initialize();
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return
      controller == null
      ? Text('Wait)')
      : CameraPreview(controller);
  }
}

**Comment by VadPinchuk** [comment] 2020-05-26 13:23
Same now with:
- Device: Samsung S8
- OS: Android 9
- Flutter Channel stable: v1.17.1, 
- camera: 0.5.8+2
Image is not rotated in preview of taken picture. but it is rotated in app folder.

**Comment by mikeb1986** [comment] 2022-05-25 21:35
Hi,
I was directed to this issue via https://github.com/flutter/flutter/issues/104134

I have same issue as noted above https://github.com/flutter/flutter/issues/25232#issuecomment-600208893

Essentially, taking a picture when the phone is in landscape mode saves the image sidweways.

I noticed actually this issue started with the camera plugin version 0.9.0 and onwards.
Previously we used 0.8.1+3 which was working fine.

What I noticed now is if the app is fixed in portrait mode via setPreferredOrientations(...)
then rotating the phone 90 degrees to take a picture will just save it sideways as portrait.

Is there a way to not have a fixed orientation on the camera even though the app itself is always portrait mode?

I was able to reproduce the issue using the camera example from the official flutter plugin page - though I had to add logic to call setPreferredOrientations(...) to keep the app in portraitUp mode.

https://github.com/flutter/plugins/blob/main/packages/camera/camera/example/lib/main.dart

**Comment by grvsaxena419** [comment] 2023-03-19 18:58
I'm facing this as well, just wondering if this has been fixed or if there are any mitigations to store the image in the correct orientation.

**Comment by juanfactor88** [comment] 2023-08-15 16:49
Im facing the same issue, any updates on this?

**Comment by russell-g5628** [comment] 2023-11-06 05:24
Galaxy A Services Always~

**Comment by TecHaxter** [comment] 2024-01-23 11:16
![image](https://github.com/flutter/flutter/assets/52215338/e5fecfe9-1ee4-4336-b809-8b80b3db07aa)

Check the height and width values, its giving a landscape right image
Although the controller is initialized with locked device orientation to portrait up
`
   await _controller!.initialize();
   await _controller!.lockCaptureOrientation(DeviceOrientation.portraitUp);
`

**Comment by quoc-huynh-cosee** [comment] 2024-06-19 07:22
I'm also experiencing it on a Xiaomi 12 Lite. Any updates on this?

**Comment by darshankawar** [comment] 2024-07-02 11:26
Revisiting the issue, I used the latest camera plugin [example](https://github.com/flutter/packages/tree/main/packages/camera/camera/example), ran on S10 using latest stable version in which I observed that the photo taken and shown in the preview is in correct order, as below:

<img width="338" alt="Screenshot 2024-07-02 at 4 54 46 PM" src="https://github.com/flutter/flutter/assets/67046386/96335f2a-cf9b-4c56-b384-931da58f5137">

@ThinkDigitalSoftware can you try the same again at your end and confirm ?

**Comment by ThinkDigitalSoftware** [comment] 2024-07-23 15:26
I cannot confirm anymore. I am no longer developing. Thank you for the work
though!

**Closed** 2024-07-23 15:32 UTC
Labels: e: device-specific, platform-android, customer: crowd, p: camera, package, P2, team-android, triaged-android
