### ISSUE TITLE
`flutter test integration_test` fails assert `Matrix4 entries must be finite.`

### ISSUE THREAD

**Issue by corecode** [flutter/flutter#96097] opened 2022-01-04 07:22 UTC
## Steps to Reproduce

1. `flutter create -t plugin --platforms android matrix4_assert`
2. `cd matrix4_assert && mkdir integration_test`
3. Add code sample in `integration_test/simple_test.dart`
4. Execute `flutter test integration_test` 

**Expected results:** 
No exceptions.

**Actual results:** 
`EXCEPTION CAUGHT BY SCHEDULER LIBRARY`

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets("succeeds", (WidgetTester tester) async {
    expect(1 + 1, equals(2));
  });
}
```

</details>

<details>
  <summary>Logs</summary>

```
00:15 +0: loading /home/corecode/tmp/matrix4_assert/example/integration_test/simple_test.dart                                                                              [ +119 ms] executing: /opt/android-sdk/platform-tools/adb -s 94GAY0P7LW shell pm list packages com.example.matrix4_assert_example
[  +99 ms] Installing APK.
[        ] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /opt/android-sdk/platform-tools/adb -s 94GAY0P7LW install -t -r /home/corecode/tmp/matrix4_assert/example/build/app/outputs/flutter-apk/app.apk
00:19 +0: loading /home/corecode/tmp/matrix4_assert/example/integration_test/simple_test.dart                                                                              [+4263 ms] Performing Streamed Install
           Success
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 4.3s)
[   +1 ms] executing: /opt/android-sdk/platform-tools/adb -s 94GAY0P7LW shell echo -n 1dcae4f6acc6773f86aa76ceb6df6167fe76cdd1 >
/data/local/tmp/sky.com.example.matrix4_assert_example.sha1
[  +41 ms] executing: /opt/android-sdk/platform-tools/adb -s 94GAY0P7LW shell -x logcat -v time -t 1
00:20 +0: loading /home/corecode/tmp/matrix4_assert/example/integration_test/simple_test.dart                                                                              [ +167 ms] --------- beginning of main
           01-03 23:17:10.103 I/Finsky  ( 3070): [444] ibv.run(2): Wrote row to frosting DB: 78579
[  +19 ms] executing: /opt/android-sdk/platform-tools/adb -s 94GAY0P7LW shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true
--ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.matrix4_assert_example/com.example.matrix4_assert_example.MainActivity
[ +104 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.matrix4_assert_example/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
00:22 +0: loading /home/corecode/tmp/matrix4_assert/example/integration_test/simple_test.dart                                                                              [+1945 ms] Observatory URL on device: http://127.0.0.1:41231/nqsCbV28osg=/
[   +2 ms] executing: /opt/android-sdk/platform-tools/adb -s 94GAY0P7LW forward tcp:0 tcp:41231
[  +16 ms] 38131
[        ] Forwarded host port 38131 to device port 41231 for Observatory
[   +5 ms] test 0: Connecting to vm service
[  +12 ms] test 0: Observatory uri is available at http://127.0.0.1:38131/nqsCbV28osg=/
[ +645 ms] test 0: Finding the correct isolate with the integration test service extension
00:23 +0: loading /home/corecode/tmp/matrix4_assert/example/integration_test/simple_test.dart                                                                              [ +205 ms] test 0: connected to test device, now awaiting test result
[   +1 ms] test 0: Waiting for test harness or tests to finish
00:24 +0: succeeds                                                                                                                                                         
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Matrix4 entries must be finite.
'dart:ui/painting.dart':
Failed assertion: line 59 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      _matrix4IsValid (dart:ui/painting.dart:59:10)
#3      SceneBuilder.pushTransform (dart:ui/compositing.dart:301:12)
#4      TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1677:27)
#5      ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:938:5)
#6      RenderView.compositeFrame (package:flutter/src/rendering/view.dart:226:37)
#7      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:501:18)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#12     LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1450:13)
#13     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 17 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:24 +0 -1: succeeds [E]                                                                                                                                                  
  Test failed. See exception logs above.
  The test description was: succeeds
  
00:24 +0 -1: (tearDownAll)                                                                                                                                                 [+1959 ms] test 0: Test harness is no longer needed by test process
[        ] test 0: finished
[        ] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[   +1 ms] executing: /opt/android-sdk/platform-tools/adb -s 94GAY0P7LW shell am force-stop com.example.matrix4_assert_example
[   +1 ms] test 0: Test process is no longer needed by test harness
00:25 +0 -1: (tearDownAll)                                                                                                                                                 [ +144 ms] executing: /opt/android-sdk/platform-tools/adb -s 94GAY0P7LW uninstall com.example.matrix4_assert_example
00:26 +0 -1: (tearDownAll)                                                                                                                                                 [+1042 ms] Success
[   +1 ms] test 0: deleting temporary directory
[   +1 ms] test 0: finished
00:26 +0 -1: Some tests failed.                                                                                                                                            
[  +19 ms] test package returned with exit code 1
[   +4 ms] "flutter test" took 26,945ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:470:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[  +64 ms] ensureAnalyticsSent: 62ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
Analyzing example...                                            
No issues found! (ran in 1.5s)
```

```
[✓] Flutter (Channel stable, 2.8.1, on Arch Linux 5.15.12-arch1-1, locale en_DK.UTF-8)
    • Flutter version 2.8.1 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.0
    • cmake version 3.22.1
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 62.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Pixel 3a (mobile) • 94GAY0P7LW • android-arm64 • Android 12 (API 31)
    • Linux (desktop)   • linux      • linux-x64     • Arch Linux 5.15.12-arch1-1

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment] 2022-01-04 09:32
Hi @corecode, Thanks for filing the issue. I just verified and the test seems to be passing as expected

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>


<details>
<summary>logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 matrix4_assert % flutter test integration_test
00:00 +0: loading /Users/mahesh/Desktop/matrix4_assert/integration_test/simple_test.dart                                       AndroidManifest.xml could not be found.
Please check /Users/mahesh/Desktop/matrix4_assert/android/app/src/main/AndroidManifest.xml for errors.
00:00 +0 -1: loading /Users/mahesh/Desktop/matrix4_assert/integration_test/simple_test.dart [E]                                
  Exception: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.
  package:flutter_tools/src/base/common.dart 10:3                    throwToolExit
  package:flutter_tools/src/android/gradle.dart 753:3                _exitWithUnsupportedProjectMessage
  package:flutter_tools/src/android/gradle.dart 233:7                AndroidGradleBuilder.buildGradleApp
  package:flutter_tools/src/android/gradle.dart 179:11               AndroidGradleBuilder.buildApk
  package:flutter_tools/src/android/android_device.dart 578:29       AndroidDevice.startApp
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/integration_test_device.dart 53:39  IntegrationTestTestDevice.start
  
00:00 +0 -1: Some tests failed.                                                                                                
mahesh@Maheshs-MacBook-Air-M1 matrix4_assert % cd example 
mahesh@Maheshs-MacBook-Air-M1 example % flutter test integration_test
00:00 +0: loading /Users/mahesh/Desktop/matrix4_assert/example/integration_test/simple_test.dart                               RWarning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
02:03 +0: loading /Users/mahesh/Desktop/matrix4_assert/example/integration_test/simple_test.dart                         123.2s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
02:05 +0: loading /Users/mahesh/Desktop/matrix4_assert/example/integration_test/simple_test.dart                               I02:19 +0: loading /Users/mahesh/Desktop/matrix4_assert/example/integration_test/simple_test.dart                          14.6s
02:23 +1: All tests passed!                                                                                                    
```
</details>

**Comment by corecode** [comment] 2022-01-04 19:51
Not for me, seems there maybe are some differences in the software stack somewhere?

**Comment by maheshmnj** [comment] 2022-01-05 05:52
@corecode, just to confirm are you adding the `integration_test`  to example or the plugin project? If the latter it fails with 
` unsupported Gradle project error`

```
mahesh@Maheshs-MacBook-Air-M1 matrix4_assert % flutter test integration_test 
00:00 +0: loading /Users/mahesh/Desktop/matrix4_assert/integration_test/simple_test.dart                                       AndroidManifest.xml could not be found.
Please check /Users/mahesh/Desktop/matrix4_assert/android/app/src/main/AndroidManifest.xml for errors.
00:00 +0 -1: loading /Users/mahesh/Desktop/matrix4_assert/integration_test/simple_test.dart [E]                                
  Exception: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.
  package:flutter_tools/src/base/common.dart 10:3                    throwToolExit
  package:flutter_tools/src/android/gradle.dart 753:3                _exitWithUnsupportedProjectMessage
  package:flutter_tools/src/android/gradle.dart 233:7                AndroidGradleBuilder.buildGradleApp
  package:flutter_tools/src/android/gradle.dart 179:11               AndroidGradleBuilder.buildApk
  package:flutter_tools/src/android/android_device.dart 578:29       AndroidDevice.startApp
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/integration_test_device.dart 53:39  IntegrationTestTestDevice.start
  
00:00 +0 -1: Some tests failed. 
```

**Comment by corecode** [comment] 2022-01-05 06:28
Sorry, I did not write the steps correctly, it should be:

1. `flutter create -t plugin --platforms android matrix4_assert`
2. `cd matrix4_assert/example && mkdir integration_test`
3. Add code sample in `integration_test/simple_test.dart`
4. Execute `flutter test integration_test` in `example`

**Comment by maheshmnj** [comment] 2022-01-05 06:42
Thanks for the update, However, I am not able to reproduce the error with the above reproducible steps, The tests in the example do pass as per my [previous response](https://github.com/flutter/flutter/issues/96097#issuecomment-1004652171) on both macOS and Ubuntu. Labeling this issue for further investigation.

**Comment by goderbauer** [comment] 2022-01-05 23:01
I am going to close this since it doesn't reproduce and there's not much we can do with this.

**Closed by goderbauer** 2022-01-05 23:01 UTC
Labels: framework, platform-linux, passed first triage, integration_test

**Comment by corecode** [comment] 2022-01-05 23:28
But the message said I should report it, because 

```
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
```

**Comment by IstvanMunkacsi** [comment] 2022-01-19 15:40
In my case, 'just_audio_background' caused the same exception in tests. Removing it from pubspec resolved the issue
