### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by byte-art** [flutter/flutter#139040] opened 2023-11-27 06:06 UTC
## Command
```
flutter attach
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:324:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.7, on Microsoft Windows [版本 10.0.22621.2715], locale zh-CN)
    • Flutter version 3.3.7 on channel stable at D:\flutter_sdk\flutter_3.3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (1 year, 1 month ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\android_sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = D:\android_sdk
    • Java binary at: D:\android_ide\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2020.3)
    • Android Studio at D:\android_ide\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.73.1)
    • VS Code at C:\Users\86187\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • SM G9910 (mobile) • R3CN90TMM8K • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [版本 10.0.22621.2715]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 119.0.6045.160
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 119.0.2151.72

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.buddy.flutter_buddy
**iOS bundle identifier**: com.buddy.flutterBuddy
**Creation channel**: stable
**Creation framework version**: 1aafb3a8b9b0c36241c5f5b34ee914770f015818
### Plugins
app_settings-4.1.6
audio_session-0.1.18
catcher-0.7.0
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
device_info-2.0.2
device_info_plus-7.0.1
file_selector_linux-0.9.2
file_selector_macos-0.9.3+1
file_selector_windows-0.9.3
flutter_boost-4.2.0
flutter_image_compress-1.1.0
flutter_inappwebview-5.7.2+3
flutter_keyboard_visibility-5.2.0
flutter_keyboard_visibility_web-2.0.0
flutter_mailer-2.1.1
flutter_plugin_android_lifecycle-2.0.15
fluttertoast-8.2.4
geolocator-7.7.0
geolocator_android-2.1.0
geolocator_apple-1.2.2
geolocator_web-2.0.6
google_maps_flutter-2.3.0
google_maps_flutter_android-2.4.16
google_maps_flutter_ios-2.2.3
google_maps_flutter_web-0.5.3
image_gallery_saver-1.7.1
image_picker-0.8.9
image_picker_android-0.8.7+4
image_picker_for_web-2.2.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_windows-0.2.1
just_audio-0.9.36
just_audio_web-0.4.9
local_auth-2.1.2
local_auth_android-1.0.31
local_auth_ios-1.1.3
local_auth_windows-1.0.8
package_info-2.0.2
package_info_plus-3.1.2
path_provider-2.1.0
path_provider_android-2.1.0
path_provider_foundation-2.3.0
path_provider_linux-2.2.0
path_provider_windows-2.2.0
permission_handler-8.1.6
sentry_flutter-6.22.0
share_extend-2.0.0
shared_preferences-2.2.0
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.3
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0
sqflite-2.2.8+4
url_launcher-6.0.10
url_launcher_linux-2.0.3
url_launcher_macos-2.0.3
url_launcher_web-2.0.18
url_launcher_windows-2.0.2
video_player-2.3.0
video_player_android-2.4.3
video_player_avfoundation-2.4.2
video_player_web-2.0.15
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment] 2023-11-27 10:15
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77581.

**Closed by danagbemava-nc** 2023-11-27 10:15 UTC
Labels: in triage
