### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by Piyush-Banik** [flutter/flutter#72234] opened 2020-12-13 12:22 UTC
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:26:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:677:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1165:11)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:264:11)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:960:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _runZoned (dart:async/zone.dart:1630:10)
#15     runZoned (dart:async/zone.dart:1550:10)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 1.22.3, on Microsoft Windows [Version 10.0.19042.610], locale en-IN)
    • Flutter version 1.22.3 at E:\Flutter\flutter
    • Framework revision 8874f21e79 (6 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\infot\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: E:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.3+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
image_gallery_saver-1.2.2
path_provider-1.6.7
path_provider_macos-0.0.4+1
permission_handler-4.4.0+hotfix.4
share-0.6.4
thumbnails-1.0.1
url_launcher-5.4.5
url_launcher_macos-0.0.1+2
url_launcher_web-0.1.0+2
video_player-0.10.9+1
video_player_web-0.1.1+1
wakelock-0.1.4+1

**Comment by iapicca** [comment] 2020-12-13 16:05
@Piyush-Banik  
please note this [comment](https://github.com/flutter/flutter/issues/69565#issuecomment-720414673)

> This issue is already fixed and merged, but only available in master. Please see [this](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004) comment.
> Please switch to latest master and try again to see if it works.
> I am going ahead and closing this as fixed. If you disagree or think the issue is still occuring on master, write in comments and I'll reopen.
> Thanks.

**Comment by TahaTesser** [comment] 2020-12-14 09:32
Closing as duplicate of https://github.com/flutter/flutter/issues/69565

**Closed by TahaTesser** 2020-12-14 09:32 UTC
