### ISSUE TITLE
TextField doesn't support Delete-Shortcuts on macOS

### ISSUE THREAD

**Issue by wottpal** [flutter/flutter#81667] opened 2021-05-03 08:38 UTC
Inside of `TextFields` I can move the cursor with my arrow keys. I can also combine them with either Option/Alt (to move the cursor over words) and CMD (to move the cursor to the beginning/end of a line). **But what not works** is combining those modifier keys with Backspace to delete text:

* Option/Alt + Backspace to delete the last word is not working
* CMD + Backspace to delete until the beginning of the current line is not working

What I also noticed I can't press ESC to clear the active text-selection (but I guess this is content for even a new ticket).

Thanks in advance!

**Comment by TahaTesser** [comment] 2021-05-03 12:08
Hi @wottpal 

> 
> Option/Alt + Backspace to delete the last word is not working
> CMD + Backspace to delete until the beginning of the current line is not working
> 


Thanks for filing the issue,  I can reproduce both issues on the `stable` and `beta`, the issue seems to be fixed on later channels `dev` and `master`.

Reproduced on the following channels
|  `stable`  |  `beta`  | `dev` | `master` |
| :---: | :---: | :---: |:---: |
|  ✅  | ✅   | ❌ | ❌ |


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (3 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

```console
[✓] Flutter (Channel beta, 2.2.0-10.2.pre, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.2.0-10.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision b5017bf8de (5 days ago), 2021-04-28 17:09:53 -0700
    • Engine revision 91ed51e05c
    • Dart version 2.13.0 (build 2.13.0-211.13.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
		
</details>

> What I also noticed I can't press ESC to clear the active text-selection (but I guess this is content for even a new ticket).

Pressing `ESC` with text selected doesn't do anything on any channel, please file a new issue  for this,  thank you

**Comment by wottpal** [comment] 2021-05-04 07:24
I can confirm it's working on the `dev` channel (didn't hat time to test both). This is great! 😍 
I would love to see this development pace in many other desktop-related tickets, too.

Have a nice day

**Comment by TahaTesser** [comment] 2021-05-04 09:45
@wottpal 
Thanks for the confirmation, let the issue be open for desktop team , thanks

**Comment by gspencergoog** [comment] 2021-05-06 20:22
I was not able to reproduce the problem on master. Closing as fixed.

**Closed by gspencergoog** 2021-05-06 20:22 UTC
Labels: P4, a: desktop, a: text input, f: material design, found in release: 2.0, found in release: 2.2, framework, has reproducible steps, platform-mac
