### ISSUE TITLE
"No MaterialLocalizations found" when device Language is Azerbaijni

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#40106] opened 2019-09-09 20:41 UTC
we are getting "No MaterialLocalizations found" error

tried with country code without and using fromSubtags same error only for Azerbaijani language.

```
return EasyLocalizationProvider(
        data: data,
        child: MaterialApp(
          localizationsDelegates: [
            // AppTranslations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            EasylocaLizationDelegate(
              locale: data.locale,
              path: 'lib/assets/lang',
            ),
            //
          ],
          supportedLocales: [
            const Locale('en', 'US'),
            const Locale('tr', 'TR'),
            const Locale('ru', 'RU'),
            // const Locale('az'),
            // const Locale('az', 'AZ'),
            const Locale.fromSubtags(
                languageCode: "az", scriptCode: "Latn", countryCode: "AZ")
          ],
```

**Comment by BondarenkoStas** [comment] 2019-09-10 14:11
@Xgamefactory please provide your ```flutter doctor -v``` output.

**Comment by Xgamefactory** [comment] 2019-09-11 23:17
```
Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.737], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\D\SDK\flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\D\SDK\android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1
```

**Comment by Xgamefactory** [comment] 2020-04-11 15:51
Thanks support team )

**Comment by TahaTesser** [comment] 2020-07-02 12:01
Hi @Xgamefactory 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/aissat/easy_localization/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-02 12:01 UTC
Labels: a: internationalization, f: material design, framework
