### ISSUE TITLE
Flutter build process should not write to the sdk location, so flutter can be installed as a system level sdk on linux.

### ISSUE THREAD

**Issue by safield** [flutter/flutter#76177] opened 2021-02-17 02:42 UTC
I have two users on my linux machine for development.

Currently I must install two instances of the flutter sdk for it to work smoothly. It would be nice if I only had to install one sdk folder at a root location. Then, only for sdk updates I would need root access.

The current issue is that running build commands writes files to the flutter sdk folder. For example I get the following error after I built a flutter project as one user, and then tried to build a project as another user.

```
Flutter failed to write to a file at "/usr/local/flutter-sdk/bin/cache/libimobiledevice.stamp". The flutter tool cannot access the file.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

```

Ideally, generated files related to builds should be placed in a temporary .flutter folder in the home folder, so the sdk folder does not have user written files.

**Comment by gspencergoog** [comment] 2021-02-18 19:14
This is a duplicate of https://github.com/flutter/flutter/issues/44526

**Closed by gspencergoog** 2021-02-18 19:14 UTC
Labels: a: desktop, passed first triage, platform-linux, proposal, tool
