### ISSUE TITLE
Flutter Web does not render on Android when using desktop mode

### ISSUE THREAD

**Issue by KevMorelli** [flutter/flutter#154296] opened 2024-08-28 21:04 UTC
### Steps to reproduce

1. Create a new project
2. Host it on the web or use `flutter run -d web-server --web-port 5000 --web-hostname 0.0.0.0` command
3. Access the page from either an Android emulator or physical device using Chrome web browser
4. Enable browser desktop mode

### Expected results

Page would render as if it was a desktop device

### Actual results

Page is entirely white, nothing renders.

Extra notes:
We forced the render engine with `--web-renderer html` and the page renders without problem, we think it may be a problem with canvaskit.
I also added `eruda` to the project which is a console for mobile devices but I didn't saw any specific error in there.

### Code sample

<details open><summary>Code sample</summary>

main.dart
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
    <base href="$FLUTTER_BASE_HREF" />

    <meta charset="UTF-8" />
    <meta content="IE=Edge" http-equiv="X-UA-Compatible" />
    <meta name="description" content="A new Flutter project." />

    <!-- iOS meta tags & icons -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-title" content="tesssttt" />
    <link rel="apple-touch-icon" href="icons/Icon-192.png" />

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="favicon.png" />

    <title>tesssttt</title>
    <link rel="manifest" href="manifest.json" />
  </head>
  <body>
    <script src="flutter_bootstrap.js" async></script>
    <script src="https://cdn.jsdelivr.net/npm/eruda"></script>
    <script>
      eruda.init();
    </script>
  </body>
</html>
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Here you can see the problem when switching between mobile and desktop mode on an android phone

https://github.com/user-attachments/assets/6031aa9f-70c9-4219-9b35-2ce94c39e0f5

</details>

### Logs

<details open><summary>Logs</summary>

```console
❯ flutter run -d web-server --web-port 5000 --web-hostname 192.168.1.126 --verbose
[   +2 ms] executing: sw_vers -productName
[   +8 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +7 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.5
[        ] executing: sw_vers -buildVersion
[   +7 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23F79
[        ] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] arm64
[   +2 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +44 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +109 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[        ] Xcode 15.2
           Build version 15C500b
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcdevice list --timeout 5
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +25 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] Skipping pub get: version match.
[  +63 ms] Generating /Users/kev/Desktop/testflutterweb/tesssttt/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +61 ms] Launching lib/main.dart on Web Server in debug mode...
[  +52 ms] Initializing file store
[   +4 ms] Skipping target: gen_localizations
[   +1 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Updating assets
[  +59 ms] Waiting for connection from debug service on Web Server...
[  +45 ms] shaderc command: [/Users/Kev/Dev/SDK/Flutter/bin/cache/artifacts/engine/darwin-x64/impellerc, --sksl, --iplr, --json, --sl=build/flutter_assets/shaders/ink_sparkle.frag,
--spirv=build/flutter_assets/shaders/ink_sparkle.frag.spirv, --input=/Users/Kev/Dev/SDK/Flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag,
--include=/Users/Kev/Dev/SDK/Flutter/packages/flutter/lib/src/material/shaders, --include=/Users/Kev/Dev/SDK/Flutter/bin/cache/artifacts/engine/darwin-x64/shader_lib]
[ +146 ms] <- reset
[   +2 ms] /Users/Kev/Dev/SDK/Flutter/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev /Users/Kev/Dev/SDK/Flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root
/Users/Kev/Dev/SDK/Flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --experimental-emit-debug-metadata --output-dill
/var/folders/3w/yd_8n51j2t742g9jq247l9g40000gn/T/flutter_tools.AmVFqD/flutter_tool.wCj1El/app.dill --packages /Users/kev/Desktop/testflutterweb/tesssttt/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /var/folders/3w/yd_8n51j2t742g9jq247l9g40000gn/T/flutter_tools.AmVFqD/flutter_tools.y4JBpw
--filesystem-scheme org-dartlang-app --initialize-from-dill build/80b1a4cf4e7b90e1ab5f72022a0bc624.cache.dill.track.dill --platform
file:///Users/Kev/Dev/SDK/Flutter/bin/cache/flutter_web_sdk/kernel/ddc_outline_sound.dill --verbosity=error --sound-null-safety
[   +5 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+4971 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,3",
                        "identifier" : "8599B138-4D7C-4E72-87E1-3CFB39AF880A",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-11-4th-1",
                        "modelName" : "iPad Pro (11-inch) (4th generation)",
                        "name" : "iPad Pro (11-inch) (4th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,17",
                        "identifier" : "F7EBEB40-A297-4FC3-A628-AA41A2DF7F87",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-air5-1",
                        "modelName" : "iPad Air (5th generation)",
                        "name" : "iPad Air (5th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,4",
                        "identifier" : "27F8A4A1-06CC-4FF8-92FD-322737F46926",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-1",
                        "modelName" : "iPhone 15",
                        "name" : "iPhone 15",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,17",
                        "identifier" : "18C30949-7799-4B7A-A578-92AA2C333A01",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-air5-1",
                        "modelName" : "iPad Air (5th generation)",
                        "name" : "iPad Air (5th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,3",
                        "identifier" : "3380202F-C0CE-4FF5-8752-79A6F3D43795",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-11-4th-1",
                        "modelName" : "iPad Pro (11-inch) (4th generation)",
                        "name" : "iPad Pro (11-inch) (4th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,5",
                        "identifier" : "214E2C95-CEC9-46FB-93F1-BCB31FAEDF7E",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-plus-1",
                        "modelName" : "iPhone 15 Plus",
                        "name" : "iPhone 15 Plus",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,5",
                        "identifier" : "D8E375AD-59D3-4324-B402-EFC6DA08C6F4",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-12point9-6th-1",
                        "modelName" : "iPad Pro (12.9-inch) (6th generation)",
                        "name" : "iPad Pro (12.9-inch) (6th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,5",
                        "identifier" : "23108761-6949-47BC-A9B6-0DFB26FF6850",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-plus-1",
                        "modelName" : "iPhone 15 Plus",
                        "name" : "iPhone 15 Plus",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,6",
                        "identifier" : "EE7CECFC-3AFA-498B-B2FD-94CDFB34F12E",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-se3-1",
                        "modelName" : "iPhone SE (3rd generation)",
                        "name" : "iPhone SE (3rd generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "CC4A565B-ECBB-4FFB-8315-F12D0BD2156F",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,1",
                        "identifier" : "A92A8580-1BA0-44BF-B199-3D9162CDBB67",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-1",
                        "modelName" : "iPhone 15 Pro",
                        "name" : "iPhone 15 Pro",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,18",
                        "identifier" : "45CA782E-B79C-4C82-8F0C-90A8BFBA924A",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-10-1",
                        "modelName" : "iPad (10th generation)",
                        "name" : "iPad (10th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "C4BB20AE-3A57-4225-ADF9-04C4B5A5E5E2",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,18",
                        "identifier" : "1558F85A-594E-42FE-9E1F-D6E6684C0E8A",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-10-1",
                        "modelName" : "iPad (10th generation)",
                        "name" : "iPad (10th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,5",
                        "identifier" : "D29AD856-0A56-4573-90C5-46EF2389F419",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-12point9-6th-1",
                        "modelName" : "iPad Pro (12.9-inch) (6th generation)",
                        "name" : "iPad Pro (12.9-inch) (6th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,1",
                        "identifier" : "E11C0F43-6EBE-4D0E-917C-1878C0A69B75",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-1",
                        "modelName" : "iPhone 15 Pro",
                        "name" : "iPhone 15 Pro",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,1",
                        "identifier" : "D1127E93-74D2-4F9F-9844-6AA6C9ABA3CA",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-mini6-1",
                        "modelName" : "iPad mini (6th generation)",
                        "name" : "iPad mini (6th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,6",
                        "identifier" : "C4548405-99E9-4C94-85CF-F977752C707B",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-se3-1",
                        "modelName" : "iPhone SE (3rd generation)",
                        "name" : "iPhone SE (3rd generation)",
                        "ignored" : false
                      },
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookPro17,1",
                        "simulator" : false,
                        "modelName" : "MacBook Pro",
                        "operatingSystemVersion" : "14.5 (23F79)",
                        "identifier" : "00008103-000E454236C0801E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "arm64e",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookpro-13-retina-touchid-late-2020"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,1",
                        "identifier" : "A9196BE3-65CA-405E-A6F9-450F2586CE81",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-mini6-1",
                        "modelName" : "iPad mini (6th generation)",
                        "name" : "iPad mini (6th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.2 (21C62)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,4",
                        "identifier" : "7718001F-91D7-476F-AF49-5408FE48B735",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-1",
                        "modelName" : "iPhone 15",
                        "name" : "iPhone 15",
                        "ignored" : false
                      }
                    ]
[   +2 ms] executing: /usr/bin/arch -arm64e xcrun devicectl --version
[  +50 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun devicectl --version
[        ] 355.7.7
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun devicectl list devices --timeout 5 --json-output
/var/folders/3w/yd_8n51j2t742g9jq247l9g40000gn/T/flutter_tools.AmVFqD/core_devices.ZrucSw/core_device_list.json
[+1055 ms] No devices found.
[        ] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/3w/yd_8n51j2t742g9jq247l9g40000gn/T/flutter_tools.AmVFqD/core_devices.ZrucSw/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "355.7.7"
             },
             "result" : {
               "devices" : [

               ]
             }
           }

[+1531 ms] Waiting for connection from debug service on Web Server... (completed in 7.8s)
[        ] Synced 42.0MB.
[        ] <- accept
[        ] Caching compiled dill
[  +16 ms] lib/main.dart is being served at http://192.168.1.126:5000
[        ] The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[   +2 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale en-AR)
    • Flutter version 3.24.1 on channel stable at /Users/Kev/Dev/SDK/Flutter
    ! Warning: `flutter` on your path resolves to /Users/kev/Dev/SDK/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/Kev/Dev/SDK/Flutter. Consider adding
      /Users/Kev/Dev/SDK/Flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/kev/Dev/SDK/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/Kev/Dev/SDK/Flutter. Consider adding
      /Users/Kev/Dev/SDK/Flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (8 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kev/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (2 available)            
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.85

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-29 07:29
Hi @KevMorelli, this is a duplicate of https://github.com/flutter/flutter/issues/154162. 

Kindly follow up in the issue linked above for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-08-29 07:29 UTC
Labels: in triage
