### ISSUE TITLE
Cross-Compiling Flutter Engine requires host sysroot

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#55516] opened 2020-04-24 00:30 UTC
This is building in master.

When Cross Compiling the engine using the below flags, it's assuming gclient hook ran, which installs an unrelated sysroot than that which I point to via --target-sysroot.

  --runtime-mode debug
  --embedder-for-target
  --disable-desktop-embeddings
  --full-dart-sdk
  --enable-fontconfig
  --target-os linux
  --linux-cpu arm
  --target-sysroot ${STAGING_DIR_TARGET}
  --target-triple cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi

```
| ERROR: Execution of '/media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/temp/run.do_configure.26416' failed with exit code 1:
| ERROR at //build/config/sysroot.gni:32:5: Assertion failed.
|     assert(
|     ^-----
| Missing sysroot (/media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/git/src/build/linux/debian_sid_amd64-sysroot). To fix, run: build/linux/sysroot_scripts/install-sysroot.py --arch=x64
| See //build/config/sysroot.gni:33:9:
|         exec_script("//build/dir_exists.py", [ sysroot ], "string") == "True",
|         ^--------------------------------------------------------------------
| This is where it was set.
| See //build/config/linux/pkg_config.gni:5:1: whence it was imported.
| import("//build/config/sysroot.gni")
| ^----------------------------------
| See //build/config/linux/BUILD.gn:5:1: whence it was imported.
| import("//build/config/linux/pkg_config.gni")
| ^-------------------------------------------
| See //build/config/BUILDCONFIG.gn:352:33: which caused the file to be included.
|   _native_compiler_configs += [ "//build/config/linux:sdk" ]
|                                 ^-------------------------
| Generating GN files in: out/linux_debug_unopt_arm
| WARNING: exit code 1 from a shell command.
```

**Comment by stuartmorgan** [comment] 2020-04-24 03:54
What are `current_toolchain` and `default_toolchain` in your build? It looks like the condition there is too restrictive.

You should be able to set `use_default_linux_sysroot` to false in your args, but that's a workaround; we should figure out the right set of conditions to handle this case in sysroot.gni.

**Comment by jwinarske** [comment] 2020-04-24 15:18
With this change
```
diff --git a/build/config/sysroot.gni b/build/config/sysroot.gni
index fb0f3c3..00ddad2 100644
--- a/build/config/sysroot.gni
+++ b/build/config/sysroot.gni
@@ -19,6 +19,10 @@ declare_args() {
   xcode_toolchain = ""
 }
 
+print("current_toolchain", current_toolchain)
+print("default_toolchain", default_toolchain)
+print("target_sysroot", target_sysroot)
+
 if (current_toolchain == default_toolchain && target_sysroot != "") {
   sysroot = target_sysroot
 } else if (is_android) {
@@ -45,6 +49,8 @@ if (current_toolchain == default_toolchain && target_sysroot != "") {
   sysroot = ""
 }
 
+print("sysroot", sysroot)
+
 if ((is_mac || is_ios) && xcode_toolchain == "") {
   xcode_toolchain = exec_script("//build/config/mac/xcode_toolchain.py",
                                 [],
```

I get

```
./flutter/tools/gn --runtime-mode debug --embedder-for-target --full-dart-sdk --enable-fontconfig --target-os linux --linux-cpu arm --arm-float-abi hard --target-triple arm-linux-gnueabihf --target-sysroot /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot --target-toolchain /media/joel/SolidState/LLVM8.0 --disable-desktop-embeddings
Generating GN files in: out/linux_debug_arm
current_toolchain //build/toolchain/custom:custom
default_toolchain //build/toolchain/custom:custom
target_sysroot /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot
sysroot /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot
current_toolchain //build/toolchain/linux:clang_x64
default_toolchain //build/toolchain/custom:custom
target_sysroot /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot
sysroot /media/joel/SolidState/engine/src/build/linux/debian_sid_amd64-sysroot
Done. Made 395 targets from 187 files in 211ms
```

**Comment by jwinarske** [comment] 2020-04-24 15:48
I believe linux:clang_x64 is coming from third_party/dart/runtime.  As without `use_default_linux_sysroot = false` I have seen to toolchain switch from target to host:
```
[809/1673] /media/joel/SolidState/LLVM8.0/bin/clang++ -MD -MF obj/third_party/skia/src/ports/typeface_freetype.SkFontHost_FreeType_common.o.d --target=arm-linux-gnueabihf --sysroot /media/joel/SolidState/rpi/rpi0w/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot -DUSE_OPENSSL=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DSK_R32_SHIFT=16 -DSK_DISABLE_REDUCE_OPLIST_SPLITTING -DSK_ENABLE_DUMP_GPU -DSK_DISABLE_AAA -DSK_DISABLE_READBUFFER -DSK_DISABLE_EFFECT_DESERIALIZATION -DSK_SUPPORT_LEGACY_DIDCONCAT44 -DSK_DISABLE_LEGACY_SHADERCONTEXT -DSK_DISABLE_LOWP_RASTER_PIPELINE -DSK_FORCE_RASTER_PIPELINE_BLITTER -DSK_GL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../third_party/libcxxabi/include -I../../third_party/skia -I../../third_party/freetype2/include -fno-strict-aliasing -fstack-protector --param=ssp-buffer-size=4 -march=armv6 -mfloat-abi=hard -fPIC -pipe -pthread -fcolor-diagnostics -mfpu=vfp -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -fvisibility=hidden --sysroot=/media/joel/SolidState/rpi/rpi0w/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot -Wstring-conversion -Wnewline-eof -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -Wno-unused-function -Wno-unused-variable -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fno-exceptions -c ../../third_party/skia/src/ports/SkFontHost_FreeType_common.cpp -o obj/third_party/skia/src/ports/typeface_freetype.SkFontHost_FreeType_common.o
[810/1673] ../../buildtools/linux-x64/clang/bin/clang++ -MD -MF clang_x64/obj/third_party/dart/runtime/bin/gen_snapshot.snapshot_utils.o.d -DEXCLUDE_CFE_AND_KERNEL_PLATFORM -DUSE_OPENSSL=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNDEBUG -DDART_PRECOMPILER -DTARGET_ARCH_ARM -DTARGET_OS_LINUX -I../../third_party/dart/runtime -I../../third_party -I../.. -Iclang_x64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../third_party/libcxxabi/include -I../../third_party/dart/runtime/include -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -fno-strict-aliasing -fstack-protector --param=ssp-buffer-size=4 -m64 -march=x86-64 -fPIC -pipe -pthread -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -fvisibility=hidden -Wstring-conversion -Wnewline-eof -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Wno-conversion-null -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fno-exceptions   -c ../../third_party/dart/runtime/bin/snapshot_utils.cc -o clang_x64/obj/third_party/dart/runtime/bin/gen_snapshot.snapshot_utils.o

```

**Comment by jwinarske** [comment] 2020-04-24 16:17
Actually I'm hitting the above regardless the state of `use_default_linux_sysroot`.  Looks like `custom_toolchain` is not checked and it defaults to host.

**Comment by jwinarske** [comment] 2020-04-24 17:37
I see this go away when I set `--target-toolchain` to `buildtools/linux-x64/clang`.

So between these two workarounds I now make it to the [icui18n plurrule.cpp error](https://github.com/dart-lang/sdk/issues/40850).

**Comment by jwinarske** [comment] 2020-04-24 21:16
I'm not sure `target_cpu` gets assigned on a host build, but this is what I'm using for now.  Happy to make PRs for this stuff.

```
diff --git a/build/config/sysroot.gni b/build/config/sysroot.gni
index fb0f3c3..69bbf7e 100644
--- a/build/config/sysroot.gni
+++ b/build/config/sysroot.gni
@@ -27,7 +27,7 @@ if (current_toolchain == default_toolchain && target_sysroot != "") {
 } else if (is_linux && !is_chromeos) {
   if (current_cpu == "mipsel") {
     sysroot = rebase_path("//mipsel-sysroot/sysroot")
-  } else if (use_default_linux_sysroot && !is_fuchsia && current_cpu == "x64") {
+  } else if (use_default_linux_sysroot && !is_fuchsia && target_cpu == "x64") {
     sysroot = rebase_path("//build/linux/debian_sid_amd64-sysroot")
     assert(
         exec_script("//build/dir_exists.py", [ sysroot ], "string") == "True",
```

**Comment by jwinarske** [comment] 2020-04-25 00:50
This was one of three patches required to build armv7 with CIPD Clang 11.

**Comment by stuartmorgan** [comment] 2020-04-25 01:58
Looking at your output it seems to me like this is working as intended. You have two passes, one for the target, and one for the host.

Target:
```
current_toolchain //build/toolchain/custom:custom
default_toolchain //build/toolchain/custom:custom
target_sysroot /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot
sysroot /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot
```
As expected, it's using your `target_sysroot`.

Host:
```
current_toolchain //build/toolchain/linux:clang_x64
default_toolchain //build/toolchain/custom:custom
target_sysroot /media/joel/SolidState/rpi/rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/flutter-engine/git-r0/recipe-sysroot
sysroot /media/joel/SolidState/engine/src/build/linux/debian_sid_amd64-sysroot
```
You haven't done anything to change the host sysroot, so it's using the default host sysroot.

So then my only question is when you said:
> it's assuming gclient hook ran
why didn't it? Did you bypass it somehow? If so, then I retract my earlier statement that `use_default_linux_sysroot = false` is a workaround; if you are running the host build in its default configuration, then you need the default host sysroot.

**Comment by jwinarske** [comment] 2020-04-25 07:43
Yocto (virtual host) provides a sand boxed sysroot.  I don't run hooks to minimize build time.  I'm not overriding `use_default_linux_sysroot` anywhere.

`gclient.py sync --nohooks --no-history --revision ${SRCREV} ${PARALLEL_MAKE} -v`

So the patches and config I'm currently using generate so for both armv7 and aarch.  Looks like the same should work for x86 and x86_64.  I'll confirm in the next few days.

**Comment by stuartmorgan** [comment] 2020-04-25 15:32
> I don't run hooks to minimize build time. I'm not overriding `use_default_linux_sysroot` anywhere.

Then closing this as WAI. You either need to get the default sysroot for the host portion of the build, or you need to set `use_default_linux_sysroot` to false to say you don't want to use it.

**Closed by stuartmorgan** 2020-04-25 15:32 UTC
