### ISSUE TITLE
Firestore Handling empty document name passed in by a var Type variable on Iphone issue 

### ISSUE THREAD

**Issue by FlatCodeIq** [flutter/flutter#62196] opened 2020-07-24 14:15 UTC
## Issue

The below Issue only happens on **Iphones**. My Android was working normally.

The below is a code to extract a **shopID** stored in an invoice under a document name called **'driverAssigned'**.
The document Name (**'driverAssigned'**) is an entry in a map called **invoiceMap**. this map is also being loaded from firestore earlier. 
By default new invoices has **invoiceMap['driverAssigned'] = ''**  Which is an **empty string.** not **null**.
if the below firestore call doesn't find the document or receive a null for a document name or even a space, it will throw an error and the Try Catch will be triggered.
If the below firestore call received a **''** for a document name, it will crash the app **with no error messages and without Try Catch being triggered.** The app simply closes immediately. and even print() around it didn't indicate where the app was exactly stopping.
```

await _firestoreDatabaseReference
          .collection('Drivers')
          .document(invoiceMap['driverAssigned'])
          .get()
          .then((value) => shopID = value.data['DriverAssignedTo']);


```

I fixed the above flaw by writing
```

await _firestoreDatabaseReference
          .collection('Drivers')
          .document(invoiceMap['driverAssigned'] == ''
              ? null
              : invoiceMap['driverAssigned'])
          .get()
          .then((value) => shopID = value.data['DriverAssignedTo']);

```

My question is, why is Try Catch not being triggered? and why does it only behave that way on Iphone? is the compilation for IOS has a flaw where it can't handle empty document name, or is it related to Firestore handling .document('').get() differently than Android?

**Comment by TahaTesser** [comment] 2020-07-24 15:07
Hi @FlatCodeIq 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-24 15:07 UTC
