### ISSUE TITLE
urllauncher\WebViewActivity.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#39423] opened 2019-08-28 19:01 UTC
`Note: C:\Users\user\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.1.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
`

**Comment by Jayant11** [comment] 2019-08-29 00:19
@Xgamefactory Which Gradle version are you using?

**Comment by BondarenkoStas** [comment] 2019-08-29 13:07
Duplicate of #37616

**Closed** 2019-08-29 13:08 UTC
Labels: p: url_launcher

**Comment by iamshubhamsaurav** [comment] 2020-07-26 06:08
Try changing the minSdkVerion to a higher version. I changed the minSdkVerion from 16 to 23 and it worked. Go to the app/build.gradle file and changing the version.

**Comment by bwerere** [comment] 2020-08-28 12:35
I tried the minSdkVersion from 16 to 23 even after flutter clean and it did not work. Still having the issue.

**Comment by tony123S** [comment] 2020-09-01 08:04
not working for me too. I'm using `Flutter 1.20.2 • channel stable `

**Comment by leszekkrol** [comment] 2020-10-16 07:45
Not working for me too Flutter (Channel dev, 1.23.0-18.0.pre)

**Comment by yaroaxito** [comment] 2020-10-23 13:39
I am having the same problem.
