### ISSUE TITLE
opened keyboard moves UP and DOWN the google map plugin when switch between apps

### ISSUE THREAD

**Issue by bogdannedelcu** [flutter/flutter#29089] opened 2019-03-09 07:44 UTC
## Steps to Reproduce

The app contains a `StatefulWidget` with `Scaffold` having `Drawer` and `GoogleMap` plugin.

Steps to reproduce:
1. Open the built sample app
2. Open Safari and click address bar to open keyboard
3. Switch to the sample app.
4. See how map bumps up and 

See movie keyboard moves map.MOV

I see it happen only on iOS. 

link to source code and recorded video: https://drive.google.com/drive/folders/1_oaZLIAqFQ82Eg_Gcn9X0I59Vto3TR5k?usp=sharing

## Logs

`flutter run --verbose` 
does not produce any logs after starting the app on iPhone

`flutter analyze` 
does not return any  issues

Not sure if we used properly the plugin. 
Thank you for helping with this issue. 

`flutter doctor -v`
```
[✓] Flutter (Channel master, v1.3.9-pre.37, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.3.9-pre.37 at /Users/bogdannedelcu/Developpment/flutter
    • Framework revision ac6afa4d20 (4 hours ago), 2019-03-08 19:26:45 -0800
    • Engine revision c48774cfe0
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 2fb6cd9f5f)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bogdannedelcu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

```

main file is bellow:

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:maps_testing/new_screen.dart';

class MapScreen extends StatefulWidget {
  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  GoogleMapController mapController;
  var _scaffoldKey = GlobalKey<ScaffoldState>();

  bool markersVisible = true;

  String error;


  @override
  Widget build(BuildContext context) {
    double _screenWidth = MediaQuery.of(context).size.width;
    double _screenHeight = MediaQuery.of(context).size.height;
    return Scaffold(
        key: _scaffoldKey,
        drawer: Drawer(
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            child: Center(
              child: Text('Press anywhere to test the bug'),
            ),
            onTap: () {
              Navigator.pop(context);
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => NewScreen(),
                ),
              );
            },
          ),
        ),
        body: Stack(children: <Widget>[
          Align(
            alignment: Alignment.topCenter,
            child: SizedBox(
              width: _screenWidth,
              height: _screenHeight,
              child: GoogleMap(
                initialCameraPosition: CameraPosition(
                  bearing: 0.0,
                  target: LatLng(48.8566,2.3522),
                  tilt: 0.0,
                  zoom: 18.0,
                ),
                mapType: MapType.normal,
                onMapCreated: _onMapCreated,
                tiltGesturesEnabled: false,
                compassEnabled: false,
              ),
            ),
          ),

        ]));
  }

  void _onMapCreated(GoogleMapController controller) {
    _showMarkers(markersVisible, controller);

//    setState(() {});
  }



  void _showMarkers(bool flag, GoogleMapController controller) {
    if (flag == true) {
      setState(() {
        mapController = controller;
        mapController.clearMarkers();
        mapController.onMarkerTapped.add((marker) {
          setState(() {});
        });

        mapController.addMarker(
          MarkerOptions(
              position: LatLng(44.496113, 26.131699),
              infoWindowText:
              InfoWindowText("Mega Image", "Strada George Bacovia"),
              icon: BitmapDescriptor.defaultMarkerWithHue(
                  BitmapDescriptor.hueGreen),
              consumeTapEvents: false),
        );

        mapController.addMarker(
          MarkerOptions(
              position: LatLng(44.4110224, 26.0712143),
              infoWindowText:
              InfoWindowText("Mega Image", "Bulevardul Lacul Tei"),
              icon: BitmapDescriptor.defaultMarkerWithHue(
                  BitmapDescriptor.hueGreen),
              consumeTapEvents: false),
        );
      });
    }
  }
}
```

**Comment by bogdannedelcu** [comment] 2019-03-10 05:43
Hello @dnfield, with the same codebase I reported this issue some days ago. https://github.com/flutter/flutter/issues/28920#issuecomment-470626727
Please add it also to Goals as it is blocking for an app using Map control. 
Thank you,
Bogdan

**Comment by bogdannedelcu** [comment] 2019-03-22 19:30
cc @amirh

**Comment by amirh** [comment] 2019-03-28 23:22
@iskakaushik

**Comment by iskakaushik** [comment] 2019-03-29 00:10
@bogdannedelcu , could you please check if this issue happens with web-view as well. That would help us determine if this is a general platform views issue or just has to do with maps. Thanks!

**Comment by bogdannedelcu** [comment] 2019-04-04 14:20
Hi @iskakaushik , I checked with WebView, in the existing code I just replaced GoogleMap widget with WebView widget. The glitch happens there too. All the screen moves up and down, including the bottom floating action button which is on top the native view.

I checked with a sample where the google map plugin is not full screen and I see the issue does not reproduce.

I do not consider this urgent, instead I watch closely the google map markers size on iOS where we have an urgent need to be corrected https://github.com/flutter/flutter/issues/24865. I see you work on the PR... looking forward...

Thank you for the good work!

**Comment by bogdannedelcu** [comment] 2019-06-03 05:02
Hi @iskakaushik , just a kind reminder on this one. Seems related to platform views. Thank you

**Comment by bogdannedelcu** [comment] 2019-06-13 11:29
September means January 2020 for stable branch... 😭

**Comment by TahaTesser** [comment] 2021-04-21 13:37
Hi @bogdannedelcu 
This seems to be fixed, I cannot reproduce on a simulator or physical device

### Preview
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/48603081/115563003-bee40580-a2bf-11eb-9629-78713b6d4a9c.gif)




<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MapScreen(),
    );
  }
}

class MapScreen extends StatefulWidget {
  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  GoogleMapController mapController;
  var _scaffoldKey = GlobalKey<ScaffoldState>();

  bool markersVisible = true;

  String error;

  @override
  Widget build(BuildContext context) {
    double _screenWidth = MediaQuery.of(context).size.width;
    double _screenHeight = MediaQuery.of(context).size.height;
    return Scaffold(
        key: _scaffoldKey,
        drawer: Drawer(
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            child: Center(
              child: Text('Press anywhere to test the bug'),
            ),
            onTap: () {
              Navigator.pop(context);
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => NewScreen(),
                ),
              );
            },
          ),
        ),
        body: Stack(children: <Widget>[
          Align(
            alignment: Alignment.topCenter,
            child: SizedBox(
              width: _screenWidth,
              height: _screenHeight,
              child: GoogleMap(
                initialCameraPosition: CameraPosition(
                  bearing: 0.0,
                  target: LatLng(48.8566, 2.3522),
                  tilt: 0.0,
                  zoom: 18.0,
                ),
                mapType: MapType.normal,
                onMapCreated: _onMapCreated,
                tiltGesturesEnabled: false,
                compassEnabled: false,
              ),
            ),
          ),
        ]));
  }

  void _onMapCreated(GoogleMapController controller) {
    _showMarkers(markersVisible, controller);

//    setState(() {});
  }

  void _showMarkers(bool flag, GoogleMapController controller) {
    if (flag == true) {
      setState(() {
        mapController = controller;
        // mapController.clearMarkers();
        // mapController.onMarkerTapped.add((marker) {
        //   setState(() {});
        // });

        // mapController.addMarker(
        //   MarkerOptions(
        //       position: LatLng(44.496113, 26.131699),
        //       infoWindowText:
        //       InfoWindowText("Mega Image", "Strada George Bacovia"),
        //       icon: BitmapDescriptor.defaultMarkerWithHue(
        //           BitmapDescriptor.hueGreen),
        //       consumeTapEvents: false),
        // );

        // mapController.addMarker(
        //   MarkerOptions(
        //       position: LatLng(44.4110224, 26.0712143),
        //       infoWindowText:
        //       InfoWindowText("Mega Image", "Bulevardul Lacul Tei"),
        //       icon: BitmapDescriptor.defaultMarkerWithHue(
        //           BitmapDescriptor.hueGreen),
        //       consumeTapEvents: false),
        // );
      });
    }
  }
}

class NewScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(),
        body: Center(
          child: Text(
            'Annoying bug incoming...',
            softWrap: true,
          ),
        ),
      );
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (5 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 89.0.4389.128

• No issues found!
```
	
</details>


Closing as fixed, If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-21 13:37 UTC
Labels: P4, p: first party, p: maps, platform-ios, plugin
