### ISSUE TITLE
[Android][PlatformView] Screen Flicker Caused by Hybrid Composition (Regression)

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#157286] opened 2024-10-21 18:24 UTC
### Steps to reproduce

When using Hybrid Composition, platformView causes a screen flicker upon widget load, impacting the entire screen. This flickering affects the entire screen. To reproduce the issue, please run the code provided in the Code sample section.
This issue is currently affecting our production environment, degrading the user experience. We would highly appreciate a hotfix or guidance on a possible workaround to resolve this as soon as possible.

### Expected results

Screen should load without a flickering effect

### Actual results

Screen is loaded with a flickering effect, see video section.

### Code sample

<details open><summary>Code sample</summary>

**Code Repository:**
https://github.com/delfme/flutter-native-text-input-repo
This sample app comprises 2 screens, the second screen contains a EditText field which is a platformView using HC.

To reproduce the issue:
- Launch the app.
- Tap the "Chat Screen" button to navigate to a new screen.

**Issue Description:**
During the screen transition animation, a flickering issue occurs. On some devices, this also causes noticeable jank, affecting the smoothness of the animation.

NOTE:
1. Our native text field has consistently worked well with Hybrid Composition (HC), so we suspect that this issue may be related to recent changes in the Flutter engine.
2. We are unable to use Texture Layer Hybrid Composition (TLHC) due to unresolved bugs reported in a separate issue: https://github.com/flutter/flutter/issues/139230#issuecomment-2426710122

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/186c59d4-b5d1-4c93-9da8-dc7afdb82fd7

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.27.0-1.0.pre.123, on macOS 14.2.1 23C71 darwin-arm64, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (5 available)
[✓] Network resources

```

</details>

**Comment by jonahwilliams** [comment] 2024-10-21 19:16
Duplicate of https://github.com/flutter/flutter/issues/152263

**Closed by jonahwilliams** 2024-10-21 19:16 UTC

**Comment by delfme** [comment] 2024-10-21 20:06
Hello @jonahwilliams, could you advise which master version we should downgrade to in order to avoid this issue until a fix is released? Also, is the latest beta affected as well? Thank you!
