### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by madhumb** [flutter/flutter#82164] opened 2021-05-10 06:19 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=11D6C542-CB35-43ED-8C8E-BACC57AD0D01 --start-paused --flavor=caregiver --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main_files/main_caregiver.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SentinelException
```

```
```
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-IN)
    • Flutter version 2.3.0-0.1.pre at /Users/madhubhilawadi/Repository/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d72bfb8d07 (2 weeks ago), 2021-04-26 06:05:55 -0700
    • Engine revision de6e1adf97
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/madhubhilawadi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.55.2)
    • VS Code at /Users/madhubhilawadi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 11D6C542-CB35-43ED-8C8E-BACC57AD0D01 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.93
    ! Error: Madhu's iPhone  is not connected. Xcode will continue when Madhu's iPhone  is connected. (code -13)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b1395592de68cc8ac4522094ae59956dd21a91db
### Plugins
path_provider_linux-2.0.0
path_provider_windows-2.0.1
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0

**Comment by darshankawar** [comment] 2021-05-10 09:17
Closing this as duplicate of https://github.com/flutter/flutter/issues/78214

**Closed by darshankawar** 2021-05-10 09:17 UTC
Labels: in triage
