### ISSUE TITLE
[webview_flutter] onPageFinished provides a wrong url

### ISSUE THREAD

**Issue by Aulig** [flutter/flutter#73428] opened 2021-01-06 20:51 UTC
## Steps to Reproduce

1. Create a new flutter project
2. Add webview_flutter 1.0.7 as a dependency
3. Use this as your main.dart:
```
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: WebViewExample()));

class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  final Completer<WebViewController> _controller = Completer<WebViewController>();

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
        // This drop down menu demonstrates that Flutter widgets can be shown over the web view.
        actions: <Widget>[
          NavigationControls(_controller.future),
        ],
      ),
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl: 'https://pelseason.com/',
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
          onPageStarted: (String url) async {
            print('onPageStarted reports URL: $url');
            print("Actual url (onPageStarted): ${await (await _controller.future).currentUrl()}");
          },
          onPageFinished: (String url) async {
            print('onPageFinished reports URL: $url');
            print("Actual url (onPageFinished): ${await (await _controller.future).currentUrl()}");
          },
          gestureNavigationEnabled: true,
        );
      }),
    );
  }
}

class NavigationControls extends StatelessWidget {
  const NavigationControls(this._webViewControllerFuture) : assert(_webViewControllerFuture != null);

  final Future<WebViewController> _webViewControllerFuture;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<WebViewController>(
      future: _webViewControllerFuture,
      builder: (BuildContext context, AsyncSnapshot<WebViewController> snapshot) {
        final bool webViewReady = snapshot.connectionState == ConnectionState.done;
        final WebViewController controller = snapshot.data;
        return Row(
          children: <Widget>[
            IconButton(
              icon: const Icon(Icons.arrow_back_ios),
              onPressed: !webViewReady
                  ? null
                  : () async {
                      if (await controller.canGoBack()) {
                        await controller.goBack();
                      } else {
                        // ignore: deprecated_member_use
                        Scaffold.of(context).showSnackBar(
                          const SnackBar(content: Text("No back history item")),
                        );
                        return;
                      }
                    },
            ),
            IconButton(
              icon: const Icon(Icons.arrow_forward_ios),
              onPressed: !webViewReady
                  ? null
                  : () async {
                      if (await controller.canGoForward()) {
                        await controller.goForward();
                      } else {
                        // ignore: deprecated_member_use
                        Scaffold.of(context).showSnackBar(
                          const SnackBar(content: Text("No forward history item")),
                        );
                        return;
                      }
                    },
            ),
            IconButton(
              icon: const Icon(Icons.replay),
              onPressed: !webViewReady
                  ? null
                  : () {
                      controller.reload();
                    },
            ),
          ],
        );
      },
    );
  }
}

```
4. Click a link from the navigation menu of the displayed website.
5. Check the printed urls.

**Expected results:** 

The url provided by onPageFinished should be the url of the page that just finished loading.

**Actual results:** 

On Android the url provided by onPageFinished does not match the url of the page that just finished loading. Calling WebViewController.currentUrl() returns the correct url though.
Additionally, onPageStarted is not called.

On iOS it doesn't call onPageFinished at all.

I'm not sure, but maybe the website is using javascript to change the displayed website content and using history.pushState() (https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) to set the URL? In that case onPageFinished() should still provide the correct current URL. Consistency between Android and iOS would be great too.

**Comment by darshankawar** [comment] 2021-01-07 07:33
@Aulig 
Tried your code sample and noticed that on Android, the `onPageFinished` returns correct url:

```
I/flutter (22324): onPageFinished reports URL: https://www.pelseason.com/
I/flutter (22324): Actual url (onPageFinished): https://www.pelseason.com/transfers
I/flutter (22324): onPageFinished reports URL: https://www.pelseason.com/
I/flutter (22324): Actual url (onPageFinished): https://www.pelseason.com/createateam
```

Although on iOS, it doesn't show the respective url:

```
flutter: onPageStarted reports URL: https://pelseason.com/
flutter: Actual url (onPageStarted): https://pelseason.com/
flutter: onPageFinished reports URL: https://www.pelseason.com/
flutter: Actual url (onPageFinished): https://www.pelseason.com/
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by Aulig** [comment] 2021-01-07 09:10
I think it doesn't report the right url in the android logs you posted, as the printed "actual url" differs from the one given by onpagefinished, right?

**Comment by darshankawar** [comment] 2021-01-07 11:51
@Aulig ah I see. I was looking at `Actual url (onPageFinished):` which prints correct url that I tapped. So the expected behavior is `onPageFinished reports URL:` and `Actual url (onPageFinished):` should print same url.

**Comment by Aulig** [comment] 2021-01-07 12:09
Yes, exactly! I should've explained it more clearly :)

**Comment by danagbemava-nc** [comment] 2021-08-12 10:02
As of `master 2.5.0-6.0.pre.63` and `stable 2.2.3` with `webview_flutter: ^2.0.12`, I cannot reproduce the issue on `iOS` and `android`.

Closing issue and labelling as fixed. If anyone still experiences this issue kindly provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you


<details>
<summary>logs</summary>

```console
flutter: onPageFinished reports URL: https://flutter.dev/
flutter: Actual url (onPageFinished): https://flutter.dev/
flutter: onPageFinished reports URL: https://flutter.dev/
flutter: Actual url (onPageFinished): https://flutter.dev/
flutter: onPageFinished reports URL: https://flutter.dev/docs/development/ui/widgets-intro
flutter: Actual url (onPageFinished): https://flutter.dev/docs/development/ui/widgets-intro
flutter: onPageFinished reports URL: https://mobile.twitter.com/flutterdev
flutter: Actual url (onPageFinished): https://mobile.twitter.com/flutterdev
flutter: onPageFinished reports URL: https://flutter.dev/docs/development/ui/widgets-intro#global-keys
flutter: Actual url (onPageFinished): https://flutter.dev/docs/development/ui/widgets-intro#global-keys
flutter: onPageFinished reports URL: https://flutter.dev/
flutter: Actual url (onPageFinished): https://flutter.dev/

```
</details>

<details>
<summary> flutter doctor -v </summary>

```console
[✓] Flutter (Channel master, 2.5.0-6.0.pre.63, on macOS 11.5.1 20G80 darwin-arm,
    locale en-GH)
    • Flutter version 2.5.0-6.0.pre.63 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 047d35d8ba (2 hours ago), 2021-08-12 12:47:05 +0800
    • Engine revision a2e60472a9
    • Dart version 2.15.0 (build 2.15.0-5.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)         • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 12 (API 31) (emulator)
    • Nexus’ IPhone (mobile)      • 00008020-001875E83A38002E • ios            •
      iOS 14.6 18F72
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)         • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 12 (API 31) (emulator)
    • Nexus’ IPhone (mobile)      • 00008020-001875E83A38002E • ios            •
      iOS 14.6
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Closed by danagbemava-nc** 2021-08-12 10:02 UTC
Labels: plugin, p: first party, p: webview, has reproducible steps, P4, found in release: 1.22

**Comment by Aulig** [comment] 2021-08-12 10:45
The original page I tested this with does no longer exist. I tried to replicate the issue, but couldn't anymore, so I guess it's fixed, yes :)
