### ISSUE TITLE
The system cannot find the file specified after switching to Flutter master channel

### ISSUE THREAD

**Issue by ari-0** [flutter/flutter#160654] opened 2024-12-20 09:56 UTC
### Steps to reproduce

1: Install or upgrade Flutter to the latest stable version (3.27.1):
flutter upgrade

2: Switch to the master channel by running:
flutter channel master

3: Attempt to run any Flutter command, such as:
flutter doctor

### Expected results

```
Flutter Doctor Output:
[✓] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.27.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 463d0668f1 (6 days ago), 2024-12-14 15:15:17 +0100
    • Engine revision 92d8b65f12
    • Dart version 3.5.0
    • DevTools version 2.24.0

[✓] Windows Version (Installed)
    • Windows 10, version 22H2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"` to install it.
    • Android Studio not found; unable to find bundled Java version.
    • Try updating or reinstalling Android Studio.
    • Try re-installing or updating Android SDK tools.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.7.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.5
    • Windows 10 SDK version 10.0.19041.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 118.0.5993.89

[✓] Network resources
    • All connected resources are available.

! Doctor found issues in 1 category.
```

### Actual results

 flutter  Doctor:  
The system cannot find the file specified.
cb4b5fff73850b2e42bd4de7cb9a4310a78ac40d was unexpected at this time.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by maheshj01** [comment] 2024-12-21 00:02
Hi @ari-0, Thanks for filing the issue. Looks like the master channel switch didn't completely download the flutter sdk, 

> The system cannot find the file specified.
cb4b5fff73850b2e42bd4de7cb9a4310a78ac40d was unexpected at this time.

Do you have the complete logs of the error, this doesn't really give much info?

For me the master channel switch went through

<details>
<summary>flutter channel 'master'</summary>

```console
 mahesh@MacBook-Pro-2 platform_stack_test % flutter upgrade
flutterFlutter is already up to date on channel stable
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (4 days ago) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2
 %                                                                                                                
mahesh@MacBook-Pro-2 platform_stack_test % flutter channel master
Switching to flutter channel 'master'...

Upgrading engine...
Downloading Darwin arm64 Dart SDK from Flutter engine 33d7f8a1b307dc46fe969facf0e1feba6f40aeb2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  5  229M    5 11.7M    0     0  14.4M      0  0:00:15 --:--:--  0:00:15 14.4M
 17  229M   17 40.8M    0     0  22.4M      0  0:00:10  0:00:01  0:00:09 22.4M
 31  229M   31 72.1M    0     0  24.6M      0  0:00:09  0:00:02  0:00:07 24.6M
 52  229M   52  120M    0     0  30.8M      0  0:00:07  0:00:03  0:00:04 30.8M
 65  229M   65  151M    0     0  31.7M      0  0:00:07  0:00:04  0:00:03 31.7M
 81  229M   81  188M    0     0  32.4M      0  0:00:07  0:00:05  0:00:02 35.3M
 95  229M   95  218M    0     0  32.3M      0  0:00:07  0:00:06  0:00:01 36.0M
100  229M  100  229M    0     0  31.8M      0  0:00:07  0:00:07 --:--:-- 36.7M
Building flutter tool...
Downloading android-arm-profile/darwin-x64 tools...                752ms
Downloading android-arm-release/darwin-x64 tools...                252ms
Downloading android-arm64-profile/darwin-x64 tools...              296ms
Downloading android-arm64-release/darwin-x64 tools...              279ms
Downloading android-x64-profile/darwin-x64 tools...                352ms
Downloading android-x64-release/darwin-x64 tools...                299ms
Downloading android-x86 tools...                                   641ms
Downloading android-x64 tools...                                   688ms
Downloading android-arm tools...                                   791ms
Downloading android-arm-profile tools...                           482ms
Downloading android-arm-release tools...                           474ms
Downloading android-arm64 tools...                                 881ms
Downloading android-arm64-profile tools...                         740ms
Downloading android-arm64-release tools...                         489ms
Downloading android-x64-profile tools...                           668ms
Downloading android-x64-release tools...                           493ms
Downloading android-x86-jit-release tools...                       691ms
Downloading ios tools...                                         2,415ms
Downloading ios-profile tools...                                 1,322ms
Downloading ios-release tools...                                 1,324ms
Downloading Web SDK...                                           2,474ms
Downloading CanvasKit...                                           704ms
Downloading package sky_engine...                                  237ms
Downloading flutter_patched_sdk tools...                           407ms
Downloading flutter_patched_sdk_product tools...                   450ms
Downloading darwin-arm64 tools...                                1,021ms
Downloading darwin-x64/FlutterMacOS.framework tools...           1,382ms
Downloading darwin-x64/gen_snapshot tools...                       420ms
Downloading darwin-x64-profile/FlutterMacOS.framework tools...        740ms
Downloading darwin-x64-profile tools...                            282ms
Downloading darwin-x64-profile/gen_snapshot tools...               397ms
Downloading darwin-x64-release/FlutterMacOS.framework tools...        560ms
Downloading darwin-x64-release tools...                            266ms
Downloading darwin-x64-release/gen_snapshot tools...               430ms
Downloading darwin-arm64/font-subset tools...                      225ms
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
mahesh@MacBook-Pro-2 platform_stack_test % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
Could not load custom device from config index 0: Expected enabled to be a boolean.
[✓] Flutter (Channel master, 3.7.0-15.0.pre.16, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[!] Android Studio (version 2024.1)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.94.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
````
</details>

**Comment by ari-0** [comment] 2024-12-21 07:37
Thanks for your response! After switching to the master channel, none of the Flutter commands work, including flutter doctor. Every command produces the same error:This makes it challenging to gather additional logs or diagnostics.

I’ve tried:

Clearing the bin/cache directory.
Verifying my network connection.
Attempting to switch channels again manually.
Unfortunately, the issue persists. Do you have any suggestions for resolving this or alternative ways to debug?
and here is new message that shows,

`flutter channel master
Switching to flutter channel 'master'...

Upgrading engine...
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d...
Expanding downloaded archive with PowerShell...
Building flutter tool...
Running pub upgrade...
Resolving dependencies...
Downloading packages...
Got dependencies.
Downloading android-arm-profile/windows-x64 tools...             1,463ms
Downloading android-arm-release/windows-x64 tools...             1,269ms
Downloading android-arm64-profile/windows-x64 tools...           1,387ms
Downloading android-arm64-release/windows-x64 tools...           1,362ms
Downloading android-x64-profile/windows-x64 tools...             1,298ms
Downloading android-x64-release/windows-x64 tools...             1,241ms
Downloading android-x86 tools...                                 2,672ms
Downloading android-x64 tools...                                 2,677ms
Downloading android-arm tools...                                    4.1s
Downloading android-arm-profile tools...                            3.7s
Downloading android-arm-release tools...                         1,708ms
Downloading android-arm64 tools...                                  3.0s
Downloading android-arm64-profile tools...                       1,822ms
Downloading android-arm64-release tools...                       1,777ms
Downloading android-x64-profile tools...                         1,828ms
Downloading android-x64-release tools...                         1,705ms
Downloading Web SDK...                                              9.4s
Downloading package sky_engine...                                1,124ms
Downloading package flutter_gpu...                                 327ms
Downloading flutter_patched_sdk tools...                         1,369ms
Downloading flutter_patched_sdk_product tools...                   227ms
Downloading flutter_patched_sdk_product tools...                   363ms
Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sdk_product.zip. Ensure you have network connectivity and then try again.
Exception: 404

C:\Users\hdps>flutter doctor
Downloading package sky_engine...                                  873ms
Downloading package flutter_gpu...                                 103ms
Downloading flutter_patched_sdk tools...                           496ms
Downloading flutter_patched_sdk_product tools...                   649ms
Downloading flutter_patched_sdk_product tools...                   404ms
Failed to download
https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sd
k_product.zip. Ensure you have network connectivity and then try again.
Exception: 404

C:\Users\hdps>flutter doctor
Downloading package sky_engine...                                  632ms
Downloading package flutter_gpu...                                 353ms
Downloading flutter_patched_sdk tools...                           493ms
Downloading flutter_patched_sdk_product tools...                   243ms
Downloading flutter_patched_sdk_product tools...                   419ms
Failed to download
https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sd
k_product.zip. Ensure you have network connectivity and then try again.
Exception: 404

C:\Users\hdps>curl -I https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sdk_product.zip
HTTP/1.1 404 Not Found
X-GUploader-UploadID: AFiumC7SyTz3dto73oi7NTEAFsz3f3agRWYmM50exPsABrIsB846j81l2oMAYsN5G9vAXbw5
Content-Type: application/xml; charset=UTF-8
Content-Length: 264
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type
Date: Sat, 21 Dec 2024 07:31:29 GMT
Expires: Sat, 21 Dec 2024 07:31:29 GMT
Cache-Control: private, max-age=0
Server: UploadServer
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000


C:\Users\hdps>flutter doctor
Downloading package sky_engine...                                  926ms
Downloading package flutter_gpu...                                 106ms
Downloading flutter_patched_sdk tools...                           776ms
Downloading flutter_patched_sdk_product tools...                   519ms
Downloading flutter_patched_sdk_product tools...                   509ms
Failed to download
https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sd
k_product.zip. Ensure you have network connectivity and then try again.
Exception: 404`

**Comment by DanTup** [comment] 2024-12-21 10:59
I see the same issue, I'm unable to do anything on current master.

I suspect this is the same issue in https://github.com/flutter/flutter/issues/160704 ?

**Comment by sma** [comment] 2024-12-21 11:39
I get this exception:
```
flutter upgrade  
Flutter is already up to date on channel main
Flutter 3.28.0-2.0.pre.38568 • channel main •
https://github.com/flutter/flutter.git
Framework • revision 7df127b1ee (6 hours ago) • 2024-12-20 21:23:04 -0800
Engine • revision 7df127b1ee
Tools • Dart 3.7.0 (build 3.7.0-267.0.dev) • DevTools 2.41.0
sma@MacBook-Pro-von-Stefan tellorium_poc % flutter doctor -v
Downloading package sky_engine...                                  594ms
Downloading package flutter_gpu...                                  38ms
Downloading flutter_patched_sdk tools...                         1.199ms
Downloading flutter_patched_sdk_product tools...                   134ms
Downloading flutter_patched_sdk_product tools...                   205ms
Failed to download
https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0
d42eedd00190e2c4ade3d/flutter_patched_sdk_product.zip. Ensure you have network
connectivity and then try again.
Exception: 404
```

Looking at <https://storage.googleapis.com/flutter_infra_release/>, I see a long XML where the latest `flutter_patched_sdk_product.zip` is

```
<Contents>
<Key>flutter/0014e0353aa9b2947ff38cc9c9aad8741e5999f7/flutter_patched_sdk_product.zip</Key>
<Generation>1714597161998195</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2024-05-01T20:59:22.105Z</LastModified>
<ETag>"1bfbe3ef0e0cba8d47041bce53e0422e"</ETag>
<Size>3747802</Size>
</Contents>
```

which is obviously the wrong one. 

I think, a critical upload is missing, breaking the flutter installation!

**Comment by jtmcdole** [comment] 2024-12-21 14:45
Duplicate of #160704

**Closed** 2024-12-23 03:58 UTC
Labels: in triage
