### ISSUE TITLE
After iOS is upgraded to 17, TextField cannot be entered on the keyboard.

### ISSUE THREAD

**Issue by wuwenwei5566** [flutter/flutter#133960] opened 2023-09-04 01:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a TextField and run it on iOS 17.1

### Expected results

Normal input

### Actual results

Unable to enter normally

### Code sample

TextField(
          autofocus: widget.autofocus,
          textAlign: widget.textAlign,
          controller: widget.controller,
          keyboardAppearance: widget.keyboardAppearance ?? _checkThemeDrak(),
          focusNode: widget.focusNode,
          scrollController: widget.scrollController,
          keyboardType: widget.keyboardType,
          textInputAction: widget.textInputAction,
          scrollPhysics: widget.scrollPhysics,
          selectionControls: widget.selectionControls,
          maxLines: widget.maxLines,
          maxLength: widget.maxLength,
          minLines: widget.minLines,
          cursorHeight: setCursorHeight(),
          cursorColor: widget.cursorColor ?? ThemeColor.themeColor(context),
          style: widget.style,
          enableInteractiveSelection: widget.enableInteractiveSelection,
          //onTap: widget.onTap,
          decoration: widget.decoration,
          onEditingComplete: widget.onEditingComplete,
          onAppPrivateCommand: widget.onAppPrivateCommand,
          onSubmitted: widget.onSubmitted,
          onChanged: widget.onChanged,
          inputFormatters: widget.inputFormatters,
          scrollPadding: widget.scrollPadding,
          textAlignVertical: widget.textAlignVertical,
          obscureText: widget.obscureText,
          obscuringCharacter: widget.obscuringCharacter,
          readOnly: widget.readOnly,
          clipBehavior: widget.clip,
        ),

### Screenshots or Video

https://github.com/flutter/flutter/assets/52393077/add9d84d-6197-4116-ab39-a4fdd7934308

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Flutter (Channel [user-branch], 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.13.2 on channel [user-branch] at /Users/wuwenwei/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision ff5b5b5fa6 (11 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

**Comment by demoYang** [comment] 2023-09-04 02:18
iOS 17.1 ?  mean  **iOS 17 beta 8** ? 
![image](https://github.com/flutter/flutter/assets/7134823/87f2bdcd-18cd-4c12-a209-6bc650a1d943)

**Comment by wuwenwei5566** [comment] 2023-09-04 02:23
![1693794127](https://github.com/flutter/flutter/assets/52393077/81c580d0-9ae6-4376-a89c-f2eb66d2b7f7)

**Comment by stuartmorgan** [comment] 2023-09-04 03:17
Closing as a duplicate of https://github.com/flutter/flutter/issues/133908

**Closed by stuartmorgan** 2023-09-04 03:17 UTC
