### ISSUE TITLE
iOS build crashes settingup firebase_messaging Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_FLTFirebaseCorePlugin", referenced from:

### ISSUE THREAD

**Issue by sandrush73** [flutter/flutter#63667] opened 2020-08-13 15:00 UTC
Hi i am trying to setup firebase for my ios project and i did add googleservices-info.plist to my runner project. i am unable to get pass this i have even tried setting it up in a empty project just with  firebase_messaging: ^6.0.16 in yaml file 

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FLTFirebaseCorePlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
  "_OBJC_CLASS_$_FLTFirebaseMessagingPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
  "_OBJC_CLASS_$_FLTFirebaseAnalyticsPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)``
```

**Comment by TahaTesser** [comment] 2020-08-18 07:39
Hi @sandrush73 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-18 07:39 UTC
