### ISSUE TITLE
Text cut off on bottom when I use to maxLines.

### ISSUE THREAD

**Issue by cakesoft-basavraj** [flutter/flutter#44802] opened 2019-11-13 08:27 UTC
## Steps to Reproduce

1) I am using Text on card view,  Text cut off on bottom when I set to maxLines property,
The two-line text will be shown properly when data comes more than four-lines it cut off bottom text.  

```
Text(
          "Text cut off on bottom when I set to maxLines property "
            maxLines: 4,
            overflow: TextOverflow.ellipsis,
            style: Themes.body2(context).copyWith(
            color: Colors.orange),
            textAlign: TextAlign.left,
        )
```

flutter doctor -v
```

[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_IN)
    • Flutter version 1.9.1+hotfix.4 at /home/flutter
    • Framework revision cc949a8e8b (7 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3

    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/Android/android-studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.35.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Moto G 4 • ZY223WTQRL • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.


```

**Comment by iapicca** [comment] 2019-11-14 10:18
Hi @cakesoft-basavraj 
does this code represent the issue you are describing?

<details>
  <summary>sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context)=> MaterialApp(home: HomePage());
}

class HomePage extends StatelessWidget {

  static const String _text =  'Text cut off on bottom when I set to maxLines property';
  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: Card(
        child: Container(
          width: 100,
          child:Text(_text,
          maxLines: 4,
          overflow: TextOverflow.ellipsis,
          textAlign: TextAlign.left,
  ),),),),);
}
```
</details>

thank you

**Comment by Tonigt** [comment] 2019-11-14 11:55
once use maxLines, will appear this situation，and TextOverflow.ellipsis 、 maxLines can not be used at the same time, it seems that TextOverflow.ellipsis has a higher priority

**Comment by Tonigt** [comment] 2019-11-14 12:11
> once use maxLines, will appear this situation，and TextOverflow.ellipsis 、 maxLines can not be used at the same time, it seems that TextOverflow.ellipsis has a higher priority

this question is only show in web

**Comment by iapicca** [comment] 2019-11-18 16:02
Hi @cakesoft-basavraj 
thank you for the clarification

case: 

```
         //maxLines: 4,
          overflow: TextOverflow.ellipsis,
```

![image](https://user-images.githubusercontent.com/45637986/69067683-327b4680-0a2c-11ea-8e1c-938a7a2c64df.png)


case: [ WEB ]

```
          maxLines: 4,
          overflow: TextOverflow.ellipsis,
```

![image](https://user-images.githubusercontent.com/45637986/69067825-6fdfd400-0a2c-11ea-88ca-0422ca582e19.png)

case: [ MOBILE ]

```
          maxLines: 4,
          overflow: TextOverflow.ellipsis,
```

![image](https://user-images.githubusercontent.com/45637986/69067921-9998fb00-0a2c-11ea-871f-514dffb34542.png)



case: 

```
          maxLines: 4,
          //overflow: TextOverflow.ellipsis,
```

![image](https://user-images.githubusercontent.com/45637986/69067921-9998fb00-0a2c-11ea-871f-514dffb34542.png)

**Comment by mdebbar** [comment] 2019-11-19 20:50
This is a known issue in the current text measurement/rendering stack (ellipsis doesn't work well with multi-line text and maxLines). There's a newer implementation that's still experimental and incomplete. This issue doesn't exist in the new implementation.

I'll work on a PR soon to make it possible for you to enable the new text measurement stack.

Here's the issue https://github.com/flutter/flutter/issues/33523

**Comment by mdebbar** [comment] 2019-11-23 00:36
As of yesterday, https://github.com/flutter/engine/pull/13929 was merged. The PR adds the ability to enable the new experimental text measurement stack which fixes this specific issue.

Please give it a try by adding the following flag to your command:
```
flutter run -d web-server --release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true
```

Make sure you run it in release mode (by using `--release`). In development mode, the `--dart-define` flag has no effect.

**Closed by mdebbar** 2019-11-23 00:36 UTC
Labels: a: quality, a: typography, severe: rendering, ☸ platform-web

**Comment by firatcetiner** [comment] 2021-06-01 11:06
@mdebbar Is there a similar workaround for non-web apps? Because I'm facing a similar issue here on both Android and iOS. The TextOverflow.ellipsis performs as TextOverflow.visible when I set maxLines. Is this an expected behavior?
