### ISSUE TITLE
Flutter desktop does not display Text widget on Linux

### ISSUE THREAD

**Issue by GioPanaro** [flutter/flutter#44886] opened 2019-11-14 05:28 UTC
No Text widgets show up anywhere on flutter desktop apps on linux. Running this code on Android works fine.

## Steps to Reproduce

1. Run the following Flutter code:

```
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show debugDefaultTargetPlatformOverride;

void main() {
  debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Test'),
        ),
        body: Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

**Target Platform:** Linux
**Target OS version/browser:** kali-rolling on kernel 5.3
**Devices:** Desktop

## Logs

```
tsrwebgl@kali:~/IdeaProjects/first_flutter_app$ flutter run --verbose
[  +18 ms] executing: [/home/tsrwebgl/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +27 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fa82b9aeac1d1fabbabdca9a0a6816f678dfccf2
[        ] executing: [/home/tsrwebgl/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.11.0-48-gfa82b9aea
[   +9 ms] executing: [/home/tsrwebgl/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/tsrwebgl/development/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +40 ms] executing: [/home/tsrwebgl/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +74 ms] executing: /home/tsrwebgl/Android/Sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /home/tsrwebgl/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +29 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] Generating /home/tsrwebgl/IdeaProjects/first_flutter_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +62 ms] Launching lib/main.dart on Linux in debug mode...
[  +10 ms] Building Linux application...
[   +2 ms] executing: make -C /home/tsrwebgl/IdeaProjects/first_flutter_app/linux BUILD=debug
[  +20 ms] make: Entering directory '/home/tsrwebgl/IdeaProjects/first_flutter_app/linux'
[        ] /home/tsrwebgl/development/flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64 debug
[+9407 ms] mkdir -p /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug
[   +1 ms] clang++  -std=c++14 -Wall -Werror  -Iflutter/ephemeral -I/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include  -MMD -c main.cc -o /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug/main.o
[ +508 ms] mkdir -p /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug/flutter
[   +1 ms] clang++  -std=c++14 -Wall -Werror  -Iflutter/ephemeral -I/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include  -MMD -c flutter/generated_plugin_registrant.cc -o
/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug/flutter/generated_plugin_registrant.o
[ +165 ms] mkdir -p /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/debug
[   +1 ms] clang++  -std=c++14 -Wall -Werror  -Iflutter/ephemeral -I/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include  /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug/main.o
/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug/flutter/generated_plugin_registrant.o
/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug//home/tsrwebgl/IdeaProjects/first_flutter_app/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.o
/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug//home/tsrwebgl/IdeaProjects/first_flutter_app/linux/flutter/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.o
/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/obj/debug//home/tsrwebgl/IdeaProjects/first_flutter_app/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.o -L/home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/debug/lib
-lflutter_linux_glfw  -Wl,-rpath=\$ORIGIN/lib -o /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/debug/flutter_desktop_example
[ +122 ms] mkdir -p /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/debug/data
[   +2 ms] rsync -rpu --delete /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/flutter_assets /home/tsrwebgl/IdeaProjects/first_flutter_app/linux/../build/linux/debug/data
[ +148 ms] make: Leaving directory '/home/tsrwebgl/IdeaProjects/first_flutter_app/linux'
[  +17 ms] Building Linux application... (completed in 10.4s)
[ +294 ms] Observatory URL on device: http://127.0.0.1:36095/nL-rWC8nMyo=/
[   +3 ms] Connecting to service protocol: http://127.0.0.1:36095/nL-rWC8nMyo=/
[ +125 ms] Successfully connected to service protocol: http://127.0.0.1:36095/nL-rWC8nMyo=/
[   +2 ms] Sending to VM service: getVM({})
[   +3 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz, operatingSystem: linux, targetCPU: x64, version: 2.7.0 (Wed Nov 13 17:56:08 2019 +0000) on "linux_x64", _profilerMode: Dart, _nativeZoneMemoryUsage: 0, p...
[   +4 ms] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: FlutterViewList, views: []}
[  +53 ms] Sending to VM service: getVM({})
[   +2 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz, operatingSystem: linux, targetCPU: x64, version: 2.7.0 (Wed Nov 13 17:56:08 2019 +0000) on "linux_x64", _profilerMode: Dart, _nativeZoneMemoryUsage: 0, p...
[   +2 ms] Sending to VM service: getIsolate({isolateId: isolates/3210589126383503})
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +2 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x2242ef0, isolate: {type: @Isolate, fixedId: true, id: isolates/3210589126383503, name: main.dart$main-3210589126383503, number: 3210589126383503}}]}
[   +4 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: first_flutter_app})
[  +15 ms] Result: {type: FileSystem, name: first_flutter_app, uri: file:///tmp/first_flutter_appUQAHGP/first_flutter_app/}
[        ] DevFS: Created new filesystem on the device (file:///tmp/first_flutter_appUQAHGP/first_flutter_app/)
[   +1 ms] Updating assets
[  +78 ms] Syncing files to device Linux...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +5 ms] /home/tsrwebgl/development/flutter/bin/cache/dart-sdk/bin/dart /home/tsrwebgl/development/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/tsrwebgl/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.SNAYNA/app.dill --packages /home/tsrwebgl/IdeaProjects/first_flutter_app/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[  +14 ms] Result: {type: Isolate, id: isolates/3210589126383503, name: main, number: 3210589126383503, _originNumber: 3210589126383503, startTime: 1573709232476, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[  +16 ms] <- compile package:first_flutter_app/main.dart
[+4327 ms] Service protocol connection closed.
[        ] Lost connection to device.
[  +23 ms] Updating files
[   +6 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57466
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57468
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57470
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57472
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57474
[        ] trying again in a few - 9 more attempts left
[ +500 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57476
[        ] trying again in a few - 8 more attempts left
[   +1 ms] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57478
[        ] trying again in a few - 8 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57480
[        ] trying again in a few - 8 more attempts left
[        ] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57482
[        ] trying again in a few - 8 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57484
[        ] trying again in a few - 8 more attempts left
[ +498 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57486
[        ] trying again in a few - 7 more attempts left
[   +1 ms] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57488
[        ] trying again in a few - 7 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57490
[        ] trying again in a few - 7 more attempts left
[        ] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57492
[        ] trying again in a few - 7 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57494
[        ] trying again in a few - 7 more attempts left
[ +498 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57496
[        ] trying again in a few - 6 more attempts left
[   +1 ms] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57498
[        ] trying again in a few - 6 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57500
[        ] trying again in a few - 6 more attempts left
[        ] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57502
[        ] trying again in a few - 6 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57504
[        ] trying again in a few - 6 more attempts left
[ +497 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57506
[        ] trying again in a few - 5 more attempts left
[   +1 ms] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57508
[        ] trying again in a few - 5 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57510
[        ] trying again in a few - 5 more attempts left
[        ] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57512
[        ] trying again in a few - 5 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57514
[        ] trying again in a few - 5 more attempts left
[ +498 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57516
[        ] trying again in a few - 4 more attempts left
[   +1 ms] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57518
[        ] trying again in a few - 4 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57520
[        ] trying again in a few - 4 more attempts left
[   +1 ms] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57522
[        ] trying again in a few - 4 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57524
[        ] trying again in a few - 4 more attempts left
[ +497 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57526
[        ] trying again in a few - 3 more attempts left
[   +2 ms] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57528
[        ] trying again in a few - 3 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57530
[        ] trying again in a few - 3 more attempts left
[   +1 ms] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57532
[        ] trying again in a few - 3 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57534
[        ] trying again in a few - 3 more attempts left
[ +497 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57536
[        ] trying again in a few - 2 more attempts left
[   +1 ms] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57538
[        ] trying again in a few - 2 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57540
[        ] trying again in a few - 2 more attempts left
[   +1 ms] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57542
[        ] trying again in a few - 2 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57544
[        ] trying again in a few - 2 more attempts left
[ +498 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57546
[        ] trying again in a few - 1 more attempts left
[        ] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57548
[        ] trying again in a few - 1 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57550
[        ] trying again in a few - 1 more attempts left
[        ] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57552
[        ] trying again in a few - 1 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57554
[        ] trying again in a few - 1 more attempts left
[ +498 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57556
[        ] trying again in a few - 0 more attempts left
[        ] Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57558
[        ] trying again in a few - 0 more attempts left
[        ] Error writing "build/flutter_assets/AssetManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57560
[        ] trying again in a few - 0 more attempts left
[        ] Error writing "build/flutter_assets/LICENSE" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57562
[        ] trying again in a few - 0 more attempts left
[        ] Error writing "build/flutter_assets/FontManifest.json" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57564
[        ] trying again in a few - 0 more attempts left
[ +498 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57566
[        ] DevFS sync failed. Lost connection to device: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57566
[   +1 ms] Syncing files to device Linux... (completed in 9,417ms, longer than expected)
[   +2 ms] "flutter run" took 20,725ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:505:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:607:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#30     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

```
Analyzing first_flutter_app...                                          
No issues found! (ran in 1.8s)

```

```
[✓] Flutter (Channel master, v1.11.1-pre.48, on Linux, locale en_US.UTF-8)
    • Flutter version 1.11.1-pre.48 at /home/tsrwebgl/development/flutter
    • Framework revision fa82b9aeac (80 minutes ago), 2019-11-14 04:08:28 +0000
    • Engine revision bb7d76248c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/tsrwebgl/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/tsrwebgl/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 8.0.1
    • GNU Make 4.2.1

[!] Android Studio (version 3.5)
    • Android Studio at /home/tsrwebgl/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /home/tsrwebgl/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.7142.36
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

! Doctor found issues in 2 categories.

```

**Comment by stuartmorgan** [comment] 2019-11-14 07:43
See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts

Closing as a duplicate of https://github.com/flutter/flutter/issues/30700

**Closed by stuartmorgan** 2019-11-14 07:43 UTC
