### ISSUE TITLE
[two_dimensional_scrollables] Request for pinned table's right columns

### ISSUE THREAD

**Issue by thanhdatvo** [flutter/flutter#146542] opened 2024-04-10 01:41 UTC
### Use case

Currently, the table widget in two_dimension_scrollable only allow to pin left columns

### Proposal

The table widget in two_dimension_scrollable should also allow to pin right columns

**Comment by huycozy** [comment] 2024-04-10 07:51
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133238 with detailed information, please follow up on it for further updates.

**Closed by huycozy** 2024-04-10 07:51 UTC
Labels: in triage
