### ISSUE TITLE
Flutter Text align Justify in Arabic RTL not working correctly 

### ISSUE THREAD

**Issue by saioufe** [flutter/flutter#45496] opened 2019-11-24 17:06 UTC
when i try to write long text in arabic language the textAlign.Justify never works (Specifically when the text contain numbers ) the numbers will break the line 

        Expanded(
          child: Container(
            child: Center(
              child: LayoutBuilder(builder: (context, c) {
                return Text(
                  textToEnter,
                  textAlign: TextAlign.justify,
                  textDirection: TextDirection.rtl,
                  style: TextStyle(
                    fontFamily: 'uthmanTnB',
                    fontSize: 22,
                  ),
                );
                // TextJustifyRTL(
                //   textToEnter,
                //   textDirection: TextDirection.rtl,
                //   style: TextStyle(fontFamily: 'uthmanTnB', fontSize: 21),
                //   boxConstraints: c,
                // );
              }),
            ),
          ),
        ),

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.1)
[√] Connected device (1 available)

• No issues found!

![Screenshot_1574614873](https://user-images.githubusercontent.com/32012762/69498134-8cc94b00-0ef5-11ea-955b-4b27e338051e.png)

**Comment by iapicca** [comment] 2019-11-25 12:01
Hi @saioufe 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/39755)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by saioufe** [comment] 2019-11-25 12:22
Hi @iapicca this issue is completely different from the one you have mentioned me with , 
my issue is from the text justification not from text selection , Please reopen the issue 
Thanks

**Comment by markusaksli-nc** [comment] 2020-08-27 10:28
Reproducible on the latest master `1.22.0-2.0.pre.93`.

<img src="https://user-images.githubusercontent.com/68219924/91431232-c2c2a380-e868-11ea-9720-5d1cd1779f29.png" height="600" />

<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                color: Colors.grey,
                height: 200,
                width: 300,
                child: Text(
                  "123132ميزة أو فائدة؟ ولكن من لديه الحق أن ينتقد شخص ما أراد أن يشعر بالسعادة التي لا تشوبها عواقب أليمة أو آخر أراد أن يتجنب الألم الذي ربما تنجم عنه بعض المتعة ؟ علي الجانب الآخر نشجب ون53412512ستنكر هؤلاء الرجال المفتونون بنشوة اللحظة الهائمون في رغباتهم فلا يدركون م123123ا يعقبها من الألم والأسي المحتم، واللوم كذلك يشمل هؤلاء الذين أخفقوا في واجباتهم نتيجة لضعف إرادتهم فيت213132ساوي مع هؤلاء الذين يتجنبون وينأون عن تحمل الكدح",
                  textAlign: TextAlign.justify,
                  textDirection: TextDirection.rtl,
                ),
              ),
              SizedBox(
                height: 20,
              ),
              Container(
                color: Colors.grey,
                height: 200,
                width: 300,
                child: Text(
                  "ميزة أو فائدة؟ ولكن من لديه الحق أن ينتقد شخص ما أراد أن يشعر بالسعادة التي لا تشوبها عواقب أليمة أو آخر أراد أن يتجنب الألم الذي ربما تنجم عنه بعض المتعة ؟ علي الجانب الآخر نشجب ونستنكر هؤلاء الرجال المفتونون بنشوة اللحظة الهائمون في رغباتهم فلا يدركون ما يعقبها من الألم والأسي المحتم، واللوم كذلك يشمل هؤلاء الذين أخفقوا في واجباتهم نتيجة لضعف إرادتهم فيتساوي مع هؤلاء الذين يتجنبون وينأون عن تحمل الكدح",
                  textAlign: TextAlign.justify,
                  textDirection: TextDirection.rtl,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.93, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.93 at C:\Development\flutter_master
    • Framework revision f35a8b7470 (4 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment] 2020-08-27 14:45
Actually since the regular Arabic RTL here is now fixed, the numbers issue can just be considered a duplicate of https://github.com/flutter/flutter/issues/44449

**Closed by markusaksli-nc** 2020-08-27 14:45 UTC
Labels: a: internationalization, a: typography, customer: crowd, found in release: 1.22, framework, has reproducible steps
