### ISSUE TITLE
Text background paint has light line on top ,and miss some Chinese word

### ISSUE THREAD

**Issue by zmtzawqlp** [flutter/flutter#24335] opened 2018-11-14 09:21 UTC
## Steps to Reproduce
# issue1 
 when background is an opacity color，a line will show at top. 
```dart
var color = Color(0xfffe7801);
 var colorb = color.withOpacity(0.1);

    Paint paint=new Paint();
    paint.color = colorb;
   var ts = Text(
        "  悬赏 ￥ " +"ddddddddddddd" + "  ",
        style: TextStyle(color: color, background: paint, fontSize: 13.0,));
```
# issue2
 when background is an opacity 1.0 color, the Chinese words is missing.
```dart
var color=Colors.black;
    var colorb=Colors.green;
    Paint paint=new Paint();
    paint.color = colorb;
   var ts = Text(
        "  悬赏 ￥ " +"ddddddddddddd" + "  ",
        style: TextStyle(color: color, background: paint, fontSize: 13.0,));
```

**Comment by zoechi** [comment] 2018-11-14 09:28
Please add the output of `flutter doctor -v`.

**Comment by zmtzawqlp** [comment] 2018-11-14 09:31
[√] Flutter (Channel master, v0.10.2-pre.47, on Microsoft Windows [Version 10.0.17134.345], locale zh-CN)
    • Flutter version 0.10.2-pre.47 at D:\Flutter\flutter
    • Framework revision 9dfc0f3aaa (3 weeks ago), 2018-10-24 07:22:08 +0100
    • Engine revision 2586e94122
    • Dart version 2.1.0-dev.7.1.flutter-45f9462398

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected device (1 available)
    • MI 6 • 5a4b233b • android-arm64 • Android 8.0.0 (API 26)

**Comment by zmtzawqlp** [comment] 2018-11-14 09:31
thanks,please check this issue.

**Comment by cixiu** [comment] 2019-01-17 16:48
+1

**Comment by zoechi** [comment] 2019-01-17 17:02
@cixiu Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by GaryQian** [comment] 2019-01-28 23:01
Closing as is a duplicate of https://github.com/flutter/flutter/issues/24337 please continue to track and comment on the other issue

**Closed by GaryQian** 2019-01-28 23:01 UTC
Labels: a: typography, engine
