### ISSUE TITLE
[web] Draggable causes the IFrameElement to reload

### ISSUE THREAD

**Issue by tanlianghao** [flutter/flutter#85303] opened 2021-06-25 10:05 UTC
## Steps to Reproduce

1. Flutter code 
<details> 
<summary>code snippet</summary> 

```dart
class IframeCustom extends StatefulWidget {
  const IframeCustom({Key? key}) : super(key: key);

  @override
  _IframeCustomState createState() => _IframeCustomState();
}

class _IframeCustomState extends State<IframeCustom> {
  IFrameElement _iFrameElement = IFrameElement();
  @override
  void initState() {
    super.initState();
    _iFrameElement.height = '500';
    _iFrameElement.width = '400';

    _iFrameElement.src = 'https://github.com/';
    _iFrameElement.style.border = 'none';
  }

  @override
  Widget build(BuildContext context) {
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => _iFrameElement,
    );
    Widget _iframeWidget;

    _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: 'iframeElement',
    );
    return Scaffold(
      appBar: AppBar(
        title: Text('iframe'),
      ),
      body: Column(
        children: [
          Draggable(
              onDragStarted: () {
              },
              child: Center(
                child: Container(
                  height: 50,
                  width: 400,
                  color: Colors.grey,
                  child: Text('drag'),
                ),
              ),
              feedback: Container()),
          SizedBox(
            height: 500,
            width: 400,
            child: _iframeWidget,
          )
        ],
      ),
    );
  }
}
```

</details>

**Expected results:** 
Drag does not cause the iframe to be rerendered
**Actual results:** 
Raising the Drag event on Draggable causes the iFrame to reload
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.2.2 at /Users/tanlianghao/works/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01
      -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK
    version 30.0.3)
    • Android SDK at /Users/tanlianghao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome
      91.0.4472.114
```

</details>

**Comment by TahaTesser** [comment] 2021-06-28 10:32
Hi @tanlianghao 
Thanks for filing the issue,  I can reproduce the issue on the `stable` channel however, I can't reproduce on beta or dev

Here I created a complete runnable sample

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: IframeCustom(),
    );
  }
}


class IframeCustom extends StatefulWidget {
  const IframeCustom({Key? key}) : super(key: key);

  @override
  _IframeCustomState createState() => _IframeCustomState();
}

class _IframeCustomState extends State<IframeCustom> {
  IFrameElement _iFrameElement = IFrameElement();
  @override
  void initState() {
    super.initState();
    _iFrameElement.height = '500';
    _iFrameElement.width = '400';

    _iFrameElement.src = 'https://flutter.dev/';
    _iFrameElement.style.border = 'none';
  }

  @override
  Widget build(BuildContext context) {
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => _iFrameElement,
    );
    Widget _iframeWidget;

    _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: 'iframeElement',
    );
    return Scaffold(
      appBar: AppBar(
        title: Text('iframe'),
      ),
      body: Column(
        children: [
          Draggable(
              onDragStarted: () {
                print('onDragStarted called');
              },
              child: Center(
                child: Container(
                  height: 50,
                  width: 400,
                  color: Colors.grey,
                  child: Text('drag'),
                ),
              ),
              feedback: Container()),
          SizedBox(
            height: 500,
            width: 400,
            child: _iframeWidget,
          )
        ],
      ),
    );
  }
}


``` 

</details>


|  `stable`  | `beta` |
| :---: |:---: |
|  ❌  |   ✅   | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.2 at /home/taha/Code/flutter_stable
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-1ubuntu1
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

```console
[✓] Flutter (Channel beta, 2.3.0-24.1.pre, on Pop!_OS 21.04 5.11.0-7614-generic, locale en_US.UTF-8)
    • Flutter version 2.3.0-24.1.pre at /home/taha/Code/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 615957513e (3 days ago), 2021-06-25 09:24:44 -0700
    • Engine revision 9d517f475b
    • Dart version 2.14.0 (build 2.14.0-188.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-1ubuntu1
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.04 5.11.0-7614-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```
		
</details>

✅ : No Issue ❌: Issue reproduced 

Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by tanlianghao** [comment] 2021-06-28 12:37
> Hi @tanlianghao
> Thanks for filing the issue, I can reproduce the issue on the `stable` channel however, I can't reproduce on beta or dev
> 
> Here I created a complete runnable sample
> 
> minimal code sample
> `stable`	`beta`
> ❌	✅
> Check `flutter doctor -v` outputs for each channel below
> 
> flutter doctor -v
> ✅ : No Issue ❌: Issue reproduced
> 
> Can you please upgrade to the latest `beta` and try again
> Execute the following commands to upgrade
> `flutter channel beta`
> `flutter upgrade --force`
> `flutter doctor -v`

Yes, the beta is fine；is there a temporary solution if I want to use stable

**Comment by TahaTesser** [comment] 2021-06-28 13:19
Hi @tanlianghao 
Please wait for the fix to land on stable or meanwhile you can choose to stay on beta
Thanks for the confirmation, Given your last message I feel safe to close this issue if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-06-28 13:19 UTC
Labels: in triage
