### ISSUE TITLE
[WebView]Android app crashes after long idle time 

### ISSUE THREAD

**Issue by DengKangKang** [flutter/flutter#105680] opened 2022-06-09 08:43 UTC
### Steps to Reproduce
- Use webview_flutter（same in flutter_inappwebview） in app。
- Wait a long time (maybe dozens of minutes or couple of hours) and app will crash in android .
- device: nova 8 SE(Harmony os).
### flutter docotr
``` [✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/dengkangkang/development/flutter_2.10.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (7 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/dengkangkang/Library/Android/sdk
    • Platform android-31, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/dengkangkang/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/dengkangkang/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • JSC AL50 (mobile) • BRNUT21B24011838 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 102.0.5005.61
```

### Cash Log 
```➜  flutter_2.10.5 adb shell dumpsys dropbox --print 2022-06-09 14:59:06 data_app_native_crash
Drop box contents: 50 entries
Max entries: 1000
Low priority rate limit period: 2000 ms
Low priority tags: {data_app_wtf, keymaster, system_server_wtf, system_app_strictmode, system_app_wtf, system_server_strictmode, data_app_strictmode, netstats}
Searching for: 2022-06-09 14:59:06 data_app_native_crash

========================================
2022-06-09 14:59:06 data_app_native_crash (text, 2474 bytes)
Process: cn.xxx.mobile
PID: 11814
UID: 10316
Flags: 0x38e83e44
Package: cn.xxxxx.mobile v194 (1.9.4)
SYSVMTYPE: Maple
APPVMTYPE: Art
Foreground: Yes
Lifetime: 495s
Build: HUAWEI/JSC-AL50CH/HWJSC-H:10/HUAWEIJSC-AL50/102.0.0.156C00:user/release-keys

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/JSC-AL50CH/HWJSC-H:10/HUAWEIJSC-AL50/102.0.0.156C00:user/release-keys'
Revision: '0'
ABI: 'arm64'
SYSVMTYPE: Maple
APPVMTYPE: Art
Timestamp: 2022-06-09 14:59:05+0800
pid: 11814, tid: 11814, name: .xxxxx.mobile  >>> cn.xxxxx.mobile <<<
uid: 10316
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7eae796228
    x0  0000007eae797000  x1  0000000000001000  x2  0000000000000003  x3  0000000000000001
    x4  000000000000010c  x5  0000000000000000  x6  00000000ffffffff  x7  0000000000000000
    x8  0000007eae796000  x9  0000000000000001  x10 0000000000000001  x11 0000000000000000
    x12 00000000ffffffd8  x13 0000007ff4bbc940  x14 fffffffffffffff8  x15 0000000000000168
    x16 0000007e0f7c4af8  x17 0000007eb0407a80  x18 0000000000000000  x19 0000007d6d84de00
    x20 00000400760bb000  x21 0000007e13db7800  x22 0000007d9b892510  x23 0000007d892eb010
    x24 0000007d87df60a0  x25 0000000000000000  x26 0000000000003084  x27 0000007d6e846808
    x28 0000007dc9ff1208  x29 0000000000000000
    sp  0000007ff4bbc920  lr  0000007e0f131cc4  pc  0000007e0f131ce8

backtrace:
      #00 pc 0000000002198ce8  /vendor/lib64/egl/libGLES_mali.so (BuildId: a81e9f07559d172ceddae9a4c4c47dfc)
      #01 pc 000000000219a650  /vendor/lib64/egl/libGLES_mali.so (BuildId: a81e9f07559d172ceddae9a4c4c47dfc)
      #02 pc 00000000021b0e7c  /vendor/lib64/egl/libGLES_mali.so (BuildId: a81e9f07559d172ceddae9a4c4c47dfc)
      #03 pc 00000000021afc10  /vendor/lib64/egl/libGLES_mali.so (BuildId: a81e9f07559d172ceddae9a4c4c47dfc)
      #04 pc 0000000000022718  /system/lib64/libEGL.so (android::eglSwapBuffersWithDamageKHRImpl(void*, void*, int*, int)+348) (BuildId: 9f54126ca3c5e205a088560d488b3844)
      #05 pc 000000000001f008  /system/lib64/libEGL.so (eglSwapBuffers+84) (BuildId: 9f54126ca3c5e205a088560d488b3844)
      #06 pc 00000000002df084  /data/app/cn.xxxxx.mobile-ldM9BHnoiFhzevy5XWdvJw==/lib/arm64/libflutter.so (BuildId: 26a22a0b39158a956f52247fdf7a41778fee53a6)
      #07 pc 0000000000616db4  /data/app/cn.xxxxx.mobile-ldM9BHnoiFhzevy5XWdvJw==/lib/arm64/libflutter.so (BuildId: 26a22a0b39158a956f52247fdf7a41778fee53a6)
```
### Others
This bug first appeared when flutter was updated to 2.8.0. We tried updating Flutter to 2.10.5 to fix this problem， It's not solved. There's some randomness to this bug. But this is a bad bug and is high-frequency on some Huawei devices（harmonyOs）.

**Comment by exaby73** [comment] 2022-06-09 09:30
@flutter-symbolizer-bot android flutter#v2.10.5 release arm64 https://github.com/flutter/flutter/issues/105680#issue-1265797739

**Comment by DengKangKang** [comment] 2022-06-09 10:23
> 2.10.5
Is flutter_MACOS_2.10.5-stable a stable version?We tried many devices and only replicated the problem on Huawei devices(Harmony os).

**Comment by DengKangKang** [comment] 2022-06-09 10:23
> Hello @DengKangKang. Can you please upgrade to stable and confirm if this bug still replicates? I was unable to replicate it on a Vivo Android 12 device (left the app running for ~2 hours) on stable

Is flutter_MACOS_2.10.5-stable a stable version?We tried many devices and only replicated the problem on Huawei devices(Harmony os)

**Comment by DengKangKang** [comment] 2022-06-09 10:29
There is one other thing .We haven't reproduced it yet in the Debug version. So crash logs are collected online ,or captured using ADB commands. But given the randomness of this bug it could be a coincidence.

**Comment by exaby73** [comment] 2022-06-09 10:36
@DengKangKang Current stable version of Flutter is 3.0.1. 2.10.5 is considered an old version now. Also, this crash looks like a duplicate of #103685

**Comment by DengKangKang** [comment] 2022-06-09 10:42
@exaby73 I'm sorry, I can't do it. Upgrading 3.0.1 will require a lot of code changes, which will take a long test cycle. There is no guarantee that the problem will be solved. What other possible solutions are there? Otherwise, we may have to consider downregulating the version of Flutter. But it was also a bad plan.

**Comment by DengKangKang** [comment] 2022-06-09 10:58
@exaby73  [#99614 ](https://github.com/flutter/flutter/issues/99614#issue-1160482361) This issue is very similar to ours. It is stated in the Issue that upgrading to 2.10.5 will solve this problem. So we tried and obviously he didn't work.

**Comment by DengKangKang** [comment] 2022-06-10 02:13
Ok, I will try again later. We chose other solutions to avoid this problem.I'm not sure it makes sense to try.

**Comment by exaby73** [comment] 2022-06-10 04:55
Since we can't verify the issue on stable and you have chosen a workaround as mentioned in your last comment, I am closing this issue. You can reopen it once you reproduce this on current stable, and possibly are able to post a sample of it as well.

**Closed by exaby73** 2022-06-10 04:55 UTC
Labels: in triage

**Comment by Sheng20152** [comment] 2022-06-20 00:54
@exaby73 Could you help to confirm [flutter/engine#32106](https://github.com/flutter/engine/pull/32106) solution fix this issue?
Does flutter sdk V3.0.2 have this fix?

**Comment by exaby73** [comment] 2022-06-20 09:58
@Sheng20152 I am not sure since I was not able to reproduce this issue on stable or master currently.
