### ISSUE TITLE
TextField,  Enter Chinese in android device ,The bottom is cut

### ISSUE THREAD

**Issue by llearn** [flutter/flutter#20183] opened 2018-08-03 15:28 UTC
#### TextField enters Chinese on Android devices, the bottom of the text is not displayed completely, iOS does not have this problem 

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: new AppBar(
          title: new Text('Flutter Demo Home Page'),
        ),
        body: new Container(
          child: TextField(),
        ),
      ),
    );
  }
}
```
<img width="763" alt="qq20180803-231912 2x" src="https://user-images.githubusercontent.com/3062671/43651215-5ae948b4-9774-11e8-9e3f-ee6addf07a02.png">

## Logs

```
Analyzing flutter_app...
No issues found! (ran in 1.2s)
```

```
[✓] Flutter (Channel master, v0.5.8-pre.229, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.5.8-pre.229 at /usr/local/flutter
    • Framework revision cacd291c5c (2 hours ago), 2018-08-03 15:13:28 +0200
    • Engine revision 4893b0760d
    • Dart version 2.0.0-dev.69.5.flutter-8bad5c7b29

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /data/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /data/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by parcool** [comment] 2018-08-03 15:34
I got the same issue. +1

**Comment by TeddyRomanos** [comment] 2018-08-04 15:59
I got the same issue. +1

**Comment by TeddyRomanos** [comment] 2018-08-05 11:14
This happens for Arabic as well.

**Comment by LOVELJ1314** [comment] 2018-08-21 03:58
it happens on v8.1

**Comment by llearn** [comment] 2018-10-25 03:54
@HansMuller  mine is zh-CN

**Comment by parcool** [comment] 2018-10-25 04:19
Locale.CHINA

**Comment by GaryQian** [comment] 2018-11-09 21:31
@llearn I have attempted to reproduce this with the test app you provided on both an emulated and physical Nexus 5X, with locale set to zh_CN and have been unable to reproduce. I have also attempted on a Pixel, Pixel 2 XL, Nexus S, and Nexus 5 all without being able to reproduce. I then tried rolling back to an older version of Flutter dated at Aug 1st, which also failed to reproduce.

Did you or anyone else have a specific environment/device-API-Flutter combination that reliably reproduces this clipping?

**Comment by GaryQian** [comment] 2018-11-12 23:33
I have been able to reproduce. Type Chinese characters on android, and then type multiple flag emojis. Erase the flag emojis, and the box will sometimes clip the characters. This is on a physical android device.

**Comment by GaryQian** [comment] 2018-11-19 22:00
Should be fixed by https://github.com/flutter/flutter/pull/24265

**Comment by zoechi** [comment] 2019-01-24 13:50
@llearn are you still seeing this?

**Comment by llearn** [comment] 2019-01-25 02:05
@GaryQian @zoechi This problem has been solved. Thank you.

**Comment by GaryQian** [comment] 2019-01-25 02:08
I believe this specific behavior was actually fixed by a patch by @jslavitz

I am still working on additional fixes to prevent the additional jank we are seeing with multilingual textfields.

**Comment by llearn** [comment] 2019-01-25 02:13
Sorry, there may be a little problem.

**Closed** 2019-02-23 11:35 UTC
Labels: a: text input, a: typography, framework, waiting for PR to land (fixed)
