### ISSUE TITLE
Flutter The default TextField on the iOS terminal pops up every time it is pasted from other APPs. There is no such problem in developing APPs with iOS native code.

### ISSUE THREAD

**Issue by caofuqing2** [flutter/flutter#155896] opened 2024-09-29 10:06 UTC
### Steps to reproduce

![WechatIMG12801](https://github.com/user-attachments/assets/d9ffd6bb-7056-467a-85f6-71ddbe165ab7)
![WechatIMG12815](https://github.com/user-attachments/assets/fb7fede0-4fa7-417b-ab3e-d293279c5481)

### Expected results

希望能支持下只授权一次

### Actual results

希望能支持下只授权一次

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-30 07:50
Closing this as a duplicate of https://github.com/flutter/flutter/issues/103163

**Closed by danagbemava-nc** 2024-09-30 07:50 UTC
Labels: in triage
