### ISSUE TITLE
video_player 0.8.0 unsupported error

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#25930] opened 2018-12-31 22:35 UTC
I had some errors with `video_player 0.8.0`
Console says those.

```
flutter W/VideoCapabilities(17185): Unrecognized profile 4 for video/hevc I/
VideoCapabilities(17185): Unsupported profile 4 for video/mp4v-es
flutter W/VideoCapabilities(21215): Unsupported mime video/mp4v-esdp
W/cr_MediaCodecUtil(17536): HW encoder for video/avc is not available on this device.

```
I hope this problem gets fixed as soon as possible.
Thank you.

**Comment by zoechi** [comment] 2019-01-02 09:14
Please add the output of `flutter doctor -v`
Ideally with the device in question connected.

**Comment by zoechi** [comment] 2019-01-02 09:15
Please also check https://github.com/flutter/flutter/issues/13909#issuecomment-448239580

**Comment by zoechi** [comment] 2019-01-04 07:45
Did you check if your video file is among the supported formats?
Flutter uses an external video player component and it might be better to report the issue there.

**Comment by Daibaku0615** [comment] 2019-01-04 10:36
It's mp4 format.
I think it's supported right?

**Comment by zoechi** [comment] 2019-01-04 10:43
```
Unsupported profile 4 for video/mp4v-es
Unsupported mime video/mp4v-esdp
```
seems to be specific sub-formats, perhaps ones that depend on platform specific encoders that the device does not provide.  
To me this sounds like an issue of the used player, not the video_player plugin that provides that functionality to Flutter.

**Comment by tvolkert** [comment] 2020-01-10 07:14
There's not enough actionable info in this bug to proceed (reproduction code, etc.).  It also looks like this is likely due to using a format that's not supported by the underlying player.  Closing as such.

**Closed by tvolkert** 2020-01-10 07:14 UTC
Labels: a: video, p: first party, p: video_player, plugin, severe: crash
