### ISSUE TITLE
Add a test that exercises minimal input interaction of Flutter on Fuchsia.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#39057] opened 2019-08-22 14:46 UTC
See https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=35184#c8 for context. Discussion should occur there, please.

**Comment by iskakaushik** [comment] 2020-02-14 21:22
duplicate of https://github.com/flutter/flutter/issues/44826

**Closed by iskakaushik** 2020-02-14 21:22 UTC
Labels: a: tests, customer: fuchsia, team, team: infra
