### ISSUE TITLE
onHorizontalDrag* always wins over onTap, even if there is no drag between the pointer down and pointer up

### ISSUE THREAD

**Issue by horiaciu** [flutter/flutter#22360] opened 2018-09-27 17:20 UTC
I want a parent widget to respond to taps and its child widget to respond to horizontal drags. The parent is wrapped in a GestureDetector with an onTap and the child is wrapped in another `GestureDetector` with an `onHorizontalDrag[Start/Update/End]`. No matter how I set the hit behaviors on the two GestureDetectors, I never get the parent to trigger on taps. It seems that the child's `onHorizontalDrag*` callback will always win over a tap event, even if there is no drag between the pointer down and pointer up.

```dart
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        print('parent onTap');
      },
      child: Container(
        alignment: Alignment.center,
        width: 400.0,
        height: 400.0,
        color: const Color(0xFF0000FF),
        child: GestureDetector(
          onHorizontalDragEnd: (details) {
            print('child onHorizontalDragEnd $details');
          },
          child: Container(
            width: 200.0,
            height: 200.0,
            color: const Color(0xFFFF0000),
          ),
        ),
      ),
    );
  }
```

When tapping on the child, the code above will print

> flutter: child onHorizontalDragEnd DragEndDetails(Velocity(0.0, 0.0))

If I change `onHorizontalDragEnd` with `onHorizontalDragUpdate`, when tapping on the child, the code will not print anything  (as if the child consumed the event even though the callback is not called).

**Comment by zoechi** [comment] 2018-09-27 17:35
Please add the output of `flutter doctor -v`.

**Comment by mehmetf** [comment] 2018-09-27 17:38
@zoechi This is a google internal issue. They are always at the bleeding edge of Flutter (lagging HEAD by 2-3 days).

**Comment by zoechi** [comment] 2018-09-27 18:02
> They are always at the bleeding edge of Flutter

👍  good to know. 

I think its always a good idea to add the output though.
If the issue isn't fixed within a few weeks, it's probably cumbersome to figure out what versions (Flutter, SDKs) were in use when the issue happened. It's often also about OS, connected device, ... 
Just my 2c. 

I don't want to get in the way of Google internal stuff.
I'll note the username when I learn it's a Googler that is not a [Member] and skip the request for `flutter doctor` output.

**Comment by zoeyfan** [comment] 2020-01-03 05:25
@mehmetf, I am triaging our bug database, and notice this old bug from 2018. I just want to follow up to see if this has been resolved, or if we plan to take any action. Can we close it now?

**Comment by mehmetf** [comment] 2020-01-03 16:23
I believe this can be closed yes. I have failed to find an internal bug tracking this.

**Closed by mehmetf** 2020-01-03 16:23 UTC
Labels: f: gestures, framework
