### ISSUE TITLE
Error after adding watchOS target to flutter app

### ISSUE THREAD

**Issue by devnoaman** [flutter/flutter#104009] opened 2022-05-17 20:40 UTC
I've added a watchOS target to flutter app and after this i got this error when run it from flutter side 
`

Error (Xcode): unable to resolve product type
'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator'

Error (Xcode): unable to resolve product type
'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator'

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.`
the app works fine when run it from xcode after change the runner rom watchos to iphone runner

**Comment by darshankawar** [comment] 2022-05-18 07:33
Closing this as duplicate of https://github.com/flutter/flutter/issues/92294

**Closed by darshankawar** 2022-05-18 07:33 UTC
Labels: in triage
