### ISSUE TITLE
TextField adds characters in a wrong way on Linux Desktop

### ISSUE THREAD

**Issue by David-Mou** [flutter/flutter#79046] opened 2021-03-25 15:30 UTC
## Steps to Reproduce

Run this application on Flutter Desktop for Linux:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(body: TextField()),
    );
  }
}
```

Try to write something in the Text Field. New characters are added to the beginning of the string instead of the end.

**Expected results:** Characters are added at the end when writing.

**Actual results:** This is how the TextField looks like after writing 'this is an example':

![image](https://user-images.githubusercontent.com/52407910/112498561-ef9b5280-8d86-11eb-90e3-9f57468c24af.png)

<details>
  <summary>Logs</summary>

```

[  +14 ms] Skipping pub get: version match.
[ +102 ms] Generating /home/mou/edu/flutter/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +55 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +2 ms] Launching lib/main.dart on Linux in debug mode...
[   +3 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.BPBGSG/flutter_tool.EVUGMR/app.dill --packages /home/mou/edu/flutter/bug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +13 ms] Building Linux application...
[   +6 ms] <- compile package:bug/main.dart
[   +6 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/mou/edu/flutter/bug/linux
[  +25 ms] -- Configuring done
[   +3 ms] -- Generating done
[   +7 ms] -- Build files have been written to: /home/mou/edu/flutter/bug/build/linux/debug
[   +2 ms] executing: ninja -C build/linux/debug install
[   +4 ms] ninja: Entering directory `build/linux/debug'
[+8597 ms] [1/5] Generating /home/mou/edu/flutter/bug/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/mou/edu/flutter/bug/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +3 ms] [  +47 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] [        ] executing: [/opt/flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] [   +8 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] [        ] 2.0.3
[        ] [  +25 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +24 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +41 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +26 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +58 ms] Initializing file store
[        ] [  +14 ms] Skipping target: gen_localizations
[        ] [   +3 ms] unpack_linux: Starting due to {}
[        ] [ +301 ms] kernel_snapshot: Starting due to {}
[        ] [   +2 ms] unpack_linux: Complete
[   +1 ms] [+1029 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter
--no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --packages /home/mou/edu/flutter/bug/.dart_tool/package_config.json --output-dill
/home/mou/edu/flutter/bug/.dart_tool/flutter_build/daa91f9edb25b9b059a995be50b3a704/app.dill --depfile /home/mou/edu/flutter/bug/.dart_tool/flutter_build/daa91f9edb25b9b059a995be50b3a704/kernel_snapshot.d package:bug/main.dart
[   +1 ms] [+5455 ms] kernel_snapshot: Complete
[        ] [ +278 ms] debug_bundle_linux_assets: Starting due to {}
[        ] [ +179 ms] debug_bundle_linux_assets: Complete
[        ] [ +311 ms] Persisting file store
[        ] [   +4 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +5 ms] "flutter assemble" took 7,691ms.
[        ] [ +222 ms] ensureAnalyticsSent: 219ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +353 ms] [2/5] Building CXX object CMakeFiles/bug.dir/flutter/generated_plugin_registrant.cc.o
[   +9 ms] [3/5] Building CXX object CMakeFiles/bug.dir/my_application.cc.o
[ +119 ms] [4/5] Linking CXX executable intermediates_do_not_run/bug
[        ] [4/5] Install the project...
[   +7 ms] -- Install configuration: "Debug"
[  +21 ms] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/bug
[        ] -- Set runtime path of "/home/mou/edu/flutter/bug/build/linux/debug/bundle/bug" to "$ORIGIN/lib"
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/icudtl.dat
[   +1 ms] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[  +90 ms] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +25 ms] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/mou/edu/flutter/bug/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[  +13 ms] Building Linux application... (completed in 9.3s)
[ +156 ms] Observatory URL on device: http://127.0.0.1:36261/Lfoezw9dd-c=/
[   +3 ms] Caching compiled dill
[  +91 ms] Connecting to service protocol: http://127.0.0.1:36261/Lfoezw9dd-c=/
[ +101 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:36261/Lfoezw9dd-c=/.
[  +72 ms] DDS is listening at http://127.0.0.1:43483/kaLjUcB9m8Y=/.
[  +32 ms] Successfully connected to service protocol: http://127.0.0.1:36261/Lfoezw9dd-c=/
[ +762 ms] DevFS: Creating new filesystem on the device (null)
[   +8 ms] DevFS: Created new filesystem on the device (file:///tmp/bugQAXYEZ/bug/)
[   +5 ms] Updating assets
[  +75 ms] Syncing files to device Linux...
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:bug/main.dart 2011bc93-ac8f-4068-9547-36ed9d6bdb62
[        ] <- 2011bc93-ac8f-4068-9547-36ed9d6bdb62
[  +73 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 76ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +4 ms] Connected to _flutterView/0x559b63600940.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:43483/kaLjUcB9m8Y=/
[        ] 
           Flutter DevTools, a Flutter debugger and profiler, on Linux is available at: http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A43483%2FkaLjUcB9m8Y%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety

```

```
Analyzing bug...                                                        
No issues found! (ran in 0.8s)

```

```
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.3 at /opt/flutter
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.0.1
    • cmake version 3.19.4
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /usr/share/idea
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.5731

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!

```

</details>

**Comment by HansMuller** [comment] 2021-03-25 15:52
CC @LongCatIsLooong - perhaps the app is opening in an RTL locale?

**Comment by LongCatIsLooong** [comment] 2021-03-25 18:12
I think this is probably Linux specific as I'm not seeing this on iOS or Android. This is probably not just wrong text directionality: Latin alphabets in the same word should still appear in left to right order.

**Comment by LongCatIsLooong** [comment] 2021-03-25 18:39
@David-Mou unfortunately I'm having problems trying to build flutter apps on my distro. Could you print what the `TextEditingController.value` looks like when you type something into the `TextField`?

**Comment by LongCatIsLooong** [comment] 2021-03-25 19:02
Also /cc @cbracken

**Comment by David-Mou** [comment] 2021-03-25 23:31
> @David-Mou unfortunately I'm having problems trying to build flutter apps on my distro. Could you print what the `TextEditingController.value` looks like when you type something into the `TextField`?

_TextEditingController.value_ is storing the same bad string as showed by TextField.

**Comment by TahaTesser** [comment] 2021-03-30 12:39
Hi @David-Mou 
Thanks for filing the issue, I can't reproduce it when running your code sample in a new project on Ubuntu 20.04


<details> 
<summary>preview</summary> 

![image](https://user-images.githubusercontent.com/48603081/112989742-e850bc00-916d-11eb-8b97-f2d11c362a38.png)


</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_IN)
    • Flutter version 2.0.3 at /home/taha/Code/flutter_stable
    • Framework revision 4d7946a68d (12 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0
[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90
! Doctor found issues in 1 category.
```
	
</details>

<details> 
<summary>neofetch</summary> 

```bash
taha@taha-Lenovo-ideapad-510S-14IKB:~/AndroidStudioProjects/stable_flutter$ neofetch
            .-/+oossssoo+/-.
        `:+ssssssssssssssssss+:`           taha@taha-Lenovo-ideapad-510S-14IKB 
      -+ssssssssssssssssssyyssss+-         ----------------------------------- 
    .ossssssssssssssssssdMMMNysssso.       OS: Ubuntu 20.04.2 LTS x86_64 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Host: 80UV Lenovo ideapad 510S-14IKB 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Kernel: 5.8.0-48-generic 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Uptime: 4 hours, 4 mins 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Packages: 1597 (dpkg), 10 (snap) 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Shell: bash 5.0.17 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Resolution: 3072x1728 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM: Mutter 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   WM Theme: Adwaita 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Theme: Yaru-dark [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Icons: Yaru [GTK2/3] 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      Terminal: gnome-terminal 
    .ossssssssssssssssssdMMMNysssso.       CPU: Intel i5-7200U (4) @ 2.500GHz 
      -+sssssssssssssssssyyyssss+-         GPU: Intel HD Graphics 620 
        `:+ssssssssssssssssss+:`           Memory: 3273MiB / 7803MiB 
            .-/+oossssoo+/-.
taha@taha-Lenovo-ideapad-510S-14IKB:~/AndroidStudioProjects/stable_flutter$ 
```

</details>


Can you please provide details of which distro you're using? Also output of `neofetch` 
Thank toy

**Comment by David-Mou** [comment] 2021-03-30 19:59
Hi @TahaTesser . Of course, I am running this in Arch Linux with Gnome as Desktop and XOrg. 

Here I post my neofetch output:

<details>
                   -`                    mou@paulamou 
                  .o+`                   ------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: A520 AORUS ELITE 
               `+oooooo:                 Kernel: 5.10.16-arch1-1 
               -+oooooo+:                Uptime: 7 days, 23 mins 
             `/:-:++oooo+:               Packages: 1638 (pacman), 7 (flatpak) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1920x1080, 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 3.38.3 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Flat-Remix-Dark-fullPanel 
       -osssssso.      :ssssssso.        Theme: Flat-Remix-GTK-Yellow-Darker [G 
      :osssssss/        osssso+++.       Icons: Tela-yellow-Dark [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gnome-terminal 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GT 730 
 `++:.                           `-/+/   Memory: 12624MiB / 32091MiB 
 .`                                 `/

</details>

**Comment by navrocky** [comment] 2021-03-30 20:46
I confirm this bug on OpenSuse Tumbleweed. It seems to be a platform error because i see in debugger in method _handleAsMethodCall  in `platform_channel.dart` the reverse aligned text:

```
MethodCall(TextInputClient.updateEditingState, [1, {text: olleH, selectionBase: 0, selectionExtent: 0, composingBase: -1, composi
```

```
                                     ......            vlad@vladnout 
     .,cdxxxoc,.               .:kKMMMNWMMMNk:.        ------------- 
    cKMMN0OOOKWMMXo. ;        ;0MWk:.      .:OMMk.     OS: openSUSE Tumbleweed x86_64 
  ;WMK;.       .lKMMNM,     :NMK,             .OMW;    Host: GS40 6QE Phantom REV:0.C 
 cMW;            'WMMMN   ,XMK,                 oMM'   Kernel: 5.10.16-1-default 
.MMc               ..;l. xMN:                    KM0   Uptime: 3 hours, 40 mins 
'MM.                   'NMO                      oMM   Packages: 4099 (rpm) 
.MM,                 .kMMl                       xMN   Shell: bash 5.1.4 
 KM0               .kMM0. .dl:,..               .WMd   Resolution: 1920x1080 
 .XM0.           ,OMMK,    OMMMK.              .XMK    DE: Plasma 5.21.0 
   oWMO:.    .;xNMMk,       NNNMKl.          .xWMx     WM: KWin 
     :ONMMNXMMMKx;          .  ,xNMWKkxllox0NMWk,      WM Theme: plastik 
         .....                    .:dOOXXKOxl,         Theme: Breeze Dark [Plasma], Breeze-Dark [GTK2], Breeze [GTK3] 
                                                       Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
                                                       Terminal: mc 
                                                       CPU: Intel i7-6700HQ (8) @ 3.500GHz 
                                                       GPU: Intel HD Graphics 530 
                                                       GPU: NVIDIA GeForce GTX 970M 
                                                       Memory: 5971MiB / 31977MiB 

                                                                               
                                                                               

```

**Comment by LongCatIsLooong** [comment] 2021-03-30 21:02
The logical order of the input is reversed. I suspect the caret is always placed at the start of the input. Does the caret move visually when you type?

**Comment by TahaTesser** [comment] 2021-03-31 06:31
@navrocky 
As you mentioned arch, this seems to be a duplicate of https://github.com/flutter/flutter/issues/76383

Can you please try this [solution](https://github.com/flutter/flutter/issues/76383#issuecomment-800085966)
Thank you

**Comment by David-Mou** [comment] 2021-03-31 11:06
@TahaTesser Issue solved if you update to the last versions of GTK3! In my case, it's working fine with **GTK 3.24.28**

Looks as this is currently solved by updating the GTK, I don't know if this could be valuable in the documentation / FAQ section in order to provide context and prevent more issues from this concern.

It's ok for me to close this if you consider that the advice updating the GTK libraries is good enough.

**Comment by TahaTesser** [comment] 2021-03-31 11:47
@David-Mou 
Glad you resolved the issue since the original issue was closed with the GTK upgrade
Closing as duplicate of https://github.com/flutter/flutter/issues/76383
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-31 11:47 UTC
Labels: a: text input, f: material design, framework, in triage, platform-linux
