### ISSUE TITLE
Could not get unknown property 'runtimeConfiguration' for object of type com.android.build.gradle.internal.api.LibraryVariantImpl

### ISSUE THREAD

**Issue by wasdty** [flutter/flutter#52799] opened 2020-03-18 08:52 UTC
## Steps to Reproduce

1. build apk i get this error.

**Actual results:** 
FAILURE: Build failed with an exception.

The plugin vibrate could not be built due to the issue above.
<details>
  <summary>Logs</summary>
FAILURE: Build failed with an exception.

* Where:
Initialization script 'F:\flutter\packages\flutter_tools\gradle\aar_init_script.gradle' line: 122

* What went wrong:
Could not get unknown property 'runtimeConfiguration' for object of type com.android.build.gradle.internal.api.LibraryVariantImpl.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

The plugin vibrate could not be built due to the issue above.

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2020-03-18 09:24
Duplicate of [#45680](https://github.com/flutter/flutter/issues/45680)
Please follow the issue there

**Closed by TahaTesser** 2020-03-18 09:24 UTC
