### ISSUE TITLE
Rounded rectangles painted badly[ios14][web][skia]

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#62652] opened 2020-07-31 09:07 UTC
## Steps to Reproduce

1. Save `min repro code`
2. `flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --release`
3. Open it up in iOS14 Safari or Chrome

<details>
<summary>min repro code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 4,
      child: Scaffold(
        floatingActionButton: Container(
            margin: EdgeInsets.symmetric(horizontal: 4),
            padding: EdgeInsets.all(6),
            width: MediaQuery.of(context).size.width * 0.8,
            height: 100,
            decoration: BoxDecoration(
              color: Colors.red,
              borderRadius: BorderRadius.circular(80),
            ),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(80),
              child: TabBar(
                  isScrollable: true,
                  labelColor: Colors.black,
                  unselectedLabelColor: Colors.grey,
                  indicatorColor: Colors.white,
                  indicator: BoxDecoration(shape: BoxShape.rectangle, borderRadius: BorderRadius.all(Radius.circular(30)), color: Colors.white),
                  tabs: [
                    Tab(icon: Icon(Icons.ac_unit)),
                    Tab(icon: Icon(Icons.ac_unit)),
                    Tab(icon: Icon(Icons.ac_unit)),
                    Tab(icon: Icon(Icons.ac_unit)),
                  ]),
            )),
      ),
    );
  }
}
```
</details>

**Expected results:** 
this is on iOS14 (standard, not skia)
![ios14 not skia](https://user-images.githubusercontent.com/25743901/89018891-6d03e580-d314-11ea-816f-2736ff330ee4.jpeg)

**Actual results:** 
this is on iOS14 (skia): flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --release
https://experiment24.web.app/#/
![ios14 skia](https://user-images.githubusercontent.com/25743901/89018996-8d33a480-d314-11ea-9485-4be6c90c28d3.jpeg)
![ios14 skia chrome](https://user-images.githubusercontent.com/25743901/89019408-29f64200-d315-11ea-96c1-d86a04623cb7.jpeg)

Bonus bug? 
this is on iPhone 11 iOS13 simulator using skia: flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --release
![ios13 iPhone 11 simulator skia](https://user-images.githubusercontent.com/25743901/89019095-b3f1db00-d314-11ea-8465-10eb8439bd61.png)

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.5 19F101, locale es-ES)
    • Flutter version 1.21.0-6.0.pre.117 at /Users/tomas/Development/flutter
    • Framework revision 7ec2d360bc (27 hours ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • iPhone (mobile)    • 00008020-000415840E50003A            • ios            • iOS 14.0
    • iPhone 11 (mobile) • 04298E38-2633-4586-B868-1FBD5C708AF7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment] 2020-07-31 10:14
Hi @tomasbaran 
I cannot reproduce this issue on latest `master` channel.


<img width="1011" alt="Screen Shot 2020-07-31 at 11 08 33" src="https://user-images.githubusercontent.com/67424416/89025167-4480e900-d31e-11ea-8ba4-76db57ddff63.png">

Can you upgrade to `master` and try again:
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`


<details>
<summary>  flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.129, on Mac OS X 10.15.6 19G73, locale en)
    • Flutter version 1.21.0-6.0.pre.129 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 30aef0a3b9 (13 hours ago), 2020-07-30 14:20:21 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.4
    • Dart plugin version 202.6397.47

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

! Doctor found issues in 2 categories
```
</details>

**Comment by tomasbaran** [comment] 2020-07-31 10:22
@pedromassango Can you share what device and what version of iOS you were running? Don't forget to make sure you run your device on iOS 14

**Comment by pedromassangocode** [comment] 2020-07-31 11:26
I tested on Chrome since I don't have a device with iOS 14.

I would recommend to follow up on https://github.com/flutter/flutter/issues/61047 for issues related to iOS 14.

**Comment by tomasbaran** [comment] 2020-07-31 11:32
@pedromassango  yes, this is an iOS14 related issue. So how do I add it there? Just post link to this issue in this: #61047 thread?

**Comment by pedromassangocode** [comment] 2020-07-31 11:35
> @pedromassango yes, this is an iOS14 related issue. So how do I add it there? Just post link to this issue in this: #61047 thread?

I already did this. The author will eventually add the issue there.

**Comment by jmagman** [comment] 2020-07-31 17:18
Added to #61047.  It's just a convenience umbrella bug to keep track of our overall progress, so keep the details of individual bugs in their respective issues to avoid noise.

**Comment by yjbanov** [comment] 2020-09-03 18:54
Related Skia issue: https://bugs.chromium.org/p/skia/issues/detail?id=10594

**Comment by TahaTesser** [comment] 2020-10-28 14:14
![IMG_2DA9E3B6E220-1](https://user-images.githubusercontent.com/48603081/97447879-095e7800-1956-11eb-9e5d-7ec63dfb8ca5.jpeg)


`flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true`

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 4,
      child: Scaffold(
        floatingActionButton: Container(
            margin: EdgeInsets.symmetric(horizontal: 4),
            padding: EdgeInsets.all(6),
            width: MediaQuery.of(context).size.width * 0.8,
            height: 100,
            decoration: BoxDecoration(
              color: Colors.red,
              borderRadius: BorderRadius.circular(80),
            ),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(80),
              child: TabBar(
                  isScrollable: true,
                  labelColor: Colors.black,
                  unselectedLabelColor: Colors.grey,
                  indicatorColor: Colors.white,
                  indicator: BoxDecoration(
                      shape: BoxShape.rectangle,
                      borderRadius: BorderRadius.all(Radius.circular(30)),
                      color: Colors.white),
                  tabs: [
                    Tab(icon: Icon(Icons.ac_unit)),
                    Tab(icon: Icon(Icons.ac_unit)),
                    Tab(icon: Icon(Icons.ac_unit)),
                    Tab(icon: Icon(Icons.ac_unit)),
                  ]),
            )),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-4.0.pre.107, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-4.0.pre.107 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 35a94f70e1 (7 hours ago), 2020-10-27 23:47:04 -0700
    • Engine revision 64e6599910
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • RMX2001 (mobile)       • 192.168.0.104:5555        • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 86.0.4240.111

• No issues found!
```

</details>

**Comment by yjbanov** [comment] 2021-03-02 18:46
This should be fixed now.

**Closed by yjbanov** 2021-03-02 18:46 UTC
Labels: P4, dependency: skia, e: OS Version specific, e: web_canvaskit, engine, found in release: 1.24, has reproducible steps, platform-ios, platform-web
