### ISSUE TITLE
Async Issue in Cloud Firestore

### ISSUE THREAD

**Issue by jrmarkham** [flutter/flutter#35405] opened 2019-07-01 16:01 UTC
I am gathering a data list with the cloud_firestore plugin and displaying it with a Bloc Builder (flutter_block). 

This all works fine when I pull data from a single document collection. 

When I add data to the payload from another document the data doesn't load in sync (i get an empty list with no data). If I do a hot reload then the data displays fines and properly populated with the extra data. So the code structure works in retrieving data but out of sync.

Below is the stack that gathers the payload from firebase.

Here is the problem area  
//        // add extra data

```
        io.questionObject =
            await loadQuestionFromQuery(GlobalData.FB_FIELD_GAME_ID, io.gameID);
        io.inviterUserObject =
            await _userServices.getUserViaDocID(io.inviterUserID);
```

Again, remove it and the data is in sync. Or when you hot reload it loads with all the added data. 

I am fine with a fix or using a different technique. 

=============================
```
Future<List<InviteObject>> loadAllInvitations(BaseUserServices _userServices) async {
    List<InviteObject> list = [];
     await Firestore.instance
        .collection(GlobalData.FB_DOC_INVITES)
        .where(GlobalData.FB_FIELD_EMAIL,
            isEqualTo: DataMangerService.currentUser.email)
        .getDocuments()
        .then((docs) async {
        docs.documents.forEach((doc) async {
        debugPrint(
            ':::::RQ::::: COMPLETE loadAllInvitations ${docs.documents.length}');
        if (doc['user_id'] != DataMangerService.currentUser.id) {
          // update
          await updateDocument(GlobalData.FB_DOC_INVITES, doc.documentID,
              GlobalData.FB_FIELD_USER_ID, DataMangerService.currentUser.id);
        }
        // create object
        InviteObject io = InviteObject(
            id: doc.documentID,
            email: doc['email'],
            gameID: doc['game_id'],
            inviteState: InviteStates.values[doc['invite_state']],
            inviterUserID: doc['inviter_user_id'],
            userID: doc['user_id']);
//        // add extra data -- this throws the data out of sync....
        io.questionObject =
            await loadQuestionFromQuery(GlobalData.FB_FIELD_GAME_ID, io.gameID);
        io.inviterUserObject =
            await _userServices.getUserViaDocID(io.inviterUserID);
        list.add(io);
      });
    }).catchError((onError) {
      debugPrint(':::::RQ::::: Invitations  error ${onError.toString()}');
    }).whenComplete(() => debugPrint(
            ':::::RQ::::: COMPLETE loadAllInvitations ${list.length}'));
    return list;
}
```

**Comment by jrmarkham** [comment] 2019-07-01 17:03
Ok so I figured out the issue -- I am leaving it open because this should work with the code above.

So it is the forEach Loop -- that disrupts the synchronization. If I use a for loop -- all is well: 

So this code below works:


```
Future<List<InviteObject>> loadAllInvitations(
      BaseUserServices _userServices) async {
    List<InviteObject> list = [];
    await Firestore.instance
        .collection(GlobalData.FB_DOC_INVITES)
        .where(GlobalData.FB_FIELD_EMAIL,
            isEqualTo: DataMangerService.currentUser.email)
        .getDocuments()
        .then((docs) async {
      final int len = docs.documents.length;
      int idx;
      // QuerySnapshot doc;
      for (idx = 0; idx < len; idx++) {
        // doc = docs.documents[idx];
        if (docs.documents[idx]['user_id'] !=
            DataMangerService.currentUser.id) {
          // update
          await updateDocument(
              GlobalData.FB_DOC_INVITES,
              docs.documents[idx].documentID,
              GlobalData.FB_FIELD_USER_ID,
              DataMangerService.currentUser.id);
        }
        // create object
        InviteObject io = InviteObject(
            id: docs.documents[idx].documentID,
            email: docs.documents[idx]['email'],
            gameID: docs.documents[idx]['game_id'],
            inviteState:
                InviteStates.values[docs.documents[idx]['invite_state']],
            inviterUserID: docs.documents[idx]['inviter_user_id'],
            userID: docs.documents[idx]['user_id']);
//        // add extra data
        io.questionObject =
            await loadQuestionFromQuery(GlobalData.FB_FIELD_GAME_ID, io.gameID);
        io.inviterUserObject =
            await _userServices.getUserViaDocID(io.inviterUserID);
        list.add(io);
      }

//
//      docs.documents.forEach((doc) async {
//        debugPrint(
//            ':::::RQ::::: COMPLETE loadAllInvitations ${docs.documents.length}');
//        if (doc['user_id'] != DataMangerService.currentUser.id) {
//          // update
//          await updateDocument(GlobalData.FB_DOC_INVITES, doc.documentID,
//              GlobalData.FB_FIELD_USER_ID, DataMangerService.currentUser.id);
//        }
//        // create object
//        InviteObject io = InviteObject(
//            id: doc.documentID,
//            email: doc['email'],
//            gameID: doc['game_id'],
//            inviteState: InviteStates.values[doc['invite_state']],
//            inviterUserID: doc['inviter_user_id'],
//            userID: doc['user_id']);
////        // add extra data
//        io.questionObject =
//            await loadQuestionFromQuery(GlobalData.FB_FIELD_GAME_ID, io.gameID);
//        io.inviterUserObject =
//            await _userServices.getUserViaDocID(io.inviterUserID);
//        list.add(io);
      //     });
    }).catchError((onError) {
      debugPrint(':::::RQ::::: Invitations  error ${onError.toString()}');
    }).whenComplete(() => debugPrint(
            ':::::RQ::::: COMPLETE loadAllInvitations ${list.length}'));

    return list;
  }
```

**Comment by Saifallak** [comment] 2019-07-01 20:45
foreach doesn't wait for await/sync;
use it if you want to enable race only
use for instead;


check this https://www.coreycleary.me/why-does-async-await-in-a-foreach-not-actually-await/

**Comment by jrmarkham** [comment] 2019-07-01 20:53
Thanks -- yes I update the forEach loop according. thanks.

**Comment by Saifallak** [comment] 2019-07-01 20:55
so this is NOT a bug, so shall you close it ?

**Closed** 2019-07-01 20:58 UTC
