### ISSUE TITLE
[go_router] Push and replace don't get along

### ISSUE THREAD

**Issue by hugofpsilva** [flutter/flutter#111356] opened 2022-09-10 23:28 UTC
Disclaimer: I'm not actually sure if this is a bug or working as intended.

## Description
After a page was pushed, replacing that page with itself causes a page transition, regardless of params or queryParams, but only on the first replace. I believe this is caused by a flag appended to the pushed page's key, which is not respected on replacements.

This bug doesn't happen when no push occurs, since no flag was appended to the key. (when the page being replaced was navigated to via go)

As a simple example of why this behaviour is strange to me, imagine a calendar app. Tapping one of the days of the month will push that day's page. Changing the day via replace will trigger a page transition, but the page hasn't changed, it is still a day page, only the day has changed. The app should transition seamlessly between days, but there is a page transition only on the first change.

## Steps to Reproduce
1. Run this [DartPad](https://dartpad.dev/8a65cc8faad8161264143f3707242aba), it is mostly self-explanatory;
2. Open one of the push pages (4-6);
3. Navigate using the bottom navigation bar;
4. You will see a page transition happening on the first navigation only.

**Expected results:**
No page transitions occurring between the same page, when only params or queryParams have changed.

**Actual results:**
Page transition occurs when replacing current page with itself, after that page was previously pushed.

**Comment by danagbemava-nc** [comment] 2022-09-12 10:38
Issue is reproducible using the code sample provided. Pasted below for easy access. 

Labeling for further insight from the team. 


<details>
<summary>recordings</summary>

| using push | using go | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/189632901-5021883e-f1db-4080-b36f-5677a546df32.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/189633064-b4b7d732-f59c-4f61-916e-b71ab97485f5.mov" /> | 

</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final GoRouter _goRouter = GoRouter(routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const HomePage(),
      routes: [
        GoRoute(
          path: 'page/:id',
          builder: (context, state) => ExamplePage(
            pageNumber: int.parse(state.params['id']!),
          ),
        ),
      ],
    ),
  ]);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'GoRouter Push/Replace',
      routerDelegate: _goRouter.routerDelegate,
      routeInformationParser: _goRouter.routeInformationParser,
      routeInformationProvider: _goRouter.routeInformationProvider,
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Root'),
      ),
      body: ListView(
        children: [
          const ListTile(
            title: Text('Go to pages (no bug)'),
            enabled: false,
          ),
          for (final i in [1, 2, 3]) PageTile(pageNumber: '$i', style: 'go'),
          const ListTile(
            title: Text('Push pages (bug occurs)'),
            enabled: false,
          ),
          for (final i in [4, 5, 6]) PageTile(pageNumber: '$i', style: 'push'),
        ],
      ),
    );
  }
}

class PageTile extends StatelessWidget {
  const PageTile({super.key, required this.pageNumber, required this.style});

  final String pageNumber;
  final String style;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text(
          style == 'go' ? 'Go to page $pageNumber' : 'Push page $pageNumber'),
      onTap: () => style == 'go'
          ? context.go('/page/$pageNumber')
          : context.push('/page/$pageNumber'),
    );
  }
}

class ExamplePage extends StatelessWidget {
  const ExamplePage({
    super.key,
    required this.pageNumber,
  });

  final int pageNumber;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page $pageNumber'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: ListView(
          children: _helperTextWidgets(
              context: context, style: pageNumber < 4 ? 'go' : 'push'),
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: <BottomNavigationBarItem>[
          for (final i in [1, 2, 3])
            BottomNavigationBarItem(
              icon: const Icon(Icons.pages),
              label: pageNumber > 3 ? '${i + 3}' : '$i',
            ),
        ],
        currentIndex: pageNumber > 3 ? pageNumber - 4 : pageNumber - 1,
        onTap: (index) =>
            context.replace('/page/${index + (pageNumber > 3 ? 4 : 1)}'),
      ),
    );
  }
}

List<Widget> _helperTextWidgets({
  required BuildContext context,
  required String style,
}) {
  final pages = Navigator.of(context).widget.pages;
  final keyList = <LocalKey>[];

  for (final page in pages) {
    if (page.key is LocalKey) {
      keyList.add(page.key!);
    }
  }
  return style == 'push'
      ? [
          Text('Current location: ${GoRouter.of(context).location}'),
          Text('Current stack keys: $keyList'),
          const SizedBox(height: 16),
          const Text(
              "Notice the push from the root page appends a -pX to the pushed page's key, where X is the push count."),
          const SizedBox(height: 16),
          const Text(
              'Clicking any of the buttons on the navbar below will call context.replace() to that new page, and remove the -pX flag.'),
          const SizedBox(height: 16),
          const Text(
              "Since the key is losing the -pX flag on that replace, a page transition will occur. From then on, since the page no longer has the -pX flag to lose, no further transitions occur on following replacements."),
          const SizedBox(height: 16),
          const Text(
              "Expected behaviour would be no page transitions between replaces of the same route which end up on the same page, since the page doesn't change."),
        ]
      : [
          Text('Current location: ${GoRouter.of(context).location}'),
          Text('Current stack keys: $keyList'),
          const SizedBox(height: 16),
          const Text(
              "As this page was navigated to via context.go(), nothing is appended to this page's key, meaning no bug occurs when calling context.replace()."),
          const SizedBox(height: 16),
          const Text(
              'You can safely and correcly navigate between pages using the navbar below, which uses context.replace(), that no page transition will show, since they are the same page, only with different params.'),
        ];
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.1 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (5 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • FFA1D5F7-87A1-4AC5-BE54-5CE70EAF3CEC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.192, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.192 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4930444f4a (2 days ago), 2022-09-09 21:58:23 -0400
    • Engine revision f72107f457
    • Dart version 2.19.0 (build 2.19.0-183.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • FFA1D5F7-87A1-4AC5-BE54-5CE70EAF3CEC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by chunhtai** [comment] 2022-09-15 21:51
According to the code page1-3 and page4-5 should behave the same. Needs more investigation

**Comment by hugofpsilva** [comment] 2022-11-20 05:18
Since go_router 5.1.8, where the changelog says

> Fixes a bug with `replace` where it was not generated a new `pageKey`.

this issue got even weirder.

The DartPad I provided is no longer accurate as of 5.1.8.

Apparently now every `replace` gets assigned a new `pageKey`, regardless of it having been `push`ed or `go`ne to, and regardless of if it is the same page but with different `params` or not.

Again, I believe replacing pages with themselves, where only `params` change, shouldn't trigger a new `pageKey`, which apparently trigger page animations, the content should just be replaced in place. If I am wrong and this is working as intended, please close this issue for me.

Thanks 😃

**Comment by ValentinVignal** [comment] 2023-02-15 06:43
I believe this is a duplicate of https://github.com/flutter/flutter/issues/115902 where I explained the issue with the keys
I also made a PR to try to fix it https://github.com/flutter/packages/pull/2846

**Comment by chunhtai** [comment] 2023-12-06 23:50
fixed

**Closed by chunhtai** 2023-12-06 23:50 UTC
Labels: package, has reproducible steps, P2, p: go_router, found in release: 3.3, found in release: 3.4, team-go_router, triaged-go_router, multiteam-retriage-candidate
