### ISSUE TITLE
expression_evaluation_test is flaky in "expressions returning complex objects"

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#148704] opened 2024-05-20 19:47 UTC
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_4_4/16869/overview

```
15:47 +84 ~1 -1: test/integration.shard/expression_evaluation_test.dart: flutter run expression evaluation - can evaluate expressions returning complex objects in build method [E]
  [Sentinel kind: Collected, valueAsString: <collected>] from evaluate()
  package:vm_service/src/vm_service.dart 265:34                  new _OutstandingRequest
  package:vm_service/src/vm_service.dart 1775:25                 VmService._call.<fn>
  package:vm_service/src/vm_service.dart 1787:8                  VmService._call
  package:vm_service/src/vm_service.dart 612:7                   VmService.evaluate
  test/integration.shard/test_driver.dart 362:37                 FlutterTestDriver.evaluate.<fn>
  ===== asynchronous gap ===========================
  test/integration.shard/test_driver.dart 479:7                  FlutterTestDriver._timeoutWithMessages.<fn>
  ===== asynchronous gap ===========================
  test/integration.shard/test_driver.dart 487:20                 FlutterTestDriver._timeoutWithMessages.<fn>
  ===== asynchronous gap ===========================
  test/integration.shard/expression_evaluation_test.dart 210:22  evaluateComplexReturningExpressions
  ===== asynchronous gap ===========================
  test/integration.shard/expression_evaluation_test.dart 90:5    batch1.<fn>
```

Flaking a lot in PRs:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_integration_tests_4_4, for example https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_integration_tests_4_4/35267/overview

**Comment by DanTup** [comment] 2024-05-20 20:27
This is the failing code:

https://github.com/flutter/flutter/blob/b2e5ab2e5761882b2c6bcd9cf4cc0146babd9ce4/packages/flutter_tools/test/integration.shard/expression_evaluation_test.dart#L207-L211

The test is calling the VM Service to evaluate the expression `new DateTime(2000)` and getting back an instance, and then evaluating `$year-$month-$day` against that instance (expecting to get back a string containing the year/month/day).

However, the VM Service is returning a collected sentinel (something that usually happens when the instance goes out of scope or possibly that a ring-buffer the VM Service uses to keep track of these results is exhausted).

@bkonyi I saw a similar failure somewhere recently (a sentinel being returned for code that I really would've expected would still be able to evaluate and get a response), but I thought it was a one-off. As far as I can tell, in this failing tests the VM is paused so this seems a little odd. Do you know of any changes or reasons they might fail like this? (is there any way to get more useful info to debug something like this?)

**Comment by zanderso** [comment] 2024-05-21 15:05
Nearly every run is failing now. I've escalated this to P0. @bkonyi is OOO today. Assigning to @aam to route to someone knowledgeable on this part of the VM service. I also created this PR to temporarily skip the test https://github.com/flutter/flutter/pull/148737

**Comment by DanTup** [comment] 2024-05-21 15:17
This reproduces for me locally (on Windows). This is the VM Service traffic with some comments.. The app is paused (first line here is `PauseBreakpoint`), `evaluateInFrame` works, but then `evaluate` against the returned instance just returns a sentinel.

```
# App pauses on breakpoint
<=vm=      {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseBreakpoint","isolateGroup":{"type":"@IsolateGroup","id":"isolateGroups/819498725695126","name":"main.dart","number":"819498725695126","isSystemIsolateGroup":false},"isolate":{"type":"@Isolate","id":"isolates/803073461992531","name":"main","number":"803073461992531","isSystemIsolate":false,"isolateGroupId":"isolateGroups/819498725695126"},"timestamp":1716304337124,"pauseBreakpoints":[{"type":"Breakpoint","fixedId":true,"id":"breakpoints/1","enabled":true,"breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@17089780/scripts/package%3Atest%2Fmain.dart/18f9bb5d7e3","uri":"package:test/main.dart"},"tokenPos":346,"line":16,"column":14}}],"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@17089780/scripts/package%3Atest%2Fmain.dart/18f9bb5d7e3","uri":"package:test/main.dart"},"tokenPos":346,"line":16,"column":14},"function":{"type":"@Function","fixedId":true,"id":"classes/1382/functions/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes/1382","name":"MyApp","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@17089780/scripts/package%3Atest%2Fmain.dart/18f9bb5d7e3","uri":"package:test/main.dart"},"tokenPos":214,"endTokenPos":454,"line":12,"column":3},"library":{"type":"@Library","fixedId":true,"id":"libraries/@17089780","name":"","uri":"package:test/main.dart"}},"static":false,"const":false,"implicit":false,"abstract":false,"isGetter":false,"isSetter":false,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@17089780/scripts/package%3Atest%2Fmain.dart/18f9bb5d7e3","uri":"package:test/main.dart"},"tokenPos":256,"endTokenPos":450,"line":13,"column":5}},"code":{"type":"@Code","fixedId":true,"id":"code/193d6b4077-158a183ca70","name":"[Unoptimized] MyApp.build","kind":"Dart","function":{"type":"@Function","fixedId":true,"id":"classes/1382/functions/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes/1382","name":"MyApp","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@17089780/scripts/package%3Atest%2Fmain.dart/18f9bb5d7e3","uri":"package:test/main.dart"},"tokenPos":214,"endTokenPos":454,"line":12,"column":3},"library":{"t...
=vm=>      {"jsonrpc":"2.0","id":"81","method":"getIsolate","params":{"isolateId":"isolates/803073461992531"}}
<=vm=      {"jsonrpc":"2.0","result":{"type":"Isolate","id":"isolates/803073461992531","name":"main","number":"803073461992531","isSystemIsolate":false,"isolateGroupId":"isolateGroups/819498725695126","_originNumber":"803073461992531","startTime":1716304336834,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":0,"avgCollectionPeriodMillis":0.0,"used":1167920,"capacity":1572864,"external":0,"time":0.0},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":2,"used":46003040,"capacity":47493120,"external":0,"time":0.000253,"avgCollectionPeriodMillis":146.793}},"isolateFlags":[{"name":"is_system_isolate","valueAsString":"false"},{"name":"is_service_isolate","valueAsString":"false"},{"name":"is_kernel_isolate","valueAsString":"false"}],"runnable":true,"livePorts":1,"pauseOnExit":false,"_isReloading":false,"pauseEvent":{"type":"Event","kind":"PauseBreakpoint","isolateGroup":{"type":"@IsolateGroup","id":"isolateGroups/819498725695126","name":"main.dart","number":"819498725695126","isSystemIsolateGroup":false},"isolate":{"type":"@Isolate","id":"isolates/803073461992531","name":"main","number":"803073461992531","isSystemIsolate":false,"isolateGroupId":"isolateGroups/819498725695126"},"timestamp":1716304337124,"pauseBreakpoints":[{"type":"Breakpoint","fixedId":true,"id":"breakpoints/1","enabled":true,"breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@17089780/scripts/package%3Atest%2Fmain.dart/18f9bb5d7e3","uri":"package:test/main.dart","_kind":"kernel"},"tokenPos":346,"line":16,"column":14}}],"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@17089780/scripts/package%3Atest%2Fmain.dart/18f9bb5d7e3","uri":"package:test/main.dart","_kind":"kernel"},"tokenPos":346,"line":16,"column":14},"function":{"type":"@Function","fixedId":true,"id":"classes/1382/functions/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes/1382","name":"MyApp","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@17089780/scripts/package%3Atest%2Fmain.dart/18f9bb5d7e3","uri":"package:test/main.dart","_kind":"kernel"},"tokenPos":214,"endTokenPos":454,"line":12,"column":3},"library":{"type":"@Library","fixedId":true,"id":"libraries/@17089780","name":"","uri":"package:test/main.dart"}},"_kind":"RegularFunction","static":false,"c...

# Evaluate expression "new DateTime(2000)" and get back instance
=vm=>      {"jsonrpc":"2.0","id":"82","method":"evaluateInFrame","params":{"isolateId":"isolates/803073461992531","frameIndex":0,"expression":"new DateTime(2000)"}}
<=vm=      {"jsonrpc":"2.0","result":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes/233","name":"DateTime","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@0150898/scripts/dart%3Acore%2Fdate_time.dart/0","uri":"dart:core/date_time.dart","_kind":"kernel"},"tokenPos":5038,"endTokenPos":31554,"line":136,"column":1},"library":{"type":"@Library","fixedId":true,"id":"libraries/@0150898","name":"dart.core","uri":"dart:core"}},"identityHashCode":3000307114,"id":"objects/7","kind":"PlainInstance","length":3},"id":"82"}

# Evaluate "$year-$month-$day" against that instance but get back collected sentintel
=vm=>      {"jsonrpc":"2.0","id":"83","method":"evaluate","params":{"isolateId":"isolates/803073461992531","targetId":"objects/7","expression":"\"$year-$month-$day\""}}
<=vm=      {"jsonrpc":"2.0","result":{"type":"Sentinel","kind":"Collected","valueAsString":"<collected>"},"id":"83"}
```

**Comment by aam** [comment] 2024-05-21 15:17
@kenzieschmoll  does this sound familiar? (per https://github.com/flutter/devtools/issues/7099)

**Comment by DanTup** [comment] 2024-05-21 15:30
I edited some additional notes into my comment above. I think this test may have always relied on an instance returned/created by an evaluated expression not being garbage collected, but now it is. We could update the test to not rely on this, but if the GC is happening more aggressively here, it could also affect users evaluating expressions during a debug session in the IDE in a similar way.

**Comment by aam** [comment] 2024-05-21 17:56
@rmacnak-google has theory that this is related to https://github.com/dart-lang/sdk/commit/4e6cd29eef8fc604721dad422ededa2ad98b9925 which could result in service response objects being gc'ed more aggressively.

**Comment by aam** [comment] 2024-05-21 18:02
Unfortunately I was not able to reproduce this myself locally neither on Windows, nor on Linux.
@DanTup can you please share what test invocation you use for your repro? Were you running the whole suite or just one test?

**Comment by DanTup** [comment] 2024-05-21 18:10
> @DanTup can you please share what test invocation you use for your repro? Were you running the whole suite or just one test?

I was just running:

```
flutter test test/integration.shard/expression_evaluation_test.dart
```

In `packages/flutter_tools` (I think I added `solo: true` to "can evaluate expressions returning complex objects in build method" to speed things up a bit too).

I was using current latest `master`. It's very reliable for me, but if the bots aren't failing 100% I suspect it's racy so maybe you'll have to run it a few times.

**Comment by rmacnak-google** [comment] 2024-05-21 20:42
> This makes me wonder whether these objects were ever really safe from collection here, and maybe this was always potentially flaky (and maybe GC is just triggering now where it wasn't before)?

Right, the lifetime of service ids that don't report fixedId=true is Undefined Behavior. (The timing of GC, the activity of other service clients and the size of the id ring are all undefined.) Unfortunately, the thing that was supposed to provide defined behavior never got implemented. The rough idea was to allow service clients to create id zones with a lifetime chosen by the client and to allow specifying as part of any service method which id zone to use for any ids that are part of the response. The VM still contains a partial implementation of this concept.

**Comment by DanTup** [comment] 2024-05-22 10:49
What's the best way to proceed? I can update these tests to work a little differently to not rely on an instance created this way - but it's not entirely clear to me if users might be affected in a similar way (eg. while debugging and evaluating expressions in the Debug Console / Watch window they will see errors about collected sentinels much more frequently).

**Comment by DanTup** [comment] 2024-05-22 10:51
Oh, I just saw https://github.com/dart-lang/sdk/commit/ffbbdb5a10a73d598db54823bcc1ce3feda59d07 by @rmacnak-google which I presume will fix this :-)

**Comment by rmacnak-google** [comment] 2024-05-28 23:22
@DanTup Right, kCollected is not possible after the recent change. I'd like to get back to a situation where the IDs aren't such a big addition to the root set and collection is possible again.

@bkonyi @derekxu16 We should consider some continuation of https://codereview.chromium.org//1132323002 to offer IDs with a lifetime the client can control, ideally tightly scoped to some high level operation.

**Comment by goderbauer** [comment] 2024-05-29 16:21
@DanTup Sorry, I hit the button on a wrong PR. Can you go ahead and open a PR? Thanks.

**Comment by a-siva** [comment] 2024-05-29 21:15
Can this issue be closed as @rmacnak-google 's fix has landed. @bkonyi has opened https://github.com/dart-lang/sdk/issues/55869 to track implementation of a better scheme to track these service IDs

**Closed** 2024-05-29 22:24 UTC
Labels: tool, dependency: dart, P2, c: flake, team-tool

**Comment by DanTup** [comment] 2024-05-29 22:26
I've landed a PR to unskip this test. If it shows up as flaky again, please let me know.
