### ISSUE TITLE
The setState not working with using the custom statefulWidget.

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#122165] opened 2023-03-08 03:52 UTC
I am using my custom icon button widget.
I tried to make a button that would be enabled when my condition is a success.
The enable button color and disable are different.
This feature is like the send button in the comment box on Facebook.
But this `setState` is not working and I don't know why.
This worked successfully in the `StatelessWidget`.

Example code (test in https://dartpad.dev/):
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: Scaffold(body: SafeArea(child: HomePage())));
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _isShowMuteButton = false;

  final Widget _normalButton =
      IconButtonWidget(icon: Icons.send_rounded, onClick: () {});
  final Widget _muteButton =
      const IconButtonWidget(icon: Icons.close, iconColor: Colors.white70);
  late final Widget _toggleButton = IconButton(
      icon: const Icon(Icons.abc),
      onPressed: () => setState(() => _isShowMuteButton = !_isShowMuteButton));

  @override
  Widget build(BuildContext context) {
    print('_isShowMuteButton: $_isShowMuteButton');
    return Column(
      children: [
        _isShowMuteButton ? _muteButton : _normalButton,
        const SizedBox(height: 20),
        _toggleButton
      ],
    );
  }
}

//my custom statefulWidget
class IconButtonWidget extends StatefulWidget {
  final IconData icon;
  final Color iconColor;
  final Function()? onClick;

  const IconButtonWidget({
    Key? key,
    required this.icon,
    this.iconColor = Colors.blue,
    this.onClick,
  }) : super(key: key);

  @override
  State<IconButtonWidget> createState() => _IconButtonWidgetState();
}

class _IconButtonWidgetState extends State<IconButtonWidget> {
  late final Widget _iconWidget = Icon(widget.icon, color: widget.iconColor);

  @override
  Widget build(BuildContext context) {
    print(widget.icon);
    Widget iconButtonWidget =
        Material(child: InkWell(onTap: widget.onClick, child: _iconWidget));
    iconButtonWidget = ClipOval(child: iconButtonWidget);
    return iconButtonWidget;
  }
}
```
In the terminal, the icon is changed when pressing the `_toggleButton`. but the UI does not change.
So I think, The second widget (`_muteButton`) uses the widget that is outside of the `builder` function from the old widget (`_normalButton`).

**Comment by huycozy** [comment] 2023-03-08 09:18
This is caused by `setState()` being called at an initializer. Try removing `late` at `late final Widget _toggleButton`, you will see this error.

```
The instance member 'setState' can't be accessed in an initializer.
```

To fix this, you can try below sample code. It works from my end.

<details>
<summary>Sample code (fixes)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: Scaffold(body: SafeArea(child: HomePage())));
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _isShowMuteButton = false;

  Widget _normalButton() => IconButtonWidget(icon: Icons.send_rounded, onClick: () {});
  Widget _muteButton() => IconButtonWidget(icon: Icons.close);

  @override
  Widget build(BuildContext context) {
    print('_isShowMuteButton: $_isShowMuteButton');
    return Column(
      children: [
        _isShowMuteButton ? _muteButton() : _normalButton(),
        const SizedBox(height: 20),
        toggleButton(),
      ],
    );
  }

  Widget toggleButton() => IconButton(
      icon: const Icon(Icons.abc),
      onPressed: () {
        setState(() {
          _isShowMuteButton = !_isShowMuteButton;
        });
      });

}

//my custom statefulWidget
class IconButtonWidget extends StatefulWidget {
  final IconData icon;
  final Color iconColor;
  final Function()? onClick;

  const IconButtonWidget({
    Key? key,
    required this.icon,
    this.iconColor = Colors.blue,
    this.onClick,
  }) : super(key: key);

  @override
  State<IconButtonWidget> createState() => _IconButtonWidgetState();
}

class _IconButtonWidgetState extends State<IconButtonWidget> {
  Widget _iconWidget() => Icon(widget.icon, color: widget.iconColor);

  @override
  Widget build(BuildContext context) {
    print(widget.icon);
    Widget iconButtonWidget =
    Material(child: InkWell(onTap: widget.onClick, child: _iconWidget()));
    iconButtonWidget = ClipOval(child: iconButtonWidget);
    return iconButtonWidget;
  }
}
```
</details>

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/223672599-3b4a1c2b-c144-4ca5-9d55-5eb1b993fd0b.mp4


</details>

Also, it seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

Closing for now.

**Closed by huycozy** 2023-03-08 09:18 UTC
Labels: in triage

**Comment by SittiphanSittisak** [comment] 2023-03-08 14:18
@huycozy Thank you for this trick.
I am using the `key` property to fix this.
