### ISSUE TITLE
Builder failed due to lack of iOS simulator

### ISSUE THREAD

**Issue by flar** [flutter/flutter#126092] opened 2023-05-04 19:22 UTC
Three failures in a row all complaining about not finding a simulator. The log of the builds shows that it ran fine on other bots so this may be a config issue with this one bot. See https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20plugin_lint_mac/25567/overview

```
[2023-05-04 10:13:38.021626] [STDOUT] stdout:  -> integration_test (0.0.1)
[2023-05-04 10:13:38.021681] [STDOUT] stdout:     - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.
```

**Comment by drewroengoogle** [comment] 2023-05-04 20:07
I ran this same build via led, on the same bot ([mac-297-g140](https://chromium-swarm.appspot.com/bot?id=mac-297-g140)) and it succeeded, which suggests to me that the bot is not the issue: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/drewroen_google.com/f39679ff88f5ce3030827be4eb8dbe7033268c100155b5c2329efcbfad2fed7f/+/build.proto?server=chromium-swarm.appspot.com

@keyonghan Any ideas you would suggest to find the root cause of this?

**Comment by keyonghan** [comment] 2023-05-04 20:41
The led run you triggered actually ran against [mac-507-g140](https://chromium-swarm.appspot.com/bot?id=mac-507-g140). @drewroengoogle 

The issue here is https://github.com/flutter/flutter/issues/125273. The root cause is [xcode installation](https://luci-milo.appspot.com/ui/p/flutter/builders/try/Mac%20tool_integration_tests_2_4/22856/overview), where build was canceled when installing xcode.

To unblock, I have cleaned the cache in this bot. @flar Please let me know if you still see issues on this bot.

I reopened the above bug to track. (closing here)

**Closed by keyonghan** 2023-05-04 20:41 UTC
Labels: team: infra, P3
