### ISSUE TITLE
Flutter 3.3.0 "flutter build appbundle" stopped and returning "exit code -1073741819"

### ISSUE THREAD

**Issue by amirudev** [flutter/flutter#111557] opened 2022-09-14 14:28 UTC
## Steps to Reproduce

1. I was completing my project and want to upload my appbundle to Play Store but the problem come when I tried to make an appbundle using command "flutter build appbundle"
2. The Command Prompt giving error outputs like this [+68523 ms] Dart snapshot generator failed with exit code -1073741819
[ +768 ms] Dart snapshot generator failed with exit code -1073741819
[ +234 ms] Dart snapshot generator failed with exit code -1073741819
[ +245 ms] > Task :app:compileFlutterBuildRelease FAILED
[  +20 ms] :app:compileFlutterBuildRelease (Thread[Execution worker for ':',5,main]) completed. Took 1 mins 11.652 secs.
[ +131 ms] FAILURE: Build failed with an exception.
3. Downgrading to Flutter 3.0.5 then the problem gone, I can build my app normally

## Logs

<details>
<summary>Logs</summary>

Task ':app:compileFlutterBuildRelease' is not up-to-date because:
[        ]   Task has failed previously.
[   +1 ms] Starting process 'command 'D:\Program\flutter\bin\flutter.bat''. Working directory:
D:\Projects\Flutter\eperpus_skiel Command: D:\Program\flutter\bin\flutter.bat --quiet assemble --no-version-check
--depfile D:\Projects\Flutter\eperpus_skiel\build\app\intermediates\flutter\release/flutter_build.d --output
D:\Projects\Flutter\eperpus_skiel\build\app\intermediates\flutter\release -dTargetFile=lib\main.dart
-dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true
android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
[   +1 ms] Successfully started process 'command 'D:\Program\flutter\bin\flutter.bat''
[+8202 ms] Dart snapshot generator failed with exit code -1073741819
[ +291 ms] Dart snapshot generator failed with exit code -1073741819
[   +1 ms] Dart snapshot generator failed with exit code -1073741819
[ +293 ms] > Task :app:compileFlutterBuildRelease FAILED
[  +28 ms] :app:compileFlutterBuildRelease (Thread[Execution worker for ':',5,main]) completed. Took 10.724 secs.
[ +179 ms] FAILURE: Build failed with an exception.
[  +14 ms] * Where:
[   +1 ms] Script 'D:\Program\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159
[  +15 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command 'D:\Program\flutter\bin\flutter.bat'' finished with non-zero exit value 1

Because I have done with this problem with downgrading Flutter from 3.3.0 to 3.0.5, so I don't have "flutter doctor -v" on 3.3.0 again, but I do have asked my friend giving him Flutter and Gradle version, maybe this can help you identify the problem

7 days ago
[  +99 ms] Flutter 3.3.1 • channel stable • https://github.com/flutter/flutter.git
           Framework • revision 4f9d92fbbd (7 days ago) • 2022-09-06 17:54:53 -0700
           Engine • revision 3efdf03e73
           Tools • Dart 2.18.0 • DevTools 2.15.0

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (JetBrains s.r.o 11.0.12+7-b1504.28-7817840)
OS:           Windows 10 10.0 amd64

</details>

=== Extras ===
At first I was think this problem reproduced by packages firebase_app_check or flutter_secure_storage, so I downgraded it both of them, but then, it still don't fix the problem, then I tried to downgrade Flutter and the problem gone, I can build my app normally.
as a reference, this is packages that I used after downgrading both dependencies
cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  mobile_scanner: ^2.0.0
  provider: ^6.0.3
  cached_network_image: ^3.2.1
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7
  sqflite: ^2.0.3+1
  path: ^1.8.1
  flip_card: ^0.6.0
  qr_flutter: ^4.0.0
  camera: ^0.10.0+1
  firebase_auth: ^3.7.0
  google_sign_in: ^5.4.1
  chips_choice_null_safety: ^2.0.2
  firebase_app_check: 0.0.6+20
  dropdown_plus: ^0.0.9
  flutter_secure_storage: 5.1.2
  animated_check: ^1.0.5
  restart_app: ^1.1.0+1

**Comment by Lorenzobettega** [comment] 2022-09-14 16:30
@amirudev this is a duplicate of #107590
If you can, please help us there with your error logs

**Comment by jason-simmons** [comment] 2022-09-14 23:17
The log above indicates that this is a different issue.  It's a crash in the Dart SDK `gen_snapshot` tool.

Is this still happening if you build using the Flutter master branch?

**Comment by amirudev** [comment] 2022-09-14 23:32
> The log above indicates that this is a different issue.  It's a crash in the Dart SDK `gen_snapshot` tool.
> 
> Is this still happening if you build using the Flutter master branch?
> 

yes, it's on Flutter 3.3.0 Master Branch

**Comment by amirudev** [comment] 2022-09-14 23:33
> @amirudev this is a duplicate of #107590
> If you can, please help us there with your error logs

Sorry for making duplicate issue, should I close this issue ?

**Comment by mraleph** [comment] 2022-09-16 13:58
> yes, it's on Flutter 3.3.0 Master Branch

Your `flutter doctor` output says that you are on stable rather than `master`, which is now at `3.4.0`.

It is unlikely that this is duplicate of https://github.com/flutter/flutter/issues/107590 - but we would need to check if it fails on master first. 

If it does fail on `master` we would need you to run something like `flutter build apk -v --release` and provide the log. After which we will try to give you instructions to try and localise the failure.

**Closed** 2022-10-11 12:12 UTC
Labels: waiting for customer response, dependency: dart
