### ISSUE TITLE
ListView becomes empty after scrolling up

### ISSUE THREAD

**Issue by fablue** [flutter/flutter#10030] opened 2017-05-12 13:31 UTC
## Issue
I am using a ListView to display a feed with flutter. Once I scroll far to the bottom and back up again
the ListView becomes empty. 
It happens only after scrolling down far. 

## Steps to Reproduce
Code used:

```dart
class Feed extends StatefulWidget{

  final int loadThreshold;
  final LimeApi _api;
  Feed(this._api, {this.loadThreshold: 5});

  
  @override
  State<StatefulWidget> createState() {
    return new _FeedState();
  }
  
}

class _FeedState extends State<Feed>{

  _FeedState(){
    print("new FeedState");
  }

  List<Map<String, dynamic>> posts = [];

  Widget _itemBuilder(BuildContext context, int i){
    return new PostWidget(posts[i]);
  }

  @override
  Widget build(BuildContext context) {
    return new Container(
      padding: new EdgeInsets.symmetric(horizontal: 0.0, vertical: 0.0),
      child: new ListView.builder(itemBuilder: _itemBuilder, itemCount: posts.length));

  }

  @override
  void initState() {
    super.initState();
    print("init FeedState");
    if(posts.length==0) {
      widget._api.getTrends().then((posts) =>
          setState(() {
            this.posts = posts;
          }));
    }
  }

  @override
  void dispose(){
    super.dispose();
    print("Feed disposed");
  }


}
```

## Flutter Doctor

] Flutter (on Linux, channel master)
    • Flutter at /opt/flutter
    • Framework revision dc4ca8db83 (vor 15 Stunden), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/sellmair/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] WebStorm (version 2017.1)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.1

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • Nexus 5X • 0214bed43bac24d0 • android-arm • Android 7.1.2 (API 25)

**Comment by eseidelGoogle** [comment] 2017-05-12 14:22
This sounds a lot like https://github.com/flutter/flutter/issues/9665 @FaisalAbid ?

@Hixie sounds like we now have two reports of this.  I wonder if posts is an iterator and can't go backwards?

**Comment by fablue** [comment] 2017-05-12 14:26
It sounds a lot like #9665! 
Here is the code which delivers the posts object! 

```dart
  Future <List<Map<String, String>>> getTrends() async {
    String url = "$server/trend?latitude=$latitude&longitude=$longitude";
    url = Uri.encodeFull(url);
    Response response = await client.get(
        url, headers: {"token": token});
    List<Map<String, String>> objects = JSON.decode(response.body);
    return objects.reversed.toList();
  }
```

**Comment by Hixie** [comment] 2017-06-06 20:51
Dupe of https://github.com/flutter/flutter/issues/9665.

**Closed by Hixie** 2017-06-06 20:51 UTC
Labels: prod: framework
