### ISSUE TITLE
Code signing Flutter.framework failed with a module

### ISSUE THREAD

**Issue by romanpozd-tg17** [flutter/flutter#69379] opened 2020-10-30 08:04 UTC
Hey guys!
We integrated flutter sub-module to our exist native android & iOS applications.
followed the documentation and modified the Podfile this way:

flutter_application_path = '../app-flutter-bond' load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ud-subject' do install_all_flutter_pods(flutter_application_path) end

it works perfect for regular builds but when I'm trying to archive an .ipa I receive the same error message that says 
"Code signing "Flutter.framework failed"
<img width="745" alt="Screen Shot 2020-10-29 at 16 55 32" src="https://user-images.githubusercontent.com/33596616/97703674-b0a7f000-1ab9-11eb-8dfc-327527b4446f.png">

with these logs:
[flutter-bond-logz1.docx](https://github.com/flutter/flutter/files/5465024/flutter-bond-logz1.docx)

pubspec.yaml file
<img width="1434" alt="Screen Shot 2020-10-30 at 13 57 13" src="https://user-images.githubusercontent.com/33596616/97703653-a84fb500-1ab9-11eb-90fd-05a6fb332669.png">

flutter doctor -v
```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-IL)
    • Flutter version 1.22.2 at /Users/roman/bin/flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/roman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/roman/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Pixel 4 XL (mobile) • 9A221FFBA002BF • android-arm64 • Android 11 (API 30)

```
Thanks

**Comment by TahaTesser** [comment] 2020-10-30 11:09
Hi @romanpozd-tg17 
Thanks for filing the issue, links you provided are 404 not found 

Can you please provide  logs from a fail build and a complete reproducible minimal code sample and steps to reproduce the issue 
Thank you

**Comment by romanpozd-tg17** [comment] 2020-10-30 11:54
[Uploading flutter-bond-logz1.docx…]()

**Comment by romanpozd-tg17** [comment] 2020-10-30 11:55
logs with archiving failure

[flutter-bond-logz1.docx](https://github.com/flutter/flutter/files/5464940/flutter-bond-logz1.docx)

**Comment by romanpozd-tg17** [comment] 2020-10-30 11:57
pubspec.yaml 

<img width="1434" alt="Screen Shot 2020-10-30 at 13 57 13" src="https://user-images.githubusercontent.com/33596616/97702548-d8965400-1ab7-11eb-9054-09b19952a5fc.png">

**Comment by romanpozd-tg17** [comment] 2020-10-30 12:04
I'm trying to integrate flutter inside our native android & iOS applications. 
Created flutter module with a screen and some method channels.
The module pushed to a different git repo and integrated to exist native app as a sub module.

To make it work during a development on iOS simulator I've run 
`flutter pub get` 
inside sub module directory and then 
`pod install` .
everything works fine on simulator (didn't try on real device yet).

yesterday tried to archive an .ipa an faced the `Code signing "Flutter.framework failed` error.

**Comment by TahaTesser** [comment] 2020-11-02 14:00
Hi @romanpozd-tg17 
This seems to be an issue with your signing, please make sure execute `flutter build ios` in the module and  you've no team id,s selected, has no errors there 

I just followed https://flutter.dev/docs/development/add-to-app/ios/project-setup#embed-the-flutter-module-in-your-existing-application in a new project on the latest stable, had no issues when generating and running on the device
<img width="560" alt="Screenshot 2020-11-02 at 7 24 18 PM" src="https://user-images.githubusercontent.com/48603081/97875873-05a96780-1d41-11eb-98bc-e2c7b82cbb0c.png">
archive 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8874f21e79 (4 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.1

! Doctor found issues in 1 category.
```

</details>

**Comment by romanpozd-tg17** [comment] 2020-11-02 18:29
finally found a solution for this issue:

added this run script to Build phases:

```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

if [$PLATFORM_NAME == *"simulator"*] 
then 
    exit 1
fi
    
find "$APP_PATH" -name 'Flutter*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done

```


and finally the code sign worked for me.

**Comment by TahaTesser** [comment] 2020-11-03 07:08
Hi @romanpozd-tg17 
Not sure why would you need this script, how did you figure you need this? Can you point to docs for this? 
Thank you

**Comment by pedromassangocode** [comment] 2020-11-24 10:13
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-24 10:13 UTC
Labels: in triage, waiting for customer response
