### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by CoderDeb-tech** [flutter/flutter#141854] opened 2024-01-19 11:13 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SentinelException
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2499:21)
#2      VmService.reloadSources (package:vm_service/src/vm_service.dart:2354:7)
#3      _reloadDeviceSources (package:flutter_tools/src/run_hot.dart:1275:33)
<asynchronous suspension>
#4      defaultReloadSourcesHelper (package:flutter_tools/src/run_hot.dart:1208:65)
<asynchronous suspension>
#5      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:958:38)
<asynchronous suspension>
#6      HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:868:16)
<asynchronous suspension>
#7      HotRunner.restart (package:flutter_tools/src/run_hot.dart:765:36)
<asynchronous suspension>
#8      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1777:40)
<asynchronous suspension>
#9      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1830:7)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel [user-branch], 3.16.5, on Microsoft Windows [Version 10.0.19045.3208],
    locale en-IN)
    [33m![39m Flutter version 3.16.5 on channel [user-branch] at C:\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    [33m![39m Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    [32m•[39m Framework revision 78666c8dc5 (4 weeks ago), 2023-12-19 16:14:14 -0800
    [32m•[39m Engine revision 3f3e560236
    [32m•[39m Dart version 3.2.3
    [32m•[39m DevTools version 2.28.4
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at D:\Sdk
    [32m•[39m Platform android-33, build-tools 34.0.0
    [32m•[39m Java binary at: D:\Android\Androidnew\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    [33m![39m Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.31)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.34114.132
    [31m✗[39m Visual Studio is missing necessary components. Please re-run the Visual Studio installer
      for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at D:\Android\Androidnew
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2020.2)
    [32m•[39m IntelliJ at D:\intelij\IntelliJ IDEA Community Edition 2020.2.3
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m Connected device (4 available)
    [32m•[39m Redmi Note 4 (mobile) • 337195850404 • android-arm64  • Android 7.0 (API 24)
    [32m•[39m Windows (desktop)     • windows      • windows-x64    • Microsoft Windows [Version
      10.0.19045.3208]
    [32m•[39m Chrome (web)          • chrome       • web-javascript • Google Chrome 120.0.6099.224
    [32m•[39m Edge (web)            • edge         • web-javascript • Microsoft Edge 120.0.2210.133

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**8dc57e9f7548ca9f8dd0740fbf0c658dc9
### Plugins
device_info_plus-9.1.1
syncfusion_flutter_pdfviewer-24.1.46
syncfusion_pdfviewer_macos-24.1.46
syncfusion_pdfviewer_web-24.1.46
syncfusion_pdfviewer_windows-24.1.46
url_launcher-6.2.3
url_launcher_android-6.2.2
url_launcher_ios-6.2.4
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.3
url_launcher_windows-3.1.1

**Comment by dam-ease** [comment] 2024-01-19 11:35
Closing as duplicate of https://github.com/flutter/flutter/issues/78214

**Closed by dam-ease** 2024-01-19 11:35 UTC
Labels: in triage
