### ISSUE TITLE
Click events on widgets over IFrames also get caught by the IFrame

### ISSUE THREAD

**Issue by goncalo-palma-3r** [flutter/flutter#65473] opened 2020-09-09 13:45 UTC
## Steps to Reproduce

1. Clone https://github.com/goncalo-palma-3r/iframe_tap_over_issue
2. Click on the button over the video

**Expected results:** 

If I click on an Flutter Widget over an IFrame, the click event event should **only** be registered by the Flutter Widget

**Actual results:** 

Both the IFrame element and the Flutter Widget register callbacks, in this case clicking on the button will print the output on the console and will start the video

<details>
  <summary>Logs</summary>

```[
✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    ✗ No valid Android SDK platforms found in /usr/lib/android-sdk/platforms. Directory was empty.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment] 2020-09-09 15:17
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 81a45ec2e5 (13 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.83

• No issues found!
```

</details> 

Similar issue, button is disabled on top of iFrame   https://github.com/flutter/flutter/issues/56477

**Comment by yjbanov** [comment] 2020-09-11 18:30
This is a duplicate of https://github.com/flutter/flutter/issues/54027

**Closed by yjbanov** 2020-09-11 18:30 UTC
Labels: dependency: dart, engine, found in release: 1.21, has reproducible steps, platform-web
