### ISSUE TITLE
Forms inside horizontal stepper behave incorrectly

### ISSUE THREAD

**Issue by realestatetechnologies** [flutter/flutter#63907] opened 2020-08-16 16:44 UTC
Bug: Using a horizontal stepper, if I type "123" into the first form field on **step 1** it also gets added to the first form field on **step 2**.  Its as if the the form fields are being recycled/reused. If I toggle the stepper type back to "vertical", the fields are no longer seemingly "coupled" and it works as expected:

Steps to reproduce the bug:

1) use the below code
2) type "123" into the name field
3) hit "next"
4) observe that "123" is incorrectly present in the "phone number" field. 
5) toggle the stepper type to "vertical"
6) repeat 1-4 and observe that 123 is correctly NOT present in the "phone number" field.

<details>
<summary> Sample code</summary>

```dart
import 'package:flutter/material.dart';
//import 'package:validate/validate.dart';  //for validation

void main() {
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new MyAppScreenMode();
  }
}

class MyData {
  String name = '';
  String phone = '';
  String email = '';
  String age = '';
}

class MyAppScreenMode extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        theme: new ThemeData(
          primarySwatch: Colors.lightGreen,
        ),
        home: new Scaffold(
          appBar: new AppBar(
            title: new Text('Steppers'),
          ),
          body: new StepperBody(),
        ));
  }
}

class StepperBody extends StatefulWidget {
  @override
  _StepperBodyState createState() => new _StepperBodyState();
}

class _StepperBodyState extends State<StepperBody> {
  int currStep = 0;
  static var _focusNode = new FocusNode();
  GlobalKey<FormState> _formKey = new GlobalKey<FormState>();
  static MyData data = new MyData();

  @override
  void initState() {
    super.initState();
    _focusNode.addListener(() {
      setState(() {});
      print('Has focus: $_focusNode.hasFocus');
    });
  }

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  List<Step> steps = [
    new Step(
        title: const Text('Name'),
        //subtitle: const Text('Enter your name'),
        isActive: true,
        //state: StepState.error,
        state: StepState.indexed,
        content: new TextFormField(
          focusNode: _focusNode,
          keyboardType: TextInputType.text,
          autocorrect: false,
          onSaved: (String value) {
            data.name = value;
          },
          maxLines: 1,
          //initialValue: 'Aseem Wangoo',
          validator: (value) {
            if (value.isEmpty || value.length < 1) {
              return 'Please enter name';
            }
          },
          decoration: new InputDecoration(
              labelText: 'Enter your name',
              hintText: 'Enter a name',
              //filled: true,
              icon: const Icon(Icons.person),
              labelStyle:
                  new TextStyle(decorationStyle: TextDecorationStyle.solid)),
        )),
    new Step(
        title: const Text('Phone'),
        //subtitle: const Text('Subtitle'),
        isActive: true,
        //state: StepState.editing,
        state: StepState.indexed,
        content: new TextFormField(
          keyboardType: TextInputType.phone,
          autocorrect: false,
          validator: (value) {
            if (value.isEmpty || value.length < 10) {
              return 'Please enter valid number';
            }
          },
          onSaved: (String value) {
            data.phone = value;
          },
          maxLines: 1,
          decoration: new InputDecoration(
              labelText: 'Enter your number',
              hintText: 'Enter a number',
              icon: const Icon(Icons.phone),
              labelStyle:
                  new TextStyle(decorationStyle: TextDecorationStyle.solid)),
        )),
    new Step(
        title: const Text('Email'),
        // subtitle: const Text('Subtitle'),
        isActive: true,
        state: StepState.indexed,
        // state: StepState.disabled,
        content: new TextFormField(
          keyboardType: TextInputType.emailAddress,
          autocorrect: false,
          validator: (value) {
            if (value.isEmpty || !value.contains('@')) {
              return 'Please enter valid email';
            }
          },
          onSaved: (String value) {
            data.email = value;
          },
          maxLines: 1,
          decoration: new InputDecoration(
              labelText: 'Enter your email',
              hintText: 'Enter a email address',
              icon: const Icon(Icons.email),
              labelStyle:
                  new TextStyle(decorationStyle: TextDecorationStyle.solid)),
        )),
    new Step(
        title: const Text('Age'),
        // subtitle: const Text('Subtitle'),
        isActive: true,
        state: StepState.indexed,
        content: new TextFormField(
          keyboardType: TextInputType.number,
          autocorrect: false,
          validator: (value) {
            if (value.isEmpty || value.length > 2) {
              return 'Please enter valid age';
            }
          },
          maxLines: 1,
          onSaved: (String value) {
            data.age = value;
          },
          decoration: new InputDecoration(
              labelText: 'Enter your age',
              hintText: 'Enter age',
              icon: const Icon(Icons.explicit),
              labelStyle:
                  new TextStyle(decorationStyle: TextDecorationStyle.solid)),
        )),
    // new Step(
    //     title: const Text('Fifth Step'),
    //     subtitle: const Text('Subtitle'),
    //     isActive: true,
    //     state: StepState.complete,
    //     content: const Text('Enjoy Step Fifth'))
  ];

  @override
  Widget build(BuildContext context) {
    void showSnackBarMessage(String message,
        [MaterialColor color = Colors.red]) {
      Scaffold
          .of(context)
          .showSnackBar(new SnackBar(content: new Text(message)));
    }

    void _submitDetails() {
      final FormState formState = _formKey.currentState;

      if (!formState.validate()) {
        showSnackBarMessage('Please enter correct data');
      } else {
        formState.save();
        print("Name: ${data.name}");
        print("Phone: ${data.phone}");
        print("Email: ${data.email}");
        print("Age: ${data.age}");

        showDialog(
            context: context,
            child: new AlertDialog(
              title: new Text("Details"),
              //content: new Text("Hello World"),
              content: new SingleChildScrollView(
                child: new ListBody(
                  children: <Widget>[
                    new Text("Name : " + data.name),
                    new Text("Phone : " + data.phone),
                    new Text("Email : " + data.email),
                    new Text("Age : " + data.age),
                  ],
                ),
              ),
              actions: <Widget>[
                new FlatButton(
                  child: new Text('OK'),
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                ),
              ],
            ));
      }
    }

    return new Container(
        child: new Form(
      key: _formKey,
      child: new Stepper(
          steps: steps,
          type: StepperType.horizontal,
          currentStep: this.currStep,
          onStepContinue: () {
            setState(() {
              if (currStep < steps.length - 1) {
                currStep = currStep + 1;
              } else {
                currStep = 0;
              }
              // else {
              // Scaffold
              //     .of(context)
              //     .showSnackBar(new SnackBar(content: new Text('$currStep')));

              // if (currStep == 1) {
              //   print('First Step');
              //   print('object' + FocusScope.of(context).toStringDeep());
              // }

              // }
            });
          },
          onStepCancel: () {
            setState(() {
              if (currStep > 0) {
                currStep = currStep - 1;
              } else {
                currStep = 0;
              }
            });
          },
          onStepTapped: (step) {
            setState(() {
              currStep = step;
            });
          },
        ),
    ));
  }
}
```
</details>

Flutter doctor output:

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.114, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.21.0-10.0.pre.114 at /Users/fsbo/dev/flutter
    • Framework revision b2c0970aa7 (7 hours ago), 2020-08-16 06:11:02 -0400
    • Engine revision b300be3df3
    • Dart version 2.10.0 (build 2.10.0-34.0.dev)


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/fsbo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • FDD25567-8440-4E2F-A54E-E30147EFADC0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
```

**Comment by Abhishek01039** [comment] 2020-08-16 18:45
Hi @realestatetechnologies 
This is not meant for your personal code assistance
please ask this question to https://flutter.dev/community
Thanks

**Comment by realestatetechnologies** [comment] 2020-08-17 05:03
@Abhishek01039 - I'm filling this issue due to clearly broken behavior with flutter-vended widgets. I'm not sure what posting on community forums would do?

**Comment by pedromassangocode** [comment] 2020-08-17 12:30
I was able to reproduce this on latest `master` channel.

@realestatetechnologies You may want to add keys to your TextFields to workaround this issue, so that each TextField will have its own identity.

<details>
<summary> minimal reproducible complete code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyData {
  String name = '';
  String phone = '';
  String email = '';
  String age = '';
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        theme: new ThemeData(
          primarySwatch: Colors.lightGreen,
        ),
        home: new Scaffold(
          appBar: new AppBar(
            title: new Text('Steppers'),
          ),
          body: new StepperBody(),
        ));
  }
}

class StepperBody extends StatefulWidget {
  @override
  _StepperBodyState createState() => new _StepperBodyState();
}

class _StepperBodyState extends State<StepperBody> {
  int currStep = 0;
  static var _focusNode = new FocusNode();
  GlobalKey<FormState> _formKey = new GlobalKey<FormState>();
  static MyData data = new MyData();

  @override
  void initState() {
    super.initState();
    _focusNode.addListener(() {
      setState(() {});
      print('Has focus: $_focusNode.hasFocus');
    });
  }

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  List<Step> steps = [
    new Step(
        title: const Text('Name'),
        //subtitle: const Text('Enter your name'),
        isActive: true,
        //state: StepState.error,
        state: StepState.indexed,
        content: new TextFormField(
          focusNode: _focusNode,
          keyboardType: TextInputType.text,
          autocorrect: false,
          onSaved: (String value) {
            data.name = value;
          },
          maxLines: 1,
          validator: (value) {
            if (value.isEmpty || value.length < 1) {
              return 'Please enter name';
            }
          },
          decoration: new InputDecoration(
              labelText: 'Enter your name',
              hintText: 'Enter a name',
              //filled: true,
              icon: const Icon(Icons.person),
              labelStyle:
              new TextStyle(decorationStyle: TextDecorationStyle.solid)),
        )),
    new Step(
        title: const Text('Phone'),
        //subtitle: const Text('Subtitle'),
        isActive: true,
        //state: StepState.editing,
        state: StepState.indexed,
        content: new TextFormField(
          keyboardType: TextInputType.phone,
          autocorrect: false,
          validator: (value) {
            if (value.isEmpty || value.length < 10) {
              return 'Please enter valid number';
            }
          },
          onSaved: (String value) {
            data.phone = value;
          },
          maxLines: 1,
          decoration: new InputDecoration(
              labelText: 'Enter your number',
              hintText: 'Enter a number',
              icon: const Icon(Icons.phone),
              labelStyle:
              new TextStyle(decorationStyle: TextDecorationStyle.solid)),
        )),
    new Step(
        title: const Text('Email'),
        // subtitle: const Text('Subtitle'),
        isActive: true,
        state: StepState.indexed,
        // state: StepState.disabled,
        content: new TextFormField(
          keyboardType: TextInputType.emailAddress,
          autocorrect: false,
          validator: (value) {
            if (value.isEmpty || !value.contains('@')) {
              return 'Please enter valid email';
            }
          },
          onSaved: (String value) {
            data.email = value;
          },
          maxLines: 1,
          decoration: new InputDecoration(
              labelText: 'Enter your email',
              hintText: 'Enter a email address',
              icon: const Icon(Icons.email),
              labelStyle:
              new TextStyle(decorationStyle: TextDecorationStyle.solid)),
        )),
    new Step(
        title: const Text('Age'),
        // subtitle: const Text('Subtitle'),
        isActive: true,
        state: StepState.indexed,
        content: new TextFormField(
          keyboardType: TextInputType.number,
          autocorrect: false,
          validator: (value) {
            if (value.isEmpty || value.length > 2) {
              return 'Please enter valid age';
            }
          },
          maxLines: 1,
          onSaved: (String value) {
            data.age = value;
          },
          decoration: new InputDecoration(
              labelText: 'Enter your age',
              hintText: 'Enter age',
              icon: const Icon(Icons.explicit),
              labelStyle:
              new TextStyle(decorationStyle: TextDecorationStyle.solid)),
        )),
    // new Step(
    //     title: const Text('Fifth Step'),
    //     subtitle: const Text('Subtitle'),
    //     isActive: true,
    //     state: StepState.complete,
    //     content: const Text('Enjoy Step Fifth'))
  ];

  @override
  Widget build(BuildContext context) {
    return new Container(
        child: new Form(
          key: _formKey,
          child: new Stepper(
            steps: steps,
            type: StepperType.horizontal,
            currentStep: this.currStep,
            onStepContinue: () {
              setState(() {
                if (currStep < steps.length - 1) {
                  currStep = currStep + 1;
                } else {
                  currStep = 0;
                }
              });
            },
            onStepCancel: () {
              setState(() {
                if (currStep > 0) {
                  currStep = currStep - 1;
                } else {
                  currStep = 0;
                }
              });
            },
            onStepTapped: (step) {
              setState(() {
                currStep = step;
              });
            },
          ),
        ));
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.114, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.21.0-10.0.pre.114 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision b2c0970aa7 (26 hours ago), 2020-08-16 06:11:02 -0400
    • Engine revision b300be3df3
    • Dart version 2.10.0 (build 2.10.0-34.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone SE (2nd generation) (mobile) • 1119074E-0493-4533-9212-6758A33EB40C
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 84.0.4147.125

! Doctor found issues in 3 categories.
```
</details>

**Comment by Aravin** [comment] 2020-10-10 17:04
I am facing the same issue.

It is very blunder BUG from flutter. It spoils 2 of my production ready app.

Raised a bug:  #67829

**Comment by Aravin** [comment] 2020-10-10 17:08
> I was able to reproduce this on latest `master` channel.
> 
> @realestatetechnologies You may want to add keys to your TextFields to workaround this issue, so that each TextField will have its own identity.
> 
>  minimal reproducible complete code
>  flutter doctor -v

How to add keys to your TextFields?

**Comment by Aravin** [comment] 2020-10-10 18:25
If I add key to the TextFields, data in the step 1 gets reset on navigating to step 2. 😓

**Comment by iapicca** [comment] 2020-10-10 20:15
> How to add keys to your TextFields?

`TextField(key: Key('username'))`

**Comment by Aravin** [comment] 2020-10-11 05:47
Your workaround TextField(key: Key('username')) is not working.

It is resetting the data in step 1 when I navigate to step 2.

**Comment by iapicca** [comment] 2020-10-11 08:26
> Your workaround TextField(key: Key('username')) is not working.

> @realestatetechnologies , @Aravin
> please look at this [code sample](https://dartpad.dartlang.org/f377382a0fa9c33c9c2a6f90db162d16)
> _**without the need of keys everything works as intended**_

@Aravin did you try this [code sample](https://dartpad.dartlang.org/f377382a0fa9c33c9c2a6f90db162d16)?
please note that is not a workaround, but rather a correct implementation

**Comment by Aravin** [comment] 2020-10-11 12:50
Your example uses `FormState`.  I have implemented using `FormBuilderState`

@iapicca

**Comment by iapicca** [comment] 2020-10-11 14:08
> Your example uses `FormState`. I have implemented using `FormBuilderState`

as mentioned [here](https://github.com/flutter/flutter/issues/67829#issuecomment-706604916) you [code sample](https://github.com/Aravin/WarrantyManager/blob/2fd22e30d985c2feeecc4b53a1e5cf8242b593cf/lib/screens/add.dart#L207) depends from 3rd party plugins

and most importantly goal of this github repo isn't to provide assistance for personal code,
but to improve flutter with bug report and feature request

I see you already asked a [question](https://stackoverflow.com/questions/64290126/flutter-stepper-data-persist-from-step1-to-step2-during-navigation-and-step2) on stackoverflow; I believe that's the right way to address the issue

I'm sure this issue has been opened in absolute good faith,
nevertheless the experienced behavior is likely to depend from the implementation
rather than from a bug within flutter

please see the [code sample](https://dartpad.dartlang.org/f377382a0fa9c33c9c2a6f90db162d16) [above](https://github.com/flutter/flutter/issues/63907#issuecomment-706605331) for reference

**Comment by Aravin** [comment] 2020-10-11 14:40
@iapicca 

I am not asking for code assistance.

It is an bug from Flutter. My formbuilder is not complex, i am just following a steps from [flutter cookbook](https://flutter.dev/docs/cookbook/forms/validation).

Tell me the reason - why the field `price` is shown in `phoneNumber` in both step ?

The third party package internally uses flutter widget.

**Comment by paulsam1016** [comment] 2021-08-03 18:17
@iapicca your code does not solve the problem, it's just an overly complicated workaround.

And about you saying your code's the correct implementation is wrong from a developer standpoint, because the Vertical Stepper works fine without any additional code.

This implies that there is a bug in the Stepper Library.
After going through the code for the Stepper Library it is more evident.
<details>
<summary><b>Vertical Stepper(_buildVertical)</b></summary>
<pre>
Column(
  <b><em>key: _keys[i],                # MISSING in Horizontal Stepper(_buildHorizontal)</em></b>
  children: <Widget>[
    InkWell(
      onTap: widget.steps[i].state != StepState.disabled
          ? () {
              // In the vertical case we need to scroll to the newly tapped
              // step.
              Scrollable.ensureVisible(
                _keys[i].currentContext!,
                curve: Curves.fastOutSlowIn,
                duration: kThemeAnimationDuration,
              );
              widget.onStepTapped?.call(i);
            }
          : null,
      canRequestFocus: widget.steps[i].state != StepState.disabled,
      child: _buildVerticalHeader(i),
    ),
    _buildVerticalBody(i),
  ],
)
</pre>
</details>
<details>
<summary><b>Horizontal Stepper(_buildHorizontal)</b></summary>
<pre>
Column(
  children: <Widget>[
    Material(
      elevation: widget.elevation ?? 2,
      child: Container(
        margin: const EdgeInsets.symmetric(horizontal: 24.0),
        child: Row(
          children: children,
        ),
      ),
    ),
    Expanded(
      child: ListView(
        physics: widget.physics,
        padding: const EdgeInsets.all(24.0),
        children: <Widget>[
          AnimatedSize(
            curve: Curves.fastOutSlowIn,
            duration: kThemeAnimationDuration,
            child: widget.steps[widget.currentStep].content,
          ),
          _buildVerticalControls(),
        ],
      ),
    ),
  ],
)
</pre>
</details>

As you can see the `key` for the `Column` widget of `_buildHorizontal()` function is missing, this causes the issue.

<details>
<summary><b>Expected Horizontal Stepper(_buildHorizontal)</b></summary>
<pre>
Column(
  <b><em>key: _keys[widget.currentStep],                # TO ADD</em></b>
  children: <Widget>[
    Material(
      elevation: widget.elevation ?? 2,
      child: Container(
        margin: const EdgeInsets.symmetric(horizontal: 24.0),
        child: Row(
          children: children,
        ),
      ),
    ),
    Expanded(
      child: ListView(
        physics: widget.physics,
        padding: const EdgeInsets.all(24.0),
        children: <Widget>[
          AnimatedSize(
            curve: Curves.fastOutSlowIn,
            duration: kThemeAnimationDuration,
            child: widget.steps[widget.currentStep].content,
          ),
          _buildVerticalControls(),
        ],
      ),
    ),
  ],
)
</pre>
</details>

Adding the key and running works fine, we get the desired result.

<details>
<summary><b>Workarround </b></summary>
Adding <code>key:</code>to the widget in <code>content:</code> in <b>Steps</b> also solves the issue.
<br>
<br>
<pre>
late List<GlobalKey> _keys;
void initState() {
  super.initState();
  _keys = List<GlobalKey>.generate(
    stepLength,
      (int i) => GlobalKey(),
  );
}
</pre>
<pre>
Step(
...
  content: Column(
    <b><em>key: _keys[#index],                # TO ADD</em></b>
    children: <Widget>[
...
</pre>
</details>

Don't know why this is not resolved yet for such an easy solution.

**Comment by iapicca** [comment] 2021-08-03 21:10
> @iapicca your code does not solve the problem, it's just an overly complicated workaround.

@paulsam1016 
I've updated the [sample](https://dartpad.dartlang.org/?id=f377382a0fa9c33c9c2a6f90db162d16&null_safety=true), could you please point out exactly which is the workaround? 
Besides a mocked state management, it seems by a `by-the-book` implementation to me

**Comment by svchostdotexe** [comment] 2021-12-05 10:34
i experience the same issues. any information on why this is not resolved? especially the fix by @paulsam1016 seems very lightweight and quick!

**Comment by maheshmnj** [comment] 2022-12-22 02:20
Hi @realestatetechnologies, I verified the issue on the stable 3.3 and master 3.7 and I can no longer reproduce it. I believe the bug is fixed.

https://user-images.githubusercontent.com/31410839/209040771-6c860f7a-37a9-42eb-a232-bb1d016a3af1.mov

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing, In case you still encounter the issue. Please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-22 02:20 UTC
Labels: a: text input, framework, f: material design, has reproducible steps, found in release: 1.21
