### ISSUE TITLE
MissingPluginException on Flutter Web

### ISSUE THREAD

**Issue by pluzmedia** [flutter/flutter#65515] opened 2020-09-10 03:38 UTC
I have been using firebase_messaging & geolocator which doesn't have support for Web. When i run on Web it's been throwing MissingPluginException and everything working fine with Android. Now my question is there any possible to disable those plugin while running on Web as i don't need those plugins on Web platform?. Any help would be appreciated, thanks.

**Comment by Abhishek01039** [comment] 2020-09-10 03:42
Hi @pluzmedia 
can you please provide `flutter run -v`, `flutter doctor -v`, and minimal reproduction code?
Thank

**Comment by pluzmedia** [comment] 2020-09-10 03:48
flutter doctor -v

[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.17134.1246], locale en-US)
    • Flutter version 1.21.0-9.2.pre at E:\Android\flutter-sdk\flutter
    • Framework revision 81a45ec2e5 (13 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

Reproduction code has nothing to do with this. Some plugins(which supports Android & iOS) are broken in Flutter Web and throws MissingPluginException. I need to disable those plugins on Web platform which is working fine without those plugins. The plugins are geolocator & firebase_messaging.

**Comment by Abhishek01039** [comment] 2020-09-10 04:34
Hi @pluzmedia 
can you please follow this blog for firebase messaging 
https://medium.com/@rody.davis.jr/how-to-send-push-notifications-on-flutter-web-fcm-b3e64f1e2b76
Thanks

**Comment by pluzmedia** [comment] 2020-09-10 04:35
Hi @Abhishek01039, 

I don't need to use those plugins on Web platform. I just want to disable it on web platform.

**Comment by Abhishek01039** [comment] 2020-09-10 04:38
please see my comment there 
https://github.com/Baseflow/flutter-permission-handler/issues/87#issuecomment-689975248
Thanks

**Comment by Abhishek01039** [comment] 2020-09-10 05:45
Hi @pluzmedia 
I guess you have got the answer to your issue
now you can close this issue
thanks.

**Comment by darshankawar** [comment] 2020-09-10 07:12
@pluzmedia,
`geolocator` is a 3rd party plugin for which it seems you already raised an issue and seemed to have resolved.
Regarding `firebase_messaging`, since it doesn't support web yet, you simply remove the plugin from `pubspec.yaml` if you have there or not use at all.
Hope this answers your question.
I am going ahead and closing this as this isn't an issue with Flutter. If you disagree, write in comments and I'll reopen.
Thanks

**Closed by darshankawar** 2020-09-10 07:12 UTC
