### ISSUE TITLE
Crash log triggered by AppBar code 

### ISSUE THREAD

**Issue by lilayoung** [flutter/flutter#48047] opened 2020-01-02 01:26 UTC
seems to have been triggered by me adding this line of code in a fresh flutter create app. when I reloaded flutter run everything behaved normally and new code was rendered. 

```
appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: IconButton(
          icon: Icon(Icons.account_circle),
          iconSize: 30.0,
          onPressed: () {},
        ),
      ),
```

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/lila/Desktop/jan_2020_repo/prototypes/flutter_app/.packages' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:95:62)
#4      _parse (package:flutter_tools/src/dart/package_map.dart:13:50)
#5      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:37:14)
#6      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:41:5)
#7      new PackageUriMapper (package:flutter_tools/src/compile.dart:202:84)
#8      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:590:26)
#9      _RecompileRequest._run (package:flutter_tools/src/compile.dart:415:16)
#10     _CompilationRequest.run (package:flutter_tools/src/compile.dart:395:30)
#11     DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:634:23)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#16     _DelayedData.perform (dart:async/stream_impl.dart:593:14)
#17     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
#18     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
#19     _rootRun (dart:async/zone.dart:1122:38)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132,
    locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/lila/developer/flutter
    [32m•[39m Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/lila/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.2

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 41.0.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 6 Plus • 1916E49C-90B0-4DD3-9455-F06901B5B5A5 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

[32m•[39m No issues found!
```

**Comment by VladyslavBondarenko** [comment] 2020-01-02 08:47
Hi @lilayoung 
I'm not sure that the exception was caused by changing AppBar widget. 
Can you reproduce it by doing the same steps?
Was not `.packages` file present in your root project directory after `flutter create app`?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-01-28 09:48
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by VladyslavBondarenko** 2020-01-28 09:48 UTC
Labels: waiting for customer response
