### ISSUE TITLE
Flutter is pulling up screwball versions of cmake

### ISSUE THREAD

**Issue by buzmeg** [flutter/flutter#75600] opened 2021-02-07 23:04 UTC
Hi, folks,

When I do 
```flutter build apk --verbose --target-platform android-arm64```

I get: 
```
[  +13 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +68 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6915495, mixed mode)
[   +2 ms] executing: [/Users/andrewl/flutter_dev/dev/native_streamer/example/android/] /Users/andrewl/flutter_dev/dev/native_streamer/example/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=lib/main.dart
-Ptrack-widget-creation=true -Pshrink=true -Ptree-shake-icons=true assembleRelease
[ +878 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':native_streamer:mergeReleaseNativeLibs'.
[        ] > Unable to get the CMake version located at: /Users/andrewl/Library/Android/sdk/cmake/3.6.4111459/bin
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 729ms
```

If I specifically demand a newer cmake with ```version "3.17.1+"``` in my build.gradle

I get:
```
[  +12 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +64 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6915495, mixed mode)
[   +2 ms] executing: [/Users/andrewl/flutter_dev/dev/native_streamer/example/android/] /Users/andrewl/flutter_dev/dev/native_streamer/example/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=lib/main.dart
-Ptrack-widget-creation=true -Pshrink=true -Ptree-shake-icons=true assembleRelease
[ +847 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':native_streamer:mergeReleaseNativeLibs'.
[        ] > Invalid revision: 3.18.1-g262b901
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 706ms
```

My local cmake is fine:
```
% cmake --version
cmake version 3.19.4
```

SDK claims to have installed the 3.18 as well:
![Screen Shot 2021-02-07 at 2 57 59 PM](https://user-images.githubusercontent.com/4359833/107161978-17f4fc00-6955-11eb-86e7-79e45d28dff6.png)

Why is flutter grabbing either ancient (3.6.4111459) or bizarre (3.18.1-g262b901) cmake versions and how do I get it to stop?

Thanks.

## Logs

<details>
<summary>Logs</summary>

```
% flutter build apk --verbose --target-platform android-arm64
[ +138 ms] executing: [/Users/andrewl/flutter_dev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +43 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[        ] executing: [/Users/andrewl/flutter_dev/flutter/] git tag --points-at HEAD
[  +16 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.6
[  +10 ms] executing: [/Users/andrewl/flutter_dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/andrewl/flutter_dev/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +46 ms] executing: [/Users/andrewl/flutter_dev/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H512
[   +1 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +43 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +87 ms] Found plugin native_streamer at /Users/andrewl/flutter_dev/dev/native_streamer/
[ +104 ms] Found plugin native_streamer at /Users/andrewl/flutter_dev/dev/native_streamer/
[  +35 ms] Generating /Users/andrewl/flutter_dev/dev/native_streamer/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +21 ms] executing: /usr/bin/xcodebuild -version
[ +104 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 12.4
           Build version 12D4e
[  +40 ms] Running Gradle task 'assembleRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +2 ms] Using gradle from /Users/andrewl/flutter_dev/dev/native_streamer/example/android/gradlew.
[        ] /Users/andrewl/flutter_dev/dev/native_streamer/example/android/gradlew mode: 33261 rwxr-xr-x.
[   +6 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[   +8 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/lo
g4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio4.1","idea.executable":"studio
","idea.platform.prefix":"AndroidStudio","idea.vendor.name":"Google","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-201.8743.12.41.7042882","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in Android Studio requests access to the device's
camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.ic
ns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"4.1","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCatego
ryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android Studio requests access to the user's Documents
folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a
network volume.","CFBundleGetInfoString":"Android Studio 4.1, build AI-201.8743.12.41.7042882. Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An application in Android Studio requests access to
files on a removable volume."}
[  +13 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +66 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6915495, mixed mode)
[   +2 ms] executing: [/Users/andrewl/flutter_dev/dev/native_streamer/example/android/] /Users/andrewl/flutter_dev/dev/native_streamer/example/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=lib/main.dart
-Ptrack-widget-creation=true -Pshrink=true -Ptree-shake-icons=true assembleRelease
[ +908 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':native_streamer:mergeReleaseNativeLibs'.
[        ] > Invalid revision: 3.18.1-g262b901
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 764ms
[ +348 ms] Running Gradle task 'assembleRelease'... (completed in 1.4s)
[   +8 ms] "flutter apk" took 1,803ms.
[   +4 ms] Gradle task assembleRelease failed with exit code 1
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +160 ms] ensureAnalyticsSent: 158ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
% flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H512 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/andrewl/flutter_dev/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/andrewl/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Pixel 4a (mobile) • 0A191JEC202802 • android-arm64 • Android 11 (API 30)

• No issues found!```

</details>

**Comment by buzmeg** [comment] 2021-02-08 07:56
Extra info: I can confirm that this behavior also exists on Ubuntu:

```$ uname -a
Linux andrewl-x1 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by buzmeg** [comment] 2021-02-08 08:10
That revision number exists only in the custom Android binaries:

```$ sudo find . -type f -exec fgrep g262b901 {} /dev/null \;
[sudo] password for andrewl: 
Binary file ./Android/Sdk/cmake/3.18.1/bin/cpack matches
Binary file ./Android/Sdk/cmake/3.18.1/bin/ctest matches
Binary file ./Android/Sdk/cmake/3.18.1/bin/cmake matches
Binary file ./Android/Sdk/cmake/3.18.1/bin/ccmake matches
```

My suspicion is that something in Gradle tries to pull up a semantic version that expects xx.yy.zz and hacks up a hairball when it gets that -g262b901 on the end.

At this point, this is *WAY* beyond my pay grade.  The Flutter, Dart, and Android Studio developers are going to have to hash this out.

So, until this is resolved, could someone tell me how to force an override on the builtin cmake executables so that flutter/dart/android studio use my system versions instead?

**Comment by buzmeg** [comment] 2021-02-08 11:20
Erm, I just notice but:

CMake 3.6 is 3.6.4111459
CMake 3.10 is 3.10.2.4988404
CMake 3.18 is 3.18.1-g262b901

Those non-numeric characters are probably causing havoc somewhere in the bowels of Gradle.

**Comment by TahaTesser** [comment] 2021-02-08 12:30
Hi @buzmeg 
How are you specifying the CMake version? When using `cmake_minimum_required` in `CMakeLists.txt` I a different error here when targeting 3.17.1+
```bash
[        ] > Task :app:processReleaseManifestForPackage
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 29 actionable tasks: 28 executed, 1 up-to-date
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:generateJsonModelRelease'.
[        ] > /Users/tahatesser/AndroidStudioProjects/beta_flutter/android/app/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake
Error at /Users/tahatesser/AndroidStudioProjects/beta_flutter/android/app/CMakeLists.txt:5 (cmake_minimum_required):
[        ]     CMake 3.17.1+ or higher is required.  You are running version 3.10.2
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 21s
[ +414 ms] Running Gradle task 'assembleRelease'... (completed in 21.8s)
[   +5 ms] "flutter apk" took 23,374ms.
[   +4 ms] Gradle task assembleRelease failed with exit code 1
```
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-17.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 4b50ca7f7f (3 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.146
! Doctor found issues in 2 categories.
```

</details>

**Comment by buzmeg** [comment] 2021-02-08 21:18
I'm setting it in the build.gradle:

```
android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 16
    }
    lintOptions {
        disable 'InvalidPackage'
    }

    // Added for dart ffi
    externalNativeBuild {
    // Encapsulates your CMake build configurations.
    cmake {
      // Provides a relative path to your CMake build script.
      path "CMakeLists.txt"
      version "3.17.1+"
    }
  }

}
```

By the time the CMakeLists.txt is being run, that's too late as the wrong cmake version has already been called.

**Comment by TahaTesser** [comment] 2021-02-09 07:29
Hi @buzmeg 
After making the changes ( I don't have local CMake) and the error is quite different
```bash
-Ptarget=/Users/tahatesser/AndroidStudioProjects/stable_flutter/lib/main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Pdart-defines=FLUTTER_WEB_AUTO_DETECT%3Dtrue assembleDebug
[+1619 ms] FAILURE: Build failed with an exception.
[   +4 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:mergeDebugNativeLibs'.
[        ] > CMake '3.17.1' or higher was not found in PATH or by cmake.dir property.
[        ]   - CMake '3.10.2' found in SDK could not satisfy requested version '3.17.1' because it was lower.
[        ]   - CMake '3.6.0' found in SDK could not satisfy requested version '3.17.1' because it was lower.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[ +462 ms] Running Gradle task 'assembleDebug'... (completed in 2,367ms)
[   +8 ms] Exception: Gradle task assembleDebug failed with exit code 1
[        ] "flutter run" took 61,422ms.
```

**Comment by buzmeg** [comment] 2021-02-09 13:03
It looks like something gets caught somewhere in Gradle and even cmake.dir got ignored.

I finally managed to make it use my system cmake even without adding cmake.dir.  Unfortunately, to do so I had to create a new blank account and reinstall everything from scratch and *NEVER* install any CMake from Android Studio.  This allowed my system CMake to get cached deep in the bowels of Gradle.

In addition, at some point Flutter *STILL* went and tried to install 3.6.0 but I managed to abort it before it got installed.

This is quite maddening.  It should just pick up 3.18 from the NDK and get on with life.

**Comment by TahaTesser** [comment] 2021-02-10 07:34
Hi @buzmeg 
Thanks for filing the issue, looks like something should be done here to make it less frustrating

**Comment by buzmeg** [comment] 2021-02-10 13:01
I really do think it is the non-numeric characters in the cmake version that are causing the issue.  Nobody expects to get something other than xx.yy.zz when they parse a semantic version.

**Comment by pavel-kolesnikov** [comment] 2021-05-19 11:51
Any news on this?

**Comment by buzmeg** [comment] 2021-05-22 10:01
Someone on the Gradle team actually pointed out that the issue is in the Android Gradle Plugin and needs to be fixed at Google.
https://github.com/gradle/gradle/issues/16555

This bug is clearly causing grief to a diverse set of folks.  How do we get this bumped in priority?

**Comment by stuartmorgan** [comment] 2022-07-26 17:44
Closing per the above, as this has been confirmed to be outside of Flutter's control.

**Closed by stuartmorgan** 2022-07-26 17:44 UTC
Labels: platform-android, tool, a: quality, passed first triage
