### ISSUE TITLE
[video_player] Video doesn't play on safari/chrome on iOS 

### ISSUE THREAD

**Issue by git9am** [flutter/flutter#79340] opened 2021-03-30 04:11 UTC
## Steps to Reproduce

1. Run `git clone https://github.com/flutter/plugins.git`.
2. `cd plugins/packages/video_player/video_player/example`
3. `flutter build web --web-renderer canvaskit`
4. Host the built web directory
5. Visit the site on the phone

The video_player plugin seems to be the core of all other video playing packages for flutter web. And this issue is blocking our application without any workaround.

PS: Tried on both Safari and Chrome and saw same issues.
PPS: It works on my Chrome on MacBook though.

**Expected results:** Videos loaded and played

**Actual results:** Videos never load and play

<details>
  <summary>flutter doctor -v</summary>

```
> [✓] Flutter (Channel master, 2.1.0-13.0.pre.303, on macOS 11.2.3 20D91 darwin-x64, locale en-CN)
    • Flutter version 2.1.0-13.0.pre.303 at /Users/hejq/flutter
    • Framework revision 39499bd2bf (3 hours ago), 2021-03-30 12:19:03 +1100
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)
    • Pub download mirror https://mirrors.cloud.tencent.com/dart-pub
    • Flutter download mirror https://mirrors.cloud.tencent.com/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hejq/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • ObjectPhone (mobile) • 0000****-00************** • ios            • iOS 14.4.2
```

</details>

https://user-images.githubusercontent.com/39660295/112932519-99485e00-9150-11eb-9d85-08947c71946c.mov

[10.37.51.100.har.zip](https://github.com/flutter/flutter/files/6226105/10.37.51.100.har.zip)

**Comment by Leffe108** [comment] 2021-03-30 06:07
You might have this issue https://github.com/flutter/flutter/issues/47030?

**Comment by maheshmnj** [comment] 2021-03-30 08:31
@git9am can you show the logs when you play the video.

**Comment by git9am** [comment] 2021-03-30 08:59
> @git9am can you show the logs when you play the video.

Hi maheshmnj, I built the example in release mode and visited it from a phone Safari. I host it with [serve](https://www.npmjs.com/package/serve) and check the phone browser's state via Mac Safari's web inspector. But I'm not seeing any log from the either the serve output or the browser console.

Am I missing anything?

**Comment by TahaTesser** [comment] 2021-03-30 10:12
Hi @git9am 
After testing, this looks like a duplicate of https://github.com/flutter/flutter/issues/47030 indeed
Closing as duplicate of https://github.com/flutter/flutter/issues/47030  
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-30 10:12 UTC
Labels: in triage
