### ISSUE TITLE
Scrollbar long list scroll freezes the app

### ISSUE THREAD

**Issue by dikeboy** [flutter/flutter#97087] opened 2022-01-23 06:44 UTC
My list have 10000 items,  When. i drag  the scrollbar.  it will  stuck/stop  for  seconds.  How to  drag scrollbar  smooth

**Comment by darshankawar** [comment] 2022-01-24 10:58
@dikeboy 
Can you provide `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior ?

**Comment by maheshmnj** [comment] 2022-01-27 09:24
I can reproduce this sample code taken from flutter sample https://docs.flutter.dev/cookbook/lists/long-lists

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MyApp(
      items: List<String>.generate(10000, (i) => 'Item $i'),
    ),
  );
}

class MyApp extends StatelessWidget {
  final List<String> items;

  const MyApp({Key? key, required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: const Text(title),
        ),
        body: ListView.builder(
          itemCount: 10000, /// changed item length
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(items[index]),
            );
          },
        ),
      ),
    );
  }
}
```

**Comment by dikeboy** [comment] 2022-01-28 01:06
> I can reproduce this issue, The app is frozen for a while when dragging 1000 items, sample code taken from flutter sample https://docs.flutter.dev/cookbook/lists/long-lists
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(
>     MyApp(
>       items: List<String>.generate(10000, (i) => 'Item $i'),
>     ),
>   );
> }
> 
> class MyApp extends StatelessWidget {
>   final List<String> items;
> 
>   const MyApp({Key? key, required this.items}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     const title = 'Long List';
> 
>     return MaterialApp(
>       title: title,
>       home: Scaffold(
>         appBar: AppBar(
>           title: const Text(title),
>         ),
>         body: ListView.builder(
>           itemCount: 10000, /// changed item length
>           itemBuilder: (context, index) {
>             return ListTile(
>               title: Text(items[index]),
>             );
>           },
>         ),
>       ),
>     );
>   }
> }
> ```

Maybe you can't drag the scrollbar, It will be stuck

**Comment by maheshmnj** [comment] 2022-01-28 05:51
I am able to reproduce the issue on stable and the master channel. running the above [code sample](https://github.com/flutter/flutter/issues/97087#issuecomment-1023007438) the app gets frozen for a while when dragging the scrollbar. Even if the listItems has 1000 items dragging the scrollbar is pretty laggy.

https://user-images.githubusercontent.com/31410839/151494477-6cfd9d43-9fdd-4e16-a561-1c590b8ff923.mov



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.307, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.307 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b7424c619c (7 hours ago), 2022-01-26 17:25:45 -0800
    • Engine revision c248c6e38e
    • Dart version 2.17.0 (build 2.17.0-63.0.dev)
    • DevTools version 2.10.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Piinks** [comment] 2022-02-02 23:05
This looks like a duplicate of https://github.com/flutter/flutter/issues/75399
I am going to close this as a duplicate, but feel free to re-open if you feel it is a separate issue. Thanks!

**Closed by Piinks** 2022-02-02 23:05 UTC
Labels: framework, f: scrolling, has reproducible steps, found in release: 2.8, found in release: 2.10
