### ISSUE TITLE
Upgrade to 1.25.0-8.1.pre beta version, when debug mode is turned on, the app will crash

### ISSUE THREAD

**Issue by stoneLee81** [flutter/flutter#72870] opened 2020-12-23 10:16 UTC
Upgrade to 1.25.0-8.1.pre beta version, when debug mode is turned on, the app will crash
```bash
flutter version:
Flutter 1.25.0-8.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f89f6505b (7 days ago) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```
```bash
exception info:
Build fingerprint: 'OnePlus/OnePlus7Pro_CH/OnePlus7Pro:10/QKQ1.190716.003/2007240000:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2020-12-23 18:12:44+0800
pid: 7906, tid: 8088, name: 1.ui  >>> com.tomato.flutter_module.host <<<
uid: 10796
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  00000076115df980  x3  00000076115df990
    x4  00000076115df950  x5  00000076115df890  x6  00000076115df910  x7  6c6b6a62ff776463
    x8  0000000000000000  x9  00000075af25ecc0  x10 00000075af37c810  x11 000000000000001a
    x12 000000000000001a  x13 0000000000270000  x14 0000000000000108  x15 0000aab286e992ff
    x16 00000075af2adc00  x17 000000769fce1350  x18 00000075ab2aa000  x19 00000075ab72da88
    x20 00000075ab72d6d8  x21 0000000000000000  x22 0000000000000000  x23 00000075ab72d6f8
    x24 00000076115df980  x25 00000076115df750  x26 000000759b551800  x27 00000076073b40c0
    x28 0000000000000000  x29 000000000000003d
    sp  00000075ab72d680  lr  00000075aef5a3dc  pc  00000075aef5a3e0
backtrace:
      #00 pc 00000000017183e0  /data/app/com.tomato.flutter_module.host-uoKI7rG4ePdoIeWh5sLZow==/lib/arm64/libflutter.so (BuildId: 9749f3c368c80b9282d5ea8491b15a9c229ed312)
      #01 pc 00000000001df98c  [anon:libc_malloc]
```

**Comment by TahaTesser** [comment] 2020-12-23 10:31
Hi @stoneLee81 
This seems to be https://github.com/flutter/flutter/issues/72627
Can you please upgrade to the latest  `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment] 2021-01-13 10:00
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-13 10:00 UTC
Labels: in triage, waiting for customer response
