### ISSUE TITLE
[web] Navigating out of the app and returning crash the debug session

### ISSUE THREAD

**Issue by arnaudelub** [flutter/flutter#90822] opened 2021-09-27 18:49 UTC
## Steps to Reproduce

First of all the version of Chrome is important. Version 94.0.4606.61 (Official Build) (64-bit) is the chrome version to use to reproduce this bug. I have tried with another version and it's working as expected (tried with Version 93.0.4577.82 (official Build)(x86_64).
Also working as expected with Brave browser

1. Run `flutter create bug`.
2. Update the files as follows:  
add:
```dart
import 'dart:html';
```
And modify the _incrementCounter() to:
```dart
void _incrementCounter() {
    window.location.href = 'https://google.com'
  }
```
3. launch the web app with flutter run -d chrome --web-port 8080
4. tap on the + button
5.  You are being redirected to google.com, wait for 5 to 10 sec then navigate back using the back button of the browser

**Expected results:** 
The web app should reload correctly

**Actual results:** 
white page, impossibility of reloading the web app

<details>
  <summary>Logs</summary>

```
flutter run --web-port 8081 --verbose                                                                                             64 ✘ 
[  +42 ms] executing: uname -m
[  +20 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +3 ms] executing: [/home/idelub/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] executing: [/home/idelub/Development/flutter/] git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[   +9 ms] Exit code 0 from: git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] 2.5.1
[   +5 ms] executing: [/home/idelub/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/idelub/Development/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +49 ms] executing: [/home/idelub/Development/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +32 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] executing: /home/idelub/Android/Sdk/platform-tools/adb devices -l
[  +21 ms] List of devices attached
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] Skipping pub get: version match.
[  +68 ms] Generating /home/idelub/Repository/Flutter/Bullfinch/testing/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +79 ms] Launching lib/main.dart on Chrome in debug mode...
[  +68 ms] Updating assets
[  +46 ms] Waiting for connection from debug service on Chrome...
[  +55 ms] <- reset
[   +4 ms] /home/idelub/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/idelub/Development/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/idelub/Development/flutter/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.GNZFGR/flutter_tool.QJJDDG/app.dill
--libraries-spec file:///home/idelub/Development/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/idelub/Repository/Flutter/Bullfinch/testing/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root /tmp/flutter_tools.GNZFGR/flutter_tools.UNQDRR --filesystem-scheme org-dartlang-app --initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill
--platform file:///home/idelub/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+11151 ms] Waiting for connection from debug service on Chrome... (completed in 11.2s)
[        ] Synced 26.2MB.
[        ] <- accept
[        ] Caching compiled dill
[ +404 ms] Using Google Chrome 94.0.4606.61 

[  +24 ms] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +122 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:39043/devtools/browser/b91d3fd8-bc23-48d0-9323-28654cd29fa8
[ +210 ms] DwdsInjector: Received request for entrypoint at http://localhost:8081/main_module.bootstrap.js
[   +2 ms] MetadataProvider: Loading debug metadata...
[   +8 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +3 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:8081/main_module.bootstrap.js
[+1545 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +44 ms] DevHandler: Debug service listening on ws://127.0.0.1:34521/BsYkAtIcGuw=/ws

[  +14 ms] This app is linked to the debug service: ws://127.0.0.1:34521/BsYkAtIcGuw=/ws
[   +5 ms] Debug service listening on ws://127.0.0.1:34521/BsYkAtIcGuw=/ws
[        ] 💪 Running with sound null safety 💪
[   +2 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[        ] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:34521/BsYkAtIcGuw=
[ +627 ms] DevTools activation throttled until 2021-09-28 04:27:02.347886.
[ +271 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:34521/BsYkAtIcGuw=
[+10748 ms] DwdsInjector: Received request for entrypoint at http://localhost:8081/main_module.bootstrap.js
[        ] MetadataProvider: Loading debug metadata...
[   +4 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +1 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:8081/main_module.bootstrap.js
[ +809 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
```

</details>

```
```
<details>

<summary>Flutter Doctor</summary>
```
flutter doctor -v                                                                                                ✔  14m 34s  
[✓] Flutter (Channel stable, 2.5.1, on Manjaro Linux 5.13.19-2-MANJARO, locale en_US.UTF-8)
    • Flutter version 2.5.1 at /home/idelub/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/idelub/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61

• No issues found!

```

</details>

**Comment by rmasarovic** [comment] 2021-09-27 22:51
i have same problem, i tried stable channel, dev channel, beta channel and have same problem

**Comment by fresnault** [comment] 2021-09-28 09:57
I have the same problem on my project.

I think the problem is with updating chrome version 94.0.4606.61. It worked in an earlier version of chrome.

**Comment by maheshmnj** [comment] 2021-09-28 11:08
Hi @rmasarovic Thanks for filing the issue, I can reproduce the issue on the latest stable 2.5.1 and the 
`master 2.6.0-12.0.pre.98` channel

When navigating back from Google the app crashes with `error code 6` and refresh does not work. 

![image](https://user-images.githubusercontent.com/31410839/135074790-114f08fe-d347-4517-aa81-71b2d42ad30e.png)



<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:html';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    window.location.href = 'https://google.com';
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              // Provide a Key to this specific Text widget. This allows
              // identifying the widget from inside the test suite,
              // and reading the text.
              key: const Key('counter'),
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        // Provide a Key to this button. This allows finding this
        // specific button inside the test suite, and tapping it.
        key: const Key('increment'),
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (11 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.98, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.98 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 48e6758fb5 (34 hours ago), 2021-09-26 21:28:03 -0400
    • Engine revision 65ad5a4836
    • Dart version 2.15.0 (build 2.15.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
</details>

**Comment by arnaudelub** [comment] 2021-09-28 11:17
hi, thanks  for following up and you're welcome. Important to mention is the version of chrome
**Chrome Version 94.0.4606.61 (Official Build) (64-bit)**

**Comment by maheshmnj** [comment] 2021-09-28 11:21
@arnaudelub its included in flutter doctor output :)

>Google Chrome 94.0.4606.61

**Comment by maheshmnj** [comment] 2021-09-28 11:32
Here's the browser console

![image](https://user-images.githubusercontent.com/31410839/135078820-c5589851-07c5-432e-9f93-00b47dd37b5f.png)

**Comment by maheshmnj** [comment] 2021-09-28 11:33
There are no logs in the flutter console and the browser console looks like this

![image](https://user-images.githubusercontent.com/31410839/135078820-c5589851-07c5-432e-9f93-00b47dd37b5f.png)

**Comment by tfreebern2** [comment] 2021-09-29 18:15
`flutter clean` && `flutter pub get` gets the app running again.

I just want to add that my app redirects the User to an Auth Server for login. After successful login, they are redirected back to my application.

This is the point where I receive the `Error Code 6` in Chrome.

**Comment by semsturgut** [comment] 2021-09-29 18:37
Same here. Google Chrome Apple Silicon Version 94.0.4606.61.

Unfortunately, I couldn't find older Apple Silicon versions for Chrome.

Temporary solution for x86_x64 (Also works on M1 Macs): 

Find and download older versions for chrome, such as this one: https://google-chrome.en.uptodown.com/mac/download/3945248

And here's how to stop auto update on macOS: 

`defaults write com.google.Keystone.Agent checkInterval 0`

https://www.stijit.com/tests-qa-automation/install-old-version-google-chrome-mac

Apple Silicon M1 macs are noticeably slower on Chrome x86_64 builds.

**Comment by tfreebern2** [comment] 2021-09-29 18:55
Downgrading Chrome worked for me

**Comment by bastosmichael** [comment] 2021-09-30 14:55
Another coworker tested `fvm flutter run -d chrome --profile` and it seemed to work as well, no debug unfortunately but at least it maintains oauth. Chrome decided to upgrade itself again on @tfreebern2 so not a long term solution having to downgrade every day.

**Comment by mdrideout** [comment] 2021-09-30 14:58
Yeah, it's specifically the debug / devtools that are broken. --profile mode compiles differently and is meant for minimal debugging with production-like settings for performance testing. Debug uses the dartdevc compiler for easier debugging.

**Comment by arnaudelub** [comment] 2021-09-30 15:24
for the moment i am using Brave instead of chrome.
In you env, just change:
```
export CHROME_EXECUTABLE="/usr/bin/chrome"
```
to 
```
export CHROME_EXECUTABLE="/usr/bin/brave"
```
or just add it if it's not present in your .bashrc or .zshenv.
And you  have to download Brave browser of course

**Comment by mdrideout** [comment] 2021-09-30 16:10
Anyone try Chrome Beta to see if it's fixed there?

**Comment by yjbanov** [comment] 2021-09-30 22:29
This looks like a Chrome bug. I'll file a Chrome issue.

**Comment by yjbanov** [comment] 2021-10-05 21:40
Looks like this was https://bugs.chromium.org/p/chromium/issues/detail?id=1252723 (merged into https://bugs.chromium.org/p/chromium/issues/detail?id=1250736). It is marked as fixed, so let's wait for the next Chrome release and verify the fix.

**Comment by nyck33** [comment] 2021-11-05 23:52
I'm getting this with Google Chrome 95.0.4638.69 when I try to debug in either VSCode or Android Studio.

**Comment by nyck33** [comment] 2021-11-06 00:35
@arnaudelub When I installed Brave on Ubuntu 20.04, I have `/usr/bin/brave-browser` and `usr/bin/brave-browser-stable`.  I tried putting `CHROME_EXECUTABLE=`"/usr/bin/brave-browser` and get with `flutter doctor -v`  
```
[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/brave-browser
```
but it still opens in Chrome when I push F5 to debug in VSCode.
However, this time when I get "aw snap...blah blah sigill" if I refresh the browser several times I can actually run in debug mode with breakpoints.  I'll try `brave-browser-stable` next.

**Comment by nyck33** [comment] 2021-11-09 04:50
I have the same issue with Brave now.

**Comment by christopherfujino** [comment] 2022-04-12 21:59
Looks like this was fixed as of https://github.com/flutter/flutter/issues/90822#issuecomment-934885235.

For users who are experiencing a similar problem in later versions, please file a new issue with full context, flutter doctor -v, etc.

**Closed by christopherfujino** 2022-04-12 21:59 UTC
Labels: tool, a: debugging, platform-web, d: devtools, has reproducible steps, assigned for triage, P3, found in release: 2.5, found in release: 2.6
