### ISSUE TITLE
No '/' in numeric keyboard for date_range_picker_dialog in Android Samsung S9 device

### ISSUE THREAD

**Issue by deviserRahul** [flutter/flutter#64928] opened 2020-08-31 05:25 UTC
## Steps to Reproduce

1. Use the date_range_picker_dialog (code below)
2. Install the app in Samsung S9 device.
3. Open the date picker in the app and switch to the manual entry type view.
4. You will notice that there is no '/' key in the keyboard to enter the character which is required for putting the date. Also, this character does not show up automatically on entering characters.

```
showDateRangePicker(
                context: context,
                initialDateRange: DateTimeRange(start: DateTime.now().subtract(Duration(days: 7)), end: DateTime.now()),
                firstDate: DateTime.now().subtract(Duration(days: 396)), //13 months
                lastDate: DateTime.now(),
                saveText: 'Done',
                helpText: 'Selected Range',
              )
```

Expected results:
The numeric keyboard should have '/' key.

Actual results:
The numeric keyboard does not have '/' key.

![Screenshot_20200828-165938](https://user-images.githubusercontent.com/14113872/91685591-66b59300-eb78-11ea-90ab-ac5f4ee42e75.jpg)

**Comment by hamdikahloun** [comment] 2020-08-31 08:33
Hi @deviserRahul 

Can you please provide:

- `flutter doctor -v`

- `flutter run --verbose`

**Comment by pedromassangocode** [comment] 2020-08-31 10:46
This issue was reproducible with latest stable channel on a Samsung S10 device and not reproducible with Pixel 3a API 30.

<details>
<summary> flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```
</details>

**Comment by HansMuller** [comment] 2020-08-31 15:56
CC @darrenaustin

**Comment by darrenaustin** [comment] 2020-08-31 20:12
This a duplicate of #62401. Closing this issue as we will track it on the other. Thanks for the report!

**Closed by darrenaustin** 2020-08-31 20:12 UTC
Labels: e: device-specific, f: date/time picker, f: material design, found in release: 1.20, framework, has reproducible steps, platform-android
