### ISSUE TITLE
Dartpad crashes when using draggable

### ISSUE THREAD

**Issue by Lootwig** [flutter/flutter#95133] opened 2021-12-12 23:25 UTC
Wanted to create an issue for another bug I found, but dartpad can't even get to the actual bug.

Open https://dartpad.dev/909fcfbd3bb0df0102ed322236b3ce81 and try to drag the number in "from" into "to".

After messing up the formatting of the `feedback` Widget when losing the theme, dartpad seems to crash once you release the mouse. There are no errors in the console.

**Comment by mamuseferha** [comment] 2021-12-13 09:45
Hi @Lootwig please report this to the dedicated dartpad repository here https://github.com/dart-lang/dart-pad/issues
I'll go ahead and close this now, if you disagree please write in the comments and I will reopen it.

**Closed by mamuseferha** 2021-12-13 09:45 UTC
Labels: in triage

**Comment by Lootwig** [comment] 2021-12-13 13:37
@mamuseferha https://github.com/dart-lang/dart-pad/issues/2107 they don't want to have this issue either ;)

**Comment by mamuseferha** [comment] 2021-12-14 07:21
Hi @Lootwig, I ran this locally using canvaskit rendering and got the same error here https://github.com/dart-lang/dart-pad/issues/2107#issuecomment-992473119.
Running in html rendering and no error is thrown `flutter run -d chrome --web-renderer html`. 

It looks like a duplicate of this issue https://github.com/flutter/flutter/issues/94906, you can follow up there. I'll be marking this as a duplicate and keeping it closed. 

Thank you.
