### ISSUE TITLE
Flutter app not supporting VPN on iOS?

### ISSUE THREAD

**Issue by jaggerwang** [flutter/flutter#21666] opened 2018-09-11 01:57 UTC
## Steps to Reproduce

I have a flutter app which using `cached_network_image` to display image and using `video_player` to display video. The image and video display correctly when debug in simulator on a MacBook Pro which set a system proxy to access foreign http resources, as I'm in China! But when build a release ipa and install on my iPhone which have a VPN to proxy foreign http resources, the image and video can't be displayed. I can browse these resources in Chrome app.

## Logs

```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.7.3 at /Users/jagger/flutter
    • Framework revision 3b309bda07 (13 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jagger/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/jagger/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by jaggerwang** [comment] 2018-11-21 09:10
any plan to support this feature? Then VPN is worked on Android.

**Comment by zoechi** [comment] 2018-12-10 09:58
Duplicate of #20704

**Closed by zoechi** 2018-12-10 09:58 UTC
Labels: a: fidelity, dependency: dart, engine, ⌺‬ platform-ios
