### ISSUE TITLE
Visual artifacts when paging using PageView on Android

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8524] opened 2017-03-02 07:04 UTC
Test device: **Pixel XL**

The `PageView` contents are rendered correctly on the initial render but once you start scrolling they become corrupted. They will remain this way even after the scrollable "settles".

The following are examples of text and a `Widget` near the edges of a `DecoratedBox`:

<img width="208" alt="screen shot 2017-03-01 at 10 48 52 pm" src="https://cloud.githubusercontent.com/assets/37941/23496477/463855da-fed3-11e6-8388-576ce8d90557.png">

<img width="435" alt="screen shot 2017-03-01 at 10 49 41 pm" src="https://cloud.githubusercontent.com/assets/37941/23496480/48415aac-fed3-11e6-9e5c-ddbe18a58d4e.png">

From @abarth (on Gitter): "it sounds like a problem in the raster cache that once we cache the texture for the page we draw the ugly version".

**Comment by chinmaygarde** [comment] 2017-03-02 07:12
Not really. The way we setup the raster cache entry hasn't changed at all recently. Will try to reproduce this issue. I have a Pixel XL I can test on.

**Comment by chinmaygarde** [comment] 2017-03-23 20:09
I see the issue. No updates yet.

**Comment by eseidelGoogle** [comment] 2017-03-23 23:05
There is at least one app in development shipping mid April which will be blocked by this.  We have time.  Just making note. :)

**Comment by eseidelGoogle** [comment] 2017-04-04 22:32
Are you actively working on this @chinmaygarde ?

**Comment by chinmaygarde** [comment] 2017-04-04 23:27
Yes, I am.

**Comment by eseidelGoogle** [comment] 2017-04-25 22:29
Any status updates?

**Comment by eseidelGoogle** [comment] 2017-05-02 22:03
Any news @chinmaygarde?

**Comment by chinmaygarde** [comment] 2017-05-02 22:43
The underlying issue causing https://github.com/flutter/flutter/issues/9276 affects this as well.

**Comment by eseidelGoogle** [comment] 2017-05-09 21:51
@chinmaygarde I presume this is not going to make the M2 `alpha` cut today and should get bumped to May?

**Comment by chinmaygarde** [comment] 2017-05-31 19:18
Update: https://github.com/flutter/engine/pull/3717 addresses this issue. Unfortunately, I am still dealing with the edge cases.

**Comment by eseidelGoogle** [comment] 2017-06-02 20:34
@lukef was asking me about this this morning (blocks *shipping* his next app, but not development currently).  Looks like good progress is being made, just needs a few more rounds of bug fixing?

**Comment by chinmaygarde** [comment] 2017-06-05 22:58
The fix for this issue has landed in https://github.com/flutter/engine/pull/3717.

**Closed by chinmaygarde** 2017-06-05 22:58 UTC
Labels: customer: posse (eap), regression, ▣ platform-android

**Comment by eseidelGoogle** [comment] 2017-06-05 23:05
Thank you @chinmaygarde!
