### ISSUE TITLE
[cloud_firestore] Exposing my Flutter app to the cloud_firestore package crashes it on IOS.

### ISSUE THREAD

**Issue by adeolaex** [flutter/flutter#68973] opened 2020-10-25 01:10 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the pubspecs.yaml to contain this two dependencies

```
firebase_core: ^0.5.0+1
cloud_firestore: "^0.14.1+3"
```
3. A minimal code example would be the Flutter Hello World program as I've tested and confirmed that it might not be a code-related issue

4. **Expected results:**

Both Hot Reload and Hot Restart should work correctly without any form of crashing.

**Actual results:** 

The app works fine up until a hot reload is performed. Hot restarts behaving normally. I don't even have to initialise Cloud Firestore, to get a crash. As long as it's present in my pubspecs.yaml file.

The traces probably from Xcode are:

  ```Restarted application in 1,264ms.
*** Assertion failure in void firebase::firestore::core::FirestoreClient::Initialize(const firebase::firestore::auth::User &, const firebase::firestore::api::Settings &)(), /Users/adeola/Documents/flutter/astroplug/ios/Pods/FirebaseFirestore/Firestore/core/src/core/firestore_client.cc:180
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Failed to open DB: Internal: Failed to open LevelDB database at /var/mobile/Containers/Data/Application/1BA6742A-2F5E-4F57-9838-B102939EF0C3/Library/Application Support/firestore/__FIRAPP_DEFAULT/astropluggroup/main: LevelDB error: IO error: lock /var/mobile/Containers/Data/Application/1BA6742A-2F5E-4F57-9838-B102939EF0C3/Library/Application Support/firestore/__FIRAPP_DEFAULT/astropluggroup/main/LOCK: already held by process (expected created.ok())'
*** First throw call stack:
(0x197a9c114 0x1ab2c2cb4 0x1979ab308 0x198cddca8 0x1004630ec 0x1004629c8 0x1005d10f0 0x1005d11a4 0x1004e098c 0x1004ebb74 0x1004ebb20 0x1004ebad4 0x1004ebaac 0x1004ea360 0x1003e22d4 0x1003df678 0x1003df638 0x1003e4b84 0x1003e4b44 0x1003e4af8 0x1003e4ad0 0x1003e34a8 0x1003e22d4 0x1003df678 0x100802fb8 0x100464110 0x1976d5280 0x19767dfa8 0x19767ea84 0x197688518 0x1dd3445a4 0x1dd347874)
libc++abi.dylib: terminating with uncaught exception of type NSException
Process 370 stopped
* thread #41, queue = 'com.google.firebase.firestore', stop reason = signal SIGABRT
    frame #0: 0x00000001c230495c libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1c230495c <+8>:  b.lo   0x1c2304978               ; <+36>
    0x1c2304960 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1c2304964 <+16>: mov    x29, sp
    0x1c2304968 <+20>: bl     0x1c22e21dc               ; cerror_nocancel
Target 0: (Runner) stopped.
```

```
[✓] Flutter (Channel unknown, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/adeola/Downloads/flutter
    • Framework revision 198df796aa (9 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/adeola/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone (mobile) • 7301a50cae9aaf2e903ef313e632bfed64bb3704 • ios • iOS
      14.0
```

</details>

**Comment by TahaTesser** [comment] 2020-10-26 08:55
Hi @adeolaex 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-26 08:55 UTC
