### ISSUE TITLE
Google Maps plugin unwanted padding on top

### ISSUE THREAD

**Issue by lucasfacchini** [flutter/flutter#28121] opened 2019-02-18 23:32 UTC
I'm having an issue with the Maps plugin, a top padding is being rendered if a Appbar is present.

This problem is only happening when running on my Xiaomi Mi 8 Lite (1080x2280) device. I've tested the same code in smaller devices (1080x1920) and the padding doesn't appear.
I also emulated a Pixel 2 XL (2880x1440) and there is no padding. So I suppose the problem is only happening with some specific screen configs.
## Code
```
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Appbar'),
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
            target: LatLng(0, 0),
            zoom: 15.0
        )
      ),
    );
}
```
If the Appbar is removed, the map fills the whole screen, and the padding isn't visible. (maybe it's hidden behind the status bar?)
Also if I replace the GoogleMap with a red Container, for example, the problem does't happen.

## Screen
![screenshot_2019-02-18-19-41-32-757_com pargio app](https://user-images.githubusercontent.com/4080698/52980905-3b66bb00-33bb-11e9-811b-e5791f14b223.png)

## Logs
```
[   +1 ms] executing: C:\Users\lucas\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.1.203:5555 forward tcp:0 tcp:40231
[  +13 ms] 55487
[        ] Forwarded host port 55487 to device port 40231 for Observatory
[   +4 ms] Connecting to service protocol: http://127.0.0.1:55487/
[ +266 ms] Successfully connected to service protocol: http://127.0.0.1:55487/
[   +2 ms] Sending to VM service: getVM({})
[   +8 ms] Result: {type: VM, name: vm, architectureBits: 64, targetCPU: arm64, hostCPU: Qualcomm Technologies, Inc SDM660, version: 2.1.0-dev.9.4.flutter-f9ebf21297 (Thu Nov 8 23:00:07 2018 +0100) on "android_arm64",
_profilerMode: VM, _nativeZoneMemoryUsage: 0, pi...
[   +4 ms] Sending to VM service: getIsolate({isolateId: isolates/871335551})
[   +2 ms] Sending to VM service: _flutter.listViews({})
[  +10 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7d65325798, isolate: {type: @Isolate, fixedId: true, id: isolates/871335551, name: main.dart$main-871335551, number: 871335551}}]}
[   +4 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: project-flutter})
[  +33 ms] Result: {type: Isolate, fixedId: true, id: isolates/871335551, name: main.dart:main(), number: 871335551, _originNumber: 871335551, startTime: 1550531054921, _heaps: {new: {type: HeapSpace, name: new, vmName:
Scavenger, collections: 2, avgCollectionPeriod...
[  +11 ms] Result: {type: FileSystem, name: project-flutter, uri: file:///data/user/0/com.project.app/cache/project-flutterMFCOYE/project-flutter/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/com.project.app/cache/project-flutterMFCOYE/project-flutter/)
[   +1 ms] Updating assets
[  +96 ms] Syncing files to device MI 8 Lite...
[   +2 ms] DevFS: Starting sync from LocalDirectory: 'C:\Users\lucas\git\project-flutter'
[        ] Scanning project files
[   +5 ms] Scanning package files
[  +63 ms] Scanning asset files
[        ] Scanning for deleted files
[  +38 ms] Compiling dart to kernel with 663 updated files
[   +5 ms] C:\flutter\bin\cache\dart-sdk\bin\dart C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental
--strong --target=flutter --output-dill build\app.dill --packages C:\Users\lucas\git\project-flutter\.packages --filesystem-scheme org-dartlang-root
[ +398 ms] W/ResourceType(11867): No package identifier when getting name for resource number 0x00000000
[  +17 ms] I/zzbz    (11867): Making Creator dynamically
[  +20 ms] W/zygote64(11867): Unsupported class loader
[   +6 ms] W/zygote64(11867): Skipping duplicate class check due to unsupported classloader
[        ] I/DynamiteModule(11867): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221
[        ] I/DynamiteModule(11867): Selected remote version of com.google.android.gms.maps_dynamite, version >= 221
[        ] V/DynamiteModule(11867): Dynamite loader version >= 2, using loadModule2NoCrashUtils
[   +4 ms] W/ResourceType(11867): No package identifier when getting name for resource number 0x00000000
[  +19 ms] W/zygote64(11867): Unsupported class loader
[  +56 ms] W/ResourceType(11867): No package identifier when getting name for resource number 0x00000000
[  +40 ms] I/Google Maps Android API(11867): Google Play services client version: 12451000
[  +12 ms] I/Google Maps Android API(11867): Google Play services package version: 15090021
[ +416 ms] I/zygote64(11867): Do partial code cache collection, code=61KB, data=41KB
[        ] I/zygote64(11867): After code cache collection, code=61KB, data=41KB
[        ] I/zygote64(11867): Increasing code cache capacity to 256KB
[  +99 ms] D/NetworkSecurityConfig(11867): No Network Security Config specified, using platform default
[  +72 ms] E/GoogleMapController(11867): Cannot enable MyLocation layer as location permissions are not granted
[  +74 ms] Updating files
[ +246 ms] DevFS: Sync finished
[        ] Syncing files to device MI 8 Lite... (completed)
[   +1 ms] Synced 0.8MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[  +16 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7d65325798, isolate: {type: @Isolate, fixedId: true, id: isolates/871335551, name: main.dart$main-871335551, number: 871335551}}]}
[        ] Connected to _flutterView/0x7d65325798.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on MI 8 Lite is available at: http://127.0.0.1:55487/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[ +121 ms] I/zygote64(11867): Do full code cache collection, code=114KB, data=88KB
[   +1 ms] I/zygote64(11867): After code cache collection, code=97KB, data=62KB
[ +123 ms] I/zygote64(11867): Do partial code cache collection, code=109KB, data=73KB
[   +1 ms] I/zygote64(11867): After code cache collection, code=109KB, data=74KB
[        ] I/zygote64(11867): Increasing code cache capacity to 512KB
[ +305 ms] I/zygote64(11867): Compiler allocated 4MB to compile void com.google.maps.api.android.lib6.gmm6.vector.bx.b(javax.microedition.khronos.opengles.GL10)
[+1129 ms] W/DynamiteModule(11867): Local module descriptor class for com.google.android.gms.googlecertificates not found.
[        ] I/DynamiteModule(11867): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
[        ] I/DynamiteModule(11867): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
[   +6 ms] W/zygote64(11867): Unsupported class loader
[  +19 ms] W/ResourceType(11867): No package identifier when getting name for resource number 0x00000000
[ +239 ms] W/zygote64(11867): Verification of void q.c() took 209.575ms
[+7826 ms] W/ResourceType(11867): No package identifier when getting name for resource number 0x00000000
[        ] I/Google Maps Android API(11867): Google Play services package version: 15090021
[ +144 ms] E/GoogleMapController(11867): Cannot enable MyLocation layer as location permissions are not granted
[ +180 ms] I/zygote64(11867): Do full code cache collection, code=250KB, data=167KB
[        ] I/zygote64(11867): After code cache collection, code=248KB, data=140KB
[ +148 ms] I/zygote64(11867): Do partial code cache collection, code=251KB, data=156KB
[        ] I/zygote64(11867): After code cache collection, code=251KB, data=156KB
[        ] I/zygote64(11867): Increasing code cache capacity to 1024KB
```

## Flutter doctor
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\lucas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • MI 8 Lite • 192.168.1.203:5555 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

**Comment by zoechi** [comment] 2019-02-19 07:01
Duplicate of #28120

**Closed by zoechi** 2019-02-19 07:01 UTC
