### ISSUE TITLE
Assets Not Loading on Real Device But Loading on the Web

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#78165] opened 2021-03-14 18:36 UTC
I have an issue with my Flutter application. I am trying to load a simple image on my SplashWidget as below. 

When I do `flutter run -d chrome` the image loads perfectly fine on the Web (Google Chrome).

Now when I test against my real Android Device(Huawei EVA LO9) running on Marshmallow (Android 6.0) I am getting the below error:

                        ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE
    ╞════════════════════════════════════════════════════
                        The following assertion was thrown resolving an image codec:
                        Unable to load asset: images/splash_icon.png
                        
                        When the exception was thrown, this was the stack:
                        #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
                        <asynchronous suspension>
                        #1      AssetBundleImageProvider._loadAsync
    (package:flutter/src/painting/image_provider.dart:667:14)
                        <asynchronous suspension>
                        ...
                        
                        Image provider: AssetImage(bundle: null, name: "images/splash_icon.png")
                        Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#d1d58(), name:
                          "images/splash_icon.png", scale: 1.0)

Here is my SplashWiget

    import 'package:flutter/material.dart';
    import 'package:flutter/widgets.dart';
    
    class SplashWidget extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return Container(
          width: double.infinity,
          height: double.infinity,
          decoration: BoxDecoration(color: BrandColors.PRIMARY_COLOR),
          child: Center(
            child: Image(
              image: AssetImage("images/splash_icon.png"),
            ),
          ),
        );
      }
    }

Here is my pubspec.yaml

    flutter:
      uses-material-design: true
      assets:
        - assets/

Here is a screenshot of my directory structure
<br/>
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/ujRJX.png

Do I need to do any android specific configurations to get this image to load on a real android device. I can't believe I have wasted hours on a simple thing like this. This is exhausting.

Someone please help me.

**Comment by iapicca** [comment] 2021-03-14 19:37
@hashweather 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, please provide your `flutter doctor -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment] 2021-03-15 11:10
@hashweather 
Your question is better suited for support channels like StackOverflow.  Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter but looks like code implementation issue. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-03-15 11:10 UTC
Labels: in triage
