### ISSUE TITLE
Use of TickerMode wrapped with TabBarView prevent animation

### ISSUE THREAD

**Issue by RuneAlexanderTrachsel** [flutter/flutter#64153] opened 2020-08-19 14:58 UTC
This is my first bug report, please say if im missing something.

After upgrading to flutter version 1.20.2 I experienced this problem.

With Flutter version 1.17.5, it works fine.

When having 2 pages wrapped with TabBarView, and each page wrapped with TickerMode. The second page is not enabled when changing to that page. First after setstate has been recalled on that page, it will work.

Because the second page is never enabled, the animations are never starting.

I have recreated the problem as simpel as I could in this project:
https://github.com/RuneAlexanderLarsen/Flutter-Ticker-TabBarView-Bug

Code snippet:
```
return TabBarView(
  controller: _tabController,
  children: [
    TickerMode(
      child: DemoPage(),
      enabled: selectedTabIndex == 0,
    ),
    TickerMode(
      child: DemoPage2(),
      enabled: selectedTabIndex == 1,
    ),
  ],
);
```

![Screen Recording 2020-08-19 at 16 18 15](https://user-images.githubusercontent.com/22022025/90651265-1d427b00-e23d-11ea-89b3-f01414adfe15.gif)

**Comment by TahaTesser** [comment] 2020-08-19 15:33
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  int selectedTabIndex = 0;
  TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: 2);
    // _tabController.addListener(() {
    //   setState(() {
    //     selectedTabIndex = _tabController.index;
    //   });
    // });
  }

  Widget _buildTabPages() {
    return TabBarView(
      controller: _tabController,
      children: [
        TickerMode(
          child: DemoPage(),
          enabled: selectedTabIndex == 0,
        ),
        TickerMode(
          child: DemoPage2(),
          enabled: selectedTabIndex == 1,
        ),
      ],
    );
  }

  // Widget _buildTabPages() {
  //   return IndexedStack(
  //     index: selectedTabIndex,
  //     children: [
  //       TickerMode(
  //         child: DemoPage(),
  //         enabled: selectedTabIndex == 0,
  //       ),
  //       TickerMode(
  //         child: DemoPage2(),
  //         enabled: selectedTabIndex == 1,
  //       ),
  //     ],
  //   );
  // }

  // @override
  // void didChangeDependencies() {
  //   super.didChangeDependencies();
  //   _tabController.addListener(() {
  //     setState(() {
  //       selectedTabIndex = _tabController.index;
  //     });
  //   });
  // }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        child: Stack(
          children: [
            _buildTabPages(),
            FloatingActionButton(child: Text('Change Page'), onPressed: change),
          ],
        ),
      ),
    );
  }

  void change() {
    int newValue;
    if (selectedTabIndex == 1) {
      newValue = 0;
    } else {
      newValue = 1;
    }

    setState(() {
      selectedTabIndex = newValue;
    });

    _tabController.animateTo(selectedTabIndex);
  }
}

class DemoPage extends StatelessWidget {
  // DemoPage() : super(key: Key('1'));

  @override
  Widget build(BuildContext context) {
    return Row(children: [
      Text('Page 1:'),
      CircularProgressIndicator(
        valueColor: AlwaysStoppedAnimation(Colors.red),
      ),
    ]);
  }
}

class DemoPage2 extends StatelessWidget {
  // DemoPage2() : super(key: Key('2'));

  @override
  Widget build(BuildContext context) {
    return Row(children: [
      Text('Page 2:'),
      CircularProgressIndicator(
        valueColor: AlwaysStoppedAnimation(Colors.red),
      ),
    ]);
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (6 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS
      13.6
    • iPhone 11 (mobile)     • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2022-11-01 11:21
Verified this on latest master version and the issue is not replicable anymore.


https://user-images.githubusercontent.com/67046386/199221992-232bec0a-cd70-45bf-9047-c673ad6c3aff.mov

<details>
<summary> master flutter doctor -v </summary>

```


[!] Flutter (Channel master, 3.5.0-12.0.pre.45, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.5.0-12.0.pre.45 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c2edb20f3d (53 minutes ago), 2022-10-31 21:18:37 -0700
    • Engine revision f721db653d
    • Dart version 2.19.0 (build 2.19.0-356.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Closing this as fixed.

**Closed by darshankawar** 2022-11-01 11:21 UTC
Labels: severe: regression, framework, a: animation, f: material design, f: scrolling, has reproducible steps, found in release: 1.20
