### ISSUE TITLE
[web] Picture.toImage throws an error on flutter web

### ISSUE THREAD

**Issue by dvdlg** [flutter/flutter#80231] opened 2021-04-11 19:50 UTC
I have been using this solution to generate my own BitmapDescriptor from an icon: https://gist.github.com/jbxbergdev/5238bb78b03a2a4e6f24e55f442d2b70

It worked perfectly until it suddenly stopped working a few days ago! And the strage thing is that I did not change anything! I did not change flutter version or anything like that.

It fails only in web, it works fine on android and ios. It fails on the line
```final image = await picture.toImage(_markerSize.round(), _markerSize.round());```
and the error looks exactly like:
https://github.com/flutter/flutter/issues/71848

I am using:
```
flutter --version
```
```
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (3 months ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)
```
which is newer than https://github.com/flutter/flutter/issues/66622#issuecomment-729979016 so it should work.

I tried:
1. revert to a commit that previously worked fine
2. ```flutter clean```
3. delete the build directory

but nothing helps.

```
flutter doctor -v
```
```
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.18363.1440], locale he-IL)
    • Flutter version 1.25.0-8.3.pre at C:\src\flutter-beta
    • Framework revision 5d36f2e7f5 (3 months ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Redmi Note 4 (mobile) • 1bf7ce869804 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)            • edge         • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```

In the console I don't see any indicative error other than ```[object Event]```
```
flutter run -d chrome -v
```
```
[  +79 ms] executing: [C:\src\flutter-beta/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +90 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[   +1 ms] executing: [C:\src\flutter-beta/] git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[ +107 ms] Exit code 0 from: git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[   +2 ms] 1.25.0-8.3.pre
[  +58 ms] executing: [C:\src\flutter-beta/] git rev-parse --abbrev-ref --symbolic @{u}
[  +71 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\src\flutter-beta/] git ls-remote --get-url origin
[  +56 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +111 ms] executing: [C:\src\flutter-beta/] git rev-parse --abbrev-ref HEAD
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +103 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +98 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +72 ms] List of devices attached
           1bf7ce869804           device product:mido model:Redmi_Note_4 device:mido transport_id:1
[  +12 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +132 ms] Skipping pub get: version match.
[  +38 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +15 ms] Found plugin google_maps_flutter at C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.2.0\
[   +6 ms] Found plugin google_maps_flutter_web at C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter_web-0.1.1\
[ +165 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[   +5 ms] Found plugin google_maps_flutter at C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.2.0\
[   +7 ms] Found plugin google_maps_flutter_web at C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter_web-0.1.1\
[  +72 ms] Generating C:\Users\USER\Desktop\Wingman\test_app\test_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +143 ms] This application is not configured to build on the web.
[   +1 ms] To add web support to a project, run `flutter create .`.
[   +3 ms] Launching lib\main.dart on Chrome in debug mode...
[ +163 ms] Updating assets
[ +114 ms] Waiting for connection from debug service on Chrome...
[  +15 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[   +4 ms] Found plugin google_maps_flutter at C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.2.0\
[   +2 ms] Found plugin google_maps_flutter_web at C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter_web-0.1.1\
[  +52 ms] Found plugin flutter_plugin_android_lifecycle at
C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[   +6 ms] Found plugin google_maps_flutter at C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-1.2.0\
[   +3 ms] Found plugin google_maps_flutter_web at C:\Users\USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter_web-0.1.1\
[ +126 ms] <- reset
[  +18 ms] C:\src\flutter-beta\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter-beta\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter-beta\bin\cache\flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\USER\AppData\Local\Temp\flutter_tools.8a4feaa7\flutter_tool.98efb097\app.dill --libraries-spec
file:///C:/src/flutter-beta/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\USER\Desktop\Wingman\test_app\test_app\.dart_tool\package_config.json 
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\USER\AppData\Local\Temp\flutter_tools.8a4feaa7\flutter_tools.4b05c501 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform file:///C:/src/flutter-beta/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill      
--no-sound-null-safety
[  +17 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+23488 ms] Waiting for connection from debug service on Chrome... (completed in 23.7s)
[   +4 ms] Synced 32.0MB.
[  +47 ms] <- accept
[  +39 ms] Caching compiled dill
[ +733 ms] Using פתיחה בסשן קיים של הדפדפן.

[+1184 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:59565/devtools/browser/99539232-f553-4668-b2f0-8ba3f693ed66
[+1900 ms] DwdsInjector: Received request for entrypoint at http://localhost:59536/main_module.bootstrap.js
[  +22 ms] MetadataProvider: Loading debug metadata...
[  +41 ms] MetadataProvider: Loaded debug metadata
[  +18 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:59536/main_module.bootstrap.js
[+7959 ms] DevHandler: Debug service listening on ws://127.0.0.1:59597/vce2M6vPsIc=/ws

[  +13 ms] Debug service listening on ws://127.0.0.1:59597/vce2M6vPsIc=/ws
[        ] Running with unsound null safety
[   +1 ms] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[   +1 ms] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms]   To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
[+1002 ms] [object Event]
```

**Comment by darshankawar** [comment] 2021-04-12 11:34
@dvdlg 
You are on older version of beta. Current is 2.1.0, so try to upgrade to latest and see if it helps.
If not, looking at the similar issue, does the documentation added helps to understand how the images are rendered on web ? https://github.com/flutter/website/pull/5061/files

**Comment by dvdlg** [comment] 2021-04-12 18:12
@darshankawar my project is too big for migration, Flutter 2.0.0 introduced so many issues that it just became impossible.
Having said that, https://github.com/flutter/flutter/issues/66622 shows that exactly the same code worked on Nov 18, which is earlier than Flutter 1.25.0-8.3.pre. The strange thing is that it did work for me too until a few days ago.

**Comment by darshankawar** [comment] 2021-04-13 06:37
@dvdlg 
Is that the complete reproducible code in the gist ? I am getting few compile errors while running it.
Can you update it to have so that we can simply copy paste and run to verify this issue ?
Thanks.

**Comment by dvdlg** [comment] 2021-04-13 18:23
@darshankawar 
You can copy paste this. I removed the part that depended on the google maps library because it was irrelevant.
thanks

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'dart:math';
import 'dart:typed_data';
import 'dart:ui' as ui;

class MarkerGenerator {
  final _markerSize;
  double _circleStrokeWidth;
  double _circleOffset;
  double _outlineCircleWidth;
  double _fillCircleWidth;
  double _iconSize;
  double _iconOffset;

  MarkerGenerator(this._markerSize) {
    // calculate marker dimensions
    _circleStrokeWidth = _markerSize / 10.0;
    _circleOffset = _markerSize / 2;
    _outlineCircleWidth = _circleOffset - (_circleStrokeWidth / 2);
    _fillCircleWidth = _markerSize / 2;
    final outlineCircleInnerWidth = _markerSize - (2 * _circleStrokeWidth);
    _iconSize = sqrt(pow(outlineCircleInnerWidth, 2) / 2);
    final rectDiagonal = sqrt(2 * pow(_markerSize, 2));
    final circleDistanceToCorners = (rectDiagonal - outlineCircleInnerWidth) / 2;
    _iconOffset = sqrt(pow(circleDistanceToCorners, 2) / 2);
  }

  /// Creates a BitmapDescriptor from an IconData
  Future<Uint8List> createBitmapDescriptorFromIconData(
      IconData iconData, Color iconColor, Color circleColor, Color backgroundColor) async {
    final pictureRecorder = ui.PictureRecorder();
    final canvas = Canvas(pictureRecorder);

    _paintCircleFill(canvas, backgroundColor);
    _paintCircleStroke(canvas, circleColor);
    _paintIcon(canvas, iconColor, iconData);

    final picture = pictureRecorder.endRecording();
    final image = await picture.toImage(_markerSize.round(), _markerSize.round());
    final bytes = await image.toByteData(format: ui.ImageByteFormat.png);
    return bytes.buffer.asUint8List();
  }

  /// Paints the icon background
  void _paintCircleFill(Canvas canvas, Color color) {
    final paint = Paint()
      ..style = PaintingStyle.fill
      ..color = color;
    canvas.drawCircle(Offset(_circleOffset, _circleOffset), _fillCircleWidth, paint);
  }

  /// Paints a circle around the icon
  void _paintCircleStroke(Canvas canvas, Color color) {
    final paint = Paint()
      ..style = PaintingStyle.stroke
      ..color = color
      ..strokeWidth = _circleStrokeWidth;
    canvas.drawCircle(Offset(_circleOffset, _circleOffset), _outlineCircleWidth, paint);
  }

  /// Paints the icon
  void _paintIcon(Canvas canvas, Color color, IconData iconData) {
    final textPainter = TextPainter(textDirection: TextDirection.ltr);
    textPainter.text = TextSpan(
        text: String.fromCharCode(iconData.codePoint),
        style: TextStyle(
          letterSpacing: 0.0,
          fontSize: _iconSize,
          fontFamily: iconData.fontFamily,
          color: color,
        ));
    textPainter.layout();
    textPainter.paint(canvas, Offset(_iconOffset, _iconOffset));
  }
}

void main() {
  runZonedGuarded(() {
    runApp(MyApp());
  }, (dynamic error, dynamic stack) {
    print(error);
    print(stack);
  });
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Uint8List im;

  @override
  void initState() {
    super.initState();
    MarkerGenerator(50)
        .createBitmapDescriptorFromIconData(
            Icons.access_alarm, Colors.blue, Colors.red, Colors.green)
        .then((value) => setState(() => im = value));
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Test'),
        ),
        body: Container(
          alignment: Alignment.center,
          child: im == null ? Text('Wait for it') : Image.memory(im),
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment] 2021-04-14 07:26
@dvdlg Thanks for the complete sample. I tried it on latest beta (2.1.0-12.2.pre) which didn't throw the error and loaded image properly I guess.

1. With canvaskit:

<img width="803" alt="Screenshot 2021-04-14 at 12 51 50 PM" src="https://user-images.githubusercontent.com/67046386/114670441-9dfc3d00-9d20-11eb-9bc1-e8dec4089ef6.png">


2. With html:

<img width="721" alt="Screenshot 2021-04-14 at 12 52 41 PM" src="https://user-images.githubusercontent.com/67046386/114670460-a3f21e00-9d20-11eb-80c8-42af97c252ff.png">

<details>
<summary> flutter doctor -v </summary>

```

[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-12.2.pre at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 5bedb7b1d5 (4 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.


```

</details>

**Comment by dvdlg** [comment] 2021-04-14 07:34
Thanks, @darshankawar, did you try it on Flutter 1.25.0-8.3.pre? It did work for me on that version of flutter a week ago, but then stopped working. I didn't try yet 2.1.0-12.2.pre, but when 2.0.0 was published I just couldn't migrate because of so many issues that arised.

**Comment by darshankawar** [comment] 2021-04-14 09:59
@dvdlg 
I couldn't go back to 1.25, but verified on `Channel beta, 1.26.0-17.6.pre`, on which too, it works as expected.

**Comment by dvdlg** [comment] 2021-04-14 13:06
Thank you @darshankawar, with your help I found the bug.
Because of https://github.com/flutter/flutter/issues/64904#issuecomment-714614807 I made all the TextStyle objects in my project to have ```wordSpacing: 0```. If you add ```wordSpacing: 0``` to the TextStyle object in the code above, the problem appears (at least on 1.25.0-8.3.pre, don't know about other releases).

**Comment by darshankawar** [comment] 2021-04-14 13:41
@dvdlg 
Thanks for identifying the root cause. That seemed to be a workaround / temporary fix per the comment, but per my verification, the issue isn't replicable on 1.26 and latest 2.1 beta versions and on latest stable (2.0.4).
I believe this issue is fixed and you get this error since you happen to be on 1.25. Upgrading to latest should resolve this, but you seem to have some limitations to upgrade. 
I am going ahead and closing this as not replicable on latest versions. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-04-14 13:41 UTC
Labels: in triage, waiting for customer response
