### ISSUE TITLE
Allow nested `WillPopScope` to handle back button at different levels and improve encapsulation.

### ISSUE THREAD

**Issue by larsbs** [flutter/flutter#47088] opened 2019-12-15 18:10 UTC
## Use case

I have an app with a `BottomNavigationBar` that has a top level `Navigator` to manage the different screens of the bottom bar and each of the screens have a nested `Navigator` to manage their own "user journey".

What I'm trying to achieve is basically that, if I'm in a route inside a screen, first, I will pop all the routes of that screen and when, I have no more routes to pop I will transfer control to the OS to manage the back button behavior. That would allow an user to click on a tab in the `BottomNavigationBar` and navigate over that tab, then, press the back button to go back to that tab root and if they pressed again, they would go back to the OS.

Right now, creating that kind of very common navigation it's complicated in flutter involving parent routes accessing the `Navigators` of children routes and all the logic and wiring having to be managed by the developer.

## Proposal

Be able to nest multiple `WillPopScope` and implement some kind of bubbling behavior like in web events, so the inner scopes will get to answer first to the back button and, if they just return `true` in `onWillPop`, the parent scope will take over and so recursively until the top of the app is reached.

This way we enforce separation of concerns and encapsulation as each `WillPopScope` and route will only take care of their direct descendants and their environment instead of having to pass keys all over the widget tree and parents managing children widgets states which IMO is a bad practice.

## Example

```dart
// parent.dart

// ... rest of the widget
WillPopScope(
  onWillPop: () async {
    // show dialog asking for confirmation
  },
  child: Navigator(
    onGenerateRoute: (RouteSettings settings) {
      switch (settings.name) {
        case '/':
          return MaterialPageRoute(builder: (BuildContext context) => MainRoute(), settings: settings);
        case '/another':
          return MaterialPageRoute(builder: (BuildContext context) => AnotherRoute(), settings: settings);
      },
  ),
),
// ... rest of the widget
```

```dart
// main_route.dart

// ... rest of the widget
WillPopScope(
  onWillPop: () async {
    // check if navigator can pop, otherwise return true and let parent WillPopScope handle it
  },
  child: Navigator(
    onGenerateRoute: (RouteSettings settings) {
      // generate children routes
    },
  ),
),
// ... rest of the widget
```

**Comment by nateshmbhat** [comment] 2020-03-05 05:42
we really need this feature , especially when trying to handle the backpresses in any custom libraries and if user wants to add his own behaviour on top of it , once the library returns false....

**Comment by AmirJaber97** [comment] 2020-04-02 13:45
anyway we could handle this right now? 
atm i'm doing this,
`return WillPopScope(
      onWillPop: () async {
        return !await navigatorKeys[_currentIndex].currentState.maybePop();
      },
      child: Scaffold()
);`
But the problem is, i can't check if i finished popping these navigators and then show a confirmation for exit dialog at the root navigator.
any help with this would be appreciated.

**Comment by Xgamefactory** [comment] 2020-05-14 20:03
same here.  navigatorKeys[_currentIndex].currentState.canPop(); also returns true even if it is on last route. 

```
return WillPopScope(
        child: _buildBody(),
        onWillPop: () {
          // return navKey.currentState.maybePop();
          if (navKey.currentState.canPop()) {
            navKey.currentState.maybePop();
            return Future(() => false);
          }
...........
Widget _buildBody() {
    return Navigator(
      key: navKey,
      initialRoute: FormPageImage.routeName,
      onGenerateRoute: (RouteSettings settings) {
```

**Comment by EzeBera** [comment] 2020-05-23 18:28
I'm really needing this

**Comment by omidraha** [comment] 2020-08-09 11:44
It is really necessary when the child wants to do things like `modal pop` separately from the parent.
Is there a solution now?

**Comment by Ossyyrr** [comment] 2020-10-08 16:53
I'm really needing this

**Comment by svenjacobs** [comment] 2020-10-12 12:37
This would be really appreciated. Also it should work with multiple nested `Navigators`. For instance:

```
WillPopScope (1)       <-- Handles back button of first navigator
  Navigator (1)
    WillPopScope (2)   <-- Handles back button of second navigator
      Navigator (2)
```

**Comment by FernandoUFS** [comment] 2020-11-20 01:58
I am really needing this. I created a custom Dropdown that uses OverlayEntry to show itself, that dropdown has a WillPopScope, when the user taps back button I capture and close the OverlayEntry returning false to WillPopScope, this is working fine. But I also added an exit confirmation dialog at application top level, the dialog must be shown when the user taps the back button. Booth functionalities are working fine individually but together are not, the OverlayEntry must be closed before, what is not happening, they are trigged together.

**Comment by schultek** [comment] 2020-12-14 03:38
I came across this issue when dealing with the same problem. Since there was no solution i wrote my own NestedWillPopScope widget, so here you go: https://gist.github.com/schultek/cc2acd8014be255c2a639a98d47be4e0

This should work out of the box with just replacing all your WillPopScope widgets with NestedWillPopScope widgets, in line with the original proposal.

**Comment by davidmartos96** [comment] 2020-12-14 14:51
@schultek Thanks for sharing! It looks very similar to the current `WillPopScope` widget implementation. Have you found any limitation that would prevent it to being merged into Flutter? If not, you could consider making a PR.

**Comment by chunhtai** [comment] 2020-12-30 21:51
You can now uses Router and RootBackButtonDispatcher and ChildBackButtonDispatcher to do so, I will close this issue since there is no plan to change the current willpopscope

**Closed by chunhtai** 2020-12-30 21:51 UTC
Labels: customer: crowd, f: routes, framework, proposal, severe: new feature

**Comment by douglasiacovelli** [comment] 2021-01-22 15:04
If anyone happens to have a similar issue, I've created a solution with childBackButtonDispatcher here: https://github.com/flutter/flutter/issues/74437#issuecomment-765462854

**Comment by theochampion** [comment] 2021-04-13 20:32
Any updates on this ?

**Comment by trongrikai** [comment] 2021-06-08 06:27
Any update?
