### ISSUE TITLE
Benchmark tasks can be flaky when gradle downloads are throttled

### ISSUE THREAD

**Issue by flar** [flutter/flutter#142637] opened 2024-01-31 20:18 UTC
We occasionally see flaky failures downloading gradle to run the benchmarks in the framework post-submit tasks. Generally the tasks will be downloading the same versions so a local cache would both decrease the flakiness and reduce the download pressure on the gradle servers.

A recent example: https://github.com/flutter/flutter/issues/142605

Usually gradle versions are stored in $USER_HOME/.gradle/caches/<VERSION_NUMBER>/

**Comment by flar** [comment] 2024-02-01 19:56
Meanwhile, should we close the PRs associated with those "flaky" Issues?

**Comment by keyonghan** [comment] 2024-02-01 19:57
Routing to android team for further triage, but feel free to loop back if anything else is needed from infra.

**Comment by keyonghan** [comment] 2024-02-01 19:57
> Meanwhile, should we close the PRs associated with those "flaky" Issues?

Yes! Closing.

**Comment by zanderso** [comment] 2024-02-07 17:26
@keyonghan Since the CIPD package automation process involves making recipe changes, I don't think this is a self-service area of our infrastructure. I think the next steps here are for `team-android` to identify the upstream download URLs for each of the desired `gradle` versions for each platform where they're needed, and then for `team-infra` to add the automation to cocoon, and modify the recipes to populate the cache directory that @flar identified above.

Leaving this marked as `team-android` only to do the first step I outlined above.

**Comment by gmackall** [comment] 2024-02-07 17:37
The Gradle urls we use are 
http://services.gradle.org/distributions/gradle-7.6.3-all.zip
http://services.gradle.org/distributions/gradle-8.2.1-all.zip
http://services.gradle.org/distributions/gradle-8.0.2-bin.zip
http://services.gradle.org/distributions/gradle-7.4-all.zip
http://services.gradle.org/distributions/gradle-8.0-all.zip

Once lands https://github.com/flutter/flutter/pull/142000, we will also use
https\://services.gradle.org/distributions/gradle-7.0-all.zip (its a test for using an old gradle version).

Extra note that 7.6.3 is primary one in use.

**Comment by zanderso** [comment] 2024-02-07 17:44
Thanks, @gmackall! Shifting to `team-infra`.

**Comment by godofredoc** [comment] 2024-02-07 18:29
Using CIPD to work around the root cause rather than fixing it will add a lot of complexity and maintenance burden in a place far away (recipes) from where the issue is happening (test).

Couple of things we may want to try:

* 1) Create a copy of the gradle binaries in GCS and download from there.
* 2) If gradle itself is being cached using $USER_HOME/.gradle/caches/<VERSION_NUMBER>/ then it should be already cached https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/flutter_deps/api.py;l=389. Are those the correct configurations for the different versions of gradle? is there a way to validate if the tests are hitting the cache or not?
* 3) Create a local mirror of flutter tests gradle dependencies (may be overkilling but preferable over the cipd option).

Implementing/validating any of the three options require collaboration between infra and the gradle experts. Please let us know who should infra work with.

Also flakes, unless they are totally blocking the tree, do not qualify as P0. Can you please provide more details on why this should be a P0?

**Comment by zanderso** [comment] 2024-02-07 18:51
> Also flakes, unless they are totally blocking the tree, do not qualify as P0. Can you please provide more details on why this should be a P0?

The flake bot files flake issues as P0.

**Comment by keyonghan** [comment] 2024-02-13 22:57
With a recent change to populate named cache of `gradle`, seems the cache is working:

- An earlier [failed build](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8757400754889463089/+/u/run_gradient_static_perf__e2e_summary/test_stdout) (without appropriate cache): It kept downloading gradle on the fly
- A recent [successful build](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8756175867681414353/+/u/run_gradient_static_perf__e2e_summary/stdout): no downloading at all (with warm cache).

Will keep monitoring to see if the issue is fixed.

**Comment by zanderso** [comment] 2024-02-13 23:26
@keyonghan Could you link to the "recent change" you mention?

**Comment by goderbauer** [comment] 2024-02-13 23:35
During critical triage I assigned this to @keyonghan since you seem to be working on or monitoring this. Please re-assign if this wasn't correct.

**Comment by keyonghan** [comment] 2024-02-13 23:54
> @keyonghan Could you link to the "recent change" you mention?

https://flutter-review.googlesource.com/c/infra/+/54931

**Comment by zanderso** [comment] 2024-02-14 03:09
@keyonghan @godofredoc I have a couple of questions:

1. In general, in what situations is the solution in https://flutter-review.googlesource.com/c/infra/+/54931 applicable? Is there some way to know that that is the mechanism that should be requested for similar dependencies in the future? That is, how does this approach scale past this one instance of one dependency?

2. With this approach, will all the bots still hit the network if/when the swarming caches are cleared?

**Comment by keyonghan** [comment] 2024-02-14 17:30
> @keyonghan @godofredoc I have a couple of questions:
> 
> 1. In general, in what situations is the solution in https://flutter-review.googlesource.com/c/infra/+/54931 applicable? Is there some way to know that that is the mechanism that should be requested for similar dependencies in the future? That is, how does this approach scale past this one instance of one dependency?

This is for customized cache locations, like xcode, engine builder, etc. For most dependencies, we do not need to worry about the named cache population as it will be auto populated and become visible via ENV.

> 2. With this approach, will all the bots still hit the network if/when the swarming caches are cleared? If so, how often does that happen? Could we still potentially get rate limited?

We have 150 VMs in prod pool, and they get re-provisioned daily. Worst case, all these 150 VMs get cleaned up around the same time, and it depends on how many gradle tests are pulling the binaries around the same time. I take it as a low chance we will hit the limit. But we still need to monitor.

A latest data point: we didn't get any flake bug related to gradle download based on today's flake bot.

**Comment by keyonghan** [comment] 2024-02-15 19:08
With the named cache, issue has been mitigated. Will monitor for another cycle, and close if no further flakes.

**Comment by godofredoc** [comment] 2024-02-15 23:22
Listing gradle caches to simplify future debugging: https://flutter-review.googlesource.com/c/recipes/+/55223

**Comment by keyonghan** [comment] 2024-02-22 19:04
Checked a couple of earlier flaky targets, and there doesn't seem a single flake. Please reopen if you see this repros.

**Closed by keyonghan** 2024-02-22 19:04 UTC
Labels: team-infra, P0, fyi-android, triaged-infra
