### ISSUE TITLE
Efficient Image Loading in infinite ListView

### ISSUE THREAD

**Issue by vipulasri** [flutter/flutter#17835] opened 2018-05-23 11:30 UTC
I am having an issue with loading images from the network to the infinite `ListView`. My app crashes without giving an error after loading some images. 
I think there's an issue with image retaining in memory and causing the app to bloat. How to solve this kind of issues in Flutter?

**Comment by vipulasri** [comment] 2018-05-26 02:45
I have two `tabs` both of them loads data/images in infinite `StaggeredList` and each Staggered List is made on basis of height and width of image(maintaining aspect ratio). 

As I scroll through the lot of images and load images in both of the tabs, app tends crash after sometime(may be due to loading lot of images).

`Flutter doctor`:

    [✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale en)
    • Flutter version 0.3.2 at /Users/Vipul/flutter
    • Framework revision 44b7e7d3f4 (5 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

    [!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Vipul/Library/Android/sdk
    • Android NDK at /Users/Vipul/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

    [!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

    [✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b02)

    [✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

    [✓] Connected devices (1 available)
    • Moto G 4 • ZY223GZZ9P • android-arm • Android 7.0 (API 24)

    ! Doctor found issues in 2 categories.

**Comment by jonahwilliams** [comment] 2018-05-26 04:36
It's hard to say exactly what the problem is, possibly image related.  There are a few things you can try to get more information here.

#### Get more information on your crash
If the issue is Image related you should be able to reproduce it locally. `flutter run` and separately use `adb logcat`.  Then when the crash happens see what information is logged.

#### Check the number of cached images
In the Dart observatory, you can see the number of images which have been cached in the "see persistent handles" in the bottom right corner.  This will display a table with different kinds of objects and their total size. To go to the observatory, open the address in a web browser which is logged when you or your IDE call` flutter run`.

    🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
    An Observatory debugger and profiler on iPhone 8 Plus is available at: http://127.0.0.1:8100/
                                                                           ^^^^^^^^^^^^^^^^^^^^^

**Comment by vipulasri** [comment] 2018-05-26 05:11
@jonahwilliams @zoechi Thanks for the input 👍 The Observatory thing I knew but wasn't able to figure out how to use :( 
"persistent handles" option did work out for me, as I was able to see the size of images being loaded into the memory, which was quite large. So, I am now loading smaller images :) 
Thanks a ton :) 

Still, I want to know, How to efficiently load images If suppose I am loading a 1000 images. How to clear previous ones. Keep the memory in check. Is there something, In Android, we use [Glide](https://github.com/bumptech/glide) a super awesome library which automatically handles all these scenarios.

**Comment by jonahwilliams** [comment] 2018-05-26 05:47
@vipulasri checkout https://github.com/flutter/flutter/pull/17614 - I am working on a design that would allow easier customization of image loading & caching.  With this change, you could customize your application to evict images from the cache once they were scrolled a certain distance offscreen

**Comment by zoechi** [comment] 2018-08-03 15:31
Is there still something missing or can this issue be closed?

**Comment by zoechi** [comment] 2018-09-01 10:59
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-09-01 10:59 UTC
