### ISSUE TITLE
Recommended edit/debug cycle for iOS?

### ISSUE THREAD

**Issue by davenotik** [flutter/flutter#1879] opened 2016-02-14 19:37 UTC
Do I `flutter start` every time I make a change, waiting for the app to compile each time, or is there something better? (I'm running on device atm, not Simulator.) It looks like there is live reloading and more for Android at least.

**Comment by Hixie** [comment] 2016-02-14 20:02
cc @chinmaygarde

**Comment by abarth** [comment] 2016-02-14 20:22
@davenotik The iteration cycle should be better on the simulator.  We're still experimenting with different ways of improving the iteration cycle on the device for iOS.  Currently that workflow isn't as fast as we'd like.

**Comment by abarth** [comment] 2016-02-14 20:24
This issue is a duplicate of #790.  For now, I'd recommend iterating using the simulator, but that's obviously not ideal.  Thanks for the report.

**Closed by abarth** 2016-02-14 20:24 UTC
Labels: affects: dev experience, affects: tools, ⌺‬ platform-ios, ⚠ astounding performance
