### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by MonaMouawadDafagate** [flutter/flutter#160782] opened 2024-12-23 11:08 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008110-000C14AC267B801E --start-paused --flavor=dev --dart-define=flutter.inspector.structuredErrors=true lib/main_dev.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:236:36)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:189:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:452:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:614:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale en-EG)
    • Flutter version 3.27.1 on channel stable at /Users/ahmedshalaby/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (7 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ahmedshalaby/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.96.1)
    • VS Code at /Users/ahmedshalaby/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.102.0

[✓] VS Code (version 1.90.2)
    • VS Code at /Users/ahmedshalaby/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • Dafa iPhone 13 pro (mobile)     • 00008110-001A64100EEA401E • ios            • iOS 17.6.1 21G93
    • Dafa’s Iphone 1  (mobile)       • 00008110-000C14AC267B801E • ios            • iOS 18.2 22C152
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.205
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for I KOBTAN. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.2+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bae5e49bc2a867403c43b2aae2de8f8c33b037e4
### Plugins
audio_waveforms-1.1.1
ffmpeg_kit_flutter_audio-6.0.3
file_picker-8.1.3
file_selector_linux-0.9.3
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
flutter_downloader-1.11.8
flutter_native_splash-2.4.1
flutter_plugin_android_lifecycle-2.0.22
flutter_sim_country_code-0.1.2
flutter_sound-9.16.3
flutter_sound_web-9.16.3
hyperpay_plugin-3.0.0
image_picker-1.1.2
image_picker_android-0.8.12+12
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-8.1.0
path_provider-2.1.5
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.3.3+1
video_player-2.9.2
video_player_android-2.7.1
video_player_avfoundation-2.6.2
video_player_web-2.3.3
video_thumbnail-0.5.3
wakelock_plus-1.2.8
webview_flutter-4.8.0
webview_flutter_android-3.16.8
webview_flutter_wkwebview-3.14.0

**Comment by danagbemava-nc** [comment] 2024-12-30 07:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-12-30 07:32 UTC
Labels: in triage
