### ISSUE TITLE
[tool_crash] ProcessException: Process timed out: Command: xcrun, OS error code: -1

### ISSUE THREAD

**Issue by didierganthier** [flutter/flutter#87379] opened 2021-07-30 22:26 UTC
## Command
```
flutter --no-color build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process timed out:
 Command: xcrun, OS error code: -1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:171:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:394:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:371:47)
<asynchronous suspension>
#3      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:244:37)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-HT)
    • Flutter version 2.0.4 at /Users/alpha/Downloads/flutter
    • Framework revision b1395592de (4 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alpha/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • SM J410G (mobile) • 84819658 • android-arm    • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 92.0.4515.107

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.4.0+43
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
add_2_calendar-1.4.0
apple_sign_in-0.1.0
cloud_firestore-0.14.4
cloud_firestore_web-0.2.1+2
esys_flutter_share-1.0.2
file_picker-2.1.7
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_dynamic_links-0.5.3
firebase_messaging-6.0.16
firebase_storage-5.2.0
firebase_storage_web-0.1.1+1
flutter_facebook_login-3.0.0
flutter_keyboard_visibility-3.3.0
flutter_local_notifications-3.0.2
flutter_native_image-0.0.5+3
flutter_plugin_android_lifecycle-1.0.9
flutter_webview_plugin-0.3.11
fluttertoast-8.0.7
geolocator-5.3.2+2
google_api_availability-2.0.4
google_maps_flutter-1.2.0
google_sign_in-4.5.3
google_sign_in_web-0.9.2
image_picker-0.6.7+8
location-3.2.4
location_permissions-3.0.0+1
location_web-1.0.1
package_info-0.4.3+4
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+3
share-0.6.5+4
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.1+1
stripe_payment-1.1.4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+1
url_launcher_windows-0.0.1+3
video_player-0.11.1+5
video_player_web-0.1.4+1

**Comment by darshankawar** [comment] 2021-08-02 08:06
Closing this as duplicate of https://github.com/flutter/flutter/issues/47633

**Closed by darshankawar** 2021-08-02 08:06 UTC
Labels: in triage
