### ISSUE TITLE
Crashes in engine on Android 

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#38506] opened 2019-08-14 04:02 UTC
## Steps to Reproduce

Several crashes were recorded by Google Play Store.

It is unknown how to reproduce.

Number of crashes in the last 60 days:

- Android 9 	3,127
- Android 8.0 	2,182
- Android 6.0 	388
- Android 8.1 	318	
- Android 7.0 	286
- Android 7.1 	85

## Logs

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> me.cartune.android <<<

backtrace:
  #00  pc 0000000000049e38  /system/lib/libc.so (tgkill+12)
  #01  pc 00000000000475b3  /system/lib/libc.so (pthread_kill+34)
  #02  pc 000000000001d7c9  /system/lib/libc.so (raise+10)
  #03  pc 00000000000192c1  /system/lib/libc.so (__libc_android_abort+34)
  #04  pc 0000000000017328  /system/lib/libc.so (abort+4)
  #05  pc 00000000001374df  /data/app/me.cartune.android-1/lib/arm/libflutter.so
  #06  pc 000000000012ccbb  /data/app/me.cartune.android-1/lib/arm/libflutter.so
  #07  pc 000000000015ec51  /data/app/me.cartune.android-1/lib/arm/libflutter.so
  #08  pc 0000000000137b09  /data/app/me.cartune.android-1/lib/arm/libflutter.so
  #09  pc 000000000013a401  /data/app/me.cartune.android-1/lib/arm/libflutter.so
  #10  pc 0000000000011fc7  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+610)
  #11  pc 0000000000011cd7  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+26)
  #12  pc 000000000008fe51  /system/lib/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+22)
  #13  pc 0000000001c3aab5  /system/framework/arm/boot-framework.oat (android.os.MessageQueue.nativePollOnce+96)
  #14  pc 0000000001c3bfc1  /system/framework/arm/boot-framework.oat (android.os.MessageQueue.next+188)
  #15  pc 0000000001c37345  /system/framework/arm/boot-framework.oat (android.os.Looper.loop+448)
  #16  pc 000000000168d9ed  /system/framework/arm/boot-framework.oat (android.app.ActivityThread.main+424)
  #17  pc 00000000000a9041  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
  #18  pc 0000000000402559  /system/lib/libart.so (art_quick_invoke_static_stub+228)
  #19  pc 00000000000b02ff  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+178)
  #20  pc 0000000000312b99  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+56)
  #21  pc 0000000000313f2b  /system/lib/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_j+766)
  #22  pc 00000000002bb3b1  /system/lib/libart.so (_ZN3artL13Method_invokeEP7_JNIEnvP8_jobjectS3_S3_+40)
  #23  pc 0000000000604f39  /system/framework/arm/boot.oat (java.lang.reflect.Method.invoke+116)
  #24  pc 0000000002128131  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run+100)
  #25  pc 0000000002128faf  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1218)
  #26  pc 00000000000a9041  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
  #27  pc 0000000000402559  /system/lib/libart.so (art_quick_invoke_static_stub+228)
  #28  pc 00000000000b02ff  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+178)
  #29  pc 0000000000312b99  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+56)
  #30  pc 00000000003129ab  /system/lib/libart.so (_ZN3art17InvokeWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+266)
  #31  pc 0000000000275c93  /system/lib/libart.so (_ZN3art3JNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+426)
  #32  pc 00000000000652b1  /system/lib/libandroid_runtime.so
  #33  pc 0000000000066b83  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+498)
  #34  pc 0000000000001947  /system/bin/app_process32
  #35  pc 0000000000016d71  /system/lib/libc.so (__libc_init+48)
  #36  pc 0000000000001564  /system/bin/app_process32
```

symbols with https://console.cloud.google.com/storage/browser/_details/flutter_infra/flutter/fee001c93f25a1e7258e762781a7361f122d29f5/android-arm-release/symbols.zip

```
Stack frame #05  pc 00000000001374df  /data/app/me.cartune.android-1/lib/arm/libflutter.so: Routine ~LogMessage at /b/s/w/ir/k/src/out/android_release/../../flutter/fml/logging.cc:92
Stack frame #06  pc 000000000012ccbb  /data/app/me.cartune.android-1/lib/arm/libflutter.so: Routine BFD: Dwarf Error: mangled line number section (bad file number).
flutter::PlatformViewAndroid::UpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) at /b/s/w/ir/k/src/out/android_release/../../flutter/shell/platform/android/platform_view_android_jni.cc:96
Stack frame #07  pc 000000000015ec51  /data/app/me.cartune.android-1/lib/arm/libflutter.so: Routine operator() at /b/s/w/ir/k/src/out/android_release/../../flutter/shell/common/shell.cc:813
Stack frame #08  pc 0000000000137b09  /data/app/me.cartune.android-1/lib/arm/libflutter.so: Routine fml::MessageLoopImpl::FlushTasks(fml::FlushType) at /b/s/w/ir/k/src/out/android_release/../../flutter/fml/message_loop_impl.cc:138
Stack frame #09  pc 000000000013a401  /data/app/me.cartune.android-1/lib/arm/libflutter.so: Routine fml::MessageLoopAndroid::OnEventFired() at /b/s/w/ir/k/src/out/android_release/../../flutter/fml/platform/android/message_loop_android.cc:92
```

flutter doctor -v

```
[✓] Flutter (Channel v1.7.8-hotfixes, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale ja-JP)
    • Flutter version 1.7.8+hotfix.4 at /Applications/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0
```

**Comment by najeira** [comment] 2019-08-14 04:03
similar #33205 #31139

**Comment by najeira** [comment] 2019-08-19 01:48
stacktrace on amr64

```
********** Crash dump: **********
pid: 0, tid: 0 >>> me.cartune.android <<<
Stack frame #00  pc 000000000002233c  /system/lib64/libc.so (abort+116)
Stack frame #01  pc 000000000026ded8  /data/app/me.cartune.android-igSvCeIqHGgM1k-fIBykVA==/lib/arm64/libflutter.so: Routine ~LogMessage at /b/s/w/ir/k/src/out/android_release_arm64/../../flutter/fml/logging.cc:92
Stack frame #02  pc 0000000000261a5c  /data/app/me.cartune.android-igSvCeIqHGgM1k-fIBykVA==/lib/arm64/libflutter.so: Routine BFD: Dwarf Error: mangled line number section (bad file number).
flutter::PlatformViewAndroid::UpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) at /b/s/w/ir/k/src/out/android_release_arm64/../../flutter/shell/platform/android/platform_view_android_jni.cc:96
Stack frame #03  pc 000000000029a100  /data/app/me.cartune.android-igSvCeIqHGgM1k-fIBykVA==/lib/arm64/libflutter.so: Routine operator() at /b/s/w/ir/k/src/out/android_release_arm64/../../flutter/shell/common/shell.cc:813
Stack frame #04  pc 000000000026e6ac  /data/app/me.cartune.android-igSvCeIqHGgM1k-fIBykVA==/lib/arm64/libflutter.so: Routine fml::MessageLoopImpl::FlushTasks(fml::FlushType) at /b/s/w/ir/k/src/out/android_release_arm64/../../flutter/fml/message_loop_impl.cc:138
Stack frame #05  pc 0000000000271b70  /data/app/me.cartune.android-igSvCeIqHGgM1k-fIBykVA==/lib/arm64/libflutter.so: Routine fml::MessageLoopAndroid::OnEventFired() at /b/s/w/ir/k/src/out/android_release_arm64/../../flutter/fml/platform/android/message_loop_android.cc:92
Stack frame #06  pc 0000000000014ff8  /system/lib64/libutils.so (android::Looper::pollInner(int)+836)
Stack frame #07  pc 0000000000014c18  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
Stack frame #08  pc 00000000001262d0  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
Stack frame #09  pc 00000000003e5fec  /system/framework/arm64/boot-framework.oat (android.media.MediaExtractor.seekTo [DEDUPED]+140)
Stack frame #10  pc 0000000000ab8544  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+244)
 ```

**Comment by keshava19** [comment] 2019-08-29 06:23
We are also facing the similar issue with some users.
```
pid: 0, tid: 0 >>> com.keka.xhr <<< backtrace:
#00 pc 000000000001cf76 /system/lib/libc.so (abort+58)
#01 pc 00000000001374df /data/app/com.keka.xhr-pikUK5cdQZb1Y5vjqevybw==/lib/arm/libflutter.so
#02 pc 000000000012ccbb /data/app/com.keka.xhr-pikUK5cdQZb1Y5vjqevybw==/lib/arm/libflutter.so
#03 pc 000000000015ec51 /data/app/com.keka.xhr-pikUK5cdQZb1Y5vjqevybw==/lib/arm/libflutter.so
#04 pc 0000000000137b09 /data/app/com.keka.xhr-pikUK5cdQZb1Y5vjqevybw==/lib/arm/libflutter.so
#05 pc 000000000013a401 /data/app/com.keka.xhr-pikUK5cdQZb1Y5vjqevybw==/lib/arm/libflutter.so
#06 pc 000000000000f2ef /system/lib/libutils.so (android::Looper::pollInner(int)+634)
#07 pc 000000000000eff3 /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+26)
#08 pc 00000000000bf41d /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+26)
#09 pc 000000000040bccd /system/framework/arm/boot-framework.oat (android.media.MediaExtractor.seekTo [DEDUPED]+92)
#10 pc 0000000000983c5d /system/framework/arm/boot-framework.oat (android.os.MessageQueue.next+204)
#11 pc 0000000000981a8d /system/framework/arm/boot-framework.oat (android.os.Looper.loop+548)
#12 pc 00000000007d8adb /system/framework/arm/boot-framework.oat (android.app.ActivityThread.main+690)
#13 pc 0000000000421575 /system/lib/libart.so (art_quick_invoke_stub_internal+68)
#14 pc 00000000003f9c4b /system/lib/libart.so (art_quick_invoke_static_stub+222)
#15 pc 00000000000a181f /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
#16 pc 0000000000358111 /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
#17 pc 0000000000359563 /system/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+962)
#18 pc 00000000003080a9 /system/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+40)
#19 pc 000000000011328f /system/framework/arm/boot.oat (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+110)
#20 pc 0000000000bda973 /system/framework/arm/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+114)
#21 pc 0000000000be0511 /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2016)
#22 pc 0000000000421575 /system/lib/libart.so (art_quick_invoke_stub_internal+68)
#23 pc 00000000003f9c4b /system/lib/libart.so (art_quick_invoke_static_stub+222)
#24 pc 00000000000a181f /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
#25 pc 0000000000358111 /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
#26 pc 0000000000357f25 /system/lib/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+300)
#27 pc 00000000002992a1 /system/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+476)
#28 pc 000000000007126f /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+38)
#29 pc 000000000007371b /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+478)
#30 pc 0000000000002f25 /system/bin/app_process32 (main+728)
#31 pc 000000000008de0d /system/lib/libc.so (__libc_init+48)
#32 pc 0000000000002c0d /system/bin/app_process32 (_start_main+40)
#33 pc 0000000000000306 <anonymous>
```

**Comment by opensourcegps** [comment] 2019-08-30 09:51
I'm struggling with this bug for many months. No solution and not reproducible locally. Crashes in Google Console every day. One suggestion was to test the app with accessibility services enabled, but still can not reproduce it. All reports were closed and feels like dead end with this bug. Does not crash on iOS.

 ```

Today, 10:24 AM on app version 494
Motorola moto g(7) power (ocean), Android 9
Report 1 of 5
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.appname.app <<<

backtrace:
 
  #00  pc 0000000000021c64  /system/lib64/libc.so (abort+116)
 
  #01  pc 000000000026ded8  /data/app/com.appname.app-vrpR3r83_8Y_DVHWD00b-g==/lib/arm64/libflutter.so
 
  #02  pc 0000000000261a5c  /data/app/com.appname.app-vrpR3r83_8Y_DVHWD00b-g==/lib/arm64/libflutter.so
 
  #03  pc 000000000029a100  /data/app/com.appname.app-vrpR3r83_8Y_DVHWD00b-g==/lib/arm64/libflutter.so
 
  #04  pc 000000000026e6ac  /data/app/com.appname.app-vrpR3r83_8Y_DVHWD00b-g==/lib/arm64/libflutter.so
 
  #05  pc 0000000000271b70  /data/app/com.appname.app-vrpR3r83_8Y_DVHWD00b-g==/lib/arm64/libflutter.so
 
  #06  pc 00000000000141c0  /system/lib64/libutils.so (android::Looper::pollInner(int)+856)
 
  #07  pc 0000000000013dcc  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
 
  #08  pc 0000000000120960  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
 
  #09  pc 00000000003e200c  /system/framework/arm64/boot-framework.oat (android.media.MediaExtractor.seekTo [DEDUPED]+140)
 
  #10  pc 0000000000ab0630  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+240)
 
  #11  pc 0000000000aadfbc  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+636)
 
  #12  pc 000000000087c6bc  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+764)
 
  #13  pc 0000000000556c4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
 
  #14  pc 00000000000cf8e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
 
  #15  pc 000000000045e778  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
 
  #16  pc 00000000004601cc  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
 
  #17  pc 00000000003f010c  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
 
  #18  pc 000000000011e6d4  /system/framework/arm64/boot-core-oj.oat (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
 
  #19  pc 0000000000be5928  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
 
  #20  pc 0000000000beccd0  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3088)
 
  #21  pc 0000000000556c4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
 
  #22  pc 00000000000cf8e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
 
  #23  pc 000000000045e778  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
 
  #24  pc 000000000045e3d8  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
 
  #25  pc 0000000000362e38  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
 
  #26  pc 00000000000b246c  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120)
 
  #27  pc 00000000000b4df0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+756)
 
  #28  pc 000000000000220c  /system/bin/app_process64 (main+1200)
 
  #29  pc 00000000000acb44  /system/lib64/libc.so (__libc_init+88)
```
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/flutter/flutter_linux_v1.7.8-hotfix.4-stable
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
```

**Comment by opensourcegps** [comment] 2019-10-03 10:10
Just to update, https://github.com/flutter/flutter/issues/33205 disappeared after switching to 1.9.1+hotfix.2. Might help here too. Thanks Flutter team!

**Comment by searchy2** [comment] 2019-11-01 14:56
I was able to reproduce this crash by turning TalkBack on and then showing/hiding a FlutterView. Thanks to https://github.com/flutter/flutter/issues/43829 we will see a fix soon!

**Comment by searchy2** [comment] 2019-11-15 15:48
After investigating for a day, I've managed to solve this issue by not updating and Embeded Flutter View when the view is removed. This crash occurred for me because I was updating a Flutter View through a method channel after the embedded view was removed from it's parent.

Unfortunately, I am now facing #31139 whenever the keyboard appears because it resizes the embedded Flutter View.

**Comment by kf6gpe** [comment] 2019-12-20 22:56
@searchy2 Am I correct in reading your last comment that this is no longer an issue for you? I'm closing it based on that, but if I'm wrong, please feel free to reopen it. Thanks!

**Closed by kf6gpe** 2019-12-20 22:56 UTC
Labels: a: accessibility, engine, severe: crash, ▣ platform-android
