### ISSUE TITLE
null pointer dereference after flutter upgrade

### ISSUE THREAD

**Issue by craigjp99** [flutter/flutter#78020] opened 2021-03-12 11:55 UTC
Hi team,

I've got an app that I've been working on for quite many months now, and while there were times early on when I would get occasional errors and issues, recently the app itself has been running fine while I've been doing my testing and adding new features.  The main screen of my app is primarily comprised of an AppBar, and a Tab view - one tab has a GoogleMap widget, the other tab has a scrolling List View.  There's some other screens like Settings, Search - which essentially just set different properties that control what is displayed on the map and in the list.

Just this week I had noticed that flutter was telling me there was an upgrade available (I have taken other flutter upgrades in the past), and I also checked recent versions of packages that I was using and noticed that a few were behind, so went ahead and did the flutter upgrade and brought my packages up to date.

One of the packages I'd been using was "firebase_admob" (https://pub.dev/packages/firebase_admob), and noted on this one that it was stating it would be deprecated and to transfer over to "google_mobile_ads", which I also went ahead and did.  The transition to that package was pretty easy.
However, when I started testing the app again, it would crash with the following exception:

D/EGL_emulation( 7501): eglMakeCurrent: 0xec4e08c0: ver 3 0 (tinfo 0xf7689880)
F/libc    ( 7501): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 7532 (RenderThread), pid 7501 (.shows_near_me1)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-03-12 22:33:18+1100
pid: 7501, tid: 7532, name: RenderThread  >>> com.example.shows_near_me1 <<<
uid: 10147
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    eax c5515000  ebx d87be864  ecx d86285c0  edx 0000001d
    edi ca67b988  esi ec46c000
    ebp ca67b94c  esp ca67b8ec  eip 00000000
backtrace:
      #00 pc 00000000  <unknown>
      #01 pc 0286c771  /system/product/app/TrichromeLibrary/TrichromeLibrary.apk!libmonochrome.so (offset 0x66c000) (BuildId: ffe50d4377c82928759c1f40f1b35ba9f411454a)
Lost connection to device.
Exited (sigterm)

With some debugging and troubleshooting, I got to the point of determining that the crash is occurring when my banner ad is shown (ie. when the "onAdLoaded" event occurs, for the ad listener, and this statement (as per example) runs:
       bannerCompleter.complete(ad as BannerAd);

Then a whole bunch of further troubleshooting (including going back to "firebase_admob", but then still experiencing the same crash), I determine the following scenarios:

- "load" the banner ad, but don't run the "bannerCompleter.complete..." statement (ie. that's the only statement that I comment out), and the app runs fine, and I can do all normal interactions with the app (including my Google Map widget)
- don't display the Google Map widget, and then the banner ad loads and displays successfully, and I can interact with all other elements of the app (obviously, not the map, though)
- display the Google Map widget and let the banner ad load and try to display, the crash will then occur at the point when the banner ad tries to display 

So, essentially, without changing any other part of my app, I did the flutter upgrade, put some packages to their latest version, and migrated from "firebase_admob" to "google_mobile_ads", and I now get a crash exception when a banner ad tries to display - BUT ONLY when I also have a GoogleMap widget displaying.

Where to next to try and get a resolution to this?

**Comment by pedromassangocode** [comment] 2021-03-12 12:23
Hi @craigjp99 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/googleads/googleads-mobile-flutter).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-12 12:23 UTC
Labels: in triage

**Comment by yuridiniz** [comment] 2021-03-21 20:44
It is a little frustrating to see this problem wandering around in different repositories without a specific direction, I have this problem of displaying Google Maps + Admob. Before in the Firebase library and now as Google Mobile Ads, I believe that they are one of those problems that will never be solved, since, it is not possible to know the source of the problem and to be able to report in an assertive way. At first glance it seems like an integration problem, where AdMob (Android Native version) does not integrate well with the flutter engine, generating this problem without a father, I am very sad about this problem, since, I am an independent developer, so, my only alternative is to recreate my app entirely on native android to be able to get paid for the ads, but at the same time, it is such a huge and demotivating effort that I can't get started. I'm sorry, it was just an outburst regarding this problem

This error appears in different ways in different places:

https://github.com/googleads/googleads-mobile-flutter/issues/32
https://github.com/flutter/flutter/issues/78578
https://github.com/FirebaseExtended/flutterfire/issues/3529
https://github.com/flutter/flutter/issues/65594
