### ISSUE TITLE
[webview_flutter] WebRTC - error getting user media permission denied

### ISSUE THREAD

**Issue by clingovcjo** [flutter/flutter#55367] opened 2020-04-22 11:12 UTC
I'm trying to open the following page using the WebView
https://appr.tc/r/clingo0005

But I get the following error
error getting user media permission denied

```
WebView(
      initialUrl: _url,
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController webViewController) {
        _controller.complete(webViewController);
      },
      gestureNavigationEnabled: true,
    )
```

The following are the permissions:

```
    <uses-permission android:name="android.permission.INTERNET"/>

    <uses-permission android:name="android.permission.CAMERA" />

    <uses-permission android:name="android.permission.RECORD_AUDIO" />

    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />

    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
```

How to fix?

**Comment by VladyslavBondarenko** [comment] 2020-04-23 08:38
Hi @clingovcjo 
I think you need `<uses-permission android:name="android.permission.INTERNET" />` as well (if you don't have it already).

Tried with `webview_flutter: ^0.3.20`. I can't see the error `error getting user media permission denied`. 
But I see

```
W/ContentCatcher(31207): Failed to notify a WebView
W/VideoCapabilities(31207): Unsupported mime video/divx
W/VideoCapabilities(31207): Unsupported mime video/divx311
W/VideoCapabilities(31207): Unsupported mime video/divx4
W/VideoCapabilities(31207): Unrecognized profile 4 for video/hevc
W/VideoCapabilities(31207): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(31207): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities(31207): Unsupported profile 4 for video/mp4v-es
```
May be related to https://github.com/flutter/flutter/issues/40791

**Comment by darshankawar** [comment] 2020-06-22 05:56
I am able to replicate the `permission denied` error on Android Samsung Galaxy device on latest `dev channel (1.20.0-0.0.pre)` and using latest version of `webview_flutter`.

```I/chromium(19962): [INFO:CONSOLE(6544)] "1.717: Error getting user media: Permission denied", source: https://appr.tc/js/apprtc.debug.js (6544)```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0-0.0.pre at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2021-08-06 12:53
This issue is reproducible on the latest `master 2.5.0-6.pre.21` with `webview_flutter: ^2.0.10`.

<details>
<summary>logs</summary>

```
I/chromium( 9814): [INFO:CONSOLE(212)] "4.135: Initializing; server= undefined.", source: https://appr.tc/js/util.js (212)
I/chromium( 9814): [INFO:CONSOLE(212)] "4.136: Initializing; room=clingo0005.", source: https://appr.tc/js/util.js (212)
W/cr_media( 9814): Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
I/CameraManagerGlobal( 9814): Connecting to camera service
W/cr_media( 9814): Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
I/chromium( 9814): [INFO:CONSOLE(212)] "4.483: Retrieved ICE server information.", source: https://appr.tc/js/util.js (212)
I/chromium( 9814): [INFO:CONSOLE(212)] "4.618: Error getting user media: Permission denied", source: https://appr.tc/js/util.js (212)
I/chromium( 9814): [INFO:CONSOLE(212)] "4.624: getUserMedia error: Failed to get access to local media. Error name was NotAllowedError. Continuing without sending a stream.", source: https://appr.tc/js/util.js (212)
D/EGL_emulation( 9814): app_time_stats: avg=362.57ms min=7.70ms max=972.76ms count=3
D/EGL_emulation( 9814): app_time_stats: avg=803.29ms min=10.55ms max=14183.71ms count=18
D/EGL_emulation( 9814): app_time_stats: avg=5594.61ms min=70.31ms max=16517.90ms count=3
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.21, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.5.0-6.0.pre.21 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (8 hours ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</details>

**Comment by chorchannaseang** [comment] 2021-08-24 07:35
webview_flutter: ^2.0.12
When I add youtube link.

D/EGL_emulation(15675): eglCreateContext: 0xbc20c9c0: maj 2 min 0 rcv 2
I/press.mobile_v(15675): Waiting for a blocking GC ProfileSaver
I/press.mobile_v(15675): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 25.509ms
D/EGL_emulation(15675): eglCreateContext: 0xbc20eb00: maj 2 min 0 rcv 2
E/chromium(15675): [ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
E/chromium(15675): [ERROR:web_contents_delegate.cc(225)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
W/cr_media(15675): Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
D/EGL_emulation(15675): eglCreateContext: 0xbc2108c0: maj 2 min 0 rcv 2
D/EGL_emulation(15675): eglCreateContext: 0xeb1b3d20: maj 2 min 0 rcv 2
I/AAudio  (15675): AAudioStreamBuilder_openStream() called ----------------------------------------
I/AudioStreamBuilder(15675): rate   =  48000, channels  = 2, format   = 5, sharing = SH, dir = OUTPUT
I/AudioStreamBuilder(15675): device =      0, sessionId = -1, perfMode = 11, callback: ON with frames = 2048
I/AudioStreamBuilder(15675): usage  =      1, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
I/AudioStreamBuilder(15675): privacy sensitive = false
D/AudioStreamBuilder(15675): build() MMAP not used because AAUDIO_PERFORMANCE_MODE_LOW_LATENCY not requested.
D/press.mobile_v(15675): PlayerBase::PlayerBase()
D/AudioStreamTrack(15675): open(), request notificationFrames = 2048, frameCount = 0
D/AAudioStream(15675): setState(s#3) from 0 to 2
W/AudioStreamTrack(15675): open() flags changed from 0x00000008 to 0x00000000
W/AudioStreamTrack(15675): open() perfMode changed from 11 to 10
I/AAudio  (15675): AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#3 ----------------
D/AAudio  (15675): AAudioStream_requestStart(s#3) called --------------
D/AAudioStream(15675): setState(s#3) from 2 to 3
D/AudioStreamLegacy(15675): onAudioDeviceUpdate() devId 2 => 2
D/press.mobile_v(15675): PlayerBase::start() from IPlayer
D/AAudio  (15675): AAudioStream_requestStart(s#3) returned 0 ---------
D/AAudioStream(15675): setState(s#3) from 3 to 4
I/cr_MediaCodecBridge(15675): create MediaCodec video decoder, mime video/x-vnd.on2.vp9
I/OMXClient(15675): IOmx service obtained
I/MediaCodec(15675): MediaCodec will operate in async mode
D/SurfaceUtils(15675): connecting to surface 0xe5acc998, reason connectToSurface
I/MediaCodec(15675): [OMX.android.goldfish.vp9.decoder] setting surface generation to 16051207
D/SurfaceUtils(15675): disconnecting from surface 0xe5acc998, reason connectToSurface(reconnect)
D/SurfaceUtils(15675): connecting to surface 0xe5acc998, reason connectToSurface(reconnect)
E/ACodec  (15675): [OMX.android.goldfish.vp9.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
D/SurfaceUtils(15675): disconnecting from surface 0xe5acc998, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(15675): connecting to surface 0xe5acc998, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(15675): set up nativeWindow 0xe5acc998 for 406x720, color 0x13, rotation 0, usage 0x1002900
D/NdkImageReader(15675): acquireImageLocked: Overriding buffer format YUV_420_888 to 0x13.
W/AudioManager(15675): Use of stream types is deprecated for operations other than volume control
W/AudioManager(15675): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case

**Comment by stuartmorgan** [comment] 2023-05-21 14:49
Closing; https://github.com/flutter/packages/pull/3543 added the ability to request permissions.

**Closed by stuartmorgan** 2023-05-21 14:49 UTC
Labels: plugin, p: webview, has reproducible steps, P5, found in release: 2.5
