### ISSUE TITLE
[tool_crash] IndexError: RangeError (index): Index out of range: index should be less than 45840444: 58159314

### ISSUE THREAD

**Issue by FedericoCampesan** [flutter/flutter#103510] opened 2022-05-11 16:38 UTC
## Command
```
flutter run -d windows
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
IndexError: RangeError (index): Index out of range: index should be less than 45840444: 58159314
```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:4181:7)
#1      InputStream.readUint32 (package:archive/src/util/input_stream.dart:237:22)
#2      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:49:34)
#3      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
#4      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:522:42)
#6      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1113:18)
<asynchronous suspension>
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:910:7)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:812:5)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:681:9)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1272:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Versione 10.0.19043.1645], locale it-IT)
    • Flutter version 2.10.5 at C:\Users\FedericoCampesan\Documents\Work\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\FedericoCampesan\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.67.1)
    • VS Code at C:\Users\FedericoCampesan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ffb2ecea5223acdd139a5039be2f9c796962833d
### Plugins
app_settings-4.1.6
desktop_window-0.4.0
device_info_plus-3.2.3
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
flutter_barcode_scanner-2.0.0
flutter_beep-1.0.0
flutter_local_notifications-9.5.2
flutter_native_splash-2.1.6
flutter_plugin_android_lifecycle-2.0.6
flutter_secure_storage-5.0.2
flutter_secure_storage_linux-1.1.0
flutter_secure_storage_macos-1.1.0
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.10
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.6
path_provider_macos-2.0.6
path_provider_windows-2.0.6
shared_preferences-2.0.14
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqlite3_flutter_libs-0.5.6

**Comment by darshankawar** [comment] 2022-05-12 07:20
Closing this as duplicate of https://github.com/flutter/flutter/issues/84276

**Closed by darshankawar** 2022-05-12 07:20 UTC
Labels: in triage
