### ISSUE TITLE
Flutter WebView JVM crash when height is large/ wrapped within ListView, SurfaceAndroidWebView does not work!!!

### ISSUE THREAD

**Issue by flutting** [flutter/flutter#113378] opened 2022-10-13 12:10 UTC
// https://github.com/flutter/flutter/issues/45243

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: CrashingWebViewExample()));

class CrashingWebViewExample extends StatefulWidget {
  @override
  _CrashingWebViewExampleState createState() => _CrashingWebViewExampleState();
}

class _CrashingWebViewExampleState extends State<CrashingWebViewExample> {
  late WebViewController _webViewController;
  // [1] the webview height was set to this because the webpage might not have been large enough to verify
  double _webViewHeight = 100000;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) {
      WebView.platform = SurfaceAndroidWebView();
    }
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(height: 100, color: Colors.green),
          Container(
            height: _webViewHeight,
            child: WebView(
              initialUrl: 'https://en.wikipedia.org/wiki/Cephalopod_size',
              javascriptMode: JavascriptMode.unrestricted,
              onPageFinished: (String url) => _onPageFinished(context, url),
              onWebViewCreated: (controller) async {
                _webViewController = controller;
              },
            ),
          ),
          Container(height: 100, color: Colors.yellow),
        ],
      ),
    );
  }

  Future<void> _onPageFinished(BuildContext context, String url) async {
    double newHeight = double.parse(
      await _webViewController
          .evaluateJavascript("document.documentElement.scrollHeight;"),
    );
    // commented out because of [1]
    // setState(() {
    //   _webViewHeight = newHeight;
    // });
  }
}
```

**Comment by huycozy** [comment] 2022-10-13 12:54
@flutting Which `webview_flutter` version are you using? Also, please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by huycozy** [comment] 2022-10-14 05:25
@flutting 
It looks like the issue is only reproducible on specific devices. Below is the result when reproducing this issue on the latest `stable` and `master` channels.

- Pixel 3a, Android 12 ❌
- Samsung Galaxy Tab A7 Lite, Android 12 OneUI 4.1, SM-T225 ✅

✅: No Issue ❌: Issue reproduced

<details>
<summary>Logs (Pixel 3a, Android 12)</summary>

```bash
Launching lib/webview_crash_113378.dart on Pixel 3a in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:51480/3ZJlPG0Liwc=/ws
Syncing files to device Pixel 3a...
I/WebViewFactory(31061): Loading com.google.android.webview version 103.0.5060.129 (code 506012933)
W/eproduce_issue(31061): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/eproduce_issue(31061): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/eproduce_issue(31061): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/eproduce_issue(31061): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/eproduce_issue(31061): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_WVCFactoryProvider(31061): Loaded version=103.0.5060.129 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(31061): Successfully loaded native library
I/cr_CachingUmaRecorder(31061): Flushed 9 samples from 9 histograms.
I/Gralloc4(31061): mapper 4.x is not supported
W/Gralloc3(31061): mapper 3.x is not supported
W/Gralloc4(31061): allocator 4.x is not supported
W/Gralloc3(31061): allocator 3.x is not supported
D/CompatibilityChangeReporter(31061): Compat change id reported: 171228096; UID 12152; state: ENABLED
I/Choreographer(31061): Skipped 66 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(31061): Davey! duration=1133ms; Flags=1, FrameTimelineVsyncId=19329, IntendedVsync=1118786031696, Vsync=1119886031652, InputEventId=0, HandleInputStart=1119893389997, AnimationStart=1119893401039, PerformTraversalsStart=1119893402236, DrawStart=1119895891299, FrameDeadline=1118806698362, FrameInterval=1119893296195, FrameStartTime=16666666, SyncQueued=1119896908070, SyncStart=1119897077081, IssueDrawCommandsStart=1119897986404, SwapBuffers=1119916834426, FrameCompleted=1119919617864, DequeueBufferDuration=7886823, QueueBufferDuration=854792, GpuCompleted=1119919617864, SwapBuffersCompleted=1119918341353, DisplayPresentTime=0, 
W/eproduce_issue(31061): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
W/cr_media(31061): Requires BLUETOOTH permission
I/PlatformViewsController(31061): Hosting view in view hierarchy for platform view: 0
E/FrameEvents(31061): updateAcquireFence: Did not find frame.
E/FrameEvents(31061): updateAcquireFence: Did not find frame.
I/Choreographer(31061): Skipped 162 frames!  The application may be doing too much work on its main thread.
Lost connection to device.

```
</details>

<details>
<summary>Logs (Pixel 3a, Android 12 - without SingleChildScrollView)</summary>

```bash
Launching lib/webview_crash_113378.dart on Pixel 3a in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:52061/_SSEt78BMWw=/ws
Syncing files to device Pixel 3a...
I/WebViewFactory(20815): Loading com.google.android.webview version 103.0.5060.129 (code 506012933)
W/eproduce_issue(20815): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/eproduce_issue(20815): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/eproduce_issue(20815): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/eproduce_issue(20815): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/eproduce_issue(20815): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_WVCFactoryProvider(20815): Loaded version=103.0.5060.129 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(20815): Successfully loaded native library
I/cr_CachingUmaRecorder(20815): Flushed 9 samples from 9 histograms.
E/chromium(20815): [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/com.example.reproduce_issues/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
E/chromium(20815): [ERROR:simple_index_file.cc(617)] Could not reconstruct index from disk
D/CompatibilityChangeReporter(20815): Compat change id reported: 171228096; UID 12152; state: ENABLED
W/eproduce_issue(20815): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
W/cr_media(20815): Requires BLUETOOTH permission
I/PlatformViewsController(20815): Hosting view in view hierarchy for platform view: 0
I/Gralloc4(20815): mapper 4.x is not supported
W/Gralloc3(20815): mapper 3.x is not supported

======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 99441 pixels on the bottom.

The relevant error-causing widget was: 
  Column Column:file:///Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/reproduce_issues/lib/webview_crash_113378.dart:28:12
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#0ccc8 OVERFLOWING
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, h=759.3)
...  size: Size(392.7, 759.3)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
====================================================================================================
W/Gralloc4(20815): allocator 4.x is not supported
W/Gralloc3(20815): allocator 3.x is not supported
E/FrameEvents(20815): updateAcquireFence: Did not find frame.
E/FrameEvents(20815): updateAcquireFence: Did not find frame.
E/eproduce_issue(20815): [SurfaceTexture-0-20815-0] bindTextureImage: error binding external image: 0x502
E/flutter (20815): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter (20815): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter (20815): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:249)
E/flutter (20815): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
E/flutter (20815): 
F/flutter (20815): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1319)] Check failed: fml::jni::CheckException(env). 
E/AndroidRuntime(13731): FATAL EXCEPTION: main
E/AndroidRuntime(13731): Process: com.android.phone, PID: 13731
E/AndroidRuntime(13731): DeadSystemException: The system died; earlier logs will point to the root cause
Lost connection to device.

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-6.0.pre.29, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-6.0.pre.29 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c738c8aa96 (6 hours ago), 2022-10-12 23:49:12 -0400
    • Engine revision 7638a1463b
    • Dart version 2.19.0 (build 2.19.0-307.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

It seems this is a regression issue due to #45243 has been fixed before. Labeling this issue for further investigation.

**Comment by huycozy** [comment] 2022-10-14 05:30
@flutting 
Sorry, this is a known issue being tracked at #106999. Closing this issue as a duplicate, so please follow up on it for further updates.

**Closed by huycozy** 2022-10-14 05:30 UTC
Labels: severe: regression, severe: crash, platform-android, plugin, p: first party, a: platform-views, p: webview, has reproducible steps, severe: fatal crash, found in release: 3.3, found in release: 3.5
