### ISSUE TITLE
[webview_flutter] `setJavaScriptEnabled` is deprecated

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#128714] opened 2023-06-12 17:32 UTC
`WKPreferences setJavaScriptEnabled` was deprecated in favor of `WKWebpagePreferences allowsContentJavaScript` in iOS 14.

Normally we would handle this with an `@availability` gate, with the new and old calls in the two branches, but the mirror-directly-to-Dart structure makes that problematic. @bparrishMines Have you given any thought yet to how we should handle this kind of thing?

**Comment by bparrishMines** [comment] 2023-06-15 03:37
I believe this could be considered a dupe of https://github.com/flutter/flutter/issues/125901. 

But to answer the question, we currently return a `PlatformException` when we attempt to call a method that isn't supported on the current version. Alternatively, we could instead

1. Not throw when the new method is called and log a message.
2. Prevent calls to the deprecated method when above a specific version. The iOS linter should already help with preventing this.
3. Leave a `TODO` on the deprecated method to remove once the minimum supported iOS version is the same as the minimum supported version of the new method.
4. Call both methods in `WebKitWebViewController` with a comment that explains 1-3.

**Closed** 2023-06-15 14:41 UTC
Labels: platform-ios, p: webview, package, P4, tech-debt
