### ISSUE TITLE
PageView page value is never absolute for last page

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#24763] opened 2018-11-27 02:51 UTC
```
[✓] Flutter (Channel master, v0.11.8-pre.12, on Linux, locale en_US.UTF-8)
```

Tested on an Android Emulator and iOS Simulator.

The `page` value of a `PageController` is always very close to absolute but never exact. 
e.g.: A `PageView` with a page count of 3 will result in a `page` value of `2.9999999999999...` but never `3.0`.

**Comment by mallardduck** [comment] 2019-03-15 03:41
Internally the framework seems to just apply `.round()` to the page getter. Based on that the obvious solution is to have the same applied within the getter itself. That would require removing that from both`nextPage` & `previousPage`; it seems like it would be a breaking change tho too.

**Comment by miguelcmedeiros** [comment] 2019-06-13 11:10
This issue has a dangerous implication: when PageView shows the last page, it actually builds the last 2.

Due to the rounding issues mentioned in this ticket, (2.99999999 instead of 3.0), PageView thinks that it needs to build page 2 and 3 since the PageController.page is neither 2.0 or 3.0.
Depending on the contents of each page (complex rendering), this behaviour could impact the functioning of the app. 

Also, it’s really difficult issue for developers to debug. More people will have it.

**Comment by mallardduck** [comment] 2019-06-13 14:16
@miguelcmedeiros while this certainly should be addressed by Flutter team, there's a fairly simple workaround for the issue as described in my comment.

Essentially using this will fix it:

    pageController.addListener(() {
      setState(() {
        this._pageIndex = pageController.page.roundToDouble();
      });
    });

Or if you want an Int you can simply do `round()`. 

Personally I will admit part of my issue was learning from tutorials that weren't fully accurate. So it gave me the wrong impression of this component. Only after diving into the code did I see the flaws in the tutorial.

Again I totally think Flutter could address this directly - but given how long it's been since the original report and that there's an easy work around, I'm not sure when that will be.

**Comment by chunhtai** [comment] 2019-06-14 22:06
the original reproducible will throw exception. here is the modified version
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  final pageController = PageController();
  double page;
  @override
  void initState() {
    super.initState();
    pageController.addListener(() => setState(() {
      page = pageController.page;
    }));
  }

  @override
  Widget build(BuildContext context) => Scaffold(
    body: PageView.builder(
      controller: pageController,
      itemBuilder: (_, index) => Container(
        color: Colors.red,
        child: Center(child: Text("${MediaQuery.of(context).size.width} --  $index -- $page")),
      ),
      itemCount: 3,
      onPageChanged: (page) => print("onPageChanged: $page"),
    ),
  );
}

```

**Closed** 2019-06-18 22:23 UTC
Labels: customer: solaris, framework, severe: customer critical
