### ISSUE TITLE
Add Windows support to url_launcher plugin

### ISSUE THREAD

**Issue by kjk** [flutter/flutter#61051] opened 2020-07-08 00:14 UTC
The code is as simple as:

```
Future<ProcessResult> launchURL(String url) {
  url = url.replaceAll("&", "^&");
  return Process.run("start", [url], runInShell: true);
}
```

` url = url.replaceAll("&", "^&");` is needed because `runInShell` runs the command as equivalent of `cmd.exe /c "start ${url}"` and `&` is interpreted by `cmd.exe` and needs to be escaped with `^`.

**Comment by stuartmorgan** [comment] 2020-07-08 02:44
Duplicate of https://github.com/flutter/flutter/issues/41721

**Closed by stuartmorgan** 2020-07-08 02:44 UTC
