### ISSUE TITLE
I use the showDatePicker and setting initialDatePickerMode,but he made a mistake

### ISSUE THREAD

**Issue by WitheredSkull** [flutter/flutter#40837] opened 2019-09-19 09:11 UTC
Here are the  details
-------------------------------------------------------------------------------------------
```
The method 'formatFullDate' was called on null.
Receiver: null
Tried calling: formatFullDate(Instance of 'DateTime')

User-created ancestor of the error-causing widget was: 
  Theme file:///E:/Flutter/flutter_widget/flutter_widget/lib/view/widget/material/DateWidget.dart:15:18
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _DatePickerDialogState.didChangeDependencies (package:flutter/src/material/date_picker.dart:897:23)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4079:12)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3912:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
```

**Comment by BondarenkoStas** [comment] 2019-09-19 09:26
@WitheredSkull Please provide your ```flutter doctor -v``` output.
Can you provide a small self-contained app that demonstrates the problem? You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Based on past issues, it may be related to localization.

**Comment by escamoteur** [comment] 2019-09-19 09:42
Seems to happen here

```Dart
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    localizations = MaterialLocalizations.of(context);
    textDirection = Directionality.of(context);
    if (!_announcedInitialDate) {
      _announcedInitialDate = true;
      SemanticsService.announce(
        localizations.formatFullDate(_selectedDate),
        textDirection,
      );
    }
  }
```
Seems like `MaterialLocalizations.of(context)` returns null.

@WitheredSkull do you use a MaterialApp as base?

**Comment by jessica1990** [comment] 2019-10-23 03:19
The same mistake.

**Comment by escamoteur** [comment] 2019-10-23 15:29
@jessica1990 could you please post your code sot that we can have a look?

**Comment by jessica1990** [comment] 2019-10-25 03:45
Parent Widget: 
```
         Form(
            key: _formkey,
            autovalidate: true,
            child: Column(
              children: <Widget>[
                //...
                DateRangeFormField(
                  titleText: '有效期限',
                  beginDate: _formData['beginTime'],
                  endDate: _formData['endTime'],
                  showShortCut: true,
                  onBeginChanged: (val) {
                    _setFormData('beginTime', formatDate(val, orderValidDateFormat));
                  },
                  onEndChanged: (val) {
                    _setFormData('endTime', formatDate(val, orderValidDateFormat));
                  },
                ),
              ],
            ),
          ),
```
DateRangeFormField：
 ```
          FlatButton(
            padding: EdgeInsets.all(0),
            child: Text(beginDate ?? formatDate(now, dateFormat)),
            onPressed: () async{
              showDatePicker(
                locale: Locale('zh'),
                context: context,
                initialDate: notEmpty(beginDate) ? DateTime.parse(beginDate) : now,
                firstDate: notEmpty(beginDate) && DateTime.parse(beginDate).isBefore(now) ? DateTime.parse(beginDate) : now,
                lastDate: endDate != null ? DateTime.parse(endDate) : DateTime(now.year + baseYear)
              ).then((DateTime value) {
                if(value != null) {
                  onBeginChanged(value);
                }
              });
            }
```
When I pressed the Flatbutton, errors on console like this:

> The method 'formatFullDate' was called on null.
> Receiver: null
> Tried calling: formatFullDate(Instance of 'DateTime')

Then I debuged, it seems to happens here:

**Comment by escamoteur** [comment] 2019-10-25 10:56
Thanks! Did you try if it happens if you don't define a `locale:` in `showDatePicker` ? Also did you try to provide a Localization to your MaterialApp?
Anyway this should not throw such a Exception.

**Comment by shihaohong** [comment] 2020-02-12 21:31
Hi @jessica1990, could you share a minimal reproducible sample? Based on the snippets of code provided, it's not very easy to move forward since I cannot reproduce the error. Thank you!

**Comment by iapicca** [comment] 2020-03-20 11:33
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-03-20 11:33 UTC
Labels: a: internationalization, f: material design, framework, severe: crash, waiting for customer response
