### ISSUE TITLE
Replace `analyze.sh` with a call to `./dev/bots/analyze.dart`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#114240] opened 2022-10-28 17:40 UTC
Replace the one-line recipe [`analyze.sh`](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/adhoc_validation/resources/analyze.sh) with the actual call to `dart --enable-asserts ./dev/bots/analyze.dart`.

When the analyzer fails and you look at execution details it doesn't give any hints for how to reproduce it locally:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8799041078584176017/+/u/Analyze/analyze/execution_details
```
Executing command [
  '/b/s/w/ir/kitchen-checkout/flutter/recipe_modules/adhoc_validation/resources/analyze.sh',
]
```
Would be better if it looked like
```
Executing command [
  '/b/s/w/ir/x/w/flutter/bin/dart',
  '--enable-asserts',
  '/b/s/w/ir/x/w/flutter/dev/bots/analyze.dart',
]
```
similar to the other tasks.

**Comment by jmagman** [comment] 2022-10-28 17:40
cc @godofredoc

**Comment by drewroengoogle** [comment] 2023-06-29 19:37
It looks like the analysis is currently done through the [adhoc_validation](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/adhoc_validation/) module, which takes the recipe properties and runs an associated script.

@keyonghan What are your thoughts on a way to add more clarity on how to reproduce it? Perhaps we could simply add an `echo` to make it clear that `dart --enable-asserts ./dev/bots/analyze.dart` is being run? My concern with directly running it through a recipe step would kind of go against the purpose of `adhoc_validation`.

**Comment by keyonghan** [comment] 2023-06-29 20:05
Yeah, `echo` the command before the execution SGTM as a short term solution.

**Comment by drewroengoogle** [comment] 2023-06-29 20:08
> Yeah, `echo` the command before the execution SGTM as a short term solution.

Question for my understanding:
In regards to this being a "short term" solution, is there a long term solution you had in mind?

**Comment by keyonghan** [comment] 2023-06-29 20:22
Actually I do not have a good long term solution in mind, which may need a refactoring of the whole adhoc module.
Back to this bug, the goal is to surface the command and `echo` is good enough to me.

**Comment by drewroengoogle** [comment] 2023-06-30 18:13
https://flutter-review.googlesource.com/c/recipes/+/46721 for a one line fix.

I'm not sure what we want to do in regards to this issue. Should we refocus this issue to be related to refactoring adhoc, or is that not something we are trying to do?

**Comment by drewroengoogle** [comment] 2023-07-06 16:36
Discussed with Keyong, we are going to close this for now!

**Closed by drewroengoogle** 2023-07-06 16:36 UTC
Labels: team: infra
