### ISSUE TITLE
Selecting multiple `SelectableText` texts all at once

### ISSUE THREAD

**Issue by ZiyadF296** [flutter/flutter#81673] opened 2021-05-03 09:29 UTC
## Use case
Unable to select multiple separate `SelectableText` widgets text.

## Proposal
Have the ability to select multiple texts that `SelectableText` is holding.
Example:
Notice that the header text "USER DATA" is a separate widget from the paragraph below. Both are `SelectableText` widgets.

![image](https://user-images.githubusercontent.com/56755783/116860781-bf0eca00-ac0a-11eb-8099-e2c37af657fb.png)

However, I cannot select the paragraph text when `USER DATA` is selected. I will need to remove focus from `USER DATA` and then be able to select the below paragraph.

![image](https://user-images.githubusercontent.com/56755783/116860938-01380b80-ac0b-11eb-92e7-9a15b07f2846.png)

PS. Having the ability to select all the text on the page on the Web that is selectable if pressing `Ctrl` + `A` would also be helpful.

**Comment by pedromassangocode** [comment] 2021-05-03 09:39
Closing as duplicate of https://github.com/flutter/flutter/issues/64854. Please follow up on that for updates.
Thank you

**Closed by pedromassangocode** 2021-05-03 09:39 UTC
Labels: in triage
