### ISSUE TITLE
VSCode debugger cannot load call stack / dart source during exception handling on macOS with Flutter 3.3.x

### ISSUE THREAD

**Issue by point-source** [flutter/flutter#113645] opened 2022-10-18 20:47 UTC
## Steps to Reproduce

1. Create a new flutter project using version 3.3.x
2. Run & debug it in VSCode
3. Throw an exception somewhere during execution
4. Try to use the vscode dubugger to step within the stack trace

<img width="305" alt="Screen Shot 2022-10-18 at 4 32 28 PM" src="https://user-images.githubusercontent.com/47544779/196537982-a3eb2f70-96c0-4223-b7c3-1eedc9b0030f.png">

Observe that the source is not available:
`Could not load source 'dart:ui/hooks.dart': <source not available>.`
`Could not load source 'dart:isolate-patch/isolate_patch.dart': <source not available>.`

Conditions necessary to reproduce:
- Flutter version at or above 3.3.x
- Build app for macOS

Making any of these changes will not reproduce the issue:
- Downgrade flutter to 3.0.5
- Build for iOS or Android instead of macOS
- Create a pure dart project with the same dart sdk version (2.18.2)

I found these related issues but could not find a solution among them:

https://github.com/flutter/flutter/issues/24912
https://github.com/Dart-Code/Dart-Code/issues/2519
https://github.com/dart-lang/sdk/issues/19227
https://github.com/dart-lang/sdk/issues/35820
https://stackoverflow.com/questions/54390922/could-not-load-source-dartcore-runtime-libobject-patch-dart-source-not-avai
https://stackoverflow.com/questions/72385991/could-not-load-source-dartcore-patch-errors-patch-dart-source-not-available

Output of flutter doctor:
```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale
    en-US)
    • Flutter version 3.3.4 on channel stable at
      /Users/andrew/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by jason-simmons** [comment] 2022-10-18 21:59
This may be a duplicate of https://github.com/flutter/flutter/issues/111189

Does this still happen on the current Flutter master branch?

**Comment by darshankawar** [comment] 2022-10-19 08:16
@point-source 
Please confirm if same happens on latest master or not.

`flutter channel master`
`flutter upgrade`

**Comment by point-source** [comment] 2022-10-19 15:44
Sure enough, appears to be fixed on master branch. I'll hold out for the next stable release. Thanks

**Comment by darshankawar** [comment] 2022-10-20 06:08
Thanks for the update. Closing based on above comment.

**Closed by darshankawar** 2022-10-20 06:08 UTC
Labels: in triage
