### ISSUE TITLE
Image widget always crash after a single crash

### ISSUE THREAD

**Issue by febg11** [flutter/flutter#64752] opened 2020-08-27 19:47 UTC
I am using a flutter Image.file() to show an Image in my app. I am also using the errorBuilder to handle any crashes and show a message to the user. 

I encounter a problem when i do these steps. 
1) Load a good image that works
2) Load a corrupt image into the same Image.File() widget
3) Load the original good image back into the same Image.File() widget

It seems every file change after the corrupt photo is passed in (step 2) will result in the error builder being shown and not the new good image. 

If i don't pass in the corrupt photo in step 2, the photo changes like it should. Is this a bug with the flutter Image() or should I be doing something after it goes into the errorBuilder.

Here is my current setup.

```
Image.file(
        file,
        fit: BoxFit.cover,
        errorBuilder: (BuildContext context, Object exception, StackTrace stackTrace) {
          print("Failed to initialise the file");
          print(stackTrace);
          //  Once an error occurs it always goes in here 
          return Text("an error occurred");
        },
      );

```

The actual error I receive on all file changes when/after the corrupt file is passed in is

```
Could not instantiate image codec.
```

**Comment by pedromassangocode** [comment] 2020-08-28 11:58
Hi @febg11 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by febg11** [comment] 2020-08-28 19:28
I have wrote a dartpad that shows the problem i am experiencing.

https://dartpad.dev/98c2dacb481c088dfd2e5bee490f45ed

If you click 
1) Good Image
2) Good Image 2
3) Good Image 
4) Good Image 2

The images cycle correctly... which works.

if you then click "Corrupt Image" which will attempt to load a corrupt jpeg file the error builder will fire. 

If you then click "Good Image" or "Good Image 2" they no longer build and the Image is stuck loading the error builder everytime... How can I get it to then load one of the good images again? 

Please let me know if I haven't been clear and I will add more information :) 

Thanks a lot

**Comment by pedromassangocode** [comment] 2020-08-31 07:15
I was able to reproduce this on latest `master` channel.

Based on the code bellow looks like Flutter is reusing the last exception thrown and fire it every time it tries to load a new URL. 
https://github.com/flutter/flutter/blob/c0ea00ed3f8db142e524aacfd5ebcdbfceb17278/packages/flutter/lib/src/widgets/image.dart#L1240-L1243

<details>
<summary> Logs</summary>

```
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 1,301ms.
flutter: #0      _futurize (dart:ui/painting.dart:4856:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:4724:12)
#2      instantiateImageCodec (dart:ui/painting.dart:1721:60)
<asynchronous suspension>
#3      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:97:12)
#4      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:114:20)
<asynchronous suspension>
#5      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
#6      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:504:13)
#7      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:358:22)
#8      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:502:83)
#9      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:108:19)
#10     ImageProvider.resolve.<anonymous closure> (package:flutter/sr<…>

```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.139, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.139 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision c0ea00ed3f (82 minutes ago), 2020-08-30 22:20:16 -0700
    • Engine revision bada9fc5f3
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by febg11** [comment] 2020-09-24 18:24
is using the UniqueKey a good solution or not?

**Comment by pedromassango** [comment] 2020-09-24 20:35
> is using the UniqueKey a good solution or not?

No. This is an issue and will be fixed soon by https://github.com/flutter/flutter/pull/65180.

**Closed** 2020-09-30 21:53 UTC
Labels: a: images, found in release: 1.22, framework, has reproducible steps, severe: crash
