### ISSUE TITLE
Use of flutter 330 causes screen jitter

### ISSUE THREAD

**Issue by PanRulee** [flutter/flutter#113820] opened 2022-10-21 09:26 UTC
I used the flutter 330 in my project and found that the screen jitters under some mobile phones.

For example: OPPO android 12

but , we haven't found any useful logs, just like everything is normal

This is a video link:https://pan.baidu.com/s/1hmXV6Py5lIOpEQCvEVAsLg?pwd=nj64

<iframe height=498 width=510 src="https://pan.baidu.com/s/1hmXV6Py5lIOpEQCvEVAsLg?pwd=nj64">

**Comment by exaby73** [comment] 2022-10-21 09:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/110885. Please upgrade to 3.3.4 to get the fix for it. Thank you.

**Closed** 2022-10-21 09:59 UTC
Labels: in triage, r: duplicate
