### ISSUE TITLE
Example app crashes at init.

### ISSUE THREAD

**Issue by Tlaloc-Es** [flutter/flutter#26775] opened 2019-01-18 21:22 UTC
When I create a new project with flutter in android studio 3.3 and execute it, the app crash on init.

With this adb ADB with Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.4.2 (API 19) on a Nexus 5 not work but when change te api to 24 work.

## Steps to Reproduce

1. With android studio 3.3 and ADB with Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.4.2 (API 19) on a Nexus 5
2. Create new empty flutter project
3. Launch the adv
4. Load the app

## Logs

**Logcat error when execute as a android project**

```
01-18 20:31:36.767 1794-2763/com.google.android.gms.persistent E/NetworkScheduler: Invalid component specified.
01-18 20:31:36.847 1177-1177/? E/Drm: Failed to open plugin directory /vendor/lib/mediadrm
01-18 20:31:58.137 1794-2560/com.google.android.gms.persistent E/WakeLock: GCM_HB_ALARM release without a matched acquire!
01-18 20:46:56.207 3375-3375/? E/memtrack: Couldn't load memtrack module (No such file or directory)
01-18 20:46:56.217 3375-3375/? E/android.os.Debug: failed to load memtrack module: -2
01-18 20:46:56.627 3386-3386/? E/memtrack: Couldn't load memtrack module (No such file or directory)
01-18 20:46:56.627 3386-3386/? E/android.os.Debug: failed to load memtrack module: -2
01-18 20:46:57.517 3402-3402/? E/memtrack: Couldn't load memtrack module (No such file or directory)
01-18 20:46:57.517 3402-3402/? E/android.os.Debug: failed to load memtrack module: -2
01-18 20:46:59.297 3431-3431/? E/memtrack: Couldn't load memtrack module (No such file or directory)
01-18 20:46:59.307 3431-3431/? E/android.os.Debug: failed to load memtrack module: -2
01-18 20:46:59.807 3449-3449/? A/libc: Fatal signal 8 (SIGFPE) at 0xb774dac8 (code=1), thread 3449 (scom.flutterapp)
01-18 20:47:00.657 1971-1971/com.android.launcher E/EGL_emulation: tid 1971: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
01-18 20:48:05.657 1177-1666/? E/Drm: Failed to open plugin directory /vendor/lib/mediadrm
01-18 20:59:19.707 3478-3478/? E/memtrack: Couldn't load memtrack module (No such file or directory)
01-18 20:59:19.707 3478-3478/? E/android.os.Debug: failed to load memtrack module: -2
01-18 20:59:22.007 3510-3510/? E/memtrack: Couldn't load memtrack module (No such file or directory)
01-18 20:59:22.007 3510-3510/? E/android.os.Debug: failed to load memtrack module: -2
01-18 20:59:22.127 3521-3527/? E/jdwp: Failed sending reply to debugger: Broken pipe
01-18 20:59:22.477 3521-3521/? A/libc: Fatal signal 8 (SIGFPE) at 0xb774dac8 (code=1), thread 3521 (scom.flutterapp)
01-18 20:59:23.317 1971-1971/com.android.launcher E/EGL_emulation: tid 1971: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
```

**Logcat verbose as android project**
```
01-18 20:59:22.907 1597-3538/system_process W/ActivityManager:   Force finishing activity tlalocescom.flutterapp/.MainActivity
01-18 20:59:22.967 2113-2290/com.google.android.gms I/Icing: Indexing com.google.android.googlequicksearchbox-applications from com.google.android.googlequicksearchbox
01-18 20:59:23.217 1597-3538/system_process I/WindowManager: Screenshot max retries 4 of Token{9d1c6470 ActivityRecord{9d0afcc8 u0 tlalocescom.flutterapp/.MainActivity t9 f}} appWin=Window{9d14e2f0 u0 Starting tlalocescom.flutterapp} drawState=4
01-18 20:59:23.217 1597-3538/system_process W/WindowManager: Screenshot failure taking screenshot for (1080x1920) to layer 21010
01-18 20:59:23.217 1597-3538/system_process W/ActivityManager: Exception thrown during pause
    android.os.DeadObjectException
        at android.os.BinderProxy.transact(Native Method)
        at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2455)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2329)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2035)
        at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9543)
        at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9436)
        at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10081)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9632)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
01-18 20:59:23.227 1597-1846/system_process I/ActivityManager: Process tlalocescom.flutterapp (pid 3521) has died.
```

**flutter.bat doctor --verbose**
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [VersiÃ³n 10.0.17134.523], locale es-ES)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.4.2 (API 19) (emulator)

• No issues found!
Process finished with exit code 0
```

**Comment by zoechi** [comment] 2019-01-20 13:50
Duplicate of #20091

**Closed by zoechi** 2019-01-20 13:50 UTC
