### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\src\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: C:\src\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0

### ISSUE THREAD

**Issue by rakhman98** [flutter/flutter#158413] opened 2024-11-09 15:15 UTC
## Command
```sh
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target C:\Users\user\Desktop\flutter_rest_api\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\src\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: C:\src\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0
```console
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:699:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:569:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:698:12)
#4      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:875:37)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:735:14)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:421:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:395:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:781:23)
#9      _rootRunUnary (dart:async/zone.dart:1407:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#16     _rootRun (dart:async/zone.dart:1391:47)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _rootRun (dart:async/zone.dart:1399:13)
#21     _CustomZone.run (dart:async/zone.dart:1301:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```console
[✓] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.19045.5073], locale az-Latn-AZ)
    • Flutter version 3.24.4 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (2 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    ✗ Android SDK file not found: C:\Users\user\AppData\Local\Android\sdk\build-tools\34.0.0\aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/to/windows-android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.95.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.5073]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 130.0.6723.117
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 130.0.2849.68

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 603104015dd692ea3403755b55d07813d5cf8965

**Comment by danagbemava-nc** [comment] 2024-11-11 07:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143391

**Closed by danagbemava-nc** 2024-11-11 07:44 UTC
Labels: in triage
