### ISSUE TITLE
[google_maps_flutter] Map shaking and showing white bars while scrolling

### ISSUE THREAD

**Issue by s17476** [flutter/flutter#135888] opened 2023-10-03 04:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
name: map_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

</details>

### Steps to reproduce

1. Create a new project and map key on Google Cloud.
2. Create a new Flutter project.
3. Add google_maps_flutter 2.5.0.
4. Set minSdkVersion to 21.
5. Add an entry <meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR KEY HERE"/> with API key cerated at step 1 to AndroidManifest.xml.
6. Use example widget code from https://pub.dev/packages/google_maps_flutter Readme section.

### Expected results

The application we are working on is a mobile public transport timetable providing live vehicle data. We use Google Maps to show stop markers, vehicles and the route to the stop. Map used to work really smooth even with large markers amount.

### Actual results

The last update to the production version was about two months ago, but a week ago we started receiving reports from users about map scrolling issues on Android devices. In some cases, it is not possible to scroll the map at all. The map shakes when user ties to scroll it. It looks like the map layers are not coordinated with each other. The problem is easier to spot when scrolling slowly.

Since there have been no performance issues with this version for at least 8 weeks, we started by checking the API keys and the overall performance of this version, but we didn't notice any issues that could cause this behavior. However, we discovered an interesting relationship. After the first installation or deletion of application data on the device, the map works as it should. However, it is enough to close it and restart it for problems to appear. It varies on a different scale depending on the device.

I checked the application for performance in DevTools, but I don't see any anomalies. There are no errors in the console either.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/services.dart';
import 'package:google_maps_flutter_android/google_maps_flutter_android.dart';
import 'package:google_maps_flutter_platform_interface/google_maps_flutter_platform_interface.dart';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final mapsImplementation = GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    AndroidMapRenderer? mapRenderer;
    mapsImplementation.useAndroidViewSurface = true;
    try {
      mapRenderer = await mapsImplementation
          .initializeWithRenderer(AndroidMapRenderer.latest);

      // Renderer can be initialized only once, that's why it throws PlatformException
      // on Hot Restart
    } on PlatformException catch (e) {
      debugPrint(e.toString());
    }
  }
  runApp(const MapSample());
}

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller =
      Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: GoogleMap(
            mapType: MapType.normal,
            initialCameraPosition: _kGooglePlex,
            onMapCreated: (GoogleMapController controller) {
              _controller.complete(controller);
            },
          ),
        ),
        floatingActionButton: FloatingActionButton.extended(
          onPressed: _goToTheLake,
          label: const Text('To the lake!'),
          icon: const Icon(Icons.directions_boat),
        ),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    await controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/62615538/bdccf946-4554-4255-a44b-dc6270a1cf01

https://github.com/flutter/flutter/assets/62615538/0558b633-a930-4518-a610-01d686befd7b

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
gfraczek@Grzegorzs-MacBook-Pro map_test % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
    • Flutter version 3.13.4 on channel stable at /Users/gfraczek/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (3 weeks ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/gfraczek/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • RMX3393 (mobile)        • PJ5PVGRGTSJF6PGE          • android-arm64  • Android 13 (API 33)
    • iPhone (Piotr) (mobile) • 00008030-001E646A3404202E • ios            • iOS 16.6.1 20G81
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-10-03 08:47
Hi @s17476 
I can reproduce this issue on my device `Realme 6, Android 11`. The issue is much clearer on the master than stable channel.

With your initial sample code, I see you are getting map instance before map renderer. The order should be reversed, see [Map renderer](https://pub.dev/packages/google_maps_flutter_android#map-renderer):

```dart
WidgetsFlutterBinding.ensureInitialized();
AndroidMapRenderer mapRenderer = AndroidMapRenderer.platformDefault;
final GoogleMapsFlutterPlatform mapsImplementation = GoogleMapsFlutterPlatform.instance;
if (mapsImplementation is GoogleMapsFlutterAndroid) {
mapsImplementation.useAndroidViewSurface = true;
  mapRenderer = await mapsImplementation
      .initializeWithRenderer(AndroidMapRenderer.latest);
}
```

After this change, the map can move more smoothly. Can you retry and confirm?

**Comment by s17476** [comment] 2023-10-03 09:58
Hi @huycozy ,
thanks for the quick reply. Unfortunately, changing the order of getting instances didn't solve the problem. Have you tried killing and relaunching the app?
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  AndroidMapRenderer mapRenderer = AndroidMapRenderer.platformDefault;
  final mapsImplementation = GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    mapsImplementation.useAndroidViewSurface = true;
    try {
      mapRenderer = await mapsImplementation
          .initializeWithRenderer(AndroidMapRenderer.latest);

      // Renderer can be initialized only once, that's why it throws PlatformException
      // on Hot Restart
    } on PlatformException catch (e) {
      debugPrint(e.toString());
    }
  }
  runApp(const MapSample());
}
```
It's exactly like before. 
1. I delete the app from my phone. 
2. flutter run --release on Realme 9 Pro+ Android 13. 
3. First launch - everything works smoothly. 
4. I'm killing the app. 
5. I open it again and the symptoms are the same. Shaking + white stripes. 
6. I'm closing it and clearing data. 
7. Starting app again. It works as it should. 
8. After closing and restarting, the map shakes again.

Unfortunately, the problem also affected the production version, which, as I wrote, has not been updated for about two months, and problems with the map started about a week ago. 

Initially, we thought that this only concerned the new version that we are currently working on and which has been heavily rebuilt. However, after a short time we started receiving emails and videos from users.

**Comment by huycozy** [comment] 2023-10-03 12:10
Thanks for the update. I can reproduce this issue following your steps above (after killing app from Recent menu and re-opening it).

Reproduced this on Android (Realme 6, Android 11) whilst it's not reproducible on iOS (iPhone 7, iOS 15.7.9).


<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/a701fa46-3eab-4e0c-a82a-37e8aafbf81a

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-x64, locale en-VN)
    • Flutter version 3.13.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Giraffe.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.16.0-2.0.pre.15, on macOS 14.0 23A344 darwin-x64, locale en-VN)
    • Flutter version 3.16.0-2.0.pre.15 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b8ff0e431 (3 hours ago), 2023-10-02 21:30:05 -0400
    • Engine revision 5bc3ab5145
    • Dart version 3.2.0 (build 3.2.0-222.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Giraffe.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by s17476** [comment] 2023-10-03 13:54
iOS works as it should. Tested on physical iPhone 11, iPhone 14 Pro Max. There were no reports from iOS users either. 

The problem probably only affects [google_maps_android]. 

We first noticed problems with the map on September 27. On September 28, we received the first reports from users and the accompanying low ratings on Google Play.

**Comment by fleoparra** [comment] 2023-10-03 22:07
Same problem here on Moto G60s Android 12

**Comment by fleoparra** [comment] 2023-10-04 16:24
In my case the problem was caused by latest renderer:

```
AndroidMapRenderer mapRenderer = AndroidMapRenderer.platformDefault;
// ···
  final GoogleMapsFlutterPlatform mapsImplementation =
      GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    WidgetsFlutterBinding.ensureInitialized();
    mapRenderer = await mapsImplementation
        .initializeWithRenderer(AndroidMapRenderer.latest);
  }

```

But I had put that code to fix #105965 

For now I prefer not to use latest renderer and wait some milliseconds on pops to prevent NullPointerException error.

**Comment by s17476** [comment] 2023-10-04 18:12
Previously, we used the legacy renderer, but we changed it to latest because of the number of crashes and because the latest one worked smoothly, quickly and stably. 

We have been using it for several months and had no problems with it until last week.

**Comment by JPFrancoia** [comment] 2023-10-05 16:51
Same issue here on a Xiaomi Redmi Note 10 Pro running Android 13 and MIUI Global 14.0.3

**Comment by alfanthariq** [comment] 2023-10-06 01:26
Same issue here, but only on release mode. If i run debug mode maps view work fine. Tested on Samsung A54 One UI 5.1

**Comment by pietroid** [comment] 2023-10-06 12:32
Same issue here. Reported that on https://github.com/flutter/flutter/issues/135763. Just to know, do you see those logs here and the exception? 
![image](https://github.com/flutter/flutter/assets/22605271/577f475c-9879-40ec-9784-81961637cd35)

**Comment by dayron9110** [comment] 2023-10-06 18:19
Same issue here, we have observed this behavior on different cell phones such as Motorola, Xiaomi, Realme and Samsung.

**Comment by ozzy1873** [comment] 2023-10-06 18:21
Also on Pixel 7

**Comment by fleoparra** [comment] 2023-10-06 21:07
> Same issue here, but only on release mode. If i run debug mode maps view work fine. Tested on Samsung A54 One UI 5.1

In my case, the problem is only on release mode too and with almost all of our test Android phones (some samsung devices, motorola, tecno, xiaomi). With a Samsung S22 Ultra works fine the map.

**Comment by mathrocco** [comment] 2023-10-18 19:19
@gmackall I noticed you marked it as P2 since it's not as important as other structural and cross problems. But I would like to re-emphasize that for those of us relying on flutter + gmaps this bug is causing a huge business impact, making the map completely unusable.

Since this problem only happens after some remote config gets downloaded, I believe that you could find a temporary solution to solve this issue. Please considere this for the prioritization. Thanks!

**Comment by johnmccutchan** [comment] 2023-10-18 20:12
I'm starting to look at this now. Just some clarifying questions:

@s17476 - You published an application near the beginning of August that worked without issue for 8 weeks and then people started to complain about the shaking/jank? Is it still true that uninstalling the app and then reinstalling it solves the problem?

**Comment by johnmccutchan** [comment] 2023-10-18 22:16
I cannot reproduce on my Pixel 6 Pro. 

```
$ flutter --version                                                                                                                                                                                                             
Flutter 3.16.0-10.0.pre.23 • channel main • git@github.com:flutter/flutter.git
Framework • revision c6aeab930a (7 days ago) • 2023-10-11 09:36:20 -0700
Engine • revision ec1d0d69fc
Tools • Dart 3.3.0 (build 3.3.0-6.0.dev) • DevTools 2.28.1
```


I initialized with:

```
AndroidMapRenderer mapRenderer = AndroidMapRenderer.platformDefault;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    // Don't use hybrid composition.
    mapsImplementation.useAndroidViewSurface = false;
    // Use latest renderer.
    mapRenderer = await mapsImplementation
        .initializeWithRenderer(AndroidMapRenderer.latest);
  }
```

I used the example widget code:

```
class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller =
      Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        mapType: MapType.normal,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
    );
  }
}
```

**Comment by johnmccutchan** [comment] 2023-10-18 22:23
I can reproduce the issue when I use hybrid composition mode:

```
    mapsImplementation.useAndroidViewSurface = true;
```

**Comment by johnmccutchan** [comment] 2023-10-18 22:23
What is unusual is that we haven't made changes to the hybrid composition rendering mode in months.

**Comment by johnmccutchan** [comment] 2023-10-18 22:24
The workaround is:

```
 mapsImplementation.useAndroidViewSurface = false;
```

**Comment by johnmccutchan** [comment] 2023-10-18 22:32
Actually, I can now observe this with hybrid composition enabled or disabled. It seems flakey.

**Comment by dayron9110** [comment] 2023-10-18 22:58
The issue started happening in our app in production without having made changes about 3 weeks or more ago. It is happening on many devices from different brands.

**Comment by dayron9110** [comment] 2023-10-18 23:00
> I can reproduce the issue when I use hybrid composition mode:
> 
> ```
>     mapsImplementation.useAndroidViewSurface = true;
> ```

I don't think changing the way the Google Maps plugin is displayed is best.

**Comment by johnmccutchan** [comment] 2023-10-18 23:06
Internal bugs: 305200382 and 277751370

**Comment by johnmccutchan** [comment] 2023-10-18 23:09
An update:

Google Maps on Android has a bug that is causing this shaking issue. I am discussing with internal folks on how we can address it.

**Comment by johnmccutchan** [comment] 2023-10-19 16:39
There is a workaround for this issue:

You must explicitly request the _legacy_ renderer. 

```
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    // Use legacy renderer.
    mapRenderer = await mapsImplementation
        .initializeWithRenderer(AndroidMapRenderer.legacy);
  }
```

**Comment by rlueders** [comment] 2023-10-19 16:50
This is good to know, it isn't really a viable workaround since the new renderer is itself a workaround for other issues associated with the legacy renderer like [105965](https://github.com/flutter/flutter/issues/105965)

**Comment by fleoparra** [comment] 2023-10-19 17:00
> There is a workaround for this issue:
> 
> You must explicitly request the _legacy_ renderer.
> 
> ```
>   if (mapsImplementation is GoogleMapsFlutterAndroid) {
>     // Use legacy renderer.
>     mapRenderer = await mapsImplementation
>         .initializeWithRenderer(AndroidMapRenderer.legacy);
>   }
> ```

In my case, this was not an option because with legacy renderer there is an issue #105965 
I decided to implement a kind of Joystick for map movements using [flutter_joystick](https://pub.dev/packages/flutter_joystick) and buttons for map zoom. People with problems can to use Joystick for movements or zoom.

```
class MapControls extends StatelessWidget {
  final Function(CameraUpdate) _moveCamera;
  final Function(CameraUpdate) _animateCamera;
  final double _bottomPadding;

  const MapControls({
    super.key,
    required Function(CameraUpdate) moveCamera,
    required Function(CameraUpdate) animateCamera,
    double bottomPadding = 0,
  })  : _moveCamera = moveCamera,
        _animateCamera = animateCamera,
        _bottomPadding = bottomPadding;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Positioned(
          bottom: 20.0 + _bottomPadding,
          left: 0.0,
          child: Joystick(
            mode: JoystickMode.all,
            listener: (details) {
              _moveCamera(CameraUpdate.scrollBy(30 * details.x, 30 * details.y));
            },
          ),
        ),
        Positioned(
          bottom: 120.0 + _bottomPadding,
          left: 28.0,
          child: InkWell(
            onTap: () {
              _animateCamera(CameraUpdate.zoomBy(-0.5));
            },
            child: Container(
              color: Colors.black26,
              padding: const EdgeInsets.all(8.0),
              child: const Icon(
                Icons.zoom_out_outlined,
                color: Colors.white,
                size: 24.0,
              ),
            ),
          ),
        ),
        Positioned(
          bottom: 162.0 + _bottomPadding,
          left: 28.0,
          child: InkWell(
            onTap: () {
              _animateCamera(CameraUpdate.zoomBy(0.5));
            },
            child: Container(
              color: Colors.black26,
              padding: const EdgeInsets.all(8.0),
              child: const Icon(
                Icons.zoom_in_outlined,
                color: Colors.white,
                size: 24.0,
              ),
            ),
          ),
        ),
      ],
    );
  }
}
```

**Comment by johnmccutchan** [comment] 2023-10-19 17:22
I am aware of the issues with the legacy renderer but as things stand now, it seems like the legacy renderer is better than latest renderer. 

I am actively working on fixing the issues with the latest renderer and then we will make it the default.

**Comment by johnmccutchan** [comment] 2023-10-19 18:02
Slight correction to what is going on:

Google Maps pushed an updated version of their latest renderer and that is incompatible with the Flutter Plugin. We are working on it internally.

In the meantime, explicitly requesting the legacy renderer is the workaround.

**Comment by topex-psy** [comment] 2023-10-21 12:59
Any updates on this issue?

**Comment by MattyBoy4444** [comment] 2023-10-25 15:55
Any update on this?  I see other apps are having the same problem.  Ex: realtor.com

**Comment by johnmccutchan** [comment] 2023-10-25 16:02
Update:

- Google Maps team can reproduce the issue.
- Currently investigating the root cause.

The recommended workaround has not changed:

- Use the legacy renderer.

**Comment by johnmccutchan** [comment] 2023-10-25 16:31
Update:

Google Maps team has identified the root cause and is going to push an update to phones today to disable the problematic code.

I will update this bug once people should expect to be able to confirm that the behaviour is fixed.

**Comment by s17476** [comment] 2023-10-26 16:47
I was unavailable for several days. It's great that the problem has been resolved in this time. Today I checked our app on several Samsung, Oneplus, Realme, Huawei devices running Android 12 and 13. It seems that the problem when dragging the map no longer occurs. At least not on the devices I tested on. Great job @johnmccutchan!

**Comment by johnmccutchan** [comment] 2023-10-26 18:04
Glad to hear that the change has propagated to our users. We expect 100% deployment by Friday October 27th.

**Closed** 2023-10-26 18:08 UTC
Labels: platform-android, p: maps, package, c: rendering, has reproducible steps, P1, team-android, triaged-android, found in release: 3.13, found in release: 3.16
