### ISSUE TITLE
Need for data_table with no InkWell

### ISSUE THREAD

**Issue by JosefPerdolt** [flutter/flutter#79264] opened 2021-03-29 12:33 UTC
It is not possible to create a DataTable with no InkWell on it's rows - hence you will always have "InkWell" effects on the data row (Animation & Events).

Reason:
The call of _buildDataCell will always provide a "onSelectChanged" Method and not pass the "null"-Value that is actually assigned to the onSelectChanged from the DataRow. Therefore if you create a DataRow with no "onTap" of the DataCell or "onSelectChanged" you still will get the TableRowInkWell.

Problem:
- The DataRow will always seem clickable -> bad UX
- In a certain combination this will produce the following bug:
DataTable with TextFormField + Samsung Tab A7 + Hardware Keyboard for Tablet --> "Space" will call the onSelectionChanged" event but the actual Input of the "space" character will not be passed to the TextFormField -> you can't enter "space" any longer.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
DataRow with no InkWell

**Actual results:** 
DataRow with "TableRowInkWell

<details>
  <summary>Logs</summary>

Flutter (Channel stable, 2.0.2, on Mac OS X 10.14.6 18G8022 darwin-x64, locale de-AT)
    • Flutter version 2.0.2 at /Users/--/Developer/flutter
    • Framework revision 8962f6dc68 (3 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/--/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    ! Xcode 11.0.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

</details>

**Comment by TahaTesser** [comment] 2021-03-29 12:42
Hi @JosefPerdolt 
I see there's an open issue addressing the case you described.
Closing as duplicate of https://github.com/flutter/flutter/issues/70755
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-29 12:42 UTC
Labels: in triage
