### ISSUE TITLE
[iOS]Flutter which is integrated into iOS projects as a Flutter Module, does not take effect when the code is modified.

### ISSUE THREAD

**Issue by ChoiKarl** [flutter/flutter#101979] opened 2022-04-15 10:34 UTC
I have integrated Flutter into my iOS project as a Flutter Module, and every time I change the Flutter code and then re-run it in Xcode, the code does not take effect.
I have to remove the stuff inside Xcode->DerivedData and then re-run it for it to take effect.
I have created a new iOS project and a new Flutter Module project and have the same problem.
This problem does not exist in 2.2.0.

```
Podfile
target 'flutter_test' do

     flutter_application_path ='../f_f'
     load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
     install_all_flutter_pods(flutter_application_path)

  # Pods for flutter_test

end
```
<details>
<summary>flutter doctor</summary>
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.10.3 at /Users/choikarl/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/choikarl/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle
      (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString
      (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read
      (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer
      (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes
      (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 Pro (mobile) • 9EF2F616-DB7E-4813-BB9B-BC3C3139B3B7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88
    ! Error: 林夕 is not connected. Xcode will continue when 林夕 is connected. (code -13)

[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed out

! Doctor found issues in 4 categories.

</details>

**Comment by darshankawar** [comment] 2022-04-18 07:41
@ChoiKarl 
Not sure if this is a bug or maybe a caching issue at your end. I tried a sample add-2-app on iOS simulator, modified a text in flutter's `main.dart` and ran from XCode which showed updated code as below:

<img width="364" alt="Screenshot 2022-04-18 at 1 09 26 PM" src="https://user-images.githubusercontent.com/67046386/163774347-f299de15-2ee6-4b24-ab06-d8b47eb87b68.png">


```
appBar: AppBar(
        title: const Text('Full-screen Flutter Demo'),
      ),`
```

Earlier the text was `Full-screen Flutter`.

I suggest you to try the samples app and see if you still get same behavior or not.

https://github.com/flutter/samples

**Comment by ChoiKarl** [comment] 2022-04-18 09:10
I have this problem and so do my colleagues.

[Demo.zip](https://github.com/flutter/flutter/files/8504767/Demo.zip)

https://user-images.githubusercontent.com/12951859/163785470-1931ecd5-de4f-4e7d-9637-995d1667d3ab.mp4

**Comment by darshankawar** [comment] 2022-04-19 05:11
@ChoiKarl 
Please try to upgrade to latest stable or master version and see if it still shows the behavior or not.

**Comment by ChoiKarl** [comment] 2022-04-19 07:25
@darshankawar 
Yes, still have the same problem, I tried to upgrade to 2.10.5 also have the problem.

**Comment by darshankawar** [comment] 2022-04-20 05:59
@ChoiKarl 
From the video you shared, you are making changes in Android Studio but trying to run from XCode. Did you try hot restarting from Android Studio itself where you made the changes ?

**Comment by ChoiKarl** [comment] 2022-04-20 06:27
@darshankawar 
If I connect with Flutter Attach and execute hot reset it takes effect.
But I want it to work straight from Xcode.

**Comment by darshankawar** [comment] 2022-04-20 11:50
@ChoiKarl 
Since you are using add2app, it requires you to use `flutter attach` and hot reload to see the updates.
See this related link for your reference: https://docs.flutter.dev/development/add-to-app#add-to-ios-applications

Closing this as using `flutter attach` and hot reloading should work and per your comment. If you disagree, write in comments and I'll reopen it.

**Comment by jmagman** [comment] 2022-04-20 20:29
I think this should be reopened, every time the app is compiled it should also recompile the dart code.  I can see from the recording that's not what's happening, Xcode is running the app but it's not reflecting the dart code edited before the app compiled.

Can you reproduce again, and export your Xcode build logs?
![Screen Shot 2022-04-20 at 1 28 27 PM](https://user-images.githubusercontent.com/682784/164317251-d07f1378-97d4-4dd4-ab69-8e81513b57a7.png)

**Comment by ChoiKarl** [comment] 2022-04-21 02:29
@jmagman 
[log.txt](https://github.com/flutter/flutter/files/8526786/log.txt)

<img width="343" alt="image" src="https://user-images.githubusercontent.com/12951859/164359144-b462bb89-ca4a-4930-9cb7-4324143630a8.png">
I deleted it and re-ran,  it’s OK.

**Comment by jmagman** [comment] 2022-04-21 18:40
> I deleted it and re-ran, it’s OK.

From those logs I see the dart code recompiling, were you reproducing the issue when this happened? 
```
[ +863 ms] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/choikarl/Desktop/-项目/market-flutter/lib/shop_cart/view/item/shop_cart_app_bar.dart}
[   +8 ms] /Users/choikarl/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/choikarl/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/choikarl/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --no-link-platform --packages /Users/choikarl/Desktop/-项目/market-flutter/.dart_tool/package_config.json --output-dill /Users/choikarl/Desktop/-项目/market-flutter/.dart_tool/flutter_build/35f2c5933da9d4a69480d25ea0491bce/app.dill --depfile /Users/choikarl/Desktop/-项目/market-flutter/.dart_tool/flutter_build/35f2c5933da9d4a69480d25ea0491bce/kernel_snapshot.d /Users/choikarl/Desktop/-项目/market-flutter/.dart_tool/flutter_build/generated_main.dart
[+8366 ms] kernel_snapshot: Complete
```

Ideally I need:
1. Run from Xcode, see app run, stop app
2. Change dart code
3. Run again in Xcode, see that the dart code was not updated in the app
4. Export logs.

**Comment by ChoiKarl** [comment] 2022-04-22 02:31
@jmagman 

I have always been able to have problems.

https://user-images.githubusercontent.com/12951859/164584496-8346812b-2029-4572-9fe5-75d5454b54f7.mp4

[log.txt](https://github.com/flutter/flutter/files/8536390/log.txt)

**Comment by jmagman** [comment] 2022-04-22 18:07
Interesting, the code actually is recompiling, but it's not being embedded into the app?
```
[ +409 ms] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/choikarl/Downloads/Test/flutter_module_project/lib/main.dart}
[   +4 ms] /Users/choikarl/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/choikarl/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/choikarl/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --no-link-platform --packages /Users/choikarl/Downloads/Test/flutter_module_project/.dart_tool/package_config.json --output-dill /Users/choikarl/Downloads/Test/flutter_module_project/.dart_tool/flutter_build/2299146171019cc8b5384988fa59ae00/app.dill --depfile /Users/choikarl/Downloads/Test/flutter_module_project/.dart_tool/flutter_build/2299146171019cc8b5384988fa59ae00/kernel_snapshot.d package:flutter_module_project/main.dart
[+3950 ms] kernel_snapshot: Complete
```

**Comment by ChoiKarl** [comment] 2022-04-23 06:36
@jmagman 
yes, it's not embedded into the app.

https://user-images.githubusercontent.com/12951859/164882982-cad059bc-8e9d-49f5-92c2-ec4df0170483.mp4

## build app time.
<img width="827" alt="iShot2022-04-23 14 27 09" src="https://user-images.githubusercontent.com/12951859/164883027-6e3eebbe-60f8-4a0e-adaa-5d1df594d033.png">

## product app.framework time.
<img width="1116" alt="iShot2022-04-23 14 27 48" src="https://user-images.githubusercontent.com/12951859/164883032-be86c263-af96-4968-acd4-105ef24b07a4.png">

**Comment by jmagman** [comment] 2022-04-25 20:32
I was able to reproduce this! The App.framework podspec is pointed to `flutter_module_project/.ios/Flutter/App.framework` but the Flutter tooling is building it subsequent times to the DerivedData products directory `/path/to/DerivedData/project/Build/Products/Debug-iphonesimulator/App.framework`

**Comment by jmagman** [comment] 2022-04-25 21:05
CocoaPods is copying the frameworks from `BUILT_PRODUCTS_DIR` correctly the first time, but the script based in xcfilelist inputs that point to the stale versions in the `.ios` module directory.

**Closed** 2022-05-02 17:44 UTC
Labels: platform-ios, tool, a: existing-apps, t: xcode, P4

**Comment by ChoiKarl** [comment] 2022-05-09 02:48
@jmagman 
How can I solve this problem without upgrading Flutter? My current version is 2.10.3.
