### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by michelsn1** [flutter/flutter#160559] opened 2024-12-19 01:02 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008120-001C609A3452201E --start-paused --flavor=prod --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 15.2 24C101 darwin-arm64, locale en-BR)
    • Flutter version 3.24.1 on channel stable at /Users/michelnassif/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (4 months ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/michelnassif/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/michelnassif/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.94.2)
    • VS Code at /Users/michelnassif/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • iPhone (mobile)                 • 00008120-001C609A3452201E • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.31+40
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7482962148e8d758338d8a28f589f317e1e42ba4
### Plugins
audioplayers-6.1.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.1
audioplayers_windows-4.0.0
firebase_analytics-11.3.6
firebase_analytics_web-0.5.10+5
firebase_auth-5.3.4
firebase_auth_web-5.13.5
firebase_core-3.8.1
firebase_core_web-2.18.2
firebase_crashlytics-4.2.0
firebase_remote_config-5.2.0
firebase_remote_config_web-1.7.5
flutter_native_splash-2.4.3
in_app_review-2.0.10
onesignal_flutter-5.2.8
package_info_plus-8.1.1
path_provider-2.1.5
path_provider_android-2.2.14
path_provider_foundation-2.4.1
path_provider_linux-2.2.1
path_provider_windows-2.3.0
share_plus-10.1.2
shared_preferences-2.3.3
shared_preferences_android-2.3.4
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.2
url_launcher_linux-3.2.1
url_launcher_macos-3.2.2
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
webview_flutter-4.10.0
webview_flutter_android-4.1.0
webview_flutter_wkwebview-3.16.3

**Comment by danagbemava-nc** [comment] 2024-12-19 07:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-12-19 07:42 UTC
Labels: in triage
