### ISSUE TITLE
Flutter Desktop cannot use Visual Studio 2022 Preview 4

### ISSUE THREAD

**Issue by xiao-cao-x** [flutter/flutter#90190] opened 2021-09-16 13:05 UTC
I installed Visual Studio 2022 Preview 4 (the latest version), Flutter Desktop compiled an error saying that Visual Studio 2019 could not be found.

Console output:
```
Building Windows application...
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.



Exception: Unable to generate build files

```

---

`flutter doctor -v`:

```
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on Microsoft Windows [Version 10.0.19043.1149], locale zh-CN)
    • Flutter version 2.6.0-5.2.pre at D:\SDK\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (14 hours ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\SDK\Android
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = D:\SDK\Android
    • Java binary at: D:\IDE\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.0.0 Preview 4.0)
    • Visual Studio at D:\IDE\Microsoft Visual Studio\2022\Preview
    • Visual Studio Enterprise 2022 version 17.0.31710.8
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\IDE\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\IDE\IDEA
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1149]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

**Comment by stuartmorgan** [comment] 2021-09-16 13:21
Duplicate of https://github.com/flutter/flutter/issues/85922

**Closed by stuartmorgan** 2021-09-16 13:21 UTC

**Comment by xiao-cao-x** [comment] 2021-09-16 13:28
@stuartmorgan 
Can I manually specify the Visual Studio version? I now need to compile my Flutter program

**Comment by stuartmorgan** [comment] 2021-09-16 14:08
> Can I manually specify the Visual Studio version?

You could try changing [the generator](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/windows/build_windows.dart#L28) in your local copy, but I have no idea if it would work.

> I now need to compile my Flutter program

If your goal is to build a Flutter application, rather than to work on adding VS 2022 support to Flutter, then the easiest path would be to use the version of VS that is supported by Flutter rather than a preview release.

**Comment by xiao-cao-x** [comment] 2021-09-17 03:55
> You could try changing the generator in your local copy, but I have no idea if it would work.
I tried it to no avail.
I have now downloaded the previously deleted VS2019 back

**Comment by xiao-cao-x** [comment] 2021-09-17 03:55
> > You could try changing the generator in your local copy, but I have no idea if it would work.
 I tried it to no avail.
 I have now downloaded the previously deleted VS2019 back

**Comment by xiao-cao-x** [comment] 2021-09-17 03:55
> You could try changing the generator in your local copy, but I have no idea if it would work.
I tried it to no avail.
I have now downloaded the previously deleted VS2019 back

**Comment by xiao-cao-x** [comment] 2021-09-17 03:56
> > You could try changing the generator in your local copy, but I have no idea if it would work.
I tried it to no avail.
I have now downloaded the previously deleted VS2019 back
