### ISSUE TITLE
FutureBuilder infinitely looping the circular progress indicator

### ISSUE THREAD

**Issue by ohrox97** [flutter/flutter#57010] opened 2020-05-12 15:57 UTC
I am writing a Future getEmail() method to extract the email data from my firebase database and use it in my BottomSheetText to display the email as a string however in the FutureBuilder, the CircularProgressIndicator is infinitely looping without going to the case where the data should be displayed

Here is the code for my getEmail() method:

```
Future<String> getEmail() async {
    String _email = (await FirebaseAuth.instance.currentUser()).email;
    DocumentSnapshot snapshot = await _firestore.collection('users')
      .document(_email)
      .collection('met_with')
      .document('email')
      .get();
    print("data: ${snapshot.data}"); // might be useful to check
    return snapshot.data['email']; // or another key, depending on how it's saved
  }
```
Here is the code that includes my FutureBuilder:

```
@override
  Widget build(BuildContext context) {
    return Card(
      elevation: 3.0,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10.0)),
      child: ListTile(
        leading: CircleAvatar(
          backgroundImage: AssetImage(imagePath),
        ),
        trailing: Icon(Icons.more_horiz),
        title: Text(
          email,
          style: TextStyle(
            color: Colors.deepPurple[700],
            fontWeight: FontWeight.bold,
          ),
        ),
        subtitle: Text(infection),
        onTap: () => showModalBottomSheet(
            context: context,
            builder: (builder) {

              return FutureBuilder(
                future: getEmail(),
                builder: (BuildContext context, snapshot) {
                if(snapshot.hasData){
                  if(snapshot.connectionState == ConnectionState.waiting){
                    return Center(
                      child: CircularProgressIndicator(),
                    );
                  }else{
                    return Padding(padding: EdgeInsets.symmetric(vertical: 50.0, horizontal: 10.0),
                     child: Column(
                  children: <Widget>[
                    BottomSheetText(
                        question: 'Email', result:  snapshot.data['email']),
                    SizedBox(height: 5.0),
                    BottomSheetText(
                        question: 'Contact Time',result:"lol"),// getTimeStamp().toString()),
                    SizedBox(height: 5.0),
                    BottomSheetText(
                        question: 'Contact Location',
                        result: "help"),
                    SizedBox(height: 5.0),
                    BottomSheetText(question: 'Times Contacted', result: "lool",),
                  ],
                  ),


                     );
                  }
                }else{
                  return CircularProgressIndicator();}
                }








                     );




            }
        ),





                ),
              );


```

**Comment by iapicca** [comment] 2020-05-15 11:10
Hi @ohrox97 
for what I can see the issue is related to a FlutterFire plugin,
if so  please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).

otherwise please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and a reproducible minimal code sample
(without 3rd party plugins)
Thank you

**Comment by iapicca** [comment] 2020-06-05 12:58
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-06-05 12:58 UTC
Labels: in triage, waiting for customer response
