### ISSUE TITLE
the assembly for windows does not work

### ISSUE THREAD

**Issue by polina1441** [flutter/flutter#105231] opened 2022-06-02 16:03 UTC
```
`Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab...
Expanding downloaded archive...
Building flutter tool...
Running pub upgrade...
Upgrading Flutter to 3.0.1 from 2.10.4 in D:\flutter_windows_2.10.4-stable\flutter...
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine caaafc5604ee9172293eb84a381be6aadd660317... 
Expanding downloaded archive...
Building flutter tool... 
Running pub upgrade... 

Upgrading engine...
Downloading android-arm-profile/windows-x64 tools...             2 236ms
Downloading android-arm-release/windows-x64 tools...             1 682ms
Downloading android-arm64-profile/windows-x64 tools...              4,3s
Downloading android-arm64-release/windows-x64 tools...           1 900ms
Downloading android-x64-profile/windows-x64 tools...                5,8s
Downloading android-x64-release/windows-x64 tools...             2 914ms
Downloading android-x86 tools...                                   14,5s
Downloading android-x64 tools...                                   13,6s
Downloading android-arm tools...                                   11,3s
Downloading android-arm-profile tools...                            6,8s
Downloading android-arm-release tools...                            4,6s
Downloading android-arm64 tools...                                 17,8s
Downloading android-arm64-profile tools...                         14,5s
Downloading android-arm64-release tools...                          5,2s
Downloading android-x64-profile tools...                            7,1s
Downloading android-x64-release tools...                            4,8s
Downloading android-x86-jit-release tools...                        7,9s
Downloading Web SDK...                                             29,2s
Downloading CanvasKit...                                            7,8s
Downloading package sky_engine...                                  941ms
Downloading flutter_patched_sdk tools...                         2 849ms
Downloading flutter_patched_sdk_product tools...                    3,3s
Downloading windows-x64 tools...                                   23,3s
Downloading windows-x64/windows-x64-flutter tools...               83,7s
Downloading windows-x64/flutter-cpp-client-wrapper tools...        450ms
Downloading windows-x64-profile/windows-x64-flutter tools...        68,8s
Downloading windows-x64-release/windows-x64-flutter tools...        74,4s
Downloading windows-x64/font-subset tools...                     1 411ms

Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (2 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.675], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please le
t us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: [
        {
          "instanceId": "893c2f0e",
          "installDate": "2022-06-01T14:01:34Z",
          "installationName": "VisualStudio/16.11.15+32510.428",
          "installationPath": "D:\\ProgramData\\Microsoft\\2019",
          "installationVersion": "16.11.32510.428",
          "productId": "Microsoft.VisualStudio.Product.Community",
          "productPath": "D:\\ProgramData\\Microsoft\\2019\\Common7\\IDE\\devenv.exe",
          "state": 4294967295,
          "isComplete": true,
          "isLaunchable": true,
          "isPrerelease": false,
          "isRebootRequired": false,
          "displayName": "Visual Studio Community 2019",
          "description": "  魠    ⥣ ஢       ।  ࠧࠡ ⪨,   ᯫ ⭠        㤥 ⮢,    ⭨     ஥ ⮢                   ⤥      
  짮  ⥫  .",
          "channelId": "VisualStudio.16.Release",
          "channelUri": "https://aka.ms/vs/16/release/channel",
          "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceH
ub\\Services\\Microsoft.VisualStudio.Setup.Service",
          "installedChannelUri": "https://aka.ms/vs/16/release/channel",
          "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.11#16
.11.15",
          "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
          "updateDate": "2022-06-01T14:01:34.3310683Z",
          "catalog": {
            "buildBranch": "d16.11",
            "buildVersion": "16.11.32510.428",
            "id": "VisualStudio/16.11.15+32510.428",
            "localBuild": "build-lab",
            "manifestName": "VisualStudio",
            "manifestType": "installer",
            "productDisplayVersion": "16.11.15",
            "productLine": "Dev16",
            "productLineVersion": "2019",
            "productMilestone": "RTW",
            "productMilestoneIsPreRelease": "False",
            "productName": "Visual Studio",
            "productPatchVersion": "15",
            "productPreReleaseMilestoneSuffix": "1.0",
            "productSemanticVersion": "16.11.15+32510.428",
            "requiredEngineVersion": "2.11.69.53063"
          },
          "properties": {
            "campaignId": "2030:aa746086-e7f9-4a79-ba08-e894351c7179",
            "channelManifestId": "VisualStudio.16.Release/16.11.15+32510.428",
            "nickname": "",
            "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
          }
        }
      ]
      . The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doi
ng when this happened:
      https://github.com/flutter/flutter/issues/new/choose
      The source bytes were:
      [91, 13, 10, 32, 32, 123, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 110, 99, 101, 73, 100, 34,
 58, 32, 34, 56, 57, 51, 99, 50, 102, 48, 101, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108
, 108, 68, 97, 116, 101, 34, 58, 32, 34, 50, 48, 50, 50, 45, 48, 54, 45, 48, 49, 84, 49, 52, 58, 48, 49, 58, 5
1, 52, 90, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 78, 9
7, 109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 47, 49, 54, 46, 49, 49,
46, 49, 53, 43, 51, 50, 53, 49, 48, 46, 52, 50, 56, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97
, 108, 108, 97, 116, 105, 111, 110, 80, 97, 116, 104, 34, 58, 32, 34, 68, 58, 92, 92, 80, 114, 111, 103, 114,
97, 109, 68, 97, 116, 97, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 92, 92, 50, 48, 49, 57, 34, 44, 1
3, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 86, 101, 114, 115, 105, 1
11, 110, 34, 58, 32, 34, 49, 54, 46, 49, 49, 46, 51, 50, 53, 49, 48, 46, 52, 50, 56, 34, 44, 13, 10, 32, 32, 3
2, 32, 34, 112, 114, 111, 100, 117, 99, 116, 73, 100, 34, 58, 32, 34, 77, 105, 99, 114, 111, 115, 111, 102, 11
6, 46, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 80, 114, 111, 100, 117, 99, 116, 46, 67, 1
11, 109, 109, 117, 110, 105, 116, 121, 34, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 8
0, 97, 116, 104, 34, 58, 32, 34, 68, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 68, 97, 116, 97, 92, 92, 77,
 105, 99, 114, 111, 115, 111, 102, 116, 92, 92, 50, 48, 49, 57, 92, 92, 67, 111, 109, 109, 111, 110, 55, 92, 9
2, 73, 68, 69, 92, 92, 100, 101, 118, 101, 110, 118, 46, 101, 120, 101, 34, 44, 13, 10, 32, 32, 32, 32, 34, 11
5, 116, 97, 116, 101, 34, 58, 32, 52, 50, 57, 52, 57, 54, 55, 50, 57, 53, 44, 13, 10, 32, 32, 32, 32, 34, 105,
 115, 67, 111, 109, 112, 108, 101, 116, 101, 34, 58, 32, 116, 114, 117, 101, 44, 13, 10, 32, 32, 32, 32, 34, 1
05, 115, 76, 97, 117, 110, 99, 104, 97, 98, 108, 101, 34, 58, 32, 116, 114, 117, 101, 44, 13, 10, 32, 32, 32,
32, 34, 105, 115, 80, 114, 101, 114, 101, 108, 101, 97, 115, 101, 34, 58, 32, 102, 97, 108, 115, 101, 44, 13,
10, 32, 32, 32, 32, 34, 105, 115, 82, 101, 98, 111, 111, 116, 82, 101, 113, 117, 105, 114, 101, 100, 34, 58, 3
2, 102, 97, 108, 115, 101, 44, 13, 10, 32, 32, 32, 32, 34, 100, 105, 115, 112, 108, 97, 121, 78, 97, 109, 101,
 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 32, 67, 111, 109, 109, 117, 110,
 105, 116, 121, 255, 50, 48, 49, 57, 34, 44, 13, 10, 32, 32, 32, 32, 34, 100, 101, 115, 99, 114, 105, 112, 116
, 105, 111, 110, 34, 58, 32, 34, 140, 174, 233, 173, 160, 239, 32, 168, 173, 226, 165, 163, 224, 168, 224, 174
, 162, 160, 173, 173, 160, 239, 32, 225, 224, 165, 164, 160, 32, 224, 160, 167, 224, 160, 161, 174, 226, 170,
168, 44, 32, 161, 165, 225, 175, 171, 160, 226, 173, 160, 239, 32, 164, 171, 239, 32, 225, 226, 227, 164, 165,
 173, 226, 174, 162, 44, 32, 227, 231, 160, 225, 226, 173, 168, 170, 174, 162, 32, 175, 224, 174, 165, 170, 22
6, 174, 162, 32, 225, 32, 174, 226, 170, 224, 235, 226, 235, 172, 32, 170, 174, 164, 174, 172, 32, 168, 32, 17
4, 226, 164, 165, 171, 236, 173, 235, 229, 32, 175, 174, 171, 236, 167, 174, 162, 160, 226, 165, 171, 165, 169
, 46, 34, 44, 13, 10, 32, 32, 32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 73, 100, 34, 58, 32, 34, 86, 105, 1
15, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 49, 54, 46, 82, 101, 108, 101, 97, 115, 101, 34, 44, 13, 10
, 32, 32, 32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 85, 114, 105, 34, 58, 32, 34, 104, 116, 116, 112, 115,
58, 47, 47, 97, 107, 97, 46, 109, 115, 47, 118, 115, 47, 49, 54, 47, 114, 101, 108, 101, 97, 115, 101, 47, 99,
 104, 97, 110, 110, 101, 108, 34, 44, 13, 10, 32, 32, 32, 32, 34, 101, 110, 103, 105, 110, 101, 80, 97, 116, 1
04, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 32, 40, 120,
56, 54, 41, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 11
7, 100, 105, 111, 92, 92, 73, 110, 115, 116, 97, 108, 108, 101, 114, 92, 92, 114, 101, 115, 111, 117, 114, 99,
 101, 115, 92, 92, 97, 112, 112, 92, 92, 83, 101, 114, 118, 105, 99, 101, 72, 117, 98, 92, 92, 83, 101, 114, 1
18, 105, 99, 101, 115, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 86, 105, 115, 117, 97, 108, 83,
116, 117, 100, 105, 111, 46, 83, 101, 116, 117, 112, 46, 83, 101, 114, 118, 105, 99, 101, 34, 44, 13, 10, 32,
32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 101, 100, 67, 104, 97, 110, 110, 101, 108, 85, 114, 105, 34,
 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 97, 107, 97, 46, 109, 115, 47, 118, 115, 47, 49, 54, 47, 114
, 101, 108, 101, 97, 115, 101, 47, 99, 104, 97, 110, 110, 101, 108, 34, 44, 13, 10, 32, 32, 32, 32, 34, 114, 1
01, 108, 101, 97, 115, 101, 78, 111, 116, 101, 115, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 100,
111, 99, 115, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 101, 110, 45, 117, 115, 47
, 118, 105, 115, 117, 97, 108, 115, 116, 117, 100, 105, 111, 47, 114, 101, 108, 101, 97, 115, 101, 115, 47, 50
, 48, 49, 57, 47, 114, 101, 108, 101, 97, 115, 101, 45, 110, 111, 116, 101, 115, 45, 118, 49, 54, 46, 49, 49,
35, 49, 54, 46, 49, 49, 46, 49, 53, 34, 44, 13, 10, 32, 32, 32, 32, 34, 116, 104, 105, 114, 100, 80, 97, 114,
116, 121, 78, 111, 116, 105, 99, 101, 115, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 103, 111, 46,
109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 102, 119, 108, 105, 110, 107, 47, 63, 76, 10
5, 110, 107, 73, 100, 61, 54, 54, 48, 57, 48, 57, 34, 44, 13, 10, 32, 32, 32, 32, 34, 117, 112, 100, 97, 116,
101, 68, 97, 116, 101, 34, 58, 32, 34, 50, 48, 50, 50, 45, 48, 54, 45, 48, 49, 84, 49, 52, 58, 48, 49, 58, 51,
 52, 46, 51, 51, 49, 48, 54, 56, 51, 90, 34, 44, 13, 10, 32, 32, 32, 32, 34, 99, 97, 116, 97, 108, 111, 103, 3
4, 58, 32, 123, 13, 10, 32, 32, 32, 32, 32, 32, 34, 98, 117, 105, 108, 100, 66, 114, 97, 110, 99, 104, 34, 58,
 32, 34, 100, 49, 54, 46, 49, 49, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 98, 117, 105, 108, 100, 86, 101,
 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 54, 46, 49, 49, 46, 51, 50, 53, 49, 48, 46, 52, 50, 56, 34, 44,
13, 10, 32, 32, 32, 32, 32, 32, 34, 105, 100, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 1
05, 111, 47, 49, 54, 46, 49, 49, 46, 49, 53, 43, 51, 50, 53, 49, 48, 46, 52, 50, 56, 34, 44, 13, 10, 32, 32, 3
2, 32, 32, 32, 34, 108, 111, 99, 97, 108, 66, 117, 105, 108, 100, 34, 58, 32, 34, 98, 117, 105, 108, 100, 45,
108, 97, 98, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 109, 97, 110, 105, 102, 101, 115, 116, 78, 97, 109, 1
01, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 34, 44, 13, 10, 32, 32, 32, 32, 3
2, 32, 34, 109, 97, 110, 105, 102, 101, 115, 116, 84, 121, 112, 101, 34, 58, 32, 34, 105, 110, 115, 116, 97, 1
08, 108, 101, 114, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 68, 105, 115,
 112, 108, 97, 121, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 54, 46, 49, 49, 46, 49, 53, 34, 44,
13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 76, 105, 110, 101, 34, 58, 32, 34, 68, 1
01, 118, 49, 54, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 76, 105, 110, 1
01, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 50, 48, 49, 57, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32,
34, 112, 114, 111, 100, 117, 99, 116, 77, 105, 108, 101, 115, 116, 111, 110, 101, 34, 58, 32, 34, 82, 84, 87,
34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 77, 105, 108, 101, 115, 116, 111
, 110, 101, 73, 115, 80, 114, 101, 82, 101, 108, 101, 97, 115, 101, 34, 58, 32, 34, 70, 97, 108, 115, 101, 34,
 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 78, 97, 109, 101, 34, 58, 32, 34, 8
6, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 1
14, 111, 100, 117, 99, 116, 80, 97, 116, 99, 104, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 53, 34
, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 80, 114, 101, 82, 101, 108, 101, 9
7, 115, 101, 77, 105, 108, 101, 115, 116, 111, 110, 101, 83, 117, 102, 102, 105, 120, 34, 58, 32, 34, 49, 46,
48, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 83, 101, 109, 97, 110, 116,
105, 99, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 54, 46, 49, 49, 46, 49, 53, 43, 51, 50, 53, 49,
 48, 46, 52, 50, 56, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 114, 101, 113, 117, 105, 114, 101, 100, 69, 1
10, 103, 105, 110, 101, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 50, 46, 49, 49, 46, 54, 57, 46, 53,
51, 48, 54, 51, 34, 13, 10, 32, 32, 32, 32, 125, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 112, 101, 114,
 116, 105, 101, 115, 34, 58, 32, 123, 13, 10, 32, 32, 32, 32, 32, 32, 34, 99, 97, 109, 112, 97, 105, 103, 110,
 73, 100, 34, 58, 32, 34, 50, 48, 51, 48, 58, 97, 97, 55, 52, 54, 48, 56, 54, 45, 101, 55, 102, 57, 45, 52, 97
, 55, 57, 45, 98, 97, 48, 56, 45, 101, 56, 57, 52, 51, 53, 49, 99, 55, 49, 55, 57, 34, 44, 13, 10, 32, 32, 32,
 32, 32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 77, 97, 110, 105, 102, 101, 115, 116, 73, 100, 34, 58, 32, 3
4, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 49, 54, 46, 82, 101, 108, 101, 97, 115, 101, 4
7, 49, 54, 46, 49, 49, 46, 49, 53, 43, 51, 50, 53, 49, 48, 46, 52, 50, 56, 34, 44, 13, 10, 32, 32, 32, 32, 32,
 32, 34, 110, 105, 99, 107, 110, 97, 109, 101, 34, 58, 32, 34, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 115
, 101, 116, 117, 112, 69, 110, 103, 105, 110, 101, 70, 105, 108, 101, 80, 97, 116, 104, 34, 58, 32, 34, 67, 58
, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41, 92, 92, 77, 10
5, 99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92, 92,
73, 110, 115, 116, 97, 108, 108, 101, 114, 92, 92, 115, 101, 116, 117, 112, 46, 101, 120, 101, 34, 13, 10, 32,
 32, 32, 32, 125, 13, 10, 32, 32, 125, 13, 10, 93, 13, 10]


[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
`



```

**Comment by darshankawar** [comment] 2022-06-03 05:49
Closing as duplicate of https://github.com/flutter/flutter/issues/102451. Please see workaround / temporary solution mentioned in it.

**Closed by darshankawar** 2022-06-03 05:49 UTC
Labels: in triage
