### ISSUE TITLE
Google Maps onCameraIdle not working in iOS when in a Stack.

### ISSUE THREAD

**Issue by leen-nobbas** [flutter/flutter#33988] opened 2019-06-06 17:22 UTC
## Steps to Reproduce

I have a layout where in a Stack I have a `GoogleMap`, a `GestureDetector` on top of it that currently absorbs all the taps and doesn't pass it to the `GoogleMap`. Once tapped, `GestureDetector` allows the taps to be passed onto `GoogleMap`.
Problem is, whenever I make this kind of layout, the `onCameraIdle` callback is not being called in `iOS` (works in `Android`). Double tapping the map or tapping on a marker somehow resets the callback, but it doesn't work the first time.

```dart
class FancyMapPageState extends State<FancyMapPage> {

  ...

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        GoogleMap(
        ...
        ),
        GestureDetector(
          behavior: !_animationController.isCompleted
              ? HitTestBehavior.opaque
              : HitTestBehavior.deferToChild,
          onTap: () {
            _animationController.forward();
          },
        ),
        SlideTransition(
          position: _cardSlideAnimation,
          Container(
            child: ...,
          ),
        ),
      ],
    );
  }
}

```

## Logs

```
No issues found! (ran in 5.9s)
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at /Users/gurleensethi/Documents/Flutter/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gurleensethi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7830

[✓] VS Code (version 1.35.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • Gurleen’s iPhone • 2e3ceb53501346b6a4d1b2e0ac2abf9850737cc5 • ios • iOS 12.3.1

• No issues found!
```

@iskakaushik Could you please look into this, thanks in advance :)

Edit by cyanglaz:
internal b/144584399

**Comment by leen-nobbas** [comment] 2019-06-06 22:00
A complete sample example:

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Maps Test",
      home: MapTestWidget(),
    );
  }
}

class MapTestWidget extends StatefulWidget {
  @override
  _MapTestWidgetState createState() => _MapTestWidgetState();
}

class _MapTestWidgetState extends State<MapTestWidget> {
  bool _isOpen = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          _buildMap(),
          _buildTranslucent(),
          _buildSampleCard(),
        ],
      ),
    );
  }

  Widget _buildSampleCard() {
    return Positioned(
      bottom: 0.0,
      right: 0.0,
      left: 0.0,
      child: Transform.translate(
        offset: _isOpen ? Offset.zero : Offset(0.0, 400.0),
        child: Container(
          height: 400.0,
          color: Colors.red,
        ),
      ),
    );
  }

  Widget _buildTranslucent() {
    return GestureDetector(
      behavior: _isOpen ? HitTestBehavior.opaque : HitTestBehavior.deferToChild,
      onTap: () {
        setState(() {
          _isOpen = false;
        });
      },
      child: Container(),
    );
  }

  Widget _buildMap() {
    return GoogleMap(
      initialCameraPosition: CameraPosition(
        target: LatLng(25.7617, -80.1918),
        zoom: 16.0,
      ),
      //markers: _markers.values.toSet(),
      onCameraIdle: () {
        print("Camera Idle1");
        print("Camera Idle2");
      },
      onMapCreated: (controller) {},
    );
  }
}

```

**Comment by MorochoRochaDarwin** [comment] 2019-06-29 23:45
I have the same problem

**Comment by ludowkm** [comment] 2019-07-04 08:49
I also met this problem, any suggestion ?

**Comment by droidpl** [comment] 2019-07-27 18:27
Same problem here. This is critical to do thing on camera movement that require an await, as there is no other callback to do this

**Comment by ludowkm** [comment] 2019-07-29 01:09
I overcome it by a workaround, on **onCameraMove**, i make a delay subscription 150 milliseconds then the result will be onCameraIdle, but before subscribe it, do cancelling first because onCameraMove will be call multiple times before. Like the below:
`onCameraMove: (newPosition) {
          _mapIdleSubscription?.cancel();
          _mapIdleSubscription = Future.delayed(Duration(milliseconds: 150))
              .asStream()
              .listen((_) => _onCameraIdle());
}`

**Comment by papalardo** [comment] 2019-08-21 23:24
I have the same problem, but when I move List on de Map

**Comment by DennisKragekjaer** [comment] 2019-08-26 18:44
Same issue here. Its becoming worrying how many problems there is with google maps/ platform views.
I have same structure as you, with a button on top of Google maps. When I press the button every stops working, no onIdle and so on. When I tap a marker or double tap the maps, it is working again, until I press the button.

**Comment by idompolo** [comment] 2019-08-27 23:55
Update the camera using mapController for button click event.

example)

  FlatButton(
                      child: Text(
                        'Next',
                        style: TextStyle(
                          fontSize: 24,
                        ),
                      ),
                      onPressed: () {
                        mapController.animateCamera(
                          CameraUpdate.zoomTo(16)
                        );
                      },
                    )

**Comment by dipendra-sharma** [comment] 2019-12-11 17:22
Any solution for this?

**Comment by amirh** [comment] 2019-12-30 22:17
cc @cyanglaz

**Comment by cyanglaz** [comment] 2020-01-16 19:54
updates:
Our [DelayingGestureRecognizer](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L515) mechanism doesn't seem to prevent other gestures to receive touch events. I google map implemented `touchesBegan` and `touchesEnded` in their gesture recognizer, and our [`blockGesture`](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L568-L570) is called after touchesBegan loop but before touchesEnded loop, it would result google map's gesture recognizer receive only touchesBegan calls but not touchesEnded calls. Which then results some unwanted behavior if the google map is relying on both calls to be called. (For example, a bool value is set in began and unset in ended.)

Note that sometimes, the `blockGestures` took a while to happen and the touchesEnded loop has already started, then the google map will get both callback. And in this case, it seems working well.

**Comment by cyanglaz** [comment] 2020-01-21 21:29
updates:
We identified a potential fix which is delaying the `blockGesture` call after `touchesEnded` in the DelayingGestureRecognizer.
We will make this new behavior configurable and the google map plugin will use the new behavior as our white mouse.

Testing for this is tricky as it seems that we will need to add a framework side integration test.

My plan is to add the test on the framework side first, then land the fix in engine.

**Comment by cyanglaz** [comment] 2020-02-11 23:38
The engine fix for this issue is merged. After the change goes into stable, I will update the plugin then the issue should be completely fixed. Thank you all for the patients. I am also going to postpone the milestone a bit, since we need to wait until the engine fix goes into stable.

**Comment by DennisKragekjaer** [comment] 2020-02-13 11:28
@cyanglaz The onCameraIdle is **NOT** fixed. I have a button on top the google map, in a Stack. First the idle works. **BUT** as soon as I tap the button the onCameraIdle is not working anymore.

I also noticed another thing regarding Google maps in Flutter that is even more critical:
Again I have a button on top of the map in a Stack. When tapping the button I will change the mapType. When doing this several times, I see some of the UI (Not on top of the map) turning into black squares!!

**Comment by cyanglaz** [comment] 2020-02-13 17:18
@DennisKragekjaer The onCameraIdle is not fixed yet. We are waiting for the engine fix to roll into stable before introduce the fix in the plugin.

Could you raise another issue with detail description for the second bug that you mentioned? Thank you in advance!

**Comment by goderbauer** [comment] 2020-02-19 00:42
Looks like there's no b/ bug attached to this. Removing customer: google and critical labels.

**Comment by cyanglaz** [comment] 2020-02-19 21:55
@goderbauer I am going to attaching the b/ bug and relabel it.

**Comment by TimG38** [comment] 2020-03-18 17:00
If it's any help, here's some additional information on how to reproduce it:

`google_maps_flutter: ^0.5.24+1`

```
class _MyHomePageState extends State<MyHomePage> {
  GoogleMapController mapController;

  final LatLng _center = const LatLng(45.521563, -122.677433);

  void _onMapCreated(GoogleMapController controller) {
    mapController = controller;
  }

  bool isCameraMoving;

  @override
  void initState() {
    super.initState();
    isCameraMoving = false;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Maps POC App'),
        ),
        body: Stack(
          children: <Widget>[
            GoogleMap(
              onMapCreated: _onMapCreated,
              initialCameraPosition: CameraPosition(
                target: _center,
                zoom: 11.0,
              ),
              onCameraMove: (CameraPosition cameraPosition) {
                setState(() {
                  isCameraMoving = true;
                });
              },
              onCameraIdle: () {
                setState(() {
                  isCameraMoving = false;
                });
              },
            ),
            Positioned(
              top: 0,
              left: 0,
              right: 0,
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Container(
                  alignment: Alignment.center,
                  color: Colors.cyan,
                  height: 200,
                  width: MediaQuery.of(context).size.width,
                  child: Text(
                    'Camera moving: $isCameraMoving',
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 24, color: Colors.white),
                  ),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

1. Move the map location, bool value keeps changing. 
2. Tap on the container anywhere. 
3. Now again move the map. 
4. bool value does not change.(onCameraIdle() not working).

**Comment by masewo** [comment] 2020-04-13 08:24
@cyanglaz Can you please push your solution to a branch so that we do not have to wait for the engine fix to hit stable?

**Comment by asksage** [comment] 2020-04-25 13:15
I just wrote a CustomPanGestureDetector that doesn't fully consume events (tested on iOS Simulator). I hope this helps:

[https://github.com/asksage/rawFiles/blob/master/custom_pan_detector.dart](url)

Wrap your GoogleMap widget like this:

`RawGestureDetector(
      gestures: <Type, GestureRecognizerFactory>{
        CustomPanGestureDetector:
            GestureRecognizerFactoryWithHandlers<CustomPanGestureDetector>(
          () => CustomPanGestureDetector(
            onPanStart: _onDown,
            onPanEnd: _onUp,
          ),
          (CustomPanGestureDetector instance) {},
        ),
      },
      child: GoogleMap`

**Comment by asksage** [comment] 2020-04-25 13:25
> I just wrote a CustomPanGestureDetector that doesn't fully consume events (tested on iOS Simulator). I hope this helps:
> 
> [https://github.com/asksage/rawFiles/blob/master/custom_pan_detector.dart](url)
> 
> Wrap your GoogleMap widget like this:
> 
> `RawGestureDetector( gestures: <Type, GestureRecognizerFactory>{ CustomPanGestureDetector: GestureRecognizerFactoryWithHandlers<CustomPanGestureDetector>( () => CustomPanGestureDetector( onPanStart: _onDown, onPanEnd: _onUp, ), (CustomPanGestureDetector instance) {}, ), }, child: GoogleMap`

Please, note I am not returning event.position in the callbacks (so add that if you need it) because I just wrote this to test the concept.

**Comment by MarcinusX** [comment] 2020-04-30 05:25
@asksage solution didn't solve the problem for me.

I've put @TimG38 code to gist: https://gist.github.com/MarcinusX/97230719f58e6835b0761f369d88b608
The bug still occurs on version `0.5.27`. Tested on simulator iPhone11

![ezgif com-video-to-gif (13)](https://user-images.githubusercontent.com/16286046/80674972-9e6dda80-8ab3-11ea-87a1-a6d5f7e3cc3c.gif)

**Comment by baldwizard** [comment] 2020-05-05 22:16
I stumbled on this issue today.  I thought about a simple workaround that might be helpful in some cases (although i am sure it doesn't solve every case ... ). The idea is rather simple - keep track of the last position to which camera got moved :
- onCameraMove: (CameraPosition position) {lastLatLng = position.target;},
- and after clicking some button located on the Stack widget -> execute:  _controller.moveCamera(CameraUpdate.newLatLng(lastLatLng)) 
- this will "move" camera to the last position and also issue onCameraMoveStarted, onCameraMove and onCameraMoveIdle events. 

The good thing is that it will reset reading events by google maps widget back to normal the bad side is that it will create few unwanted events.

**Comment by baldwizard** [comment] 2020-05-06 09:28
Btw. you can restrict issuing .moveCamera events to minimum by checking if onCameraMove event ended with onCameraIdle event:
- onCameraMove: (CameraPosition position) {lastLatLng = position.target; isMoveTerimanted = false},
- onCameraIdle: () => isMoveTerminated = true
- onTap (in some button on Stack) : () { if(!isMoveTerminated) _controller.moveCamera(CameraUpdate.newLatLng(lastLatLng)) }

It should issue only when onCameraMove event doesn't get terminated with onCameraIdle event.

**Comment by cyanglaz** [comment] 2020-05-12 23:16
This issue has been fixed in https://github.com/flutter/plugins/pull/2746
Please update the plugin to 0.5.27+3 to apply the fix.
I'm closing the issue.

**Closed by cyanglaz** 2020-05-12 23:16 UTC
Labels: a: platform-views, customer: google, p: maps, platform-ios, plugin
