### ISSUE TITLE
[flutter doctor] Could not determine java version with JDK 21

### ISSUE THREAD

**Issue by mohabmetwalli** [flutter/flutter#135402] opened 2023-09-25 06:15 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run an Arch-based Linux distribution.
2. Install `jdk-openjdk` and its dependencies.
3. Install `flutter` using the official `.tar`

### Actual results

In #134333, I was instructed to open a new issue after making sure Java is properly installed. I made sure `java --version` successfully executes (output included in logs); furthermore, it's evident in the output of `flutter doctor --verbose` that `flutter` detects the java binary, and can successfully run `java --version` but fails to parse the output.

### Logs

<details>
<summary>Logs</summary>

 `java --version`:

```console
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)
```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Could not parse java version from:
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)

If there is a version please look for an existing bug
https://github.com/flutter/flutter/issues/ and if one does not exist
file a new issue.
[✓] Flutter (Channel stable, 3.13.5, on Artix Linux 6.5.4-artix2-1,
    locale en_US.utf8)
    • Flutter version 3.13.5 on channel stable at
      /home/mohab/.local/share/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (5 days ago), 2023-09-19 13:56:11
      -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK
    version 34.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome
      executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt
      install clang), or can be downloaded from
      https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt
      install cmake), or can be downloaded from
      https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt
      install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-setu
      p for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Artix Linux
      6.5.4-artix2-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

```

</details>

**Comment by kiisi** [comment] 2023-09-25 10:06
I am currently facing this issue when i run flutter doctor
I installed JDK 21
`
Doctor summary (to see all details, run flutter doctor -v):
Could not parse java version from:
java 21 2023-09-19 LTS
Java(TM) SE Runtime Environment (build 21+35-LTS-2513)
Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not
exist file a new issue.
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.19045.3448], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X Could not determine java version
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (not installed)
[√] VS Code (version 1.82.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 3 categories.
`

Any fix for this please

**Comment by huycozy** [comment] 2023-09-25 12:01
Thanks for filing a separate issue. Looking at both `flutter doctor` outputs above, I notice Android Studio hasn't been installed yet. Maybe the issue can be solved if you install it. Can you try to see if it helps?

**Comment by darshankawar** [comment] 2023-09-26 05:49
@mohabmetwalli 
Check [this](https://stackoverflow.com/questions/75114124/flutter-doctor-unable-to-find-bundled-java-version-android-studio-electric-eel) link and see if it helps to answer your question.

**Comment by kiisi** [comment] 2023-09-26 08:02
Finally fixed this issues by installing JDK 17

**Comment by mohabmetwalli** [comment] 2023-09-26 11:56
Removing Android Studio, installing JDK 17, and running `sudo archlinux-java set java-17-openjdk` fixed it for me too. It seems `flutter` has a problem with JDK 21, for some reason.

**Comment by huycozy** [comment] 2023-09-27 05:46
Thanks for the update. I just installed JDK 21 and now I can reproduce this issue. This is how I reproduce the issue:

### Steps to reproduce

#### 1. Find the Java version Flutter is using currently 
- Check current available Java versions on system
```console
  Selection    Path                                          Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/jdk-21-oracle-x64/bin/javac       352321536 auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/javac   1111      manual mode
  2            /usr/lib/jvm/java-17-openjdk-amd64/bin/javac   1711      manual mode
  3            /usr/lib/jvm/jdk-21-oracle-x64/bin/javac       352321536 manual mode
```
- Check the current Java version used by Flutter
```console
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-31, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.
```
Flutter currently uses Java 11. It prioritizes Android Studio's Java version first. If it's not found, then it will rely on `JAVA_HOME` path (see https://github.com/flutter/flutter/issues/106416#issuecomment-1522198064). 

Also, check Android Studio Java version as well for sure:
```console
huynq@ubuntu:~/Documents/android-studio/jre/bin$ ./java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
OpenJDK 64-Bit Server VM (build 11.0.11+0-b60-7590822, mixed mode)
```

So it is. Flutter is using Android Studio java binary. 

#### 2. Reproduce the issue with Java JDK 21

I will intentionally break Android Studio config so Flutter will seek Java in `JAVA_HOME`:

```console
flutter config --android-studio-dir=/
````

Set JAVA_HOME to JDK 21:

```console
export JAVA_HOME=/usr/lib/jvm/jdk-21-oracle-x64
```

Check Flutter doctor and see the issue appears:

```console
huynq@ubuntu:~/Documents/android-studio/jre/bin$ flutter doctor -v
Could not parse java version from: 
java 21 2023-09-19 LTS
Java(TM) SE Runtime Environment (build 21+35-LTS-2513)
Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)
...
```

The issue doesn't happen if I switch to Java 11 or Java 17. Reproduced this issue on the latest Flutter stable/master channels.

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.5, on Ubuntu 22.04.3 LTS 6.2.0-32-generic, locale en_US.UTF-8)
    • Flutter version 3.13.5 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (7 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-31, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.82.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-32-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.15.0-10.0.pre.12, on Ubuntu 22.04.3 LTS 6.2.0-32-generic, locale en_US.UTF-8)
    • Flutter version 3.15.0-10.0.pre.12 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bea63d7c81 (5 hours ago), 2023-09-26 20:46:25 -0400
    • Engine revision 0a8ad236e4
    • Dart version 3.2.0 (build 3.2.0-199.0.dev)
    • DevTools version 2.28.0-dev.12
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-31, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.82.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-32-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by Sparks1998** [comment] 2023-10-19 08:56
I solved the problem without the android studio it turns out that flutter android tool chain doesn't currently suppor java 21 so all you need is to install another version of java for me it was java 17 that worked.

**Comment by stuartmorgan** [comment] 2023-10-19 14:07
@reidbaker It looks like the format of the version string has changed, and we are expecting at least one `.` in the version.

**Comment by stuartmorgan** [comment] 2023-10-19 16:57
There's a sneaky note at the end:
> The version string doesn't have trailing zero elements. For example, if the value of $FEATURE is 21, the value of $INTERIM is 0, the value of $UPDATE is 1, and the value of $PATCH is 0, then the full version string is 21.0.1.

**Comment by WGinit** [comment] 2023-10-20 04:10
Check system environment variables and restart

**Comment by vmlinuz** [comment] 2023-10-20 11:33
Just encountered this issue, agree with @reidbaker . In `packages/flutter_tools/lib/src/android/java.dart` in the flutter repo, in checking the JDK version string, the following code was found:
```
// The contents that matter come in the format '11.0.18' or '1.8.0_202'.
final RegExp jdkVersionRegex = RegExp(r'\d+\.\d+(\.\d+(?:_\d+)?)?');
```
SInce I see the `java 21 2023-09-19 LTS` string when executing the `java --version`, the code above should be fixed.

**Comment by reidbaker** [comment] 2023-11-09 16:44
The fast mitigation for someone hitting this issue is to use the version of java shipped with android studio by using the android studio config. If you do not wish to install android studio then set java home to a version of java that is supported by the android tooling. 

Additionally as of today java 21 has a patch version java 21.0.1 https://www.oracle.com/java/technologies/downloads/#jdk21-mac which avoids this bug.

**Comment by Lasslos** [comment] 2023-11-20 13:44
I still get the issue on the master branch:

```console
    ~  java -version                                                                                                                                                                                       ✔ 
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)
    ~  flutter doctor -v                                                                                                                                                                                   ✔ 
Could not parse java version from: 
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not exist file a new issue.
[✓] Flutter (Channel master, 3.17.0-10.0.pre.42, on Manjaro Linux 6.1.62-1-MANJARO, locale de_DE.UTF-8)
    • Flutter version 3.17.0-10.0.pre.42 on channel master at /home/lasloh/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e9de448420 (vor 11 Stunden), 2023-11-17 02:08:13 +0100
    • Engine revision 5064aeff00
    • Dart version 3.3.0 (build 3.3.0-143.0.dev)
    • DevTools version 2.30.0-dev.4

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/lasloh/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /home/lasloh/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 76.3.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Manjaro Linux 6.1.62-1-MANJARO

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

**Comment by reidbaker** [comment] 2023-11-20 21:05
Test case 
"""
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)
"""

**Closed** 2023-11-27 16:14 UTC
Labels: tool, t: flutter doctor, has reproducible steps, fyi-android, team-tool, found in release: 3.13, found in release: 3.15

**Comment by tranvansang** [comment] 2023-12-10 06:27
In my case, I am setting `java 21.0.1 2023-10-17 LTS` but `flutter doctor` and other flutter commands consistently report java version from android studio.

```
    • Java binary at: /home/ninja/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
```

<details>
<summary>

`echo $JAVA_HOME`
</summary>

```
/opt/jdk
```
</details>

<details>
<summary>

`which java`
</summary>

```
/opt/jdk/bin/java
```
</details>

<details>
<summary>

`java --version`
</summary>

```
java 21.0.1 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
```
</details>

<details>
<summary>

`flutter doctor -v`
</summary>

```
[✓] Flutter (Channel stable, 3.16.3, on Arch Linux 6.5.7-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.16.3 on channel stable at /opt/flutter_linux_3.16.3-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (4 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/ninja/Android/Sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /home/ninja/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/ninja/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin version 76.3.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /home/ninja/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 76.3.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.5.7-arch1-1
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by reidbaker** [comment] 2023-12-11 16:49
> In my case, I am setting `java 21.0.1 2023-10-17 LTS` but `flutter doctor` and other flutter commands consistently report java version from android studio.
> 
> ```
>     • Java binary at: /home/ninja/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
> ```
> 
> `echo $JAVA_HOME`
> 
> `which java`
> 
> `java --version`
> 
> `flutter doctor -v`

What you are seeing is expected behavior flutter prioritizes android studios java version over java_home and to change that now would break existing customers.

**Comment by tranvansang** [comment] 2023-12-11 17:28
@reidbaker 
Thank you for your comment. Since Android Studio bundles this java version directly (by looking at the java bin path), we cannot upgrade the java version. Am I understanding correctly?

**Comment by reidbaker** [comment] 2023-12-12 15:34
You can upgrade the java version but it a bit more complicated. You can setup the environment variables for the android sdk then override the environment variable for android studio to something invalid. That will cause flutter to fallback to the java_home defined version of java. 
Your other option is to not install Android studio and only install the android sdks you might do that on a build machine for example. 

Here is a link to the code where we decide what version of java to use. 
https://github.com/flutter/flutter/blob/872f375b00689c5f09e2132141b4a14b7bac85cb/packages/flutter_tools/lib/src/android/java.dart#L44

**Comment by reidbaker** [comment] 2023-12-12 20:18
@tranvansang I just was reminded there is also an option to pass in the java directory as a config param
`flutter config --jdk-dir` 

Implementation here. 
https://github.com/flutter/flutter/blob/872f375b00689c5f09e2132141b4a14b7bac85cb/packages/flutter_tools/lib/src/android/java.dart#L207

**Comment by tranvansang** [comment] 2023-12-15 01:45
For anyone interested in, flutter config (.e.g, setup via `flutter config`) is stored in `$HOME/.config/flutter/settings`


```
{
  "jdk-dir": "/opt/jdk"
}
```
