### ISSUE TITLE
expecting to see OTA updates in flutter.

### ISSUE THREAD

**Issue by kushankurxd** [flutter/flutter#87506] opened 2021-08-02 18:16 UTC
## Use case

Every time we get some changes/bug fixes from the client we need to wait for at least a week or two for review processing to see the changes in production, which is very time-consuming and bad for businesses.

## Proposal

OTA updates, something like we can do in `React Native`.

Thanks #team

**Comment by stuartmorgan** [comment] 2021-08-02 19:52
Duplicate of https://github.com/flutter/flutter/issues/14330

**Closed by stuartmorgan** 2021-08-02 19:52 UTC

**Comment by chgibb** [comment] 2021-08-06 21:47
https://hydro-sdk.io/blog/fluttering-over-the-air
