### ISSUE TITLE
video_player can not get playing buffering status

### ISSUE THREAD

**Issue by WoKee** [flutter/flutter#29041] opened 2019-03-08 09:27 UTC
if video is initialized, then network not good , get buffering is always false. please check.
like :  controller.value.isBuffering  is always false.

**Comment by shashikantshaale** [comment] 2019-09-26 01:57
#https://github.com/flutter/flutter/issues/28494#issue-414466617

**Comment by shashikantshaale** [comment] 2019-09-26 01:57
Duplicate of #https://github.com/flutter/flutter/issues/28494#issue-414466617

**Closed** 2020-01-03 04:45 UTC
Labels: package, plugin
