### ISSUE TITLE
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.

### ISSUE THREAD

**Issue by AhsanNaushad11** [flutter/flutter#68779] opened 2020-10-22 12:38 UTC
I see this weird exception when running application. I upgraded my flutter version to 1.24.0.2.0.pree.98, ever since I am getting this exception on console, however results are desired.
![image](https://user-images.githubusercontent.com/36572551/96872404-0878a280-148d-11eb-9130-6be5e6f72c40.png)

If anyone can help solving this issue?

**Comment by TahaTesser** [comment] 2020-10-22 15:38
Hi @AhsanNaushad11 
This is fixed in https://github.com/flutter/flutter/issues/68705
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`
Closing as duplicate of https://github.com/flutter/flutter/issues/68705
Thank you

**Closed by TahaTesser** 2020-10-22 15:38 UTC
