### ISSUE TITLE
app_setting and system_setting packages not working

### ISSUE THREAD

**Issue by uzairleo** [flutter/flutter#55684] opened 2020-04-26 13:01 UTC
Hi there i am facing trouble while navigating to android wifi setting screen and i dont know how to solve this issue the screenshot will show u the exception below

![Screenshot (943)](https://user-images.githubusercontent.com/52172428/80308351-f670bc80-87e7-11ea-962e-7dff5ca8ebeb.png)

**Comment by VladyslavBondarenko** [comment] 2020-04-27 12:52
Hi I see you've filed already the issue in the app_settings plugin repository https://github.com/spencerccf/app_settings/issues/48
Closing, as this isn't an issue with the 3rd party plugin,
if you disagree or it turns out the issue is not plugin specific write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-04-27 12:52 UTC

**Comment by uzairleo** [comment] 2020-04-27 18:52
hi there bro actually in the app setting repo there are number of issues not solved yet thats why i came here and open issued here bcoz i know they  they will take alot of time to solved all that issues .
