### ISSUE TITLE
Navigator transition glitch nested navigators macOS

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#125711] opened 2023-04-28 20:46 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

It only happens on macOS. On Linux and Windows it doesn't happen because the animation is different. 

When you navigate to a new screen inside a nested navigator, the transition has an strange glitch. See the attached code and the attached video.

### Expected results

The transition should not have that glitch.

### Actual results

The animation has a glitch. See the attached video.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Nested navigators',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class NavigatorScreen {
  final String label;
  final GlobalKey<NavigatorState> globalKey;

  const NavigatorScreen({
    required this.label,
    required this.globalKey
  });
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<NavigatorScreen> globalKeys = [
    NavigatorScreen(
      label: "Screen 1", 
      globalKey: GlobalKey<NavigatorState>()
    ),
    NavigatorScreen(
      label: "Screen 2", 
      globalKey: GlobalKey<NavigatorState>()
    ),
    NavigatorScreen(
      label: "Screen 3", 
      globalKey: GlobalKey<NavigatorState>()
    ),
    NavigatorScreen(
      label: "Screen 4", 
      globalKey: GlobalKey<NavigatorState>()
    ),
    NavigatorScreen(
      label: "Screen 5", 
      globalKey: GlobalKey<NavigatorState>()
    ),
  ];

  int selectedScreen = 0;

  @override
  Widget build(BuildContext context) {

    void onScreenChange(int val, BuildContext context) {
      if (selectedScreen == val) {
        globalKeys[val].globalKey.currentState!.popUntil((route) => route.isFirst);
      } else {
        if (mounted) {
          setState(() {
            selectedScreen = val;
          });
        }
      }
    }

    return Material(
      color: Colors.transparent,
      child: Row(
        children: [
          Expanded(
            flex: 1,
            child: Scaffold(
              appBar: AppBar(
                title: const Text("Nested navigator"),
              ),
              body: ListView.builder(
                itemCount: globalKeys.length,
                itemBuilder: (context, index) => ListTile(
                  title: Text(globalKeys[index].label),
                  onTap: () => onScreenChange(index, context),
                )
              ),
            )
          ),
          Expanded(
            flex: 2,
            child: IndexedStack(
              index: selectedScreen,
              children: globalKeys.asMap().entries.map((e) => Navigator(
                key: e.value.globalKey,
                onGenerateRoute: (route) => MaterialPageRoute(
                  settings: route,
                  builder: (context) => Scaffold(
                    appBar: AppBar(
                      title: Text(e.value.label),
                    ),
                    body: Center(
                      child: ElevatedButton(
                        onPressed: () => Navigator.push(context, MaterialPageRoute(
                          builder: (context) => Subroute(routeName: e.value.label)
                        )),
                        child: const Text("Navigate to subroute")
                      ),
                    ),
                  ),
                ),
              )).toList(),
            )
          )
        ],
      ),
    );
  }
}

class Subroute extends StatelessWidget {
  final String routeName;

  const Subroute({
    Key? key,
    required this.routeName
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("$routeName subroute"),
      ),
      body: Center(
        child: Text("$routeName subroute"),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://user-images.githubusercontent.com/47545344/235250688-0d3e9270-eb39-44fb-8813-2a69d5c0e6ff.mp4

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale es-ES)
    • Flutter version 3.7.12 on channel stable at /Users/juan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (11 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/juan/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/juan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by znromonk** [comment] 2023-05-01 06:39
@JGeek00  I remember seeing this issue before but cannot find the link to it. Not sure if it was by design, but the solution was to wrap the Widget with in a `ClipRect`. In your case, wrapping the `IndexedStack` widget with `ClipRect` will eliminate the overflow animation. 

PS: To replicate the same undesired behavior on any platform, you can replace the `MaterialPageRoute` with `CupertinoPageRoute`

**Comment by danagbemava-nc** [comment] 2023-05-02 07:01
Hi @JGeek00, this issue has been fixed on the master & beta channels and should be available on the stable channel sometime in the future. The root cause of this issue is https://github.com/flutter/flutter/issues/113130. 

Per our triage policy, I'll close this since it has already been fixed on the master channel. If you run into this issue on the master or beta channel, kindly leave a comment below and I will reopen this issue. 

Thank you

**Closed by danagbemava-nc** 2023-05-02 07:01 UTC
Labels: in triage

**Comment by JGeek00** [comment] 2023-05-02 20:13
> @JGeek00 I remember seeing this issue before but cannot find the link to it. Not sure if it was by design, but the solution was to wrap the Widget with in a `ClipRect`. In your case, wrapping the `IndexedStack` widget with `ClipRect` will eliminate the overflow animation.
> 
> PS: To replicate the same undesired behavior on any platform, you can replace the `MaterialPageRoute` with `CupertinoPageRoute`

That worked for me. Thank you.
