### ISSUE TITLE
Got white line between Containers

### ISSUE THREAD

**Issue by iamjinge** [flutter/flutter#108969] opened 2022-08-04 12:49 UTC
## Steps to Reproduce

A Column with three Containers which height is 39.6, shows white lines between Containers.

<details>
<summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: <Widget>[
          Container(color: Colors.red, height: 39.6,),
          Container(color: Colors.red, height: 39.6,),
          Container(color: Colors.red, height: 39.6,),
        ],
      ),
    );
  }
}
```

This is the screenshot.
![image](https://user-images.githubusercontent.com/6782942/182850805-efee84a2-ea85-4e0c-af09-36ffe546e356.png)

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment] 2022-08-04 13:15
Hi @iamjinge, I believe this is a duplicate of https://github.com/flutter/flutter/issues/14288. 

Kindly follow up in the linked issue for updates. 

Thank you

**Closed by danagbemava-nc** 2022-08-04 13:15 UTC
Labels: in triage
