### ISSUE TITLE
State in native activity lost when navigating away and back to app.

### ISSUE THREAD

**Issue by fyzs-n9001** [flutter/flutter#20675] opened 2018-08-16 03:22 UTC
As long as current page is a Flutter page, the home button returns to the desktop, you can return from the launcher icon to the original page; but in the native Activity, then the state is lost, the return page is MainActivity

## Steps to Reproduce

1. In android native SecondActivity , press home key back to desktop
2. click launcher icon enter app , and the MainActivity shows
3. But in Flutter pages , i don't have this problem

## Logs

```
```

```
```

```
```

**Comment by goderbauer** [comment] 2019-01-17 23:36
Is this a dup of https://github.com/flutter/flutter/issues/6827?

**Comment by zoechi** [comment] 2019-01-18 07:21
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction project ideally shared on GitHub.

**Comment by zoechi** [comment] 2019-02-12 07:58
Duplicate of #6827

**Closed by zoechi** 2019-02-12 07:58 UTC
Labels: a: existing-apps, engine, framework, waiting for customer response
