### ISSUE TITLE
[Web][HTML] Tapping on Persian/Arabic characters of Inkwell Text causes an ArgumentError.

### ISSUE THREAD

**Issue by Ali-Fadaei** [flutter/flutter#151310] opened 2024-07-04 13:21 UTC
## sample code:
```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text('Flutter Demo'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Material(
                color: Colors.cyan,
                child: InkWell(
                  onTap: () => debugPrint('do something'),
                  child: const SizedBox(
                    height: 20,
                    width: 30,
                    child: Center(
                      child: Text(
                        'قبلی',
                      ),
                    ),
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```
### Expected results

Expected results is just inkwell works fine including Persian/Arabic Texts.

### inkwell onTap not work and throws this exception:

```console
══╡ EXCEPTION CAUGHT BY GESTURES LIBRARY
╞══════════════════════════════════════════════════════════
The following ArgumentError was thrown while handling a pointer data packet:
Invalid argument: 10.77

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_number.dart 145:7                clamp]
lib/_engine/engine/text/layout_fragmenter.dart 655:45
[_getClosestCharacterInRange]
lib/_engine/engine/text/layout_fragmenter.dart 685:12
getClosestCharacterBox
lib/_engine/engine/text/layout_service.dart 431:45
getClosestGlyphInfo
lib/_engine/engine/text/canvas_paragraph.dart 189:82
getClosestGlyphInfoForOffset
packages/flutter/src/painting/text_painter.dart 1547:52
getClosestGlyphForOffset
packages/flutter/src/rendering/paragraph.dart 755:43
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/shifted_box.dart 88:23                             <fn>
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/rendering/shifted_box.dart 83:20
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/proxy_box.dart 173:63
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/proxy_box.dart 173:63
hitTest
packages/flutter/src/rendering/proxy_box.dart 3147:54
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 1974:18
hitTest
packages/flutter/src/rendering/box.dart 3137:23                                   <fn>
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/rendering/box.dart 3132:32
defaultHitTestChildren
packages/flutter/src/rendering/flex.dart 1008:12
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/shifted_box.dart 88:23                             <fn>
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/rendering/shifted_box.dart 83:20
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/box.dart 3137:23                                   <fn>
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/rendering/box.dart 3132:32
defaultHitTestChildren
packages/flutter/src/rendering/custom_layout.dart 414:12
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 1974:18
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 3588:31
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 3718:31
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/widgets/overlay.dart 991:80
childHitTest
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/widgets/overlay.dart 992:21
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 3841:17
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/proxy_box.dart 173:63
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/custom_paint.dart 559:18
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/widgets/tap_region.dart 214:72
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/view.dart 263:7
hitTest
packages/flutter/src/rendering/binding.dart 610:34
hitTestInView
packages/flutter/src/gestures/binding.dart 391:7
[_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5
handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7
[_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9
[_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1419:5
invoke1
lib/_engine/engine/platform_dispatcher.dart 333:5
invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30
[_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7
onPointerData
lib/_engine/engine/pointer_binding.dart 961:16                                    <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 531:9
loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37
_checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
════════════════════════════════════════════════════════════════════════════════════════
════════════
Another exception was thrown: Invalid argument: 10.77
```

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text('Flutter Demo'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Material(
                color: Colors.cyan,
                child: InkWell(
                  onTap: () => debugPrint('do something'),
                  child: const SizedBox(
                    height: 20,
                    width: 30,
                    child: Center(
                      child: Text(
                        'قبلی',
                      ),
                    ),
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
```console
══╡ EXCEPTION CAUGHT BY GESTURES LIBRARY
╞══════════════════════════════════════════════════════════
The following ArgumentError was thrown while handling a pointer data packet:
Invalid argument: 10.77

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_number.dart 145:7                clamp]
lib/_engine/engine/text/layout_fragmenter.dart 655:45
[_getClosestCharacterInRange]
lib/_engine/engine/text/layout_fragmenter.dart 685:12
getClosestCharacterBox
lib/_engine/engine/text/layout_service.dart 431:45
getClosestGlyphInfo
lib/_engine/engine/text/canvas_paragraph.dart 189:82
getClosestGlyphInfoForOffset
packages/flutter/src/painting/text_painter.dart 1547:52
getClosestGlyphForOffset
packages/flutter/src/rendering/paragraph.dart 755:43
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/shifted_box.dart 88:23                             <fn>
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/rendering/shifted_box.dart 83:20
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/proxy_box.dart 173:63
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/proxy_box.dart 173:63
hitTest
packages/flutter/src/rendering/proxy_box.dart 3147:54
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 1974:18
hitTest
packages/flutter/src/rendering/box.dart 3137:23                                   <fn>
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/rendering/box.dart 3132:32
defaultHitTestChildren
packages/flutter/src/rendering/flex.dart 1008:12
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/shifted_box.dart 88:23                             <fn>
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/rendering/shifted_box.dart 83:20
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/box.dart 3137:23                                   <fn>
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/rendering/box.dart 3132:32
defaultHitTestChildren
packages/flutter/src/rendering/custom_layout.dart 414:12
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 1974:18
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 3588:31
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 3718:31
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/widgets/overlay.dart 991:80
childHitTest
packages/flutter/src/rendering/box.dart 807:31
addWithPaintOffset
packages/flutter/src/widgets/overlay.dart 992:21
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 3841:17
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/proxy_box.dart 173:63
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/custom_paint.dart 559:18
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/widgets/tap_region.dart 214:72
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/proxy_box.dart 118:19
hitTestChildren
packages/flutter/src/rendering/box.dart 2749:11
hitTest
packages/flutter/src/rendering/view.dart 263:7
hitTest
packages/flutter/src/rendering/binding.dart 610:34
hitTestInView
packages/flutter/src/gestures/binding.dart 391:7
[_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5
handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7
[_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9
[_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1419:5
invoke1
lib/_engine/engine/platform_dispatcher.dart 333:5
invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30
[_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7
onPointerData
lib/_engine/engine/pointer_binding.dart 961:16                                    <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 531:9
loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37
_checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
════════════════════════════════════════════════════════════════════════════════════════
════════════
Another exception was thrown: Invalid argument: 10.77
```
```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22621.3737], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Alifa\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35013.160
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[✓] VS Code (version 1.91.0)
    • VS Code at C:\Users\Alifa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3737]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.87

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-05 06:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/146588

**Closed by danagbemava-nc** 2024-07-05 06:53 UTC
Labels: in triage
