### ISSUE TITLE
1.22.2 - Flutter plugin not installed; this adds Flutter specific functionality.

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#68429] opened 2020-10-18 07:26 UTC
How do I fix this android plugin error? This error is being come after upgrade to 1.22.2 

**flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
 
[✓] Connected device (1 available)            

! Doctor found issues in 1 category.
```

**Android Studio**
<img width="1010" alt="Screenshot 2020-10-18 at 12 51 35" src="https://user-images.githubusercontent.com/34953062/96361127-c3790700-1140-11eb-8d31-dc5d828e00de.png">

**Comment by sidrao2006** [comment] 2020-10-18 07:55
@bhanuka96 
The plugin warnings do not matter. See [this](https://github.com/flutter/flutter/issues/67986#issuecomment-707881534) comment for reference. Also this is similar to [67986](https://github.com/flutter/flutter/issues/67986).

_Originally posted by @darshankawar in https://github.com/flutter/flutter/issues/68274#issuecomment-709924282_

**Comment by darshankawar** [comment] 2020-10-19 10:40
Closing this as duplicate of [67986](https://github.com/flutter/flutter/issues/67986) 
Even if you are getting those errors, you should be able to build without any issues. See the above referred link for more details.

**Closed by darshankawar** 2020-10-19 10:40 UTC

**Comment by kyughost** [comment] 2020-12-08 07:12
Hey @bhanuka96  try this line of code, worked for me 

`ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

**Comment by bhanuka96** [comment] 2020-12-08 10:00
@kyughost now working

**Comment by westindiantech** [comment] 2020-12-08 19:01
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanks this worked for me just now.

**Comment by Juenchine** [comment] 2020-12-09 20:32
@kyughost thank you from France ;) it works.

**Comment by kyughost** [comment] 2020-12-09 21:14
> @kyughost thank you from France ;) it works.

My pleasure, from Congo

**Comment by hebaothman** [comment] 2020-12-11 12:13
@kyughost Thanks it worked :)

**Comment by MuttakinHasib** [comment] 2020-12-12 01:05
@kyughost Thank you from Bangladesh :) it works

**Comment by Raphaelmbewe** [comment] 2020-12-14 09:34
@kyughost does this also work on windows?

**Comment by kyughost** [comment] 2020-12-14 10:17
> @kyughost does this also work on windows? 

No sir. Sorry

**Comment by Raphaelmbewe** [comment] 2020-12-14 12:32
please people how can I fix this problem on windows?

**Comment by KingKhan1234** [comment] 2020-12-14 21:43
Thanks so much! just got a new Macbook Air 2020, and was giving me the same problem.

**Comment by kyughost** [comment] 2020-12-16 14:32
> please people how can I fix this problem on windows?

I'm sorry. Mac user here

**Comment by bennybat50** [comment] 2020-12-17 07:34
Thanks @kyughost  It worked for me too too

**Comment by SupremeQingHong** [comment] 2020-12-25 07:36
> 嘿@ bhanuka96 试试这一行代码，对我有用
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`
nice！

**Comment by kamamuri** [comment] 2020-12-29 16:45
Funcionó :) perfecto, muchas gracias

**Comment by lynnscode** [comment] 2021-01-04 06:37
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanks, this worked for me

**Comment by GP1024** [comment] 2021-01-07 14:05
how to do for win10

**Comment by GP1024** [comment] 2021-01-07 14:05
how to do for win10?

**Comment by nezzard** [comment] 2021-01-14 11:17
How to fix it? On win 10 i tried all solutions, buyt nothing work ( 
Only work on dev brunch, but i need stable

**Comment by saifamer2030** [comment] 2021-01-14 13:53
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanx bro this worked for me :)

**Comment by JekMx** [comment] 2021-01-19 17:15
Nice !! Thanx !!! 

> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

**Comment by zazaliu** [comment] 2021-01-20 13:12
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

worked for me thx!

**Comment by infinZero** [comment] 2021-01-22 11:14
Can I use this

**Comment by infinZero** [comment] 2021-01-22 11:15
I've android studio 4.1.2 so Can I used this instead of 4.1 ? 
Like as?


ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1.2/plugins ~/Library/Application\ Support/AndroidStudio4.1.2

**Comment by japneetbhatia** [comment] 2021-01-23 09:06
Can someone please tell how to resolve this issue in win10 ?

**Comment by infinZero** [comment] 2021-01-23 20:10
> Can someone please tell how to resolve this issue in win10 ?

for win10 you can consult with [this](https://github.com/flutter/flutter/issues/67986) for windows

**Comment by madura7** [comment] 2021-02-01 14:23
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanks. This is working

**Comment by RYgithub1** [comment] 2021-02-03 01:30
`ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

**Comment by domicoder** [comment] 2021-02-05 08:49
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thank you. Worked for me!

**Comment by aboutuoba** [comment] 2021-02-07 09:44
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanks. It work!

**Comment by osamasorani** [comment] 2021-02-11 19:58
please, how can solve this problem in win10 ?

**Comment by garshom** [comment] 2021-02-17 05:06
ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

this worked for me as well. thanks

**Comment by FlutterD** [comment] 2021-02-18 11:58
I have just upgraded android studio to the latest version 4.1.2, and the problem were fixed

**Comment by iNeedHelpX** [comment] 2021-02-28 01:32
> > 嘿@ bhanuka96 试试这一行代码，对我有用
> > `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`
> > nice！

I can't thank you enough!! It was perplexing me!!

**Comment by germanngc** [comment] 2021-03-01 03:54
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

(Y) Worked

**Comment by anjali-tiwari24** [comment] 2021-05-11 21:58
I was facing the same problem but this works for me.( https://github.com/flutter/flutter/issues/11940#issuecomment-728005813 )

**Comment by stuarthua** [comment] 2021-06-13 20:56
For Android Studio 4.2.1
```
Flutter 1.22.5 • channel unknown • unknown source
Framework • revision 7891006299 (6 个月前) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
```
just change version: 
```
ln -s ~/Library/Application\ Support/Google/AndroidStudio4.2/plugins ~/Library/Application\ Support/AndroidStudio4.2
```
Worked for me.

**Comment by exeptionerror** [comment] 2021-06-24 04:36
3 Working Solution Added [Flutter plugin not installed error. When running flutter doctor](https://fluttercorner.com/flutter-plugin-not-installed-error-when-running-flutter-doctor/)
