### ISSUE TITLE
Unable to focus or input text in TextField-widget in Overlay without giving its own materialApp.

### ISSUE THREAD

**Issue by Valtteri-Jokinen** [flutter/flutter#28986] opened 2019-03-07 11:34 UTC
I'm having trouble using `TextField` in overlay in my app.

In my app I'm trying to get text input from user in a custom overlay.

`TextField` does require the `Material`-parent but I can not get it to work without giving it its own `MaterialApp`.
Without `MaterialApp` I can not focus on the textfield or get the soft keyboard opened or insert any text into it even with hardware keyboard. 
But long pressing and then pasting text does work. (?)
I am debugging in Android emulator.

How should one use `TextField` in overlay?

It does not seem right to create two `MaterialApp` widgets nested together. The `MaterialApp` creates and hosts the overlay's, right?

Or should the overlay be regarded as completely separate app which means it really should include its own `MaterialApp`-widget? The `Overlay`-class documentation only talks about making it possible to draw independent child widgets on top of owther widgets. Where should one read more information about Overlay?

This is also somewhat related to [this StackOverflow question](https://stackoverflow.com/questions/52973246/flutter-textfield-in-overlay-triggering-rebuilds), where also the inclusion of `MaterialApp`-widget was questioned.

## Steps to Reproduce

Use the included code.

1. Open new overlay with included button.
2. Try to focus on the `TextField` by tapping.

### Reproduce code

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatelessWidget {
  static OverlayEntry menuOverlay;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter textfield in overlay Demo'),
      ),
      body: Column(
        children: <Widget>[
          RaisedButton(
              onPressed: () => Overlay.of(context).insert(new OverlayEntry(builder: (BuildContext context) => MenuOverlay())),
              child: const Text('show overlay')),
        ],
      ),
    );
  }
}

class MenuOverlay extends StatefulWidget {
  MenuOverlay({Key key}) : super(key: key);

  @override
  _MenuOverlayState createState() => _MenuOverlayState();
}

class _MenuOverlayState extends State<MenuOverlay> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Positioned(
          top: 100.0,
          right: 10.0,
          child: Container(
            constraints: BoxConstraints(maxWidth: 200, maxHeight: 200),
            child:
           // MaterialApp( home:
              Material(
                type: MaterialType.transparency,
                child: TextField(
                  decoration: InputDecoration(hintText: 'Please enter a text'),
                  onSubmitted: print,
                ),
              ),
           // ), // MaterialApp
          ),
        ),
      ],
    );
  }
}

```

### Flutter status

Output of `flutter doctor -v`:

```bash
# flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.348], locale en-GB)
    • Flutter version 1.0.0 at C:\Users\username\development-tools\flutter_windows_v1.0.0-stable\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\username\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by HansMuller** [comment] 2019-03-08 16:57
To create a TextField in an Overlay you need to provide an enclosing FocusScope. My apologies: I don't think there's any way you could have known that.

Here's a version of your test app that manages the focus correctly:
https://gist.github.com/HansMuller/55f4e530a8e96777ad53af8bb20fb83b

**Comment by Valtteri-Jokinen** [comment] 2019-03-11 16:13
I appreciate the fast answer! 

But sadly your submitted Flutter app does not work on my android emulator. It does not gain focus, even if giving the text field `autofocus: true,`-parameter. Did you run it on some real hardware? Is this an issue within the emulator?

I even tried to put MaterialApp inside the submitted FocusScope-widget and with that the TextField cannot be focused. That's strange, because it works without the FocusScope-widget.

The MaterialApp does include it's own FocusScope, if I'm looking at Flutter inspector's widget tree correctly.

Is there still something missing?

**Comment by HansMuller** [comment] 2019-03-12 23:30
I've verified that the [test app](https://gist.github.com/HansMuller/55f4e530a8e96777ad53af8bb20fb83b) works correctly on an Android emulator as well as a device.

However, a fix for FocusScope that was only added at the end of January is needed: https://github.com/flutter/flutter/pull/27365. Unfortunately this change has yet to land in a "good" dev build (it was in [dev 1.3.9](https://github.com/flutter/flutter/releases/tag/v1.3.9)  which was considered a ["bad build"](https://github.com/flutter/flutter/wiki/Bad-Builds) for reasons unrelated to focus scopes) so for the moment to get the fix you'd have to build on the current Flutter repo. With any luck we'll have a new dev build that includes the fix soon. It's being worked on now.

Sorry about that.

**Comment by jwehrle** [comment] 2019-07-05 22:47
Subscribing because there is a common input design pattern I am trying to implement where a textfield is brought up on an overlay and sits on top of the keyboard but it doesn't work smoothly without autofocus or focus nodes working in Overlays. The best that can be done before this fix hits is to show the textfield in the overlay and then when the user taps on it the keyboard comes up. But that's not really an elegant design.

**Comment by TahaTesser** [comment] 2020-07-09 13:57
Hi @guidezpl 
Not able to reproduce this issue using your code sample  on latest `dev` channel on physical device or emulator 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatelessWidget {
  static OverlayEntry menuOverlay;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter textfield in overlay Demo'),
      ),
      body: Column(
        children: <Widget>[
          RaisedButton(
              onPressed: () => Overlay.of(context).insert(new OverlayEntry(
                  builder: (BuildContext context) => MenuOverlay())),
              child: const Text('show overlay')),
        ],
      ),
    );
  }
}

class MenuOverlay extends StatefulWidget {
  MenuOverlay({Key key}) : super(key: key);

  @override
  _MenuOverlayState createState() => _MenuOverlayState();
}

class _MenuOverlayState extends State<MenuOverlay> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Positioned(
          top: 100.0,
          right: 10.0,
          child: Container(
            constraints: BoxConstraints(maxWidth: 200, maxHeight: 200),
            child:
                // MaterialApp( home:
                Material(
              type: MaterialType.transparency,
              child: TextField(
                decoration: InputDecoration(hintText: 'Please enter a text'),
                onSubmitted: print,
              ),
            ),
            // ), // MaterialApp
          ),
        ),
      ],
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (5 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
``` 

</details>

**Comment by guidezpl** [comment] 2020-07-09 14:07
Just added a label, @Valtteri-Jokinen are you still facing this issue?

**Comment by Valtteri-Jokinen** [comment] 2020-07-18 06:22
The original use-case in our app was redone to not use overlays to circumvent the problem.

Good if the issue has been fixed on the dev channel. Unfortunately I currently have no way to test if the issue is also fixed on the stable channel.

If the issue has been fixed then this issue can be closed. 

Sorry for late reply.

**Comment by TahaTesser** [comment] 2020-07-20 13:24
Hi @HansMuller 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-20 13:24 UTC
Labels: a: text input, f: material design, framework

**Comment by dcchristopher** [comment] 2020-08-27 06:03
I don't think this issue has been "fixed" in either branch, possibly because it's really about how one is supposed to implement it properly. I switched to dev and it didn't make a difference. @HansMuller's [comment](https://github.com/flutter/flutter/issues/28986#issuecomment-472220386), however, saved the day.
