### ISSUE TITLE
Flutter for Web Screen Reader support for Windows Narrator and Orca

### ISSUE THREAD

**Issue by anticode-403** [flutter/flutter#39133] opened 2019-08-23 18:49 UTC
Title says it all. I want to use Flutter for Web in a project where accessibility is a requirement and Flutter for Web does not seem to support screen readers.

**Comment by Levi-Lesches** [comment] 2019-08-25 20:16
I've noticed there doesn't seem to be a logical order to the DOM when it comes to Flutter for Web. I remember seeing an issue about this but I can't find it now. But this is super important.

**Comment by nturgut** [comment] 2020-09-22 21:04
closing this one as duplicate of: https://github.com/flutter/flutter/issues/66383 

thanks for filing the issue.

**Closed by nturgut** 2020-09-22 21:04 UTC
Labels: P5, a: accessibility, a: desktop, platform-web
