### ISSUE TITLE
SliverPersistentHeaderDelegate with wrong build params

### ISSUE THREAD

**Issue by dmvvilela** [flutter/flutter#46721] opened 2019-12-10 21:31 UTC
I am trying to build an app with slivers, but this seems wrong. I have an appbar which changes its size and it is pinned.. some widgets.. then another sliver which is pinned too and then some widgets..

The documentation on https://api.flutter.dev/flutter/widgets/SliverPersistentHeaderDelegate/build.html says:

"The shrinkOffset is a distance from maxExtent towards minExtent representing the current amount by which the sliver has been shrunk. When the shrinkOffset is zero, the contents will be rendered with a dimension of maxExtent in the main axis. When shrinkOffset equals the difference between maxExtent and minExtent (a positive number), the contents will be rendered with a dimension of minExtent in the main axis. The shrinkOffset will always be a positive number in that range."

Well, my configuration is:

```
class _SliverBarDelegate extends SliverPersistentHeaderDelegate {
  _SliverBarDelegate();

  @override
  double get minExtent => 60;
  @override
  double get maxExtent => 87;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
// tried stuff to make it happen.. wont work..
    double percent = 1;
    final barSize = 87 - shrinkOffset;

    if (overlapsContent) {
      percent = barSize / 87;
    }

    print(shrinkOffset);
    return HomeBar(percent);
  }

  @override
  bool shouldRebuild(_SliverBarDelegate oldDelegate) {
    return false;
  }
}
```

**Which means that shrinkOffset should be between 0 and 17 correct?
Actually it is returning between 0 and 87..** And it makes me crazy cause i can't avoid overflow.. It stops shrinking but then the value continues to change.. Also.. overlapsContent won't work either.. I have another sliver behind it but it always returns false..

My code:

```
class HomeView extends StatelessWidget {
  const HomeView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Container(
        child: CustomScrollView(
          slivers: <Widget>[
            SliverPersistentHeader(
              delegate: _SliverBarDelegate(),
              pinned: true,
            ),
            // SliverPersistentHeader(
            //   delegate: _SliverHeaderDelegate(),
            // ),
// here it was another delegate but i tried to change..
            SliverToBoxAdapter(child: PlacesCarousel()),
            SliverToBoxAdapter(child: PlacesHistory()),
            SliverPersistentHeader(
              delegate: _SliverFilterRowDelegate(),
              pinned: true,
            ),
            PlacesList(),
          ],
        ),
      ),
    );
  }
}
```

PlacesList() is a sliverlist which was working fine. i need this correct cause i will make a fade on my widget with changing size and removing a widget from this bar..

Following flutter doctor:
```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012,
    locale pt-BR)
    • Flutter version 1.9.1+hotfix.6 at /Users/danvilela/Code/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/danvilela/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.0

[✓] Connected device (1 available)
    • iPhone 8 • 3D8B39FB-41B3-41D4-BBD8-95499E3788B1 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
```

**Comment by mHaisham** [comment] 2020-05-20 15:06
Same thing is happening to me. i dont know if this is a bug or not. i want to know if this has a workaround.

**Comment by greymag** [comment] 2020-07-14 08:19
Same behaviour. As far as I can see from source code - there is no clamp of `shrinkOffset` by `maxExtent - minExtent`. But it's can't be more than `maxExtent`. So the documentation at that moment doesn't meet implementation - `shrinkOffset` is in range between `0` and `maxExtent`.

And seems it's also leads to unexpected behaviour - while `shrinkOffset` is changing from `maxExtent - minExtent` to `maxExtent ` nothing scrolls, but scroll position is changing, i.e. to scroll down I need to scroll back from `maxExtent` to `maxExtent - minExtent`, and only after that I will see changes on screen. Looks horrible.

**Comment by darshankawar** [comment] 2020-09-25 14:14
Hi @dmvvilela,
Is this still an issue on latest version ?
If so, can you provide latest `flutter doctor -v` and a minimal complete reproducible code sample ?
Thanks.

**Comment by dmvvilela** [comment] 2020-09-26 11:40
This was too long ago.. I don't have this code anymore.. It didn't work, nobody responded here so i removed it.

**Comment by Piinks** [comment] 2023-05-30 19:50
I am going to close this as a dupe of https://github.com/flutter/flutter/issues/26667, please follow up there for more updates in the issue. Thanks!

**Closed by Piinks** 2023-05-30 19:50 UTC
Labels: framework, f: scrolling, P4
