### ISSUE TITLE
[url_launcher] Uncaught PlatformException

### ISSUE THREAD

**Issue by johnsheehan** [flutter/flutter#114843] opened 2022-11-07 20:35 UTC
## Steps to Reproduce

Run the sample code below in iOS Simulator.

**Expected results:**
Apple Maps opens without an exception

**Actual results:**
Apple Maps opens but a PlatformException is thrown and uncaught.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: TextButton(
        onPressed: (() async {
          var url = Uri(
            scheme: 'https',
            host: 'maps.apple.com',
            queryParameters: {
              'address': '1600 Pennsylvania Avenue NW, Washington, DC 20500',
              'q': 'The White House',
              'll': '38.8975342,-77.0386928',
            },
          );

          await launchUrl(url);
        }),
        child: const Text('Launch'),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[+15741 ms] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Error, Error while
launching
https://maps.apple.com?address=1600+Pennsylvania+Avenue+NW%2C+Washington%2C+DC+20500&q=The+White+House&ll=38.8975
342%2C-77.0386928, null, null)
                     #0      StandardMethodCodec.decodeEnvelope
(package:flutter/src/services/message_codecs.dart:653:7)
                     #1      MethodChannel._invokeMethod
(package:flutter/src/services/platform_channel.dart:296:18)
                     <asynchronous suspension>
                     #2      launchUrl (package:url_launcher/src/url_launcher_uri.dart:53:10)
                     <asynchronous suspension>
                     #3      MyApp.build.<anonymous closure> (package:launch_platform_exception/main.dart:28:11)
                     <asynchronous suspension>
```

```
Analyzing launch_platform_exception...                                  
No issues found! (ran in 1.2s)
```

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.7 on channel stable at /Users/john/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (6 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 885EAE0F-20DA-4ABF-A7CC-74DB5E84212B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-11-08 08:10
Hi @johnsheehan, I believe this is a duplicate of https://github.com/flutter/flutter/issues/75691. The exception is thrown because the map opens before safari can complete loading the page which effectively closes the page before a response can be returned. 

As such, I'll be closing this in favor of the issue linked above. 

If you disagree, leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-11-08 08:10 UTC
Labels: in triage
