### ISSUE TITLE
flutter could use a "bug report" command that collects all the information the flutter issue template requires.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2127] opened 2016-02-24 19:34 UTC
For instance, it could grab 'flutter logs' output, 'flutter --version', maybe even screenshots in the future.

The output of the 'bug report' command should be easy to copy/paste or attach to a flutter issue.

**TLDR: I'm too lazy to fill out the new issue template, can you do it for me?**

Below is the current template:

_Detailed issue description here. More information at [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/)_
### Steps to Reproduce
- _Add steps here. Provide verbose variants of `flutter` commands if necessary._
### Flutter Version

_Add `flutter --version` here_
### Logs

_Paste relevant logs here_
### Crash Reports

_Add relevant crash reports here_

**Comment by devoncarew** [comment] 2016-02-24 20:38
This bug report form does seem a bit long. Perhaps just:

- what were you doing?
- please run `flutter --version`

**Comment by eseidelGoogle** [comment] 2017-01-26 23:18
https://github.com/flutter/flutter/issues/1657 is related.

**Comment by Hixie** [comment] 2017-08-15 20:17
Dupe of #1657.

**Closed by Hixie** 2017-08-15 20:17 UTC
Labels: dev: tool
