### ISSUE TITLE
 AAPT Process manager cannot be shut down while daemons are in use

### ISSUE THREAD

**Issue by jiuyeit** [flutter/flutter#45669] opened 2019-11-27 05:45 UTC
```
Exception in thread "ForkJoinPool.commonPool-worker-4" java.lang.IllegalStateException: AAPT Process manager cannot be shut down while daemons are in use
        at com.android.builder.internal.aapt.v2.Aapt2DaemonManager.shutdown(Aapt2DaemonManager.kt:96)
        at com.android.build.gradle.internal.res.namespaced.RegisteredAaptService.shutdown(Aapt2DaemonManagerService.kt:61)
        at com.android.build.gradle.internal.workeractions.WorkerActionServiceRegistry$shutdownAllRegisteredServices$1$1.run(WorkerActionServiceRegistry.kt:96)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  E:\app\flutter_app2\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:0: error: xml parser error: not well-formed (invalid token).

  Command: C:\Users\zhuangwei\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\975e3ca4f7a6d7add2116ef243c9a532\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          E:\app\flutter_app2\build\app\intermediates\res\merged\debug \
          E:\app\flutter_app2\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  E:\app\flutter_app2\android\app\src\main\res\values\styles.xml:3:5-7:13: AAPT: error: xml parser error: not well-formed (invalid token).

  Command: C:\Users\zhuangwei\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\975e3ca4f7a6d7add2116ef243c9a532\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          E:\app\flutter_app2\build\app\intermediates\res\merged\debug \
          E:\app\flutter_app2\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        16.6s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
```

**Comment by zw-zhuangwei** [comment] 2019-11-27 05:49
我也遇到这个问题 请问解决了么

**Comment by iapicca** [comment] 2019-11-27 12:14
Hi @jiuyeit 
could you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem

There has been a similar error for an older version of gradle, I'm not sure that this is the case,
but you might want to take a look [[link](https://stackoverflow.com/questions/52712063/build-failing-during-merge-resources-with-android-gradle-plugin-3-3-0)].
thank you

**Comment by VladyslavBondarenko** [comment] 2020-01-10 08:57
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by neuroteks** [comment] 2020-01-12 19:20
* $ flutter doctor -v 

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [versÃ£o 10.0.17763.914], locale pt-AO)
    • Flutter version 1.12.13+hotfix.5 at C:\Lib\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\henri\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code
    • VS Code at C:\Users\henri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Moto E 4 • 0039486085 • android-arm • Android 7.1.1 (API 25)

• No issues found! 

* $ flutter run 

Launching lib\main.dart on Moto E 4 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleDebug'...
AAPT2 aapt2-3.3.0-5013011-windows Daemon #3: Unexpected standard output: Ready
AAPT2 aapt2-3.3.0-5013011-windows Daemon #5: Unexpected standard output: Ready
AAPT2 aapt2-3.3.0-5013011-windows Daemon #4: Unexpected standard output: Ready
AAPT2 aapt2-3.3.0-5013011-windows Daemon #6: Unexpected standard output: Ready
AAPT2 aapt2-3.3.0-5013011-windows Daemon #1: Unexpected standard output: Ready
AAPT2 aapt2-3.3.0-5013011-windows Daemon #2: Unexpected standard output: Ready
AAPT2 aapt2-3.3.0-5013011-windows Daemon #0: Unexpected standard output: Ready

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-3.3.0-5013011-windows Daemon #0: Daemon startup failed
  This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 30s
Exception in thread "ForkJoinPool.commonPool-worker-4" java.lang.IllegalStateException: AAPT Process manager cannot be shut down while daemons are in use
        at com.android.builder.internal.aapt.v2.Aapt2DaemonManager.shutdown(Aapt2DaemonManager.kt:96)
        at com.android.build.gradle.internal.res.namespaced.RegisteredAaptService.shutdown(Aapt2DaemonManagerService.kt:61)
        at com.android.build.gradle.internal.workeractions.WorkerActionServiceRegistry$shutdownAllRegisteredServices$1$1.run(WorkerActionServiceRegistry.kt:96)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       157,7s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...                            -
C:\Media\Doc\Carlos\Projetos\Neuro Teks\Flutter\Vem Rodar Cliente> 

Maybe this can be related to another ghost daemons runing on background or even with the issue at #16604 
- I manage to solve it by killing any remaining flutter process and doing a fluter clean

**Comment by VladyslavBondarenko** [comment] 2020-01-13 10:05
Thanks @neuroteks !
given your last message I feel safe to close this issue,
@jiuyeit if the last comment doesn't help you or you are disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by VladyslavBondarenko** 2020-01-13 10:05 UTC
Labels: waiting for customer response
