### ISSUE TITLE
%5Btool_crash%5D ProcessException%3A The command failed%0AStdout%3A%0A%0AStderr%3A%0A%5B%2Fhome%2Fujjawal%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fflutter%2F3029dcd93ed4e02379c16c77543915f1b69c16ad%2Fandroid-arm-profile%2Flinux-x64.zip%5D%0A  

### ISSUE THREAD

**Issue by ujjawa1** [flutter/flutter#64877] opened 2020-08-29 20:52 UTC
End-of-central-directory signature not found.  Either this file is not%0A  a zipfile%2C or it constitutes one disk of a multi-part archive.  In the%0A  latter case the central directory and zipfile comment will be found on%0A  the last disk%28s%29 of this archive.%0Aunzip%3A  cannot find zipfile directory in one of %2Fhome%2Fujjawal%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fflutter%2F3029dcd93ed4e02379c16c77543915f1b69c16ad%2Fandroid-arm-profile%2Flinux-x64.zip or%0A        %2Fhome%2Fujjawal%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fflutter%2F3029dcd93ed4e02379c16c77543915f1b69c16ad%2Fandroid-arm-profile%2Flinux-x64.zip.zip%2C and cannot find %2Fhome%2Fujjawal%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fflutter%2F3029dcd93ed4e02379c16c77543915f1b69c16ad%2Fandroid-arm-profile%2Flinux-x64.zip.ZIP%2C period.%0A Command%3A unzip%2C OS error code%3A 9

%23%23 Command%0A%60%60%60%0Aflutter --no-color --no-version-check precache%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0AProcessException%3A The command failed%0AStdout%3A%0A%0AStderr%3A%0A%5B%2Fhome%2Fujjawal%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fflutter%2F3029dcd93ed4e02379c16c77543915f1b69c16ad%2Fandroid-arm-profile%2Flinux-x64.zip%5D%0A  End-of-central-directory signature not found.  Either this file is not%0A  a zipfile%2C or it constitutes one disk of a multi-part archive.  In the%0A  latter case the central directory and zipfile comment will be found on%0A  the last disk%28s%29 of this archive.%0Aunzip%3A  cannot find zipfile directory in one of %2Fhome%2Fujjawal%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fflutter%2F3029dcd93ed4e02379c16c77543915f1b69c16ad%2Fandroid-arm-profile%2Flinux-x64.zip or%0A        %2Fhome%2Fujjawal%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fflutter%2F3029dcd93ed4e02379c16c77543915f1b69c16ad%2Fandroid-arm-profile%2Flinux-x64.zip.zip%2C and cannot find %2Fhome%2Fujjawal%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fflutter%2F3029dcd93ed4e02379c16c77543915f1b69c16ad%2Fandroid-arm-profile%2Flinux-x64.zip.ZIP%2C period.%0A Command%3A unzip%2C OS error code%3A 9%0A%60%60%60%0A%230      RunResult.throwException %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fprocess.dart%3A172%3A5%29%0A%231      _DefaultProcessUtils.runSync %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fprocess.dart%3A463%3A17%29%0A%232      _PosixUtils.unzip %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fos.dart%3A226%3A19%29%0A%233      ArtifactUpdater._downloadArchive %28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A1478%3A18%29%0A%234      _rootRunUnary %28dart%3Aasync%2Fzone.dart%3A1198%3A47%29%0A%235      _CustomZone.runUnary %28dart%3Aasync%2Fzone.dart%3A1100%3A19%29%0A%236      _FutureListener.handleValue %28dart%3Aasync%2Ffuture_impl.dart%3A143%3A18%29%0A%237      Future._propagateToListeners.handleValueCallback %28dart%3Aasync%2Ffuture_impl.dart%3A696%3A45%29%0A%238      Future._propagateToListeners %28dart%3Aasync%2Ffuture_impl.dart%3A725%3A32%29%0A%239      Future._completeWithValue %28dart%3Aasync%2Ffuture_impl.dart%3A529%3A5%29%0A%2310     _AsyncAwaitCompleter.complete %28dart%3Aasync-patch%2Fasync_patch.dart%3A40%3A15%29%0A%2311     _completeOnAsyncReturn %28dart%3Aasync-patch%2Fasync_patch.dart%3A311%3A13%29%0A%2312     Net.fetchUrl %28package%3Aflutter_tools%2Fsrc%2

**Comment by darshankawar** [comment] 2020-08-31 07:25
This seems to be a duplicate of [64876](https://github.com/flutter/flutter/issues/64876).
Closing.

**Closed by darshankawar** 2020-08-31 07:25 UTC
