### ISSUE TITLE
The loadUrl method in webview_flutter is not redirected in iOS

### ISSUE THREAD

**Issue by wanyoung1231** [flutter/flutter#94908] opened 2021-12-09 03:46 UTC
## Steps to Reproduce

**Expected results:** When the server returns a `302` status code, it can redirect to a new page.

**Actual results:** `loadUrl` does not redirect to a new page and keeps looping in the `navigationDelegate`, but there is no problem in Android.

<details>
<summary>Flutter code sample</summary>

```dart
import 'controller.dart';

late WebViewController webview;

class WebPage extends GetView<CommonWebviewController> {
  const WebPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: SafeArea(
        top: false,
        bottom: true,
        child: WebView(
          initialUrl: Get.arguments['url'],
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (_controller) {
            webview = _controller;
          },
          navigationDelegate: (NavigationRequest request) {
            if (request.url
                .startsWith("http://192.168.3.114:9001/oauth2/authorize")) {
              webview.loadUrl(
                request.url,
                headers: {
                  'Authorization': 'Bearer ${Get.arguments["jwt"]}',
                  'framework': 'flutter'
                },
              );
              print('blocking navigation to $request}');
              return NavigationDecision.prevent;
            }
            print('allow navigation to $request}');
            return NavigationDecision.navigate;
          },
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>Vue code sample</summary>

```Javascript
let code = this.getQueryVariable("code");
let token = localStorage.getItem("token");

if (token) {
  await this.$store.dispatch("getAccountInformation");
} else {
  if (code) {
    let data = {
      code: code,
      store_id: store_id
    };
    account
      .login(data)
      .then(res => {
        localStorage.setItem("token", res.results.token);
        localStorage.setItem("store_id", store_id);
      });
  } else {
    window.location.href =
        "http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=" +
        encodeURIComponent("http://192.168.3.114:8081/") +
        "&t=" +
        +new Date();
  }
}
```
</details>

<details>
<summary>Server code sample</summary>

```go
func HandleGetOAuth2Code(c *gin.Context) {
  type Serializer struct {
    AppID       string `form:"app_id" binding:"required"`
    RedirectURI string `form:"redirect_uri" binding:"required"`
  }
  
  serializer := Serializer{}
  if err := c.ShouldBind(&serializer); err != nil {
    FailedResponse(c, CodeParamsError)
    return
  }
  
  account := c.MustGet("account").(models.User)
  
  code := utils.GenerateOAuth2Code(serializer.AppID, account.UserID)
  
  uri, _ := url2.QueryUnescape(serializer.RedirectURI)
  location := fmt.Sprintf("%s?code=%s", uri, code)
  
  c.Redirect(302, location)
}
```
</details>

<details>
<summary>Logs</summary>

```
[ +369 ms] flutter: allow navigation to NavigationRequest(url: http://192.168.3.114:8081/?store_id=sid_285162b1ebfd&sign=f0ca8749e2132914493b49243e8ab3d8, isForMainFrame: true)}
[ +162 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[   +7 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[        ] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[  +37 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[  +21 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[   +8 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[   +1 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[   +2 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[        ] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[   +8 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[   +3 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
[   +8 ms] flutter: blocking navigation to NavigationRequest(url: http://192.168.3.114:9001/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739, isForMainFrame: true)}
```

```
[GIN] 2021/12/09 - 11:36:44 | 302 |  100.926957ms |   192.168.3.141 | GET      "/oauth2/authorize?app_id=mq05722d531dbb&redirect_uri=http%3A%2F%2F192.168.3.114%3A8081%2F&t=1639021003739"
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/young/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/young/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • young 的 iPhone (mobile) • 00008101-000144842E10001E • ios            • iOS 15.1.1 19B81
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```

</details>

![image](https://user-images.githubusercontent.com/3946765/145330506-16c36e72-4d9a-4288-b404-b9a058ff2a24.png)

**Comment by stuartmorgan** [comment] 2021-12-09 04:08
Closing as a duplicate of https://github.com/flutter/flutter/issues/65502; see https://github.com/flutter/flutter/issues/65502#issuecomment-696237384 and subsequent discussion.

You are explicitly creating the infinite loop in your delegate; it only works on Android because the handler isn't called there for `loadUrl`.

**Closed by stuartmorgan** 2021-12-09 04:08 UTC
