### ISSUE TITLE
FlutterFragmentActivity  incompatible with AndroidX

### ISSUE THREAD

**Issue by Myhone** [flutter/flutter#43974] opened 2019-11-01 11:25 UTC
FlutterFragmentActivity  should be compatible with AndroidX

**Comment by xster** [comment] 2019-11-09 01:00
Can you elaborate a bit? If you meant io.flutter.app.FlutterFragmentActivity, we encourage you to use io.flutter.embedding.android.FlutterFragmentActivity instead (@matthew-carroll, we can probably add deprecation annotations to those classes now since they're not used in full-Flutter and we never shipped add-to-app). 

If you meant io.flutter.embedding.android.FlutterFragmentActivity, it should cleanly jetify in your AndroidX project.

**Comment by matthew-carroll** [comment] 2019-12-22 07:30
@Myhone are you currently jetifying your project? If so, are you getting any errors? If not, it will be necessary for some time to jetify projects that use Flutter and AndroidX until Flutter eventually migrates internally to AndroidX.

**Comment by blasten** [comment] 2020-01-03 23:40
Duplicate of https://github.com/flutter/flutter/issues/46840, so closing.

**Closed by blasten** 2020-01-03 23:40 UTC
Labels: a: existing-apps, engine, severe: new feature, t: gradle, tool, waiting for customer response, ▣ platform-android

**Comment by mcshaba** [comment] 2020-01-31 14:46
I have tried all the cases ever and the application keeps crashing. Kindly migrate FlutterActivity and FlutterFragmentActivity to Appcompat in AndroidX
