### ISSUE TITLE
[web]: Getting a working offline version of the web build

### ISSUE THREAD

**Issue by anoureddini** [flutter/flutter#67664] opened 2020-10-08 18:30 UTC
We build for mobile and standalone apk or iOS app setup file is generated. Why doesn't `flutter build web` give us a standalone working offline version of the website? Why do we need to have a running server to be able to run the web version of our app?

**Comment by iapicca** [comment] 2020-10-08 19:02
duplicate of https://github.com/flutter/flutter/issues/67663

**Comment by jonahwilliams** [comment] 2020-10-08 19:44
Because that is not how websites work, they are designed to be viewed in the browser - but do not have permissions to access the local file system. Thus, you need a web server to provide the resources. 

That server can be running locally, for example https://stackoverflow.com/questions/27977972/how-do-i-setup-a-local-http-server-using-python

You can also use `flutter run -d chrome --release` to serve a web build.

**Closed by jonahwilliams** 2020-10-08 19:44 UTC

**Comment by anoureddini** [comment] 2020-10-08 20:19
Thank you Jonah. I mistakenly duplicated the topic. I'll elaborate more on my question here: https://github.com/flutter/flutter/issues/67663
