### ISSUE TITLE
Several jobs not making progress or being scheduled?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#131192] opened 2023-07-24 14:14 UTC
<img width="676" alt="Screenshot 2023-07-24 at 7 13 50 AM" src="https://github.com/flutter/flutter/assets/6343103/f42810f5-7c21-4bd0-b310-d8953819b540">

**Comment by ricardoamador** [comment] 2023-07-24 15:14
It appears that the builds in yellow actually did complete but the dashboard was not able to update. I found quite a few errors in the scheduler where we were not able to complete what appears to be the update transaction due to database transaction aborted.

![image](https://github.com/flutter/flutter/assets/32242716/e2142054-4d12-4704-9743-dab7c1c7ed06)

**Comment by ricardoamador** [comment] 2023-07-24 15:24
Okay this is odd, 71 of the 72 errors are for the same commit in the postsubmit subscription, for `userData={commit_key: flutter/flutter/master/d7ed5dc2e212d164fd8733f34a832af10481cd8b, task_key: 6091431327170560}`

**Comment by ricardoamador** [comment] 2023-07-24 16:12
Yeah it appears that this is happening going back a ways. We are getting un'acked messages which is explainable by the error above. Let me see if I can find out if there are any changes to Datastore recently.

**Comment by zanderso** [comment] 2023-07-25 15:43
This issue appears to be more widespread this morning. Very concerned because the tree is still open, so commits are landing and testing is essentially stopped.

<img width="1244" alt="Screenshot 2023-07-25 at 8 42 49 AM" src="https://github.com/flutter/flutter/assets/6343103/83bce3b7-1b54-4627-9e97-1e3c9b155a4e">

**Comment by jonahwilliams** [comment] 2023-07-25 18:25
I see that the non flaky tasks appear to be running at ToT now. the flaky tasks still seem stuck though I'm not sure if that is prioritization or another issue.

**Comment by keyonghan** [comment] 2023-07-25 18:59
We are still seeing missed task updates, and are still investigating (most likely is related to transaction operation in Datastore). A new version has been deployed hopefully to mitigate the issue.

**Comment by keyonghan** [comment] 2023-07-26 00:55
A quick update: an earlier version has been rolled back. Culprit of the issue:
https://github.com/flutter/cocoon/pull/2949
https://github.com/flutter/cocoon/pull/2945

Both framework and engine trees are now open, with framework tree slowly catching up and engine tree missed tasks finished rescheduling.

A test version is been validated based on https://github.com/flutter/cocoon/pull/2950. Before that, we need to stop the cocoon daily deployment to avoid regression again.

**Comment by ricardoamador** [comment] 2023-07-26 03:10
Well we could stop the deployment but we do not have IAM permissions setup to pause the jobs. I will add that in the morning should we ever encounter this issue again.

**Comment by ricardoamador** [comment] 2023-07-26 22:25
Update here, we were able to identify an issue with one of the dependencies we are using for access to Datastore and have made a change to scheduler. It has been running with this change for around 4 hours now and tasks look to be getting updated correctly. I am going to let it run to make sure nothing bad happens and then deploy the change most likely tomorrow. So far everything looks okay.

**Comment by jonahwilliams** [comment] 2023-07-27 04:23
Most tasks seem to be running correctly, but for lack of a better term a large number of the flaky targets seem "stuck". Is there some manual intervention needed to get those running again?

**Comment by keyonghan** [comment] 2023-07-27 15:27
> Most tasks seem to be running correctly, but for lack of a better term a large number of the flaky targets seem "stuck". Is there some manual intervention needed to get those running again?

Focused on `prod` targets! Thanks for catching this. Just cleaned a bit of obsolete status of staging tasks, and they should catch up slowly.

**Comment by ricardoamador** [comment] 2023-07-28 16:58
Spoke with keyong, and we agreed to make the following reverts: 
https://github.com/flutter/cocoon/pull/2961
https://github.com/flutter/cocoon/pull/2960

New version was deployed without these changes to stabilize the builds.

**Comment by ricardoamador** [comment] 2023-07-28 16:59
Not sure why this was automatically closed again but reopening to make sure the new build does not have any issues.

**Comment by keyonghan** [comment] 2023-07-31 16:29
Seems we are hitting the grpc error again `The transaction was aborted.`:
![Screenshot 2023-07-31 at 9 29 04 AM](https://github.com/flutter/flutter/assets/54558023/1cee089d-2537-4795-a74e-e1b4cff60e94)

**Comment by ricardoamador** [comment] 2023-07-31 16:31
Yes but that is okay if the tasks are being updated. If we want to reduce this occurrence or lower the log level we either need to look at the cocurrency mode or switch this to a warning.

**Comment by ricardoamador** [comment] 2023-08-02 21:53
I was able to enable audit logging for Datastore so we will have to run some tests with the retry version from appengine.

**Comment by ricardoamador** [comment] 2023-08-03 21:50
Closing in favor of the tracking issue as this problem has been identified and resolved. The follow up issue tracks the work in order to be able to deal with and debug the updated packages.

**Closed by ricardoamador** 2023-08-03 21:50 UTC
Labels: team-infra, P0, triaged-infra
