### ISSUE TITLE
Trying to read plugins.flutter.io/package_info' for web causes Overflow on channel

### ISSUE THREAD

**Issue by phackwer** [flutter/flutter#59866] opened 2020-06-19 17:02 UTC
## Steps to Reproduce

1 - Add this to any code:

MethodChannel _kChannel =  MethodChannel('plugins.flutter.io/package_info');
final Map<String, dynamic> map =  await _kChannel.invokeMapMethod<String, dynamic>('getAll');

**Expected results:** 

To have  map["version"] and map["buildNumber"] populated as it happens on iOS and Android

**Actual results:** 

Overflow on channel: plugins.flutter.io/package_info.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to
adjust the buffer size if of the channel.
Error: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
    at Object.throw_ [as throw] (http://yoda-dev.threadable.io:8080/dart_sdk.js:4458:11)
    at MethodChannel._invokeMethod (http://yoda-dev.threadable.io:8080/packages/flutter/src/services/platform_channel.dart.lib.js:410:21)
    at _invokeMethod.next (<anonymous>)
    at http://yoda-dev.threadable.io:8080/dart_sdk.js:37107:33
    at _RootZone.runUnary (http://yoda-dev.threadable.io:8080/dart_sdk.js:36961:58)
    at _FutureListener.thenAwait.handleValue (http://yoda-dev.threadable.io:8080/dart_sdk.js:32048:29)
    at handleValueCallback (http://yoda-dev.threadable.io:8080/dart_sdk.js:32595:49)
    at Function._propagateToListeners (http://yoda-dev.threadable.io:8080/dart_sdk.js:32633:17)
    at _Future.new.[_completeWithValue] (http://yoda-dev.threadable.io:8080/dart_sdk.js:32476:23)
    at async._AsyncCallbackEntry.new.callback (http://yoda-dev.threadable.io:8080/dart_sdk.js:32498:35)
    at Object._microtaskLoop (http://yoda-dev.threadable.io:8080/dart_sdk.js:37222:13)
    at _startMicrotaskLoop (http://yoda-dev.threadable.io:8080/dart_sdk.js:37228:13)
    at http://yoda-dev.threadable.io:8080/dart_sdk.js:32850:9Application finished.

**Comment by TahaTesser** [comment] 2020-06-22 09:06
Hi @phackwer 
`package_info` isn't supported for web yet 
Closing as duplicate of https://github.com/flutter/flutter/issues/46609

**Closed by TahaTesser** 2020-06-22 09:06 UTC
