### ISSUE TITLE
Build APK for multiple target platforms

### ISSUE THREAD

**Issue by marnberg** [flutter/flutter#19275] opened 2018-07-11 18:48 UTC
Build the Android apk 
```
flutter build apk --release
```
Creates apk with:
`armeabi-v7a/libflutter.so`

but it is missing `libflutter.so` in:
`arm64-v8a/`

From the build help I see that I can choose arm64
``` 
flutter build apk -h
    --target-platform          [android-arm (default), android-arm64]
```
Running 
```
flutter build apk --release --target-platform android-arm64
```
includes `libflutter.so` in `arm64-v8a` but not `armeabi-v7a`

For the play store it multiple APKs can be uploaded but for our continues integration it would be handy to be able to make a fat APK that include all the platforms and work on all phones without special instructions.

Something like this:
```
flutter build apk --release --target-platforms [android-arm,android-arm64]
```

**Comment by mars3142** [comment] 2018-09-05 13:57
All ABI (arm, arm64, x86, x86_64) should be the default for https://github.com/flutter/flutter/issues/18840

**Comment by james-lawrence** [comment] 2018-12-22 23:52
this should really be fixed. seems odd to build a broken apk unexpectedly.

are there any workarounds that don't require building multiple apks?

**Comment by joakiti** [comment] 2019-01-23 16:21
Same issue.

**Comment by Intellugo** [comment] 2019-01-23 17:18
Thanks for posting this issue, just helped me solve a release issue I had with `Flutter Run --release` working **BUT** `Flutter build apk` + subsequence `Flutter Install` which will normally crash. Thanks :)

**Comment by ikakaxi** [comment] 2019-03-28 03:24
You can read this article.
https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd
It solved my problem.
I think it can also solve your problem.

Now I use `Flutter build apk` Only armeabi-v7a was generated
![image](https://user-images.githubusercontent.com/6301454/55127681-f701d400-514b-11e9-9383-c1bfa0ad15fd.png)

**Comment by mpetlyuk** [comment] 2019-04-24 19:25
> All ABI (arm, arm64, x86, x86_64) should be the default for #18840

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.4 18E226, locale ru-UA)
    • Flutter version 1.0.0 at /Users/maxim/flutter
    • Framework revision 5391447fae (5 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/maxim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/maxim/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.2
    • Dart plugin version 182.3569.4

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

My release apk contains only armeabi-v7 libflutter.so. What is the issue?

**Comment by mpetlyuk** [comment] 2019-04-24 19:36
> You can read this article.
> https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd
> It solved my problem.
> I think it can also solve your problem.
> 
> Now I use `Flutter build apk` Only armeabi-v7a was generated
> ![image](https://user-images.githubusercontent.com/6301454/55127681-f701d400-514b-11e9-9383-c1bfa0ad15fd.png)

How can it help if we talk about the workaround to build the APK that includes **all** ABI like the debug build does?

**Comment by ikakaxi** [comment] 2019-04-25 01:23
> > 你可以阅读这篇文章。
> > https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd 
> > 它解决了我的问题。
> > 我认为它也可以解决你的问题。
> > 现在我使用`Flutter build apk`只生成了armeabi-v7a
> > ![图片](https://user-images.githubusercontent.com/6301454/55127681-f701d400-514b-11e9-9383-c1bfa0ad15fd.png)
> 
> 如果我们谈论构建包含**所有** ABI（如调试版本）的APK的解决方法，它会如何帮助？

It can't do it because flutter only generates one copy into lib, I think flutter should provide commands to support all cpu, but now it does not provide

**Comment by ikakaxi** [comment] 2019-04-25 01:24
> > You can read this article.
> > https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd
> > It solved my problem.
> > I think it can also solve your problem.
> > Now I use `Flutter build apk` Only armeabi-v7a was generated
> > ![image](https://user-images.githubusercontent.com/6301454/55127681-f701d400-514b-11e9-9383-c1bfa0ad15fd.png)
> 
> How can it help if we talk about the workaround to build the APK that includes **all** ABI like the debug build does?

It can't do it because flutter only generates one copy into lib, I think flutter should provide commands to support all cpu, but now it does not provide

**Comment by mpetlyuk** [comment] 2019-04-26 07:03
> > > You can read this article.
> > > https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd
> > > It solved my problem.
> > > I think it can also solve your problem.
> > > Now I use `Flutter build apk` Only armeabi-v7a was generated
> > > ![image](https://user-images.githubusercontent.com/6301454/55127681-f701d400-514b-11e9-9383-c1bfa0ad15fd.png)
> > 
> > 
> > How can it help if we talk about the workaround to build the APK that includes **all** ABI like the debug build does?
> 
> It can't do it because flutter only generates one copy into lib, I think flutter should provide commands to support all cpu, but now it does not provide

Absolutely agreed. If they are worried about the APK size, then it should be left to the discretion of the developer. We should have the ability to build universal apk. 

I have tested **split** config in gradle, but anyway there is the only lib inside all APK outputs.

**Comment by ikakaxi** [comment] 2019-04-26 07:18
> > > > You can read this article.
> > > > https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd
> > > > It solved my problem.
> > > > I think it can also solve your problem.
> > > > Now I use `Flutter build apk` Only armeabi-v7a was generated
> > > > ![image](https://user-images.githubusercontent.com/6301454/55127681-f701d400-514b-11e9-9383-c1bfa0ad15fd.png)
> > > 
> > > 
> > > How can it help if we talk about the workaround to build the APK that includes **all** ABI like the debug build does?
> > 
> > 
> > It can't do it because flutter only generates one copy into lib, I think flutter should provide commands to support all cpu, but now it does not provide
> 
> Absolutely agreed. If they are worried about the APK size, then it should be left to the discretion of the developer. We should have the ability to build universal apk.
> 
> I have tested **split** config in gradle, but anyway there is the only lib inside all APK outputs.

yes, maybe at the beginning, Google is worried that the size of the app will be too large to affect the popularize, but now it should provide options that can be run on all CPUs. and that the size of the app  should let the developers choose.

**Comment by jonahwilliams** [comment] 2019-05-21 17:07
Duplicate of https://github.com/flutter/flutter/issues/18494

**Closed by jonahwilliams** 2019-05-21 17:07 UTC
Labels: severe: new feature, t: gradle, tool
