### ISSUE TITLE
Interactive Code does not Compile on Browser.

### ISSUE THREAD

**Issue by parjanyaacoder** [flutter/flutter#84430] opened 2021-06-11 10:28 UTC
### ****AnimatedSize**** 

The Intercative code of AnimatedSize class does not compile and the sample code is correct. 

Steps to reproduce the error - .

1.  Open this Url. [AnimatedSize Class](https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html)
2.  Select Interactive App. 
3.  Click on Run. The code does not compile. 
4.  Add this line.   
     `AnimatedSize(vsync:this,)
 // vsync is a required field for AnimatedSize
`

5.  Click on Run. The code compiles. 

Please allow me to solve this issue. Help required.

**Comment by TahaTesser** [comment] 2021-06-11 13:08
Hi @parjanyaacoder 
This is a duplicate of https://github.com/flutter/flutter/issues/82619 https://github.com/flutter/flutter/issues/83604 https://github.com/flutter/flutter/issues/83606

**Closed by TahaTesser** 2021-06-11 13:08 UTC
Labels: in triage
