### ISSUE TITLE
Android Studio (version unknown)     ✗ Unable to determine Android Studio version.     ✗ Unable to find bundled Java version.

### ISSUE THREAD

**Issue by craftedcodes** [flutter/flutter#141566] opened 2024-01-15 12:01 UTC
### Steps to reproduce

1. Open terminal
2. Run flutter doctor -v

### Expected results

When running the flutter doctor command in Android Studio Hedgehog | 2023.1.1 Patch 1, I expect it to correctly determine the Android Studio version and provide information about the Flutter development environment without any errors. There should be no "Unable to determine Android Studio version" error, and the command should run smoothly.

### Actual results

When running the flutter doctor -v command in Android Studio Hedgehog | 2023.1.1 Patch 1, I am encountering the following error:
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
    
    
This problem also occurred when I was still using Android Studio Giraffe and I re-installed and updated everything.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter doctor -v
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Android Studio (version unknown)
    • Android Studio at /Users/XXX/iCloud Drive (Archiv)/Desktop/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
```

</details>
<img width="559" alt="Bildschirmfoto 2024-01-15 um 12 58 41" src="https://github.com/flutter/flutter/assets/65518042/8fe33124-6c80-4eb9-bcb2-17075e40d4b1">

**Comment by dam-ease** [comment] 2024-01-15 14:15
Thanks for filing this @craftedcodes.
Can you please share the full output of your `flutter doctor -v`?
I see there are some open issues similar to this but reproduced on macOS and Linux.

**Comment by craftedcodes** [comment] 2024-02-06 16:52
Sorry, I just saw it. It's already solved. Reason was that there was an Android Studio Preview verison. More details can be found here: https://medium.com/@craftedcodes/the-syntax-chronicles-solution-for-flutter-doctor-and-android-studio-detection-on-macos-305c30959649

**Comment by dam-ease** [comment] 2024-02-07 06:42
Thanks for your response @craftedcodes 
Per your last comment, I’ll be closing this since it has been solved

**Closed by dam-ease** 2024-02-07 06:42 UTC
Labels: in triage
