### ISSUE TITLE
Black screen before app launch

### ISSUE THREAD

**Issue by Amine-Smahi** [flutter/flutter#50912] opened 2020-02-17 10:40 UTC
Steps :
1) Create a flutter app
2) Run the flutter app

![problem](https://user-images.githubusercontent.com/24621701/74646418-1e093000-517a-11ea-8484-ba23fc06fcfd.gif)

**Comment by TahaTesser** [comment] 2020-02-17 10:41
Hi @Amine-Smahi 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Amine-Smahi** [comment] 2020-02-17 10:44
![image](https://user-images.githubusercontent.com/24621701/74646860-e6e74e80-517a-11ea-80e2-039cecb1ff7d.png)

**Comment by Amine-Smahi** [comment] 2020-02-17 10:46
[  +23 ms] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git -c log.showSignature=false log -n1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git describe --match v*.*.*
--first-parent --long --tags
[  +28 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +6 ms] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git rev-parse --abbrev-ref --symbolic@{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] origin/stable
[   +1 ms] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +86 ms] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +135 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +25 ms] Exit code 0 from: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
           8D4P8TMJN7LFW4EQ       device product:Allure_M1 model:Allure_M1 device:Allure_M1 transport_id:1
[  +20 ms] C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ shell getprop
[ +114 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +15 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +151 ms] Generating
C:\Users\moham\Documents\dev\flutter\try2\myapp2\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +49 ms] ro.hardware = mt6755
[   +1 ms] ro.build.characteristics = default
[  +66 ms] Launching lib\main.dart on Allure M1 in debug mode...
[  +12 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\moham\Documents\dev\flutter\try2\myapp2\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +12 ms] Exit code 0 from: C:\Users\moham\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\moham\Documents\dev\flutter\try2\myapp2\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.myapp2" (Raw: "com.example.myapp2")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="myapp2" (Raw: "myapp2")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.myapp2.MainActivity" (Raw: "com.example.myapp2.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +18 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ shell -x logcat -v time -t 1
[ +110 ms] Exit code 0 from: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           02-17 11:45:49.620 D/AALLightSensor(  425): newLux = 1, [0, 0] -> 0
[  +18 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +2 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ logcat -v time -T 02-17 11:45:49.620
[  +45 ms] Android Debug Bridge version 1.0.40
           Version 4986621
           Installed as C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +8 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +36 ms] Building APK
[  +27 ms] Running Gradle task 'assembleDebug'...
[   +7 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from C:\Users\moham\Documents\dev\flutter\try2\myapp2\android\gradlew.bat.
[  +27 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +70 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_152-release"
           OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
           OpenJDK 64-Bit Server VM (build 25.152-b01, mixed mode)
[   +6 ms] executing: [C:\Users\moham\Documents\dev\flutter\try2\myapp2\android\]
C:\Users\moham\Documents\dev\flutter\try2\myapp2\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\moham\Documents\dev\flutter\try2\myapp2\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm64 assembleDebug
[ +655 ms] Welcome to Gradle 5.6.2!
[   +3 ms] Here are the highlights of this release:
[   +3 ms]  - Incremental Groovy compilation
[   +1 ms]  - Groovy compile avoidance
[   +1 ms]  - Test fixtures for Java projects
[   +1 ms]  - Manage plugin versions via settings script
[   +8 ms] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[+3197 ms] > Task :app:compileFlutterBuildDebug
[   +3 ms] [  +25 ms] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [   +1 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] [        ] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git describe --match
v*.*.* --first-parent --long --tags
[        ] [  +26 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.8-0-g0b8abb472
[        ] [  +14 ms] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git rev-parse --abbrev-ref--symbolic @{u}
[   +2 ms] [  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git ls-remote --get-url
origin
[   +1 ms] [  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +66 ms] executing: [E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\] git rev-parse --abbrev-refHEAD
[   +1 ms] [  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[   +3 ms] [  +23 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [  +96 ms] Initializing file store
[        ] [  +15 ms] Done initializing file store
[ +712 ms] [+1407 ms] Skipping target: kernel_snapshot
[   +2 ms] [  +57 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +198 ms] [ +151 ms] debug_android_application: Complete
[   +3 ms] [  +25 ms] Persisting file store
[   +3 ms] [  +14 ms] Done persisting file store
[   +1 ms] [   +6 ms] build succeeded.
[  +16 ms] [  +16 ms] "flutter assemble" took 1 849ms.
[ +190 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +4 ms] > Task :app:preBuild UP-TO-DATE
[  +81 ms] > Task :app:preDebugBuild UP-TO-DATE
[  +12 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[  +17 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[  +11 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +3 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugAssets
[ +245 ms] > Task :app:copyFlutterAssetsDebug
[   +3 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[  +98 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +9 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +3 ms] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[   +3 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +5 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +2 ms] > Task :app:compileDebugSources UP-TO-DATE
[  +96 ms] > Task :app:processDebugJavaRes NO-SOURCE
[  +43 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[  +10 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[  +23 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +11 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[ +153 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[  +13 ms] > Task :app:mergeDexDebug UP-TO-DATE
[  +13 ms] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[ +387 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +5 ms] Compatible side by side NDK version was not found.
[   +1 ms] > Task :app:packageDebug UP-TO-DATE
[   +1 ms] > Task :app:assembleDebug UP-TO-DATE
[   +3 ms] BUILD SUCCESSFUL in 5s
[        ] 30 actionable tasks: 4 executed, 26 up-to-date
[ +338 ms] Running Gradle task 'assembleDebug'... (completed in 6,8s)
[  +63 ms] calculateSha: LocalDirectory: 'C:\Users\moham\Documents\dev\flutter\try2\myapp2\build\app\outputs\apk'/app.apk
[  +78 ms] calculateSha: reading file took 72us
[ +652 ms] calculateSha: computing sha took 649us
[  +11 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[   +3 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\moham\Documents\dev\flutter\try2\myapp2\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +20 ms] Exit code 0 from: C:\Users\moham\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\moham\Documents\dev\flutter\try2\myapp2\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +8 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.myapp2" (Raw: "com.example.myapp2")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="myapp2" (Raw: "myapp2")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.myapp2.MainActivity" (Raw: "com.example.myapp2.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on Allure M1.
[   +7 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ shell am force-stop com.example.myapp2[+1130 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ shell pm list packages
com.example.myapp2
[ +790 ms] package:com.example.myapp2
[   +6 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ shell cat
/data/local/tmp/sky.com.example.myapp2.sha1
[  +37 ms] 8ce14344e0863c0fd58337693481777f325e7712
[   +2 ms] Latest build already installed.
[   +5 ms] Allure M1 startApp
[   +2 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true
--ez verify-entry-points true com.example.myapp2/com.example.myapp2.MainActivity
[ +846 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.myapp2/.MainActivity (has extras) }
[   +2 ms] Waiting for observatory port to be available...
[ +258 ms] D/FlutterActivity(15609): Using the launch theme as normal theme.
[   +6 ms] D/FlutterActivityAndFragmentDelegate(15609): Setting up FlutterEngine.
[        ] D/FlutterActivityAndFragmentDelegate(15609): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this
FlutterFragment.
[ +461 ms] D/FlutterActivityAndFragmentDelegate(15609): Attaching FlutterEngine to the Activity that owns this Fragment.
[  +73 ms] D/FlutterView(15609): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@a1e4cf9
[  +21 ms] D/FlutterActivityAndFragmentDelegate(15609): Executing Dart entrypoint: main, and sending initial route: /
[ +157 ms] Observatory URL on device: http://127.0.0.1:55318/Zdqyk9k4JYI=/
[   +2 ms] executing: C:\Users\moham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 8D4P8TMJN7LFW4EQ forward tcp:0 tcp:55318
[  +23 ms] 55038
[   +2 ms] Forwarded host port 55038 to device port 55318 for Observatory
[  +16 ms] Connecting to service protocol: http://127.0.0.1:55038/Zdqyk9k4JYI=/
[ +609 ms] Successfully connected to service protocol: http://127.0.0.1:55038/Zdqyk9k4JYI=/
[   +5 ms] Sending to VM service: getVM({})
[  +10 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: MT6755V/C, operatingSystem: android, targetCPU: arm64, version: 2.7.0
(Fri Dec 6 16:26:51 2019 +0100) on "android_arm64", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 15609, startTime: 1581...
[   +6 ms] Sending to VM service: getIsolate({isolateId: isolates/3583348236765859})
[  +12 ms] Sending to VM service: _flutter.listViews({})
[  +11 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7e6b453220, isolate: {type: @Isolate, fixedId: true,
id: isolates/3583348236765859, name: main.dart$main-3583348236765859, number: 3583348236765859}}]}
[   +8 ms] DevFS: Creating new filesystem on the device (null)
[   +5 ms] Sending to VM service: _createDevFS({fsName: myapp2})
[  +41 ms] Result: {type: Isolate, id: isolates/3583348236765859, name: main, number: 3583348236765859, _originNumber: 3583348236765859,
startTime: 1581936361094, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[  +60 ms] Result: {type: FileSystem, name: myapp2, uri: file:///data/user/0/com.example.myapp2/code_cache/myapp2UUQCMO/myapp2/}
[   +2 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.myapp2/code_cache/myapp2UUQCMO/myapp2/)
[   +4 ms] Updating assets
[  +98 ms] Syncing files to device Allure M1...
[   +5 ms] Scanning asset files
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +7 ms] E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\bin\cache\dart-sdk\bin\dart.exe
E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
E:\amine\Courses\Courses\flutter\flutter_windows_v1.12.13+hotfix.8-stable\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\moham\AppData\Local\Temp\flutter_tool.928748db-5172-11ea-ad50-509a4cbcb389\app.dill --packages
C:\Users\moham\Documents\dev\flutter\try2\myapp2\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[  +16 ms] <- compile package:myapp2/main.dart
[+2398 ms] E/AccessibilityBridge(15609): VirtualView node must not be the root node.
[  +58 ms] D/GraphicBuffer(15609): register, handle(0x7e3863d040) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
[+3566 ms] Updating files
[ +906 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Allure M1... (completed in 6 963ms, longer than expected)
[   +1 ms] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[  +10 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7e6b453220, isolate: {type: @Isolate, fixedId: true, id: isolates/3583348236765859, name:
main.dart$main-3583348236765859, number: 3583348236765859}}]}
[   +2 ms] <- accept
[  +16 ms] Connected to _flutterView/0x7e6b453220.
[   +3 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +2 ms] An Observatory debugger and profiler on Allure M1 is available at: http://127.0.0.1:55038/Zdqyk9k4JYI=/
[   +1 ms] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

**Comment by Amine-Smahi** [comment] 2020-02-17 10:47
For the code part, its just the default flutter create app

**Comment by TahaTesser** [comment] 2020-02-17 10:51
Duplicate of [#47024](https://github.com/flutter/flutter/issues/47024)

**Closed by TahaTesser** 2020-02-17 10:51 UTC
