### ISSUE TITLE
[Desktop]Space cannot be entered into TextField inside a ListTile

### ISSUE THREAD

**Issue by PeterNjeim** [flutter/flutter#97490] opened 2022-01-30 07:12 UTC
Duplicate of https://github.com/flutter/flutter/issues/90907. The reason this is being created is because that issue got closed due to a merged PR which solved the issue: https://github.com/flutter/flutter/pull/91129, however this PR was later reverted due to failing tests: https://github.com/flutter/flutter/pull/92544, but now the original issue has been locked by the github bot due to inactivity and so I cannot comment on it.

Not asking for help, just creating attention for the original issue as I unfortunately think that the flutter devs don't know of its existence due to it being closed. Thanks in advance for whoever inevitably fixes the issue.

*Reproducible steps copied from the original issue*

## Steps to Reproduce

1. flutter create bug
2. create TextField inside ListTile. Or Copy my main.dart
3. Run on windows-x64
4. Try to type "Test Typing wow"

**Expected results:** 
"Test Typing wow"

**Actual results:** 
"TestTypingwow"

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: ListTile(
              title: TextField(
                
              ),
            ),
      ),
    );
  }
}
```

**Comment by maheshmnj** [comment] 2022-01-31 08:38
Hi @PeterNjeim, Thanks for bringing this to notice, I am able to reproduce the issue on stable and the master channel. space key doesn't work with the above code sample also there is some ripple effect in the text field on pressing space key.

*Output from the master channel*

https://user-images.githubusercontent.com/31410839/151761283-711aed7e-dc92-4367-9add-b374d0186c8e.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.319, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.319 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 120d25f786 (3 days ago), 2022-01-28 12:40:06 +0200
    • Engine revision c5ee2e4c35
    • Dart version 2.17.0 (build 2.17.0-66.0.dev)
    • DevTools version 2.10.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-01-31 09:28
cc: @justinmc

**Comment by AlexVegner** [comment] 2022-01-31 17:44
@maheshmnj @HansMuller 
Seme for Android, iOS.

**Comment by AlexVegner** [comment] 2022-02-01 13:06
@HansMuller @maheshmnj @PeterNjeim 
I have found workaround: 
```dart
  Widget workaroud() {
    return ListTile(
      title: Shortcuts(
        shortcuts: <ShortcutActivator, Intent>{
          const SingleActivator(LogicalKeyboardKey.space): SpaceKeyIntent(),
        },
        child: Actions(
          actions: {
            SpaceKeyIntent: CallbackAction<SpaceKeyIntent>(
              onInvoke: (SpaceKeyIntent intent) {
                _insertSpaceCharacter();
              },
            ),
          },
          child: TextField(
            controller: widget.controller,
          ),
        ),
      ),
    );
  }

  void _insertSpaceCharacter() {
    final inserted = ' ';
    if (widget.controller != null) {
      final text = widget.controller!.text;
      final selection = widget.controller!.selection;
      final newText =
          text.replaceRange(selection.start, selection.end, inserted);
      widget.controller!.value = TextEditingValue(
        text: newText,
        selection: TextSelection.collapsed(
            offset: selection.baseOffset + inserted.length),
      );
    }
  }

class SpaceKeyIntent extends Intent {}
```

**Comment by maheshmnj** [comment] 2022-02-01 13:15
> Seme for Android and iOS with hardware keyboard

Thanks for the info @PeterNjeim, I can confirm it on Android and IOS. This purely looks like a framework issue.

https://user-images.githubusercontent.com/31410839/151975135-37dadd94-b2e7-470b-8ab7-61c6a3b8973e.mov

**Comment by gspencergoog** [comment] 2022-02-03 19:13
It seems like we should just re-land the original PR (with changes so it won't cause failures, obv). (Desktop triage)

**Comment by justinmc** [comment] 2022-03-08 21:31
I believe this should be fixed with https://github.com/flutter/flutter/pull/98469, but let me know if anyone still sees this problem.

**Closed by justinmc** 2022-03-08 21:31 UTC
Labels: a: text input, framework, f: material design, a: desktop, has reproducible steps, P4, found in release: 2.8, found in release: 2.10
