### ISSUE TITLE
To set different colors for containers within a container and also add rounded corners

### ISSUE THREAD

**Issue by weeidl** [flutter/flutter#134712] opened 2023-09-14 06:11 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- Place one container inside another container
- Give them different colors, for example, make the first container red and the second one gray
- And also add borderRadius: BorderRadius.all(Radius.circular(20)) to both containers

### Expected results

To prevent the parent container from exceeding the boundaries of the child container

### Actual results

The lower container protrudes slightly from the parent container, and the color is visible. You can see it more clearly in the screenshots.

### Code sample

<details><summary>Code sample</summary>

```dart
Container(
      height: 200,
      width: 200,
      decoration: const BoxDecoration(
        borderRadius: BorderRadius.all(Radius.circular(20)),
        color: Colors.red,
      ),
      child: Container(
        height: 200,
        width: 200,
        decoration: const BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(20)),
          color: Colors.grey,
        ),
      ),
    ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots</summary>
<img width="388" alt="image" src="https://github.com/flutter/flutter/assets/35844015/8a75df05-d522-41d1-8cb5-73a16019fd3c">
<img width="84" alt="Screenshot 2023-09-14 at 09 05 44" src="https://github.com/flutter/flutter/assets/35844015/0fd2dc61-4ae5-41dc-b5ac-a24eb72d3b30">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment] 2023-09-14 10:08
There is a known issue with a similar case https://github.com/flutter/flutter/issues/132911 but it's a duplicate of https://github.com/flutter/flutter/issues/14288. Please follow up on it for updates.

**Closed by huycozy** 2023-09-14 10:08 UTC
Labels: in triage
