### ISSUE TITLE
Upgrading to recent flutter throwing up some error.

### ISSUE THREAD

**Issue by KamalPatra** [flutter/flutter#36817] opened 2019-07-24 08:27 UTC
This is what the error is:
Gradle task assembleAarDebug failed with exit code 1

FAILURE: Build failed with an exception.

* Where:
Script '/Users/kamal369/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 946

* What went wrong:
Execution failed for task ':app:buildPluginDebugFirebaseAuth'.
> Process 'command '/Users/kamal369/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by skordesign** [comment] 2019-07-24 13:36
I have same problem.

**Comment by KamalPatra** [comment] 2019-07-24 14:03
I have tried manually migrating the app to androidX and now it shows the following in red:

* Error running Gradle:
ProcessException: Process "/Users/kamal369/AndroidStudioProjects/rent_me/android/gradlew" exited abnormally:

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
  Command: /Users/kamal369/AndroidStudioProjects/rent_me/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by prasant10050** [comment] 2019-07-24 14:03
i m also facing same issue
Gradle task assembleAarDebug failed with exit code 1

FAILURE: Build failed with an exception.

* Where:
Script '/home/me/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 946

* What went wrong:
Execution failed for task ':app:buildPluginDebugPermissionHandler'.
> Process 'command '/home/me/Flutter/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 15s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by skordesign** [comment] 2019-07-24 14:26
I've switched to stable channel. It just works fine for now.

**Comment by KamalPatra** [comment] 2019-07-24 14:34
What channel?

**Comment by skordesign** [comment] 2019-07-24 14:37
If you're using master branch, switch to stable: **flutter channel stable**

**Comment by KamalPatra** [comment] 2019-07-24 15:36
I still face the same issue, as I have made some changes to migrate the app to AndroidX.. i have mentioned the errors above.

**Comment by blasten** [comment] 2019-07-24 18:08
This is a duplicate of https://github.com/flutter/flutter/issues/36842.

**Comment by KamalPatra** [comment] 2019-07-24 18:33
@blasten Don't you guys see the time of issue created or comment. I have created this before the one you have mentioned above. That is the duplicate not mine. Thanks!!

**Comment by blasten** [comment] 2019-07-25 01:04
This is definitely fix by https://github.com/flutter/flutter/pull/36886

**Closed** 2019-07-25 15:49 UTC
Labels: a: build, t: gradle
