### ISSUE TITLE
`ExpansionTileController` is unusable if the `ExpansionTile` changes

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#152005] opened 2024-07-18 23:10 UTC
### Steps to reproduce

My use case is that I have a list of expansion tiles, initially collapsed. When the user types in a search box, the list should be filtered by the search query, and any remaining expansion tiles should expand. This is for UX, as there are too many total children to show all of them before the user starts searching. 

My approach was to maintain a list of `ExpansionTileController`s and call `.expand()` on the ones that match the search. But since the ones that don't fit the search are hidden, they are disposed, and they dissociate their state from the controllers. Which means if an expansion tile wasn't searched for before, it will dispose itself, and now the controller will throw errors if I try to use it in future searches. 

I pasted a reproducible example in the dropdowns below. I'm not sure but I believe https://github.com/flutter/flutter/issues/138153 or https://github.com/flutter/flutter/issues/138916 will fix this. 

### Expected results

I would like the controllers to collapse or expand the expansion tiles they are currently attached to when I call them, despite having passed the controller to a different expansion tile previously.

### Actual results

If the `ExpansionTile` has previously been removed from the page, trying to expand or collapse it with the controller results in the following error: 

```
'package:flutter/src/material/expansion_tile.dart': Failed assertion: line 77 pos 12: '_state != null': is not true.
```

This is an assertion in debug mode, but the code uses `!` in release mode: 
https://github.com/flutter/flutter/blob/978657becd854b0b5ced80d372bdfc9b82da19b0/packages/flutter/lib/src/material/expansion_tile.dart#L76-L81

### Code sample

<details open><summary>Code sample</summary>

```dart
import "package:flutter/material.dart";

void main() => runApp(MaterialApp(home: SearchPage()));

class SearchPage extends StatefulWidget {
  @override
  SearchState createState() => SearchState();
}

class SearchState extends State<SearchPage> {
  static const ids = [
    "hello", "world", "example", "stuff", "etc",
  ];

  final controllers = {
    for (final id in ids)
      id: ExpansionTileController(),
  };

  Iterable<String> filtered = ids;

  void search(String query) {
    setState(() => filtered = ids.where((id) => query.isEmpty || id.contains(query)));
    for (final id in filtered) {
      // Error: 'package:flutter/src/material/expansion_tile.dart': 
      // Failed assertion: line 77 pos 12: '_state != null': is not true.
      controllers[id]?.expand();
    }
  }

  @override
  Widget build(BuildContext context) => ListView(
    children: [
      TextField(
        onChanged: search,
      ),
      for (final id in filtered)
        ExpansionTile(
          key: ValueKey(id),
          title: Text(id),
          controller: controllers[id],
          children: [
            for (final other in ids) Text(other),
          ],
        ),
    ],
  );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

════════ Exception caught by widgets ═══════════════════════════════════════════
The following assertion was thrown while calling onChanged:
'package:flutter/src/material/expansion_tile.dart': Failed assertion: line 77 pos 12: '_state != null': is not true.

When the exception was thrown, this was the stack:
#2      ExpansionTileController.expand (package:flutter/src/material/expansion_tile.dart:77:12)
expansion_tile.dart:77
#3      SearchState.search (package:trinket/src/widgets/tasks/sidebar.dart:112:24)
sidebar.dart:112
#4      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:4186:27)
editable_text.dart:4186
#5      EditableTextState.userUpdateTextEditingValue (package:flutter/src/widgets/editable_text.dart:4550:5)
editable_text.dart:4550
#6      EditableTextState._replaceText (package:flutter/src/widgets/editable_text.dart:4934:5)
editable_text.dart:4934
#7      CallbackAction.invoke (package:flutter/src/widgets/actions.dart:597:39)
actions.dart:597
#8      Action._invoke (package:flutter/src/widgets/actions.dart:338:17)
actions.dart:338
#9      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:641:19)
actions.dart:641
#10     Actions.invoke.<anonymous closure> (package:flutter/src/widgets/actions.dart:966:48)
actions.dart:966
#11     Actions._visitActionsAncestors (package:flutter/src/widgets/actions.dart:748:18)
actions.dart:748
#12     Actions.invoke (package:flutter/src/widgets/actions.dart:960:30)
actions.dart:960
#13     _DeleteTextAction.invoke (package:flutter/src/widgets/editable_text.dart:5820:20)
editable_text.dart:5820
#14     _OverridableContextAction.invokeDefaultAction (package:flutter/src/widgets/actions.dart:1806:28)
actions.dart:1806
#15     _OverridableActionMixin.invoke (package:flutter/src/widgets/actions.dart:1671:9)
actions.dart:1671
#16     Action._invoke (package:flutter/src/widgets/actions.dart:336:19)
actions.dart:336
#17     ActionDispatcher.invokeActionIfEnabled (package:flutter/src/widgets/actions.dart:666:28)
actions.dart:666
#18     ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:907:83)
shortcuts.dart:907
#19     _ShortcutsState._handleOnKeyEvent (package:flutter/src/widgets/shortcuts.dart:1098:20)
shortcuts.dart:1098
#20     _HighlightModeManager.handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:2073:39)
focus_manager.dart:2073
#21     KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1100:34)
hardware_keyboard.dart:1100
#22     KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1172:17)
hardware_keyboard.dart:1172
#23     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
platform_channel.dart:235
#24     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
binding.dart:581
#25     _invoke2 (dart:ui/hooks.dart:344:13)
hooks.dart:344
#26     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
channel_buffers.dart:45
#27     _Channel.push (dart:ui/channel_buffers.dart:135:31)
channel_buffers.dart:135
#28     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
channel_buffers.dart:343
#29     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
platform_dispatcher.dart:750
#30     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
hooks.dart:257
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Users\KDAB\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\KDAB\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35013.160
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\KDAB\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.128
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.102

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by Levi-Lesches** [comment] 2024-07-18 23:16
My workaround is to leverage `ExpansionTileController.of` to get the current controller correctly. I use `maintainState: true` so the children elements are forced to be drawn even when hidden (which probably incurs a performance penalty since `Offstage` is no longer being used), then used a `Builder` to get that expansion tile's controller and open or close it based on the query. Here's that code: 
```dart
        children: [
          for (final child in children)
            if (child.isWhatIwant) Builder(
              builder: (context) {
                // We want the default state to be closed, unless this element was searched for
                // Note that keeping the controller in the view model does not work as the controllers
                // are automatically disposed when scrolled out of view and are unusable after that.
                if (model.filter.isNotEmpty) Timer.run(ExpansionTileController.of(context).expand);
                if (model.filter.isEmpty) Timer.run(ExpansionTileController.of(context).collapse);
                return Padding(...),

**Comment by danagbemava-nc** [comment] 2024-07-19 10:02
Reproducible using the sample provided above. 

### Steps to reproduce

- Run the code sample. 
- Type some text in the textfield to filter out some of the tiles
- Clear the textfield


<details>
<summary>complete sample</summary>

```dart
import "package:flutter/material.dart";

void main() => runApp(MaterialApp(home: SearchPage()));

class SearchPage extends StatefulWidget {
  @override
  SearchState createState() => SearchState();
}

class SearchState extends State<SearchPage> {
  static const ids = [
    "hello", "world", "example", "stuff", "etc",
  ];

  final controllers = {
    for (final id in ids)
      id: ExpansionTileController(),
  };

  Iterable<String> filtered = ids;

  void search(String query) {
    setState(() => filtered = ids.where((id) => query.isEmpty || id.contains(query)));
    for (final id in filtered) {
      // Error: 'package:flutter/src/material/expansion_tile.dart': 
      // Failed assertion: line 77 pos 12: '_state != null': is not true.
      controllers[id]?.expand();
    }
  }

  @override
  Widget build(BuildContext context) => Scaffold(
    body: ListView(
      children: [
        TextField(
          onChanged: search,
        ),
        for (final id in filtered)
          ExpansionTile(
            key: ValueKey(id),
            title: Text(id),
            controller: controllers[id],
            children: [
              for (final other in ids) Text(other),
            ],
          ),
      ],
    ),
  );
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.22.3 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (2 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
```

````
[✓] Flutter (Channel master, 3.24.0-1.0.pre.197, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0-1.0.pre.197 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0bac2be379 (6 hours ago), 2024-07-19 00:15:26 -0400
    • Engine revision ea1e53a4e8
    • Dart version 3.6.0 (build 3.6.0-55.0.dev)
    • DevTools version 2.37.1
```
</details>

**Comment by Piinks** [comment] 2024-07-24 18:56
> I believe https://github.com/flutter/flutter/issues/138153 or https://github.com/flutter/flutter/issues/138916 will fix this.

I believe you are correct! I am going to close this issue then since it is covered there. This will be linked to those issues now for future reference. Thanks!

**Closed by Piinks** 2024-07-24 18:56 UTC
Labels: framework, f: material design, a: error message, has reproducible steps, team-design, found in release: 3.22, found in release: 3.24

**Comment by Levi-Lesches** [comment] 2024-07-24 19:48
Just as a note, those issues aren't reporting bugs, but possible enhancements. The PR in #138153 has possible issues and #138916 can be worked around by re-using the controller. The latter is closer to this but this issue is an actual error, so I clarified that in my comment in #138916
