### ISSUE TITLE
.dart_tool/package_config.json does not exist on Flutter 2.12.0-4.1.pre

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#100350] opened 2022-03-18 05:08 UTC
Error: https://github.com/flutter/samples/runs/5595965164?check_suite_focus=true#step:5:72
Context: https://github.com/flutter/samples/pull/1053

```console
== Testing 'add_to_app/books/flutter_module_books' on Flutter's beta channel ==
~/work/samples/samples/add_to_app/books/flutter_module_books ~/work/samples/samples
Running "flutter pub get" in flutter_module_books...                4.7s
/opt/hostedtoolcache/flutter/2.12.0-4.1.pre-beta/x64/packages/flutter_tools/.dart_tool/package_config.json does not exist.Did you run this command from the same directory as your pubspec.yaml file?

Error: Process completed with exit code 1.
```

Flutter doctor output: 
```console
[✓] Flutter (Channel beta, 2.12.0-4.1.pre, on Ubuntu 20.04.4 LTS 5.11.0-1028-azure, locale C.UTF-8)
    • Flutter version 2.12.0-4.1.pre at /opt/hostedtoolcache/flutter/2.12.0-4.1.pre-beta/x64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 680962aa75 (32 hours ago), 2022-03-16 13:[46](https://github.com/flutter/samples/runs/5595917505?check_suite_focus=true#step:5:46):03 -0700
    • Engine revision e9f57b5d0f
    • Dart version 2.17.0 (build 2.17.0-182.1.beta)
    • DevTools version 2.11.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /usr/local/lib/android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /usr/local/lib/android/sdk
    • ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
    • Java binary at: /opt/hostedtoolcache/jdk/12.0.2/x64/bin/java
    • Java version OpenJDK Runtime Environment Zulu12.3+11-CA (build 12.0.2+3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.[47](https://github.com/flutter/samples/runs/5595917505?check_suite_focus=true#step:5:47)[58](https://github.com/flutter/samples/runs/5595917505?check_suite_focus=true#step:5:58).102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by sigurdm** [comment] 2022-03-18 10:09
Seems like the package_config.json does not load.

The error is thrown from here:

https://github.com/flutter/flutter/blob/5398c34cfeadc5796665ac4dae64647a8972fbd4/packages/flutter_tools/lib/src/dart/package_map.dart#L38

Could you try running with `--verbose` somehow?

**Comment by domesticmouse** [comment] 2022-03-18 12:53
@sigurdm is the following helpful?

https://github.com/flutter/samples/runs/5599349696?check_suite_focus=true#step:5:69

**Comment by sigurdm** [comment] 2022-03-18 13:32
It seems like the `flutter_module_books/.dart_tool/package_config.json` gets written:
```
[   +1 ms] IO  : Writing 8765 characters to text file .dart_tool/package_config.json.
[        ] FINE: Contents:
[        ]     | {
[        ]     |   "configVersion": 2,
[        ]     |   "packages": [
[        ]     |     {
......
[        ]     |     {
[        ]     |       "name": "flutter_module_books",
[        ]     |       "rootUri": "../",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.7"
[        ]     |     }
[        ]     |   ],
[        ]     |   "generated": "2022-03-18T11:03:45.833890Z",
[        ]     |   "generator": "pub",
[        ]     |   "generatorVersion": "2.17.0-182.1.beta"
[        ]     | }
```
And then it tries to load the package_config of flutter_tools:
```
[  +79 ms] Running "flutter pub get" in flutter_module_books... (completed in 6.9s)
[  +86 ms] Invalid argument (file): File cannot be read: "file:///opt/hostedtoolcache/flutter/2.12.0-4.1.pre-beta/x64/packages/flutter_tools/.dart_tool/package_config.json"
```
The "File cannot be read" comes from:
https://github.com/flutter/flutter/blob/use_package_config_in_build_info/.pub_cache/hosted/pub.dartlang.org/package_config-2.0.2/lib/src/package_config_io.dart#L102

Loading the package_config.json of flutter_tools probably comes from:
https://github.com/flutter/flutter/blob/f523ddd2d6ab0eb403aea5b3726c23b90733e0d2/packages/flutter_tools/lib/src/flutter_cache.dart#L88

Still not sure what has changed here, or what is going wrong. I doubt it is a pub issue.

**Comment by domesticmouse** [comment] 2022-03-18 13:50
My concern is this code path is working fine with stable, and has been working pretty much unchanged for a year. We are either going to need to fix this, or publicise a work around.

/cc @RedBrogdon @kevmoo

**Comment by kevmoo** [comment] 2022-03-18 17:31
CC @mit-mit – related to `.packages` changes?

**Comment by christopherfujino** [comment] 2022-03-21 17:22
@Jasguerrero can you take a look at this? This release does have your change, however, I'm still not exactly sure how we are reaching this.

Also note that this CI build is using https://github.com/subosito/flutter-action, which may be doing something funny with the pub-cache.

**Comment by christopherfujino** [comment] 2022-03-21 21:23
I suspect this is a regression caused by https://github.com/flutter/flutter/pull/97722

**Comment by bichoalexis** [comment] 2022-03-22 05:02
Hey there, Im not sure If you already discovered (because me English is not the best) but for anyone who directly download de arm64 flutter beta zip from flutter.dev, they gonna have the same issue, the current solution is clone the repository and then when you create your app, its gonna auto download the required tools. 🤓

**Comment by christopherfujino** [comment] 2022-05-26 04:34
This was fixed by https://github.com/flutter/flutter/commit/50f3e47b67f5307657d71c9bcac9fed3129398b7

**Closed by christopherfujino** 2022-05-26 04:34 UTC
Labels: tool, dependency: dart, found in release: 2.12
