### ISSUE TITLE
Flutter crash during installation

### ISSUE THREAD

**Issue by vinayakvk** [flutter/flutter#18911] opened 2018-06-28 12:11 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: The system cannot find the file specified.

  Command: C:\Users\vinayak.bedage\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses

```
#0      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:193)
<asynchronous suspension>
#1      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:152)
<asynchronous suspension>
#2      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#3      Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#4      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1501)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#22     new Future.sync (dart:async/future.dart:222)
#23     CommandRunner.run (package:args/command_runner.dart:109)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1126)
#28     _CustomZone.run (dart:async/zone.dart:1023)
#29     runZoned (dart:async/zone.dart:1501)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50)
#33     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#34     main (file:///D:/Softwares/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: ProcessException: The system cannot find the file specified.

  Command: C:\Users\vinayak.bedage\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses

#0      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:193)
<asynchronous suspension>
#1      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:152)
<asynchronous suspension>
#2      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#3      Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#4      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:194)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1126)
#7      _CustomZone.run (dart:async/zone.dart:1023)
#8      runZoned (dart:async/zone.dart:1501)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#10     _doctorText (package:flutter_tools/runner.dart:193)
<asynchronous suspension>
#11     _createLocalCrashReport (package:flutter_tools/runner.dart:171)
<asynchronous suspension>
#12     _handleToolError (package:flutter_tools/runner.dart:126)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#20     run (package:flutter_tools/runner.dart:50)
#21     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#22     main (file:///D:/Softwares/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by zoechi** [comment] 2018-06-28 15:14
How did you install the Android SDK?
Did you install it with Android Studio?

**Comment by vinayakvk** [comment] 2018-06-29 06:37
Hey Zoechi,
No,I have downloaded the flutter sdk from github abd  then started using in android studio

**Comment by zoechi** [comment] 2018-06-29 12:57
What about the Android SDK?
Does the file `Command: C:\Users\vinayak.bedage\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT` exist?

**Comment by vinayakvk** [comment] 2018-06-29 13:10
Yes it exists

**Comment by zoechi** [comment] 2018-06-29 13:17
Looks similar to #16214

**Comment by zoechi** [comment] 2018-06-29 13:21
I'm going to close this issue because it looks like a duplicate of #16214.
I'd suggest to upvote #16214 using 
![image](https://user-images.githubusercontent.com/405837/42094401-fd7099d8-7baf-11e8-8efd-45ee98201e5a.png)

**Closed by zoechi** 2018-06-29 13:21 UTC
