### ISSUE TITLE
Trivial app on MacOS produces Shader compilation error

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#64827] opened 2020-08-28 21:25 UTC
The following app fails with the current build using ` flutter run --device-id 'MacOS'`. It does not fail when run on a Pixel2.

```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Material(color: Colors.blue),
    );
  }
}

void main() {
  runApp(MaterialApp(home: Home()));
}
```

```
Shader compilation error
------------------------
   1	#version 110
   2	
   3	const float kIndexBit = exp2(13.0);
   4	const float kInvIndexBit = exp2(-13.0);
   5	uniform vec4 sk_RTAdjust;
   6	uniform vec2 uAtlasSizeInv_Stage0;
   7	attribute vec2 inPosition;
   8	attribute vec4 inColor;
   9	attribute vec2 inTextureCoords;
  10	varying vec2 vTextureCoords_Stage0;
  11	varying float vTexIndex_Stage0;
  12	varying vec4 vinColor_Stage0;
  13	void main() {
  14	    vec2 coord = vec2(inTextureCoords.x, inTextureCoords.y);
  15	    vec2 unitTexCoords = kInvIndexBit * coord;
  16	    vec2 highBits = floor(unitTexCoords);
  17	    vec2 unormTexCoords = coord - kIndexBit * highBits;
  18	    vTextureCoords_Stage0 = unormTexCoords * uAtlasSizeInv_Stage0;
  19	    vTexIndex_Stage0 = 0.0;
  20	    vinColor_Stage0 = inColor;
  21	    gl_Position = vec4(inPosition.x, inPosition.y, 0.0, 1.0);
  22	    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
  23	}
  24	
Errors:
ERROR: 0:3: Initializer not allowed
ERROR: 0:4: Initializer not allowed
ERROR: 0:15: Use of undeclared identifier 'kInvIndexBit'
ERROR: 0:16: Use of undeclared identifier 'unitTexCoords'
ERROR: 0:17: Use of undeclared identifier 'kIndexBit'
ERROR: 0:17: Use of undeclared identifier 'highBits'
ERROR: 0:18: Use of undeclared identifier 'unormTexCoords'
```

**Comment by DJafari** [comment] 2020-08-28 22:30
@HansMuller have a workaround for this ? or i must downgrade ?

**Comment by HansMuller** [comment] 2020-08-28 23:26
Not at the moment no. You're running into it as well I assume?

**Comment by DJafari** [comment] 2020-08-28 23:50
yeah, i had to downgrade

```
flutter version 1.22.0-1.0.pre
```

**Comment by dnfield** [comment] 2020-08-28 23:56
This is fixed at head - there's another duplicate of this here: #64831

**Closed by dnfield** 2020-08-28 23:56 UTC
Labels: engine, severe: rendering
