### ISSUE TITLE
Installing release apk – which version should flutter install?

### ISSUE THREAD

**Issue by asavchuk** [flutter/flutter#48199] opened 2020-01-05 07:34 UTC
After I build release apk there are three different apk in project `release` folder (app-arm64-v8a-release.apk, app-armeabi-v7a-release.apk, app-x86_64-release.apk). In addition, there is an apk file named `app.apk` in `apk` folder (above the `release` folder level). 

When I run
> flutter install

the output is

> Installing app.apk to [android device]... 

> Uninstalling old version...

> Installing build\app\outputs\apk\app.apk...                                  2,0s

And, as you can see now, flutter installs the `app.apk` which is the same size as `app-armeabi-v7a-release.apk`, so I suppose those files are the same file. But the target android device supports `arm64-v8a` instructions, so why in this case flutter installs apk based an `armeabi-v7a` instructions set?

**Comment by dnfield** [comment] 2020-01-06 04:19
This is a question for StackOverflow or one of the communities at https://flutter.dev/community - it is not a bug or feature request for Flutter, so I'm closing it.

A start at the answer - Android devices can support armv7 even if they're arm64. Generally speaking, you should just ship up AABs to the store since it will take care of the bundling/platform weirdness for you.

**Closed by dnfield** 2020-01-06 04:19 UTC
