### ISSUE TITLE
[Flutter Web, Navigation 2.0, pushNamed] Navigator 2.0's main focus was for Flutter web to change URL in browser and History stack management. I have found that this is possible with Navigator 1.0 as well.

### ISSUE THREAD

**Issue by AbhishekDoshi26** [flutter/flutter#84491] opened 2021-06-12 13:16 UTC
Navigator 2.0's main focus was for Flutter web to change URL in browser and History stack management. I have found that this is possible with Navigator 1.0 as well. I have used named routes in Flutter Web `Navigator.pushNamed(context, '/second');` to move to next screen. To my surprise, navigating in Flutter web using this did change the URL and also added it to the browser history. I thought this might be due to local host. Hence, I used the same in one of my client project and deployed it using Google Cloud. The same behavior was observed. Not just this, if we moved to the link of 2nd page directly (somewebsite.com/second) this also worked without any flaw.

### Hence, we can change URL and have history stack without using Navigator 2.0 by using `pushNamed`!!

I don't know if this is the expected result or is issue with pushNamed. If so, I feel there was not much need of 2.0 as the other thing introduced were canPop and Router widget. Also, it's not even buggy as I have tried with multi pages and dynamic links as well (Eg: moving to next screen based on some product id).

## Steps to Reproduce

1. Simply create a flutter app with named routes. I took the official example (https://flutter.dev/docs/cookbook/navigation/named-routes)
2. Run it on your chrome/edge.
3. Move to 2nd screen and move back (Notice the URL change)
4. Check the history of your browser and you will see the history reflects all transitions. (would just show localhost, but if deployed, it shows complete path)

**Expected results:** pushNamed shouldn't change the URL and history stack.

**Actual results:** pushNamed works completely flawless and hence defy the need for Navigator 2.0

## Reproducible Code
(Can use official example: https://flutter.dev/docs/cookbook/navigation/named-routes)

#### `main.dart`
```
import 'package:flutter/material.dart';
import 'package:route_example/screen.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Named Routes Demo',
      initialRoute: '/',
      routes: {
        '/': (context) => FirstScreen(),
        '/second': (context) => SecondScreen(),
      },
    );
  }
}
```

#### `screen.dart`

```
import 'package:flutter/material.dart';

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pushNamed(context, '/second');
          },
          child: Text('Launch screen'),
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

<details>
  <summary>Logs</summary>

#### `flutter run --verbose`
```
[ +118 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +530 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[   +1 ms] executing: [C:\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +50 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] 2.2.1
[   +6 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +160 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +102 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] executing: C:\Users\Bacancy Technology\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +45 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +81 ms] Multiple devices found:
[  +22 ms] Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.41
[   +2 ms] [1]: Chrome (chrome)
[   +1 ms] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+5085 ms] 1
[  +41 ms] Skipping pub get: version match.
[ +244 ms] Generating D:\Flutter Projects\route_example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java        
[ +115 ms] Launching lib\main.dart on Chrome in debug mode...
[ +232 ms] Updating assets
[  +83 ms] Waiting for connection from debug service on Chrome...
[ +117 ms] <- reset
[   +6 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill    
C:\Users\BACANC~1\AppData\Local\Temp\flutter_tools.725974fa\flutter_tool.37fcd2c6\app.dill --libraries-spec
file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\Flutter Projects\route_example\.dart_tool\package_config.json    
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\BACANC~1\AppData\Local\Temp\flutter_tools.725974fa\flutter_tools.6bdd7307 --filesystem-scheme org-dartlang-app
--initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+21330 ms] Waiting for connection from debug service on Chrome... (completed in 21.4s)
[ +176 ms] Synced 28.2MB.
[  +11 ms] <- accept
[   +4 ms] Caching compiled dill
[ +428 ms] [CHROME]:
[  +18 ms] [CHROME]:DevTools listening on ws://127.0.0.1:57484/devtools/browser/bb05959c-8f34-4cc7-9cdf-a8198105ff5a
[ +500 ms] DwdsInjector: Received request for entrypoint at http://localhost:53080/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +20 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +11 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:53080/main_module.bootstrap.js
[+2182 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +87 ms] DevHandler: Debug service listening on ws://127.0.0.1:63910/hnqiWz9h7s8=/ws

[  +29 ms] This app is linked to the debug service: ws://127.0.0.1:63910/hnqiWz9h7s8=/ws
[  +12 ms] Debug service listening on ws://127.0.0.1:63910/hnqiWz9h7s8=/ws
[        ]  Running with sound null safety
[   +2 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+9866 ms] DevHandler: Stopped debug service on ws://127.0.0.1:63908

[+10181 ms] Application finished.
[  +13 ms] "flutter run" took 51,121ms.

```

#### `flutter analyze`
```
Analyzing route_example...
No issues found! (ran in 2.9s)
```

#### `flutter doctor -v`

```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1       

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)     
    • Android SDK at C:\Users\Bacancy Technology\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    

[√] VS Code (version 1.57.0)
    • VS Code at C:\Users\Bacancy Technology\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-14 13:32
Hi @AbhishekDoshi26 
While this works, there are many more reasons for Navigator 2.0 to exist.  The code looks fairly simple so I am not sure this is unexpected.  I recommend discussing this on  Discord and get the feedback you need as this is not a bug.,

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-14 13:32 UTC
Labels: in triage
