### ISSUE TITLE
PathProvider in ios simulator isolate does not work even registerWith()

### ISSUE THREAD

**Issue by whquddn55** [flutter/flutter#100436] opened 2022-03-20 05:42 UTC
When run PathProvider's any method on isolate, Exception(MissingPluginException) occur. 
Even I ran `PathProviderIOS.registerWith();`!

![image](https://user-images.githubusercontent.com/26822105/159149642-91265cc4-17a5-4a02-a1b4-08625f999ff9.png)

Considering that it does not occur when the method of Pathprovider is called at the UI level, it is not a problem with the Simulator. It always happens only in Isolates I create.

I already run `flutter clean` `flutter pub get` 'reinstall flutter sdk', 'reinstall app on simulator' 

Any solutions?

part of my code
``` 
static Future<void> initialize() async {
    PathProviderIOS.registerWith();
    final String path = (await getApplicationDocumentsDirectory()).path + '/db';
    try {
      store = await openStore();
    } catch (e) {
      store = Store.attach(getObjectBoxModel(), path);
    }
```

logs
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_ios)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:175
<asynchronous suspension>
#1      getApplicationDocumentsDirectory
package:path_provider/path_provider.dart:115
<asynchronous suspension>
#2      StorageController.initialize
package:pnu_plato_advanced_browser/controllers/storage_controller.dart:19
<asynchronous suspension>
#3      _onStart
package:pnu_plato_advanced_browser/services/background_service.dart:98
<asynchronous suspension>
```

**Comment by ryzizub** [comment] 2022-03-20 11:41
What version of `path_provider` package you using?

**Comment by whquddn55** [comment] 2022-03-20 14:58
> What version of `path_provider` package you using?

The version is 2.0.8 !

**Comment by maheshmnj** [comment] 2022-03-21 08:55
Hi @whquddn55, Thanks for filing the issue. Please see this https://github.com/flutter/flutter/issues/99155#issuecomment-1060956399 comment to resolve the issue.

Closing the issue as duplicate of https://github.com/flutter/flutter/issues/99155

**Closed by maheshmnj** 2022-03-21 08:55 UTC
Labels: in triage

**Comment by whquddn55** [comment] 2022-03-22 03:58
> The Dart registration has already worked in the error you listed; it's using the correct method channel.
> 
> What you are missing is the registration of the native code for your isolate; Flutter only registers plugins for the main isolate. This has always been true, and is unrelated to Dart registration.
> 
> If you want to use plugins on an isolate you need to manually register them with an engine that is running that isolate, or use one of the community plugins that manages that for you, as has always been the case.

Solved! Thx!!
