### ISSUE TITLE
pub get failed chat depends on charts, flutter >=0.01+1<0.4.0 which requires SDK version >=1.23.0 <2.0.0 exit code 1 

### ISSUE THREAD

**Issue by wassim6975** [flutter/flutter#48020] opened 2019-12-31 14:58 UTC
Hello everyone and happy new year,

I am a beginner with flutter and dart an i have an issue on flutter when i want to use charts_flutter.

I tried flutter clear, to check the others topics with this kind of issues and change the sdk environnement but it didn't work...

Thank you in advance for your help

**I'm using macOS Catalina 10.15.1** 

**This is the main.dart :**

```
import 'package:flutter/material.dart';
import 'package:charts_flutter/flutter.dart' as charts;
void main() => runApp(new MyApp());
class MyApp extends StatelessWidget {
@override
Widget build(BuildContext context) {
return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
MyHomePage({Key key, this.title}) : super(key: key);
final String title;
@override
_MyHomePageState createState() => new _MyHomePageState();
}
class ClicksPerYear {
final String year;
final int clicks;
final charts.Color color;
ClicksPerYear(this.year, this.clicks, Color color)
: this.color = new charts.Color(
            r: color.red, g: color.green, b: color.blue, a: color.alpha);
}
class _MyHomePageState extends State<MyHomePage> {
int _counter = 0;
void _incrementCounter() {
setState(() {
      _counter++;
    });
  }
@override
Widget build(BuildContext context) {
var data = [
new ClicksPerYear('2016', 12, Colors.red),
new ClicksPerYear('2017', 42, Colors.yellow),
new ClicksPerYear('2018', _counter, Colors.green),
    ];
var series = [
new charts.Series(
        domainFn: (ClicksPerYear clickData, _) => clickData.year,
        measureFn: (ClicksPerYear clickData, _) => clickData.clicks,
        colorFn: (ClicksPerYear clickData, _) => clickData.color,
        id: 'Clicks',
        data: data,
      ),
    ];
var chart = new charts.BarChart<ClicksPerYear>(
      series,
      animate: true,
    );
var chartWidget = new Padding(
      padding: new EdgeInsets.all(32.0),
      child: new SizedBox(
        height: 200.0,
        child: chart,
      ),
    );
return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
new Text(
'You have pushed the button this many times:',
            ),
new Text(
'$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
            chartWidget,
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}
```
**This is the pubspec.yaml**

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```

And this is the error messages :

Running "flutter pub get" in chat...
The current Dart SDK version is 2.8.0-dev.0.0.flutter-aa6709974d.

Because chat depends on charts_flutter >=0.0.1+1 <0.4.0 which requires SDK version >=1.23.0 <2.0.0, version solving failed. pub get failed (1; Because chat depends on charts_flutter >=0.0.1+1 <0.4.0 which requires SDK version >=1.23.0 <2.0.0, version solving failed.) exit code 1

**flutter analyze**
The current Dart SDK version is 2.8.0-dev.0.0.flutter-aa6709974d.       
                                                                        
Because chat depends on charts_flutter >=0.0.1+1 <0.4.0 which requires SDK version >=1.23.0 <2.0.0, version solving failed.
Running "flutter pub get" in chat...                                    
pub get failed (1; Because chat depends on charts_flutter >=0.0.1+1 <0.4.0 which
requires SDK version >=1.23.0 <2.0.0, version solving failed.)

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.13.5, on Mac OS X 10.15.1 19B88, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by jonahwilliams** [comment] 2019-12-31 21:07
The last version of charts flutter is 0.8.1, released in September. See https://pub.dev/packages/charts_flutter/versions

The version you are trying to depend on was released in April of 2018, and the error message is attempting to communicate that this requires an older version of dart/flutter - this is not a bug.

I recommend updating to a newer version of charts_flutter

**Closed by jonahwilliams** 2019-12-31 21:07 UTC

**Comment by wassim6975** [comment] 2020-01-02 09:54
Thanks it helped me
