### ISSUE TITLE
Did my flutter upgrade fail?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9561] opened 2017-04-24 17:52 UTC
I just tried to run `flutter upgrade` and I got this message:

```
sethladd-macbookpro:flutter_gallery sethladd$ flutter upgrade && flutter run --release
fatal: no upstream configured for branch 'package-assets'
Unable to upgrade Flutter: no upstream repository configured.
sethladd-macbookpro:flutter_gallery sethladd$
```

As a user, I'm left wondering:

* What state am I in?
* Did it fail?

Suggestion:

Assuming that the whole upgrade did indeed fail, let's print out how to mitigate this particular error (I'm actually not sure what to do here?) and at least print out "Upgrade failed".

Thanks!

**Comment by eseidelGoogle** [comment] 2017-04-24 17:53
You're also in a funny setup, whereby you've switched your git branch to one which does not have an `upstream` branch configured. :)  Normal flutter users won't have switched their git branch on their flutter checkout.

**Comment by eseidelGoogle** [comment] 2017-04-24 17:54
You can restore peace and justice using `git checkout -b master upstream/master`.

**Comment by sethladd** [comment] 2017-04-24 17:55
Thanks!

Would still love for the tool to print out an acknowledge if the command itself failed.

**Comment by maryx** [comment] 2018-03-18 21:03
```
flutter git:(c59966290) $ flutter upgrade
Downloading Dart SDK from Flutter engine 520529dbba9b3048f5cc0e0268a274911f3887e6...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.3M  100 44.3M    0     0  15.9M      0  0:00:02  0:00:02 --:--:-- 15.9M
Building flutter tool...
Unable to upgrade Flutter: no upstream repository configured.
```

I just encountered this same message, as I had pulled down an older commit on master to test it (not master). Would be great to have more text in the tool to notify users about the state :)

**Comment by zoechi** [comment] 2019-01-16 11:04
Duplicate of #14120

**Comment by zoechi** [comment] 2019-01-16 11:04
Similar #25220

**Closed by zoechi** 2019-01-16 11:04 UTC
Labels: tool
