### ISSUE TITLE
App crashes when writing "^" and then pressing backspace

### ISSUE THREAD

**Issue by PascalGehring** [flutter/flutter#71659] opened 2020-12-03 14:41 UTC
# Flutter apps crash when typing "^" and then backspace on a hardware keyboard

Every  Flutter App crashes when you are in a text field and type "^" and then backspace. First I thought it is an issue only affecting my App. But I tried it on several other Apps including Reflectly and it appeared in every other App as well.

## Code Snippet

```JavaScript
TextField(
  obscureText: true,
  decoration: InputDecoration(
    border: OutlineInputBorder(),
    labelText: 'Password',
  ),
)
```

## Flutter Doctor

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.78, on Mac OS X 10.15.6 19G2021
    darwin-x64, locale de)
    • Flutter version 1.25.0-5.0.pre.78 at
      /Users/pascalgehring/documents/flutter
    • Framework revision f78b6d6a51 (vor 5 Tagen), 2020-12-04 14:38:13 -0800
    • Engine revision 59b4baea51
    • Dart version 2.12.0 (build 2.12.0-113.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/pascalgehring/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/contents/developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 86F2A5BD-1CC6-4036-8B76-7154BE0246AB • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 87.0.4280.88

• No issues found!


```

Thanks for your Answers

**Comment by TahaTesser** [comment] 2020-12-03 15:45
Hi @PascalGehring 
Just tried on the `stable` and `master`, there is no issue when typing "^" and then backspace
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by PascalGehring** [comment] 2020-12-04 16:26
Hi @TahaTesser 
I should have mentioned that this only happens, when pressing "^" and then backspace on a hardware keyboard. A specific code sample should not be necessary, because it happens with every single textfield widget in flutter. But I will nevertheless provide a code sample.
Thank you for your response

**Comment by TahaTesser** [comment] 2020-12-07 07:27
Hi @PascalGehring 
Just tried to reproduce using a Bluetooth hardware keyboard on a physical XR/simulator, there is no issue.

### Preview
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/101320556-f8c0ec00-3889-11eb-922f-4e7188102515.gif)



<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(
          obscureText: true,
          decoration: InputDecoration(
            border: OutlineInputBorder(),
            labelText: 'Password',
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by PascalGehring** [comment] 2020-12-09 20:22
Hi @TahaTesser 
I realised, that it also occurs when typing "`" . I think it only occurs with French/Spanish/Swiss keyboards, because when you type "^" and then a character the character there will be a character with accent. I think it only crashes, when you use a keyboard with the accent feature. On the screenshot you see that the character is underlined, this means that you could press a character and it would get the accent.
For example:
^ + a => â

Thank you


**Screenshot:**
![Simulator Screen Shot - iPhone 12 Pro - 2020-12-09 at 20 53 59](https://user-images.githubusercontent.com/41545796/101681765-f5cd2380-3a62-11eb-9b33-b03908032e00.png)
**flutter run --verbose:**
```
[   +1 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 12 Pro is available at: http://127.0.0.1:55840/zcDJOWsdfsfzKLo=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+171057 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device
(file:///Users/x/Library/Developer/CoreSimulator/Devices/86F2A5BD-1CC6-4036-8B76-7154BE0246AB/data/Containers/Data/Application/265F3BC5-55DD-4E0D-86ED-0E13D4483CD7/tmp/timetable2UKeen/timetable/)
[ +254 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 199.821ms.
[  +60 ms] ensureAnalyticsSent: 58ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 0
```

**Comment by TahaTesser** [comment] 2020-12-10 08:13
Hi @PascalGehring 
Tried all ways to reproduce this issue using Egnlish, Spanish/French keywords, tried ` â` and similar characters and `^` on iOS and Android, no issues at all on the latest `stable` and latest master`
Also, your logs don't indicate the crash, Do you get `TimeoutException after 0:00:00.250000: Future not completed` when you type?  Can you please try a different device or simulator? if possible please create a screen recording of the issue

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>multiple flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios           • iOS 14.2
    • iPhone 12 (mobile)   • 2188C52E-1D22-45B2-98B8-48401D2B6716 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.141, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-5.0.pre.141 at /Users/tahatesser/Code/flutter_master
    • Framework revision 36bed2b4c3 (7 hours ago), 2020-12-09 20:13:04 -0500
    • Engine revision 8518a5bbe6
    • Dart version 2.12.0 (build 2.12.0-135.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.2
    • iPhone 12 (mobile)   • 2188C52E-1D22-45B2-98B8-48401D2B6716 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

Thank you

**Comment by PascalGehring** [comment] 2020-12-22 18:36
Hi @TahaTesser
It only happens on iOS devices, on android devices the key press just doesn't get recognised. I tried it on different iOS Simulators and it appeared on everyone. I don't get a `TimeoutException after 0:00:00.250000: Future not completed`
I have attached a screenrecording from an iPad. 
I could be related to the Swiss Keyboard layout...

It's weird that the app just crashes without any error message...

> [+7977 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +4 ms] DevFS: Deleting filesystem on the device
(file:///Users/pascalgehring/Library/Developer/CoreSimulator/Devices/F1DE1179-6CA6-4062-A633-53F4902E56A6/data/Containers/Data/Application/3713EFC1-45F3-4838-9FE8-724B205C35F0/tmp/lasttryR0lglh/lasttry/)
[ +256 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +1 ms] "flutter run" took 34.907ms.
[  +61 ms] ensureAnalyticsSent: 56ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +11 ms] Shutdown hooks complete
[        ] exiting with code 0 


Thank you

https://user-images.githubusercontent.com/41545796/102921311-7725ac80-448c-11eb-89c0-5001f98bf471.mp4

**Comment by TahaTesser** [comment] 2020-12-23 07:40
Hi @PascalGehring 
It's hard to bug an app from the store, can you please reproducible sample and logs from Flutter itself and not from a store.
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by PascalGehring** [comment] 2020-12-23 17:24
Hi @TahaTesser 

Here is my `flutter run --verbose` output:

> [  +51 ms] ensureAnalyticsSent: 47ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[        ] exiting with code 

I have attached both Video of crash from simulator and system crash report (as zip file)

Thank you

https://user-images.githubusercontent.com/41545796/103022286-f928da80-454b-11eb-95c7-72f390016109.mov




[Runner_2020-12-23-181833_Pascals-iMac.crash.zip](https://github.com/flutter/flutter/files/5736379/Runner_2020-12-23-181833_Pascals-iMac.crash.zip)

**Comment by TahaTesser** [comment] 2020-12-28 09:12
I tried to reproduce it again with French/Swiss keyboard again, still, no crash using either "^" or "`" on iOS physical device or simulator or physical iPad.
Labelling it for now, since it reproduces for the author.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.137 at /Users/tahatesser/Code/flutter_master
    • Framework revision 8f5d0371af (2 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64  • Android 10 (API 29)
    • iPhone 12 (mobile) • 12D8FF8E-2815-436E-9951-B8A6A42E4ACF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

**Comment by canastro** [comment] 2021-03-03 17:09
Seems to be related with https://github.com/flutter/flutter/issues/26602

**Comment by PascalGehring** [comment] 2021-03-03 23:02
> Seems to be related with #26602

Yes. I think it‘s the Same issue.

**Comment by TahaTesser** [comment] 2021-03-04 12:15
@PascalGehring 
Let's close it as a duplicate ofhttps://github.com/flutter/flutter/issues/26602

**Closed by TahaTesser** 2021-03-04 12:15 UTC
Labels: a: internationalization, a: text input, f: material design, framework, passed first triage, severe: fatal crash
