### ISSUE TITLE
Web : when web mode enabled in existing project - giving error

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#63896] opened 2020-08-16 10:45 UTC
Hi,
I enabled web mode, then added flutter web by below command
flutter create .

After than running on chrome by Android Studio

Now its giving error like below
<details>
 <summary>Logs</summary>

```
[ +149 ms] executing: [E:\flutter-web/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +221 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] bbfbf1770cca2da7c82e887e4e4af910034800b6
[        ] executing: [E:\flutter-web/] git tag --contains HEAD
[ +349 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.2
[  +11 ms] executing: [E:\flutter-web/] git rev-parse --abbrev-ref --symbolic @{u}
[ +160 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [E:\flutter-web/] git ls-remote --get-url origin
[ +161 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +211 ms] executing: [E:\flutter-web/] git rev-parse --abbrev-ref HEAD
[ +164 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +84 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] executing: C:\Users\80065124\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +122 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +130 ms] Found plugin connectivity at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.9\
[   +6 ms] Found plugin connectivity_for_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity_for_web-0.3.1\
[   +2 ms] Found plugin connectivity_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+3\
[   +9 ms] Found plugin device_info at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\device_info-0.4.2+6\
[  +17 ms] Found plugin firebase_analytics at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[   +3 ms] Found plugin firebase_analytics_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[   +2 ms] Found plugin firebase_core at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +3 ms] Found plugin firebase_core_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +2 ms] Found plugin firebase_crashlytics at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_crashlytics-0.1.4+1\
[   +2 ms] Found plugin firebase_remote_config at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.3.1+1\
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +3 ms] Found plugin google_maps_flutter at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.30\
[  +14 ms] Found plugin open_file at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.1\
[   +6 ms] Found plugin path_provider at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +1 ms] Found plugin path_provider_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +1 ms] Found plugin path_provider_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[  +11 ms] Found plugin shared_preferences at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.8\
[   +1 ms] Found plugin shared_preferences_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+1\
[   +1 ms] Found plugin shared_preferences_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +2 ms] Found plugin shared_preferences_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +9 ms] Found plugin sqflite at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.1\
[  +13 ms] Found plugin url_launcher at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.0\
[   +1 ms] Found plugin url_launcher_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+1\
[   +1 ms] Found plugin url_launcher_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+7\
[   +2 ms] Found plugin url_launcher_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.2+1\
[   +8 ms] Found plugin webview_flutter at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\
[  +85 ms] Found plugin connectivity at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.9\
[   +1 ms] Found plugin connectivity_for_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity_for_web-0.3.1\
[   +1 ms] Found plugin connectivity_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+3\
[   +4 ms] Found plugin device_info at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\device_info-0.4.2+6\
[   +9 ms] Found plugin firebase_analytics at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[   +2 ms] Found plugin firebase_analytics_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[   +1 ms] Found plugin firebase_core at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +1 ms] Found plugin firebase_core_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +1 ms] Found plugin firebase_crashlytics at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_crashlytics-0.1.4+1\
[   +1 ms] Found plugin firebase_remote_config at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.3.1+1\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +2 ms] Found plugin google_maps_flutter at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.30\
[  +10 ms] Found plugin open_file at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.1\
[   +3 ms] Found plugin path_provider at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +1 ms] Found plugin path_provider_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +6 ms] Found plugin shared_preferences at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.8\
[        ] Found plugin shared_preferences_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+1\
[        ] Found plugin shared_preferences_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +1 ms] Found plugin shared_preferences_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +5 ms] Found plugin sqflite at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.1\
[   +6 ms] Found plugin url_launcher at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.0\
[        ] Found plugin url_launcher_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+1\
[        ] Found plugin url_launcher_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+7\
[   +1 ms] Found plugin url_launcher_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.2+1\
[   +5 ms] Found plugin webview_flutter at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\
[  +59 ms] Generating E:\office_projects\mobily_b2b_virat_new\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":1740}}]
[{"event":"app.start","params":{"appId":"a28821d2-ec1b-4a19-a0a4-fc55eec9c00a","deviceId":"chrome","directory":"E:\\office_projects\\mobily_b2b_virat_new","supportsRestart":true,"launchMode":"run"}}]
Launching lib\main.dart on Chrome in debug mode...
[ +228 ms] Updating assets
[ +248 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
Syncing files to device Chrome...
[{"event":"app.progress","params":{"appId":"a28821d2-ec1b-4a19-a0a4-fc55eec9c00a","id":"0","progressId":null,"message":"Syncing files to device Chrome..."}}]
[  +22 ms] Found plugin connectivity at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.9\
[   +1 ms] Found plugin connectivity_for_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity_for_web-0.3.1\
[   +1 ms] Found plugin connectivity_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+3\
[   +2 ms] Found plugin device_info at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\device_info-0.4.2+6\
[   +5 ms] Found plugin firebase_analytics at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[   +1 ms] Found plugin firebase_analytics_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[        ] Found plugin firebase_core at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[        ] Found plugin firebase_core_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[        ] Found plugin firebase_crashlytics at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_crashlytics-0.1.4+1\
[        ] Found plugin firebase_remote_config at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.3.1+1\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +1 ms] Found plugin google_maps_flutter at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.30\
[   +4 ms] Found plugin open_file at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.1\
[   +2 ms] Found plugin path_provider at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[        ] Found plugin path_provider_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[        ] Found plugin path_provider_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +4 ms] Found plugin shared_preferences at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.8\
[        ] Found plugin shared_preferences_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+1\
[        ] Found plugin shared_preferences_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +1 ms] Found plugin shared_preferences_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +2 ms] Found plugin sqflite at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.1\
[   +4 ms] Found plugin url_launcher at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.0\
[        ] Found plugin url_launcher_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+1\
[        ] Found plugin url_launcher_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+7\
[   +1 ms] Found plugin url_launcher_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.2+1\
[   +2 ms] Found plugin webview_flutter at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\
[  +13 ms] Found plugin connectivity at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.9\
[   +1 ms] Found plugin connectivity_for_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity_for_web-0.3.1\
[   +1 ms] Found plugin connectivity_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+3\
[   +2 ms] Found plugin device_info at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\device_info-0.4.2+6\
[   +3 ms] Found plugin firebase_analytics at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[        ] Found plugin firebase_analytics_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[        ] Found plugin firebase_core at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[        ] Found plugin firebase_core_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[        ] Found plugin firebase_crashlytics at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_crashlytics-0.1.4+1\
[   +1 ms] Found plugin firebase_remote_config at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.3.1+1\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +1 ms] Found plugin google_maps_flutter at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.30\
[   +4 ms] Found plugin open_file at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.1\
[   +1 ms] Found plugin path_provider at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[        ] Found plugin path_provider_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[        ] Found plugin path_provider_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +4 ms] Found plugin shared_preferences at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.8\
[   +1 ms] Found plugin shared_preferences_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+1\
[        ] Found plugin shared_preferences_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +1 ms] Found plugin shared_preferences_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +3 ms] Found plugin sqflite at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.1\
[   +3 ms] Found plugin url_launcher at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.0\
[        ] Found plugin url_launcher_linux at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+1\
[        ] Found plugin url_launcher_macos at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+7\
[        ] Found plugin url_launcher_web at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.2+1\
[   +2 ms] Found plugin webview_flutter at E:\flutter-web\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\
[   +8 ms] Generating E:\office_projects\mobily_b2b_virat_new\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +162 ms] <- reset
[   +6 ms] E:\flutter-web\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev E:\flutter-web\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root E:\flutter-web\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true -Dflutter.inspector.structuredErrors=true --output-dill C:\Users\80065124\AppData\Local\Temp\flutter_tools.6ab9eed9\flutter_tool.3607bae6\app.dill --libraries-spec file:///E:/flutter-web/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root C:\Users\80065124\AppData\Local\Temp\flutter_tools.6ab9eed9\flutter_tools.13ad141c --filesystem-scheme org-dartlang-app --initialize-from-dill build\f872507f30e2ff2523f0f1d19160266e.cache.dill.track.dill --platform file:///E:/flutter-web/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[ +134 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[{"event":"app.progress","params":{"appId":"a28821d2-ec1b-4a19-a0a4-fc55eec9c00a","id":"0","progressId":null,"finished":true}}]
[+14718 ms] Synced 39.7MB.
[        ] <- accept
[        ] Caching compiled dill
[ +387 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:59730/devtools/browser/4507be83-531c-4371-a1c7-7fbd13b505a0
ERROR - 2020-08-16 16:56:44.311173
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                      Object.noSuchMethod
package:dwds/src/handlers/injector.dart 51:41  DwdsInjector.middleware.<fn>.<fn>
```
</details>

**Comment by viratshukla** [comment] 2020-08-16 10:47
These are logs of flutter doctor


[√] Flutter (Channel beta, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
    • Flutter version 1.20.2 at C:\Users\80065124\Downloads\flutter
    • Framework revision bbfbf1770c (3 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\80065124\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\80065124\Downloads\android-studio-4.0.1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\80065124\Downloads\android-studio-4.0.1
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
Process finished with exit code 0

**Comment by sidrao2006** [comment] 2020-08-16 13:56
Please make sure followed the following steps

1. Run `flutter channel beta` (You can also use `dev` or `master` )
2. Run `flutter upgrade`
3. Run `flutter config --enable-web`

Then on running `flutter run -d Chrome` or `flutter build web` , it should download the Web Sdk.

**Comment by sidrao2006** [comment] 2020-08-16 13:58
Duplicate of #44459

**Comment by Abhishek01039** [comment] 2020-08-16 15:14
Duplication of https://github.com/flutter/flutter/issues/58110

**Comment by markusaksli-nc** [comment] 2020-08-17 15:06
Hi @viratshukla 
Could you please try `flutter update-packages` as per https://github.com/flutter/flutter/issues/58110#issuecomment-634940055?
Thank you

**Comment by TahaTesser** [comment] 2020-09-09 14:11
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-09-09 14:11 UTC
Labels: in triage
