### ISSUE TITLE
No signature of method: build_e1607ckisf3tv98uon6r164yj.android() 

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#79428] opened 2021-03-31 05:12 UTC
## Steps to Reproduce

1. create new project
2.  apply android product flavors
3.  run using terminal by this command  "flutter run -v"

## Logs

<details>
<summary>Logs</summary>

```
FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[        ] Build file '/media/hardik/work/soft/hardik/flutter_app3/android/app/build.gradle' line: 28
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':app'.
[        ] > No signature of method: build_e1607ckisf3tv98uon6r164yj.android() is applicable for argument types: (build_e1607ckisf3tv98uon6r164yj$_run_closure2) values:
[build_e1607ckisf3tv98uon6r164yj$_run_closure2@168eb882]

```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_IN)
    • Flutter version 2.0.2 at /media/hardik/Storage/extra/flutterSdk/flutter
    • Framework revision 8962f6dc68 (3 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/hardik/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2021-03-31 10:54
Hi @mehtahardikr 
You need to provide `--flavor` and target when adding flavor

```bash
tahatesser@Tahas-MacBook-Pro stable_flutter %  flutters run --flavor app1 -t lib/main.dart 
Multiple devices found:
sdk gphone x86 (mobile) • emulator-5554             • android-x86    • Android 11 (API 30) (emulator)
Taha’s iPhone (mobile)  • 00008020-001059882212002E • ios            • iOS 14.4.1
macOS (desktop)         • macos                     • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
Chrome (web)            • chrome                    • web-javascript • Google Chrome 89.0.4389.90
[1]: sdk gphone x86 (emulator-5554)
[2]: Taha’s iPhone (00008020-001059882212002E)
[3]: macOS (macos)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleApp1Debug'...                              
Running Gradle task 'assembleApp1Debug'... Done                     8.7s
✓ Built build/app/outputs/flutter-apk/app-app1-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              1,547ms
Activating Dart DevTools...                                         7.2s
Syncing files to device sdk gphone x86...                          162ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:59882/Y9NkY0jH7LE=/

Flutter DevTools, a Flutter debugger and profiler, on sdk gphone x86 is available at:
http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A59882%2FY9NkY0jH7LE%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety


```

<details> 

<summary>build.gradle</summary> 

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.stable_flutter"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

    flavorDimensions "app"
    productFlavors {

        app1 {
            dimension "app"
            applicationId "com.example.stable_flutter.app1"
            versionCode 1
            versionName "1.0"
        }

        app2 {
            dimension "app"
            applicationId "com.example.stable_flutter.app2"
            versionCode 1
            versionName "1.0"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

</details>

When not specifying `--flavor` and `--target`, build successful but the app fails to launch with a different error than yours
```bash
[        ] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 4s
[        ] 64 actionable tasks: 9 executed, 55 up-to-date
[ +397 ms] Running Gradle task 'assembleDebug'... (completed in 5.6s)
[   +5 ms] LocalFile: '/Users/tahatesser/AndroidStudioProjects/stable_flutter/android/build.gradle' provides AGP
version: 4.1.0
[   +5 ms] Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under
           /Users/tahatesser/AndroidStudioProjects/stable_flutter/build, but the tool couldn't find it.
[   +3 ms] "flutter run" took 14,221ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
```


Can you please provide your `build.gradle` and try again with `--flavor` and `target`?
Thank you

**Comment by mehtahardikr** [comment] 2021-04-01 04:12
@TahaTesser  : thanks for the answer.

here is my build.gradle file content.
````
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_app3"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

    flavorDimension "default"
    productFlavors {
        dev {

            versionCode 1
            versionName "1.0.0"

            resValue "string", 'app_name', '"Demo Dev"'

            applicationIdSuffix ".dev"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

````

i have tried using target also, but no luck. getting error as i reported. i just create new project and added falvors.

**Comment by TahaTesser** [comment] 2021-04-01 08:29
Hi @mehtahardikr 
The error is caused by a typo in your `build.gradle` 
`flavorDimensions "default"` instead you've `flavorDimension "default"`

When fixing the typo, I can run the app 
```bash
tahatesser@Tahas-MBP stable_flutter %  flutters run --flavor dev -t lib/main.dart
Using hardware rendering with device sdk gphone x86. If you notice graphics
artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDevDebug'...                               
Running Gradle task 'assembleDevDebug'... Done                     34.4s
✓ Built build/app/outputs/flutter-apk/app-dev-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4.4s
Activating Dart DevTools...                                      2,913ms
Syncing files to device sdk gphone x86...                          334ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on sdk gphone x86 is available at:
http://127.0.0.1:56696/Ms9mgvpODy0=/

Flutter DevTools, a Flutter debugger and profiler, on sdk gphone x86 is
available at:
http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A56696%2FMs9mgvpODy0%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
```

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-01 08:29 UTC
Labels: in triage
