### ISSUE TITLE
Flutter Web: TextFormField shows a different behavior on Microsoft Edge.

### ISSUE THREAD

**Issue by al4nnw** [flutter/flutter#88401] opened 2021-08-18 02:26 UTC
_This is my first time opening an issue on github. If there is something I need to edit, tell me._

I was building a Flutter Web Application with a login form. In this form there is a TextFormField for the password value. In this field, I've implemented a simple show/hide password mechanism, but when I open it on Microsoft Edge(debug), there is another iconButton that was never coded. 

From what I've tested, it only appears if `obscureText == true`, if the field is on focus and if the field has any value.

Post I made on StackOverflow:
[https://stackoverflow.com/questions/68812458/flutter-web-textformfield-shows-another-suffixicon-on-microsoft-edge?noredirect=1#comment121612575_68812458](url)

## Steps to Reproduce

1. Create a Flutter project
2. Use this sample app:

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

InputDecoration loginFormFieldDecoration = InputDecoration(
  constraints: const BoxConstraints(maxWidth: 400, maxHeight: 70),
  border: OutlineInputBorder(
      borderSide: BorderSide(color: Colors.grey[300]!, width: 1.0), borderRadius: BorderRadius.circular(12)),
  focusedBorder: OutlineInputBorder(
      borderSide: BorderSide(color: Colors.grey[300]!, width: 1.0), borderRadius: BorderRadius.circular(12)),
);

void main() {
  runApp(const MaterialApp(
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool isObscured = true;

  final _password = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: TextFormField(
        controller: _password,
        keyboardType: TextInputType.visiblePassword,
        obscureText: isObscured,
        decoration: loginFormFieldDecoration.copyWith(
            prefixIcon: const Icon(
              Icons.lock,
              color: Colors.grey,
            ),
            suffixIcon: IconButton(
                splashRadius: 0.1,
                onPressed: () {
                  setState(() {
                    isObscured = !isObscured;
                  });
                },
                icon: Icon(
                  isObscured ? Icons.visibility_off : Icons.visibility,
                  color: isObscured ? Colors.grey : Colors.blueAccent,
                )),
            hintText: "Type your password"),
      )),
    );
  }
}
``` 

</details>

3. Run it on Chrome(web):
    It will run just fine, as it would on Android emulator.

4. Run it on Microsoft Edge:
    You will notice that when you type something on the TextFormField, an unwanted interactable visibility icon will appear.

**Expected results:** 
![test_on_chrome](https://user-images.githubusercontent.com/65188332/129825737-cead7aa4-54b8-4ae8-b8e1-ae176c248447.gif)

**Actual results:** 
![test_on_edge](https://user-images.githubusercontent.com/65188332/129825748-7dfa085d-5c0b-49fa-9130-e716b8d2c2c1.gif)

<details>
  <summary>Logs</summary>

```
flutter run --verbose
[  +71 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +520 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5cda761161de53f0a7b1d4b039b5fbb41366d3c7
[   +1 ms] executing: [C:\flutter/] git tag --points-at 5cda761161de53f0a7b1d4b039b5fbb41366d3c7
[  +82 ms] Exit code 0 from: git tag --points-at 5cda761161de53f0a7b1d4b039b5fbb41366d3c7
[   +1 ms] executing: [C:\flutter/] git describe --match *.*.* --long --tags 5cda761161de53f0a7b1d4b039b5fbb41366d3c7
[ +111 ms] Exit code 0 from: git describe --match *.*.* --long --tags 5cda761161de53f0a7b1d4b039b5fbb41366d3c7
[   +1 ms] 2.4.0-0.0.pre-82-g5cda761161
[   +7 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +44 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +133 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +79 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +73 ms] executing: C:\Users\Alan\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +53 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +83 ms] Multiple devices found:
[  +29 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.1165]
[   +2 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.159
[   +1 ms] Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.73
[   +3 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +3 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 
[+10830 ms] 3
[  +32 ms] Skipping pub get: version match.
[ +132 ms] Generating C:\Users\Alan\Desktop\teste issue\teste_issue\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +107 ms] Launching lib\main.dart on Edge in debug mode...
[ +133 ms] Updating assets
[  +86 ms] Waiting for connection from debug service on Edge...
[ +106 ms] <- reset
[  +12 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill     
C:\Users\Alan\AppData\Local\Temp\flutter_tools.9fa073d6\flutter_tool.8c7c515c\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages    
C:\Users\Alan\Desktop\teste issue\teste_issue\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root C:\Users\Alan\AppData\Local\Temp\flutter_tools.9fa073d6\flutter_tools.f8d6df71 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety        
[  +14 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+16851 ms] Waiting for connection from debug service on Edge... (completed in 17,0s)
[   +1 ms] Synced 26.0MB.
[        ] <- accept
[        ] Caching compiled dill
[ +952 ms] [CHROME]:[32628:21896:0817/231604.312:ERROR:storage_reserve.cc(164)] Failed to open file to mark as storage reserve:
C:\Users\Alan\AppData\Local\Temp\flutter_tools.9fa073d6\flutter_tools_chrome_device.ec688a65\Default\Code Cache\js
[  +22 ms] [CHROME]:
[  +21 ms] [CHROME]:DevTools listening on ws://127.0.0.1:60002/devtools/browser/0c026c1f-dfcb-429f-ab62-e1f62c0a36bb
[ +911 ms] DwdsInjector: Received request for entrypoint at http://localhost:58105/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +12 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +7 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:58105/main_module.bootstrap.js
[+1893 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +69 ms] DevHandler: Debug service listening on ws://127.0.0.1:51694/H0TDqapgm_o=/ws

[  +24 ms] This app is linked to the debug service: ws://127.0.0.1:51694/H0TDqapgm_o=/ws
[  +11 ms] Debug service listening on ws://127.0.0.1:51694/H0TDqapgm_o=/ws
[        ]  Running with sound null safety
[   +3 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Edge is available at: http://127.0.0.1:51694/H0TDqapgm_o=
[ +696 ms] Activating Dart DevTools...
[+8259 ms] Activating Dart DevTools... (completed in 8,3s)
[ +507 ms] The Flutter DevTools debugger and profiler on Edge is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:51694/H0TDqapgm_o=
```

```
flutter analyze
Analyzing teste_issue...                                                
No issues found! (ran in 1.7s)
```

```
[√] Flutter (Channel master, 2.4.0-1.0.pre.82, on Microsoft Windows [versÃ£o 10.0.19042.1165], locale pt-BR)
    • Flutter version 2.4.0-1.0.pre.82 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5cda761161 (6 weeks ago), 2021-07-05 21:46:01 -0400
    • Engine revision 60ff03819c
    • Dart version 2.14.0 (build 2.14.0-280.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Alan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.2.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\Alan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.1165]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.73
```

</details>

**Comment by TahaTesser** [comment] 2021-08-18 10:38
Hi @al4nnw 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/83695
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-18 10:38 UTC
Labels: in triage
