### ISSUE TITLE
CupertinoTextField clear button doesn't work on android

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#28148] opened 2019-02-19 15:48 UTC
https://t.me/mobile_jobs_talk/279466
Code : 
```dart
         CupertinoTextField(
          controller: textController,
          placeholder: "Search",
          style: const TextStyle(
            fontSize: 16.0,
            fontFamily: "SanFrancisco",
          ),
          prefix: const Padding(padding: EdgeInsets.only(left: 8.0) , child: Icon(CupertinoIcons.search)),
          decoration: const BoxDecoration(border: null),
          clearButtonMode: OverlayVisibilityMode.editing,
```
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.2 18C54, locale ru-RU)
    • Flutter version 1.2.1-pre.142 at /Users/daniel/crossplatform/flutter
    • Framework revision fec01201b1 (10 days ago), 2019-02-09 11:23:28 -0500
    • Engine revision 067045757f
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 174d6fec3d)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment] 2019-02-19 15:51
Can you please make a complete (incl `main() {}`) runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by Renesanse** [comment] 2019-02-19 16:10
class SearchWidget extends StatelessWidget {

  final textController = TextEditingController();

  build(context) {
    return Padding(
      padding: const EdgeInsets.only(right: 16.0, top: 4.0),
      child: Container(
        decoration: BoxDecoration(
          color: CupertinoColors.inactiveGray,
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: CupertinoTextField(
          controller: textController,
          placeholder: "Search",
          style: const TextStyle(
            fontSize: 16.0,
            fontFamily: "SanFrancisco",
          ),
          prefix: const Padding(padding: EdgeInsets.only(left: 8.0) , child: Icon(CupertinoIcons.search)),
          decoration: const BoxDecoration(border: null),
          clearButtonMode: OverlayVisibilityMode.editing,
        ),
      )
    );
  }
}

**Comment by Renesanse** [comment] 2019-02-19 16:11
```class SearchWidget extends StatelessWidget {

  final textController = TextEditingController();

  build(context) {
    return Padding(
      padding: const EdgeInsets.only(right: 16.0, top: 4.0),
      child: Container(
        decoration: BoxDecoration(
          color: CupertinoColors.inactiveGray,
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: CupertinoTextField(
          controller: textController,
          placeholder: "Search",
          style: const TextStyle(
            fontSize: 16.0,
            fontFamily: "SanFrancisco",
          ),
          prefix: const Padding(padding: EdgeInsets.only(left: 8.0) , child: Icon(CupertinoIcons.search)),
          decoration: const BoxDecoration(border: null),
          clearButtonMode: OverlayVisibilityMode.editing,
        ),
      )
    );
  }
}```

**Comment by zoechi** [comment] 2019-02-19 16:39
Can you please make it a complete runnable example. Incl. `void main() {...}` and imports.
We try to avoid depending on assumptions how you used the code snippet to reproduce.
Just copy-paste and run should do.

**Comment by Renesanse** [comment] 2019-02-19 17:01
updated

**Comment by zoechi** [comment] 2019-02-19 17:08
Thanks! I can reproduce. Seems the button doesn't get the tap gesture.

**Comment by xster** [comment] 2019-02-19 21:49
I took a look and I strongly suspect that the issue will be fixed by https://github.com/flutter/flutter/pull/26659 where on non-supported devices will no longer 'steal' taps as being interpreted as high pressure force presses because the normal tap pressures are close to the devices' reported max pressure.

**Comment by xster** [comment] 2019-02-26 22:34
This issue should be fixed now. Please let us know if you're still experiencing it on master HEAD.

**Closed by xster** 2019-02-26 22:34 UTC
Labels: f: cupertino, framework, waiting for PR to land (fixed)

**Comment by Renesanse** [comment] 2019-02-27 09:52
Thanks
