### ISSUE TITLE
InteractiveViewer on Flutter for Web onInteraction does not considering zoom as an interaction

### ISSUE THREAD

**Issue by TerrenceAddison** [flutter/flutter#64852] opened 2020-08-29 04:20 UTC
## Use case
So what I found is that when using InteractiveViewer in flutter web, zoom in/out uses the Mouse Scroll Wheel to do this. When using onInteractionStart/Update/End it does not consider the scroll as an interaction and will not run the function in it. 
A sample code below:
`                 
              onInteractionUpdate:(details){
                    currentScale = details.scale;
                    print(currentScale);
                  },
`
So what happens is it will only print when panning and not when zooming in/out (scroll down/up).

## Proposal
What I hope is that the scrolling will be able to be considered as an Interaction by the onInteraction or another method to zoom in/out that will be considered by onInteraction as an interaction. I wasn't sure if this is considered a  bug or feature request so apologies if I post it on the wrong section!

**Comment by sidrao2006** [comment] 2020-08-29 06:21
Duplicate of #64210

**Comment by TerrenceAddison** [comment] 2020-08-29 14:22
> Duplicate of #63084

I'd argue it's not a duplicate because my issue is with onInteraction unable to detect zoom in web as an interaction but I do agree one of my solution proposal is related to it

**Comment by iapicca** [comment] 2020-08-30 09:18
I agree with @TerrenceAddison 
it seems to me this being a mouse specific issue

It would be useful to have a runnable repro code and your doctor

**Comment by TerrenceAddison** [comment] 2020-08-30 13:06
> I agree with @TerrenceAddison
> it seems to me this being a mouse specific issue
> 
> It would be useful to have a runnable repro code and your doctor

the code I used is the default flutter go board for InteractiveViewer demo but editted in the onInteractionUpdate code above 
for the doctor:
`
[√] Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.20.0-7.2.pre at C:\flutter
    • Framework revision a2bde82fbd (6 weeks ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Owner\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Owner\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\Owner\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
`

**Comment by iapicca** [comment] 2020-08-30 13:56
testing the code below with the latest master

<details>
<summary>sample</summary>

```dart
/// source [https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html#widgets.InteractiveViewer.1]

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: MyStatelessWidget(),
      ),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: InteractiveViewer(
        /// [try interact using mouse scrolling!]
        onInteractionUpdate: (ScaleUpdateDetails details) => print('$details'),

        ///
        boundaryMargin: EdgeInsets.all(20.0),
        minScale: 0.1,
        maxScale: 1.6,
        child: Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: <Color>[Colors.orange, Colors.red],
              stops: <double>[0.0, 1.0],
            ),
          ),
        ),
      ),
    );
  }
}

```


</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.22.0-2.0.pre.130, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-2.0.pre.130 at /home/francesco/development/flutter_master
    • Framework revision 12b7355da1 (26 hours ago), 2020-08-29 07:28:03 -0400
    • Engine revision 3029dcd93e
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] VS Code
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 2 categories.
```

</details>

[InteractiveViewer](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html#) ignore mouse scrolling in  `onInteractionUpdate` 
I'd consider this as a bug rather than a feature request

**Comment by TerrenceAddison** [comment] 2020-08-30 15:08
> testing the code below with the latest master
> 
> sample
> doctor
> [InteractiveViewer](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html#) ignore mouse scrolling in `onInteractionUpdate`
> I'd consider this as a bug rather than a feature request
> 
> related to #63060

Thank you very much, this is my first time posting an issue so I am still unfamiliar with formatting, apologies for the trouble

**Comment by TahaTesser** [comment] 2020-08-31 09:09
I agree with @iapicca, this is more of a bug, as it should've registered zooming on the web as interaction on `onInteractionUpdate`

Issue is reproducible 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.139, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-2.0.pre.139 at /Users/tahatesser/Code/flutter_master
    • Framework revision c0ea00ed3f (4 hours ago), 2020-08-30 22:20:16 -0700
    • Engine revision bada9fc5f3
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6.1
    • iPhone 11 (mobile)     • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by TerrenceAddison** [comment] 2020-09-01 15:08
@TahaTesser I plan on attempting to contribute the bug fix for this issue, I wonder if it's a feasible / possible PR and is anyone currently handling it?
If it is and no one is currently handling it, do you have any possible suggestions/lead on approaching this issue to reduce the chance of performance issues or other issues? 
Also I'd like to ask some short questions to start of:
which development environment should I be using; the Framework development or Engine Development?
Is the repository I'm supposed to fork is the main flutter repo?

Sorry for the beginner questions! Thank you in advance!

**Comment by justinmc** [comment] 2020-09-03 22:48
@TerrenceAddison Thank you for catching this problem!  At first glance I think it's just an oversight on my part.  I think I never wired up the mouse scrolling handler to call onInteraction.

If that's the case, it should be a totally doable PR.  I think you'll just need to find the right places to call onInteractionStart/Update/End, and then write a test.  There shouldn't be any performance concerns if you're just calling those directly.

We try to be faithful about using the "Assignees" on issues, so since no one is assigned to this one, you can assume no one is working on it.  I've just assigned you, but feel free to unassign if you end up not working on it.

You shouldn't need to touch the engine for this issue, so you can just follow the instructions for the framework.

Feel free ask if you need more help!

**Comment by TerrenceAddison** [comment] 2020-09-04 10:32
@justinmc 
So I have 2 solutions I feel to be feasible:
1.  the _ReceivedPointerSignal will run the child GestureDetector's onScaleUpdate property
2. the onScaleUpdate property also accepts scrollevent as an update
I was doing some research and feel the 2nd solution is more of a roundabout way and more complicated , I've tried to go forward for solution 1 but I can't find a way to call the onScaleUpdate property within the _ReceivedPointerSignal, do you have a suggestion on this? 
Or do you maybe have a different outlook of a solution to approach this?
I'm still pretty new to flutter so I may be unfamiliar to some better ways to approach it.

One of a semi-successful attempt is within the _ReceivedPointerSignal I put this code in:
`      if (widget.onInteractionUpdate != null) {
      widget.onInteractionUpdate(ScaleUpdateDetails(
        scale: scaleChange,    
      ));
    }`

This was able to trigger the onInteraction function when scrolling but I am unable to take values of the ScaleUpdateDetails unlike the __onScaleUpdate function. I also feel that this attempt is a bit on a crude side. 

Thank you in advance!

**Comment by justinmc** [comment] 2020-09-08 20:21
Sorry for the slow response, just getting back from a long weekend.  Usually Github is a good way to get ahold of me.  I'll respond over on your PR, but let me know if I missed anything!

**Comment by justinmc** [comment] 2020-09-14 16:01
Closing with https://github.com/flutter/flutter/pull/65313

**Closed by justinmc** 2020-09-14 16:01 UTC
Labels: P4, a: mouse, f: material design, found in release: 1.22, framework, has reproducible steps, platform-web
