### ISSUE TITLE
flutter/flutter ci.yaml validation fail presumit "generateGitHubToken failed"

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#95027] opened 2021-12-10 18:22 UTC
Exception: generateGitHubToken failed to get token from Github for repo=flutter/flutter

https://github.com/flutter/flutter/pull/94878/checks?check_run_id=4486933863

**Comment by CaseyHillers** [comment] 2021-12-10 18:28
Dupe of https://github.com/flutter/flutter/issues/94635

**Closed by CaseyHillers** 2021-12-10 18:28 UTC
Labels: team: infra
