### ISSUE TITLE
Blank Screen Problem when trying to publish iOS App

### ISSUE THREAD

**Issue by balanpaul** [flutter/flutter#32122] opened 2019-05-05 20:15 UTC
We are encountering some issues with publishing our app. First of all in debug mode it works on all emulators but during release, it doesn't work all the time. We have encountered a blank screen problem on Ipads. We encountered this problem on an Iphone as well (physical device), but after a flutter clean and flutter build iOS -release it worked. Then we have archived the app without selecting "compress the app" in XCode. Would you be able to tell us if you have experienced this "blank screen problem" on Ipads ? We would really appreciate any pieces of advice. Thank you!

## Steps to Reproduce

I don't know exactly
I tried before release this:
flutter clean
flutter build ios --release
Then we have archived the app without selecting "compress the app" in XCode.

In our project we use permission for location and notification

We use permission for notification and location. We use the following packages in flutter pubspec:

- cupertino_icons: ^0.1.2
- rxdart: ^0.18.0
- http: ^0.12.0+1
- firebase_database: ^2.0.2
- cloud_firestore: 0.9.13+1
- firebase_storage: ^2.1.0+1
- cached_network_image: ^0.7.0
- image_picker: ^0.5.3+1
- flutter_facebook_login: ^2.0.0
- flutter_auth_buttons: ^0.5.0
- firebase_auth: ^0.8.4+5
- url_launcher: ^5.0.2
- geolocator: ^4.0.1
- permission_handler: ^2.2.0
- shared_preferences: ^0.5.2
- flutter_range_slider: "^1.0.1"
- intl: ^0.15.8
- geocoder: ^0.1.2
- fluttertoast: ^3.0.4
- datetime_picker_formfield: ^0.1.8
- flutter_launcher_icons: ^0.7.0
- firebase_messaging: ^2.0.0
- firebase_crashlytics: ^0.0.4+2

**Comment by gustavobrian** [comment] 2019-05-06 15:43
yes, exact! similar problem with channel dev

**Comment by BondarenkoStas** [comment] 2019-10-14 20:58
@balanpaul is it the same while using current flutter stable and latest dependencies?

**Comment by iapicca** [comment] 2019-11-08 10:05
Hi @balanpaul 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 10:05 UTC
Labels: waiting for customer response
