### ISSUE TITLE
[Web] [CanvasKit] HtmlElementView is not interactive

### ISSUE THREAD

**Issue by vs-krasnov** [flutter/flutter#71479] opened 2020-12-01 13:29 UTC
Content of `HtmlElementView` is not interactive with CanvasKit. DomCanvas works correctly.

## Steps to Reproduce

1. Paste the following code:
```
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  // ignore: undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory(
      'hello-html',
      (int viewId) => IFrameElement()
        ..width = '640'
        ..height = '360'
        ..src = 'https://www.youtube.com/embed/xg4S67ZvsRs'
        ..style.border = 'none');

  runApp(
    Padding(
      padding: EdgeInsets.all(25),
      child: SizedBox(
        width: 640,
        height: 360,
        child: HtmlElementView(viewType: 'hello-html'),
      ),
    ),
  );
}
```
2. Run this application with enabled CanvasKit flag: `--dart-define=FLUTTER_WEB_USE_SKIA=true`;
3. Try to launch the video.

**Expected results:** The video can be launched (on DomCanvas).

**Actual results:** The video cannot be launched.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.375, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.375 at /Users/krasnov/sdk/flutter
    • Framework revision a7f5fd5360 (25 hours ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/krasnov/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/krasnov/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.67

• No issues found!
```
</details>

**Comment by omatt** [comment] 2020-12-01 15:57
I'm able to replicate the behavior using `Flutter (Channel master, 1.24.0-8.0.pre.375, on Mac OS X 10.15.7 19H15 darwin-x64)`

**CanvasKit flag enabled**. Play button is disabled while hovering the cursor.

![canvaskit_flag_enabled](https://user-images.githubusercontent.com/4143153/100763773-95216380-3430-11eb-8126-ea3670e43cde.gif)

**CanvasKit flag disabled**. Video can be played without issues.

![canvaskit_flag_disabled](https://user-images.githubusercontent.com/4143153/100763789-9bafdb00-3430-11eb-8cac-2e983887ab40.gif)

**Comment by darshankawar** [comment] 2020-12-02 06:34
@vs-krasnov There's similar open issue describing your case, [49634](https://github.com/flutter/flutter/issues/49634).
Does it resemble your case ?

**Comment by vs-krasnov** [comment] 2020-12-02 07:29
@darshankawar, I don't think they are related. #49634 reports general issues. 
This issue is related to CanvasKit only. DomCanvas works perfectly.

**Comment by darshankawar** [comment] 2020-12-02 08:42
Thanks for confirming @vs-krasnov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.406, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-8.0.pre.406 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 60bdcf55fe (67 minutes ago), 2020-12-01 21:24:21 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 87.0.4280.67

• No issues found!

```

</details>

**Comment by yjbanov** [comment] 2020-12-03 22:34
I think this is a duplicate of https://github.com/flutter/flutter/issues/69580. If we find that it's not, let's reopen this one.

**Closed by yjbanov** 2020-12-03 22:34 UTC
Labels: dependency: skia, e: web_canvaskit, engine, found in release: 1.24, has reproducible steps, passed first triage, platform-web
