### ISSUE TITLE
[Android] Flutter unreachable code crash with two different audio libraries

### ISSUE THREAD

**Issue by gert7** [flutter/flutter#113599] opened 2022-10-18 11:04 UTC
## Steps to Reproduce

1. Play audio from asset using just_audio or audio_players.
2. Crash

**Expected results:**
No error, audio playback

**Actual results:**
App crashes to home screen

<details>
<summary>Code sample</summary>

```dart
    final player = AudioPlayer();
    await player.setAsset(path); // some path that exists and is permitted in pubspec.yaml
    await player.setVolume(1.0);
    await player.play();
    await player.dispose();
```

</details>

<details>
  <summary>Logs</summary>

Here are the logs with just_audio (app name changed):
```
I/flutter(5277): assets/audio/strings_m4a/naine.m4a
I/ExoPlayerImpl(5277): Init c0e9832[ExoPlayerLib/2.17.1][OnePlus5T, ONEPLUS A5010, OnePlus, 29]
W/xx(5277): Accessing hidden method Landroid/media/AudioTrack
->getLatency()I(greylist, reflection, allowed)
E/Dart(5277): ../../third_party/dart/runtime/vm/message_snapshot.cc: 2185: error: unreachable code
E/DartVM(5277): version = 2.19.0-314.0.dev(dev)(Mon Oct 17 08: 54: 56 2022 - 0700) on "android_arm64"
E/DartVM(5277): pid = 5277, thread = 8519, isolate_group = (nil)(0x0), isolate = (nil)(0x0)
E/DartVM(5277): os = android, arch = arm64, comp = yes, sim = no
E/DartVM(5277): isolate_instructions = 0, vm_instructions = 6eb6389700
E/DartVM(5277):   pc 0x0000006eb64a7b2c fp 0x0000006ed450c420 / data/app/com.gert.xx-0u_oyVBGe8BHVF-OGsXn_A == /lib/arm64/libflutter.so+0x1b67b2c
E/DartVM(5277): -- End of DumpStackTrace
F/libc(5277): Fatal signal 6 (SIGABRT), code - 1 (SI_QUEUE) in tid 8519 (DartWorker), pid 5277 (xx)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'OnePlus/OnePlus5T/OnePlus5T:10/QKQ1.191014.012/2010292059:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-10-18 13: 53: 14+0300
pid: 5277, tid: 8519, name: DartWorker >> > com.gert.xx << <
uid: 10320
signal 6 (SIGABRT), code - 1 (SI_QUEUE), fault addr - -------
Abort message: '../../third_party/dart/runtime/vm/message_snapshot.cc: 2185: error: unreachable code'
x0  0000000000000000  x1  0000000000002147  x2  0000000000000006  x3  0000006ed450c3a0
x4  0000000000800000  x5  0000000000800000  x6  0000000000800000  x7  0000800000000000
x8  00000000000000f0  x9  b36a7d4e2c2332b3  x10 0000000000000001  x11 0000000000000000
x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000002  x15 0000ae6a44bee23d
x16 0000006fba59b8c0  x17 0000006fba577900  x18 0000006ec569e000  x19 000000000000149d
x20 0000000000002147  x21 00000000ffffffff  x22 0000000000000005  x23 0000000000000003
x24 7ffffffffffffff8  x25 1000000000000000  x26 0000000000000005  x27 00000000004c4b40
x28 0000000000000000  x29 0000006ed450c440
sp  0000006ed450c380  lr  0000006fba5290c4  pc  0000006fba5290f0
backtrace:
    # 00 pc 00000000000830f0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: e55e6e4c631509598633769798683023)
    # 01 pc 0000000001a48954  /data/app/com.gert.xx-0u_oyVBGe8BHVF-OGsXn_A==/lib/arm64/libflutter.so (BuildId: 88fc2edc27a704136153a1acf5e942751c391875)
    # 02 pc 0000000001ad38d0  /data/app/com.gert.xx-0u_oyVBGe8BHVF-OGsXn_A==/lib/arm64/libflutter.so (BuildId: 88fc2edc27a704136153a1acf5e942751c391875)
    # 03 pc 00000000001205f4  [anon:libc_malloc]
Lost connection to device.

Exited.
```

Here are the logs with audio_players:
```
I/flutter(5276): playing audio/strings_m4a/naine.m4a
E/Dart(5276): ../../third_party/dart/runtime/vm/message_snapshot.cc: 2185: error: unreachable code
E/DartVM(5276): version = 2.19.0-314.0.dev(dev)(Mon Oct 17 08: 54: 56 2022 - 0700) on "android_arm64"
E/DartVM(5276): pid = 5276, thread = 7489, isolate_group = (nil)(0x0), isolate = (nil)(0x0)
E/DartVM(5276): os = android, arch = arm64, comp = yes, sim = no
E/DartVM(5276): isolate_instructions = 0, vm_instructions = 6eb8809700
E/DartVM(5276):   pc 0x0000006eb8927b2c fp 0x0000006ea777b420 / data/app/com.gert.xx-1cSXg-hPdxikPwpQss370g == /lib/arm64/libflutter.so+0x1b67b2c
E/DartVM(5276): -- End of DumpStackTrace
F/libc(5276): Fatal signal 6 (SIGABRT), code - 1 (SI_QUEUE) in tid 7489 (DartWorker), pid 5276 (xx)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'OnePlus/OnePlus5T/OnePlus5T:10/QKQ1.191014.012/2010292059:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-10-18 13: 48: 48+0300
pid: 5276, tid: 7489, name: DartWorker >> > com.gert.xx << <
uid: 10320
signal 6 (SIGABRT), code - 1 (SI_QUEUE), fault addr - -------
Abort message: '../../third_party/dart/runtime/vm/message_snapshot.cc: 2185: error: unreachable code'
x0  0000000000000000  x1  0000000000001d41  x2  0000000000000006  x3  0000006ea777b3a0
x4  0000000000800000  x5  0000000000800000  x6  0000000000800000  x7  0000800000000000
x8  00000000000000f0  x9  b36a7d4e2c2332b3  x10 0000000000000001  x11 0000000000000000
x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000002  x15 0000ee08e3be7a01
x28 0000000000000000  x29 0000006ea777b440
sp  0000006ea777b380  lr  0000006fba5290c4  pc  0000006fba5290f0
backtrace:
    # 00 pc 00000000000830f0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: e55e6e4c631509598633769798683023)
    # 01 pc 0000000001a48954  /data/app/com.gert.xx-1cSXg-hPdxikPwpQss370g==/lib/arm64/libflutter.so (BuildId: 88fc2edc27a704136153a1acf5e942751c391875)
    # 02 pc 0000000001ad38d0  /data/app/com.gert.xx-1cSXg-hPdxikPwpQss370g==/lib/arm64/libflutter.so (BuildId: 88fc2edc27a704136153a1acf5e942751c391875)
    # 03 pc 0000000000508064  [anon:libc_malloc]
Lost connection to device.

Exited.

```

</details>

It seems I was able to play some audio that was previously played from the app cache, so this might have something to do with the asset system not working correctly? The files do exist and missing assets would give a different error.

**Comment by gert7** [comment] 2022-10-18 11:06
`flutter doctor -v` output:
```
[✓] Flutter (Channel master, 3.5.0-8.0.pre.31, on Arch Linux 6.0.2-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.5.0-8.0.pre.31 on channel master at /home/gert/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0ad71e8727 (9 hours ago), 2022-10-18 10:06:30 +0800
    • Engine revision 465ccd2974
    • Dart version 2.19.0 (build 2.19.0-314.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/gert/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.2
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.0.2-arch1-1
    • Chrome (web)    • chrome • web-javascript • Chromium 106.0.5249.119 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment] 2022-10-18 11:31
Hi @gert7 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in [just_audio repository](https://github.com/ryanheise/just_audio/tree/minor/just_audio) and [audioplayers repository](https://github.com/bluefireteam/audioplayers).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Comment by mraleph** [comment] 2022-10-18 12:38
Native crashes pointing to `../../third_party/dart/runtime/*{.cc,.h}` are all Dart issues so its okay to report them here.

**Comment by mraleph** [comment] 2022-10-18 12:48
The crash happens because we encounter some unknown typed data view cid when deserialising a message from the channel. Might have been accidentally fixed by @rmacnak-google in dart-lang/sdk@d2a43581a3af.

**Comment by huycozy** [comment] 2022-10-19 03:20
@gert7 Can you retry on the latest Flutter master channel and confirm the issue is fixed?

**Comment by gert7** [comment] 2022-10-19 08:35
On the new version 3.5.0-8.0.pre.46, after clearing the app's cache of (corrupted?) data, the audio files are now playing properly.

<details>
<summary>flutter doctor -v</summary>
```[✓] Flutter (Channel master, 3.5.0-8.0.pre.46, on Arch Linux 6.0.2-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.5.0-8.0.pre.46 on channel master at /home/gert/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abfaec6811 (78 minutes ago), 2022-10-19 08:13:17 +0100
    • Engine revision 563b8e830c
    • Dart version 2.19.0 (build 2.19.0-317.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/gert/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.2
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Linux (desktop)                  • linux         • linux-x64      • Arch Linux 6.0.2-arch1-1
    • Chrome (web)                     • chrome        • web-javascript • Chromium 106.0.5249.119 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!```

</details>

**Comment by huycozy** [comment] 2022-10-19 08:41
@gert7 thanks for confirming. Close the issue as fixed on master.

**Closed by huycozy** 2022-10-19 08:41 UTC
Labels: platform-android, dependency: dart, p: third party
