### ISSUE TITLE
HELP: flutter crash on release 1.17.1 (Work fine on everything else)

### ISSUE THREAD

**Issue by tuanha2000vn** [flutter/flutter#57318] opened 2020-05-15 15:09 UTC
**Flutter 1.12.13+hotfix.9 debug: Work**

**Flutter 1.12.13+hotfix.9 release: Work**
https://github.com/tuanha2000vn/Home-Assistant-Dashboard/releases/download/6.0/app-release.apk

**Flutter 1.17.1 debug: Work**
https://github.com/tuanha2000vn/Home-Assistant-Dashboard/releases/download/6.0.5/app.apk

**Flutter 1.17.1 release: Crash**
https://github.com/tuanha2000vn/Home-Assistant-Dashboard/releases/download/6.0.5/app-release.apk

**flutter doctor --verbose**
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-VN)
    • Flutter version 1.17.1 at /Users/hoanganhtuan/development/flutter
    • Framework revision f7a6a7906b (3 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hoanganhtuan/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • Nokia 7 plus       • B2NGAA8830704049                         • android-arm64 • Android 10 (API 29)
    • iPhone • 2baf6deff522d733da56ad8fbe6071321d4623d7 • ios           • iOS 13.4.1

• No issues found!
```

**Logcat**

```
2020-05-15 21:04:45.845 9183-9235/? A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x79e6dd5800 in tid 9235 (1.ui), pid 9183 (studio.hassdash)
2020-05-15 21:04:45.914 9318-9318/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG: Build fingerprint: 'Nokia/Onyx_00WW/B2N_sprout:10/QKQ1.190828.002/00WW_4_10G:user/release-keys'
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG: Revision: '0'
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG: ABI: 'arm64'
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG: Timestamp: 2020-05-15 21:04:45+0700
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG: pid: 9183, tid: 9235, name: 1.ui  >>> com.thhkstudio.hassdash <<<
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG: uid: 10485
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x79e6dd5800
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     x0  00000079e6dd57f9  x1  00000079ea3825f1  x2  0000000000000000  x3  00000079e6494d81
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     x4  0000000000000007  x5  0000007a6329c788  x6  0000000000000001  x7  0000000000000001
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     x8  00000079e9f94000  x9  0000000000000000  x10 0000000000000006  x11 0000000000000a00
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     x12 0000000002533e90  x13 0000000000110000  x14 0000000000000004  x15 0000007a00f45428
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     x16 0000007a00e6f000  x17 0000000000000004  x18 00000079f8ae0000  x19 00000079f47b27f1
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     x20 0000000000000000  x21 00000079ea14f980  x22 00000079ea380041  x23 0000007a00e6e000
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     x24 00000079e659ee41  x25 0000007a00e6e000  x26 00000079e9f94000  x27 00000079e6500040
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     x28 0000000000000004  x29 0000007a00f45428
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:     sp  0000007a00e6e000  lr  00000079f3ee3040  pc  00000079f3e7d014
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG: backtrace:
2020-05-15 21:04:45.915 9318-9318/? A/DEBUG:       #00 pc 000000000026e014  /data/app/com.thhkstudio.hassdash-PdxwHtA7qaYaPHeBgS6V4w==/lib/arm64/libapp.so (offset 0x2000) (_kDartIsolateSnapshotInstructions+2519060)
```

**Comment by TahaTesser** [comment] 2020-05-15 15:30
Hi @tuanha2000vn 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by tuanha2000vn** [comment] 2020-05-15 16:03
Flutter run —verbose work fine
Flutter run — release —venue work fine
Only crash after app starred

**Comment by tuanha2000vn** [comment] 2020-05-15 16:04
It’s part of the complete project, I can’t make a minimize sample code for now

**Comment by mraleph** [comment] 2020-05-15 16:08
I think this might be the same as https://github.com/dart-lang/sdk/issues/41910 so I will assign this to myself for now

**Comment by altherat** [comment] 2020-05-16 03:53
Getting this same crash in my app, but seemingly only upon opening a `Drawer`. It started since upgrading to 1.17.0 and like the OP, it only happens on the release version. I also confirmed it does not crash on 1.12.13+hotfix.9.

I've tried creating a simple example to demonstrate the crash but can't seem to recreate it. I haven't encountered a crash like this before, but it does appear to be memory related like @mraleph concluded.

The only other bit of information I can provide is my logcat includes: 
> Cause: null pointer dereference

**Comment by mraleph** [comment] 2020-05-16 09:30
I have figured out the cause and confirmed that the issue should already be fixed on other channels. I have confirmed that applying this fix and using rebuilt engine with APKs that I have access to (one provided by  @tuanha2000vn and one other one) fixes the issue. I have requested cherry pick of the relevant fix into stable channel. (see dart-lang/sdk#41928)

**Comment by altherat** [comment] 2020-05-16 10:29
@mraleph You mean I should not encounter this crash on the dev channel for instance? I still am getting it on the latest dev channel release (1.19.0-1.0.pre) but maybe my crash is different. :(

**Comment by mraleph** [comment] 2020-05-16 11:54
@altherat yeah, if you hit it on the dev channel - then you hit a different crash - please file a separate issue and provide details (e.g. stack trace of the crash from the `adb logcat`)

**Comment by tuanha2000vn** [comment] 2020-05-16 14:58
> I have figured out the cause and confirmed that the issue should already be fixed on other channels. I have confirmed that applying this fix and using rebuilt engine with APKs that I have access to (one provided by @tuanha2000vn and one other one) fixes the issue. I have requested cherry pick of the relevant fix into stable channel. (see [dart-lang/sdk#41928](https://github.com/dart-lang/sdk/issues/41928))

Thank you @mraleph

**Comment by 10ndavis** [comment] 2020-05-18 18:07
I believe I am also having the same issue. As @mraleph mentioned, if I check out older versions (1.16) or future versions (1.19) I do not see the issue. 

It only happens in release mode. Thanks for investigating this!

**Comment by tvolkert** [comment] 2020-05-20 21:38
eng approval for cp of https://github.com/dart-lang/sdk/commit/76bff1e1981ee7c0e5e9e0b6c3121f9ba8056dec into 1.17

**Closed** 2020-05-29 16:22 UTC
Labels: cp: 1.17 completed, dependency: dart, hotfix: 1.17, severe: crash, severe: regression
