### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for E:\DevEnvironment\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.

### ISSUE THREAD

**Issue by liuli19920328** [flutter/flutter#77345] opened 2021-03-05 08:55 UTC
## Command
```
flutter --quiet assemble --depfile E:\work\zhengfeng\flutter_library\.android\Flutter\build\intermediates\flutter\release/flutter_build.d --output E:\work\zhengfeng\flutter_library\.android\Flutter\build\intermediates\flutter\release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for E:\DevEnvironment\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:232:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
```
```
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19043.844], locale zh-CN)
    • Flutter version 2.0.1 at E:\DevEnvironment\flutter
    • Framework revision c5a4b4029c (15 hours ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\DevEnvironment\AndroidSDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = E:\DevEnvironment\AndroidSDK
    • Java binary at: E:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1.0)
    • Android Studio at E:\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at D:\IntelliJ IDEA
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] Connected device (2 available)
    • SM N9760 (mobile) • R3CM80CKCZY • android-arm64  • Android 11 (API 30)
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.zendaccess.flutter_library
**iOS bundle identifier**: com.zendaccess.flutterLibrary
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
flutter_custom_dialog-1.0.20
path_provider_linux-0.0.1+2
path_provider_windows-0.0.5
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3

**Comment by pedromassangocode** [comment] 2021-03-05 09:29
Duplicate of https://github.com/flutter/flutter/issues/68475.

**Closed by pedromassangocode** 2021-03-05 09:29 UTC
Labels: in triage
