### ISSUE TITLE
PageView widget swipe is not working on web

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#86959] opened 2021-07-23 20:18 UTC
Added the PageView widget in the app and run the code on the web.
The swipe on PageView is not working on the web.

Everything works fine on an Android device.
Here is the code which has the issue
https://github.com/deepak786/onboarding_screen

Github page with above code:
https://deepak786.github.io/onboarding-screen-demo/#/

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 2.4.0-4.0.pre, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.4.0-4.0.pre at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (12 days ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • XT1562 (mobile) • ZY2224VT7J • android-arm    • Android 7.1.1 (API 25)
    • Chrome (web)    • chrome     • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by kushankurxd** [comment] 2021-07-25 03:50
hey, I tried to reproduce the issue and found the problem is where you setted

`constraints: const BoxConstraints(
            maxWidth: 500,
          ),`

This means the swipe functionality of the `PageView` widget is bounded to `500`, not the whole page, that's why you can't swipe outside that area. To solve this, you should increase the width of the parent widget equal to the screen size or the area you want to swipe

**Comment by kushankurxd** [comment] 2021-07-25 04:00
Also try `stable` of flutter and see if it works, works well for me

[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at E:\flutter
    • Framework revision d79295af24 (6 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\kusha\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_291\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 1 category.

**Comment by deepak786** [comment] 2021-07-25 09:38
> hey, I tried to reproduce the issue and found the problem is where you setted
> 
> `constraints: const BoxConstraints( maxWidth: 500, ),`
> 
> This means the swipe functionality of the `PageView` widget is bounded to `500`, not the whole page, that's why you can't swipe outside that area. To solve this, you should increase the width of the parent widget equal to the screen size or the area you want to swipe

@kushankurxd the issue is Page view is not swiping even you try to swipe in the bounds.

Check the page https://deepak786.github.io/onboarding-screen-demo/#/
It will not swipe.

**Comment by kushankurxd** [comment] 2021-07-25 11:39
@deepak786  yes, can you try the `stable` channel of flutter and see if the issue still persits

**Comment by maheshmnj** [comment] 2021-07-26 07:18
Hi @deepak786, I ran your hosted site https://deepak786.github.io/onboarding-screen-demo/#/  in the browser and I was able to swipe through the pages both in Desktop and mobile browsers, let me know if I am missing anything.


https://user-images.githubusercontent.com/31410839/126948327-21a3c0e6-212b-4461-8b70-3978ddd3f8d0.mov

Thank you.

**Comment by deepak786** [comment] 2021-07-26 09:04
@maheshmnj are you able to swipe with the help of a mouse? because I'm not able to.
I the video, I see that your mouse is not moving when you swipe.

**Comment by maheshmnj** [comment] 2021-07-26 11:12
@deepak786  you are right I swiped using the laptop trackpad And you need to use an HTML renderer in order to make it work. 

```
flutter run -d chrome --web-renderer html // to run using HTML renderer
flutter build web --web-renderer html // to generate a build using HTML renderer 
```

You can read more about [flutter web renderers here](https://flutter.dev/docs/development/tools/web-renderers).

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';

class PageViewDemo extends StatefulWidget {
  PageViewDemo({Key? key}) : super(key: key);

  @override
  PageViewDemoState createState() => PageViewDemoState();
}

class PageViewDemoState extends State<PageViewDemo> {
  final PageController pageController = PageController(initialPage: 0);

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    pageController.addListener(() {
      print('page Changed');
    });
  }

  int page = 1;
  @override
  Widget build(BuildContext context) {
    List<Color> colors = [
      Colors.red,
      Colors.blue,
      Colors.orange,
      Colors.purpleAccent,
      Colors.greenAccent
    ];
    double width = MediaQuery.of(context).size.width;
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: PageView.builder(
              itemCount: 20,
              scrollDirection: Axis.horizontal,
              controller: pageController,
              itemBuilder: (_, index) => Container(
                height: 100,
                width: 100,
                color: colors[index % colors.length],
                child: Center(
                  child: Text('Page $index'),
                ),
              ),
            ),
          ),
          Expanded(
              child: Container(
                  alignment: Alignment.center,
                  child: ElevatedButton(
                    child: Text('Jump to page'),
                    onPressed: () {
                      pageController.jumpTo(page * width);
                      page += 1;
                    },
                  )))
        ],
      ),
    );
  }
}

```
</details>


<details>
<summary>Output</summary>

https://user-images.githubusercontent.com/31410839/126979753-c4f05ad4-e683-4850-8d39-8d3c4c6871ee.mov

</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.166, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.166 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2dc11a85ff (4 hours ago), 2021-07-22 17:56:03 -0700
    • Engine revision fbbb3b3f7b
    • Dart version 2.14.0 (build 2.14.0-343.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30)
      (emulator)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71
      darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      91.0.4472.164

• No issues found!
```
</details>

Thank you.

**Comment by maheshmnj** [comment] 2021-07-26 14:29
Can you please try the sample code provided in [this comment ](https://github.com/flutter/flutter/issues/86959#issuecomment-886608003)

**Comment by deepak786** [comment] 2021-07-26 20:34
not working

**Comment by maheshmnj** [comment] 2021-07-27 07:24
@deepak786, I ran [your code sample](https://github.com/flutter/flutter/issues/86959#issue-951871479) using the HTML renderer

`flutter run -d chrome --web-renderer html`

And I could see It running out of the box without any code changes.


https://user-images.githubusercontent.com/31410839/127113022-7211293b-18e6-4270-bd74-203abbdca8df.mov

**Comment by maheshmnj** [comment] 2021-07-27 07:45
@deepak786 I see that you are on the dev channel, This issue is reproducible on the master and the dev channel but works fine on the stable channel, so this seems to be a regression and I ran your sample code it's working fine on the stable channel using the HTML renderer by running

```
flutterd run -d chrome --web-renderer html
```

 You may switch to the stable channel until this issue is fixed by running 

```
flutter channel stable
flutter upgrade
```

<details>
<summary>flutter doctor for stable, master and dev</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.166, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.166 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2dc11a85ff (4 hours ago), 2021-07-22 17:56:03 -0700
    • Engine revision fbbb3b3f7b
    • Dart version 2.14.0 (build 2.14.0-343.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30)
      (emulator)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71
      darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      91.0.4472.164

• No issues found!
```

```
[✓] Flutter (Channel dev, 2.4.0-0.0.pre, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.4.0-0.0.pre at /Users/mahesh/Documents/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96bbcd006f (4 weeks ago), 2021-06-30 03:43:41 -0400
    • Engine revision c633b2a6a0
    • Dart version 2.14.0 (build 2.14.0-258.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```
</details>

<details>
<summary>Output from stable</summary>

https://user-images.githubusercontent.com/31410839/127116060-3380f028-57d0-48e3-8f16-d4a71a704f73.mov

</details>

**Comment by maheshmnj** [comment] 2021-07-27 09:00
@deepak786 This is an expected behaviour scrolling is disabled by default since this change https://github.com/flutter/flutter/pull/81569, please see the [migration guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) to enable mouse gestures.

Closing this issue as invalid. If you disagree feel free to comment and I will reopen it thank you.

**Closed by maheshmnj** 2021-07-27 09:00 UTC
Labels: found in release: 2.4, framework, has reproducible steps, platform-web, severe: regression

**Comment by deepak786** [comment] 2021-07-27 09:25
@maheshmnj I wasn't aware of this change.
I enabled the Mouse drag on the PageView by using the `ScrollConfiguration` and it worked fine.

Note: There is no need to use --web-renderer. It works just fine with `flutter run -d chrome`

Thank you.
