### ISSUE TITLE
Unable to install a simple app on iPhone simulator(4s) with iOS version 8.1 

### ISSUE THREAD

**Issue by Vikas-Jilla** [flutter/flutter#25537] opened 2018-12-19 05:22 UTC
```
Launching lib/main.dart on iphone4s8 in debug mode...
Xcode build done.                                           18.7s
PackageType = Developer;
SimulatorRootPath = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot";
SimulatorUserPath = "/Users/home/Library/Developer/CoreSimulator/Devices/9300BDCB-8352-423F-AC0D-740C5D25533E/data";
}
Added: {(
"com.example.**"
)}
Removed: {(
)}
Modified: {(
)}
CFBundleIdentifier = "com.example.***";
PackageType = Developer;
SimulatorRootPath = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot";
SimulatorUserPath = "/Users/home/Library/Developer/CoreSimulator/Devices/9300BDCB-8352-423F-AC0D-740C5D25533E/data";
})
arguments =     (
"--enable-dart-profiling",
"--enable-checked-mode",
"--start-paused",
"--observatory-port=0"
);
environment =     {
};
}
retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
Simulator booted at: 2018-12-19 04:58:15 +0000
Current time: 2018-12-19 05:14:14 +0000
Within boot leeway: NO
Unhandled exception:
FormatException: Bad UTF-8 encoding 0xbd (at offset 250)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:568:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#11     _StreamController._add (dart:async/stream_controller.dart:639:7)
#12     _StreamController.add (dart:async/stream_controller.dart:585:5)
#13     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
Exited (255)
```

**Comment by zoechi** [comment] 2018-12-19 06:36
Duplicate of #15646

**Closed by zoechi** 2018-12-19 06:36 UTC
