### ISSUE TITLE
video_player plugin not show texture in IOS device

### ISSUE THREAD

**Issue by xGANDx** [flutter/flutter#23061] opened 2018-10-13 22:45 UTC
Hello, the video_player does not show the texture, just the sound on the IOS devices, the android works correctly.

video_player: 0.6.5

<img width="400" alt="screen shot 2018-10-13 at 19 42 26" src="https://user-images.githubusercontent.com/10067343/46910739-35019780-cf20-11e8-864b-dc3e2cd277ee.png">

**Comment by Daibaku0615** [comment] 2018-10-15 00:16
If you’re running on iOS simulator, it won’t be played because playing video is not supported on iOS simulator.

**Comment by zoechi** [comment] 2018-10-15 07:28
Please add the output of `flutter doctor -v`.

**Comment by gand33** [comment] 2018-10-16 01:14
Good night, I tested it on the iPhone 6 plus and it does not appear the same texture, just sound.

flutter doctor -v:
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-BR)
    • Flutter version 0.9.4 at /Users/uizzy/development/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/uizzy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/uizzy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • iPhone XS Max • A73E00A3-A233-4439-81D4-0D065A2B4FD8 • ios • iOS 12.0 (simulator)

• No issues found!

```

**Comment by cbenhagen** [comment] 2019-01-28 17:23
Looks like a duplicate of https://github.com/flutter/flutter/issues/14647:

> [✓] Connected devices (1 available)
>     • iPhone XS Max • A73E00A3-A233-4439-81D4-0D065A2B4FD8 • ios • iOS 12.0 (simulator)

**Comment by zoechi** [comment] 2019-01-28 19:07
@cbenhagen this issue seems to be on a real device as well. #14647 is about the simulator.

**Comment by cbenhagen** [comment] 2019-01-28 19:30
Sorry must have missed that comment.

@gand33 can you provide us with more information please? Does that happen with all video sources? If not, can you provide a sample clip? Also some log output and a demo project could help us reproducing and diagnosing the issue.

**Comment by zoeyfan** [comment] 2020-01-03 07:13
Unfortunately there isn't enough information on this bug to reproduce the issue. Closing for now. 

If you are still experiencing this issue, you're welcome to reopen it. Please tell us exactly how to reproduce the problem you're running into. Attach a small sample that demonstrates the issue, or include the specific tool commands that reproduce the problem along with the results of running `flutter doctor -v`. 

Thank you for using Flutter!

**Closed by zoeyfan** 2020-01-03 07:13 UTC
Labels: a: video, e: device-specific, p: first party, p: video_player, plugin
