### ISSUE TITLE
Shadder Compliation Error

### ISSUE THREAD

**Issue by ProblematicDude** [flutter/flutter#78122] opened 2021-03-13 19:15 UTC
## Steps to Reproduce

1. Run `flutter run` and BOOM , 

It's 2021 and the Shadder error from 19 is still there. Can the existing issue be solved before, adding more and more features. I'm Getting too much Shadder spam that the terminal is almost unusable now. I cant see even my own debug statements. 

Already tried flutter clean.

Don't ask to turn off hardware rendering. Because that's what I'm doing from last 2 year. Turning that slows down the emulator to a level that , it cant be used anymore.

**Expected results:** No such Shadder spam on the output terminal

**Actual results:** 
 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 
D/skia    ( 6817): Shader compilation error
D/skia    ( 6817): ------------------------
D/skia    ( 6817): Errors:
D/skia    ( 6817): 

<details>
  <summary>Logs</summary>

```
[+12755 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xdd31a0c0: ver 3 1 (tinfo 0xdd30f080)
[+25440 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xd9e3bfe0: ver 3 1 (tinfo 0xdd3ffbf0)
[  +74 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xdd31a0c0: ver 3 1 (tinfo 0xdd30f080)
[ +176 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xd9e3bfe0: ver 3 1 (tinfo 0xdd3ffbf0)
[+16705 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xdd31a0c0: ver 3 1 (tinfo 0xdd30f080)
[ +177 ms] E/libEGL  ( 7390): call to OpenGL ES API with no current context (logged once per thread)
[+1653 ms] W/ActivityThread( 7390): handleWindowVisibility: no activity for token android.os.BinderProxy@ab06df8
[ +296 ms] D/EGL_emulation( 7390): eglCreateContext: 0xf077f7c0: maj 3 min 1 rcv 4
[  +40 ms] D/EGL_emulation( 7390): eglCreateContext: 0xf077f880: maj 3 min 1 rcv 4
[   +8 ms] D/HostConnection( 7390): HostConnection::get() New Host Connection established 0xdd3563c0, tid 7499
[   +3 ms] D/HostConnection( 7390): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2
ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem
ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands
ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache
ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync
ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3
GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing
ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_1
[   +9 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xf077f880: ver 3 1 (tinfo 0xb4ef1740)
[   +3 ms] E/eglCodecCommon( 7390): glUtilsParamSize: unknow param 0x000082da
[   +5 ms] E/eglCodecCommon( 7390): glUtilsParamSize: unknow param 0x000082da
[ +284 ms] D/HostConnection( 7390): HostConnection::get() New Host Connection established 0xc5a67f50, tid 7498
[   +2 ms] D/HostConnection( 7390): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2
ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem
ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands
ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache
ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync
ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3
GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing
ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_1
[  +18 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xf077f7c0: ver 3 1 (tinfo 0xd9e82fd0)
[   +8 ms] E/eglCodecCommon( 7390): glUtilsParamSize: unknow param 0x000082da
[   +2 ms] E/eglCodecCommon( 7390): glUtilsParamSize: unknow param 0x000082da
[  +48 ms] D/EGL_emulation( 7390): eglCreateContext: 0xf077fa00: maj 3 min 1 rcv 4
[  +14 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xf077fa00: ver 3 1 (tinfo 0xd9e82fd0)
[   +1 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xf077f7c0: ver 3 1 (tinfo 0xd9e82fd0)
[ +649 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xdd31a0c0: ver 3 1 (tinfo 0xdd30f080)
[  +76 ms] I/Choreographer( 7390): Skipped 55 frames!  The application may be doing too much work on its main thread.
[ +558 ms] D/EGL_emulation( 7390): eglMakeCurrent: 0xf077f7c0: ver 3 1 (tinfo 0xd9e82fd0)
[  +19 ms] D/skia    ( 7390): Shader compilation error
[   +1 ms] D/skia    ( 7390): ------------------------
[   +1 ms] D/skia    ( 7390): Errors:
[   +1 ms] D/skia    ( 7390): 
[  +17 ms] D/skia    ( 7390): Shader compilation error


```

```
```

```
[✓] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
    • Flutter version 2.0.2 at E:\Software\IDEs\Android\flutter
    • Framework revision 8962f6dc68 (2 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\Software\IDEs\Android\android-sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = E:\Software\IDEs\Android\android-sdk
    • Java binary at: E:\Software\IDEs\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = E:\Software\Browsers\Chrome\Chrome Stable x64 Launcher.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at E:\Software\IDEs\Android\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at E:\Software\IDEs\Intellij\Intellij
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!
```

</details>

**Comment by iapicca** [comment] 2021-03-14 12:42
@ProblematicDude 
on what platform are you experiencing the issue?
can you provide  complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by ProblematicDude** [comment] 2021-03-14 14:04
Atleast read the issue before COMPLETELY (Since you are asking the platform) . I have already provided flutter doctor -v.  And for the other part I would like to mention that its on Emulator. And its not something which can be produced intentionally. Its more of a engine issue.  See this https://github.com/flutter/flutter/issues/33018

**Comment by iapicca** [comment] 2021-03-14 14:42
> Atleast read the issue before COMPLETELY (Since you are asking the platform) . I have already provided flutter doctor -v. I can add more

@ProblematicDude 
I read your report, 
but I don't usually assume that the platform or the command that is producing the output from the `doctor`

> It's WINDOWS 10 , RYZEN 3500 , 16GB RAM , And for the other part I would like to mention that its on Emulator. 

the hardware of your windows machine is relevant only if you are running your flutter project as `windows app`

> And for the 3rd part its not something which can be produced intentionally. Its more of a engine issue ig ? 
> See this #33018 The other was closed that's why i filed a new issue

this was closed and locked about a year ago, your case might differ

---

I apologize if my request was not clear, I'll try to rephrase it;
given that the logs you provided appear to be produced by running your flutter project on a **_virtual android device_**
- are you experiencing the issue on `web` and `desktop` as well or `only on mobile` ?
- if the latter, is the issue occurring only on `virtual device` or on `physical device` as well ?

most importantly

> ## Steps to Reproduce
> 1. Run `flutter run` and BOOM ,

this is probably not comprehensive enough to reproduce the issue
please provide a[minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment] 2021-03-15 09:44
@ProblematicDude 
Please provide above requested details to properly address your issue.
Thanks.

**Comment by ProblematicDude** [comment] 2021-03-15 10:00
> 
> 
> > Atleast read the issue before COMPLETELY (Since you are asking the platform) . I have already provided flutter doctor -v. I can add more
> 
> @ProblematicDude
> I read your report,
> but I don't usually assume that the platform or the command that is producing the output from the `doctor`
> and logs produced by running the app on a virtual device do not rule out the issue occurring on a physical one
> 
> > It's WINDOWS 10 , RYZEN 3500 , 16GB RAM , And for the other part I would like to mention that its on Emulator.
> 
> the hardware of your windows machine is relevant only if you are running your flutter project as `windows app`
> 
> > And for the 3rd part its not something which can be produced intentionally. Its more of a engine issue ig ?
> > See this #33018 The other was closed that's why i filed a new issue
> 
> this was closed and locked about a year ago, your case might differ
> 
> I apologize if my request was not clear, I'll try to rephrase it;
> given that the logs you provided appear to be produced by running your flutter project on a **_virtual android device_**
> 
>     * are you experiencing the issue on `web` and `desktop` as well or `only on mobile` ?
> 
>     * if the latter, is the issue occurring only on `virtual device` or on `physical device` as well ?
> 
> 
> most importantly
> 
> > ## Steps to Reproduce
> > 
> > 1. Run `flutter run` and BOOM ,
> 
> this is probably not comprehensive enough to reproduce the issue
> please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

1. I haven't tried any other platform (web/desktop). I'm developing the app on ANDROID system.
2. It happens on EMULATOR, that too when I enable ```hardware rendering``` option in the emulator settings. ```Software rendering``` doesn't produce any such issue. But software rendering is itself an issue as it slows down the emulator. 
3. And about the third part. It doesn't happen in light weight apps like the default counter apps. It mostly happens when there is too much to render ig ? So i don't think  i can reproduce the issue. Just by providing a small piece of code. Neither anyone did in the ```existing closed issue``` or any existing post on the ```whole internet``` . One thing which i noticed , it mainly start giving such errors when I move my app to background and reopen it from recent app menu. Like when I go to home screen and when i reopen the app from recent menu it begins then no matter what  I do. I wont stop and will keep on printing on the console. Only solution is ```terminate the app``` and remember never to leave the app while it's running.

**Comment by iapicca** [comment] 2021-03-15 10:42
@ProblematicDude 

> on what platform are you experiencing the issue and does it occur on `virtual` or `physical` device (or both)?

> > * are you experiencing the issue on `web` and `desktop` as well or `only on mobile` ?
> > * if the latter, is the issue occurring only on `virtual device` or on `physical device` as well ?

> > > 2. It happens on EMULATOR, that too when I enable `hardware rendering` option in the emulator settings. `Software rendering` doesn't produce any such issue. But software rendering is itself an issue as it slows down the emulator.

if the issue does not occur on physical device it could be a problem with the emulator,
please run `flutter run --release -v` on **_physical_** device and provide the output


> It doesn't happen in light weight apps like the default counter apps. It mostly happens when there is too much to render 

please consider that
- the issue will not be workable  without a being reproduible
- the issue might not depend from `flutter`, but be caused by: 
   - a third party plugin
   - an error in **_your_** code
   
if you can not provide a code sample please provide clear steps to reproduce the issue
as requested in the template

```
## Steps to Reproduce

<!-- You must include full steps to reproduce so that we can reproduce the problem. -->

1. Run `flutter create bug`.
2. Update the files as follows: ... <!-- include every file that is different from the template app! -->
3. ... <!-- describe how to reproduce the problem -->
```

**Comment by ProblematicDude** [comment] 2021-03-16 12:48
You can close the issue as I don't think I'll be able to produce the issue without a large piece of code. One more thing i can tell, that all the time before this shadder spam. 
I can see this line on terminal.
```Skipped {some count} frames!  The application may be doing too much work on its main thread.``` 
It might be due to my bad coding. If that's the case. Sorry for bothering and please close this issue now.

**Comment by iapicca** [comment] 2021-03-16 12:59
> `Skipped {some count} frames! The application may be doing too much work on its main thread.`

@ProblematicDude 
this is very likely to depend from your implementation,
but it's impossible to tell for sure w/o a code sample

you may want to follow the [performance best practices](https://flutter.dev/docs/perf/rendering/best-practices)

**Comment by darshankawar** [comment] 2021-03-16 13:33
Closing this as non-actionable. Feel free to write in comments if you see a pattern / concrete steps to replicate this issue.

**Closed by darshankawar** 2021-03-16 13:33 UTC
Labels: in triage
