### ISSUE TITLE
[video_player] Initialization failure

### ISSUE THREAD

**Issue by Nuyoahhjh** [flutter/flutter#160861] opened 2024-12-26 09:42 UTC
### Steps to reproduce

Android
Device: Huawei p20. Huawei HONOR Play5. Huawei mate40e

### Expected results

![ef2a2bf9d823bba31b9583bc313c6ce8_](https://github.com/user-attachments/assets/d3c5fe31-f894-4a6e-8269-f4280fa76923)

### Actual results

![ef2a2bf9d823bba31b9583bc313c6ce8_](https://github.com/user-attachments/assets/f2289fb7-88cb-450e-be08-cfaef267114c)

### Code sample

<details open><summary>Code sample</summary>

```dart
void _loadVideo() {
    _controller = VideoPlayerController.networkUrl(Uri.parse("https://huiren-exam.cn-shanghai.oss.aliyuncs.com/course_m3u8/course/建立信任关系的沟通_1734599362198/建立信任关系的沟通_1734599362198.m3u8"))
      ..initialize().then((_) {
        setState(() {
          if (_currentVideoIndex != 0) {
            _controller.play();
          }
        });
      }).catchError((error) {
        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (context) => AlertDialog(
            title: Text('视频加载失败'),
            content: Text(error.toString()),
            actions: [
              TextButton(
                onPressed: () => Navigator.of(context).pop(),
                child: Text('确定'),
              ),
            ],
          ),
        );
      });
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-12-31 10:04
Closing this as a duplicate of https://github.com/flutter/flutter/issues/81804

**Closed by danagbemava-nc** 2024-12-31 10:04 UTC
Labels: in triage
