### ISSUE TITLE
flutter_gallery_ios32__transition_perf is flaky

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#53431] opened 2020-03-27 18:57 UTC
This test is failing and being restarted nearly every commit.
[flutter_gallery_ios32__transition_perf_6442611_3.log](https://github.com/flutter/flutter/files/4395392/flutter_gallery_ios32__transition_perf_6442611_3.log)

```
2020-03-27T10:59:26.111623: stderr: VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
2020-03-27T10:59:26.112028: stderr: VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
2020-03-27T11:03:45.663736: stdout: 05:02 [32m+0[0m[31m -1[0m: flutter gallery transitions all demos [1m[31m[E][0m[0m
stdout: 
2020-03-27T11:03:45.664663: stdout:   TimeoutException after 0:05:00.000000: Test timed out after 5 minutes.
```

<img width="52" alt="77691448-25cea800-6f62-11ea-8e3f-39e058f9345a" src="https://user-images.githubusercontent.com/682784/77790396-fc755100-7021-11ea-8949-4bf9d3c4164a.png">

**Comment by flar** [comment] 2020-03-27 19:03
It looks like https://github.com/flutter/flutter/commit/6c7c2e372ae6cbf20c6601f4eb11f9cbfb09b591 is where the benchmark became flaky. I'm now running the benchmark manually on the previous commit to establish stability there and will then run it on the suspect commit and see if there is a distinct rise in the flakiness.

**Comment by gaaclarke** [comment] 2020-03-27 19:06
@godofredoc is this possibly a hardware or infra issue with that janky phone?

**Comment by gaaclarke** [comment] 2020-03-27 19:11
I looked back in our logs so long my wrist hurt from scrolling.  This thing has always been flakey.  I looked back the whole month of march.

**Comment by jmagman** [comment] 2020-03-27 19:37
> I looked back in our logs so long my wrist hurt from scrolling. This thing has always been flakey. I looked back the whole month of march.

I think it's gotten much worse recently.  For example from 31175e..af21e (19 commits) it passed on the first try except for three times it failed on the second (yes, still flaky).  But in the last few days it's usually failed the first time, and sometimes needs up to [4 runs to pass](https://github.com/flutter/flutter/files/4395588/flutter_gallery_ios32__transition_perf_c9f9992_4.1.log).

**Comment by flar** [comment] 2020-03-27 19:47
This benchmark has never been 100%, but just a few days ago it went from "requiring a rerun once every 4-5 runs" to "nearly always requiring a rerun and sometimes just failing outright".

But, here's the thing. This all looks like it started with https://github.com/flutter/flutter/commit/6c7c2e372ae6cbf20c6601f4eb11f9cbfb09b591 which failed the benchmark outright with two disconnects. I just ran the benchmark 5 times in a row on that commit and it ran to completion every time.

I'm suspecting there is something going on with the phone, or more likely its lightning cable is being flaky.

**Comment by flar** [comment] 2020-03-27 19:51
If you have another commit you suspect, let me know and I'll do a bunch of runs on it locally to see if it's the software, or if it is the testbed...

**Comment by gaaclarke** [comment] 2020-03-27 20:10
It is my duty as sheriff to make a best effort to root cause the issue.  Having fulfilled that role, with the power granted to me by the Flutter Council I find flutter_gallery_ios32__transition_perf guilty of sedition and it will be disabled with extreme prejudice.

Surviving maintainers of the test will be notified and petitions for fixing the test will be open upon removal.

**Comment by tvolkert** [comment] 2020-03-29 20:34
Closing - filed https://github.com/flutter/flutter/issues/53537 to re-enable.

**Closed by tvolkert** 2020-03-29 20:34 UTC
Labels: engine, severe: regression, ⚠ TODAY
