### ISSUE TITLE
No Zooming in or out by clicking 'Ctrl' + mouse wheel

### ISSUE THREAD

**Issue by awaisCh07** [flutter/flutter#137322] opened 2023-10-26 07:05 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am trying to zoom in my web page but it is not getting zoomed in by clicking ctrl + mouse wheel but it works with ctrl + '-' or '+'
i created mobile app with flutter and then i run this code for web 

### Expected results

the page should get zoom in or out by clicking ctrl + mouse wheel

### Actual results

it has no effect when i click ctrl + mouse wheel

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2023-10-26 08:47
Closing this as a duplicate of https://github.com/flutter/flutter/issues/129933

**Closed by darshankawar** 2023-10-26 08:47 UTC
Labels: in triage
