### ISSUE TITLE
Firebase_auth no passwordless signon method

### ISSUE THREAD

**Issue by JosephDunivan** [flutter/flutter#24995] opened 2018-12-05 19:22 UTC
It would be great to have an implementation for passwordless signon. Its an option in firebase but not the plugin. Can we add a method and documentation for this?

**Comment by cbenhagen** [comment] 2019-02-27 17:41
Duplicate of https://github.com/flutter/flutter/issues/22958.
Check out this PR: https://github.com/flutter/plugins/pull/1159

**Comment by JosephDunivan** [comment] 2019-03-09 04:47
> Duplicate of #22958.
> Check out this PR: [flutter/plugins#1159](https://github.com/flutter/plugins/pull/1159)

Actually their's is a duplicate of mine. I submitted this last December. But good to know it's being worked on.

**Comment by kroikie** [comment] 2019-10-13 18:39
@JosephDunivan

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/557. Any further collaboration will be done there.

**Closed by kroikie** 2019-10-13 18:39 UTC
Labels: p: firebase, p: firebase_auth, p: first party, plugin, severe: new feature
