### ISSUE TITLE
Pass environment variables to flutter 

### ISSUE THREAD

**Issue by arielnmz** [flutter/flutter#18377] opened 2018-06-11 22:20 UTC
I know this has been asked several times, however I'm surprised I couldn't find an entry suggesting an approach similar to Webpack+Nativescript where webpack reads vars from the environment and passes down a static object with the values set. In this case it could work by reading a very specific pattern from the cli's parameters, like:

    $ flutter run/build --env.DEBUG

And then it would just be a matter of initializing a static data structure that would hold the passed parameters:

~~~
if (flutter.env.DEBUG) {
    print("DEBUG")
}
~~~

I am aware of the [multiple entry points approach](https://flutter.rocks/2018/03/02/separating-build-environments-part-one/), but I think it becomes unintuitive when the dev environment changes constantly (e.g. having a PC at work and also working from home or while traveling), let alone when working with more people and each has their own dev environment and you end up polluting the working tree just to change an IP to test a change with a local server.

**Comment by pq** [comment] 2018-08-22 14:30
Bumping this one as I'm exploring something similar as a means to initialize logging details for flutter runs.  Is support for passing args to `flutter run` planned?  

FWIW: there are a few special cases already that a general solution would potentially simply?

https://github.com/flutter/flutter/blob/18e7549bc8f2ae1d061c943fcf3f8de251f6a5fa/packages/flutter_tools/lib/src/commands/run.dart#L178-L179

cc @cbracken @chinmaygarde @Hixie

**Comment by zoechi** [comment] 2018-08-22 14:41
That would be great.

The usual suggested workaround is to use different entry point files

```sh
flutter run -t lib/main_debug.dart
```

**Comment by pdf** [comment] 2019-08-09 05:51
I think build-/compile-time variables are really what we're looking for here? (#26638)

**Comment by jonahwilliams** [comment] 2020-01-09 22:02
Duplicate of https://github.com/flutter/flutter/issues/26638

**Closed by jonahwilliams** 2020-01-09 22:02 UTC
Labels: framework, severe: new feature, tool
