### ISSUE TITLE
Set locale of subtree

### ISSUE THREAD

**Issue by Leffe108** [flutter/flutter#98835] opened 2022-02-20 17:36 UTC
## Use case
There are situations when app UI is in one language and it will show content of a different language. In HTML it is possible to markup this content of a foreign language with the `lang` attribute so that assistive technology like VoiceOver can use the right voice engine for that content.

### Single word from other language
I have an app where the UI is in Swedish:
```dart
      supportedLocales: [
        const Locale('sv', 'SE'), // Swedish
      ],
```

But the name of the app contains the English word "Quiz". However VoiceOver struggle to read it out correctly when it uses the Swedish voice engine (it is almost silent gibberish). So I want to provide metadata that this text is in English.

Here is a audio recording on how bad it sounds when Swedish voice is used to read out "quiz" from my Flutter app: 

https://user-images.githubusercontent.com/4630670/154855872-79fcdfe0-1981-463f-ba91-96b926d1704a.mp4

**In HTML I can do this:**
```html
<html lang="sv-SE"><body>
<p>Välkommen till TSP <span lang="en-UK">Quiz</span></p>
</body></html>
```
[demo](https://tspquiz.se/locale.html)

https://user-images.githubusercontent.com/4630670/154855602-1f3f6dd3-bcd1-4a46-8d91-679c3366ee84.mp4

Note: Turn on sound on the video. Audio description: It says "Välkommen till TSP" with Swedish voice. Then switches to UK voice and says "Quiz".

### Content reader app
Another use case could be a content reader app like a news feed app. It could consume news items from different sources of more than one language. The app UI would remain in one language while user uses the app. But the article content would be great if it can be marked up as the correct locale so VocieOver is able to pick a suitable voice engine for the content to read up.

## Proposal
* A new widget that takes a locale and a child which sets the locale of the subtree.
* Some widgets like Semantics, Text or TextSpan could as shortcuts have a locale property.

**Comment by danagbemava-nc** [comment] 2022-02-21 11:40
Hi @Leffe108, it looks like the Text widget already has a `locale` property that you can use to set the preferred locale. 

There's also a `Localizations` widget, it has a `.override` factory that you can use as well. 

Can you check if the `locale` property of `Text` and the `Localizations.override` help you achieve what you want to achieve?

**Comment by Leffe108** [comment] 2022-02-21 21:23
Hi, I missed the locale property on Text(). Whenever I use VS Code and type locale it auto-completes the Locale type and not the locale property, but I should have looked better at the docs as well.

# iOS
For this testing I now test on an iPad where I have set the system language to Norwegian - a language similar enough to Swedish for me to understand but distinct enough that I can tell it apart from Swedish. 

With this setup I will be able to hear if VocieOver uses MaterialApp lanuage (sv-SE), system lanugage (Norwegian Bokmål) or the override to en-US.

Texts in the app not overridden with examples given below are read out in Swedish.

**Works**
This works. It spells out TSP in Norwegian and then speaks "Quiz" in English.

It does not solve my case though as it is to have the semantic label of an image set to a different language.
```dart
Text.rich(
  TextSpan(children: [
    TextSpan(text: 'TSP', spellOut:  true),
    TextSpan(text: ' Quiz', locale: Locale('en', 'US')),
  ]),
),
```

**Does not work**
Now things get interesting. This solution below reads out the text "TSP Quiz" in Norwegian. The system language - not the MaterialApp lanugage.
```dart
Localizations.override(
  context: context,
  locale: Locale('en', 'US'),
  child: Image.asset(
    'assets/images/head.png',
    semanticLabel: 'TSP Quiz',
  ),
),
```

**Does not work** 
As the above example uses a `semanticLabel` I decided to test again with a visual `Text()` inside `Localaizations.override`. But this attempt gave the same response as the previous. - The text, in this case "Localizations.override" is read out in Norwegian - the system language.
```dart
Localizations.override(
   context: context,
   locale: Locale('en', 'US'),
   child: Text('Localizations.override'),
 ),
```

**Does work**
I dived into some issues and found out about `attributedLabel` and figured out the following solution which does work. It reads out "TSP" in Swedish and then "Quiz" in English. I 
```dart
Semantics(
  attributedLabel: AttributedString('TSP Quiz', attributes: [
    LocaleStringAttribute(range: TextRange(start: 4, end: 8), locale: Locale('en', 'US')),
  ]),
  child: Image.asset(
    'assets/images/head.png',
  ),
),
```

# Web
I also did some testing with Flutter Web and there it seems to not work at all. In fact I realized that the default index.html created by `flutter create some_name` does not set lang attribute of `html`. Without it, VocieOver uses whatever locale is of the iOS device. If I set it to sv-SE or eg. en-US it will stick to that for the entire app. Flutter Web does not seem to communicate at all the global locale nor sub-tree locales. This might warrant a separate issue as it is a different thing from this issue.

**Comment by danagbemava-nc** [comment] 2022-02-22 06:57
Hi @Leffe108, glad you found a solution. 

Kindly file a new issue for web, but please check for already existing issues. 

Can you also file an issue for `Localizations.override` and provide steps to reproduce? According to the docs, it should have worked so this is probably a bug that needs to be fixed. This is what it states

```
 /// Overrides the inherited [Locale] or [LocalizationsDelegate]s for `child`.
  ///
  /// This factory constructor is used for the (usually rare) situation where part
  /// of an app should be localized for a different locale than the one defined
  /// for the device, or if its localizations should come from a different list
  /// of [LocalizationsDelegate]s than the list defined by
  /// [WidgetsApp.localizationsDelegates].
  ///
  /// For example you could specify that `myWidget` was only to be localized for
  /// the US English locale:
  ///
  /// ```dart
  /// Widget build(BuildContext context) {
  ///   return Localizations.override(
  ///     context: context,
  ///     locale: const Locale('en', 'US'),
  ///     child: myWidget,
  ///   );
  /// }
  /// ```
  ///
  /// The `locale` and `delegates` parameters default to the [Localizations.locale]
  /// and [Localizations.delegates] values from the nearest [Localizations] ancestor.
  ///
  /// To override the [Localizations.locale] or [Localizations.delegates] for an
  /// entire app, specify [WidgetsApp.locale] or [WidgetsApp.localizationsDelegates]
  /// (or specify the same parameters for [MaterialApp]).
```


Seeing as setting Locales for certain parts of the app is already supported, I'm going to close this issue. 

Thank you

**Closed by danagbemava-nc** 2022-02-22 06:57 UTC
Labels: in triage
