### ISSUE TITLE
[canvas_kit] `embedded_views` are not being rendered properly from `v3.7.0`

### ISSUE THREAD

**Issue by Juliotati** [flutter/flutter#124919] opened 2023-04-15 13:45 UTC
After upgrading to flutter `v3.3.7`, embedded views are now "broken" on `canvaskit` renderer.
> Everything is fine with `html` renderer

# Screen recordings
### Working version `(flutter v3.3.7)`
- Both `iframes`_(stream video and chat)_ are rendered without any issues ✅ 
- Additional `iframes` are rendered without any issues ✅ 

https://user-images.githubusercontent.com/59662912/215334200-dfb20f64-65e2-4841-8570-92ea670093e8.mp4

### Broken version after `(flutter v3.7.0)`

https://user-images.githubusercontent.com/59662912/215333996-6d2d2cd7-5e3a-44e6-afb3-90f0438d47f7.mp4

> Observations
- Rendering only one `iframe` seems to work, but the same issue is present when more are rendered 🚫 
- `iframes` stay in view with transparency after navigation 🚫 
 
assertion error points [here](https://github.com/flutter/engine/blob/649362168faad2b0be78151f08b7e7dc03a0f7ce/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart#L689)

_Originally posted by @Juliotati in https://github.com/flutter/flutter/issues/118452#issuecomment-1407684265_
            
cc @ditman

**Comment by darshankawar** [comment] 2023-04-17 06:41
Thanks for the report @Juliotati 
Can you provide us a minimal code sample that shows the reported behavior ?
From the linked issue, I tried the code sample as mentioned https://github.com/flutter/flutter/issues/118452#issuecomment-1383909098 which gives me below using latest master and stable version but I am not sure if it represents your use case as reported.

<img width="417" alt="Screenshot 2023-04-17 at 12 04 59 PM" src="https://user-images.githubusercontent.com/67046386/232404551-2a6f207b-7a4a-416f-b799-d55d26650e03.png">

**Comment by Juliotati** [comment] 2023-04-20 16:14
@darshankawar i'll provide a code sample soon. 
The linked issue was just where i originally posted but they are different issues.

**Comment by Juliotati** [comment] 2023-05-01 19:42
**Update:**
I tried the exact same code in a new project and it worked fine on `v3.7.11` as it did before update `v3.7.0`

<details><summary>Minimal Code Sample</summary>
<p>

```dart
import 'dart:html' as html;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

import 'package:url_strategy/url_strategy.dart';

void main() {
  setPathUrlStrategy();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Canvas-kit iframe',
      home: IFrameBody(),
    );
  }
}

class IFrameBody extends StatefulWidget {
  const IFrameBody({super.key});

  @override
  State<IFrameBody> createState() => _IFrameBodyState();
}

class _IFrameBodyState extends State<IFrameBody> {
  bool _loading = true;
  String channelName = 'selfdev_tv';

  void registerStream(String channel) async {
    setState(() => _loading = true);
    channelName = channel;
    await TwitchIFrameHelper.instance.setupStream(channelName: channelName);
    setState(() => _loading = false);
  }

  @override
  void didChangeDependencies() {
    registerStream('selfdev_tv');
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return _loading
        ? const Center(child: CircularProgressIndicator())
        : Row(
            children: [
              Expanded(
                child: Column(
                  children: [
                    SizedBox(
                      height: 600,
                      width: double.infinity,
                      child: HtmlElementView(
                        key: const Key('iFrame<StreamPlayer>'),
                        viewType: const TwitchIframeSettings().iframeStreamId(
                          channelName,
                        ),
                      ),
                    ),
                    TextButton(
                      onPressed: () => registerStream('lululuvely'),
                      child: const Text('channel: 🔥lululuvely'),
                    ),
                    TextButton(
                      onPressed: () => registerStream('selfdev_tv'),
                      child: const Text('channel: 🔥selfdev_tv'),
                    ),
                    TextButton(
                      onPressed: () => registerStream('piratesoftware'),
                      child: const Text('channel: 🔥piratesoftware'),
                    ),
                  ],
                ),
              ),
              SizedBox(
                height: double.infinity,
                width: 350,
                child: HtmlElementView(
                  key: const Key('iFrame<StreamChat>'),
                  viewType: const TwitchIframeSettings().iframeStreamChatId(
                    channelName,
                  ),
                ),
              )
            ],
          );
  }
}

class TwitchIFrameHelper {
  TwitchIFrameHelper._();

  static TwitchIFrameHelper instance = TwitchIFrameHelper._();

  final _iframeStreamElement = html.IFrameElement();
  final _iframeStreamChatElement = html.IFrameElement();

  static TwitchIframeSettings settings = const TwitchIframeSettings();

  Future<void> setupStream({
    required String channelName,
  }) async {
    await _setupStreamIFrame(channelName);
    await _setupStreamChatIFrame(channelName);

    await ui.platformViewRegistry.registerViewFactory(
      settings.iframeStreamId(channelName),
      (viewId) => _iframeStreamElement,
    );
    await ui.platformViewRegistry.registerViewFactory(
      settings.iframeStreamChatId(channelName),
      (viewId) => _iframeStreamChatElement,
    );
  }

  Future<void> _setupStreamIFrame(String channelName) async {
    _iframeStreamElement.style.width = settings.width;
    _iframeStreamElement.style.height = settings.height;
    _iframeStreamElement.style.border = settings.border;
    _iframeStreamElement.style.cursor = settings.cursor;
    _iframeStreamElement.style.backgroundColor = settings.backgroundColor;
    _iframeStreamElement.allowFullscreen = true;
    _iframeStreamElement.src =
        TwitchIframeSettings.twitchIFrameChannel(channelName);
  }

  Future<void> _setupStreamChatIFrame(String channelName) async {
    _iframeStreamChatElement.style.width = settings.width;
    _iframeStreamChatElement.style.height = settings.height;
    _iframeStreamChatElement.style.border = settings.border;
    _iframeStreamChatElement.style.cursor = settings.cursor;
    _iframeStreamChatElement.style.backgroundColor = settings.backgroundColor;
    _iframeStreamChatElement.src =
        TwitchIframeSettings.twitchIFrameChat(channelName);
  }
}

class TwitchIframeSettings {
  const TwitchIframeSettings({
    this.width = '100%',
    this.height = '100%',
    this.border = 'none',
    this.cursor = 'auto',
    this.backgroundColor = '#000000',
  });

  String iframeStreamId(String value) {
    return 'iframeTwitchStream:$value';
  }

  String iframeStreamChatId(String value) {
    return 'iframeTwitchStreamChat:$value';
  }

  static const String twitchIFramePlayer = 'https://player.twitch.tv';
  static const String twitch = 'https://www.twitch.tv';

  static get hostname => html.window.location.hostname;

  static String twitchIFrameChannel(String channel) {
    const String fullScreen = 'allowfullscreen=true';
    return '$twitchIFramePlayer/?channel=$channel&parent=$hostname&$fullScreen';
  }

  static String twitchIFrameChat(String channel) {
    return '$twitch/embed/$channel/chat?darkpopout&parent=$hostname';
  }

  final String width;
  final String height;
  final String border;
  final String cursor;
  final String backgroundColor;
}

``` 

</p>
</details> 

Not sure yet if this is only an issue with existing projects that came before `v3.7.0`. I'll continue trying

**Comment by darshankawar** [comment] 2023-05-02 05:13
Thanks for the update. Also you may try by creating a new Flutter project and running the code sample on latest stable (3.7.12) or master to see if it still persists or not.

**Comment by ashekelahe** [comment] 2023-05-08 04:16
The issue is still exists on flutter 3.7.11 and 3.7.12

**Comment by ditman** [comment] 2023-05-08 18:13
Flutter 3.10 is around the corner, can this be quickly tested with the `beta` channel to confirm that the issue still exists?

**Comment by darshankawar** [comment] 2023-05-09 05:03
@Juliotati  @ashekelahe Please verify this on latest beta and confirm if the issue persists or not.

`flutter channel beta`
`flutter upgrade`

**Comment by Juliotati** [comment] 2023-05-09 23:35
## Update

- After fighting with some dependencies for almost 2days, everything is working fine again ✅
### versions:
- flutter `v3.10.0-1.5.pre` channel beta
- dart `Dart 3.0.0 (build 3.0.0-417.4.beta)`

### Extra:
- The emojis on canvaskit is fixed too. cc https://github.com/flutter/flutter/issues/119536#issuecomment-1520939918  ✅

<a href="https://theselfdev.com/community/julio-tati"><img src="https://user-images.githubusercontent.com/59662912/159568426-01f0f338-7383-4b93-bcfe-0ef4e285bbec.gif" height="220" alt="Blazing Elmo"/></a>

_I guess we can close this issue, or wait until it's in the stable channel?_

**Comment by ditman** [comment] 2023-05-10 00:08
@Juliotati we can wait until this is stable ;)

**Comment by darshankawar** [comment] 2023-05-12 05:21
Thanks for the update. Will close it as fixed based on above comment.

**Closed by darshankawar** 2023-05-12 05:21 UTC
Labels: in triage
