### ISSUE TITLE
webview_flutter: unknown setting key: debuggingEnabled

### ISSUE THREAD

**Issue by yezxxx** [flutter/flutter#34620] opened 2019-06-18 03:27 UTC
Hey guys, I use webview_flutter plugin and I got a wrong message `webview_flutter: unknown setting key: debuggingEnabled`, what should I do to fix this problem? Thank you!

**Comment by wqhiOS** [comment] 2019-06-18 09:53
the same issue

**Comment by jjjachyty** [comment] 2019-06-19 11:36
+1

**Comment by nnquan** [comment] 2019-06-22 03:49
+ 1

**Comment by nnquan** [comment] 2019-06-22 03:49
+1

**Comment by mnc12004** [comment] 2019-06-24 10:08
+1

**Comment by shuyanzi** [comment] 2019-06-25 02:41
the same issue....

**Comment by jonahwilliams** [comment] 2019-06-25 02:44
+1 adds nothing to the discussion and only creates noise for subscribers of the issue. Please add a reaction +1 to the original issue instead

**Comment by chustruth** [comment] 2019-07-03 14:58
Same Issue and I'll include code because no one has stated anything:

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

`import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewContainer extends StatelessWidget {
  final url;
  WebViewContainer(this.url);
  final _key = UniqueKey();
  @override
  Widget build(BuildContext context) {
    final GlobalKey<ScaffoldState> _scaffoldKey =
        new GlobalKey<ScaffoldState>();
    return Scaffold(
      key: _scaffoldKey,
        body: Column(
          children: [
            Expanded(
                child: WebView(
                    key: _key,
                    javascriptMode: JavascriptMode.unrestricted,
                    initialUrl: url))
          ],
        ));
  }
}
`

**Comment by amirh** [comment] 2019-07-15 23:37
Which platform are you running on? can you share the output of `flutter doctor -v` and the version of webview_flutter you're using?

**Comment by amirh** [comment] 2019-07-16 00:59
Seems like a regression introduced in https://github.com/flutter/plugins/pull/1401 the iOS code was not updated to ignore the setting key and thus is logging an error.

Sent https://github.com/flutter/plugins/pull/1857 to fix the issue.

**Comment by amirh** [comment] 2019-07-16 19:26
Fixed in 0.3.10+3

**Closed by amirh** 2019-07-16 19:26 UTC
Labels: p: webview, plugin
