### ISSUE TITLE
CupertinoNavigationBar Alignment is Wrong

### ISSUE THREAD

**Issue by kornha** [flutter/flutter#89951] opened 2021-09-12 18:40 UTC
Hello,

I don't post issues much but this is a major problem.
The CupertinoNavigationBar leading and trailing icons are misaligned! I found this issue with the following code:
```
CupertinoPageScaffold(
      resizeToAvoidBottomInset: false,
      navigationBar: CupertinoNavigationBar(
        trailing: CupertinoButton(
          child: Icon(
            CupertinoIcons.chevron_right,
            color: CupertinoTheme.of(context).primaryColor,
          ),
          onPressed: null,
        ),
      ),
```

<img src="https://user-images.githubusercontent.com/5386694/132999035-43c248fa-dd3d-4df3-8e07-d1d1437d757c.png" width ="300">

 I see this issue here: https://github.com/flutter/flutter/issues/18536 but even if I use said alignment it still doesn't align perfectly.
Please advise if I'm doing something wrong.
Flutter version 2.5.
No flutter doctor Issues

**Comment by maheshmnj** [comment] 2021-09-13 09:29
@kornha Thanks for filing the issue, Are you talking about the alignment of leading and trailing icons?

**Comment by TahaTesser** [comment] 2021-10-05 10:47
duplicate of https://github.com/flutter/flutter/issues/49157

**Closed by TahaTesser** 2021-10-05 10:47 UTC
Labels: in triage

**Comment by victorsanni** [comment] 2025-06-05 22:35
This can be fixed by setting the padding of the CupertinoButton to EdgeInsets.zero.
