### ISSUE TITLE
GL proc resolver couldnot resolve glGetString

### ISSUE THREAD

**Issue by limbouser** [flutter/flutter#55833] opened 2020-04-28 09:14 UTC
What could be the reason for the error

[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(41)] Check failed : gl_get_string. The GL proc resolver couldnot resolve glGetString
Aborted (core dumped)

What could be the reason for this? What changes will I have to make in engine building or the system to get past this? I assumed [Provide a default GL function resolver in the embedder #6523](https://github.com/flutter/engine/pull/6523/files) was to clear an error of this kind but I don't find any way to apply this in the engine compilation code.

**Comment by TahaTesser** [comment] 2020-04-28 10:40
Hi @limbouser 
can you please provide your `flutter doctor -v`  or  what version of the engine?

**Comment by limbouser** [comment] 2020-04-28 11:30
I'm actually trying to run   [flutter_wayland](https://github.com/chinmaygarde/flutter_wayland) by @chinmaygarde on Raspberry Pi. To meet some library dependencies, I'm using a flutter engine v1.9.1 that I compiled for ARM architecture. That's when this error came up when I tried running 
`flutter_wayland <path to asset>`

**Comment by chinmaygarde** [comment] 2020-04-28 20:15
The wayland embedder does indeed wire up the custom GL proc resolver. Are you finding that the [Error on line 75](https://github.com/chinmaygarde/flutter_wayland/blob/e48b11082ba73b424be0549995009e62020becb6/src/flutter_application.cc#L75) is displayed from the embedder? That could just mean that the embedder could not find an OpenGL implementation on the device.

**Comment by limbouser** [comment] 2020-04-29 12:23
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(107)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
ERROR: /usr/src/debug/flutter-wayland/1.0-r0/src/flutter_application.cc:75: Tried unsuccessfully to resolve: glGetString
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(41)] Check failed: gl_get_string. The GL proc resolver could not resolve glGetString
Aborted

In my case, this is how the error looks like.

**Comment by mogol** [comment] 2020-05-30 04:06
I bumped into the same issue when run [example glfw](https://github.com/flutter/engine/tree/master/examples/glfw) on Ubuntu.

I managed to bypass this by calling `glGetString` after [glfwMakeContextCurrent](https://github.com/flutter/engine/blob/master/examples/glfw/FlutterEmbedderGLFW.cc#L88). But it failed later on [GrGLInterface::validate()](https://skia.googlesource.com/skia/+/master/src/gpu/gl/GrGLInterfaceAutogen.cpp#209)

However, after adding `glewInit()`  after [glfwMakeContextCurrent](https://github.com/flutter/engine/blob/master/examples/glfw/FlutterEmbedderGLFW.cc#L88), I was able to launch demo app. Unlikely that valid solution :) 

Any clues what causes the problem?

**Comment by limbouser** [comment] 2020-06-01 09:18
Hello @mogol Can you please be a bit more specific about the methods you used to resolve the error? Did you make any changes to the flutter-engine source code?

**Comment by mogol** [comment] 2020-06-01 12:10
@limbouser I didn't change anything in the engine. I added [glew](http://glew.sourceforge.net) to glfw embedder and called `glewInit` [after context config](https://github.com/flutter/engine/blob/923687f0e7ff0cddcbd05c98fd3ca12db9c45ac8/examples/glfw/FlutterEmbedderGLFW.cc#L88)

```
  config.open_gl.make_current = [](void* userdata) -> bool {
    glfwMakeContextCurrent((GLFWwindow*)userdata);
    -> glewInit();
    return true;
  };

```

**Comment by limbouser** [comment] 2020-06-01 12:23
glGetString call is part of the engine, right? I'm new to all this and I don't really have a very big idea.

**Comment by mogol** [comment] 2020-06-01 12:27
It's OpenGL function [glGetString](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGetString.xml). The engine uses some wrapper on it and looks like in some cases there is no proper initialization or configuration for OpenGL. But I haven't found the root cause, so my solution is more like the workaround for the issue, rather than proper fix.

**Comment by mogol** [comment] 2020-06-01 12:33
> The wayland embedder does indeed wire up the custom GL proc resolver. Are you finding that the [Error on line 75](https://github.com/chinmaygarde/flutter_wayland/blob/e48b11082ba73b424be0549995009e62020becb6/src/flutter_application.cc#L75) is displayed from the embedder? That could just mean that the embedder could not find an OpenGL implementation on the device.

@chinmaygarde this check fails to me 
https://github.com/flutter/engine/blob/923687f0e7ff0cddcbd05c98fd3ca12db9c45ac8/shell/gpu/gpu_surface_gl_delegate.cc#L40

**Comment by TahaTesser** [comment] 2020-12-08 13:55
Hi @chinmaygarde 
Did you get your answer? Can you please steps to reproduce this issue?
Thank you

**Comment by pedromassangocode** [comment] 2020-12-30 11:39
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 11:39 UTC
Labels: engine, waiting for customer response
