### ISSUE TITLE
In ExpansionTile widget giving more than 10 widget as children, above the 10th child height of the child's widget got increased

### ISSUE THREAD

**Issue by Nandhini-Ravichandran** [flutter/flutter#53404] opened 2020-03-27 09:34 UTC
<img width="188" alt="Capture1" src="https://user-images.githubusercontent.com/56873926/77742759-fe98d900-703c-11ea-8ec9-1ddc195de128.PNG">

**Comment by VladyslavBondarenko** [comment] 2020-03-27 09:40
Hi @Nandhini-Ravichandran 
Post please a complete minimal code sample to reproduce the problem

**Comment by Nandhini-Ravichandran** [comment] 2020-03-27 11:05
@VladyslavBondarenko 
ExpansionTile(
      title:const Text('ExpandTile'),
      children: <Widget>[
        _widget('one',Colors.blue),
        _widget('two',Colors.red),
        _widget('three',Colors.grey),
        _widget('four',Colors.green),
        _widget('five',Colors.yellow),
        _widget('six',Colors.pink),
        _widget('seven',Colors.black),
        _widget('eight',Colors.orange),
        _widget('nine',Colors.purple),
        _widget('ten',Colors.teal),
        _widget('one',Colors.brown),
        _widget('two',Colors.white),
        _widget('three',Colors.cyan),
        _widget('four',Colors.lime),
        
      ],
   )
///////////////////////////////////////

 Widget _widget(String text, Color color){
    return Container(
      color: color,
      padding: const EdgeInsets.all(10),
    child: Text(text));
  }

**Comment by VladyslavBondarenko** [comment] 2020-03-27 12:45
<details>
 <summary>This is what I see</summary>

![image](https://user-images.githubusercontent.com/17024977/77757017-08b8d880-7039-11ea-9ec4-ee58a428a59d.png)

</details>

<details>
 <summary>with this code</summary>
 
```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: ExpansionTile(
          title:const Text('ExpandTile'),
          children: [
            _widget('one',Colors.blue),
            _widget('two',Colors.red),
            _widget('three',Colors.grey),
            _widget('four',Colors.green),
            _widget('five',Colors.yellow),
            _widget('six',Colors.pink),
            _widget('seven',Colors.black),
            _widget('eight',Colors.orange),
            _widget('nine',Colors.purple),
            _widget('ten',Colors.teal),
            _widget('one',Colors.brown),
            _widget('two',Colors.white),
            _widget('three',Colors.cyan),
            _widget('four',Colors.lime),

          ],
        ),
      ),
    );
  }

  Widget _widget(String text, Color color){
    return Container(
        color: color,
        padding: const EdgeInsets.all(10),
        child: Text(text));
  }
}
```

</details>

( with flutter v1.16.3-pre.56 and Android 10 emulator). The same in DartPad.

I can't reproduce. It may be an issue with code, not with flutter

**Comment by TahaTesser** [comment] 2020-04-17 11:17
Hi @Nandhini-Ravichandran 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-04-17 11:17 UTC
Labels: in triage, waiting for customer response
