### ISSUE TITLE
Websafe_svg widget problem

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#77568] opened 2021-03-08 07:38 UTC
Hi,
Websafe_svg widget. If I run the sample app in a mobile emulator or desktop windows it works perfectly, however if I run the app in web mode the icons are not shown, only a rectangle with an x inside is shown.

In debug console:
Exception caught by image resource service
Failed to decode image data.
Image source: data:image/svg+xml;base64,PHN2Z...................................

Flutter 2.1.0-11.0.pre.145 channel master
Dart 2.13.0

Apparently the latest version of Flutter web causes an error with svg. 

Regards,
Jose

**Comment by iapicca** [comment] 2021-03-08 10:51
@Josua2012 
[websafe_svg](https://pub.dev/packages/websafe_svg) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/peiffer-innovations/websafe_svg/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by Josua2012** [comment] 2021-03-08 11:51
Hi @iapicca,

**flutter doctor -v**

[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [VersiÃ³n 10.0.19042.844], locale es-ES)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\jamol\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\jamol\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [VersiÃ³n 10.0.19042.844]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!

------------------------------------------------------------------------

**flutter run -v**
[  +64 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +75 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] executing: [C:\src\flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +66 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +30 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +44 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +72 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +52 ms] executing: C:\Users\jamol\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +48 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +62 ms] Multiple devices found:
[  +28 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [VersiÃ³n 10.0.19042.844]
[        ] Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)  
[        ] [3]: Edge (edge)      
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+12945 ms] 3
[  +17 ms] Skipping pub get: version match.
[ +117 ms] Generating
C:\Dart\VisualStudioProjects\Flutter\prueba_websafe_1\prueba_websafe_1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +79 ms] Launching lib\main.dart on Edge in debug mode...
[ +103 ms] Updating assets
[ +134 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +2 ms] Waiting for connection from debug service on Edge...
[ +190 ms] <- reset
[   +4 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental      
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\jamol\AppData\Local\Temp\flutter_tools.4ee51edd\flutter_tool.d4bd0743\app.dill --libraries-spec
file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
C:\Dart\VisualStudioProjects\Flutter\prueba_websafe_1\prueba_websafe_1\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false       
--enable-asserts --track-widget-creation --filesystem-root C:\Users\jamol\AppData\Local\Temp\flutter_tools.4ee51edd\flutter_tools.4c9ae963
--filesystem-scheme org-dartlang-app --initialize-from-dill build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +15 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+12262 ms] Waiting for connection from debug service on Edge... (completed in 12,5s)
[   +1 ms] Synced 29.9MB.
[        ] <- accept
[        ] Caching compiled dill
[ +221 ms] Using Abriendo en sesión de explorador existente.

[+10637 ms] [CHROME]:[11436:45980:0308/124853.406:ERROR:token_service_table.cc(140)] Failed to decrypt token for service AccountId-0006BFFDB38BF21C
[   +7 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:62838/devtools/browser/c254c535-0e87-4022-af25-503e9daa7b20
[ +396 ms] DwdsInjector: Received request for entrypoint at http://localhost:62569/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[   +9 ms] MetadataProvider: Loaded debug metadata
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:62569/main_module.bootstrap.js
[+4098 ms] DevHandler: Debug service listening on ws://127.0.0.1:62916/ySBp47M9Yac=/ws

[  +12 ms] Debug service listening on ws://127.0.0.1:62916/ySBp47M9Yac=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+23206 ms] ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[   +2 ms] The following ImageCodecException was thrown resolving an image codec:
[        ] Failed to decode image data.
[        ] Image source:
[   +1 ms]
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBkPSJNNDM2IDE2MGM2LjYgMCAxMi01LjQgMTItMT
J2LTQwYzAtNi42LTUuNC0xMi0xMi0xMmgtMjBWNDhjMC0yNi41LTIxLjUtNDgtNDgtNDhINDhDMjEuNSAwIDAgMjEuNSAwIDQ4djQxNmMwIDI2LjUgMjEuNSA0OCA0OCA0OGgzMjBjMjYuNSAwIDQ4LTIxLj
UgNDgtNDh2LTQ4aDIwYzYuNiAwIDEyLTUuNCAxMi0xMnYtNDBjMC02LjYtNS40LTEyLTEyLTEyaC0yMHYtNjRoMjBjNi42IDAgMTItNS40IDEyLTEydi00MGMwLTYuNi01LjQtMTItMTItMTJoLTIwdi02NG
gyMHptLTY4IDMwNEg0OFY0OGgzMjB2NDE2ek0yMDggMjU2YzM1LjMgMCA2NC0yOC43IDY0LTY0cy0yOC43LTY0LTY0LTY0LTY0IDI4LjctNjQgNjQgMjguNyA2NCA2NCA2NHptLTg5LjYgMTI4aDE3OS4yYz
EyLjQgMCAyMi40LTguNiAyMi40LTE5LjJ2LTE5LjJjMC0zMS44LTMwLjEtNTcuNi02Ny4yLTU3LjYtMTAuOCAwLTE4LjcgOC00NC44IDgtMjYuOSAwLTMzLjQtOC00NC44LTgtMzcuMSAwLTY3LjIgMjUuOC           02Ny4yIDU3LjZ2MTkuMmMwIDEwLjYgMTAgMTkuMiAyMi40IDE5LjJ6Ii8+PC9zdmc+
[   +2 ms] When the exception was thrown, this was the stack:
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image.dart 102:7                     createDefault     
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart 141:41        new
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image.dart 92:3                      decodeFromBytes   
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image.dart 75:53                     <fn>
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall     
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37283:58                              <fn>
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1370:13                                              _rootRunUnary     
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1265:19                                              runUnary
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1170:7                                               runUnaryGuarded   
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1207:26                                              <fn>
[   +1 ms] Image provider:
[   +1 ms]
NetworkImage("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBkPSJNNDM2IDE2MGM2LjYgMC  

AxMi01LjQgMTItMTJ2LTQwYzAtNi42LTUuNC0xMi0xMi0xMmgtMjBWNDhjMC0yNi41LTIxLjUtNDgtNDgtNDhINDhDMjEuNSAwIDAgMjEuNSAwIDQ4djQxNmMwIDI2LjUgMjEuNSA0OCA0OCA0OGgzMjBj  

MjYuNSAwIDQ4LTIxLjUgNDgtNDh2LTQ4aDIwYzYuNiAwIDEyLTUuNCAxMi0xMnYtNDBjMC02LjYtNS40LTEyLTEyLTEyaC0yMHYtNjRoMjBjNi42IDAgMTItNS40IDEyLTEydi00MGMwLTYuNi01LjQtMT  

ItMTItMTJoLTIwdi02NGgyMHptLTY4IDMwNEg0OFY0OGgzMjB2NDE2ek0yMDggMjU2YzM1LjMgMCA2NC0yOC43IDY0LTY0cy0yOC43LTY0LTY0LTY0LTY0IDI4LjctNjQgNjQgMjguNyA2NCA2NCA2NHpt  

LTg5LjYgMTI4aDE3OS4yYzEyLjQgMCAyMi40LTguNiAyMi40LTE5LjJ2LTE5LjJjMC0zMS44LTMwLjEtNTcuNi02Ny4yLTU3LjYtMTAuOCAwLTE4LjcgOC00NC44IDgtMjYuOSAwLTMzLjQtOC00NC44LT  
             gtMzcuMSAwLTY3LjIgMjUuOC02Ny4yIDU3LjZ2MTkuMmMwIDEwLjYgMTAgMTkuMiAyMi40IDE5LjJ6Ii8+PC9zdmc+",
[   +2 ms]   scale: 1)
[        ] Image key:
[        ]
NetworkImage("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBkPSJNNDM2IDE2MGM2LjYgMC  

AxMi01LjQgMTItMTJ2LTQwYzAtNi42LTUuNC0xMi0xMi0xMmgtMjBWNDhjMC0yNi41LTIxLjUtNDgtNDgtNDhINDhDMjEuNSAwIDAgMjEuNSAwIDQ4djQxNmMwIDI2LjUgMjEuNSA0OCA0OCA0OGgzMjBj  

MjYuNSAwIDQ4LTIxLjUgNDgtNDh2LTQ4aDIwYzYuNiAwIDEyLTUuNCAxMi0xMnYtNDBjMC02LjYtNS40LTEyLTEyLTEyaC0yMHYtNjRoMjBjNi42IDAgMTItNS40IDEyLTEydi00MGMwLTYuNi01LjQtMT  

ItMTItMTJoLTIwdi02NGgyMHptLTY4IDMwNEg0OFY0OGgzMjB2NDE2ek0yMDggMjU2YzM1LjMgMCA2NC0yOC43IDY0LTY0cy0yOC43LTY0LTY0LTY0LTY0IDI4LjctNjQgNjQgMjguNyA2NCA2NCA2NHpt  

LTg5LjYgMTI4aDE3OS4yYzEyLjQgMCAyMi40LTguNiAyMi40LTE5LjJ2LTE5LjJjMC0zMS44LTMwLjEtNTcuNi02Ny4yLTU3LjYtMTAuOCAwLTE4LjcgOC00NC44IDgtMjYuOSAwLTMzLjQtOC00NC44LT  
             gtMzcuMSAwLTY3LjIgMjUuOC02Ny4yIDU3LjZ2MTkuMmMwIDEwLjYgMTAgMTkuMiAyMi40IDE5LjJ6Ii8+PC9zdmc+",
[   +2 ms]   scale: 1)
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +25 ms] Another exception was thrown: ImageCodecException: Failed to decode image data.
[   +1 ms] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[   +1 ms] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[   +1 ms] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[   +1 ms] Another exception was thrown: ImageCodecException: Failed to decode image data.
[   +1 ms] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.
[        ] Another exception was thrown: ImageCodecException: Failed to decode image data.

-------------------------------------------------------

https://github.com/peiffer-innovations/websafe_svg/tree/main/example

Thanks.

Regards,
Jose.

**Comment by pedromassangocode** [comment] 2021-03-08 11:53
Hi @Josua2012 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/peiffer-innovations/websafe_svg/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-08 11:53 UTC
Labels: in triage

**Comment by Josua2012** [comment] 2021-03-08 11:58
Hi @pedromassango,

Before Flutter v2 this plugin worked perfectly, so I suppose it is due to a problem with version 2 of Flutter. 

**pubspec.yaml**

name: prueba_websafe_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  websafe_svg: ^1.1.4+2  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/all.json
    - assets/svgs/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

Thanks.

Regards,
Jose

**Comment by iapicca** [comment] 2021-03-08 13:43
> Before Flutter v2 this plugin worked perfectly, so I suppose it is due to a problem with version 2 of Flutter.

or [websafe_svg](https://pub.dev/packages/websafe_svg) is has not been [migrated to null safety](https://dart.dev/null-safety/migration-guide) 

- no `null safety badge`
![image](https://user-images.githubusercontent.com/45637986/110328953-a926c380-8024-11eb-8aa6-37bf5502a839.png)

- with `null safety badge`
![image](https://user-images.githubusercontent.com/45637986/110329289-0cb0f100-8025-11eb-9c3c-ddc015b9bf29.png)

**Comment by Josua2012** [comment] 2021-03-08 13:49
@iapicca 
But if it is a problem related to the migration to null safety it should not work on Android or desktop windows either.

**Comment by Josua2012** [comment] 2021-03-29 08:43
@pedromassangocode
This seems like a problem from the latest version of flutter. 
using flutter run -d chrome --web-renderer html, it's displayed , ok
but using vscode debug model like this launch.json file config don't display svg:
"name": "Flutter",
"type": "dart",
"request": "launch",
"program": "lib/main.dart",
"args": ["--web-renderer html"]
https://github.com/peiffer-innovations/websafe_svg/issues/19

Regards,
Jose A.Molina
