### ISSUE TITLE
On Flutter for Web. When tested on safari. assets are requested again and again when scrolling up and down

### ISSUE THREAD

**Issue by onb3891** [flutter/flutter#76758] opened 2021-02-25 03:41 UTC
I have a column with 5 images. After rendering the page, If I scroll up and down on website. Same assets are downloaded again and again.

Issue seen with only Safari for MAC. Safari version "Version 14.0.3 (16610.4.3.1.4)"

To verify:
a. Open the website on Safari
b. Open Developer tools -> Network. 
c. Wait for all assets and scripts are downloaded.
d. Scroll Up and then slowly Scroll Down. Repeat this step
e. On Network, we can see image is downloaded again and again. In my real application this causes image placeholders to be empty.

Code:
```
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TestWidget(),
    );
  }
}

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
        child: Column(
      children: [
        Image.network(
            "https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145",
            height: 200,
            width: 250,
            fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
        Image.network(
            "https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145",
            height: 200,
            width: 250,
            fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
        Image.network(
            "https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145",
            height: 200,
            width: 250,
            fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
        Image.network(
            "https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145",
            height: 200,
            width: 250,
            fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
        Image.network(
            "https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145",
            height: 200,
            width: 250,
            fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
      ],
    ));
  }
}
`

Flutter doctor

`[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    • Flutter version 1.25.0-8.3.pre at /Users/Shared/flutterSDK/flutter
    • Framework revision 5d36f2e7f5 (6 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Shared/AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!`


```

**Comment by iapicca** [comment] 2021-02-25 05:50
@onb3891 
can you run `flutter upgrade -f`

**Comment by onb3891** [comment] 2021-02-25 06:08
Upgraded and seeing same above issue

`[✓] Flutter (Channel beta, 1.26.0-17.7.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    • Flutter version 1.26.0-17.7.pre at /Users/Shared/flutterSDK/flutter
    • Framework revision 68e7d2e301 (31 hours ago), 2021-02-23 15:30:39 -0800
    • Engine revision 4a466e17cb
    • Dart version 2.12.0 (build 2.12.0-259.15.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Shared/AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!`

**Comment by jonahwilliams** [comment] 2021-02-25 06:56
There are some devtools specific options which disable caching of images downloaded over the network (disable cache?). That can have the effect of forcing images to reload if they're in a lazy rendered container, flutter or not

**Comment by darshankawar** [comment] 2021-02-25 10:06
I was able to replicate this on latest master. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-9.0.pre.85, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-9.0.pre.85 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 71b2b4d6e0 (5 hours ago), 2021-02-25 00:01:01 -0500
    • Engine revision 867e51b762
    • Dart version 2.13.0 (build 2.13.0-73.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.


```

</details>

@jonahwilliams Should this be tracked under devtools then or not ? considering per your comment that this may not be specific to Flutter ?

**Comment by onb3891** [comment] 2021-02-25 11:03
Few more observation. If I change the image url then issue is not seen. Compared to above code here I am using a different random Image URL

`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TestWidget(),
    );
  }
}

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
        child: Column(
      children: [
        Image.network("https://i.imgur.com/dDfxzKa.jpg",
            height: 200, width: 250, fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
        Image.network("https://i.imgur.com/dDfxzKa.jpg",
            height: 200, width: 250, fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
        Image.network("https://i.imgur.com/dDfxzKa.jpg",
            height: 200, width: 250, fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
        Image.network("https://i.imgur.com/dDfxzKa.jpg",
            height: 200, width: 250, fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
        Image.network("https://i.imgur.com/dDfxzKa.jpg",
            height: 200, width: 250, fit: BoxFit.contain),
        Container(
          color: Colors.black,
          width: 250,
          height: 3,
        ),
      ],
    ));
  }
}
`

**Comment by darshankawar** [comment] 2021-02-25 12:44
@onb3891 
Could this be happening due to the source of images you were loading from earlier, ie, firebase storage ? and not with regular images ?

**Comment by onb3891** [comment] 2021-02-25 13:35
@darshankawar No. If I have public firebase storage image for ex: https://storage.googleapis.com/openimages/web/images/c159532248cb84da.png

issue is not seen. (Picked a random firebase image without any token)

**Comment by darshankawar** [comment] 2021-02-25 13:47
@onb3891 So it seems to be image specific, and maybe used in your project to be precise ?

**Comment by onb3891** [comment] 2021-02-25 13:56
@darshankawar 

I deployed a simple website with following code

`<!DOCTYPE html>
<html>
<body>

<h2>HTML Image</h2>
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">

</body>
</html>

`

It runs without reloading. With same images as above.
PS: Not an expert on HTML and JS

**Comment by onb3891** [comment] 2021-02-25 14:01
@darshankawar 

I deployed a simple website with following code

```<!DOCTYPE html>
<html>
<body>

<h2>HTML Image</h2>
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">
<img src="https://firebasestorage.googleapis.com/v0/b/sih2020-cad27.appspot.com/o/pic1.jpg?alt=media&token=267a9d96-b7cc-43b5-b504-1717330de145" alt="Trulli" width="500" height="333">

</body>
</html>

```

It runs without reloading. With same images as above.
PS: Not an expert on HTML and JS

**Comment by darshankawar** [comment] 2021-02-26 07:14
Keeping this issue open for further investigation.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-9.0.pre.106, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-9.0.pre.106 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1610a27476 (3 hours ago), 2021-02-25 20:26:02 -0800
    • Engine revision 1515b1d4a4
    • Dart version 2.13.0 (build 2.13.0-79.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

**Comment by jonahwilliams** [comment] 2021-02-26 15:47
This is not a bug, this is the intended functionality of the chrome devtools disable caching functionality. The reason the static html does not display this is because it has no "virtualization" (i.e. the elements are not removed when scrolled off screen).

**Comment by onb3891** [comment] 2021-02-27 05:33
@jonahwilliams I am seeing this on release deployed website

**Comment by hterkelsen** [comment] 2021-03-05 21:01
From what I can tell, the difference between the images which are repeatedly requested and the images which aren't is the cache headers. Pay attention to the `Cache-Control` headers:

firebase image with token:
<img width="315" alt="Screen Shot 2021-03-05 at 12 48 28 PM" src="https://user-images.githubusercontent.com/1961493/110172476-10890d00-7db2-11eb-8bcf-435c8ff4a62a.png">

imgur image:
<img width="297" alt="Screen Shot 2021-03-05 at 12 50 07 PM" src="https://user-images.githubusercontent.com/1961493/110172578-31516280-7db2-11eb-8732-ae4e335267e4.png">

public firebase image:
<img width="313" alt="Screen Shot 2021-03-05 at 12 52 58 PM" src="https://user-images.githubusercontent.com/1961493/110172641-4af2aa00-7db2-11eb-9320-b98ab48926c1.png">


I think this would work if you change the cache settings in your firebase settings, but I don't have enough experience with Firebase to know how to do that. The reason you don't see the same thing in the version of the app with 6 img tags is that those DOM elements are persisted even after they scroll off screen. In Flutter, things which aren't currently on screen may or may not be persisted, so when they scroll back into view we may need to kick off a new request, and if the cache headers say the image needs to be redownloaded, it looks like Safari will try to do that.

Closing this issue since it seems like an image hosting issue and not an issue with Flutter.

**Closed by hterkelsen** 2021-03-05 21:01 UTC
Labels: a: assets, a: images, assigned for triage, browser: safari, d: devtools, f: scrolling, found in release: 1.27, framework, has reproducible steps, platform-web

**Comment by onb3891** [comment] 2021-03-06 07:14
@hterkelsen Surprisingly this behavior is seen only with Safari, not with Chrome or Firefox 🤔
