### ISSUE TITLE
`NeverScrollableScrollPhysics()` doesn't work as intended when wrapped inside a `SelectionArea`.

### ISSUE THREAD

**Issue by ZiyadF296** [flutter/flutter#143650] opened 2024-02-17 18:44 UTC
### Steps to reproduce

1. Wrap a widget such as `PageView` with `SelectionArea`.
2. Set `physics` property to `const NeverScrollableScrollPhysics(),`. 

### Expected results

To not be able to navigate to any other page by interaction if physics is set to be never scrollable.

### Actual results

When selecting any selectable text inside the widget with the physics property, and pushing the highlighted text to the right side of the `PageView`, you can push the page to the next child or the left side to the previous child. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: SizedBox(
          width: MediaQuery.of(context).size.width / 2,
          height: MediaQuery.of(context).size.height / 2,
          child: ColoredBox(
            color: Theme.of(context).colorScheme.primaryContainer,
            child: SelectionArea(
              child: PageView(
                physics: const NeverScrollableScrollPhysics(),
                children: const [
                  Text('This is the text for page 1'),
                  Text('This is the text for page 2'),
                  Text('This is the text for page 3'),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/56755783/9748be3e-2c57-48f7-8fb3-7fd5578abaf5

</details>

### Logs

<details open><summary>Logs</summary>

```console
N/A
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22635.3209], locale en-US)
    • Flutter version 3.19.0 on channel stable at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (4 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ziyad\AppData\Local\Android\sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: C:\Users\ziyad\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34525.116
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Users\ziyad\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Users\ziyad\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] VS Code (version 1.86.2)
    • VS Code at C:\Users\ziyad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[✓] VS Code (version 1.87.0-insider)
    • VS Code at C:\Users\ziyad\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22635.3209]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.128

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2024-02-19 07:46
Thanks for filing this @ZiyadF296.
I can reproduce on the latest `master` and `stable` channels but there is a similar issue currently being tracked https://github.com/flutter/flutter/issues/128935. 
Kindly upvote, comment and follow up on that issue for updates.
Closing this as a duplicate of the already existing issue, if you disagree please comment and I'll reopen this.
Thank you!

**Closed by dam-ease** 2024-02-19 07:46 UTC
Labels: in triage
