### ISSUE TITLE
Multi audio support to video within file are external audio sources

### ISSUE THREAD

**Issue by dineshnaikb** [flutter/flutter#156557] opened 2024-10-11 02:10 UTC
### Use case

User can able to play different type of audio like language changes of a particular video. Example Hindi, English, Telugu, Tamil, etc
And the possible stream source of audio can able to fetch from a video Or can able to fetch from external source like url file or network data It will help to experience a single video in multi language or multi audio for creating memes movies and shows

### Proposal

The package multi audio source for a single video that can enhance the user experience and more interactive for any application And wide range of accessibility for a customer satisfaction So I request to enhance this particular package for supporting multiple audio streams.

**Comment by darshankawar** [comment] 2024-10-11 07:44
Closing as duplicate of https://github.com/flutter/flutter/issues/59437

**Closed by darshankawar** 2024-10-11 07:44 UTC
Labels: in triage
