### ISSUE TITLE
Problem using Slider on AlertDialog

### ISSUE THREAD

**Issue by hjJunior** [flutter/flutter#19323] opened 2018-07-12 21:50 UTC
I doing a AlertDialog, so when I tried to insert Slider widget inside the state of value sound realy stranger, and this doesn't happens if Slider is outside of AlertDialog

```dart
    new Slider(
      onChanged: (double value) {
        setState(() {
          sliderValue = value;
        });
      },
      label: 'Oi',
      divisions: 10,
      min: 0.0,
      max: 10.0,
      value: sliderValue,
    )
```

The complete widget code of AlertDialog

```dart
    Future<Null> _showDialog() async {
      await showDialog<Null>(
          context: context,
          builder: (BuildContext context) {
            return new AlertDialog(
              title: const Text('Criar novo cartão'),
              actions: <Widget>[
                new FlatButton(onPressed: () {
                  Navigator.of(context).pop(null);
                }, child: new Text('Hello'))
              ],
              content: new Container(
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    new Text('Deseja iniciar um novo cartão com quantos pedidos ja marcados?'),
                    new Slider(
                  onChanged: (double value) {
                    setState(() {
                      sliderValue = value;
                    });
                  },
                  label: 'Oi',
                  divisions: 10,
                  min: 0.0,
                  max: 10.0,
                  value: sliderValue,
                )
                  ],
                ),
              ),
            );
          }
      );
    }
```

and everything is under State class of StatefullWidget.

Its look like doesn't update the value and when try to change the value keep in same position.

### Update 1

The problem is there are 2 required parameters in Slider `(onChanged, value)`, So I should update this or UI keep quite, see the video how the application is running

[Video on Youtube][1]

  [1]: https://youtu.be/nyLmhDvqJ4U

**Comment by zoechi** [comment] 2018-07-13 08:42
Please add the output of `flutter doctor`.

**Comment by zoechi** [comment] 2018-07-13 09:33
This Flutter version is quite outdated. Can you please try if you can reproduce with a recent version?
`beta` or better `dev` channel, because the latest `beta` is also already a bit dated.

**Comment by zoechi** [comment] 2018-07-13 10:34
The issue is the same, right?

**Comment by hjJunior** [comment] 2018-07-13 10:36
Yep :(

**Comment by zoechi** [comment] 2018-07-13 10:40
There is already an answer on https://stackoverflow.com/questions/51271061/flutter-why-slider-doesnt-update-in-alertdialog so I'm going to close this issue.

**Closed by zoechi** 2018-07-13 10:40 UTC
Labels: f: material design, framework

**Comment by hjJunior** [comment] 2018-07-13 10:43
@zoechi  This answer it was opened about me in StackOverflow

**Comment by zoechi** [comment] 2018-07-13 10:58
I know. I'm quite positive the answer you get there is a good one.

**Comment by zoechi** [comment] 2018-07-13 12:02
I think it's rather because the slider is build by a function, not by a widget. 
See also this discussion #19269
