### ISSUE TITLE
Requesting to add support for picking multiple images

### ISSUE THREAD

**Issue by aritradgupta** [flutter/flutter#17591] opened 2018-05-14 23:47 UTC
Please add support for selecting multiple images at once using the image_picker plugin.

**Comment by d-silveira** [comment] 2018-06-26 18:58
duplicate of https://github.com/flutter/flutter/issues/16054

**Comment by zoechi** [comment] 2018-06-26 20:15
Closing as dup - thanks @d-silveira for spotting.

**Closed by zoechi** 2018-06-26 20:15 UTC
