### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by jaca420** [flutter/flutter#141433] opened 2024-01-12 02:59 UTC
## Command
```
flutter run
```

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2499:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2470:14)
#3      VmService.callMethod (package:vm_service/src/vm_service.dart:2452:12)
#4      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:501:28)
#5      FlutterVmService.renderFrameWithRasterStats (package:flutter_tools/src/vmservice.dart:601:49)
#6      ResidentHandlers.debugFrameJankMetrics (package:flutter_tools/src/resident_runner.dart:727:35)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1830:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.5, on macOS 13.5.2 22G91 darwin-x64, locale en-RO)
    [32m•[39m Flutter version 3.16.5 on channel stable at /Users/this-cpu/Documents/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    [32m•[39m Engine revision 3f3e560236
    [32m•[39m Dart version 3.2.3
    [32m•[39m DevTools version 2.28.4

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [32m•[39m Android SDK at /Users/this-cpu/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 30.0.3
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 13.0.2+8)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14C18
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Mihai’s iPhone (mobile) • 00008101-000939581E91001E • ios            • iOS 15.4.1 19E258
    [32m•[39m macOS (desktop)         • macos                     • darwin-x64     • macOS 13.5.2 22G91 darwin-x64
    [32m•[39m Chrome (web)            • chrome                    • web-javascript • Google Chrome 120.0.6099.216
    [33m![39m Error: Mihai’s iPhone is busy: Fetching debug symbols for Mihai’s iPhone. Xcode will continue when Mihai’s iPhone is finished. (code -10)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 2.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-4.9.1
cloud_firestore_web-3.7.0
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+2
file_selector_windows-0.9.3+1
firebase_auth-4.9.0
firebase_auth_web-5.8.0
firebase_core-2.15.1
firebase_core_web-2.7.0
firebase_storage-11.2.6
firebase_storage_web-3.6.6
flutter_plugin_android_lifecycle-2.0.16
image_picker-1.0.4
image_picker_android-0.8.8
image_picker_for_web-3.0.1
image_picker_ios-0.8.8+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.1
path_provider_android-2.2.2
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
sqflite-2.3.0
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.20
url_launcher_windows-3.0.8

**Comment by darshankawar** [comment] 2024-01-12 08:56
There are couple of open issues showing same error log, but the command and replication steps are different.
I'll label this for team's tracking and input and if this needs to be tracked separately or clubbed with existing issues.

**Comment by christopherfujino** [comment] 2024-02-08 20:58
Closing this as a duplicate of: https://github.com/flutter/flutter/issues/143010

**Closed by christopherfujino** 2024-02-08 20:58 UTC
Labels: c: crash, tool, team-tool
