### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by Qing1234567** [flutter/flutter#104136] opened 2022-05-19 02:39 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#6      VsCode._getVersionFromPackageJson (package:flutter_tools/src/vscode/vscode.dart:293:64)
#7      new VsCode.fromDirectory (package:flutter_tools/src/vscode/vscode.dart:69:35)
#8      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:273:28)
#9      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:237:12)
#10     VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:98:14)
#11     VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:21:10)
#12     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:91:26)
#13     Doctor.validators (package:flutter_tools/src/doctor.dart:195:47)
#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:201:45)
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:339:72)
#16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1342:12)
<asynchronous suspension>
#18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
```
```
encountered exception: FileSystemException: Failed to decode data using encoding 'utf-8', path = 'C:\Users\logxo\AppData\Local\Programs\Microsoft VS Code\resources\app\package.json'

#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#6      VsCode._getVersionFromPackageJson (package:flutter_tools/src/vscode/vscode.dart:293:64)
#7      new VsCode.fromDirectory (package:flutter_tools/src/vscode/vscode.dart:69:35)
#8      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:273:28)
#9      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:237:12)
#10     VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:98:14)
#11     VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:21:10)
#12     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:91:26)
#13     Doctor.validators (package:flutter_tools/src/doctor.dart:195:47)
#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:201:45)
#15     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:610:60)
#16     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
#17     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:614:71)
#18     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart:607:47)
#19     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart)
#20     CrashReporter.informUser (package:flutter_tools/src/reporting/crash_reporting.dart:92:32)
#21     _handleToolError (package:flutter_tools/runner.dart:166:35)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment] 2022-05-19 08:06
Closing as duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by darshankawar** 2022-05-19 08:06 UTC
Labels: in triage
