### ISSUE TITLE
The engine notify twice for the same value when use numeric keyboard input

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#65811] opened 2020-09-15 03:10 UTC
@justinmc Hi,
This is the track for https://github.com/flutter/flutter/pull/65754#discussion_r488103285
## Step to reproduce
There are some differences between the real device and the simulator, but both of them will repeatedly notify the same value.
### Real device, OPPO, Reno3, Sogou input.
1, Run the app, focus the textField, switch to numeric keyboard, input any number will trigger.
```
I/flutter (30312): updateEditingValue [TextEditingValue(text: ┤I love flutter!1├, selection: TextSelection(baseOffset: 16, extentOffset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))]
I/flutter (30312): Second text field: I love flutter!1
I/flutter (30312): updateEditingValue [TextEditingValue(text: ┤I love flutter!1├, selection: TextSelection(baseOffset: 16, extentOffset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))]
I/flutter (30312): updateEditingValue [TextEditingValue(text: ┤I love flutter!12├, selection: TextSelection(baseOffset: 17, extentOffset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))]
I/flutter (30312): Second text field: I love flutter!12
I/flutter (30312): updateEditingValue [TextEditingValue(text: ┤I love flutter!12├, selection: TextSelection(baseOffset: 17, extentOffset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))]
```
### Simulator, Chinese language.
1, Run the app, clean the textField, switch to numeric keyboard, input one number
2, Delete the number will trigger the issue
![20200915_110514](https://user-images.githubusercontent.com/61075224/93160718-838ac280-f743-11ea-8f50-447be5ce0558.gif)

```
I/flutter (17052): updateEditingValue [TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))]
I/flutter (17052): Second text field: 
I/flutter (17052): updateEditingValue [TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))]
```
## Sample Code
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Retrieve Text Input',
      home: MyCustomForm(),
    );
  }
}

// Define a custom Form widget.
class MyCustomForm extends StatefulWidget {
  @override
  _MyCustomFormState createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds data related to the Form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller and use it to retrieve the current value
  // of the TextField.
  final myController = TextEditingController(text: 'I love flutter!');
  final newController = TextEditingController(text: 'I am a new controller.');
  TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = myController;

    _controller.addListener(_printLatestValue);
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is removed from the widget tree.
    // This also removes the _printLatestValue listener.
    myController.dispose();
    newController.dispose();
    super.dispose();
  }

  _printLatestValue() {
    print("Second text field: ${myController.text}");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Retrieve Text Input'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: <Widget>[
//            TextField(
//              onChanged: (text) {
//                print("First text field: $text");
//              },
//            ),
            TextField(
              controller: _controller,
              keyboardType: TextInputType.multiline,
              maxLines: 7,
//              inputFormatters: [LengthLimitingTextInputFormatter(3)],
            ),
            MaterialButton(
                child: Text("set to '123'"),
                onPressed: () {
                  setState(() {
                    _controller.value = TextEditingValue(
                        text: '123',
                        composing:TextRange(start: -1, end: -1),
                        selection: TextSelection(
                            baseOffset: 3,
                            extentOffset: 3,
                            affinity: TextAffinity.downstream,
                            isDirectional: false));
                  });
                }),
            MaterialButton(
                child: Text("set to '12'"),
                onPressed: () {
                  setState(() {
                    _controller.text = '12';
                  });
                }),
            MaterialButton(
                child: Text('change controller'),
                onPressed: () {
                  setState(() {
                    _controller = newController;
                  });
                }),
          ],
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment] 2020-09-15 09:27
Hi @xu-baolin 
I am unable to print `updateEditingValue`  using your code sample, does this require more than just your code sample?

**Comment by xu-baolin** [comment] 2020-09-15 11:53
you should add log in function 'updateEditingValue'.

**Comment by TahaTesser** [comment] 2020-09-15 13:35
```
I/flutter ( 4438): TextEditingValue(text: ┤I love flutter!23├, selection: TextSelection(baseOffset: 17, extentOffset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I/flutter ( 4438): Second text field: I love flutter!23
I/flutter ( 4438): TextEditingValue(text: ┤I love flutter!23├, selection: TextSelection(baseOffset: 17, extentOffset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
```

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Retrieve Text Input',
      home: MyCustomForm(),
    );
  }
}

// Define a custom Form widget.
class MyCustomForm extends StatefulWidget {
  @override
  _MyCustomFormState createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds data related to the Form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller and use it to retrieve the current value
  // of the TextField.
  final myController = TextEditingController(text: 'I love flutter!');
  final newController = TextEditingController(text: 'I am a new controller.');
  TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = myController;

    _controller.addListener(_printLatestValue);
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is removed from the widget tree.
    // This also removes the _printLatestValue listener.
    myController.dispose();
    newController.dispose();
    super.dispose();
  }

  _printLatestValue() {
    print("Second text field: ${myController.text}");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Retrieve Text Input'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: <Widget>[
//            TextField(
//              onChanged: (text) {
//                print("First text field: $text");
//              },
//            ),
            TextField(
              controller: _controller,
              keyboardType: TextInputType.multiline,
              maxLines: 7,
//              inputFormatters: [LengthLimitingTextInputFormatter(3)],
            ),
            MaterialButton(
                child: Text("set to '123'"),
                onPressed: () {
                  setState(() {
                    _controller.value = TextEditingValue(
                        text: '123',
                        composing: TextRange(start: -1, end: -1),
                        selection: TextSelection(
                            baseOffset: 3,
                            extentOffset: 3,
                            affinity: TextAffinity.downstream,
                            isDirectional: false));
                  });
                }),
            MaterialButton(
                child: Text("set to '12'"),
                onPressed: () {
                  setState(() {
                    _controller.text = '12';
                  });
                }),
            MaterialButton(
                child: Text('change controller'),
                onPressed: () {
                  setState(() {
                    _controller = newController;
                  });
                }),
          ],
        ),
      ),
    );
  }
}


```

</details> 
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.176, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.176 at /Users/tahatesser/Code/flutter_master
    • Framework revision 96ca0e272b (3 hours ago), 2020-09-15 09:02:04 +0100
    • Engine revision 7e962ba911
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2023-01-10 04:06
Hi @xu-baolin, I verified the issue on stable and the master channel with Pinyin input on Xiaomi Redmi k20 pro with Gboard and I am unable to reproduce the issue. I believe this issue is fixed. 


https://user-images.githubusercontent.com/31410839/211459498-ceada7be-4f11-4077-aaf7-662902ebbd97.mov

 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Retrieve Text Input',
      home: MyCustomForm(),
    );
  }
}

// Define a custom Form widget.
class MyCustomForm extends StatefulWidget {
  const MyCustomForm({super.key});

  @override
  _MyCustomFormState createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds data related to the Form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller and use it to retrieve the current value
  // of the TextField.
  final myController = TextEditingController(text: 'I love flutter!');
  final newController = TextEditingController(text: 'I am a new controller.');
  late TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = myController;

    _controller.addListener(_printLatestValue);
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is removed from the widget tree.
    // This also removes the _printLatestValue listener.
    myController.dispose();
    newController.dispose();
    super.dispose();
  }

  _printLatestValue() {
    print("Second text field: ${myController.text}");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Retrieve Text Input'),
      ),
      body: GestureDetector(
        onTap: () => FocusScope.of(context).unfocus(),
        child: Column(
          children: <Widget>[
//            TextField(
//              onChanged: (text) {
//                print("First text field: $text");
//              },
//            ),
            TextField(
              controller: _controller,
              keyboardType: TextInputType.multiline,
              maxLines: 7,
//              inputFormatters: [LengthLimitingTextInputFormatter(3)],
            ),
            MaterialButton(
                child: const Text("set to '123'"),
                onPressed: () {
                  setState(() {
                    _controller.value = const TextEditingValue(
                        text: '123',
                        composing: TextRange(start: -1, end: -1),
                        selection: TextSelection(
                            baseOffset: 3,
                            extentOffset: 3,
                            affinity: TextAffinity.downstream,
                            isDirectional: false));
                  });
                }),
            MaterialButton(
                child: const Text("set to '12'"),
                onPressed: () {
                  setState(() {
                    _controller.text = '12';
                  });
                }),
            MaterialButton(
                child: const Text('change controller'),
                onPressed: () {
                  setState(() {
                    _controller = newController;
                  });
                }),
          ],
        ),
      ),
    );
  }
}

```
</details> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed. Incase you still encounter the issue then please feel free to write in the comments and we will reopen it.

**Closed by maheshmnj** 2023-01-10 04:06 UTC
Labels: a: text input, framework, engine, has reproducible steps, P4, found in release: 1.22
