### ISSUE TITLE
TextStyle copyWith doesn't work as expected

### ISSUE THREAD

**Issue by predatorx7** [flutter/flutter#75897] opened 2021-02-12 05:07 UTC
**Describe the bug**
On using `.copyWith` in a TextStyle, the font-weight reduces. When I use copyWith, I expect it to copy properties I defined in the arguments with properties in the TextStyle instance. However, this is not happening. This fixes when I pass a font family in `copyWith` arguments but the same can't be done in some cases, for example: When using packages like GoogleFonts.

**One way to reproduce**
1. Create an instance of any GoogleFont i.e `final myStyle = GoogleFonts.raleway( ... )`
2. use `myStyle` as textstyle for a text and it'll look the way you expect.
3. Now use copyWith on `myStyle` i.e `myStyle.copyWith(fontWeight: FontWeight.w800,)`
4. Instead of heavier weight like FontWeight.w800, text will appear like FontWeight.normal

**Expected behavior**
I want GoogleFont textStyle with custom styles by using `copyWith` method.

**Include the contents of your `google_fonts` directory**
google_fonts/OFL.txt
google_fonts/Raleway-Black.ttf
google_fonts/Raleway-BlackItalic.ttf
google_fonts/Raleway-Bold.ttf
google_fonts/Raleway-BoldItalic.ttf
google_fonts/Raleway-ExtraBold.ttf
google_fonts/Raleway-ExtraBoldItalic.ttf
google_fonts/Raleway-ExtraLight.ttf
google_fonts/Raleway-ExtraLightItalic.ttf
google_fonts/Raleway-Italic.ttf
google_fonts/Raleway-Light.ttf
google_fonts/Raleway-LightItalic.ttf
google_fonts/Raleway-Medium.ttf
google_fonts/Raleway-MediumItalic.ttf
google_fonts/Raleway-Regular.ttf
google_fonts/Raleway-SemiBold.ttf
google_fonts/Raleway-SemiBoldItalic.ttf
google_fonts/Raleway-Thin.ttf
google_fonts/Raleway-ThinItalic.ttf

**Screenshots**
![flutter_01](https://user-images.githubusercontent.com/33719927/107084180-b92c6700-681c-11eb-811d-311699616d15.png)
for code
```
RichText(
        text: TextSpan(
          text: 'AAVEKH',
          style: GoogleFonts.raleway(
            fontWeight: FontWeight.w800,
            fontSize: 24,
            color: Colors.white,
          ),
        ),
      )
```
*and*

![flutter_02](https://user-images.githubusercontent.com/33719927/107084419-090b2e00-681d-11eb-9516-75f0ecf62e56.png)
for code
```
RichText(
        text: TextSpan(
          text: 'AAVEKH',
          style: GoogleFonts.raleway().copyWith(
            fontWeight: FontWeight.w800,
            fontSize: 24,
            color: Colors.white,
          ),
        ),
      )
```

**Smartphone (please complete the following information if applicable):**
 - Device: Samsung M31
 - OS: Android 11

**futter doctor -v**
```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_IN.UTF-8)
    • Flutter version 1.22.6 at /home/red/devel/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/red/devel/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/red/devel/android-sdk
    • Java binary at: /usr/lib/jvm/java-11/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /snap/bin/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = /snap/bin/android-studio
    ✗ Android Studio not found at /snap/bin/android-studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.53.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available
```

**Comment by pedromassangocode** [comment] 2021-02-12 08:30
Hi @predatorx7 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/material-foundation/google-fonts-flutter).
Closing, as this isn't an issue with Flutter itself.  

I see you already opened an issue there https://github.com/material-foundation/google-fonts-flutter/issues/141.

If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-12 08:30 UTC

**Comment by luffynas** [comment] 2021-06-13 07:37
Same with me, where TextStyle ..copyWith() not working on flutter :

Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (2 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**pubspec.yml**
fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic

class AppStyle {
  static const standart = TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: AppColors.textPrimary,
    fontFamily: 'Roboto',
  );
}

How Access?
Text(
            interst.name,
            style: AppStyle.medium
              ..copyWith(
                color: selected ? Colors.white : Color(0xFF0960ac),
              ),
          ),

Note:
- No use 3rd library
