### ISSUE TITLE
Too big size for empty APK (engine disk footprint size)

### ISSUE THREAD

**Issue by hooramin** [flutter/flutter#12456] opened 2017-10-08 18:35 UTC
Hey there
I ran flutter create project and release the Android-release apk. 
the size of app apk was about 7 mb !!!!!!!

it's really big size for an empty application!

**Comment by Hixie** [comment] 2017-10-09 00:45
What is your target size?

**Comment by hooramin** [comment] 2017-10-09 00:54
I was "vb" programmer before and now i'm about switching to another language that i found Flutter so intersting.
but after my first build in compare b4a apk(s) it's so heavy .
There i could get 1mb at maximum size on a light apk file like this one.

**Comment by Hixie** [comment] 2017-10-09 01:01
Not sure we'll ever be able to get down to 1MB but I do agree that we will need to get smaller!

**Comment by sethladd** [comment] 2017-10-09 20:30
Thanks for the feedback! We explain a bit of where the size comes from here: https://flutter.io/faq/#how-big-is-the-flutter-engine

**Comment by MrIceman** [comment] 2018-02-07 22:08
I created a simple app with sqlite and sharedprefs and I am at 100 mb already..

**Comment by Hixie** [comment] 2018-02-08 04:47
That seems significantly larger than we can expect, beyond the issue described in this bug. Can you file a separate bug for that and list the contents of the 100MB APK with sizes so we can see the cause? Thanks.

**Comment by Hixie** [comment] 2018-05-03 19:34
Closing in favour of https://github.com/flutter/flutter/issues/16833 which has more concrete data

**Closed by Hixie** 2018-05-03 19:34 UTC
Labels: engine, severe: performance

**Comment by adaamohi** [comment] 2018-10-30 08:05
i have simple app 3 page with button(next/back) for move to another page and back size is 101mb

**Comment by zoechi** [comment] 2018-10-30 08:17
@adaamohi that's only for debug builds. If you want to evaluate size, create a release build `flutter build apk --release`

**Comment by adaamohi** [comment] 2018-10-30 08:49
> @adaamohi that's only for debug builds. If you want to evaluate size, create a release build `flutter build apk --release`
thank you so much sorry im jjust new :)

**Comment by AhmadullahSaikat** [comment] 2019-09-29 14:21
I'm an Android Developer. I'm a little bit greedy developer. So I'm learning to develop Android & IOS apps within Flutter. But the APK size frustrated me.
Now I understand that, "Kill the goose that lays golden eggs".

**Comment by siddastic** [comment] 2020-09-20 05:56
@adaamohi Debug apps are container for your dart code
They are usually big since they contain everything you might need during a hot restart or restart which prevents building whole system again when you made just a small change in you code
Release builds are real result of all your code and they are real minified apps without any containers which then you can distribute on stores
I'm not a good explainer but I hope you got it😅

**Comment by thamarakshan-pilla** [comment] 2021-07-01 15:05
@adaamohi I would also like to add that `flutter build apk --release` creates a fat APK that contains the code for all the target ABIs. Individual platform specific release APKs are much smaller. Try this : `flutter build apk --split-per-abi` to multiple release APKs for the target ABIs. Hope this info helps you :)
