### ISSUE TITLE
How to set cookies, please help

### ISSUE THREAD

**Issue by bingzhao0719** [flutter/flutter#42611] opened 2019-10-13 13:17 UTC
In projects, it is often necessary to open an H5 page in app that needs to be logged in. The login information is brought to the H5 page through cookie. How do I set cookies? I read about cookie issues, such as #27597、#1179. It mentions that cookies can be set through the addCookie method of cookiemanager, but I did not find the addCookie method in webview_flutter: 0.3.14. What should I do? Please help me.

**Comment by janmoppel** [comment] 2019-10-14 09:21
Hello @bingzhao0719 !

Thank you for posting.
Can you please clarify, do you want to set cookies using `webview_flutter` specifically?

**Comment by wbingz0719** [comment] 2019-10-16 09:59
@janmoppel Yes, in the project, webview_flutter is widely used to load H5 pages, but there are many H5 pages that need to pass some login information to display different UI and different operations. These login information is passed to H5 through cookies. If I can't pass the information to H5 through cookies, the company's project can't go on. Please help me, it's urgent.

**Comment by bingzhao0719** [comment] 2019-10-16 11:52
@janmoppel Yes, in the project, webview_flutter is used to load H5 pages, but there are many H5 pages that need to pass some login information to display different UI and different operations. These login information is passed to H5 through cookies. If I can't pass the information to H5 through cookies, the company's project can't go on. Please help me, it's urgent.

**Comment by YunyunZhai** [comment] 2019-10-19 02:09
> @janmoppel Yes, in the project, webview_flutter is used to load H5 pages, but there are many H5 pages that need to pass some login information to display different UI and different operations. These login information is passed to H5 through cookies. If I can't pass the information to H5 through cookies, the company's project can't go on. Please help me, it's urgent.

i have add the add cookie code in my project

**Comment by bingzhao0719** [comment] 2019-10-19 09:43
> > @janmoppel Yes, in the project, webview_flutter is used to load H5 pages, but there are many H5 pages that need to pass some login information to display different UI and different operations. These login information is passed to H5 through cookies. If I can't pass the information to H5 through cookies, the company's project can't go on. Please help me, it's urgent.
> 
> i have add the add cookie code in my project

How do you set cookies？

**Comment by wbingz0719** [comment] 2019-10-21 06:36
> > @janmoppel Yes, in the project, webview_flutter is used to load H5 pages, but there are many H5 pages that need to pass some login information to display different UI and different operations. These login information is passed to H5 through cookies. If I can't pass the information to H5 through cookies, the company's project can't go on. Please help me, it's urgent.
> 
> i have add the add cookie code in my project

Can you share your way of setting cookies please？

**Comment by YunyunZhai** [comment] 2019-10-21 09:26
> > > @janmoppel Yes, in the project, webview_flutter is used to load H5 pages, but there are many H5 pages that need to pass some login information to display different UI and different operations. These login information is passed to H5 through cookies. If I can't pass the information to H5 through cookies, the company's project can't go on. Please help me, it's urgent.
> > 
> > 
> > i have add the add cookie code in my project
> 
> Can you share your way of setting cookies please？

模仿其他方法就可以了

**Comment by wbingz0719** [comment] 2019-10-21 09:35
> webview中添加
> private void addCookie(MethodCall methodCall, final Result result) {
> Map<String, String> args = (Map<String, String>) methodCall.arguments;
> String domain = args.get("domain");
> String cookieString = args.get("cookieString");
> CookieManager cookieManager = CookieManager.getInstance();
> cookieManager.setCookie(domain, cookieString);
> }
请问一下这个方法是在weview的onWebViewCreated回调里设置还是在哪里设置的？

**Comment by bingzhao0719** [comment] 2019-10-21 15:01
> addCookie

我在进入webview页面的时候和onWebViewCreated的回调中调用了addCookie的方法都不起效果，请问你是在什么时机调的？

**Comment by bingzhao0719** [comment] 2019-10-21 15:01
> webview中添加
> private void addCookie(MethodCall methodCall, final Result result) {
> Map<String, String> args = (Map<String, String>) methodCall.arguments;
> String domain = args.get("domain");
> String cookieString = args.get("cookieString");
> CookieManager cookieManager = CookieManager.getInstance();
> cookieManager.setCookie(domain, cookieString);
> }

我在进入webview页面的时候和onWebViewCreated的回调中调用了addCookie的方法都不起作用，请问你是在什么时机调用的？

**Comment by bingzhao0719** [comment] 2019-11-10 07:02
@janmoppel  Do you plan to provide the function of setting cookies in webview_flutter?

**Comment by Hixie** [comment] 2019-12-20 22:17
Duplicate of https://github.com/flutter/flutter/issues/27597

**Closed by Hixie** 2019-12-20 22:17 UTC
Labels: p: first party, p: webview, plugin
