### ISSUE TITLE
Overflowing `WidgetSpan` in `Text.rich` causes NPE

### ISSUE THREAD

**Issue by jackdreilly** [flutter/flutter#53238] opened 2020-03-25 10:45 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

`lib/main.dart`

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
    home: Scaffold(
        body: Center(
            child: Container(
                width: 140,
                child: const Text.rich(
                    TextSpan(children: [
                      TextSpan(text: "first target"),
                      WidgetSpan(child: Text("second target"))
                    ]),
                    maxLines: 1))))));
```

3. `flutter run` for android device (mine is MotoX4)
4. Click "first target" text in center of screen.

**Expected results:** No error thrown

**Actual results:** Error throws

### Motivation
The error thrown from the sample above was preventing click events from working on our `TextSpan` in a more complex example.

### Symptoms
This error seems to trigger whenever there's a `WidgetSpan` that falls into the overflow.

For instance, any of the following changes will stop triggering the above error:

1. Get rid of `maxLines: 1`
2. Switch the positions of `TextSpan` and `WidgetSpan`, so the `WidgetSpan` is no longer overflowing
3. Change the width to 500 so it the `WidgetSpan` no longer overflows
4. Change the `WidgetSpan` to a `TextSpan`.

<details>
  <summary>Logs</summary>

```
E/flutter (20096): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toDouble' was called on null.
E/flutter (20096): Receiver: null
E/flutter (20096): Tried calling: toDouble()
[38;5;244mE/flutter (20096): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)[39;49m
[38;5;244mE/flutter (20096): #1      double.*  (dart:core-patch/double.dart:38:23)[39;49m
[38;5;248mE/flutter (20096): #2      Matrix4.scale[39;49m
[38;5;244mE/flutter (20096): #3      RenderParagraph.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #4      RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #5      RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #6      RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #7      RenderShiftedBox.hitTestChildren.<anonymous closure>[39;49m
[38;5;244mE/flutter (20096): #8      BoxHitTestResult.addWithRawTransform[39;49m
[38;5;244mE/flutter (20096): #9      BoxHitTestResult.addWithPaintOffset[39;49m
[38;5;244mE/flutter (20096): #10     RenderShiftedBox.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #11     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #12     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure>[39;49m
[38;5;244mE/flutter (20096): #13     BoxHitTestResult.addWithRawTransform[39;49m
[38;5;244mE/flutter (20096): #14     BoxHitTestResult.addWithPaintOffset[39;49m
[38;5;244mE/flutter (20096): #15     RenderBoxContainerDefaultsMixin.defaultHitTestChildren[39;49m
[38;5;244mE/flutter (20096): #16     RenderCustomMultiChildLayoutBox.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #17     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #18     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #19     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #20     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #21     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #22     RenderPhysicalModel.hitTest[39;49m
[38;5;244mE/flutter (20096): #23     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #24     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #25     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #26     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #27     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #28     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #29     RenderIgnorePointer.hitTest[39;49m
[38;5;244mE/flutter (20096): #30     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #31     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #32     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #33     RenderFractionalTranslation.hitTestChildren.<anonymous closure>[39;49m
[38;5;244mE/flutter (20096): #34     BoxHitTestResult.addWithRawTransform[39;49m
[38;5;244mE/flutter (20096): #35     BoxHitTestResult.addWithPaintOffset[39;49m
[38;5;244mE/flutter (20096): #36     RenderFractionalTranslation.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #37     RenderFractionalTranslation.hitTest[39;49m
[38;5;244mE/flutter (20096): #38     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #39     RenderBox.hitTest[39;49m
[38;5;244mE/flutter (20096): #40     RenderProxyBoxMixin.hitTestChildren[39;49m
[38;5;244mE/flutter (20096): #41     RenderBox.hitTest[39;49m
E/flutter (20096): #42     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/render

```

`flutter analyze`

```
Analyzing bug...
No issues found! (ran in 3.0s)
```

`flutter doctor -v`

```
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.14.6 18G3020, locale en-US)
    • Flutter version 1.15.17 at /usr/local/opt/flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jdrblu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • moto x4    • ZY224LHPZL • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-30 10:11
Persists with current master `1.21.0-6.0.pre.117`

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.117 at /Users/nevercode/dev/flutter
    • Framework revision 7ec2d360bc (2 hours ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

<details>
 <summary>log</summary>

```
E/flutter (32380): [ERROR:flutter/lib/ui/ui_dart_state.cc(167)] Unhandled Exception: UnimplementedError
E/flutter (32380): #0      Matrix4.scale (package:vector_math/src/vector_math_64/matrix4.dart:886:7)
E/flutter (32380): #1      RenderParagraph.hitTestChildren (package:flutter/src/rendering/paragraph.dart:447:10)
E/flutter (32380): #2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #3      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #5      RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:85:24)
E/flutter (32380): #6      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:777:31)
E/flutter (32380): #7      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:80:21)
E/flutter (32380): #8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #9      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2524:24)
E/flutter (32380): #10     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:777:31)
E/flutter (32380): #11     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2519:33)
E/flutter (32380): #12     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:411:12)
E/flutter (32380): #13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #14     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #16     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #18     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1823:18)
E/flutter (32380): #19     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #23     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #25     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3159:31)
E/flutter (32380): #26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #29     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2578:22)
E/flutter (32380): #30     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:777:31)
E/flutter (32380): #31     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2572:19)
E/flutter (32380): #32     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2558:12)
E/flutter (32380): #33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #37     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #39     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3269:31)
E/flutter (32380): #40     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
E/flutter (32380): #41     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
E/flutter (32380): #42     _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:724:24)
E/flutter (32380): #43     BoxHitT
```

</details>

**Comment by yrom** [comment] 2020-08-24 08:05
Wrap the Text with [AbsorbPointer](https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html) may workaround.

**Comment by pedromassango** [comment] 2021-03-24 17:11
Does not reproduce on latest master channel!

**Comment by chunhtai** [comment] 2021-03-24 17:39
This looks like a duplicate issue i fixed a while back. closing

**Closed by chunhtai** 2021-03-24 17:39 UTC
Labels: a: typography, found in release: 1.21, framework, has reproducible steps, severe: crash
