### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: "D:\BSCS\Web Development\Others\Android area\Flutter Software\flutter\bin\cache\dart-sdk\bin\pub.bat", OS error code: 2

### ISSUE THREAD

**Issue by rashid0300** [flutter/flutter#73045] opened 2020-12-28 16:20 UTC
## Command
```
flutter create first_app
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: "D:\BSCS\Web Development\Others\Android area\Flutter Software\flutter\bin\cache\dart-sdk\bin\pub.bat", OS error code: 2
```

```
```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.5 at D:\BSCS\Web Development\Others\Android area\Flutter Software\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Sonic\AppData\Local\Android\sdk
    • Platform android-29, build-tools 30.0.3
    ✗ Android SDK file not found: C:\Users\Sonic\AppData\Local\Android\sdk\platforms\android-29\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Sonic\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment] 2020-12-29 06:54
Closing this as duplicate of https://github.com/flutter/flutter/issues/60776

**Closed by darshankawar** 2020-12-29 06:54 UTC
