### ISSUE TITLE
Routing animation lagging (appears to be a regression)

### ISSUE THREAD

**Issue by RobertBrunhage** [flutter/flutter#15294] opened 2018-03-08 14:16 UTC
I have an open StackOverFlow issue here that expains the issue that I have: https://stackoverflow.com/questions/49145258/flutter-routing-stutter?noredirect=1#comment85329917_49145258

In short: It lags when routing to a new view. Tried the flutter gallery app in play store but it doesn't lag. Ran the flutter gallery app with flutter run --released and the issue is there again.

Flutter doctor -v

[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale en-GB)
    • Flutter version 0.1.5 at C:\Users\Robert\flutter
    • Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Robert\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices (1 available)
    • ONEPLUS A3003 • 5ffff941 • android-arm64 • Android 8.0.0 (API 26)

**Comment by Herohtar** [comment] 2018-03-08 22:20
You can see the difference in the Flutter Gallery apps in the Play Store.

Flutter Gallery posted by "Google Samples" with a release date of 2017-04-24, version `flutter-gallery-bv8-rc000`: https://play.google.com/store/apps/details?id=io.flutter.gallery

Flutter Gallery posted by "flutter.io" with a release date of 2018-02-22, version `0.1.5-pre.25`: https://play.google.com/store/apps/details?id=io.flutter.demo.gallery

Animations in the 2017 one are smooth, while the 2018 version has the stuttering.

**Comment by Hixie** [comment] 2018-03-14 20:29
This is probably just a side-effect of us disabling the fade animation, see https://github.com/flutter/flutter/issues/13736.

**Comment by xster** [comment] 2018-03-15 05:38
Can you guys describe the stuttering/lag a bit more? 

If the Android page transition appears and vanishes in the middle of the screen during the animation, it's a known issue #13736. If the animation motion itself is jittery or drops frames, it'd be a different issue. @Herohtar, what phone are you using?

**Comment by Herohtar** [comment] 2018-03-15 06:36
@xster My phone is the Pixel 2 XL.

After taking a closer look to try to get a better idea of what's going on, I think the issue I'm seeing is that when pushing a route the page just pops into existence about 2/3 of the way up, then slides the rest of the way to the top. It's a bit more noticeable going the other direction: the page slides down, then stops briefly -- again at 2/3 of the way up the screen -- then just vanishes. The animation during the sliding phase looks okay; I think the pause and then the abrupt vanishing is what gives it a sense of being stuttery/jerky/laggy for me.

Is that https://github.com/flutter/flutter/issues/13736?

**Comment by xster** [comment] 2018-03-15 06:47
Yes. I'll close this bug as a dupe of #13736. For an immediate solution applicable locally, see the debugEnableFadingRoutes flag on MaterialPageRoute.

**Closed by xster** 2018-03-15 06:47 UTC
Labels: performance, prod: routes
