### ISSUE TITLE
Image re-render when state change in ListView( KeepAlive not working  )

### ISSUE THREAD

**Issue by nirav4273** [flutter/flutter#22514] opened 2018-10-01 16:09 UTC
Structure
```
ListVIew->
 1. PageView
 2. SizezBox
 3. ListVIew
 4. SizexBox
 5. ListVIew
```
i am trying to make widget keepAlive which on are already loaded in ViewPort in ListView.

On page view change update state. When page change that time ListView widgets re-render.

i am used `AutomaticKeepAliveClientMixin` & also add `addAutomaticKeepAlives:true`.
Also tried with `cacheExtent` attribute.

![ezgif com-crop](https://user-images.githubusercontent.com/22423754/46300797-36e36680-c5c2-11e8-8d78-2773c2bbcfe3.gif)

Here is my code

```dart
import 'package:flutter/material.dart';
import "detail.dart";
void main(){
  runApp(
    new MaterialApp(
      home: Home(),
      theme: ThemeData(
        primaryColor: Colors.white
      ),
    )
  );
}
class Home extends StatefulWidget{
  createState()=>HomeState();
}
class HomeState extends State<Home> with AutomaticKeepAliveClientMixin<Home>{
  int activePage = 0;
  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    setState(() {
      activePage = 0;
    });
  }
  goToNext(img){
    Navigator.push(context,MaterialPageRoute(builder: (context)=>Detail(image: img)));
  }
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        elevation: 0.0,
        leading: Icon(Icons.menu),
        actions: <Widget>[
          Padding(
            padding: EdgeInsets.only(right: 5.0),
            child: Icon(Icons.search),
          )
        ],
        title: Text("Theme"),
      ),
      body: ListView(
        addAutomaticKeepAlives: true,
        children: <Widget>[
          SizedBox(height: 10.0,),
          Container(
            height: 200.0,
            child: PageView.builder(
              onPageChanged: (num){
                print("Page $num");
                setState(() {
                  activePage = num;
                });
              },
              controller: PageController(viewportFraction: 0.85),
              itemBuilder: (context,index){
                  return Stack(
                    fit: StackFit.expand,
                    children: <Widget>[
                      InkWell(
                        onTap: (){
                          goToNext("images/${index+1}.jpg");
                        },
                        child: Padding(
                          padding: EdgeInsets.all(5.0),
                          child:Container(
                            padding: EdgeInsets.all(activePage == index ? 1.0 : 5.0),
                            child: Container(
                              decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(10.0),
                                  boxShadow: activePage == index ? [
                                    BoxShadow(
                                      color: Colors.black38,
//                                    spreadRadius: 1.0,
                                      blurRadius: 8.0,
                                    )
                                  ] : []
                              ),
                              child: ClipRRect(
                                  borderRadius: BorderRadius.circular(10.0),
                                  child: Image.asset("images/${index+1}.jpg",fit: BoxFit.cover,)
                              ),
                            ),
                          ),
                        )
                      ),
                      Container(
                        padding: EdgeInsets.only(left: 15.0,right: 10.0),
                        child: Text("Image overlay Te Image dads Image overlay Te Image dads Image overlay Te Image dads  overlay Text $index",style: TextStyle(color: Colors.white,fontSize: 18.0,fontWeight: FontWeight.w600),),
                        alignment: Alignment(-0.8, 0.6),
                      ),
                    ],
                  );
                },
              itemCount: 10,
            )
          ),
          SizedBox(height: 30.0,),
          Container(
            height: 75.0,
            child: ListView.builder(
              addAutomaticKeepAlives: true,
              itemBuilder: (context,index){
                  return InkResponse(
                    onTap: (){},
                    child:Container(
                      padding: EdgeInsets.only(left: 15.0,right: 10.0,top: 5.0,bottom: 5.0),
                      child: InkWell(
                        onTap: (){},
                        child: Container(
                          child: Container(
                            width: 150.0,
                            height: 70.0,
                            alignment: Alignment.center,
                            decoration: BoxDecoration(
                                boxShadow: [
                                  BoxShadow(
                                    color: Colors.redAccent[100].withOpacity(0.6),
                                    blurRadius: 6.0,
                                  )
                                ],
                                image: DecorationImage(image:AssetImage("images/36.jpg"),fit: BoxFit.fill,colorFilter: ColorFilter.mode(Colors.redAccent.withOpacity(0.5),BlendMode.color)),
                                borderRadius: BorderRadius.circular(10.0)
                            ),
                            child: Text("BUtton $index",style: TextStyle(color: Colors.white,fontWeight: FontWeight.w500,fontSize: 18.0),),
                          ),
                        ),
                      )
                    )
                  );
               },
              itemCount: 10,
              scrollDirection: Axis.horizontal,
            ),
          ),
          Container(
              height: 50.0,
              child: ListTile(
                leading: Text("My Set",style: TextStyle(fontWeight: FontWeight.bold),),
                trailing: Icon(Icons.chevron_right,color: Colors.black,),
              )
          ),
           Container(
                height: 170.0,
                padding: EdgeInsets.only(left: 10.0),
                child: ListView.builder(
                  itemBuilder:(context,index){
                    return Padding(
                        padding: EdgeInsets.only(right: 15.0,top: 10.0,bottom: 10.0),
                        child:Container(
                          width: 100.0,
                          decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(5.0),
                              color: Colors.black12,
                              image: DecorationImage(image: AssetImage("images/${index+1}.jpg",),fit: BoxFit.cover),
                              shape: BoxShape.rectangle,
                              boxShadow: [
                                BoxShadow(
                                  blurRadius: 5.0,
                                  color: Colors.black38,
                                )
                              ]
                          ),
                        )
                    );
                  },
                  scrollDirection: Axis.horizontal,
                  itemCount: 20,
                  addAutomaticKeepAlives: true,
                )
          ),
          Container(
              height: 50.0,
              child: ListTile(
                leading: Text("Popular on Netflix ",style: TextStyle(fontWeight: FontWeight.bold),),
                trailing: Icon(Icons.chevron_right,color: Colors.black,),
              )
          ),
          Container(
              height: 170.0,
              padding: EdgeInsets.only(left: 10.0),
              child: ListView.builder(
                itemBuilder:(context,index){
                  return Padding(
                      padding: EdgeInsets.only(right: 15.0,top: 10.0,bottom: 10.0),
                      child:Container(
                        width: 100.0,
                        decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(5.0),
                            color: Colors.black12,
                            image: DecorationImage(image: AssetImage("images/${index+1}.jpg",),fit: BoxFit.cover),
                            shape: BoxShape.rectangle,
                            boxShadow: [
                              BoxShadow(
                                blurRadius: 5.0,
                                color: Colors.black38,
                              )
                            ]

                        ),
                      )
                  );
                },
                scrollDirection: Axis.horizontal,
                itemCount: 20,
                addAutomaticKeepAlives: true,
                cacheExtent: 1000.0,
              )
          )
        ],
      ),
    );
  }
}

```

**Comment by zoechi** [comment] 2018-10-01 18:56
What part of the animation does not work as expected?

**Comment by nirav4273** [comment] 2018-10-02 02:29
@zoechi  Don't need any type of animation. Issue is when `pageview` change event trigger at that time update state variable.
When state update `ListView` images re-render. Already attached issue with image.(https://github.com/flutter/flutter/issues/22514#issue-365534279)


My code structure 
```
ListVIew->
 1. PageView
 2. SizezBox
 3. ListVIew
 4. SizexBox
 5. ListVIew
```

Flutter details
```
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at E:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = E:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android license status unknown.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.12.2


```

**Comment by zoechi** [comment] 2018-10-02 06:41
What part of the video above demonstrates that? I don't understand the relation between the question and the video.

**Comment by nirav4273** [comment] 2018-10-02 14:41
Ok i will explain in details

Below section is `PageView` widget on PageView change i am updating state.

![pageview](https://user-images.githubusercontent.com/22423754/46354086-65714800-c67b-11e8-9fd6-da349e68b6f4.PNG)

Here is `PageView` section code
```
PageView.builder(
  onPageChanged: (num){
    print("Page $num");
    setState(() {
      activePage = num;
    });
  },
  controller: PageController(viewportFraction: 0.85),
  itemBuilder: (context,index){
      return Stack(
        fit: StackFit.expand,
        children: <Widget>[
          InkWell(
            onTap: (){
              goToNext("images/${index+1}.jpg");
            },
            child: Padding(
              padding: EdgeInsets.all(5.0),
              child:Container(
                padding: EdgeInsets.all(activePage == index ? 1.0 : 5.0),
                child: Container(
                  decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(10.0),
                      boxShadow: activePage == index ? [
                        BoxShadow(
                          color: Colors.black38,
                          blurRadius: 8.0,
                        )
                      ] : []
                  ),
                  child: ClipRRect(
                      borderRadius: BorderRadius.circular(10.0),
                      child: Image.asset("images/${index+1}.jpg",fit: BoxFit.cover,)
                  ),
                ),
              ),
            )
          ),
          Container(
            padding: EdgeInsets.only(left: 15.0,right: 10.0),
            child: Text("Image overlay Te Image dads Image overlay Te Image dads Image overlay Te Image dads  overlay Text $index",style: TextStyle(color: Colors.white,fontSize: 18.0,fontWeight: FontWeight.w600),),
            alignment: Alignment(-0.8, 0.6),
          ),
        ],
      );
    },
  itemCount: 10,
)
```

Below section is ListView. When state update  that time image re-render as mention in video.

![listview](https://user-images.githubusercontent.com/22423754/46355358-49bb7100-c67e-11e8-8f47-ca3fc61254ff.PNG)


PageView & Listview both Widgets added inside ListView Widgets.


i hope now you are clear with issue.

**Comment by nirav4273** [comment] 2018-10-09 02:50
@zoechi  any update on  issue https://github.com/flutter/flutter/issues/22514#issuecomment-426300010  issue ?

**Comment by hankchiutw** [comment] 2019-01-05 15:04
Try wrapping your `ListView` children with stateful widget having `AutomaticKeepAliveClientMixin`.

Based on your code, this `StatefulWidget` may looks like:
```dart
class ImageSliver extends StatefulWidget {
  ImageSliver(this.image);
  final AssetImage image;

  @override
  _ImageSliverState createState() => _ImageSliverState();
}
class _ImageSliverState extends State<ImageSliver>
    with AutomaticKeepAliveClientMixin<ImageSliver> {
    @override
    bool get wantKeepAlive => true;

    @override
    Widget build(BuildContext context) {
       return Padding(
          ...
             image: DecorationImage(image: widget.image,),
          ...
       );
    }
}
```

and use in your code:
```dart
Container(
  ...
  child: ListView.builder(
    itemBuilder:(context,index){
      return ImageSliver(AssetImage("images/${index+1}.jpg",));
    },
  ),
  ...
)
```

**Comment by nirav4273** [comment] 2019-01-06 07:46
@zoechi  Added method as you mentioned still same use.
@hankchiutw  Also tried code as you mentioned.

Here is my code : https://github.com/nirav4273/flutter_keepalive_issue

**Comment by zoechi** [comment] 2019-01-06 10:06
I think this should better be asked in one of the other channels listed at http://flutter.io/support .

**Comment by muarifer** [comment] 2019-04-03 08:07
I have some problem in mine app: 
Flutter 1.3.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e5b1ed7a7f (4 weeks ago) • 2019-03-06 14:23:37 -0800
Engine • revision f4951df193
Tools • Dart 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

After changing stable channel, everything is ok. 
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (7 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

**Comment by AshwinKmr2502** [comment] 2019-06-24 09:48
Hi @zoechi , 
Still facing same issue in listview, every time item gets re rendered.How to fix this??

**Comment by basnetjiten** [comment] 2019-07-11 09:37
There's seems to be no any fixes for this ??

**Comment by joshuapocsidio** [comment] 2019-08-23 06:11
Not sure if this issue has been solved but I was stuck on this issue for the past week and I think I may have found an work around. 

I realised it was the `decoration: DecorationImage(image: AssetImage())` that was causing the AutomaticKeepAliveClientMixin to not work at all. I removed the image from the `BoxDecoration()` and instead used the child of the `Container()` to store an `Image.asset("assets/image.png)`. Although I am not exactly sure about the reasoning behind it, but it definitely worked for me and completely stopped re-rendering given that the AutomaticKeepAliveClientMixin is still in place. I have not been able to spend some time and implement this on your given code but let me know if this works or helps with this issue!

A simplified version of my code is below: 

```
ListView(
  addAutomaticKeepAlives: true,
  scrollDirection: Axis.horizontal,
  children: <Widget> [
    ListItem(image: Image.asset("images/image.jpg", fit: BoxFit.cover)),
    ListItem(image: Image.asset("images/image.jpg", fit: BoxFit.cover)),
    ListItem(image: Image.asset("images/image.jpg", fit: BoxFit.cover)),
    ListItem(image: Image.asset("images/image.jpg", fit: BoxFit.cover)),
  ],
),
```

```
class ListItem extends StatefulWidget {
  final Image image;

  ListItem({this.image});

  @override
  _ListItemState createState() => _ListItemtate();
}

class _ListItemState extends State<ListItem>
    with AutomaticKeepAliveClientMixin<ListItem> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  @mustCallSuper
  Widget build(BuildContext context) {
    super.build(context);

    return Container(
      child: widget.image,
    );
  }

  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}
```

**Comment by Nolence** [comment] 2019-10-23 14:11
Had a similar issue. Realized I had the children of my `PageView` inside the build method and they were thus getting recreated when `setState` was being called from the `BottomNavigationBar` `onTap` method. I just moved the children into the state of the root widget and that did the trick:

```dart
class HomePage extends StatefulWidget {
    @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _page = 0;
  PageController _c;
  final children = [
    ModulesTab(),
    ProfileTab(),
  ];

  @override
  void initState() {
    _c = PageController(initialPage: _page);
    super.initState();
  }

  @override
  void dispose() {
    _c.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return TransparentBackground(
      child: Scaffold(
        body: PageView(
          controller: _c,
          onPageChanged: (newPage) => setState(() => this._page = newPage),
          children: children,
        ),
        bottomNavigationBar: BottomAppBar(
          child: BottomNavigationBar(
            onTap: (index) => _c.animateToPage(
              index,
              duration: const Duration(milliseconds: 500),
              curve: Curves.easeInOut,
            ),
            currentIndex: _page,
            items: const [
              BottomNavigationBarItem(
                icon: Icon(Typicons.flow_merge),
                title: Text('Practice'),
              ),
              BottomNavigationBarItem(
                icon: Icon(Typicons.user_outline),
                title: Text('Profile'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

and then for pageview item:

```dart
class ModulesTab extends StatefulWidget {
  @override
  _ModulesTabState createState() => _ModulesTabState();
}

class _ModulesTabState extends State<ModulesTab>
    with AutomaticKeepAliveClientMixin<ModulesTab> {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    
    /* ... */
  }
}
```

**Comment by 4RSIM3R** [comment] 2020-02-11 07:14
> Not sure if this issue has been solved but I was stuck on this issue for the past week and I think I may have found a work around.
> 
> I realised it was the `decoration: DecorationImage(image: AssetImage())` that was causing the AutomaticKeepAliveClientMixin to not work at all. I removed the image from the `BoxDecoration()` and instead used the child of the `Container()` to store an `Image.asset("assets/image.png)`. Although I am not exactly sure about the reasoning behind it, but it definitely worked for me and completely stopped re-rendering given that the AutomaticKeepAliveClientMixin is still in place. I have not been able to spend some time and implement this on your given code but let me know if this works or helps with this issue!
> 
> A simplified version of my code is below:
> 
> ```
> ListView(
>   addAutomaticKeepAlives: true,
>   scrollDirection: Axis.horizontal,
>   children: <Widget> [
>     ListItem(image: Image.asset("images/image.jpg", fit: BoxFit.cover)),
>     ListItem(image: Image.asset("images/image.jpg", fit: BoxFit.cover)),
>     ListItem(image: Image.asset("images/image.jpg", fit: BoxFit.cover)),
>     ListItem(image: Image.asset("images/image.jpg", fit: BoxFit.cover)),
>   ],
> ),
> ```
> 
> ```
> class ListItem extends StatefulWidget {
>   final Image image;
> 
>   ListItem({this.image});
> 
>   @override
>   _ListItemState createState() => _ListItemtate();
> }
> 
> class _ListItemState extends State<ListItem>
>     with AutomaticKeepAliveClientMixin<ListItem> {
>   @override
>   void initState() {
>     // TODO: implement initState
>     super.initState();
>   }
> 
>   @override
>   @mustCallSuper
>   Widget build(BuildContext context) {
>     super.build(context);
> 
>     return Container(
>       child: widget.image,
>     );
>   }
> 
>   @override
>   // TODO: implement wantKeepAlive
>   bool get wantKeepAlive => true;
> }
> ```

Hay, Very Well Thank You, I Spend two day to solve this problem

**Comment by VladyslavBondarenko** [comment] 2020-03-31 15:20
Reproduced https://github.com/nirav4273/flutter_keepalive_issue
with `master v1.16.4-pre.34`

**Comment by VladyslavBondarenko** [comment] 2020-07-28 07:46
Persists with current stable `1.17.5`.
But I can't reproduce it with current beta `1.20.0-7.2.pre` and master `1.21.0-6.0.pre.41`.

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/17024977/88634735-70526380-d0bf-11ea-8ca8-10d40b3b242f.gif)

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.41, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.41 at /Users/nevercode/dev/flutter
    • Framework revision 39fa00201d (3 hours ago), 2020-07-27 21:11:43 -0700
    • Engine revision f27729e97b
    • Dart version 2.10.0 (build 2.10.0-0.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (5 available)            
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

Seems to be fixed, closing since there is not need then to track the issue. 
@nirav4273 if you disagree please comment and I'll reopen

**Closed by VladyslavBondarenko** 2020-07-28 07:46 UTC
Labels: d: stackoverflow, f: scrolling, framework, has reproducible steps

**Comment by Tharindu-dart** [comment] 2020-07-29 16:15
> @zoechi Added method as you mentioned still same use.
> @hankchiutw Also tried code as you mentioned.
> 
> Here is my code : https://github.com/nirav4273/flutter_keepalive_issue

problem is DecorationImage  , because it will not keepAlive . Remove DecorationImage and then use Direct Image widget with ClipRect to add radius.
