### ISSUE TITLE
DateTime.parse fails with "Invalid date format"

### ISSUE THREAD

**Issue by ozzy1873** [flutter/flutter#25891] opened 2018-12-29 18:21 UTC
An API returns date strings in this format: "2018-12-29T18:39:12.4867135Z". The DateTime parse method fails with "Invalid date format" unless the fractional seconds are truncated.

**Comment by marcoms** [comment] 2018-12-29 22:34
Looks like a Dart issue, not Flutter

**Comment by zoechi** [comment] 2018-12-30 15:06
Duplicate of dart-lang/sdk#24205

**Closed by zoechi** 2018-12-30 15:06 UTC
