### ISSUE TITLE
Flutter app (MacOS) with Associated Domains capability won't build (builds fine using Xcode)

### ISSUE THREAD

**Issue by martin-robert-fink** [flutter/flutter#77941] opened 2021-03-11 17:23 UTC
When using plugins `uni_links` and `uni_links_macos` (which require the Associated Domains capability for Universal Links), flutter won't build a MacOS app and emits the following error (It does build/run using Xcode):

```
Launching lib/main.dart on macOS in debug mode...
lib/main.dart:1
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: Provisioning profile "Mac Team Provisioning Profile: com.example.test" doesn't include the currently selected device "MacBook Pro M1" (identifier XXX). (in target 'Runner' from project 'Runner')
** BUILD FAILED **

Exception: Build process failed
```
However, the app builds fine using Xcode. I did submit an issue with the `uni_links_macos` plugin, but since this builds fine in Xcode, but not using flutter (VSCode), I believe this is an issue with Flutter devtools.

Steps to replicate....

1. `flutter create` the standard default app/template
2. add `uni_links` and `uni_links_macos` to `pubspec.yaml` dependencies
3. No code changes required to duplicate this.
4. Using Xcode, add the `Associated Domains` capability which will require signatures get setup properly
 
**(Note: If you try to do this by just editing `DebugProfile.entitlements`, you'll still need to go setup signatures in Xcode).**

That's it.  Attempt to build in Xcode, all will work fine; attempt to build/run (Using VSCode) and the build fails with the error above.

I've tried both the dev and stable channels.  Here's my flutter doctor for dev channel:

```
mfink@MacBook-Pro test_app % flutter doctor -v
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.2 20D80 darwin-arm, locale en-US)
    • Flutter version 2.1.0-10.0.pre at /Users/mfink/Developer/flutter
    • Framework revision cc9b78fc5c (2 weeks ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mfink/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/mfink/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/mfink/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 11.2.2 20D80 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

**Comment by darshankawar** [comment] 2021-03-12 10:50
@martin-robert-fink 
I tried your steps to replicate using latest master and was able to compile and build macOS app without any issues using Android Studio.

<img width="277" alt="Screenshot 2021-03-12 at 4 18 33 PM" src="https://user-images.githubusercontent.com/67046386/110930004-9bd44680-834e-11eb-8a68-da43bb1a563a.png">

```
Running pod install...                                           1,468ms
Building macOS application...                                           
Syncing files to device macOS...                                   100ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:56283/b_D1Xm7qUbg=/

```

Since I don't have VScode, I couldn't verify on it. But can you switch to latest master and try again to see if issue persists or not ?

```
flutter channel master
flutter upgrade

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.227, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.227 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 66768f8c5b (6 hours ago), 2021-03-11 19:55:02 -0800
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by martin-robert-fink** [comment] 2021-03-12 15:27
Hi - Thanks so much for trying this.  I had not tried on Android Studio, but now I have.

I followed your steps.  I did switch to master channel/upgrade.  I get the exact same error.

Here is the screen shot:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/31779055/110957984-6b1dee00-8309-11eb-8cbf-67e8bf0af3fc.png">

Also have `pubspec.yaml` as yours:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/31779055/110958165-a4565e00-8309-11eb-815b-7e38d3691f7d.png">

I tried both with/without null safety enabled, no difference.

Also, just for completeness, here is the `DebugProfile.entitlements`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>webcredentials:example.com</string>
	</array>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
</dict>
</plist>
```

Finally, here again is flutter doctor....

```
mfink@MacBook-Pro test_app % flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.229, on macOS 11.2.2 20D80 darwin-arm, locale en-US)
    • Flutter version 2.1.0-11.0.pre.229 at /Users/mfink/Developer/flutter
    • Framework revision d20ec4c7d8 (9 hours ago), 2021-03-11 22:18:51 -0800
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mfink/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/mfink/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/mfink/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.2.2 20D80 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

I'm not sure why the plugin comment is showing up.  I have both plugins installed in Android studio and no updates available:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/31779055/110961075-a372fb80-830c-11eb-9dd4-14effd7170fb.png">

Thanks again for looking at this.  I'd love to find a solution....

Martin

**Comment by martin-robert-fink** [comment] 2021-03-12 15:37
Hi -

I tried something else... I tried doing it on my x86 Mac (I have both M1 and x86) and it worked fine, which is likely why it worked for you.  So, it appears this is an issue with the flutter build plugin (both VSCode and Android Studio) that is specific to the M1 Mac.

Thanks again for giving me the idea to go check.

I suspect the issue needs to be relabeled as an M1 Mac specific issue.  But again, it builds using Xcode on the M1 Mac.

Martin

**Comment by darshankawar** [comment] 2021-03-15 05:40
> I'm not sure why the plugin comment is showing up. I have both plugins installed in Android studio and no updates available:

@martin-robert-fink 
These are just warnings given by `doctor`, and you may ignore them, since you should be able to use the plugins as usual.

I am tagging @markusaksli-nc to verify this on M1.

**Comment by markusaksli-nc** [comment] 2021-03-15 13:36
Hi @martin-robert-fink 
First off the error is coming from Xcode code signing, not the Flutter tool so this just isn't an issue with the Flutter tool itself.
Please make sure your [Apple Developer device list](https://developer.apple.com/account/resources/devices/list) contains the **`Hardware UUID`** (from `About This Mac` -> `System Report...`) **not** the `Provisioning UDID`.
Thank you

**Comment by martin-robert-fink** [comment] 2021-03-15 14:35
Hi Markus...

Thanks for looking into this.  A few things:

- If you look at the stream, you'll see that I mention that the project compiles fine using Xcode.  That would seem to indicate that all the signing is proper.  It fails using VSCode or Android Studio.
- To double check, I did go look at my device list.  You are correct that my device list contains the `Provisioning UUID` and not the `hardware UUID`.
- However, when I try to add the hardware UUID, I get an error that it's not a a valid UUID.  See images below:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/31779055/111169766-e16c5b80-8568-11eb-8b9a-54851f8535d6.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/31779055/111169849-f517c200-8568-11eb-86c9-5fa634334a77.png">

This is the current device configuration:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/31779055/111170075-2c866e80-8569-11eb-9c70-fed90e98d251.png">

**Comment by martin-robert-fink** [comment] 2021-03-15 14:53
I found this on the Apple developer web site:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/31779055/111172938-dc5cdb80-856b-11eb-8f62-31eada192b37.png">

**Comment by martin-robert-fink** [comment] 2021-03-15 15:44
If you have an M1, it appears easy to duplicate the issue.  Are you able to duplicate it on your end?  Keep in mind that it's only when the `Associated Domains` capability is added (with `uni_links`/`uni_links_macos` in `pubspec.yaml`) that the issue presents itself.  Without that capability, builds are fine.

**Comment by markusaksli-nc** [comment] 2021-03-15 15:53
It isn't just `Associated Domains`. I ran into this when trying to build with `firebase_messaging` for macOS. It's probably any capability that requires you to sign for more than running locally.

Like I said I ran into this exact issue before but was able to get around it with the mentioned solution. I would need someone at the team to remove the device with the UUID from the list to reproduce it again and I don't think it's necessary as this occoured on a previous version of the 2.1 master channel.

**Comment by rdev-software** [comment] 2021-04-05 09:21
Still present, even on MASTER channel

```
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: Provisioning profile "Mac Team Provisioning Profile: *" doesn't include the currently selected device "Tomas’s Mac mini" (identifier BB6A7A35-E283-5E84-XXXX-XXXXXX). (in target 'Runner' from project 'Runner')
** BUILD FAILED **
```

My plugin list:
```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  universal_platform: 1.0.0-nullsafety
  provider: 5.0.0
  location: 4.1.1
  path_provider: 2.0.1
  biometric_storage:
    git:
      url: https://github.com/radvansky-tomas/biometric_storage.git
      ref: null-safety
  reactive_forms:
    git:
      url: https://github.com/tierratechnologies/reactive_forms.git
      ref: 9.0.0
  sizer: ^1.1.8
  protobuf: 2.0.0
  firebase_core: 1.0.2
  url_launcher: 6.0.1
  uuid: 3.0.3
  sembast: 3.0.0+4
  sembast_web: '>=1.0.0'
  latlng: 0.1.0
  jaguar_jwt: 3.0.0
  package_info_plus: 1.0.0
  flutter_modular: ^3.0.2+1
  convert: 3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
```

**Comment by nickmeinhold** [comment] 2021-12-01 03:14
Registering another device, using the hardware UUID, worked for me.  

In the screenshot above (Register a device), the Platform appears to be set to "iOS, tvOS, watchOS" rather than "MacOS".

**Comment by jmagman** [comment] 2022-12-22 22:44
I don't think this has much to do with Flutter, it sounds like it's something with Apple Developer accounts, M1, and what devices you have registered.  I know it worked from Xcode, but it's probably doing some extra magic that doesn't happen with the `xcodebuild` command line tool that Flutter is calling.

I'm going to close this because I don't think Flutter tooling can do anything about it.  If you see this issue, please double-check your Apple developer account to make sure you have all the expected devices registered.

**Closed by jmagman** 2022-12-22 22:44 UTC
Labels: tool, platform-mac, a: build, P4, 💻platform-bigsur, platform-host-arm, platform-target-arm
