### ISSUE TITLE
Plugin: Can iOS and macOS depend on same native source files without being copied?

### ISSUE THREAD

**Issue by namniav** [flutter/flutter#61829] opened 2020-07-19 18:37 UTC
[platform-integration/c-interop#step-2-add-cc-sources](https://flutter.dev/docs/development/platform-integration/c-interop#step-2-add-cc-sources) says:
>You add the sources to the `ios` folder, because CocoaPods doesn’t allow including sources above the `podspec` file, but Gradle allows you to point to the `ios` folder.

However, the macOS-specific also use CocoaPods. 

For example, I have some platform-independent source files written in c(or objc, swift, etc) and I want to develop a flutter plugin for it. Can I "link" native source files, without being copied, to both `ios/my_plugin.podspec` and `macos/my_plugin.podspec`?

I tried create a symlink under `macos` but it didn't work:
```
.
├── ios
│   ├── Classes
│   │   ├── MyPlugin.h
│   │   ├── MyPlugin.m
│   │   └── SwiftMyPlugin.swift
│   ├── native_add
│   │   ├── native_add.c
│   └── my_plugin.podspec			# s.source_files = 'Classes/**/*', 'native_add/*.c'
├── macos
│   ├── Classes
│   │   └── SwiftMyPlugin.swift
│   ├── native_add  -> ../ios/native_add	# did not work
│   └── my_plugin.podspec			# s.source_files = 'Classes/**/*', 'native_add/*.c'
├── lib
│   └── my_plugin.dart
└── pubspec.yaml
```

Since Flutter generates a `Podfile` and create a symlink to `ios or macos` for app-project that using the plugin, Can I create a custom `native_add/podspec` and make it a dependency to `ios/podspec` and `macos/podspec`?
```
.
├── ios
│   ├── Classes
│   │   ├── MyPlugin.h
│   │   ├── MyPlugin.m
│   │   └── SwiftMyPlugin.swift
│   └── my_plugin.podspec			# s.dependency "native_add"
├── macos
│   ├── Classes
│   │   └── SwiftMyPlugin.swift
│   └── my_plugin.podspec			# s.dependency "native_add"
├── native_add
│   ├── native_add.c
│   └── native_add.podspec			# Can I tell Flutter to link this podspec(and the native_add folder) to those app-projects using the plugin, just like the ios/macos folder?
├── lib
│   └── my_plugin.dart
└── pubspec.yaml
```

**Comment by stuartmorgan** [comment] 2020-07-19 19:57
Duplicate of https://github.com/flutter/flutter/issues/52285

**Closed by stuartmorgan** 2020-07-19 19:57 UTC
Labels: created via support template
