### ISSUE TITLE
flutter run -d chrome JSNoSuchMethodError / TypeError

### ISSUE THREAD

**Issue by Olischne** [flutter/flutter#153826] opened 2024-08-21 08:39 UTC
### Steps to reproduce

run any Flutter Web project with `flutter run -d chrome` in Flutter 3.24.0

### Expected results

App should be shown in chrome

### Actual results

Chrome opens. In some cases, the app starts normally. In most cases one of the following errors happens:

1. JSNoSuchMethodError: App shows red Exception screen, logs show NoSuchMethodError "TypeError: Cannot read properties of undefined"  (see logs)
2. App keeps loading, console logs still waiting for connection from debug service, chrome console shows "TypeError: Cannot read properties of undefined"  (see screenshots)

Reloading the page in chrome always fixes the error, the app gets shown correctly.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.green),
        useMaterial3: true,
      ),
      home: const Text("Test"),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1312" alt="Screenshot 2024-08-21 at 09 54 36" src="https://github.com/user-attachments/assets/4ae15e42-8816-49b3-bcfc-b504f9c11b0a">

![Screenshot 2024-08-21 at 09 56 15](https://github.com/user-attachments/assets/cdbab77a-a61a-467b-abee-d1cfc952498e)

</details>

### Logs

<details open><summary>Logs</summary>

```console
olischne@OliMSWAG flutter_test_app % fvm flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...              6.3s
This app is linked to the debug service: ws://127.0.0.1:50299/fDglXp4SKlY=/ws
Debug service listening on ws://127.0.0.1:50299/fDglXp4SKlY=/ws

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

A Dart VM Service on Chrome is available at: http://127.0.0.1:50299/fDglXp4SKlY=
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown building MyApp(dirty):
TypeError: Cannot read properties of undefined (reading 'ThemeData')

The relevant error-causing widget was:
  MyApp MyApp:file:///Users/olischne/projects/flutter_test_app/lib/main.dart:4:16

When the exception was thrown, this was the stack:
packages/flutter_test_app/main.dart 14:14                                build
packages/flutter/src/widgets/framework.dart 5687:22                      build
packages/flutter/src/widgets/framework.dart 5617:15                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5780:11                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5771:11                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5780:11                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5771:11                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5780:11                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5771:11                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5780:11                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5771:11                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/view.dart 441:16                            [_updateChild]
packages/flutter/src/widgets/view.dart 464:5                             mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/framework.dart 5642:16                      performRebuild
packages/flutter/src/widgets/framework.dart 5780:11                      performRebuild
packages/flutter/src/widgets/framework.dart 5333:7                       rebuild
packages/flutter/src/widgets/framework.dart 5599:5                       [_firstBuild]
packages/flutter/src/widgets/framework.dart 5771:11                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5593:5                       mount
packages/flutter/src/widgets/framework.dart 4468:15                      inflateWidget
packages/flutter/src/widgets/framework.dart 3963:18                      updateChild
packages/flutter/src/widgets/binding.dart 1605:16                        [_rebuild]
packages/flutter/src/widgets/binding.dart 1574:5                         mount
packages/flutter/src/widgets/binding.dart 1527:16                        <fn>
packages/flutter/src/widgets/framework.dart 3038:11                      buildScope
packages/flutter/src/widgets/binding.dart 1526:12                        attach
packages/flutter/src/widgets/binding.dart 1265:26                        attachToBuildOwner
packages/flutter/src/widgets/binding.dart 1247:5                         attachRootWidget
packages/flutter/src/widgets/binding.dart 1233:7                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:11  internalCallback

════════════════════════════════════════════════════════════════════════════════════════════════════
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:50299/fDglXp4SKlY=


```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
olischne@OliMSWAG flutter_test_app % fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/olischne/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/olischne/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/olischne/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 15 (mobile)              • 1DB47993-EF40-4F5E-B4F1-CC92D9BBBC2C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-08-21 09:51
Hi @Olischne 
This is a known issue at https://github.com/flutter/flutter/issues/145410 and it's fixed on Flutter master channel. Please follow https://github.com/flutter/flutter/issues/152953 for updates.

Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/145410.

**Closed by huycozy** 2024-08-21 09:51 UTC
Labels: in triage
