### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'Receiver: Closure: (_SyncIterator<Package>) => boolTried calling: MutablePackageTree.allPackages()Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool

### ISSUE THREAD

**Issue by maltub9** [flutter/flutter#59590] opened 2020-06-16 19:29 UTC
## Command
```
flutter run --machine --target lib\main.dart -d 192.168.1.11:4455 --track-widget-creation --start-paused --web-server-debug-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      new SimplePackageConfig (package:package_config/src/package_config_impl.dart:26:36)
#3      parsePackageConfigJson (package:package_config/src/package_config_json.dart:213:10)
#4      parsePackageConfigBytes (package:package_config/src/package_config_json.dart:45:10)
#5      readAnyConfigFileUri (package:package_config/src/package_config_io.dart:76:14)
<asynchronous suspension>
#6      loadPackageConfigUri (package:package_config/package_config.dart:90:5)
#7      loadPackageConfigWithLogging (package:flutter_tools/src/dart/package_map.dart:36:10)
#8      findPlugins (package:flutter_tools/src/plugins.dart:308:45)
#9      refreshPluginsList (package:flutter_tools/src/plugins.dart:1067:38)
#10     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:229:11)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:782:21)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:694:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _runZoned (dart:async/zone.dart:1630:10)
#18     runZoned (dart:async/zone.dart:1550:10)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:684:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
```
```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.18.0-11.1.pre at C:\Users\Malek\flutter
    • Framework revision 2738a1148b (5 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Malek\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Users\Malek\android_studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Users\Malek\android_studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.46.0)
    • VS Code at C:\Users\Malek\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • JSN L22 • 192.168.1.11:4455 • android-arm64 • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 2a7bc389f28d83c581f7ddd4601588a22e12512e
### Plugins
path_provider-1.6.7
path_provider_macos-0.0.4+1
url_launcher-5.4.7
url_launcher_macos-0.0.1+5
url_launcher_web-0.1.1+6

**Comment by YI--** [comment] 2020-06-17 05:48
今天碰见同样的问题

**Comment by TahaTesser** [comment] 2020-06-17 09:28
duplicate of https://github.com/flutter/flutter/issues/59245

**Closed by TahaTesser** 2020-06-17 09:28 UTC
