### ISSUE TITLE
#in-app-purchase uses old google play billing

### ISSUE THREAD

**Issue by MohoPina** [flutter/flutter#151436] opened 2024-07-08 22:34 UTC
### Use case

Hello, in_app_purchase library uses low version of google play billing but google play required all android developers to use google billing version 6.0.1 or later as August 2024. when will you update this dependency of in_app_purchase?

### Proposal

no sample code

**Comment by stuartmorgan** [comment] 2024-07-08 22:38
Closing as a duplicate of https://github.com/flutter/flutter/issues/149991

**Closed by stuartmorgan** 2024-07-08 22:38 UTC
