### ISSUE TITLE
RawKeyboardListener not working in iOS

### ISSUE THREAD

**Issue by BuuTran-Savvycom** [flutter/flutter#62774] opened 2020-08-03 07:22 UTC
Hi,
RawKeyboardListener stops working in iOS, it used to work couple of weeks ago. It still works in Android. I use Flutter demo app for testing:
```
import 'package:flutter/material.dart';
import 'package:logger/logger.dart';

final logger = Logger(
  printer: PrettyPrinter(
      methodCount: 2, // number of method calls to be displayed
      errorMethodCount: 8, // number of method calls if stacktrace is provided
      lineLength: 120, // width of the output
      colors: true, // Colorful log messages
      printEmojis: true, // Print an emoji for each log message
      printTime: true // Should each log print contain a timestamp
      ),
);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
         primarySwatch: Colors.blue,
         visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final FocusNode _rawNode = FocusNode();
  final FocusNode _textNode = FocusNode();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    final myController = TextEditingController();
    TextField _textField = TextField(
      controller: myController,
      enableSuggestions: false,
      showCursor: true,
      // style: TextStyle(color: Colors.white),
      autofocus: true,
      focusNode: _textNode,
      readOnly: true, // false, same outcome
      // decoration: InputDecoration(fillColor: Colors.white, filled: true),
    );
    
    if(_textNode.hasFocus) {
      logger.d('got focus');
    }

    if(ModalRoute.of(context).isCurrent) {
      if(!_textNode.hasFocus) {
        FocusScope.of(context).requestFocus(_textNode); 
        logger.d('request focus');
      }      
    }
    else  if(_textNode.hasFocus) {
      _textNode.unfocus();
    }

    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
        flexibleSpace: RawKeyboardListener(focusNode: _rawNode, onKey: handleKey,
              child: _textField, autofocus: true),
      ),

      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Future<void> handleKey(RawKeyEvent key) async {
    if(key.runtimeType.toString().contains('UpEvent')) {
      logger.d(key.data.logicalKey.debugName);    
    }
  }
}
```

Here is output from flutter doctor
flutter doctor -v
```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.14.6 18G84, locale en-VN)
    • Flutter version 1.19.0-4.1.pre at /Users/buuth/MyApps/flutter
    • Framework revision f994b76974 (8 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/Caskroom/android-sdk/4333796
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • D6C085E2-F0C3-4CED-958E-C2C61CB78DB4 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator) 
```

**Comment by pedromassangocode** [comment] 2020-08-03 13:10
Hi @BuuTran-Savvycom 
For the issue to be workable, it needs to be reproducible with a [minimal complete code](https://stackoverflow.com/help/minimal-reproducible-example) sample that doesn’t include 3rd party plugins or complex production code. Please provide such sample. Also please provide the steps to reproduce the issue.
Thank you

**Comment by BuuTran-Savvycom** [comment] 2020-08-04 01:30
@pedromassango : thank you for fast response, it's a good sign!
I attach the test app. Pls run app in Android emulator and iOS simulator, make sure that emulator/ simulator has focus, then type in your PC keyboard
Expected: counter in both app to go up
Actually: only Android app works, iOS app does not capture any keyboard press events 
This issue was introduced within just few weeks, it used to work perfectly in iOS.
Thank you

[test_raw_keyboard_listener.zip](https://github.com/flutter/flutter/files/5019575/test_raw_keyboard_listener.zip)

**Comment by pedromassangocode** [comment] 2020-08-04 07:53
Also found in `1.21.0-6.0.pre.160`. Only reproducible on iOS, Android and Web works fine.

<details>
<summary> Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final FocusNode _rawNode = FocusNode();
  final FocusNode _textNode = FocusNode();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    final myController = TextEditingController();
    TextField _textField = TextField(
      controller: myController,
      enableSuggestions: false,
      showCursor: true,
      // style: TextStyle(color: Colors.white),
      autofocus: true,
      focusNode: _textNode,
      readOnly: true,
      // decoration: InputDecoration(fillColor: Colors.white, filled: true),
    );

    if(_textNode.hasFocus) {
      print('got focus');
    }

    if(ModalRoute.of(context).isCurrent) {
      if(!_textNode.hasFocus) {
        FocusScope.of(context).requestFocus(_textNode);
        print('request focus');
      }
    }
    else  if(_textNode.hasFocus) {
      _textNode.unfocus();
    }

    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
        flexibleSpace: RawKeyboardListener(focusNode: _rawNode, onKey: handleKey,
            child: _textField, autofocus: true),
      ),

      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Future<void> handleKey(RawKeyEvent key) async {
    if(key.runtimeType.toString().contains('UpEvent')) {
      _incrementCounter();
      print(key.data.logicalKey.debugName);
    }
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.160, on Mac OS X 10.15.6 19G73,
    locale en)
    • Flutter version 1.21.0-6.0.pre.160 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 31ee51a302 (7 hours ago), 2020-08-03 17:27:21 -0700
    • Engine revision fa16c3d0ba
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.4
    • Dart plugin version 202.6397.47

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) • 1119074E-0493-4533-9212-6758A33EB40C
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 84.0.4147.105

! Doctor found issues in 2 categories.
```
</details>

**Comment by gspencergoog** [comment] 2020-08-10 17:08
Yes, it did: I added support for delayed event synthesis, but it shouldn't have affected this.  I'll check it out.

**Comment by gspencergoog** [comment] 2020-08-18 17:12
So, it's not the delayed event synthesis, as that was reverted.

@BuuTran-Savvycom I'm actually a bit curious as to what you were using that used to work here, since we've never implemented hardware key event support for iOS. Were these events from the software keyboard?

For instance, this issue is still open: https://github.com/flutter/flutter/issues/31945 because we've never implemented iOS key event support. Not that we don't want to: it's one of the things that we definitely want to fix, but we haven't gotten to it yet.

**Comment by pedromassango** [comment] 2020-08-18 18:13
> So, it's not the delayed event synthesis, as that was reverted.
> 
> @BuuTran-Savvycom I'm actually a bit curious as to what you were using that used to work here, since we've never implemented hardware key event support for iOS. Were these events from the software keyboard?
> 
> For instance, this issue is still open: #31945 because we've never implemented iOS key event support. Not that we don't want to: it's one of the things that we definitely want to fix, but we haven't gotten to it yet.

Is the actual issue related to https://github.com/flutter/flutter/issues/14809? I really wan to send a PR to https://github.com/flutter/flutter/issues/14809 but have some questions on where to start

**Comment by gspencergoog** [comment] 2020-08-18 18:39
@pedromassango What are your questions?

**Comment by pedromassango** [comment] 2020-08-18 19:16
> @pedromassango What are your questions?

Where do I even start to fix https://github.com/flutter/flutter/issues/14809? At first I thoughht to just detect when a character is removed but then I realised that the issue is to detect the 'Delete' button press and tried to fix by using RawKeyboardListener but I had no luck with it.

**Comment by gspencergoog** [comment] 2020-08-18 19:37
@pedromassango We should probably talk about that issue on the #14809 comments, rather than here, see https://github.com/flutter/flutter/issues/14809#issuecomment-675673186.

**Comment by BuuTran-Savvycom** [comment] 2020-08-26 09:05
@gspencergoog 
I do remember it was working in iOS. It used to work for many people, you can find many discussions in Internet about using raw keyboard events for barcode scanner. We used hardware keyboard. If it's not intended to be working, probably you should change documentation and state clearly that RawKeyboardListener is useless in iOS.
Thanks

**Comment by gspencergoog** [comment] 2020-08-27 23:33
OK, thanks for the info.

Since we've never implemented iOS keyboard support, I'm going to close this issue, since it's not a regression, and https://github.com/flutter/flutter/issues/31945 still is open.

We should probably add a comment to the `RawKeyboardListener`/`RawKeyboard` docs about not supporting it yet on iOS.

**Closed by gspencergoog** 2020-08-27 23:33 UTC
Labels: P2, a: text input, engine, found in release: 1.19, found in release: 1.21, framework, has reproducible steps, platform-ios, severe: regression
