### ISSUE TITLE
ListView use memory abnormally in IOS, gc works incorrectly. 

### ISSUE THREAD

**Issue by zf19820621** [flutter/flutter#39613] opened 2019-08-31 09:56 UTC
It is serious, i hope official will fix it in prior.I reported in issue #36753 before, but i discover it is not final problem in the fact.

## flutter doctor:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 1.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
[!] Android Studio (version 2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.15.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
```

Description: 
1. Create a listview, and add some items (anything is ok), then open xcode for debug, scroll the view up and down some times, the memory increase 500K-3MB, howerver, it is not easy to decrease for memory. Someone publish it in 2018, issue #20245, and refer to dart vm gc.
Howerver i use flutter 1.7.8-hotfix4, dart-2.4(i checked it has fixed the gc problem), the problem still occured. My app is pure flutter, not native blend flutter.

2.Create a swiper using flutter-swiper plugin, then open xcode for debug, the memory is increasing if the pages in swiper controll changes,  and with no decreasing. The memory leaks. The swiper use pageview,pagecontroller to realize.

I think anywhere using listview, pageview will result to memory cosume incorrectly, maybe it is due to gc mechanism, or listview itself not handle normally.Due to this, it is almost not possible to release some complicated app, the memory is used so terrible.

**Comment by dnfield** [comment] 2019-09-04 23:12
Can you try to get a memory dump of the app and see what's taking up the space?  Run it in Xcode, and use the memory debugging features to check.

I suspect this is WAI - Skia has an internal cache which will hold on to some graphics related things up to a certain limit. We almost never flush that cache, unless there is memory pressure. I recently changed it so that the limit of the cache would be based on screen resolution, but I expect that 3MB is far below that limit (the cache previously was hard coded to 512MB, now it should typically be somewhere in at least the 10s if not 100s of MB, dependent on screen resolution).

If you need to set that cache smaller (which is not typically recommended), there's a system channel to do so.  However, it would be good to first verify which objects are taking up space.  You could also verify that Dart objects are getting collected by attaching to the observatory and looking at the heap.

**Comment by zf19820621** [comment] 2019-09-09 05:58
Sorry, i reply to this now.It is not relevant to graphic cache directly, because i test it in almost empty example code, that only have app widget, and create a listview in body, add two or more text or image items, then scroll the listview, you can reappear my problem. You just scroll the listview up and down, xcode memory performance will change, mostly up but rarely down. You can try it as my discription.
I use flutter swiper, just show the control widget, not do something else, the memory also increase, i don't know clearly that if the plugin has some bug, i only see the plugin use pageview and timer, but the memory consume abnormally as result.

**Comment by zf19820621** [comment] 2019-09-09 06:03
@dnfield

**Comment by alectogeek** [comment] 2019-11-08 17:14
Is there any news?

**Comment by dnfield** [comment] 2020-01-13 21:33
Can you please share a sample app that causes this problem?

This could be due to many different things and it's hard to properly triage this issue as is right now.  What specific widgets you're using makes a difference here, as it could be images, or it could be something else.  We've made some memory usage improvements since this bug was originally filed, and it may be fixed now as well.

**Comment by dnfield** [comment] 2020-01-13 21:41
And if the problem is with images, see my comment on the other bug you linked.

**Comment by VladyslavBondarenko** [comment] 2020-03-12 13:56
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
@zf19820621 provide please a sample app to reproduce this problem if it persists and I'll reopen it,
Thank you

**Closed by VladyslavBondarenko** 2020-03-12 13:56 UTC
Labels: f: scrolling, framework, severe: performance, waiting for customer response, ⌺‬ platform-ios
