### ISSUE TITLE
Error 1062 Starting Hello World

### ISSUE THREAD

**Issue by juanfeorar** [flutter/flutter#27500] opened 2019-02-04 17:14 UTC
**Hello, i installed flutter but when try run on hello world, it shows this error:**

> E/flutter ( 1062): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(85)] Failed to setup Skia Gr context.

**The debug console complete is:**

> Launching lib/main.dart on 192.168.56.101:5555 in debug mode...
> Built build/app/outputs/apk/debug/app-debug.apk.
> E/flutter ( 1062): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(85)] Failed to setup Skia Gr context.

**Thanks**

**Comment by wouterhardeman** [comment] 2019-02-04 17:16
Can you post the output of `flutter doctor -v`?

Seems related to: https://github.com/flutter/flutter/issues/15451

Try running the application using: `flutter run --enable-software-rendering`.

**Comment by zoechi** [comment] 2019-02-12 13:42
Duplicate of #8610

**Closed by zoechi** 2019-02-12 13:42 UTC
Labels: dependency: skia, engine, severe: crash
