### ISSUE TITLE
Bug: Screen would be flashing when Other Apps are using the keyboard.

### ISSUE THREAD

**Issue by zhbh** [flutter/flutter#59301] opened 2020-06-12 03:44 UTC
## Steps to Reproduce

1. Run the flutter project without opening the keyboard;
2. Switch other apps and using the keyboard;
3. And then return the flutter app, its UI would be flashing.

**Expected results:** 

I think when switching between apps, they should have not effect on themselves, And it is a little bit weird for users operating the app.

**Actual results:**

In the flutter project, the screen would be flashing when Other Apps are using the keyboard and return back.

flutter version: v1.12.13 / 1.17.1

**Comment by TahaTesser** [comment] 2020-06-12 10:52
duplicate of https://github.com/flutter/flutter/issues/53565

**Closed by TahaTesser** 2020-06-12 10:52 UTC
