### ISSUE TITLE
Failed Assertion: 'hasSize'

### ISSUE THREAD

**Issue by aayush-b17** [flutter/flutter#65677] opened 2020-09-12 04:24 UTC
I am making a flutter app and while running a scrollable page, I see a white screen on the emulator. I do not know what it is. 

The main thing I see is Failed Assertion: hasSize

**Comment by e-e** [comment] 2020-09-12 06:02
I am also getting this. Similar case, I am trying to use a `ListView.builder()`, and I am getting
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderViewport#a94aa NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1702 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ListView file:///PATH/TO/PROJECT/lib/PATH/TO/FILE.dart:33:31
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1702:12)
#3      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1359:26)
#4      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
#5      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
#6      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
```

**Comment by iapicca** [comment] 2020-09-12 09:32
@aayush-b17 @e-e 
the issue might depend from your app implementation rather than being a bug with flutter,

if you are asking for assistance on your personal code, consider asking a question on stackoverflow.com instead

if you believe the error is caused by a bug in flutter
please provide your `flutter doctor` and a minimal reproducible code sample

**Comment by PixelToast** [comment] 2020-09-12 11:19
`Failed Assertion: hasSize` errors are an unfortunate side-effect of an exception being thrown during layout, I'm not sure if there is an open issue about handling it more gracefully.

@aayush-b17 When reporting bugs please make sure you post the first full error message you see in the console, not any secondary exceptions that happen afterwards.

**Comment by e-e** [comment] 2020-09-12 16:54
@iapicca the reason I posted here and not to stackoverflow was because the error message explicitly says to do so.

**Comment by Zazo032** [comment] 2020-09-12 17:11
This is probably fixed by adding `shrinkWrap: true,` to the scrollable widget

**Comment by e-e** [comment] 2020-09-12 22:54
@Zazo032 this solved the issue for me, thank you.

**Comment by shinsenter** [comment] 2020-10-06 06:16
Same problem with SingleChildScrollView (no way to add `shrinkWrap: true,`).

**Comment by PixelToast** [comment] 2020-10-06 06:47
Unfortunately without more information, the team cannot move forward with the original issue posted by @aayush-b17

If anyone else hits a similar assertion please file a new issue containing full debug logs and a minimal reproducible example

**Closed by PixelToast** 2020-10-06 06:47 UTC
Labels: waiting for customer response
