### ISSUE TITLE
[integration_test] Enable screenshots for iOS / Android

### ISSUE THREAD

**Issue by smkhalsa** [flutter/flutter#73596] opened 2021-01-08 20:22 UTC
It seems that you can [only](https://github.com/flutter/flutter/blob/87746c767408e3936093f338f9427e9b3ae4bfa7/packages/integration_test/example/integration_test/extended_test.dart#L7) take screenshots using the web platform at the moment.

**Comment by darshankawar** [comment] 2021-01-11 07:46
Closing this as duplicate of https://github.com/flutter/flutter/issues/51890

**Closed by darshankawar** 2021-01-11 07:46 UTC
