### ISSUE TITLE
API documentation text has accessibility problems

### ISSUE THREAD

**Issue by awulkan** [flutter/flutter#47849] opened 2019-12-26 20:23 UTC
## Use case

Some parts of the documentation has extremely thin text, which is very hard to read, even if you don't have bad eyesight. The text is only one pixel thick, and blends in with the white background.

Here's two examples ([taken from here](https://api.flutter.dev/flutter/cupertino/CupertinoNavigationBar-class.html)) where the first two methods are just fine, but the ones below are very hard to read.

**Example 1:**
![Example1](https://i.imgur.com/iwjAfLR.png)

**Example 2:**
![Example2](https://i.imgur.com/4lHv6Z8.png)

I find it painstakingly difficult to read through these docs, and I can't imagine what people with worse monitors or eyesight feels about it.

## Proposal

Make the font thicker and use something else to indicate the difference, such as colors, icons, emphasis, or something else.

**Comment by shihaohong** [comment] 2019-12-26 21:57
This is a duplicate of https://github.com/flutter/flutter/issues/47796/. Could you add a thumbs up emoji there to the first comment? We use the number of thumbs up emojis to help determine the priority of issues.

I'll close this issue in favor of the existing one

**Closed by shihaohong** 2019-12-26 21:57 UTC
