### ISSUE TITLE
[path_provider] PathProviderPlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by l1z0b** [flutter/flutter#93389] opened 2021-11-10 10:45 UTC
When I compile the app I get this warning:

`Note: /Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.6/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.`

## Steps to Reproduce

1. flutter clean
2. flutter pub get
3. flutter run

I am using `path_provider: ^2.0.6`, I would like to know if this issue can be resolved and if it could cause problems in the future.

**Flutter Doctor**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5 20G71 darwin-x64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)

**Comment by mamuseferha** [comment] 2021-11-10 11:15
Hi @l1z0b, thank you for filing this issue.

I tested this on the latest master and stable channel with `path_provider 2.0.6` and the issue is reproducible. They will not cause problems for your project as they are just deprecation warnings from the plugin itself. 

<details>
<summary>logs</summary>

```bash
Users/flo/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.6/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java:165: warning: [unchecked] unchecked call to getConstructor(Class<?>...) as a member of the raw type Class
          methodChannelClass.getConstructor(
                                           ^

  where T is a type-variable:
    T extends Object declared in class Class
/Users/flo/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.6/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java:165: warning: [unchecked] unchecked conversion
          methodChannelClass.getConstructor(
                                           ^
  required: Constructor<MethodChannel>
  found:    Constructor

2 warnings

```
</details>
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 98CBBFB1-4069-4A28-B7F7-138911ACBE72 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 2.6.0-12.0.pre.670, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.670 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 858a328712 (2 hours ago), 2021-11-09 22:22:14 -0800
    • Engine revision 76bf5a1ad0
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 98CBBFB1-4069-4A28-B7F7-138911ACBE72 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by stuartmorgan** [comment] 2021-11-11 21:26
> they are just deprecation warnings from the plugin itself

This is not a deprecation warning, it's a warning about type handling (likely due to casting of values from method channels).

**Comment by cmedamine** [comment] 2021-11-12 16:18
Same issue

**Comment by MohamedTarek7** [comment] 2021-11-14 18:39
Same issue:

> Note: C:\Users\username\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.6\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.

**Comment by stuartmorgan** [comment] 2021-11-14 19:35
We're aware that this issue exists; we don't need additional confirmations. It's a harmless warning.

**Comment by TheFabbiusCorp** [comment] 2021-12-10 22:04
Yeah, and it's annoying and it's **red**, which diverts the developer's attention to futile matters and makes them lose focus of central topics. Red is meant for errors 🚨, not warnings ⚠.

BTW, it's still present in release 2.0.8 😔.

**Comment by stuartmorgan** [comment] 2021-12-10 23:02
> Yeah, and it's annoying and it's **red**, which diverts the developer's attention to futile matters and makes them lose focus of central topics.

Which is why it's an open issue, tracking the need to fix it. PRs are welcome from anyone who wants to accelerate the process of getting it fixed.

**Comment by tayfunuyar** [comment] 2021-12-11 16:44
Hi guys,
You can solve this problem use with multiDexEnabled in project/android/app/build.gradle
````
defaultConfig {
      ......
       multiDexEnabled true
   }
````

**Comment by Harsh223** [comment] 2021-12-14 02:39
> Hi guys, You can solve this problem use with multiDexEnabled in project/android/app/build.gradle
> 
> ```
> defaultConfig {
>       ......
>        multiDexEnabled true
>    }
> ```

Didn't work for me :(

**Comment by shareef-dweikat** [comment] 2021-12-14 17:14
Having same issue.

**Comment by ZahraVe** [comment] 2022-02-24 10:34
I am facing with same warning and not able to  run in profile mode on android devices. Is this warning might cause issue for runnimg in profile mode? I have tried many ways to solve profiling issue like `flutter clean` flutter upgrade` flutter pub upgrade` flutter pub cache repair` , .... still cannot run in profile mode!

**Comment by realnihal** [comment] 2022-02-24 12:52
It's still there in version 2.10.1, and its still red lol

**Comment by HDEVCODER** [comment] 2022-03-03 17:36
It's still there in version 2.10.3, and its still red lol

**Comment by HDEVCODER** [comment] 2022-03-03 17:37
just do build again it disappear

**Comment by HDEVCODER** [comment] 2022-03-03 17:37
or https://stackoverflow.com/questions/61702748/note-recompile-with-xlintdeprecation-for-details-solved

**Comment by seenai88** [comment] 2022-04-01 00:40
version 2.0.12 has same issue. annoying

**Comment by harguus** [comment] 2022-04-18 19:28
I don't know if they solved it, but I managed to solve it by adding the latest version of path_provider to the dependency list in pubspec.yaml and it solved it for me.
path_provider: ^2.0.9

**Comment by Mudathir-Albany** [comment] 2022-04-21 16:42
Is it really harmless?

Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.12\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by camsim99** [comment] 2022-04-28 22:58
Fixed with https://github.com/flutter/plugins/pull/5267.

**Closed by camsim99** 2022-04-28 22:58 UTC
Labels: platform-android, plugin, p: path_provider, passed secondary triage, has reproducible steps, P5, found in release: 2.5, found in release: 2.6
