### ISSUE TITLE
[android] Problem with key Select

### ISSUE THREAD

**Issue by Aksiys** [flutter/flutter#79257] opened 2021-03-29 09:12 UTC
I have an android box with a remote control. When I click on the OK / Select button, an exception occurs:
```
The following assertion was thrown during a platform message callback:
 Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
 RawKeyDownEvent#e2365(logicalKey: LogicalKeyboardKey#70077(keyId: "0x100070077", keyLabel: "",
debugName: "Select"), physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName:
"Control Right")) and its data: RawKeyEventDataAndroid(keyLabel:  flags: 8, codePoint: 0, keyCode:
 23, scanCode: 97, metaState: 0, modifiers down: {})
 
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 626 pos 12: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

```

flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.13.6 17G14042 darwin-x64, locale ru-RU)
    • Flutter version 2.0.3 at /Users/test/flutter
    • Framework revision 4d7946a68d (10 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/test/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Xcode 10.1.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0
```

**Comment by pedromassangocode** [comment] 2021-03-29 10:59
Hi @Aksiys 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by Aksiys** [comment] 2021-03-29 11:36
> a minimal complete reproducible code sample?


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: Center(
          child: IconButton(
            icon: const Icon(Icons.replay, size: 35.0),
            onPressed: () => print('test'),
          ),
        ),
      ),
    );
  }

**Comment by pedromassangocode** [comment] 2021-03-29 14:14
Hi @Aksiys 
I cannot reproduce this issue with the code you provided. Tested on dev and stable channel.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: Center(
          child: IconButton(
            icon: const Icon(Icons.replay, size: 35.0),
            onPressed: () => print('test'),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by Aksiys** [comment] 2021-03-30 04:59
> Hi @Aksiys
> I cannot reproduce this issue with the code you provided. Tested on dev and stable channel.

Hi!
I think it's the device. For some keys, the RawKeyDownEvent does not come, only the RawKeyUpEvent. One of them is Select. But I don't know what it depends on.

On other devices with the same code, I have no problem.

**Comment by pedromassangocode** [comment] 2021-03-30 07:01
Please provide information about your device.

**Comment by Aksiys** [comment] 2021-03-30 07:27
> Please provide information about your device.

<details>
  <summary>getprop</summary>

[camera.disable_zsl_mode]: [1]
[config.disable_bluetooth]: [true]
[dalvik.vm.appimageformat]: [lz4]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.heapgrowthlimit]: [192m]
[dalvik.vm.heapmaxfree]: [8m]
[dalvik.vm.heapminfree]: [512k]
[dalvik.vm.heapsize]: [512m]
[dalvik.vm.heapstartsize]: [16m]
[dalvik.vm.heaptargetutilization]: [0.75]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[dalvik.vm.isa.arm.features]: [default]
[dalvik.vm.isa.arm.variant]: [cortex-a9]
[dalvik.vm.lockprof.threshold]: [500]
[dalvik.vm.stack-trace-file]: [/data/anr/traces.txt]
[dalvik.vm.usejit]: [true]
[dalvik.vm.usejitprofiles]: [true]
[debug.atrace.tags.enableflags]: [0]
[debug.force_rtl]: [0]
[debug.hwui.render_dirty_regions]: [false]
[debug.sf.latch_unsignaled]: [1]
[dev.bootcomplete]: [1]
[drm.service.enable]: [true]
[drm.service.enabled]: [1]
[init.svc.accelerateboot]: [stopped]
[init.svc.adbd]: [running]
[init.svc.audioserver]: [running]
[init.svc.bcmdl]: [stopped]
[init.svc.bootanim]: [stopped]
[init.svc.cameraserver]: [running]
[init.svc.console]: [running]
[init.svc.daemonsu]: [stopped]
[init.svc.debuggerd]: [running]
[init.svc.drm]: [running]
[init.svc.gatekeeperd]: [running]
[init.svc.hdcp_tx22]: [stopped]
[init.svc.hdmi_cec]: [running]
[init.svc.healthd]: [running]
[init.svc.imageserver]: [running]
[init.svc.installd]: [running]
[init.svc.keystore]: [running]
[init.svc.lmkd]: [running]
[init.svc.logd]: [running]
[init.svc.logd-reinit]: [stopped]
[init.svc.media]: [running]
[init.svc.mediacodec]: [running]
[init.svc.mediadrm]: [running]
[init.svc.mediaextractor]: [running]
[init.svc.netd]: [running]
[init.svc.perfprofd]: [running]
[init.svc.pppoe_wrapper]: [running]
[init.svc.preinstall]: [stopped]
[init.svc.remote_cfg]: [stopped]
[init.svc.remotecfg]: [stopped]
[init.svc.rtl_supplicant]: [running]
[init.svc.servicemanager]: [running]
[init.svc.surfaceflinger]: [running]
[init.svc.system_control]: [running]
[init.svc.ueventd]: [running]
[init.svc.usbpm]: [restarting]
[init.svc.vold]: [running]
[init.svc.zygote]: [running]
[libplayer.livets.softdemux]: [1]
[libplayer.netts.recalcpts]: [1]
[log.tag.WifiHAL]: [D]
[logd.logpersistd.enable]: [true]
[mbx.hdmiin.switchfull]: [false]
[mbx.hdmiin.videolayer]: [false]
[media.amplayer.dropwaitxms]: [100]
[media.amplayer.dsource4local]: [1]
[media.amplayer.enable]: [true]
[media.amplayer.enable-acodecs]: [ac3,eac3,rm,dts]
[media.amplayer.seekkeyframe]: [true]
[media.amplayer.thumbnail]: [true]
[media.amsuperplayer.defplayer]: [PV_PLAYER]
[media.amsuperplayer.enable]: [true]
[media.amsuperplayer.m4aplayer]: [STAGEFRIGHT_PLAYER]
[media.arm.audio.decoder]: [ape,flac,dts,ac3,eac3,wma,wmapro,mp3,aac,vorbis,raac,cook,amr,pcm,adpcm,aac_latm,rm]
[media.bootplayer.osdwithvideo]: [1]
[media.decoder.vfm.defmap]: [decoder ppmgr deinterlace amvideo]
[media.decoder.vfm.drmmap]: [decoder amvideo]
[media.html5videowin.enable]: [1]
[media.libplayer.curlenable]: [true]
[media.libplayer.modules]: [vhls_mod,dash_mod,curl_mod,prhls_mod,vm_mod,bluray_mod]
[media.libplayer.seek.fwdsearch]: [1]
[media.omx.display_mode]: [1]
[media.wfd.use-pcm-audio]: [false]
[media.wfd.video-bitrate]: [2000000]
[media.wfd.videoframerate]: [24]
[media.wfd.videoresolution-group]: [0]
[media.wfd.videoresolution-type]: [1]
[net.bt.name]: [Android]
[net.change]: [net.dns2]
[net.hostname]: [android-f478dbcde6ad5508]
[net.qtaguid_enabled]: [1]
[net.tcp.default_init_rwnd]: [60]
[net.tethering.noprovisioning]: [true]
[persist.fw.force_adoptable]: [true]
[persist.logd.logpersistd]: []
[persist.sys.app.rotation]: [middle_port]
[persist.sys.dalvik.vm.lib.2]: [libart.so]
[persist.sys.dts.edid]: [false]
[persist.sys.hdmi.keep_awake]: [false]
[persist.sys.hdr.state]: [2]
[persist.sys.locale]: [ru-RU]
[persist.sys.profiler_ms]: [0]
[persist.sys.sdr.state]: [0]
[persist.sys.timezone]: [Europe/Athens]
[persist.sys.usb.config]: [adb]
[persist.sys.webview.vmsize]: [104857600]
[pm.dexopt.ab-ota]: [speed-profile]
[pm.dexopt.bg-dexopt]: [speed-profile]
[pm.dexopt.boot]: [verify-profile]
[pm.dexopt.core-app]: [speed]
[pm.dexopt.first-boot]: [interpret-only]
[pm.dexopt.forced-dexopt]: [speed]
[pm.dexopt.install]: [interpret-only]
[pm.dexopt.nsys-library]: [speed]
[pm.dexopt.shared-apk]: [speed]
[ro.adb.secure]: [1]
[ro.allow.mock.location]: [0]
[ro.app.optimization]: [true]
[ro.audio.mapvalue]: [0,0,0,0]
[ro.autoconnectbt.btclass]: [50c]
[ro.autoconnectbt.isneed]: [false]
[ro.autoconnectbt.macprefix]: [00:CD:FF]
[ro.autoconnectbt.nameprefix]: [Amlogic_RC]
[ro.baseband]: [unknown]
[ro.board.platform]: [gxl]
[ro.boot.data_mounted]: [true]
[ro.boot.firstboot]: [0]
[ro.boot.hardware]: [amlogic]
[ro.boot.selinux]: [permissive]
[ro.boot.slot_suffix]: [_a]
[ro.bootimage.build.date]: [2019年 06月 01日 星期六 10:24:22 CST]
[ro.bootimage.build.date.utc]: [1559355862]
[ro.bootimage.build.fingerprint]: [Amlogic/ChitramMini/ChitramMini:7.1.2/NHG47L/root:userdebug/test-keys]
[ro.bootloader]: [unknown]
[ro.bootmode]: [unknown]
[ro.build.characteristics]: [mbx,nosdcard]
[ro.build.date]: [2019年 06月 01日 星期六 10:24:22 CST]
[ro.build.date.utc]: [1559355862]
[ro.build.description]: [ChitramMini-userdebug 7.1.2 NHG47L root test-keys]
[ro.build.display.id]: [20190601.10:26]
[ro.build.fingerprint]: [Amlogic/ChitramMini/ChitramMini:7.1.2/NHG47L/root:userdebug/test-keys]
[ro.build.flavor]: [ChitramMini-userdebug]
[ro.build.host]: [yxt001-S2600JF]
[ro.build.id]: [NHG47L]
[ro.build.product]: [ChitramMini]
[ro.build.tags]: [test-keys]
[ro.build.type]: [userdebug]
[ro.build.user]: [yxt001]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [root]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [7.1.2]
[ro.build.version.sdk]: [25]
[ro.build.version.security_patch]: [2017-12-01]
[ro.camera.preview.LimitedRate]: [1280x720x30,640x480x30,320x240x28]
[ro.camera.preview.MaxSize]: [1280x720]
[ro.camera.preview.UseMJPEG]: [1]
[ro.carrier]: [unknown]
[ro.com.android.dateformat]: [MM-dd-yyyy]
[ro.config.alarm_alert]: [Alarm_Classic.ogg]
[ro.config.notification_sound]: [pixiedust.ogg]
[ro.config.ringtone]: [Ring_Synth_04.ogg]
[ro.config.wallpaper]: [/system/etc/default_wallpaper.png]
[ro.crypto.fuse_sdcard]: [true]
[ro.crypto.state]: [unencrypted]
[ro.dalvik.vm.native.bridge]: [0]
[ro.debuggable]: [1]
[ro.device_owner]: [false]
[ro.firstboot]: [0]
[ro.fota.app]: [5]
[ro.fota.device]: [ChitramMini]
[ro.fota.id]: [mac]
[ro.fota.oem]: [amediatech905X_7.1]
[ro.fota.platform]: [Amlogic_S905X_7.1]
[ro.fota.type]: [box]
[ro.fota.version]: [20190601.10:26_20190601-1026]
[ro.hardware]: [amlogic]
[ro.hdmi.device_type]: [4]
[ro.hwui.layer_cache_size]: [15.0f]
[ro.hwui.texture_cache_size]: [18.0f]
[ro.is.ChitramMini]: [true]
[ro.net.pppoe]: [true]
[ro.opengles.version]: [131072]
[ro.platform.disable.audiorawout]: [false]
[ro.platform.has.down_power]: [true]
[ro.platform.has.mbxuimode]: [true]
[ro.platform.has.pppoe]: [true]
[ro.platform.has.realoutputmode]: [true]
[ro.platform.keepbackground.app]: [com.droidlogic.PPPoE]
[ro.platform.support.dolby]: [true]
[ro.platform.support.dts]: [true]
[ro.platform.support.over.4k30]: [false]
[ro.product.board]: [ChitramMini]
[ro.product.brand]: [Amlogic]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.device]: [ChitramMini]
[ro.product.firmware]: [00502001]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Amlogic]
[ro.product.model]: [ChitramMini]
[ro.product.name]: [ChitramMini]
[ro.radio.noril]: [false]
[ro.revision]: [0]
[ro.runtime.firstboot]: [1420070435299]
[ro.secure]: [1]
[ro.serialno]: []
[ro.sf.full_activemode]: [false]
[ro.sf.lcd_density]: [160]
[ro.sys.hdmiin.enable]: [true]
[ro.testapk.tag]: [true]
[ro.ubootenv.varible.prefix]: [ubootenv.var]
[ro.wifi.channels]: [11]
[ro.zygote]: [zygote32]
[rw.camera.usb.faceback]: [true]
[security.perf_harden]: [1]
[selinux.reload_policy]: [1]
[service.adb.tcp.port]: [5555]
[service.bootanim.exit]: [1]
[service.bootvideo]: [0]
[supolicy.loaded]: [1]
[sys.boot_completed]: [1]
[sys.fb.bits]: [32]
[sys.ignore.inativecec]: [true]
[sys.logbootcomplete]: [1]
[sys.open.deepcolor]: [true]
[sys.sysctl.extra_free_kbytes]: [10800]
[sys.sysctl.tcp_def_init_rwnd]: [60]
[sys.usb.config]: [adb]
[sys.usb.configfs]: [0]
[sys.usb.state]: [adb]
[sys.wifi.first_boot]: [0]
[tv.launcher.firsttime.launch]: [false]
[ubootenv.var.1080i_h]: []
[ubootenv.var.1080i_w]: []
[ubootenv.var.1080i_x]: []
[ubootenv.var.1080i_y]: []
[ubootenv.var.1080p_h]: []
[ubootenv.var.1080p_w]: []
[ubootenv.var.1080p_x]: []
[ubootenv.var.1080p_y]: []
[ubootenv.var.480i_h]: []
[ubootenv.var.480i_w]: []
[ubootenv.var.480i_x]: []
[ubootenv.var.480i_y]: []
[ubootenv.var.480p_h]: []
[ubootenv.var.480p_w]: []
[ubootenv.var.480p_x]: []
[ubootenv.var.480p_y]: []
[ubootenv.var.4k2k24hz_h]: []
[ubootenv.var.4k2k24hz_w]: []
[ubootenv.var.4k2k24hz_x]: []
[ubootenv.var.4k2k24hz_y]: []
[ubootenv.var.4k2k25hz_h]: []
[ubootenv.var.4k2k25hz_w]: []
[ubootenv.var.4k2k25hz_x]: []
[ubootenv.var.4k2k25hz_y]: []
[ubootenv.var.4k2k30hz_h]: []
[ubootenv.var.4k2k30hz_w]: []
[ubootenv.var.4k2k30hz_x]: []
[ubootenv.var.4k2k30hz_y]: []
[ubootenv.var.4k2ksmpte_h]: []
[ubootenv.var.4k2ksmpte_w]: []
[ubootenv.var.4k2ksmpte_x]: []
[ubootenv.var.4k2ksmpte_y]: []
[ubootenv.var.576i_h]: []
[ubootenv.var.576i_w]: []
[ubootenv.var.576i_x]: []
[ubootenv.var.576i_y]: []
[ubootenv.var.576p_h]: []
[ubootenv.var.576p_w]: []
[ubootenv.var.576p_x]: []
[ubootenv.var.576p_y]: []
[ubootenv.var.720p_h]: []
[ubootenv.var.720p_w]: []
[ubootenv.var.720p_x]: []
[ubootenv.var.720p_y]: []
[ubootenv.var.cecconfig]: []
[ubootenv.var.colorattribute]: []
[ubootenv.var.cvbsmode]: []
[ubootenv.var.defaulttvfrequency]: []
[ubootenv.var.digitaudiooutput]: []
[ubootenv.var.disp.fromleft]: []
[ubootenv.var.edid.crcvalue]: []
[ubootenv.var.has.accelerometer]: []
[ubootenv.var.hdmimode]: []
[ubootenv.var.is.bestmode]: []
[ubootenv.var.outputmode]: []
[vold.has_adoptable]: [0]
[vold.post_fs_data_done]: [1]
[wifi.interface]: [wlan0]
[wlan.driver.status]: [ok]
</details>

**Comment by pedromassangocode** [comment] 2021-03-30 10:13
Please make sure your device is connected and then run `flutter run doctor -v` and provide the logs.

**Comment by pedromassangocode** [comment] 2021-04-21 09:12
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:12 UTC
Labels: in triage, waiting for customer response
