### ISSUE TITLE
fontvariatiomsettings not found , ttc index not found

### ISSUE THREAD

**Issue by Atominac** [flutter/flutter#27726] opened 2019-02-09 15:37 UTC
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\my work space\Flutter\conexo\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:101: error: resource android:attr/fontVariationSettings not found.
  D:\my work space\Flutter\conexo\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:101: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by zoechi** [comment] 2019-02-11 07:40
Duplicate of #27106

**Closed by zoechi** 2019-02-11 07:40 UTC

**Comment by Atominac** [comment] 2019-02-19 09:50
flutter_local_notifications:
this was creating the issue
i used the older version and it worked fine

older version
  flutter_local_notifications: 0.4.4+1
