### ISSUE TITLE
List<Icon> can not be assigned to the type Widget

### ISSUE THREAD

**Issue by zatnuviz** [flutter/flutter#81198] opened 2021-04-26 12:56 UTC
The issue is that i am not able to assign a Widget made from a list to a Row in flutter, I tried different ways but cant find an answer

   starsGan, 

that is the line that cant be called back, and shows me an error 

List<Icon> can not be assigned to the type Widget, i changed to widget and still the same
List<Widget> can not be assigned to the type Widget,

when i make just one object it gets called back, but when used the list cant, any help, thanks in advance

```import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.orange,
      ),
      home: SafeArea(
        child: Scaffold(
          backgroundColor: Colors.orange,
          // appBar: AppBar(title: Text('Let us Know')),
          body: Padding(
            padding: EdgeInsets.symmetric(horizontal: 10.0),
            child: CustomScrollView(
              slivers: [
                SliverAppBar(
                  backgroundColor: Colors.deepOrange[50],
                  title: Text('Let us Know'),
                  centerTitle: true,
                  floating: true,
                ),
                SliverFixedExtentList(
                  itemExtent: 800,
                  delegate: SliverChildBuilderDelegate(
                    (BuildContext context, int index) {
                      if (index > 0) return null;
                      // or we can do this // childCount: 0,
                      return QuizApp();
                    },
                  ),
                ),
              ],
            ),
          ),
          bottomNavigationBar: BottomAppBar(
            shape: CircularNotchedRectangle(),
            notchMargin: 4.0,
            child: new Row(
              children: <Widget>[
                SizedBox(width: 8.00),
                Text('My Score'),
                // for a button do // IconButton(icon: Icon(Icons.star), onPressed: () {},),
           

THE PROBLEM IS HERE >     starsGan, 

              ],
            ),
          ),
          floatingActionButtonLocation: FloatingActionButtonLocation.endDocked,
          floatingActionButton: FloatingActionButton(
            child: const Icon(Icons.add),
            onPressed: () {},
          ),
        ),
      ),
    );
  }
}

class QuizApp extends StatefulWidget {
  @override
  _QuizAppState createState() => _QuizAppState();
}

Flexible questionBank(
    {required String questionText, required int questionNumber}) {
  return Flexible(
    fit: FlexFit.loose,
    child: Card(
      child: Column(
        children: <Widget>[
          ListTile(
            trailing: Icon(Icons.contact_support_outlined),
            title: Text('$questionText'),
            subtitle: Text('Question $questionNumber'),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: <Widget>[
              TextButton(
                child: const Text('Yes'),
                onPressed: () {/* ... */},
              ),
              const SizedBox(width: 8),
              TextButton(
                child: const Text('No'),
                onPressed: () {/* ... */},
              ),
              const SizedBox(width: 8),
            ],
          ),
        ],
      ),
    ),
  );
}

List<Icon> starsGan = [Icon(Icons.star),Icon(Icons.cancel)];
// Same as before // final starsGan = [Icon(Icons.star),Icon(Icons.cancel)];


class _QuizAppState extends State<QuizApp> {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        questionBank(questionText: 'Are you Married', questionNumber: 1),
        questionBank(questionText: 'Do you like apples', questionNumber: 2),
        questionBank(questionText: 'Do you Study Hard', questionNumber: 3),
        questionBank(questionText: 'Are you brave', questionNumber: 4),
        questionBank(questionText: 'Do you want to learn to meditate', questionNumber: 5),
        questionBank(questionText: 'Do you love life and the people around you', questionNumber: 6),
      ],
    );
  }
}
```

**Comment by stuartmorgan** [comment] 2021-04-26 15:09
For help with your own code, see the discussion and help resources at https://flutter.dev/community

Closing, as this is not a bug; the error message here is correct.

**Closed by stuartmorgan** 2021-04-26 15:09 UTC

**Comment by zatnuviz** [comment] 2021-04-26 17:38
thanks a lot
