### ISSUE TITLE
Custom Managed KeepAlive can no longer call globalToLocal

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#60565] opened 2020-06-29 23:04 UTC
We manage our own KeepAlives in a SliverFixedExtentList due to custom rules around dragging and dropping and needing certain elements to KeepAlive when dragged but well off the viewport. [This PR](https://github.com/flutter/flutter/pull/60129) introduces a Keep Alive Bucket tracked by the SliverMultiBoxAdapter which doesn't account for our custom KeepAlives, which results in a degenerate matrix from RenderBox.globalToLocal (and more specifically getTransformTo).

Specifically, these changes introduce the issue:
https://github.com/flutter/flutter/commit/62378a3755e0cd7cbc20f2c33a068cec51d92dd1#diff-52c4178347c79d5992e975d960759110R587-R596

**Comment by chunhtai** [comment] 2020-07-06 22:41
do you have a mini repo that demonstrate the case? I am not quite sure i understand the use case.

**Comment by mjohnsullivan** [comment] 2020-07-08 02:01
I've put a small example together here: https://gist.github.com/mjohnsullivan/b552f03f013e88b8f9b9956a1224062b

To demonstrate, compile and run with Flutter master on a Mac. (This will let you use the scroll wheel to scroll the list while holding down the left button to start a drag on an item).

If you left-click on any item in the list other than 2, and move the mouse around, you'll see that the offset updates, calculated from ```getBox.globalToLocal(details.globalPosition)```. If you then use the mouse wheel to scroll the item off the screen, you'll see that the offset no longer updates, as it's been killed off, as expected.

If you left-click on item 2, and do the same thing, you'll see that when the item is off the screen, the offset sets to zero, but if you scroll the item back on the screen (whilst still holding down the mouse button), it will begin to update again once the item is visible.

This is due to the ```applyPaintTransform()``` function in ```silver_multi_box_adapter.dart```. It looks like when an item marked with keepAlive is being kept alive off-screen, the transform sets to zero. This causes the ```globalToLocal()``` call to fail as the matrix inversion fails.

This affects the use case where you want to drag an item in a list and drop it in a position that's outside the viewing area of where the dragged item is positioned in the list. Once the list scrolls and the item is off-screen, the position is lost as the offset is zero'd.

**Comment by chunhtai** [comment] 2020-07-08 22:55
This is a risky way of calculating the drag location even before the change. The globalToLocal depends on the scroll position of the child. and the scroll offset is not guaranteed to be correct when the child is in kept alive bucket. This only works if the children order and their sizes never changed.

I will suggest use column or a row if you want to build a reorderable list since it will always keep its children alive even if they are outside of the view port.

**Comment by mjohnsullivan** [comment] 2020-07-09 01:41
There may be cases where one might want the elements of a list to be virtualized, except for the ones marked for keep alive when they've been scrolled out of the viewport. We do this to ensure performance as we can have very large lists of items that can have elements dragged around them.

**Comment by mjohnsullivan** [comment] 2020-07-09 19:26
We've been playing around with ideas to get this working again on the master branch and come up with a solution that involves walking up the render tree to find the list so that we can then find a child that hasn't been recycled and call globalToLocal on that. It's a messy way of doing it, but it works:

https://gist.github.com/mjohnsullivan/63277aefd0e212cfd1628fe85488bc35

**Comment by luigi-rosso** [comment] 2020-07-09 19:46
Thanks for the suggestions @chunhtai. Like @mjohnsullivan mentioned, we really need a performant way to do this when the list is really large. It's common for our users to drag items from one end of the list to the other.

The fundamental thing we need to make this work is:
- The index of the row currently hovered (during a drag op) in the virtualized list.
-- Important that the list may be a SliverFixedExtentList so the index must be relative to that set, not the entire scrolling list.
- The offset within that row (how close to the top/bottom).

The solution @mjohnsullivan provided gives us that but we're wondering if you have better guidance. We'd rather implement something we know the framework is intended to support and will survive longer.

**Comment by chunhtai** [comment] 2020-07-10 17:06
@mjohnsullivan your example is actually a more reliable way to find the right child because we don't guarantee anything about children outside of the viewport. One thing i may do is assigning a global key to the SliverFixedExtentList and use it to get the renderObject directly.

**Comment by mjohnsullivan** [comment] 2020-07-10 19:37
That's great to know, thanks for looking it over.

**Comment by chunhtai** [comment] 2020-07-10 19:55
Closing this issue as work as intended. Feel free to reopen if you have further questions.

**Closed by chunhtai** 2020-07-10 19:55 UTC
Labels: customer: thrive, customer: web10, framework, platform-web
