### ISSUE TITLE
toString of the ErrorDescription instance not working properly in release mode 

### ISSUE THREAD

**Issue by mansurov1024** [flutter/flutter#105712] opened 2022-06-09 16:16 UTC
try {
      throw ErrorDescription("test error message");
    } catch(e) {
      print(e.toString());
      print("$e");
      print(e);
    }

In release mode on Android prints "Instance of ErrorDescription" while in debug mode prints 'test error message'.
At the same time **throw Exception** works fine in both modes.

**Comment by huycozy** [comment] 2022-06-10 05:09
Hi @mansurov1024

It works as intended, see:
https://github.com/flutter/flutter/blob/9d46e7800f287797d09c3a5e9f27d6489bb3ffe4/packages/flutter/lib/src/foundation/assertions.dart#L245

Closing this issue due to it's neither bugs or feature request. If you disagree about this, please drop a comment and I will reopen it.

**Closed by huycozy** 2022-06-10 05:09 UTC
Labels: in triage
