### ISSUE TITLE
[firebase_auth] FirebaseUser.reauthenticateWithCredential() throws { noSuchMethod: []('user') was called on null }

### ISSUE THREAD

**Issue by DawidBartniczak** [flutter/flutter#38424] opened 2019-08-13 11:25 UTC
## Info
* I'm using the latest version of firebase_auth plugin (0.14.0+1)
* Issue is present in version 0.12.0 and onward (probably introduced by [this](https://github.com/flutter/plugins/commit/533ee023b7b5aa52ece6643bb82d1dca20380818) commit)
* I've tried to change user's password but got `ERROR_REQUIRES_RECENT_LOGIN` so I've tried `reauthenticateWithCredential` but got `noSuchMethod: []('user') was called on null`
## Problematic Code
```
if (newPassword != newPasswordConfirm)
  throw AuthException('ERROR_PASSWORDS_DONT_MATCH', '');

AuthCredential credential = EmailAuthProvider.getCredential(
  email: user.email,
  password: oldPassword
);
await user.reauthenticateWithCredential(credential);

await user.updatePassword(newPassword);
```
## Error Log
```
I/flutter ( 5035): NoSuchMethodError: The method '[]' was called on null.
I/flutter ( 5035): Receiver: null
I/flutter ( 5035): Tried calling: []("user")
```
## Flutter Doctor
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale
    pl-PL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.0)
[✓] Connected device (1 available)
```

**Comment by Fallenstedt** [comment] 2019-08-14 15:57
Possibly related to #37681

**Comment by AndroidNils** [comment] 2019-08-16 18:33
Same Problem :(

**Comment by mrwwalmsley** [comment] 2019-08-21 04:02
Same problem as https://github.com/flutter/flutter/issues/37542

**Comment by BondarenkoStas** [comment] 2019-09-05 15:03
Duplicate of #37542

**Closed by BondarenkoStas** 2019-09-05 15:03 UTC
