### ISSUE TITLE
How to prevent auto scroll down on tab2 when user scroll down on tab1?

### ISSUE THREAD

**Issue by mesuutt** [flutter/flutter#27887] opened 2019-02-13 17:54 UTC
Hi, I am new to flutter and I have a problem that I couldn't solve.

I asked the question on [stackoverflow](https://stackoverflow.com/q/54647229/1027507) but I haven't found the solution. So I am asking at here. 

I created a screen using `SliverAppBar`, `SliverPersistentHeader`, `TabView` and `ListView`.

If I scroll down in tab1, tab2 scrolling down automatically. So If I swith to tab2, list not starting from first item. How can I prevent this?

Simplified build function content of screen:

```dart
return Scaffold(
  body: DefaultTabController(
    length: 2,
    child: NestedScrollView(
      headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
        return <Widget>[
          SliverAppBar(
            expandedHeight: 120.0,
            floating: false,
            forceElevated: innerBoxIsScrolled,
            backgroundColor: Colors.green,
            pinned: true,
            flexibleSpace: FlexibleSpaceBar(
              collapseMode: CollapseMode.pin,
              centerTitle: true,
              title: Text(
                spaceBarFlatName,
                style: TextStyle(color: config.topBarTextColor),
                textAlign: TextAlign.left,
                overflow: TextOverflow.ellipsis,
                softWrap: true,
                maxLines: 1,
              ),
              background: Container(
                alignment: Alignment.topCenter,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    Row(
                      children: <Widget>[
                        Text(
                          '${formatMoney(periodBalance.abs())}',
                          style: TextStyle(
                              color: config.topBarTextColor,
                              fontSize: 30.0,
                              fontWeight: FontWeight.bold),
                        ),
                        Icon(FontAwesomeIcons.liraSign,
                            color: textColor, size: 24.0),
                        Text(" (Alacak)",
                          style: TextStyle(
                            color: config.topBarTextColor,
                            fontSize: 20.0,
                          ),
                        )
                      ],
                      mainAxisAlignment: MainAxisAlignment.center,
                    ),
                    Container(width: 0,height: 0)
                  ],
                ),
              ),
            ),
          ),
          SliverPersistentHeader(
            pinned: true,
            delegate: _SliverAppBarDelegate(
              TabBar(
                tabs: [
                  Tab(child: Text("Borçlarım"),
                  Tab(child: Text("Ödemelerim"),
                ],
              ),
            ),
          ),
        ];
      },
      body: TabBarView(
        children: [
          Container(
            child: ListView.builder(
                scrollDirection: Axis.vertical,
                shrinkWrap: true,
                itemCount: debits.length,
                //itemExtent: 1.0,
                itemBuilder: (context, index) {
                  return DebitCard(debits[index]);
                }),
          ),
          Container(
            child: ListView.builder(
                scrollDirection: Axis.vertical,
                shrinkWrap: true,
                itemCount: receipts.length,
                //itemExtent: 1.0,
                itemBuilder: (context, index) {
                  return ReceiptCard(receipts[index]);
                }),
          ),
        ]
      ),
    ),
  ),
);


```

**Initial state of the screen:**
<img src="https://user-images.githubusercontent.com/823338/52731908-f49a4f00-2fcf-11e9-81e6-adf3bba50754.jpeg" width="350">

**If I scroll tab1 shown as below:**
<img src="https://user-images.githubusercontent.com/823338/52731909-f532e580-2fcf-11e9-926c-912162595a2b.jpeg" width="350">

**Tab2 scrolling down automatically shown as below when I scroll tab1 which I don't want to be:**
<img src="https://user-images.githubusercontent.com/823338/52731910-f532e580-2fcf-11e9-9650-887993f0b626.jpeg" width="350">

I want when user switch to tab2, scroll should start in other words why tab2 scrolling automatically when I scroll on tab1?

------
```
$ flutter doctor -v

[✓] Flutter (Channel beta, v1.1.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.1.8 at /opt/flutter-sdk/flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /home/mesuutt/tmp/tools/idea-IU-182.4892.20
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
```

**Comment by zoechi** [comment] 2019-02-14 09:48
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by mesuutt** [comment] 2019-02-14 11:12
You can look at [this gist](https://gist.github.com/mesuutt/5d892bf0b5f3f0bbf36e19bda2d1a49d) for example code.

**Comment by zoechi** [comment] 2019-02-14 12:54
Similar to #19720

**Comment by zmtzawqlp** [comment] 2019-02-15 12:27
> You can look at [this gist](https://gist.github.com/mesuutt/5d892bf0b5f3f0bbf36e19bda2d1a49d) for example code.

you can try this to fix your problem https://pub.flutter-io.cn/packages/extended_nested_scroll_view

**Comment by zoechi** [comment] 2019-02-15 14:16
Does https://github.com/flutter/flutter/issues/27928#issuecomment-463662840 help?

**Comment by mesuutt** [comment] 2019-02-16 00:56
> To get rid of this you can have each tab bar be made of different Nested Scroll View instead of sharing a single one.

@zoechi I didn't understand how to use different `NestedScrollView` for tabs. Because there is a one `TabBar`.

**Comment by zoechi** [comment] 2019-02-20 13:59
@mesuutt please check again https://github.com/flutter/flutter/issues/27928#issuecomment-464998788

**Comment by mesuutt** [comment] 2019-02-21 13:54
@zoechi the example working but not same as my screen, I couldn't adapt the example to my screen. In my screen there is a sticky header and sticky app bar. 

@Kartik1607 can we adapt your [example](https://github.com/flutter/flutter/issues/27928#issuecomment-464998788) to [my screen](https://github.com/flutter/flutter/issues/27887#issuecomment-463589129)?

**Comment by Kartik1607** [comment] 2019-02-21 14:45
Hi, I'm out of station right now and don't have my laptop with me so can't run any code. If you have an image or a gif of your requirement I might be able to help through mobile and give some basic ideas or steps.

**Comment by arthurharutyunyan91** [comment] 2019-09-21 10:56
_scrollController = ScrollController();
    _tabController = TabController(vsync: this, length: 3)
      ..addListener(() => setState(() {
        _scrollController.jumpTo(_scrollController.position.minScrollExtent);
      }));

this will solve the problem

**Comment by patelkrunal78** [comment] 2019-10-05 15:24
Wrap your widget tree inside a SingleChildScrollView

body: SingleChildScrollView(
child: Stack(
children: <Widget>[
new Container(
decoration: BoxDecoration(
image: DecorationImage(...),
new Column(children: [
new Container(...),
new Container(...... ),
new Padding(
child: SizedBox(
child: RaisedButton(..),
),
....
...
); // Single child scroll view

Find At [Here](https://icetutor.com/question/how-to-scroll-page-in-flutter)

**Comment by shamnex** [comment] 2019-10-09 13:00
> _scrollController = ScrollController();
> _tabController = TabController(vsync: this, length: 3)
> ..addListener(() => setState(() {
> _scrollController.jumpTo(_scrollController.position.minScrollExtent);
> }));
> 
> this will solve the problem

Hey man, nice one! It partially solves the problem.
This will jump the `scrollController` back to the top, which works fine... but what if we want to maintain the previous scrollOffset?

**Comment by Piinks** [comment] 2020-01-23 23:48
This looks like a duplicate of #36419

**Comment by VladyslavBondarenko** [comment] 2020-04-03 14:43
@mesuutt 
Please follow up on https://github.com/flutter/flutter/issues/36419,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-04-03 14:43 UTC
Labels: d: stackoverflow, f: material design, f: scrolling, framework

**Comment by arthurharutyunyan91** [comment] 2020-04-03 15:10
> > _scrollController = ScrollController();
> > _tabController = TabController(vsync: this, length: 3)
> > ..addListener(() => setState(() {
> > _scrollController.jumpTo(_scrollController.position.minScrollExtent);
> > }));
> > this will solve the problem
> 
> Hey man, nice one! It partially solves the problem.
> This will jump the `scrollController` back to the top, which works fine... but what if we want to maintain the previous scrollOffset?

This is only for the case if you want to return to the top
