### ISSUE TITLE
How to reformat the layout when keyboard pops up.

### ISSUE THREAD

**Issue by TitikshaDaga** [flutter/flutter#11653] opened 2017-08-17 06:42 UTC
I have a login screen with 2 text fields and 2 buttons. Whenever I click on the text field key board pops up and  the screen is pushed up and a red box appears that hides my button and goes away when the key board is closed. How do I avoid the red box?Do I need to realign the layout whenever the screen is pushed up? If so how do I do it whenever the screen is pushed up?

**Comment by sethladd** [comment] 2017-08-17 16:59
Hi, thanks for the question! Do you happen to have a small sample that illustrates this issue? A small reproducible case?

**Comment by TitikshaDaga** [comment] 2017-08-18 04:07
This is the normal window.
![screenshot_2017-08-18-09-31-36-272_com yourcompany urmuv](https://user-images.githubusercontent.com/12954116/29443868-a0f8200e-83f8-11e7-9a27-e6ad463c1f1f.png)
This is what what happens when the keyboard pops up
![screenshot_2017-08-18-09-31-41-894_com yourcompany urmuv](https://user-images.githubusercontent.com/12954116/29443883-c274ac02-83f8-11e7-9641-e0a209ecc316.png)
the red box in the second pic is what i m talking about

**Comment by Hixie** [comment] 2017-08-18 16:14
What's happening is that your Column contains more stuff than you have room to display, so it's overflowing (and clipping). You could swap it out for a ListView or some such.

**Comment by TitikshaDaga** [comment] 2017-08-21 05:03
You are saying instead of a column I should use a ListView?

**Comment by Hixie** [comment] 2017-08-21 17:27
Depends what you want to have happen. What would you want to have your UI look like if the screen wasn't tall enough for everything in your dialog?

**Comment by Hixie** [comment] 2017-08-21 17:28
(e.g. turn the device on it's side then bring up the keyboard, what do you want to see?)

**Comment by TitikshaDaga** [comment] 2017-08-22 04:21
I just want that user should be able to see whatever he/she is typing. The way the layout is right now works for me. But the only problem is that red box that appears. That should go away.

**Comment by Hixie** [comment] 2017-08-22 04:26
If the screen was ~100 pixels less tall than your screenshot, when the keyboard comes up after the user taps the password field, the password field would no longer be visible. The red line is warning you of that.

Hence my question, what would you want it to look like?

If you want it to scroll, then yes I would recommend using a ListView instead of a Column.

By the way the red only appears in debug builds, when you release your app it won't be visible.

**Comment by TitikshaDaga** [comment] 2017-08-22 04:30
When the user taps on username field I want the user to see the username field and when the user types in password field then he/she should be able to see that.

**Comment by Hixie** [comment] 2017-08-22 05:29
Yeah, you definitely want it to be in a ListView. The actual scrolling to show the right thing in view won't work until we fix the last few parts of https://github.com/flutter/flutter/issues/10826#issuecomment-311220245.

**Comment by TitikshaDaga** [comment] 2017-08-22 05:32
Ok. let me try that.

**Comment by TitikshaDaga** [comment] 2017-08-22 05:43
No this doesn't work.I can't set the background nor is the screen pushed up.The parent element in this screen is stack.

**Comment by Hixie** [comment] 2017-08-23 18:08
Yeah, the screen won't push up properly until https://github.com/flutter/flutter/issues/10826#issuecomment-311220245 is fixed.

Not sure what you mean about the background though.

**Comment by TitikshaDaga** [comment] 2017-08-29 07:24
I meant that the faded background isn't visible

**Comment by ride4sun** [comment] 2018-01-14 21:07
Any plans to work on this?

**Comment by bregydoc** [comment] 2018-02-01 08:42
I'm trying this too.

**Comment by Hixie** [comment] 2018-03-12 02:50
As far as I can tell this is two issues, one is #7032, and the other is #10826.

Closing as a duplicate of those issues.

**Closed by Hixie** 2018-03-12 02:50 UTC
