### ISSUE TITLE
[go_router] Support double slash after schema for deep linking

### ISSUE THREAD

**Issue by KestasVenslauskas** [flutter/flutter#112071] opened 2022-09-21 15:09 UTC
I encountered some limitations where other SDK's require deepLinking schema to be as `"myApp://..."` with double slashes. But go_router works only with `"myApp:/..."` which I cannot use in other SDK's. 

## Use case
Do not ignore  paths with double slashes after schema.
So users won't be confused with it when acidentally adding double slashes.

## Proposal
`"myApp://..."` and `"myApp:/..."` should work the same.

**Comment by danagbemava-nc** [comment] 2022-09-22 08:54
Hi @KestasVenslauskas, I believe this should already be supported. Is there a particular issue you're running into when using double slashes?

**Comment by KestasVenslauskas** [comment] 2022-09-22 09:42
@danagbemava-nc So if I run `adb shell am start -d myApp:/screenA` on android app it opens the screenA route. Even if the app is force stopped... But if I run `adb shell am start -d myApp://screenA` nothing happens if the app is running already. And if the app is force closed then it only opens the app with initial route...

**Comment by danagbemava-nc** [comment] 2022-09-22 13:30
Hi @KestasVenslauskas, please provide a complete minimal reproducible code sample so that we can investigate this. 

Thank you

**Comment by KestasVenslauskas** [comment] 2022-09-23 09:04
@danagbemava-nc Here you go https://github.com/KestasVenslauskas/go-router-paths-issue

**Comment by danagbemava-nc** [comment] 2022-09-23 12:59
Hi @KestasVenslauskas, thanks for the repro. This is indeed a bug and I think it is a duplicate of https://github.com/flutter/flutter/issues/100624. Can you take a look at https://github.com/flutter/flutter/issues/100624 to see if my suspicion is correct?

**Closed** 2022-09-23 13:37 UTC
Labels: in triage
