### ISSUE TITLE
[url_launcher][mobile-web] Phone number and body fields are not always pre-populated in SMS app

### ISSUE THREAD

**Issue by pryshrm** [flutter/flutter#97564] opened 2022-02-01 06:02 UTC
I am trying to launch the default sms app from my flutter web app running on chrome/android device. The sms app does get launched but the phone number and body fields are not getting values from the uri. Here is my code:

```
Future<bool> launchSMS({required String phnumber, required String msg}) async {
  // Android 'sms:+39 348 060 888?body=hello%20there';
  String body = Uri.encodeComponent(msg);

  String androidPh = phnumber.replaceAll("(", "").replaceAll(")", "");
  String androiduri = 'sms:$androidPh?body=$body';

  String iosPh = phnumber.replaceAll("+", "00").replaceAll("(", "").replaceAll(")", ""); //'sms:0039-222-060-888?body=hello%20there';
  String iosuri = 'sms:$iosPh&body=$body';
  if(kIsWeb){
    if (await urllauncher.canLaunch(androiduri)) {
      print('launching uri $androiduri');
      return await urllauncher.launch(androiduri);
    } else {
      if (await urllauncher.canLaunch(iosuri)) {
        print('launching iosuri $iosuri');
        return await urllauncher.launch(iosuri);
      } else {
        return false;
      }
    }
  } else {
    if (Platform.isIOS) {
      print('launching iosuri $iosuri');
      if (await urllauncher.canLaunch(iosuri)) {
        return await urllauncher.launch(iosuri);
      } else {
        return false;
      }
    } else //if(Platform.isAndroid)
        {
      print('launching uri $androiduri');
      if (await urllauncher.canLaunch(androiduri)) {
        return await urllauncher.launch(androiduri);
      } else {
        return false;
      }
    }
  }
}

```

**Comment by danagbemava-nc** [comment] 2022-02-01 08:18
Please provide the output of `flutter doctor -v` as well as the version of `url_launcher` you're using. 

Thank you

**Comment by pryshrm** [comment] 2022-02-01 09:14
url_launcher: 6.0.18

C:\works\flutter\projects\uome_app>flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-IN)
    • Flutter version 2.8.1 at C:\flutter223
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\CEO\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.76

• No issues found!

C:\works\flutter\projects\uome_app>

**Comment by danagbemava-nc** [comment] 2022-02-01 11:51
Hi @pryshrm, I looked at your code sample and the issue is with how you're going about it. 
What you need to do is check the host os of the device the browser is on when you're on web and then from there use the appropriate formatted uri. 

I modified your sample a bit and in my tests the values were prepopulated in the SMS field. See sample below. You may need to tweak it to suit your code base. 

<details>
<summary>code sample</summary>

```dart
import 'dart:html' as html;
import 'dart:io' as io;

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart' as urllauncher;

void main(List<String> args) {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TexspanTap(),
    );
  }
}

class TexspanTap extends StatefulWidget {
  @override
  _TexspanTapState createState() => _TexspanTapState();
}

class _TexspanTapState extends State<TexspanTap> {
  @override
  void initState() {
    // _editingcontroller.text = "dghali";
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            children: [
              TextButton(
                onPressed: () async {
                  await launchSMS(
                    phnumber: '+39348060888',
                    msg: 'some message',
                  );
                },
                child: Text('Launch'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  bool _isIOS() {
    final userAgent = html.window.navigator.userAgent.toString().toLowerCase();
    return userAgent.contains('iphone') || userAgent.contains('ipad');
  }

  bool _isAndroid() {
    final userAgent = html.window.navigator.userAgent.toString().toLowerCase();
    return userAgent.contains('android');
  }

  Future<bool> launchSMS(
      {required String phnumber, required String msg}) async {
    // Android 'sms:+39 348 060 888?body=hello%20there';
    String body = Uri.encodeComponent(msg);

    String androidPh = phnumber.replaceAll("(", "").replaceAll(")", "");
    String androiduri = 'sms:$androidPh?body=$body';

    String iosPh = phnumber
        .replaceAll("+", "00")
        .replaceAll("(", "")
        .replaceAll(")", ""); //'sms:0039-222-060-888?body=hello%20there';
    String iosuri = 'sms:$iosPh&body=$body';
    if (kIsWeb) {
      if (_isIOS()) {
        return await urllauncher.launch(iosuri);
      } else if (_isAndroid()) {
        return await urllauncher.launch(androiduri);
      } else {
        return false;
      }
      // if (await urllauncher.canLaunch(iosuri)) {
      //   print('launching ios uri $iosuri');
      //   return await urllauncher.launch(iosuri);
      // } else {
      //   if (await urllauncher.canLaunch(androiduri)) {
      //     print('launching android $androiduri');
      //     return await urllauncher.launch(androiduri);
      //   } else {
      //     return false;
      //   }
      // }
    } else {
      if (io.Platform.isIOS) {
        print('launching iosuri $iosuri');
        if (await urllauncher.canLaunch(iosuri)) {
          return await urllauncher.launch(iosuri);
        } else {
          return false;
        }
      } else //if(Platform.isAndroid)
      {
        print('launching uri $androiduri');
        if (await urllauncher.canLaunch(androiduri)) {
          return await urllauncher.launch(androiduri);
        } else {
          return false;
        }
      }
    }
  }
}

```
</details>

**Comment by pryshrm** [comment] 2022-02-01 12:24
Hi, Thanks for responding but that is just a superficial change in the logic and that didn't change anything (at least on android, where I am testing). I printed the exact uri that is being launched just before launching:

```
if (_isIOS()) {
  print('launching sms for ios $iosuri');
  return await urllauncher.launch(iosuri);
} else if (_isAndroid()) {
  print('launching sms for android $androiduri');
  return await urllauncher.launch(androiduri);
} else {
  return false;
}
```

it prints:

`launching sms for android sms:+39999222333?body=OK%20Thanks`

This launched the sms app but with neither the ph number nor the body prepopulated.

I did another test and removed the body i.e.

`launching sms for android sms:+39999222333`

This worked fine. The phone number was prepopulated. So, I can reconfirm that there is definitely something going on when the body part is present.

**Comment by pryshrm** [comment] 2022-02-01 12:31
I did another test. Removed all special chars from body. So now, I am launching this:
launching sms for android sms:+39999888777?body=OKTHANKS

This launches the sms app and prepopulates the phone number but body is still missing.

**Comment by danagbemava-nc** [comment] 2022-02-01 12:38
I just did another test on android and it worked just fine, see video below.  I'm using the code sample I posted earlier. 

<details>
<summary>video </summary>


https://user-images.githubusercontent.com/88313112/151969649-3bfa6409-9f05-4fe7-9b06-9e63a1cd8a42.mp4


</details>

**Comment by pryshrm** [comment] 2022-02-01 13:16
Could you please tell me which device did you try it on (real android phone or ios?). 

I tried it on my iPad and it did work correctly. But I tried the same on my Asus Android phone and it did not work. I swear I have the exact same code that you suggested. It is printing out the correct uri in the log message, which I am able to see using chrome remote debugging ( chrome://inspect/#devices )

**Comment by danagbemava-nc** [comment] 2022-02-01 13:58
> Could you please tell me which device did you try it on (real android phone or ios?).

I initially tested on an `iOS simulator` before testing on android. On android, I tested on both:  emulator and physical device. 

Emulators: Pixel 4a API 31 & Pixel 4a API 30
Physical device: Poco X3 NFC

**Comment by pryshrm** [comment] 2022-02-01 14:24
I tried it with three phones 1: Android v 9 (Asus_X00TD),  2. Android v 11 ( Galaxy F41 and F62). 
On all three, the phone and body are absent when body has special chars (even though encoded). 
On all three, the phone is present but the body is absent when body is plain text with no special chars such as OKTHANKS.

**Comment by danagbemava-nc** [comment] 2022-02-02 06:42
There's a chance this might be an issue that is affecting only a certain group of devices. I don't know if this is something that url_launcher has any control over considering all it does it call a method to open the URL.  Can you confirm a few things for me?

- Everything works as expected in a mobile flutter app (ios/android)
- This works as expected on ios (according to your test on iPad) Which browser did you use?
- This works on some of your android devices but not on some

Where "This works" refers to SMS app opening with text and number prepopulated

**Comment by pryshrm** [comment] 2022-02-03 05:20
Yes, it seems like it is device specific or some security trap. I guess some devices are interpreting the uri very strictly and allowing only the phone number part in the uri.

1. Everything works as expected in a mobile flutter app (ios/android)
The mobile flutter app works fine on various Android devices. Not tested on iOS because I haven't built the ios version of the app yet.

2. This works as expected on ios (according to your test on iPad) Which browser did you use?
Yes, the web version works on ios (ipad as well as iphone). Tested on Chrome.

3. This works on some of your android devices but not on some.
Yes, the web version running on Chrome fails consistently on relatively newer devices (Samsung and Asus) that I tested on. It worked on an old Android 6 device. Another interesting bit that I observed was that if you have an ampersand in the body (before url encoding), it fails even on that old android device. It had no impact on the app version. i.e. the app version works even if there is an & in the body text. 

Thanks for your attention.

**Comment by danagbemava-nc** [comment] 2022-02-03 10:01
Can you test if using 

```dart
 String body = Uri.encodeQueryComponent(msg);
```

instead of

```dart
String body = Uri.encodeComponent(msg);
```

makes any difference?

**Comment by pryshrm** [comment] 2022-02-04 06:34
No, that didn't make any difference.

**Comment by danagbemava-nc** [comment] 2022-02-04 13:59
Labeling for further investigation. 

## Summary
- I am unable to reproduce this locally, either on my emulator or physical device. Video of it functioning properly is in https://github.com/flutter/flutter/issues/97564#issuecomment-1026799106. 
- The SMS and body fields are populated when the app is built for either android or ios
- OP confirmed it worked on some of his devices in https://github.com/flutter/flutter/issues/97564#issuecomment-1027030970
- The devices it failed on are Samsung and Asus. Devices are in https://github.com/flutter/flutter/issues/97564#issuecomment-1026898772
- iOS works just fine, so this seems to be an android only issue. 

I have stripped the code sample down to run on web since that is where the issue appears to be. 

<details>
<summary>code sample</summary>

```dart
import 'dart:html' as html;

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart' as urllauncher;

void main(List<String> args) {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TexspanTap(),
    );
  }
}

class TexspanTap extends StatefulWidget {
  const TexspanTap({Key? key}) : super(key: key);

  @override
  _TexspanTapState createState() => _TexspanTapState();
}

class _TexspanTapState extends State<TexspanTap> {
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            children: [
              TextButton(
                onPressed: () async {
                  await launchSMS(
                    phnumber: '+39348060888',
                    msg: 'some message',
                  );
                },
                child: const Text('Launch'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  bool _isIOS() {
    final userAgent = html.window.navigator.userAgent.toString().toLowerCase();
    return userAgent.contains('iphone') || userAgent.contains('ipad');
  }

  bool _isAndroid() {
    final userAgent = html.window.navigator.userAgent.toString().toLowerCase();
    return userAgent.contains('android');
  }

  Future<bool> launchSMS(
      {required String phnumber, required String msg}) async {
    // Android 'sms:+39 348 060 888?body=hello%20there';
    String body = Uri.encodeComponent(msg);

    String androidPh = phnumber.replaceAll("(", "").replaceAll(")", "");
    String androiduri = 'sms:$androidPh?body=$body';

    String iosPh = phnumber
        .replaceAll("+", "00")
        .replaceAll("(", "")
        .replaceAll(")", ""); //'sms:0039-222-060-888?body=hello%20there';
    String iosuri = 'sms:$iosPh&body=$body';

    if (_isIOS()) {
      return await urllauncher.launch(iosuri);
    } else if (_isAndroid()) {
      return await urllauncher.launch(androiduri);
    } else {
      return false;
    }
  }
}
```

</details>

**Comment by pryshrm** [comment] 2022-02-04 17:09
didn't work on duckduckgo either.

**Comment by pryshrm** [comment] 2022-02-04 17:17
On Via browser, it was worse. It couldn't even launch the sms app!

**Comment by danagbemava-nc** [comment] 2022-02-07 08:15
Labeling for further investigation. 

## Summary
- I am unable to reproduce this locally, either on my emulator or physical device. Video of it functioning properly is in https://github.com/flutter/flutter/issues/97564#issuecomment-1026799106. 
- The SMS and body fields are populated when the app is built for either android or ios
- OP confirmed it worked on some of his devices in https://github.com/flutter/flutter/issues/97564#issuecomment-1027030970
- The devices it failed on are Samsung and Asus, but there could be other devices affected. Devices are in https://github.com/flutter/flutter/issues/97564#issuecomment-1026898772
- iOS works just fine, so this seems to be an android only issue. 

I have stripped the code sample down to run on web since that is where the issue appears to be. 

<details>
<summary>code sample</summary>

```dart
import 'dart:html' as html;

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart' as urllauncher;

void main(List<String> args) {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TexspanTap(),
    );
  }
}

class TexspanTap extends StatefulWidget {
  const TexspanTap({Key? key}) : super(key: key);

  @override
  _TexspanTapState createState() => _TexspanTapState();
}

class _TexspanTapState extends State<TexspanTap> {
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            children: [
              TextButton(
                onPressed: () async {
                  await launchSMS(
                    phnumber: '+39348060888',
                    msg: 'some message',
                  );
                },
                child: const Text('Launch'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  bool _isIOS() {
    final userAgent = html.window.navigator.userAgent.toString().toLowerCase();
    return userAgent.contains('iphone') || userAgent.contains('ipad');
  }

  bool _isAndroid() {
    final userAgent = html.window.navigator.userAgent.toString().toLowerCase();
    return userAgent.contains('android');
  }

  Future<bool> launchSMS(
      {required String phnumber, required String msg}) async {
    // Android 'sms:+39 348 060 888?body=hello%20there';
    String body = Uri.encodeComponent(msg);

    String androidPh = phnumber.replaceAll("(", "").replaceAll(")", "");
    String androiduri = 'sms:$androidPh?body=$body';

    String iosPh = phnumber
        .replaceAll("+", "00")
        .replaceAll("(", "")
        .replaceAll(")", ""); //'sms:0039-222-060-888?body=hello%20there';
    String iosuri = 'sms:$iosPh&body=$body';

    if (_isIOS()) {
      return await urllauncher.launch(iosuri);
    } else if (_isAndroid()) {
      return await urllauncher.launch(androiduri);
    } else {
      return false;
    }
  }
}
```

</details>

**Comment by Hixie** [comment] 2022-02-08 23:57
@pryshrm For the devices where this doesn't work in Flutter, have you tested to see if it works on a normal web page? e.g. `<!DOCTYPE HTML><a href="sms:0039-222-060-888?body=hello%20there">test</a>`?

**Comment by stuartmorgan** [comment] 2022-02-10 21:14
`sms` URLs don't have a standard behavior for extra parameters across platforms. This is not something within the control of the plugin, as it's at the level of the receiver of the URL.

Closing as a duplicate of https://github.com/flutter/flutter/issues/18823

**Closed by stuartmorgan** 2022-02-10 21:14 UTC
Labels: platform-android, waiting for customer response, plugin, p: first party, will need additional triage, platform-web, p: url_launcher
