### ISSUE TITLE
[Desktop] Shortcut "ctrl/command + z" in the textfield

### ISSUE THREAD

**Issue by Bestfastfire** [flutter/flutter#76061] opened 2021-02-15 11:48 UTC
It would be interesting if it were possible to add this feature, several people end up using it as they type.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [versÃ£o 10.0.19042.746], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.0)
[√] Connected device (3 available)

• No issues found!
```

**Comment by pedromassangocode** [comment] 2021-02-15 12:03
Closing as duplicate of https://github.com/flutter/flutter/issues/24222. Please follow up on that issue for updated.
Thank you

**Closed by pedromassangocode** 2021-02-15 12:03 UTC
