### ISSUE TITLE
SharedPreferences update breaks my app

### ISSUE THREAD

**Issue by push-22** [flutter/flutter#27538] opened 2019-02-05 10:39 UTC
I have been using SharedPreferences in an app for a while now and everything worked ok until the 0.5.0 upgrade. 

The problem is caused by my use of a SharedPreferences instance in main, I need to get a Theme colour preference **before** creating my main window so I can create the window using the required Theme.

This is a hacked version of what I'm doing but fails in the same way.

NOTE: I have migrated my app to AndroidX , using Android Studio.

```
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  // **** goes bang here ****
  SharedPreferences prefs = await SharedPreferences.getInstance();
  if(!prefs.getKeys().contains('THEME')) {
    prefs.setBool('THEME', true);
  }
  final theme = prefs.getBool('THEME') ? ThemeData.dark() : ThemeData.light();
  runApp(MaterialApp(
    theme: theme, // needed at runtime
    home: Scaffold(
      body: Center(
      child: RaisedButton(
        onPressed: null,
        child: Text('Increment Counter'),
        ),
      ),
    ),
  ));
}
```

## Logs
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
E/flutter ( 6368): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'window' was called on null.
E/flutter ( 6368): Receiver: null
E/flutter ( 6368): Tried calling: window
E/flutter ( 6368): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 6368): #1      BinaryMessages._sendPlatformMessage 
E/flutter ( 6368): #2      BinaryMessages.send 
E/flutter ( 6368): #3      MethodChannel.invokeMethod 
E/flutter ( 6368): <asynchronous suspension>
E/flutter ( 6368): #4      SharedPreferences.getInstance 
E/flutter ( 6368): <asynchronous suspension>
E/flutter ( 6368): #5      main 
E/flutter ( 6368): <asynchronous suspension>
E/flutter ( 6368): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:170:23)
E/flutter ( 6368): #7      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6368): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6368): #9      _runZoned (dart:async/zone.dart:1516:10)
E/flutter ( 6368): #10     runZoned (dart:async/zone.dart:1500:12)
E/flutter ( 6368): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:169:5)
E/flutter ( 6368): #12     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
E/flutter ( 6368): #13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter ( 6368): 

```
## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.2.1-pre.88, on Microsoft Windows [Version 10.0.17763.292], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.30.2)
[√] Connected device (1 available)
• No issues found!
```

**Comment by jonahwilliams** [comment] 2019-02-05 20:18
Duplicate of https://github.com/flutter/flutter/issues/27541

**Closed by jonahwilliams** 2019-02-05 20:18 UTC
