### ISSUE TITLE
App crashes due to class not found exception on Android 9 & X

### ISSUE THREAD

**Issue by fazil-augr** [flutter/flutter#40742] opened 2019-09-18 08:27 UTC
I successfully published the flutter app in play store. I have 1000+ users. In my app is crashing too much times. Daily having 165 crashes out of 100 users. It effecting in Android 10 and Android9 versions. I don't what is the reason.
Is there any resolution?

Due to the crash users are uninstalling the app?
Why flutter having too much crashes?

My flutter version is 
```
v1.7.8+hotfix.4
```

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3404)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:201)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1668)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6746)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:171)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.AppComponentFactory.instantiateReceiver (AppComponentFactory.java:84)
  at androidx.core.app.CoreComponentFactory.instantiateReceiver (CoreComponentFactory.java)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3397)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:201)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1668)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6746)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

**Comment by escamoteur** [comment] 2019-09-18 09:42
Hi, does this only effect Android? Can you see if it only effects specific device types?  
Do you have any idea what your app is doing at that moment?
do you have the same problems with other Apps?

**Comment by fazil-augr** [comment] 2019-09-18 09:49
It only effect in android and it effecting more than number devices, And the effecting android versions are android 9 and android 10. I didn't published any other flutter apps. In my apps I am using firebase database. And I am using listener streaming data's. For example in my home page have to display list of items. IF there is any change happen that moment it will reflect in displaying items.

**Comment by escamoteur** [comment] 2019-09-18 12:33
So in versions below Android 9 you don't see this happen?

**Comment by fazil-augr** [comment] 2019-09-18 12:36
No I didn't find

**Comment by escamoteur** [comment] 2019-09-18 20:39
@eseidl this seems serious.

**Comment by dnfield** [comment] 2019-09-18 23:15
/cc @blasten @mklim @matthew-carroll who might know more about this.

It seems likely to me that you're using some feature and not including the required JAR in your build dependencies for Android.  This could mean you need some Android support library, or some other library that a plugin is using.  It would be most helpful if you had a reproduction for this case, or barring that if you have some source code you can share (particularly your gradle files).

**Comment by blasten** [comment] 2019-09-18 23:24
@fazil-augr Did you enable Proguard with missing rules?  I think it would be great if you can share more about the current setup.

**Comment by fazil-augr** [comment] 2019-09-19 08:29
I added `proguard-rules.pro` in `android/app/proguard-rules.pro`
The `proguard-rules.pro` code is
```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.google.firebase.** { *; }
-keep class com.razorpay.**  { *; }
-keep class com.baseflow.** { *; }
-dontwarn com.razorpay.**
-dontwarn com.google.gson.**
-ignorewarnings
-keep class * {
    public private *;
}
```

And my grade file is
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}


def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1.0.3'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0.3'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

    

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.myapp"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 200105
        versionName "2.1.5"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
    

        // ndk {
        //  abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
        // }
    
    }

    

    

    signingConfigs {
    release {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile file(keystoreProperties['storeFile'])
        storePassword keystoreProperties['storePassword']
    }

   
}



    buildTypes {

        release {

            signingConfig signingConfigs.release

            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }
    }

    




}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0-alpha02'
   // androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.2-alpha01'
    //implementation 'com.google.firebase:firebase-core:16.0.7'
    // implementation 'com.razorpay:checkout:1.4.9'
    // compile 'com.razorpay:checkout:1.5.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.fragment:fragment:1.2.0-alpha02'
   // implementation 'com.google.android.gms:play-services-analytics:16.0.7'

   // androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.2-alpha01'

        implementation fileTree(dir: 'libs', include: ['*.jar'])

    //implementation "android.arch.persistence.room:guava:1.1.1"
    //implementation 'com.google.firebase:firebase-core:16.0.7'
    //implementation 'com.google.firebase:firebase-database:16.0.6'

   // implementation 'android.arch.work:work-runtime-ktx:1.0.0-rc01'
   // implementation 'androidx.concurrent:concurrent-futures:1.0.0-alpha03'
    implementation('androidx.concurrent:concurrent-futures:1.0.0-alpha02')  {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }

    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'

    implementation('androidx.concurrent:concurrent-futures:1.0.0-alpha02')  {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }

    api 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'

    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    androidTestImplementation 'com.android.support.test:rules:1.0.2'

    implementation 'com.google.firebase:firebase-core:17.0.1'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
    implementation 'com.crashlytics.sdk.android:answers:1.4.7'

    implementation('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
    transitive = true;


    implementation 'com.android.support:appcompat-v7:28.0.0'
androidTestImplementation "com.android.support:support-annotations:28.0.0"



}

    implementation 'com.google.android.gms:play-services-tagmanager:17.0.0'
    implementation 'com.google.firebase:firebase-messaging:19.0.1'
    implementation 'com.google.firebase:firebase-auth:18.1.0'
    implementation 'com.facebook.android:facebook-android-sdk:5.1.1'



}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.fabric'


```

**Comment by BugsBunnyBR** [comment] 2019-09-19 13:42
It looks similar to this issue 
https://stackoverflow.com/questions/51006967/androidx-build-fails-in-release-mode-regarding-appcomponentfactory

Could you try this solution ?
https://stackoverflow.com/a/51011781/2742962

**Comment by dnfield** [comment] 2019-09-19 13:50
We should bpribaboy add that to our proguard instructions

**Comment by Hixie** [comment] 2019-09-24 23:13
cc @mklim @zanderso

**Comment by Hixie** [comment] 2019-09-24 23:14
cc @blasten

**Comment by blasten** [comment] 2019-09-25 20:52
@fazil-augr I'd suggest to avoid using `-ignorewarnings` in `proguard-rules.pro`. If Proguard aborts the build, it's better to fix the issue either by specifying more fine-grained rules or replacing the conflicting dependency.

In the next stable release (or master channel currently), you will find that you don't need Proguard anymore. `flutter build apk --release` and `flutter build appbundle --release` turns R8, the new code shrinker for Android apps, on.

Give it a try by switching to the master channel and let me know if you run into any issues. Otherwise, please consider closing the thread.

**Comment by fazil-augr** [comment] 2019-09-26 11:56
@blasten I will try with removing ```-ignorewarnings```

**Comment by Hixie** [comment] 2019-09-30 23:24
@fazil-augr any luck?

**Comment by KarmaEstudio** [comment] 2019-10-11 11:53
I´m having the same problem.

Any solution?

`java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3398)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:208)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1691)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6715)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:134)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.AppComponentFactory.instantiateReceiver (AppComponentFactory.java:84)
  at androidx.core.app.CoreComponentFactory.instantiateReceiver (CoreComponentFactory.java:56)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3391)`

**Comment by fazil-augr** [comment] 2019-10-14 05:49
when I am removing `-ignorewarnings`
It showing error of 

```
Note: there were 10 references to unknown classes.                                    You should check your configuration for typos.                                  (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)Note: there were 2 references to unknown class members.                               You should check your configuration for typos.                            Note: there were 62 unresolved dynamic references to classes or interfaces.           You should check if you need to specify additional program jars.                (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)                                 
Warning: there were 23 unresolved references to classes or interfaces.                   You may need to add missing library jars or update their versions.              If your code works fine without the missing classes, you can suppress           the warnings with '-dontwarn' options.                                          (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)                             
Warning: there were 2 unresolved references to library class members.                    You probably need to update the library versions.                               (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)                
Running Gradle task 'bundleRelease'...                                          Running Gradle task 'bundleRelease'... Done                       122.9s (!)
********************************************************************************
***********
The Gradle failure may have been because of AndroidX incompatibilities in this
Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
********************************************************************************
***********
Gradle task bundleRelease failed with exit code 1

```

I don't how to solve the issue.

**Comment by fazil-augr** [comment] 2019-10-14 05:51
same crash is happening in version `Flutter 1.9.1+hotfix.2`

**Comment by blasten** [comment] 2019-10-14 16:19
@fazil-augr Is this the full error message?  Maybe re-run the command with the `-v` flag.

**Comment by fazil-augr** [comment] 2019-10-15 10:46
I have used `flutter run -v`. It is successfully running without error. But when I trying with `flutter build appbundle -v` . It showing error.


```

[  +95 ms] Note: duplicate definition of library class
[android.annotation.TargetApi]
[        ] Note: duplicate definition of library class
[android.annotation.SuppressLint]
[ +103 ms] Reading library jar
[/Users/faziltm/Library/Android/sdk/build-tools/28.0.3/core-lambda-stubs.jar]
[        ] Reading library jar
[/Users/faziltm/Library/Android/sdk/platforms/android-28/optional/org.apache.htt
p.legacy.jar]
[        ] Reading library jar
[/Users/faziltm/Library/Android/sdk/platforms/android-28/optional/android.test.m
ock.jar]
[        ] Reading library jar
[/Users/faziltm/Library/Android/sdk/platforms/android-28/optional/android.test.b
ase.jar]
[        ] Reading library jar
[/Users/faziltm/Library/Android/sdk/platforms/android-28/optional/android.test.r
unner.jar]
[   +1 ms] Note: there were 2 duplicate class definitions.
[   +2 ms] 
(http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
[  +88 ms] Initializing...
[        ] Note: the configuration refers to the unknown class
'com.webstersys.geofence.BootDeviceReceiver'
[        ] Note: the configuration refers to the unknown class
'com.webstersys.geofence.geofence.GeofenceBroadcastReceiver'
[        ] Note: the configuration refers to the unknown class
'com.webstersys.geofence.geofence.GeofenceTransitionsJobIntentService'
[        ] Note: the configuration refers to the unknown class
'com.google.android.gms.common.api.internal.BasePendingResult$ReleasableResultGu
ardian'
[        ] Note: the configuration refers to the unknown class
'com.android.vending.billing.IInAppBillingService'
[        ] Note: the configuration refers to the unknown class
'com.android.vending.billing.IInAppBillingService'
[        ] Note: the configuration refers to the unknown class
'com.facebook.messaging.analytics.reliability.ReliabilityInfo'
[ +107 ms] Note: the configuration refers to the unknown class
'com.facebook.messaging.analytics.reliability.ReliabilityInfo.Outcome'
[        ] Note: the configuration refers to the unknown class
'com.android.vending.billing.IInAppBillingService'
[        ] Note: the configuration refers to the unknown class
'com.android.vending.billing.IInAppBillingService'
[ +691 ms] Warning: io.flutter.embedding.android.FlutterView: can't find
referenced method 'android.graphics.Insets getSystemGestureInsets()' in library
class android.view.WindowInsets
[        ] Warning: io.flutter.embedding.android.FlutterView: can't find
referenced class android.graphics.Insets
[        ] Warning: io.flutter.embedding.android.FlutterView: can't find
referenced class android.graphics.Insets
[        ] Warning: io.flutter.embedding.android.FlutterView: can't find
referenced class android.graphics.Insets
[        ] Warning: io.flutter.embedding.android.FlutterView: can't find
referenced class android.graphics.Insets
[        ] Warning: io.flutter.embedding.android.FlutterView: can't find
referenced class android.graphics.Insets
[        ] Warning: io.flutter.embedding.android.FlutterView: can't find
referenced class android.graphics.Insets
[  +22 ms] Warning: io.flutter.view.FlutterView: can't find referenced method
'android.graphics.Insets getSystemGestureInsets()' in library class
android.view.WindowInsets
[        ] Warning: io.flutter.view.FlutterView: can't find referenced class
android.graphics.Insets
[        ] Warning: io.flutter.view.FlutterView: can't find referenced class
android.graphics.Insets
[        ] Warning: io.flutter.view.FlutterView: can't find referenced class
android.graphics.Insets
[        ] Warning: io.flutter.view.FlutterView: can't find referenced class
android.graphics.Insets
[        ] Warning: io.flutter.view.FlutterView: can't find referenced class
android.graphics.Insets
[        ] Warning: io.flutter.view.FlutterView: can't find referenced class
android.graphics.Insets
[  +79 ms] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.OpenSSLProvider
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.OpenSSLProvider
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[  +18 ms] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[        ] Warning: okhttp3.internal.platform.ConscryptPlatform: can't find
referenced class org.conscrypt.Conscrypt
[ +175 ms] Note: com.crashlytics.android.core.CrashlyticsController: can't find
dynamically referenced class com.google.firebase.crash.FirebaseCrash
[        ] Note: com.facebook.appevents.codeless.internal.UnityReflection: can't
find dynamically referenced class com.unity3d.player.UnityPlayer
[        ] Note: com.facebook.appevents.codeless.internal.ViewHierarchy: can't
find dynamically referenced class android.view.View$ListenerInfo
[        ] Note: com.facebook.appevents.codeless.internal.ViewHierarchy: can't
find dynamically referenced class android.view.View$ListenerInfo
[        ] Note: com.facebook.appevents.codeless.internal.ViewHierarchy: can't
find dynamically referenced class com.facebook.react.uimanager.TouchTargetHelper
[        ] Note:
com.facebook.appevents.internal.InAppPurchaseActivityLifecycleTracker: can't
find dynamically referenced class
com.android.vending.billing.IInAppBillingService$Stub
[        ] Note:
com.facebook.appevents.internal.InAppPurchaseActivityLifecycleTracker: can't
find dynamically referenced class
com.android.billingclient.api.ProxyBillingActivity
[  +21 ms] Note: com.google.android.gms.common.util.WorkSourceUtil: can't find
dynamically referenced class android.os.WorkSource$WorkChain
[        ] Note: com.google.android.gms.internal.firebase_auth.zzgj: can't find
dynamically referenced class libcore.io.Memory
[        ] Note: com.google.android.gms.internal.firebase_auth.zzgj: can't find
dynamically referenced class org.robolectric.Robolectric
[        ] Note: com.google.android.gms.internal.firebase_auth.zzhp: can't find
dynamically referenced class com.google.protobuf.ExtensionSchemaFull
[        ] Note: com.google.android.gms.internal.firebase_auth.zzix: can't find
dynamically referenced class com.google.protobuf.DescriptorMessageInfoFactory
[        ] Note: com.google.android.gms.internal.firebase_auth.zzjf: can't find
dynamically referenced class com.google.protobuf.MapFieldSchemaFull
[        ] Note: com.google.android.gms.internal.firebase_auth.zzjr: can't find
dynamically referenced class com.google.protobuf.NewInstanceSchemaFull
[        ] Note: com.google.android.gms.internal.firebase_auth.zzjy: can't find
dynamically referenced class com.google.protobuf.GeneratedMessage
[        ] Note: com.google.android.gms.internal.firebase_auth.zzjy: can't find
dynamically referenced class com.google.protobuf.UnknownFieldSetSchema
[        ] Note: com.google.android.gms.internal.gtm.zzpp: can't find
dynamically referenced class libcore.io.Memory
[        ] Note: com.google.android.gms.internal.gtm.zzpp: can't find
dynamically referenced class org.robolectric.Robolectric
[        ] Note: com.google.android.gms.internal.gtm.zzqo: can't find
dynamically referenced class com.google.protobuf.ExtensionRegistry
[        ] Note: com.google.android.gms.internal.gtm.zzqp: can't find
dynamically referenced class com.google.protobuf.Extension
[        ] Note: com.google.android.gms.internal.gtm.zzqs: can't find
dynamically referenced class com.google.protobuf.ExtensionSchemaFull
[        ] Note: com.google.android.gms.internal.gtm.zzrz: can't find
dynamically referenced class com.google.protobuf.DescriptorMessageInfoFactory
[        ] Note: com.google.android.gms.internal.gtm.zzsh: can't find
dynamically referenced class com.google.protobuf.MapFieldSchemaFull
[        ] Note: com.google.android.gms.internal.gtm.zzst: can't find
dynamically referenced class com.google.protobuf.NewInstanceSchemaFull
[        ] Note: com.google.android.gms.internal.gtm.zztb: can't find
dynamically referenced class com.google.protobuf.GeneratedMessage
[        ] Note: com.google.android.gms.internal.gtm.zztb: can't find
dynamically referenced class com.google.protobuf.UnknownFieldSetSchema
[        ] Note: com.google.android.gms.internal.measurement.zzdr: can't find
dynamically referenced class libcore.io.Memory
[        ] Note: com.google.android.gms.internal.measurement.zzdr: can't find
dynamically referenced class org.robolectric.Robolectric
[        ] Note: com.google.android.gms.internal.measurement.zzeq: can't find
dynamically referenced class com.google.protobuf.Extension
[        ] Note: com.google.android.gms.internal.measurement.zzet: can't find
dynamically referenced class com.google.protobuf.ExtensionSchemaFull
[        ] Note: com.google.android.gms.internal.measurement.zzgb: can't find
dynamically referenced class com.google.protobuf.DescriptorMessageInfoFactory
[        ] Note: com.google.android.gms.internal.measurement.zzgj: can't find
dynamically referenced class com.google.protobuf.MapFieldSchemaFull
[        ] Note: com.google.android.gms.internal.measurement.zzgy: can't find
dynamically referenced class com.google.protobuf.NewInstanceSchemaFull
[        ] Note: com.google.android.gms.internal.measurement.zzhf: can't find
dynamically referenced class com.google.protobuf.GeneratedMessage
[        ] Note: com.google.android.gms.internal.measurement.zzhf: can't find
dynamically referenced class com.google.protobuf.UnknownFieldSetSchema
[        ] Note: com.google.android.gms.internal.measurement.zzx: can't find
dynamically referenced class android.os.SystemProperties
[        ] Note: com.google.android.gms.measurement.internal.zzx: can't find
dynamically referenced class android.os.SystemProperties
[        ] Note: com.google.common.util.concurrent.MoreExecutors: can't find
dynamically referenced class com.google.appengine.api.ThreadManager
[        ] Note: com.google.common.util.concurrent.MoreExecutors: can't find
dynamically referenced class com.google.apphosting.api.ApiProxy
[  +68 ms] Note: com.google.gson.internal.UnsafeAllocator: can't find
dynamically referenced class sun.misc.Unsafe
[        ] Note: com.google.gson.internal.reflect.UnsafeReflectionAccessor:
can't find dynamically referenced class sun.misc.Unsafe
[        ] Note: com.google.protobuf.ExtensionRegistryFactory: can't find
dynamically referenced class com.google.protobuf.ExtensionRegistry
[        ] Note: com.google.protobuf.ExtensionRegistryLite: can't find
dynamically referenced class com.google.protobuf.Extension
[        ] Note: com.squareup.okhttp.internal.Platform: can't find dynamically
referenced class com.android.org.conscrypt.SSLParametersImpl
[        ] Note: com.squareup.okhttp.internal.Platform: can't find dynamically
referenced class org.apache.harmony.xnet.provider.jsse.SSLParametersImpl
[        ] Note: com.squareup.okhttp.internal.Platform: can't find dynamically
referenced class sun.security.ssl.SSLContextImpl
[        ] Note: io.fabric.sdk.android.FabricKitsFinder: can't find dynamically
referenced class com.google.android.gms.ads.AdView
[ +123 ms] Note: io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors:
can't find dynamically referenced class android.util.LongArray
[        ] Note: io.grpc.Context$LazyStorage: can't find dynamically referenced
class io.grpc.override.ContextStorageOverride
[        ] Note: io.grpc.ManagedChannelProvider$HardcodedClasses: can't find
dynamically referenced class io.grpc.netty.NettyChannelProvider
[        ] Note: io.grpc.internal.JndiResourceResolverFactory: can't find
dynamically referenced class javax.naming.directory.InitialDirContext
[        ] Note: io.grpc.internal.JndiResourceResolverFactory: can't find
dynamically referenced class com.sun.jndi.dns.DnsContextFactory
[        ] Note: io.grpc.okhttp.internal.Platform: can't find dynamically
referenced class org.conscrypt.OpenSSLProvider
[        ] Note: kotlin.internal.PlatformImplementationsKt: can't find
dynamically referenced class kotlin.internal.jdk8.JDK8PlatformImplementations
[        ] Note: kotlin.internal.PlatformImplementationsKt: can't find
dynamically referenced class kotlin.internal.JRE8PlatformImplementations
[        ] Note: kotlin.internal.PlatformImplementationsKt: can't find
dynamically referenced class kotlin.internal.JRE7PlatformImplementations
[        ] Note: kotlin.jvm.internal.Reflection: can't find dynamically
referenced class kotlin.reflect.jvm.internal.ReflectionFactoryImpl
[        ] Note: okhttp3.internal.platform.AndroidPlatform: can't find
dynamically referenced class com.android.org.conscrypt.SSLParametersImpl
[        ] Note: okhttp3.internal.platform.AndroidPlatform: can't find
dynamically referenced class
org.apache.harmony.xnet.provider.jsse.SSLParametersImpl
[        ] Note: okhttp3.internal.platform.AndroidPlatform$CloseGuard: can't
find dynamically referenced class dalvik.system.CloseGuard
[        ] Note: okhttp3.internal.platform.ConscryptPlatform: can't find
dynamically referenced class org.conscrypt.ConscryptEngineSocket
[        ] Note: okhttp3.internal.platform.Platform: can't find dynamically
referenced class sun.security.ssl.SSLContextImpl
[+1074 ms] Note: the configuration refers to the unknown field
'com.google.android.gms.common.api.internal.BasePendingResult$ReleasableResultGu
ardian mResultGuardian' in class
'com.google.android.gms.common.api.internal.BasePendingResult'
[        ] Note: the configuration refers to the unknown method
'com.google.android.gms.measurement.AppMeasurement
getInstance(android.content.Context,java.lang.String,java.lang.String)' in class
'com.google.android.gms.measurement.AppMeasurement'
[ +597 ms] Note: there were 10 references to unknown classes.
[        ]       You should check your configuration for typos.
[        ] 
(http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
[        ] Note: there were 2 references to unknown class members.
[        ]       You should check your configuration for typos.
[        ] Note: there were 62 unresolved dynamic references to classes or
interfaces.
[        ]       You should check if you need to specify additional program
jars.
[        ] 
(http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
[        ] > Task :app:transformClassesAndResourcesWithProguardForRelease FAILED
[        ]          *********************************************************
[        ] WARNING: This version of android_intent will break your Android build
if it or its dependencies aren't compatible with AndroidX.
[  +28 ms]          See https://goo.gl/CP92wY for more information on the
problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real
root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 393 actionable tasks: 10 executed, 383 up-to-date
[        ] Warning: there were 23 unresolved references to classes or
interfaces.
[        ]          You may need to add missing library jars or update their
versions.
[        ]          If your code works fine without the missing classes, you can
suppress
[        ]          the warnings with '-dontwarn' options.
[        ] 
(http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
[        ] Warning: there were 2 unresolved references to library class members.
[   +4 ms]          You probably need to update the library versions.
[        ] 
(http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibrarycl
assmember)
[ +409 ms] Running Gradle task 'bundleRelease'... (completed in 120.6s, longer
than expected)
[        ]
********************************************************************************
           ***********
[        ] The Gradle failure may have been because of AndroidX
incompatibilities in this
           Flutter app.
[        ] See https://goo.gl/CP92wY for more information on the problem and how
to fix it.
[        ]
********************************************************************************
           ***********
[  +12 ms] "flutter appbundle" took 1,24,477ms.
Gradle task bundleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2
(package:flutter_tools/src/android/gradle.dart:751:5)
#2      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:71:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:552:7)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:173:5)



```

**Comment by blasten** [comment] 2019-10-22 17:22
@fazil-augr It looks like some of the Gradle dependencies in your app require fine grained Proguard rules. This issue is solved if you switch to the beta or master channel since the Flutter tool doesn't use Proguard. Please give it a try and let us know if this solved the error.

**Comment by zanderso** [comment] 2019-11-12 22:46
@fazil-augr Please feel free to re-open if this is still a problem, thanks!

**Closed by zanderso** 2019-11-12 22:46 UTC
Labels: customer: product, d: examples, d: website - content, severe: crash, severe: customer critical, severe: regression, t: gradle, tool, waiting for customer response, ▣ platform-android
