### ISSUE TITLE
Error capture Camera

### ISSUE THREAD

**Issue by joharputr** [flutter/flutter#83961] opened 2021-06-04 03:45 UTC
Error when capture photo on realme 3 using camera 0.8.1+2

flutter doctor : 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19041.985], locale en-ID)
    • Flutter version 2.0.6 at C:\Users\1087\Downloads\flutter
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\1087\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\1087\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • RMX1821 (mobile) • Y5ZD8LMFHYF6I7JF • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 91.0.864.37

! Doctor found issues in 1 category.
```

</details>

<img src="https://user-images.githubusercontent.com/32647004/120742820-dd295c00-c521-11eb-8e99-748c1c4d8655.jpg" height="450" />

**Comment by TahaTesser** [comment] 2021-06-04 11:44
Hi @joharputr 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/76305
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-04 11:44 UTC
Labels: in triage
