### ISSUE TITLE
bin/cache/lockfile - OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by tvw** [flutter/flutter#28210] opened 2019-02-20 15:19 UTC
I installed Flutter on my machine and of course the application directory is write protected!!!

When starting flutter, I noticed, that it tries to write into bin/cache and crashes.

Seriously????? IMHO it is very bad style to write stuff here. There are user-/profile-directories on Unix/Linux, MacOS and Windows, so user- and temporary data should go there leaving the application directory tree untouched.

**Comment by zoechi** [comment] 2019-02-20 15:33
That's how Flutter is currently working

https://flutter.io/docs/get-started/install/windows

> do not install Flutter in a directory like C:\Program Files\ that requires elevated privileges

Closing as working as intended.
That might be reconsidered eventually, but I don't think it's worth keeping an issue for that.

**Closed by zoechi** 2019-02-20 15:33 UTC

**Comment by tvw** [comment] 2019-02-20 16:43
I am using Flutter on Linux. Up to now it does not seem to need more write access rather that to bin/cache and version.

**Comment by nnhan0719** [comment] 2019-08-15 16:00
I have find out root cause to solve this problem.
Go to folder contain flutter SDK:
`sudo chmod -R 777 flutter`

**Comment by imedDrioua** [comment] 2020-05-16 01:22
> sudo chmod -R 777 flutter

it works very well thanks man
