### ISSUE TITLE
Flutter not generating App.framework, thrown error : ld: framework not found Flutter

### ISSUE THREAD

**Issue by gianalmada** [flutter/flutter#51825] opened 2020-03-03 08:48 UTC
i want to build ios app of my project, but after i run the project, app not compiling updated code of my project. i dont know what causing this error, i have tried to delete Flutter.framework and App.framework, but after run app again, App.framework not generate, and thrown error : ld: framework not found Flutter, anyone can help me to solve this ?? 
Thank you.

**Comment by TahaTesser** [comment] 2020-03-03 08:53
Duplicate of [#32454](https://github.com/flutter/flutter/issues/32454)

**Closed by TahaTesser** 2020-03-03 08:53 UTC

**Comment by gianalmada** [comment] 2020-03-03 09:12
> 
> 
> Duplicate of [#32454](https://github.com/flutter/flutter/issues/32454)

is this problem solved ?? i can not find the right anwer,

**Comment by TahaTesser** [comment] 2020-03-03 09:56
Hi @gianalmada 
Please the upvote the mentioned issue in that page and issue still open issue
Thank you
