### ISSUE TITLE
Null object exception from Gallery on Android (method not found: 'inheritFromWidgetOfExactType')

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6184] opened 2016-10-03 22:06 UTC
```
10-03 11:29:10.612 29886 29912 E flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
10-03 11:29:10.612 29886 29912 E flutter : The null object does not have a method 'inheritFromWidgetOfExactType'.
10-03 11:29:10.612 29886 29912 E flutter : 
10-03 11:29:10.612 29886 29912 E flutter : NoSuchMethodError: method not found: 'inheritFromWidgetOfExactType'
10-03 11:29:10.612 29886 29912 E flutter : Receiver: null
10-03 11:29:10.612 29886 29912 E flutter : Arguments: [Type: class 'FormScope']
10-03 11:29:10.612 29886 29912 E flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart)
10-03 11:29:10.612 29886 29912 E flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart)
10-03 11:29:10.612 29886 29912 E flutter : #2      _FormFieldData.onChanged (package:flutter/src/material/input.dart)
10-03 11:29:10.612 29886 29912 E flutter : #3      RawInputLineState._handleTextUpdated (package:flutter/src/widgets/editable.dart)
10-03 11:29:10.612 29886 29912 E flutter : #4      _KeyboardClientImpl.updateEditingState (package:flutter/src/widgets/editable.dart)
10-03 11:29:10.612 29886 29912 E flutter : #5      _KeyboardClientStubControl.handleMessage (package:sky_services/editing/editing.mojom.dart)
10-03 11:29:10.612 29886 29912 E flutter : #6      StubMessageHandler.handleRead (package:mojo/src/stub.dart)
10-03 11:29:10.612 29886 29912 E flutter : #7      MojoEventHandler._handleEvent (package:mojo/src/event_handler.dart)
10-03 11:29:10.612 29886 29912 E flutter : #8      MojoEventHandler._tryHandleEvent (package:mojo/src/event_handler.dart)
10-03 11:29:10.612 29886 29912 E flutter : #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart)
```

**Comment by sethladd** [comment] 2016-10-03 22:06
cc @mpcomplete

**Comment by jason-simmons** [comment] 2016-10-12 23:10
Duplicate of #6274

**Closed by jason-simmons** 2016-10-12 23:10 UTC
Labels: affects: text input, customer: gallery, ⚠ bug
