### ISSUE TITLE
[go router] Update documentation with 4.0 migration guide and changes

### ISSUE THREAD

**Issue by cgutierr-zgz** [flutter/flutter#107458] opened 2022-07-12 10:23 UTC
I'd like an update to the documentation to hold information regarding go_router 4.0 migration guide and relevant changes.
Thanks ☺️

**Comment by cgutierr-zgz** [comment] 2022-07-12 13:48
Hi @huycozy, not sure what you mean by this
Should I remove the part of the issue where I mention the documentation and only leave the update to 4.0 migration part?

Thanks

**Comment by huycozy** [comment] 2022-07-13 03:28
Hi @cgutierr-zgz. Sorry, it wasn't clear. 
> Should I remove the part of the issue where I mention the documentation and only leave the update to 4.0 migration part?

Yes, we already had #102171 mentioned to GitHub repo owner issue, so we don't need to solve it here.
And let's keep only the update to 4.0 migration part here in this issue's description.
Thanks!

**Comment by cgutierr-zgz** [comment] 2022-07-13 06:53
Ok @huycozy guess now it's better?
Thanks!

**Comment by chunhtai** [comment] 2022-07-22 17:27
I will close this as a duplicate of https://github.com/flutter/flutter/issues/102171

**Closed by chunhtai** 2022-07-22 17:27 UTC
Labels: p: first party, package, documentation, P4, p: go_router
