### ISSUE TITLE
Gallery App - Android 6 - Google Play - Stuck in black startup screen

### ISSUE THREAD

**Issue by jonboj** [flutter/flutter#6347] opened 2016-10-16 08:36 UTC
## Steps to Reproduce

Device Samsung Galaxy A3, Android 6.0.1 - Google Play install of Gallery App `flutter_gallery-bv0005-rc000`
- Open app, then the app stays stuck in a black screen mode, see attached screendump. The rest of the android environment works ok. The exit button, exits the app. After reboot and a re-install of the app, the bug remains. On this device 100% reproducible.
## Note.

  The bug was introduced with the upgraded to Android 6.0.1.

![screenshot_flutter_gallery](https://cloud.githubusercontent.com/assets/7474093/19416231/a83181c0-938b-11e6-8c97-d31d3573681b.png)

**Comment by eseidelGoogle** [comment] 2016-10-16 22:33
@chinmaygarde or @jason-simmons would know.

Looks like the A3 has a Adreno 306 GPU which is a very popular GPU and looks to be covered by Skia.  We've definitely seen this failure mode in other devices before.  @chinmaygarde might remember why.

**Comment by jonboj** [comment] 2016-11-07 15:20
Same behavior after update to `flutter_gallery-bv0006-rc000`

**Comment by chinmaygarde** [comment] 2016-12-06 01:35
Sorry, just getting around to the device/GPU specific issues. I'll try to procure this device and check what is happening. In the meantime, do you happen to have the results of `adb shell dumpsys SurfaceFlinger` handy?

**Comment by jonboj** [comment] 2016-12-06 07:02
Great. I run the Gallery App on my normal use phone, just installing from Google Play.

From an Android terminal, with the Gallery App running.
> dumpsys SurfaceFlinger
>Error dumping service info: (Unknown error -2147483646) SurfaceFlinger

**Comment by jonboj** [comment] 2017-02-05 08:08
This app with builddate 2016-12-11 works with no problem
https://play.google.com/store/apps/details?id=com.yourcompany.cruisedeals

**Comment by eseidelGoogle** [comment] 2017-02-08 22:21
This will be resolved by https://github.com/flutter/flutter/issues/7983 when we push a new version of the gallery.

**Comment by eseidelGoogle** [comment] 2017-02-23 03:12
I'm going to close this as a dupe of https://github.com/flutter/flutter/issues/7983.  Thanks for the report!

**Closed by eseidelGoogle** 2017-02-23 03:12 UTC
Labels: dependency: skia, device-specific, gpu-driver-bug, ▣ platform-android

**Comment by jonboj** [comment] 2017-05-10 07:35
Test with same device - Gallery version bv8-rc000, No lockup in startup screen. Confirmed working.
