### ISSUE TITLE
Dart plugin registration doesn't work when app is built with obfuscation

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#99477] opened 2022-03-03 11:24 UTC
When building without obfuscation, this works.
This has started failing recently. Same issue seen on Windows, Linux and possibly other platforms.

## Steps to Reproduce (Windows)

1. Execute `flutter build windows --obfuscate --split-debug-info=build\app\symbols\windows` on the code sample
2. Run the application from: build\windows\runner\Release
3. Press the button to see if the docs path is read correctly

**Expected results:** Call to `getApplicationDocumentsDirectory()` completes and docs path is updated

**Actual results:** Call never completes

<details>
<summary>pubspec.yaml</summary>

```
name: obfuscation
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-165.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

</details>

<details>
<summary>main.dart</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key, this.dir}) : super(key: key);

  final String? dir;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: dir ?? ''),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _path = '<?>';

  Future<void> _getPath() async {
    final Directory directory;
    try {
      directory = await getApplicationDocumentsDirectory();
    } catch (e) {
      return;
    }

    setState(() { _path = directory.path; });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Text('Documents path: $_path'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _getPath,
        tooltip: 'Get path',
        child: const Icon(Icons.folder),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[√] Flutter (Channel master, 2.11.0-0.0.pre.752, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.11.0-0.0.pre.752 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a786f65700 (3 hours ago), 2022-03-03 03:01:22 -0500
    • Engine revision 993285f64d
    • Dart version 2.17.0 (build 2.17.0-165.0.dev)
    • DevTools version 2.11.1

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.64.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by tgucio** [comment] 2022-03-03 12:04
/cc @stuartmorgan 

A bit of early debug suggests that when obfuscation is enabled, PathProviderWindows isn't registered at all and instead the default MethodChannelPathProvider instance is used, which is why the calls go nowhere. After disabling obfuscation this goes away and PathProviderWindows.registerWith() is called.

**Comment by maheshmnj** [comment] 2022-03-03 13:30
Hi @tgucio, thanks for filing the issue, I was able to reproduce the issue `getApplicationDocumentsDirectory()` does not return path on the master channel with obfuscation. But it does work on the stable channel. Labeling this issue as a regression.

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.10.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (14 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[√] Flutter (Channel master, 2.11.0-0.0.pre.752, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.11.0-0.0.pre.752 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a786f65700 (in the future), 2022-03-03 03:01:22 -0500
    • Engine revision 993285f64d
    • Dart version 2.17.0 (build 2.17.0-165.0.dev)
    • DevTools version 2.11.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19044.1526]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 98.0.4758.102
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by stuartmorgan** [comment] 2022-03-03 15:04
@gaaclarke It sounds like the new lookup system not robust against obfuscation, which would be a significant regression.

**Comment by stuartmorgan** [comment] 2022-03-03 15:14
It's probably this code:

```
     if (EndsWith(library_name,
                 "dart_tool/flutter_build/dart_plugin_registrant.dart'")) {            
```

combined with https://github.com/dart-lang/sdk/issues/44215

@alexmarkov Is there a workaround we can use to call an entry point when obsfuscation is enabled?

**Comment by stuartmorgan** [comment] 2022-03-03 15:18
We're already iterating through all the libraries to find the right one... what if we just tried calling `InvokeDartPluginRegistrantIfAvailable` on every single library until one works? The ones that are wrong would just return false due it looks like:
https://github.com/flutter/engine/blob/e37b91037c4f9ee7aa2ebc47d6898913df463620/runtime/dart_plugin_registrant.cc#L57-L62

(Presumably that's slower; we could try to find it by name first, then fall back to trying everything.)

**Comment by gaaclarke** [comment] 2022-03-03 17:47
> what if we just tried calling InvokeDartPluginRegistrantIfAvailable on every single library until one works?

One problem with that is we could face naming collisions with `_PluginRegistrant`.  It would already be a bummer to have to accept the performance cost, but we'd have to try to limit the chance of collisions.  I guess if we only did that logic when the executable is obfuscated it would only collide if there was a `@pragma('vm:entry-point')`.

I'll wait to hear back about https://github.com/dart-lang/sdk/issues/44215 from @alexmarkov since that's the ideal solution considering it has come up a few times already.

**Comment by alexmarkov** [comment] 2022-03-03 17:56
Unfortunately I'm not aware of any workarounds. We should just fix the obfuscation (https://github.com/dart-lang/sdk/issues/44215).

**Comment by stuartmorgan** [comment] 2022-03-03 18:08
@alexmarkov How quickly could we get that done? This is a non-trivial regression, so we need a solution in the short term.

**Comment by alexmarkov** [comment] 2022-03-03 18:48
@mraleph might know better as he implemented the obfuscation.

**Comment by mraleph** [comment] 2022-03-04 15:00
The fix should be fairly straightforward, can be done in pure Dart. See `ObfuscationProhibitionsVisitor` - it should probably just be changed to add URIs of libraries containing entry points to the list of protected names.

**Comment by mraleph** [comment] 2022-03-08 16:02
I asked @jensjoha to look at this on the Dart side.

**Comment by stuartmorgan** [comment] 2022-03-17 18:17
It looks like a fix has landed on the Dart side, and I believe it's rolled all the way through Flutter at this point. Is this still reproducible on latest master?

**Comment by mraleph** [comment] 2022-03-18 09:08
I am gonna close given that @jensjoha has tested with Flutter and says it works.

@tgucio please verify and let us know if it does not work.

**Closed by mraleph** 2022-03-18 09:08 UTC
Labels: severe: regression, engine, plugin, has reproducible steps, P3, found in release: 2.11

**Comment by tgucio** [comment] 2022-03-18 09:23
Verified by running a binary built with `flutter build windows --obfuscate --split-debug-info=build\app\symbols\windows` using Flutter master 2.13.0-0.0.pre.142 and it starts correctly.

Thanks a lot!
