### ISSUE TITLE
PC keyboard not works on text fields in emulator when on master branch.

### ISSUE THREAD

**Issue by worldofsites** [flutter/flutter#28438] opened 2019-02-25 00:42 UTC
The problem is reproduced within a week after updating the latest packages from the master branch.
Before that, everything was working well.
Also on stable all working well.

Master:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.2.3-pre.31, on Microsoft Windows [Version 10.0.17763.316], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)
• No issues found!
```
Stable:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.316], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)
• No issues found!
```

**Comment by zoechi** [comment] 2019-02-25 06:36
I can not reproduce. Can you please provide more information?
What device, and what code, causes the issue? What does "not work" mean exactly?
```
[✓] Flutter (Channel master, v1.2.3-pre.31, on Mac OS X 10.14.3 18D42, locale en-AT)
    • Flutter version 1.2.3-pre.31 at /Users/zoechi/flutter/flutter
    • Framework revision 3423c831b9 (10 hours ago), 2019-02-24 21:48:50 +0100
    • Engine revision 0546e1e5e9
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by worldofsites** [comment] 2019-02-25 07:00
@zoechi 
Sorry for not specifying more details, I initially thought that it was not working at all, but it turned out that there are details there.
Reproduced on any android emulator devices like Nexus 5X API 28 or Nexus 9 API 28.
Keyboard input does not work for textfields with the following text input types:
- datetime
- number
- phone

![image](https://user-images.githubusercontent.com/23352829/53319617-980b2e00-3905-11e9-998f-c5002356d177.png)

Sample code:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Container(
                constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(context).size.width * 0.6,
                    minWidth: MediaQuery.of(context).size.width * 0.6),
                margin: EdgeInsets.only(left:15),
                child: TextField(
                    keyboardType: TextInputType.text,
                    decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        labelText: 'text'))),
            Container(
                constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(context).size.width * 0.6,
                    minWidth: MediaQuery.of(context).size.width * 0.6),
                margin: EdgeInsets.only(left:15),
                child: TextField(
                    keyboardType: TextInputType.datetime,
                    decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        labelText: 'datetime'))),
            Container(
                constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(context).size.width * 0.6,
                    minWidth: MediaQuery.of(context).size.width * 0.6),
                margin: EdgeInsets.only(left:15),
                child: TextField(
                    keyboardType: TextInputType.emailAddress,
                    decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        labelText: 'emailAddress'))),
            Container(
                constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(context).size.width * 0.6,
                    minWidth: MediaQuery.of(context).size.width * 0.6),
                margin: EdgeInsets.only(left:15),
                child: TextField(
                    keyboardType: TextInputType.multiline,
                    decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        labelText: 'multiline'))),
            Container(
                constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(context).size.width * 0.6,
                    minWidth: MediaQuery.of(context).size.width * 0.6),
                margin: EdgeInsets.only(left:15),
                child: TextField(
                    keyboardType: TextInputType.number,
                    decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        labelText: 'number'))),
            Container(
                constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(context).size.width * 0.6,
                    minWidth: MediaQuery.of(context).size.width * 0.6),
                margin: EdgeInsets.only(left:15),
                child: TextField(
                    keyboardType: TextInputType.phone,
                    decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        labelText: 'phone'))),
            Container(
                constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(context).size.width * 0.6,
                    minWidth: MediaQuery.of(context).size.width * 0.6),
                margin: EdgeInsets.only(left:15),
                child: TextField(
                    keyboardType: TextInputType.url,
                    decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(vertical: 4),
                        labelText: 'url'))),
          ]),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

**Comment by zoechi** [comment] 2019-02-25 07:07
Thanks for the update! I can reproduce that.

**Comment by zoechi** [comment] 2019-02-25 07:08
I added `today` because I can reproduce and I think it's a serious problem that might affect lots of developers.

**Comment by dnfield** [comment] 2019-02-25 23:05
@matthew-carroll any chance this is related to the platform channels refactor?

**Comment by matthew-carroll** [comment] 2019-02-25 23:07
I'll try to reproduce and investigate.

**Comment by matthew-carroll** [comment] 2019-02-25 23:12
I have verified that the reported situation does occur on a Pixel emulator.  Now I'll investigate the root cause.

**Comment by matthew-carroll** [comment] 2019-02-25 23:19
I have verified that key down and key up events are being recognized on the Android side, they are being packaged as system channel JSON messages, and they are being sent to Flutter.  It looks likely that this issue is on the Flutter side and is probably not related to recent Android embedding changes.

**Comment by matthew-carroll** [comment] 2019-02-25 23:35
I'm going to assign this to @gspencergoog who is now investigating the Flutter side.  Feel free to assign back to me if the issue appears to trace back to Android again.

**Comment by zoechi** [comment] 2019-02-26 13:28
@worldofsites this should be fixed in latest `master`.
Please let us know if you're still seeing it.

**Closed by zoechi** 2019-02-26 13:28 UTC
Labels: a: text input, framework, severe: regression, ⚠ TODAY

**Comment by worldofsites** [comment] 2019-02-26 14:07
@zoechi 
All works now!
Thanks!
