### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by BugraUmut** [flutter/flutter#115615] opened 2022-11-18 01:09 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2233:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:822:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:841:49)
#5      FlutterVmService.flutterDebugDumpRenderTree (package:flutter_tools/src/vmservice.dart:587:50)
#6      ResidentHandlers.debugDumpRenderTree (package:flutter_tools/src/resident_runner.dart:683:53)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1760:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.6.0-1.0.pre.12, on Microsoft Windows [Version 10.0.19044.2251], locale
    tr-TR)
    [32m•[39m Flutter version 3.6.0-1.0.pre.12 on channel master at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ff75451856 (8 days ago), 2022-11-10 03:07:12 -0500
    [32m•[39m Engine revision a42b2d9b94
    [32m•[39m Dart version 2.19.0 (build 2.19.0-382.0.dev)
    [32m•[39m DevTools version 2.19.0

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at C:\Users\pinzon\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default
      components

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.73.1)
    [32m•[39m VS Code at C:\Users\pinzon\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.52.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.107
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.42

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e3c29ec00c9c825c891d75054c63fcc46454dca1

**Comment by darshankawar** [comment] 2022-11-18 07:21
Closing as duplicate of https://github.com/flutter/flutter/issues/101962

**Closed by darshankawar** 2022-11-18 07:21 UTC
Labels: in triage
