### ISSUE TITLE
[in_app_purchase] Apps must use Billing Library version 3 or newer.

### ISSUE THREAD

**Issue by ibragunduz** [flutter/flutter#79529] opened 2021-04-01 06:46 UTC
**Starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing [Library version 3 or newer.](https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html)**

Flutter In-app purchase library using older than [library version 3](https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html). 

<img width="984" alt="Ekran Resmi 2021-04-01 09 41 16" src="https://user-images.githubusercontent.com/24707258/113253770-69bf6000-92ce-11eb-92da-b7e4749d3317.png">

**Comment by TahaTesser** [comment] 2021-04-01 08:40
Hi @ibragunduz 
This has been fixed in https://github.com/flutter/flutter/issues/75204 and landed in [0.5.0](https://pub.dev/packages/in_app_purchase/changelog#050) release 
Closing as duplicate of https://github.com/flutter/flutter/issues/75204
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-01 08:40 UTC
Labels: in triage
