### ISSUE TITLE
New flutter google map create image from asset giving issue due its future 

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#32024] opened 2019-05-03 06:58 UTC
I am having problem to update my markers with custom icon. Earlier function bitmapdescriptor works fine but with the new function I am having issue cause it has the future in it.The problem now I have to put await here    Future<BitmapDescriptor> returnValue = _createMarkerImageFromAsset(iconPath); and the whole function I have put sync and Future then I get error at here markers: markersFrom("InitialState",0,0), cause I cant set it with Future. So what is the best resolution on this?

Below is snippet of my codes.
```

> Widget build(BuildContext context) {
>       return Stack(
>       children: <Widget>[
>                GoogleMap(
>                   onMapCreated: onMapCreated,
>                   initialCameraPosition: new CameraPosition(
>                       target: LatLng(3.326411697920109, 102.13127606037108)),
>                   //trackCameraPosition: true,
>                   zoomGesturesEnabled: true,
>                   markers: markersFrom("InitialState",0,0),
>                   mapType: MapType.normal,
>                 )  
>       ],
>     );
>   }
> 
> void onMapCreated(GoogleMapController controller) {
>     mapController = controller;
>     markersFrom("MoveMarkerState",1.71266305,100.40908813);
>   }
>    Set<Marker>  markersFrom(String state,double latitude, double longitude)  {
>     Set<Marker> markers = {};
>    double minLatitude = 0, maxLatitude = 0, minLongitude = 0, maxLongitude = 0;
>    
>     if(state=="InitialState"){
>       
>     }
>     else if(state=="CleanState"){
> 
>     }
>     else if(state=="MoveMarkerState"){
>       var i=0;  
>              
>              
>               String iconPath = "";
>               
>               if (Platform.isAndroid) iconPath = "lib/assets/and_tripStart.png";
>               if (Platform.isIOS) iconPath = "lib/assets/ios_tripStart.png";
>               Future<BitmapDescriptor> returnValue = _createMarkerImageFromAsset(iconPath);
>             
>               final markerId = MarkerId(i.toString());
>               final marker = Marker(
>                 markerId: markerId,
>                 position: LatLng(latitude, longitude),
>                 //icon: BitmapDescriptor.fromBytes(iconPath);
>                 icon: returnValue,  
>                 infoWindow: InfoWindow(title: "", snippet: ''),
>                 
>               );
>               markers.add(marker);     
>     }
>     print("Markers size is "+markers.length.toString());
>     return markers;
>     
>   }
>   Future <BitmapDescriptor> _createMarkerImageFromAsset(String iconPath) async {
>    ImageConfiguration configuration = ImageConfiguration();
>               BitmapDescriptor bmpd = await BitmapDescriptor.fromAssetImage(
>               configuration, iconPath);
>     return bmpd;
>   }
> 
```

**Comment by tobischo** [comment] 2019-07-21 09:54
```dart
var icon;
await _createMarkerImageFromAsset(iconPath)
        .then((i) {
          icon = i
        }
```
works for me

That does require `onMapCreated` to be `async` though, which wasn't a problem in my case

**Comment by BondarenkoStas** [comment] 2019-10-15 10:58
@newbieflutter did you manage to solve the issue?

**Comment by webwarrior** [comment] 2019-10-20 09:20
I am stuck on this too

**Comment by darshankawar** [comment] 2021-05-04 10:10
@newbieflutter 
Is this still a valid issue using plugin's [latest](https://pub.dev/packages/google_maps_flutter/install) version and with latest framework version ?
If so, can you provide updated `flutter doctor -v` and complete minimal reproducible code sample ?

Thanks.

**Comment by webwarrior** [comment] 2021-05-04 10:44
I will give it a try.

**Comment by TahaTesser** [comment] 2021-05-27 12:49
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-05-27 12:49 UTC
Labels: p: first party, p: maps, plugin
