### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/sm/Documents/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.

### ISSUE THREAD

**Issue by 1321353970** [flutter/flutter#62335] opened 2020-07-27 14:16 UTC
## Command
```
flutter assemble --output=/Users/sm/Desktop/StudySpace/flutter_module/.ios/Flutter/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation= -dDartObfuscation=false -dEnableBitcode= --DartDefines= -dExtraFrontEndOptions= release_ios_bundle_flutter_assets
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/sm/Documents/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:69:31)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
#12     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/sm/Documents/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sm/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.flutter_module
**iOS bundle identifier**: com.flutterModule
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4

**Comment by TahaTesser** [comment] 2020-07-27 14:39
Hi @1321353970 
I cannot reproduce this issue on latest beta channel. Since dev version is in beta now  [reference](https://github.com/flutter/flutter/issues/60079#issuecomment-648652537)
Can you upgrade to beta and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Related to https://github.com/flutter/flutter/issues/60079
Might be fixed by https://github.com/flutter/flutter/pull/57874

Thank you

**Comment by TahaTesser** [comment] 2020-08-25 15:59
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-25 15:59 UTC
Labels: in triage
