### ISSUE TITLE
Can flutter make the default insertion point of a TextEditingValue be at the end of the text?

### ISSUE THREAD

**Issue by jiajiabingcheng** [flutter/flutter#14446] opened 2018-02-03 00:06 UTC
Hi Flutter team, 

I'm using TextEditingValue to construct my TextEditingController for my TextField.

I found that if not passing in the TextSelection with the string length as the offset, the cursor would be inserted at the beginning of the text. Should it be at the end of text? Or did I not use it correctly?

What I did is:
```dart
TextEditingController _controller = new TextEditingController.fromValue(new TextEditingValue(
    text: initialValue,
    selection: new TextSelection.collapsed(
      offset: initialValue.length,
    ))
);
```
Thanks!

**Comment by zoechi** [comment] 2018-12-19 07:00
Similar #11416

**Comment by goderbauer** [comment] 2018-12-28 19:43
Dupe of #11416.

**Closed by goderbauer** 2018-12-28 19:43 UTC
Labels: a: quality, a: text input, framework, severe: API break
