### ISSUE TITLE
[SelectionArea] issue on any mouse region text

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#110655] opened 2022-08-31 09:58 UTC
I'm using flutter 3.3 and tried the new widget for SelectionArea, 
```dart
...
                      MaterialApp(
                      ....
                      title: S.current.appTitle,
                      builder: (context, child) => MediaQuery(
                        data: MediaQuery.of(context).copyWith(
                            textScaleFactor: getTheTextFactorFix(context)),
                        child: SelectionArea(child: child!),
                      ),
                      color: Theme.of(context).scaffoldBackgroundColor,
                      )
...
```
the issue here is while I'm putting the mouse or hover on an InkWall or on ElevatedButton that has a Text widget as a child, the mouse aims to select the text, and the hover mouse looks like it's not about to tap but select a text.

**Comment by danagbemava-nc** [comment] 2022-08-31 13:13
Hi @nimr77, please provide a complete minimal runnable code sample so that we can investigate this. 

Thank you

**Comment by nimr77** [comment] 2022-08-31 13:21
it's quite simple to reduce, just wrap any button that has a Text as a child, for example (ElevatedButton) with ```SelectionArea```
you will see that you can select the text in the button, but on the web/desktop this is not expected behavior, so if I wrap my Scaffold with ```SelectionArea``` I will get an issue with the buttons inside the scaffold.

**Comment by danagbemava-nc** [comment] 2022-09-01 07:19
Hi @nimr77, I believe this is a duplicate of https://github.com/flutter/flutter/issues/104595. 

As such, I'll be closing this in favor of the linked issue. 

Kindly follow up there for updates. 

If you disagree, leave a comment below and I will reopen this. Kindly upvote the linked issue. 

Thank you

**Closed by danagbemava-nc** 2022-09-01 07:19 UTC
Labels: in triage
