### ISSUE TITLE
Cannot  using http.post 

### ISSUE THREAD

**Issue by dione24** [flutter/flutter#55620] opened 2020-04-25 02:57 UTC
Exception has occurred.
FormatException (FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^
)

**Comment by stuartmorgan** [comment] 2020-04-25 04:35
Duplicate of #55621

**Closed by stuartmorgan** 2020-04-25 04:35 UTC
