### ISSUE TITLE
Failed assertion: line 2247 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by abdosaidbassuony** [flutter/flutter#41340] opened 2019-09-26 03:37 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment] 2019-09-26 06:49
Hello @abdosaidbassuony !

Thank you for posting.
However, without any additional information, such as the code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.
But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-09-26 06:49 UTC
