### ISSUE TITLE
Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized. (can't white label an app)

### ISSUE THREAD

**Issue by GilbertoGmobil** [flutter/flutter#78789] opened 2021-03-22 14:18 UTC
## Bug report

**Describe the bug**
I'm transforming my code in a white_labeling way to re-use the same code to another client. In my first app I was using firebase_messaging with its google-services.json. But in this new client I won't use it... I tried to run and it throws this error:

```
E/flutter ( 7850): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized. Have you added the "google-services.json" file to the project? 
E/flutter ( 7850):     
E/flutter ( 7850):     View the Android Installation documentation for more information: https://firebase.flutter.dev/docs/installation/android
E/flutter ( 7850):     
E/flutter ( 7850): #0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:86:9)
E/flutter ( 7850): <asynchronous suspension>
E/flutter ( 7850): #1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:44:9)
E/flutter ( 7850): <asynchronous suspension>
E/flutter ( 7850): #2      main (package:app_md/main.dart:72:3)
E/flutter ( 7850): <asynchronous suspension>
E/flutter ( 7850): 
```

How can I deal with child projects that don't will use firebase_messaging:? I'm using the 'config' parameter to do this heritage

`flutter doctor `
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H524 darwin-x64, locale pt-BR)
    • Flutter version 2.0.2 at /Users/interno/Documents/FlutterSDK/flutter
    • Framework revision 8962f6dc68 (8 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/interno/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • SM T580 (mobile) • 33007cb4a621a5fb • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

`flutter pub deps -- --style=compact`
```
Dart SDK 2.12.1
Flutter SDK 2.0.2
raffer_app 1.0.0+1

dependencies:
- app_md 1.0.0+1 [config flutter intl http provider shared_preferences hive hive_flutter path_provider cpfcnpj mask_text_input_formatter mask_shifter flux_validator_dart email_validator carousel_slider dio permission_handler open_file flutter_local_notifications cached_network_image url_launcher image_picker table_calendar flutter_barcode_scanner firebase_storage firebase_core qr_code_scanner pdf printing cloud_firestore firebase_messaging drag_and_drop_gridview file_picker image_viewer flutter_localizations cupertino_icons]
- cupertino_icons 1.0.2
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

dependency overrides:
- config 1.0.0

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- barcode 1.17.1 [meta qr]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image 2.5.1 [flutter flutter_cache_manager octo_image]
- carousel_slider 2.3.4 [flutter]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore 0.16.0+1 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_firestore_platform_interface 3.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- cpfcnpj 1.0.3
- crypto 2.1.5 [collection convert typed_data]
- dio 3.0.10 [http_parser path]
- drag_and_drop_gridview 1.0.8 [flutter]
- email_validator 1.0.6
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- file_picker 2.1.7 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging 8.0.0-dev.15 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.6 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_barcode_scanner 1.0.2 [flutter flutter_plugin_android_lifecycle]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_local_notifications 3.0.3 [flutter platform flutter_local_notifications_platform_interface timezone]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flux_validator_dart 1.0.3
- hive 1.4.4+1 [meta crypto]
- hive_flutter 0.3.1 [flutter hive path_provider path]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- image_viewer 1.0.0 [flutter]
- intl 0.17.0 [clock path]
- js 0.6.3
- mask_shifter 0.1.0 [flutter]
- mask_text_input_formatter 1.2.1 [flutter]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- octo_image 0.3.0 [flutter flutter_blurhash]
- open_file 3.1.0 [flutter ffi]
- path 1.8.0
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.28 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.5 [path_provider_platform_interface meta path flutter ffi win32]
- pdf 1.13.0 [archive barcode crypto image meta path_parsing vector_math xml]
- pedantic 1.11.0
- permission_handler 5.1.0+2 [flutter meta permission_handler_platform_interface]
- permission_handler_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- printing 3.7.2 [flutter flutter_web_plugins image js meta pdf plugin_platform_interface]
- process 4.1.0 [file path platform]
- provider 4.3.3 [collection flutter nested]
- qr 1.3.0 [meta]
- qr_code_scanner 0.0.14 [flutter]
- quiver 2.1.5 [matcher meta]
- rxdart 0.25.0
- service_worker 0.2.4 [js]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- simple_gesture_detector 0.1.6 [flutter]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- table_calendar 2.3.3 [flutter intl simple_gesture_detector]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.5.9 [path]
- typed_data 1.3.0 [collection]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0
- win32 2.0.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
```

I used this way: https://medium.com/@ramiechaarani/how-to-make-a-white-label-app-in-flutter-6c3ea40fd7d5

In sum:

I have One main app that initially I did to one client. This client uses firebase. Now I wanna keep only the main functions and separate it to use in another client. The problem is, this new client does not use firebase, so when i try to run the app it throws that error because I haven't a google-services.json. How can I say that in this project (which inherit the main project) I don't will use firebase?

Expected outcome: in the second brand app don't use firebase..

maybe there is a way to override dependency?

**Comment by pedromassangocode** [comment] 2021-03-22 14:25
Hi @GilbertoGmobil 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-22 14:25 UTC
Labels: in triage
