### ISSUE TITLE
Chip widget showing square corners after update

### ISSUE THREAD

**Issue by bcurley2314** [flutter/flutter#47341] opened 2019-12-18 15:18 UTC
After updating Flutter to (v1.13.3-pre.60) on master channel, all of the `Chip()` widgets have square corners. Applying a `RoundedRectangleBorder()` to the shape property doesn't have any effect.

`[✓] Flutter (Channel master, v1.13.3-pre.60, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.0)
[✓] Connected device (3 available)

• No issues found!
Brians-MacBook-Pro-2:rydrapp briancurley$ flutter doctor -v
[✓] Flutter (Channel master, v1.13.3-pre.60, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.3-pre.60 at /Users/briancurley/Documents/Rydr/flutter
    • Framework revision ceef460a64 (7 hours ago), 2019-12-18 00:23:02 -0800
    • Engine revision 500f9cedf6
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 2d332ee1d3)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/briancurley/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 1BD8D1EA-8724-4D64-86BC-738AD9791F6B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 79.0.3945.79
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!`

**Comment by HansMuller** [comment] 2019-12-18 18:31
It looks like this is a duplicate of https://github.com/flutter/flutter/issues/47350

CC @goderbauer

**Comment by goderbauer** [comment] 2019-12-18 23:33
I rolled back the bad change.

**Closed by goderbauer** 2019-12-18 23:33 UTC
Labels: f: material design, framework
