### ISSUE TITLE
[Video Player] Wrap video player to opacity widget makes video stucks.

### ISSUE THREAD

**Issue by triannoviandi** [flutter/flutter#62285] opened 2020-07-26 08:30 UTC
Hi, im trying to decrease video player opacity by wrap it into Opacity widget, and the video didn't play .

```
Opacity(
     opacity: .2, child: VideoPlayer(_videocontroller)),
```

**Comment by darshankawar** [comment] 2020-07-27 10:02
Issue is replicable on latest dev channel (1.20.0-0.0.pre) and with latest version of `video_player` plugin.
Basically, if we wrap video player with `Opacity` < 1, then the video doesn't play.  Whereas, with opacity with 1, video plays properly.
Tested on Android 8.1.0 device and with official video player [example](https://flutter.dev/docs/cookbook/plugins/play-video).

[62285.mp4.zip](https://github.com/flutter/flutter/files/4981321/62285.mp4.zip)

**Comment by triannoviandi** [comment] 2020-07-27 10:38
> Issue is replicable on latest dev channel (1.20.0-0.0.pre) and with latest version of `video_player` plugin.
> Basically, if we wrap video player with `Opacity` < 1, then the video doesn't play. Whereas, with opacity with 1, video plays properly.
> Tested on Android 8.1.0 device and with official video player [example](https://flutter.dev/docs/cookbook/plugins/play-video).
> 
> [62285.mp4.zip](https://github.com/flutter/flutter/files/4981321/62285.mp4.zip)

exactly

**Comment by edurossi** [comment] 2020-09-19 12:40
I'm having the same problem. Any workaround for this issue?

**Comment by ollydixon** [comment] 2020-12-04 18:19
Same issue, any work around?

**Comment by nt4f04uNd** [comment] 2020-12-30 20:12
@edurossi the only workaround i can come up is wrapping video player into stack and overlay it with some widget with opacity, which was applicable for my case
example:
```dart
return AspectRatio(
  aspectRatio: 1.0,
  child: Stack(
    alignment: Alignment.center,
    children: [
      initialized ? VideoPlayer(logoVideoController) : SizedBox.shrink(),
      AnimatedSwitcher(
        duration: const Duration(milliseconds: 900),
        switchInCurve: Curves.easeOutCubic,
        switchOutCurve: Curves.easeInCubic,
        child: initialized
            ? SizedBox.shrink()
            : Container(color: theme.colorScheme.background),
      ),
    ],
  ),
);
```

**Comment by maheshmnj** [comment] 2021-06-22 09:26
Hi @triannoviandi ,
Thanks for filing the issue. I can confirm the issue is not reproducible with latest version of the plugin ```video_player: ^2.1.6``` on the latest flutter stable channel. I would request you to verify this by upgrading to the latest stable version of flutter and use the latest version of the video_player plugin.

Here is the sample code used. 

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(VideoApp());
}
class VideoApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _VideoAppState();
  }
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4',
    )..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Video Demo',
        home: Scaffold(
          body: Center(
            child: _controller.value.isInitialized
                ? Opacity(
                    opacity: 0.2,
                    child: AspectRatio(
                      aspectRatio: _controller.value.aspectRatio,
                      child: VideoPlayer(_controller),
                    ),
                  )
                : Container(),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () async {
              final duration = await _controller.position;

              /// check if video has ended
              if (duration!.inSeconds == _controller.value.duration.inSeconds) {
                /// restart the video
                await _controller.seekTo(Duration.zero);
              }
              _controller.value.isPlaying
                  ? await _controller.pause()
                  : await _controller.play();
              setState(() {});
            },
            child: Icon(
              _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
            ),
          ),
        ));
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (11 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

### output 

https://user-images.githubusercontent.com/31410839/122899258-4e15a400-d369-11eb-8be8-a030da924806.mov

**Comment by TahaTesser** [comment] 2021-07-14 12:41
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-14 12:41 UTC
Labels: found in release: 1.20, has reproducible steps, p: first party, p: video_player, plugin, waiting for customer response

**Comment by edurossi** [comment] 2021-07-19 13:14
I tested today and it seems that the problem is solved. Thank you.
