### ISSUE TITLE
Cupertino text selection options shouldn’t scale

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#40628] opened 2019-09-16 22:29 UTC
Similar to nav bar buttons, title, pickers and some other Cupertino widgets, the text selection options should stay at `1.0` scaling factor, regardless of the user settings. You can see that even if you set your scale down or up, natively, it will stay at `1.0`.

![IMG_0041](https://user-images.githubusercontent.com/27860743/64998134-e7816d80-d8da-11e9-845a-6867bf285b38.jpg)

In the screenshot provided, the scale is set to max in the user settings and the text just overflows for the selection options. The opposite happens if the font is set to minimum, where the font looks smaller (as expected). If set to default it’s pretty much even with the native, I’d say. 

I suggest wrapping it with a `MediaQuery` with the font scale locked to `1.0`.

```
[✓] Flutter (Channel dev, v1.10.1, on Mac OS X 10.14.6 18G87, locale pt-PT)
    • Flutter version 1.10.1 at /Users/miguelruivo/DevTools/flutter
    • Framework revision ce45c2d3e6 (10 days ago), 2019-09-06 20:11:41 -0400
    • Engine revision b9ce2500d9
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)
```

**Comment by HansMuller** [comment] 2019-09-17 00:15
CC @justinmc

**Comment by justinmc** [comment] 2019-09-17 15:43
Good catch!  I agree with everything here.  Should hopefully be an easy fix.

**Comment by miguelpruivo** [comment] 2019-09-17 18:19
@justinmc also, I'm not sure if that vertical line should crop the balloon arrow. :eyes: I believe that natively, it is drawn on the edge of the closer option (which in this case is _copy_).

**Comment by miguelpruivo** [comment] 2019-09-17 18:21
@justinmc also, I'm not sure if that vertical line should crop the balloon arrow. 👀 I believe that natively, it is always drawn below an option, which prevents this to happen.

**Comment by miguelpruivo** [comment] 2019-09-17 18:22
@justinmc also, I'm not sure if that vertical line should crop the balloon arrow. 👀 I believe that natively, it is always drawn below an option, which prevents that to happen.

**Comment by LongCatIsLooong** [comment] 2019-09-17 23:29
From what I'm seeing on iOS 13.1 the text does scale with system text size settings, but unfortunately I wasn't able to get the exact font size since the menu is not visible in xcode. 

As for the other issue, it seems iOS does that on a best effort basis. It's already been tracked here: https://github.com/flutter/flutter/issues/11274.

**Comment by miguelpruivo** [comment] 2019-11-26 02:55
@LongCatIsLooong I’m not sure if this is the same. #11274 relates to the indicator not being properly aligned sometimes.

This is regarding the font size that should stay at its default size despite user settings, thus, preventing the scale factor by just wrapping it with a `MediaQuery` with scale factor set to 1.0, should be enough.

**Comment by LongCatIsLooong** [comment] 2019-11-26 03:26
@miguelpruivo sorry I meant the issue described in https://github.com/flutter/flutter/issues/40628#issuecomment-532341862 is #11274. As for text scaling, from the screenshots the native selection menu's font size does seem to change as the scaling factor increases.

**Comment by miguelpruivo** [comment] 2019-11-26 10:18
That’s right @LongCatIsLooong, they’ve changed the behavior to act similar to the bottom action sheet where the text scales only a bit upwards and never downwards, this is, never below 1.0 but up to 1.1 or 1.2.

You can test it by yourself by setting to default, then to minimum and then to maximum. Max will have a slight upscale but minimum won’t change at all.

**Comment by TahaTesser** [comment] 2020-03-30 15:32
Hi @miguelpruivo 

Here i tried to reproduce it 

![Simulator Screen Shot - iPhone 11 - 2020-03-30 at 21 01 30](https://user-images.githubusercontent.com/48603081/77931412-c4903700-72c9-11ea-8046-6e322deddfb5.png)

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.16.3 at /Users/taha/Code/flutter_dev
    • Framework revision be3a4b37b3 (4 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • iPhone 11  • 41EB2A85-7EB4-4FD2-8978-FBBE2A681D74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.4 19E266
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 80.0.3987.149
    • Web Server • web-server                           • web-javascript •
      Flutter Tools

• No issues found!
```


Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment] 2020-04-24 11:35
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-04-24 11:35 UTC
Labels: a: text input, f: cupertino, framework, waiting for customer response

**Comment by aris-1** [comment] 2021-07-14 09:51
Hi this is still an issue

<img width="267" alt="Screenshot 2021-07-14 at 11 36 35" src="https://user-images.githubusercontent.com/70529421/125601627-03afa403-962e-41e0-8f42-145fc2adeb52.png">

If the user sets the font size very big in Settings -> Accessibility -> Larger text 

flutter doctor -v                
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-ZA)
    • Flutter version 2.2.3 at /Applications/flutter
    • Framework revision f4abaa0735 (13 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /users/user/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 199F82C4-F570-46EA-9AFB-2B8F13E953FF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

**Comment by justinmc** [comment] 2021-07-21 14:59
@aris-1 Is your problem covered by https://github.com/flutter/flutter/issues/45481?

**Comment by aris-1** [comment] 2021-07-21 15:06
Yes, it is the same issue, but last comments say that it is fine, when it is not still today.
