### ISSUE TITLE
[web-server] Flutter Debug Extension not connecting to docker container

### ISSUE THREAD

**Issue by adrubesh** [flutter/flutter#78971] opened 2021-03-24 14:24 UTC
## Steps to Reproduce

1. Create a Dockerfile with Flutter installed
2. Run with exposed web port (8000 in my case): `docker run -v appcode:/app -p 8000:8000 my-flutter-container bash` 
3. Run flutter in the container: `flutter run -d web-server --web-port 8000 --web-hostname 0.0.0.0`
4. On client machine, navigate to http://localhost:8000

**Expected results:** 
The flutter app + debug extension to work.

**Actual results:** 
The flutter app loads, I see the app, but the extension won't connect.
![image](https://user-images.githubusercontent.com/33096067/112326490-91854700-8c82-11eb-987e-a385af4d567c.png)
![image](https://user-images.githubusercontent.com/33096067/112326578-a1049000-8c82-11eb-99ba-b9bd76370746.png)

<details>
  <summary>Logs</summary>

```
dev@bf829b73d06b:/app$ flutter run -d web-server --web-port 8000 --web-hostname 0.0.0.0 --verbose
[  +67 ms] executing: uname -m
[  +29 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +12 ms] executing: [/home/dev/.local/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[        ] executing: [/home/dev/.local/flutter/] git tag --points-at 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[   +2 ms] Exit code 0 from: git tag --points-at 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[        ] 2.1.0-12.1.pre
[  +41 ms] executing: [/home/dev/.local/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/dev/.local/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +25 ms] Unable to locate an Android SDK.
[   +5 ms] executing: [/home/dev/.local/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +63 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] Skipping pub get: version match.
[ +120 ms] Generating /app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +101 ms] Launching lib/main.dart on Web Server in debug mode...
[  +99 ms] Updating assets
[  +70 ms] Waiting for connection from debug service on Web Server...
[  +95 ms] <- reset
[   +6 ms] /home/dev/.local/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/dev/.local/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/dev/.local/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.VVBCXI/flutter_tool.DHQLAH/app.dill --libraries-spec
file:///home/dev/.local/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /app/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/tmp/flutter_tools.VVBCXI/flutter_tools.QLUNHA --filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///home/dev/.local/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +17 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+16526 ms] Waiting for connection from debug service on Web Server... (completed in 16.6s)
[        ] Synced 29.2MB.
[        ] <- accept
[        ] Caching compiled dill
[  +25 ms] lib/main.dart is being served at http://0.0.0.0:8000
[        ] The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or
Edge devices
           for an improved development workflow.
[   +6 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
```

```
dev@bf829b73d06b:~$ flutter analyze
Analyzing dev...
No issues found! (ran in 0.6s)

```

```
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale en_US)
    • Flutter version 2.1.0-12.1.pre at /home/dev/.local/flutter
    • Framework revision 8264cb3e8a (2 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

```

</details>

**Comment by TahaTesser** [comment] 2021-03-25 11:19
Hi @adrubesh 
This is not related to flutter itself but VS Code Flutter Extension

Nevertheless, I tried it out of curiosity, extensions woks fine in a container and app launches with no issues

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-25 11:19 UTC
Labels: in triage

**Comment by adrubesh** [comment] 2021-03-25 12:02
@TahaTesser I'm not using Vscode.

**Comment by TahaTesser** [comment] 2021-03-25 14:49
Hi @adrubesh 
What extension in the screenshot is this? What is "Flutter Debug Extension "? 
https://user-images.githubusercontent.com/33096067/112326578-a1049000-8c82-11eb-99ba-b9bd76370746.png

Also please provide complete Dockerfile and Linux distro details
Thank you

**Comment by adrubesh** [comment] 2021-03-25 15:58
@TahaTesser  Here is a sample Dockerfile that I tested out. (Add to a sample flutter project directory that's already been initialized via `flutter create .`) and then do a `docker build -t test-flutter-container .` 

```
FROM debian:bullseye

RUN 	apt update && \
	apt -y upgrade && \
	apt -y install \
	curl \ 
	git \
	unzip \
	zip \
	xz-utils

# Create our user
RUN useradd -c "development user" -m -s /bin/bash -u 1000 dev

USER dev
RUN mkdir -p /home/dev/.local
RUN git clone https://github.com/flutter/flutter.git -b beta /home/dev/.local/flutter 
ENV PATH=$PATH:/home/dev/.local/flutter/bin
RUN flutter pub global activate devtools


RUN mkdir -p /home/dev/app
WORKDIR /home/dev/app
COPY --chown=dev:dev . .

RUN flutter clean 

ENTRYPOINT ["flutter", "run", "--web-port", "8000", "--web-hostname", "0.0.0.0", "-d", "web-server"]

EXPOSE 8000
```

The extension is the browser extension, 'Dart Debug' from https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm that the CLI mentions to use when using the `web-server` device.

**Comment by TahaTesser** [comment] 2021-03-26 12:04
Hi @adrubesh 
Can you point to the Flutter documentation where it mentions this dart plugin? link it please 
Thank you

**Comment by adrubesh** [comment] 2021-03-26 12:10
![image](https://user-images.githubusercontent.com/33096067/112629462-5c076780-8e02-11eb-9805-bb9124f3bd48.png)
It's output in the console as soon as you do a `flutter run`

**Comment by TahaTesser** [comment] 2021-03-29 09:41
@adrubesh 
Thanks for the Dockerfile and steps, I can reproduce it on Ubuntu (FYI using the same Dockerfile on Windows doesn't even load the page)

<details> 
<summary>preview</summary> 

![image](https://user-images.githubusercontent.com/48603081/112818295-0b0aa400-908c-11eb-8821-3ff6d05d4cfe.png)


</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale en_IN)
    • Flutter version 2.1.0-12.1.pre at /home/taha/Code/flutter_dev
    • Framework revision 8264cb3e8a (3 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
[✓] Android Studio (version 4.1)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0
[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90
• No issues found!
```
	
</details>

**Comment by jonahwilliams** [comment] 2021-06-08 22:59
FYI @annagrin
