### ISSUE TITLE
DateTime - Add/Subtract - Around Daylight Savings Time Change

### ISSUE THREAD

**Issue by LAPPIT** [flutter/flutter#138069] opened 2023-11-08 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Take a date before the daylight savings time change
2. Add any number of days, to make the result after daylight savings time change
3. Take a date after the daylight savings time change
4. Subtract any number of days, to make the result before daylight savings time change

### Expected results

Since I started with a date, without any time (at midnight), I exptected the result to be at midnight as well (in both cases).

### Actual results

Seems to add/subtract 24 hours per day, instead of just the day. Get some strange results around the daylight savings time change. See hardcopy.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo DateTime & Daylight Savings Time',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final DateTime dateBeforeDaylightSavingsChange = DateTime(2023, 10, 27);

  final DateTime dateAfterDaylightSavingsChange = DateTime(2023, 10, 31);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('DateTime Add/Subtract'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Sweden 2023 Daylight Savings Time change:'),
            const SizedBox(height: 10),
            const Text('2023-10-29'),
            const SizedBox(height: 50),
            const Text('A date before the change:'),
            const SizedBox(height: 10),
            Text('$dateBeforeDaylightSavingsChange'),
            const SizedBox(height: 20),
            const Text('Add 5 days - The result is:'),
            const SizedBox(height: 10),
            Text('${dateBeforeDaylightSavingsChange.add(const Duration(days: 5))}'),
            const SizedBox(height: 20),
            const Text('Expected:'),
            const SizedBox(height: 10),
            const Text('2023-11-01 00:00:00.000'),
            const SizedBox(height: 50),
            const Text('A date after the change:'),
            const SizedBox(height: 10),
            Text('$dateAfterDaylightSavingsChange'),
            const SizedBox(height: 20),
            const Text('Subtract 5 days - The result is:'),
            const SizedBox(height: 10),
            Text('${dateAfterDaylightSavingsChange.subtract(const Duration(days: 5))}'),
            const SizedBox(height: 20),
            const Text('Expected:'),
            const SizedBox(height: 10),
            const Text('2023-10-26 00:00:00.000'),

          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20231108_102447](https://github.com/flutter/flutter/assets/16556902/dd19e838-6724-450b-9b6f-ffab53a99c0f)

</details>

### Logs

<details><summary>Logs</summary>

```consolePerforming hot reload...
Syncing files to device sdk gphone64 x86 64...
Reloaded 1 of 689 libraries in 771ms (compile: 43 ms, reload: 183 ms, reassemble: 254 ms).
D/EGL_emulation(18614): app_time_stats: avg=79554.46ms min=85.21ms max=238396.12ms count=3
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
C:\Users\Mariette\IdeaProjects\testdatetime>flutter doctor -v
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale en-SE)
    • Flutter version 3.13.9 on channel stable at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)  

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Mariette\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32825.248
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\Mariette\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 118.0.5993.120
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 118.0.2088.61

[√] Network resources
    • All expected network resources are available.

• No issues found!

C:\Users\Mariette\IdeaProjects\testdatetime>

```

</details>

**Comment by dam-ease** [comment] 2023-11-08 11:32
Thanks for filing this. I can't seem to reproduce this on my end. I tested with the code sample provided on an emulator (changed the location of the emulator to Sweden) but I can see the expected behaviour. Can you help with more information on how this reproduces?

![Screenshot_1699442867](https://github.com/flutter/flutter/assets/53122008/4f3ae6de-a849-43b5-9a92-23eefdebedde)

<details><summary>flutter doctor -v</summary>
<p>

```

[!] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile) • 00008110-001964480AE1801E            • ios
      • iOS 17.0.2 21A351
    • iPhone 15 Pro Max (mobile) • 56A225C9-B8F6-4201-A0AE-8C3CFA4CE152 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 119.0.6045.105

[!] Network resources
    ✗ A network error occurred while checking "https://github.com/": Operation
      timed out

! Doctor found issues in 3 categories.
``` 

</p>
</details>

**Comment by LAPPIT** [comment] 2023-11-08 14:52
Did some more googling and found a comment that it is the way it is and they referenced to the documentation of  DateTime add/subtract. 

Found that it says:

====================

>   _/// Returns a new [DateTime] instance with [duration] added to [this].
>   ///
>   /// ```dart
>   /// final today = DateTime.now();
>   /// final fiftyDaysFromNow = today.add(const Duration(days: 50));
>   /// ```
>   ///
>   /// Notice that the duration being added is actually 50 * 24 * 60 * 60
>   /// seconds. If the resulting `DateTime` has a different daylight saving offset
>   /// than `this`, then the result won't have the same time-of-day as `this`, and
>   /// may not even hit the calendar date 50 days later.
>   ///
>   /// Be careful when working with dates in local time.
>   external DateTime add(Duration duration);
> 
>   /// Returns a new [DateTime] instance with [duration] subtracted from [this].
>   ///
>   /// ```dart
>   /// final today = DateTime.now();
>   /// final fiftyDaysAgo = today.subtract(const Duration(days: 50));
>   /// ```
>   ///
>   /// Notice that the duration being subtracted is actually 50 * 24 * 60 * 60
>   /// seconds. If the resulting `DateTime` has a different daylight saving offset
>   /// than `this`, then the result won't have the same time-of-day as `this`, and
>   /// may not even hit the calendar date 50 days earlier.
>   ///
>   /// Be careful when working with dates in local time.
> 

====================

It seems that it work as intended, according to the documentation :(

Are there any plans to change this behavior? 

So that not everyone have to come up with a solution that I feel should be in the bas code!

**Comment by dam-ease** [comment] 2023-11-09 09:22
Thanks for your detailed response. I see from the documentation as well that it seems to be working as intended.  Looking through, I can't seem to find any proposal to change this behaviour. You could file a detailed feature request if you think this behaviour should be changed.
Closing this as this seems to be working as expected, if you disagree, please comment and I'll reopne this.
Thank you!

**Closed by dam-ease** 2023-11-09 09:22 UTC
Labels: in triage

**Comment by LAPPIT** [comment] 2023-11-13 14:44
Hello,

I would like to file for a feature request, but how do I do it?

The current implementation makes the functionality useless and give us that try to use it a lot of extra work (error searching and then everyone have to write this basic functionality on their own).

I think it should be implemented in a useful way or removed from the DateTime function, to stop creating bugs.

Regards,
Mariette Lindström

**Comment by dam-ease** [comment] 2023-11-14 07:45
Hello,
To file a feature request, kindly make use of this: https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=3_feature_request.yml.
I hope this helps!
