### ISSUE TITLE
Url-Launcher Unable to be archived in Xcode

### ISSUE THREAD

**Issue by biomwalk** [flutter/flutter#40511] opened 2019-09-14 21:48 UTC
ErrorMessage when attempting to Archive in Xcode

I'm getting this error message:
```
Library not found for -lurl_launcher
```

## Code
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:async';

class SiteExplorer extends StatefulWidget {
  String surl;
  SiteExplorer(this.surl);
  @override
  _SiteExplorerState createState() => _SiteExplorerState(surl);
} //SiteExplorer

class _SiteExplorerState extends State<SiteExplorer> {
  Completer<WebViewController> _controller = Completer<WebViewController>();
  final Set<String> _favorites = Set<String>();
  String surl;
  _SiteExplorerState(this.surl);


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
      ), //appbar
      body: WebView(
        initialUrl: surl,
        onWebViewCreated: (WebViewController webViewController) {
          _controller.complete(webViewController);
        }, //onWebViewCreated
      ), //Webview
    ); //Scaffold
  } //BuildContext
} //_SiteExplorerState
```
## Logs
```
Ld /Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner normal armv7 (in target: Runner)
    cd /Users/brandonwalker/Development/Apps/WanderJaunt/ios
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk -L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos -L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher -L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/webview_flutter -L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher -L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/webview_flutter -L/Users/brandonwalker/Development/Apps/WanderJaunt/ios/Flutter -F/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos -F/Users/brandonwalker/Development/Apps/WanderJaunt/ios/Pods/../.symlinks/flutter/ios-release -F/Users/brandonwalker/Development/Apps/WanderJaunt/ios/Pods/../.symlinks/flutter/ios-release -F/Users/brandonwalker/Development/Apps/WanderJaunt/ios/Flutter -filelist /Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner_lto.o -Xlinker -final_output -Xlinker /Applications/Runner.app/Runner -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner.swiftmodule -ObjC -lurl_launcher -lwebview_flutter -framework Flutter -ObjC -lurl_launcher -lwebview_flutter -framework Flutter -framework Flutter -framework App -lPods-Runner -Xlinker -dependency_info -Xlinker /Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner_dependency_info.dat -o /Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner

ld: warning: directory not found for option '-L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher'
ld: warning: directory not found for option '-L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/webview_flutter'
ld: warning: directory not found for option '-L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher'
ld: warning: directory not found for option '-L/Users/brandonwalker/Library/Developer/Xcode/DerivedData/Runner-djeztiwsswkkxmcwsaammljxrcvt/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/webview_flutter'
ld: library not found for -lurl_launcher
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by BondarenkoStas** [comment] 2019-09-15 16:57
@biomwalk Please provide your ```flutter doctor -v``` output, to know what the framework version and environment you use.

**Comment by wei-ancoris** [comment] 2019-09-23 20:26
I had the exactly the same problem, then I carefully compared the output in flutter build ios --release, I found this issue is caused by opened wrong project file.

You must open **"Runner.xcworkspace"** instead of "Runner.xcodeproj"

If you try to open Runner.xcodeproj and archive, the xcode will create the build folder under Library/Developer/Xcode/DerivedData folder, but flutter has already created the library under project/build/ios/Release-iphone folder.

**Comment by Heblar** [comment] 2019-10-17 19:42
@wei-ancoris - you saved my life! 3 days trying to understand why it builds but can't archive.

**Comment by biomwalk** [comment] 2019-10-18 20:08
@wei-ancoris was right. Was trying to run the wrong file.

**Comment by janmoppel** [comment] 2019-10-21 09:18
Hello @biomwalk !

Glad to hear that the problem was solved!
Closing the issue, as the working solution was proposed.

**Closed by janmoppel** 2019-10-21 09:18 UTC

**Comment by delphicarlos** [comment] 2020-01-14 10:11
Great!!! Your save my life!
