### ISSUE TITLE
ListViewBuilder items overlap the Ink widget while scrolling

### ISSUE THREAD

**Issue by abubakarmvp** [flutter/flutter#146066] opened 2024-04-01 13:16 UTC
### Steps to reproduce

1. just run the sample code provided below

> if you replace any of Ink widget with container widget. everything works as expected

### Expected results

the listview items should not effect/overlap the Ink Widget.

### Actual results

the listview items overlaping the Ink Widget.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Ticket(),
    );
  }
}

class Ticket extends StatelessWidget {
  const Ticket({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(
      children: [
        Expanded(
          child: ListView.builder(
              padding: const EdgeInsets.only(top: 25),
              itemCount: 100,
              itemBuilder: (context, index) => const TicketItem()),
        ),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 21.0),
          child: InkWell(
              borderRadius: BorderRadius.circular(29.5),
              onTap: () {},
              child: Ink(
                  height: 59,
                  width: double.infinity,
                  decoration: BoxDecoration(
                    color: Colors.green,
                    borderRadius: BorderRadius.circular(29.5),
                  ),
                  child: const Text(
                    "Clik here to see more",
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      fontSize: 18,
                      color: Colors.white,
                      fontWeight: FontWeight.w600,
                    ),
                  ))),
        ),
      ],
    ));
  }
}

class TicketItem extends StatelessWidget {
  final bool isPending;
  const TicketItem({super.key, this.isPending = true});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(left: 13, right: 13, bottom: 18),
      child: InkWell(
        borderRadius: const BorderRadius.all(Radius.circular(10)),
        onTap: () {},
        child: Ink(
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 15),
          decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.all(Radius.circular(10)),
              boxShadow: [
                BoxShadow(blurRadius: 10, color: Color.fromRGBO(0, 0, 0, 0.08)),
              ]),
          child: const Text(
            "12/07/2023",
            style: TextStyle(
              fontSize: 10,
              fontWeight: FontWeight.w300,
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/103175184/628128cb-60b2-40d3-aef1-3c149a3452af

https://github.com/flutter/flutter/assets/103175184/8fc756df-c3f1-4035-94fc-882ae9f2a854

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 Flutter (Channel stable, 3.19.5, on macOS 12.6.6 21G646 darwin-x64, locale en-AE)
    • Flutter version 3.19.5 on channel stable at /Users/mac/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554                        • android-x64    • Android 13 (API 33) (emulator)
    • iPhone 14 Pro Max (mobile) • 362D19F3-892B-4FAC-8856-4E668B131DFF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6.6 21G646 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2024-04-01 13:30
This is a duplicate of https://github.com/flutter/flutter/issues/73315. 

You should wrap your `Ink` with a `Material` widget to prevent the overflow. Ink works by painting on the nearest `Material` ancestor which in this case, is your `Scaffold`. 

Closing this in favor of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-04-01 13:30 UTC
Labels: in triage
