### ISSUE TITLE
When iOS app is launched in background (e.g. via background notification), the AppLifecycleState is resumed.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#73978] opened 2021-01-14 21:28 UTC
https://b.corp.google.com/issues/177496319, which has links to Google-affected teams.

/cc @xster @goderbauer

**Comment by enetor** [comment] 2021-01-20 17:24
Internal bug b/177496319 is marked as P2 so marking this issue as P2 as well.

**Comment by xster** [comment] 2021-01-20 17:42
@enetor do you have a reproduction project you can share?

@pedromassango can we check if this is a regression for stable cherry pick once there's a repro?

**Comment by pedromassango** [comment] 2021-01-20 17:45
> @pedromassango can we check if this is a >regression for stable cherry pick once >there's a repro?

Sure!

**Comment by goderbauer** [comment] 2021-01-20 23:10
@xster I assigned this to you for now since b/177496319 is also assigned to you.

**Comment by xster** [comment] 2021-01-27 05:03
Update: we've been wrapping up the next stable release so no one looked at it yet, but we should soon. Any repro could be very helpful in the meantime.

**Comment by enetor** [comment] 2021-01-27 20:54
@xster That comment was generated by an automated tool run once weekly by the Flutter@Google oncall. The oncall engineer isn't aware of anything happening on GitHub - they won't look at individual GitHub issues. If there is anything needed, please comment on the internal bug directly.

**Comment by jiahaog** [comment] 2021-02-02 01:21
Internal bug b/177496319 is marked as P2 so marking this issue as P2 as well.

**Comment by chinmaygarde** [comment] 2021-02-08 18:35
Update: Progress on an investigation continues in the internal issue tracker.

**Comment by chinmaygarde** [comment] 2021-02-17 18:15
This looks stalled. @xster is OOO and the internal issue seems to the application being blocked on a workaround for https://github.com/flutter/flutter/issues/71074 instead. That issue does look serious and it seems unlikely that an application would be able to work around it in Dart code anyway due to timing issues. The workaround itself should not be necessary but I'll let @xster investigate why its not working when he is back. I am unable to lower the priority of this issue as its priority is synced by a bot. @kf6gpe is following up on that.

**Comment by pedromassangocode** [comment] 2021-02-22 13:20
Oops, I think this should stay opened. Feel free to close otherwise.

**Comment by chinmaygarde** [comment] 2021-02-22 18:35
No updates since last triage.

**Comment by gaaclarke** [comment] 2021-02-24 00:20
This bug is only a problem because `money` is relying on this behavior to workaround this issue: https://github.com/flutter/flutter/issues/71074

That PR has a hypothetical fix that I asked them to try out since we don't have reproduction steps.  Ideally we'd fix the root problem which is [71074](https://github.com/flutter/flutter/issues/71074), we'll see if that patch fixes it.

**Comment by Hixie** [comment] 2021-03-03 00:04
Sounds like we do not believe this is an actual issue? Should we close it?

**Comment by gaaclarke** [comment] 2021-03-03 00:12
Yes, we should close it.  I mentioned it in the internal bug.  We can't guarantee the lifecycle state when Flutter's main is called.  Imagine add-to-app, you could launch Flutter at any point.

**Closed by gaaclarke** 2021-03-03 00:12 UTC
Labels: P2, customer: money (g3), engine, framework, passed first triage, platform-ios

**Comment by Hixie** [comment] 2021-03-05 00:28
@gaaclarke Is the documentation sufficiently detailed on this front?
