### ISSUE TITLE
Flutter app crash when click on select element in Flutter (webview_flutter)

### ISSUE THREAD

**Issue by Maulik009** [flutter/flutter#47514] opened 2019-12-20 06:29 UTC
```dart
 javascriptMode: JavascriptMode.unrestricted,
      javascriptChannels: <JavascriptChannel>[].toSet(),
      onWebViewCreated: (WebViewController webViewController) {
        _myWebViewController = webViewController;
      },
      onPageFinished: (String url) {
      if (_myWebViewController != null) {
          _myWebViewController.evaluateJavascript(
              //  "document.getElementById('mainmenu').style.display = 'none';"
              "document.getElementById('Username').value = '$_username';"
              "document.getElementById('Password').value = '$_password';"
              "document.getElementsByClassName('form-horizontal')[0].submit();");
          _myWebViewController.evaluateJavascript(
              "document.getElementsByClassName('masthead')[0].style.display = 'none';"
              "document.getElementsByClassName('navbar navbar-default')[0].style.display = 'none';"
              "document.getElementsByTagName('footer')[0].style.display = 'none';"
          );

        }
```

**Comment by iapicca** [comment] 2019-12-20 13:40
Hi @Maulik009 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by mklim** [comment] 2020-01-07 18:33
Thanks for reporting this issue! Closing as a duplicate of flutter/flutter#25767.

**Closed by mklim** 2020-01-07 18:33 UTC
Labels: waiting for customer response
