### ISSUE TITLE
[Android] Running an app with debug scene when the device is locked cause a black screen on Android

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#94921] opened 2021-12-09 09:07 UTC
Flutter runs with a black screen when the device is locked and the screen is off on Android. It's reproducible almost 100% on some OnePlus devices.
Searched for relevant issues showing that some apps do have the same behavior when the app is left in the background for a while. All these might be related.

## Steps to Reproduce

1. `flutter create test_example`.
2. `flutter run --verbose` and make sure your device is locked and the screen is off.
3. Wait until you see the `Syncing files to device...` appeared, and hang it for a couple of seconds.
4. Unlock your devices.
5. App is a completely black screen.

### To recover the normal behavior

1. Push the app to the background.
2. Pull it back from the background.

## Verbose logs

I'll explain the behavior along with the log.

```
[  +10 ms] executing: /Volumes/T5/android-sdk/platform-tools/adb -s f8e67ce3 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.example.flutter_test_app/com.example.flutter_test_app.MainActivity
[ +128 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.flutter_test_app/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1160 ms] Observatory URL on device: http://127.0.0.1:38541/F76tt4cIexk=/
[   +1 ms] executing: /Volumes/T5/android-sdk/platform-tools/adb -s f8e67ce3 forward tcp:0 tcp:38541
[  +18 ms] 64028
[        ] Forwarded host port 64028 to device port 38541 for Observatory
[  +10 ms] Caching compiled dill
[ +116 ms] Connecting to service protocol: http://127.0.0.1:64028/F76tt4cIexk=/
[  +32 ms] W/FlutterActivityAndFragmentDelegate( 9430): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
[ +499 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:64028/F76tt4cIexk=/.
[ +369 ms] DDS is listening at http://127.0.0.1:64031/5vM-8dHEa5Q=/.
[  +76 ms] Successfully connected to service protocol: http://127.0.0.1:64028/F76tt4cIexk=/
[ +204 ms] DevFS: Creating new filesystem on the device (null)
[  +83 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.flutter_test_app/code_cache/flutter_test_appITIYOQ/flutter_test_app/)
[   +2 ms] Updating assets
Debug service listening on ws://127.0.0.1:64031/5vM-8dHEa5Q=/ws
[  +67 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
Syncing files to device ONEPLUS A6010...
[   +8 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:testapp/main.dart 6d8be2ea-8af1-4012-9eb2-0d789c346a04
[        ] <- 6d8be2ea-8af1-4012-9eb2-0d789c346a04
[   +2 ms] Bundle processing done.
[  +90 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[  +13 ms] Connected to _flutterView/0x70e0a65a70.
```

The phone is still locked, now let's unlock it.

```
[+43519 ms] D/PhoneWindow( 9430): setNavigationBarColor: 0
[  +15 ms] D/DecorView( 9430): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@960c24b[MainActivity]
[   +2 ms] D/ViewRootImpl[MainActivity]( 9430): windowFocusChanged hasFocus=true inTouchMode=true
```

The device is now unlocked and presented with a black screen.

```
[+11249 ms] D/ViewRootImpl[MainActivity]( 9430): windowFocusChanged hasFocus=false inTouchMode=true
[+2006 ms] D/PhoneWindow( 9430): setNavigationBarColor: 0
[   +4 ms] D/ActivityThread( 9430): pid:9430 tid:9430 doframe Callback
[  +14 ms] E/lutter_test_ap( 9430): Invalid ID 0x00000001.
[  +17 ms] D/DecorView( 9430): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@960c24b[MainActivity]
[   +1 ms] D/ViewRootImpl[MainActivity]( 9430): windowFocusChanged hasFocus=true inTouchMode=true
```

After pushing it into the background and pulling it back, a `doframe Callback` method seems to be called, then the app displayed correctly.

## Environment

Device: OnePlus A6010 (OnePlus 6T)
System version: Android 11

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.976, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-12.0.pre.976 at /Users/alex/Documents/flutter-master
    • Upstream repository https://github.com/AlexV525/flutter
    • Framework revision ca7b823d93 (66 minutes ago), 2021-12-09 02:54:08 -0500
    • Engine revision 716d1b0998
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Volumes/T5/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Volumes/T5/android-sdk
    • ANDROID_SDK_ROOT = /Volumes/T5/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
    • All Android licenses accepted.

[✓] Connected device (1 available)
    • ONEPLUS A6010 (mobile) • f8e67ce3                  • android-arm64  • Android 11 (API 30)

• No issues found!
```

**Comment by xuelongqy** [comment] 2021-12-15 07:02
Add in MainActivity. Flutter will use texture for rendering. It won't have this problem again. But if you reinstall the app, it may crash at the first startup.
```kotlin
override fun getBackgroundMode(): BackgroundMode {
      return if (intent.hasExtra("background_mode")) {
          BackgroundMode.valueOf(intent.getStringExtra("background_mode")!!)
      } else {
          BackgroundMode.transparent
      }
  }
```

**Comment by AlexV525** [comment] 2021-12-15 07:07
> But if you reinstall the app, it may crash at the first startup.

That doesn't sound like a valid solution...

**Comment by xuelongqy** [comment] 2021-12-15 07:17
> > But if you reinstall the app, it may crash at the first startup.
> 
> That doesn't sound like a valid solution...

It will crash only at the first startup, and after reinstalling the app. Weird...

**Comment by maheshmnj** [comment] 2021-12-16 11:56
Hi @AlexV525, Thanks for filing the issue. I see there is a similar issue describing this case  https://github.com/flutter/flutter/issues/93276. 
Closing this issue as a duplicate, since the linked issue has been already prioritized.

If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by Moice** [comment] 2021-12-21 14:07
The same problem, the log has not been crawled, and the most found in Huawei mobile phones at present, please solve it

**Comment by AlexV525** [comment] 2022-01-13 10:42
I can reproduce this issue 100% on my OnePlus 6T (Android 11, Hydrogen OS). I've made a screen record for this. From the recording, we can see the screen is totally black (or blank since my background is black) but it's actually responsive to the input. After I triggered a route push, everything works fine. Also, after discussing with @ColdPaleLight offline, this is not related to images loading.

(Once you see the black screen, skip to the 16 seconds of the video.)

https://user-images.githubusercontent.com/15884415/149314497-89fdc019-a083-4fa8-b4dc-7bce2393fedf.mp4

/cc @dnfield

**Comment by maheshmnj** [comment] 2022-01-13 10:49
FWIW, The other issue I linked above seems to show that the users are able to reproduce this issue on the Oneplus device.

**Comment by AlexV525** [comment] 2022-01-13 13:19
> FWIW, The other issue I linked above seems to show that the users are able to reproduce this issue on the Oneplus device. So they could be very much related and device specific.

Agreed in such high relavance, but I saw Dan said it should be easy to fix, which probably means that can be improved somewhere.

**Comment by dnfield** [comment] 2022-01-13 17:35
Once https://github.com/flutter/engine/pull/30590 lands can you check if it resolves this?

**Comment by AlexV525** [comment] 2022-01-14 02:10
> Once [flutter/engine#30590](https://github.com/flutter/engine/pull/30590) lands can you check if it resolves this?

I've checkout 9e9a728 with flutter/engine@f121c1fe and unfortunately, it still exists. /cc @ColdPaleLight

**Comment by AlexV525** [comment] 2022-01-17 02:47
I've verified https://github.com/flutter/engine/pull/30897 solved this issue by updating the activity like this:

```Kotlin
import android.view.View
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    override fun onStart() {
        super.onStart()
        window.decorView.visibility = View.VISIBLE
    }

    override fun onStop() {
        window.decorView.visibility = View.GONE
        super.onStop()
    }
}
```

**Comment by fine1021** [comment] 2022-01-17 08:41
> I've verified [flutter/engine#30897](https://github.com/flutter/engine/pull/30897) solved this issue by updating the activity like this:
> 
> ```kotlin
> import android.view.View
> import io.flutter.embedding.android.FlutterActivity
> 
> class MainActivity: FlutterActivity() {
>     override fun onStart() {
>         super.onStart()
>         window.decorView.visibility = View.VISIBLE
>     }
> 
>     override fun onStop() {
>         window.decorView.visibility = View.GONE
>         super.onStop()
>     }
> }
> ```

have you try Huawei phone？ this issue still exists.  HUAWEI Mate40 Pro HarmonyOS

**Comment by AlexV525** [comment] 2022-01-17 08:44
> have you try Huawei phone？ this issue still exists. HUAWEI Mate40 Pro HarmonyOS

@fine1021 Is your case the same as the issue? Start the app when screen locked?

**Comment by fine1021** [comment] 2022-01-17 08:55
> > have you try Huawei phone？ this issue still exists. HUAWEI Mate40 Pro HarmonyOS
> 
> @fine1021 Is your case the same as the issue? Start the app when screen locked?

1. start app
2. push app to background
3. locked screen and wait some time
4. unlock screen and click app icon to start app, see black screen，but some times is ok

when this happen, the app is not crash,  it can be recovery like follow
back to homescreen then start app again, everything is ok

**Comment by AlexV525** [comment] 2022-01-17 08:57
> when this happen, the app is not crash, it can be recovery like follow back to homescreen then start app again, everything is ok

Please refer to #93276 which is a certain case from your description.

**Comment by ColdPaleLight** [comment] 2022-01-17 09:43
> > > have you try Huawei phone？ this issue still exists. HUAWEI Mate40 Pro HarmonyOS
> > 
> > 
> > @fine1021 Is your case the same as the issue? Start the app when screen locked?
> 
> 1. start app
> 2. push app to background
> 3. locked screen and wait some time
> 4. unlock screen and click app icon to start app, see black screen，but some times is ok
> 
> when this happen, the app is not crash, it can be recovery like follow back to homescreen then start app again, everything is ok

@fine1021 Can you modify your MainActivity/FlutterActivity like this? Then execute `flutter run`, and then post the Log here when the screen is black.

```
import android.os.Bundle
import android.view.View
import io.flutter.Log
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Log.setLogLevel(2)
    }

    override fun onStart() {
        super.onStart()
        window.decorView.visibility = View.VISIBLE;
    }

    override fun onStop() {
        super.onStop()
        window.decorView.visibility = View.GONE;
    }
}
```

**Comment by ColdPaleLight** [comment] 2022-01-21 00:01
Fixed by https://github.com/flutter/engine/pull/30897

**Closed by ColdPaleLight** 2022-01-21 00:01 UTC
Labels: platform-android, engine, severe: rendering, passed first triage, P4, perf: startup
