### ISSUE TITLE
[video_player] on `iOS 12.4`,  VideoPlayerController.file(file) duration is 0

### ISSUE THREAD

**Issue by akindone** [flutter/flutter#87334] opened 2021-07-30 10:30 UTC
## Steps to Reproduce

1. using `video_player: ^2.1.12`, a 12.4 iphone device 
2. the `main.dart`

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: IosVideoDisappear(),
    );
  }
}

class IosVideoDisappear extends StatefulWidget {
  @override
  _IosVideoDisappearState createState() => _IosVideoDisappearState();
}

class _IosVideoDisappearState extends State<IosVideoDisappear> {
  VideoPlayerController? controller1;

  var url1 = 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';

  @override
  void initState() {
    super.initState();

    initVideoPlayerController();
  }

  Future<File> downloadFile(String url) async {
    final directory = Platform.isAndroid
        ? await getExternalStorageDirectory()
        : await getApplicationDocumentsDirectory();
    var basePath =
        (directory?.path ?? '') + Platform.pathSeparator + 'Download';
    final savedDir = Directory(basePath);
    var hasExisted = await savedDir.exists();
    if (!hasExisted) {
      await savedDir.create();
    }
    var name = url.split('/').last;
    var path = '$basePath/$name';
    var file = File(path);
    if (file.existsSync()) {
      print('downloadFile $url existsSync');
      return file;
    }
    final response = await http.get(Uri.parse(url));
    await file.writeAsBytes(response.bodyBytes);
    return file;
  }

  Future<void> initVideoPlayerController() async {
    VideoPlayerController initControllerForFile(File file) {
      var controller = VideoPlayerController.file(file);
      controller.addListener(() {
        setState(() {});
      });
      controller.setLooping(false);
      controller.initialize().then((value) => setState(() {}));
      controller.play();
      return controller;
    }

    controller1 = initControllerForFile(await downloadFile(url1));
  }

  Future<void> changeVideo() async {
    await controller1?.pause();
    var lastController1 = controller1;
    await initVideoPlayerController();
    WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
      lastController1?.dispose();
    });
  }

  @override
  Widget build(BuildContext context) {
    return _buildVideos();
  }

  Scaffold _buildVideos() {
    return Scaffold(
      body: Column(
        children: [
          Stack(
            children: [
              SizedBox(
                width: 320,
                height: 230,
                child: _buildVideoView(controller1),
              ),
            ],
          ),
          Expanded(
            child: Wrap(
              spacing: 10,
              children: [
                ElevatedButton(
                  onPressed: () {
                    controller1?.pause();
                  },
                  child: Text('Video pause'),
                ),
                ElevatedButton(
                  onPressed: () {
                    controller1?.pause();
                  },
                  child: Text('Video play'),
                ),
                ElevatedButton(
                  onPressed: () {
                    controller1?.position.then((value) {
                      if (value != null) {
                        controller1?.seekTo(value + Duration(seconds: 15));
                      }
                    });
                  },
                  child: Text('Video fast forward 15'),
                ),
                ElevatedButton(
                  onPressed: changeVideo,
                  child: Text('Recreate'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildVideoView(VideoPlayerController? controller) {
    if (controller == null) return SizedBox.shrink();
    return Column(
      children: [
        AspectRatio(
          aspectRatio: (controller.value.isInitialized)
              ? controller.value.aspectRatio
              : 16 / 9,
          child: (controller.value.isInitialized)
              ? VideoPlayer(controller)
              : Container(
                  color: Colors.black12,
                ),
        ),
        Text(
          _getPosition(controller),
        ),
      ],
    );
  }

  String _getPosition(VideoPlayerController controller) {
    return '${controller.value.position}/${controller.value.duration}/${controller.value.isInitialized}}';
  }
}
``` 

</details>

3.after the file download and start play, the duration is 1ms(if this not happen, click the 'Recreate' button can reproduce)
4. the video_player 2.1.1  can get the duration correctly; it seem this commit `3f940429d0e73e2cadfa8a3d487354e0e06f2206` causing the bug 

**Expected results:get the correct duration** 

**Actual results:the duration shows 0:00:00.001** 
<img src="https://user-images.githubusercontent.com/17843738/127640395-f239cb92-eae8-4032-9e36-48da9a817529.png" height="450" />	

<details>
  <summary>Logs</summary>

```
```

```
```

```
```
</details>

**Comment by TahaTesser** [comment] 2021-07-30 12:10
Hi @akindone 
Is the issue only on `iOS 12.4`? I just tried on `iOS 12.5.4` your code sample, duration is 1 min on iPhone 5s  on the latest `video_player: ^2.1.12`

### Preview

https://user-images.githubusercontent.com/48603081/127650748-adc68f8d-9445-452b-859e-1a456f905a64.MP4



<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios
      • iOS 12.5.4
    • macOS (desktop)        • macos                                    •
      darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.107

! Doctor found issues in 1 category.
```

</details>

**Comment by akindone** [comment] 2021-07-30 12:13
> Hi @akindone
> Is the issue only on `iOS 12.4`? I just tried on `iOS 12.5.4` your code sample, duration is 1 min on iPhone 5s on the latest `video_player: ^2.1.12`
> 
> ### Preview
>  RPReplay_Final1627646730.MP4 
> flutter doctor -v

@TahaTesser yes,only on 12.4 devices

**Comment by jmagman** [comment] 2021-07-30 21:59
Suggested commit is https://github.com/flutter/plugins/commit/3f940429d0e73e2cadfa8a3d487354e0e06f2206

**Comment by stuartmorgan** [comment] 2021-08-05 20:16
> the video_player 2.1.1 can get the duration correctly; it seem this commit `3f940429d0e73e2cadfa8a3d487354e0e06f2206` causing the bug

2.1.1->2.1.12 is a relatively large regression range; could you elaborate on how you determined that that's the specific regression?

Getting it narrowed down to the specific version that broke it would be useful in ensuring that's the right commit.

**Comment by akindone** [comment] 2021-12-03 02:11
I add log, and the first time play can get duration, but then I click the 'Recreate' button, it can't get correct duration. I can only reproduce this issue on iOS12.4
![image](https://user-images.githubusercontent.com/17843738/144532629-71f53561-775b-44f8-a184-8a828aa41808.png)
```
2021-12-03 10:05:25.036518+0800 Runner[239:4367] setupEventSinkIfReadyToPlay duration :60095; status:1
2021-12-03 10:05:30.951225+0800 Runner[239:4367] setupEventSinkIfReadyToPlay duration :-9223372036854775807; status:1
2021-12-03 10:05:36.789444+0800 Runner[239:4367] setupEventSinkIfReadyToPlay duration :-9223372036854775807; status:1
2021-12-03 10:05:40.372488+0800 Runner[239:4367] setupEventSinkIfReadyToPlay duration :60095; status:1
2021-12-03 10:05:45.680708+0800 Runner[239:4367] setupEventSinkIfReadyToPlay duration :-9223372036854775807; status:1
2021-12-03 10:05:49.706049+0800 Runner[239:4367] setupEventSinkIfReadyToPlay duration :-9223372036854775807; status:1
2021-12-03 10:06:04.836495+0800 Runner[239:4367] setupEventSinkIfReadyToPlay duration :-9223372036854775807; status:1
```

**Comment by jmagman** [comment] 2021-12-03 02:31
@akindone What version of the plugin are on on? I thought I fixed that in 2.2.6 https://github.com/flutter/plugins/pull/4438

**Comment by jmagman** [comment] 2021-12-03 02:32
If it's fixed in 2.2.6+, https://github.com/flutter/flutter/issues/91975 should have been duped to this and we can close.

**Comment by jmagman** [comment] 2021-12-03 02:36
> If it's fixed in 2.2.6+, #91975 should have been duped to this and we can close.

Never mind in https://github.com/flutter/plugins/pull/4564 I see you're testing on master.

**Comment by akindone** [comment] 2021-12-03 02:43
> If it's fixed in 2.2.6+, #91975 should have been duped to this and we can close.

using 2.2.7.

**Comment by AlexV525** [comment] 2022-01-06 01:59
https://github.com/flutter/plugins/blob/72634e0c404ca0cef18227dec5f8eaa4b6445998/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L378

Can you verify if it's working when applying this patch?

From

```objc
- (int64_t)duration {
  return FLTCMTimeToMillis([[_player currentItem] duration]);
}
```

to

```objc
- (int64_t)duration {
  return FLTCMTimeToMillis([[[_player currentItem] asset] duration]);
}
```

**Comment by stuartmorgan** [comment] 2022-07-21 20:26
Based on the last comment, this was fixed by https://github.com/flutter/plugins/pull/4639

**Closed by stuartmorgan** 2022-07-21 20:26 UTC
Labels: severe: regression, platform-ios, plugin, p: first party, p: video_player, passed first triage, e: OS Version specific, P3
