### ISSUE TITLE
http request block ui

### ISSUE THREAD

**Issue by chavesgu** [flutter/flutter#58956] opened 2020-06-08 07:35 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
[main&second.txt](https://github.com/flutter/flutter/files/4744502/main.second.txt)

3. ... 

In second page,create a https request in initState,ui will be blocked.
Below is my phone,
![Jun-08-2020 15-24-01](https://user-images.githubusercontent.com/20633606/84003186-35279400-a99c-11ea-86b8-a7dff8f0ba86.gif)

**Expected results:** 
didn't block ui
**Actual results:** 
block ui
<details>
  <summary>Logs</summary>

[flutter run verbose.txt](https://github.com/flutter/flutter/files/4744506/flutter.run.verbose.txt)

flutter analyze
analyze is just some unused value.
```
Analyzing bug...                                                        

   info • The value of the field '_counter' isn't used • lib/main.dart:54:7 • unused_field
   info • The declaration '_incrementCounter' isn't referenced • lib/main.dart:56:8 • unused_element
   info • Unused import: 'dart:convert' • lib/second.dart:1:8 • unused_import
   info • The value of the local variable 'response' isn't used • lib/second.dart:39:9 • unused_local_variable

4 issues found. (ran in 2.6s)
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/guchunwen/Documents/project/flutter-sdk/flutter
    • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/guchunwen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/guchunwen/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone • 00008020-00183131149A002E • ios • iOS 13.5
```

</details>

**Comment by iapicca** [comment] 2020-06-08 11:52
Hi @chavesgu 
running a slightly modified version of your code on the latest master 

<details>
  <summary>code</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:io';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
      appBar: AppBar(
        
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              child: Text('second page'),
              onPressed: () {
                print('pushing ms: ${DateTime.now().millisecond}');
                Navigator.of(context).push(MaterialPageRoute(
                  builder: (context) => SecondPage(),
                ));
              },
            )
          ],
        ),
      ), 
    );
  }
}

class SecondPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => SecondPageState();
}

class SecondPageState extends State<SecondPage> {
  String text = '';

  @override
  Widget build(BuildContext context) {
    print('second page open ms: ${DateTime.now().millisecond}');
    return Scaffold(
      appBar: AppBar(
        title: Text('Second Page'),
      ),
      body: Center(
        child: Text(text),
      ),
    );
  }

  @override
  void initState() {
    print('initState ms: ${DateTime.now().millisecond}');
    try {
      getData();
    } catch (e) {
      print('$e');
    }
    super.initState();
  }

  void getData() async {
    print('getting data ms: ${DateTime.now().millisecond}');
      var httpClient = new HttpClient();
      var uri = new Uri.https(
          'api.chavesgu.com',
          '/music/playlist/detail?time=${DateTime.now()}',
          {"id": "3193705217"});
      var request = await httpClient.getUrl(uri);
      var response = await request.close();
      print('${response.contentLength}');
  }
}

```

</details>

<details>
  <summary>logs</summary>

```bash
[ +157 ms] Syncing files to device iPhone SE (2nd generation)...
[   +3 ms] Scanning asset files
[   +4 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:master/main.dart 731c2dbf-59cd-47c5-a1dd-0d3221c03d4d
[        ] <- 731c2dbf-59cd-47c5-a1dd-0d3221c03d4d
[ +156 ms] Updating files
[ +205 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone SE (2nd generation)... (completed in 373ms)
[   +3 ms] Synced 0.9MB.
[   +5 ms] <- accept
[   +2 ms] Connected to _flutterView/0x7f88de01b620.
[   +1 ms] Flutter run key commands.
[  +11 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[   +1 ms] An Observatory debugger and profiler on iPhone SE (2nd generation) is available at: http://127.0.0.1:62474/jQFXTBBPTCM=/
[+178824 ms] flutter: pushing ms: 3
[  +27 ms] flutter: initState ms: 39
[   +2 ms] flutter: getting data ms: 42
[  +23 ms] flutter: second page open ms: 66
[+1967 ms] flutter: -1
[ +294 ms] flutter: pushing ms: 328
[  +21 ms] flutter: initState ms: 350
[   +1 ms] flutter: getting data ms: 350
[   +1 ms] flutter: second page open ms: 351
[+1408 ms] flutter: -1
[+5003 ms] [VERBOSE-2:profiler_metrics_ios.mm(65)] Error retrieving thread information: (ipc/send) invalid destination port
[+12232 ms] flutter: pushing ms: 999
[  +18 ms] flutter: initState ms: 17
[   +2 ms] flutter: getting data ms: 17
[        ] flutter: second page open ms: 18
[+3530 ms] flutter: -1

```

</details>


<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-4.0.pre.99, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.19.0-4.0.pre.99 at /Users/nevercode/development/flutter_master
    • Framework revision 7467492444 (6 hours ago), 2020-06-08 02:03:01 -0400
    • Engine revision dfdd88deb7
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) • 96856728-4BA4-47CD-A70E-4AB604D0D5B6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server                 • web-server                           • web-javascript • Flutter Tools
    • Chrome                     • chrome                               • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

i cannot reproduce the issue,
could you please run the modified sample and post the output
Thank you

**Comment by dnfield** [comment] 2020-06-08 17:46
Possible duplicate of dart-lang/sdk#41519

**Comment by chavesgu** [comment] 2020-06-09 01:13
> Possible duplicate of [dart-lang/sdk#41519](https://github.com/dart-lang/sdk/issues/41519)

oh,I actually used Let's Encrypt.oh my god!

**Comment by chavesgu** [comment] 2020-06-09 01:16
@iapicca 
You don't have to test the run order issue,I have tested it,this is indeed the reason for the HTTPS request.
I believe it's probably @dnfield said.

**Closed** 2020-06-09 01:25 UTC
Labels: in triage

**Comment by chavesgu** [comment] 2020-06-09 03:20
@dnfield I didn't solve the problem,[https://github.com/dlecorfec/ocsp-proxy]() didn't work

**Comment by chavesgu** [comment] 2020-06-11 10:49
@dnfield  it doesn't have a resolution, currently, I change certificate to solve
