### ISSUE TITLE
Create a Flutter IDE

### ISSUE THREAD

**Issue by vladislav1nikov** [flutter/flutter#123068] opened 2023-03-20 23:23 UTC
It would be nice to have a dedicated IDE for Flutter that will have development tools for all target platforms (For example based on IntelliJ). Most likely there will be problems from Apple, but this idea could be considered. I saw this question already asked (#60001). But a few years have passed, perhaps the plans of the Flutter team have changed?

**Comment by stuartmorgan** [comment] 2023-03-21 00:18
Closing as a duplicate of https://github.com/flutter/flutter/issues/60001. Please don't re-file the same request as a previously closed request; if there were a change in decision about a previously closed issue, it would have been re-opened.

**Closed by stuartmorgan** 2023-03-21 00:18 UTC
