### ISSUE TITLE
SizeTransition does not affect on Ink

### ISSUE THREAD

**Issue by ValeriusGC** [flutter/flutter#124444] opened 2023-04-08 10:27 UTC
When using Ink widget it does not affected by SizeTransition, see video
![strange_ink_behavior-2023-04-08_15 19 39](https://user-images.githubusercontent.com/3320861/230716272-ed49f5c1-4428-4045-9696-ab3f2f803ac0.gif)

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({super.key});

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// [AnimationController]s can be created with `vsync: this` because of
/// [TickerProviderStateMixin].
class _MyStatefulWidgetState extends State<MyStatefulWidget>
    with TickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 3),
    vsync: this,
  )..repeat();
  late final Animation<double> _animation = CurvedAnimation(
    parent: _controller,
    curve: Curves.fastOutSlowIn,
  );

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizeTransition(
        sizeFactor: _animation,
        axis: Axis.horizontal,
        axisAlignment: -1,
        child: Center(
          child:
          InkWell(
            child: Ink(
              color: Colors.red,
              padding: const EdgeInsets.symmetric(
                horizontal: 5,
                vertical: 2,
              ),
              child: SizedBox(
                width: 200,
                height: 200,
                child: Text(
                  'tag',
                  style: Theme.of(context).textTheme.headlineMedium,
                ),
              ),
            ),
            onTap: () {
              // debugPrint('$tag selected');
            },
          ),
          // child: FlutterLogo(size: 200.0),
        ),
      ),
    );
  }
}
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on Ubuntu 20.04.5 LTS 5.15.0-69-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by exaby73** [comment] 2023-04-10 07:42
Hello @ValeriusGC. Is this issue still reproducible on the latest master version?

**Comment by ValeriusGC** [comment] 2023-04-10 11:50
> Hello @ValeriusGC. Is this issue still reproducible on the latest master version?

Yes, this is still here on
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.10.0-2.0.pre.29, on Ubuntu 20.04.5 LTS 5.15.0-69-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] Network resources

```

**Comment by exaby73** [comment] 2023-04-10 13:40
Wrapping the `Center` with a `Material` fixes this. The way I like to think about `Ink`s, and I might be wrong on how this works, is that the `Ink` sort of draws on the `Material` provided by the `Scaffold` rather than its parent. Since the `Scaffold` expands the screen, it doesn't get affected by the `SizeTransition`. So we need to supply a `Material` within the `SizeTransition`, so that the `Ink` draws on that one which is being resized by the transition.

This is working as expected and therefore, I will close this issue. Thank you.

<details>
<summary>Updated Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({super.key});

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget>
    with TickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 3),
    vsync: this,
  )..repeat();

  late final Animation<double> _animation = CurvedAnimation(
    parent: _controller,
    curve: Curves.fastOutSlowIn,
  );

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizeTransition(
        sizeFactor: _animation,
        axis: Axis.horizontal,
        axisAlignment: -1,
        child: Material(
          child: Center(
            child: InkWell(
              child: Ink(
                color: Colors.red,
                padding: const EdgeInsets.symmetric(
                  horizontal: 5,
                  vertical: 2,
                ),
                child: SizedBox(
                  width: 200,
                  height: 200,
                  child: Text(
                    'tag',
                    style: Theme.of(context).textTheme.headlineMedium,
                  ),
                ),
              ),
              onTap: () {},
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Closed by exaby73** 2023-04-10 13:40 UTC
Labels: in triage
