### ISSUE TITLE
zsh: operation not permitted: flutter

### ISSUE THREAD

**Issue by orest-kostiuk** [flutter/flutter#65159] opened 2020-09-03 09:01 UTC
1.charged the terminal to zsh and made new zprofile through touch

2.then i used vim .zprofile, .zshrc and added this variable- export PATH="$PATH:/Users/username/flutter/bin"
Now when i run flutter i get this error "zsh: operation not permitted: flutter"

3. added full disk access for my terminal

**Comment by TahaTesser** [comment] 2020-09-03 09:10
Closing as duplicate of https://github.com/flutter/flutter/issues/65101

**Closed by TahaTesser** 2020-09-03 09:10 UTC
