### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by Ashish-003** [flutter/flutter#154469] opened 2024-08-31 10:19 UTC
## Command
```sh
flutter run -d a52403b6
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:266:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1783:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1795:8)
#3      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1734:14)
#4      VmService.callMethod (package:vm_service/src/vm_service.dart:1717:12)
#5      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:501:28)
#6      FlutterVmService.renderFrameWithRasterStats (package:flutter_tools/src/vmservice.dart:606:49)
#7      ResidentHandlers.debugFrameJankMetrics (package:flutter_tools/src/resident_runner.dart:726:37)
<asynchronous suspension>
#8      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1836:7)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.0, on Ubuntu 22.04.4 LTS 6.8.0-40-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.24.0 on channel stable at /home/ash/Documents/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 80c2e84975 (5 weeks ago), 2024-07-30 23:06:49 +0700
    [32m•[39m Engine revision b8800d88be
    [32m•[39m Dart version 3.5.0
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /home/ash/Android/Sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m ANDROID_HOME = /home/ash/Android/Sdk
    [32m•[39m Java binary at: /home/ash/Documents/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[31m[✗][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Ubuntu clang version 14.0.0-1ubuntu1.1
    [32m•[39m cmake version 3.22.1
    [32m•[39m ninja version 1.10.1
    [32m•[39m pkg-config version 0.29.2
    [31m✗[39m GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /home/ash/Documents/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at /snap/code/current/usr/share/code
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m RMX2061 (mobile) • a52403b6 • android-arm64  • Android 11 (API 30)
    [32m•[39m Linux (desktop)  • linux    • linux-x64      • Ubuntu 22.04.4 LTS 6.8.0-40-generic
    [32m•[39m Chrome (web)     • chrome   • web-javascript • Google Chrome 127.0.6533.88

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
android_alarm_manager_plus-4.0.3
android_intent_plus-5.1.0
audioplayers-6.0.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.0
audioplayers_windows-4.0.0
google_mobile_ads-5.1.0
path_provider-2.1.3
path_provider_android-2.2.5
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
sqflite-2.2.6
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.2.5
url_launcher_android-6.3.0
url_launcher_ios-6.2.5
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.2
webview_flutter-4.8.0
webview_flutter_android-3.16.6
webview_flutter_wkwebview-3.14.0

**Comment by darshankawar** [comment] 2024-09-02 08:02
Closing as duplicate of https://github.com/flutter/flutter/issues/117988

**Closed by darshankawar** 2024-09-02 08:02 UTC
Labels: in triage
