### ISSUE TITLE
The class 'Timer' doesn't have a constructor named 'periodic'.

### ISSUE THREAD

**Issue by a7me63azzab** [flutter/flutter#26521] opened 2019-01-14 09:57 UTC
### I get that error when i use Timer.periodic() in my flutter app .
```dart
import 'dart:async';

 
  Timer timer;
  var endDate = DateTime.parse('2019-01-14 11:50:00').millisecondsSinceEpoch;
  const oneSec = const Duration(milliseconds:1000);
  timer = new Timer.periodic(oneSec, (Timer t)  {
    var now = new DateTime.now().millisecondsSinceEpoch;

    var distance = endDate- now;
  
    var hours = ((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)).round();
    var minutes = ((distance % (1000 * 60 * 60)) / (1000 * 60)).round();
    var seconds = ((distance % (1000 * 60)) / 1000).round();
    
    if (distance < 0) {
      timer.cancel();
      print('finish');
  }
  
    print('$hours h, $minutes m, $seconds s');
  });
```

**Comment by zoechi** [comment] 2019-01-14 10:12
In the Dart Analyzer window in IntelliJ/Android studio there is a button to restart the analyzer

![image](https://user-images.githubusercontent.com/405837/51106830-3c6d6100-17ed-11e9-8e95-eedd0a9b3863.png)

Try if this helps. 
If you are using another IDE try restarting the IDE.

**Comment by zoechi** [comment] 2019-01-14 10:13
Also check that `git status` in the Flutter install directory doesn't list any changed files.

**Comment by zoechi** [comment] 2019-01-14 10:16
Duplicate of https://github.com/dart-lang/sdk/issues/35650

**Closed by zoechi** 2019-01-14 10:16 UTC
Labels: waiting for customer response
