### ISSUE TITLE
Scaffold's layout algorithm places snack bar beneath persistent bottom sheet.

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#19547] opened 2018-07-19 01:18 UTC
The Material Spec says that snack bars should appear above persistent bottom sheets. 

![image](https://user-images.githubusercontent.com/2225255/42915129-d97cea9c-8ab2-11e8-9eea-aad55e2ff607.png)

https://material.io/design/components/snackbars.html#placement

The current implementation of Scaffold ignores the persistent bottom sheet when vertically positioning the snack bar (it's not part of [contentBottom](https://github.com/flutter/flutter/blob/c39f2f26f7e74c516060fa3475876de21c38bbf3/packages/flutter/lib/src/material/scaffold.dart#L368)). Additionally, it places the snack bar beneath the bottom sheet (in the third dimension). Therefore, if you have a bottom sheet that's at least as tall as the snack bar, you don't see the snack bar at all.

**Comment by efroim102** [comment] 2018-12-21 14:54
Any timeline on this being fixed?

**Comment by dalebulmer** [comment] 2019-06-04 11:58
Is there any timeline on this issue, or a workaround?

**Comment by Dancovich** [comment] 2019-06-19 13:39
Waiting for this fix too.

For now I'm using the bottom sheet controller to close the persistent bottom sheet before showing the snack bar.

```dart
      try {
        _bottomSheetController?.close();
      } catch (e) {} finally {
        _bottomSheetController = null;
      }
      Scaffold.of(context).showSnackBar(
        SnackBar(
          duration: Duration(seconds: 4),
          content: Text("Some text"),
        ),
      );
```

**Comment by talatkuyuk** [comment] 2020-02-12 23:50
I have also the same problem or wish. Bottomsheet property of scaffold is over the snack bar, so snackbar is not shown, stays hidden under bottomsheet of scaffold. (behavior: SnackBarBehavior.fixed so I like this behaviour not float one.) Actually I want the snackbar is shown as expected without any confliction with bottom sheet. I wish you solve it. Thanks.

**Comment by Reprevise** [comment] 2020-04-28 17:41
Would love to have this so I wouldn't have to use `SnackBarBehavior.floating` since I don't like how it looks.

Any update on this?

**Comment by TahaTesser** [comment] 2020-06-04 09:33
![Simulator Screen Shot - iPhone 11 - 2020-06-04 at 14 59 03](https://user-images.githubusercontent.com/48603081/83740452-79e9bd00-a674-11ea-9aa9-ffc2a96be7c8.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final GlobalKey<ScaffoldState> key = GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: key,
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Stack(
        alignment: Alignment.center,
        children: [
          Positioned(
            bottom: 0,
            child: Text('Hello World'),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          key.currentState.showSnackBar(SnackBar(
              content: Text('Yay! A SnackBar!'),
              action: SnackBarAction(
                label: 'Undo',
                onPressed: () {},
              )));
        },
      ),
      bottomSheet: BottomSheet(
          backgroundColor: Colors.transparent,
          onClosing: () {},
          builder: (_) {
            return Container(height: 50, color: Colors.transparent);
          }),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (2 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by filiph** [comment] 2020-08-08 02:40
I found a workaround to a similar issue. Maybe some of you here might find it enough to work around this one: https://github.com/flutter/flutter/issues/63254#issuecomment-670811726

Basically: 


```dart
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SnackBar Demo',
      home: Scaffold(
        appBar: AppBar(
          title: Text('SnackBar Demo'),
        ),
        body: SnackBarPage(),
        bottomSheet: Container(
          color: Colors.yellow,
          child: SizedBox(
            height: 200,
            child: Text('Bottom sheet'),
          ),
        ),
        // This is a workaround that makes snack bars appear _above_
        // the bottom sheet. Floating snackbars are shown above FABs,
        // so we just create an invisible, zero-size FAB here.
        floatingActionButton: const SizedBox(height: 1),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      ),
    );
  }
}
```

DartPad with the workaround: https://dartpad.dev/b84641713571200d24ef145085764060

**Comment by aliftaufik** [comment] 2020-09-19 10:53
> I found [a workaround](https://github.com/flutter/flutter/issues/63254#issuecomment-670811726) to a similar issue. Maybe some of you here might find it enough to work around this one.
> 
> ```dart
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'SnackBar Demo',
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('SnackBar Demo'),
>         ),
>         body: SnackBarPage(),
>         bottomSheet: Container(
>           color: Colors.yellow,
>           child: SizedBox(
>             height: 200,
>             child: Text('Bottom sheet'),
>           ),
>         ),
>         // This is a workaround that makes snack bars appear _above_
>         // the bottom sheet. Floating snackbars are shown above FABs,
>         // so we just create an invisible, zero-size FAB here.
>         floatingActionButton: const SizedBox(height: 1),
>         floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
>       ),
>     );
>   }
> }
> ```
> 
> DartPad with the workaround: https://dartpad.dev/b84641713571200d24ef145085764060

This probably solves some of the use cases, but it must have the behavior of floating, which not everyone uses this behavior (for me, it's because I cannot change the snack bar to have a width of the entire screen, and so not matching my UI design). The @Dancovich workaround requires us to hide the bottom sheet, which in my case I can't do that either. Another workaround I found online suggests using the bottom navigation bar instead of the bottom sheet since the snack bar will appear above it. But it makes me lose some of the bottom sheet behavior that I'd like to keep (in my case, I want the bottom sheet to be shown above the keyboard).

Is there any workaround for it?

**Comment by AlexHartford** [comment] 2020-09-28 22:51
@filiph solution is better than nothing, but still doesn't really solve properly layering a snackbar on top of a bottomsheet.

**Comment by aliftaufik** [comment] 2020-09-29 07:57
Right now, my workaround is adding bottom padding to snack bar content whenever there's a bottom sheet on the screen. But you have to know the height of the bottom sheet, which will potentially give you a headache later on. It works for me because I know that whenever my scaffold has a persistent bottom sheet, it has to be that same widget, which in my case it's a full-width button. So I can hardcode the snack bar bottom padding.

**Comment by filiph** [comment] 2020-09-29 16:08
@aliftaufik I'm curious: how can you add bottom padding to a snack bar? In `Theme`? Because if I remember correctly, `Snackbar` itself doesn't have that option, and if you put the padding inside, then the whole snackbar gets larger.

**Comment by aliftaufik** [comment] 2020-09-29 19:42
I put it in the content argument, like this:

```
SnackBar(
  content: Padding(
    padding: EdgeInsets.only(bottom: 52), // I hardcoded it since I know my app will only have bottom sheet with this size
    child: Text('Error'),
  ),
)
```

I can do this because I only have one widget that will be inside the bottom sheet. But if the app has different bottom sheet widgets on each screen, this workaround will be hard to maintain.

**Comment by amitkot** [comment] 2020-11-02 13:45
The workaround suggested by @filiph is good as long as you don't require a null FAB.
In my use case I have a FAB that when pressed shows the persistent bottom sheet instead of it. 
I get this effect by setting the `Scaffold`'s FAB to `null`:

```dart
floatingActionButton: !_showingQuickAddSheet
                ? FloatingActionButton(onPressed: _fabPressed, child: const Icon(Icons.add))
                : null,
```

This shows a nice animation as the FAB disappears and returns when the bottom sheet closes.
When using the workaround there is a FAB in both cases and the nice appear / disappear animation no longer shows.

**Comment by amitkot** [comment] 2020-11-02 21:40
For now I've wrapped it with an `AnimatedSwitcher` for mimicking most of the animated effect `Scaffold` implements :

```dart
AnimatedSwitcher(
  duration: const Duration(milliseconds: 200),
  transitionBuilder: (child, animation) => ScaleTransition(
    scale: animation,
    child: child,
  ),
  child: _showingQuickAddSheet
      ? const SizedBox(height: 1)
      : FloatingActionButton(
          onPressed: _fabPressed,
          child: const Icon(Icons.add),
        ),
)
```

**Comment by xu-baolin** [comment] 2021-01-08 10:40
@Piinks Hi
`Snackbars should appear directly above persistent footer elements.`
I think the footer elements correspond to the `persistentFooterButtons` of flutter, right?

If I understand is correct, we only need to paint the snack bar on the cover of the `bottomSheet` described by @filiph at #63254.

**Comment by Piinks** [comment] 2021-01-08 17:57
Hey @xu-baolin thanks for taking a look at this! 
I just found this to help guide us on the right behavior:
https://material.io/components/snackbars#placement

It looks like we want the Snackbar to go above things like persistent footer buttons, FABs and navigation bars, and then in the case of bottom sheets, the Snackbar should be on top.

**Comment by xu-baolin** [comment] 2021-01-08 22:36
> Hey @xu-baolin thanks for taking a look at this!
> I just found this to help guide us on the right behavior:
> https://material.io/components/snackbars#placement
> 
> It looks like we want the Snackbar to go above things like persistent footer buttons, FABs and navigation bars, and then in the case of bottom sheets, the Snackbar should be on top.

Yes，so I think we can close this issue and just keep #63254 open to track the painting issue.

**Comment by Piinks** [comment] 2021-01-08 22:55
SGTM! Closing as a dupe of #63254

**Closed by Piinks** 2021-01-08 22:55 UTC
Labels: P4, a: quality, customer: mulligan (g3), f: material design, found in release: 1.19, framework, has reproducible steps
