### ISSUE TITLE
Screen transitions with optimized images are janky

### ISSUE THREAD

**Issue by pejalo** [flutter/flutter#27625] opened 2019-02-07 01:10 UTC
I'm working on a iPad app with image-heavy navigation. Check out this [sample app](https://github.com/pejalo/flutter_image_performance) and [YouTube video](https://youtu.be/TOeRnlF5n44) that demonstrates the isolated issue.

In short, the app has screens that are composed of images. The transitions between the screens are only smooth if the second screen has been shown recently.

Yes, I'm running this in release mode via `flutter run --release` on a real iPad 6th Gen (Air 2).

All images are pre-cached into memory using [precacheImage()](https://docs.flutter.io/flutter/widgets/precacheImage.html) before being displayed.

Unfortunately the performance is noticeable enough to keep my team from being able to ship.

**App explanation**

The main screen consists of 10 images. Tapping on one of them leads to a second screen that also displays 10 images (with a back-button at the top).

When tapping from the main screen the first time, there is a noticeable delay. A split-second later, the transition animation catches up. When tapping the same image from the main screen again, there is no delay.

After tapping around for long enough, the screens that were shown with smooth transitions before become janky again.

What exactly is happening under the hood? I suspect there is some GPU level caching of textures or something. Is there anything I can do to make these transitions smooth the first time?

**`flutter doctor -v`**
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/peter/flutter
    • Framework revision 5391447fae (10 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/peter/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available
```

**Comment by Sh1d0w** [comment] 2019-02-07 04:13
Try to optimize the images you are rendering as much as possible. I've experienced the same problem, but managed to resolve it.

Basically I was displaying a lot of small images in one of my pages, but I was passing the original image as source (e.g. 5000x3000 resolution and around 14 MB in size). This caused a lot of jank and also caused the images to flash when scrolling.

As soon as I served images that was optimized for the size I wanted to display it all become smooth again.

I would suggest you to serve thumbs, instead of original images and see how this feels. AFAIK Flutter loads the images you are rendering into the memory I would also suggest to load as less as possible images on a page and implement infinite scroll so you load less images in the first load.

**Comment by pejalo** [comment] 2019-02-07 19:47
Hey @Sh1d0w I really appreciate the response and suggestion. The issues you mentioned are all caused by downsampling images and can be overcome by resizing them beforehand. However, you'll see in my sample app that the images are already optimized for display.

The code [here](https://github.com/pejalo/flutter_image_performance/blob/4be14c9e58a7285144fc63feb48fde8d4e0c19e0/lib/main.dart#L105) shows that all images are displayed in a 480x240 container:
```
child: Container(
  width: 480,
  height: 240,
  child: Image.asset("photos/${imageNumber + 1}.jpg"),
),
```

All the images in [this folder](https://github.com/pejalo/flutter_image_performance/tree/4be14c9e58a7285144fc63feb48fde8d4e0c19e0/photos) are 960x480 for the retina screen. (480x240 images look pixelated on an iPad.)

**Comment by pejalo** [comment] 2019-02-08 02:29
From further experimentation, it seems that the performance is directly related to the size (in data) of the images. In our real app we were using PNGs. Transforming them into JPEGs, while keeping the same resolutions, outside of Flutter helped a lot. The lower the JPEG quality, the better the performance. It's an unfortunate tradeoff, but we've found an acceptable sweet spot for now.

It still makes me uneasy that my sample app is janky with those images mentioned above, which are not any larger than I would expect Flutter to be able to handle.

**Comment by Sh1d0w** [comment] 2019-02-08 03:19
@pejalo Sorry if I haven’t explained it more clearly, this is exactly what I tried to tell you - that the image dimensions and it size has direct impact on the performance. Also forgot to mention that PNG and GIFs have poor render performance as well.

As I am the maintainer of the popular multi_image_picker plugin for Flutter I found and reported this long ago. I still hope this gets fixed soon, but until the I’ve put a guide in my plugin docs how to utilize the thumbnail feature of my plugin along with the quality parameter. 

For that same reason and with the other one that the Flutter image widget does not support many image codecs (like HEIC which is how iOS takes photos by default) I also convert all images to JPEG before I return them from the plugin.

**Comment by pejalo** [comment] 2019-02-11 19:19
Thanks again @Sh1d0w. That's really useful information. I wish the Flutter docs included information like "PNG and GIFs have poor render performance" and were more transparent in general about related shortcomings.

**Comment by AurelianTimu** [comment] 2020-03-27 11:01
I am experiencing exactly the same issue. 
In my case, I am using 320 × 240 thumb images having a size of about 9KB each.

It can not be optimized further that this.. 
What can I do to eliminate the junky effect transition?

**Comment by TahaTesser** [comment] 2020-09-23 15:35
Hi @pejalo 
I cannot reproduce it on XR in the release mode on iOS 14

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  bool didLoadImages = false;

  @override
  Widget build(BuildContext context) {
    // Pre-cache images
    if (!didLoadImages) {
      for (var i = 1; i <= 110; i++) {
        precacheImage(AssetImage('photos/$i.jpg'), context);
      }
      didLoadImages = true;
    }

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final int imageNumberOffset;

  MyHomePage({this.imageNumberOffset = 0});

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Center(
        child: Container(
          width: double.infinity,
          child: Column(
            children: <Widget>[
              // Back button
              imageNumberOffset == 0
                  ? Container()
                  : Container(
                      padding: EdgeInsets.only(top: 20),
                      child: FlatButton(
                        color: Colors.grey,
                        child: Text('Back'),
                        onPressed: () => Navigator.of(context).pop(),
                      ),
                    ),
              // ListView of Rows with CardWidgets
              Expanded(
                child: ListView.builder(
                  itemCount: 5,
                  itemBuilder: (context, rowNumber) {
                    return Row(
                      children: [
                        CardWidget(
                          imageNumber:
                              (imageNumberOffset * 10) + (rowNumber * 2),
                          onTap: imageNumberOffset != 0
                              ? null
                              : () =>
                                  Navigator.of(context).push(MaterialPageRoute(
                                    builder: (context) => MyHomePage(
                                        imageNumberOffset: rowNumber * 2 + 1),
                                  )),
                        ),
                        CardWidget(
                          imageNumber:
                              (imageNumberOffset * 10) + (rowNumber * 2) + 1,
                          onTap: imageNumberOffset != 0
                              ? null
                              : () =>
                                  Navigator.of(context).push(MaterialPageRoute(
                                    builder: (context) => MyHomePage(
                                        imageNumberOffset: rowNumber * 2 + 2),
                                  )),
                        ),
                      ],
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class CardWidget extends StatelessWidget {
  final int imageNumber;
  final Function onTap;

  CardWidget({this.imageNumber, this.onTap});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: 300,
        height: 240,
        child: Image.asset("photos/${imageNumber + 1}.jpg"),
      ),
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.317, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.317 at /home/taha/Code/flutter_master
    • Framework revision 10febea877 (6 hours ago), 2020-09-23 07:22:10 +0200
    • Engine revision 57ee3d4b32
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details> 

Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by TahaTesser** [comment] 2020-10-16 12:43
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-16 12:43 UTC
Labels: P4, a: images, engine, framework, severe: performance
