### ISSUE TITLE
keycloak_flutter package import in main.dart causes CanvasKit to crash - works fine with HTML renderer

### ISSUE THREAD

**Issue by jonasbark** [flutter/flutter#110775] opened 2022-09-01 13:31 UTC
## Steps to Reproduce

1. Execute `flutter build web --profile --web-renderer canvaskit` on the repository https://github.com/propops/canvaskitflutterissue
2. run localhost:4200 after starting a local server in build/web
3. observe the console error

**Expected results:** 
Flutter app loads up correctly and shows yellow screen

**Actual results:** 
Console shows the following issue:
```
Uncaught NoSuchMethodError: method not found: 'then'
Receiver: Instance of 'PlainJavaScriptObject'
Arguments: [Closure '_Future__chainForeignFuture_closure', onError: Closure '_Future__chainForeignFuture_closure0']
    at Object.wrapException (main.dart.js:5186:17)
    at LegacyJavaScriptObject.noSuchMethod$1 (main.dart.js:34290:15)
    at LegacyJavaScriptObject.then$1$2$onError (main.dart.js:41207:19)
    at Object.then$1$2$onError$z (main.dart.js:24193:43)
    at _Future._chainForeignFuture$1 (main.dart.js:37472:11)
    at _Future._chainFuture$1 (main.dart.js:37527:13)
    at _Future._asyncComplete$1 (main.dart.js:37508:14)
    at _AsyncCompleter.complete$1 (main.dart.js:37323:10)
    at downloadCanvasKit_closure0.call$1 (main.dart.js:26217:35)
    at Object.Primitives_applyFunction (main.dart.js:5074:30)
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:keycloak_flutter/keycloak_flutter.dart';

void main() {
  runApp(
    TestApp(),
  );
}

class TestApp extends StatelessWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      debugShowCheckedModeBanner: false,
      theme: Theme.of(context).copyWith(),
      home: Container(color: Colors.yellow),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.4 21F79 darwin-arm, locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 3 categories.
```

</details>

- this only happened after upgrading to the latest stable 3.3
- if I remove the import to keycloak_flutter it works fine
- if I downgrade keycloak_flutter to 0.0.3 it works fine. As the error is internal I would assume that this is a dart or flutter bug.
- it also works fine using the HTML renderer instead of canvaskit

**Comment by exaby73** [comment] 2022-09-01 20:46
Hello @jonasbark. Thank you for filing this issue. Unfortunately, we do not provide support for 3rd party packages. I think this issue is more suited to be raised in [`keycloak_flutter`](https://github.com/gibahjoe/keycloak_flutter).

This may be an internal error but the source of the error seems to be that library, therefore I am closing this issue. If you disagree, please comment and I reopen it. Thank you.

**Comment by jonasbark** [comment] 2022-09-01 21:06
@exaby73 I disagree. A simple import should not keep flutter web from running at all, even before the library in question has even been loaded.

Even if the culprit is the library, I would think that the flutter or Dart maintainers have an interest in the internal error.

Another proof: it works with the html renderer but does not with canvaskit. Why can a 3rd party import cause such an issue?

Therefore please reopen - thanks!

**Comment by exaby73** [comment] 2022-09-02 07:00
@jonasbark This looks like a package error. Downgrading the package to `0.0.3` produces no error. Keeping it closed for this reason.

**Comment by jonasbark** [comment] 2022-09-02 07:11
@exaby73 but why does it work fine on debug mode and fails in Release mode? Don't you think that's something that should be investigated on the flutter side?

I honestly find it unacceptable that tickets are closed and it's simply stated that it's the plugins fault. To me it's clearly not and I've worked with flutter for three years now. 

Here's a summary of why I believe that it's a framework issue:
1) it's a simple import and it breaks the initialization of the canvaskit renderer. How?
2) it works fine in debug mode. Why?
3) it works fine with the html renderer. 

Aren't those reasons enough for an investigation?

**Comment by exaby73** [comment] 2022-09-02 07:15
@jonasbark I will reopen this issue for the team to further investigate. Thank you.

**Comment by jason-simmons** [comment] 2022-09-17 01:54
Bisected this to https://github.com/flutter/engine/commit/82aad2e48051e7121565cf8e81e084e4aa818012

**Comment by yjbanov** [comment] 2023-02-09 19:09
Just a heads up, that it will be too difficult to find the issue if the repro contains dependencies doing magical things. I'm not exactly sure what the keycloak_flutter package does. It may be altering the runtime of the browser (by monkey-patching the API) in ways that are incompatible with Flutter Web.

Can you provide a repro case without the dependency?

**Comment by ditman** [comment] 2023-02-09 19:16
Is this a keycloak_flutter issue?

* https://github.com/gibahjoe/keycloak_flutter/issues/17
* https://github.com/gibahjoe/keycloak_flutter/issues/20

**Comment by jonasbark** [comment] 2023-02-09 19:33
> Just a heads up, that it will be too difficult to find the issue if the repro contains dependencies doing magical things. I'm not exactly sure what the keycloak_flutter package does. It may be altering the runtime of the browser (by monkey-patching the API) in ways that are incompatible with Flutter Web.
> 
> Can you provide a repro case without the dependency?

@yjbanov keycloak_flutter does no such thing. It's pretty much just a wrapper around a Javascript dependency.

Regarding the repro case: no, I can not. I'm sure that the linked repository is well enough.

@ditman flutter shouldn't crash before initializing when just referencing an external dependency, shouldn't it? I don't think it matters if the referenced package is at fault.

Please all keep in mind that it breaks flutter from initializing. Not during runtime.

**Comment by ditman** [comment] 2023-02-09 20:31
> flutter shouldn't crash before initializing when just referencing an external dependency, shouldn't it? I don't think it matters if the referenced package is at fault.

@jonasbark I guess it depends in what that external dependency does. For example, this external dependency breaks flutter, and there's **nothing** Flutter web can do to work around it:

```html
<script>
  Promise = null;
</script>
```

And maybe the package itself has a legitimate use case for whatever it does when used as intended in a JavaScript app, but it's doing something that breaks with Flutter web (the PR I linked seems to fix the issue, according to the author, btw).

**Comment by jonasbark** [comment] 2023-02-09 20:35
But why would flutter initializing only fail for CanvasKit usage? Why does it work fine when the HTML renderer is used?

I would understand that it would fail in general, but why does the renderer matter?

**Comment by ditman** [comment] 2023-02-09 22:01
> Why would flutter initializing only fail for CanvasKit usage? Why does it work fine when the HTML renderer is used?
>
> I would understand that it would fail in general, but why does the renderer matter?

@jonasbark I think this is not entirely accurate. I get the same error regardless of the web-renderer I use, here's the same problem happening with `--web-renderer=html`:

<img width="1066" alt="Screenshot 2023-02-09 at 1 24 23 PM" src="https://user-images.githubusercontent.com/1255594/217942581-8fe10e51-f3ed-42af-8fb3-1158e7867d9f.png">

### So what's the deal?

What really matters is the **dart compiler** that is being used.

In debug mode (`flutter run`) flutter uses `dartdevc` (which allows for hot restart/recompiling pressing "r"). In profile and release mode (`flutter build`), flutter compiles with `dart2js` (this produces a deployable bundle).

I suspect that `dart2js` is seeing an opportunity to "optimize" the generated app code, and attempting to do something with the [KeycloakPromise](https://github.com/gibahjoe/keycloak_flutter/blob/master/lib/src/keycloak.dart#L333) definition. Note how the error in profile mode (the same as release, but without minification) mentions "_chain**Foreign**Future".

The compiler is confused because the package claims that `KeycloakPromise implements Future`. 

When doing JS-interop with Dart, mixing JS-Interop with regular Dart objects is a bad idea (AFAIK this is actually such a large problem that it won't be doable in the future). In the case of the KeycloakPromise, the js-interop definition claims that it `implements Future` (when it actually [does *not*](https://api.dart.dev/be/175791/dart-async/Future-class.html#instance-methods)), and the Dart type system fails with a TypeError when it can't find an `onError` function (or at least that's what it looks to me, without being an expert in the web compilers).

It is very likely that this works in debug mode because DDC just "trusts" whatever you say in your JS definition, for compilation speed's sake.

### Testing the fix

I've applied [the fix](https://github.com/gibahjoe/keycloak_flutter/pull/19) and the flutter test app provided above now initializes correctly for any renderer in `profile` mode.

I think the keycloak_flutter author should have picked this up when testing their package, but I have personally pushed code that "works on ddc but breaks in dart2js", so I can't be too hard on them. (Not having landed the PR in this long is maybe a red flag 🚩)

I hope this little investigation satisfies your curiosity. I don't think there's much more we can do in this issue?

**Comment by jonasbark** [comment] 2023-02-09 22:06
Yes indeed, thank you for the thorough investigation. I guess I understand what the underlying issue is.

But while it may be the developers fault in not detecting it (which isn't easy when it only fails in Release mode) - shouldn't the web compiler itself see the issue and make the compilation fail with a proper error? Is this issue better suited for another repository?

**Comment by ditman** [comment] 2023-02-09 22:27
> shouldn't the web compiler itself see the issue and make the compilation fail with a proper error?

@jonasbark Actually, I cloned the package itself, and **the compiler does complain,** but the author decided to mark the offending class as `abstract` (and never implement it anywhere else) to silence the error 🫡

<img width="640" alt="Screenshot 2023-02-09 at 2 16 47 PM" src="https://user-images.githubusercontent.com/1255594/217952001-d833e47e-3655-42da-81ac-0ec67bb4edd3.png">

> Is this issue better suited for another repository?

I don't think there's anything of interest left to discuss with anybody other than the package author. IMO, enough energy has been used here to discover what we already suspected: the package needs some extra love ([and](https://github.com/gibahjoe/keycloak_flutter/blob/master/test/keycloak_flutter_test.dart) [tests](https://github.com/gibahjoe/keycloak_flutter/blob/master/example/integration_test/app_test.dart)).

**Closed** 2023-02-09 22:28 UTC
Labels: severe: crash, waiting for customer response, platform-web, e: web_canvaskit, has reproducible steps, assigned for triage, found in release: 3.3, found in release: 3.4
