### ISSUE TITLE
Back button isn't displayed

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#65582] opened 2020-09-10 21:04 UTC
## Steps to Reproduce

1. Run this Gist on DartPad: https://dartpad.dev/71e1f185541eecc0a934723261b96901
2. Click "show details"
3. See that the back button doesn't appear:

<img width="539" alt="Screen Shot 2020-09-10 at 2 01 05 PM" src="https://user-images.githubusercontent.com/1145719/92805598-1acfce80-f36e-11ea-92de-0c4c90d8149e.png">

@dnfield @willlarche Is it possible that the icon is getting optimized away since it's not used directly?

**Comment by dnfield** [comment] 2020-09-10 21:35
Web doesn't do any icon shaking. Does this reproduce on mobile/desktop?

**Comment by dnfield** [comment] 2020-09-10 21:38
Oh. It seems like whatever revision DartPad is on is not matched properly to the icon font it's trying to use.  See e.g.:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: ColoredBox(
        color: Colors.white,
        child: Column(children: [
          Icon(Icons.play_arrow),
          Icon(Icons.ac_unit),
        ]),
      ),
    ),
  );
}
```

Shows the wrong icons in Dart.

**Comment by dnfield** [comment] 2020-09-10 21:41
![image](https://user-images.githubusercontent.com/8620741/92811854-b0ba2800-f373-11ea-92c9-77fc592c8fa5.png)

**Comment by johnpryan** [comment] 2020-09-10 22:04
Good catch, I'll move this issue to DartPad's tracker: https://github.com/dart-lang/dart-pad/issues/1627

**Comment by dnfield** [comment] 2020-09-10 22:06
Closing this one in favor of the DartPad bug. We can reopen if it turns out to require a fix on Flutter's end.

**Closed by dnfield** 2020-09-10 22:06 UTC
