### ISSUE TITLE
Launching native ViewController over Flutter seems to kill rendering upon returning

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#26966] opened 2019-01-23 16:09 UTC
Sorry if the title is worded incorrectly, and please update if necessary.  I'm not entirely sure what's happening here but it's 100% reproducible with the version of Flutter I'm on.  Also this isn't only happening with the ImagePicker plugin, it happens with any ViewController.

Basically, when I launch a ViewController over Flutter and do my work with that and then return, Flutter just seems to stop rendering?  

Here's a demo project to test on: https://github.com/KevinTheGray/flutter_app_image_picker_issue

For example, In the demo project I provided, I select an image from the ImagePicker, the await completes (proven by a print statement), and build is called.  The `_image` field clearly has data now (again proven by a print), yet it doesn't render it.  Notice also that the splash on the button stops rendering.  The button does still react though.

I see statements like these in the console, that seem related:
```
[VERBOSE-2:gpu_surface_gl.cc(42)] Could not make the context current to setup the gr context.
flutter: null
[VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
```

## Steps to Reproduce

1. Clone the project provided above
2. Press the FAB so the ImagePicker launches
3. Take a picture and return
4. The image is not rendered in Flutter, the console start printing warnings, and the splash on the FAB no longer renders.  

## Logs
```
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on iPhone is available at: http://127.0.0.1:1046/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+6518 ms] flutter: awaiting pick image...
[+17605 ms] [VERBOSE-2:gpu_surface_gl.cc(42)] Could not make the context current to setup the gr context.
[   +1 ms] flutter: finished awaiting pick image...
[        ] flutter: File:
'/private/var/mobile/Containers/Data/Application/25DC0322-FCA3-4421-A003-8F869315E112/tmp/image_picker_1D7AA8E1-8F77-46F
9-A72D-DA405BE922B4-6316-00000425E67A635B.jpg'
[  +22 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[ +248 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[ +278 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[+9062 ms] [VERBOSE-2:gpu_surface_gl.cc(42)] Could not make the context current to setup the gr context.
[   +4 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[+2403 ms] flutter: awaiting pick image...
[  +27 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[  +14 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[  +15 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[   +9 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[  +15 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[  +34 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[  +34 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[  +23 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[  +25 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[   +2 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[        ] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[   +1 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[  +15 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[+5218 ms] flutter: finished awaiting pick image...
[   +2 ms] [VERBOSE-2:gpu_surface_gl.cc(42)] Could not make the context current to setup the gr context.
[   +1 ms] flutter: File:
'/private/var/mobile/Containers/Data/Application/25DC0322-FCA3-4421-A003-8F869315E112/tmp/image_picker_17452203-F7BF-48D
6-8CF8-CF036FD07845-6316-00000425FF786672.jpg'
[   +9 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[ +244 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
[ +270 ms] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.

```

## Flutter Doctor
```
[✓] Flutter (Channel master, v1.1.10-pre.153, on Mac OS X 10.13.6 17G4015, locale en-US)
    • Flutter version 1.1.10-pre.153 at /Users/KG/Developer/Flutter/flutter
    • Framework revision 66f424f0f8 (67 minutes ago), 2019-01-23 15:43:27 +0100
    • Engine revision 319e1c5c1d
    • Dart version 2.1.1 (build 2.1.1-dev.2.0 2e5453ddb4)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25
```

**Comment by dnfield** [comment] 2019-01-23 16:27
I'll take a look, thanks for the details

**Comment by dnfield** [comment] 2019-01-23 17:23
Interesting - I can't reproduce this if I pick an image from the gallery, only if I use the camera.

**Comment by dnfield** [comment] 2019-01-23 22:13
I have a fix for this.  Marking it as TODAY as it's very reproducible when using the Camera plugin (and probably the same root cause for the linked issue).

**Comment by timtraversy** [comment] 2019-01-23 22:18
Seeing this in url_launcher when returning from a Safari View Controller.

**Comment by LynGao** [comment] 2019-01-24 06:45
> I have a fix for this. Marking it as TODAY as it's very reproducible when using the Camera plugin (and probably the same root cause for the linked issue).

Hi, in my project, i also had same problem.
In My Project, i just presented a UIViewController on the FlutterViewController.
After i turn back,  all elements in FlutterViewController did not response to all gestureEvents。
Just like flutter refresh ui not in the main thread.

//Xcode logs:
019-01-24 14:35:07.963210+0800 HWG[2342:192938] flutter: h = 1024.0
2019-01-24 14:35:07.963358+0800 HWG[2342:192938] flutter: w = 1024.0
2019-01-24 14:35:07.963482+0800 HWG[2342:192938] flutter: screen = Size(2048.0, 1536.0)s= Size(1024.0, 768.0)
2019-01-24 14:35:07.967103+0800 HWG[2342:192939] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
2019-01-24 14:35:07.980410+0800 HWG[2342:192938] flutter: h = 1024.0
2019-01-24 14:35:07.980565+0800 HWG[2342:192938] flutter: w = 1024.0
2019-01-24 14:35:07.980770+0800 HWG[2342:192938] flutter: screen = Size(2048.0, 1536.0)s= Size(1024.0, 768.0)
2019-01-24 14:35:07.984729+0800 HWG[2342:192939] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
2019-01-24 14:35:08.014474+0800 HWG[2342:192938] flutter: h = 1024.0
2019-01-24 14:35:08.015285+0800 HWG[2342:192938] flutter: w = 1024.0
2019-01-24 14:35:08.016034+0800 HWG[2342:192938] flutter: screen = Size(2048.0, 1536.0)s= Size(1024.0, 768.0)
2019-01-24 14:35:08.019882+0800 HWG[2342:192939] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
2019-01-24 14:35:08.046755+0800 HWG[2342:192938] flutter: h = 1024.0
2019-01-24 14:35:08.046912+0800 HWG[2342:192938] flutter: w = 1024.0
2019-01-24 14:35:08.047248+0800 HWG[2342:192938] flutter: screen = Size(2048.0, 1536.0)s= Size(1024.0, 768.0)
2019-01-24 14:35:08.051201+0800 HWG[2342:192939] [VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.

//Flutter docor:
[✓] Flutter (Channel master, v1.1.10-pre.163, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.1)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        /Users/xxx/Library/Android/sdk/tools/bin/sdkmanager "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[✓] Connected device (2 available)

**Comment by JohanSnygg** [comment] 2019-01-24 12:17
Seeing this in both url_launcher and barcode_scan plugins. Would be great with a quick fix for this, since all our attempts to rollback to previous flutter versions end up having these bugs still. 

Thanks

**Comment by dnfield** [comment] 2019-01-24 22:09
Fix has landed in engine, should roll through to flutter/flutter soon.

**Closed** 2019-01-25 00:02 UTC
Labels: a: platform-views, engine, severe: crash, ⚠ TODAY

**Comment by flaviup** [comment] 2019-08-02 22:04
I can still reproduce this issue using Google Maps plugin inside an IndexedStack showing another widget on top of the maps and then rotating the device from portrait to landscape back and forth.

**Comment by ChauNTM** [comment] 2019-12-10 06:31
Any one help

> I can still reproduce this issue using Google Maps plugin inside an IndexedStack showing another widget on top of the maps and then rotating the device from portrait to landscape back and forth.

me too, I got the similar situation, when rotating the device and use Stack too.

**Comment by SVyatoslavG** [comment] 2019-12-28 03:31
I am having the same issue with Stack and rotating the device.

**Comment by tp** [comment] 2020-03-23 16:25
> Seeing this in url_launcher when returning from a Safari View Controller.

We're also seeing something similar with Safari View Controller: Deeplinks back to the app are not executed until the user closes Safari VC.

As we use a "deeplink widget" (which requires rendering to update), this seems to be based on the same underlying issue.

Once we moved the deeplink handling out of the widget tree and called `closeWebView` on an incoming link, it worked like a charm.

**Comment by Pebsie** [comment] 2020-04-09 16:11
Why is this closed? It's still an issue.

**Comment by dnfield** [comment] 2020-04-09 18:05
@Pebsie, @tp, @SVyatoslavG  - the specific bug reported here was fixed.  If you have a similar bug, please file an issue with a reproduction and the revision of Flutter you're using (output of `flutter doctor -v`).
