### ISSUE TITLE
Put tree status in the favicon of the build dashboard

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#105035] opened 2022-05-31 16:54 UTC
It would be nice if the tab I have open with the build dashboard would display and update the tree status without having to switch to that tab.  Can we update the favicon to display that information and have it updated periodically?

cc @CaseyHillers

**Comment by CaseyHillers** [comment] 2022-05-31 17:05
This seems like a dupe of https://github.com/flutter/flutter/issues/46175

I haven't seen the tree closed to verify the favicon is changing. I know the icon could be made more explicit. Maybe we could change it to a green and red circle instead of the Flutter logo.

\cc @codebird

**Comment by gaaclarke** [comment] 2022-05-31 17:17
Yep, that sounds like the same issue.  I think it's just a ux problem since the favicon is using different metaphors than the page.  The favicon is (blue text=good, red text=bad), page is (green bar=good, red bar=bad).

I recommend using the same metaphor some good state would look like this:
![New Piskel-1 png](https://user-images.githubusercontent.com/30870216/171234434-95859bee-2c1b-4702-9225-5bff397951a8.png)

Bad state would be the same but red.

**Comment by codebird** [comment] 2022-05-31 17:49
hahahahaha! I think they're fine... @CaseyHillers what do you think?

**Comment by codebird** [comment] 2022-05-31 17:52
I did this, for the failure, but I think @gaaclarke's are better

![favicon-failure](https://user-images.githubusercontent.com/327589/171252615-eab2fb94-34d4-46af-bac6-f33137409dfe.png)

**Comment by gaaclarke** [comment] 2022-05-31 17:57
Shoot, let me update the colors.  That red one looks off.   One sec.

**Comment by gaaclarke** [comment] 2022-05-31 18:00
There we go:

![favicon (2)](https://user-images.githubusercontent.com/30870216/171254024-df8d73f0-56b1-48b1-97f3-f814e617559b.png)
![favicon (1)](https://user-images.githubusercontent.com/30870216/171254035-97fd0d08-de81-48e4-b062-5ff422c23879.png)

**Comment by CaseyHillers** [comment] 2022-05-31 18:01
Thank you @gaaclarke ! These are great, I like the added detail in the Flutter logo

**Comment by codebird** [comment] 2022-06-02 19:40
Hmmmm that's weird I'll check it out tomorrow.

**Comment by codebird** [comment] 2022-06-02 19:43
@gaaclarke was the bar green or red when you switched tabs? I mean did it change when you switched tabs or it was already?

**Comment by gaaclarke** [comment] 2022-06-02 19:53
I wasn't paying attention, sorry

**Comment by codebird** [comment] 2022-06-02 20:00
K will test it tomorrow.

**Comment by gaaclarke** [comment] 2022-06-02 20:07
> I did a test on the Flutter dashboard in Chrome. It changed from red to green when the bar changed, while I was tabbed out.
> 
> @gaaclarke what browser are you using? Maybe it prevents background workers

I'm on chrome.  It could be that I switched tabs before the autorefresh?  Like if it refreshes every 3 minutes maybe I happened to notice quickly via email?

**Comment by codebird** [comment] 2022-06-02 20:18
It is an animatedBuilder. And I guess I saw it updating in the background on localhost Chrome too. I'll still double check just to make sure.

**Comment by gaaclarke** [comment] 2022-06-02 20:40
(It just happened to me again, i'm pretty sure it's not updating.)

**Comment by CaseyHillers** [comment] 2022-06-02 20:46
I realized this doesn't go to the green circle, but instead to the white, boxed logo. However, tree closures do go to the red circle.

> (It just happened to me again, i'm pretty sure it's not updating.)

This is somewhat of a stretch, but do you have any chrome extensions that puts non-focussed tabs to sleep?

**Comment by codebird** [comment] 2022-06-02 20:49
> I realized this doesn't go to the green circle, but instead to the white, boxed logo. However, tree closures do go to the red circle.


The white boxed logo is just cache, it is no longer there.

**Comment by gaaclarke** [comment] 2022-06-02 20:52
When you comment on this thread I see the tab's description update, so it is updating that in the background.  So it seems to work elsewhere.

**Comment by codebird** [comment] 2022-06-03 10:55
I can confirm the issue on Chrome Linux (102.0.5005.61) and Chrome ChromeOS (101.0.4951.72) both the bar and the favicon are not updating. Looks like AnimatedBuilder stops updating when the tab is inactive.

**Comment by nehalvpatel** [comment] 2023-01-26 23:25
Hey, looks like this is good to close?

**Closed** 2023-01-27 01:56 UTC
Labels: new feature, team: infra
