### ISSUE TITLE
iOS navigation sliding title will shake when back swipe on iPhone 8  13.3.1 & iPhone 6  12.4.5

### ISSUE THREAD

**Issue by Tecode** [flutter/flutter#60954] opened 2020-07-07 03:16 UTC
## iOS navigation sliding title will shake

**The phone in question**

```
iPhone 6  12.4.5
iPhone 8  13.3.1
```

I tested the iPhone XR without this problem, I think it may be related to the screen size of the phone.

**Performance result**

![演示](https://github.com/Tecode/Avalon-/blob/master/img/ios_sneke.gif?raw=true)

## flutter --version

```bash
Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (5 weeks ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

## Code

I used CupertinoNavigationBar to set transitionBetweenRoutes `true`. After iphone 6 8 is used for page jump, text jitter will appear.

```dart
import 'package:dynamic_theme/helpers/customBehavior.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Discovery extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        transitionBetweenRoutes: true,
        middle: Text('发现'),
      ),
      child: ScrollConfiguration(
        behavior: CustomBehavior(),
        child: ListView.builder(
          controller: PrimaryScrollController.of(context),
          itemCount: 600,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              height: 44.0,
              width: MediaQuery.of(context).size.width,
              child: Center(child: Text('Data-$index')),
            );
          },
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment] 2020-07-07 09:14
Hi @Tecode 
Can you please provide your `flutter doctor -v`  and complete provide runnable code sample with `CustomBehavior()`. I cannot reproduce this issue using code sample i created on  iPhone 8 simulator. Can you reproduce this simulator too? 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(title: 'Cupertino App', home: Home());
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('Cupertino App Bar'),
      ),
      child: Center(
        child: Container(
          child: CupertinoButton(
              child: Text('Next'),
              onPressed: () {
                Navigator.push(context,
                    CupertinoPageRoute(builder: (_) => SecondScreen()));
              }),
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
        tabBar: CupertinoTabBar(items: [
          BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.home), title: Text("Home")),
          BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.search), title: Text("Search")),
          BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.person), title: Text("User Info"))
        ]),
        tabBuilder: (context, index) {
          switch (index) {
            case 0:
              return FirstPage();
              break;
            case 1:
              return SecondPage();
              break;
            case 2:
              return ThirdPage();
              break;
            default:
              return FirstPage();
              break;
          }
        });
  }
}

class FirstPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        transitionBetweenRoutes: true,
        middle: Text('发现'),
      ),
      child: ListView.builder(
        controller: PrimaryScrollController.of(context),
        itemCount: 600,
        itemBuilder: (BuildContext context, int index) {
          return Container(
            height: 44.0,
            width: MediaQuery.of(context).size.width,
            child: Center(child: Text('Data-$index')),
          );
        },
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        transitionBetweenRoutes: true,
        middle: Text('发现'),
      ),
      child: ListView.builder(
        controller: PrimaryScrollController.of(context),
        itemCount: 600,
        itemBuilder: (BuildContext context, int index) {
          return Container(
            height: 44.0,
            width: MediaQuery.of(context).size.width,
            child: Center(child: Text('Data-$index')),
          );
        },
      ),
    );
  }
}

class ThirdPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        transitionBetweenRoutes: true,
        middle: Text('First'),
      ),
      child: ListView.builder(
        controller: PrimaryScrollController.of(context),
        itemCount: 600,
        itemBuilder: (BuildContext context, int index) {
          return Container(
            height: 44.0,
            width: MediaQuery.of(context).size.width,
            child: Center(child: Text('Data-$index')),
          );
        },
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (3 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!

``` 

</details> 

Thank you

**Comment by Tecode** [comment] 2020-07-07 10:41
Hi @TahaTesser 

`CustomBehavior`

```dart
import 'package:flutter/widgets.dart';

class CustomBehavior extends ScrollBehavior {
  @override
  Widget buildViewportChrome(
      BuildContext context, Widget child, AxisDirection axisDirection) {
    return child;
  }
}
```

**Comment by TahaTesser** [comment] 2020-07-07 13:53
Hi @Tecode 
Can you please confirm the issue reproduces using this code sample i have created for you? Also added `CustomBehavior()`


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(title: 'Cupertino App', home: Home());
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('Cupertino App Bar'),
      ),
      child: Center(
        child: Container(
          child: CupertinoButton(
              child: Text('Next'),
              onPressed: () {
                Navigator.push(context,
                    CupertinoPageRoute(builder: (_) => SecondScreen()));
              }),
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
        tabBar: CupertinoTabBar(items: [
          BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.home), title: Text("Home")),
          BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.search), title: Text("Search")),
          BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.person), title: Text("User Info"))
        ]),
        tabBuilder: (context, index) {
          switch (index) {
            case 0:
              return FirstPage();
              break;
            case 1:
              return SecondPage();
              break;
            case 2:
              return ThirdPage();
              break;
            default:
              return FirstPage();
              break;
          }
        });
  }
}

class FirstPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        transitionBetweenRoutes: true,
        middle: Text('发现'),
      ),
      child: ListView.builder(
        controller: PrimaryScrollController.of(context),
        itemCount: 600,
        itemBuilder: (BuildContext context, int index) {
          return Container(
            height: 44.0,
            width: MediaQuery.of(context).size.width,
            child: Center(child: Text('Data-$index')),
          );
        },
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        transitionBetweenRoutes: true,
        middle: Text('发现'),
      ),
      child: ScrollConfiguration(
        behavior: CustomBehavior(),
        child: ListView.builder(
          controller: PrimaryScrollController.of(context),
          itemCount: 600,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              height: 44.0,
              width: MediaQuery.of(context).size.width,
              child: Center(child: Text('Data-$index')),
            );
          },
        ),
      ),
    );
  }
}

class ThirdPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        transitionBetweenRoutes: true,
        middle: Text('First'),
      ),
      child: ListView.builder(
        controller: PrimaryScrollController.of(context),
        itemCount: 600,
        itemBuilder: (BuildContext context, int index) {
          return Container(
            height: 44.0,
            width: MediaQuery.of(context).size.width,
            child: Center(child: Text('Data-$index')),
          );
        },
      ),
    );
  }
}

class CustomBehavior extends ScrollBehavior {
  @override
  Widget buildViewportChrome(
      BuildContext context, Widget child, AxisDirection axisDirection) {
    return child;
  }
}

``` 

</details>

**Comment by Tecode** [comment] 2020-07-08 02:02
Hi @TahaTesser 

I used the code you provided, this problem does not appear on the `iPhone 8 13.3` virtual machine, there is the problem of text jitter on the physical machine. This problem requires you to test on the physical machine iPhone8 6.

<details>
  <summary>flutter doctor -v<summary>

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.142, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
    • Flutter version 1.20.0-3.0.pre.142 at /Users/aming/Applications/flutter
    • Framework revision cfc0082db7 (22 hours ago), 2020-07-06 23:59:01 -0400
    • Engine revision 0e9b250843
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 69aba23371)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/aming/Library/Android/sdk
    • Platform android-R, build-tools 29.0.0
    • ANDROID_HOME = /Users/aming/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • 测试手机 (mobile)     • 555bc4a3a47db4d03db1be6d09a571e2f91804c6 • ios            • iOS 12.4.5
    • iPhone 8 (mobile) • 2C71AB95-116A-4DF8-ABFD-B4F337D9F49E     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS (desktop)   • macos                                    • darwin-x64     • Mac OS X 10.14.6 18G87
    • Web Server (web)  • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 1 category.

```

</details>

Thank you

**Comment by django-wong** [comment] 2020-08-05 15:38
Having the same issue on physical iPhone X 13.5.1 with Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-CN). Works fine on simulator iOS 13.6

**Comment by Tecode** [comment] 2020-08-06 01:42
@django-wong 这个问题已经给他们反馈了，应该会在flutter1.20的版本会解决这个问题，还需要再等等。或者在开发时不要使用这种切换效果。

**Comment by django-wong** [comment] 2020-08-11 08:31
likely the same issue and a workaround can be found here https://github.com/flutter/flutter/issues/42759

**Comment by gaaclarke** [comment] 2020-10-26 23:09
I'm unable to reproduce this with the following setup on an iPhone 8 and the code from https://github.com/flutter/flutter/issues/60954#issuecomment-654878054:
```
[✓] Flutter (Channel master, 1.24.0-2.0.pre.91, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
    • Flutter version 1.24.0-2.0.pre.91 at /Users/aaclarke/dev/flutter
    • Framework revision cb5865d86c (6 days ago), 2020-10-20 09:50:31 -0700
    • Engine revision ea2aea1c61
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Connected device (4 available)
    • iPhone (2) (mobile) • 9f7f1435a54bb826cdca696461217ecc2dabda05 • ios            • iOS 13.5.1
```

The titles of the pages actually fades out during the animation for me.  I was trying to verify that it is the same issue as https://github.com/flutter/flutter/issues/42759 which it almost assuredly is.  Can you please verify?

**Comment by pedromassangocode** [comment] 2020-11-20 13:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-20 13:08 UTC
Labels: e: OS Version specific, f: cupertino, found in release: 1.20, framework, has reproducible steps, platform-ios, waiting for customer response
