### ISSUE TITLE
Border on Container causes small artefacts

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#43159] opened 2019-10-21 08:51 UTC
Image: 
![bug_image](https://i.imgur.com/dwrKakV.png)

Code:

```
Container(
  width: 40,
  height: 40,
  decoration: BoxDecoration(
    color: Colors.purple,
    border: Border.all(
      color: Colors.white,
      width: 2,
     ),
    borderRadius: BorderRadius.circular(40),
  ),
)
```

flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.9.1+hotfix.5 at /Users/tudor/dev/flutter
    • Framework revision 1aedbb1835 (4 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tudor/Library/Android/sdk
    • Java binary at: /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro • 332C8E72-5F12-4719-B917-2A2687F7FB42 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by iapicca** [comment] 2019-10-21 10:14
Hi @tudor07 
thank you for opening this issue,
I guess the Border radius was missing from your code,
nevertheless your claim is correct

>  child: Container(
>         width: 40,
>         height: 40,
>         decoration: BoxDecoration(
>           color: Colors.purple,
>           borderRadius: BorderRadius.circular(100),
>           border: Border.all(
>             color: Colors.white,
>             width: 2,
>           ),
>         ),
>       ),

**Comment by tudor07** [comment] 2019-10-21 10:15
Yes, just edited. It happens with a square shape as well though.

**Comment by bleroux** [comment] 2019-10-22 10:14
@tudor07 Same problem here with the circle. 
But I'm not able to reproduce it with a square shape. 
Thank you to add screenshot and code using a square shape.

**Comment by tudor07** [comment] 2019-10-23 07:38
@bleroux 
![square_shape](https://i.imgur.com/lmZmA0N.png)

```
Container(
  width: 40,
  height: 40,
  decoration: BoxDecoration(
    color: Colors.purple,
    border: Border.all(
      color: Colors.white,
      width: 2,
    ),
  ),
),
```

It's more visible with the circle though.

**Comment by lumenier1** [comment] 2019-10-29 11:39
Same problem:
<img width="436" alt="flutter-box-decoration-shadow-2" src="https://user-images.githubusercontent.com/23046497/67763888-c3788680-fa59-11e9-9005-5bdc91d4c835.png">

```
Row(children: <Widget>[
  Image.asset(
    'assets/images/shopping-cart-icon.png',
    fit: BoxFit.fitHeight,
    width: 41,
    height: 39,
  ),
  Transform.translate(
    offset: Offset(-10.0, -10.0),
    child: Container(
      width: 26,
      height: 26,
      decoration: BoxDecoration(
        color: Color(0xFF44B751),
        shape: BoxShape.circle,
        border: new Border.all(
          color: Colors.white,
          width: 3.0,
          style: BorderStyle.solid
        ),
      ),
      child: Center(
        child: Text('3', style: TextStyle(fontSize: 14, color: Colors.white)),
      )
    )
  )
],)
```

**Comment by bleroux** [comment] 2019-10-29 15:20
I found some explanations there : https://github.com/flutter/flutter/issues/25009
And a workaround in this comment : https://github.com/flutter/flutter/issues/25009#issuecomment-445061729

**Comment by VladyslavBondarenko** [comment] 2020-01-15 13:23
Thanks @bleroux !
@tudor07 follow on https://github.com/flutter/flutter/issues/25009
I'm closing the current as duplicate.
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by tudor07** [comment] 2020-01-15 15:15
@VladyslavBondarenko That issue is marked as `platform-android` while my issue is happening also on iOS

**Comment by fluttercorner** [comment] 2020-10-07 03:45
[How to add Border Radius to Container in Flutter ?](https://fluttercorner.com/how-to-add-border-radius-to-container-in-flutter/)

**Comment by tudor07** [comment] 2020-10-07 07:16
@fluttercorner thanks, I just reported you

**Comment by TahaTesser** [comment] 2020-10-23 12:06
<img width="401" alt="Screenshot 2020-10-23 at 5 34 16 PM" src="https://user-images.githubusercontent.com/48603081/97001577-3675e980-1556-11eb-819c-dadd8d120a3e.png">
<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          width: 40,
          height: 40,
          decoration: BoxDecoration(
            color: Colors.purple,
            border: Border.all(
              color: Colors.white,
              width: 2,
            ),
            borderRadius: BorderRadius.circular(40),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-4.0.pre.33, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-4.0.pre.33 at /Users/tahatesser/Code/flutter_master
    • Framework revision 351ccf7eaf (5 hours ago), 2020-10-22 23:28:51 -0700
    • Engine revision defa8be2b1
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 86.0.4240.111

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2022-11-10 12:36
Using the code sample provided above and running with latest versions, zooming in the image shows the artefacts as below:

<img width="661" alt="Screenshot 2022-11-10 at 6 00 53 PM" src="https://user-images.githubusercontent.com/67046386/201093227-2a9c709a-ffb2-4206-8166-875241178c29.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.8 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (25 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.6.0-1.0.pre.11, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.6.0-1.0.pre.11 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e6fb12469d (2 hours ago), 2022-11-09 21:41:49 -0500
    • Engine revision b42ed6933c
    • Dart version 2.19.0 (build 2.19.0-382.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by chunlea** [comment] 2023-08-07 21:22
Follow https://github.com/flutter/flutter/issues/14288#issuecomment-1542861156, I just confirmed Impeller solved this problem in Android!

| w/o Impeller | w/ Impeller |
|--------|--------|
| ![CleanShot 2023-08-07 at 14 21 12@2x](https://github.com/flutter/flutter/assets/1522415/160687a0-215a-4d22-815d-632b7d6d4188) | ![CleanShot 2023-08-07 at 14 22 02@2x](https://github.com/flutter/flutter/assets/1522415/03c1c474-272e-4861-9f4d-0dc32f0fda6d) |

**Comment by jonahwilliams** [comment] 2024-08-13 03:33
Duplicate of https://github.com/flutter/flutter/issues/14288 and https://github.com/flutter/flutter/issues/13675

**Closed by jonahwilliams** 2024-08-13 03:33 UTC
Labels: engine, c: performance, dependency: skia, has reproducible steps, P2, r: duplicate, found in release: 3.3, found in release: 3.6, team-engine, triaged-engine

**Comment by bernaferrari** [comment] 2024-08-15 20:04
This is now fixed.
