### ISSUE TITLE
Video init error It sometimes comes and sometimes doesn't with the same code only

### ISSUE THREAD

**Issue by rishabhshukla7** [flutter/flutter#57955] opened 2020-05-25 17:56 UTC
```
W/Adreno-ES20(28259): <get_gpu_clk:229>: open failed: errno 13
I/ExoPlayerImpl(28259): Init 457c340 [ExoPlayerLib/2.9.6] [rolex, Redmi 4A, Xiaomi, 25]
W/VideoCapabilities(28259): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(28259): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(28259): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(28259): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(28259): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(28259): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(28259): Unsupported mime video/divx
W/VideoCapabilities(28259): Unsupported mime video/divx4
W/VideoCapabilities(28259): Unsupported mime video/mp4v-esdp
W/VideoCapabilities(28259): Unsupported mime video/mp4v-esdp
W/Utils   (28259): could not parse long range '35-34'
I/VideoCapabilities(28259): Unsupported profile 4 for video/mp4v-es
W/VideoCapabilities(28259): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(28259): Unrecognized profile 2130706434 for video/avc
I/OMXClient(28259): MuxOMX ctor
I/MediaCodec(28259): [OMX.qcom.video.decoder.avc] setting surface generation to 28937217
I/ExtendedACodec(28259): setupVideoDecoder()
I/ExtendedACodec(28259): vpp-enable search is 0 and value is 0
I/ExtendedACodec(28259): Decoder will be in frame by frame mode
D/SurfaceUtils(28259): set up nativeWindow 0x7f78ee6810 for 640x352, color 0x7fa30c04, rotation 0, usage 0x2002900
I/OMXClient(28259): MuxOMX ctor
I/ACodec  (28259): codec does not support config priority (err -2147483648)
I/ACodec  (28259): codec does not support config priority (err -2147483648)
I/ACodec  (28259): codec does not support config operating rate (err -2147483648)
E/ACodec  (28259): Failed to allocate buffers after transitioning to IDLE state (error 0xffffffea)
E/ACodec  (28259): signalError(omxError 0x80001001, internalError -22)
E/MediaCodec(28259): Codec reported err 0xffffffea, actionCode 0, while in state 5
W/AHierarchicalStateMachine(28259): Warning message AMessage(what = 'omxI') = {
W/AHierarchicalStateMachine(28259):   int32_t type = 0
W/AHierarchicalStateMachine(28259):   int32_t event = 0
W/AHierarchicalStateMachine(28259):   int32_t data1 = 0
W/AHierarchicalStateMachine(28259):   int32_t data2 = 1
W/AHierarchicalStateMachine(28259): } unhandled in root state.
W/MediaCodecRenderer(28259): Failed to initialize decoder: OMX.google.aac.decoder
W/MediaCodecRenderer(28259): java.lang.IllegalArgumentException: start failed
W/MediaCodecRenderer(28259): 	at android.media.MediaCodec.native_start(Native Method)
W/MediaCodecRenderer(28259): 	at android.media.MediaCodec.start(MediaCodec.java:1991)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(28259): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(28259): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/MediaCodecRenderer(28259): 	at android.os.Looper.loop(Looper.java:163)
W/MediaCodecRenderer(28259): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(28259): Playback error.
E/ExoPlayerImplInternal(28259): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.google.aac.decoder, Format(2, null, null, audio/mp4a-latm, null, -1, und, [-1, -1, -1.0], [2, 48000])
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(28259): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(28259): 	at android.os.Looper.loop(Looper.java:163)
E/ExoPlayerImplInternal(28259): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(28259): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.google.aac.decoder, Format(2, null, null, audio/mp4a-latm, null, -1, und, [-1, -1, -1.0], [2, 48000])
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(28259): 	... 9 more
E/ExoPlayerImplInternal(28259): Caused by: java.lang.IllegalArgumentException: start failed
E/ExoPlayerImplInternal(28259): 	at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(28259): 	at android.media.MediaCodec.start(MediaCodec.java:1991)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
E/ExoPlayerImplInternal(28259): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(28259): 	... 10 more
E/flutter (28259): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.google.aac.decoder, Format(2, null, null, audio/mp4a-latm, null, -1, und, [-1, -1, -1.0], [2, 48000]), null)
E/flutter (28259): 
```

**Comment by TahaTesser** [comment] 2020-05-26 10:18
Hi @rishabhshukla7 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by kw2019ltd** [comment] 2020-06-07 11:18
same issue with me

**video_player: ^0.10.11+1**

I/ACodec  (15445): ignoring message as already freed component: AMessage(what = 'omxL', target = 52) = {
I/ACodec  (15445):   int32_t generation = 1
I/ACodec  (15445):   RefBase *messages = 0x75611e0650
I/ACodec  (15445): }
W/MediaCodecRenderer(15445): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(15445): android.media.MediaCodec$CodecException: start failed
W/MediaCodecRenderer(15445): 	at android.media.MediaCodec.native_start(Native Method)
W/MediaCodecRenderer(15445): 	at android.media.MediaCodec.start(MediaCodec.java:2159)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(15445): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(15445): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer(15445): 	at android.os.Looper.loop(Looper.java:214)
W/MediaCodecRenderer(15445): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(15445): Playback error.
E/ExoPlayerImplInternal(15445): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1280, 720, -1.0], [-1, -1])
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(15445): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(15445): 	at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(15445): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(15445): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1280, 720, -1.0], [-1, -1])
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(15445): 	... 9 more
E/ExoPlayerImplInternal(15445): Caused by: android.media.MediaCodec$CodecException: start failed
E/ExoPlayerImplInternal(15445): 	at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(15445): 	at android.media.MediaCodec.start(MediaCodec.java:2159)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
E/ExoPlayerImplInternal(15445): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(15445): 	... 10 more
D/SurfaceUtils(15445): connecting to surface 0x757de5a010, reason connectToSurface
I/MediaCodec(15445): [OMX.qcom.video.decoder.avc] setting surface generation to 15815691
D/SurfaceUtils(15445): disconnecting from surface 0x757de5a010, reason connectToSurface(reconnec

**Comment by TahaTesser** [comment] 2020-06-17 12:00
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-17 12:00 UTC
Labels: in triage
