### ISSUE TITLE
Can't clone flutter to .flutter folder

### ISSUE THREAD

**Issue by ykmnkmi** [flutter/flutter#41891] opened 2019-10-03 04:55 UTC
## Steps to Reproduce
1. git clone -b beta https://github.com/flutter/flutter .flutter
2. add .flutter/bin to PATH
3. any flutter command

## Logs
```[ykmnkmi@notebook ~]$ flutter doctor


Unhandled exception:
FileSystemException: Cannot create file, path = '/home/ykmnkmi/.flutter' (OS Error: Is a directory, errno = 21)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.createSync (dart:io/file_impl.dart:281:5)
#2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:119:13)
#3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:17)
#4      new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:175:20)
#5      new Usage (package:flutter_tools/src/reporting/usage.dart:70:9)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:106:20)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#11     Usage.instance (package:flutter_tools/src/reporting/usage.dart:76:40)
#12     flutterUsage (package:flutter_tools/src/reporting/usage.dart:60:33)
#13     _handleToolError (package:flutter_tools/runner.dart:120:7)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:77:13)
<asynchronous suspension>
#15     _rootRunBinary (dart:async/zone.dart:1148:13)
#16     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#17     runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#19     Future._propagateToListeners (dart:async/future_impl.dart:628:16)
#20     Future._completeError (dart:async/future_impl.dart:530:5)
#21     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1500:12)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50:10)
#36     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#37     main (file:///home/ykmnkmi/.flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by pouledodue** [comment] 2019-10-03 05:20
clone it somewhere else?

**Comment by BondarenkoStas** [comment] 2019-10-03 10:28
@ykmnkmi right, please try to clone it not in .flutter

**Comment by janmoppel** [comment] 2019-10-03 10:29
Hello @ykmnkmi !

Thank you for posting an issue.
This is a duplicate of this issue: #25089. You can rename the folder, and it should solve it.

**Comment by janmoppel** [comment] 2019-10-03 10:31
Closing this one, as the solution was found in the other issue.

**Comment by ykmnkmi** [comment] 2019-10-03 11:00
but problem is not solved

**Closed** 2019-10-03 11:00 UTC

**Comment by pouledodue** [comment] 2019-10-03 11:10
@ykmnkmi what is your OS?

**Comment by pouledodue** [comment] 2019-10-03 11:13
```
git clone -b beta https://github.com/flutter/flutter .flutter_sdk
```
then add `.flutter_sdk/bin` to your PATH environment variable
