### ISSUE TITLE
GoogleMap doesn't blur when using BackdropFilter (iOS)

### ISSUE THREAD

**Issue by ZhuBoao** [flutter/flutter#103126] opened 2022-05-05 12:24 UTC
## Steps to Reproduce
I was trying to build a widget on top of a full screen Google Map widget, and blur all the background including the map. However everything else is blurred but the map when I add a BackdropFilter on top of the `Stack`.

**Expected results: The map is blurred

**Actual results: The map is not blurred. But if I replace the map with any other image widget, it will be blurred. Just the map is not working.

Here is sample code:
```dart
return Scaffold(
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: cameraTarget,
              zoom: cameraZoom,
            ),
          ),
          // If I replace the map with this, it will be blurred
          // Container(
          //   height: 1.sh,
          //   width: 1.sw,
          //   color: Colors.blue,
          //   child: Image.network("https://picsum.photos/500/500"),
          // ),
          BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 6, sigmaY: 6),
            child: Center(
              child: Container(
                height: 100.h,
                width: 100.w,
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(10),
                      topRight: Radius.circular(10),
                      bottomLeft: Radius.circular(10),
                      bottomRight: Radius.circular(10)),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.5),
                      spreadRadius: 6,
                      blurRadius: 5,
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
```
Screenshots:
| Google Map | Building with another image |
| -- | -- |
| ![WechatIMG229](https://user-images.githubusercontent.com/17305573/166923215-4d044550-86ec-485c-a9c2-c1e9a1012d24.jpeg) | ![WechatIMG228](https://user-images.githubusercontent.com/17305573/166923225-4e7a4890-d40e-495d-ae27-b9136cbc4c21.jpeg) |

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
    • Flutter version 2.10.5 at /Users/leonardo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/leonardo/Library/Android/sdk
    • Platform android-32, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/leonardo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 00008020-000A3D240AD9002E • ios • iOS 15.3 19D50

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

I understand there is a [similar issue](https://github.com/flutter/flutter/issues/56789), but this seems to be marked duplicated to [another issue](https://github.com/flutter/flutter/issues/56789) which seems to be resolved by [this PR](https://github.com/flutter/engine/pull/28500). However I don't feel like the original issue is actually resolved. The `BackdropFilter` is still not working on Google Map.

**Comment by danagbemava-nc** [comment] 2022-05-05 13:21
Hi @ZhuBoao, this is a duplicate of https://github.com/flutter/flutter/issues/43902. 

Kindly follow up there for more info. 

Closing from here as duplicate. If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-05-05 13:21 UTC
Labels: in triage
