### ISSUE TITLE
Linear Gradient transform is broken

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#77743] opened 2021-03-09 21:38 UTC
I am 90% certain this was working a few days ago. But there has been no commit in the gradients file. Maybe it is an SKIA issue?
 
I expect that `transform: GradientRotation(1.20),` to be different than `transform: GradientRotation(2.40),` (it is in radians). However, the output is exactly the same. For SweepGradients, Transform is working as intended. Only in Linear that I can't get it to work.

![image](https://user-images.githubusercontent.com/351125/110541292-502f5c00-8106-11eb-99d7-5e19115123e5.png)
 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Row(children: [
      Container(
        width: 50,
        height: 50,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            transform: GradientRotation(1.20),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
      Container(
        width: 50,
        height: 50,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            transform: GradientRotation(2.40),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
      Container(
        width: 50,
        height: 50,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            transform: GradientRotation(3.60),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
    ]);
  }
}
```
</details>

Tested on DartPad with Flutter 2.0.1 Dart SDK 2.12.0 and locally on web with:
```
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale
    en-BR)
    • Flutter version 2.0.1 at /usr/local/flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
```

**Comment by pedromassangocode** [comment] 2021-03-10 08:17
Hi @bernaferrari 
Is it possible for you to provide a visual representation of the expected result? Is the expected UI like the image bellow?

Note: I've just increased the size of the containers to make it more visible!

![Screen Shot 2021-03-10 at 09 13 46](https://user-images.githubusercontent.com/67424416/110597502-edc77180-8180-11eb-8394-e1b2ac421005.png)

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-AO)
    • Flutter version 2.0.1 at /Users/pedromassango/Code/flutter_beta
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by bernaferrari** [comment] 2021-03-10 18:14
It is hard to think in radians. I changed the angles to be in degrees. I expect something like this picture:

![image](https://user-images.githubusercontent.com/351125/110676832-313ad380-81b3-11eb-912b-db1763fdadd7.png)

<details>
<summary>code sample</summary>

```dart
import 'dart:math' as math;
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Row(children: [
      Container(
        width: 50,
        height: 50,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            transform: GradientRotation(45 * math.pi/180),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
      Container(
        width: 50,
        height: 50,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            transform: GradientRotation(90 * math.pi/180),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
      Container(
        width: 50,
        height: 50,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            transform: GradientRotation(120 * math.pi/180),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
    ]);
  }
}
```
</details>

**Comment by pedromassangocode** [comment] 2021-03-11 07:24
> It is hard to think in radians. I changed the angles to be in degrees. I expect something like this picture:

The `GradientRotation` constructor expects a radian value!

There is something wrong for sure, some values simply have no effects.

Note: For this image, I had to remove the align property!

![Screen Shot 2021-03-11 at 08 18 50](https://user-images.githubusercontent.com/67424416/110750203-6b06eb00-8242-11eb-95ba-08b0555a8b7d.png)


<details>
<summary>code sample</summary>

```dart
import 'dart:math' as math;
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Row(children: [
      Container(
        width: 150,
        height: 150,
        margin: EdgeInsets.all(8),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            //begin: Alignment.topCenter,
            //end: Alignment.bottomCenter,
            transform: GradientRotation(1.6),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
      Container(
        width: 150,
        height: 150,
        margin: EdgeInsets.all(8),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            //begin: Alignment.topCenter,
            //end: Alignment.bottomCenter,
            transform: GradientRotation(0),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
      Container(
        width: 150,
        height: 150,
        margin: EdgeInsets.all(8),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            //begin: Alignment.topCenter,
            //end: Alignment.bottomCenter,
            transform: GradientRotation(120),
            colors: [Color(0xffff9900), Color(0xff00088d)],
          ),
        ),
      ),
    ]);
  }
}
```
</details>

**Comment by bernaferrari** [comment] 2021-03-11 15:03
Oh, sorry. I know they support radians. That's why I updated the sample to use 45 * math.pi / 180 instead of 1.2 😅

**Comment by pedromassangocode** [comment] 2021-03-12 13:21
> Well.. It has a default value?

Yes

**Comment by plexp** [comment] 2021-04-19 00:47
I think it's duplicate of #79980

**Comment by bernaferrari** [comment] 2021-04-19 01:26
Yeah, probably

**Comment by pedromassangocode** [comment] 2021-04-19 11:31
Since https://github.com/flutter/flutter/issues/79980 is being worked out, I'm going to close this as duplicate.
Thanks everyone

**Closed by pedromassangocode** 2021-04-19 11:31 UTC
Labels: found in release: 2.0, found in release: 2.1, framework, has reproducible steps
