### ISSUE TITLE
Flutter web TextField mouse click on the multiline text does not position the cursor on the text where clicked.

### ISSUE THREAD

**Issue by kkibria** [flutter/flutter#53705] opened 2020-03-31 22:38 UTC
In web build when a ``TextField`` is used with multiline, and multiple line has been entered, mouse clicking on any part of the text does not move the cursor on the text and position itself at the place where the mouse has been clicked.

```
final TextEditingController _controller = TextEditingController();
...  
TextField(
   maxLines: 20,
   controller: _controller,
),
```

**Comment by VladyslavBondarenko** [comment] 2020-04-01 09:34
Hi @kkibria 
Please follow up on https://github.com/flutter/flutter/issues/33523,
Closing current one as duplicate of https://github.com/flutter/flutter/issues/51640,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-04-01 09:34 UTC
