### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by DimaOstrovskyiEk** [flutter/flutter#134518] opened 2023-09-12 09:58 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm using [url_launcher 6.1.14](https://pub.dev/packages/url_launcher) and just received this exception in a live app's error reporting from a device running Android 14:

### Expected results

One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(16603): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
E/AndroidRuntime(16603): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
E/AndroidRuntime(16603): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(16603): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime(16603): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime(16603): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
E/AndroidRuntime(16603): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16603): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(16603): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(16603): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(16603): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16603): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(16603): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

### Actual results

The web browser must be open with the appropriate page.

### Code sample

<details><summary>Code sample</summary>

```dart
launchUrl('https://www.google.com');
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(16603): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
E/AndroidRuntime(16603): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
E/AndroidRuntime(16603): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(16603): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime(16603): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime(16603): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
E/AndroidRuntime(16603): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16603): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(16603): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(16603): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(16603): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16603): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(16603): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2023-09-12 11:49
Closing as a duplicate of https://github.com/flutter/flutter/issues/126460

**Closed by stuartmorgan** 2023-09-12 11:49 UTC
