### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by kansin2017** [flutter/flutter#150085] opened 2024-06-12 06:01 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=83c81b88 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2305:3)
#1      Uint8Buffer._createBuffer (package:typed_data/src/typed_buffer.dart:328:40)
#2      TypedDataBuffer._createBiggerBuffer (package:typed_data/src/typed_buffer.dart:259:12)
#3      TypedDataBuffer._ensureCapacity (package:typed_data/src/typed_buffer.dart:241:21)
#4      TypedDataBuffer._insertKnownLength (package:typed_data/src/typed_buffer.dart:209:5)
#5      TypedDataBuffer._addAll (package:typed_data/src/typed_buffer.dart:186:7)
#6      TypedDataBuffer.addAll (package:typed_data/src/typed_buffer.dart:91:5)
#7      HashSink.add (package:crypto/src/hash_sink.dart:79:18)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:49:11)
#9      Hash.convert (package:crypto/src/hash.dart:28:15)
#10     _calculateSha (package:flutter_tools/src/android/gradle.dart:928:20)
#11     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:586:36)
#12     _rootRunUnary (dart:async/zone.dart:1407:47)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#16     Future._completeWithValue (dart:async/future_impl.dart:652:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:722:7)
#18     _rootRun (dart:async/zone.dart:1399:13)
#19     _CustomZone.run (dart:async/zone.dart:1301:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel stable, 3.22.1, on Microsoft Windows [版本 10.0.22631.3672], locale en-US)
    • Flutter version 3.22.1 on channel stable at D:\flutterLib\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\laowu\AppData\Local\Android\sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • Java binary at: D:\AS\newAS\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.30)
    • Visual Studio at D:\VsBuildTools
    • Visual Studio Build Tools 2019 version 16.11.34031.81
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.

[!] Android Studio (version 2021.2)
    • Android Studio at D:\AS\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.2)
    • Android Studio at D:\AS\newAS
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2022.3.2
    • Flutter plugin version 72.0.4
    • Dart plugin version 223.8617.8

[✓] Connected device (4 available)
    • Mi 10 (mobile)    • 83c81b88 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22631.3672]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 125.0.6422.142
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 120.0.2210.144

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
app_settings-5.1.1
connectivity_plus-6.0.3
device_info_plus-10.1.0
fluwx-4.5.5
location-5.0.0
location_web-4.2.0
mmkv-1.3.5
mmkv_android-1.0.1
mmkv_ios-1.0.1
package_info_plus-8.0.0
path_provider-2.1.3
path_provider_android-2.2.5
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.3.1
permission_handler_android-12.0.6
permission_handler_apple-9.4.4
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
photo_manager-3.1.1
shared_preferences-2.2.3
shared_preferences_android-2.2.3
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
tencent_map_flutter-0.0.1
url_launcher-6.2.6
url_launcher_android-6.3.3
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1

**Comment by danagbemava-nc** [comment] 2024-06-12 08:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133371

**Closed by danagbemava-nc** 2024-06-12 08:48 UTC
Labels: in triage
