### ISSUE TITLE
%5Btool_crash%5D FileSystemException%3A Cannot delete file%2C OS Error%3A The process cannot access the file because it is being used by another process.%0D%0A%2C errno %3D 32

### ISSUE THREAD

**Issue by DotPlusTech** [flutter/flutter#119986] opened 2023-02-04 04:53 UTC
%23%23 Command%0A%60%60%60%0Aflutter --quiet assemble --no-version-check --depfile D%3A%5CProjects%5Chostel_app%5Cbuild%5Capp%5Cintermediates%5Cflutter%5Cdebug%2Fflutter_build.d --output D%3A%5CProjects%5Chostel_app%5Cbuild%5Capp%5

**Comment by huycozy** [comment] 2023-02-06 05:27
Hi @DotPlusTech 
It seems the issue is caused by tool but based on the information above there is not much information to confirm. When it happens again, please click on the link (which usually be shown in the console log) which navigates to a new issue with full filled information so we can confirm it properly. 

Closing the issue as no provided information. Once it's updated with full information, please write a comment and we will re-open it. Thanks!

**Closed by huycozy** 2023-02-06 05:27 UTC
Labels: in triage
