### ISSUE TITLE
License golden file is platform-specific, only can be generated on linux

### ISSUE THREAD

**Issue by jamesr** [flutter/flutter#8405] opened 2017-02-24 23:15 UTC
https://github.com/flutter/engine/blob/master/travis/licenses.golden contains files that only exist in linux checkouts, for example from the android NDK.  This means it's impossible to create a change to the engine that require updates to this file from a non-linux host.

**Comment by Hixie** [comment] 2017-02-25 00:51
The license file should include everything that ends up in every binary on every platform.

I am surprised to hear that Mac doesn't download the Android NDK. How does it build Android binaries?

**Comment by jamesr** [comment] 2017-02-25 01:00
The NDK is not the same on each platform, some bits are platform-specific:
```
 ====================================================================================================
 LIBRARY: ndk
-ORIGIN: ../../../third_party/android_tools/ndk/shader-tools/linux-x86_64/NOTICE
+ORIGIN: ../../../third_party/android_tools/ndk/shader-tools/darwin-x86_64/NOTICE
 TYPE: LicenseType.apache
-FILE: ../../../third_party/android_tools/ndk/shader-tools/linux-x86_64/glslc
-FILE: ../../../third_party/android_tools/ndk/shader-tools/linux-x86_64/repo.prop
-FILE: ../../../third_party/android_tools/ndk/shader-tools/linux-x86_64/spirv-as
-FILE: ../../../third_party/android_tools/ndk/shader-tools/linux-x86_64/spirv-dis
-FILE: ../../../third_party/android_tools/ndk/shader-tools/linux-x86_64/spirv-val
+FILE: ../../../third_party/android_tools/ndk/shader-tools/darwin-x86_64/glslc
+FILE: ../../../third_party/android_tools/ndk/shader-tools/darwin-x86_64/repo.prop
+FILE: ../../../third_party/android_tools/ndk/shader-tools/darwin-x86_64/spirv-as
+FILE: ../../../third_party/android_tools/ndk/shader-tools/darwin-x86_64/spirv-dis
+FILE: ../../../third_party/android_tools/ndk/shader-tools/darwin-x86_64/spirv-val
```
Additionally parts of the NDK appear different on case-sensitive and case-insensitive mountpoints, which are more common on mac:

```
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv4/ipt_ttl.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6_tables.h
-FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_HL.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_LOG.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_NPT.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_REJECT.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_ah.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_frag.h
+FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_hl.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_ipv6header.h
 FILE: ../../../third_party/android_tools/ndk/platforms/android-22/arch-x86_64/usr/include/linux/netfilter_ipv6/ip6t_mh.h
```

**Comment by chinmaygarde** [comment] 2017-02-26 07:57
cc @jason-simmons

**Comment by Hixie** [comment] 2017-03-01 21:24
Dupe of https://github.com/flutter/flutter/issues/8165

**Closed by Hixie** 2017-03-01 21:24 UTC
