### ISSUE TITLE
Theme cursor color not working on iOS dark mode

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#66869] opened 2020-09-29 00:59 UTC
The `cursorColor` field inside the `darkTheme` field of `MaterialApp` only works on Android.

**Code snippet:**
```
MaterialApp(
  title: 'Flutter Demo',
  theme: ThemeData(
    brightness: Brightness.light,
    primarySwatch: Colors.blue,
    cursorColor: Colors.red,
    visualDensity: VisualDensity.adaptivePlatformDensity,
  ),
  darkTheme: ThemeData(
    brightness: Brightness.dark,
    primarySwatch: Colors.blue,
    cursorColor: Colors.red, // <<<<<<<<<<<<<<<<<   Use custom cursor color
    visualDensity: VisualDensity.adaptivePlatformDensity,
  ),
  themeMode: ThemeMode.dark,
  home: MyHomePage(title: 'Flutter Demo Home Page'),
)
```
And:
```
TextField(
  controller: _controller,
  keyboardType: TextInputType.text,
)
```

**Android dark theme:**
The correct cursor color (red) is shown:
![Android](https://user-images.githubusercontent.com/48091135/94500332-bdf66400-0207-11eb-9644-9c38b29bcde7.png)

**iOS dark theme:**
The correct cursor color (red) is **NOT** shown:
![iOS](https://user-images.githubusercontent.com/48091135/94500470-0d3c9480-0208-11eb-8e49-6257ba346c9f.png)

**Comment by pedromassangocode** [comment] 2020-09-29 10:04
Hi @talent-apps 
Can you please provide your `flutter doctor -v`.
Thank you

**Comment by talent-apps** [comment] 2020-09-29 16:28
Output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version
    10.0.18363.1082], locale en-US)
    • Flutter version 1.20.4 at C:\flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)    • Android SDK at C:\Users\XXX\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\XXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for
      detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available
```

**Comment by pedromassangocode** [comment] 2020-09-30 08:31
Hi @talent-apps 
Based on latest master branch, the `cursorColor` property is now deprecated.
![Screen Shot 2020-09-30 at 09 24 39](https://user-images.githubusercontent.com/67424416/94661324-ced5d100-02fe-11eb-8b31-eaa7f3eeca73.png)

You will now use the `textSelectionTheme` property to provide the cursorColor which applies the color properly.

![Screen Shot 2020-09-30 at 09 27 53](https://user-images.githubusercontent.com/67424416/94661660-43107480-02ff-11eb-9b02-014fe057e490.png)

![Screen Shot 2020-09-30 at 09 29 33](https://user-images.githubusercontent.com/67424416/94661842-7e12a800-02ff-11eb-804f-220f87cd078c.png)

I'm closing this since it has been fixed in the master branch. Please wait until the fix lands into the stable (or any other) channel.

Thank you

**Closed by pedromassangocode** 2020-09-30 08:31 UTC
Labels: in triage

**Comment by darrenaustin** [comment] 2020-09-30 22:45
I am pretty sure this is a duplicate of #61227, and should be addressed by the work we have done on with the `TextSelectionTheme` in #62014. Closing this issue, but if it turns out not to be a duplicate, please reopen and we will take another look.

**Comment by pedromassangocode** [comment] 2020-10-01 09:12
It is clearly a duplicate of https://github.com/flutter/flutter/issues/61227 and since the changes are currently on master I think this can remains closed.
