### ISSUE TITLE
Please make flutter to perform multi-thread in web 

### ISSUE THREAD

**Issue by parmeetmaster** [flutter/flutter#86541] opened 2021-07-16 08:41 UTC
I having a scenario when I tried to load huge JSON data from the web using dio or HTTP library. The circular progress indicator is a freezer because flutter is single-threaded language. Even we applied isolates like future and stream also.

I also attached sample repository 
here : https://github.com/parmeetmaster/testing_web_project

**Comment by hndrbrm** [comment] 2021-07-16 09:06
I have tried the code, i think there is some typos in there:
`loadData() async* {` it should be `loadData() async {`

(And whole lot of error on model parsing in there, need to change lot of code)

And the indicator working fine, BTW.

As far as i know:
1. Dart use Javascript as backend in web. And javascript is single threaded.
2. Even it is single threaded its multi process using pool mechanims. And its enough to handle something like progress indicator. It will failed in my experience when i mingled it with native looping in c++ using ffi, but its a differenct cases, since ffi is not mature yet.
3. Until now i don't have any problem loading big json (whole lot bigger than the example above), using dio and CircularProgressIndicator working fine as intended.

**Comment by parmeetmaster** [comment] 2021-07-16 09:14
But my browser is getting hang when if we ignore parsing stuff still.My browser is hang.My gif indicator freezer until dio response comes.

**Comment by maheshmnj** [comment] 2021-07-16 09:26
@parmeetmaster,
Isolates are not supported on the web, Future and Streams are not isolates these are ways of performing asynchronous operations, Please take a look at using isolates here in the flutter docs here : https://api.dart.dev/stable/2.0.0/dart-isolate/Isolate/spawnUri.html
for difference on ```future vs isolate``` please [read this stackoverflow thread](https://stackoverflow.com/questions/52498773/flutter-isolate-vs-future)

I am going to close this issue as invalid if you disagree feel free to comment and I will reopen it.
Thank you.

**Closed by maheshmnj** 2021-07-16 09:26 UTC
Labels: in triage

**Comment by parmeetmaster** [comment] 2021-07-16 10:37
Isolates are not working in dart4web

**Comment by parmeetmaster** [comment] 2021-07-16 10:38
Please give an alternative solution on dart4web so UI no longer hangs.Until data not loaded from dio or http

**Comment by parmeetmaster** [comment] 2021-07-16 10:40
> @parmeetmaster,
> Isolates are not supported on the web, Future and Streams are not isolates these are ways of performing asynchronous operations, Please take a look at using isolates here in the flutter docs here : https://api.dart.dev/stable/2.0.0/dart-isolate/Isolate/spawnUri.html
> for difference on `future vs isolate` please [read this stackoverflow thread](https://stackoverflow.com/questions/52498773/flutter-isolate-vs-future)
> 
> I am going to close this issue as invalid if you disagree feel free to comment and I will reopen it.
> Thank you.

Please give an alternative solution on dart4web so UI no longer hangs.Until data not loaded from dio or http

**Comment by maheshmnj** [comment] 2021-07-16 11:30
If the data is huge in number you could try pagination and lazy load the data. e.g Try to fetch a batch of 100 data and load another 100 as and when needed.
