### ISSUE TITLE
Travis build failure during npm installation

### ISSUE THREAD

**Issue by aam** [flutter/flutter#13960] opened 2018-01-06 08:33 UTC
```
$ node --version
v6.12.0
$ npm --version
3.10.10
$ nvm --version
0.33.8
NaNs$ ./dev/bots/travis_install.sh
+'[' -n true ']'
+'[' false == false ']'
+gem install coveralls-lcov
Fetching: coveralls-lcov-1.5.1.gem (100%)
Successfully installed coveralls-lcov-1.5.1
1 gem installed
+npm install -g 'firebase-tools@>=3.6.1 <3.7.0'
npm ERR! Linux 4.9.6-040906-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.12.0/bin/node" "/home/travis/.nvm/versions/node/v6.12.0/bin/npm" "install" "-g" "firebase-tools@>=3.6.1 <3.7.0"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect
npm ERR! network connect ETIMEDOUT 151.101.32.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/flutter/flutter/npm-debug.log
The command "./dev/bots/travis_install.sh" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by DanTup** [comment] 2018-06-27 10:47
Seen this twice today but without the network error output:

```
Successfully installed bundler-1.16.2
1 gem installed
+npm install -g 'firebase-tools@>=3.6.1 <3.7.0'
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

It's on the `docs` shard of the Travis built. I restarted it on the first failure and then it did exactly the same. The NPM status page suggests there are no current issues 🤔

**Comment by DanTup** [comment] 2018-06-27 10:49
This is a dupe of https://github.com/flutter/flutter/issues/12928.

**Closed by DanTup** 2018-06-27 10:49 UTC
Labels: team: flakes
