### ISSUE TITLE
Can run android module but can not run main.dart flutter app

### ISSUE THREAD

**Issue by vatsal2710** [flutter/flutter#60736] opened 2020-07-02 03:19 UTC
I can run android module of my flutter project on android device but if i try to run main.dart flutter file (run flutter project) ,I got 

Exception: Gradle task assembleDebug failed with exit code -1

I have tried all possible way to solve this error..I have reinstalled android studio,flutterSDK,SDK,VPN though I can not run my flutter project

flutter doctor :

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Android Studio (version 4.0)
[√] VS Code (version 1.46.1)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

Need help..
Thank you

**Comment by Goolpe** [comment] 2020-07-02 06:45
Try to accept android licenses https://stackoverflow.com/a/49762939

**Comment by TahaTesser** [comment] 2020-07-02 07:26
duplicate of https://github.com/flutter/flutter/issues/60465

**Closed by TahaTesser** 2020-07-02 07:26 UTC
