### ISSUE TITLE
PageView loses current page when phone is locked and then unlocked

### ISSUE THREAD

**Issue by d4manek** [flutter/flutter#61273] opened 2020-07-10 22:35 UTC
## Steps to Reproduce

1. Create a new flutter application and paste in the code below.
2. Build and run the application on an iPhone 11 Pro with OS 13.5.1.
3. Swipe the PageView until you see 'Page 3' on the screen.
4. Lock your iPhone, put it in your pocket and walk around for about 1 minute. I'm not sure why, but it seems necessary to lock the phone and walk around with it for awhile. It may be necessary to put the phone in your pocket in an upside down manor.
5. Pull your phone out of your pocket and unlock it.
6. This isn't consistent, but a good percentage of the time the PageView will be stuck between 'Page 2' and 'Page 3' and will often automatically shift to 'Page 2'. This doesn't happen all the time, but after a few tries it will happen.

This may seem like a minor bug, but I am creating an application that logs data. It requires the user to enter data on one page of the PageView, then after about 10-15 minutes they will log more data on a different page of the PageView. The user typically puts their phone in their pocket between logs. It is a very poor experience to have the PageView stuck between pages and switch away from the last viewed page. This is also very difficult to debug since the debugger disconnects when you lock your phone. I have been unable to reproduce this in the iPhone simulator. My hunch tells me that Flutter thinks the viewport has changed and is recalculating the current page to show, but who knows.

### Source Code

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  // Binds the framework to the Flutter engine
  WidgetsFlutterBinding.ensureInitialized();

  // Force portrait orientation
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final String _title = 'Flutter Demo';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: _title),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SafeArea(
        child: PageView.builder(
          itemCount: 18,
          itemBuilder: (context, index) => _buildPage(context, index),
        ),
      ),
    );
  }

  Widget _buildPage(BuildContext context, int index) {
    return Card(
      clipBehavior: Clip.antiAlias,
      margin: const EdgeInsets.all(16),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
      ),
      child: Center(
        child: Text(
          'Page ${index + 1}',
          style: Theme.of(context).textTheme.headline3,
        ),
      ),
    );
  }
}

```

### Flutter Doctor

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.5 at /Users/X/Development/flutter
    • Framework revision 8af6b2f038 (10 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/X/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 11 Pro • EDE5EEA4-1F2E-46D7-ACD4-AFF06CBC2678 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

**Comment by darshankawar** [comment] 2020-07-13 11:30
Hi @d4manek,
Given the details and since we need to put phone upside down, it may happen that the orientation might be causing the issue that shows the pageview being shifted to Page 2 from Page 3. 
I am going to relate this issue with [61156](https://github.com/flutter/flutter/issues/61156) and close this as duplicate.
If you disagree, please write in the comment and I'll reopen it.
Thanks.

**Comment by d4manek** [comment] 2020-07-31 02:16
I did some more testing on this today. This time I made sure that the phone stayed upright while it was locked. The same problem occurred, so I don't think it's an orientation issue. It happens by simply locking the phone, waiting awhile and then unlocking the phone. Unfortunately it's doesn't reproduce very easily.

**Comment by d4manek** [comment] 2020-09-19 17:18
Still having issues with this. Tested with Flutter 1.22.0-10.0.pre.264 • channel master today which should include fixes for similar issues. No luck. Can you please reopen this?

**Comment by d4manek** [comment] 2020-09-22 23:32
More info on this. I put some logging in to watch the AppLifecycleState and a listener on the page controller for any movement of the PageView. There appears to be a small delay from the time a user clicks the phone's lock button and the time the lifecycle goes inactive. During this time, it's possible for the user to still interact with the screen. For example, if you click the lock button and immediately put your phone in your pocket then it is possible you may have touched the screen and caused the PageView to start scrolling before the lock actually takes hold. This can leave the PageView stuck between pages. When you unlock your phone, the PageView will jump you to the nearest page and that may not be the same page as when you locked your phone. It seems to me that all screen interactions should be immediately ignored once the lock button is pressed. This is a really annoying experience for users. Can someone look at this please?

**Comment by darshankawar** [comment] 2020-10-15 10:33
@d4manek 
Are you still seeing this issue ? I'd recommend to upgrade to latest Flutter version (master or stable) and try again to see if issue persists.

**Comment by darshankawar** [comment] 2020-10-15 10:42
@d4manek Also tried your code sample on latest stable (1.22.1) using iphone 6s with OS 14, but couldn't replicate the issue. I see Page3.

**Comment by d4manek** [comment] 2020-10-15 13:35
I have retested this on 1.22.1 and can still make it happen. Here's an easy way to reproduce it. Start dragging the PageView with one hand to the left or right. At the same time, use the other hand to lock the device by hitting the power button. Essentially, you are forcing the PageView to be stuck between pages while simultaneously locking the device. This mimics the often unreproducible scenario of locking the device and inadvertently touching the screen at approximately the same time. When you unlock the device, the PageView will be stuck between pages and jump one way or the other to lock in on a page.

The strange thing is, while the iPhone is dimming its screen after hitting the lock button it appears that the PageView animates to a snapped position. But when you unlock the phone it is still stuck between pages and animates to a full page.

I am currently working around this issue by using NeverScrollableScrollPhysics on the PageView and forcing the user to click left and right arrow buttons to switch pages.

**Comment by darshankawar** [comment] 2020-10-16 06:11
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

</details>

**Comment by maheshmnj** [comment] 2022-12-07 13:52
We verified this on both Android and IOS (Physical) devices and we are no longer able to reproduce it. 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing, In case anyone still has a problem, Please feel free to comment on the issue and we will reopen it.

**Closed by maheshmnj** 2022-12-07 13:52 UTC
Labels: platform-ios, framework, f: material design, passed first triage, has reproducible steps, found in release: 1.22
