### ISSUE TITLE
Firestore.instance.runTransaction((transaction) async won't work.

### ISSUE THREAD

**Issue by melianawinata** [flutter/flutter#37671] opened 2019-08-06 07:33 UTC
I tried to make application from this tutorial:

https://codelabs.developers.google.com/codelabs/flutter-firebase

and I got stuck at step 11 because

Firestore.instance.runTransaction((transaction) async won't work.

What should i do?

This is the code that i've made so far :
```
Widget _buildListItem(BuildContext context, DocumentSnapshot data) {

    final record = Record.fromSnapshot(data);

    return Padding(
        key: ValueKey(record.name),
        padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
        child: Container(
            decoration: BoxDecoration(
                border: Border.all(color: Colors.grey),
                borderRadius: BorderRadius.circular(5.0),
            ),
        child: ListTile(
            title: Text(record.name),
            trailing: Text(record.votes.toString()),
        onTap: () {
            print("123");
            Firestore.instance.runTransaction((transaction) async {
                print("456");
                final freshSnapshot = await 
                transaction.get(record.reference);
                final fresh = Record.fromSnapshot(freshSnapshot);

                final Map<String, dynamic> json = HashMap<String, dynamic>();
                json['name'] = fresh.name;
                json['votes'] = fresh.votes + 1;
                print(fresh.name);

                await transaction.update(record.reference, json);
            });
        },
        ),
        ),
        );
    }
}
```
it execute  print("123"); but it won't execute  print("456");

**Comment by Superprogrameur59** [comment] 2019-09-17 11:50
Same issue here, need help

**Comment by Superprogrameur59** [comment] 2019-09-17 12:07
Edit : Just update your pubspec.yaml file with "cloud_firestore: ^0.12.9+4" (or check the latest version of the package) and run "flutter pub get" command, it will surely works

**Comment by BondarenkoStas** [comment] 2019-09-19 12:09
@melianawinata Please report if the issue was solved with the comment above?

**Comment by iapicca** [comment] 2019-11-11 16:24
Hi @melianawinata 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-11 16:24 UTC
Labels: waiting for customer response
