### ISSUE TITLE
memory leak of android view

### ISSUE THREAD

**Issue by Stonekity** [flutter/flutter#50104] opened 2020-02-04 09:50 UTC
I have a simple android view in widget tree, it causes a memory leak every time when I back from a page which contains it.

**Comment by VladyslavBondarenko** [comment] 2020-02-04 10:13
Hi @Stonekity 
Could you please provide your `flutter doctor -v`, show how do you define the leak and post a minimal code sample to reproduce it?
Thank you

**Comment by Stonekity** [comment] 2020-02-04 10:26
> Hi @Stonekity
> Could you please provide your `flutter doctor -v`, show how do you define the leak and post a minimal code sample to reproduce it?
> Thank you


[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/stonekity/Library/flutter/flutter_v1.12.13_hotfix5
    • Framework revision 27321ebbad (8 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/stonekity/Library/Android/sdk
    • Android NDK at /Users/stonekity/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • PRO 6s • 80SQBDQ722279 • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 2 categories.

**Comment by liyuqian** [comment] 2020-03-10 00:30
@Stonekity : https://github.com/flutter/flutter/pull/46184 is an example memory test that you may follow. Please let me know if you have any questions. I'm very happy to help.

**Comment by darshankawar** [comment] 2020-09-18 12:01
I am going ahead and closing this issue as fixed, since the concerned [PR](https://github.com/flutter/flutter/pull/50111) made by @Stonekity  was merged. 
If you think this shouldn't be closed, please write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-18 12:01 UTC
Labels: a: platform-views, framework, perf: memory, platform-android, severe: performance
