### ISSUE TITLE
microbenchmarks_ios regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8585] opened 2017-03-06 17:44 UTC
The microbenchmarks_ios test has started failing frequently.

**Comment by Hixie** [comment] 2017-03-06 17:45
cc @yjbanov 

Yegor, can you begin an investigation and delegate to whoever you think is most likely to be able to fix it? (I'm suggesting starting with you since it could be a cocoon issue since it's not failing all the time, just most of the time.)

**Comment by yjbanov** [comment] 2017-03-06 17:49
I'll have a look.

**Comment by yjbanov** [comment] 2017-03-10 00:42
Update: it seems the issue is that `flutter logs` sometimes feeds us log output from past runs. So the benchmark can either pick up wrong numbers or pick up half-printed log and fail.

**Comment by eseidelGoogle** [comment] 2017-03-10 01:54
`adb` on android has this "give you past logs sometimes" problem which we have code to work around.  I wasn't aware iOS could do the same.  @chinmaygarde @xster @cbracken

**Comment by yjbanov** [comment] 2017-03-31 21:01
Fixed by https://github.com/flutter/flutter/commit/bc8cc80b9f4c487021f4a3e3f7ea9e96f6afe833

**Closed by yjbanov** 2017-03-31 21:01 UTC
Labels: dev: tests, regression, team: code health
