### ISSUE TITLE
How to destroy FlutterViewController ?

### ISSUE THREAD

**Issue by shi1234ww** [flutter/flutter#71985] opened 2020-12-09 10:24 UTC
Hi ~  
I had an ios native project which add flutter module to app .  when I called  [self.navigationController popToRootViewControllerAnimated:YES];    It will goback from FlutterViewController to my native Controller  
, But here is a problem that , when I push to   FlutterViewController next time from my native ViewController , The  FlutterViewController won't be destroy , and show the previous flutter page , It seems that although 
 FlutterViewController has dismissed  ,  But It will also exist in memory ??  .   Then I trying to destroy FlutterViewController called [flutterVC.engine destroyContext]  , The app will immediately crash.  So how can I  destroy FlutterViewController manually?  

Here is my code :
```swift
`FlutterEngine *flutterEngine = [(AppDelegate *)[[UIApplication sharedApplication] delegate] flutterEngine];
    FlutterViewController *flutterVC = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
    FlutterBasicMessageChannel *startNaitveBasicMessageChannel = [FlutterBasicMessageChannel messageChannelWithName:@"startNative" binaryMessenger:flutterVC ];

[startNaitveBasicMessageChannel setMessageHandler:^(id  _Nullable message, FlutterReply  _Nonnull callback) {
        if ([message isEqualToString:@"goNative"] ) {
//            [weakSelf.navigationController popToRootViewControllerAnimated:YES];
            [flutterVC.engine destroyContext]; 
        }
}];
[self.navigationController pushViewController:flutterVC animated:YES];
```

<img width="1099" alt="Screen Shot 2020-12-09 at 18 04 50" src="https://user-images.githubusercontent.com/15307512/101615415-0e304480-3a49-11eb-9bd2-ffcb6e7d91e4.png">

shiweiwei@ShiWeiWeideMacBook-Pro ~ % flutter doctor -v
```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-CN)
    • Flutter version 1.22.2 at /Users/shiweiwei/Desktop/Study/flutter
    • Framework revision 84f3d28555 (8 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at
      /Users/shiweiwei/Desktop/Study/Android/Android_SDK/android-sdk-macosx
    • Platform android-29, build-tools 30.0.2
    • ANDROID_HOME =
      /Users/shiweiwei/Desktop/Study/Android/Android_SDK/android-sdk-macosx
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • shiweiwei’s iPhone (mobile) • c578619393aa85cd066dfbd1864f5886c51a35d8 •
      ios • iOS 13.3.1
    • iPhone 8 (mobile)           • 6175D695-E8F0-4608-80E8-4D5062F5748F     •
      ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment] 2020-12-09 14:19
Hi @shi1234ww 
This is a duplicate of https://github.com/flutter/flutter/issues/63092, which I retitled to better describe the issue. 
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-09 14:19 UTC
