### ISSUE TITLE
[web] WebSocketStream is not closed on HotRestart

### ISSUE THREAD

**Issue by masseelch** [flutter/flutter#78212] opened 2021-03-15 13:44 UTC
## Steps to Reproduce

Have a flutter app connect to WebSocket. HotRestart the flutter app:
```dart
_channel = WebSocketChannel.connect(Uri.parse(url));
_channel.stream.listen((event) {
  print(event);
});
```

**Expected results:** I see one print per event on the WebSocket.

**Actual results:** I see one print per event per number of hot restarts. (New connections can even be observed on the server).

<details>
  <summary>Logs</summary>

```
» flutter doctor -v
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.2 at /opt/flutter-stable
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/jcl/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.72

! Doctor found issues in 1 category.

```

</details>

**Comment by iapicca** [comment] 2021-03-15 16:31
> ```dart
> _channel = WebSocketChannel.connect(Uri.parse(url));
> _channel.stream.listen((event) {
>   print(event);
> });
> ```

@masseelch 
where is located the snippet you provided?
can you provide a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by masseelch** [comment] 2021-03-16 08:07
I did some more research and it looks like this is a direct result of Flutter not calling dispose on the widget tree like mentioned by @rrousselGit [in this comment](https://github.com/rrousselGit/provider/issues/621#issuecomment-799513158).

I found lots of issues which all seem to be related to flutter not calling dispose on hot restart (at least in web). I can still provide a reproducible example. but since there are already so many issues open, this would not add any more useful information? What do you think?

**Comment by darshankawar** [comment] 2021-03-16 08:18
@masseelch 
Please provide one to properly address and track this issue.
Thanks.

**Comment by masseelch** [comment] 2021-03-16 09:33
I tried my best, but wasn't able to create one. I have to dig in further in the project i noticed this behavior in. Must be something else. If not I will reopen with an example.

**Comment by masseelch** [comment] 2021-03-16 10:39
If you use [this](https://github.com/dpallot/simple-websocket-server) simple websocket-server (echo example) and this flutter example:

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:web_socket_channel/web_socket_channel.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home:  MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final Timer _timer;
  late final WebSocketChannel _channel;
  late final Stream<String> _stream;

  @override
  void initState() {
    super.initState();

    _channel = WebSocketChannel.connect(Uri.parse('ws://localhost:8000/'));
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      print('sending <hi> from $hashCode');
      _channel.sink.add("hi");
    });

    _stream = _channel.stream.map((event) {
      print('received $event in $hashCode');
      return "$event";
    });
  }

  @override
  void dispose() {
    _channel.sink.close();
    _timer.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamProvider<String>.value(
        initialData: "",
        value: _stream,
        child: Consumer<String>(
          builder: (context, value, child) {
            return Container();
          },
        ),
      ),
    );
  }
}
```

You can see the server logging every connect attempt by the client. On HoRestart in web there is no close message in the server, but a new connect. If you shutdown the flutter app you see all previously opened connections closed. 

So the `WebSocket` does not close it connection on hot restart, even though it is called in `dispose`. This happens because flutter does not call `dispose` on hot restart, i guess.

**Comment by darshankawar** [comment] 2021-03-16 13:03
@masseelch 


> This happens because flutter does not call `dispose` on hot restart, i guess.

That seems to be correct, and there's an open issue for it, https://github.com/flutter/flutter/issues/10437. Please follow-up there for updates and any questions you may have.
Closing this as duplicate.

**Closed by darshankawar** 2021-03-16 13:03 UTC
Labels: in triage

**Comment by masseelch** [comment] 2021-03-18 10:27
@darshankawar This does not look like it is the same. The linked issue is about whether or not plugins need to know about hot restart. 

This issue is about flutter web not calling `dispose()` on hot restart. It is incredible painful to recompile the app every time there is a change in my app just because i have a stream in the app somewhere.

**Comment by masseelch** [comment] 2021-03-25 15:45
@darshankawar So, should i reopen anoter issue? The linked issue is not the same as this one!

**Comment by darshankawar** [comment] 2021-03-26 06:27
@masseelch 
Sorry for not getting back earlier. I see a similar open issue describing your case, https://github.com/flutter/flutter/issues/69949.  Please follow-up there for updates.

**Comment by masseelch** [comment] 2021-03-26 06:44
Ah yes! That describes what i meant. Thank you!
