### ISSUE TITLE
find.byWidgetPredicate() call results in error if widget does not exist

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#6641] opened 2016-11-02 03:39 UTC
Typical widget non-existence testing pattern that works:

```Dart
expect(find.text('Daily budget'), findsNothing);
```

Trying to use this with WidgetPredicate does not work:

```Dart
expect(find.byWidgetPredicate((Widget widget) =>
     widget is Input && widget.value.text == '588.0'), findsNothing);
```

throws the following:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following NoSuchMethodError was thrown running a test:
NoSuchMethodError: The getter 'text' was called on null.
Receiver: null
Tried calling: text

When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      main.<anonymous closure>.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure> (///build/work/c00df5e9a1c2de2bff80763fc9ce5ac6/google3/runfiles/google3/crm/greentea/mobile/app/test/ui/opportunity/offering_detail_test.dart:154:66)
#3      _WidgetPredicateFinder.matches (package:flutter_test/src/finders.dart:424:21)
#4      WhereIterator.moveNext (dart:_internal/iterable.dart:443)
#5      CachingIterable._fillNext (package:flutter/src/foundation/basic_types.dart:215:27)
#6      CachingIterable._precacheEntireList (package:flutter/src/foundation/basic_types.dart:211:12)
#7      CachingIterable.toList (package:flutter/src/foundation/basic_types.dart:206:5)
#8      Finder.toString (package:flutter_test/src/finders.dart:246:46)
#9      prettyPrint._prettyPrint (package:matcher/src/pretty_print.dart:86:26)
#10     prettyPrint (package:matcher/src/pretty_print.dart:108:22)
#11     StringDescription.addDescriptionOf (package:matcher/src/description.dart:44:11)
#12     _defaultFailFormatter (package:test/src/frontend/expect.dart:95:33)
#13     expect (package:test/src/frontend/expect.dart:83:17)
#14     expect (package:flutter_test/src/widget_tester.dart:126:3)
#15     main.<anonymous closure>.<anonymous closure>.<<anonymous closure>_async_body> 
```

**Comment by eseidelGoogle** [comment] 2016-11-02 03:41
@Hixie or @yjbanov know about this code.

**Comment by Hixie** [comment] 2016-11-02 17:08
The bug is that the widget's `value` property was null, so when you did `value.text` you were trying to dereference a null.

Replace it with `widget.value?.text == '588.0'` and it should work fine.

**Comment by mehmetf** [comment] 2016-11-03 03:32
Thanks @Hixie. Still getting used to reading these error messages. When I saw:

```main.<anonymous closure>.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>``` I said to myself, "that can't be our code" :-).

**Comment by yjbanov** [comment] 2016-11-14 20:36
Should we use this as a signal that we need to improve stack traces in `package:flutter_test`? For example, we could have `package:stack_trace` wrap `WidgetTesterCallback`:

```dart
import 'package:stack_trace/stack_trace.dart';

void main() {
  try {
    print('>>>>>>>>>> BEFORE <<<<<<<<<<<');
    crazyStack();
  } catch(_, s) {
    print(s);
  }

  try {
    print('\n\n>>>>>>>>>> AFTER <<<<<<<<<<<');
    Chain.capture(() {
      crazyStack();
    });
  } catch(_, s) {
    print(s);
  }
}

void crazyStack() {
  () {
    () {
      () {
        throw 'Error!';
      }();
    }();
  }();
}
```

Output:

```
>>>>>>>>>> BEFORE <<<<<<<<<<<
#0      crazyStack.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///a/very/long/path/to/the/package/that/obscures/important/information/bin/stack.dart:25:9)
#1      crazyStack.<anonymous closure>.<anonymous closure> (file:///a/very/long/path/to/the/package/that/obscures/important/information/bin/stack.dart:26:8)
#2      crazyStack.<anonymous closure> (file:///a/very/long/path/to/the/package/that/obscures/important/information/bin/stack.dart:27:6)
#3      crazyStack (file:///a/very/long/path/to/the/package/that/obscures/important/information/bin/stack.dart:28:4)
#4      main (file:///a/very/long/path/to/the/package/that/obscures/important/information/bin/stack.dart:6:5)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

>>>>>>>>>> AFTER <<<<<<<<<<<
Unhandled exception:
Error!
bin/stack.dart 25:9                        crazyStack.<fn>.<fn>.<fn>
bin/stack.dart 26:8                        crazyStack.<fn>.<fn>
bin/stack.dart 27:6                        crazyStack.<fn>
bin/stack.dart 28:4                        crazyStack
bin/stack.dart 14:7                        main.<fn>
package:stack_trace/src/chain.dart 86:24   Chain.capture.<fn>
dart:async/zone.dart 1150                  _rootRun
dart:async/zone.dart 1026                  _CustomZone.run
dart:async/zone.dart 1503                  runZoned
package:stack_trace/src/chain.dart 84:12   Chain.capture
bin/stack.dart 13:11                       main
dart:isolate-patch/isolate_patch.dart 261  _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 148  _RawReceivePortImpl._handleMessage
```

Reopening so we could decide what to do about it. I think we'll want a new issue.

**Comment by Hixie** [comment] 2016-11-14 21:15
The BEFORE stack is way better IMHO. It contains the actual path to the file, which is the most critical information. The AFTER stack is confusing for various reasons, e.g. it doesn't include the full paths so IDEs can't make use of the stack, and it puts the files first instead of the symbols first.

However, I'm all for making it clearer. See also https://github.com/flutter/flutter/issues/4021 which I really want to do one day. Once we have that we can prettify all the stacks we catch.

**Comment by Hixie** [comment] 2016-11-14 21:17
(For example, we could replace "crazyStack.<anonymous closure>.<anonymous closure>.<anonymous closure>" with "crazyStack (nested closures)" or something.)

**Comment by yjbanov** [comment] 2016-11-14 22:35
For IDEs it should be sufficient to know the package and the path relative to the package. Barback used to have a formatting for asset paths (including Dart files) that I really liked, e.g.:

```
flutter_tools|lib/src/commands/drive.dart
^             ^
|             |
package name  |
              path relative to package
```

It's short and contains enough information for a tool to find the location (it's as much information as a `package:` import, which IDEs already know how to deal with).

**Comment by Hixie** [comment] 2016-11-14 22:42
Depends on your IDE. For example for Emacs the basic approach for compile-mode is regexp pattern matching on the path.

**Comment by yjbanov** [comment] 2016-11-14 23:05
The trend in modern IDE design is to rely on the underlying language server. In Dart's case, if the analysis server is taught to understand the stack frame format then all IDEs would understand it too. Emacs shouldn't be an exception.

**Comment by Hixie** [comment] 2016-11-14 23:22
Parsing a stack trace shouldn't require a language server. That's absurd. You should be able to just grab the stdout of a random script that runs programs from multiple different languages, and it should be able to get you useful jump-to-line results for any frames in the output.

Which you can today (without stack_trace). I can have a shell script that dumps stacks from Perl, ObjectPascal, Java, and Dart and all of them work fine without needing any language-specific knowledge.

**Comment by yjbanov** [comment] 2016-11-14 23:53
I'm not against having an option to print the full paths for the rare IDE-averse users, but having a concise noise-free stack trace should be an option for that vast majority of users who use IDEs. And, because the vast majority of users do use IDEs and language services, that should be the _default_ option IMHO.

An additional benefit of concise stack trace is that it is easy to copy and paste it into a bug report. Without one's local file system layout noise, the stack trace will be _identical_ to the one reproduced by whoever is assigned to fix it.

**Comment by Hixie** [comment] 2016-11-15 00:01
I'm all for making the stacks prettier. stack_trace's output isn't pretty, and it regresses what I consider an important use case. (The fact that we have any output that uses it is a constant source of pain for me.)

We already have code that does stack trace manipulation (for example some of our messages literally parse the stack to tell you the exact line number where your bug is). My plan is to factor that code out so that it's not duplicated all over the place, and use it to make the stacks even more useful than they are now. Issue #4021 is where I'm tracking that work.

**Comment by Hixie** [comment] 2016-11-15 00:05
(Incidentally, I would caution against minimising or trivialising the needs of some of our customers. "rare IDE-averse users" sounds pejorative. We should respect all our users. Every user has some feature for which they are a minority user. We make a good product by having a solid offering that reaches far into the long tail and meets all our users where they are, instead of only meeting the needs of the "average" user.)

**Comment by yjbanov** [comment] 2016-11-15 00:57
> I would caution against minimising or trivialising the needs of some of our customers. "rare IDE-averse users" sounds pejorative.

Not intended. That's why I'm not a PM. My point is, if our goal is to provide the best possible IDE experience, which seems like the path we've chosen, then we should optimize for IDE usage, including the stack traces. Of course, I'd be sad if plain text experience is bad. You don't always have an IDE at your disposal.

**Comment by Hixie** [comment] 2017-02-27 21:45
Closing in favour of #4021.

**Closed by Hixie** 2017-02-27 21:45 UTC
Labels: customer: leafy, dev: tests
