### ISSUE TITLE
Unhandled exception when calling RenderRepaintBoundary.toImage()

### ISSUE THREAD

**Issue by netsmertia** [flutter/flutter#25128] opened 2018-12-09 06:12 UTC
Getting unhandled exception while saving the widget as png.

Here is little setup from the [medium post](https://medium.com/flutter-community/export-your-widget-to-image-with-flutter-dc7ecfa6bafb) and changed a little to avoid debugNeedsPaint as in [22308](https://github.com/flutter/flutter/issues/22308). 
 
```dart
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GlobalKey _globalKey = new GlobalKey();

  Future<Uint8List> _capturePng() async {
      print('inside');
      RenderRepaintBoundary boundary =
          _globalKey.currentContext.findRenderObject();
      ui.Image image = await boundary.toImage(pixelRatio: 3.0);
      ByteData byteData =
          await image.toByteData(format: ui.ImageByteFormat.png);
      Uint8List pngBytes = byteData.buffer.asUint8List();
      String bs64 = base64Encode(pngBytes);
      print(pngBytes);
      print(bs64);
      setState(() {});
      return pngBytes;
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Widget To Image demo'),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RepaintBoundary(
              key: _globalKey,
              child: Card(
                child: ConstrainedBox(
                  constraints: BoxConstraints(minHeight: 80.0 ),
                  child: Center(
                    child: new Text(
                      'click below given button to capture iamge',
                    ),
                  ),
                ),
              ),
            ),
            new RaisedButton(
              child: Text('capture Image'),
              onPressed: _capturePng,
            ),
          ],
        ),
      ),
    );
  }
}
```
Exception
```
I/flutter ( 2152): inside
E/flutter ( 2152): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 2152): Exception: operation failed
E/flutter ( 2152): #0      OffsetLayer.toImage (package:flutter/src/rendering/layer.dart:798:14)
E/flutter ( 2152): <asynchronous suspension>
E/flutter ( 2152): #1      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:2621:18)
E/flutter ( 2152): #2      _MyHomePageState._capturePng (package:toimage/main.dart:36:39)
E/flutter ( 2152): <asynchronous suspension>
E/flutter ( 2152): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 2152): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 2152): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 2152): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 2152): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter ( 2152): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter ( 2152): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 2152): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 2152): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter ( 2152): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter ( 2152): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter ( 2152): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 2152): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 2152): #16     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 2152): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
Application finished.
```

Flutter Doctor 
```
netss-MBP:FlutterApps nets$ flutter doctor -v
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.0.0 at /Volumes/SSD/Development/flutter
    • Framework revision 5391447fae (9 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Volumes/SSD/Android/sdk
    • Android NDK at /Volumes/SSD/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Volumes/SSD/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • Custom Phone, 8 0, API 26, 768x1280 • 192.168.56.101:5555 • android-x86 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
```
It worked earlier  when I tested it on my office computer first time. Now I am getting exception in my actual project. It may related to my setup only.

**Comment by jason-simmons** [comment] 2018-12-12 02:02
I was able to reproduce this on a Nexus 7 running in landscape mode.  The call to `SkSurface::MakeRenderTarget` in `Rasterizer::MakeRasterSnapshot` fails because it is trying to allocate a 2885x264 sized texture.

The texture is so large because the example app is calling `boundary.toImage` with a `pixelRatio` of 3.0.

Does the pixel ratio need to be so big for this application?  Reducing the `pixelRatio` should allow the output texture size to fit within the resources of the target device.

**Comment by netsmertia** [comment] 2018-12-12 05:07
I am trying this on emulator with bellow configuration 
![screenshot 2018-12-12 at 10 33 25 am](https://user-images.githubusercontent.com/4003316/49848157-c47cd700-fdf9-11e8-9177-b5e5352d82c0.png)

I got the same exception irrespective of `pixelRation` value. I have tried with 1 and 0.2.

**Comment by netsmertia** [comment] 2018-12-14 10:17
Here is the `flutter doctor` summery of my office computer where `RenderRepaintBoundary.toImage()` is working fine (channel beta, v0.11.3)
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17763.134], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.29.1)
[√] Connected device (1 available)

• No issues found!
PS D:\dev\F\one\one> flutter doctor -v
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17763.134], locale en-US)
    • Flutter version 0.11.3 at C:\flutter
    • Framework revision 72bf075e8d (5 weeks ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\nets\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.29.1)
    • VS Code at C:\Users\nets\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.0

[√] Connected device (1 available)
    • Custom Phone, 8 0, API 26, 768x1280 • 192.168.3.101:5555 • android-x86 • Android 8.0.0 (API 26)

• No issues found!
```
console output
```
I/flutter ( 2096): [137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 3, 192, 0, 0, 1, 8, 8, 6, 0, 0, 0, 144, 242, 157, 107, 0, 0, 0, 4, 115, 66, 73, 84, 8, 8, 8, 8, 124, 8, 100, 136, 0, 0, 32, 0, 73, 68, 65, 84, 120, 156, 237, 221, 125, 124, 205, 245, 227, 255, 241, 231, 108, 51, 132, 141, 207, 106, 104, 198, 36, 226, 131, 40, 215, 22, 154, 33, 148, 16, 209, 149, 15, 41, 21, 34, 34, 149, 190, 74, 181, 46, 144, 228, 42, 164, 176, 62, 46, 162, 11, 159, 20, 159, 202, 85, 46, 70, 76, 11, 69, 177, 143, 25, 53, 77, 46, 198, 98, 134, 57, 191, 63, 214, 222, 191, 243, 62, 103, 103, 59, 103, 59, 187, 234, 253, 184, 223, 110, 110, 246, 62, 23, 239, 243, 58, 231, 253, 62, 239, 243, 126, 190, 95, 87, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 191, 1, 159, 82, 186, 110, 0, 0, 0, 0, 192, 223, 151, 173, 48, 86, 234, 213, 144, 122, 252, 248, 241, 134, 149, 43, 87, 238, 23, 16, 16,
I/flutter ( 2096): iVBORw0KGgoAAAANSUhEUgAAA8AAAAEICAYAAACQ8p1rAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzt3X18zfXj//HnbDOEjc9qaMYk4oMo1xaaIZQQ0ZUPKRUiIpW+SrUukOQqpLA+LqILnxSfylUuRkwLRbGPGTVNLsZihjm/P9bev/M+Z2c7Zzu76v24325u9j4X7/M65/0+7/N+vl9XEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC/AZ9Sum4AAAAAwN+XrTBW6tWQevz48YaVK1fuFxAQ0L5MmTINfXx8rpXk683XAAAAAAD8bWXabLY/rl69uj8jI2PzuXPnVlavXn2/t1bulQB8/Pjxhv/4xz8m+vv79/fG+gAAAAAAkKTLly9/dOrUqZe9EYQLHIDT0tKGVaxYcYao6QUAAAAAFI7MP//8c2SlSpXmFGQlZQry5PPnz79YsWLF2SL8AgAAAAAKj2/FihVnnz9//sWCrCTfNcB/1fzOLsiLAwAAAADgiT///HN4fmuC8xWAk5KS/hkWFrZH1PwCAAAAAIpW5tGjR2+uVavWT54+MT9NoH1CQkJeFOEXAAAAAFD0fP/KpB5X6HocgPft29c4ICCgn6fPAwAAAADAGwICAvrt27evsafP8zQAlwkJCWGqIwAAAABAsform3qUaT0NwH4VK1a8zcPnAAAAAADgVX9lUz9PnuNJAC4jqay/v/9NHpUKAAAAAAAv+yublpUHudbjAOzr6/sPTwsGAAAAAIA3/ZVNCzUA+/v4+ORn5GgAAAAAALzmr2zqr0IIwD5/Pdaj9tUAAAAAABQiP2VlVbemRPKkNtdHzP0LAAAAACg5fOXBfMA0ZwYAAAAAWAIBGAAAAABgCQRgAAAAAIAlEIABAAAAAJZAAAYAAAAAWAIBGAAAAABgCQRgAAAAAIAlEIABAAAAAJZAAAYAAAAAWAIBGAAAAABgCQR
```

**Comment by netsmertia** [comment] 2018-12-15 16:08
Update:
The above code is only failing to the emulator, on the real device It worked but the same is also working on emulator on office computer.

**Comment by mtcliatt** [comment] 2019-10-07 19:17
Could the tag, `customer: octopod`, please be added?

**Comment by originlan** [comment] 2019-10-19 07:52
How fix

**Comment by DLErice** [comment] 2019-10-19 07:53
waiting for fix, In a hurry

**Comment by markusaksli-nc** [comment] 2020-12-02 09:02
I can't reproduce this with the example above on the latest master `1.24.0-8.0.pre.406`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.406, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.406 at C:\Development\flutter_master
    • Framework revision 60bdcf55fe (3 hours ago), 2020-12-01 21:24:21 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```
</details>

@netsmertia @mtcliatt Is this still a relevant issue?

**Comment by pedromassangocode** [comment] 2020-12-23 09:21
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:21 UTC
Labels: P4, customer: octopod, engine, severe: crash, waiting for customer response
