### ISSUE TITLE
The new blur is causing text (and images) to flicker

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#140193] opened 2023-12-15 01:54 UTC
### Steps to reproduce

@bdero 
@gaaclarke 

This bug is being re-posted after request(https://github.com/flutter/engine/pull/48472#issuecomment-1857097635, https://github.com/flutter/engine/pull/48472#issuecomment-1857109418)

```
Flutter 3.18.0-11.0.pre.55 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0b6da5b450 (3 hours ago) • 2023-12-14 18:16:50 -0500
Engine • revision 0b0fab8215
Tools • Dart 3.3.0 (build 3.3.0-220.0.dev) • DevTools 2.30.0
```

### Problem:
Text that is being blurred now flickers **_during a scroll._**   If the text is held still under the blur there is no flicker, however when scrolling, then a flickering of the text occurs.  The problem seems to get worse when a finger is lifted and the scroll slows down with friction scrolling.

In my case, this is happening when using a scrollable `Listview` that contains black text on a white background.   Overlaying the listview is a blurred `Container` created using a `BackdropFilter`.

The listview and the container live together in a `Stack` widget

Here's a video showing the problem from the simulator.  The problem is a bit more apparent on a real device, but for sure its there on the simulator

**EDIT/UPDATE:  Images also flicker**

https://github.com/flutter/flutter/assets/87546778/a0e0705e-01b0-49c9-ab8c-5ae9556b6908

### Problem source:
The problem starting occurring with the launch of the `new blur` https://github.com/flutter/engine/pull/48472 (or possibly https://github.com/flutter/engine/pull/49038).  Both those updates are in commit `0b6da5b45088bb1d8a9b1d1e89f3b7d1437390c4` which is where the problem has started.  It looks like that commit will be reverted soon, so lets enjoy the problem while it lasts

### Expected results

No flickering of text

### Actual results

Flicker of text

### Code sample

<details open><summary>Code sample</summary>

```dart
My code is quite large and will be difficult to put here, but conceptually it is a container with a backdrop filter sitting in a stack on top of a lsitview 
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2023-12-15 09:51
Hi @mark8044 
I'm checking this on the same master channel version with below sample code but can't seem to see the issue.

<details>
<summary>Sample code</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Stack(
          children: [
            ListView.builder(
              itemCount: 100,
              itemBuilder: (context, index) {
                if (index % 2 == 0) return const Divider();
                return ListTile(
                  title: Container(
                    margin: const EdgeInsets.symmetric(vertical: 8),
                    padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 8),
                    child: Text('Hello $index'),
                  ),
                  leading: const Icon(Icons.ac_unit),
                );
              },
            ),
            ClipRect(
              child: BackdropFilter(
                filter: ImageFilter.blur(
                  sigmaX: 5.0,
                  sigmaY: 5.0,
                ),
                child: Container(
                  alignment: Alignment.center,
                  height: 400.0,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>


<details>
<summary>Demo video (iPhone 7, iOS 15.8)</summary>

https://github.com/flutter/flutter/assets/104349824/ee409767-001a-4f15-a1c9-54f676c3850c

</details>

Could you also try this sample code on your end and confirm? If the sample needs to be updated, please help to do.

**Comment by mark8044** [comment] 2023-12-15 15:03
> Hi @mark8044 I'm checking this on the same master channel version with below sample code but can't seem to see the issue.
> 
> Sample code
> Demo video (iPhone 7, iOS 15.8)
> Could you also try this sample code on your end and confirm? If the sample needs to be updated, please help to do.

Your sample doesn't do it because your SigmaX and SigmaY are too low.  If you put it up to say 20 for example, you will see the problem.

Here is an example where I set it to 40

https://github.com/flutter/flutter/assets/87546778/f5bcd800-4df3-4db9-816e-0ce058212f60

**Comment by gaaclarke** [comment] 2023-12-15 16:36
I think this is related to subpixel alignment in the downsampled image.  Once the pixels get bigger, the subpixel math becomes more prominent.  It's going to be tricky to fix.  Thanks for reporting.

**Comment by mark8044** [comment] 2023-12-15 17:24
> I think this is related to subpixel alignment in the downsampled image. Once the pixels get bigger, the subpixel math becomes more prominent. It's going to be tricky to fix. Thanks for reporting.

@gaaclarke 
Incase its meaningful:  Blurring as it stood, just before yesterdays commit was absolutely perfect to my eyes at least.  Very smooth, lag free and platform native appearing.  And very performant (on my devices: iPhone X, iPhone 13, iPhone 14 pro, S21 Samsung).  

I know there have been other improvements to backdrop filter blur in the past few weeks and they were all really good too.

Hope this extra information has some significance

**Comment by danagbemava-nc** [comment] 2023-12-18 04:54
Hi @mark8044, which of the sigma values did you set to 40? When I set both to 40, the blur is barely visible and if I set it to 20 (for both), I do not see the issue on my iPhone XS. I tested on the latest master. Please see the recordings below

<details>
<summary>recordings</summary>

| 20 | 40 | 
| -- | -- |
| <video src="https://github.com/flutter/flutter/assets/88313112/1e7182fe-8bb2-4377-ab95-dd2b7569535d" /> | <video src="https://github.com/flutter/flutter/assets/88313112/64fc697b-69c6-412d-94c4-262d17139b83" /> |
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.18.0-11.0.pre.96, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-11.0.pre.96 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32d42b63de (16 hours ago), 2023-12-17 07:39:25 -0500
    • Engine revision 626c93260f
    • Dart version 3.3.0 (build 3.3.0-238.0.dev)
    • DevTools version 2.31.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2 21C62
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by gaaclarke** [comment] 2023-12-18 17:05
@danagbemava-nc the new blur is off by default now.  There were some benchmarks that were experiencing memory problems after it landed.  This bug is still relevant.

**Comment by bdero** [comment] 2023-12-20 11:40
I was able to reproduce this with `AiksTest.GaussianBlurFilter`. Video showing the new blur vs the old blur:

https://github.com/flutter/flutter/assets/919017/d6c3223c-638c-4f72-8a1c-62196f62e10c

I took a frame capture and the cause appears to be overwhelming information loss during the downsampling pass, not subpixel alignment.

Original image:
![boston](https://github.com/flutter/flutter/assets/919017/90e51fc9-70da-46ef-a4f9-3fa7f6de1cd1)

Downsampled image in the new blur:
![Screenshot 2023-12-20 at 2 39 21 AM](https://github.com/flutter/flutter/assets/919017/42b9b4f6-8a09-41c3-92f5-478b744d9e0b)

This is happening because the downsample pass is bilinear sampling from the base mip level (mipmap blits only occur for ui.Images automatically, they don't occur automatically for backdrop textures nor this photo of Boston present in the interactive playground. The bilinear sampler will only read from immediately adjacent texels and weight their colors -- it won't weight the 10s or 100s of nearby texels that should be contributing to each result texel when scaling down by such large percentages.

The old blur has minor banding artifacts (most likely due to a subpixel alignment problem), but doesn't suffer from this kind of information loss because it integrates samples along the original image extents (which is what makes it so slow).

The downscaling pass needs to produce a result that reasonably approximates the original image and doesn't skip over any texels from the original image:
![Screenshot 2023-12-20 at 2 45 57 AM](https://github.com/flutter/flutter/assets/919017/f712d93e-633f-4115-8231-0d070ce287bd)
(properly scaled down image with bilinear filter made in Photoshop)

To fix this, we'll need to either:
1. Sample from more texels in the downsample shader and average them together (very expensive).
2. Do a blit pass and generate the closest mip level for the snapshot output texture and linear sample from that (less expensive and we don't need to do this for ui.Images since we already generate full mipmaps for them; we just need to do it for backdrop filters and subpass textures).

There are two missing features we'd need to do this efficiently:
1. In the blit pass, we only support computing _all_ mip levels at once, but we should also allow generating a set of given mip levels. All backends can support this.
2. We need to track which mip levels have been generated, as well as a way to "invalidate" mip levels for reused textures from the pool.

**Comment by bdero** [comment] 2023-12-20 12:12
Visuals of sampling behavior from [this article](https://bgolus.medium.com/sharper-mipmapping-using-shader-based-supersampling-ed7aadb47bec).

This is how backdrop filters and subpass textures are rendering in the new blur's first pass. We're bilinear filtering with only the base mip level. So once we shrink down past half size, entire rows and columns of texels from the source image begin getting entirely dropped from contributing to the output:
![image](https://miro.medium.com/v2/resize:fit:640/format:webp/1*uZXjZ_9bYO-blnI6S-gmsQ.gif)

And this is what happens for ui.Images, which have full mipmaps already. Still some jumping (which can be alleviated further by trilinear filtering), but we get a much better approximation:
![image](https://miro.medium.com/v2/resize:fit:640/format:webp/1*88BbPuG2NSyfOlFdjWICYg.gif)

**Comment by gaaclarke** [comment] 2023-12-20 17:14
Thanks @bdero that description of the problem tracks with my poorly articulated intuition.  I had hoped we could potentially get good enough with less aggressive downsampling.  The problem with all of these solutions is that they all require some sort of overhead.  I haven't measured the latest optimization but I want to make sure we are clearly below status quo before attempting these.

**Comment by jonahwilliams** [comment] 2024-01-08 19:19
I think this issue is covered by the bugs that have already been filled but there is a lot of good info here so I will leave it open.

**Comment by jonahwilliams** [comment] 2024-01-22 22:59
We think this is fixed now. CLosing.

**Closed by jonahwilliams** 2024-01-22 22:59 UTC
Labels: engine, c: rendering, P2, e: impeller, team-engine, triaged-engine
