### ISSUE TITLE
image_picker Bitmap NullPointException on Android 10 with open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by mofada** [flutter/flutter#41459] opened 2019-09-27 09:23 UTC
When I made a picture selection on Xiaomi Mi 9, I got an error. I debugged it and found that getting the bitmap failed. I got it on another phone Pixel 3 XL.

BitmapFactory show message : EACCES (Permission denied)

However, the display details have been granted in the app details interface.

![debug](https://user-images.githubusercontent.com/22286246/65757398-9dee1980-e149-11e9-8596-457d91ae40d8.png)

![bitmapFactory](https://user-images.githubusercontent.com/22286246/65758106-0be71080-e14b-11e9-8d8a-5def75539e8c.png)

![screen](https://user-images.githubusercontent.com/22286246/65758155-24efc180-e14b-11e9-8857-91dc90ec2144.png)

## Logs
```
W/99.bole_studen: Got a deoptimization request on un-deoptimizable method java.io.FileDescriptor libcore.io.Linux.open(java.lang.String, int, int)
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Screenshots/Screenshot_2019-09-26-18-58-07-298_com.tencent.mobileqq.jpg: open failed: EACCES (Permission denied)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:115)
W/System.err:     at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:515)
W/System.err:     at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:542)
W/System.err:     at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:51)
W/System.err:     at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:40)
W/System.err:     at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:530)
W/System.err:     at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
W/System.err:     at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
W/System.err:     at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
W/System.err:     at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
W/System.err:     at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
        at android.app.Activity.dispatchActivityResult(Activity.java:8250)
W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4898)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4946)
W/System.err:     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:221)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7419)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:482)
    	... 25 more

```

## flutter doctor -v
```
C:\Users\fada>flutter doctor -v
[√] Flutter (Channel master, v1.10.7-pre.51, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)
    • Flutter version 1.10.7-pre.51 at D:\flutter
    • Framework revision 957d839775 (3 hours ago), 2019-09-26 22:45:21 -0700
    • Engine revision a206557f8f
    • Dart version 2.6.0 (build 2.6.0-dev.3.0 327bc451f8)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\Android\android-studio canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.5)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\Community
    • Visual Studio Community 2019 version 16.2.29306.81

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Android Studio (version 3.6)
    • Android Studio at D:\Android\android-studio canary
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 192.6262.58
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] Connected device (2 available)
    • MI 9    • c3bd46f9 • android-arm64 • Android 10 (API 29)
    • Windows • Windows  • windows-x64   • Microsoft Windows [Version 10.0.18362.356]

! Doctor found issues in 1 category.
```

**Comment by mofada** [comment] 2019-09-27 09:24
## Supplementary log
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dct99.bole_student, PID: 16255
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:339675 flg=0x1 }} to activity {com.dct99.bole_student/com.dct99.bole_student.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4905)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4946)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:221)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:52)
        at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:40)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:530)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
        at android.app.Activity.dispatchActivityResult(Activity.java:8250)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4898)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4946) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:221) 
        at android.app.ActivityThread.main(ActivityThread.java:7520) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```

**Comment by mofada** [comment] 2019-09-27 09:35
[proposed Label] image_picker

**Comment by escamoteur** [comment] 2019-09-27 13:07
Did you add the necessary permissions in your android project?

**Comment by mofada** [comment] 2019-09-27 13:16
No, I didn't add it, image_picker implements the permission request internally.

![image](https://user-images.githubusercontent.com/22286246/65771989-edddd800-e16b-11e9-9615-edfcf4ed7a18.png)

**Comment by escamoteur** [comment] 2019-09-27 13:27
Does the exception happen when you tap on an image or even before?
Is the path really the correct one?

**Comment by escamoteur** [comment] 2019-09-27 13:30
Not sure if I understand it correctly does it Work on the Pixel or doesn't it work on any phone?
Which version of the image_picker are you using?

**Comment by mofada** [comment] 2019-09-27 13:30
There is only an exception here, I think it may be because of the system, because the miui of the xiaomi released a new version these two days.
The path is correct, the file exists normally

**Comment by mofada** [comment] 2019-09-27 13:30
`image_picker: ^0.6.1+4`

**Comment by mofada** [comment] 2019-09-27 13:31
I am normal on the lower version of xiaomi's miui system, I am confused.

**Comment by escamoteur** [comment] 2019-09-27 13:44
It does work on the Google Pixel?

**Comment by mofada** [comment] 2019-09-27 14:23
Yes, my phone is google pixel 3 xl, it works fine

**Comment by escamoteur** [comment] 2019-09-27 15:38
Which Android version runs on the Xiomi?

**Comment by mofada** [comment] 2019-09-27 16:20
Android 10 and MIUI system 11

**Comment by mofada** [comment] 2019-09-28 09:03
Now I can't choose on my pixel 3 xl.

**Comment by mofada** [comment] 2019-09-28 09:07
## Pixel 3 XL
```
E/BitmapFactory(27576): Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/tencent/QQ_Images/0.jpg: open failed: EACCES (Permission denied)
D/AndroidRuntime(27576): Shutting down VM
E/AndroidRuntime(27576): FATAL EXCEPTION: main
E/AndroidRuntime(27576): Process: com.dct99.bole_student, PID: 27576
E/AndroidRuntime(27576): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:176513 flg=0x1 }} to activity {com.dct99.bole_student/com.dct99.bole_student.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(27576): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime(27576): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime(27576): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(27576): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(27576): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(27576): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(27576): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(27576): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(27576): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(27576): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27576): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(27576): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(27576): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(27576): 	at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:53)
E/AndroidRuntime(27576): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:41)
E/AndroidRuntime(27576): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:530)
E/AndroidRuntime(27576): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
E/AndroidRuntime(27576): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
E/AndroidRuntime(27576): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(27576): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(27576): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(27576): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime(27576): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime(27576): 	... 11 more
I/Process (27576): Sending signal. PID: 27576 SIG: 9
Lost connection to device.
```

**Comment by mofada** [comment] 2019-09-28 09:16
```
[ro.product.board]: [crosshatch]
[ro.product.brand]: [google]
[ro.product.build.date]: [Wed Sep 11 22:36:39 UTC 2019]
[ro.product.build.date.utc]: [1568241399]
[ro.product.build.fingerprint]: [google/crosshatch/crosshatch:10/QP1A.190711.020.C3/5869620:user/release-keys]
[ro.product.build.id]: [QP1A.190711.020.C3]
[ro.product.build.tags]: [release-keys]
[ro.product.build.version.release]: [10]
[ro.product.build.version.sdk]: [29]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [crosshatch]
[ro.product.first_api_level]: [28]
[ro.product.locale]: [en-US]
[ro.product.model]: [Pixel 3 XL]
[ro.product.name]: [crosshatch]
```

**Comment by escamoteur** [comment] 2019-09-28 09:23
Have you tried on another phone?

**Comment by escamoteur** [comment] 2019-09-28 09:24
That is really strange. Before you could select on the Pixel?

**Comment by mofada** [comment] 2019-09-28 09:29
![image](https://user-images.githubusercontent.com/22286246/65814532-88462600-e215-11e9-8b7b-c1540c2824b8.png)

**Comment by mofada** [comment] 2019-09-28 09:29
I am pretty sure that the file exists.

**Comment by mofada** [comment] 2019-09-28 09:30
I tried another xiaomi, Android version 7.1.1. He is normal. I am surprised that it was OK yesterday. I will not be able to uninstall and reinstall today.

**Comment by escamoteur** [comment] 2019-09-28 09:36
I think you use it the wrong way. pickImage returns a File you have to use this File to load the image because Android makes a copy for you that is later removed.

**Comment by mofada** [comment] 2019-09-28 09:50
The problem now is that I have crashed without getting the image program.

**Comment by escamoteur** [comment] 2019-09-28 09:56
Did you get another error?

**Comment by mofada** [comment] 2019-09-28 10:19
On this issue, the file crashes when it is selected. The reason is open failed: EACCES (Permission denied), but it is normal on the xiaomi phone that also requires the runtime permissions of 7.1.1, which is not normal on xiaomi 9 android 10. But yesterday I was normal on the pixel 3 xl of android 10, but today it is not working.

**Comment by mofada** [comment] 2019-09-28 10:22
Then it will cause a NullPointerException here

![image](https://user-images.githubusercontent.com/22286246/65815060-dad71080-e21c-11e9-970e-3da17f3a334d.png)

**Comment by escamoteur** [comment] 2019-09-28 10:30
You are still not using the File that you get returned from pickImage. Please try this.

**Comment by mofada** [comment] 2019-09-28 10:36
No, no, I have not received the document and I am getting an error.

**Comment by mofada** [comment] 2019-09-28 10:37
I am getting an error when I run here.

![image](https://user-images.githubusercontent.com/22286246/65815208-03600a00-e21f-11e9-9ed2-cee939ea652a.png)

**Comment by escamoteur** [comment] 2019-09-28 11:00
Which document are you talking about?
I meant instead of using decodeFile you should use the File that pickImage returns.

**Comment by mofada** [comment] 2019-09-28 11:02
This is not the code I wrote, this is the source code of image_picker

**Comment by escamoteur** [comment] 2019-09-28 11:08
Ah, sorry. This is indeed strange. Could you please paste your code in here?

**Comment by mofada** [comment] 2019-09-28 11:11
My code is very simple, that is, to select the image, the latter is not executed.

I found a strange problem, I recorded a video, but github does not support video, I am trying to convert a gif file, please wait a moment.

```
 var file = await ImagePicker.pickImage(source: source, imageQuality: 75);
```

**Comment by mofada** [comment] 2019-09-28 11:44
First look at the error situation

![error](https://user-images.githubusercontent.com/22286246/65815940-44105100-e228-11e9-8cb8-ab4f105810b4.gif)

**Comment by mofada** [comment] 2019-09-28 11:45
Then this is the time of success. When it is successful, it is the incoming album and then the selection. When it fails, it is directly selected in the file interface.

![on success](https://user-images.githubusercontent.com/22286246/65815950-60ac8900-e228-11e9-80e1-81ce90b0d660.gif)

**Comment by masewo** [comment] 2019-09-28 12:15
I have the same error over here on a Pixel 3 emulator with Android 10.
After picking an image from gallery with plugin image_picker 0.6.1+4 and flutter  on master channel, I get following error:
`Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/IMG_20190928_115132.jpg: open failed: EACCES (Permission denied)`
I call image_picker like this:
```
var image = await ImagePicker.pickImage(
        source: source, maxWidth: 1280, maxHeight: 1280);
```

**Comment by escamoteur** [comment] 2019-09-28 12:16
You mean when it fails it doesn't even show the image folders content?

How did you get the success recorded did you try on another phone? 
You have inialized the source parameter, right.

**Comment by mofada** [comment] 2019-09-28 12:20
I mean, when I choose a picture, if I don't go to the album in the upper left corner to choose, it will flash back. If I enter the album to choose it is normal, I am also very strange.

**Comment by mofada** [comment] 2019-09-28 12:20
`source` value is `ImageSource.gallery`

**Comment by mofada** [comment] 2019-09-28 12:22
@masewo  The mistakes of both of us are the same

**Comment by escamoteur** [comment] 2019-09-28 12:23
Possibly a Android 10 related problem.

**Comment by masewo** [comment] 2019-09-28 12:28
@escamoteur Yes it is. It works on my Pixel 3 emulator with Android 9.0 just fine.

**Comment by escamoteur** [comment] 2019-09-28 12:40
OK thanks, I'll pass it on now we have a good understanding what's happening.

**Comment by mofada** [comment] 2019-09-29 01:10
@escamoteur   I think the title should be modified "image_picker Bitmap NullPointException on Android 10 with open failed: EACCES (Permission denied)"

**Comment by escamoteur** [comment] 2019-09-29 09:30
Yeah, completely agree

**Comment by masewo** [comment] 2019-09-29 13:40
As a short-term workaround you can use this in your AndroidManifest.xml:
`android:requestLegacyExternalStorage="true"`
See here for more information:
https://developer.android.com/training/data-storage/files/external-scoped#opt-out-of-scoped-storage

**Comment by masewo** [comment] 2019-09-29 17:40
As a dirty hack I forked image_picker plugin and made it work by following change:
https://github.com/masewo/plugins/commit/1910ae887c7c7acbc67ab3495f02bed1de9af510

**Comment by ozzy1873** [comment] 2019-09-29 18:45
This problem is in SDK 29. I downgraded to target SDK version 28 and it works.

**Comment by cailiwu55** [comment] 2019-10-14 02:44
look here [external-scoped](https://developer.android.com/training/data-storage/files/external-scoped)，if your SDK is upgraded to 29, you should do this

> 
<manifest ... >
  
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>

**Comment by aliyazdi75** [comment] 2019-10-23 13:46
And it's more strange that plugin `example`  works fine on Android 10 but in my project just works with `<application android:requestLegacyExternalStorage="true" ... >` on `manifest` file.

**Comment by Knupper** [comment] 2019-10-31 06:44
I have the same problem. It works fine for me when i am using "Google Photos" to select a image, but when i am using the "File" App it crashs after selecting a image. Maybe it helps to find out to find a solution.

With the ` android:requestLegacyExternalStorage="true` it works in both cases.

**Comment by droidluv** [comment] 2019-10-31 18:55
US the compile and target sdk 28 doesn't help and crashes in the Android emulator, I updated both to target sdk 29 and set android:requestLegacyExternalStorage="true" under the application tag, we definitely need better scoped storage support for Android 10, ideally the plugin will have to copy the file to the current apps own directory to return a file.

**Comment by cholojuanito** [comment] 2019-11-01 22:33
https://github.com/flutter/flutter/issues/41459#issuecomment-536329696

This worked for me as well. I have my project running Java for Android and have it setup for AndroidX

**Comment by cyanglaz** [comment] 2019-11-13 18:07
Thanks for reporting the issue and the detailed discussion. I would like to gather a little more information so I can reproduce the issue and try to find the root cause.
1. What are the model of devices that cause the issue in the original post(permission denial issue)? 
2. What is the Android SDK version? (I have seen 29 is the version caused the problem but I want to confirm.)
3. If anyone can provide a reduced test case (An example app with minimum code to reproduce the issue.) that'd be great.

**Comment by cyanglaz** [comment] 2019-11-13 18:32
@Minituff It would be beneficial if we can get a reduced test case to reproduce the issue. The less code the better, it would better help us to ping point the root cause.

**Comment by droidluv** [comment] 2019-11-14 20:07
I'm not trying to be sarcastic, just a quick heads up @cyanglaz this is happening because of scoped storage restrictions which can be skipped through some flags for Android 10 and is mandatory from Android 11, where everything is expected to start working through the storage access framework, where retrieving a File through the legacy approach File (filepath) will throw a security exception unless the file is in the calling apps own directory, we have to adhere to the more sandboxed system, just a simple hello world app with a button to pick an image file from the phone gallery and an attempt to work with the file will give you the problems we are facing, provided you run it in an Android 10 device

**Comment by Minituff** [comment] 2019-11-22 05:47
It looks like this issue has been resolved with the latest image_picker update: https://github.com/flutter/plugins/pull/2293

**Comment by droidluv** [comment] 2019-11-22 09:00
@Minituff are you sure from the description of the PR it seemed like a fix for picking a non-image file, the issue here is related to access restrictions to the file because of scoped storage

**Comment by DevAlpesh** [comment] 2019-11-26 11:29
<application
. . . 
android:requestLegacyExternalStorage="true"/>

This is works for me also. But still I am not sure why this is happen.

**Comment by cyanglaz** [comment] 2019-12-02 21:20
@droidluv I created a simple app and add a button to pick the image. Running the app on a pixel 3a xl with android 10. Setting the compileSdkVersion and targetSdkVersion to 29. Picked an image from gallery and it didn't crash. 
Am I missing something else?

**Comment by epiphanatic** [comment] 2019-12-03 00:21
@cyanglaz I've upgraded to latest version of plugin, both versions 29, Pixel 3 (on two devices) and a couple of other android devices leads to a crash if I do not include android:requestLegacyExternalStorage="true". Note it's not for _all_ files but for only some like "RECENT IMAGES ON PHONE", bitmoji, etc. If instead of choosing a recent photo I, for example, go to "Photos" under "BROWSE FILES IN OTHER APPS" , then choose "Camera" or anything else listed there it will work.

**Comment by cyanglaz** [comment] 2019-12-04 00:54
@epiphanatic I did pick some images under 'recent' and it didn't crash for me.

**Comment by droidluv** [comment] 2019-12-04 06:04
Hey Chris,

I understand that you picked the image but did you try using the File
object? Like doing some sort of read/write action? The security exception
will be thrown when trying to manipulate the file directly.

**Comment by cyanglaz** [comment] 2019-12-04 17:00
@droidluv After the fix in flutter/plugins#2293, picking a file object will result a null. So technically, you shouldn't be able to pick any file other than images(by image, i mean something that can be converted to bitmap).

**Comment by droidluv** [comment] 2019-12-04 18:00
No I don't mean picking a file, I mean picking  an image, the picker will
return a file instance which if you try to read/write throws the security
exception.

Sebi Sheldin Sebastian | Android Developer

**Comment by cyanglaz** [comment] 2019-12-04 20:24
@droidluv  I did try to pick an image which returns a `File`, then display that image in the app. It doesn't crash.

Do you mind providing a code snippet for a reduced test case so I can try it out?

**Comment by joknjokn** [comment] 2019-12-05 15:37
I, and a friend, have this issue as well.
Devices: Xiaomi 9t Pro and OnePlus 7 Pro, both running Android 10

If I choose an image through Google Photos in the left drawer, it works. But if I choose an image through the file manager or the Photos-folder-shortcut in the left drawer, ImagePicker.pickImage returns null without any errors.

Can someone explain an exact fix and where to apply it? Would appreciate that!

I have: 
minSdkVersion 21
targetSdkVersion 29

**Comment by joknjokn** [comment] 2019-12-05 16:03
> @droidluv After the fix in [flutter/plugins#2293](https://github.com/flutter/plugins/pull/2293), picking a file object will result a null. So technically, you shouldn't be able to pick any file other than images(by image, i mean something that can be converted to bitmap).

So, maybe some of the providers in the left side drawer returns images as file objects, resulting in a null?

This is a pretty serious bug.

**Comment by joknjokn** [comment] 2019-12-05 16:15
My temporary solution: 
image_picker: 0.6.1+11

**Comment by cyanglaz** [comment] 2019-12-05 17:12
@joknjokn In my opinion, if a file that is picked is an image, it should always be able to be decoded to a Bitmap. The code is here: https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java#L41-L44

**Comment by joknjokn** [comment] 2019-12-05 17:14
@cyanglaz I guess I agree, but that seems not to be working at the moment.

**Comment by joknjokn** [comment] 2019-12-06 10:43
Update: using "image_picker: 0.6.1+11" worked in debug on my phone, but after publishing and downloading from Play Store, the app just crashes entirely if I select an image from file manager/Photos-shortcut. Google Photos and Drive still work.

**Comment by eduribas** [comment] 2019-12-06 14:28
I have a similar issue using a Galaxy S10+ with Android 10, v0.6.2+1 and targetSdkVersion 29:

- If a pick an image from some of the default folders on the file chooser, like Recents or Images -> Camera, it returns `null`.
- If I pick an image from Google Photos or Google Drive it works.

Adding `android:requestLegacyExternalStorage="true"` solves the problem. But we really need a future proof solution here.

**Comment by joknjokn** [comment] 2019-12-10 11:01
This is the most serious bug in my app and has been for a week. No news about a fix? Are someone working on it? Or should I abandon ship?

**Comment by joknjokn** [comment] 2019-12-10 11:04
> I have a similar issue using a Galaxy S10+ with Android 10, v0.6.2+1 and targetSdkVersion 29:
> 
> * If a pick an image from some of the default folders on the file chooser, like Recents or Images -> Camera, it returns `null`.
> * If I pick an image from Google Photos or Google Drive it works.
> 
> Adding `android:requestLegacyExternalStorage="true"` solves the problem. But we really need a future proof solution here.

Exactly where do you add requestLegacy? I can't make it work.

**Comment by mofada** [comment] 2019-12-10 11:15
@joknjokn  look here
![image](https://user-images.githubusercontent.com/22286246/70524875-15481c80-1b81-11ea-83b2-0521dd3d51e3.png)

![image](https://user-images.githubusercontent.com/22286246/70525027-5f310280-1b81-11ea-9287-d3a8d94d108c.png)

**Comment by alejandrorosas** [comment] 2019-12-27 12:40
Happening the same when selecting a recent image using Pixel 4.

Adding the `requestLegacyExternalStorage` property fixes the issue for now.

**Comment by mockturtl** [comment] 2020-01-22 21:10
> What are the model of devices that cause the issue in the original post(permission denial issue)?
> What is the Android SDK version? (I have seen 29 is the version caused the problem but I want to confirm.)

emulator, Pixel C API 29

**Comment by cyanglaz** [comment] 2020-03-12 18:20
Un-assign myself from this issue as I don't have cycle to actively working on it.

**Comment by 9thwall** [comment] 2020-03-21 01:54
I'm using Pixel3 and @DevAlpesh fix solved the issue.

**Comment by zhaofengnju** [comment] 2020-04-28 02:38
Ping... Is there any progress on this issue?

The workaround here to add requestLegacyExternalStorage doesn't work in Android 11: 
"After you update your app to target Android 11, the system ignores the requestLegacyExternalStorage flag."
https://developer.android.com/preview/privacy/storage

It blocks our targeting to Android 11.
Thanks!

**Comment by cyanglaz** [comment] 2020-05-01 18:10
open a WIP PR to fix this https://github.com/flutter/plugins/pull/2728
Still working on it if anyone wants to try apply the PR, you should see the fix.

**Comment by cyanglaz** [comment] 2020-05-05 03:51
Should be fixed by https://github.com/flutter/plugins/pull/2728 in image_picker 0.6.6+1
I'm going to close the issue, please feel free to tag me on this issue if you still face the same problem after updating image_picker to 0.6.6+1; Or open a new GitHub issue if you found a different issue.

**Closed by cyanglaz** 2020-05-05 03:51 UTC
Labels: a: images, customer: money (g3), customer: quill (g3), e: OS Version specific, p: image_picker, platform-android, plugin, severe: crash, severe: customer blocker, severe: customer critical, severe: regression

**Comment by praharshbhatt** [comment] 2020-05-19 10:42
> @joknjokn look here
> ![image](https://user-images.githubusercontent.com/22286246/70524875-15481c80-1b81-11ea-83b2-0521dd3d51e3.png)
> 
> ![image](https://user-images.githubusercontent.com/22286246/70525027-5f310280-1b81-11ea-9287-d3a8d94d108c.png)

This works perfectly

**Comment by deborahjames** [comment] 2020-06-28 15:45
[WORKED FOR ME]
ERROR :  BitmapFactory: Unable to decode stream: /storage/emulated/filepath.jpg: open failed: EACCES (Permission denied)
SOLUTION : Thanks was able to solve the issue by adding  android:requestLegacyExternalStorage="true"  in AndroidMAnifest.xml file.

_<application    
        android:theme="@style/AppTheme"
        android:requestLegacyExternalStorage="true">_

**Comment by kbrmimbyl** [comment] 2021-03-18 09:21
This thread just saved my life. flutter 1.22.1, image_picker 0.6.3+1

**Comment by IbtsamRana** [comment] 2021-06-15 13:46
Updating the image_picker version solved my issue
