### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by pmg1991** [flutter/flutter#98563] opened 2022-02-16 05:18 UTC
## Command
```
flutter run --machine --start-paused -d chrome --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart -d web-server --web-port 2021
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:44:31)
#1      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:695:16)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1466], locale en-IN)
    • Flutter version 2.10.1 at C:\Users\prakharmohan.garg\apps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (6 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\prakharmohan.garg\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Users\prakharmohan.garg\apps\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Users\prakharmohan.garg\apps\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 98.0.1108.50

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 02c026b03cd31dd3f867e5faeb7e104cce174c5f
### Plugins
flutter_compass-0.7.0
flutter_secure_storage-5.0.2
flutter_secure_storage_linux-1.1.0
flutter_secure_storage_macos-1.1.0
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
geolocator-8.0.3
geolocator_android-3.0.2
geolocator_apple-2.0.1
geolocator_web-2.1.4
http_certificate_pinning-2.0.3
modal_progress_hud_nsn-0.1.0-nullsafety-1
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-8.3.0
sqflite-2.0.2
url_launcher-6.0.18
url_launcher_android-6.0.14
url_launcher_ios-6.0.14
url_launcher_linux-2.0.3
url_launcher_macos-2.0.2
url_launcher_web-2.0.6
url_launcher_windows-2.0.2

**Comment by danagbemava-nc** [comment] 2022-02-16 09:25
Duplicate of #96988

**Closed by danagbemava-nc** 2022-02-16 09:25 UTC
Labels: in triage
