### ISSUE TITLE
[tool_crash] _CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))

### ISSUE THREAD

**Issue by chuviethung** [flutter/flutter#115738] opened 2022-11-21 04:48 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))
```
#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34)
#1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1409:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[!] Flutter (Channel master, 3.6.0-6.0.pre.29, on macOS 13.0.1 22A400 darwin-arm64, locale en-VN)
    • Flutter version 3.6.0-6.0.pre.29 on channel master at /Users/chuviethung/dev/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/chuviethung/dev/flutter. Consider adding /Users/chuviethung/dev/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee9bc784b5 (4 hours ago), 2022-11-20 19:32:24 -0500
    • Engine revision 271461837e
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/chuviethung/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: fb57da5f945d02ef4f98dfd9409a72b7cce74268

**Comment by danagbemava-nc** [comment] 2022-11-21 09:36
Labeling this as I cannot find any existing issues.

**Comment by arcas0803** [comment] 2023-02-02 17:40
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter pub upgrade

## exception

_CastError: type 'Null' is not a subtype of type 'String' in type cast

```
#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:547:40)
#1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#7      PackagesInteractiveGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:357:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale es-ES)
    • Flutter version 3.7.0 on channel stable at /Users/alvaroarcasgarcia/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (10 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/alvaroarcasgarcia/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • M2012K11AG (mobile) • 99d3cf67 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
Just upgrading to 3.7.1 on one project. I upgrade to 3.7 in another project and works fine.

**Comment by TrueNight** [comment] 2023-02-07 15:06
Same issue here

**Comment by krishh-apnaklub** [comment] 2023-02-10 06:25
I have just upgraded the Flutter SDK from v3.3.7 to v3.7.3. I am still getting this error in the latest stable version (v3.7.3).

## Command
```
flutter pub get
```

## Steps to Reproduce
1. Open Terminal
2. Execute `flutter pub get` command.

## Logs
_CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))
```
#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34)
#1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:179:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓] [39m Flutter (Channel stable, 3.7.3, on macOS 13.2 22D49
    darwin-arm64, locale en-IN)
     [32m• [39m Flutter version 3.7.3 on channel stable at /Users/user/tools/flutter-arm64
     [32m• [39m Upstream repository https://github.com/flutter/flutter.git
     [32m• [39m Framework revision 9944297138 (30 hours ago), 2023-02-08 15:46:04 -0800
     [32m• [39m Engine revision 248290d6d5
     [32m• [39m Dart version 2.19.2
     [32m• [39m DevTools version 2.20.1

 [32m[✓] [39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
     [32m• [39m Android SDK at /Users/user/Library/Android/sdk
     [32m• [39m Platform android-33, build-tools 33.0.1
     [32m• [39m ANDROID_HOME = /Users/user/Library/Android/sdk
     [32m• [39m Java binary at: /Users/user/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
     [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
     [32m• [39m All Android licenses accepted.

 [32m[✓] [39m Xcode - develop for iOS and macOS (Xcode 14.2)
     [32m• [39m Xcode at /Applications/Xcode.app/Contents/Developer
     [32m• [39m Build 14C18
     [32m• [39m CocoaPods version 1.11.3

 [32m[✓] [39m Chrome - develop for the web
     [32m• [39m Chrome at /Applications/GoogleChrome.app/Contents/MacOS/Google Chrome

 [32m[✓] [39m Android Studio (version 2022.1)
     [32m• [39m Android Studio at /Users/user/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
     [32m• [39m Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter
     [32m• [39m Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart
     [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

 [32m[✓] [39m Android Studio (version 2022.1)
     [32m• [39m Android Studio at /Users/user/Library/ApplicationSupport/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
     [32m• [39m Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter
     [32m• [39m Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart
     [32m• [39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

 [32m[✓] [39m VS Code (version 1.72.1)
     [32m• [39m VS Code at /Applications/Visual Studio Code.app/Contents
     [32m• [39m Flutter extension version 3.52.0

 [32m[✓] [39m Connected device (2 available)
     [32m• [39m macOS (desktop) • macos  • darwin-arm64   • macOS 13.222D49 darwin-arm64
     [32m• [39m Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.77

 [32m[✓] [39m HTTP Host Availability
     [32m• [39m All required HTTP hosts are available

 [32m• [39m No issues found!
```

## Flutter Application Metadata
**Type**: app
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03

**Comment by krishh-apnaklub** [comment] 2023-02-13 07:25
I have received [this reply](https://github.com/flutter/flutter/issues/117926#issuecomment-1426129483) on the thread of the original issue. If anyone wants to try it out and check what exactly the issue that you want to get resolved.

**Comment by krishh-apnaklub** [comment] 2023-03-02 10:52
I am still getting the same errors in v3.7.6 on stable channel while executing `flutter pub get` command. But on master channel v3.8+ there is no error and everything is working fine.

So, maybe we can wait for v3.8 to be released on stable channel.

**Comment by neetable-chollarasan** [comment] 2023-04-03 09:07
Updated to v3.7.9 still facing the same issu. Any solutions?

**Comment by stuartmorgan** [comment] 2023-05-13 20:30
Closing as a duplicate of https://github.com/flutter/flutter/issues/117926

**Closed by stuartmorgan** 2023-05-13 20:30 UTC
Labels: severe: crash, tool
