### ISSUE TITLE
Error after Flutter Upgrade

### ISSUE THREAD

**Issue by yoush97** [flutter/flutter#78721] opened 2021-03-21 10:45 UTC
So I decided to upgrade the flutter to the latest stable version 2, I used flutter clean then after the flutter upgrade, I kept getting this error intl version dependency 

```
PS D:\Flutter\flutter-app> flutter run
Because fstore depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because fstore depends on intl ^0.16.1, version solving failed.
Running "flutter pub get" in flutter-app...
pub get failed (1; So, because fstore depends on intl ^0.16.1, version solving failed.)

```
so after chaning the dependency to
```
dependency_overrides:
 intl: 0.17.0
```
I started getting these errors, _before the clean build and upgrade everything was working fine_
```
PS D:\Flutter\codecanyon-8n5MtXRZ-fluxstore-woocommerce-flutter-ecommerce-full-app> flutter run
Launching lib\main.dart on SM N950F in debug mode...
lib/widgets/firebase/firebase_cloud_messaging_wapper.dart:32:24: Error: The method 'configure' isn't defined for the class 'FirebaseMessaging'.
 - 'FirebaseMessaging' is from 'package:firebase_messaging/firebase_messaging.dart' ('../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-8.0.0-dev.15/lib/firebase_messaging.dart').
Try correcting the name to the name of an existing method, or defining a method named 'configure'.
    _firebaseMessaging.configure(
                       ^^^^^^^^^
lib/widgets/firebase/firebase_cloud_messaging_wapper.dart:42:24: Error: The getter 'onIosSettingsRegistered' isn't defined for the class 'FirebaseMessaging'.
 - 'FirebaseMessaging' is from 'package:firebase_messaging/firebase_messaging.dart' ('../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-8.0.0-dev.15/lib/firebase_messaging.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'onIosSettingsRegistered'.
    _firebaseMessaging.onIosSettingsRegistered
                       ^^^^^^^^^^^^^^^^^^^^^^^
lib/models/user_model.dart:64:14: Error: Not a constant expression.     
        case AuthorizationStatus.authorized:
             ^^^^^^^^^^^^^^^^^^^
lib/models/user_model.dart:64:14: Error: 'AuthorizationStatus' is imported from both 'package:apple_sign_in/apple_sign_in.dart' and 'package:firebase_messaging_platform_interface/src/types.dart'.
        case AuthorizationStatus.authorized:
             ^^^^^^^^^^^^^^^^^^^
lib/models/user_model.dart:86:14: Error: Not a constant expression.
        case AuthorizationStatus.error:
             ^^^^^^^^^^^^^^^^^^^
lib/models/user_model.dart:86:14: Error: 'AuthorizationStatus' is imported from both 'package:apple_sign_in/apple_sign_in.dart' and 'package:firebase_messaging_platform_interface/src/types.dart'.
        case AuthorizationStatus.error:
             ^^^^^^^^^^^^^^^^^^^
lib/models/user_model.dart:89:14: Error: Not a constant expression.
        case AuthorizationStatus.cancelled:
             ^^^^^^^^^^^^^^^^^^^
lib/models/user_model.dart:89:14: Error: 'AuthorizationStatus' is imported from both 'package:apple_sign_in/apple_sign_in.dart' and 'package:firebase_messaging_platform_interface/src/types.dart'.
        case AuthorizationStatus.cancelled:
             ^^^^^^^^^^^^^^^^^^^
lib/screens/home/onboard_screen.dart:207:19: Error: No named parameter with the name 'enableSlideIcon'.
                  enableSlideIcon: true,
                  ^^^^^^^^^^^^^^^
../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/liquid_swipe-2.0.1/lib/liquid_swipe.dart:211:9: Context: Found this candidate, but the arguments don't match.
  const LiquidSwipe({
        ^^^^^^^^^^^
../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/extended_image-2.0.0/lib/src/extended_image.dart:786:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^
../Flutter_SDK/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^
../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:46:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'colors` or `gradients');
            ^^^^^^^^^^^^^^
../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:60:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'durations');
            ^^^^^^^^^^^^^^
../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:66:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'heightPercentages');
            ^^^^^^^^^^^^^^
../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/stripe_sdk-4.0.2/lib/src/models/card.dart:55:38: Error: Too few positional arguments: 2 required, 1 given.
      return _ccValidator.validateCVV(cvc, cardType: cardType).isValid;
                                     ^
../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/stripe_sdk-4.0.2/lib/src/models/card.dart:57:38: Error: Too few positional arguments: 2 required, 1 given.
      return _ccValidator.validateCVV(cvc).isValid;
                                     ^
                                                                        
                                                                        
FAILURE: Build failed with an exception.

* Where:
Script 'D:\Flutter\Flutter_SDK\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Flutter\Flutter_SDK\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full 
insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 36s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       342.1s
Exception: Gradle task assembleDebug failed with exit code 1
```
Any help will be really appericiated.

**Comment by ekasetiawans** [comment] 2021-03-21 16:24
it doesn't seem like an issue for flutter, maybe you can go to the repository of the packages you are using and make sure that it supports flutter 2.

**Comment by pedromassangocode** [comment] 2021-03-22 10:52
Those errors seems to be related to third-party plugin/packages. If you you are facing any first-party package's dependency conflicts issue, please post your feedback in https://github.com/flutter/flutter/issues/77681.

Closing as invalid/ duplicate of https://github.com/flutter/flutter/issues/77681.
Thank you

**Closed by pedromassangocode** 2021-03-22 10:52 UTC
Labels: in triage
