### ISSUE TITLE
[go_router] Access to fragment(`/#access_token=bla_bla_bla`) in router `state`

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#108614] opened 2022-07-29 11:33 UTC
## Use case

I'm using Amazon Cognito auth and it sends token in redirect URL as `/#access_token=bla_bla_bla`
On v4.1 it worked well for me and I was able to access to this fragment in `state.location`.

On v4.2 there is no more fragment in `state.location`.

## Proposal
Could you expose fragment(`#access_token=bla_bla_bla`) the same way as you do with `state.params`?

**Comment by chunhtai** [comment] 2022-08-04 21:52
Is this a regression that it worked on 4.1?

also can you provide a minimum repro code?

**Comment by chunhtai** [comment] 2022-08-25 21:41
It looks like the fragment is dropped somewhere in the parsing pipeline
`_addQueryParams` in match.dart should also append the fragment.

**Comment by SheriefAlaa** [comment] 2022-11-06 10:48
I can reproduce on version 5.1.5. Flutter 3.3.5.

**Comment by rlee1990** [comment] 2023-04-17 02:04
Any update on this?

**Comment by chunhtai** [comment] 2023-07-21 16:16
yes this looks correct, although I am not the owner of that part of the code. feel free to open a pr and pin me on it, I can help redirect to the right person

**Comment by yjbanov** [comment] 2023-08-03 18:16
Assigned to @vasilich6107 and @chunhtai who are actively working on the PR.

**Comment by chunhtai** [comment] 2023-08-03 18:18
should be fixed by https://github.com/flutter/flutter/pull/131123

**Closed** 2023-12-07 22:47 UTC
Labels: c: new feature, package, c: proposal, P2, p: go_router, team-go_router, triaged-go_router, fyi-web, multiteam-retriage-candidate
