### ISSUE TITLE
Can't change fontFamily when using ThemeData light/dark constructors

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#41276] opened 2019-09-25 09:50 UTC
When using a `MaterialApp`, you can change the `fontFamily` of the whole app by specifying the `fontFamily` parameter in the provided `ThemeData`.

## Steps to Reproduce

1. Create a new app
2. Specify the `theme` and `darkTheme` parameters as in the provided code

## Sample code

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData.light().copyWith(
        fontFamily: 'Nunito',
      ),
      darkTheme: ThemeData(
        fontFamily: 'Nunito',
      ),
      home: Scaffold(
        body: Center(
          child: Text('Sample app'),
        ),
      ),
    ),
  );
}
```

Notice the first `fontFamily` will not be valid, whereas the second one will. This parameter is important because if you want to use the default `ThemeData.light()` or `ThemeData.dark()` parameters but want to change the `fontFamily` parameter, the workaround would be more difficult or non-trivial.

## Flutter doctor

```
flutter doctor -v
[√] Flutter (Channel master, v1.10.6-pre.61, on Microsoft Windows [VersiÃ³n 10.0.18362.356], locale es-ES)
    • Flutter version 1.10.6-pre.61 at C:\src\flutter
    • Framework revision 7bf9aea254 (70 minutes ago), 2019-09-25 00:37:12 -0700
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Pixel 3 XL • 89PY09NNV • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by darran-kelinske-fivestars** [comment] 2019-11-05 04:08
Anyone have a workaround?

**Comment by dazza5000** [comment] 2019-11-05 04:12
This is a workaround for ThemeData.light()

```
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        title: COMPANY_NAME,
        navigatorKey: NotificationUtil.navigatorKey,
        theme: ThemeData(
          brightness: Brightness.light,
            fontFamily: "ProximaNova",
            primaryColor: const Color(0xFF13172a),
            accentColor: const Color(0xFFA8C048),),
        home: HomePage(title: COMPANY_NAME),
        routes: {
          '/notifications': (context) => MainPage(1),
        });
```

**Comment by resfandiari** [comment] 2020-04-28 14:36
This work for me
```dart
ThemeData lightTheme = ThemeData.light().copyWith(
    textTheme: ThemeData.dark().textTheme.apply(
          fontFamily: 'RobotoMono',
        ),
    primaryTextTheme: ThemeData.dark().textTheme.apply(
          fontFamily: 'RobotoMono',
        ),
    accentTextTheme: ThemeData.dark().textTheme.apply(
          fontFamily: 'RobotoMono',
        ),
);
```

**Comment by BigtoC** [comment] 2020-05-17 10:32
> This work for me
> 
> ```dart
> ThemeData lightTheme = ThemeData.light().copyWith(
>     textTheme: ThemeData.dark().textTheme.apply(
>           fontFamily: 'RobotoMono',
>         ),
>     primaryTextTheme: ThemeData.dark().textTheme.apply(
>           fontFamily: 'RobotoMono',
>         ),
>     accentTextTheme: ThemeData.dark().textTheme.apply(
>           fontFamily: 'RobotoMono',
>         ),
> );
> ```

This works for me! Thanks!

**Comment by TahaTesser** [comment] 2020-07-03 12:02
Hi @dazza5000 
This is deprecated 
```
 theme: ThemeData.light().copyWith(
        fontFamily: 'Nunito',
      ),
```

https://github.com/flutter/flutter/issues/41276#issuecomment-549655361 works fine 
<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData.light().copyWith(
        textTheme: ThemeData.dark().textTheme.apply(
              fontFamily: 'Ubuntu',
            ),
        primaryTextTheme: ThemeData.dark().textTheme.apply(
              fontFamily: 'Ubuntu',
            ),
        accentTextTheme: ThemeData.dark().textTheme.apply(
              fontFamily: 'Ubuntu',
            ),
      ),
      darkTheme: ThemeData(
        fontFamily: 'Ubuntu',
      ),
      home: Scaffold(
        body: Center(
          child: Text('Sample app'),
        ),
      ),
    ),
  );
}

``` 

</details> 

<details> 
<summary>stable flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (10 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
``` 

</details> 

Do you think this issue is still valid?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-07-29 11:12
I can't reproduce it as well with the code sample from https://github.com/flutter/flutter/issues/41276#issuecomment-653514931 with current master `1.21.0-6.0.pre.90`.
Seems to be fixed, closing.
@Zazo032 please comment if you disagree and I'll reopen

**Closed by VladyslavBondarenko** 2020-07-29 11:12 UTC
Labels: a: typography, customer: crowd, f: material design, framework, waiting for customer response

**Comment by Zazo032** [comment] 2020-08-03 15:15
Hi @VladyslavBondarenko, I think you can't change `fontFamily` by copying default light or dark `ThemeData`'s constructors yet:

![image](https://user-images.githubusercontent.com/2807712/89197967-c6864180-d5ac-11ea-9b75-c5d54b483d0e.png)

`Flutter 1.21.0-6.0.pre.142`

**Comment by TahaTesser** [comment] 2020-08-04 12:43
Hi @Zazo032 
<img width="858" alt="Screenshot 2020-08-04 at 6 12 44 PM" src="https://user-images.githubusercontent.com/48603081/89295112-20a30780-d67e-11ea-850c-e1743e1e58a8.png">

I can run the code sample 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.160, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-6.0.pre.160 at /Users/taha/Code/flutter_master
    • Framework revision 31ee51a302 (10 hours ago), 2020-08-03 17:27:21 -0700
    • Engine revision fa16c3d0ba
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

 
[✓] Connected device (5 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.6
    • iPhone 11 (mobile)     • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X
      10.15.6 19G73
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      84.0.4147.105

• No issues found!
```

</details>

**Comment by karmazinkd** [comment] 2020-11-06 14:31
@resfandiari @TahaTesser  ok, but how you're going to change `fontWeight` for all buttons in this case?

There is no such property as `fontWeight` in `ThemeData.textTheme.apply(fontweight: ...)`

**Comment by Okladnoj** [comment] 2020-12-14 09:45
Thus, I change the font of my theme, but the error breaks everything ...
![image](https://user-images.githubusercontent.com/36802187/102065742-9e7fd800-3e01-11eb-84f9-92e0edc89181.png)
![image](https://user-images.githubusercontent.com/36802187/102065666-890aae00-3e01-11eb-97ec-05ae3c9c9bcb.png)
what's wrong?

**Comment by ronytesler** [comment] 2021-07-07 23:06
@VladyslavBondarenko Not working:
```
ThemeData.light().copyWith(
        fontFamily: 'Heebo',
       primaryColor: Color(0xff283c81)
      )
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.1052], locale en-US)
    • Flutter version 2.2.1 at c:\flutter\flutter
    • Framework revision 02c026b03c (6 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Rony\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Rony\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.64

• No issues found!
```
