### ISSUE TITLE
Flutter Android Alarm Manager is not firing events as expected when screen is off

### ISSUE THREAD

**Issue by alemoi** [flutter/flutter#58263] opened 2020-05-29 19:27 UTC
## Steps to Reproduce

Run the Flutter official example app "Android Alarm Manager": https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager/example

with the modification that `AndroidAlarmManager.oneShot` is called directly after its finished, so we have a continuous one after another flow of `oneShot` calls:

```dart
  static Future<void> callback() async {
    print('Alarm fired!');

    // Get the previous cached count and increment it.
    final prefs = await SharedPreferences.getInstance();
    int currentCount = prefs.getInt(countKey);
    await prefs.setInt(countKey, currentCount + 1);

    // This will be null if we're running in the background.
    uiSendPort ??= IsolateNameServer.lookupPortByName(isolateName);
    uiSendPort?.send(null);

    // ------> Here is the only modification: triggering alarm again
    await AndroidAlarmManager.oneShot(
      const Duration(seconds: 10),
      // Ensure we have a unique alarm ID.
      Random().nextInt(pow(2, 31)),
      callback,
      exact: true,
      wakeup: true,
    );
    // End of modification
  }
```

**Expected results:**
`AndroidAlarmManager.oneShot` is being fired every 10 seconds after first start.

**Actual results:**

In emulator and when real device is debugged using USB - everything works well. However on a real device with the screen turned off (and no USB debugging) - `AndroidAlarmManager.oneShot` calls are not fired properly (strangely delayed or not fired at all after first one).

This issue is probably related to this one: https://github.com/flutter/flutter/issues/39115

I don't think it matters on which physical device I'm running, but its Android version is 10.

**Versions:**

Everything latest: Flutter and Android Alarm Manager.

**Comment by TahaTesser** [comment] 2020-06-01 09:55
hI @alemoi 
Using official example using modification in release mode with screen off without cable and usb debugging off 

```
  static Future<void> callback() async {
    print('Alarm fired!');

    // Get the previous cached count and increment it.
    final prefs = await SharedPreferences.getInstance();
    int currentCount = prefs.getInt(countKey);
    await prefs.setInt(countKey, currentCount + 1);

    // This will be null if we're running in the background.
    uiSendPort ??= IsolateNameServer.lookupPortByName(isolateName);
    uiSendPort?.send(null);

    await AndroidAlarmManager.oneShot(
      const Duration(seconds: 10),
      // Ensure we have a unique alarm ID.
      Random().nextInt(pow(2, 31)),
      callback,
      exact: true,
      wakeup: true,
    );
  }
```
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (3 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details> 

![Screenshot_20200601-152004](https://user-images.githubusercontent.com/48603081/83397804-daca8880-a41b-11ea-986a-605b6967f016.jpeg)


Can you please provide your `flutter doctor -v`? This could be device specific, which device you tested on?
Thank you"

**Comment by alemoi** [comment] 2020-06-06 09:33
Dear @TahaTesser, thanks for the reply!

I still can reproduce it on several devices (all Android 10), don't think doctor information will tell you anything. Reproduction scenario:
1. Have the reoccurring `oneShot` alarm as described before. But set the `Duration` to 60 seconds for easier counting (in both `oneShot` calls).
2. Start the "Android Alarm Manager" and some default Android Stopwatch timer, so you can verify the results. And start them both one after each other.
3. Just put the phone aside with screen off.
4. For me on any device, for example, after 15 minutes on Stopwatch, I see around 7 alarms fired in "Android Alarm Manager", and it should be 15 instead.

That's basically it. Again, setting `oneShot` to 60 seconds just simplifies counting.

**Comment by TahaTesser** [comment] 2020-06-08 08:56
@alemoi 
Thanks for detailed steps, i can definitely reproduce this now  

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-4.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-4.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 2f7a59a8da (3 days ago), 2020-06-05 03:44:02 -0700
    • Engine revision d17c84e7af
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 02915ec5ce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by alemoi** [comment] 2020-06-13 21:25
@TahaTesser my pleasure :) Hope it helps moving this hot topic of background jobs further :)

**Comment by shinewanna** [comment] 2020-10-18 05:37
I'm also facing the issue, when the app screen is off too long, alarm manager is delay 5 mins to 30 mins to execute, the problem is not alerting at exact time.

**Comment by klitzouille** [comment] 2020-10-31 12:42
It may be related to Android doze mode. Doc [here](https://developer.android.com/training/monitoring-device-state/doze-standby) states this : 

> The following restrictions apply to your apps while in Doze:
> 
> - Network access is suspended.
> - The system ignores wake locks.
> - Standard AlarmManager alarms (including setExact() and setWindow()) are deferred to the next maintenance window.
>   - If you need to set alarms that fire while in Doze, use setAndAllowWhileIdle() or setExactAndAllowWhileIdle().
>   - Alarms set with setAlarmClock() continue to fire normally — the system exits Doze shortly before those alarms fire.

You could try with :
```
allowWhileIdle: true,
exact: true
```
or just :
`
alarmClock: true
`

**Comment by habilgur** [comment] 2020-11-11 18:22
Im facing an issue with alarms that androidAlarmManager never handle over  doze mode even i used setAlarmClock().   

Android Document says:"Alarms set with setAlarmClock() continue to fire normally — the system exits Doze shortly before those alarms fire." 
Also i checked the plugin codes  in android_alarm_manager-0.4.5 17 version, 
with parameters ( wakeup: true, rescheduleOnReboot: true, alarmClock: true), AndroidAlarmManager.oneShot() func is returning setAlarmClock() with RTC_WAKEUP clock from native side.

Below you can find how im calling oneShot();

    AndroidAlarmManager.oneShot(Duration(milliseconds: nextAlarmTimeInMilliseconds), item.id, _notificationCallBack,
        rescheduleOnReboot: true,
        alarmClock: true ,
    );

Everythings seems working when phone awake however when phone enter doze mode, alarms not firing on exact time. Whenever the phone exit doze mode by moved or touched by someone,  alarms are firing with delay.

**Comment by klitzouille** [comment] 2020-11-12 12:44
You could try the fix suggested in https://github.com/flutter/flutter/issues/30555

**Comment by bradolh** [comment] 2020-12-17 10:05
@klitzouille not working with that fix neither any of the suggestions listed above, so basically this plugins is useless if your phone enters the doze mode?

**Comment by klitzouille** [comment] 2020-12-17 10:20
I did a little digging in the plugin code, and I found out that it uses Android's JobIntentService, scheduled through JobScheduler to execute the dart code provided in the callback.

Doc [here](https://developer.android.com/reference/androidx/core/app/JobIntentService) says that any task scheduled with JobScheduler can be delayed by the system as it sees fit (doze mode, strong memory pressure, ...). I don't think there is a way to ensure your task will be triggered when in doze mode with this plugin.

Google's alarm app uses a ForegroundService instead of a JobIntentService to achieve that, so it may work for you as well, but you will have to code in Java/Kotlin for this part.

**Comment by TahaTesser** [comment] 2021-01-29 13:47
Hi @alemoi 
Thanks, @klitzouille, I agree it depends on the system's resources, I doubt the package can't do anything here. Alternatively, you can try any third-party packages that support ForegroundService.
Closing, as this isn't an issue with `android_alarm_manager. itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-29 13:47 UTC
Labels: found in release: 1.19, has reproducible steps, p: android_alarm_manager, p: first party, platform-android, plugin

**Comment by myNameIsHamza** [comment] 2021-02-12 11:50
AndroidAlarmManager.oneShot(Duration(seconds: 10), 0, _playSound,
      exact: true,wakeup: true);
wakeup: true  solve it for me.

**Comment by myNameIsHamza** [comment] 2021-02-12 14:08
For screen off wakeup: true solve it like:
AndroidAlarmManager.oneShot(Duration(seconds: 10), 0, _playSound,
      exact: true,wakeup: true);

But if you kill the app I needed to use notification with alarm manager to make it work like in:
await flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: (String payload) async {
    if (payload != null) {
      debugPrint('notification payload: $payload');
      //do some work
    }
