### ISSUE TITLE
Overall experience test is flaky on windows

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#81556] opened 2021-04-30 17:39 UTC
Output:

```
04:36 +8 ~14: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                          
Test is taking a long time.
Expected state transitions:
    0 NOW WAITING FOR> "Flutter run key commands.", "called main" (matched 0 so far)
    1                  /^Performing hot reload\.\.\./
    2                  "ready", "called paint" (matched 0 so far)
    3                  /^Performing hot restart\.\.\./
    4                  "ready", "called main", "called paint" (matched 0 so far)
    5                  "ready", "called paint", "called debugPaintSize" (matched 0 so far)
    6                  "ready", "called paint" (matched 0 so far)
    7                  "Application finished."
So far nothing has been logged; use debug:true to print all output.
(streaming all logs from this point on...)
stdout: called main
stdout: Syncing files to device Flutter test device...                  
stdout: called paint
stdout: Syncing files to device Flutter test device...                     310ms
stdout: 
stdout: Flutter run key commands.
(matched "Flutter run key commands.", "called main" (matched 2 so far))
stdin: r
stdout: r Hot reload. 
stdout: R Hot restart.
stdout: h List all available interactive commands.
stdout: d Detach (terminate "flutter run" but leave application running).
stdout: c Clear the screen
stdout: q Quit (terminate the application on the device).
stdout: 
stdout:  Running with sound null safety 
stdout: 
stdout: An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:53174/ALApntEKYaY=/
stdout: 
stdout: Performing hot reload...                                        called reassemble
(matched /^Performing hot reload\.\.\./)
(enabled logging)
stdout: called paint
stdout: 
stdout: Reloaded 0 libraries in 193ms.
stdout: ready
(matched "ready", "called paint" (matched 2 so far))
stdin: R
stdout: 
stdout: Performing hot restart...                                       
(matched /^Performing hot restart\.\.\./)
stdout: Restarted application in 617ms.
stdout: ready
stdout: called main
(process is not quitting, trying to send a "q" just in case that helps)
(a functional test should never reach this point)
stdout: 
stdout: Application finished.
stdout: ready
(process terminated with exit code 0)
The subprocess terminated before all the expected transitions had been matched.
The transition that we were hoping to see next but that we never saw was:
    4 NOW WAITING FOR> "ready", "called main", "called paint" (matched 2 so far)

04:49 +8 ~14 -1: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key [E]                                                                   
  Missed some expected transitions.
  test\integration.shard\overall_experience_test.dart 275:5  runFlutter
  

04:49 +8 ~14 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link  
```

**Comment by goderbauer** [comment] 2021-04-30 18:31
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_4_5/33/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_4_5/35/overview

**Comment by Hixie** [comment] 2021-05-03 22:20
This should be fixed by https://github.com/flutter/flutter/pull/81607.

**Comment by Hixie** [comment] 2021-05-03 22:21
(It's also possible it's a separate problem, but in that case we'll need new logs anyway to determine the issue, since that PR changes how this test would work.)

**Comment by darrenaustin** [comment] 2021-08-10 19:45
Re-opening as I just tried to reenable this test and got the following log:

```
08:20 +13 ~13: test\integration.shard\observatory_port_test.dart: flutter run --dds-port                                                                                                               
08:20 +13 ~13: loading test\integration.shard\overall_experience_test.dart                                                                                                                             
08:20 +13 ~13: test\integration.shard\overall_experience_test.dart: flutter run writes and clears pidfile appropriately                                                                                
08:20 +13 ~14: test\integration.shard\overall_experience_test.dart: flutter run writes and clears pidfile appropriately                                                                                
08:20 +13 ~14: test\integration.shard\overall_experience_test.dart: flutter run handle SIGUSR1/2                                                                                                       
08:20 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run handle SIGUSR1/2                                                                                                       
08:20 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:21 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:22 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:23 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:24 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:25 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:26 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:27 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:28 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:29 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:30 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:31 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:32 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:33 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
08:33 +13 ~15: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key                                                                         
Test is taking a long time (12 seconds so far).
Expected state transitions:
    0 NOW WAITING FOR> "Flutter run key commands.", "called main", "called paint" (all matched)
    1                  "Performing hot reload...                                        "
    2                  "ready", "called reassemble", "called paint" (all matched)
    3                  "Performing hot restart...                                       "
    4                  "ready", "called main", "called paint" (all matched)
    5                  "ready", "called paint", "called debugPaintSize" (all matched)
    6                  "ready", "called paint" (all matched)
    7                  "Application finished."
So far nothing has been logged; use debug:true to print all output.
(streaming all logs from this point on...)
[ 25.1s] (process is not quitting, trying to send a "q" just in case that helps)
(a functional test should never reach this point)
[ 25.1s] stdin: q
[ 27.0s] stdout: called main
[ 27.6s] stdout: Syncing files to device Flutter test device...                  
[ 27.6s] stdout: called paint
[ 27.9s] stdout: Syncing files to device Flutter test device...                     320ms
[ 28.0s] stdout: 
[ 28.0s] stdout: Flutter run key commands.
(matched "Flutter run key commands.", "called main", "called paint" (matched 3 so far))
[ 28.0s] stdin: r
[ 28.0s] stdout: r Hot reload. 
[ 28.0s] stdout: R Hot restart.
[ 28.0s] stdout: h List all available interactive commands.
[ 28.0s] stdout: d Detach (terminate "flutter run" but leave application running).
[ 28.0s] stdout: c Clear the screen
[ 28.0s] stdout: q Quit (terminate the application on the device).
[ 28.0s] stdout: 
[ 28.0s] stdout:  Running with sound null safety 
[ 28.0s] stdout: 
[ 28.0s] stdout: An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:62637/e-2rTfn9HCs=/
[ 28.0s] stdout: 
[ 28.0s] stdout: ready
(taking a long time...)

23:20 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key [E]                                                                  
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
  
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

23:20 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:21 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:22 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:23 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:24 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:25 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:26 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:27 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:28 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:29 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:30 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:31 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:32 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:33 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
23:33 +13 ~15 -1: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link                                                                                  
Test is taking a long time (12 seconds so far).
Expected state transitions:
    0 NOW WAITING FOR> /^An Observatory debugger and profiler on Flutter test device is available at: /
    1                  /^The Flutter DevTools debugger and profiler on Flutter test device is available at: /
    2                  "Performing hot reload...                                        "
    3                  /^Reloaded 0 libraries in [0-9]+ms./
So far nothing has been logged; use debug:true to print all output.
(streaming all logs from this point on...)
[ 25.0s] (process is not quitting, trying to send a "q" just in case that helps)
(a functional test should never reach this point)
[ 25.0s] stdin: q
[ 25.9s] stdout: Syncing files to device Flutter test device...                     284ms
[ 26.0s] stdout: 
[ 26.0s] stdout: Flutter run key commands.
[ 26.0s] stdout: r Hot reload. 
[ 26.0s] stdout: R Hot restart.
[ 26.0s] stdout: h List all available interactive commands.
[ 26.0s] stdout: d Detach (terminate "flutter run" but leave application running).
[ 26.0s] stdout: c Clear the screen
[ 26.0s] stdout: q Quit (terminate the application on the device).
[ 26.0s] stdout: 
[ 26.0s] stdout:  Running with sound null safety 
[ 26.0s] stdout: 
[ 26.0s] stdout: An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:62734/8bMsW-pY1BQ=/
(matched /^An Observatory debugger and profiler on Flutter test device is available at: /)
[ 26.0s] stdout: 
[ 26.0s] stdout: Application finished.
[ 26.1s] (process terminated with exit code 0)
The subprocess terminated before all the expected transitions had been matched.
The transition that we were hoping to see next but that we never saw was:
    1 NOW WAITING FOR> /^The Flutter DevTools debugger and profiler on Flutter test device is available at: /

23:47 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter error messages include a DevTools link [E]                                                                              
  Missed some expected transitions.
  test\integration.shard\overall_experience_test.dart 318:5   runFlutter
  ===== asynchronous gap ===========================
  test\integration.shard\overall_experience_test.dart 495:40  main.<fn>
  

23:47 +13 ~15 -2: loading test\integration.shard\overall_experience_test.dart                                                                                                                          
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

23:47 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:48 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:49 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:50 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:51 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:52 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:53 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:54 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:55 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:56 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:57 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:58 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:59 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
23:59 +13 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
Test is taking a long time (12 seconds so far).
Expected state transitions:
    0 NOW WAITING FOR> /^The Flutter DevTools/
    1                  /^The Flutter DevTools/
    2                  "Application finished."
Log (only contains logged lines; use debug:true to print all output):
[  3.1s] stdout: Launching lib\main.dart on Flutter test device in debug mode...
(streaming all logs from this point on...)
[ 18.4s] stdout: Syncing files to device Flutter test device...                     100ms
[ 18.4s] stdout: 
[ 18.4s] stdout: Flutter run key commands.
[ 18.4s] stdout: r Hot reload. 
[ 18.4s] stdout: R Hot restart.
[ 18.4s] stdout: h List all available interactive commands.
[ 18.4s] stdout: d Detach (terminate "flutter run" but leave application running).
[ 18.4s] stdout: c Clear the screen
[ 18.4s] stdout: q Quit (terminate the application on the device).
[ 18.4s] stdout: 
[ 18.4s] stdout:  Running with sound null safety 
[ 18.4s] stdout: 
[ 18.4s] stdout: An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:62741/6zv6D0unhLA=/
[ 19.5s] stdout: The Flutter DevTools debugger and profiler on Flutter test device is available at: http://127.0.0.1:62746?uri=http://127.0.0.1:62741/6zv6D0unhLA=/
(matched /^The Flutter DevTools/)
[ 19.5s] stdin: h
[ 19.5s] stdout: 
[ 19.5s] stdout: Flutter run key commands.
[ 19.5s] stdout: r Hot reload. 
[ 19.5s] stdout: R Hot restart.
[ 19.5s] stdout: v Open Flutter DevTools.
[ 19.5s] stdout: w Dump widget hierarchy to the console.                                               (debugDumpApp)
[ 19.5s] stdout: t Dump rendering tree to the console.                                          (debugDumpRenderTree)
[ 19.5s] stdout: L Dump layer tree to the console.                                               (debugDumpLayerTree)
[ 19.5s] stdout: S Dump accessibility tree in traversal order.                                   (debugDumpSemantics)
[ 19.5s] stdout: U Dump accessibility tree in inverse hit test order.                            (debugDumpSemantics)
[ 19.5s] stdout: i Toggle widget inspector.                                  (WidgetsApp.showWidgetInspectorOverride)
[ 19.5s] stdout: p Toggle the display of construction lines.                                  (debugPaintSizeEnabled)
[ 19.5s] stdout: I Toggle oversized image inversion.                                     (debugInvertOversizedImages)
[ 19.5s] stdout: o Simulate different operating systems.                                      (defaultTargetPlatform)
[ 19.5s] stdout: b Toggle platform brightness (dark and light mode).                        (debugBrightnessOverride)
[ 19.5s] stdout: P Toggle performance overlay.                                    (WidgetsApp.showPerformanceOverlay)
[ 19.5s] stdout: a Toggle timeline events for all widget build methods.                    (debugProfileWidgetBuilds)
[ 19.5s] stdout: M Write SkSL shaders to a unique file in the project directory.
[ 19.5s] stdout: g Run source code generators.
[ 19.5s] stdout: h Repeat this help message.
[ 19.5s] stdout: d Detach (terminate "flutter run" but leave application running).
[ 19.5s] stdout: c Clear the screen
[ 19.5s] stdout: q Quit (terminate the application on the device).
[ 19.5s] stdout: 
[ 19.5s] stdout:  Running with sound null safety 
[ 19.5s] stdout: 
[ 19.5s] stdout: An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:62741/6zv6D0unhLA=/
[ 19.6s] stdout: The Flutter DevTools debugger and profiler on Flutter test device is available at: http://127.0.0.1:62746?uri=http://127.0.0.1:62741/6zv6D0unhLA=/
(matched /^The Flutter DevTools/)
[ 19.6s] stdin: q
[ 19.6s] stdout: 
[ 19.6s] stdout: Application finished.
(matched "Application finished.")
[ 19.7s] (process terminated with exit code 0)
[ 19.7s] (completed execution successfully!)

24:06 +14 ~15 -2: test\integration.shard\overall_experience_test.dart: flutter run help output                                                                                                         
24:06 +14 ~15 -2: loading test\integration.shard\plist_parser_test.dart                                                                                                                                
24:07 +14 ~15 -2: loading test\integration.shard\plist_parser_test.dart                                                                                                                                
24:07 +14 ~15 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile returns null for malformed plist file                                                                    
24:07 +14 ~16 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile returns null for malformed plist file                                                                    
24:07 +14 ~16 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile works with json file                                                                                     
24:07 +14 ~17 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile works with json file                                                                                     
24:07 +14 ~17 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile returns null for non-existent plist file                                                                 
24:07 +14 ~18 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile returns null for non-existent plist file                                                                 
24:07 +14 ~18 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile works with xml file                                                                                      
24:07 +14 ~19 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile works with xml file                                                                                      
24:07 +14 ~19 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile throws when /usr/bin/plutil is not found                                                                 
24:07 +15 ~19 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile throws when /usr/bin/plutil is not found                                                                 
24:07 +15 ~19 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile works with binary file                                                                                   
24:07 +15 ~20 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile works with binary file                                                                                   
24:07 +15 ~20 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile returns null for non-existent key within plist                                                           
24:07 +15 ~21 -2: test\integration.shard\plist_parser_test.dart: PlistParser.getValueFromFile returns null for non-existent key within plist                                                           
24:07 +15 ~21 -2: loading test\integration.shard\single_widget_reload_test.dart                                                                                                                        
24:07 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:08 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:09 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:10 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:11 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:12 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:13 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:14 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:15 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:16 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:17 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:18 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:19 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:20 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:21 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:22 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:23 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:24 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:25 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:26 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:27 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:28 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:29 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:30 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:31 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:32 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:33 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:34 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:35 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:36 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:37 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:38 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:38 +15 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
Failed to delete C:\b\s\w\ir\x\t\flutter_hot_reload_test.ddd20f43: FileSystemException: Deletion failed, path = 'C:\b\s\w\ir\x\t\flutter_hot_reload_test.ddd20f43' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)

24:38 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: newly added code executes during hot reload with single widget reloads, but only invalidated widget                           
24:38 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:39 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:40 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:41 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:42 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:43 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:44 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:45 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:46 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:47 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:48 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:49 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:50 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:51 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:52 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:53 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:54 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:55 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:56 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:57 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:58 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
24:59 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:00 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:01 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:02 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:03 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:04 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:05 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:06 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:07 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:08 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:08 +16 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
Failed to delete C:\b\s\w\ir\x\t\flutter_hot_reload_test.e73bafc2: FileSystemException: Deletion failed, path = 'C:\b\s\w\ir\x\t\flutter_hot_reload_test.e73bafc2' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)

25:08 +17 ~21 -2: test\integration.shard\single_widget_reload_test.dart: changes outside of the class body triggers a full reload                                                                      
25:08 +17 ~21 -2: Some tests failed.                                                                                                                                                                   
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
Command: ..\..\bin\cache\dart-sdk\bin\pub.bat run test --test-randomize-ordering-seed=20210810 -rcompact -j1 --no-color test\integration.shard\hot_reload_test.dart test\integration.shard\hot_reload_with_asset_test.dart test\integration.shard\ios_content_validation_test.dart test\integration.shard\lifetime_test.dart test\integration.shard\macos_content_validation_test.dart test\integration.shard\observatory_port_test.dart test\integration.shard\overall_experience_test.dart test\integration.shard\plist_parser_test.dart test\integration.shard\single_widget_reload_test.dart
Relative working directory: packages\flutter_tools
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by Hixie** [comment] 2021-08-11 15:54
@darrenaustin probably best to file a new bug since there's lots of different causes wrapped in here.

It's also possible this is a new regression rather than just the test being flaky (I haven't had a chance to examine those logs yet) since the test has been relatively stable for a while now if I'm not mistaken.

**Comment by Hixie** [comment] 2021-08-11 21:23
Looking at the logs above it seems like things were just too slow that run? 25s to get from the top of the test to syncing with the "device" seems excessive, but I guess maybe we just need to increase the timeouts? I am not sure why we have a timeout that short in the first place, it's supposed to be only a little less than the full test timeout itself (15 min).

**Comment by Hixie** [comment] 2021-09-16 21:49
Closing as duplicate of https://github.com/flutter/flutter/issues/81486.

**Closed by Hixie** 2021-09-16 21:49 UTC
Labels: team, tool, team: flakes
