### ISSUE TITLE
Ripple does not finish before pushing material page route

### ISSUE THREAD

**Issue by joshrap67** [flutter/flutter#133889] opened 2023-09-01 20:44 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Have some sort of widget that produces a ripple (e.g. ElevatedButton)
2. From the onTap of that widget push a new material route to a second page
3. On the second page, pop to return to the first page.

### Expected results

1. The first page should return with no further animation on the button that was pressed to push the route.

### Actual results

When returning to the first page, the ripple animation will now finish its animation. Hopefully this makes sense, if not I think the video clearly shows what is happening.

I'm not sure if this is intended behavior, to me it seems very odd and buggy and I do not see it on any of the mainstream apps I have downloaded so it makes me think this is some sort of bug. I find it very distracting when returning to a page and seeing the ripple as it looks like a button was pressed on its own (since I could be returning to the original page after some time).

I would expect the ripple animation to finish before launching the page, or to just be canceled when the new page is pushed. On my older flutter apps I did not see this problem, and on [the official documentation for navigating to a new page](https://docs.flutter.dev/cookbook/navigation/navigation-basics#interactive-example) I did not observe this.

I would prefer to not have to wrap all of my material route pushes in a future.delayed to let the ripple finish since this feels like a pretty gross hack.

I'm experiencing this both on an emulator in debug mode, and on a Samsung device in release mode.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:untitled/other.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const OtherScreen(),
                  ),
                );
              },
              child: const Text('Foo'),
            )
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![VTnjQ](https://github.com/flutter/flutter/assets/36081235/ced72efe-98dc-491d-92e2-ad6620cdafc3)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
    • Flutter version 3.13.2 on channel stable at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (8 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 223.8617.8

[√] VS Code (version 1.81.1)
    • VS Code at C:\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 116.0.5845.140
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 116.0.1938.54

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by sabin26** [comment] 2023-09-02 11:30
Duplicate of #119897.

Solution is mentioned here: https://github.com/flutter/flutter/issues/119897#issuecomment-1446149037

**Comment by danagbemava-nc** [comment] 2023-09-04 07:17
Closing this as a duplicate of https://github.com/flutter/flutter/issues/119897

**Closed by danagbemava-nc** 2023-09-04 07:17 UTC
Labels: in triage
