### ISSUE TITLE
`SliverAppBar` decreases brightness of `FlexibleSpaceBar` if `isScrolledUnder == true`

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#131449] opened 2023-07-28 00:18 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run code sample below.
2. Scroll list up so that `FlexibleSpaceBar` is collapsed
3. Pull list down a bit again, but not all the way to show the very top of the list
4. Carefully watch the color of the `FlexibleSpaceBar` as you continue to pull the list down, to expose the very top of the list. The background will get brighter.

Screenshot of step 3:

![image](https://github.com/flutter/flutter/assets/811305/07898ec1-4856-4aa4-b8fe-84be957f8840)

Screenshot of step 4, showing brighter (correct shade of) background:

![image](https://github.com/flutter/flutter/assets/811305/a9447375-0727-42df-936c-19d799e1a2bd)

### Expected results

The background color should never change.

### Actual results

When the list is scrolled so that the top of 'Place 1' is not shown (i.e. when `SliverAppBar.isScrolledUnder` is `true`), the background color gets a bit darker.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            const SliverAppBar(
              expandedHeight: 100,
              flexibleSpace: FlexibleSpaceBar(
                title: Text('Title text'),
              ),
              floating: true,
              pinned: false,
              snap: false,
              backgroundColor: Colors.amber,
            ),
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (_, int index) {
                  return ListTile(
                    leading: Container(
                      padding: const EdgeInsets.all(8),
                      width: 100,
                      child: const Placeholder(),
                    ),
                    title: Text('Place ${index + 1}', textScaleFactor: 2),
                  );
                },
                childCount: 20,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

See above.

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on Fedora Linux 38 (Workstation Edition) 6.3.6-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.10.6 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.5 (Fedora 16.0.5-1.fc38)
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.3.6-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 115.0.5790.102

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-07-28 09:21
Hi @lukehutch. Thanks for filing this issue. This is an expected behaviour see: https://api.flutter.dev/flutter/material/SliverAppBar/surfaceTintColor.html
surface tint color is drawn on top of the background color, you can set `surfaceTintColor` to `Colors.transparent` to disable it. Closing this as this seems to be the expected behaviour.

**Closed by dam-ease** 2023-07-28 09:21 UTC
Labels: in triage

**Comment by lukehutch** [comment] 2023-07-28 09:58
@dam-ease Thanks, that fixed it. However, then the docs are wrong:

```dart
  /// {@template flutter.material.appbar.elevation}
  /// The z-coordinate at which to place this app bar relative to its parent.
  ///
  /// This property controls the size of the shadow below the app bar if
  /// [shadowColor] is not null.
  ///
  /// If [surfaceTintColor] is not null then it will apply a surface tint overlay
  /// to the background color (see [Material.surfaceTintColor] for more
  /// detail).
  ///
  /// The value must be non-negative.
  ///
  /// If this property is null, then [AppBarTheme.elevation] of
  /// [ThemeData.appBarTheme] is used. If that is also null, the
  /// default value is 4.
  /// {@endtemplate}
  ///
  /// See also:
  ///
  ///  * [scrolledUnderElevation], which will be used when the app bar has
  ///    something scrolled underneath it.
  ///  * [shadowColor], which is the color of the shadow below the app bar.
  ///  * [surfaceTintColor], which determines the elevation overlay that will
  ///    be applied to the background of the app bar.
  ///  * [shape], which defines the shape of the app bar's [Material] and its
  ///    shadow.
  final double? elevation;
```

By default, `surfaceTintColor` is null, so these docs imply that there should be no elevation overlay color applied to the background of the app bar.

More generally, anything other than `Colors.transparent` is a really bad default for `surfaceTintColor`.
