### ISSUE TITLE
I'm getting an exception to authenticate with phone number using firebase in flutter

### ISSUE THREAD

**Issue by shrutiramnandan** [flutter/flutter#37753] opened 2019-08-07 06:03 UTC
## Logs

```
//It will send you OTP to given phone number.


  Future<void> verifyPhone()async{
    final PhoneCodeAutoRetrievalTimeout autoRetrieval=(String verId){
      this.verificationId=verId;
    };

    final PhoneCodeSent smsCodeSent=(String verId, [int forceCodeResend]){
      this.verificationId=verId;
      smsCodeDialog(context).then((value){
        print("Signed in");
      });
    };
     
    final PhoneVerificationCompleted verifiedSuccess = (FirebaseUser user){
    print("verified");
    } as PhoneVerificationCompleted;

    final PhoneVerificationFailed verfifailed=(AuthException exception){
      print("${exception.message}");
    };
    
    await firebaseAuth.verifyPhoneNumber(
     phoneNumber: this.phoneNo,
     codeAutoRetrievalTimeout: autoRetrieval,
     codeSent: smsCodeSent,
     timeout: const Duration(seconds: 5),
     verificationCompleted: verifiedSuccess,
     verificationFailed: verfifailed
    );
  }

```

method for authentication with phone number

```
signIn()async{
    AuthCredential credential= PhoneAuthProvider.getCredential(
      verificationId: verificationId,
      smsCode: smsCode
    );
    FirebaseUser firebaseUser=await  firebaseAuth.signInWithCredential(credential).then((user){
       Navigator.of(context).pushReplacementNamed('/homepage');
         print('signed in with phone number successful: user -> $user');
    }).catchError((onError){
      print(onError);
    });
  }
```
Here ,the exception that i have getting

`
Unhandled Exception: type '(FirebaseUser) => Null' is not a subtype of type '(AuthCredential) => void' in type cast
`

**Comment by mannprerak2** [comment] 2019-08-07 08:48
Hi Shruti,
You need to change the function signature for **verifiedSuccess** to this
```dart
final PhoneVerificationCompleted verifiedSuccess = (AuthCredential phoneAuthCredential){
    print("verified");
}
```
**You can use the phoneAuthCredentials to sign in or link it to an existing user**
```dart
    // sign in with creds
    FirebaseUser firebaseUser=await  firebaseAuth.signInWithCredential(credential).then((
    
    // or link this phone with existing user
    await user.linkWithCredential(phoneAuthCredential);
}
```

**Comment by iapicca** [comment] 2020-01-17 07:28
Hi @shrutiramnandan  
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-17 07:28 UTC
Labels: severe: performance
