### ISSUE TITLE
xcodebuild: error: Unable to find a destination matching the provided destination specifier

### ISSUE THREAD

**Issue by krjw-eyev** [flutter/flutter#107776] opened 2022-07-16 13:58 UTC
When trying to run on my device I get the following error:

```
Running "flutter pub get" in barber_time...
Launching lib/main.dart on <my devices name> in debug mode...
Signing iOS app for device deployment using developer identity: ""
Xcode build done.                                           31.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-07-16 15:47:53.523 xcodebuild[28422:4999890] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-07-16 15:47:53.524 xcodebuild[28422:4999890] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    xcodebuild: error: Unable to find a destination matching the provided destination specifier:
    		{ id:<my devices id>}
    	The requested device could not be found because no available devices matched the request.
    	Available destinations for the "Runner" scheme:
        <List of simulators omitted>
    	Ineligible destinations for the "Runner" scheme:
    		{ platform:iOS, id:<my devices id>, name:<my devices name>, error:Device is busy (Preparing the watch for development via <my devices name>) }
Could not build the precompiled application for the device.
════════════════════════════════════════════════════════════════════════════════
Building a deployable iOS app requires a selected Development Team with a 
Provisioning Profile. Please ensure that a Development Team is selected by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again

For more information, please visit:
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════

Error launching application on iKw.
Exited

```

This is not a signing error!!! I have checked my signing and I can build and launch my app from Xcode and I have been able to launch my app from VSCode / Terminal but I get this error now really frequently.

What I have tried:

* Rebooting device -> worked a couple of times but issue returns
* Rebooting MacOS -> did not work.
* Turning off my Apple Watch -> This seems to help since this is clearly the error stating my device is an "ineligable destination"...

My question is why does it work with Xcode, why does Xcode does not show that my device is busy preparing my watch and how do I resolve this?

**Comment by maheshmnj** [comment] 2022-07-18 08:56
Looks similar to https://github.com/flutter/flutter/issues/95117

**Comment by huycozy** [comment] 2022-07-18 09:16
Hi @krjw-eyev 
Based on your logs, it's very similar to issue #95117. Please try to provide information corresponding to hints from #95117's comments:

- Please provide the output of `flutter doctor -v`. In case your Flutter version is old, try running the project on the latest stable Flutter version `3.0.5` and master `3.1.0` to see if the issue still reproduces.
- Check [this SO thread](https://stackoverflow.com/questions/46316373/fixing-xcode-9-issue-iphone-is-busy-preparing-debugger-support-for-iphone) and try all provided solutions in there.

Thank you!

**Comment by maheshmnj** [comment] 2022-07-18 12:16
@krjw-eyev for now you will have to work around by rebooting your apple watch when you hit this issue. Looks like this a bug from Xcode and flutter can't do much about it see https://github.com/flutter/flutter/issues/95117#issuecomment-995094721

**Comment by maheshmnj** [comment] 2022-07-18 12:17
Closing as this issue is not related to flutter.

**Closed by maheshmnj** 2022-07-18 12:17 UTC
Labels: in triage
