### ISSUE TITLE
I'm facing issue in Shared preferences with Desktop

### ISSUE THREAD

**Issue by hariom-dev** [flutter/flutter#50337] opened 2020-02-07 15:30 UTC
I'm facing issue with Shared preferences with Desktop.
I got error every time when i run code on windows and linux machine.
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

**Comment by stuartmorgan** [comment] 2020-02-07 16:32
That plugin isn't implemented for Windows or Linux yet. Duplicate of #41719 and #41720

I would recommend reading the notes about plugins [here](https://github.com/flutter/flutter/wiki/Desktop-shells); this will happen with almost any plugin you use on Windows or Linux at this point.

**Closed by stuartmorgan** 2020-02-07 16:32 UTC
