### ISSUE TITLE
Firebase Authentication error in Flutter Web

### ISSUE THREAD

**Issue by withdurrani** [flutter/flutter#47276] opened 2019-12-18 03:38 UTC
I am getting the error **_Expected a value of type 'String', but got one of type 'AssertionErrorImpl'_** while attempting to sign in using the FirebaseAuth.

Below is my code:

`AuthResult result = await FirebaseAuth.instance.signInWithEmailAndPassword(email: email, password: password);`

**Comment by iapicca** [comment] 2019-12-19 12:35
Hi @withdurrani 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-19 12:35 UTC
