### ISSUE TITLE
Camera Package Issues

### ISSUE THREAD

**Issue by Pianisimo** [flutter/flutter#29500] opened 2019-03-17 04:53 UTC
First thanks for reading, and sorry for not following the format.
I'm having three problems with the camera package testing on my pixel 2.
1. Every photo I take has the same resolution with the three different resolution presets.
`_cameraController = CameraController(cameraDescription, ResolutionPreset.high);`
2. The PreviewWidget shows incorrect orientation when I switch to landscape mode.
3. When trying to correct the orientation by rotating the widget manually I am missing information since 
the `_cameraController.description.sensorOrientation ` always gives me a value of 90 when using the front facing camera, and a value of 270 when using the rear camera, this values are independent of the device orientation, I tried Disposing and/or initiating a new instance of the cameraController every time the` _cameraController.description` could change but, the values of 90 and 270 seems constant values to me.

**Comment by keitoro** [comment] 2019-03-19 10:32
I have noticed the same issue with the rotation to landscape mode. Even when I start the android emulator I see that the preview is 90 rotated for some reason. I have been on this for the past two days but nothing seems to fix that rotation issue. On an iPhone device, I noticed that the preview image is being stretched and it is rotated. It sounds weird to me that one of the most important functions of a phone is not being taken care of in a new programming language. Or are we doing something wrong here?

**Comment by Pianisimo** [comment] 2019-03-19 15:20
@keitoro Have you experienced the resolution and the orientation sensor issues as well?

**Comment by keitoro** [comment] 2019-03-19 15:26
@Pianisimo not the resolution issue. I have not yet tested that. Net to this i have also the xcode profile singing issue that is keeping me busy or the  Fatal signal 11 lol.

**Comment by keitoro** [comment] 2019-03-21 11:18
I have been looking into this issue and one thing I have noticed is that this code 
class CameraDescription {
  CameraDescription({this.name, this.lensDirection, this.sensorOrientation});

  final String name;
  final CameraLensDirection lensDirection;

  /// Clockwise angle through which the output image needs to be rotated to be upright on the device screen in its native orientation.
  ///
  /// **Range of valid values:**
  /// 0, 90, 180, 270
  ///
  /// On Android, also defines the direction of rolling shutter readout, which
  /// is from top to bottom in the sensor's coordinate system.
  final int sensorOrientation;

  @override
  bool operator ==(Object o) {
    return o is CameraDescription &&
        o.name == name &&
        o.lensDirection == lensDirection;
  }

  @override
  int get hashCode {
    return hashValues(name, lensDirection);
  }

  @override
  String toString() {
    return '$runtimeType($name, $lensDirection, $sensorOrientation)';
  }
}
does nothing. I have been trying to update it by hardcoding and does nothing. It is tally frustrating.

**Comment by keitoro** [comment] 2019-03-21 11:31
I assume that is a simple solution to this and that is to lock the CameraPreview from rotating. As when you make a picture in landscape mode it does turn out to be a normal picture in my case. it is just that preview that is getting distorted when you rotate the device. If that widget can be locked it should all work as intended. It is just a fix until there is more to go on.

**Comment by keitoro** [comment] 2019-03-21 11:46
I have added the following code to main.dart to lock the screen rotation

SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
      ]);

it solves that cameraPreview from rotating and the screen looks normal.

**Comment by Pianisimo** [comment] 2019-03-21 12:54
I guess that works, but to be honest taking pictures or recording videos in portrait mode seems wrong to me, all the tvs and monitor are designed for wider media.

**Comment by keitoro** [comment] 2019-03-21 13:01
Well, it depends on what your camera should do. You can still rotate phone only the widgets won't turn.  I am also going to try another solution with a rotate widget. However, this is really some bug they should solve fast as this is something that one of the most important part of an app (often).

**Comment by quentinleguennec** [comment] 2019-04-05 15:10
Hi @Pianisimo @keitoro 
I added a way to control video and picture capture quality on botha iOS and Android
You can check the PR here:
flutter/plugins#1403
Suggestions are welcome. Don't hesitate to leave a comment to push the review process if that works for you.

I have also been working on fixing video orientation on iOS (which is pretty complicated because metadata are handle differently on different platform and different video players). I'm in the process of creating a new PR for this and will keep you updated.

**Comment by quentinleguennec** [comment] 2019-04-05 17:47
I added a fix for video orientation metadata when recording a video with the camera plugin. The PR is this one: flutter/plugins#1452
I also added a fix to the video_player. The PR is here: flutter/plugins#1451
Please don't hesitate to have a look at the PRs and leave comments or suggestions to push the review process.

**Comment by haamaanaa** [comment] 2019-12-05 14:47
I also stumbled upon this issue [value of 90 when using the front facing camera, and a value of 270 when using the rear(selfie) camera]

I am required to have external camera feed as well, that's why functional camera orientation values would be extremely important to have so that video / image orientation would be correct.

**Comment by stuartmorgan** [comment] 2021-04-24 13:03
Having multiple unrelated bugs in one issue makes it impossible to effectively; given that, closing this issue. (For instance, it looks like a fix landed for at least one, but the state of each piece is unclear.)

If you are still experiencing any of the problem described here, please file a new individual issue for each one, following the issue template.

**Closed by stuartmorgan** 2021-04-24 13:03 UTC
Labels: p: camera, plugin
