### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null after release build

### ISSUE THREAD

**Issue by ultamatum** [flutter/flutter#93321] opened 2021-11-09 15:09 UTC
## Steps to Reproduce

1. Execute `flutter build web --release` on the code sample 
2. Run the built web release (I've been using firebase / live server extension for vscode)

**Expected results:** 

Expected my project to load as it does when I use `flutter run`

**Actual results:** 

Website opens, background colour loads and then I get various errors detailed below

Starts with:
`TypeError: Instance of 'minified:iO': type 'minified:iO' is not a subtype of type 'minified:dy'`

Then it spams: 
`Uncaught TypeError: Cannot read properties of null (reading 'x')`

Full log available here: https://gist.github.com/ultamatum/09dc6915f6b3b7e61a443ff2e6cb2f15

<details>
<summary>Code sample</summary>

Code sample is below, also available at: https://github.com/ultamatum/website/tree/Crash-Example

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Alexander Gray',
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Center(
          child: ListView(
            physics: const BouncingScrollPhysics(),
            children: [
              Expanded(
                child: Container(
                  padding: const EdgeInsets.only(top: 95),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      Text(
                        'Alexander Gray',
                        textAlign: TextAlign.center,
                        style: Theme.of(context).textTheme.headline3!.copyWith(
                              color: Theme.of(context).primaryColor,
                              fontSize: 48,
                              fontWeight: FontWeight.bold,
                            ),
                      ),
                    ],
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

See https://gist.github.com/ultamatum/09dc6915f6b3b7e61a443ff2e6cb2f15 as it's very long

```
flutter analyze
Analyzing website...                                                    
No issues found! (ran in 1.1s)
```

```
flutter doctor -v
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on Pop!_OS 21.10 5.15.0-76051500-generic, locale en_US.UTF-8)
    • Flutter version 2.6.0-11.0.pre at /home/ultamatum/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (8 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /home/ultamatum/Development/Android
    • Platform android-31, build-tools 32.0.0-rc1
    • ANDROID_HOME = /home/ultamatum/Development/Android
    • Java binary at: /home/ultamatum/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/ultamatum/Development/android-studio
    • Flutter plugin version 62.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.10 5.15.0-76051500-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

Thanks in advance as it's more than likely a dumb issue. Let me know if there's anything more I can give

**Comment by darshankawar** [comment] 2021-11-10 08:02
@ultamatum 
Looking at the log you provided, I think you are hitting https://github.com/flutter/flutter/issues/78041. If you go through the comment thread in it, it seems to be causing due to the way dart is handling `Type.toString()`, because on the web, `Type.toString` returns something like `minified:xy` which is what you are seeing in the logs. There's an open issue in dart for this: https://github.com/dart-lang/sdk/issues/46373 in which you can track the status.

**Comment by ultamatum** [comment] 2021-11-10 15:41
@darshankawar 

Thanks for the response, looking through them and as you said it seems to be part of how dart deals with `Type.toString()` however I'm looking through my code to see where would be using `Type.toString()` and I couldn't find anything.

However when I removed the expanded widget I was using it seems to have went away, which should be fine for now.

**Comment by darshankawar** [comment] 2021-11-11 06:23
Thanks for digging in and identifying root cause. Considering the original issue you reported isn't there anymore, I will close it for now based on above comment. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-11-11 06:23 UTC
Labels: in triage
