### ISSUE TITLE
Crash on iOS when interacting with TextField, possibly related to embedded UIKit views

### ISSUE THREAD

**Issue by b4tchkn** [flutter/flutter#135343] opened 2023-09-23 02:47 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This issue is the same as https://github.com/flutter/flutter/issues/128846.
The previous issue is closed and cannot be commented on, so a new issue is being created.
Is this resolved in Flutter 3.13.5?
The original issue content is listed below.

In a prior version of my production iOS app:

1: Run the app in profile mode on a physical device (I used an iPhone 13 mini but the app has crashed on customer iOS devices of all different models, and on iPad as well).
2: Increase dynamic type size to 160%.
3: Tap on the text field to bring up the keyboard.
4: Tap the text field's icon (specified by TextField.decoration), which is within a gesture recognizer and hides the keyboard again.
5: Repeatedly and rapidly tap on the center of the text field's icon, and slowly move your finger to the right, from the center of the icon towards the text field. Try to move your finger no more than a few pixels at a time.
6: If the keyboard appears, repeat from step 4. Eventually, the app crashes before tapping close enough to the text field to focus it and display the keyboard.

I have not been able to reproduce this crash in anything less than my production app (it will not reproduce in any of the samples I created, see "code sample" for more information). I believe this is because the crashes are related to the use of the google_mobile_ads AdMob pub plugin. See the "code sample" section for more information.

https://github.com/flutter/flutter/issues/127789 looks related, but at present lacks some required information to be actionable.

### Expected results

When following the steps to reproduce, I expect my app to hide and show the keyboard, to focus and unfocus the text field, but not to crash.

### Actual results

The app crashes. I have attached the following below:

Console output from reproducing the crash in my production app.
A minimally-redacted, fully-symbolicated iOS crash report from a real production user where my app crashed due to this issue.

### Code sample

As I said above, I cannot at the moment reproduce the issue with this code sample, only with my production app. However, this sample is intended to replicate as closely as possible the configuration of my production app, replacing the ad view with a web view. Please reference this code sample while reading the steps to reproduce.

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  final _controller = TextEditingController();
  final _focus = FocusNode();

  final _webViewController = WebViewController()
    ..loadRequest(Uri.parse("https://www.google.com"));

  @override
  void initState() {
    _controller.addListener(() {
      setState(() {});
    });
    super.initState();
  }

  void onSubmit() {
    setState(() {
      _focus.unfocus();
      _controller.text = '';
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: Container(
          alignment: Alignment.center,
          padding: const EdgeInsets.all(16),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              TextField(
                controller: _controller,
                focusNode: _focus,
                decoration: InputDecoration(
                  icon: ExcludeSemantics(
                    child: GestureDetector(
                      onTap: onSubmit,
                      child: const Icon(Icons.add),
                    ),
                  ),
                  hintText: 'A long string for the hint text of the text field',
                  border: const OutlineInputBorder(),
                  contentPadding:
                      const EdgeInsets.only(left: 16.0, right: 36.0),
                ),
                textCapitalization: TextCapitalization.words,
                onSubmitted: (_) => onSubmit,
              ),
              SizedBox(height: 400),
              SizedBox(
                height: 100,
                child: WebViewWidget(controller: _webViewController),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-US)
    • Flutter version 3.10.4 on channel stable at /Users/roysianez/Desktop/Bug/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (8 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/roysianez/Library/Android/sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.79.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)            
    • Roy’s iPhone 13 (mobile) • 00008110-000C644802DB801E • ios            • iOS 16.5 20F66
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2023-09-25 08:13
Hi @b4tchkn 
I re-visited #128846 and saw me there since the last time. I checked this issue again on my physical device (iPhone 7, iOS 15.7.9) but can't reproduce it (still stuck at step 5 to step 6). So if you can provide a recorded video for reproducing steps, it would be helpful.

<details>
<summary>Demo video when checking on Flutter master channel</summary>

https://github.com/flutter/flutter/assets/104349824/10b41f4b-4a89-409b-972d-ea842f73b0c8
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (5 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.15.0-7.0.pre.2, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.15.0-7.0.pre.2 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master.
      Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master.
      Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f56288a4e (2 hours ago), 2023-09-24 18:49:07 -0700
    • Engine revision 2daf5e7bb2
    • Dart version 3.2.0 (build 3.2.0-191.0.dev)
    • DevTools version 2.28.0-dev.12
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by b4tchkn** [comment] 2023-09-26 03:17
I'm sorry.
I just observed the same error on my project Sentry before and was not able to reproduce it.
I would like to request a video recording from the original reporter of the issue, @roy-sianez , if possible.

**Comment by darshankawar** [comment] 2023-09-26 05:46
@b4tchkn 
It may be similar / related to https://github.com/flutter/flutter/issues/131999 that you can check and confirm.

**Comment by b4tchkn** [comment] 2023-09-27 04:28
@darshankawar 
Thanks for responding.
What do you think #131999  has in common with this issue?
Is #128846 really solved?

**Comment by huycozy** [comment] 2023-09-27 05:56
>I just observed the same error on my project Sentry before and was not able to reproduce it.

@b4tchkn Could you share the entire crash stack trace? If the log is too long, please save it into a file and attach it here. 

Also, please provide the list of affected device info and the percentage occurrence of the crash. Thanks!

**Comment by b4tchkn** [comment] 2023-09-27 12:40
クラッシュ発生率は1.45%でした。

それぞれ発生が多い順でソートされています
デバイスのリスト
iOSのリスト

**Comment by b4tchkn** [comment] 2023-09-27 12:48
Crash rate was 1.45%.

- List of iOS devices (in order of most frequent occurrence)
  - iPhone 8
  - iPhone 7
  - Phone SE (2nd generation)
  - iPhone XR
  - iPhone 11
  - iPhone 6s
  - iPhone SE (1st generation)
  - iPhone X
  - iPhone 13
  - iPhone 12

- List of iOS versions (in order of occurrence)
  - iOS 16.5.1
  - iOS 15.7.7
  - iOS 15.7.6
  - iOS 16.3.1
  - iOS 16.1.1
  - iOS 16.2
  - iOS 15.5
  - iOS 14.8.1
  - iOS 16.5
  - iOS 15.6.1

StackTrace
<img width="861" alt="スクリーンショット 2023-09-27 21 46 53" src="https://github.com/flutter/flutter/assets/28699251/69b41682-f836-419a-b63b-362f73f8cb3f">

**Comment by huycozy** [comment] 2023-09-28 04:58
@b4tchkn Please share the entire crash stack trace in text format instead of a screenshot for better investigation. Thanks!

**Comment by b4tchkn** [comment] 2023-09-28 05:49
@huycozy Sorry. Corrected stack trace to text format.
When I check https://github.com/flutter/flutter/issues/128846, the following stack traces are very similar, can I assume that this is the same problem?

```
Last Exception Backtrace:
0   CoreFoundation                	0x1c9c1948c __exceptionPreprocess + 160 (NSException.m:202)
1   libobjc.A.dylib               	0x1c2f05050 objc_exception_throw + 56 (objc-exception.mm:356)
2   CoreFoundation                	0x1c9da8420 _CFThrowFormattedException + 104 (CFObject.m:2235)
3   CoreFoundation                	0x1c9da4e1c -[__NSArrayM insertObject:atIndex:].cold.1 + 48 (NSArrayM.m:164)
4   CoreFoundation                	0x1c9c23764 -[__NSArrayM insertObject:atIndex:] + 888 (NSArrayM.m:164)
5   Flutter                       	0x101015420 flutter::IOSExternalViewEmbedder::SubmitFrame(GrDirectContext*, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::SurfaceFrame, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::SurfaceFrame>>) (in Flutter) + 5204
6   Flutter                       	0x1013bd800 flutter::Rasterizer::DrawToSurfaceUnsafe(flutter::FrameTimingsRecorder&, flutter::LayerTree&) (in Flutter) + 1308
7   Flutter                       	0x1013bda58 std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&)::$_1, std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&)::$_1>, void ()>::destroy_deallocate() (in Flutter) + 0
8   Flutter                       	0x1012c4ae8 fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const (in Flutter) + 52
9   Flutter                       	0x1013bd174 flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&) (in Flutter) + 264
10  Flutter                       	0x1013be9a0 std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::Rasterizer::Draw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>> const&, std::_LIBCPP_ABI_NAMESPACE::function<bool (flutter::LayerTree&)>)::$_1, std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::Rasterizer::Draw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>> const&, std::_LIBCPP_ABI_NAMESPACE::function<bool (flutter::LayerTree&)>)::$_1>, void (std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::LayerTreeItem, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::LayerTreeItem>>)>::operator()(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::LayerTreeItem, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::LayerTreeItem>>&&) (in Flutter) + 240
11  Flutter                       	0x1013bdc98 flutter::Rasterizer::Draw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>> const&, std::_LIBCPP_ABI_NAMESPACE::function<bool (flutter::LayerTree&)>) (in Flutter) + 416
12  Flutter                       	0x1013be680 std::_LIBCPP_ABI_NAMESPACE::__function::__func<fml::internal::CopyableLambda<flutter::Rasterizer::Draw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>> const&, std::_LIBCPP_ABI_NAMESPACE::function<bool (flutter::LayerTree&)>)::$_0>, std::_LIBCPP_ABI_NAMESPACE::allocator<fml::internal::CopyableLambda<flutter::Rasterizer::Draw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>> const&, std::_LIBCPP_ABI_NAMESPACE::function<bool (flutter::LayerTree&)>)::$_0>>, void ()>::operator()() (in Flutter) + 116
13  Flutter                       	0x1012c3120 fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) + 548
14  Flutter                       	0x1012c644c fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) + 12
15  CoreFoundation                	0x1c9cd1c1c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28 (CFRunLoop.c:1797)
16  CoreFoundation                	0x1c9c92e64 __CFRunLoopDoTimer + 884 (CFRunLoop.c:2402)
17  CoreFoundation                	0x1c9c3c17c __CFRunLoopDoTimers + 284 (CFRunLoop.c:2560)
18  CoreFoundation                	0x1c9c8563c __CFRunLoopRun + 1940 (CFRunLoop.c:3120)
19  CoreFoundation                	0x1c9c89da0 CFRunLoopRunSpecific + 584 (CFRunLoop.c:3418)
20  GraphicsServices              	0x200faf998 GSEventRunModal + 160 (GSEvent.c:2196)
21  UIKitCore                     	0x1cbf1efd8 -[UIApplication _run] + 868 (UIApplication.m:3782)
22  UIKitCore                     	0x1cbf1ec50 UIApplicationMain + 312 (UIApplication.m:5372)
23  Runner                        	0x10003fbf8 main + 64 (AppDelegate.swift:5)
24  dyld                          	0x1e7407344 start + 1860 (dyldMain.cpp:1165)
```

**Comment by huycozy** [comment] 2023-09-28 11:49
Thanks for your update. Maybe related/similar: https://github.com/flutter/flutter/issues/134106

**Comment by cyanglaz** [comment] 2023-09-28 14:49
Closing as I think it is dup of https://github.com/flutter/flutter/issues/134106
If you could find any reliable way to reproduce this, please leave a comment at https://github.com/flutter/flutter/issues/134106

**Closed by cyanglaz** 2023-09-28 14:49 UTC
Labels: a: text input, c: crash, platform-ios, engine, a: platform-views, a: production, team-ios
