### ISSUE TITLE
The following ProviderNotFoundException was thrown building Wrapper(dirty): Error: Could not find the correct Provider<User> above this Wrapper Widget

### ISSUE THREAD

**Issue by mrgandy** [flutter/flutter#88247] opened 2021-08-15 18:38 UTC
## Steps to Reproduce

1. Run `flutter run`.

**Expected results:**
App should run.

**Actual results:**
```
I/flutter (17194): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17194): The following ProviderNotFoundException was thrown building Wrapper(dirty):
I/flutter (17194): Error: Could not find the correct Provider<User> above this Wrapper Widget
I/flutter (17194): 
I/flutter (17194): This happens because you used a `BuildContext` that does not include the provider
I/flutter (17194): of your choice. There are a few common scenarios:
I/flutter (17194): 
I/flutter (17194): - You added a new provider in your `main.dart` and performed a hot-reload.
I/flutter (17194):   To fix, perform a hot-restart.
I/flutter (17194): 
I/flutter (17194): - The provider you are trying to read is in a different route.
I/flutter (17194): 
I/flutter (17194):   Providers are "scoped". So if you insert of provider inside a route, then
I/flutter (17194):   other routes will not be able to access that provider.
I/flutter (17194): 
I/flutter (17194): - You used a `BuildContext` that is an ancestor of the provider you are trying to read.
I/flutter (17194): 
I/flutter (17194):   Make sure that Wrapper is under your MultiProvider/Provider<User>.
I/flutter (17194):   This usually happens when you are creating a provider and trying to read it immediately.
I/flutter (17194): 
I/flutter (17194):   For example, instead of:
I/flutter (17194): 
I/flutter (17194):   ```
I/flutter (17194):   Widget build(BuildContext context) {
I/flutter (17194):     return Provider<Example>(
I/flutter (17194):       create: (_) => Example(),
I/flutter (17194):       // Will throw a ProviderNotFoundError, because `context` is associated
I/flutter (17194):       // to the widget that is the parent of `Provider<Example>`
I/flutter (17194):       child: Text(context.watch<Example>()),
I/flutter (17194):     ),
I/flutter (17194):   }
I/flutter (17194):   ```
I/flutter (17194): 
I/flutter (17194):   consider using `builder` like so:
I/flutter (17194): 
I/flutter (17194):   ```
I/flutter (17194):   Widget build(BuildContext context) {
I/flutter (17194):     return Provider<Example>(
I/flutter (17194):       create: (_) => Example(),
I/flutter (17194):       // we use `builder` to obtain a new `BuildContext` that has access to the provider
I/flutter (17194):       builder: (context) {
I/flutter (17194):         // No longer throws
I/flutter (17194):         return Text(context.watch<Example>()),
I/flutter (17194):       }
I/flutter (17194):     ),
I/flutter (17194):   }
I/flutter (17194):   ```
I/flutter (17194): 
I/flutter (17194): If none of these solutions work, consider asking for help on StackOverflow:
I/flutter (17194): https://stackoverflow.com/questions/tagged/flutter
I/flutter (17194): 
I/flutter (17194): The relevant error-causing widget was:
I/flutter (17194):   Wrapper file:///Users/gandy37/StudioProjects/chronic_illness/lib/main.dart:24:15
I/flutter (17194): 
I/flutter (17194): When the exception was thrown, this was the stack:
I/flutter (17194): #0      Provider._inheritedElementOf (package:provider/src/provider.dart:332:7)
I/flutter (17194): #1      Provider.of (package:provider/src/provider.dart:284:30)
I/flutter (17194): #2      Wrapper.build (package:chronicillness/screens/wrapper.dart:35:33)
I/flutter (17194): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4648:28)
I/flutter (17194): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
I/flutter (17194): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (17194): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
I/flutter (17194): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
I/flutter (17194): ...     Normal element mounting (166 frames)
I/flutter (17194): #173    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
I/flutter (17194): #174    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
I/flutter (17194): #175    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:32)
I/flutter (17194): ...     Normal element mounting (339 frames)
I/flutter (17194): #514    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
I/flutter (17194): #515    Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
I/flutter (17194): #516    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
I/flutter (17194): #517    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:456:11)
I/flutter (17194): #518    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
I/flutter (17194): #519    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
I/flutter (17194): #520    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
I/flutter (17194): #521    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:356:11)
I/flutter (17194): ...     Normal element mounting (7 frames)
I/flutter (17194): #528    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
I/flutter (17194): ...     Normal element mounting (7 frames)
I/flutter (17194): #535    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
I/flutter (17194): #536    Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
I/flutter (17194): #537    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1189:16)
I/flutter (17194): #538    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1159:5)
I/flutter (17194): #539    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1104:18)
I/flutter (17194): #540    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
I/flutter (17194): #541    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1103:13)
I/flutter (17194): #542    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:937:7)
I/flutter (17194): #543    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:917:7)
I/flutter (17194): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (17194): 
I/flutter (17194): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/TransportRuntime.CctTransportBackend(17194): Status Code: 200
I/TransportRuntime.CctTransportBackend(17194): Content-Type: application/json; charset=UTF-8
I/TransportRuntime.CctTransportBackend(17194): Content-Encoding: gzip
```

<details>
  <summary>Logs</summary>

```
[flutter-verbose.txt](https://github.com/flutter/flutter/files/6988659/flutter-verbose.txt)
[flutter-analyze.txt](https://github.com/flutter/flutter/files/6988664/flutter-analyze.txt)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/gandy37/Development/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gandy37/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • VS996 (mobile)  • VS996ca291eca • android-arm64  • Android 9 (API 28)
    • macOS (desktop) • macos         • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome        • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

My main.dart:

```dart
import 'package:firebase_core/firebase_core.dart';
import 'package:chronicillness/models/user.dart';
import 'package:chronicillness/services/auth.dart';
import 'package:flutter/material.dart';
import 'package:chronicillness/screens/wrapper.dart';
import 'package:provider/provider.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<User?>(
      create: (_) => AuthService().user,
      initialData: null,
      child: MaterialApp(
        home: Wrapper(),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}


```

My pubspec.yaml:

```dart
name: chronicillness
description: A Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_screenutil: ^5.0.0+2
  polygon_clipper: ^1.0.2
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  flutter_material_color_picker: ^1.1.0+1
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  intl: ^0.17.0
  timeago: ^3.1.0
  url_launcher: ^6.0.9
  charts_flutter: ^0.11.0
  flutter_slidable: ^0.6.0
  firebase_crashlytics: ^2.1.1
  firebase_core: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pain/
```

**Comment by darshankawar** [comment] 2021-08-16 11:14
@mrgandy 
The log you provided points to potential issue and suggests you to try solutions:
```

I/flutter (17194): This happens because you used a `BuildContext` that does not include the provider
I/flutter (17194): of your choice. There are a few common scenarios:
I/flutter (17194): 
I/flutter (17194): - You added a new provider in your `main.dart` and performed a hot-reload.
I/flutter (17194):   To fix, perform a hot-restart.
I/flutter (17194): 
I/flutter (17194): - The provider you are trying to read is in a different route.
I/flutter (17194): 
I/flutter (17194):   Providers are "scoped". So if you insert of provider inside a route, then
I/flutter (17194):   other routes will not be able to access that provider.
I/flutter (17194): 
I/flutter (17194): - You used a `BuildContext` that is an ancestor of the provider you are trying to read.
I/flutter (17194): 
I/flutter (17194):   Make sure that Wrapper is under your MultiProvider/Provider<User>.
I/flutter (17194):   This usually happens when you are creating a provider and trying to read it immediately.
I/flutter (17194): 
I/flutter (17194):   For example, instead of:
I/flutter (17194): 
I/flutter (17194):   ```
I/flutter (17194):   Widget build(BuildContext context) {
I/flutter (17194):     return Provider<Example>(
I/flutter (17194):       create: (_) => Example(),
I/flutter (17194):       // Will throw a ProviderNotFoundError, because `context` is associated
I/flutter (17194):       // to the widget that is the parent of `Provider<Example>`
I/flutter (17194):       child: Text(context.watch<Example>()),
I/flutter (17194):     ),
I/flutter (17194):   }
I/flutter (17194):   ```
I/flutter (17194): 
I/flutter (17194):   consider using `builder` like so:
I/flutter (17194): 
I/flutter (17194):   ```
I/flutter (17194):   Widget build(BuildContext context) {
I/flutter (17194):     return Provider<Example>(
I/flutter (17194):       create: (_) => Example(),
I/flutter (17194):       // we use `builder` to obtain a new `BuildContext` that has access to the provider
I/flutter (17194):       builder: (context) {
I/flutter (17194):         // No longer throws
I/flutter (17194):         return Text(context.watch<Example>()),
I/flutter (17194):       }
I/flutter (17194):     ),
I/flutter (17194):   }
I/flutter (17194):   ```
I/flutter (17194): 
I/flutter (17194): If none of these solutions work, consider asking for help on StackOverflow:
I/flutter (17194): https://stackoverflow.com/questions/tagged/flutter
```


Also, it seems to be pointing to 3rd party plugin `provider`, so it's better to ask in dedicated repo or in support channels like StackOverflow to get a solution.

Closing from here. If you think this is an issue in the framework and not in the plugin, provide a complete reproducible code sample without any 3rd party plugins along with `flutter doctor -v`, so that we can properly address it.

**Closed by darshankawar** 2021-08-16 11:14 UTC
Labels: in triage
