### ISSUE TITLE
[tool_crash] NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'Receiver: Closure: (_SyncIterator<Package>) => boolTried calling: MutablePackageTree.allPackages()Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool

### ISSUE THREAD

**Issue by SalihMertATALAY** [flutter/flutter#61151] opened 2020-07-09 09:44 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      new SimplePackageConfig (package:package_config/src/package_config_impl.dart:26:36)
#3      parsePackageConfigJson (package:package_config/src/package_config_json.dart:213:10)
#4      parsePackageConfigBytes (package:package_config/src/package_config_json.dart:45:10)
#5      readAnyConfigFile (package:package_config/src/package_config_io.dart:55:18)
<asynchronous suspension>
#6      readAnyConfigFileUri (package:package_config/src/package_config_io.dart:76:14)
#7      loadPackageConfigUri (package:package_config/package_config.dart:88:5)
#8      DartUri._loadPackageConfig (package:dwds/src/utilities/dart_uri.dart:35:30)
#9      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:57:13)
#10     AppInspector._initialize (package:dwds/src/debugging/inspector.dart:87:19)
<asynchronous suspension>
#11     AppInspector.initialize (package:dwds/src/debugging/inspector.dart:145:24)
#12     ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:165:37)
<asynchronous suspension>
#13     ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:133:23)
#14     DebugService.start (package:dwds/src/services/debug_service.dart:140:55)
#15     DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:156:25)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
```
```
[✓] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.17763.1282], locale tr-TR)
    • Flutter version 1.17.0 at D:\flutter
    • Framework revision d3ed9ec945 (3 months ago), 2020-04-06 14:07:34 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\mertt\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.45.0)
    • VS Code at C:\Users\mertt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • Redmi Note 8 Pro • qsovtc55sshqbyws • android-arm64  • Android 9 (API 28)
    • Chrome           • chrome           • web-javascript • Google Chrome 83.0.4103.116
    • Web Server       • web-server       • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: d3ed9ec945f8869f0e136c357d0c2a6be2b60c98

**Comment by VladyslavBondarenko** [comment] 2020-07-09 10:49
Duplicate of https://github.com/flutter/flutter/issues/59245

**Closed by VladyslavBondarenko** 2020-07-09 10:49 UTC
