### ISSUE TITLE
Custom Drawer Hides Behind Webview Widget

### ISSUE THREAD

**Issue by sekarvetrivel** [flutter/flutter#124117] opened 2023-04-04 13:20 UTC
Hi,
I am using webview and custom drawer in same page. custom drawer is modelroute, webview hides that modelroute. also gestureRecognizers added for webview. kindly check attached video for better details.

https://user-images.githubusercontent.com/105904147/229803393-f024d308-e18f-4b13-89b8-b725433b5d4a.mp4

code sample:
```
WebView(
                                          gestureRecognizers: Set()
                                            ..add(Factory<
                                                    OneSequenceGestureRecognizer>(
                                                () =>
                                                    EagerGestureRecognizer())),
                                          javascriptMode:
                                              JavascriptMode.unrestricted,
                                          initialUrl:
                                              "https://swapful.zodeak-dev.com/#/pro-exchange/${first}_${last}/chart?theme=dark",
                                          onWebViewCreated:
                                              (webViewController) {
                                            viewModel.webViewController =
                                                webViewController;
                                          },
                                          onPageFinished: (url) {
                                            if (viewModel.webLoad) {
                                              viewModel.webViewController?.loadUrl(
                                                  "https://swapful.zodeak-dev.com/#/pro-exchange/${first}_${last}/chart?theme=dark");
                                              viewModel.setWebLoad(false);
                                            }
                                          },
                                        ),
```

```
class FullScreenDrawer extends ModalRoute {
...
  @override
  Widget buildPage(
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
  ) {
    ...
  }
```

**Comment by exaby73** [comment] 2023-04-04 14:52
I believe this is a duplicate of https://github.com/flutter/flutter/issues/113601. Therefore, I will close this issue. If you disagree, please comment and I can reopen the issue. Thank you

**Closed** 2023-04-04 14:53 UTC
Labels: r: duplicate
