### ISSUE TITLE
Each toggle of "Select widget mode" in IntelliJ IDEA makes initState calls of widgets in builder property of WidgetsApp class

### ISSUE THREAD

**Issue by mozochek** [flutter/flutter#130385] opened 2023-07-12 06:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run code sample
2. Toggle few times "Select widget mode" button in Flutter Inspector in IntelliJ IDEA

### Expected results

String `TEST INIT STATE` prints in console 1 time.

### Actual results

String `TEST INIT STATE` prints in console as many times as "Select widget mode" button was toggled.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (context, child) {
        return Test(child: child!);
      },
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class Test extends StatefulWidget {
  const Test({
    required this.child,
    super.key,
  });

  final Widget child;

  @override
  TestState createState() => TestState();
}

class TestState extends State<Test> {
  @override
  void initState() {
    super.initState();

    print('TEST INIT STATE');
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

It is actual stable channel, but detected as 'unknown' becase of `git checkout` in sdk folder.
<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.7.12, on Microsoft Windows [Version 10.0.19045.3086], locale ru-RU)
    ! Flutter version 3.7.12 on channel unknown at Y:\SDKs\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 4d9e56e694 (3 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at Y:\SDKs\Android
    • Platform android-33-ext5, build-tools 33.0.2
    • ANDROID_HOME = Y:\SDKs\Android
    • Java binary at: Y:\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at O:\Programs\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at Y:\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at Y:\Programs\IntelliJ IDEA
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[√] Connected device (3 available)
    • NTH NX9 (mobile)  • 192.168.0.194:5555 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 114.0.1823.67

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by danagbemava-nc** [comment] 2023-07-12 08:03
Hi @mozochek, I believe this is a duplicate of https://github.com/flutter/devtools/issues/3223. 

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen this issue. 

Thank you

**Closed by danagbemava-nc** 2023-07-12 08:03 UTC
Labels: in triage
