### ISSUE TITLE
Update API doc samples for null safety

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#71503] opened 2020-12-01 21:05 UTC
We need to go through all our API docs and update the sample code to null safety.

**Comment by ZainUrRehmanKhan** [comment] 2020-12-03 06:27
I would like to help.

**Comment by goderbauer** [comment] 2020-12-08 21:34
Duplicate of https://github.com/flutter/flutter/issues/69123.

**Closed by goderbauer** 2020-12-08 21:34 UTC
Labels: P3, a: null-safety, d: api docs, documentation, framework, passed first triage
