### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by Suyleap** [flutter/flutter#76977] opened 2021-03-01 10:39 UTC
<details>
<summary>logs</summary>

```bash
E/flutter (17101): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter (17101): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (17101): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (17101): <asynchronous suspension>
E/flutter (17101): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (17101): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359:49)
E/flutter (17101): #4      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)
E/flutter (17101): #5      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:233:42)
E/flutter (17101): <asynchronous suspension>
E/flutter (17101): #6      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:297:16)
E/flutter (17101): #7      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (17101): #8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (17101): #9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (17101): #10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (17101): #11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (17101): #12     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
E/flutter (17101): #13     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (17101): #14     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (17101): #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (17101): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (17101): #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (17101): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (17101):
```

</details>

**Comment by TahaTesser** [comment] 2021-03-01 11:36
Hi @Suyleap 
Looks like a duplicate of https://github.com/flutter/flutter/issues/75224 https://github.com/flutter/flutter/issues/33393
Please follow up there, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-01 11:36 UTC
Labels: in triage
