### ISSUE TITLE
TextField in iPadOS 16.1 is abnormal when use cut, copy, paste.

### ISSUE THREAD

**Issue by JalorOo** [flutter/flutter#115649] opened 2022-11-18 12:53 UTC
When use a TextField in iPadOS 16.1, it seems abnormal.

This one is Flutter TextField: 
![S7`34ZENADMPWAJ}HV9ZF{G](https://user-images.githubusercontent.com/20612722/202708884-2f946c56-59c3-4934-8fba-ba1a5b45e513.jpg)

and this one is iOS origin component:
![3X5C4_3` F5L5~U3BXRI2D7](https://user-images.githubusercontent.com/20612722/202709184-543cacf6-b223-487c-abb4-963147b2e2cf.jpg)

compare this two picture, you can see the cut, paste, copy function can't use in the iPad keyboard.

## Steps to Reproduce

1. just announced a TextFiled, and you can see this error.

## Logs

<details>

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
✗ cmdline-tools component is missing
Run `path/to/sdkmanager --install "cmdline-tools;latest"`
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run `flutter doctor --android-licenses` to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 13.3.1)
! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```
</details>

**Comment by darshankawar** [comment] 2022-11-18 13:13
Closing this as duplicate of https://github.com/flutter/flutter/issues/102940. You may upvote it for team's attention.

**Closed by darshankawar** 2022-11-18 13:13 UTC
Labels: in triage
