### ISSUE TITLE
Flutter behind proxy

### ISSUE THREAD

**Issue by NiketanMhatre** [flutter/flutter#10362] opened 2017-05-27 09:01 UTC
## Steps to Reproduce

You have to work behind proxy to reproduce problem, means no direct access to internet to download SDK files.
## Logs

```
C:\Users\niketan.mhatre>flutter analyze
Checking Dart SDK version...
Downloading Dart SDK 1.23.0-dev.11.11...
Start-BitsTransfer : HTTP status 407: Proxy authentication is required.
At D:\CurrentProjects\Flutter\bin\internal\update_dart_sdk.ps1:44 char:19
+ Start-BitsTransfer <<<<  -Source $dartSdkUrl -Destination $dartSdkZip
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exce
   ption
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.Backgrou
   ndIntelligentTransfer.Management.NewBitsTransferCommand

Error: Unable to update Dart SDK. Retrying...
```

Waiting for 4 seconds, press CTRL+C to quit ...

## Flutter Doctor

```
C:\Users\niketan.mhatre>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK 1.23.0-dev.11.11...
Start-BitsTransfer : HTTP status 407: Proxy authentication is required.
At D:\CurrentProjects\Flutter\bin\internal\update_dart_sdk.ps1:44 char:19
+ Start-BitsTransfer <<<<  -Source $dartSdkUrl -Destination $dartSdkZip
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exce
   ption
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.Backgrou
   ndIntelligentTransfer.Management.NewBitsTransferCommand

Error: Unable to update Dart SDK. Retrying...
```

I guess I am missing some proxy setting in configuration. I couldn't locate anywhere ..I am working behind corporate proxy so my proxy URL will be like http://domain%5Cusername:password@proxyIP:proxyPort/

**Comment by sethladd** [comment] 2017-05-27 13:36
Thanks for the feedback!

**Comment by eseidelGoogle** [comment] 2017-05-27 14:43
According to https://apple.stackexchange.com/questions/166442/how-to-set-proxy-configuration-file-in-command-line setting HTTP_PROXY in the environment might work?

**Comment by NiketanMhatre** [comment] 2017-05-30 07:02
@eseidelGoogle  
I am working on windows ,also I had checked this system configuration setting for my other projects to work behind proxy. It didn't worked. 
I had to specify proxy setting in files used by applications .. like .gradle.properties(for gradle), .npmrc (for node modules).

**Comment by eseidelGoogle** [comment] 2017-05-30 13:32
Sounds like things are working now @NiketanMhatre?

FYI @goderbauer

**Comment by goderbauer** [comment] 2017-05-30 17:07
We are using Windows' build-in [BitTransfer](https://technet.microsoft.com/en-us/itpro/powershell/windows/bitstransfer/start-bitstransfer) Tool to do the download. According to the docs, it should detect proxies automatically, if those are configured properly for that. We currently don't provide a mechanism to manually configure a proxy server. However, you could play with the proxy parameters mentioned in the BitTransfer docs (example 9) above and add them to this line to potentially make it work: https://github.com/flutter/flutter/blob/master/bin/internal/update_dart_sdk.ps1#L44

Let me know, which parameters worked for you. Also, after you get passed that point, you'll probably also have to configure the proxy for pub: https://www.dartlang.org/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

**Comment by Hixie** [comment] 2018-03-03 00:48
Dupe of https://github.com/flutter/flutter/issues/10903.

**Closed by Hixie** 2018-03-03 00:48 UTC
Labels: dev: tool

**Comment by nathanbrizzee** [comment] 2019-07-11 19:40
I know this issue has been closed, but it doesn't work for me behind our corporate proxy.  Even though I have my environment variables (http_proxy, https_proxy, no_proxy) set, it still doesn't work. I found a way to make it work, but I have to modify  /bin/internal/update_dart_sdk.ps1.

I had to modify it like this:
In the Try catch block for invoking BITS Transfer, I changed the Catch block that invokes Webrequest to specify the proxy and then to use the default credentials set up in Windows.
(IP address has been changed for this post)

Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip **-Proxy "10.1.1.100:8080" -ProxyUseDefaultCredentials**


Here is the full Try Catch block that I substitute out after I manually do a git pull --force on the flutter folder: .
`Try {`
`   Import-Module BitsTransfer`
`    Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip`
`}`
`Catch {`
`    Write-Host "Downloading the Dart SDK using the BITS service failed, retrying with WebRequest..."`
`    If($httpProxy = ([System.Uri] $env:http_proxy)){`
`        Write-Host "Using proxy settings for webrequest."`
`        Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip -Proxy "10.1.1.100:8080" -ProxyUseDefaultCredentials`
`    }Else{`
`        Write-Host "Proxy not detected for webrequest"`
`        Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip`
`    }`
`}`


I know this isn't preferred, but it was the only way I could get it to work with our Proxy server.  The implementation could be a little cleaner. This is a quick hack to get it to work.

Here is the output I get when running flutter doctor: (protecting sensitive data with XXXX).

C:\src\flutter>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 54ad777fd29b031b87c7a68a6637fb48c0932862...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest :
Access Denied (authentication_failed)
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your
credentials can be verified.
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
For assistance, please provide the Service Desk with a Screen Shot (ALT+Print Screen) of this message.
E-Mail: XXXXXXXXXX@XXXXX.XXXX.XXX
Phone: 1-XXX-XXX-XXXX
Client-IP: 10.1.X.XUsername:
Category: Content ServersURL: tcp://storage.googleapis.com:443/
Browser: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.17134.765
At C:\src\flutter\bin\internal\update_dart_sdk.ps1:62 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Error: Unable to update Dart SDK. Retrying...

Waiting for 4 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? y

C:\src\flutter>
