### ISSUE TITLE
ReorderableListView throws RenderFlex exception while dragging on latest stable and master

### ISSUE THREAD

**Issue by aleripe** [flutter/flutter#83224] opened 2021-05-23 17:41 UTC
Hi, `ReorderableListView` widget shows a strange behavior while dragging a card with a nested `ListView` inside. It suddendly overflows, as you can see in the attached reproducible sample.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Reorderable cards',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Reorderable cards'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ReorderableListView.builder(
        itemCount: 10,
        itemBuilder: (context, index) {
          return Container(
            key: ValueKey(index),
            child: Card(
              child: InkWell(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    ListTile(
                      title: Padding(
                        child: Text('Title'),
                        padding: const EdgeInsets.only(top: 8),
                      ),
                      subtitle: Text('Subtitle'),
                    ),
                    Padding(
                      padding: const EdgeInsets.fromLTRB(16, 8, 16, 0),
                      child: ListView.builder(
                        shrinkWrap: true,
                        physics: ClampingScrollPhysics(),
                        itemCount: 3,
                        itemBuilder: (context, index) {
                          return Text('Other data');
                        },
                      ),
                    ),
                  ],
                ),
                onTap: () => null,
              ),
            ),
          );
        },
        onReorder: (oldIndex, newIndex) => null,
      ),
    );
  }
}
```

```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Versione 10.0.19042.985], locale it-IT)
    • Flutter version 2.2.0 at C:\flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/Alessandro/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/Alessandro/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Alessandro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (4 available)
    • LG H930 (mobile)            • LGH9308e11f266 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554  • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome         • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge           • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!
```

**Comment by 111mma** [comment] 2021-05-23 19:38
fdd

**Comment by Nomeleel** [comment] 2021-05-24 11:27
ListView needs to set “primary” as false.

**Comment by aleripe** [comment] 2021-05-24 11:32
> ListView needs to set “primary” as false.

That doesn't solve the problem... that has appeared after the Flutter 2.2.0 release.

**Comment by darshankawar** [comment] 2021-05-24 12:55
Thanks for reporting this. This seems to be a regression, wherein, 2.0.6 works well without throwing renderflow exception, but the same code shows the exception in 2.2.0 and on latest master (2.3.0-13.0.pre.120):

1. Stable (2.0.6):


https://user-images.githubusercontent.com/67046386/119350181-a56a1b00-bcbc-11eb-9fa6-8ddfb2a08f78.mov



2. Stable (2.2.0):


https://user-images.githubusercontent.com/67046386/119350223-b155dd00-bcbc-11eb-9f57-a32a211271cc.mov


<details>
<summary> console error log </summary>

```


Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           31.8s
Debug service listening on ws://127.0.0.1:54889/XhnfgmhRqIQ=/ws
Syncing files to device iPhone 12 Pro Max...

======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 47 pixels on the bottom.

The relevant error-causing widget was: 
  Column file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:43:24
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#b383e OVERFLOWING
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=420.0, h=165.0)
...  size: Size(420.0, 165.0)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: min
...  crossAxisAlignment: center
...  verticalDirection: down

```

</details>

<details>
<summary> latest stable flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ncflutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!



```

</details>


<details>
<summary>latest master flutter doctor -v</summary>

```


[✓] Flutter (Channel master, 2.3.0-13.0.pre.120, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-13.0.pre.120 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 197632cab2 (16 hours ago), 2021-05-23 16:54:02 -0400
    • Engine revision ea5c137515
    • Dart version 2.14.0 (build 2.14.0-144.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```

</details>

**Comment by asorokin** [comment] 2021-06-01 20:13
Not sure, if this will help on resolving the issue, but I've encountered this problem in my project. A work around for me was to use the proxyDecorator parameter and wrap its child widget with MediaQuery.removePadding like below.

return ReorderableListView(              
              **proxyDecorator**:
                  (Widget child, int index, Animation<double> animation) =>
                      **MediaQuery.removePadding**(context: context, child: child),
              children: [
                for (var i = 0; i < list.length; i++)
                  MyCustomStatefullClass(
                    key: ValueKey(list[i]),                   
                  ),
              ],
             onReorder: (oldIndex, newIndex) {},
);

**Comment by HansMuller** [comment] 2021-06-02 16:17
CC @darrenaustin

**Comment by darrenaustin** [comment] 2021-06-11 01:16
Sorry that this broke for your use case. This is related to the nested ListViews that are in each item of the example. We refactored the reorderable list a while back and the way the overlay is handled now doesn't appear to work the same for these nested list views. Just curious about this use case. What is the reason for using a shrink wrapped ListView in each child instead of a Column with the same contents? 

I have a fix for this in progress, but in the mean time if you need a work around you can wrap your ListView in a MediaQuery with the top padding removed:

```dart
child: MediaQuery(
  data: MediaQuery.of(context).removePadding(removeTop: true),
  child: ListView.builder(
    shrinkWrap: true,
    physics: const ClampingScrollPhysics(),
    itemCount: 3,
    itemBuilder: (context, index) {
      return const Text('Other data');
    },
  ),
),
```

and that should work as it did i n 2.0.6.

**Closed** 2021-06-23 22:46 UTC
Labels: f: scrolling, found in release: 2.2, found in release: 2.3, framework, has reproducible steps, severe: regression
