### ISSUE TITLE
Ensure Android architecture works with deep linking

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21255] opened 2018-08-31 00:59 UTC
Ensure Android architecture works with deep linking: 

https://docs.google.com/document/d/1AKPWL50wzQFTSaEz2AbGZm5Fkm01uvunZH8AEoLJMRI/edit

**Comment by zoechi** [comment] 2019-01-08 09:02
Is this a duplicate of #5330, #11607 ?

**Comment by matthew-carroll** [comment] 2019-01-09 20:17
@zoechi I don't think so.  This ticket is about the Android-specific notion of deep linking as is used by Android developers today.  I don't think those other tickets are about that.

**Comment by xster** [comment] 2020-11-09 21:27
@chunhtai your https://github.com/flutter/engine/pull/22363 will address this one too presumably?

**Comment by chunhtai** [comment] 2020-11-09 21:39
yes, I don't know this issue exist.

**Comment by xster** [comment] 2020-11-09 21:45
ok, since you already closed your issue :) I'll just add that your PR fixes this in the description.

**Closed** 2020-11-11 22:51 UTC
Labels: P4, engine, passed first triage
