### ISSUE TITLE
Talkback not properly working with add-2-app approach

### ISSUE THREAD

**Issue by saha69** [flutter/flutter#80422] opened 2021-04-14 10:45 UTC
Hi!

I'm working with existing Android project. The project is a rather large, so writing app from scratch is not an option. My plan is to evaluate can I use Flutter to extend current app, writing a new parts with the Flutter. 

I've followed instructions described on documentation: https://flutter.dev/docs/development/add-to-app.

Everything works nicely, except the Talkback green indicator which highlights the selected widget. The position is off.

I've created a simple project to illustrate the problem better.

Flutter part, label is wrongly highlighted:
![talkback_label_problem](https://user-images.githubusercontent.com/82434656/114685041-2cb98b80-9d1a-11eb-95d4-dadafead5b55.png)

The native button bar is properly highlighted:
![talkback_ok](https://user-images.githubusercontent.com/82434656/114685295-67bbbf00-9d1a-11eb-9c22-38c03045ace2.png)

The problem is somehow related to add-2-app approach, since pure "Flutter" approach works properly. I've tested it with real device and emulator.

[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.2)
[✓] Connected device (3 available)

• No issues found!

TransparencyMode is set to opaque, otherwise Talkback indicator is not visible on Flutter view.

</details>

**Comment by TahaTesser** [comment] 2021-04-14 11:57
Hi @saha69 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/75371
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-14 11:57 UTC
Labels: in triage

**Comment by saha69** [comment] 2021-04-23 08:37
I tested the behaviour against the latest master version (2.2.0-11.0.pre.247) - I can gladly report that it's fixed.
