### ISSUE TITLE
[image_picker] Android animated gif not working if maxWidth & maxHeight are set

### ISSUE THREAD

**Issue by PabloTortosaLopez** [flutter/flutter#90185] opened 2021-09-16 11:41 UTC
## Steps to Reproduce

1. Run this example on Android
2. Tap on the floating action button
3. Select a GIF from the device
4. See GIF is not working

**`main.dart`**
```dart
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

final picker = ImagePicker();

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Uint8List? _image;

  void _pickImage() async {
    final image = await picker.pickImage(
      source: ImageSource.gallery,
      maxHeight: 2500,
      maxWidth: 2500,
    );
    if (image != null) {
      _image = await image.readAsBytes();
      setState(() {});
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: _image != null ? Image.memory(_image!) : SizedBox(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _pickImage,
        child: Icon(Icons.image),
      ),
    );
  }
}

```

**`pubspec.yaml`**
```yaml
name: my_app_gif
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  image_picker: ^0.8.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true


```

**Expected results:**
I would expect to see any GIF working as it happens on iOS.

**Actual results:**
GIF is not working if we set maxWidth & maxHeight on the pickImage method

**Comment by danagbemava-nc** [comment] 2021-09-16 13:58
Issue is reproducible on `stable` and `master` with `image_picker: ^0.8.4+1`. 

Without the `maxHeight` and `maxWidth` properties, the gif plays. 

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.114, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.114 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd1892f04f (7 hours ago), 2021-09-15 22:17:02 -0700
    • Engine revision 5a09f16031
    • Dart version 2.15.0 (build 2.15.0-110.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • Nexus’ IPhone (mobile)       • 00008020-001875E83A38002E            • ios            • iOS 14.7.1 18G82
    • iPhone 12 (mobile)           • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • iPad Pro (9.7-inch) (mobile) • 64BCA5CE-E9C3-47AB-97F3-E0610A3A7E14 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)              • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • Nexus’ IPhone (mobile)       • 00008020-001875E83A38002E            • ios            • iOS 14.7.1 18G82
    • iPhone 12 (mobile)           • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • iPad Pro (9.7-inch) (mobile) • 64BCA5CE-E9C3-47AB-97F3-E0610A3A7E14 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)              • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```
</details>

**Comment by stuartmorgan** [comment] 2021-09-16 20:22
> GIF is not working

What does "not working" mean? Is this specifically about *animated* gifs, or do you not see an image it all?

**Comment by PabloTortosaLopez** [comment] 2021-09-16 20:32
> > GIF is not working
> 
> What does "not working" mean? Is this specifically about _animated_ gifs, or do you not see an image it all?

@stuartmorgan 
Yes! It is specifically about animated gifs, i can see the first frame of the GIF, no more. The GIF is frozen, not animated at all.

**Comment by PabloTortosaLopez** [comment] 2021-11-19 09:36
Hey @stuartmorgan! Is this being worked on?

**Comment by stuartmorgan** [comment] 2021-11-19 16:06
Closing as a duplicate of https://github.com/flutter/flutter/issues/34134

You can follow the PR associated with that issue for updates.

**Closed by stuartmorgan** 2021-11-19 16:06 UTC
Labels: platform-android, plugin, p: first party, p: image_picker, has reproducible steps, P4, found in release: 2.5, found in release: 2.6
