### ISSUE TITLE
On iOS, number emojis show up as unknown characters and cause following emoji to show as unknown characters as well

### ISSUE THREAD

**Issue by fbcouch** [flutter/flutter#140896] opened 2024-01-03 18:05 UTC
### Steps to reproduce

Use a text widget to display a string that starts with a number emoji such as 3️⃣, optionally followed by other emoji.

### Expected results

The 3 emoji and any following emojis should render properly

### Actual results

Unknown character boxes are rendered instead – two for 3️⃣, then one for each following emoji.

Interestingly, adding a different emoji, like 😎, before the 3️⃣ causes the text to render correctly.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '3️⃣🖍️🎶🖍️',
            ),
            Text(
              '🖍️🎶🖍️',
            ),
            Text(
              '3️⃣ other 😎',
            ),
            Text(
              '😎3️⃣🖍️🎶🖍️',
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Simulator Screenshot - iPhone 14 Pro - 2024-01-03 at 11 54 43](https://github.com/flutter/flutter/assets/3249979/9ce00fa0-aaf4-4041-afa7-5e71d981558f)

</details>

### Logs

<details open><summary>Logs</summary>

```console
|> flutter run -d 9A9          
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      1,436ms
Xcode build done.                                            9.8s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Syncing files to device iPhone 14 Pro...                            22ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 14 Pro is available at: http://127.0.0.1:54012/htqRfurvgL8=/
The Flutter DevTools debugger and profiler on iPhone 14 Pro is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:54012/htqRfurvgL8=/
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
|> flutter doctor -v
[!] Flutter (Channel stable, 3.16.5, on macOS 13.6.3 22G436 darwin-arm64, locale en-US)
    • Flutter version 3.16.5 on channel stable at /Users/jami/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/jami/flutter. Consider adding
      /Users/jami/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jami/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/jami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15C5042i
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (7 available)
    • SM G950U1 (mobile)                           • 9888e3363157334a48                       • android-arm64  • Android 9 (API 28)
    • Lindsay iPhone (2) (mobile)                  • 00008030-0015448A2280802E                • ios            • iOS 17.2 21C5029g
    • Twin’s iPad (mobile)                         • e8478fd0364f4dbdd177e8ad6a3addf65f548824 • ios            • iOS 16.6 20G75
    • iPhone 14 Pro (mobile)                       • 9A9739BE-A81E-4191-8C5C-4D1EFB7BCD69     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • iPad Pro (11-inch) (4th generation) (mobile) • 19783265-3961-45F2-8F8D-C684F3C12E37     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                              • macos                                    • darwin-arm64   • macOS 13.6.3 22G436 darwin-arm64
    • Chrome (web)                                 • chrome                                   • web-javascript • Brave Browser 119.1.60.125

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by ChenJinCan** [comment] 2024-01-04 05:47
me too

**Comment by danagbemava-nc** [comment] 2024-01-04 07:12
Hi @fbcouch, I believe this is a duplicate of https://github.com/flutter/flutter/issues/36062. 

Closing from here as duplicate. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-01-04 07:12 UTC
Labels: in triage
