### ISSUE TITLE
[video_player_web] Unable to play  H264 video on IE Windows 7/10, Edge Windows 10, iPad Safari/Chrome

### ISSUE THREAD

**Issue by linuxfedora2020** [flutter/flutter#61705] opened 2020-07-17 08:27 UTC
This is my testing result below, Is the browser below incompatible to H264? Thanks

Win 7 Chrome | OK
Win 7 I.E | X
Win 10 Edge | X
Win 10 Chrome | OK
Win 7 I.E | X
iPad Chrome | X
iPad safari | X
Android Chrome | OK

**Comment by TahaTesser** [comment] 2020-07-17 11:01
Hi @linuxfedora2020 
You should be able play H.254 on Edge Windows 10 [Supported Formats
](https://pub.dev/packages/video_player_web#supported-formats)

Can you please provide your `flutter doctor -v`, your `pubspec.yaml`  and a complete reproducible minimal code sample and sample video if possible
Thank you

**Comment by linuxfedora2020** [comment] 2020-07-19 09:04
flutter doctor -v
[âˆš] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version
    6.1.7601], locale zh-HK)
    â€¢ Flutter version 1.19.0-4.3.pre at C:\flutter
    â€¢ Framework revision 8fe7655ed2 (2 weeks ago), 2020-07-01 14:31:18 -0700
    â€¢ Engine revision 9a28c3bcf4
    â€¢ Dart version 2.9.0 (build 2.9.0-14.1.beta)

[âˆš] Android toolchain - develop for Android devices (Android SDK version 28.0.
3)
    â€¢ Android SDK at C:\Users\FAI-WONG\AppData\Local\Android\sdk
    â€¢ Platform android-28, build-tools 28.0.3
    â€¢ Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    â€¢ All Android licenses accepted.

[âˆš] Chrome - develop for the web
    â€¢ Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[âˆš] Android Studio (version 4.0)
    â€¢ Android Studio at C:\Program Files\Android\Android Studio
    â€¢ Flutter plugin version 47.1.2
    â€¢ Dart plugin version 193.7361
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[âˆš] Connected device (2 available)
    â€¢ Web Server â€¢ web-server â€¢ web-javascript â€¢ Flutter Tools
    â€¢ Chrome     â€¢ chrome     â€¢ web-javascript â€¢ Google Chrome 83.0.4103
.116

â€¢ No issues found!



pubspec.yaml

name: testshopdescription: Test Shop# The following line prevents the package from being accidentally published to# pub.dev using `pub publish`. This is preferred for private packages.publish_to: 'none' # Remove this line if you wish to publish to pub.dev# The following defines the version and build number for your application.# A version number is three numbers separated by dots, like 1.2.43# followed by an optional build number separated by a +.# Both the version and the builder number may be overridden in flutter# build by specifying --build-name and --build-number, respectively.# In Android, build-name is used as versionName while build-number used as versionCode.# Read more about Android versioning at https://developer.android.com/studio/publish/versioning# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.# Read more about iOS versioning at# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.htmlversion: 1.0.0+1environment:  sdk: ">=2.7.0 <3.0.0"dependencies:  #universal_html: ^1.2.1  video_player: ^0.10.11+2  video_player_web: ^0.1.3+2  #video_player_web_hls: ^0.1.2  flutter:    sdk: flutter  # The following adds the Cupertino Icons font to your application.  # Use with the CupertinoIcons class for iOS style icons.  cupertino_icons: ^0.1.3dev_dependencies:  flutter_test:    sdk: flutter# For information on the generic Dart part of this file, see the# following page: https://dart.dev/tools/pub/pubspec# The following section is specific to Flutter.flutter:  # The following line ensures that the Material Icons font is  # included with your application, so that you can use the icons in  # the material Icons class.  uses-material-design: true  # To add assets to your application, add an assets section, like this:  # assets:  #   - images/a_dot_burr.jpeg  #   - images/a_dot_ham.jpeg  # An image asset can refer to one or more resolution-specific "variants", see  # https://flutter.dev/assets-and-images/#resolution-aware.  # For details regarding adding assets from package dependencies, see  # https://flutter.dev/assets-and-images/#from-packages  # To add custom fonts to your application, add a fonts section here,  # in this "flutter" section. Each entry in this list should have a  # "family" key with the font family name, and a "fonts" key with a  # list giving the asset and other descriptors for the font. For  # example:  # fonts:  #   - family: Schyler  #     fonts:  #       - asset: fonts/Schyler-Regular.ttf  #       - asset: fonts/Schyler-Italic.ttf  #         style: italic  #   - family: Trajan Pro  #     fonts:  #       - asset: fonts/TrajanPro.ttf  #       - asset: fonts/TrajanPro_Bold.ttf  #         weight: 700  #  # For details regarding fonts from package dependencies,  # see https://flutter.dev/custom-fonts/#from-packagessource code://import 'package:video_player_web/video_player_web.dart';import 'package:video_player/video_player.dart';//import 'package:video_player_web_hls/video_player_web_hls.dart';import 'package:flutter/material.dart';//import 'package:universal_html/html.dart' as html;void main() => runApp(VideoApp());/*void playVideo(String atUrl) {  if(true) {    final v = html.window.document.getElementById('videoPlayer');    if(v != null) {      v.setInnerHtml(          '<source type="video/mp4" src="$atUrl">',          validator: html.NodeValidatorBuilder()            ..allowElement('source', attributes: ['src', 'type']));      final a = html.window.document.getElementById( 'triggerVideoPlayer' );      if(a != null) {        a.dispatchEvent(html.MouseEvent('click'));      }    }  } else {    // we're not on the web platform    // and should use the video_player package  }}*/class VideoApp extends StatefulWidget {  @override  _VideoAppState createState() => _VideoAppState();}class _VideoAppState extends State<VideoApp> {  VideoPlayerController _controller;  @override  void initState() {    super.initState();    _controller = VideoPlayerController.network(        'http://storage.googleapis.com/teleeye-test/test/out01.mp4')      ..initialize().then((_) {        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.        setState(() {});      });  }  @override  Widget build(BuildContext context) {    return MaterialApp(      title: 'Video Demo',      home: Scaffold(        body: Center(          child: _controller.value.initialized              ? AspectRatio(            aspectRatio: _controller.value.aspectRatio,            child: VideoPlayer(_controller),          )              : Container(),        ),        floatingActionButton: FloatingActionButton(          onPressed: () {            setState(() {              _controller.value.isPlaying                  ? _controller.pause()                  : _controller.play();              //playVideo('http://storage.googleapis.com/teleeye-test/test/hevc.mp4');            });          },          child: Icon(//Icons.play_arrow            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,          ),        ),      ),    );  }  @override  void dispose() {    super.dispose();    _controller.dispose();  }}From: Taha Tesser 
Sent: Friday, July 17, 2020 7:01 PM
To: flutter/flutter 
Cc: linuxfedora2020 ; Mention 
Subject: Re: [flutter/flutter] Chrome/safari on iOS and I.E from Windows 7/10 and Edge on Windows 10 cannot play H264 video using video_player_web (#61705)

Hi @linuxfedora2020
You should be able play H.254 on Edge Windows 10 Supported Formats


Can you please provide your flutter doctor -v, your pubspec.yaml and a complete reproducible minimal code sample and sample video if possible
Thank you

**Comment by linuxfedora2020** [comment] 2020-07-20 00:45
I put it into the web server and tested on 2 PC with Windows 10 Edge, but cannot play. But work on the Chrome on Windows 10. http://server3.teleeye.link:1024/recording/web1/index.html

**Comment by linuxfedora2020** [comment] 2020-07-20 01:10
The whole project source code can be downloaded from 
http://www.teleeye.com/softreg/export/test.zip

this is just a very simple testing project. Thanks for your help.

**Comment by TahaTesser** [comment] 2020-07-20 07:17
<details> 
<summary>Code Sample</summary> 

``` 
//import 'package:video_player_web/video_player_web.dart';
import 'package:video_player/video_player.dart';
//import 'package:video_player_web_hls/video_player_web_hls.dart';
import 'package:flutter/material.dart';
//import 'package:universal_html/html.dart' as html;

void main() => runApp(VideoApp());

/*void playVideo(String atUrl) {
  if(true) {
    final v = html.window.document.getElementById('videoPlayer');
    if(v != null) {
      v.setInnerHtml(
          '<source type="video/mp4" src="$atUrl">',
          validator: html.NodeValidatorBuilder()
            ..allowElement('source', attributes: ['src', 'type']));
      final a = html.window.document.getElementById( 'triggerVideoPlayer' );
      if(a != null) {
        a.dispatchEvent(html.MouseEvent('click'));
      }
    }
  } else {
    // we're not on the web platform
    // and should use the video_player package
  }
}*/

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'http://storage.googleapis.com/teleeye-test/test/out01.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.initialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
              //playVideo('http://storage.googleapis.com/teleeye-test/test/hevc.mp4');
            });
          },
          child: Icon(
            //Icons.play_arrow
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (5 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by linuxfedora2020** [comment] 2020-07-20 07:58
So you have same problem on Microsoft Edge on Windows 10, right? So no solution at the moment? Thanks
My most concern is to play H.264 and HEVC video on Windows platform, as only Edge support Hevc hardware decode. But it even failed on H264.

**Comment by ditman** [comment] 2020-08-04 23:39
Hey @linuxfedora2020, can you provide some samples of the videos that you're trying to reproduce? In general, if you drag the video into the browser and it starts playing, it should work with the plugin.

There's also some limitations on safari-based browsers (like chrome for iOS) where if the video has an audio-track and it is not muted, it won't start playing by default. Have you tried setting the video controller to mute before playing? I had to do a few changes to the image_picker example app recently to alleviate this, at least on macos safari, check them out here:

https://github.com/flutter/plugins/pull/2819

**Comment by TahaTesser** [comment] 2020-08-06 15:10
this is  the sample video http://storage.googleapis.com/teleeye-test/test/out01.mp4  provided by author in their zip project and i was able to reproduce the issue.  https://github.com/flutter/flutter/issues/61705#issuecomment-660849979

**Comment by dannycortesv** [comment] 2020-08-08 13:44
I'm having the same issue on iPhone Safari / Chrome

**Comment by darshankawar** [comment] 2020-09-02 09:40
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by dannycortesv** [comment] 2020-09-02 12:19
@darshankawar why you closed it without waiting someone else response, the plugin  is not working on iOS Web browsers, i think it is a major issue.

**Comment by darshankawar** [comment] 2020-09-02 13:25
@dannycortesv we didn't receive response from original author for 29 days after adding `wait` label, so we have to close it and that's why I mentioned in my closing note:

```
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of flutter doctor -v.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
```

**Comment by ditman** [comment] 2020-09-02 18:07
I'm going to reopen this issue, this is something we really want to look at.

**Comment by ditman** [comment] 2020-09-02 18:26
I'm going to reopen this issue, this is something we really want to look at.

**Comment by AngusPei** [comment] 2020-09-14 15:26
iPhone Safari same issue


```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on macOS 11.0 20A5364e, locale
    zh-Hans-CN)
    • Flutter version 1.21.0-9.2.pre at /Users/angus/flutter
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/angus/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • 7F336652-C2C2-4320-800D-F0C53303503F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)  • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)      • chrome                               • web-javascript
      • Google Chrome 85.0.4183.102

• No issues found!

```

**Comment by maheshmnj** [comment] 2021-07-06 11:50
Thanks for filing the issue,
The issue is no longer replicable on the latest stable and the master channel with ```video_player: ^2.1.6```. 
Verified on Safari,Chrome on Ipad,and on Chrome, Edge in Windows. IE is not officially supported for [flutter web ](https://flutter.dev/docs/development/platform-integration/web) yet.  
I would request you to upgrade to latest stable version and verify the issue.

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
	
```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.84, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.4.0-1.0.pre.84 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 691fa19dd7 (6 hours ago), 2021-07-06 02:06:04 -0400
    • Engine revision c1ce39ecb7
    • Dart version 2.14.0 (build 2.14.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.22000.51]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 91.0.4472.124
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 91.0.864.64

• No issues found!
```
		
</details>
Thank you

**Comment by TahaTesser** [comment] 2021-07-28 12:06
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-28 12:06 UTC
Labels: P5, browser: edge, browser: ie, browser: safari, found in release: 1.21, has reproducible steps, p: first party, p: video_player, platform-web, plugin
