### ISSUE TITLE
Copy-Pasting does not work when CAPS LOCK is active on macOS

### ISSUE THREAD

**Issue by technolion** [flutter/flutter#51772] opened 2020-03-02 15:42 UTC
## Steps to Reproduce

1. Create a simple app that includes a text field
2. run app on macOS
3. hit CAPS LOCK on the keyboard
4. enter some text in the text field and try to copy & paste it

**Expected results:** all modifier key actions should work as normal

**Actual results:** Nothing happens

<details>
  <summary>Logs</summary>

porcupine:Development tom$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.4-pre.241, on Mac OS X 10.15.3 19D76, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

```
```

</details>

**Comment by technolion** [comment] 2020-03-02 15:43
cc @gspencergoog

**Comment by pedromassangocode** [comment] 2020-09-03 11:02
I was able to reproduce this on latest `master` channel. Simply the copy/paste (command + c/command + v) does not work while CapsLock is enabled on Mac.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.65, on Mac OS X 10.15.6 19G2021, locale
    en)
    • Flutter version 1.22.0-10.0.pre.65 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 2032a448ed (4 hours ago), 2020-09-02 23:36:19 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
```
</details>

**Comment by gspencergoog** [comment] 2020-09-25 01:25
I was also able to reproduce this.  I think this is the same cause as a similar bug on Linux: I suspect the `NSEventModifierFlagCapsLock` flag in `modifierFlags` means that the caps lock is "locked", not "The caps lock key is pressed", as the [Apple docs](https://developer.apple.com/documentation/appkit/nseventmodifierflags/nseventmodifierflagcapslock?language=objc) claim. Flutter is expecting information about whether the key itself is down, not whether the lock is locked.

**Comment by stuartmorgan** [comment] 2021-01-21 23:00
This should be addressable with #44918

**Comment by gspencergoog** [comment] 2021-01-25 17:51
Reassigning to @dkwingsmt, since Tong's key event work should fix this.

**Comment by gspencergoog** [comment] 2021-10-18 21:40
This has been fixed, I am unable to reproduce this on macOS.

**Closed by gspencergoog** 2021-10-18 21:40 UTC
Labels: a: text input, framework, platform-mac, a: desktop, has reproducible steps, P4, found in release: 1.22
