### ISSUE TITLE
flutter video_player not work after build apk

### ISSUE THREAD

**Issue by sobhan15** [flutter/flutter#78419] opened 2021-03-17 12:56 UTC
### The #videoـplayer playback video well in debug mode, but after build apk I get this message in release mode:

Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
    #0      VideoPlayerApi.initialize (package:video_player_platform_interface/messages.dart:177)

any solution?
@pedromassangocode 

`flutter doctor -v`

> [✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.utf8)
>     • Flutter version 2.0.2 at /home/sobi/snap/flutter/common/flutter
>     • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
>     • Engine revision 5d8bf811b3
>     • Dart version 2.12.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /home/sobi/Android/Sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /usr/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+9)
>     • All Android licenses accepted.
> 
> [✗] Chrome - develop for the web (Cannot find Chrome executable at
>     google-chrome)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from
>       https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
>       for detailed instructions).
> 
> [✓] Connected device (1 available)
>     • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
>       (API 30) (emulator)
> 
> ! Doctor found issues in 2 categories.

**Comment by pedromassangocode** [comment] 2021-03-17 13:22
This seems to be a duplicate of https://github.com/flutter/flutter/issues/66877. 

Can you please provide a minimal reproducible code sample, your `flutter doctor -v` and `flutter run --release --verbose` (running in the same device)?
Thank you

**Comment by sobhan15** [comment] 2021-03-25 22:32
This happens when I use two packages [video_player](https://pub.dev/packages/video_player) and [file_picker](https://pub.dev/packages/file_picker). These two packages seem to be incompatible with each other.
This problem does not exist when I delete package [file_picker](https://pub.dev/packages/file_picker)

**Comment by sobhan15** [comment] 2021-03-25 22:34
> This seems to be a duplicate of #66877.
> 
> Can you please provide a minimal reproducible code sample, your `flutter doctor -v` and `flutter run --release --verbose` (running in the same device)?
> Thank you


This happens when I use two packages [video_player](https://pub.dev/packages/video_player) and [file_picker](https://pub.dev/packages/file_picker). These two packages seem to be incompatible with each other.
This problem does not exist when I delete package [file_picker](https://pub.dev/packages/file_picker)

**Comment by pedromassangocode** [comment] 2021-03-26 07:26
Hi @sobhan15 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://pub.dev/packages/file_picker).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-26 07:26 UTC
Labels: in triage
