### ISSUE TITLE
Flutter Crash: ==== CRASH =====

### ISSUE THREAD

**Issue by shyamkawale** [flutter/flutter#65301] opened 2020-09-06 07:49 UTC
I just run my flutter app normally and this happen and is not getting resolved after doing flutter clean or restarting vscode or even restarting laptop...

==== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF7FD0D5C17
version=2.10.0-7.2.beta (beta) (Mon Aug 17 11:01:01 2020 +0200) on "windows_x64"
pid=6732, thread=321
2, isolate_group=main(0000022A0F82D770), isolate=main(0000022A0F831050)
isolate_instructions=22a0e200000, vm_instructions=7ff7fce0eef0
Stack dump aborted because GetAndValidateThreadStackBounds failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 897

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 29s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by iapicca** [comment] 2020-09-06 09:05
@shyamkawale can you provide your doctor and the output of `flutter run -v`

**Comment by shyamkawale** [comment] 2020-09-06 10:00
> @shyamkawale can you provide your doctor and the output of `flutter run -v`
Thanks @iapicca,
I don't know what happened but I shutdown and then started my laptop and then it was working very fine...

**Comment by iapicca** [comment] 2020-09-06 10:03
If the problem is fixed consider closing the issue

**Closed** 2020-09-06 10:11 UTC
