### ISSUE TITLE
In Chromebooks, apps should start full screen

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15749] opened 2018-03-20 17:41 UTC
Currently, they start in a small window:

![mbq46etmmz9](https://user-images.githubusercontent.com/15253456/37672400-18a59bce-2c2b-11e8-83c1-c35f8cf9c5e7.png)

**Comment by JediBurrell** [comment] 2019-01-08 14:46
All Android apps launch this way by default, Flutter has no preference over this.

To make your app maximize, you can add the following code in the `<application>` tag of your AndroidManifest:
```xml
<meta-data android:name="WindowManagerPreference:FreeformWindowSize"
           android:value="maximize" />
```

**Comment by cbracken** [comment] 2019-11-06 21:39
Closing as working as intended.

**Closed by cbracken** 2019-11-06 21:39 UTC
Labels: customer: mulligan (g3), engine, ⎊ platform-chromebook
