### ISSUE TITLE
Mobile Web using RenderRepaintBoundary.toImage()

### ISSUE THREAD

**Issue by BernardinD** [flutter/flutter#97071] opened 2022-01-22 19:09 UTC
## Steps to Reproduce
RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
var image = await boundary.toImage();

**Expected results:** 
I'm using Flutter-web to take a screenshot of a widget.

**Actual results:** 
 It works on PC but hasn't worked on my Android. Tried with chrome and the default browser. I get the error:
`Unsupported operation: toImage is not supported on the Web`

<details>
<summary>Code sample</summary>

```
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GlobalKey globalKey = new GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RepaintBoundary(
                  key: globalKey,
                  child: Image.asset(''),
                ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: (){
          RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
          boundary.toImage();
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466],
    locale en-US)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\deziu\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.2
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.19042.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.62

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-01-24 09:11
Hi @BernardinD, please provide the output of `flutter doctor -v`. 

Thank you

**Comment by BernardinD** [comment] 2022-01-24 09:31
@danagbemava-nc just added it

**Comment by danagbemava-nc** [comment] 2022-01-24 13:21
Similar to [47721](https://github.com/flutter/flutter/issues/47721).

Hi @BernardinD,
Please see [this](https://github.com/flutter/flutter/issues/47721#issuecomment-570718927) comment from above referenced ticket and another [comment](https://github.com/flutter/flutter/issues/47721#issuecomment-638450866) in which the issue is split into two tickets.
Please follow-up there for updates on this issue.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by danagbemava-nc** 2022-01-24 13:21 UTC
Labels: in triage

**Comment by BernardinD** [comment] 2022-01-25 07:02
@danagbemava-nc Those threads don't seem to cover mobile-web. I can get it to work from a PC so the problem seems to be mobile specific

**Comment by danagbemava-nc** [comment] 2022-01-25 07:05
Mobile-web is just the `html` renderer being used. The default for desktop is `canvaskit` whereas `html` is the default for mobile devices. You can confirm this by running `flutter run -d chrome --web-renderer html`. It will reproduce on desktop as well.

**Comment by BernardinD** [comment] 2022-01-25 07:42
@danagbemava-nc i understand now. Thx so much!
