### ISSUE TITLE
[camera] >= 0.5.3 android.media.ImageReader.getSurface() on null object

### ISSUE THREAD

**Issue by kevin-lot** [flutter/flutter#39109] opened 2019-08-23 08:59 UTC
Since 0.5.3, camera plugin crashes with 
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference.
```

Last year, equivalent bug was posted: https://github.com/flutter/flutter/issues/19595

## Steps to Reproduce

1. Run application with camera preview without authorizations enabled.
2. After authorizing camera and microphone
3. Crash

## Logs
note: I don't understand why but application don't crash in flutter run when verbose mode is on.

```
I/CameraManagerGlobal(14425): Connecting to camera service
D/AndroidRuntime(14425): Shutting down VM
E/AndroidRuntime(14425): FATAL EXCEPTION: main
E/AndroidRuntime(14425): Process: com.keyclic.app, PID: 14425
E/AndroidRuntime(14425): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
E/AndroidRuntime(14425): 	at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
E/AndroidRuntime(14425): 	at io.flutter.plugins.camera.Camera$3.onOpened(Camera.java:173)
E/AndroidRuntime(14425): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:143)
E/AndroidRuntime(14425): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(14425): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14425): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(14425): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(14425): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14425): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(14425): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (14425): Sending signal. PID: 14425 SIG: 9

```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/kevin/Softwares/SDK/flutter
    • Framework revision 20e59316b8 (il y a 5 semaines), 2019-07-18 20:04:33
      -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/kevin/Softwares/SDK/android
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at:
      /home/kevin/Softwares/android-studio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
[✓] Android Studio (version 3.5)
    • Android Studio at /home/kevin/Softwares/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)
• No issues found!
```

**Comment by kevin-lot** [comment] 2019-08-23 09:44
**It seems this issues didn't happen anymore with:**

Inspired by example and not the README [https://raw.githubusercontent.com/flutter/plugins/master/packages/camera/example/lib/main.dart](https://raw.githubusercontent.com/flutter/plugins/master/packages/camera/example/lib/main.dart).

Code to fix issue.
```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App state changed before we got the chance to initialize.
    if (controller == null || !controller.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive) {
      controller?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (controller != null) {
        onNewCameraSelected(controller.description);
      }
    }
  }
```

**Comment by CoreyCole** [comment] 2019-11-27 20:06
I'm confused by the logic in the example. The `onNewCameraSelected()` function initializes the camera controller. Why are we calling that if the controller is `!=` null?

If I'm understanding the `didChanceAppLifecycleState()` function, it is called whenever the app is put into the background and whenever it returns into the foreground. If the controller is null, wouldn't we want to initialize it and not return early from the `didChanceAppLifecycleState()` function?

Could anyone shed some light on what is going on here?

**Comment by MarcelEdward2** [comment] 2019-12-09 15:40
This error is still happening with 0.5.7

I suspect it is a race condition. Something called pictureImageReader is not initialized and startPreview will crash.

**Comment by varun-kernellabs** [comment] 2019-12-20 23:18
This is still going on with 0.5.7 and 0.5.7+1. 
Any solutions out there. Currently using Flutter 1.9.1+hotfix.6.

**Comment by maurozadu** [comment] 2020-02-19 15:05
same issue here!

**Comment by sgehrman** [comment] 2020-03-15 10:31
same issue.

**Comment by mahtab-ali** [comment] 2020-03-22 09:31
same issue ... did anyone found a fix for it ?

**Comment by AxesandGrinds** [comment] 2020-03-30 14:20
same issue

**Comment by hillelcoren** [comment] 2020-04-19 18:45
This change resolves the error for me: https://github.com/flutter/flutter/issues/19595#issuecomment-540402580

You can use this in your pubspec.yaml for a version with the fix:

      camera:
        git:
          url: git://github.com/hillelcoren/plugins.git
          path: packages/camera

Note: this fork includes one other change, it ensures videos are saved as MPEG4 rather than QuickTime on iOS devices:  https://github.com/flutter/plugins/compare/master...hillelcoren:master

**Comment by kw2019ltd** [comment] 2020-07-01 16:11
same issue with latest plugin

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:151)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7710)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by valconetti** [comment] 2020-09-23 11:48
Hi @kevin-lot,

Can you tell me if you also get this crash when using the example app of the plugin?

**Comment by amirh** [comment] 2020-09-23 17:42
duplicate of https://github.com/flutter/flutter/issues/19595

**Closed by amirh** 2020-09-23 17:42 UTC
Labels: d: examples, p: camera, plugin

**Comment by abdullah432** [comment] 2021-01-14 13:58
> **It seems this issues didn't happen anymore with:**
> 
> Inspired by example and not the README https://raw.githubusercontent.com/flutter/plugins/master/packages/camera/example/lib/main.dart.
> 
> Code to fix issue.
> 
> ```
>   @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     // App state changed before we got the chance to initialize.
>     if (controller == null || !controller.value.isInitialized) {
>       return;
>     }
>     if (state == AppLifecycleState.inactive) {
>       controller?.dispose();
>     } else if (state == AppLifecycleState.resumed) {
>       if (controller != null) {
>         onNewCameraSelected(controller.description);
>       }
>     }
>   }
> ```

Can you please share onNewCameraSelected(controller.description) code?

**Comment by kevin-lot** [comment] 2021-02-10 11:39
> Can you please share onNewCameraSelected(controller.description) code?

```
void onNewCameraSelected(CameraDescription cameraDescription) async {
  if (controller != null) {
    await controller.dispose();
  }
  controller = CameraController(
    cameraDescription,
    ResolutionPreset.medium,
    enableAudio: enableAudio,
  );

  // If the controller is updated then update the UI.
  controller.addListener(() {
    if (mounted) setState(() {});
    if (controller.value.hasError) {
      showInSnackBar('Camera error ${controller.value.errorDescription}');
    }
  });

  try {
    await controller.initialize();
  } on CameraException catch (e) {
    _showCameraException(e);
  }

  if (mounted) {
    setState(() {});
  }
}
```

But we are reworking a lot of code with new camera version of plugin.

**Comment by eliaweiss** [comment] 2021-02-23 08:32
> **It seems this issues didn't happen anymore with:**
> 
> Inspired by example and not the README https://raw.githubusercontent.com/flutter/plugins/master/packages/camera/example/lib/main.dart.
> 
> Code to fix issue.
> 
> ```
>   @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     // App state changed before we got the chance to initialize.
>     if (controller == null || !controller.value.isInitialized) {
>       return;
>     }
>     if (state == AppLifecycleState.inactive) {
>       controller?.dispose();
>     } else if (state == AppLifecycleState.resumed) {
>       if (controller != null) {
>         onNewCameraSelected(controller.description);
>       }
>     }
>   }
> ```

The link is broken, can you please explain which class should override this method?
