### ISSUE TITLE
Gesture events seem to not be sent on PlatformViewLink on Flutter 3.13

### ISSUE THREAD

**Issue by letsar** [flutter/flutter#133984] opened 2023-09-04 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install Flutter 3.13
2. On an Android device, run the code on this repo: [main/example](https://github.com/flutter-stripe/flutter_stripe/tree/main/example?rgh-link-date=2023-09-04T12%3A04%3A25Z)
3. Expand the **Wallets** section and then click on **Google Pay** item
4. Click on the Google Pay button
5. Nothing happens

### Expected results

We should be able to click on the Google Pay button.

### Actual results

Nothing happens, it seems that the tap gesture is not sent to the PlatformView.
It works with Flutter 3.7.12

I filled an issue on the flutter_stripe repo in case it's on the package's side (https://github.com/flutter-stripe/flutter_stripe/issues/1393) but I don't understand why it works with Flutter 3.7 and not 3.13 then.

### Code sample

Run the code from this repo: https://github.com/flutter-stripe/flutter_stripe/tree/main/example?rgh-link-date=2023-09-04T12%3A04%3A25Z

### Logs

<details><summary>Logs</summary>

```console
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on IN2023 is available at: http://127.0.0.1:65325/pQqHbaZ1ILQ=/
[ +401 ms] The Flutter DevTools debugger and profiler on IN2023 is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:65325/pQqHbaZ1ILQ=/
[  +42 ms] D/OplusScrollToTopManager(16156): com.flutter.stripe.example/com.flutter.stripe.example.MainActivity,This DecorView@1804249[MainActivity] change focus to true
[+1966 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[        ] D/OplusSystemUINavigationGestureExtImpl(16156): regionString = null
[        ] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +32 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +8 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +68 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +6 ms] D/OplusInputMethodManagerInternal(16156): get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@1c8cb04
[        ] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[+1460 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +7 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +16 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +6 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +16 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +8 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +33 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +8 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +40 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +8 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +66 ms] I/PlatformViewsController(16156): Using hybrid composition for platform view: 0
[  +58 ms] D/BufferQueueConsumer(16156): [](id:3f1c00000002,api:0,p:-1,c:16156) connect: controlledByApp=true
[        ] D/BufferQueueProducer(16156): [SurfaceView[com.flutter.stripe.example/com.flutter.stripe.example.MainActivity]#1(BLAST Consumer)1](id:3f1c00000001,api:1,p:16156,c:16156) disconnect: api 1
[        ] D/BufferQueueProducer(16156): [ImageReader-1080x2260f1m3-16156-0](id:3f1c00000002,api:1,p:16156,c:16156) connect: api=1 producerControlledByApp=true
[  +92 ms] I/.stripe.example(16156): Compiler allocated 5021KB to compile void android.view.ViewRootImpl.performTraversals()
[ +904 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +10 ms] D/ProfileInstaller(16156): Installing profile for com.flutter.stripe.example
[   +8 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +16 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +17 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +16 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +16 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +17 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +32 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +49 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +17 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +15 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +6 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[ +379 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +29 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[ +131 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +3 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[ +257 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[ +102 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +32 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +51 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +8 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[        ] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[ +283 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +20 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +17 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +32 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +50 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +32 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[   +9 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[ +318 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +36 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +18 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +97 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +17 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[        ] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[ +291 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +20 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +33 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +18 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +16 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +15 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +17 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +33 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[  +33 ms] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[        ] D/VRI[MainActivity](16156): handleWindowFocusChanged mWindowFocusChanged false mUpcomingWindowFocus true mAdded true
[+2406 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.flutter.stripe.example/code_cache/exampleMSSDGH/example/)
[   +6 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.flutter.stripe.example/code_cache/exampleMSSDGH/example/)
[   +4 ms] executing: /Users/romain.rastel/Library/Android/sdk/platform-tools/adb -s 87950fce shell am force-stop com.flutter.stripe.example
[  +89 ms] Application finished.
[   +2 ms] "flutter run" took 19 006ms.
[   +8 ms] Service protocol connection closed.
[  +32 ms] ensureAnalyticsSent: 37ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 12.5.1 21G83 darwin-arm64, locale fr-FR)
    • Flutter version 3.13.2 on channel stable at /Users/xxx/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (11 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-14.0.0.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • IN2023 (mobile)            • 87950fce                             • android-arm64  • Android 13 (API 33)
    • iPhone 13 Pro Max (mobile) • F7BD4E2B-91F5-47DA-9594-0D808C2C260C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-09-05 06:08
Hi @letsar 
>I filled an issue on the flutter_stripe repo in case it's on the package's side (https://github.com/flutter-stripe/flutter_stripe/issues/1393) but I don't understand why it works with Flutter 3.7 and not 3.13 then.

Since you are also not sure if this is a package issue or not, I would recommend you follow up on your opened issue there for better support. Once it's verified as a Flutter framework issue, please try to provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this properly.

I will close this issue. Please write in the comments when you have more information for us. Thank you!

**Comment by letsar** [comment] 2023-09-05 06:42
Hi @huycozy, since it works with Flutter 3.7 but not in 3.13 with the same version of the package, it seems it's related to Flutter, isn't it?

I know I didn't provide a complete and minimal reproducible code sample, but it's not easy to see what's going wrong here, that's why I came for help to both sides.

**Comment by huycozy** [comment] 2023-09-06 03:34
>since it works with Flutter 3.7 but not in 3.13 with the same version of the package, it seems it's related to Flutter, isn't it?

Hi. There will be cases where the framework API has some changes but the package has not been updated to be compatible with them yet. You can also look at the release notes and breaking changes [here](https://docs.flutter.dev/release/release-notes) to see if there are any suspicious changes.

**Comment by letsar** [comment] 2023-09-06 06:52
There is nothing about changes about `PlatformViews` which should be addressed in this version, and if there were they should be breaking in order to be in a situation where changes has to be made, to not having a runtime issue.
Moreover, the code seems to work on some devices but not all (the android version does not matter). It really looks like a regression that should be addressed.

**Comment by huycozy** [comment] 2023-09-07 04:12
Reopening this issue for further investigation. The issue should be actionable with clear steps with minimal sample code to reproduce it. As mentioned above, `flutter_stripe` is a complex package, you should narrow down to the issue and try to re-create it with a simpler sample code. You can folk my minimal repo [here](https://github.com/huycozy/platformviews-demo) and elaborate on it for reproduction. Thank you!

**Comment by remonh87** [comment] 2023-09-13 07:14
@huycozy  thanks for looking into it I have created a simple reproduction scenario that shows the issue: https://github.com/remonh87/platform_view_test . What is very curious is that when tapping on the android icon the callback is not fired but what is curious once I comment out `layout.initialize()` (line 27 on NativeView.kt) and press in the center of the screen it does work. It seems like that when button.xml is rendered the clicks are not occuring anymore.

Hope this helps

**Comment by huycozy** [comment] 2023-09-13 11:33
@remonh87 Thank you for the sample code but it seems not the correct one. It also doesn't work on Flutter 3.7.12 as mentioned above.

**Comment by remonh87** [comment] 2023-09-25 19:41
@huycozy  thanks problem is that Stripe is a huge sdk and it is not easy to create a minimal reproducible example. Is there an easy way I can triage that the click events are being send to the native side ? e.g. by adding some verbose flag in flutter

**Comment by huycozy** [comment] 2023-09-29 11:02
@remonh87 I am not aware if there is such a flag. Looks like you can only debug this by adding your own log to framework/engine code and finding where the bottleneck is.

To make it simpler, please try to provide a minimal sample if that is possible. Thank you!

**Closed** 2023-10-13 07:08 UTC
Labels: waiting for customer response, in triage
