### ISSUE TITLE
Windows window jittering resizing

### ISSUE THREAD

**Issue by Oleksa3** [flutter/flutter#87094] opened 2021-07-27 08:06 UTC
Running app from starter project in Visual Studio, regardless of `flutterMode` in launch.json, produces window jitter on its resizing:

https://user-images.githubusercontent.com/46814554/127115866-c40c6db7-f897-4230-af31-797de6eda3e1.mp4

 **To reproduce the problem:**
1. Create project from default template.
2. Run with/without debugging in release/debug mode.
3. Resize window by left/top side. 

**Expected results:** 
Smooth window resizing by left/top side.

**Actual results:**
Jittering resizing

To fix this, read the answer: https://stackoverflow.com/a/25364123/9486175

**Comment by TahaTesser** [comment] 2021-07-27 11:36
Hi @Oleksa3 
This was reported in https://github.com/flutter/flutter/issues/76465, a duplicate of https://github.com/flutter/flutter/issues/79427
Closing as duplicate 
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-27 11:36 UTC
Labels: in triage
