### ISSUE TITLE
macos desktop onScaleUpdate does not respond to pinch

### ISSUE THREAD

**Issue by jackdreillyvia** [flutter/flutter#69372] opened 2020-10-30 06:35 UTC
## Steps to Reproduce

```dart
void main() => runApp(MaterialApp(
        home: Scaffold(
            body: GestureDetector(
      onScaleUpdate: print,
      child: Container(
        color: Colors.blue,
      ),
    ))));
```
1. `flutter run -d macos`
2. pinch using macbook trackpad
3. nothing printed
4. drag with trackpad
5. note that dragging works but scale is always 1.0

**Expected results:**

pinching makes `onScaleUpdate` trigger.

**Actual results:**

no trigger

<details>
## Flutter Doctor
[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-FR)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
</details>

**Comment by darshankawar** [comment] 2020-10-30 10:14
@jackdreillyvia 
There's similar [open](https://github.com/flutter/flutter/issues/23604) issue. Does your issue resembles it ?

**Comment by jackdreillyvia** [comment] 2020-10-30 11:36
Yes, this is the same.

**Comment by darshankawar** [comment] 2020-10-30 13:15
@jackdreillyvia Thanks for confirming. Closing this as duplicate of [23604](https://github.com/flutter/flutter/issues/23604)

**Closed by darshankawar** 2020-10-30 13:15 UTC
Labels: in triage
