### ISSUE TITLE
[web] HtmlElementView messes with other widgets after window resize

### ISSUE THREAD

**Issue by A-L-M** [flutter/flutter#96447] opened 2022-01-11 06:27 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Change the width of the window (either increase it or decrease it) 
3. The container on the left disappears 

**Expected results:** 
![image](https://user-images.githubusercontent.com/20939910/148889577-5cdee2e5-d3e1-489c-9a51-bc1d804c2818.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/20939910/148889614-33d1a961-29ed-45ec-bbb1-798b20175bb5.png)

<details>
<summary>Code sample</summary>

```
import 'dart:html';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final htmlId = '1';

  final elem = DivElement()
    ..id = '1'
    ..style.width = "100%"
    ..style.height = "100%"
    ..style.border = 'solid';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Builder(builder: (context) {
          final size = MediaQuery.of(context).size;
          // ignore: undefined_prefixed_name
          ui.platformViewRegistry.registerViewFactory(htmlId, (int viewId) {
            return elem;
          });
          return Row(
            children: [
              Container(
                color: Colors.black,
                width: size.width * 0.5,
              ),
              SizedBox(
                height: size.height,
                width: size.width * 0.5,
                child: HtmlElementView(viewType: htmlId),
              ),
            ],
          );
        }),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +52 ms] executing: [C:\Users\ALM\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +387 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] executing: [C:\Users\ALM\Documents\flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +42 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[   +6 ms] executing: [C:\Users\ALM\Documents\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\ALM\Documents\flutter/] git ls-remote --get-url origin
[  +23 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +78 ms] executing: [C:\Users\ALM\Documents\flutter/] git rev-parse --abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +61 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] executing: C:\Users\ALM\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +34 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] Multiple devices found:
[  +16 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.376]
[        ] Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.71
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.55
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+6395 ms] 2
[  +11 ms] Skipping pub get: version match.
[  +96 ms] Generating C:\Users\ALM\Desktop\CB LUNA\RTA\Flutter Apps\pruebas\so_example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +76 ms] Launching lib\main.dart on Chrome in debug mode...
[  +97 ms] Updating assets
[  +58 ms] Waiting for connection from debug service on Chrome...
[  +69 ms] <- reset
[   +5 ms] C:\Users\ALM\Documents\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\ALM\Documents\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\ALM\Documents\flutter\bin\cache\flutter_web_sdk/      
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\ALM\AppData\Local\Temp\flutter_tools.85879cca\flutter_tool.88dbb26c\app.dill --libraries-spec
file:///C:/Users/ALM/Documents/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\ALM\Desktop\CB LUNA\RTA\Flutter
Apps\pruebas\so_example\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\ALM\AppData\Local\Temp\flutter_tools.85879cca\flutter_tools.905c82b6 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///C:/Users/ALM/Documents/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill    
--sound-null-safety
[  +10 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+12378 ms] Waiting for connection from debug service on Chrome... (completed in 12.5s)
[   +1 ms] Synced 28.4MB.
[        ] <- accept
[        ] Caching compiled dill
[ +427 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:55894/devtools/browser/0204b6cb-d8d7-4e80-b530-3ee5204aff4a
[ +215 ms] DwdsInjector: Received request for entrypoint at http://localhost:55872/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +14 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +7 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:55872/main_module.bootstrap.js
[+2255 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +56 ms] DevHandler: Debug service listening on ws://127.0.0.1:55911/iaDKy8RSVh8=/ws

[  +19 ms] This app is linked to the debug service: ws://127.0.0.1:55911/iaDKy8RSVh8=/ws
[   +8 ms] Debug service listening on ws://127.0.0.1:55911/iaDKy8RSVh8=/ws
[        ]  Running with sound null safety 
[   +3 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:55911/iaDKy8RSVh8=
[+3571 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:55911/iaDKy8RSVh8=
```

```
Analyzing so_example...                                                 

   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\main.dart:1:1 - avoid_web_libraries_in_flutter

1 issue found. (ran in 2.0s)
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale en-US)
    • Flutter version 2.8.1 at C:\Users\ALM\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\ALM\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\ALM\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.376]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.55

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2022-01-11 09:36
Thanks for the report. Verified this on latest versions (stable, master and beta) and seems to be occuring with canvaskit rendering, while, the same works properly with html rendering.

1. Canvaskit:


https://user-images.githubusercontent.com/67046386/148917582-36cb16a2-b336-4588-9bd4-a1bacd3e612b.mov



2. html:

<img width="509" alt="Screenshot 2022-01-11 at 2 57 06 PM" src="https://user-images.githubusercontent.com/67046386/148917812-e352f5bc-d846-4abc-b311-0a2dca075831.png">

<details>
<summary> stable, master, beta flutter doctor -v </summary>

```
[[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.9.0-1.0.pre.316, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.295 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 79025d4567 (9 minutes ago), 2022-01-10 23:40:18 -0500
    • Engine revision b5a9cfd537
    • Dart version 2.16.0 (build 2.16.0-144.0.dev)
    • DevTools version 2.9.2
    • PATH =
      /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/binpplicat
      ions/Software_Setup/flutter/bin:/Users/dhs/triagemagic/bin/:/Users/dhs/doc
      uments/fluttersdk/flutter/bin:/emulator:/tools:/tools/bin:/platform-tools:
      /Users/dhs/.pub-cache/bin
    
[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-0.1.pre at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (4 weeks ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.




```

</details>

**Comment by zambetpentru** [comment] 2022-01-11 20:20
Hi, sounds related to https://github.com/flutter/flutter/issues/95259 ?

**Comment by A-L-M** [comment] 2022-01-14 04:50
> There may be a race condition in the code. The code creates a single `DivElement` and the returns the same element every time the platform view factory is called. To eliminate the possibility of this being caused by a race condition, can you check if returning a _new_ element from the factory helps? An easy way to check is to change `return elem;` to `return elem.clone(true);`.

I'm afraid that didn't work. After changing that line I get the following error:
```
Error: A value of type 'Node' can't be returned from a function with return type 'Element'.
 - 'Node' is from 'dart:html'.
 - 'Element' is from 'dart:html'.
            return elem.clone(true);
```

**Comment by yjbanov** [comment] 2022-04-01 20:01
I'm unable to reproduce this any more. Is this still an issue?

**Comment by yjbanov** [comment] 2022-05-05 20:46
Closing for now. If this shows up again, let's retriage. We have a contributor that's currently working on fixing `devicePixelRatio` and window resize notifications from the engine to the framework, which might improve the situation further.

**Closed by yjbanov** 2022-05-05 20:46 UTC
Labels: engine, platform-web, e: web_canvaskit, has reproducible steps, found in release: 2.8, found in release: 2.9
