### ISSUE TITLE
[regression] Texture is not rendered on Linux/master

### ISSUE THREAD

**Issue by bdlukaa** [flutter/flutter#123974] opened 2023-04-02 19:34 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Expect the texture to be displayed

**Expected results:** 

On the master channel, the texture should be visible

**Actual results:** 

The texture is not displayed on the master channel, only in the beta and stable channel

<details>
<summary>Code sample</summary>

https://github.com/lattice0/external_texture_flutter_linux

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, 3.9.0-0.2.pre, on Ubuntu 22.04.2 LTS
    5.19.0-38-generic, locale en_US.UTF-8)
    • Flutter version 3.9.0-0.2.pre on channel beta at /home/bruno/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0df8557c56 (10 days ago), 2023-03-23 22:02:01 -0500
    • Engine revision 1cc4b2d280
    • Dart version 3.0.0 (build 3.0.0-290.3.beta)
    • DevTools version 2.22.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.60.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.2 LTS 5.19.0-38-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by huycozy** [comment] 2023-04-03 12:34
Thanks for filing the issue. This issue is reproducible on the latest master (`3.9.0-20.0.pre.92`) whilst it does not happen on stable (`3.7.9`).

| stable | master |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/229509639-2ab47d77-0284-4c64-acab-97ed00d08149.png"> | <img width="450" src="https://user-images.githubusercontent.com/104349824/229509624-75fd6f37-e810-4cfb-b2ec-81cdec144c1d.png">

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[!] Flutter (Channel stable, 3.7.9, on Ubuntu 22.04.1 LTS 5.19.0-38-generic, locale en_US.UTF-8)
    • Flutter version 3.7.9 on channel stable at /home/huynq/Documents/Working/flutter
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter. Consider adding /home/huynq/Documents/Working/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (4 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.9.0-20.0.pre.92, on Ubuntu 22.04.1 LTS 5.19.0-38-generic, locale en_US.UTF-8)
    • Flutter version 3.9.0-20.0.pre.92 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f98499f9bb (57 minutes ago), 2023-04-03 07:23:36 -0400
    • Engine revision ea07ee9ec3
    • Dart version 3.0.0 (build 3.0.0-401.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment] 2023-04-03 13:47
closing as duplicate of https://github.com/flutter/flutter/issues/124009

**Closed by TahaTesser** 2023-04-03 13:47 UTC
Labels: severe: regression, engine, platform-linux, has reproducible steps, found in release: 3.9
