### ISSUE TITLE
Can't run my flutter apps

### ISSUE THREAD

**Issue by donPathos** [flutter/flutter#40338] opened 2019-09-12 08:33 UTC
**I receive crash report when i execute flutter run.**
```
Initializing gradle...
Finished with error: ProcessException: Process "C:\Users\codeLogic\AndroidStudioProjects\flutter_app\android\gradlew.bat" exited abnormally:
Unzipping C:\Users\codeLogic\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip to C:\Users\codeLogic\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\codeLogic\AndroidStudioProjects\flutter_app\android\gradlew.bat -v
```

**Comment by donPathos** [comment] 2019-09-13 10:00
@BondarenkoStas 
i tried your solution and didn't get such error again but the problem now is that i get
'Initializing gradle.....' and this takes forever.

**Comment by jonahwilliams** [comment] 2019-10-15 19:30
Duplicate of https://github.com/flutter/flutter/issues/40517

**Closed by jonahwilliams** 2019-10-15 19:30 UTC
Labels: t: gradle, tool
