### ISSUE TITLE
image_picker crashes when picking images on simulator running on Apple Silicon M1 

### ISSUE THREAD

**Issue by Lerobindesbois** [flutter/flutter#71943] opened 2020-12-08 21:20 UTC
On an Apple Silicon M1 it is not possible to use the Image_picker Package to select an image. In the photo gallery, when you click on the image, the interface does nothing and does not react.

To exit the interface you must click on the cancel button, so the operation does not work.

The event on the click of the image is not captured.

[Run -- verbose.txt](https://github.com/flutter/flutter/files/5661954/Run.--.verbose.txt)

![Capture d’écran, le 2020-12-08 à 16 12 06](https://user-images.githubusercontent.com/69640665/101542082-49ab1000-3970-11eb-81a7-1bf69bc75048.png)

Merci ! Thank you !

**Comment by YazeedAlKhalaf** [comment] 2020-12-09 08:41
Hi @Lerobindesbois 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment] 2020-12-09 08:56
Hi @Lerobindesbois 
Does it reproduce on a simulator only?  Have you tried running on a physical device? 
Running on Intel-based mac on the simulator has no issue when picking images
Can you please provide a complete reproducible minimal code sample without using third parry packages 
```bash
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 11 Pro is available at: http://127.0.0.1:58250/1kpMRUvORsc=/
[+1230 ms] flutter: Instance of 'DocumentSnapshot'
[   +3 ms] flutter: Instance of 'DocumentSnapshot'
[+7090 ms] flutter: Instance of 'QueryDocumentSnapshot'
[   +3 ms] flutter: Instance of 'QueryDocumentSnapshot'
[        ] flutter: Instance of 'QueryDocumentSnapshot'
[        ] flutter: Instance of 'QueryDocumentSnapshot'
[        ] flutter: Instance of 'QueryDocumentSnapshot'
[        ] flutter: Instance of 'QueryDocumentSnapshot'
[+8555 ms] flutter: Erreur
```
Thank you

**Comment by Lerobindesbois** [comment] 2020-12-09 16:49
Hello, Thank you for your feedback,

I did not try with a physical device, I continue my development on an Intel Mac.

The aim of the application is the detection of harmful insects on farms.

Here is my very simple code:

 Future<void> getImageGallery() async {
    PickedFile tempPictFile;
    tempPictFile = await ImagePicker().getImage(source: ImageSource.gallery);
    if (tempPictFile != null) {
      imageFile = await tempPictFile.readAsBytes();
      imageFile = await decodeImageFromList(imageFile);

      setState(() {
        pickedImage = File(tempPictFile.path);
        isImageLoaded = true;
        isFaceDetected = false;
        imageFile = imageFile;
      });
    } else {
      print("Aucune Image de sélectionner");
    }
  }

**Comment by HiroshiHorie** [comment] 2020-12-12 09:58
Having the same issue here!

**Comment by markusaksli-nc** [comment] 2020-12-22 08:48
Reproducible on the latest master `1.26.0-2.0.pre.103` but only on Apple Silicon M1 iOS 14.3 simulator. Works just fine on physical iOS 14.3 and iOS 14.2 simulator on Intel Macbook. Tested using the official `image_picker` example.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.103, on macOS 11.0.1 20B29 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.103 at /Users/nevercode/development/flutter_master
    • Framework revision 32741c0ec8 (7 hours ago), 2020-12-21 18:34:02 -0600
    • Engine revision af6889a600
    • Dart version 2.12.0 (build 2.12.0-169.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.3
    • iPhone 12 Pro Max (mobile)  • 09D9E93F-A98D-4735-B6E6-6E57F9CD01D8     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
</details>

**Comment by johnhaha** [comment] 2020-12-25 10:16
the same issue happened to me and I spent 1 hour looking for what I am doing wrong with the code 😭

**Comment by ikey2244** [comment] 2021-01-19 06:24
I think this is an issues with the IOS simulator on apple silicon. I am having the same issue with a React Native project. I also tried to choose an image from the Messages app and I am getting a black screen. So I don't this is a code issue within flutter or React native. We need to take it up with Apple.

**Comment by xWorldx** [comment] 2021-02-03 08:14
i am having the same problem, it works fine on a physical device but when it comes to the simulator it doesn't work.
Hopefully someone can help us :)

**Comment by Lerobindesbois** [comment] 2021-02-12 16:09
What is going on with this bug? It’s really too long, there are already a lot of M1 processor users, it’s been a long time to fix this bug! I need an iOS simulator to continue development ...... or do I need to report this bug for serious consideration?

**Comment by webdevike** [comment] 2021-02-12 16:13
> What is going on with this bug? It’s really too long, there are already a lot of M1 processor users, it’s been a long time to fix this bug! I need an iOS simulator to continue development ...... or do I need to report this bug for serious consideration?

As far as I know it's not a flutter issue. No matter the project IOS image picker doesn't work on M1.

**Comment by Matsuo32** [comment] 2021-03-07 04:57
any updated?

**Comment by MtDesigners** [comment] 2021-03-11 05:23
I have the same issue and I posted my problem in detail [HERE](https://github.com/flutter/flutter/issues/72854#issuecomment-796459678)

I'm quite sure it's not a coding problem, rather the new Macs not being fully compatible. I guess we just have to wait 
@TahaTesser

**Comment by Matsuo32** [comment] 2021-03-14 06:39
Right now, for iOS emulator on M1 chip  ,  "multi_image_picker" package is work now .

**Comment by salehahmedZ** [comment] 2021-03-26 05:06
I am having the same problem
it works fine on a physical device but when it comes to the simulator it doesn't work.
This only happened on an Apple Silicon M1 computer

**Comment by a-yarohovich** [comment] 2021-04-07 14:43
Same problem for me on MacMini M1.

**Comment by Razbotics** [comment] 2021-04-18 14:26
Same issue on macbook pro m1. Hope it gets solved quickly

**Comment by TahaTesser** [comment] 2021-04-20 10:04
Hey everyone, 
Please add "thumbs up" reaction to https://github.com/flutter/flutter/issues/71943#issue-759790370, instead of commenting same issue

**Comment by ducthinh2111** [comment] 2021-04-24 02:44
I am having the same issue while using React Native. Have anyone had the solution yet?

**Comment by Razbotics** [comment] 2021-04-24 05:41
Hello everyone, looks like the image picker on IOS emulator on Mac m1 is working now, few days back it wasn't. What I did is, I reinstalled the xcode with latest one from store (maybe the simulator issue has been fixed with a update)

**Comment by ydag** [comment] 2021-04-29 16:02
Hello , is the issue solved as @Razbotics mentioned https://github.com/flutter/flutter/issues/71943#issuecomment-826039142 the possible solution in here? Can you check please @Lerobindesbois ?

**Comment by Andresdn14** [comment] 2021-05-02 01:33
> Hello, is the issue solved as @Razbotics mentioned [#71943 (comment)](https://github.com/flutter/flutter/issues/71943#issuecomment-826039142) the possible solution in here? Can you check please @Lerobindesbois?

This solution did't work for me, this is really frustrating.

**Comment by Razbotics** [comment] 2021-05-03 06:50
> > Hello, is the issue solved as @Razbotics mentioned [#71943 (comment)](https://github.com/flutter/flutter/issues/71943#issuecomment-826039142) the possible solution in here? Can you check please @Lerobindesbois?
> 
> This solution did't work for me, this is really frustrating.

Hey are you using flutter? FYI I am using react native. I am not sure if the update fixed issue. Another thing I am suspecting is permission library. Did you get permission request for media on IOS simulator? I remember before updating xcode I never got the permission prompt. But after reinstalling xcode I got that and my picker library started working fine.
So it's possible the permission library is the culprit not the picker. Try giving permission manually if it's possible on IOS

**Comment by akashgk** [comment] 2021-05-10 07:58
I'm also facing the same issue in the new M1 Mac, The Simulator does not seem to work at all.

has anyone found any work around for it ?

**Comment by Razbotics** [comment] 2021-05-10 15:10
> > Hello everyone, looks like the image picker on IOS emulator on Mac m1 is working now, few days back it wasn't. What I did is, I reinstalled the xcode with latest one from store (maybe the simulator issue has been fixed with a update)
> 
> @Razbotics can you confirm your Xcode version? i'm having Xcode 12.5
> OS: 11.3.1 Big Sur
> 
> M1 Chip

Yes I am on Xcode 12.5

**Comment by jangelRiveaux** [comment] 2021-05-17 14:08
I am having the same problem.  Any solution for  it?

**Comment by NozomiIto** [comment] 2021-05-17 14:20
This is not a fultter issue but a Xcode/iOS simulator issue. I think the best way to resolve this is to report the prooblem to Apple from https://feedbackassistant.apple.com/.
The more developers report this issue, the more seriously and quickly Apple team will resolve this issue.

FYI: https://openradar.appspot.com/radar?id=5026493528801280 is the copy of the message I posted to https://feedbackassistant.apple.com/.

**Comment by jmagman** [comment] 2021-06-10 00:16
Indeed I see the same `_LSSchemaConfigureForStore` as the pasteboard question described in https://github.com/flutter/flutter/issues/74970#issuecomment-858170914.  It's the same iOS 14 Rosetta translation simulator bug.

I validated that the image picker works in a iOS 13.7 simulator, so that's a workaround you can use until Apple fixes it, or Flutter no longer needs Rosetta translation #60118.

Closing as duplicate of https://github.com/flutter/flutter/issues/74970.

**Closed by jmagman** 2021-06-10 00:16 UTC
Labels: P6, customer: crowd, found in release: 1.26, has reproducible steps, p: first party, p: image_picker, passed first triage, platform-host-arm, platform-ios, platform-mac, plugin, severe: crash
