### ISSUE TITLE
Engine -> Flutter roll failed after taking 44 minutes to install XCode

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#89343] opened 2021-09-02 04:26 UTC
The roll here https://github.com/flutter/flutter/pull/89334

failed on a presubmit check here

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests_1_4/9124/overview

on a timeout after it took 44 minutes to install XCode.

Marking P3 for now, but I will monitor for further failures.

**Comment by zanderso** [comment] 2021-09-02 04:28
Next roll attempt is here https://github.com/flutter/flutter/pull/89342

**Comment by yusufm** [comment] 2021-09-02 15:39
@zanderso Looks like the builds have been passing after this failure. Is this still an issue?

**Comment by zanderso** [comment] 2021-09-02 15:42
This is not currently happening as far as I can tell, but if we don't understand why it happened, then I am worried that it will happen again.

**Comment by godofredoc** [comment] 2021-09-08 02:25
The task took 44mins to download xcode which left only a few mins for execution before the timeout that killed the task. The caching mechanism and the named caches are correct.

Seems like the root cause is a [previous task](https://chromium-swarm.appspot.com/task?id=55bc39a4e2d1dc10) that failed to save the named caches and cause a full cache cleanup. This behavior is expected but we may need to find a way to mitigate timeouts caused by xcode not being in the cache.

**Comment by godofredoc** [comment] 2021-11-18 21:09
Marking as obsolete. I haven't seen this happening frequently only when the versions of xcode are updated.

**Closed by godofredoc** 2021-11-18 21:09 UTC
Labels: passed first triage, team: infra, passed secondary triage, P3
