### ISSUE TITLE
Flutter App freezes  after  animating for a few seconds

### ISSUE THREAD

**Issue by doradsoft** [flutter/flutter#99288] opened 2022-02-28 19:37 UTC
The sample code is almost the same as in #99233 (a `Text` child widget instead of `Image`). Although `CanvasKit` has the same issue in certain cases, the current issue is for another problem in CanvasKit.
The problem is that after a few seconds (depends on child's weight, screen width and probably more parameters) the whole app is freezing. 

### Reproducible steps

1. Create new folder `flutter_web_bug`
2. Open terminal inside that folder and execute `flutter create .`
3. Replace `./lib/main.dart` contents with the following code
4. Open terminal and execute `flutter run -d chrome --web-renderer canvaskit`

<details>
  <summary>code sample</summary>

```dart
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter web bug',
      home: MyHomePage(title: 'Flutter web bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double angle = 0.0;
  @override
  void initState() {
    super.initState();
    Timer.periodic(const Duration(milliseconds: 20), (timer) {
      setState(() {
        angle += 0.01;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Transform(
              transform: Matrix4.identity()
                ..setEntry(3, 2, 0.001)
                ..rotateY(pi * angle),
              alignment: Alignment.center,
              child: Align(
                  alignment: Alignment.center,
                  child: Container(
                      color: const Color(0xffaaffff),
                      child: Transform(
                          alignment: Alignment.center,
                          transform: Matrix4.identity()..rotateY(pi),
                          child: const Text(
                              "אבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגשאבגדה וזח טי כלמנספצ גדךלףגש"))))),
        ));
  }
}

```
</details>

<details>
  <summary>Video</summary>
  
https://user-images.githubusercontent.com/5598420/156046982-391033ff-5a13-471f-820a-5034cd270a4d.mp4 
</details>

<details>
  <summary>flutter doctor -v</summary>
  
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1526], locale en-IL)
    • Flutter version 2.10.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (10 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Dorad\AppData\Local\Android\sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.10.31402.337
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.64.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by maheshmnj** [comment] 2022-03-01 08:54
Hi @doradsoft, Thanks for filing the issue. I am able to reproduce the issue the rotation is frozen with canvaskit and works fine with HTML renderer. This is reproducible on both stable and the master channel.

HTML | Canvaskit
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/156136094-5ba64aaf-b4d9-4353-a04b-5962fd9f2bee.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/156136574-48608d18-c96a-413f-87dd-a58c94d6b845.mov' width=180/> 


```console
mahesh@Maheshs-MacBook-Air-M1 webassets % flutterm run -d chrome --web-renderer canvaskit
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             14.2s
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
This app is linked to the debug service: ws://127.0.0.1:64796/d3jD5pbYbOA=/ws
Debug service listening on ws://127.0.0.1:64796/d3jD5pbYbOA=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:64796/d3jD5pbYbOA=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:64796/d3jD5pbYbOA=
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
```


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.715, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.715 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8b95cd6f35 (7 hours ago), 2022-02-28 16:31:12 -0800
    • Engine revision 615a60512c
    • Dart version 2.17.0 (build 2.17.0-150.0.dev)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • CBEF6BFA-D3DC-4680-8900-E01C62A4B04C • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by maheshmnj** [comment] 2022-03-02 13:27
Thanks for the update @doradsoft, I have updated the issue. This looks purely like a framework issue since this reproduces on all platforms

**Comment by maheshmnj** [comment] 2022-03-02 13:40
Thanks for the update @doradsoft, I have updated the issue accordingly.

**Comment by doradsoft** [comment] 2022-03-02 17:55
Hey @maheshmnj, thanks for your effort making this issue better to solve.
You have changed the issue title and I think it's not accurate. As I mentioned in #99233 the issues reproduces also without `Timer.Periodic`. It happens with Animation and AnimatedBuilder as well.
I think it's more about the child widget type.

**Comment by jason-simmons** [comment] 2022-03-02 21:15
Reproduced this on Android.

This is due to the same cause as https://github.com/flutter/flutter/issues/98275

**Comment by Kobatsu** [comment] 2022-03-03 16:37
I spent days on this problem without understanding the cause of it since I was using animations, images (including gif) and Transform on a large number of widgets. It worked quite fine on mobiles and macOS but it would just freeze each time after a while on Web.
It apparently happened only because there was a label on top of my animated widgets as suggested by @jason-simmons. Thank you so much for pointing this out, it drove me crazy. 🙏

**Comment by chinmaygarde** [comment] 2022-03-07 18:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98275 that has a linked Skia issue. I'm going to elevate the priority of the linked issue.

**Closed by chinmaygarde** 2022-03-07 18:58 UTC
Labels: engine, severe: performance, dependency: skia, severe: rendering, perf: speed, has reproducible steps, found in release: 2.10, found in release: 2.11
