### ISSUE TITLE
Markers are not shown in the Android app only

### ISSUE THREAD

**Issue by mohadel92** [flutter/flutter#80539] opened 2021-04-15 22:04 UTC
Hi Guys,
i have a problem with official  google maps package
the markers are not shown in the android app only(iOS is working fime)
## Steps to Reproduce

1. implement google maps
2. use your markers
3. in my case markers are not visible in android app

**Expected results:** 
the markers should be visible in both iOS and Android

**Actual results:** 
iOS working version
<a href="https://ibb.co/1fCBsqX"><img src="https://i.ibb.co/d0NXb2p/Simulator-Screen-Shot-i-Phone-11-Pro-Max-2021-04-15-at-23-55-39.png" alt="Simulator-Screen-Shot-i-Phone-11-Pro-Max-2021-04-15-at-23-55-39" border="0"></a>

Android broken map
<a href="https://ibb.co/w72Lf4S"><img src="https://i.ibb.co/FXdWFz5/Screenshot-2021-04-15-23-57-00-150-com-sevensquare-saloni.jpg" alt="Screenshot-2021-04-15-23-57-00-150-com-sevensquare-saloni" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>post pictures</a><br />

<details>

`E/flutter (13818): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (13818): 	at android.os.Looper.loop(Looper.java:165)
E/flutter (13818): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/flutter (13818): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (13818): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (13818): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (13818): )
E/flutter (13818): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:582
E/flutter (13818): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
E/flutter (13818): <asynchronous suspension>
E/flutter (13818): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter (13818): #3      MethodChannelGoogleMapsFlutter.updateMarkers
package:google_maps_flutter_platform_interface/…/method_channel/method_channel_google_maps_flutter.dart:245
E/flutter (13818): #4      GoogleMapController._updateMarkers
package:google_maps_flutter/src/controller.dart:115
E/flutter (13818): #5      _GoogleMapState._updateMarkers
package:google_maps_flutter/src/google_map.dart:287
E/flutter (13818): <asynchronous suspension>
E/flutter (13818): #6      _GoogleMapState.didUpdateWidget
package:google_maps_flutter/src/google_map.dart:265
E/flutter (13818): #7      StatefulElement.update
package:flutter/…/widgets/framework.dart:4815
E/flutter (13818): #8      Element.updateChild
package:flutter/…/widgets/framework.dart:3314
E/flutter (13818): #9      RenderObjectElement.updateChildren
package:flutter/…/widgets/framework.dart:5647
E/flutter (13818): #10     MultiChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6246
E/flutter (13818): #11     Element.updateChild
package:flutter/…/widgets/framework.dart:3314
E/flutter (13818): #12     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4652
E/flutter (13818): #13     StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
E/flutter (13818): #14     Element.rebuild
package:flutter/…/widgets/framework.dart:4343
E/flutter (13818): #15     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2730
E/flutter (13818): #16     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:913
E/flutter (13818): #17     RendererBinding._handlePersistentFra
W/DynamiteModule(13818): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(13818): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6`

```
```

`**Flutter Doctor -v**

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.6, on Mac OS X 10.14.6 18G8012 darwin-x64, locale en-EG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)

• No issues found!
Mohammeds-MacBook-Pro:saloni_salon mohammedadelalisorour$ `

```
```

</details>

**Comment by pedromassangocode** [comment] 2021-04-16 07:03
Hi @mohadel92 
I cannot reproduce the issue.

![Screen Shot 2021-04-16 at 07 56 59](https://user-images.githubusercontent.com/67424416/114984155-5644f500-9e89-11eb-9fa6-d5a0d294ccf9.png)

Please upgrade your Flutter version and provide your `flutter doctor -v`, your `flutter run --verbose`, your `pubspec.yaml` and a minimal reproducible code sample.
Thank you

**Comment by pedromassangocode** [comment] 2021-05-07 11:20
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 11:20 UTC
Labels: in triage, waiting for customer response
