### ISSUE TITLE
 Set the “cacheWidth ” and “cacheHeight”parameter when using Image.network in ListView, the screen flickers when loading data asynchronously

### ISSUE THREAD

**Issue by LjxTttt** [flutter/flutter#70770] opened 2020-11-18 15:36 UTC

**Comment by LjxTttt** [comment] 2020-11-19 05:31
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (11 months ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by TahaTesser** [comment] 2020-11-19 11:27
Hi @LjxTttt 
Looks like you're on nearly a year old Flutter version. 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment] 2020-12-11 09:50
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-11 09:50 UTC
Labels: in triage, waiting for customer response
