### ISSUE TITLE
[web] Email Autofill broken on Firefox & Chrome

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#87309] opened 2021-07-29 23:46 UTC
## Bug

A common use case on the web is **autofill** for an _email + password combination_.

In Flutter, this can be achieved using an [`AutofillGroup`](https://api.flutter.dev/flutter/widgets/AutofillGroup-class.html) and two [`TextField`](https://api.flutter.dev/flutter/material/TextField-class.html)s using the appropriate [`AutofillHints`](https://api.flutter.dev/flutter/services/AutofillHints-class.html).

After saving the email + password combination to the browser, Flutter should _autofill_ the email and password the next time the user interacts with that text field.  

### Broken on Firefox

However, **on Firefox** only the _password_ is autofilled when clicking onto the email field. On the flip side, when clicking the password field, both the email and password are autofilled. So this is clearly a bug and probably a trivial one to fix. 

### Illustration

I have illustrated the broken behavior in the following screen recording:

https://user-images.githubusercontent.com/19204050/127579138-c7629cf7-12ef-42f9-a795-ba20916278c1.mp4

On the left side, you can see the app running on Chrome (where everything works fine) and on the right side, you can see it running on Firefox (where it is broken and shows the described behavior).

## Steps to Reproduce

Follow the steps shown in the video by running the following code:

<details>
  <summary>Click to expand minimal sample code and version</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Autofill bug',
    home: Scaffold(
      body: Center(
        child: FractionallySizedBox(
          widthFactor: 1 / 3,
          child: const Bug(),
        ),
      ),
    ),
  ));
}

class Bug extends StatefulWidget {
  const Bug({Key? key}) : super(key: key);

  @override
  State createState() => _BugState();
}

class _BugState extends State<Bug> {
  var _showingTextFields = true;

  void _hideTextFields() {
    setState(() {
      _showingTextFields = false;
    });
    Future.delayed(const Duration(seconds: 1), () {
      if (!mounted) return;
      setState(() {
        _showingTextFields = true;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    if (!_showingTextFields) return const SizedBox();
    return AutofillGroup(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: TextField(
              autofillHints: [AutofillHints.email],
              decoration: InputDecoration(
                prefixIcon: const Icon(Icons.alternate_email_outlined),
                labelText: 'Email',
                border: OutlineInputBorder(),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: TextField(
              autofillHints: [AutofillHints.password],
              obscureText: true,
              decoration: InputDecoration(
                prefixIcon: const Icon(Icons.password_outlined),
                labelText: 'Password',
                border: OutlineInputBorder(),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: OutlinedButton(
              onPressed: _hideTextFields,
              child: Text('Reset text fields'),
            ),
          ),
        ],
      ),
    );
  }
}
```

```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
```

</details>

**Comment by maheshmnj** [comment] 2021-07-30 10:53
Hi @creativecreatorormaybenot,
Thanks for filing the issue, I am able to reproduce it on the latest stable channel, but I see that its broken on the latest master channel for the chrome too. Clicking on email or password input field should auto fill both the fields.

### master 2.5.0-2.0.pre.69
                   Chrome on the left    ❌                                 Firefox on the right ❌

https://user-images.githubusercontent.com/31410839/127641245-e7c4733f-670a-490b-b94e-a51a0df08c3e.mov

### stable 2.2.3
                   Chrome on the left  ✅                                  Firefox on the right. ❌
https://user-images.githubusercontent.com/31410839/127641265-91f6e678-c4e3-4bff-8c01-dc7505d0a85e.mov



✅ : No Issue ❌: Issue reproduced



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

```
[✓] Flutter (Channel master, 2.5.0-2.0.pre.69, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-2.0.pre.69 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ccf6f0353a (10 minutes ago), 2021-07-29 01:50:54 -0700
    • Engine revision 40451453ab
    • Dart version 2.14.0 (build 2.14.0-361.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2021-08-10 14:17
Hi @creativecreatorormaybenot  

There are two issues here
### Firefox issue on current stable
This is https://github.com/flutter/flutter/issues/68005, we don't need separate issues for email hint, as hints take a list of hints, you can provide email and password hints like this and neither of them work on Firefox on the current stable 
```dart
       autofillHints: const <String>[
                  AutofillHints.username,
                  AutofillHints.email
                ],
```

### Autofill web regression for all browsers
This has been reported in https://github.com/flutter/flutter/issues/86497, autofill broke since 2.3 on the web, independent from browsers. This is also reproduced in https://github.com/flutter/flutter/issues/87309#issuecomment-889812906

closing as a duplicate for both issues explained above

**Closed by TahaTesser** 2021-08-10 14:17 UTC
Labels: a: text input, engine, platform-web, has reproducible steps, browser: firefox, P3, found in release: 2.2, found in release: 2.5
