### ISSUE TITLE
Flutter Windows only partially paint window

### ISSUE THREAD

**Issue by SuperPenguin** [flutter/flutter#112908] opened 2022-10-05 03:27 UTC
Flutter app on Windows only partially paint a portion of app that is visible on display. This will make the app looks glitched when dragged back to center. It will paint again only when there is any rebuild.
On macOS the app is painting whole window.

## Steps to Reproduce

1. Run the code sample
2. Drag window to right side of screen, partially hide half of it outside the display
3. Change Tab
4. Drag window to center again
5. See result

**Expected results:** App should paint whole window

**Actual results:** Only portion on visible display is painted

<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (context) => const HomeScreen(),
      },
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _index = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          NavigationRail(
            labelType: NavigationRailLabelType.all,
            selectedIndex: _index,
            onDestinationSelected: (value) {
              setState(() {
                _index = value;
              });
            },
            destinations: const [
              NavigationRailDestination(
                icon: Icon(Icons.home),
                label: Text('Home'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.settings),
                label: Text('Settings'),
              ),
            ],
          ),
          Expanded(
            child: Builder(
              builder: (context) {
                switch (_index) {
                  case 0:
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: const [
                        Expanded(
                          child: ColoredBox(color: Colors.blue),
                        ),
                        Expanded(
                          child: ColoredBox(color: Colors.green),
                        ),
                      ],
                    );

                  case 1:
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: const [
                        Expanded(
                          child: ColoredBox(color: Colors.red),
                        ),
                        Expanded(
                          child: ColoredBox(color: Colors.orange),
                        ),
                      ],
                    );
                }

                return const Placeholder();
              },
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.22621.525], locale en-ID)
    • Flutter version 3.3.3 on channel stable at C:\GitHub\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (6 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\andre\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\andre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.525]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.91
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/1574722/193974835-1602da48-d181-4c27-a93b-dde20edc8e80.mp4

**Comment by exaby73** [comment] 2022-10-05 08:00
Hello @SuperPenguin. I can reproduce this issue on stable but not on master indicating that this is already fixed. Closing due to this reason. If you disagree, please comment and I can reopen the issue. Thank you.

**Closed** 2022-10-05 08:00 UTC
Labels: in triage
