### ISSUE TITLE
A widget is buggy or. Something looks wrong or not

### ISSUE THREAD

**Issue by Somtobro** [flutter/flutter#134450] opened 2023-09-11 18:40 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I tried to create a import txt file when I noticed this.
Create a Textfield
Set controller.text= "very large data";//5mb txt file

### Expected results

Probably lazy load the content on the textfield or not crash 

### Actual results

App crashes

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Somtobro** [comment] 2023-09-12 08:24
@darshankawar 
Ive attached the code to reproduce and the txt file , 
You really just need to try to set the text controller.text to a large string to reproduce this error.
I could not get the crash log I don't know how to get that but these should be sufficient
Hoping to hear from you

[dcode.txt](https://github.com/flutter/flutter/files/12584083/dcode.txt)
[repository.txt](https://github.com/flutter/flutter/files/12584084/repository.txt)

**Comment by darshankawar** [comment] 2023-09-13 06:33
@Somtobro 
Can you provide flutter doctor -v on which it is crashing ? If you run the code locally in debug mode, running the code crashes the app which shows in the console log ?

**Comment by Somtobro** [comment] 2023-09-13 08:05
Good morning, okay so after reading your response I tried to log the crash but it isn't logging every other thing is logged successfully but the app is stopping so I guess that's why that couldn't log.

I've given you everything you need to recreate the crash, you could also try pasting a large text directly into any flutter app and see what happens
Just try this and you'd see what I speak of

**Comment by darshankawar** [comment] 2023-09-13 12:01
Thanks for the feedback @Somtobro 
I tried your code sample which seems to be using flutter_riverpod package that is community package.
Does the same reported behavior occur without using that package implementation ? If so, please provide us updated code sample without using any third party package code, that triggers the crash or reported behavior.

**Comment by huycozy** [comment] 2023-09-14 05:49
Hi @Somtobro 
Thanks for your update but the sample code is still incomplete and not represent the main part of the issue (it only has the importing file data part and lack of loading text part).

Regarding to the initial issue, it could be a duplicate of framework issue at https://github.com/flutter/flutter/issues/90063. But as you mentioned there is a crash as well, we need to know if the crash is caused by Flutter framework or 3rd plugins you use. 

So please provide the entire output of `flutter run -v`. If the output log is too long, please save it into a file and attach it here. And please also let us know the platform you are checking on. Thank you!

**Comment by Somtobro** [comment] 2023-09-15 09:00
I've written a sample code for you

```
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'dart:io';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller = TextEditingController();
  String _filePath = '';

  Future<void> pickFile() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles();

    if (result != null) {
      // The user has selected a file.
      String filePath = result.files.single.path!;
      String fileContent = await File(filePath).readAsString();

      setState(() {
        _controller.text = fileContent;
        _filePath = filePath;
      });
    } else {
      // User canceled the file picker.
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Import Text File into TextField'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: pickFile,
              child: Text('Select Text File'),
            ),
            SizedBox(height: 20),
            Text('Selected File: $_filePath'),
            SizedBox(height: 20),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(20.0),
                child: TextField(
                  controller: _controller,
                  maxLines: null, // Allows multiple lines for large text.
                  readOnly: true, // Prevents editing and nay be true later on
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                    labelText: 'File Content',
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

I was thinking lazy loading the content onto the textfield may be a good way to solve this issue once and for all.
I will attach the flutter verbose soon hopefully but you don't even need that,this will recreate the error

**Comment by Somtobro** [comment] 2023-09-16 18:20
@darshankawar

**Comment by huycozy** [comment] 2023-09-18 05:51
@Somtobro Thanks for your update with sample code. I tried running it on my device `Realme 6, Android 11` but I only see the app freeze instead of crashing. I'm using this [large text file](https://github.com/BitDoctor/speed-test-file/blob/master/5mb.txt). 

As I mentioned above, this issue is very similar to https://github.com/flutter/flutter/issues/90063 if it's frozen only. If you can observe the crash, please provide the output of `flutter run -v` so that we may investigate it. Otherwise, feel free to close this and follow up on linked issue for updates.

**Comment by Somtobro** [comment] 2023-09-18 08:24
It actually does crash
It freezes then crashes
Copy and then paste the large text file in itself a couple times

Let's see if there would be a difference

**Comment by huycozy** [comment] 2023-09-19 05:50
I tried this with some text files:

- 500KB: can load text normally
- 1MB: can load text normally
- 5MB: app freeze, no crash

As I mentioned above, you should share the output of `flutter run -v` which contains the crash stack trace so that we can verify this. Without additional information, we are unfortunately not sure how to resolve this issue.

**Comment by darshankawar** [comment] 2023-09-19 05:57
@Somtobro Also try using `adb logcat` command to see if it gives you any meaningful crash log.
https://developer.android.com/tools/logcat

**Closed** 2023-10-10 06:09 UTC
Labels: waiting for customer response, in triage
