### ISSUE TITLE
flutter downgrades to the wrong version

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#63635] opened 2020-08-13 07:17 UTC
We are releasing our new app but 1.20 is causing to much issues for us to release.

I want to go back from 1.20.1 to 1.17.5 but the flutter tool forces us to go back to 1.17.4 instead of 1.17.5 on the stable channel

`flutter version 1.17.5` is a deprecate command so we can't use that

![image](https://user-images.githubusercontent.com/21172855/90104995-75611500-dd45-11ea-906a-2130c9d3a14d.png)

**Comment by itssidhere** [comment] 2020-08-13 09:07
Have you tried doing it manually

https://flutter.dev/docs/development/tools/sdk/releases

**Comment by vanlooverenkoen** [comment] 2020-08-13 09:09
A full reinstall? Yeah that worked. But I would expect that the downgrade command would do that for you

**Comment by itssidhere** [comment] 2020-08-13 09:13
I have also downgraded to 1.17.5 using downgrade and version commands on windows. Are you doing this on windows?

**Comment by vanlooverenkoen** [comment] 2020-08-13 09:14
I am using a mac. Our buildserver is a mac mini

**Comment by vanlooverenkoen** [comment] 2020-08-13 09:30
And now our buildserver downgrades to 1.17.1 😑

**Comment by TahaTesser** [comment] 2020-08-13 10:00
Hi @vanlooverenkoen 
Jus tried to reproduce, i had to install `1.17.5` -> upgraded to `1.20.1` and then `flutter downgrade 1.17.5`
```
tahatesser@Tahas-MacBook-Pro ~ % flutterp downgrade 1.17.5
Downgrade flutter to version 1.17.5
? [y|n]: 
```

**Comment by vanlooverenkoen** [comment] 2020-08-13 10:09
@TahaTesser 
```
~/Documents/work(:|✔) % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.4 19E287, locale en-BE)
    • Flutter version 1.20.1 at /Users/vanlooverenkoen/flutter
    • Framework revision 2ae34518b8 (7 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • SHIELD Android TV (mobile) • 192.168.2.124:5555                   • android-arm64 • Android 9 (API 28)
    • iPhone 11 (mobile)         • 93B47E6A-8DAA-43C9-9ED8-1A3D266D3218 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
~/Documents/work(:|✔) % flutter downgrade 1.17.5
Downgrade flutter to version 1.17.4
? [y|n]: 
```

**Comment by christopherfujino** [comment] 2020-08-13 18:33
@vanlooverenkoen `flutter version` is deprecated but it will still work.

**Comment by vanlooverenkoen** [comment] 2020-08-13 18:39
Yes indeed. But I also create this ticket to make sure it will be fixed in the future.

**Comment by christopherfujino** [comment] 2020-08-13 18:47
`flutter upgrade` will store the current version (before upgrading) to a file `.flutter_tool_state` in a user's home directory. Then if you issue the command `flutter downgrade`, it will read that version, and then git reset the repo to that tag.

It seems either you were on version `1.17.5` issued `flutter upgrade` and the tool erroneously recorded `1.17.4` as the last tool version, in which case we should fix that.

Or, you were previously on version `1.17.4`, and this is working as intended. Can you confirm which version you were previously on?

**Comment by vanlooverenkoen** [comment] 2020-08-13 18:49
Hmm that sounds strange. Because on our build server we had 1.17.5
For 1 build we need to use 1.20.1 so we did a flutter upgrade. 
next build we needed 1.17.5 => flutter downgrade went to 1.17.4
next build we needed 1.20.1 again => flutterr upgrade
next build we needed 1.17.5 => flutter downgrade went to 1.17.0 🤷 
I have no idea why

**Comment by vanlooverenkoen** [comment] 2020-08-13 18:50
I do think we should have a command `flutter select 1.20.1` and it automaticly uses that specific version. (as flutter version did)

**Comment by christopherfujino** [comment] 2020-08-13 18:55
@vanlooverenkoen you can do `flutter reset --hard 1.20.1`

**Comment by vanlooverenkoen** [comment] 2020-08-13 19:04
You mean that that is the recommended command to select a specific version?

**Comment by christopherfujino** [comment] 2020-08-13 19:11
Yes. If you don't mind having a detached HEAD, even easier is `git checkout 1.20.1`, which is essentially what `flutter version` did.

**Comment by vanlooverenkoen** [comment] 2020-08-13 19:12
So what is the difference between `flutter version 1.20.1` and  `flutter reset --hard 1.20.1`

**Comment by christopherfujino** [comment] 2020-08-13 19:18
> So what is the difference between `flutter version 1.20.1` and `flutter reset --hard 1.20.1`

`flutter version 1.20.1` will detach your git HEAD, your channel will be reported as `unknown`, and you will not be able to `flutter upgrade` to a new version (because you're not on a channel). Maybe other things break too? This is one of the reasons we're deprecating the `flutter version` command.

**Comment by TahaTesser** [comment] 2020-08-14 08:30
Hi @vanlooverenkoen 
Hope this answers your issue, thanks christopherfujino 
Closing, as this isn't an issue with Flutter itself and depends `flutter_tool_state` and not take a version, it just reverts based on history. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-14 08:30 UTC
Labels: in triage

**Comment by vanlooverenkoen** [comment] 2020-08-14 08:37
I think for now it is clear for me. We will do some extra testing to make sure it is doing what we expect

**Comment by vanlooverenkoen** [comment] 2020-08-18 08:08
> @vanlooverenkoen you can do `flutter reset --hard 1.20.1`
```
~/Documents/work(:|✔) % flutter reset --hard 1.20.1
Could not find a command named "reset".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

Reset is not found

**Comment by christopherfujino** [comment] 2020-08-18 15:56
> > @vanlooverenkoen you can do `flutter reset --hard 1.20.1`
> 
> ```
> ~/Documents/work(:|✔) % flutter reset --hard 1.20.1
> Could not find a command named "reset".
> 
> 
> Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
> ```
> 
> @TahaTesser & @christopherfujino
> Failed to use the reset command.

Sorry, I meant `git reset --hard 1.20.1`.

**Comment by vanlooverenkoen** [comment] 2020-08-18 16:05
Alright. I do think flutter needs a way to select a specific version. And I would expect flutter downgrade 1.17.5 to go to the correct one. Not downgrade to a version you previously installed.

I don't think we want to be using git to make sure we have the correct version.

**Comment by vanlooverenkoen** [comment] 2020-08-19 09:41
@TahaTesser I think this ticket should be reopened. 

Because I can not find any reason why I would want to go to 1.17.4 instead of my selected version 1.17.5
For when downgrading I don't want to be using a version I previously installed. But go to the correct version.

**Comment by christopherfujino** [comment] 2020-08-19 20:00
> @TahaTesser I think this ticket should be reopened and marked as a bug.
> 
> Because I can not find any reason why I would want to go to 1.17.4 instead of my selected version 1.17.5
> For when downgrading I don't want to be using a version I previously installed. But go to the correct version.

`flutter downgrade` is working as intended. If you believe it should work in another way, please file a feature request outlining the desired behavior and the rationale. Thanks!

**Comment by vanlooverenkoen** [comment] 2020-08-19 20:03
So to be clear the inteded behavour of flutter downgrade is to go back to a previous installed flutter version. even if you selected an other version?

**Comment by christopherfujino** [comment] 2020-08-19 20:22
> So to be clear the inteded behavour of flutter downgrade is to go back to a previous installed flutter version. even if you selected an other version?

Correct, `flutter downgrade` does not supporting selecting an arbitrary version. From the help descriiption:

```
~/git$ flutter help downgrade
Downgrade Flutter to the last active version for the current channel.

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with --help, shows hidden options.
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.
    --packages              Path to your ".packages" file.
                            (required, since the current directory does not contain a ".packages" file)

Usage: flutter downgrade [arguments]
-h, --help    Print this usage information.
```

**Comment by hengsoheak** [comment] 2020-12-09 05:41
5k+error
