### ISSUE TITLE
FAILURE: Build failed with an exception - Flutter

### ISSUE THREAD

**Issue by OmarYehiaDev** [flutter/flutter#66355] opened 2020-09-22 15:45 UTC
## Steps to Reproduce

I was trying to build my app as normal

**Expected results:** 

Message says that `build is done successfully` and the app shows on my phone

**Actual results:** 

I faced a weird error

<details>
  <summary>Logs</summary>

This is the error :-

```
C:\Native\findhelpapp\findhelpapp>flutter run
Launching lib\main.dart on M2003J15SC in debug mode...
Running Gradle task 'assembleDebug'...
C:\Native\findhelpapp\findhelpapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:25: error: cannot find symbol
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
                                                                      ^
  symbol:   class PathProviderPlugin
  location: package io.flutter.plugins.pathprovider
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.    

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 26s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       207.9s (!)
Exception: Gradle task assembleDebug failed with exit code 1

C:\Native\findhelpapp\findhelpapp>
```
Running `flutter analyze` :-

```
C:\Native\findhelpapp\findhelpapp>flutter analyze
Analyzing findhelpapp...

   info - The value of the field '_hasSpeech' isn't used - lib\pages\tabs\mapPage.dart:33:8 - unused_field
   info - The value of the field '_currentLocaleId' isn't used - lib\pages\tabs\mapPage.dart:40:10 - unused_field

2 issues found. (ran in 73.8s)

C:\Native\findhelpapp\findhelpapp>
```
The logs of `flutter doctor` :-

```
C:\Users\Omar>flutter doctor -v
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.20.4 at C:\Native\flutter
    • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Omar\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\Omar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • M2003J15SC (mobile) • 1b19b6000404 • android-arm64 • Android 10 (API 29)

• No issues found!

C:\Users\Omar>
```

</details>

**Comment by doyle-flutter** [comment] 2020-09-22 16:15
using pathprovider?

**Comment by OmarYehiaDev** [comment] 2020-09-22 16:20
> using path provider?

Nope

**Comment by doyle-flutter** [comment] 2020-09-22 16:36
try 'flutter clean'

**Comment by OmarYehiaDev** [comment] 2020-09-22 16:39
> try 'flutter clean'

I tried it a lot but it doesn't work

**Comment by doyle-flutter** [comment] 2020-09-22 16:46
lack of information... ummmmm .... think native code err.... can u show me packages ? and 'C:\Native\findhelpapp\findhelpapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:25' code .

**Comment by OmarYehiaDev** [comment] 2020-09-22 17:00
![image](https://user-images.githubusercontent.com/42435651/93913755-cfbaa180-fd05-11ea-997f-b93e9896d031.png)
here is the line

**Comment by OmarYehiaDev** [comment] 2020-09-22 17:01
and this is my packages :-
```
dependencies:
    flutter:
        sdk: flutter
    # SplashScreen
    splashscreen:
        git:
            url: git://github.com/OmarYehiaDev/SplashScreenFlutterPackage
    # HTTP & Network
    http: ^0.12.2
    # Icons
    material_design_icons_flutter: 4.0.5345
    # Firebase
    # firebase_core: ^0.5.0
    # firebase_auth: ^0.18.0+1
    # Social Login
    # flutter_facebook_login: ^1.2.0
    # google_sign_in: ^4.1.1
    # Map
    platform_maps_flutter: ^0.1.8+1
    # STT
    speech_to_text: ^2.4.1
    # Form Validation
    wc_form_validators: ^0.1.1
    # WebView
    webview_flutter: ^0.3.22+1
    # Location
    location: ^3.0.0
    geocoder: ^0.2.1
    # State Management
    # provider: ^4.3.2+1
    # In-App Badges
    badges: ^1.1.1
    # Out-App Badges
    flutter_app_badger: ^1.1.2
    # Offline Storage
    shared_preferences: ^0.5.10
    # Google Fonts
    google_fonts: ^1.1.0
    # Biometric Auth
    local_auth: ^0.6.1+3
    # Search Bar
    material_floating_search_bar:
        git:
            url: git://github.com/bnxm/material_floating_search_bar
    # DateTimePicker
    flutter_datetime_picker: ^1.4.0
    # Toast messages
    fluttertoast: ^7.1.1

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    # Launcher Icons
    flutter_launcher_icons: "^0.7.5"
flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/mylogo.png"
```

**Comment by doyle-flutter** [comment] 2020-09-22 17:09
Delete the native 25 lines and do error checking. This is because the package dependencies are wrong.
'google_fonts' or conflicting with other packages.

**Comment by OmarYehiaDev** [comment] 2020-09-22 17:14
I deleted 'C:\Native\findhelpapp\findhelpapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:25' code and I'll try to build the app now. Should I run `flutter clean` or anything else first?

**Comment by doyle-flutter** [comment] 2020-09-22 17:18
APP Delete first in Emulator
1. delete -> clean -> Build -> Err Msg Check 
2. reset -> google_fonts or other packages delete -> build test

**Comment by doyle-flutter** [comment] 2020-09-22 17:37
Please comment when it is resolve :) Additional issues are also good.

**Comment by OmarYehiaDev** [comment] 2020-09-22 18:32
> Please comment when it is resolve :) Additional issues are also good.

Still facing it :"(
but I don't know exactly what to do for performing step 2

**Comment by doyle-flutter** [comment] 2020-09-22 19:04
step 1. native code remove -> build -> msg check 

step 2. native code 25 line reset -> google_fonts package delete(or other package delete), flutter code update -> build test

**Comment by doyle-flutter** [comment] 2020-09-22 19:06
step 3. [Android_studio] new Flutter Project -> Paste existing files( ' lib ' folder) & pubspec etc ... -> Build Test

**Comment by OmarYehiaDev** [comment] 2020-09-22 21:18
Steps 1 & 2 don't work. Must I try Step 3 :"( ??
because it will be very frustrating to move all this work done in the old workplace to another new one

**Comment by doyle-flutter** [comment] 2020-09-23 02:51
It's hard, but it can be the fastest way ..

**Comment by TahaTesser** [comment] 2020-09-23 07:42
Hi @OmarYehiaDev 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using third party packages 
Thank you

**Comment by TahaTesser** [comment] 2020-10-14 12:26
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 12:26 UTC
Labels: in triage

**Comment by VigneshPasupathy** [comment] 2020-10-20 05:26
I'm getting the exact same error. Project was working till i added the path provider dependency. Post adding the dependency keep getting 

/Volumes/SDCard/InventionLabs/AvazAAC/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:18: error: cannot find symbol
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());


The GeneratedPluginRegistrant is auto generated. Deleting it or flutter clean and rebuild doesnt work

**Comment by VigneshPasupathy** [comment] 2020-10-20 08:27
Update: The isssue went away when i fixed the path_provider version to 
dependencies:
   path_provider: 1.6.17

Not sure about the exact reason though
