### ISSUE TITLE
 platformViewRegistry.registerViewFactory func  is missing in import dart.ui 

### ISSUE THREAD

**Issue by zengfr** [flutter/flutter#41563] opened 2019-09-29 11:38 UTC
Upgrading-from-package:flutter_web-to-the-Flutter-SDK in flutter>=1.9  
 import 'package:flutter_web_ui/ui.dart' as ui change to import 'dart.ui '  
 ui.platformViewRegistry.registerViewFactory func   is missing.

```dart
import 'package:flutter_web_ui/ui.dart' as ui;
 ui.platformViewRegistry.registerViewFactory(
        'maphtml',
            (int viewId) => IFrameElement()
          ..allowFullscreen=true
          ..height = '360'
          ..src = 'https://github.com/zengfr?'+_params
          ..style.border = 'none');
```

https://github.com/flutter/flutter/wiki/Upgrading-from-package:flutter_web-to-the-Flutter-SDK
Update the pubspec.yaml
Change:
dependencies:
  flutter_web: any
  flutter_web_ui: any
to:
dependencies:
  flutter:
    sdk: flutter

**Comment by GaspardMerten** [comment] 2019-09-29 12:04
The problem is just that the analyser version of Flutter does not _yet_ support dart:ui or dart:js! So you should be able to build your app and it will work as expected because the version of Flutter that is used to build/run has dart:ui!

**Comment by escamoteur** [comment] 2019-09-29 12:22
For Flutter Web I recommend to use the master channel.
Could you please add the output of flutter doctor - v here

**Comment by zengfr** [comment] 2019-09-29 12:25
> For Flutter Web I recommend to use the master channel.
> Could you please add the output of flutter doctor - v here

E:\javaproject\flutterwebdemo\examples\myweb>flutter doctor - v
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.7-pre.70, on Microsoft Windows [Version 10.0.10240], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] Connected device (2 available)

• No issues found!

E:\javaproject\flutterwebdemo\examples\myweb>

**Comment by escamoteur** [comment] 2019-09-29 12:41
Do you still have the problem?

**Comment by zengfr** [comment] 2019-09-29 13:57
is use  D:\flutter>flutter upgrade  Still have problems  
 

 error: The name 'platformViewRegistry' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix. (undefined_prefixed_name at [myweb] lib\agent\map.dart:12)  

import 'dart:html';
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

class MapPage extends StatefulWidget {
 final String _params;

  MapPage({String params}) : _params = params;

  @override
  State<StatefulWidget> createState() {
    ui.platformViewRegistry.registerViewFactory(
        'maphtml',
        (int viewId) => IFrameElement()

Flutter 1.10.7-pre.73 • channel master • https://github.com/flutter/flutter.git
Framework • revision 67b5bdf99b (16 hours ago) • 2019-09-28 14:24:46 -0700
Engine • revision 5b952f286f
Tools • Dart 2.6.0 (build 2.6.0-dev.3.0 6ff8d2199d)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.7-pre.73, on Microsoft Windows [Version 10.0.10240], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] Connected device (2 available)

• No issues found!

D:\flutter>

**Comment by Abhilash-Chandran** [comment] 2019-09-30 15:04
Same issue in my case. 

[√] Flutter (Channel master, v1.10.7-pre.79, on Microsoft Windows [Version 10.0.17134.950], locale de-DE)
    • Flutter version 1.10.7-pre.79 at C:\Abhilash\Installs\flutter
    • Framework revision 7e73cd74b1 (77 minutes ago), 2019-09-30 14:45:30 +0100
    • Engine revision 5b952f286f
    • Dart version 2.6.0 (build 2.6.0-dev.3.0 6ff8d2199d)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\xyz\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Users\xyz\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.5791312\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\xyz\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\xyz\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5692245
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\xyz\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.5791312
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\xyz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!

**Comment by rxlabz** [comment] 2019-10-04 09:13
Same for me

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.11-pre.3, on Mac OS X 10.14.6 18G103, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)

**Comment by rostopira** [comment] 2019-10-04 10:15
Why can't we just add empty function with same declaration in ios/android engine to silence this warning? That shouldn't  take a week to fix

**Comment by escamoteur** [comment] 2019-10-04 10:35
@rostopira Flutter Web is still in preview. 5 days ago we got this reported. We currently over 5000 open issues so it depends on the priority an issue has how fast it is Fixed.
You can make a PR to speed up things

**Comment by jan-pavlovsky** [comment] 2019-10-30 07:50
Facing the same issue now and it is a real show-breaker unfortunately :/ Would be great if this could be fixed soooon... Thanks :)

**Comment by Fox32** [comment] 2019-10-30 11:13
As it compiles and is only an analyser issue, you can ignore it for just that line as a workaround:

```
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry
        .registerViewFactory(...);
```

**Comment by venshine** [comment] 2019-11-01 07:53
> As it compiles and is only an analyser issue, you can ignore it for just that line as a workaround:
> 
> ```
>     // ignore: undefined_prefixed_name
>     ui.platformViewRegistry
>         .registerViewFactory(...);
> ```

Well, It's good for me.

**Comment by carman247** [comment] 2020-02-19 22:20
> The problem is just that the analyser version of Flutter does not _yet_ support dart:ui or dart:js! So you should be able to build your app and it will work as expected because the version of Flutter that is used to build/run has dart:ui!

Thank you! This had me so confused

**Comment by yasinarik** [comment] 2020-05-11 14:47
```
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory('drop_zone_div', (int viewId) {
      return innerDivElement;
    });
```

Today I have upgraded from **1.15.3 dev** channel ---> to **1.19.0-1.0.pre.27 master** channel and the above code works no more. It doesn't ignore and shows it as an error always.

**Comment by muhleder** [comment] 2020-05-11 15:08
@yasinarik In your analysis_options.yaml you can add a global

```
analyzer:
  errors:
    undefined_prefixed_name: ignore
```

Not sure if that can be restricted to just the one file.

**Comment by muhleder** [comment] 2020-05-11 15:11
I'm using a conditional import personally

```
// UiFake.dart
// ignore: camel_case_types
class platformViewRegistry {
  static registerViewFactory(String viewId, dynamic cb) {}
}
```

and then where I want to use dart:ui

```
import './UiFake.dart' if (dart.library.html) 'dart:ui' as ui;
```

**Comment by yasinarik** [comment] 2020-05-11 15:35
@muhleder Thank you for the very quick response, first of all. 

`// ignore: undefined_prefixed_name` 

Actually this line doesn't work for me at the moment. It **was working before** I upgraded to the latest one. (I mean I was using it with the ignore comment already to ignore the error.)

Without this line working, I think your conditional import didn't work for me too.

Your approach is very fine for me. However, I keep a separate project for the web app. I also have this issue in a single file. 

Edited the .yaml file yet it couldn't help :(

Which version/channel are you using currently?

**Comment by muhleder** [comment] 2020-05-11 16:11
@yasinarik  The conditional import technique doesn't require that `// ignore: undefined_prefixed_name` to work, I haven't been using that particular `ignore` for a while.

If you edit your analysis_options.yaml you will need to restart the dart analysis server for it to pick up the changes. I just press the button in Intellij and wait a bit for it to restart.

I'm on the master branch, ran into the same issues when I updated a few weeks(?) ago with a different analysis error. I'll see if I can find another issue where this came up.

**Comment by muhleder** [comment] 2020-05-11 16:14
@yasinarik  Here's the PR where I found this workaround https://github.com/flutter/plugins/pull/2658

**Comment by yasinarik** [comment] 2020-05-11 16:39
@muhleder Thank you so much for taking care.

I've got some serious and urgent things to build at the moment. There were some other issues about the shared_preferences package. I didn't have the time to fix those. So I've just downgraded to **1.16.3 master channel**. Thus, I can't test if it works with the **latest version**. (I believe it works. I'll try tomorrow.)

But OK. For the current version, `// ignore: undefined_prefixed_name` works too.

I was mistaken while trying the solution you showed which is adding:

```
analyzer:
  errors:
    undefined_prefixed_name: ignore
```

This YAML file is located at: `.../flutter/packages/flutter/lib/analysis_options_user.yaml`

So you were right. Thanks for resolving a headache ☺️👍🏻

**Comment by BrutalCoding** [comment] 2020-05-17 09:42
> @muhleder Thank you so much for taking care.
> 
> I've got some serious and urgent things to build at the moment. There were some other issues about the shared_preferences package. I didn't have the time to fix those. So I've just downgraded to **1.16.3 master channel**. Thus, I can't test if it works with the **latest version**. (I believe it works. I'll try tomorrow.)
> 
> But OK. For the current version, `// ignore: undefined_prefixed_name` works too.
> 
> I was mistaken while trying the solution you showed which is adding:
> 
> ```
> analyzer:
>   errors:
>     undefined_prefixed_name: ignore
> ```
> 
> This YAML file is located at: `.../flutter/packages/flutter/lib/analysis_options_user.yaml`
> 
> So you were right. Thanks for resolving a headache ☺️👍🏻

I don't recommend editing that file, since its part of the flutter SDK and I think you should leave that untouched. According to https://dart.dev/guides/language/analysis-options, you can simply create an analysis_options.yaml next to your pubspec.yaml file (same folder). I just tried and that works. The analysis_options.yaml file should just contain:
```
analyzer:
    errors:
      undefined_prefixed_name: ignore
```

**Comment by yasinarik** [comment] 2020-05-17 09:47
@BrutalCoding oh well of course editing the SDK wasn’t appropriate. 

Thank you for providing this. I didn’t know it and will make the changes asap. 😊

**Comment by tatiblockchain** [comment] 2020-05-21 08:52
I have tested it, the code works even with the warning - so it is an analyser issue.

**Comment by natebosch** [comment] 2020-05-21 17:24
> it is an analyser issue.

We don't support having different APIs across conditional imports (but unfortunately don't have good static checking for that). There are potential improvements we could make to improve the static checking for identical surface area of conditional imports, but the root cause is a flutter issue. `dart:ui` needs to have a consistent set of APIs across all platforms.

**Comment by ditman** [comment] 2020-05-21 18:26
@hterkelsen is currently working on moving this web-only methods from dart:ui to a web-only location so the analyzer is happy with our programs again.

**Comment by wliumelb** [comment] 2020-05-29 01:59
> I'm using a conditional import personally
> 
> ```
> // UiFake.dart
> // ignore: camel_case_types
> class platformViewRegistry {
>   static registerViewFactory(String viewId, dynamic cb) {}
> }
> ```
> 
> and then where I want to use dart:ui
> 
> ```
> import './UiFake.dart' if (dart.library.html) 'dart:ui' as ui;
> ```

Nice hack for now :) 
Hope this could get fixed soon.

**Comment by pedromassangocode** [comment] 2020-08-25 10:56
> @hterkelsen is currently working on moving this web-only methods from dart:ui to a web-only location so the analyzer is happy with our programs again.

@hterkelsen can you confirm if this is now tru on the current `master` channel so that we can close this issue?

**Comment by ditman** [comment] 2020-08-25 17:24
No, AFAIK this cannot be closed yet.

**Comment by TahaTesser** [comment] 2020-09-03 13:14
This issue still exists on the latest`master

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
// import 'dart:io' if (dart.library.html) 'dart:ui' as ui;
import 'dart:ui' as ui;
import 'dart:html' as html;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Iframe()),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class Iframe extends StatelessWidget {
  Iframe() {
    ui.platformViewRegistry.registerViewFactory('iframe', (int viewId) {
      var iframe = html.IFrameElement();
      iframe.src = 'https://flutter.dev';
      return iframe;
    });
  }
  @override
  Widget build(BuildContext context) {
    return Container(
        width: 400, height: 300, child: HtmlElementView(viewType: 'iframe'));
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.65, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.65 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2032a448ed (6 hours ago), 2020-09-02 23:36:19 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.7
    • iPhone 11 (mobile)     • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X
      10.15.6 19G2021
    • Web Server (web)       • web-server                           • web-javascript • Flutter
      Tools
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 85.0.4183.83

• No issues found!

```

</details> 

The only way is to use following
```
analyzer:
  errors:
    undefined_prefixed_name: ignore
```

**Comment by KedwithGod** [comment] 2020-09-10 09:35
> Upgrading-from-package:flutter_web-to-the-Flutter-SDK in flutter>=1.9
> import 'package:flutter_web_ui/ui.dart' as ui change to import 'dart.ui '
> ui.platformViewRegistry.registerViewFactory func is missing.
> 
> ```dart
> import 'package:flutter_web_ui/ui.dart' as ui;
>  ui.platformViewRegistry.registerViewFactory(
>         'maphtml',
>             (int viewId) => IFrameElement()
>           ..allowFullscreen=true
>           ..height = '360'
>           ..src = 'https://github.com/zengfr?'+_params
>           ..style.border = 'none');
> ```
> 
> https://github.com/flutter/flutter/wiki/Upgrading-from-package:flutter_web-to-the-Flutter-SDK
> Update the pubspec.yaml
> Change:
> dependencies:
> flutter_web: any
> flutter_web_ui: any
> to:
> dependencies:
> flutter:
> sdk: flutter

flutter_web_ui:  has been changed to flutter_for_web_ui:

**Comment by aguilaair** [comment] 2020-11-22 19:08
Hey!

I'm trying to release a package on pub.dev which uses `registerViewFactory` to create an iFrame, this causes my plugin to drop 30 points in the score and the platforms to become unidentified. 

Can anything be done to tell pub.dev to ignore this issue?

**Comment by creativecreatorormaybenot** [comment] 2020-11-22 20:17
@aguilaair Yes, you can create a stub.

**Comment by flutterlabz** [comment] 2020-12-07 12:00
As an alternative solution, I created a plugin.

NOTE:
This solution is not my idea,
I just published it to pub.dev to make it easier to use.

https://pub.dev/packages/universal_ui

How To Use:
Import the package.

`import 'package: universal_ui / universal_ui.dart';`


Then, use the ui object as usual.
You don't need to create an alias.


```
ui.platformViewRegistry.registerViewFactory (
    'iframeElement',
    (int viewId) => _iframeElement,
);
```

**Comment by migalv** [comment] 2021-01-18 10:54
> This issue still exists on the latest`master
> 
> code sample
> flutter doctor -v
> The only way is to use following
> 
> ```
> analyzer:
>   errors:
>     undefined_prefixed_name: ignore
> ```

@TahaTesser This does not work anymore for some reason.

I even tried to exclude the file where I use the `ui.platformViewRegistry` but the analyzer keeps showing the error.

<details>
 <summary>analyzer_options.yaml</summary>

```
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - lib/widgets/google_map.dart

  errors:
    undefined_prefixed_name: ignore
```


</details>

<details>
 <summary>flutter doctor</summary>

```
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [VersiÃ³n 10.0.19041.746], locale es-ES)
    • Flutter version 1.25.0-8.3.pre at C:\src\flutter
    • Framework revision 5d36f2e7f5 (3 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\migal\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\migal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```

</details>

**Comment by ditman** [comment] 2021-01-19 19:51
@migalv correct, the analyzer is not tolerating this anymore. The current solution involves creating a [stub](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter_web/lib/src/shims), or maybe using the plugin created by @flutterlabz [here](https://github.com/flutter/flutter/issues/41563#issuecomment-739873993).

**Comment by jannikhst** [comment] 2021-01-24 11:26
https://stackoverflow.com/questions/65869727/flutter-web-iframe-weird-behavior
Why does it not work anymore?

**Comment by sabowsla** [comment] 2021-02-21 22:39
> @migalv correct, the analyzer is not tolerating this anymore. The current solution involves creating a [stub](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter_web/lib/src/shims), or maybe using the plugin created by @flutterlabz [here](https://github.com/flutter/flutter/issues/41563#issuecomment-739873993).

this worked for me

**Comment by dvaldivia** [comment] 2021-03-07 21:40
it'd be nice if  the solution by @flutterlabz is posted to github so we can move it to null safety, this missing ui is preventing upgrades to null safety

**Comment by ditman** [comment] 2021-03-08 22:03
@dvaldivia looks like it is? https://github.com/flutterlabz/universal_ui

**Comment by dvaldivia** [comment] 2021-03-08 22:27
@ditman thanks! it's not on pub.dev so I totally missed it

**Comment by ditman** [comment] 2021-03-08 23:13
> @ditman thanks! it's not on pub.dev so I totally missed it

That's also a good contribution for the pubspec.yaml of the package, add a `repository` entry haha :P

**Comment by singerdmx** [comment] 2021-03-26 19:09
Is this fixed? Our pub https://pub.dev/packages/flutter_quill/score is missing 30 points because of this

**Comment by ditman** [comment] 2021-03-30 00:27
@singerdmx it seems you rolled your own fix for this.

**Comment by singerdmx** [comment] 2021-03-30 00:27
I remove the code
It is not fix

**Comment by LautaroLobo12** [comment] 2021-04-09 19:41
I'm facing this issue too. Using Dart SDK 2.12.2 and Flutter 2.0.3.

**Comment by jeremiahlukus** [comment] 2021-04-13 17:18
same issue..

```
± |master ✓| → flutter --version
Flutter 2.1.0-12.2.pre • channel beta • git@github.com:flutter/flutter.git
Framework • revision 5bedb7b1d5 (4 weeks ago) • 2021-03-17 17:06:30 -0700
Engine • revision 711ab3fda0
Tools • Dart 2.13.0 (build 2.13.0-116.0.dev)


± |master U:1 ✗| → dart --version
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"
```

**Comment by LautaroLobo12** [comment] 2021-04-15 15:23
I solved it by reading the docs, lol

> For android, You must have to update minSdkVersion to 21 (or higher).

From the [Take a picture using the camera](https://flutter.dev/docs/cookbook/plugins/picture-using-camera) tutorial.

**Comment by AdeAnima** [comment] 2021-04-21 21:08
Same issue here. 

> I solved it by reading the docs, lol
> 
> > For android, You must have to update minSdkVersion to 21 (or higher).
> 
> From the [Take a picture using the camera](https://flutter.dev/docs/cookbook/plugins/picture-using-camera) tutorial.

Honestly no idea, how this should solve this problem ^^

**Comment by AdeAnima** [comment] 2021-05-23 17:16
Honestly emberassing that this is still open after 2 years

**Comment by creativecreatorormaybenot** [comment] 2021-05-23 19:35
What are you saying @AdeAnima?

This is only a minor inconvenience.  
You can simply use the shim ([example here](https://github.com/flutter/flutter/issues/41563#issuecomment-794384561)) and you are good to go! So this is not an actual problem.

**Comment by lirantzairi** [comment] 2021-10-13 14:28
In both iOS and Android, the PlatformViewFactory is a class that has a `create(...)` method which can take a dynamic `args` parameter. This way the view can be created with arguments (there are many use cases for this). However, in dart web it seems (correct me if I'm wrong) that the `PlatformViewFactory` is a dypedef for a function that only gets the view ID and returns an html element.
Allowing to pass arguments is very important. Can you please support this?

Thanks.

**Comment by RafiqCR7** [comment] 2022-06-29 17:01
> What are you saying @AdeAnima?
> 
> This is only a minor inconvenience. You can simply use the shim ([example here](https://github.com/flutter/flutter/issues/41563#issuecomment-794384561)) and you are good to go! So this is not an actual problem.

How can you make use of the shim?

**Comment by ditman** [comment] 2022-06-29 23:39
> How can you make use of the shim?

@RafiqCR7 you import `ui` from the shim, instead of directly. See this:

* https://github.com/flutter/plugins/blob/670ade44963f9ba307a258331419dc42ff5ca91f/packages/video_player/video_player_web/lib/video_player_web.dart#L12

**Comment by RoyalNewScoolCode** [comment] 2022-11-20 20:44
> It compiles for web but fails on mobile. I'm using conditional imports as a workaround for that.
> 
> FakeUi.dart
> 
> ```
> // ignore: camel_case_types
> class platformViewRegistry {
>   static registerViewFactory(String viewId, dynamic cb) {}
> }
> ```
> 
> RealUi.dart
> 
> ```
> import 'dart:ui' as ui;
> 
> // ignore: camel_case_types
> class platformViewRegistry {
>   static registerViewFactory(String viewId, dynamic cb) {
>     // ignore:undefined_prefixed_name
>     ui.platformViewRegistry.registerViewFactory(viewId, cb);
>   }
> }
> ```
> 
> and then to use in a widget
> 
> ```
> import 'FakeUi.dart' if (dart.library.html) 'RealUi.dart' as ui;
> ```

**Comment by RoyalNewScoolCode** [comment] 2022-11-20 20:45
thanks ..this help me a lot

**Comment by ditman** [comment] 2023-05-19 23:38
# A fix for this is finally coming!! https://github.com/flutter/engine/pull/41877 🎉

**Closed** 2023-05-23 16:17 UTC
Labels: framework, customer: crowd, platform-web, a: build, a: error message, has reproducible steps, P3, found in release: 1.22

**Comment by NotTsunami** [comment] 2023-05-23 22:10
> # A fix for this is finally coming!! [flutter/engine#41877](https://github.com/flutter/engine/pull/41877) 🎉
> The new API will be something like:
> 
> ```dart
> import 'dart:ui_web' as ui_web; // New import for all web-only stuff...
> 
> ...
> 
> ui_web.platformViewRegistry.registerViewFactory(...); // as usual!
> ```

This is fantastic. I hope to see it land in the next stable version!
