### ISSUE TITLE
flutter.h not found

### ISSUE THREAD

**Issue by rohitsainik** [flutter/flutter#79936] opened 2021-04-07 09:43 UTC
I am stuck on these issue from last one month tried almost all the solution but still not able to figure of how to resolve it my app is in already uploaded on AppStore and I have to give a new update but due to these issue i am not able to create new build please someone help me out with these.

```
  In file included from
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/JavaScriptChannelHandler.m:5:
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/JavaScriptChannelHandler.h:5:9: fatal error:
    'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FlutterWebView.m:5:
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FlutterWebView.h:5:9: fatal error:
    'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FLTWebViewFlutterPlugin.m:5:
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FLTWebViewFlutterPlugin.h:5:9: fatal error:
    'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FLTWKProgressionDelegate.m:5:
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FLTWKProgressionDelegate.h:5:9: fatal error:
    'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FLTWKNavigationDelegate.m:5:
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FLTWKNavigationDelegate.h:5:9: fatal error:
    'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FLTCookieManager.m:5:
    /Users/rohitsainik/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.3/ios/Classes/FLTCookieManager.h:5:9: fatal error:
    'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
```

**Comment by TahaTesser** [comment] 2021-04-07 12:30
Hi @rohitsainik 
Make sure you're on the latest `stable` flutter and try following 
https://github.com/flutter/flutter/issues/70895#issuecomment-744734693
https://github.com/flutter/flutter/issues/70895#issuecomment-792755327

Duplicate of https://github.com/flutter/flutter/issues/70895

**Comment by nt4f04uNd** [comment] 2021-04-07 20:03
duplicate of https://github.com/flutter/flutter/issues/79920

**Comment by pedromassangocode** [comment] 2021-04-28 10:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-28 10:08 UTC
Labels: in triage, waiting for customer response
