### ISSUE TITLE
Unsigned binaries on Catalina (Flutter Dev Channel)

### ISSUE THREAD

**Issue by Shchvova** [flutter/flutter#50540] opened 2020-02-11 05:32 UTC
## Steps to Reproduce
1. Update flutter to Dev Channel (on Stable it is even worse!)
2. `flutter run`
3. Get an error `“iproxy” cannot be opened because the developer cannot be verified.`
<img width="532" alt="image" src="https://user-images.githubusercontent.com/130387/74213085-8d8ea380-4cd2-11ea-8255-9c20e8262f69.png">

## Logs

```
➜  mytestapp flutter run -v
........... lots of log .........
[ +113 ms] Process 26099 detached
[  +39 ms] Application launched on the device. Waiting for observatory port.
[   +3 ms] Checking for advertised Dart observatories...
[+5017 ms] Checking for available port on com.coronalabs.iCloudTestApp._dartobservatory._tcp.local
[   +1 ms] Checking for authentication code for com.coronalabs.iCloudTestApp._dartobservatory._tcp.local
[   +3 ms] Attempting to forward device port 62338 to host port 1024
[        ] executing: /Users/vlad/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy 1024 62338 00008020-000B182C0CF8002E
[+1045 ms] Forwarded port ForwardedPort HOST:1024 to DEVICE:62338
[   +1 ms] Installing and launching... (completed in 31.1s)
[   +5 ms] Connecting to service protocol: http://127.0.0.1:1024/Lz38jvpw4IQ=/
[  +10 ms] Exception attempting to connect to Observatory: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 59456
[        ] This was attempt #1. Will retry in 0:00:00.100000.
[ +105 ms] Exception attempting to connect to Observatory: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 59457
[        ] This was attempt #2. Will retry in 0:00:00.200000.
[ +206 ms] Exception attempting to connect to Observatory: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 59458
[        ] This was attempt #3. Will retry in 0:00:00.400000.
[ +407 ms] Exception attempting to connect to Observatory: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 59459
[        ] This was attempt #4. Will retry in 0:00:00.800000.
[ +804 ms] Exception attempting to connect to Observatory: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 59460
[        ] This was attempt #5. Will retry in 0:00:01.600000.
[+1602 ms] Exception attempting to connect to Observatory: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 59461
[        ] This was attempt #6. Will retry in 0:00:01.600000.
... keeps repeating ....
```

```
➜  mytestapp flutter doctor -v
[✓] Flutter (Channel dev, v1.15.2, on Mac OS X 10.15.3 19D76, locale en-CA)
    • Flutter version 1.15.2 at /Users/vlad/Library/flutter
    • Framework revision d94ff4bdbe (4 days ago), 2020-02-06 13:19:46 -0800
    • Engine revision f34bc65bee
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 b3396cbdca)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vlad/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • XXXXXX • XXXXXXX-XXXXXXXXX • ios • iOS 13.3

• No issues found!
➜  mytestapp 

```

**Comment by dnfield** [comment] 2020-02-11 06:57
@christopherfujino

**Comment by Shchvova** [comment] 2020-02-11 10:17
Sorry. My bad. Title is wrong. Tool is `codesign`ed, and runtime seems to be hardened, with proper entitlements.
```
➜  tmp codesign -vvvv -R="notarized" --check-notarization  ~/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy
/Users/vlad/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy: valid on disk
/Users/vlad/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy: satisfies its Designated Requirement
/Users/vlad/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy: explicit requirement satisfied
```

**Comment by Shchvova** [comment] 2020-02-11 10:56
If it would be helpful for anyone, I made a script, which check signatures.
Save it to `check_sign.sh`, and use like 
```
./check_sign.sh ~/Library/flutter/bin
```

Script:
```bash
#!/usr/bin/env zsh

set -e

LOCATION="${1:-.}"

while read f
do
	file_result=$(file "$f" -b -h)

	if [[ $file_result == *"Mach-O"*"executable"* ]]
	then
		FS="${f/$HOME/~}"
		if RESULT=$(codesign --verify -v -R="notarized" --check-notarization "$f" 2>&1)
		then
			echo "OK: $FS"
		else
			echo "\e[31mFAIL!: $FS"
			echo "codesign --verify -v -R=\"notarized\" --check-notarization \"$f\""
			echo "${RESULT}\e[39m"
		fi
	fi

done < <(find "$LOCATION" -type f)
```

Sample output:
```
➜  tmp ./check_sign.sh ~/Library/flutter/bin
OK: ~/Library/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
OK: ~/Library/flutter/bin/cache/artifacts/libimobiledevice/idevicename
OK: ~/Library/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog
OK: ~/Library/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo
OK: ~/Library/flutter/bin/cache/artifacts/libimobiledevice/idevicescreenshot
OK: ~/Library/flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller
OK: ~/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy
OK: ~/Library/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot
OK: ~/Library/flutter/bin/cache/artifacts/engine/ios-profile/gen_snapshot_arm64
OK: ~/Library/flutter/bin/cache/artifacts/engine/ios-profile/gen_snapshot_armv7
OK: ~/Library/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester
OK: ~/Library/flutter/bin/cache/artifacts/engine/darwin-x64/font-subset
OK: ~/Library/flutter/bin/cache/artifacts/engine/darwin-x64/gen_snapshot
OK: ~/Library/flutter/bin/cache/artifacts/engine/android-x64-profile/darwin-x64/gen_snapshot
OK: ~/Library/flutter/bin/cache/artifacts/engine/android-arm64-release/darwin-x64/gen_snapshot
OK: ~/Library/flutter/bin/cache/artifacts/engine/ios/gen_snapshot_arm64
OK: ~/Library/flutter/bin/cache/artifacts/engine/ios/gen_snapshot_armv7
OK: ~/Library/flutter/bin/cache/artifacts/engine/android-arm64-profile/darwin-x64/gen_snapshot
OK: ~/Library/flutter/bin/cache/artifacts/engine/android-x64-release/darwin-x64/gen_snapshot
OK: ~/Library/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64
OK: ~/Library/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_armv7
OK: ~/Library/flutter/bin/cache/artifacts/engine/android-arm-profile/darwin-x64/gen_snapshot
OK: ~/Library/flutter/bin/cache/artifacts/ios-deploy/ios-deploy
OK: ~/Library/flutter/bin/cache/dart-sdk/bin/dart
```

Note, that `~/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy` is notarized (and signed). However running it results in error and message from the OS.

**Comment by Shchvova** [comment] 2020-02-11 11:24
By the way. I gave up, and did `sudo xattr  -c ~/Library/flutter/bin/cache/artifacts/usbmuxd/iproxy` which removed quarantine attribute, and it worked.

I don't know what is was going on but it may be a roadblock for new users. Cheers!

**Comment by christopherfujino** [comment] 2020-02-11 18:09
Thanks @Shchvova for filing and doing some digging. As you reported, the binary is codesigned, however it is failing because the binary dynamically links to external path, which gatekeeper is not able to verify. I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/42969, please follow there for discussion and updates!

**Closed by christopherfujino** 2020-02-11 18:09 UTC
Labels: tool, ‎‍💻platform-catalina, ⌘‬ platform-mac
