### ISSUE TITLE
Flutter: When i set video effects it shows black screen preview instead of video preview.

### ISSUE THREAD

**Issue by YogendraAlgo** [flutter/flutter#137563] opened 2023-10-30 19:05 UTC
### Steps to reproduce

I am using Media3 ExoPlayer in flutter. I have just migrated code of plugin [video_player_android](https://github.com/flutter/packages/blob/main/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java#L79) to Media3 ExoPlayer.

It is working perfectly after migration.
Problem: When i set video effects like below snippet it shows black screen instead of video preview.
I am not getting any error or exception in log so i am not able to debug cause.

### Actual results

Problem: When i set video effects like below snippet it shows black screen instead of video preview.
I am not getting any error or exception in log so i am not able to debug cause.

### Code sample

<details><summary>Code sample</summary>

```dart
ExoPlayer exoPlayer = new ExoPlayer.Builder(context).build();
ImmutableList.Builder effects = new ImmutableList.Builder<>();
effects.add(RgbFilter.createInvertedFilter());
exoPlayer.setVideoEffects(effects.build());
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="292" alt="Screenshot 2023-10-31 at 12 24 02 AM" src="https://github.com/flutter/flutter/assets/147655821/b60879c9-dfbc-49bd-a405-78092ffaa5f4">

</details>

**Comment by huycozy** [comment] 2023-10-31 08:36
Hi @YogendraAlgo 
Does this issue occur if you also apply the same effects for ExoPlayer on a native example?

**Comment by YogendraAlgo** [comment] 2023-10-31 10:00
Hi @huycozy 

It will not occur when i apply in native.
`
    private fun initializePlayer() {
        player = ExoPlayer.Builder(this)
                .build()
                .also { exoPlayer ->
                    viewBinding.videoView.player = exoPlayer

                    val effects: ImmutableList.Builder<Effect> = ImmutableList.Builder<Effect>()
                    effects.add(RgbFilter.createInvertedFilter())
                    exoPlayer.setVideoEffects(effects.build())

                    val mediaItem = MediaItem.fromUri("https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4")
                    exoPlayer.repeatMode = Player.REPEAT_MODE_ALL;
                    exoPlayer.setMediaItem(mediaItem)
                    exoPlayer.prepare()
                    exoPlayer.play()
                }
    }
`
<img width="1421" alt="Screenshot 2023-10-31 at 3 28 09 PM" src="https://github.com/flutter/flutter/assets/147655821/48d83ebf-577f-4812-bb61-4bf828ca3195">

**Comment by huycozy** [comment] 2023-11-01 04:00
When try reproducing this on Flutter, I see `RgbFilter` is not found, looks like it's from 3rd dependency, right?

Could you share the forked Flutter project with changes above?

**Comment by YogendraAlgo** [comment] 2023-11-01 10:37
Hi @huycozy 
Please check forked repository.  [Commit Link](https://github.com/YogendraAlgo/packages/commit/e10d45b2eb283f30116f31a2b688daca5b08086a )


### Cause of issue:-I have raised same issue on Media3 repository.
It is using **Surface** for video output which we don't support currently, and due to platform limitation we won't be able to support it. [Media3 Issue Link](https://github.com/androidx/media/issues/779#issuecomment-1787105832)

Is there any way to achieve this in flutter? 
Does flutter support **SurfaceView** and **SurfaceHolder** as mentioned by Media3 team?

**Comment by huycozy** [comment] 2023-11-02 04:40
Thanks for the update. 

>Does flutter support SurfaceView and SurfaceHolder as mentioned by Media3 team?

SurfaceView doesn't seem to be supported currently. Please see https://github.com/flutter/flutter/issues/95617; if that proposal can solve your issue, please follow up on it and close this one. You can react to the initial comment or write a comment about your case that will help to raise that issue.

**Closed** 2023-11-02 11:17 UTC
Labels: waiting for customer response, in triage
