### ISSUE TITLE
Font size to scale with Android settings

### ISSUE THREAD

**Issue by Aquinter** [flutter/flutter#10524] opened 2017-06-06 09:12 UTC
The font size of the flutter application does not scale with the Android font size settings.
![screenshot_20170606-110718](https://cloud.githubusercontent.com/assets/6039556/26822053/051cab92-4aa9-11e7-8b77-6669dc7ed402.png)
![screenshot_20170606-110632](https://cloud.githubusercontent.com/assets/6039556/26822045/01d9a21e-4aa9-11e7-807d-831359bc603a.png)

**Comment by eseidelGoogle** [comment] 2017-06-06 14:30
See also https://github.com/flutter/flutter/issues/4815.

**Comment by Hixie** [comment] 2017-06-06 16:00
The framework has support for this it just hasn't been hooked up.

**Comment by gspencergoog** [comment] 2017-09-16 00:25
So, @Hixie, when you say that the framework has support for it, can you elaborate?

Is it a matter of hooking it into the engine someplace [like here in RenderStyle.cpp](https://github.com/flutter/engine/blob/08961f8ec5d3ee9ecc55bf4e9474ea37b0480c2b/sky/engine/core/rendering/style/RenderStyle.cpp#L829), or is there someplace higher up that you're thinking of?  And is this only on Android?  Does iOS already work?

**Comment by Hixie** [comment] 2017-09-16 18:35
we pass a textScaleFactor value around all over the place. We just never populate it with anything other than 1.0 yet. We need to get the number from the OS to the framework somehow, then the framework needs to put it into the DefaultTextStyle or the Theme's TextTheme or some such.

**Comment by gspencergoog** [comment] 2017-09-18 20:15
Just a note that the iOS version of this issue is #4815

**Comment by gspencergoog** [comment] 2017-10-10 17:57
Closing this because it's fixed on Android.  iOS has #4815 to track this featerh for that platform.  Also see #12311 to track issues in individual widgets caused by setting textScaleFactor.

**Closed by gspencergoog** 2017-10-10 17:57 UTC
Labels: prod: accessibility, prod: engine, ▣ platform-android
