### ISSUE TITLE
`flutter doctor` should account for Android Studio Electric Eel changed folder structure

### ISSUE THREAD

**Issue by Amphaal** [flutter/flutter#119909] opened 2023-02-03 09:15 UTC
When Android Studio Electric Eel is installed on a local development machine, a `flutter doctor` run goes like this:

```
/Users/guillaumevara/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-arm64, locale fr-FR)
    • Flutter version 3.7.1 on channel stable at /Users/guillaumevara/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (il y a 2 jours), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/guillaumevara/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /Users/guillaumevara/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.58+23-CA (build 11.0.16.1+1-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

And yet, everything works perfectly on Android Studio when using an flutter project. 

Following this https://stackoverflow.com/questions/75106727/android-studio-electric-eel-unable-to-find-bundled-java-version-issue, we find that Electric Eel changed the default JRE folder name for some reason. I guess the flutter cli should search for the folder `jbr` instead of `jre` starting with this specific Android Studio release.

**Comment by christopherfujino** [comment] 2023-02-04 00:55
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/pull/119244. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2023-02-04 00:55 UTC
