### ISSUE TITLE
TabbarView unable to keep scroll position of a stateful widget

### ISSUE THREAD

**Issue by zainulhassan815** [flutter/flutter#89503] opened 2021-09-05 14:08 UTC
## Steps to Reproduce
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter TabbarView Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'TabbarView in Slivers'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
          body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxIsScrolled) => [
          SliverAppBar(
            floating: true,
            pinned: true,
            title: Text(title),
            bottom: TabBar(
              tabs: [
                Tab(
                  text: 'Page 1',
                ),
                Tab(
                  text: 'Page 2',
                ),
                Tab(
                  text: 'Page 3',
                ),
              ],
            ),
          ),
        ],
        body: TabBarView(
          children: <Widget>[
            ListPage(
              key: PageStorageKey<String>('Page1'),
            ),
            ListPage(
              key: PageStorageKey<String>('Page2'),
            ),
            ListPage(
              key: PageStorageKey<String>('Page3'),
            ),
          ],
        ),
      )),
    );
  }
}

/// This is a simple statefull widget that shows a list of items.
/// Whenever it is scrolled back up, all the pages return to a
/// scroll position of 0.
class ListPage extends StatefulWidget {
  const ListPage({Key? key}) : super(key: key);

  @override
  _ListPageState createState() => _ListPageState();
}

class _ListPageState extends State<ListPage> {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: [
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (context, index) {
              return ListTile(
                title: Text('Item : $index'),
              );
            },
            childCount: 30,
          ),
        ),
      ],
    );
  }
}

```
**Issue:** When using stateful widgets inside tabbar view, the scroll positions of inner scrollable widgets is not preserved. And whenever the list is scrolled, pages loose their actual scroll location and return back to zero.

Read more about the actual issue that I encountered in my app here : [Stackoverflow](https://stackoverflow.com/questions/69002803/flutter-tabbarview-not-keeping-scroll-position-even-after-using-keys)

**Expected results:** The pages should keep their scroll positions when tabs are changed.

**Actual results:**  Pages loose their scroll position when list is scrolled.

<details>
  <summary>Logs</summary>

```
[  +60 ms] Connected to _flutterView/0xd452f810.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[  +34 ms] q Quit (terminate the application on the device).
[   +4 ms] 💪 Running with sound null safety 💪
[   +1 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:64474/CMn69zJDx4o=/
[ +255 ms] D/EGL_emulation(26957): eglMakeCurrent: 0xd44d7060: ver 2 0 (tinfo 0xd7abdc00)
[ +104 ms] D/eglCodecCommon(26957): setVertexArrayObject: set vao to 0 (0) 1 0
[ +476 ms] The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
                    http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A64474%2FCMn69zJDx4o%3D%2F
```

```
Analyzing bug...
No issues found! (ran in 18.3s)
```

```
 [✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DreamersLab\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\DreamersLab\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_261\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)        
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[☠] Android Studio (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at     
      https://github.com/flutter/flutter/issues.
    ✗ FileSystemException: Exists failed, path = 'C:\Program Files\Android\Android Studio" .plugins' (OS Error: The filename, directory name, or      volume label syntax is incorrect.
      , errno = 123)
    • #0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
      #1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
      #2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:479:22)
      #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
      #4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:478:12)
      #5      AndroidStudio.pluginsPath (package:flutter_tools/src/android/android_studio.dart:186:52)
      #6      AndroidStudioValidator.validate (package:flutter_tools/src/android/android_studio_validator.dart:46:17)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #9      _rootRun (dart:async/zone.dart:1354:13)
      #10     _CustomZone.run (dart:async/zone.dart:1258:19)
      #11     _runZoned (dart:async/zone.dart:1789:10)
      #12     runZonedGuarded (dart:async/zone.dart:1777:12)
      #13     runZoned (dart:async/zone.dart:1708:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:199:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:303:47)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1192:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>


[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.0)
    • VS Code at C:\Users\DreamersLab\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 93.0.961.38 
```

</details>

**Comment by TahaTesser** [comment] 2021-09-06 10:29
Hi @zainulhassan815 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/36419
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-06 10:29 UTC
Labels: in triage
