### ISSUE TITLE
couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by lovepreetSinghElectricpe** [flutter/flutter#122022] opened 2023-03-06 16:43 UTC
Got this crash report from Firebase.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wattapp.electricpe/com.wattapp.electricpe.consumer_app.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/androidx.test.tools.crawler-P_6_RmV_XbDEoTwEJL1YvA==/base.apk", zip file "/data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/base.apk", zip file "/data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/split_config.kn.apk", zip file "/data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/split_config.x86.apk", zip file "/data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-P_6_RmV_XbDEoTwEJL1YvA==/lib/x86, /data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/lib/x86, /data/app/androidx.test.tools.crawler-P_6_RmV_XbDEoTwEJL1YvA==/base.apk!/lib/x86, /data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/base.apk!/lib/x86, /data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/split_config.kn.apk!/lib/x86, /data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/split_config.x86.apk!/lib/x86, /data/app/com.wattapp.electricpe-ec5ia-z7tBOShWwUpLfmQg==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
## Steps to Reproduce

We are not able to reproduce it, but is occurring only android OS

**Comment by lovepreetSinghElectricpe** [comment] 2023-03-06 16:44
Devices are running on x86 on which it is occurring

**Comment by darshankawar** [comment] 2023-03-07 06:41
Closing this as duplicate of https://github.com/flutter/flutter/issues/83596.

**Closed by darshankawar** 2023-03-07 06:41 UTC
Labels: in triage
