### ISSUE TITLE
google_sign_in - Using custom back-end id to get token

### ISSUE THREAD

**Issue by calebisstupid** [flutter/flutter#17813] opened 2018-05-22 18:10 UTC
I am relatively new to flutter, but as far as I can tell, the google sign in flutter plugin does not allow you to authenticate with a custom back end using sign in options such as:
`.requestIdToken(getString(R.string.server_client_id))`

I can login to my google account no issues, but my idToken is always null, which is something we would need to have for our back-end system.

Am I completely misunderstanding how to use this?

**Comment by matthew5025** [comment] 2018-05-25 16:02
Is this a duplicate of #16613?

**Comment by calebisstupid** [comment] 2018-05-25 17:29
Nope. I do not use Firebase. We have a custom back-end server that I needed to send an idToken to for our mobile clients. In our case, we build a workaround by grabbing the authToken and having our back-end authorize with google on the mobile device's behalf, but this was not the "ideal" approach.

**Comment by matthew5025** [comment] 2018-05-25 17:33
Yes, I too don't use firebase, but you do need to create a firebase project to generate the google-services.json file that is needed.

**Comment by matthew5025** [comment] 2018-05-25 17:35
I think what that guy is saying is that he uses firebase, but wants an alternative.

Anyway, feel free to try the steps I've posted there, I'm not using firebase auth and it's working for me.

**Comment by matthew5025** [comment] 2018-05-25 18:57
@calebisstupid The theory is that basically you configure your android app for google sign in (gradle dependencies, cred tokens etc) and when configured correctly, you'll get the idToken automatically.

The important part is the google-services.json file, and the Google Services gradle plugin, which automatically creates two XML files with string values, the most critical being "default_web_client_id"; without which you'll not get an idToken.

In theory it would be possible to self generate the json file or even the XML file, but I've taken the simplest way out here. You should be able to find more info in the link below.

https://developers.google.com/android/guides/google-services-plugin

**Comment by calebisstupid** [comment] 2018-05-25 19:43
@matthew5025 that totally makes sense. thanks for helping explain it all. I would say this is more of a duplicate of #16613 now that I understand the details of your workaround.

**Closed** 2018-08-30 22:02 UTC
Labels: p: first party, plugin

**Comment by laertispappas** [comment] 2018-09-23 02:47
Hi @calebisstupid 

can you please confirm that verifying the `idToken` works to google api? I'm trying to verify the token on the backend (no firebase) but I'm getting `wrong value` from the corresponding endpoint. Sending the access token it works though.

```
GET https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=12345 (Fails)
GET https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=999999 (Succeeds)
```

thank you in advance.

**Comment by DJafari** [comment] 2019-02-04 01:33
i think until this [PullRequest](https://github.com/flutter/plugins/pull/879) merged, this bug can't solved

**Comment by 5hanth** [comment] 2019-11-07 08:14
+1
