### ISSUE TITLE
[Image_picker][iOS] Image picker  returned selected image is rotated 90 degrees

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#37688] opened 2019-08-06 12:14 UTC
When using image_picker: ^0.6.1 (in iOS only) and simply selecting an image from the camera gallery, the image will be rotated 90 degrees.

**Edit: after below discussion: Problem only occurs when using maxHeight,maxWidth parameters of image_picker.**

**Comment by liaobushi520** [comment] 2019-08-06 12:27
denpend on your device.

**Comment by htsnet** [comment] 2019-08-07 12:17
in iOS I realised this behavior, in Android is OK

**Comment by cyanglaz** [comment] 2019-08-09 15:58
related https://github.com/flutter/flutter/issues/35334. It is likely an issue with the image widget.
@mikron123 If you use image_picker prior to 0.6.0+5, does it work?

**Comment by g-balas** [comment] 2019-08-14 13:49
Thanks to @cyanglaz, changing the version of image_picker from image_picker: ^0.6.1+2 to image_picker: 0.6.0+5 fix this issue on the orientation bug on iOS.

Looks good on Android also.

This issue seems to be a regression.

**Comment by mikron123** [comment] 2019-08-14 14:53
@cyanglaz Yes it indeed worked, thanks! But what does it mean in terms of package updates..? they don't intend to reincorporate the fix back?

**Comment by cyanglaz** [comment] 2019-08-14 15:42
@g-balas @mikron123 Could any of you provide a minimum app to reproduce the issue when you used 0.6.1+2?
I couldn't reproduce the issue with the example app in the plugin.

**Comment by mikron123** [comment] 2019-08-14 17:27
@cyanglaz 

I think it has to do with the pics, as some pics were alright. The code is very straight forward, choose a pic and display it.

I've attached the problematic pic, and her shirt motivates us to solve this problem.. ;)
P.s. The server actually saved the pic correctly after downgrading to 0.6.0+5...


![32BBDD45-11B3-4502-9E52-8B50A7F4EF23](https://user-images.githubusercontent.com/16115860/63041906-8fb5a800-bed1-11e9-81f4-b6dfed1e00a9.jpeg)

**Comment by mikron123** [comment] 2019-08-14 17:28
Now I see that also in GitHub it's in the wrong orientation ! Maybe it lost the data after uploading?!

**Comment by cyanglaz** [comment] 2019-08-14 17:39
@mikron123 So rotated image you uploaded was captured by 0.6.0+5 right? What happens if you upload an image captured with 0.6.1?

**Comment by mikron123** [comment] 2019-08-14 18:46
No, it was captured with my iPhone, and looks just find in the phone's image gallery.
I do not capture pics in the app, only use Image_picker to choose from gallery.
It also looks fine when I display it with an app with 0.6.0+5, but looks rotated with 0.6.1. 
Funny enough, the above picture looks just fine on my mac as well, but when I uploaded it right now to this thread, same thing happened, and it got rotated 90 degrees! I tried in a different pic hosting site and same thing happened.

**Comment by mikron123** [comment] 2019-08-14 18:48
Here is website that didn't fail and displays it the right way:
[https://ibb.co/68Bf5fg](url)

**Comment by cyanglaz** [comment] 2019-08-14 19:09
@mikron123 If you try with the example app in the image picker plugin with the same photo, at 0.6.1, do you see the correct rotation of the image? I still can't reproduce the issue with the example app, whether capturing the image in the app, or pick an image from the gallery.

**Comment by mikron123** [comment] 2019-08-14 20:45
Ok, now I notice I do use "flutter_image_compress" package which has a compressAndGetFile with an "autoCorrectAngle" which is set to true by default, but does a default parameter of keepExif to false... which might be the problem. Sorry for the trouble, I'm guessing this it.

**Comment by cyanglaz** [comment] 2019-08-14 21:24
@mikron123 No worries. Please share your final finding if you don't mind :)

**Comment by mikron123** [comment] 2019-08-14 21:41
Ok @cyanglaz , it looks like the image is screwed up straight away.. I display it straight away using 
var image = await ImagePicker.pickImage(source: ImageSource.gallery,maxHeight: 720,maxWidth: 720);
img = image;

changing then the screen mode to loading, in which I display img using Image.file(img);

THE BUG ONLY HAPPENS WHEN I USE THE maxHeight,maxWidth parameteres... omitting them displayed the pic properly :D

**Comment by worawutt** [comment] 2019-08-15 05:26
I have a similar issue.
The issue occurs only portrait photo, not issue on landscape photo.
Image source both camera and gallery are the same result.

[iPhone take a portrait photo]
test result:
- iPhone display rotate 90˚.
- upload to server, in browser display portrait (OK).
- Android (LG G2) download from server, display rotate 90˚ same as iPhone.

[Android take a portrait photo]
test result:
- LG display as portrait correctly.
- upload to server, in browser display rotate 90˚ clockwise.
- iPhone SE download from server, display as portrait correctly.

I used image_picker latest version ^0.6.1
flutter v1.7.8+hotfix.4

<img width="1099" alt="Screen Shot 2562-08-15 at 12 12 51" src="https://user-images.githubusercontent.com/15317912/63074174-33e13280-bf56-11e9-949a-5d05fe221077.png">

**Comment by worawutt** [comment] 2019-08-15 15:08
> Ok @cyanglaz , it looks like the image is screwed up straight away.. I display it straight away using
> var image = await ImagePicker.pickImage(source: ImageSource.gallery,maxHeight: 720,maxWidth: 720);
> img = image;
> 
> changing then the screen mode to loading, in which I display img using Image.file(img);
> 
> THE BUG ONLY HAPPENS WHEN I USE THE maxHeight,maxWidth parameteres... omitting them displayed the pic properly :D

I just saw your comment, after remove maxWidth and maxHeight parameters, the pic displayed properly on iPhone device. But after uploaded the pic to server and open in browser, the pic rotate 90˚ clockwise.

**Comment by mikron123** [comment] 2019-08-15 16:30
> > Ok @cyanglaz , it looks like the image is screwed up straight away.. I display it straight away using
> > var image = await ImagePicker.pickImage(source: ImageSource.gallery,maxHeight: 720,maxWidth: 720);
> > img = image;
> > changing then the screen mode to loading, in which I display img using Image.file(img);
> > THE BUG ONLY HAPPENS WHEN I USE THE maxHeight,maxWidth parameteres... omitting them displayed the pic properly :D
> 
> I just saw your comment, after remove maxWidth and maxHeight parameters, the pic displayed properly on iPhone device. But after uploaded the pic to server and open in browser, the pic rotate 90˚ clockwise.

Why do you care about the browser? Check how it's been displayed after reloaded from the server into an Image widget in the iOS app.

**Comment by htsnet** [comment] 2019-08-15 17:41
Thanks for all the suggestions. I used the version 0.6.0+5 and everything is OK on iOS (camera and gallery).

**Comment by cyanglaz** [comment] 2019-08-15 17:47
All, Thanks to @mikron123 's help, I can finally reproduce the issue and found the root cause. When the image is scaled using `scaledImage`, it lost the orientation data. I am current working on a fix, should provide a patch soon.

**Comment by cyanglaz** [comment] 2019-08-16 02:45
Should be fixed in  0.6.1+3. I'm closing this PR. If any related issue is found, please feel free to open another issue with details.

**Closed by cyanglaz** 2019-08-16 02:45 UTC
Labels: p: image_picker, plugin, severe: regression, waiting for PR to land (fixed)

**Comment by cvolzke4** [comment] 2019-10-25 02:39
I believe this caused a regression where images are squished when taking a picture in Portrait mode:
https://github.com/flutter/flutter/issues/39311

**Comment by adnankhan74444** [comment] 2021-05-27 07:29
i figure out the problem is that when ever i give maxWidth and  maxHeight in getImage ios image start rotating.
  var image = await picker.getImage(
      source: imageSource,
      maxWidth: 500.0,
      maxHeight: 500.0,
    );
