### ISSUE TITLE
Flutter application can't run on windows

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#36054] opened 2019-07-12 08:58 UTC
Every time I try to run a flutter application (even  hello world) on Windows, I get the following error:
```
[  +91 ms] Launching lib\main.dart on Windows in debug mode...
[ +153 ms] Building Windows application...
[ +126 ms] **********************************************************************
[        ] ** Visual Studio 2019 Developer Command Prompt v16.1.3
[   +1 ms] ** Copyright (c) 2019 Microsoft Corporation
[   +1 ms] **********************************************************************
[ +915 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[  +47 ms] Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[        ] MSBUILD : error MSB1009: Project file does not exist.
[        ] Switch: Runner.sln
[   +5 ms] Building Windows application... (completed in 1.1s)
[   +2 ms] "flutter run" took 8,549ms.
[        ] "flutter run" took 8,549ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:83:5)
<asynchronous suspension>
#2      WindowsDevice.startApp (package:flutter_tools/src/windows/windows_device.dart:85:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:247:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:476:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:477:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:112:14)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1500:12)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:57:24)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:51:10)
#42     main (package:flutter_tools/executable.dart:63:9)
<asynchronous suspension>
#43     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Flutter doctor output:

```
[√] Flutter (Channel master, v1.8.2-pre.56, on Microsoft Windows [Version 10.0.17134.829], locale en-US)
    • Flutter version 1.8.2-pre.56 at C:\flutter
    • Framework revision 90326b6184 (5 hours ago), 2019-07-12 09:46:48 +0530
    • Engine revision d1dcd18486
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.1.29102.190

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
```
![vs-installed](https://user-images.githubusercontent.com/5729291/61115920-d60f8580-a493-11e9-921d-42e89fb5e28b.png)

**Comment by akarika** [comment] 2019-07-12 11:15
same bug on IOS since v1.7.8+hotfix.3 when I use Android simulator

**Comment by stuartmorgan** [comment] 2019-07-12 13:17
> MSBUILD : error MSB1009: Project file does not exist.

The project you are trying to run hasn't been correctly set up to run on Windows. Where did you get the `windows` directory that you are using to add Windows support to the project?

**Comment by MohiuddinM** [comment] 2019-07-12 13:23
the windows directory get generated automatically, when I run the `flutter run` command

**Comment by MohiuddinM** [comment] 2019-07-12 13:25
windows directory contains only one file named `Generated.props`

**Comment by stuartmorgan** [comment] 2019-07-12 13:39
A project as created by `flutter create` doesn't support running on Windows, you currently need to set it up manually. See [flutter.dev/desktop](http://flutter.dev/desktop), especially https://github.com/flutter/flutter/wiki/Desktop-shells#using-the-shells

Closing as a duplicate of #35271

**Comment by escamoteur** [comment] 2019-12-18 19:58
@stuartmorgan I just ran into the same issue with latest master. Do we still have to setup the project manually?

**Comment by jonahwilliams** [comment] 2019-12-18 20:26
>  I just ran into the same issue with latest master. Do we still have to setup the project manually?

Yes

**Comment by stuartmorgan** [comment] 2019-12-18 22:23
https://github.com/flutter/flutter/wiki/Desktop-shells#create is the current link.

**Closed** 2019-12-18 22:22 UTC
Labels: severe: crash, ❖ platform-windows
