### ISSUE TITLE
[in_app_purchase] ios received many unfinished purchases (pendingCompletePurchase = true)

### ISSUE THREAD

**Issue by Sotatek-PhiPham** [flutter/flutter#115241] opened 2022-11-13 15:36 UTC
I'm using in_app_purchare 3.0.8. 
My app has a subscription feature. After login success, the user goes to the screen to select a subscription plan.
Step:
1. I use account A to log into the app and buy a subscription with Sandbox account X.
2. Wait for a few minutes for the subscription to automatically renew then logout, close, and re-open the app
3. Log in to other app account and start listening **purchaseStream.listen** but haven't called the function **buyNonConsumable** to buy anything yet
After sep 3, i received many event about subscription plan I purchased in the previous step

```
flutter: ==================7

==================date: Sunday, November 13, 2022 11:11:54 AM GMT+07:00<=>purchaseID:1<=>pendingCompletePurchase:true<=>status: PurchaseStatus.purchased<=>productId: weekly<=>source: app_store

==================date: Sunday, November 13, 2022 11:14:54 AM GMT+07:00<=>purchaseID:2<=>pendingCompletePurchase:true<=>status: PurchaseStatus.purchased<=>productId: weekly<=>source: app_store

==================date: Sunday, November 13, 2022 11:17:54 AM GMT+07:00<=>purchaseID:3<=>pendingCompletePurchase:true<=>status: PurchaseStatus.purchased<=>productId: weekly<=>source: app_store

==================date: 1668313293000<=>purchaseID:4<=>pendingCompletePurchase:true<=>status: PurchaseStatus.purchased<=>productId: weekly<=>source: app_store

==================date: 1668313576000<=>purchaseID:5<=>pendingCompletePurchase:true<=>status: PurchaseStatus.purchased<=>productId: weekly<=>source: app_store

==================date: 1668313819000<=>purchaseID:6<=>true<=>pendingCompletePurchase:status: PurchaseStatus.purchased<=>productId: weekly<=>source: app_store

==================date: 1668313999000<=>purchaseID:7<=>pendingCompletePurchase:true<=>status: PurchaseStatus.purchased<=>productId: weekly<=>source: app_store
```

my question is Why am I getting those events when I just closed and re-opened the app again and haven't purchased anything?

a piece of code:

```dart
void _init() async {
    final purchaseUpdated = iapConnection.purchaseStream;
    _subscription = purchaseUpdated.listen(
      (event) {
        _onPurchaseUpdate(event);
      },
      onDone: _updateStreamOnDone,
      onError: _updateStreamOnError,
    );
  }

  void _onPurchaseUpdate(List<PurchaseDetails> purchaseDetailsList) {
    print("==================${purchaseDetailsList.length}");
    purchaseDetailsList.forEach(_handlePurchase);
  }

  void _handlePurchase(PurchaseDetails purchaseDetails) async {
    print("==================date: ${purchaseDetails.transactionDate}<=>purchaseID:${purchaseDetails.purchaseID}<=>${purchaseDetails.pendingCompletePurchase}<=>status: ${purchaseDetails.status}<=>productId: ${purchaseDetails.productID}<=>source: ${purchaseDetails.verificationData.source}");
    switch (purchaseDetails.status) {
      case PurchaseStatus.pending:
      // You can update UI to let your users know the purchase is pending.
        onPurchasePending?.call(purchaseDetails);
        break;
```

**Comment by danagbemava-nc** [comment] 2022-11-14 13:42
Hi @Sotatek-PhiPham, do you call `restorePurchases` at any point before purchasing after the user has logged in? 

Do you call `completePurchase` after the purchase has been made? 

Please provide the version of `in_app_purchase_storekit` your project is using(you can find this in your pubspec.lock). 
Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by Sotatek-PhiPham** [comment] 2022-11-15 01:50
Thanks for replying, i'm using `in_app_purchase_storekit` version **0.3.3**, don't call **restorePurchases** any time and also call `completePurchase` like tutorial from codelab.
flutter doctor -v
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.2 on channel stable at /Users/phamngocphi/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (9 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/phamngocphi/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone (4) (mobile) • ee68752fac871aec2f50fe5f0eb78472cbf3d861 • ios            • iOS 15.5 19F77
    • macOS (desktop)     • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)        • chrome                                   • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by danagbemava-nc** [comment] 2022-11-15 06:28
Hi @Sotatek-PhiPham, 

Please provide the [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that you use so that we can investigate this issue.

Thank you

**Comment by Sotatek-PhiPham** [comment] 2022-11-28 10:19
@danagbemava-nc Sorry for the late reply.
I tried with the code in your example [here](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase/example/lib)
Steps to reproduce:
1: buy a subscription
2: quit the app and waiting for 10 minutes or more to subscription auto-renew
3: open the app
Here is the log when I open app
```
================purchaseDetailsList.length = 3
==========================================
2022-11-28 17:03:12.060270+0700 Runner[59381:3369782] flutter: transactionDate: 1669629221000
2022-11-28 17:03:12.060349+0700 Runner[59381:3369782] flutter: status: PurchaseStatus.purchased
2022-11-28 17:03:12.060419+0700 Runner[59381:3369782] flutter: productID: A_weekly
2022-11-28 17:03:12.060511+0700 Runner[59381:3369782] flutter: pendingCompletePurchase: true
2022-11-28 17:03:12.060552+0700 Runner[59381:3369782] flutter: ==========================================
2022-11-28 17:03:12.061962+0700 Runner[59381:3369782] flutter: ==========================================
2022-11-28 17:03:12.062057+0700 Runner[59381:3369782] flutter: transactionDate: 1669629401000
2022-11-28 17:03:12.062089+0700 Runner[59381:3369782] flutter: status: PurchaseStatus.purchased
2022-11-28 17:03:12.062120+0700 Runner[59381:3369782] flutter: productID:A_weekly
2022-11-28 17:03:12.062160+0700 Runner[59381:3369782] flutter: pendingCompletePurchase: true
2022-11-28 17:03:12.062189+0700 Runner[59381:3369782] flutter: ==========================================
2022-11-28 17:03:12.062391+0700 Runner[59381:3369782] flutter: ==========================================
2022-11-28 17:03:12.062534+0700 Runner[59381:3369782] flutter: transactionDate: 1669629775000
2022-11-28 17:03:12.062669+0700 Runner[59381:3369782] flutter: status: PurchaseStatus.purchased
2022-11-28 17:03:12.062813+0700 Runner[59381:3369782] flutter: productID: A_weekly
2022-11-28 17:03:12.062943+0700 Runner[59381:3369782] flutter: pendingCompletePurchase:true
```
ios device: iphone X
xcode Version 14.1

**Comment by danagbemava-nc** [comment] 2022-11-29 06:13
Hi @Sotatek-PhiPham, I think this might be a duplicate of https://github.com/flutter/flutter/issues/98484. Can you take a look at the issue linked and confirm whether or not it matches the scenario you're describing? 

Thank you

**Comment by Sotatek-PhiPham** [comment] 2022-12-09 03:54
@danagbemava-nc I don't think it is a duplicate of [98484](https://github.com/flutter/flutter/issues/98484).
In my case, when the app starts, I receive many events in purchaseStream
here is a video when I run ios app with your code from [example](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase/example/lib)
Besides, after clicking restore, I can't buy any subscription, it returns storekit_duplicate_product_object error 

https://user-images.githubusercontent.com/91038708/206620079-63ba512f-3686-4ab3-8091-afc1d5c05015.mov

**Comment by danagbemava-nc** [comment] 2022-12-09 07:25
Hi @Sotatek-PhiPham, are you testing on `iOS 15` or `iOS 16`? I'm unable to reproduce the issue atm (I'm testing on iOS 16) and I do not see similar messages when I open the app.

**Comment by Sotatek-PhiPham** [comment] 2022-12-09 07:40
@danagbemava-nc I'm testing on both Ios 14.4 and 16. After many time testing,  I realized that it doesn't always happen, maybe there is some special condition for this to happen. For more detail to help you reproduce, here are my steps:

1. buy 1 subscription
2. waiting for more than 5 minutes (because in the sandbox, the subscription will be renewed every 5 minutes)
3. quit the app and open it again
4. if the bug still doesn't occur, you can click buy and cancel on the opened dialog or click restore ten quit app and open it again

**Comment by danagbemava-nc** [comment] 2022-12-09 13:44
Hi @Sotatek-PhiPham, after some more testing I do believe that this is in fact a duplicate of https://github.com/flutter/flutter/issues/98484. 
From what I'm seeing the 2 issues point out that although completePurchase has been called, pendingCompletePurchase still returns `true`, and looking at the statuses of the products in the logs, the products do show that they have either been purchased or restored but pendingCompletePurchase is true. 

In light of this, I'll be closing this as a duplicate of https://github.com/flutter/flutter/issues/98484. 

> Besides, after clicking restore, I can't buy any subscription, it returns storekit_duplicate_product_object error, must be quit the app and open it again to buy

This is likely related to https://github.com/flutter/flutter/issues/85529. 

Kindly follow up in the issues linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2022-12-09 13:44 UTC
Labels: in triage
