### ISSUE TITLE
Conflict between webview and pusher beam in app Flutter

### ISSUE THREAD

**Issue by chuvanhoang888** [flutter/flutter#117044] opened 2022-12-14 08:29 UTC
When I use webview the app immediately cannot receive notifications from pusher beam but the app can still receive notifications in background

Please see the image below. How to fix this. Thank you 

![image](https://user-images.githubusercontent.com/104492264/207544567-f0a3dae8-555e-48b6-a1f9-5ae73f491924.png)
![image](https://user-images.githubusercontent.com/104492264/207544613-24568ad1-9220-417a-b984-dbe903fd9057.png)
![image](https://user-images.githubusercontent.com/104492264/207544660-a773a427-6d9a-4fc0-bf41-8c42422a6865.png)

**Comment by huycozy** [comment] 2022-12-14 11:11
Hi @chuvanhoang888 
The goal of this GitHub repo is not to give assistance on personal code or the whole package/plugin project,
but to improve Flutter framework reporting bugs or feature requests.

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. And I also see that you already filed an issue there as @iapicca mentioned above. So please follow up on it for further updates. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2022-12-14 11:11 UTC
Labels: in triage
