### ISSUE TITLE
Exception: The plugin firebase_core could not be built due to the issue above.

### ISSUE THREAD

**Issue by Naveenarroju** [flutter/flutter#56835] opened 2020-05-10 14:30 UTC
I have upgrade my flutter sdk and when I run the app I see the below error.

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve androidx.lifecycle:lifecycle-common:2.2.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5
      > Could not resolve androidx.lifecycle:lifecycle-common:2.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common/2.2.0/lifecycle-common-2.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common/2.2.0/lifecycle-common-2.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve androidx.lifecycle:lifecycle-common:2.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common/2.2.0/lifecycle-common-2.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common/2.2.0/lifecycle-common-2.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve androidx.lifecycle:lifecycle-common-java8:2.2.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5
      > Could not resolve androidx.lifecycle:lifecycle-common-java8:2.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common-java8/2.2.0/lifecycle-common-java8-2.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common-java8/2.2.0/lifecycle-common-java8-2.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve androidx.lifecycle:lifecycle-common-java8:2.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common-java8/2.2.0/lifecycle-common-java8-2.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common-java8/2.2.0/lifecycle-common-java8-2.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve androidx.lifecycle:lifecycle-runtime:2.2.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5
      > Could not resolve androidx.lifecycle:lifecycle-runtime:2.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.2.0/lifecycle-runtime-2.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.2.0/lifecycle-runtime-2.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve androidx.lifecycle:lifecycle-runtime:2.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.2.0/lifecycle-runtime-2.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.2.0/lifecycle-runtime-2.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve androidx.fragment:fragment:1.1.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5
      > Could not resolve androidx.fragment:fragment:1.1.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve androidx.fragment:fragment:1.1.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve com.google.firebase:firebase-core:16.0.4.
     Required by:
         project :app > project :firebase_core
      > Could not resolve com.google.firebase:firebase-core:16.0.4.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/16.0.4/firebase-core-16.0.4.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/16.0.4/firebase-core-16.0.4.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.google.firebase:firebase-core:16.0.4.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/16.0.4/firebase-core-16.0.4.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/16.0.4/firebase-core-16.0.4.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin firebase_core...
Running Gradle task 'assembleAarRelease'...
         *********************************************************
WARNING: This version of firebase_core will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'firebase_core'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Exception: The plugin firebase_core could not be built due to the issue above.

```

**Comment by iapicca** [comment] 2020-05-11 11:39
Hi @Naveenarroju 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-05-11 11:39 UTC
