### ISSUE TITLE
[shared_preferences] Failed to resolve native function 'Window_sendPlatformMessage' in 'Window._sendPlatformMessage@112065589'

### ISSUE THREAD

**Issue by The-Redhat** [flutter/flutter#30333] opened 2019-04-01 20:21 UTC
## Steps to Reproduce

1. execute method with `compute`
2. call `await SharedPreferences.getInstance()`

## Logs

```
../../third_party/dart/runtime/vm/native_entry.cc: 222: error: Failed to resolve native function 'Window_sendPlatformMessage' in 'Window._sendPlatformMessage@112065589'
```

```
Analyzing schoolsen-mobile...                                           
No issues found! (ran in 12.2s)
```

```
[✓] Flutter (Channel beta, v1.3.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.3.8 at /home/gregor/development/flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/gregor/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/73/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • ONEPLUS A3003             • fe20f4e6      • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

There should be a better error message.

**Comment by dnfield** [comment] 2019-04-01 22:59
Duplicate of https://github.com/flutter/flutter/issues/13937

**Closed by dnfield** 2019-04-01 22:59 UTC
