### ISSUE TITLE
Missing xcode dependency: Python module "six"

### ISSUE THREAD

**Issue by u84six** [flutter/flutter#16428] opened 2018-04-10 18:48 UTC
## Steps to Reproduce

On macOS High Sierra

- Install Flutter
- Run Flutter Doctor

Everything is checked except for "Missing Xcode dependency: Python module "six". Install via 'pip install six' or 'sudo easy_install six'."

I have both the built-in macOS dependent Python2.7 as well as Python3.6 (latest). I ran both pip and pip3 commands to install six. Then ran Flutter Doctor again. Still the same error. Then tried 'sudo easy_install six'. Still the same error in Flutter Doctor.

Edit: got this error when trying to install six:

Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (1.4.1)
matplotlib 1.3.1 requires nose, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.
matplotlib 1.3.1 has requirement numpy>=1.5, but you'll have numpy 1.8.0rc1 which is incompatible.

Tried to install the 3 module mentioned above:
sudo pip install nose
Collecting nose
  Downloading nose-1.3.7-py2-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 3.7MB/s
matplotlib 1.3.1 requires tornado, which is not installed.
matplotlib 1.3.1 has requirement numpy>=1.5, but you'll have numpy 1.8.0rc1 which is incompatible.
Installing collected packages: nose
Consider using the `--user` option or check the permissions

I believe that I can't install anything for the macOS default version of Python because it will break lower level dependencies within the OS.

I then uninstalled Python3.6 (which was  a pain to find all the directories associated with it), as well as all the symlinks. Reinstalled Python3.6, ran Flutter Doctor. Still the same error. Restarted, etc, still the same error.

Also, if I try to make Python3.6 the default python on the mac, it will likely break OS level services that depend on python2.7.

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

I'm not even at the stage of building a flutter app yet. Just trying to install and setup.

## Flutter Doctor
Paste the output of running `flutter doctor -v` here.
flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.8 at /Users/myname/Development/flutter/flutter
    • Framework revision b397406561 (8 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/myname/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone 7 • E8EF95FA-8E51-44F3-BF6D-AA12032481F3 • ios • iOS 11.2 (simulator)

**Comment by bdevos** [comment] 2018-04-11 09:41
+1

**Comment by uinz** [comment] 2018-04-11 14:47
> brew reinstall python@2
> pip install six

**Comment by u84six** [comment] 2018-04-11 21:40
@uinz's answer worked. Thank you!

**Comment by BrelanAllin** [comment] 2018-04-12 15:06
Have been wracking my brain trying to get it to work and uinz comes in with the save!

**Comment by bssPhongNguyen** [comment] 2018-04-13 10:54
thank God and thank @uinz, it works now!

**Comment by karanatwal** [comment] 2018-04-13 12:10
Thanks alot @uinz . You save my precious time. 🥇

**Comment by ashtonthomas** [comment] 2018-04-14 13:49
🔥 

thank you 🙏

**Comment by humblerookie** [comment] 2018-04-23 01:50
Still does not work for me.

```brew reinstall python@2
==> Reinstalling python@2 
==> Downloading https://homebrew.bintray.com/bottles/python@2-2.7.14_3.high_sierra.bottle.1.tar.gz
Already downloaded: /Users/anvithbhat/Library/Caches/Homebrew/python@2-2.7.14_3.high_sierra.bottle.1.tar.gz
==> Pouring python@2-2.7.14_3.high_sierra.bottle.1.tar.gz
==> /usr/local/Cellar/python@2/2.7.14_3/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/
==> /usr/local/Cellar/python@2/2.7.14_3/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/
==> /usr/local/Cellar/python@2/2.7.14_3/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@2/2.7.14_3: 4,602 files, 81.8MB
Anviths-MacBook-Pro:bin anvithbhat$ pip install six
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.11.0)
Anviths-MacBook-Pro:bin anvithbhat$ ./flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D47, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2017.2.1)
[!] VS Code (version 1.22.2)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by humblerookie** [comment] 2018-04-23 02:07
@uinz Could you update your answer with this

>  python2.x -m pip install six
for people using parallel python installations (- Me being one). Took a lot of time to figure this out :/

**Comment by uinz** [comment] 2018-04-23 16:07
@humblerookie

I updated my answer but I am not sure about it.

**Comment by humblerookie** [comment] 2018-04-24 07:45
@uinz What makes you skeptic, The root cause for me is the fact that Mac Os Sierra uses python 2.x and when you do manage to install a parallel python 3 things go south since the pip installer defaults to 3.x installation directory instead of 2.x and flutter doc doesn't detect it.

**Comment by jjyy1008** [comment] 2018-04-24 10:53
@uinz 's answer worked. Thanks.

**Comment by uinz** [comment] 2018-04-25 02:12
@humblerookie 

I'm not familiar with `python`

But I install `python3` by `brew install python@3`

`brew` told me that I can use `pip3` to install package.

**Comment by ronaldxian** [comment] 2018-04-26 15:50
@uinz thank you

**Comment by brunosansigolo** [comment] 2018-04-27 03:29
@uinz thank you!

**Comment by mikebriseno** [comment] 2018-04-28 03:01
@uinz that worked like a charm, thanks!

brew reinstall python@2
pip install six

**Comment by chrislambe** [comment] 2018-04-29 22:25
In addition to `python2.x -m pip install six` I also had to run `python2.x -m ensurepip --default-pip` to ensure that my Python 2.x install had pip available.

**Comment by humblerookie** [comment] 2018-05-02 06:32
@Kenny1610 Whats the output for your 'six' installation?

**Comment by Belliott404** [comment] 2018-05-02 14:49
@uinz thank you!!!

**Comment by Kenny1610** [comment] 2018-05-02 15:30
@humblerookie my output for that is: Requirement already satisfied: six in /Users/The_Chosen_King/anaconda3/lib/python3.6/site-packages (1.11.0)

**Comment by humblerookie** [comment] 2018-05-02 16:43
@Kenny1610  clearly the case is that six is installed in python 3.6 and your system python is 2.x so six is being looked up in 2.x repo and is not found. 

what's the output for 

> ls /usr/local/Frameworks/Python.framework/Versions

if its 2.7 then try 

> python2.7 -m pip install six

else insert the appropriate 2.x version number

**Comment by Kenny1610** [comment] 2018-05-02 16:49
@humblerookie 2.7 is the current version, so I ran the 'python2.7 -m pip install six' command and got:
Collecting six
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.11.0

I tried running the program again and still got the exact same error for some reason.

**Comment by humblerookie** [comment] 2018-05-02 16:55
@Kenny1610 try [uninstalling it](https://stackoverflow.com/a/6263564/2185582) and then using "python2.7 -m pip install six". Should work.

**Comment by Kenny1610** [comment] 2018-05-02 17:08
@humblerookie I tried a lot of those commands in the link you provided and it's not uninstalling like it should. I believe I might not be entering the the correct value for 'packages'. I'm new to this kind of stuff. I apologize.

**Comment by toddtyler** [comment] 2018-05-02 20:07
Thanks @uinz, your comment solved the issue for me.

**Comment by krasavello13** [comment] 2018-05-06 19:48
I had the same issue, @uinz answer works for me!

**Comment by AppleEducate** [comment] 2018-05-07 19:31
@uinz answer worked for me.

**Comment by kangmaman** [comment] 2018-05-08 15:55
If you have already installed Python 3 on MacOS, just copy file six.py to folder /usr/local/lib/python2.7/site-packages.

You can get file six.py from https://github.com/benjaminp/six

**Comment by liangerzhao** [comment] 2018-05-09 07:30
@uinz thank you!!!!!

**Comment by vakenbolt** [comment] 2018-05-11 21:39
Christ! This one of the many reasons I loathe Python and it's ecosystem. Can we at least get accurate messaging in `flutter doctor`? For MacOS users the messages related to missing python dependencies is cloudy at best.

```
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ Missing Xcode dependency: Python module "six".

      MacOS users that have Apple's version Python need to reinstall before using pip to install six.
              e.g. brew reinstall python@2

      Install via 'pip install six' or 'sudo easy_install six'.
```

Clarity is our friend.

**Comment by mit-mit** [comment] 2018-05-14 07:46
cc @cbracken I think this is the issue I showed to you last week. Is there anything you can think off we can do to mitigate this?

**Comment by Sun3** [comment] 2018-05-15 16:53
I have reformatted two different Mac Computes with macOS Sierra but received the same errors:

```
Missing Xcode dependency: Python module "six".
Install via 'pip install six' or 'sudo easy_install six'.
Could not build the application for the simulator.
Error launching application on iPhone X.
```

Was there any progress on this issue?

Thank you

**Comment by cbracken** [comment] 2018-05-15 17:17
@mit-mit this comes down to a bug (mis-feature) in Xcode, which is that it's using the version of python at the front of the path as opposed to the system-default python it expects. Xcode itself relies on the `six` module, so it'll need to be installed in whichever python is at the front of the PATH.

As a temporary workaround, I'd suggest everyone run `which python` and `which pip` and ensure that they're consistent with each other, then `pip install six` to get the `six` module installed in that version.

One thing I'll look into is whether we can stomp on any user-customisations to the PATH just for the duration of any Xcode invocations. That's certainly doable for invocations via the flutter tool itself, but I'm not 100% certain it'll work for Xcode builds that occur from the Xcode UI -- it'll depend on whether the error is occurring during the build of the Obj-C/Swift bits of the app or during our build of the AOT assembly.

**Comment by Sun3** [comment] 2018-05-18 18:03
Running the commands get rid of the pip six error but... when you compile a project for release you receive an error:
```
brew reinstall python@2
pip install six
```

# Error by running -> ```flutter run --release``` to an actual device like an iPhone
```
flutter run --release
Launching lib/main.dart on Marco’s iPhone in release mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: W4DESGH8Y9
Running Xcode clean...                                       1.1s
Starting Xcode build...                                          
 ├─Building Dart code...                             24.3s
 ├─Assembling Flutter resources...                    1.1s
 └─Compiling, linking and signing...                  9.4s
Xcode build done.                                           36.8s
Installing and launching...                                      
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

To repeat this help message, press "h". To quit, press "q".
```

**Comment by jjavierweb** [comment] 2018-05-20 17:53
@uinz worked like really good, thanks a lot

**Comment by TimZ99** [comment] 2018-05-20 21:32
Didn't work for me, unfortunately.
Getting this message every time I run `flutter run`.

**Comment by opyate** [comment] 2018-06-05 09:40
A note for anyone getting `No module named pip` and who can't install `pip` using the usual methods because [environment](https://www.xkcd.com/1987/).

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python2.7 get-pip.py
```

Then @uinz 's answer will work:

```
python2.7 -m pip install six
```

**Comment by Sun3** [comment] 2018-06-05 15:38
The curl works good, but when you run the ```python2.7 get-pip.py``` you get errors 

```matplotlib 1.3.1 requires nose, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.```

@uinz solution then gives same error as above.

**Comment by emaalouf** [comment] 2018-06-08 17:13
@uinz answer helped so much, Thanks

**Comment by zeasin** [comment] 2018-06-11 02:05
🔥

thank you @uinz  🙏

**Comment by toventang** [comment] 2018-06-24 05:06
@opyate well done!  thanks s

**Comment by MurphLu** [comment] 2018-06-26 09:09
@uinz thank you

**Comment by CodingWasaby** [comment] 2018-07-08 12:51
@uinz u r my hero

**Comment by cbracken** [comment] 2018-07-12 00:35
Fixed in #19281 on `master`. It should no longer be necessary to manually install the `six` module if you have a custom Python install on your path.

**Closed by cbracken** 2018-07-12 00:35 UTC
Labels: ⌺‬ platform-ios

**Comment by bestswifter** [comment] 2018-08-12 06:43
See: https://github.com/Homebrew/homebrew-core/issues/29176

**Comment by kenanduman1988** [comment] 2018-10-09 13:37
> try `python2.x -m pip install six` by [@humblerookie's suggest](https://github.com/flutter/flutter/issues/16428#issuecomment-383434503)
> 
> or
> 
> `brew reinstall python@2`
> `pip install six`

Thanks man!
