### ISSUE TITLE
 UIKitView will always be on top of any other widget.

### ISSUE THREAD

**Issue by sinano1107** [flutter/flutter#61073] opened 2020-07-08 06:48 UTC
Hello, Flutter Team.

I'm using a package called flutter_unity_view_widget, which launches Unity inside Flutter.

I want to layer buttons and dialogs on top of this widget, but I couldn't do that.

I'm hoping that this will solve this problem as this widget uses a UIKitView internally.

I don't have time for this as I have a contest coming up in two months.

I would like to ask for your help.

**Comment by TahaTesser** [comment] 2020-07-08 07:43
Hi @sinano1107 
Are you experiencing this [issue](https://github.com/flutter/flutter/issues/59751)?
If not, 
Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample including flutter code and native code
Thank you

**Comment by sinano1107** [comment] 2020-07-08 07:54
Yes, probably the same.
And I tried the solution you provided in that issue, but it didn't work.

Create a code sample.
Please wait a moment.

**Comment by sinano1107** [comment] 2020-07-08 08:09
```
import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  AnimationController _controller;

  @override
  void initState() {
    _controller = AnimationController(vsync: this);
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Stack(
          children: <Widget>[
            Center(
              child: Container(
                height: 200,
                width: 200,
                child: UnityWidget(
                  onUnityViewCreated: (controller) => print('get controller'),
                ),
              ),
            ),

            Positioned(
              top: 250,
              left: 50,
              child: Container(
                height: 100,
                width: 100,
                color: Colors.red,
              ),
            ),

          ],
        ),
      ),
    );
  }
}
```

**Comment by sinano1107** [comment] 2020-07-08 08:21
This is the result of the above code.
The UnityWidget(UIKitView) is now on top.

Also, the UIKitView will be displayed above the Dialog.

![IMG_0551](https://user-images.githubusercontent.com/45984123/86894318-dc375100-c13d-11ea-9379-260d621aae84.png)

![IMG_0552](https://user-images.githubusercontent.com/45984123/86895443-6d5af780-c13f-11ea-8829-925cb8d7ce10.png)

**Comment by TahaTesser** [comment] 2020-07-08 10:28
Hi @sinano1107 
Thanks for confirming, i have edited the title of the known to better to fit the described issue 
Closing as duplicate of https://github.com/flutter/flutter/issues/59751

**Closed by TahaTesser** 2020-07-08 10:28 UTC
Labels: in triage
