### ISSUE TITLE
Flutter List widgets won't scroll on iOS 13 modalPresentationStyle = .automatic

### ISSUE THREAD

**Issue by mixdesign** [flutter/flutter#48630] opened 2020-01-11 13:40 UTC
## Steps to Reproduce

1. Create a simple Flutter app (module) with a single page including `ListView` or `SingleChildScrollView`. Append as many children as possible to make it scrollable.
2. Create a simple iOS native app, which has two controllers. **Controller A** has a button which initializes **controller B**. **Controller B** initializes and adds `FlutterViewController` into itself.
3. Run the app on the simulator using Xcode 11, iOS 13
4. Press on a button in the **controller A**, instantiate and present **controller B** (which includes the flutter project content).
5. Because we run on iOS 13, the presented modal controller style would be `.automatic`.
6. We will get a list we built with Flutter `ListView` or `SingleChildScrollView`.
7. Try to scroll the list, it won't at first try. Even it scrolls very hard if you try to swipe your fingers up and down many-many times. I tried setting `controller.isModalInPresentation = true`

**Target Platform: Xcode 11.3**
**Target OS version/browser: iOS 13**
**Devices: Simulator iOS 13, Any device type, Real device**

## Logs

```ruby
> flutter analyze
// flutter analyze no issues!
```

```ruby
> flutter doctor -v
[✓] Flutter (Channel unknown, v1.13.6, on Mac OS X 10.15.2 19C46a, locale en-KZ)
    • Flutter version 1.13.6 at /Users/almasadilbek/development/flutter
    • Framework revision 659dc8129d (12 days ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/almasadilbek/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Users/almasadilbek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/almasadilbek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Almas’s iPhone Xs Max • 00008020-001C05260101002E • ios • iOS 13.3

• No issues found!
```

![flutter-list-on-modal](https://user-images.githubusercontent.com/198882/72232502-bc3e2f00-35eb-11ea-96f9-d34c1a5df548.gif)

**Comment by rmrg-tec** [comment] 2020-01-13 17:11
same here

**Comment by xster** [comment] 2020-02-13 05:47
This one seems like a pretty big annoyance. @gaaclarke would you like to take a swing at it?

**Comment by gaaclarke** [comment] 2020-02-13 18:04
@mixdesign or @rmrg-tec, can you add reproduction code please?

**Comment by mixdesign** [comment] 2020-02-18 04:34
@gaaclarke Hey, thanks

Pushed the reproduction Xcode project:
https://github.com/mixdesign/flutter-issue48630-demo

**Comment by MichealReed** [comment] 2020-02-24 21:14
Is there a suggested way to toggle modalInPresentation? There is a similar issue with the default flutter platform view example on iOS. Can open a separate issue if @gaaclarke recommends.

![image](https://user-images.githubusercontent.com/12153323/75191636-524f9400-5718-11ea-97bc-b2700aac14f6.png)

**Comment by gaaclarke** [comment] 2020-02-24 23:54
The problem can be demonstrated more simply with the following change (just to show it isn't the extra view controller that is creating the problem):
```diff
--- a/module_project/Demo/Demo/ViewController.swift
+++ b/module_project/Demo/Demo/ViewController.swift
@@ -8,6 +8,7 @@
 
 import UIKit
 import Issue48630Framework
+import Flutter
 
 class ViewController: UIViewController {
 
@@ -17,7 +18,9 @@ class ViewController: UIViewController {
     }
 
     @IBAction func launchFlutter(_ sender: Any) {
-        let controller = FlutterScreenViewController()
+        let engine = FlutterEngine.init(name: "io.flutter.issue48630", project: nil)
+        engine.run(withEntrypoint: "mainMethod")
+        let controller = FlutterViewController.init(engine: engine, nibName: nil, bundle: nil)
         controller.isModalInPresentation = true
         self.present(controller, animated: true, completion: nil)
     }
```

**Comment by gaaclarke** [comment] 2020-02-25 01:27
This is expected behavior for iOS.  I've created an empty xcode project that demonstrates the behavior here: ( https://github.com/gaaclarke/touchesmovedmodal ).  Just launch that app and watch the logs as you drag your finger on the presented view controller.  You might want to file a bug with apple if you don't think that's how it should work.

The behavior manifests itself in Flutter here: https://github.com/flutter/engine/blob/d2e2cc9d4551a93f550bf06fd2c453c864a614c6/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L690.   We will get a touchesBegan, a few touchesMoved, then touchesCancelled in FlutterViewController.

Closing the issue since it's not a bug in Flutter and we are behaving the way any app would.

**Closed by gaaclarke** 2020-02-25 01:27 UTC
Labels: a: existing-apps, engine, f: scrolling, framework, ⌺‬ platform-ios

**Comment by gaaclarke** [comment] 2020-02-25 01:30
@MichealReed Yea, file a different bug.  This one is specifically talking about the add-to-app case.

**Comment by kmorey** [comment] 2020-02-25 15:22
@gaaclarke while true this is the default behavior if you don't have a scrolling widget, I don't believe it is the same behavior if scrolling can happen. I have added a webview to a fork your repo for testing ( https://github.com/kmorey/touchesmovedmodal ). If you launch that app, you will see the modal only dismisses on swipe down if the webview is scrolled to the top. Otherwise the webview will scroll and bounce as normal without dismissing the view controller.

I have found some more information about how you can set up your own UIGestureRecognizer to prevent the dismiss behavior conditionally.

https://stackoverflow.com/a/57635168

(other answers later in the thread might provide more insight, such as the one about implementing a signature panel where the user could draw with gestures but didn't try to dismiss the view controller)

**Comment by gaaclarke** [comment] 2020-02-25 17:12
@kmorey Thanks for the stackoverflow link.  Looks like those proposed changes can be implemented by the user of Flutter.  There is no required change to Flutter.  The question is: "do we want to make those the default behavior for all users of FlutterViewController?"  It could even be more confusing to users if our view controller doesn't behave like other view controllers.  In the case of using the gesture recognizer it could make it even more difficult for someone to customize the behavior.  I don't know if we can come up with a one size fits all solution here for the same reason that the Apple API doesn't.

**Comment by gaaclarke** [comment] 2020-02-25 17:16
@kmorey Thanks for the stackoverflow link.  Looks like those proposed changes can be implemented by the user of Flutter.  There is no required change to Flutter.  The question is: "do we want to make those the default behavior for all users of FlutterViewController?"  It could even be more confusing to users if our view controller doesn't behave like other view controllers.  In the case of using the gesture recognizer it could make it even more difficult for someone to customize the behavior.  I don't know if we can come up with a one size fits all solution here for the same reason that the Apple API doesn't.

**Comment by kmorey** [comment] 2020-02-27 19:41
For any coming here looking for a solution, feel free to build off what I ended up with. This works well enough for my current use case, which all my Flutter views have an ActionBar at top. This code will disable the iOS13 dismiss gesture if the user starts dragging at y > 65 (estimate of ActionBar size, this could be improved by figured it out in code I guess, but good enough for me, for now). If they start dragging on the ActionBar it will allow dismissal.

[CustomFlutterViewController.txt](https://github.com/flutter/flutter/files/4263723/CustomFlutterViewController.txt)

**Comment by mixdesign** [comment] 2020-03-17 06:47
@gaaclarke Thanks, I agree with your point of view.
@kmorey approach works well. There is still different behavior than the one we experience with native Lists like `UITableView` when holding and scrolling down (from any region of the screen) will trigger modal dismissal (in **kmoreys** solution it won't, which gives inconsistent feelings), but that's a nice working solution.

Maybe we should mention the problem and reference the solution in [add-to-app/ios/add-flutter-screen](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen) ?

**Comment by kmorey** [comment] 2020-03-17 11:26
@mixdesign yes that is true on the inconsistent behavior. I did try another approach first, where I used a flutter side gesture detector and method channel to pass information back to native (such as scroll behavior when you are at the top of a list view) to trigger it. It seems the method channel calls were all delayed until dragging on the screen was complete (too late) so I was unsuccessful.
