### ISSUE TITLE
Refresh Indicator UI is frozen if duration is over 10 seconds

### ISSUE THREAD

**Issue by AndrewTran2018** [flutter/flutter#13782] opened 2017-12-28 03:09 UTC
## Steps to Reproduce
- Open the example project flutter_gallery
- Change the timer duration that mimics a latency interval for the indicator to be shown to 10 seconds<like the below:

  **Future<Null> _handleRefresh() {**
    final Completer<Null> completer = new Completer<Null>();
    new Timer(const Duration(**seconds: 10**), () { completer.complete(null); });

- Run the app
- Go to Pull to Refresh example, pull the list to refresh, see the indicator is a blue dot and stops working.

See the screenshot attached
![refreshindicator_broken](https://user-images.githubusercontent.com/31315360/34399140-25f076be-ebb7-11e7-90f7-7ecbf8204a59.png)

**Comment by BenedictP** [comment] 2018-03-07 15:03
To be precise it freezes after 6666 miliseconds. 
https://github.com/flutter/flutter/blob/c01cad34915618b33a43802dba3553c56d4fde29/packages/flutter/lib/src/material/progress_indicator.dart#L359

**Comment by tsun424** [comment] 2018-03-26 01:19
It seems indicator freezes there and the whole process stops. Any workaround solution at this stage?

**Comment by AndrewTran2018** [comment] 2018-03-28 01:22
@tsun424 The patch is exactly where @BenedictP has pointed out.

**Comment by Hixie** [comment] 2018-05-29 23:20
Duplicate of https://github.com/flutter/flutter/issues/17923

**Closed by Hixie** 2018-05-29 23:20 UTC
Labels: f: material design
