### ISSUE TITLE
this is a unknown error 

### ISSUE THREAD

**Issue by tzt1994** [flutter/flutter#46942] opened 2019-12-13 03:27 UTC
Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[LabeledGlobalKey<NavigatorState>#8842f](dirty, state: NavigatorState#245ae(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2247 pos 12: '!_debugLocked': is not true.

**Comment by tzt1994** [comment] 2019-12-13 03:27
I don't know why?

**Comment by jonahwilliams** [comment] 2019-12-13 03:40
Duplicate of https://github.com/flutter/flutter/issues/45822

**Closed by jonahwilliams** 2019-12-13 03:40 UTC
