### ISSUE TITLE
Semantics widget breaks layout

### ISSUE THREAD

**Issue by under3415** [flutter/flutter#121952] opened 2023-03-04 20:38 UTC
## Steps to Reproduce

1. Wrap `Expanded` widget with `Semantics` widget in a `Row`
2. `Expanded` stops working and the underlying widget overflows
3. Removing `Semantics` widget or moving it under `Expanded` fixes the problem

**Expected results:** 
`Expanded` should not be affected by non-layout widget such as `Semantics` or `Focus`

**Actual results:** 
Layout is broken and overflow error is triggered

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: [
          Semantics(
            label: "long text",
            child: const Expanded(
              child: Text(
                'very long very long very long very long very long very long very long text',
                overflow: TextOverflow.ellipsis,
                style: TextStyle(fontSize: 24),
              ),
            ),
          ),
          const Text(
            "12:34",
            style: TextStyle(fontSize: 24),
          ),
        ],
      ),
    );
  }
}

```

</details>

```
[√] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19045.2673], locale en-US)
    • Flutter version 3.7.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (3 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.17)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32630.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.76.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2673]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.63

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-03-06 09:45
This is WAI (working as intended) I think. Please see https://github.com/flutter/flutter/issues/15207#issuecomment-370972365. Also, you may want to take a look at https://github.com/flutter/flutter/issues/92040 in case moving `Semantics`   to be under `Expanded`.

Closing this issue as WAI. If you disagree, please write in the comments and I will reopen it. Thanks!

**Closed by huycozy** 2023-03-06 09:45 UTC
Labels: in triage
