### ISSUE TITLE
web_benchmarks_html dynamic_clip_on_static_picture.html.drawFrameDuration.average, other web benchmark regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54976] opened 2020-04-16 16:30 UTC
Looks like dynamic_clip_on_static_picture.html.sceneBuildDuration and dynamic_clip_on_static_picture.html.totalUiFrame.average did too:

<img width="1353" alt="Screen Shot 2020-04-16 at 9 28 30 AM" src="https://user-images.githubusercontent.com/1435716/79481663-a8c4aa80-7fc4-11ea-9b0c-107081a60159.png">

https://github.com/flutter/flutter/pull/54909 looks like a likely culprit.

**Comment by yjbanov** [comment] 2020-04-17 16:28
The difference seems to be within the noise range, so I'll close as not a regression. I just landed noise reduction for Web benchmarks. Hopefully it will be much easier to tell regressions apart from noise.

**Closed by yjbanov** 2020-04-17 16:28 UTC
Labels: perf: speed, platform-web, severe: performance, severe: regression
