### ISSUE TITLE
Corporate users need a way to populate an internal mirror of FLUTTER_STORAGE_BASE_URL

### ISSUE THREAD

**Issue by oravecz** [flutter/flutter#138171] opened 2023-11-09 19:42 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Think of some large, highly regulated companies in the US as operating in a restricted Internet capacity (even more restrictive than China).

Our developer laptops do not have free access to the Internet, nor are we allowed to poke holes in our firewall for an exception to Google servers.

When Flutter is executed, depending on the command and the OS and chipset, Flutter will go out to a network location (base url specified by `FLUTTER_STORAGE_BASE_URL`) to download any number of support files and binaries specific to that version of Flutter. 

Within a firewall (corporate or China), we have the ability to change the base URL specified by FLUTTER_STORAGE_BASE_URL to a reachable URL for the current network. Any calls made by Flutter (and a number of other tools), will respect the environment variable to locate files.

HOWEVER, without the ability to mirror Google's default base URL for supplementary Flutter content, we haven't the means to supply the necessary files to our internal "mirror" to be downloaded.

The default base url for that environment variable is `https://storage.googleapis.com`, however the folder structure is indeterminate. There is no way for someone outside of Google to recreate the contents of the `flutter_infra_release` folder and its subfolders without a manifest of all files a particular Flutter version requires.

There is a China mirror, because Google copies files to that location. There is no ability for a corporation to do so.

### Actual results

Any downloads of external content attempted by Flutter results in a network timeout or unreachable error.

```shell
flutter -vv --disable-telemetry
Downloading Darwin arm64 Dart SDK from Flutter engine a794cf2681c6c9fe7b260e0e84de96298dc9c18b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    19  100    19    0     0     90      0 --:--:-- --:--:-- --:--:--    94
[/usr/local/jpmc/flutter-3.13.6/bin/cache/dart-sdk-darwin-arm64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /usr/local/jpmc/flutter-3.13.6/bin/cache/dart-sdk-darwin-arm64.zip or
        /usr/local/jpmc/flutter-3.13.6/bin/cache/dart-sdk-darwin-arm64.zip.zip, and cannot find /usr/local/jpmc/flutter-3.13.6/bin/cache/dart-sdk-darwin-arm64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=1_activation.yml
```

How might we be able to create our own mirror of Flutter's on-demand files?

### Logs

N/A

### Flutter Doctor output

Cannot run `flutter doctor`

**Comment by huycozy** [comment] 2023-11-10 10:50
Labeling this as a feature request for other's opinions.

**Comment by christopherfujino** [comment] 2023-11-10 20:20
Thanks for this well explained issue. I believe the solution would be to implement https://github.com/flutter/flutter/issues/82383, which I haven't gotten around to doing. However, if you have the capacity to prepare a PR for this I'd be happy to review it :)

**Comment by christopherfujino** [comment] 2023-11-10 20:20
Closing as a duplicate of https://github.com/flutter/flutter/issues/82383

**Closed by christopherfujino** 2023-11-10 20:20 UTC
Labels: c: new feature, tool, team-tool

**Comment by oravecz** [comment] 2023-11-13 14:55
While these tickets are related, I do not thing they are the same. For example, I am trying to populate an internal file server for Flutter dependencies across all OS and Chip Architectures. The `precache --dry-run` will only return the files needed to be mirrored for the OS and architecture of the local machine.

Here is what I am doing today. Note: don't expect this to be complete - I am frequently finding holes in my manifest which is why I am asking for these files to be specified in release notes or some other deterministic manner. Also, just providing a way to crawl the Google mirror will suffice.

```typescript
import {readFileSync} from "fs";

const INTERNAL = `/bin/internal`;

const fileContents = (path: string) => readFileSync(path).toString().trim();

export class FlutterStructure {

    private readonly FLUTTER_ROOT: string;
    private readonly FLUTTER_TOOLS_DIR: string;
    private INTERNAL: string;
    private SNAPSHOT_PATH: string;
    private STAMP_PATH: string;
    private SCRIPT_PATH: string;
    private readonly DART_SDK_PATH: string;
    private DART: string;

    constructor(flutterRoot: string) {
        this.FLUTTER_ROOT = flutterRoot;
        this.INTERNAL = `${this.FLUTTER_ROOT}/bin/internal`;
        this.FLUTTER_TOOLS_DIR = `${this.FLUTTER_ROOT}/packages/flutter_tools`
        this.SNAPSHOT_PATH = `${this.FLUTTER_ROOT}/bin/cache/flutter_tools.snapshot`
        this.STAMP_PATH = `${this.FLUTTER_ROOT}/bin/cache/flutter_tools.stamp`
        this.SCRIPT_PATH = `${this.FLUTTER_TOOLS_DIR}/bin/flutter_tools.dart`
        this.DART_SDK_PATH = `${this.FLUTTER_ROOT}/bin/cache/dart-sdk`
        this.DART = `${this.DART_SDK_PATH}/bin/dart`
    }

    manifest() {
        return [
            ...this.dartSdk(),
            ...this.updatePackages(),
            ...this.engineArch(),
            ...this.cache(),
            ...this.libimobiledevice(),
            ...this.usbmuxd(),
            ...this.iosUsb(),
            ...this.misc(),
        ]
    }

    dartSdk() {
        const ENGINE_VERSION = fileContents(`${this.INTERNAL}/engine.version`);
        return [
            "dart-sdk-darwin-x64.zip",
            "dart-sdk-darwin-arm64.zip",
            "dart-sdk-linux-arm64.zip",
            "dart-sdk-linux-x64.zip",
            "dart-sdk-windows-x64.zip",
        ].map(DART_ZIP_NAME => `flutter_infra_release/flutter/${ENGINE_VERSION}/${DART_ZIP_NAME}`);
    }

    updatePackages() {
        return [
            `flutter_infra_release/flutter/coverage/lcov.info`,
        ]
    }

    engineArch() {
        const ENGINE_VERSION = fileContents(`${this.INTERNAL}/engine.version`);
        const url = `flutter_infra_release/flutter/${ENGINE_VERSION}`;

        const dl = (filename:string) => [
            'darwin-x64',
            'darwin-arm64',
            'windows-x64',
            'linux-x64',
            'linux-arm64',
        ].map(arch => `${url}/${arch}/${filename}`);

        return [
            ...dl('artifacts.zip'),
            ...dl('font-subset.zip'),
        ]
    }

    cache() {
        const ENGINE_VERSION = fileContents(`${this.INTERNAL}/engine.version`);
        const url = `flutter_infra_release/flutter/${ENGINE_VERSION}`;

        return [
            `${url}/android-arm-profile/darwin-x64.zip`,
            `${url}/flutter-web-sdk.zip`,
            `${url}/sky_engine.zip`,
            `${url}/flutter_patched_sdk.zip`,
            `${url}/flutter_patched_sdk_product.zip`,
            `${url}/windows-x64/artifacts.zip`,
            `${url}/linux-x64/artifacts.zip`,
            `${url}/linux-arm64/artifacts.zip`,
            `${url}/darwin-x64/artifacts.zip`,
            `${url}/darwin-arm64/artifacts.zip`,
        ]
    }

    libimobiledevice() {
        const VERSION = fileContents(`${this.INTERNAL}/libimobiledevice.version`);
        const url = `flutter_infra_release/ios-usb-dependencies/libimobiledevice/${VERSION}`;
        return [
            `${url}/libimobiledevice.zip`
        ]
    }

    usbmuxd() {
        const VERSION = fileContents(`${this.INTERNAL}/usbmuxd.version`);
        const url = `flutter_infra_release/ios-usb-dependencies/usbmuxd/${VERSION}`;
        return [
            `${url}/usbmuxd.zip`
        ]
    }

    iosUsb() {
        const dl = (base: string) => {
            const VERSION = fileContents(`${this.INTERNAL}/${base}.version`);
            const url = `flutter_infra_release/ios-usb-dependencies/${base}/${VERSION}`;
            return `${url}/${base}.zip`
        }
        return [
            'libimobiledevice',
            'usbmuxd',
            'libplist',
            'openssl',
            'ios-deploy',
        ].map(dl);
    }

    android() {
        const a = [
            'windows-x64-debug/windows-x64-flutter.zip',
            'windows-x64/flutter-cpp-client-wrapper.zip',
            'windows-x64-profile/windows-x64-flutter.zip',
            'windows-x64-release/windows-x64-flutter.zip',
            'darwin-x64/FlutterMacOS.framework.zip',
            'darwin-x64/gen_snapshot.zip',
            'darwin-x64-profile/FlutterMacOS.framework.zip',
            'darwin-x64-profile/artifacts.zip',
            'darwin-x64-profile/gen_snapshot.zip',
            'darwin-x64-release/FlutterMacOS.framework.zip',
            'darwin-x64-release/artifacts.zip',
            'darwin-x64-release/gen_snapshot.zip',
            'android-arm-profile/darwin-x64.zip',
            'android-arm-release/darwin-x64.zip',
            'android-arm64-profile/darwin-x64.zip',
            'android-arm64-release/darwin-x64.zip',
            'android-x64-profile/darwin-x64.zip',
            'android-x64-release/darwin-x64.zip',
            'android-arm-profile/linux-x64.zip',
            'android-arm-release/linux-x64.zip',
            'android-arm64-profile/linux-x64.zip',
            'android-arm64-release/linux-x64.zip',
            'android-x64-profile/linux-x64.zip',
            'android-x64-release/linux-x64.zip',
            'android-arm-profile/windows-x64.zip',
            'android-arm-release/windows-x64.zip',
            'android-arm64-profile/windows-x64.zip',
            'android-arm64-release/windows-x64.zip',
            'android-x64-profile/windows-x64.zip',
            'android-x64-release/windows-x64.zip',
            'ios/artifacts.zip',
            'ios-profile/artifacts.zip',
            'ios-release/artifacts.zip',
            'android-x86/artifacts.zip',
            'android-x64/artifacts.zip',
            'android-arm/artifacts.zip',
            'android-arm-profile/artifacts.zip',
            'android-arm-release/artifacts.zip',
            'android-arm64/artifacts.zip',
            'android-arm64-profile/artifacts.zip',
            'android-arm64-release/artifacts.zip',
            'android-x64-profile/artifacts.zip',
            'android-x64-release/artifacts.zip',
            'android-x86-jit-release/artifacts.zip',
        ]
    }

    misc() {
        return [
            fileContents(`${this.INTERNAL}/gradle_wrapper.version`),
            fileContents(`${this.INTERNAL}/material_fonts.version`),
        ]
    }
}
```
