### ISSUE TITLE
The `Wrap` widget wrongly computes its max intrinsic width/height

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#44529] opened 2019-11-09 22:55 UTC
The `Wrap` widget wrongly computes its max intrinsic width/height because it forgets to add the `spacing` between children:

```
  @override
  double computeMaxIntrinsicWidth(double height) {
    switch (direction) {
      case Axis.horizontal:
        double width = 0.0;
        RenderBox child = firstChild;
        while (child != null) {
          width += child.getMaxIntrinsicWidth(double.infinity);
          SPACING MISSING HERE
          child = childAfter(child);
        }
        return width;
      case Axis.vertical:
        return _computeIntrinsicWidthForHeight(height);
    }
    return null;
  }
```

This leads to problem when `Wrap` is used inside `Flex` widgets since it uses that information to compute its own intrinsic sizes.

**Comment by iapicca** [comment] 2019-11-11 13:12
Hi @derolf 
could you please provide your updated  `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by gtrochimiuk** [comment] 2019-11-25 10:09
I am experiencing a similar problem.

flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-GB)
    • Flutter version 1.9.1+hotfix.6 at /Users/gtrochimiuk/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gtrochimiuk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • SM G920F        • 06157df691565f01                         • android-arm64 • Android 7.0 (API 24)
    • iPhone (Maciej) • b2e9c97397cb4e9d0db77340f6fd9e0beba0332a • ios           • iOS 12.4

! Doctor found issues in 1 category.
```

Minimal code sample:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.red,
        width: 100,
        child: IntrinsicHeight(
          child: Column(
            children: <Widget>[
              Wrap(
                spacing: 10,
                children: <Widget>[
                  Container(color: Colors.blue, width: 50, height: 50),
                  Container(color: Colors.green, width: 50, height: 50),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

When using spacing of 10 in this example the wrapped containers are arranged in two lines, but the intrinsic height is calculated to be 50 and it results in an exception - `A RenderFlex overflowed by 50 pixels on the bottom`.

**Comment by iapicca** [comment] 2019-12-04 15:11
Thank you @gtrochimiuk

**Comment by dnfield** [comment] 2020-02-25 08:16
Removing the Crowd label because it's not clear how many peopel this is impacting.

Removing the render label, since that is for engine/skia side rendering issues.

Removing the images label since this doesn't involve rendering images.

**Comment by andcea** [comment] 2020-03-05 21:11
Related: #29123

**Comment by iapicca** [comment] 2020-07-31 08:05
Hi @derolf 
despite your issue being older
I'm closing this issue in favour of https://github.com/flutter/flutter/issues/61204
due to higher priority assigned.

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-31 08:05 UTC
Labels: framework
