### ISSUE TITLE
iOS Flutter 2.8.1 got crash because of EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by BlakeWuh** [flutter/flutter#96855] opened 2022-01-19 12:35 UTC
## Steps to Reproduce

1. 100% of this crash happens when app is in foreground.
2. The crash got reported to Firebase console.
3. I havn't found a way to reproduce it.

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x21e0 objc_msgSend + 32
1  Flutter                        0x32108 (missing)
2  Flutter                        0x3cc60 (missing)
3  Flutter                        0x3bc850 (missing)
4  Flutter                        0x2eb0d8 (missing)
5  Flutter                        0x2ee6a4 (missing)
6  CoreFoundation                 0xa41d4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
7  CoreFoundation                 0xa3dd0 __CFRunLoopDoTimer + 1076
8  CoreFoundation                 0xa3220 __CFRunLoopDoTimers + 328
9  CoreFoundation                 0x9cfd4 __CFRunLoopRun + 1944
10 CoreFoundation                 0x9c308 CFRunLoopRunSpecific + 600
11 GraphicsServices               0x3734 GSEventRunModal + 164
12 UIKitCore                      0xbca75c -[UIApplication _run] + 1072
13 UIKitCore                      0xbcffcc UIApplicationMain + 168
14 Runner                         0x5e9c main + 10 (main.swift:10)
15 libdyld.dylib                  0x1cf8 start + 4
```

<details>
  <summary>Logs</summary>

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x21e0 objc_msgSend + 32
1  Flutter                        0x32108 (missing)
2  Flutter                        0x3cc60 (missing)
3  Flutter                        0x3bc850 (missing)
4  Flutter                        0x2eb0d8 (missing)
5  Flutter                        0x2ee6a4 (missing)
6  CoreFoundation                 0xa41d4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
7  CoreFoundation                 0xa3dd0 __CFRunLoopDoTimer + 1076
8  CoreFoundation                 0xa3220 __CFRunLoopDoTimers + 328
9  CoreFoundation                 0x9cfd4 __CFRunLoopRun + 1944
10 CoreFoundation                 0x9c308 CFRunLoopRunSpecific + 600
11 GraphicsServices               0x3734 GSEventRunModal + 164
12 UIKitCore                      0xbca75c -[UIApplication _run] + 1072
13 UIKitCore                      0xbcffcc UIApplicationMain + 168
14 Runner                         0x5e9c main + 10 (main.swift:10)
15 libdyld.dylib                  0x1cf8 start + 4
```

```
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/blake/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/blake/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/blake/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

</details>

**Comment by BlakeWuh** [comment] 2022-01-19 12:41
@flutter-symbolizer-bot [#96855 (comment)](https://github.com/flutter/flutter/issues/96855#issue-1108049453) flutter#v2.8.1 force ios release arm64

**Comment by danagbemava-nc** [comment] 2022-01-19 14:15
Hi @BlakeWuh, can we get a list of devices that are affected by this?

**Comment by BlakeWuh** [comment] 2022-01-20 02:47
iOS 14, 15 iPadOS 15

devices

iPhone 11
iPhone 12 Pro Max
iPhone XR 
iPhone XS Max
iPhone 13 Pro Max
iPhone 11 Pro
iPhone 12 Pro
iPhone 11 Pro Max

BTW, our app don't support iOS 12 or below.

**Comment by danagbemava-nc** [comment] 2022-01-20 06:19
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/96855#issue-1108049453 force flutter#v2.8.1 ios release arm64

**Comment by danagbemava-nc** [comment] 2022-01-20 06:27
The symbolized logs from https://github.com/flutter/flutter/issues/96855#issuecomment-1017155664 match the logs from https://github.com/flutter/flutter/issues/96850#issuecomment-1016493402. 

This is likely the same crash just happening on a different set of devices. 

Closing as duplicate of https://github.com/flutter/flutter/issues/96850

Thank you

**Closed by danagbemava-nc** 2022-01-20 06:27 UTC
Labels: in triage
