### ISSUE TITLE
[in_app_purchase] Android: Null status from queryPastPurchases

### ISSUE THREAD

**Issue by jonjon1123** [flutter/flutter#37980] opened 2019-08-09 23:06 UTC
I have noticed that the in_app_purchase plugin returns a null status when I call `queryPastPurchases` on Android (but not iOS). After diving into the plugin code, I noticed that the `queryPastPurchases` method calls `billingClient.queryPurchases`. I noticed that method has comments that say "Unlike [queryPurchaseHistory], This does not make a network request and does not return items that are no longer owned."(https://github.com/flutter/plugins/blob/b48dd36fccc6edf6b37a0291a90d3efccd8d2b78/packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart#L163). So what is sounds like is that it only returns active purchases (no refunded or cancelled purchases). If this is the case, does it make since to set the status to `purchased` when the mapping from `PurchaseWrapper` to `PurchaseDetails` is done (https://github.com/flutter/plugins/blob/b48dd36fccc6edf6b37a0291a90d3efccd8d2b78/packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart#L113)?

**Comment by lesnitsky** [comment] 2019-08-13 15:39
I'm having the same issue. What's the right way to determine if user had previously purchased some item? (let say app was removed and all local data was lost)

**Comment by lesnitsky** [comment] 2019-08-13 15:53
Just to clarify: `queryPastPurchases` returns a list of `PurchaseDetails` for me, but `status` is null

**Comment by nanox77** [comment] 2019-08-29 12:23
I'm running in real device and I have same issue using version ^0.2.1.

**Comment by alekxlight** [comment] 2019-09-02 23:11
I am having the same issue as well.  I close the app and, although the in-app purchase PurchaseDetails is not null, the STATUS for that purchase IS null.   This documentation https://pub.dev/documentation/in_app_purchase/latest/in_app_purchase/PurchaseStatus-class.html states that error, pending and purchased are the possible values of status. Thank you.

**Comment by Dimous** [comment] 2019-11-09 10:29
To overcome this bug I have to read purchaseState from localVerificationData if Platform.isAndroid.
Please, assign someone to look at this issue!

**Comment by Dimous** [comment] 2019-11-10 15:10
Dirty workaround:
if Platform.isAndroid and status is null then parse `this._purchaseDetails?.verificationData?.localVerificationData`
if resulting map contains `purchaseState` then map it to [PurchaseStatus.purchased, PurchaseStatus.error/* there should be canceled */, PurchaseStatus.pending][parsedData["purchaseState"] as int]

https://developers.google.com/android-publisher/api-ref/purchases/products#purchaseState

**Comment by cyanglaz** [comment] 2020-02-10 23:59
@lesnitsky Could you try the latest version? I just tried and queryPastPurchases does return purchaseDetails with non-null status.

**Comment by lesnitsky** [comment] 2020-02-11 11:51
@cyanglaz did you try to get the value right after purchase or did you restart the app?

**Comment by cyanglaz** [comment] 2020-02-11 16:53
@lesnitsky I restart the app. Would you mind maybe providing a sample `main.dart` with minimum code to reproduce the issue?

**Comment by BeMacized** [comment] 2021-04-01 13:30
Closing this as I'm quite sure this is a duplicate of #38671.

**Closed by BeMacized** 2021-04-01 13:30 UTC
Labels: customer: crowd, p: first party, p: in_app_purchase, plugin
