### ISSUE TITLE
Make a flutter gallery for Official plugins

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#18237] opened 2018-06-06 13:11 UTC
The official flutter plugins are really useful. 
Would it not be smart to have a flutter gallery plugins app tmso developers can get firsthand experience and the plugin team get more cross device testing ??

**Comment by xster** [comment] 2018-06-06 18:48
cc @mit-mit

**Comment by mit-mit** [comment] 2018-06-07 09:15
@gedw99 do you mean on flutter.io, or on Pub? Or really on either, just make these more showcased?

**Comment by gedw99** [comment] 2018-06-07 10:22
@mit-mit I mean an app that runs on Android and IOS. And a repo of the source code of that app.

Come to think of it, It could be easier to add to the existing Flutter Gallery too if thats easier, which i think it is.
Like a new Nav Section called "Plugins", and then a Page for each once showing a typical use case for using each plugin.

But it might be easier for the Flutter team to decouple and have a separate app too.

Either is good :) JUst as long as it gets in people faces and you can collect success / failure data on lots of mobile !! Very useful to get a matrix of what plugins work and dont work on which phones.
But also good because it helps devs see how thee plugins really help solve problems too.

**Comment by mit-mit** [comment] 2018-06-07 10:55
Did you notice that each plugin has a small example app located inside it?

**Comment by gedw99** [comment] 2018-06-07 11:28
yes of course :) 

But this does not help my concerns. 
Is there data somewhere that shows a regression test matrix that cross references the official plugins to mobiles ( and their environment) ??  Is it public ?

**Comment by zoechi** [comment] 2019-02-14 18:28
Similar to #16736

**Comment by mmcc007** [comment] 2019-02-23 18:52
@gedw99 I put together an example of using the Flutter Gallery with SauceLabs to run the instrumentation test provided with Flutter Gallery (android only). You can see a video (and logs) of it running on SauceLabs here:
https://app.saucelabs.com/tests/0953cb723204478ab206b7b8f0097554/watch
and source here:
https://travis-ci.com/mmcc007/test_flutter_saucelabs/builds/102025976
 
This can be used as a starting point to maintain a test matrix on various real devices. 

It seems more work is needed to make integration testing on real devices in the cloud a practical option.

See further details on #7087

**Comment by gedw99** [comment] 2019-04-16 16:41
Thank you.
This is a great start @mmcc007

Currently using internal CI and rolling it out to internal people for beta testing for now to try to get a device matrix going. All manual still. No saucelabs automation for the tests yet 

Fledge also looks useful to help standardise the provisioning aspects and CI.

**Comment by mmcc007** [comment] 2019-04-18 17:07
@gedw99 Glad you found the above experiments and fledge helpful.

If seems there is no CI/CD framework or reference for mobile development in general. Every dev has to kinda invent there own. Fledge is an attempt to accumulate some best practices for Flutter and use as a starting reference point (as you mention). 

I have made a start, as mentioned above, with SauceLabs, and Genymotion. 

BTW: I also made a start on access to AWS Device Farm (currently android only):
https://github.com/mmcc007/sylph
(the Flutter team recently made a fix that should make testing in device farms easier #28662)

Mobile testing (independent of dev framework) in a CI/CD context depends on a number of things including the suitability of the services available (Saucelabs, Genymotion, AWS Device Farm, alternatives, etc..).

There seems to be room for improvement.

**Comment by stuartmorgan** [comment] 2023-03-11 14:16
I'm going to close this, as I don't think there's a compelling benefit to it that would outweigh the work of maintaining it.

In particular:

> Is there data somewhere that shows a regression test matrix that cross references the official plugins to mobiles ( and their environment) ??

A gallery app that almost nobody would have any reason to run wouldn't give us meaningful data here, not are most issues we see in practice things that would show up in metrics. Real-world issues are gathered via real apps.

And:

> This can be used as a starting point to maintain a test matrix on various real devices.

Automated tests on real devices are done via the example apps that we already have.

**Closed by stuartmorgan** 2023-03-11 14:16 UTC
Labels: team, plugin, d: examples, P6
