### ISSUE TITLE
flutter frames drop when relaunch from background with IOS(specially beyond the iphoneX series device)

### ISSUE THREAD

**Issue by siu666** [flutter/flutter#96381] opened 2022-01-10 06:32 UTC
while i relaunch from background my app will frames drop in few second even though under the release mode , this situation is obiviously show in IOS(specially beyond the iphoneX series device，and my device is iphone12)，when i download the Application from App Store also has this problem。

<details>
<summary> flutter doctor -v </summary>

```

➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/jacob/Downloads/flutter2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jacob/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

```

</details>

**Comment by siu666** [comment] 2022-01-10 08:03
and my situation is similar with #35638

**Comment by darshankawar** [comment] 2022-01-10 13:32
@siu666 
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) alongwith steps to replicate and performance usage that shows the frame drops, so that we can use this info to verify further.

Thanks.

**Comment by siu666** [comment] 2022-01-10 15:09
@darshankawar thanks for viewing，

**Comment by siu666** [comment] 2022-01-10 15:12
@darshankawar thanks for viewing.
and i don't think will be the code cause this situation , like i said before . all the application that i download from App Store had reproduced the same situation~~

**Comment by darshankawar** [comment] 2022-01-11 06:04
@siu666 
Check below similar issues and see if they relate to your scenario:
https://github.com/flutter/flutter/issues/95838
https://github.com/flutter/flutter/issues/81684

**Comment by siu666** [comment] 2022-01-11 06:40
> @siu666 Check below similar issues and see if they relate to your scenario: #95838 #81684

sorry , is not relate like the issue below , here is the specifically situation(under IOS release mode) :
1、when i first launch my App , everything is smoothly.
2、when i  put my App to background , not only the  scrollView Jitter , but also the whole app is jittering(such like the animation) but it will be normal in a few second.
3.i have tested  with 3 series ios device : iphone7(smooth)、iphoneX(jitter)、iphone12(jitter).
@darshankawar

**Comment by siu666** [comment] 2022-01-11 06:46
sorry , is not relate like the issue below , here is the specifically situation(under IOS release mode) :
1、when i first launch my App , everything is smoothly.
2、when i put my App to background then i resume to App . not only the scrollView Jitter , but also the whole app is jittering(such like the animation) but it will be normal in a few second.
3.i have tested with 3 series ios device : iphone7(smooth)、iphoneX(jitter)、iphone12(jitter).
@darshankawar

**Comment by darshankawar** [comment] 2022-01-11 12:49
@siu666 
Can you provide us a small video of the jittery behavior ?

**Comment by darshankawar** [comment] 2022-01-13 05:38
@siu666 
Can you try [this](https://github.com/flutter/flutter/issues/31086#issue-433482411) sample code in debug and in release mode and see if you still get the same behavior as you mentioned ?

**Comment by siu666** [comment] 2022-01-13 06:46
yes , also jitter,
btw , could you give me a sample code that you can work smoothly then i can test with it ?
@darshankawar

**Comment by siu666** [comment] 2022-01-13 08:03
sorry , is it my description not clearly ？ this situation is happening all the flutter App that i download from App Store , i hope this situation can get a useful reply as soon as possible , cause i am choosing a front-end stack between RN and flutter , now i can't bring a good performance with flutter. so that i probably consider RN‘s feasibility .

**Comment by darshankawar** [comment] 2022-01-13 12:53
I tried to replicate this using sample code from here in release mode on iPhone 6s, but couldn't replicate the jittery behavior. I've requested my colleague @danagbemava-nc to verify on iphone Xs and confirm.

**Comment by siu666** [comment] 2022-01-13 15:16
yes ，under iphone8 series it wont has jitter ，but when i use iPhoneX  or further series IOS device like XS、11、12 ,it will reproduce , but when i ask someone who develop with flutter, they all develop with hybrid mode in Native client ，so i think the pure flutter develop is unusual. so that this situation is unusual~~

**Comment by danagbemava-nc** [comment] 2022-01-14 07:26
Hi @siu666, thanks for reporting this. 

## Steps to reproduce
- Run the code sample below in release mode
- Open `Instruments`
- Use the `Metal System Trace` template
- Select the flutter app you're testing from the list of apps on your device
- Start a recording
- Put the app in the background for a couple of seconds, maybe 10, 15s
- Open the app again
- Scroll for a bit and then end the recording
- Check the `Average Frame Time` from the `Display` Section
- In most cases you should see a momentary spike in the `Average frame time`
- Everything becomes normal after that

I can't share the whole instruments file because it's larger than the GH file limit

<details>
<summary>screenshots</summary>

The spike in the frame time corresponds to when the app comes from the background

<img width="1374" alt="Screenshot 2022-01-14 at 07 18 10" src="https://user-images.githubusercontent.com/88313112/149467229-92a03a39-32e1-4b41-b5fd-7119d551f331.png">

<img width="1374" alt="Screenshot 2022-01-14 at 07 18 02" src="https://user-images.githubusercontent.com/88313112/149467255-b6817d7c-9a5b-4c5a-9ba7-2f8e99120fa6.png">


</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const padding = EdgeInsets.symmetric(vertical: 10, horizontal: 10);

    return MaterialApp(
      home: Scaffold(
        body: ListView(
          children: <Widget>[
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.363, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.363 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e9a728667 (6 hours ago), 2022-01-14 09:40:11 +0800
    • Engine revision f121c1fe68
    • Dart version 2.17.0 (build 2.17.0-11.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by jmagman** [comment] 2022-01-14 18:27
> I can't share the whole instruments file because it's larger than the GH file limit

@danagbemava-nc Thanks for reproducing! Is there some place you can upload and link to share the instruments file?

/cc @gaaclarke

**Comment by danagbemava-nc** [comment] 2022-01-17 14:02
> Is there some place you can upload and link to share the instruments file?

I have uploaded a couple of them to this google drive link. It's a zip file that contains about 3 or 4 instruments files.  https://drive.google.com/file/d/1aSeVUuyOppcATVsUMnV0GkHdA6aQYGa1/view?usp=sharing

**Comment by siu666** [comment] 2022-01-18 07:52
so , is it find out the situation now ? is it the jitter cant not reproduce ?
@darshankawar @danagbemava-nc

**Comment by gaaclarke** [comment] 2022-01-18 19:11
I opened "jitter sample" trace and looked at the frame times for the "Built-in Display" probe for the time the app is launched versus the time when it comes back from the background (ignoring the first frame when coming back from the background which is an outlier at 283.48ms)

| | after launch | after foreground |
|--|--|--|
| average frame time| 24.98054475 | 25.28893162 |
| stdev | 8.353298591|8.466714082 |

Just eyeballing the first few seconds of coming back to the foreground there doesn't appear to be any deviation either.  Were you able to identify what you are experiencing with any data in the Instruments traces?

I looked at CPU usage too and nothing seems extraordinary between the 2.  The launch takes a bit more CPU than foregrounding actually.

**Comment by m-j-g** [comment] 2022-03-08 14:10
I was trying to gather information for this.  Every time I stop the cpu profiler and it is processing data it crashes.  Even if I only record for 1 second.  The frame rate is also stable when screen recording is enabled.  So, I can't show the jank in a screen record.  I did however record the frame rendering times in this attached video.

However, as I've outlined here with a minimum sample > https://github.com/flutter/flutter/issues/98886 .  It is very consistent and easy to reproduce on iPhone X or later (any iPhone bought in the last 5 years).  

In video begins with the app in the foreground.  At 5 seconds you will see that the frames stop, this is when I put the app in the background.  Then you will see the wall of red when I bring the app back into the foreground and scroll.  Soon after it returns to normal.
https://user-images.githubusercontent.com/10711395/157253973-afebe2ae-ddbb-44f2-846c-9598558fa97f.mov


The first thing our users do when they resume the app is scroll down to see more stories and it is the worst jank imaginable.   This is making the app feel low quality, especially if they are swiping back and forth between the app and other data.  The user is basically in constant jank.  

This should be a major concern and deal breaker for anyone who needs to put an iOS app into production.

**Comment by gaaclarke** [comment] 2022-03-08 18:47
> Every time I stop the cpu profiler and it is processing data it crashes.

You can try updating your Xcode.

**Comment by m-j-g** [comment] 2022-03-08 18:49
> > Every time I stop the cpu profiler and it is processing data it crashes.
> 
> You can try updating your Xcode.

I'm already on the latest version: 13.2.1.

**Comment by rotorgames** [comment] 2022-05-27 10:16
I'm not sure, but it could be related to https://github.com/flutter/flutter/issues/101653

**Comment by m-j-g** [comment] 2022-05-27 11:40
> I'm not sure, but it could be related to #101653

iPhone X, 11, and 12 have 60hz refresh rate and have this issue so I don’t think it is related

**Comment by ckjavacoder** [comment] 2022-06-08 08:08
iphone xr have this issue

**Comment by flappygod** [comment] 2022-07-16 15:12
> I'm not sure, but it could be related to #101653

Unfortunately,I found CAMetalLayer's nextDrawable takes more than 30ms in a few seconds after relaunched from background,it could be related to https://developer.apple.com/forums/thread/670453 .
Any solution?

**Comment by flappygod** [comment] 2022-07-17 05:37
> I'm not sure, but it could be related to #101653

It looks much better by setting presentsWithTransaction to YES in the few seconds,But I'm not sure if it will lead to other issues. Now, it works fine for me. Thanks for your #101653

**Comment by roybeitner** [comment] 2022-09-17 21:07
> > I'm not sure, but it could be related to #101653
> 
> 
> 
> It looks much better by setting presentsWithTransaction to YES in the few seconds,But I'm not sure if it will lead to other issues. Now, it works fine for me. Thanks for your #101653

How did you resolve it? Where did you set parentsWithTransaction?

**Comment by roybeitner** [comment] 2022-09-18 20:54
Managed to find the reason for it. Not sure why it happens and what leads to it but if you add a dark colored bottom nav bar or enable safe area in a dark color, the lag on opening or foregrounding disappears... so odd.
Tested on iPhone 13 Pro Max with 120hz enabled flutter version 3.3.2

**Comment by roybeitner** [comment] 2022-10-14 21:02
Still having this severe issue on all flutter apps I run. Any updates?

**Comment by delfme** [comment] 2022-11-09 20:53
@flappygod would you be so kind as to tell me how to set presentsWithTransaction to YES? I experience screens jank animation after app launch and on every app resume. Compiling shaders doesnt fix the issue. I’m on latest flutter stable and iphone 13 pro

**Comment by flappygod** [comment] 2022-11-10 01:37
> @flappygod would you be so kind as to tell me how to set presentsWithTransaction to YES? I experience screens jank animation after app launch and on every app resume. Compiling shaders doesnt fix the issue. I’m on latest flutter stable and iphone 13 pro

https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/ios_surface_metal_skia.mm

Just change presentsWithTransaction to yes and compile a customize engine.

**Comment by delfme** [comment] 2022-11-10 09:12
Thanks! What are the drawback of this change? Is there a custom engine already available for download?

**Comment by Noteofman** [comment] 2022-11-24 10:33
As its been asked, what is the drawback of the suggested solution, is there an update on an official solution?

**Comment by Ivan981508** [comment] 2023-01-27 20:46
It seems the problem has not been fixed even in the latest version of flutter 3.7.0

**Comment by luckysmg** [comment] 2023-02-06 10:48
Maybe 
- https://github.com/flutter/engine/pull/39359

has fixed this problem. 
Tested on iPhone XS Max and current master channel seems not to be reproduced.

**Comment by flappygod** [comment] 2023-02-10 06:18
> Maybe [flutter/engine#39359](https://github.com/flutter/engine/pull/39359)
> 
> has fixed this problem. Tested on iPhone XS Max and current master channel seems not to be reproduced.

Nice, frames drop has gone in flutter 3.7.3.

**Comment by luckysmg** [comment] 2023-02-10 06:19
Closing issue according to https://github.com/flutter/flutter/issues/96381#issuecomment-1418879552 and https://github.com/flutter/flutter/issues/96381#issuecomment-1425248877

**Closed by luckysmg** 2023-02-10 06:19 UTC
Labels: e: device-specific, platform-ios, engine, severe: performance, perf: speed, has reproducible steps, P4, perf: startup, found in release: 2.8, found in release: 2.9
