### ISSUE TITLE
[url_launcher] In iOS, when in airplane mode (i.e. no network connection), it throws `Error while launching ...`, while indeed the open webview looks good

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#130136] opened 2023-07-07 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use iOS
2. Open airplane mode, or make sure you disable network connection
3. run the launchUrl code
4. observe error

### Expected results

no error. The webview is opened correctly (though the content shows that there is no network connection). Or, at least provide a helpful error message, indicating that this is not a real exception that we should be worried.

### Actual results

has error

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:url_launcher/url_launcher.dart';

await launchUrl(Uri.parse('https://whatever-website-you-like'), mode: LaunchMode.inAppWebView);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2023-07-07 22:57
> ### Expected results
> no error.

I'm not clear on why you are expecting this behavior. Why would failing to load a URL that you asked to load not be an error?

> Or, at least provide a helpful error message

This is probably not something we would change without doing breaking changes to align with https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#platform-exception-handling

What would you want the error message to say? The only information we have is that the URL did not successfully load.

> indicating that this is not a real exception that we should be worried.

I'm not sure what this means. How is it not a "real" exception? Why would we not expect clients to care that the URL doesn't load?

**Comment by fzyzcjy** [comment] 2023-07-07 23:36
> I'm not clear on why you are expecting this behavior. Why would failing to load a URL that you asked to load not be an error?
> I'm not sure what this means. How is it not a "real" exception? Why would we not expect clients to care that the URL doesn't load?

So, here is my use case in real app (I guess many people do this): Click a button in the app, say, "open link https://google.com", and I call url_launcher to launch the webview.

In addition, I have error reporting service (Sentry for me, but others should be similar) setup, as is common the case for apps in production. That service will catch any uncaught exceptions, and report it to the server.

Now the problem is, I want to know if url_launcher really fails. For example, imagine the iPhone has a weird bug that, if I launchUrl, it will not open the webview. In that case, I want Sentry to tell me my app has a bug.

However, now url_launcher throws when there is no network, and *I have no way to distinguish it from real url_launcher bugs*, and even do not know it is because of no-network. IMHO, if there is really no network, it is normal (and expected) for a user to see WebView launched and displayed text like "no network", and no user will consider it as a real bug (indeed how can we display website without network?). If, on the other hand, the network is good, and the target website it up, but users cannot visit it, then it is a real bug, surely.

> This is probably not something we would change without doing breaking changes to align with [flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#platform-exception-handling](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#platform-exception-handling)

That looks interesting, looking forward to it!

**Comment by stuartmorgan** [comment] 2023-07-08 00:04
> In addition, I have error reporting service (Sentry for me, but others should be similar) setup, as is common the case for apps in production. That service will catch any uncaught exceptions, and report it to the server.
> 
> Now the problem is, I want to know if url_launcher really fails. For example, imagine the iPhone has a weird bug that, if I launchUrl, it will not open the webview. In that case, I want Sentry to tell me my app has a bug.
> 
> However, now url_launcher throws when there is no network, and _I have no way to distinguish it from real url_launcher bugs_

Since fixing that falls under error alignment, I'm going to go ahead and close this as a duplicate of https://github.com/flutter/flutter/issues/127665

I want to reiterate though:

> even do not know it is because of no-network

We do not receive that information from `SFSafariViewController`.

> IMHO, if there is really no network, it is normal (and expected) for a user to see WebView launched and displayed text like "no network", and no user will consider it as a real bug (indeed how can we display website without network?). If, on the other hand, the network is good, and the target website it up, but users cannot visit it, then it is a real bug, surely.

Those two cases are indistinguishable in `SFSafariViewController`.

As I commented in the other issue: we can (and should) be more structured and consistent about how we report errors, but doing that won't create information that we never had in the first place.

**Closed by stuartmorgan** 2023-07-08 00:04 UTC

**Comment by fzyzcjy** [comment] 2023-07-08 00:25
I see, thank you! (So the SFSafariViewController is really weird :( )
