### ISSUE TITLE
TextFormField's maxLength is weird working.

### ISSUE THREAD

**Issue by promhat** [flutter/flutter#68183] opened 2020-10-15 07:58 UTC
```
import 'package:flutter/material.dart';
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  String _value1 = '';
  String _value2 = '';
  void _onChange(String value) {
    _value1 = value;
    setState(() {});
  }
  void _onChangeWithTextInputType(String value) {
    _value2 = value;
    setState(() {});
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test TextFormField'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Example 1'),
            TextFormField(
              initialValue: _value1,
              maxLength: 3,
              onChanged: _onChange,
            ),
            SizedBox(height: 50),
            Text('Example 2: With KeyboardType'),
            TextFormField(
              initialValue: _value2,
              maxLength: 3,
              onChanged: _onChangeWithTextInputType,
              keyboardType: TextInputType.numberWithOptions(decimal: true),
            ),
          ],
        ),
      ),
    );
  }
}
```

<details open>

[✓] Flutter (Channel unknown, 1.22.1, on Mac OS X 10.15.7 19H2,
    locale ko-KR)
    • Flutter version 1.22.1 at /Users/hein/development/flutter
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08
      10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.1)
    • Android SDK at /Users/hein/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 48.0.3
    • Dart plugin version 201.7846.93

[✓] Connected device (1 available)
    • ANE LX2J (mobile) • 7SK7N18908000323 • android-arm64 • Android
      8.0.0 (API 26)

• No issues found!
</details>  

i find some bug in new flutter version. 

first one is maxLength is not working without keyboardType. (Issue  #68139) 

second one, if i apply keyboardType correctly, some devices can change keyboard language(ex. 'keyboardType = number' , 'devices keyboard = character'). At these cases, maxLength doesn't working either. (ex. huawei phone)

last one is maybe buffer problem. if i input '3333333' to textField(maxLength=3), field show only '333'. but, i have to backspaceBar 7 times to delete '333' while text editing.

**Comment by whoch-g2e** [comment] 2020-10-15 08:05
When tested with v1.17.4, there was no problem (version was random in the previous version)

**Comment by pedromassangocode** [comment] 2020-10-15 08:36
`maxLength` issue is being tracked by https://github.com/flutter/flutter/issues/67898. 
I'm going to  close this as a duplicate of https://github.com/flutter/flutter/issues/67898. 
Please follow up on that issue for more information.

**Closed by pedromassangocode** 2020-10-15 08:36 UTC
