### ISSUE TITLE
Google Sign In not showing logged accounts

### ISSUE THREAD

**Issue by scaraux** [flutter/flutter#65669] opened 2020-09-12 00:21 UTC
## Steps to Reproduce

1. Add google Sign In plugin to your project
2. Instantiate the GoogleSignIn

```
final GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: [
    'https://www.googleapis.com/auth/gmail.readonly',
    'https://www.googleapis.com/auth/gmail.send',
  ],
);
```

3. Call the sign in method 

```
 GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
```

**Expected results:** 

I should see a list of my Google accounts like the native iOS Google sign-in does:

![IMG_1214](https://user-images.githubusercontent.com/26309761/92982486-306af400-f453-11ea-8507-a3f9713bcec0.jpg)

**Actual results:** 

I am directly taken to the email input:

![IMG_0022](https://user-images.githubusercontent.com/26309761/92982495-3d87e300-f453-11ea-985c-6420e255ec95.jpg)

<details>
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.21.0-9.2.pre at /Users/oscar/flutter
    • Framework revision 81a45ec2e5 (2 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/oscar/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • Oscar’s iPhone (mobile) • f2e420e9b1e4de1b5ddc09364c5f26154c950cb0 • ios • iOS 13.6.1
</details>

**Comment by markusaksli-nc** [comment] 2020-09-14 08:11
Hi @scaraux 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by markusaksli-nc** 2020-09-14 08:11 UTC

**Comment by scaraux** [comment] 2020-09-15 00:06
> Hi @scaraux
> From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments and I will reopen it.
> Thank you

Could you tell me a bit more about how this is related to FlutterFire, I don't know what to mention on the FlutterFire issue

**Comment by markusaksli-nc** [comment] 2020-09-15 05:59
Ah, at first glance I thought you were using firebase. If you are just using the `google_sign_in` package without firebase then this is a known issue https://github.com/flutter/flutter/issues/48602 with an open PR. In that case no need to open an issue on FlutterFire. You can follow the mentioned issue for updates.

Sorry for the inaccurate comment.

**Comment by scaraux** [comment] 2020-09-16 22:30
> Ah, at first glance I thought you were using firebase. If you are just using the `google_sign_in` package without firebase then this is a known issue #48602 with an open PR. In that case no need to open an issue on FlutterFire. You can follow the mentioned issue for updates.
> 
> Sorry for the inaccurate comment.

No problem :)
Thanks for your help!
