### ISSUE TITLE
Camera can't initialize in Android 13 

### ISSUE THREAD

**Issue by duki97** [flutter/flutter#116804] opened 2022-12-09 21:30 UTC
When I try init camera,it can't do, I get this message in the console
 
E/flutter (10347): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference)

**Comment by danagbemava-nc** [comment] 2022-12-12 04:18
Closing this as a duplicate of https://github.com/flutter/flutter/issues/109769. 

Kindly follow up in the issue linked above for updates. 

Please upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2022-12-12 04:18 UTC
Labels: in triage
