### ISSUE TITLE
You can't tap through a fully transparent drag target.  You should be able to, imo.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1529] opened 2016-02-02 21:07 UTC
If you have something like this:

```dart
new Stack([
  new Button(), 
  new DragTarget(builder:(_,__,___) =>
    new Container(decoration:
      new BoxDecoration(backgroundColor:
        new Color(0x00000000)))];
```
You can't tap the button.

**Comment by abarth** [comment] 2016-02-02 21:15
There are a couple things going on here:

1. If you removed the DragTarget, you still wouldn't be able to tap the button.  The issue is that the container is opaque to hit testing because its drawing something.  The fact that it's drawing transparent black doesn't change the fact that it's drawing something.  For example, it should have the same behavior if you painted 0.5 opacity (or 1.0 opacity) black.

2. DragTarget uses onTapDown to trigger the drag, which means even if you hit both the button and the drag target, they'd still fight over the tap gesture.  DragTarget should use onDragDown to trigger, but that doesn't exist yet.  :)

**Comment by apwilson** [comment] 2016-02-02 21:24
For 1. would just new Container() with no background allow it to be 'tap throughable'?

For 2. you are referring to Draggable not DragTarget right?  Why does DragTarget need to listen for onDragDown?

**Comment by abarth** [comment] 2016-02-02 21:27
> For 1. would just new Container() with no background allow it to be 'tap throughable'?

Yes, although then it will be invisible to hit testing and therefore unable to receive drags.  I suspect what you want is for the button to be a child of the DragTarget.

> For 2. you are referring to Draggable not DragTarget right? Why does DragTarget need to listen for onDragDown?

Yes, you're right.  Ignore (2).  :)

**Comment by apwilson** [comment] 2016-02-02 21:31
Could I cheat to make it visible to hit testing and invisible at the same time?  Like if the child was a translucent gesture detector or something?

Making the button a child of the dragtarget does work but I've some other dragtargets I cannot do that with.

**Comment by Hixie** [comment] 2016-02-02 21:35
I think what we really want is for the DragTarget builder to be able to optionally say "include me for the purposes of hit testing when determining if a drag is hitting me and ignore me otherwise".

**Comment by abarth** [comment] 2016-02-02 21:35
Yeah, we could make it possible to have a translucent DragTarget.

**Comment by apwilson** [comment] 2016-02-02 21:48
Yeah that's essentially what I thought the behaviour would be like (having not thought about it too hard - or at all).

**Closed** 2016-02-13 01:19 UTC
Labels: affects: framework, customer: pink, ⚠ brand new feature
