### ISSUE TITLE
Add  GroundOverlayOptions for Google Maps

### ISSUE THREAD

**Issue by efoertsch** [flutter/flutter#48142] opened 2020-01-03 18:39 UTC
## Use case
I need the equivalent of  Android Google Maps GroundOverlayOptions.  Trying to rewrite an app that uses the GroundOverlayOptions (and provide iOS version) but see that feature is not yet implemented in Flutter Google Maps.

## Proposal

Implement same features as Android GroundOverlayOptions in Flutter, including transparency. The overlay api should accept png, jpeg, bitmaps, etc. Any point on the map should be clickable to allow for an infowindow to be displayed at that location and/or allow other processing/UI displays to be created. 

(Actually to cover all bases,  implement all Android map features that are not currently implemented in Flutter.)

**Comment by darshankawar** [comment] 2021-05-04 11:17
This is similar / duplicate of https://github.com/flutter/flutter/issues/26479. The original issue has more upvotes and hence closing this in favor of 26479.
If anyone disagrees, write in comments and I'll reopen this.

Thanks.

**Closed by darshankawar** 2021-05-04 11:17 UTC
Labels: P4, p: first party, p: maps, passed first triage, plugin, proposal, severe: new feature
