### ISSUE TITLE
[proposal] [website] [community] [triage] Investigate the use of `Github Discussions`

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#72013] opened 2020-12-09 20:06 UTC
## Use case

- many new issues are not bug report feature request, but **_generic questions_** or request for **_help to implement a feature_**

- I [honestly believed](https://github.com/flutter/flutter/issues/61094) that the option `I want help writing my application` pointing to [stackoverflow.com](https://stackoverflow.com/) 
would reduce the problem, but I clearly I was wrong, 
this might depend from different reasons:
   - maybe some reporter does not want to use a platform different than **github**
   - maybe some reporter is not satisfied with the experience on [stackoverflow.com](https://stackoverflow.com/) 

## Proposal

github has recently introduced [discussions](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-team-discussions), I do not have a direct experience with it, but it [looks nice](https://github.com/vercel/vercel/discussions) 
(I'm not affiliated with that repo, just the first result from google)

please consider investigate this solution to help reducing invalid issues

**Comment by pedromassango** [comment] 2020-12-09 20:25
Duplicate of https://github.com/flutter/flutter/issues/60696.

**Comment by darshankawar** [comment] 2020-12-10 06:31
Closing this as duplicate of https://github.com/flutter/flutter/issues/60696

**Closed by darshankawar** 2020-12-10 06:31 UTC
