### ISSUE TITLE
Flutter doctor crashed with Intellij Community 2021.3

### ISSUE THREAD

**Issue by arisAlexis** [flutter/flutter#95264] opened 2021-12-14 14:43 UTC
## Steps to Reproduce

1. flutter doctor -v

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2021-12-15 06:41
Closing this as duplicate of https://github.com/flutter/flutter/issues/94060

**Closed by darshankawar** 2021-12-15 06:41 UTC
Labels: in triage
