### ISSUE TITLE
LogicalKeyboardKey.arrow* constants don't map to keys encountered in events (macOS)

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#36976] opened 2019-07-25 23:56 UTC
The LogicalKeyboardKeys I'm receiving from arrow key presses on macOS do not match up with the `LogicalKeyboardKey.arrow*` constants.

These are the keyboard keys I receive:
left: `LogicalKeyboardKey(0x0000f702)`
up: `LogicalKeyboardKey(0x0000f700)`
right: `LogicalKeyboardKey(0x0000f703)`
down: `LogicalKeyboardKey(0x0000f701)`

And here are the constants:
left: `LogicalKeyboardKey(0x00100070050)`
up: `LogicalKeyboardKey(0x00100070052)`
right: `LogicalKeyboardKey(0x0010007004f)`
down: `LogicalKeyboardKey(0x00100070051)`

**Comment by shyndman** [comment] 2019-07-26 19:53
CC @stuartmorgan

**Comment by franciscojma86** [comment] 2019-07-26 23:14
Hey Scott, it seems to me like the constants you are referring to are the physical keys, not logical. They are meant to be used in different ways. If you change your layout, the physical key should always be the same, as opposed to the logical ones. They don't necessarily need to match. We get the the physical keys from the "keycode" value that macos provides.

Hope this helps.

**Comment by stuartmorgan** [comment] 2019-07-26 23:46
I did a quick test with a slightly modified version of `testbed`, and I'm seeing the same thing Scott is. Logging `event.data.logicalKey`, `event.data.physicalKey`, `LogicalKeyboardKey.arrowLeft` and pressing the left arrow I see:

```
LogicalKeyboardKey#0f702(keyId: "0x0000f702", keyLabel: "", debugName: "Key ")
PhysicalKeyboardKey#70050(usbHidUsage: "0x00070050", debugName: "Arrow Left")
LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: null, debugName: "Arrow Left"
```

Note that the logical key constant's ID matches the reported *physical* key, not the *logical* key. Seems like there's a bug in the code that's handling conversions between codes/ID for the different types.

**Comment by franciscojma86** [comment] 2019-07-27 00:13
Ah sorry, I see which constants you were referring to. IIRC, the challenge here is that macOS doesn't provide a logical keyCode, that is dependent on the layout, so we rely on the charactersIgnoringModifiers to generate the logical key, which doesn't match the constant. 
@gspencergoog any ideas on how to approach this?

**Comment by franciscojma86** [comment] 2019-07-27 02:07
Maybe before generating the LogicalKey based on the charactersIgnoringModifiers, we should check for the [modifier flags](https://developer.apple.com/documentation/appkit/nseventmodifierflags?language=objc) (in this specific case, NSEventModifierFlagFunction for arrow keys), and in that case, search for the constant based on the physicalKey.usbHidUsage as we do when keyLabel is null. I'll do some tests with that

**Comment by shyndman** [comment] 2019-07-29 17:14
Thanks for looking at this, Francisco.

**Comment by gspencergoog** [comment] 2019-08-08 18:40
Yes, the problem is probably that the platform is producing a Unicode character for those keys, whereas our pre-defined logical keys assume that those are not keys which produce a character.

**Comment by franciscojma86** [comment] 2019-09-03 16:13
Landed! (sorry for the delay)

**Closed by franciscojma86** 2019-09-03 16:13 UTC
Labels: a: desktop, framework, ⌘‬ platform-mac

**Comment by shyndman** [comment] 2019-09-03 16:20
Huzzah! Thanks :)
