### ISSUE TITLE
ListView content visible outside of ListView

### ISSUE THREAD

**Issue by maheini** [flutter/flutter#99290] opened 2022-02-28 20:01 UTC
## Details
If you set ListTile -> selected to true and set selectedTileColor, this will be visible outside the list on any transparent Wiget. Same applies to the highlight/splash effect on Inkwell Items inside ListView - the aren't cut at the border of the Listview.
Tested under Win 11, Web and Desktop app.

### Actual result
The background color of the selected ListTiles/Inkwell is visible outside of my ListView. Same applies with a Inkwell highlight on hover/splash effect.

### Expected result
No element of the list should ever be visible outside the list.

### Assets
<details>
<summary>Image showing the problem</summary>

![grafik](https://user-images.githubusercontent.com/65506676/156011739-6a8f3841-ed49-4f00-b515-7b662fd3fe7f.png)

</details>

<details>
<summary>minimal Source code</summary>

```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Container(
              height: 150,
              child: Center(
                child: Text(
                    'Container without color ->listtile background visible!'),
              )),
          Container(
              color: Colors.green,
              height: 150,
              child: const Center(
                child: Text(
                    'Container with color ->no listtile background visible'),
              )),
          Expanded(
            child: ListView.builder(
              itemCount: 100,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text('Item nr. $index'),
                  selected: index % 2 > 0 ? true : false,
                  selectedTileColor: Colors.red,
                );
              },
            ),
          )
        ],
      ),
    );
  }
}
```

</details>

<details>
<summary>Flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale de-CH)
    • Flutter version 2.10.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (10 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Martin\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Martin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • BLA L29 (mobile)  • AQH7N18927003547 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 98.0.1108.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by jason-simmons** [comment] 2022-03-01 02:34
See https://github.com/flutter/flutter/issues/86584

Try wrapping the `ListView` in a `Material` widget.

**Comment by maheshmnj** [comment] 2022-03-01 07:55
Closing as duplicate of #86584

**Closed by maheshmnj** 2022-03-01 07:55 UTC
Labels: in triage

**Comment by maheini** [comment] 2022-03-01 09:56
Thanks @jason-simmons  & @maheshmnj -> Wrapping my Listview inside Material() widget solved both problems. I really appreciate your support :)
