### ISSUE TITLE
video_player plugin showing black line in some devices 

### ISSUE THREAD

**Issue by venkata-reddy-boya** [flutter/flutter#97632] opened 2022-02-02 08:09 UTC
Sample repo to reproduce this issue: https://github.com/venkata-reddy-boya/vid_sample

**Black line coming at bottom of video with device** [moto g10 power device ](https://www.gsmarena.com/motorola_moto_g10_power-10778.php)

 log message 
 `D/MediaCodecInfo(18019): NoSupport [sizeAndRate.support, 720x894x60.0] [c2.android.avc.decoder, video/avc] [capri, moto g(10) power, motorola, 30]
`

![Screenshot_20220202-132248](https://user-images.githubusercontent.com/85147004/152115840-a566afb4-58df-4d8e-bb3c-f9e40bea0554.png)

**Working fine with android simulator**
 
![Screenshot_1643788388](https://user-images.githubusercontent.com/85147004/152115926-dab7fdbc-52e8-4ff1-8bd4-651a0b5d6c5f.png)

**Comment by venkata-reddy-boya** [comment] 2022-02-02 08:10
`rr-reddy@RR-REDDYs-Mac-mini vid_sample % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/rr-reddy/Documents/soft/flutter_soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (5 months ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rr-reddy/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • moto g 10 power (mobile)    • ZF6526NFVQ    • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.
`

**Comment by darshankawar** [comment] 2022-02-02 08:42
Closing this as duplicate of https://github.com/flutter/flutter/issues/72508

**Closed by darshankawar** 2022-02-02 08:42 UTC
Labels: in triage
