### ISSUE TITLE
Running flutter doctor through VSCode plugin isn't working

### ISSUE THREAD

**Issue by sudo-panda** [flutter/flutter#65959] opened 2020-09-16 19:38 UTC
## Steps to Reproduce

1. Install flutter and flutter plugin through VSCode
2. Install Android SDK through cli tools and add the folders to the `PATH` and other required variables like `ANDROID_SDK_ROOT` through `.zshrc`
3. Run flutter doctor through the plugin and through the integrated terminal

## Logs

Output of flutter doctor in the VSCode output panel when running it via the plugin:
```
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.4 at /opt/flutter
    • Framework revision fba99f6cf9 (2 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
exit code 0
```

Output of flutter doctor in the VSCode integrated terminal using the cli command:
```
[✓] Flutter (Channel stable, 1.20.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.4 at /opt/flutter
    • Framework revision fba99f6cf9 (2 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /opt/AndroidSDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /opt/AndroidSDK
    • ANDROID_SDK_ROOT = /opt/AndroidSDK
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • ONEPLUS A6000 (mobile) • dcd7f7fc • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-09-17 07:53
Hi @sudo-panda 
Just tried through the plugin, no issues 
```
[flutter] flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.204, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.204 at /Users/tahatesser/Code/flutter_master
    • Framework revision b2b5f2636a (17 hours ago), 2020-09-16 08:02:06 -0700
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.0
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 85.0.4183.102
    ! Error: Taha’s iPhone is busy: Copying cache files from device. Xcode will continue when Taha’s iPhone is finished. (code -10)

• No issues found!
exit code 0
```


Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-17 07:53 UTC
