### ISSUE TITLE
Flutter text widget display chinese have incorrect space in iOS device

### ISSUE THREAD

**Issue by elviskuo07** [flutter/flutter#43312] opened 2019-10-23 03:05 UTC
## Steps to Reproduce

1. Set text widgt with "測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試"

<img width="412" alt="Screen Shot 2019-10-23 at 10 54 08 AM" src="https://user-images.githubusercontent.com/6488902/67352885-c835ca00-f583-11e9-8c97-f8ed1a7d0d00.png">

2. I think Chinese text can not start with symbol(，), so have incorrect space

**Target Platform: iOS**
**Target OS version/browser: 13.0**
**Devices:  iPhone 11 Pro Max Simulator**

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale en-TW)
    • Flutter version 1.9.1+hotfix.5 at /Users/Elvis/flutter
    • Framework revision 1aedbb1835 (5 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Elvis/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/Elvis/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • A9B058A0-545B-4E8B-B772-A6B5737317F8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!

```

**Comment by VladyslavBondarenko** [comment] 2020-04-09 10:46
The issue isn't specific for iOS and Cupertino. 

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Text(
          '測試測試測試測測試測試測試測，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試，測試測試測試測試，測試測試測試，測試測試測試，測試測試',
        )
      ),
    );
  }
}
```

</details>

![image](https://user-images.githubusercontent.com/17024977/78886700-57b63300-7a67-11ea-8c58-11392f4ab617.png)

With latin `textAlign: TextAlign.justify` helps

![image](https://user-images.githubusercontent.com/17024977/78887175-14a88f80-7a68-11ea-995c-6d88b42e17be.png)
![image](https://user-images.githubusercontent.com/17024977/78887209-21c57e80-7a68-11ea-91fe-a3a5336c7cc9.png)

But not with Chinese

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/nevercode/dev/flutter_dev
    • Framework revision 8f7327f83a (2 days ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (6 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.4
    • iPhone 11 Pro Max         • 5D5365D0-C0F6-4440-B758-FFA83896129E     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4
      (simulator)
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 80.0.3987.163
    • Web Server                • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-04-09 10:49
@elviskuo07 
please follow up on https://github.com/flutter/flutter/issues/35734
Closing

**Closed by VladyslavBondarenko** 2020-04-09 10:49 UTC
Labels: a: typography, framework, has reproducible steps, release: 1.12, release: 1.17, release: 1.18
