### ISSUE TITLE
WebView visible behind iOS statusbar when using SafeArea and no appBar set

### ISSUE THREAD

**Issue by SebastianEngel** [flutter/flutter#25274] opened 2018-12-12 13:09 UTC
In one of our screens with Material Scaffold no AppBar is set and the body is a ListView containing normal Flutter widgets and a WebView. The ListView is wrapped in a SafeArea.

When scrolling up, as expected, the normal Flutter widgets are not visible behind the statusbar. Unfortunately on iOS the WebView IS visible below the statusbar. It seems like the padding given by SafeArea is not working for WebViews/PlatformViews on iOS.

I created a simple version which you can see in attached gif.

![webview-safearea](https://user-images.githubusercontent.com/1561749/49871418-80e49600-fe16-11e8-9b15-c2b39aab0f21.gif)

Here is my output of `flutter doctor -v`:

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale de-DE)
    • Flutter version 1.0.0 at /Users/basti/Coding/SDKs/flutter
    • Framework revision 5391447fae (vor 12 Tagen), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/basti/Coding/SDKs/android-sdk-macosx/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/basti/Coding/SDKs/android-sdk-macosx/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by zoechi** [comment] 2018-12-12 13:14
To investigate a minimal runnable reproduction would be helpful
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by SebastianEngel** [comment] 2018-12-12 13:19
Sure, here's the sample's main.dart

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView(children: <Widget>[
          Container(
            padding: const EdgeInsets.all(8),
            alignment: Alignment.center,
            color: Colors.red,
            child: Text("This is a container widget with Text. "
                "\nBelow is a WebView.\n\nAs the Container the WebView should NOT show up behind the status bar.", textAlign: TextAlign.center,),
          ),
          Container(
              height: 1200,
              child: const WebView(
                initialUrl: 'https://flutter.io',
                javaScriptMode: JavaScriptMode.unrestricted,
              ))
        ],),

      ),
    );
  }
}

```

**Comment by SebastianEngel** [comment] 2018-12-12 13:20
Using webview_flutter: ^0.0.1

**Comment by zoechi** [comment] 2018-12-12 13:22
Any specific reason you're not using `0.1.0+1`?

**Comment by cyanglaz** [comment] 2019-01-08 00:04
This is a result of the UIKitView not being clipped. There is an open issue on UIKitView being clipped being tracked here https://github.com/flutter/flutter/issues/25965 . If you really need this right now, you can maybe workaround by covering the status bar using a container. e.g.

```
class WebViewExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          SafeArea(
            child: ListView(
              children: <Widget>[
                Container(
                  padding: const EdgeInsets.all(8),
                  alignment: Alignment.center,
                  color: Colors.red,
                  child: const Text(
                    "This is a container widget with Text. "
                        "\nBelow is a WebView.\n\nAs the Container the WebView should NOT show up behind the status bar.",
                    textAlign: TextAlign.center,
                  ),
                ),
                Container(
                  height: 1200,
                  child: const WebView(
                    initialUrl: 'https://flutter.io',
                  ),
                )
              ],
            ),
          ),
          Builder(
            builder: (BuildContext context) {
              return Container(
                height: MediaQuery.of(context).padding.top,
                decoration: BoxDecoration(
                    color: Scaffold.of(context).widget.backgroundColor),
              );
            },
          ),
        ],
      ),
    );
  }
}
```

Duplicate of #25965

**Closed by cyanglaz** 2019-01-08 00:04 UTC
Labels: p: first party, p: webview, plugin

**Comment by gankac** [comment] 2019-04-23 05:43
It didn't solve the issue. Webview still bleeds outside the container.

![Simulator Screen Shot - iPhone X - 2019-04-23 at 11 11 34](https://user-images.githubusercontent.com/13103614/56557444-a51c6480-65b8-11e9-950e-185c55d156d0.png)

**Comment by heinzan** [comment] 2019-09-26 07:29
same too
