### ISSUE TITLE
[google_maps_flutter] dynamic marker clustering feature

### ISSUE THREAD

**Issue by aytunch** [flutter/flutter#27512] opened 2019-02-04 22:16 UTC
Since Flutter is very promising tech and maps/markers in some sort are in nearly most of the modern apps, I do believe marker clustering should be implemented in google_maps_flutter asap. Can a pull request be made by an experienced developer? I am not sure if I should write this request here but i searched and did't come up with anywhere else.

**Comment by zoechi** [comment] 2019-02-07 10:16
Looks like a duplicate of #26863

**Closed by zoechi** 2019-02-07 10:16 UTC
