### ISSUE TITLE
[cloud_firestore] Nullpointer exception in firebase snapshot

### ISSUE THREAD

**Issue by ismailvellore** [flutter/flutter#36917] opened 2019-07-25 04:53 UTC
Unable to get the firebase collection snapshot due to exception.

**Code Line triggered the Exception**
`Firestore.instance.collection('post').snapshots()`

**project build.gradle**
```
buildscript {
      dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:4.3.0'
    }
}
```
**project app.gradle**
```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.1.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-core:17.0.0'
}
apply plugin: 'com.google.gms.google-services'
```
**pubspec.yaml**
```
dependencies:
  flutter:
    sdk: flutter
    cupertino_icons: ^0.1.2
    cloud_firestore: ^0.12.7+1
```
**Exception:**
```
_E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): java.lang.NullPointerException: Firestore component is not present.
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:906)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at com.google.firebase.firestore.FirebaseFirestore.getInstance(com.google.firebase:firebase-firestore@@19.0.0:88)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at com.google.firebase.firestore.FirebaseFirestore.getInstance(com.google.firebase:firebase-firestore@@19.0.0:80)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getFirestore(CloudFirestorePlugin.java:89)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getCollectionReference(CloudFirestorePlugin.java:104)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getReference(CloudFirestorePlugin.java:94)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:203)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:622)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at android.os.Looper.loop(Looper.java:169)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at android.app.ActivityThread.main(ActivityThread.java:7539)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#plugins.flutter.io/cloud_firestore(27825): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
E/flutter (27825): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Firestore component is not present., null)_
```

**Comment by QuinnZillian** [comment] 2019-08-12 09:51
Hey ismailvellore,
Did you try using the latest cloud_firestore: ^0.12.9 


As of this posting, I have success using... 
**flutter doctor**

Flutter 1.7.8+hotfix.4
Develop for Android devices (Android SDK version 29.0.0)
Android Studio (version 3.4)


**android/build.gradle**

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.0'
    }

**android/app/build.gradle**

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.app.firebase"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    dependencies {
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'androidx.test:runner:1.1.1'
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
        implementation 'androidx.multidex:multidex:2.0.0'
        implementation 'com.google.firebase:firebase-core:17.0.0'
    }

    apply plugin: 'com.google.gms.google-services'


**android/gradle/wrapper/gradle-wrapper.properties**
    distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip



 **running gradle** 
_I do get a few red Notes but everything is working_
 
Note: \flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.9\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: \flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.9\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...

**pubspec.yaml**

    firebase_core: ^0.4.0+8
    firebase_auth: ^0.14.0+1
    cloud_firestore: ^0.12.9

Good Luck

**Comment by BondarenkoStas** [comment] 2019-09-22 14:57
@ismailvellore is the issue still relevant?

**Comment by iapicca** [comment] 2019-11-11 16:07
Hi @ismailvellore 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-11 16:07 UTC
Labels: waiting for customer response
