### ISSUE TITLE
The cursor height becomes shorter when I delete all characters from TextField

### ISSUE THREAD

**Issue by YowFung** [flutter/flutter#92080] opened 2021-10-19 10:42 UTC
like the following picture:
![](https://user-images.githubusercontent.com/26346560/137885790-863d4847-baa9-470f-824c-d15f92f84d43.png)

<details>
<summary>flutter doctor -v</summary>

```log
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.17763.2237], locale    en-US)
    • Flutter version 2.5.3 at D:\SDK\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://gitee.com/mirrors/Flutter.git
    • Framework revision 18116933e7 (4 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\SDK\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\SDK\Android
    • ANDROID_SDK_ROOT = D:\SDK\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.3
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Zhanghuifeng\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.2237]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.50

• No issues found!
```
</details>

<details>
<summary>simple code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TextField Demo',
      theme: ThemeData(primarySwatch: Colors.teal),
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: 200,
            height: 80,
            child: TextField(
              controller: TextEditingController(text: "Hello"),
              minLines: 1,
              textAlignVertical: TextAlignVertical.center,
              cursorHeight: 14,
              decoration: InputDecoration(
                border: const OutlineInputBorder(),
                hintText: "HintText",
                labelText: "LabelText",
                hintStyle: const TextStyle(fontSize: 14),
                labelStyle: const TextStyle(fontSize: 15),
                counterText:  "",
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by danagbemava-nc** [comment] 2021-10-20 07:39
@YowFung, thanks for the clarification. 

One question, is there any reason in particular you need to set the `cursorHeight`?

**Comment by danagbemava-nc** [comment] 2021-10-20 13:18
I don't think it's just a matter of it becoming short. I played around with the values of the `cursorHeight` and it shows an issue with the behaviour of the cursor.

Reproducible on `stable` and `master`.

@YowFung, thanks for catching that.

<details>
<summary> videos </summary>

https://user-images.githubusercontent.com/88313112/138100035-882b1257-b26e-4e34-b3e0-c6cdb3afc539.mov


https://user-images.githubusercontent.com/88313112/138100046-d3b0eed2-beec-4d12-bc7a-bac56bf15b5a.mov


https://user-images.githubusercontent.com/88313112/138100053-aedd36ea-203e-40be-828e-88f606cf825c.mov


</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.405, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.405 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f80d1d9447 (5 hours ago), 2021-10-19 23:33:03 -0400
    • Engine revision e6a4610ebd
    • Dart version 2.15.0 (build 2.15.0-233.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```
</details>

**Comment by navaronbracke** [comment] 2021-11-07 18:11
I had reported a similar issue #87790 a little while ago. I decided if I could fix it myself. I found that the results of  `TextPainter._computeCaretMetrics()` are off. Or at least that is how it looks to me? I can still reproduce the weird cursor behaviour on `master` while testing on Android (a physical device).

Should the initial metric not try to emulate a character, 
to prevent resizing/ repositioning the caret on the y-axis?

Some examples of the `_CaretMetrics` results that I found while testing:

```
An empty EditableText

TextPainter Caret Metrics:
offset: dx 0.0, dy: 0.0
fullHeight: null -> should this not be equal to 16.40625 ?
```

```
A character in EditableText, i.e. `k`
TextPainter Caret Metrics:
offset: dx 7.09765625, dy: -0.40625
fullHeight: 16.40625
```

A single space character in EditableText yields some strange behaviour.
The metrics kept recomputing back and forth:

```
TextPainter Caret Metrics:
offset: dx 3.47265625, dy: -0.40625
fullHeight: 16.40625
TextPainter Caret Metrics:
offset: dx 0.0, dy: -0.40625
fullHeight: 16.40625
TextPainter Caret Metrics:
offset: dx 3.47265625, dy: -0.40625
fullHeight: 16.40625
TextPainter Caret Metrics:
offset: dx 0.0, dy: -0.40625
fullHeight: 16.40625

…
```

**Comment by justinmc** [comment] 2021-12-28 19:58
@GaryQian Digging into this it looks like there are some old TODOs of yours in the code related to this bug.  Do you still have any plans or insight on fixing this?

https://github.com/flutter/flutter/blob/7addb9136455a6c4d7c01c679d4727ffe86cd699/packages/flutter/lib/src/rendering/editable.dart#L2208-L2214

In that method and elsewhere there are `switch` statements that perform different behavior for Mac and iOS, which is probably why this bug doesn't seem to happen on those platforms.

When there is text in the field it uses TextPainter. getFullHeightForCaret instead ([code](https://github.com/flutter/flutter/blob/7addb9136455a6c4d7c01c679d4727ffe86cd699/packages/flutter/lib/src/rendering/editable.dart#L2845)), and the caret height is correct.

**Comment by PcolBP** [comment] 2022-06-13 11:01
Issue is reproducible on Flutter 3.0.2
![image](https://user-images.githubusercontent.com/67896443/173339569-df8127c7-0090-4719-a8a8-1fad5a1b76fc.png)
![image](https://user-images.githubusercontent.com/67896443/173339773-8bef624f-03f4-4138-81e2-0950b4e5d079.png)

![image](https://user-images.githubusercontent.com/67896443/173339981-c3a16162-cb18-42ad-aa54-17106838c9f6.png)

**Comment by jiangkang** [comment] 2022-07-21 08:06
Issue is reproducible on Flutter 3.0.5 - Platform IOS

https://user-images.githubusercontent.com/12570868/180026801-62023b6e-4730-436f-b5aa-afbc67f920d9.mp4

**Comment by antOnioOnio** [comment] 2022-08-11 08:37
Any news on this ? Anyone has come with a workaround?

**Comment by justinmc** [comment] 2022-10-05 22:26
CC @LongCatIsLooong, should be fixed with your upcoming cursor refactor.

**Closed** 2023-03-13 22:37 UTC
Labels: a: text input, framework, f: material design, f: cupertino, has reproducible steps, P4, found in release: 1.21, found in release: 2.5, found in release: 2.6
