### ISSUE TITLE
backspace button works twice at physical Android device

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#71101] opened 2020-11-23 19:40 UTC
1. build application ( $ flutter build appbundle )
2. share build application and install using "Google play internal App sharing"
3. Input word in textfield
4. press backspace

**Expected results:**
just delete 1 word

**Actual results:**
2 word will be delete

<details>

```
PS C:\Users\hatadev\Desktop\product\plotter\manga_plotter\mangaplotter> flutter doctor -v
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale ja-JP)
    • Flutter version 1.24.0-10.2.pre at C:\src\flutter
    • Framework revision 022b333a08 (5 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\hatadev\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\hatadev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server (web)             • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 87.0.664.41
```

</details>

**Comment by christopherfujino** [comment] 2020-11-23 23:44
looks like a duplicate of https://github.com/flutter/flutter/issues/70744

**Closed by christopherfujino** 2020-11-23 23:44 UTC
