### ISSUE TITLE
LayoutBuilder with AlertDialog not work

### ISSUE THREAD

**Issue by woozbooz** [flutter/flutter#35812] opened 2019-07-09 17:14 UTC
```
infoDialog(BuildContext context, String msg) async {
      _dialogBody() {
      return LayoutBuilder(
        builder: (context, constraints) {
          return
           IntrinsicHeight(
            child:
            IntrinsicWidth(
             child:
             Container(width: constraints.minWidth, height: constraints.maxHeight,
             //padding: EdgeInsets.all(10),
             decoration:
              BoxDecoration(
                borderRadius: BorderRadius.circular(20),
                border: Border.all(width: 3, color: Colors.blue)
              ),
              child: Text(msg)
            )
          ),
         );
        }
      );
    }

    return await showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return AlertDialog(
          content: SingleChildScrollView(
                    child: _dialogBody(),
                   ),
          contentPadding: EdgeInsets.zero,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          elevation: 4,
        );
      },
    );
}
```

Flutter: 1.5.4-hotfix.2:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.14393], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
[√] Connected device (1 available)
• No issues found!

**Comment by TahaTesser** [comment] 2020-04-02 15:43
It doesn't show anything, just dialog shadow 

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
          child: RaisedButton(
              onPressed: () => infoDialog(context, 'Hello World'))),
    );
  }

  infoDialog(BuildContext context, String msg) async {
    _dialogBody() {
      return LayoutBuilder(builder: (context, constraints) {
        return IntrinsicHeight(
          child: IntrinsicWidth(
              child: Container(
                  width: constraints.minWidth,
                  height: constraints.maxHeight,
                  //padding: EdgeInsets.all(10),
                  decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(width: 3, color: Colors.blue)),
                  child: Text(msg))),
        );
      });
    }

    return await showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return AlertDialog(
          content: Container(
            height: ,
            // child: _dialogBody(),
          ),
          contentPadding: EdgeInsets.zero,
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          elevation: 4,
        );
      },
    );
  }
}
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/taha/Code/flutter_stable
    • Framework revision f139b11009 (3 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-04-02 15:44
This could be related [#18108](https://github.com/flutter/flutter/issues/18108)

**Comment by TahaTesser** [comment] 2020-04-24 12:35
Duplicate of [#46063](https://github.com/flutter/flutter/issues/46063)

**Closed by TahaTesser** 2020-04-24 12:35 UTC
Labels: f: material design, framework, has reproducible steps
