### ISSUE TITLE
Windows Native App Shift+Home (Shift+End) Selection

### ISSUE THREAD

**Issue by jsheely** [flutter/flutter#77987] opened 2021-03-12 02:56 UTC
It looks like `ctrl+a` and `shift+left` or `shift+right` arrow key seletion has been made available. 

However on windows `shift+home` and `shift+end` should highlight a selection from current cursor position to respective direction and that does not appear to be working

I'm currenting using `<TextFormField / >` on build **Flutter 2.1.0-10.0.pre**

See also: https://github.com/flutter/flutter/issues/53133

**Comment by TahaTesser** [comment] 2021-03-12 12:00
HI @jsheely 
This seems to be fixed, on the latest `master` channel, I can shift + end, selects text from start o end, and vice versa

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: TextField(),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.229, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.1.0-11.0.pre.229 at C:\Users\Taha\Code\flutter_master
    • Framework revision d20ec4c7d8 (6 hours ago), 2021-03-11 22:18:51 -0800
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759
[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0
[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45
• No issues found!
```

</details>

Duplicate of https://github.com/flutter/flutter/issues/76121
Thank you

**Closed by TahaTesser** 2021-03-12 12:00 UTC
Labels: in triage
