### ISSUE TITLE
Can't retreive data from firestore

### ISSUE THREAD

**Issue by makecrepin** [flutter/flutter#87229] opened 2021-07-28 22:02 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-07-29 07:53
Hi @makecrepin 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-29 07:53 UTC
Labels: in triage

**Comment by makecrepin** [comment] 2021-08-06 19:02
Yes, now that updated my plugin and pub get the yaml file, it is working. Thank you
