### ISSUE TITLE
Inline Android and iOS WebView

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#730] opened 2015-12-04 17:50 UTC
Presumably this requires some compositor work, similar to maps or video?

**Comment by jxson** [comment] 2016-01-04 20:52
Adding an example use case for this:

I have a hybrid [Android application](https://github.com/vanadium/reader/tree/master/android) where some rendering is handled by a WebView but controls for things like navigation are handled by native UI widgets. I would like to port a version to Flutter, off the top of my head the requirements for getting this to work are:

* A way to add a WebView into the rendered tree so that it can live along side native widgets for things like navigation buttons.
* A way to allow interaction with JS in the WebView (something like [this](http://developer.android.com/reference/android/webkit/WebView.html#addJavascriptInterface(java.lang.Object, java.lang.String))).
* A way to intercept HTTP requests from the WebView.

The last item here allows us to stream the contents of PDF files to the WebView. The current Android implementation intercepts HTTP requests from the WebView and streams back the contents of the requested PDF file. The implementation can be seen [here](https://github.com/vanadium/reader/blob/master/android/app/src/main/java/io/v/android/apps/reader/PdfViewWrapper.java#L53).

I'm new to Flutter so I may have gotten some of the terminology wrong, let me know if you need clarification on anything.

**Comment by eseidelGoogle** [comment] 2016-05-13 17:05
We're currently moving towards an approach of making it easier to use native views in conjunction with FlutterView:
https://docs.google.com/document/d/1DOfwpL6VojCAG_zjjcA_z5ekF7rTIohV8dWn2o7_IME/edit

**Comment by Hixie** [comment] 2016-05-13 17:18
This is more about having a way to put a WebView within a Flutter widget tree, I think. As you say in your original comment, we need something similar for embedding videos or maps provided by a third-party non-Flutter library.

**Comment by spierce7** [comment] 2016-05-20 15:46
Something else that would be nice while considering integrating native views into flutter would be integrating flutter into existing applications.

**Comment by jingweno** [comment] 2017-01-17 15:13
Any updates on integrating a webview with flutter?

**Comment by eseidelGoogle** [comment] 2017-05-14 14:13
Looks like someone has started a plugin to do full screen webviews: https://github.com/dart-flitter/flutter_webview_plugin

**Comment by xster** [comment] 2017-05-20 08:06
I think doing the activity subset is a great start. It would unlock a whole set of app types that would need getting an oauth token from a web login.

**Comment by sethladd** [comment] 2017-06-19 15:32
FWIW: here's the PR for the iOS version of the webview plugin: https://github.com/dart-flitter/flutter_webview_plugin/pull/3

**Comment by lejard-h** [comment] 2017-06-20 19:02
We now have the webview plugin on IOS thanks to @toufikzitouni 👍 https://pub.dartlang.org/packages/flutter_webview_plugin

**Comment by Hixie** [comment] 2017-12-13 00:14
This is not on our short-term priority list. Moving to next milestone.

**Comment by csbenjamin** [comment] 2017-12-22 03:15
It would be great to have a webview and a way to interacting with it. I want to show embedded YouTube video and to control the player. Right now I am using https://github.com/dart-flitter/flutter_webview_plugin, but I am using some hack for some situations. For example, I change the webview URL in JavaScript after the video ends in order to the flutter app to receive an event onUrlChange and then to close the webview.

**Comment by eseidelGoogle** [comment] 2017-12-22 16:37
@csbenjamin Are you specifically looking for YouTube you prefer https://developers.google.com/youtube/android/player/ over a WebView to control?  Or did you also need a WebView?  If you're looking for a YouTube specific player, please file a new bug, that's definitely a reasonable request. :)

**Comment by csbenjamin** [comment] 2017-12-22 19:04
Yes, I am looking for YouTube player. I don't need anything from webview, just a YouTube player. I will open a new issue. Thanks

**Comment by megatolya** [comment] 2017-12-26 14:52
We have to open payment web form and this feature is blocker for us 😢

**Comment by lejard-h** [comment] 2017-12-29 10:51
@megatolya the webview plugin cannot do the job for you ?

**Comment by megatolya** [comment] 2018-01-10 14:50
@lejard-h 
Unfortunately no. We need to have oppurtunity to render web forms in any place on the page. Not only on top of other content or on the separate page. Manually control scroll (to reposition webview) seems too complicated for us.

I understand that this issue is by-design problem but IMHO this feature is quite fundamental to ignore.

**Comment by Hixie** [comment] 2018-01-11 05:57
This is definitely something we intend to do and we agree that it is critical for many use cases.

**Comment by osama-lionheart** [comment] 2018-02-14 19:58
Sadly this issue would also be a blocker for us to consider Flutter as we also have a similar use case to what @jxson mentioned above, and what Basecamp blogged about here:
https://m.signalvnoise.com/basecamp-3-for-ios-hybrid-architecture-afc071589c25

Using Flutter on its own to write once and deploy to both mobile platforms is already a win. But we want to go a step further and bring all of our web features in a hybrid app with enough native components to make the whole experience feels as close to native as possible, without the constant need to keep up with the new features that we introduce on our web version.

Anything that can be shared about the roadmap in relationship to this issue would be really helpful.

**Comment by eseidelGoogle** [comment] 2018-02-15 16:54
We're working on some code changes now which we expect may make inline WebViews work with Flutter on iOS.  Inline WebViews in FlutterViews on Android are a bit further off.  Sorry I don't have more specifics than that. :/

This is definitely nearing the top of our list.

**Comment by osama-lionheart** [comment] 2018-02-15 22:51
Thanks for the update.

At this point, can we tell whether this is a beta or a 1.0 release blocker?

**Comment by Sun3** [comment] 2018-03-04 18:49
Since Beta 1 as been released, is there any news on a WebView widget support?

Thanks

**Comment by mrbm** [comment] 2018-03-04 21:46
@eseidelGoogle  << bump >>

**Comment by eseidelGoogle** [comment] 2018-03-04 23:29
I recommend following https://github.com/flutter/flutter/issues/73, the work needed for both of these is similar.  Status is very similar to what I reported 17 days ago, sorry.  The situation for WebView is nearly identical to Maps as described here: https://github.com/flutter/flutter/issues/73#issuecomment-367818217

**Comment by agreensh** [comment] 2018-03-16 17:26
While you consider creating a Webview in Flutter, it would be useful to allow loading html from a string,  also giving the webview a base url (from which resources referenced in the html - .css, .js, images etc - would be loaded), as can be done in iOS (shown below) and Android.
`webView.loadHTMLString(htmlString, baseURL: locationWhereResourcesAreLocated);`

**Comment by gregko** [comment] 2018-03-18 23:28
For me too, Flutter is not an option without a fully functional WebView control, that can load HTML, local and remote URLs, execute JavaScript and enables communication between Flutter code and JavaScript in the WebView.

**Comment by letscreate** [comment] 2018-03-19 15:17
Any updates on integrating a Web View with flutter?

**Comment by DanielSmith1239** [comment] 2018-03-20 17:53
Yea, this would also be super helpful for me.

**Comment by IanDarwin** [comment] 2018-03-30 02:00
agree with agreensh - load from a string would be the icing on the cake. Maybe also from a local file (at least on Android?)? Thanks

**Comment by zoechi** [comment] 2018-03-30 04:33
@IanDarwin https://github.com/dart-flitter/flutter_webview_plugin/issues/23#issuecomment-367618709 contains a few suggestiins that should work here as well

**Comment by jaiminmehtadxred** [comment] 2018-04-03 13:48
We are plan to use flutter for our application but as describe above current sdks does not support webview with other flutter widget is a major blocker to us to use flutter as mobile application development sdk.

**Comment by andrewrabon** [comment] 2018-04-24 17:45
Flutter should not hit stable until this is added IMO.

**Comment by xuexin** [comment] 2018-05-02 08:27
Any updates about inline WebView?

**Comment by turweet** [comment] 2018-05-02 11:25
@jaiminmehtadxred I think maybe you can try to implement webview with platform-specific code that's not hard

**Comment by MaskyS** [comment] 2018-05-05 03:31
@eseidelGoogle Any progress? while flutter_webview_plugin is great, the webview is not inline. Please help us out :)

**Comment by iostriz** [comment] 2018-05-09 15:34
We have a messaging app (www.touchmoon.com) that relies heavily on WKWebView and MKMapView inside scrollable areas (as collection view cells). Since our Android app is dragging behind, there is a strong initiative to rewrite it from ground up using ReactNative (as Skype did, Discord, Instagram...).
I'm fond of Flutter, but lacking this feature is a breaking point where I have no arguments left.
Do you have ANY prediction, is there ANY chance this will be Futter first-class-citizen?

**Comment by zmasinelli** [comment] 2018-05-23 19:26
Can't build the apps we have in mind until webview is implemented...what's the status? This seems pretty vital for many designs.

**Comment by p30arena** [comment] 2018-05-25 15:11
without inline webview, apps look like ...

https://gfycat.com/LawfulZanyGecko

**Comment by MaskyS** [comment] 2018-05-30 14:55
@eseidelGoogle , @mit-mit , I know I am asking for a lot here, but is there even the smallest chance that this can moved to an earlier milestone? Lots of projects require inline webview, and the current plugin can be very often be a poor alternative. Thanks guys! p.s waiting eagerly for the beta 4 medium post :)

**Comment by xuexin** [comment] 2018-06-21 02:20
I noticed that Flutter published preview version. Does this mean that the first release will not include inline WebView?

**Comment by MaskyS** [comment] 2018-06-21 02:56
Preview without this feature seems a bit unorthodox to me :disappointed:

**Comment by Hixie** [comment] 2018-06-21 22:49
We will likely not have this feature in our 1.0 build. We are actively working on it, and will make it available as soon as we are able to do so in a manner that meets our standards of quality.

If you need this in the meantime, you can do it from Java/Kotlin or ObjectiveC/Swift by creating an OEM Web view and layering it on top of Flutter's view. This unfortunately won't properly composite with the rest of the Flutter widgets, which is why we are not advocating this as a solution.

**Comment by mdanics** [comment] 2018-06-22 03:05
So any idea when we can expect it?

**Comment by Hixie** [comment] 2018-06-22 04:01
It's very hard to predict.

One question that we're wrestling with is what Android versions to support. The more versions we support, the longer it will likely take to get a good solution. Do you have opinions on what versions of Android a Web view plugin needs to support to be viable?

**Comment by osama-lionheart** [comment] 2018-06-22 04:19
For our use case, Android 6+ should be good enough.

**Comment by jmgeffroy** [comment] 2018-06-22 04:34
5+ in our case too. We're quickly slowing down dev speed supporting 4.x
Eager to play with the first builds!

**Comment by stanonyime** [comment] 2018-06-22 04:40
Android 5+ for us

**Comment by iostriz** [comment] 2018-06-22 04:44
Android 5.x has ~20% market share with strong declining tendency.
So, if you take 6 mo to develop it for 5.0 (less than 5%), there will be no phones left to test it.
:-)
If it is easier, why don't you develop it for the flagship models (7+), release it (so that we can play with it) and you can expand support for older Androids as we go?

**Comment by Hixie** [comment] 2018-06-22 05:08
@iostriz Unfortunately, depending what version we're targetting we'd have to take entirely different approaches, because of the different APIs introduced at each version. So if it takes N months to do version X, and N+5 months to do version X-1, then it would take 2N+5 months to do version X then version X-1, but only N+5 months to do version X-1 and X at the same time. If that makes sense.

**Comment by MaskyS** [comment] 2018-06-22 06:17
5 and above would be great, as it covers the majority of the market. Inline webview is a crucial requirement for many apps, please reconsider this feature's priority.

**Comment by IanDarwin** [comment] 2018-06-22 12:35
On Thu, Jun 21, 2018 at 10:09:44PM -0700, Ian Hickson wrote:
> @iostriz Unfortunately, depending what version we're targetting we'd have
> to take entirely different approaches, because of the different APIs
> introduced at each version. So if it takes N months to do version X, and N+5
> months to do version X-1, then it would take 2N+5 months to do version X
> then version X-1, but only N+5 months to do version X-1 and X at the same
> time. If that makes sense.

Then I'd vote for 6+

**Comment by Chris1234567899** [comment] 2018-06-22 14:05
5 and above from our side

**Comment by csbenjamin** [comment] 2018-06-23 07:40
5 and above would be great for me

Em Sex, 22 de jun de 2018 11:06, Chris1234567899 <notifications@github.com>
escreveu:

**Comment by letscreate** [comment] 2018-06-23 07:59
5+ would be great!

**Comment by mannrecaged** [comment] 2018-06-26 11:11
5+ should be fine

**Comment by nekator** [comment] 2018-06-28 17:22
In my opinion 5+ should be the way to go.

**Comment by minikin** [comment] 2018-06-28 19:03
I'd like to have a really great solution, not like WKWebView, so I'm ready to wait or contribute.

**Comment by amirh** [comment] 2018-06-28 19:43
@minikin  can you be more specific regarding the issues you're having with WKWebView?

I don't think it's reasonable to embed an html engine as part of the Flutter binary. So I'm guessing we will end up with a solution that delegates to an html engine that's available on the platform (on iOS this will likely by WKWebView).

**Comment by CaiJingLong** [comment] 2018-06-29 08:02
android 5+

**Comment by minikin** [comment] 2018-06-29 08:07
@amirh 
sure, for instance, you cannot set a cookie with appropriate methods, for now (iOS11, 12beta). WKWebView just ignoring that. So you need to use workarounds.

The reason why I'd like to see some kind of WebView in Flutter that's a possibility to
use libs like d3js and render some static HTML pages.

**Comment by amirh** [comment] 2018-06-29 13:57
While a pure Flutter implementation of all widgets is the ideal.
I think we will need to make exceptions in a few cases, web view is one of them.

A pure-Flutter web view implementation (as in: everything is implemented in Dart), if at all possible (I think app store policy might be a limiting factor), will be a huge project, I'm guessing at least the scale of Flutter itself.

A plugin that embeds a web browser code (e.g [cef](https://bitbucket.org/chromiumembedded/cef)), might be possible once #7053 is resolved. I believe such an approach will still face some app store policy challenges, and will significantly increase the binary size.

I believe the reasonable and practical approach we should take for web view is to embed the platform's web view in Flutter. There are some non-trivial technical challenges involved in doing that which we are working on. I think we should use this specific issue to track the progress for getting a web view inlined. I think that solving the inlining problem will unlock a big chunk of the web view use cases, but I expect there to still be a long list of web view issues we will gradually work on (support platform's web view feature X), which I think will be more practical to track in separate issues.

**Comment by minikin** [comment] 2018-06-30 07:49
@amirh Thank you very much for the clarifications!

**Comment by a2en** [comment] 2018-07-10 11:30
Any updates on integrating a webview with flutter?

**Comment by eugenio-tesio** [comment] 2018-07-12 15:59
Updates?

**Comment by amirh** [comment] 2018-07-12 16:07
We're actively working on it, you can follow the progress of #19030.

**Comment by amirh** [comment] 2018-07-20 16:46
You might be able to come up with a plugin that embeds a web engine, I'd guess the first blocker would be #7053. Doing this will probably have a non trivial impact on the release binary size (which might be ok for some apps).
What I'm currently working on is embedding the platform's web view in Flutter.

**Comment by benbucksch** [comment] 2018-07-20 22:30
Yes, the platform WebView is a reasonable first step and sufficient for many applications.
-- 
Sent from my phone. Please excuse the brevity.

**Comment by manujbahl** [comment] 2018-07-22 22:06
On a related note is there another way to execute JavaScript code in flutter app. Right now I'm relying on creating a webview plugin and using it. The problem is that it uses a platform channel and I have to run the js asynchronously. I want to run it in a synchronous function and not have to go through future builders. 

Any ideas?

**Comment by zoechi** [comment] 2018-07-23 02:51
@manujbahl there is no other way.

**Comment by egbuna** [comment] 2018-08-05 10:25
Good day, great job you all are doing. is their support for setJavaScriptCanOpenWindowsAutomatically on the flutter webView plugin?

**Comment by BenDietze** [comment] 2018-08-14 15:08
Hanging into this list :)
I need a simple inline webview without visible controls just displaying html/css and working with js, uri via API - in a free sizeable etc. webview widget :+1: 

A real webview isn't interesting for me, but inline html/css + js and the capabilities to load extended content (like fonts from google or js libs)

**Comment by MisterJimson** [comment] 2018-09-13 16:16
Anyone try 19030 AndroidView for Web View?

**Comment by amirh** [comment] 2018-09-13 16:31
@MisterJimson there's some WIP here: https://github.com/flutter/plugins/tree/master/packages/webview_flutter

You should at most treat it just as a preview right now, there are some known bugs, iOS support is missing, and the API surface is very minimal (deliberately at this point, until we figure out the iOS story).

**Comment by pichillilorenzo** [comment] 2018-09-15 12:49
Hey guys, I released the "InAppBrowser" plugin that works in both Android and iOS systems: https://github.com/pichillilorenzo/flutter_inappbrowser

This first release is just a porting of the popular cordova-plugin-inappbrowser in order to make it work with the Flutter API.. I'm working on it for updates!!

**Comment by MichaelSowah** [comment] 2018-09-16 21:04
@pichillilorenzo your plugin is not inline and this channel is about having the browser in line

**Comment by pichillilorenzo** [comment] 2018-09-16 21:35
@MichaelSowah Yeah, I know that, thats why I wrote "I'm working on it for updates"! I will work also on that using [AndroidView](https://docs.flutter.io/flutter/widgets/AndroidView-class.html) for Android and for iOS when it will be released

**Comment by romatroskin** [comment] 2018-10-11 23:44
any updates for iOS?

**Comment by flddr** [comment] 2018-10-18 11:08
Can you explain why it is issued for years but we don't get _anything of_ `webview`in **flutter** itself? Isn't all about showing `HTML`, `CSS` and `JS` the biggest technology evolution since release of _NCSA Mosaic_? What is a technology (or a framework), _called the future of app development_, without _web view_? Isn't everything about _Google_ `the web`? :wink: 

This is a point i do not understand :question: 

For example, _inline webview_ means to **have** the power and _UI_ of `HTML`, `CSS` and hopefully `JS` to display things like the web, like _code_ in messages in _gitter webapp_, which isn't _slack App_ capable of, including `JS` libs for _syntax highlighting_ and so on.

The difference between other `widgets` and a `webview` is like between all the web and so called **RichText**Boxes...

I see a gap between all that what's done in _hybrids_ and a framework, like flutter, but, the power of a webview is nothing else than the power of browsers, of _electron_, of _atom_ and _VS Code_, of all those things we are loving _every day_.

:confused:

**Comment by zoechi** [comment] 2018-10-18 11:47
@flddr Just because it is an important feature doesn't mean it is easy and quick to add. Rather the opposite. 
You seem to assume that Google has unlimited resources and that adding enough additional developers to a team is enough to get instant results. Sadly that's not how the world works.

You can rest assured that the Flutter team is aware of this features importance and you can follow progress in https://github.com/flutter/plugins/tree/master/packages/webview_flutter

**Comment by flddr** [comment] 2018-10-18 11:56
@zoechi ups, thanks, i did never want to say this :confused: 

My guess was, it was dropped morely in development to hold a gap between _hybrids_ and _natives_, because the flutter UI itself is enormous powerful and clean, whereas the possibility _to do things in a webview_ can end in lower quality.

Thanks for the link

**Comment by zoechi** [comment] 2018-10-18 12:02
@flddr I think it's mostly that they don't want to rewrite a browser in Dart (for good reasons) and instead make native functionality available which required to implement additional capabilities for Flutter.
This capability became available recently and since then implementing webview is in progress.

https://pub.dartlang.org/packages/flutter_webview_plugin (community effort) is available since quite some time, but it had the disadvantage that it was always shown on top of Flutter widgets. For example opening a drawer menu opens it behind the webview if there is overlap.
The new plugin will work well with other Flutter widgets.

**Comment by Rockvole** [comment] 2018-10-18 15:14
Flutter uses Skia to render, and Chrome uses Skia to render so it seems like it should be an easy conversion. But you cannot add a browser into Flutter this way because any flutter apps would be banned from running on the apple store. Without cross platform ability Flutter would be abandoned. Google are right to take time with this issue.

https://www.howtogeek.com/184283/why-third-party-browsers-will-always-be-inferior-to-safari-on-iphone-and-ipad/

**Comment by flddr** [comment] 2018-10-18 19:45
@Rockvole interesting

**Comment by pichillilorenzo** [comment] 2018-10-22 05:44
Finally I released a new version (v0.5.1) of [flutter_inappbrowser](https://github.com/pichillilorenzo/flutter_inappbrowser) where there is an initial support of **inline WebViews** (`InAppWebView` class)! Obviously, this Widget is available only for Android at this moment and there are some limitation because [AndroidView](https://docs.flutter.io/flutter/widgets/AndroidView-class.html) is not stable enough.

However you can already play with it a little bit. There are a lot functions and events that you can test and use! An example of an inline WebView can be found in the README.md file of the plugin repository.

**Comment by pichillilorenzo** [comment] 2018-10-22 05:45
Finally I released a new version (v0.5.1) of [flutter_inappbrowser](https://github.com/pichillilorenzo/flutter_inappbrowser) where there is an initial support of **inline WebViews** (`InAppWebView` class)! Obviously, this Widget is available only for Android at this moment and there are some limitation because [AndroidView](https://docs.flutter.io/flutter/widgets/AndroidView-class.html) is not stable enough.

However you can already play with it a little bit. There are a lot functions and events that you can test and use! An example of an inline WebView can be found in the README.md file of the plugin repository.

**Comment by pichillilorenzo** [comment] 2018-10-22 05:46
Finally I released a new version (v0.5.1) of [flutter_inappbrowser](https://github.com/pichillilorenzo/flutter_inappbrowser) where there is an initial support of **inline WebViews** (`InAppWebView` class)! Obviously, this Widget is available only for Android at this moment and there are some limitation because [AndroidView](https://docs.flutter.io/flutter/widgets/AndroidView-class.html) is not stable enough.

However you can already play with it a little bit. There are a lot functions and events that you can test and use! An example of an inline WebView can be found in the README.md file of the plugin repository.

**Comment by imWildCat** [comment] 2018-11-08 23:58
@InMatrix Sorry for my misunderstanding. Many thanks your explanation and I really appreciate it. I look forward to the release of the official WebView plugin.

**Comment by amirh** [comment] 2018-11-10 00:34
flutter/plugins#890 added iOS support to the webview_flutter plugin.
The platform views embedding support, which the inline webview is based on, is still in early preview (see https://github.com/flutter/flutter/issues/19030#issuecomment-437534853 ).

Open issues are tagged with the [platform-views](https://github.com/flutter/flutter/labels/a%3A%20platform-views) and/or [webview](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+webview%22) labels, please upvote the issues you care about to help us prioritize.

**Closed by amirh** 2018-11-10 00:34 UTC
Labels: customer: mulligan (g3), framework, p: first party, plugin, severe: new feature

**Comment by amirh** [comment] 2018-11-10 00:46
Note that if you want to try it out on iOS you will need to enable the preview flag, see more details on:
https://github.com/flutter/flutter/issues/19030#issuecomment-437534853

**Comment by ZhennanWu** [comment] 2018-11-29 13:35
The absence of a usable WebView is really a deal-breaker to me personally.
flutter_inappbrowser is a great package that comes very close to full usability but still lacks keyboard support yet. Unfortunately, I was just going to build a code editor app........

**Comment by flddr** [comment] 2018-12-05 18:34
Congratulations to `1.0` for best mobile framework ever :tada: 

Now waiting for **webview** :relaxed:

**Comment by amirh** [comment] 2018-12-05 18:52
Just to clarify: The [webview_flutter](https://github.com/flutter/plugins/tree/master/packages/webview_flutter) plugin provides an embedded WebView on Android and iOS and is currently in developers preview.

We are tracking issues and missing features with the [webview](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22p%3A+webview%22) tag, if you care about specific issues you can help by filing an issue if there's isn't one yet, or upvoting an existing issue. PRs are of course also welcomed 😄

**Comment by danielRi** [comment] 2018-12-12 19:34
@amirh Sorry to hassle you with questions. We are heavily considering moving over to Flutter for a upcoming project, but we rely on a WebView to work (inline, flutter_webview_plugin is not an option). Do you have any information about upcoming updates or a roadmap for us? Thank you very much for any reply, keep up the great work and may the Flutter love spread around the world.

**Comment by zoechi** [comment] 2018-12-13 06:51
@danielRi https://pub.dartlang.org/packages/webview_flutter

**Comment by kyawsithu** [comment] 2019-03-14 15:16
Very interesting topic for my problem, I have come across to this topic after struggling a lot to find a right web view for flutter. Unfortunately, this new plugin (still developer preview) has a big issue with Android when I tried to open keyboard. Would that be fixed when it comes to release.

**Comment by mzulfugarov2018** [comment] 2019-04-11 13:54
assdfssdf

**Comment by v7lin** [comment] 2019-09-29 10:19
i think (foreign function interface)[https://flutter.dev/docs/development/platform-integration/c-interop] + (webkit)[https://github.com/WebKit/webkit] is best way. inline android webview or ios wkwebview is not good idea

**Comment by amirh** [comment] 2019-09-30 17:09
> i think [foreign function interface](https://flutter.dev/docs/development/platform-integration/c-interop) + [webkit](https://github.com/WebKit/webkit) is best way. inline android webview or ios wkwebview is not good idea

There are pros and cons (the obvious one is binary size).
I definitely see how for certain use case bundling a web engine would be the preferred choice.
It may be possible to add this as an alternative `webview_flutter` implementation by implementing the [platform interface](https://github.com/flutter/plugins/blob/2d1c16e5c8b510f1a80ad98f71cb6f7e491f4b87/packages/webview_flutter/lib/platform_interface.dart). If anyone gives it a shot I'm curious to lean about it!
