### ISSUE TITLE
The image_picker returns null when selecting an image from onedrive

### ISSUE THREAD

**Issue by jamesmoore255** [flutter/flutter#47240] opened 2019-12-17 18:54 UTC
## Steps to Reproduce

1. Use the image picker to choose an image from the gallery
2. Use the onedrive application on your phone to choose an image
3. print out the File object after choosing the image and it will be null, if used on a real phone the application will crash to the home screen

**Target Platform:**
Android
iOS needs to be tested
**Target OS version/browser:**

**Devices:**
Pixel 2, Pixel

## Logs

```
   info • The value of the local variable 'stateNotifications' isn't used •
          lib/my-app.dart:57:24 • unused_local_variable
   info • The value of the local variable 'updateRefCollection' isn't used •
          lib/pages/admin/admin-users.dart:71:12 • unused_local_variable
   info • The value of the local variable 'sendTest' isn't used •
          lib/pages/admin/admin-users.dart:143:22 • unused_local_variable
   info • The value of the local variable 'message' isn't used •
          lib/pages/admin/admin-users.dart:149:22 • unused_local_variable
   info • The value of the local variable 'type' isn't used •
          lib/pages/admin/admin-users.dart:150:22 • unused_local_variable
   info • The value of the local variable 'stateUser' isn't used •
          lib/pages/campaign-builder/campaign-messages-variations.dart:52:15 •
          unused_local_variable
   info • The value of the local variable 'canEdit' isn't used •
          lib/pages/campaign-builder/campaign-messages-variations.dart:53:10 •
          unused_local_variable
   info • The value of the local variable 'alert' isn't used •
          lib/pages/click/clicks-page.dart:148:11 • unused_local_variable
   info • The declaration '_auth' isn't referenced •
          lib/pages/client/client-profile.dart:15:20 • unused_element
   info • The value of the field '_clicker' isn't used •
          lib/state/state-user.dart:13:8 • unused_field
   info • The value of the local variable 'client' isn't used •
          lib/state/state-user.dart:122:12 • unused_local_variable

11 issues found. (ran in 3.9s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/james/development/flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/james/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/james/Android/Sdk
    • Java binary at:
      /home/james/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.601
      0548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at
      /home/james/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.601
      0548
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at
      /home/james/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/193.5233.102
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.40.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.1.0
      (API 27) (emulator)
```

**Comment by Dararii** [comment] 2020-01-29 07:37
this also happened on Samsung with Android Q. The return value is null at all, except from camera and download directory.

**Comment by corsantic** [comment] 2020-02-17 12:03
Any update for this issue? I have the same problem with my pixel emulator and some Samsung phones like @Dararii  said.

**Comment by xmany** [comment] 2020-02-22 23:47
had the same issue.
I am using google pixel, image_picker will return null except from camera and download

**Comment by CasperPas** [comment] 2020-02-23 03:06
I'm facing the same problem. Anything directly from device will be null.
If I select the same file from device, but via Google Photos, it will works. (Open from -> Photos -> Device folders or Cloud)

**Comment by Dararii** [comment] 2020-02-23 03:21
I think there are no updates for this issue. Please help by tapping 👍 button.

**Comment by mustakimpawle** [comment] 2020-02-27 07:26
Any update for this issue?

**Comment by corsantic** [comment] 2020-02-27 07:37
[https://stackoverflow.com/a/57804657/9854763](url)

This one works for me.

**Comment by cetorres** [comment] 2020-03-06 21:08
I can confirm that it's happening also with photos from the gallery. And also confirm that the this worked for me:

Adding this to the AndroidManifest.xml
```xml
<manifest ... >
    <!-- This attribute is "false" by default on apps targeting Android Q. -->
    <application android:requestLegacyExternalStorage="true" ... >
     ...
    </application>
</manifest>
```

Source: https://stackoverflow.com/a/57804657/9854763

**Comment by shubh-151410** [comment] 2020-04-13 22:00
thankyou @corsantic  for helping  it was like nightmare error

**Comment by cg021** [comment] 2020-05-14 16:29
Should this issue be closed? In Android 10+, requestLegacyExternalStorage has to be set to access external storage through the image picker. On APIs < 29, the attribute is not present and the bug is not happening from what I can tell. I tested this scenario on a Nexus S API 27 emulator, and it returned a file path: `/data/usr/0/com.example.pickertest/cache/<imagename.jpg>`.

**Comment by blasten** [comment] 2020-05-14 21:05
@cg021 at the very list, we should mention that in the docs: https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker - Feel free to modify `README.md` and then close this issue.

**Comment by cg021** [comment] 2020-05-14 21:15
OK. I updated the `README.md` with documentation for configuring external storage permissions.

**Closed by cg021** 2020-05-14 21:15 UTC
Labels: documentation, p: first party, p: image_picker, platform-android, plugin, severe: crash

**Comment by bittuRichestsoft** [comment] 2021-06-29 10:40
> I think there are no updates for this issue. Please help by tapping 👍 button.

use android:requestLegacyExternalStorage="true"
