### ISSUE TITLE
Text Layout CanvasKit benchmark regressed

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#118898] opened 2023-01-20 18:17 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1673574904&end=1673623515&keys=X7134ace58332d04d61af2a8b237fe871&num_commits=50&request_type=1&xbaroffset=32849

Seems to have started with https://github.com/flutter/flutter/pull/118432, which contains 1 Skia roll.

**Comment by jason-simmons** [comment] 2023-01-20 18:29
This benchmark measures `Paragraph.getBoxesForRange` and was probably affected by https://github.com/google/skia/commit/759456210de67c8c27d3ec3556fdb7c0621e2b9a

**Comment by chinmaygarde** [comment] 2023-01-23 18:36
Per @jason-simmons in triage, this is an expected regression from the change to the CanvasKit. It would be good to get confirmation of someone familiar with this subsystem to reason about the implications. cc @mdebbar perhaps.

**Comment by mdebbar** [comment] 2023-01-23 20:56
We consume Skia through CanvasKit. So if Skia has a regression, we'll get that regression too. This regression is fine for now, should we close the issue or what's the next step?

**Comment by chinmaygarde** [comment] 2023-01-23 21:10
> should we close the issue or what's the next step?

I thought you'd tell give us that guidance :) Seems like its expected?

**Comment by mdebbar** [comment] 2023-01-23 21:50
Oh, I meant that I'm okay with the regression, and wondering what the next step to hande the P0. So, I guess closing the issue is the next step?

I have a question though: do we have similar text layout benchmarks on other platforms? Were they affected too after the Skia change?

**Comment by jason-simmons** [comment] 2023-01-23 22:58
https://github.com/google/skia/commit/759456210de67c8c27d3ec3556fdb7c0621e2b9a was a change to CanvasKit that only affects the web platform.

Closing the issue as WAI.

**Closed by jason-simmons** 2023-01-23 22:58 UTC
Labels: severe: regression, engine, severe: performance, P0
