### ISSUE TITLE
Bottom insets are not stable when keyboard shows on screen on Android 11

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#65821] opened 2020-09-15 05:33 UTC
The following output is observed with the repro code found below:

```
I/flutter ( 3578): isKeyboardVisible: false, bottomPadding: 0.0
I/flutter ( 5555): isKeyboardVisible: false, bottomPadding: 0.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 797.0     <---- Why?
I/flutter ( 5555): isKeyboardVisible: false, bottomPadding: 0.0
I/flutter ( 5555): isKeyboardVisible: false, bottomPadding: 0.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 172.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 332.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 445.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 530.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 590.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 640.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 675.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 706.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 730.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 751.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 766.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 778.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 787.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 792.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 795.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 797.0
I/flutter ( 5555): isKeyboardVisible: true, bottomPadding: 797.0
```

There's a sudden jump on bottom padding to max and then a gradual increase.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeMetrics() {
    final bottomPadding = WidgetsBinding.instance.window.viewInsets.bottom;
    final isKeyboardVisible = bottomPadding > 0;
    print(
      'isKeyboardVisible: $isKeyboardVisible, bottomPadding: $bottomPadding',
    );
    if (!isKeyboardVisible && focusNode.hasFocus) {
       focusNode.unfocus();
    }
  }

  final focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              GestureDetector(
                behavior: HitTestBehavior.translucent,
                onTap: () => focusNode.unfocus(),
                child: Container(
                  height: 200,
                  color: Colors.red,
                  child:
                      Center(child: Text('Click here to unfocus text field')),
                ),
              ),
              TextField(focusNode: focusNode),
            ],
          ),
        ));
  }
}
```

(The repro code does not irrelevant things like trying to control the focus. This is due to the use case the client is trying to implement and (probably?) has nothing to do with the issue itself).

IIRC this bottomPadding trick is the only way we know and recommend for detecting keyboard open/close consistently. If there's another solution, let us know.

**Comment by mehmetf** [comment] 2020-09-15 05:34
This is a P1 since Android 11 has been released and customer:money cannot release their app with this bug.

**Comment by pedromassangocode** [comment] 2020-09-15 07:44
I was able to reproduce this on the latest beta channel. I noticed a visual problem of this issue that on Android 11 the keyboard closes without being fully opened. I consider this an issue because on previous version of Android (Android 29) it shows the keyboard without auto-close itself.

![gif](https://user-images.githubusercontent.com/67424416/93180410-06555280-f72f-11ea-8d52-3423fcfd2506.gif)

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.21.0-9.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile)        • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by xster** [comment] 2020-09-15 23:48
Assigning to @GaryQian. Please take a look.

**Comment by xster** [comment] 2020-09-15 23:50
@pcsosinski depending on the fix, we should consider this for fixing into 1.22 branch (let me know if this is the correct process).

**Comment by xster** [comment] 2020-09-15 23:53
> this bottomPadding trick is the only way we know and recommend for detecting keyboard open/close consistently. If there's another solution, let us know.

We'd love to fully address this as well. @mehmetf do you have a documentation issue to summarize the need?

**Comment by GaryQian** [comment] 2020-09-16 00:08
The delayed bounce of the flutter content is due to non-synced framerates between the flutter app and the IME. This sync issue is barely visible in physical devices. Emulators are much slower and experience extremely slow frames.

There is logic in place to capture those initial out-of-place window inset values and set them later, but it looks like in some versions, it is not working properly, I will take a deeper look.

**Comment by xster** [comment] 2020-09-16 00:09
@mehmetf do you have an upstream bug / reproduction environment? Device type / emulator etc.

**Comment by GaryQian** [comment] 2020-09-16 00:12
https://github.com/android/user-interface-samples/blob/master/WindowInsetsAnimation/app/src/main/java/com/google/android/samples/insetsanimation/RootViewDeferringInsetsCallback.kt explains the reason behind that initial outlier window inset change

**Comment by mehmetf** [comment] 2020-09-16 03:56
Internal bug is b/168563461.

AFAIK, this is affecting any Android 11 phone. I believe most test phones internally are Pixels (Pixel 3 and 4).

As for documentation bug, I don't have one. I am basing it on popular content like this:
https://stackoverflow.com/questions/48750361/flutter-detect-keyboard-open-close
https://stacksecrets.com/flutter/detect-keyboard-visibility-in-flutter-app
https://github.com/flutter/flutter/issues/28839

We also internally recommend this since AFAIK there's no reliable way to detect keyboard show/hide on Android: yaqs/6488937704062976.

**Comment by GaryQian** [comment] 2020-09-16 11:00
https://github.com/flutter/engine/pull/21213 Removes the initial extraneous call with the keyboard's final position.

Regarding the usage of `final isKeyboardVisible = bottomPadding > 0;`, with the keyboard animating in, this will no longer work since there will be multiple frames with the keyboard inset at zero before it completes its animation. With the animating keyboard feature as-is, this will either need to use different logic or add a timing delay for the keyboard to animate up.

In Android 30, there is now a way to query the windowInsets for IME visibility. I can look to see if this can be exposed somehow, maybe along with the insets data into MediaQuery.

**Comment by mehmetf** [comment] 2020-09-16 15:03
> With the keyboard animating in, this will no longer work since there will be multiple frames with the keyboard inset at zero before it completes its animation.

This flag does not need to resolve immediately when IME starts showing up. Biggest concern is its stability; it should not flip-flop to true/false while the animation is ongoing. It is OK for it to switch to true only when keyboard is fully visible.

**Comment by GaryQian** [comment] 2020-09-16 19:05
With the outlier inset fixed, you may want to consider using something similar to https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterView.java#L477 which simply uses a heuristic to determine if keyboard is shown. When the inset is smaller than a percentage of screen, the keyboard is considered visible, otherwise, it is considered hidden. This heuristic has held up so far with no issue.

**Comment by xster** [comment] 2020-09-16 19:10
> As for documentation bug, I don't have one. I am basing it on popular content like this:

ya, it's a bit of a leading question. We also can't document it since there's no real API before API 30. Even plugin solutions just do https://github.com/adee42/flutter_keyboard_visibility/blob/981f6794718654cb30b36e403505fe1ff502205b/android/src/main/java/com/github/adee42/keyboardvisibility/KeyboardVisibilityPlugin.java#L45 which is more or less what the Flutter solution is too so far. 

If there's real requirements to know if the keyboard is visible (rather than mixing it in with the rest of the media query), it would be good to know what those business needs are. Is it just a boolean people want? 

Of course this won't work in API <30 so pragmatically, what Gary [suggested](https://github.com/flutter/flutter/issues/65821#issuecomment-693601986) might still have to be the pragmatic solution.

**Comment by mehmetf** [comment] 2020-09-16 21:27
There are two board categories of use cases I have seen:

- _I want a callback when keyboard appears/disappears so I can force focus on some widget, log some interaction, etc._ This is the boolean use case and it is the most common.

- _I want to smoothly animate some widget on screen based on keyboard animation._ This is a far rarer use case since Flutter handles this already for the most part. In that case, we tell folks to use https://api.flutter.dev/flutter/dart-ui/Window/onMetricsChanged.html because they typically find that they want the same kind of animation when the screen changes size/format for any event, not just keyboard.

**Comment by xster** [comment] 2020-09-17 16:37
> I want to smoothly animate some widget on screen based on keyboard animation.

This is smoothly addressable only in Android R which has an API for it now https://github.com/flutter/flutter/issues/62876. Though a follow-up question is do we want to somehow make specifically the keyboard special and monitor that only or do you really mean "I want to smoothly animate some widget on screen based on _viewInset_ animation"?

> when keyboard appears/disappears so I can force focus on some widget

Can you elaborate on this one a bit? Typically a focus triggers a keyboard show/hide than the other way around. Maybe we're missing a use case? 

@GaryQian we can close the original issue for this now right?

**Comment by mehmetf** [comment] 2020-09-17 16:59
> do you really mean "I want to smoothly animate some widget on screen based on viewInset animation"?

From the use cases I have seen, that's what apps typically want. Keyboard just happens to be the most obvious manifestation. Again, this is a fairly rare use case, I only encountered it once in the last 2 years.

> Maybe we're missing a use case?

I don't think Flutter framework is missing a use case. Apps wanting to do "something" when keyboard opens/closes is relatively common. I will PM you some code if you are interested.

**Comment by GaryQian** [comment] 2020-09-18 19:12
flutter/engine#21213 Has landed, it should be cherry picked.

@mehmetf is using the heuristic of comparing against a ratio suggested above sufficient to resolve this issue?

**Comment by mehmetf** [comment] 2020-09-18 19:32
Could you translate that to Dart code using window metrics? I can then expose that as the canonical solution for keyboard visibility internally.

**Comment by GaryQian** [comment] 2020-09-19 00:38
Yeah, sure, it is very straightforwards:
```
// Any value from 0.10-0.30 tends to work find, but Flutter embedder currently uses 0.18 without issue
final double keyboardVisibilityThresholdRatioHeuristic = 0.18;
bool isKeyboardVisible = WidgetsBinding.instance.window.viewInsets.bottom > keyboardVisibilityThresholdRatioHeuristic;
```

This will result in the keyboard being considered "visible" midway through the animation.

**Closed** 2020-09-19 00:47 UTC
Labels: P1, cp: 1.22, customer: money (g3), e: OS Version specific, engine, found in release: 1.21, has reproducible steps, passed first triage, platform-android

**Comment by jin-dub** [comment] 2020-10-20 00:30
The problem got solved??

**Comment by pedromassangocode** [comment] 2020-10-20 06:32
> The problem got solved??

Yes.
