### ISSUE TITLE
Find a solution to the version-mismatch dependency hell

### ISSUE THREAD

**Issue by martin-braun** [flutter/flutter#128923] opened 2023-06-15 03:52 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Working with Flutter for quite a while now, I experience something that you all probably experienced once in a while. You try to use a package that is not that good maintained, thus you are getting a mismatch. For example, I try to use `flutter_localizations` and `date_picker_timeline` (less maintained) in Flutter 3.10.5 and `intl` will have a mismatch, no matter which version I pick: 

```
Because every version of flutter_localizations from sdk depends on intl 0.18.0 and fooddelivery depends on intl ^0.17.0, flutter_localizations from sdk is forbidden.
So, because fooddelivery depends on flutter_localizations from sdk, version solving failed.
```

```
Because date_picker_timeline 1.2.3 depends on intl ^0.17.0 and no versions of date_picker_timeline match >1.2.3 <2.0.0, date_picker_timeline ^1.2.3 requires intl ^0.17.0.
So, because fooddelivery depends on both intl ^0.18.0 and date_picker_timeline ^1.2.3, version solving failed.
```

### Proposal

At this point, I wouldn't care if my app grows in size. This is just a frustrating experience over and over. I think we need a way to declare a package as stale, so that it will embed its dependencies separately from the normal dependencies, so it can work without any version mis-match.

In the above example, the only two solutions to the problem are:

1. Either downgrade all other packages and Flutter, effectively moving back in time, so they play nice with the recent `date_picker_timeline` (this will cause problems sooner or later),
2. Fork `date_picker_timeline`, patch it, publish it myself

I don't like either solution, it's too much work to quickly get things going. I have an ancient Flutter 2 project that I try to modernize and a few packages aren't maintained anymore resulting in a huge load of work. I can't delay this work, because some old packages aren't compatible with the recent Apple guidelines.

This is a very frustrating experience with such a big impact that I would never pick Flutter for a new project, because I know what bitter after-math can result in this, unless you only use official packages.

I want to be able to define a package as stale, so that it keeps its dependencies separately isolated. It would increase the app size, but the current method is just a blocker and causes unnecessary cost from the business point of view. 

Having the ability to stale a package would also motivate people to build Flutter components, because they don't have to be worried to be stressed by constant **blocking** issues and PRs. They can take time to modernize their packages without people being stuck. They still should maintain their packages, but at least it won't block people who decided to pick their package in the past.

**Comment by stuartmorgan** [comment] 2023-06-15 11:25
This is a duplicate of https://github.com/dart-lang/pub/issues/2272

**Closed by stuartmorgan** 2023-06-15 11:25 UTC
Labels: waiting for customer response, in triage

**Comment by stuartmorgan** [comment] 2023-06-15 11:44
> 2\. Fork `date_picker_timeline`, patch it, publish it myself

FYI you do not need to publish a package to use it (with all the overhead of changing name, metadata, etc. that involves). If all you are doing with a fork is adjusting its dependencies to match your app's, there's no real reason to do so; you can just fork it and then adjust your pubspec to use a git reference for that package.

**Comment by martin-braun** [comment] 2023-06-15 17:24
@stuartmorgan Yep someone did exactly that so I just included his repo at a specific commit and it works, but it's still a mess to deal with. Thanks for linking my issue, so I can track it.

**Comment by martin-braun** [comment] 2023-06-16 04:05
Also @darshankawar, I've seen `dependency_override` that might solve my problem, but it will provide a version of `intl` to `date_picker_timeline` which will be untested. Probably works, but this is a recurring issue that worries me. @jonasfj also pointed me to https://pub.dev/packages/vendor which addresses my concerns and looks like a good trade-off for now. The frustration with this issue hopefully will decrease using this package.

I still hope for first class support for stale packages in `flutter pub` itself.
