### ISSUE TITLE
Firebase Auth Facebook not working on Android (prints "getGoogleApiForMethod() returned Gms")

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#23214] opened 2018-10-17 17:39 UTC
## Steps to Reproduce

I'm using `firebase_auth-0.6.2+1` and `flutter_facebook_login-1.1.1`

Here is my code

```dart
  void _facebookSignIn() async {
    final currentAT = await _facebookAuth.currentAccessToken;
    if (currentAT != null) {
      final fireUser = await _fa.signInWithFacebook(accessToken: currentAT.token);
      assert(fireUser != null);
      S.firebaseUser = fireUser;
      Navigator.of(context).pushReplacementNamed("/home");
      return;
    }
    var facebookLoginResult = await _facebookAuth.logInWithReadPermissions([]);
    switch (facebookLoginResult.status) {
      case FacebookLoginStatus.error:
        print("Error");
        return;
      case FacebookLoginStatus.cancelledByUser:
        print("CancelledByUser");
        return;
      case FacebookLoginStatus.loggedIn:
        print("LoggedIn");
        break;
    }
    final fireUser = await _fa.signInWithFacebook(accessToken: facebookLoginResult.accessToken.token);
    assert(fireUser != null);
    S.firebaseUser = fireUser;
    Navigator.of(context).pushReplacementNamed("/home");
  }
```

It works perfectly on iOS, but on Android nothing happens, except error in log on each button press

## Logs

```
Installing build/app/outputs/apk/app.apk...
Syncing files to device Pixel XL...
V/FA      (20354): Inactivity, disconnecting from the service
W/BiChannelGoogleApi(20354): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@194dfe6
W/BiChannelGoogleApi(20354): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@194dfe6
W/BiChannelGoogleApi(20354): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@194dfe6
```

```
   info • The method '_sendPush' isn't used • lib/firebaseRtcClient.dart:155:3 • unused_element
   info • Unused import: 'package:flutter/services.dart' • lib/main.dart:10:8 • unused_import
   info • The method '_createOffer' isn't used • lib/main.dart:88:8 • unused_element
   info • The method '_createAnswer' isn't used • lib/main.dart:96:8 • unused_element
   info • This function has a return type of 'Future<bool>', but doesn't end with a return statement • lib/notificationProcessor.dart:9:10 • missing_return

5 issues found. (ran in 2.7s)
```
Result isn't related to `auth_page.dart` anyway

```
```

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.3 17D47, locale en-BY)
    • Flutter version 0.9.4 at /Users/this/flutter_shit/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/this/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (3 available)
    • C6903        • BH908RZP06                               • android-arm   • Android 5.0.2 (API 21)
    • Pixel XL     • 192.168.1.19:5555                        • android-arm64 • Android 9 (API 28)
    • iPhone (Geo) • f911b0623262d44c8c67714bf804d2ff1cbe3498 • ios           • iOS 11.4.1

! Doctor found issues in 3 categories.
```

For flutter I use Android Studio

```
```

**Comment by zoechi** [comment] 2018-10-18 07:18
flutter_facebook_login-1.1.1 looks a bit outdated (last update Apr 4, 2018 https://pub.dartlang.org/packages/flutter_facebook_login#-versions-tab-)
Probably better to raise the issue there https://github.com/roughike/flutter_facebook_login/issues

**Comment by rostopira** [comment] 2018-10-18 14:05
@zoechi first of all, it works on iOS. Also, I've checked, that I got valid access token from facebook login
And yeah, check log I've attached, they are printed exactly on this line:
`final fireUser = await _fa.signInWithFacebook(accessToken: currentAT.token);`
This is clearly an issue of `firebase_auth`

**Comment by zoechi** [comment] 2018-10-18 15:33
@rostopira thanks for the additional info!

**Comment by ened** [comment] 2018-10-19 04:30
@rostopira Please collect logs with `adb logcat` as well and post them here.

Have you checked the `AndroidManifest.xml` configuration?
- Does it contain entries for `com.facebook.FacebookActivity` and `com.facebook.CustomTabActivity`?
- Did you set `com.facebook.sdk.ApplicationId`?

**Comment by fgatti675** [comment] 2018-11-29 21:18
I am facing the same issue with `firebase_auth: 0.6.6` and `flutter_facebook_login:1.1.1`
I've spent one day trying to fix it and no luck. I have checked and rechecked everything is setup properly. Google login works fine for me though

**Comment by fgatti675** [comment] 2018-12-10 17:06
I have realised this happens only when logging in with Facebook, when an already linked Google account exists with the same email, and only on Android.

**Comment by jagged3dge** [comment] 2018-12-17 10:55
I'm facing the same problem. When a previous Firebase user record exists which was created using a Google account, and user tries to log in with a Facebook account of the same email address as the Google account, this `loginWithFacebook()` doesn't return any value. Debug output appears stuck.

**Comment by diegoveloper** [comment] 2018-12-20 21:04
I have the same issue here, the problem is like @jagged3dge described, only happens when you already has a google account in Firebase auth and you try to login with a Facebook account with the same email.

I was checking the firebase_auth plugin and I see a breaking change is coming :

https://github.com/flutter/plugins/commit/a444ad120418d622c4dea2882190968722abbcfe

And this is related with the social networks credentials, but I don't when it will be released.

cc: @collinjackson  @kroikie

**Comment by jagged3dge** [comment] 2019-01-02 13:14
I'm currently having to work around this by sending the Facebook access token backend server instead. 

Using the nodejs Firebase Admin API, I can check whether a previous Firebase user record exists with Facebook as provider and also the email as read from profile of the provided Facebook access token. 

If user record exists with a different provider than Facebook, Flutter client receives a custom error (code). 
This is used to display a snackbar to the user, reporting what happened. (Struggling to find a concrete workaround to suggest to the user at this point in flow.)

If not, then send the new access token from Firebase Admin API loginWithFacebook method promise result.

(I wonder if this could this be turned into a cloud function oO)

**Comment by cyanglaz** [comment] 2019-04-05 22:03
@rostopira @fgatti675 @diegotori Is the issue still happening?

**Comment by razzazcode** [comment] 2019-04-21 21:39
i have the same issue with phone authintication of firebase pone auth .. ot prints the error 
getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzam@e848e93
whenever i try to signup a new user through the app .. the phone auth used to work before what could be wrong with it ?
![err](https://user-images.githubusercontent.com/48647269/56475850-9df93780-648e-11e9-8c68-aaaab95f915f.jpg)

**Closed** 2019-04-26 22:32 UTC
Labels: p: firebase, p: firebase_auth, p: first party, plugin, severe: crash, waiting for customer response

**Comment by kroikie** [comment] 2019-10-13 18:45
@rostopira

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/607. Any further collaboration will be done there.
