### ISSUE TITLE
flutter run on iOS doesn't detect changes to AppDelegate

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#9846] opened 2017-05-05 20:22 UTC
## Steps to Reproduce

* Attach iOS device
* flutter create myapp
* cd myapp
* flutter run
* Hit CTRL+C to kill app.
* Add some non-code string like "poop" to AppDelegate.m
* Run `flutter run` again

Instead of showing compile failures, the app relaunches.

Now uninstall the app from the simulator

flutter run now fails to compile the app with the error: "unknown type name 'poop'"

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel unknown)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision 0652737f3b (6 hours ago), 2017-05-05 09:34:55 -0500
    • Engine revision 0071651ecb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/jackson/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.1
    • CocoaPods version 1.0.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[✓] Connected devices
    • Nexus 5       • 07e401a0d00b3699                     • android-arm • Android 6.0.1 (API 23)
    • iPhone 7 Plus • 5F90A4C3-6F80-446A-88CB-5394635BF8EF • ios         • iOS 10.3 (simulator)
```

**Comment by Hixie** [comment] 2018-01-03 00:55
In general we should make sure "flutter run" (and "flutter build", etc) build whatever needs building...

**Comment by jmagman** [comment] 2021-05-27 01:36
I wasn't able to reproduce this.  Ran the first time and it worked, updated AppDelegate and `flutter run` failed:
```
Xcode's output:
↳
    /Users/m/Projects/flutter/dev/integration_tests/flutter_gallery/ios/Runner/AppDelegate.m:11:57: error: use of undeclared identifier 'poop'
      [GeneratedPluginRegistrant registerWithRegistry:self];poop
```
We've changed a lot of the Xcode/compilation caching behavior in the tool since this was reported.  Closing.

**Closed by jmagman** 2021-05-27 01:36 UTC
Labels: P4, platform-ios, plugin, tool
