### ISSUE TITLE
Forgetting a Widget's build() context argument can lead to confusion

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#1272] opened 2016-01-15 23:19 UTC
The trivial app below is wrong because the build function is missing its BuildContext argument. I have made this mistake several times.

```
import 'package:flutter/material.dart';

class BadApp extends StatelessComponent {

  Widget build() {
    return new Text("FAIL");
  }
}

void main() {
  runApp(new MaterialApp(
    routes: {
      '/': (RouteArguments args) => new BadApp()
    }
  ));
}
```

I assume that the analyzer would have warned me off running the app. Doing so yields 128 stack frames, only one of which comes from the app.  The failure mode is somewhat confusing, moreso in the context of a larger app.

```
android: --------- beginning of system
android: I/flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
android: I/flutter : Exception caught while building _ModalScopeStatus(active)
android: I/flutter : type '() => Widget' is not a subtype of type 'WidgetBuilder' of 'value'.
android: I/flutter : Stack trace:
android: I/flutter : #0      ComponentElement._builder= (packages/flutter/src/widgets/framework.dart:1136)
android: I/flutter : #1      StatelessComponentElement.StatelessComponentElement (packages/flutter/src/widgets/framework.dart:1206)
android: I/flutter : #2      StatelessComponent.createElement (packages/flutter/src/widgets/framework.dart:309)
...
android: I/flutter : #128    main (/builds/dev/flutter/examples/widgets/test.dart:15)
```

I don't know if it would be worth doing something about this.

**Comment by Hixie** [comment] 2016-01-15 23:21
The analyzer _didn't_ say anything??

**Comment by eseidelGoogle** [comment] 2016-01-15 23:55
@pq

**Comment by pq** [comment] 2016-01-19 05:29
I'm surprised by this... You should really see a static warning notifying you that you're missing the parameter.  If you're not, please open a bug on the Dart [SDK](https://github.com/dart-lang/sdk/issues/), and feel free to assign it to me.

**Comment by pq** [comment] 2016-01-19 14:50
And to be clear, the issue is that `BadApp` should look more like this?

```
class GoodApp extends StatelessComponent {
  Widget build(BuildContext context) => new Text('success');
}
```

**Comment by bwilkerson** [comment] 2016-01-19 15:56
Are you running with strong mode enabled?

If not, then I believe that the problem is that the literal map does not have an explicit type annotation, which means that it is a `Map<dynamic, dynamic>`, which is assignable to a `Map<String, RouteBuilder>`, hence no warning.

**Comment by Hixie** [comment] 2016-01-19 16:42
Oh, hey, that literal doesn't have type annotations. There ya go.

So this is basically just a duplicate of the "analyzer should complain when you imply `dynamic`" feature request.

**Comment by sethladd** [comment] 2016-01-19 17:35
FWIW I ran into this same problem. I had to add an explicit parameterized type to the `routes` parameter to get the analyzer to warn me that I put the wrong thing in the value.

**Comment by HansMuller** [comment] 2016-01-19 18:54
Just for the record, I'm going to provide a translation of my own text, since it required decoding. And I'm sorry about not having been being clear:

> I assume that the analyzer would have warned me off running the app. Doing so yields

Translation: 

> I assume that if I'd run the Dart analyzer, it would have warned me about the missing build() method parameter. I didn't run the analyzer, because I'm often impatient. When I ran the app it produced [the following exception]

**Comment by sethladd** [comment] 2016-01-19 19:09
> because I'm often impatient

You might want to keep Atom running in the background, only to provide real-time analysis. There's no real-time display of analyzer output to the console, but Atom's "problem view" is the next best thing.

**Comment by Hixie** [comment] 2017-07-25 20:35
This will be caught by the analyzer.

**Closed by Hixie** 2017-07-25 20:35 UTC
