### ISSUE TITLE
failed to debug the flutter application to an Android 8.1.0 smartphone

### ISSUE THREAD

**Issue by fritssasia** [flutter/flutter#43222] opened 2019-10-21 23:20 UTC
## exception
```
ProcessException: ProcessException: Process "/home/fritssasia/hello_apps/android/gradlew" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /home/fritssasia/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/gradle-4.10.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: /home/fritssasia/hello_apps/android/gradlew -v

```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.5, on Linux, locale en_US.UTF-8)
    [32m•[39m Flutter version 1.9.1+hotfix.5 at /home/fritssasia/Apps/flutter
    [32m•[39m Framework revision 1aedbb1835 (3 days ago), 2019-10-17 08:37:27 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/fritssasia/Apps/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /home/fritssasia/Apps/sdk
    [32m•[39m Java binary at: /home/fritssasia/Apps/android/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /home/fritssasia/Apps/android/android-studio
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.38.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.5.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m CPH1803 • 9eace264 • android-arm64 • Android 8.1.0 (API 27)

[33m![39m Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment] 2019-10-22 00:36
The most likely cause of this is a failed gradle update. We've since added some special exception handling code, but in the meantime this should be solvable by rerunning (until the update succeeds).

**Comment by iapicca** [comment] 2019-10-22 07:17
Hi @fritssasia 
could you post your `flutter run --verbose` / `flutter build --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-15 15:37
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 15:37 UTC
Labels: waiting for customer response
