### ISSUE TITLE
flutter video_player can't play m3u8 files. Throws PlatformException (MEDIA_ERR_SRC_NOT_SUPPORTED  )

### ISSUE THREAD

**Issue by sirwes** [flutter/flutter#115860] opened 2022-11-22 21:05 UTC
Hi,
I'm trying to view m3u8 files from the network in flutter web chrome through the video_player ^2.4.8. I would expect this functionality to be automatically included. If it isn't then already, then it should be.

This is the full exception 

> Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

Minimum code to reproduce:

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(const VideoApp());

/// Stateful widget to fetch and then display video content.
class VideoApp extends StatefulWidget {
  const VideoApp({Key? key}) : super(key: key);

  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        "https://content.jwplatform.com/manifests/yp34SRmf.m3u8")
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```

flutter doctor -v:
```
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
    • Flutter version 3.3.8 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at C:\Users\wesle\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\wesle\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment] 2022-11-23 10:11
Hi @sirwes 
Are you facing this issue on Chrome desktop? Please check https://github.com/flutter/flutter/issues/46778#issuecomment-567738693 for more information. It isn't supported for Chrome yet but it can play normally on Safari. 

There is also a (WIP) feature request here at #53011.

**Comment by huycozy** [comment] 2022-11-24 03:09
@sirwes It has been prioritized with p5. You might want to take a look at this: [How issue prioritization works](https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities). You can leave there your comment and react an upvote to the original comment will help to raise the issue.

Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/53011, so please follow up on it for further updates. Thank you!

**Closed by huycozy** 2022-11-24 03:09 UTC
Labels: in triage
