### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error:The operation could not be completed successfully because the file is infected with a virus or contains unwanted software., errno = 225

### ISSUE THREAD

**Issue by BurakTalhaY** [flutter/flutter#124791] opened 2023-04-13 14:13 UTC
## Command
```
flutter build apk --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Dosya virüslü olduğundan veya istenmeyebilecek yazılım içerdiğinden işlem başarılı bir şekilde tamamlanmadı.
, errno = 225
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.openSync (dart:io/file_impl.dart:473:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:533:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#5      _calculateSha (package:flutter_tools/src/android/gradle.dart:761:32)
#6      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:488:36)
<asynchronous suspension>
#7      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#8      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:111:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.22621.1555], locale tr-TR)
    [32m•[39m Flutter version 3.7.10 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4b12645012 (10 days ago), 2023-04-03 17:46:48 -0700
    [32m•[39m Engine revision ec975089ac
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\BurakTalhaYILMAZ\AppData\Local\Android\sdk
    [32m•[39m Platform android-33-ext5, build-tools 33.0.2
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.5.33516.290
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[32m[✓][39m VS Code (version 1.77.1)
    [32m•[39m VS Code at C:\Users\BurakTalhaYILMAZ\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.62.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m MI 8 Lite (mobile) • 4e3bf452 • android-arm64  • Android 10 (API 29)
    [32m•[39m Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    [32m•[39m Chrome (web)       • chrome   • web-javascript • Google Chrome 112.0.5615.86
    [32m•[39m Edge (web)         • edge     • web-javascript • Microsoft Edge 112.0.1722.39

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ad6cd72c040113b47ee9055e722606a490ef0da
### Plugins
app_install_date-0.1.2
carrier_info-2.0.8
device_info_plus-8.2.0
flutter_native_splash-2.2.19
flutter_native_timezone-2.0.0
package_info_plus-3.1.0
path_provider-2.0.14
path_provider_android-2.0.24
path_provider_foundation-2.2.2
path_provider_linux-2.1.10
path_provider_windows-2.1.5
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.8
permission_handler_windows-0.1.2
qr_code_scanner-1.0.1
share_plus-6.3.2
share_plus_web-3.1.0
toast-0.3.0
url_launcher-6.1.10
url_launcher_android-6.0.26
url_launcher_ios-6.1.4
url_launcher_linux-3.0.4
url_launcher_macos-3.0.5
url_launcher_web-2.0.16
url_launcher_windows-3.0.5

**Comment by darshankawar** [comment] 2023-04-14 05:44
I am closing this as a duplicate of https://github.com/flutter/flutter/issues/61997. The Flutter SDK cannot do anything if you are using a virus scanner that is flagging the Android SDK emulator. I can say that this is a legitimate part of the Android SDK, and you should allow-list it, per the linked issue.

**Closed by darshankawar** 2023-04-14 05:44 UTC
Labels: in triage
