### ISSUE TITLE
Tutorial First Flutter app suggestion

### ISSUE THREAD

**Issue by martin-at-ipal** [flutter/flutter#61598] opened 2020-07-16 07:39 UTC
**Problem:**
The tutorial [Write your first Flutter app, part 1 Step 4](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3) produces `error: Invalid constant value. (invalid_constant at [app1] lib/main.dart:18)`.

**Reason:**
[Step 4](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3) does not contain information about changing `        body: const Center(` (which is the case in [Step 3](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#2)) to `        body: Center(`

**Suggestion:**
Modify these two lines in [Step 4](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3) so that they guide the beginner better:
```dart
        body: Center(
          //child: Text('Hello World'),   // Replace this text...
```
as preciously both lines in [Step 3](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#2) contained `const` keyword: 
```dart
        body: Center(  // Remove "const"
          //child: const Text('Hello World'),   // Replace this text...
```

Resulting tutorial segment
```dart
import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final wordPair = WordPair.random(); // Add this line.
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(  // Remove "const"
          //child: const Text('Hello World'),   // Replace this text...
          child: Text(wordPair.asPascalCase),  // With this text.
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2020-07-16 09:16
HI @martin-at-ipal 
Looks there is an issue open for issue 
Closing as duplicate of https://github.com/flutter/flutter/issues/53375

**Closed by TahaTesser** 2020-07-16 09:16 UTC
