### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\Ale\Documents\Prueba Flutter\cuarta_app\cuarta_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', OS Error: Acceso denegado., errno = 5

### ISSUE THREAD

**Issue by Aleka764** [flutter/flutter#67922] opened 2020-10-12 14:06 UTC
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot copy file to 'C:\Users\Ale\Documents\Prueba Flutter\cuarta_app\cuarta_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', OS Error: Acceso denegado.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:267:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      Template.render (package:flutter_tools/src/template.dart:190:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:799:21)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
```
```
[✓] Flutter (Channel stable, 1.22.1, on Microsoft Windows [VersiÃ³n 10.0.17763.1282], locale es-AR)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\Ale\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by sidrao2006** [comment] 2020-10-12 14:11
Possible Duplicate of #67141

Hey @Aleka764, I found an open issue addressing your problem. Please follow up there
Thanks.

**Comment by Aleka764** [comment] 2020-10-12 14:12
Thanks @sidrao2006

**Comment by TahaTesser** [comment] 2020-10-12 15:15
Hi @Aleka764  
Please follow up on that issue, I'm closing the current one as a duplicate. https://github.com/flutter/flutter/issues/67141
If you disagree, please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-10-12 15:15 UTC
