### ISSUE TITLE
compute() does not work properly at least android release build

### ISSUE THREAD

**Issue by toda-bps** [flutter/flutter#49476] opened 2020-01-25 10:38 UTC
## Steps to Reproduce

1. Set up this app.

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(App());

Future<List<int>> generateData(int wait) {
  return Future.delayed(Duration(seconds: wait), () {
    return [0, 1, 2, 3, 4];
  });
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: FutureBuilder<List<int>>(
          future: compute(generateData, 1),
          builder: (context, snapshot) {
            debugPrint(snapshot.connectionState.toString());

            return Center(
              child: Text(
                snapshot.hasData
                    ? 'Data: ${snapshot.data.toString()}'
                    : 'No Data',
                style: Theme.of(context).textTheme.headline3,
              ),
            );
          },
        ),
      ),
    );
  }
}
```

2. `flutter run --release`, we have a problem.
3. `flutter run --debug`, works correctly. I don't know why.

* I found that reverting this change resolved the problem.

https://github.com/flutter/flutter/commit/92cbaa3efe985cc8370d0d70fef5058c971b2eee#diff-25df10da35feb4bfd4848eab0e3f208eR83

**Expected results:**

* App shows `Data: [0, 1, 2, 3, 4]` after 1 sec from startup.

**Actual results:**

* App shows `No Data` forever but connectionState is `done`.
  * You will see `I/flutter ( 5547): ConnectionState.done` log.

```console
[✓] Flutter (Channel master, v1.14.5-pre.28, on Mac OS X 10.13.6 17G10021, locale ja-JP)
    • Flutter version 1.14.5-pre.28 at /buildroot/flutter
    • Framework revision 93a5b7d419 (53 minutes ago), 2020-01-25 01:23:01 -0800
    • Engine revision 4218f8026f
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yuichi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • SHT W09 • JJN6R18C03001065 • android-arm64 • Android 9 (API 28)
    • macOS   • macOS            • darwin-x64    • Mac OS X 10.13.6 17G10021
```

**Comment by toda-bps** [comment] 2020-01-28 16:28
It seems to be fixed by undoing.

https://github.com/flutter/flutter/commit/fabeb2a16f1d008ab8230f450c49141d35669798

@dnfield Should I close this issue?

**Comment by jonahwilliams** [comment] 2020-01-28 16:30
I think this is a duplicate of https://github.com/flutter/flutter/issues/49601

**Closed by jonahwilliams** 2020-01-28 16:30 UTC
Labels: engine, framework, severe: regression

**Comment by dnfield** [comment] 2020-01-28 17:32
Sorry about that - we've added a test to cover this case specifically so we can more confidently reland the change.
