### ISSUE TITLE
[iOS] Flutter version 1.22.0 app crash on startup in release mode

### ISSUE THREAD

**Issue by sylvia971** [flutter/flutter#67597] opened 2020-10-08 03:47 UTC
Platform: iOS
Flutter version: 1.22.0

Issue: The app works fine in debug mode. But it crashes on startup I release mode. Tried with previous stable version 1.20.4, works fine in release mode.

**Comment by darshankawar** [comment] 2020-10-08 09:35
@sylvia971 
Please provide complete `flutter doctor -v`, iOS version, a minimal complete reproducible code sample along with `flutter run build ios --release --verbose` and `flutter run build apk --release --verbose`.
Thanks.

**Comment by fabrice-ndja** [comment] 2020-10-08 16:12
Before launching my application on VS code and Xcode worked very well I published it on Appstore and apple refused my request because the content of my application was reserved only for the organization and also my application crashed at startup so I migrated from individual developer account to organization developer account and since my application crashes I can't fix it and publish it on Appstore.
It works very well on Android but the problem is on IOS.
 I really need your help.

=====================================================
When I launch the application on xcode here's what I find in the console:

2020-10-07 18:18:01.264225+0000 Runner[18512:1399904] Could not load the "LaunchImage" image referenced from a nib in the bundle with identifier "com.conduireencotedivoire.conduireenci2"
2020-10-07 18:18:01.348161+0000 Runner[18512:1400779] 6.22.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001011] App Delegate Proxy is disabled.
2020-10-07 18:18:01.375846+0000 Runner[18512:1400858] flutter: Observatory listening on http://127.0.0.1:62991/wW6qsyV6PFo=/
2020-10-07 18:18:01.380712+0000 Runner[18512:1400789] 6.22.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60401000 started
2020-10-07 18:18:01.381012+0000 Runner[18512:1400789] 6.22.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-10-07 18:18:01.381469+0000 Runner[18512:1400789] 6.22.0 - [Firebase/Analytics][I-ACS025036] App Delegate Proxy is disabled
2020-10-07 18:18:01.421385+0000 Runner[18512:1399904] FBSDKLog: Unable to obtain a key window, marking <UIWindow: 0x119f3ce40; frame = (0 0; 736 414); hidden = YES; gestureRecognizers = <NSArray: 0x282075d10>; layer = <UIWindowLayer: 0x282e94240>> as keyWindow
2020-10-07 18:18:02.582723+0000 Runner[18512:1400875] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 5100 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 5100 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2020-10-07 18:18:02.695675+0000 Runner[18512:1400852] fopen failed for data file: errno = 2 (No such file or directory)
2020-10-07 18:18:02.695750+0000 Runner[18512:1400852] Errors found! Invalidating cache...
2020-10-07 18:18:03.071074+0000 Runner[18512:1400852] fopen failed for data file: errno = 2 (No such file or directory)
2020-10-07 18:18:03.071275+0000 Runner[18512:1400852] Errors found! Invalidating cache...
2020-10-07 18:18:04.485576+0000 Runner[18512:1400789] 6.22.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2020-10-07 18:18:04.613748+0000 Runner[18512:1400851] flutter: mon email sharedpreference est  null
2020-10-07 18:18:04.615485+0000 Runner[18512:1400851] flutter: mon telephone sharedpreference est  null
2020-10-07 18:18:04.685945+0000 Runner[18512:1400875] [tcp] tcp_input [C4.1.1:3] flags=[R] seq=1714190026, ack=0, win=0 state=CLOSED rcv_nxt=1714190026, snd_una=2559633045
2020-10-07 18:18:04.691304+0000 Runner[18512:1400875] [tcp] tcp_input [C6.1.1:3] flags=[R.] seq=3682261735, ack=277174350, win=122 state=CLOSED rcv_nxt=3682261695, snd_una=277174350
2020-10-07 18:18:04.694016+0000 Runner[18512:1400875] [tcp] tcp_input [C4.1.1:3] flags=[R] seq=1714190026, ack=0, win=0 state=CLOSED rcv_nxt=1714190026, snd_una=2559633045
2020-10-07 18:18:04.698246+0000 Runner[18512:1400792] 6.22.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
2020-10-07 18:18:16.212135+0000 Runner[18512:1400851] flutter: height 686.0 width 414.0
2020-10-07 18:18:22.880329+0000 Runner[18512:1400851] flutter: height 686.0 width 414.0
2020-10-07 18:18:24.453650+0000 Runner[18512:1400851] flutter: height 686.0 width 414.0
2020-10-07 18:18:27.630567+0000 Runner[18512:1400851] flutter: height 686.0 width 414.0
2020-10-07 18:18:28.676532+0000 Runner[18512:1400851] flutter: height 686.0 width 414.0
2020-10-07 18:18:30.117111+0000 Runner[18512:1400851] flutter: height 686.0 width 414.0
2020-10-07 18:21:51.051548+0000 Runner[18512:1400851] flutter: height 686.0 width 414.0

**Comment by ride4sun** [comment] 2020-10-12 20:53
I have the same problem and I think it has to do that the GoogleService-Info-Release is not available on startup. 
I am not sure why.

**Comment by pedromassangocode** [comment] 2020-11-04 12:38
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-04 12:38 UTC
