### ISSUE TITLE
Unable to load assets named "0.png"

### ISSUE THREAD

**Issue by gitboss** [flutter/flutter#35137] opened 2019-06-26 21:29 UTC
My project had series of images from 1.png to 10.png. I decided to make these 0 based and merely manually changed the names of these images from 0.png to 9.png in Windows 10 explorer. 

However now Flutter is giving errors while loading some images and loads other images. After pausing for the following exception it will load some other images.

The following error is produced after the name change - 

```
[   +1 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:50588/OlTzc04jRYM=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+6179 ms] D/EGL_emulation(10423): eglMakeCurrent: 0xe6d844e0: ver 2 0 (tinfo 0xe6d838a0)
[  +32 ms] D/EGL_emulation(10423): eglMakeCurrent: 0xe6d84360: ver 2 0 (tinfo 0xe6d837b0)
[   +6 ms] D/EGL_emulation(10423): eglMakeCurrent: 0xe6d844e0: ver 2 0 (tinfo 0xe6d838a0)
[+4615 ms] I/flutter (10423): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[   +4 ms] I/flutter (10423): The following assertion was thrown resolving an image codec:
[        ] I/flutter (10423): Unable to load asset: assets/images/underwater1/0.png
[        ] I/flutter (10423): 
[        ] I/flutter (10423): When the exception was thrown, this was the stack:
[   +7 ms] I/flutter (10423): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
[        ] I/flutter (10423): <asynchronous suspension>
[        ] I/flutter (10423): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:464:44)
[        ] I/flutter (10423): <asynchronous suspension>
[        ] I/flutter (10423): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:449:14)
[        ] I/flutter (10423): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:315:48)
[        ] I/flutter (10423): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:157:22)
[        ] I/flutter (10423): #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:315:25)
[        ] I/flutter (10423): (elided 13 frames from package dart:async)
[        ] I/flutter (10423): 
[        ] I/flutter (10423): Image provider: AssetImage(bundle: null, name: "assets/images/underwater1/0.png")
[        ] I/flutter (10423): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#bc71d(), name:
[        ] I/flutter (10423): "assets/images/underwater1/0.png", scale: 1.0)
[        ] I/flutter (10423): ════════════════════════════════════════════════════════════════════════════════════════════════════
[+20037 ms] I/flutter (10423): 0
[+20048 ms] I/flutter (10423): 0
```

My pubspec.yaml file looks like this - 
```
name: scrolling_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

```

Output of flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.292], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.35.1)
[√] Connected device (1 available)

• No issues found!
```

How do I fix this?

**Comment by gitboss** [comment] 2019-06-26 21:33
The following widget loads the images. As shown in above error I'm passing the asset name as = "assets/images/underwater1/0.png". The image path is correct since other images like "assets/images/underwater1/1.png" and "assets/images/underwater1/2.png" etc are being loaded.

```
class LoadImages extends StatelessWidget {
  const LoadImages(
      {Key key,
      @required this.left,
      @required this.asset,
      @required this.length,
      this.mirror = false})
      : super(key: key);

  final double left;
  final String asset;
  final double length;
  final bool mirror;

  @override
  Widget build(BuildContext context) {
    return Positioned(
      left: left,
      top: 0,
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
          width: length,
          height: MediaQuery.of(context).size.height,
          child: Image.asset(
            asset,
            alignment: Alignment.topLeft,
            fit: BoxFit.scaleDown,
            repeat: ImageRepeat.repeatX,
            gaplessPlayback: true,
          ),
        ),
      ),
    );
  }
}
```

**Comment by gitboss** [comment] 2019-06-26 23:04
Kindly note that I went ahead and renamed the images back to 1.png thru 10.png and it works. But I have a lot of folders. 

I would also like to confirm that Flutter has issue while loading **0.png** only. All other images load as expected. 

Please help with why Flutter wont load images named 0.png.

**Comment by BondarenkoStas** [comment] 2019-10-02 12:14
@gitboss Can you please try if `flutter clean` will fix it?

**Comment by Hixie** [comment] 2019-12-02 18:06
It would be helpful to have confirmation about whether this problem happens just when you rename the files (in which case `flutter clean` would fix it) or if it's specifically `0.png` that's the issue.

**Comment by jonahwilliams** [comment] 2019-12-02 18:38
The issue is that providing a directory argument to the asset manifest like `assets/images/` only grabs images or variants directly under the last directory, while the image you're loading is under `assets/images/underwater/`.

The fix would be to change `assets/images/` to ``assets/images/underwater`

**Comment by gitboss** [comment] 2019-12-04 19:09
I tested it again. flutter clean will not fix the issue. Also the issue is only with 0.png file name all other filenames worked

**Comment by Hixie** [comment] 2019-12-04 19:12
@jonahwilliams why would it work for `1.png` but not `0.png` in that case?

**Comment by Hixie** [comment] 2019-12-04 19:12
@gitboss if you could upload a zip file with the bare minimum required to reproduce this that would really help us track it down. Thanks in advance if you're able to do this.

**Comment by jonahwilliams** [comment] 2019-12-04 20:08
That is definitely surprising. I can see if it repros locally with those names. If it does I suspect something is wonky in the variant detection logic

**Comment by jonahwilliams** [comment] 2020-02-19 07:28
Its possible this was due to a URI encoding issue with assets that was fixed recently by dnfield. At any rate, at ToT I can't reproduce the issue.

@gitboss would you be willing to switch to a dev branch temporarily to verify it is fixed?

**Comment by jmagman** [comment] 2020-03-11 00:52
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-03-11 00:52 UTC
Labels: a: assets, tool, waiting for customer response
