### ISSUE TITLE
[WEB] [flutter_service_worker] Can't access directly page by url

### ISSUE THREAD

**Issue by mminhlequang** [flutter/flutter#119998] opened 2023-02-04 12:27 UTC
Problem is can't load flutter_service_worker/main.js

So the problem is normally app will open with the root path example: https://domain.com
so to load flutter_service_worker:
https://domain/flutter_service_worker.js?v=78597701 => This ok because it's the default

but if we have a page example: https://domain.com/contact_us/
so to load flutter_service_worker:
https://domain/contact_us/flutter_service_worker.js?v=78597701 => This throw 404

NOTE: I also `Configuring the URL strategy`
https://docs.flutter.dev/development/ui/navigation/url-strategies

**Comment by mminhlequang** [comment] 2023-02-04 12:35
![image](https://user-images.githubusercontent.com/46816270/216767958-ca08c50e-5a5b-480b-9c5b-2d78abf5ceb0.png)
I think here must return only domain

**Comment by cdhermann** [comment] 2023-02-05 07:13
same here. The service worker isn't loaded from base-href. It seems to be loaded from the actual path.

**Comment by shammill** [comment] 2023-02-06 05:10
We are also having a problem since upgrading to Flutter 3.7.0.

Assuming the following base ref:   ```<base href="/apps/my_app">```
Navigating to `domain.com/apps/my_app/` works, but `domain.com/apps/my_app` does not.

Loading the flutter.js is fine, but loading the service worker and main.js breaks as it trims off some of the path:
```https://domain.com/apps/flutter_service_worker.js?v=1509226287```

**Comment by darshankawar** [comment] 2023-02-06 07:17
@mminhlequang 
A related issue was fixed and merged recently that maybe helpful in your case : https://github.com/flutter/flutter/pull/118684, so can you try to switch to latest master and run your scenario again to see if the behavior persists or not ?

**Comment by mminhlequang** [comment] 2023-02-06 07:29
@darshankawar thank you for your answer, I will check it now

**Comment by mminhlequang** [comment] 2023-02-06 07:49
yes so this will fix on the next flutter version release on the stable channel, right?

**Closed** 2023-02-06 07:53 UTC
Labels: in triage

**Comment by ditman** [comment] 2023-02-08 02:36
We're cherry-picking the fix, [here](https://github.com/flutter/flutter/issues/120197). In the meantime, you can also configure the main.dart.js and flutter_service_worker.js URLs as described in this comment:

* https://github.com/flutter/flutter/issues/116360#issuecomment-1364181861

```js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: "/YOUR_APP_BASE/main.dart.js",
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
          serviceWorkerUrl: "/YOUR_APP_BASE/flutter_service_worker.js?v=",
        },
   ...
```

That way the files will be requested from the appropriate URL, rather than the relative URLs that are being used now.

**Comment by mminhlequang** [comment] 2023-02-08 12:07
> We're cherry-picking the fix, [here](https://github.com/flutter/flutter/issues/120197). In the meantime, you can also configure the main.dart.js and flutter_service_worker.js URLs as described in this comment:
> 
> * [[web] PathUrlStrategy doesn't work with nested paths #116360 (comment)](https://github.com/flutter/flutter/issues/116360#issuecomment-1364181861)
> 
> ```js
>       _flutter.loader.loadEntrypoint({
>         entrypointUrl: "/YOUR_APP_BASE/main.dart.js",
>         serviceWorker: {
>           serviceWorkerVersion: serviceWorkerVersion,
>           serviceWorkerUrl: "/YOUR_APP_BASE/flutter_service_worker.js?v=",
>         },
>    ...
> ```
> 
> That way the files will be requested from the appropriate URL, rather than the relative URLs that are being used now.

thank you

**Comment by mdebbar** [comment] 2023-02-08 20:51
Duplicate of https://github.com/flutter/flutter/issues/116360

**Comment by mminhlequang** [comment] 2023-02-24 07:48
`<script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: window.location.origin + "/main.dart.js?v=1.0.89",
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
          serviceWorkerUrl: window.location.origin + "/flutter_service_worker.js?v=",
        },
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
`
Seem good with simple solution: window.location.origin
