### ISSUE TITLE
Lag / microstutter on certain OnePlus devices

### ISSUE THREAD

**Issue by dasmikko** [flutter/flutter#24782] opened 2018-11-27 14:37 UTC
I'm getting a lot of lag/microstutter on my OnePlus 5T in all flutter apps.

Even in the official flutter gallery app. 

Other apps this doesn't happen, and I've tried to restart my phone and nothing really helps.

Video from flutter gallery app:
[https://my.mixtape.moe/yisdcw.mp4](https://my.mixtape.moe/yisdcw.mp4)

Video from Reddit sync app:

[https://my.mixtape.moe/ljcmsc.mp4](https://my.mixtape.moe/ljcmsc.mp4)

**Comment by dasmikko** [comment] 2018-11-30 07:39
I forgot to state in the OP, that I'm running the latest stock ROM and is not rooted. Everything is 100% stock.

**Comment by davidmartos96** [comment] 2018-12-03 10:34
Try to run it with `flutter run --profile`

**Comment by dasmikko** [comment] 2018-12-03 13:49
That seemed to make my own apps run a whole lot more smooth!

But, how come the gallery app still has microstutters?

**Comment by dasmikko** [comment] 2018-12-06 07:53
After some more testing, listviews still stutter with `--profile` on

**Comment by dasmikko** [comment] 2019-01-23 09:56
OnePlus has release the update 9.0.3, which might have fixed the microstutter issue.

This still needs more testing, but looks promising!

**Comment by dasmikko** [comment] 2019-01-31 14:23
Still an issue, sadly.

**Comment by liyuqian** [comment] 2019-02-05 23:31
We don't have a OnePlus 5T in our lab to reproduce your issue so can you please provide us a trace of microstutter?

Specifically, you can capture a trace with
1. `flutter run --profile --trace-skia`, 
2. follow the link to open observatory, 
3. click timeline, 
4. select "All", 
5. scroll your app until a lag appears, 
6. click "refresh" and "save" in the observatory timeline web page, and attach the saved json file here.

**Comment by dasmikko** [comment] 2019-02-06 08:38
Sure.

Just rename the file to .json, as Github wouldn't allow .json files.

[dart-timeline-2019-1-6.txt](https://github.com/flutter/flutter/files/2835436/dart-timeline-2019-1-6.txt)

**Comment by dasmikko** [comment] 2019-02-06 09:49
Let me know if you need more.

**Comment by liyuqian** [comment] 2019-02-06 18:23
There seems to be a jank/missed frame around 350ms. @dasmikko Can you please confirm that it's the case?

From the trace, all GPU raster times and UI build times are less than 16ms. The only suspicious behavior is a Dart Idle GC right before 350ms in the middle of two animated frames. That shouldn't happen since we're still animating. After the GC, there's a long "Frame Request Pending" (18ms) which seems to have blocked both the GPU thread and the UI thread.

CC @rmacnak-google who may have more knowledge about the Dart Idle GC.

**Comment by dasmikko** [comment] 2019-02-06 18:43
@liyuqian That is correct with the frame at 350ms.

What you are saying sounds like something that could make the app microstutter.

**Comment by UnoDeTantos** [comment] 2019-07-18 15:15
@liyuqian same problem with a Oneplus 3T (stock  9.0.4), it's more noticeable when slowing down

Same scroll with a Nexus 5 is buttery smooth.

[dart-timeline-2019-6-18.json.zip](https://github.com/flutter/flutter/files/3407191/dart-timeline-2019-6-18.json.zip)

**Comment by liyuqian** [comment] 2019-07-22 17:39
@UnoDeTantos : your trace seems to be a little different from the one that dasmikko posted. Yours doesn't have a GC in the middle of an animation, and it seems that the GPU thread is running out of 16ms budget in some frames.

Is your scroll issue also happening inside flutter_gallery app?

Can you please also provide us:
1. Your flutter version (from `flutter doctor -v`). If possible, please switch flutter to master channel and redo your test again since Flutter is constantly fixing bugs and improving performance.
2. Record a video of the performance issue using another phone (iPhone slo-mo is preferred) so we can have an intuitive understanding of what happened. Don’t use "adb screenrecord", as that affects the performance of the profile run.
3. Enable performance overlay (by pressing 'P' during `flutter run --profile`) during the video recording so we know which frames may be causing the problem.

**Comment by UnoDeTantos** [comment] 2019-07-22 18:39
@liyuqian, my other phone to test is the Nexus 5, and well... I think you are not going to see anything if I record the video with that phone. If you want the video anyway, just say it :)

The issue happens (or is more noticeable) when the scroll is slowing down, in that moment some micro sutters appears until stops. Same problem occurs with flutter_galley (not as noticeable) but it's more complicated to test because scrolls are to short. With the nexus 5 no problem at all, just perfect. 

About, flutter doctor, switch to master an redo:
```
[✓] Flutter (Channel master, v1.8.2-pre.135, on Mac OS X 10.14.5 18F132, locale es-ES)
    • Flutter version 1.8.2-pre.135 at /Users/Tito/development/flutter
    • Framework revision 11d3d45b6b (41 minutes ago), 2019-07-22 10:23:12 -0700
    • Engine revision 849fe73170
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 a089199b93)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Tito/library/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/Tito/library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (3 available)
    • ONEPLUS A3003 • dc136996 • android-arm64  • Android 9 (API 28)
    • macOS         • macOS    • darwin-x64     • Mac OS X 10.14.5 18F132
    • Chrome        • chrome   • web-javascript • Google Chrome 75.0.3770.142 


• No issues found!
```

Test again:
[dart-timeline-2019-6-22.json.zip](https://github.com/flutter/flutter/files/3418737/dart-timeline-2019-6-22.json.zip)

**Comment by liyuqian** [comment] 2019-07-22 19:54
@UnoDeTantos : I meant to use your Nexus 5 as a camera to record the micro stutters on your OnePlus 3T with performance overlay turned on :-)

**Comment by UnoDeTantos** [comment] 2019-07-23 08:53
@liyuqian, yes, I understood you, but I didn't think the video had the necessary quality 😅 

Video:
https://streamable.com/9f0o1

**Comment by UnoDeTantos** [comment] 2019-07-23 10:00
I leave here the row structure in case it helps:

```
Card > InkWell > Padding > Column [

  // CHANNEL ROW
  SizedBox(height) > Row [
    Container(width, center) > CircularAvatar > CachedNetworkImageProvider,
    Expanded > Text
    IconButton
  ],

  // PROGRESS
  Container(height, padding) > LinearProgressIndicator,

  // EPG ROW
  "StreamValueBuilder" > Container(height) > Row [
    Expanded > Column [
      Row [
        SizedBox(width) > Text(center),
        Expanded > Text
      ],
      Row [
        SizedBox(width) > Text(center),
        Expanded > Text
      ]
    ],
    IconButton
  ]

]
```

`StreamValueBuilder` is something I am testing to fix the "double tic" behavior with RxDart `BehaviorSubject`. The problem persist with and without "EPG ROW". Nexus 5 is buttery smooth in any way.

I leave here the code for `StreamValueBuilder`:

```dart
typedef StreamValueBuilderListener<T> = void Function(AsyncSnapshot<T> oldValue, AsyncSnapshot<T>newValue);
class StreamValueBuilder<T> extends StreamBuilder<T> {
  final StreamValueBuilderListener<T> onChange;
  StreamValueBuilder({
    Key key,
    @required Stream<T> stream,
    T initialData,
    @required AsyncWidgetBuilder<T> builder,
    this.onChange,
    Equality compare = const DeepCollectionEquality()
  }) :
    assert( stream!=null ),
    assert( builder!=null ),
    super(
      key: key, 
      stream: stream is ValueObservable && (stream as ValueObservable).hasValue
        ? stream.distinct(compare.equals).skip(1)
        : stream.distinct(compare.equals),
      initialData: initialData ?? (stream is ValueObservable ? (stream as ValueObservable).value : null),
      builder: builder, 
    );

  @override
  AsyncSnapshot<T> initial() {
    final value = super.initial();
    onChange?.call(null,value);
    return value;
  }

  @override
  AsyncSnapshot<T> afterData(AsyncSnapshot<T> current, T data) {
    final newValue = super.afterData(current, data);
    onChange?.call(current,newValue);
    return newValue;
  }
}
```

**Comment by jckpn** [comment] 2019-07-31 01:13
I don't have a OnePlus myself to test this but I've had quite a few reports of my app stuttering on OnePlus devices (and LG, possibly related?). Most of everyone else says it runs buttery smooth, which is also how it appears on my Pixel 2 and Galaxy S10e.

**Comment by dasmikko** [comment] 2019-08-12 08:03
Did some testing this weekend, to see if it was the stock ROM from OnePlus only having the stutters.

So I flashed Lineage OS, on my OnePlus 5T and boom, all the lag/stutter are gone. I can scroll smoothly without issues.

So this seems to be an issue with the OnePlus ROMs.

**Comment by jckpn** [comment] 2019-08-14 15:52
Interesting, but there's still clearly an issue with the Flutter framework since OnePlus devices don't have this issue with native apps.

**Comment by dasmikko** [comment] 2019-08-14 16:31
That is true, though I should mention, that I would get some random slowdowns when running the Stock ROM, even in native apps. Only very briefly though.

**Comment by jckpn** [comment] 2019-09-08 19:45
Kinda sad to see this not being addressed by the team anymore :(

It's the #1 complaint on my Flutter app. All of the animations (including the 'fling' animations on scrollviews) have insane amounts of jank from videos I've seen.

**Comment by liyuqian** [comment] 2019-09-09 17:02
We hear you! We're purchasing a OnePlus 5T to further investigate this issue today :-)

**Comment by Feenposhleen** [comment] 2019-09-17 14:31
Just wanted to drop by and say that this also happens on my 6T. ListViews are stuttering a lot, especially when flinging. As someone mentioned, it seems especially bad when the scroll animation is easing out, just before it stops. I'm happy to provide any debug data you'd need, just ask!

**Comment by liyuqian** [comment] 2019-09-18 17:18
I wasn't able to reproduce any lag/microstutter using Flutter gallery's list view on a OnePlus 5T. Please see the recording below.

- [Recording](https://photos.app.goo.gl/MJYcxkZxk8MC7G9a8)
- Flutter version: 2f3515de31c0479cd09ad11cdc079281270405f4
- OnePlus 5T Model A5010
  - OxygenOS version 4.7.4
  - Android version 7.1.1
  - Kernel version 4.4.21-perf+
  - Build number ONEPLUS A5010_43_171206

@dasmikko : your video recording in https://github.com/flutter/flutter/issues/24782#issue-384824814 is no longer available. Can you please re-upload a recording with the tip-of-tree Flutter?

**Comment by dasmikko** [comment] 2019-09-18 18:54
@liyuqian : I sadly don't have the recording anymore. :( 

I can also see you are running an old version on the Oneplus 5T

The issue appeared after updating to android 9. Could you try updating the phone?

**Comment by Feenposhleen** [comment] 2019-09-19 12:36
Here is a recording of the Flutter Gallery stuttering on the 6T. It might be hard to see in the compressed web version, but if you download it it's visible.

Oxygen 9.0.16 (Android 9)
Build ONEPLUS A6013_41_190801

https://drive.google.com/file/d/10JIqFFEcIQC_Tzs5lll5JiU333yAWAMW/view?usp=sharing

**Comment by jckpn** [comment] 2019-09-21 18:27
@Feenposhleen That looks better than my brief testing with my friend's OnePlus 3T. Flutter animations ran at like 5 FPS on his phone, it looks awful

**Comment by Feenposhleen** [comment] 2019-09-21 19:52
@jckpn Yeah, I've also have much bigger frame drops than that on apps I've worked on (that runs like butter on my much older HTC 10). Unfortunately I can't share recordings from those.

I guess it also gets less noticeable on newer hardware. Still very noticeable and definitely not native-feeling though.

**Comment by liyuqian** [comment] 2019-09-23 17:40
@dasmikko : I've upgraded the OnePlus 5T to Android 9 (OxygenOS version 9.0.8), and the [recording](https://photos.app.goo.gl/XiP5z8ZWo1ge92J46) still doesn't show any stutter...

@Feenposhleen , @jckpn : I don't see any obvious problem in your recording on 6T. Can you please enable the performance overlay, and probably provide us a trace and a sample app for reproducing the issue?

Here's more info about how to help us better investigate performance issues:

> 1.  Please tell us exactly how to reproduce the problem you are running into.
> 
> 2.  Please attach a small application (ideally just one main.dart file) that
>      reproduces the problem. You could use https://gist.github.com/ for this.
> 
> 3.  Switch flutter to master channel and run this app on a physical device
>      using profile mode with Skia tracing enabled, as follows:
>        flutter channel master
>        flutter run --profile --trace-skia
>      Then press ‘P’ to enable the performance overlay.
> 
>      The bleeding edge master channel is encouraged here because Flutter is
>      constantly fixing bugs and improving its performance. Your problem in an
>      older Flutter version may have already been solved in the master channel.
> 
> 4.  Record a video of the performance issue using another phone so we
>      can have an intuitive understanding of what happened. Don’t use
>      "adb screenrecord", as that affects the performance of the profile run.
> 
> 5.  Open Observatory and save a timeline trace of the performance issue
>      so we know which functions might be causing it. See "How to Collect
>      and Read Timeline Traces" on this blog post:
>        https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af03#a499

**Comment by Feenposhleen** [comment] 2019-09-23 20:33
Okay, so I created a stupid thing to reproduce the issue.
https://gist.github.com/Feenposhleen/ecb19d962343f7ea35275af76f6690d6

Recorded me running this on latest master. Hopefully you can see that something is up, atleast from the graphs. Frame processing time suddenly spikes when the scroll is about to end. A wild guess would be that something is causing GC or other cleanup to take place prematurely.

I ran the same test on the HTC10 for reference, and while it's weaker, it still shows a much more stable graph.

HTC10: https://drive.google.com/open?id=111gfG5T5R7jUmu2uBeqtyDmYVu30bTIJ
OnePlus 6T:  https://drive.google.com/open?id=1-hJKBkDpgv0i117YswZ57R9k_PCj5ABh

I couldn't get the Observatory trace to download, saying I had an empty timeline when it clearly was not. Maybe some issue with stuff in master perhaps. Could try on stable channel if that would be useful.

**Comment by UnoDeTantos** [comment] 2019-09-24 11:40
@liyuqian the performance is way better now but still some hiccups here a there... (Oneplus 3T)

**Videos:**
- Before: https://streamable.com/9f0o1
- Now: https://streamable.com/x9qjy

**Flutter doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.6-pre.39, on Mac OS X 10.14.6 18G95, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)
```

**Gist:**
https://gist.github.com/UnoDeTantos/64837d58357ab539a7580b10bd4ce89c

**Video testing the gist:**
https://streamable.com/3i8e9

**How test**
Scroll down a lot and then up slowly.

**Comment by Feenposhleen** [comment] 2019-10-23 11:23
@liyuqian Any updates on this?

**Comment by liyuqian** [comment] 2019-10-24 22:55
Oops, this slipped from my radar. Reopen this issue and get back to work on it.

**Comment by zemanux** [comment] 2019-12-13 16:36
I had this issue for a while on my OnePlus 5T with Flutter Gallery and other. I didn't made any factory reset since I bought it on december 2017. 
This morning, I made a factory reset and the problem disappeared !

**Comment by dasmikko** [comment] 2019-12-16 09:19
> I had this issue for a while on my OnePlus 5T with Flutter Gallery and other. I didn't made any factory reset since I bought it on december 2017.
> This morning, I made a factory reset and the problem disappeared !

After 3 days, is it still smooth?

I had also tried reflashing a custom rom, and then back to stock, where the issue came back after using the phone for some time.

**Comment by zemanux** [comment] 2019-12-16 13:40
I just tested, it is still smooth.

**Comment by UnoDeTantos** [comment] 2019-12-16 20:10
Oneplus 3T here, the problem persists even with the factory reset

@liyuqian did you try my gist?

**Comment by liyuqian** [comment] 2019-12-17 21:14
@UnoDeTantos I just tried your gist and reproduced the issue on OnePlus 5T. Thank you very much for the gist! Attached are the traces I got on a OnePlus 5T [i24782-5t.json.zip][1] and a [Moto G4][2]. Here are summaries of my findings:

The root cause of the lag/microstutter seems to be the occasionally slow `AndroidContextGL::SwapBuffers` on 5T compared to an older device G4 with presumably weaker hardware:
- `5T average=1.543ms, max=5.421ms, p90=2.128ms`
- `G4 average=1.064ms, max=2.594ms, p90=1.374ms`

The slowness seems to be mainly caused by GPU driver blocking the CPU so this might be a GPU driver issue, or maybe Flutter/Skia doesn't have an optimal setting for that GPU. Below are their GPU info. CC @brianosman to see if there's any known issue with Adreno (TM) 540
- `5T GLES: Qualcomm, Adreno (TM) 540, OpenGL ES 3.2 V@331.0 (GIT@4c638fb, I557c585805) (Date:10/06/18)`
- `G4 GLES: Qualcomm, Adreno (TM) 405, OpenGL ES 3.2 V@145.0 (GIT@I8ee426a9a2)`

On the other hand, I also see GC `CollectNewGeneration` happening during the middle of the animation on the UI thread. But that's expected and shouldn't contribute to the stutter because:
1. The UI thread task never run out of the 16ms budget
2. Flutter intentionally calls the GC if the frame build time on the UI thread is tiny. If the build time is only 2ms and we have a 16ms budget, Flutter is going to allow GC to use the remaining time to free some memory.

[1]: https://github.com/flutter/flutter/files/3975438/i24782-5t.json.zip
[2]: https://github.com/flutter/flutter/files/3975439/i24782-G4.json.zip

**Comment by brianosman** [comment] 2019-12-17 21:30
I don't know of any issues with the 540 (that GPU is in quite a few phones, including the Pixel 2, where we test heavily).

**Comment by UnoDeTantos** [comment] 2019-12-18 11:56
Some recap...

Oneplus devices directly reported here:
3T => Adreno 530
5T => Adreno 540
6T => Adreno 630

@dasmikko: 5T with Lineage works perfect
@jckpn: Reports from Oneplus devices (and LG, possibly related?)

With this in hand, we can think that there is a problem in Oneplus ROM but, as @jckpn has said, I don't have this issue with apps other than flutter

**Comment by dasmikko** [comment] 2019-12-18 13:09
@UnoDeTantos I can also confirm that stock Rom with custom kernel also solves the issue.

**Comment by liyuqian** [comment] 2020-01-05 07:55
According to https://github.com/flutter/flutter/issues/24782#issuecomment-567024351, this issue seems to be caused by OS kernels in which Flutter doesn't have much control. Tentatively close this issue for now. Please feel free to reopen if there's something to be done in Flutter.

**Closed by liyuqian** 2020-01-05 07:55 UTC
Labels: e: device-specific, engine, severe: performance, team: gallery, ▣ platform-android
