### ISSUE TITLE
Exposed beyond app through Intent.getData()

### ISSUE THREAD

**Issue by TheOutrider** [flutter/flutter#79432] opened 2021-03-31 05:57 UTC
I'm using the package to open a downloaded image, which is working perfectly in android marshmellow versions and below.
but when i use the same code for Android N and above, it throws the error :

**[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, file:///storage/emulated/0/Android/data/com.example.myapp/files/myFile.png exposed beyond app through Intent.getData(), null, android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.example.myapp/files/myFile.png exposed beyond app through Intent.getData()**

If there is Something I am missing here, please let me know, and also notify if there might some changes required in the android _manifest.xml_ .

Thanks

**Comment by iapicca** [comment] 2021-03-31 07:40
@TheOutrider 
can you provide your `flutter doctor -v`, your `flutter run -v` and most importantly a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment] 2021-03-31 08:38
@TheOutrider 
It seems to be an issue from Native rather than Flutter. See this similar SO [question](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed) (808 upvotes )and corresponding [solution](https://stackoverflow.com/a/38858040) (1439 upvotes for accepted answer), so I think we don't need to say anything more :-)

**Comment by TheOutrider** [comment] 2021-03-31 08:41
> 
> 
> @TheOutrider
> It seems to be an issue from Native rather than Flutter. See this similar SO [question](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed) (808 upvotes )and corresponding [solution](https://stackoverflow.com/a/38858040) (1439 upvotes for accepted answer), so I think we don't need to say anything more :-)

Thanks for your review, i'll check out your references

**Comment by pedromassangocode** [comment] 2021-04-21 09:14
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:14 UTC
Labels: in triage, waiting for customer response
