### ISSUE TITLE
Failure to run simple app compiled to WASM with error about identityHashCode

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#148617] opened 2024-05-18 18:44 UTC
### Steps to reproduce

1. Clone https://github.com/Rexios80/rexios.dev
2. Checkout the branch `feature/wasm-support`
3. Run `flutter run --wasm` (must be on flutter master, or do it the hard way on stable)
4. See the error in the web debugger

### Expected results

No exception

### Actual results

The following error:
```console
Uncaught (in promise) CompileError: WebAssembly.compileStreaming(): Compiling function #1263:"identityHashCode" failed: type error in return[0] (expected i64, got (ref null 103)) @+1479968
```

### Code sample

https://github.com/Rexios80/rexios.dev

There isn't much there

### Logs

Web debugger:
```console
Uncaught (in promise) CompileError: WebAssembly.compileStreaming(): Compiling function #1263:"identityHashCode" failed: type error in return[0] (expected i64, got (ref null 103)) @+1479968
```

Nothing in the Flutter logs

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel main, 3.22.0-36.0.pre.49, on macOS 14.5 23F79 darwin-arm64,
    locale en-US)
    • Flutter version 3.22.0-36.0.pre.49 on channel main at
      /Users/rexios/repos/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f7012db828 (63 minutes ago), 2024-05-18 10:41:56 -0700
    • Engine revision 552a965b70
    • Dart version 3.5.0 (build 3.5.0-167.0.dev)
    • DevTools version 2.36.0-dev.10

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rexios/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio
      Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (4 available)
    • Aaron’s iPhone (mobile)         • 00008130-001C35CE3A20001C • ios
      • iOS 17.5 21F79
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 124.0.6367.208
    ! Error: Browsing on the local area network for Raj's Apple Vision Pro.
      Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac. (code -27)
    ! Error: Browsing on the local area network for Joe’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2024-05-20 10:25
Hi @Rexios80 
I checked this on a new Flutter project without any additional plugins/packages and I didn't see the issue. Steps I did (following docs on https://docs.flutter.dev/platform-integration/web/wasm):

1. Build with wasm: `flutter build web --wasm`
2. activate `dhttpd`: `flutter pub global activate dhttpd`
3. Hosting the web: `dhttpd '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin'`

I tried the same on your project but it built with a long error. Since your project is using many dependencies, please narrow it down to see if one of them may cause this. Thanks!

**Comment by Rexios80** [comment] 2024-05-20 17:14
I've narrowed it down to `pub_api_client`, but I'm not sure it's that package's fault either. There are no references to `identityHashCode` in that code base. There are other packages with weird issues as well:
- https://github.com/flyerhq/flutter_chat_ui/issues/596#issuecomment-2119160655

That package has perfectly valid code that is failing to compile to WASM. There isn't anything to work off of from either the Flutter debugger or the web dev tools besides that cryptic error without any other information.

**Comment by huycozy** [comment] 2024-05-21 04:50
>I've narrowed it down to pub_api_client, but I'm not sure it's that package's fault either. 

Does that mean the issue disappeared after you removed it from project? You can also check [Requires JS-interop to access browser and JS APIs](https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm) to filter out which packages haven't been migrated to support wasm compilation yet.

**Comment by Rexios80** [comment] 2024-05-21 05:04
If it was a web package migration issue wouldn't the app not even compile? This is a runtime error.

**Comment by huycozy** [comment] 2024-05-21 05:36
I will mark this as an issue with `flutter run --wasm` to get insights from others. Reproduced the error above `WebAssembly.compileStreaming()` on the latest master channel with given sample code.

<details>
<summary>flutter doctor -v</summary>

```bash
[!] Flutter (Channel master, 3.22.0-39.0.pre.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.0-39.0.pre.1 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 165e535474 (3 hours ago), 2024-05-20 16:52:15 -0700
    • Engine revision c2ef01f6f1
    • Dart version 3.5.0 (build 3.5.0-172.0.dev)
    • DevTools version 2.36.0-dev.10
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.61

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by osa1** [comment] 2024-05-22 13:30
> cc @mkustermann @osa1 do you recognize the issue with identityHashCode being miscompiled?

I think this is probably new, I can debug this.

> If it was a web package migration issue wouldn't the app not even compile? This is a runtime error.

This is a type error in the generated Wasm file, and type errors in the generated code are always a compiler bug, dart2wasm should never generate ill-typed Wasm. It happens in runtime because compilation of the generated Wasm is compiled in runtime.

We could actually catch these kinds of errors in compile time by validating the generated code right after generating it, in compile time. @mkustermann any thoughts on this?

**Comment by Rexios80** [comment] 2024-05-22 14:24
Should I make a separate issue for this one? https://github.com/flyerhq/flutter_chat_ui/issues/596

**Comment by Rexios80** [comment] 2024-05-22 15:04
I'm also having a bunch of issues with type casting with JSON deserialization. This code works without running on WASM. Are those issues I should report as well or are they expected?

**Comment by leoafarias** [comment] 2024-05-22 15:22
The issue seems to happen on version `3.22.0-42.0.pre.6`, but I was not able to replicate it on lastest stable `3.22.0`

I was able to create a reproducible example using the `dart_mappable` package.
https://github.com/leoafarias/reproducible_dart_mappable_wasm 

cc @osa1 @mraleph

**Comment by osa1** [comment] 2024-05-22 15:25
> Should I make a separate issue for this one? flyerhq/flutter_chat_ui#596

Yes, that's also a dart2wasm bug and a separate bug.
 
I think these should be reported in the SDK repo as they're not Flutter bugs.

> I'm also having a bunch of issues with type casting with JSON deserialization. This code works without running on WASM. Are those issues I should report as well or are they expected?

I can't tell without seeing the program and the output. When in doubt please just report.

> The issue seems to occur on version 3.22.0-42.0.pre.6, but I was not able to replicate it on the latest stable 3.22.0.

I wonder if this was fixed with https://github.com/dart-lang/sdk/commit/0299c05481c. Is this commit included in the fixed version?

**Comment by leoafarias** [comment] 2024-05-22 15:31
@osa1 Is there a commit with this change on flutter, and I can test it

**Comment by osa1** [comment] 2024-05-22 15:40
@leoafarias I don't know how the SDK dependency is updated in Flutter repo so I'm not sure.

Basically dart2wasm between https://github.com/dart-lang/sdk/commit/9f075b1fd33ef349af40cba0e451799499796de6 and https://github.com/dart-lang/sdk/commit/0299c05481c is buggy, so we should check if the buggy version uses dart2wasm between those two commits.

I can't see the tag 3.22.0-36.0.pre.49 in https://github.com/flutter/flutter/tags.. Where do I get that tag?

**Comment by leoafarias** [comment] 2024-05-22 16:11
That tag just comes from the latest on master.

This is the version of the Dart SDK, let me know if that helps?
Dart 3.5.0 (build 3.5.0-177.0.dev)

**Comment by leoafarias** [comment] 2024-05-22 16:16
@osa1 
This version does not work: https://github.com/flutter/engine/pull/52970

This version works: https://github.com/flutter/engine/pull/52625

At least based on my tests

**Comment by Rexios80** [comment] 2024-05-22 17:59
I do actually get the same error at compile time on Flutter master:
[log.txt](https://github.com/flutter/flutter/files/15407031/log.txt)

**Comment by osa1** [comment] 2024-05-23 08:54
I found the bug, but I don't understand why it happens.

Basically in this program `Object.hashCode` somehow returns a boxed int, instead of unboxed:

```
  (func $Object.hashCode (;1268;) (param $var0 (ref $#Top)) (result (ref null $_BoxedInt))
    (local $var1 i64)
    local.get $var0
    call $Object._objectHashCode
    local.set $var1
    i32.const 5
    local.get $var1
    struct.new $_BoxedInt               ;; <----- Why box here??
    return
    ref.null none)
```

And `Object.identityHashCode` code generator assumes that it will return unboxed.

This can be easily fixed but I'd like to understand why `Object.hashCode` returns boxed first. Since `int` can't be subtyped, and all overrides of `hashCode` will return `int`, I would expect `Object.identityHashCode` to return unboxed.

**Comment by osa1** [comment] 2024-05-23 09:53
This seems to be a TFA bug. In this method:

```
    method hashValue(covariant-by-class final map3::MapperBase::T value, [final map2::MapperContainer? container = #C2]) → core::int {
      try {
        final map8::MappingContext context = new map8::MappingContext::•(container: container, args: () → core::List<core::Type> => typ12::TypePlus|get#args(value.{core::Object::runtimeType}{core::Type}).{core::Iterable::map}<core::Type>((final core::Type t) → core::Type => t =={core::Type::==}{(core::Object) → core::bool} #C99088 ?{core::Type} #C99083 : t){((core::Type) → core::Type) → core::Iterable<core::Type>}.{core::Iterable::toList}(){({growable: core::bool}) → core::List<core::Type>});
        return this.{map3::MapperBase::hash}(value, context){(map3::MapperBase::T, map8::MappingContext) → core::int};
      }
      on core::Object catch(final core::Object e, final core::StackTrace stacktrace) {
        core::Error::throwWithStackTrace(map4::MapperException::chain(#C99098, "[${value}]", e), stacktrace);
        e;
        stacktrace;
      }
    }
```

which I think is coming from:

https://github.com/schultek/dart_mappable/blob/4777e79cdc99e15730d18990e1d774edc0064b0a/packages/dart_mappable/lib/src/mappers/mapper_mixins.dart#L18

TFA infers the return type as `int?`, even though the Dart type is `int`:

```
    [@vm.inferred-return-type.metadata=dart.core::_BoxedInt?]
    [@vm.procedure-attributes.metadata=methodOrSetterCalledDynamically:false,getterCalledDynamically:false,hasThisUses:false,hasTearOffUses:false,methodOrSetterSelectorId:12475,getterSelectorId:12476]
    method hashValue([@vm.inferred-type.metadata=!] [@vm.inferred-arg-type.metadata=!] covariant-by-class final map2::MapperBase::T value, [[@vm.inferred-arg-type.metadata=library package:dart_mappable/src/mapper_container.dart::_MapperContainerBase?] final map::MapperContainer? container = #C43]) → core::int { ... }
```

@alexmarkov do you already know what the issue may be here or do you need a smaller repro? We tried to minimize this for a while, I can try more if you need a smaller repro.

**Comment by osa1** [comment] 2024-05-24 06:54
This should be fixed by https://github.com/dart-lang/sdk/commit/345b4371798e3d035737355421c4d69273b07e52.

**Comment by alexmarkov** [comment] 2024-05-24 14:24
The fix rolled into Flutter in b3d8053f0491c9028e1ab90695fcf859d5afbf91.

**Closed by alexmarkov** 2024-05-24 14:24 UTC
Labels: platform-web, has reproducible steps, e: wasm, team-web, found in release: 3.22

**Comment by Rexios80** [comment] 2024-05-24 14:44
@alexmarkov Will this be included in the next hotfix?

**Comment by alexmarkov** [comment] 2024-05-24 19:04
Cherry-pick request for beta branch: https://github.com/dart-lang/sdk/issues/55837. Please follow that issue for updates.

@Rexios80 Do you also need the fix in stable?

**Comment by Rexios80** [comment] 2024-05-28 13:40
@alexmarkov I would think any WASM compilation bug fixes should be in stable

**Comment by alexmarkov** [comment] 2024-06-03 14:58
As per https://github.com/dart-lang/sdk/issues/55837#issuecomment-2137113947, stable branch is likely unaffected.

@Rexios80 @osa1 Can you reproduce the bug on stable and verify if the fix for stable branch is needed or not?

**Comment by mkustermann** [comment] 2024-06-10 10:48
> /cc @mkustermann can we make a call if this needs to be cherry picked?

See my comment on https://github.com/dart-lang/sdk/issues/55837#issuecomment-2137113947.  The stable branch was cut already in march, way before we used this information in dart2wasm. So there's no need to cherry-pick it I believe.

**Comment by Rexios80** [comment] 2024-06-10 12:20
I can confirm I no longer see the `identityHashCode` issue on stable, but no longer allowing imports of FFI broke other packages so I'll have to deal with that

**Comment by mkustermann** [comment] 2024-06-10 14:34
> I can confirm I no longer see the identityHashCode issue on stable, but no longer allowing imports of FFI broke other packages so I'll have to deal with that

This may be due to conditional imports being incorrectly evaluated, tracked here https://github.com/flutter/flutter/issues/149984

**Comment by Rexios80** [comment] 2024-06-10 14:58
I'm not sure there's a conditional import involved
Here is the issue I created in `flutter_svg`: https://github.com/dnfield/flutter_svg/issues/1076
Here is the file that imports `vector_graphics_compiler`: https://github.com/dnfield/flutter_svg/blob/2f7c8ca1a1c1aaedc37e77cf1560cbb0e00baa9a/packages/flutter_svg/lib/src/cache.dart#L2
Which is directly imported in `svg.dart`: https://github.com/dnfield/flutter_svg/blob/2f7c8ca1a1c1aaedc37e77cf1560cbb0e00baa9a/packages/flutter_svg/lib/svg.dart#L8

**Comment by mkustermann** [comment] 2024-06-11 12:27
> Here is the issue I created in flutter_svg: https://github.com/dnfield/flutter_svg/issues/1076

@Rexios80 The `package:vector_graphics_compiler` has conditional imports [here](https://github.com/dnfield/vector_graphics/blob/357db2575ebbf64280e792228af6724e3d9ef0e9/packages/vector_graphics_compiler/lib/src/svg/tessellator.dart#L7) and [here](https://github.com/dnfield/vector_graphics/blob/357db2575ebbf64280e792228af6724e3d9ef0e9/packages/vector_graphics_compiler/lib/src/svg/path_ops.dart#L7) that depend on `dart.library.ffi`.


The fix for https://github.com/dart-lang/sdk/issues/55948 landed and will make it upstream in coming days into flutter main channel.
