### ISSUE TITLE
`Windows tool_integration_tests_1_6` flake for "allows overriding the directory for code size files"

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#125512] opened 2023-04-25 20:37 UTC
Logs found at: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_1_6/6857/overview

```
07:56 +26 ~2 -1: test/integration.shard/analyze_size_test.dart: --analyze-size allows overriding the directory for code size files [E]
  Expected: <0>
    Actual: <1>
  
  package:matcher                                      expect
  test\integration.shard\analyze_size_test.dart 190:5  main.<fn>
```

Referenced in issue filed by bot: https://github.com/flutter/flutter/issues/125116

Link to the builder: https://ci.chromium.org/p/flutter/builders/prod/Windows%20tool_integration_tests_1_6

**Comment by eliasyishak** [comment] 2023-04-25 20:38
Another example of the same test failing for this builder: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_1_6/6787/overview

**Comment by christopherfujino** [comment] 2023-04-25 21:21
Looks like `<1>` means the exit code, in that building the app failed. Can we update the test to show the stdout and stderr when that line fails? https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/analyze_size_test.dart#L190

**Comment by christopherfujino** [comment] 2023-04-25 21:22
There's a handy test helper `printOnFailure` which will only print if the current test eventually fails: https://pub.dev/documentation/test_api/latest/test_api.scaffolding/printOnFailure.html

**Comment by christopherfujino** [comment] 2023-05-02 20:11
cc @eliasyishak

**Comment by eliasyishak** [comment] 2023-05-03 14:52
Closing issue, PR: https://github.com/flutter/flutter/pull/125910 has added logging to this test incase it fails again

**Comment by eliasyishak** [comment] 2023-05-04 16:40
Re-opening, we should probably only close this once we have identified the cause of the flake

**Comment by eliasyishak** [comment] 2023-05-04 16:43
With our updates from PR #125910, we can now observe the following output from the `printOnFailure` calls

```
07:10 +23 ~2 -1: test/integration.shard/analyze_size_test.dart: --analyze-size allows overriding the directory for code size files [E]
  Expected: <0>
    Actual: <1>
  
  package:matcher                                      expect
  test\integration.shard\analyze_size_test.dart 204:5  main.<fn>
  
workingDirectory: C:\b\s\w\ir\x\w\flutter\examples\hello_world

command:
C:\b\s\w\ir\x\w\flutter\bin\flutter build apk --analyze-size --code-size-directory=C:\b\s\w\ir\x\t\flutter_size_test.2b8000db --target-platform=android-arm64 --release

stdout:
Downloading android-arm-profile/windows-x64 tools...               601ms
Downloading android-arm-release/windows-x64 tools...               224ms
Downloading android-arm64-profile/windows-x64 tools...             256ms
Downloading android-arm64-release/windows-x64 tools...             229ms
Downloading android-x64-profile/windows-x64 tools...               226ms
Downloading android-x64-release/windows-x64 tools...               222ms

Running Gradle task 'assembleRelease'...                        
Checking the license for package Android SDK Build-Tools 30.0.3 in C:\b\s\w\ir\cache\android\sdk\licenses
License for package Android SDK Build-Tools 30.0.3 accepted.
Preparing "Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)".
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" ready.
Installing Android SDK Build-Tools 30.0.3 in C:\b\s\w\ir\cache\android\sdk\build-tools\30.0.3
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
Running Gradle task 'assembleRelease'...                          157.3s

stderr:
Dart snapshot generator failed with exit code -1073740940
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -1073740940


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\b\s\w\ir\x\w\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 2m 36s
Gradle task assembleRelease failed with exit code 1
```

**Comment by christopherfujino** [comment] 2023-05-04 20:27
This is great info. I still think we will need more before we share the dart vm team. @eliasyishak can you add the `--verbose` flag to our flutter tool invocations for these tests?

**Comment by eliasyishak** [comment] 2023-05-11 15:46
Looks like we have some logging coming out for this build on a flake

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_1_6/7248/overview

**Comment by christopherfujino** [comment] 2023-05-12 20:43
> Looks like we have some logging coming out for this build on a flake
> 
> https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_1_6/7248/overview

I don't see the crash from https://github.com/flutter/flutter/issues/125512#issuecomment-1535065136 in this log.

**Comment by eliasyishak** [comment] 2023-05-12 21:04
If you search for "stdout:" in the logs, the first match is one of our tests. There seem to be more test files failing in this one builder run, but the stack trace can be seen for one of ours too

**Comment by christopherfujino** [comment] 2023-05-12 22:05
> If you search for "stdout:" in the logs, the first match is one of our tests. There seem to be more test files failing in this one builder run, but the stack trace can be seen for one of ours too

It looks to me like the root cause of that failure was:

```
[        ] Execution failed for task ':app:packageRelease'.
[        ] > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
[        ]    > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "C:\Users\chrome-bot\.android\debug.keystore": Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available
```

While it looks (to me) like the root cause of https://github.com/flutter/flutter/issues/125512#issuecomment-1535065136 was:

```
Dart snapshot generator failed with exit code -1073740940
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -1073740940
```

**Comment by christopherfujino** [comment] 2023-06-20 20:47
Closing this as we updated the test to use `ProcessResultMatcher`. If this test flakes again, the flaky issue bot will re-open and we should have better test failure logs.

**Closed by christopherfujino** 2023-06-20 20:47 UTC
Labels: tool, P3
