### ISSUE TITLE
Flutter Internal Problem Compiler cannot run without a CompilerContext

### ISSUE THREAD

**Issue by aswinmohanme** [flutter/flutter#24964] opened 2018-12-05 03:08 UTC
When compiling my project I got the following error and the app would not run
```
[  +27 ms] executing: [/home/aswinmohanme/Flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/aswinmohanme/Flutter/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/home/aswinmohanme/Flutter/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/home/aswinmohanme/Flutter/flutter/] git log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/home/aswinmohanme/Flutter/flutter/] git log -n 1 --pretty=format:%ar
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 days ago
[   +3 ms] executing: [/home/aswinmohanme/Flutter/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[  +82 ms] executing: /home/aswinmohanme/Android/Sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /home/aswinmohanme/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           79c0f009               device usb:3-3 product:kenzo model:Redmi_Note_3 device:kenzo transport_id:8
[ +174 ms] Found plugin shared_preferences at /home/aswinmohanme/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[  +78 ms] Found plugin shared_preferences at /home/aswinmohanme/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[  +44 ms] /home/aswinmohanme/Android/Sdk/platform-tools/adb -s 79c0f009 shell getprop
[ +116 ms] ro.hardware = qcom
[ +176 ms] "flutter run" took 624ms.

Oops; flutter has exited unexpectedly: "Internal problem: Compiler cannot run without a compiler context.
Tip: Are calls to the compiler wrapped in CompilerContext.runInContext?".
Sending crash report to Google.

```
After further digging in I found that the double semicolon in the second import statement was the problem.

```dart
import 'package:flutter/material.dart';
import '../widgets/datetime_header.dart';;
import 'package:lessphone/widgets/page_scaffold.dart';

class TasksScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PageScaffold(
      content: <Widget>[
        DateTimeHeader(),
      ],
    );
  }
}

```
 Shouldn't the error message be more helpful ?

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/aswinmohanme/Flutter/flutter
    • Framework revision 5391447fae (5 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/aswinmohanme/Android/Sdk
    • Android NDK at /home/aswinmohanme/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/aswinmohanme/Android/Sdk
    • Java binary at: /home/aswinmohanme/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/aswinmohanme/Android/android-studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Redmi Note 3 • 79c0f009 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!

```

**Comment by zoechi** [comment] 2018-12-05 07:31
Please add the output of `flutter doctor -v`.

**Comment by aswinmohanme** [comment] 2018-12-16 14:37
I am still getting the same error while switching to `master`.

I ran `flutter channel master` and then `flutter upgrade`, is there something I'm missing ?

**Comment by zoechi** [comment] 2018-12-16 14:51
Not sure. Perhaps restart the IDE.

**Comment by aswinmohanme** [comment] 2018-12-16 16:54
I'm still getting  the same error after I restart the IDE, I'm trying with a new empty project too
```
import 'package:flutter/material.dart';;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by aswinmohanme** [comment] 2018-12-17 11:39
```
[✓] Flutter (Channel master, v1.1.2-pre.38, on Linux, locale en_US.UTF-8)
    • Flutter version 1.1.2-pre.38 at /home/aswinmohanme/Flutter/flutter
    • Framework revision 59bfab157e (2 days ago), 2018-12-15 13:29:54 -0800
    • Engine revision 101b27da7a
    • Dart version 2.2.0 (build 2.2.0-dev.1.0 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/aswinmohanme/Android/Sdk
    • Android NDK at /home/aswinmohanme/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/aswinmohanme/Android/Sdk
    • Java binary at: /home/aswinmohanme/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/aswinmohanme/Android/android-studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment] 2018-12-17 16:22
It might be worth checking your Flutter install is not corrupted https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by FlxAlbroscheit** [comment] 2018-12-18 11:13
`;import 'package:flutter/material.dart';`
throws the same kind of error. Removing the very first semicolon fixes the problem, flutter doctor does not report anything critical, version is 1.0.0

**Comment by zoechi** [comment] 2018-12-18 11:49
@FlxAlbroscheit the error is known for Flutter 1.0.0, but it was fixed in the meantime.
I can't reproduce with `master` channel anymore.

**Closed** 2018-12-24 19:09 UTC
Labels: dependency: dart, engine, severe: crash

**Comment by Guang1234567** [comment] 2019-01-04 08:14
flutter version 2.0

How to reappear? flutter is too sick!!

```dart
;import 'package:flutter/material.dart’;  //  add the ; at the head of import
```
throws the same kind of error. Removing the very first semicolon fixes the problem, flutter doctor does not report anything critical, version is 1.0.0

**Comment by Hitsaa** [comment] 2019-06-28 12:12
This may be caused by any syntax error in your code. Try to figure out. I also had syntax error by placing two semicolons during importing packages. Solved by correcting the syntax.
