### ISSUE TITLE
IOS - app won't build!

### ISSUE THREAD

**Issue by fipooo** [flutter/flutter#68008] opened 2020-10-13 09:45 UTC
Hi, I update Flutter yesterday and now the app don't run on IOS. On android, everything works fine, but on IOS it crashes errors as below.

<details> 
<summary>logs</summary> 

```bash
s/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/port.h:22:10: warning: double-quoted include "absl/base/attributes.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/attributes.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/attributes.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/port.h:23:10: warning: double-quoted include "absl/base/config.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/config.h"
             ^~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/config.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:62:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/port.h:23:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/config.h:66:10: warning: double-quoted include "absl/base/options.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/options.h"
             ^~~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/options.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/config.h:67:10: warning: double-quoted include "absl/base/policy_checks.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/policy_checks.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/policy_checks.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:62:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/port.h:24:10: warning: double-quoted include "absl/base/optimization.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/optimization.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/optimization.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:62:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/port.h:24:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/optimization.h:25:10: warning: double-quoted include "absl/base/config.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/config.h"
             ^~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/config.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:10: warning: double-quoted include "absl/strings/numbers.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/strings/numbers.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/strings/numbers.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:39:10: warning: double-quoted include "absl/base/config.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/config.h"
             ^~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/config.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:40:10: warning: double-quoted include "absl/base/internal/bits.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/internal/bits.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/internal/bits.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:40:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/internal/bits.h:23:10: warning: double-quoted include "absl/base/config.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/config.h"
             ^~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/config.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/internal/bits.h:37:10: warning: double-quoted include "absl/base/attributes.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/attributes.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/attributes.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:49:10: warning: double-quoted include "absl/base/macros.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/macros.h"
             ^~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/macros.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:49:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/macros.h:34:10: warning: double-quoted include "absl/base/attributes.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/attributes.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/attributes.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/macros.h:35:10: warning: double-quoted include "absl/base/optimization.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/optimization.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/optimization.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/base/macros.h:36:10: warning: double-quoted include "absl/base/port.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/port.h"
             ^~~~~~~~~~~~~~~~~~
             <absl/absl/base/port.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:50:10: warning: double-quoted include "absl/base/port.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/port.h"
             ^~~~~~~~~~~~~~~~~~
             <absl/absl/base/port.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:51:10: warning: double-quoted include "absl/numeric/int128.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/numeric/int128.h"
             ^~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/numeric/int128.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:51:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/numeric/int128.h:33:10: warning: double-quoted include "absl/base/config.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/config.h"
             ^~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/config.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/numeric/int128.h:34:10: warning: double-quoted include "absl/base/macros.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/macros.h"
             ^~~~~~~~~~~~~~~~~~~~
             <absl/absl/base/macros.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/numeric/int128.h:35:10: warning: double-quoted include "absl/base/port.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/base/port.h"
             ^~~~~~~~~~~~~~~~~~
             <absl/absl/base/port.h>
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/numeric/int128.h:1081:10: warning: double-quoted include "absl/numeric/int128_have_intrinsic.inc" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/numeric/int128_have_intrinsic.inc"  // IWYU pragma: export
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/numeric/int128_have_intrinsic.inc>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:52:10: warning: double-quoted include "absl/strings/string_view.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
    #include "absl/strings/string_view.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <absl/absl/strings/string_view.h>
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc:22:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/ios/Pods/FirebaseFirestore/Firestore/core/src/nanopb/pretty_printing.h:24:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/str_cat.h:63:
    In file included from /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/numbers.h:52:
    /Users/macbook/AndroidStudioProjects/gamenumber/build/ios/Debug-iphonesimulator/abseil/absl.framework/Headers/strings/string_view.h:39:10: warning: double-quoted include "absl/base/config.h" in framework header, expected angle-bracketed instead 
```

```
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebasePerformance' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Crashlytics' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flutter' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Fabric' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Firebase' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleAppMeasurement' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCoreDiagnosticsInterop' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseAuthInterop' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseAnalyticsInterop' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseAnalytics' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'abseil' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GTMSessionFetcher' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'PromisesObjC' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Protobuf' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'shared_preferences' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleToolboxForMac' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'BoringSSL-GRPC' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleDataTransport' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleUtilities' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCoreDiagnostics' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCore' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseInstallations' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseDatabase' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseABTesting' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseInstanceID' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseRemoteConfig' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseMessaging' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseFirestore' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'firebase_crashlytics' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'firebase_core' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'firebase_performance' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'firebase_messaging' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'firebase_database' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'firebase_admob' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'cloud_firestore' from project 'Pods')
                    
[+41770 ms] Could not build the application for the simulator.
[   +2 ms] Error launching application on iPhone 11 Pro Max.
[   +3 ms] "flutter run" took 291 077ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale pl-PL)
    • Flutter version 1.22.1 at /Users/macbook/Developer/flutter
    • Framework revision f30b7f4db9 (5 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 2302E079-1E6D-46D0-B3A9-3F1E693B6527 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

</details>

**Comment by Dominic12** [comment] 2020-10-13 10:04
Have you tried flutter clean?

**Comment by fipooo** [comment] 2020-10-13 10:10
@Dominic12 
Yes.

**Comment by TahaTesser** [comment] 2020-10-13 10:43
Hi @fipooo 
Have you updated firebase packages as well? 
Error seems to indicate Firebase Core related 
```
    3 warnings generated.
    3 warnings generated.
    3 warnings generated.
    ld: framework not found FirebaseCoreDiagnostics
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-13 10:43 UTC
