### ISSUE TITLE
Inconsistency detected by ld.so: ../elf/dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#67761] opened 2020-10-09 19:59 UTC
Linux web_tests is failing for my PR but it doesn't seem to be related to my PR:
https://github.com/flutter/flutter/pull/67585/checks?check_run_id=1223328474

Extract from https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867052161243417888/+/steps/run_test.dart_for_web_tests_shard_and_subshard_7_last/0/stdout:
```
04:40 +732 ~16: loading /b/s/w/ir/k/flutter/packages/flutter/test/gestures/debug_test.dart                                                                                                             
04:40 +732 ~16: /b/s/w/ir/k/flutter/packages/flutter/test/widgets/automatic_keep_alive_test.dart: AutomaticKeepAlive with keepAlive set to true before initState                                       
04:41 +732 ~16: /b/s/w/ir/k/flutter/packages/flutter/test/widgets/automatic_keep_alive_test.dart: AutomaticKeepAlive with keepAlive set to true before initState                                       
04:41 +733 ~16: loading /b/s/w/ir/k/flutter/packages/flutter/test/gestures/debug_test.dart                                                                                                             
04:41 +733 ~16: /b/s/w/ir/k/flutter/packages/flutter/test/widgets/automatic_keep_alive_test.dart: AutomaticKeepAlive with keepAlive set to true before initState and widget goes out of scope          
04:41 +734 ~16: loading /b/s/w/ir/k/flutter/packages/flutter/test/gestures/debug_test.dart                                                                                                             
04:41 +734 ~16: /b/s/w/ir/k/flutter/packages/flutter/test/widgets/automatic_keep_alive_test.dart: AutomaticKeepAlive with SliverKeepAliveWidget                                                        
04:41 +735 ~16: loading /b/s/w/ir/k/flutter/packages/flutter/test/gestures/debug_test.dart                                                                                                             [+3637 ms] Serving tests at http://localhost:42465/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A42465%2F66&debug=false
[ +106 ms] [CHROME]:Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[   +3 ms] [CHROME]:Inconsistency detected by ld.so: ../elf/dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!

04:41 +735 ~16 -1: loading /b/s/w/ir/k/flutter/packages/flutter/test/gestures/debug_test.dart [E]                                                                                                      
  Failed to load "/b/s/w/ir/k/flutter/packages/flutter/test/gestures/debug_test.dart":
  Unable to connect to Chrome debug port: 36201
   SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 45400
  package:flutter_tools/src/base/common.dart 14:3                throwToolExit
  package:flutter_tools/src/web/chrome.dart 309:9                ChromiumLauncher._connect
  ===== asynchronous gap ===========================
  dart:async/future.dart 280:46                                  new Future.error
  package:test_core/src/runner/loader.dart 238:26                Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
  package:test_core/src/runner/loader.dart                       Loader.loadFile.<fn>
  package:test_core/src/runner/load_suite.dart 97:31             new LoadSuite.<fn>.<fn>
  package:test_core/src/runner/load_suite.dart 107:8             new LoadSuite.<fn>
  package:test_api/src/backend/invoker.dart 231:15               Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 370:9                Invoker._onRun.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 150:7                Invoker.guard
  package:test_api/src/backend/invoker.dart 413:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 369:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 104:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 102:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 368:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 153:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
  

16:25 +735 ~16 -2: loading /b/s/w/ir/k/flutter/packages/flutter/test/material/typography_test.dart [E]                                                                                                 
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12      _RawReceivePortImpl._handleMessage
  

16:28 +735 ~16 -3: loading /b/s/w/ir/k/flutter/packages/flutter/test/widgets/basic_test.dart [E]                                                                                                       
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12      _RawReceivePortImpl._handleMessage
  

16:30 +735 ~16 -4: loading /b/s/w/ir/k/flutter/packages/flutter/test/widgets/routes_test.dart [E]                                                                                                      
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12      _RawReceivePortImpl._handleMessage
  
```

**Comment by Hixie** [comment] 2020-10-09 21:50
Might not be a flake, I saw it again when I retried that test. Can't see how I could have caused it though....
This is part of https://github.com/flutter/flutter/pull/67585

**Comment by yjbanov** [comment] 2023-10-10 20:18
Duplicate of https://github.com/flutter/flutter/issues/67454. Fixed by https://github.com/flutter/flutter/pull/67466.

**Closed by yjbanov** 2023-10-10 20:18 UTC
Labels: a: tests, platform-web, P2, c: flake, team-web, triaged-web
