### ISSUE TITLE
Request for Background service in flutter

### ISSUE THREAD

**Issue by mustafapc19** [flutter/flutter#67107] opened 2020-10-02 06:03 UTC
## Use case

I am currently building a chat app in flutter where I always want the device to be connected with my server when internet is available and also to push notifications and update the state of the app in general. But the issue is I dont think flutter has a background service equivalent. I think this a very prime requirement for many apps. Right now all I have seen is to use native code for each platform and link it with flutter 

## Proposal

My proposal is that, almost every platform, and I think chrome(for background webpage stuff but I am not sure) uses some sort of this service, so flutter should be providing this. I know this feature can be a pain to maintain and implement. 

I am a beginner to app development and flutter in general. So please pardon my mistakes.

**Comment by SANSKARJAIN2** [comment] 2020-10-02 07:14
HI @mustafapc19 ,
I think isolates would work for you.
I haven`t used them for this purpose but I think they have the ability to run in the background.
For more info, you could refer the link below:
https://flutter.dev/docs/development/packages-and-plugins/background-processes 

Hope it helps.

Thank you!

**Comment by TahaTesser** [comment] 2020-10-02 10:02
Hi @mustafapc19 
As mentioned above,t there are resources t help you achieve background processing
Also, check this issue for more details https://github.com/flutter/flutter/issues/64407 and follow the official documentation 

Closing, as a duplicate of https://github.com/flutter/flutter/issues/64407f. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-02 10:02 UTC
