### ISSUE TITLE
Webview Flutter(Android) cannot pick file(image) 

### ISSUE THREAD

**Issue by ayechanmaung47** [flutter/flutter#95669] opened 2021-12-22 11:18 UTC
Why android cannot? iOS works fine. I thought it was fixed in this new flutter version and plugin new version. We got in trouble.
Please fix it as fast as  dear team.

**Comment by danagbemava-nc** [comment] 2021-12-22 12:45
Duplicate of #27924.

Please do not intentionally file duplicates of existing issues. If you want an existing issue to gain more attention, kindly upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2021-12-22 12:45 UTC
Labels: in triage
