### ISSUE TITLE
Inconsistent try/finally behavour on flutter web

### ISSUE THREAD

**Issue by chutchatut** [flutter/flutter#145066] opened 2024-03-13 06:54 UTC
### Steps to reproduce

1. Build flutter web
2. View the console
3. Click the button

### Expected results

Console should print test1 and test3.

### Actual results

Console print test1, test2, and test3. Do note that flutter web produce expected results when ran using flutter run command.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return TextButton(
      onPressed: () {
        try {
          print('test1');
          assert(false);
          print('test2');
        } finally {
          print('test3');
        }
      },
      child: const Text('press me'),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

The result when run using flutter run:
![image](https://github.com/flutter/flutter/assets/33798875/8463ffc3-fd88-428f-a03a-f91f7b518f28)
The result when running from index.js produced from flutter build
![image](https://github.com/flutter/flutter/assets/33798875/06ca2f1d-9887-4152-8997-c3e7ca2c2217)
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on Debian GNU/Linux 12 (bookworm) 6.1.0-18-amd64, locale en_US.UTF-8)
    • Flutter version 3.19.3 on channel stable at /home/chutchatut/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (5 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/chutchatut/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 12 (bookworm) 6.1.0-18-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.111

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-03-13 09:53
This is working as intended and is not an issue with try/finally. `asserts` are only used in debug mode. They are not used in profile or release mode. 

Closing as this is an issue with your code and not a flutter issue. 

Thank you

**Closed by danagbemava-nc** 2024-03-13 09:53 UTC
Labels: in triage
