### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by taniksha-mfy** [flutter/flutter#93767] opened 2021-11-17 05:35 UTC
Flutter doctor command giving error: Bad cpu type in executable.
When installing on m1 chip and macos monterey. On installing rosetta it is showing rosetta 2 update not available.
Terminal command: sudo softwareupdate --install-rosetta --agree-to-license
Terminal output:
By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
If you do not agree, press CTRL-C and cancel this process immediately.
Rosetta 2 update is not available

Please help me, I'm stuck on it.

**Comment by darshankawar** [comment] 2021-11-17 08:36
Closing this as duplicate of https://github.com/flutter/flutter/issues/88012

**Closed by darshankawar** 2021-11-17 08:36 UTC
Labels: in triage

**Comment by taniksha-mfy** [comment] 2021-11-17 08:45
> Closing this as duplicate of #88012

There is no solution to this problem on #88012. Please help me with this. **Rosetta 2 update is not available**
