### ISSUE TITLE
Flutter engine crash (iOS) in customer:money

### ISSUE THREAD

**Issue by meiwin** [flutter/flutter#71249] opened 2020-11-26 05:09 UTC
Internal: b/174209758
Engine hash: `defa8be2b10650dad50dfee9324ed8d16eeec13f` (ios release arm 64)

Stack trace:

```
0x00000001059c5d5c(Flutter + 0x003fdd5c)		
0x00000001059c5c34(Flutter + 0x003fdc34)		
0x00000001059c5c34(Flutter + 0x003fdc34)		
0x00000001059c5534(Flutter + 0x003fd534)		
0x00000001059c5534(Flutter + 0x003fd534)		
0x00000001059aea60(Flutter + 0x003e6a60)		
0x00000001059ae6e8(Flutter + 0x003e66e8)		
0x0000000105aa6080(Flutter + 0x004de080)		
0x0000000105aa47bc(Flutter + 0x004dc7bc)		
0x0000000105aa43a0(Flutter + 0x004dc3a0)		
0x0000000105b264e0(Flutter + 0x0055e4e0)		
0x0000000105adec04(Flutter + 0x00516c04)		
0x00000001e04ccb38(libsystem_pthread.dylib + 0x00009b38)		_pthread_start
```

**Comment by mehmetf** [comment] 2020-11-26 06:08
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/71249#issue-751287523 internal engine#defa8be2b10650dad50dfee9324ed8d16eeec13f ios release arm64

**Comment by mehmetf** [comment] 2020-11-26 06:12
This seems like a different `security_context_macos` issue than https://github.com/flutter/flutter/issues/70350.

**Comment by mehmetf** [comment] 2020-11-26 06:19
Similar trace:

```
Thread 2  (id: 0x00006707) CRASHED [EXC_BAD_ACCESS / KERN_INVALID_ADDRESS @ 0x12fe01c6 ]Show exception record
0x00000001060a9498(Flutter + 0x003fd498)
0x00000001060a9534(Flutter + 0x003fd534)
0x00000001060a9534(Flutter + 0x003fd534)
0x0000000106087ca4(Flutter + 0x003dbca4)
0x0000000106086cb8(Flutter + 0x003dacb8)
0x00000001061898b8(Flutter + 0x004dd8b8)
0x00000001061896d8(Flutter + 0x004dd6d8)
```

**Comment by mehmetf** [comment] 2020-11-26 06:19
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/71249#issuecomment-734098758 internal engine#defa8be2b10650dad50dfee9324ed8d16eeec13f ios release arm64

**Comment by mraleph** [comment] 2020-11-26 09:51
Duplicate of #70800

**Closed** 2020-11-26 09:51 UTC
Labels: P3, customer: money (g3), engine, passed first triage, platform-ios, severe: crash
