### ISSUE TITLE
RefreshIndicator frame drop when calling http.get, CertificateVerificationCallback made jank

### ISSUE THREAD

**Issue by rpplusplus** [flutter/flutter#61967] opened 2020-07-21 17:40 UTC
## Details

1. I just used a http.get in RefreshIndicator onRefresh Method, like:

```dart
onRefresh: () async {
     await http.get("https://mydomain.com/");
})
```
and found that the indicator's animation droped frame, and I use --profile and dartdev tool  timeline got this :

![image](https://user-images.githubusercontent.com/1753142/88086966-c2285480-cbba-11ea-9ad5-66c4bd06d569.png)

when I expand the longest frame, found:
![image](https://user-images.githubusercontent.com/1753142/88087040-e2f0aa00-cbba-11ea-9e0a-5ff3e6a66436.png)

**Target Platform: iOS**

**Target OS version/browser:  iOS 13/14**

**Devices: iPhone 11 Pro**

## Logs

```
 info • This method overrides a method annotated as '@mustCallSuper' in 'AutomaticKeepAliveClientMixin', but doesn't invoke the overridden method • lib/order_list_page.dart:217:10 • must_call_super
   info • Cancel instances of dart.async.StreamSubscription • lib/record_list_page.dart:26:52 • cancel_subscriptions
   info • This method overrides a method annotated as '@mustCallSuper' in 'AutomaticKeepAliveClientMixin', but doesn't invoke the overridden method • lib/record_list_page.dart:71:10 • must_call_super
   info • Unused import: 'package:flutter/services.dart' • lib/search_page.dart:2:8 • unused_import
```

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-CN)
    • Flutter version 1.17.5 at /Users/txx/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/txx/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2


[✓] Connected device (2 available)
    • txx's iPhone               • 00008030-001C69CC1A30802E            • ios • iOS 14.0
    • iPhone SE (2nd generation) • 36EBBFC9-C428-48F0-904C-E98B88F28BE5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-07-22 14:32
I’m unable to reproduce the issue to pinpoint the cause The issue needs further investigation.
`CertificateVerificationCallback` isn't being located in longest frame

**Comment by chinmaygarde** [comment] 2020-07-27 18:28
This is a duplicate of https://github.com/dart-lang/sdk/issues/41519. A workaround is to process the HTTP request on another isolate.

**Comment by Hixie** [comment] 2020-08-04 23:03
Closing per last comment.

**Closed by Hixie** 2020-08-04 23:03 UTC
Labels: P4, dependency: dart, engine, framework, severe: performance, will need additional triage
