### ISSUE TITLE
Tapping an obscured text field for the first time won't change the keyboard type on iOS

### ISSUE THREAD

**Issue by njovy** [flutter/flutter#32346] opened 2019-05-08 21:46 UTC
## Steps to Reproduce

1. Tap an obscured text field.
2. Tap other text field that is not an obscured text.
3. The keyboard type doesn't change so users can only input password even a focused text field is not an obscured text field.

This behavior only happens if an obscured text field selected first. I have a screen for sign up that leads to this bug as a username is already filled after a verification step.

Attached is a result of this bug.
![bug](https://user-images.githubusercontent.com/1792070/57410818-cfac2580-7226-11e9-9b2a-b3f84407c05a.png)

**Comment by dnfield** [comment] 2019-05-09 02:46
This appears to be a duplicate of https://github.com/flutter/flutter/issues/32265, which was fixed very recently.  Can you try this out on master, it should be working a bit better now.

Please feel free to re-open this if I'm missing something here, or if there's some aspect of this bug that still isn't resolved on master.

**Comment by dnfield** [comment] 2019-05-09 02:46
(and for reference, I opened #32285 to track enhancing this feature further)

**Closed by dnfield** 2019-05-09 02:46 UTC
Labels: f: material design, framework, ⌺‬ platform-ios

**Comment by njovy** [comment] 2019-05-09 08:28
The issue has been resolved with master. Thank you!
