### ISSUE TITLE
How to limit the time in showTimePicker

### ISSUE THREAD

**Issue by rullyalves** [flutter/flutter#23717] opened 2018-10-30 06:16 UTC
Can you help a way to limit yourself as time? no data picker exists the predicate day selectable, but I did not find anything like it in the time picker.

**Comment by goderbauer** [comment] 2019-01-04 00:07
What do you mean by "limit the time picker"? Do you want to limit the user to only pick a time between, say, 7am and 6pm? Or something different?

**Comment by rullyalves** [comment] 2019-01-06 08:54
exactly, in many applications, it is necessary that the time of a calendar or even the time of a selector of hours may be limited.

**Comment by zoechi** [comment] 2019-01-07 08:21
@rullyalves 

> may be limited.

>  only pick a time between, say, 7am and 6pm? Or something different?

Can you please elaborate how you want to limit

**Comment by rullyalves** [comment] 2019-01-07 11:06
Yes, in the case of the calendar, there must be a way to limit days / months can be selected by the user, since the time selector, there must be a way to limit what hours / minutes can be chosen, and also a gap between them, such as :
be able to select hours from 08:00 to 12:00, or even mark a break as: 08:00 to 18:00 and be able to remove selectable times within that range.

**Comment by zoechi** [comment] 2019-01-07 12:50
@rullyalves thanks for the update. That makes it more clear.

**Comment by martipello** [comment] 2019-05-08 17:07
any news on this?

**Comment by Segebre** [comment] 2019-05-27 15:19
This is a must. Hope we get news soon.

**Comment by mt40** [comment] 2019-08-18 13:16
Hi, is there any new updates for this?

**Comment by peazz** [comment] 2019-09-10 16:01
Bump on this, trying to create two timer pickers that are linked. If I pick a date on the start time, it needs to affect the end time options.

If I select the time on time A @ 4pm then time B must not be able to select 3pm - there is also cases where one time selector is required but it cant be earlier than the current time

**Comment by lucasnbsb** [comment] 2019-09-18 15:45
Bump this, i'm using this to let the user schedule a notification, but anything past 3 hours breaks business rules on this case.

**Comment by tapizquent** [comment] 2019-12-20 17:50
Any updates on this? There should be a way to limit selected time to only times before current time.

**Comment by portmanteautech** [comment] 2020-01-27 18:41
Bump this. Hope this functionality is added soon.

**Comment by Dinver** [comment] 2020-02-11 13:48
Functionality is really necessary.

**Comment by sclausen** [comment] 2020-04-07 10:58
There is a `selectableDayPredicate`for `showDatePicker`, so a `selectableTimePredicate` for `showTimePicker` would be really great.

**Comment by Chris1234567899** [comment] 2020-04-24 16:56
Maybe something like a list of allowed hours and a list of allowed minutes would be good.

like 
```
showTimePicker(
        context: context,
        initialTime: TimeOfDay.now(),
        allowedHours: [8,9,10,11,12, 15,16,17],
        allowedMinutes: [0,10,20,30,40,50],
        displayDisabledValues: true
);
```

Then we can restrict users also to a minimum time resolution (every 15 minutes, half an hour or alike). 
`displayDisabledValues` would be a bool to either hide disabled hours or minutes, or display them (greyed out = unselectable).

**Comment by sclausen** [comment] 2020-04-25 07:29
I copied the source and adapted it to show only a given List of TimeOfDay and changed some logic around converting the angle to a time. It’s both in code and visually a mess because restricting for example to a range from 08:00 to 18:00 in 15 minute intervals distributes the am hous and pm hours equally around its ring and that looks really odd in the material time picker.
Nevertheless, the approach I built for my company works but I think I could make a PR with the predicate solution in my spare time since I would like to do it completely different.
@Chris1234567899 what if you want to restrict the time range from 09:15 to 16:30? In your approach that wouldn’t work.

**Comment by wterrill** [comment] 2020-04-29 22:28
@sclausen Would you be willing to share your code?  I'm currently trying to limit the time selection to 15 minute increments using the time picker. It would be nice to see what you've done.

**Comment by sclausen** [comment] 2020-05-28 15:08
> @sclausen Would you be willing to share your code? I'm currently trying to limit the time selection to 15 minute increments using the time picker. It would be nice to see what you've done.

Sorry for the long delay. I needed permission from my superior and I let it slide a litte.
I warned you about the quality! https://gist.github.com/sclausen/b97e96f33373b8cdc33fcd7bb6f6dfe7

**Comment by wterrill** [comment] 2020-05-28 17:19
great!  thank you very much!

**Comment by farismohammed** [comment] 2020-07-04 09:42
long time.! still issue not fixed. this is really needed functionality

**Comment by FadiBasheer** [comment] 2020-07-14 18:42
@sclausen Thanks for your code, but there is a problem with it, when you enter the whole hours of the day, the number 12 will repeat twice
![Screenshot_1594751983](https://user-images.githubusercontent.com/67523490/87463868-fef6b900-c5c6-11ea-953e-4ae80776e8fb.png)

**Comment by sclausen** [comment] 2020-07-18 12:55
> @sclausen Thanks for your code, but there is a problem with it, when you enter the whole hours of the day, the number 12 will repeat twice

That’s bad. Do you have a fix for this?

**Comment by mrgulshanyadav** [comment] 2020-08-26 17:11
I am still looking for a solution to this problem, this is a must-have feature in this library. Please, mates, add this feature.

**Comment by Sepehr13** [comment] 2020-09-24 18:38
Bump! 🙄

**Comment by SamerDiab** [comment] 2020-10-10 14:13
Bump!

**Comment by Beautylivery** [comment] 2020-10-10 15:24
Yep would be a great feature to be implemented

**Comment by being-yash-t** [comment] 2020-11-06 14:44
Bump!!!

**Comment by equitharn** [comment] 2020-12-02 03:40
Bump!!!!!

**Comment by hasanalfath** [comment] 2020-12-06 23:29
Please mates, add this feature.

**Comment by migalv** [comment] 2020-12-12 10:11
Bump!

**Comment by jorwan** [comment] 2020-12-23 16:54
using this temporal solution...

https://pub.dev/packages/time_picker_widget

**Comment by timohtey** [comment] 2021-01-07 19:58
Bump!

**Comment by manoellribeiro** [comment] 2021-01-13 12:39
Bump!

**Comment by hasanalfath** [comment] 2021-01-19 03:28
Bump!

**Comment by WillianSalceda** [comment] 2021-01-21 15:40
Bump!

**Comment by WillianSalceda** [comment] 2021-01-21 15:42
Bump!

Just as DatePicker, I need a firstDate and lastDate parameters, but for TimePicker.

**Comment by AntoliniMatteo** [comment] 2021-02-14 10:42
Bump!

**Comment by MariannaKrzewinska** [comment] 2021-02-15 17:45
Bump!

**Comment by amirhasyimi** [comment] 2021-03-07 08:06
A really necessary feature. Hope this will get added soon!

**Comment by yashwp** [comment] 2021-03-11 06:58
When to expect this man??!!!!!!
Basic feature.

**Comment by Khader-1** [comment] 2021-03-18 18:07
Bump!

**Comment by brightseagit** [comment] 2021-03-19 05:18
Yes, this is a very neccessary feature to schedule ranged timetables.  To create something like this:-
![Screenshot 2021-03-19 104312](https://user-images.githubusercontent.com/72334435/111734325-ecdcc100-889f-11eb-8f9d-983992732e49.png)
Without this, I'm forced to show popups to users showing that the selected time can't be set which creates bad UX.

I hope that the team is already working on a solution as the issue is quite old. Bump!

**Comment by Okladnoj** [comment] 2021-04-03 19:53
Bump!

**Comment by Okladnoj** [comment] 2021-04-03 19:53
Bump!

**Comment by FlawLessx** [comment] 2021-04-04 09:31
any updates?

**Comment by dukaric1991** [comment] 2021-04-09 09:13
Bump!

**Comment by adamk22** [comment] 2021-05-18 19:13
Another bump!

**Comment by Huzon** [comment] 2021-05-20 11:00
bump!

**Comment by Okladnoj** [comment] 2021-05-21 06:11
Bump!

**Comment by setbap** [comment] 2021-06-19 09:55
Bump!

**Comment by Isidoria** [comment] 2021-07-10 18:49
I'd love this too

**Comment by amucunguzi** [comment] 2021-08-11 16:09
Bump, please!

**Comment by abdallah-gaber** [comment] 2021-10-05 09:11
bump!

**Comment by magax** [comment] 2021-10-07 03:38
This is necessary!

**Comment by rami-a** [comment] 2021-10-20 21:09
There isn't any guidance for this from Material unfortunately. It does seem like a tricky problem to solve. 

An alternative could be building something custom with a dropdown menu that only shows the allowed times for hours/minutes.

**Comment by flenairMacif** [comment] 2021-11-09 14:06
So long

![image](https://user-images.githubusercontent.com/48446573/140938608-ff503092-6750-4d7e-8131-8e8258457877.png)

**Comment by Aristidios** [comment] 2021-11-10 10:47
> 
> An alternative could be building something custom with a dropdown menu that only shows the allowed times for hours/minutes.

I don't think a dropdown would look so good - ![image](https://user-images.githubusercontent.com/54664724/141099413-74354ac8-3484-4b95-b1f3-9cf9983cec08.jpeg)

- juste hide the times outside of intervals or snap like so ?

**Comment by rami-a** [comment] 2021-11-11 20:25
Hey folks,

After speaking with designers on the Material team, it's been decided that limiting selection on the TimePicker is not something we want to support officially. We see the time picker UI as something similar to a slider, so having disabled values within that would be confusing.

My recommendation is to either handle the validation of the time after the user taps OK or to build something custom (using dropdowns or existing packages or whatever).

The Material team is in the early phases of designing/creating a more desktop appropriate time picker selection UI (that might involve dropdown-like behavior). Once that is in a more solidified state, it could be something we add to Flutter as a new widget.

That being said, I'm going to close out this issue. Thanks for all the feedback and important discussion!

**Closed by rami-a** 2021-11-11 20:25 UTC
Labels: severe: new feature, framework, f: material design, f: date/time picker, customer: crowd, passed first triage

**Comment by Aristidios** [comment] 2021-11-11 20:44
> Hey folks,
> 
> 
> 
> After speaking with designers on the Material team, it's been decided that limiting selection on the TimePicker is not something we want to support officially. We see the time picker UI as something similar to a slider, so having disabled values within that would be confusing.
> 

I don't see how it would be confusing to the user not being able to pick hours outside of working hours if it fits the context - what is confusing is being able to pick a dentist appointment at midnight making TimePicker unusable for many use cases...

**Comment by Fleximex** [comment] 2021-11-24 08:12
@rami-a 
I don't understand the use of the Slider widget as an example. It contradicts the point you want to make. When we create a Slider we can literally set a min-max value with divisions. So for example:
```
Slider(
  value: _currentSliderValue,
  min: 0,
  max: 100,
  divisions: 5,
  label: _currentSliderValue.round().toString(),
  onChanged: (double value) {
    setState(() {
      _currentSliderValue = value;
    });
  },
),
```
Here we limit the user by not allowing it to pick a value below 0 or above 100. And within the set range we limit the user to only pick 0, 20, 40, 60, 80 or 100. Which is what we also want for the TimePicker widget.

Allowing users to only pick in intervals of 5 or 10 minutes is UI wise very clear. Don't grey out the options you can't pick, but simply don't show them. Sof or the 10 minutes interval option you would omit the 5, 15, 25, etc labels and let the picker snap to the closest 10 minute interval.
For the selectable range I can understand it can look weird in the current TimePicker widget. However, isn't that up to the developer to manage functionality and visuals?

Other widgets don't limit the developer to make them visually unpleasing or hard to use for users:
I.e. I can take a ListTile widget and add huge or no paddings to it making it look bad. I can use the same highlightColor as backgroundColor for the ListTile widget; making it unclear for the user the ListTile is tappable.

**Comment by winneze1** [comment] 2021-12-03 17:40
> Hey folks,
> 
> After speaking with designers on the Material team, it's been decided that limiting selection on the TimePicker is not something we want to support officially. We see the time picker UI as something similar to a slider, so having disabled values within that would be confusing.
> 
> My recommendation is to either handle the validation of the time after the user taps OK or to build something custom (using dropdowns or existing packages or whatever).
> 
> The Material team is in the early phases of designing/creating a more desktop appropriate time picker selection UI (that might involve dropdown-like behavior). Once that is in a more solidified state, it could be something we add to Flutter as a new widget.
> 
> That being said, I'm going to close out this issue. Thanks for all the feedback and important discussion!

That is very wrong thinking. I dont think the design team really understand the logic behind the TimePick widget. By compare this with slider. I'm 100% sure you guys DO NOT know about the need of this widget to Developers and also users. Why does a neccesary function would be confusing?? I dont get it
