### ISSUE TITLE
CupertinoDatePicker doesn't display some dates

### ISSUE THREAD

**Issue by delbyze** [flutter/flutter#53528] opened 2020-03-29 18:11 UTC
I implement a `CustomDatePicker` using `CupertinoDatePicker`. I give a specific initialDateTime but if this date is after today, CupertinoDatePicker **hide today's line**. 

[**Normal behaviour**] With an initialDateTime = today or before : 
![Capture d’écran 2020-03-29 à 20 00 03](https://user-images.githubusercontent.com/38207269/77856501-f1741980-71f7-11ea-8044-b9b93763f5cb.png)

[**Wrong behaviour**] With an initialDateTime = tomorrow or after : 
![Capture d’écran 2020-03-29 à 20 00 15](https://user-images.githubusercontent.com/38207269/77856509-ff299f00-71f7-11ea-8530-3938159a0c51.png)

Here is my custom `CupertinoDatePicker` class : 

<img width="579" alt="Capture d’écran 2020-03-29 à 19 50 45" src="https://user-images.githubusercontent.com/38207269/77856322-9e4d9700-71f6-11ea-9287-35cc0f76e20c.png">

Here is my `Flutter doctor -v` log :

![Capture d’écran 2020-03-29 à 20 03 43](https://user-images.githubusercontent.com/38207269/77856585-6e9f8e80-71f8-11ea-91cb-4936a36fab5a.png)

**Comment by VladyslavBondarenko** [comment] 2020-03-30 10:53
Hi @delbyze 
do you experience this with different devices?
I can't reproduce it with `flutter stable v1.12.13+hotfix.8` and iOS 13.4 simulator

<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Center(
        child: CupertinoDatePicker(
          initialDateTime: DateTime(2020, 3, 31, 8, 30),
          use24hFormat: true,
          mode: CupertinoDatePickerMode.dateAndTime,
          onDateTimeChanged: (_) {},
        ),
      ),
    );
  }
}
```
</details>

Please don't post screenshots of text, post the text instead.
Screenshots are not searchable and it's not possible to copy-past text out of it.

**Comment by delbyze** [comment] 2020-03-30 11:48
Sorry for the screenschot, it was for readability but I should had added text code too.

Yes, I do experience it on multiple devices : iOS or Android, simulators or real devices.

After trying today, I still have a bug but it is different from what I thought.
In fact, it's specifically the **SUN 29 MARCH 2020**  which is not written in the `CupertinoDatePicker`.
We can see, in your screenshot, that this date is missing too. 

Morevover, I have searched a little further ;
- In 2021, it's the **SUN 28 MARCH** that is missing.
- In 2022, it's the **SUN 27 MARCH** that is missing.
- In 2023, it's the **SUN 26 MARCH** that is missing.
- In 2024, it's the **SUN 31 MARCH** that is missing.
- In 2025, it's the **SUN 30 MARCH** that is missing.
....
i didn't continue but this behaviour seems to repeat every year on the last sunday of march.

**Comment by VladyslavBondarenko** [comment] 2020-04-24 14:31
I can't reproduce it with current beta `v1.17.0-3.2.pre` and dev `v1.18.0-6.0.pre`, only with stable `v1.12.13+hotfix.9`. 
Seems to be fixed. Closing since there is no more need to track the issue.
if you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-04-24 14:31 UTC
Labels: f: cupertino, f: date/time picker, framework, has reproducible steps
