### ISSUE TITLE
I got a problem that i cannot prevent click event through my float button into under webview 

### ISSUE THREAD

**Issue by 903496130** [flutter/flutter#121310] opened 2023-02-23 06:22 UTC
Hello guys. It's nice to talk to you all.

I am a flutter beginner  and writing a game app with it. Now i am writing a simple demo that some floating button on a webview.

The game run in webView and user can do something with the floating button created by flutter.

But it's upset to me that i found when i touch the floating button, under webview will also be effected.

### I try many ways to fix that, such as AbsorbPointer, PointerInterceptor, IgnorePointer. But them all fail.

Then i found that when i tap the floating button,webView actually know i press the screen, but webView doesn't know my finger leave the screen.It's not a problem in  most scene, because webPage handle click event just over when our finger off the screen. But my project is a game, press event is also important.The reason make me think so is my game in webview is a plane which shot when we are pressing screen. But in flutter, when i tap the floating button, the plane start shot and never stop until i touch somewhere in webview. I guess webView know i touch its other place and make plane stop shot.

<details>
<summary>Code sample</summary>

###  this is GameMainView
```
import 'package:flutter/material.dart';
import 'Container/GameContainer.dart';
import 'UIFrame/GameUIView.dart';
import 'package:pointer_interceptor/pointer_interceptor.dart';

class GameMainView extends StatelessWidget {
  const GameMainView({super.key});

  @override
  Widget build(BuildContext context) {
    // 同时加载GameContainer 和 GameViewUI，两个组件同时存在，GameViewUI在GameContainer之上，GameViewUI是透明的
    return Stack(
      children: [
        GameContainer(url: "http://81.70.159.96/"),
        PointerInterceptor(
          child: Positioned(
            right: 10,
            bottom: 15,
            child: Column(children: const <Widget>[
              // GameUIViewButton
              // 从上到下依次是： 点赞 评论 收藏 折叠 四个按钮
              GameUIViewButton(buttonIcon: Icons.thumb_up, buttonTitle: '点赞'),
              GameUIViewButton(buttonIcon: Icons.comment, buttonTitle: '评论'),
              GameUIViewButton(buttonIcon: Icons.star, buttonTitle: '收藏'),
              GameUIViewButton(
                  buttonIcon: Icons.arrow_drop_down, buttonTitle: '折叠'),
            ]),
          ),
        )
      ],
    );
  }
}
```

### and this is the GameContainer
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class GameContainer extends StatefulWidget {
  String url;

  GameContainer({super.key, required this.url});

  @override
  State<StatefulWidget> createState() => GameContainerState();
}

class GameContainerState extends State<GameContainer> {
  WebViewController controller = WebViewController()
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    ..setBackgroundColor(const Color(0x00000000))
    ..setNavigationDelegate(
      NavigationDelegate(
        onProgress: (int progress) {
          // Update loading bar.
        },
        onPageStarted: (String url) {},
        onPageFinished: (String url) {},
        onWebResourceError: (WebResourceError error) {},
        onNavigationRequest: (NavigationRequest request) {
          if (request.url.startsWith('https://www.youtube.com/')) {
            return NavigationDecision.prevent;
          }
          return NavigationDecision.navigate;
        },
      ),
    )
    ..loadRequest(Uri.parse("http://81.70.159.96/"));

  @override
  Widget build(BuildContext context) {
    return Stack(children: [
      WebViewWidget(controller: controller),
      GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: () {
          // do something
          print("object");
        },
      ),
    ]);
  }
}

```

### finally this is  GameUIView
```
import 'package:flutter/material.dart';


class GameUIView extends StatelessWidget {
  const GameUIView({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.transparent,
      ),
      child: Column(
        children: const <Widget>[
          GameUIViewButton(buttonIcon: Icons.home, buttonTitle: '玩游戏'),
          GameUIViewButton(buttonIcon: Icons.search, buttonTitle: '查找'),
          GameUIViewButton(buttonIcon: Icons.person, buttonTitle: '我的'),
        ],
      ),
    );
  }
}

class GameUIViewButton extends StatelessWidget {
  final IconData buttonIcon;
  final String buttonTitle;

  // 类初始化 传入buttonIcon, buttonTitle两个参数
  const GameUIViewButton(
      {super.key, required this.buttonIcon, required this.buttonTitle});

  @override
  Widget build(BuildContext context) {
    // 创建一个按钮 按钮的图标和文字分别为buttonIcon, buttonTitle，图标和文字是上下排列
    return Column(children: [
      Icon(buttonIcon, color: Colors.red, size: 100),
      Text(buttonTitle,
          style: const TextStyle(color: Colors.red, fontSize: 12)),
    ]);
  }
}

```

</details>

<details>
  <summary>My `flutter doctor -v` result msg</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.10 on channel stable at /Users/jiangzhaoguang/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/jiangzhaoguang/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.7571.203

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 87A2B808-D457-4687-B630-755FB2178450 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1
      22C65 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 110.0.5481.100

HTTP Host availability check is taking a long time...[!] HTTP Host Availability
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while
      checking the HTTP host: Operation timed out
    ✗ HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the
      HTTP host: Connection terminated during handshake
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while
      checking the HTTP host: Operation timed out

! Doctor found issues in 3 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-02-23 10:10
Closing this as a duplicate of https://github.com/flutter/flutter/issues/58659. 

Kindly subscribe to the original issue for updates. 

Thank you.

**Closed by danagbemava-nc** 2023-02-23 10:10 UTC
Labels: in triage
