### ISSUE TITLE
InteractiveViewer sometimes treats Scale as Pan

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#63999] opened 2020-08-17 22:12 UTC
## Steps to reproduce

  1. Run the code given below.
  1. Attempt many different scale gestures.
  1. Eventually, one may get stuck as a pan. You'll have two fingers on the screen, but no amount of pinching them together/apart will cause a zoom. Lifting one or more fingers will reset it.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Scaffold(
        appBar: AppBar(title: Text('Demo')),
        body: Center(
          child: ClipRect(
            child: InteractiveViewer(
              child: Container(
                color: Colors.brown,
                child: Image.network(
                  'https://1001freedownloads.s3.amazonaws.com/vector/thumb/116435/go_board_09x09.png',
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

## Cause
_onScaleUpdate always receives a scale of 1.0 during this stuck gesture.  That would make me think that it's a bug with GestureDetector, but I was unable to reproduce this with a lone GestureDetector.  There must be something with InteractiveViewer's widget tree or configuration that causes the bug to show up.

Moved to new issue from some discussion in https://github.com/flutter/flutter/issues/63006.

**Comment by markusaksli-nc** [comment] 2020-08-18 06:12
Reproducible on the latest master `1.21.0-10.0.pre.114`.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Scaffold(
        appBar: AppBar(title: Text('Demo')),
        body: Center(
          child: InteractiveViewer(
            child: Container(
              color: Colors.brown,
              child: Image.network(
                'https://1001freedownloads.s3.amazonaws.com/vector/thumb/116435/go_board_09x09.png',
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.135, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.135 at C:\Development\flutter_master
    • Framework revision 654022aecb (6 hours ago), 2020-08-18 03:01:02 +0300
    • Engine revision b9243713a0
    • Dart version 2.10.0 (build 2.10.0-36.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

I can reproduce this on both emulator and physical Android and iOS.

On both Android and iOS physical devices I can get into this stuck state where only gestures from one corner of the screen are detected. This obviously results in the same scale turning into pan issue. A strange detail is that lifting both fingers off the screen 
doesn't reset it. the only thing that seems to work is panning back towards the middle from the working corner.

<img src="https://user-images.githubusercontent.com/68219924/90476680-a91bb080-e132-11ea-96e4-9cd615fdddef.gif" height="400" />

**Comment by justinmc** [comment] 2020-08-18 18:35
@markusaksli-nc I've realized that the specific problem with gestures happening near the corners is not related to this issue, it's a mistake in the sample code we're using.  If you wrap your InteractiveViewer in a ClipRect you'll see what the problem is: the gestures are happening outside of the InteractiveViewer.  I've updated the issue's description to use a ClipRect.

To avoid this problem without using a smaller area of the screen with a ClipRect, you'll have to make sure that the InteractiveViewer is taking up the full size of the screen. See my [flutter-go code](https://github.com/justinmc/flutter-go/blob/master/lib/main.dart) for a full example of positioning a widget within the screen while letting it zoom to the full size of the screen without hitting this problem.

**Comment by markusaksli-nc** [comment] 2020-08-18 19:44
Ah I see! Thanks for clarifying this. I suppose it should be mentioned in the documentation to some degree to make it easier for users to diagnose the resulting behavior (unless it's already mentioned somewhere and I can't find it) . The [InteractiveViewer](https://master-api.flutter.dev/flutter/widgets/InteractiveViewer-class.html) class page has plenty of room for this.

Sorry for causing a bit of a detour here with the faulty sample code. I'll keep this in mind if it pops up again during triage.

**Comment by justinmc** [comment] 2020-08-18 21:32
No worries!  I'm really trying to get a feel for how people are using InteractiveViewer and the problems they are having, so this is really useful.  I think you're right about the documentation, I'll add something.

**Comment by huycozy** [comment] 2023-04-19 09:52
This issue seems to have been fixed on the latest master channel as I cannot reproduce it there using the latest sample code at https://github.com/flutter/flutter/issues/63999#issue-680556122. 

I don't get stuck when zooming in/out and panning as well. Verified on `Samsung Galaxy Tab A7 Lite, Android 13`. 

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/233035616-d9aac260-3dc7-427a-8cd7-7c760951f352.mov

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.11 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (31 hours ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-7.0.pre.44, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-7.0.pre.44 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9392f2e2a (3 hours ago), 2023-04-18 20:31:26 -0400
    • Engine revision 099ed6c62d
    • Dart version 3.1.0 (build 3.1.0-12.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 112.0.5615.121

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Could you please confirm if it's fixed on a PR?

**Closed** 2023-05-10 10:10 UTC
Labels: waiting for customer response, framework, f: gestures, has reproducible steps, P4, found in release: 1.21
