### ISSUE TITLE
Filter out bots from Analytics 

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/flutter#37339] opened 2019-07-31 21:26 UTC
There are some signals that suggest that we have bots reporting to Analytics (or you have a bug).

* Hundreds clients run 9-10 hot reloads and hot restarts every day
* About 7% of the new clients are using custom branch of Flutter or are suspected to run CI/CD process
* Clients with no IDE information (meaning they use CL tool?) consists over 40% of total clients

(Note: a client is a machine that has Flutter installed and Analytics enabled)

**Comment by zanderso** [comment] 2019-08-06 16:13
In https://github.com/flutter/flutter/pull/37514 I removed sending an analytics screen that was sent unconditionally on tool startup. My expectation is that it will help, but not remove all the unexpected items. We should continue monitoring as the changes makes its way into dev, beta, and stable.

**Comment by zanderso** [comment] 2019-08-23 20:28
@jayoung-lee Could you send me the data or a link to the data for the hot reloads by email? Thanks!

**Comment by zanderso** [comment] 2020-02-11 21:40
Duplicate of https://github.com/flutter/flutter/issues/4709

**Closed by zanderso** 2020-02-11 21:40 UTC
Labels: from: study, tool
