### ISSUE TITLE
Invalid symlinks when installing in iOS simulator: plugin dependencies of my module on a native iOS project

### ISSUE THREAD

**Issue by danilofuchs** [flutter/flutter#64162] opened 2020-08-19 15:54 UTC
## Steps to Reproduce

1. Create sample Xcode project using UIKit (Storyboard)
2. Create a module and link it to the project following the official steps via Cocoapods (option A)
3. Close Xcode and open `.xcworkspace` instead
3. Add `device_info` as dependency of module and use it in the code
4. Run `flutter pub get` on the flutter module and `pod install` on the native iOS app
5. Build the project with Xcode, targeting a simulator (can be brand new)

**Expected results:** 

Should open the app on the simulator

**Actual results:** 

Build is successful, but Xcode has errors:

```
Could not install at this time.
invalid symlink at /Users/danilo.fuchs/Library/Developer/CoreSimulator/Devices/B21B0058-78C0-419E-8FBD-819FD6D1342C/data/Library/Caches/com.apple.mobile.installd.staging/temp.CKxTLM/extracted/test_flutter_native_2.app/my_flutter/.ios/Flutter/.symlinks/device_info
```

![image](https://user-images.githubusercontent.com/17657014/90653547-b362ab00-e215-11ea-8991-95dd19a5d0c0.png)

**Things I tried doing to fix the issue:**

- `flutter clean` + `flutter pub get` + `pod install` (multiple times)
- Xcode clean
- delete Xcode `DerivedData`
- `flutter upgrade` (stable)
- `flutter pub cache restore` + clean installs
- `flutter pub upgrade`

<details>
  <summary>Logs</summary>

```
➜ flutter analyze
Analyzing my_flutter...                                                 
No issues found! (ran in 4.7s)
```

```
➜ flutter doctor -v

[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.4 19E287, locale en)
    • Flutter version 1.20.2 at /Users/danilo.fuchs/flutter
    • Framework revision bbfbf1770c (6 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/danilo.fuchs/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (1 available)            
    • iPhone Xʀ (mobile) • B21B0058-78C0-419E-8FBD-819FD6D1342C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2020-08-21 08:10
Hi @danilofuchs 
Following your steps, I couldn't reproduce the issue. 

<img width="839" alt="Screenshot 2020-08-21 at 1 36 54 PM" src="https://user-images.githubusercontent.com/48603081/90867948-c7441380-e3b3-11ea-98c9-65267982f3f3.png">

**Please check out my code sample (Includes module and ios project)** 

[test_project.zip](https://github.com/flutter/flutter/files/5107628/test_project.zip)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (8 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS
      13.6.1
    • iPhone 11 (mobile)     • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-08-25 10:49
hi @danilofuchs 
It could be Xcode but since the issue isn't reproducible, I feel safe to close the issue. 
If you disagree please write in the comments and I will reopen it. Provide  reproducible code sample 
Thank you

**Closed by TahaTesser** 2020-08-25 10:49 UTC
