### ISSUE TITLE
flutter gallery benchmark code is not determistic on android

### ISSUE THREAD

**Issue by sortie** [flutter/flutter#23958] opened 2018-11-05 21:38 UTC
Hi,

The Dart VM team's flutter gallery code size benchmarks have started not being deterministic, sometimes varying up to 40% for the read only data. It seems it's the read only data and the isolate data that's varying. This is preventing proper detection of performance changes to these benchmarks as any real changes is usually within the huge noise here. The problem seems to affect the android builds: flutter profile & flutter release, as well as both 32-bit ARM and 64-bit ARM. No data on whether this affects iOS.

These benchmarks build the latest Dart SDK, Flutter Engine, and Flutter framework together. That may cause problems that might not occur with just plain flutter right now.

For instance, one benchmark is run as:

```
printf %s 'solutions = [ { "name": "src/flutter", "url": "https://github.com/flutter/engine.git", "deps_file": "DEPS", "custom_deps": { "src/third_party/libjpeg-turbo": "https://fuchsia.googlesource.com/third_party/libjpeg-turbo.git" }, }, { "name": "flutter", "url": "https://github.com/flutter/flutter.git", }, ] cache_dir = "/tmp/builder_git_cache" target_os = ["android"] ' > .gclient
gclient sync -r src/flutter@$engineHash -r flutter@$flutterHash -r src/third_party/dart@$dartHash --ignore_locks > /dev/null
src/third_party/dart/tools/3xhead_flutter_hooks.sh
cd src
flutter/tools/gn --runtime-mode release
ninja -C out/host_release
flutter/tools/gn --android --android-cpu arm --runtime-mode release
ninja -C out/android_release
cd ..
PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:$PATH" ANDROID_HOME=/opt/android-sdk flutter/bin/flutter config --no-analytics
cd flutter
cd examples
cd flutter_gallery
cat >> pubspec.yaml << EOF dependency_overrides: sky_engine: path: $(realpath ../../../src/out/android_release/gen/dart-pkg/sky_engine) sky_services: path: $(realpath ../../../src/out/android_release/gen/dart-pkg/sky_services) EOF
PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:$PATH" ANDROID_HOME=/opt/android-sdk ../../../flutter/bin/flutter build -v aot --extra-gen-snapshot-options=--print_snapshot_sizes --local-engine-src-path="$PWD/../../../src" --local-engine=android_release --target="lib/main.dart" --target-platform=android-arm > ../../../flutter_gallery.apk.aot.log
PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:$PATH" ANDROID_HOME=/opt/android-sdk ../../../flutter/bin/flutter build apk --local-engine-src-path="$PWD/../../../src" --local-engine=android_release --target="lib/main.dart" --target-platform=android-arm
cp build/app/outputs/apk/release/app-release.apk ../../../flutter_gallery.apk
PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:$PATH" ANDROID_HOME=/opt/android-sdk ../../../flutter/bin/flutter clean
git checkout -- pubspec.yaml
cd ..
cd ..
cd ..
grep -E 'Building AOT snapshot' -A 10 flutter_gallery.apk.aot.log
```

Not sure who to talk to here. @mraleph @mkustermann can you help me route this to the right people?

**Comment by mkustermann** [comment] 2018-11-06 12:02
I would guess that either the CFE is not deterministic or the VM's `gen_snapshot`.

Can we have tarball of two such builds which should be the same or not? Then we can just look into the `flutter_gallery/build/aot/app.dill` and see if that is the same.

/cc @kmillikin

**Comment by sortie** [comment] 2018-11-06 18:04
The problem seems to have disappeared. Unclear what fixed it or if it'll be back.

The flutter gallery code sizes are different between these two builds, where the only difference is this dart2js commit <https://github.com/dart-lang/sdk/commit/36874154b486f75a8544d13cc06ebbcae6cd229a>.

http://146.148.43.81:4538/buildstorage/flutter-release/72573/bin/android-armv7.tar.gz
http://146.148.43.81:4538/buildstorage/flutter-release/72574/bin/android-armv7.tar.gz

**Comment by jensjoha** [comment] 2018-11-07 09:54
Disclaimer: I'm not providing any answers in the below, only digging into stuff a bit.

Downloading ranges 72571-72576 and extracting `isolate_snapshot_data` from the `flutter_gallery.apk` i get the following sizes:
```
5.5M Nov  5 22:01 isolate_snapshot_data.72571
4.1M Nov  5 22:06 isolate_snapshot_data.72572
4.1M Nov  5 22:39 isolate_snapshot_data.72573
5.5M Nov  5 23:51 isolate_snapshot_data.72574
5.5M Nov  5 23:24 isolate_snapshot_data.72575
4.1M Nov  5 23:33 isolate_snapshot_data.72576
```

running `strings` on them I get this:
```
1.4M strings.72571
435K strings.72572
435K strings.72573
1.4M strings.72574
1.4M strings.72575
435K strings.72576
```
running it through `sort` and `uniq` I get this:
```
1.3M strings_sorted.72571
418K strings_sorted.72572
418K strings_sorted.72573
1.3M strings_sorted.72574
1.3M strings_sorted.72575
418K strings_sorted.72576
```

Looking into them, only
```
1.3M strings_sorted.72571
1.3M strings_sorted.72574
1.3M strings_sorted.72575
```
contains the strings `_offsetSinceLastStop` and `_snackBarController` for instance.

If also looking at the newest one at the time of this writing (72659) the data is like this:
```
6.1M isolate_snapshot_data.72659
571K strings.72659
554K strings_sorted.72659
```
and it does contain the strings `_offsetSinceLastStop` and `_snackBarController` for instance, though fewer times, e.g.
```
strings_sorted.72575:13566:|dyn:_offsetSinceLastStop@522498029
strings_sorted.72575:14679:dyn:set:_offsetSinceLastStop@522498029
strings_sorted.72575:17308:FF_offsetSinceLastStopx
strings_sorted.72575:22723:hget:_offsetSinceLastStop@522498029

strings_sorted.72575:31409:*_offsetSinceLastStop@522498029
strings_sorted.72575:46729:xset:_offsetSinceLastStop@522498029

strings_sorted.72659:14467:*_offsetSinceLastStop@522498029
strings_sorted.72659:22734:xset:_offsetSinceLastStop@522498029
```
(space inserted for clearity --- the first 4 doesn't occur in 72659).

**Comment by mraleph** [comment] 2018-11-07 12:44
This is caused by concurrent marking. Assigning to @rmacnak-google. 

We have the following code:

```cpp
void Symbols::Compact(Isolate* isolate) {
  ASSERT(isolate != Dart::vm_isolate());
  Zone* zone = Thread::Current()->zone();

  // 1. Drop the symbol table and do a full garbage collection.
  isolate->object_store()->set_symbol_table(Object::empty_array());
  isolate->heap()->CollectAllGarbage();

  // ...
} 
```

The expectation here is that symbols that were only reachable through symbol table will die. 

However if concurrent marking is in progress we might have already marked through symbol table - meaning that `  isolate->object_store()->set_symbol_table(Object::empty_array());` has no effect and all symbol table entries survive `CollectAllGarbage`.

It seems to me that we should probably disable concurrent marking during snapshot generation, or at least change `CollectAllGarbage` to truly collect all garbage by stopping in-progress marking and then doing a clean GC cycle from scratch.

To confirm this analysis I made the following patch:

```diff
diff --git a/runtime/vm/heap/heap.cc b/runtime/vm/heap/heap.cc
index 96b0eecb56..98049fcbb7 100644
--- a/runtime/vm/heap/heap.cc
+++ b/runtime/vm/heap/heap.cc
@@ -482,9 +482,13 @@ void Heap::CollectMostGarbage(GCReason reason) {
   CollectOldSpaceGarbage(thread, kMarkSweep, reason);
 }
 
-void Heap::CollectAllGarbage(GCReason reason) {
+void Heap::CollectAllGarbage(GCReason reason, bool verbose) {
   Thread* thread = Thread::Current();
 
+  if (verbose) {
+    OS::PrintErr("CollectAllGarbage(%s)\n", PageSpace::PhaseToString(old_space_.phase()));
+  }
+
   // New space is evacuated so this GC will collect all dead objects
   // kept alive by a cross-generational pointer.
   EvacuateNewSpace(thread, reason);
diff --git a/runtime/vm/heap/heap.h b/runtime/vm/heap/heap.h
index 6f2051841b..e3032f395b 100644
--- a/runtime/vm/heap/heap.h
+++ b/runtime/vm/heap/heap.h
@@ -129,7 +129,7 @@ class Heap {
 
   // Collect both generations by performing an evacuation followed by a
   // mark-sweep. This function will collect all unreachable objects.
-  void CollectAllGarbage(GCReason reason = kFull);
+  void CollectAllGarbage(GCReason reason = kFull, bool verbose = false);
 
   bool NeedsGarbageCollection() const {
     return old_space_.NeedsGarbageCollection();
diff --git a/runtime/vm/heap/pages.h b/runtime/vm/heap/pages.h
index 047a3b74b2..3d5461e6c7 100644
--- a/runtime/vm/heap/pages.h
+++ b/runtime/vm/heap/pages.h
@@ -220,6 +220,17 @@ class PageSpace {
   enum GrowthPolicy { kControlGrowth, kForceGrowth };
   enum Phase { kDone, kMarking, kAwaitingFinalization, kSweeping };
 
+  static const char* PhaseToString(Phase phase) {
+    switch (phase) {
+      case kDone: return "DONE";
+      case kMarking: return "MARKING";
+      case kAwaitingFinalization: return "AWAITING-FINALIZATION";
+      case kSweeping: return "SWEEPING";
+      default:
+        return "???";
+    }
+  }
+
   PageSpace(Heap* heap, intptr_t max_capacity_in_words);
   ~PageSpace();
 
diff --git a/runtime/vm/symbols.cc b/runtime/vm/symbols.cc
index e9f410fe6b..9c8c8af4d8 100644
--- a/runtime/vm/symbols.cc
+++ b/runtime/vm/symbols.cc
@@ -350,7 +350,8 @@ void Symbols::Compact(Isolate* isolate) {
 
   // 1. Drop the symbol table and do a full garbage collection.
   isolate->object_store()->set_symbol_table(Object::empty_array());
-  isolate->heap()->CollectAllGarbage();
+  isolate->heap()->CollectAllGarbage(Heap::kFull, true);
+  isolate->heap()->CollectAllGarbage(Heap::kFull, true);
 
   // 2. Walk the heap to find surviving symbols.
   GrowableArray<String*> symbols;
@@ -377,6 +378,8 @@ void Symbols::Compact(Isolate* isolate) {
     iteration.IterateObjects(&visitor);
   }
 
+  OS::PrintErr(">>> found %" Pd " symbols\n", symbols.length());
+
   // 3. Build a new table from the surviving symbols.
   Array& array = Array::Handle(
       zone, HashTables::New<SymbolTable>(symbols.length() * 4 / 3, Heap::kOld));
```

With one `CollectGarbage` in `Symbols::Compact` I get 

```
╭─vegorov@volhv ~/src/flutter/flutter/examples/flutter_gallery ‹master*›                                                     
╰─$ flutter clean && flutter build aot --release --extra-gen-snapshot-options="--print-snapshot-sizes" --local-engine android_release
Deleting 'build/'.
Building AOT snapshot in release mode (android_release)...                                                                   
CollectAllGarbage(AWAITING-FINALIZATION)
>>> found 46031 symbols
VMIsolate(CodeSize): 4729
Isolate(CodeSize): 2289548
ReadOnlyData(CodeSize): 3467232
Instructions(CodeSize): 6091360
Total(CodeSize): 11852869
53.4s
Built to build/aot/.
```

And with 2 I get:

```
╭─vegorov@volhv ~/src/flutter/flutter/examples/flutter_gallery ‹master*›                                                     
╰─$ flutter clean && flutter build aot --release --extra-gen-snapshot-options="--print-snapshot-sizes" --local-engine android_release
Deleting 'build/'.
Building AOT snapshot in release mode (android_release)...                                                                   
CollectAllGarbage(AWAITING-FINALIZATION)
CollectAllGarbage(SWEEPING)
>>> found 15688 symbols
VMIsolate(CodeSize): 4729
Isolate(CodeSize): 2165751
ReadOnlyData(CodeSize): 2148072
Instructions(CodeSize): 6091360
Total(CodeSize): 10409912
51.5s
Built to build/aot/.
```

Notice that `RO` size is reduced because most of the symbols die.

**Comment by rmacnak-google** [comment] 2018-11-07 18:43
There are many sources of non-determinism in the VM, and most of them involve performance trade-offs. The VM doesn't know at startup whether it will be used to create a snapshot or not, so determinism is opt-in. If determinism is preferred over compile time, flutter tool should pass --deterministic to gen_snapshot.

**Comment by mraleph** [comment] 2018-11-07 18:47
Ryan please read the analysis of the issue. Notice that we are nondeterministically emitting effectively dead symbols into AOT snapshot. 

It’s okay to be nondeterministic. It’s not good is we put 30k dead strings into RO section.

**Comment by rmacnak-google** [comment] 2018-11-07 18:56
We are non-deterministically including dead symbols when gen_snapshot was not asked to be deterministic. I don't see why this particular non-determinism is special.

**Comment by mraleph** [comment] 2018-11-07 19:09
Because it is a significant regression - turning concurrent marking on altered contract of CollectAllGarbage - which AOT compiler relies on and introduced non-determinism where previously there was none.

**Closed** 2018-11-07 22:44 UTC

**Comment by sortie** [comment] 2018-11-08 20:56
Thanks all for figuring this out and fixing it. The benchmarks have stabilized again and produce trustworthy data.
