### ISSUE TITLE
 SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353

### ISSUE THREAD

**Issue by evan8133** [flutter/flutter#156393] opened 2024-10-08 08:09 UTC
### Steps to reproduce

1-flutter run

### Expected results

The application to run normally 

## exception

SocketException: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353

```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```

### Code sample

<details open><summary>Code sample</summary>
Nothing is wrong with code

```dart

void main() async {
  await initialMain();
  runApp(const MyApp());
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

Oops; flutter has exited unexpectedly: "SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353".
A crash report has been written to /Users/arivanshamal/projects/battuta_flutter/flutter_04.log
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+SocketException%3A+Send+failed+%28OS+Error%3A+No+route+to+host%2C+errno+%3D+65%29%2C+address+%3D+0.0.0.0%2C+port+%3D+5353

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/to/report-bugs

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+SocketException%3A+Send+failed%2C+OS+Error%3A+No+route+to+host%2C+errno+%3D+65&body=%23%23+Command%0A%60%60%60sh%0Aflutter+run+--machine+--start-paused+-d+00008101-00115C1E1081401E+--devtools-server-address+http%3A%2F%2F127.0.0.1%3A9101%2F+--target+%2FUsers%2Farivanshamal%2Fprojects%2Fbattuta_flutter%2Flib%2Fmain.dart%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0ASocketException%3A+Send+failed%2C+OS+Error%3A+No+route+to+host%2C+errno+%3D+65%0A%60%60%60console%0A%230++++++_NativeSocket.send+%28dart%3Aio-patch%2Fsocket_patch.dart%3A1275%3A34%29%0A%231++++++_RawDatagramSocket.send+%28dart%3Aio-patch%2Fsocket_patch.dart%3A2590%3A15%29%0A%232++++++MDnsClient.lookup+%28package%3Amulticast_dns%2Fmulticast_dns.dart%3A219%3A22%29%0A%233++++++MDnsVmServiceDiscovery._pollingVmService+%28package%3Aflutter_tools%2Fsrc%2Fmdns_discovery.dart%3A232%3A66%29%0A%3Casynchronous+suspension%3E%0A%234++++++MDnsVmServiceDiscovery.firstMatchingVmService+%28package%3Aflutter_tools%2Fsrc%2Fmdns_discovery.dart%3A188%3A56%29%0A%3Casynchronous+suspension%3E%0A%235++++++MDnsVmServiceDiscovery.getVMServiceUriForLaunch+%28package%3Aflutter_tools%2Fsrc%2Fmdns_discovery.dart%3A433%3A50%29%0A%3Casynchronous+suspension%3E%0A%236++++++Future.any.onValue+%28dart%3Aasync%2Ffuture.dart%3A628%3A5%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60console%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.24.3%2C+on+macOS+15.0+24A335+darwin-arm64%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+3.24.3+on+channel+stable+at+%2FUsers%2Farivanshamal%2Fdevelopment%2Fflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+2663184aa7+%284+weeks+ago%29%2C+2024-09-11+16%3A27%3A48+-0500%0A++++%E2%80%A2+Engine+revision+36335019a8%0A++++%E2%80%A2+Dart+version+3.5.3%0A++++%E2%80%A2+DevTools+version+2.37.3%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+34.0.0%29%0A++++%E2%80%A2+Android+SDK+at+%2FUsers%2Farivanshamal%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+Platform+android-34%2C+build-tools+34.0.0%0A++++%E2%80%A2+Java+binary+at%3A+%2FApplications%2FAndroid+Studio.app%2FContents%2Fjbr%2FContents%2FHome%2Fbin%2Fjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+21.0.3%2B-79915917-b509.11%29%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+16.0%29%0A++++%E2%80%A2+Xcode+at+%2FApplications%2FXcode.app%2FContents%2FDeveloper%0A++++%E2%80%A2+Build+16A242d%0A++++%E2%80%A2+CocoaPods+version+1.15.2%0A%0A%5B%E2%9C%97%5D+Chrome+-+develop+for+the+web+%28Cannot+find+Chrome+executable+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%29%0A++++%21+Cannot+find+Chrome.+Try+setting+CHROME_EXECUTABLE+to+a+Chrome+executable.%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2024.2%29%0A++++%E2%80%A2+Android+Studio+at+%2FApplications%2FAndroid+Studio.app%2FContents%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+21.0.3%2B-79915917-b509.11%29%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.94.0%29%0A++++%E2%80%A2+VS+Code+at+%2FApplications%2FVisual+Studio+Code.app%2FContents%0A++++%E2%80%A2+Flutter+extension+version+3.98.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%284+available%29%0A++++%E2%80%A2+Arivan%E2%80%99s+iPhone+%28mobile%29++++++++%E2%80%A2+00008120-000210963E04201E+%E2%80%A2+ios++++++++++%E2%80%A2+iOS+18.1+22B5069a%0A++++%E2%80%A2+Hema+%28mobile%29+++++++++++++++++++%E2%80%A2+00008101-00115C1E1081401E+%E2%80%A2+ios++++++++++%E2%80%A2+iOS+17.6.1+21G93%0A++++%E2%80%A2+macOS+%28desktop%29+++++++++++++++++%E2%80%A2+macos+++++++++++++++++++++%E2%80%A2+darwin-arm64+%E2%80%A2+macOS+15.0+24A335+darwin-arm64%0A++++%E2%80%A2+Mac+Designed+for+iPad+%28desktop%29+%E2%80%A2+mac-designed-for-ipad+++++%E2%80%A2+darwin+++++++%E2%80%A2+macOS+15.0+24A335+darwin-arm64%0A%0A%5B%E2%9C%93%5D+Network+resources%0A++++%E2%80%A2+All+expected+network+resources+are+available.%0A%0A%21+Doctor+found+issues+in+1+category.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B3%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+300451adae589accbece3490f4396f10bdf15e6e%0A%23%23%23+Plugins%0Aconnectivity_plus-5.0.2%0Afile_selector_linux-0.9.3%0Afile_selector_macos-0.9.4%2B2%0Afile_selector_windows-0.9.3%2B3%0Afirebase_analytics-11.3.3%0Afirebase_analytics_web-0.5.10%2B2%0Afirebase_app_check-0.3.1%2B3%0Afirebase_app_check_web-0.1.3%2B2%0Afirebase_core-3.6.0%0Afirebase_core_web-2.18.1%0Afirebase_crashlytics-4.1.3%0Afirebase_messaging-15.1.3%0Afirebase_messaging_web-3.9.2%0Afirebase_performance-0.10.0%2B8%0Afirebase_performance_web-0.1.7%2B2%0Aflutter_local_notifications-17.2.3%0Aflutter_local_notifications_linux-4.0.1%0Aflutter_native_splash-2.4.1%0Aflutter_plugin_android_lifecycle-2.0.22%0Agoogle_sign_in-6.2.1%0Agoogle_sign_in_android-6.1.31%0Agoogle_sign_in_ios-5.7.7%0Agoogle_sign_in_web-0.12.4%2B2%0Aimage_picker-1.1.2%0Aimage_picker_android-0.8.12%2B14%0Aimage_picker_for_web-3.0.5%0Aimage_picker_ios-0.8.12%0Aimage_picker_linux-0.2.1%2B1%0Aimage_picker_macos-0.2.1%2B1%0Aimage_picker_windows-0.2.1%2B1%0Ain_app_update-4.2.3%0Amap_launcher-3.5.0%0Apackage_info_plus-8.0.2%0Apath_provider-2.1.4%0Apath_provider_android-2.2.10%0Apath_provider_foundation-2.4.0%0Apath_provider_linux-2.2.1%0Apath_provider_windows-2.3.0%0Apermission_handler-11.3.1%0Apermission_handler_android-12.0.12%0Apermission_handler_apple-9.4.5%0Apermission_handler_html-0.1.3%2B2%0Apermission_handler_windows-0.2.1%0Arecaptcha_enterprise_flutter-18.6.1%0Asign_in_with_apple-6.1.3%0Asign_in_with_apple_web-2.1.0%0Asqflite-2.3.3%2B2%0Aurl_launcher-6.3.0%0Aurl_launcher_android-6.3.11%0Aurl_launcher_ios-6.3.1%0Aurl_launcher_linux-3.2.0%0Aurl_launcher_macos-3.2.1%0Aurl_launcher_web-2.3.3%0Aurl_launcher_windows-3.1.2%0Awebview_flutter-4.9.0%0Awebview_flutter_android-3.16.8%0Awebview_flutter_wkwebview-3.15.0%0A%0A&labels=tool%2Csevere%3A+crash
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

## flutter doctor

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/arivanshamal/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/arivanshamal/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • Arivan’s iPhone (mobile)        • 00008120-000210963E04201E • ios          • iOS 18.1 22B5069a
    • Hema (mobile)                   • 00008101-00115C1E1081401E • ios          • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64 • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin       • macOS 15.0 24A335 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-10-08 09:33
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-10-08 09:33 UTC
Labels: in triage
