### ISSUE TITLE
flutter doctor --android-licenses fails on Command-line Tools 11.0

### ISSUE THREAD

**Issue by Actticus** [flutter/flutter#138132] opened 2023-11-09 06:13 UTC
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install v11 cmdline-tools
2. Try to run flutter doctor --android-licenses
3. Catch an error

### Actual results

This command works only with cmdline-tools v8, with rename folder to latest

https://stackoverflow.com/questions/76882205/error-linkageerror-occurred-while-loading-main-class-com-android-sdklib-tool-sd

### Logs

<details>
<summary>Logs</summary>

```console
PS C:\Users\username> flutter doctor --android-licenses -v
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
        java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Android sdkmanager tool was found, but failed to run
(C:\Users\salty\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:406:9)
<asynchronous suspension>
#2      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:26)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22621.2428], locale ru-RU)
    • Flutter version 3.13.9 on channel stable at C:\Users\salty\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\salty\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\salty\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.25)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33423.256
    • Windows 10 SDK version 10.0.19041.0
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code, 64-bit edition (version 1.84.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.92
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.44

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by Actticus** [comment] 2023-11-09 11:08
> Does that mean it will not work with versions greater than 8?

I'm not sure about all versions above 8, I tried on the latest one (11.0) and I was getting this error. I found this problem on stackoverflow, did a downgrade to 8, and everything worked

**Comment by huycozy** [comment] 2023-11-10 03:59
Thanks for spotting it. I can reproduce this issue after installing the latest Command-line Tools 11.0. 

<details>
<summary>Screenshot of installed SDK Tools</summary>

![image](https://github.com/flutter/flutter/assets/104349824/08ce222f-882e-41f0-bf4f-c1ce0ae8f03a)
</details>

Renaming Command-line Tools `8.0` to `latest` can work around this.

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.13.9 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (7 hours ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.17.0-1.0.pre.61, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.17.0-1.0.pre.61 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current
      Flutter SDK checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK
      checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5ff09c27f8 (56 minutes ago), 2023-11-07 03:35:26 -0500
    • Engine revision 99149d59cb
    • Dart version 3.3.0 (build 3.3.0-102.0.dev)
    • DevTools version 2.30.0-dev.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.84.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.105
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by andrewkolos** [comment] 2023-11-10 21:42
I was able to reproduce this using Commandline-Tools 11.0, but only after downgrading Android Studio to Electric Eel 2022.1.1.21 (which makes sense as this effectively downgrades the JDK that Flutter uses).

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel master, 3.17.0-5.0.pre.45, on Debian GNU/Linux rodete 6.5.6-1rodete4-amd64, locale en_US.UTF-8)
    • Flutter version 3.17.0-5.0.pre.45 on channel master at /usr/local/google/home/andrewkolos/Desktop/flutter
    ! The flutter binary is not on your path. Consider adding /usr/local/google/home/andrewkolos/Desktop/flutter/bin to your path.
    ! Warning: `dart` on your path resolves to /usr/lib/google-dartlang/bin/dart, which is not inside your current Flutter SDK checkout at /usr/local/google/home/andrewkolos/Desktop/flutter. Consider adding /usr/local/google/home/andrewkolos/Desktop/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d42d639924 (46 minutes ago), 2023-11-10 13:41:18 -0500
    • Engine revision 77349dc8e2
    • Dart version 3.3.0 (build 3.3.0-113.0.dev)
    • DevTools version 2.30.0-dev.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /usr/local/google/home/andrewkolos/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/local/google/home/andrewkolos/Desktop/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2022.1)
    • Android Studio at /usr/local/google/home/andrewkolos/Desktop/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.82.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.67.20230601

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 6.5.6-1rodete4-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```
</details>

I wonder if Android Studio itself can encounter these type of situations—where the Java runtime bundled with Android Studio is too out-of-date to run the latest installed version of the Android SDK command line tools.

I'm passing this back to the Android team, since I believe they have experience with similar classes of issues that have come up in the past. I'll stay in the loop on this issue.

**Comment by andrewkolos** [comment] 2023-11-15 22:20
> I'm passing this back to the Android team since I believe they have experience with similar classes of issues that have come up in the past.

I've learned this is not the case (thanks @reidbaker), so I am personally looking into this issue again.

As per the logs provided in the original comment, this issue is caused when the JDK bundled with Android Studio (which `flutter` will always use unless `flutter config --jdk-dir` is set) is version 11, but the JDK that was used to compile `sdkmanager` was version 17[^1].

I assume this type of situation is rare, because most folks typically accept licenses soon after installing Android Studio[^2]. In this case, there shouldn't be a discrepancy between the JDK versions involved here. At least, this is what I imagine to be the case.

Since this situation is probably rare, I think a sufficient fix for this issue is for the `flutter` CLI tool to detect this error and display a helpful message and what the user can do to solve their issue (ideally, downloading a more recent version of Android Studio).

[^1]: See https://javaalmanac.io/bytecode/versions/ for a mapping of JDK versions to class file versions.
[^2]: I wonder if Android Studio itself could run into this type of situation. It's probably not worth the time to investigate though.

**Comment by andrewkolos** [comment] 2023-11-20 23:20
Theoretically, we could avoid this issue by, instead of running `sdkmanager`, simply checking for existence of the `licenses` directory within the Android SDK installation directory (credit to @dnfield for the idea). For context, `sdkmanager --licenses` (which we invoke in `flutter doctor --android-licenses`), generates this `licenses` directory and creates files within it for each license agreement the user accepts. However, this means that checking for the existence of `licenses` is not sufficient, as it will be generated even if the user accepts only some of the license agreements. We could check for each of the files within the directory, but if this list ever changes, this functionality would break. I don't have enough confidence in the fact that this list won't change, so I don't feel comfortable with having `flutter` depend on it.

To come back to the solution I proposed in my previous comment:

> I think a sufficient fix for this issue is for the flutter CLI tool to detect this error and display a helpful message and what the user can do to solve their issue (ideally, downloading a more recent version of Android Studio).

I still think this is sufficient.

**Closed** 2023-11-21 23:16 UTC
Labels: platform-android, tool, t: flutter doctor, has reproducible steps, P2, fyi-android, team-tool, triaged-tool, found in release: 3.13, found in release: 3.17
