### ISSUE TITLE
Mac_android microbenchmarks execution time increased by 50% over the past year

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#131701] opened 2023-08-01 19:05 UTC
The execution time has increased from 850s (14min) to 1300s (21min) over the past year.
A recent build with 21 min: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/11765/overview
An old build (back to 04/2022) with 13 mins: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/4500/overview
![Screenshot 2023-08-01 at 12 01 23 PM](https://github.com/flutter/flutter/assets/54558023/bc98f1e4-5764-45da-b12b-8e88aa24c869)

@zanderso Do you mind taking a look?

**Comment by zanderso** [comment] 2023-08-01 19:18
In that timeframe the number of microbenchmarks increased from 15 to 20, so an increase in runtime from ~14 minutes to ~21 minutes seems expected. Closing as working as intended, but if there's some larger issue here that a long runtime for this job is contributing to, we should talk about that.

**Closed by zanderso** 2023-08-01 19:18 UTC
Labels: team-engine
