### ISSUE TITLE
RTL text rendering glitch on web

### ISSUE THREAD

**Issue by ialhashim** [flutter/flutter#69396] opened 2020-10-30 12:40 UTC
When hovering over an interactive element (e.g. a regular FlatButton), the text is drawn incorrectly as seen here (GIF):

![ezgif-7-ec426dbce091](https://user-images.githubusercontent.com/2434978/97706922-88bf8900-1ac7-11eb-9e79-11d6f826477a.gif)

Digging a bit more into it, it seems that when displaying the element as a `flt-dom-canvas` everything looks good but when its turned into a canvas element `flt-canvas` and checking the `CanvasRenderingContext2D.direction` it seems it is set to `ltr` even though the theme of the app is `rtl`. So bottom line, this optimization seems to be broken for RTL.

Testing with `FLUTTER_WEB_USE_SKIA` behaves correctly but it introduces many other different unrelated issues.

<details>
  <summary>Flutter 1.23.0-18.1.pre</summary>
  
```
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (2 weeks ago) • 2020-10-15 12:04:33 -0700      
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
```
</details>

**Comment by TahaTesser** [comment] 2020-10-30 15:51
Hi @ialhashim 
For me, RTL doesn't render properly using simple FlatButton with mixed Text as shown in your GIF

<img width="167" alt="Screenshot 2020-10-30 at 9 20 23 PM" src="https://user-images.githubusercontent.com/48603081/97726912-c0ddc080-1af5-11eb-878d-8aee905730bc.png">


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: FlatButton(
          child: Text('Hello رسالة (4)'),
          onPressed: () {},
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 198df796aa (2 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (4 available)            
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.1
    • iPhone 12 (mobile)   • BAFAB765-173F-4B78-93AC-F6FB6E6783C3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Web Server (web)     • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```

</details>

Can you please provide your  `flutter run --debug --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome -v`  and a complete reproducible minimal code sample
Thank you

**Comment by ialhashim** [comment] 2020-10-30 16:28
Here is a complete reproducible minimal code sample:
```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: [
        GlobalCupertinoLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [Locale("ar")],
      locale: Locale("ar"),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              child: Text('message (4) رسالة'),
              onPressed: () {},
            ),
          ],
        ),
      ),
    );
  }
}
```

When running `flutter run --debug --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome -v` I get the same thing with boxes (i.e. missing Arabic letters). I am including the output here.

<details>
<summary>Complete reproducible minimal code sample</summary>

```
[  +89 ms] executing: [F:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 198df796aa80073ef22bdf249e614e2ff33c6895
[        ] executing: [F:\flutter\flutter/] git tag --points-at HEAD
[  +34 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.23.0-18.1.pre
[   +8 ms] executing: [F:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [F:\flutter\flutter/] git ls-remote --get-url origin
[  +23 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [F:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +41 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +58 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +32 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +117 ms] Generating F:\Temp\rtl_test\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +29 ms] List of devices attached
[  +46 ms] Launching lib\main.dart on Chrome in debug mode...
[  +14 ms] List of devices attached
[  +75 ms] Updating assets
[  +67 ms] Syncing files to device Chrome...
[  +35 ms] Generating F:\Temp\rtl_test\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +44 ms] <- reset
[   +7 ms] F:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev F:\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root F:\flutter\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true -DFLUTTER_WEB_USE_SKIA=true --output-dill C:\Users\User\AppData\Local\Temp\flutter_tools.b25ed98e\flutter_tool.b58cc77e\app.dill --libraries-spec file:///F:/flutter/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\User\AppData\Local\Temp\flutter_tools.b25ed98e\flutter_tools.cefc459 --filesystem-scheme org-dartlang-app --initialize-from-dill build\dfea9bfe94cb64da780a8ef62c567803.cache.dill.track.dill --platform file:///F:/flutter/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[   +5 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+7880 ms] Syncing files to device Chrome... (completed in 7,966ms, longer than expected)
[        ] Synced 30.4MB.
[        ] <- accept
[        ] Caching compiled dill
[ +261 ms] Using Opening in existing browser session.

[ +164 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:53660/devtools/browser/a6e95dad-80f0-41e8-942a-44efec5b8853
[+5927 ms] Debug service listening on ws://127.0.0.1:53693/PNhqqbTWEM4=

[ +191 ms] Debug service listening on ws://127.0.0.1:53693/PNhqqbTWEM4=
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+5942 ms] Stopped debug service on ws://127.0.0.1:53693

[  +34 ms] Application finished.
[   +3 ms] "flutter run" took 21,016ms.
[ +256 ms] ensureAnalyticsSent: 253ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +7 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```
</details>
With `FLUTTER_WEB_USE_SKIA=false` we can see the letters but the switching issue is there.

**Comment by TahaTesser** [comment] 2020-11-02 09:46
Hi @ialhashim 
Forgot about localization, thanks for the code sample, I can reproduce the issue

| HTML | Canvaskit |
| --------------- | --------------- |
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/97853331-f9f87980-1d1d-11eb-83a5-e6132307aae1.gif) | ![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/97853269-e3eab900-1d1d-11eb-966d-a652f41fb992.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:i18n_example/generated/i18n.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final i18n = I18n.delegate;

    return MaterialApp(
      onGenerateTitle: (context) => I18n.of(context).title,
      theme: ThemeData.dark(),
      home: MyHomePage(),
      locale: Locale('ar', 'SA'),
      localizationsDelegates: [
        i18n,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: i18n.supportedLocales,
      localeResolutionCallback: i18n.resolution(
        fallback: Locale('en', 'US'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              child: Text('message (4) رسالة'),
              onPressed: () {},
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\Code\flutter_beta
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.56

• No issues found!
```
```bash
[✓] Flutter (Channel dev, 1.24.0-6.0.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-6.0.pre at C:\Code\flutter_dev
    • Framework revision 13896b3bd1 (4 days ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.56

• No issues found!
```

```bash
[✓] Flutter (Channel master, 1.24.0-7.0.pre.47, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-7.0.pre.47 at C:\Code\flutter_master
    • Framework revision 2f18e0b23d (18 hours ago), 2020-11-01 20:58:04 +0530
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.56

• No issues found!

```

</details>

**Comment by yjbanov** [comment] 2020-11-05 23:13
The missing fonts issue for canvaskit is being worked on. The non-canvaskit issue seems text layout related.

**Comment by ialhashim** [comment] 2020-11-10 08:36
Is there a way to globally disable this `flt-canvas` optimization for a specific type of widget? 

I really wish to know an easy way to just temporarily disable this for `Text` widget and have a perfect looking web app.

**Comment by mdebbar** [comment] 2020-11-19 22:17
Tried using the `[direction](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/direction)` property on canvas2d but that didn't work, and it doesn't have good support across browsers anyway. So we will need to programmatically detect and position the RTL text blocks.

**Comment by TahaTesser** [comment] 2021-01-04 08:41
Hi @yjbanov 
Closed duplicate for canvaskit font issue https://github.com/flutter/flutter/issues/73165
You mentioned it's being worked on in https://github.com/flutter/flutter/issues/69396#issuecomment-722698952
Can you please point to the issue/PR so I can reference it, can't find any obvious issue tracking this. 
Thank you

**Comment by yjbanov** [comment] 2021-01-06 17:44
@TahaTesser we had several reports. Here's one example: https://github.com/flutter/flutter/issues/53897. Although it's marked as fixed, the fix had to be rolled back due to a regression. @hterkelsen is working on a new iteration.

**Comment by ahmednfwela** [comment] 2021-06-13 12:14
Any news on this?

**Closed** 2021-06-29 22:30 UTC
Labels: P3, a: internationalization, a: typography, e: web_html, engine, found in release: 1.24, has reproducible steps, platform-web, severe: regression

**Comment by kiaxseventh** [comment] 2021-07-21 08:50
this issue has in stable 2.2.3 just on web html render mode
