### ISSUE TITLE
Can iOS run Flutter AOT in simulator?

### ISSUE THREAD

**Issue by ryansong** [flutter/flutter#23775] opened 2018-10-31 12:53 UTC
I have viewed the guide https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps, it works.

And so I want to use the output file (framework& asset )to integrate to existing iOS APP. It seems simulator not support AOT ant it run in debug model with a VM.

**Comment by zoechi** [comment] 2018-10-31 13:45
Please add the output of `flutter doctor -v`.

**Comment by ryansong** [comment] 2018-10-31 16:29
Building flutter tool...
[✓] Flutter (Channel master, v0.10.2-pre.121, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.10.2-pre.121 at /usr/local/flutter
    • Framework revision b20e7a2671 (2 hours ago), 2018-10-31 07:06:05 -0700
    • Engine revision 3a67757300
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ryan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected device (2 available)
    • iPhone 7 • 7e30d5cefe20e2e0d835de2261c15cbfea691252 • ios • iOS 11.3.1
    • iPhone 6 • 2BEB3B83-CFC4-4BFF-850D-D7FB9B019A2A     • ios • iOS 8.2 (simulator)

**Comment by cbracken** [comment] 2019-11-06 21:23
Closing as duplicate of https://github.com/flutter/flutter/issues/11754

**Closed by cbracken** 2019-11-06 21:23 UTC
Labels: a: existing-apps, engine
