### ISSUE TITLE
MacOS schemes are not working

### ISSUE THREAD

**Issue by konstantintuev** [flutter/flutter#66258] opened 2020-09-21 11:40 UTC
## Steps to Reproduce

1. Run `flutter run` targeting any custom build flavor.
2. Fail

Adding the following code to `macos_assemble.sh` and building the macos app without a flavor before that produces a working app:
```
if [[ $build_mode == *"debug"* ]]; then
  build_mode="debug"
fi
if [[ $build_mode == *"release"* ]]; then
  build_mode="release"
fi
if [[ $build_mode == *"profile"* ]]; then
  build_mode="profile"
fi
```

<details>
  <summary>Logs</summary>

```
No target named "release-customScheme_macos_bundle_flutter_assets" defined.
Command PhaseScriptExecution failed with a nonzero exit code
```

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.264, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.264 at /Users/konstantintuev/flutter
    • Framework revision 3e6863ab2b (2 days ago), 2020-09-18 21:05:27 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/konstantintuev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/konstantintuev/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7206

[!] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
      x86_64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

! Doctor found issues in 2 categories.
```

</details>

**Comment by stuartmorgan** [comment] 2020-09-21 13:33
Duplicate of https://github.com/flutter/flutter/issues/64088

**Closed by stuartmorgan** 2020-09-21 13:33 UTC
