### ISSUE TITLE
Problem Dart CLI isolate

### ISSUE THREAD

**Issue by Faelnas1** [flutter/flutter#100897] opened 2022-03-28 13:56 UTC
Hi guys, I'm recently starting the study in Flutter, I can't run emulator on my mac and the problem is this one below, I made several attempts to fix it like deleting the cache and reinstalling the sdk.
![Captura de Tela 2022-03-28 às 14 54 36](https://user-images.githubusercontent.com/102529919/160413585-38f54c0a-bfe8-48ce-99dd-151d41b297d0.png)

Servicess-Air:~ servicesline$ flutter doctor
Building flutter tool...
Failed to start the Dart CLI isolate
(null).
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Failed to start the Dart CLI isolate
(null).
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Failed to start the Dart CLI isolate

**Comment by darshankawar** [comment] 2022-03-29 05:39
Closing this as a duplicate of https://github.com/flutter/flutter/issues/87867. Please follow-up in it for further updates.

**Closed by darshankawar** 2022-03-29 05:39 UTC
Labels: in triage

**Comment by Faelnas1** [comment] 2022-03-29 15:21
I still haven't been able to solve the problem
