### ISSUE TITLE
type '(dynamic) => dynamic' is not a subtype of type '(IndividualLessonItem) => Widget' of 'f'

### ISSUE THREAD

**Issue by YFeoktistov** [flutter/flutter#47649] opened 2019-12-23 06:10 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment] 2019-12-23 07:24
Hello @YFeoktistov !

Thank you for posting.
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-12-23 07:24 UTC
