### ISSUE TITLE
[macOS] Entering text at a cursor position is broken when using some non-English language inputs

### ISSUE THREAD

**Issue by blono** [flutter/flutter#77791] opened 2021-03-10 10:46 UTC
## Steps to Reproduce

1. Run `git clone https://github.com/blono/flutter_test_field_test.git` (I really wanted to name it test_field_text, but it's mistakenly named test_field_test...😭)
2. Run `cd flutter_test_field_test`
3. Run `flutter run -d macos`
4. See attached movie

https://user-images.githubusercontent.com/743024/110617098-a4a30c00-81d8-11eb-8fa6-2b5df861f5b4.mov

<details>

```
flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.180, on macOS 11.2.3 20D91
    darwin-x64, locale ja-JP)
    • Flutter version 2.1.0-11.0.pre.180 at /usr/local/flutter
    • Framework revision be8989f185 (3 hours ago), 2021-03-09 23:31:02 -0800
    • Engine revision 7764b5c55f
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 2 categories.
```

</details>

**Comment by blono** [comment] 2021-03-10 11:12
This bug has been occurring for about a month now, though I can't remember it very well.
It was working fine a couple of months ago.

**Comment by TahaTesser** [comment] 2021-03-10 13:21
Hi @blono 
Thanks for filing the issue, I can reproduce with Japanese  and Arabic as well and sometimes with Korean too, tested tons of times to be sure

### `dev` and `master`
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/48603081/110635302-f21b7b00-81d0-11eb-8c27-de219302ca29.gif)


###  `stable` and `beta`　(input  style a little bit different here when using the method on macOS, first you type then hit return key to insert text) but no issue when testing
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/48603081/110635393-0c555900-81d1-11eb-938f-8ece283b8950.gif)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.82
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```


```bash
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_beta
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.82
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```


```bash
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.3 20D91 darwin-x64,
    locale en-GB)
    • Flutter version 2.1.0-10.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision cc9b78fc5c (13 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.82
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.180, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.180 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision be8989f185 (6 hours ago), 2021-03-09 23:31:02 -0800
    • Engine revision 7764b5c55f
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.82
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```

</details>


Thank you

**Comment by gspencergoog** [comment] 2021-03-11 19:24
This is going to be fixed when https://github.com/flutter/engine/pull/24866 lands in the Framework.

**Comment by cbracken** [comment] 2021-03-12 07:17
The above patch is landed on master of engine. It has not yet rolled to the framework, but should do so within the next day or two.

**Comment by cbracken** [comment] 2021-03-12 07:34
Just as FYI, this won't get the IME composing menu positioned correctly, but we're working on that separately as part of https://github.com/flutter/flutter/issues/30660

**Comment by blono** [comment] 2021-03-13 06:34
I was able to confirm the fix in the following environment, thank you.

<details>
flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-13.0.pre.83, on macOS 11.2.3 20D91
    darwin-x64, locale ja-JP)
    • Flutter version 2.1.0-13.0.pre.83 at /usr/local/flutter
    • Framework revision c3d0f60407 (3 hours ago), 2021-03-12 19:14:05 -0800
    • Engine revision dc73780f69
    • Dart version 2.13.0 (build 2.13.0-134.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 2 categories.
</details>

**Comment by cbracken** [comment] 2021-03-13 07:06
Thank you. I did discover this issue today https://github.com/flutter/flutter/issues/78061, which is caused by some recent changes to keydown/keyup event handling. I'm working with the author of those changes to come up with a fix.

**Comment by cbracken** [comment] 2021-03-13 07:07
I'm going to close this issue since this specific failure is resolved. I'm leaving #78061 and #30660 open, since those remain open.

**Closed by cbracken** 2021-03-13 07:07 UTC
Labels: P4, a: desktop, a: internationalization, f: material design, found in release: 2.1, framework, has reproducible steps, platform-mac, severe: regression
