### ISSUE TITLE
Cupertino route back gesture width

### ISSUE THREAD

**Issue by Sergey04IO** [flutter/flutter#159891] opened 2024-12-06 16:55 UTC
### Use case

Cupernito back gesture width is hardcoded in cupertino/route.dart file in _kBackGestureWidth constant.

### Proposal

It would be nice to have a possibility to override the back gesture width value.

**Comment by darshankawar** [comment] 2024-12-09 07:20
Closing as duplicate of https://github.com/flutter/flutter/issues/46598. Please upvote it and follow-up in it for further updates.

**Closed by darshankawar** 2024-12-09 07:20 UTC
Labels: in triage
