### ISSUE TITLE
onTap in GestureDetector is taking a value less, but Text is taking correct, both used in the same loop

### ISSUE THREAD

**Issue by gitman-2021** [flutter/flutter#97861] opened 2022-02-05 11:09 UTC
Hello,
In the following code, ```Text(subjects[address])``` is printing the correct value, but ```GestureDetector( onTap: ``` is taking the same value for the whole ```Row```, and incrementing the values of ```subject``` and ```address``` directly by 2 and 6 respectively, at exit from inner loop,

```
Column(
                        children: [
                          for (int i = 0, address = ((arr[1] * (6 * 3))), subject = 0; i < 3; i++)
                            Row(
                              children: [
                                for (int j = 0; j < 2; address += 3, subject++, j++)
                                 GestureDetector(
                                        child: Text(subjects[address]),
                                        onTap: () async {
                                          List<String> data =
                                              await File("$privateStoragePath/data.txt").readAsLines();
                                          showModalBottomSheet(
                                            context: context,
                                            builder: (BuildContext context) {
                                              return SubjectPage(
                                                subject: subject,
                                                subjectName: subjects[address],
                                                subjectFullName: subjects[(address + 1)],
                                                subjectDes: subjects[(address + 2)],
                                                data: data,
                                              );
                                            },
                                          );
                                        },
                                      ),
                              ],
                            ),
                        ],
                      ),
```

Thanking you...

**Comment by darshankawar** [comment] 2022-02-07 09:25
@gitman-2021 
Looking at your code sample and description, it is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, because it doesn't seem to highlight any bug or description isn't clear as what exactly the issue is. If you disagree, use the new issue template and fill out requested details.

**Closed by darshankawar** 2022-02-07 09:25 UTC
Labels: in triage
