### ISSUE TITLE
webview_flutter 0.3.17

### ISSUE THREAD

**Issue by keyalsolution** [flutter/flutter#41050] opened 2019-09-22 09:02 UTC
## Proposal

currently using (webview_flutter 0.3.17) plugin  it does not have  webview with html5 full screen video player. webview with transparent background .

**Comment by TahaTesser** [comment] 2020-03-19 15:20
Duplicate of [#27101](https://github.com/flutter/flutter/issues/27101)

**Closed by TahaTesser** 2020-03-19 15:20 UTC
Labels: p: webview, plugin, severe: new feature
