### ISSUE TITLE
Flutter 3.0.3 : dependency version solving failed for flutter_test and flutter_localizations which both depend on path 1.8.1

### ISSUE THREAD

**Issue by pureimpro** [flutter/flutter#106609] opened 2022-06-25 15:21 UTC
After updating package **path 1.8.1 to 1.8.2**, both **flutter_test** and **flutter_localizations** **fail version solving** :

Running "flutter pub get" in flutterApp...                 
Because every version of **flutter_test** from sdk depends on **path 1.8.1** and myApp depends on **path ^1.8.2**, flutter_test from sdk is **forbidden**.
So, because myApp depends on flutter_test from sdk, **version solving failed**.
pub get failed (1; So, because myApp depends on flutter_test from sdk, version solving failed.)
exit code 1

Running "flutter pub get" in flutterApp...                 
Because myApp depends on **flutter_localizations** from sdk which depends on **path 1.8.1**, path 1.8.1 is required.
So, because myApp depends on **path ^1.8.2**, **version solving failed**.
pub get failed (1; So, because myApp depends on path ^1.8.2, version solving failed.)
exit code 1

PS C:\Users\dev\app> **flutter doctor -v**
[√] **Flutter (Channel stable, 3.0.3,** on Microsoft Windows [version 10.0.19044.1766], locale fr-FR)
    • **Flutter version 3.0.3** at C:\Users\dev\myApp\flutter-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (3 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at C:\Users\dev\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: C:\Users\dev\myApp\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Users\dev\myApp\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\dev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
PS C:\Users\dev\app>

**Comment by stuartmorgan** [comment] 2022-06-25 18:15
Duplicate of https://github.com/flutter/flutter/issues/104181

**Closed by stuartmorgan** 2022-06-25 18:15 UTC
