### ISSUE TITLE
image_picker - iOS - during camera preview, you can still interact with the (hidden) widgets below

### ISSUE THREAD

**Issue by oodavid** [flutter/flutter#69913] opened 2020-11-05 20:01 UTC
## Steps to Reproduce

1. Use `image_picker: ^0.6.7+11` on a real iOS device (you need the camera)
2. Take a photo
3. _Don't_ close the preview screen (where it says Retake / Use Photo)
4. You can now interact with app widgets, even though the preview is visible

This may be a related issue - https://github.com/flutter/flutter/issues/54251

## Demo

Below are two recordings demonstrating the issue. It was a customers iPhone 8, we've had similar reports on all iOS devices.

I can't replicate this on the simulator since it requires a camera. Nor do I have access to an iPhone at the moment.

### Video 1 - Typing through the preview

Demonstration of interacting with Widgets below the camera preview.

I manage to fill out a text input while the camera preview is still open.

https://www.youtube.com/watch?v=JddPDSKlEgk

### Video 2 - Two Camera Instances

Here I create *two* camera instances by the same method - interacting with the widgets below the preview.

In this state it's not possible to return to the App as the *first* camera instance cannot be closed.

https://youtu.be/nGTTdfLhhGA

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.20.3 at /Users/david/Development/flutter
    • Framework revision 216dee60c0 (9 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/david/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 8 Plus (mobile) • 4F6B6FB8-B9F1-431F-B67F-AC9074C6A2DC • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-11-06 09:33
Hi @oodavid 
This is an old known issue, a duplicate of https://github.com/flutter/flutter/issues/39218, which I just updated to better reflect the actual behavior.

Feel free to add your investigation to the original issue 
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-06 09:33 UTC
