### ISSUE TITLE
SingleChildScrollView iOS vs Android discrepancies

### ISSUE THREAD

**Issue by adamsowinski** [flutter/flutter#34229] opened 2019-06-11 10:42 UTC
I'm using `SingleChildScrollView` for a login screen. When I test on Android and iOS - both platforms behave in a different way. 

On Android if I tap on a text field and the keyboard pops up I can scroll the view to reveal what is obstructed. When I dismiss the keyboard. The view scrolls itself back. When the keyboard is not on screen I can't scroll the content because it fits the screen.

On iOS if I do the same, and when I dismiss the keyboard the content doesn't scroll itself back and when the keyboard is not on screen I can scroll the content even if it fits the screen. What is important to note is that if I interact with the text field again and keyboard pops up - if I do not scroll the content and dismiss the keyboard - the content is not anymore scrollable. That is very weird.

**Comment by Kinnear** [comment] 2019-08-06 02:26
I'm having this issue as well! It works on android but it doesn't work in iOS. Anyone else having the same issue?

**Comment by VladyslavBondarenko** [comment] 2020-04-22 14:20
@adamsowinski 
I can't reproduce it. After dismissing keyboard content is scrolled back the same as on Android.

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: SingleChildScrollView(
          child: Container(
            color: Colors.grey,
            height: 600,
            child: Center(
              child: TextField(),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision 84c84fb249 (31 hours ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

 
[✓] Connected device (6 available)            
    • Redmi Note 7              • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.4.5
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 81.0.4044.122
    • Web Server                • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

</details>

Seems to be fixed, closing.
Could everyone who still has this problem please file a new issue with the exact descriptions, minimal reproducible sample code and the output of 'flutter doctor -v'  please.

**Closed by VladyslavBondarenko** 2020-04-22 14:20 UTC
Labels: f: scrolling, framework
