### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by shijinthottiyil** [flutter/flutter#142038] opened 2024-01-23 10:32 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2499:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2470:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:868:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:887:49)
#5      FlutterVmService.flutterDebugDumpFocusTree (package:flutter_tools/src/vmservice.dart:645:50)
#6      ResidentHandlers.debugDumpFocusTree (package:flutter_tools/src/resident_runner.dart:771:53)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1830:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.1, on Microsoft Windows [Version 10.0.22000.2538], locale en-AE)
    [32m•[39m Flutter version 3.16.1 on channel stable at C:\Users\WORK\Documents\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 7f20e5d18c (8 weeks ago), 2023-11-27 09:47:30 -0800
    [32m•[39m Engine revision 22b600f240
    [32m•[39m Dart version 3.2.1
    [32m•[39m DevTools version 2.28.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at C:\Users\WORK\AppData\Local\Android\sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.23)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.33214.272
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m VS Code (version 1.85.2)
    [32m•[39m VS Code at C:\Users\WORK\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Nokia C01 Plus (mobile) • 192.168.29.201:45459 • android-arm    • Android 11 (API 30)
    [32m•[39m Windows (desktop)       • windows              • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    [32m•[39m Chrome (web)            • chrome               • web-javascript • Google Chrome 120.0.6099.225
    [32m•[39m Edge (web)              • edge                 • web-javascript • Microsoft Edge 120.0.2210.144

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2524052335ec76bb03e04ede244b071f1b86d190

**Comment by dam-ease** [comment] 2024-01-23 10:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/102994

**Closed by dam-ease** 2024-01-23 10:59 UTC
Labels: in triage
