### ISSUE TITLE
When I run flutter run I am getting this issue Flutter (Channel unknown, v0.0.0-unknown, on Microsoft Windows [Version 10.0.18362.657], locale en-IN)     X Command exited with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso       Standard error: fatal: your current branch 'stable' does not have any commits yet

### ISSUE THREAD

**Issue by AkilaKuppuswamy** [flutter/flutter#51098] opened 2020-02-20 04:42 UTC

**Comment by jonahwilliams** [comment] 2020-02-20 04:46
Duplicate of https://github.com/flutter/flutter/issues/50902

**Closed by jonahwilliams** 2020-02-20 04:46 UTC

**Comment by nix007nitin** [comment] 2020-03-12 08:55
I'm getting the same issue:

Running pub upgrade...
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, v0.0.0-unknown, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    X Command exited with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
      Standard error: fatal: unterminated line in .git/packed-refs: ...


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
PS E:\project_apps\bazarpanda>
