### ISSUE TITLE
 IOS folder is not generated in a new flutter project from Android Studio or flutter CLI

### ISSUE THREAD

**Issue by keval-devani** [flutter/flutter#110072] opened 2022-08-23 10:36 UTC
## Steps to Reproduce

1. Android studio new flutter project
2. From terminal `flutter create .`
3. `flutter create -i swift -a kotlin drift_demo` this command generate all other folders except ios

It's creating all other platform folder but not ios. 
I tried to downgrade flutter version but still not able to create flutter project with ios folder. 
I'm attaching flutter create . -v and pub_log.txt logs

## Logs

<details>
<summary>flutter doctor -v</summary>

```
Running "flutter pub get" in flutter_tools...                      16.9s
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.4 20G417 darwin-x64, locale en-US)
    • Flutter version 3.0.5 at /Users/imac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/imac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.4 20G417 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 104.1.42.97

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

[flutter create . -v log](https://github.com/flutter/flutter/files/9401752/flutterLog.txt)

[pub_log.txt](https://github.com/flutter/flutter/files/9401765/pub_log.txt)

**Comment by maheshmnj** [comment] 2022-08-23 11:38
Hi @keval-devani, Thanks for filing the issue, I am unable to reproduce the issue, Please ensure your workspace has not accidentally hidden/excluded the ios folder. 

Can you please run the below commands and share the output

```bash
flutter create -i swift -a kotlin drift_demo
cd drift_demo
ls
```


#### logs

```
mahesh@Maheshs-MacBook-Air-M1 Desktop % flutter create -i swift -a kotlin drift_demo
Signing iOS app for device deployment using developer identity: "Apple Development: maheshmn121@gmail.com (FLXW3987AP)"
Creating project drift_demo...
Running "flutter pub get" in drift_demo...                       2,065ms
Wrote 127 files.

All done!
In order to run your application, type:

  $ cd drift_demo
  $ flutter run

Your application code is in drift_demo/lib/main.dart.

mahesh@Maheshs-MacBook-Air-M1 Desktop % cd drift_demo 
mahesh@Maheshs-MacBook-Air-M1 drift_demo % ls
README.md               android                 ios                     linux                   pubspec.lock            test                    windows
analysis_options.yaml   drift_demo.iml          lib                     macos                   pubspec.yaml            web
mahesh@Maheshs-MacBook-Air-M1 drift_demo % 
```


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by keval-devani** [comment] 2022-08-23 11:59
Hey @maheshmnj, Thanks for the response. 

This is the output log from commands

```
Last login: Tue Aug 23 17:24:58 on ttys003
imac@kds-iMac test % flutter create -i swift -a kotlin drift_demo && cd drift_demo && ls -a
Creating project drift_demo...
Running "flutter pub get" in drift_demo...                       1,911ms
Wrote 89 files.

All done!
In order to run your application, type:

  $ cd drift_demo
  $ flutter run

Your application code is in drift_demo/lib/main.dart.

.			.idea			analysis_options.yaml	linux			test
..			.metadata		android			macos			web
.dart_tool		.packages		drift_demo.iml		pubspec.lock		windows
.gitignore		README.md		lib			pubspec.yaml
imac@kds-iMac drift_demo % 

```

**Comment by maheshmnj** [comment] 2022-08-23 12:13
@keval-devani  Can you try running the below command in the existing project?
```
flutter create . --platforms ios
```
if the above works and if it is only failing in a newly created project then run the below command which should enable IOS project too.

```
flutter config --enable-ios
``` 

And after running the second command check if it works by running `flutter create` command

**Comment by keval-devani** [comment] 2022-08-23 12:27
This command helped me `flutter config --enable-ios` for my existing projects and new projects also. Now it's working. 

Thank you @maheshmnj

**Comment by maheshmnj** [comment] 2022-08-23 12:50
Thanks for the update closing based on the above response.

**Closed** 2022-08-23 12:50 UTC
Labels: in triage
