### ISSUE TITLE
Make my font follow the system

### ISSUE THREAD

**Issue by Robert-Stackflow** [flutter/flutter#125670] opened 2023-04-28 06:34 UTC
How to make my font follow the system font style instead of using the default font

**Comment by Robert-Stackflow** [comment] 2023-04-28 07:08
Same with #48381

**Comment by darshankawar** [comment] 2023-04-28 08:46
@Robert-Stackflow 
Since there's an already open proposal for it as you linked, please follow-up in it for further updates. Closing this as a duplicate of https://github.com/flutter/flutter/issues/48381

**Closed by darshankawar** 2023-04-28 08:46 UTC
Labels: in triage
