### ISSUE TITLE
[camera] Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference

### ISSUE THREAD

**Issue by sumitagadhvi** [flutter/flutter#146423] opened 2024-04-08 13:25 UTC
### Steps to reproduce

this crash is from play console crash and ANR i tried to reproduce it but its device specific and its reproducing sometimes

### Expected results

it should not throw crash like this obviously.

### Actual results

its showing crash error like below: 

java.lang.NullPointerException
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.close()' on a null object reference
  at io.flutter.plugins.camera.Camera.closeCaptureSession (Camera.java)
  at io.flutter.plugins.camera.Camera$1.onClosed (Camera.java)
  at android.hardware.camera2.impl.CameraDeviceImpl$5.run (CameraDeviceImpl.java:215)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:264)
  at android.os.HandlerThread.run (HandlerThread.java:67)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 12.7.1 21G920 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.63.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-04-09 06:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/114012

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-04-09 06:28 UTC
Labels: in triage
