### ISSUE TITLE
Support float rgb as buffer texture for shaders

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#142874] opened 2024-02-04 02:49 UTC
### Use case

Recreate this:
https://twitter.com/anshrathodfr/status/1753746769849249826?t=dQpyh7xnX_z6Eiz7_GZKEg&s=19 

![Screenshot_20240203_234812_X](https://github.com/flutter/flutter/assets/351125/baaaad2a-f9ec-4637-9bb6-e586550cfee4)

### Proposal

Apparently "Flutter can read the canvas only with uchar RGBA (4 bytes)" 

https://twitter.com/lildeimos/status/1753831353177518168?t=HyQb7fSeoVQPFYPXqytgKA&s=19

**Comment by jonahwilliams** [comment] 2024-02-04 03:08
See also: https://github.com/flutter/flutter/issues/55092

* https://github.com/flutter/flutter/issues/127852
* https://github.com/flutter/flutter/issues/127855

Flutter can do this but it is hardware restricted and only implemented in Impeller. I'm closing this issue as I believe its a duplicate of the others, but if there is something more specific we're missing please let me know.

**Closed by jonahwilliams** 2024-02-04 03:08 UTC

**Comment by bernaferrari** [comment] 2024-02-04 03:17
Oh, I didn't know it was Color only working with int. Thanks.

**Comment by jonahwilliams** [comment] 2024-02-06 04:37
This doesn't really have anything to do with the dart:ui Color type, if you are talking about using the fragment program API. Instead you need the display to support HDR content, and the renderer to be able to request that content. This is supported on Impeller on iOS, but not yet on Android.
