### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by XuFeng-Li** [flutter/flutter#127782] opened 2023-05-29 05:22 UTC
## Command
```
flutter --no-color build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1436:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2302:41)
#14     _rootRunUnary (dart:async/zone.dart:1444:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#20     _StreamController._add (dart:async/stream_controller.dart:607:7)
#21     _StreamController.add (dart:async/stream_controller.dart:554:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1830:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 13.3.1 22E772610a darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/maple/Documents/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (1 year, 5 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/maple/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/maple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • NAM AL00 (mobile) • 7SQVB22308012776          • android-arm64  • Android 12 (API 31)
    • lixf11 (mobile)   • 00008030-000C6D881A83802E • ios            • iOS 16.2 20C65
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 113.0.5672.126

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.14.1+31
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
ali_auth-d34063d3d93359df038d7c1d0243f42aeb306c01
amap_flutter_location-3.0.0
amap_flutter_map-3.0.0
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
desktop-8361aaa79a99015f4e4ccbfd28e7efa6d54ffc76
device_info_plus-3.2.4
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
ffmpeg_kit_flutter-4.5.1-LTS
flutter_aliyun_captcha-1.0.4
flutter_bugly-0.4.4
flutter_contacts-1.1.5
flutter_inappwebview-5.6.0+2
flutter_native_image-0.0.6+1
flutter_plugin_android_lifecycle-2.0.7
flutter_vibrate-1.3.0
flutter_xupdate-2.0.3
fluttertoast-8.1.2
fluwx-3.12.2
image_gallery_saver-1.7.1
image_picker-0.8.5+3
image_picker_android-0.8.5+2
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+6
jpush_flutter-2.3.8
livan_log_tool-0.0.3
livan_payment
open_app_settings-2.0.1
package_info-2.0.2
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-1.0.5
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
permission_handler-8.3.0
photo_manager-2.2.1
scan-1.6.0
sensors_analytics_flutter_plugin-2.3.1
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.2
url_launcher-6.1.5
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.6
url_launcher_windows-3.0.1
video_player-2.3.0
video_player_android-2.3.9
video_player_avfoundation-2.3.5
video_player_web-2.0.12
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.4
webview_flutter_android-2.8.14
webview_flutter_wkwebview-2.7.5

**Comment by huycozy** [comment] 2023-05-29 09:23
Closing this as a duplicate of https://github.com/flutter/flutter/issues/81666.

**Closed by huycozy** 2023-05-29 09:23 UTC
Labels: in triage
