### ISSUE TITLE
Add2app iOS framework

### ISSUE THREAD

**Issue by ilteoood** [flutter/flutter#44138] opened 2019-11-04 22:30 UTC
Hi everyone!
With the add2app tutorial [here described](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) I'm trying to create a sort of "common" sdk package that automatically initialize the method channel and that can be used both on Android and on iOS.
I'm trying to make something that can be redistributable: for Android no problem, the creation of the _.aar_ package is quite easy, but what about iOS? Is it possible to create a _.framework_ that embeds everything (Swift class + flutter project)?

Thank you so much,
Matteo

**Comment by DrBendson** [comment] 2019-11-04 22:50
Please provide me with your monitor manufacturer

**Comment by jmagman** [comment] 2019-11-04 22:58
Duplicate of https://github.com/flutter/flutter/issues/36968.

**Closed by jmagman** 2019-11-04 22:58 UTC
Labels: created via support template
