### ISSUE TITLE
Cache ability for video_player

### ISSUE THREAD

**Issue by seljad** [flutter/flutter#130007] opened 2023-07-05 13:06 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have an app and use video_player for playing videos. The problem is with each time I dispose of the controller, the video must download again to the user can see that.

### Proposal

Please add this feature for caching videos in video_player.

**Comment by danagbemava-nc** [comment] 2023-07-05 13:15
Closing this as a duplicate of https://github.com/flutter/flutter/issues/28094

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-07-05 13:15 UTC
Labels: in triage
