### ISSUE TITLE
Many infra failures on Mac_arm64_ios%20run_debug_test_macos

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#133807] opened 2023-08-31 21:02 UTC
https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64_ios%20run_debug_test_macos

**Comment by yusuf-goog** [comment] 2023-08-31 21:04
cc @vashworth 

FYI: https://github.com/flutter/flutter/pull/133788

**Comment by ricardoamador** [comment] 2023-08-31 21:20
Should we revert that change then?

**Comment by ricardoamador** [comment] 2023-08-31 21:21
@zanderso  can you please use the infra issue template from now on?

**Comment by yusuf-goog** [comment] 2023-08-31 21:33
change is being reverted

**Comment by ricardoamador** [comment] 2023-08-31 21:34
Thank you sir!

**Comment by ricardoamador** [comment] 2023-08-31 23:16
It seems that there is some kind of delay/error between what the phone is actually doing and the command we use to list devices is reporting.

For some reason the xcrun xcdevice list shows the device as waiting for debug symbols. However if you launch xcode and look at the connected device it shows up as connected.

![image](https://github.com/flutter/flutter/assets/32242716/a3f166d8-58c7-4f43-8619-897ead997cee)

It will show that it is waiting for the debugger but in this case it was operational and not looking for debug symbols as reported in the xcrun command.

Something may be wrong with the bot/device.

But I will need @Victoria Ashworth's help on this.

**Comment by ricardoamador** [comment] 2023-08-31 23:16
I also tried restarting the device and it always returns to that state of looking for the debug symbols.

**Comment by yusuf-goog** [comment] 2023-09-01 00:01
> It seems that there is some kind of delay/error between what the phone is actually doing and the command we use to list devices is reporting.
> 
> For some reason the xcrun xcdevice list shows the device as waiting for debug symbols. However if you launch xcode and look at the connected device it shows up as connected.
> 
> ![image](https://user-images.githubusercontent.com/32242716/264811790-a3f166d8-58c7-4f43-8619-897ead997cee.png)
> 
> It will show that it is waiting for the debugger but in this case it was operational and not looking for debug symbols as reported in the xcrun command.
> 
> Something may be wrong with the bot/device.
> 
> But I will need @victoria Ashworth's help on this.

This used to be an issue previously, but it was a one time thing, which got fixed when we went in and manually opened Xcode. Once we opened Xcode it sets things up and then things just worked. 

Is this running the new Xcode?

**Comment by ricardoamador** [comment] 2023-09-01 00:14
I am guessing. There was no dialog though. The device appears to be fine. Just something up with it's status in the device list. It is running this version: xcode/14e300c/XCode.app

**Comment by vashworth** [comment] 2023-09-01 14:22
So I don't think the symbols stuff is the main issue here. I can take a look at that, but it's usually fixed by opening Xcode or deleting the existing symbols.

The I think the real issue is that it failed to open Xcode:
```
[INFO] : stderr from `open`:
No application knows how to open URL file:///opt/s/w/ir/cache/cocoon/dashboard/ios/Runner.xcodeproj/project.xcworkspace/ (Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file" UserInfo={_LSLine=1489, _LSFunction=runEvaluator}).
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8771213845302282993/+/u/ios_debug_symbol_doctor/recover_with_120_second_timeout/stdout

Not sure why that's happening, though

**Comment by ricardoamador** [comment] 2023-09-01 15:12
Is it attempting to load the directory or everything in it?

**Comment by vashworth** [comment] 2023-09-01 15:21
Okay figured it out and fixed. So this bot hasn't been in use for a long time and didn't have any Xcode versions installed previously.

So the issue is the current version of Xcode we use on CI is 14.3.1, which requires macOS 13+. However, all of our bots are 12.6 (It's kind of surprising it's been working thus far and more things haven't broken).

I was able to resolve this by installing an older compatible Xcode version (14.2) on the bot. As long as it has an older compatible version, it's smart enough to know to use that one when opening Xcode, even is the newer version is selected via `xcode-select`. So I'm assuming the only reason this hasn't been an issue yet out in the wild is because all of our bots probably have older Xcode 14.2 still installed.

I filed an issue for us to prevent this in the future by adding tests to check if the Xcode version is incompatible before allowed it to be used in CI:
https://github.com/flutter/flutter/issues/133867

**Comment by vashworth** [comment] 2023-09-01 15:40
I confirmed the `Mac_arm64_ios run_debug_test_macos` ran successfully on [flutter-devicelab-mac-38](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-38) in presubmit
PR: https://github.com/flutter/flutter/pull/133869
https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64_ios%20run_debug_test_macos/345/overview

Closing.

**Closed by vashworth** 2023-09-01 15:40 UTC
Labels: team-infra
