### ISSUE TITLE
Error DecorationImage on Container

### ISSUE THREAD

**Issue by mamm26** [flutter/flutter#89697] opened 2021-09-08 23:11 UTC
The bug is that DecorationImage covers all Containers in Stack.

The background should be used in the current Container, not all containers.

`image.jpg` also affects Container of Text("Test")

```dart

Stack(
 children: <Widget>[
     Container(
        color: Colors.red,
        child: Text("Test")
     ),
     Container(
        decoration: BoxDecoration(
          image: DecorationImage(
             image: AssetImage("image.jpg"),
             fit: BoxFit.cover
          )
       )
     )
  ]
)

```

----
> Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale es-419)
>     • Flutter version 2.2.3 at /flutter
>     • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
>

**Comment by jeiea** [comment] 2021-09-09 02:29
I expect the result is that image.jpg covers red backgrounded "Test" text because `Stack` means stacking widgets like overlaying. What layout did you expect?

**Comment by danagbemava-nc** [comment] 2021-09-09 07:53
Hi @mamm26, as @jeiea pointed out, that is the intended behaviour of the `Stack` widget and it is not an issue with the Decoration. 

See [Stack documentation](https://api.flutter.dev/flutter/widgets/Stack-class.html) for more information. 

Closing as this is not an issue with `flutter`. 

If you disagree, kindly leave a comment explaining why and I will reopnen.

Thank you

**Closed by danagbemava-nc** 2021-09-09 07:53 UTC
Labels: in triage
