### ISSUE TITLE
After my project introduced the 'image_picker_for_web' dependency, the App side won't run.

### ISSUE THREAD

**Issue by Sansuihe** [flutter/flutter#130572] opened 2023-07-14 09:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Since my App project developed by flutter needs to run on the web side, I added the image_picker_for_web dependency according to the document that image_picker relies on, which allowed me to complete the file acquisition function on the web side very smoothly. But since I added the image_picker_for_web dependency it contains the dart:html library. So my APP won't work. I am very upset that I removed the image_picker_for_web dependency and my App can run normally, how should I run the App without the image_picker_for_web dependency library or what other methods are compatible?

Error prompt:

 /D:/tool/flutterPubCache/hosted/pub.flutter-io.cn/image_picker_for_web-2.1.12/lib/image_picker_for_web.dart:6:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html;
       ^
Context: The unavailable library 'dart:html' is imported through these packages:

    package:fixed_assets => package:image_picker_for_web => dart:html
    package:fixed_assets => package:image_picker_for_web => package:flutter_web_plugins => dart:html

Detailed import paths for (some of) the these imports:

### Expected results

How can I use image_picker_for_web in this code that relies on dart:html and still work in my APP

### Actual results

image_picker_for_web introduces 'dart:html' which prevents my App from compiling

### Code sample

  image_picker: ^0.8.5+3 
  image_picker_for_web: ^2.1.12 

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Invalid depfile: D:\job\workJob\objet\flutter2.5\fixed-assets-sdk3.7\.dart_tool\flutter_build\b5b74403a33b0bb01d3f56b6d393ce01\kernel_snapshot.d
Invalid depfile: D:\job\workJob\objet\flutter2.5\fixed-assets-sdk3.7\.dart_tool\flutter_build\b5b74403a33b0bb01d3f56b6d393ce01\kernel_snapshot.d
/D:/tool/flutterPubCache/hosted/pub.flutter-io.cn/image_picker_for_web-2.1.12/lib/image_picker_for_web.dart:6:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html;
       ^
Context: The unavailable library 'dart:html' is imported through these packages:

    package:fixed_assets => package:image_picker_for_web => dart:html
    package:fixed_assets => package:image_picker_for_web => package:flutter_web_plugins => dart:html

Detailed import paths for (some of) the these imports:

    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/file_widget.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/file_widget.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/js_url_strategy.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/file_widget.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/file_widget.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => package:flutter_web_plugins/src/navigation/js_url_strategy.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/file_widget.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => package:flutter_web_plugins/src/navigation/utils.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/file_widget.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/utils.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/file_widget.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => package:image_picker_for_web/src/image_resizer.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/video_widget.dart => package:fixed_assets/components/generalduty/upload_video.dart => package:image_picker_for_web/image_picker_for_web.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/video_widget.dart => package:fixed_assets/components/generalduty/upload_video.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/js_url_strategy.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/video_widget.dart => package:fixed_assets/components/generalduty/upload_video.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/video_widget.dart => package:fixed_assets/components/generalduty/upload_video.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => package:flutter_web_plugins/src/navigation/js_url_strategy.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/video_widget.dart => package:fixed_assets/components/generalduty/upload_video.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => package:flutter_web_plugins/src/navigation/utils.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/video_widget.dart => package:fixed_assets/components/generalduty/upload_video.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/utils.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/form_module/form_assets.dart => package:fixed_assets/page/form_module/scet_element/video_widget.dart => package:fixed_assets/components/generalduty/upload_video.dart => package:image_picker_for_web/image_picker_for_web.dart => package:image_picker_for_web/src/image_resizer.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/project_module/fixed_assets/fixed_assets_add.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/project_module/fixed_assets/fixed_assets_add.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/js_url_strategy.dart => dart:html
    package:fixed_assets/main.dart => package:fixed_assets/routers/routes.dart => package:fixed_assets/page/project_module/fixed_assets/fixed_assets_add.dart => package:fixed_assets/components/generalduty/upload_file.dart => package:image_picker_for_web/image_picker_for_web.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => dart:html

### Flutter Doctor output

[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [版本 10.0.18363.1556], locale zh-CN)
    • Flutter version 3.7.0 on channel stable at D:\tool\flutterSdk3.7.0\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (6 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at E:\tools\AndroidStudioTool\Android\Sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.1
    • ANDROID_HOME = E:\tools\AndroidStudioTool\Android\Sdk
    • Java binary at: D:\tool\android studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\asus\AppData\Local\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio 15 生成工具 2017 15.9.13)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio 15 生成工具 2017 version 15.9.28307.718
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at D:\tool\android studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 4.1)
    • Android Studio at D:\tool\android-studio-ide-4.1.3-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • EBG AN00 (mobile)            • DSLDU20414000085 • android-arm64  • Android 10 (API 29)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows          • windows-x64    • Microsoft Windows [版本 10.0.18363.1556]
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)                   • edge             • web-javascript • Microsoft Edge 113.0.1774.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by stuartmorgan** [comment] 2023-07-14 10:39
> I added the image_picker_for_web dependency according to the document that image_picker relies on

I'm not sure what document you are referring to, but as it says in the package's README you do not need depend on the package directly in normal use.

If for some reason it's important to your use case to bypass `image_picker`, you will need to manage the conditional imports yourself, as with any other web-specific library.

Closing as this is not a bug in the plugin; the app-facing package is where the plugin manages this, by design.

**Closed by stuartmorgan** 2023-07-14 10:39 UTC
