### ISSUE TITLE
please make the installation process simpler just like visual studio which is done all by it self

### ISSUE THREAD

**Issue by fisforfaheem** [flutter/flutter#54639] opened 2020-04-12 19:27 UTC
tired of uselessly so difficult actions to be performed. please make everything easier like visual studio do, everything should be installed in a single click...tired of writing code nd running stuff...
and please dont call it customization cuz vs has everything eaiser al ready...go ahed and isntall one

**Comment by TahaTesser** [comment] 2020-04-13 14:38
duplicate of [#54614](https://github.com/flutter/flutter/issues/54614)

**Closed by TahaTesser** 2020-04-13 14:38 UTC
