### ISSUE TITLE
In Android Studio, In debug mode , the class static variable is not initialized in watches tab console.

### ISSUE THREAD

**Issue by dongzhixuanyuan** [flutter/flutter#61059] opened 2020-07-08 02:29 UTC
![image](https://user-images.githubusercontent.com/17685717/86867746-f2c1b600-c105-11ea-8b27-75305596adae.png)

<img width="1368" alt="flutter_module____android_code_netease_YDNativeFlutterBridge_Embed_flutter_module__-_____Business_yd_exam_lib_common_router_exam_routers_dart__Embed-flutter_module_" src="https://user-images.githubusercontent.com/17685717/86867646-c6a63500-c105-11ea-9e68-d65be40cb7a1.png">

it's strange that in debug watches tab,the static variable not initlized.

**Comment by iapicca** [comment] 2020-07-08 07:24
Hi @dongzhixuanyuan 
If you are experiencing the issue only with Android Studio or IntelliJ and not with VS Code, then following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Otherwise, please provide your ´flutter doctor - v´ output.
Thank you

**Comment by iapicca** [comment] 2020-07-29 10:46
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-07-29 10:46 UTC
Labels: in triage, waiting for customer response
