### ISSUE TITLE
type 'Null' is not a subtype of type 'String' while trying to connect Flutter app to Deno + MongoDB backend

### ISSUE THREAD

**Issue by goodmanworld** [flutter/flutter#92727] opened 2021-10-29 19:14 UTC
I want to write a simple registration function and this is my code:

auth_screen.dart:

```
  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) {
      // Invalid!
      return;
    }
    _formKey.currentState!.save();
    setState(() {
      _isLoading = true;
    });
    try {
      if (_authMode == AuthMode.Login) {
        // Log user in
        await Provider.of<Auth>(context, listen: false).login(
          _authData['email'] as String,
          _authData['password'] as String,
        );
      } else {
        // Sign user up
        await Provider.of<Auth>(context, listen: false).signup(
          _authData['email'] as String,
          _authData['password'] as String,
          
        );
      }
    } on HttpException catch (error) {
      var errorMessage = 'Authentication failed';
      print("this is the auth data");
      print(_authData);
      if (error.toString().contains('EMAIL_EXISTS')) {
        errorMessage = 'This email address is already in use.';
      } else if (error.toString().contains('INVALID_EMAIL')) {
        errorMessage = 'This is not a valid email address';
      } else if (error.toString().contains('WEAK_PASSWORD')) {
        errorMessage = 'This password is too weak.';
      } else if (error.toString().contains('EMAIL_NOT_FOUND')) {
        errorMessage = 'Could not find a user with that email.';
      } else if (error.toString().contains('INVALID_PASSWORD')) {
        errorMessage = 'Invalid password.';
      }
      _showErrorDialog(errorMessage);
    } catch (error) {
      var errorMessage = 'Could not authenticate you. Please try again later.' +
          error.toString();
      _showErrorDialog(errorMessage);
    }

    setState(() {
      _isLoading = false;
    });
  }
```
auth.dart:
```

  Future<void> signup(String email, String password) async {
    return _authenticate(email, password, 'register');
  }

  Future<void> _authenticate(
      String email, String password, String urlSegment) async {

    final url = Uri.parse('http://10.0.2.2:8000/api/$urlSegment');
    // final url = Uri.http('http://localhost:8000/api/', 'urlSegment');
    try {
      final response = await http.post(
        url,
        body: json.encode(
          {
            'email': email,
            'password': password,

            //'returnSecureToken': true,
          },
        ),
      );
      final responseData = json.decode(response.body);
      if (responseData['error'] != null) {
        throw HttpException(responseData['error']['message']);
      }
      _token = responseData['idToken'];
      _userId = responseData['localId'];
      _expiryDate = DateTime.now().add(
        Duration(
          seconds: int.parse(
            responseData['expiresIn'],
          ),
        ),
      );
      _autoLogout();
      notifyListeners();
      final prefs = await SharedPreferences.getInstance();
      final userData = json.encode(
        {
          'token': _token,
          'userId': _userId,
          'expiryDate': _expiryDate!.toIso8601String(),
        },
      );
      prefs.setString('userData', userData);
    } catch (error) {
      throw error;
    }
  }
```

This is the backend(Deno) part of the project:

auth_controller.ts:

```
async register(ctx: RouterContext) {
    const { email, password } = await ctx.request.body().value;
    let user = await User.findOne({ email });
    if (user) {
        ctx.response.status = 422;
        ctx.response.body = { message: "Email is already exist" };
        return;
    }
    const hashedPassword = hashSync(password);
    user = new User({ email, password: hashedPassword });
    await user.save();
    ctx.response.status = 201;
    ctx.response.body = {
        id: user.id,
        name: user.name,
        email: user.email
    };
}
```

And this is the `user.ts` class:
```

export default class User extends BaseModel {
    public id: string = "";
    public name: string = "";
    public email: string = "";
    public password: string = "";
    constructor({ id = "", name = "", email = "", password = "" }) {
        super();
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
    }
    static async findOne(params: object): Promise<User | null> {
        const user = await userCollection.findOne(params);
        if (!user) {
            return null;
        }
        return new User(User.prepare(user));
    }
    async save() {
        const _id = await userCollection.insertOne(this);
        this.id = _id;
        return this;
    }
}

```
I get this error message when I want to test the application on Android emulator:

> type 'Null' is not a subtype of type 'String'

EDIT: When I try the backend server using Postman and send post request to `http://0.0.0.0:8000/api/register` address. I get correct response and it works, but I don't know why do I get `Null` response using the Flutter app?

**Comment by iapicca** [comment] 2021-10-29 20:47
@goodmanworld 
this seems a problem with your code rather than a bug with flutter
especially this part looks suspicious

```dart
  final responseData = json.decode(response.body);
      if (responseData['error'] != null) {
        throw HttpException(responseData['error']['message']);
      }
      _token = responseData['idToken'];
      _userId = responseData['localId'];
      _expiryDate = DateTime.now().add(
        Duration(
          seconds: int.parse(
            responseData['expiresIn'],
          ),
        ),
      );
```

**Comment by goodmanworld** [comment] 2021-10-29 21:24
> @goodmanworld this seems a problem with your code rather than a bug with flutter especially this part looks suspicious
> 
> ```dart
>   final responseData = json.decode(response.body);
>       if (responseData['error'] != null) {
>         throw HttpException(responseData['error']['message']);
>       }
>       _token = responseData['idToken'];
>       _userId = responseData['localId'];
>       _expiryDate = DateTime.now().add(
>         Duration(
>           seconds: int.parse(
>             responseData['expiresIn'],
>           ),
>         ),
>       );
> ```

I found that the problem is in this line of the code:

`const  { email, password }  = await ctx.request.body().value;`

I can not print the `email` and `password` values and seems they are Null variables! But I don't know why as they work good with Postman!

**Comment by or-adar** [comment] 2021-10-29 23:07
> > @goodmanworld this seems a problem with your code rather than a bug with flutter especially this part looks suspicious
> > ```dart
> >   final responseData = json.decode(response.body);
> >       if (responseData['error'] != null) {
> >         throw HttpException(responseData['error']['message']);
> >       }
> >       _token = responseData['idToken'];
> >       _userId = responseData['localId'];
> >       _expiryDate = DateTime.now().add(
> >         Duration(
> >           seconds: int.parse(
> >             responseData['expiresIn'],
> >           ),
> >         ),
> >       );
> > ```
> 
> I found that the problem is in this line of the code:
> 
> `const { email, password } = await ctx.request.body().value;`
> 
> I can not print the `email` and `password` values and seems they are Null variables! But I don't know why as they work good with Postman!

On your backend, it looks like you assume the request's body is in the form of:
```
{
    value: {
        email: "<email>",
        password: "<password>"
    }
}
```
However, on the client side you send the request's body in the form of
```
{
    email: "<email>",
    password: "<password>"
}
```

**Comment by goodmanworld** [comment] 2021-10-30 00:41
> > > @goodmanworld this seems a problem with your code rather than a bug with flutter especially this part looks suspicious
> > > ```dart
> > >   final responseData = json.decode(response.body);
> > >       if (responseData['error'] != null) {
> > >         throw HttpException(responseData['error']['message']);
> > >       }
> > >       _token = responseData['idToken'];
> > >       _userId = responseData['localId'];
> > >       _expiryDate = DateTime.now().add(
> > >         Duration(
> > >           seconds: int.parse(
> > >             responseData['expiresIn'],
> > >           ),
> > >         ),
> > >       );
> > > ```
> > 
> > 
> > I found that the problem is in this line of the code:
> > `const { email, password } = await ctx.request.body().value;`
> > I can not print the `email` and `password` values and seems they are Null variables! But I don't know why as they work good with Postman!
> 
> On your backend, it looks like you assume the request's body is in the form of:
> 
> ```ts
> {
>     value: {
>         email: "<email>",
>         password: "<password>"
>     }
> }
> ```
> 
> However, on the client side you send the request's body in the form of
> 
> ```ts
> {
>     email: "<email>",
>     password: "<password>"
> }
> ```

It seems correct but when I try to eliminate `.value` from the end of following line of code, I get new errors as following:

`const { email, password } = await ctx.request.body();
`
It gives me error messages like:

`Property 'email' does not exist on type 'Body'.
`Property 'password' does not exist on type 'Body'.

**Comment by or-adar** [comment] 2021-10-30 09:18
> It seems correct but when I try to eliminate `.value` from the end of following line of code, I get new errors as following:
> 
> `const { email, password } = await ctx.request.body(); ` It gives me error messages like:
> 
> `Property 'email' does not exist on type 'Body'. `Property 'password' does not exist on type 'Body'.

Yeah, I was wrong, sorry.
I'm not familliar with Deno and it seems like the "value" propery is just the way the framework your using parses the body.
But, If I may have another assumption, you probably need to provide a "content-type" header when making your post request to the server on ```auth.dart```, like so:
```dart
final response = await http.post(
        url,
        headers: {"Content-Type": "application/json"},
        body: json.encode(
          {
            'email': email,
            'password': password
          },
        ),
      );
```
It should tell the body parser to treat the request's body as json.

**Comment by darshankawar** [comment] 2021-11-01 06:36
@goodmanworld 
In order to properly address this issue, we would need a complete minimal reproducible code sample without any 3rd party plugin and clear steps to replicate the issue that throws the `null` error, along with `flutter doctor -v`.

**Comment by goodmanworld** [comment] 2021-11-05 19:47
> > It seems correct but when I try to eliminate `.value` from the end of following line of code, I get new errors as following:
> > `const { email, password } = await ctx.request.body(); ` It gives me error messages like:
> > `Property 'email' does not exist on type 'Body'. `Property 'password' does not exist on type 'Body'.
> 
> Yeah, I was wrong, sorry. I'm not familliar with Deno and it seems like the "value" propery is just the way the framework your using parses the body. But, If I may have another assumption, you probably need to provide a "content-type" header when making your post request to the server on `auth.dart`, like so:
> 
> ```dart
> final response = await http.post(
>         url,
>         headers: {"Content-Type": "application/json"},
>         body: json.encode(
>           {
>             'email': email,
>             'password': password
>           },
>         ),
>       );
> ```
> 
> It should tell the body parser to treat the request's body as json.

I did that and printed out the result that comes from the backend side in this line of the code: `      final responseData = json.decode(response.body);` and it seems the result is also OK. But I don't know why do I still get the error message.

**Comment by or-adar** [comment] 2021-11-05 20:35
@goodmanworld 

Great, at this poin you are receiving a response from your server!
However, "Seems OK" is a bit ambigous, you are probably trying to access fields on the response that doesn't exist.
Make sure that when you access & assign values of `responseData` on `auth.dart`, they're not null.
(when invoking `responseData['idToken']`, `responseData['localId']`, `responseData['expiresIn']`)
If they are, you aren't setting some of these values when sending a response through your backend.
Make sure all these field exist on your response's body!

**Comment by darshankawar** [comment] 2021-11-08 05:59
It seems to me that this is more of a debugging and troubleshooting thread, more than discussing on an issue, so I would suggest to continue this on support channels like StackOverflow. If there's a concrete steps to replicate that shows a bug in the framework, please provide minimal code sample that shows the issue along with `flutter doctor -v`. Closing from here for now.

**Closed by darshankawar** 2021-11-08 05:59 UTC
Labels: in triage

**Comment by goodmanworld** [comment] 2021-11-13 19:58
> @goodmanworld In order to properly address this issue, we would need a complete minimal reproducible code sample without any 3rd party plugin and clear steps to replicate the issue that throws the `null` error, along with `flutter doctor -v`.


I uploaded the complete project here(https://github.com/goodmanworld/flutter_test). It's a really simple project and backend works properly as I can test it with Postman. Also wherever I print the responses I get from the backend in the Flutter side, it's correct and it is what I expected to be. But I don't know why do I get this strange error message whenever I try to hit SUBMIT button to register a new user using Android emulator running my Flutter app:

`'Null' is not a subtype of type 'String'`
