### ISSUE TITLE
Config autovalidateMode: AutovalidateMode.onUserInteraction not work when focus textformfield

### ISSUE THREAD

**Issue by rickynguyenc** [flutter/flutter#147851] opened 2024-05-06 03:52 UTC
### Steps to reproduce

1. Run app
2. Focus into TextFormField and don't type anything
3. Nothing happen

### Expected results

I want TextFormField is validated when i only focus into it

### Actual results

TextFormField is not validated when i only focus into it

### Code sample

```dart
Form(
          autovalidateMode: AutovalidateMode.onUserInteraction,
          key: _formKeyTitle,
          child: TextFormField(
            initialValue: widget.dtoGetDiscuss?.title,
            autocorrect: false,
            decoration: InputDecoration(
              labelText: 'Tiêu đề',
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
              enabledBorder: InputBorder.none,
              filled: true,
              fillColor: const Color(0xffF4F3F4),
            ),
            // maxLength: 255,
            onSaved: (value) {
              if (widget.dtoGetDiscuss != null) {
                widget.dtoGetDiscuss!.title = value!.trim();
              }
            },
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Đây là trường bắt buộc!';
              } else if (value.length > 255) {
                return 'Tối đa 255 ký tự!';
              } else {
                return null;
              }
            },
            onChanged: (value) {
              setState(() {
                isChangeEdit = true;
                dtoCreateDiscuss.title = value.trim();
                isValidTitle = _formKeyTitle.currentState!.validate();
              });
            },
          ),
        )
``` 

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
    • Flutter version 3.7.12 on channel stable at C:\Users\chuon\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (1 year, 1 month ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\chuon\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.89.0)
    • VS Code at C:\Users\chuon\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (4 available)
    • 2201117TG (mobile) • 40d8a81b • android-arm64  • Android 13 (API 33)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 124.0.6367.119
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 124.0.2478.80

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-05-06 10:45
This is working by design. `onUserInteraction` is triggered when the user changes the text in the textfield not when it gets focus. This is because focus can be triggered through various means. You can use `always` if you want it to be validated when the user focuses on the textfield. 

Closing this as working by design. 

PS: You should upgrade your flutter version as the version you're using is quite old. 

Thank you

**Closed by danagbemava-nc** 2024-05-06 10:45 UTC
Labels: in triage
