### ISSUE TITLE
CupertinoIcons `create` icon is buggy

### ISSUE THREAD

**Issue by xavierdonnellon** [flutter/flutter#116594] opened 2022-12-06 15:44 UTC
`CupertinoIcons.create` looks wrong. It is filled with an odd offset, when it should be an outline. 

<details>
  <summary>Logs</summary>

[doctor_output.txt](https://github.com/flutter/flutter/files/10162640/doctor_output.txt)
</details>

Expected for `create`: 
<img width="62" alt="Screenshot 2022-12-06 at 10 42 14 AM" src="https://user-images.githubusercontent.com/74732530/205957086-3015b5d4-5963-44c4-9b7d-268a8acd610e.png">

Reality (found [here](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html); same behavior in app)
<img width="44" alt="Screenshot 2022-12-06 at 10 43 12 AM" src="https://user-images.githubusercontent.com/74732530/205957293-1a4b4819-88d5-4843-97bb-139d9679b9dd.png">

`create` is filled when it shouldn't be, and the fill has a weird offset. 
`create_fill` is filled properly, but still has weird offset.

**Comment by darshankawar** [comment] 2022-12-07 06:02
```
return Center(
      child: Icon(
        CupertinoIcons.create
      )
    );
```

<img width="66" alt="Screenshot 2022-12-07 at 11 31 16 AM" src="https://user-images.githubusercontent.com/67046386/206100750-f72e6958-22d9-40c4-b165-2ba7cf7180fa.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.9 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (12 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-3.0.pre.57, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.7.0-3.0.pre.57 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef6ead4401 (44 minutes ago), 2022-12-06 23:15:24 -0500
    • Engine revision 67254d6e4b
    • Dart version 2.19.0 (build 2.19.0-467.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by leighajarett** [comment] 2022-12-07 20:51
Is this the same as https://github.com/flutter/flutter/issues/106065?

**Comment by xavierdonnellon** [comment] 2022-12-07 21:11
> 

Yes it is. Now about 6 months old

**Comment by darshankawar** [comment] 2022-12-08 05:25
Closing as duplicate of https://github.com/flutter/flutter/issues/106065

**Closed by darshankawar** 2022-12-08 05:25 UTC
Labels: framework, f: cupertino, has reproducible steps, p: cupertino_icons, found in release: 3.3, found in release: 3.7
