### ISSUE TITLE
Image decoding/encoding, access to pixel data

### ISSUE THREAD

**Issue by hugovangalen** [flutter/flutter#11167] opened 2017-07-12 15:22 UTC
For basic image analysis and manipulation, having access to the decoded pixel-data of an image is essential, yet not possible right now (it is with package:image, but the main bottleneck really is decoding and encoding).

It would be tremendously helpful to have an image decoding API that exposes the decoded pixel-data (*). Especially if I could specify a source rectangle: the native decoder could then decode and return the cropped result only. 

After optional manipulation, this pixel-data could then be passed to an encoding API, #11016. Perhaps, apart from compression level and other format specific parameters, optionally specifying a forced output size, so it could conveniently be scaled before encoding (but that may be too specific to my use case). Then the encoder either returns the bytes of the resulting file, or writes them to a file directly and returns nothing.

(*) If a Canvas could also draw this pixel-data (or initialise with it), and could also return its contents in a similar manner, a lot more interesting things become possible.

**Comment by eseidelGoogle** [comment] 2017-07-12 15:32
It certainly would be reasonable to extend dart:ui's API surface to provide access to image data and encoders/decoders.

It also should be possible for someone to write a plugin which does this and provide's access to the platform's image decoders (CGImage, android.graphics, etc.)

**Comment by majido** [comment] 2017-10-17 01:19
FWIW, I have a flutter/engine [patch](https://github.com/majido/engine/compare/master...majido:support_image_encoding) to expose the decoding API. If this is something of general interest I am happy to upstream.

**Comment by domesticmouse** [comment] 2017-10-17 02:09
@majido +100

**Comment by Hixie** [comment] 2018-03-10 01:03
Dupe of https://github.com/flutter/flutter/issues/11648

**Closed by Hixie** 2018-03-10 01:03 UTC
Labels: prod: engine
