### ISSUE TITLE
Document how transform affects paint, but not layout

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#5850] opened 2016-09-13 18:54 UTC
I would expect this widget tree to result in a centered, scaled-to-half-size `child` widget:

```
  new Center(
    child: new Transform(
      transform: new Matrix4.identity()..scale(0.5),
      child: child
    )
  );
```

But the Center doesn't apply. It looks as though it tries to center the tree before the transform is applied. However, this works:

```
    new Transform(
      transform: new Matrix4.identity()..scale(0.5),
      alignment: FractionalOffset.center,
      child: child
    );
```

**Comment by mpcomplete** [comment] 2016-09-13 18:54
Possibly related: https://github.com/flutter/flutter/issues/5671

**Comment by dragostis** [comment] 2016-09-16 22:08
I believe this issue is caused by the following flow:

* `Center`'s `RenderPositioned` calls `alignChild`
* `alignChild` calls `child.size`
* `RenderTransform` does not override `size`, so the call reaches `RenderBox`'s `size` which returns the full, unscaled size
* because `alignChild` does not know the real size of the child so it doesn't produce any offset

We might want to transform offset and sizes as well?

**Comment by Hixie** [comment] 2016-09-18 23:23
If you transform a child by 2x, the size doesn't grow by 2x. The paint overflow might, but that's not relevant to the Align. You can see this if you wrap the Transform in a ClipRect or a DecoratedBox with a border.

**Comment by mpcomplete** [comment] 2016-09-20 20:43
OK, this isn't a bug, just me misunderstanding what Transform does. Transform affects paint, but not layout. Maybe we can point that out in the docs.

**Comment by eseidelGoogle** [comment] 2017-02-08 18:41
Well our transform docs are pretty sparse. :)  One line:
https://docs.flutter.io/flutter/widgets/Transform-class.html

Easy to add a second line which clarifies that it doesn't affect layout.  Not sure if that's necessary.

**Comment by markusaksli-nc** [comment] 2020-07-27 10:36
Closing since this was fixed in the [Trasform docs](https://api.flutter.dev/flutter/widgets/Transform-class.html).

**Closed by markusaksli-nc** 2020-07-27 10:36 UTC
Labels: P4, d: api docs, easy fix, framework
