### ISSUE TITLE
On Windows, mouse wheel cannot scroll horizontal ListView

### ISSUE THREAD

**Issue by ngugcx** [flutter/flutter#109107] opened 2022-08-07 09:37 UTC
## Steps to Reproduce

```
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
  runApp(MyApp());
}

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
        // etc.
      };
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final List<Widget> tabs = [
    Container(width: 120, color: const Color(0xff2d2d2d)),
    Container(width: 120, color: const Color(0xff2d2d2d)),
    Container(width: 120, color: const Color(0xff1e1e1e)),
    Container(width: 120, color: const Color(0xff2d2d2d)),
    Container(width: 120, color: const Color(0xff2d2d2d)),
    Container(width: 120, color: const Color(0xff2d2d2d)),
    Container(width: 120, color: const Color(0xff2d2d2d)),
    Container(width: 120, color: const Color(0xff2d2d2d)),
    Container(width: 120, color: const Color(0xff2d2d2d)),
    Container(width: 120, color: const Color(0xff2d2d2d)),
  ];

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      scrollBehavior: MyCustomScrollBehavior(),
      home: Center(
          child: Container(
              constraints: const BoxConstraints(maxWidth: 600),
              child: ListView.separated(
                shrinkWrap: true,
                scrollDirection: Axis.horizontal,
                itemCount: tabs.length,
                itemBuilder: (BuildContext context, int index) {
                  return tabs[index];
                },
                separatorBuilder: (BuildContext context, int index) {
                  return Container(width: 2, color: const Color(0xff3c3c3c));
                },
              ))),
    );
  }
}

```

Running the above minimal code can reproduce the problem on Windows 10.
Mouse wheel or Shift+Mouse wheel is not able to scroll the ListView.

**Expected results:** 
Mouse wheel can scroll the ListView without problem.

**Actual results:** 
Mouse wheel or Shift+Mouse wheel is not able to scroll the ListView.

**Environments**
Flutter version: 
```Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```
OS: Windows 10

**Comment by exaby73** [comment] 2022-08-08 09:30
Duplicate of https://github.com/flutter/flutter/issues/105095

**Closed** 2022-08-08 09:31 UTC
Labels: in triage, r: duplicate

**Comment by ngugcx** [comment] 2022-08-08 09:41
What do you mean "not planned"?

**Comment by exaby73** [comment] 2022-08-08 10:14
This issue is "not planned" because it's a duplicate. Please follow the original issue and upvote it :)
