### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by Ritesh9828** [flutter/flutter#127132] opened 2023-05-18 19:28 UTC
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:325:52)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#8      Template.render (package:flutter_tools/src/template.dart:248:24)
#9      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:480:21)
<asynchronous suspension>
#10     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:503:23)
<asynchronous suspension>
#11     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:350:31)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.2965], locale en-IN)
    • Flutter version 3.10.0 on channel stable at D:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (9 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\dell\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\dell\AppData\Local\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at C:\Users\dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • AC2001 (mobile)   • 8b0d6764 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 113.0.1774.42

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by danagbemava-nc** [comment] 2023-05-19 06:39
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by danagbemava-nc** 2023-05-19 06:39 UTC
Labels: in triage
