### ISSUE TITLE
User called to null when trying to user the search screen

### ISSUE THREAD

**Issue by jeremiahseun** [flutter/flutter#74143] opened 2021-01-17 05:50 UTC
I have loaded the project and there is no error. But when I want to open the search screen for me to search for other users, it brings an error of "User call to null"

This is my Search Screen

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:scrolly/models/user.dart' as user;
import 'package:scrolly/resources/firebase_repository.dart';
import 'package:scrolly/screens/chat_screen.dart';
import 'package:scrolly/screens/widgets/custom_tile.dart';
import 'package:scrolly/utils/universal_variables.dart';

class SearchScreen extends StatefulWidget {
  @override
  _SearchScreenState createState() => _SearchScreenState();
}

class _SearchScreenState extends State<SearchScreen> {
  final FirebaseRepository _firebaseRepository = FirebaseRepository();

  List<User> userList;
  String query = "";
  TextEditingController searchController = TextEditingController();
  FirebaseAuth auth = FirebaseAuth.instance;

  @override
  void initState() {
    super.initState();

    _firebaseRepository.getCurrentUser().then((User user) {
      _firebaseRepository.fetchAllUsers(user).then((List<User> list) {
        setState(() {
          userList = list;
        });
      });
    });
  }

  searchAppBar(BuildContext context) {
    return AppBar(
      leading: IconButton(
        icon: Icon(Icons.arrow_back, color: Colors.white),
        onPressed: () => Navigator.pop(context),
      ),
      elevation: 10,
      bottom: PreferredSize(
        preferredSize: const Size.fromHeight(kToolbarHeight + 20),
        child: Padding(
          padding: EdgeInsets.only(left: 20),
          child: TextField(
            controller: searchController,
            onChanged: (val) {
              setState(() {
                query = val;
              });
            },
            cursorColor: UniversalVariables.blackColor,
            autofocus: true,
            style: TextStyle(
              fontWeight: FontWeight.bold,
              color: Colors.white,
              fontSize: 35,
            ),
            decoration: InputDecoration(
              suffixIcon: IconButton(
                icon: Icon(Icons.close, color: Colors.white),
                onPressed: () {
                  WidgetsBinding.instance
                      .addPostFrameCallback((_) => searchController.clear());
                },
              ),
              border: InputBorder.none,
              hintText: "Search",
              hintStyle: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 35,
                color: Color(0x88ffffff),
              ),
            ),
          ),
        ),
      ),
    );
  }

  buildSuggestions(String query) {
    final List<User> suggestionList = query.isEmpty
        ? []
        : userList != null
            ? userList.where((user) {
                String _getUsername = user.email.toLowerCase();
                String _query = query.toLowerCase();
                String _getName = user.displayName.toLowerCase();
                bool matchesUsername = _getUsername.contains(_query);
                bool matchesName = _getName.contains(_query);

                return (matchesUsername || matchesName);

                // (User user) => (user.username.toLowerCase().contains(query.toLowerCase()) ||
                //     (user.name.toLowerCase().contains(query.toLowerCase()))),
              }).toList()
            : [];

    return ListView.builder(
      itemCount: suggestionList.length,
      itemBuilder: ((context, index) {
        User searchedUser = user.UUser(
            uid: suggestionList[index].uid,
            profilePhoto: suggestionList[index].photoURL,
            name: suggestionList[index].displayName,
            username: suggestionList[index].email) as User;

        return CustomTile(
          mini: false,
          onTap: () {
            Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => ChatScreen(
                          receiver: searchedUser,
                        )));
          },
          leading: CircleAvatar(
            backgroundImage: NetworkImage(searchedUser.photoURL),
            backgroundColor: Colors.grey,
          ),
          title: Text(
            searchedUser.email,
            style: TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.bold,
            ),
          ),
          subtitle: Text(
            searchedUser.displayName,
            style: TextStyle(color: UniversalVariables.greyColor),
          ),
        );
      }),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: UniversalVariables.blackColor,
      appBar: searchAppBar(context),
      body: Container(
        padding: EdgeInsets.symmetric(horizontal: 20),
        child: buildSuggestions(query),
      ),
    );
  }
}

**USER MODEL CLASS**

class UUser {
  String uid;
  String name;
  String email;
  String username;
  String status;
  int state;
  String profilePhoto;

  UUser({
    this.uid,
    this.name,
    this.email,
    this.username,
    this.status,
    this.state,
    this.profilePhoto,
  });

  Map toMap(UUser user) {
    var data = Map<String, dynamic>();
    data['uid'] = user.uid;
    data['name'] = user.name;
    data['email'] = user.email;
    data['username'] = user.username;
    data["status"] = user.status;
    data["state"] = user.state;
    data["profile_photo"] = user.profilePhoto;
    return data;
  }

  // Named constructor
  UUser.fromMap(Map<String, dynamic> mapData) {
    this.uid = mapData['uid'];
    this.name = mapData['name'];
    this.email = mapData['email'];
    this.username = mapData['username'];
    this.status = mapData['status'];
    this.state = mapData['state'];
    this.profilePhoto = mapData['profile_photo'];
  }
}

**FIREBASE METHODS CLASS**

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:scrolly/constants/strings.dart';
import 'package:scrolly/models/post.dart';
import 'package:scrolly/models/user.dart' as user;
import 'package:scrolly/utils/utilities.dart';

class FirebaseMethods {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  final GoogleSignIn _googleSignIn = GoogleSignIn();
  static final FirebaseFirestore firestore = FirebaseFirestore.instance;

  final FirebaseStorage firebaseStorage = FirebaseStorage.instance;

  //user class
  var user;

  Future<User> getCurrentUser() async {
    User currentUser;
    currentUser = _auth.currentUser;
    return currentUser;
  }

  Future<User> signIn() async {
    try {
      final GoogleSignInAccount _signInAccount = await _googleSignIn.signIn();
      final GoogleSignInAuthentication _signInAuthentication =
          await _signInAccount.authentication;

      final AuthCredential credential = GoogleAuthProvider.credential(
        accessToken: _signInAuthentication.accessToken,
        idToken: _signInAuthentication.idToken,
      );

      User user = (await _auth.signInWithCredential(credential)).user;
      return user;
    } catch (e) {
      print(e);
    }
    return null;
  }

  Future<bool> authenticateUser(User user) async {
    QuerySnapshot result = await firestore
        .collection('users')
        .where('email', isEqualTo: user.email)
        .get();

    final List<DocumentSnapshot> docs = result.docs;

    //if user is registered then length of lost > 0 else less than 0
    return docs.length == 0 ? true : false;
  }

  Future<void> addDataToDb(User currentUser) async {
    String username = Utils.getUsername(currentUser.email);
    user = user.UUser(
        uid: currentUser.uid,
        email: currentUser.email,
        name: currentUser.displayName,
        profilePhoto: currentUser.photoURL,
        username: username);

    firestore.collection('users').doc(currentUser.uid).set(user.toMap(user));
  }

  Future<Post> addPostToDb(Post post) async {
    post = Post(
      uid: user.uid,
      caption: post.caption,
      name: post.name,
      photoUrl: post.photoUrl,
      date: DateTime.now().toString(),
    );

    firestore.collection('posts').doc(user.uid).set(
          post.toMap(post),
        );
    return null;
  }

  Future<void> signOut() async {
    await _googleSignIn.disconnect();
    await _googleSignIn.signOut();
    return await _auth.signOut();
  }

  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  static final CollectionReference _userCollection =
      _firestore.collection(USERS_COLLECTION);

  Future<User> getUserDetails() async {
    FirebaseAuth auth = FirebaseAuth.instance;

    DocumentSnapshot documentSnapshot =
        await _userCollection.doc(auth.currentUser.uid).get();
    return user.User.map(documentSnapshot.data);
  }

  Future<User> getUserDetailsById(id) async {
    try {
      DocumentSnapshot documentSnapshot = await _userCollection.doc(id).get();
      return user.User.fromMap(documentSnapshot.data);
    } catch (e) {
      print(e);
      return null;
    }
  }

  Stream<DocumentSnapshot> getUserStream({@required String uid}) =>
      _userCollection.doc(uid).snapshots();

  Future<List<User>> fetchAllUsers(User currentUser) async {
    List<User> userList = List<User>();

    QuerySnapshot querySnapshot =
        await firestore.collection(USERS_COLLECTION).get();
    for (var i = 0; i < querySnapshot.docs.length; i++) {
      if (querySnapshot.docs[i].id != currentUser.uid) {
        userList.add(user.User.fromMap(querySnapshot.docs[i].data));
      }
    }
    return userList;
  }
}

**FIREBASE REPOSITORY CLASS**

import 'package:scrolly/models/post.dart';
import 'package:scrolly/resources/firebase_methods.dart';
import 'package:firebase_auth/firebase_auth.dart';

class FirebaseRepository {
  FirebaseMethods _firebaseMethods = FirebaseMethods();

  Future<User> getCurrentUser() => _firebaseMethods.getCurrentUser();

  Future<User> signIn() => _firebaseMethods.signIn();

  Future<bool> authenticateUser(User user) =>
      _firebaseMethods.authenticateUser(user);

  Future<void> addDataToDb(User user) => _firebaseMethods.addDataToDb(user);

  Future<Post> addPostToDb(Post post) => _firebaseMethods.addPostToDb(post);

  Future<void> signOut() => _firebaseMethods.signOut();

  Future<List<User>> fetchAllUsers(User user) =>
      _firebaseMethods.fetchAllUsers(user);
}

**AND THE EXCEPTION ERROR WHEN I OPEN THE SEARCH SCREEN**

2 W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed) W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed) W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed) I/chatty (17540): uid=10517(com.scrolly.app) FirestoreWorker identical 1 line 2 W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed) W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed) W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed) W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed) W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed) E/flutter (17540): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'User' was called on null. E/flutter (17540): Receiver: null E/flutter (17540): Tried calling: User E/flutter (17540): #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5) E/flutter (17540): #1 FirebaseMethods.fetchAllUsers package:scrolly/resources/firebase_methods.dart:125 E/flutter (17540): E/flutter (17540): #2 FirebaseRepository.fetchAllUsers package:scrolly/resources/firebase_repository.dart:22 E/flutter (17540): #3 _SearchScreenState.initState. package:scrolly/…/search/search_screen.dart:27 E/flutter (17540): #4 _rootRunUnary (dart:async/zone.dart:1198:47) E/flutter (17540): #5 _CustomZone.runUnary (dart:async/zone.dart:1100:19) E/flutter (17540): #6 _FutureListener.handleValue (dart:async/future_impl.dart:143:18) E/flutter (17540): #7 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45) E/flutter (17540): #8 Future._propagateToListeners (dart:async/future_impl.dart:725:32) E/flutter (17540): #9 Future._completeWithValue (dart:async/future_impl.dart:529:5) E/flutter (17540): #10 Future._asyncCompleteWithValue. (dart:async/future_impl.dart:567:7) E/flutter (17540): #11 _rootRun (dart:async/zone.dart:1190:13) E/flutter (17540): #12 _CustomZone.run (dart:async/zone.dart:1093:19) E/flutter (17540): #13 _CustomZone.runGuarded (dart:async/zone.dart:997:7) E/flutter (17540): #14 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:1037:23) E/flutter (17540): #15 _microtaskLoop (dart:async/schedule_microtask.dart:41:21) E/flutter (17540): #16 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5) E/flutter (17540): W/com.scrolly.ap(17540): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)

**Comment by iapicca** [comment] 2021-01-17 08:31
@jeremiahseun 
if you are experiencing a problem with [firebase](https://firebase.flutter.dev/) I recommend to open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues) 
otherwise please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **that does not use 3rd party plugins**

**Comment by jeremiahseun** [comment] 2021-01-17 10:36
Microsoft Windows [Version 10.0.19041.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\user>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.746], locale en-US)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • ONEPLUS A6013 (mobile) • d6ffa1ae • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by iapicca** [comment] 2021-01-17 11:33
@jeremiahseun
> [...]  please provide [...] a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **that does not use 3rd party plugins**

**Comment by pedromassangocode** [comment] 2021-01-18 08:49
Hi @jeremiahseun 
Please provide what was asked in https://github.com/flutter/flutter/issues/74143#issuecomment-761786520.

**Comment by jeremiahseun** [comment] 2021-01-18 09:29
The issue from the search screen.

```
@override void initState() { super.initState();
_firebaseRepository.getCurrentUser().then((User user) {
  _firebaseRepository.fetchAllUsers(user).then((List<User> list) {
    setState(() {
      userList = list;
    });
  });
});
}
```

From the FirebaseRepository class

  ```
Future<List<User>> fetchAllUsers(User user) =>
      _firebaseMethods.fetchAllUsers(user);
```
From the FirebaseMethods class
```
  Stream<DocumentSnapshot> getUserStream({@required String uid}) =>
      _userCollection.doc(uid).snapshots();

   Future<List<User>> fetchAllUsers(User currentUser) async {
    List<User> userList = List<User>();

    QuerySnapshot querySnapshot =
        await firestore.collection(USERS_COLLECTION).get();
    for (var i = 0; i < querySnapshot.docs.length; i++) {
      if (querySnapshot.docs[i].id != currentUser.uid) {
        userList.add(user.User.fromMap(querySnapshot.docs[i].data));
      }
    }
    return userList;
  }

```

**Comment by iapicca** [comment] 2021-01-18 10:39
> [...]  please provide [...] a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **that does not use 3rd party plugins**
> > The issue from the search screen.
> > 
> > ```dart
> > @override void initState() { super.initState();
> > _firebaseRepository.getCurrentUser().then((User user) {
> > ```

@jeremiahseun 
[firebase](https://firebase.flutter.dev/) is most definitely a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by jeremiahseun** [comment] 2021-01-18 10:44
Ooh... Already did. Thanks! 

I guess that the issue is from the Firebase code.

**Comment by pedromassangocode** [comment] 2021-01-18 13:49
Hi @...
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-18 13:49 UTC
Labels: in triage
