### ISSUE TITLE
getting error in custom bottom navigation bar after running

### ISSUE THREAD

**Issue by MohammedRedha126** [flutter/flutter#151584] opened 2024-07-11 11:28 UTC
### Steps to reproduce

I am customizing a bottom Navigation bar and I create a List of widgits and connect the list to bottom navigationn bar and after that I includ the bottom navigation bar to the files it need it to be included

in main.dart should I reffer my home screen as the navigation bar?

### Expected results

I expected that the code will work proparly without any error and the bottom navigation bar will work perfecte

### Actual results

I give me this error:

```
═════════════════════Exception caught by widgets library ══════════════════════════
The following assertion was thrown building ScrollNotificationObserver(state: ScrollNotificationObserverState#c1135):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5207 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    Scaffold Scaffold:file:///C:/Users/User/Desktop/Go_Gas_Flutter_and_Laravel/go_gas%20flutter/lib/Screens/Bottom%20Navigation%20Bar/home_screen.dart:20:15
```

### Code sample

<details open><summary>Code sample</summary>

code of bottom_nav_bar.dart:

```
import 'package:flutter/material.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/favorite.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/home_screen.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/more_options.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/search.dart';

class BottomNavBarScreen extends StatefulWidget {
  const BottomNavBarScreen({super.key});

  @override
  State<BottomNavBarScreen> createState() {
    return _BottomNavBarScreenState();
  }
}

class _BottomNavBarScreenState extends State<BottomNavBarScreen> {
  int screenIndex = 0;
  final screens=[
    const HomeScreen(),
    const Search(),
    const Favorite(),
    const MoreOptions(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(index: screenIndex, 
      children: screens,),
      


      bottomNavigationBar: BottomNavigationBar(
        currentIndex: screenIndex,
        onTap: (index) => setState(() {
          screenIndex = index;
        }),
        items: const [
          
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
            backgroundColor: Colors.blue,
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            label: 'Search',
            backgroundColor: Colors.blue,
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.favorite),
            label: 'Favorite',
            backgroundColor: Colors.blue,
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.more_horiz),
            label: 'More ',
            backgroundColor: Colors.blue,
          ),
        ],
      ),
    );
  }
}


code of home_screen.dart:
import 'package:flutter/material.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/bottom_nav_bar.dart';

class HomeScreen extends StatefulWidget{
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() {
    
    return _HomeScreenState();
  }
}


class _HomeScreenState extends State<HomeScreen>{
  @override
  Widget build(BuildContext context) {
    
    return const Center(
      child:  Scaffold(
        backgroundColor: Colors.white,
        body: Text('home', style: TextStyle(fontSize: 25),),



        bottomNavigationBar: BottomNavBarScreen(),
      ),
    );
  }
}

```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/152763896/a51ce608-e010-4a2e-b286-a868f77ee2e8)

![image](https://github.com/flutter/flutter/assets/152763896/a7664835-702d-4ee4-8df6-c0d8415e3770)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.91.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2024-07-11 13:01
@MohammedRedha126 
This is a code implementation issue at your end. Below is updated runnable code sample I came up with based on code you provided.

<details>
<summary> code </summary>

```

import 'package:flutter/material.dart';
import 'package:pointer_interceptor/pointer_interceptor.dart';
import 'package:flutter_web_plugins/url_strategy.dart';

void main() {
//  usePathUrlStrategy();
  runApp(MaterialApp(
    home: HomeScreen(),
  ));
}

class HomeScreen extends StatefulWidget{
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() {

    return _HomeScreenState();
  }
}


class _HomeScreenState extends State<HomeScreen>{
  @override
  Widget build(BuildContext context) {

    return const Center(
      child:  Scaffold(
        backgroundColor: Colors.white,
        body: Text('home', style: TextStyle(fontSize: 25),),



        bottomNavigationBar: BottomNavBarScreen(),
      ),
    );
  }
}

class BottomNavBarScreen extends StatefulWidget {
  const BottomNavBarScreen({super.key});

  @override
  State<BottomNavBarScreen> createState() {
    return _BottomNavBarScreenState();
  }
}

class _BottomNavBarScreenState extends State<BottomNavBarScreen> {
  int screenIndex = 0;
  final screens=[
    const HomeScreen(),
  //  const Search(),
  //  const Favorite(),
  //  const MoreOptions(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(index: screenIndex,
        children: screens,),



      bottomNavigationBar: BottomNavigationBar(
        currentIndex: screenIndex,
        onTap: (index) => setState(() {
          screenIndex = index;
        }),
        items: const [

          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
            backgroundColor: Colors.blue,
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            label: 'Search',
            backgroundColor: Colors.blue,
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.favorite),
            label: 'Favorite',
            backgroundColor: Colors.blue,
          ),

          BottomNavigationBarItem(
            icon: Icon(Icons.more_horiz),
            label: 'More ',
            backgroundColor: Colors.blue,
          ),
        ],
      ),
    );
  }
}

```

</details>

And your issue is here:

```
 final screens=[
    const HomeScreen(),
```

ie you have set the `HomeScreen` to be a child of itself.

Closing, as this is not a bug.

**Closed by darshankawar** 2024-07-11 13:01 UTC
Labels: in triage
