### ISSUE TITLE
pageView ScrollController attached to multiple scroll views.

### ISSUE THREAD

**Issue by gbbest15** [flutter/flutter#86549] opened 2021-07-16 12:22 UTC
i have seen so Answer but does not related to pageView. ``
for me to jumpTo next page i keep getting This error:
```
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'
```

this is my full code

<details>
<summary>Code Sample</summary>

```
Column(
                          children: [
                            Expanded(
                              child: Container(
                                height: MediaQuery.of(context).size.height * 10,
                                child: TinderSwapCard(
                                  swipeUp: true,
                                  swipeDown: true,
                                  orientation: AmassOrientation.BOTTOM,
                                  totalNum: userData.length,
                                  stackNum: 3,
                                  swipeEdge: 6.0,
                                  maxWidth:
                                      MediaQuery.of(context).size.width * 0.9,
                                  maxHeight:
                                      MediaQuery.of(context).size.height * 0.9,
                                  minWidth:
                                      MediaQuery.of(context).size.width * 0.8,
                                  minHeight:
                                      MediaQuery.of(context).size.width * 0.8,
                                  allowVerticalMovement: true,
                                  cardBuilder: (context, index) =>
                                      StreamBuilder(
                                          stream: firestore
                                              .collection('Image')
                                              .doc(userData[index].id)
                                              .collection('Photos')
                                              .orderBy('timestap')
                                              .snapshots(),
                                          builder: (context, snapshot) {
                                            if (!snapshot.hasData) {
                                              return Center(
                                                child:
                                                    CircularProgressIndicator(),
                                              );
                                            }
                                            return Container(
                                              child: Stack(
                                                fit: StackFit.passthrough,
                                                alignment: Alignment.center,
                                                children: [
                                                  PageView.builder(
                                                      pageSnapping: true,
                                                      onPageChanged: (pageNum) {
                                                        setState(() {
                                                          pageNumber = pageNum;
                                                        });
                                                      },
                                                      physics:
                                                          NeverScrollableScrollPhysics(),
                                                      controller:
                                                          _pageController,
                                                      itemCount: snapshot
                                                          .data.docs.length,
                                                      itemBuilder:
                                                          (ctx, index) {
                                                        return GestureDetector(
                                                          onTap: () {
                                                            _pageController
                                                                .jumpToPage(1);
                                                          },
                                                          child: Container(
                                                            child: Card(
                                                              semanticContainer:
                                                                  true,
                                                              clipBehavior: Clip
                                                                  .antiAliasWithSaveLayer,
                                                              child: Image(
                                                                image:
                                                                    NetworkImage(
                                                                  snapshot
                                                                          .data
                                                                          .docs[
                                                                              index]
                                                                          .data()[
                                                                      'picture'],
                                                                ),
                                                                fit:
                                                                    BoxFit.fill,
                                                              ),
                                                            ),
                                                          ),
                                                        );
                                                      }),
                                                  if (snapshot
                                                          .data.docs.length !=
                                                      1)
                                                    Padding(
                                                      padding: const EdgeInsets
                                                              .symmetric(
                                                          vertical: 8.0,
                                                          horizontal: 8.0),
                                                      child: Align(
                                                        alignment:
                                                            Alignment.topCenter,
                                                        child: Row(
                                                          children: [
                                                            Expanded(
                                                              child:
                                                                  StepProgressIndicator(
                                                                totalSteps:
                                                                    snapshot
                                                                        .data
                                                                        .docs
                                                                        .length,
                                                                currentStep:
                                                                    pageNumber +
                                                                        1,
                                                                selectedColor:
                                                                    Colors.red,
                                                                unselectedColor:
                                                                    Colors
                                                                        .yellow,
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                  if (direction.value <= -1 &&
                                                      index == currentIndex)
                                                    Padding(
                                                      padding:
                                                          const EdgeInsets.all(
                                                              15.0),
                                                      child: Align(
                                                        alignment:
                                                            Alignment.topRight,
                                                        child: Padding(
                                                          padding:
                                                              EdgeInsets.all(
                                                                  8.0),
                                                          child: Container(
                                                              height: 100,
                                                              width: 100,
                                                              child: Image.asset(
                                                                  'assets/Nope.png')),
                                                        ),
                                                      ),
                                                    ),
                                                  if (direction.value >= 1)
                                                    Padding(
                                                      padding:
                                                          const EdgeInsets.all(
                                                              15.0),
                                                      child: Align(
                                                        alignment:
                                                            Alignment.topLeft,
                                                        child: Padding(
                                                          padding:
                                                              EdgeInsets.all(
                                                                  8.0),
                                                          child: Container(
                                                            height: 100,
                                                            width: 100,
                                                            child: Image.asset(
                                                                'assets/Like.png'),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  PositionedDirectional(
                                                    bottom: 30,
                                                    child: GestureDetector(
                                                      onTap: () {},
                                                      child: Container(
                                                        decoration:
                                                            BoxDecoration(
                                                          borderRadius:
                                                              BorderRadius
                                                                  .circular(15),
                                                          color: Colors.white70,
                                                        ),
                                                        padding:
                                                            EdgeInsets.all(10),
                                                        width: 305,
                                                        height: 100,
                                                        child: Row(
                                                          children: [
                                                            Container(
                                                              child: Image(
                                                                image:
                                                                    NetworkImage(
                                                                  userData[
                                                                          index]
                                                                      .profilePicture,
                                                                ),
                                                                fit:
                                                                    BoxFit.fill,
                                                              ),
                                                            ),
                                                            SizedBox(
                                                              width: 15,
                                                            ),
                                                            Expanded(
                                                              child: Column(
                                                                crossAxisAlignment:
                                                                    CrossAxisAlignment
                                                                        .start,
                                                                children: [
                                                                  Text(
                                                                    userData[
                                                                            index]
                                                                        .name,
                                                                    overflow:
                                                                        TextOverflow
                                                                            .fade,
                                                                    maxLines: 1,
                                                                    softWrap:
                                                                        false,
                                                                    style:
                                                                        TextStyle(
                                                                      color: Colors
                                                                          .black,
                                                                      fontSize:
                                                                          20,
                                                                      fontWeight:
                                                                          FontWeight
                                                                              .bold,
                                                                    ),
                                                                  ),
                                                                  Text(
                                                                    'male',
                                                                    style:
                                                                        TextStyle(
                                                                      color: Colors
                                                                          .black,
                                                                      fontSize:
                                                                          15,
                                                                      fontWeight:
                                                                          FontWeight
                                                                              .bold,
                                                                    ),
                                                                  ),
                                                                  Flexible(
                                                                    child: Text(
                                                                      'i am blesses',
                                                                      style:
                                                                          TextStyle(
                                                                        color: Colors
                                                                            .black,
                                                                        fontSize:
                                                                            15,
                                                                      ),
                                                                    ),
                                                                  ),
                                                                ],
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 60,
                                                    bottom: 60,
                                                    child: GestureDetector(
                                                      onTap: () {},
                                                      child: Container(
                                                        height: 30,
                                                        decoration:
                                                            BoxDecoration(
                                                          borderRadius:
                                                              BorderRadius
                                                                  .circular(15),
                                                        ),
                                                        child: Icon(
                                                            Icons.play_arrow),
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            );
                                          }),
                                  cardController: controller,
                                  swipeUpdateCallback:
                                      (DragUpdateDetails details,
                                          Alignment align) {
                                    direction.value = align.x.round();
                                  },
                                  swipeCompleteCallback:
                                      (CardSwipeOrientation orientation,
                                          int index) async {
                                    /// Get orientation & index of swiped card
                                    direction.value = 0;
                                    if (orientation ==
                                        CardSwipeOrientation.DOWN) {
                                      //! add to favourite
                                      setState(() {
                                        currentIndex = index + 1;
                                        pageNumber = 0;
                                      });

                                      await ControllerApi().addtoLikes(
                                          userData[index].id, context);
                                    } else if (orientation ==
                                        CardSwipeOrientation.UP) {
                                      setState(() {
                                        currentIndex = index + 1;
                                        pageNumber = 0;
                                      });
                                      //! to view the profile

                                      // var returnid = await
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                          builder: (_) => MatchesProfile(
                                            viewId: userData[index].id,
                                          ),
                                        ),
                                      );
                                   
                                    } else if (orientation ==
                                        CardSwipeOrientation.LEFT) {
                                      setState(() {
                                        currentIndex = index + 1;
                                      });
                                      print('Remove from index.....');
                                    } else if (orientation ==
                                        CardSwipeOrientation.RIGHT) {
                                      //! to like... And match
                                      setState(() {
                                        currentIndex = index + 1;
                                        pageNumber = 0;
                                      });
                                      await ControllerApi()
                                          .addtoLikesWithMatches(
                                        userData[index].id,
                                        context,
                                      );
                                    }
                                  },
                                ),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(top: 55.0),
                              child: SizedBox(
                                height: 10,
                              ),
                            )
                          ],
                        ),

```
</details>

**Comment by maheshmnj** [comment] 2021-07-16 12:43
Hi @gbbest15,
Thanks for filing the issue, Please provide the output of flutter doctor -v along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), The code provided has lot of unknown variables and widgets, This helps to better investigate the issue.

Thank you.

**Comment by gbbest15** [comment] 2021-07-16 13:30
hi @maheshmnj thanks

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    en-NG)
    • Flutter version 2.2.2 at /Users/mac/Documents/Developer/flutter
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • CDD00C1F-71D5-411D-8D11-74DE2986BFCF • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114
```
here is the code that i am having issue with



```
Expanded(
                              child: Container(
                                height: MediaQuery.of(context).size.height * 10,
                                child: TinderSwapCard(
                                  swipeUp: true,
                                  swipeDown: true,
                                  orientation: AmassOrientation.BOTTOM,
                                  totalNum: userData.length,
                                  stackNum: 3,
                                  swipeEdge: 6.0,
                                  maxWidth:
                                      MediaQuery.of(context).size.width * 0.9,
                                  maxHeight:
                                      MediaQuery.of(context).size.height * 0.9,
                                  minWidth:
                                      MediaQuery.of(context).size.width * 0.8,
                                  minHeight:
                                      MediaQuery.of(context).size.width * 0.8,
                                  allowVerticalMovement: true,
                                  cardBuilder: (context, index) =>
                                      StreamBuilder(
                                          stream: firestore
                                              .collection('Image')
                                              .doc(userData[index].id)
                                              .collection('Photos')
                                              .orderBy('timestap')
                                              .snapshots(),
/// here i have to images in my firebase collection 
                                          builder: (context, snapshot) {
                                            if (!snapshot.hasData) {
                                              return Center(
                                                child:
                                                    CircularProgressIndicator(),
                                              );
                                            }
                                            return Container(
                                              child: Stack(
                                                fit: StackFit.passthrough,
                                                alignment: Alignment.center,
                                                children: [
                                                  PageView.builder(
                                                      pageSnapping: true,
                                                      onPageChanged: (pageNum) {
                                                        setState(() {
                                                          pageNumber = pageNum;
                                                        });
                                                      },
                                                      physics:
                                                          NeverScrollableScrollPhysics(),
                                                      controller:
                                                          _pageController,
                                                      itemCount: snapshot
                                                          .data.docs.length,
                                                      itemBuilder:
                                                          (ctx, index) {
                                                        return GestureDetector(
                                                          onTap: () {
//here if i click to jump to the next image in the swiping care it keeps showing me the error
                                                            _pageController
                                                                .jumpToPage(1);
                                                          },
                                                          child: Container(
                                                            child: Card(
                                                              semanticContainer:
                                                                  true,
                                                              clipBehavior: Clip
                                                                  .antiAliasWithSaveLayer,
                                                              child: Image(
                                                                image:
                                                                    NetworkImage(
                                                                  snapshot
                                                                          .data
                                                                          .docs[
                                                                              index]
                                                                          .data()[
                                                                      'picture'],
                                                                ),
                                                                fit:
                                                                    BoxFit.fill,
                                                              ),
                                                            ),
                                                          ),
                                                        );
                                                      }),
```

**Comment by maheshmnj** [comment] 2021-07-16 13:55
@gbbest15, The code provided has a lot of unknown variables, the minimal reproducible code should be directly runnable with minimal code changes and on top of that, this issue doesn't seem to describe a bug in the flutter framework or a feature request.
Please take a look at this [stackoverflow thread](https://stackoverflow.com/questions/56540074/how-to-jump-to-another-page-with-pageview-flutter).  Since this issue isn't about flutter but with your code I am going to go ahead and close this issue as invalid, Feel free to comment if you disagree, And I will reopen it.

 Thank you.

**Closed by maheshmnj** 2021-07-16 13:55 UTC
Labels: in triage
