### ISSUE TITLE
[image_picker] PlatformException(invalid_source, Invalid image source., null, null) on iPhone 11 (ios 15.5)

### ISSUE THREAD

**Issue by Aboneyx** [flutter/flutter#125618] opened 2023-04-27 10:17 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

in the ios 15.5 simulator, the selection of photos from the gallery does not work. 
image_picker: ^0.8.7+2

### Expected results

this works in the latest version of ios

### Actual results

in the ios 15.5 simulator, the selection of photos from the gallery does not work. 
image_picker: ^0.8.7+2

### Code sample

<details><summary>Code sample</summary>

```dart
 final image = await picker.pickImage(source: ImageSource.gallery);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://user-images.githubusercontent.com/79087226/234833037-c53daa9a-f61e-48c6-8769-a938abf915c3.png)

</details>

### Logs

<details><summary>Logs</summary>

```console
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(invalid_source, Invalid image source., null, null)
#0      ImagePickerApi.pickImage
messages.g.dart:136
<asynchronous suspension>
#1      ImagePickerIOS.getImageFromSource
image_picker_ios.dart:78
<asynchronous suspension>
#2      __ProdileEditScreenState._getImage
profile_edit_page.dart:63
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v 
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale ru-KZ)
    • Flutter version 3.7.12 on channel stable at /Users/rayyvon/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (9 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/rayyvon/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • iPhone 14 Pro Max (mobile) • 593DC49F-C551-4F4B-BF13-D816D2854487 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 11 Pro (mobile)     • 81053BFE-EF27-4EFF-AAA2-BCC2A19DC177 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!```

</details>

**Comment by huycozy** [comment] 2023-04-27 12:17
Hi @Aboneyx 
Can you please provide the complete output logs (`flutter run -v`) so that we may verify the issue properly? Also, what kind of image type have you picked?

Taking a look at the error message, it may be caused by [source type](https://github.com/flutter/packages/blob/c11149c63e2ed2101e1257b8e048aa1b923a98ed/packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin.m#L147) or [supported type](https://github.com/flutter/packages/blob/c11149c63e2ed2101e1257b8e048aa1b923a98ed/packages/image_picker/image_picker_ios/ios/Classes/FLTPHPickerSaveImageToPathOperation.m#L112).

**Comment by Aboneyx** [comment] 2023-04-27 17:49
I found out that this bug exists in versions below ios 16.1

**Comment by huycozy** [comment] 2023-04-28 04:51
I can reproduce this issue even with iOS 15.2 or iOS 16.4. And it only happens with a specific image (image has flowers above) whilst other images can display well. 

After checking image format, it's a `HEIC` image: `IMG_0006.HEIC` ([IMG_0006.HEIC.zip](https://github.com/flutter/flutter/files/11349906/IMG_0006.HEIC.zip)). This is a known issue that is being noted on the document (please see [iOS note](https://pub.dev/packages/image_picker#ios)). When I test this image on physical device, the issue doesn't happen.

Please retry on a physical device for HEIC format. I will close this issue as this is a foreseeable issue. If the crash still occurs on physical device, please write a comment and I will reopen this for further investigation. Thanks!

**Closed by huycozy** 2023-04-28 04:51 UTC
Labels: in triage
