### ISSUE TITLE
Calling Path.getBounds() has the side effect of making future calls to Path.shift() or Path.transform() to fail valid path assertions

### ISSUE THREAD

**Issue by gilbert-jolly** [flutter/flutter#69284] opened 2020-10-29 08:15 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add the following code before setState()
3. Run the code

```  
final path = Path()
      ..moveTo(0, 1)
      ..lineTo(1, 2);

path.getBounds();
final newPath = path.transform(Matrix4.identity().scaled(200, 200).storage);
newPath.getBounds();
final path2 = newPath.shift(Offset(100.0, -100));
```

**Expected results:** The path should be shifted

**Actual results:** 
Exception

<details>
  <summary>Logs</summary>

```

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/path/path_ref.dart:831:12
isValid
is not true
```

```
```

```
```

[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
[✓] Connected device (4 available)

• No issues found!
```
```

</details>

**Comment by darshankawar** [comment] 2020-10-29 09:04
Not sure if this is specific to web, because on Android, same code returns below error log:

<details>
<summary>android log</summary>

```

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following UnimplementedError was thrown while handling a gesture:
UnimplementedError

When the exception was thrown, this was the stack: 
#0      Matrix4.scale (package:vector_math/src/vector_math_64/matrix4.dart:886:7)
#1      Matrix4.scaled (package:vector_math/src/vector_math_64/matrix4.dart:908:65)
#2      _MyHomePageState._incrementCounter (package:newweb/main.dart:57:55)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:985:20)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1101:38)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#13d1b
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(308.7, 553.3)
  finalLocalPosition: Offset(20.7, 33.3)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
W/libEGL  (13512): EGLNativeWindowType 0xc7111808 disconnect failed
W/libEGL  (13512): EGLNativeWindowType 0xc7111008 disconnect failed
D/mali_winsys(13512): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
D/mali_winsys(13512): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
E/BpSurfaceComposerClient(13512): Failed to transact (-1)
E/BpSurfaceComposerClient(13512): Failed to transact (-1)
W/libEGL  (13512): EGLNativeWindowType 0xc116b808 disconnect failed
W/libEGL  (13512): EGLNativeWindowType 0xc7111008 disconnect failed

```

</details>
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.82, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-4.0.pre.82 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision e5814756a2 (2 days ago), 2020-10-27 01:47:03 -0700
    • Engine revision 1857470267
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.111

• No issues found!


```

</details>

<details>
<summary>web error log</summary>

```
For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/path/path_ref.dart:831:12
isValid
is not true

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
lib/_engine/engine/html/path/path_ref.dart 831:12                             debugValidate
lib/_engine/engine/html/path/path_ref.dart 350:5                              shiftedFrom
lib/_engine/engine/html/path/path.dart 63:27                                  shiftedFrom
lib/_engine/engine/html/path/path.dart 1281:19                                shift
packages/newweb/main.dart 59:26                                               [_incrementCounter]
packages/flutter/src/material/ink_well.dart 985:14                            [_handleTap]
packages/flutter/src/material/ink_well.dart 1101:38                           <fn>
packages/flutter/src/gestures/recognizer.dart 183:24                          invokeCallback
packages/flutter/src/gestures/tap.dart 598:48                                 handleTapUp
packages/flutter/src/gestures/tap.dart 287:5                                  [_checkUp]
packages/flutter/src/gestures/tap.dart 259:7                                  acceptGesture
packages/flutter/src/gestures/arena.dart 157:12                               sweep
packages/flutter/src/gestures/binding.dart 372:20                             handleEvent
packages/flutter/src/gestures/binding.dart 348:14                             dispatchEvent
packages/flutter/src/rendering/binding.dart 279:11                            dispatchEvent
packages/flutter/src/gestures/binding.dart 303:7                              [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 267:5                              handlePointerEvent
packages/flutter/src/gestures/binding.dart 225:7                              [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 208:32                             [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 895:13                            _invoke1
lib/_engine/engine/platform_dispatcher.dart 174:5                             invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 128:39                                [_onPointerData]
lib/_engine/engine/pointer_binding.dart 477:16                                <fn>
lib/_engine/engine/pointer_binding.dart 438:21                                <fn>
lib/_engine/engine/pointer_binding.dart 208:16                                <fn>

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#a84a0
════════════════════════════════════════════════════════════════════════════════════════════════════


```

</details>

**Comment by gilbert-jolly** [comment] 2020-10-29 09:27
I believe it is specific to web, the application runs fine on android and iOS, but fails on web

**Comment by ferhatb** [comment] 2020-10-29 16:02
duplicate of https://github.com/flutter/flutter/issues/68702 , PR to fix will be in master shortly.

**Closed by ferhatb** 2020-10-29 16:02 UTC
Labels: f: material design, found in release: 1.24, framework, has reproducible steps, passed first triage, platform-web
