### ISSUE TITLE
[Camera] Problem taking a photo with auto flash mode

### ISSUE THREAD

**Issue by brahimchebbi** [flutter/flutter#143690] opened 2024-02-19 09:36 UTC
### Steps to reproduce

1 - add the camera: ^0.10.5+9 in the pupspec.yaml
2- take a photo in a place where there is no light so that the flash turns on.

### Expected results

Normally the photo should be clear since the flash is on when the photo is taken

### Actual results

the photo is black 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';



void main() {
 runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: TakePicture()
        );
  }
}


class TakePicture extends StatefulWidget {
  const TakePicture({super.key});

  @override
  State<TakePicture> createState() => _TakePictureState();
}

class _TakePictureState extends State<TakePicture> {
  
  
  
   CameraController? cameraController;
  
  
  Future<void> initCamera() async {
    final cameras = await availableCameras();
    if (cameras.isEmpty) return;
    cameraController = CameraController(
      cameras[0],
      ResolutionPreset.veryHigh,
      enableAudio: false,
    );


    await cameraController!.initialize();
    Future.delayed(Duration.zero); // Attendre l'initialisation



    if (cameraController != null &&  cameraController!.value.isInitialized) {
      cameraController!.setFlashMode(FlashMode.auto);

    }
   

   
  }
    @override
  void initState() {
 initCamera();
    // TODO: implement initState
    super.initState();
  }
  
  @override
  Widget build(BuildContext context) {
   

    

    return Scaffold(
               
                body: Column(
                  children: [
                    Expanded(
                      child: AspectRatio(
                        // Plein écran
                        aspectRatio:
                            cameraController!.value.aspectRatio,
                        child: CameraPreview(cameraController!),
                      ),
                    ),
                  ],
                ),
                bottomNavigationBar: BottomAppBar(
                  color: Colors.black,
                  elevation: 0,
                  child: Padding(
                    padding: const EdgeInsets.symmetric(vertical: 10),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceAround,
                      children: [
                     
                        Stack(
                          alignment: Alignment.center,
                          children: [
                            IconButton(
                             
                              icon: Icon(Icons.camera_alt_outlined,
                                  color: Colors.white),
                              onPressed: () async {
                                final XFile? photo = await cameraController?.takePicture();

    if (photo == null) return;
                                
                              },
                            ),
                          
                         
                          ],
                        ),
                     
                      ],
                    ),
                  ),
                ),
              );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.6.3 22G436 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone de synertic XR. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone de brahim. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by dam-ease** [comment] 2024-02-19 11:42
Thanks for filing this @brahimchebbi.
The code sample shared has some bugs and refactoring this, I can't seem to reproduce the issue on my end.
Can you upgrade to the latest versions of flutter and test this again to see if it still reproduces?

**Comment by brahimchebbi** [comment] 2024-02-19 13:51
Thank you for your prompt response and suggestion. I've upgraded Flutter to the latest version and retested the code using the sample from https://pub.dev/packages/camera/example. However, the issue still persists on my end.
I think there is a delay between actually taking the photo and the flash turning off, that's why the image is not clear. I tested the photo taking with the native camera and the flash are not in sync like with the lib camera.

**Comment by sudhar08** [comment] 2024-02-19 15:12
I also faced the same issue. I think the bug is in  the camera plugin

**Comment by brahimchebbi** [comment] 2024-02-19 15:35
@sudhar08 Have you found a solution or a work around to resolve this problem?

**Comment by sudhar08** [comment] 2024-02-19 15:42
Not yet iam also still searching the solution 😞

**Comment by dam-ease** [comment] 2024-02-20 06:45
Hello @brahimchebbi @sudhar08
Thanks for your response.
I tried reproducing this on physical Android and iOS ( see videos below) and couldn't reproduce it, can you please share videos on your end as well including the device information on which this reproduces for you

| Android | iOS |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/53122008/cc3853dc-42a6-4a70-818a-d5794d88ebc4"> | <video src="https://github.com/flutter/flutter/assets/53122008/453510f6-7a5c-4b13-9bde-9ae218ecc6ae"> |

**Comment by sudhar08** [comment] 2024-02-20 07:10
**hello** @dam-ease here is my code  
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';



void main() {
 runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: TakePicture()
        );
  }
}


class TakePicture extends StatefulWidget {
  const TakePicture({super.key});

  @override
  State<TakePicture> createState() => _TakePictureState();
}

class _TakePictureState extends State<TakePicture> {
  
  
  
   CameraController? cameraController;
  
  
  Future<void> initCamera() async {
    final cameras = await availableCameras();
    if (cameras.isEmpty) return;
    cameraController = CameraController(
      cameras[0],
      ResolutionPreset.veryHigh,
      enableAudio: false,
    );


    await cameraController!.initialize();
    Future.delayed(Duration.zero); // Attendre l'initialisation



    if (cameraController != null &&  cameraController!.value.isInitialized) {
      cameraController!.setFlashMode(FlashMode.auto);

    }
   

   
  }
    @override
  void initState() {
 initCamera();
    // TODO: implement initState
    super.initState();
  }
  
  @override
  Widget build(BuildContext context) {
   

    

    return Scaffold(
               
                body: Column(
                  children: [
                    Expanded(
                      child: AspectRatio(
                        // Plein écran
                        aspectRatio:
                            cameraController!.value.aspectRatio,
                        child: CameraPreview(cameraController!),
                      ),
                    ),
                  ],
                ),
                bottomNavigationBar: BottomAppBar(
                  color: Colors.black,
                  elevation: 0,
                  child: Padding(
                    padding: const EdgeInsets.symmetric(vertical: 10),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceAround,
                      children: [
                     
                        Stack(
                          alignment: Alignment.center,
                          children: [
                            IconButton(
                             
                              icon: Icon(Icons.camera_alt_outlined,
                                  color: Colors.white),
                              onPressed: () async {
                                final XFile? photo = await cameraController?.takePicture();

    if (photo == null) return;
                                
                              },
                            ),
                          
                         
                          ],
                        ),
                     
                      ],
                    ),
                  ),
                ),
              );
  }
}

can you share your code also

**Comment by brahimchebbi** [comment] 2024-02-20 13:49
@dam-ease Here is a video that shows my black image problem even after the flash is on.

device : Google pixel 2 android 11

https://github.com/flutter/flutter/assets/36197788/58290a53-a8fa-48ab-9aab-a0a8386adc83

**Comment by dam-ease** [comment] 2024-02-21 06:49
Thanks for your responses @brahimchebbi @sudhar08.
@sudhar08 I'm testing with the example code here: https://pub.dev/packages/camera/example
I see you are on an Android device, I tested multiple times on my Android device and still can't reproduce it (another screen record below).

https://github.com/flutter/flutter/assets/53122008/71c39899-5095-4be7-9e82-17ef3fa27231

This might be device-specific but for one more test could you also check on the latest version `3.19.0` to see if it still reproduces for you?

**Comment by brahimchebbi** [comment] 2024-02-22 08:54
@dam-ease thank you for your response.
To reproduce the problem you have to take a photo in total darkness, there must be no light.
I did this with the example from the lib I got the image in black even if the flash turns on and I tested with the device's native camera I have a clear image.

**Comment by dam-ease** [comment] 2024-02-23 06:52
Thanks for your response and patience @brahimchebbi.
Tried this multiple times as well in a totally dark environment but can't seem to reproduce as well.
I'll be labelling this for more insights.
Thank you!

**Comment by stuartmorgan** [comment] 2024-02-27 20:42
@brahimchebbi Are you seeing this on any platforms other than Android, or is it Android-specific?

**Comment by brahimchebbi** [comment] 2024-03-04 15:22
@stuartmorgan i tested the lib only in android device

**Comment by camsim99** [comment] 2024-03-21 18:47
@brahimchebbi Can you try using `camera_android_camerax` (https://pub.dev/packages/camera_android_camerax) to see if that fixes the issue?

**Comment by reidbaker** [comment] 2024-04-04 18:37
Thank you for taking the time to file this issue. Without additional information, we're unfortunately not sure how to resolve this issue. I'm therefore reluctantly going to close this for now. Please don't hesitate to comment on the issue if you have any more information to add; we'll reopen it right away!

**Closed by reidbaker** 2024-04-04 18:37 UTC
Labels: platform-android, waiting for customer response, p: camera, package, team-android
