### ISSUE TITLE
RawKeyboardListener conflict with TextField

### ISSUE THREAD

**Issue by NickNevzorov** [flutter/flutter#121259] opened 2023-02-22 19:18 UTC
Wraping TextField by RawKeyboardListener , runing, 

1. TextField is inactive, press any key, event RawKeyboardListener.onKey working
2. Focus TextField, press any key, event RawKeyboardListener.onKey working
3. Unfocus TextField, press any key, event RawKeyboardListener.onKey **did not working** 
4. Focus TextField, press any key, event RawKeyboardListener.onKey working **again**
3. Unfocus TextField, press any key, event RawKeyboardListener.onKey **did not working** 

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(
      focusNode: FocusNode(),
      onKey: (RawKeyEvent event) async {
        print(event);
      },
      autofocus: true,
      child: Scaffold(
        body: TextField(),
      ),
    );
  }
}

```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.4, on Microsoft Windows [Version 10.0.22621.1265], locale ru-UA)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.74.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

```

**Comment by exaby73** [comment] 2023-02-23 10:25
I think this is occurring because of the focus is not on the `RawKeyboardListener` after you tap on the `TextField` and remove the focus. Try refocusing the `RawKeybaordListener` after the `unfocus` of the `TextField`

**Comment by NickNevzorov** [comment] 2023-03-08 07:53
> I think this is occurring because of the focus is not on the `RawKeyboardListener` after you tap on the `TextField` and remove the focus. Try refocusing the `RawKeybaordListener` after the `unfocus` of the `TextField`

RawKeybaordListener working only if TextField is focused. After removing focus from TextField RawKeybaordListener  did not working and did not listen key events

I solve my task by periodical checking allowed FocusNodes and refocus, but is not good

**Comment by exaby73** [comment] 2023-03-08 11:09
You can use a FocusNode and add a listener to it using `addListenner`, then check of the `RawKeyboardListener` has focus and focus it if it doesn't. This is working as intended there I will close this issue

**Closed by exaby73** 2023-03-08 11:09 UTC
Labels: in triage
