### ISSUE TITLE
error : definition of implicit copy assignment operator for 'Mat2D' is deprecated because it has a user-decl ared copy constructor

### ISSUE THREAD

**Issue by absalam48** [flutter/flutter#129340] opened 2023-06-22 09:23 UTC
C:\..\..\windows\flutter\ephemeral\.plugin_symlinks\rive_common\windows\..\ios\rive-cpp\include\rive/math/mat2
d.hpp(17,5): error : definition of implicit copy assignment operator for 'Mat2D' is deprecated because it has a user-decl
ared copy constructor [-Werror,-Wdeprecated-copy] [C:\..\..\build\windows\plugins\rive_common\rive_common_plug
in.vcxproj]

**Comment by huycozy** [comment] 2023-06-22 09:50
Hi @absalam48 
From what I can see, the issue is related to a 3rd party plugin ([rive_common](https://pub.dev/packages/rive_common)) rather than to Flutter itself. Please open the issue in the its [repository](https://github.com/rive-app/rive-flutter/issues) for better support.

Closing, as this isn't an issue with Flutter itself.

**Closed by huycozy** 2023-06-22 09:50 UTC
Labels: in triage
