### ISSUE TITLE
Why late non initialised variable isn't treated as null , hence can be checked

### ISSUE THREAD

**Issue by mshenawy22** [flutter/flutter#114288] opened 2022-10-29 11:20 UTC
If you created a late variable and for some reason it hasn't been initialised where it should be , There's no way to check if this variable is initialised before using it. 
Even comparing the variable to null won't work and you will end up with 

if you tried to check ithis variable against null before using it , you will still get an error LateInitializationError.

If my understanding is correct there's no way to check if a late var isn't initilaised yet , Is there a reason why the non initialised variable in this case can't be treated as Null variables and hence be checked ?

**Comment by stuartmorgan** [comment] 2022-10-29 11:49
See https://dart.dev/null-safety/understanding-null-safety#late-variables

Closing as this is the intended behavior of `late`.

> Is there a reason why the non initialised variable in this case can't be treated as Null variables

If you use a `late` non-nullable variable you've explicitly requested not to have that behavior. If you want to treat a variable as nullable, you need to declare it as such.

**Closed by stuartmorgan** 2022-10-29 11:49 UTC
