### ISSUE TITLE
Samsung phones running Android 14 stops drawing platform views on resume

### ISSUE THREAD

**Issue by lmk378** [flutter/flutter#139039] opened 2023-11-27 05:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run and change to other app, and back again.

### Expected results

WebViewWidget show same contents as before backgrounded.

### Actual results

Show white screen. no error.

### Code sample

Minimum code.

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late WebViewController webviewController;

  @override
  void initState() {
    super.initState();
    webviewController = createWebViewController('https://google.com');
  }

  WebViewController createWebViewController(String initialUrl) {
    final controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..loadRequest(Uri.parse(initialUrl));
    return controller;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: WebViewWidget(controller: webviewController),
    );
  }
}
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jasonzhijian98** [comment] 2023-11-27 11:57
I have the same issue on my Samsung Galaxy S22 Ultra when using flutter_inappwebview. The issue appears after switching to different applications then back to my app and the webview is blank but my app bar is still there and I'm able to interact with it but the webview doesn't reload. So far tested on another vivo phone and I'm unable to reproduce with it.

**Comment by huycozy** [comment] 2023-11-28 03:24
Looks like this only occurs on Samsung device with Android 14. 

@jbourny Could you please share the current `webview_flutter` version and the output of `flutter doctor -v`?

**Comment by lmk378** [comment] 2023-11-28 08:59
Hi @huycozy .
I test with `Don't keep activities` option enable and foregrounded, app restarted. It looks like launch app first time.
I've tested webview_flutter version 4.4.2 and 4.0.0 and have same issues.

**Comment by lmk378** [comment] 2023-11-28 09:02
`flutter docker -v`

[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2715], locale ko-KR)
    • Flutter version 3.13.6 on channel stable at C:\Programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (9 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\son.sh\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\son.sh\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\son.sh\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.3.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Users\son.sh\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9477386
    • Flutter plugin version 74.0.1
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Users\son.sh\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\son.sh\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\son.sh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (5 available)
    • SM S911N (mobile)            • R3CW302VKEF   • android-arm64  • Android 14 (API 34)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2715]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 119.0.6045.160
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 119.0.2151.72

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment] 2023-11-30 03:57
Adding `customer: crowd` label based on the number of upvotes.

**Comment by reidbaker** [comment] 2023-11-30 20:18
potentially a platform view issue. @johnmccutchan to take a look or reprioritize.

**Comment by jbourny** [comment] 2023-11-30 20:55
> webview_flutter

Hello, actually I was using inappwebview I forgot but I tried the sample code with webview and its the same problem.
I'm using webview_flutter 4.4.2.
This is my doctor output  : 

`[✓] Flutter (Channel stable, 3.16.1, on macOS 14.2 23C5030f darwin-arm64, locale fr-FR)
    • Flutter version 3.16.1 on channel stable at /Users/jonathanbourny/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (il y a 3 jours), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jonathanbourny/Library/Developer/Xamarin/android-sdk-macosx
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.85.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • SM S918B (mobile) • R5CW11WM8QV • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 14.2 23C5030f darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.`


This is the debug output when I run the app : 
`I/ViewRootImpl@4bd35cb[MainActivity](10770): mWNT: t=0xb400007d00399a80 mBlastBufferQueue=0xb400007d06a5bf00 fn= 31 caller= android.view.SyncRtSurfaceTransactionApplier.applyTransaction:96 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0:69 android.view.SyncRtSurfaceTransactionApplier.$r8$lambda$SgowXC58rj3PR958kHUfRgLZmvE:0 
D/InsetsController(10770): cancelAnimation of types: 3, animType: 0, host: com.example.webviewbug/com.example.webviewbug.MainActivity, from:android.view.InsetsController.notifyFinished:1727 android.view.InsetsAnimationControlImpl.applyChangeInsets:312 android.view.InsetsController.lambda$new$3:906 
I/ViewRootImpl@4bd35cb[MainActivity](10770): mWNT: t=0xb400007d00399c00 mBlastBufferQueue=0xb400007d06a5bf00 fn= 32 caller= android.view.SyncRtSurfaceTransactionApplier.applyTransaction:96 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0:69 android.view.SyncRtSurfaceTransactionApplier.$r8$lambda$SgowXC58rj3PR958kHUfRgLZmvE:0 
I/ViewRootImpl@4bd35cb[MainActivity](10770): mWNT: t=0xb400007d0039a980 mBlastBufferQueue=0xb400007d06a5bf00 fn= 32 caller= android.view.SyncRtSurfaceTransactionApplier.applyTransaction:96 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0:69 android.view.SyncRtSurfaceTransactionApplier.$r8$lambda$SgowXC58rj3PR958kHUfRgLZmvE:0 
I/ViewRootImpl@4bd35cb[MainActivity](10770): mWNT: t=0xb400007d0039bd00 mBlastBufferQueue=0xb400007d06a5bf00 fn= 32 caller= android.view.SyncRtSurfaceTransactionApplier.applyTransaction:96 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0:69 android.view.SyncRtSurfaceTransactionApplier.$r8$lambda$SgowXC58rj3PR958kHUfRgLZmvE:0 `

And when I minimize the App : 

`D/SurfaceView@4189fdb(11719): updateSurface: surface is not valid
I/SurfaceView@4189fdb(11719): releaseSurfaces: viewRoot = ViewRootImpl@4bd35cb[MainActivity]
I/ViewRootImpl@4bd35cb[MainActivity](11719): stopped(true) old = false
D/ViewRootImpl@4bd35cb[MainActivity](11719): WindowStopped on com.example.webviewbug/com.example.webviewbug.MainActivity set to true
D/SurfaceView@4189fdb(11719): updateSurface: surface is not valid
I/SurfaceView@4189fdb(11719): releaseSurfaces: viewRoot = ViewRootImpl@4bd35cb[MainActivity]
D/InputTransport(11719): Input channel destroyed: 'ClientS', fd=251
D/SurfaceView@4189fdb(11719): updateSurface: surface is not valid
I/SurfaceView@4189fdb(11719): releaseSurfaces: viewRoot = ViewRootImpl@4bd35cb[MainActivity]`

When I resume it (the webview is still visible) : 

`I/ViewRootImpl@4bd35cb[MainActivity](11719): MSG_WINDOW_FOCUS_CHANGED 0 0
D/InsetsSourceConsumer(11719): applyRequestedVisibilityToControl: visible=true, type=1
D/InsetsSourceConsumer(11719): applyRequestedVisibilityToControl: visible=true, type=2
I/ViewRootImpl@4bd35cb[MainActivity](11719): mWNT: t=0xb400007d6ccafa80 mBlastBufferQueue=0xb400007d173b8f00 fn= 5 caller= android.view.SyncRtSurfaceTransactionApplier.applyTransaction:96 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0:69 android.view.SyncRtSurfaceTransactionApplier.$r8$lambda$SgowXC58rj3PR958kHUfRgLZmvE:0 
I/ViewRootImpl@4bd35cb[MainActivity](11719): MSG_WINDOW_FOCUS_CHANGED 1 0
D/ViewRootImpl@4bd35cb[MainActivity](11719): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007d6cd83000}
D/InputMethodManagerUtils(11719): startInputInner - Id : 0
I/InputMethodManager(11719): startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus`

And when I minimize it, I open an other app (not using web renderer, for example the settings app) and the I come back to the example app : 

`I/ViewRootImpl@4bd35cb[MainActivity](11719): mWNT: t=0xb400007d1726b700 mBlastBufferQueue=0xb400007d173b8f00 fn= 2 caller= android.view.ViewRootImpl$6.onFrameDraw:5539 android.view.ViewRootImpl$2.onFrameDraw:2103 android.view.ThreadedRenderer$1.onFrameDraw:788 
I/ViewRootImpl@4bd35cb[MainActivity](11719): MSG_WINDOW_FOCUS_CHANGED 1 0
D/ViewRootImpl@4bd35cb[MainActivity](11719): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007d6cd83000}
D/InputMethodManagerUtils(11719): startInputInner - Id : 0
I/InputMethodManager(11719): startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
D/InsetsSourceConsumer(11719): applyRequestedVisibilityToControl: visible=false, type=8
I/ViewRootImpl@4bd35cb[MainActivity](11719): Resizing android.view.ViewRootImpl@cd07d1: frame = [0,0][1440,3088] reportDraw = false forceLayout = false syncSeqId = -1
I/ViewRootImpl@4bd35cb[MainActivity](11719): handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1440,3088] display=[0,0][1440,3088] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false`

Here I see behind the webview (white background).
I click somewhere in the webview area : 

`I/chromium(11719): [INFO:CONSOLE(184)] "Unrecognized feature: 'attribution-reporting'.", source: https://www.google.com/xjs/_/js/k=xjs.qs.fr.feOIkgeUJc0.O/ck=xjs.qs.bq_2PvZvhPs.L.W.O/am=EAAAAAIEAAAAABAAAIABACgAAAAAMArD4ZCADRAAIIAGEhwAAAABZIhCUMEAAGIEKHwzUAAAAAAAMAECMwGC5DMQEQAFAQCIBAohOwAAAAAO9gMi2AJAAAAABgAQCAALAXAAIUAJCAAAAKAfCDwIwEcRFgAAAAAAAAAAAAAYIIZgYuABCIAAAAAAAAAAAAAAAClBl4WHAIA/d=0/dg=2/br=1/ujg=1/rs=ACT90oF1l3zDQ8Ele9h267sKosxEQXR8Cw/m=sywf,sy39r,sy6l0,sy6l5,PrTY3,syzk,syzl,syzm,syzn,syzo,syzq,syzr,syzs,DOekCd,sy39s,symr,syms,symn,sy13z,sy1vu,sy27z,sy6l2,rRNiyd,sy46v,yPkEPb?cb=72433544&xjs=s3 (184)
I/chromium(11719): [INFO:CONSOLE(2)] "Powered by AMP ⚡ HTML – Version 2311171837000 https://www-bfmtv-com.cdn.ampproject.org/v/s/www.bfmtv.com/amp/politique/parlement/elisabeth-borne-sermonnee-a-l-assemblee-pour-vapotage-deux-jours-apres-le-plan-contre-le-tabac_AN-202311300421.html?amp_js_v=0.1&usqp=mq331AQIUAKwASCAAgM%3D#origin=https%3A%2F%2Fwww.google.com&prerenderSize=1&visibilityState=prerender&paddingTop=32&p2r=0&csi=1&aoh=17013771089752&viewerUrl=https%3A%2F%2Fwww.google.com%2Famp%2Fs%2Fwww.bfmtv.com%2Famp%2Fpolitique%2Fparlement%2Felisabeth-borne-sermonnee-a-l-assemblee-pour-vapotage-deux-jours-apres-le-plan-contre-le-tabac_AN-202311300421.html&history=1&storage=1&cid=1&cap=navigateTo%2Ccid%2CfullReplaceHistory%2Ceducation%2Cfragment%2CreplaceUrl%2CiframeScroll", source: https://cdn.ampproject.org/rtv/012311171837000/v0.mjs (2)`

I dont know if it can help but when we minimize and we resume the App we can see the webview flashing fastly (but not in this example).

Here is a video capture : https://drive.google.com/file/d/1j3XQPkx1IlLIPfX_DQ0qKxigK7LPJbzt/view?usp=drive_link

Thank you

**Comment by lmk378** [comment] 2023-12-01 00:31
@jbourny HI. 
Your video capture access denied. I request access permission.

**Comment by jbourny** [comment] 2023-12-01 06:55
I tried to install an other app who uses webview and effectively it has almost the same problem, I'm not certain he uses Flutter or not but the difference is when we resume his app it's white but when we begin to scroll or when we change screen orientation the webview is back.
I tried to set visibility off and on when this event occurs on the sample code but it doesn't work

**Comment by mossmana** [comment] 2023-12-01 18:37
I wasn't able to repro using a debug build from the latest code from flutter (main) and webview_flutter (main) with the `Don't keep activities` flag enabled and disabled. I'll try to narrow down which combination of versions may exhibit this broken behavior.

**Comment by mossmana** [comment] 2023-12-01 18:43
I tested with Samsung Galaxy S23 Ultra with T-mobile carrier provided OTA updates. It hasn't updated to Android 14 yet. It's still on 13 and did not exhibit the issue. Since it's my personal daily use device, I'd prefer to wait for the official OTA update.

@johnmccutchan I suggest obtaining a test device to repro and debug.

**Comment by mossmana** [comment] 2023-12-01 18:57
@lmk378 May I ask how you updated your device to Android 14? It is not yet available for my region/carrier.

**Comment by johnmccutchan** [comment] 2023-12-07 20:21
Flutter team will have a Samsung S23 phone next week and we can start investigating.

**Comment by wlekin** [comment] 2023-12-08 10:03
i have a pixel 7 pro running in android 14. the webview show blank page after the app resume from background. And if I tried using bannerAds in admob and webview at the same time, when slivergrid comes into the viewport, bannerAds shows crazy display errors, duplicating the webview screen.

- flutter 3.16.3, webview_flutter: ^4.4.2, google_mobile_ads: ^4.0.0.
- Android 14 AP11.231020.016.A1 in Pixel 7 Pro

![telegram-cloud-document-5-6307651131967277862_2](https://github.com/flutter/flutter/assets/7090968/ae16fb78-fda4-4cf6-bb49-620571864f37)
![telegram-cloud-document-5-6307651131967277862_8](https://github.com/flutter/flutter/assets/7090968/ed3f508a-216d-49b9-bb9c-0a5dde55bd71)

i commented in more detail in other thread https://github.com/flutter/flutter/issues/30111#issuecomment-1846658373

**Comment by johnmccutchan** [comment] 2023-12-08 22:04
Documenting what I've tried so far:

- I've traced the ImageReader backend:
   - The PlatformView continues to be rendered and frames are pushed to the native side.
   - Native code picks up frames and draws them (via `DlCanvas::DrawImageRect`)
- I tried forcing the SurfaceTexture backend (versus ImageReader) for Platform Views but it had the same problem.

The rest of the Flutter app continues to paint itself but not the platform view.

Issue #139630 is very similar, background an app and then restore it and then it stops painting itself. In this case it is the entire app and not just the platform view.

**Comment by johnmccutchan** [comment] 2023-12-08 22:39
I have also tried running with Impeller Vulkan and it doesn't work either.

**Comment by johnmccutchan** [comment] 2023-12-08 23:14
Using AGI I noticed one thing:

After resume the texture that should hold the contents of the platform view is FORMAT_U8 instead of FORMAT_RGBA8888. The texture also has an error 'Channel D not found in source format: S_U8'.

**Comment by johnmccutchan** [comment] 2023-12-08 23:16
[agi_traces.zip](https://github.com/flutter/flutter/files/13621659/agi_traces.zip)

**Comment by m-skolnick** [comment] 2023-12-13 16:17
Hi @johnmccutchan, any chance there is more info related to this? We are also attempting to come up with a fix, but we haven't had any luck.

**Comment by baonqscs** [comment] 2023-12-14 09:21
Any updates? I have same issue on Samsung S22 Android 14 One UI 6.

**Comment by wlekin** [comment] 2023-12-14 10:58
> Hi @johnmccutchan, any chance there is more info related to this? We are also attempting to come up with a fix, but we haven't had any luck. 

try resizing a container then restore it in after frame callback on app resume, that work for me some how.

**Comment by brennan-smith** [comment] 2023-12-14 17:25
3.7.3 here @johnmccutchan

**Comment by johnmccutchan** [comment] 2023-12-14 22:57
> > Hi @johnmccutchan, any chance there is more info related to this? We are also attempting to come up with a fix, but we haven't had any luck.
> 
> try resizing a container then restore it in after frame callback on app resume, that work for me some how.

What do you mean resizing a container? What code are you executing?

**Comment by Caronesse** [comment] 2023-12-15 08:15
> Can folks please report the Flutter versions that they've observed this bug with?

3.13.8 for me

**Comment by mxnortal** [comment] 2023-12-15 11:36
Our team also faced this issue. Reported on multiple Samsung devices: S22, S23, S22 Ultra, S23 Ultra. All were updated to Android 14 recently.

We use `WebViewWidget` from [webview_flutter](https://pub.dev/packages/webview_flutter). 

Flutter versions: `3.7.2` and latest `3.16.3`.


Stable reproducible example: Open app with webview -> switch to another app -> switch back to app.  Second step is important, otherwise if you just minimize app and then reopen it, issue will not reproduce.
Video with an example:

https://github.com/flutter/flutter/assets/138577948/9c8551ba-3d0c-4b59-9363-76e554f104ab


Temporary workaround: for us, the only temp solution was to reload WebView, something like this:

```dart
class _LoginPageState extends State<LoginPage> with WidgetsBindingObserver {
  bool _isInProgress = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _shouldReloadWebView();
    }
  }

  Future<void> _shouldReloadWebView() async {
    if (Platform.isAndroid) {
      try {
        var androidInfo = await DeviceInfoPlugin().androidInfo;
        var sdkInt = androidInfo.version.sdkInt;
        var manufacturer = androidInfo.manufacturer;

        if (sdkInt == 34 && manufacturer == 'samsung') {
          setState(() {
            _isInProgress = true;
          });

          Future.delayed(const Duration(milliseconds: 300), () {
            setState(() {
              _isInProgress = false;
            });
          });
        }
      } catch (_) {}
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

@override
  Widget build(BuildContext context) => _isInProgress
      ? const SizedBox.shrink()
      : WebViewWidget();

```

**Comment by RGTENG** [comment] 2023-12-19 09:51
Thanks for this issue ! Although I'm not the user for S23 Android 14, 
but  I have same issue on " Samsung A53 Android 14 " One UI 6.

**Comment by letrungdo** [comment] 2023-12-20 13:11
=> For fix: use HybridComposition for Android

Widget _buildWebView() {
    late WebViewWidget webViewWidget;
    if (_controller.platform is AndroidWebViewController) {
      final androidWebViewController = (_controller.platform as AndroidWebViewController);
      webViewWidget = WebViewWidget.fromPlatformCreationParams(
        params: AndroidWebViewWidgetCreationParams.fromPlatformWebViewWidgetCreationParams(
          AndroidWebViewWidgetCreationParams(
            controller: androidWebViewController,
          ),
          displayWithHybridComposition: true,
        ),
      );
    } else {
      webViewWidget = WebViewWidget(
        controller: _controller,
      );
    }
    return webViewWidget;
  }

**Comment by facundoduran** [comment] 2023-12-20 15:46
> ```dart
> DeviceInfoUtil().shouldHybridComposition()
> ```

Could you share the DeviceInfoUtil().shouldHybridComposition() implementation? Thanks!

**Comment by letrungdo** [comment] 2023-12-20 16:04
@facundoduran 
```dart
import 'dart:async';
import 'dart:io';
import 'package:device_info_plus/device_info_plus.dart';

class DeviceInfoUtil {
  factory DeviceInfoUtil() {
    return _singleton;
  }

  DeviceInfoUtil._internal();

  static final DeviceInfoUtil _singleton = DeviceInfoUtil._internal();
  final DeviceInfoPlugin _deviceInfo = DeviceInfoPlugin();
  late AndroidDeviceInfo _androidDeviceInfo;
  static const versionSupportHybrid = 30;

  Future<void> init() async {
    if (Platform.isAndroid) {
      _androidDeviceInfo = await _deviceInfo.androidInfo;
    }
  }

  bool shouldHybridComposition() {
    if (!Platform.isAndroid) {
      return false;
    }
    final sdkInt = _androidDeviceInfo.version.sdkInt;
    return sdkInt >= DeviceInfoUtil.versionSupportHybrid;
  }
}
```

**Comment by letrungdo** [comment] 2023-12-20 16:14
@facundoduran 
DeviceInfoUtil().shouldHybridComposition() = true if sdkInt >= 30

var androidInfo = await DeviceInfoPlugin().androidInfo;
var sdkInt = androidInfo.version.sdkInt;

**Comment by b4tchkn** [comment] 2023-12-29 13:20
We are checking with Samsung.
Our apps are having the same problem!
https://forum.developer.samsung.com/t/emergency-about-compatibility-between-flutter-and-samsung/28701

**Comment by xOldeVx** [comment] 2023-12-30 20:52
**This is not related to Samsung devices**, it also reproduces on an emulator in Android Studio with Android 14

**Comment by johnmccutchan** [comment] 2024-01-02 17:13
@xOldeVx I just tried to reproduce with your steps on an Android 14 emulator and could not reproduce.

**Comment by xOldeVx** [comment] 2024-01-03 07:54
@johnmccutchan try it:

code:
```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late InAppWebViewController webViewController;

  InAppWebViewSettings settings = InAppWebViewSettings(
    clearCache: true,
    useHybridComposition: false,
  );

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) {
      InAppWebViewController.setWebContentsDebuggingEnabled(false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.black,
      child: InAppWebView(
        initialSettings: settings,
        onWebViewCreated: (controller) => webViewController = controller,
        initialUrlRequest: URLRequest(url: WebUri.uri(Uri.parse('https://pub.dev'))),
      ),
    );
  }
}
```

versions:
```
compileSdkVersion 34
targetSdkVersion 34
flutter_inappwebview: ^6.0.0-beta.8
sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
Flutter version 3.13.1 on channel stable
Dart version 3.1.0
```

screenshot:
[Screen_recording_20240103_094558.webm](https://github.com/flutter/flutter/assets/24361103/7676e8a9-3aef-4064-b39d-335ac779bec5)

**Comment by johnmccutchan** [comment] 2024-01-03 14:57
I just tried running your exact code against Flutter 3.18 and cannot reproduce.

**Comment by wongcheehong** [comment] 2024-01-18 04:19
> @xOldeVx I just tried running your exact code against Flutter 3.18 and cannot reproduce.

What phone are you using? and what android version

**Comment by xOldeVx** [comment] 2024-01-18 05:05
@wongcheehong  Galaxy s22 Ultra and Galaxy s22, both Android 14

**Comment by wgardner** [comment] 2024-01-19 19:05
We are having this issue as well. I am personally using Galaxy S23+. Is there any hope for this being fixed soon?

**Comment by johnmccutchan** [comment] 2024-01-19 20:04
Samsung is actively investigating the issue as it is a bug in their version of Android. We hope to hear from them soon.

**Comment by doriansabo** [comment] 2024-01-24 10:11
I'm facing the same issue on both Android and iOS devices. 
`Flutter (Channel stable, 3.13.8, on macOS 14.1 23B74 darwin-arm64, locale en-RS)`
Plugin version:   webview_flutter: ^4.4.1

**Comment by dnfield** [comment] 2024-01-24 17:20
I think it's very likely that this is the same issue as #139630.

**Comment by rashidotm** [comment] 2024-02-08 10:13
> Samsung is actively investigating the issue as it is a bug in their version of Android. We hope to hear from them soon.

@johnmccutchan thanks for sharing this info. do you have a link to track their progress/update?

**Comment by dnfield** [comment] 2024-02-16 19:36
Unfortunately, this seems to be a somewhat different issue compared to https://github.com/flutter/flutter/issues/139630, although rotating the phone (which causes a relayout/surface creation) does get things rendering again.

**Comment by dnfield** [comment] 2024-02-16 22:06
https://github.com/flutter/engine/pull/50734 seems to make this issue goes away, but introduces some other regressions around first frame on resume.

**Comment by YuxuanDu** [comment] 2024-03-07 04:02
Any updates on this issue? When will the fixes be released? As more and more users upgraded Android to Android 14 we got many complaints about the issue.

**Comment by johnmccutchan** [comment] 2024-03-07 04:04
We are waiting on Samsung to respond.

**Comment by YuxuanDu** [comment] 2024-03-07 04:12
> We are waiting on Samsung to respond.

Thanks for the quick reply. I can see a fix has been merged, does that fixes the issue? Or is there a workaround we can try to temporarily solve the issue?

**Comment by johnmccutchan** [comment] 2024-03-07 06:08
The merged fix will be reverted because it broke other things that can't be worked around.

Samsung broke the Android API contract and we can't do anything but wait for them to fix it.

**Comment by agent515** [comment] 2024-03-07 07:26
> Or is there a workaround we can try to temporarily solve the issue?

@YuxuanDu eventually we replaced this package with InAppWebview as we couldn't find any quick workarounds in time. But even so I hope that Samsung fixes this issue soon for everyone..

**Comment by jmw11x** [comment] 2024-03-26 16:13
I have ran into this issue today. Considering never using flutter again after multiple instances of gaps in functionality.

**Comment by Nobler** [comment] 2024-04-01 07:15
Any updates?

**Comment by rashidotm** [comment] 2024-04-03 10:46
Is there a way to track this bug with Samsung? I remember reading that the target was end of march but I can't get a hand on it.

I guess they are also using a tracker to communicate with developers but I am unable to find a link to it. 

@johnmccutchan pls if you have it share it. or if you have a more concrete update on their progress do share it. or deny receiving any update if you haven't heard back from them.

**Comment by johnmccutchan** [comment] 2024-04-03 14:19
I suggest you reach out to Samsung and file bugs via their official bug reporting mechanism.

The Flutter project has no control over when Samsung releases a firmware with the bug fixes.

**Comment by jmw11x** [comment] 2024-04-03 18:17
> I suggest you reach out to Samsung and file bugs via their official bug reporting mechanism.
> 
> The Flutter project has no control over when Samsung releases a firmware with the bug fixes.

I take it because "Samsung broke the Android API contract and we can't do anything but wait for them to fix it." that while you have no control over the timeline of the fix, this assures us that Samsung will indeed fix the problem? Or is this incorrect.

**Comment by johnmccutchan** [comment] 2024-04-18 17:31
We now believe that this is a bug in some releases of Android 14 (and all releases of Android 15 betas).

Closing this issue, updates will be here: https://github.com/flutter/flutter/issues/146499

**Closed by johnmccutchan** 2024-04-18 17:31 UTC
Labels: e: device-specific, platform-android, customer: crowd, a: platform-views, p: webview, package, c: rendering, P1, e: samsung, team-android
