### ISSUE TITLE
Debugger stops at random line

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#81051] opened 2021-04-23 16:33 UTC
Dart's debugger is the worst debugger in a language I've ever used. I believe it's because Dart is optimizing code, and things just don't run linearly. I press F8 (I am using IntelliJ) and instead of going to the next line it just goes somewhere else. I have to add breakpoints into every line, and even so it never really works out. Sometimes I have to create variables just to be able to see values, since the debugger just doesn't show these values otherwise.

I was hoping I could tell the Dart compiler to turn off all optimizations, and see if the debugger stops being bad. I am tired of adding prints to my code.

**EDIT:** I was told it's expected behavior that when the debugger reaches an `await` keyword it can just go to some completely unrelated code which happens to be in the microtask queue. And that if I want to continue to the next line I should add a breakpoint. Why can't we press a special key that runs to the next line after the `await`? It would be just like a "force run to cursor" to the next line. Still, sometimes I can't read values, and it just jumps some code even if there's no async code. It seems related to optimizations, but I am just supposing.

**Comment by marcglasberg** [comment] 2021-04-23 16:39
Also, how do I prevent the debugger to enter internal Dart code? For example, just now it entered a file called `declared.dart`: "A class that manages the state of tests as they're declared."

**Comment by TahaTesser** [comment] 2021-04-26 09:34
Hi @marcglasberg 
Thanks for filing the issue

> Dart's debugger is the worst debugger in a language I've ever use. I believe it's because Dart is optimizing code, and things just don't run linearly. I press F8 (I am using IntelliJ) and instead of going to the next line it just goes somewhere else. I have to add breakpoints into every line, and even so it never really works out. Sometimes I have to create variables just to be able to see values, since the debugger just doesn't show these values otherwise.

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 

Not sure if it is related or even an issue but this is something I experienced.
When I set a breakpoint on `onPressed` and run the app, the app stops at launch and I see the following result. I've simply launched the app, the breakpoint is reached onPressed and you can see stop is at different line 

<img width="1116" alt="Screenshot 2021-04-26 at 12 30 33 PM" src="https://user-images.githubusercontent.com/48603081/116061547-a98a2500-a68b-11eb-8a14-1011ea7500e5.png">

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: ElevatedButton(
            onPressed: () {
              print('test');
            },
            child: Text('Button'),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554                        •
      android-x86    • Android 11 (API 30) (emulator)
    • Taha’s iPhone (mobile)  • 00008020-001059882212002E            • ios
      • iOS 14.4.2
    • iPhone 12 (mobile)      • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)         • macos                                •
      darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)            • chrome                               •
      web-javascript • Google Chrome 90.0.4430.85

• No issues found!
```
	
</details>

**Comment by marcglasberg** [comment] 2021-04-28 15:50
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [versÃ£o 10.0.19041.928], locale en-US)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\marcg.DESKTOP-LP3T69M\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.46

**Comment by marcglasberg** [comment] 2021-04-28 15:55
@TahaTesser I can't provide a minimal complete reproducible code sample. It all just happens, sometimes, when I am debugging. And also what I've been seeing is that I create some prints, and add a breakpoint in these lines. The debugger doesn't stop at those lines, but the information gets printed to the console.

I'd say the issue you've been experiencing is exactly this problem. So you already have a way to reproduce it.

**Comment by TahaTesser** [comment] 2021-04-29 06:40
@marcglasberg 
Since you confirm this is something the same, I will describe my steps to reproduce the issue from https://github.com/flutter/flutter/issues/81051#issuecomment-826677359

### Steps to reproduce 
1. Create any project `flutter create myapp` on any channel as of this writing
2. Launch the project in VS Code or Android Studio, reproduces on both
3. Set breakpoint any `onTap` or `onPressed` or use my code sample below
4. Launch in debug mode `F5` on VS Code or `Shift` + `F9` in Android Studio
5. Notice is launched, the breakpoint is hit but Text Widget is highlighted

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: ElevatedButton(
                onPressed: () {
                  print("something pressed");
                },
                child: Text('Something')),
          ),
        ),
      ),
    );
  }
}
``` 

</details>

**Comment by marcglasberg** [comment] 2021-04-29 15:56
I can't really reproduce this. For me it's stopping at the right place with your code above (I am using IntelliJ). Problem is, I thinks this problem is dependent on your machine configuration, your memory, the program you are running etc. I'd say the person who gets to work on fixing this will have to try it out until they find a situation where the bug is visible for them.

**Comment by yamauchieduardo** [comment] 2021-04-29 16:51
**I noticed another problems:**

1) If you use a breakpoint to stop the execution in a specific part of the code and you use the hot restart, sometimes the application stuck in a loop. To avoid that, usually I needed to remove all breakpoints to use the hot restart. This is a shame, I lose a lot of production time to avoid that.

2) When you run the debugger with simple Dart/Flutter unit test, if you update the code (test) sometimes the changes aren't noticed to the debugger, and the debugger runs the old version of the code. I lost a lot of time to understand that. This very strange because If you run the test with normal `run` this behavior don't appear.

I use the Intellij debugger for around 3 years programming with Flutter/Dart, and I ever noticed these problems. 
I don't trust in the debugger for Dart/Flutter debug because of theses problems.

**Comment by TahaTesser** [comment] 2021-04-30 12:43
@marcglasberg 
Since you can't reproduce the same, I am removing the labels, I might file a new issue 
Coming to this issue, since you can't provide reproducible details https://github.com/flutter/flutter/issues/81051#issuecomment-828570454 
This issue needs further triage

**Comment by Hixie** [comment] 2021-05-04 23:02
@marcglasberg What you describe doesn't sound like the behaviour we would expect. It's not what I see when debugging my own applications.

Can you check to see if it happens for you when debugging a simple app created using `flutter create foo`?

**Comment by darshankawar** [comment] 2021-06-04 13:13
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by marcglasberg** [comment] 2021-06-04 18:44
@Hixie @darshankawar Sorry for taking that long to respond. Actually, no, I can't see the problem in some random project I create with `flutter create foo`. We do have a very large codebase, and it's difficult to create a minimum code to reproduce this.

However, @TahaTesser did find a problem in his code too, as he stated above. So the problem does exist and has been seen by at least two people in this thread.

**Comment by fernando-s97** [comment] 2021-07-13 17:22
I'm also facing this exactly issue. I've thought it was only me. With me it also happen randomly, so I can't give a code to reproduce

**Comment by AndreRidho** [comment] 2022-12-25 16:29
I have experienced this error a number of times and I find that the line the debugger points to (without any explanation) is always inside a custom method that returns the type Widget. I make methods like this to reuse widgets that have a lot of code, e.g. replacing a Text widget with 10 lines of styling with myTextWidget(text). It's a shame this issue exists, because it forces me to duplicate massive amounts of code.

Some things that I also notice:
- This doesn't happen every single time I shorten code using this method. Some of my custom methods are safe, while others are not. However, when this issue does happen, the debugger stubbornly latches onto whatever line it pointed to and no amount of reloads or restarts can change the outcome.
- This error persists even when using a try catch block.

My code:

```
import 'dart:convert';

import 'package:autoyard/domain/entities/vehicle.dart';
import 'package:autoyard/presentation/bloc/bloc/autoyard_bloc.dart';
import 'package:autoyard/presentation/widgets/loading_screen.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:intl/intl.dart';

class VehicleHistoryPage extends StatelessWidget {
  const VehicleHistoryPage({super.key});

  @override
  Widget build(BuildContext context) {
    List argList = ModalRoute.of(context)!.settings.arguments as List;
    Map vehicleHistory = json.decode(argList[0]);
    Vehicle vehicle = argList[1];
    int hex = argList[2];
    return BlocListener<AutoyardBloc, AutoyardState>(
        listener: (context, state) {
          if (state is LoadingState) {
            Navigator.pushNamedAndRemoveUntil(
                context, '/loading', (route) => false);
          }
        },
        child: WillPopScope(
            onWillPop: () async {
              BlocProvider.of<AutoyardBloc>(context)
                  .add(GetVehicleEvent(vehicle.vin, hex, vehicle.picId));
              return false;
            }, //pop to loading screen with boolean that instructs to pop again
            child: Scaffold(
              appBar: AppBar(
                title: const Text('Vehicle History'),
                backgroundColor: const Color(0xFF1B1464),
                leading: BackButton(
                  onPressed: () async => BlocProvider.of<AutoyardBloc>(context)
                      .add(GetVehicleEvent(vehicle.vin, hex, vehicle.picId)),
                ),
              ),
              body: SingleChildScrollView(
                  child: Padding(
                      padding: const EdgeInsets.all(15),
                      child: Column(
                        children: [
                          gateSection("Gate 1 In", 'gate 1', vehicleHistory),
                          gateSection(
                              "Yard Parking", 'yard parking', vehicleHistory),
                          gateSection("Yard Out", 'yard out', vehicleHistory),
                          gateSection("Gate 2 Out", 'gate 2', vehicleHistory),
                          gateSection("Gate 3 In", 'gate 3', vehicleHistory),
                          gateSection("Gate 4 Out", 'gate 4', vehicleHistory),
                        ],
                      ))),
            )));
  }

  Widget subheading(String text) {
    return Text(
      text,
      style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 17),
    );
  }

  Widget gateSection(String title, String gate, Map vehicleHistory) {
    if (vehicleHistory[gate]['admitted'] == null) {
      return const SizedBox();
    } else {
      String formatDate = "";
      try {
        formatDate = DateFormat('h:mm a, EEEE, dd-MM-yyyy')
            .format(DateTime.parse(vehicleHistory[gate]['admitted']));
      } catch (e) {
        print("error: $e");
        formatDate = "-";
      }
      // print("formatDate: $formatDate");
      try {
        return const SizedBox();
      } catch (e) {
        print("error: $e");
        return const SizedBox();
      }
    }
  }
}
```


Before the Flutter page above can be built, the app crashes and the debugger points to the return const SizedBox() line (the second to last return const SizedBox() in line 79) with absolutely no explanation.

**Comment by TahaTesser** [comment] 2023-08-16 09:13
@christopherfujino 

Ran the sample code sample from [here](https://github.com/flutter/flutter/issues/81051#issuecomment-826677359) and now it stop on FAB even tho the breakpoint is on `ElevatedButton.onPressed` 




https://github.com/flutter/flutter/assets/48603081/8459a593-afa4-4ebf-af04-76e2a4c17609

**Comment by DanTup** [comment] 2023-08-22 11:39
I can reproduce what is in @TahaTesser's comment above, but it's not clear to me that this is not the correct behaviour.

The breakpoint is added to the line starting "onPressed" which puts it _outside_ of the function. The line it appears to stop on seems like the first statement/expression that would be executed at runtime after that point (the FAB constructor invocation). If you remove "const" from the `Text()` constructor, then it would instead stop there.

It's not clear to me if the expectation is that the breakpoint goes _inside_ the function (if so, I think it should be placed on the first line inside the function), or it should stop on the line starting "onPressed" (but that doesn't seem like a valid location to stop to me).

**Comment by DanTup** [comment] 2023-08-22 12:01
@TahaTesser your example has `const` which means that instance is created up-front and not at the time that code is hit. I believe if you remove `const` you'll see it stop there.

**Comment by a-siva** [comment] 2024-06-13 00:04
//cc @derekxu16

**Comment by derekxu16** [comment] 2024-06-25 22:06
I have recently landed some changes to the debugger to make it attempt to resolve a breakpoint as soon as it is requested, instead of waiting for the function containing the breakpoint to be compiled. Here is the tracking issue that provides more context regarding that change: https://github.com/Dart-Code/Dart-Code/issues/4734. I have confirmed that when running @TahaTesser's sample on a version of Flutter that includes my changes, starting a debugging session now makes a resolved breakpoint get set immediately on the `onPressed: () {` line, instead of one being set one a line below that.

My changes are available in `master` channel builds of Flutter that contain the commit https://github.com/flutter/flutter/commit/c9f72d5da64a95180e901da9011839cd460a28ae. Since this issue is old, and @TahaTesser's sample was the only reproduction provided, I will be closing this issue. If you see unexpected breakpoint behaviour when using a version of Flutter that includes my changes, please file new issues in the [dart-lang/sdk](https://github.com/dart-lang/sdk) issue tracker with detailed descriptions of the behaviour you're seeing (and if possible, repro steps/projects). Thanks!

**Closed by derekxu16** 2024-06-25 22:06 UTC
Labels: tool, dependency: dart, a: debugging, d: devtools
