### ISSUE TITLE
Android splash screen is dark even though light theme is activated

### ISSUE THREAD

**Issue by MrBananaPants** [flutter/flutter#79137] opened 2021-03-26 11:25 UTC
Since updating my app, there are two new files that allow for using custom splash screen images. When not specifying a splash screen image, it should be either white or black depending on the user's OS theme (light or dark).

However, when my phone is set to light mode, the splash screen always shows a black screen.
This is the file for the light mode splash screen found in ``android/app/src/main/res/drawable-v21/launch_background.xml``:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Modify this file to customize your launch splash screen -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="?android:colorBackground" />

    <!-- You can insert your own image assets here -->
    <!-- <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/launch_image" />
    </item> -->
</layer-list>
```

And this is for the dark theme splash screen found at ``android/app/src/main/res/values-night/styles.xml ``:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is on -->
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```

As you can see, the dark mode file clearly specifies ``@android:style/Theme.Black.NoTitleBar``. That means the light mode splash screen should be another color (white) but it isn't.

Flutter doctor:
```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-arm, locale
    en-BE)
    • Flutter version 2.0.3 at /Users/joranvancoillie/tools/flutter
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/joranvancoillie/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-03-26 12:49
Hi @MrBananaPants 
It depends on your code, do you have to any await in your startup code, are you using any plugins?  what device you're using for this? Can you please try another device or emulator
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by MrBananaPants** [comment] 2021-03-26 15:02
Hi @TahaTesser 
I'm using a Pixel 3a. It also happens on the Android Emulator. It happens in the default flutter application with the res folder I attached (extract it in app/src/main/ folder)
[res.zip](https://github.com/flutter/flutter/files/6212626/res.zip)

**Comment by TahaTesser** [comment] 2021-03-29 09:05
Hi @MrBananaPants 
I can't reproduce it on the `stable` channel on emulator (Pixel 3a) or physical device (Oneplus 8)
`values-night/styles.xml ` correctly shows black on launch, it's not really splash screen btw you haven't enabled splash screen in `launch_background.xml`.


| Default | Dark theme |
| --------------- | --------------- |
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/112812317-a6e4e180-9085-11eb-9e91-48a75d9b47cf.gif) | ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/48603081/112813544-f8da3700-9086-11eb-8475-f9b2397bf6f4.gif)




<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (10 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30)
      (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 11.2.3 20D91
      darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```
	
</details>

**Comment by MrBananaPants** [comment] 2021-03-29 09:08
If you mean Android version with API, my physical Pixel 3a is running the Android 12 Developer Preview (DP2) and the Pixel 3a emulator is running 11 I think (https://github.com/google/android-emulator-m1-preview). Both of these devices (physical and emulator) showed the black animation when not using dark mode.

**Comment by TahaTesser** [comment] 2021-03-30 06:45
Hi @MrBananaPants 
In your project, [default](https://github.com/MrBananaPants/StarTracker/blob/master/android/app/src/main/res/values/styles.xml) `style.xml` also has black in it, same as [night theme](https://github.com/MrBananaPants/StarTracker/blob/master/android/app/src/main/res/values-night/styles.xml), that's the reason you're seeing a dark launch screen even if the device theme is light

It should be light in default style.xml, you can create a new project and compare 
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is off -->
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```

After correcting default style, i can see white launch screen in your app as well 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-30 06:45 UTC
Labels: in triage

**Comment by MrBananaPants** [comment] 2021-03-30 06:52
Thanks for helping me! But the issue is that Flutter itself made it black by default in the style.xml file. I never edited the file, that's also why it says "initial commit". Shouldn't this be `Theme.Light.NoTitleBar` by default in the `style.xml` file instead of `Theme.Black.NoTitleBar` like the night theme `styles.xml`?

**Comment by TahaTesser** [comment] 2021-03-30 09:58
@MrBananaPants 
I tried a new project with `stable` and `master` both have the correct style.xml

**Comment by MrBananaPants** [comment] 2021-03-30 10:14
I'll close this issue since it is no longer existent. Thanks for your help.
