### ISSUE TITLE
Flake in windows integration.shard tool tests (socketexception failed to create server socket)

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#74073] opened 2021-01-15 21:16 UTC
See https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858008542344509392/+/steps/run_test.dart_for_tool_tests_shard_and_subshard_integration/0/stdout#L6706_0

Log text: 

```
 16:12 +36 ~2 -1: test\integration.shard\flutter_immediately_exit_test.dart: flutter_tools gracefully handles quick app shutdown [E]                                                                    
   Expected: contains 'Error connecting to the service protocol:'
     Actual: 'Unhandled exception:\n'
               'SocketException: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.\n'
               ', errno = 10048), address = 127.0.0.1, port = 9109\n'
               '#0      serveDevTools (package:devtools_server/src/server.dart:199:5)\n'
               '<asynchronous suspension>\n'
               '#1      serveDevToolsWithArgs (package:devtools_server/src/server.dart:72:10)\n'
               '<asynchronous suspension>\n'
               'Failed to launch DevTools: TimeoutException after 0:00:10.000000: Future not completed\n'
               '\n'
               ''
   
   package:test_api                                                expect
   test\integration.shard\flutter_immediately_exit_test.dart 32:7  main.<fn>
   
 Failed to delete C:\b\s\w\ir\tmp\t\flutter_run_test.e32b2176: FileSystemException: Deletion failed, path = 'C:\b\s\w\ir\tmp\t\flutter_run_test.e32b2176' (OS Error: The process cannot access the file because it is being used by another process.
 , errno = 32)
```

Looks like we're trying to reuse the same port/IP twice on Windows sometimes.

**Comment by jmagman** [comment] 2021-01-19 22:18
Duplicate of https://github.com/flutter/flutter/issues/74052.

**Closed by jmagman** 2021-01-19 22:18 UTC
Labels: passed first triage, platform-windows, team: presubmit flakes, tool
