### ISSUE TITLE
BottomNavigationBar has little to no contrast if it has at least 4 items

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#108484] opened 2022-07-27 21:27 UTC
Note that this issue is reproducible on <https://dartpad.dev/>

## Steps to Reproduce

1. Run the code sample on DartPad or on desktop (reproduced with Linux) 
2. Look at the bottom navigation bar

**Expected results:** Colors are rendered properly (see screenshots)

**Actual results:** Colors are rendered improperly, with very low contrast that's not usable (see screenshots)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: 0,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.looks_one_outlined),
            label: 'Single color',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.color_lens_outlined),
            label: 'Multi color',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.waves_outlined),
            label: 'Wave',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.flash_on),
            label: 'Flash',
          ),
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +47 ms] executing: uname -m
[  +20 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/rgabriel/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] executing: [/home/rgabriel/flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[  +11 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] 3.0.5
[   +6 ms] executing: [/home/rgabriel/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/rgabriel/flutter/] git ls-remote --get-url origin
[   +1 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +55 ms] executing: [/home/rgabriel/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +38 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +58 ms] Skipping pub get: version match.
[  +30 ms] Found plugin quick_usb at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/quick_usb-0.4.0/
[   +8 ms] Found plugin url_launcher at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.5/
[   +1 ms] Found plugin url_launcher_android at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.17/
[   +3 ms] Found plugin url_launcher_ios at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[   +1 ms] Found plugin url_launcher_linux at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[   +1 ms] Found plugin url_launcher_macos at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +1 ms] Found plugin url_launcher_web at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.12/
[   +1 ms] Found plugin url_launcher_windows at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +33 ms] Found plugin quick_usb at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/quick_usb-0.4.0/
[   +3 ms] Found plugin url_launcher at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.5/
[        ] Found plugin url_launcher_android at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.17/
[        ] Found plugin url_launcher_ios at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[   +1 ms] Found plugin url_launcher_linux at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[        ] Found plugin url_launcher_macos at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[   +1 ms] Found plugin url_launcher_web at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.12/
[        ] Found plugin url_launcher_windows at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[  +40 ms] Generating
/home/rgabriel/Projects/maingear_keyboard_lights/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistran
t.java
[  +73 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents:
/home/rgabriel/Projects/maingear_keyboard_lights/.dart_tool/package_config_subset,/home/rgabriel/Projects/maingear_key
board_lights/.dart_tool/flutter_build/dart_plugin_registrant.dart}
[  +11 ms] Found plugin quick_usb at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/quick_usb-0.4.0/
[   +2 ms] Found plugin url_launcher at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.1.5/
[        ] Found plugin url_launcher_android at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.17/
[        ] Found plugin url_launcher_ios at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.17/
[        ] Found plugin url_launcher_linux at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-3.0.1/
[        ] Found plugin url_launcher_macos at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-3.0.1/
[        ] Found plugin url_launcher_web at /home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.12/
[        ] Found plugin url_launcher_windows at
/home/rgabriel/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-3.0.1/
[   +5 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +3 ms] /home/rgabriel/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/rgabriel/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/rgabriel/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.EBMRSA/flutter_tool.LPBHOK/app.dill --packages
/home/rgabriel/Projects/maingear_keyboard_lights/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --source
/home/rgabriel/Projects/maingear_keyboard_lights/.dart_tool/flutter_build/dart_plugin_registrant.dart --source
package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///home/rgabriel/Projects/maingear_keyboard_lights/.dart_tool/flutter_build/dart
_plugin_registrant.dart --enable-experiment=alternative-invalidation-strategy
[  +16 ms] Building Linux application...
[  +14 ms] <- compile package:maingear_keyboard_lights/main.dart
[   +1 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/rgabriel/Projects/maingear_keyboard_lights/linux
[  +53 ms] -- Configuring done
[        ] -- Generating done
[        ] -- Build files have been written to: /home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug
[   +3 ms] executing: ninja -C build/linux/x64/debug install
[  +10 ms] ninja: Entering directory `build/linux/x64/debug'
[+1720 ms] [1/9] Generating
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/rgabriel/Projects/maingear_keyboard_lights/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +2 ms] [  +51 ms] executing: uname -m
[        ] [  +23 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +4 ms] executing: [/home/rgabriel/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] [        ] executing: [/home/rgabriel/flutter/] git tag --points-at
f1875d570e39de09040c8f79aa13cc56baab8db1
[   +2 ms] [   +9 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] [        ] 3.0.5
[        ] [   +7 ms] executing: [/home/rgabriel/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/rgabriel/flutter/] git ls-remote --get-url origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +43 ms] executing: [/home/rgabriel/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +39 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +64 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +29 ms] Initializing file store
[        ] [   +6 ms] Done initializing file store
[        ] [  +27 ms] Skipping target: gen_localizations
[        ] [   +8 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +331 ms] Skipping target: unpack_linux
[        ] [ +288 ms] Skipping target: kernel_snapshot
[        ] [ +203 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +7 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 996ms.
[        ] [ +103 ms] ensureAnalyticsSent: 100ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[  +34 ms] [2/7] Linking CXX shared library plugins/quick_usb/libquick_usb_plugin.so
[  +20 ms] [3/7] Linking CXX shared library plugins/url_launcher_linux/liburl_launcher_linux_plugin.so
[ +322 ms] [4/7] Building CXX object CMakeFiles/maingear_keyboard_lights.dir/flutter/generated_plugin_registrant.cc.o
[  +32 ms] [5/7] Building CXX object CMakeFiles/maingear_keyboard_lights.dir/my_application.cc.o
[ +135 ms] [6/7] Linking CXX executable intermediates_do_not_run/maingear_keyboard_lights
[        ] [6/7] Install the project...
[   +5 ms] -- Install configuration: "Debug"
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/maingear_keyboard_lights
[   +1 ms] -- Set runtime path of
"/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/maingear_keyboard_lights" to
"$ORIGIN/lib"
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/icudtl.dat
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/lib/libquick_usb_plugin.so
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/lib/libusb-1.0.23.so
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/lib/liburl_launcher_linux_plugin.so
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_i
cons
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_i
cons/assets
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_i
cons/assets/CupertinoIcons.ttf
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/font_awesom
e_flutter
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/font_awesom
e_flutter/lib
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/font_awesom
e_flutter/lib/fonts
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/font_awesom
e_flutter/lib/fonts/fa-brands-400.ttf
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/font_awesom
e_flutter/lib/fonts/fa-regular-400.ttf
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/packages/font_awesom
e_flutter/lib/fonts/fa-solid-900.ttf
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-
Regular.otf
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing:
/home/rgabriel/Projects/maingear_keyboard_lights/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[   +9 ms] Building Linux application... (completed in 2,375ms)
[ +200 ms] Observatory URL on device: http://127.0.0.1:44849/5TzW5oRommY=/
[   +5 ms] Caching compiled dill
[  +56 ms] Connecting to service protocol: http://127.0.0.1:44849/5TzW5oRommY=/
[ +114 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:44849/5TzW5oRommY=/.
[  +66 ms] DDS is listening at http://127.0.0.1:46109/6h3w_arqniA=/.
[  +50 ms] Successfully connected to service protocol: http://127.0.0.1:44849/5TzW5oRommY=/
[ +237 ms] DevFS: Creating new filesystem on the device (null)
[  +15 ms] DevFS: Created new filesystem on the device
(file:///tmp/maingear_keyboard_lightsFNVSVM/maingear_keyboard_lights/)
[   +2 ms] Updating assets
[  +78 ms] Syncing files to device Linux...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:maingear_keyboard_lights/main.dart 8cacc15c-1974-4138-b7c1-842be878bd99
[        ] <- 8cacc15c-1974-4138-b7c1-842be878bd99
[   +1 ms] Bundle processing done.
[  +59 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 63ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +1 ms] Connected to _flutterView/0x55677afdffb0.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:46109/6h3w_arqniA=/
[ +748 ms] The Flutter DevTools debugger and profiler on Linux is available at:
                    http://127.0.0.1:9101?uri=http://127.0.0.1:46109/6h3w_arqniA=/
[+5016 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device
(file:///tmp/maingear_keyboard_lightsFNVSVM/maingear_keyboard_lights/)
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] "flutter run" took 9,701ms.
[  +26 ms] ensureAnalyticsSent: 23ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing maingear_keyboard_lights...                                   
No issues found! (ran in 1.1s)
```

```
[✓] Flutter (Channel stable, 3.0.5, on Arch Linux 5.18.14-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.0.5 at /home/rgabriel/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/rgabriel/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/rgabriel/Android/Studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.23.2
    • ninja version 1.8.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/rgabriel/Android/Studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 5.18.14-arch1-1
    • Chrome (web)    • chrome • web-javascript • Chromium 103.0.5060.134 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

If there are 3 items, colors are rendered properly:

![image](https://user-images.githubusercontent.com/24363938/181374159-023fe748-0745-4854-a8b5-22ee473068d8.png)

But if there are 4 items or more, items are white on white background:

![image](https://user-images.githubusercontent.com/24363938/181374252-436f63b6-385e-40ee-acdb-5ce1c1c0a4c1.png)

On dark modes, the bug still occurs:

![image](https://user-images.githubusercontent.com/24363938/181374411-e62f5bb0-d2e9-40a1-8deb-a889a555ad4a.png)

![image](https://user-images.githubusercontent.com/24363938/181374325-41d4abd8-8fae-4879-8e04-304c7a6517b3.png)

**Comment by gabrc52** [comment] 2022-07-28 00:19
I'm working around this bug by overriding the colors manually:

```dart
            /// Manually override colors to workaround https://github.com/flutter/flutter/issues/108484
            selectedItemColor: const Color(0xffe2c1a4),
            selectedLabelStyle: const TextStyle(color: Color(0xffe2c1a4)),
            unselectedItemColor: const Color(0xffbcbbba),
            unselectedLabelStyle: const TextStyle(color: Color(0xffbcbbba)),
```

**Comment by danagbemava-nc** [comment] 2022-07-28 09:05
Hi @gabrc52, this is working as documented in https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html. See also https://github.com/flutter/flutter/issues/13642#issuecomment-371875044

You can fix this by changing the BottomNavigationBarType to fixed, instead of shifting or providing colors as you have. 

There is a proposal open requesting the behavior be improved in https://github.com/flutter/flutter/issues/73177. You can upvote the issue so it gets more attention. 

For now, I'll be closing this as working as intended. 

Thank you

**Closed by danagbemava-nc** 2022-07-28 09:05 UTC
Labels: in triage
