### ISSUE TITLE
google map in flutter

### ISSUE THREAD

**Issue by parthdomadiay23** [flutter/flutter#48173] opened 2020-01-04 12:01 UTC
in flutter application such a terrible use of google map. really it's very dangerous all time because flutter works only one-time work good with google Maps if I refresh UI or restart the app, then error. and nothing happens next, such a terrible experience, if google cant solved it, I assure new developers leave this platform.

```bash
Error is
**Exception has occurred.**
PlatformException (PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:189)
	at android.app.ActivityThread.main(ActivityThread.java:7183)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
, null))

```

**Comment by hauketoenjes** [comment] 2020-01-04 13:03
Duplicate of #45695

**Comment by iapicca** [comment] 2020-01-06 11:04
Hi @parthdomadiay23 
as @hauketoenjes pointed out (thank you)
there's an open issue addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-01-06 11:04 UTC
