### ISSUE TITLE
Flutter macOS desktop: Freezes in release build mode

### ISSUE THREAD

**Issue by ethanblake4** [flutter/flutter#61899] opened 2020-07-20 20:46 UTC
I'm creating a macOS desktop application. It works well in debug and profile mode, but when running in release mode it will work for 2-20 seconds and then freeze. When it freezes, there is no output or error messages of any kind - perhaps there would be if I ran it from Xcode, but I can't get release mode to work from Xcode at the moment (issue for another day). Resizing the app when it is frozen will simply stretch its last displayed frame as if it were a bitmap.

I've tried to reproduce this with other Flutter applications on macOS, but they seem to work fine, so it must be something specific to my application. I'd rather not share my code publicly at the moment, so if there's a way I can send it to a Flutter team member privately please let me know.

<details>
  <summary>Logs</summary>
(no logs since I am running in release mode)

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.75, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.21.0-2.0.pre.75 at /Users/ethanelshyeb/fluttersdk/flutter
    • Framework revision 3577da53ff (4 hours ago), 2020-07-20 09:54:50 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ethanelshyeb/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 4.0 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

! Doctor found issues in 2 categories.
```

</details>

**Comment by jonahwilliams** [comment] 2020-07-20 21:05
We need stack traces/errors/logs to make this issue actionable.

> so if there's a way I can send it to a Flutter team member privately please let me know.

We cannot look at code that is not released under an open source license. I recommend trying to come up with a minimal reproduction that does not depend on your application and sharing that publicly

**Comment by ethanblake4** [comment] 2020-07-20 21:53
@jonahwilliams Ok, I traced it to the following code:

```dart
class AstWidget extends StatefulWidget {
  const AstWidget();

  @override
  _AstWidgetState createState() => _AstWidgetState();
}

class _AstWidgetState extends State<AstWidget> {
  @override
  Widget build(BuildContext context) {
    Future.delayed(
      Duration(milliseconds: 4),
      () {
        final el = toDiagnosticsNode(name: "astWidget").getProperties()[2] as ObjectFlagProperty<StatefulElement>;
        print((el.value.renderObject as RenderBox).localToGlobal(Offset.zero));
      },
    );
    /// other stuff here that doesn't matter
    return Text("No widget");
  }
}
```

This is clearly a strange code pattern and it's easy to see why it might be invalid. That said, it's strange that it works in both debug and profile mode, as well as for at least a few frames of release mode, but then fails.

**Comment by jonahwilliams** [comment] 2020-07-20 22:17
Why don't you wrap that logic in a try/catch with a print to see what is failing?

**Comment by jonahwilliams** [comment] 2020-07-20 22:20
I'm almost certain this freeze is just a regular UI bug. If your widget has properties that are excluded from release mode you'll get some amount of NoSuchMethodError or  otherrwise

**Comment by ethanblake4** [comment] 2020-07-20 22:23
The problem is that since I'm running in release mode (and the problem doesn't occur in debug or profile mode), I can't see the output of print() or any exceptions that are logged. Unless there's a way to do that that I'm not aware of.

**Comment by stuartmorgan** [comment] 2020-07-20 22:40
> since I'm running in release mode [...] I can't see the output of print()

Why not?

**Comment by ethanblake4** [comment] 2020-07-20 23:12
> Why not?

Am I going crazy? I've never been able to see print() output in release mode. Just to make sure, I put this as the very first line in my `main.dart`: (I have other calls to print() in various places too).
```dart
void main() {
  print('Hello from Flutter');
  // ... etc
}
```
And ran using ` flutter run -d macos --release`.
The only output I get in the console is:
```
Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
```

**Comment by stuartmorgan** [comment] 2020-07-20 23:18
```
$ build/macos/Build/Products/Release/Testbed.app/Contents/MacOS/Testbed 
flutter: Hello from Flutter
```

Flutter run may not hook output up to the terminal in release mode (@jonahwilliams is that intentional?) but the output still exists.

**Comment by jonahwilliams** [comment] 2020-07-20 23:20
seems like an oversight, let me take a look

**Comment by jonahwilliams** [comment] 2020-07-20 23:25
Fix is:

```
diff --git a/packages/flutter_tools/lib/src/desktop_device.dart b/packages/flutter_tools/lib/src/desktop_device.dart
index 937bfcd61e..aaef7cc218 100644
--- a/packages/flutter_tools/lib/src/desktop_device.dart
+++ b/packages/flutter_tools/lib/src/desktop_device.dart
@@ -118,10 +118,10 @@ abstract class DesktopDevice extends Device {
     _runningProcesses.add(process);
     unawaited(process.exitCode.then((_) => _runningProcesses.remove(process)));
 
+    _deviceLogReader.initializeProcess(process);
     if (debuggingOptions?.buildInfo?.isRelease == true) {
       return LaunchResult.succeeded();
     }
-    _deviceLogReader.initializeProcess(process);
     final ProtocolDiscovery observatoryDiscovery = ProtocolDiscovery.observatory(_deviceLogReader,
       devicePort: debuggingOptions?.deviceVmServicePort,
       hostPort: debuggingOptions?.hostVmServicePort,
```

I'll put together a PR later today

**Comment by ethanblake4** [comment] 2020-07-20 23:30
Interesting, glad that's fixed!

So @stuartmorgan this is actually very interesting. When I run it directly as you suggest, I now indeed get an error being printed repeatedly to the terminal:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: RangeError (length): Invalid value: Valid value range is empty: 2
#0      _AstWidgetState.build.<anonymous closure> (package:iona_flutter/plugin/dart/ui/ast_widget.dart)
#1      new Future.delayed.<anonymous closure> (dart:async/future.dart:325)
#2      _rootRun (dart:async/zone.dart:1182)
#3      _CustomZone.run (dart:async/zone.dart:1093)
#4      _CustomZone.runGuarded (dart:async/zone.dart:997)
#5      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037)
#6      _rootRun (dart:async/zone.dart:1190)
#7      _CustomZone.run (dart:async/zone.dart:1093)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021)
#9      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:401)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)
```

However, the app now **does not freeze**, (and in fact continues to work as expected, since in this case the error is occurring isolated in a Future callback and has no side-effects). So it seems the freezing issue only happens when it is being run from `flutter run`.

**Comment by TahaTesser** [comment] 2020-07-21 08:27
Hi @ethanblake4 
I cannot reproduce the freeze issue in release mode even after 20 sec

<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: AstWidget(),
      ),
      floatingActionButton: FloatingActionButton.extended(
          label: Text('next'),
          icon: Icon(Icons.arrow_right),
          onPressed: () {
            Navigator.push(
                context, MaterialPageRoute(builder: (_) => Second()));
          }),
    );
  }
}

class AstWidget extends StatefulWidget {
  const AstWidget();

  @override
  _AstWidgetState createState() => _AstWidgetState();
}

class _AstWidgetState extends State<AstWidget> {
  @override
  Widget build(BuildContext context) {
    Future.delayed(
      Duration(milliseconds: 4),
      () {
        final el = toDiagnosticsNode(name: "astWidget").getProperties()[2]
            as ObjectFlagProperty<StatefulElement>;
        print((el.value.renderObject as RenderBox).localToGlobal(Offset.zero));
      },
    );

    /// other stuff here that doesn't matter
    return Text("No widget");
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton:
          FloatingActionButton(child: Icon(Icons.add), onPressed: () {}),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.83, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.83 at /Users/taha/Code/flutter_master
    • Framework revision 9e658bc3d5 (6 hours ago), 2020-07-21 03:56:07 +0200
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

```

</details>

**Comment by ethanblake4** [comment] 2020-07-21 19:00
@TahaTesser did you try resizing the window? you need to make sure that the widget is forced to rebuild

**Comment by TahaTesser** [comment] 2020-07-22 09:13
Hi @ethanblake4 
Yes, i cannot reproduce the issue even after window resizes and rebuilding the widget 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.94, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-2.0.pre.94 at /Users/taha/Code/flutter_master
    • Framework revision adc9dde3ba (10 hours ago), 2020-07-21 16:17:23 -0700
    • Engine revision 5a73d4dc25
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by ethanblake4** [comment] 2020-08-04 02:28
@TahaTesser Sorry for the delay. can you try wrapping it in a LayoutBuilder like this:

```dart
child: LayoutBuilder(builder: (context, c) {
    return AstWidget();
})
```
This way it is forced to rebuild every frame.
Then resize the window for a few seconds and it should freeze.

**Comment by TahaTesser** [comment] 2020-08-04 08:33
Hi @ethanblake4 
Added `LayoutBuilder` the code sample, still not able to reproduce this issue with lots of resizes and setState

<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(child: LayoutBuilder(
        builder: (context, c) {
          return AstWidget();
        },
      )),
      floatingActionButton: FloatingActionButton.extended(
          label: Text('next'),
          icon: Icon(Icons.arrow_right),
          onPressed: () {
            Navigator.push(
                context, MaterialPageRoute(builder: (_) => Second()));
          }),
    );
  }
}

class AstWidget extends StatefulWidget {
  const AstWidget();

  @override
  _AstWidgetState createState() => _AstWidgetState();
}

class _AstWidgetState extends State<AstWidget> {
  @override
  Widget build(BuildContext context) {
    Future.delayed(
      Duration(milliseconds: 4),
      () {
        final el = toDiagnosticsNode(name: "astWidget").getProperties()[2]
            as ObjectFlagProperty<StatefulElement>;
        print((el.value.renderObject as RenderBox).localToGlobal(Offset.zero));
      },
    );

    /// other stuff here that doesn't matter
    return Text("No widget");
  }
}

class Second extends StatefulWidget {
  @override
  _SecondState createState() => _SecondState();
}

class _SecondState extends State<Second> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () {
            setState(() {});
          }),
    );
  }
}
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.160, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-6.0.pre.160 at /Users/taha/Code/flutter_master
    • Framework revision 31ee51a302 (8 hours ago), 2020-08-03 17:27:21 -0700
    • Engine revision fa16c3d0ba
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6
    • iPhone 11 (mobile)     • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 84.0.4147.105

• No issues found!

```

</details> 

I cannot reproduce this issue on latest `master` channel.
Can you upgrade to master and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by TahaTesser** [comment] 2020-08-25 13:31
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-25 13:31 UTC
