### ISSUE TITLE
IDE gets slower and slower over time until it stops working

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#33280] opened 2019-05-23 22:26 UTC
```
$ flutter --version

Flutter 1.6.0 • channel dev • git@github.com:flutter/flutter.git
Framework • revision ed90d05596 (9 days ago) • 2019-05-14 17:09:29 -0700
Engine • revision 832cdacc6f
Tools • Dart 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)
```

I am using:

- Visual Studio Code (`Version 1.33.1 (1.33.1)`)
- Dart and Flutter Plugins (`3.0.2`)

I have a moderate-sized Flutter application (hobby app). I can't reproduce this with a specific series of steps, but generally this happens every single time:

- I run the application and use hot reload (on save) to debug/iterate.
- The analyzer/auto-complete gets slower and slower until it does nothing.

For example, here is what the IDE shows:

![Screen Shot 2019-05-23 at 3 21 29 PM](https://user-images.githubusercontent.com/168174/58290404-77b90700-7d6e-11e9-97ff-36505984cf36.png)

You can see the following diagnostic being shown:

```json
{
	"resource": "/Users/.../lib/src/pages/squads.dart",
	"owner": "dart",
	"code": "missing_function_body",
	"severity": 8,
	"message": "A function body must be provided.\nTry adding a function body.",
	"source": "dart",
	"startLineNumber": 65,
	"startColumn": 3,
	"endLineNumber": 65,
	"endColumn": 4,
	"tags": []
}
```

This is wrong, and is based on what I wrote 30+ seconds ago, and isn't updating. Even closing/opening the file again does nothing (the same diagnostics show up).

Once I get to this state, hot reload/restart and even the "stop" button also stop functioning, so it's possible this is some sort of bug/leak on the IDE side instead of the analyzer, I can't exactly tell. Even `killall dart` does not work. I can close the IDE and re-open it, but that's it. 

Note that I see `Analyzing...` in the lower bottom-left corner during this.

**Comment by gsbhasin123** [comment] 2019-05-23 22:52
Have you tried restarting your computer

**Comment by matanlurey** [comment] 2019-05-23 23:48
@gsbhasin123:
> Have you tried restarting your computer

I don't think that is related, this is over the course of weeks.

---

OK, so I already hit this again 30 minutes later. In this case, the IDE again is still functioning (including hot reload on save), but anything that seems to use the analyzer does not function:

![Screen Shot 2019-05-23 at 4 46 35 PM](https://user-images.githubusercontent.com/168174/58293452-637b0700-7d7a-11e9-8714-dfabf941cd75.png)

FWIW, VS Code detected a crash:

![Screen Shot 2019-05-23 at 4 47 37 PM](https://user-images.githubusercontent.com/168174/58293517-8ad1d400-7d7a-11e9-82d9-0e749e69cc51.png)

After this, hot reload/restart also stopped functioning.

**Comment by jonahwilliams** [comment] 2019-05-23 23:51
cc @DanTup @devoncarew

**Comment by DanTup** [comment] 2019-05-24 06:38
> Note that I see Analyzing... in the lower bottom-left corner during this.

I wonder if you're seeing https://github.com/Dart-Code/Dart-Code/issues/1692. Do you have the `dart.analyzerObservatoryPort` setting set? If so, try removing it and see if the issue goes away (if so, you can install [vNext beta](https://github.com/Dart-Code/Dart-Code/releases) for a better fix). That issue is caused by the VM sometimes unexpectedly pausing on handled exceptions (https://github.com/dart-lang/sdk/issues/36911) when we use `--observe` (which should only pause on unhandled exceptions) - but since we really want pausing on uncaught ones either, vNext switches from `--observe` to `--enable-vm-service`.

If that doesn't help, please enable the [analysis server log file](https://dartcode.org/docs/settings/#dartanalyzerlogfile). It'll overwrite itself on each load of VS and log all communication with the server. Then when you next see it, grab a copy of the log.

**Comment by matanlurey** [comment] 2019-05-24 23:30
Interesting, because I explicitly chose `Start Without Debugging`.

I'll try anyway @DanTup and report back.

**Comment by matanlurey** [comment] 2019-05-25 00:04
So, I ran and checked the ideas you had. I don't see anything suspicious, though, and the slow downs (and eventually crapping out) still happens. Is there anything specific I should be looking for in any of these logs?

**Comment by DanTup** [comment] 2019-05-25 07:48
> Start Without Debugging

The Observatory setting I mentioned is for the analyzer server (we have it to help debug the server) and not the project you're running directly. However, it may be unrelated - I think I saw this behaviour last night. I'd been working for a couple of hours and the editor started to feel laggy. I didn't have that setting enabled. I grabbed a copy of my log (which unfortunately is *massive* because it's about 6 hours of hacking) and will dig through it soon.

> Is there anything specific I should be looking for in any of these logs?

I'm not entirely sure yet, as I'm still not sure what sort of thing could cause things like this. My guess is that it's a Dart-Code issue (and the same reported at https://github.com/Dart-Code/Dart-Code/issues/1721), but I'll leave this issue open here until I've done some a little digging.

**Comment by DanTup** [comment] 2019-05-27 08:09
I saw this again last night, but the extension host crashed and restarted right as I tried to take a profile (possibly enabling profiling pushed it over the edge). I posted more details in https://github.com/Dart-Code/Dart-Code/issues/1721#issuecomment-496120647.. there were warnings in the dev console about possible leaked handlers, so I'll see if I can track this down.

The only significant thing I'm aware that's changed recently is the support for completing unimported symbols, so I wonder if there are bugs in my handling of that.

**Comment by DanTup** [comment] 2019-05-27 14:06
I've been doing some testing today, and although I can't reproduce memory running away, the performance of completions in large projects (esp. those refrencing Flutter) is unacceptably bad. In the next release (expected to ship at the end of the week) I'm [disabling completion for unimported files](https://github.com/Dart-Code/Dart-Code/issues/1751) by default (you can still opt-in if you really want) while I work on improving the performance and reducing memory allocations.

Until the release ships, you can set `"dart.autoImportCompletions": false` in your settings to disable ot yourself.

If you do see this behaviour even with it disabled, please let me know!

I'll close this a a dupe of https://github.com/Dart-Code/Dart-Code/issues/1721/https://github.com/Dart-Code/Dart-Code/issues/1750 because I don't think there's anything to do in Dart/Flutter here, I think it's entirely down to the VS Code extension.

**Closed by DanTup** 2019-05-27 14:06 UTC
Labels: severe: crash, tool

**Comment by DanTup** [comment] 2019-05-28 09:40
FWIW, I found what seems like a leak in VS Code (https://github.com/microsoft/vscode/issues/74446). Turning off auto-import completions will not solve it, but it should reduce its impact (due to less completions). I'm reverting my change to automatically disable them for the next release, as I expect VS Code will ship a fix for this very soon after (I believe their release is 1-2 weeks away, and this is being looked at now).

**Comment by DanTup** [comment] 2019-05-29 07:57
(Hopefully) Final update: This has been fixed in VS Code. I've verified it in the Insiders build and they're targeting Jun 6th for release.
