### ISSUE TITLE
DrawerItem does not update after setState()

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#640] opened 2015-11-30 23:07 UTC
Repro:
- Run widgets/pageable_list.dart
- Tap the menu button in the top left to open the drawer.
- Tap *Vertical Layout*.

Note that the vertical layout takes effect, but the *Vertical Layout* DrawerItem is not selected.
If you open and close the drawer, then it will be correctly selected.

**Comment by abarth** [comment] 2015-11-30 23:12
Duplicate of #187

**Closed by abarth** 2015-11-30 23:12 UTC
