### ISSUE TITLE
[path_provider] Add a fallback if xdg-user-dirs is not available 

### ISSUE THREAD

**Issue by lexxxel** [flutter/flutter#74392] opened 2021-01-21 09:38 UTC
## Steps to Reproduce

1. have a Linux system without `xdg-user-dirs` installed
1. try to use `path_provider::getApplicationDocumentsDirectory` 
2. that will call `xdg_directories::getUserDirectory`
3. that will fail if the `xdg-user-dir` executable can not be found

**Expected results:** 
Documentation, about host dependencies.

**Actual results:** 
This dependency is not documented, as far as I could see.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment] 2021-01-21 11:33
We should probably just add a hard-coded fallback in path_provider, rather than document the dependency (especially since it's a common transitive dependency, so people may never see the docs).

**Comment by TahaTesser** [comment] 2021-01-21 12:00
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () async {
            print(await getApplicationDocumentsDirectory());
          },
        ),
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>logs</summary> 

```bash
[  +53 ms] executing: [/home/taha/Code/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +23 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[        ] executing: [/home/taha/Code/flutter_master/] git tag --points-at eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[   +8 ms] Exit code 0 from: git tag --points-at eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[   +1 ms] executing: [/home/taha/Code/flutter_master/] git describe --match *.*.* --long --tags eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[  +20 ms] Exit code 0 from: git describe --match *.*.* --long --tags eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[        ] 1.26.0-1.0.pre-448-geeb7c261f2
[  +26 ms] executing: [/home/taha/Code/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/taha/Code/flutter_master/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +26 ms] executing: [/home/taha/Code/flutter_master/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +32 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +40 ms] executing: /home/taha/Code/SDK/platform-tools/adb devices -l
[  +10 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +40 ms] executing: /home/taha/Code/SDK/platform-tools/adb devices -l
[  +12 ms] Skipping pub get: version match.
[  +20 ms] Found plugin path_provider at /home/taha/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[   +3 ms] Found plugin path_provider_linux at /home/taha/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /home/taha/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +2 ms] Found plugin path_provider_windows at /home/taha/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +67 ms] Found plugin path_provider at /home/taha/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[        ] Found plugin path_provider_linux at /home/taha/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[        ] Found plugin path_provider_macos at /home/taha/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +1 ms] Found plugin path_provider_windows at /home/taha/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +13 ms] Generating /home/taha/AndroidStudioProjects/master_flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +62 ms] Initializing file store
[   +5 ms] Skipping target: gen_localizations
[   +2 ms] complete
[   +3 ms] Launching lib/main.dart on Linux in debug mode...
[   +3 ms] /home/taha/Code/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/taha/Code/flutter_master/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/taha/Code/flutter_master/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.XCXPEJ/flutter_tool.JJUOFM/app.dill --packages /home/taha/AndroidStudioProjects/master_flutter/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +11 ms] Building Linux application...
[  +18 ms] <- compile package:master_flutter/main.dart
[   +1 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/taha/AndroidStudioProjects/master_flutter/linux
[   +6 ms] List of devices attached
[   +1 ms] List of devices attached
[  +24 ms] -- Configuring done
[   +4 ms] -- Generating done
[        ] -- Build files have been written to: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug
[   +2 ms] executing: ninja -C build/linux/debug install
[   +5 ms] ninja: Entering directory `build/linux/debug'
[+3011 ms] [1/5] Generating /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/taha/AndroidStudioProjects/master_flutter/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[        ] [  +58 ms] executing: [/home/taha/Code/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[        ] [        ] executing: [/home/taha/Code/flutter_master/] git tag --points-at eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[        ] [   +8 ms] Exit code 0 from: git tag --points-at eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[        ] [   +1 ms] executing: [/home/taha/Code/flutter_master/] git describe --match *.*.* --long --tags eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[        ] [  +21 ms] Exit code 0 from: git describe --match *.*.* --long --tags eeb7c261f227664c7d3af734bf20d3c71fb3b8b9
[        ] [        ] 1.26.0-1.0.pre-448-geeb7c261f2
[        ] [  +30 ms] executing: [/home/taha/Code/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/taha/Code/flutter_master/] git ls-remote --get-url origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +28 ms] executing: [/home/taha/Code/flutter_master/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +38 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +33 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +84 ms] Initializing file store
[        ] [   +6 ms] Done initializing file store
[        ] [  +27 ms] Skipping target: gen_localizations
[        ] [+1422 ms] Skipping target: unpack_linux
[        ] [ +348 ms] Skipping target: kernel_snapshot
[        ] [ +248 ms] Skipping target: debug_bundle_linux_assets
[        ] [        ] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 2,199ms.
[        ] [ +180 ms] ensureAnalyticsSent: 177ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +396 ms] [2/5] Building CXX object CMakeFiles/master_flutter.dir/flutter/generated_plugin_registrant.cc.o
[  +25 ms] [3/5] Building CXX object CMakeFiles/master_flutter.dir/my_application.cc.o
[ +106 ms] [4/5] Linking CXX executable intermediates_do_not_run/master_flutter
[        ] [4/5] Install the project...
[   +6 ms] -- Install configuration: "Debug"
[  +12 ms] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/master_flutter
[        ] -- Set runtime path of "/home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/master_flutter" to "$ORIGIN/lib"
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/icudtl.dat
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[  +78 ms] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/taha/AndroidStudioProjects/master_flutter/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +33 ms] Building Linux application... (completed in 3.7s)
[ +250 ms] Observatory URL on device: http://127.0.0.1:36167/5NPvmgzpZDk=/
[+2310 ms] Caching compiled dill
[  +52 ms] Connecting to service protocol: http://127.0.0.1:36167/5NPvmgzpZDk=/
[  +82 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:36167/5NPvmgzpZDk=/.
[  +45 ms] DDS is listening at http://127.0.0.1:35875/Z9kUtmU3NJQ=/.
[  +36 ms] Successfully connected to service protocol: http://127.0.0.1:36167/5NPvmgzpZDk=/
[ +728 ms] DevFS: Creating new filesystem on the device (null)
[   +8 ms] DevFS: Created new filesystem on the device (file:///tmp/master_flutterRPQZWI/master_flutter/)
[   +1 ms] Updating assets
[  +61 ms] Syncing files to device Linux...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:master_flutter/main.dart da613299-3324-41e2-9b62-4a70f83e1ce5
[        ] <- da613299-3324-41e2-9b62-4a70f83e1ce5
[ +288 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 292ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +4 ms] Connected to _flutterView/0x23c23d0.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:35875/Z9kUtmU3NJQ=/
[        ] 
           Flutter DevTools, a Flutter debugger and profiler, on Linux is available at: http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A35875%2FZ9kUtmU3NJQ%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+2055 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Cannot find executable for xdg-user-dir.
[        ] #0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
[        ] #1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
[        ] #2      getUserDirectory (package:xdg_directories/xdg_directories.dart:147:48)
[        ] #3      PathProviderLinux.getApplicationDocumentsPath (package:path_provider_linux/path_provider_linux.dart:39:25)
[        ] #4      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:104:39)
[        ] #5      MyApp.build.<anonymous closure> (package:master_flutter/main.dart:22:25)
[        ] #6      MyApp.build.<anonymous closure> (package:master_flutter/main.dart:21:22)
[        ] #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
[        ] #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
[        ] #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
[        ] #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
[        ] #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
[        ] #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
[        ] #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
[        ] #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
[        ] #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
[        ] #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
[        ] #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381:19)
[        ] #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
[        ] #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
[        ] #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
[        ] #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
[        ] #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
[        ] #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
[        ] #25     _rootRunUnary (dart:async/zone.dart:1370:13)
[        ] #26     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
[        ] #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
[        ] #28     _invoke1 (dart:ui/hooks.dart:176:10)
[        ] #29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
[        ] #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.448, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.448 at /home/taha/Code/flutter_master
    • Framework revision eeb7c261f2 (8 hours ago), 2021-01-20 23:04:03 -0500
    • Engine revision dde6b7e8ea
    • Dart version 2.12.0 (build 2.12.0-246.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by Ch4rl3B** [comment] 2021-08-30 17:17
Having similar issue with gitlab CI/CD.. any sugestion??

```
Running "flutter pub get" in xxxxxx-mobile...                       4.9s
00:21 +13 -1: /builds/aaaaa-eeeeeeeeeee/xxxxxx/xxxxxx-mobile/test/functional/home_page_test.dart: Test Home Page is the first shown widget, and correctly navigates to CollectionFilterPage when pressing the YYY Collection button [E]
  ProcessException: Failed to find "xdg-user-dir" in the search path.
    Command: xdg-user-dir 
  package:get_storage/src/storage_impl.dart 47:7  GetStorage._init
```

**Comment by stuartmorgan** [comment] 2021-08-30 17:24
> any sugestion??

See my comment above. I'm happy to review a PR that addresses this.

**Comment by lexxxel** [comment] 2021-08-30 20:36
> > any sugestion??
> 
> See my comment above. I'm happy to review a PR that addresses this.

I can only recommend to NOT hard code a path. Also, @Ch4rl3B is the second one (I was the first one) for whom xdg-usr-dirs wasn't a common transitive dependency. This is especially true for docker images and Gentoo. 

@Ch4rl3B you have to modify the docker images you are using by installing the corresponding package that provides the executable `xdg-user-dir` either in you CI script or in the Dockerfile (preferred way).

**Comment by stuartmorgan** [comment] 2021-08-30 20:44
> I can only recommend to NOT hard code a path.

The XDG spec explicitly describes fallback directories (which it uses internally) when nothing specific is set, so I don't see how it would be problematic for `path_provider` to default to those when `xdg-user-dir` isn't present.

**Comment by lexxxel** [comment] 2021-08-31 07:19
@stuartmorgan I didn't know that. Your are right there.

Docker images might still be an issue. Many do not set `$HOME` or even work with a user that has a `$HOME` path. In such cases the path_provider code would have to handle non existing paths. `$HOME/.config` would then have to be created recursively.

Or do I miss something here?

**Comment by stuartmorgan** [comment] 2021-08-31 13:59
The POSIX spec requires `HOME` to be set on login. Running a Linux Flutter application in a non-POSIX-compliant environment is not a supported configuration, and `path_provider` will not handle it.

**Comment by spydon** [comment] 2023-01-08 10:32
So what is the way forward here, setting a fallback?

**Comment by stuartmorgan** [comment] 2023-01-08 12:33
> So what is the way forward here, setting a fallback?

Yes, please see my comments above.

**Comment by spydon** [comment] 2023-01-08 12:57
> Yes, please see my comments above.

So the fallbacks should be set to the same fallbacks as the XDG spec defines then.
I'll see if I have some time to do a PR for that today then.

**Comment by spydon** [comment] 2023-01-08 13:49
Should the fallbacks be added in path_provider, and not directly in the `xdg_directories` package?

**Comment by stuartmorgan** [comment] 2023-01-08 14:30
I don't remember the details of the XDG spec and how exactly path_provider uses XDG offhand. If there are XDG defaults that aren't in `xdg_directories`, they should be added there. If not, they should be added in `path_provider` based on some more basic directory that is guaranteed to be present.

(Either way `xdg_directories` should be fixed not to throw an internal implementation exception beyond its API boundary.)

**Comment by spydon** [comment] 2023-01-08 17:29
> If not, they should be added in `path_provider` based on some more basic directory that is guaranteed to be present.

I don't think there are any user dirs that are guaranteed to be present in Linux distributions, `$HOME/Downloads` and `$HOME/Desktop` are common, but with localisation and different DEs/WMs that doesn't use xdg-user-dirs nothing is guaranteed. Or do you mean to use a fallback directory that is directly `$HOME` or something?

**Comment by stuartmorgan** [comment] 2023-01-08 17:46
> `$HOME/Downloads` and `$HOME/Desktop` are common, but with localisation and different DEs/WMs that doesn't use xdg-user-dirs nothing is guaranteed.

Hm, that's a good point. We could just create them, but that could easily be unexpected behavior.

Looking at the interface details again, we actually already have `MissingPlatformDirectoryException` defined and documented as the way to handle cases where we can't return anything from `path_provider`, so using that is probably the better option.

So it looks like the steps here are actually:
- fix `xdg_directories` to return null rather than throwing when this happens (it's already nullable so that's non-breaking)
- make sure `path_provider_linux` will pass a null through correctly (which the app-facing package will automatically convert to the correct exception).

**Comment by stuartmorgan** [comment] 2023-01-08 17:52
(In addition to the above, which we should do regardless, we could consider adding an env-based fallback to `path_provider`. E.g., if something like `FLUTTER_PATH_PROVIDER_DOCUMENTS_DIR` is set, use that as a fallback. This could potentially be useful for CI environments, but it's not clear to me that that's actually useful without knowing more about the use cases.)

**Closed** 2023-01-10 21:17 UTC
Labels: plugin, p: first party, platform-linux, p: path_provider, a: desktop, has reproducible steps, P4, found in release: 1.26

**Comment by spydon** [comment] 2023-01-11 11:49
I don't think this should be closed just yet.

**Comment by stuartmorgan** [comment] 2023-01-11 13:08
I checked when this auto-closed, and `path_provider_linux` already looks like it's handling `null`s correctly. Based on the discussion above I don't think there's anything else to do an this point.
