### ISSUE TITLE
[web] App glitches when running in canvaskit on an older machine 

### ISSUE THREAD

**Issue by JerichoCross** [flutter/flutter#91223] opened 2021-10-04 10:32 UTC
## Steps to Reproduce
1. Run flutter create testapp
2. cd into testapp
3. flutter run

**Expected results:**
The starter app opens in chrome and you can increment the counter with the FAB

**Actual results:**
The starter app opens in chrome but any attempt to put the mouse on the FAB causes the appbar to disappear and the counter text and the FAB to jump up the screen. The FAB is no longer clickable in its new position, however, clicking where the FAB used to be increments the counter. In the output below, the three WARNING lines at the end only appear when an attempt is made to put the mouse on the FAB.

<details>
  <summary>Logs</summary>

```
[  +86 ms] executing: uname -m
[  +43 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing: [/home/paul/Development/FlutterSDK/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[        ] executing: [/home/paul/Development/FlutterSDK/flutter/] git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[  +19 ms] Exit code 0 from: git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[        ] 2.5.2
[  +18 ms] executing: [/home/paul/Development/FlutterSDK/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/paul/Development/FlutterSDK/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +121 ms] executing: [/home/paul/Development/FlutterSDK/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +75 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +83 ms] executing: /home/paul/Android/Sdk/platform-tools/adb devices -l
[  +54 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +100 ms] Skipping pub get: version match.
[ +161 ms] Generating
/home/paul/Development/flutter-projects/testproject/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +211 ms] Launching lib/main.dart on Chrome in debug mode...
[ +139 ms] Updating assets
[ +108 ms] Waiting for connection from debug service on Chrome...
[ +135 ms] <- reset
[   +9 ms] /home/paul/Development/FlutterSDK/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/paul/Development/FlutterSDK/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/paul/Development/FlutterSDK/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.GZYHFW/flutter_tool.RFGEZD/app.dill --libraries-spec
file:///home/paul/Development/FlutterSDK/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/paul/Development/flutter-projects/testproject/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.GZYHFW/flutter_tools.YRKBUA --filesystem-scheme
org-dartlang-app --initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///home/paul/Development/FlutterSDK/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +12 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+24279 ms] Waiting for connection from debug service on Chrome... (completed in 24.4s)
[        ] Synced 26.3MB.
[        ] <- accept
[        ] Caching compiled dill
[ +164 ms] Using Google Chrome 94.0.4606.71 

[  +58 ms] executing: uname -m
[  +10 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +276 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:35395/devtools/browser/68e95ac9-bf6d-4387-8025-e86a3ecdc32e
[ +544 ms] DwdsInjector: Received request for entrypoint at http://localhost:40857/main_module.bootstrap.js
[  +10 ms] MetadataProvider: Loading debug metadata...
[  +37 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +25 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:40857/main_module.bootstrap.js
[+3947 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[ +112 ms] DevHandler: Debug service listening on ws://127.0.0.1:35199/kokXzbxETh4=/ws

[  +35 ms] This app is linked to the debug service: ws://127.0.0.1:35199/kokXzbxETh4=/ws
[  +16 ms] Debug service listening on ws://127.0.0.1:35199/kokXzbxETh4=/ws
[        ] 💪 Running with sound null safety 💪
[   +4 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +2 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:35199/kokXzbxETh4=
[ +613 ms] DevTools activation throttled until 2021-10-04 23:19:43.641618.
[+1190 ms] The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:35199/kokXzbxETh4=
[+27521 ms] WARNING: failed to attach a stencil buffer. Rendering will be skipped.
[  +38 ms] WARNING: failed to attach a stencil buffer. Rendering will be skipped.
[  +25 ms] WARNING: Falling back to CPU-only rendering. Failed to initialize WebGL context.

```

```
Analyzing testproject...                                                
No issues found! (ran in 1.8s)

```

```
[✓] Flutter (Channel stable, 2.5.2, on Zorin OS 16 5.11.0-37-generic, locale en_GB.UTF-8)
    • Flutter version 2.5.2 at /home/paul/Development/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/paul/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/paul/Development/AndroidStudio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/paul/Development/AndroidStudio/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.71

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2021-10-04 12:30
Hi @JerichoCross 
Thanks for filing the issue. I am not able to reproduce on Zorin OS.

### Preview
https://user-images.githubusercontent.com/48603081/135851402-292dc2d9-99a9-4863-b9e3-9ff4d1a0dbd2.mp4


<details> 



<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.2, on Zorin OS 16 5.11.0-37-generic, locale en_US.UTF-8)
    • Flutter version 2.5.2 at /home/taha/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Zorin OS 16 5.11.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
	 
</details>

<details> 
<summary>neofetch</summary> 
	
```console
taha@taha-Lenovo-ideapad-510S-14IKB:~$ neofetch
        `osssssssssssssssssssso`           taha@taha-Lenovo-ideapad-510S-14IKB 
       .osssssssssssssssssssssso.          ----------------------------------- 
      .+oooooooooooooooooooooooo+.         OS: Zorin OS 16 x86_64 
                                           Host: 80UV Lenovo ideapad 510S-14IKB 
                                           Kernel: 5.11.0-37-generic 
  `::::::::::::::::::::::.         .:`     Uptime: 5 hours, 41 mins 
 `+ssssssssssssssssss+:.`     `.:+ssso`    Packages: 2020 (dpkg), 12 (flatpak), 13 (snap) 
.ossssssssssssssso/.       `-+ossssssso.   Shell: bash 5.0.17 
ssssssssssssso/-`      `-/osssssssssssss   Resolution: 1920x1080 
.ossssssso/-`      .-/ossssssssssssssso.   DE: GNOME 
 `+sss+:.      `.:+ssssssssssssssssss+`    WM: Mutter 
  `:.         .::::::::::::::::::::::`     WM Theme: ZorinPurple-Dark 
                                           Theme: ZorinPurple-Dark [GTK2/3] 
                                           Icons: ZorinPurple-Dark [GTK2/3] 
      .+oooooooooooooooooooooooo+.         Terminal: gnome-terminal 
       -osssssssssssssssssssssso-          CPU: Intel i5-7200U (4) @ 3.100GHz 
        `osssssssssssssssssssso`           GPU: Intel HD Graphics 620 
                                           Memory: 2745MiB / 7801MiB 

                                                                   
                                                                   


taha@taha-Lenovo-ideapad-510S-14IKB:~$ 
```
	
</details>


Can you please provide try running `sudo apt upgrade` ,restart your system and try Flutter app and provide your `neofetch`
Thank you

**Comment by TahaTesser** [comment] 2021-10-05 07:18
Hi @JerichoCross 
I'm still unable to reproduce this on the same distro on 7th intel graphics. Could try updating your Chrome browser? Mine is  `Version 94.0.4606.61 (Official Build) (64-bit)`

**Comment by JerichoCross** [comment] 2021-10-05 08:24
Hi, my current version is 94.0.4606.71
![Screenshot from 2021-10-05 09-23-52](https://user-images.githubusercontent.com/13554154/135987314-b96f1e48-d556-438e-9045-45db3719431d.png)

**Comment by JerichoCross** [comment] 2021-10-05 09:01
If I start the app using

`flutter run --web-renderer html`

the app works as expected.
This must be something to do with CanvasKit or WebGL

**Comment by JerichoCross** [comment] 2021-10-05 09:47
Interestingly, if I do a hot reload after the problem occurs, I get the following message:

`WARNING: Falling back to CPU-only rendering. WebGL support not detected.`

The application reloads and then works as expected.

**Comment by TahaTesser** [comment] 2021-10-06 06:51
Hi @JerichoCross 
Thanks for the update, it certainly looks like a WebGL issue on your system.  Give your device is pretty old and it doesn't reproduce on my system with OS, it has to be specific to your system or WebGL on older machines

**Comment by JerichoCross** [comment] 2021-10-06 09:36
I used to use Ubuntu MATE on the same hardware and WebGL rendering worked fine on that. I did not expect a problem with Zorin due to its Ubuntu base.

**Comment by TahaTesser** [comment] 2021-10-06 10:02
@JerichoCross 
In that case, this doesn't look like a Flutter, i feel safe to close this, thanks for the update

**Closed by TahaTesser** 2021-10-06 10:02 UTC
Labels: e: device-specific, engine, platform-web, platform-linux, severe: rendering, passed first triage
