### ISSUE TITLE
DropDown should honour incoming maxwidth constraint

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4570] opened 2016-06-15 01:46 UTC
With a dropdown that includes a very long item, the dropdown extends off the edge of the drawer to the end of the screen, this makes the material dropdown icon invisible.

I can illustrate the bug offline if you need further clarification.

**Comment by Hixie** [comment] 2016-06-15 02:34
cc @HansMuller

**Comment by eseidelGoogle** [comment] 2016-06-17 20:58
@DaveShuckerow worked around this by setting a character limit on the dropdown itself.

**Comment by Hixie** [comment] 2017-10-24 23:19
Dupe of https://github.com/flutter/flutter/issues/9211.

**Closed by Hixie** 2017-10-24 23:19 UTC
Labels: prod: framework, prod: material design
