### ISSUE TITLE
visual studio getting crashed on app refresh

### ISSUE THREAD

**Issue by Bassambasheer** [flutter/flutter#97621] opened 2022-02-02 05:14 UTC
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+NoSuchMethodError%3A+NoSuchMethodError%3A+The+getter+%27assetPathsToEvict%27+was+called+on+null.%0AReceiver%3A+null%0ATried+calling%3A+assetPathsToEvict&body=%23%23+Command%0A%60%60%60%0Aflutter+run%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0ANoSuchMethodError%3A+NoSuchMethodError%3A+The+getter+%27assetPathsToEvict%27+was+called+on+null.%0AReceiver%3A+null%0ATried+calling%3A+assetPathsToEvict%0A%60%60%60%0A%230++++++Object.noSuchMethod+%28dart%3Acore-patch%2Fobject_patch.dart%3A68%3A5%29%0A%231++++++HotRunner._resetDirtyAssets+%28package%3Aflutter_tools%2Fsrc%2Frun_hot.dart%3A510%3A20%29%0A%232++++++HotRunner._restartFromSources+%28package%3Aflutter_tools%2Fsrc%2Frun_hot.dart%3A578%3A5%29%0A%3Casynchronous+suspension%3E%0A%233++++++HotRunner._fullRestartHelper+%28package%3Aflutter_tools%2Fsrc%2Frun_hot.dart%3A754%3A16%29%0A%3Casynchronous+suspension%3E%0A%234++++++HotRunner.restart+%28package%3Aflutter_tools%2Fsrc%2Frun_hot.dart%3A701%3A38%29%0A%3Casynchronous+suspension%3E%0A%235++++++TerminalHandler._commonTerminalInputHandler+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A1640%3A40%29%0A%3Casynchronous+suspension%3E%0A%236++++++TerminalHandler.processTerminalInput+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A1680%3A7%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+2.8.1%2C+on+Microsoft+Windows+%5BVersion+10.0.19043.1466%5D%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+2.8.1+at+C%3A%5CUsers%5CHP%5CDocuments%5Cflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+77d935af4d+%287+weeks+ago%29%2C+2021-12-16+08%3A37%3A33+-0800%0A++++%E2%80%A2+Engine+revision+890a5fca2e%0A++++%E2%80%A2+Dart+version+2.15.1%0A%0A%5B%21%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+32.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5CHP%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%80%A2+Platform+android-32%2C+build-tools+32.0.0%0A++++%E2%80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjre%5Cbin%5Cjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.10%2B0-b96-7249189%29%0D%0A++++%21+Some+Android+licenses+not+accepted.++To+resolve+this%2C+run%3A+flutter+doctor+--android-licenses%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2020.3%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.10%2B0-b96-7249189%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.63.2%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5CHP%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.34.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%283+available%29%0A++++%E2%80%A2+Redmi+Note+8+%28mobile%29+%E2%80%A2+43b12896+%E2%80%A2+android-arm64++%E2%80%A2+Android+10+%28API+29%29%0A++++%E2%80%A2+Chrome+%28web%29++++++++++%E2%80%A2+chrome+++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+97.0.4692.99%0A++++%E2%80%A2+Edge+%28web%29++++++++++++%E2%80%A2+edge+++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+96.0.1054.62%0A++++%21+Device+43b12896+is+offline.%0A%0A%21+Doctor+found+issues+in+1+category.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+77d935af4db863f6abd0b9c31c7e6df2a13de57b%0A%23%23%23+Plugins%0Aflutter_local_notifications-9.2.0%0Aflutter_native_timezone-2.0.0%0Apath_provider-2.0.8%0Apath_provider_android-2.0.11%0Apath_provider_ios-2.0.7%0Apath_provider_linux-2.1.5%0Apath_provider_macos-2.0.5%0Apath_provider_windows-2.0.5%0Ashared_preferences-2.0.12%0Ashared_preferences_android-2.0.10%0Ashared_preferences_ios-2.0.9%0Ashared_preferences_linux-2.0.4%0Ashared_preferences_macos-2.0.2%0Ashared_preferences_web-2.0.3%0Ashared_preferences_windows-2.0.4%0A%0A&labels=tool%2Csevere%3A+crash

**Comment by danagbemava-nc** [comment] 2022-02-02 07:33
Duplicate of #89738

**Closed by danagbemava-nc** 2022-02-02 07:33 UTC
Labels: in triage
