### ISSUE TITLE
[google_maps_flutter] Using Map ID from Cloud Styling in GoogleMap widget

### ISSUE THREAD

**Issue by maganap** [flutter/flutter#104839] opened 2022-05-27 16:59 UTC
## Use case

I'd like to be able to use a Map ID from the Cloud-based Map Styling offered by Google, instead of using a JSON to style the map.
Is there any plan to include this feature? 

This is to allow design team to play around with the map styling, or even change the style a bit whenever they want without the hassle of having to copy and paste a huge JSON every time and wait for another team to embed the style in the app. Or having to rebuild the app just to show different styles inside the app to a client, for example.  Having the style change dynamically would be of great help.

Thanks!

**Comment by darshankawar** [comment] 2022-05-30 06:14
Closing this as duplicate of https://github.com/flutter/flutter/issues/67631

**Closed by darshankawar** 2022-05-30 06:14 UTC
Labels: in triage

**Comment by maganap** [comment] 2022-05-30 12:59
@darshankawar Oh! I tried to find some other issue with this feature but I couldn't find it. Many thanks :-)
