### ISSUE TITLE
Add python linter in engine tests

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#70654] opened 2020-11-16 21:52 UTC
@gaaclarke suggested I run a linter against a [new python script I added](https://github.com/flutter/engine/pull/22506#issuecomment-728334397).  I has assumed this was already being done in a pre-submit linter (like `./ci/bin/lint.dart` or somewhere else).

Add python lint checks if they don't already exist.  Fix issues the linter finds.

**Comment by zanderso** [comment] 2023-01-06 17:50
Closing as duplicate of https://github.com/flutter/flutter/issues/100772

**Closed by zanderso** 2023-01-06 17:50 UTC
Labels: a: tests, team, engine, passed first triage, P4
