### ISSUE TITLE
On iPad, preferred orientation is not working after calling SystemChrome.setPreferredOrientations

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#74453] opened 2021-01-22 00:43 UTC
## Steps to Reproduce

1. Create an app with the following code and run on an iPad mini

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'dart:io' show Platform; // For Platform.isX

void main() {
  // ++++ #61707: https://github.com/flutter/flutter/issues/61707
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([
    Platform.isAndroid ?
    DeviceOrientation.landscapeLeft :
    DeviceOrientation.landscapeRight
  ]);

  // --- #61607
  runApp(MamGuestApp());
}

```

3. ... 

**Expected results:** 

The orientation should be locked onto landscape-right

**Actual results:** 

When rotating the iPad, the orientation changes.

<details>
  <summary>Logs</summary>

```
```

Something is wrong with my Xcode and I can only run the app inside Xcode.
But it should work the same way as it does on other iPhones I have.

```sh
$ flutter analyze
Analyzing Desktop...                                                    

  error • Target of URI doesn't exist: 'package:flutter_test/flutter_test.dart' •
         _dev/flutter/dev/automated_tests/flutter_run_test/flutter_run_test.dart:5:8 • uri_does_not_exist
  error • The function 'group' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_run_test/flutter_run_test.dart:8:3 • undefined_function
  error • The function 'test' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_run_test/flutter_run_test.dart:9:5 • undefined_function
  error • The function 'expect' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_run_test/flutter_run_test.dart:10:7 • undefined_function
  error • The function 'test' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_run_test/flutter_run_test.dart:12:5 • undefined_function
  error • The function 'expect' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_run_test/flutter_run_test.dart:13:7 • undefined_function
  error • The function 'test' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_run_test/flutter_run_test.dart:15:5 • undefined_function
  error • The function 'expect' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_run_test/flutter_run_test.dart:16:7 • undefined_function
  error • Target of URI doesn't exist: 'package:test/test.dart' •
         _dev/flutter/dev/automated_tests/flutter_test/child_directory/second_trivial_test.dart:5:8 •
         uri_does_not_exist
  error • The function 'test' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_test/child_directory/second_trivial_test.dart:8:3 •
         undefined_function
  error • Target of URI doesn't exist: 'package:test/test.dart' •
         _dev/flutter/dev/automated_tests/flutter_test/child_directory/trivial_test.dart:5:8 • uri_does_not_exist
  error • The function 'test' isn't defined •
         _dev/flutter/dev/automated_tests/flutter_test/child_directory/trivial_test.dart:8:3 • undefined_function
  error • Target of URI doesn't exist: 'package:flutter/foundation.dart' •
....
```

There are many pages of errors like this.

```
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.7 19H15, locale en-CN)
    • Flutter version 1.22.0-12.0.pre at /Applications/flutter
    • Framework revision a27c242b0e (4 months ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Applications/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Applications/Android/sdk
    • ANDROID_SDK_ROOT = /Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • MyiPad (mobile) • <udid> • ios        • iOS 13.2.3
    • macOS (desktop)        • macos        • darwin-x64 • Mac OS X 10.15.7 19H15

! Doctor found issues in 1 category.
```

</details>

**Comment by kakyoism** [comment] 2021-01-22 02:26
Just updated my flutter and cocoapods as well but the problem is still there. Here is the updated `flutter doctor -v`.

```sh
flutter doctor -v
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-CN)
    • Flutter version 1.26.0-12.0.pre at /Applications/flutter
    • Framework revision a706cd2112 (7 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Applications/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Applications/Android/sdk
    • ANDROID_SDK_ROOT = /Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • MyiPad (mobile) • <udid> • ios        • iOS 13.2.3
    • macOS (desktop)        • macos        • darwin-x64 • Mac OS X 10.15.7 19H15

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-01-22 11:17
Hi @kakyoism 
I can reproduce it on iPad 8, no issue on iPhone.

<details>
<summary>complete runnable code sample</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([
    Platform.isAndroid
        ? DeviceOrientation.landscapeLeft
        : DeviceOrientation.landscapeRight
  ]);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}
```
</details>


<details>
<summary>logs</summary>

```bash
[  +24 ms] [ 65%] InstallingEmbeddedProfile
[   +5 ms] [ 70%] VerifyingApplication
[  +96 ms] [ 75%] CreatingContainer
[   +5 ms] [ 80%] InstallingApplication
[   +7 ms] [ 85%] PostflightingApplication
[   +2 ms] [ 90%] SandboxingApplication
[   +9 ms] [ 95%] GeneratingApplicationMap
[  +83 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +188 ms] ------ Debug phase ------
[        ] Starting debug of 00008020-000255113EE8402E (J171aAP, J171aAP, uknownos, unkarch) a.k.a. 'Taha’s iPad'
connected through USB...
[ +170 ms] [  0%] Looking up developer disk image
[   +8 ms] [ 95%] Developer disk image mounted successfully
[ +981 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +229 ms] (lldb) command source -s 0
'/tmp/FE0F6799-BD8B-4996-B4D5-DA9004AFBC86/fruitstrap-lldb-prep-cmds-00008020_000255113EE8402E'
[        ] Executing commands in
'/tmp/FE0F6799-BD8B-4996-B4D5-DA9004AFBC86/fruitstrap-lldb-prep-cmds-00008020_000255113EE8402E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/tahatesser/Library/Developer/Xcode/iOS
DeviceSupport/14.3 (18C66) arm64e/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols"
[        ] (lldb)     target create
"/Users/tahatesser/AndroidStudioProjects/triage_project/build/ios/iphoneos/Runner.app"
[+4576 ms] Current executable set to
'/Users/tahatesser/AndroidStudioProjects/triage_project/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script
fruitstrap_device_app="/private/var/containers/Bundle/Application/3E775197-A14F-418E-A580-A3DC693A28A3/Runner.app"
[ +552 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:60906"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/tahatesser/Library/Developer/Xcode/iOS
DeviceSupport/14.3 (18C66) arm64e/Symbols/usr" /System "/Users/tahatesser/Library/Developer/Xcode/iOS
DeviceSupport/14.3 (18C66) arm64e/Symbols/System"
"/private/var/containers/Bundle/Application/3E775197-A14F-418E-A580-A3DC693A28A3"
"/Users/tahatesser/AndroidStudioProjects/triage_project/build/ios/iphoneos"
"/var/containers/Bundle/Application/3E775197-A14F-418E-A580-A3DC693A28A3"
"/Users/tahatesser/AndroidStudioProjects/triage_project/build/ios/iphoneos" /Developer
"/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols/Developer"
[  +13 ms] (lldb)     command script import
"/tmp/FE0F6799-BD8B-4996-B4D5-DA9004AFBC86/fruitstrap_00008020_000255113EE8402E.py"
[   +8 ms] (lldb)     command script add -f fruitstrap_00008020_000255113EE8402E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000255113EE8402E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000255113EE8402E.autoexit_command
autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000255113EE8402E.safequit_command
safequit
[        ] (lldb)     connect
[  +37 ms] (lldb)     run
[ +214 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+1392 ms] Observatory URL on device: http://127.0.0.1:53663/
[   +8 ms] Attempting to forward device port 53663 to host port 60919
[        ] executing: /Users/tahatesser/Code/flutter_dev/bin/cache/artifacts/usbmuxd/iproxy 60919:53663 --udid
00008020-000255113EE8402E
[+1018 ms] Forwarded port ForwardedPort HOST:60919 to DEVICE:53663
[   +2 ms] Forwarded host port 60919 to device port 53663 for Observatory
[  +10 ms] Installing and launching... (completed in 23.6s)
[   +5 ms] Caching compiled dill
[ +214 ms] Connecting to service protocol: http://127.0.0.1:60919/
[   +3 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:60919/.
[ +930 ms] DDS is listening at http://127.0.0.1:60926/BDX5c6lEVVU=/.
[  +83 ms] Successfully connected to service protocol: http://127.0.0.1:60919/
[+3232 ms] DevFS: Creating new filesystem on the device (null)
[  +49 ms] DevFS: Created new filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/C99AF3AA-C987-4C45-9137-55C4AA51C075/tmp/triage_projectC5traz/
triage_project/)
[   +4 ms] Updating assets
[ +109 ms] Syncing files to device Taha’s iPad...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:triage/main.dart d4e1e6f0-a02d-402a-aedf-725e8e5bdf17
[        ] <- d4e1e6f0-a02d-402a-aedf-725e8e5bdf17
[ +151 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Taha’s iPad... (completed in 157ms)
[        ] Synced 0.0MB.
[        ] <- accept
[  +15 ms] Connected to _flutterView/0x116023a20.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Taha’s iPad is available at: http://127.0.0.1:60926/BDX5c6lEVVU=/
[   +1 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on Taha’s iPad is available at:
           http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A60926%2FBDX5c6lEVVU%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (7 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
```bash
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-12.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision a706cd2112 (8 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.118, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.118 at /Users/tahatesser/Code/flutter_master
    • Framework revision 08068fd94c (4 hours ago), 2021-01-21 22:51:03 -0800
    • Engine revision 90641fa923
    • Dart version 2.12.0 (build 2.12.0-248.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thanks for filing the issue.

**Comment by nt4f04uNd** [comment] 2021-01-22 13:21
@TahaTasser this is duplicate #27235

**Comment by TahaTesser** [comment] 2021-01-22 14:00
@nt4f04uNd 
Thanks!

@kakyoism 
This looks like it won't work as expected if you use multitasking, please check the explanation [here](https://github.com/flutter/flutter/blob/78910062997c3a836feee883712c241a5fd22983/packages/flutter/lib/src/services/system_chrome.dart#L234-L241) 


Closing as duplicate of https://github.com/flutter/flutter/issues/27235. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-22 14:00 UTC
Labels: a: layout, a: tablet, found in release: 1.22, found in release: 1.25, found in release: 1.26, framework, has reproducible steps, platform-ios
