### ISSUE TITLE
I am trying to run my flutter project but constantly getting the below error. I tried flutter clean, deleting the pubspec.lock and again running flutter pub get but the error pops out now and then. 

### ISSUE THREAD

**Issue by Ashish-1008** [flutter/flutter#84911] opened 2021-06-19 14:45 UTC

**Comment by behzodfaiziev** [comment] 2021-06-19 21:24
Duplicate of #84912

**Comment by darshankawar** [comment] 2021-06-21 10:08
Closing as duplicate of https://github.com/flutter/flutter/issues/84912.
Please don't create multiple issues for same reason.

**Closed by darshankawar** 2021-06-21 10:08 UTC
Labels: in triage
