### ISSUE TITLE
local_auth canCheckBiometrics and getAvailableBiometrics gives incorrect results in iOS 9.x & 10.x

### ISSUE THREAD

**Issue by danwulff** [flutter/flutter#29457] opened 2019-03-15 22:49 UTC
I believe issue #27366 got closed prematurely. The incorrect results still occur, even with the latest release of local_auth `0.4.0+1` incorrect results are returned.

I've copied the previous issue's content below (with some small tweaks)

> ## Issue
> `LocalAuthentication().canCheckBiometrics` returns false in iOS 9.x and iOS 10.x, with Touch ID enabled. (Strangely it returns true with Touch ID disabled)
>
> Additionally `LocalAuthentication().getAvailableBiometrics()` returns an empty array whether or not Touch ID is enabled.
>
> This is reproducible on both a simulator and physical device.
>
> Note: this may be present on other device models, our team originally found this issue on a iPhone 6 which is why it has been used for testing.
> 
> ## Expected Functionality
> 
> `canCheckBiometrics` and `getAvailableBiometrics` should work in iOS 9.x and 10.x.
> 
> ## Steps to Reproduce
> 
> - `git clone https://github.com/danwulff/flutter_local_auth_bug.git`
> - `cd flutter_local_auth_bug/`
> - Open an iOS simulator with iPhone 6 and iOS 10.x or 9.x
> - Ensure Touch ID is enabled in the Simulator (in the menus, Hardware -> Touch ID -> Enrolled ✔️)
> 
> **For reference:** the main.dart file from the above repo is copied here:
```dart
import 'package:flutter/material.dart';
import 'package:local_auth/local_auth.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final localAuth = LocalAuthentication();

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _canCheckBiometricsResult;
  List<BiometricType> _getAvailableBiometricsResult;

  void _checkBiometrics() async {
    final checkResult = await widget.localAuth.canCheckBiometrics;
    final getResult = await widget.localAuth.getAvailableBiometrics();
    setState(() {
      _canCheckBiometricsResult = checkResult;
      _getAvailableBiometricsResult = getResult;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('local_auth bug'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'The result of canCheckBiometrics:',
            ),
            Text(
              '${_canCheckBiometricsResult ?? ''}',
              style: Theme.of(context).textTheme.display1,
            ),
            Text(
              'The result of getAvailableBiometrics (length):',
            ),
            Text(
              '${_getAvailableBiometricsResult?.length ?? ''}',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _checkBiometrics,
        tooltip: 'Increment',
        child: Icon(Icons.update),
      ),
    );
  }
}
```
> 
> ## Logs
> 
> flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/dwulff/development/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dwulff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/dwulff/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone 6 • 3436A745-6D12-4EAD-9FBB-76311AAEC17B • ios • iOS 10.3 (simulator)

• No issues found!
```

**Comment by duzenko** [comment] 2019-09-03 12:49
I have the same problem on Android
My test device has no fingerprints scanned. getAvailableBiometrics returns empty. canCheckBiometrics returns true - why? What is it supposed to check?

**Comment by BaptisteMonet** [comment] 2020-07-01 08:36
Hello I also have the same problem on Android
 auth.canCheckBiometrics always return true even if is disabled in android

**Comment by Pr47h4m** [comment] 2020-09-09 11:44
try "flutter clean"
and then run the application

**Comment by html-rulez-d00d** [comment] 2020-11-19 22:51
I am having similar issues as well (v0.6.3+4) for my Pixel 3 (Android 11) and Samsung S8+ (Android 9, One UI 1.0). I removed all fingerprints (and confirmed not other biometric is present) from both devices and the following results are incorrectly returned:

- **_auth.canCheckBiometrics** == true
- **_auth.getAvailableBiometrics()** returns a list of one, stating fingerprint exists. 
- **_auth.authenticateWithBiometrics(localizedReason: '...')** will ask to add a fingerprint via OS prompt.

I would expect **canCheckBiometrics** should return false and **getAvailableBiometrics** should return empty if no biometric exists.

**Comment by syahferiaswan** [comment] 2021-01-19 11:09
i have the same problem on Android 10, any update how to fix this issue?

**Comment by devon2018** [comment] 2021-04-03 10:18
Having this same issue with android, any update on when this will be sorted, bit of a blocker.

**Comment by stuartmorgan** [comment] 2021-06-13 15:40
There's another issue tracking the Android issue; this is specific to iOS. The implementations at the level of determining supported options are entirely separate.

**Comment by stuartmorgan** [comment] 2023-03-26 17:05
Closing as obsolete since iOS 9 and 10 are no longer supported.

**Closed by stuartmorgan** 2023-03-26 17:05 UTC
Labels: platform-ios, plugin, p: local_auth, P4
