### ISSUE TITLE
[web] Widgets flickering randomly since 1.19.0-1.0.pre on dev and master channels

### ISSUE THREAD

**Issue by ja2375** [flutter/flutter#57198] opened 2020-05-14 08:26 UTC
I have a pretty large app developed mainly for flutter web. The application was working perfectly well until i updated to flutter 1.19.0-1.0.pre on dev channel, that many widgets started to flicker randomly. Either in debug and in release mode.

Widgets that flicker include `Image`, `Stack`, `TextFormField` (only the border), `CheckBox` inside `DataTable` and maybe more that i may have not noticed of.

This did not happen on 1.19.0-0.0.pre on the dev channel, so i'm pretty sure that this started to happen in 1.19.0-1.0.pre. I also tried changing to the master channel to see if this was fixed, but it is not.

It is important to note that i did not make any modifications to my app since i upgraded to 1.19.0-1.0.pre. So i guess it's not an issue of myself.

Anybody else is having this issue?

My doctor output:
```
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale es-ES)
    • Flutter version 1.19.0-1.0.pre at /Users/ja2375/flutter
    • Framework revision 456d80b9dd (3 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ja2375/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

**Comment by slavap** [comment] 2020-05-14 10:09
The same problem, see https://github.com/flutter/flutter/issues/57105

**Comment by ja2375** [comment] 2020-05-14 12:41
Many thanks for the reference and information. Definetively this has to be solved.

As a scroll and go through the screens of my app, nearly every widget flickers. Some of them even appear/disappear.

**Comment by TahaTesser** [comment] 2020-05-14 12:59
Closing as duplicate of https://github.com/flutter/flutter/issues/57105

**Closed by TahaTesser** 2020-05-14 12:59 UTC
