### ISSUE TITLE
examples/widgets/mixed_viewport.dart crashes when you remove big nodes before small nodes

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#144] opened 2015-11-09 21:21 UTC
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Aug 25, 2015 at 21:33 GMT_
_Originally opened as https://github.com/flutter/engine/issues/820_

----

To reproduce:
- click add a few times until you have a big block followed by a small block
- scroll the big block almost off screen, such that more of the block is off the top of the screen than the height of the small block
- tap the big block

The small block is moved off the screen and then there's a crash.

CC @HansMuller

**Comment by FlutterIssues** [comment] 2015-11-09 21:21
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Tuesday Aug 25, 2015 at 21:39 GMT_

----

I think you can also trigger this in examples/widgets/card_collection.dart by flinging a card out while scrolling.

**Comment by FlutterIssues** [comment] 2015-11-09 21:21
<a href="https://github.com/HansMuller"><img src="https://avatars.githubusercontent.com/u/1377460?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansMuller](https://github.com/HansMuller)**
_Tuesday Aug 25, 2015 at 21:52 GMT_

----

I have looked into this (without success) more than once.  The failure is signalled by this assert:

'http://localhost:9888/packages/sky/widgets/framework.dart': Failed assertion: line 366 pos 14: 'oldNode.mounted' is not true.

The problem can be avoided by changing MixedViewport._doLayout():
```
    // Remove any old children.
    for (_Key oldChildKey in childrenByKey.keys) {
      if (!childrenByKey[oldChildKey].mounted)  // HACK
        continue;
      ...
     }
```
It's not clear how a !mounted Widget ends up in childrenByKey at this point.

**Comment by FlutterIssues** [comment] 2015-11-09 21:21
<a href="https://github.com/HansMuller"><img src="https://avatars.githubusercontent.com/u/1377460?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansMuller](https://github.com/HansMuller)**
_Monday Aug 31, 2015 at 18:25 GMT_

----

I've checked this against the original test case and with the card_collection.dart (swipe away) demo. The bug appears to have been fixed. I haven't been able to pin down exactly which change gets the credit.

**Comment by sethladd** [comment] 2016-09-14 17:09
Is this still an issue?

**Comment by Hixie** [comment] 2016-09-14 17:14
I'm going to close this because I don't know how to reproduce it anymore.
I did get https://github.com/flutter/flutter/issues/5864 while trying to reproduce it...

**Closed by Hixie** 2016-09-14 17:14 UTC
Labels: affects: framework, customer: demos, waiting for customer response, ⚠ bug
