### ISSUE TITLE
List<Widget>.last returns the first element when the element is const

### ISSUE THREAD

**Issue by visign3d** [flutter/flutter#109046] opened 2022-08-05 15:53 UTC
```
final List<Widget> children;

  Widget body(BuildContext context) {
    List<Widget> rows = [];
    for (var i in children) {
      rows.add(i);
      rows.add(const SizedBox(height: 8,));
    }
    rows.remove(rows.last);
    return Column(children: rows);
  }

```

**Expected results:** a gap should appear between widgets, and the last gap should be removed

**Actual results:** the first gap is removed , not the lat in the list

if i add the sizedbox whitout const the gap appears as expected, and the last gap is removed from list

log example:
```
MobilePage.body : [PageCard, PageCard, PageVerticalGap, PageCard, PageVerticalGap]
```
expected:
```
MobilePage.body : [PageCard, PageVerticalGap, PageCard, PageVerticalGap, PageCard]
```

```

<!-- Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1826], locale hu-HU)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.0)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.0)
[√] VS Code, 32-bit edition (version 1.32.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
 -->

```

![image](https://user-images.githubusercontent.com/25665922/183114968-7c674838-ac13-4d94-97a9-5ca5869d383f.png)

without const, expected result:

![image](https://user-images.githubusercontent.com/25665922/183115458-5c067ce0-29a0-4a47-9bb8-fb8302ffc7c5.png)

**Comment by BrianCraig** [comment] 2022-08-05 20:12
The behaviour is correct, check https://medium.com/flutter-community/the-flutter-const-keyword-demystified-c8d2a2609a80, all the `const SizedBox` are the same instance, so it removes the first one found.

**Comment by huycozy** [comment] 2022-08-08 05:34
Hi @visign3d 
As @BrianCraig provided the article above explains the root cause of the issue, please try using `list.removeLast()` for your case.
 
I also try using the method and this is the result:
![Screen Shot 2022-08-08 at 12 33 07](https://user-images.githubusercontent.com/104349824/183346216-f379707b-8fda-4065-984a-76bf43395404.png)

Closing the issue as solved. If you disagree, please write in the comments and I will reopen it.

**Closed by huycozy** 2022-08-08 05:34 UTC
Labels: in triage
