### ISSUE TITLE
App crash only adding sizedBox

### ISSUE THREAD

**Issue by samaddestring** [flutter/flutter#71551] opened 2020-12-02 11:20 UTC
Please check it out 
```dart
               SizedBox(height: 30),
                  _signInButton(),
                  SizedBox(height: 10),
                  _signInFBButton(),
                  SizedBox(height: 10),
                  _signInPhoneButton(),
```

```bash
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#26001](dirty, dependencies: [HeroControllerScope], state: NavigatorState#326da(tickers: tracking 3 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///var/www/Hunarmand/hunarmand/lib/main.dart:38:13
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:4041:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)

════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by TahaTesser** [comment] 2020-12-02 11:41
Hi @samaddestring 
Looks like the same crash, please follow up on  your first issue 
Closing as duplicate of https://github.com/flutter/flutter/issues/71542

**Closed by TahaTesser** 2020-12-02 11:41 UTC
