### ISSUE TITLE
Cursor control on Samsung One UI keyboard should NOT work when selection length > 0 

### ISSUE THREAD

**Issue by wonpyohong** [flutter/flutter#75776] opened 2021-02-10 10:43 UTC
gif: https://github.com/flutter/flutter/issues/61954#issuecomment-775742834

This problem is only happen on Samsung Keyboard

Reproducible step
1. 'Setting' of phone -> touch 'serach icon' on right top -> search 'Keyboard swipe controls' -> select 'Cursor control'
2. Make TextField. minimal code is below
3. Type some text and select text entirely with double tap -> touch any key on keyboard 
**expected**: all text is deleted and insert a new character
**actual**: append a new character to original text

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: SafeArea(
          child: TextField()
        )
      ),
    );
  }
}
```

Cursor control is comfortable function that can move cursor of TextField by dragging on broad keyboard layout (not on small TextField layout).
However it should NOT work when selection length > 0 like Android native

**Comment by TahaTesser** [comment] 2021-02-10 11:23
closing as a duplicate of https://github.com/flutter/flutter/issues/75776

**Closed by TahaTesser** 2021-02-10 11:23 UTC

**Comment by wonpyohong** [comment] 2021-02-10 11:28
@TahaTesser why closed? https://github.com/flutter/flutter/issues/61954 has not enough information than this
