### ISSUE TITLE
DropdownButtonFormField generating bug but DropdownButton working fine

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#52461] opened 2020-03-12 09:49 UTC
I have the below codes. I have these 2 dropdown. When I selected the first drop down it will trigger to populate the next dropdown value and I am using the bloc to do the updates cause setState will cause the entire page to be rebuild. Something very weird. You can see I am using 
```
_subcountyDropDownMenuItems.clear();
                              _subcountyDropDownMenuItems = [];
```
to ensure its clean each time the list and only then I assign the new list into the` return DropdownButtonFormField`

Example when the very first time the first dropdown is selected below is array values generated for the second dropdown.

```
I/flutter (28594): Build subcounty dropdown Instance of 'SubcountyApiInitialState'
I/flutter (28594): What is the items sub county list size now 2
I/flutter (28594): NEW drop down value is : 47
I/flutter (28594): NEW drop down child is : Text("ISle North")
I/flutter (28594): NEW drop down value is : 48
I/flutter (28594): NEW drop down child is : Text("ISle South")
```
When I selected another first dropdown value. Example below list is generated.
```
I/flutter (28594): What is the items sub county list size now 5
I/flutter (28594): NEW drop down value is : 49
I/flutter (28594): NEW drop down child is : Text("Kj Central")
I/flutter (28594): NEW drop down value is : 50
I/flutter (28594): NEW drop down child is : Text("Kj East")
I/flutter (28594): NEW drop down value is : 51
I/flutter (28594): NEW drop down child is : Text("Kj North")
I/flutter (28594): NEW drop down value is : 52
I/flutter (28594): NEW drop down child is : Text("Kj South")
I/flutter (28594): NEW drop down value is : 53
I/flutter (28594): NEW drop down child is : Text("Kj West")
```
I get this error 
```
There should be exactly one item with [DropdownButton]'s value: 48. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 803 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'
```
It keep referring to the previous selected value I/flutter (28594): NEW drop down value is : 48. But you can see I have cleared the list and even print out the list to show all the new value but it keep giving me this error `There should be exactly one item with [DropdownButton]'s value: 48. `. But there is one weird part here if I use this widget DropdownButton. It works perfectly fine but I need this DropdownButtonFormField cause I need to standardize with the rest of the items in the form? So how to overcome this bug?

```
BlocBuilder(
                          bloc: subcountyBLoC,
                          builder: (BuildContext context, SubcountyApiState state) {
                            print("Build subcounty dropdown "+state.toString());                            
                            if(state is SubcountyApiInitialState && state.subcountyList.length>0 ){
                              _subcountyDropDownMenuItems.clear();
                              _subcountyDropDownMenuItems = [];
                              //_subcountyDropDownMenuItems = null;
                              for (final info in state.subcountyList) {
                                     _subcountyDropDownMenuItems.add(new DropdownMenuItem(
                                    value: info.subcountyID.toString(),
                                    child: new Text(info.subcountyName)
                                ));
                              }
                            
                              print("What is the items sub county list size now "+_subcountyDropDownMenuItems.length.toString());
                              if(_subcountyDropDownMenuItems.length>0){
                                for(var f=0; f<_subcountyDropDownMenuItems.length; f++){
                                   print("NEW drop down value is : "+_subcountyDropDownMenuItems[f].value.toString());
                                   print("NEW drop down child is : "+_subcountyDropDownMenuItems[f].child.toString());
                                }
                              return DropdownButtonFormField(
                                  hint: Text('Select Sub County'),
                                  onChanged: changedSubcountyDropDownItem,
                                  items: _subcountyDropDownMenuItems,
                                  value: null,
                                  /*decoration: InputDecoration(
                                    labelText: 'Sub County',
                                  ),
                                  validator: validateDropDown,*/
                                );
                                

                              
                              }                              
                              else{
                                return Container(height: 0, width: 0,);
                              }
                          }
```

**Comment by lazul92** [comment] 2020-03-22 18:56
I have same problem. I change version beta 1.14.x it worsk dont error and stable also working, but latest beta version throw error.

DropdownButtonFormField and i change DropdownButton dont throw error but same item comapre method.  Maybe is a bug?

**Comment by TahaTesser** [comment] 2020-04-15 13:09
Hi @newbieflutter 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by narawut-sadabpote** [comment] 2020-04-17 13:58
same  to me i have multiple DropdownButtonFormField. When user select the 1st DropdownButtonFormField i load data to 2nd drop down and when user change 1st again i load data to 2nd drop down again. the problem is if user select 2nd drop down value and change 1st  drop down value 2nd drop down not change to null even i set value to 2nd drop down value to null thank you

> [✓] Flutter (Channel master, v1.18.0-6.0.pre.64, on Mac OS X 10.15.4 19E287, locale en-TH)
    • Flutter version 1.18.0-6.0.pre.64 at /Users/narawutsadabpote/Work/flutter
    • Framework revision 0b9c42f944 (14 hours ago), 2020-04-16 20:00:01 -0400
    • Engine revision f4d6ce13dc
    • Dart version 2.8.0 (build 2.8.0-dev.20.7 5900a0ac49)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/narawutsadabpote/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

>

**Comment by gustavomassa** [comment] 2020-05-10 16:57
@TahaTesser 
Full example here:

Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (8 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  Home({Key key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final GlobalKey<FormState> formKey = GlobalKey<FormState>();
  Future<FormDependency> _dependencies;
  Model _model;

  List<Tecnology> _tecnologyList;
  Tecnology _currentTecnology;
  List<Tecnology> _currentTecnologyList;

  @override
  void initState() {
    super.initState();

    _model = Model(category: null, tecnology: null);
    _tecnologyList = null;
    _currentTecnology = null;
    _currentTecnologyList = null;

    _dependencies = _getFormDependency();
  }

  Future<FormDependency> _getFormDependency() async {
    var web = Category(id: 1, name: 'Web');
    var mobile = Category(id: 2, name: 'Mobile');
    var desktop = Category(id: 3, name: 'Desktop');

    var categoryList = [web, mobile, desktop];
    var tecnologyList = [
      Tecnology(id: 1, name: 'Angular', category: web),
      Tecnology(id: 2, name: 'React', category: web),
      Tecnology(id: 3, name: 'Vue', category: web),
      Tecnology(id: 3, name: 'Flutter', category: mobile),
      Tecnology(id: 4, name: 'Electron', category: desktop),
      Tecnology(id: 4, name: 'GTK', category: desktop),
    ];

    // Init tecnology variables
    _tecnologyList = tecnologyList;
    _currentTecnology = _tecnologyList[0];
    _currentTecnologyList = _tecnologyList
        .where((x) => x.category.id == categoryList[0].id)
        .toList();

    return FormDependency(categories: categoryList, tecnologies: tecnologyList);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material Form'),
      ),
      body: FutureBuilder<FormDependency>(
          future: _dependencies,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return Form(
                key: formKey,
                child: SingleChildScrollView(
                  padding:
                      const EdgeInsets.only(top: 12.0, left: 5.0, right: 5.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: _buildForm(context, snapshot.data),
                  ),
                ),
              );
            } else {
              return Center(child: CircularProgressIndicator());
            }
          }),
    );
  }

  List<Widget> _buildForm(BuildContext context, FormDependency data) {
    List<Widget> form = [];

    // Category
    form.add(CustomDropDownInput<Category>(
      labelText: 'Category',
      optional: false,
      enabled: true,
      initialValue: data.categories[0],
      itemList: data.categories.map((Category category) {
        return DropdownMenuItem<Category>(
          value: category,
          child: Text(category.name),
        );
      }).toList(),
      onChanged: (newValue) {
        _model.category = newValue;

        // Reset tecnology dropdown value and update the item list based on the category selected
        setState(() {
          _currentTecnology =
              null; //null is passed to the dropdown build, but the internal valu of dropdown does not set the null value
          _currentTecnologyList = _tecnologyList
              .where((x) => x.category.id == newValue.id)
              .toList();
        });
      },
    ));

    // Tecnologies
    form.add(CustomDropDownInput<Tecnology>(
      labelText: 'Tecnology',
      optional: false,
      enabled: true,
      initialValue: _currentTecnology,
      itemList: (_currentTecnologyList != null)
          ? _currentTecnologyList.map((Tecnology tecnology) {
              return DropdownMenuItem<Tecnology>(
                value: tecnology,
                child: Text(tecnology.name),
              );
            }).toList()
          : null,
      onChanged: (newValue) {
        _model.tecnology = newValue;
      },
    ));

    return form;
  }
}

class Category {
  final id;
  final name;

  Category({@required this.id, @required this.name});
}

class Tecnology {
  final id;
  final name;
  final Category category;

  Tecnology({@required this.id, @required this.name, @required this.category});
}

class FormDependency {
  final List<Category> categories;
  final List<Tecnology> tecnologies;

  FormDependency({@required this.categories, @required this.tecnologies});
}

class Model {
  Category category;
  Tecnology tecnology;

  Model({@required this.category, @required this.tecnology});
}

class CustomDropDownInput<T> extends StatelessWidget {
  const CustomDropDownInput({
    Key key,
    @required this.labelText,
    @required this.itemList,
    @required this.onChanged,
    this.initialValue,
    this.show,
    this.enabled,
    this.optional,
  }) : super(key: key);

  final String labelText;
  final List<DropdownMenuItem<T>> itemList;
  final ValueChanged<T> onChanged;
  final T initialValue;
  final bool show;
  final bool enabled;
  final bool optional;

  String _validateOptional(T value) {
    if (value == null) return "Campo obrigatório";

    return null;
  }

  void _handleOnChanged(T newValue) {
    if (newValue != null) {
      // Call onChanged callback if registered
      if (onChanged != null) onChanged(newValue);
    }
  }

  @override
  Widget build(BuildContext context) {
    return (show == null || show == true)
        ? Column(
            children: <Widget>[
              DropdownButtonFormField(
                icon: Icon(Icons.search),
                isDense: true,
                decoration: InputDecoration(
                  labelText: labelText,
                  labelStyle: TextStyle(
                    color: (optional != null && optional == false)
                        ? Colors.redAccent
                        : Colors.black38,
                    fontWeight: FontWeight.bold,
                    fontSize: 15.0,
                  ),
                  filled: false,
                  border: const OutlineInputBorder(),
                ),
                validator: (optional != null && optional == false)
                    ? _validateOptional
                    : null,
                disabledHint: (enabled != null &&
                        enabled == false &&
                        itemList != null &&
                        initialValue != null)
                    ? itemList.firstWhere((x) => x.value == initialValue).child
                    : null,
                items: (enabled != null && enabled == false) ? null : itemList,
                onChanged: _handleOnChanged,
                value: initialValue,
              ),
              const SizedBox(
                height: 20.0,
              )
            ],
          )
        : Container();
  }
}
```

**Comment by TahaTesser** [comment] 2020-05-11 15:08
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision a849daf283 (3 days ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!


``` 

</details>

**Comment by TahaTesser** [comment] 2020-05-12 07:22
Hi @newbieflutter 
First thought it might be crash but you getting null items, which isn't a Flutter but code 
Your implementation has something wrong so i created an example for you

Please checkout this [Code Gist](https://gist.github.com/tesserx/e0d2c4518c5765f5942dfba243d109d4)
If you want to learn more about this example, checkout. [Multi-Level Dependent Dropdown](https://medium.com/@afegbua/flutter-thursday-08-multi-level-dependent-dropdown-d965c08d2748)

Closing, as this isn't an issue with Flutter itself but code issue
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-12 07:22 UTC
Labels: in triage

**Comment by aopar75** [comment] 2020-05-12 19:08
Hi @TahaTesser, as @newbieflutter described, the bug is on DropdownButtonFormField widget, In your example you uses DropdownButton.
I have the same issue in my code.. 

Regards.
