### ISSUE TITLE
crash gif

### ISSUE THREAD

**Issue by fly512** [flutter/flutter#25845] opened 2018-12-28 15:10 UTC
flutter V1.1.4
Profile mode        iPhone 6 Plus 12.1.2 (16C104) 
```
[✓] Flutter (Channel unknown, v1.1.4, on Mac OS X 10.14 18A2063, locale zh-Hans-CN)
    • Flutter version 1.1.4 at /Users/xxx/Desktop/workspace/flutter
    • Framework revision 7a88fbc5fd (8 days ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4886.3

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1
```

```
0 Flutter | std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<int, std::__1::unique_ptr<blink::MultiFrameCodec::DecodedFrame, std::__1::default_delete<blink::MultiFrameCodec::DecodedFrame> > >, std::__1::__tree_node<std::__1::__value_type<int, std::__1::unique_ptr<blink::MultiFrameCodec::DecodedFrame, std::__1::default_delete<blink::MultiFrameCodec::DecodedFrame> > >, void*>*, long>, bool> std::__1::__tree<std::__1::__value_type<int, std::__1::unique_ptr<blink::MultiFrameCodec::DecodedFrame, std::__1::default_delete<blink::MultiFrameCodec::DecodedFrame> > >, std::__1::__map_value_compare<int, std::__1::__value_type<int, std::__1::unique_ptr<blink::MultiFrameCodec::DecodedFrame, std::__1::default_delete<blink::MultiFrameCodec::DecodedFrame> > >, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, std::__1::unique_ptr<blink::MultiFrameCodec::DecodedFrame, std::__1::default_delete<blink::MultiFrameCodec::DecodedFrame> > > > >::__emplace_unique_key_args<int, std::__1::piecewise_construct_t const&, std::__1::tuple<int const&>, std::__1::tuple<> >(int const&, std::__1::piecewise_construct_t const&&&, std::__1::tuple<int const&>&&, std::__1::tuple<>&&) + 68
-- | --
1 Flutter | blink::MultiFrameCodec::GetNextFrameImage(fml::WeakPtr<GrContext>) + 72
2 Flutter | blink::MultiFrameCodec::GetNextFrameImage(fml::WeakPtr<GrContext>) + 72
3 Flutter | _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN5blink15MultiFrameCodec12getNextFrameEP12_Dart_HandleE3$_3EENS_9allocatorISA_EEFvvEEclEv + 196
4 Flutter | fml::MessageLoopImpl::RunExpiredTasks() + 2060
5 Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
6 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
7 CoreFoundation | ___CFRunLoopDoTimer + 864
8 CoreFoundation | ___CFRunLoopDoTimers + 248
9 CoreFoundation | ___CFRunLoopRun + 1880
10 CoreFoundation | CFRunLoopRunSpecific + 436
11 Flutter | fml::MessageLoopDarwin::Run() + 88
12 Flutter | _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 272
13 libsystem_pthread.dylib | __pthread_body + 128
14 libsystem_pthread.dylib | _pthread_start + 48
```

**Comment by kangwang1988** [comment] 2018-12-28 15:32
@fly512 
Please paster `flutter doctor -v` result here.
If possible, please give us a demo project which can reproduce this problem, for example, one github repo.

**Comment by kangwang1988** [comment] 2018-12-29 02:48
@mklim  Can you have a look at this issue?

**Comment by mklim** [comment] 2018-12-29 16:55
Thanks for reporting the problem! I'm not completely sure, but it's possible that this may already be fixed in the next release of flutter. flutter/engine#7048 fixed another GIF decoding issue and removed one of the classes mentioned in this stack trace. Is it possible to check and see if you're still seeing this problem on the master channel?

**Comment by fly512** [comment] 2019-01-02 02:03
Thank you. I'll verify this later.

**Comment by fly512** [comment] 2019-01-08 07:21
`

0 Flutter | SkGifCodec::decodeFrame(bool, SkCodec::Options const&, int*) + 1012
-- | --
1 Flutter | SkGifCodec::decodeFrame(bool, SkCodec::Options const&, int*) + 2088
2 Flutter | SkCodec::getPixels(SkImageInfo const&, void*, unsigned long, SkCodec::Options const*) + 632
3 Flutter | blink::MultiFrameCodec::GetNextFrameImage(fml::WeakPtr<GrContext>) + 1460
4 Flutter | _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN5blink15MultiFrameCodec12getNextFrameEP12_Dart_HandleE3$_3EENS_9allocatorISA_EEFvvEEclEv + 196
5 Flutter | fml::MessageLoopImpl::RunExpiredTasks() + 2060
6 Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
7 CoreFoundation | 0x00000001e2d43000 + 720152
8 CoreFoundation | 0x00000001e2d43000 + 812539093645892
9 CoreFoundation | 0x00000001e2d43000 + 29391595078611512
10 CoreFoundation | 0x00000001e2d43000 + 13208982940983032
11 CoreFoundation | CFRunLoopRunSpecific + 8862063719875012
12 Flutter | fml::MessageLoopDarwin::Run() + 34627469449363544
13 Flutter | _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 272
14 libsystem_pthread.dylib | 0x00000001e2a66000 + 6516
15 libsystem_pthread.dylib | _pthread_start + 23317343090245684


`

**Comment by mklim** [comment] 2019-01-08 18:16
```
0 Flutter | SkGifCodec::decodeFrame(bool, SkCodec::Options const&, int*) + 1012
1 Flutter | SkGifCodec::decodeFrame(bool, SkCodec::Options const&, int*) + 2088
2 Flutter | SkCodec::getPixels(SkImageInfo const&, void*, unsigned long, SkCodec::Options const*) + 632
3 Flutter | blink::MultiFrameCodec::GetNextFrameImage(fml::WeakPtr) + 1460
```

Thanks for the second look @fly512. So what I can see from this is that the crash is happening in Skia itself, and it's being triggered from our call to actually decode a frame at [`SkCodec#getPixels`](https://github.com/google/skia/blob/master/src/codec/SkCodec.cpp#L308) in [`MultiFrameCodec#GetNextFrameImage`](https://github.com/flutter/engine/blob/770536a/lib/ui/painting/codec.cc#L425). I think `SkCodec#getPixels` [is calling through to `SkGifCodec#onGetPixels`](https://github.com/google/skia/blob/master/src/codec/SkCodec.cpp#L362) and then [that calls through to `SkGifCodec#decodeFrame`](https://github.com/google/skia/blob/36f7e3298e9d8e21d095197db0ec72c155f7d61f/src/codec/SkGifCodec.cpp#L292), [where we're finally seeing the crash](https://github.com/google/skia/blob/36f7e3298e9d8e21d095197db0ec72c155f7d61f/src/codec/SkGifCodec.cpp#L322).

I'm guessing the crash is because of something unexpected about how the GIF it's trying to decode here has been encoded. The most suspicious thing at first glance is that it looks like there's an assert that can throw if it's on an unexpected frame number. Would it be possible for you to upload the file that's causing this crash for me to take a look at? So far I haven't seen this stack trace myself to investigate.

**Comment by fly512** [comment] 2019-01-09 11:52
We use gif expressions, the number of gifs is limited, not more than 100, I played all the gifs, and found no gifs will collapse.

Currently this version has been audited on the Appstore and some crash logs will be provided later

**Comment by mklim** [comment] 2019-01-15 22:08
I reached out to the Skia team, but unfortunately they weren't able to debug this from the stack trace alone either. 

Is it possible that this is device specific in some way? I see iPhone XS Max 12.1.2 and iPhone 6 Plus 12.1.2 mentioned. Are those the only combinations of device/OS versions that this crash is happening on, or is it more widespread?

**Comment by zoechi** [comment] 2019-02-18 07:50
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by fly512** [comment] 2019-02-28 02:38
@mklim @kangwang1988

Now, we find a 100% crash on an iPhone 6，When the iPhone is lit from the lock screen
According to the crash report, there are other models with the same crash, but we haven't seen it yet.

我们手上目前有一个iphone6，发现了一个必现的崩溃，在ui上只放一个小gif，然后锁屏，再点亮屏幕，程序就崩溃了。

[https://github.com/flutter/flutter/issues/22933#issuecomment-467430875](url)

**Comment by kangwang1988** [comment] 2019-03-01 04:12
@fly512 
A demo project would be helpful.
Besides, I've create a sample project with a gif and following the steps you described, it works fine.
I'm using the flutter master branch.
```dart
[✓] Flutter (Channel master, v1.3.2-pre.9, on Mac OS X 10.14.4 18E194d, locale en-CN)
    • Flutter version 1.3.2-pre.9 at /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 338581b866 (4 hours ago), 2019-02-28 19:17:18 -0500
    • Engine revision 5194919e13
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 40bab34fbd)
```

**Comment by fly512** [comment] 2019-03-01 12:32
目前可稳定复现的崩溃仅仅发生在一个iphone6手机，且版本是11.2.6 。
其他的型号手机我们只在崩溃上报里看到，并未复现。

The current stable recurrence of the crash occurred only on an iPhone 6 phone, with version 11.2.6.
Other models of mobile phones we only saw in the crash report, did not reappear.

This is the simplest engineering address.
https://github.com/fly512/flutter_crash 

```
[✓] Flutter (Channel unknown, v1.2.0, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
    • Flutter version 1.2.0 at /Users/mayh/Desktop/workspace/flutter
    • Framework revision 06b979c4d5 (5 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mayh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • iPhone X • 53A0E96F-96D9-4255-A431-E73BD00A334A • ios • iOS 12.1
      (simulator)
```

**Comment by mklim** [comment] 2019-03-01 23:12
@fly512 thanks for the code and detailed steps!

Could you also post the stack trace for the latest crash you're seeing?

And I'm also assuming this is only happening on physical devices, not simulators?

**Comment by zhileichen** [comment] 2019-03-03 01:11
@mklim  please see this comment for detail.
 https://github.com/flutter/flutter/issues/22933#issuecomment-467430875
It indeed happens on iPhone6(iOS 11.2.6) physical devices.

**Comment by zhileichen** [comment] 2019-03-03 01:15
And according this comment, it won't crash when reproduce with same steps on iPhone 7 physical devices, but there were some GPU related errors in the console log.

**Comment by fly512** [comment] 2019-03-05 07:21
```
[Bugly]  Trapped fatal signal 'SIGSEGV(11)' 
(
    "0  libGPUSupportMercury.dylib     0x000000019e374ee8 0x000000019e373000 + 7912",
    "1  AGXGLDriver                    0x00000001a2597228 gldUpdateDispatch + 7296",
    "2  libGPUSupportMercury.dylib     0x000000019e375ecc gpusSubmitDataBuffers + 176",
    "3  AGXGLDriver                    0x00000001a2598724 gldUpdateDispatch + 12668",
    "4  Flutter                        0x0000000102df2b5c _ZN7SkImage27MakeCrossContextFromEncodedEP9GrContext5sk_spI6SkDataEbP12SkColorSpaceb + 628",
    "5  Flutter                        0x0000000102befb68 _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN5blink12_GLOBAL__N_121InstantiateImageCodecEP21_Dart_NativeArgumentsE3$_1EENS_9allocatorISA_EEFvvEEclEv + 1372",
    "6  Flutter                        0x0000000102be019c _ZN3fml15MessageLoopImpl15RunExpiredTasksEv + 824",
    "7  Flutter                        0x0000000102be357c _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32",
    "8  CoreFoundation                 0x0000000182e83dc0 0x0000000182d98000 + 966080",
    "9  CoreFoundation                 0x0000000182e83ae4 0x0000000182d98000 + 965348",
    "10 CoreFoundation                 0x0000000182e832e4 0x0000000182d98000 + 963300",
    "11 CoreFoundation                 0x0000000182e80ecc 0x0000000182d98000 + 954060",
    "12 CoreFoundation                 0x0000000182da0c58 CFRunLoopRunSpecific + 436",
    "13 Flutter                        0x0000000102be36a0 _ZN3fml17MessageLoopDarwin3RunEv + 88",
    "14 Flutter                        0x0000000102be03a8 _ZN3fml15MessageLoopImpl5DoRunEv + 52",
    "15 Flutter                        0x0000000102be2d58 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 200",
    "16 libsystem_pthread.dylib        0x0000000182b042b4 0x0000000182b02000 + 8884",
    "17 libsystem_pthread.dylib        0x0000000182b04180 0x0000000182b02000 + 8576"
)

```

**Comment by fly512** [comment] 2019-03-05 07:23
In the above-mentioned mobile phone, in a listview, when you slide quickly, you close the screen and it crashes.

**Comment by fly512** [comment] 2019-03-05 08:37
On the above machine and equipment, we found that V1.0.0 worked well and did not find the inevitable collapse.

**Comment by fly512** [comment] 2019-04-03 07:48
On V1.4.8, the problem remains 100% crash-prone.

**Comment by hllGitHub** [comment] 2019-07-15 13:32
@fly512 Can you send me the crash demo? I want to reproduce it. Thanks!

**Comment by gaaclarke** [comment] 2019-11-25 18:37
Please provide reproduction.

One of the stacktraces mentioned seemed to be related to backgrounding the app.  There was a recent fix merged for that so you can try the master channel.

**Comment by Hixie** [comment] 2019-12-18 00:49
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. I recommend filing a new bug if you are still seeing this, ideally with reliable steps to reproduce, because we've been unable to determine the cause from just the stack traces.

**Closed by Hixie** 2019-12-18 00:49 UTC
Labels: a: images, dependency: skia, engine, severe: crash, waiting for customer response
