### ISSUE TITLE
Flutter Web Iframe Reloads When Resizing Page

### ISSUE THREAD

**Issue by Akifcan** [flutter/flutter#83993] opened 2021-06-04 13:13 UTC
## Details

Hello, i use Iframe on flutter web (on Microsoft Edge Browser) i don't have any problem but when i resize the page iframe reloads.  Is there a way stop the reloads again thank you. 

**Steps To Reproduce**
```
  IFrameElement iFrameElement = IFrameElement();
  Widget _iframeWidget;

  void createiFrame() {
    iFrameElement.src = 'http://localhost:5000/#/login';
    iFrameElement.width = "337";
    iFrameElement.height = "660";
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => iFrameElement,
    );
    _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: 'iframeElement',
    );
}
```

**Target Platform:**: Web

## Logs

<details>
<summary>Logs</summary>

Flutter Doctor

```
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19041.985], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (1 available)

```

</details>

**Comment by TahaTesser** [comment] 2021-06-07 15:51
Hi @Akifcan 
This is a known issue, I can reproduce it 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  IFrameElement iFrameElement = IFrameElement();

  late  Widget _iframeWidget;

    void createiFrame() {
    iFrameElement.src = 'https://flutter.dev/docs';
    iFrameElement.width = "337";
    iFrameElement.height = "660";
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => iFrameElement,
    );
    _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: 'iframeElement',
    );
}


  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    createiFrame();
  }



  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: HtmlElementView(
          viewType: 'iframeElement',
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}



``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.226, on Microsoft Windows [Version 10.0.19043.1023], locale en-US)
    • Flutter version 2.3.0-17.0.pre.226 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c9d5485361 (17 hours ago), 2021-06-06 18:59:02 -0400
    • Engine revision 66068e2e7d
    • Dart version 2.14.0 (build 2.14.0-186.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (5 available)
    • IN2011 (mobile)         • c9d8ee0c • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.19043.1023]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 91.0.4472.77
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 91.0.864.41

• No issues found!
```

</details>

Closing as duplicate of  https://github.com/flutter/flutter/issues/80524 

https://github.com/flutter/flutter/issues/79065
https://github.com/flutter/flutter/issues/51865

**Closed by TahaTesser** 2021-06-07 15:51 UTC
Labels: in triage

**Comment by ditman** [comment] 2021-06-07 17:51
Yes, a fix for this exists in the `master` channel (maybe `dev` too, not sure). Thanks for reporting @Akifcan!
