### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Volumes/Mac/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.

### ISSUE THREAD

**Issue by qinglixiao** [flutter/flutter#66018] opened 2020-09-17 12:01 UTC
## Command
```
flutter assemble --output=/Volumes/Mac/work/iEnglish/code/flutter_ienglish_fine/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=/Volumes/Mac/work/iEnglish/code/flutter_ienglish_fine/lib/main.dart -dBuildMode=release -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --DartDefines=flutter.inspector.structuredErrors=true -dExtraFrontEndOptions= release_ios_bundle_flutter_assets
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Volumes/Mac/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:69:31)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
#12     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Volumes/Mac/flutter
    • Framework revision e6b34c2b5c (5 months ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chunyu/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/chunyu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.8)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • iPhone (8) • 41e3889244ccfd02d93728dff2d05b42f4c44308 • ios • iOS 11.3
    • iPhone 11  • 395BABB4-A2E0-4435-97AB-63E43BE5E50B     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f
### Plugins
fluwx-2.3.0
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
screen-0.0.5
shared_preferences-0.5.7
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.0
url_launcher-5.6.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.3+2
url_launcher_windows-0.0.1+1
video_player-0.10.12+2
video_player_web-0.1.3+2
wakelock-0.1.4+2
webview_flutter-0.3.22+1

**Comment by TahaTesser** [comment] 2020-09-17 15:05
Hi @ihsh,
Please see [this](https://github.com/flutter/flutter/issues/57929) related issue. You seem to be on old version of Flutter. I'd suggest you to upgrade to latest stable or master and try again. This issue was [fixed](https://github.com/flutter/flutter/pull/57874) and merged.

duplicate of https://github.com/flutter/flutter/issues/65924

Thanks.

**Closed by TahaTesser** 2020-09-17 15:05 UTC

**Comment by berrylawchingman** [comment] 2020-09-17 15:13
Ok kill/

**Comment by berrylawchingman** [comment] 2020-09-17 15:25
Ok thx
