### ISSUE TITLE
Flutter for MacOS not work with Network Extension. 

### ISSUE THREAD

**Issue by whitemay** [flutter/flutter#52877] opened 2020-03-19 09:52 UTC
I recently work on building UI for my macos app. I found out that the app can't start up after I added Network Extension framework in it. 
No code for NE yet, just added the framework in. logout says:

```
Launching lib/main.dart on macOS in debug mode...
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on macOS.
Exited (sigterm)
```

My current platform is: Flutter (Channel dev, v1.16.0, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
I had tried to clean & rebuild the project. no use.

Actually I found out that it goes well if I move the network extension related entry from entitlements file, with the framework left in the app.
btw, NE works fine under iOS with flutter.

**Comment by TahaTesser** [comment] 2020-03-19 11:02
Duplicate of [#52764](https://github.com/flutter/flutter/issues/52764)

**Comment by TahaTesser** [comment] 2020-03-19 11:42
Reopened the issue based on this [comment](https://github.com/flutter/flutter/issues/52764#issuecomment-601127009)

**Comment by stuartmorgan** [comment] 2020-03-19 14:23
> I found out that it goes well if I move the network extension related entry from entitlements file

What are the exact changes you are making that cause it to fail?

Also, please run the app from Xcode, rather than `flutter run`, so that you can get a crash stack if it's crashing (vs. being killed by the OS).

**Comment by whitemay** [comment] 2020-03-25 08:23
Just upgrade my flutter to v1.16.2 to ensure the issue still exists.
error log below:

`
[   +9 ms] executing: /usr/bin/plutil -convert json -o - /Homes/aston/git/flutter_keyaas/build/macos/Build/Products/Debug/keyaas.app/Contents/Info.plist
[  +26 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Homes/aston/git/flutter_keyaas/build/macos/Build/Products/Debug/keyaas.app/Contents/Info.plist
[        ] {"CFBundleName":"keyaas","DTXcode":"1140","DTSDKName":"macosx10.15","NSHumanReadableCopyright":"Copyright © 2020 cn.yunid. All rights
reserved.","DTSDKBuild":"19E258","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"19D76","NSPrincipalClass":"NSApplication","CFBundleIconName":"Ap
pIcon","CFBundlePackageType":"APPL","CFBundleIconFile":"AppIcon","CFBundleSupportedPlatforms":["MacOSX"],"CFBundleShortVersionString":"1.0.0","NSMainNibFile":"MainMenu","CFBun
dleInfoDictionaryVersion":"6.0","CFBundleExecutable":"keyaas","DTCompiler":"com.apple.compilers.llvm.clang.1_0","CFBundleIdentifier":"cn.yunid.keyaas","DTPlatformVersion":"GM"
,"DTXcodeBuild":"11E146","LSMinimumSystemVersion":"10.11","DTPlatformBuild":"11E146"}
[  +68 ms] Error waiting for a debug connection: The log reader stopped unexpectedly.
[   +6 ms] Error launching application on macOS.
[  +95 ms] "flutter run" took 74,201ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:715:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:612:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1147:13)
#7      _CustomZone.run (dart:async/zone.dart:1040:19)
#8      _runZoned (dart:async/zone.dart:1539:10)
#9      runZoned (dart:async/zone.dart:1486:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:602:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1147:13)
#17     _CustomZone.run (dart:async/zone.dart:1040:19)
#18     _runZoned (dart:async/zone.dart:1539:10)
#19     runZoned (dart:async/zone.dart:1486:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
#27     _rootRun (dart:async/zone.dart:1147:13)
#28     _CustomZone.run (dart:async/zone.dart:1040:19)
#29     _runZoned (dart:async/zone.dart:1539:10)
#30     runZoned (dart:async/zone.dart:1523:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#32     run.<anonymous closure> (package:flutter_tools/runner.dart)
#33     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:67:18)
<asynchronous suspension>
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#36     _rootRun (dart:async/zone.dart:1147:13)
#37     _CustomZone.run (dart:async/zone.dart:1040:19)
#38     _runZoned (dart:async/zone.dart:1539:10)
#39     runZoned (dart:async/zone.dart:1486:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#41     runInContext (package:flutter_tools/src/context_runner.dart:70:24)
#42     run (package:flutter_tools/runner.dart:47:10)
#43     main (package:flutter_tools/executable.dart:69:9)
#44     main (file:///Homes/aston/git/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
`

**Comment by stuartmorgan** [comment] 2020-03-25 16:24
Looks like there's no OS logging, unfortunately.

Again, what are the exact changes you made to the project (linking, entitlements, etc.) to cause this? The description so far is too vague for anyone to be able to reproduce it for further debugging.

**Comment by whitemay** [comment] 2020-03-26 08:18
it is really simple to reproduct it. 
1. create a flutter project with desktop dest.
2. in MacOS runner, add Network Extionsion support. sure u also hv to enable code sign as needed.
3. try to run it. then the issue shows.

**Comment by stuartmorgan** [comment] 2020-03-26 14:59
> in MacOS runner, add Network Extionsion support.

Meaning what, exactly? You referenced entitlement changes you made, but not what they are.

**Comment by whitemay** [comment] 2020-03-27 06:53
Step 2 I mean in Xcode, add Network Extension support in Project settings. as i know, it actually does 2 actions below.
1. add Network Extension framework into the project.
2. add Network Extension entries in the entitlement file.
after steps above, the issue occured. 

and then i tried to comment the entries from entitlement file by hand, with framework remained. the issue disappered.
and i uncomment the entries again, the issue occur again.

btw, edit the entitlement file by hand is not a common step. so it is just some additional information about this issue, not really important.

**Comment by whitemay** [comment] 2020-03-31 07:50
I try to run in release mode, then some new information shows in Xcode.

Exhausted heap space, trying to allocate 32 bytes.
../../third_party/dart/runtime/vm/object.cc: 2577: error: Out of memory.
version=2.8.0-dev.17.0.flutter-1402e8e1a4 (be) (Thu Mar 26 13:15:18 2020 +0000) on "macos_x64"
pid=29019, thread=775, isolate=vm-isolate(0x1030c6e00)
isolate_instructions=1009edc20, vm_instructions=1009edc20
  pc 0x0000000100b479a5 fp 0x00007ffeefbfb3c0 dart::Profiler::DumpStackTrace(void*)+0x85
  pc 0x00000001009edd72 fp 0x00007ffeefbfb4a0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x0000000100ab8732 fp 0x00007ffeefbfb4f0 dart::Object::Allocate(long, long, dart::Heap::Space)+0x152
  pc 0x0000000100b01f6e fp 0x00007ffeefbfb550 dart::Code::FinalizeCode(dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0xae
  pc 0x0000000100b0235a fp 0x00007ffeefbfb580 dart::Code::FinalizeCodeAndNotify(char const*, dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0x2a
  pc 0x0000000100bc1ba2 fp 0x00007ffeefbfb690 dart::StubCode::Generate(char const*, dart::compiler::ObjectPoolBuilder*, void (*)(dart::compiler::Assembler*))+0x52
  pc 0x0000000100bc1a3b fp 0x00007ffeefbfb760 dart::StubCode::Init()+0xcb
  pc 0x0000000100a3fd5e fp 0x00007ffeefbfb930 dart::Dart::Init(unsigned char const*, unsigned char const*, _Dart_Isolate* (*)(char const*, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**), bool (*)(void**, char**), void (*)(void*, void*), void (*)(void*, void*), void (*)(void*), void (*)(), void* (*)(char const*, bool), void (*)(unsigned char**, long*, void*), void (*)(void const*, long, void*), void (*)(void*), bool (*)(unsigned char*, long), _Dart_Handle* (*)(), bool, Dart_CodeObserver*)+0x54e
  pc 0x0000000100df3065 fp 0x00007ffeefbfb9a0 Dart_Initialize+0x65
  pc 0x00000001009e4b85 fp 0x00007ffeefbfbbf0 flutter::DartVM::DartVM(std::__1::shared_ptr<flutter::DartVMData const>, std::__1::shared_ptr<flutter::IsolateNameServer>)+0xae5
  pc 0x00000001009e3f58 fp 0x00007ffeefbfc2b0 flutter::DartVM::Create(flutter::Settings, fml::RefPtr<flutter::DartSnapshot>, fml::RefPtr<flutter::DartSnapshot>, std::__1::shared_ptr<flutter::IsolateNameServer>)+0x138
  pc 0x00000001009e61ce fp 0x00007ffeefbfc970 flutter::DartVMRef::Create(flutter::Settings, fml::RefPtr<flutter::DartSnapshot>, fml::RefPtr<flutter::DartSnapshot>)+0x23e
  pc 0x00000001007a515c fp 0x00007ffeefbfd6e0 flutter::Shell::Create(flutter::TaskRunners, flutter::WindowData, flutter::Settings, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)>, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)>)+0x10c
  pc 0x00000001007a4fc0 fp 0x00007ffeefbfde20 flutter::Shell::Create(flutter::TaskRunners, flutter::Settings, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)+0x100
  pc 0x00000001002ed38f fp 0x00007ffeefbfe3b0 flutter::EmbedderEngine::LaunchShell()+0x7f
  pc 0x00000001002dcdcb fp 0x00007ffeefbfe4f0 FlutterEngineRunInitialized+0x17b
  pc 0x00000001002cb718 fp 0x00007ffeefbfe6c0 -[FlutterEngine runWithEntrypoint:]+0x288
  pc 0x00000001002d10e7 fp 0x00007ffeefbfe6f0 -[FlutterViewController launchEngine]+0x57
  pc 0x00000001002d0d95 fp 0x00007ffeefbfe720 -[FlutterViewController viewWillAppear]+0x65
  pc 0x00007fff35ea4e73 fp 0x00007ffeefbfe740 -[NSViewController _sendViewWillAppear]+0x28
  pc 0x00007fff35ea4d2f fp 0x00007ffeefbfe770 -[NSViewController _windowWillOrderOnScreen]+0x62
  pc 0x00007fff35ea4bd6 fp 0x00007ffeefbfe870 -[NSView(NSInternal) _windowWillOrderOnScreen]+0x43
  pc 0x00007fff35ea4c6c fp 0x00007ffeefbfe970 -[NSView(NSInternal) _windowWillOrderOnScreen]+0xd9
  pc 0x00007fff35ea4a83 fp 0x00007ffeefbfe9a0 -[NSWindow _doWindowWillBeVisibleAsSheet:]+0x3b
  pc 0x00007fff35ea2556 fp 0x00007ffeefbfebd0 -[NSWindow _reallyDoOrderWindowAboveOrBelow:relativeTo:findKey:forCounter:force:isModal:]+0x5ed
  pc 0x00007fff35ea1c12 fp 0x00007ffeefbfec30 -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:]+0x87
  pc 0x00007fff35ea0b9e fp 0x00007ffeefbfed30 -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:]+0x125
  pc 0x00007fff35ea0a17 fp 0x00007ffeefbfed80 -[NSWindow orderWindow:relativeTo:]+0x9b
  pc 0x00007fff35d207b5 fp 0x00007ffeefbff0e0 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:]+0x86b
  pc 0x00007fff35d14331 fp 0x00007ffeefbff130 loadNib+0x191
  pc 0x00007fff35d138f2 fp 0x00007ffeefbff1f0 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:]+0x2b5
  pc 0x00007fff35d13548 fp 0x00007ffeefbff310 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:]+0xc9
  pc 0x00007fff35d13321 fp 0x00007ffeefbff430 +[NSBundle(NSNibLoading) loadNibNamed:owner:]+0x1be
  pc 0x00007fff35d04ee6 fp 0x00007ffeefbff480 NSApplicationMain+0x1f9
  pc 0x0000000100002069 fp 0x00007ffeefbff490 main+0x9
  pc 0x00007fff72ad1cc9 fp 0x00007ffeefbff4a0 start+0x1
-- End of DumpStackTrace

**Comment by whitemay** [comment] 2020-04-29 06:52
some additional information today:
i tried to run in release mode today, and the application works well on MacOS platform. so i guess the issue on MacOS platform is actually related to the debug part of the flatter, not the app part.

**Comment by gicounts** [comment] 2020-05-20 14:37
@whitemay I'm apparently going through the same issue for a Flutter app I'm trying to deploy on iOS.  I'm brand new to Apple/Xcode and just using MacInCloud for the first time.  So if you could lay out some steps to get around this problem for a newbie, I would appreciate it.

When I open the iOS module in Xcode it seems to get hung up on Signing & Capabilities.  But I'm not sure if this is where the problem originates.

**Comment by stuartmorgan** [comment] 2020-05-20 15:25
@gicounts This issue is about Flutter for macOS, not Flutter for iOS.

**Comment by gicounts** [comment] 2020-05-20 18:00
@stuartmorgan Thanks I had totally missed that.  However, I am getting the same error and I'm hoping @whitemay might still be able to point me in the right direction.  I've spent three days trying to get around this.  And I'm just trying to run this on a simulator.

> Launching lib/main.dart on iPhone 8 Plus in debug mode...
> log: Must be admin to run 'stream' command
> Script started, output file is /dev/null
> 
> Script done, output file is /dev/null
> Running pod install...                                             27.4s
> Running Xcode build...
> Xcode build done.                                           382.8s
> Error waiting for a debug connection: The log reader failed unexpectedly
> Error launching application on iPhone 8 Plus.

**Comment by stuartmorgan** [comment] 2020-05-20 18:06
@gicounts And this is happening when you try to use NetworkExtension in your iOS application?

**Comment by gicounts** [comment] 2020-05-20 18:31
@stuartmorgan I'm not sure.  I couldn't locate the entitlements file in Xcode.  And I'm not sure if one of the packages in my app, like Agora RTC, is using it.  I get similar behavior in that the app loads in the simulator, appears to open, and then fails.

**Comment by stuartmorgan** [comment] 2020-05-20 19:11
@gicounts There are many, many things that could cause an application to crash on launch. If you aren't using NetworkExtension your issue is unrelated to this one.

**Comment by gicounts** [comment] 2020-05-21 13:46
@stuartmorgan You were right.  I was able to capture the fault:
*** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'

**Comment by elsadeny** [comment] 2021-08-20 12:03
> I recently work on building UI for my macos app. I found out that the app can't start up after I added Network Extension framework in it.
> No code for NE yet, just added the framework in. logout says:
> 
> ```
> Launching lib/main.dart on macOS in debug mode...
> Error waiting for a debug connection: The log reader stopped unexpectedly.
> Error launching application on macOS.
> Exited (sigterm)
> ```
> 
> My current platform is: Flutter (Channel dev, v1.16.0, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
> I had tried to clean & rebuild the project. no use.
> 
> Actually I found out that it goes well if I move the network extension related entry from entitlements file, with the framework left in the app.
> btw, NE works fine under iOS with flutter.

Did you manage to figure it out?

**Comment by gspencergoog** [comment] 2022-08-11 18:26
Please check this StackOverflow answer: https://stackoverflow.com/questions/57841871/flutter-http-get-fails-on-macos-build-target-connection-failed

And look at the documentation about entitlements on flutter.dev: https://docs.flutter.dev/development/platform-integration/desktop#setting-up-entitlements

And if those don't fix the issue, please comment on this issue and we'll reopen it.

(Desktop Triage)

**Closed by gspencergoog** 2022-08-11 18:26 UTC
Labels: severe: crash, platform-mac, a: desktop, P6
