### ISSUE TITLE
Having problem installing video_player v2.4.5 on pub.dev

### ISSUE THREAD

**Issue by travisdang36** [flutter/flutter#107457] opened 2022-07-12 09:30 UTC
I have `flutter pub add video_player` into my project, but it seems like none of the actual files is being accessible for me, and my Flutter version is 3.0.4, but the `video_player` dependencies still are shown in pubspec.yaml. I have tried to `flutter pub remove video_player` and re-adding it again, but it doesn't seem to do anything. In addition, it is introducing errors in my "generated_plugin_registrant.dart". If anybody is having the same issues with using video_player, can you help me with the situation that I'm currently having?

Thank you for your input.

**Comment by exaby73** [comment] 2022-07-12 09:36
Hello @travisdang36. Have you tried running `flutter clean` and then `flutter pub get` again? Also, can you provide the output to `flutter doctor -v`?

**Comment by travisdang36** [comment] 2022-07-14 02:01
I did run `flutter pub get`, but it didn't really change anything inside VSC, and it is still currently the same issue. I also have included two screenshot of `flutter doctor -v` and current problems that is currently happening with using `video_player` on pub.dev

<img width="1680" alt="Screen Shot 2022-07-14 at 8 58 57 AM" src="https://user-images.githubusercontent.com/82469971/178880184-14a532fb-5b1a-41ba-a6f1-f655f1893161.png">
![Screen Shot 2022-07-14 at 8 58 57 AM 2](https://user-images.githubusercontent.com/82469971/178880238-5e300c52-3fb7-42ba-8a12-86971b8b98f0.png)

<img width="1414" alt="Screen Shot 2022-07-14 at 9 00 30 AM" src="https://user-images.githubusercontent.com/82469971/178880635-1f7b6448-01cf-434d-95b7-fcfc7a4ed291.png">

**Comment by travisdang36** [comment] 2022-07-14 02:19
What does `podfile.lock` contribute to the addition of `pubspec.yaml` because for some reason the `video_player` package is currently working, and no longer giving me an error in my `vid_player.dart`

**Comment by exaby73** [comment] 2022-07-14 08:02
The `Podfile.lock` is for cocoapods, which is an iOS package manager. Can you provide your `pubspec.yaml` file as well?

Also I notice you are running `flutter pub get video_player`. To install a package in your project, you have to run `flutter pub add video_player`. `flutter pub get` is used to download dependencies already present in your `pubspec.yaml`.

**Comment by travisdang36** [comment] 2022-07-18 02:24
I did run `flutter pub add video_player` before running `flutter pub get`. Right now, I don't have anymore issues with using the `video_player` dependencies in my app, but I need to get some tutorial about playing video in fullscreen, and how to hide the `BottomNavigationBar` when going into landscape for playing video.

<img width="1792" alt="Screen Shot 2022-07-18 at 9 22 54 AM" src="https://user-images.githubusercontent.com/82469971/179436643-0a8fac2f-e672-48ea-8542-ff47b2bbd165.png">

**Comment by exaby73** [comment] 2022-07-18 03:39
@travisdang36 Glad you were able to solve your issue. Though, for tutorials or help with your code, please looks at Youtube or Stackoverflow for answers. You can also look into communities highlighted on https://flutter.dev/community. Since this issue is not a bug or feature request, I am closing it. Thank you

**Closed** 2022-07-18 03:44 UTC
Labels: r: invalid
