### ISSUE TITLE
ListView scrolling performance

### ISSUE THREAD

**Issue by werner-scholtz** [flutter/flutter#128487] opened 2023-06-08 06:42 UTC
## Details

The main reason for this Issue is because the final app will run on a device with less than desirable hardware and performance will be important.

When scrolling with speed through a List View there are widgets that regularly take long to build in comparison to others and when more widgets are added to each list row this impacts performance even more, is there a solution to this or some information as to why it is happening ? 

You can reproduce this issue by cloning the [example app ](https://github.com/werner-scholtz/list_view_example), then grab the scrollbar of the list view and drag it up and down.

Example application: https://github.com/werner-scholtz/list_view_example 

4. Using `flutter run --profile --trace-skia` on master channel.
Here you can see that some text widgets take longer than other text widgets.
![linux_perforamance](https://github.com/flutter/flutter/assets/121276491/1c38cae9-063a-403e-895d-902d645da131)

Here is the video:

https://github.com/flutter/flutter/assets/121276491/c591e41c-1622-4834-bc7a-5a91dd264a88

Here is the dart_devtools save:
[dart_devtools_2023-06-08_08_14_39.347.zip](https://github.com/flutter/flutter/files/11684766/dart_devtools_2023-06-08_08_14_39.347.zip)

**Target Platform: Android, Linux, Windows**
**Target OS version/browser: Android 13.0, Android 12.0, Ubuntu 22.04.2, Windows 10**
**Devices: I have checked on Windows. Linux and Android and this is happening on all devices.**

## Logs

<details>
<summary>Logs</summary>

```
Analyzing list_view_example...                                          
No issues found! (ran in 1.0s)
```

```
[✓] Flutter (Channel stable, 3.10.2, on Ubuntu 22.04.2 LTS 6.1.0-1004-oem, locale en_ZA.UTF-8)
    • Flutter version 3.10.2 on channel stable at /home/werner/KDAB/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (2 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/werner/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /snap/android-studio/126/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at /snap/android-studio/126/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.66.0

[✓] Connected device (5 available)
    • M2101K7BG (mobile)           • SCGUKBBEU85DSODI • android-arm64  • Android 13 (API 33)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux            • linux-x64      • Ubuntu 22.04.2 LTS 6.1.0-1004-oem
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 114.0.5735.106
    • SK-AM62 (mobile)             • TI AM62x Board   • linux-arm64    • SDK Linux for AM62x 08_04_01_03

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-06-08 09:35
Hi @werner-scholtz. Thanks for filing this issue. I'm able to reproduce and this seems to be related to #52207. Kindly confirm on your end that it is as well.

**Comment by werner-scholtz** [comment] 2023-06-09 08:17
Hi @dam-ease I have tested this on Android, Linux and Windows and all devices show this behaviour.
It is similar to #52207 one difference being that in this example the `itemExtent: 48,` property on the list view is declared which increases performance by a lot. 

I just want to know why some of the text widgets in this example takes multiple times longer than other text widgets and if there is a fix for it.

**Comment by dam-ease** [comment] 2023-06-12 07:32
Thanks for this @werner-scholtz. Closing this as a duplicate, you can comment on issue #52207, upvote and follow up on updates.

**Closed by dam-ease** 2023-06-12 07:32 UTC
Labels: in triage
