### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The getter 'ZERODIGIT' was called on null.

### ISSUE THREAD

**Issue by liudonghua123** [flutter/flutter#61539] opened 2020-07-15 13:33 UTC
## Steps to Reproduce

1. I executed some code like the following
```dart
DateFormat dateFormat = DateFormat('yyyy-MM-dd HH:mm:ss');
dateFormat.format(lastLoginDatetime);
```
2. The the exception thrown.

In my environment, my local is 'zh-CN', I also read the doc on https://stackoverflow.com/questions/16126579/how-do-i-format-a-date-with-dart, and it refered the following pieces.
> For non-en_US dates, you need to explicitly load in the locale. See the DateFormat docs for more info. The date_symbol_data_local.dart contains all of the formats for each country/language, if you would like a more in-depth look.

So I tried to executed `initializeDateFormatting('zh_CN', null);` or `initializeDateFormatting('en_US', null);`, but the problem stills.

**Expected results:** 
The code works.

**Actual results:** 
Exception thrown.

<details>
  <summary>Logs</summary>

```
E/flutter (31053): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter 'ZERODIGIT' was called on null.
E/flutter (31053): Receiver: null
E/flutter (31053): Tried calling: ZERODIGIT
E/flutter (31053): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
E/flutter (31053): #1      DateFormat.localeZero 
package:intl/…/intl/date_format.dart:743
E/flutter (31053): #2      DateFormat.localeZeroCodeUnit 
package:intl/…/intl/date_format.dart:735
E/flutter (31053): #3      DateFormat._localizeDigits 
package:intl/…/intl/date_format.dart:760
E/flutter (31053): #4      _DateFormatPatternField.padTo 
package:intl/…/intl/date_format_field.dart:650
E/flutter (31053): #5      _DateFormatPatternField.formatYear 
package:intl/…/intl/date_format_field.dart:403
E/flutter (31053): #6      _DateFormatPatternField.formatField 
package:intl/…/intl/date_format_field.dart:379
E/flutter (31053): #7      _DateFormatPatternField.format 
package:intl/…/intl/date_format_field.dart:244
E/flutter (31053): #8      DateFormat.format 
package:intl/…/intl/date_format.dart:276
E/flutter (31053): #9      Preference.lastLoginDatetime= 
package:colorful_classroom_app/preference.dart:81
E/flutter (31053): #10     Utils.updateLoginInfo 
package:colorful_classroom_app/utils.dart:35
E/flutter (31053): #11     _LoginPageState.build.<anonymous closure> 
package:colorful_classroom_app/pages/login_page.dart:325
E/flutter (31053): #12     _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (31053): #13     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (31053): #14     _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (31053): #15     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (31053): #16     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (31053): #17     Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (31053): #18     Future._asyncCompleteWithValue.<anonymous closure>  (dart:async/future_impl.dart:567:7)
E/flutter (31053): #19     _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (31053): #20     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (31053): #21     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (31053): #22     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (31053): #23     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
E/flutter (31053): #24     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
```

```
```

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-8.0.pre.102, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
[✓] Android Studio (version 4.0)
[✓] VS Code, 64-bit edition (version 1.47.0)
[✓] Connected device (4 available)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-15 14:13
Hi @liudonghua123 
what the value do you have as `lastLoginDatetime`?
does it persist with 

```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: RaisedButton(
            onPressed: () {
              DateFormat dateFormat = DateFormat('yyyy-MM-dd HH:mm:ss');
              print(dateFormat.format(DateTime.now()));
            },
          ),
        ),
      ),
    );
  }
}
```

?

**Comment by liudonghua123** [comment] 2020-07-15 14:21
@VladyslavBondarenko Hi, the `lastLoginDatetime` value is just `DateTime.now()`.

I found the exception was thrown in `dart_format.dart#743`. the `localeZero` was null, `useNativeDigits` was true, and `dateSymbols` is null.
```dart
  /// For performance, keep the zero digit available.
  String get localeZero => _localeZero == null
      ? _localeZero = useNativeDigits ? dateSymbols.ZERODIGIT ?? '0' : '0'
      : _localeZero;
```

**Comment by VladyslavBondarenko** [comment] 2020-07-15 15:05
@liudonghua123 
What device are you running?
I tried with my Redmi Note 7 Android 9 (API 28) and Android 10 emulator (with Chinese language set too), master `1.20.0-8.0.pre.102`, intl 0.16.1, but couldn't reproduce the exception

**Comment by liudonghua123** [comment] 2020-07-15 15:22
@VladyslavBondarenko 
Did you executed some code like `initializeDateFormatting('zh_CN', null);`?
I will try to test on other devices and reply here later.

**Comment by VladyslavBondarenko** [comment] 2020-07-16 09:32
@liudonghua123 
Yes I tried with and without `initializeDateFormatting('zh_CN', null);` or `en_US`

<details>
 <summary>even like this</summary>

```
import 'package:flutter/material.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    super.initState();
    initializeDateFormatting('zh_CN', null).then((_) {
      DateFormat dateFormat = DateFormat('yyyy-MM-dd HH:mm:ss');
      print(dateFormat.format(DateTime.now()));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold();
  }
}
```

</details>

and I always have correct result `I/flutter (29046): 2020-07-16 12:30:32`

**Comment by darshankawar** [comment] 2020-09-02 09:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by pal** [comment] 2020-10-13 19:34
Did you get this sorted @liudonghua123? I run into the same problem here...

**Comment by liudonghua123** [comment] 2020-10-14 07:47
I have rewrote the code, and I can't reproduce the issue now. It's a pity. 😭

**Comment by darshankawar** [comment] 2020-10-14 07:52
Given @liudonghua123 last message, I am closing this as non-actionable.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of flutter doctor -v.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-10-14 07:52 UTC
