### ISSUE TITLE
Add roadmap issue for 2021, goals to be achieved.

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#71367] opened 2020-11-29 09:42 UTC
I think having a roadmap for some time span such as a whole year or whatever is good for the team would be great! and it should be pinned so people have an idea about what will be happening and what is the prioritized tasks.

```
For 2021 we would like to have web shipped to stable and all desktops shipped to beta and maybe macOS to stable also.
```
The above is just a tiny example.

maybe like the fireflutter roadmap: [https://github.com/FirebaseExtended/flutterfire/issues/2582](https://github.com/FirebaseExtended/flutterfire/issues/2582)

**Comment by iapicca** [comment] 2020-11-29 10:16
I agree with @YazeedAlKhalaf 

I really like the idea of having a better idea of what  new feature / fixes are coming;
maybe a whole year is a long time and of course estimated time is always flexible
(`Elon Musk` style, not `cyberpunk 2077` style!)
but I'd be happy to see `what is coming next` and `in what direction flutter is heading`

**Comment by stuartmorgan** [comment] 2020-11-29 23:15
There is already a high-level yearly roadmap; it's [on the wiki](https://github.com/flutter/flutter/wiki/Roadmap).

**Comment by YazeedAlKhalaf** [comment] 2020-11-30 06:14
Yup, I saw it but it is so vague, If the team could create an issue for the roadmap, maybe every 3 months one roadmap, the roadmap should contain goals, specific ones, and issues related to getting to that goal. it should be limited to only owners so that it does not transform into a mess there.

**Comment by iapicca** [comment] 2020-11-30 08:13
I think @YazeedAlKhalaf has a point here,
the current [road map](https://github.com/flutter/flutter/wiki/Roadmap) is quite generic,
something more granular would be great.

Maybe should be re-titled as "improve road map" or something along this line
since it already exists

**Comment by pedromassangocode** [comment] 2020-11-30 08:43
From few months now working with Flutter issues I was able to notice that the priority of issues in this repository is not constant, it may vary for time to time. I mean that Flutter may focus on improving Windows support today and next month focus on  improving Linux. Having an issue to track roadmap does not seems valid because currently we can see what issues belongs to which goal by filtering issues by **Milestones**.

### Filter by Milestones
![Screen Shot 2020-11-30 at 09 33 20](https://user-images.githubusercontent.com/67424416/100586234-1f61ae80-32ef-11eb-860d-42068ef5b046.png)

### For more advanced search you can filter by project as well
![Screen Shot 2020-11-30 at 09 40 51](https://user-images.githubusercontent.com/67424416/100586895-26d58780-32f0-11eb-80eb-f5342638539c.png)

**Comment by YazeedAlKhalaf** [comment] 2020-11-30 08:54
What I mean is there is no real plan or measurable goal. If there is an issue where people can look at and know what issues to fulfill would be great

**Comment by pedromassangocode** [comment] 2020-11-30 09:46
Issues are added to specific Milestones, meaning that the issue is supposed to be fixed by that Milestone. By filtering by Milestone you will get all issues related to a specific plan.

**Comment by iapicca** [comment] 2020-11-30 10:08
@pedromassangocode 
I think that @YazeedAlKhalaf is trying to make the point 
that a more transparent and granular road map 
might help developer to choose how to invest their time and resources

given that both a [road map](https://github.com/flutter/flutter/wiki/Roadmap) and [milestones](https://github.com/flutter/flutter/milestones) exist
I personally see a possible improvement of one or both as a reasonable request

`milestones` for example appear to be limited to a [3 month projection ](https://user-images.githubusercontent.com/45637986/100595746-01eb0f80-3304-11eb-9d14-863723f80f9d.png) 
and in my personal opinion `road map` could be more detailed

maybe the title of the issue could be misleading, 
but I can easily agree with a request like `provide a more detailed road map for 2021`

**Comment by pedromassangocode** [comment] 2020-11-30 12:26
Will leave this for @stuartmorgan or Hixie to decide.

**Comment by stuartmorgan** [comment] 2020-11-30 19:07
> Maybe should be re-titled as "improve road map" or something along this line
> since it already exists

The suggested example text of what the 2021 year-long roadmap should say is roughly the level of granularity that's there now. (It's less detailed, in fact.) Maybe a clearer example of what is being suggested would help?

> that a more transparent and granular road map

The more granular a year-long roadmap is though, the less accurate it will be. The granular roadmap is the prioritized issue tracker, but it doesn't have a year's worth of dates because they would end up being wrong.

> might help developer to choose how to invest their time and resources

Giving guidance to developers on how they should invest time and resources is exactly what priorities are for though.

> Will leave this for @stuartmorgan or Hixie to decide.

It's not my call, I just saw the issue go by and wanted to point out that what it appeared to be asking for (a very high-level, year-long roadmap) already exists.

**Comment by YazeedAlKhalaf** [comment] 2020-11-30 19:17
An example would be like:

This issue will be a roadmap from Jan_2021 to Mar_2021:
We will be Web Support in the stable channel, to accomplish this we need to solve those issues:
#6444
#6444

**Comment by pedromassangocode** [comment] 2020-12-01 07:55
> This will give developers a better view of what will happen in the near future and also let them know what to help in exactly 🚀. Let's say I want to help in Windows UWP support, I can come to the roadmap issue and see which one I can solve and try to solve it. I believe it will make the development process way faster.

All you said here is now possible with issue filter! And as I said what if the priorities changes? the Roadmap will be updated with new issues, new descriptions and will be useless. From my point of view that is why there is no issues mentioned in the current roadmap. Again, I might be wrong as well :) this is just my point of view.

Cc @Hixie

**Comment by Hixie** [comment] 2020-12-01 08:21
Fundamentally the roadmap on the wiki is as detailed as it's going to get. (I mean, I'll update it for 2021 in the next few weeks, but the level of detail isn't going to get much greater.)

There are several reasons for this.

1. It's extremely difficult to accurately predict what we will actually be doing 12 months from now, or ever 3 months from now, or even, frankly, 3 days from now, because we're an open source project with several hundred contributors who are all following their own (or their employers') priorities.
2. Everyone's priorities may not be widely communicated. For example, I know that Canonical are working on Flutter, and I know they're working on Linux desktop features primarily, but I don't know what precisely they plan to be working on each week of the next year. How can I write a roadmap that accurately reflects what is going to happen if I just don't know?
3. Even if I did know, priorities change. Google Pay uses Flutter. If the Google Pay team runs into some problem with Flutter that they care about, one or more Google engineers working on Flutter will likely drop what they are doing and work on that problem instead. If someone suddenly decides they are going to hire 20 engineers to fix all our Cupertino bugs, then we'll suddenly have a lot more effort spent there than we would otherwise (20 engineers' worth of more effort!).
4. Even if the priorities didn't change and I knew all about all of them, there is an inherent conflict between our marketing team and product managers on the one hand, and our openness and transparency on the other. @timsneath in particular is a big fan of having splashy events to announce new features, and who can blame him, those events are fantastic. But those events don't work if all the splashy stuff was preannounced a year in advance, or three months in advance, so at some level, we have to keep the details somewhat vague just to give the press something new to write about. (And you do want that, because more press means more users means more funding for Flutter to get better faster.) That we are as open as we are is a testament to how much our PMs understand and appreciate open source.
5. Even if I knew what we _wanted_ to do, and could communicate it, that _still_ wouldn't be enough to write a reliable detailed roadmap, because engineering is an unpredictable art. We'll probably say we want to work on https://github.com/flutter/flutter/issues/51752 in 2021, but maybe we'll find that after 9 months of working on it, we discover that fundamentally the problem is harder than we anticipated and it'll actually take us another 3 years.

(There are also some legal issues around giving forward guidance but I won't go into those.)

Given all these problems, I find the 2020 roadmap is actually remarkably detailed and actually remarkably accurate. There's a few things we've not really succeeded at executing on (e.g. our investment in Cupertino wasn't as great as we'd intended), but pretty much everything else listed is exactly what we worked on.

**Comment by stuartmorgan** [comment] 2020-12-01 15:00
On this aspect of the proposal specifically:

> We will be shipping Windows to the beta channel with UWP, to accomplish this we need to solve those issues:

We already use GitHub Projects to do this kind of thing (e.g., there are projects for both UWP and Windows beta). Maintaining a Project is dramatically easier than maintaining a bug list that lives somewhere else, as well as providing more information and utility.

**Comment by pedromassangocode** [comment] 2021-02-16 12:06
[triage]

Given the last two comments, I feel safe to close this issue. Please feel free to reopen it if necessary.
Thank you

**Closed by pedromassangocode** 2021-02-16 12:06 UTC
Labels: documentation, passed first triage, proposal
