### ISSUE TITLE
[web]: error on sqlite persistence 

### ISSUE THREAD

**Issue by eumagnun** [flutter/flutter#48640] opened 2020-01-11 17:38 UTC
I have a simple flutter app. This runs ok on Android, but i'm having some problems when build the app for web.

The error occurs when I try to perform an action that results in persistence on a local sqlite base.

```
errors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:435:18
state.down
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:435)
    at _engine.PointerAdapter.new.[_convertEventToPointerData] (pointer_binding.dart:366)
    at pointer_binding.dart:334
    at HTMLElement.<anonymous> (pointer_binding.dart:183)
DartError @ errors.dart:147
throw_ @ errors.dart:196
assertFailed @ errors.dart:26
convert @ pointer_converter.dart:435
[_convertEventToPointerData] @ pointer_binding.dart:366
(anonymous) @ pointer_binding.dart:334
(anonymous) @ pointer_binding.dart:183
```

**Comment by jonahwilliams** [comment] 2020-01-12 23:50
The error message you've posted is a duplicate of https://github.com/flutter/flutter/issues/46793 .

Consider filling a new issue with the template filled out, including the output of flutter doctor -v as well as detailed steps to reproduce (like sample code).

**Closed by jonahwilliams** 2020-01-12 23:50 UTC
