### ISSUE TITLE
Connecting to the VM Service is taking longer than expected...

### ISSUE THREAD

**Issue by njugunapm233** [flutter/flutter#77802] opened 2021-03-10 13:07 UTC

**Comment by TahaTesser** [comment] 2021-03-10 14:36
Hi @njugunapm233 
Can you please provide more details? Where the issue is occurring? Which IDE or terminal?
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2021-04-07 12:41
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-07 12:41 UTC
Labels: in triage, waiting for customer response

**Comment by evil123** [comment] 2021-04-11 20:54
flutter run -v
 Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...
If you do NOT see the Flutter application running, it might have crashed. The device logs (e.g. from adb or XCode) might have more details.
If you do see the Flutter application running on the device, try re-running with --host-vmservice-port to use a specific port known to be available.
Exception attempting to connect to the VM Service: SocketException: Connection failed, address = 127.0.0.1, port = 53627
This was attempt #50. Will retry in 0:00:01.600000.
Exception attempting to connect to the VM Service: SocketException: Connection failed, address = 127.0.0.1, port = 53627
This was attempt #100. Will retry in 0:00:01.600000.
Exception attempting to connect to the VM Service: SocketException: Connection failed, address = 127.0.0.1, port = 53627
This was attempt #150. Will retry in 0:00:01.600000.
Exception attempting to connect to the VM Service: SocketException: Connection failed, address = 127.0.0.1, port = 53627
This was attempt #200. Will retry in 0:00:01.600000.
