### ISSUE TITLE
[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] 

### ISSUE THREAD

**Issue by jchenx2** [flutter/flutter#59825] opened 2020-06-19 01:51 UTC
I am running monkey test,this error usually occurs after several hours

log
06-18 01:56:40.268   993   993 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Rect.left' on a null object reference
06-18 01:56:40.268   993   993 E flutter : 	at io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo(AccessibilityBridge.java:634)
06-18 01:56:40.268   993   993 E flutter : 	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:149)
06-18 01:56:40.268   993   993 E flutter : 	at io.flutter.view.AccessibilityBridge.obtainAccessibilityEvent(AccessibilityBridge.java:1562)
06-18 01:56:40.268   993   993 E flutter : 	at io.flutter.view.AccessibilityBridge.sendWindowContentChangeEvent(AccessibilityBridge.java:1544)
06-18 01:56:40.268   993   993 E flutter : 	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1325)
06-18 01:56:40.268   993   993 E flutter : 	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:266)
06-18 01:56:40.268   993   993 E flutter : 	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:428)
06-18 01:56:40.268   993   993 E flutter : 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-18 01:56:40.268   993   993 E flutter : 	at android.os.MessageQueue.next(MessageQueue.java:323)
06-18 01:56:40.268   993   993 E flutter : 	at android.os.Looper.loop(Looper.java:136)
06-18 01:56:40.268   993   993 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:6121)
06-18 01:56:40.268   993   993 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
06-18 01:56:40.268   993   993 E flutter : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-18 01:56:40.268   993   993 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-18 01:56:40.268   993   993 E flutter : 
06-18 01:56:40.268   993   993 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(95)] Check failed: CheckException(env). 
06-18 01:56:40.268   993   993 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 993 (m.jci.xlauncher)
06-18 01:56:40.270   229   229 W         : debuggerd: handling request: pid=993 uid=1000 gid=1000 tid=993
06-18 01:56:40.322 25808 25808 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-18 01:56:40.322 25808 25808 F DEBUG   : Build fingerprint: 'jci/azalea/azalea:7.1.2/N2G47H/230:userdebug/test-keys'
06-18 01:56:40.322 25808 25808 F DEBUG   : Revision: '0'
06-18 01:56:40.322 25808 25808 F DEBUG   : ABI: 'arm'
06-18 01:56:40.322 25808 25808 F DEBUG   : pid: 993, tid: 993, name: m.jci.xlauncher  >>> com.jci.xlauncher <<<
06-18 01:56:40.323 25808 25808 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-18 01:56:40.327 25808 25808 F DEBUG   : Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(95)] Check failed: CheckException(env). 
06-18 01:56:40.327 25808 25808 F DEBUG   : '
06-18 01:56:40.327 25808 25808 F DEBUG   :     r0 00000000  r1 000003e1  r2 00000006  r3 00000008
06-18 01:56:40.327 25808 25808 F DEBUG   :     r4 aac7a58c  r5 00000006  r6 aac7a534  r7 0000010c
06-18 01:56:40.327 25808 25808 F DEBUG   :     r8 ffffffff  r9 00000104  sl 88cebc5c  fp ffffffff
06-18 01:56:40.327 25808 25808 F DEBUG   :     ip 0000000b  sp be81aab0  lr a83d95a7  pc a83dbe28  cpsr 200f0010
06-18 01:56:40.338 25808 25808 F DEBUG   : 
06-18 01:56:40.338 25808 25808 F DEBUG   : backtrace:
06-18 01:56:40.338 25808 25808 F DEBUG   :     #00 pc 00049e28  /system/lib/libc.so (tgkill+12)
06-18 01:56:40.338 25808 25808 F DEBUG   :     #01 pc 000475a3  /system/lib/libc.so (pthread_kill+34)
06-18 01:56:40.338 25808 25808 F DEBUG   :     #02 pc 0001d7f5  /system/lib/libc.so (raise+10)
06-18 01:56:40.339 25808 25808 F DEBUG   :     #03 pc 00019331  /system/lib/libc.so (__libc_android_abort+34)
06-18 01:56:40.339 25808 25808 F DEBUG   :     #04 pc 000172e8  /system/lib/libc.so (abort+4)
06-18 01:56:40.339 25808 25808 F DEBUG   :     #05 pc 00023a13  /system/priv-app/XLauncher/XLauncher.apk (offset 0x8e2000)

flutter doctor -v
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.17.3 at C:\flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

**Comment by TahaTesser** [comment] 2020-06-19 11:36
Hi @jchenx2 
Looks Flutter is incompatible with Android Monkey Tests 
Closing as duplicate of https://github.com/flutter/flutter/issues/30617

**Closed by TahaTesser** 2020-06-19 11:36 UTC
