### ISSUE TITLE
Testing plugin in example project.

### ISSUE THREAD

**Issue by hyochan** [flutter/flutter#21172] opened 2018-08-29 16:54 UTC
Hi. Today, I tried to work on making test codes for my plugin and I can't make the call to plugin methods in test code. Is there any guideline make test code for plugins?

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_sound/flutter_sound.dart';

import 'package:flutter_sound_example/main.dart';

void main() {
  test('startRecorder', () async {
    FlutterSound flutterSound = new FlutterSound();
    String path = await flutterSound.startRecorder(null);
    print('path: $path');
  });
}

```

Error code below.
```
Exception: MissingPluginException(No implementation found for method startRecorder on channel flutter_sound)
  package:flutter_sound/flutter_sound.dart 100:7  FlutterSound.startRecorder
  ===== asynchronous gap ===========================
  dart:async                                      _AsyncAwaitCompleter.completeError
  package:flutter_sound/flutter_sound.dart        FlutterSound.startRecorder
  ===== asynchronous gap ===========================
  dart:async                                      _asyncErrorWrapperHelper
  package:flutter_sound/flutter_sound.dart        FlutterSound.startRecorder
  test/widget_test.dart 28:38                     main.<fn>
```

flutter doctor.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by dooboolab** [comment] 2018-08-29 17:33
Also, tried mocking.

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/services.dart';

import 'package:flutter_sound_example/main.dart';

void main() {
  final List<MethodCall> log = <MethodCall>[];
  MethodChannel channel = const MethodChannel('plugins.flutter_sound/flutter_sound');
  channel.setMockMethodCallHandler((MethodCall methodCall) async {
    log.add(methodCall);
  });

  test('Audio Recorder', () async {
    expect(log, equals(<MethodCall>[new MethodCall('startRecorder', "")]));
  });
}
```

Output
```
flutter test ./test/widget_test.dart
00:04 +1 -1: Audio Recorder [E]                                                                                                                                                                                            
  Expected: [MethodCall:MethodCall(startRecorder, )]
    Actual: []
     Which: shorter than expected at location [0]
  
  package:test                                        expect
  package:flutter_test/src/widget_tester.dart 153:16  expect
  test/widget_test.dart 35:5                          main.<fn>
  ===== asynchronous gap ===========================
  dart:async                                          _AsyncAwaitCompleter.completeError
  test/widget_test.dart                               main.<fn>
  
00:04 +1 -1: Some tests failed.    
```

**Comment by zoechi** [comment] 2019-01-23 16:36
See also https://github.com/flutter/flutter/issues/24097#issuecomment-452326031

Duplicate of #10824

**Closed by zoechi** 2019-01-23 16:36 UTC
Labels: a: tests, p: framework
