### ISSUE TITLE
Regression in multi_widget_construction_perf__e2e_summary benchmarls

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#68620] opened 2020-10-20 15:55 UTC
See https://flutter-flutter-perf.skia.org/e/?begin=1602102124&end=1603169996&keys=Xa6ab3890c3982db78aadaec0616a0db6&requestType=0&xbaroffset=22068.

Was previously bimodal, with the predominant mode lower. Now it's clearly unimodal, with the higher value. Probably worth investigating, not a P0.

This affects all of 
`average_frame_rasterizer_time_millis90th_percentile_frame_build_time_millis`, `90th_percentile_frame_rasterizer_time_millis`, and `average_frame_build_time_millis`.

Maybe commit https://github.com/flutter/flutter/pull/68424? It started to climb on the previous commit, but that doesn't seem relevant.

**Comment by zanderso** [comment] 2020-10-20 16:01
https://github.com/flutter/flutter/pull/67594 Looks like it could be related as well. @CareF @liyuqian

**Comment by CareF** [comment] 2020-10-20 17:25
#67594 introduces #64780 to all macrobenchmark for consistency, including `multi_widget_construction_perf__e2e_summary`. That might be the reason but I don't have a local MOTO G4 to really see the time distribution.

**Comment by liyuqian** [comment] 2020-10-20 18:56
Confirmed that #67594 caused this regression because the added delay changed the frames that we measured and their frame time distributions. Specifically, later frames are slower to build than earlier frames as shown in the screenshot below. I'm closing this issue as there's no actual performance regression.

<img width="881" alt="Screen Shot 2020-10-20 at 11 55 07 AM" src="https://user-images.githubusercontent.com/22987568/96631478-3c0bcf00-12cb-11eb-9d6c-5b2e19ebde4b.png">

**Closed** 2020-10-20 18:56 UTC
Labels: P2, engine, perf: speed, severe: performance, severe: regression, team: benchmark, team: bimodal benchmark
