### ISSUE TITLE
Android SDK file not found: ... aapt. ?? What is aapt file where is it ..

### ISSUE THREAD

**Issue by sandho** [flutter/flutter#57811] opened 2020-05-22 16:09 UTC
```
C:\Users\hi>flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.778], locale en-IN)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (10 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\hi\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\hi\AppData\Local\Android\Sdk
    X Android SDK file not found: C:\Users\hi\AppData\Local\Android\sdk\build-tools\29.0.2\aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\hi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by Niranjan-10** [comment] 2020-05-25 06:42
[https://github.com/flutter/flutter/issues/51670#](url)
Here is the solution

**Comment by Niranjan-10** [comment] 2020-05-25 06:43
[https://github.com/flutter/flutter/issues/51670](url)

**Comment by Niranjan-10** [comment] 2020-05-25 06:47
[](https://github.com/flutter/flutter/issues/51712#issuecomment-600318840)

**Comment by Niranjan-10** [comment] 2020-05-25 06:48
[https://github.com/flutter/flutter/issues/51712#issuecomment-600318840](url)

**Comment by Niranjan-10** [comment] 2020-05-25 06:49
Duplicate of #51712

**Comment by iapicca** [comment] 2020-05-25 07:29
Hi @sandho 
I see there's an open [issue](https://github.com/flutter/flutter/issues/51712) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-05-25 07:29 UTC
