### ISSUE TITLE
The flutter tool cannot access the file or directory. Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

### ISSUE THREAD

**Issue by rajdip0** [flutter/flutter#115571] opened 2022-11-17 17:23 UTC
Exception: The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

flutter doctor -v

[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-arm,
    locale en-IN)
    • Flutter version 3.3.8 on channel stable at
      /Users/rajdip/Documents/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (9 days ago), 2022-11-09 12:09:26
      +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK
    version 32.1.0-rc1)
    • Android SDK at /Users/rajdip/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/rajdip/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • Redmi Note 8 (mobile)                • 133efded      •
      android-arm64  • Android 11 (API 30)
    • Android SDK built for arm64 (mobile) • emulator-5554 •
      android-arm64  • Android 9 (API 28) (emulator)
    • macOS (desktop)                      • macos         •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)                         • chrome        •
      web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment] 2022-11-18 06:49
Based on the error, closing this as duplicate of 
https://github.com/flutter/flutter/issues/70216. You may upvote original issue for team's attention.

**Closed by darshankawar** 2022-11-18 06:49 UTC
Labels: in triage
