### ISSUE TITLE
[Linux] Cannot receive receive more pointers on touchscreen

### ISSUE THREAD

**Issue by WeicongLi124** [flutter/flutter#133239] opened 2023-08-24 07:37 UTC
### Steps to reproduce

Run the demo on the Linux touchscreen machine;
1. One finger test:
    1) Run the demo on the Linux touchscreen machine;
    2) Touch on the screen and up;
2. Two fingers test:
    1) On the premise that one finger has already touched;
    2) Touch the screen with the second finger;
3. Three fingers test:
    1) On the premise that two fingers has already touched;
    2) Touch the screen with the third finger;

### Expected results

1. The first test expected results:
Successfully received all events, all events type are touch;

2. The second test expected results:
Successfully received all events, received the new down and up, all events type are touch;

3. The third test expected results:
Successfully received all events, received the new down and up, all events type are touch;

### Actual results

1. The first test actual results:
Successfully received all events, but all event types are mouse;

2. The second test actual results:
No new down event received, and there was no up event when the second finger was release;

3. The third test actual results:
Received the zoom events: ZoomStart, ZoomUpdate, ZoomEnd, and all event types are trackpad;

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Listener(
        onPointerDown: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerDown:${event}  kind:${event.kind}");
        },
        onPointerMove: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerMove:${event}  kind:${event.kind}");
        },
        onPointerUp: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerUp:${event}  kind:${event.kind}");
        },
        onPointerCancel: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerCancel:${event}  kind:${event.kind}");
        },
        onPointerPanZoomStart: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerPanZoomStart:${event}  kind:${event.kind}");
        },
        // TODO onPointerSignal 独立分发
        onPointerSignal: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerSignal:${event}  kind:${event.kind}");
        },
        onPointerHover: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerHover:${event}  kind:${event.kind}");
        },
        onPointerPanZoomEnd: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerPanZoomEnd:${event}  kind:${event.kind}");
        },
        onPointerPanZoomUpdate: (PointerEvent event) {
          debugPrint(
              "flutter-demo  onPointerPanZoomUpdate:${event}  kind:${event.kind}");
        },
        child: Container(
          color: Colors.yellow,
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Logs

<details><summary>Logs</summary>

1. The first test logs
```console
flutter: flutter-demo  onPointerDown:_TransformedPointerDownEvent#53ba5(position: Offset(208.1, 251.6))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#d62a9(position: Offset(208.6, 254.0))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#ffc41(position: Offset(211.0, 257.9))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#86f91(position: Offset(212.8, 263.0))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#ac328(position: Offset(215.2, 268.5))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#bd1bc(position: Offset(217.1, 275.9))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#5eee4(position: Offset(218.5, 282.2))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#407b4(position: Offset(219.9, 288.5))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#c94b3(position: Offset(221.3, 294.9))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#da376(position: Offset(221.3, 301.4))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#3fb59(position: Offset(222.7, 307.0))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#669cb(position: Offset(222.7, 311.7))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerMove:_TransformedPointerMoveEvent#7171a(position: Offset(222.7, 316.5))  kind:PointerDeviceKind.mouse
flutter: flutter-demo  onPointerUp:_TransformedPointerUpEvent#c31b4(position: Offset(222.7, 316.5))  kind:PointerDeviceKind.mouse
```

2. The second test logs
```console
no logs
```

3. The third test logs
```console
flutter: flutter-demo  onPointerPanZoomStart:_TransformedPointerPanZoomStartEvent#b2e4a(position: Offset(197.1, 299.1))  kind:PointerDeviceKind.trackpad
flutter: flutter-demo  onPointerPanZoomUpdate:_TransformedPointerPanZoomUpdateEvent#506cf(position: Offset(197.1, 299.1))  kind:PointerDeviceKind.trackpad
flutter: flutter-demo  onPointerPanZoomUpdate:_TransformedPointerPanZoomUpdateEvent#ffaba(position: Offset(197.1, 299.1))  kind:PointerDeviceKind.trackpad
flutter: flutter-demo  onPointerPanZoomUpdate:_TransformedPointerPanZoomUpdateEvent#b5e52(position: Offset(197.1, 299.1))  kind:PointerDeviceKind.trackpad
flutter: flutter-demo  onPointerPanZoomUpdate:_TransformedPointerPanZoomUpdateEvent#e6912(position: Offset(197.1, 299.1))  kind:PointerDeviceKind.trackpad
flutter: flutter-demo  onPointerPanZoomUpdate:_TransformedPointerPanZoomUpdateEvent#881a8(position: Offset(197.1, 299.1))  kind:PointerDeviceKind.trackpad
flutter: flutter-demo  onPointerPanZoomUpdate:_TransformedPointerPanZoomUpdateEvent#874b6(position: Offset(197.1, 299.1))  kind:PointerDeviceKind.trackpad
flutter: flutter-demo  onPointerPanZoomEnd:_TransformedPointerPanZoomEndEvent#9a650(position: Offset(197.1, 299.1))  kind:PointerDeviceKind.trackpad
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on BrilliaOS 5.10.179.ft, locale zh_CN.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[!] Network resources                                        
    ✗ A cryptographic error occurred while checking "https://pub.dev/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your computer.
    ✗ A network error occurred while checking "https://maven.google.com/": Connection timed out
    ✗ An HTTP error occurred while checking "https://github.com/": Connection closed before full header was received

! Doctor found issues in 3 categories.
```

</details>

**Comment by WeicongLi124** [comment] 2023-08-24 07:40
When I test on a touch screen device on Windows, all fingers can receive independent down and up events, and all events kind are touch; when I tested touchscreen devices on Ubuntu and Debian Linux systems, their events kind were both mouse or trackpad, and cannot recognize multiple fingers individually

**Comment by darshankawar** [comment] 2023-08-24 10:10
@WeicongLi124 
Can you take a look at below related issues and a comment and check if they help to know why touch events on a touchscreen device running on Linux may not be working as expected ?

https://github.com/flutter/flutter/issues/90366
https://github.com/flutter/flutter/issues/52202
https://github.com/flutter/flutter/issues/78232#issuecomment-819157114

**Comment by WeicongLi124** [comment] 2023-08-24 10:10
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WeicongLi124** [comment] 2023-08-25 02:29
> @WeicongLi124 Can you take a look at below related issues and a comment and check if they help to know why touch events on a touchscreen device running on Linux may not be working as expected ?
> 
> #90366 #52202 [#78232 (comment)](https://github.com/flutter/flutter/issues/78232#issuecomment-819157114)

Yes, I have already read them.
Sadly, it didn't help me. I see that these issues are still open. So, I'm wondering if Flutter has not yet implemented touch adaptation for Linux.
I am developing a touch handwriting software that implements the function of double finger movement and scaling. It can be triggered on Windows and Android, but not on Linux.
The issue was discovered through a simple demo test.

**Comment by darshankawar** [comment] 2023-08-25 05:48
Thanks for the update. We don't have a Linux touchscreen machine to verify properly, but based on the report, keeping the issue open for team's input and attention. Most likely, it is similar / related to the links I shared [earlier](https://github.com/flutter/flutter/issues/133239#issuecomment-1691398285).

**Comment by WeicongLi124** [comment] 2023-08-25 06:19
> Thanks for the update. We don't have a Linux touchscreen machine to verify properly, but based on the report, keeping the issue open for team's input and attention. Most likely, it is similar / related to the links I shared [earlier](https://github.com/flutter/flutter/issues/133239#issuecomment-1691398285).

Got it, no thanks. May I ask if the team has any plans to address these issue in the near future, or when are they planning to address it.

**Comment by gspencergoog** [comment] 2023-08-31 18:10
Closing as a duplicate of #52202 (Desktop Triage)

**Closed by gspencergoog** 2023-08-31 18:10 UTC
Labels: framework, f: gestures, platform-linux, a: desktop, team-desktop
