### ISSUE TITLE
Date picker layout exceptions

### ISSUE THREAD

**Issue by DasserBasyouni** [flutter/flutter#71363] opened 2020-11-29 06:53 UTC
DatePickerEntryMode.input layout is being cut on a flutter web project and there is no way to disable an EntryMode

Date Picker
![image](https://user-images.githubusercontent.com/12116538/100535227-b95a2600-321f-11eb-80da-2c4627c275f5.png)
![image](https://user-images.githubusercontent.com/12116538/100535234-c414bb00-321f-11eb-8ab1-f505a8e78caf.png)

Time Picker
![image](https://user-images.githubusercontent.com/12116538/100535237-cecf5000-321f-11eb-9e4a-231466d8e501.png)
![image](https://user-images.githubusercontent.com/12116538/100535245-d8f14e80-321f-11eb-95b9-5db81f248ae5.png)

Code to produce:

    final DateTime pickedDate = await showDatePicker(
          context: context,
          initialDate: DateTime.now(),
          initialEntryMode: DatePickerEntryMode.input,
          initialDatePickerMode: DatePickerMode.day,
          firstDate: DateTime.now(),
          lastDate: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 30));
   
    final TimeOfDay pickedTime = await showTimePicker(
        context: context,
        initialTime: TimeOfDay.now(),
      );

Things might be related: I'm using 
- `easy_localization: ^2.3.3`
- `sdk: ">=2.7.0 <3.0.0"`
- SDK `2.11.0-213.1.beta` in a web flutter project (I'm using an old version to be able to use `setUrlStrategy(UrlStrategy)` that have been removed and added later on a master build, surely unstable one)

**Update**
`flutter doctor -v` results

    [√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 1.23.0-18.1.pre at D:\Tools\SDK\flutter_1.23.0-18.1.pre
    • Framework revision 198df796aa (6 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

    [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Tools\SDK\android
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Program\Android Studio Dev\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

    [√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

    [√] Android Studio (version 4.1)
    • Android Studio at D:\Program\Android Studio Dev
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

    [√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

    [√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

    [√] VS Code (version 1.51.1)
    • VS Code at C:\Users\dasse\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

    [√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.69

    ! Doctor found issues in 1 category.

**Comment by iapicca** [comment] 2020-11-29 08:26
@DasserBasyouni 
can you provide your `flutter doctor -v` your `flutter run -v`
and most importantly a minimal reproducible code sample 
that does not depend on 3rd party packages (like [easy_localization](https://pub.dev/packages/easy_localization))

**Comment by DasserBasyouni** [comment] 2020-11-29 09:07
@iapicca 
Sure, I have added `flutter doctor -v` results
and produce sample is calling the previously added code in FlatButton, [here is the full class code of the button if it would be helpful](https://gist.github.com/DasserBasyouni/68464e13bb8dd80db058afd9dab549b4)
and thanks for your help

**Comment by iapicca** [comment] 2020-11-29 09:56
@DasserBasyouni 
thanks for the link, but the issue might depend from the 3rd party package used in your code
can you provide a minimal code sample that does not relies only 3rd party dependencies

**Comment by pedromassangocode** [comment] 2020-11-30 10:51
Hi @DasserBasyouni 
Please provide what was asked in the comment above!

**Comment by DasserBasyouni** [comment] 2020-11-30 10:59
@pedromassangocode @iapicca, sure I'm just making a nice empty app for testing that and give you the needed feedback, in a couple of hours

**Comment by DasserBasyouni** [comment] 2020-11-30 13:12
@pedromassangocode @iapicca, I have tested [the same class that picks date and time](https://gist.github.com/DasserBasyouni/68464e13bb8dd80db058afd9dab549b4) on a new project, that gave me the picker without being cut.

The new project without any dependencies
![2en](https://user-images.githubusercontent.com/12116538/100613598-7aaa9580-331d-11eb-827f-87ee94b09754.PNG)
![1en](https://user-images.githubusercontent.com/12116538/100613601-7bdbc280-331d-11eb-8b30-eeff3abf0af2.PNG)

The new project with adding `easy_localization` and locale property in the date picker 
![fl1](https://user-images.githubusercontent.com/12116538/100613581-75e5e180-331d-11eb-8aaa-277e0b9ee1e4.PNG)

I notice that with `easy_localization` the picker popup was to be in English not Arabic even when defining Arabic as app default in `easy_localization`. and in my main project the picker popup is displayed in Arabic even when I'm not setting the `locale` of the `showDatePicker`.
I tried to set the locale in English in the main project the language is displayed in English but it still cut as the Arabic version

Is there is any hints can help on knowing what 3rd party dependencies causing that? or an option to turn off any effects on popup or even disabling `DatePickerEntryMode.input`?

**Comment by iapicca** [comment] 2020-11-30 13:47
@DasserBasyouni 

> [...]I have tested [the same class that picks date and time](https://gist.github.com/DasserBasyouni/68464e13bb8dd80db058afd9dab549b4) on a new project, that gave me the picker without being cut.
> The new project without any dependencies [...]


your link points at the same project from before 

> [...] [here is the full class code of the button if it would be helpful](https://gist.github.com/DasserBasyouni/68464e13bb8dd80db058afd9dab549b4)

(that depends on easy_localization](https://pub.dev/packages/easy_localization))
can you provide the `new project without any dependencies` you are mentioning

**Comment by pedromassangocode** [comment] 2020-11-30 14:14
Hi @DasserBasyouni 
As said before, provide a code without third-party dependcies!

**Comment by DasserBasyouni** [comment] 2020-11-30 14:22
@iapicca

> your link points at the same project from before

Yes, I mean I have tired that class with a newly created app it works without any problem, just referencing the file to remember it. 

> (that depends on easy_localization](https://pub.dev/packages/easy_localization))

Might be it, but the newly created app worked normally with the dependency, here is my [pubspec.yaml](https://gist.github.com/DasserBasyouni/02c611c7aacec0f67f9f63239909df48) to see my full dependencies if that helps

> can you provide the `new project without any dependencies` you are mentioning

Sure, [here it is on the master branch](https://github.com/DasserBasyouni/test_case_date_picker) and [the version with `easy_localization` dependency branch](https://github.com/DasserBasyouni/test_case_date_picker/tree/dependency)

**Comment by iapicca** [comment] 2020-11-30 15:37
@DasserBasyouni 

> ![1en](https://user-images.githubusercontent.com/12116538/100613601-7bdbc280-331d-11eb-8b30-eeff3abf0af2.PNG)

sorry, maybe I misunderstood, are you saying that it works correctly without 3rd party package?

**Comment by DasserBasyouni** [comment] 2020-11-30 17:11
@iapicca, Yes it is even with `easy_localization` it still works on the new project only, so it might be other dependencies issue

**Comment by HansMuller** [comment] 2020-11-30 19:41
CC @darrenaustin @shihaohong

**Comment by pedromassangocode** [comment] 2020-12-01 08:35
Hi @DasserBasyouni 
This may happen only with the locale you are using. Does the code bellow reproduces the issue?

Note: this is the same as your code in the main branch, I've just added `locale: Locale('ar')` into the showDatePicker() method.

<details><summary>pubspec.yaml</summary>

```
  intl:
  flutter_localizations:
    sdk: flutter
```
</details>

<details><summary>Code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
  /*runApp(
    EasyLocalization(
        supportedLocales: [Locale('en'), Locale('ar')],
        path: 'assets/translations', // <-- change patch to your
        fallbackLocale: Locale('ar'),
        child: MyApp()),
  );*/
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: [
        DefaultMaterialLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
      ],
      //supportedLocales: context.supportedLocales,
      //locale: context.locale,
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ProjectPickerButton(
              text: 'test',
              type: PickerButtonType.dateTime,
            ),
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

enum PickerButtonType { date, time, dateTime, uploadImage }

class ProjectPickerButton extends StatefulWidget {
  final String text;
  final ValueChanged<dynamic> onDateTimePicked;
  final PickerButtonType type;

  ProjectPickerButton({@required this.text, @required this.type, this.onDateTimePicked, LocalKey key})
      : super(key: key);

  @override
  _ProjectPickerButtonState createState() => _ProjectPickerButtonState();
}

class _ProjectPickerButtonState extends State<ProjectPickerButton> {
  String pickedDateTimeStr;

  @override
  Widget build(BuildContext context) {
    IconData iconData;
    switch (widget.type) {
      case PickerButtonType.dateTime:
        iconData = Icons.date_range;
        break;
      case PickerButtonType.uploadImage:
        iconData = Icons.upload_rounded;
        break;
      case PickerButtonType.date:
        iconData = Icons.calendar_today;
        break;
      case PickerButtonType.time:
        iconData = Icons.timer_rounded;
        break;
    }

    return FlatButton(
      padding: EdgeInsets.only(top: 26, bottom: 26),
      hoverColor: Colors.red.withOpacity(.3),
      onPressed: widget.type == PickerButtonType.uploadImage
          ? null
          : widget.type == PickerButtonType.date
          ? getDateOnPress()
          : widget.type == PickerButtonType.time
          ? getTimeOnPress()
          : widget.type == PickerButtonType.dateTime
          ? getDateTimeOnPress()
          : null,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
      color: Colors.white,
      child: Row(
        children: [
          SizedBox(
            width: 10,
          ),
          Expanded(
            child: Material(
                color: Colors.transparent,
                child: Text(
                  pickedDateTimeStr == null ? widget.text : pickedDateTimeStr,
                  style: TextStyle(color: Colors.black54, fontWeight: FontWeight.bold),
                  textAlign: TextAlign.center,
                ) //.tr(),
            ),
          ),
          SizedBox(
            width: 10,
          ),
          Icon(
            iconData,
            color: Colors.blue,
          ),
          SizedBox(
            width: 10,
          ),
        ],
      ),
    );
  }

  getDateOnPress() {
    return () async {
      DateTime pickedDate = await pickDate();

      if (pickedDate == null) {
        return;
      } else {
        setState(() {
          //pickedDateTimeStr = '${DateFormat.yMd().format(pickedDate)}';
        });
        widget.onDateTimePicked.call(pickedDate);
      }
    };
  }

  getTimeOnPress() {
    return () async {
      TimeOfDay pickedTime = await pickTime();

      if (pickedTime == null) {
        return;
      } else {
        setState(() {
          pickedDateTimeStr = '${pickedTime.format(context)}';
        });
        widget.onDateTimePicked.call(pickedTime);
      }
    };
  }

  getDateTimeOnPress() {
    return () async {
      DateTime pickedDate = await pickDate();

      if (pickedDate == null) {
        //BotToast.showSimpleNotification(title: tr('processIsCanceled'));
        return;
      } else {
        TimeOfDay pickedTime = await pickTime();

        if (pickedTime == null) {
          //BotToast.showSimpleNotification(title: tr('processIsCanceled'));
          return;
        } else {
          DateTime pickedDateTime =
          DateTime(pickedDate.year, pickedDate.month, pickedDate.day, pickedTime.hour, pickedTime.minute);

          setState(() {
            //pickedDateTimeStr = '${DateFormat.yMd().format(pickedDate)} - ${pickedTime.format(context)}';
          });

          widget.onDateTimePicked.call(pickedDateTime);
        }
      }
    };
  }

  Future<DateTime> pickDate() async {
    return await showDatePicker(
        context: context,
        //locale: Locale('ar'),
        initialDate: DateTime.now(),
        initialDatePickerMode: DatePickerMode.day,
        firstDate: DateTime.now(),
        locale: Locale('ar'),
        lastDate: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 30));
  }

  Future<TimeOfDay> pickTime() async {
    return await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );
  }
}
```
</details>

**Comment by DasserBasyouni** [comment] 2020-12-01 08:45
Hi @pedromassangocode 

setting local on the testing case project, I provided before is causing no error
but on main project `locale: Locale('ar')` is causing yes but `locale: Locale('en')` is not only when the selected date is short to be in one line

![2en](https://user-images.githubusercontent.com/12116538/100716923-083fc100-33c2-11eb-95c3-6ad85399aa6f.PNG)
![1en](https://user-images.githubusercontent.com/12116538/100716925-08d85780-33c2-11eb-9759-f79b11c0e698.PNG)
![image](https://user-images.githubusercontent.com/12116538/100717047-36bd9c00-33c2-11eb-8ee3-3e67941665be.png)

**Comment by pedromassangocode** [comment] 2020-12-01 14:04
Hi @DasserBasyouni 
Are you running ton Web?

**Comment by DasserBasyouni** [comment] 2020-12-03 02:01
Hey @pedromassangocode, what do you mean by "ton web", I'm just running on default Google chrome no other modifications in the running commands

**Comment by pedromassangocode** [comment] 2020-12-03 09:24
Hi @DasserBasyouni 
Sorry, I meant "on Web".

I just tested on Web and it is working fine.

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository.
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-03 09:24 UTC
Labels: f: date/time picker, f: material design, framework, in triage

**Comment by DasserBasyouni** [comment] 2020-12-14 00:49
@iapicca @pedromassangocode 
I have been testing it on my free time, founding that bug is happening when using a custom font in the project, [reproduced bug source code](https://github.com/DasserBasyouni/test_case_date_picker/tree/custom-font), searched about font properties in `pubspec.yaml` finding`style` and `weight` that are not affecting the bug.

So, is there is a way to fix it with using the same font or there is a way must do to exclude custom font in picker popup?

**Comment by DasserBasyouni** [comment] 2020-12-20 22:08
Hello, @iapicca @pedromassangocode, should I open a new issue? or provide other details?

**Comment by shihaohong** [comment] 2020-12-21 04:02
Hey @DasserBasyouni, if the issue is related to this one and you think it is a problem with `flutter/flutter`, feel free to re-open the issue, and provide some context on the expected vs actual behavior you're seeing. That way, it's easier for us to identify what we're looking for and if it's a resolvable issue.

Based on some of the comments in the thread, it may be a problem with the third-party package/plugin itself, so double check to see if it's a problem that the framework itself can address. Thanks!
