### ISSUE TITLE
[tool_crash] ProcessException: The directory app/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj)

### ISSUE THREAD

**Issue by harikrushn1412** [flutter/flutter#156933] opened 2024-10-16 04:47 UTC
## Command
```
flutter build ipa -t lib/main.dart --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally with exit code 78:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2024-10-16 10:16:26.873 xcodebuild[39224:1112709] Writing error result bundle to /var/folders/1c/wv8qftxd4qq9ynx9dnh5xhvc0000gn/T/ResultBundle_2024-16-10_10-16-0026.xcresult
xcodebuild: error: The directory /Users/squareinfosoft/StudioProjects/mtv-flutter/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: /usr/bin/arch, OS error code: 78
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:321:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:342:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:452:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/xcode_project.dart:405:36)
<asynchronous suspension>
#5      IosProject._parseHostAppBundleName (package:flutter_tools/src/xcode_project.dart:379:55)
<asynchronous suspension>
#6      IosProject.hostAppBundleName (package:flutter_tools/src/xcode_project.dart:368:35)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:116:39)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutte

**Comment by danagbemava-nc** [comment] 2024-10-16 07:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/78839

**Closed by danagbemava-nc** 2024-10-16 07:14 UTC
Labels: in triage
