### ISSUE TITLE
running ''flutter doctor'' red writing flashes up then window crashes. Cant even get into anything.

### ISSUE THREAD

**Issue by flutternooob** [flutter/flutter#72215] opened 2020-12-12 23:34 UTC
I had thought that I had got this all sorted, but apparently not. I have deleted everything and re downloaded flutter for the fifth time now. I followed al instructions on flutter's website and am still having issues.

when I run flutter doctor it flashes up in red writing saying this( i cant copy and paste as it quickly flashes up and disapears.)

'' The term 'unblock-file' is not recognized as the name of a cmdlet. function, script file, or operable program. check the spelling of the name, or if a path was included, verify that the path is correct and try agai, at line:1 char:13

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by ameysunu** [comment] 2020-12-13 08:08
Check issue [#30657](https://github.com/flutter/flutter/issues/30657)

**Comment by flutternooob** [comment] 2020-12-13 08:28
Thank you I'm looking now.

**Comment by pedromassangocode** [comment] 2020-12-14 10:14
Hi @flutternooob 
Can you please run (making sure you run from your terminal and not from an IDE)
```console
cd <your app folder>
flutter doctor -v
flutter pub upgrade --verbose
``` 
and provide the output.
Thank you

**Comment by flutternooob** [comment] 2020-12-14 20:07
> 
> 
> Hi @flutternooob
> Can you please run (making sure you run from your terminal and not from an IDE)
> 
> ```
> cd <your app folder>
> flutter doctor -v
> flutter pub upgrade --verbose
> ```
> 
> and provide the output.
> Thank you
Hi I just done what you said I opened CND and typed what you said and it still flashed up red and crashed the window it just closed bu itself again. 
I have no idea what t do to fix this.

**Comment by pedromassangocode** [comment] 2020-12-15 08:39
Hi @flutternooob 
Please provide what was asked in https://github.com/flutter/flutter/issues/72215#issuecomment-744335566. If it shows any error then provide that same error.

**Comment by flutternooob** [comment] 2020-12-15 13:22
> Hi @flutternooob 
> 
> Please provide what was asked in https://github.com/flutter/flutter/issues/72215#issuecomment-744335566. If it shows any error then provide that same error.

Hi. I'm really sorry I'm new to coding and not fully understanding what you're asking me could you explain please? Thank you.

**Comment by pedromassangocode** [comment] 2020-12-15 13:54
Hi @flutternooob 
Sorry about that. What you need to do is to copy each line bellow and paste it in the Terminal, after you ran the second and third commands, you should copy and paste the output here is the comments.

```console
cd <your app folder>
flutter doctor -v
flutter pub upgrade --verbose
``` 

Let me know if you still need help with the commands above.
Thank you

**Comment by flutternooob** [comment] 2020-12-15 13:57
> Hi @flutternooob 
> 
> Sorry about that. What you need to do is to copy each line bellow and paste it in the Terminal, after you ran the second and third commands, you should copy and paste the output here is the comments.
> 
> 
> 
> ```console
> 
> cd <your app folder>
> 
> flutter doctor -v
> 
> flutter pub upgrade --verbose
> 
> ``` 
> 
> 
> 
> Let me know if you still need help with the commands above.
> 
> Thank you

No its no worries. Ok I'll try that then. I did do that but i copied and pasted what they commands were. I guess that must've been wrong. I'll do it one line at a time and get back to you. Thanks.

**Comment by flutternooob** [comment] 2020-12-15 19:44
> Hi @flutternooob 
> 
> Sorry about that. What you need to do is to copy each line bellow and paste it in the Terminal, after you ran the second and third commands, you should copy and paste the output here is the comments.
> 
> 
> 
> ```console
> 
> cd <your app folder>
> 
> flutter doctor -v
> 
> flutter pub upgrade --verbose
> 
> ``` 
> 
> 
> 
> Let me know if you still need help with the commands above.
> 
> Thank you

Hi Ive done it in cmd and its still flashing red and crashing. 

Then i done it in flutters console and it just keeps crashing and flashing up red writing from what it says when I originally posted. 

My powershell version is 2.0 I've just found out do you think thats part of the problem? I have windows 7, but I was able to get into andriod studio and could see everything there. Then all of a sudden this happened. Should I update powershell? I tried to do it but that didn't seem to work I'm not sure if I was doing it wrong or not.

**Comment by flutternooob** [comment] 2020-12-15 19:48
> 
> 
> Hi @flutternooob
> Sorry about that. What you need to do is to copy each line bellow and paste it in the Terminal, after you ran the second and third commands, you should copy and paste the output here is the comments.
> 
> ```
> cd <your app folder>
> flutter doctor -v
> flutter pub upgrade --verbose
> ```
> 
> Let me know if you still need help with the commands above.
> Thank you

The '<' operator is reserved for future use.
At line:1 char:5
+ cd < <<<< your app folder>
    + CategoryInfo          : ParserError: (<:OperatorToken) [], ParentC
    + FullyQualifiedErrorId : RedirectionNotSupported

PS C:\Users\hp> flutter doctor -v
Checking Dart SDK version...
The term 'Unblock-File' is not recognized as the name of a cmdlet, funct
e spelling of the name, or if a path was included, verify that the path
At line:1 char:13
+ Unblock-File <<<<  -Path 'C:\Users\hp\Documents\flutter\flutter/bin/in
uments\flutter\flutter/bin/internal/update_dart_sdk.ps1'; exit $LASTEXIT
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) [],
    + FullyQualifiedErrorId : CommandNotFoundException

Flutter requires PowerShell 5.0 or newer.
See https://flutter.dev/docs/get-started/install/windows for more.
Current version is 2.
PS C:\Users\hp> flutter pub upgrade --verbose
Checking Dart SDK version...
The term 'Unblock-File' is not recognized as the name of a cmdlet, funct
e spelling of the name, or if a path was included, verify that the path
At line:1 char:13
+ Unblock-File <<<<  -Path 'C:\Users\hp\Documents\flutter\flutter/bin/in
uments\flutter\flutter/bin/internal/update_dart_sdk.ps1'; exit $LASTEXIT
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) [],
    + FullyQualifiedErrorId : CommandNotFoundException

Flutter requires PowerShell 5.0 or newer.
See https://flutter.dev/docs/get-started/install/windows for more.
Current version is 2.

**Comment by pedromassangocode** [comment] 2020-12-16 07:30
> Flutter requires PowerShell 5.0 or newer.

Looks like this is caused by the lower version of PowerShell that you are using. Please try to upgrade to PowerShell 5 or later and try again.

Closing as this is not an issue with Flutter itself.
Thank you

**Closed by pedromassangocode** 2020-12-16 07:30 UTC
Labels: in triage
