### ISSUE TITLE
Chip with chipPadding fails to render in RenderBox.debugAssertDoesMeetConstraints

### ISSUE THREAD

**Issue by cvolzke4** [flutter/flutter#30081] opened 2019-03-28 02:53 UTC
To reproduce:

```
  Future<void> pumpWidget(WidgetTester tester, Widget widget) {
    return tester.pumpWidget(
      Material(
        child: MaterialApp(
          home: widget,
        ),
      ),
    );
  }

  testWidgets('should render chip', (tester) async {
    await pumpWidget(
      tester,
      Chip(
        label: Text('label'),
// *** Removing this padding fixes the test (!)
        padding: EdgeInsets.only(left: 10, right: 10),
      ),
    );
  }, timeout: Timeout.none);
```

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the RenderPhysicalModel class returned values that violate the
intrinsic protocol contract.
The following failures was detected:
 * getMinIntrinsicWidth(Infinity) returned a larger value (106.0) than
   getMaxIntrinsicWidth(Infinity) (86.0)
 * getMinIntrinsicWidth(600.0) returned a larger value (106.0) than getMaxIntrinsicWidth(600.0)
   (86.0)
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1813:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1823:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1543:17)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1543:65)
#4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:106:7)
#5      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)

**Comment by HansMuller** [comment] 2019-03-28 16:17
This appears to be a duplicate of some known issues. 

Flake: intrinsic dimension methods of the RenderPadding class returned values that violate the intrinsic protocol contract #26319

drawer_test.dart sometimes claims RenderPadding violates the intrinsic protocol contract #19696

**Comment by Hixie** [comment] 2019-05-17 18:04
Dupe of https://github.com/flutter/flutter/issues/19696

**Closed by Hixie** 2019-05-17 18:04 UTC
Labels: f: material design, framework
