### ISSUE TITLE
In App Purchase : pendingCompletePurchase is always true on IOS

### ISSUE THREAD

**Issue by mohsinnaqvi606** [flutter/flutter#134529] opened 2023-09-12 12:48 UTC
### Steps to reproduce

1. Buy a none Consumable
2. Call completePurchase function.
3. Get purchase history

In the response of history **pendingCompletePurchase** will always be true.  
The same code works fine on Android but on IOS it has different behavior.

**Please note I have already called completePurchase function still purchase is pending**

### Expected results

**pendingCompletePurchase : false**

### Actual results

**pendingCompletePurchase : true**

### Code sample

<details><summary>Code sample</summary>

```dart
 late StreamSubscription<dynamic> streamSubscription;
 InAppPurchase iAP = InAppPurchase.instance;
 
  getPurchaseHistory() {
    streamSubscription =
        InAppPurchase.instance.purchaseStream.listen((purchaseList) {
      log('length : ${purchaseList.length}');

      if (purchaseList.length > 0) {
        for (int i = 0; i < purchaseList.length; i++) {
          PurchaseDetails details = purchaseList[i];
          log('******************************** Response ****************************');
          log('purchaseID : ${details.purchaseID}');
          log('status : ${details.status}');
          log('productID : ${details.productID}');
          log('pendingCompletePurchase : ${details.pendingCompletePurchase}');
          log('error : ${details.error}');

          if (details.pendingCompletePurchase) {
             iAP.completePurchase(details).then((value) {});
          }
        }
      } else {
        log('In App not found');
      }
    }, onDone: () {
      print('done');
      streamSubscription.cancel();
    }, onError: (error) {
      print('Error');
    });

   iAP.restorePurchases();
  }
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.19045.3393], locale en-US)
    • Flutter version 3.13.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (4 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ParityZone\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • Infinix X690B (mobile) • 055832508C002250 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3393]
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 116.0.5845.187
    • Edge (web)             • edge             • web-javascript • Microsoft Edge 92.0.902.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-12 13:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98484.

**Closed by danagbemava-nc** 2023-09-12 13:41 UTC
Labels: in triage
