### ISSUE TITLE
example gallary build error

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#25621] opened 2018-12-20 14:14 UTC
Example of gallery build erro on iPhoneX simulator:

```
flutter: The following _CompileTimeError was thrown building Builder(dirty):
flutter: 'package:flutter_gallery/gallery/app.dart': error: line 144 pos 13: lib/gallery/app.dart:144:13:
flutter: Error: The method 'CupertinoTheme' isn't defined for the class '#lib1::_GalleryAppState'.
flutter: Try correcting the name to the name of an existing method, or defining a method named
flutter: 'CupertinoTheme'.
flutter:             CupertinoTheme(
flutter:             ^^^^^^^^^^^^^^
flutter:             CupertinoTheme(
flutter:             ^
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _WidgetsAppState.build.<anonymous closure> (package:flutter/src/widgets/app.dart:1099:25)
flutter: #1      Builder.build (package:flutter/src/widgets/basic.dart:5736:41)
flutter: #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #32     ComponentElement._firs
```

**Comment by zoechi** [comment] 2018-12-20 14:15
Duplicate of #22467

**Closed by zoechi** 2018-12-20 14:15 UTC
