### ISSUE TITLE
NoSuchMethodError: The getter 'isSetter' was called on null.

### ISSUE THREAD

**Issue by Musasshi90** [flutter/flutter#22292] opened 2018-09-26 03:36 UTC
Hello i have this issue, when the app start run at main.dart, the error appear (refer the log below).

I have the latest version of the flutter(Flutter (Channel beta, v0.8.2) still cannot solve this problem. Can help me, thx.

### Logs
```

compiler message: Unhandled exception:
compiler message: Crash when compiling null,
compiler message: at character offset null:
compiler message: NoSuchMethodError: The getter 'isSetter' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: isSetter
compiler message: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
compiler message: #1      SourceLibraryBuilder.addToScope (package:front_end/src/fasta/source/source_library_builder.dart:749:16)
compiler message: #2      Import.finalizeImports.<anonymous closure> (package:front_end/src/fasta/import.dart:65:18)
compiler message: #3      Import.finalizeImports.<anonymous closure> (package:front_end/src/fasta/import.dart:79:10)
compiler message: #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
compiler message: #5      Scope.forEach (package:front_end/src/fasta/scope.dart:251:11)
compiler message: #6      Import.finalizeImports (package:front_end/src/fasta/import.dart:72:26)
compiler message: #7      SourceLibraryBuilder.addImportsToScope (package:front_end/src/fasta/source/source_library_builder.dart:736:14)
compiler message: #8      KernelLibraryBuilder.addImportsToScope (package:front_end/src/fasta/kernel/kernel_library_builder.dart:1251:11)
compiler message: #9      SourceLoader.computeLibraryScopes.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:341:23)
compiler message: #10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
compiler message: #11     SourceLoader.computeLibraryScopes (package:front_end/src/fasta/source/source_loader.dart:338:14)
compiler message: #12     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:246:18)
compiler message: <asynchronous suspension>
compiler message: #13     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
compiler message: <asynchronous suspension>
compiler message: #14     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:239:12)
compiler message: <asynchronous suspension>
compiler message: #15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:233:24)
compiler message: <asynchronous suspension>
compiler message: #16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
compiler message: #17     new Future.sync (dart:async/future.dart:224:31)
compiler message: #18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
compiler message: #19     _rootRun (dart:async/zone.dart:1124:13)
compiler message: #20     _CustomZone.run (dart:async/zone.dart:1021:19)
compiler message: #21     _runZoned (dart:async/zone.dart:1516:10)
compiler message: #22     runZoned (dart:async/zone.dart:1463:12)
compiler message: #23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
compiler message: #24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
compiler message: <asynchronous suspension>
compiler message: #25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
compiler message: <asynchronous suspension>
compiler message: #26     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:329:67)
compiler message: #27     new Future.<anonymous closure> (dart:async/future.dart:176:37)
compiler message: #28     _rootRun (dart:async/zone.dart:1120:38)
compiler message: #29     _CustomZone.run (dart:async/zone.dart:1021:19)
compiler message: #30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
compiler message: #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
compiler message: #32     _rootRun (dart:async/zone.dart:1124:13)
compiler message: #33     _CustomZone.run (dart:async/zone.dart:1021:19)
compiler message: #34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
compiler message: #35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
compiler message: #36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
compiler message: #37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
compiler message: #38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
compiler message: 
compiler message: 
compiler message: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
compiler message: #1      SourceLibraryBuilder.addToScope (package:front_end/src/fasta/source/source_library_builder.dart:749:16)
compiler message: #2      Import.finalizeImports.<anonymous closure> (package:front_end/src/fasta/import.dart:65:18)
compiler message: #3      Import.finalizeImports.<anonymous closure> (package:front_end/src/fasta/import.dart:79:10)
compiler message: #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
compiler message: #5      Scope.forEach (package:front_end/src/fasta/scope.dart:251:11)
compiler message: #6      Import.finalizeImports (package:front_end/src/fasta/import.dart:72:26)
compiler message: #7      SourceLibraryBuilder.addImportsToScope (package:front_end/src/fasta/source/source_library_builder.dart:736:14)
compiler message: #8      KernelLibraryBuilder.addImportsToScope (package:front_end/src/fasta/kernel/kernel_library_builder.dart:1251:11)
compiler message: #9      SourceLoader.computeLibraryScopes.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:341:23)
compiler message: #10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
compiler message: #11     SourceLoader.computeLibraryScopes (package:front_end/src/fasta/source/source_loader.dart:338:14)
compiler message: #12     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:246:18)
compiler message: <asynchronous suspension>
compiler message: #13     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
compiler message: <asynchronous suspension>
compiler message: #14     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:239:12)
compiler message: <asynchronous suspension>
compiler message: #15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:233:24)
compiler message: <asynchronous suspension>
compiler message: #16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
compiler message: #17     new Future.sync (dart:async/future.dart:224:31)
compiler message: #18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
compiler message: #19     _rootRun (dart:async/zone.dart:1124:13)
compiler message: #20     _CustomZone.run (dart:async/zone.dart:1021:19)
compiler message: #21     _runZoned (dart:async/zone.dart:1516:10)
compiler message: #22     runZoned (dart:async/zone.dart:1463:12)
compiler message: #23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
compiler message: #24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
compiler message: <asynchronous suspension>
compiler message: #25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
compiler message: <asynchronous suspension>
compiler message: #26     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:329:67)
compiler message: #27     new Future.<anonymous closure> (dart:async/future.dart:176:37)
compiler message: #28     _rootRun (dart:async/zone.dart:1120:38)
compiler message: #29     _CustomZone.run (dart:async/zone.dart:1021:19)
compiler message: #30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
compiler message: #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
compiler message: #32     _rootRun (dart:async/zone.dart:1124:13)
compiler message: #33     _CustomZone.run (dart:async/zone.dart:1021:19)
compiler message: #34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
compiler message: #35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
compiler message: #36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
compiler message: #37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
compiler message: #38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

### Flutter doctor -v
```
 C:\Users\Public\Documents\My Project\casa>flutter doctor -v
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-MY)
    • Flutter version 0.8.2 at C:\src\flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\Zappit\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = C:\Users\Zappit\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-09-26 09:11
What action led to this exception? (what steps to reproduce)
Please add the output of `flutter doctor -v`.

**Comment by jeanpaulcozzatti** [comment] 2018-11-15 00:05
I have the same issue.
Hot reload on IOS simulator


[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone XR • 35E1965A-0CF5-4A3B-B65C-09689ED47EDC • ios • iOS 12.1 (simulator)

**Comment by zoechi** [comment] 2018-11-19 19:20
@jeanpaulcozzatti have you tried a newer Flutter version (new `beta` channel or `master` channel)?

**Comment by jeanpaulcozzatti** [comment] 2018-11-20 18:16
@zoechi i was able to isolate it and fix, would appreciate any advice on a better approach.

I had a library exports for files that i was importing to other files/screens. like so.

### imports.dart
```
export 'package:evand/theme/evan_theme.dart';
export 'package:firebase_analytics/firebase_analytics.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:firebase_database/firebase_database.dart';
export 'package:firebase_storage/firebase_storage.dart';
export 'package:fluro/fluro.dart';
```

i would then import imports.dart where necessary.

at some point this (in the last month?) hotloads started breaking with this way of importing files.
Is there a proper way of doing this?

**Comment by zoechi** [comment] 2018-11-20 19:13
@jeanpaulcozzatti there is nothing against having such combined exports.
My suspicion is that it's rather accidentally that such a change fixed the issue.
Perhaps `flutter clean` had done it already. Have you tried?
It's possible thought that a Dart bug was introduced.

**Comment by jeanpaulcozzatti** [comment] 2018-11-20 22:12
thanks @zoechi. i tried many a flutter clean :),
clean pulls from my repos, etc... 
i've reproduced it on many pages. it's odd.

**Comment by zoechi** [comment] 2018-12-12 14:12
Are you still seeing this?
Any chance you can provide a reproduction?
Can you please try again with the latest Flutter version?

**Comment by Musasshi90** [comment] 2018-12-14 02:58
I'm still having this issue, even i upgraded the flutter version. Same issue like @jeanpaulcozzatti mentioned above.

**Comment by zoechi** [comment] 2018-12-14 07:07
And you are on the latest Flutter version (`1.0.0`) now?
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted might be worth a try.

**Comment by Musasshi90** [comment] 2018-12-14 07:21
@zoechi this is my latest version
 Flutter (Channel master, v1.1.2-pre.22, on Microsoft Windows [Version 10.0.17134.471], locale en-MY)
    • Flutter version 1.1.2-pre.22 at C:\src\flutter
    • Framework revision 95b0124785 (9 hours ago), 2018-12-13 14:11:11 -0800
    • Engine revision a549981da7
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by zoechi** [comment] 2018-12-14 09:33
It looks like a Dart bug to me. Perhaps it's better to report in https://github.com/dart-lang/sdk.
I think it will get more attention there. 
Please link this issue if you do.

> this appear when i run the main.dart.

Can you provide a minimal reproduction for that?

**Comment by cbracken** [comment] 2019-11-06 21:34
Thanks for your contribution. Since we haven't seen a reply, we're going to reluctantly close this PR for now, but if you get time to address the comments, we'd be more than happy to take a look at a new PR. If you do send a new PR, it would be very useful to reference this one in the description in order to help reviewers see the previous context.

**Closed by cbracken** 2019-11-06 21:34 UTC
Labels: dependency: dart, engine, severe: crash, ▣ platform-android
