### ISSUE TITLE
I have the same problem with both Android 19 phones. The page can be loaded normally, but it can't be operated. Sliding or clicking can't trigger the above exceptions. It's the same with the update of 2.0.12 today. My log has been very detailed. Why can't we pay attention to it? If your document is directly changed to the minimum Android 22, I can just give up and stop paying attention

### ISSUE THREAD

**Issue by puzhengwu** [flutter/flutter#88146] opened 2021-08-13 06:15 UTC
I have the same problem with both Android 19 phones. The page can be loaded normally, but it can't be operated. Sliding or clicking can't trigger the above exceptions. It's the same with the update of 2.0.12 today. My log has been very detailed. Why can't we pay attention to it? If your document is directly changed to the minimum Android 22, I can just give up and stop paying attention

_Originally posted by @puzhengwu in https://github.com/flutter/flutter/issues/87980#issuecomment-898218369_

**Comment by puzhengwu** [comment] 2021-08-13 06:54
![image](https://user-images.githubusercontent.com/4401394/129316716-da8dee17-418d-409f-a1f6-12e1c3b2e521.png)

The cloud test platform has a lot of android4.4.4 machines, all have the same problem, the page can open, but can't operate

**Comment by TahaTesser** [comment] 2021-08-16 07:40
Hi @puzhengwu 
It is the same on an emulator and I have a created new issue for the website to mention the minimum requirement for both engine modes and ensure they're the  functioning version, which doesn't rely on the package and its bugs  such as webview 

Here https://github.com/flutter/website/issues/6152

I will investigate it more and find out what is actual min requirement until the issue is a duplicate of https://github.com/flutter/flutter/issues/87980

**Closed by TahaTesser** 2021-08-16 07:40 UTC
Labels: in triage
