### ISSUE TITLE
Flutter web hangs when downloading file on Chrome

### ISSUE THREAD

**Issue by milke** [flutter/flutter#150523] opened 2024-06-19 21:58 UTC
I can reproduce this in Chrome, but not in Firefox or Safari, so maybe this is something for @addyosman to look into.

I've got a flutter web app, build with flutter version 3.22.2. When I click a button to download a file, the download animation happens and immediately afterwards the flutter web app becomes unresponsive to clicks and scrolls. Switching to another tab and then back unfreezes the page, as well as switching to another (not Chrome) application. Using the latest Chrome version on macOS, 126.0.6478.62 (Universal). changing tabs or switching to another app unlocks the hang. So it seems like the download popup on Chrome is causing the tab to be in a frozen state.

Links to related Chrome support issues:
https://support.google.com/chrome/thread/280608434?hl=en&sjid=30753122648466353-NC
https://support.google.com/chrome/thread/280904881?hl=en&sjid=16115862103674561801-NA
https://support.google.com/chrome/thread/280905329?hl=en&sjid=375371675249558091-EU

### Steps to reproduce

A sample app source can be found here: https://github.com/milke/chrome_bug
Run that flutter app on Web in, for example, VSCode debugger, click the Crash Me button.  It hangs the UI.

### Code sample

In my case, any code that causes Chrome to download a file shows this issue and I tried various methods. For example:

```
import 'package:url_launcher/url_launcher.dart' as launcher;

launcher.launchUrl(
    Uri.parse('https://get.cocoatech.com/dashboard/Deckr-macos.dmg'),
    webOnlyWindowName:   '_self',
);

```

Also can be reproduced visiting this site in Chrome and clicking on any of buttons to download files/binaries: https://deckr.surf/

We tried downloading with alternate code, so it seems not to be a bug in `url_launcher`.  The sample app is just the simplest code. Any download on chrome will hang flutter web. Also reproducible on a few other flutter websites I know of, with a download button.

### What target platforms are you seeing this bug on?

macOS, Linux

### OS/Browser name and version | Device information

The latest stable Chrome version 126.0.6478.62 on macOS Sonoma beta version 14, but the same happened on the latest official version macOS 14.5
Linux Chrome version 126.0.6478.114 (Official Build) (64-bit)
MacBook Pro (16 inch, late 2021, M1 Max)

### Does the problem occur on emulator/simulator as well as on physical devices?

Desktop, Chrome, and VSCode debugger on Chrome

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.6 23G5052d darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/milke/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • macOS (desktop)                             • macos                              • darwin-arm64  • macOS 14.6 23G5052d darwin-arm64
    • Mac Designed for iPad (desktop)  • mac-designed-for-ipad  • darwin                • macOS 14.6 23G5052d darwin-arm64
    • Chrome (web)                                  • chrome                             • web-javascript  • Google Chrome 126.0.6478.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by andrewmallory8** [comment] 2024-06-19 22:46
I'm seeing this also. My Flutter website does not work on Chrome

**Comment by darshankawar** [comment] 2024-06-20 07:28
Thanks for the report @milke 
If it's occuring in latest chrome version, you can check [this](https://github.com/flutter/flutter/issues/150193) issue which has been fixed recently that was linked with a chromium issue.
Also, there's another issue open that you can check if it resembles your case or not : https://github.com/flutter/flutter/issues/149417

**Comment by scolnet** [comment] 2024-06-20 21:20
Hello team,

I confirm the problem with Chrome and flutter 3.22.2 (on mac and windows too).
Just after download, the app freeze. You need to switch tab of Chrome and back on it to unfreeze the app.
Same behavior with alternate code like
```
AnchorElement anchorElement = new AnchorElement(href: url);
              anchorElement.download = "Test";
              anchorElement.click();
```
Impact : no more download fonctionality with latest stable version of Flutter on Chrome !

@darshankawar, It's severe regression, could you increase priority of the issue ? I think it's the same than  https://github.com/flutter/flutter/issues/149417

Thanks for your help

**Comment by mdebbar** [comment] 2024-06-21 20:26
Duplicate of https://github.com/flutter/flutter/issues/149417

**Closed by mdebbar** 2024-06-21 20:26 UTC
Labels: waiting for customer response, in triage
