### ISSUE TITLE
Running a project on VSCode with Linux or Chrome 

### ISSUE THREAD

**Issue by ragokan** [flutter/flutter#77516] opened 2021-03-07 11:42 UTC
## Steps to Reproduce

1. Firstly, everything works well on terminal or android studio.
2. On VSCode, I get this:
![image](https://user-images.githubusercontent.com/63511519/110238479-ec186680-7f52-11eb-8486-6cf03a825d73.png)
3. I press the 'Run' button, if I select Android device, it works, but if I select chrome or linux device, it doesn't. It waits for like 3 seconds, an application starts and shuts down immediately then 'Debug Console' says that there are an error.
4. Chrome, on the other hand is always stuck, it opens chrome and closes directly but no error.
![image](https://user-images.githubusercontent.com/63511519/110238554-4c0f0d00-7f53-11eb-9009-a9824ca2a398.png)

## Logs

<details>
<summary>Logs</summary>

Flutter Doctor V
```
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-10.0.pre at /home/rago/snap/flutter/common/flutter
    • Framework revision cc9b78fc5c (10 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/rago/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2021-03-08 09:42
Hi @ragokan 
Just tried to reproduce the issue in manual Flutter setup as well as Flutter snap on the `dev` channel in VS Code for web and Linux, has no issues when launching the app from VS Code. I saw this issue before, a couple of weeks back but no issue since then. It might be fixed by the plugin.

<details> 
<summary>flutter doctor -v</summary> 

```bash
taha@pop-os:~/AndroidStudioProjects$ flutter doctor -v
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-10.0.pre at /home/taha/snap/flutter/common/flutter
    • Framework revision cc9b78fc5c (11 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.54.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
taha@pop-os:~/AndroidStudioProjects$
```

```bash
taha@pop-os:~/AndroidStudioProjects$ flutter doctor -v
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-10.0.pre at /home/taha/snap/flutter/common/flutter
    • Framework revision cc9b78fc5c (11 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.54.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
taha@pop-os:~/AndroidStudioProjects$
```

</details>

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-08 09:42 UTC
Labels: in triage

**Comment by ragokan** [comment] 2021-03-08 10:00
> Hi @ragokan
> Just tried to reproduce the issue in manual Flutter setup as well as Flutter snap on the `dev` channel in VS Code for web and Linux, has no issues when launching the app from VS Code. I saw this issue before, a couple of weeks back but no issue since then. It might be fixed by the plugin.
> 
> flutter doctor -v
> Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> Thank you

Great, I will ask in VS Code Flutter Extension repo, I am also using VSCode Insiders, it may also be the problem.

**Comment by ragokan** [comment] 2021-03-08 10:06
> Hi @ragokan
> Just tried to reproduce the issue in manual Flutter setup as well as Flutter snap on the `dev` channel in VS Code for web and Linux, has no issues when launching the app from VS Code. I saw this issue before, a couple of weeks back but no issue since then. It might be fixed by the plugin.
> 
> flutter doctor -v
> Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> Thank you

Just to add, 
![image](https://user-images.githubusercontent.com/63511519/110306645-192a4f00-800f-11eb-9742-aa9b195b1126.png)
It works well in vscode, the problem may be about insiders.
