### ISSUE TITLE
The applications developed with Flutter must be able to run normally in China's Windows 7 32-bit system

### ISSUE THREAD

**Issue by GithubSiXun** [flutter/flutter#116559] opened 2022-12-06 01:45 UTC
Hello,
We have a big request for the 32-bit windows flutter.
We are migrating our app from mobile to desktop,About 1 million users in our company are using 32-bit windows 7. Lots of old computers still run 32-bit Windows in China.
The applications developed with Flutter must be able to run normally in China's Windows 7 32-bit system.Please raise the priority to the support the 32-bit windows.

**Comment by yefl2064** [comment] 2022-12-06 01:51
We have the same requirement, how can we run it on win7 32bit

**Comment by yefl2064** [comment] 2022-12-06 01:52
We have the same request, how can we run it on win7 32-bit?

**Comment by stuartmorgan** [comment] 2022-12-06 02:26
Closing as a duplicate of https://github.com/flutter/flutter/issues/37777, which you already commented on.

Please do not deliberately file duplicate issues; it will not change prioritization, and triaging duplicate issues takes time that could be spent on other things.

**Closed by stuartmorgan** 2022-12-06 02:26 UTC
