### ISSUE TITLE
Cannot start FlutterActivity when adding flutterpart library as aar module to existing application

### ISSUE THREAD

**Issue by tomergoldst** [flutter/flutter#18025] opened 2018-05-30 13:38 UTC
## Steps to Reproduce

1. Create new flutter project
2. Create new Android app
3. Add flutter project into existing android app (from step 2) according to [](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) 
4. run the android app and start the MainActivity of flutter project -> **everything works**

5. run gradle -> assemble for the flutter project Build directory
6. copy the flutterpart-release.aar generated at build/outputs/arr
7. Create a different new Android app
8. Create new module  ->Import JAR/ARR package -> select flutterpart-release.aar -> finish
9. add to app build.grade "implementation project(':flutterpart')"
10. add button to start flutterpart MainAcitivty
ComponentName componentName = new ComponentName(getBaseContext(),
                        "com.example.flutterpart.MainActivity");
                Intent intent = new Intent().setComponent(componentName);
                startActivity(intent);
11. Run the app -> click the button -> app crashed

## Logs

Crash log
```
05-30 16:32:36.124 21199-21199/com.example.androidwithflutter3 A/flutter: [FATAL:flutter/fml/icu_util.cc(95)] Check failed: context->IsValid(). Must be able to initialize the ICU context. Tried: /data/user/0/com.example.androidwithflutter3/app_flutter/icudtl.dat
05-30 16:32:36.124 21199-21199/com.example.androidwithflutter3 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 21199 (oidwithflutter3)
```
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.16299.125], locale he-IL)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected devices (1 available)
```

**Comment by alexandresoler** [comment] 2018-06-13 14:27
Same for me.
Works well when including the flutter project as a module with sources (like https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)
Doesn't works when exporting the flutter project as an aar and include it on my Android APP as a fat aar. (Must be able to initialize the ICU context...)

**Comment by davidbilly** [comment] 2018-06-27 02:47
Same for me, after export to AAR. 

App crash and show "A/flutter: [FATAL:flutter/fml/icu_util.cc(95)] Check failed: context->IsValid(). Must be able to initialize the ICU context. Tried: /data/user/0/APP_ID/app_flutter/icudtl.dat"

**Comment by davidbilly** [comment] 2018-06-27 09:45
Guys, after few attempt and i manage let AAR work with my demo app on simulator. 

Reason : The **"assets/flutter_shared/icudtl.dat"** was not generated when you're export to AAR but export APK does include **"icudtl"** file if you directly embedded flutter SDK.

How to : 
Step : 
1) Build APK with flutter SDK directly. e.g : https://github.com/flutter/flutter/tree/flutter_module/examples/flutter_view
2) After you successfully build APK and use zip to extract APK and copy out the **"icudtl.dat"**
3) create **"src/main/assets/flutter_shared/"** folders and copy **"icudtl.dat"** to under **"flutter_shared"** folder on your library which used to export AAR later.
4) export your library to AAR and extract it make sure **"icudtl.dat"** created.
5) import AAR file into your main project and enjoy it.

Note : i'm not sure that **"icudtl.dat"** file what for and not sure will be work on all of android devices, please share/contribute me the result as i not own much android devices to test. 

Please share if have any better workaround for this issue.

Hopefully, in future flutter dev @mit-mit @mravn-google will included for export AAR.

Sorry for my bad english.

**Comment by mravn-google** [comment] 2018-06-27 10:18
@davidbilly Using [the new Flutter module template](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#preview-use-the-flutter-module-template), the `icudtl.dat` file is included in the apk of the host app. That file tells Flutter how to do international text processing with unicode.

**Comment by LarryLawrence** [comment] 2018-09-17 09:31
> @davidbilly Using [the new Flutter module template](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#preview-use-the-flutter-module-template), the ```icudtl.dat``` file is included in the apk of the host app. That file tells Flutter how to do international text processing with unicode.

Hi I'm using  [the new Flutter module template](
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#preview-use-the-flutter-module-template) and adding flutter module as source code, but still encountering this issue..

When searching in the project I can see ```icudtl.dat``` is already included in the jar. Why can't flutter find it? 
![img](https://upload-images.jianshu.io/upload_images/3326381-e9093752a463d706.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by matthew-carroll** [comment] 2018-09-18 00:27
@tomergoldst I tried to repro your issue but was unable to find any issues.  Here are the steps that I took:

1. Created an Android app project called android_app
1. Created a Flutter module project called flutter_module
1. Linked android_app to flutter_module as per the [steps in the Wiki](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)
1. Changed MainActivity in android_app to extend FlutterActivity
1. Launched android_app and confirmed that the Flutter UI displayed as expected
1. Changed android_app to an Android library by editing the build.gradle file
1. Ran ./gradlew assemble to create an AAR
1. Created a new Android app project called android_app2
1. Added the earlier AAR as a module to android_app2
1. Added a button to MainActivity2 within android_app2 that launches MainActivity from within the AAR

The above steps worked as expected without any build errors or crashes.

I'm going to close this ticket.  If you still have issues with the above steps then please re-open with any additional information that might help.

**Comment by Igor1201** [comment] 2018-10-30 19:21
@matthew-carroll We've just created a repo to reproduce the issue following your step above (using flutter flutter@40fc45ace3d75dce1a69b901429f3b6355a15fb9): https://github.com/Igor1201/min-repro-flutter

Your steps actually were missing the import of flutter classes themselves (the .aar generated from the `.android/Flutter` project) that is not embedded on the MyApplication project (the one you converted from an app to a library).

So our steps actually were:

1. Created an Android app project called `app` (on `android` folder)
2. Created a Flutter module project called `flutter_module` (on root)
3. Linked `app` to `flutter_module` as per the steps in the Wiki
4. Changed MainActivity in `app` to extend FlutterActivity
5. Launched `app` and confirmed that the Flutter UI displayed as expected
6. Changed `app` to an Android library by editing the build.gradle file
7. Ran ./gradlew assemble to create an AAR
8. Created a new Android app project called `app` (on `android_app_2` folder)
9. Added the earlier AAR as a module to `android_app_2`
10. Ran `./gradlew flutter:assemble` on `android` folder
11. **Added the flutter AAR (`flutter_module/.android/Flutter/(...)/outputs/flutter-debug.aar`) as a module to `android_app_2`**
12. Added a button to MainActivity2 within `android_app_2` that launches MainActivity from within the `app` AAR
13. Crashed with the missing icudtl.dat error

---

We thought about some solutions to this problem:
1. Change flutter.jar to be flutter.aar
  By definition, jar files on android shouldn't contain assets, so migrating flutter to an AAR would make it work, as the compiler would than merge the assets.

2. Add an `assets` folder containing `flutter_shared` to the generated `.android/Flutter` module
  This way, the output of this project (which is an AAR) will contain the `flutter_shared` folder inside `assets`, which will be merged to the final APK.

What do you think about the solutions? Do you have anything in mind, or do you have any concern with any of these approaches?

**Comment by matthew-carroll** [comment] 2018-11-02 21:36
I wanted to let you all know that I've seen the new posts here, I just haven't had a chance to come back to this issue.  I'll re-open it and come back to it when I can.

@Igor1201 FYI - Changing flutter.jar to flutter.aar is currently not possible due to infrastructure issues within the Flutter embedding/engine.  I'll look into your other suggestion when I get a chance.

**Comment by MichaelShnaider** [comment] 2018-11-07 16:35
@matthew-carroll Manually adding the icudtl file into a new assets folder works and fixes the issue, but now when you have a Flutter project that uses any plugin like path_provider for example, and you build the AAR file (with the icu file included), the project throws a missing plugin exception cause none of the plugins were included in the AAR im guessing. It's an addition to the icu issue. I made a separate issue for the missing plugins here: #23944

**Comment by jelenacarnegie** [comment] 2018-11-27 16:45
@mravn-google any updates here? issue is still present.

**Comment by matthew-carroll** [comment] 2018-11-27 22:51
Update: Support for AAR packaging is still not an imminent implementation.  It is on the roadmap but there are no hard dates.

CC for feature request visibility: @dnfield @cbracken @chinmaygarde @jason-simmons @sbaranov @mklim

**Comment by Igor1201** [comment] 2018-11-28 13:02
@matthew-carroll We've already implemented the second suggestion [discussed here](https://github.com/flutter/flutter/issues/18025#issuecomment-434435454) on the following PR: https://github.com/flutter/flutter/pull/23782

Hixie requested some tests on this matter however, as we described [here](https://github.com/flutter/flutter/pull/23782#issuecomment-435132344), we're not sure how to implement these tests as the changes are on gradle level and none of these are currently tested (and we're not sure how to setup a infrastructure to do this).

Do you have any idea and how can we advance this for now?

**Comment by jelenacarnegie** [comment] 2018-11-28 14:01
@Igor1201  and this PR solves the issue? 
Are you able to import your flutter .aar into you project, and everything works fine? Even plugins used in flutter .aar?
This is a showstopper for me at the moment, and I hope this will be fixed asap.

**Comment by Igor1201** [comment] 2018-11-28 16:04
@jelenacarnegie Yes. We are able to make this work with the PR + generate a FatAAR, as discussed on https://github.com/flutter/flutter/issues/23944

**Comment by jelenacarnegie** [comment] 2018-11-28 16:19
@eseidel @cbracken 

As I already said, this is a deal breaker for me(and probably many other developers).
I'm not able to import generated Flutter .aar into my existing Android project(and solution to import it as a module is not an option at the moment).

@Igor1201 says his PR solves this issue.

Can anyone from Flutter team at least take a look at it?

Thank you.

**Comment by eseidelGoogle** [comment] 2018-11-28 16:55
Things are pretty busy with Flutter Live being only a few days away.  I suspect this will need some help from @matthew-carrolll.  To set expectations: with Flutter Live and the holiday season, it's possible we won't get to help get the PR resolved until early 2019. :( Obviously we'll try to do to better than that.

**Comment by matthew-carroll** [comment] 2018-11-29 02:54
In additio to @eseidel's comments, for visibility, this issue might require work or input from any of the following: myself, @jason-simmons, @sbaranov, @mklim, @chinmaygarde, @cbracken 

If this problem is primarily Gradle related then I think myself, @jason-simmons, and @sbaranov are likely to be involved.

If this problem requires general AAR support then we have a buildroot issue that is likely to involve @jason-simmons, @chinmaygarde, and @cbracken

**Comment by carl1990** [comment] 2018-12-03 07:55
+1  
when I user debug.aar integrate into my native app is ok,use release.aar will be into crash

**Comment by jelenalecic** [comment] 2018-12-11 08:51
@carl1990 proguard maybe?

**Comment by carl1990** [comment] 2018-12-11 09:52
@jelenalecic  yes ,has resolved

**Comment by kimlet** [comment] 2018-12-21 07:54
just copy `flutter_shared` to your project assets

![image](https://user-images.githubusercontent.com/1001783/50331153-aa00d700-0538-11e9-8021-b9fc568c0f57.png)

**Comment by jelenalecic** [comment] 2019-01-15 13:11
@eseidel 

any updates? :)

**Comment by mahendramahi** [comment] 2019-05-31 09:39
## Use case
In my project we have ios and android native project. But after heard about flutter we decide that new functionality will develop into flutter module ( `flutter create -t module project_name` ) and finish work on flutter, we export .aar file from flutter project.

Now go to my android project and import flutter exported .aar file in android project as module or lib. for reference  see the image 
![Untitled](https://user-images.githubusercontent.com/9445572/58249703-37ad5080-7d7d-11e9-8441-58b5570a45dc.png)


After import we analyze .aar just like .apk file and here are image for reference  
![analyze](https://user-images.githubusercontent.com/9445572/58251588-996fb980-7d81-11e9-90a5-11284ec83d45.png)

## How can we call dart route page from Android app

`
@Override
  protected void onCreate(Bundle savedInstanceState){
        Flutter.startInitialization(getApplicationContext());
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        DisplayMetrics displayMetrics=new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(displayMetrics);
        height=displayMetrics.heightPixels;
        width=displayMetrics.widthPixels;


        View flutterView=Flutter.createView(
        MainActivity.this,
        getLifecycle(),
        "/"
        );
        FrameLayout.LayoutParams layout=new FrameLayout.LayoutParams(width,height);

        addContentView(flutterView,layout);
        }`

Call this code from my android activity .. 
and we are successfully able to load flutter view on android activity
and for android we export app.framwork and flutter.framwork , ios app also able to load same view as like android(save time of development same thing in different lang or on difference platform )

## issue
Now we create other module in flutter and import same as last time. during the import .aar we can change name of module using android studio. Here are we attaching image reference.

![next](https://user-images.githubusercontent.com/9445572/58252141-0768b080-7d83-11e9-8a7d-19d3a9a62dee.png)


Now you can see the .so file in second .aar file with the same name of last one .aar file..

when we run this it gives error 
` More than one file was found with OS independent path libflutter.so' `

**Comment by tvolkert** [comment] 2019-05-31 14:25
FYI @blasten @xster

**Comment by xster** [comment] 2019-08-09 02:53
I'd like to reset this bug since the previous solution was a half offering and a lot has changed since. For instance, we have a proper `flutter build aar` CLI function now. 

If you had issues with this in the past, could you try the new process https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#1-depend-on-the-android-archive-aar on the master channel?

**Closed** 2019-09-04 00:42 UTC
Labels: a: existing-apps, customer: headline, engine, t: gradle, tool, waiting for customer response
