### ISSUE TITLE
WidgetsBindingObserver doesn't work

### ISSUE THREAD

**Issue by vijayawoshe** [flutter/flutter#44525] opened 2019-11-09 21:19 UTC
Hello Flutter Team,

WidgetsBindingObserver is not working with latest flutter version.

```
Flutter 1.10.16-pre.111 • channel master • https://github.com/flutter/flutter.git
Framework • revision c1920c4c03 (16 hours ago) • 2019-11-08 23:36:17 -0500
Engine • revision e0b9a2bb23
Tools • Dart 2.7.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.16-pre.111, on Mac OS X 10.15.1 19B88, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)


```

```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    print("__________________state");
    print(state.index);
    switch(state) {
      case AppLifecycleState.paused:
        print('paused state___________________');
        break;
      case AppLifecycleState.resumed:
        // call user online api
        break;
      case AppLifecycleState.inactive:
        print('inactive state______________');
        // call user offline api
        break;
      case AppLifecycleState.suspending:
        print('suspending state');
        break;
    }
    super.didChangeAppLifecycleState(state);
  }
```

**Comment by iapicca** [comment] 2019-11-11 10:31
Hi @vijayawoshe 
I've just tested the  on the latest master channel release with this [code](https://gist.github.com/iapicca/4fb71e506d33e3fa6cac5369e294a262) and seams working as intended,
I even run your code with the following output

<details>
  <summary>output</summary>

```
I/flutter (27837): __________________state
I/flutter (27837): 1
I/flutter (27837): inactive state______________
I/flutter (27837): __________________state
I/flutter (27837): 2
I/flutter (27837): paused state___________________
I/flutter (27837): __________________state
I/flutter (27837): 1
I/flutter (27837): inactive state______________
I/flutter (27837): __________________state
I/flutter (27837): 0
I/flutter (27837): __________________state
I/flutter (27837): 1
I/flutter (27837): inactive state______________
I/flutter (27837): __________________state
I/flutter (27837): 0
I/flutter (27837): __________________state
I/flutter (27837): 1
I/flutter (27837): inactive state______________
I/flutter (27837): __________________state
I/flutter (27837): 2
I/flutter (27837): paused state___________________
I/flutter (27837): __________________state
I/flutter (27837): 1
I/flutter (27837): inactive state______________
I/flutter (27837): __________________state
I/flutter (27837): 0
```
</details>

Can you please provide your  `flutter run --verbose`?
thank you

**Comment by iapicca** [comment] 2019-12-02 15:57
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-12-02 15:57 UTC
Labels: waiting for customer response

**Comment by RicharC293** [comment] 2021-01-26 15:44
Hi, after some time I had the same problem. I was run this code and when start the application not show AppLifeCycle State. Only show this if lock and unlock mobile. Please, open this issue.

**Comment by iapicca** [comment] 2021-01-26 16:07
> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
> All system setups can be slightly different so its always better to open new issues and reference related issues.

@RicharC293 
please follow the indication in the [comment above](https://github.com/flutter/flutter/issues/44525#issuecomment-560457909)
