### ISSUE TITLE
[image_picker] Support maxWidth and maxHeight on Windows

### ISSUE THREAD

**Issue by madicd** [flutter/flutter#129441] opened 2023-06-23 18:44 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Automatic resizing of selected images on Windows 10 and newer.
As we already use file_picker, and it supports automatic resizing for Android and iOS, it would be beneficial to have the same feature on Windows.

### Proposal

Support `maxWidth` and `maxHeight` image options on Windows 10 and newer.

```
await picker.pickMultiImage(maxWidth: 1024, maxHeight: 768);

await picker.pickImage(maxWidth: 1024, maxHeight: 768, source: ImageSource.gallery)
```

This will automatically scale the selected images.

**Comment by stuartmorgan** [comment] 2023-06-23 21:44
Duplicate of https://github.com/flutter/flutter/issues/128453

**Closed by stuartmorgan** 2023-06-23 21:44 UTC
