### ISSUE TITLE
Dart SDK failing to roll to the framework on analysis failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#137540] opened 2023-10-30 14:24 UTC
Starting with https://github.com/flutter/flutter/pull/137470, framework analysis and customer testing analysis are failing with errors like:

```
error • Instance member 'parse' can't be accessed using static access • dev/automated_tests/flutter_test/flutter_gold_test.dart:43:13 • static_access_to_instance_member
```

The list of Dart SDK commits is here https://dart.googlesource.com/sdk.git/+log/5a666e8d8259..38e8459ca2aa.

There are a couple of analyzer changes from @stereotype441

Surprisingly, the monorepo dashboard is not red on this failure cc @whesse

**Comment by whesse** [comment] 2023-10-30 14:44
The flutter-analyze bot, which runs the analysis tests on flutter with each Dart SDK change (so it is on Dart CI, not monorepo CI) did detect this failure.  There were 2 failed builds, and then it was fixed again. It was either fixed by the next commit (after a 2 day gap due to the weekend), or it is a flaky failure due somehow to something being cached.

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-analyze

Asking for verification that this was really caused and fixed by the SDK commits, @johnniwinther .
It doesn't seem like the change to @scheglov to only analyzer/test/src/summary/macro could have caused this, or the inline classes experiment flag could have fixed this.

Also, the error was reported to not reproduce locally.

**Comment by johnniwinther** [comment] 2023-10-30 14:52
I don't think commit #21248 could have fixed these errors.

**Comment by zanderso** [comment] 2023-10-30 15:08
After landing the revert in https://github.com/flutter/engine/pull/47459, there were similar analyzer failures in Engine postsubmit CI https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/441837/overview

**Comment by zanderso** [comment] 2023-10-30 15:21
In chat @whesse mentioned that https://dart-review.googlesource.com/c/sdk/+/332401 was a large change appearing in the range https://dart.googlesource.com/sdk.git/+log/360370ff93b0..5a666e8d8259 cc @johnniwinther

**Comment by whesse** [comment] 2023-10-30 15:22
But also  https://dart-review.googlesource.com/c/sdk/+/332370  is a later change that tries to fix a problem with lookups.

**Comment by zanderso** [comment] 2023-10-30 16:04
The error continues to happen on the presubmits for reverting the previous Dart roll at https://github.com/flutter/engine/pull/47464:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Framework%20Smoke%20Tests/39504/overview

**Comment by scheglov** [comment] 2023-10-30 16:45
I believe https://dart-review.googlesource.com/c/sdk/+/332370 causes this breakage.

**Comment by zanderso** [comment] 2023-10-30 17:38
Assigning to @gaaclarke to track restarting the rollers when fixes/reverts land.

**Comment by aam** [comment] 2023-10-30 17:42
@scheglov , can you suggest some steps to troubleshoot this kind of error? It would be good to know whether for example, running previous version of analyzer, then rerunning it with new version without clearing the cache(keeping `.dart_tool` folder intact, could help?

**Comment by scheglov** [comment] 2023-10-30 18:32
The cached data version issue can show in various ways - from surprising diagnostics like here, to crashes when loading data. If you run the previous version of the analyzer, and then the new version, and there are strange issues, then it might be the version mismatch. Might be something else, though, e.g. just bugs in the analyzer. If removing `.analysis-driver` fixes the issues, then this is the cache version issue.

**Comment by zanderso** [comment] 2023-10-30 20:07
@scheglov is there any way to run the analyzer that ignores caches? For the Flutter CI tests, we can both investigate ways to avoid retaining caches between runs, and disable reading any caches in the first place in order to avoid problems like this in the future.

**Comment by scheglov** [comment] 2023-10-30 20:14
Disable cache - AFAIK this is impossible.

I don't know for sure on what level you invoke the analyzer. The analyzer as a package, lets you provide `ByteStore` that can be anywhere, even in memory. The analyzer as analysis server, usually uses the fixed cache location, but also have an option `--cache` that overrides the cache location (which might be not available anymore through `dart analyze xyz`). Or you can set `ANALYZER_STATE_LOCATION_OVERRIDE` environment variable to change the location.

But if you use any of these ways, then why not just remove the cache from the file system?

**Comment by gaaclarke** [comment] 2023-10-30 21:32
Closing this issue.  The forward fix for the analyzer has landed in the dart sdk.  Dart roller has been resumed.  Engine->flutter manual roll has succeeded and landed.  The engine->flutter roller has been resumed.

**Closed by gaaclarke** 2023-10-30 21:32 UTC
Labels: dependency: dart, P0, team-engine, triaged-engine
