### ISSUE TITLE
[web] PageView physics not working

### ISSUE THREAD

**Issue by ja2375** [flutter/flutter#38175] opened 2019-08-11 12:30 UTC
I am writing a flutter_web app. Just tried to include the PageView widget and disable user scrolling by adding a `NeverScrollableScrollPhysics` widget to its `physics` property but it is not working (i mean only the `physics` property, everything else works).

This is my code:

```
PageView.builder(
  controller: _pageController,
  itemCount: 3,
  physics: NeverScrollableScrollPhysics(),
  itemBuilder: (context, pos) {
    return Center(
      child: Text('Page $pos'),
    );
  },
)
```

The physics property seems to be ignored as i'm able to swipe the PageView.

**Comment by yjbanov** [comment] 2019-09-19 22:09
This seems to be a duplicate of https://github.com/flutter/flutter/issues/35687

**Closed by yjbanov** 2019-09-19 22:09 UTC
Labels: ☸ platform-web
