### ISSUE TITLE
"OK" button in Arabic doesn't look right

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#12288] opened 2017-09-27 20:03 UTC
![flutter_ok_in_ar_bug](https://user-images.githubusercontent.com/211513/30935001-2bf8e90e-a384-11e7-8e11-e9cae4514997.png)

/cc @HansMuller

**Comment by Yousefjb** [comment] 2017-09-30 10:41
I tried the chat tutorial at [codelab](https://codelabs.developers.google.com/codelabs/flutter/index.html#0) and arabic text breaks in the same way

**Comment by Hixie** [comment] 2017-10-31 23:55
I've been able to reproduce this bug; unfortunately it does not occur with the Ahem font.

**Comment by YaminT** [comment] 2018-03-07 07:33
Looks like Text widget relies a lot on Textdirection to paint its value.
try setting textDirection property in the Text widget.it should solve it.
new Text('حسنا',textDirection: TextDirection.rtl,)

**Comment by HansMuller** [comment] 2018-03-07 16:53
The DatePicker's OK button is defined like this:
```dart
  new FlatButton(
    child: new Text(localizations.okButtonLabel),
    onPressed: _handleOk,
  ),
```

I'm not familiar with Arabic script but it does seem like the حسنا flat button label was rendered RTL but we've inexplicably inserted a line break?

**Comment by Hixie** [comment] 2018-03-07 17:25
Almost certainly a dupe of https://github.com/flutter/flutter/issues/10719.

Setting the textDirection explicitly shouldn't need to help assuming you've correctly set up the localization, since then the infrastructure should already be configuring everything to RTL.

**Comment by Rmaan** [comment] 2018-05-30 10:29
This issue (breaking Arabic/Persian text lines in inappropriate positions), is fixed a long time ago. OP could verify.

**Closed** 2018-05-30 15:38 UTC
