### ISSUE TITLE
Different Import style make Casting error at compile

### ISSUE THREAD

**Issue by anggaaryas** [flutter/flutter#125864] opened 2023-05-02 07:34 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. run this `bar_test.dart` code

### Expected results

1. the test should success

### Actual results

Test 1 : `Error: The argument type  can't be assigned to the parameter type `
Test 2: Success

### Code sample

<details><summary>Code sample</summary>

imagine we will test `Bar` class that need `Foo` object

1. Inside `lib/`

foo.dart

```dart
class Foo {}
```

bar.dart

```dart
import 'foo.dart';

class Bar{
  Foo foo;

  Bar(this.foo);
}
```

2. inside `test/`

mock_foo.dart

```dart
import '../lib/foo.dart';

class MockFoo implements Foo {}
```

mock_foo_2.dart

```dart
import 'package:test_dif_import/foo.dart';

class MockFoo2 implements Foo {}
```

bar_test.dart

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:test_dif_import/bar.dart';

import 'mock_foo.dart';
import 'mock_foo_2.dart';

void main(){
  test("test create bar using MockFoo", (){
    var result = false;
    try{
      var mock = MockFoo();
      var bar = Bar(mock);
      result = true;
    } finally {
      expect(result, true);
    }
  });

  test("test create bar using MockFoo2", (){
    var result = false;
    try{
      var mock = MockFoo2();
      var bar = Bar(mock);
      result = true;
    } finally {
      expect(result, true);
    }
  });
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Althought the analytic did not detected any error

![Screenshot 2023-05-02 at 14 32 23](https://user-images.githubusercontent.com/36914072/235606470-2a17b732-691f-4baa-972d-361a00774399.png)

</details>

### Logs

<details><summary>Logs</summary>

Even i use try-catch, the error still not catched

```console
Testing started at 14.26 ...
test/bar_test.dart:12:21: Error: The argument type 'MockFoo' can't be assigned to the parameter type 'Foo'.
 - 'MockFoo' is from 'test/mock_foo.dart'.
 - 'Foo' is from 'package:test_dif_import/foo.dart' ('lib/foo.dart').
      var bar = Bar(mock);
                    ^
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v

[✓] Flutter (Channel stable, 3.7.7, on macOS 13.3.1 22E261 darwin-arm64, locale
    en-ID)
    • Flutter version 3.7.7 on channel stable at /Users/Angga/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (8 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/Angga/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/Angga/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS
      13.3.1 22E261 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2023-05-02 10:07
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/41868

**Closed by stuartmorgan** 2023-05-02 10:07 UTC
