### ISSUE TITLE
TextField border color incorrect for default state

### ISSUE THREAD

**Issue by asadbekdev** [flutter/flutter#98368] opened 2022-02-13 20:19 UTC
![image](https://user-images.githubusercontent.com/67022917/153773215-f572deef-95e9-44cd-a050-c4ae0e4df795.png)

Hello, 
1- in first situation textfield border should be opacity 0.4 as picture
2 - in focus and after filling textfiled, textfiled border opacity's should be 1.0
but in default situation textfield border opacity's is 1.0 too.

![image](https://user-images.githubusercontent.com/67022917/153773230-055a6316-c3bd-44c2-b998-7a48ef09d67f.png)

in my view, before filling the textfiled border property should work, when you touch it focusBorder should work, when you filled enabled border should work.
Unfortunately, before the filling and after the filled, in the both states enabled border property working.

is there any flutter bug or my mistake ?

**Comment by asadbekdev** [comment] 2022-02-13 21:07
It's Flutter 2.10 version bug !

**Comment by mozochek** [comment] 2022-02-14 05:15
It's not a bug, if you need to add opacity to your text field in your situation you need to replace `border` value to `enabledBorder`. Actually I don't know if `border` value even used in framework, because I didn't have situation when it's value was used.

**Comment by maheshmnj** [comment] 2022-02-14 12:24
Hi @asadbekdev, I see that this is working as intended. In your code  snippet focusedBorder and enabledBorder has same color so you are seeing the same color when the TextField is focused.  Please refer the below code sample which shows the desired behavior.

<details>
<summary>flutter doctor -v</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Test",
      theme: ThemeData(),
      home: Scaffold(
          appBar: AppBar(
            title: const Text("Test"),
          ),
          body: const Center(
              child: TextField(
            decoration: InputDecoration(
              enabledBorder:
                  OutlineInputBorder(borderSide: BorderSide(color: Colors.red)),
              focusedBorder: OutlineInputBorder(
                  borderSide: BorderSide(color: Colors.teal)),
              labelText: "Test",
            ),
          ))),
    );
  }
}

```
</details>
 
Closing as this is not a bug.

**Closed** 2022-02-14 12:25 UTC
Labels: in triage

**Comment by asadbekdev** [comment] 2022-02-14 14:17
> It's not a bug, if you need to add opacity to your text field in your situation you need to replace `border` value to `enabledBorder`. Actually I don't know if `border` value even used in framework, because I didn't have situation when it's value was used. `Enabled` means that flag `enabled = true` and field is not focused (default state), `focused` means flag flag `enabled = true` and field is focused.

Thanks! worked
