### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by shathurshan** [flutter/flutter#71916] opened 2020-12-08 14:36 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=D1CGAPE740501898 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:148:16)
#5      _writeFlutterPluginsListLegacy (package:flutter_tools/src/plugins.dart:520:15)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:1140:30)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:242:11)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:960:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _runZoned (dart:async/zone.dart:1630:10)
#15     runZoned (dart:async/zone.dart:1550:10)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.22.4 at C:\Fluttter\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Acer\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Users\Acer\New folder\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Acer\New folder
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Acer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.0

[✓] Connected device (1 available)
    • TA 1000 (mobile) • D1CGAPE740501898 • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
device_info-0.4.2+7
devicelocale-0.3.1
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
firebase_storage-3.1.6
flutter_contact-0.6.4
flutter_native_timezone-1.0.4
flutter_plugin_android_lifecycle-1.0.8
geolocator-6.1.12
get_ip-0.4.0
google_maps_flutter-1.0.6
image_picker-0.6.7+7
libphonenumber-1.0.1
permission_handler-5.0.1+1
url_launcher-5.7.2
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+1

**Comment by iapicca** [comment] 2020-12-08 15:22
possible duplicate of https://github.com/flutter/flutter/issues/69116

**Comment by pedromassangocode** [comment] 2020-12-09 07:06
Duplicate of https://github.com/flutter/flutter/issues/69116

**Closed by pedromassangocode** 2020-12-09 07:06 UTC
