### ISSUE TITLE
 ~500ms spent in the Flutter UI thread before rendering the first Dream frame

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#35009] opened 2019-06-24 16:45 UTC
Mirror issue for [this internal bug](https://b.corp.google.com/issues/135134294). Conversation should occur there. 

cc @cbracken, to whom the issue is currently assigned.

**Comment by liyuqian** [comment] 2019-07-03 16:39
This may be a duplicate of https://github.com/flutter/flutter/issues/19350

**Comment by Hixie** [comment] 2019-07-16 00:28
This has been resolved.

**Closed by Hixie** 2019-07-16 00:28 UTC
Labels: customer: dream (g3), engine, severe: customer blocker, severe: performance, waiting for customer response
