### ISSUE TITLE
NoSuchMethodError: The getter 'className' was called on null.

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19347] opened 2018-07-13 17:15 UTC
So I created a custom class and I'm trying to build it with data from Firebase.

I get a Map<dynamic> from firebase and tease it apart with .map() and returning Lists instances of class SocialLink (working merely as a struct).

here's the code

```dart
void onProjectValue(void callback(List<Project> projects)){
    this.dbRef.child('threads').limitToLast(40).onValue.listen((Event event){
      List<Project> projects = [];
      Map result = event.snapshot.value;

      result.forEach((id, projectData){
        projects.add(
          new Project(
            id: int.parse(id),
            title: projectData['thread-scrape']['subject'],
            iconUrl: 'http://192.168.1.120:8080/services/twitter.png',
            tags: projectData['thread-scrape']['tags'].values.map<String>( (value){
              return '$value';
            }).toList(),  // does this work? yes
            links: projectData['links-scrape'].entries.map<SocialLink>( (entry)=>
              SocialLink(
                iconUrl: this.socialUrls[entry.key], 
                linkUrl: entry.value
              )).toList(), // does this work? no!
            views: projectData['thread-scrape']['views']

          )
        );
      }); 

      return callback(projects);
    });
  }
```

Problem is I get this error (stack trace)

```
Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.
CADisplay.name = LCD;
CADisplay.deviceName = PurpleMain;
CADisplay.seed = 1;
tags = 0;
currentMode = <FBSDisplayMode: 0x60c000097700; 375x812@3x (1125x2436/3) 60Hz p3 SDR>;
safeOverscanRatio = {0.89999997615814209, 0.89999997615814209};
nativeCenter = {562.5, 1218};
pixelSize = {1125, 2436};
bounds = {{0, 0}, {375, 812}};
CADisplay = <CADisplay:LCD PurpleMain>;
}
5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[1.1 69498871-3F7C-4F0A-AFCD-4581EDF0C1ED 192.168.1.120.58897<->172.217.3.106:443]
Connected Path: satisfied (Path is satisfied), interface: en1
Duration: 0.281s, DNS @0.001s took 0.040s, TCP @0.043s took 0.044s, TLS took 0.114s
bytes in/out: 3579/1061, packets in/out: 9/10, rtt: 0.043s, retransmitted packets: 0, out-of-order packets: 0
5.4.0 - [Firebase/Core][I-COR000004] App with name when-coin-test does not exist.
[2.1 32DB1D89-B138-4B98-A6D9-B68CC8652D59 192.168.1.120.58905<->172.217.12.138:443]
Connected Path: satisfied (Path is satisfied), interface: en1
Duration: 0.270s, DNS @0.000s took 0.018s, TCP @0.024s took 0.049s, TLS took 0.129s
bytes in/out: 3337/1061, packets in/out: 9/10, rtt: 0.046s, retransmitted packets: 0, out-of-order packets: 0
flutter: connected!
flutter: {Telegram: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Ftelegram.png?alt=media&token=dbbd043f-05db-45ca-b00d-50edfe763f95, Medium: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fmedium.png?alt=media&token=15267fc3-f112-4fa1-9e6c-facbe787e68d, YouTube: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fyoutube.png?alt=media&token=4de33db4-ec85-47d0-9a9e-952479bdb761, GitHub: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fgithub.png?alt=media&token=403440df-65e3-4c1b-8ac8-a8bed7ea2f4c, Steemit: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fsteemit.png?alt=media&token=308f7f2d-0120-454d-b2f7-415d13f57106, Slack: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fslack.png?alt=media&token=6dfa1b2b-33a5-4820-a167-05d25e9c743a, Facebook: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/<…>
compiler message: Unhandled exception:
compiler message: NoSuchMethodError: The getter 'className' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: className
compiler message: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
compiler message: #1      serializeProcedure (package:front_end/src/fasta/kernel/utils.dart:82:29)
compiler message: #2      FrontendCompiler.compileExpression (package:vm/frontend_server.dart:452:16)
compiler message: <asynchronous suspension>
compiler message: #3      _FlutterFrontendCompiler.compileExpression (package:frontend_server/server.dart:55:22)
compiler message: #4      listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:650:20)
compiler message: <asynchronous suspension>
compiler message: #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
compiler message: #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
compiler message: #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
compiler message: #8      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
compiler message: #9      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
compiler message: #10     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
compiler message: #11     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
compiler message: #12     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
compiler message: #13     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
compiler message: #14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
compiler message: #15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
compiler message: #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
compiler message: #17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
compiler message: #18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
compiler message: #19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
compiler message: #20     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
compiler message: #21     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
compiler message: #22     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
compiler message: #23     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
compiler message: #24     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
compiler message: #25     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
compiler message: #26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
compiler message: #27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
compiler message: #28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
compiler message: #29     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
compiler message: #30     _StreamController._add (dart:async/stream_controller.dart:639:7)
compiler message: #31     _StreamController.add (dart:async/stream_controller.dart:585:5)
compiler message: #32     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
compiler message: #33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
compiler message: #34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
compiler message: #35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
compiler message: #36     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
compiler message: #37     _StreamController._add (dart:async/stream_controller.dart:639:7)
compiler message: #38     _StreamController.add (dart:async/stream_controller.dart:585:5)
compiler message: #39     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
compiler message: #40     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
compiler message: #41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
compiler message: #42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
compiler message: #43     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
compiler message: #44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
Exited (255)
```

**Comment by lukepighetti** [comment] 2018-07-13 17:17
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.7-pre.111, on Mac OS X 10.13.5 17F77, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✗] Android Studio (not installed)
[✓] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
```

**Comment by lukepighetti** [comment] 2018-07-13 17:39
I tried refactoring to a .forEach loop and I got the same errors. Perhaps the .map() has nothing to do with it... I shall dig further

**Comment by lukepighetti** [comment] 2018-07-13 17:42
Oh, I have been getting this error every other time I try to build the app (for debug), I don't know if it's related.

```
Launching lib/main.dart on iPhone X in debug mode...
Exit code 3 from: /usr/bin/xcrun simctl launch 97AC0229-A8BD-4704-B61F-DF517A59EEC0 com.if-then.when-coin --enable-dart-profiling --enable-checked-mode --start-paused --observatory-port=0:
com.if-then.when-coin: -1
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=3):
The request to open "com.if-then.when-coin" failed.
The process did launch, but has since exited or crashed.
Error launching application on iPhone X.
Exited (sigterm)
```

**Comment by lukepighetti** [comment] 2018-07-13 18:18
Same error on Beta channel

```
Launching lib/main.dart on iPhone X in debug mode...
CADisplay.name = LCD;
CADisplay.deviceName = PurpleMain;
CADisplay.seed = 1;
tags = 0;
currentMode = <FBSDisplayMode: 0x600000092480; 375x812@3x (1125x2436/3) 60Hz p3 SDR>;
safeOverscanRatio = {0.89999997615814209, 0.89999997615814209};
nativeCenter = {562.5, 1218};
pixelSize = {1125, 2436};
bounds = {{0, 0}, {375, 812}};
CADisplay = <CADisplay:LCD PurpleMain>;
}
5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[1.1 3FD0335B-CE17-41F1-95ED-E84191D82ED9 192.168.1.120.59601<->172.217.12.170:443]
Connected Path: satisfied (Path is satisfied), interface: en1
Duration: 0.287s, DNS @0.003s took 0.040s, TCP @0.045s took 0.044s, TLS took 0.114s
bytes in/out: 3554/1015, packets in/out: 9/9, rtt: 0.044s, retransmitted packets: 0, out-of-order packets: 0
5.4.0 - [Firebase/Core][I-COR000004] App with name when-coin-test does not exist.
[2.1 F86FC52A-B8EB-4B15-921F-1C6CFBF6FFEE 192.168.1.120.59611<->172.217.12.202:443]
Connected Path: satisfied (Path is satisfied), interface: en1
Duration: 0.244s, DNS @0.003s took 0.012s, TCP @0.015s took 0.046s, TLS took 0.117s
bytes in/out: 3699/1060, packets in/out: 9/10, rtt: 0.044s, retransmitted packets: 0, out-of-order packets: 0
flutter: connected!
flutter: {GitHub: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fgithub.png?alt=media&token=403440df-65e3-4c1b-8ac8-a8bed7ea2f4c, Steemit: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fsteemit.png?alt=media&token=308f7f2d-0120-454d-b2f7-415d13f57106, Slack: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fslack.png?alt=media&token=6dfa1b2b-33a5-4820-a167-05d25e9c743a, ANN: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fann.png?alt=media&token=8716d4ef-5fed-44e2-b9c3-056d40a35705, YouTube: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fyoutube.png?alt=media&token=4de33db4-ec85-47d0-9a9e-952479bdb761, Medium: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fmedium.png?alt=media&token=15267fc3-f112-4fa1-9e6c-facbe787e68d, Reddit: https://firebasestorage.googleapis.com/v0/b/when-coin-test.appspot.com/o/img%2Fredd<…>
[4.1 29D890A7-D5BA-484E-A8E4-770D6CBE29D7 192.168.1.120.59613<->172.217.12.202:443]
Connected Path: satisfied (Path is satisfied), interface: en1
Duration: 62.382s, DNS @0.004s took 0.034s, TCP @0.040s took 0.044s, TLS took 0.115s
bytes in/out: 12686/1966, packets in/out: 46/24, rtt: 0.048s, retransmitted packets: 0, out-of-order packets: 0

```

<img width="1075" alt="screen shot 2018-07-13 at 2 18 04 pm" src="https://user-images.githubusercontent.com/666539/42707261-a14f9f16-86a7-11e8-9a00-09008c0203d5.png">

```
Lukes-iMac:when_coin lukepighetti$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✗] Android Studio (not installed)
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

! Doctor found issues in 3 categories.
```

**Comment by lukepighetti** [comment] 2018-07-13 18:20
I just so happened to be watching this expression and this is an interesting clue that was not available anywhere else...

<img width="1468" alt="screen shot 2018-07-13 at 2 19 39 pm" src="https://user-images.githubusercontent.com/666539/42707328-d53c4914-86a7-11e8-98f3-79960014cade.png">

**Comment by lukepighetti** [comment] 2018-07-13 18:20
```
Unhandled exception:
NoSuchMethodError: The getter 'firebase' was called on null.
Receiver: null
Tried calling: firebase
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      Object.Eval (evaluate:source:1:17)
```

**Comment by lukepighetti** [comment] 2018-07-13 18:34
OK I found the error.

Basically I was trying to call `myAwesomeMap['myAwesomeKey'].values` on a map without `myAwesomeKey`. For some reason the error/stack trace wasn't very useful but this can be closed I think. ?

**Comment by fuzzybinary** [comment] 2018-08-28 19:56
I'm encountered a similar error without firebase using JsonSerializer. It appears an attempt to as cast a Map to a String caused the error, but it doesn't happen in simple examples.

I got the stack trace in the first post with 'className called on null'.
Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)
```

**Comment by zoechi** [comment] 2018-08-29 07:00
The stack trace really is all but helpful.
A reproduction would be great.

**Comment by fuzzybinary** [comment] 2018-08-29 15:07
Hi @zoechi -

This commit can duplicate this issue, but I couldn't find simpler code to do so:
https://github.com/fuzzybinary/flutterdon/tree/85d94c5e650cd8f38a2a66cc76000880f0440db9

My STR are for Visual Studio Code but I don't think this is a VSCode issue

1. Start debugging
1. Make sure you're on the "debug" tab in VSCode
1. Log in to a mastodon instance  / authorize the app
1. Crash - VSCode disconnects

The offending line here is the code generated because of this line:
https://github.com/fuzzybinary/flutterdon/blob/85d94c5e650cd8f38a2a66cc76000880f0440db9/lib/mastodon/models.dart#L67

This should be a Toot, and the attempt to cast from Map<String, dynamic> to String does throw the proper cast error that *can* be caught be VSCode before you get the above stack trace if you're not in the debug tab.

**Comment by zoechi** [comment] 2018-08-31 18:27
@fuzzybinary I don't have a mastodon instance or account

**Comment by fuzzybinary** [comment] 2018-08-31 23:44
@zoechi Most prevelent instance is https://mastodon.social/ Or you could use https://instances.social/ to find an instance you like better.

**Comment by vijaykanta** [comment] 2019-01-11 03:03
I was having a similar issue with no idea how to fix as the log didn't give any indication whatsoever. The basic issue was the http.post() call fails, and I had no clue what the source was until I saw this topic and @lukepighetti answer that the String conversion from Map<> fails. So, I print the dictionary items and yes, one of them had a value of "null" in iOS (but not on Android). I solved it.

**Comment by zoechi** [comment] 2019-02-14 18:19
Are you still seeing this in Flutter `master` channel?

**Comment by l-k22** [comment] 2019-02-15 10:51
I'm suddenly having this issue, the app builds and install but just displays a white screen.
The first error I got was because an exception couldn't be cast to string eg
```
print('Error: ') + e; 
//this never caused issue before changed to 
print('Error: ${e.toString}');
```

now I'm getting an error else where in the app 
`Unhandled Exception: NoSuchMethodError: The getter 'isNotEmpty' was called on null.`

I can tell already this is going to be a long day :(

**Comment by zoechi** [comment] 2019-02-15 10:53
@l-k22 please post the output of `flutter doctor -v`

**Comment by l-k22** [comment] 2019-02-15 10:57
> @l-k22 please post the output of `flutter doctor -v`
If it's helpful the app was working before but recently I needed to setup OneSignal background notifications, I updated my compileSDKversion to 28, would this be related to AndroidX?

Here is the output

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.14.2 18C54, locale en-GB)
    • Flutter version 1.2.0 at /Users/xxxx/Documents/Programming/flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.rc.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (2 available)
    • ASUS X00TD               • xxxxxxxxxxxx                          • android-arm64 • Android 8.1.0 (API 27)
    • BSAVA Developer’s iPhone • xxxxxxxxxxxxxxxxxxxxxxxx • ios           • iOS 12.1.4

• No issues found!
```

**Comment by zoechi** [comment] 2019-02-15 11:00
Your error seems unrelated to this issue. Please create a new issue with a minimal reproduction project.

**Comment by l-k22** [comment] 2019-02-15 11:03
Ok, it's probably something I've done.I'll do more investigating then post an issue if need be.

**Comment by fuzzybinary** [comment] 2019-02-15 15:59
Can confirm that this is fixed in flutter master channel and debugging works correctly.

**Comment by zoechi** [comment] 2019-02-15 17:05
@fuzzybinary thanks for the update. Closing then.
@lukepighetti just add a comment if you're still seeing this and I'll reopen.

**Closed by zoechi** 2019-02-15 17:05 UTC
Labels: p: firebase, p: first party, plugin, severe: crash, waiting for PR to land (fixed), waiting for customer response

**Comment by kroikie** [comment] 2019-10-13 19:01
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/756. Any further collaboration will be done there.
