### ISSUE TITLE
When StatefulWidget is used instead of StatelessWidget, the build() method is called more often when navigating

### ISSUE THREAD

**Issue by FrantisekGazo** [flutter/flutter#42361] opened 2019-10-09 21:36 UTC
## Steps to Reproduce
I prepared 2 versions of the same code - first uses `StatefullWidget`s and the second `StatelessWidget`s for pages. 

STATEFULL version:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build MyApp');
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Page1(),
    );
  }
}

class Page1 extends StatefulWidget {
  @override
  _Page1State createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  @override
  Widget build(BuildContext context) {
    print('build Page 1');
    return WillPopScope(
      onWillPop: () async {
        print('Back pressed on Page 1');
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text('Page 1'),
        ),
        body: Center(
          child: RaisedButton(
            child: Text('Go to Page2'),
            onPressed: () {
              print('Go to Page 2 pressed');
              Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (context) => Page2(),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatefulWidget {
  @override
  _Page2State createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  @override
  Widget build(BuildContext context) {
    print('build Page 2');
    return WillPopScope(
      onWillPop: () async {
        print('Back pressed on Page 2');
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text('Page 2'),
        ),
        body: Center(
          child: RaisedButton(
            child: Text('Go to Page 3'),
            onPressed: () {
              print('Go to Page 3 pressed');
              Navigator.of(context).pushAndRemoveUntil(
                MaterialPageRoute(
                  builder: (context) => Page3(),
                ),
                (route) => true,
              );
            },
          ),
        ),
      ),
    );
  }
}

class Page3 extends StatefulWidget {
  @override
  _Page3State createState() => _Page3State();
}

class _Page3State extends State<Page3> {
  @override
  Widget build(BuildContext context) {
    print('build Page 3');
    return WillPopScope(
      onWillPop: () async {
        print('Back pressed on Page 3');
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text('Page 3'),
        ),
        body: Container(),
      ),
    );
  }
}

```
vs 
STATELESS version:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build MyApp');
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Page1(),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build Page 1');
    return WillPopScope(
      onWillPop: () async {
        print('Back pressed on Page 1');
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text('Page 1'),
        ),
        body: Center(
          child: RaisedButton(
            child: Text('Go to Page2'),
            onPressed: () {
              print('Go to Page 2 pressed');
              Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (context) => Page2(),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build Page 2');
    return WillPopScope(
      onWillPop: () async {
        print('Back pressed on Page 2');
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text('Page 2'),
        ),
        body: Center(
          child: RaisedButton(
            child: Text('Go to Page 3'),
            onPressed: () {
              print('Go to Page 3 pressed');
              Navigator.of(context).pushAndRemoveUntil(
                MaterialPageRoute(
                  builder: (context) => Page3(),
                ),
                (route) => true,
              );
            },
          ),
        ),
      ),
    );
  }
}

class Page3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build Page 3');
    return WillPopScope(
      onWillPop: () async {
        print('Back pressed on Page 3');
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text('Page 3'),
        ),
        body: Container(),
      ),
    );
  }
}
```

Run these steps for both versions:
1. Start app (Page1 will show).
2. Navigate to Page2 by pressing "Go to Page 2" on Page1 button.
3. Navigate to Page3 by pressing "Go to Page 3" on Page2 button.
4. Navigate back to Page2 by pressing back button.
5. Navigate back to Page1 by pressing back button.

See the difference in logs:
STATEFULL version:
```
I/flutter ( 4268): build MyApp
I/flutter ( 4268): build Page 1
I/flutter ( 4268): Go to Page 2 pressed
I/flutter ( 4268): build Page 2
I/flutter ( 4268): build Page 1
I/flutter ( 4268): Go to Page 3 pressed
I/flutter ( 4268): build Page 3
I/flutter ( 4268): build Page 2
I/flutter ( 4268): build Page 1
I/flutter ( 4268): Back pressed on Page 3
I/flutter ( 4268): build Page 2
I/flutter ( 4268): build Page 1
I/flutter ( 4268): Back pressed on Page 2
I/flutter ( 4268): build Page 1
```

STATELESS version:
```
I/flutter ( 4268): build MyApp
I/flutter ( 4268): build Page 1
I/flutter ( 4268): Go to Page 2 pressed
I/flutter ( 4268): build Page 2
I/flutter ( 4268): Go to Page 3 pressed
I/flutter ( 4268): build Page 3
I/flutter ( 4268): Back pressed on Page 3
I/flutter ( 4268): Back pressed on Page 2
```

**Target Platform: Android**
**Target OS version/browser: Android 8.1, Android 9**
**Devices: emulator and also physical device**

## Logs

```
flutter analyze
Analyzing flutter_test_app...                                           
No issues found! (ran in 2.0s)

```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/franky/CODE/flutter-sdk
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/franky/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/franky/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by tmulin** [comment] 2019-12-06 07:58
Got the same problem when using  MaterialPageRoute and CupertinoPageRoute . 
But when use PageRouteBuilder as show below, it works .

`
PageRouteBuilder(
        opaque: false,
        transitionDuration: Duration(milliseconds: 300),
        pageBuilder: (BuildContext context, Animation<double> animation,
            Animation<double> secondaryAnimation) {
          return child;
        },
        transitionsBuilder: (BuildContext context, Animation<double> animation,
            Animation<double> secondaryAnimation, Widget child) {
          var begin = Offset(1.0, 0.0);
          var end = Offset.zero;
          var tween = Tween(begin: begin, end: end);
          var offsetAnimation = animation.drive(tween);

          return SlideTransition(
            position: offsetAnimation,
            child: child,
          );
        })
`

**Comment by csells** [comment] 2020-01-13 20:03
@FrantisekGazo the build() method can be called arbitrarily many times by design. Is the number of times that it's called causing you some trouble?

**Comment by FrantisekGazo** [comment] 2020-01-25 19:52
Currently I'm not aware of any issue. I was more curious why is it so.

**Comment by VladyslavBondarenko** [comment] 2020-07-14 12:51
With current master `1.20.0-8.0.pre.75` I can see the same for Stateful and Stateless widgets - they aren't rebuilt on navigating how it was about STATEFULL version:

```
I/flutter ( 4193): build MyApp
I/flutter ( 4193): build Page 1
I/flutter ( 4193): build MyApp
I/flutter ( 4193): build Page 1
I/flutter ( 4193): Go to Page 2 pressed
I/flutter ( 4193): build Page 2
I/flutter ( 4193): Go to Page 3 pressed
I/flutter ( 4193): build Page 3
I/flutter ( 4193): Back pressed on Page 3
I/flutter ( 4193): Back pressed on Page 2
```

Closing since initial issue seems to be fixed

**Closed by VladyslavBondarenko** 2020-07-14 12:51 UTC
Labels: f: routes, framework
