### ISSUE TITLE
Flutter doctor fails continuously

### ISSUE THREAD

**Issue by luccasclezar** [flutter/flutter#15075] opened 2018-03-02 17:28 UTC
## Steps to Reproduce

Run `flutter doctor` after downloading flutter.

## Logs

None, it's failing on doctor.

## Flutter Doctor

Updating flutter tool...
FINE: Pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
IO  : Spawning "cmd /c ver" in C:\flutter\packages\flutter_tools\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [versÃ£o 10.0.16299.248]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - coverage 0.10.0 from hosted (coverage)
    | - test 0.12.30+3 from hosted (test)
    | - file 2.3.6 from hosted (file)
    | - mustache 1.0.0 from hosted (mustache)
    | - meta 1.1.2 from hosted (meta)
    | - web_socket_channel 1.0.7 from hosted (web_socket_channel)
    | - http 0.11.3+16 from hosted (http)
    | - xml 2.6.0 from hosted (xml)
    | - json_rpc_2 2.0.7 from hosted (json_rpc_2)
    | - stream_channel 1.6.3 from hosted (stream_channel)
    | - process 2.0.7 from hosted (process)
    | - vm_service_client 0.2.4+1 from hosted (vm_service_client)
    | - front_end any from hosted (front_end)
    | - linter 0.1.43 from hosted (linter)
    | - quiver 0.28.0 from hosted (quiver)
    | - args 1.3.0 from hosted (args)
    | - package_config 1.0.3 from hosted (package_config)
    | - crypto 2.0.2+1 from hosted (crypto)
    | - platform 2.1.2 from hosted (platform)
    | - plugin 0.2.0+2 from hosted (plugin)
    | - stack_trace 1.9.1 from hosted (stack_trace)
    | - usage 3.3.0 from hosted (usage)
    | - intl 0.15.2 from hosted (intl)
    | - archive 1.0.33 from hosted (archive)
    | - cli_util 0.1.2+1 from hosted (cli_util)
    | - json_schema 1.0.8 from hosted (json_schema)
    | - yaml 2.1.13 from hosted (yaml)
    | - analyzer any from hosted (analyzer)
IO  : Get versions from https://pub.dartlang.org/api/packages/coverage.
IO  : HTTP GET https://pub.dartlang.org/api/packages/coverage
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: upgrade
    | X-Pub-Session-ID: 4536270E-0F24-47AF-975D-67B3DAA7A98C
    | X-Pub-Environment: :flutter_install
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

This gets looped continuously.

**Comment by luccasclezar** [comment] 2018-03-02 17:34
Only now I noticed it's the same error as #14959.

**Comment by mraleph** [comment] 2018-03-02 18:06
Duplicate of #14959 

Please let me know if you would be willing to run a debugging session for us - so far we were not able to reproduce this issue locally.

**Closed by mraleph** 2018-03-02 18:06 UTC
