### ISSUE TITLE
Google Map authorization failure

### ISSUE THREAD

**Issue by dhruvanwd** [flutter/flutter#25803] opened 2018-12-27 05:49 UTC
I/DynamiteModule( 4290): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:220
I/DynamiteModule( 4290): Selected remote version of com.google.android.gms.maps_dynamite, version >= 220
W/ResourcesManager( 4290): Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
W/ResourcesManager( 4290): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
W/art     ( 4290): Suspending all threads took: 24.880ms
I/Google Maps Android API( 4290): Google Play services client version: 12451000
I/art     ( 4290): Background partial concurrent mark sweep GC freed 1577(135KB) AllocSpace objects, 0(0B) LOS objects, 51% free, 953KB/1977KB, paused 32.541ms total 182.526ms
I/Google Maps Android API( 4290): Google Play services package version: 13280013
E/Google Maps Android API( 4290): Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
E/Google Maps Android API( 4290): In the Google Developer Console (https://console.developers.google.com)
E/Google Maps Android API( 4290): Ensure that the "Google Maps Android API v2" is enabled.
E/Google Maps Android API( 4290): Ensure that the following Android Key exists:
E/Google Maps Android API( 4290):       API Key: AxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxE
E/Google Maps Android API( 4290):       Android Application (<cert_fingerprint>;<package_name>): 38:B6:60:6F:54:6B:87:B5:08:A6:37:2D:B7:5A:00:45:DD:16:CA:94;com.example.invites
W/DynamiteModule( 4290): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 4290): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule( 4290): Selected remote version of com.google.android.gms.googlecertificates, version >= 4

**Comment by zoechi** [comment] 2018-12-27 08:50
Duplicate of #25021

**Closed by zoechi** 2018-12-27 08:50 UTC
