### ISSUE TITLE
[image_picker][iOS] Selecting "Use Video" on iOS after recording video sometimes causes dialog to be closed image_picker is used in.

### ISSUE THREAD

**Issue by TheLeaf-code** [flutter/flutter#91165] opened 2021-10-02 18:11 UTC
Sometimes if the user records a video with image_picker then selects "Use Video", we have been noticing that the dialog we call ImagePicker() in is also closed.
## Steps to Reproduce
1. Run `flutter create bug`.
2. Update the files as follows:

**main.dart:**
```
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  openDialog(BuildContext context) {
    showDialog(context: context, builder: (BuildContext context) {
      return Dialog(child:
          Center(
            child: Column(children: [
              ElevatedButton(
                onPressed: () async {
                  await ImagePicker().pickVideo(source: ImageSource.camera);
                },
                child: Text("record video"),
              ),
              ElevatedButton(
                onPressed: Navigator.of(context).pop,
                child: Text("exit"),
              )
            ],),
          )
      );
    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () {openDialog(context);},
              child: Text("Open dialog"),
            ),
          ],
        ),
      ),
    );
  }
}
```
**pubspec.yaml:**
```
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+2
```
Then run `flutter pub get` and `pod install`

**info.plist:**
Add these two keys to info.plist:
```
<key>NSMicrophoneUsageDescription</key>
<string>to record audio</string>

<key>NSCameraUsageDescription</key>
<string>to upload videos</string>
```
_As this issue is only on iOS, I am not showing setup for Android._
1. press the "Open dialog" button
2. press "record video" in the opened dialog
3. record a video and select "use video"

Keep in mind that this bug is not occurring every time ImagePicker is being used, it may take a couple tries to close the dialog.

<details>
  <summary>Logs</summary>

```
[ +184 ms] Successfully connected to service protocol: http://127.0.0.1:61602/
[  +70 ms] DevFS: Creating new filesystem on the device (null)
[  +39 ms] DevFS: Created new filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/3732C74E-1AF3-46F0-81BB-637D460DB115/tmp/flutter_image_picker_bugzVmblZ/flutter_image_picker_bug/)
[   +5 ms] Updating assets
[ +527 ms] Syncing files to device Charles’s iPhone...
[   +4 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +8 ms] <- recompile package:flutter_image_picker_bug/main.dart 6de6402f-b839-47d4-8ef4-880fe77237b1
[        ] <- 6de6402f-b839-47d4-8ef4-880fe77237b1
[+1111 ms] Updating files.
[   +7 ms] DevFS: Sync finished
[   +9 ms] Syncing files to device Charles’s iPhone... (completed in 1,136ms)
[   +3 ms] Synced 0.0MB.
[   +7 ms] <- accept
[  +12 ms] DevTools activation throttled until 2021-10-02 23:07:12.938700.
[  +93 ms] Connected to _flutterView/0x135033620.
[  +85 ms] Flutter run key commands.
[  +18 ms] r Hot reload. 🔥🔥🔥
[   +6 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[   +3 ms] q Quit (terminate the application on the device).
[   +9 ms] 💪 Running with sound null safety 💪
[   +8 ms] An Observatory debugger and profiler on Charles’s iPhone is available at: http://127.0.0.1:61605/-3_skFds6gw=/
[+2229 ms] The Flutter DevTools debugger and profiler on Charles’s iPhone is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:61605/-3_skFds6gw=/
[+15494 ms] [Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
[  +38 ms] [Snapshotting] Snapshotting a view (0x133b64d60, CAMPreviewView) that has not been rendered at least once requires afterScreenUpdates:YES.
[+3584 ms] [Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
[  +16 ms] [Snapshotting] Snapshotting a view (0x133a78040, CAMPreviewView) that has not been rendered at least once requires afterScreenUpdates:YES.
[+3060 ms] [Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
[  +18 ms] [Snapshotting] Snapshotting a view (0x133823e90, CAMPreviewView) that has not been rendered at least once requires afterScreenUpdates:YES.
[+2291 ms] [Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
[   +6 ms] [Snapshotting] Snapshotting a view (0x133b64d60, CAMPreviewView) that has not been rendered at least once requires afterScreenUpdates:YES.
```

**futter analyze:**
```
Analyzing flutter_image_picker_bug...                                   
No issues found! (ran in 7.4s)

```

**flutter doctor -v:**

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.5.2 at /Users/Chuck/Documents/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Chuck/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.7792

[✓] VS Code (version 1.60.0)
    • VS Code at /Users/Chuck/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available
```

</details>

This my first issue I am posting on GitHub, so if there is anything I can clarify let me know. Thank you.

**Comment by TahaTesser** [comment] 2021-10-04 10:25
Hi @TheLeaf-code 
Dialog is getting closed because somehow the user is tapping on the edges, widgets receive touch events even when the camera is on top, see https://github.com/flutter/flutter/issues/28335 and https://github.com/flutter/flutter/issues/14720.

I can reproduce this every time by tapping outside the dialog area from the camera overlay. 

https://user-images.githubusercontent.com/48603081/135835274-f3155b2d-a747-4521-8f9f-e75b55b6219e.mov



Closing as duplicate of https://github.com/flutter/flutter/issues/28335

**Closed by TahaTesser** 2021-10-04 10:25 UTC
Labels: in triage
