### ISSUE TITLE
GestureDetector not honouring behaviour in horizontal dragging with HitTestBehaviour.translucent

### ISSUE THREAD

**Issue by proformance** [flutter/flutter#83271] opened 2021-05-24 17:27 UTC
It seems the GestureDetector is not forward horizontal dragging to children or widgets visually behind them no matter what behaviour is set.

# Problem
```
GestureDetector(
  behavior: HitTestBehavior.translucent,  
  onHorizontalDragUpdate: (details) {
    print('parent update');
  },
  child: GestureDetector(
    onHorizontalDragUpdate: (details) {
      print('child update');
    },
    behavior: HitTestBehavior.translucent,
    child: Container(
      height: 40,
      width: 300,
      color: Colors.yellow,
      child: Text('Item'),
    ),
  ),
),
```

**Expected results:**
I expect both 'parent update' and 'child update' to be printed when dragging horizontally

**Actual results:** 
Only 'child update' is being printed when dragging horizontally

# Another way to visualise the problem:

```
Stack(
  children: [
    Container(
      child: GestureDetector(
        onHorizontalDragUpdate: (details) {
          print('child update');
        },
        behavior: HitTestBehavior.translucent,
        child: Container(
          height: 40,
          width: 300,
          color: Colors.pink,
          child: Text(item.value.text),
        ),
      ),
    ),
    Positioned.fill(
      child: GestureDetector(
        behavior: HitTestBehavior.translucent,
        onHorizontalDragUpdate: (details) {
          print('parent update');
        },
      ),
    ),
  ],
)
```

**Expected results:**
I expect both 'parent update' and 'child update' to be printed when dragging horizontally

**Actual results:** 
Only 'parent update' is being printed when dragging horizontally

flutter doctor -v
```
flutter doctor -v
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-12.2.pre at /Users/##/dev/flutter
    • Framework revision 5bedb7b1d5 (10 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/###/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-05-25 12:11
Hi @proformance 
It's not just `onHorizontalDragUpdate` but double-tap or on tap.  They all only print child widget events. 


Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Stack(
            children: [
              Positioned.fill(
                child: GestureDetector(
                  behavior: HitTestBehavior.translucent,
                  onTap: () => print('parent tap'),
                  onHorizontalDragUpdate: (details) {
                    print('parent update');
                  },
                  child: Container(
                    height: 40,
                    width: 300,
                    color: Colors.yellow,
                    child: Text('Text'),
                  ),
                ),
              ),
              Container(
                child: GestureDetector(
                  onTap: () => print('child tap'),
                  onHorizontalDragUpdate: (details) {
                    print('child update');
                  },
                  behavior: HitTestBehavior.translucent,
                  child: Container(
                    height: 40,
                    width: 300,
                    color: Colors.pink,
                    child: Text('Text'),
                  ),
                ),
              ),
            ],
          ),
        ));
  }
}

``` 

</details>

This is a duplicate of https://github.com/flutter/flutter/issues/18450  https://github.com/flutter/flutter/issues/74733

**Closed by TahaTesser** 2021-05-25 12:11 UTC
Labels: in triage
