### ISSUE TITLE
The SystemUiOverlayStyle for status bar doesn't get the right brightness on iOS.

### ISSUE THREAD

**Issue by jiajiabingcheng** [flutter/flutter#12960] opened 2017-11-10 00:53 UTC
I found an issue that the if I build a scaffold widget on top of another Scaffold widget, the SystemUiOverlayStyle doesn't get the new brightness from it's appbar setting. It actually shows as the based Scaffold widget.

I created a widget with ThemeData.primaryColorBrightness == Brightness.dark like below:
```
// The first scaffold
new Scaffold(
    body: new InkWell(
        onTap: () =>
            Navigator.push(
                context, new MaterialPageRoute(builder: (context) =>
           // the second Scaffold
            new Scaffold(
                appBar: new AppBar(backgroundColor: Colors.white,
                    brightness: Brightness.light))))
    )
);
```
Since I set the brightness for the second scaffold appbar to light, it should build with black as the text color for the system status bar. But it didn't, instead, it still use white text as the first Scaffold.

If I create a statefulWidget for the second Scaffold, it doesn't work only for the first build. But when this widget gets rebuild, the text changed to black in the status bar.

**Comment by Hixie** [comment] 2017-11-14 23:27
There's probably a race condition where different widgets are fighting to get the color set.

**Comment by Hixie** [comment] 2017-11-14 23:28
In due course this will be fixed by https://github.com/flutter/flutter/issues/4630.

**Comment by Hixie** [comment] 2018-05-21 21:16
Closing as a dupe of #4630 since we're working on that now.

**Closed by Hixie** 2018-05-21 21:16 UTC
