### ISSUE TITLE
[Web] Multibyte characters are displayed incorrectly when TextField goes multiline

### ISSUE THREAD

**Issue by takinok** [flutter/flutter#98817] opened 2022-02-20 04:30 UTC
## Explanation of the issue

The display of multibyte characters is incorrect when the lines is expanded in a text field.
This issue has been present since version 2.8.1.
This issue is a serious issue in countries that use multibyte characters, so please take action as soon as possible.

**Expected results:** 
![animation_02](https://user-images.githubusercontent.com/49100289/154828396-dcc47886-4d94-4e96-af3b-2654c4d1ad47.gif)

**Actual results:** 
![animation_01](https://user-images.githubusercontent.com/49100289/154828402-335c3c5a-55de-4114-99e5-216593977e82.gif)

<details>
<summary>Code sample</summary>

Success Case
```dart
  SizedBox(
                width: 300,
                child: TextField(
                  keyboardType: TextInputType.multiline,
                  controller: ctrller,
                  maxLines: 3,
                  decoration: const InputDecoration(
                    filled: true,
                    border: OutlineInputBorder(),
                  ),
                ),
              ),
```

Error Case

```dart
  SizedBox(
                width: 300,
                child: TextField(
                  keyboardType: TextInputType.multiline,
                  controller: ctrller,
                  maxLines: null,　// <- In this case, if new line is needed, the line of textfield is expanded.
                  decoration: const InputDecoration(
                    filled: true,
                    border: OutlineInputBorder(),
                  ),
                ),
              ),
```

</details>

<details>
  <summary>Logs</summary>

```
D:\github\test02>flutter doctor -v
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19042.1526], locale ja-JP)
    • Flutter version 2.10.1 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (10 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\takur\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\takur\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\takur\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment] 2022-02-21 11:54
Hi @takinok, Thanks for filing the issue, If I understand correctly when the textfield goes multiline the text is displayed incorrectly, is that correct? 

Could you please specify what language keyboard do I need to use to reproduce the issue along with the English keys that I need to press to reproduce the issue? It would be great if you can be more precise with reproducible steps and share the expected and actual output in a textual form.

**Comment by takinok** [comment] 2022-02-24 14:09
Hi @maheshmnj , Thank you for your comment. And sorry for my late response.

> Hi @takinok, Thanks for filing the issue, If I understand correctly when the textfield goes multiline the text is displayed incorrectly, is that correct?
> 
Yes, correct.

> Could you please specify what language keyboard do I need to use to reproduce the issue along with the English keys that I need to press to reproduce the issue? It would be great if you can be more precise with reproducible steps and share the expected and actual output in a textual form.

I'm using the Japanese keyboard and MS Japanase IME.
In Japanese "テスト"  is meaning the TEST. If you type "tesuto" using Japanese IME, you can see "テスト" on your display. As I attached to the last post as an actual result, unfortunately, "てすtお" is displayed.
The problem has occurred **when the text field is expanded.** 
As mentioned as an expected result of a previous post, if I use a fixed number of lines on the textfield, the problem has not occurred.

**Comment by maheshmnj** [comment] 2022-02-25 06:27
Thanks for the info @takinok, I am able to reproduce the issue, I ran the below code sample with two textfields one with fixed max lines and the other with null and continuously typed English characters "tenuto" on the Japanese Keyboard and I see the different output in both the text fields when the textfield goes multiline.

The first textfield has the expected output and the other is the actual output.

![image](https://user-images.githubusercontent.com/31410839/155663548-86cd4363-e839-4d8e-940e-6e9e8afd1d3d.png)


This issue is reproducible only on the web and works fine on windows desktop


Web  |  Desktop
:-------------------------:|:-------------------------:
<video src="https://user-images.githubusercontent.com/31410839/155665392-f8a0c4ff-c393-466b-8672-5dea38b7e7ac.mp4"/>  |  <video src="https://user-images.githubusercontent.com/31410839/155665387-86d7063b-864c-4a0d-b509-5895783640a6.mp4"/>




<details>
<summary>code sample</summary>


```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
            'Hello World!'), // should be voiced with UK Engilsh voice (app default)
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            SizedBox(
              width: 300,
              child: TextField(
                keyboardType: TextInputType.multiline,
                maxLines: 3,
                decoration: InputDecoration(
                  filled: true,
                  border: OutlineInputBorder(),
                ),
              ),
            ),
            SizedBox(
              height: 20,
            ),
            SizedBox(
              width: 300,
              child: TextField(
                keyboardType: TextInputType.multiline,
                maxLines: null,
                decoration: InputDecoration(
                  filled: true,
                  border: OutlineInputBorder(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)    • Flutter version 2.10.2 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (6 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]  
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[√] Flutter (Channel master, 2.11.0-0.0.pre.554, on Microsoft Windows [Version 10.0.19044.1526],
    locale en-US)
    • Flutter version 2.11.0-0.0.pre.554 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 894ef49c7c (10 days ago), 2022-02-14 22:15:17 -0500
    • Engine revision 8714a2448f
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)    
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version
      10.0.19044.1526]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 98.0.4758.102
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Nhinlee** [comment] 2022-06-06 14:54
Hi @maheshmnj, for this bug, I trace the change of the Flutter v2.8.1 & find out the cause making this bug happen (since this bug don't happen on Flutter v2.5.3), It's from:
- PR: https://github.com/flutter/flutter/pull/86312
- Lines make out the bug: https://github.com/LongCatIsLooong/flutter/blame/e57b3d38f679675f838b952acedb4219b00673e6/packages/flutter/lib/src/material/text_field.dart#L348

Demo for the fix:


https://user-images.githubusercontent.com/48386426/172184648-3cdfb7d9-a383-464c-8e2f-74b5416da94c.mp4

**Comment by toco1001** [comment] 2023-07-07 22:30
I'm facing with same error again on Flutter 3.10.5.

Before upgrading Flutter to 3x, I was able to fix the bug by @Nhinlee 's idea.
But now I can't fix it even I changed `this.autofillHints = const <String>[],` to `this.autofillHints`.

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-x64, locale en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (4 available)
[✓] Network resources
```

**Comment by TP-113** [comment] 2024-02-23 12:47
I am currently facing this problem as well. Is there any chance that the fixes will be merged?

**Comment by TP-113** [comment] 2024-02-24 02:11
This problem can be avoided by the user in the following ways. However, I don't like the default behavior of TextFiled to contain bugs, and I hope that the default value of autoFillHints will be changed.

``` fix_sample.dart
TextField(
  controller: _controller,
  decoration: InputDecoration(
    hintText: hintText,
  ),
  onSubmitted: (_) => {
    if (Platform.isIOS || Platform.isAndroid)
        submit()
    },
  style: Theme.of(context).textTheme.bodyMedium,
  keyboardType: TextInputType.multiline,
  autofillHints: null, // add this line
  minLines: 1,
  maxLines: 20),
),
```

**Closed** 2024-03-14 16:58 UTC
Labels: a: text input, framework, a: internationalization, platform-windows, platform-web, has reproducible steps, P1, found in release: 2.10, found in release: 2.11, team-web, triaged-web
