### ISSUE TITLE
Strange images on startup

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#29376] opened 2019-03-14 20:20 UTC
When I start the app the first time all images look very strange.
Usually it takes some time (some seconds) and then it looks normal.

What's really strange is the following behaviour (see [video](https://share.icloud.com/photos/02fPqgNgc2uoch5HlwSeN7T2w)). If you check frame by frame you can see the text (there should be a background image) and shortly after the whole screen is "destroyed".

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale de-CH)
    • Flutter version 1.2.1 at /Users/defuns/Development/Tools/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/defuns/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/defuns/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/defuns/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Philippe • 00008020-000A615C11E2002E • ios • iOS 12.1.4

• No issues found!
```

**Comment by YAPPDEF** [comment] 2019-04-18 14:36
Linked to issue #27675

**Comment by dnfield** [comment] 2019-04-24 22:05
Can you try this again on master?  I believe we've fixed this.

**Comment by dnfield** [comment] 2019-04-25 04:29
Going to close this one as well - it's almost certainly a duplicate of a fixed issue.  Please re-open if this is still occurring on master (or even dev at this point).

**Closed by dnfield** 2019-04-25 04:29 UTC
Labels: waiting for customer response, ⌺‬ platform-ios
