### ISSUE TITLE
flutter child props is changing parent variable.

### ISSUE THREAD

**Issue by AzadCoder** [flutter/flutter#90614] opened 2021-09-23 17:11 UTC
I send a variable from a parent widget to its child. by parameters. I'm using that variable on the parent and child widget. for example, I'm using `variable.name` on the parent widget. When I change the variable on the child widget `widget.variable.name = 'all'` it's also updating the parent widget but I just wanna change that on the child widget.

**Comment by maheshmnj** [comment] 2021-09-24 09:59
>When I change the variable on the child widget.variable.name = 'all' it's also updating the parent widget

Hi @AzadCoder, This is the intended behavior that's how dart is by design, it's because of shadowing

>t's also updating the parent widget but I just wanna change that on the child widget.

I would recommend you to please ask such questions on community forums like StackOverflow and you may get some help if you post it with proper description and code sample.

Closing as this isn't an issue with flutter itself, If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-24 09:59 UTC
Labels: in triage
