### ISSUE TITLE
android build apk error flutter gradle' line: 896

### ISSUE THREAD

**Issue by umang6alpha** [flutter/flutter#63990] opened 2020-08-17 20:34 UTC
in debug and profile mod run perfectly   fine but when i try to release build i got error 

flutter build apk --split-per-abi
Running "flutter pub get" in Life...                                1.8s
Running Gradle task 'assembleRelease'...  

Codepoint 58849 not found in font, aborting.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\pc\DevTool\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\pc\DevTool\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get 
full insights.

BUILD FAILED in 5m 28s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done

Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.48.0)
[√] Connected device (1 available)

• No issues found!

**Comment by jonahwilliams** [comment] 2020-08-17 20:51
@dnfield

**Comment by dnfield** [comment] 2020-08-17 22:02
I think this is probably a duplicate of https://github.com/flutter/flutter/issues/60325.

Can you re-try on master?

It would also help to have the full verbose logs.

**Comment by dnfield** [comment] 2020-08-18 15:45
The fix for this on master is about to get reverted, but will reland sometime soon.

**Comment by dnfield** [comment] 2020-08-19 00:30
Fix relanded in https://github.com/flutter/engine/pull/20609

I'm going to close this - if you have more details to add (like that this isn't working with the newer harfbuzz), please add a comment and we'll re-open.

**Comment by umang6alpha** [comment] 2020-08-19 18:53
}
Codepoint 58849 not found in font, aborting.



FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\umang\DevTool\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\umang\DevTool\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get 
full insights.


        project.exec {
            logging.captureStandardError LogLevel.ERROR
            executable flutterExecutable.absolutePath
            workingDir sourceDir
            if (localEngine != null) {
                args "--local-engine", localEngine
                args "--local-engine-src-path", localEngineSrcPath
            }
            if (verbose) {
                args "--verbose"
            } else {
                args "--quiet"
            }

**Comment by dnfield** [comment] 2020-08-19 18:57
Yeah, that log confirms this is the harfbuzz issue.  Please retry on master and reopen if it's still not working.

**Closed by dnfield** 2020-08-19 18:57 UTC

**Comment by umang6alpha** [comment] 2020-08-19 20:53
i got error in master also 

Because every version of flutter_test from sdk depends on vector_math 2.1.0-nullsafety.2 and Homeopathy depends on vector_math 2.0.8, 
flutter_test from sdk is forbidden.
So, because Homeopathy depends on flutter_test any from sdk, version solving failed.
Running "flutter pub get" in Life...
pub get failed (1; So, because Homeopathy depends on flutter_test any from sdk, version solving failed.)

**Comment by umang6alpha** [comment] 2020-08-19 21:00
name: Homeopathy
description: World Class Homeopathic Treatment

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.6+3001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.1
  html_unescape: 1.0.1+3
  provider: 4.1.2
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.8.1
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html: 0.3.3+4
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.4+3
  validate: 1.7.0
  country_pickers: 1.3.0
  shared_preferences: 0.5.7+3
  firebase_messaging: 6.0.16
  firebase_analytics: 5.0.14
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.8
  localstorage: 3.0.2+5
  notification_permissions: 0.4.4
  flare_splash_screen: 3.0.1
  rate_my_app: 0.6.1+3
  page_indicator: 0.3.0
  intro_slider: 2.3.1
  url_launcher: 5.4.10
  extended_image: 0.8.0
  firebase_core: 0.4.4 # keep these version as there is new issue
  firebase_auth: 0.15.3 # with the latest firebase https://github.com/FirebaseExtended/flutterfire/issues/2084
  flutter_webview_plugin: 0.3.11
  connectivity: 0.4.8+6
  random_string: 2.0.1
  google_maps_flutter: 0.5.28+1
  cached_network_image: 2.2.0+1
  uuid: 2.0.4
  uni_links: 0.4.0
  flutter_staggered_grid_view: 0.3.0
  auto_size_text: 2.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  video_player: 0.10.11+1
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.3
  animated_text_kit: 2.1.0
  wave: 0.0.8
  http_auth: 0.2.9
  firebase_admob: 0.9.3+2
  facebook_audience_network: 0.6.1
  pin_code_fields: 3.0.1
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.22+1
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.5.1
  google_fonts: 1.1.0
  flutter_statusbarcolor: 0.2.3
  app_settings: 4.0.0
  animated_splash: 1.0.0
  firebase_database: 3.1.6
  event_bus: 1.1.1
  country_code_picker: 1.3.14
  flutter_typeahead: 1.8.1
  flash: 1.3.1
  flutter_cupertino_date_picker: 1.0.26
  location: 3.0.2
  liquid_swipe: 1.4.3
  sticky_headers: 0.1.8+1
  onesignal_flutter: 2.4.1
  zoom_widget: 0.1.3
  awesome_card: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.5
  pedantic: 1.8.0+1 # Analysis

# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: assets/fonts/Entypo.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true

**Comment by dnfield** [comment] 2020-08-19 21:15
You'll have to bump some version constraints in your app to match what master expects :)

**Comment by umang6alpha** [comment] 2020-08-19 21:23
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\umang\DevTool\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 897

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\umang\DevTool\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get 
full insights.

* Get more help at https://help.gradle.org

**Comment by diezep** [comment] 2020-09-06 08:50
Same issue. I come from this issue #63112
