### ISSUE TITLE
[video_player] Exposing currently playing frame as an Image

### ISSUE THREAD

**Issue by John42506176Linux** [flutter/flutter#124930] opened 2023-04-15 22:16 UTC
## Proposal

Currently, I want to perform a computer vision algorithm on a video from a network url, but currently I have to download the video use ffmpeg to get the individual frames and then perform the algorithm in that order. I've seen this issue pop up for other people too when dealing with computer vision on video files. I wanted to see if it would be possible to expose the currently playing frame as an image which could be easily used for image processing without extra overhead.

Ideally it would look something like _controller.value.frame.

**Comment by stuartmorgan** [comment] 2023-04-16 01:35
Duplicate of https://github.com/flutter/flutter/issues/72693

**Closed by stuartmorgan** 2023-04-16 01:35 UTC
