### ISSUE TITLE
Support magnify glass feature for text selection in TextField in iOS

### ISSUE THREAD

**Issue by shujames** [flutter/flutter#20279] opened 2018-08-06 22:26 UTC
iOS currently supports magnify glass effect for text selection because it is hard to see the cursor position under the finger. 

Android will release a similar feature in P. It would be nice if Flutter also provide this feature.

**Comment by alanrussian** [comment] 2018-08-06 22:39
Dupe of #17617 I think

**Comment by zoechi** [comment] 2018-08-23 17:08
Closing as dup of #17617

**Comment by richgoldmd** [comment] 2018-08-29 12:01
#17617 seems to be android specific, while this issue also affects iOS. The iOS text editing experience is jarring for iOS users currently (no magnifying glass, no 3d touch cursor positioning). Just raising this because the other issue is only tagged for android.

**Comment by zoechi** [comment] 2018-08-29 12:02
Fair point

**Comment by marnberg** [comment] 2018-09-21 16:48
This issue is really important to our app since it is the first impression when logging in or creating an account. It feels broken for iOS users. It is really hard to edit an email field and impossible to drag the cursor around. On Android you can drag the cursor although it would be nice to have the magnifier too. Please prioritize this higher!

**Comment by goderbauer** [comment] 2019-01-02 23:54
Dupe of https://github.com/flutter/flutter/issues/9507, which is older.

**Closed by goderbauer** 2019-01-02 23:54 UTC
Labels: a: fidelity, framework, ⌺‬ platform-ios

**Comment by tedhenry100** [comment] 2019-07-13 17:20
This is critical! I cannot see the cursor under my finger and the app feels broken!!
