### ISSUE TITLE
TextField not reading input correctly upon pressing AltGr on desktop

### ISSUE THREAD

**Issue by HrX03** [flutter/flutter#75768] opened 2021-02-10 08:15 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Use the following file as main.dart
<details>
  <summary>main.dart</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("TextField bug"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(),
          ],
        ),
      ),
    );
  }
}

```
</details>
3. Run the app on desktop (tested only on windows for now)
4. Focus the textfield and write some stuff
5. Press AltGr and see that now textfield defaults every key press as ctrl was pressed too
6. To return to normal behaviour press ctrl

**Expected results:**
The textfield should register input correctly

**Actual results:**
Upon pressing AltGr every input is treated as there was the ctrl key pressed

<details>
  <summary>Flutter doctor output</summary>

```
[√] Flutter (Channel master, 1.26.0-18.0.pre.210, on Microsoft Windows [Versione 10.0.21292.1010], locale it-IT)
    • Flutter version 1.26.0-18.0.pre.210 at C:\src\flutter
    • Framework revision a77388e670 (5 days ago), 2021-02-04 22:51:04 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\dnbia\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.21292.1010]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.146

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-02-10 10:46
Hi @HrX03 
I don't have AltGr, can you please provide details on what kinda input is exactly showing  with "Upon pressing AltGr every input is treated as there was the ctrl key pressed"

Thank you

**Comment by HrX03** [comment] 2021-02-10 12:13
@TahaTesser Sorry for the late response but here's a video of what happens with the onscreen keyboard, hope it's clear enough

https://user-images.githubusercontent.com/29352339/107508670-aeb5f880-6ba1-11eb-8c26-af9d359c76e3.mp4

**Comment by HrX03** [comment] 2021-02-10 12:17
@TahaTesser sorry for the double mention, had some troubles with the previous video. Anyways here's a video showcasing the issue, recorded with the onscreen keyboard

https://user-images.githubusercontent.com/29352339/107509074-369c0280-6ba2-11eb-8f77-f623e4abbd7b.mp4

**Comment by TahaTesser** [comment] 2021-02-11 07:40
Hi @HrX03 
Thanks for the details, I can re; produce using on-screen keyboard using English (India) layout which AltGr, using the same keyboard on google chrome or text document has no issue

<details>
<summary>flutter doctor -v</summary>

```bash
[âˆš] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    â€¢ Flutter version 1.27.0-1.0.pre at C:\Users\Taha\Code\flutter_dev
    â€¢ Framework revision 68c96f100e (2 days ago), 2021-02-08 16:14:15 -0800
    â€¢ Engine revision b04955656c
    â€¢ Dart version 2.13.0 (build 2.13.0-0.0.dev)
[âˆš] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    â€¢ Android SDK at C:\Users\Taha\Code\SDK
    â€¢ Platform android-30, build-tools 30.0.3
    â€¢ ANDROID_HOME = C:\Users\Taha\Code\SDK
    â€¢ Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    â€¢ All Android licenses accepted.
[âˆš] Chrome - develop for the web
    â€¢ Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
[âˆš] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    â€¢ Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    â€¢ Visual Studio Community 2019 version 16.8.30907.101
    â€¢ Windows 10 SDK version 10.0.18362.0
[âˆš] Android Studio (version 4.1.0)
    â€¢ Android Studio at C:\Users\Taha\Code\android-studio
    â€¢ Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    â€¢ Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[âˆš] VS Code (version 1.53.1)
    â€¢ VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    â€¢ Flutter extension version 3.19.0
[âˆš] Connected device (3 available)
    â€¢ Windows (desktop) â€¢ windows â€¢ windows-x64    â€¢ Microsoft Windows [Version 10.0.19042.746]
    â€¢ Chrome (web)      â€¢ chrome  â€¢ web-javascript â€¢ Google Chrome 88.0.4324.150
    â€¢ Edge (web)        â€¢ edge    â€¢ web-javascript â€¢ Microsoft Edge 88.0.705.63
â€¢ No issues found!
```
```bash
[âˆš] Flutter (Channel master, 1.27.0-2.0.pre.67, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    â€¢ Flutter version 1.27.0-2.0.pre.67 at C:\Users\Taha\Code\flutter_master
    â€¢ Framework revision 78ce11d7e3 (60 minutes ago), 2021-02-11 07:37:57 +0100
    â€¢ Engine revision cdc49c575b
    â€¢ Dart version 2.13.0 (build 2.13.0-25.0.dev)
[âˆš] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    â€¢ Android SDK at C:\Users\Taha\Code\SDK
    â€¢ Platform android-30, build-tools 30.0.3
    â€¢ ANDROID_HOME = C:\Users\Taha\Code\SDK
    â€¢ Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    â€¢ All Android licenses accepted.
[âˆš] Chrome - develop for the web
    â€¢ Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
[âˆš] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    â€¢ Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    â€¢ Visual Studio Community 2019 version 16.8.30907.101
    â€¢ Windows 10 SDK version 10.0.18362.0
[âˆš] Android Studio (version 4.1.0)
    â€¢ Android Studio at C:\Users\Taha\Code\android-studio
    â€¢ Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    â€¢ Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[âˆš] VS Code (version 1.53.1)
    â€¢ VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    â€¢ Flutter extension version 3.19.0
[âˆš] Connected device (3 available)
    â€¢ Windows (desktop) â€¢ windows â€¢ windows-x64    â€¢ Microsoft Windows [Version 10.0.19042.746]
    â€¢ Chrome (web)      â€¢ chrome  â€¢ web-javascript â€¢ Google Chrome 88.0.4324.150
    â€¢ Edge (web)        â€¢ edge    â€¢ web-javascript â€¢ Microsoft Edge 88.0.705.63
â€¢ No issues found!
```

</details>

Thank you

**Comment by Ronjack** [comment] 2021-03-10 10:17
This bug is not bound on the textfield or textformfield its general if alt gr is pressed in a flutter desktop app... New standard Flutter project. Master / Latest Dart version / latest flutter package / latest vscode version

**Comment by zsmiklos** [comment] 2021-03-24 08:54
Same case here: https://github.com/flutter/flutter/issues/78005  with more detail.
In any Flutter app in a TextField widget, on Windows, pressing once the AltGr key will drive Windows keyboard crazy: after pressing AltGr, Windows behaves as if the ctrl key was pressed continuously in any application. (Pressing a simple v behaves like if the ctrl-v was pressed) Just double-pressing the left ctrl key will stop this strange state. 
This bug prevents developing and publishing Flutter apps to Windows.

**Comment by Josua2012** [comment] 2021-03-24 12:12
Text input has many problems in Windows, if they are not solved quickly they will prevent other developers from even testing with Flutter-Windows. :(

**Comment by yurik94** [comment] 2021-05-07 11:04
Even backspace key on a text edit still not work!

**Comment by stuartmorgan** [comment] 2021-05-10 13:59
Duplicate of #78005

**Closed by stuartmorgan** 2021-05-10 13:59 UTC
Labels: P4, a: desktop, a: text input, engine, f: material design, found in release: 1.26, found in release: 1.27, framework, has reproducible steps, platform-windows

**Comment by HrX03** [comment] 2021-05-10 14:21
aight thanks for the heads up, was wondering indeed why this was deemed duplicate
