### ISSUE TITLE
Flutter Go: no handler for firebase Auth

### ISSUE THREAD

**Issue by guit4eva** [flutter/flutter#47130] opened 2019-12-16 13:04 UTC
I'm getting the following error when trying to access the Firebase Auth plugin with Flutter Go:

> go-flutter: no handler found for channel plugins.flutter.io/firebase_auth

The rest of the app is working well so far. Is there a step I'm missing with getting Firebase Auth to work?

**Comment by iapicca** [comment] 2019-12-16 14:37
Hi @guit4eva 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-16 14:37 UTC
