### ISSUE TITLE
Some errors are silenced

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#19191] opened 2018-07-10 00:25 UTC
I need some help in figuring out why some errors are being silenced by Flutter framework.

As far as I remember this has been the case since I started working with Flutter (January) but it's really hard to reproduce. I haven't seen this in a while but just got another scenario which I'll try to explain here.

In short: some errors simply do not show up in logs and application keeps running as nothing happened. There is no async calls / Futures involved, I didn't override FlutterError handler and don't use Zones.

Here is screen recording of me attempting to delete single character in a text document. Notice how for the second attempt I wrap the broken piece of code in a try-catch block which prints the error.

![kapture 2018-07-09 at 17 07 34](https://user-images.githubusercontent.com/441756/42482374-05cf2a74-839c-11e8-82bf-bc4fbe97d6c6.gif)

The app is a barebones Flutter project created with `flutter create`.

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.74, on Mac OS X 10.13.5 17F77, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[!] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-07-10 07:13
Are you sure the changes took effect? It happens often to me that I have to run `flutter clean` to get the latest changes included in the running app flutter/flutter-intellij#2472

**Comment by pulyaevskiy** [comment] 2018-07-10 17:09
It doesn't seem like an issue in the IDE.

Here is the same issue, but I used `flutter run` directly instead of the IDE:

![kapture 2018-07-10 at 10 03 00](https://user-images.githubusercontent.com/441756/42525731-c07dc9ca-8428-11e8-8381-f09cc16e95ae.gif)

**Comment by zoechi** [comment] 2018-07-10 17:17
But after `flutter clean` it's working again, right?

**Comment by pulyaevskiy** [comment] 2018-07-10 17:57
Ok, so looks like my problem originates somewhere here:
https://github.com/flutter/flutter/blob/0a4c1166833083815d34a4a963a093ea1f63bf11/packages/flutter/lib/src/services/platform_channel.dart#L335-L337

Broken code is executed within a TextInput update. Here is the stack trace:

```
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      NotusDocument.compose (package:notus/src/document.dart)
#3      NotusDocument.delete (package:notus/src/document.dart:135:7)
#4      NotusDocument.replace (package:notus/src/document.dart:165:27)
#5      ZefyrController.replaceText (package:zefyr/src/widgets/controller.dart:106:24)
#6      _ZefyrEditableTextState._handleRemoteValueChange (package:zefyr/src/widgets/editable_text.dart:275:10)
#7      InputConnectionController.updateEditingValue (package:zefyr/src/widgets/input.dart:113:5)
#8      _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:397:36)
<asynchronous suspension>
#9      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:326:55)
<asynchronous suspension>
#10     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:299:54)
#11     BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
<asynchronous suspension>
#12     _invoke3.<anonymous closure> (dart:ui/hooks.dart:165:15)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _invoke3 (dart:ui/hooks.dart:164:10)
#17     _dispatchPlatformMessage (dart:ui/hooks.dart:75:5)
```

Wondering if someone can explain where result of `encodeErrorEnvelope` ends up?

**Comment by pulyaevskiy** [comment] 2018-07-10 18:17
The above helped me to come up with a workaround. I added try-catch block in my `TextInputClient.updateEditingValue` implementation and use `FlutterError.reportError` to print the error, followed by `rethrow`.

Though I feel like it would make more sense for Flutter to not silence such errors.

What would be a good solution in this case? I see two options here:

1. Update `_TextInputClientHandler._handleTextInputInvocation` and add a try-catch block around switch statement.
2. Update `MethodChannel._handleAsMethodCall` where it catches the error to `FlutterError.reportError` before returning error envelope

I like option 2 more as it will report any unhandled error for any plugin.
I'd be happy to submit a PR with either solution though.

Let me know your thoughts.

**Comment by obshksw** [comment] 2020-06-19 17:50
I'm also having that problem and it can become VERY annoying.

There's sometimes no way to know where errors occur at runtime unless diving deep into the code until you see that your code stops altogether, then have to put a try-catch to know what the error is. That is very counter-productive. It also becomes a problem when these errors occurs in production and there's no way to track error stacks (no error in the web console).

Also, doing dev tests while trying to mock some parts of the app can be painful. For example, I have a screen that contains a panel with a chat, and want to dev test that it is open when the screen is instantiated:

Let's say my test looks like this:
```
testWidgets('Panels should be in full state when entering room', (WidgetTester tester) async {
      await tester.runAsync(() async {
        await tester.pumpWidget(_getAppWidget());
        await tester.pumpAndSettle();

        final Finder finder = find.byType(PanelChat);
        expect(finder, findsOneWidget);

        final PanelChat panelChat = finder.evaluate().first.widget;
        expect(panelChat.displayState, PanelDisplayState.full);
      });
    });
```

And my app widget has this:
```
@override
  void initState() {
    super.initState();
    try {
      _chatManagerSubscription = BlocProvider.of<IChatManager>(context).eventStream.listen(_onChatManagerEvent);
     
    } catch (e) {
      print(e);
    }
  }```

For some reasons I only thought of mocking ChatManager, so it will crash on eventStream.
If not for the try-catch, I'd get no errors, even running in debug, all I get is that my test fails like this:

Expected: exactly one matching node in the widget tree
  Actual: _WidgetTypeFinder:<zero widgets with type "PanelChat" (ignoring offstage widgets)>
   Which: means none were found but one was expected

This is only one case, but I have multiple things I have to mock on different widget levels because I have multiple bloc builders, so my only choice is to got through one at a time and adding try catch here and there to find what is missing?

Maybe I'm doing it wrong, but I feel like I should know what error caused a crash anyway!

**Comment by pedromassangocode** [comment] 2020-09-09 10:56
Hi @pulyaevskiy 
Are you still facing this issue? If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by darshankawar** [comment] 2020-09-30 11:06
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-30 11:06 UTC
Labels: framework, p: framework, plugin, severe: crash, waiting for customer response
