### ISSUE TITLE
Failed assertion using a NestedScrollView

### ISSUE THREAD

**Issue by dicoda** [flutter/flutter#75107] opened 2021-02-01 00:50 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `main.dart` with code bellow:

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: CupertinoThemeData(),
      home: CupertinoTabScaffold(
        tabBar: CupertinoTabBar(items: [
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.waveform),
            label: '1',
          ),
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.app),
            label: '2',
          )
        ]),
        tabBuilder: (context, index) {
          return TabPage();
        },
      ),
    );
  }
}

class TabPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return [
            CupertinoSliverNavigationBar(
              largeTitle: Text('Large Title'),
            )
          ];
        },
        body: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, index) {
                  return Text('');
                },
                childCount: 10,
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

**Expected results:**
The app running after first build.

**Actual results:**
Crashes on the first run, right after a build. A hot reload hides the issue, but every time the app is built again, it will show this error.

**Observations:**
Bug might be related to issue #72257

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder(dirty):
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 805 pos 14: 'position.hasContentDimensions && position.hasPixels': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
NestedScrollView
lib/main.dart:37
When the exception was thrown, this was the stack
#2      _NestedScrollCoordinator.hasScrolledBody
package:flutter/…/widgets/nested_scroll_view.dart:805
#3      NestedScrollViewState.build.<anonymous closure>
package:flutter/…/widgets/nested_scroll_view.dart:627
#4      Builder.build
package:flutter/…/widgets/basic.dart:7555
```

<details>
  <summary>Doctor output</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-arm, locale en-PT)
    • Flutter version 1.25.0-8.3.pre at /Users/delta/Development/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/delta/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 12 mini (mobile) • AA46B792-422D-4099-8663-FA128A11DAAD • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
```

</details>

**Comment by darshankawar** [comment] 2021-02-01 11:18
@dicoda 
Pass `controller` to your `CustomScrollView` which should resolve your issue.

```
body: CustomScrollView(
          controller: _scrollController,
```

`var _scrollController = ScrollController();`

<img width="328" alt="Screenshot 2021-02-01 at 4 47 33 PM" src="https://user-images.githubusercontent.com/67046386/106451918-336f8b00-64ad-11eb-8a20-d1fa5b6fc35d.png">

Closing this as solved. If you think otherwise, write in comments and I'll reopen it.

**Comment by dicoda** [comment] 2021-02-01 11:36
Thanks @darshankawar

**Comment by xu-baolin** [comment] 2021-02-02 07:24
@darshankawar Hi,
at a glance, this looks like a framework bug, reopen.

**Comment by darshankawar** [comment] 2021-02-02 07:31
Thanks @xu-baolin for the tip. 

<details>
<summary> error log </summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder(dirty):
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 798 pos 14: 'position.hasContentDimensions && position.hasPixels': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  NestedScrollView file:///Users/dhs/Documents/NCFlutter/webtest/lib/main.dart:37:14
When the exception was thrown, this was the stack: 
#2      _NestedScrollCoordinator.hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:798:14)
#3      NestedScrollViewState.build.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:620:48)
#4      Builder.build (package:flutter/src/widgets/basic.dart:7555:48)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4583:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4509:15)
...
====================================================================================================


```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.121, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-18.0.pre.121 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 225e408d4f (3 hours ago), 2021-02-01 22:26:03 -0500
    • Engine revision e59457b818
    • Dart version 2.12.0 (build 2.12.0-279.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.96

! Doctor found issues in 1 category.


```

</details>

**Comment by chunhtai** [comment] 2021-02-03 17:28
looks like a regression of https://github.com/flutter/flutter/issues/31195
is this for ios only?

**Comment by xu-baolin** [comment] 2021-02-03 18:42
> looks like a regression of #31195
> is this for ios only?

This should be another issue comment, right?

**Comment by dicoda** [comment] 2021-02-03 18:47
Hi,

I can confirm that the issue is present in both iOS 14.4 and Android API 30.

Adding a ScrollController() does hide the issue, but that presents a whole set new of problems on itself, so it's not working as a temporary solution.

**Comment by chunhtai** [comment] 2021-02-03 19:20
Sorry for the earliest comment, I can confirm this is not a regression but another corner case that will make nestedScrollView built twice without being laid out.

**Closed** 2021-02-10 09:01 UTC
Labels: f: material design, f: scrolling, found in release: 1.26, framework, has reproducible steps, severe: crash
