### ISSUE TITLE
Android scroll speed deceleration rate doesn't match native

### ISSUE THREAD

**Issue by korbin-w** [flutter/flutter#16371] opened 2018-04-09 16:41 UTC
## Steps to Reproduce

1, Scroll a ListView page on Android.  
2, Observe and compare the scrolls between Flutter and Native pages.
3, The scroll is tiny bumpy in Flutter. Besides, before the end of scroll, I have a feeling that it "suddenly" stops.

[screenrecord_20180409_213143.mp4.zip](https://github.com/flutter/flutter/files/1890829/_20180409_213143.mp4.zip)

## Flutter Doctor

[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.12.6 16G1314, locale zh-Hans-HK)
    • Flutter version 0.2.3 at /Users/guoyou/projects/flutter
    • Framework revision 5a58b36e36 (4 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/guoyou/Library/Android/sdk
    • Android NDK at /Users/guoyou/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 172.3968.27

[✓] Connected devices (1 available)
    • iPhone X • 8D4A21F9-E417-43CE-8B40-52CEAB6B7D04 • ios • iOS 11.2 (simulator)

• No issues found!

**Comment by korbin-w** [comment] 2018-04-11 02:38
@xster Yes, it is that friction is too high and the flings slow down too quickly towards the end.  Comparing it with native views, there is tiny difference.    I looked at the performance, it is normal. 
As the difference is tiny, feel free to handle this issue.  It is not blocker.

**Comment by xster** [comment] 2018-04-11 06:40
Yes it does look a bit off. Would you mind comparing with our gallery app (https://play.google.com/store/apps/details?id=io.flutter.demo.gallery)? Couldn't tell from the video but it does look a bit different from our default expected behaviour too.

**Comment by korbin-w** [comment] 2018-04-11 17:26
@xster Thanks for your suggestion, I've compared with the gallery app, I think the difference is still existing. I'm comparing the scroll gallery with any android native app, the smooth is tiny different but I don't know how to  figure the difference with test results, I'm just observing between them.  Or else can you tell me the principle or code position of the scroll speed of Flutter?

**Comment by xster** [comment] 2018-04-11 18:30
They're different per platform but for Android, it's at https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_simulation.dart#L141 (which I believe is extracted from the Android source code)

**Comment by TahaTesser** [comment] 2020-09-08 13:12
I can easily notice the different when using lists example from  https://github.com/flutter/gallery and Play store

**Comment by hamberluo** [comment] 2020-11-18 04:29
this tiny difference of scroll behavior between native and flutter should important to users

**Comment by hamberluo** [comment] 2020-11-20 02:58
Changing `friction` smaller in ClampingScrollSimulation will help improving the speed deceleration.

But the problem is the default friction is 0.015 and algorithm also from android source, so what's wrong with flutter?

**Comment by vannevar-morgan** [comment] 2021-06-10 09:25
I agree scrolling feels different in flutter vs native.  Noticed after upgrading to flutter 2.0.0 that scrolling seems much more slippy.  Using defaults, can now easily fling through a ListView of 300+ items with one flick.  Whereas native it might take 3 or 4 flicks.  Using ClampingScrollSimulation and increase the friction, .03 or .045 it still feels like the deceleration curve is just off.  Apologies for the terms like "slippy", best I can describe it.

**Comment by nt4f04uNd** [comment] 2021-08-28 01:39
I think was fixed with https://github.com/flutter/flutter/pull/77497

**Comment by Piinks** [comment] 2021-09-09 23:12
I think some of the comments here may have actually been caused by https://github.com/flutter/flutter/pull/77497.
I have bisected it as the cause for https://github.com/flutter/flutter/issues/83632, which some of the comments above describe as well.

**Comment by eseidelGoogle** [comment] 2022-03-18 20:01
This came up today. Is it worth landing the test from https://github.com/flutter/flutter/pull/92338/files even if it's marked as failing for now?

**Comment by Piinks** [comment] 2022-09-08 17:10
The PR that closed this is being reverted. Reopening.

**Comment by Piinks** [comment] 2022-09-08 17:30
For the next crack at solving this, this reproduction should be included as a test case: https://github.com/flutter/flutter/issues/110340

Also, the [latest attempt](https://github.com/flutter/flutter/pull/107735) included creating and passing updated FixedScrollMetrics to createBallisticScrollAnimation. This was a breaking change for customers with their own custom scroll physics that expect a scroll position be provided to createBallisticScrollAnimation, not just ScrollMetrics. Either migrating the customer off of this currently safe assumption will be required, or a different approach that preserves that.

**Comment by exaby73** [comment] 2023-04-21 07:09
@Piinks What's the status of this issue currently? The scrolling performance I see is very similar currently. Though the device I am using is an older one so I'm not confident closing this issue based on that.

**Comment by gnprice** [comment] 2023-04-21 07:42
Thanks for the bump. I believe this was fixed by the combination of the two PRs
* #120420
* and #122338.

These symptoms were a combined effect of
* #113424,
* #119875,
* #120338,
* and #120345.

Those four issues were fixed by the two PRs mentioned above. In particular, see the "after" video from the latter PR (at https://github.com/flutter/flutter/pull/122338#issuecomment-1462999629), which compares fling-scrolls in Flutter and a native Android scrollable.

I think that covers all the reports in this thread (other than those that were #83632). For any discrepancies that remain, it's probably best to file a new issue.

**Closed by gnprice** 2023-04-21 07:42 UTC
Labels: platform-android, framework, a: fidelity, f: scrolling, customer: alibaba, a: quality, has reproducible steps, P4, found in release: 1.22
