### ISSUE TITLE
Execution failed for task ':firebase_core:generateDebugRFile'. > Could not resolve all files for configuration ':firebase_core:debugCompileClasspath'.    > Could not find com.google.firebase:firebase-common:.      Required by:          project :firebase_core  * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.  * Get more help at https://help.gradle.org

### ISSUE THREAD

**Issue by yashvenrakumar** [flutter/flutter#88101] opened 2021-08-12 10:34 UTC
Execution failed for task ':firebase_core:generateDebugRFile'.
> Could not resolve all files for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-common:.
     Required by:
         project :firebase_core

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by TahaTesser** [comment] 2021-08-12 10:39
Hi @yashvenrakumar 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-12 10:39 UTC
Labels: in triage
