### ISSUE TITLE
Feature Request: Listen to line wrap event in TextField

### ISSUE THREAD

**Issue by kulny** [flutter/flutter#109810] opened 2022-08-18 22:28 UTC
## Use case

I'm trying to design a text editor for flutter that has line numbers associated with each line in the TextField. I would prefer to use Flutter's default TextField rather than develop a full alternative only to copy or otherwise solve problems in the same way that TextField already does. 

One issue I've continually run into is the question of determining line numbers. Ultimately, the only good way seems to be counting the number of '\n' characters throughout the string. However, this method fails when dealing with text wrapping from a TextField. The wrapped text in a TextField, naturally, doesn't add any actual newlines to the text itself, so the method that merely counts the newline characters (which is seemingly the same method used by `TextPainter.computeLineMetrics()`) completely misses this case when trying to keep track of line numbers.

A non-simple alternative would be to parse the text at every input from the user and perform a TextPainter simulation (create a new TextPainter and perform a layout with the known text) to see if it wraps the text, then to find the nearest word beginning (or split the word ala `long-\nword`), add a newline, and then continue on. However this quickly becomes quite complex and unwieldy for what amounts to determining when a line is wrapped by a TextField.

## Proposal

Some way of listening to when a TextField wraps its text into a new line, ideally with reference to the index at which the line wrapping occurred (for cases where the user is editing text in the middle of the TextField and a line wrap is added in some arbitrary position).

**Comment by LongCatIsLooong** [comment] 2022-08-31 17:57
This looks like (partially) a duplicate of https://github.com/flutter/flutter/issues/91010.

Also `TextPainter.computeLineMetrics()` accounts for softwraps (not just newline characters) as far as I know.

**Comment by kulny** [comment] 2022-08-31 19:18
Here is a minimal sample of a case where line numbers provided by `TextPainter.computeLineMetrics()` never increments, even after soft wrapping inputted text. 

<details>
<summary>minimal example</summary>


```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController tec = TextEditingController();

  @override
  void initState() {
    super.initState();

    tec.addListener(() {
      TextPainter tp = TextPainter(
          text: TextSpan(text: tec.text), textDirection: TextDirection.ltr);
      tp.layout();
      print(tp.computeLineMetrics());
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ConstrainedBox(
        constraints: BoxConstraints(maxWidth: 100),
        child: TextField(
          controller: tec,
          maxLines: null,
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19043.1889], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)      
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.70.2)
[√] Connected device (2 available)
[√] HTTP Host Availability

• No issues found!
```


</details>

<details>
<summary> gif of example</summary>

![line metrics test example](https://user-images.githubusercontent.com/27989807/187764128-76a89e1e-7eef-47a3-9233-3a7bda365406.gif)


</details>

**Comment by LongCatIsLooong** [comment] 2022-08-31 19:43
> `tp.layout();`

if you don't specify the constraints the painter will layout the text with `minWidth = 0.0` and `maxWidth = double.infinity`, there won't be any soft-wrapping. See https://master-api.flutter.dev/flutter/painting/TextPainter/layout.html

**Closed by LongCatIsLooong** 2022-08-31 19:43 UTC
Labels: a: text input, new feature, framework, proposal, P6
