### ISSUE TITLE
LiDAR support in Flutter

### ISSUE THREAD

**Issue by gangov** [flutter/flutter#68776] opened 2020-10-22 10:39 UTC
## Use case

With Apple releasing ARKit 4 it will be useful for some of the developers to benefit from the latest LiDAR capabilities

## Proposal

Probably an update of the [arkit_plugin](https://pub.dev/packages/arkit_plugin) would be the best solution for this request

Cheers,

**Comment by iapicca** [comment] 2020-10-22 13:18
@gangov 
[arkit_plugin](https://pub.dev/packages/arkit_plugin) is a 3rd party plugin, consider opening an issue in its dedicated [github](https://github.com/olexale/arkit_flutter_plugin/issues)
regardless, isn't this something achievable with a [platform channel](https://flutter.dev/docs/development/platform-integration/platform-channels)?

**Comment by TahaTesser** [comment] 2020-10-22 15:23
Hi @iapicca 
I agree with @iapicca, This seems like a request for `arkit_plugin`.
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/olexale/arkit_flutter_plugin/issues).
Closing, as this isn't an issue with Flutter itself.  
Thank you

**Closed by TahaTesser** 2020-10-22 15:23 UTC
