### ISSUE TITLE
textfield panic with Input method switching in win10

### ISSUE THREAD

**Issue by luckrill** [flutter/flutter#94714] opened 2021-12-06 09:02 UTC
textfield edit mode

panic with Input method switching in win10

key is: Ctrl + blank

env: windows 10 or 11

**Comment by maheshmnj** [comment] 2021-12-06 11:20
Hi @luckrill, Thanks for filing the issue. I am not exactly sure what the issue is, can you please update the description to clearly describe the issue? The description should include `flutter doctor -v`, complete logs or errors if any along with steps to reproduce the issue.

Thank you.

**Comment by luckrill** [comment] 2021-12-06 14:30
macos no this issue. only windows have issue

**Comment by luckrill** [comment] 2021-12-07 01:33
![image](https://user-images.githubusercontent.com/5372899/144949565-f5d8814c-d100-4269-861f-de3a7b55ea55.png)

![image](https://user-images.githubusercontent.com/5372899/144949622-aa74424f-e6f2-484c-ab3d-2aa0916834e0.png)

**Comment by maheshmnj** [comment] 2021-12-07 06:31
@luckrill. Can you please rephrase the issue with sample code and reproducible steps?

> I am not exactly sure what the issue is, can you please update the description to clearly describe the issue?

**Comment by luckrill** [comment] 2021-12-27 09:55
https://user-images.githubusercontent.com/5372899/147459789-1dc2b6a9-00c5-46a3-a276-8c77f393f544.mp4

this is issue video, only input keyboard and ctrl+space, textfield is pannic in windows env.

**Comment by luckrill** [comment] 2021-12-27 09:58
![image](https://user-images.githubusercontent.com/5372899/147460247-a22501c0-f9a8-49a6-b102-c887aefce671.png)

my env

**Comment by maheshmnj** [comment] 2021-12-27 11:46
Thanks for the video @luckrill, If I understand correctly the issue is about app freezing when you enter ctrl +space is that correct? if so I did verify on windows 10 with input method set to simplified Chinese on the master channel and could not reproduce the issue

https://user-images.githubusercontent.com/31410839/147468643-2443e435-cb95-48cc-9e56-91437e3f29d5.mp4


 Do you see any error logs in the console? 
 
 
<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.9.0-1.0.pre.146, on Microsoft Windows [Version 10.0.19042.1415], locale
    en-US)
    • Flutter version 2.9.0-1.0.pre.146 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 710502c420 (6 days ago), 2021-12-21 04:59:14 -0500
    • Engine revision 4aec3e6b2e
    • Dart version 2.16.0 (build 2.16.0-124.0.dev)
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19042.1415]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 96.0.4664.110
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 96.0.1054.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by luckrill** [comment] 2021-12-28 01:07
this issue only show with fultter build mode.  
no any log, It's not inevitable every time, it's accidental. 

in flutter debug mode, textfield no issue

**Comment by maheshmnj** [comment] 2021-12-28 07:09
@luckrill, If I understand correctly you mean this issue is only in release mode is that correcct? 
However I did verify the below sample code in both debug and release with Chinese input source, but I am unable to reproduce it.  Can you please confirm if the issue reproduces for you with below code sample?


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            TextField(),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
····
</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.9.0-1.0.pre.146, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)    • Flutter version 2.9.0-1.0.pre.146 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 710502c420 (7 days ago), 2021-12-21 04:59:14 -0500
    • Engine revision 4aec3e6b2e
    • Dart version 2.16.0 (build 2.16.0-124.0.dev)
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)    
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19042.1415]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 96.0.4664.110
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 96.0.1054.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by luckrill** [comment] 2021-12-28 07:42
https://user-images.githubusercontent.com/5372899/147540598-5f0e6ae2-914c-4030-a452-3effc9e4fa3a.mp4

with your simple code, in debug mode, have issue 

flutter.bat doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel dev, 2.9.0-0.1.pre, on Microsoft Windows [Version 10.0.22000.376], locale zh-CN)
    • Flutter version 2.9.0-0.1.pre at D:\program\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (13 days ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\luckr\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32002.185
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\luckr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.376]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!

**Comment by maheshmnj** [comment] 2021-12-28 07:52
@luckrill Can you please clarify this, I am not really sure what you meant by "textfield panic"

Are you referring to Textfield input changing from simplified Chinese to English and vice versa when ctl+space is pressed?

**Comment by luckrill** [comment] 2021-12-30 08:20
today, try install another innoput method 

no meet above issue again

maybe Microsoft Pinyin IME cause above problems

**Comment by maheshmnj** [comment] 2021-12-30 09:37
Provided that you are no longer able to reproduce the issue, I am closing it for now. If you encounter this issue again feel free to write back or file a new issue.

**Closed by maheshmnj** 2021-12-30 09:37 UTC
Labels: in triage
