### ISSUE TITLE
"Failure to dismiss dialog" errors on Mac_ios 20flutter_gallery_ios__transition_perf

### ISSUE THREAD

**Issue by flar** [flutter/flutter#104677] opened 2022-05-26 01:04 UTC
See logs for various runs at: https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios__transition_perf
See also similar issue for another benchmark: https://github.com/flutter/flutter/issues/104675

Examples:

https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios__transition_perf/2297
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios__transition_perf/2298
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios__transition_perf/2300
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios__transition_perf/2301
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios__transition_perf/2303
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios__transition_perf/2304

**Comment by christopherfujino** [comment] 2022-05-26 02:05
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/104672. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-05-26 02:05 UTC
Labels: team: infra
