### ISSUE TITLE
Unable to load asset: icons/slack.png.

### ISSUE THREAD

**Issue by yash-pietech** [flutter/flutter#121327] opened 2023-02-23 11:11 UTC
I have facing the issue with load the assets in my app .
we have created the package  getwidget (https://pub.dev/packages/getwidget) . 
now we are facing the issue with images.
## Steps to Reproduce

1. you can download the code and run this repo and use this  GFSocialButton widget or you can import this library to your app and you can test this issue       .    

we want that our assets are display properly . but it is showing like that below image

<img width="303" alt="Screenshot 2023-02-23 at 4 29 44 PM" src="https://user-images.githubusercontent.com/126047746/220888103-5f8d71eb-dd60-4dfc-903d-cad47293bb49.png">

  GFSocialButton(
                    onPressed: () {},
                    type: GFSocialType.slack,
                    buttonType: GFSocialButtonType.solid),

    
<details>
  <summary>Logs</summary>

[✓] Flutter (Channel stable, 3.3.10, on macOS 12.4 21F2081 darwin-arm, locale en-IN)
    • Flutter version 3.3.10 on channel stable at /Users/yash/fvm/versions/3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/yash/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.4 21F2081 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment] 2023-02-23 12:14
@yash-pietech 
From what I can see, the issue is related to a `getwidget` rather than to Flutter itself. Please open the issue in [getwidget repository](https://github.com/ionicfirebaseapp/getwidget/issues). For quick search results, it sounds similar to [this existing issue](https://github.com/ionicfirebaseapp/getwidget/issues/313).

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2023-02-23 12:14 UTC
Labels: in triage
