### ISSUE TITLE
[Proposal] Proper window management API for Flutter Desktop in the SDK

### ISSUE THREAD

**Issue by KRTirtho** [flutter/flutter#156666] opened 2024-10-13 08:00 UTC
### Use case

I don't think Flutter deserved to be called a _"Desktop App Framework"_ without having an official API for controlling the App's window.

Currently, `window_manager` and `bitsdojo_window` (no release for upto 9 months) are only 2 plugins that the entire community is using.
They constantly break due to embedder changes in the official Flutter releases. `window_manager` is broken in `Windows` since Flutter stable `3.22.x` https://github.com/leanflutter/window_manager/issues/464. So practically, every Flutter Desktop app that needs to hide the ugly (respectfully incoherent to the app UI design) Titlebar is officially broken for 2 major Flutter versions.

While the plugin developers are trying their best to resolve this kind of crucial bugs, it's understandable that they can't keep up. Because this kind of crucial plugins must keep their compatibility with newer Flutter versions. And there shouldn't be any new Flutter feature that breaks them without having a solution in the first place and gets released

So, what we need is an official **Window (embedder) Mangement API** for the Desktop apps that will be in the Flutter SDK.

### Proposal

We need official way to control the Window behaviour and manipulate the application Window (as much as the OS lets us in userspace). Probably abstraction over multiple major desktop OS's window APIs (macos: `NSWindow`, windows: `HWND`, linux: `GtkWindow`) is needed. 

But, it'd be much more preferred if it's written as common abstraction for embedders. That way any new targets/platforms can be integrated easily with their different window management APIs.

Also, the binding should be initialized before any Widget initialization ig because we don't want any "ghost effect"[1] that we currently experience using `window_manager` or `bitsdojo_window` plugin

> **ghost effect:** It's a transparent (black in macos) window yet with border and shadow that's shown for a few milliseconds before Flutter renderer paints for the first time. The time it's shown is proportional to the number of plugin initializations you do before `runApp`

**Comment by KRTirtho** [comment] 2024-10-13 08:04
This is the current situation in Windows app using the plugins


![Stretched window image](https://private-user-images.githubusercontent.com/61944859/336926742-1fefa699-6dc4-46ea-bfa9-2ef12c1c1383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDY4NTIsIm5iZiI6MTcyODgwNjU1MiwicGF0aCI6Ii82MTk0NDg1OS8zMzY5MjY3NDItMWZlZmE2OTktNmRjNC00NmVhLWJmYTktMmVmMTJjMWMxMzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA4MDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNGU5ZDgxZjAxZWQxMmNhODI0MDY2OWJmMjFkZmUxN2I0MTRjZDM0MDEwZTlmODIzMTA1ZmIwZWQ1ZDRlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UhoiZh7U5jAyvjR61SlgMV2rrGNy3XPgCvFgWsNuMTU)

**Comment by stuartmorgan** [comment] 2024-10-13 09:07
Closing as a duplicate of https://github.com/flutter/flutter/issues/30701, as window management is already part of the design proposal for multi-window.

**Closed by stuartmorgan** 2024-10-13 09:07 UTC
