### ISSUE TITLE
Deep Link and Universal Link Support

### ISSUE THREAD

**Issue by viztushar** [flutter/flutter#57315] opened 2020-05-15 13:08 UTC
i'm request to add Deep Link and Universal Link Support in Flutter. 

or is there any way we can add support for Deep Link and Universal Link ?

**Comment by TahaTesser** [comment] 2020-05-15 15:21
Closing as duplicate of https://github.com/flutter/flutter/issues/11607

**Closed by TahaTesser** 2020-05-15 15:21 UTC
