### ISSUE TITLE
Overlapping Flutter- and browser-rendered text selection handles

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#118111] opened 2023-01-06 19:22 UTC
On mobile web, both the native browser and Flutter-rendered text selection handle are drawn on top of each other:

![Screenshot_20230106-111247](https://user-images.githubusercontent.com/389558/211083936-422b3ece-3a20-4048-af60-c2307f1ab5ae.png)

Also, it looks like the Flutter-drawn handle is no longer a pixel perfect match.  The color and size appear slightly off.

On iOS, I assume the same problem is happening, but maybe the Flutter-drawn handles are hidden behind the native ones.  The selection color seems off, possibly due to overlap, and the lower handle seems cut off.

![IMG_7412](https://user-images.githubusercontent.com/389558/211084993-26cb3519-c22f-40f1-9188-e60d3e78f94f.jpg)

### Steps to reproduce

1. Run any Flutter app with a text field, such as the one below.
2. Enter some text and tap to place the collapsed cursor somewhere.

Expected: Only one handle appears.
Actual: Two overlapping handles appear.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            TextField(),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by htoor3** [comment] 2023-01-12 18:35
Possibly a dupe of https://github.com/flutter/flutter/issues/99918

**Comment by yjbanov** [comment] 2023-01-12 19:20
Let's deduplicate.

**Closed by yjbanov** 2023-01-12 19:20 UTC
Labels: a: text input, platform-web
