### ISSUE TITLE
[desktop] Pass command line arguments through to Dart's 'main'

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#32986] opened 2019-05-19 09:11 UTC
## Use case
I am trying to build an image viewer for Linux desktop and I need to provide command line interface for the the application like most Linux applications

## Proposal
Currently any arguments passed to the built binary on desktop when executed from terminal just ignores command line arguments. The arguments passed to binary should be  available inside main() as shown below 

```
void main(List<String> args) {
  print('Arguments');
  print(args.toString());
  runApp(new MyApp());
}
```

The array printed should have "hi"

![screenshot](https://user-images.githubusercontent.com/12265908/57980057-9a33e300-7a43-11e9-9fd4-5cd7872e4e96.png)

**Comment by stuartmorgan** [comment] 2019-05-19 13:00
I'm not sure passing all arguments directly through to `main` is the eventual solution, but this is a use case we should think about how to facilitate. We may want to have the template runner store them for access by plugins (or possibly a system channel), for instance.

> the built binary on desktop

Note that you're conflating the `flutter-desktop-example` application with Flutter itself here. That particular runner ignores command line arguments, but it's perfectly possible right now for someone to make a runner that stores then, and a plugin to retrieve them.

**Comment by gspencergoog** [comment] 2019-08-07 04:55
I actually like the idea of passing the args through to the Dart main: it's how I would expect it to work. I've been working on an app that would like to be able to get command line arguments (right now I just have to hard-code them inside the source: not ideal, obviously).

**Comment by gspencergoog** [comment] 2019-08-08 02:19
In addition to passing command line arguments to AOT compiled apps, I'd also like to be able to pass arguments via `flutter run`: I've run into this before with the `assets-for-api-docs` repo, and I had to do some really unethical things to the `--route` parameter to make it work.  Ideally it would be something like `flutter run -- --my-args-go-here`

**Comment by stuartmorgan** [comment] 2019-08-08 02:42
That raises an interesting problem, because on mobile, Flutter expects command line arguments to be things like VM arguments, which obviously aren't the things we'd want to pass to the Dart code.

**Comment by gspencergoog** [comment] 2019-08-08 16:10
Yeah, right now it thinks those are target paths to run.  I suspect that for the `flutter run` case, we might need to have an argument that contains the arguments to pass (and quote them), e.g. `--command-args="--my-args-go-here"`.  But for the AOT compiled app, it should just pass the arguments through to the main.

**Comment by jonahwilliams** [comment] 2019-08-08 16:17
I think @zanderso had an idea on this a while back?

**Comment by zanderso** [comment] 2019-08-09 17:50
The engine already nearly understands a flag like `--command-args`. It's called `dart_entrypoint_args` in `engine/common/settings.h`. The missing piece is to wire it into the engine command line parsing in `flutter::SettingsFromCommandLine` in `engine/shell/common/switches.cc`. Then supposing that arguments to the desktop embedders are already going through `flutter::SettingsFromCommandLine`, we can plumb a similar `flutter run` flag through.

**Comment by stuartmorgan** [comment] 2020-02-25 20:16
> Then supposing that arguments to the desktop embedders are already going through `flutter::SettingsFromCommandLine`

This is exactly the thing that would problematic per my comment above. `SettingsFromCommandLine` assumes that we (the Flutter engine+tool, basically) "own" the command line arguments. If we're running in a context where we expect Flutter application developers to be able to define their own arguments, and end users to pass those arguments on the command line, then we can't just dump the command line into the engine's command line parser. We'd need the wrapper, or something like it.

**Comment by stuartmorgan** [comment] 2020-02-25 20:22
Also:
> The missing piece is to wire it into the engine command line parsing in flutter::SettingsFromCommandLine in engine/shell/common/switches.cc

We can't call that code in the desktop embeddings, because we use the embedding API. We should expose a way to set `dart_entrypoint_args` via that API, probably as a new `FlutterProjectArgs` field. (Which will be confusing, because there's already the unfortunate `command_line_argv` which does dump things directly into the engine switch parser.)

**Comment by gspencergoog** [comment] 2020-02-25 20:32
Related to #46005

**Comment by stuartmorgan** [comment] 2020-09-29 01:14
Summarizing the current state/plan:
- The desktop affordance for setting Flutter engine switches will be [environment variables](https://github.com/flutter/flutter/issues/60393#issuecomment-696940505)
- That leaves us free to treat all command line arguments as intended for the application itself, without needing to do any extra parsing/filtering. We should just need to add an `embedder.h` field to set `dart_entrypoint_args` (which per my comment above will be tricky to name), and then plumb that up through each desktop embedding.

**Comment by gw280** [comment] 2020-11-07 00:51
Closing as this is now implemented on all three platforms and in the flutter tool.

**Closed by gw280** 2020-11-07 00:51 UTC
Labels: P4, a: desktop, engine

**Comment by cosmotek** [comment] 2020-12-19 07:52
For what it's worth, if we ever want to offer protocol-handlers/custom scheme support for desktop, we're going to need the ability to pass args from the runner to the dart application. I do think @stuartmorgan has the right perspective here... a plugin-based implementation would allow us to keep the implementation (and potentially the interface) consistent across all platforms.

**Comment by blurymind** [comment] 2021-03-10 20:32
I am kind of confused. If we run this

`exportedFlutterApp.exe /path/to/file.jpg`

what would the flutter code be to open the file.jpg with exportedFlutterApp.exe

**Comment by stuartmorgan** [comment] 2021-03-10 20:43
```
void main(List<String> arguments) {
  if (arguments.isNotEmpty) {
    // Insert your code using arguments here.
  }
  ...
```

**Comment by blurymind** [comment] 2021-03-10 20:43
thank you :) I will give this a try
