### ISSUE TITLE
TextField obscure: true crashes on iOS simulator.

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#77946] opened 2021-03-11 18:24 UTC
On iOS the app is crashing, if we have the TextField with the property `obscure: true`.
Related issue: https://github.com/flutter/flutter/issues/62501

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Padding(
        padding: const EdgeInsets.all(10.0),
        child: Column(
          children: [
            Text(
                "Focus on the Password field and then click on done button from the Keyboard.\nThe app will crash."),

            // Text Field
            TextField(
              decoration: InputDecoration(
                hintText: "Password field",
              ),
              obscureText: true,
              textInputAction: TextInputAction.done,
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Mac OS X 10.15.6 19G2021
    darwin-x64, locale en-US)
    • Flutter version 2.1.0-10.0.pre at /Library/flutter
    • Framework revision cc9b78fc5c (2 weeks ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 11 Pro Max (mobile) • FCD33A06-2942-4D0A-823B-3DA28CB6BDAD • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```
</details>

Crash Report from the App:
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x7fff5129d40b objc_msgSend + 11
1  Flutter                        0x108b42cf5 -[TextInputSemanticsObject setSemanticsNode:] + 344
2  Flutter                        0x108b401d3 flutter::AccessibilityBridge::UpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) + 547
3  Flutter                        0x108b4a4e6 flutter::PlatformViewIOS::UpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) + 80
4  Flutter                        0x108ee965a std::__1::__function::__func<flutter::Shell::OnEngineUpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >)::$_37, std::__1::allocator<flutter::Shell::OnEngineUpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >)::$_37>, void ()>::operator()() + 108
5  Flutter                        0x108e691ba fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 160
6  Flutter                        0x108e6df38 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 26
7  CoreFoundation                 0x7fff23da2414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
8  CoreFoundation                 0x7fff23da20ae __CFRunLoopDoTimer + 1038
9  CoreFoundation                 0x7fff23da170a __CFRunLoopDoTimers + 282
10 CoreFoundation                 0x7fff23d9c35e __CFRunLoopRun + 1950
11 CoreFoundation                 0x7fff23d9b8a4 CFRunLoopRunSpecific + 404
12 GraphicsServices               0x7fff38c05bbe GSEventRunModal + 139
13 UIKitCore                      0x7fff49372964 UIApplicationMain + 1605
14 Agenda BOA                     0x107eea0ab main + 5 (AppDelegate.swift:5)
15 libdyld.dylib                  0x7fff5211c1fd start + 1
```

```
Fatal Exception: NSInvalidArgumentException
-[MTLSimCommandBuffer backingTextInputAccessibilityObject]: unrecognized selector sent to instance 0x7fc723c1fc20

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x7fff20421ae6 (Missing)
1  libobjc.A.dylib                0x7fff20177e78 objc_exception_throw
2  CoreFoundation                 0x7fff204306f7 (Missing)
3  CoreFoundation                 0x7fff20426036 (Missing)
4  CoreFoundation                 0x7fff20428068 (Missing)
5  Flutter                        0x11059acf5 (Missing)
6  Flutter                        0x1105981d3 (Missing)
7  Flutter                        0x1105a24e6 (Missing)
8  Flutter                        0x11094165a (Missing)
9  Flutter                        0x1108c11ba (Missing)
10 Flutter                        0x1108c5f38 (Missing)
11 CoreFoundation                 0x7fff20390c57 (Missing)
12 CoreFoundation                 0x7fff2039072a (Missing)
13 CoreFoundation                 0x7fff2038fcdd (Missing)
14 CoreFoundation                 0x7fff2038a35e (Missing)
15 CoreFoundation                 0x7fff203896d6 (Missing)
16 GraphicsServices               0x7fff2c257db3 (Missing)
17 UIKitCore                      0x7fff24696cf7 (Missing)
18 UIKitCore                      0x7fff2469bba8 (Missing)
19 Agenda BOA                     0x10f7b013b main + 5 (AppDelegate.swift:5)
20 libdyld.dylib                  0x7fff2025a3e9 (Missing)
21 ???                            0x1 (Missing)
```

https://user-images.githubusercontent.com/14223997/110835591-00e35a00-82c5-11eb-8d72-23cdc06ca3a1.mov

**Comment by darshankawar** [comment] 2021-03-12 09:56
Verified this on all latest channels and observed that, this crash occurs only on dev and master using simulator. The same code works properly if we run it on physical device (tested on iPhone 6s, iOS 14.3) with no crash.

Simulator : iphone 12 pro max : 14.3

1. Latest master using device:


https://user-images.githubusercontent.com/67046386/110923491-f8336800-8346-11eb-8ef5-201fd9af93b0.MP4


2. Latest stable using simulator:


https://user-images.githubusercontent.com/67046386/110923539-06818400-8347-11eb-8031-2419b704887f.mov



@deepak786 
Try to use a device on same channel and you shouldn't see the crash.

Cc: @LongCatIsLooong for further insights.

<details>
<summary>latest master and dev flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.227, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.227 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 66768f8c5b (6 hours ago), 2021-03-11 19:55:02 -0800
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-10.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision cc9b78fc5c (2 weeks ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.2
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by deepak786** [comment] 2021-03-12 10:15
@darshankawar I don't have the iOS device so I'm not able to test it on the real device.

According to your findings, the issue is only on the simulator and with only the master and dev channel, right?

**Comment by darshankawar** [comment] 2021-03-12 13:03
@deepak786 
I updated my previous comment to following:

`You may switch to latest beta or stable to continue with your work, where you can use the simulator.`

**Comment by LongCatIsLooong** [comment] 2021-03-12 17:57
looks like a duplicate of #77139

**Closed by LongCatIsLooong** 2021-03-12 17:57 UTC
Labels: in triage, waiting for customer response
