### ISSUE TITLE
Developers want to build Flutter apps on Windows (not deployment target)

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#138] opened 2015-11-09 21:18 UTC
Rough TODO list:
- [x] Make //flutter/snapshotter work on Windows.
- [x] Make the `flutter` command line tool work on Windows.
  - [X] Teach the `flutter.ps1` where to get the Dart SDK and how to bootstrap into Dart.
  - [x] Teach the tool about Windows as a host platform (e.g., where to find the snapshotter)
  - [x] Teach the tool how to control Android devices via `adb` on Windows.
- [ ] Infrastructure for continuously building and testing the Windows toolchain.

---

<a href="https://github.com/Scorpiion"><img src="https://avatars.githubusercontent.com/u/1047298?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Scorpiion](https://github.com/Scorpiion)**
_Sunday Aug 23, 2015 at 18:18 GMT_
_Originally opened as https://github.com/flutter/engine/issues/771_

---

I understand that Windows support is not prio 1 atm, but in the future, as a platform for developing Android apps (and maybe iOS apps), would it be possible to add Windows support? I understand that it would be some work, but basically what I'm asking is if it's part of the long term plan or simply ignored on purpose for some reason (other than maybe no devs on the team are using Windows..).

Even if I myself only use Linux (close to 10 years Linux only) I think it can be good for the project to support Windows in the long run, at Stackoverflow's latest developer survey Windows developers was still a little bit more that 50% (Mac and Linux at ~21% each): 
http://stackoverflow.com/research/developer-survey-2015#tech-os

The only reference of Windows I could find was this old comment in an old readme:
https://github.com/domokit/sky_engine/pull/165/files#r35055666

_And just to be extra clear and avoid any confusion, this issue is about developing Android and iOS apps on Windows, not deploying Sky to Windows Phone._

**Comment by FlutterIssues** [comment] 2015-11-09 21:18
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sethladd](https://github.com/sethladd)**
_Sunday Aug 23, 2015 at 20:43 GMT_

----

To be clear, are you asking to deploy to windows phone, windows desktop, or
simply develop on windows?

**Comment by FlutterIssues** [comment] 2015-11-09 21:19
<a href="https://github.com/Scorpiion"><img src="https://avatars.githubusercontent.com/u/1047298?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Scorpiion](https://github.com/Scorpiion)**
_Sunday Aug 23, 2015 at 21:39 GMT_

----

Hi @sethladd, _"simply develop on windows"_, yes.  

If anyone have a suggestion for a more clear issue name then be my guest and change it or tell me and I change it.

Edit: Added "(development host only, not deployment target)" to the topic for now.

**Comment by FlutterIssues** [comment] 2015-11-09 21:19
<a href="https://github.com/eseidel"><img src="https://avatars.githubusercontent.com/u/478541?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eseidel](https://github.com/eseidel)**
_Sunday Aug 23, 2015 at 22:12 GMT_

----

Yup.  It is definitely be possible to support Windows development of Sky apps (for running on mobile OSes for which there exist Windows SDKs) at some point in the future.  (Not clear one could develop Sky apps for iOS on windows ever for instance.)  Right now we're focused on polishing the actual deployed product first.  If the product isn't first awesome, it doesn't matter what development environments it supports. :)

**Comment by FlutterIssues** [comment] 2015-11-09 21:19
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sethladd](https://github.com/sethladd)**
_Monday Aug 24, 2015 at 03:16 GMT_

----

Thanks! Agreed... there are a ton of Windows developers.

**Comment by FlutterIssues** [comment] 2015-11-09 21:19
<a href="https://github.com/Scorpiion"><img src="https://avatars.githubusercontent.com/u/1047298?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Scorpiion](https://github.com/Scorpiion)**
_Monday Aug 24, 2015 at 08:45 GMT_

----

Thanks for the reply @eseidel, sounds great, I think the team have the right focus, looking forward to that initial awesome product! :+1:

**Comment by cooler-king** [comment] 2015-11-19 13:33
Now that Dart SDK 1.13.0 is released, are we getting close to adding support for developing on Windows?  The additional feedback from Windows devs will help you make flutter awesome.

**Comment by adaojunior** [comment] 2015-11-19 14:31
@cooler-king what does Dart 1.13.0 has that could help Flutter and Windows development ? (curious).
I'm currently using Windows, and I'm very interested in testing Flutter.

**Comment by cooler-king** [comment] 2015-11-19 14:39
@adaojunior Maybe nothing.  Just hoping for some movement on this issue.

**Comment by cooler-king** [comment] 2016-01-14 20:27
Any chance we could get an update on this one?  If the answer is still we'll get to it when we get to it, that's fine.  But if you have an estimated month or quarter (without any firm commitment) that would be better.

**Comment by adaojunior** [comment] 2016-01-14 21:31
@cooler-king Have you tried using it though a virtual box VM ?
I haven't yet but I may try in the future.

**Comment by cooler-king** [comment] 2016-01-14 21:47
@adaojunior I tried a couple of months ago to no avail.  Not to say it's impossible, but I couldn't get it fully working at that time.

**Comment by sethladd** [comment] 2016-01-15 16:58
Sorry, no updates. Thanks for checking in!

**Comment by DanTup** [comment] 2016-01-17 23:02
I'm curious about this too... There are some pull requests updating instructions on how to run this on Windows (using Python 2) so I'm a little confused about whether this works or not?

**Comment by abarth** [comment] 2016-01-18 22:12
> I'm a little confused about whether this works or not?

Does not currently work.  The sticking point is that we need to run a binary on the host to snapshot the Dart code before sending it to the target.  We don't have a build of this binary for Windows yet.

**Comment by eseidelGoogle** [comment] 2016-03-21 16:17
See also https://github.com/flutter/flutter/issues/1437

**Comment by mwalcott3** [comment] 2016-07-16 16:46
Does the Windows Subsystem for Linux help alleviate any of the problems in bringing Flutter to Windows?

**Comment by abarth** [comment] 2016-07-16 16:47
Very likely.

**Comment by alexantenna** [comment] 2016-08-16 22:01
Today I was able to manage to run everything in Oracle VirtualBox hosting Ubuntu/Debian. The only interesting and off-path part was to add USB filter for the phone to VirtualBox and to ensure you connect the phone after VM start but not earlier. I may clarify the experience if someone is interested :-)

**Comment by bbalet** [comment] 2016-08-17 13:06
Why don't you use PowerShell instead of BAT files? I saw in comments into flutter.bat that you are struggling with a lot of things that are natevily implemented in PS or .net

- PowerShell is part of Windows 7.
- It is used by chocolatey the package manager recommended by Dart Project for installing tools on Windows.
- It is far more easy for people behind a company proxy (see the examples with chocolatey).
- No need for external tools such as curl, etc.

**Comment by abarth** [comment] 2016-08-17 21:16
> Why don't you use PowerShell instead of BAT files?

That's probably a good idea.  We'd certainly welcome a patch that replaced our existing BAT file with PowerShell.

**Comment by bbalet** [comment] 2016-08-18 18:46
Ive pushed a PR with a PowerShell script that fix the BAT script in addition to provide an alternative (#5484). What exactly should be done to make it works on Windows? It looks that it is almost done, but they are some details failing. For example, **flutter doctor** tells me:

    Android SDK file not found: C:\Users\benjamin\AppData\Local\Android\sdk\platform-tools\adb

But this location is valid, moreover **flutter devices** works fine... Is it possible to list the tasks to do so as to complete this port?

**Comment by eseidelGoogle** [comment] 2016-08-18 19:10
@bbalet no one (to my knowledge) has looked at building a list of TODOs for making flutter development possible from Windows.  One big step will be that we'll need to start building/publishing sky_snapshot binaries (the binary run on the host to compile Dart code into ARM for the device) for Windows.  That would involve building https://github.com/flutter/engine on Windows, which although I'm sure is possible to make work hasn't been attempted to my knowledge.

**Comment by bbalet** [comment] 2016-08-20 12:14
I don't know the chromium building tool, but I've made some attempts.

In the source of the engine, windows platform is not defined in flutter/sky/shell/platform

In the contributing guide of flutter/engine, you should add the command *gclient runhooks* in order to get gn.exe (if i'm not mistaken).

In buildroot -> tools/dart/update.py

    +WINDOWS_64_SDK = 'dartsdk-windows-x64-release.zip'

    +  elif sys.platform.startswith('win'):
     +    sdk_url = SDK_URL_BASE + WINDOWS_64_SDK
     +    output_file = os.path.join(DART_SDK_DIR, WINDOWS_64_SDK)

In engine -> sky/tools/roll/roll.py (files_not_to_roll):

     + 'tools/android/VERSION_WINDOWS_NDK',
     + 'tools/android/VERSION_WINDOWS_SDK',

I don't know what is the process in charge of filling these files with what looks like a git revision or the hash of a distributed package (the content is not the same that what we can get from the git repo or from the binary release). Anyway, the two new files must be added but I don't know how and with what content.

As I said, I don't know the building tool, so I'm stuck with these errors:

    PS C:\tools\engine\src> python ./flutter/tools/gn --android --unoptimized
    gn gen --check in out\android_debug_unopt
    ERROR at //build/config/BUILDCONFIG.gn:589:5: Assertion failed.
        assert(false, "Unknown host for android cross compile")

And this one due to the fact that sky/shell is not yet implemented for Windows:

    PS C:\tools\engine\src> python ./flutter/tools/gn --unoptimized
    gn gen --check in out\host_debug_unopt
    ERROR at //flutter/sky/shell/BUILD.gn:487:3: Assertion failed.
      assert(false, "Unsupported platform")

**Comment by abarth** [comment] 2016-08-20 15:31
> In the source of the engine, windows platform is not defined in flutter/sky/shell/platform

We should try to get `//flutter/snapshotter` working first.  It has a lot less code in it and having the snapshotter will unblock developing on Windows.  (We only need sky_shell if we want to run tests on Windows hosts.)

> In buildroot -> tools/dart/update.py

That looks like a good patch.  Would you be willing to contribute it?

> I don't know what is the process in charge of filling these files with what looks like a git revision or the hash of a distributed package (the content is not the same that what we can get from the git repo or from the binary release)

For the change to buildroot, just send a pull request to https://github.com/flutter/buildroot and at-message me.  After the change lands, we'll need to update the DEPS file in engine.git, but I can take care of that mechanical step for you.

> python ./flutter/tools/gn --android --unoptimized

We don't need to cross-compile the Android bits from Windows.  We can build the Android bits from Linux or Mac, and that's sufficient.  What we need is to be able to build the sky_snapshot host binary for Windows.  That means we'll want to invoke:

`python ./flutter/tools/gn`

and use `is_windows` checks in the BUILD.gn file to limit the build to just `//flutter/snapshot`.  That should simplify the problem dramatically because there's much less code to build.

> And this one due to the fact that sky/shell is not yet implemented for Windows

Yes, the good news is that we don't need an implementation of sky_shell for Windows, at least not to get developers on Windows going.

**Comment by bbalet** [comment] 2016-08-20 15:41
Actualy you can reopen my patch https://github.com/flutter/buildroot/pull/3/files
Don't forget sky/tools/roll/roll.py once you've updated the DEPS file

**Comment by bbalet** [comment] 2016-08-20 18:36
I've update src/flutter/BUILD.gn:

      } else {
         if (current_os == "win") {
             deps = [
               "//flutter/snapshotter($host_toolchain)",
             ]    
           } else {
             deps = [
               "//flutter/sky",
             ]
         }
       }

I've install Visual Studio 2015 update 3 with the recommended options. But now I get this error:

    gn gen --check in out\host_debug
    Traceback (most recent call last):
    Traceback (most recent call last):
      File "C:/tools/engine/src/build/vs_toolchain.py", line 21, in <module>
      File "C:/tools/engine/src/build/vs_toolchain.py", line 21, in <module>
            import gyp
    import gyp
    ImportErrorImportError: : NNo module named gypo module named gyp
    Traceback (most recent call last):
    
      File "C:/tools/engine/src/build/vs_toolchain.py", line 21, in <module>
        import gyp
    ImportError: No module named gyp
    ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
          exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
          ^----------
    Current dir: C:/tools/engine/src/out/host_debug/
    Command: C:/Python27/python.exe C:/tools/engine/src/build/vs_toolchain.py get_toolchain_dir
    Returned 1.

I've set DEPOT_TOOLS_WIN_TOOLCHAIN to 0.

**Comment by bbalet** [comment] 2016-08-21 07:21
In order to solve the issue about Python module gyp, I had to install gyp (I don't know if it is the normal process, because I thought that gclient would install all dependancies):

    git clone https://chromium.googlesource.com/external/gyp
    cd gyp
    python ./setup.py install

But another error appeared and I've noticed that into `{build folder}/src/tools/gyp/pylib/gyp` there is only one file related to mac (again I don't know the building system, but I guess that a variable indicating that win is a supported platform is missing somewhere).

So I ended up to copy the content of `{gyp install}\gyp\build\lib\gyp` into `{build folder}/src/tools/gyp/pylib/gyp`

Now, when I run `python ./flutter/tools/gn`, I get this error:

    gn gen --check in out\host_debug
    ERROR at the command-line "--args":1:180: Build argument has no effect.
    use_glfw=false is_clang=true use_goma=false dart_experimental_interpreter=false
    use_aura=false is_debug=false dart_runtime_mode="develop" flutter_runtime_mode="
    debug" flutter_aot=false goma_dir="None" use_system_harfbuzz=false
                   ^----
    The variable "flutter_aot" was set as a build argument
    but never appeared in a declare_args() block in any buildfile.

**Comment by bbalet** [comment] 2016-08-21 09:29
I've solved the issue with the build file and I got one version that produces the ninja files:

        if (current_os == "win") {
            import("//flutter/common/config.gni")
            import("//flutter/lib/snapshot/toolchain.gni")
            deps = [
              "//flutter/assets",
              "//flutter/snapshotter",
              "//flutter/snapshotter($host_toolchain)",
            ]    
          } else {
            deps = [
              "//flutter/sky",
            ]
        }
      }

But it seems to require some mojo bindings and in DEPS file there is nothing for Windows (only Mac and Linux) for **mojom_tool** and **mojom_generators** sections. I don't know what to put into the parameters and if it exists on the server side (I mean on Google storage) because after some search, I'm unable to find an example of a DEPS file that uses win platform.

**Comment by binary132** [comment] 2016-12-14 20:51
This is relevant to my interests.  Is there any work in progress on this or where should I start?  I've read the thread and I'd like to know where help is needed right now. @abarth / @bbalet / @eseidelGoogle 

Is there some documentation I can dig into?

**Comment by Hixie** [comment] 2016-12-15 03:09
@binary132 the current state is basically what it says in the first comment in this bug.

**Comment by eseidelGoogle** [comment] 2016-12-28 18:37
FYI, I attempted to setup flutter very briefly just now with bash on windows 10 (and failed):
- Installed linux (http://www.windowscentral.com/how-install-bash-shell-command-line-windows-10)
- Installed git and unzip (`sudo apt-get install git unzip`)
- Cloned flutter `git clone https://github.com/flutter/flutter.git`
- Ran `flutter doctor`
Hangs indefinitely at "Building Flutter tool..."
Doctor with `-v` didn’t show anything.

**Comment by eseidelGoogle** [comment] 2016-12-28 19:10
Further investigation, turns out that it's `pub get` hanging inside flutter_tools.  Even when I ran it with -v it still just seemed to freeze w/o any error.  This may be folly attempting to get pub working inside Windows bash, may be better to use the normal cmd.exe.

**Comment by Hixie** [comment] 2016-12-28 19:12
I suspect on the medium term we will want to run in native cmd.exe windows anyway, just to limit our dependencies.

**Comment by mit-mit** [comment] 2017-01-18 13:18
+1 to getting things working in the standard windows Command Prompt. We current fail with a bunch of path issues:

```
C:\Users\Michael Thomsen>set PATH=%PATH%;"C:\Users\Michael Thomsen\flutter\bin"
C:\Users\Michael Thomsen>flutter doctor
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the file C:\Users\Michael.
Updating flutter tool...
'pub.bat' is not recognized as an internal or external command,
operable program or batch file.
'pub.bat' is not recognized as an internal or external command,
operable program or batch file.
'dart' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
'dart' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bbalet** [comment] 2017-01-18 13:43
> We current fail with a bunch of path issues

This is not related to this issue. You are missing some prequisites such as Dart (maybe not in the path or not installed). Even if your setup is complete, Flutter doesn't support Windows yet as the snapshotter has been ported to Windows.

**Comment by mit-mit** [comment] 2017-01-18 13:48
`flutter doctor` is expected to download Dart (like it does on Mac and Linux). But we need changes to the `\bin\flutter` script to make that work on Windows.

And, yes, we need snapshotter.

**Comment by artichokes** [comment] 2017-02-01 23:58
> We should try to get //flutter/snapshotter working first. It has a lot less code in it and having the snapshotter will unblock developing on Windows. (We only need sky_shell if we want to run tests on Windows hosts.)

I've generated `vs` files with `gn` and major issue is the dependencies on `fuschia/ftl`. The Fuchsia Template Library is highly platform dependent and only supports poisix systems.

**Comment by goderbauer** [comment] 2017-02-02 00:45
I am making good progress on this issue: I am currently able to compile a Flutter app on Windows and deploy it from Windows on Android (in other words: `flutter run --release` is pretty much working on Windows). Most of the bits and pieces are already checked in for that and I am working on resolving the remaining smaller issues. I also just started work on enabling the fast development refresh cycle ("hot reload" with `flutter run`). Once those two pieces are in, I'll provide some instructions for using Flutter on Windows for early adopters (sharp edges included). Watch this space for updates!

**Comment by davisnrjr** [comment] 2017-02-20 17:40
Hi goderbauer,

Are there some instructions on how the Flutter/Windows is to work with DART?  Please advise.  Appears to be possible, but I don't see a link to the solution.

**Comment by goderbauer** [comment] 2017-02-21 17:37
Hi @davisnrjr,
while many pieces are already in place, Windows support for Flutter is not 100% there yet. I am currently working on resolving the last few issues and once that is done, I will provide step-by-step instructions for using Flutter on Windows. Stay tuned!

**Comment by b-strauss** [comment] 2017-02-21 17:41
@goderbauer will this also make it possible to help in the development of the framework itself on windows?

**Comment by davisnrjr** [comment] 2017-02-21 20:34
Awesome

**Comment by davisnrjr** [comment] 2017-02-21 20:35
@goderbauer   Awesome, thx!!

**Comment by goderbauer** [comment] 2017-02-22 00:26
@b-strauss You will be able to make contributions to anything in the [flutter/flutter](https://github.com/flutter/flutter) repository from Windows. If you want to contribute to [flutter/engine](https://github.com/flutter/flutter), you are most likely limited to changes that don't effect the Flutter Android or iOS runtime as we currently don't have plans to make those runtimes compilable on Windows (they ship as a pre-built binary for users of the Flutter framework).

**Comment by eseidelGoogle** [comment] 2017-03-03 21:44
@goderbauer is progress far enough that we should close this and track with other (smaller) bugs?

**Comment by goderbauer** [comment] 2017-03-06 18:37
Today is the day! If you want, you can try out Flutter on Windows. I posted some [setup instructions](https://github.com/flutter/flutter/wiki/Flutter-on-Windows) to get started on Windows. Please be aware that Windows-support for Flutter is brand-new. **Do expect some sharp edges** and please [file bugs](https://github.com/flutter/flutter/issues/new) when you encounter them. There are [some known issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22%E2%9D%96+platform-windows%22), the two main ones are:

* Hot Reload is slower on Windows than it is on other platforms (#8513)
* The flutter test command is not supported on Windows (#8516)

[**I hope you follow these instructions to give Flutter on Windows a try**](https://github.com/flutter/flutter/wiki/Flutter-on-Windows).

Feel free to report back on this bug if that worked for you and you got your first Flutter app deployed from Windows.

**Comment by rbishop-bah** [comment] 2017-03-06 18:44
I've been building my app for days on Windows and most things work great!

Sometimes relaunching an app from Android Studio complains about needing to replace the APK and bad things happen if you let it... but if you just ignore it and retry until it stops complaining that seems to work.

**Comment by goderbauer** [comment] 2017-03-06 18:59
@rbishop-bah Thanks for confirming that things work. Can you please file a new bug for the Android Studio issue you are seeing with the exact error? Thanks.

**Comment by CoenB95** [comment] 2017-03-06 19:10
@goderbauer Thank you very much for paying so much effort of making Flutter available for developers on Windows like me. I can't wait until I have some time to try it out. One question: is it really necessary to install Android Studio, or do I only need the android_sdk? (forgive my English)

**Comment by goderbauer** [comment] 2017-03-06 19:18
@CoenB95 I believe, Android Studio is the only official way to get the Android SDK these days. In addition to using the Android SDK from Android Studio, Flutter also uses Gradle from Android Studio and possibly other components. In other words: in theory you probably don't need the full Android Studio installation, but you'd currently be on your own to figure out what components you would need to install instead and from where to get them. This is true for all platforms (Windows, Mac, Linux) that Flutter supports.

**Comment by b-strauss** [comment] 2017-03-06 19:22
![](http://68.media.tumblr.com/ced9c86f6dfc5ac3bbbec9fcdf5deee3/tumblr_o6s06q9fjO1tv4k5po1_500.gif)

**Comment by CoenB95** [comment] 2017-03-06 19:37
I see. I thought I only needed the sdk, which I could get using the standalone ADB tool, but if you say Grade is needed too, than I indeed wouldn't know where to get it from. Tomorrow I'll try it out using the IntelliJ plugin. If I don't forget it, I'll try to give feedback.

**Comment by b-strauss** [comment] 2017-03-06 20:50
@goderbauer You can also download the SDK separately. Do I need Android Studio, or is IntelliJ IDEA + Android Plugin enough?

**Comment by alexantenna** [comment] 2017-03-06 20:52
Cool, it works! Finally! Installed and configured everything as back-burner to other activities and it took only half an hour! Just hot-reloaded sample app on my cellphone. Thank you very much!

**Comment by goderbauer** [comment] 2017-03-06 21:23
@b-strauss: For the time being we require Android Studio to be installed if you want to target Android as Flutter uses some of its components to deploy on Android (this is true on all supported host platforms, not only Windows). You don't have to use Android Studio to write your code, though. For that we recommend IntelliJ + Dart Plugin + Flutter Plugin (see https://flutter.io/intellij-setup/).

Having said that, if you absolutely want, you could download and install the components Flutter requires from Android Studio separately. But that's not officially supported nor documented and might break at any time. You'd be on your own there.

**Comment by binary132** [comment] 2017-03-06 22:26
Bravo @goderbauer!

**Comment by b-strauss** [comment] 2017-03-06 23:48
Demo app works for me on Windows 10. \o/

**Comment by CoenB95** [comment] 2017-03-07 08:26
Good morning. I've just succeeded (yeey) to run flutter doctor. Some feedback so far:
- I could not use PowerShell right-away; it said "running scripts is disabled on this system" (tips welcome).
- Cmd did work. But first I needed to add a `PATH` so flutter could find Git (I used git bash, therefore it wasn't required earlier).
- The first time I tried, I had to interrupt the internet connection (Wifi on the bus was to slow) while "transferring BITS". This resulted in an endless loop instead of just failing where the doctor constantly retries to get a connection. Is this loop expected behavior, or should I open a issue (screenshot available)?
- Second try with better Wifi resulted in a success. All marks were checked (including already installed InteliJ-plugin), except the android_sdk which is to old according to flutter (shall update). I believe it is recommended to check regularly in order to keep that sdk up-to-date?

**Comment by jsiedentop** [comment] 2017-03-07 11:32
Hello CoenB95,
> I could not use PowerShell right-away; it said "running scripts is disabled on this system" (tips welcome)
For safty reasons it's not possible to run unsigned scripts by default. A Power Shell Script could do something unwanted on your system.

You can activate the execution with the following command:
`Set-ExecutionPolicy Unrestricted`

**Comment by rbishop-bah** [comment] 2017-03-07 12:31
Having some trouble running now after a flutter upgrade this morning: https://github.com/flutter/flutter/issues/8607

**Comment by goderbauer** [comment] 2017-03-07 20:55
@CoenB95

> I could not use PowerShell right-away; it said "running scripts is disabled on this system" (tips welcome).

In a PowerShell, execute `Set-ExecutionPolicy RemoteSigned` to allow running scripts. I am investigating if there is a better way, otherwise I will add this step to the setup instructions (see #8615).

> Cmd did work. But first I needed to add a PATH so flutter could find Git (I used git bash, therefore it wasn't required earlier).

The setup instructions say that you should make sure to have Git added to the PATH by the Git installer. I will add a note for people installing Git from other sources.

> The first time I tried, I had to interrupt the internet connection (Wifi on the bus was to slow) while "transferring BITS". This resulted in an endless loop instead of just failing where the doctor constantly retries to get a connection. Is this loop expected behavior, or should I open a issue (screenshot available)?

Please file a separate bug.

> Second try with better Wifi resulted in a success. All marks were checked (including already installed InteliJ-plugin), except the android_sdk which is to old according to flutter (shall update). I believe it is recommended to check regularly in order to keep that sdk up-to-date?

There shouldn't be a need to manually check this. The tool should tell you if it can't perform a certain action because the SDK is too old. You can update then.

**Comment by goderbauer** [comment] 2017-03-07 20:56
@rbishop-bah @jsiedentop I replied to your bugs on the issues you filed. Thanks for the reports.

**Comment by goderbauer** [comment] 2017-03-07 21:02
Thanks everybody for trying out Flutter on Windows and for reporting back. I am now going to close this issue as the main goal is achieved. Going forward, we will track the remaining work for Windows in other (smaller) [issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22%E2%9D%96+platform-windows%22).

If you encounter any new bugs, please open [new issues](https://github.com/flutter/flutter/issues/new) and don't reply to this one. Feel free to mention me in the issue, if it is related to Windows.

**Closed by goderbauer** 2017-03-07 21:02 UTC
Labels: dev: tool, new feature, ❖ platform-windows

**Comment by NicolasJacob** [comment] 2017-03-07 23:06
Windows support still refer to this pr in flutter website https://flutter.io/setup/
