### ISSUE TITLE
Texture rendering not real aspect ratio when i play 960x540 videos

### ISSUE THREAD

**Issue by wangp8895** [flutter/flutter#58138] opened 2020-05-28 03:16 UTC
I use https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/example to test my mp4 (960x540).
video link: 
Widgets code:
```
          Container(
            padding: const EdgeInsets.all(20),
            child: AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              child: Stack(
                alignment: Alignment.bottomCenter,
                children: <Widget>[
                  VideoPlayer(_controller),
                  _PlayPauseOverlay(controller: _controller),
//                  VideoProgressIndicator(_controller, allowScrubbing: true),
                ],
              ),
            ),
          ),
```
result:
![device-2020-05-28-103340](https://user-images.githubusercontent.com/16893328/83092219-6fa54d00-a0cf-11ea-9bef-f05feded84d7.png)

The width is larger than parent widget.

THS

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/lushijie/developer/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lushijie/android_sdk/
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/lushijie/android_sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Nexus 6P • 84B5T15A17001747 • android-arm64 • Android 8.1.0 (API 27)


```

**Comment by TahaTesser** [comment] 2020-05-28 12:46
Hi @wangp8895 

Just tested 960x540 aspect video in `video_player` https://imgur.com/a/YL3ndNq

<img width="219" alt="Screenshot 2020-05-28 at 6 10 21 PM" src="https://user-images.githubusercontent.com/48603081/83142771-920a8b00-a10e-11ea-9499-c1348fbb7822.png">

![flutter_01](https://user-images.githubusercontent.com/48603081/83142926-ce3deb80-a10e-11ea-90ea-40ef14aa5201.png)

```

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/test.mp4');

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.initialize().then((_) => setState(() {}));
    _controller.play();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

```

`video_player: ^0.10.11+1`

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F   • 32003c30dc19668f                     • android-arm64  • Android 10 (API 29)
    • iPhone 11  • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by wangp8895** [comment] 2020-05-29 02:31
@TahaTesser   thanks for answer
It is ok when i use iphone and android simulator.

simulator:
![device-2020-05-29-102228](https://user-images.githubusercontent.com/16893328/83214476-3e904f80-a197-11ea-9caf-a3db91dc7e8d.png)

Samsung Galaxy Note9:
![20200529-102357](https://user-images.githubusercontent.com/16893328/83214517-57006a00-a197-11ea-9d36-91e247deae8a.png)

Other phone has same problem!

**Comment by tsx1453** [comment] 2020-07-20 02:56
![2020_07_20_10_50_24](https://user-images.githubusercontent.com/24406775/87895148-3fe34780-ca77-11ea-81df-14beeae68a85.png)

i have the same problem when play low quality video with the video_player plugin,

```
[✓] Flutter (Channel unknown, v1.17.2, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/tian/development/environment/flutter
    • Framework revision 5f21edf8b6 (7 周前), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tian/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio
      4.0.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 4.0.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • MI 6X      • 49b6a9be   • android-arm64  • Android 9 (API 28)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Chrome     • chrome     • web-javascript • Google Chrome 84.0.4147.89
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by ds84182** [comment] 2021-03-09 02:05
This bug is not device specific. In fact, it happens on every physical device. The reason why this occurs is because the math used to handle the SurfaceTexture transformation matrix is incorrect.

The following code applies the transformation matrix to the image, not to the texture coordinates within the image: https://github.com/flutter/engine/blob/master/shell/platform/android/android_external_texture_gl.cc#L64

The documentation for getTransformMatrix explicitly specifies that the matrix maps texture coordinates in the range of [0, 1]. This transformation must be applied to texture coordinates, not to the image. https://developer.android.com/reference/android/graphics/SurfaceTexture#getTransformMatrix(float[])

When Android decodes video, it sometimes utilizes a texture larger than the actual video. When this happens, the pixels at the sides of the video repeat so texel sampling near edges gives the correct color. This is why you can see stretched colors at the bottom of incorrectly-transformed videos, which can be seen in @tsx1453 screenshot.

Since Flutter applies the crop transform matrix incorrectly, the end result is horizontal stretching of the video bounds. Combined with the larger backing texture size, videos are squashed vertically (due to using the entire texture height) and then subsequently stretched horizontally.

cc @chinmaygarde

**Comment by ds84182** [comment] 2021-03-09 02:08
Screenshot for reference:

I was working on a change to the video_player plugin to allow you to hint the viewport resolution. At extremely low resolutions (like 180p) the effect is very noticable.

![Screenshot_20210308-180554](https://user-images.githubusercontent.com/2268005/110407652-13496380-8039-11eb-8b87-1694da0580b2.png)

**Comment by maheshmnj** [comment] 2021-06-29 12:44
Hi @wangp8895,
Thanks for filing the issue, I verified on the latest stable version of flutter with ```video_player: ^2.1.6```, but I am not able to replicate the issue.  I would request you to upgrade to latest stable version of flutter and use the latest plugin and verify the issue.

<details>

<summary>Output</summary>

Network              |  Asset
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/123798984-5d669580-d905-11eb-9a18-ec3fbd3abda0.png)  |  ![](https://user-images.githubusercontent.com/31410839/123799010-622b4980-d905-11eb-8262-8606864df4ee.png)
</details>

**Comment by TahaTesser** [comment] 2021-07-21 12:15
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by ds84182** [comment] 2021-07-22 07:55
This is an issue that is device-specific, and does not reproduce on all devices. It also depends on the resolution of the video being played. I suggest testing with the video resolution above on the device used above to accurately reproduce this issue, as it still happens.

**Closed** 2022-08-05 00:12 UTC
Labels: e: device-specific, engine, plugin, p: first party, p: video_player, passed first triage, P4
