### ISSUE TITLE
[DUPLICATE] PopScope stopped working in conjunction with StatefulShellRoute.indexedStack after upgrading go_router from version 12.1.0 to 13.0.1

### ISSUE THREAD

**Issue by nunibye** [flutter/flutter#143172] opened 2024-02-08 18:57 UTC
### Steps to reproduce

I had stateful shell navigation with a bottom nav bar and I wanted to change android back button behavior to navigate to the home page instead of exiting the app. I achomplished this by wrapping each of the root pages in the StatefulShellBranch with PopScope (WillPopScope has the same behavior i tested). This worked as intended until i upgraded go_router to version 13.0.1. Here is my code:
Stopped working here: [https://github.com/nunibye/Eko/commit/51f1efb9a361cd599d907ac8d9a33bfca8ff63e1]
Fixed by rolling back go_router version here: [https://github.com/nunibye/Eko/commit/74f92ba89c01bbed7ee602ee98871e8939555b2c]

### Expected results

PopScope(canPop: false, child: ) should make it imposible to close the app with the back button in a StatefulShellBrach

### Actual results

There doesn't seem to be a way to affect behavior of the back button on root pages of a StatefulShellRoute.indexedStack.

### Code sample

<details open><summary>Code sample</summary>

```dart
StatefulShellRoute.indexedStack(
      builder: (context, state, navigationShell) {
        return ScaffoldWithNestedNavigation(navigationShell: navigationShell);
      },
      branches: [
        StatefulShellBranch(
          navigatorKey: _shellNavigatorFeedKey,
          routes: [
            GoRoute(
              path: '/feed',
              name: 'feed',
              pageBuilder: (context, state) {
                bool reload = false;
                if (state.extra is bool) reload = state.extra as bool;
                return NoTransitionPage(
//this does nothing in 13 but works in 12
                  child: PopScope(canPop: false,
child: FeedPage(
                    rebuild: reload,
                  ),
),
                );
              },),),)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22621.3007], locale en-US)
    • Flutter version 3.16.9 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (2 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\ereec\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.86.0)
    • VS Code at C:\Users\ereec\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.106

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by nunibye** [comment] 2024-02-08 21:37
This is a Duplicate issue.
https://github.com/flutter/flutter/issues/138737
https://github.com/flutter/flutter/issues/140869

**Comment by dam-ease** [comment] 2024-02-09 09:05
Hello @nunibye
Thanks for filing this. I see this is a duplicate of https://github.com/flutter/flutter/issues/138737. Kindly comment, upvote and follow up on the issue for updates.
Closing this from here, if you disagree, please comment and I'll reopen this.

**Closed by dam-ease** 2024-02-09 09:05 UTC
Labels: in triage
