### ISSUE TITLE
Flutter crashing after App kill / restart on iOS 14

### ISSUE THREAD

**Issue by mikel2405** [flutter/flutter#66422] opened 2020-09-23 06:03 UTC
We are using Flutter for various components in our native iOS and Android App.
For iOS 14 I've update flutter to the latest beta version 1.22.0-12.1.pre.
So far when launching the App and using the flutter components inside the App, everything is working fine.
However, once I'm killing and restarting the App, the flutter components are not longer working.
Using the debug version initially started from Xcode then killed and restart from Homescreen, the FlutterViewController simply does not open when I try to open a flutter component.
When I'm then starting from Xcode debugger again, everything is working fine.
So, I cannot debug the problem, as in the debugger everything is working....

The TestFlight App shows different behaviour. In this case, once I kill the App and restart, the App will crash when I'm trying to use a Flutter component. The is no way to get it working again then but to reinstall the app.
The only crashlog I'm getting from TestFlight shows rather strange and unrelated information as shown below:

<img width="388" alt="Bildschirmfoto 2020-09-23 um 07 52 13" src="https://user-images.githubusercontent.com/5472349/93972149-075f3300-fd72-11ea-8f32-16acb7e5b742.png">

I've been trying different workarounds like calling destroyContext on the FlutterEngine on applicationWillTerminate, but this just leads to a crash. 

At the moment I don't have a solution for this problem but to tell our users not to kill the App once launched...
I've also tested with the stable channel, but the results are even worse as the debug version immediately crashes on 2nd launch after kill.

**Comment by helloWorldGeorge** [comment] 2020-09-23 08:03
face the same issue, when I install the app with Xcode ,it would be crash at the second time .
But on the ios version lower than 14.0 ,app works ok every time;

**Comment by pedromassangocode** [comment] 2020-09-23 08:49
Hi @mikel2405 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample? 

If you believe it is some native-side code causing this, you can create a minimal sample project and push it to GitHub.
Thank you

**Comment by abaturyna** [comment] 2020-09-23 09:06
I am facing the same problem . 

flutter doctor (tried latest version from channels stable, master and ) : 

[✓] Flutter (Channel dev, 1.23.0-4.0.pre, on Mac OS X 10.15.6 19G73 x86_64, locale ru-BY)
    • Flutter version 1.23.0-4.0.pre at /Users/nastya/Dropbox/BUSINESS/Soft/flutter 1.2.13
    • Framework revision 83dd176777 (14 часов назад), 2020-09-22 12:04:44 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nastya/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.97

[✓] Connected device (3 available)
    • nastenka’s iPhone (mobile) • 00008030-000A113802E2802E • ios            • iOS 14.0
    • Web Server (web)           • web-server                • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

I looked at the logs of problem in ios analytics system settings : it is EXC_BAD_ACCESS (SIGSEGV)
KERN INVALID ADDRESS AT 0x0000000000000000

VM region info : 0 is not in any region. Bytes before following region : 4339826688

Termination signal : Segmentation fault : 11

**Comment by lecicdjuro** [comment] 2020-09-23 10:05
The same here

**Comment by lecicdjuro** [comment] 2020-09-23 10:05
This is a show stopper

**Comment by 77251380** [comment] 2020-09-23 12:54
The same issue to me, hope fix it as soon as possible!

**Comment by pedromassangocode** [comment] 2020-09-23 13:55
Using "add reaction" on the initial comment would increase priority while +1 comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself, use the [Subscribe] button to the top right instead.

**Comment by abaturyna** [comment] 2020-09-23 16:20
@mikel2405 please provide response to @pedromassangocode 
or 
@pedromassangocode  you can use my comment 7 hours ago . I am facing THE SAME issue.

**Comment by mikel2405** [comment] 2020-09-23 16:37
Here is my Flutter Doctor -v:

[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on macOS 11.0 20A5374g, locale de-DE)
    • Flutter version 1.22.0-12.1.pre at /Users/mikel/src/flutter
    • Framework revision 8b3760638a (vor 8 Tagen), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mikel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 3.6.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 3.6.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

• No issues found!


As I mentioned, we are using a native iOS App and embed certain flutter components. So, I can't launch is with flutter run -v.
We are using FlutterEngine / FlutterViewController:

## Initializing FlutterEngine
    FlutterEngine *fe = [[FlutterEngine alloc] initWithName:@"engine.flutter.smazing" project:nil];
    self.flutterEngine = fe;
    
    [self.flutterEngine runWithEntrypoint:nil];

    FlutterMethodChannel* sessionChannel = [FlutterMethodChannel methodChannelWithName:BRConstants.flutterMethodChannelSession binaryMessenger:self.flutterEngine.binaryMessenger];
    self.sessionChannel = sessionChannel;
    
    
    [sessionChannel setMethodCallHandler:^(FlutterMethodCall * _Nonnull call, FlutterResult  _Nonnull result) {
        if([call.method isEqualToString:BRConstants.flutterMethodGetSessionId]) {
            NSString *sessionId = C2CallPhone.currentPhone.sessionId;
            result(sessionId);
        } else {
            result(FlutterMethodNotImplemented);
        }
    }];
    
    [GeneratedPluginRegistrant registerWithRegistry:self.flutterEngine];

#####

FlutterViewController subclass:

@objc class BRFlutterViewController: FlutterViewController
{
    private var isSetMethodHandler = false
    private var methodCallChannel:FlutterMethodChannel! = nil
    private let settingsController = BRWalletSettingsViewController()
    private var currentRouteHint:String?
    
    @objc static func controller(withData data:Data, currentRouteHint:String? = nil) -> BRFlutterViewController? {
        let app = UIApplication.shared.delegate as? BRAppDelegate
        guard let flutterEngine = app?.flutterEngine else {
          return nil
        }
        
        if let fvc = flutterEngine.viewController as? BRFlutterViewController {
            fvc.currentRouteHint = currentRouteHint
            fvc.binaryMessenger.send(onChannel: BRConstants.flutterMessageChannelNavigation, message: data)
            return fvc
        }
        let flutterViewController = BRFlutterViewController.init(engine: flutterEngine, nibName: nil, bundle: nil)
        flutterViewController.modalPresentationStyle = .fullScreen
        flutterViewController.currentRouteHint = currentRouteHint
        flutterViewController.binaryMessenger.send(onChannel: BRConstants.flutterMessageChannelNavigation, message: data)
        return flutterViewController
    }
....

## Open About View in Flutter:

    func goToAboutMe() {
        let args:[String:Any] = [
            "route" : BRConstants.flutterRouteAboutMe
        ];
        
        do {
            let data = try JSONSerialization.data(withJSONObject: args, options: JSONSerialization.WritingOptions.prettyPrinted)
           if let fvc = BRFlutterViewController.controller(withData: data) {
                self.present(fvc, animated: true, completion: nil)
           }
        } catch {
          print(error.localizedDescription)
        }
    }


That's basically how we use it.

**Comment by mraleph** [comment] 2020-09-23 21:06
This sounds very much like https://github.com/flutter/flutter/issues/60657. 

If you have a debug mode Flutter application (or an application that embeds Flutter in debug mode) you can *only* launch it through XCode tooling (or via tools like `flutter run` or `ios-deploy` which wrap XCode tooling). If you try to launch it from Home screen it would crash. 

There are no fix available for this and none is planned. You can choose between:

- using XCode tooling (or via tools like `flutter run` or `ios-deploy`)  to launch the app in debug mode
- building the app in release/profile build if you want it to be launchable from Home screen.

/cc @xster @jmagman

**Comment by jmagman** [comment] 2020-09-23 21:50
@mraleph That's correct.  Documentation at https://flutter.dev/docs/development/ios-14#launching-flutter-with-flutter-tools.

There should be a message on your device when you launch from the app that says something like "In iOS 14+, Flutter application in debug mode can only be launched from Flutter tooling..."  Are you not seeing that @mikel2405?  The description just says "the FlutterViewController simply does not open when I try to open a flutter component."

**Comment by jmagman** [comment] 2020-09-23 21:51
Ah, this is add-to-app.

**Comment by pedromassangocode** [comment] 2020-09-24 08:06
@jmagman @mraleph since it is already specified in the docs, can this be closed? Or it should remain open for any reason?

Will label it for now!

**Comment by mraleph** [comment] 2020-09-24 09:01
Duplicate of #60657

**Closed by mraleph** 2020-09-24 09:01 UTC
Labels: a: existing-apps, e: OS Version specific, platform-ios, severe: fatal crash, t: xcode, tool

**Comment by mikel2405** [comment] 2020-09-24 10:02
> @mraleph That's correct. Documentation at https://flutter.dev/docs/development/ios-14#launching-debug-flutter-without-a-host-computer.
> 
> There should be a message on your device when you launch from the app that says something like "In iOS 14+, Flutter application in debug mode can only be launched from Flutter tooling..." Are you not seeing that @mikel2405? The description just says "the FlutterViewController simply does not open when I try to open a flutter component."
No, I do not see that message. Just nothing happens when I try to present the VC.

So, that explains it and it's ok.
I guess it can be closed, since I cannot reproduce the crash on the release version any longer.
