### ISSUE TITLE
Darwin: Downloaded executables cannot execute on host AND failed with exit code -4

### ISSUE THREAD

**Issue by MichelDiz** [flutter/flutter#33479] opened 2019-05-29 00:41 UTC
## Steps to Reproduce

MacOS Mojave 10.14.4

1. Install Flutter as says docs
2. Can Run normally any example app.
3. Doctor says there's is a missing config but I'm not sure about it.
4. I can't build a simple APK for test. I'm not sure if the missing config is related to the build error.
`flutter build apk`

BTW, https://github.com/flutter/flutter/issues/6207 don't help at all. I'm using Darwin.

## Logs

```bash
flutter build apk
Initializing gradle...                                              1,0s
Resolving dependencies...                                           1,4s
Dart snapshot generator failed with exit code -4                        
Snapshotting exited with non-zero exit code: -4                         
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       2,6s
Gradle task assembleRelease failed with exit code 1

```
```
(...)
                    writeReleaseApplicationId

                    Rules
                    -----
                    Pattern: clean<TaskName>: Cleans the output files of a task.
                    Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
                    Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to
                    a configuration.
                    1 actionable task: 1 executed
[  +57 ms] Resolving dependencies... (completed in 1,5s)
[        ] Running Gradle task 'assembleRelease'...
[   +2 ms] executing: [/Users/micheldiz/Documents/GitHub/dgraph/flutter_graphql_demo/android/]
/Users/micheldiz/Documents/GitHub/dgraph/flutter_graphql_demo/android/gradlew -Pverbose=true
-Ptarget=lib/main.dart -Ptrack-widget-creation=false -Pcompilation-trace-file=compilation.txt
-Ptarget-platform=android-arm assembleRelease
[ +813 ms] > Task :app:checkReleaseClasspath UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :path_provider:preBuild UP-TO-DATE
[        ] > Task :path_provider:preReleaseBuild UP-TO-DATE
[        ] > Task :path_provider:checkReleaseManifest UP-TO-DATE
[        ] > Task :path_provider:processReleaseManifest UP-TO-DATE
[        ] > Task :app:preReleaseBuild UP-TO-DATE
[        ] > Task :path_provider:compileReleaseAidl NO-SOURCE
[        ] > Task :app:compileReleaseAidl NO-SOURCE
[        ] > Task :path_provider:packageReleaseRenderscript NO-SOURCE
[        ] > Task :app:compileReleaseRenderscript UP-TO-DATE
[        ] > Task :app:checkReleaseManifest UP-TO-DATE
[        ] > Task :app:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :app:prepareLintJar UP-TO-DATE
[        ] > Task :app:cleanMergeReleaseAssets UP-TO-DATE
[+1382 ms] > Task :app:flutterBuildRelease FAILED
[        ] Dart snapshot generator failed with exit code -4
[   +1 ms] Snapshotting exited with non-zero exit code: -4
[  +35 ms] 10 actionable tasks: 1 executed, 9 up-to-date
[        ]          *********************************************************
[        ] WARNING: This version of path_provider will break your Android build if it or its dependencies
aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error
may be unrelated.
[        ]          *********************************************************
[ +365 ms] Running Gradle task 'assembleRelease'... (completed in 2,6s)
[   +3 ms] "flutter apk" took 5.570ms.
[        ] "flutter apk" took 5.570ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:478:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:346:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:51:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:559:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

```
bash-5.0$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale pt-BR)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)
```

**Comment by MichelDiz** [comment] 2019-05-29 00:52
```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
```

```
bash-5.0$ git clean -xfd
Removing .DS_Store
Removing .idea/
(...)
Removing version
bash-5.0$ git stash save --keep-index
Saved working directory and index state WIP on stable: 7a4c33425 cherry-pick: fix edge swiping and dropping back at starting point (#31623)
bash-5.0$ git stash drop
Dropped refs/stash@{0} (c1ec09134e2f2fea99b8c385d814a80a66b23173)
bash-5.0$ git pull
remote: Enumerating objects: 1757, done.
remote: Counting objects: 100% (1757/1757), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 2885 (delta 1750), reused 1752 (delta 1750), pack-reused 1128
Receiving objects: 100% (2885/2885), 1.25 MiB | 1.50 MiB/s, done.
Resolving deltas: 100% (2288/2288), completed with 661 local objects.
From https://github.com/flutter/flutter
   0ba67226e..7c811b6a6  dev                                 -> origin/dev
   eb996afaa..c56b45518  master                              -> origin/master
 * [new branch]          revert-33163-tests_cleanup_1        -> origin/revert-33163-tests_cleanup_1
 * [new branch]          revert-33230-bug_31691              -> origin/revert-33230-bug_31691
 * [new branch]          revert-33297-add_to_app_measurement -> origin/revert-33297-add_to_app_measurement
 * [new tag]             v1.6.5                              -> v1.6.5
 * [new tag]             v1.6.0                              -> v1.6.0
 * [new tag]             v1.6.1                              -> v1.6.1
 * [new tag]             v1.6.2                              -> v1.6.2
 * [new tag]             v1.6.3                              -> v1.6.3
 * [new tag]             v1.6.4                              -> v1.6.4
Already up to date.
bash-5.0$ flutter doctor
Downloading Dart SDK from Flutter engine 52c7a1e849a170be4b2b2fe34142ca2c0a6fea1f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  120M  100  120M    0     0  4592k      0  0:00:26  0:00:26 --:--:-- 4548k
Building flutter tool...
Downloading package sky_engine...                                   0,7s
Downloading common tools...                                         2,5s
Downloading common tools...                                         2,6s
Downloading darwin-x64 tools...                                     6,8s
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale pt-BR)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by kangwang1988** [comment] 2019-05-29 02:42
Duplicate of https://github.com/flutter/flutter/issues/6207

**Closed by kangwang1988** 2019-05-29 02:42 UTC

**Comment by MichelDiz** [comment] 2019-05-29 02:49
@kangwang1988 isn't duplicated. That issue #6207 talks about Linux. I'm using Mac. That issue there's no solution for Mac...

**Comment by MichelDiz** [comment] 2019-05-29 02:57
BTW, an issue from 2016? 2 years and half and still happening?
If one thing still happens years later, the old issue should no longer be considered. After all it was not solved and yet it was closed, assuming it was resolved. Come on, two years? and still hanging on "Link to an issue" that doesn't help everyone really?

This should be fixed and not use an issue as "troubleshooting". This is disappointing.

**Comment by kangwang1988** [comment] 2019-05-29 06:26
@MichelDiz 
Never mind, you can still comment below that issue https://github.com/flutter/flutter/issues/6207 .
It's better to track under that issue, just as the `flutter doctor` says.
