### ISSUE TITLE
GoogleSignIn.disconnect()/SignIn hangs or becomes stuck for iOS when using IsolateHandler.spawn<T>()

### ISSUE THREAD

**Issue by nicodumdum** [flutter/flutter#63583] opened 2020-08-12 16:43 UTC
## Steps to Reproduce

I am using the `google_sign_in` plugin to login to my app using a Google account.

1. I login using this method:
```dart
Future<void> _onLoginWithGoogleButtonPressed() async {
    ...
      final GoogleSignIn googleSignIn = GoogleSignIn(
        scopes: <String>[
          'email',
        ],
      );
      GoogleSignInAccount googleAccount;

      try {
        googleAccount = await googleSignIn.signIn();

        if (googleAccount != null) {
        ...
```
It works just fine for both Android and iOS.

2. However, when I logout using this method:
```dart
Future<void> _onLogoutButtonPressed() async {
    ...
            final GoogleSignIn googleSignIn = GoogleSignIn();
            if (await googleSignIn.isSignedIn())
              await googleSignIn.disconnect(); // Stuck here in iOS.
            ...
```
It works just fine for Android but it becomes stuck indefinitely in the `GoogleSignIn.disconnect()` method for iOS.
It does not throw any errors, it just becomes stuck indefinitely until I force close the app.

**Expected results:** To finish logging out and proceed to login screen.

**Actual results:** Stuck in log out process.

<details>
  <summary>Logs</summary>

### pubspec.yaml
```
name: sssi_lgu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 10.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_init: ^0.1.2
  after_layout: ^1.0.7+2
  barcode_image: ^1.1.0
  connectivity: ^0.4.9
  device_info: ^0.4.2+4
  easy_localization: ^2.3.2
  flip_card: ^0.4.4
  flutter_facebook_login: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_speed_dial: ^1.2.5
  google_sign_in: ^4.5.1
  isolate_handler: ^0.3.1
  http: ^0.12.1
  logger: ^0.9.1
  meta: ^1.1.8
  package_info: ^0.4.1
  path_provider: ^1.6.11
  photo_view: ^0.9.2
  progress_dialog: ^1.2.4
  qr_flutter: ^3.2.0
  quiver: ^2.1.3
  responsive_builder: ^0.2.0+2
  shared_preferences: ^0.5.8
  simple_gesture_detector: ^0.1.4
  sqflite: ^1.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path_android: "assets/images/sssi_logo_square.png"
  image_path_ios: "assets/images/sssi_logo_square_ios.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - locales/
    - assets/fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


```

### flutter analyze
```

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Marvins-Mac-mini:flutter_sssi_lgu yuri$ flutter analyze
Analyzing flutter_sssi_lgu...                                              

   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MyProgressDialog._myProgressDialogState •
          lib/components/my_progress_dialog.dart:4:7 • must_be_immutable
   info • The value of the local variable 'shortestSide' isn't used • lib/pages/id_card/id_card_page.dart:207:18 • unused_local_variable
   info • The value of the local variable 'orientation' isn't used • lib/pages/id_card/id_card_page.dart:213:23 • unused_local_variable
   info • The declaration '_generateIdCardFront' isn't referenced • lib/pages/id_card/id_card_page_2.dart:141:16 • unused_element
   info • The declaration '_generateIdCardBack' isn't referenced • lib/pages/id_card/id_card_page_2.dart:176:16 • unused_element
   info • The value of the local variable 'idCardTemplateFile' isn't used • lib/pages/id_card/id_card_page_2.dart:247:18 • unused_local_variable
   info • The value of the local variable 'profilePictureFile' isn't used • lib/pages/id_card/id_card_page_2.dart:271:22 • unused_local_variable
   info • The value of the local variable 'fontFile' isn't used • lib/pages/id_card/id_card_page_2.dart:285:22 • unused_local_variable
   info • The value of the local variable 'profilePictureFile' isn't used • lib/pages/id_card/id_card_page_2.dart:507:22 • unused_local_variable
   info • The value of the local variable 'fontFile' isn't used • lib/pages/id_card/id_card_page_2.dart:521:22 • unused_local_variable
   info • The value of the local variable 'a' isn't used • lib/pages/id_card/id_card_page_2.dart:627:18 • unused_local_variable
   info • The value of the local variable 'shortestSide' isn't used • lib/pages/id_card/id_card_page_2.dart:735:18 • unused_local_variable
   info • The value of the local variable 'screenWidth' isn't used • lib/pages/id_card/id_card_page_2.dart:740:18 • unused_local_variable
   info • The value of the local variable 'orientation' isn't used • lib/pages/id_card/id_card_page_2.dart:741:23 • unused_local_variable
   info • The value of the local variable 'loginResult' isn't used • lib/pages/id_card/id_card_page_2.dart:1092:25 • unused_local_variable
   info • The value of the local variable 'refreshResult' isn't used • lib/pages/id_card/id_card_page_2.dart:1220:27 • unused_local_variable
   info • The value of the local variable 'a' isn't used • lib/pages/login/login_form.dart:447:14 • unused_local_variable
   info • The value of the local variable 'shortestSide' isn't used • lib/pages/login/login_page.dart:67:18 • unused_local_variable
   info • The value of the local variable 'orientation' isn't used • lib/pages/login/login_page.dart:73:23 • unused_local_variable
   info • The value of the local variable 'shortestSide' isn't used • lib/pages/password_reset/password_reset_page.dart:40:18 • unused_local_variable
   info • The value of the local variable 'orientation' isn't used • lib/pages/password_reset/password_reset_page.dart:46:23 • unused_local_variable
   info • Unused import: 'package:flutter_facebook_login/flutter_facebook_login.dart' • lib/pages/splash/splash_page.dart:4:8 • unused_import
   info • The value of the local variable 'shortestSide' isn't used • lib/pages/splash/splash_page.dart:66:18 • unused_local_variable
   info • The value of the local variable 'screenWidth' isn't used • lib/pages/splash/splash_page.dart:71:18 • unused_local_variable
   info • The value of the local variable 'orientation' isn't used • lib/pages/splash/splash_page.dart:72:23 • unused_local_variable
   info • Avoid using braces in interpolation when not needed • lib/services/my_pretty_printer.dart:38:29 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/my_pretty_printer.dart:39:29 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/my_pretty_printer.dart:40:17 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/my_pretty_printer.dart:44:28 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/my_pretty_printer.dart:45:16 • unnecessary_brace_in_string_interps

30 issues found. (ran in 28.5s)
Marvins-Mac-mini:flutter_sssi_lgu yuri$ 
```

### flutter doctor -v
```

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Marvins-Mac-mini:flutter_sssi_lgu yuri$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-PH)
    • Flutter version 1.17.5 at /Users/yuri/Desktop/PRJ/flutter
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 18FC5455-66B4-43C3-8D26-3F7F8B1A5D91 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 2 categories.
Marvins-Mac-mini:flutter_sssi_lgu yuri$ 
```

### flutter run --verbose
[flutter run.txt](https://github.com/flutter/flutter/files/5064264/flutter.run.txt)

</details>

**Comment by TahaTesser** [comment] 2020-08-13 09:00
Hi @nicodumdum 
Tried on latest `stable`, it disconnects successfully with no issues on `google_sign_in: ^4.5.1`

Please try this code sample on latest `stable`

<details> 
<summary>main.dart</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String userName;
  bool iSignedIn = false;
  GoogleSignInAccount _currentUser;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        setState(() {
          iSignedIn = true;
          userName = account.displayName;
        });
      }
    });
    _googleSignIn.signInSilently().then((value) {
      if (value != null) {
        setState(() {
          userName = value.displayName;
        });
      }
    });
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Container(
              child: Text(iSignedIn ? userName : 'empty user name'),
            ),
            FlatButton(
                onPressed: () async {
                  if (await _googleSignIn.isSignedIn())
                    _googleSignIn
                        .disconnect()
                        .then((value) => print('disconnected'));
                },
                child: Text('disconnect'))
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        icon: Icon(Icons.add),
        label: Text(iSignedIn ? 'Sign Out' : 'Sign In'),
        onPressed: () {
          if (!iSignedIn) {
            _handleSignIn();
          } else {
            _googleSignIn.signOut();
            setState(() {
              iSignedIn = false;
            });
          }
        },
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 2ae34518b8 (7 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 13.6

• No issues found!
```

</details> 


I cannot reproduce this issue on latest dev channel.
Can you upgrade to `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by nicodumdum** [comment] 2020-08-14 15:43
Hi,

I tried running your sample code in my existing environment (Flutter 1.17.5) and it actually worked fine.
So I went back to my working code and started tinkering as to what might have caused this abnormal behavior and I figured that it only becomes stuck in `GoogleSignIn.disconnect()` method only after spawning an isolate using the `IsolateHandler.spawn<T>()` method from the `isolate_handler: ^0.3.1` plugin. My app does this multiple heavy image processing within isolates after logging in. I would like to mention that I do properly dispose my running isolates after they are done processing by using the `IsolateHandler.kill()` method so I am not sure how it could affect the Google sign in.

I modified your sample code to include some minimal test codes for the `isolate_handler` plugin and ran it in my existing environment (Flutter 1.17.5) to confirm my suspicion and I was able to reproduce my issue.

## Steps to Reproduce
1. I logged in using `GoogleSignIn.signIn()`.
2. Then spawned an isolate using `IsolateHandler.spawn<T>()`.
3. Then waited for the isolate to finish.
4. Then called `IsolateHandler.kill()` to dispose the isolate.
5. Then signed out using `disconnect()`.
6. And then it got stuck there.

<details>
  <summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:isolate_handler/isolate_handler.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String userName;
  bool iSignedIn = false;
  GoogleSignInAccount _currentUser;
  IsolateHandler isolates = IsolateHandler();
  int counter = 0;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        setState(() {
          iSignedIn = true;
          userName = account.displayName;
        });
      }
    });
    _googleSignIn.signInSilently().then((value) {
      if (value != null) {
        setState(() {
          userName = value.displayName;
        });
      }
    });
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Container(
              child: Text(iSignedIn ? userName : 'empty user name'),
            ),
            FlatButton(
                onPressed: () async {
                  // Start the isolate at the `entryPoint` function.
                  isolates.spawn<int>(entryPoint,
                      name: "counter",
                      // Executed every time data is received from the spawned isolate.
                      onReceive: setCounter,
                      // Executed once when spawned isolate is ready for communication.
                      onInitialized: () =>
                          isolates.send(counter, to: "counter"));
                },
                child: Text('spawn isolate')),
            FlatButton(
                onPressed: () async {
                  if (await _googleSignIn.isSignedIn())
                    _googleSignIn
                        .disconnect()
                        .then((value) => print('disconnected'));
                },
                child: Text('disconnect')),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        icon: Icon(Icons.add),
        label: Text(iSignedIn ? 'Sign Out' : 'Sign In'),
        onPressed: () {
          if (!iSignedIn) {
            _handleSignIn();
          } else {
            _googleSignIn.signOut();
            setState(() {
              iSignedIn = false;
            });
          }
        },
      ),
    );
  }

  // Set new count and display current count.
  void setCounter(int count) {
    counter = count;
    print("Counter is now $counter");

    // We will no longer be needing the isolate, let's dispose of it.
    isolates.kill("counter");
  }
}

// This function happens in the isolate.
void entryPoint(Map<String, dynamic> context) {
  // Calling initialize from the entry point with the context is
  // required if communication is desired. It returns a messenger which
  // allows listening and sending information to the main isolate.
  final messenger = HandledIsolate.initialize(context);

  // Triggered every time data is received from the main isolate.
  messenger.listen((count) {
    // Add one to the count and send the new value back to the main
    // isolate.
    messenger.send(++count);
  });
}
```
</details>

I would appreciate if you could try it to see if you could reproduce my issue as well using the modified sample code.

For a last bit of hope, I also tried the modified sample code in the latest Flutter 1.20.2 but unfortunately it showed the same behavior/issue.

I'm not sure how to go about this. I hope you can help me.

Thanks!

**Comment by TahaTesser** [comment] 2020-08-17 07:45
HI @nicodumdum 
Thanks for providing clear details and steps to reproduce, i can reproduce the issue using code sample and steps, also notice i cannot sign in again after `IsolateHandler` 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 7c6f9dd239 (8 days ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.125

• No issues found!
```

</details>

**Comment by tananga** [comment] 2021-07-09 07:04
Any updates for this issue ?

**Comment by huycozy** [comment] 2023-02-01 12:05
I'm verifying this issue on the latest Flutter master using `google_sign_in: ^5.4.4`, on both `iPhone 7, iOS 15.7.2` and `Samsung Galaxy Tab A7 Lite, Android 13`, it works as expected. 


| iOS | Android |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/216037419-5f304932-e62c-4ee9-b562-23cc7b38f14e.MP4"/> | <video src="https://user-images.githubusercontent.com/104349824/216037427-df30e655-6a93-403a-af73-924ad5a120dd.mp4"/>

<details>
<summary>Sample code (be compatible with the new flutter version)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:isolate_handler/isolate_handler.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String? userName;
  bool iSignedIn = false;
  GoogleSignInAccount? _currentUser;
  IsolateHandler isolates = IsolateHandler();
  int counter = 0;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount? account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        setState(() {
          iSignedIn = true;
          userName = account?.displayName;
        });
      }
    });
    _googleSignIn.signInSilently().then((value) {
      if (value != null) {
        setState(() {
          userName = value.displayName;
        });
      }
    });
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Container(
              child: Text(iSignedIn ? (userName ?? '') : 'empty user name'),
            ),
            TextButton(
                onPressed: () async {
                  // Start the isolate at the `entryPoint` function.
                  isolates.spawn<int>(entryPoint,
                      name: "counter",
                      // Executed every time data is received from the spawned isolate.
                      onReceive: setCounter,
                      // Executed once when spawned isolate is ready for communication.
                      onInitialized: () =>
                          isolates.send(counter, to: "counter"));
                },
                child: Text('spawn isolate')),
            TextButton(
                onPressed: () async {
                  if (await _googleSignIn.isSignedIn())
                    _googleSignIn
                        .disconnect()
                        .then((value) => print('disconnected'));
                },
                child: Text('disconnect')),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        icon: Icon(Icons.add),
        label: Text(iSignedIn ? 'Sign Out' : 'Sign In'),
        onPressed: () {
          if (!iSignedIn) {
            _handleSignIn();
          } else {
            _googleSignIn.signOut();
            setState(() {
              iSignedIn = false;
            });
          }
        },
      ),
    );
  }

  // Set new count and display current count.
  void setCounter(int count) {
    counter = count;
    print("Counter is now $counter");

    // We will no longer be needing the isolate, let's dispose of it.
    isolates.kill("counter");
  }
}

// This function happens in the isolate.
void entryPoint(Map<String, dynamic> context) {
  // Calling initialize from the entry point with the context is
  // required if communication is desired. It returns a messenger which
  // allows listening and sending information to the main isolate.
  final messenger = HandledIsolate.initialize(context);

  // Triggered every time data is received from the main isolate.
  messenger.listen((count) {
    // Add one to the count and send the new value back to the main
    // isolate.
    messenger.send(++count);
  });
}
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (3 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Dolphin 2021.3.1.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio Dolphin 2021.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio Electric Eel 2022.1.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.8.0-1.0.pre.3, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.8.0-1.0.pre.3 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3894d24816 (17 minutes ago), 2023-02-01 00:03:13 -0500
    • Engine revision 1703a39662
    • Dart version 3.0.0 (build 3.0.0-187.0.dev)
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Dolphin 2021.3.1.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio Dolphin 2021.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
</details>

I'll be closing this issue since it has already been fixed on the latest plugin version. If anyone still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2023-02-01 12:05 UTC
Labels: platform-ios, plugin, severe: performance, p: first party, p: google_sign_in, has reproducible steps, P4, found in release: 1.21
