### ISSUE TITLE
> Channel dev, 3.4.0-17.2.pre

### ISSUE THREAD

**Issue by RonyBrosh** [flutter/flutter#141014] opened 2024-01-05 11:29 UTC
> Channel dev, 3.4.0-17.2.pre

@cristianormoraes You are on a decommissioned channel of flutter. Latest available channels are `stable`,`beta` and `master`. So I recommend you to switch to either of them with latest version (ex: `flutter channel stable`, `flutter upgrade --force`) and check if you still see same behavior or not.
Closing for now.

_Originally posted by @darshankawar in https://github.com/flutter/flutter/issues/118059#issuecomment-1373317462_

I have the same behaviour on stable channel:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3.2)
[✓] VS Code (version 1.85.1)
Sc[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: /Users/ron.brosh/Library/Android/sdk/platform-tools/adb
[✓] Network resources

! Doctor found issues in 1 category.

I can run adb only when restarting my laptop..

**Comment by dam-ease** [comment] 2024-01-05 12:15
Hi @RonyBrosh  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2024-01-05 12:15 UTC
Labels: in triage
