### ISSUE TITLE
Unable to get text from obscured text form field on Flutter Web

### ISSUE THREAD

**Issue by chrisnorman7** [flutter/flutter#93624] opened 2021-11-14 20:16 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Enter a password.
3. Click the "Show Password" button.

**Expected results:** 

The resulting dialog should show the password you have entered.

**Actual results:** 

On Windows with the latest Chrome, I see all except the final character replaced with the bullet symbol.

On Android, I see the expected password.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final rendererBinding = RendererBinding.instance;
    if (rendererBinding != null) {
      rendererBinding.setSemanticsEnabled(true);
    }
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  /// Create an instance.
  const MyHomePage({Key? key}) : super(key: key);

  /// Create state for this widget.
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

/// State for [MyHomePage].
class _MyHomePageState extends State<MyHomePage> {
  final _formKey = GlobalKey<FormState>();
  final _passwordController = TextEditingController();

  /// Build a widget.
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(
        key: _formKey,
        child: ListView(
          children: [
            ListTile(
              title: TextFormField(
                controller: _passwordController,
                autocorrect: false,
                enableSuggestions: false,
                obscureText: true,
                decoration: const InputDecoration(labelText: 'Password'),
              ),
            ),
            ListTile(
              title: ElevatedButton(
                onPressed: () => showDialog(
                    context: context,
                    builder: (context) => AlertDialog(
                          title: const Text('Password'),
                          content: Text(_passwordController.text),
                          actions: [
                            TextButton(
                                onPressed: () => Navigator.pop(context),
                                child: const Text('OK'))
                          ],
                        )),
                child: const Text('Show Password'),
              ),
            )
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _passwordController.dispose();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +45 ms] executing: [C:\Users\chris\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +168 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3dab5550407a2c2fe70a762acfdfde93311148de
[        ] executing: [C:\Users\chris\flutter/] git tag --points-at 3dab5550407a2c2fe70a762acfdfde93311148de
[  +34 ms] Exit code 0 from: git tag --points-at 3dab5550407a2c2fe70a762acfdfde93311148de
[        ] 2.8.0-3.1.pre
[   +6 ms] executing: [C:\Users\chris\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\Users\chris\flutter/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +75 ms] executing: [C:\Users\chris\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +46 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] Skipping pub get: version match.
[  +75 ms] Generating C:\Users\chris\src\BA\poc\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +88 ms] Launching lib\main.dart on Chrome in debug mode...
[  +65 ms] Updating assets
[  +53 ms] Waiting for connection from debug service on Chrome...
[  +41 ms] <- reset
[   +5 ms] C:\Users\chris\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\chris\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\chris\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\chris\AppData\Local\Temp\flutter_tools.15df0a4\flutter_tool.a50e9ba3\app.dill --libraries-spec file:///C:/Users/chris/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\chris\src\BA\poc\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\chris\AppData\Local\Temp\flutter_tools.15df0a4\flutter_tools.ddc4a2d4 --filesystem-scheme org-dartlang-app --initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///C:/Users/chris/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +5 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+10316 ms] Waiting for connection from debug service on Chrome... (completed in 10.4s)
[        ] Synced 28.4MB.
[        ] <- accept
[        ] Caching compiled dill
[ +184 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:1102/devtools/browser/169e0e49-4b25-45b6-9512-1fb921e215c6
[ +250 ms] DwdsInjector: Received request for entrypoint at http://localhost:1097/main_module.bootstrap.js
[   +3 ms] MetadataProvider: Loading debug metadata...
[   +7 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +3 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:1097/main_module.bootstrap.js
[+1465 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +44 ms] DevHandler: Debug service listening on ws://127.0.0.1:1125/wUfc7BwSjS0=/ws

[  +13 ms] This app is linked to the debug service: ws://127.0.0.1:1125/wUfc7BwSjS0=/ws
[   +6 ms] Debug service listening on ws://127.0.0.1:1125/wUfc7BwSjS0=/ws
[        ]  Running with sound null safety 
[   +1 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[        ] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:1125/wUfc7BwSjS0=
[ +768 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:1125/wUfc7BwSjS0=
[+13729 ms] DevHandler: Stopped debug service on ws://127.0.0.1:44456

[ +142 ms] Application finished.
[   +2 ms] "flutter run" took 27,434ms.
[  +13 ms] ensureAnalyticsSent: 11ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing poc...                                                
No issues found! (ran in 1.2s)
```

```
[ÔêÜ] Flutter (Channel beta, 2.8.0-3.1.pre, on Microsoft Windows [Version 10.0.19043.1348], locale en-GB)
    ÔÇó Flutter version 2.8.0-3.1.pre at C:\Users\chris\flutter
    ÔÇó Upstream repository https://github.com/flutter/flutter.git
    ÔÇó Framework revision 3dab555040 (2 days ago), 2021-11-12 11:50:00 -0800
    ÔÇó Engine revision 09f1520e8b
    ÔÇó Dart version 2.15.0 (build 2.15.0-268.8.beta)

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    ÔÇó Android SDK at C:\Users\chris\AppData\Local\Android\sdk
    ÔÇó Platform android-31, build-tools 31.0.0-rc2
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ÔÇó All Android licenses accepted.

[ÔêÜ] Chrome - develop for the web
    ÔÇó Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[ÔêÜ] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    ÔÇó Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    ÔÇó Visual Studio Community 2019 version 16.9.31129.286
    ÔÇó Windows 10 SDK version 10.0.19041.0

[ÔêÜ] Android Studio (version 2020.3)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    ÔÇó Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ÔÇó Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    ÔÇó Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[ÔêÜ] VS Code, 64-bit edition (version 1.62.2)
    ÔÇó VS Code at C:\Program Files\Microsoft VS Code
    ÔÇó Flutter extension version 3.27.0

[ÔêÜ] Connected device (4 available)
    ÔÇó Pixel 5 (mobile)  ÔÇó 08131FDD4003WG ÔÇó android-arm64  ÔÇó Android 12 (API 31)
    ÔÇó Windows (desktop) ÔÇó windows        ÔÇó windows-x64    ÔÇó Microsoft Windows [Version 10.0.19043.1348]
    ÔÇó Chrome (web)      ÔÇó chrome         ÔÇó web-javascript ÔÇó Google Chrome 95.0.4638.69
    ÔÇó Edge (web)        ÔÇó edge           ÔÇó web-javascript ÔÇó Microsoft Edge 95.0.1020.30

ÔÇó No issues found!
```

</details>

**Comment by oravecz** [comment] 2021-11-14 22:37
```
Flutter 2.7.0-3.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fc7015e35a (3 weeks ago) • 2021-10-27 15:18:41 -0700
Engine • revision a75e3b80f9
Tools • Dart 2.15.0 (build 2.15.0-178.1.beta)
```

MacOS - Works Fine
Chrome Version 95.0.4638.54 (Official Build) (arm64) - Fails like you describe

![image](https://user-images.githubusercontent.com/297712/141701310-e7ca2b45-0899-425e-81b7-634297ce427a.png)

**Comment by danagbemava-nc** [comment] 2021-11-15 07:21
Duplicate of #90794

**Closed by danagbemava-nc** 2021-11-15 07:21 UTC
Labels: in triage

**Comment by chrisnorman7** [comment] 2021-11-15 08:54
OK, thanks for the heads up.

Take care,

Chris Norman
