### ISSUE TITLE
Font rendered differently on Android and iOS

### ISSUE THREAD

**Issue by tahooki** [flutter/flutter#145069] opened 2024-03-13 08:49 UTC
![image](https://github.com/flutter/flutter/assets/15773636/18da1a69-775e-477e-b8af-f72f046ea298)

This is a case where a font is added to flutter and the text is displayed by specifying a style in the Text widget.
Android and iOS render differently.

![image](https://github.com/flutter/flutter/assets/15773636/4f7eaeb2-a877-40d5-a622-1c66130dea7b)

When rendering a font in Flutter, isn't it rendered in the same shape?

I am using Flutter with the expectation that it will be able to provide the same UI for each device.
This part is a bit important to me, so I hope you can help.

**Comment by huycozy** [comment] 2024-03-13 10:33
Hi @tahooki, please try to provide all information indicated in the template so that we can address the issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)). More specifically, please provide the following information:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using 3rd packages or production code to represent the issue
- The output of `flutter doctor -v`
- Please also check if the issue persists without using a custom font (Line)

**Comment by tahooki** [comment] 2024-03-14 04:35
# 대답하기

Thank you. My concern was whether this issue is a bug or if it's normal behavior for fonts, and how to address it in such cases.

Let me explain in more detail!

I'm using an Android Galaxy 20 and an iOS 14 Pro simulator.

## Here's the output from Flutter Doctor -v:

```jsx
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.3 22E252 darwin-arm64, locale ko-KR)
    • Flutter version 3.16.0 on channel stable at /Users/tahooki/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (4 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tahooki/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • SM G998N (mobile)      • R3CR10L5HMV                          • android-arm64  • Android 14 (API 34)
    • iPhone 14 Pro (mobile) • 7F7C0AF9-5409-49EF-9E03-404E0525A661 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.
```

## **Here is the code information used:**

### **This is the button style code:**

```jsx
static get buttonText => TextStyle(
        color: Color(0XFFFFFFFF),
        fontSize: 15.fSize,
        fontFamily: "Line",
        fontWeight: FontWeight.w700,
      );
```

### **The following is the button code:**

The text part specifies the CustomTextStyles.buttonText style through the Text widget.

```jsx
import 'package:flutter/material.dart';
import 'package:happy/core/app_export.dart';
import 'package:happy/widgets/base_button.dart';

class CustomElevatedButton extends BaseButton {
  final bool? isLoading;

  CustomElevatedButton({
    Key? key,
    this.decoration,
    this.leftIcon,
    this.rightIcon,
    EdgeInsets? margin,
    VoidCallback? onPressed,
    ButtonStyle? buttonStyle,
    Alignment? alignment,
    TextStyle? buttonTextStyle,
    bool? isDisabled,
    double? height,
    double? width,
    this.isLoading = false,
    this.loadingColor,
    required String text,
  }) : super(
          text: text,
          onPressed: onPressed,
          buttonStyle: buttonStyle,
          isDisabled: isDisabled,
          buttonTextStyle: buttonTextStyle,
          height: height,
          width: width,
          alignment: alignment,
          margin: margin,
        );

  final BoxDecoration? decoration;

  final Widget? leftIcon;

  final Widget? rightIcon;

  final isRound = false;

  final Color? loadingColor;

  @override
  Widget build(BuildContext context) {
    return alignment != null
        ? Align(
            alignment: alignment ?? Alignment.center,
            child: buildElevatedButtonWidget,
          )
        : buildElevatedButtonWidget;
  }

  Widget get buildElevatedButtonWidget => Container(
        height: this.height ?? 44.v,
        width: this.width ?? double.maxFinite,
        margin: margin,
        decoration: decoration,
        child: ElevatedButton(
          style: isDisabled == true
              ? buttonStyle?.copyWith(
                  backgroundColor: MaterialStateProperty.all(appTheme.gray300),
                  //border
                  side: MaterialStateProperty.all(
                    BorderSide(
                      color: appTheme.gray300,
                      width: 1,
                    ),
                  ),
                )
              : buttonStyle,
          onPressed: isDisabled ?? false ? null : onPressed ?? () {},
          child: isLoading == false
              ? Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    leftIcon != null ? SizedBox(width: 20.h) : Container(),
                    leftIcon ?? const SizedBox.shrink(),
                    rightIcon != null ? SizedBox(width: 40.h) : Container(),
                    Flexible(
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Container(
                            decoration: BoxDecoration(
                              color: Colors.black45,
                            ),
                            child: Text(
                              text,
                              style: buttonTextStyle ??
                                  CustomTextStyles.buttonText,
                            ),
                          ),
                        ],
                      ),
                    ),
                    leftIcon != null ? SizedBox(width: 40.h) : Container(),
                    rightIcon ?? const SizedBox.shrink(),
                    rightIcon != null ? SizedBox(width: 20.h) : Container(),
                  ],
                )
              : Center(
                  child: Container(
                    width: 20.h,
                    height: 20.h,
                    child: CircularProgressIndicator(
                      strokeWidth: 2.h,
                      valueColor: AlwaysStoppedAnimation<Color>(
                          loadingColor ?? appTheme.white),
                    ),
                  ),
                ),
        ),
      );
}

```

## **Checking without using a custom font**

I tried using the Roboto font, and it seemed to center align well on both devices.

```jsx
static get buttonText => TextStyle(
        color: Color(0XFFFFFFFF),
        fontSize: 15.fSize,
        fontFamily: "Roboto",
        fontWeight: FontWeight.w700,
      );
```

![image](https://github.com/flutter/flutter/assets/15773636/5d86dd0e-771b-4d7c-afa9-72294563b30e)

However, there seems to be a slight difference in the thickness.

I wish to display the same UI on different devices, even with fonts.

Below are the fonts I used.
[LINESeedKR-Bd.ttf.zip](https://github.com/flutter/flutter/files/14596683/LINESeedKR-Bd.ttf.zip)


I would appreciate any help with this!

**Comment by huycozy** [comment] 2024-03-14 07:54
There are some issues around here:

>However, there seems to be a slight difference in the thickness

This could be an issue with [Impeller](https://docs.flutter.dev/perf/impeller) (Impeller is enabled on iOS by default), please see some similar issues: https://github.com/flutter/flutter/issues/138386, https://github.com/flutter/flutter/issues/138670.

>My concern was whether this issue is a bug or if it's normal behavior for fonts, and how to address it in such cases.
>I tried using the Roboto font, and it seemed to center align well on both devices.

It could be an issue with typography on a specific font as you tested on Roboto and Line fonts that we need to investigate. 

-----

Your sample code is production code so I minimize it into this one for checking. Below are results on Android and iOS (checking on the latest Flutter stable channels)

| Android | iOS |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/f3501e8e-0efb-4c79-99a4-40c80cecbc9d"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/844a96d8-8bd0-42fc-8578-620dc4c20a0c">

| Android | iOS |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/3b641c9d-52f5-4cde-b7d0-775e7f0832e0"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/d051b8a3-b5b0-4f38-80a0-055b58689033">

On iOS the text is thinner but the height is not as obvious a difference as your original demo. So, to make the issue more clearly, could you please check:

- Disable Impeller on (`flutter run --no-enable-impeller`) and compare results between Android and iOS
- Try with below `Minimal sample code`. If the issue doesn't occur with this code, perhaps some properties cause the issue. You should narrow it down into your code to find it.
- Upgrading/Switching to the latest Flutter stable/master channels and retry. 


<details>
<summary>Minimal sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Container(
            alignment: Alignment.center,
            color: Colors.blue,
            width: double.maxFinite,
            height: 40.0,
            child: TextButton(
              child: const Text('안녕하세요 세계',
                  style: TextStyle(
                    color: Color(0XFFFFFFFF),
                    fontSize: 15.0,
                    fontFamily: "Line",
                    fontWeight: FontWeight.w700,
                  )),
              onPressed: () {},
            ),
          ),
        ),
      ),
    ),
  );
}

```
</details>

**Comment by tahooki** [comment] 2024-03-16 03:48
### Thank you for answer.

I tested again with the code you mentioned.

I confirmed that the problem is the same and is rendered differently on iOS and Android.

The result I want is
1. IOS and Android are rendered identically
2. Fonts are centered

but number 2 is not important.

Number 1 is very important. I wonder if there is a way to solve this.

Otherwise, it looks like I will have no choice but to branch the Text widget to Android and iOS. If I had to develop like this, I would lose one of the main reasons why I chose Flutter over ReactNative.

### Here's what I tested:

I ran it with flutter run --no-enable-impeller.
| Platform | Image |
|-----|-----|
| ![image](https://github.com/flutter/flutter/assets/15773636/5b4dd1a8-7aab-4281-b541-08281fef509d) | ![KakaoTalk_Photo_2024-03-16-12-43-27](https://github.com/flutter/flutter/assets/15773636/1ab566de-81f4-4ccb-a926-31e3f998d73d) |

**Comment by huycozy** [comment] 2024-03-18 05:36
Okay, let's only focus on `thickness` rendering issue. I can see the font is not rendered identically on Android and iOS. This is more visible when the Impeller is not turned on.

### --no-enable-impeller

| Android | iOS |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/10858fe5-f377-4cc6-80f5-ee7266f319b4"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/15b92a45-80f0-4f9a-9720-3f6bae6b0c24">


### --enable-impeller

| Android | iOS |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/13f2124c-3fd6-4cee-8460-a585e7dd586f"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/a38a71d4-a133-4c28-bf6e-eef94991c190">

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 hours ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.21.0-9.0.pre.33, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.21.0-9.0.pre.33 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dd865ce476 (2 hours ago), 2024-03-17 20:24:27 -0400
    • Engine revision 89c7759639
    • Dart version 3.4.0 (build 3.4.0-242.0.dev)
    • DevTools version 2.33.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by tahooki** [comment] 2024-03-18 14:46
@huycozy 
Thank you for your interest in my issue.

I hope this issue is resolved!

**Comment by jonahwilliams** [comment] 2024-03-18 17:55
The font rendering differences could likely come from CoreText vs Freetype. We cannot promise identical font rendering across platforms (or even across different machines on the same platform).

**Comment by jonahwilliams** [comment] 2024-03-18 17:56
Closing because I don't think there is anything actionable here.

**Closed by jonahwilliams** 2024-03-18 17:56 UTC
Labels: engine, a: internationalization, a: typography, c: rendering, has reproducible steps, team-engine, found in release: 3.19, found in release: 3.21

**Comment by tahooki** [comment] 2024-03-19 01:03
Unfortunately, I understand. Similar to me, many people will approach fonts thinking they will be rendered the same, so I should write a post dealing with this and let them know.

**Comment by Stitch-Taotao** [comment] 2024-03-19 09:25
This implies that even if all platforms use the same rendering engine, whether it’s Impeller or Skia, font rendering and visual consistency may still vary. Is it impossible to change the future?
The most critical factor is that the layout and size of text will inevitably lead to differences in UI layout.

**Comment by tahooki** [comment] 2024-03-25 04:38
@Stitch-Taotao Yes, I have to change it, but it hasn't changed that it's become difficult to choose a pretty font.
