### ISSUE TITLE
I don't set divider, but the CustomScrollView has one pixels divider between slivers

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#43878] opened 2019-10-31 04:20 UTC
flutter --version

```
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (7 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```

dart code

```dart
          child: CustomScrollView(
            anchor: 0.5,
            slivers: <Widget>[
              SliverToBoxAdapter(
                child: SizedBox(
                  width: double.infinity,
                  height: MediaQuery.of(context).padding.top +
                      kToolbarHeight +
                      114.0 +
                      42.5,
                  child: Stack(
                    children: <Widget>[
                      Align(
                        alignment: Alignment.bottomCenter,
                        child: ClipPath(
                          clipper: _BannerClipper(offset: 10.0),
                          child: Container(
                            color: Colors.white,
                            height: 42.5 + 10.0,
                          ),
                        ),
                      ),
                      Align(
                        alignment: Alignment.bottomCenter,
                        child: Image(
                          image: NetworkImage(_imageUrl),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.white.withOpacity(0.99),
                  height: 11,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.white,
                  height: 200,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.white,
                  height: 200,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.blue,
                  height: 200,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.amber,
                  height: 200,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.cyan,
                  height: 200,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.black,
                  height: 200,
                ),
              ),
            ],
          ),
```

screenshot

![screenshot](https://raw.githubusercontent.com/v7lin/bug-report/master/flutter_01.png)

**Comment by dmvvilela** [comment] 2019-11-05 21:32
I want to know how to remove this too

**Comment by goderbauer** [comment] 2019-11-06 23:14
Duplicate of https://github.com/flutter/flutter/issues/14288.

**Closed by goderbauer** 2019-11-06 23:14 UTC
Labels: d: stackoverflow, framework
