### ISSUE TITLE
crash AndroidProject._regenerateLibrary FileSystemException: FileSystemException: Deletion failed, path = '……….android' 

### ISSUE THREAD

**Issue by tianyingzhong** [flutter/flutter#35975] opened 2019-07-11 10:44 UTC
flutter --no-color packages get

## exception

FileSystemException: FileSystemException: Deletion failed, path = '………\.android' (OS Error: 系统找不到指定的路径。
, errno = 3)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      _deleteIfExistsSync (package:flutter_tools/src/project.dart:459:15)
#4      AndroidProject._regenerateLibrary (package:flutter_tools/src/project.dart:436:5)
#5      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:400:7)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:144:19)
<asynchronous suspension>
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:84:23)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by jmagman** [comment] 2019-09-19 03:21
This looks like a duplicate of https://github.com/flutter/flutter/.  Thanks!

**Comment by jmagman** [comment] 2019-09-19 03:22
Actually ……….android is weird, re-opening.

**Comment by blasten** [comment] 2020-01-04 01:23
This one does seem like duplicate of #28319, should we close this one?

**Comment by jmagman** [comment] 2020-01-04 01:41
@tianyingzhong I know you filed this a long time ago, but does this look the same as https://github.com/flutter/flutter/issues/28319?  Did it really say `……….android` or were you redacting the path for us?

**Comment by jmagman** [comment] 2020-01-15 20:00
Closing as duplicate of https://github.com/flutter/flutter/issues/28319.

**Closed by jmagman** 2020-01-15 20:00 UTC
Labels: a: existing-apps, tool, waiting for customer response, ▣ platform-android
