### ISSUE TITLE
The ExpansionTile with a TextField in the title has undesirable behavior when the space bar is pressed

### ISSUE THREAD

**Issue by csells** [flutter/flutter#63722] opened 2020-08-13 23:21 UTC
## Steps to Reproduce
1. Run 'flutter create foo'
2. Update the [code to have an ExpansionTile with a TextField in the title](https://gist.github.com/csells/d082e0cccba14c93e8e639d8bf4ed980).
3. Run.
4. Type into the TextField using spaces.

**Expected results:**
I expect that the TextField has focus and it handles all of the input itself, including spaces.

**Actual results:**
- The ExpansionList is shown as having focus w/ a grey background.
- Entering a space into the TextField shows a splash effect.
- Entering a space into the TextField toggles the expanded state of the ExpansionTile.

![expansion_list_space](https://user-images.githubusercontent.com/2568253/90196410-8aa76500-dd80-11ea-8749-eace56b6916b.gif)
 

<details>
  <summary>Logs</summary>
no exceptions show in Debug output at runtime.

there are no analyzer issues

```
➜ flutter doctor -v
Downloading android-arm-profile/darwin-x64 tools...                 0.7s
Downloading android-arm-release/darwin-x64 tools...                 0.5s
Downloading android-arm64-profile/darwin-x64 tools...               0.4s
Downloading android-arm64-release/darwin-x64 tools...               0.4s
Downloading android-x64-profile/darwin-x64 tools...                 0.5s
Downloading android-x64-release/darwin-x64 tools...                 0.5s
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.15.6 19G73, locale en)
    • Flutter version 1.21.0-9.0.pre at /Users/csells/flutter
    • Framework revision 7c6f9dd239 (4 days ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/csells/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

**Comment by csells** [comment] 2020-08-13 23:21
cc @goderbauer

**Comment by TahaTesser** [comment] 2020-08-14 11:42
<details> 
<summary>main.dart</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  static const title = 'Flutter App';
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: title,
        theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: HomePage(),
      );
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text(App.title)),
        body: ExpansionTile(
          title: TextField(),
          children: [Text('child')],
        ),
      );
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
 [✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 7c6f9dd239 (5 days ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.125

• No issues found!

```

</details>

**Comment by goderbauer** [comment] 2020-08-14 17:57
In general it seems undesirable that a keypress which has already been interpreted by a text field can (also) activate a shortcut.

cc @gspencergoog Do we have a way for the textfield to swallow key-presses that it handled?

**Comment by gspencergoog** [comment] 2020-08-17 17:28
Yes, this is a duplicate of https://github.com/flutter/flutter/issues/47156 Please follow that issue for updates.

**Closed by gspencergoog** 2020-08-17 17:28 UTC
Labels: a: desktop, a: text input, f: material design, found in release: 1.21, framework, has reproducible steps
