### ISSUE TITLE
Gradle build failed to produce an Android package.

### ISSUE THREAD

**Issue by CocoaZX** [flutter/flutter#39799] opened 2019-09-04 06:36 UTC
VSCode & AndroidStudio can't run flutter application.
AndroidStudio can run native application

## Logs
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
/Users/crow/Desktop/Sale.mobile/sale_manage/android/app/src/main/AndroidManifest.xml has replace package.
/Users/crow/Desktop/Sale.mobile/sale_manage/android/app/src/main/java/com/xq/wormhole/saleManageDevelop/MainActivity.java has replace package.
/Users/crow/Desktop/Sale.mobile/sale_manage/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java has replace package.
/Users/crow/Desktop/Sale.mobile/sale_manage/android/app/src/main/res/drawable/launch_background.xml has replace package.
/Users/crow/Desktop/Sale.mobile/sale_manage/android/app/src/main/res/values/strings.xml has replace package.
/Users/crow/Desktop/Sale.mobile/sale_manage/android/app/src/main/res/values/styles.xml has replace package.
/Users/crow/Desktop/Sale.mobile/sale_manage/android/app/src/main/res/xml/file_paths.xml has replace package.
/Users/crow/Desktop/Sale.mobile/sale_manage/android/app/src/main/res/xml/network_security_config.xml has replace package.
build.gradle has replace package.
Gradle build failed to produce an Android package.
Exited (sigterm)
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/crow/Desktop/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/crow/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0
      (API 27) (emulator)
    • iPhone X                  • 7340321C-FC76-4BC5-AD33-E4C267561295 • ios         • iOS 12.1
      (simulator)

• No issues found!
```

**Comment by CocoaZX** [comment] 2019-09-04 06:37
I see many people has this issue, Can u push a stable patch？

**Comment by CocoaZX** [comment] 2019-09-04 06:38
Other solutions no use to me

**Comment by zanderso** [comment] 2019-09-04 20:04
@blasten @mklim It looks like we're throwing a tool exit, but not giving guidance on what the corrective action is in this case. Can the tool exit give some more advice here?

**Comment by Andrewx987** [comment] 2019-09-19 06:36
I have exactly the same error , please need a fix!

**Comment by blasten** [comment] 2019-09-19 15:32
@CocoaZX I'm curious about the version of Gradle and the Android Gradle plugin that you are using.  To find this out, paste the content of `<app>/android/build.gradle` and `<app>/android/gradle/wrapper/gradle-wrapper.properties`.

**Comment by Andrewx987** [comment] 2019-09-19 18:47
For me i have in the wrapper the 4.10.2 version and using the build.gradle at 3.3.0

**Comment by Andrewx987** [comment] 2019-09-19 18:49
I guess that the Flutter.graddle could be the problem in

**Comment by Andrewx987** [comment] 2019-09-19 19:20
This should show: 
```
 Gradle build failed to produce an Android package

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:857:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

**Comment by CocoaZX** [comment] 2019-09-20 05:26
build.gradle use 'com.android.tools.build:gradle:3.2.1'

here is gradle-wrapper.properties 

#Tue Sep 03 14:30:13 CST 2019
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

**Comment by CocoaZX** [comment] 2019-09-20 05:37
I update flutter, and create a new project , copy all code. It's a different error come



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.asynclayoutinflater:asynclayoutinflater' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
AndroidX incompatibilities may have caused this build to fail. See https://goo.gl/CP92wY.
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by ArtfulDodgerB92** [comment] 2019-10-18 02:04
I am having this exact issue after updating flutter, dart, android studio and the gradle version recently.   Entire dev environment broken on two different machines (a win 7 machine and a win 10 laptop).   I have been trying all day every day this week to resolve this issue, wasted a whole week of my life on this so far.   Trying to use older versions of the gradle but the error never changes:

```
[   +1 ms] 30 actionable tasks: 4 executed, 26 up-to-date
[ +362 ms] Running Gradle task 'assembleDebug'... (completed in 12.9s)
[   +5 ms] "flutter run" took 61,604ms.
Gradle build failed to produce an Android package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:758:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

It feels like something is corrupted somewhere, and it will not matter from this point what version of the gradle I try and use, but not sure where this corruption might be.   If it helps, my flutter doctor:

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17763.805], locale en-AU)
    • Flutter version 1.9.1+hotfix.4 at c:\Installations\Flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Installations\AndroidSDK\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Installations\AndroidSDK\
    • Java binary at: C:\Installations\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Installations\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM G970F • XXXXXX • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by ku4nc4** [comment] 2019-11-01 06:36
`[ +336 ms] Running Gradle task 'assembleDevuniversalDebug'... (completed in 21.2s)
[  +10 ms] "flutter run" took 26,269ms.
Gradle build failed to produce an Android package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:758:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)`

and this is my flutter doctor

`[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /home/jasonkuanca/Documents/dev/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jasonkuanca/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at:
      /home/###/Documents/dev/android-studio-ide-191.5900203-linux/andro
      id-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at
      /home/###/Documents/dev/android-studio-ide-191.5900203-linux/andro
      id-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)

• No issues found!`

On my case vanilla flutter app both regular and androidx runs fine.

**Comment by gwsh** [comment] 2019-12-26 14:33
I have the same problem Please fix it! !!👍

**Comment by quetool** [comment] 2020-01-03 20:34
I am getting the same issue, I am solving by generating bundle/apk from android studio. Don't know why flutter produce this issue now, everything was going well till last week

**Comment by jonahwilliams** [comment] 2020-02-28 01:06
Duplicate of https://github.com/flutter/flutter/issues/13977

**Closed by jonahwilliams** 2020-02-28 01:06 UTC
Labels: a: quality, severe: crash, t: gradle, tool
