### ISSUE TITLE
Support for Reorderable Gridview

### ISSUE THREAD

**Issue by brightseagit** [flutter/flutter#85334] opened 2021-06-25 17:32 UTC
## Use case

For reordering widgets in a Gridview, it is required to have a widget like reorderable Gridview. Just like how Google Keep Notes have a reorderable Gridview to reorder notes.

For this, I tried various packages on pub.dev/flutter and faced various issues in them:-
1. [Drag_and_drop_gridview](https://pub.dev/packages/drag_and_drop_gridview) - In this package, I was able to successfully reorder Gridview but this widget fails to scroll continuously by dragging a draggable at the ends of Gridview. 
The draggable widget becomes invisible when dropped outside of the Gridview. 
It also doesn't provide a way to stop multiple drags simultaneously. 
Also, It looks like the plugin is no longer maintained.

2. [Reorderable_grid_view](https://pub.dev/packages/reorderable_grid_view) -  This package is great but it doesn't support scrolling by dragging a draggable. I also made a feature request for it but the author didn't know how to do that.

3. [Reorderables](https://pub.dev/packages/reorderables) - This package doesn't support scroll by dragging a draggable.

So, all the packages failed to solve the above problems.

## Proposal

Now it would be great if flutter provides reorderable Gridview just like how it provided reorderable listview. The reorderable should work just like drag and drop Gridview works in Google Keep Notes app.

Thanks.

**Comment by TahaTesser** [comment] 2021-06-28 11:48
Hi @brightseagit 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/46430
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-28 11:48 UTC
Labels: in triage
