### ISSUE TITLE
[cross_file] Document all ignored parameters

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#87812] opened 2021-08-06 14:55 UTC
Following up from https://github.com/flutter/flutter/issues/87808#issuecomment-894291660

We ignore `name` for IO-backed files, so we should clearly document that.

We could even consider making a breaking change to the constructor APIs to group the the web-specific and io-specific arguments into parameter objects, then asserting that the parameter object that doesn't apply to the current implementation is null. /cc @ditman

**Comment by ditman** [comment] 2021-08-06 17:02
> We could even consider making a breaking change to the constructor APIs to group the the web-specific and io-specific arguments into parameter objects

I've been missing this lately. Ideally I think I'd like to make `XFile` abstract/interface for when a plugin user is using the file, but at the moment of creating that XFile being able to choose what underlying implementation I need. So the method_channel would do:

`XFileIO.fromFile(File file)`

and the web:

`XFileWeb.fromHtmlFile(HtmlFile file)`

or any other "specialty" constructors that make sense per platform. I haven't looked at the coding implications of my idea.

I haven't thought this through too much yet, but I found myself wanting to experiment with a "Blob" constructor this week, and ending up doing something else because of not wanting to bloat the constructor API any more.

**Comment by ditman** [comment] 2021-08-06 17:28
(Documenting the current behavior is the easy fix. If we decide to change the API, that's not so easy)

**Comment by stuartmorgan** [comment] 2021-08-06 18:33
I think we could make it relatively painless if we:
- Add new constructors with the APIs we want, and comment (but don't actively deprecate) the old APIs as being soft-deprecated
- Update all our plugins to use the new APIs
- Give the ecosystem a little while to catch up
- At some point deprecated the old constructors
- Eventually remove them in a breaking change

**Comment by stuartmorgan** [comment] 2022-03-02 15:24
@yashbujji If you are still learning Dart, this is probably not a good starting point; this issue requires having enough familiarity with Dart to read all of the code for `cross_file` to understand how it works sufficiently to document its actual behavior.

(In general, contributing to Flutter itself is likely not a good first step in learning Dart given that it's a very large and complex project.)

**Comment by maheshmnj** [comment] 2022-04-18 13:28
Minimal reproduction

```dart
import 'dart:typed_data';

import 'package:image_picker/image_picker.dart';

void main() {
  final bytes = Uint8List.fromList([0, 1, 2, 3, 4]);
  final file = XFile.fromData(
    bytes,
    length: bytes.length,
    name: 'Hello.png', // Name of the file
    lastModified: DateTime.now(),
  );

  print(file.name); /// this is empty
}
```
### output

<img width="755" alt="image" src="https://user-images.githubusercontent.com/31410839/163814907-9c844c15-406d-4514-a89f-00c724f0f175.png">

**Comment by andreacioni** [comment] 2023-06-24 14:25
Hello everyone, I was looking for a first issue to contribute to and I found this one stuck from quite a long time. Do you think it still relevant so I can start working on it?

**Comment by ueman** [comment] 2023-10-15 14:25
@stuartmorgan I guess this could be closed since https://github.com/flutter/packages/pull/4416 has been merged.

**Closed** 2023-10-15 14:56 UTC
Labels: d: api docs, package, good first issue, team-ecosystem, P2, p: cross_file, triaged-ecosystem

**Comment by ditman** [comment] 2023-10-19 05:33
Yay! Thanks for getting this done! 🙏
