### ISSUE TITLE
 I/flutter ( 9984): Failed to initialize videos: PlatformException(VideoError, Video player had error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1080, 1920, 30.000002, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES, null, null)  

### ISSUE THREAD

**Issue by YousefSalem01** [flutter/flutter#160852] opened 2024-12-25 23:21 UTC
### Steps to reproduce

this exception happen in redmi note 8 pro and most android 10 but if u test it on emulator or iPhone it works fine no exception can u please someone help me with that

### Expected results

no exception and package work on all Android types 

### Actual results

throwing exception 

### Code sample

Future initializeVideos() async {
  try {
    emit(OnboardingLoadingState());
    videoPlayers = AppAssets.onboardingVideosList
      .map((videoPath) => VideoPlayerController.asset(videoPath))
      .toList();
    for (var videoPlayer in videoPlayers) {
      await videoPlayer.initialize();
      initializeVideoListener(videoPlayer);
    }

    areVideosLoaded = true;
    emit(OnboardingLoadedState());
  } catch (e) {
    Utils.showToast('Failed to initialize videos: $e');
    emit(OnboardingErrorState());
  }
}

### Screenshots or Video

no need exception here  videoPlayer.initialize(); in that line I/flutter ( 9984): Failed to initialize videos: PlatformException(VideoError, Video player had error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1080, 1920, 30.000002, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES, null, null)  

### Logs

I/flutter ( 9984): Failed to initialize videos: PlatformException(VideoError, Video player had error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1080, 1920, 30.000002, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES, null, null)  

### Flutter Doctor output

[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version
    10.0.19045.5247], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.     
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of
      its default components
[!] Android Studio (not installed)
[√] VS Code (version 1.96.2)
[√] Connected device (5 available)
[√] Network resources

! Doctor found issues in 2 categories.

**Comment by Nuyoahhjh** [comment] 2024-12-26 09:49
I encountered the same error on the following devices: Huawei p20. Huawei HONOR Play5. Huawei mate40e

**Comment by Nuyoahhjh** [comment] 2024-12-26 09:49
PlatformException(VideoError,Video player had error w0.l:MediaCodecVideoRenderer error,
index=0, format=Format(0, null, null, vide0/avc, avc1.640028, -1, null, [1920, 1080,-1.0,
Colorlnfo(Unset color space, Unset color range, Unset color transfer, false,8bit Luma,8bit Chroma)],
[-1, -1]), format_supported=YES, null, null)

**Comment by khoadng** [comment] 2024-12-26 10:02
Some of my users who are using Android 10 reported this issue as well.

Their models:
Xiaomi Redmi 9, Android 10
Huawei P30 Pro, Android 10

**Comment by Nuyoahhjh** [comment] 2024-12-27 04:20
[@](https://github.com/flutter/flutter/issues/160861)

**Comment by Daphne-CoffeeIT** [comment] 2024-12-30 13:08
Same issue on Samsung S21 on Android 14

**Comment by danagbemava-nc** [comment] 2024-12-31 10:01
Closing this as a duplicate of https://github.com/flutter/flutter/issues/81804

**Closed by danagbemava-nc** 2024-12-31 10:01 UTC
Labels: in triage
