### ISSUE TITLE
Running used a lot of memory, the computer stuck(Used 20.56G)

### ISSUE THREAD

**Issue by Tecode** [flutter/flutter#57369] opened 2020-05-16 08:33 UTC
![Running used a lot of memory, the computer stuck(Used 20.56G)](https://github.com/Tecode/flutter_widget/blob/master/picture/tapd_59861796_base64_1589612431_37.png?raw=true)

## Flutter version
```bash
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (5 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```

## OS

```bash
Mac OS 10.14.6
```

**Comment by TahaTesser** [comment] 2020-05-18 11:20
Hi @Tecode 
can you please provide your complete `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem

Does this happen with a new project? 
Thank you

**Comment by Tecode** [comment] 2020-05-19 01:47
Hi @TahaTesser 
The new project will not have this problem,it's previously created using `flutter1.5.x` Version.
Now the upgraded version `1.17.x` sometimes has this problem.

**Comment by Tecode** [comment] 2020-05-19 01:56
Cannot reproduce now, reproduce my print log.

**Comment by TahaTesser** [comment] 2020-05-19 07:14
Hi @Tecode 
We need more details 
can you please provide your complete `flutter doctor -v` and `flutter run --verbose` from root of your project? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment] 2020-06-05 09:57
duplicate of https://github.com/flutter/flutter/issues/56569

**Closed by TahaTesser** 2020-06-05 09:57 UTC
Labels: in triage, waiting for customer response
