### ISSUE TITLE
Flutter Web : Error: XMLHttpRequest error.

### ISSUE THREAD

**Issue by luohaohaha** [flutter/flutter#63763] opened 2020-08-14 10:56 UTC
A simple http request, an error was reported on flutter web, it works very well on Android, is there any special configuration on flutter web?

```
void _requestMusicList() async{
    var url = 'http://...';
    var response = await http.post(url,headers: {'Content-Type':'application/json'});
    print('response is ${response.body}');
  }
```

error:
```
Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 264:20      get current
packages/http/src/browser_client.dart 84:22                                       <fn>
dart-sdk/lib/async/zone.dart 1450:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 143:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 696:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 725:32                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 519:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1300:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37287:58                              <fn>


    at Object.createErrorWithStack (http://localhost:60427/dart_sdk.js:4348:12)
    at Object._rethrow (http://localhost:60427/dart_sdk.js:37893:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60427/dart_sdk.js:37887:13)
    at Object._microtaskLoop (http://localhost:60427/dart_sdk.js:37719:13)
    at _startMicrotaskLoop (http://localhost:60427/dart_sdk.js:37725:13)
    at http://localhost:60427/dart_sdk.js:33244:9
```

doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-10.0.pre.95, on Mac OS X 10.14.6 18G103,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (3 available)
    ! Error: Could not locate device support files. This iPhone 6s is running
      iOS 13.5.1 (17F80), which may not be supported by this version of Xcode.
      An updated version of Xcode may be found on the App Store or at
      developer.apple.com. (code 601)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-08-14 13:21
Hi @luohaohaha 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-14 13:21 UTC

**Comment by geeraj** [comment] 2021-01-06 23:16
Hi Taha and luohaohaha, 

May I know the solution for the above issue as I also face the same issue and am struggling for last few days. 
Appreciate your help on this

**Comment by Yoda-Man** [comment] 2021-05-05 09:32
I am also getting this issue. What was the solution.

Error: XMLHttpRequest error.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 84:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58

**Comment by TahaTesser** [comment] 2021-05-06 10:57
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Yoda-Man** [comment] 2021-05-11 08:35
Looks like we have the exact same issue it must be a flaw in Flutter Web. If you come right please let me know.

**Comment by TahaTesser** [comment] 2021-05-11 12:16
https://github.com/flutter/flutter/issues/63763#issuecomment-833432312

**Comment by joseluisseg05** [comment] 2021-05-11 14:16
> Looks like we have the exact same issue it must be a flaw in Flutter Web. If you come right please let me know.

I think it's more of a backend in the  cors issue

**Comment by mycrosan** [comment] 2021-05-14 02:06
It seems to be a problem in the web flutter, if using the simulator it works normally.

**Comment by Yoda-Man** [comment] 2021-05-14 11:32
True I only get the problem on Flutter web for some projects and then it works fine one other flutter web projects. it could be making calls over the default https that's a problem. I hope they resolve it quick.
