### ISSUE TITLE
[engine] All Linux builds default to building GLFW (X11 dep)

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#98221] opened 2022-02-10 23:30 UTC
Building with Flutter SDK Tag 2.10.1 I get a repeat of https://github.com/flutter/flutter/issues/95711#issuecomment-1035169813

Is there a reason why the problematic commit wasn't just reverted?  It would resolve it everywhere...

**Comment by darshankawar** [comment] 2022-02-11 08:55
Labeling it for further investigation from the team.

**Comment by zanderso** [comment] 2022-02-14 19:50
@jwinarske Sorry for the trouble. My understanding from the resolution of https://github.com/flutter/flutter/issues/95711 was that the changes mentioned there landed on master and were cherry-picked to beta. Since that beta has now been promoted to stable, all of master, beta, and stable should be consistent w.r.t. the flag. Are you seeing something different?

**Comment by cmc5788** [comment] 2022-02-16 18:51
@zanderso -- I believe the changes mentioned to add the build examples flag got cherrypicked, but not the change to default the example build flag to false, so builds were still broken against the cherrypicked state as a result.

**Comment by zanderso** [comment] 2022-02-16 19:14
@godofredoc @devoncarew @itsjustkevin

https://github.com/flutter/flutter/issues/95711 needed to commits to be cherry-picked. The commits and the order that they needed to be applied in was in https://github.com/flutter/flutter/issues/95711#issuecomment-1018024673. Can you confirm whether this happenend?

**Comment by godofredoc** [comment] 2022-02-16 20:44
They haven't been landed yet. We were planning to do it during the hotfix window but the beta release got delayed a little bit and just landed today.

**Comment by cmc5788** [comment] 2022-02-16 21:01
I can confirm that the latest beta release has the examples flagged off. Once that's on stable we should be good.

**Comment by zanderso** [comment] 2022-02-17 16:12
@godofredoc @itsjustkevin I think there's a little confusion. https://github.com/flutter/flutter/issues/95711 was tagged `cp: 2.10 completed` on Jan 27, but it sounds like it actually hasn't been done, yet?

Looking over the commits on the branch https://github.com/flutter/engine/commits/flutter-2.8-candidate.16, it does seem that the `completed` tag was added to the issue prematurely, and then missed being included in an early hotfix release.

**Comment by itsjustkevin** [comment] 2022-02-25 19:10
@zanderso this was cherry-picked into the engine for the 2.10.2 release.

https://github.com/flutter/engine/pull/31525

Adding the completed label and closing this issue.

**Closed by itsjustkevin** 2022-02-25 19:10 UTC
Labels: engine, cp: 2.10
