### ISSUE TITLE
windows paths with flutter web cause issues when debugging in edge browser

### ISSUE THREAD

**Issue by Freundschaft** [flutter/flutter#60235] opened 2020-06-24 20:19 UTC
Using Edge Browser in Windows 10, the path to framework.dart is served incorrectly.
I receive the following error message:

```
Invalid argument (requestedUri): handlerPath "null" and url "null" must combine to equal requestedUri path "/D:/repos/flutter/packages/flutter/lib/src/widgets/framework.dart".: Instance of '_Uri'
dart:isolate  _RawReceivePortImpl._handleMessage
```

with chrome, and in production environment, everything works.

output of flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.19041.329], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (2 available)

• No issues found!
```

**Comment by jonahwilliams** [comment] 2020-06-24 20:24
@Freundschaft could you include the full stack trace (if available)?

**Comment by Freundschaft** [comment] 2020-06-24 21:56
@jonahwilliams unfourtunately that is the full stack trace.
the error occurs, because edge tries to request framework.dart from the server with this path.
I don't know why edge shows this kind of behavior and chrome doesnt.

![image](https://user-images.githubusercontent.com/5065616/85631725-59f75900-b676-11ea-9b44-2719500eef3c.png)

**Comment by jonahwilliams** [comment] 2020-09-25 18:55
Marking as a duplicate of https://github.com/flutter/flutter/issues/66376

**Closed by jonahwilliams** 2020-09-25 18:55 UTC
Labels: P4, platform-web, tool
