### ISSUE TITLE
Pixelated / very buggy looking font underneath gradient

### ISSUE THREAD

**Issue by nicklbaert** [flutter/flutter#133983] opened 2023-09-04 12:47 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use example widget
2. (possibly relevant: use font `Inter`)

Interestinly enough, the bug seems to disappear when removing either the `WidgetSpan` or one of the `TextSpans` from the `Text.rich` widget. 

### Expected results

Font looks normal, as in:
![IMG_2892](https://github.com/flutter/flutter/assets/33283708/d4ce8da5-ee52-4105-bdb4-f83c5b34e85c)

### Actual results

Font appears pixelated and buggy
![IMG_2891](https://github.com/flutter/flutter/assets/33283708/eb553779-553c-4999-9944-f50681fabcc8)

Also happening in the newest Flutter version! I'm using 3.10. due to https://github.com/flutter/flutter/issues/132735

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:ui';

import 'package:flutter/material.dart';

class DemoWidget extends StatefulWidget {
  const DemoWidget({super.key});

  @override
  State<DemoWidget> createState() => _DemoWidgetState();
}

class _DemoWidgetState extends State<DemoWidget> {
  final _flipDuration = const Duration(milliseconds: 400);
  final _period = const Duration(seconds: 5);

  late final Timer _pageFlipTimer;
  final pageController = PageController(
    viewportFraction: 0.8,
    initialPage: 0,
  );

  @override
  void initState() {
    super.initState();
    _pageFlipTimer = Timer.periodic(
      _period,
      (timer) {
        if (pageController.hasClients) {
          pageController.nextPage(
            duration: _flipDuration,
            curve: Curves.easeInOut,
          );
        }
      },
    );
  }

  @override
  void dispose() {
    _pageFlipTimer.cancel();
    pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 32,
      width: MediaQuery.of(context).size.width,
      child: ShaderMask(
        shaderCallback: (rect) {
          return LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
              Colors.transparent,
              Colors.black.withOpacity(0.8),
              Colors.black,
              Colors.black.withOpacity(0.8),
              Colors.transparent,
            ],
          ).createShader(
            Rect.fromLTRB(0, 0, rect.width, rect.height),
          );
        },
        blendMode: BlendMode.dstIn,
        child: SizedBox(
          height: 32,
          child: PageView.builder(
            controller: pageController,
            scrollDirection: Axis.vertical,
            physics: const NeverScrollableScrollPhysics(),
            itemBuilder: (context, index) {
              return Center(
                child: Text.rich(
                  TextSpan(
                    text: '',
                    children: [
                      WidgetSpan(
                        alignment: PlaceholderAlignment.middle,
                        child: ClipOval(
                          child: SizedBox.square(
                            dimension: 16,
                            child: ColoredBox(
                              color: Colors.transparent,
                              child: ImageFiltered(
                                imageFilter:
                                    ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
                                child: const Stack(
                                  alignment: Alignment.center,
                                  children: [
                                    SizedBox.expand(
                                      child: Image(
                                        image: NetworkImage(
                                          'https://flxt.tmsimg.com/assets/235135_v9_bc.jpg',
                                        ),
                                      ),
                                    )
                                  ],
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      const TextSpan(text: ' some middle text '),
                      const TextSpan(text: 'some text here'),
                    ],
                  ),
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w500,
                    color: const Color(0xFF141414).withOpacity(0.5),
                  ),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
![IMG_2891](https://github.com/flutter/flutter/assets/33283708/934c9d8b-64a6-4b1e-af88-74df771cd858)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.10.6 on channel stable at /Users/nicklbaert/Documents/Apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (8 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nicklbaert/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-16.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 16+36-2231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • ...

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment] 2023-09-05 05:57
Hi @nicklbaert 
I checked this issue on the latest master channel and 3.10.6 too, but can't see the pixelated texts as yours. Also, the text is the same even when removing `WidgetSpan` which displays the image widget. 

| with Image | without Image |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/6961c752-817d-477e-bade-6e38901f2863"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/4d71e9ab-0ef6-498d-b3d8-9ae49c51fe98">

I'm checking this on iPhone 14 Pro, iOS 16.4. Which device are you seeing this issue on?

**Comment by nicklbaert** [comment] 2023-09-05 07:59
> Hi @nicklbaert I checked this issue on the latest master channel and 3.10.6 too, but can't see the pixelated texts as yours. Also, the text is the same even when removing `WidgetSpan` which displays the image widget.
> 
> with Image	without Image
> <img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/265597041-6961c752-817d-477e-bade-6e38901f2863.png">	<img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/265597687-4d71e9ab-0ef6-498d-b3d8-9ae49c51fe98.png">
> I'm checking this on iPhone 14 Pro, iOS 16.4. Which device are you seeing this issue on?

Hi @huycozy , thanks for the quick reply. I am using an iPhone 12 with iOS 16.0.2.

**Comment by jonahwilliams** [comment] 2023-09-05 17:09
This is a duplicate of https://github.com/flutter/flutter/issues/132928

**Closed by jonahwilliams** 2023-09-05 17:09 UTC
Labels: in triage
