### ISSUE TITLE
Package Integration_test : update archive dependence 

### ISSUE THREAD

**Issue by redDwarf03** [flutter/flutter#100383] opened 2022-03-18 18:16 UTC
Hello
could you update the archive dependency please in integration_test package
cf https://pub.dev/packages/archive

**Comment by christopherfujino** [comment] 2022-03-18 18:34
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/98536. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-03-18 18:34 UTC
