### ISSUE TITLE
[BUG] Hovering ListTile or TextField triggers unnecessary rebuild of CustomPaint

### ISSUE THREAD

**Issue by asmith20002** [flutter/flutter#120521] opened 2023-02-11 11:56 UTC
Looks similar to #117627.

## Bug Summary
Hovering a `ListTile` with `onTap` enabled or Hovering a `TextField` triggers `CustomPaint` paint function. Even with `shouldRepaint` set to false.

## Demonstration

https://user-images.githubusercontent.com/17809451/218256520-9283782f-39f2-48fb-a154-1b8cbc4f8b51.mp4

## Sample code
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Column(
        children: [
          CustomPaint(
            painter: PaintBlue(),
            child: const SizedBox(
              width: 500,
              height: 200,
              child: Center(
                child: Icon(
                  Icons.format_paint_rounded,
                  color: Colors.white,
                  size: 40,
                ),
              ),
            ),
          ),
          const SizedBox(
            height: 100,
          ),
          const TextField(
            decoration: InputDecoration(
                hintText: 'Hovering me will cause rebuild of custompaint.'),
          ),
          const SizedBox(
            height: 100,
          ),
          ListTile(
            title: const Text('ListTile'),
            subtitle: const Text(
                'Hovering a ListTile with onTap enabled will also rebuild customPaint.'),
            onTap: () {
              // Do nothing.
            },
          )
        ],
      ),
    );
  }
}

class PaintBlue extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    // ignore: avoid_print
    print('Rebuilding!');

    canvas.drawRect(Rect.fromLTWH(0, 0, size.width, size.height),
        Paint()..color = Colors.blue);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return false;
  }
}

```

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1194], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.75.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by huycozy** [comment] 2023-02-13 08:31
@asmith20002 Thanks for your report. But it doesn't seem to be related to #117627. 

Instead, wrapping the `CustomPaint` by `RepaintBoundary` will prevent this side effect. You can try it and confirm if it works.

**Comment by asmith20002** [comment] 2023-02-13 15:16
Yes I tried it and it solves the problem. However if this is the intended way and what I described is not a bug, feel free to close this. I'll investigate on `RepaintBoundary`.

**Comment by huycozy** [comment] 2023-02-14 05:46
I also see there is an open issue https://github.com/flutter/flutter/issues/28814 which has a little bit of similarity. But it's not really the same. That issue is about `shouldRepaint` issue. 

When taking a look at https://github.com/flutter/flutter/issues/28814#issuecomment-665615116 with sample code, `CustomPainter`'s paint is also called when invoking `setState(() {})`, but this issue is about hovering on `ListTile` and TextField`. 

It may be `ListTile`/`TextField` issue when using with `CustomPainter`. So I will label this issue for further investigation. 
This issue is reproducible on the latest `stable` and `master` channels with provided sample code from OP.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (17 hours ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Users/huynq/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

```bash
[!] Flutter (Channel master, 3.8.0-12.0.pre.49, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.8.0-12.0.pre.49 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b08cc8be79 (45 minutes ago), 2023-02-13 22:36:26 -0500
    • Engine revision c4f51bc786
    • Dart version 3.0.0 (build 3.0.0-233.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.96

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by dkwingsmt** [comment] 2023-02-17 01:35
Yes, I think it's working as intended and you should wrap the `CustomPaint` in a `RepaintBoundary`. Because without it, the three widgets are painting on the same layer, and any change to any of the widgets require painting the entire layer from scratch. With the `RepaintBoundary`, the result of the custom painter is cached onto a separate layer, and changes to its siblings only need to use this cached result instead.

Why doesn't `shouldRepaint` work? Because `shouldRepaint`, as its document says, is only used when a different `CustomPainter` is provided in order to determine if it's the same painter. It is not used to determine whether the paint animates, which is actually the job of the `painter` parameter.

I'm closing this issue. But feel free to comment if you have more questions, especially if you think the documentation can be improved! :)

**Closed by dkwingsmt** 2023-02-17 01:35 UTC
Labels: framework, f: material design, a: mouse, has reproducible steps, P4, workaround available, found in release: 3.7, found in release: 3.8
