### ISSUE TITLE
compile using proguard then auto rename MethodChannel call.method string

### ISSUE THREAD

**Issue by erlangp** [flutter/flutter#45036] opened 2019-11-16 10:53 UTC

**Comment by janmoppel** [comment] 2019-11-18 10:30
Hello @erlangp !

Thank you for posting.
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-11-18 10:30 UTC
