### ISSUE TITLE
[image_picker] PlatformException(multiple_request, Cancelled by a second request, null, null) when picking the first default image from the ios simulator

### ISSUE THREAD

**Issue by ShunyaWatanabe** [flutter/flutter#82602] opened 2021-05-15 02:55 UTC
## Steps to Reproduce

1. Run `flutter create temp`.
2. Update the files as follows: https://github.com/ShunyaWatanabe/flutter-picker-image-test/commit/3e4feeb15a182396765af4d6868b0f086339597a 
3. Run `flutter run --verbose` 
4. Click the button on the bottom right, which is the increment counter
5. Approve permission
6. Load different default pictures

**Expected results:** 
Image picker should work on all of the default pictures.

**Actual results:** 
One of them doesn't work, with the error that says `PlatformException(multiple_request, Cancelled
by a second request, null, null)`

If this is the expected result, I'd like to know what the cause is and request better logs for better understanding.

https://user-images.githubusercontent.com/25846438/118346219-cb811400-b574-11eb-8e06-f7453f3d1d2a.mov

<details>
  <summary>Logs</summary>

```
[+4665 ms] flutter: error: PlatformException(multiple_request, Cancelled
by a second request, null, null)
```

```
Analyzing temp...
No issues found! (ran in 2.5s)
```

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H114 darwin-x64,
    locale en-JP)
    • Flutter version 2.0.4 at /Users/shunya_watanabe/development/flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01
      -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/shunya_watanabe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/shunya_watanabe/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 14C87317-9478-42BE-AEE5-9CC4FF5590BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)      • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2021-05-17 10:11
@ShunyaWatanabe 
It'd be great if you could provide a code sample in a single file that we can directly copy paste and run to verify the issue.

Also, take a look at this open similar issue which talks about same exception you are getting, https://github.com/flutter/flutter/issues/49780 and see if it resemble your issue.

**Comment by ShunyaWatanabe** [comment] 2021-05-17 13:17
@darshankawar 
I wish I could do that but in order to use image_picker I need to at least modify 3 files (pubspec.yml, main.dart, and pubspec.lock which is automatically modified) and then a few more files to configure permission for access to the photos.
Please understand that this is the minimum I extracted to reproduce the issue.

Also, thanks for the suggestion. I took a look at #49780, but I'm not sure if they are the same issue.

**Comment by darshankawar** [comment] 2021-05-18 06:32
@ShunyaWatanabe 
Manually picking up changes from the file you shared is time consuming. It'd be great if you could put that file in a github repo and share the link that we can clone and directly run to verify this issue.

Thanks.

**Comment by ShunyaWatanabe** [comment] 2021-05-18 06:52
You can clone this repo: https://github.com/ShunyaWatanabe/flutter-picker-image-test

**Comment by darshankawar** [comment] 2021-05-18 12:12
@ShunyaWatanabe 
In your code, I see that you've explicitly added to handle permissions using `permission_handler` plugin, which is not required. On iOS, app now by default asks for permissions, as shown below:

<img width="374" alt="Screenshot 2021-05-18 at 5 32 56 PM" src="https://user-images.githubusercontent.com/67046386/118648076-aa802380-b7ff-11eb-8214-f5c09357459a.png">

Above screenshot is from plugin's official repo https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker/example, wherein, you'll see, no explicit permission is used / handled.

Can you try the same without permission_handler issue and see if you still get same issue ?

**Comment by ShunyaWatanabe** [comment] 2021-05-23 06:49
I removed permission_handler and tried it again, and the error still occurs.

**Comment by intoxicated** [comment] 2021-05-24 00:41
I'm experiencing this as well, when user clicks cancel button `getImage` does not return anything (expect null here), and when `getImage` is get called again, it throws this error

**Comment by darshankawar** [comment] 2021-05-24 07:12
Thanks for the updated code sample. Using it and with latest plugin version, I was able to replicate the issue, irrespective of any kind of permission we select and seems to be happening only after selecting particular image, ie, top left image:

<img width="338" alt="Screenshot 2021-05-24 at 12 37 23 PM" src="https://user-images.githubusercontent.com/67046386/119310364-42ad5b00-bc8d-11eb-9351-a743e9a8ca55.png">

```
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: error: PlatformException(multiple_request, Cancelled by a second request, null, null)
flutter: error: PlatformException(multiple_request, Cancelled by a second request, null, null)
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'


Syncing files to device iPhone 12 Pro Max...
flutter: error: PlatformException(multiple_request, Cancelled by a second request, null, null)
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: pickedFile: Instance of 'PickedFile'
flutter: error: PlatformException(multiple_request, Cancelled by a second request, null, null)
```

<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ncflutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!



```

</details>

**Comment by mostafaAbdelazim** [comment] 2021-05-26 09:18
is there a stable version we can use for now?

**Comment by mono0926** [comment] 2021-06-01 06:37
This bug seems to be added at `0.7.5`( #3835 ).

> ## 0.7.5
> 
> * Fixes an issue where image rotation is wrong when Select Photos chose and image is scaled.
> * Migrate to PHPicker for iOS 14 and higher versions to pick image from the photo library.
> * Implement the limited permission to pick photo from the photo library when Select Photo is chosen.
> https://pub.dev/packages/image_picker/changelog#075

This bug can be avoided by downgrading to ` image_picker: 0.7.4` at `pubspec.yaml`.

```yaml
  image_picker: 0.7.4
```

**Comment by a7medpa** [comment] 2021-06-07 20:00
I have the same issue on v0.8.0+1. Oddly, if I pick any other default image other than the first one (with the bunch of flowers) it doesn't give me the error.

**Comment by ydag** [comment] 2021-06-10 07:27
> I have the same issue on v0.8.0+1. Oddly, if I pick any other default image other than the first one (with the bunch of flowers) it doesn't give me the error.



> This bug seems to be added at `0.7.5`( #3835 ).
> 
> > ## 0.7.5
> > 
> > * Fixes an issue where image rotation is wrong when Select Photos chose and image is scaled.
> > * Migrate to PHPicker for iOS 14 and higher versions to pick image from the photo library.
> > * Implement the limited permission to pick photo from the photo library when Select Photo is chosen.
> >   https://pub.dev/packages/image_picker/changelog#075
> 
> This bug can be avoided by downgrading to ` image_picker: 0.7.4` at `pubspec.yaml`.
> 
> ```yaml
>   image_picker: 0.7.4
> ```

Hello @mono0926 and @a7medpa,

This is because there is a  [known issue](https://www.google.com/search?q=63426347+apple&ei=XdSLYJqTIP-O9u8P54eH8AU&oq=63426347+apple&gs_lcp=Cgdnd3Mtd2l6EAxQAFgAYIc0aABwAngAgAE5iAE5kgEBMZgBAKoBB2d3cy13aXrAAQE&sclient=gws-wiz&ved=0ahUKEwjatcCJ2qXwAhV_h_0HHefDAV4Q4dUDCA0) to pick HEIC images (the first one is HEIC format) with PHPicker implementation. But it should only affect transcoding on simulators. So we have two options here. Either test with a real device or test with non-HEIC images until Apple solves the issue.

**Comment by y-alkhateeb** [comment] 2021-06-16 12:26
The same issue with the last version of image_picker: ^0.8.0+3

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en)
    • Flutter version 2.2.2 at /Users/y.alkhateeb/Documents/dev/sdk/flutter
    • Framework revision d79295af24 (5 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/y.alkhateeb/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 00B2C40E-A430-47D8-8D77-4E556C5A9294 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.101

• No issues found!

**Comment by KuoyHuot** [comment] 2021-06-17 02:57
I also get this exception on physical ios device (not sure on Android), when I close the image picker sheet or tap the cancel button on the sheet, then call `ImagePicker().getImage(source: ImageSource.gallery)` again.

**Comment by ydag** [comment] 2021-06-17 14:06
Hello @KuoyHuot and @y-alkhateeb,

I think your issue is a bit different than this issue. This issue is about HEIC format and you can find the details in my comment above. I guess the reason you have the `PlatformException (PlatformException(multiple_request, Cancelled by a second request, null, null))` error is explained in [this comment](https://github.com/flutter/flutter/issues/82519#issuecomment-861519841). So the PR that is mentioned in the comment will fix the problem.

If you think otherwise please let me know.

**Comment by SebghatYusuf** [comment] 2021-08-20 19:01
Any updates?? 
It seems to be a long time since the issue is reported, is there any fix available??

**Comment by dkarakay** [comment] 2021-09-07 17:52
I got the same error using ^0.8.4
Only the top left one causes the error
![Simulator Screen Shot - iPhone 11 - 2021-09-07 at 20 51 06](https://user-images.githubusercontent.com/20050426/132389023-4f0fa097-ca9b-4147-b7d4-e8fc32751452.png)

**Comment by Tommy-Elliott** [comment] 2021-09-14 18:44
For those who don't want to read the entire comment thread, the reason for this issue as reported is explained fully in an above comment:
https://github.com/flutter/flutter/issues/82602#issuecomment-858383514

The flowers image is the only one in the iOS simulator sample images that is HEIC format, and iOS simulators currently fail to transcode HEIC images.  Real iOS devices don't have that issue.  Apple is expected to eventually resolve the iOS simulator HEIC format transcoding open issue, and the workaround for now is to test an HEIC image on a real iOS device or to test only using the other (non-HEIC) images on the simulator.

**Comment by mostafaAbdelazim** [comment] 2021-09-15 02:11
Hey guys it seems like I'm getting this error with every image on the simulator it self, not just the flowers image. 

I'm using M1 machine for flutter development

**Comment by lucaphen** [comment] 2021-09-15 09:12
> Hey guys it seems like I'm getting this error with every image on the simulator it self, not just the flowers image.
> 
> I'm using M1 machine for flutter development

Same for me, not just HEIC images. Also using M1 for development and used a flutter template to replicate issue. Link to Github repo: [here](https://github.com/lucaphen/camera_test)

**Comment by domtom1126** [comment] 2021-09-16 17:50
> Hey guys it seems like I'm getting this error with every image on the simulator it self, not just the flowers image.
> 
> I'm using M1 machine for flutter development

I am still getting this error as well. I had tried the above recommendation of downgrading to `image_picker: 0.7.4` and I am getting another error for using XFile. Switching back to `0.8.4`

**Comment by domtom1126** [comment] 2021-09-16 17:58
UPDATE: I again downgraded to image_picker: ^0.7.4+1 and changed `final XFile? image = await picker.getImage(source: ImageSource.gallery);` to `final image = await picker.getImage(source: ImageSource.gallery);`. If anyone needs help be sure to reply.

**Comment by cormalenv** [comment] 2021-11-26 05:19
> UPDATE: I again downgraded to image_picker: ^0.7.4+1 and changed `final XFile? image = await picker.getImage(source: ImageSource.gallery);` to `final image = await picker.getImage(source: ImageSource.gallery);`. If anyone needs help be sure to reply.

Concur. This is not an image selection related issue. Seems to have been introduced from 0.8.0 onwards and remains until current. ^0.7.5 runs fine.

**Comment by khalilkm01** [comment] 2021-12-12 02:33
Is this fixed yet?

**Comment by BenjaminFarquhar** [comment] 2021-12-23 01:58
> ers image is the only one in the iOS simulator sample images that is HEIC format, and iOS simulators

For me even jpg images cause the same error

**Comment by FantaZZ** [comment] 2021-12-24 17:02
Is this fixed yet?

**Comment by tmkook** [comment] 2021-12-27 04:49
Same for me

**Comment by devbrandonlong** [comment] 2022-01-07 13:00
still happening in 2022. Unable to select any images on m1, even when I drag in my own jpgs into the simulator 😔

**Comment by holisticapps** [comment] 2022-01-07 21:22
Same for me

**Comment by nicop2000** [comment] 2022-01-11 16:18
same here

**Comment by kauzige** [comment] 2022-01-13 14:19
saaaaaaaaame here

**Comment by qdmitry** [comment] 2022-01-19 07:55
M1 Pro, issue PlatformException(multiple_request, Cancelled by a second request, null, null)
First request not complete. And second error. Image not selected. iOS Sim.

**Comment by lukeirvin** [comment] 2022-01-21 20:35
Currently using an M1 Mac Mini, running the latest version of image_picker & seeing this error.

**Comment by Andrewngabriel** [comment] 2022-02-03 03:48
I'm using version `^0.8.4+5` of the package and running on iOS Simulator iPhone 11 Pro (iOS 14.5). Still getting the error.

**Comment by CoderJava** [comment] 2022-02-12 09:07
I'm using version `^0.8.4+8` of the package and still getting the error. 😢

**Comment by qdmitry** [comment] 2022-02-22 10:17
@CoderJava @cardzap-ewan I'm using M1 Pro and iOS Simulator 12. all works.

**Comment by orourkedd** [comment] 2022-02-23 18:48
Same for me

**Comment by zaferguler0** [comment] 2022-02-28 20:50
Hi everyone ı found the solution. Install İOS 13.7 from Xcode. Go to Xcode > Preferences, Select the "Components" tab, Mark the İOS 13.7, press "Check and Install Now".

**Comment by XinleZhou2018** [comment] 2022-03-04 01:30
image_picker: ^0.8.4+10 still has some error

**Comment by zaferguler0** [comment] 2022-03-04 15:08
@XinleZhou2018 try this version 0.8.4

**Comment by cardzap-ewan** [comment] 2022-03-04 18:41
Tried version 0.8.4 and got the same error.  I haven't tried downgrading to 13.7.  Seems like this must be a recent change to the image_picker code since the exact same code worked on the simulator a couple of weeks ago.

**Comment by cardzap-ewan** [comment] 2022-03-04 18:51
I tried with the 13.7 iOS and it works with that.  That being said, it's a bit worrying having to develop with an older version of the OS.

**Comment by hoonblizz** [comment] 2022-03-18 20:57
Having the same issue here.

**Comment by ritenv** [comment] 2022-03-19 09:48
Facing this issue even when using my own JPG or PNG images.
image_picker: ^0.8.4+10

**Comment by cardzap-ewan** [comment] 2022-03-20 15:01
I "fixed" this by creating a special IOS simulator with iOS 13.7 installed which I use when I'm testing image picking on the simulator.  It all seems to work fine on the physical device with iOS 15.3.  This isn't ideal but it kind of solves the problem.

**Comment by a7medpa** [comment] 2022-03-20 15:20
I don't know who's sleeping but this should be fixed by now

**Comment by maxwell882000** [comment] 2022-03-21 16:36
I hope the problem will be fixed soon

**Comment by sangh518** [comment] 2022-03-24 01:00
same problem

**Comment by domtom1126** [comment] 2022-03-24 02:32
I have had this problem for a couple of months on the simulator but now its on TestFlight and it works fine on all devices the app has been used on. However, when I was using the simulator today on `image_picker: ^0.8.4+10` it gave me an error after closing the gallery. I have never gotten an error before, usually it would just close out without error so thats why I'm posting here:
`StateError (Bad state: File: '/Users/dominic./Library/Developer/CoreSimulator/Devices/92751D63-6DF4-4C4B-9C42-57F7AFBBA607/data/Containers/Data/Application/C69BCFA0-CD9E-4083-99A2-A28F9C6C440F/tmp/image_picker_D9856652-1D5B-44FD-86A7-C09D1E75656C-35296-0000123DB274F5AE.jpg' is empty and cannot be loaded as an image.)` 

No reason it should say empty it works just fine on physical devices. But hey, I finally got an error!

**Comment by mailliwi** [comment] 2022-04-04 15:41
Same here as of April 2022.
**Error message:** `Failed to pick image. See error: PlatformException(multiple_request, Cancelled by a second request, null, null)` when trying to use the first default picture of the simulator. It works fine for the other pictures.

**Computer:** Mac M1 Mini.
**Version of image_picker:** 0.8.4+11.

**Comment by maheshmnj** [comment] 2022-04-08 06:10
Reproducible as of `image_picker: ^0.8.5` on Flutter `stable 2.10.4`

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by lexycole** [comment] 2022-04-15 07:58
Mine show the error message, then few minute later pop up alert "to select photo"
WORKED iOS14.2, image_picker^0.8.5

**Comment by haroonkhan335** [comment] 2022-04-21 01:12
A year has passed and the dude is snoring.

**Comment by LuAnmin-Github** [comment] 2022-04-21 10:09
same here , 0.8.5

**Comment by stuartmorgan** [comment] 2022-04-29 16:08
Does this reproduce with the latest dependencies (image_picker_ios 0.8.5+)? The last update to the iOS implementation packages fixed some situations where we would incorrectly think that a previous request was still in progress.

**Comment by nomoreboredom** [comment] 2022-04-30 10:14
@stuartmorgan it does for me

**Comment by cardzap-ewan** [comment] 2022-05-01 16:44
And reproduces for me with the latest 0.8.5 version and latest Xcode. 

Fwiw, the first call silently fails (I breakpointed every line of code) and somehow you just end up in the main thread. The second call gives the “cancelled by second request” error. 

Will post a minimal app which exhibits this behaviour soon(ish).

**Comment by azazadev** [comment] 2022-05-01 17:20
same issue with the latest 0.8.5 version

**Comment by jmagman** [comment] 2022-05-02 17:39
Please do not reply "same here" or "me too" to any GitHub issues.  It adds noise and makes it harder for maintainers to see actually important information.  Just give the original description of the issue a 👍  or subscribe to the issue for updates.

**Comment by stuartmorgan** [comment] 2022-05-02 17:56
> Fwiw, the first call silently fails (I breakpointed every line of code) and somehow you just end up in the main thread. The second call gives the “cancelled by second request” error.

It sounds like we're never running the callback at all for the first call then, so it makes sense that the change in 0.8.5 wouldn't have fixed it. The changes there that I thought might be relevant were for cases where we *did* run the callback, but failed to clean up state (and would then incorrectly call the in-progress error later).

Thanks for verifying!

**Comment by maheshmnj** [comment] 2022-05-03 12:51
Updated triage report for this issue can be found here https://github.com/flutter/flutter/issues/82602#issuecomment-1092475129

**Comment by FakharAlyas119** [comment] 2022-05-11 06:39
> Does this reproduce with the latest dependencies (image_picker_ios 0.8.5+)? The last update to the iOS implementation packages fixed some situations where we would incorrectly think that a previous request was still in progress.

yes i am still facing this issue even i update the plugin to latest package

**Comment by CAJazzer** [comment] 2022-06-01 20:24
I can consistently reproduce the problem as follows on my M1 Macbook Pro:

1. Create a new Flutter (3.01) application and add latest image_picker (0.8.5+3) and other packages required for the demo app -  Run the app on ios Simulator and everything works fine (non heic images load correctly)
2. For me, I need the [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) package so I add it and configure it for ios.  -  Now image_picker no longer works and fails with the PlatformException
3. Removing the google_maps_flutter and its settings allows the image_picker to work

**Comment by jmagman** [comment] 2022-06-01 20:31
If you are on a M1 Mac you are likely hitting an iOS simulator Rosetta issue.  google_maps does not yet support arm64 simulators, which is why adding it drops you back to Rosetta, exposing iOS simulator bugs.  You're hitting https://github.com/flutter/flutter/issues/82602#issuecomment-1144099379 and https://github.com/flutter/flutter/issues/74970#issuecomment-858170914.  We have an open issue to update google_maps at https://github.com/flutter/flutter/issues/94491 but essentially Apple needs to fix that bug.

However, if you are running on an x64 intel machine, as the originator is, you are not hitting a Rosetta issue.  This open GitHub issue is tracking that.

**Comment by idkq** [comment] 2022-06-10 14:25
I was able to get a different error by picking a different image from the default ones and updating my Xcode.

```
File: '/Users/xxxxxxxxxx/Library/Developer/CoreSimulator/Devices/1D3E25DA-803E-447F-A42D-
6BC794318FE9/data/Containers/Data/Application/056DDD20-F362-49F0-B36D-
EE6CF862A38A/tmp/image_picker_37D3019E-1DCC-4366-9098-1DF67424373A-71238-0000B04C05F8D3ED.jpg'
 is empty and cannot be loaded as an image.
```

I'm using the VERY latest version of Xcode 13.4.1 (therefore latest simulator). 

Repro:

1 - Download the example app image_picker
2 - Add `google_maps_flutter: ^2.1.5` and `google_maps_flutter_web: ^0.3.3` to `pubspec.yaml`
3 - Using simulator browser, go to google, search for a panda, download the image to the gallery. Very important, it has to be a panda ;-)
4 - Run example app. Pick the panda.


Another thing. This is weird - not sure if is related:

Photos app crash when you get Information about picture.

1 - Go to Photos
2 - Click on any photo
3 - Click on Information
4 - Photos App will crash with error `MobileSlideShow quit unexpectedly` 

`terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'coordinate spaces don't have a common ancestor'`

**Comment by maheshmnj** [comment] 2022-07-06 10:26
Updating the issue since this is reproducible on intel machine too.

**Comment by thphuc** [comment] 2022-07-07 02:12
I still can see this exception on `^0.8.5+3`, iOS simulator

**Comment by yareyaredesuyo** [comment] 2022-08-23 02:40
In iOS simulator, you should avoid using top-left sample photo image, because this image type is heif.

Another photo type is all jpeg, so you should use these photo images.

<img src="https://user-images.githubusercontent.com/31843888/186056357-520edcf1-36bc-40c9-9796-345314011cdc.png" width=250 />

And you can check photo image type using photo app.

<img src="https://user-images.githubusercontent.com/31843888/186057080-653cc033-c439-44b8-823a-98f6e4d44b0e.png" width=250 />

<img src="https://user-images.githubusercontent.com/31843888/186057220-5b804306-468e-4c33-b34a-edef4ace1b00.png" width=250 />

**Comment by Matias-Raverta** [comment] 2022-11-29 12:57
Still happening in version **image_picker: ^0.8.6.** in IOS simulator.
I was able to see the image info in my first try. After a second try I was never able to get the same behavior again. Uninstalled the app from simulator, cleaned the project, run it and gave permissions again for picker to work.

**Closed** 2022-12-19 22:58 UTC
Labels: platform-ios, plugin, p: first party, customer: crowd, p: image_picker, has reproducible steps, P3, found in release: 2.2, found in release: 2.10
