### ISSUE TITLE
[WEB] Special characters not rendered correctly with canvaskit renderer

### ISSUE THREAD

**Issue by woprandi** [flutter/flutter#76003] opened 2021-02-14 13:29 UTC
## Steps to Reproduce
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  Widget build(BuildContext context) {
    return Scaffold(
        body: Text("Special char : ← ↑ → ↓ \u2190 \u2191 \u2192 \u2193"));
  }
}
```

`$ flutter run -d chrome --web-renderer canvaskit`

**Expected results:** 

Special characters rendered correctly (html renderer here)
![html](https://user-images.githubusercontent.com/1449422/107878001-10db6a00-6ed0-11eb-8010-778d0a35f2a4.png)

**Actual results:** 

![canvaskit](https://user-images.githubusercontent.com/1449422/107878012-2355a380-6ed0-11eb-8891-77e65c7f5ee9.png)

Reproductible with current master/dev/beta channels

<details>
  <summary>Logs</summary>

```
 ~/Documents/repos/flutter_playground  flutter run --verbose -d chrome --web-renderer canvaskit
[  +74 ms] executing: uname -m
[  +37 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +16 ms] executing: [/home/william/Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 696e4f70d1a7a9b9b793aa3fc4ad2d8d3d8eac17
[        ] executing: [/home/william/Documents/flutter/] git tag --points-at 696e4f70d1a7a9b9b793aa3fc4ad2d8d3d8eac17
[  +15 ms] Exit code 0 from: git tag --points-at 696e4f70d1a7a9b9b793aa3fc4ad2d8d3d8eac17
[   +1 ms] executing: [/home/william/Documents/flutter/] git describe --match *.*.* --long --tags 696e4f70d1a7a9b9b793aa3fc4ad2d8d3d8eac17
[  +35 ms] Exit code 0 from: git describe --match *.*.* --long --tags 696e4f70d1a7a9b9b793aa3fc4ad2d8d3d8eac17
[        ] 1.27.0-1.0.pre-98-g696e4f70d1
[  +45 ms] executing: [/home/william/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/william/Documents/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +46 ms] executing: [/home/william/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +74 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] executing: /home/william/Android/Sdk/platform-tools/adb devices -l
[  +21 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +75 ms] executing: /home/william/Android/Sdk/platform-tools/adb devices -l
[  +15 ms] Skipping pub get: version match.
[  +19 ms] Found plugin barcode_scanner at /home/william/.pub-cache/git/barcode-scanner-750bd8ac35fdbff88eaff07a4488acea6b50a514/
[  +59 ms] Found plugin url_launcher at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/
[   +3 ms] Found plugin url_launcher_linux at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+4/
[   +3 ms] Found plugin url_launcher_macos at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/
[   +5 ms] Found plugin url_launcher_web at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5+3/
[   +2 ms] Found plugin url_launcher_windows at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+3/
[  +25 ms] Found plugin integration_test at /home/william/Documents/flutter/packages/integration_test/
[  +85 ms] Found plugin barcode_scanner at /home/william/.pub-cache/git/barcode-scanner-750bd8ac35fdbff88eaff07a4488acea6b50a514/
[  +31 ms] Found plugin url_launcher at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/
[   +1 ms] Found plugin url_launcher_linux at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+4/
[   +1 ms] Found plugin url_launcher_macos at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/
[   +3 ms] Found plugin url_launcher_web at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5+3/
[   +1 ms] Found plugin url_launcher_windows at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+3/
[  +22 ms] Found plugin integration_test at /home/william/Documents/flutter/packages/integration_test/
[  +16 ms] Generating /home/william/Documents/repos/flutter_playground/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +164 ms] List of devices attached
[   +5 ms] List of devices attached
[ +104 ms] Launching lib/main.dart on Chrome in debug mode...
[ +132 ms] Updating assets
[ +104 ms] Waiting for connection from debug service on Chrome...
[   +5 ms] Found plugin barcode_scanner at /home/william/.pub-cache/git/barcode-scanner-750bd8ac35fdbff88eaff07a4488acea6b50a514/
[  +23 ms] Found plugin url_launcher at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/
[   +2 ms] Found plugin url_launcher_linux at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+4/
[   +1 ms] Found plugin url_launcher_macos at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/
[   +2 ms] Found plugin url_launcher_web at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5+3/
[   +1 ms] Found plugin url_launcher_windows at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+3/
[   +9 ms] Found plugin integration_test at /home/william/Documents/flutter/packages/integration_test/
[   +5 ms] Found plugin barcode_scanner at /home/william/.pub-cache/git/barcode-scanner-750bd8ac35fdbff88eaff07a4488acea6b50a514/
[  +17 ms] Found plugin url_launcher at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/
[   +1 ms] Found plugin url_launcher_linux at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+4/
[   +1 ms] Found plugin url_launcher_macos at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/
[   +2 ms] Found plugin url_launcher_web at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5+3/
[        ] Found plugin url_launcher_windows at /home/william/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+3/
[  +11 ms] Found plugin integration_test at /home/william/Documents/flutter/packages/integration_test/
[ +102 ms] <- reset
[   +5 ms] /home/william/Documents/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/william/Documents/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/william/Documents/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true --output-dill
/tmp/flutter_tools.OWJPPB/flutter_tool.FXIFSJ/app.dill --libraries-spec file:///home/william/Documents/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/william/Documents/repos/flutter_playground/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.OWJPPB/flutter_tools.DTBFAO
--filesystem-scheme org-dartlang-app --initialize-from-dill build/5ce7c659493310451672e1cde9a7cc60.cache.dill.track.dill --platform file:///home/william/Documents/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[  +13 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+23358 ms] Waiting for connection from debug service on Chrome... (completed in 23,6s)
[        ] Synced 29.3MB.
[        ] <- accept
[        ] Caching compiled dill
[  +98 ms] Using Google Chrome 88.0.4324.150 

[ +686 ms] [CHROME]:
[  +10 ms] [CHROME]:DevTools listening on ws://127.0.0.1:36465/devtools/browser/b95169ad-0f17-4df6-b48a-8c14bed29a6a
[ +607 ms] DwdsInjector: Received request for entrypoint at http://localhost:45147/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +19 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[  +18 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:45147/main_module.bootstrap.js
[+2211 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: false
[ +544 ms] DevHandler: Debug service listening on ws://127.0.0.1:40433/yCLcfBjNrHI=/ws

[  +10 ms] Debug service listening on ws://127.0.0.1:40433/yCLcfBjNrHI=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +8 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
```

```
Analyzing flutter_playground...                                         
No issues found! (ran in 3.4s)
```

```
 ~/Documents/repos/flutter_playground  flutter doctor -v
[✓] Flutter (Channel master, 1.27.0-2.0.pre.98, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.27.0-2.0.pre.98 at /home/william/Documents/flutter
    • Framework revision 696e4f70d1 (il y a 14 heures), 2021-02-13 18:31:02 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/william/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.0.0 (Fedora 11.0.0-2.fc33)
    • cmake version 3.18.4
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 2 categories.
```

</details>

**Comment by iapicca** [comment] 2021-02-14 20:55
possible duplicate of https://github.com/flutter/flutter/issues/73628

**Comment by pedromassangocode** [comment] 2021-02-15 08:00
Closing as duplicate of https://github.com/flutter/flutter/issues/76003. Please follow up on that issue.
Thank you

**Closed by pedromassangocode** 2021-02-15 08:00 UTC
