### ISSUE TITLE
When the visual keyboard is visible; Web has no bottomInset, while native does

### ISSUE THREAD

**Issue by vazkir** [flutter/flutter#56039] opened 2020-04-30 12:18 UTC
## The problem

I am trying to get my form with multiple TextFormFields, to scroll and work on both native and web for the last few days, but these 2 issues are making pretty hard to be consistent between my web and native App:

#### First issue
It seems that the MediaQuery yields different results on web and native, mainly that;
- Native: Has a bottominset when the keyboard is visible, but the height stays the same.
- Web: Has no botteminset when the keyboard is visible, but it does change in height.

#### Second issue
The Scafold's resizeToAvoidBottomInset doesn't work on web. Below I have added gifs for the resizeToAvoidBottomInset set to true and set to false for both platforms, so 4 gifs in total.

## Steps to Reproduce

This is the sample code I created to simulate the exact issue:
```

```
Do note that you have to change the "resizeToAvoidBottomInset" from true to false, to also see that this setting seems to have no effect on web.

#### Native (iOS Iphone Xr):

Note: The left the screenrecorded gifs are the ones with "resizeToAvoidBottomInset" set to true, and the right ones set to false

![](https://media.giphy.com/media/YN2FZOL6IXiaW27iKK/giphy.gif) | ![](https://media.giphy.com/media/TjXFumEhSQUFZItVc3/giphy.gif)

Which both will print this:
```
flutter: Web is false and bottom inset -> 0.0 and height: 896.0
flutter: Web is false and bottom inset -> 346.0 and height: 896.0
flutter: Web is false and bottom inset -> 0.0 and height: 896.0
```

#### Mobile Safar (iOS Iphone Xr):
![](https://media.giphy.com/media/WPu209e7rzphN6OGRH/giphy.gif) | ![](https://media.giphy.com/media/RkoZbGRyFvlwlRIMWF/giphy.gif)

Which both will print this:
```
[Log] Web is true and bottom inset -> 0 and height: 719 (main.dart.js, line 3930)
[Log] Web is true and bottom inset -> 0 and height: 412 (main.dart.js, line 3930)
[Log] Web is true and bottom inset -> 0 and height: 719 (main.dart.js, line 3930)
```

## My own interpretation

The height sizes are not similar between native and web (ofcourse;)), because you have the top and bottom bezels when using the browser. 

#### Regarding the first issue
I did notice that the screen actually get's smaller on both platforms, when the "resizeToAvoidBottomInset" is set to true. Because this makes sure that there is no actual inset. Meaning that I can't scroll on both platforms when the visual keyboard is up. 

So I believe that perhaps the bottomInset value on native could be wrong, since it's the size of the screen that changes and not the bottominset. 

<details>
<summary>code sample</summary>

```dart
class LoginPage extends StatefulWidget {
  LoginPage();

  @override
  State<StatefulWidget> createState() {
    return LoginPageState();
  }
}

class LoginPageState extends State<LoginPage>  {
  final double _spacingFields = 10.0;

  @override
  Widget build(BuildContext context) { 
    final _keyboardBottomInset = MediaQuery.of(context).viewInsets.bottom;
    final _screenHeight = MediaQuery.of(context).size.height;
    print("Web is $kIsWeb and bottom inset -> $_keyboardBottomInset and height: $_screenHeight");

    return Scaffold(
      appBar: AppBar(title: Text("Test bottom inset")),
      resizeToAvoidBottomInset: true,
      body: Container(
        child: Center(
          child:SingleChildScrollView(
            reverse: false,
            child: Column(
              children: [
                TextField(decoration: InputDecoration(border: OutlineInputBorder(),labelText: 'Something')),
                SizedBox(height: _spacingFields),
                TextField(decoration: InputDecoration(border: OutlineInputBorder(),labelText: 'Something')),
                SizedBox(height: _spacingFields),
                TextField(decoration: InputDecoration(border: OutlineInputBorder(),labelText: 'Something')),
                SizedBox(height: _spacingFields),
                TextField(decoration: InputDecoration(border: OutlineInputBorder(),labelText: 'Something')),
              ],
            )
          )
        )
      )
    );  
  }
}
```
</details>

#### The second issue
Maybe this can be because there are some issues with safari web regarding the visual keyboard, where people noticed that the screen will always move up to make room for the keyboard.

- Medium article explaining the behavior:
https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d

- A possible solution managing keyboard change, from stackoverflow:
https://stackoverflow.com/questions/39417778/iphone-safari-not-resizing-viewport-on-keyboard-open

- New visual viewport API (from iOS 13) making handling viewports easier:
https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API

## Logs

<details>
  <summary>flutter doctor -v logs</summary>
```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.3 19D76, locale en-NL)
    • Flutter version 1.18.0-8.0.pre at /Users/vascowerk/Development/flutter
    • Framework revision e0c63cd35e (6 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vascowerk/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (5 available)
    • iPhone        • 00008020-000568861146002E            • ios            • iOS 13.3
    • iPhone 6      • 0A8F65D1-C945-4584-88E0-6D790C7E65BD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)
    • iPhone 7 Plus • 4778B1FE-65BB-4781-94EC-E27364EFE8C8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)
    • Web Server    • web-server                           • web-javascript • Flutter Tools
    • Chrome        • chrome                               • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```
</details>

**Comment by nturgut** [comment] 2020-05-15 22:45
Can you please check this issue again?

We made some changes in the viewInsets on web: https://github.com/flutter/engine/pull/18328

**Comment by AresVampire** [comment] 2020-05-25 21:14
It is not working for me too for the latest version.
`resizeToAvoidBottomInset` or `resizeToAvoidBottomPadding` has no effect at all on Flutter web.

**Comment by tomasbaran** [comment] 2020-06-03 07:58
In @10686142' samples code:

- iOS13 listens to `resizeToAvoidBottomInset: true`
- iOS12 (iPhone SE): DOES NOT listen to  `resizeToAvoidBottomInset: true` and doesn't move the Textfields towards to top of the screen:

![Grabación de pantalla 2020-06-03 a las 8 56 23](https://user-images.githubusercontent.com/25743901/83611032-49245d80-a578-11ea-9aef-a106974033fc.gif)

**Comment by 10686142** [comment] 2020-06-18 09:20
> Can you please check this issue again?
> 
> We made some changes in the viewInsets on web: [flutter/engine#18328](https://github.com/flutter/engine/pull/18328)

The issue seems to be resolved for iOS 13 but I noticed just like @tomasbaran that there seems to be another issue for devices lower than iOS 13. Now the issue seems to be no bottom inset happens at al for those devices.

The left one is with resizetoAvoidBottomInset set to 'true' and left with 'false'
![](https://media.giphy.com/media/dy9UB3aWyLjyAEMQrJ/giphy.gif) ![](https://media.giphy.com/media/YqQ7Zos1yjeSjXCCO5/giphy.gif)

**Comment by pdivita** [comment] 2020-06-26 10:36
My text TextFormFields doesn't scroll on a similar example, on Android (didn't test on ios). The weird thing is that same code works on an old project.
I figured out that viewInsets.bottom is never updated (I'm using flutter  v1.17.4).
More info here #60348

**Comment by nturgut** [comment] 2020-06-26 17:26
I assigned to myself for triage. "assigned for triage" label is also added.

**Comment by TahaTesser** [comment] 2021-01-28 15:41
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: LoginPage(),
    );
  }
}

class LoginPage extends StatefulWidget {
  LoginPage();

  @override
  State<StatefulWidget> createState() {
    return LoginPageState();
  }
}

class LoginPageState extends State<LoginPage> {
  final double _spacingFields = 10.0;

  @override
  Widget build(BuildContext context) {
    final _keyboardBottomInset = MediaQuery.of(context).viewInsets.bottom;
    final _screenHeight = MediaQuery.of(context).size.height;
    print(
        "Web is $kIsWeb and bottom inset -> $_keyboardBottomInset and height: $_screenHeight");

    return Scaffold(
        appBar: AppBar(title: Text("Test bottom inset")),
        resizeToAvoidBottomInset: false,
        body: Container(
            child: Center(
                child: SingleChildScrollView(
                    reverse: false,
                    child: Column(
                      children: [
                        TextField(
                            decoration: InputDecoration(
                                border: OutlineInputBorder(),
                                labelText: 'Something')),
                        SizedBox(height: _spacingFields),
                        TextField(
                            decoration: InputDecoration(
                                border: OutlineInputBorder(),
                                labelText: 'Something')),
                        SizedBox(height: _spacingFields),
                        TextField(
                            decoration: InputDecoration(
                                border: OutlineInputBorder(),
                                labelText: 'Something')),
                        SizedBox(height: _spacingFields),
                        TextField(
                            decoration: InputDecoration(
                                border: OutlineInputBorder(),
                                labelText: 'Something')),
                      ],
                    )))));
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.229, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.229 at /Users/tahatesser/Code/flutter_master
    • Framework revision 650b240634 (2 hours ago), 2021-01-27 21:39:06 -0800
    • Engine revision 68cd4c42b5
    • Dart version 2.12.0 (build 2.12.0-267.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by amr-eniou-3r** [comment] 2021-09-01 10:29
I used this solution to hide the bottom navigation bar
https://stackoverflow.com/questions/48750361/flutter-detect-keyboard-open-close/63241409#63241409

**Comment by razfazz** [comment] 2022-06-18 08:21
this issue might be related to this https://stackoverflow.com/questions/62972305/how-to-disable-the-behavior-bottom-navigation-bar-goes-up-with-keyboard-in-flutt

**Comment by danagbemava-nc** [comment] 2024-04-17 11:26
On my iPhone XS running iOS 17, it web seems to react well to media query changes. I do not have a device running an older version of iOS so I cannot confirm if this is fixed on lower versions of iOS. Can anyone confirm if this issue still reproduces with an older version of iOS on the latest version of flutter? 


https://github.com/flutter/flutter/assets/88313112/53d8c984-7c58-47c9-b678-30e3393a1b42

**Closed** 2024-05-08 12:09 UTC
Labels: platform-ios, waiting for customer response, framework, platform-web, a: layout, has reproducible steps, P3, found in release: 1.25, found in release: 1.26, team-framework, triaged-framework
