### ISSUE TITLE
Building iOS app generates Flutter.build folder with dgph files under ios/build/

### ISSUE THREAD

**Issue by jaeyoi** [flutter/flutter#89912] opened 2021-09-11 11:43 UTC
## Steps to Reproduce

1. Add a package to pubspec. (ex. in_app_purchase)
1. Run `flutter run` with iPhone simulator.
1. **q**uit.
1. Run `flutter run` again.

**Expected results:**
No 'bulid' folder in ios

**Actual results:**
A new folder will appear in ios folder.
![스크린샷 2021-09-11 오후 8 32 13](https://user-images.githubusercontent.com/1281315/132946527-10dd98f3-abeb-42f2-9494-23a34e9e20df.png)

<details>
  <summary>Logs</summary>

```
```
[run-verbose.txt](https://github.com/flutter/flutter/files/7147705/log.txt)

```
Analyzing flutter_application_25...                                     
No issues found! (ran in 2.0s)
```

```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1323 darwin-x64, locale ko-KR)
    • Flutter version 2.5.0 at /usr/local/Caskroom/flutter/2.0.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jaeyoi/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0
    • ANDROID_HOME = /Users/jaeyoi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 77F672B8-FB55-4269-AE26-340031FA342C • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment] 2021-09-13 12:24
@jaeyoi 
I do see the said file and it may have something to do with cocoapods.

<img width="603" alt="Screenshot 2021-09-13 at 5 53 05 PM" src="https://user-images.githubusercontent.com/67046386/133082723-6285de47-060a-4bcb-9a0a-63355e6413c1.png">

Wondering why do you think there should be no `build` folder ?

**Comment by cervm** [comment] 2021-09-13 13:43
I can confirm the same issue with Flutter 2.5. In our case, it ends up creating over 20 such files. It's enough to run `flutter pub get` to reproduce.

@darshankawar I believe there should be no `build` folder under `ios` since there was never one before Flutter 2.5, and Git would track it. Providing this is expected behavior, I'd assume such folder (or the dgph files) be added to `.gitignore` under `ios`, which is not the case.

**Comment by jaeyoi** [comment] 2021-09-14 00:18
@darshankawar I have the same thoughts as @cervm

**Comment by darshankawar** [comment] 2021-09-14 06:27
Thanks for the details @cervm and @jaeyoi. I do see the same behavior comparing with 2.2.3.

1. On Stable 2.2.3, adding a plugin and then running `flutter pub get`, doesn't generate the said folders under `build` as below:

<img width="617" alt="Screenshot 2021-09-14 at 11 52 21 AM" src="https://user-images.githubusercontent.com/67046386/133206161-847b062e-28c4-4051-9e30-ee4650e5e8b7.png">


2. On Stable 2.5.0, running same command shows below folders with dgph files:

<img width="626" alt="Screenshot 2021-09-14 at 11 55 01 AM" src="https://user-images.githubusercontent.com/67046386/133206224-9ee41a2f-d57c-4602-ace3-8e96922eac63.png">


<details>
<summary> stable 2.2.3 and 2.5.0 flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 93.0.4577.63

• No issues found!


[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.0 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 93.0.4577.63

• No issues found!

```

</details>


Keeping this open for further insights from the team.

/cc: @jmagman

**Comment by jmagman** [comment] 2021-09-14 18:06
Thanks for the report, we didn't notice that.
`dgph` file` shouldn't be checked in.  You can add `**/dgph` to your `ios/.gitignore`.

**Comment by jmagman** [comment] 2021-09-14 21:12
This was caused by #87244.  It can be reproduced by running `cd ios && xcodebuild -alltargets -sdk iphonesimulator -project Pods/Pods.xcodeproj -showBuildSettings`, which is what that commit does.  The xcodebuild command is missing `BUILD_DIR`.

**Closed** 2021-09-16 01:37 UTC
Labels: platform-ios, tool, customer: crowd, t: xcode, has reproducible steps, P3, found in release: 2.5

**Comment by devoncarew** [comment] 2021-10-11 17:00
@godofredoc - after cherry picking, can you add the cp: xx label? Thanks!
