### ISSUE TITLE
camera plugin doesn't work with android_alarm_manager

### ISSUE THREAD

**Issue by sestegra** [flutter/flutter#20913] opened 2018-08-22 14:45 UTC
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.6 17G65, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

• No issues found!
```

**Steps to reproduce the issue**
- Clone flutter plugins repo
- Go to android_alarm_manager example directory
- Run following commands to run example
$flutter packages get
$flutter packages run
=> it's work well
- Add camera 0.2.1 in pubspec.yaml
- Run following commands to run updated example
$flutter packages get
$flutter packages run
Following NPE occurs.

```
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: Failed to handle method call
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at io.flutter.plugins.camera.CameraPlugin.registerWith(CameraPlugin.java:132)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at io.flutter.plugins.androidalarmmanagerexample.Application.registerWith(Application.java:18)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at io.flutter.plugins.androidalarmmanager.AlarmService.startAlarmService(AlarmService.java:65)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.startService(AndroidAlarmManagerPlugin.java:75)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:52)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:165)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at android.os.MessageQueue.next(MessageQueue.java:328)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at android.os.Looper.loop(Looper.java:148)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at java.lang.reflect.Method.invoke(Native Method)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
08-22 16:38:04.366  8655  8655 E MethodChannel#plugins.flutter.io/android_alarm_manager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by anirudhrata** [comment] 2018-11-18 17:20
Hello @sestegra , I am facing the same issue when using camera plugin alongwith alarm manager or the android job scheduler plugin. Did you find any workaround to it? 

It looks like there should be an active UI to use the camera plugin. It runs properly when the app is open, but crashes with the NPE as soon as the activity is closed.

The line which causes the crash:
131: `cameraManager = (CameraManager) registrar.activity().getSystemService(Context.CAMERA_SERVICE);`

registrar.activity() is null in background isolate.

Let me know if you did find any workaround to the issue.

**Comment by sestegra** [comment] 2018-11-19 13:00
@anirudhrata Camera plugin need UI activity to get the context to work.

I suggest 2 options:
1) You should patch the plugin code by using directly context (see similar issue https://github.com/BaseflowIT/flutter-geolocator/pull/83/files).
2) Create your own GeneratedPluginRegistrant class and remove camera init.

**Comment by alexandranb** [comment] 2018-12-30 21:43
Hi,

Did you find a solution? I am facing the same problem with 2 other plugins and still no solution until now.

Thanks

**Comment by Hixie** [comment] 2019-01-03 07:32
The issue appears to be that the camera plugin is assuming there's an activity when it's registered.

**Comment by zzpmaster** [comment] 2019-01-18 08:30
Hi @sestegra ,   I am facing the same problem, Did you find some solution?

**Comment by alexandranb** [comment] 2019-01-18 08:35
Hi, 

Try to make a custom class for GeneratedPluginRegistrant  and remove the plugin init for Camera, then call it in Activity class.  This did the trick for me. However, I must let you know that the plugin doesn't work when the app is terminated. It only works in foreground.

Thanks

**Comment by zzpmaster** [comment] 2019-01-18 10:03
@alexandranb thanks

**Comment by stuartmorgan** [comment] 2021-05-26 17:39
Registration for Android plugins now works very differently; is this still reproducible with current versions of the plugins?

**Comment by darshankawar** [comment] 2021-09-03 11:10
Verified this issue using the latest plugin master and added [latest ](https://pub.dev/packages/camera/install)camera plugin to it and ran which didn't throw the NPE as mentioned in original description, although it throws below ClassNotFoundException` which I think isn't related to `camera` plugin.

<details>
<summary> error log </summary>

```


Launching lib\main.dart on SM A260G in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
E/AndroidRuntime(30309): FATAL EXCEPTION: main
E/AndroidRuntime(30309): Process: io.flutter.plugins.androidalarmmanagerexample, PID: 30309
E/AndroidRuntime(30309): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.flutter.plugins.androidalarmmanagerexample/io.flutter.plugins.androidalarmmanagerexample.DriverExtensionActivity}: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.androidalarmmanagerexample.DriverExtensionActivity" on path: DexPathList[[zip file "/data/app/io.flutter.plugins.androidalarmmanagerexample-8J1XQvMlHvHnK5W4RsqJlw==/base.apk"],nativeLibraryDirectories=[/data/app/io.flutter.plugins.androidalarmmanagerexample-8J1XQvMlHvHnK5W4RsqJlw==/lib/arm, /data/app/io.flutter.plugins.androidalarmmanagerexample-8J1XQvMlHvHnK5W4RsqJlw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
E/AndroidRuntime(30309): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2690)
E/AndroidRuntime(30309): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2872)
E/AndroidRuntime(30309): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(30309): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
E/AndroidRuntime(30309): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(30309): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(30309): 	at android.app.ActivityThread.main(ActivityThread.java:6543)
E/AndroidRuntime(30309): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30309): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E/AndroidRuntime(30309): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
E/AndroidRuntime(30309): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.androidalarmmanagerexample.DriverExtensionActivity" on path: DexPathList[[zip file "/data/app/io.flutter.plugins.androidalarmmanagerexample-8J1XQvMlHvHnK5W4RsqJlw==/base.apk"],nativeLibraryDirectories=[/data/app/io.flutter.plugins.androidalarmmanagerexample-8J1XQvMlHvHnK5W4RsqJlw==/lib/arm, /data/app/io.flutter.plugins.androidalarmmanagerexample-8J1XQvMlHvHnK5W4RsqJlw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
E/AndroidRuntime(30309): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/AndroidRuntime(30309): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(30309): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(30309): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
E/AndroidRuntime(30309): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2680)
E/AndroidRuntime(30309): 	... 9 more


```

</details>

Closing this as not reproducible using latest camera plugin version.

<details>
<summary> flutter doctor -v </summary>

```
C:\Users\Win>flutter doctor -v
Could not load custom device from config index 0: Expected enabled to be a boolean.
[√] Flutter (Channel master, 2.6.0-1.0.pre.170, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.6.0-1.0.pre.170 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4069c6355b (4 hours ago), 2021-09-03 02:11:05 -0400
    • Engine revision d6f6a0fe90
    • Dart version 2.15.0 (build 2.15.0-69.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.84

! Doctor found issues in 1 category.

C:\Users\Win>

```

</details>

**Closed by darshankawar** 2021-09-03 11:10 UTC
Labels: severe: crash, platform-android, plugin, p: first party, p: camera, P4
