### ISSUE TITLE
[webview_flutter] Whether the webview can add the mixedContentMode property

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#59227] opened 2020-06-11 02:59 UTC
[webview_flutter] Whether the webview can add the mixedContentMode property 😄

**Comment by TahaTesser** [comment] 2020-06-11 11:48
hi @2534290808 
Looks like there is an there is open [pr](https://github.com/flutter/plugins/pull/2468)

**Comment by stuartmorgan** [comment] 2023-07-09 21:13
Closing as a duplicate of https://github.com/flutter/flutter/issues/43595

**Closed by stuartmorgan** 2023-07-09 21:13 UTC
Labels: c: new feature, p: webview, package, c: proposal, team-ecosystem, P3, triaged-ecosystem
