### ISSUE TITLE
[in_app_purchase] Is possible to check active subscription on iOS

### ISSUE THREAD

**Issue by AathifMahir** [flutter/flutter#84436] opened 2021-06-11 12:28 UTC
When it comes to Android, we can query PastPurchases and Get the Active Subscription based on Past Purchases is empty or not, but on IOS is there any way to get the active and valid subsctiption?

**Comment by TahaTesser** [comment] 2021-06-11 13:59
Hi @AathifMahir 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/61339
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-11 13:59 UTC
Labels: in triage
