### ISSUE TITLE
[tool_crash] FileSystemException: Cannot retrieve modification time, OS Error: The operation completed successfully., errno = 0

### ISSUE THREAD

**Issue by ONOMSHI** [flutter/flutter#157670] opened 2024-10-26 12:50 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot retrieve modification time, OS Error: The operation completed successfully.
, errno = 0
```console
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.lastModifiedSync (dart:io/file_impl.dart:453:5)
#2      ForwardingFile.lastModifiedSync (package:file/src/forwarding/forwarding_file.dart:57:43)
#3      ForwardingFile.lastModifiedSync (package:file/src/forwarding/forwarding_file.dart:57:43)
#4      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:299:21)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1738:17)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19045.5011], locale en-US)
    [32m•[39m Flutter version 3.24.1 on channel stable at C:\Users\hp\AppData\Local\Android\Sdk\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5874a72aa4 (10 weeks ago), 2024-08-20 16:46:00 -0500
    [32m•[39m Engine revision c9b9d5780d
    [32m•[39m Dart version 3.5.1
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    [33m![39m Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default
      components

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[32m[✓][39m VS Code (version 1.94.2)
    [32m•[39m VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.5011]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 130.0.6723.70
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 130.0.2849.52

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5874a72aa4c779a02553007c47dacbefba2374dc
### Plugins
cloud_firestore-5.4.4
cloud_firestore_web-4.3.2
connectivity_plus-6.0.5
file_selector_linux-0.9.3
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
firebase_auth-5.3.1
firebase_auth_web-5.13.2
firebase_core-3.6.0
firebase_core_web-2.18.1
firebase_storage-12.3.2
firebase_storage_web-3.10.2
flutter_inappwebview-6.1.4
flutter_inappwebview_android-1.1.3
flutter_inappwebview_ios-1.1.2
flutter_inappwebview_macos-1.1.2
flutter_inappwebview_web-1.1.2
flutter_inappwebview_windows-0.5.0+2
flutter_local_notifications-17.2.3
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.22
image_picker-1.1.2
image_picker_android-0.8.12+14
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.3.3+2
toast-0.3.0
webview_flutter-4.9.0
webview_flutter_android-3.16.8
webview_flutter_wkwebview-3.15.0

**Comment by danagbemava-nc** [comment] 2024-10-28 08:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/134549

**Closed by danagbemava-nc** 2024-10-28 08:11 UTC
Labels: in triage
