### ISSUE TITLE
Inconsistent runtimeType.toString() in debug and release mode

### ISSUE THREAD

**Issue by Goxiaoy** [flutter/flutter#56232] opened 2020-05-03 09:52 UTC
I have this following codes:

```
  List<T> deserializeList<T>(String item) {
    var a=List<T>();
    var targetType=a.runtimeType.toString();
    return (ApiClient.deserialize(item,targetType ) as List ).cast<T>().toList();
  }
```

But the variable `targetType` return different value in debug and release mode

debug/profile: value like `List<xx>`;
release:  value like `_GrowableList<xx>`;

**Comment by TahaTesser** [comment] 2020-05-04 08:38
Hi @Goxiaoy 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Goxiaoy** [comment] 2020-05-04 09:32
code sample:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home:Scaffold(
          appBar: AppBar(
            title: Text("HH"),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  getTargetType<_A>(),
                ),
              ],
            ),
          )
      ),
    );
  }
}
class _A{
}

String getTargetType<T>() {
  var a=List<T>();
  var targetType=a.runtimeType.toString();
  return targetType;
}
```
Screen shots：
![image](https://user-images.githubusercontent.com/8577611/80952893-06fae580-8e2d-11ea-97ba-78bf61c0aa7f.png)
![image](https://user-images.githubusercontent.com/8577611/80952897-0b270300-8e2d-11ea-8505-ceb71d507fd0.png)

**Comment by Goxiaoy** [comment] 2020-05-04 09:38
`flutter doctor -v`

![微信图片_20200504173642](https://user-images.githubusercontent.com/8577611/80953417-0adb3780-8e2e-11ea-9ddd-66714cd919d0.png)

**Comment by TahaTesser** [comment] 2020-05-08 14:15
Hi @Goxiaoy 
Looks like this is my design
Please check this [comment](https://github.com/flutter/flutter/issues/56232)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-08 14:15 UTC
Labels: found in release: 1.12, found in release: 1.18, has reproducible steps

**Comment by Goxiaoy** [comment] 2020-05-08 14:55
@TahaTesser 
Hi, it seems that the link you just provided point to this issue again, so I am not sure where to find more information about this design

But I find something related in https://github.com/flutter/flutter/issues/56537#issuecomment-625217935  

> Code should not expect or rely on a particular format of toString output.

So I will just adjust my code base on this principal.
Thank you so much!

**Comment by Goxiaoy** [comment] 2020-05-08 15:31
And I personally do not agree with this because it's quite easy  for those who do not see this issue write some codes based on `runtimeType.toString()` to do some runtime check, which may cause unpredictable results in release mode.

For example

```
bool isAorListA(Type t){
  //some regex match based on t.toString()
}
```

**Comment by TahaTesser** [comment] 2020-05-08 16:10
Hi @Goxiaoy 
Updated the above comment

**Comment by mraleph** [comment] 2020-05-11 07:23
@Goxiaoy in general you should never depend on a particular format of `Type.toString` output. 

FYI @rmacnak-google @a-siva - I am not sure why we are disabling user visible name mapping in the PRODUCT VM builds - it seems to have been done intentionally in https://codereview.chromium.org/1723733002 - but the motivation is unclear from the CL itself. I don't think it saves a lot of space in the snapshot. Also we are inconsistent a bit with ourselves (we preserve some - but not all user visible names). Maybe we should consider undoing for the sake of consistency.
