### ISSUE TITLE
Previous field Keyboard type appearing on next field focus

### ISSUE THREAD

**Issue by abeeriqbal** [flutter/flutter#90049] opened 2021-09-14 13:08 UTC
We are facing issues on some Android devices that, When we focus on first input fields its shows correct keyboard. then when focusing on next fields its shows same type keyboard. when unfocus or focus again then its shows proper keyboard on textfield. Same things everywhere in app but on some android devices. i checked that on that devices other native apps, it doesn't make issue. It happens on Android 9 Xioami phone and infinix X688B model.
i also tried with Flutter 1.27, 2.20 and 2.5. Same issue on all versions.
Also Tried with Form, FormTextField and TextField but issue persist.
This need to be resolve asap

**Comment by maheshmnj** [comment] 2021-09-14 13:19
Hi @abeeriqbal, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v`.


Thanks.

**Comment by abeeriqbal** [comment] 2021-09-14 14:51
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80 darwin-arm, locale en-US)
    • Flutter version 2.5.0 at /Users/abeeriqbal/Desktop/Abeer/Flutter/Things/flutter2.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/abeeriqbal/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Users/abeeriqbal/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/abeeriqbal/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • haytxgamcey5swsc                     • android-arm64  • Android 11 (API 30)
    • iPhone 8 Plus (mobile)    • 0869D13C-ACAF-4DC3-A423-4A8FD4718E3A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 93.0.4577.82
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
    ! Error: E&S mobile is not connected. Xcode will continue when E&S mobile is connected. (code -13)

• No issues found!

**Comment by abeeriqbal** [comment] 2021-09-14 15:06
Issue also reproduce with new application
Sample issue code. 
class Text extends StatefulWidget {
  const Text({Key key}) : super(key: key);

  @override
  TextState createState() => TextState();
}

class _TextState extends State<Text> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Center(
          child: Column(crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: TextField(
                  keyboardType: TextInputType.number,
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: TextField(
                  keyboardType: TextInputType.text,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by maheshmnj** [comment] 2021-09-15 04:56
@abeeriqbal  Thanks for the details, I ran your code sample on the emulator and the physical Android Device on the latest stable channel 2.5.0 but could not reproduce the issue it seems to be opening the right keyboard.  Are you experiencing this issue only the first time when focusing on a different keyboard type or always? And is this reproducible on IOS too?



https://user-images.githubusercontent.com/31410839/133372794-a6889e37-689a-415f-b4b8-52eb889ece06.mov


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.6:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
``` 

</details>

**Comment by abeeriqbal** [comment] 2021-09-15 05:18
As i mentioned its appearing only on Some android devices, on other devices its have no issue. Issue reproduced on Android 9 Xioami phone and infinix X688B model. It also appear everytime on these phones
One phone specification screenshot given below
<img width="283" alt="Screen Shot 2021-09-15 at 10 17 59 AM" src="https://user-images.githubusercontent.com/10529652/133374963-f25622d0-2325-44e6-b236-c964728ff95a.png">

**Comment by maheshmnj** [comment] 2021-09-15 05:21
@abeeriqbal can you share a recording to understand the issue better?

**Comment by maheshmnj** [comment] 2021-09-15 05:23
Labeling this issue as a bug for further investigation as this issue looks device specific

**Comment by abeeriqbal** [comment] 2021-09-29 07:12
Any update on it?

**Comment by maheshmnj** [comment] 2021-09-29 14:25
cc: @justinmc

**Comment by justinmc** [comment] 2021-09-29 17:27
@LongCatIsLooong Do we have a Xiaomi phone we could try this on?

**Comment by LongCatIsLooong** [comment] 2021-09-29 17:49
There're a few on the test device rack IIRC.

**Comment by camsim99** [comment] 2023-08-17 18:27
This seems to be a duplicate of https://github.com/flutter/flutter/issues/73388. Closing this in favor of that one

**Closed by camsim99** 2023-08-17 18:27 UTC
Labels: a: text input, e: device-specific, platform-android, framework, f: material design, team-android, multiteam-retriage-candidate
