### ISSUE TITLE
[Flutter Web]Web-side rendering exception On Release

### ISSUE THREAD

**Issue by sunjianan9900** [flutter/flutter#104600] opened 2022-05-25 10:09 UTC
The same code is rendered inconsistently in Release mode and Debug mode. And the Release mode rendering is wrong.

Exported by
`flutter build web --release --web-renderer html`

Release state with color rendering exception. The first item should be red, not green
![image](https://user-images.githubusercontent.com/10936316/170230354-9b85a971-2b66-416c-b15a-df48d95df675.png)

Debug mode is displayed normally.

Normal condition: the first bar should be red

Minimal code package：
[icon_maker_web.zip](https://github.com/imaNNeoFighT/fl_chart/files/8769786/icon_maker_web.zip)

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm (Rosetta),
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

```

**Comment by sunjianan9900** [comment] 2022-05-26 03:13
Can anyone explain the reason for this problem?

**Comment by sunjianan9900** [comment] 2022-05-26 04:28
Currently it has been found that reducing the data source to less than one screen does not cause problems. As soon as the number of X-axes exceeds the number that can be displayed on one screen, the problem occurs.


Problem blocks.
 data1 = 77
 data2 = 0

 BarChartRodStackItem(data1, data1 + data2, AppColor.d2)

If data1 = data1 + data2 there is a problem

 BarChartRodStackItem(data1, data1 + data2 + 1, AppColor.d2)

If the value is slightly + 1, there will be no exception

**Comment by huycozy** [comment] 2022-05-26 04:46
Hi @sunjianan9900,
From what I can see, the issue is related to a 3rd party plugin [fl_chart](https://pub.dev/packages/fl_chart) rather than to Flutter itself. Please open the issue in the dedicated [fl_chart repository](https://github.com/imaNNeoFighT/fl_chart/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-05-26 04:46 UTC
Labels: in triage

**Comment by sunjianan9900** [comment] 2022-05-26 04:48
This problem only exists in html mode rendering in Release mode, Debug mode does not appear, the same code case, is it not a problem of flutter rendering?

**Comment by huycozy** [comment] 2022-05-27 05:17
Hi. In order for us to be able to solve this, we'll need a reproduction that doesn't depend on a complex package, such as [fl_chart](https://pub.dev/packages/fl_chart). 

A couple of possibilities:
- File an issue with package [fl_chart](https://pub.dev/packages/fl_chart). If they conclude that the issue is in Flutter Web, they could file an issue with more concrete repro steps here.
- Try to distill the issue into a repro case without the dependency.

Thanks!
