### ISSUE TITLE
[local_auth] Flutter 1.25.0-8.1.pre (beta) -- Because local_auth >=0.6.0+1 depends on intl >=0.15.1 <0.17.0 and my_app depends on intl ^0.17.0-nullsafety.2, local_auth >=0.6.0+1 is forbidden.

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#72682] opened 2020-12-20 15:17 UTC
## Steps to Reproduce

1. Upgrade to latest beta branch version: `1.25.0-8.1.pre`
2. Add `intl` to your project: `intl: ^0.16.1`. You will get this error:
```
Because my_app depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.
```
3. Add the latest release of `local_auth` to your project: `local_auth: ^0.6.3+4`
4. Update your `intl` to that version: `intl: 0.17.0-nullsafety.2`.
5. Now you will get this error:
6. Because local_auth >=0.6.0+1 depends on intl >=0.15.1 <0.17.0 and my_app depends on intl ^0.17.0-nullsafety.2, local_auth >=0.6.0+1 is forbidden.

**Expected results:** 
Should be able to use `local_auth` on the latest beta channel release.

**Actual results:** 
Unable to get packages on the latest beta channel release.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2020-12-21 07:35
Hi @acoutts 
Please see [Conflict resolution](https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution) section to see how to solve this version conflict.

Closing as this is not an issue with flutter itself. If you disagree please comment and I will reopen it.
Thank you

**Comment by acoutts** [comment] 2020-12-21 09:58
I think there is an issue because flutter 1.25.0-8.1.pre now uses the nullsafety pre-release of intl. There's no pub versions for `flutter_localizations` to change to, it has to be `sdk`. Now that the sdk has bumped its dependency on intl, packages using intl need to bump theirs too.

local_auth needs to use the nullsafety pre-release as well or else nobody can update beyond 1.24.0-10.2.pre.

**Comment by acoutts** [comment] 2020-12-21 10:26
@pedromassangocode

**Comment by pedromassangocode** [comment] 2020-12-21 14:10
Hi @acoutts 
I cannot reproduce the step #2 you mentioned, as you can see using Flutter beta and the two packages does not throws any error.

![gif](https://user-images.githubusercontent.com/67424416/102785174-d0fb7900-439d-11eb-8a1a-467948e9b04d.gif)

Can you please provide your pubspec.yaml?
Thank you

**Comment by acoutts** [comment] 2020-12-23 15:34
@pedromassango please include `flutter_localizations` too. This will reproduce the issue:

```yaml
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  local_auth: ^0.6.3+3
  flutter_localizations:
    sdk: flutter
```

**Comment by acoutts** [comment] 2020-12-23 15:36
The `local_auth` package needs updated to use `intl 0.17.0-nullsafety.2` like the sdk uses with `flutter_localizations`.

**Comment by pedromassangocode** [comment] 2020-12-28 06:38
I was able to reproduce the issue.

<details><summary>Logs</summary>

```
Running "flutter pub get" in flutter_example...                 

Because local_auth >=0.6.0+1 depends on intl >=0.15.1 <0.17.0 and flutter_example depends on intl ^0.17.0-nullsafety.2, local_auth >=0.6.0+1 is forbidden.
So, because flutter_example depends on local_auth ^0.6.3+4, version solving failed.
pub get failed (1; So, because flutter_example depends on local_auth ^0.6.3+4, version solving failed.)
Process finished with exit code 1
```
</details>

**Comment by stuartmorgan** [comment] 2021-03-09 12:20
The null-safe version of `local_auth` uses 0.17

**Closed by stuartmorgan** 2021-03-09 12:20 UTC
Labels: found in release: 1.26, has reproducible steps, p: first party, p: local_auth, passed first triage, plugin
