### ISSUE TITLE
AppIcon gets overridden adding Flutter to app

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/flutter#31156] opened 2019-04-16 21:56 UTC
When developing and then uploading the iOS app to TestFlight, not my icon is taken into account, but the Flutter icon from the `.ios` folder.

## Steps to Reproduce

1. Setup Flutter [Add2App](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)
2. Build and run the app and the see that the app icon on the home screen is the Flutter icon 
3. If this is not the case build and upload the app to TestFlight and then the Flutter icon is picked up and not the defined icon in the iOS Info.plist

## Logs
<details>
<summary>flutter analyze</summary>

taking too long for me to finish ...
```
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.3 18D109, locale
    en-US)
    • Flutter version 1.4.9-hotfix.1 at /Users/denniskugelmann/develop/flutter
    • Framework revision 88fa7ea403 (5 days ago), 2019-04-11 14:01:46 -0700
    • Engine revision 4737fc5cd8
    • Dart version 2.2.1 (build 2.2.1-dev.4.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/denniskugelmann/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/denniskugelmann/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/denniskugelmann/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 417E55AD-59A0-4372-B4A3-DBAD31DDA867 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

</details>

**Comment by IchordeDionysos** [comment] 2019-06-20 15:41
Maybe related to #32883

**Comment by jmagman** [comment] 2019-12-20 23:43
You filed this first, but there's more information in https://github.com/flutter/flutter/issues/32883.
Duplicate of #32883.

**Closed by jmagman** 2019-12-20 23:43 UTC
Labels: a: existing-apps
