### ISSUE TITLE
`DraggableScrollableSheet` doesn't maintain size after rebuild

### ISSUE THREAD

**Issue by SuperPenguin** [flutter/flutter#101114] opened 2022-03-31 12:54 UTC
## Steps to Reproduce

1. Run code below
2. Try expand the sheet by scroll, tap light and dark button
3. Minimize sheet, now expand it by tapping the button, tap light and dark button

**Expected results:** Sheet maintain it size

**Actual results:** Sheet lost the size and went back to initial size during rebuild if previous size was changed from controller

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const App());
}

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  State<App> createState() => AppState();

  static AppState of(BuildContext context) {
    return context.findAncestorStateOfType<AppState>()!;
  }
}

class AppState extends State<App> {
  ThemeMode _themeMode = ThemeMode.light;

  void setThemeMode(ThemeMode mode) {
    if (_themeMode != mode) {
      setState(() {
        _themeMode = mode;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      themeMode: _themeMode,
      theme: ThemeData(brightness: Brightness.light),
      darkTheme: ThemeData(brightness: Brightness.dark),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Demo'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            showModalBottomSheet(
              context: context,
              isScrollControlled: true,
              builder: (context) => const _DemoSheet(),
            );
          },
          child: const Text('Open'),
        ),
      ),
    );
  }
}

class _DemoSheet extends StatefulWidget {
  const _DemoSheet({Key? key}) : super(key: key);

  @override
  _DemoSheetState createState() => _DemoSheetState();
}

class _DemoSheetState extends State<_DemoSheet> {
  final _draggableController = DraggableScrollableController();

  void _expand() {
    _draggableController.animateTo(
      0.9,
      duration: const Duration(milliseconds: 150),
      curve: Curves.easeOut,
    );
  }

  void _setTheme(ThemeMode themeMode) {
    App.of(context).setThemeMode(themeMode);
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return DraggableScrollableSheet(
      controller: _draggableController,
      initialChildSize: 0.5,
      minChildSize: 0.2,
      maxChildSize: 0.9,
      expand: false,
      builder: (context, scrollController) => ListView(
        physics: const BouncingScrollPhysics(),
        controller: scrollController,
        children: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: ElevatedButton(
              onPressed: _expand,
              child: const Text('Expand'),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              'Current brightness: ${theme.brightness}',
              textAlign: TextAlign.center,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: ElevatedButton(
              onPressed: () => _setTheme(ThemeMode.light),
              child: const Text('Light'),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: ElevatedButton(
              onPressed: () => _setTheme(ThemeMode.dark),
              child: const Text('Dark'),
            ),
          ),
          for (int i = 0; i < 100; i++)
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                i.toString(),
                textAlign: TextAlign.center,
              ),
            ),
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel unknown, 2.10.4, on macOS 12.1 21C52 darwin-arm, locale en-ID)
    • Flutter version 2.10.4 at /Users/s21/Documents/GitHub/flutter/flutter
    • Upstream repository unknown
    • Framework revision c860cba910 (6 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/s21/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • E31DBB95-A1F1-4893-AF0C-48C839A6A434 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/1574722/161059139-890ee69f-9f3a-49ba-ad79-9b086fd54a0d.mov

**Comment by darshankawar** [comment] 2022-03-31 13:27
Thanks for the report. Using code sample provided, I do see same behavior, ie, the the widget doesn't maintain the size after dragging it to expand and then clicking the light and dark button, which resets the size of the widget.
This happens using both options, ie using `expand` button and also manually dragging / scrolling the sheet to expanded state.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.329, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.329 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c6918933e (77 minutes ago), 2022-03-30 20:30:09 -0700
    • Engine revision a1106daced
    • Dart version 2.17.0 (build 2.17.0-249.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by campovski** [comment] 2022-04-04 10:45
The same issue persists if you call `jumpTo` method. The problem is caused by setting
```dart
_attachedController!.extent.hasDragged = false;
```
in `jumpTo` and `animateTo` methods. If you comment this line out, it works, however this line has to be there for other purposes, but this is a good starting point for debugging.

I can take a more in-depth look into this in upcoming days if requested and come up with solution.

**Comment by ltoenjes** [comment] 2022-04-18 07:52
> The same issue persists if you call `jumpTo` method. The problem is caused by setting
> 
> ```dart
> _attachedController!.extent.hasDragged = false;
> ```
> 
> in `jumpTo` and `animateTo` methods. If you comment this line out, the issue is gone, however this line has to be there for other purposes, but this is a good starting point for debugging.
> 
> I can take a more in-depth look into this in upcoming days if requested and come up with solution.

This doesn't seem to only happen when using jumpTo or animateTo but also after simply dragging. For me at least. Commenting out this line works in all these cases. In my setup i have a text input at the bottom, so this happens every time the text input is focused and the keyboard pops up.
Have you found a solution yet @campovski?

**Comment by campovski** [comment] 2022-04-18 08:56
@ltoenjes I didn't manage to investigate further yet. It didn't seem to me that this issue is urgent since nobody interacted with it. I will take a look at it these week.

**Comment by ltoenjes** [comment] 2022-04-18 09:52
@campovski i did some debugging. I was able to fix it by replacing `initialSize: widget.initialChildSize` with `initialSize: _extent.currentSize` in the `replaceExtent` method of `_DraggableScrollableSheetState`.

**Comment by TahaTesser** [comment] 2022-07-01 07:28
Assigning the same priority label as the duplicate [issue](https://github.com/flutter/flutter/issues/106777).

**Comment by sanekyy** [comment] 2022-07-11 14:49
Hi!

There ara some things which I found during research of this behaviour:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/18647037/178289747-5865b896-e638-4b97-8c99-56fb722d563e.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/18647037/178290081-c3ab1797-98dc-483b-a067-c7d098ff1c57.png">

On second screenshot we can see that comments says that `programmatically set size` have to be respected too.

But on the next screenshot we can see that it always pick `initialSize` regardless has bottom sheet been dragged programmatically (via animateTo/jumpTo of `DraggableScrollableController`) or not.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/18647037/178290797-bc259a57-286a-4d46-96ce-b0e3401e8b58.png">

So `hasDragged` set to `true` only on user drag.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/18647037/178291316-9adefd6d-c108-449a-8738-762a79185dc4.png">

It should some how set  hasDragged to true after first call of animateTo/jumpTo on `DraggableScrollableController`

**Comment by caseycrogers** [comment] 2022-07-11 14:50
Yeah this one's on me. I added `hasDragged` to handle subtle behavior around whether or not to snap and didn't think through all of the consequences sufficiently. I'll revisit this and throw out a PR for it this weekend.

Here is hideous work around for the time being:
```dart
void _simulateDrag() {
  (widget.controller.position as ScrollPositionWithSingleContext).applyUserOffset(.1);
}
```

Whenever you trigger a programmatic change, after call:
```dart
WidgetsBinding.instance.addPostFrameCallback((_) => _simulateDrag());
```

**Comment by caseycrogers** [comment] 2022-07-19 00:47
PR is up, just waiting on tests and then review.

**Comment by SuperPenguin** [comment] 2022-07-30 14:09
@caseycrogers I guess this issue is now fixed? Quite weird the PR is merged but the issue is not auto closed

**Comment by caseycrogers** [comment] 2022-08-04 23:19
I'm not sure why the corresponding issue is not closed. Either way, yeah it's merged and just waiting to make it to release.

FWIW I really hate that issues get closed on merge (and not on release) as it makes it really hard to tell when you should expect a bug to be resolved in your production app. I'll leave it to others to close the issue as they see fit.

**Comment by kamami** [comment] 2022-08-11 12:48
Is this already available on any branch?

**Comment by sanekyy** [comment] 2022-08-11 13:01
> Is this already available on any branch?

Master

https://github.com/flutter/flutter/pull/107876

**Comment by bleroux** [comment] 2022-08-11 13:44
The new autosubmit bot didn't close linked issue when the PR for this issue was merged.
This is fixed now, see https://github.com/flutter/flutter/issues/106211#issuecomment-1194543471.

**Closed by bleroux** 2022-08-11 13:44 UTC
Labels: framework, f: material design, f: scrolling, has reproducible steps, P4, found in release: 2.10, found in release: 2.13
