### ISSUE TITLE
Add support for running the iOS app on macOS without the simulator

### ISSUE THREAD

**Issue by ellet0** [flutter/flutter#145908] opened 2024-03-28 15:31 UTC
### Use case

First of all I'm not sure if this a duplicated issue or can't be supported by flutter side, Xcode support this feature of running the the `iOS` app on macOS directly and the native code like request notifications permissions of iOS will run as if it was on macOS without having to have the `macOS` project at all

![image](https://github.com/flutter/flutter/assets/73608287/ae597b6f-2c42-41d6-b8f6-993ac291fed9)

I can run the iOS project on macOS without any issues using Xcode by open the iOS native platform project which will be created by `flutter create . --platforms=iOS` but features like hot reload and hot restart is not available, I'm wondering if flutter can add support for running and show it in the list of available devices:

![image](https://github.com/flutter/flutter/assets/73608287/e8792da9-7249-4a06-bac6-20b4b93d947e)

### Proposal

It would be really nice if we can launch the iOS app on macOS using Flutter CLI as almost macOS app without the simulator or having to sign and maintain a different platform project

All what is missing the hot reload and hot restart features and add it to the list of devices in Flutter CLI which will affect both Android Studio and VS Code

Yes it can't replace platform native macOS project but there is a lot of flutter plugins that still doesn't have good support for macOS as the iOS and Android and I'm having build issues all the time with CocoaPods

I was able to launch my iOS app on macOS and the native functions like requesting the notifications permission on the iOS app will delegate to the macOS function

![image](https://github.com/flutter/flutter/assets/73608287/610a5474-4882-4819-a932-22e147a433ac)

I'm not sure if this is already available or it's just a simple PR or require a lot of changes in order to support it

**Comment by moffatman** [comment] 2024-03-28 18:21
I always run my app like this, I agree on all the benefits, especially plugins like video/webview.

1. `flutter build ios` from command line
2. Run app on "My Mac (Designed for iPad)" in Xcode
3. `flutter attach` from command line

Then I can hot reload/hot restart by pressing r / R in my terminal. Nothing automatic on save in VSCode or debugger. But I don't really bother with those anyways. Perhaps it is possible to "attach" from VSCode, but I've never tried.

If I remember right, the decision by Flutter top brass was not to add it as a "device" to run directly to avoid confusion (to be honest, it is quite a confusing feature, without proper official naming). See https://github.com/flutter/flutter/pull/84411.

Also this feature seems to be buggy from Apple. Sometimes the app freezes for a few seconds, I checked in Instruments, it has some hang inside UIKit in input event processing. Or also, after I upgraded to macOS 14.4, my app can't even launch any more, I have to temporarily change the bundle ID.

**Comment by stuartmorgan** [comment] 2024-03-28 19:55
Closing as a duplicate of https://github.com/flutter/flutter/issues/125741.

**Closed by stuartmorgan** 2024-03-28 19:55 UTC

**Comment by stuartmorgan** [comment] 2024-03-28 19:57
> and I'm having build issues all the time with CocoaPods

FYI, nothing changes about the build process when using this mode, so adding this device target would not help with any build issues.

**Comment by ellet0** [comment] 2024-03-28 20:18
> > and I'm having build issues all the time with CocoaPods
> 
> FYI, nothing changes about the build process when using this mode, so adding this device target would not help with any build issues.

The native code for the plugins on the macOS might be different, plus it did for me

I can't use firebase crashlytics on a new blank project using the macOS target
