### ISSUE TITLE
Flutter Deep linking [Android] was open new App when open notification in foreground

### ISSUE THREAD

**Issue by ayechan-maung** [flutter/flutter#106654] opened 2022-06-27 10:15 UTC
`<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="http" android:host="flutterbooksample.com" />
    <data android:scheme="https" />
</intent-filter>`

Deep-link should open the application and navigate to the page in the app was terminated however, it opens the foreground and background state also.

**Comment by exaby73** [comment] 2022-06-27 10:29
Hello @ayechan-maung. In Flutter, you need to handle the navigation yourself for deep linking. In fact, deep link only opens your app, and doesn't navigate anywhere. I suggest you look into the deep link library you're using, you you can find great documentation in the [`uni_links`](https://pub.dev/packages/uni_links) package. If you have any other questions, I do suggest you ask on a Q&A forum like StackOverflow.

Since this is not a bug with Flutter, I am closing this issue. If you disagree, please comment and we can reopen it.

**Closed by exaby73** 2022-06-27 10:29 UTC
Labels: in triage
