### ISSUE TITLE
Background problem issue buggy screen

### ISSUE THREAD

**Issue by ljbdelacruz** [flutter/flutter#52092] opened 2020-03-06 08:42 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```
![IMG_1385](https://user-images.githubusercontent.com/22063776/76066855-58bbf680-5fc9-11ea-994b-8de0b0b723df.PNG)

</details>

**Comment by TahaTesser** [comment] 2020-03-06 08:44
Hi @ljbdelacruz 

can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem

Thank you

**Comment by ljbdelacruz** [comment] 2020-03-07 08:39
Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.1 19B2106, locale en-PH)
    • Flutter version 1.12.13+hotfix.8 at /Users/fortunefaith/Desktop/projects/flutter/tools/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fortunefaith/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode11.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

**Comment by ljbdelacruz** [comment] 2020-03-07 08:40
this is how i displayed the BG image

return SafeArea(
      child:Container(
        decoration: BoxDecoration(
        image: DecorationImage(
          image: AssetImage("assets/images/bgimage.png"),
          fit: BoxFit.cover,
          ),
        ), 
          child: Scaffold(
          backgroundColor: Colors.transparent,
          body: Center( child: Viewer1Lottie(anim),)
          ,),
      )
    );

**Comment by TahaTesser** [comment] 2020-03-09 09:54
Hi @ljbdelacruz 

It's probably your asset image not a Flutter issue
Since i didn't have access to your asset image, here i replaced with network image 

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: SafeArea(
          child: Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            image: NetworkImage("https://i.imgur.com/nWHQd22.jpg"),
            fit: BoxFit.cover,
          ),
        ),
        child: Scaffold(
          backgroundColor: Colors.transparent,
          body: Center(
              // child: Viewer1Lottie(anim),
              ),
        ),
      )),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-03-09 09:54 UTC
Labels: in triage
