### ISSUE TITLE
Flutter not automatically changing the status bar icons to black on devices running iOS 13.0 in Dark Mode it only does so when Dark Mode on iOS 13 is turned off

### ISSUE THREAD

**Issue by Chimba123** [flutter/flutter#41067] opened 2019-09-22 22:47 UTC
I upgraded my iPhone X operating system(OS) from 12.4 to iOS 13.0 and I also updated my Xcode to version 11. I have noticed one puzzling thing, previously when loading my Flutter app on my iPhone X running iOS 12.4 then the status bar icons(network, wifi, battery, time) would automatically turn black to provide contrast from the grey `Cupertino Navigation Bar` and white `Material App Bar` widgets. But when I upgraded the OS on the actual device this automatic functionality is gone and the status icons are white and barely visible. It only does so when Dark Mode on the device is turned off.

How could we get the automatic functionality of status bar icons and text switching to black in Dark Mode on iOS 13?

**Comment by Mugen0** [comment] 2019-09-22 23:45
Turn off dark mode on your device and it will appear as before. Yet I don't know how to adapt if dark mode is on.

**Comment by Chimba123** [comment] 2019-09-22 23:50
@Mugen Thanks I actually lost my temper with it and yet such a simple fix

**Comment by Chimba123** [comment] 2019-09-22 23:51
@Mugen maybe you can open an issue for the Dark Mode.

**Comment by cetorres** [comment] 2019-09-23 16:27
Turning off dark mode on iOS 13 is not the solution. We should have a way to either detect dark mode and deal with the status bar color by ourselves or the framework could do it automatically. It should be an issue to be fixed.

**Comment by vanelizarov** [comment] 2019-09-27 09:50
Some time ago I've written a simple [plugin](https://github.com/vanelizarov/flutter_ios_dark_mode) for getting iOS 13 Dark Mode enabled state
Basically it can be a temporary workaround for this problem

**Comment by Chimba123** [comment] 2019-09-28 19:29
@vanelizarov could you please illustrate a comprehensive example on how to use your plugin?

**Comment by Mugen0** [comment] 2019-09-28 22:55
@vanelizarov I got an error with the plugin.
`fatal error: 'flutter_ios_dark_mode/flutter_ios_dark_mode-Swift.h' file not`

**Comment by vanelizarov** [comment] 2019-09-29 00:32
@Mugen0 your app needs to be scaffolded with Swift language because plugin is written in Swift

**Comment by vanelizarov** [comment] 2019-09-29 00:49
@Chimba123 sorry for the false alarm, I've tried to write an example app and figured out that my plugin can help, but not exactly in the way I've expected. For example you can subscribe to `onDarkModeStateChanged` via `StreamBuilder` and change app brightness dynamically. I know that it's not an accurate solution for our problem, but it's better than nothing. Here's the minimal runnable example:
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter_ios_dark_mode/flutter_ios_dark_mode.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<bool>(
      stream: FlutterIosDarkMode().onDarkModeStateChanged,
      initialData: false,
      builder: (context, snapshot) {
        return CupertinoApp(
          debugShowCheckedModeBanner: false,
          theme: CupertinoThemeData(
            brightness: snapshot.data ? Brightness.dark : Brightness.light,
          ),
          home: Home(),
        );
      },
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(),
      child: Container(),
    );
  }
}
```

Unfortunately, if you set `barBackgroundColor` strictly to let's say white and then switch to dark mode - status bar items color stays white, even with the help of this plugin. So, the most correct solution I think will be to wait for Flutter team to fix this problem or try to fix it on our own

**Comment by LongCatIsLooong** [comment] 2019-10-03 21:16
On Xcode 11.2 beta & iOS 13.2, setting [`UIApplicatin.shared.statusBarStyle`](https://developer.apple.com/documentation/uikit/uiapplication/1622988-statusbarstyle) (which is also deprecated) seems to have stopped working. [`UIViewController.preferredStatusBarStyle`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621416-preferredstatusbarstyle) works fine.

**Comment by joaowd** [comment] 2019-10-09 11:44
Any news on this ?

**Comment by blackox626** [comment] 2019-10-14 03:36
## FlutterPlatformPlugin

```objc
- (void)setSystemChromeSystemUIOverlayStyle:(NSDictionary*)message {
  NSString* style = message[@"statusBarBrightness"];
  if (style == (id)[NSNull null])
    return;

  UIStatusBarStyle statusBarStyle;
  if ([style isEqualToString:@"Brightness.dark"])
    statusBarStyle = UIStatusBarStyleLightContent;
  else if ([style isEqualToString:@"Brightness.light"])
    statusBarStyle = UIStatusBarStyleDefault;
  else
    return;

  NSNumber* infoValue = [[NSBundle mainBundle]
      objectForInfoDictionaryKey:@"UIViewControllerBasedStatusBarAppearance"];
  Boolean delegateToViewController = (infoValue == nil || [infoValue boolValue]);

  if (delegateToViewController) {
    // This notification is respected by the iOS embedder
    [[NSNotificationCenter defaultCenter]
        postNotificationName:@(kOverlayStyleUpdateNotificationName)
                      object:nil
                    userInfo:@{@(kOverlayStyleUpdateNotificationKey) : @(statusBarStyle)}];
  } else {
    // Note: -[UIApplication setStatusBarStyle] is deprecated in iOS9
    // in favor of delegating to the view controller
    [[UIApplication sharedApplication] setStatusBarStyle:statusBarStyle];
  }
}
```

engine code  ，we can see  no  UIStatusBarStyleDarkContent 

delete  ‘UIViewControllerBasedStatusBarAppearance ’  from  info.plist  


add notification 

```objc
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(appStatusBar:) name:@"io.flutter.plugin.platform.SystemChromeOverlayNotificationName" object:nil];

- (void)appStatusBar:(id)notification {
    if (@available(iOS 13.0, *)) {
        [UIApplication sharedApplication].statusBarStyle = UIStatusBarStyleDarkContent;
    }
}
```

**Comment by jayjun** [comment] 2019-10-14 11:34
The problem is `SystemUiOverlayStyle.dark` sets the status bar style as `UIStatusBarStyleDefault`, which defaults to light text in Dark Mode.

I sent https://github.com/flutter/engine/pull/13119 to use `UIStatusBarStyleDarkContent` (iOS 13.0+) instead, which should fix this issue.

**Comment by Chimba123** [comment] 2019-10-14 11:54
@jayjun keep us posted

**Comment by vanelizarov** [comment] 2019-10-14 12:14
@blackox626 thanks for the idea, I've finally figured out how to temporarily fix fix this issue via native code, while we all are waiting for @jayjun's PR to be merged

1. Set `View controller based status bar appearance` in `Info.plist` to YES
1.1. (Optional) Set `Status bar style` option to whatever value you want to determine status bar color on app start
<img width="427" alt="Screen Shot 2019-10-14 at 15 05 57" src="https://user-images.githubusercontent.com/5096148/66750066-21bb3c00-ee94-11e9-893b-025560165da0.png">

2. Add this extension to `FlutterViewController` in separate file or below the `AppDelegate`:

```swift
let kOverlayStyleUpdateNotificationName = "io.flutter.plugin.platform.SystemChromeOverlayNotificationName"
let kOverlayStyleUpdateNotificationKey = "io.flutter.plugin.platform.SystemChromeOverlayNotificationKey"

extension FlutterViewController {
    private struct StatusBarStyleHolder {
        static var style: UIStatusBarStyle = .default
    }
    
    open override func viewDidLoad() {
        super.viewDidLoad()
        
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appStatusBar(notification:)),
            name: NSNotification.Name(kOverlayStyleUpdateNotificationName),
            object: nil
        )
    }

    open override var preferredStatusBarStyle: UIStatusBarStyle {
        return StatusBarStyleHolder.style
    }
    
    @objc private func appStatusBar(notification: NSNotification) {
        guard
            let info = notification.userInfo as? Dictionary<String, Any>,
            let statusBarStyleKey = info[kOverlayStyleUpdateNotificationKey] as? Int
        else {
            return
        }
        
        if #available(iOS 13.0, *) {
            StatusBarStyleHolder.style = statusBarStyleKey == 0 ? .darkContent : .lightContent
        } else {
            StatusBarStyleHolder.style = statusBarStyleKey == 0 ? .default : .lightContent
        }
        
        setNeedsStatusBarAppearanceUpdate()
    }
}
```

**Comment by Chimba123** [comment] 2019-10-15 20:22
@vanelizarov 

works thanks should I close the issue based on this temporary fix?

**Comment by LongCatIsLooong** [comment] 2019-10-15 20:32
@Chimba123 could you keep the issue open until a proper fix lands?

**Comment by vanelizarov** [comment] 2019-10-15 21:14
@Chimba123 I think that @LongCatIsLooong is right, we should close it when fix lands at least dev channel

**Comment by Chimba123** [comment] 2019-10-15 21:21
based on the temporal fixes  I think it's fit to close this issue. Thanks to all and happy coding with Flutter

**Comment by Chimba123** [comment] 2019-10-15 21:26
@LongCatIsLooong I think the temporal fix will carry us through unless something breaks again anyone can re-open the issue since Google is working on dark mode and a PR is on its way I am sure it will be addressed within the framework itself, when? I don't know but this works and I feel that's cool but if you feel otherwise it's okay you can re-open it

**Comment by jayjun** [comment] 2019-10-16 01:57
@Chimba123 https://github.com/flutter/flutter/issues/41067#issuecomment-541641738 is a temporary workaround, not a fix. Issues should be closed after fixes are merged, because my pull request is not guaranteed to be accepted.

**Comment by v7lin** [comment] 2019-10-16 05:02
Any news on this ?

**Comment by ToniTornado** [comment] 2019-10-18 10:13
I don't use Swift in my project... Does anyone have an ObjC version of the fix?

**Comment by loushou** [comment] 2019-10-22 15:59
@vanelizarov thanks for the extension code. this worked brilliantly! you rock man!

**Comment by horgag1** [comment] 2019-10-23 21:01
will this work for text as well. I'm using a Zendesk Api for chat (I don't have any control over the UI) that works fine except for iOS 13 where the Dark Mode is enabled and the text is coming out white on a white background..

**Comment by vanelizarov** [comment] 2019-10-23 22:46
@horgag1 if I correctly understand you, this fix is for status bar color, not for the plain textviews or other text representations. So you need to implement custom logic for changing text color when dark mode is enabled

**Comment by FineTillYouCameAlong** [comment] 2019-11-02 21:09
So how to explicitly set the text color to black or white on the status bar on iOS 13? Is there a way? No solution works and no one seems to care.

**Comment by ThiagoAM** [comment] 2019-11-29 10:22
Any news on this? Waiting for an official fix from the Flutter team!

**Comment by vanelizarov** [comment] 2019-12-10 19:14
Hello everyone again!
I need some help in Objective-C implementation of my temp fix. 

I've written UIViewController category, which contains almost the same logic as extension above. The problem is that I don't know how to hook into FlutterViewController to: 
1. Subscribe to dark mode notifications (method `setupStatusBarFix`, must be called after `[super viewDidLoad]` in view controller)
2. Override `- (UIStatusBarStyle *) preferredStatusBarStyle` (must return `fixedStatusBarStyle` static property value)

It would be great to have this temp fix for both languages while https://github.com/flutter/engine/pull/13119 is not merged and released. I'm not an Obj-C expert, so any help is welcome 🙂

Here's the source code for category:
```objc
//
//  UIViewController+StatusBarFix.h
//  objc_status_bar_fix
//
//  Created by vanya elizarov on 10.12.2019.
//  Copyright © 2019 vanya elizarov. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UIViewController (StatusBarFix)
+ (UIStatusBarStyle) fixedStatusBarStyle;
- (void) setupStatusBarFix;
@end
```

```objc
//
//  UIViewController+StatusBarFix.m
//  objc_status_bar_fix
//
//  Created by vanya elizarov on 10.12.2019.
//  Copyright © 2019 vanya elizarov. All rights reserved.
//

#import "UIViewController+StatusBarFix.h"

NSString* const kOverlayStyleUpdateNotificationName = @"io.flutter.plugin.platform.SystemChromeOverlayNotificationName";
NSString* const kOverlayStyleUpdateNotificationKey = @"io.flutter.plugin.platform.SystemChromeOverlayNotificationKey";

@implementation UIViewController (StatusBarFix)

static UIStatusBarStyle fixedStatusBarStyle = UIStatusBarStyleDefault;

+ (UIStatusBarStyle)fixedStatusBarStyle {
    return fixedStatusBarStyle;
}

- (void)setupStatusBarFix {
    [[NSNotificationCenter defaultCenter]
         addObserver:self
         selector:@selector(fixStatusBarAppearance:)
         name:kOverlayStyleUpdateNotificationName
         object:nil
    ];
}

- (void)fixStatusBarAppearance:(NSNotification *)notification {
    NSDictionary<NSString *, NSNumber *> *info = notification.userInfo;
    NSNumber *statusBarStyleKey = [info valueForKeyPath:kOverlayStyleUpdateNotificationKey];
    
    if (@available(iOS 13.0, *)) {
        fixedStatusBarStyle = statusBarStyleKey == 0 ? UIStatusBarStyleDarkContent : UIStatusBarStyleLightContent;
    } else {
        fixedStatusBarStyle = statusBarStyleKey == 0 ? UIStatusBarStyleDefault : UIStatusBarStyleLightContent;
    }
    
    [self setNeedsStatusBarAppearanceUpdate];
}
@end
```

**Comment by Chimba123** [comment] 2019-12-11 23:15
Hey guys does this solve the problem? (link below)

https://medium.com/flutter/announcing-flutter-1-12-what-a-year-22c256ba525d

there is claim in that article that dark mode is now supported can anyone
test and see?

**Comment by rserro** [comment] 2019-12-13 12:24
@Chimba123 I tried to use a light theme on Dark Mode and the status bar kept white (invisible over the light background). So it didn't work for me with 1.12.13+hotfix.5. But I haven't  gone further trying to make it work, so this should not be taken as a definitive "does not work" answer.

**Comment by LongCatIsLooong** [comment] 2019-12-13 18:11
FYI https://github.com/flutter/engine/pull/13119 is approved (thank you @jayjun!) but our infra has to be migrated to use xcode 11 first. We are still working on that. If all goes well we might be able to land the fix next week [or so](https://en.wikipedia.org/wiki/Hofstadter%27s_law).

**Comment by jaddoescad** [comment] 2019-12-19 04:41
Any news on if this fix has been applied?

**Comment by nodegin** [comment] 2019-12-27 18:25
Please fix this asap..

**Comment by iampawan** [comment] 2019-12-29 13:13
Waiting for it to get fixed soon.

**Comment by ZacharyEilers** [comment] 2020-01-05 02:04
Same. Still waiting for fix.

**Comment by atereshkov** [comment] 2020-01-05 11:43
Hm, almost 4 months of waiting..

**Comment by dotcink** [comment] 2020-01-06 13:02
> @blackox626 thanks for the idea, I've finally figured out how to temporarily fix this issue via native code, while we all are waiting for @jayjun's PR to be merged
> 
> 1. Set `View controller based status bar appearance` in `Info.plist` to YES
>    1.1. (Optional) Set `Status bar style` option to whatever value you want to determine status bar color on app start
> 
> <img alt="Screen Shot 2019-10-14 at 15 05 57" width="427" src="https://user-images.githubusercontent.com/5096148/66750066-21bb3c00-ee94-11e9-893b-025560165da0.png">
> 
> 1. Add this extension for `FlutterViewController` to separate file or below the `AppDelegate`:
> 
> ```swift
> let kOverlayStyleUpdateNotificationName = "io.flutter.plugin.platform.SystemChromeOverlayNotificationName"
> let kOverlayStyleUpdateNotificationKey = "io.flutter.plugin.platform.SystemChromeOverlayNotificationKey"
> 
> extension FlutterViewController {
>     private struct StatusBarStyleHolder {
>         static var style: UIStatusBarStyle = .default
>     }
>     
>     open override func viewDidLoad() {
>         super.viewDidLoad()
>         
>         NotificationCenter.default.addObserver(
>             self,
>             selector: #selector(appStatusBar(notification:)),
>             name: NSNotification.Name(kOverlayStyleUpdateNotificationName),
>             object: nil
>         )
>     }
> 
>     open override var preferredStatusBarStyle: UIStatusBarStyle {
>         return StatusBarStyleHolder.style
>     }
>     
>     @objc private func appStatusBar(notification: NSNotification) {
>         guard
>             let info = notification.userInfo as? Dictionary<String, Any>,
>             let statusBarStyleKey = info[kOverlayStyleUpdateNotificationKey] as? Int
>         else {
>             return
>         }
>         
>         if #available(iOS 13.0, *) {
>             StatusBarStyleHolder.style = statusBarStyleKey == 0 ? .darkContent : .lightContent
>         } else {
>             StatusBarStyleHolder.style = statusBarStyleKey == 0 ? .default : .lightContent
>         }
>         
>         setNeedsStatusBarAppearanceUpdate()
>     }
> }
> ```

This solves the status bar color problem, but results in another.
I cannot hide the status bar with `SystemChrome.setEnabledSystemUIOverlays([]);`.

**Comment by luscas** [comment] 2020-01-07 17:32
Change in **Info.plist**
```plist
<key>UIUserInterfaceStyle</key>
<string>Light</string>
<key>UIViewControllerBasedStatusBarAppearance</key>
<true/>
```

Changing status bar with
```dart
SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(statusBarBrightness: Brightness.light)
);
```

**Comment by 330676687** [comment] 2020-01-08 00:36
> ```plist
> UIViewControllerBasedStatusBarAppearance
> ```

nice!!

**Comment by 330676687** [comment] 2020-01-08 00:37
> Add line in **Info.plist**
> 
> ```plist
> <key>UIUserInterfaceStyle</key>
> <string>Light</string>
> <key>UIViewControllerBasedStatusBarAppearance</key>
> <true/>
> ```
> 
> And change status bar 👍
> 
> ```dart
> import 'package:flutter/services.dart';
> /// ...
> SystemChrome.setSystemUIOverlayStyle(
>       SystemUiOverlayStyle(statusBarBrightness: Brightness.light) // Or Brightness.dark
> );
> ```

nice!!!

**Comment by Csutkas** [comment] 2020-01-10 13:41
Thank you! 

For beginners like me:
Info.plist is under ios/Runner

**Comment by shorben07** [comment] 2020-01-11 10:13
One more possible workaround:
1. Set View controller-based status bar appearance in Info.plist to YES
2. Create a subclass of the flutter view controller
```
class CustomFlutterViewController: FlutterViewController {
    
    override open var preferredStatusBarStyle: UIStatusBarStyle {
        let value = super.preferredStatusBarStyle
        if #available(iOS 13.0, *) {
            return value == .default ? .darkContent : value
        } else {
            return value
        }
    }
} 
```

**Comment by gabryelferreira** [comment] 2020-01-13 00:28
> Add line in **Info.plist**
> 
> ```plist
> <key>UIUserInterfaceStyle</key>
> <string>Light</string>
> <key>UIViewControllerBasedStatusBarAppearance</key>
> <true/>
> ```
> 
> And change status bar 👍
> 
> ```dart
> import 'package:flutter/services.dart';
> /// ...
> SystemChrome.setSystemUIOverlayStyle(
>       SystemUiOverlayStyle(statusBarBrightness: Brightness.light) // Or Brightness.dark
> );
> ```

Works like a charm. Tks!

**Comment by gabryelferreira** [comment] 2020-01-13 00:28
@330676687 Works like a charm. Tks!

**Comment by LongCatIsLooong** [comment] 2020-01-16 18:24
Seems to be working on master now. Closing.

**Closed by LongCatIsLooong** 2020-01-16 18:24 UTC
Labels: customer: crowd, engine, f: cupertino, framework, ⌺‬ platform-ios

**Comment by edwardez** [comment] 2020-01-16 18:33
Will a hotfix be issued on 1.12.13 for this fix? Or this won’t be merged to stable until next major release?

**Comment by LongCatIsLooong** [comment] 2020-01-16 19:05
@edwardez not that I know of. To quote the [wiki](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release):
> __Will a particular bug fix be provided in a hotfix release?__
Almost certainly not. We only hotfix the most egregious bugs (e.g. "nobody can build on iOS any more"), and even then we're more likely to just release a new build.
>
> If you really need a particular patch and it's a fix to the flutter/flutter repository, you should feel free to create a Flutter branch yourself on your development machine and cherry-pick the fix you want onto that branch. Flutter is distributed as a git repository and all of git's tools are available to you. If you need a particular patch that's from the flutter/engine repository or one of our dependencies (e.g. Dart or Skia), you could build your own engine but it's probably easier to just wait until the next release. On average, the next dev release is about a day away and the next beta release is about two weeks away.

Switching to the dev channel or the beta channel could also be an option.

**Comment by edwardez** [comment] 2020-01-16 19:14
> @edwardez not that I know of. To quote the [wiki](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release):
> 
> > **Will a particular bug fix be provided in a hotfix release?**
> > Almost certainly not. We only hotfix the most egregious bugs (e.g. "nobody can build on iOS any more"), and even then we're more likely to just release a new build.
> > If you really need a particular patch and it's a fix to the flutter/flutter repository, you should feel free to create a Flutter branch yourself on your development machine and cherry-pick the fix you want onto that branch. Flutter is distributed as a git repository and all of git's tools are available to you. If you need a particular patch that's from the flutter/engine repository or one of our dependencies (e.g. Dart or Skia), you could build your own engine but it's probably easier to just wait until the next release. On average, the next dev release is about a day away and the next beta release is about two weeks away.
> 
> Switching to the dev channel or the beta channel could also be an option.

Make sense, thanks for the detailed explanation.

**Comment by mono0926** [comment] 2020-01-16 23:33
> Seems to be working on master now. Closing.

Fixed by https://github.com/flutter/engine/pull/13119

**Comment by Chimba123** [comment] 2020-01-16 23:52
@mono0926 is it safe for us to use the Master Channel in production? Our concern is a production ready solution, not a developer-only solution.

**Comment by Chimba123** [comment] 2020-01-16 23:58
@mono0926 if we can't use the master channel to deploy our final Apps to the App store as a well-finished product then I'd advise you to re-open the issue till it is properly addressed on the stable channel

**Comment by BassamxMednini** [comment] 2020-02-08 21:36
It works fine in the simulator, but on a real device it doesn't work...

**Comment by atereshkov** [comment] 2020-02-10 18:13
My app freezes when I run Flutter from master channel. I had to switch to stable version where's no fix exists for this issue. News, guys?

**Comment by eugene-kalaganov** [comment] 2020-02-12 08:13
it doesn't works even on simulator
Master channel

**Comment by minikin** [comment] 2020-02-12 08:16
btw: @eugene-kalaganov It's a bad practice to fully rely on how things work in a simulator (iOS).

**Comment by eugene-kalaganov** [comment] 2020-02-12 08:18
> btw: @eugene-kalaganov It's a bad practice to fully rely on how things work in a simulator (iOS).

I forget to ask you what is bad or good practice

**Comment by woutergoossens** [comment] 2020-02-12 22:38
How can we have this fix in our apps?

**Comment by LongCatIsLooong** [comment] 2020-02-14 21:53
@atereshkov could you create a new issue, if there isn't one already? That sounds like a severe problem. 

also the dev channel and the beta channel should have the fix now if you don't want to patch and build the engine manually.

**Comment by lukepighetti** [comment] 2020-02-21 16:44
> Add line in **Info.plist**
> 
> ```plist
> <key>UIUserInterfaceStyle</key>
> <string>Light</string>
> <key>UIViewControllerBasedStatusBarAppearance</key>
> <true/>
> ```
> 
> And change status bar 👍
> 
> ```dart
> import 'package:flutter/services.dart';
> /// ...
> SystemChrome.setSystemUIOverlayStyle(
>       SystemUiOverlayStyle(statusBarBrightness: Brightness.light) // Or Brightness.dark
> );
> ```

I'm unable to control the status bar brightness on iOS using this method. I'm on Flutter `1.15.3`. Is there another step required that isn't documented?

**Comment by ilweonair** [comment] 2020-02-24 10:41
@atereshkov are there any news about this issue? Could you create a new issue?

**Comment by atereshkov** [comment] 2020-02-24 13:36
@ilweonair I'll check it one more time today and address if it's still an issue

**Comment by AndroidNils** [comment] 2020-02-25 06:19
For me this issue is fixed in `flutter beta` and everything is working fine 👍

**Comment by ilweonair** [comment] 2020-02-25 15:34
Obviously, I think that it isn’t possible to work with a beta version in a
production environment

Il giorno mar 25 feb 2020 alle 07:19 Nils Reichardt <
notifications@github.com> ha scritto:

**Comment by lukepighetti** [comment] 2020-02-28 01:27
@ilweonair Depends on your pipelining needs. We typically deploy from `dev`

**Comment by diepnguyen137** [comment] 2020-03-16 14:09
> Add line in **Info.plist**
> 
> ```plist
> <key>UIUserInterfaceStyle</key>
> <string>Light</string>
> <key>UIViewControllerBasedStatusBarAppearance</key>
> <true/>
> ```
> 
> And change status bar 👍
> 
> ```dart
> import 'package:flutter/services.dart';
> /// ...
> SystemChrome.setSystemUIOverlayStyle(
>       SystemUiOverlayStyle(statusBarBrightness: Brightness.light) // Or Brightness.dark
> );
> ```

work like charm <3
