### ISSUE TITLE
error when navigator push from root path page

### ISSUE THREAD

**Issue by gurjeetsinghsainig** [flutter/flutter#95320] opened 2021-12-15 07:34 UTC
Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4595 pos 12: '_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      NavigatorState._pushEntry (package:flutter/src/widgets/navigator.dart:4595:12)
#3      NavigatorState.push (package:flutter/src/widgets/navigator.dart:4511:5)
#4      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:4243:12)
#5      Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:1742:34)
#6      _MyAccountPage._openEditProfile (package:jualary/ui/myaccount.dart:625:15)
#7      _MyAccountPage.build.<anonymous closure> (package:jualary/ui/myaccount.dart:198:31)
#8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)

**Comment by mamuseferha** [comment] 2021-12-15 08:56
Hi @gurjeetsinghsainig 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by mamuseferha** [comment] 2021-12-16 08:11
duplicate of https://github.com/flutter/flutter/issues/95377

**Closed** 2021-12-16 08:11 UTC
Labels: r: invalid
