### ISSUE TITLE
 ModalRoute.of(context).settings.name return as Widget in release build version 1.17.0+

### ISSUE THREAD

**Issue by amit-android-dev** [flutter/flutter#58066] opened 2020-05-27 04:33 UTC
I am trying to get my current screen name by using settings.name

`ModalRoute.of(context).settings.name`

 is return default by string. While I'm testing build in debug mode it's working fine. When I'm doing release build it converted into Widget. 

`var currentScreen = ModalRoute.of(context).settings.name.toString();`

currentScreen return as a string in Release build flutter version 1.12.9 (working case)
currentScreen return as a string in debug build flutter version 1.17.0+ (working case)
currentScreen return as a widget in Release build flutter version 1.17.0+ (Not working case)

**Comment by helinanever** [comment] 2020-05-27 12:29
Hi, @amit-android-dev

Can you please share the details of your code snippet to reproduce the issue including flutter doctor?
I got similarly closed issues to consider looking #53361  #50147 #37878

**Comment by amit-android-dev** [comment] 2020-05-27 12:44
There is no major snippet code for this. It working fine at debug mode, but once I'm prepare release build it automatically convert my "currentScreen" to Widget, i don't know why?
```

 var currentScreen = ModalRoute.of(context).settings.name.toString();
          if (currentScreen != "NotificationScreen") {
            NavigationUtils.push(context, routeNotification);
         }

```

**Comment by iapicca** [comment] 2020-05-27 12:56
Hi @amit-android-dev 
I've just tested this [code sample](https://dartpad.dev/59ac3f2c13f0fee3ea437822e80a6d63)
with the latest stable

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/nevercode/development/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 8 • D5F70F31-B488-4454-9539-320B5551D92A • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>

both in debug and [release](https://drive.google.com/file/d/1DvEDbPq1djqWWOi7m_7zG-ctqO3791Eg/view?usp=sharing)
seems to wrk as intended;
if the code sample doesn't represent the issue you are describing 
please provide your `flutter doctor -v`, 
and a minimal complete reproducible code sample
Thank you

**Comment by amit-android-dev** [comment] 2020-05-27 15:19
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.2 19C57, locale en-IN)
    • Flutter version 1.17.1 at /Users/amit.prajapati/Documents/android/flutter/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/amit.prajapati/Documents/android/sdk/
    • Platform android-R, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/amit.prajapati/Documents/android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • Redmi 7A • 3967d3829906 • android-arm   • Android 9 (API 28)
    • Mi A1    • 7e429b020404 • android-arm64 • Android 9 (API 28)

**Comment by TahaTesser** [comment] 2020-05-28 09:38
Hi @amit-android-dev 

<details> 
<summary>Code Sample</summary> 

``` 
// import 'package:flutter/material.dart';

// void main() => runApp(MyApp());

// class MyApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Material App',
//       theme: ThemeData.dark(),
//       home: Home(),
//     );
//   }
// }

// class Home extends StatefulWidget {
//   @override
//   _HomeState createState() => _HomeState();
// }

// class _HomeState extends State<Home> with SingleTickerProviderStateMixin {
//   AnimationController _controller;

//   @override
//   void initState() {
//     super.initState();

//     _controller = new AnimationController(
//         lowerBound: -1.0,
//         upperBound: 1.0,
//         duration: new Duration(seconds: 2),
//         vsync: this)
//       ..addListener(() {
//         this.setState(() {});
//       });

//     _controller.addStatusListener((status) {
//       if (status == AnimationStatus.dismissed) {
//         print('dimissed');
//       }
//     });

//     _controller.forward(from: -1.0);
//   }

//   @override
//   Widget build(BuildContext context) {
//     var currentScreen = ModalRoute.of(context).settings.name.toString();
//     print(currentScreen);
//     if (currentScreen != "NotificationScreen") {}
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Material App Bar'),
//       ),
//       body: RaisedButton(onPressed: () {
//         print('raised');
//       }),
//       floatingActionButton: FloatingActionButton(
//         child: Icon(Icons.add),
//         onPressed: () {
//           print('after change test');
//         },
//       ),
//     );
//   }
// }

import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Named Routes Demo',
    // Start the app with the "/" named route. In this case, the app starts
    // on the FirstScreen widget.
    initialRoute: '/',
    routes: {
      // When navigating to the "/" route, build the FirstScreen widget.
      '/': (context) => FirstScreen(),
      // When navigating to the "/second" route, build the SecondScreen widget.
      '/second': (context) => SecondScreen(),
    },
  ));
}

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var currentScreen = ModalRoute.of(context).settings.name.toString();
    print(currentScreen);
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Launch screen'),
          onPressed: () {
            // Navigate to the second screen using a named route.
            Navigator.pushNamed(context, '/second');
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var currentScreen = ModalRoute.of(context).settings.name.toString();
    print(currentScreen);
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            // Navigate back to the first screen by popping the current route
            // off the stack.
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}

``` 

</details> 

```
✓ Built build/app/outputs/apk/release/app-release.apk (6.2MB).
Installing build/app/outputs/apk/app.apk...                         3.3s

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (25468): /
I/flutter (25468): /second
I/flutter (25468): /second
I/flutter (25468): /second

```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.17.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • Taha’s iPhone • 00008020-001059882212002E            • ios • iOS 13.5
    • iPhone 11     • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)

• No issues found!
``` 

</details> 

it does return string, i am not sure what do you mean by return widget, can you please `flutter run --release` with print using code sample i have provided

Thank you

**Comment by amit-android-dev** [comment] 2020-05-28 09:46
While I'm run my app by the android studio on everything working fine as you provided. However, I'm preparing to release build somehow it stops working.

 var currentScreen = ModalRoute.of(context).settings.name.toString();
          if (currentScreen != "NotificationScreen") {
            NavigationUtils.push(context, routeNotification);
         }

In debug mode while I'm run my app by android studio, I'm performing on toast and it returns "currentScreen" as string "NotificationScreen" so my condition matches perfect and working everything fine.


In Release build "currentScreen" is return me widget in that string. I don't know what happens in between prearpe release build and it stops working my condition not match because "currentScreen" return widget so.

**Comment by iapicca** [comment] 2020-05-29 08:01
Hi @amit-android-dev 
just tested the code [above](https://github.com/flutter/flutter/issues/58066#issuecomment-634641170) in release mode
everything seems to work as intended;
for the issue to be workable it needs to be reproducible
please provide **runnable** minimal code sample of your implementation
Thank you

**Comment by amit-android-dev** [comment] 2020-05-29 08:31
@iapicca Thanks for your response. I need some more time to prepare a demo for this, the case actually I'm facing issues in my current live project and I'm not able to share those things. so I have to prepare demo for it, it would be great if you close or hold this issue for now.

**Comment by TahaTesser** [comment] 2020-07-01 10:22
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-01 10:22 UTC
Labels: in triage, waiting for customer response

**Comment by jonataslaw** [comment] 2020-07-01 15:51
similar https://github.com/flutter/flutter/issues/60075
