### ISSUE TITLE
BottomNavigationBar breaks when increasing number of items it contains

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#14466] opened 2018-02-05 18:56 UTC
I believe that the cause is that the bar's state allocates animation controllers for each item when the state is first constructed, but it doesn't create new controllers when the state updates with more items.

## Steps to Reproduce

Create a nav bar with 3 items.

Increase the number of items to 4.

```
RangeError(index): invalid value: not in range 0..2, inclusive: 3.
```

## Logs
I/flutter (27323): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (27323): The following RangeError was thrown building BottomNavigationBar(dirty, state:
I/flutter (27323): _BottomNavigationBarState#68e58(tickers: tracking 3 tickers)):
I/flutter (27323): RangeError (index): Invalid value: Not in range 0..2, inclusive: 3
I/flutter (27323): 
I/flutter (27323): When the exception was thrown, this was the stack:
I/flutter (27323): #0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)
I/flutter (27323): #1      _BottomNavigationBarState._createTiles (package:flutter/src/material/bottom_navigation_bar.dart:411:26)
I/flutter (27323): #2      _BottomNavigationBarState.build (package:flutter/src/material/bottom_navigation_bar.dart:477:45)
I/flutter (27323): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3690:27)
I/flutter (27323): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3602:15)
I/flutter (27323): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
I/flutter (27323): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
I/flutter (27323): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
I/flutter (27323): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #31     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
I/flutter (27323): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
I/flutter (27323): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #45     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2210:33)
I/flutter (27323): #58     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (27323): #59     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (27323): #60     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (27323): #61     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (27323): #62     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (27323): #63     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter (27323): #64     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter (27323): ════════════════════════════════════════════════════════════════════════════════════════════════════

## Doctor
Version of Flutter is the current g3 version.

**Comment by tfzxyinhao** [comment] 2018-03-27 12:28
try to call `setState` trigger rebuild

**Comment by teg-danger** [comment] 2018-04-06 16:44
i have the same issue

**Comment by hmkrivoj** [comment] 2018-04-25 18:31
I get the same error when creating a BottomNavigationBar with 'items' being a list of four BottomNavigationBarItems.

**Comment by AlexandreRoba** [comment] 2018-05-10 06:34
I have the same error with three items.

**Comment by wypbusy** [comment] 2018-05-18 06:43
Same error with four items in hot reload. A full restart solved.

**Comment by HansMuller** [comment] 2018-05-25 00:32
Duplicate of #10322

**Closed** 2018-07-09 23:47 UTC
Labels: f: material design, severe: crash
