### ISSUE TITLE
[tool_crash] ExistingDartDevelopmentServiceException

### ISSUE THREAD

**Issue by Yunush1** [flutter/flutter#149313] opened 2024-05-30 11:22 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ExistingDartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:155:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:166:12)
<asynchronous suspension>
#3      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:511:7)
<asynchronous suspension>
#4      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:238:21)
<asynchronous suspension>
#5      Dwds.debugConnection (package:dwds/dart_web_debug_service.dart:58:30)
<asynchronous suspension>
#6      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:801:15)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.22635.3500], locale en-US)
    [32m•[39m Flutter version 3.22.1 on channel stable at C:\Users\Gamer\Downloads\flutter_windows_3.22.1-stable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision a14f74ff3a (8 days ago), 2024-05-22 11:08:21 -0500
    [32m•[39m Engine revision 55eae6864b
    [32m•[39m Dart version 3.4.1
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\Gamer\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2023.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[32m[✓][39m VS Code (version 1.89.1)
    [32m•[39m VS Code at C:\Users\Gamer\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.90.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22635.3500]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.78
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.24

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: a14f74ff3a1cbd521163c5f03d68113d50af93d3

**Comment by huycozy** [comment] 2024-05-30 11:46
Closing this as a duplicate of https://github.com/flutter/flutter/issues/135552.

**Closed by huycozy** 2024-05-30 11:46 UTC
Labels: in triage
