### ISSUE TITLE
[Proposal] CupertinoDatePicker with year only.

### ISSUE THREAD

**Issue by maplepam** [flutter/flutter#146194] opened 2024-04-03 11:22 UTC
### Use case

Looking at the cupertino date picker [flutter/packages/flutter/lib/src/cupertino/date_picker.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/date_picker.dart) there isn't a way to have just a year like so:
<img width="380" alt="image" src="https://github.com/flutter/flutter/assets/4180865/132d5e16-847b-4672-93f9-ff2604589310">

### Proposal

I propose adding a new CupertinoDatePickerMode to support having just a year and also a way to reverse or display the year selection in descending order like so:

<img width="274" alt="image" src="https://github.com/flutter/flutter/assets/4180865/9ee12c32-a568-4a65-a60b-94051c7d5191">

**Comment by darshankawar** [comment] 2024-04-03 12:58
Closing as duplicate of https://github.com/flutter/flutter/issues/139697

**Closed by darshankawar** 2024-04-03 12:58 UTC
Labels: in triage
