### ISSUE TITLE
Desktop app resizes on switching monitor

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#46096] opened 2019-12-04 18:09 UTC
Moving my app from my primary to secondary monitor results in a pixel density change. Flutter does not seem to repaint the window, so after moving to the secondary window, only the bottom-right hand corner of the image paints. 

Primary 
<img width="712" alt="Screen Shot 2019-12-04 at 10 05 25 AM" src="https://user-images.githubusercontent.com/2319867/70168552-f677f080-167d-11ea-84e6-2bec3ba0bd0d.png">

Secondary
![Screen Shot 2019-12-04 at 10 05 33 AM](https://user-images.githubusercontent.com/2319867/70168565-fbd53b00-167d-11ea-94e7-2ad97cf4c275.png)

**Comment by stuartmorgan** [comment] 2019-12-04 19:15
Duplicate of #35095

If this was with today's master we should reopen that issue

**Closed by stuartmorgan** 2019-12-04 19:15 UTC
Labels: a: desktop, engine, ⌘‬ platform-mac

**Comment by timsneath** [comment] 2019-12-04 21:09
Confirm fixed on `v1.12.17-pre.72`. Thanks, @stuartmorgan!
