### ISSUE TITLE
[WEB] flutter stop execution when undefined returned instead of a promise.

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#97082] opened 2022-01-23 03:01 UTC
## Steps to Reproduce

1. clone my plugin repo: https://github.com/matanshukry/flutter_google_places_sdk
2. in `flutter_google_places_sdk/example/lib/main.dart` set value to the api key, e.g. `const API_KEY = 'DummyKeyValue';`
3. Run the example
4. Add text to the Query (e.g. "bbb")
5. Click on 'Predict' button

**Expected results:**
The flow should continue and an error would be displayed in the UI.
The line where the flow stops is: https://github.com/matanshukry/flutter_google_places_sdk/blob/master/flutter_google_places_sdk_web/lib/flutter_google_places_sdk_web.dart#L112

I tried various ways to catch the errors:
* Changing the return value of `getPlacePredictions` from `Object` to `Object?` and then check for undefined/null. Looks like it still has a value (at least from flutter pov).
* wrapping the `_svcAutoComplete!.getPlacePredictions` method in a try-catch
* wrapping the `promiseToFuture(prom)` in a try-catch
* wrapping the `await value` (separated from the `promiseToFuture` call) in a try-catch
* adding `.then` with `onError` handler to the value returned from `promiseToFuture`.

When trying to run the method locally in chrome, through the console - I get back `undefined`. That makes me think the first thing I tried, checking for null, should work. However - it does not.

Note: you can see teh different results by skipping step 2.

**Actual results:**
Execution is stopped.

From the UI perspective, button is still being held (setState that will make it enabled again isn't running).

<details>
<summary>Code sample</summary>
Provided as github repo in reproducble steps above.

</details>

<details>
  <summary>Logs</summary>

There isn't any.
The only error that shows up is the one coming from the google maps api:

```
[  +70 ms] Google Maps JavaScript API error: InvalidKeyMapError
           https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error
```

```
No issues found! (ran in 4.8s)
```

```
$ flutter doctor -v
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
    • Flutter version 2.8.0 at C:\Flutter\SDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (6 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = C:\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.63.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.69

• No issues found!

```

</details>

**Comment by matanshukry** [comment] 2022-01-25 11:41
@maheshmnj sorry, I forgot to write "Click on 'Predict' button". Added it now.
Added it there but also note that if you don't do step 2 (changing the api key to "dummy value") you can see what is the expected result (as written)

**Comment by maheshmnj** [comment] 2022-01-25 13:39
@matanshukry  I see that `hasContent` is always false when I click predict so the control always returns from line 213

>   if (!hasContent) {
      return;
    }
    
could you please recheck the code, let me know if I am missing anything. Clicking predict I don't see any result nor any logs in the console.

**Comment by matanshukry** [comment] 2022-01-25 14:10
@maheshmnj sorry again, need to add text to the query. Updated steps as well

**Comment by maheshmnj** [comment] 2022-01-26 05:29
@matanshukry I don't see any error neither in chrome nor in vscode console. 

> The flow should continue and an error would be displayed in the UI.

Could you please explain a bit in terms of code which flow stops and what are you expecting when you hit predict?

https://user-images.githubusercontent.com/31410839/151108733-6ac2a830-02d2-4eac-8e11-3aa871b132ad.mov

**Comment by matanshukry** [comment] 2022-01-26 09:44
@maheshmnj you didn' follow step 2 correctly :)

If you got back results - it means you put in the correct key.
In step 2 I've written to put a `DummyKeyValue` - it wasn't as a palceholder for a real key.

The issue of when the flow stops is happening when the key is incorrect (but not null)

**Comment by matanshukry** [comment] 2022-01-26 09:47
Attached screenshot of what happens when the key is incorrect but not null:

p.s.
in the image you see lots of prints (e.g. "doInit2" and "Step #2.05") - those are things not in the example that i tried to track down the issue. you'll see though the the button is stuck on "disabled", and the "InvalidKeyMapError" in the console

![image](https://user-images.githubusercontent.com/5613042/151140392-7558a81a-9528-4d6e-aa14-4478fb7bcf99.png)

**Comment by maheshmnj** [comment] 2022-01-26 13:25
> In step 2 I've written to put a DummyKeyValue - it wasn't as a palceholder for a real key.

> The issue of when the flow stops is happening when the key is incorrect (but not null)

Thanks for the info @matanshukry, that makes it clear now. 

When an incorrect/ or empty api key is passed in the example app, the exception is not getting caught in the try-catch block, and the control is abruptly lost as a result the button remains disabled (expected to be enabled on catching the exception). This is reproducible on `stable 2.8.1` and I could not verify on master the project needs to be migrated to v2 of Android Embedding to run it.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.504, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.504 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 94d9b02deb (9 hours ago), 2022-01-25 22:00:07 -0600
    • Engine revision 54e1f3f4bb
    • Dart version 2.17.0 (build 2.17.0-54.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


<details>
<summary>logs</summary>

```
Restarted application in 320ms.
FlutterGooglePlacesSdk::call error: TypeError: Cannot read properties of undefined (reading 'then')
caught error
TypeError: Cannot read properties of undefined (reading 'then')
    at Object.promiseToFuture (http://localhost:59215/dart_sdk.js:62138:15)
at flutter_google_places_sdk_web.FlutterGooglePlacesSdkWebPlugin.new.findAutocompletePredictions (http://localhost:59215/packages/flutter_google_places_sdk_web/flutter_google_places_sdk_web.dart.lib.js:328:114)
    at findAutocompletePredictions.next (<anonymous>)
    at http://localhost:59215/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:59215/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:59215/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:59215/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:59215/dart_sdk.js:35589:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59215/dart_sdk.js:35318:27)
    at Object._microtaskLoop (http://localhost:59215/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:59215/dart_sdk.js:40336:13)
    at http://localhost:59215/dart_sdk.js:35811:9

```
</details>

**Comment by maheshmnj** [comment] 2022-01-27 12:43
What I meant is when I ran your application on the latest master channel the app failed to build with this error

```console
mahesh@Maheshs-MacBook-Air-M1 example % flutterm run -d chrome
Running "flutter pub get" in example...                             3.4s
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `flutter_google_places_sdk_android` requires your app to be migrated to the Android embedding v2. Follow the steps on
https://flutter.dev/go/android-project-migration and re-run this command.
```

**Comment by annagrin** [comment] 2022-01-27 19:49
[dart rotation] Opened dartdevc bug to investigate: https://github.com/dart-lang/sdk/issues/48239

**Comment by matanshukry** [comment] 2022-01-29 08:05
> What I meant is when I ran your application on the latest master channel the app failed to build with this error
> 
> ```
> mahesh@Maheshs-MacBook-Air-M1 example % flutterm run -d chrome
> Running "flutter pub get" in example...                             3.4s
> This app is using a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
> Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
> The plugin `flutter_google_places_sdk_android` requires your app to be migrated to the Android embedding v2. Follow the steps on
> https://flutter.dev/go/android-project-migration and re-run this command.
> ```
> 
> flutter doctor
> 
> ```
> [✓] Flutter (Channel master, 2.10.0-1.0.pre.307, on macOS 12.1 21C52 darwin-arm, locale en-GB)
>     • Flutter version 2.10.0-1.0.pre.307 at /Users/mahesh/Documents/flutter_master
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision b7424c619c (11 hours ago), 2022-01-26 17:25:45 -0800
>     • Engine revision c248c6e38e
>     • Dart version 2.17.0 (build 2.17.0-63.0.dev)
>     • DevTools version 2.10.0-dev.1
> ```

Pushed a new commit that should fix that, if it matters.

**Comment by nshahan** [comment] 2022-01-31 23:15
@matanshukry My suspicion is that if the value passed to `promissToFuture()` is `undefined` there will be an error but it might be on an async thread that we are not propagating correctly. I'd like to confirm if that is true or not.

> When trying to run the method locally in chrome, through the console - I get back undefined. That makes me think the first thing I tried, checking for null, should work. However - it does not.

I have some questions regarding this observation:
- Using chrome devtools, can you set a breakpoint and inspect the value you get back from the API before calling `promiseToFuture()`. What is it?
- Can you call the API with the same input arguments from the console when stopped at a breakpoint and get the same result?
- Any reason why you would expect the value to be different (undefined vs some value)?

Failing that, could you help us with a more bare bones reproduction? I'm not totally sure how to reproduce the issue you are experiencing.

**Comment by nshahan** [comment] 2022-03-01 01:07
@matanshukry 
Thanks for helping me out on this more. I think we definitely have an async timing issue on our hands here. By trying again and again I have finally been able to reproduce the issue you described but only a few times so far. Usually I see errors printing in the application after I click the "Predict" button.

<img width="824" alt="Screen Shot 2022-02-28 at 5 05 00 PM" src="https://user-images.githubusercontent.com/2498387/156085098-082085bd-5d87-43e8-8e6b-6abbce7a18ea.png">


A couple more questions: 

- Should I focus on the example in `flutter_google_places_sdk/example`? What is the difference with `flutter_google_places_sdk_web/example`?
- I noticed that in your paste from flutter doctor you are using flutter 2.8. Have you been able to reproduce this issue in the current stable release v2.10? 
- It looks like this issue exists in release mode as well. Can you confirm with running `flutter run -d chrome --release`?

**Comment by matanshukry** [comment] 2022-03-01 10:25
@nshahan not sure why you can't reproduce it constantly, but for me it seems to be 100% of the time.
To yours points:
* One example is more "advance" than the others, but for this case it shouldn't matter. Using the web example should just make it easier, but if you can't get one to work just use the other.
* Both. There was an issue with my impl that prevented initially running the example on release 2.10. I pushed a fix to that though, and once that was done you can run it against flutter 2.10, where the isuse reproduce as well.
* I ran it in release mode as well and yes, it happens there as well

**Comment by nshahan** [comment] 2022-03-03 01:48
>@nshahan not sure why you can't reproduce it constantly, but for me it seems to be 100% of the time.

It turns out that was user error on my part. I'm able to reliably reproduce it now and I have a smaller reproduction that shows the same problem.

@matanshukry 
What I am seeing is that there is an error that is thrown when the script element that contains the google maps .js file is added to the page. I tried writing straight JS and I see what looks like similar behavior where the errors that appear during the initial evaluation of the script don't get caught in the try catch because they are executing in a different context.

flutter_google_places_sdk_web/lib/flutter_google_places_sdk_web.dart
```dart
body.append(html.ScriptElement()
        ..id = _SCRIPT_ID
        ..src =
            'https://maps.googleapis.com/maps/api/js?key=${apiKey}&libraries=places&callback=initMap'
        ..async = true
        ..type = 'application/javascript');
```

I have some ideas for alternative implementations on your side:
- It looks like you are providing a callback, when is it called? 
- Do they provide you hooks for a callback to be called in the event there are errors? 
- Can you load the authentication information separately after the script is loaded on the page?

**Comment by matanshukry** [comment] 2022-03-03 02:34
> * It looks like you are providing a callback, when is it called?

Due to the error, it is never called. Otherwise it's called when the map is initialized, which is quite early in the life-cycle of the "web app", but I can't be more precise than that.

> * Do they provide you hooks for a callback to be called in the event there are errors?

Nope. But you get back a promise, which by it self contains error handling (same as future in Dart). That together with wrapping the call with try-catch should be enough.

> * Can you load the authentication information separately after the script is loaded on the page?

What authentication information are you talking about?
If you're talking about the `apiKey` then no - it's part of the url, as you can see.

@nshahan

**Comment by nshahan** [comment] 2022-03-08 00:01
@matanshukry 

> Due to the error, it is never called. Otherwise it's called when the map is initialized, which is quite early in the life-cycle of the "web app", but I can't be more precise than that.

If I set a breakpoint inside `_doInit()` (which I believe is the callback) I see it being called before the error appears.

> Nope. But you get back a promise, which by it self contains error handling (same as future in Dart). That together with wrapping the call with try-catch should be enough.

Looking closer at the code that makes the error appear in the console I think this is the issue. The message comes from line 75 of the maps API script. It's minified but buried in that line is the offending code:

```javascript
_.Sa.console.error.apply(_.Sa.console,_.na(a))
```

which if you set a breakpoint and evaluate these pieces it is essentially:

```javascript
window.console.error.apply(window.console, ['Google Maps JavaScript API error: InvalidKeyMapErr…n/javascript/error-messages#invalid-key-map-error'])
```

No error is being thrown that you can catch, it is simply being printed to the console.

> What authentication information are you talking about?
If you're talking about the apiKey then no - it's part of the url, as you can see.

I was just curious if there was any other way to use this library. Some way to provide the apiKey after script has been downloaded and evaluated. This is probably besides the point now.

**Comment by matanshukry** [comment] 2022-03-08 07:51
@nshahan 

> If I set a breakpoint inside _doInit() (which I believe is the callback) I see it being called before the error appears.

Not really. It is a callback, just not the problematic one.
`_doInit()` is called after the initialization of the object. There is no error at that point, even just at the logs level, as far as I remember.

The error is being displayed when calling `getPlacePredictions`, where the callback is the return value (promise/future). That callback is never called.

**Comment by ditman** [comment] 2022-03-10 22:06
Just a quick drive-through comment, from a quick look to the code:

@matanshukry have you considered using [`package:google_maps/google_maps_places.dart`](https://pub.dev/packages/google_maps) as your js-interop layer, instead of writing your own?

The library contains re-implemented ["Places" examples from the Google Maps JS SDK](https://developers.google.com/maps/documentation/javascript/examples#places) as their [Dart examples](https://github.com/a14n/dart-google-maps/tree/master/example/10-places).

We use it as the backing implementation for `package:google_maps_flutter`. I didn't miss one second having to write my own js-interop layer to the maps SDK :)

**Comment by matanshukry** [comment] 2022-05-27 08:01
@ditman just tried it instead, and I will use it fron now on, but it doesn't fix the issue; it has exactly the same problem.

That is, when the key is invalid I can see an error and a warning in the logs, but they are logs printed from the actual method call (javascript), and the actual method I called which is a future is never resolved nor does it throw anything.

**Comment by ditman** [comment] 2022-05-27 18:39
OK, I took a look at this, here's what I learned:

1. The error that you see on the screen cannot be caught, because it's not an actual thrown error that bubbled up all the way to the console, it's Google Maps printing it straight to the console by doing `console.error` (and `console.warn`). You can see that by clicking on the filename next to the error:
    <img width="517" alt="Screen Shot 2022-05-27 at 11 14 02 AM" src="https://user-images.githubusercontent.com/1255594/170767771-17a1d042-dd83-434f-ba67-4be0724bafb7.png">
    * This behavior is also documented here: https://developers.google.com/maps/documentation/javascript/error-messages#checking-errors (looks like errors are intended for humans to look at, not programs to "catch").
2. (Unfortunately) the method `doInit` is called, so the `completer` will always successfully complete, even when the API key is wrong. I'm not sure you can programmatically discover if the API has successfully loaded or not. (I tried to do a `Future.timeout` with the completer, but it gets resolved before my timeout triggers)

What we do to sidestep this, is to ask developers to modify their index.html and add the Google Maps script tag directly there, with their API key, [like here](https://github.com/flutter/plugins/blob/main/packages/google_maps_flutter/google_maps_flutter_web/README.md#modify-webindexhtml). This educates them that there's some "script" that may not be working correctly, and then they associate the API_KEY in the line they just pasted, with the error in the console.

I'm going to close this, since this is not a Flutter/Dart issue, it's the way the Google Maps JS SDK (mis)behaves.

**Closed by ditman** 2022-05-27 18:39 UTC
Labels: framework, dependency: dart, a: debugging, platform-web, has reproducible steps, blocked, found in release: 2.8
