### ISSUE TITLE
Bypass download of dart

### ISSUE THREAD

**Issue by Eraazeur** [flutter/flutter#15333] opened 2018-03-09 08:48 UTC
Hi, 

I would like to install dart on my work computer, but there is a proxy, and i can't disable it.

So when i write the command flutter it check for dart update and i got an error.

Flutter doctor : 
```
**C:\Users\g594841>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8
a...
Start-BitsTransfer : État HTTP 407 : l'authentification du proxy est demandée.
Au caractère C:\Program Files\flutter\bin\internal\update_dart_sdk.ps1:47 : 1
+ Start-BitsTransfer -


Source $dartSdkUrl -Destination $dartSdkZip
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [Start-BitsTransfer], Exc
   eption
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.Backgrou
   ndIntelligentTransfer.Management.NewBitsTransferCommand

Error: Unable to update Dart SDK. Retrying...

Attendre 2 secondes, appuyez sur CTRL+C pour quitter ...**
```

it asks me to authantify the proxy, but i don't know the password. Is there a way to bypass this check and install dart by hand ?

Thanks

**Comment by Hixie** [comment] 2018-06-06 00:01
Duplicate of https://github.com/flutter/flutter/issues/10903.

**Closed by Hixie** 2018-06-06 00:01 UTC
