### ISSUE TITLE
[ Camera ] How to handle error when using camera if another app open camera flutter

### ISSUE THREAD

**Issue by buihongvinh** [flutter/flutter#114392] opened 2022-11-01 04:16 UTC
My app using camera but another app using my camera like video call coming like messenger . and my app crash . and i dont know how to handle this Exception. I use package camera.

I need the help of the experts. Thanks
![aGJQa](https://user-images.githubusercontent.com/72612544/199157447-2041818f-3c9d-41fa-b864-9111ff09cd12.png)

enter image description here

I have try this code to listener the error but nothing can be catch.

   cameraController.addListener(() {
      if (mounted) {
        setState(() {});
      }
      if (cameraController.value.hasError) {
        showInSnackBar(
            'Camera error ${cameraController.value.errorDescription}');
      }
    });

**Comment by huycozy** [comment] 2022-11-01 10:43
Hi @buihongvinh, 
Which `camera` plugin version are you using? 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the crash log in text format instead of a screenshot for better readability. Thank you!

**Comment by buihongvinh** [comment] 2022-11-02 03:35
Hi @huycozy Thanks for your answer.
I am using 
-camera: ^0.10.0+4

step to Reproduce :

- download the newest example in Pub of Camera :
- open app and recording video
-using another phone make a call. ( another app use camera or micro )
- stop call
- app can not catch video have been record before


here is the video .

https://user-images.githubusercontent.com/72612544/199389374-0593b30d-45bb-4004-8417-490ecd67021a.mp4

**Comment by huycozy** [comment] 2022-11-02 07:55
Hi @buihongvinh 
I tried running the [camera/example](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example) sample code but there was no exception log from the console as yours. I can see the same from your recorded video. 

>app can not catch video have been record before

For this issue, I can see it from my side with the plugin sample code. But this function hasn't been implemented yet in the sample code when the app goes to background. You may need to implement this function as the OP in issue #113477, but that issue hasn't been fixed.

For the exception log from your first comment, can you check whether this issue happens randomly or all the time? Also, please provide the crash log in text format instead of a screenshot for better readability. Thank you!

**Comment by buihongvinh** [comment] 2022-11-02 09:01
Hi @huycozy 

For the exception log from my first comment,
I am using another package running camera in background. (https://github.com/X-SLAYER/camera-android)  .
 - not this package
I dowload sample code and run .
- start camera
- press home 
- the app will go into background
- open camera app
- and this will show this error

E/CameraCaptureSession(17520): Session 1: Exception while stopping repeating: 
E/CameraCaptureSession(17520): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:461: Camera 1: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession(17520): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1003)
E/CameraCaptureSession(17520): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession(17520): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1265)
E/CameraCaptureSession(17520): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(17520): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:790)
E/CameraCaptureSession(17520): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:251)
E/CameraCaptureSession(17520): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(17520): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(17520): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CameraCaptureSession(17520): 	at android.os.Looper.loop(Looper.java:288)
E/CameraCaptureSession(17520): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/CameraCaptureSession(17520): Caused by: android.os.ServiceSpecificException: cancelRequest:461: Camera 1: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession(17520): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
E/CameraCaptureSession(17520): 	at android.os.Parcel.createException(Parcel.java:2402)
E/CameraCaptureSession(17520): 	at android.os.Parcel.readException(Parcel.java:2385)
E/CameraCaptureSession(17520): 	at android.os.Parcel.readException(Parcel.java:2327)
E/CameraCaptureSession(17520): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:746)
E/CameraCaptureSession(17520): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession(17520): 	... 9 more
W/s.cameraexampl(17520): Long monitor contention with owner CameraBackground (17810) at void android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating()(CameraDeviceImpl.java:1276) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 319ms
I/Camera  (17520): open | onDisconnected

this issue happen all the time .
Thanks you for your help .

**Comment by buihongvinh** [comment] 2022-11-02 09:02
And can I request feature " catch video have been record before another app useing camera " ?

**Comment by huycozy** [comment] 2022-11-02 12:12
Hi @buihongvinh 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. I also see your [filled issue](https://github.com/X-SLAYER/camera-android/issues/1) there. Please follow up on that issue for further updates.
Also, based on the above crash log, I see there's an open issue that has the similar log: #102644. You may follow up on it or refer that issue to [plugin's filled issue](https://github.com/X-SLAYER/camera-android/issues/1) which may help plugin's author investigate further.

>And can I request feature " catch video have been record before another app useing camera " ?

Please check this https://github.com/flutter/flutter/issues/102644#issuecomment-1116766881 as an answer.


Closing the issue since it relates to 3rd plugin. If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2022-11-02 12:12 UTC
Labels: in triage
