### ISSUE TITLE
Support .9.png format of a image

### ISSUE THREAD

**Issue by coderJohnZhang** [flutter/flutter#13863] opened 2018-01-03 08:06 UTC
Here is my question submit on stackoverflow:
[How to display .9.png format of a picture in flutter?](https://stackoverflow.com/questions/48056304/how-to-display-9-png-format-of-a-picture-in-flutter)

**Comment by coderJohnZhang** [comment] 2018-01-04 12:14
See [https://github.com/coderJohnZhang/flutter_tv](https://github.com/coderJohnZhang/flutter_tv). The focus box may change size when move position form one to another, so I need a nine-patch picture if build with android, see [http://developer.android.com/guide/topics/graphics/2d-graphi‌​cs.html#nine-patch. ](http://developer.android.com/guide/topics/graphics/2d-graphi‌​cs.html#nine-patch). What is the same way in flutter?

**Comment by Hixie** [comment] 2018-01-05 00:58
Is there any documentation on what the format of these images is?

**Comment by Hixie** [comment] 2018-01-05 00:59
You can set the [centerSlice](https://flutter.docs.io/flutter/widgets/Image/centerSlice.html) property on the Image widget if you know the coordinates of the middle section of your nine-patch image. We don't currently read those coordinates out of the image automatically. If there's any documentation on how Android does that, it's something we would consider doing.

**Comment by goderbauer** [comment] 2018-12-28 21:47
Closing as dupe of https://github.com/flutter/flutter/issues/16098, which has more context.

**Closed** 2018-12-30 16:44 UTC
Labels: framework, severe: new feature
