### ISSUE TITLE
Android Studio/IntelliJ crashes when showing suggestions on macOS

### ISSUE THREAD

**Issue by Andreigr0** [flutter/flutter#71779] opened 2020-12-05 16:17 UTC
## Steps to Reproduce
Can't say exactly how to reproduce it just crashes when it tries to receive suggestions. Sometimes I can work for several hours without crashing and sometimes it could be 2-3 crashes within 10 minutes (!)

I've already tried to completely uninstall Android Studio but it didn't help (https://stackoverflow.com/a/18458893/9586934)
First time it happened about 2-3 months ago

Android Studio 4.1.1 and Flutter plugin 52.0.1

P.S. I've tried to search for this problem but haven't succeed in it, but I asked in Russian community in Telegram and there some people also facing this issue

## Logs

flutter doctor -v
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-10.2.pre at /Users/andrey/flutter
    • Framework revision 022b333a08 (2 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 50.0.2
    • Dart plugin version 201.9002

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 3997FAF8-563B-4DE0-9BA7-AFF7BF40F2CF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-12-07 08:48
Hi @Andreigr0 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-07 08:48 UTC
