### ISSUE TITLE
[proposal] Improve Emoji resolution when using large sized text 

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#76322] opened 2021-02-18 18:51 UTC
Here you can see a large emoji beside a large text
![image](https://user-images.githubusercontent.com/736973/108406190-4ee1d200-71df-11eb-9ab9-57c9b51d8b22.png)

Observe that the text is crisp while the emoji quite low-resolution and visibly up-scaled. 

Confirmed on Windows and Web
```
Flutter 1.26.0-12.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision a706cd2112 (5 weeks ago) • 2021-01-14 18:20:26 -0500
Engine • revision effb529ece
Tools • Dart 2.12.0 (build 2.12.0-224.0.dev)
```

**Comment by yjbanov** [comment] 2021-02-19 01:01
Looks like this is standard behavior. This is what large emoji look like in plain HTML:

![big-emoji](https://user-images.githubusercontent.com/211513/108441870-de50aa80-720a-11eb-8fcf-123d16cc5470.png)

Having said that if there is indeed a way to make them look nicer, we should definitely try.

**Comment by esDotDev** [comment] 2021-02-19 01:37
Thanks! Ya it effects Windows builds as well, sounds like it is standard Emoji behavior?? 

Definitely would be nice if something can be done, some sort of manual cache sizing would be nice. So we can turn it up if we're on a more powerful device, or have only a handful of Emojis.

**Comment by TahaTesser** [comment] 2021-02-19 13:40
Hi @esDotDev 
I faced a similar issue on the iPad, it looked bad. I will label this as a proposal  to improve this

**Comment by yjbanov** [comment] 2021-02-20 01:18
After some research we found that indeed the font contains bitmap emoji, not vector, so this is working as intended. It's not clear what we can do here.

Having said that, you can find the vector versions of emojis here: https://github.com/googlefonts/noto-emoji/tree/master/svg. Perhaps you can use SVG with `package:flutter_svg` and `ParagraphBuilder.addPlaceholder`?

**Comment by yjbanov** [comment] 2021-02-25 23:16
Closing as this is working as intended. We have https://github.com/flutter/flutter/issues/76797 to use a different emoji fallback, but the biggest motivator is size. It feels like there's room for a pub package that renders emoji using vector graphics that scale well.

**Closed by yjbanov** 2021-02-25 23:16 UTC
Labels: passed first triage, platform-web, proposal
