### ISSUE TITLE
dart fix --apply not fixing the warnings

### ISSUE THREAD

**Issue by PranayDosii** [flutter/flutter#105875] opened 2022-06-13 07:26 UTC
I was using the `flutter 2.10.5` version after that the new flutter version was released and I switched to 3.0. Now I am getting some warnings which are already mentioned in [link](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0).
but when I am trying to run this command `dart fix --apply` It's not fixing my problem please help with it.
warnings 
```: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/src/extension_navigation.dart:468
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Documents/flutter_2/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1```
Thank you

**Comment by maheshmnj** [comment] 2022-06-13 11:46
Hi @PranayDosii, Could you please share me the complete log of the warning/error by running `flutter run -v`?

Also, note that `dart fix --apply` would only work if the warnings are in your code and not in the plugins or libraries that you depend on. Warnings in those dependencies must be fixed by the plugin authors by running the same command.

**Comment by PranayDosii** [comment] 2022-06-14 04:03
` Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/src/extension_navigation.dart:357
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Documents/flutter_2/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^

: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/src/extension_navigation.dart:468
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Documents/flutter_2/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^

: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/snackbar/snackbar.dart:452
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Documents/flutter_2/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^

: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
../…/rx_flutter/rx_disposable.dart:20
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Documents/flutter_2/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
`

**Comment by maheshmnj** [comment] 2022-06-14 06:03
Thanks for the output @PranayDosii,  

> : Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
../…/rx_flutter/rx_disposable.dart:20

this warning is from rx_flutter (should be fixed by the package owner) and rest of them are from flutter. However, these are just warnings and can be ignored. (Probably fixed in the newer release of flutter) You may verify this on the master channel.

`dart fix --apply` is only to fix the warnings in your code and not in the packages you depend on. So I would say this the desired behavior and working as intended.

Closing as no action can be taken here.

**Closed by maheshmnj** 2022-06-14 06:03 UTC
Labels: in triage
