### ISSUE TITLE
On Marker Drag Event Listener

### ISSUE THREAD

**Issue by kttary** [flutter/flutter#87903] opened 2021-08-08 13:06 UTC
Please consider to implement on marker drag event listener like onMarkerDrag(Marker marker) in java

**Comment by maheshmnj** [comment] 2021-08-09 09:35
Hi @kttary, Could you please be more specific?
I believe you are talking about the Google maps marker drag event? if so please take a look at this [stackoverflow answer](https://stackoverflow.com/a/57970515/8253662)

Thanks.

**Comment by kttary** [comment] 2021-08-09 09:59
Hi @maheshmnj, yes i'm talking about Google maps marker. In flutter, google maps only listen to onDragEnd listener. I believe its coming from GoogleMapController.java method:

```
@Override
public void onMarkerDragEnd(Marker marker) {
markersController.onMarkerDragEnd(marker.getId(), marker.getPosition());
}
```
the other 2 java methods which are `onMarkerDrag(Marker marker) {} ` and `onMarkerDragStart(Marker marker) {}` is not implemented yet on flutter. I need this two event listener on flutter. Hope this clear

**Comment by maheshmnj** [comment] 2021-08-09 11:03
Could you please update your main post with this description.

**Comment by maheshmnj** [comment] 2021-08-09 11:32
@kttary There's a similar issue describing this case and PR's inbound closing this issue as a duplicate of https://github.com/flutter/flutter/issues/26117

**Closed by maheshmnj** 2021-08-09 11:32 UTC
Labels: in triage
