### ISSUE TITLE
error while building flutter app: Final field 'licenseEntries' is not initialized by this constructor. in about.dard Flutter SDK

### ISSUE THREAD

**Issue by AbdulazizAlnahhas** [flutter/flutter#90445] opened 2021-09-21 11:25 UTC
hi 
when i tried to build my new Flutter app i faced this error in Flutter SDK 

`C:/FlutterSDK/flutter/packages/flutter/lib/src/material/about.dart:792:3: Error: Final field 'licenseEntries' is not initialized by this constructor.
Try to initialize the field using an initializing formal or a field initializer.
  _DetailArguments.name(this.packageName);
  ^^^^
/C:/FlutterSDK/flutter/packages/flutter/lib/src/material/about.dart:790:28: Context: 'licenseEntries' is defined here.
  final List<LicenseEntry> licenseEntries;
                           ^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\FlutterSDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\FlutterSDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s`

I am using flutter 2.2.3, Dart 2.12.0
No Issues in flutter Doctor

tried to do "Flutter clean" 
and reinstall flutter SDK 
but nothing solve my problem

**Comment by maheshmnj** [comment] 2021-09-21 12:22
> Try to initialize the field using an initializing formal or a field initializer.
_DetailArguments.name(this.packageName);

@AbdulazizAlnahhas it looks like the error is clear enough to indicate the cause of the build failure. If you need further help please try asking the question on communities like stackoverflow with a proper sample code. The Github issue tracker is only to track issues in the flutter framework and not to help on personal code.

Closing the issue as invalid, Since it doesn't seem to describe a bug or feature request in the flutter framework.
If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-21 12:22 UTC
Labels: in triage
