### ISSUE TITLE
Flutter's pub commands should support and list all valid options

### ISSUE THREAD

**Issue by jeroen-meijer** [flutter/flutter#67678] opened 2020-10-08 21:00 UTC
## Use case

I'm the author of a VS Code extension called [Pubspec Assist](https://marketplace.visualstudio.com/items?itemName=jeroen-meijer.pubspec-assist) that is useful for managing Dart and Flutter dependencies.
I want to write a new feature that allows the user to automatically update outdated dependencies.

In pure Dart projects, I can use `pub outdated --json` to fetch the necessary data.
However, the Flutter equivalent `flutter pub outdated` does not have a `--json` option. I think this option should be available.

Interestingly enough, running `flutter pub outdated --no-color` **does** work, even though that flag is not reported by `flutter pub outdated --help`. In fact, the `--help` command doesn't report any supported arguments except from the global options and the `--help` flag itself, even though `--no-color` is/seems to be supported.

<details><summary>flutter pub oudated --help output</summary>

```
Analyze dependencies to find which ones can be upgraded.
This runs the "pub" tool in a Flutter context.

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands
                            executed.
                            If used with --help, shows hidden options.
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Usage: flutter pub outdated [<arguments...>]
-h, --help    Print this usage information.

Run "flutter help" to see global options.
```

</details>

## Proposal

I believe that:

1. Any arguments passed to `flutter pub` should be passed to the internal `pub` tool, or, in other words, all supported arguments for a `pub` command should be supported in Flutter's `pub` tool as well (where applicable).
2. The `flutter pub <command> --help` command should provide the arguments that are available for that command (similar to `pub <command> --help`).

**Comment by iapicca** [comment] 2020-10-08 22:22
possible related issue https://github.com/flutter/flutter/issues/57411

**Comment by TahaTesser** [comment] 2020-10-09 09:51
Hi @jeroen-meijer 
This is a duplicate of https://github.com/flutter/flutter/issues/57411
```bash
tahatesser@pop-os:~$ flutterm pub outdated -h
Analyze dependencies to find which ones can be upgraded.
This runs the "pub" tool in a Flutter context.

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands
                            executed.
                            If used with --help, shows hidden options.
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.
    --packages              Path to your ".packages" file.
                            (required, since the current directory does not
                            contain a ".packages" file)

Usage: flutter pub outdated [<arguments...>]
-h, --help    Print this usage information.

Run "flutter help" to see global options.
tahatesser@pop-os:~$ dart pub outdated -h
Analyze your dependencies to find which ones can be upgraded.

Usage: pub outdated [options]
-h, --help                         Print this usage information.
    --[no-]color                   Whether to color the output.
                                   Defaults to color when connected to a
                                   terminal, and no-color otherwise.
    --[no-]dependency-overrides    Show resolutions with `dependency_overrides`.
                                   (defaults to on)
    --[no-]dev-dependencies        Take dev dependencies into account.
                                   (defaults to on)
    --json                         Output the results using a json format.
    --[no-]prereleases             Include prereleases in latest version.
    --[no-]show-all                Include dependencies that are already
                                   fullfilling --mode.

Run "pub help" to see global options.
See https://dart.dev/tools/pub/cmd/pub-outdated for detailed documentation.
tahatesser@pop-os:~$ 
```


Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-09 09:51 UTC

**Comment by jeroen-meijer** [comment] 2020-10-09 10:11
Great point, apologies for opening a dupe. I'll follow any further developments on the linked ticket.
