### ISSUE TITLE
webview_flutter_wkwebview: No visible @interface for 'FWFWebView' declares the selector 'setInspectable:'

### ISSUE THREAD

**Issue by thangldvn** [flutter/flutter#129602] opened 2023-06-27 03:20 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. build ipa for ios
2. No visible @interface for 'FWFWebView' declares the selector 'setInspectable:'
![Screen Shot 2023-06-27 at 10 16 07](https://github.com/flutter/flutter/assets/32036945/8afdb0e2-43a4-4c02-a18f-c828dd8561e3)
this can be by new version release 3.6.0 on webview_flutter_wkwebview
I am using flutter 3.7.3

### Expected results

this can be export ipa successfully

### Actual results

Failed to build iOS app
ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the selector 'setInspectable:'
/Users/va/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.6.0/ios/Classes/FWFWebViewHostApi.m:203:44

![Screen Shot 2023-06-27 at 10 16 07](https://github.com/flutter/flutter/assets/32036945/8afdb0e2-43a4-4c02-a18f-c828dd8561e3)

### Code sample

<details><summary>Code sample</summary>

```dart
flutter build ipa --release --flavor uat
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6 21G115 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

**Comment by BottlePumpkin** [comment] 2023-06-27 04:29
me too

**Comment by BottlePumpkin** [comment] 2023-06-27 05:17
@thangldvn 
I updated my xcode version to 14.3.1 and the issue was resolved.

**Comment by stuartmorgan** [comment] 2023-06-27 09:53
Duplicate of https://github.com/flutter/flutter/issues/129587

**Closed** 2023-06-27 09:53 UTC
