### ISSUE TITLE
flutter 2.2.2, flutter doctor command stucks at running `Running "flutter pub get" in flutter_tools...`

### ISSUE THREAD

**Issue by suifengtec** [flutter/flutter#85503] opened 2021-06-29 03:11 UTC
Hi! I tried to install  lastest flutter on Windows 10 , but some issue(s) happend.

 I have set `FLUTTER_STORAGE_BASE_URL`  to `https://storage.flutter-io.cn` and `PUB_HOSTED_URL` to `https://pub.flutter-io.cn`. casuse I am in China.

where is flutter and dart?

```bash

λ where flutter dart
D:\tools\flutter\bin\flutter
D:\tools\flutter\bin\flutter.bat
D:\tools\flutter\bin\dart
D:\tools\flutter\bin\dart.bat

```
flutter upgrade

```bash

λ flutter upgrade
Flutter is already up to date on channel stable
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (2 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

set Android Studio and SDK dirs: 

```bash
# Android Studio 4.2
flutter config --android-studio-dir="D:\Program Files\Android\Android Studio"
# lastest
flutter config --android-sdk="D:\tools\android-sdk"

```

flutter doctor

```bash
Running "flutter pub get" in flutter_tools...                          \

```

now , it stacks at this command and download nothing and looks like do something:

![stack](https://i.imgur.com/yxmALKP.jpeg)

I wait it three hours to ensure it is stucked.

I have tried to  delete the `flutter` directory and re-unzip `flutter_windows_2.2.2-stable.zip` to it and run `flutter doctor` again, but everything is same as above.

How to fix it...

**Comment by TahaTesser** [comment] 2021-06-29 13:17
Hi @suifengtec 
Can you please try disabling any antivirus or firewall apps or switch your network? 
Thank you

**Comment by suifengtec** [comment] 2021-06-30 10:21
> Hi @suifengtec
> Can you please try disabling any antivirus or firewall apps or switch your network?
> Thank you

@TahaTesser  thank you for your response!

I have disabled antivirus software( and firewall) and deleted `\flutter\bin\cache\lockfile`, then : 

![S](https://i.imgur.com/v9KehVi.jpeg)

may only files in this directory be refreshed:

![s](https://i.imgur.com/nI7yUlE.jpeg)

the following directory has  nothing:
![s](https://i.imgur.com/GPl6CaC.jpeg)

the dart.exe is running:

![S](https://i.imgur.com/AvlfWfd.jpeg)

![s](https://i.imgur.com/15hmXgK.jpeg)

everthing looks like before: dart.exe may do something but nothing.

I will try to install flutter on another new PC.

**Comment by TahaTesser** [comment] 2021-07-01 07:49
Hi @suifengtec
Looks like an issue with your cache, can you please clear your cache and try again?  `flutter pub cache repair`

if the issue persists on the new system, the issue is most likely with the network, not being able to access pub files, you might have to try different network

**Comment by TahaTesser** [comment] 2021-07-23 12:58
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-23 12:58 UTC
