### ISSUE TITLE
[Web] Navigation with back-button is broken

### ISSUE THREAD

**Issue by Grouen** [flutter/flutter#110597] opened 2022-08-30 16:52 UTC
<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void main() async {
  setUrlStrategy(PathUrlStrategy());
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Front-End',
      theme: ThemeData(),
      initialRoute: "/",
      onGenerateRoute: (settings) {
        var screen;

        switch (settings.name) {
          case "/":
            screen = Screen1();
            break;
          case "/test2":
            screen = Screen2();
            break;
          case "/test3":
            screen = Screen3();
            break;
        }

        return PageRouteBuilder(pageBuilder: (context, animation, secondaryAnimation) => screen!, settings: settings);
      },
    );
  }
}

class Screen1 extends StatelessWidget {
  const Screen1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: MaterialButton(
        child: Text("1"),
        onPressed: () {
          Navigator.pushNamed(context, "/test2");
        },
      ),
    );
  }
}

class Screen2 extends StatelessWidget {
  const Screen2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: MaterialButton(
        child: Text("2"),
        onPressed: () {
          Navigator.pushNamed(context, "/test3");
        },
      ),
    );
  }
}

class Screen3 extends StatelessWidget {
  const Screen3({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: MaterialButton(
        child: Text("3"),
        onPressed: () {},
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

https://user-images.githubusercontent.com/20682547/187494810-c29cd44a-bf59-4cc0-8a40-7fd36c80b041.mp4

**Comment by Grouen** [comment] 2022-08-30 16:53
Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale ru-RU)
    • Flutter version 3.0.5 at H:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by adilwahla** [comment] 2022-08-30 18:02
### Hey follow the pop() to go back when you are using Named routing 
To work with named routes, use the [Navigator.pushNamed()](https://api.flutter.dev/flutter/widgets/Navigator/pushNamed.html) function. This example replicates the functionality from the original recipe, demonstrating how to use named routes using the following steps:

1. Create two screens.
2. Define the routes.
3. Navigate to the second screen using Navigator.pushNamed().
**4. Return to the first screen using Navigator.pop().**

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Named Routes Demo',
      // Start the app with the "/" named route. In this case, the app starts
      // on the FirstScreen widget.
      initialRoute: '/',
      routes: {
        // When navigating to the "/" route, build the FirstScreen widget.
        '/': (context) => const FirstScreen(),
        // When navigating to the "/second" route, build the SecondScreen widget.
        '/second': (context) => const SecondScreen(),
      },
    ),
  );
}

class FirstScreen extends StatelessWidget {
  const FirstScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('First Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          // Within the `FirstScreen` widget
          onPressed: () {
            // Navigate to the second screen using a named route.
            Navigator.pushNamed(context, '/second');
          },
          child: const Text('Launch screen'),
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  const SecondScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          // Within the SecondScreen widget
          onPressed: () {
            // Navigate back to the first screen by popping the current route
            // off the stack.
            Navigator.pop(context);
          },
          child: const Text('Go back!'),
        ),
      ),
    );
  }
}
```

**Comment by adilwahla** [comment] 2022-08-30 18:12
> routes: {
>         // When navigating to the "/" route, build the FirstScreen widget.
>         '/': (context) => const FirstScreen(),
>         // When navigating to the "/second" route, build the SecondScreen widget.
>         '/second': (context) => const SecondScreen(),
>       },
>     ),
>   );
> }

think this code part is modified switch case same just syntax is different the thing is .....


> onPressed: () {},

use Navigator.pop() here in last screen onPressed(){Navigator.pop();}

**Comment by Grouen** [comment] 2022-08-30 18:26
> ### Hey follow the pop() to go back when you are using Named routing
> To work with named routes, use the [Navigator.pushNamed()](https://api.flutter.dev/flutter/widgets/Navigator/pushNamed.html) function. This example replicates the functionality from the original recipe, demonstrating how to use named routes using the following steps:
> 
> 1. Create two screens.
> 2. Define the routes.
> 3. Navigate to the second screen using Navigator.pushNamed().
>    **4. Return to the first screen using Navigator.pop().**
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(
>     MaterialApp(
>       title: 'Named Routes Demo',
>       // Start the app with the "/" named route. In this case, the app starts
>       // on the FirstScreen widget.
>       initialRoute: '/',
>       routes: {
>         // When navigating to the "/" route, build the FirstScreen widget.
>         '/': (context) => const FirstScreen(),
>         // When navigating to the "/second" route, build the SecondScreen widget.
>         '/second': (context) => const SecondScreen(),
>       },
>     ),
>   );
> }
> 
> class FirstScreen extends StatelessWidget {
>   const FirstScreen({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('First Screen'),
>       ),
>       body: Center(
>         child: ElevatedButton(
>           // Within the `FirstScreen` widget
>           onPressed: () {
>             // Navigate to the second screen using a named route.
>             Navigator.pushNamed(context, '/second');
>           },
>           child: const Text('Launch screen'),
>         ),
>       ),
>     );
>   }
> }
> 
> class SecondScreen extends StatelessWidget {
>   const SecondScreen({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Second Screen'),
>       ),
>       body: Center(
>         child: ElevatedButton(
>           // Within the SecondScreen widget
>           onPressed: () {
>             // Navigate back to the first screen by popping the current route
>             // off the stack.
>             Navigator.pop(context);
>           },
>           child: const Text('Go back!'),
>         ),
>       ),
>     );
>   }
> }
> ```

The issue about browser back button and how flutter handles it.

**Comment by adilwahla** [comment] 2022-08-30 18:32
> > ### Hey follow the pop() to go back when you are using Named routing
> > To work with named routes, use the [Navigator.pushNamed()](https://api.flutter.dev/flutter/widgets/Navigator/pushNamed.html) function. This example replicates the functionality from the original recipe, demonstrating how to use named routes using the following steps:
> > 
> > 1. Create two screens.
> > 2. Define the routes.
> > 3. Navigate to the second screen using Navigator.pushNamed().
> >    **4. Return to the first screen using Navigator.pop().**
> > 
> > ```
> > import 'package:flutter/material.dart';
> > 
> > void main() {
> >   runApp(
> >     MaterialApp(
> >       title: 'Named Routes Demo',
> >       // Start the app with the "/" named route. In this case, the app starts
> >       // on the FirstScreen widget.
> >       initialRoute: '/',
> >       routes: {
> >         // When navigating to the "/" route, build the FirstScreen widget.
> >         '/': (context) => const FirstScreen(),
> >         // When navigating to the "/second" route, build the SecondScreen widget.
> >         '/second': (context) => const SecondScreen(),
> >       },
> >     ),
> >   );
> > }
> > 
> > class FirstScreen extends StatelessWidget {
> >   const FirstScreen({super.key});
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >       appBar: AppBar(
> >         title: const Text('First Screen'),
> >       ),
> >       body: Center(
> >         child: ElevatedButton(
> >           // Within the `FirstScreen` widget
> >           onPressed: () {
> >             // Navigate to the second screen using a named route.
> >             Navigator.pushNamed(context, '/second');
> >           },
> >           child: const Text('Launch screen'),
> >         ),
> >       ),
> >     );
> >   }
> > }
> > 
> > class SecondScreen extends StatelessWidget {
> >   const SecondScreen({super.key});
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >       appBar: AppBar(
> >         title: const Text('Second Screen'),
> >       ),
> >       body: Center(
> >         child: ElevatedButton(
> >           // Within the SecondScreen widget
> >           onPressed: () {
> >             // Navigate back to the first screen by popping the current route
> >             // off the stack.
> >             Navigator.pop(context);
> >           },
> >           child: const Text('Go back!'),
> >         ),
> >       ),
> >     );
> >   }
> > }
> > ```
> 
> The issue is about browser back button and how flutter handles it. Your example doesn't solve the problem because user always can press browser back button instead of regular button

hey don't use my example only use Navigator.pop() in onpress(){} of last screen thats all give a try in your own code

**Comment by adilwahla** [comment] 2022-08-30 18:50
Hey got it [https://stackoverflow.com/questions/61322093/how-to-configure-go-back-button-in-browser-for-flutter-web-app]

**Comment by Grouen** [comment] 2022-08-30 19:31
> Hey got it have you tried WillPopScope()
> 
> ```
> class webScope extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new WillPopScope(
>       onWillPop: () async => Navigator.push(context, MaterialPageRoute(builder: (context) => new NewPageWidget())),
>       child: Scaffold(
>         appBar: new AppBar(
>           title: new Text("webScope"),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> [[stackoverflow link ](https://stackoverflow.com/questions/61322093/how-to-configure-go-back-button-in-browser-for-flutter-web-app)]

I tried, but it doesn't solve the issue with back button. It still doesn't work as expected even if I pop navigator manually, and sometimes it even doesn't trigger onWillPop.

**Comment by danagbemava-nc** [comment] 2022-08-31 10:48
Hi @Grouen, a new version of stable was released recently. Can you upgrade to the latest version of stable to see whether or not this issue still occurs for you? If it does, please provide the updated output of `flutter doctor -v`. 

Thank you

**Comment by Grouen** [comment] 2022-08-31 10:51
> Hi @Grouen, a new version of stable was released recently. Can you upgrade to the latest version of stable to see whether or not this issue still occurs for you? If it does, please provide the updated output of `flutter doctor -v`.
> 
> Thank you

Hi. Still have this issue.

Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.856], locale ru-RU)
    • Flutter version 3.3.0 on channel stable at H:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (34 hours ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

**Comment by danagbemava-nc** [comment] 2022-09-01 07:10
Reproducible on `stable` and `master`. 

Possibly related: https://github.com/flutter/flutter/issues/59185

After messing around with the back button for some time, I got some errors in my console. 

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/187853149-41fa6402-d885-4ae9-aa34-a29bddb37c1c.mov
</details>

Labeling for further investigation from the team.

<details>
<summary>logs</summary>

```
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:52705/zXNObG_Jfj0=/ws
Debug service listening on ws://127.0.0.1:52705/zXNObG_Jfj0=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:52705/zXNObG_Jfj0=/ws
Flutter Web Bootstrap: Programmatic
Flutter Web Bootstrap: Programmatic
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:325:14
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
lib/_engine/engine/navigation/history.dart 325:37                                 onPopState
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:325:14
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
lib/_engine/engine/navigation/history.dart 325:37                                 onPopState
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:325:14
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
lib/_engine/engine/navigation/history.dart 325:37                                 onPopState
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:325:14
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
lib/_engine/engine/navigation/history.dart 325:37                                 onPopState
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (2 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2608, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2608 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 759d0e1b20 (62 minutes ago), 2022-08-31 23:07:20 -0700
    • Engine revision b149eea0a3
    • Dart version 2.19.0 (build 2.19.0-154.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by shawks03** [comment] 2023-05-04 23:00
I'm seeing problems with back button too, didn't see before upgrading flutter. What's interesting, if I use Firefox the back button works just fine, but using Chrome it goes to back to New Tab or whatever site was open before mine.

flutter --version
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (2 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by dvmatyun** [comment] 2023-11-11 17:33
Any progress?

**Comment by mdebbar** [comment] 2023-12-07 19:48
Please see [this comment](https://github.com/flutter/flutter/issues/139561#issuecomment-1845999909).

Duplicate of https://github.com/flutter/flutter/issues/139561

**Closed by mdebbar** 2023-12-07 19:48 UTC
Labels: framework, f: routes, platform-web, has reproducible steps, assigned for triage, found in release: 3.1, found in release: 3.3, team-web
