### ISSUE TITLE
TextField: Missing keyboard shortcuts for Windows

### ISSUE THREAD

**Issue by PavelPZ** [flutter/flutter#77020] opened 2021-03-01 23:30 UTC
I follow recomendation in https://github.com/flutter/flutter/issues/64721#issuecomment-712919337 (**"If you find specific issues in a current version..."** )

For windows, the following shortcuts are missing: Ctrl+End, Ctrl+Home, Ctrl+Shift+End, Ctrl+Shift+Home, Shift+End, Shift+Home

**Comment by TahaTesser** [comment] 2021-03-02 09:32
Hi @PavelPZ 
Please provide uses cases for these shortcuts, actual results, and expected with a code sample
Can you please provide your `flutter doctor -v`  and a complete reproducible minimal code sample with print examples
Thank you

**Comment by PavelPZ** [comment] 2021-03-04 23:59
Hi @TahaTesser, I thing the problem is discussed in https://github.com/flutter/flutter/issues/76121

**Comment by TahaTesser** [comment] 2021-03-05 07:55
HI @PavelPZ 
Yes, that issue explains what HOME or END keys are supposed to do, Can you please explain what ` Ctrl+End, Ctrl+Home, Ctrl+Shift+End, Ctrl+Shift+Home, Shift+End, Shift+Home` are supposed to do? 

Sample and expected results similar to https://github.com/flutter/flutter/issues/76121#issue-809434169
Thank you

**Comment by AberrantWolf** [comment] 2021-03-06 02:20
I didn't file this issue, but I'm also encountering the problem, so here's the detailed information.

Similar sample code to https://github.com/flutter/flutter/issues/76121#issue-809434169, but multiple lines are required.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Text Edit',
      home: _TextFieldExample(),
    );
  }
}

class _TextFieldExample extends StatefulWidget {
  @override
  _TextFieldExampleState createState() => _TextFieldExampleState();
}

class _TextFieldExampleState extends State<_TextFieldExample> {
  final FocusNode _focusNode = FocusNode();
  final TextEditingController _textController = TextEditingController();

  @override
  void dispose() {
    _focusNode.dispose();
    _textController.dispose();
    super.dispose();
  }

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Text Test'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            SizedBox(
              width: 400,
              child: TextField(
                controller: _textController,
                focusNode: _focusNode,
                minLines: 5,
                maxLines: 5,
                decoration: InputDecoration(
                  hintText:
                      'Write several lines, then experiment with\nShift+HOME, Shift+END,\nCtrl+HOME, Ctrl+END,\nand\nCtrl+Shift+HOME, Ctrl+Shift+END',
                  border: const OutlineInputBorder(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

### Expected Results:
* Shift+HOME: selects all text from the cursor/pivot to the beginning of the current line
* Shift+END: selects all text from the cursor/pivot to the end of the current line
* Ctrl+HOME: moves the cursor to the beginning of the text (first line, before the first character)
* Ctrl+END: move the cursor to the end of the text (last line, after the last character)
* Ctrl+Shift+HOME: selects all text from the cursor/pivot back to the beginning of the text (first line, through first character)
* Ctrl+Shift+END: selects all text from the cursor/pivot forward to the end of the text (last line, through the last character)

### Actual Results:
* Shift+HOME: nothing happens
* Shift+END: nothing happens
* Ctrl+HOME: nothing happens
* Ctrl+END: nothing happens
* Ctrl+Shift+HOME: nothing happens
* Ctrl+Shift+END: nothing happens

### Tested On
**Platform Windows**
2.0.1 beta channel: *Fail*
2.10.0-10.0.pre dev channel: *Fail*


<details>
<summary>Flutter Doctor:</summary>

```
[√] Flutter (Channel dev, 2.1.0-10.0.pre, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 2.1.0-10.0.pre at G:\Programming\Libs\flutter
    • Framework revision cc9b78fc5c (8 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\AndroidSdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\lareo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!
```
</details>

**Comment by AberrantWolf** [comment] 2021-03-06 05:21
Also, if someone can point me to where the inputs come in and where they're mapped and turned into actions (even if on Linux/MacOS) I'm happy to take a look at implementing this on Windows. I looked briefly at the repos and couldn't figure it out and don't have the time to spend all day just learning the code structure, sadly. But point me at some source files and I'm happy to try to fix it myself.

**Comment by canastro** [comment] 2021-03-07 14:58
@AberrantWolf the text editing shortcuts is currently being redesigned;
* Doc: https://docs.google.com/document/d/1QaVIr1bbOWJGNyyNsB75sXgTDRMuxP268sLGTBNDut0/edit#
* First PR: https://github.com/flutter/flutter/pull/75032

**Comment by TahaTesser** [comment] 2021-03-09 11:45
@AberrantWolf 
Thank you so much for the details! https://github.com/flutter/flutter/issues/77020#issuecomment-791842871

**Comment by gspencergoog** [comment] 2021-03-11 19:35
cc @justinmc

**Comment by justinmc** [comment] 2021-04-02 20:24
Thanks @PavelPZ and @AberrantWolf for reporting this and for all of the info.

Shift + home and shift + end should work now, but let me know if they're still not working.  For the others, I'll plan to open a PR to support them soon.

You can see all of the text editing keyboard shortcuts for Windows here:

https://github.com/flutter/flutter/blob/2369d76a1d4278645de9533ea0bd10c8a7ed3254/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart#L348-L372

**Comment by NikolaTotev** [comment] 2021-04-04 09:29
Hello, shift+home and shift+end still don't work for me. I can't find the file shown above in my flutter directory, what is the correct/ recommended procedure for adding this file into my flutter folder?

**Comment by AberrantWolf** [comment] 2021-04-05 04:54
> 
> 
> Hello, shift+home and shift+end still don't work for me. I can't find the file shown above in my flutter directory, what is the correct/ recommended procedure for adding this file into my flutter folder?

I think I saw that the CL got reverted because it ended up breaking some test once it got committed but which wasn't caught pre-submission for some reason.

**Comment by jgoyvaerts** [comment] 2021-07-29 11:15
What's the latest status on this?
Shift + home and Shift + end don't work on windows, in fact Home and End don't even work on Windows at the moment. I'm on flutter 2.2.3

**Comment by justinmc** [comment] 2021-09-25 03:22
I just tried this out on master on my Windows machine and this is what I'm seeing:

| Shortcut | Behavior (Windows) | Behavior (Flutter) |
| -- | -- | -- |
| Ctrl+Home/End | move to start/end of all text | ❌ nothing |
| Ctrl+Shift+Home/End | extend selection to start/end of all text | ❌ nothing |
| Shift+Home/End | extend selection to start/end of line | ❌ works, but pauses at inversion, and jumps lines |

Will open a PR for this.

**Closed** 2021-11-23 22:49 UTC
Labels: severe: new feature, engine, platform-windows, a: desktop, passed first triage, P4
