### ISSUE TITLE
[image_picker] image_picker: ^1.0.7 image revert issue in IOS

### ISSUE THREAD

**Issue by ItsArsalanAziz** [flutter/flutter#146751] opened 2024-04-15 07:46 UTC
### Steps to reproduce

1. get the image from library/gallery or capture it from camera(only front camera)
2. select and show it
3. all images are inverted like a mirror in IOS devices only are inverted

### Expected results

The image must be the same as placed in the gallery or captured by camera using the front camera.

### Actual results

Images are inverted in IOS when choosing from library/gallery using ImagePicker().pickImage(ImageSource.gallery) or captured by camera using ImagePicker().pickImage(ImageSource.camera).

### Code sample

```
ImagePicker().pickImage(source:text == StringConstants.loadFromLibrary ? ImageSource.gallery : ImageSource.camera).then((value) async {
if (value != null) {
List imageBytes = File(value.path).readAsBytesSync();
String _base64Image = base64Encode(imageBytes);
}
}).onError((err, stackTrace) {
debugPrint(err.toString());
});
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
• Flutter version 3.16.7 on channel stable at D:\dev\projects\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/ef1af02aead6fe2414f3aafa5a61087b610e1332 (3 months ago), 2024-01-11 15:19:26 -0600
• Engine revision 4a585b7929
• Dart version 3.2.4
• DevTools version 2.28.5
```

Note: the bug is only generating in case of front camera images that are placed in gallery or captured from camera.

**Comment by darshankawar** [comment] 2024-04-15 11:46
@ItsArsalanAziz 
Is there any difference between this issue and the [other](https://github.com/flutter/flutter/issues/146750) one you reported ?
Can you provide screenshots of the current behavior ?
Check [this](https://github.com/flutter/flutter/issues/74014) similar issue which was fixed and see if it helps in your case or not.

**Comment by ItsArsalanAziz** [comment] 2024-04-15 12:12
@darshankawar 

Yes these both issues are totally different from each other, I have added images [here](https://github.com/flutter/flutter/issues/146750) for that issue.

The [issue](https://github.com/flutter/flutter/issues/74014) you mentioned, not worked in my case. I have tried all the solutions posted there.

Below you can see the behavior for this issue that when I pick from the list, the image have the bottle on RHS but when it appears on screen using Image Widget, the bottle shifted to LHS.

**Comment by darshankawar** [comment] 2024-04-16 05:54
Thanks for the update @ItsArsalanAziz 
I tried with image_picker [plugin example](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) running on iOS physical device OS 15.3.1 with which I didn't see the reported behavior.

<img width="342" alt="Screenshot 2024-04-16 at 11 22 31 AM" src="https://github.com/flutter/flutter/assets/67046386/7e6bb7d4-e62c-48ff-8f93-9ff3ea9d7fd1">

Can you try the same at your end using plugin example and  check if using it, you still get reported behavior or not ?
If not, please provide us runnable complete but minimal reproducible code sample (ex: main.dart) that we can directly use to verify the issue further. Also, provide iOS device you are using which shows the issue.

**Comment by ItsArsalanAziz** [comment] 2024-04-16 13:10
```
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: "Test",
      home: MainApp(),
    );
  }
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  _pickImage(BuildContext context, src) {
    ImagePicker().pickImage(source: src).then((value) async {
      if (value != null) {
        showDialog(
          context: context,
          builder: (context) {
            return Center(
              child: Image.file(
                File(value.path),
                height: 300.0,
                width: 300.0,
                fit: BoxFit.cover,
              ),
            );
          },
        );
      }
    }).onError((err, stackTrace) {
      debugPrint(err.toString());
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            GestureDetector(
              onTap: () => _pickImage(context, ImageSource.gallery),
              behavior: HitTestBehavior.opaque,
              child: const Text(
                'Pick from Gallery',
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontFamily: 'Roboto',
                  color: Colors.blue,
                  fontSize: 16,
                ),
              ),
            ),
            const SizedBox(height: 30),
            GestureDetector(
              onTap: () => _pickImage(context, ImageSource.camera),
              behavior: HitTestBehavior.opaque,
              child: const Text(
                'Capture from Camera',
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontFamily: 'Roboto',
                  color: Colors.blue,
                  fontSize: 16,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```



Above is the simplest code, by running it with the below image you can see the rotation issue. Kindly check it on latest IOS device and use only the front camera, as I have already , mentioned that this issue occurs on front camera. For your kind information, I am using iPhone 13 pro max and this issue is also occurs in other latest IOS devices too.

**Comment by darshankawar** [comment] 2024-04-17 06:18
Thanks for the update. Although I don't have iPhone 13 pro max, I tried the code sample on iPhone 6s with which using camera and gallery, both times, the images was shown as expected using front camera.

<img width="339" alt="Screenshot 2024-04-17 at 11 47 52 AM" src="https://github.com/flutter/flutter/assets/67046386/165f09a5-f0e6-4fbd-94f4-c5f65842820a">
<img width="341" alt="Screenshot 2024-04-17 at 11 47 58 AM" src="https://github.com/flutter/flutter/assets/67046386/db002401-55b8-45d1-a02c-f13d32d30c45">

I tried on latest stable version.

**Comment by ItsArsalanAziz** [comment] 2024-04-17 08:30
https://github.com/flutter/flutter/assets/104122442/7db2d043-9eb0-4360-89b2-283ecfdb61cb

You can see clearly that I have used the official image_picker example in 13 pro max and used only front camera to reproduce it. I have iPhone 7 plus and 13 pro max, and in both this issue occurs. Kindly capture image from only front camera in this example app.

**Comment by darshankawar** [comment] 2024-04-18 05:58
> Kindly capture image from only front camera in this example app.

I used front camera while using your example app with which I didn't get the reported behavior on iphone I tried. 
I am wondering since this is occuring using camera which is being used underlying in image_picker package, whether you are hitting this https://github.com/flutter/flutter/issues/27650

**Comment by ItsArsalanAziz** [comment] 2024-04-19 11:57
@darshankawar this issue persists across every iOS device I've. I've tested on the following devices: iPhone 7 Plus, iPhone 12 Mini, iPhone 13, and iPhone 13 Pro Max

To get the reported behavior in iPhone 6s, as you said it works fine on 6s, I've arranged it and checked using the example app from image_picker, where this issue also occurs. In the below video, you can see the behavior clearly, and in the end of the video, you can see the device info too.

https://github.com/flutter/flutter/assets/104122442/1b2edc28-1b41-4157-8cf6-973b594a2f03

**Comment by darshankawar** [comment] 2024-04-22 05:31
I tried on iPhone 13 pro max simulator running iOS 15.3 version but wasn't able to replicate.


https://github.com/flutter/flutter/assets/67046386/d96e3dd0-6293-4bad-98f1-15433f694bc6


Also, as previously stated, tried on iphone 6s device on which as well, I wasn't able to replicate the reported behavior.

Based on the report, it seems to be device + OS specific, so labeling it for team's input / tracking.

**Comment by jmagman** [comment] 2024-04-24 21:35
@ItsArsalanAziz, please take a moment to read out see our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md), which requires kind and actively welcoming behavior.  Your last comment was neither.

**Comment by ItsArsalanAziz** [comment] 2024-04-25 05:34
@jmagman apologies for the kind of behavior but look into the matter as I clearly mentioned the issue that is not device-specific but platform-specific. I have checked in more than 6 different IOS physical devices and it generates in every device. @darshankawar marked it as a device-specific issue which is hard to understand.

**Comment by darshankawar** [comment] 2024-04-25 06:36
@ItsArsalanAziz 
You are correct. It doesn't seem to be device specific so I will remove that label. I was finally able to replicate this on iPhone 6s device with front camera as shown below:


https://github.com/flutter/flutter/assets/67046386/c83d3bb2-09ba-4e7b-a3e4-efa201cf76a8

I compared it with native iOS camera with which same behavior occurs using front camera:

https://github.com/flutter/flutter/assets/67046386/f76a56b9-889e-48c5-9627-cd551bd7e7c3


In both videos, you can observe that when we open front camera, the cupboard is to the right, when we take picture, in preview you'll see it on left which is same behavior in native iOS and Flutter.

This indicates it is how native iOS front camera works that you can check on the range of devices you mentioned and compare with Flutter's image_picker or camera.

**Comment by ItsArsalanAziz** [comment] 2024-04-25 06:59
@darshankawar thank you, will there be any fix for this in Flutter's image_picker in upcoming release?

**Comment by darshankawar** [comment] 2024-04-25 13:03
The current behavior is in sync with native iOS, so I am not sure if the fix is in scope for the plugin to be made.
Since image_picker under the hood uses camera, I suggest you to follow-up in https://github.com/flutter/flutter/issues/27650 which is similar  as your request.
Closing for now. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2024-04-25 13:03 UTC
Labels: platform-ios, p: image_picker, package, team-ios

**Comment by stuartmorgan** [comment] 2024-04-25 14:24
This isn't actually a duplicate of #27650, since `camera` and `image_picker` have fundamentally different code. `camera` is a wrapper around the low-level OS camera APIs, and does not involve any system UI. There's a lot more opportunity to customize behaviors at that level.

`image_picker` is a wrapper around a very high-level system-provide UI control. The only things the plugin can change about the resulting UI are those that the OS specifically provides (which is basically [this](https://developer.apple.com/documentation/photokit/phpickerconfiguration)). I don't see any way to control the behavior of the camera UI in that configuration, which means that the functionality requested here cannot be implemented in this plugin.

Given that, removing the duplicate label, but leaving the issue closed. Clients who need to customize the capture experience would need to build their own UI around `camera` or a similar plugin, rather than using `image_picker`.

**Comment by jmagman** [comment] 2024-04-25 21:27
What @stuartmorgan said.

When taking a picture with the front camera, iOS automatically mirrors it. This is built into Apple's `UIImagePickerController` API. The preview of the image (the view where it says "Retake" and "Use Photo" is also part of `UIImagePickerController`). You may also notice that when you use the native iOS camera app, this behavior also occurs. In conclusion, this is not an issue with `image_picker` or Flutter but the expected behavior.

**Comment by ItsArsalanAziz** [comment] 2024-04-26 05:43
@jmagman this might be the default behavior you are right, but it works fine in other platforms. As in my case, this behavior is a glitch which is the reason why I opened this issue.
