### ISSUE TITLE
web

### ISSUE THREAD

**Issue by rmasonh18** [flutter/flutter#57879] opened 2020-05-24 00:58 UTC
I just tried to install flutter on my macbook pro and it will not install stating a git: fatal" origin/beta or origin/dev { flutter channel bete | flutter channel dev } is not a commit and a branch <beta | dev> cannot be created from it. Switching channels failed with error code 128.

**Comment by pthevenet** [comment] 2020-05-24 16:59
I got the same error after installing flutter via git on linux

```sh
git clone https://github.com/flutter/flutter.git -b stable --depth 1
./flutter/bin/flutter doctor
./flutter/bin/flutter channel beta
```

Output of last command:
```
Switching to flutter channel 'beta'...
git: fatal: 'origin/beta' is not a commit and a branch 'beta' cannot be created from it
Switching channels failed with error code 128.
```

**Comment by jonahwilliams** [comment] 2020-05-24 18:09
Duplicate of https://github.com/flutter/flutter/issues/18532

Flutter needs tags to validate its version. I recommend either downloading from the website or doing a full clone

**Closed by jonahwilliams** 2020-05-24 18:09 UTC
