### ISSUE TITLE
Firebase Database on orderByChild / orderByKey returns in random order

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#19389] opened 2018-07-15 14:26 UTC
`firebase_database: 1.0.2`

## Steps to Reproduce

Run a simple Flutter app:
https://gist.github.com/dotdoom/5180eb27084afb3b71db44f2201c6877

Most important part is (for history purposes):

```dart
(await FirebaseDatabase.instance
            .reference()
            .child(subpath)
            .orderByChild('year')
            .limitToFirst(3)
            .onValue
            .first)
        .snapshot
        .value
        .values
        .forEach((v) => debugPrint(v['year'].toString()));
```

The output is indeed the first 3 entries of a sorted list, but the entries themselves are not sorted:

```
I/flutter ( 6096): Sorted years:
I/flutter ( 6096): 1856
I/flutter ( 6096): 1867
I/flutter ( 6096): 1564
```

`limitToFirst` does not affect the order and is only to demonstrate that Firebase server gets the correct request.

I suspect there might be some issue when [transferring data between Java and Dart](https://github.com/flutter/plugins/blob/cd4829a6cf3afcf687fd064f18a028b519644d66/packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java#L185) where the map ordering is lost. Unfortunately it's buried too deep for me to find quickly, so I hope someone with more experience in the MethodChannel mechanism can help me out. The type of the map in Flutter app is `_InternalLinkedHashMap` which IIUC is supposed to be ordered.

## Logs

```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/artem/pkg/flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /home/artem/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /home/artem/pkg/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/artem/pkg/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by alamboley** [comment] 2018-07-19 16:54
Having exactly the same issue `orderByChild` just seems to be ignored.

I tried things like this but without chance:
```dart
FirebaseDatabase.instance.reference().child("users").orderByChild("score").once().then((DataSnapshot snapshot) {

      final value = snapshot.value as Map;
      for (final key in value.keys) {
        print(value[key]);
      }
});
```
The list is not ordered. At the moment I've no choice than doing it in the front side:
```dart
Map<dynamic, dynamic> map = snapshot.value;
List<dynamic> list = map.values.toList()..sort((a, b) => b['score'].compareTo(a['score']));
```

It seems @collinjackson is mentionned when a Firebase Database issue is raised!

**Comment by dotdoom** [comment] 2018-07-29 09:14
The same is happening when using `orderByKey`.

**Comment by dancingbannana** [comment] 2018-08-02 20:43
Did anyone find a fix yet?

**Comment by lukepighetti** [comment] 2018-08-21 16:39
Hey guys, this has been a wont fix from people in the Dart world from day one as far as I can tell. the default Map in Dart does not maintain its insertion order like it does in Javascript. There are maps in Dart that can achieve this but it seems like it is rarely used. Perhaps someone on the team could correct me. But yes, having maps return their Firebase sort like they do in Javascript would be VERY VERY very VERY nice.

**Comment by zoechi** [comment] 2018-08-21 16:54
@lukepighetti I haven't seen a comment stating that this won't be fixed. 
It seems resources for plugin work are a bit short currently. 
Might just be because of vacation season.

**Comment by lukepighetti** [comment] 2018-08-21 17:09
I didn't mean that from the team, but the general community response is "its not sorted because maps aren't sorted"

**Comment by zoechi** [comment] 2018-08-21 17:16
That's probably just because the first naive implementation missed this case and no free resources were available to fix it yet.

**Comment by ffeu** [comment] 2018-12-07 12:57
I'm having the same with **iOS** with `firebase_database` `1.0.5`, feels like I'm doing something wrong, but seriously haven't being able to find if/what it is.

**Comment by ffeu** [comment] 2018-12-07 13:20
By the way, I was debugging this plugin and the problem does not seem to relay on the message channel mechanism. According to my testing, in iOS, the plugin already receives it out of order and the item's order received is sent through the message channel consistently maintaining the order.

**Comment by dotdoom** [comment] 2018-12-07 18:07
If you think there's something wrong with the way you're doing it, I suggest asking on StackOverflow. If you are sure you are doing it right and Flutter is wrong on iOS, giving an example of your data structure and code (see first post of this thread) could help.

**Comment by fvisticot** [comment] 2018-12-17 21:19
I have the same issue sorting using "sortByChild". order is not correct !

**Comment by lukepighetti** [comment] 2018-12-17 22:34
What's interesting is that if you're pulling from Realtime Database and its an array (only sequential integers for keys) it will return with the order preserved as a list. But if you get a map the order is all jumbled up.

**Comment by dotdoom** [comment] 2019-01-05 11:53
> the default Map in Dart does not maintain its insertion order like it does in Javascript

@lukepighetti how did you arrive to this conclusion? The documentation states that the [default implementation is LinkedHashMap](https://api.dartlang.org/stable/2.1.0/dart-core/Map/Map.html) (and [was in Dart 1](https://api.dartlang.org/stable/1.12.0/dart-core/Map/Map.html)) which indeed guarantees the order.

On the other hand, HashMap in Java is unordered, and - thanks to *now* opensource Android Firebase SDK - we can see it is exactly what's used in [snapshot.getValue](https://github.com/firebase/firebase-android-sdk/blob/c627b48e40d3eedbb3a342bba61bf9a4b50088f9/firebase-database/src/main/java/com/google/firebase/database/snapshot/ChildrenNode.java#L122) which is [consumed by firebase_database plugin](https://github.com/flutter/plugins/blob/c989956d1cd15bd2a894a42aa1a8e212f29eb8ab/packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java#L406) (android version).

Thanks to https://github.com/flutter/flutter/issues/19389#issuecomment-445230632 by @ffeu which helped realize that MethodChannel is not where the things get broken.

Re https://github.com/flutter/flutter/issues/19389#issuecomment-448024840 about ordered arrays: in that `getValue()` method above there is also an answer why arrays are always ordered - the data is read from `children` (which is ordered) and stored in a list, discarding unordered HashMap value :tada:

**Comment by lukepighetti** [comment] 2019-01-05 16:52
@dotdoom Perhaps I read that somewhere and repeated it here.

**Comment by collinjackson** [comment] 2019-01-07 15:24
It appears to me that this is working as intended -- if the native side gives us an unordered collection, it's not the plugin's job to order it. Please let me know if I'm mistaken

**Closed by collinjackson** 2019-01-07 15:24 UTC
Labels: p: firebase, p: firebase_database, p: first party, plugin

**Comment by dotdoom** [comment] 2019-01-07 15:55
@collinjackson correct. Now we're in a situation where the plugin doesn't provide access to appropriate native SDK methods, which supply data in the order requested.

We can continue tracking missing implementation in https://github.com/flutter/flutter/issues/20524 or https://github.com/flutter/flutter/issues/20745.

**Comment by Saifallak** [comment] 2019-06-27 12:21
so any updates on this ?

**Comment by collinjackson** [comment] 2019-06-27 21:13
I would be happy to consider pull requests that improve this situation.

**Comment by kroikie** [comment] 2019-10-13 19:01
@dotdoom

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/753. Any further collaboration will be done there.

**Comment by Alexei-Suzdalenko** [comment] 2021-05-01 12:49
I have it problem !!!
    var db = FirebaseDatabase.instance.reference().child('users').child(FirebaseAuth.instance.currentUser.uid.toString()).child('categories').orderByChild('id');

 await db.once().then((DataSnapshot snapshot) {
       snapshot.value.forEach((key, values) {
        final category = Category(name: values['category'], date: values['date'], id: values['id']);
        categoryList.add(category);
      });

**Comment by Alexei-Suzdalenko** [comment] 2021-05-01 12:50
How can I use multiple order by in real time database flutter to order data by specific field? [duplicate]

**Comment by michaelNabil316** [comment] 2021-07-31 11:31
i get an **solution** not the best but it work good with me 
after i get data i sort it using flutter code not firebase
//this code is work with my code
postsList.add(postWidget); //adding the coming data from firebase to a list 
postsList .sort((a, b) => a.postDate.compareTo(b.postDate)); //sort by the time that i upload it with the post

**Comment by michaelNabil316** [comment] 2021-07-31 11:36
i get an solution not the best but it work good with me 🎉✌
after i get data i sort it using flutter code not firebase
//this code is work with my project
postsList.add(postWidget); //adding the coming data from firebase to a list
postsList .sort((a, b) => a.postDate.compareTo(b.postDate)); //sort by the time that i upload it with the post
