### ISSUE TITLE
MultiLine Text not centered in Carouselslider

### ISSUE THREAD

**Issue by HoBill** [flutter/flutter#59749] opened 2020-06-18 08:33 UTC
Having a simple container with three Carouselslider with text each - cut&paste - the middle slider does not center the text if its multi-line.

source code:

@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        color: Color(0xe6e4da),
        width: MediaQuery.of(context).size.width,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            carouselSlider = CarouselSlider(
              options: CarouselOptions(
                height: 50,
                initialPage: 0,
                enlargeCenterPage: true,
                viewportFraction: 0.4,
                reverse: false,
                autoPlay: false,
                enableInfiniteScroll: true,
                autoPlayInterval: Duration(seconds: 2),
                autoPlayAnimationDuration: Duration(milliseconds: 2000),
                scrollDirection: Axis.horizontal,
              ),
              items: textlist.map((tt) {
                return Builder(
                  builder: (BuildContext context) {
                    return Container(
//                      width: MediaQuery.of(context).size.width,
                        margin: EdgeInsets.symmetric(horizontal: 5.0),
                        width: 180,
                        height: 30,
                        decoration: BoxDecoration(
                          color: Colors.green,
                        ),
                        child: Align(
                            alignment: Alignment.center,
                            child: Text(
                              tt,
                              style: TextStyle(
                                  fontFamily: 'Moderation',
                                  color: Colors.white,
                                  fontSize: 16),
                              textAlign: TextAlign.center,
                            )));
                  },
                );
              }).toList(),
            ),
            carouselSlider = CarouselSlider(
              options: CarouselOptions(
                height: 80,
                initialPage: 0,
                enlargeCenterPage: true,
                viewportFraction: 0.4,
                reverse: false,
                autoPlay: false,
                enableInfiniteScroll: true,
                autoPlayInterval: Duration(seconds: 2),
                autoPlayAnimationDuration: Duration(milliseconds: 2000),
                scrollDirection: Axis.horizontal,
              ),
              items: textlist2.map((tt) {
                return Builder(
                  builder: (BuildContext context) {
                    return Container(
//                      width: MediaQuery.of(context).size.width,
                        margin: EdgeInsets.symmetric(horizontal: 5.0),
                        width: 180,
                        height: 80,
                        decoration: BoxDecoration(
                          color: Colors.green,
                        ),
                        child: Align(
                            alignment: Alignment.center,
                            child: Text(
                              tt,
                              style: TextStyle(
                                  fontFamily: 'Moderation',
                                  fontSize: 16,
                                  color: Colors.black54),
                            )));
                  },
                );
              }).toList(),
            ),
            carouselSlider = CarouselSlider(
              options: CarouselOptions(
                height: 80,
                initialPage: 0,
                enlargeCenterPage: true,
                viewportFraction: 0.4,
                reverse: false,
                autoPlay: false,
                enableInfiniteScroll: true,
                autoPlayInterval: Duration(seconds: 2),
                autoPlayAnimationDuration: Duration(milliseconds: 2000),
                scrollDirection: Axis.horizontal,
              ),
              items: textlist3.map((tt) {
                return Builder(
                  builder: (BuildContext context) {
                    return Container(
//                      width: MediaQuery.of(context).size.width,
                        margin: EdgeInsets.symmetric(horizontal: 5.0),
                        width: 180,
                        height: 80,
                        decoration: BoxDecoration(
                          color: Colors.green,
                        ),
                        child: Align(
                            alignment: Alignment.center,
                            child: Text(
                              tt,
                              style: TextStyle(
                                  fontFamily: 'Moderation',
                                  color: Colors.white,
                                  fontSize: 16),
                              textAlign: TextAlign.center,
                            )));
                  },
                );
              }).toList(),
            ),
          ],
        ),
      ),
    );
  }
}

What I do see:
![Screenshot1](https://user-images.githubusercontent.com/67095314/84997471-ee315f80-b14e-11ea-993b-abbc07452f58.jpg)

while the middle - black text on one line is centered, the multiline text is not. Nevertheless in the lower carouselslider it does work as expected (and it is not the textcolor making a difference)

Any idea how to accomplish the centered - mulitline text?

**Comment by TahaTesser** [comment] 2020-06-18 12:58
Hi @HoBill 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/serenader2014/flutter_carousel_slider/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-18 12:58 UTC
