### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The directory is not empty., errno = 145

### ISSUE THREAD

**Issue by makule-crypto** [flutter/flutter#87004] opened 2021-07-25 09:40 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: The directory is not empty.
, errno = 145
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:469:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:468:12)
#6      FlutterWebSdk.updateInner (package:flutter_tools/src/flutter_cache.dart:187:16)
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:677:11)
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:546:24)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1144:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version
    10.0.19043.1110], locale en-KE)
    • Flutter version 2.2.3 at
      C:\Users\goody\Downloads\Compressed\flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11
      -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK
    version 30.0.3)
    • Android SDK at C:\Users\goody\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jdk-13.0.1\bin\java.exe
    • Java version Java(TM) SE Runtime Environment (build 13.0.1+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK
      licenses.
      See
      https://flutter.dev/docs/get-started/install/windows#android-setu
      p for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/windows#android-setu
      p for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\goody\AppData\Local\Programs\Microsoft VS
      Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • SM A107F (mobile) • R9WN415L45J • android-arm    • Android 10
      (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      91.0.4472.164
    • Edge (web)        • edge        • web-javascript • Microsoft Edge
      91.0.864.64

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: d79295af24c3ed621c33713ecda14ad196fd9c31
### Plugins
firebase_auth-0.14.0+9
firebase_core-0.4.5
firebase_core_web-0.1.1+2

**Comment by darshankawar** [comment] 2021-07-26 10:53
Closing this as duplicate of https://github.com/flutter/flutter/issues/64410

**Closed by darshankawar** 2021-07-26 10:53 UTC
Labels: in triage
