### ISSUE TITLE
App crashes when displaying a text beginning with space on right-to-left localization

### ISSUE THREAD

**Issue by Helliconia** [flutter/flutter#41968] opened 2019-10-04 08:09 UTC
If an app displays a text that starts with a blank space with a right-to-left localization (for example arabic) it instantly crashes without exception message.
For example:
```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      locale: Locale('ar', ''),
      supportedLocales: [Locale('ar', '')],
      home: Scaffold(
        body: Center(
          child: Text(' Hi'),
        ),
      ),
    );
  }
}
```
Changing the localization to "en" will prevent the crash.

Below is the flutter doctor output:
```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.740], locale de-AT)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Proxy Configuration
[√] Connected device (2 available)

• No issues found!
```

**Comment by Helliconia** [comment] 2019-10-04 08:26
BTW an easy workaround is to use trim() on strings.

**Comment by HansMuller** [comment] 2019-10-04 23:39
This appears to be a duplicate of #39553, see https://github.com/flutter/flutter/issues/39553#issuecomment-531376793, which has been fixed.

CC @jason-simmons

**Comment by KirolousNashaat** [comment] 2019-10-12 08:24
is this fixed on stable channel yet !??

**Comment by iapicca** [comment] 2020-01-17 07:44
Hi @Helliconia  
are you still experiencing this issue with the latest stable version of flutter?
thank you

**Comment by iapicca** [comment] 2020-06-05 12:55
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-06-05 12:55 UTC
Labels: a: internationalization, a: typography, framework, severe: crash, waiting for customer response
