### ISSUE TITLE
TextField isn't usable with Flutter 2.8.0 beta on iPhone 15 simulator

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#94140] opened 2021-11-24 03:08 UTC
TextField isn't usable on the iOS 15 iPhone simulator with Flutter beta 2.8.0-3.2.pre.

## Steps to Reproduce

Running the following code on an iOS 15 iPhone simulator results in a an unusable TextField.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _controller = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('Please enter a thing:'),
              TextField(controller: _controller),
            ],
          ),
        ),
      ),
    );
  }
}
```

<details>

<summary>Logs</summary>

## Version

```console
$ flutter --version
Flutter 2.8.0-3.2.pre • channel beta • https://github.com/flutter/flutter
Framework • revision 2901cd7208 (5 days ago) • 2021-11-18 11:15:09 -0800
Engine • revision bcc2b7f12c
Tools • Dart 2.15.0 (build 2.15.0-268.18.beta)
```

## Flutter doctor

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 2.8.0-3.2.pre, on macOS 12.1 21C5031d darwin-x64, locale en)
    • Flutter version 2.8.0-3.2.pre at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 2901cd7208 (5 days ago), 2021-11-18 11:15:09 -0800
    • Engine revision bcc2b7f12c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • EFDF3255-2EA1-4762-92A7-A1A4712A9950 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)   • macos                                • darwin-x64     • macOS 12.1 21C5031d darwin-x64
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

</details>

**Comment by domesticmouse** [comment] 2021-11-24 03:17
FYI @csells

**Comment by HansMuller** [comment] 2021-11-24 05:57
CC @LongCatIsLooong

**Comment by TahaTesser** [comment] 2021-11-24 15:06
@HansMuller @LongCatIsLooong 

### Descroiption
This looks like an issue input from the raw keyboard. The issue can be reproduced on a physical or simulator when using the physical keyboard instead of the soft keyboard.

### 25th Oct
Initial regression was introduced in https://github.com/flutter/flutter/pull/92441, which includes an Engine PR https://github.com/flutter/engine/pull/29108 related to iOS input 

<img width="1055" alt="Screenshot 2021-11-24 at 16 58 56" src="https://user-images.githubusercontent.com/48603081/143262028-1ebe20a0-fd85-40a2-8f92-3eec8fb0ac6b.png">

| Good commit  | Regression commit |
| --------------- | --------------- |
| https://github.com/flutter/flutter/commit/1daae0b0ae0e819019100415e53e574e5d154dbd  | https://github.com/flutter/flutter/commit/6434f8e84accdda85c9f507f93b01ddb95caebc3 |

### 21 days ago 
### Then the issue persisted until it was fixed late from a PR https://github.com/flutter/engine/pull/29464 in another engine https://github.com/flutter/flutter/pull/92977

<img width="1072" alt="Screenshot 2021-11-24 at 17 05 51" src="https://user-images.githubusercontent.com/48603081/143263082-bc0126d3-f8b9-4175-ae34-a22a59d278d9.png">


| Bug commit  | Fix commit |
| --------------- | --------------- |
| https://github.com/flutter/flutter/commit/607d7934c728afef9a6cc8d329b6f50b3c479466  | https://github.com/flutter/flutter/commit/136592ae79e7ed5dee251e712b2f37a6bd10b8ae |

**Comment by LongCatIsLooong** [comment] 2021-11-24 16:46
https://github.com/flutter/engine/pull/29464 was the fix. It should be relatively safe to cherrypick and the pull request only removes code.

**Comment by devoncarew** [comment] 2021-11-30 19:17
@HansMuller (and @LongCatIsLooong); when was this regression introduced? What's the impact of not taking it for stable? We have a very high bar for this week - can you talk about taking it now vs. delaying to consider it for a batch or cherry picks after the stable release?

**Comment by LongCatIsLooong** [comment] 2021-11-30 21:05
The regression was introduced in flutter/engine#29108. It prevents **iOS** hardware keyboard events from being properly sent to flutter text input fields, I'd expect it will affect these: people
1. developers that use a simulator to debug their apps (there's an easy workaround, you can choose to use the onscreen keyboard in the simulator, but it's still going to be an annoyance).
2. actual users that connect a hardware keyboard to their ipads. It's a definitely not the best user experience if they're forced to use the onscreen keyboard instead, and developers would have to find a way to tell them about this workaround.

The patch itself should be relatively safe. flutter/engine#29108 replaced a quirk in the ios text input plugin with a proper implementation, but there was a workaround for that quirk in the code that wasn't removed at the time. The fix simply removed that and the code changes only affect hardware keyboard events handling (which wasn't working prior to the fix so it almost can't be worse unless the fix would introduce a crash. I've been using ios simulator for debugging flutter apps since then and haven't seen anything strange so far).

**Comment by maheshmnj** [comment] 2021-12-22 09:19
This is no longer reproducible on `stable 2.8.1` or `master, 2.9.0-1.0.pre.93`, TextField works with both physical and virtual keyboard on ios 15.


https://user-images.githubusercontent.com/31410839/147068226-883bf9bb-5e28-4633-9326-c4b35dc222b0.mov



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • A55680BB-E46F-425E-B803-ACB8DEA8A239 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.93, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.93 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1be7f1ea56 (7 days ago), 2021-12-14 22:14:07 -0500
    • Engine revision e444009bf4
    • Dart version 2.16.0 (build 2.16.0-109.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • A55680BB-E46F-425E-B803-ACB8DEA8A239 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

Closing as fixed.

**Closed by maheshmnj** 2021-12-22 09:19 UTC
Labels: a: text input, platform-ios, framework, f: material design, regression identified, cp: 2.8, cp: 2.8 completed
