### ISSUE TITLE
There are multiple heroes that share the same tag within a subtree even when I'm not using any heroes!

### ISSUE THREAD

**Issue by Cyberavater** [flutter/flutter#85706] opened 2021-07-01 16:33 UTC
## Steps to Reproduce

Repo link: https://github.com/Cyberavater/state_management_practice
1. Run it on the web
2. Click on the second page

3. ... 

**Expected results:** 

**Actual results:** 

<details>

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
Here is the subtree for one of the offending heroes: Hero
  tag: <default FloatingActionButton tag>
  state: _HeroState#22d2d
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
packages/flutter/src/widgets/heroes.dart 320:11                                                                            <fn>
packages/flutter/src/widgets/heroes.dart 330:16                                                                            inviteHero
packages/flutter/src/widgets/heroes.dart 350:11                                                                            visitor
packages/flutter/src/widgets/framework.dart 6070:23                                                                        visitChildren
...
====================================================================================================
```

</details>

My suspicion is that, it's related to bloc. Also, I'm relatively new, but block isn't the one who is actually throwing the issue so, I opened here.

**Comment by Cyberavater** [comment] 2021-07-02 06:58
Can anyone please look at this issue? I tried to look for a solution but it seems there isn't one.

**Comment by TahaTesser** [comment] 2021-07-02 15:46
Hi @Cyberavater 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample without third-party packages, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Cyberavater** [comment] 2021-07-02 15:49
> minimal code sample without third-party packages

That might take some time, but in the meantime check this issue, seems like it's very related,
https://stackoverflow.com/questions/66038738/there-are-multiple-heroes-that-share-the-same-tag-within-a-subtree-error-without

**Comment by TahaTesser** [comment] 2021-07-05 07:38
Hi @Cyberavater 
To better address the issue 

> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample without third-party packages, and complete `flutter run --verbose` logs running the minimal code sample?
> Thank you

**Comment by Cyberavater** [comment] 2021-07-07 07:29
> without third-party packages

If I remove flutter_bloc, the issue goes away, so...
Does this mean I should file an issue in their repo?

**Comment by TahaTesser** [comment] 2021-07-07 07:47
Hi @Cyberavater 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository.
Closing, as this isn't an issue with Flutter itself.  If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-07 07:47 UTC
Labels: in triage
