### ISSUE TITLE
Flutter Material 3 Badge in iOS 

### ISSUE THREAD

**Issue by rddewan** [flutter/flutter#119221] opened 2023-01-26 06:06 UTC
Material 3 Badge widget loads find in Android but in iOS it does not show in full by default. We need to adjust the largeSize to make it fully visable
```
class CartBadgeWidget extends ConsumerWidget {
  final Widget? child;
  const CartBadgeWidget({Key? key, this.child}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final badgeCount = ref.watch(cartControllerProvider.select((value) => value.badgeCount));
    
    return Badge(         
      isLabelVisible: badgeCount > 0 ? true : false,
      label: badgeCount < 1 ? const SizedBox.shrink() : Text('$badgeCount'),
      child: child,
    )
    ;
  }
}
```
![Screenshot 2566-01-26 at 1 04 28 PM](https://user-images.githubusercontent.com/13164167/214768817-4fa7dbc0-5026-4c44-ad54-57aabe7d2eba.png)
![Screenshot 2566-01-26 at 1 05 05 PM](https://user-images.githubusercontent.com/13164167/214768881-f7b632e0-5cf1-4465-aa56-c11d7373348f.png)

**Comment by exaby73** [comment] 2023-01-26 13:44
Hello @rddewan. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by rddewan** [comment] 2023-02-14 11:15
@exaby73  hello here is the sample project https://github.com/rddewan/flutter-material3-demo

```
richard@MAQEs-MacBook-Pro material3_demo % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-arm64, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.75.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category
```

**Comment by exaby73** [comment] 2023-02-14 13:30
Hey @rddewan. I cannot reproduce this issue. Here's the simplified code sample I am testing with:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      bottomNavigationBar: NavigationBar(
        destinations: const [
          NavigationDestination(
            icon: Badge(
              largeSize: 20,
              label: Text('9'),
              child: Icon(Icons.add),
            ),
            label: 'Add',
          ),
          NavigationDestination(
            icon: Icon(Icons.add),
            label: 'Add',
          ),
          NavigationDestination(
            icon: Icon(Icons.add),
            label: 'Add',
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by rddewan** [comment] 2023-02-15 07:55
@exaby73 Hi
You have set the largeSize, try to comment the `// largeSize: 20`
```
 NavigationDestination(
            icon: Badge(
              // largeSize: 20,
              label: Text('9'),
              child: Icon(Icons.add),
            ),
            label: 'Add',
          ),
```

**Comment by exaby73** [comment] 2023-02-15 08:59
That doesn't really change the output

<img width="300" src="https://user-images.githubusercontent.com/50555895/218980717-7d722299-21b3-447c-855d-d5b06b9dd278.png">

**Comment by rddewan** [comment] 2023-02-15 09:32
@exaby73  are you in Android ? It works fine in android , I am only facing issue in iOS

**Comment by rddewan** [comment] 2023-02-15 10:48
@exaby73 I think you haven't enable Materil3 `useMaterial3: true,`  try to run with Materl3 enabled

**Comment by exaby73** [comment] 2023-02-15 14:37
It does not change the outcome. Can you test my code sample on your device? Also, which simulator are you using?

**Comment by rddewan** [comment] 2023-02-16 04:38
@exaby73  I am using your code. You can see the difference in iOS and Android 
![Screenshot 2566-02-16 at 11 34 08 AM](https://user-images.githubusercontent.com/13164167/219269539-4b4e467a-f93d-46af-8ba6-c18ae3a4937b.png)

**Comment by huycozy** [comment] 2023-02-16 05:58
@rddewan I also can not reproduce the issue on the latest `stable` and `master` channels. Verified on `iPhone 14 Pro Max, iOS 16.1 (emulator)`.

<details>
<summary>Demo</summary>

![Screenshot 2023-02-16 at 12 54 14](https://user-images.githubusercontent.com/104349824/219280704-ad4cdc5e-7ab1-4c6c-a75c-f1476f119ee9.png)

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      bottomNavigationBar: NavigationBar(
        destinations: const [
          NavigationDestination(
            icon: Badge(
              label: Text('9'),
              child: Icon(Icons.add),
            ),
            label: 'Add',
          ),
          NavigationDestination(
            icon: Icon(Icons.add),
            label: 'Add',
          ),
          NavigationDestination(
            icon: Icon(Icons.add),
            label: 'Add',
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (17 hours ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Users/huynq/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

```bash
[!] Flutter (Channel master, 3.8.0-13.0.pre.51, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.8.0-13.0.pre.51 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efde350812 (15 minutes ago), 2023-02-15 21:49:06 -0500
    • Engine revision a966cf878f
    • Dart version 3.0.0 (build 3.0.0-240.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Can you try upgrading to the latest Flutter versions and retry?

**Comment by rddewan** [comment] 2023-02-17 08:11
@huycozy Thank you i found the issue . It's working fine with xcode 14.2 iOS 16.2. Not sure if it's a iOS 16 or xcode 14 issue

**Comment by huycozy** [comment] 2023-02-17 11:04
@rddewan Thanks for the update. 

It could be an emulator's issue (I'm not sure). Closing the issue as solved on your side. Once you see the issue again, please write a comment and we will reopen it for further discussion.

**Closed by huycozy** 2023-02-17 11:04 UTC
Labels: in triage
