### ISSUE TITLE
'Take a picture using the camera' page issue

### ISSUE THREAD

**Issue by stephenhuey** [flutter/flutter#56305] opened 2020-04-06 16:43 UTC
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:

Tried to deploy this example to iOS 13.3.1 but I'm seeing this error: 

Failed to send request: {"jsonrpc":"2.0","id":"87","method":"getStack","params":{"isolateId":"isolates/3518422606420823"}}
Failed to send request: {"jsonrpc":"2.0","id":"86","method":"getMemoryUsage","params":{"isolateId":"isolates/3518422606420823"}}
Failed to send request: {"jsonrpc":"2.0","id":"88","method":"getObject","params":{"isolateId":"isolates/3518422606420823","objectId":"classes/3876"}}

Flutter 1.12.13+hotfix.8 with Android Studio 3.6 and Xcode 11.3.1 on Mac OS X Mojave 10.14.6 (so my tools are recent and I'm using the latest package dependencies mentioned in the tutorial.

**Comment by sfshaza2** [comment] 2020-05-04 17:32
If something turns up that affects our documentation on flutter.dev, please file an issue!

**Comment by sfshaza2** [comment] 2020-05-04 17:33
Oops, didn't mean to close this.

**Comment by VladyslavBondarenko** [comment] 2020-05-05 07:14
Hi @stephenhuey 
I checked this code sample with `iOS 13.4.5` with current stable `1.12.13+hotfix.8` and dev `1.18.0-8.0.pre` and can't see the error.
are you using the last plugin versions, right? `path_provider: ^1.6.7`, `camera: ^0.5.7+4`.
what command are you running?
could you provide log of running it with `--verbose` flag?

**Comment by VladyslavBondarenko** [comment] 2020-05-27 11:55
I can't reproduce it. 

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (6 available)
    • Redmi Note 7              • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.5
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server                • web-server                               • web-javascript • Flutter Tools
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

I hope it's fixed, closing.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of `flutter doctor -v`  please.

**Closed by VladyslavBondarenko** 2020-05-27 11:55 UTC
Labels: in triage, waiting for customer response
