### ISSUE TITLE
App doesn't launch after upgrading to Android SDK 33

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#105764] opened 2022-06-10 07:52 UTC
## Steps to Reproduce

1. Set `compileSdkVersion` and `targetSdkVersion` to `33`
2. Set Kotlin version to `1.7.0`
3. Set Gradle version to `gradle-7.5-rc-1-bin`
4. Open an emulator with API 33
5. Run `flutter run -v`

**Expected results:** The debug app launches

**Actual results:** Debug app seems to be installed but not automatically launched (opening the app manually seems to work fine)

<details>
  <summary>Logs</summary>

The logs get stuck like this:

```
[  +30 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=<elided>/io.flutter.embedding.android.FlutterActivity (has extras) }

           Error type 3
           Error: Activity class {<elided>/io.flutter.embedding.android.FlutterActivity} does not exist.
[        ] Waiting for observatory port to be available...

```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-DE)
    • Flutter version 3.0.1 at <elided>
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at <elided>
    • Platform android-33, build-tools 33.0.0
    • Java binary at: 
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at <elided>
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at <elided>

[✓] Android Studio (version 2021.2)
    • Android Studio at <elided>
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at <elided>
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-06-10 12:43
I can reproduce this on stable. Though this seems to be fixed on master. Closing the issue as fixed. If you disagree, please comment and we can open it again.

**Comment by Zazo032** [comment] 2022-06-10 12:54
Could the fix be cherry picked to stable? Thanks

**Closed** 2022-06-10 13:46 UTC
Labels: r: fixed

**Comment by exaby73** [comment] 2022-06-10 14:04
@Zazo032 That's up to the Flutter team to decide :)

**Comment by GaryQian** [comment] 2022-08-23 18:39
This issue is already fixed in master and beta channels. Since we have yet to default target 33 on stable, it may make the most sense to just use the beta or master channels for now until we bump everything to target API 33. If you want to stay on stable, the manual workaround is to just tap the icon for the app to launch it.
