### ISSUE TITLE
RichTextEditor

### ISSUE THREAD

**Issue by toilathor** [flutter/flutter#130474] opened 2023-07-13 03:37 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I found that creating a RichTextEditor widget that is supported by google's wait is necessary because the libraries available on pub.dev are not fully optimized while the demand for using RichTextEditor is relatively large.

Its essential feature is the creation of paragraphs containing the most basic editing styles. Can generate to other formats such as HTML, quill, ...

Hope it gets answered soon.

### Proposal

[untitled.webm](https://github.com/flutter/flutter/assets/54834124/3ae56328-9e5a-4d4a-9626-bc9643319aab)

**Comment by danagbemava-nc** [comment] 2023-07-13 07:15
Closing this as a duplicate of https://github.com/flutter/flutter/issues/12675.

**Closed by danagbemava-nc** 2023-07-13 07:15 UTC
Labels: in triage
