### ISSUE TITLE
StreamBuilder stuck in connectionState.waiting when Stream is null

### ISSUE THREAD

**Issue by YawarOsman** [flutter/flutter#114320] opened 2022-10-30 19:15 UTC
I have this code down below, i want to get a list of `Users` through a `UserChats` table. it works perfectly but there is an issue, i have a tab bar and when i click another tab and back to previous tab the `StreamBuilder` goes to `waiting` state and will never came back to `done` state (never came back with the milk 😬)

This is my code:

```
import 'dart:async';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:socialnetwork/models/UserChats.dart';
import 'package:socialnetwork/submodels/appBars/allMessagesAppBar.dart';
import '../models/Users.dart';
import '../provider/data.dart';
import '../provider/log.dart';
import 'userMessages.dart';

class AllMessages extends StatefulWidget {
  const AllMessages({Key? key}) : super(key: key);

  @override
  State<AllMessages> createState() => _AllMessagesState();
}

class _AllMessagesState extends State<AllMessages> {
  final StreamController<List<UserChats>?> _usersYouChatedWith =
      StreamController<List<UserChats>?>.broadcast();

  Future<Users>? _eachUserYouChatedWith = null;

  @override
  void initState() {
    super.initState();
    getUsersYouChatedWith();
  }

  void getUsersYouChatedWith() async {
    try {
      final yourId = context.read<Data>().userData.userId;
      await Amplify.DataStore.query(UserChats.classType,
              where: UserChats.USERIDSENDER.eq(yourId))
          .then((value) {
        _usersYouChatedWith.sink.add(value.isNotEmpty ? value : null);
      });
    } catch (e) {
      debugPrint(e.toString());
    }
  }

  Future<Users> getEachUserYouChatedWith(String userId) async {
    final eachUser = await Amplify.DataStore.query(Users.classType,
        where: Users.USERID.eq(userId));
    return eachUser.first;
  }

  @override
  void dispose() {
    super.dispose();
    _usersYouChatedWith.close();
  }

  @override
  Widget build(BuildContext context) {
    return Consumer2<Data, Log>(
        builder: (context, data, log, child) => DefaultTabController(
              length: 3,
              child: Scaffold(
                appBar: PreferredSize(
                  preferredSize: Size.fromHeight(80),
                  child: AllMessagesAppBar(),
                ),
                body: TabBarView(children: [
                  people(data),
                  gruops(data),
                  requests(data),
                ]),
              ),
            ));
  }

  Padding people(Data data) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 13, vertical: 5),
      child: Column(
        children: [
          Expanded(
              child: StreamBuilder(
                  stream: _usersYouChatedWith.stream,
                  builder: (context, snapshot) {
                    if (snapshot.connectionState == ConnectionState.waiting) {
                      return Center(child: CircularProgressIndicator());
                    }
                    if (!snapshot.hasData) {
                      return Center(
                        child: Text('You\'ve not messaged to anyone yet...'),
                      );
                    }
                    final messages = snapshot.data as List;
                    _eachUserYouChatedWith = getEachUserYouChatedWith(
                        snapshot.data!.first.userIdReciever);
                    return ListView.builder(
                        itemCount: messages.length,
                        itemBuilder: (context, index) => Text(messages.content);
                  })),
        ],
      ),
    );
  }


}

```

This is `flutter doctor -v` output:

<details>
<summary>Output Sample</summary>

[✓] Flutter (Channel stable, 3.3.6, on macOS 11.7 20G817 darwin-x64, locale en-US)
    • Flutter version 3.3.6 on channel stable at /Users/yara/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (5 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/yara/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/yara/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A233
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 36055F8C-CDAA-4E9D-9DC2-28CFF3839EA0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.7 20G817 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by darshankawar** [comment] 2022-10-31 11:44
@YawarOsman 
Your issue is better suited for support channels like StackOverflow, so please ask the same there.
The code sample you provided is not minimal and contains community plugin code so we can't properly analyze as what could be causing the behavior you are reporting.
If you think the issue is in the framework, please provide a complete minimal reproducible code sample without third party plugin that shows the behavior and I'll reopen this issue.

Closing for now.

**Closed by darshankawar** 2022-10-31 11:44 UTC
Labels: in triage

**Comment by YawarOsman** [comment] 2022-11-05 10:17
> 

here is a minimal code example: https://stackoverflow.com/questions/74326762/streambuilder-stuck-in-connectionstate-waiting-in-flutter

**Comment by iapicca** [comment] 2022-11-05 23:50
> > 
> 
> here is a minimal code example: https://stackoverflow.com/questions/74326762/streambuilder-stuck-in-connectionstate-waiting-in-flutter

@YawarOsman 
fixed for you [sample](https://dartpad.dartlang.org/?id=52e8e2ef8bad97f21dc91fa420dcec0e)

**Comment by YawarOsman** [comment] 2022-11-13 09:23
> > > 
> > 
> > 
> > here is a minimal code example: https://stackoverflow.com/questions/74326762/streambuilder-stuck-in-connectionstate-waiting-in-flutter
> 
> @YawarOsman I fixed for you in this [sample](https://dartpad.dartlang.org/?id=52e8e2ef8bad97f21dc91fa420dcec0e) and answered in SO

I really appreciate your efforts, but is this case that hard or something that needs all that code and multiple StreamBuilders to get the work done ??? can't it be a little simpler ?
