### ISSUE TITLE
Regression in average frame build time for Linux_android_textfield_perf__e2e_summary

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#90061] opened 2021-09-14 15:28 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1627405143&end=1631621316&keys=X1eb3c60bab5cd2e049ad4b0ba89ed0cb&requestType=0&xbaroffset=25788

Three commits in the range:

[Skip the drawShadow call in a MergeableMaterial with zero elevation](https://github.com/flutter/flutter/commit/eb5ae39f139115930cd3113bed67269996924030)
[Use async timeline events for the phases of the scheduler binding](https://github.com/flutter/flutter/commit/2004afae06706cafe0a6ed148bbb86b0123b6f31)
[Don't display empty tooltips (Tooltips with empty message property)](https://github.com/flutter/flutter/commit/7736b9eef03124c46418dea6718e6c412a375a00)

/cc @jason-simmons @bambinoua @dkwingsmt

**Comment by jason-simmons** [comment] 2021-09-14 19:15
It looks like this started with https://github.com/flutter/flutter/commit/2004afae06706cafe0a6ed148bbb86b0123b6f31

That PR changed how the frame timing events are logged to the timeline.  I'm not sure exactly why that change to the timeline is causing a difference in the metrics for this benchmark.  But the actual frame build process was not changed, so I don't think it reflects a real change in performance.

**Comment by jason-simmons** [comment] 2021-09-16 03:55
The benchmark regressed because https://github.com/flutter/flutter/commit/2004afae06706cafe0a6ed148bbb86b0123b6f31 converted the "Frame" and "Animate" timeline events from synchronous to async.  These events are logged by the framework for every frame.

The Dart `Timeline.startSync` API for synchronous events will skip the event if the Dart timeline stream is not enabled:
    https://github.com/dart-lang/sdk/blob/main/sdk/lib/developer/timeline.dart#L107

However, the `TimelineTask.start` API for async events does not do this.

The Dart timeline stream is not enabled in these e2e benchmarks.  So with https://github.com/flutter/flutter/commit/2004afae06706cafe0a6ed148bbb86b0123b6f31 the benchmark started recording events that were previously omitted.

@a-siva @zanderso Would it be safe to change `TimelineTask` in the Dart SDK to check `_isDartStreamEnabled`?

Beyond that I noticed some other small inefficiencies:
* https://github.com/flutter/flutter/commit/2004afae06706cafe0a6ed148bbb86b0123b6f31 is allocating a new `TimelineTask` for each `Frame`/`Animate` event.  It could reuse one instance for all these events.
* `TimelineTask.start` in the Dart SDK is always making a copy of the arguments map.  But that is not needed if the event has no parent or filterKey.

**Comment by a-siva** [comment] 2021-09-16 16:53
> @a-siva @zanderso Would it be safe to change `TimelineTask` in the Dart SDK to check `_isDartStreamEnabled`?
> 

I think that should be possible to mirror the implementations in Timeline.startSync and Timeline.instantSync over to
TimelineTask.start and TimelineTask.instant (.oe. pushing null values onto the stack).

// cc @bkonyi

**Comment by jason-simmons** [comment] 2021-09-16 23:35
This also means that these timeline events are being logged in release mode.

The `_hasTimeline` flag in `sdk/lib/developer/timeline.dart` is `true` even in release mode.  So without the `_isDartStreamEnabled` check, the "Frame"/"Animate" events (and any other use of `TimelineTask`) will spend time writing the events to the timeline buffer.

@a-siva Is there a way to disable the Dart timeline APIs entirely when running in release mode?

https://github.com/dart-lang/sdk/blob/main/sdk/lib/developer/timeline.dart sets `_hasTimeline` based on the `dart.developer.timeline` environment variable.  Should the engine be controlling that somehow?

**Comment by a-siva** [comment] 2021-09-17 00:21
> @a-siva Is there a way to disable the Dart timeline APIs entirely when running in release mode?
> 
> https://github.com/dart-lang/sdk/blob/main/sdk/lib/developer/timeline.dart sets `_hasTimeline` based on the `dart.developer.timeline` environment variable. Should the engine be controlling that somehow?

It used to be always disabled in release mode before this change https://dart-review.googlesource.com/c/sdk/+/90100 was done to make it on in product mode for Fuchsia. The engine could set the dart.developer.timeline variable to false or maybe we could change the code in timeline.dart to do this new stuff only if Platform.isFuchsia is true.

**Comment by bkonyi** [comment] 2021-09-17 14:17
I've updated the `TimelineTask` logic to also check `_isDartStreamEnabled` in [this CL](https://dart-review.googlesource.com/c/sdk/+/213780).

**Comment by goderbauer** [comment] 2021-09-29 21:44
It looks like this benchmark went back down right around https://github.com/flutter/flutter/pull/90421, but later went back up and now appears to be even higher. Commits right arround where it jumps include:

[Roll Engine from eb94e4f595b6 to 694664037380 (6 revisions)](https://github.com/flutter/flutter/commit/e72b294704e8a148c24d4a1496feaca2cf7931b2)
[Roll Plugins from d2c6c4314412 to a5cd0c3aea70](https://github.com/flutter/flutter/commit/38a19cee18c462de4ade5baf7ad920b35e50ea14)
[Roll Engine from 694664037380 to 5ef2faeb10af (3 revisions)](https://github.com/flutter/flutter/commit/1881311268022a49f7fdf7e631b60c203f44deb1)

https://flutter-flutter-perf.skia.org/e/?begin=1627405143&end=1632948484&keys=X1eb3c60bab5cd2e049ad4b0ba89ed0cb&requestType=0&xbaroffset=25788

**Comment by a-siva** [comment] 2021-09-30 17:51
The dart changes in the two engine roll changes posted above are
dart-lang/sdk@65184a9 [cfe] Don't serialize an empty show/hide clause by Chloe Stefantsova · 7 days ago
dart-lang/sdk@1197e15 [CFE] Enable avoid_void_async lint by Jens Johansen · 7 days ago
dart-lang/sdk@6207d1d Revert "Stop using available suggestions for already imported libraries" by Konstantin Shcheglov · 7 days ago
dart-lang/sdk@57e71e3 Fix RemoveUnusedField when some SourceRange(s) being removed are fully covered. by Konstantin Shcheglov · 7 days ago
dart-lang/sdk@19b7a3e [infra] Use dart-lang/co19 issue links in co19 rolls by Alexander Thomas · 7 days ago
dart-lang/sdk@651d6e0 Add null-unsoundness check to print's `object.toString()` result. by Lasse R.H. Nielsen · 7 days ago

None of these changes are in the VM and I feel the Dart rolls may not have contributed to this.

**Comment by jason-simmons** [comment] 2021-10-02 00:52
The second change in the benchmark is happening for the same reason as https://github.com/flutter/flutter/issues/90883#issuecomment-930682438

**Comment by goderbauer** [comment] 2021-10-04 17:10
I am gonna close this bug than since the new regression is tracked in #90883.

**Closed by goderbauer** 2021-10-04 17:10 UTC
Labels: severe: regression, framework, engine, severe: performance, passed first triage, perf: speed, P2
