### ISSUE TITLE
Gallery release builds increased in size

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13618] opened 2017-12-15 22:48 UTC
The change in https://github.com/flutter/flutter/pull/13567 (originally https://github.com/flutter/flutter/pull/12944) dramatically increased the size of the gallery release builds.

cc @szakarias

**Comment by mravn-google** [comment] 2017-12-16 21:24
AFAIK, the PR establishes a stepping stone towards getting rid of `app.flx`, involving the temporary duplication of `app.flx` content into a `flutter_assets` folder. It should go away as soon as we transition asset-reading code to the new structure. Assigning @szakarias for now; we'll provide an update Monday.

**Comment by Hixie** [comment] 2017-12-16 22:51
I thought that might be it. We should probably put this behind a flag so that people can still release apps from master in the meantime though (we have a lot of customers who are shipping apps and expect master, and certainly alpha, to be in a shippable state).

**Comment by szakarias** [comment] 2017-12-18 15:33
app.flx removed on Android in #13647. The PR doing the same on iOS is here #13648 but not landed due to red tree caused by Windows bot recipe error. Also pending is #13649 which updates our example iOS projects.

**Comment by mravn-google** [comment] 2017-12-18 19:32
Closed per #13647, #13648, and #13649.

**Closed by mravn-google** 2017-12-18 19:32 UTC
Labels: performance, regression, ⚠ TODAY
