### ISSUE TITLE
Web-Server device no longer available

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#72645] opened 2020-12-19 10:27 UTC
## Use case

The web-server option which used to be available no longer shows up in `flutter devices` and therefore is no longer an option in IntelliJ.

I need this because I haven't found a way to set flags in the chrome runner, and I need the insecure localhost flag enabled.

## Proposal

Re-enable the web server device in the listing of devices.

I know that it is still supported because I can run `flutter run -d web-server` on the terminal.

<details>
<summary>Flutter Doctor results</summary> 

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64, locale en-CA)
    • Flutter version 1.25.0-8.1.pre at /Users/morgan/devtools/flutter
    • Framework revision 8f89f6505b (3 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/morgan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/morgan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode 12.1.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • iPhone (mobile) • ce658d8044f32c23abe2d077b3793e8c5a9f8663 • ios            • iOS 14.3
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2020-12-21 10:04
Hi @rmtmckenzie 
This to be a proposal for `intellij` 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-21 10:04 UTC

**Comment by rmtmckenzie** [comment] 2020-12-21 16:21
I can open an issue there, but I have a pretty strong feeling it's just going to be bounced back here. The flutter tool used to report both `Chrome (web)` and `Server (web)` devices but now only reports `Chrome (web)`.


```
> flutter devices

2 connected devices:

iPhone (mobile) • ce658.................................. • ios            • iOS 14.3
Chrome (web)    • chrome                                   • web-javascript • Google Chrome 87.0.4280.88
```

**Comment by tayo** [comment] 2020-12-22 04:18
I'm also seeing this.  Specifically the [Get Started](https://flutter.dev/docs/get-started/web#set-up) instructions for Flutter are no longer correct.  Following these instructions, I only see the Chrome(web) device.  The web server does not exist.

**Comment by TahaTesser** [comment] 2020-12-22 09:15
@rmtmckenzie  @tayo 
Interesting, this is by design. Implemented in https://github.com/flutter/flutter/pull/71491
It should work fine with the command and you can still make a proposal for the Flutter plugin to still give option if they agree. 
Since this is by design and verified by PR, no issues here
Thank you
