### ISSUE TITLE
can't run on ios9 after create new app

### ISSUE THREAD

**Issue by xkubow** [flutter/flutter#5543] opened 2016-08-23 08:25 UTC
## Steps to Reproduce
Following [getting-started](https://flutter.io/getting-started/), created myapp with command _flutter create myapp_ then hit flutter run. Probably same as issue #3448.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/kubo/Library/flutter
    • Framework revision 9a0a0d9903 (11 days ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /Users/kubo/Library/Android/sdk
    • Platform android-24, build-tools 24.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.37

## Logs and Crash Reports
  31 ms • /Users/kubo/Library/Android/sdk/platform-tools/adb devices -l
   0 ms • Exit code 0 from: /Users/kubo/Library/Android/sdk/platform-tools/adb devices -l
   1 ms • List of devices attached
   7 ms • idevice_id -h
   4 ms • which idevice_id
   0 ms • Exit code 0 from: which idevice_id
   0 ms • /usr/local/bin/idevice_id
   6 ms • /usr/local/bin/idevice_id -l
   1 ms • Exit code 0 from: /usr/local/bin/idevice_id -l
  26 ms • xcode-select --print-path
   0 ms • Exit code 0 from: xcode-select --print-path
   0 ms • /Applications/Xcode.app/Contents/Developer
 108 ms • xcodebuild -version
   0 ms • Exit code 0 from: xcodebuild -version
   0 ms • Xcode 7.3.1
          Build version 7D1014
  13 ms • xcrun clang
 128 ms • /usr/bin/xcrun simctl list --json devices
 625 ms • /usr/bin/defaults read /Users/kubo/Documents/FlutterProjects/myapp/ios/Runner/Info CFBundleIdentifier
   0 ms • Exit code 0 from: /usr/bin/defaults read /Users/kubo/Documents/FlutterProjects/myapp/ios/Runner/Info CFBundleIdentifier
   0 ms • com.yourcompany.myapp
  10 ms • Stopping app 'Runner.app' on iPhone 6 Plus.
   1 ms • Running lib/main.dart on iPhone 6 Plus...
   0 ms • Building Runner.app for D52CC780-6C85-4AE2-BAC4-865CFB6A541F.
   2 ms • tail -n 0 -F /Users/kubo/Library/Logs/CoreSimulator/D52CC780-6C85-4AE2-BAC4-865CFB6A541F/system.log
  56 ms • Building build/app.flx
 349 ms • tail -n 0 -F /private/var/log/system.log
   7 ms • which zip
 130 ms • Encoding zip file to build/app.flx
 271 ms • zip -q /Users/kubo/Documents/FlutterProjects/myapp/build/app.flx fonts/MaterialIcons-Regular.ttf fonts/Roboto-Regular.ttf fonts/Roboto-Italic.ttf fonts/Roboto-T…
   0 ms • Exit code 0 from: zip -q /Users/kubo/Documents/FlutterProjects/myapp/build/app.flx fonts/MaterialIcons-Regular.ttf fonts/Roboto-Regular.ttf fonts/Roboto-Italic.ttf fonts/Roboto-Thin.ttf fonts/Roboto-ThinItalic.ttf fonts/Roboto-Light.ttf fonts/Roboto-LightItalic.ttf fonts/Roboto-Medium.ttf fonts/Roboto-MediumItalic.ttf fonts/Roboto-Bold.ttf fonts/Roboto-BoldItalic.ttf fonts/Roboto-Black.ttf fonts/Roboto-BlackItalic.ttf fonts/RobotoCondensed-Regular.ttf fonts/RobotoCondensed-Italic.ttf fonts/RobotoCondensed-Light.ttf fonts/RobotoCondensed-LightItalic.ttf fonts/RobotoCondensed-Bold.ttf fonts/RobotoCondensed-BoldItalic.ttf AssetManifest.json FontManifest.json LICENSE
   0 ms • Built build/app.flx.
 221 ms • /usr/bin/xcrun simctl get_app_container booted com.yourcompany.myapp
  12 ms • /usr/bin/killall Runner
  12 ms • Using engine artifacts dir: /Users/kubo/Library/flutter/bin/cache/artifacts/engine/ios
 104 ms • xcodebuild -version
   0 ms • Exit code 0 from: xcodebuild -version
   1 ms • Xcode 7.3.1
          Build version 7D1014
   2 ms • Trying to resolve native pub services.
   0 ms • Looking for YAML at 'flutter.yaml'
   0 ms • No services specified in the manifest
   0 ms • Found 0 service definition(s).
   0 ms • Copying service frameworks to '/Users/kubo/Documents/FlutterProjects/myapp/ios/Frameworks'.
   2 ms • Creating service definitions manifest at 'ios/ServiceDefinitions.json'
12864 ms • /usr/bin/env xcrun xcodebuild clean build -configuration Release ONLY_ACTIVE_ARCH=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/kubo/Documents/FlutterProjects/myapp/ios/build -sdk iphonesimulator -arch x86_64
4526 ms • [SYS LOG] Aug 23 10:11:56 Jans-iMac Mail[49844]: Stream 0x7f9ed8e42780 is sending an event before being opened
   3 ms • [DEVICE LOG] Aug 23 10:12:00 Jans-iMac routined[26558]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
67089 ms • routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
103144 ms • [SYS LOG] Aug 23 10:13:07 Jans-iMac syslogd[47]: ASL Sender Statistics
125156 ms • [SYS LOG] Aug 23 10:14:50 Jans-iMac WindowServer[157]: send_datagram_available_ping: pid 308 failed to act on a ping it dequeued before timing out.
64603 ms • [SYS LOG] Aug 23 10:16:56 Jans-iMac Mail[49844]: Stream 0x7f9edb7a5d60 is sending an event before being opened
   0 ms • [DEVICE LOG] Aug 23 10:18:00 Jans-iMac routined[26558]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
   0 ms • routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
   0 ms • [DEVICE LOG] Aug 23 10:18:00 Jans-iMac syslogd[26555]: ASL Sender Statistics
235471 ms • syslogd: ASL Sender Statistics
 568 ms • [SYS LOG] Aug 23 10:21:56 Jans-iMac Mail[49844]: Stream 0x7f9edb6222e0 is sending an event before being opened
72683 ms • [SYS LOG] Aug 23 10:21:56 Jans-iMac accountsd[338]: AIDA Notification plugin running

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment] 2016-08-23 15:21
I don't see any errors in that log.  Did it successfully install on the device, but fail to run?  Or neither? A common error is provisioning, but I would expect to see an error from xcode in that case.

CC @chinmaygarde @danrubel @johnmccutchan

**Comment by eseidelGoogle** [comment] 2016-08-23 15:22
I'm confused by seeing configuration "Release" and iOSSimulator both in the logs.  @tvolkert is that an expected configuration?  I presume that "release" has nothing to do with our engine release?

**Comment by johnmccutchan** [comment] 2016-08-23 16:27
@chinmaygarde Could this be the same cacoa pod build step issue that I ran into locally?

**Comment by tvolkert** [comment] 2016-08-23 16:35
That Release has nothing to do with engine release -- it's the Xcode build config passed here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/mac.dart#L124

**Comment by xkubow** [comment] 2016-08-24 06:26
@eseidelGoogle looks like neither. Build in Xcode is working so I expect that the provision profiles are ok.

**Comment by eseidelGoogle** [comment] 2016-08-24 14:50
@xkubow are you able to open ios/Runner.xcodeproj and run the flutter app from within XCode?

**Comment by xkubow** [comment] 2016-08-26 08:37
XCode error:

Build target Runner of project Runner with configuration Debug

PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/kubo/Library/Developer/Xcode/DerivedData/Runner-azkhspqcbykvpfaudxxrahwtwnkh/Build/Intermediates/Runner.build/Debug-iphonesimulator/Runner.build/Script-AB1344B0443C71CD721E1BB7.sh
    cd /Users/kubo/Documents/FlutterProjects/myapp/ios
    /bin/sh -c /Users/kubo/Library/Developer/Xcode/DerivedData/Runner-azkhspqcbykvpfaudxxrahwtwnkh/Build/Intermediates/Runner.build/Debug-iphonesimulator/Runner.build/Script-AB1344B0443C71CD721E1BB7.sh

diff: /Users/kubo/Documents/FlutterProjects/myapp/ios/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by xkubow** [comment] 2016-08-26 09:37
After removing pods it worked except the float button lost its add icon.

**Comment by collinjackson** [comment] 2016-08-26 15:40
I believe this is a duplicate of #5398, which was fixed in #5432.

**Closed by collinjackson** 2016-08-26 15:40 UTC
Labels: affects: tools, ⌺‬ platform-ios
