### ISSUE TITLE
flutter test --coverage stopped reporting property initializer lines as covered.

### ISSUE THREAD

**Issue by CaleyD** [flutter/flutter#28542] opened 2019-02-27 00:44 UTC
`flutter test —coverage` has regressed since v`1.0.0` and is now incorrectly reporting some lines (property initializers) as uncovered. 

## Steps to Reproduce

 create a file in the lib folder of a package called class_under_test.dart with the following contents

```dart
 class ClassUnderTest {
  const ClassUnderTest({this.value});
  final String value;
  static const String _className = 'ClassUnderTest';

  @override
  String toString() => '$_className(value: $value)';
} 
```

create a test to verify the `toString` method of this class:

```dart
 import 'package:flutter_test/flutter_test.dart';
import 'package:entities/class_under_test.dart';

void main() {
  test('reproduce coverage bug', () {
    expect(const ClassUnderTest(value: 'hello').toString(), equals('ClassUnderTest(value: hello)'));
  });
} 
```

 Execute the `flutter test --coverage` command to run the test with coverage. 

 See the generated `info.lcov` file reports line 4 (`static const String _className = 'ClassUnderTest';`) as uncovered when its value is definitely validated by the test..  

```
 SF:lib/class_under_test.dart
DA:2,1
DA:4,0
DA:6,1
DA:7,2
LF:4
LH:3
end_of_record
```

## Flutter Doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/caldavis/flutter
    • Framework revision 8661d8aecd (12 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/caldavis/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.rc.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (1 available)
    • iPhone XR • B65D20EC-6A80-4137-AA01-CED713750A42 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by devoncarew** [comment] 2019-02-27 06:00
cc @cbracken @a-siva

**Comment by jason-simmons** [comment] 2019-03-02 00:51
The change in coverage behavior started with https://github.com/dart-lang/sdk/commit/7e81f56ad7e919b4cf2b610ca9bc0ff63e8e79cb

**Comment by ZichangG** [comment] 2019-03-07 17:09
4ec72c1eb11f37b1ce4046eeb01c05f7e81629a9
The cl has been merged. Can you do a cherry pick to fix the issue?

**Comment by ZichangG** [comment] 2019-03-07 17:39
@kf6gpe Previous CL is a candidate for cherry picking.

**Comment by kf6gpe** [comment] 2019-03-08 18:08
Thanks! We'll use that as the cherry-pick for our test.

**Comment by ZichangG** [comment] 2019-04-04 22:32
@kf6gpe Hi, Ray. I assigned you the issue. Can you close this issue if the problem is solved?

**Comment by kf6gpe** [comment] 2019-04-04 22:37
Ohj! Yes, we can close this. Thanks!

**Comment by dwach414** [comment] 2019-04-11 19:26
Why was this closed? This is not fixed on beta or master.

**Comment by masewo** [comment] 2019-09-08 12:35
@ZichangG Why was the fix not merged into master?

**Comment by a-siva** [comment] 2019-09-13 10:43
This is related to https://github.com/dart-lang/sdk/issues/38284

**Comment by ZichangG** [comment] 2019-09-18 17:27
https://github.com/dart-lang/sdk/commit/3731cfdef9daafac6739569f3d5135f0cc66bedb 
The fix has been landed. It will be rolled into flutter later.

**Closed by ZichangG** 2019-09-18 17:27 UTC
Labels: customer: marketplace, dependency: dart, severe: regression, tool

**Comment by masewo** [comment] 2019-09-20 20:53
static const fields are now ignored by test coverage so they are not marked as not covered anymore.
Flutter Channel master, v1.10.6-pre.27

**Comment by hjJunior** [comment] 2019-11-03 21:35
I'm using `Channel stable, v1.9.1+hotfix.6` and I keep having this problem

**1. I tried defining a class with static const**

![image](https://user-images.githubusercontent.com/10780132/68092245-ed6de680-fe67-11e9-9796-37c3a355bd71.png)

```dart
void main() {
  test('should register const CIRCULAR_LOADING_KEY', () {
    expect(LoadingButtonKeys.CIRCULAR_LOADING_KEY, Key('CIRCULAR_LOADING_KEY'));
  });
}
```

**2. I used just const** 
![image](https://user-images.githubusercontent.com/10780132/68092297-64a37a80-fe68-11e9-883f-dfb8fac38ea6.png)

```dart
  test('should register SECURE_STORAGE_USER_TOKEN_KEY const', () {
    expect(SECURE_STORAGE_USER_TOKEN_KEY, 'SECURE_STORAGE_USER_TOKEN_KEY');
  });
```

**Comment by ZichangG** [comment] 2019-11-04 04:53
To be more specific, previous pr only ignores initialization of Static const field.
For 1st case, function call to Key() marks the line as visited. FYI, VM uses callsites data to keep track of coverage.
