### ISSUE TITLE
red heart emoji is rendered without color.

### ISSUE THREAD

**Issue by p1318k** [flutter/flutter#138697] opened 2023-11-20 05:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Red heart emoji (\u2764\uFE0F) rendered without red color on Text or TextField widget.
It is reproducible building and running macOS test app on macOS Ventura(14.1.1).

### Expected results

Red heart emoji rendered with red color.

### Actual results

Red heart emoji rendered without color.

### Code sample

<details><summary>Code sample</summary>

```dart
const Text(
              'red heart emoji (\u2764\uFE0F) is not rendered correctly.',
            ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="801" alt="screenshot" src="https://github.com/flutter/flutter/assets/5835658/cbafc7f3-b862-4c5f-9506-ff500182f6f2">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-11-20 14:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/100964. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-11-20 14:11 UTC
Labels: in triage
