### ISSUE TITLE
Problem with transition inside PageRoute when initialRoute is not equal to '/'

### ISSUE THREAD

**Issue by andyduke** [flutter/flutter#27635] opened 2019-02-07 10:59 UTC
If the `initialRoute` in `MaterialApp` is not equal to '/', but points to another screen, when returning from another screen (via `Navigator.pop` or by pressing the Back button on the phone), the `secondaryAnimaton` in the `PageRoute` for the main screen will not play.

If I push another screen through `Navigator.pushNamed` and return to the main screen - the `secondaryAnimation` for the main screen works.

### Reproduce
Below is the code that reproduces the problem and screenshots of how it works and how it should work.
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  final Map<String, WidgetBuilder> routes = {
    '/':              (_) => HomePage(),
    '/page2':         (_) => Page2(),
  };

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Page Transition Demo',
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        scaffoldBackgroundColor: Colors.indigo[100],
      ),
      initialRoute: '/page2',
      onGenerateRoute: (RouteSettings settings) {
        if (routes.containsKey(settings.name)) {
          return CoverUpZoomOutPageRoute(builder: routes[settings.name], settings: settings);
        }
      },
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          border: Border.all(color: Colors.indigo, width: 1.5),
        ),

        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[

              Padding(
                padding: const EdgeInsets.all(20.0),
                child: Text('Home'),
              ),

              RaisedButton(
                child: Text('Page 2'),
                onPressed: () {
                  Navigator.of(context).pushNamed('/page2');
                },
              ),

            ],
          ),
        ),

      ),
    );
   }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          border: Border.all(color: Colors.indigo, width: 1.5),
        ),

        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[

              Padding(
                padding: const EdgeInsets.all(20.0),
                child: Text('Page 2'),
              ),

              RaisedButton(
                child: Text('Back'),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),

            ],
          ),
        ),

      ),
    );
  }
}

class CoverUpZoomOutPageRoute<T> extends PageRouteBuilder<T> {

  final WidgetBuilder builder;
  final Duration duration;

  CoverUpZoomOutPageRoute({
    Key key,
    @required this.builder,
    this.duration = const Duration(milliseconds: 3000), // Slow for better observation
    RouteSettings settings,
  }) :
    super(
      settings: settings,
      transitionDuration: duration,
      pageBuilder: (
        BuildContext context,
        Animation<double> animation,
        Animation<double> secondaryAnimation
      ) {
        return builder(context);
      },
      transitionsBuilder: (
        BuildContext context,
        Animation<double> animation,
        Animation<double> secondaryAnimation,
        Widget child
      ) {
        return CoverUpZoomOutPageTransition(
          child: child,
          primaryAnimation: animation,
          secondaryAnimation: secondaryAnimation,
        );
      },
    );

}

class CoverUpZoomOutPageTransition extends StatelessWidget {

  final Animation<double> primaryAnimation;
  final Animation<double> secondaryAnimation;
  final Widget child;

  CoverUpZoomOutPageTransition({
    Key key,
    @required this.child,
    this.primaryAnimation,
    this.secondaryAnimation,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var inAnimation = primaryAnimation;

    var outAnimation = secondaryAnimation;

    var outShadowTransition = DecoratedBoxTransition(
      position: DecorationPosition.foreground,
      decoration: outAnimation.drive(_outShadowTween),
      child: child,
    );

    var inTransition = SlideTransition(
      position: inAnimation.drive(_slideInTween),
      child: outShadowTransition,
    );

    var outTransition = ScaleTransition(
      scale: outAnimation.drive(ReverseTween(_scaleInTween)),
      child: inTransition,
    );

    return outTransition;
  }

  static Animatable<double> _scaleInTween = Tween<double>(
    begin: 0.8,
    end: 1.0,
  );

  static Animatable<Offset> _slideInTween = Tween<Offset>(
    begin: Offset(0.0, 1.0),
    end: Offset.zero,
  );

  static DecorationTween _outShadowTween = DecorationTween(
    begin: BoxDecoration(
      color: Color.fromRGBO(0, 0, 0, 0.0),
    ),
    end: BoxDecoration(
      color: Color.fromRGBO(0, 0, 0, 0.5),
    ),
  );

}
```

### How it work:
![flutter_01](https://user-images.githubusercontent.com/52318/52406849-c1435600-2adf-11e9-86ad-7cea0d482f6b.png)

### How it should work:
![flutter_02](https://user-images.githubusercontent.com/52318/52406881-d4eebc80-2adf-11e9-9bc9-d6f50f05175e.png)

### Flutter doctor
```
flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
    • Flutter version 1.0.0 at D:\.Flutter\flutter
    • Framework revision 5391447fae (10 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\.Flutter\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\.Flutter\android-sdk
    • Java binary at: D:\.Flutter\jdk\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] Connected device (1 available)
    • Custom • 192.168.20.101:5555 • android-x86 • Android 6.0 (API 23)

! Doctor found issues in 1 category.
```

**Comment by kangwang1988** [comment] 2019-02-07 15:39
@andyduke 
What's the difference between screenshot for 
`How it work:`
and `How it should work:`.

**Comment by andyduke** [comment] 2019-02-07 16:31
> @andyduke
> What's the difference between screenshot for
> `How it work:`
> and `How it should work:`.

When returning to the main screen, it should scale from 0.8 to 1.0 and the dim color should change the alpha channel from 0.5 to 0.0 but this does not happen. The secondaryAnimation does not work.

**Comment by kangwang1988** [comment] 2019-02-09 15:55
@andyduke 
Got it, thank you for making it clear.

**Comment by xster** [comment] 2019-02-14 02:33
@goderbauer to re-triage for route transitions.

**Comment by patelkrunal78** [comment] 2019-10-03 15:45
What you’re doing sounds somewhat like a BottomNavigationBar, so you might want to consider one of those instead of a Drawer.

However, having a single Scaffold and updating the body when the user taps a drawer item is a totally reasonable approach. You might consider a FadeTransition to change from one body to another.

Or, if you like using Navigator but don’t want the default slide animation, you can customize (or disable) the animation by extending MaterialPageRoute. Here’s an example of that:

Checkout Here Maybe You Will Find Your Solutionhttps://icetutor.com/question/replace-initial-route-in-materialapp-without-animation

**Comment by VladyslavBondarenko** [comment] 2020-05-28 13:29
I can't reproduce it with current stable.

<details>
 <summary>Summary Goes Here</summary>
 
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/nevercode/dev/flutter_stable
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

 
[✓] Connected device (1 available)            
    • Redmi Note 7 • 6345c469 • android-arm64 • Android 9 (API 28)

• No issues found!
```

</details>

Seems to be fixed. Closing.
@andyduke If you are disagree, comment and I'll reopen

**Closed by VladyslavBondarenko** 2020-05-28 13:29 UTC
Labels: f: routes, framework
