### ISSUE TITLE
[Add2App Android] Hotreload seems broken on latest Dev release

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#56957] opened 2020-05-12 01:04 UTC
In an Android Add2App scenario, doing a Hot reload seems to break, as this exception fires and nothing can be done anymore:

```
2020-05-11 20:58:46.867 15159-15344/ I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2020-05-11 20:58:46.867 15159-15344/ I/flutter: The following _CompileTimeError was thrown building MyApp(dirty):
2020-05-11 20:58:46.867 15159-15344/ I/flutter: 'package:my_app/main.dart': error: line 168 pos 12: Static call with invalid arguments: no
2020-05-11 20:58:46.867 15159-15344/ I/flutter: optional formal parameter named '$creationLocationd_0dea112b
2020-05-11 20:58:46.867 15159-15344/ I/flutter:     return MaterialApp(
```

**Comment by dannyvalentesonos** [comment] 2020-05-12 01:05
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.19.0-0.0.pre at /Users/danny.valente/Library/flutter/1.19.0-0.0.pre-dev
    • Framework revision a849daf283 (4 days ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

**Comment by dannyvalentesonos** [comment] 2020-05-12 01:59
I can repro with `1.18.0-11.0.pre`.

`1.18.0-dev.3.0-dev` does not have this problem.

**Comment by dannyvalentesonos** [comment] 2020-05-12 02:13
It also only happens on Android. My iOS device doesn't run into this problem.

**Comment by jonahwilliams** [comment] 2020-05-12 02:28
It looks like part of the application was built with track-widget-creation enabled and part wasn't. How are you building and debugging the application?

**Comment by dannyvalentesonos** [comment] 2020-05-12 04:05
Using option B from here: https://flutter.dev/docs/development/add-to-app/android/project-setup

Once the app runs, I open the flutter module project in Android Studio, and use Flutter attach to attach to the flutter instance running in my app. This hasn't changed for me in over a year and has always worked until now. Let me know if you need any other details.

**Comment by VladyslavBondarenko** [comment] 2020-05-12 15:03
@dannyvalentesonos 
I just tried with current dev `1.19.0-0.0.pre`.
Attached default module `flutter create -t module --org com.example flutter_module` to the sample app https://github.com/flutter/samples/tree/master/add_to_app/android_fullscreen and hot-reload is working.
Could you try if you are experiencing this exception when attaching default flutter module to your app/to this sample app?

**Comment by TahaTesser** [comment] 2020-05-12 15:22
Please try this [sample](https://github.com/tesserx/a2a-test)  and @VladyslavBondarenko mentioned, there is no issue

**Comment by dannyvalentesonos** [comment] 2020-05-12 17:04
@VladyslavBondarenko @TahaTesser 
I am attaching a very simple app, that is similar to my real app, and I can repro this with the same app I'm attaching.

Basically, I run ./build.sh inside the `flutter_module` directory.
Then I open the android project and build/run/install onto a device.
I then open the flutter_module in Android Studio, and using Flutter Attach from Android Studio, I repro the exact exception above when changing anything in the dart code and hot reloading.

**Comment by dannyvalentesonos** [comment] 2020-05-12 17:04
[Add2AppTest.zip](https://github.com/flutter/flutter/files/4617299/Add2AppTest.zip)

**Comment by VladyslavBondarenko** [comment] 2020-05-13 09:45
@dannyvalentesonos 
I can't reproduce the error with your project. Hot-reload and hot-restart are working. 

The only difference I made is added
```
include ':flutter_module'
project(':flutter_module').projectDir = new File('../../flutter_module')
```
to the settings.gradle in android project. And didn't delete .android dir (`flutter pub get` after `rm -rf build .android .ios .dart_tool`)

**Comment by dannyvalentesonos** [comment] 2020-05-13 12:49
@VladyslavBondarenko  Is there a reason you made that change? Can you please try it with no changes, as that's how it's documented in the Flutter documentation.

Also, are you specifically using `1.19.0-0.0.pre` or `1.18.0-dev.3.0-dev` to test? Maybe this was fixed on master if you're testing with master?

Thanks for looking into this!

**Comment by VladyslavBondarenko** [comment] 2020-05-13 13:42
@dannyvalentesonos 

I had flutter_module stuck on trying to attach

```
Waiting for a connection from Flutter on Redmi Note 7...
```

I looked at TahaTesser's sample https://github.com/tesserx/a2a-test/blob/master/Demo/settings.gradle to see what can be different.
Added these 2 lines and on the next attempt it connected. 

But now I tried again and I see that it's working and without these 2 lines. Sorry, never-mind.

I'm running with current dev `1.19.0-1.0.pre`.

Probably needs to be added also that I see this exception on the first hot-reload.

```
I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
    The following NoSuchMethodError was thrown building MyApp(dirty):
    No constructor 'MaterialApp.' with matching arguments declared in class 'MaterialApp'.
    Receiver: MaterialApp
    Tried calling: new MaterialApp.()
    Found: new MaterialApp.({Key key, GlobalKey<NavigatorState> navigatorKey, Widget home, Map<String,
    (BuildContext) => Widget> routes, String initialRoute, (RouteSettings) => Route<dynamic>
    onGenerateRoute, (String) => List<Route<dynamic>> onGenerateInitialRoutes, (RouteSettings) =>
    Route<dynamic> onUnknownRoute, List<NavigatorObserver> navigatorObservers, (BuildContext, Widget) =>
    Widget builder, String title, (BuildContext) => String onGenerateTitle, Color color, ThemeData
    theme, ThemeData darkTheme, ThemeMode themeMode, Locale locale,
    Iterable<LocalizationsDelegate<dynamic>> localizationsDelegates, (List<Locale>, Iterable<Locale>) =>
    Locale localeListResolutionCallback, (Locale, Iterable<Locale>) => Locale localeResolutionCallback,
    Iterable<Locale> supportedLocales, bool debugShowMaterialGrid, bool showPerformanceOverlay, bool
    checkerboardRasterCacheImages, bool checkerboardOffscreenLayers, bool showSemanticsDebugger, bool
    debugShowCheckedModeBanner, Map<LogicalKeySet, Intent> shortcuts, Map<Type, Action<Intent>>
    actions}) => MaterialApp
    Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
    be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
    When the exception was thrown, this was the stack:
    #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:204:5)
    #1      MyApp.build (package:add2app_test_module/main.dart)
    #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4580:28)
    #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
    #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
I/flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
    #6      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
    #7      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
    #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
    #9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1013:9)
    #10     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:822:7)
    (elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
```

But after hot-restart next hot-reloads work fine

**Comment by dannyvalentesonos** [comment] 2020-05-13 14:35
@VladyslavBondarenko Thanks, but I'm a little confused. Are you confirming that there is an issue? This wasn't causing me any problems with `1.18.0-dev.3.0-dev` or earlier.

**Comment by dannyvalentesonos** [comment] 2020-05-13 14:53
@VladyslavBondarenko  one more thing to note is that in the Add2App case, it's not always acceptable to need a hot-restart to get things working. In my case, I can't respawn a Flutter View unless the underlying models are cleaned up once that view goes away. In the case of this exception when running the Hot Reload, the view cannot be cleaned up correctly, and a Hot restart leaves my app in a broken state. A Hot Restart works for me only if the Fluter View is already gone and cleaned up.

**Comment by jonahwilliams** [comment] 2020-05-13 14:59
This issue is caused by an update we made to build aar to accept more build flags. As a result of this change, the default mode of --track-widget-creation was disabled in debug mode.

**Comment by dannyvalentesonos** [comment] 2020-05-13 15:09
Awesome, thanks @jonahwilliams !

**Comment by VladyslavBondarenko** [comment] 2020-05-13 15:12
@dannyvalentesonos 
I somewhy didn't check with some previous version before, but yes, I confirm that the exception isn't thrown with current stable

**Comment by dannyvalentesonos** [comment] 2020-05-13 15:49
@jonahwilliams Just also letting you know that we don't build using the aar method. We include the flutter project as part of our main app, as in Option B from that page I linked above. Will your change still fix this problem for us?

**Comment by jonahwilliams** [comment] 2020-05-13 15:55
Ahh, my mistake then I misread your post. As far as I know this is the only thing that has changed recently. fyi @jmagman @blasten .

**Comment by dannyvalentesonos** [comment] 2020-05-13 17:01
Thanks @jonahwilliams that gives me somewhere to start looking.

I see this in `flutter.gradle`

```
Boolean trackWidgetCreationValue = false
        if (project.hasProperty('track-widget-creation')) {
            trackWidgetCreationValue = project.property('track-widget-creation').toBoolean()
        }
```

Does this mean that now we have to set this property somewhere in our build process for debug builds? That feels a little cumbersome for us to track based on what kind of build we're doing, whereas it would make more sense for the flutter gradle build to do it for us.

**Comment by jonahwilliams** [comment] 2020-05-13 17:06
This flag has existed for at least 2 years, so its not clear to me what changed here. You don't need to pass it, but if you don't use it, then it should be disabled using `flutter attach --no-track-widget-creation`

**Comment by dannyvalentesonos** [comment] 2020-05-13 17:31
```
if (trackWidgetCreation != null) {
                args "-dTrackWidgetCreation=${trackWidgetCreation}"
            }
```

was added to `flutter.gradle` when running the flutter command!

**Comment by blasten** [comment] 2020-05-13 17:36
This might be due to https://github.com/flutter/flutter/commit/6dc1e83f121157b35e648cdf138d022a5e5d706b?  @dannyvalentesonos could you try to revert that commit in a local branch and see if that fixes it?

**Comment by dannyvalentesonos** [comment] 2020-05-13 17:38
Yep, already on it :)

**Comment by dannyvalentesonos** [comment] 2020-05-13 17:41
Ok, I have this working. We'll submit a PR and @blasten  you can see what you think.

**Comment by shihchanghsiungsonos** [comment] 2020-05-13 18:38
PR https://github.com/flutter/flutter/pull/57145 has created to fix this issue. Thanks!

**Comment by jonahwilliams** [comment] 2020-05-13 18:40
Ahh shoot, thanks @blasten !

**Comment by jonahwilliams** [comment] 2020-05-26 15:24
The PR has been merged, so I'm closing this as fixed, thanks!

**Closed by jonahwilliams** 2020-05-26 15:24 UTC
Labels: severe: crash, tool
