### ISSUE TITLE
Engine crashed with -1073741819 on Windows

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#18287] opened 2018-06-07 23:40 UTC
Appveyor failed with:

```
⏩ RUNNING: cd examples\flutter_gallery; ..\..\bin\flutter.bat test
01:02 +10 -1: loading C:\projects\flutter sdk\examples\flutter_gallery\test\smoke_test.dart [E]                                                                                                        
  Shell subprocess crashed with unexpected exit code -1073741819 after tests finished.
  Test: C:\projects\flutter sdk\examples\flutter_gallery\test\smoke_test.dart
  Shell: C:\projects\flutter sdk\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe
```

**Comment by chinmaygarde** [comment] 2018-06-09 00:30
Is this reproducible?

**Comment by Hixie** [comment] 2018-06-11 21:24
I've only seen it once, no idea how to reproduce.

**Comment by DanTup** [comment] 2018-07-02 12:31
Just seen this on Cirrus in [a PR I was working on](https://github.com/flutter/flutter/pull/18990):

https://cirrus-ci.com/task/4803565335871488

```
01:07 +11 -1: loading C:\Windows\Temp\flutter sdk\examples\flutter_gallery\test\smoke_test.dart [E]                                                                                                    
  Shell subprocess crashed with unexpected exit code -1073741819 after tests finished.
  Test: C:\Windows\Temp\flutter sdk\examples\flutter_gallery\test\smoke_test.dart
  Shell: C:\Windows\Temp\flutter sdk\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe
  dart:async/stream_controller.dart 594                     _StreamController.addError
  dart:async/stream_controller.dart 862                     _StreamSinkWrapper.addError
  package:stream_channel/src/guarantee_channel.dart 140     _GuaranteeSink._addError
  package:stream_channel/src/guarantee_channel.dart 131     _GuaranteeSink.addError
  package:flutter_tools/src/test/flutter_platform.dart 454  _FlutterPlatform._startTest.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                 _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77           _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart 444  _FlutterPlatform._startTest.<fn>
  package:flutter_tools/src/test/flutter_platform.dart 630  _FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                 _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77           _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart 374  _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 367  _FlutterPlatform.loadChannel
  package:test/src/runner/plugin/platform.dart 65           PlatformPlugin.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                 _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77           _asyncThenWrapperHelper
  package:test/src/runner/loader.dart 242                   Loader.loadFile.<fn>
  package:test/src/runner/load_suite.dart 89                new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                 _CustomZone.registerCallback
  dart:async/zone.dart 964                                  _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                  new Timer
  dart:async/timer.dart 87                                  Timer.run
  dart:async/future.dart 172                                new Future
  package:test/src/backend/invoker.dart 402                 Invoker._onRun.<fn>.<fn>.<fn>
01:07 +11 -1: Some tests failed.                                                                                                                                                                       
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by DanTup** [comment] 2018-07-02 12:34
Also https://github.com/flutter/flutter/issues/18287

**Comment by letsar** [comment] 2018-07-14 20:53
I have a similar issue (but different exit code) when I try to run flutter test on my personal Windows computer.

This is the verbose log I have:

``` powershell
PS D:\Dev\flutter-fork\flutter\packages\flutter> ..\..\bin\flutter test -v .\test\widgets\widget_inspector_test.dart
[  +93 ms] [D:\Dev\flutter-fork\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [D:\Dev\flutter-fork\flutter\] git rev-parse --abbrev-ref HEAD
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [D:\Dev\flutter-fork\flutter\] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/letsar/flutter.git
[        ] [D:\Dev\flutter-fork\flutter\] git log -n 1 --pretty=format:%H
[  +28 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] e7832a389755a1894494be1a26c2debf2cac745e
[        ] [D:\Dev\flutter-fork\flutter\] git log -n 1 --pretty=format:%ar
[  +29 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 hours ago
[        ] [D:\Dev\flutter-fork\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +40 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.6-122-ge7832a3
[ +516 ms] running test package with arguments: [-r, compact, --, D:\Dev\flutter-fork\flutter\packages\flutter\.\test\widgets\widget_inspector_test.dart]
00:00 +0: loading D:\Dev\flutter-fork\flutter\packages\flutter\.\test\widgets\widget_inspector_test.dart               [ +411 ms] test 0: starting test D:\Dev\flutter-fork\flutter\packages\flutter\.\test\widgets\widget_inspector_test.dart
[  +78 ms] test 0: starting shell process in preview-dart-2 mode
[   +6 ms] Discovered flutter_test_config.dart in D:\Dev\flutter-fork\flutter\packages\flutter\test
[  +16 ms] Compiling D:\Système\Temp\dart_test_listener506898bd-87a7-11e8-952b-408d5cb3c159/listener.dart
[  +16 ms] D:\Dev\flutter-fork\flutter\bin\cache\dart-sdk\bin\dart D:\Dev\flutter-fork\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\Dev\flutter-fork\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --strong --target=flutter --initialize-from-dill=foo --output-dill D:\Système\Temp\output_dill506898be-87a7-11e8-952b-408d5cb3c159\output.dill --packages D:\Dev\flutter-fork\flutter\packages\flutter\.packages
00:04 +0: loading D:\Dev\flutter-fork\flutter\packages\flutter\.\test\widgets\widget_inspector_test.dart               [+4564 ms] Copying platform.dill file from D:\Dev\flutter-fork\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk\platform_strong.dill
[   +6 ms] D:\Dev\flutter-fork\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe --disable-observatory --flutter-assets-dir=D:\Système\Temp\flutter_bundle_directory506898c0-87a7-11e8-952b-408d5cb3c159 --enable-checked-mode --enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts --packages=D:\Dev\flutter-fork\flutter\packages\flutter\.packages D:\Système\Temp\dart_test_listener506898bd-87a7-11e8-952b-408d5cb3c159/listener.dart.dill
[   +9 ms] test 0: awaiting initial result for pid 16860
[  +31 ms] test 0: process with pid 16860 crashed before connecting to test harness
[  +11 ms] test 0: waiting for controller sink to close
[   +5 ms] test 0: cleaning up...
[   +4 ms] test 0: deleting temporary bundle directory
00:04 +0 -1: loading D:\Dev\flutter-fork\flutter\packages\flutter\.\test\widgets\widget_inspector_test.dart [E]
  Failed to load "D:\Dev\flutter-fork\flutter\packages\flutter\.\test\widgets\widget_inspector_test.dart":
  Shell subprocess crashed with unexpected exit code -1073740791 before connecting to test harness.
  Test: D:\Dev\flutter-fork\flutter\packages\flutter\.\test\widgets\widget_inspector_test.dart
  Shell: D:\Dev\flutter-fork\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe


[  +18 ms] test 0: deleting temporary directory
[   +4 ms] test 0: shutting down test harness socket server
00:04 +0 -1: Some tests failed.
[  +18 ms] test 0: finished
[  +58 ms] test package returned with exit code 1
[  +13 ms] "flutter test" took 5 628ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:173:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#9      Future._complete (dart:async/future_impl.dart:472:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

How can I help more?

**Comment by letsar** [comment] 2018-08-27 05:27
I finally got it working on my PC, but I'm not sure what fixed it.

This is what I did:
1. Install the same sdk but from https://storage.googleapis.com/flutter_infra/releases/beta/windows/flutter_windows_v0.5.1-beta.zip on the same location as before
(at this point nothing was fixed)
2. Rename the TEMP and TMP env variables to a shorter and diacritic-free path (from **D:\Système\Temp** to **D:\sys\tmp**)
3. Restart the computer
=> At this point it was fixed and I could run `flutter test` without errors.

Hope this helps.

**Comment by cbracken** [comment] 2019-11-06 21:20
Closing this as we haven't seen it on recent builds (and our infra has changed signficantly either way) and we don't have clear repro instructions. If we do start seeing this again, we can open a new issue.

**Closed by cbracken** 2019-11-06 21:20 UTC
Labels: engine, severe: crash, team: flakes, ❖ platform-windows

**Comment by michael-wang** [comment] 2020-03-12 05:35
@cbracken I still encounter this issue yesterday, fixed by changing TEMP & TMP env var as @letsar suggested. Looks like it's the non-ASCII char in the path which cause this issue.
My flutter version:
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

**Comment by cbracken** [comment] 2020-03-12 05:48
@michael-wang just it be clear you’re also on Windows? If I remember correctly Windows doesn’t limit filenames to UTF-8 but rather uses a windows codepage specific to the machine locale. At least last I worked on it, the VM’s IO functionality translates all file paths to URLs and Dart assumes all URLs are UTF-8. Paths that are not valid UTF-8 may be the problem here. If I were to guess why “ASCII” paths work in those cases is that most locales’ codepage happens to start with some ASCII-like character set (e.g. Japanese is ASCII but with backslash replaced by ¥) and UTF-8 is happy with single-byte encodings in that range. 

Would you mind opening a new bug with detailed repro instructions and refer back to this one?
