### ISSUE TITLE
iOS doesn't show text controls

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19278] opened 2018-07-11 20:35 UTC
iOS doesn't show text controls like autocorrect, copy, paste, cut, etc.

**Comment by zoechi** [comment] 2018-07-12 07:14
Please add the output of `flutter doctor`

**Comment by lukepighetti** [comment] 2018-07-12 10:41
? I don't think this is bug, but a feature request?

**Comment by lukepighetti** [comment] 2018-07-12 10:51
```
Lukes-iMac:~ lukepighetti$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.7-pre.95, on Mac OS X 10.13.5 17F77, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✗] Android Studio (not installed)
[✓] VS Code (version 1.25.0)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment] 2018-07-12 11:22
There was some work going on recently and this might have been fixed already or a PR waiting.
Also it might take a while until someone has time to have a closer look and by this time it might have been implemented for other reasons already.
The `flutter doctor` output always allows to check if a commit was made before or after the version used when the bug report/feature request was made.
So it's usually a good idea to add the `flutter doctor` output.

Thanks for adding 👍

**Comment by zoechi** [comment] 2018-12-28 14:17
Duplicate of #24407

**Closed by zoechi** 2018-12-28 14:17 UTC
Labels: a: text input, framework, ⌺‬ platform-ios
