### ISSUE TITLE
video_player: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference, null, null)

### ISSUE THREAD

**Issue by MattiaudaNicolasCN** [flutter/flutter#88424] opened 2021-08-18 09:39 UTC
Hi guys. 
I'm testing my application on Android emulator and I'using `video_player: ^2.1.14`. When I try to start the streaming of cameras I get the exception below:

> E/flutter (15602): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference, null, null)
> E/flutter (15602): #0      VideoPlayerApi.create
> package:video_player_platform_interface/messages.dart:189
> E/flutter (15602): <asynchronous suspension>
> E/flutter (15602): #1      MethodChannelVideoPlayer.create
> package:video_player_platform_interface/method_channel_video_player.dart:47
> E/flutter (15602): <asynchronous suspension>

I attach my code:
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: ManageAppBar(
        lastCheck: _lastCheck,
        height: _appBarHeight,
        isDark: _isDark,
        pageName: "Cameras",
        plant: _plant,
      ),
      endDrawer: PlantDrawer(
        title: _plant.name,
        avatar: _getImageUrl(),
        isDark: _isDark,
        plantId: _plant.id,
        stopTimer: stopTimer,
        drawerItems: _drawerItems,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: isPlayed ? Colors.red : Colors.green,
        child: isPlayed ? Icon(Icons.stop) : Icon(Icons.play_arrow),
        onPressed: () async => {
          setState(() {
            isPlayed = !isPlayed;
          }),
          if (isPlayed) await getCameras(),
        },
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.startFloat,
      backgroundColor: _isDark ? AppColors.darkBack : AppColors.back,
      body: ScreenTypeLayout(
        mobile: OrientationLayoutBuilder(
          portrait: (context) => mobilePortrait(),
          landscape: (context) => mobileLandscape(),
        ),
        tablet: OrientationLayoutBuilder(
          portrait: (context) => tabletPortrait(),
          landscape: (context) => tabletLandscape(),
        ),
      ),
    );
  }

  mobilePortrait() {
    return SingleChildScrollView(child: Column(children: videos));
  }

  getCameras() async {
    for (var camera in _plant.cameras) {
      print(camera["Address"]);
      VideoPlayerController videoPlayerController =
          VideoPlayerController.network(camera["Address"], httpHeaders: {
        "user": camera["User"],
        "password": camera["Password"]
      });
      videoPlayerController.addListener(() {
        setState(() {});
      });
      await videoPlayerController.setLooping(true);
      await videoPlayerController.initialize();
      await videoPlayerController.play();

      setState(() {
        videos.add(Container(
            width: 400,
            height: 200,
            child: VideoPlayer(videoPlayerController)));
      });
    }
  }
```

here the output of `flutter doctor -v`

> [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Versione 10.0.19042.1165], locale it-IT)
>     • Flutter version 2.2.3 at C:\tools\flutter
>     • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at C:\Users\nicolas.mattiauda\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.9.4)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
>     • Visual Studio Professional 2019 version 16.9.31205.134
>     • Windows 10 SDK version 10.0.19041.0
> 
> [√] Android Studio (version 4.1.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code (version 1.59.0)
>     • VS Code at C:\Users\nicolas.mattiauda\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.25.0
> 
> [√] Connected device (4 available)
>     • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
>     • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Versione 10.0.19042.1165]
>     • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.131
>     • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.73
> 
> • No issues found!

**Comment by darshankawar** [comment] 2021-08-18 13:16
@MattiaudaNicolasCN 
The code you provided seem to have lot of custom snippets which we don't know, so would be great if you could provide us a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue.
Also confirm if the same exception is thrown using a physical device ?

**Comment by MattiaudaNicolasCN** [comment] 2021-08-18 13:59
I haven't had a chance to try with a physical device  yet.

Anyway here there is a minimal reproducible code sample:

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

main(List<String> args) {
  runApp(Test());
}

class Test extends StatefulWidget {
  const Test({Key? key}) : super(key: key);

  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  List<Widget> videos = [];
  List<String> addresses = ["http://camstream1.com", "http://camstream2.com"];
  @override
  void initState() {
    getData();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: videos,
      ),
    );
  }

  void getData() async {
    for (var address in addresses) {
      VideoPlayerController videoPlayerController =
          VideoPlayerController.network(address,
              httpHeaders: {"user": "user", "password": "password"});
      videoPlayerController.addListener(() {
        setState(() {});
      });
      await videoPlayerController.setLooping(true);
      await videoPlayerController.initialize();
      await videoPlayerController.play();

      setState(() {
        videos.add(Container(
            width: 400,
            height: 200,
            child: VideoPlayer(videoPlayerController)));
      });
    }
  }
}
```

**Comment by darshankawar** [comment] 2021-08-19 05:50
@MattiaudaNicolasCN 
Did you try with https ? Newer Android version enforces security and I see that you are trying to access url starting with http.

**Comment by rwintrich** [comment] 2021-08-19 05:59
Do u added Android permissions??

 <manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application ...>

    </application>

    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>

**Comment by MattiaudaNicolasCN** [comment] 2021-08-19 06:06
> @MattiaudaNicolasCN
> Did you try with https ? Newer Android version enforces security and I see that you are trying to access url starting with http.

unfortunately the calls I have to make are on http

**Comment by MattiaudaNicolasCN** [comment] 2021-08-19 06:06
> Do u added Android permissions??
> 
> ```
> </application>
> 
> <uses-permission android:name="android.permission.INTERNET"/>
> ```

Yes I added it

**Comment by darshankawar** [comment] 2021-08-19 06:18
@MattiaudaNicolasCN 
Try [this](https://stackoverflow.com/a/62988210) solution and see if it helps.

**Comment by rwintrich** [comment] 2021-08-19 06:24
Hey @MattiaudaNicolasCN , http://camstream1.com/http://camstream2.com is offline;

**Comment by rwintrich** [comment] 2021-08-19 06:25
> @MattiaudaNicolasCN
> Try [this](https://stackoverflow.com/a/62988210) solution and see if it helps.

Idk, i tried here, but the same result :/ link is off

**Comment by MattiaudaNicolasCN** [comment] 2021-08-19 06:27
I tried your solution but nothing change, I also tried to downgrade the Android version of the emulator but nothing

**Comment by MattiaudaNicolasCN** [comment] 2021-08-19 06:31
> Hey @MattiaudaNicolasCN , http://camstream1.com. / http://camstream2.com is offline;

It was an example link , I can't share the links where I try to stream cameras

**Comment by rwintrich** [comment] 2021-08-19 06:33
List<String> addresses = [
    "https://www.rmp-streaming.com/media/big-buck-bunny-360p.mp4",
    "https://www.rmp-streaming.com/media/big-buck-bunny-360p.mp4"
  ];

**Comment by MattiaudaNicolasCN** [comment] 2021-08-19 06:37
with my code above and tese urls I see this:
![Screenshot_1629355002](https://user-images.githubusercontent.com/56304440/130019905-10e6a643-5d40-47a6-a995-89c91ef711f9.png)
So it works...

**Comment by rwintrich** [comment] 2021-08-19 06:44
> with my code above and tese urls I see this:
> ![Screenshot_1629355002](https://user-images.githubusercontent.com/56304440/130019905-10e6a643-5d40-47a6-a995-89c91ef711f9.png)
> So it works...

U need specify path of file and format u want to render.

**Comment by MattiaudaNicolasCN** [comment] 2021-08-19 06:48
@rwintrich whay do you mean with 

> U need specify path of file and format u want to render. ?

**Comment by rwintrich** [comment] 2021-08-19 06:56
> @rwintrich whay do you mean with
> 
> > U need specify path of file and format u want to render. ?

Video player need path/format.  Ex: https://test/vídeos.mp4 
Path+ format

**Comment by rwintrich** [comment] 2021-08-19 06:56
> > with my code above and tese urls I see this:
> > ![Screenshot_1629355002](https://user-images.githubusercontent.com/56304440/130019905-10e6a643-5d40-47a6-a995-89c91ef711f9.png)
> > So it works...
> 
> U need specify path of file and format u want to render.

This resolve ur issue?

**Comment by darshankawar** [comment] 2021-08-19 12:18
@MattiaudaNicolasCN 
This seems to be related to the specific urls with http url maybe accessing form your local server.
There's a similar open issue describing such case, https://github.com/flutter/flutter/issues/85435
Please follow-up there for updates.
Closing this as duplicate.

**Closed by darshankawar** 2021-08-19 12:18 UTC
Labels: in triage

**Comment by MattiaudaNicolasCN** [comment] 2021-08-20 13:25
@darshankawar I added the video format into the link that is a file **.amp** and then I also added into the declaration of the controller this line: `formatHint: VideoFormat.hls,`  that is specific for HTTP Live Streaming.
And now i didn't get the exception above, but I get : 

> E/ExoPlayerImplInternal( 4692): Playback error
> E/ExoPlayerImplInternal( 4692):   com.google.android.exoplayer2.ExoPlaybackException: Source error
> E/ExoPlayerImplInternal( 4692):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
> E/ExoPlayerImplInternal( 4692):       at android.os.Handler.dispatchMessage(Handler.java:102)
> E/ExoPlayerImplInternal( 4692):       at android.os.Looper.loop(Looper.java:193)
> E/ExoPlayerImplInternal( 4692):       at android.os.HandlerThread.run(HandlerThread.java:65)
> E/ExoPlayerImplInternal( 4692):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 503
> E/ExoPlayerImplInternal( 4692):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
> E/ExoPlayerImplInternal( 4692):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
> E/ExoPlayerImplInternal( 4692):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
> E/ExoPlayerImplInternal( 4692):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
> E/ExoPlayerImplInternal( 4692):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
> E/ExoPlayerImplInternal( 4692):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
> E/ExoPlayerImplInternal( 4692):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/ExoPlayerImplInternal( 4692):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/ExoPlayerImplInternal( 4692):       at java.lang.Thread.run(Thread.java:764)
> E/flutter ( 4692): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)


Why ?
