### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference

### ISSUE THREAD

**Issue by HappyGhostz** [flutter/flutter#62665] opened 2020-07-31 13:27 UTC
**Rough code logic**
renderMode = RenderMode.texture
```
companion object {
        @JvmStatic
        fun newInstance(
            identifier: String,
            transparencyMode: TransparencyMode = TransparencyMode.opaque,
            renderMode: RenderMode = RenderMode.surface,
            shouldAttachEngineToActivity: Boolean = true
        ): FlutterContainerFragment {
            return FlutterContainerFragmentBuilder(identifier)
                .renderMode(renderMode)
                .transparencyMode(transparencyMode)
                .shouldAttachEngineToActivity(shouldAttachEngineToActivity)
                .destroyEngineWithFragment(false)
                .build<FlutterContainerFragment>()
        }
    }

    private class FlutterContainerFragmentBuilder(private val identifier: String) :
        FlutterFragment.CachedEngineFragmentBuilder(
            FlutterContainerFragment::class.java,
            DEFAULT_CACHED_ENGINE_ID
        ) {

        override fun createArgs(): Bundle {
            return super.createArgs().apply {
                putString(FRAGMENT_ARG_IDENTIFIER, identifier)
            }
        }
    }
```
When I set **renderMode = RenderMode.texture**, the following bug information will appear

**bug Info**

```
2020-07-31 21:06:06.235 12400-12400/com.grabtaxi.passenger E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.grabtaxi.passenger, PID: 12400
    java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference
        at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:699)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:290)
        at io.flutter.embedding.android.FlutterFragment.onCreateView(FlutterFragment.java:585)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7054)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Flutter doctor**

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G6020, locale en)
    • Flutter version 1.17.5 at /Users/xxx/Documents/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxx/Library/Anxdroid/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.7.4 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • vivo 1725 • 889daa23 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

**flutter analyze**

```
Analyzing flutter_pax...                                                
No issues found! (ran in 8.8s)
```

**And after debugging the tracking code, I found that there is such a code snippet in FlutterView under this package(package io.flutter.embedding.android;).**

```
  private FlutterView(
      @NonNull Context context,
      @Nullable AttributeSet attrs,
      @NonNull FlutterTextureView flutterTextureView) {
    super(context, attrs);

    this.flutterTextureView = flutterTextureView;
    this.renderSurface = flutterSurfaceView;

    init();
  }
```
**I think because of renderSurface=flutterSurfaceView instead of renderSurface=flutterTextureView, renderSurface is null in the code below. This is what I see in the tracking code. or is it correct?**
```
  //package io.flutter.embedding.android;
 //    renderSurface.attachToRenderer(flutterRenderer);
  public void attachToFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    Log.v(TAG, "Attaching to a FlutterEngine: " + flutterEngine);
    if (isAttachedToFlutterEngine()) {
      if (flutterEngine == this.flutterEngine) {
        // We are already attached to this FlutterEngine
        Log.v(TAG, "Already attached to this engine. Doing nothing.");
        return;
      }

      // Detach from a previous FlutterEngine so we can attach to this new one.
      Log.v(
          TAG,
          "Currently attached to a different engine. Detaching and then attaching"
              + " to new engine.");
      detachFromFlutterEngine();
    }

    this.flutterEngine = flutterEngine;

    // Instruct our FlutterRenderer that we are now its designated RenderSurface.
    FlutterRenderer flutterRenderer = this.flutterEngine.getRenderer();
    isFlutterUiDisplayed = flutterRenderer.isDisplayingFlutterUi();
    renderSurface.attachToRenderer(flutterRenderer);
    flutterRenderer.addIsDisplayingFlutterUiListener(flutterUiDisplayListener);

    // Initialize various components that know how to process Android View I/O
    // in a way that Flutter understands.
    textInputPlugin =
        new TextInputPlugin(
            this,
            this.flutterEngine.getDartExecutor(),
            this.flutterEngine.getPlatformViewsController());
    androidKeyProcessor =
        new AndroidKeyProcessor(this.flutterEngine.getKeyEventChannel(), textInputPlugin);
    androidTouchProcessor = new AndroidTouchProcessor(this.flutterEngine.getRenderer());
    accessibilityBridge =
        new AccessibilityBridge(
            this,
            flutterEngine.getAccessibilityChannel(),
            (AccessibilityManager) getContext().getSystemService(Context.ACCESSIBILITY_SERVICE),
            getContext().getContentResolver(),
            this.flutterEngine.getPlatformViewsController());
    accessibilityBridge.setOnAccessibilityChangeListener(onAccessibilityChangeListener);
    resetWillNotDraw(
        accessibilityBridge.isAccessibilityEnabled(),
        accessibilityBridge.isTouchExplorationEnabled());

    // Connect AccessibilityBridge to the PlatformViewsController within the FlutterEngine.
    // This allows platform Views to hook into Flutter's overall accessibility system.
    this.flutterEngine.getPlatformViewsController().attachAccessibilityBridge(accessibilityBridge);

    // Inform the Android framework that it should retrieve a new InputConnection
    // now that an engine is attached.
    // TODO(mattcarroll): once this is proven to work, move this line ot TextInputPlugin
    textInputPlugin.getInputMethodManager().restartInput(this);

    // Push View and Context related information from Android to Flutter.
    sendUserSettingsToFlutter();
    sendLocalesToFlutter(getResources().getConfiguration());
    sendViewportMetricsToFlutter();

    flutterEngine.getPlatformViewsController().attachToView(this);

    // Notify engine attachment listeners of the attachment.
    for (FlutterEngineAttachmentListener listener : flutterEngineAttachmentListeners) {
      listener.onFlutterEngineAttachedToFlutterView(flutterEngine);
    }

    // If the first frame has already been rendered, notify all first frame listeners.
    // Do this after all other initialization so that listeners don't inadvertently interact
    // with a FlutterView that is only partially attached to a FlutterEngine.
    if (isFlutterUiDisplayed) {
      flutterUiDisplayListener.onFlutterUiDisplayed();
    }
  }

```
**renderSurface.attachToRenderer(flutterRenderer)** When the code was in the aisle, the exception displayed at the top broke out!

Is there any time to solve this problem, or is there something wrong with my usage? Thank you!

**Comment by collindever** [comment] 2020-07-31 18:23
I ran into this same issue. It is related to the issue #57096 and is a bug fixed in 1.18.0-dev.0.0 you can update to fix the problem (I've tried latest beta and 1.18.0-11.1.pre) and it works.  I have not gotten the work around posted to work but I'm also working with a flutterFragment not a flutterActivity.

**Comment by HappyGhostz** [comment] 2020-08-01 03:27
When can it be used in a stable? we must use stable!

**Comment by darshankawar** [comment] 2020-08-03 09:50
Hi @HappyGhostz,
Per [this](https://github.com/flutter/flutter/issues/56962#issuecomment-648333189) comment, the fix is currently available in `beta` channel. You may wait till the fix reaches stable or can cherry-pick the commit which fixed the issue and use it in stable channel. 
I am going ahead and closing this issue since the issue is fixed already and is available in beta. 
If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-08-03 09:50 UTC
