### ISSUE TITLE
Flutter doesn't understand iOS expanding status bar

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5327] opened 2016-08-10 22:01 UTC
iOS will occasionally enlarge the status bar to indicate background activity (like an app using location, or connections to your hotspot, etc.)

Flutter doesn't understand when this happens and the AppBar looks wrong:
![img_0255](https://cloud.githubusercontent.com/assets/11857803/17572788/4232d608-5f0b-11e6-86f3-58565821ccc3.png)

**Comment by sethladd** [comment] 2016-08-10 22:02
Good catch!

**Comment by chinmaygarde** [comment] 2016-09-09 18:22
The rendering surface does account for the status bar updates. So I am not sure about the expected behavior. https://www.youtube.com/watch?v=1p8EccWihis&feature=youtu.be

**Comment by HansMuller** [comment] 2016-09-09 19:18
What appears to be going on (from the app bar's perspective) is that the status bar height per MediaQuery.of(context).padding.top is doubling - which I think it should - but the app itself is moving downwards by the status bar's increase in size.  In other words the root of the app doesn't appear to be at the top of the screen after the status bar's height increases.

**Comment by eseidelGoogle** [comment] 2016-09-21 16:00
I asked an iOS expert.  The status bar has two sizes. Normal size where it's transparent and doesn't really act like a button, you can draw behind it and you get an origin of 0x0.  Double size were it's opaque, it acts like a button, you can't draw behind it, and it will move you view from 0x0 to 0x40 (or whatever the number is) to accommodate it appearing.

When we fix this we should also test what pulling out a drawer does when the double status bar is showing.  Current material apps on iOS seem to hide the status bar which causes some very strange behavior of jumping.  https://youtu.be/tYRzBnTnLfI

**Comment by Hixie** [comment] 2016-09-22 18:29
Sounds like when it's double size we should shrink the window size that we report, and set the padding to zero, and the positioning should be handled on the engine side.

**Comment by eseidelGoogle** [comment] 2016-09-29 03:12
We're going to need to do this before folks can ship.  This double-status bar is quite common.

The iOS simulator even has a way to test this, command-Y toggles the "in call status bar".

**Comment by Hixie** [comment] 2016-09-29 16:54
This is an engine-level bug. @tvolkert or @chinmaygarde are likely candidates for fixing it. Once the data from the engine is correct we may need to apply some tweaks on the framework side but in theory it should just work.

**Comment by eseidelGoogle** [comment] 2016-11-08 14:55
I believe the fix is to make the window size smaller and the window padding empty as @Hixie suggests:
https://docs.flutter.io/flutter/dart-ui/Window/physicalSize.html
https://docs.flutter.io/flutter/dart-ui/Window/padding.html

I believe this line just needs to change:
https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L348

To detect the specific 40pt case and don't report those 40pts as padding but rather as a reduction in size:
http://stackoverflow.com/questions/12991935/how-to-programmatically-get-ios-status-bar-height

**Comment by eseidelGoogle** [comment] 2017-01-24 04:10
There is another mode of the status bar where it just turns opaque (like when you have a hotspot running and something connected). I don't think we need to do anything to support that, but thought I'd mention.

**Comment by cbracken** [comment] 2017-01-24 18:58
The padding issue is fixed by flutter/engine#3357, which fixes the layout. Filed #7616 since the animation between the standard and expanded status bars is still janky.

**Closed by cbracken** 2017-01-24 18:58 UTC
Labels: prod: engine, prod: fidelity, prod: framework, ⌺‬ platform-ios
