### ISSUE TITLE
Flutter App in playstore fails for Pixel 2, Virtual API Level 28

### ISSUE THREAD

**Issue by RevTpark** [flutter/flutter#108666] opened 2022-07-30 09:45 UTC
I tried to reproduce it using `Firebase Test Labs` and it failed the test too. The following error was encountered:
![image](https://user-images.githubusercontent.com/78678620/181903095-88fb8236-cf42-4c44-9adf-3fac65accc48.png)

This problem did not occur for the first 3-4 months of deployment. All of a sudden playstore started to send warning notifications regarding this device. At first, I thought this might mean some package we used in the development process might be the issue but when I rolled back the codebase to the time before the issue appeared and tried to test it, it still failed the test for the particular device.

On further research, I took a good look at the error logs. Where I saw it failed due to `'libflutter.so'` missing. I tried to analyze the apk using `Andriod Studio`  and found there were 4 build packs created inside `lib/`.

On diving deep into the problem, I found the issue was regarding the x86 build pack. There was no **'libflutter.so'** being created for x86. I tried various methods to fix it like [this article](https://medium.com/codechai/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd) but then the Flutter Test labs threw the error that `x86 build file does not exist.`  I also found [this issue](https://github.com/flutter/flutter/issues/51191) from 2020 where it said x86 wasn't supported. But then my question is why aren't other production-level apps aren't facing the same error?

**Comment by exaby73** [comment] 2022-08-01 06:14
Hello @RevTpark. Thank you for filing this issue. Can you share the complete logs you have as well as the output of `flutter doctor -v`?

**Comment by RevTpark** [comment] 2022-08-01 12:47
Hey @exaby73, thanks for the response, here is the information you need.
This is the entire log as received from firebase: [logcat.txt](https://github.com/flutter/flutter/files/9233930/logcat.1.txt)
This is the log of flutter doctor:
```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1826], locale en-IN)
    • Flutter version 3.0.5 at C:\Users\tanis\flutter_windows_2.8.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\tanis\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.12)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32407.337
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\tanis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by exaby73** [comment] 2022-08-01 13:31
Thank you. Looks like this is a duplicate of https://github.com/flutter/flutter/issues/37396. Closing as such. Please share your findings and upvote the original issue. Thank you

**Closed by exaby73** 2022-08-01 13:31 UTC
Labels: in triage
