### ISSUE TITLE
Older firebase_messaging (pre AndroidX) not working anymore

### ISSUE THREAD

**Issue by JulioCGC** [flutter/flutter#30190] opened 2019-03-29 13:30 UTC
Hello,

i`m using an Flutter application that does not support AndroidX update, because of some plugins, but when i`ll install the firebase_messaging, i get this error (i`m using firebase_messaging: 2.1.0):

D8: Program type already present: android.support.v4.app.INotificationSideChannel
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/2.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/3.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/27.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/29.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/31.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/34.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/37.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/42.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/43.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/44.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/45.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/46.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/47.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/48.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/49.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/50.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/51.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/52.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/53.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/54.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/56.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/57.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/58.jar, /Users/desenvolvedor/projects_flutter/nrformaturas/build/app/intermediates/transforms/dexBuilder/debug/59.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

HELP, PLEASE!!!

**Comment by ffeu** [comment] 2019-03-30 18:56
Have you tried defining the version of `firebase_core` to `0.2.5+1` in your `pubspec.yaml` ([see this version compatibility list](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx))?

(before trying to run, execute `flutter clean` in your repo)

Please include an output of `flutter doctor -v` in your issue.

**Comment by JulioCGC** [comment] 2019-04-01 11:32
Hello, i've followed these steps and it still not working, tryied with this in my pubspec.yaml:
cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.0
  flutter_swiper: ^1.1.4
  material_design_icons_flutter: ^3.0.3392
  url_launcher: ^4.0.3
  scoped_model: ^1.0.1 
  http: ^0.12.0+1
  flutter_secure_storage: ^3.1.3
  transparent_image: ^1.0.0
  flutter_inappbrowser: ^1.1.0
  share: ^0.5.3
  path_provider: 0.4.1
  firebase_core: 0.2.5
  firebase_messaging: 2.1.0
  qrcode_reader: 0.4.4
  qr_flutter: ^2.0.0

My flutter_doctor -v analises:
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G65, locale en-BR)
    • Flutter version 1.2.1 at /Users/desenvolvedor/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/desenvolvedor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (2 available)
    • M5c      • 710HZBRT223J9                        • android-arm64 • Android 6.0 (API 23)
    • iPhone 7 • 7B40CFAD-0864-4B78-967B-924AB37ED41D • ios           • iOS 12.1 (simulator)

**Comment by JulioCGC** [comment] 2019-04-03 17:20
It's very pleasurable to see how you guys are receptives, very helpful.

**Comment by escamoteur** [comment] 2019-09-25 09:16
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment] 2019-11-07 14:08
Hi @JulioCGC 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-07 14:08 UTC
Labels: waiting for customer response
