### ISSUE TITLE
ImageFilter widget

### ISSUE THREAD

**Issue by MichaelRFairhurst** [flutter/flutter#13489] opened 2017-12-11 21:10 UTC
I want to implement a blur, not of the layer below my widget, but of a current widget.

Is there a widget that looks something like:

```dart
build() =>
  new FilteredWidget(
    filter: new ImageFilter.blur(...),
    child: ...
  );
```

or should I copy `RenderProxy` from https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart to create one?

I also want to stack these layers, which I'm assuming requires compositing:

```dart
build() =>
  new Stack(
    children: [
      new FilteredWidget(
        filter: new ImageFilter.blur(...),
        child: ...
      ),
      new FilteredWidget(
        filter: new ImageFilter.blur(...),
        child: ...
      ),
      ...
  );
```

They will be blurred different amounts, so while I can use `BackdropFilter`, I have to order the most blurred before the least blurred, and calculate the proper blur amount to do on the first one such that blurring the second one results in the desired _actual_ blur amount on the first. Would be much better to treat each widget as a blurred widget and composite them, than to treat each widget as blurring its prior paint.

Not sure if solving the first one gets me the second one for free, or if they are separate issues.

**Comment by Hixie** [comment] 2017-12-11 21:39
Looks like you want a widget similar to ShaderMask.

**Comment by MichaelRFairhurst** [comment] 2017-12-11 21:50
I realized I gave very little practical context: I'm doing a blur in an animation. That's why its not a backdrop, really.

**Comment by sroddy** [comment] 2018-03-18 01:42
@jonahwilliams I saw that you self-assigned this issue. Do you have a (tentative) ETA for this?
This is a road blocker for one of our projects as the performances of Backdrop Fliter are not satisfying (and we just really need to blur a static background). I need to understand if it's worth to wait for this feature or if we work around this issue pre-processing the images on the server

**Comment by jonahwilliams** [comment] 2018-03-18 04:48
@sroddy No ETA at this time, though it would be great if you could share any perf issues you are having with Backdrop Filter.

**Comment by sroddy** [comment] 2018-03-18 05:11
I'm just applying a backdrop filter on top of a static background image to obtain a blur effect of the background. Something very similar to this example: https://github.com/FlutterRocks/blurry_artist_details_page/blob/master/lib/artist_details_page.dart#L104

on top of the blurred background there is a ListView that displays paragraphs of text. Scrolling it is extremely laggy (<30 fps) on Nexus 5 and Nexus 5x and far from usable. My guess is that everything behind the backdrop filter gets rasterized on every frame even if it doesn't change instead of being rasterized just once when something changes.

Even in the example above you will notice that scrolling the horizontal listview is laggy on these devices, while if you remove the filter everything becomes smooth again.

**Comment by sroddy** [comment] 2018-03-18 05:12
@jonahwilliams

**Comment by jonahwilliams** [comment] 2018-03-18 18:20
@sroddy Thanks for the report, I'll take a look on a real device.

**Comment by jonahwilliams** [comment] 2018-03-20 19:13
@sroddy I have reproduced the issue on a Nexus 5, using a filtered image within a list view.  `SkCanvas::Flush` and `AndroidContextGL::SwapBuffers` are each taking > 15ms a frame here.  I'm going to drilldown into these more.  Ideally we could just apply the filter to the image once and save that new image, I'm going to look into an implementation that does just that

## Image Filter: Blur
![image_filter_timeline](https://user-images.githubusercontent.com/8975114/37673347-355195aa-2c2d-11e8-913a-f3167558a69c.png)

## No Image Filter
![without_image_filter](https://user-images.githubusercontent.com/8975114/37673349-373c7da8-2c2d-11e8-8170-64e4cf011f7e.png)

**Comment by sroddy** [comment] 2018-03-21 04:00
thanks @jonahwilliams, that would be really appreciated. Please keep me posted!

**Comment by jonahwilliams** [comment] 2018-03-26 21:39
Two updates for @MichaelRFairhurst  and @sroddy 

I'm working on a more efficient way of painting an image with a blur, where the intention is the image/blur is more or less fixed.  On my testing on a Nexus 5 with a list of blurred pictures, this technique gets about 40 fps GPU/60 fps UI whereas the BackdropFilter gets about 15 fsp GPU/20 fps UI.

This is also informing my design for what an (animated) image filter widget would look like.  I'm working on a design which works by modifying how the image is painted.

**Comment by jonahwilliams** [comment] 2018-04-16 17:30
@AnwarShahriar No current update, I encountered similar performance issues on older devices so I am currently waiting on https://github.com/flutter/engine/pull/5008 so I can try a dart implementation of the blur.

If you have similar performance issues as documented above I would continue with your plan to pre-process images for the time being.

**Comment by Hixie** [comment] 2018-04-16 18:50
That API by definition can't get you 60fps since it's asynchronous -- you'd at best have one frame of lag all the time (which would look pretty terrible).

**Comment by dnfield** [comment] 2018-09-10 08:19
Did anyone end up looking at whether it'd make sense to just expose `ImageFilter` on `Paint`?  It seems like at least some gains should be possible by not trying to construct a whole new layer, and just have a `RenderObject` paint with a blur filter applied to it.

**Comment by Hixie** [comment] 2018-09-11 20:32
we need both

**Comment by maryx** [comment] 2018-11-21 01:06
A similar example of where one would prefer to blur each widget individually: https://stackoverflow.com/questions/53403835/how-to-selectively-blur-widgets-in-a-child-stack-in-flutter

Also agree there are performance issues with using BackdropFilter right now: https://stackoverflow.com/questions/53402799/performant-blur-opacity-in-flutter

**Comment by gspencergoog** [comment] 2019-02-22 19:09
Removed the easy fix label, because it's clearly just not that easy... :-)

**Comment by maryx** [comment] 2019-02-22 19:18
I have a sample app that demonstrates the performance issues once blur is turned on. You can check it out at https://github.com/maryx/confetti and maybe it can help with debugging/resolving this issue.

**Closed** 2019-12-21 22:03 UTC
Labels: framework, severe: new feature

**Comment by cmkweber** [comment] 2020-01-10 20:31
An additional use case of this widget is now realtime supersampling can be performed. This can be beneficial when doing canvas operations that do not support antialiasing (such as drawVertices). I have provided an example gist here: [https://gist.github.com/cmkweber/c17aae8fa48a4853a87f242835cb65cb](https://gist.github.com/cmkweber/c17aae8fa48a4853a87f242835cb65cb)

**Comment by fluttercorner** [comment] 2020-10-08 17:53
[How to make a blur Background Image effect in Flutter using BackdropFilter.](https://fluttercorner.com/how-to-make-a-blur-background-image-effect-in-flutter-using-backdropfilter/)

**Comment by flar** [comment] 2020-10-08 18:48
> [How to make a blur Background Image effect in Flutter using BackdropFilter.](https://fluttercorner.com/how-to-make-a-blur-background-image-effect-in-flutter-using-backdropfilter/)

The app in this article is a pretty good example of when to use the ImageFiltered widget instead of BackdropFilter - the background consists of a single image which could be blurred directly with fewer lines of code.

**Comment by dnfield** [comment] 2020-10-08 18:53
@fluttercorner please do not use the issue tracker database to promote content that is either only loosely related or actually detrimental.
