### ISSUE TITLE
Codelab missing firebase core

### ISSUE THREAD

**Issue by stephenhuey** [flutter/flutter#53835] opened 2020-04-02 16:56 UTC
The following page says "Note: All Flutter-Firebase apps, both iOS and Android versions, require the firebase_core plugin for Flutter."

https://firebase.google.com/docs/flutter/setup

But firebase_core is missing from this page of the Firebase for Flutter codelab:

https://codelabs.developers.google.com/codelabs/flutter-firebase/#3

This is all it mentions adding to your project:

`dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1     # new`

Shouldn't firebase_core also be there?

**Comment by stephenhuey** [comment] 2020-04-02 19:47
Just verified that a Flutter app deployed to Android can successfully query Cloud Firestore with only cloud_firestore (no firebase_core seems to be needed).  So I assume the docs on the Firebase  site are out-of-date.

**Comment by iapicca** [comment] 2020-04-03 05:59
Hi @stephenhuey 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-03 05:59 UTC

**Comment by stephenhuey** [comment] 2020-04-03 14:18
Pardon me, their codelab linked to here for leaving feedback about errors!  And from what I can tell, the issue is in the Firebase documentation.
