### ISSUE TITLE
Characters are garbled when dividing a character string type that includes pictograms

### ISSUE THREAD

**Issue by KazumaShimomiya** [flutter/flutter#64932] opened 2020-08-31 06:01 UTC
Is this a Dart or Flutter spec! ?

[Dart Pad](https://dartpad.dev/43168709ecc4776b09ec8441fccba792)

```
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String str =  'Test.😗😗😗';
    List<String> listStr = str.split('');
    Iterable<Characters> characters = str.characters.split(''.characters);
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Column(
            children: [
              Text('No problem↓'),
              Text(characters.last.first),
              Text(str),
              Text('Problem↓'),
              Text(listStr.last), // Garbled
            ]
          ),
        ),
      ),
    );
  }
}

```

**Comment by pedromassangocode** [comment] 2020-08-31 12:04
Hi @KazumaShimomiya 
Can you elaborate more what this issue is about? I'm not sure if I understood this correctly.

Please  share the actual vs expected results, also please share you `flutter doctor -v`.
Thank you

**Comment by KazumaShimomiya** [comment] 2020-09-01 01:45
Hi @pedromassangocode 
Thank you for your reply!!

It can be displayed by applying emoji to the Text widget.
However, when emoticons are applied to the Text widget after executing split(), the characters are garbled.
Is this a Dart or Flutter spec ?
You can check it [here](https://dartpad.dev/43168709ecc4776b09ec8441fccba792).

`flutter doctor -v` result.
```
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale ja-JP)
    • Flutter version 1.20.1 at /Users/shimomiya_k/Develop/flutter
    • Framework revision 2ae34518b8 (4 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/shimomiya_k/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 904C57FA-5829-41ED-AF00-95DA6930DBD8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

**Comment by pedromassangocode** [comment] 2020-09-01 07:37
Hi @KazumaShimomiya 
Sorry I'm not able to understand what the issue is based on your code, and I'm not able to reproduce that too. Can you please provide a visual example of the actual vs expected result? I'm not really sure if your code reproduces the issue you’re trying to address.

**Comment by pedromassangocode** [comment] 2020-09-01 07:53
Hi @KazumaShimomiya 
From what I can see, the issue is related to a Dart language rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/language).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-01 07:53 UTC
Labels: in triage

**Comment by KazumaShimomiya** [comment] 2020-09-01 08:15
Hi @pedromassangocode 

I understand the problem with the Dart language.
Thank you.
