### ISSUE TITLE
Flutter custom navigation drawer with bloc does not work as expected

### ISSUE THREAD

**Issue by lazarvgd** [flutter/flutter#60086] opened 2020-06-23 11:12 UTC
**Note**: Please sorry if my question is not related to Flutter behavior, but due to lack of experience and knowledge I have to ask about some Flutter behavior that I do not understand.

I created my custom NavDrawer using Stateful widget and added Bloc to it so I can dynamically update UI depending on if a user changed the profile picture or updated any other data that is present in NavDrawer. 

**The problem:**
When I close NavDrawer it seems that the Flutter engine destroys the screen and bloc even though I created bloc for drawer in parent class/screen that is never removed from the stack and passed every time NavDrawer widget is created. So, from my understanding, the NavDrawer should always have the same state because the instance of the bloc has never changed because the instance is in the parent widget that is still displayed on the device.
And yet I am getting an error: **_Unhandled error Bad state: Cannot add new events after calling close occurred in bloc Instance of 'NavigationDrawerBloc'._**

Can somebody please tell me what in Flutter engine I am overseeing so that issue is happening? Is this behavior expected?
Is it possible to tell Flutter not to destroy NavDrawer with some kind of flag or something? What am I missing here? Thanks

Here is CustomNavDrawer:

```
class CustomNavigationDrawer extends StatefulWidget {
  @override
  _CustomNavigationDrawerState createState() => _CustomNavigationDrawerState();
}

class _CustomNavigationDrawerState extends State<CustomNavigationDrawer> {
  MobileSpecificModel mobileSpecificModel = GetIt.instance.get<MobileSpecificModel>();
  UserDto _userData;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<NavigationDrawerBloc, NavigationDrawerState>(builder: (builderContext, state) {
      if (state is DrawerLoadingState) {
        return LoadingWidget();
      } else if (state is DrawerLoadedState) {
        _userData = state.userDto;
        return Drawer(
          child: Container(
            color: AppColors.NAV_DRAWER_BODY_BACKGROUND_COLOR,
            child: ListView(
              padding: EdgeInsets.zero,
              children: <Widget>[
                CustomNavigationDrawerHeader(_userData),
                SizedBox(
                  height: 10,
                ),
                ListTile(
                  leading: Text(
                    AppStrings.NavDrawerProfileSettingsTitle,
                    style: AppFontStyles.kNavDrawerListTileTextStyle,
                  ),
                  trailing: ImageIcon(
                    AssetImage(
                      AppImages.IcMenuSettings,
                    ),
                    color: Colors.white,
                  ),
                  onTap: _openProfileSettings,
                ),
                Divider(
                  height: 20,
                  color: AppColors.NAV_DRAWER_HEADER_BACKGROUND_COLOR,
                  thickness: 2,
                ),
                ListTile(
                  leading: Text(
                    AppStrings.NavDrawerAboutUsTitle,
                    style: AppFontStyles.kNavDrawerListTileTextStyle,
                  ),
                  trailing: ImageIcon(
                    AssetImage(
                      AppImages.IcMenuAbout,
                    ),
                    color: Colors.white,
                  ),
                  onTap: () {
                    _openUrl(mobileSpecificModel.urlFrontendAboutUs);
                  },
                ),
                ListTile(
                  leading: Text(
                    AppStrings.NavDrawerContactUsTitle,
                    style: AppFontStyles.kNavDrawerListTileTextStyle,
                  ),
                  trailing: ImageIcon(
                    AssetImage(
                      AppImages.IcMenuMessage,
                    ),
                    color: Colors.white,
                  ),
                  onTap: () {
                    _openUrl(mobileSpecificModel.urlFrontendContactUs);
                  },
                ),
                ListTile(
                  leading: Text(
                    _userData != null ? AppStrings.NavDrawerLogoutTitle : AppStrings.NavDrawerLoginTitle,
                    style: AppFontStyles.kNavDrawerListTileTextStyle,
                  ),
                  trailing: ImageIcon(
                    AssetImage(
                      AppImages.IcMenuLogout,
                    ),
                    color: Colors.white,
                  ),
                  onTap: _userData != null ? _performLogOut : _navigateToLogin,
                ),
              ],
            ),
          ),
        );
      } else if (state is DrawerNotLoggedInState) {
        return Drawer(
          child: Container(
            color: AppColors.NAV_DRAWER_BODY_BACKGROUND_COLOR,
            child: ListView(
              padding: EdgeInsets.zero,
              children: <Widget>[
                CustomNavigationDrawerHeader(_userData),
                SizedBox(
                  height: 10,
                ),
                ListTile(
                  leading: Text(
                    _userData != null ? AppStrings.NavDrawerLogoutTitle : AppStrings.NavDrawerLoginTitle,
                    style: AppFontStyles.kNavDrawerListTileTextStyle,
                  ),
                  trailing: ImageIcon(
                    AssetImage(
                      AppImages.IcMenuLogout,
                    ),
                    color: Colors.white,
                  ),
                  onTap: _userData != null ? _performLogOut : _navigateToLogin,
                ),
              ],
            ),
          ),
        );
      } else {
        return Center(
          child: Text(
            'ERROR',
            style: AppFontStyles.WhiteFont20,
          ),
        );
      }
    });
  }

  void _navigateToLogin() {
    Navigator.pushNamed(context, MainLoginScreen.id);
  }

  void _performLogOut() {
    BlocProvider.of<NavigationDrawerBloc>(context).add(DrawerLogoutEvent());
    _navigateToLogin();
  }

  void _openProfileSettings() {
    if (_userData != null) Navigator.pushNamed(context, ProfileSettingsScreen.id, arguments: ProfileSettingsScreenArgs(_userData));
  }

  void _openUrl(String url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
}

class ProfileSettingsScreenArgs {
  final UserDto userData;

  ProfileSettingsScreenArgs(this.userData);
}
```

Here is a code snippet of build method from parent widget where NavDrawer and bloc are instantiated:

```
 Widget build(BuildContext context) {
    return Scaffold(
      key: widget._scaffoldStateContainingDrawerKey,
      drawer: BlocProvider(
        create: (BuildContext context) => drawerBloc,
        child: CustomNavigationDrawer(),
      ),
```
Here is my flutter doctor -v:
```
$ flutter doctor -v 
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-RS)
    • Flutter version 1.17.4 at /Users/lazarjovicic/flutter
    • Framework revision 1ad9baa8b9 (6 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lazarjovicic/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • SM G970F                  • RF8M728WTMP   • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by iapicca** [comment] 2020-06-24 07:50
Hi @lazarvgd 
From what I can see, the issue is related to the 3rd party plugin [bloc](https://pub.dev/packages/bloc) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/felangel/bloc/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 07:50 UTC

**Comment by lazarvgd** [comment] 2020-06-24 07:53
@iapicca thank you for pointing me in the right direction. There is no need to reopen the ticket for now. 
Thank you
