### ISSUE TITLE
Poor application performance. Empty app, scrolling low fps.

### ISSUE THREAD

**Issue by Ivan981508** [flutter/flutter#96663] opened 2022-01-14 17:25 UTC
## Steps to Reproduce

1. Use the flutter starter app
2. Embed any scrollable element there

**Expected results:** 
The application should not lose performance during normal scrolling. And also after the application exits the background, there is a drop in performance for a few seconds.

**Actual results:**
Rendering performance is greatly reduced. When scrolling the fps element, it can sink up to 15 frames, and jerks occur. Considering that this is a completely empty application, without any complex widgets, there should be no such problem at all. In the video, you can see a demonstration of the application on the device.

Note:

In fact, the problem is low performance (low fps) in all my applications, in an empty application and in a working project. This problem is not limited to the scrollable element, it just made it easier to reproduce the problem.
The demo application was created using the command: flutter build ios --release

[Video with a demonstration of the problem](https://www.youtube.com/watch?v=I_ZvkBcI0cs)

<details>
<summary>Code sample</summary>

```import 'package:flutter/material.dart';
import 'dart:math' as math;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
        itemCount: 100,
        itemBuilder: (BuildContext context, int index) {
          return Container(
            color: Color((math.Random().nextDouble() * 0xFFFFFF).toInt())
                .withOpacity(1.0),
            height: 100,
          );
        });
    
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.1 20G80 darwin-x64,
    locale ru-RU)
    • Flutter version 2.8.1 at /Users/ivanleontev/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33
      -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/ivanleontev/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more
      details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See
      https://flutter.dev/docs/get-started/install/macos#android-setup
      for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • E0D513E1-6FB1-4988-9464-0E303B234897 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               •
      web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.
```

```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

```
```

</details>

**Comment by nt4f04uNd** [comment] 2022-01-16 02:34
Duplicate of https://github.com/flutter/flutter/issues/96381 and https://github.com/flutter/flutter/issues/95838

**Closed by nt4f04uNd** 2022-01-16 02:34 UTC
