### ISSUE TITLE
Expose Flutter version in app

### ISSUE THREAD

**Issue by ueman** [flutter/flutter#80430] opened 2021-04-14 14:52 UTC
## Use case

For crash reporting it is useful to know which version of Flutter and which channel the app is using.

## Proposal

I would expect a class similar to Darts [Platform](https://api.dart.dev/stable/2.12.3/dart-io/Platform-class.html) so I can retrieve metadata about Flutter. It should be compatible with Flutter Web (which Dart's platform is not) and Flutter for mobile and desktop.

For example something like:

```dart
class FlutterInfo {
    String version = '2.0.0';
    String channel = 'stable';
    String dartVersion = '2.12.0';
    String dartChannel = 'stable';
}

```

 ## Releated issues:
https://github.com/flutter/flutter/issues/11481

**Comment by JagandeepBrar** [comment] 2021-04-14 18:37
This issue appears to be a duplicate of https://github.com/flutter/flutter/issues/61814.

**Comment by darshankawar** [comment] 2021-04-15 06:10
It indeed looks like similar to 61814.
@ueman Please check out that issue and follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-04-15 06:10 UTC
Labels: in triage
