### ISSUE TITLE
Crash when compiling null

### ISSUE THREAD

**Issue by NiBoTe** [flutter/flutter#92757] opened 2021-10-30 14:36 UTC
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Unhandled exception:
Crash when compiling null,
at character offset null:
Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:342:22)
#1      ClassBuilderImpl.buildTypesWithBuiltArguments (package:front_end/src/fasta/builder/class_builder.dart:566:44)
#2      ClassBuilderImpl.buildType (package:front_end/src/fasta/builder/class_builder.dart:617:12)
#3      NamedTypeBuilder.declarationBuildType (package:front_end/src/fasta/builder/named_type_builder.dart:266:27)
#4      NamedTypeBuilder.buildInternal (package:front_end/src/fasta/builder/named_type_builder.dart:295:28)
#5      NamedTypeBuilder.build (package:front_end/src/fasta/builder/named_type_builder.dart:244:12)
#6      FunctionTypeBuilder.build (package:front_end/src/fasta/builder/function_type_builder.dart:83:21)
#7      SourceTypeAliasBuilder.buildThisType (package:front_end/src/fasta/source/source_type_alias_builder.dart:154:16)
#8      TypeAliasBuilderImpl.buildTypeInternal (package:front_end/src/fasta/builder/type_alias_builder.dart:202:25)
#9      TypeAliasBuilderImpl.buildType (package:front_end/src/fasta/builder/type_alias_builder.dart:187:12)
#10     NamedTypeBuilder.declarationBuildType (package:front_end/src/fasta/builder/named_type_builder.dart:266:27)
#11     NamedTypeBuilder.buildInternal (package:front_end/src/fasta/builder/named_type_builder.dart:295:28)
#12     NamedTypeBuilder.build (package:front_end/src/fasta/builder/named_type_builder.dart:244:12)
#13     FormalParameterBuilder.build (package:front_end/src/fasta/builder/formal_parameter_builder.dart:131:17)
#14     FunctionBuilderImpl.buildFunction (package:front_end/src/fasta/builder/function_builder.dart:348:48)
#15     SourceProcedureBuilder.build (package:front_end/src/fasta/builder/procedure_builder.dart:288:5)
#16     SourceProcedureBuilder.buildMembers (package:front_end/src/fasta/builder/procedure_builder.dart:259:21)
#17     SourceClassBuilder.build.buildBuilders (package:front_end/src/fasta/source/source_class_builder.dart:152:25)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#19     Scope.forEach (package:front_end/src/fasta/scope.dart:524:12)
#20     SourceClassBuilder.build (package:front_end/src/fasta/source/source_class_builder.dart:180:11)
#21     SourceLibraryBuilder.buildBuilder (package:front_end/src/fasta/source/source_library_builder.dart:2695:31)
#22     SourceLibraryBuilder.build (package:front_end/src/fasta/source/source_library_builder.dart:1038:7)
#23     SourceLoader.buildComponent (package:front_end/src/fasta/source/source_loader.dart:1021:40)
#24     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:325:14)
<asynchronous suspension>
#25     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#26     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:304:38)
<asynchronous suspension>
#27     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#28     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:520:11)
<asynchronous suspension>
#29     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1132:11)
<asynchronous suspension>


#0      List.single (dart:core-patch/growable_array.dart:342:22)
#1      ClassBuilderImpl.buildTypesWithBuiltArguments (package:front_end/src/fasta/builder/class_builder.dart:566:44)
#2      ClassBuilderImpl.buildType (package:front_end/src/fasta/builder/class_builder.dart:617:12)
#3      NamedTypeBuilder.declarationBuildType (package:front_end/src/fasta/builder/named_type_builder.dart:266:27)
#4      NamedTypeBuilder.buildInternal (package:front_end/src/fasta/builder/named_type_builder.dart:295:28)
#5      NamedTypeBuilder.build (package:front_end/src/fasta/builder/named_type_builder.dart:244:12)
#6      FunctionTypeBuilder.build (package:front_end/src/fasta/builder/function_type_builder.dart:83:21)
#7      SourceTypeAliasBuilder.buildThisType (package:front_end/src/fasta/source/source_type_alias_builder.dart:154:16)
#8      TypeAliasBuilderImpl.buildTypeInternal (package:front_end/src/fasta/builder/type_alias_builder.dart:202:25)
#9      TypeAliasBuilderImpl.buildType (package:front_end/src/fasta/builder/type_alias_builder.dart:187:12)
#10     NamedTypeBuilder.declarationBuildType (package:front_end/src/fasta/builder/named_type_builder.dart:266:27)
#11     NamedTypeBuilder.buildInternal (package:front_end/src/fasta/builder/named_type_builder.dart:295:28)
#12     NamedTypeBuilder.build (package:front_end/src/fasta/builder/named_type_builder.dart:244:12)
#13     FormalParameterBuilder.build (package:front_end/src/fasta/builder/formal_parameter_builder.dart:131:17)
#14     FunctionBuilderImpl.buildFunction (package:front_end/src/fasta/builder/function_builder.dart:348:48)
#15     SourceProcedureBuilder.build (package:front_end/src/fasta/builder/procedure_builder.dart:288:5)
#16     SourceProcedureBuilder.buildMembers (package:front_end/src/fasta/builder/procedure_builder.dart:259:21)
#17     SourceClassBuilder.build.buildBuilders (package:front_end/src/fasta/source/source_class_builder.dart:152:25)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#19     Scope.forEach (package:front_end/src/fasta/scope.dart:524:12)
#20     SourceClassBuilder.build (package:front_end/src/fasta/source/source_class_builder.dart:180:11)
#21     SourceLibraryBuilder.buildBuilder (package:front_end/src/fasta/source/source_library_builder.dart:2695:31)
#22     SourceLibraryBuilder.build (package:front_end/src/fasta/source/source_library_builder.dart:1038:7)
#23     SourceLoader.buildComponent (package:front_end/src/fasta/source/source_loader.dart:1021:40)
#24     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:325:14)
<asynchronous suspension>
#25     withCrashReporting (package:front_end/src/fasta/crash.dart:121:12)
<asynchronous suspension>
#26     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:304:38)
<asynchronous suspension>
#27     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#28     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:520:11)
<asynchronous suspension>
#29     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1132:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

**Comment by NiBoTe** [comment] 2021-10-30 14:36
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (2 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

**Comment by or-adar** [comment] 2021-10-30 17:04
It is pretty hard to deduce the reason why this happens,
but from the look of it, your calling the `single` property of an empty list.
If that's the case, please notice that `single` throws an error if the list is empty or if it holds more than a single element.
To avoid this, check if the list is not empty and has exactly one element before invoking `single`
or use try-catch to handle StateError
or import `package:collection` which includes more null aware extensions of iterables and invoke `singleOrNull` instead.
If that's not your case, I'll need some code snippets or more information on what your attempting to do.

**Comment by alexmarkov** [comment] 2021-11-01 04:52
Looks like a CFE crash. /cc @johnniwinther

**Comment by darshankawar** [comment] 2021-11-01 08:09
Looks similar / related to https://github.com/flutter/flutter/issues/92679

Keeping it open for further insights from the team.

**Comment by CharlyKeleb** [comment] 2022-06-30 22:15
Did this issue got fixed @NiBoTe ?

**Comment by JaffaKetchup** [comment] 2022-07-10 10:45
I've just started getting this issue.

**Comment by johnniwinther** [comment] 2022-07-11 06:02
@JaffaKetchup Can you provide a repro?

**Comment by JaffaKetchup** [comment] 2022-07-11 06:07
Not really. Basically, I was making a package with example application.

The library used 2.17 with the super parameter at one point. The example app used 2.16 but used a path dependency on the parent directory (the library).

I solved by updating the example app to minimum 2.17.

**Comment by JaffaKetchup** [comment] 2022-07-11 06:16
Actually I kind of described that wrong.

So I've got 3 libraries:

1. A 3rd party library
2. My own library (the one I'm working in)
3. An example application for my own library

My library depended on the 3rd party library using the usual syntax, nothing special. My example app depended on the library by a path, and on the 3rd party library by a dependency_override to a Git repo.

I changed the minimum supported Dart version of my library to 2.17, as I needed to use a super constructor.

This threw the complication error in my example application.

One clue was that, if I could manage to get it to compile past this error (I can't remember exactly how unfortunately), then Dart said the super parameter I was supering from the 3rd party in my library did not exist, although my IDE never acknowledged this.

In the end, I made the dependency on the 3rd party the same in both the example and library.

**Comment by Vedsaga** [comment] 2022-08-27 15:43
@JaffaKetchup  sorry, I am not getting what you did that solve this issue pls could you share what have you removed from `pubspec.yaml`? that solved it?

**Comment by JaffaKetchup** [comment] 2022-08-27 15:44
@Vedsaga Sorry, but it was very specific to my project. Besides, I can't really remember any more. My apologies!

**Comment by Vedsaga** [comment] 2022-08-27 15:49
@JaffaKetchup actually I am also building my package and while running coverage command I am getting this error. I also have example folder.

```
C:\Bulding Packages\check_network>flutter clean
Deleting .dart_tool...                                              14ms
Deleting .flutter-plugins-dependencies...                            1ms
Deleting .flutter-plugins...                                         0ms

C:\Bulding Packages\check_network>flutter pub get
Running "flutter pub get" in check_network...                       3.7s

C:\Bulding Packages\check_network>flutter pub global run coverage:test_with_coverage
The Dart VM service is listening on http://127.0.0.1:8181/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2Fws
Unhandled exception:
Crash when compiling null,
at character offset null:
Null check operator used on a null value
#0      InferableTypeBuilderMixin.type (package:front_end/src/fasta/builder/type_builder.dart:392:29)
#1      InferableTypeBuilder.inferType (package:front_end/src/fasta/builder/omitted_type_builder.dart:155:12)
#2      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:2358:19)
#3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:532:14)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:407:33)
<asynchronous suspension>
#6      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:50)
<asynchronous suspension>
#7      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:572:11)
<asynchronous suspension>
#8      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1210:11)
<asynchronous suspension>


#0      InferableTypeBuilderMixin.type (package:front_end/src/fasta/builder/type_builder.dart:392:29)
#1      InferableTypeBuilder.inferType (package:front_end/src/fasta/builder/omitted_type_builder.dart:155:12)
#2      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:2358:19)
#3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:532:14)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:407:33)
<asynchronous suspension>
#6      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:50)
<asynchronous suspension>
#7      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:572:11)
<asynchronous suspension>
#8      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1210:11)
<asynchronous suspension>
00:00 +0 -1: loading test\src\current_intenet_status_test.dart [E]
  Failed to load "test\src\current_intenet_status_test.dart": unknown error
  SocketException: Write failed (OS Error: The pipe is being closed.
  , errno = 232), port = 0
  dart:io-patch/socket_patch.dart 1190:34                                _NativeSocket.write
  dart:io-patch/socket_patch.dart 1916:15                                _RawSocket.write
  dart:io-patch/socket_patch.dart 2356:18                                _Socket._write
  dart:io-patch/socket_patch.dart 2104:26                                _SocketStreamConsumer.write
  dart:io-patch/socket_patch.dart 2078:11                                _SocketStreamConsumer.addStream.<fn>
  dart:async/zone.dart 1399:47                                           _rootRunUnary
  dart:async/zone.dart 1300:19                                           _CustomZone.runUnary
  dart:async/zone.dart 1209:7                                            _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 339:11                                     _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 271:7                                      _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 774:19                               _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 648:7                                _StreamController._add
  dart:async/stream_controller.dart 596:5                                _StreamController.add
  dart:io/io_sink.dart 136:17                                            _StreamSinkImpl.add
  dart:io/io_sink.dart 269:5                                             _IOSinkImpl.write
  dart:io/io_sink.dart 289:5                                             _IOSinkImpl.writeln
  dart:io-patch/socket_patch.dart 2196:45                                _Socket.writeln
  dart:io/stdio.dart 342:11                                              _StdSink.writeln
  package:frontend_server_client/src/frontend_server_client.dart 322:21  FrontendServerClient._sendCommand
  package:frontend_server_client/src/frontend_server_client.dart 239:5   FrontendServerClient.accept
  package:test_core/src/runner/vm/test_compiler.dart 127:30              _TestCompilerForLanguageVersion._compile
  ===== asynchronous gap ===========================
  package:pool/pool.dart 127:14                                          Pool.withResource
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/platform.dart 157:9                    VMPlatform._spawnKernelIsolate
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/platform.dart 54:11                    VMPlatform.load
  ===== asynchronous gap ===========================
  package:test_core/src/runner/loader.dart 221:25                        Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/load_suite.dart 97:21                     new LoadSuite.<fn>.<fn>

00:00 +0 -1: Some tests failed.
```

**Comment by Vedsaga** [comment] 2022-08-27 15:50
I have even , search though the stackoverflow
 https://stackoverflow.com/questions/73072428/crash-when-compiling-null-at-character-offset-null-flutter-and-dart

Still no luck :(

**Comment by JaffaKetchup** [comment] 2022-08-27 15:52
Sorry @Vedsaga, I really can't help. My only suggestion is rolling back through your project progressively, until you can find a version that works. That should make it much more obvious where the problem is.

**Comment by Vedsaga** [comment] 2022-08-27 15:54
@JaffaKetchup mm, no worries really appreciate taking out time to response. I guess the only way is to go step-by-step

**Comment by JaffaKetchup** [comment] 2022-08-27 15:54
@Vedsaga No problem, sorry I couldn't be of more help.

**Comment by Vedsaga** [comment] 2022-08-27 15:56
> @Vedsaga No problem, sorry I couldn't be of more help.

no worries, need to sorry :)

**Comment by johnniwinther** [comment] 2022-08-29 06:20
The two crashes happen for different reasons (given the different stack-traces). The latter seems related to https://github.com/dart-lang/sdk/issues/49357

I'll look into both.

**Comment by johnniwinther** [comment] 2022-08-29 12:09
The original crash comes from code that uses a typedef like `typedef F = FutureOr Function();`. I cannot reproduce a crash and since the code in question has changed a lot since the crash was observed, I'd assume that the problem has been fixed. Otherwise a new issue should be created.

The second crash is fixed with https://dart-review.googlesource.com/c/sdk/+/256663

**Closed by johnniwinther** 2022-08-29 12:09 UTC
Labels: severe: crash, tool, dependency: dart, passed first triage
