### ISSUE TITLE
java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native when Internet Connection state is changed

### ISSUE THREAD

**Issue by PallaviSiddabathula** [flutter/flutter#30952] opened 2019-04-12 07:54 UTC
**Issue Description :** 
I am using the Connectivity package [https://pub.dartlang.org/packages/connectivity#-example-tab-](url) to check the internet connectivity state(i.e whether connected to mobile, wifi or none) in my app.

Now, I am facing a runtime issue. **When** i launch my app in **No_Internet** state, later after launching my app i enable Wifi access(**Internet_connected**) on the device. At this point my app abruptly crashes leaving the following stack trace.

**Logs**

E/AndroidRuntime(32563): FATAL EXCEPTION: main
E/AndroidRuntime(32563): Process: com.myappname.droid, PID: 32563
E/AndroidRuntime(32563): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 bqHint=4 (has extras) } in io.flutter.plugins.connectivity.ConnectivityPlugin$1@13796d7f
E/AndroidRuntime(32563): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:988)
E/AndroidRuntime(32563): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(32563): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(32563): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(32563): 	at android.app.ActivityThread.main(ActivityThread.java:7007)
E/AndroidRuntime(32563): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32563): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32563): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(32563): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime(32563): Caused by: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime(32563): 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:514)
E/AndroidRuntime(32563): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:444)
E/AndroidRuntime(32563): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
E/AndroidRuntime(32563): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:149)
E/AndroidRuntime(32563): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:142)
E/AndroidRuntime(32563): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:213)
E/AndroidRuntime(32563): 	at io.flutter.plugins.connectivity.ConnectivityPlugin$1.onReceive(ConnectivityPlugin.java:148)
E/AndroidRuntime(32563): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:978)
E/AndroidRuntime(32563): 	... 8 more

The output of running **`flutter doctor -v`** is below

[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17134.706], locale en-IN)
    • Flutter version 1.3.8 at C:\Users\Amigo\flutter
    • Framework revision e5b1ed7a7f (5 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Amigo\AppData\Local\Android\sdk2
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Amigo\AppData\Local\Android\sdk2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • SM J320F • 42008024d6661300 • android-arm • Android 5.1.1 (API 22)

**Comment by najeira** [comment] 2019-04-15 01:26
same as #29877

**Comment by fazil-augr** [comment] 2019-05-03 09:02
I am using flutter 'flutter_offline' same error is happening to me. In my play store console the same error is shown in crash report. It is effected in android version 9.

**Comment by jogboms** [comment] 2019-05-03 20:27
@fazil-augr I see you found this already, i would keep track of this as well.

**Comment by sanekyy** [comment] 2020-02-05 09:49
Problem still reproduce

```
Flutter 1.14.6 • channel dev • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (8 days ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```
![image](https://user-images.githubusercontent.com/18647037/73830521-ddbebf00-4815-11ea-880b-919994004f94.png)

**Comment by kw2019ltd** [comment] 2020-05-16 06:45
hi
getting below issue with Flutter (Channel unknown, v1.17.1)


Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222)
       at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35)
       at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

image

$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.17.1, on Linux, locale en_US.UTF-8)
• Flutter version 1.17.1 at /home/cirrus/sdks/flutter
• Framework revision f7a6a79 (3 days ago), 2020-05-12 18:39:00 -0700
• Engine revision 6bc433c6b6
• Dart version 2.8.2
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /opt/android-sdk-linux
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /opt/android-sdk-linux
• ANDROID_SDK_ROOT = /opt/android-sdk-linux
• Java binary at: /usr/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[!] Connected device
! No devices available
! Doctor found issues in 3 categories

**Comment by stuartmorgan** [comment] 2021-05-27 15:27
Closing as `connectivity` is deprecated in favor of [`connectivity_plus`](https://pub.dev/packages/connectivity_plus).

**Closed by stuartmorgan** 2021-05-27 15:27 UTC
Labels: P6, p: connectivity, p: first party, platform-android, plugin, severe: crash, severe: fatal crash
