### ISSUE TITLE
[MacOS ] English characters and numbers are garbled on MacOS 

### ISSUE THREAD

**Issue by cuishijie1991** [flutter/flutter#110133] opened 2022-08-24 02:09 UTC
It's weird, as shown in the picture. 
On macOS 10.12.6, the English characters and numbers displayed by the flutter app display garbled characters, while the numbers and English characters in the native view above are displayed normally.
The gibberish in the picture should have shown "新建标签1" and "72x50mm".
flutter version is 3, but I don't think it is the problem of flutter version.
This is the only mac I've seen with this situation, what do you guys think? Any help please
![d9f0d25e81b3ff307d97476dc564a3d](https://user-images.githubusercontent.com/17976216/186301998-d0728b98-42a0-4f86-a3c1-c0a59b2b1d1c.jpg)

**Comment by stuartmorgan** [comment] 2022-08-24 09:46
Duplicate of https://github.com/flutter/flutter/issues/57805

**Closed by stuartmorgan** 2022-08-24 09:46 UTC
Labels: in triage

**Comment by huycozy** [comment] 2022-08-24 10:08
Hi @cuishijie1991 
According to the duplicated issue that is mentioned above, there was a merged PR https://github.com/flutter/flutter/pull/107689 recently. So, please follow the instructions at https://github.com/flutter/flutter/pull/107689#issue-1305448700 to fix this issue. 
Thanks!

**Comment by cuishijie1991** [comment] 2022-08-26 07:41
> Duplicate of #57805



> Hi @cuishijie1991
> According to the duplicated issue that is mentioned above, there was a merged PR #107689 recently. So, please follow the instructions at [#107689 (comment)](https://github.com/flutter/flutter/pull/107689#issue-1305448700) to fix this issue.
> Thanks!

thanks a lot
