### ISSUE TITLE
LicensePage() in landscape mode throws Renderflex overflow error

### ISSUE THREAD

**Issue by mysticeti** [flutter/flutter#82169] opened 2021-05-10 09:06 UTC
## Steps to Reproduce

Call the following to show the default license page in the app.
```
LicensePage(
          applicationIcon: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Container(
                width: MediaQuery.of(context).size.width * 0.5,
                child:
                    Image(image: AssetImage('assets/logo/my_logo.png'))),
          ),
          applicationVersion: '0.0.1',
        );
```

**Expected results:**  No issues just like in the portrait orientation.
**Actual results:** Only in landscape orientation there is RenderFlex overflow error due to CircularProgressIndicator() widget. 

<details>
  <summary>Logs</summary>
```
The following assertion was thrown during layout:
A RenderFlex overflowed by 43 pixels on the bottom.

The relevant error-causing widget was: 
  LicensePage file:///D:/Geovation/flutter_sandbox/lib/sandbox_license/sandbox_license_page.dart:28:16
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#2861e relayoutBoundary=up4 OVERFLOWING
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=748.9, 0.0<=h<=215.4)
...  size: Size(748.9, 215.4)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
====================================================================================================
```

```

</details>

**Comment by darshankawar** [comment] 2021-05-10 12:38
@mysticeti 
It's probably because of the way you are setting the width:

`width: MediaQuery.of(context).size.width * 0.5`

If you set it to 0.1, you should get expected behavior.

**Comment by mysticeti** [comment] 2021-05-10 16:37
If I reduce the container width then the error does go away because CircularProgressIndicator() is visible on screen but if the logo increases in size then the RenderFlex error pops up. The error occurs at the bottom of the screen in landscape mode, not on the sides. The error goes away when listview shows up with all the licenses.

**Comment by TahaTesser** [comment] 2021-12-22 10:07
Hi @mysticeti 
I cannot reproduce this anymore in landscape

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: LicensePage(
        applicationIcon: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SizedBox(
            width: MediaQuery.of(context).size.width * 0.5,
            child: const Image(
              image: NetworkImage('https://i.imgur.com/h2tXDJX.png'),
            ),
          ),
        ),
        applicationVersion: '0.0.1',
      ),
    );
  }
}
``` 
	
</details>

Closing as fixed, if the problem persists, please let me know

**Closed by TahaTesser** 2021-12-22 10:07 UTC
Labels: framework, f: material design, a: quality, a: layout, has reproducible steps, found in release: 2.3
