### ISSUE TITLE
"Error: Permission denied (publickey)" while pub get Private Github Repo in VS Code Flutter

### ISSUE THREAD

**Issue by vin-fandemand** [flutter/flutter#59073] opened 2020-06-09 14:56 UTC
I wanted to add a private repo from Github to my dependencies. As per the [https://dart.dev/tools/pub/dependencies#git-packages](https://dart.dev/tools/pub/dependencies#git-packages ) , I added the SSH link from Github in my dependencies. For that 

1. I configured the SSH key and added it to Github as per [Github's guidelines](https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh).
2. I tested the connection  running `ssh -vT git@github.com` and got welcome message
3. My config
```
Host *
 HostName github.com
 User git
 IgnoreUnknown AddKeysToAgent,UseKeychain
 UseKeychain yes
 AddKeysToAgent yes
 IdentityFile ~/.ssh/id_rsa
```
Despite all this, I kept getting "Error: Permission denied (publickey)" in VSCode, when I try to do `pub get`. After a long night and frustration, when I was about to give up, I decided to do `pub get` in `git bash` , and it worked. To me, it seems this is some kind of OS problem and VSCode is looking for the key in some other place. On the other hand, any change to the config file is reflected in VSCode logs.

I have a work around for this now. But one would wish the functionality to work in VSCode as well.

**Comment by iapicca** [comment] 2020-06-10 08:35
HI @vin-fandemand 
If you are experiencing the issue only with VS Code 
and not with Android Studio or terminal,
then following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), 
the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-10 08:35 UTC
Labels: created via support template
