### ISSUE TITLE
NoSuchMethodError: The method 'setOption' was called on null

### ISSUE THREAD

**Issue by ccornici** [flutter/flutter#32578] opened 2019-05-12 08:44 UTC
```
    var httpClient = HttpClient()..connectionTimeout = const Duration(seconds: 5);
    var request = await httpClient.getUrl(url);
```

I modified my code to now use a timeout and this happens:

```
D/skia    ( 5333): Program linking failed.
E/flutter ( 5333): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'setOption' was called on null.
E/flutter ( 5333): Receiver: null
E/flutter ( 5333): Tried calling: setOption(Instance of 'SocketOption', true)
```

```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version
    10.0.17763.379], locale en-US)
    • Flutter version 1.2.1 at C:\Software\flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at C:\Users\claud\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[!] VS Code (version 1.33.1)
    • VS Code at C:\Users\claud\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9
      (API 28) (emulator)

! Doctor found issues in 1 category.

```

**Comment by kangwang1988** [comment] 2019-05-12 08:47
@ccornici 
Thank you for reporting this. A minimal demo project which can reproduce this issue would be more helpful to diagnose. Can you create one in GitHub?

**Comment by nemethmik** [comment] 2019-08-04 18:36
You should reopen it, this is very easy to reproduce. Here is my example and instructions including a test script [When timeout is raised on HttpClient because of IP address issues, NoSuchMethodEror is thrown instead of SocketException](https://gist.github.com/nemethmik/ed3eec698ae9afb1c08a6fafe240a56a)
This issue happens when the IP address is not valid, or the port is not listening. Normally, within 30 seconds or so a nice SocketException is thrown, but when we don't want to wait that long we set the timeout on the HTTP client of dart:io. Instead of the SocketException we have a NuSuchMethodError.

**Comment by rockingdice** [comment] 2019-08-10 00:39
Met this issue too. I'm downloading 48 files from where the connection is not stable. 
This is happening when the request is timed out.

```
HttpClient client = HttpClient();
client.connectionTimeout = Duration(milliseconds: 5000);
```

```
E/flutter (17811): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'setOption' was called on null.
E/flutter (17811): Receiver: null
E/flutter (17811): Tried calling: setOption(Instance of 'SocketOption', true)
E/flutter (17811): null
```

@jonahwilliams Could you please take a look at this?

**Comment by jonahwilliams** [comment] 2019-08-10 00:42
@zanderso mentioned recently that SocketExceptions may be thrown into an incorrect zone. That would prevent them from being caught in futures or try/catch.

**Comment by rockingdice** [comment] 2019-08-10 01:02
Thanks for the response! Actually, this issue is pretty easy to reproduce - just set the connectionTimeout to 100 ms or less, it should trigger the timeout and the unhandled exception.

**Comment by zanderso** [comment] 2019-08-12 16:27
This bug is unrelated to the Zone issue. A connection timeout could take either one of two paths through the http connection setup code. This CL https://dart-review.googlesource.com/c/sdk/+/112742 will make sure they both result in a `SocketException` as the docs indicate.

**Comment by zanderso** [comment] 2019-08-13 14:30
The fix to the Dart SDK has rolled into Flutter's master channel. If you're able to give this another try that would be great.

**Comment by rockingdice** [comment] 2019-08-14 00:18
Thanks! I'll try it soon.

**Comment by iapicca** [comment] 2020-01-15 12:53
Hi @ccornici 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by ccornici** [comment] 2020-01-15 14:27
> Hi @ccornici
> are you still experiencing this issue with the latest stable version of flutter?
> If so could you please provide your updated `flutter doctor -v`
> and your `flutter run --verbose` and a reproducible minimal code sample
> or the steps to reproduce the problem.
> Thank you

I haven't tried this and neither do I use flutter anymore, so maybe you can ask the other members of the thread about it, or just close the issue and see if anyone else suggests a to reopen it.

**Comment by iapicca** [comment] 2020-01-16 06:16
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2020-01-16 06:16 UTC
