### ISSUE TITLE
flutter packages get faild on building and installing the Flutter gallery app

### ISSUE THREAD

**Issue by majidfathi69** [flutter/flutter#26648] opened 2019-01-16 16:30 UTC
According to the [this link](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery#building-and-installing-the-flutter-app) I try to building and installing the Flutter app. So I run `flutter upgrade` command and the following error is displayed:

`Because flutter_gallery depends on flutter_driver any from sdk which depends on process 3.0.9, process 3.0.9 is required.`

`So, because flutter_gallery depends on process 3.0.5, version solving failed.`

`pub get failed (1)`

**Comment by zoechi** [comment] 2019-01-16 17:09
Please add the output of `flutter doctor -v`.

**Comment by majidfathi69** [comment] 2019-01-16 17:59
`flutter doctor -v`


[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/mohsen/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/mohsen/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • C6903 • BH908QSK06 • android-arm • Android 5.1.1 (API 22)

• No issues found!

**Comment by majidfathi69** [comment] 2019-01-16 18:49
I tried `flutter channel beta` and had the same result.

**Comment by tatemz** [comment] 2019-01-24 22:35
Running `flutter update-packages --force-upgrade` and then resolving each dependency one-by-one worked for me, but then running the app had all sorts of compilation errors during `./gradlew assembleDebug`

**Comment by dnfield** [comment] 2019-01-25 17:12
This should be fixed now - please feel free to reopen if it's not!

**Closed by dnfield** 2019-01-25 17:12 UTC
Labels: team, team: gallery

**Comment by dnfield** [comment] 2019-01-25 17:14
Actually, I'm not sure this can be fixed - I suspect `flutter upgrade` in gallery is going to mess up pinned dependencies elsewhere.  However, this is a duplicate of https://github.com/flutter/flutter/issues/24292
