### ISSUE TITLE
On some devices, native keyboard cannot be closed with back button

### ISSUE THREAD

**Issue by ksankumar** [flutter/flutter#66036] opened 2020-09-17 16:00 UTC
Device: Samsung S8, S9
Branch: master

android native keyboard not able to close when we tab hide keyboard and back button in samsung devices with **master** branch. Works fine with **stable** branch. 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Keyboard Input')),
      body: Center(
        child: TextField(),
      ),
    );
  }
}
```
```
flutter doctor
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.22.0-10.0.pre.222, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.49.0)
[√] Connected device (3 available)
• No issues found!
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3350098/93499704-56741680-f8e1-11ea-954a-96a5ebbce73c.gif)

**Comment by ksankumar** [comment] 2020-09-17 16:26
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3350098/93499485-0e54f400-f8e1-11ea-8669-89038adc0a86.gif)

**Comment by chocolatkey** [comment] 2020-09-17 19:19
I have the same problem, using beta 1.22.0-12.1.pre. `FocusScope.of(context).unfocus();` dismisses the keyboard, but as soon as the textfield is selected again, this happens.

**Comment by hamdikahloun** [comment] 2020-09-17 21:46
Hi @ksankumar 
Can you provide please the devices info (Android Version, Model Number...)

**Comment by ksankumar** [comment] 2020-09-17 22:03
@chocolatkey 
![Screenshot_20200917-180018_Settings](https://user-images.githubusercontent.com/3350098/93532959-02345b00-f910-11ea-8c83-0b263b37868f.jpg)

**Comment by chocolatkey** [comment] 2020-09-17 23:19
![Screenshot_20200917-161911_Settings.jpg](https://user-images.githubusercontent.com/13407784/93537858-8206f900-f901-11ea-9ffa-909ed7f36615.jpg)

**Comment by jason-simmons** [comment] 2020-09-18 01:10
Reproduced this on a Nexus 7

This regressed with https://github.com/flutter/flutter/commit/0d8de393aa07b6f4d43d1082dc5fe20d101d25d2

@mdebbar @gspencergoog @chunhtai

**Comment by TahaTesser** [comment] 2020-09-18 07:58
I cannot reproduce on Realme device
and
@darshankawar  tested on S10+, latest master, also doesn't reproduce for him

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Keyboard Input')),
      body: Center(
        child: TextField(),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.251, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.251 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision d26268bb9e (7 hours ago), 2020-09-18 09:06:26 +0900
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (4 available)            
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021 x86_64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details> 

Labelling the issue base on https://github.com/flutter/flutter/issues/66036#issuecomment-694588621

**Comment by hamdikahloun** [comment] 2020-09-18 09:13
I cannot reproduce on:

SM-G950F (Samsung Galaxy S8)
SM-F916U (Samsung Galaxy Z Fold 2)
SM-G960F (Samsung Galaxy S9)

<details>
  <summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Keyboard Input')),
      body: Center(
        child: TextField(),
      ),
    );
  }
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.40, on Microsoft Windows [version 10.0.19041.508], locale fr-FR)
    • Flutter version 1.22.0-10.0.pre.40 at D:\flutter
    • Framework revision 9234389a59 (36 minutes ago), 2020-09-18 09:25:19 +0100
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\hamdi\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\hamdi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30225.117
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\hamdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (5 available)
    • SM G960F (mobile) • localhost:63921 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [version 10.0.19041.508]
    • Web Server (web)  • web-server      • web-javascript • Flutter Tools
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```

</details>

**Comment by dujianchi** [comment] 2020-09-26 08:10
reproduce on Xiaomi(MIUI12/Android10) and Huawei(EMUI8/Android8).
code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TextField(
        decoration:
            InputDecoration(labelText: 'this is a annoying input field'),
      ),
    );
  }
}
```
doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [Version 10.0.18363.1082], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (4 available)

! Doctor found issues in 1 category.
```

![Uploading screenrecorder.gif…]()

**Comment by ganeshshirole** [comment] 2020-09-26 08:55
Same issue is there on beta version please resolve this as soon as possible.

**Comment by chinmaygarde** [comment] 2020-09-28 18:02
cc @gspencergoog @jason-simmons. We should revert https://github.com/flutter/flutter/commit/0d8de393aa07b6f4d43d1082dc5fe20d101d25d2 and cherry pick it into the beta.

**Comment by jason-simmons** [comment] 2020-09-28 19:58
It looks like this was fixed by https://github.com/flutter/flutter/commit/0d945a1a5643ab9d1091e9bc56aed4b281f05463

@pcsosinski @christopherfujino That change should be cherry picked.

**Closed** 2020-09-28 20:07 UTC
Labels: P2, a: text input, cp: 1.22, e: device-specific, engine, found in release: 1.22, framework, passed first triage, platform-android
