### ISSUE TITLE
webview_flutter will automatically stitch cookie= in the headers on the android side, can it be removed

### ISSUE THREAD

**Issue by lullabyys** [flutter/flutter#129622] opened 2023-06-27 10:29 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1、代码处设置 

```dart
this.webViewController.loadRequest(
                    WebViewRequest(
                        uri: Uri.parse(widget.url),
                        method: WebViewRequestMethod.get,
                        headers: {
                          "Cookie": loginCookie,
                          "Access-Control-Allow-Origin": "*",
                        }),
                  );
```

### Expected results

Cookie: JSESSIONID=fe203856-585e-413c-8138-622061ebe5ac

### Actual results

Cookie:  Cookie=JSESSIONID=fe203856-585e-413c-8138-622061ebe5ac

### Code sample

```
this.webViewController.loadRequest(
                    WebViewRequest(
                        uri: Uri.parse(widget.url),
                        method: WebViewRequestMethod.get,
                        headers: {
                          "Cookie": loginCookie,
                          "Access-Control-Allow-Origin": "*",
                        }),
                  );
```

### Screenshots or Video

![企业微信截图_34996f46-455a-4017-a10f-25e2f4efeec2](https://github.com/flutter/flutter/assets/48517796/f79a66c8-7970-4826-b40b-5738ba490723)

![企业微信截图_8fa0e62d-c866-478c-8c84-faece5ba9f62](https://github.com/flutter/flutter/assets/48517796/01854a6a-da0c-44b1-85aa-550bb9181c5f)

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 13.3.1 22E261 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/xuefei/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (1 year, 2 months ago), 2022-04-18 09:55:37
      -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/xuefei/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.79.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • PDSM00 (mobile)             • BIV8CE9D8HEANRBM          • android-arm64  •
      Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 13 (API 33) (emulator)
    • kl的iPhone (mobile)          • 00008110-000E6C293A6B801E • ios            •
      iOS 15.4 19E241
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 114.0.5735.198

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by 0xj0hn** [comment] 2023-06-27 10:49
Could you say what is assigned to `loginCookie` variable?

**Comment by 0xj0hn** [comment] 2023-06-27 14:56
> Hi @lullabyys. I see you are on an older version of flutter. Can you upgrade to the latest version to confirm this issue still persists? If it does, Kindly provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

I guess the problem should be in his code. The `loginCookie` might not have been in the correct form.

**Comment by lullabyys** [comment] 2023-06-28 01:14
> Could you say what is assigned to `loginCookie` variable?
'loginCookie'是从接口请求中获得的，在此处的内容是‘JSESSIONID=fe203856-585e-413c-8138-622061ebe5ac’

**Comment by lullabyys** [comment] 2023-06-28 01:16
> Hi @lullabyys. I see you are on an older version of flutter. Can you upgrade to the latest version to confirm this issue still persists? If it does, Kindly provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

你好，感谢你的回复，因为我的项目使用的是旧版本的flutter，因此无法升级到最新版确认此问题，你能告诉我是否还有其他办法吗

**Comment by lullabyys** [comment] 2023-06-28 01:17
> Could you say what is assigned to `loginCookie` variable?

'loginCookie'是从接口请求中获得的，在此处的内容是‘JSESSIONID=fe203856-585e-413c-8138-622061ebe5ac’

**Comment by lullabyys** [comment] 2023-06-28 01:19
> 

‘loginCookie’ 是一个字符串，请求中的headers中的值我知道可以是字符串，请问还有其他的格式吗

**Comment by lullabyys** [comment] 2023-06-28 01:19
> > Hi @lullabyys. I see you are on an older version of flutter. Can you upgrade to the latest version to confirm this issue still persists? If it does, Kindly provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> I guess the problem should be in his code. The `loginCookie` might not have been in the correct form.

‘loginCookie’ 是一个字符串，请求中的headers中的值我知道可以是字符串，请问还有其他的格式吗

**Comment by danagbemava-nc** [comment] 2023-06-28 06:36
Hi @lullabyys, the current version of webview_flutter has changed significantly since the last version that supports the version of flutter you're using. Can you create a dummy project using the latest version of flutter and webview_flutter to see if you still have this issue? 

If you do, please provide a complete minimal reproducible code sample so that we can investigate this issue.

Thank you

**Comment by 0xj0hn** [comment] 2023-06-28 08:23
> 

What I meant by correct form, is a correct structure. I meant if you have assigned "Cookie=JSESSIONID=fe203856-585e-413c-8138-622061ebe5ac", you're doing a mistake there.

But If you have just "JSESSIONID=fe203856-585e-413c-8138-622061ebe5ac" in your variable, the issue is somewhere else.

**Comment by lullabyys** [comment] 2023-06-29 01:11
> Hi @lullabyys, the current version of webview_flutter has changed significantly since the last version that supports the version of flutter you're using. Can you create a dummy project using the latest version of flutter and webview_flutter to see if you still have this issue?
> 
> If you do, please provide a complete minimal reproducible code sample so that we can investigate this issue.
> 
> Thank you

你好，感谢你的回复，我会找时间尝试你说的方法，有结果后我会再次回复你

**Comment by lullabyys** [comment] 2023-06-29 01:13
> > 'loginCookie' is a string. I know that the value in the headers in the request can be a string. Is there any other format?
> 
> What I meant by correct form, was an appropriate/right structure. I meant if you have assigned "Cookie=JSESSIONID=fe203856-585e-413c-8138-622061ebe5ac", you're doing a mistake there.
> 
> But If you have just "JSESSIONID=fe203856-585e-413c-8138-622061ebe5ac" in your variable, the issue is somewhere else.

好的，感谢，我明白你说的意思了，正如你所说问题出在其他地方，我也正在寻找这个问题

**Closed** 2023-07-20 07:08 UTC
Labels: waiting for customer response, in triage
