### ISSUE TITLE
Text don't get ellipses when wrapped with in the Wrap widget

### ISSUE THREAD

**Issue by Yuvaraj-Gajaraj** [flutter/flutter#125466] opened 2023-04-25 08:36 UTC
Facing an issue in the wrap widget as per the below code snippet.

Sample Code:
```dart
`import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

List<String> textList = <String>[
  'Hi',
  'How are you',
  'I use fastLineSeries for real time data without setting interval/min/max on the primary Y-axis. It all works fine',
  'You can achieve your requirement with the help of the rangePadding property in the NumericAxis it will help you to eliminate the unwanted range in the axis and calculate the range based on the visible point. We have shared the related UG documentation below for your reference.',
  'Welcome to Flutter',
];

List<Icon> icons = const <Icon>[
  Icon(color: Colors.red, Icons.circle),
  Icon(color: Colors.blue, Icons.rectangle),
  Icon(color: Colors.green, Icons.access_alarm),
  Icon(color: Colors.yellow, Icons.star),
  Icon(color: Colors.brown, Icons.pentagon),
];

class _MyHomePageState extends State<MyHomePage> {
  _MyHomePageState();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SizedBox(
            height: 400,
            child: Wrap(
              children: List<Widget>.generate(
                textList.length,
                (int index) {
                  return _buildRowWidget(index);
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

Widget _buildRowWidget(int index) {
  List<Widget> child = <Widget>[
    icons[index],
    const SizedBox(width: 5),
    Text(
      textList[index],
      style: const TextStyle(overflow: TextOverflow.ellipsis),
    ),
  ];
  return Row(children: child);
}
```
<img width="360" alt="image" src="https://user-images.githubusercontent.com/82077349/230908971-611fd536-7753-4654-8672-bd787024d333.png">

`

_Originally posted by @LavanyaGowtham2021 in https://github.com/flutter/flutter/issues/123599#issuecomment-1501808970_

**Comment by huycozy** [comment] 2023-04-25 10:19
Hi @Yuvaraj-Gajaraj 
This issue has the same reason as I pointed out at https://github.com/flutter/flutter/issues/123599#issuecomment-1490065367. This is an issue of Text and Row. You should wrap the Text widget inside Expanded to make sure Text can only be as wide as Row.  

<details>
<summary>Updated sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

List<String> textList = <String>[
  'Hi',
  'How are you',
  'I use fastLineSeries for real time data without setting interval/min/max on the primary Y-axis. It all works fine',
  'You can achieve your requirement with the help of the rangePadding property in the NumericAxis it will help you to eliminate the unwanted range in the axis and calculate the range based on the visible point. We have shared the related UG documentation below for your reference.',
  'Welcome to Flutter',
];

List<Icon> icons = const <Icon>[
  Icon(color: Colors.red, Icons.circle),
  Icon(color: Colors.blue, Icons.rectangle),
  Icon(color: Colors.green, Icons.access_alarm),
  Icon(color: Colors.yellow, Icons.star),
  Icon(color: Colors.brown, Icons.pentagon),
];

class _MyHomePageState extends State<MyHomePage> {
  _MyHomePageState();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SizedBox(
            height: 400,
            child: Wrap(
              children: List<Widget>.generate(
                textList.length,
                (int index) {
                  return _buildRowWidget(index);
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

Widget _buildRowWidget(int index) {
  List<Widget> child = <Widget>[
    icons[index],
    const SizedBox(width: 5),
    Expanded(child: Text(
      textList[index],
      style: const TextStyle(overflow: TextOverflow.ellipsis),
    )),
  ];
  return Row(children: child);
}

```
</details>

![Screenshot 2023-04-25 at 17 18 23](https://user-images.githubusercontent.com/104349824/234247716-8b87f052-7461-4fa9-94d2-1c9d6d69771c.png)

Since it is expected behavior, I will close the issue from here. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Thanks!

**Closed by huycozy** 2023-04-25 10:19 UTC
Labels: in triage
