### ISSUE TITLE
Transforming Clipped Images results in strange clipping behaviour

### ISSUE THREAD

**Issue by GSamuel** [flutter/flutter#69531] opened 2020-11-01 15:01 UTC
I run the build on flutter web.

## Steps to Reproduce:

```
class _TestPageState extends State<TestPage> {

  double x = 0;
  double y = 0;
  double z = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(

      body: Stack(children: [
        Center(
          child: Transform(
            transform: Matrix4.identity()
              ..rotateX(x)..rotateY(y)..rotateZ(z),
            alignment: Alignment.center,
            child: Container(
              width: 300,
              height: 300,
              color: Colors.blue,
              child: ClipOval(
                  child: Image.network('https://cdn.jpegmini.com/user/images/slider_puffin_before_mobile.jpg',) 
              ),
            ),
          ),
        ),
        GestureDetector(
            onPanUpdate: (details) {
              setState(() {
                y = y - details.delta.dx / 1000;
                x = x + details.delta.dy / 1000;
                //z = z + details.delta.dy / 1000;
              });
            }
        ),
      ]),
    );
  }
}
```

**Expected results:**

Expected to see rotated blue container where the image is rotated exactly the same way as the container
Image should be a skewed circle touching all edges of the container, instead of being chopped off.

**Actual results:**

It looks like the clipping isn't transformed correctly and not in the same way the container is transformed.

** Apparently wrapping the The Container with Opactiivty fixes the problem, but that shouldn't be required **

```
child: Opacity(
              opacity: 0.99,
              child: Container(
                width: 300,
                height: 300,
                color: Colors.blue,
                child: ClipOval(
                    child: Image.network('https://cdn.jpegmini.com/user/images/slider_puffin_before_mobile.jpg',) 
                ),
              ),
            ),
```

Before rotating:
![non-rotated-image](https://user-images.githubusercontent.com/2345381/97806230-e59f7880-1c5a-11eb-8932-4546c343f6c5.PNG)
After rotating on y axis:
![rotated_around_single_axis](https://user-images.githubusercontent.com/2345381/97806232-e6d0a580-1c5a-11eb-89f4-76e93b6f1557.PNG)
After rotating on y and x axis:
![rotated_around_multiple_axis](https://user-images.githubusercontent.com/2345381/97806231-e6380f00-1c5a-11eb-8744-8d3155491aed.PNG)

<details>

```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18362.1139], locale nl-NL)
    • Flutter version 1.23.0-18.1.pre at D:\tools\flutter_v1.12.13\flutter
    • Framework revision 198df796aa (2 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\tools\Android\Android_SDK
    X Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at D:\tools\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.51
```

</details>

**Comment by TahaTesser** [comment] 2020-11-02 12:21
hI @GSamuel 
I can reproduce the issue on the `beta`, however, the seems to be fixed on `dev` 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    String url = ''; // Initialize image with empty url string

    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Image.network(
          url,
          width: 50,
          height: 50,
          errorBuilder: (_, __, ___) {
            return Image.asset(
              "assets/flutter.png",
              width: 50,
              height: 50,
            );
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          setState(() {
            // Update with legal url, However, the image still enters the wrong mode.
            url = "https:/i.imgur.com/QCNbOAo.png";
          });
        },
      ),
    );
  }
}

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.24.0-6.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-GB)
    • Flutter version 1.24.0-6.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 13896b3bd1 (4 days ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.1
    • macOS (desktop)      • macos                     • darwin-x64     • Mac OS
      X 10.15.7 19H2 darwin-x64
    • Web Server (web)     • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 86.0.4240.111

• No issues found!

```

</details>

Can you please upgrade to the latest  `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

labelling the issue to rack fix into `beta` channel

**Comment by ferhatb** [comment] 2020-11-04 18:16
Verified this was fixed by https://github.com/flutter/goldens/pull/126

**Closed by ferhatb** 2020-11-04 18:16 UTC
Labels: found in release: 1.23, framework, has reproducible steps, platform-web
