### ISSUE TITLE
[camera][camera_avfoundation]  hope to support ios proraw 

### ISSUE THREAD

**Issue by 385841539** [flutter/flutter#130700] opened 2023-07-17 09:51 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i want  to get 6800*8000 picture , need ios promax。

### Expected results

i want  to get 6800*8000 picture , need ios promax。

### Actual results

i want  to get 6800*8000 picture , need ios promax。

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment] 2023-07-17 13:45
Hi @385841539
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly. 
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Also, if it is a proposal, you can use the proposal template to explain your proposition.
Closing this issue, since little information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-07-17 13:45 UTC
Labels: in triage

**Comment by 385841539** [comment] 2023-07-18 03:32
yes， is there plane for support ios proraw img?
