### ISSUE TITLE
[iOS 16] Semantics seems to be broken

### ISSUE THREAD

**Issue by Attiv** [flutter/flutter#113685] opened 2022-10-19 09:05 UTC
I use Semantics in my app and it works fine on iOS 14 devices. While on iOS 16 devices, when tapping the screen, it is marked as a whole container. So does the Semantics support iOS 16? or have some other ways?

**Comment by Attiv** [comment] 2022-10-19 09:34
It doesn't work in Column such as: 
```
Semantics(
                explicitChildNodes: true,
                child: Column(
                  children: [
                    Semantics(
                      child: Text(
                        'Hello',
                        style: TextStyle(
                          fontSize: 24,
                        ),
                      ),
                    ),
                    Semantics(
                      child: Text(
                        'Word',
                        style: TextStyle(
                          fontSize: 24,
                        ),
                      ),
                    )
                  ],
                ),
              )
```

**Comment by Attiv** [comment] 2022-10-19 09:45
I found it doesn't work under a GestureDetector on iOS16

**Comment by Attiv** [comment] 2022-10-19 12:11
```
Semantics(
label: 'test', 
explicitChildNodes: true,         
child: Column(children:[])
),
```
Can not mark the children widgets if set label attributes on iOS16, and it works fine on iOS14.

**Comment by danagbemava-nc** [comment] 2022-10-19 12:34
Hi @Attiv, can you share a recording of the issue you're facing? Please also provide a complete sample with steps to reproduce. 

Please also provide the output of `flutter doctor -v`. 

Finally, can you take a look at https://github.com/flutter/flutter/issues/113377 to see if it is similar to your issue? 

Thank you

**Comment by danagbemava-nc** [comment] 2022-10-20 06:07
Hi @Attiv, this is a duplicate of https://github.com/flutter/flutter/issues/113377. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Please upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2022-10-20 06:07 UTC
Labels: in triage
