### ISSUE TITLE
input Chinese on iOS, cursor will move in wrong way

### ISSUE THREAD

**Issue by huangyumeng123** [flutter/flutter#99748] opened 2022-03-08 09:34 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. When I input **chinese** strings on **iOS**,   I move cursor to center then I input a new char.

**Expected results:** The cursor shouldn't jump

**Actual results:** The cursor will move to last position automatically.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'extended_text_field demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyPage(),
    );
  }
}

class MyPage extends StatefulWidget {
  const MyPage({Key key}) : super(key: key);

  @override
  _MyPageState createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("iOS composing bug"),
      ),
      body: SizedBox(height: 50, child: TextField()),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
no error message
```

```
no error message
```

```
➜  ~ flutter doctor -v



[✓] Flutter (Channel unknown, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.5.1 at /Users/huangyumeng/flutter/sdk/flutter
    • Upstream repository unknown
    • Framework revision ffb2ecea52 (6 months ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
    • Pub download mirror https://pub.flutter-io.cn/
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/huangyumeng/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone (2) (mobile) • 07764bc3e54f20576249b16f73d1a6311787f474 • ios
      • iOS 14.7.1 18G82
    • macOS (desktop)     • macos                                    • darwin-x64
      • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)        • chrome                                   • web-javascript
      • Google Chrome 99.0.4844.51

! Doctor found issues in 1 category.
```

</details>

**Comment by huangyumeng123** [comment] 2022-03-08 09:36
[https://mkpub-release.menkor.com/affair/590919/chat/520611/n4jE9kyUkG.MP4](url)

**Comment by huangyumeng123** [comment] 2022-03-08 09:39
https://user-images.githubusercontent.com/54969026/157209911-ba194dde-08b2-481f-88e9-9598832db444.MP4

**Comment by maheshmnj** [comment] 2022-03-08 14:06
Hi @huangyumeng123, Thanks for filing the issue. I am unable to reproduce the issue on `stable 2.10.3`, I believe this has been fixed recently, Please try upgrading to latest `stable 2.10.3` and see if it resolves the issue for you.


https://user-images.githubusercontent.com/31410839/157253548-ca37df04-49bb-498c-bcad-a1a0997499a4.mov



<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by huangyumeng123** [comment] 2022-03-09 01:48
You can try change cursor position by touching screen in typing , then you input a new char and you will see the bug. 
I try the latest version and it's same.

**Comment by huangyumeng123** [comment] 2022-03-09 01:53
I found another similar issue: 
https://github.com/flutter/flutter/issues/86471

**Comment by huangyumeng123** [comment] 2022-03-09 03:08
It seems that change selection in **composing state** is not working, when I input new char it will always inserted at string tail. 
And the strange thing is when I input eng words, this bug will disappear. I think the [FlutterTextInputPlugin.mm](https://engine.chinmaygarde.com/ios_2framework_2_source_2_flutter_text_input_plugin_8mm_source.html) has some problem.

**Comment by maheshmnj** [comment] 2022-03-09 06:23
Thanks for the update @huangyumeng123, I don't see cursor moving to end but rather the old string is entered on changing the cursor position manually, which looks related to https://github.com/flutter/flutter/issues/99652


https://user-images.githubusercontent.com/31410839/157384153-bde34833-0e44-43f2-8cba-03daabf1b909.mov



> I found another similar issue: https://github.com/flutter/flutter/issues/86471

If this issue is exactly the same, You could followup on that issue and we should close this as a duplicate?

**Closed** 2022-03-10 08:03 UTC
Labels: waiting for customer response, in triage
