### ISSUE TITLE
camera plugin: Image always rotates 270 on server

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#18391] opened 2018-06-12 05:56 UTC
I am working on a production app which I have convinced the company I currently work in to allow me to port it to Flutter and it was going all great till we did the first test only to notice that all images coming from the flutter app front-facing camera are rotated 270 degrees no matter the camera orientation.
A few to note is that by default the app is locked to portrait mode, there is no landscape mode. Also the front-facing camera is very key part of the apps process.

I am using the camera 0.2.1 in the app and whenever I take a picture with the front-facing camera and send to the server the image is rotated 270 degrees. even when I intentionally or manually give the jpeg rotation a const orientation.

I will very much appreciate all the help to get this resolved so the app can go live thanks

## Logs
```
flutter doctor -v
[√] Flutter (Channel dev, v0.5.2, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
    • Flutter version 0.5.2 at M:\flutter
    • Framework revision 0a26ac0970 (5 days ago), 2018-06-06 15:28:20 -0700
    • Engine revision a83b37d35a
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.24.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.13.2

[√] Connected devices (1 available)
    • SM T555 • 7779e875 • android-arm • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by zoechi** [comment] 2018-06-12 06:06
@Hixie

**Comment by MichaelSowah** [comment] 2018-06-15 15:38
@zoechi @Hixie any updates on this please...a big blocker for launch...any help will be appreciated

**Comment by Hixie** [comment] 2018-06-18 07:22
@MichaelSowah This is not an area that we're currently looking at; however, if you can figure out what the cause is and submit a PR I will definitely make sure it gets reviewed and so on.

**Comment by maral** [comment] 2018-07-13 09:50
I encountered the same problem in emulator, however the problem disappeared on my Android phone. Maybe a bug of the emulator?

**Comment by AlexBacich** [comment] 2018-08-04 11:14
Similar problem here. 
In my case back camera isn't saving photos right. This isn't happening on all phones however. Wileyfox Swift shoots just fine, but Sony F5321 saves photos rotated. 

As a workaround I can rotate image once saved, but it's taking over 5 seconds to do for Image plugin. Quite a long time to do.

**Comment by eseidelGoogle** [comment] 2018-11-25 19:55
This sounds like something is losing the EXIF data.  Likely just a duplicate of: https://github.com/flutter/flutter/issues/24574

Photos from cellphones are complicated.  These days the files are always written in the same orientation, but then the orientation information is recorded in metadata for the file (EXIF) and then all viewers need to respect that.  It appears in https://github.com/flutter/flutter/issues/24574 that the Flutter camera plugin is not correctly recording the EXIF data when encoding the file.  Hence problems like this one (at least that's my guess).

**Comment by eseidelGoogle** [comment] 2018-11-26 17:17
I've written notes about how to add exif on iOS/Android to: https://github.com/flutter/flutter/issues/10533#issuecomment-441719073 . I suspect all of these exif bugs are the same root cause and easy to fix.

**Comment by zoechi** [comment] 2018-11-26 17:35
Related https://github.com/flutter/plugins/pull/866

**Comment by mklim** [comment] 2018-11-28 00:57
Still investigating this, but from what I've seen so far this doesn't seem like it's just an EXIF problem. I've been able to reproduce photos always locked to one orientation with an Android device and the camera plugin example app. Updating the plugin to write all the EXIF values from `onCaptureCompleted` instead doesn't look like it's solving the orientation issue or adding new EXIF tags from what it's already saving now. My current thinking is that there's potentially something wrong with how the plugin is [calculating and setting the orientation](https://github.com/flutter/plugins/blob/master/packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java#L570-L574). I'm always seeing `displayOrientation` and `displayRotation` at 0 and `sensorOrientation` at 90, no matter how the device is rotated.

**Comment by mklim** [comment] 2018-11-28 18:31
The root issue I've been seeing is that the plugin code is setting the photo orientation based on the screen orientation, not the actual physical device orientation. That can differ, an easy way to see the problem is to lock the device to portrait mode and then try to take landscape pictures using the example camera plugin app. The above PR should fix the problem.

**Closed** 2018-11-28 23:46 UTC
Labels: p: first party, plugin, ▣ platform-android

**Comment by idealopamp** [comment] 2018-11-29 01:52
Hi @mklim , I have a question that is kind of tangential to this issue -- how can I build my app with your fixed version of the camera plugin? Even though I'm on the flutter master branch, it is still giving me the 0.2.4 version of the camera plugin, I imagine because this 0.2.6 version is not on pub.dartlang.org .

**Comment by mklim** [comment] 2018-11-29 18:05
@idealopamp yeah, the problem you were seeing is most likely that 0.2.6 hadn't been uploaded yet. Sorry about that. I've just uploaded 0.2.6 to pub.dartlang.org, so it should be available now.

**Comment by matte5031** [comment] 2018-12-29 03:12
So, does this work for you guys now?  I still get this error on android simulator, all images rotate 90 in preview image even if phone is portrait

**Comment by tanamduit** [comment] 2019-02-14 10:43
so do i in andro device

**Comment by Monoss** [comment] 2019-03-05 04:13
> So, does this work for you guys now? I still get this error on android simulator, all images rotate 90 in preview image even if phone is portrait

Still seing this problem. One of the Android device I tried (Mi MIX 2S) have all its captured images rotated 90 degree reverse clockwise, no matter the device orientation.

Tested using using the latest `0.4.0+3` version with the app orientation locked to portrait mode.

**Comment by febg11** [comment] 2019-05-26 13:34
Happening to me on ios only.
