### ISSUE TITLE
Selection toolbar triangle doesn't highlight

### ISSUE THREAD

**Issue by zywj** [flutter/flutter#22469] opened 2018-09-29 14:57 UTC
![image](https://user-images.githubusercontent.com/5554211/46247137-85b1c480-c439-11e8-8bef-be94c2fe20f1.png)

As shown, the triangle doesn't  have the selected effect.  

Output of the flutter doctor:
```
[✓] Flutter (Channel dev, v0.9.5, on Mac OS X 10.13.6 17G65, locale en-HK)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✗] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.27.2)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment] 2019-01-04 11:08
Somewhat related #24784, #11274, #22576

**Comment by pedromassangocode** [comment] 2020-07-24 10:17
Hi @zywj 
Can't reproduce this in the current `dev` and `stable` channel.

![Kapture 2020-07-24 at 11 13 41](https://user-images.githubusercontent.com/67424416/88381791-ffe5d280-cd9e-11ea-8bf7-d4d723e3f9a0.gif)

Closing as fixed. Please comment if you disagree.

**Closed by pedromassangocode** 2020-07-24 10:17 UTC
Labels: P4, a: fidelity, a: text input, framework, platform-ios
