### ISSUE TITLE
codelab @override

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10983] opened 2017-06-26 23:41 UTC
In the Flutter codelab:
https://codelabs.developers.google.com/codelabs/flutter/#6

The third code listing, which starts with the comment:
// Modify the ChatMessage class definition as follows.

The "@override" on the second line was added, but it is not marked as "//new"

(might be nice to explain why this directive was added).

**Comment by LarkAscending** [comment] 2017-06-28 00:37
Duplicate of #10739

**Closed** 2017-06-28 18:22 UTC
Labels: dev: docs - codelab, easy fix
