### ISSUE TITLE
Downloaded executables cannot execute on host - macOS 10.15 Catalina Beta

### ISSUE THREAD

**Issue by tomadimitrie** [flutter/flutter#34000] opened 2019-06-06 19:51 UTC
## Steps to Reproduce

1. Run flutter doctor

## Logs

```
[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.15 19A471t, locale en-GB)
    • Flutter version 1.5.4-hotfix.2 at /Users/toma/Developer/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/toma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/toma/Library/Android/sdk
    • Java binary at: /Users/toma/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M336w
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/toma/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android
      Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Users/toma/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 36.0.7
    • Dart plugin version 191.7221

[✓] Connected device (1 available)
    • Toma’s iPhone • 6f7dcfc53234c0662a44c3ca27222998f53ba02e • ios • iOS 13.0

```

## What I have tried

-> running `flutter upgrade`
-> updated Xcode 11
-> updated CocoaPods

**Comment by timsneath** [comment] 2019-06-06 20:14
Flutter is not yet supported on macOS 10.15, although we're obviously looking at it. This is a duplicate of #22598, which relates to the removal of 32-bit support from Catalina.

**Closed by timsneath** 2019-06-06 20:14 UTC
Labels: tool, ⌘‬ platform-mac

**Comment by hahazheng** [comment] 2019-07-23 05:49
我也遇到相同的问题 目前有解决方案嘛 ~~~

**Comment by Mahdi-Hemmatnia** [comment] 2019-09-03 17:04
Easy fix:
Open terminal on mac and run following commands:

1- flutter channel master
2- flutter doctor

enjoy

**Comment by AleksandarSavic95** [comment] 2020-02-03 16:09
What helped me was to download the 1.9.1 release from the ["releases" page (link)](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos).
[Here (link) is the download link for v1.9.1+hotfix.6, stable channel](https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.9.1+hotfix.6-stable.zip).

**Don't forget** to point Your flutter command to the location of this new dowloaded flutter version!
I just extracted it to `flutter` dir, but renamed the old `flutter` directory to `flutter_old` (just in case I need it, but I won't).

Good luck! :)
