### ISSUE TITLE
TextInputAction button is absent on the keyboard on IOS

### ISSUE THREAD

**Issue by Goolpe** [flutter/flutter#30361] opened 2019-04-02 08:03 UTC
I have form with TextFormFields, if I add keyboard type phone or number, text input actions button is away on IOS
```
TextFormField(
  textInputAction: TextInputAction.next,
  keyboardType: TextInputType.phone,
)
```

```
[✓] Flutter (Channel dev, v1.4.7, on Mac OS X 10.14.3 18D109, locale ru-RU)
    • Flutter version 1.4.7 at /Users/ads/Library/flutter
    • Framework revision 1bfa2f2311 (4 days ago), 2019-03-29 10:05:18 -0700
    • Engine revision c4d14a0071
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ads/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ads/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • Redmi Note 3 • 89ab2252                                 • android-arm64 • Android 6.0.1 (API 23)
    • iPhone ads   • 8281cc08213a56923023315c42893a5f4671ab6c • ios           • iOS 12.1.2
```

**Comment by TahaTesser** [comment] 2020-02-25 09:18
Hi @Goolpe 
Are you still experiencing this issue?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-03-13 12:55
Duplicate of https://github.com/flutter/flutter/issues/30361

**Closed by VladyslavBondarenko** 2020-03-13 12:55 UTC
Labels: a: text input, framework, waiting for customer response, ⌺‬ platform-ios
