### ISSUE TITLE
 auto import '../../../../../ not import 'package:...'

### ISSUE THREAD

**Issue by xty19** [flutter/flutter#47333] opened 2019-12-18 12:38 UTC
When i use android studio to write flutter applicaitons,I write some key words like 'MaterialApp','Text'.But what it auto import is like this:
`import '../../../../../flutter/packages/flutter/lib/material.dart';`
but it used to be like this before,`import 'package:flutter/material.dart';`

But before I upgrade flutter , it auto import like this `import 'package:flutter/material.dart';`
so I do not know what happen when i upgrade fultter.
Would you please handle this problem,thanks very much!

**pic below**
![1](https://user-images.githubusercontent.com/9359167/71087034-3094d680-21d6-11ea-897d-95ca32d6f5df.png)
![2](https://user-images.githubusercontent.com/9359167/71087036-312d6d00-21d6-11ea-85b6-9f5dd50a7534.png)

**Comment by Ahmadre** [comment] 2019-12-20 13:12
Same here on VSCode! Problem exists since the latest Flutter version on Master branch 💯

**Comment by deep-gaurav** [comment] 2019-12-20 15:13
Looks like a duplicate of #47065

**Comment by Ahmadre** [comment] 2019-12-30 12:59
It's fixed guys. could someone close this issue?

**Comment by DanTup** [comment] 2020-01-04 15:03
Yep, this was fixed by https://github.com/dart-lang/sdk/issues/39848 and has been rolled into the master branch. Thanks!

**Closed by DanTup** 2020-01-04 15:03 UTC
Labels: customer: crowd, severe: regression, t: devtools, tool
