### ISSUE TITLE
[tool_crash] ClientException

### ISSUE THREAD

**Issue by futurelucas4502** [flutter/flutter#80825] opened 2021-04-20 23:05 UTC
Hi there i recently updated to flutter 2.0.5 and ever since i have had problem after problem this is one of them provided by the crash tool i have had different ones to this but i didnt keep the logs

I simply made a change to my code and ran a hot restart and it crashed

## Command
```
flutter run --machine --target lib/main.dart -d 55f03ef4b1f7de570c32c7baaa52f919008582a3 --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/
```

## Logs
ClientException
```
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:50:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:45:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:272:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:441:16)
#5      _rootRunBinary (dart:async/zone.dart:1378:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#12     _addErrorWithReplacement (dart:async/stream_pipe.dart:176:8)
#13     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:277:11)
#14     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#15     _rootRunBinary (dart:async/zone.dart:1378:47)
#16     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#17     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#18     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#19     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#20     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#21     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#22     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#23     _StreamController.addError (dart:async/stream_controller.dart:569:5)
#24     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1163:22)
```
```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 2.0.5 at /Applications/flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lucaswilson/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Lucas's iPhone (mobile) • 55f03ef4b1f7de570c32c7baaa52f919008582a3 • ios            • iOS 9.3.6
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 90.0.4430.85
    ! Error: Lucas's iPhone is busy: Copying cache files from device. Xcode will continue when Lucas's iPhone is finished. (code -10)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
device_info-2.0.0
flutter_keyboard_visibility-5.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_secure_storage-4.1.0
native_pdf_renderer-3.0.0
path_provider-2.0.1
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.0
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
video_player-2.1.1
video_player_web-2.0.0

**Comment by darshankawar** [comment] 2021-04-21 08:05
@futurelucas4502 
This issue was fixed and merged into master, https://github.com/flutter/flutter/issues/73356.
But not sure if it has made into stable.
Can you switch to latest master and try same command again to see if issue persists or not.

Also, closing this as duplicate of https://github.com/flutter/flutter/issues/80615.

**Closed by darshankawar** 2021-04-21 08:05 UTC
Labels: in triage
