### ISSUE TITLE
User-created ancestor of the error-causing widget was:

### ISSUE THREAD

**Issue by minhhoang1007** [flutter/flutter#41887] opened 2019-10-03 03:05 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment] 2019-10-03 09:47
Hello @minhhoang1007 !

Thank you for posting.
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-10-03 09:47 UTC

**Comment by nisimjoseph** [comment] 2019-10-06 18:39
I got the same message and the solution was the Router didn't find any route and return to MaterialApp empty Widget.
