### ISSUE TITLE
Integration_test has documentation for a parameter named onScreenshot but does not have the actual parameter

### ISSUE THREAD

**Issue by rajeshpatil95** [flutter/flutter#94881] opened 2021-12-08 19:15 UTC
flutter/packages/integration_test/lib/integration_test_driver.dart
`/// `onScreenshot` can be used to process the screenshots taken during the test.
/// An example could be that this callback compares the byte array against a baseline image,
/// and it returns `true` if both images are equal.
///
/// As a result, returning `false` from `onScreenshot` will make the test fail.`

But in integration_test_driver_extended.dart have **onScreenshot(**) callback but does not have **responseDataCallback()** parameter: though in both cases it return null after all test case execution.
**How to capture screenshot using integration_test_driver.dart package if it doesn't not contain onScreenshot() callback?**

**Flutter doctor:**
`C:\Users\Ext07696\FlutterProjects\signify-bics-frontend>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.2)
[√] Connected device (2 available)

• No issues found!`

**Comment by maheshmnj** [comment] 2021-12-09 08:39
Hi @rajeshpatil95, Thanks for filing the issue, You should be able to take a screenshot as below.


```dart
import 'package:integration_test/integration_test.dart';
import 'package:integration_test/integration_test_driver_extended.dart';
import 'package:flutter_driver/flutter_driver.dart' as d;


      final d.FlutterDriver driver = await d.FlutterDriver.connect();
      await integrationDriver(
        driver: driver,
        onScreenshot: (String screenshotName, List<int> screenshotBytes) async {
          print('screenshot taken');
          return true;
        },
      );
```
Closing this issue as a duplicate of  https://github.com/flutter/flutter/issues/91813

**Closed by maheshmnj** 2021-12-09 08:39 UTC
Labels: in triage

**Comment by rajeshpatil95** [comment] 2021-12-09 08:55
Okay @maheshmnj in your above code how do we listen to responseDatacCallback()...which is something is not implemented in 
**package:integration_test/integration_test_driver_extended.dart** ...how do we generate json report in this case?
