### ISSUE TITLE
[iOS] Unicode `\u202b` crashes app

### ISSUE THREAD

**Issue by SvenFang** [flutter/flutter#110454] opened 2022-08-29 05:14 UTC
## Steps to Reproduce

Flutter 3.0.5 ios Text Widget contact   \u202b will crash

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              ("آنـ๋͜‏ـجـ๋͜‏ـى🪄❤‫"),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Flutter
skia::textlayout::TextLine::measureTextInsideOneRun(skia::textlayout::SkRange<unsigned long>, skia::textlayout::Run const*, float, float, bool, bool) const (TextLine.cpp:0)
1
Flutter
skia::textlayout::TextLine::measureTextInsideOneRun(skia::textlayout::SkRange<unsigned long>, skia::textlayout::Run const*, float, float, bool, bool) const (tuple:265)
2
Flutter
skia::textlayout::TextLine::iterateThroughSingleRunByStyles(skia::textlayout::Run const*, float, skia::textlayout::SkRange<unsigned long>, skia::textlayout::StyleType, std::__1::function<void (skia::textlayout::SkRange<unsigned long>, skia::textlayout::TextStyle const&, skia::textlayout::TextLine::ClipContext const&)> const&) const (SkRect.h:779)
3
Flutter
_ZNSt3__110__function6__funcIZN4skia10textlayout8TextLine28ensureTextBlobCachePopulatedEvE3$_3NS_9allocatorIS5_EEFbPKNS3_3RunEfNS3_7SkRangeImEEPfEEclEOSA_OfOSC_OSD_ (TextLine.cpp:234)
4
Flutter
std::__1::function<bool (skia::textlayout::Run const*, float, skia::textlayout::SkRange<unsigned long>, float*)>::operator()(skia::textlayout::Run const*, float, skia::textlayout::SkRange<unsigned long>, float*) const (functional:2555)
5
Flutter
skia::textlayout::TextLine::iterateThroughVisualRuns(bool, std::__1::function<bool (skia::textlayout::Run const*, float, skia::textlayout::SkRange<unsigned long>, float*)> const&) const (TextLine.cpp:0)
6
Flutter
skia::textlayout::TextLine::ensureTextBlobCachePopulated() (functional:1838)
7
Flutter
skia::textlayout::ParagraphImpl::paint(SkCanvas*, float, float) (vector:1520)
8
Flutter
Paragraph_paint (paragraph.cc:40)
```

```
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 3.0.5, on macOS 12.3.1 21E258 darwin-arm, locale zh-Hans-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by SvenFang** [comment] 2022-08-29 05:16
\u200f also crash

**Comment by SvenFang** [comment] 2022-08-30 10:35
Hi @danagbemava-nc , thanks for ur answer. please use this code, if first time hadn't crashed, click 'Refresh' many time will crash.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _text = 'آنـ๋͜‏ـجـ๋͜‏ـى🪄❤‫';

  void _incrementCounter() {
    if (mounted) {
      setState(() {
        _text = 'آنـ๋͜‏ـجـ๋͜‏ـى🪄❤‫';
      });
    }
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text("Test"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(_text),
              Text(_text),
              Text(_text),
            ],
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Refresh',
          child: const Icon(Icons.add),
        ));
  }
}

```

Log
```
Debug service listening on ws://127.0.0.1:53965/it2OYzBf8Fo=/ws
Syncing files to device AlomateiPhone...
* thread #8, name = 'io.flutter.1.ui', stop reason = EXC_BAD_ACCESS (code=1, address=0x14f54bbc8)
    frame #0: 0x0000000107cb10e0 Flutter`skia::textlayout::TextLine::measureTextInsideOneRun(skia::textlayout::SkRange<unsigned long>, skia::textlayout::Run const*, float, float, bool, bool) const + 980
Flutter`skia::textlayout::TextLine::measureTextInsideOneRun:
->  0x107cb10e0 <+980>: ldr    s11, [x8, x9]
    0x107cb10e4 <+984>: ldp    s0, s1, [x21, #0xa0]
    0x107cb10e8 <+988>: ldrb   w8, [x21, #0xdb]
    0x107cb10ec <+992>: cmp    w8, #0x0
Target 0: (Runner) stopped.
Lost connection to device.
```

**Comment by danagbemava-nc** [comment] 2022-08-30 13:28
Hi @SvenFang, I ran the new code sample (added logs to show when I clicked the button) and I still can't reproduce the issue. See the logs below. 

What iOS device/version are you running on?

<details>
<summary>logs</summary>

```
Multiple devices found:
Nexus (mobile)             • 00008020-001875E83A38002E            • ios            • iOS 15.6.1 19G82
iPhone 13 Pro Max (mobile) • FD5949EA-E739-4960-9E9D-16F3DE69816E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
Chrome (web)               • chrome                               • web-javascript • Google Chrome 104.0.5112.101
[1]: Nexus (00008020-001875E83A38002E)
[2]: iPhone 13 Pro Max (FD5949EA-E739-4960-9E9D-16F3DE69816E)
[3]: macOS (macos)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on Nexus in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,580ms
Xcode build done.                                           15.4s
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Installing and launching...                                        20.3s
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Syncing files to device Nexus...                                   164ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Nexus is available at: http://127.0.0.1:55123/VfNVraiswok=/
The Flutter DevTools debugger and profiler on Nexus is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:55123/VfNVraiswok=/
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked
flutter: clicked

Application finished.
```
</details>

**Comment by SvenFang** [comment] 2022-08-31 02:15
Hi, @danagbemava-nc ,my device is iPhone Xs Max, iOS 15.6.1, Xcode 13.4.

**Comment by danagbemava-nc** [comment] 2022-08-31 06:53
Hi @SvenFang, can you provide the full output of `flutter run -v` that captures the crash? If the output is too large to embed in github, kindly put it into a .txt file and attach it here. 

Thank you

**Comment by SvenFang** [comment] 2022-09-01 05:52
Hi @danagbemava-nc , my log in 
https://github.com/SvenFang/mytest/blob/master/crash_log.txt

**Comment by danagbemava-nc** [comment] 2022-09-01 08:03
Thanks for the logs, one more thing, @SvenFang, can you confirm if you can still reproduce this on either the master channel or the latest version of stable (3.3.0)?

Thank you

**Comment by SvenFang** [comment] 2022-09-01 10:30
Hi @danagbemava-nc , it also crash in 3.3.0, but it can run in 2.10.5
https://github.com/SvenFang/mytest/blob/master/3.3.0_crash.txt

**Comment by danagbemava-nc** [comment] 2022-09-02 07:06
I can't seem to reproduce this, so I will label this for further investigation from the team. 

Verbose logs can be found [here](https://github.com/SvenFang/mytest/blob/master/3.3.0_crash.txt?rgh-link-date=2022-09-01T10%3A30%3A01Z) and [here](https://github.com/SvenFang/mytest/blob/master/crash_log.txt?rgh-link-date=2022-09-01T05%3A52%3A41Z)

**Comment by chinmaygarde** [comment] 2022-09-06 18:59
Closing this as there is no reproducible test case.

**Closed by chinmaygarde** 2022-09-06 18:59 UTC
Labels: severe: crash, platform-ios, engine, a: typography, will need additional triage, severe: fatal crash
