### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by imshailesh593** [flutter/flutter#134517] opened 2023-09-12 09:46 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:337:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
```
```
[✓] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.22621.2215], locale en-IN)
    • Flutter version 3.13.0 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (4 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Sk593\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at C:\Users\Sk593\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2215]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.187
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.76

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ad6cd72c040113b47ee9055e722606a490ef0da
### Plugins
connectivity_plus-3.0.3
flutter_downloader-1.10.2
flutter_plugin_android_lifecycle-2.0.9
fluttertoast-8.2.1
image_picker-0.8.7
image_picker_android-0.8.6+1
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+1
package_info_plus-4.1.0
path_provider-2.0.13
path_provider_android-2.0.24
path_provider_foundation-2.1.3
path_provider_linux-2.1.10
path_provider_windows-2.1.7
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
share-2.0.4
shared_preferences-2.0.18
shared_preferences_android-2.0.17
shared_preferences_foundation-2.1.5
shared_preferences_linux-2.1.5
shared_preferences_web-2.0.6
shared_preferences_windows-2.1.5
sqflite-2.2.6
url_launcher-6.1.10
url_launcher_android-6.0.25
url_launcher_ios-6.1.2
url_launcher_linux-3.0.4
url_launcher_macos-3.0.4
url_launcher_web-2.0.16
url_launcher_windows-3.0.5
video_player-2.7.0
video_player_android-2.4.2
video_player_avfoundation-2.4.1
video_player_web-2.0.15
wakelock_plus-1.1.1
webview_flutter-4.0.7
webview_flutter_android-3.4.3
webview_flutter_wkwebview-3.2.2

**Comment by dam-ease** [comment] 2023-09-12 09:54
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224.

Kindly subscribe to the original issue for updates.

Thank you

**Closed by dam-ease** 2023-09-12 09:54 UTC
Labels: in triage
