### ISSUE TITLE
[Linux desktop] Error connecting to the service protocol

### ISSUE THREAD

**Issue by T99Rots** [flutter/flutter#72659] opened 2020-12-19 22:08 UTC
## Steps to Reproduce

1. flutter channel dev
2. flutter upgrade
3. flutter config --enable-linux-desktop
4. flutter create example
5. cd example
6. flutter run

I'm running on ubuntu 20.10 with kernel 5.9.12-050912-generic
I'm trying to run the app for linux desktop

This issue also occurs when running `>Debug: Start Debugging` in vscode

This setup has worked before and was running fine for about 2 weeks, i started building the app on 1.25.0-4.0.pre, i'm working on 2 different projects at the same time, one running on android on channel stable and one running on linux desktop on channel dev so i quite regularly switched between channels, it broke after i switched from stable to dev and ran flutter upgrade, downgrading doesn't fix the issue

## Logs

The output from `flutter run --verbose`

```
[  +38 ms] executing: [/home/tim/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +18 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 63062a64432cce03315d6b5196fda7912866eb37
[        ] executing: [/home/tim/snap/flutter/common/flutter/] git tag --points-at 63062a64432cce03315d6b5196fda7912866eb37
[   +5 ms] Exit code 0 from: git tag --points-at 63062a64432cce03315d6b5196fda7912866eb37
[        ] 1.26.0-1.0.pre
[  +21 ms] executing: [/home/tim/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/tim/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +21 ms] executing: [/home/tim/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +24 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] executing: /home/tim/Android/Sdk/platform-tools/adb devices -l
[  +20 ms] List of devices attached
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] Skipping pub get: version match.
[  +46 ms] Found plugin integration_test at /home/tim/snap/flutter/common/flutter/packages/integration_test/
[  +71 ms] Found plugin integration_test at /home/tim/snap/flutter/common/flutter/packages/integration_test/
[   +2 ms] Generating /home/tim/Projects/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +47 ms] Initializing file store
[   +4 ms] Skipping target: gen_localizations
[   +1 ms] complete
[   +2 ms] Launching lib/main.dart on Linux in debug mode...
[   +2 ms] /home/tim/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/tim/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/tim/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
--output-dill /tmp/flutter_tools.PQLEJP/flutter_tool.BMXAVA/app.dill --packages /home/tim/Projects/example/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[   +8 ms] Building Linux application...
[   +9 ms] <- compile package:example/main.dart
[   +3 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/tim/Projects/example/linux
[ +540 ms] -- The CXX compiler identification is Clang 6.0.0
[   +7 ms] -- Check for working CXX compiler: /snap/flutter/40/usr/bin/clang++
[  +57 ms] -- Check for working CXX compiler: /snap/flutter/40/usr/bin/clang++ -- works
[   +2 ms] -- Detecting CXX compiler ABI info
[  +65 ms] -- Detecting CXX compiler ABI info - done
[   +2 ms] -- Detecting CXX compile features
[ +275 ms] -- Detecting CXX compile features - done
[   +4 ms] -- Found PkgConfig: /snap/flutter/40/usr/bin/pkg-config (found version "0.29.1") 
[   +1 ms] -- Checking for module 'gtk+-3.0'
[  +16 ms] --   Found gtk+-3.0, version 3.22.30
[  +59 ms] -- Checking for module 'glib-2.0'
[  +10 ms] --   Found glib-2.0, version 2.56.4
[  +35 ms] -- Checking for module 'gio-2.0'
[   +8 ms] --   Found gio-2.0, version 2.56.4
[  +36 ms] -- Checking for module 'blkid'
[  +13 ms] --   Found blkid, version 2.31.1
[  +30 ms] -- Checking for module 'liblzma'
[  +13 ms] --   Found liblzma, version 5.2.2
[  +43 ms] -- Configuring done
[  +15 ms] -- Generating done
[        ] -- Build files have been written to: /home/tim/Projects/example/build/linux/debug
[   +3 ms] executing: ninja -C build/linux/debug install
[   +7 ms] ninja: Entering directory `build/linux/debug'
[+6557 ms] [1/6] Generating /home/tim/Projects/example/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/tim/Projects/example/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +3 ms] [  +39 ms] executing: [/home/tim/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +18 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 63062a64432cce03315d6b5196fda7912866eb37
[        ] [        ] executing: [/home/tim/snap/flutter/common/flutter/] git tag --points-at 63062a64432cce03315d6b5196fda7912866eb37
[        ] [   +9 ms] Exit code 0 from: git tag --points-at 63062a64432cce03315d6b5196fda7912866eb37
[        ] [        ] 1.26.0-1.0.pre
[        ] [  +21 ms] executing: [/home/tim/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/dev
[        ] [        ] executing: [/home/tim/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +20 ms] executing: [/home/tim/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [  +23 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +25 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +49 ms] Initializing file store
[        ] [   +9 ms] Skipping target: gen_localizations
[        ] [   +3 ms] unpack_linux: Starting due to {}
[        ] [  +51 ms] kernel_snapshot: Starting due to {}
[        ] [   +1 ms] unpack_linux: Complete
[   +1 ms] [ +939 ms] /home/tim/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/tim/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/tim/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --packages /home/tim/Projects/example/.dart_tool/package_config.json --output-dill
/home/tim/Projects/example/.dart_tool/flutter_build/e0927e2321f0cd00b4c4a60e7c03338c/app.dill --depfile
/home/tim/Projects/example/.dart_tool/flutter_build/e0927e2321f0cd00b4c4a60e7c03338c/kernel_snapshot.d package:example/main.dart
[   +1 ms] [+4067 ms] kernel_snapshot: Complete
[        ] [ +244 ms] debug_bundle_linux_assets: Starting due to {}
[        ] [ +127 ms] debug_bundle_linux_assets: Complete
[        ] [ +268 ms] Persisting file store
[        ] [   +3 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +5 ms] "flutter assemble" took 5,807ms.
[        ] [ +139 ms] ensureAnalyticsSent: 137ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +240 ms] [2/6] Building CXX object CMakeFiles/example.dir/main.cc.o
[  +17 ms] [3/6] Building CXX object CMakeFiles/example.dir/flutter/generated_plugin_registrant.cc.o
[   +9 ms] [4/6] Building CXX object CMakeFiles/example.dir/my_application.cc.o
[  +54 ms] [5/6] Linking CXX executable intermediates_do_not_run/example
[        ] [5/6] Install the project...
[   +9 ms] -- Install configuration: "Debug"
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/example
[        ] -- Set runtime path of "/home/tim/Projects/example/build/linux/debug/bundle/example" to "$ORIGIN/lib"
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/icudtl.dat
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[  +73 ms] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +15 ms] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/tim/Projects/example/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[  +11 ms] Building Linux application... (completed in 8.3s)
[ +315 ms] Observatory URL on device: http://127.0.0.1:35549/WiEFI6br_zc=/
[   +4 ms] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:35549/WiEFI6br_zc=/
[   +2 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:35549/WiEFI6br_zc=/.
[ +191 ms] Warning: Failed to start DDS: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:35549/WiEFI6br_zc=/ws
[        ] Fail to connect to service protocol: http://127.0.0.1:35549/WiEFI6br_zc=/: DartDevelopmentServiceException: WebSocketChannelException: WebSocketChannelException: HttpException:
Connection closed before full header was received, uri = http://127.0.0.1:35549/WiEFI6br_zc=/ws
[   +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:35549/WiEFI6br_zc=/
[   +3 ms] "flutter run" took 9,119ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[  +38 ms] ensureAnalyticsSent: 37ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 2
```

The output from `flutter doctor -v`
```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-1.0.pre at /home/tim/snap/flutter/common/flutter
    • Framework revision 63062a6443 (6 days ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/tim/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.

```

**Comment by cachapa** [comment] 2020-12-20 08:57
I'm having the same issue since updating to the latest dev channel a couple of days ago.
Unfortunately, using the `downgrade` command doesn't seem to be working for me.

**Comment by TahaTesser** [comment] 2020-12-21 11:44
Hi @T99Rots 
Looks like you're running a snap version of Flutter, please check out https://github.com/flutter/flutter/issues/72456
The problem might snap package, it is confirmed with git clone method https://github.com/flutter/flutter/issues/72456#issuecomment-748093601
Thank you

**Comment by T99Rots** [comment] 2020-12-21 17:22
Hi @TahaTesser  
I installed flutter through the git clone method and it works fine, but as you didn't have any issues with the snap package i expect the problem might have been in the upgrade process or the frequent switching between channels, i'll post a update here if it happens again

**Comment by cachapa** [comment] 2020-12-21 18:25
Same here. Installing manually works for me.
I tried `snap remove flutter --purge` and reinstalling but it didn't work for me.

I even installed all the Ubuntu dependencies (which shouldn't be necessary with the snap package) but nothing. I did notice there was a snap flutter update a few days ago. I suspect this is what broke the installation.

**Comment by TahaTesser** [comment] 2020-12-22 07:23
@T99Rots 
Glad you got it working with git clone. Nevertheless, I reported these new issues to Snap repo https://github.com/canonical/flutter-snap/issues/21
Closing as duplicate of https://github.com/flutter/flutter/issues/72456

**Closed by TahaTesser** 2020-12-22 07:23 UTC
Labels: in triage

**Comment by MarcusTomlinson** [comment] 2020-12-22 08:38
Hi, could I please ask you to try a full re-install of the snap and see if it fixes things:

```
snap remove --purge flutter
rm -rf ~/snap/flutter
snap install flutter --classic
flutter channel dev
flutter upgrade
flutter config --enable-linux-desktop
```
