### ISSUE TITLE
Screenshot support in integration_test without the need of a custom driver

### ISSUE THREAD

**Issue by robertof-wolt** [flutter/flutter#108963] opened 2022-08-04 11:17 UTC
## Use case

Currently to be able to take screenshots from an integration test it's necessary to use a custom driver, for example like this one:

```dart
import 'dart:io';
import 'package:integration_test/integration_test_driver_extended.dart';

Future<void> main() async {
  try {
    await integrationDriver(
      onScreenshot: (screenshotName, screenshotBytes) async {
        final File image = await File('screenshots/$screenshotName.png')
            .create(recursive: true);
        image.writeAsBytesSync(screenshotBytes);
        return true;
      },
    );
  } catch (e) {
    print('Error occured taking screenshot: $e');
  }
}
```

This also force the test to be started using `flutter drive` instead of `flutter test`. The approach works fine locally but when running tests in Firebase Test Lab we don't have control on the environment and cannot specify to use a custom driver so screenshots are not taken.

## Proposal

Support screenshot natively in integration_test. Maybe the directory where to store them could be configurable via a parameter also.

**Comment by danagbemava-nc** [comment] 2022-08-04 12:37
Hi @robertof-wolt, I believe this is a duplicate of https://github.com/flutter/flutter/issues/51890. 

Kindly follow up in the linked issue for updates. 

Closing this as a duplicate of the linked issue. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-08-04 12:37 UTC
Labels: in triage

**Comment by robertof-wolt** [comment] 2022-08-04 13:06
Hi @danagbemava-nc, these are slightly different things but I agree that they could be handled together. So I added a comment there.
