### ISSUE TITLE
[image_picker] IOS Limited Photos function not working

### ISSUE THREAD

**Issue by huurray** [flutter/flutter#160632] opened 2024-12-20 01:04 UTC
### Steps to reproduce

Hello. In the iOS environment, I first set the permission to "limited access" and selected only a few photos, but when I accessed it through pickImage and pickMultiImage, all the photos were displayed.

### Expected results

Only a few selected photos should be displayed in the image picker

### Actual results

All photos in the gallery are displayed.

### Code sample

<details open><summary>Code sample</summary>

```dart
var selectedMultiImages = await imagePicker.pickMultiImage(
     maxWidth: 1440,
     maxHeight: 1440,
     imageQuality: 70,
     limit: 3,
);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/531b40bc-6339-4e7f-9826-ac0d7b686f87

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.0.1 24A348 darwin-arm64, locale ko-KR)
    • Flutter version 3.27.1 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (3일 전), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/huurray/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/huurray/Library/Android/sdk
    • Java binary at: /opt/homebrew/Cellar/openjdk@17/17.0.13/libexec/openjdk.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.13+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.96.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • 허준혁 iphone (mobile)             • 00008110-00080CD40AA2401E            • ios            • iOS 18.1.1 22B91
    • iPhone 16 (mobile)              • 5AD57449-7473-48F1-BDB0-33AEBEAD90E6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 131.0.6778.205
    ! Error: Browsing on the local area network for Michelle의 iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-12-20 11:14
Hi @huurray, this shares a root cause as https://github.com/flutter/flutter/issues/90373. 

The "Limit Access" permission is not actually for limiting the number of images you can access, but rather the data that the user gets from the image. See https://github.com/flutter/flutter/issues/90373#issuecomment-1409660120

Closing this in favor of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-12-20 11:14 UTC
Labels: in triage

**Comment by huurray** [comment] 2024-12-20 13:06
@danagbemava-nc Aha, well I actually saw an app where you go through the first photo selection and then on the second screen, you get a list of photos that you select and you can choose from them.

Is this an app that implements the selection screen directly?

**Comment by danagbemava-nc** [comment] 2024-12-23 06:00
Hi @huurray, that would most likely be the case
