### ISSUE TITLE
iOS distributed app is unable to install on device

### ISSUE THREAD

**Issue by hanabon** [flutter/flutter#76172] opened 2021-02-17 01:18 UTC
## Steps to Reproduce

1. Run `flutter build ios`
2. Run `flutter build ipa`
3. Validate and distribute app (to Testflight and Firebase App Distribution with Distribution and Ad Hoc profiles)

Both internal and external testers of Testflight experience this. App icon appears on home screen but is greyed out and always get popup "Unable to install *app name*, please try again later

I'm using Xcode 12.4 and iPhone with iOS 14.4

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en)
    • Flutter version 1.27.0-1.0.pre
    • Framework revision 68c96f100e (8 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
```

</details>

**Comment by darshankawar** [comment] 2021-02-17 08:30
@hanabon 
Are you able to run the app locally in non-prod environment ? There's not enough details around what exactly is causing the error.  Since you mentioned of getting grey screen, it usually occurs in release mode which is equivalent of red screen in debug mode.  For more info on it, check out this open issue, https://github.com/flutter/flutter/issues/53482 and underlying comments to know what exactly could be causing the issue.

**Comment by hanabon** [comment] 2021-02-17 14:22
Yes I'm able to run it locally. Unfortunately there aren't any errors or logs so I cannot provide any additional details. Also, the icon is grey not the screen. The app is never launched because it doesn't seem to be fully downloaded

**Comment by darshankawar** [comment] 2021-02-18 06:14
@hanabon 
Can you also try to install the app after running `flutter build ios` and see if it works ? 
Can you provide `flutter build ios --verbose` logs to see if it shows anything unusual ?
Since there are no logs, exceptions, it'll be tough to investigate as what exactly is causing the issue. Please try to see if you can get any kind of stacktrace or crashlytics to properly address this issue.

**Comment by hanabon** [comment] 2021-02-18 16:56
I tried that but nothing unusual pops out. I've also tried crashlytics and checking the device logs but I guess since it hasn't actually installed I don't get any logs at all

**Comment by darshankawar** [comment] 2021-02-19 06:14
@hanabon 
Can you try `flutter install --verbose` and see if you get any logs with errors ? If not, is it possible for you to provide a sample app and share it as a github repo so that we can try and verify it ?

**Comment by hanabon** [comment] 2021-02-23 01:54
flutter install --verbose didn't give any errors. I created a brand new project and but hasn't seen the issue yet. I'll try to upload a copy of the existing project soon

**Comment by darshankawar** [comment] 2021-02-23 05:53
@hanabon 
Try to compare your new project config with your existing one and see what could be missing or unusual which might be throwing the error.

**Comment by hanabon** [comment] 2021-02-25 15:31
Everything was exactly the same but I think it was the flavors that was causing the issue. I added flavors to the new project and it started to not being able to install.

**Comment by darshankawar** [comment] 2021-02-26 06:06
@hanabon 
Are you able to build the app on iOS and run it locally, but fails to install after distributing it ?
Can you provide a reproducible code sample including flavors ? a repo would be helpful that we can clone and verify.

**Comment by hanabon** [comment] 2021-03-03 02:00
I apologize for the delay, the flavors seem to work on a fresh project. I will try to get a code sample up soon

**Comment by pedromassangocode** [comment] 2021-03-24 12:56
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-24 12:56 UTC
Labels: in triage, waiting for customer response

**Comment by surveshoeb** [comment] 2021-04-23 03:10
I'm also facing the same issue, `flutter run` or `flutter install` works but installing IPA via Diawi or test flight doesn`t.

<img width="385" alt="Screenshot 2021-04-23 at 8 37 10 AM" src="https://user-images.githubusercontent.com/26933124/115812493-1a70d900-a40f-11eb-9c3b-ab2e6ab79db6.png">

I have also added the UDID of the device in apple developer and also tried via the public link of the test flight.

Adding flutter doctor response
```
mac:weone surveshoeb$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```
