### ISSUE TITLE
Can't change TextFormField error message background color

### ISSUE THREAD

**Issue by mehranshoqi** [flutter/flutter#75068] opened 2021-01-30 16:49 UTC
Hello every one

i want to change errer background color but i didn't any solution..
i can't change white background color.

TextFormField code :

<details>
<summary>code sample</summary>

```dart

TextFormField(
                  focusNode: _emailFocusNode,
                  textInputAction: TextInputAction.next,
                  keyboardType: TextInputType.emailAddress,
                  style: TextStyle(
                    color: Colors.white,
                    letterSpacing: .5,
                  ),
                  decoration: InputDecoration(
                    helperText: 'HELPER',
                    helperStyle: TextStyle(
                      backgroundColor: Colors.red,
                      color: Colors.black,
                      decorationColor: Colors.black,
                      debugLabel: 'debug label',
                    ),
                    filled: true,
                    fillColor: Theme.of(context).accentColor,
                    labelText: 'Email Address',
                    labelStyle: TextStyle(
                      color: Colors.white70,
                      fontSize: 15,
                    ),
                    hintText: 'Enter a valid email address',
                    hintStyle: TextStyle(
                      color: Colors.grey.withOpacity(.8),
                      fontSize: 13,
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(10),
                      borderSide: BorderSide(
                        color: Theme.of(context).accentColor,
                      ),
                    ),
                    focusedBorder: OutlineInputBorder(
                      gapPadding: 12,
                      borderRadius: BorderRadius.circular(10),
                      borderSide: BorderSide(
                        color: Theme.of(context).accentColor,
                      ),
                    ),
                  ),
                  cursorColor: Theme.of(context).primaryColor,
                  validator: (value) {
                    if (value.isEmpty) {
                      return 'required *';
                    }
                    if (!RegExp(
                            r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+")
                        .hasMatch(value)) {
                      return 'Enter Correct Email';
                    }
                    return null;
                  },
                  onSaved: (value) {},
                  onFieldSubmitted: (_) => FocusScope.of(context).requestFocus(
                    _passwordFocusNode,
                  ),
                ),
```
</details>

![Screenshot (13)](https://user-images.githubusercontent.com/65711096/106362464-2aa97880-6338-11eb-9ebd-881849135831.png)

**Comment by iapicca** [comment] 2021-01-30 19:51
@mehranshoqi 
please try this possible [solution](https://stackoverflow.com/a/61843489/9836706)
here's the [code sample](https://codepen.io/FirasDev/pen/YzyJaGg)

if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by mehranshoqi** [comment] 2021-01-31 19:36
@iapicca 

No man,
it's about changing background color of TextFormField when Error occured but i want change background color of Error box

i want change white background color on this photo :
![Screenshot (13)](https://user-images.githubusercontent.com/65711096/106395707-e8a43380-6418-11eb-900a-c221210f247d.png)

**Comment by pedromassangocode** [comment] 2021-02-01 08:48
Hi @mehranshoqi 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by iapicca** [comment] 2021-02-06 15:45
@mehranshoqi 
did you run the code I provided [above](https://github.com/flutter/flutter/issues/75068#issuecomment-770271259), 
it seems to work as intended

![Uploading image.png…]()

**Comment by iapicca** [comment] 2021-02-06 15:45
@mehranshoqi 
did you run the code I provided [above](https://github.com/flutter/flutter/issues/75068#issuecomment-770271259), 
it seems to work as intended

![image](https://user-images.githubusercontent.com/45637986/107122875-17039200-68a3-11eb-9674-11caf5df9db6.png)

**Comment by pedromassangocode** [comment] 2021-02-26 13:03
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-26 13:03 UTC
Labels: a: text input, f: material design, framework, in triage, waiting for customer response
