### ISSUE TITLE
CircularProgressIndicator() while WebView is loading

### ISSUE THREAD

**Issue by zurie** [flutter/flutter#28994] opened 2019-03-07 14:37 UTC
Looking for a way to show a CircularProgressIndicator() while flutter_webview plugin is loading.

I have tried 

```
              webViewController.loadUrl(widget['url']).whenComplete(() {
                showLoader = false;
              });
```

Would be nice to have a working example.  Thanks!

**Comment by vleeuwenmenno** [comment] 2019-03-07 14:49
I don't think this is related to the flutter framework repository.
I'd suggest you to check Gitter and ask it there in the Dart/Flutter chatroom

**Comment by deandreamatias** [comment] 2020-05-27 10:35
Related to #36136

**Comment by stuartmorgan** [comment] 2021-02-16 21:17
Duplicate of https://github.com/flutter/flutter/issues/28872. Please add votes there if you are interested in this feature.

**Closed by stuartmorgan** 2021-02-16 21:17 UTC
Labels: d: api docs, d: examples, p: first party, p: webview, passed first triage, plugin, proposal
