### ISSUE TITLE
Since Flutter 1.22 the STACKTRACE is being swallowed when the error is inside of widgets

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#67418] opened 2020-10-06 15:34 UTC
Since Flutter 1.22 the STACKTRACE is being swallowed when the error is inside of widgets.

For example, I am getting this:

```
════════ Exception caught by widgets library ════════ 
Failed assertion: boolean expression must not be null
The relevant error-causing widget was: 
  MyWidget file:///C:/Users/Me/flutter_app/lib/my_widget/my_widget.dart:117:13
══════════════════════════════════════ 
```

It points me to the widget declaration, but the error is inside of it and this information is not being displayed.

**Comment by marcglasberg** [comment] 2020-10-06 17:34
Some of my colleagues are having the same problem, and others are not. 

The ones who are not experiencing the problem are actually getting the error twice, once with the stacktrace and once without it:

```
════════ Exception caught by widgets library ════════ 
The following assertion was thrown building MyWidget(dirty):
Failed assertion: boolean expression must not be null
The relevant error-causing widget was: 
  MyWidget file:///C:/Users/Me/flutter_app/lib/my_widget/my_widget.dart:117:13
When the exception was thrown, this was the stack: 
#0      MyWidget.preambulo (package:xyz/participantes_widget.dart:44:27)
#1      MyWidget._varios (package:xyz/my_widget.dart:71:14)
#2      MyWidget.build (package:xyz/my_widget.dart:56:14)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
...
════════════════════════════════════

════════ Exception caught by widgets library ════════ 
Failed assertion: boolean expression must not be null
The relevant error-causing widget was: 
  MyWidget file:///C:/Users/Me/flutter_app/lib/my_widget/my_widget.dart:117:13
══════════════════════════════════════ 
```

**Comment by bradyt** [comment] 2020-10-06 19:42
@marcglasberg I am seeing similar behavior. Is this only in your IDE run tab? If I try in a terminal, I get the stack trace as expected.

This might be related to intellij. If you can confirm, maybe we should create an associated issue at <https://github.com/flutter/flutter-intellij>. I wouldn't know if either or both projects are involved in bug.

I have checked with the following diff to `flutter create counter`:

```diff
modified   lib/main.dart
@@ -8,6 +8,7 @@ class MyApp extends StatelessWidget {
   // This widget is the root of your application.
   @override
   Widget build(BuildContext context) {
+    throw Exception;
     return MaterialApp(
       title: 'Flutter Demo',
       theme: ThemeData(

```

If I try the run button in intellij, there is no stack trace. But if I try in intellij's terminal tab, or in Terminal.app, the stack trace is shown as expected. I have checked this behavior in vscode, as well as in intellij on Windows. (vscode just does an odd truncation of about five lines of stack trace.)

I will double check for an older flutter version later today.

**Comment by bradyt** [comment] 2020-10-06 21:37
With the following version, intellij shows stack trace again. So bug seems to start between 1.20 and 1.22.

```
% flutter --version
Flutter 1.20.4 • channel unknown • unknown source
Framework • revision fba99f6cf9 (3 weeks ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

**Comment by TahaTesser** [comment] 2020-10-07 08:38
Hi @marcglasberg  
I'm unable to reproduce with a null bool value 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by marcglasberg** [comment] 2020-10-07 14:41
@TahaTesser That's not so easy. As I said, some of my colleagues are having the same problem, and others are not, so it's not just a code problem. And the bool value is just an example. The problem happens for any error thrown by a widget.

@bradyt Ok, I will test if this happens only in the IDE run tab vs the terminal.

**Comment by marcglasberg** [comment] 2020-10-07 18:59
@TahaTesser @bradyt
Yes, I can confirm that it happens  only in the IDE run tab. The terminal gives the complete information.

Also, if you downgrade the Flutter plugin from 50.0 to 49.04 the problem is gone. You can download the plugin in this page: 
https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable/96118

And the direct download link is this:
https://plugins.jetbrains.com/files/9212/96118/flutter-intellij.zip?updateId=96118&pluginId=9212&family=INTELLIJ

**Comment by marcglasberg** [comment] 2020-10-07 19:02
https://github.com/flutter/flutter-intellij/issues/4952

**Comment by TahaTesser** [comment] 2020-10-08 08:14
Hi @marcglasberg 
Correct me if I'm wrong but this sounds like a plugin issue since downgrading plugins solves the issue 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-08 08:14 UTC
Labels: in triage
