### ISSUE TITLE
bug: TextField autofocus & Router

### ISSUE THREAD

**Issue by cpboyd** [flutter/flutter#67745] opened 2020-10-09 17:05 UTC
## Steps to Reproduce

Reproduction based upon [the Nested Router example from the Medium article](https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade):
https://github.com/cpboyd/flutter_autofocus_bug

The `autofocus` worked fine in my application before switching to the new Router.
I'm not sure if they're directly linked, since using a `Router` that only has a single page can still result in a working `autofocus`.

**Expected results:** 
The `TextField(autofocus: true)` should take focus for immediate user input.

**Actual results:** 
The `TextField` appears but doesn't grab focus.

<details>
  <summary>Logs</summary>

```
```

```
route_test % flutter analyze
Analyzing route_test...                                                 

   info • Unused import: 'package:route_test/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

2 issues found. (ran in 2.2s)
```

```
route_test % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.1, on macOS 11.0 20A5384c, locale en-US)
    • Flutter version 1.22.1 at /Users/cpboyd/dev/flutter
    • Framework revision f30b7f4db9 (24 hours ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/cpboyd/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/cpboyd/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/cpboyd/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437/Android
      Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Users/cpboyd/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • FB044C8B-8B92-410B-9EC1-3837B55406AC • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0
      (simulator)

• No issues found!
```

</details>

**Comment by cpboyd** [comment] 2020-10-09 17:31
I've tested with both stable and master branches. Same issue on both.

**Comment by cpboyd** [comment] 2020-10-10 20:32
From various testing, I've found that the inner router's `Navigator` seems to be preventing focus (and possibly suppressing errors)...

Removing both Navigators allows focus, but results in this error:
```
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching notifications for FocusNode:
flutter: No Overlay widget exists above EditableText-[LabeledGlobalKey<EditableTextState>#25ccd](controller:
flutter: TextEditingController#3b929(TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: 0,
flutter: extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing:
flutter: TextRange(start: -1, end: -1))), focusNode: FocusNode#5d68e([PRIMARY FOCUS]), debugLabel:
flutter: (englishLike subhead 2014).merge(blackCupertino subtitle1), inherit: false, color:
flutter: Color(0xdd000000), family: .SF UI Text, size: 16.0, weight: 400, baseline: alphabetic, decoration:
flutter: TextDecoration.none, textAlign: start, autofocus: true, keyboardType: TextInputType(name:
flutter: TextInputType.text, signed: null, decimal: null), dirty, dependencies: [Directionality, MediaQuery,
flutter: _FocusMarker], state: EditableTextState#b73f1(tickers: tracking 2 tickers)).
flutter: Usually the Navigator created by WidgetsApp provides the overlay. Perhaps your app content was
flutter: created above the Navigator with the WidgetsApp builder parameter.
flutter: 'package:flutter/src/widgets/text_selection.dart':
flutter: Failed assertion: line 304 pos 12: 'overlay != null'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new TextSelectionOverlay (package:flutter/src/widgets/text_selection.dart:304:12)
flutter: #3      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:2016:27)
flutter: #4      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:2269:9)
flutter: #5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
flutter: #6      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1027:5)
flutter: #7      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1723:12)
flutter: (elided 12 frames from class _AssertionError and dart:async)
flutter:
flutter: The FocusNode sending notification was:
flutter:   FocusNode#5d68e([PRIMARY FOCUS])
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Keeping the primary `Navigator` will suppress the error.

@chunhtai @johnpryan Are there any additional steps for managing state within the new Router / Navigator 2.0?
I did come across #9282 which referenced an issue with keys and not properly managing state... But I removed the keys from this reproduction and still had the autofocus issue.

**Comment by cpboyd** [comment] 2020-10-10 20:54
I was able to find a work-around by moving the `_isSearching` state and `appBar` to the inner-most child, not on the inner-route wrapper like in the Medium article.

Still, as `AppShell` is a `StatefulWidget`, I think this is a bug where state updates within Navigator 2.0 aren't processing as expected.

At the very least, there should be additional documentation warning users of instances where state is not maintained across the new Router system.

**Comment by darshankawar** [comment] 2020-10-12 07:46
Hi @cpboyd 
Can you please provide more information on when should the textfield get activated and grab focus ?
I cloned your repo and navigated back and forth, maybe I missed something while replicating the issue.
Thanks.

**Comment by cpboyd** [comment] 2020-10-12 16:02
@darshankawar The `TextField` should be activated when clicking the search icon...

Note that the most recent commit (https://github.com/cpboyd/flutter_autofocus_bug/commit/5533594d0fb78b99edcc67e2e18838c5af755508#) moved the `appBar` within the inner `Navigator` which "fixed" the focus scope.

So if you've cloned it, you'll have to checkout this commit rather than the most recent master: https://github.com/cpboyd/flutter_autofocus_bug/commit/2284ec13099312fb82e507443213fc592dda7e37

As my recent investigations, it seems that the `Router` messes with the `FocusScope`... the reason the work-around works is because the `Navigator` widget sets its own `FocusScope`.

**Comment by Crisis2010** [comment] 2020-10-12 23:15
i've noticed that realization with `IndexedStack` and two `Navigator` have some performance issue.

For example:
Create two Pages A and B by tabs, then add to page B widget with, for example, animation. Run app in debug, open performance debuger, go to pages A > B > A, and even if you on the page A without any content that can trigger rerender, debug panel will show render chart like on the screen widget with animation (but it's on page B)
Well that of course because even that we see only page A, page B is still exist in render tree and trigger rerendering evry ticket.
That problem fixed in `CupertinoTabScaffold` by using `Offstage`, `TickerMode` and `FocusMode` for, probably, bug fixes described in #67745 .
Is that only one way to fix that performance issue somebody know?

Seems like need copy of CupertinoTabScaffold but in material (Scaffold)...

**Comment by chunhtai** [comment] 2020-12-08 00:28
This is WAI, the navigator will grab focus for its content automatically, if the textfield is in the outer appbar, it will not be able to auto focus because the inner navigator already claims the focus. You can however create a focus node to pass into the textfield, and calls FocusNode.requestFocus when search is tapped.

@Crisis2010 can you file a separate issue for the performance issue?

**Comment by chunhtai** [comment] 2020-12-08 00:29
closing this issue as WAI

**Comment by zakton5** [comment] 2021-01-12 17:00
@chuntai This is an issue even if the text field is not in the outer app bar. I have a nested router that contains a login page and then a forgot password page on top of it. I cannot focus the text field in the forgot password page and I don't think that is "working as intended" and I shouldn't have to create a focus node for standard behavior. This should probably be reopened.

**Comment by chunhtai** [comment] 2021-01-12 17:39
@zakton5 can you provide a reproducible example?

**Comment by zakton5** [comment] 2021-01-12 23:20
@chunhtai https://github.com/zakton5/flutter-router-text-field-focus-issue

Just run the app and attempt to focus the fields on the login form. Then tap forgot password and attempt to use the single field on that page. You can't focus it. This was only tested on iOS btw.

**Comment by chunhtai** [comment] 2021-01-12 23:55
Thanks, I will look into it

**Comment by chunhtai** [comment] 2021-01-13 00:46
I can't reproduce it in iOS on both emulator and real device the email field does receive focus when i tap it

**Comment by zakton5** [comment] 2021-01-13 17:22
@chunhtai The email field on the login page or the forgot password page?

**Comment by chunhtai** [comment] 2021-01-13 17:34
This is what i did

# no autofocus
1. run app
2. click email in login page to bring up keyboard focus
3. click forget password
4. click email in forget password
5. email does receive keyboard focus

# with autofocus
1. run app
2. click email in login page to bring up keyboard focus
3. click forget password
5. email does receive auto keyboard focus
6. click back to login page
7. click forget password
8. email still receives auto keyboard focus

**Comment by zakton5** [comment] 2021-01-13 17:50
@chunhtai Sure enough it now works. 100% this did not work yesterday on my iOS simulator though. I'm very confused. It also works in my actual app now whereas yesterday it did not work no matter what I did.

**Comment by chunhtai** [comment] 2021-01-13 18:04
closing as not reproducible

**Closed by chunhtai** 2021-01-13 18:04 UTC
Labels: a: text input, f: material design, f: routes, framework, passed first triage
