### ISSUE TITLE
java.lang.NoClassDefFoundError: com.google.firebase.FirebaseApp

### ISSUE THREAD

**Issue by gofur** [flutter/flutter#42822] opened 2019-10-16 06:28 UTC
i have problem
`FATAL EXCEPTION: main java.lang.NoClassDefFoundError: com.google.firebase.FirebaseApp at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.1.0:53) at android.content.ContentProvider.attachInfo(ContentProvider.java:1214) at android.content.ContentProvider.attachInfo(ContentProvider.java:1189) at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.1.0:47) at android.app.ActivityThread.installProvider(ActivityThread.java:5119) at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665) at android.app.ActivityThread.access$1400(ActivityThread.java:159) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:176) at android.app.ActivityThread.main(ActivityThread.java:5419) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:525) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) at dalvik.system.NativeStart.main(Native Method)`

Device: Samsung Galaxy S3
OS : Android 4.3

anyone can help?

**Comment by BondarenkoStas** [comment] 2019-10-16 10:40
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1132

**Closed by BondarenkoStas** 2019-10-16 10:40 UTC
