### ISSUE TITLE
flutter test --coverage does not mark if statements as covered

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#49895] opened 2020-01-31 17:40 UTC
![image](https://user-images.githubusercontent.com/21172855/73561302-097a2780-4459-11ea-9f77-d78bd2a84b80.png)

The if null checks are not covered. 

What am I doing wrong?

This is my test
```
void main() {
  ListStringConverter sut;
  setUp(() {
    sut = const ListStringConverter();
  });

  group('test ListStringConverter default state', () {
    test('to string', () async {
      const array = ['test1', 'test2'];
      final data = sut.mapToSql(array);
      expect(data, equals('["test1","test2"]'));
    });

    test('to object', () async {
      const arrayString = '["test1","test2"]';
      final data = sut.mapToDart(arrayString);
      expect(data.isNotEmpty, true);
      expect(data.length, equals(2));
      expect(data[0], equals('test1'));
      expect(data[1], equals('test2'));
    });
  });

  group('test ListStringConverter null checks', () {
    test('to string', () async {
      final data = sut.mapToSql(null);
      expect(data, isNull);
    });

    test('to object', () async {
      final data = sut.mapToDart(null);
      expect(data, isNull);
    });
  });
}

```

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-BE)
    • Flutter version 1.12.13+hotfix.5 at /Users/vanlooverenkoen/flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • F2704E51-185C-4E5F-BC54-8FB1BA3C43BE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.1 19B88
    • Chrome            • chrome                               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server        • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment] 2020-01-31 17:43
Duplicate of https://github.com/flutter/flutter/issues/46868

**Comment by vanlooverenkoen** [comment] 2020-01-31 17:49
@jonahwilliams  I get why it is a duplicate for the const variable but not for the if statement?

**Comment by jason-simmons** [comment] 2020-01-31 19:08
See https://github.com/dart-lang/coverage/issues/248 for discussion of how Dart coverage handles if statements.

**Comment by jonahwilliams** [comment] 2020-02-16 18:12
Discussion should take place in dart-lang/coverage#248

**Closed by jonahwilliams** 2020-02-16 18:12 UTC
Labels: dependency: dart
