### ISSUE TITLE
`Color.lerp` does not maintain equality

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#155803] opened 2024-09-27 03:40 UTC
## Use case

I'd like to make sure a widget only rebuilds when `colorScheme.primary` changes.

<br>

## Test

```dart
import 'dart:ui';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('Color can lerp and maintain equality with itself', () {
    const color = Color(0xFF123456);

    expect(Color.lerp(color, color, 0.0), color);
    expect(Color.lerp(color, color, 0.1), color);
    expect(Color.lerp(color, color, 0.2), color);
    expect(Color.lerp(color, color, 0.3), color);
    expect(Color.lerp(color, color, 0.4), color);
    expect(Color.lerp(color, color, 0.5), color);
    expect(Color.lerp(color, color, 0.6), color);
    expect(Color.lerp(color, color, 0.7), color);
    expect(Color.lerp(color, color, 0.8), color);
    expect(Color.lerp(color, color, 0.9), color);
  });
}
```

The test fails due to tiny floating point rounding errors 😃 😃

**Comment by matanlurey** [comment] 2024-09-27 19:04
We could make `Color.lerp(a, a)` always return `a` but I doubt that is what you are asking; the problem is that Color now stores the underlying data as floating point numbers (for wider color ranges), and of course floating point numbers cannot be perfectly maintained the way fixed point integers were.

A few ideas (not mutually exclusive):

- Add a note on [`Color`](https://github.com/flutter/engine/blob/f21f2b232b8a1b0b09c322e5bbe18244519b99e1/lib/ui/painting.dart#L85) that explains how equality now works, and what to do.
- Add a method, such as [`Color.isCloseTo`] directly on the class
- Remove equality and hashCode entirely from the class, given it is unlikely to be stable in the same way it was before

Defer of course to @gaaclarke who has been leading the color improvement effort.

**Comment by gaaclarke** [comment] 2024-09-27 20:06
Hey @nate-thegrate, this is expected behavior and is addressed in the breaking change notice: https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework#equality

The only guarantee we should make with respect to colors made with the 8 bit-per-pixel constructors is that unadulterated they will remain equal (`Color(0xaabbccdd) == Color(0xaabbccdd)`).  In practice, integer addition, subtraction and multiplication should be fine for small numbers.  It's the division here that messes things up.

> A few ideas (not mutually exclusive):
> 
> Add a note on [Color](https://github.com/flutter/engine/blob/f21f2b232b8a1b0b09c322e5bbe18244519b99e1/lib/ui/painting.dart#L85) that explains how equality now works, and what to do.

I'm open to this.  It could mention `isSameColorAs `.

> Add a method, such as [Color.isCloseTo] directly on the class

Given the times this has come up has been in tests I would rather just lean into `isSameColorAs`.

> Remove equality and hashCode entirely from the class, given it is unlikely to be stable in the same way it was before

I think developers can manage.  What Nate didn't show was the error message you get when these equality tests fail.  I think the solution is pretty obvious when you see what prints out (something like `expected Color(alpha: 1.000, red: 0.9999, green: 1.000, blue: 1.000), but got Color(alpha: 1.000, red: 1.000, green: 1.000, blue: 1.000)`).

**Comment by gaaclarke** [comment] 2024-09-27 20:35
> In Nate's case, it's in his actual code - he wants to use equality to avoid widget rebuilds.

Okay, in that case I think it's up to the user to define their own criteria for color closeness.  My preference is that we leave that out of `dart:ui` since there are a lot of different ways people could define closeness of colors, and it's usually a couple of lines.

Like should `Color.from(alpha: 1, red:1, blue: 0, green: 0).isCloseTo(Color.from(alpha: 1, red: 0.9175, blue: 0.2004, green: 0.1385)) == true`.  They are the same color, but in different color spaces.  Or how about using vector distance?  Or converting to a colorspace that better matches perception like XYZ to do comparison?  I think anything beyond literal bitwise equality should be left to users of Flutter.

**Comment by nate-thegrate** [comment] 2024-09-27 20:50
Perhaps instead of something in `dart:ui`, this issue could be fixed with a change to the color scheme implementation:

```dart
class ColorScheme {
  final Color primary;
  final Color onPrimary;
  // ...

  @override
  bool operator==(Object other) {
    if (other is! ColorScheme || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return other.primary.isCloseTo(primary)
        && other.onPrimary.isCloseTo(onPrimary)
        // etc.
  }

  @override
  int get hashCode => // ???
}
```

<br><br>

IMO the easiest change would be to add a guard statement to `Color.lerp`:

```diff
  static Color? lerp(Color? x, Color? y, double t) {
    assert(x?.colorSpace != ColorSpace.extendedSRGB);
    assert(y?.colorSpace != ColorSpace.extendedSRGB);
+   if (t == 0.0 || x == y) return x;
+   if (t == 1.0) return y;
    // ...
  }
```

Interested to hear thoughts!

**Comment by nate-thegrate** [comment] 2024-09-27 21:05
I bet https://github.com/flutter/engine/pull/55496 would help several folks out, thanks!

If there's a reason we'd want to avoid guard statements in `Color.lerp`, it wouldn't be a huge deal, since it'd be easy to just add them to a private `_lerpColor()` function in **color_scheme.dart**.

**Comment by nate-thegrate** [comment] 2024-09-27 23:28
> - Remove equality and hashCode entirely from the class, given it is unlikely to be stable in the same way it was before

I've put some thought into this idea—given `Color`'s ubiquity, it'd be nice to reduce the amount of bloat in the class if possible—but there is an advantage to retaining the `==` / `hashCode` implementations:

```dart
final a = Colors.grey.withValues(alpha: 0.5);
final b = Colors.grey.withValues(alpha: 0.5);

a == b; // true
```

There are still spots where you have identical configuration on non-identical `Color` objects, so the equality implementation is nice for that.

**Comment by matanlurey** [comment] 2024-11-12 23:41
It sounds like we've decided the docstring update is what we'll do at this time.

**Closed by matanlurey** 2024-11-12 23:41 UTC
Labels: c: performance, a: annoyance, P2, fyi-design, team-engine, triaged-engine
